#
# 北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北?
#
# Text labels and messages used by EDITOR.C
#
# (These MUST match "text message" enumeration on the top of EDITOR.C)
#
# 北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北?
#
#
{100}{}{DONE}
{101}{}{OPTIONS}
{102}{}{CANCEL}
{103}{}{PRINT}
{104}{}{AGE}
{105}{}{SEX}
{106}{}{NAME}
{107}{}{MALE}
{108}{}{FEMALE}
{109}{}{PERKS}
{110}{}{KARMA}
{111}{}{KILLS}
{112}{}{SKILL POINTS}
{113}{}{Level:}
{114}{}{Exp:}
{115}{}{Next Level:}
{116}{}{CHAR POINTS}
{117}{}{SKILLS}
{118}{}{You must use all character points} # 1
{119}{}{before starting the game!}         # 2
#
{120}{}{Character Points}
{121}{}{Amount of free character points that can be added to one of the basic stats.}
{122}{}{Next Level}
{123}{}{The amount of experience points needed to move up to the next level.}
{124}{}{Perks}
{125}{}{Karma}
{126}{}{Kills}
{127}{}{Perks add additional abilities. Every third experience level, you can choose one perk.}
{128}{}{These are the effects of the choices you make during the game.}
{129}{}{A counter that keeps track of the type and numbers of creatures you have slaughtered, or have seen killed in your presence.}
{130}{}{Skill Points}
{131}{}{Use free skill points to increase the level of a skill.  As you get better at a given skill, however, it takes more points to raise that skill.  Mastering a skill can take a lot of time and effort.}
#
{132}{}{At maximum level.}        # 1
{133}{}{Unable to increment it.}  # 2
{134}{}{At minimum level.}        # 1
{135}{}{Unable to decrement it.}  # 2
{136}{}{Not enough skill points available.}
{137}{}{Base:}
{138}{}{TAG SKILLS}
{139}{}{OPTIONAL TRAITS}
{140}{}{You already have the maximum of} # 1
{141}{}{three tag skills!}               # 2
{142}{}{You must select all tag skills}  # 1
{143}{}{before starting the game!}       # 2
{144}{}{Tag Skills}
{145}{}{Tag skills are skills your character specializes in.  Each tag skill gains +20%, and increases twice as fast.  You must pick three tag skills.}
{146}{}{Optional Traits}
{147}{}{Optional traits describe your character in more detail.  All traits will have positive and negative effects.  You may choose up to two traits during creation.}
{148}{}{You already have the maximum of} # 1
{149}{}{two traits!}                     # 2
{150}{}{Skills}
{151}{}{Skills are learned knowledge.  Skills increase by experience, or during the course of the game by special events.  The higher the skill level, the better you are at that skill.}
#
{152}{}{PICK A PERK}
{153}{}{PICK A NEW TRAIT}
{154}{}{LOSE A TRAIT}
{155}{}{PICK A NEW TAG SKILL}
{156}{}{TRAITS}
#
{157}{}{All stats must be between 1 and 10} # 1
{158}{}{before starting the game!}          # 2
# Fallout 2:
{160}{}{Warning: You haven't changed your player} # 1
{161}{}{name.  Use this character anyway?}        # 2

{175}{}{Next Lvl:}  # Short for Level:


#
# Abbreviated basic stat levels
#
{200}{}{V.Bad}  # Terrible
{201}{}{Bad}    # Bad
{202}{}{Poor}   # Poor
{203}{}{Fair}   # Fair
{204}{}{Avrg}   # Average
{205}{}{Good}   # Good
{206}{}{V.Good} # Very Good
{207}{}{Great}  # Great
{208}{}{Exclnt} # Excellent
{209}{}{Heroic} # Heroic

#
# Abbreviated Derived/Non Derived stat names
#
{300}{}{Hit Points}
{301}{}{Action Points }
{302}{}{Armor Class}
{303}{}{Unarmed Damage}
{304}{}{Melee Damage}
{305}{}{Damage Res.  }
{306}{}{Poison Res.   }
{307}{}{Radiation Res.}
{308}{}{Sequence}
{309}{}{Healing Rate}
{310}{}{Critical Chance}
{311}{}{Carry Weight}
{312}{}{Poisoned}
{313}{}{Radiated}
{314}{}{Eye Damage}
{315}{}{Crippled Right Arm}
{316}{}{Crippled Left Arm}
{317}{}{Crippled Right Leg}
{318}{}{Crippled Left Leg}

#
# Damage info texts
#
# Poisoned
{400}{}{Your character has been poisoned.  Poison will do damage over a period of time, until cured or it passes from your system.}
# Radiation
{401}{}{Your character is suffering from a significant amount of Radiation poisoning.  The more radiation damage, the more deadly the effect.}
# Eye Damage
{402}{}{This means your character has been seriously hit in one or both of your eyes.  This affects your Perception.}
# Crippled right arm
{403}{}{The right arm has been severely hurt, and cannot function well.  If one arm has been crippled, you cannot use two-handed weapons.  If both arms have been crippled, you cannot attack with weapons.}
# Crippled left arm
{404}{}{Your character's left arm has been severely hurt, and cannot function well.  If one arm has been crippled, you cannot use two-handed weapons.  If both arms have been crippled, you cannot attack with weapons.}
# Crippled right leg
{405}{}{Your character has a crippled right leg.}
# Crippled left leg
{406}{}{Your character has a crippled left leg.}

# Month strings
{500}{}{January}
{501}{}{February}
{502}{}{March}
{503}{}{April}
{504}{}{May}
{505}{}{June}
{506}{}{July}
{507}{}{August}
{508}{}{September}
{509}{}{October}
{510}{}{November}
{511}{}{December}

#
# Option menu text
#
{600}{}{SAVE}
{601}{}{LOAD}
{602}{}{PRINT TO FILE}
{603}{}{ERASE}
{604}{}{DONE}
{605}{}{Are you sure you want to erase}      # line 1
{606}{}{the current character?}                 # line 2
{607}{}{ was successfully saved.}
{608}{}{ was successfully loaded.}
{609}{}{already exists.}
{610}{}{Do you wish to overwrite?}
{611}{}{Error saving }
{612}{}{Error loading }
{613}{}{Character file invalid.}
{614}{}{Character data invalid.}
{615}{}{Error reading file list!}
{616}{}{PRINT}
{617}{}{PLAYER}
{618}{}{BLANK.GCD}

#
# ASCII text file printing text
#
{620}{}{FALLOUT}                   # Title line 1
{621}{}{VAULT-13 PERSONNEL RECORD} # Title line 2
{622}{}{hours} # Title line 3
# -
# -
#{000}{}{      Strength: 00        Hit Points: 000/000          Sequence: 00}
#{000}{}{    Perception: 00       Armor Class: 000          Healing Rate: 00}
#{000}{}{     Endurance: 00     Action Points: 000       Critical Chance: 000%}
#{000}{}{      Charisma: 00      Melee Damage: 000          Carry Weight: 000 lbs.}
#{000}{}{  Intelligence: 00       Damage Res.: 000%}
#{000}{}{       Agility: 00    Radiation Res.: 000%}
#{000}{}{          Luck: 00       Poison Res.: 000%}
#
{623}{}{ ::: Statistics :::}
{624}{}{       Strength:}
{625}{}{        Hit Points:}
{626}{}{        Sequence:}
# -
{627}{}{     Perception:}
{628}{}{       Armor Class:}
{629}{}{        Healing Rate:}
# -
{630}{}{      Endurance:}
{631}{}{     Action Points:}
{632}{}{      Critical Chance:}
# -
{633}{}{       Charisma:}
{634}{}{      Melee Damage:}
{635}{}{         Carry Weight:}
# -
{636}{}{   Intelligence:}
{637}{}{       Damage Res.:}
# -
{638}{}{        Agility:}
{639}{}{    Radiation Res.:}
# -
{640}{}{           Luck:}
{641}{}{       Poison Res.:}
# -
# -
#{000}{}{ Name: 01234567890        Age: 00         Gender: Female}
{642}{}{  Name:}
{643}{}{Age:}
{644}{}{               Gender:}
{645}{}{Male}
{646}{}{Female}
#-
#{000}{}{ Level: 00                 Exp: 000,000    Next Level: 000,000}
{647}{}{ Level:}
{648}{}{                Exp:}
{649}{}{Next Level:}
#-
{650}{}{ ::: Traits :::}
{651}{}{ ::: Perks :::}
{652}{}{ ::: Karma :::}

#-
{653}{}{ ::: Skills :::                ::: Kills :::}
#-
{654}{}{ ::: Inventory :::}
#-
{655}{}{                                      Total Weight:}
{656}{}{ ::: Reliances :::}
{657}{}{ ::: Reputation :::}

#
# Karma name strings
#
{1000}{}{Reputation (General) }
{1001}{}{Berserker}
{1002}{}{Champion}
{1003}{}{Childkiller}
{1004}{}{Nuka Cola reliance}
{1005}{}{Buffout reliance}
{1006}{}{Mentats reliance}
{1007}{}{Psycho reliance}
{1008}{}{RadAway reliance}
{1009}{}{Alcohol reliance}
{1010}{}{Jet reliance}
{1011}{}{Game addiction}
{1012}{}{Child killer}
{1013}{}{The Death Machine}
{1014}{}{The Great Hunter}
{1015}{}{Monster Slayer}
{1016}{}{The peace-loving wanderer}
{1017}{}{Dedicated to the Brotherhood of Steel}
{1018}{}{Clerk of the Brotherhood of Steel}
{1019}{}{Knight of the Brotherhood of Steel}
{1020}{}{Paladin of the Brotherhood of Steel}
{1021}{}{Scout of the Brotherhood of Steel}
{1022}{}{Traitor to the Brotherhood of Steel}
{1023}{}{The Arizona Ranger}
{1024}{}{Follower of Fire}
{1025}{}{Road Warrior}
{1026}{}{Runaway slave}
{1027}{}{Reborn}
{1028}{}{Keeper of Traditions}
{1029}{}{The destroyer of traditions}
{1030}{}{Professional fighter}

#
# Karma description strings
#
{1100}{}{This is a ranged stat that represents your general reputation. The higher the number, the better known and respected you are. If your rep is negative, you are hated by some for your evil actions.}
{1101}{}{You have done many despicable things. And you will probably do even more. Honest people will avoid you, but people on the other side of the concept of goodness and honor may accept you as one of their own.}
{1102}{}{Your actions have made you a folk hero. The news of the war that you declared on evil and meanness spread throughout the region. Honest people will respect you more.}
{1103}{}{ }
{1104}{}{You thoroughly enjoy Nuka-Cola, the pop of the post-nuclear world.}
{1105}{}{You are reliant to the chem Buffout. You must take this chem on an ongoing basis or suffer the effects of withdrawal.}
{1106}{}{You are suffering from Mentat reliant. You must take this particular chem or suffer withdrawal.}
{1107}{}{You have a chem reliant. If you do not take Psycho on a regular schedule, you will suffer. If you do, others will suffer.}
{1108}{}{Your body has become reliant on Radaway. While not life threatening, you must take it regularly.}
{1109}{}{You have a problem with alcohol. Actually, you have many problems with your drinking habits.}
{1110}{}{You have a chem reliant. You must take Jet on a regular basis.}
{1111}{}{Tragically, you are reliant on the Garnering. You are constantly in search of new expansions.}
{1112}{}{You killed children, flowers in the ruins of the world. Such actions are generally not welcome. You are a bad, very bad person.}
{1113}{}{You've killed a lot of people. And they did it with taste. Not everyone likes people like you, even in a post-nuclear world.}
{1114}{}{You are a born hunter. You've beaten so many wild animals to death that you've lost count.}
{1115}{}{Cleansing the modern world from all kinds of mutants has become your calling. Some people admire you, others you frighten.}
{1116}{}{You have reached level 12, and very few people (or even none) have died due to your fault. With such an attitude towards life, it is a miracle that you yourself are still alive.}
{1117}{}{You have joined the Brotherhood of Steel. And although your training is not yet complete, this already says a lot about your capabilities.}
{1118}{}{You have achieved significant success in your position, benefiting the overall goals of the Brotherhood. Therefore, the Elders decided to recognize you as an accomplished scribe.}
{1119}{}{You have achieved significant success in your position, benefiting the overall goals of the Brotherhood. Therefore, the Elders decided to recognize you as an accomplished knight.}
{1120}{}{You have achieved significant success in your position, benefiting the overall goals of the Brotherhood. Therefore, the Elders decided to recognize you as an accomplished paladin.}
{1121}{}{You have achieved significant success in your position, benefiting the overall goals of the Brotherhood. Therefore, the Elders decided to recognize you as an accomplished scout.}
{1122}{}{You betrayed the Brotherhood of Steel after all they did for you. The brotherhood does not forgive this. Never.}
{1123}{}{You have officially been accepted into the ranks of the Rangers. Now it is your responsibility to create order in the Wasteland.}
{1124}{}{The Cult of Fire has accepted you into its narrow circle of initiates. Few have succeeded.}
{1125}{}{Transporters now consider you one of their people and are ready to come to your aid from now on.}
{1126}{}{You are now an outlaw. You will have to constantly hide from your pursuers until you manage to get your manumission from your slave owner.}
{1127}{}{You... have changed. You have become a new person. It makes you look at yourself in a new way. And to the whole world around us.}
{1128}{}{You have rejected progress in favor of maintaining tradition. By doing this, you have inspired the people of the Villa and proven your dedication to the ideals of the community.}
{1129}{}{You have rejected tradition in favor of progress. You have your reasons, but most of the Villa's residents are unlikely to agree with you on this issue.}
{1130}{}{You are the heavyweight champion of Phoenix. You have gained fame, respect and love from thousands of fans.}

#
# Town reputations
#
{2000}{}{Idolized}
{2001}{}{Liked}
{2002}{}{Accepted}
{2003}{}{Neutral}
{2004}{}{Antipathy}
{2005}{}{Hated}
{2006}{}{Vilified}

{2100}{}{Everyone in this area would like to be you. You're the toast-of-the-town and are held up as a shining example of all that a person can be.}
{2101}{}{People wave, and greet you, wherever you go in this area. Everyone has heard talk of you, and they like what they've heard.}
{2102}{}{Although, you're not greeted with open arms, most people in this area will at least nod in acknowledgment when you meet. You fit in as well as most.}
{2103}{}{Though normally suspicious of strangers, the people of this area haven't made up their minds about you yet.}
{2104}{}{You're just another out-of-towner in this area. Probably up to no good.}
{2105}{}{You've proven to the people in this area that their initial distrust was well founded. People in this area look at you and mutter to one another when you come near. They know you're up to no good.}
{2106}{}{Staring and muttering, some cross the street to avoid walking near you, while others, spit and turn away when you come near. Everyone knows that you're one of the worst things that's ever slithered into this area.}

#
# Karma status strings
#
{3000}{}{Savior of the Damned}
{3001}{}{Guardian of the Wastes}
{3002}{}{Shield of Hope}
{3003}{}{Defender}
{3004}{}{Wanderer}
{3005}{}{Betrayer}
{3006}{}{Sword of Despair}
{3007}{}{Scourge of the Wastes}
{3008}{}{Demon Spawn}

#
# Karma section titles.
#
{4000}{}{Reputation}
{4001}{}{Reliance}

#
# Karma section descriptions.
#
{4100}{}{Represents your reputation for a particular location.}
{4101}{}{Things you have become reliant to.}

#
# Special Demo version only text
#
{5000}{}{Sorry, you can only print your}   # 1
{5001}{}{character in the full version.}   # 2
{5002}{}{Sorry, you can only save your}    # 1
{5003}{}{character in the full version.}   # 2
{5004}{}{Sorry, you can only load a saved} # 1
{5005}{}{character in the full version.}   # 2
{5006}{}{CHEAT MODE}
{5007}{}{Not available in demo.}