#
# Inventory messages from inventry.c
#
{0}{}{ST}
{1}{}{PE}
{2}{}{EN}
{3}{}{CH}
{4}{}{IN}
{5}{}{AG}
{6}{}{LK}
{7}{}{Hit Points}
{8}{}{Armor Class}
{9}{}{  Normal}
{10}{}{  Laser}
{11}{}{  Fire}
{12}{}{  Plasma}
{13}{}{  Explode}
{14}{}{No item}
{15}{}{Dmg:}
{16}{}{Rng:}
{17}{}{Ammo:}
{18}{}{(Not worn)}
{19}{}{You don't have enough action points to use inventory.}
{20}{}{Total Wt:}
{21}{}{MOVE ITEMS}
{22}{}{ALL}
{23}{}{SET TIMER}
{24}{}{Unarmed dmg:}
{25}{}{You cannot pick that up. You are at your maximum weight capacity.}
{26}{}{There is no space left for that item.}
{27}{}{OK, that's a good trade.}
{28}{}{No, your offer is not good enough.}
{29}{}{You gain %d experience points for successfully using your Steal skill.}
{30}{}{Wt.}
{31}{}{Sorry, you cannot carry that much.}
{32}{}{Sorry, that's too much to carry.}

{50}{}{You can't find anything to take from that.}