#
# Item.c messages
#
{1}{}{You gained %d %s.}
{2}{}{You lost %d %s.}
{3}{}{You feel better.}
{4}{}{You suffer a fatal heart attack from chem overdose.}
{5}{}{%s has no charges left.}
{6}{}{%s is on.}
{7}{}{%s is off.}
{8}{}{You pass the Geiger counter over your body. The rem counter reads: %d}
{9}{}{This item can only be used from the interface bar.}
{10}{}{Nothing happens.}


# Fallout 2:
{50}{}{That didn't seem to do that much.}


#
# Fallout 2
#
{500}{}{There is not enough light to recharge this item.}
#
{600}{}{%s succumbs to the adverse effects of chems.}

# Weapon Damage strings
{800}{}{Light}
{801}{}{Medium}
{802}{}{Heavy}
{803}{}{Extreme}
# Weapon Range strings
{820}{}{Short}
{821}{}{Medium}
{822}{}{Long}