{0}{}{** Autoloot for the main character is disabled **}
{1}{}{** Main character autoloot enabled **}
{100}{}{As you wish.}
{101}{}{On my way.}
{102}{}{Okay.}
{103}{}{As you wish.}
{104}{}{Okay, okay.}
{105}{}{Right away.}
{110}{}{Woof!}
{111}{}{Woof! Woof!}
{1100}{}{Put your weapon away, }
{1101}{}{People, put your weapons away.}
{1200}{}{Heal up, }
{1201}{}{Heal quickly, everyone.}
{1210}{}{uses super stim.}
{1211}{}{uses stimulant.}
{1212}{}{heals}
{1213}{}{units health.}
{1214}{}{cure fails.}
{1215}{}{run out of medicine.}
{1400}{}{Gather your goods, }
{1410}{}{Enough. Back, }
{1415}{}{I don't have enough room for these things.}
{1420}{}{Done.}
{1421}{}{I'm done.}
{1422}{}{Everything is ready.}
{1423}{}{That's it.}
{1424}{}{No more to collect.}
{1499}{}{All partners are overloaded and cannot collect.}
{1500}{}{Come closer,}
{1501}{}{Everyone gather!}
{1600}{}{Move away,}
{1601}{}{Everyone run away!}
{1900}{}{Load normal ammo,}
{1901}{}{Load some normal ammo everyone!}
{1910}{}{Load armor-piercing ammo,}
{1911}{}{Load armor-piercing ammo everyone!}
{2000}{}{Let's shoot in bursts!}
{2001}{}{Don't shoot in bursts!}
{2002}{}{Partners: burst fire is allowed.}
{2003}{}{Partners: burst fire is prohibited.}