{100}{}{Rocket}
{200}{}{Plasma Ball}
{300}{}{Explosion}
{400}{}{Blood}
{500}{}{No-Trans hex}
{600}{}{knife}
{700}{}{spear}
{800}{}{EMP Explosion}
{900}{}{Laser Blast}
{1000}{}{Plasma Blast}
{1100}{}{Explosion}
{1200}{}{Scroll Blocker}
{1300}{}{Electricity Bolt}
{1400}{}{Explosion}
{1500}{}{Explosion}
{1600}{}{Exit Grid}
{1700}{}{Exit Grid}
{1800}{}{Exit Grid}
{1900}{}{Exit Grid}
{2000}{}{Exit Grid}
{2100}{}{Exit Grid}
{2200}{}{Exit Grid}
{2300}{}{Exit Grid}
{2400}{}{Flare}
{2500}{}{Grenade}
{2600}{}{Rock}
{2700}{}{Explosion}
{2800}{}{Explosion}
{2900}{}{Explosion}
{3000}{}{Molotov Cocktail}
{3100}{}{Exit grid}
{3200}{}{Exit grid}
{3300}{}{Exit grid}
{3400}{}{Exit grid}
{3500}{}{Exit grid}
{3600}{}{Exit grid}
{3700}{}{Exit grid}
{3800}{}{Exit grid}
{3900}{}{Exit grid}
{4000}{}{Exit grid}
{4100}{}{Exit grid}
{4200}{}{Exit grid}
{4300}{}{Exit grid}
{4400}{}{Exit grid}
{4500}{}{Exit grid}
{4600}{}{Exit grid}
{4700}{}{Robot Rocket}
{4800}{}{Boom!}
{4900}{}{Plant thorn}
{5000}{}{Double plasma clot}
{5100}{}{Map border}
{5200}{}{Map border}
{5300}{}{Spitting acid}
{5400}{}{Air wave}