{100}{}{The male hero}
{101}{}{}
{200}{}{The female hero}
{201}{}{}
{300}{}{Area}
{301}{}{The radius of action is not more than 8 hexes.}
{400}{}{Rad-area}
{401}{}{The range of action is not more than 8 hexes.}
{500}{}{The Giant Ant}
{501}{}{A mutant ant of enormous size.}
{600}{}{Ant-soldier}
{601}{}{A mutant ant of enormous size.}
{700}{}{Rad-Ants}
{701}{}{A glowing mutant ant of enormous size.}
{800}{}{Mantis}
{801}{}{A deadly mantis of enormous size.}
{900}{}{The Giant Mantis}
{901}{}{A deadly mantis of incredibly huge size.}
{1000}{}{The Womb of mantises}
{1001}{}{A deadly mantis of incredibly huge size.}
{1100}{}{Mutant rat}
{1101}{}{A wild rat of unusually large size.}
{1200}{}{City rat}
{1201}{}{A disgusting rat of unusually large size.}
{1300}{}{Pig-rat}
{1301}{}{Hefty mutant pig-rat}
{1400}{}{The Mole Rat}
{1401}{}{Hefty mutant mole rat}
{1500}{}{The Rat King}
{1501}{}{The strongest and largest rodent you've ever come across.}
{1600}{}{Coyote}
{1601}{}{A ferocious descendant of wild coyotes.}
{1700}{}{Wild dog}
{1701}{}{A stray dog of mixed breed.}
{1800}{}{Pack leader}
{1801}{}{A strong dog, the leader of his pack.}
{1900}{}{Mountain Wolf}
{1901}{}{Bloodthirsty mountain wolf.}
{2000}{}{Radscorpion}
{2001}{}{A small mutant scorpion.}
{2100}{}{Radscorpion}
{2101}{}{A huge mutant scorpion.}
{2200}{}{Radscorpion-legend}
{2201}{}{An incredibly huge and dangerous mutant scorpion.}
{2300}{}{Pack Brahmin}
{2301}{}{A two-headed mutant cow with a load on its back.}
{2400}{}{The domesticated Brahmin}
{2401}{}{A tamed two-headed mutant cow.}
{2500}{}{Wild Brahmin}
{2501}{}{Wild two-headed mutant cow.}
{2600}{}{Exhausted Brahmin}
{2601}{}{Two-headed mutant cow, exhausted from malnutrition.}
{2700}{}{Predatory plant}
{2701}{}{A dangerous carnivorous plant.}
{2800}{}{Flyer}
{2801}{}{A disgusting creature bred in the laboratory.}
{2900}{}{Centaur}
{2901}{}{An evil creature bred in the laboratory.}
{3000}{}{El Monstro}
{3001}{}{A terrifying monster, the worst nightmare you could imagine.}
{3100}{}{El Gigante}
{3101}{}{A terrifying monster, the worst nightmare you could imagine.}
{3200}{}{El Diablo}
{3201}{}{A terrifying monster, the worst nightmare you could imagine.}
{3300}{}{Mr. Handy}
{3301}{}{An old robot with many functions.}
{3400}{}{Robobrain}
{3401}{}{An old robot with a brain as a processor.}
{3500}{}{Roboglaz}
{3501}{}{Security robot of the pre-war era.}
{3600}{}{Security robot}
{3601}{}{Powerful security robot.}
{3700}{}{Turret}
{3701}{}{Powerful security turret.}
{3800}{}{A reasonable ghoul}
{3801}{}{A disfigured person affected by a virus and radiation.}
{3900}{}{A reasonable ghoul}
{3901}{}{A disfigured person affected by a virus and radiation.}
{4000}{}{The Shrunken Ghoul}
{4001}{}{Wild unreasonable ghoul.}
{4100}{}{The Ripper}
{4101}{}{Wild unreasonable ghoul.}
{4200}{}{The Glowing Ripper}
{4201}{}{A wild, unintelligent ghoul, from which powerful rays of radiation emanate.}
{4300}{}{Sporonos}
{4301}{}{A creature infected with a plant virus.}
{4400}{}{The Ghost}
{4401}{}{A man who has lost his mind with a withered body. A non-working gas mask is hanging from his neck.}
{4500}{}{Boy}
{4501}{}{In front of you is a weak defenseless child.}
{4600}{}{Girl}
{4601}{}{In front of you is a weak defenseless child.}
{4700}{}{Savage}
{4701}{}{You see a red-skinned man in a loincloth.}
{4800}{}{Savage}
{4801}{}{You see a red-skinned woman in a loincloth.}
{4900}{}{The peasant}
{4901}{}{You see a tanned man.}
{5000}{}{Peasant woman}
{5001}{}{You see a tanned woman.}
{5100}{}{Citizen}
{5101}{}{You see a frail man.}
{5200}{}{The townswoman}
{5201}{}{You see a frail person.}
{5300}{}{Citizen}
{5301}{}{You see a city dweller.}
{5400}{}{The townswoman}
{5401}{}{You see a city dweller.}
{5500}{}{Citizen}
{5501}{}{You see a city dweller.}
{5600}{}{The townswoman}
{5601}{}{You see a city dweller.}
{5700}{}{Merchant}
{5701}{}{You see a local merchant.}
{5800}{}{Merchant}
{5801}{}{You see a local merchant.}
{5900}{}{Merchant}
{5901}{}{You see a merchant.}
{6000}{}{Merchant}
{6001}{}{You see a merchant.}
{6100}{}{Mercenary}
{6101}{}{You see a strong man.}
{6200}{}{A mercenary}
{6201}{}{You see a strong woman.}
{6300}{}{Mercenary}
{6301}{}{You see a strong man.}
{6400}{}{A mercenary}
{6401}{}{You see a strong woman.}
{6500}{}{Mercenary}
{6501}{}{You see a strong man in leather armor.}
{6600}{}{A mercenary}
{6601}{}{You see a strong woman in leather armor.}
{6700}{}{Mercenary}
{6701}{}{You see a strong man in metal armor.}
{6800}{}{A mercenary}
{6801}{}{You see a strong woman in metal armor.}
{6900}{}{Mercenary}
{6901}{}{You see a strong man in combat armor.}
{7000}{}{A mercenary}
{7001}{}{You see a strong woman in battle armor.}
{7100}{}{Ranger}
{7101}{}{You see a private ranger.}
{7200}{}{Ranger}
{7201}{}{You see a private ranger.}
{7300}{}{Veteran Ranger}
{7301}{}{You see a battle-hardened veteran ranger.}
{7400}{}{Ranger General}
{7401}{}{You see a strong gray-haired old man who has seen life in all its manifestations.}
{7500}{}{Clerk of the Brotherhood of Steel}
{7501}{}{}
{7600}{}{Clerk of the Brotherhood of Steel}
{7601}{}{}
{7700}{}{Scout of the Brotherhood of Steel}
{7701}{}{}
{7800}{}{Knight of the Brotherhood of Steel}
{7801}{}{}
{7900}{}{Paladin of the Brotherhood of Steel}
{7901}{}{}
{8000}{}{Supreme Paladin}
{8001}{}{}
{8100}{}{Preacher of Fire}
{8101}{}{}
{8200}{}{Follower of Fire}
{8201}{}{}
{8300}{}{Lord of the Phoenix}
{8301}{}{}
{8400}{}{Scientist}
{8401}{}{}
{8500}{}{A follower of the Apocalypse}
{8501}{}{}
{8600}{}{A follower of the Apocalypse}
{8601}{}{}
{8700}{}{ Tinker}
{8701}{}{}
{8800}{}{ Tinker}
{8801}{}{}
{8900}{}{Master Hard}
{8901}{}{}
{9000}{}{Crazy Bitch}
{9001}{}{Here is the leader of the Jackal tribe.}
{9100}{}{Padre}
{9101}{}{This is your father. It's definitely him.}
{9200}{}{Granny}
{9201}{}{}
{9300}{}{Geronimo}
{9301}{}{Here is the village elder in his national attire.}
{9400}{}{The Mysterious Stranger}
{9401}{}{Here is A Mysterious Stranger. He seems to be quite friendly to you.}
{9500}{}{Mr. Kogan}
{9501}{}{}
{9600}{}{ Administrator}
{9601}{}{}
{9700}{}{Roy Faber}
{9701}{}{}
{9800}{}{Arthur}
{9801}{}{}
{9900}{}{The Overseer's Ghost}
{9901}{}{A horribly disfigured creature in a torn jumpsuit.}
{10000}{}{Advisor}
{10001}{}{This person confidently sits at the post of the overseer and studies you down.}
{10100}{}{Don Diego}
{10101}{}{Here is a sexy man in an expensive suit with an elegant pattern.}
{10200}{}{Miguel}
{10201}{}{}
{10300}{}{Angelo}
{10301}{}{}
{10400}{}{Jock}
{10401}{}{}
{10500}{}{Jock}
{10501}{}{}
{10600}{}{Savage}
{10601}{}{}
{10700}{}{Canelo}
{10701}{}{}
{10800}{}{Big Mario}
{10801}{}{}
{10900}{}{Citizen}
{10901}{}{}
{11000}{}{The townswoman}
{11001}{}{}
{11100}{}{General Sarabia}
{11101}{}{You see a man in a spectacular combat outfit.}
{11200}{}{Red Rider}
{11201}{}{Here is an unshaven man with a revolver. He looks at you with obvious disgust.}
{11300}{}{Ben}
{11301}{}{Hiding his face with a mask, this man inspires fear in his subordinates.}
{11400}{}{Barclay}
{11401}{}{}
{11500}{}{Levi}
{11501}{}{Here is a mysterious figure in a gas mask and a badly worn hoodie. He speaks importantly and judiciously.}
{11600}{}{Super Mutant}
{11601}{}{Hefty green mutant.}
{11700}{}{The Ghost}
{11701}{}{You see... the soul of a man burned in a nuclear flame!}
{11800}{}{The Ghost}
{11801}{}{You see... the soul of a man burned in a nuclear flame!}
{11900}{}{Wang Chun}
{11901}{}{You see either a plant or a person. It's already hard to say.}
{12000}{}{Priestess}
{12001}{}{}
{12100}{}{ Priest}
{12101}{}{}
{12200}{}{ La Garra}
{12201}{}{A terrifying monster, the worst nightmare you could imagine.}
{12300}{}{Senior Assistant}
{12301}{}{You see a robot of the Senor Assistant series.}
{12400}{}{Jack}
{12401}{}{}
{12500}{}{ Eugene}
{12501}{}{}
{12600}{}{Diana}
{12601}{}{}
{12700}{}{Diana}
{12701}{}{}
{12800}{}{Diana}
{12801}{}{}
{12900}{}{Diana}
{12901}{}{}
{13000}{}{Arthur}
{13001}{}{}
{13100}{}{Arthur}
{13101}{}{}
{13200}{}{Arthur}
{13201}{}{}
{13300}{}{Barclay}
{13301}{}{}
{13400}{}{Barclay}
{13401}{}{}
{13500}{}{Barclay}
{13501}{}{}
{13600}{}{Jack}
{13601}{}{}
{13700}{}{Jack}
{13701}{}{}
{13800}{}{Jack}
{13801}{}{}
{13900}{}{Sancho}
{13901}{}{}
{14000}{}{Ugo}
{14001}{}{}
{14100}{}{Scolopendra}
{14101}{}{Giant Scolopendra.}
{14200}{}{Mexican}
{14201}{}{A man with a dark skin tone. He hides his head under a wide-brimmed hat.}
{14300}{}{A reasonable ghoul}
{14301}{}{A disfigured person affected by a virus and radiation.}
{14400}{}{A bunch}
{14401}{}{}
{14500}{}{ Fernando}
{14501}{}{}
{14600}{}{Beatrice}
{14601}{}{}
{14700}{}{El Temor Rojo}
{14701}{}{A terrifying monster, the worst nightmare you could imagine.}
{14800}{}{La Fantasma}
{14801}{}{A terrifying monster, the worst nightmare you could imagine.}
{14900}{}{Survivalist}
{14901}{}{}
{15000}{}{Mother Bates}
{15001}{}{}
{15100}{}{Merchant Sid}
{15101}{}{}
{15200}{}{Merchant Joshua}
{15201}{}{}
{15300}{}{Merchant Clark}
{15301}{}{}
{15400}{}{}
{15401}{}{}
{15500}{}{}
{15501}{}{}
{15600}{}{}
{15601}{}{}
{15700}{}{}
{15701}{}{}
{15800}{}{}
{15801}{}{}
{15900}{}{}
{15901}{}{}
{16000}{}{}
{16001}{}{}
{16100}{}{}
{16101}{}{}
{16200}{}{}
{16201}{}{}
{16300}{}{}
{16301}{}{}
{16400}{}{}
{16401}{}{}
{16500}{}{}
{16501}{}{}
{16600}{}{}
{16601}{}{}
{16700}{}{}
{16701}{}{}
{16800}{}{}
{16801}{}{}
{16900}{}{}
{16901}{}{}
{17000}{}{}
{17001}{}{}
{17100}{}{}
{17101}{}{}
{17200}{}{}
{17201}{}{}
{17300}{}{}
{17301}{}{}
{17400}{}{}
