##########################################################
#
# DESCRIPTIONS OF QUESTS IN PIP-BOY
# (start each new section with 100 and multiples of it)
#
##########################################################

#---------------------------------------------------------
# Villa
#---------------------------------------------------------

{100}{}{Learn about the raiders in the neighboring city}
{101}{}{Free your fellow tribesmen in Flagstaff}
{102}{}{Free your fellow tribesmen in Two-Sun}
{103}{}{To address the Community Council}
{104}{}{Find family heirlooms in the cellars}
{105}{}{One of the residents needs medical help}
{106}{}{Stop the invasion of rats}
{107}{}{Find and return the runaway child}
{108}{}{Drive the looters from the plantations}
{109}{}{Fix the weather station}
{110}{}{Eliminate the sect in Phoenix}
{111}{}{Find Chris, he's probably hiding somewhere}
{112}{}{The council decided to undermine the Flagstaff mines}
{113}{}{The council decided to destroy the machine in Garage City}
{114}{}{The Council believes that Villa needs allies}

#---------------------------------------------------------
# Flagstaff
#---------------------------------------------------------

{200}{}{Find Villa people in the Prisoner pen}
{201}{}{In any way to release the tribesmen from prison}
{202}{}{Rescue the tribesmen from the trap in the mine}
{203}{}{Repair the drilling robot}
{204}{}{Eliminate the rat king in the mine}
{205}{}{Someone attacks patrols in an abandoned area}
{206}{}{Take lunch to the mine administrator}
{207}{}{Mercenary Davis owed the bar a hundred caps}
{208}{}{Eliminate the infidel in the name of the Sacred Fire}
{209}{}{Cure a child of radiation sickness}
{210}{}{Drive the invaders from Randy's farm}
{211}{}{Find Miss Brandley's personal belongings}
{212}{}{To remove the supervisor of the Whip from his position}
{213}{}{Check out what's going on at Camp Winon}

#---------------------------------------------------------
# Garage- City
#---------------------------------------------------------

{300}{}{Stop the scavengers in the dorm}
{301}{}{Get Mr. Kogan the parts from the factory}
{302}{}{Participate in a deal with a caravan}
{303}{}{Lucas needs data from the computer in the garage}
{304}{}{Participate in a deal with a caravan}
{305}{}{Participate in the capture of a Brahmin}
{306}{}{Restore the trade route to San Brahmin}
{307}{}{Organize a trade route to the Ranger lands}
{308}{}{Organize the supply of alcohol from Flagstaff}
{309}{}{Stop fake tire production}
{310}{}{Find and return the welding machine}

#---------------------------------------------------------
# San- Brahmin
#---------------------------------------------------------

{400}{}{To help the leader in the conclusion of an alliance}
{401}{}{Missionaries offer the tribe a union}
{402}{}{Help the ranger drive away the missionaries}
{403}{}{Stop tequila production in Phoenix}
{404}{}{Clear the paddock of brahmin excrement}
{405}{}{Uncover the mystery of the Buried City}
{406}{}{Clear the oasis of radscorpions}
{407}{}{Protect the caravan on the way to Phoenix}
{408}{}{}
{409}{}{}

#---------------------------------------------------------
# Tu- San
#---------------------------------------------------------

{500}{}{Find a way to disable the force barrier}
{501}{}{Find your Padre in the Restricted Area}
{502}{}{Get the Villa people out of the Restricted Area}
{503}{}{The padre asks to convince Carlos (and in case of failure - to eliminate)}
{504}{}{The Tinkerers want to deactivate the security of the Restricted Area}
{505}{}{Find out who attacked the caravan and stop this threat}
{506}{}{Find the missing tinker in Casa Grande}
{507}{}{Cody experiences a personality conflict and asks to find his family in Casa Grande}
{508}{}{Get an energy cell for a peasant}
{509}{}{}

#---------------------------------------------------------
# Puerto-Penasco
#---------------------------------------------------------

{600}{}{Take Ulysses Grant's holodisk to Puerto Penasco}
{601}{}{Find the missing Brotherhood Squad in Inferno}
{602}{}{Paladin Bell suffers from a mental disorder}
{603}{}{Conduct reconnaissance in the south}
{604}{}{Eliminate the Rangers}
{605}{}{Participate in raids on bandit camps}
{606}{}{Conduct a reconnaissance in San Felipe}
{607}{}{}
{608}{}{}
{609}{}{}

#---------------------------------------------------------
# Rangers
#---------------------------------------------------------

{700}{}{Fix the water tank on the farm}
{701}{}{Spy needs Ranger radio code}
{702}{}{Repair the equipment at the power plant}
{703}{}{Escort a young mechanic from Garage City to serve at the power plant}
{704}{}{Expand the broadcast area of the radio station}
{705}{}{Take the report to the ranger in San Brahmin}
{706}{}{Escort a rogue family to the ferry}
{707}{}{Find the missing reconnaissance squad in the desert in the north}
{708}{}{Find out what happened to the residents of Quartz}
{709}{}{Collect cartographic data in Quartz}
{710}{}{Find out in Garage City what happened to the refugees}
{711}{}{Help Cadet Presley}
{712}{}{Find out the cause of the epidemic in the Aqueduct}
{713}{}{Find and kill the legendary Radscorpion}
{714}{}{Find the missing gear}
{715}{}{Assist the rebels in Phoenix}
{716}{}{Find the missing Aqueduct residents}
{717}{}{Conduct reconnaissance in Puerto Penasco}
{718}{}{}
{719}{}{}

#---------------------------------------------------------
# Phoenix
#---------------------------------------------------------

{800}{}{Learn about slaves from the Villa in Phoenix}
{801}{}{Find your Uncle Miguel in Phoenix}
{802}{}{Bring the heads of the chieftains of Los Panchos}
{803}{}{Kill the legendary shooter Gil McCord}
{804}{}{Investigate recent attacks on monks}
{805}{}{Infiltrate the ranks of the rebels}
{806}{}{Help George Crook in San Brahmin}
{807}{}{Eliminate George Crook}
{808}{}{Find an agent of the Liberation Party in the ruins}
{809}{}{Sabotage in the Cathedral commissioned by the Liberation Party}
{810}{}{The client will owe the casino a large amount of caps}
{811}{}{Return stolen emails}
{812}{}{The Red Cardinals gang is in trouble}
{813}{}{There was an accident at the nuclear power plant}
{814}{}{Iron Mike craves justice}
{815}{}{To help slum dwellers in their difficult fate}
{816}{}{}
{817}{}{}
{818}{}{}
{819}{}{}

#---------------------------------------------------------
# Fishermen's Village (Oil platform)
#---------------------------------------------------------

{900}{}{Stop the leak on the oil platform}
{901}{}{Cure patients from oil poisoning}
{902}{}{Thelma asks to find her uncle's memorabilia}
{903}{}{Bring the Geiger counter to the merchant}
{904}{}{Ruiz is looking for treasure}
{905}{}{To catch a creature that plunders fish caches}
{906}{}{Investigate a mysterious murder}

#---------------------------------------------------------
# Casa Grande
#---------------------------------------------------------

{1000}{}{Steve claims his rights to the bath}
{1001}{}{Sullivan will pay for the repair of the water pump}
{1002}{}{There was a mess in an abandoned bar}
{1003}{}{Robbers have appeared in Casa Grande}
{1004}{}{Save a resident at the railway station}
{1005}{}{Destroy the mainline fuel depot}
{1006}{}{The mayor pays for the head of the leader of the Blue Shields}
{1007}{}{}
{1008}{}{}
{1009}{}{}

#---------------------------------------------------------
# Hermosillo
#---------------------------------------------------------

{1100}{}{Return the radio to the Dominguez Ranch}
{1101}{}{Escort the prisoner to Puerto Penasco}

#---------------------------------------------------------
# San-Felipe (Old Lighthouse)
#---------------------------------------------------------

{1200}{}{Check out rumors about monsters in the graveyard of ships}
{1201}{}{Get rid of monsters}
{1202}{}{Repair the lighthouse}
{1203}{}{Find and save Gloria}

#---------------------------------------------------------
# Inferno
#---------------------------------------------------------

{1300}{}{Find Paladin Barkley's entire squad}
{1301}{}{Levi is trying to create a mutagen to save his flock}
{1302}{}{Escort Diana to Casa Nueva}
{1303}{}{}
{1304}{}{}
{1305}{}{}
{1306}{}{}
{1307}{}{}
{1308}{}{}
{1309}{}{}

#---------------------------------------------------------
# Casa Nueva
#---------------------------------------------------------

{1400}{}{}
{1401}{}{Find the missing peasant}
{1402}{}{Followers are trying to stop the epidemic}
{1403}{}{People are disappearing at the concrete plant}
{1404}{}{Chipo asks to cure his pet despite the discontent of the residents}
{1405}{}{The local school needs more books}
{1406}{}{}
{1407}{}{}
{1408}{}{}
{1409}{}{}

#---------------------------------------------------------
# ! Free slot
#---------------------------------------------------------

{1500}{}{}

#---------------------------------------------------------
# Old the motel
#---------------------------------------------------------

{1600}{}{}

#---------------------------------------------------------
# !DLC Dayglow / San Diego
#---------------------------------------------------------

{1700}{}{Visit the mysterious city of the dead}
{1701}{}{Find Vault 24}
{1702}{}{Neutralize a military robot in the ruins of Tijuana}
{1703}{}{Neutralize the distraught Gonzo}
{1704}{}{Restore the city's electricity supply}
{1705}{}{Restore urban radio broadcasting}
{1706}{}{Take the holodisk to the Old Town}
{1707}{}{Meet the caravan from the Hub}
{1708}{}{Treasures of Coronado Island}
{1709}{}{Restore monorail service}
{1710}{}{Organize mariachi performances}
{1711}{}{Find Donovan}
{1712}{}{Get chips from black miners at the Factory}
{1713}{}{Granny Judy is looking for her husband Rupert}
{1714}{}{To work for Mr. De Santi}
{1715}{}{}
{1716}{}{Truckers' contract to search for relics}
{1717}{}{Contract for the delivery of strong alcohol}
{1718}{}{Coffee delivery contract}
{1719}{}{Lunch delivery contract}
{1720}{}{Mortimer's New book Search Contract}

#---------------------------------------------------------
# ! Free slot
#---------------------------------------------------------

{1800}{}{}

#---------------------------------------------------------
# Santa- Ana
#---------------------------------------------------------

{1900}{}{Talk to the residents about the holiday}
{1901}{}{Find the missing ceremonial wreath}
{1902}{}{Find and return Lucia}
{1903}{}{Stop the headman Ilario}
{1904}{}{Conclude a trade alliance with Casa Nueva}

#---------------------------------------------------------
# ! Free slot
#---------------------------------------------------------

{2000}{}{}

#---------------------------------------------------------
# Jackals
#---------------------------------------------------------

{2100}{}{Save the Ranger}
{2101}{}{The rabid Bitch is ready to make alliances with outsiders to solve the problem of hunger}
{2102}{}{Black Fang intends to leave the valley to solve the problem of hunger}
{2103}{}{Eliminate the Jackals}
{2104}{}{To raid the burrows together with the thugs from Garage City}

#---------------------------------------------------------
# Car outta Gas Quests
#---------------------------------------------------------

{2200}{}{}

#---------------------------------------------------------
# ! Free slot
#---------------------------------------------------------

{2300}{}{}

#---------------------------------------------------------
# Vault 27
#---------------------------------------------------------

{2400}{}{Find Vault 27}
{2401}{}{Find information about the background of the asylum 27}
{2402}{}{Start backup generator}
{2403}{}{Start backup generator and restore ventilation}
{2404}{}{Meet the surviving member of the expedition}
{2405}{}{Escort Arthur Carrington to the safe zone}

#---------------------------------------------------------
# Camp Fraternities of Steel
#---------------------------------------------------------

{2500}{}{}

#---------------------------------------------------------
# Raiders (mainline workers)
#---------------------------------------------------------

{2600}{}{Eliminate the raider in the Casa Grande prison}
{2601}{}{Conclude a truce of Blue Shields with the Tinsmiths}
{2602}{}{Conclude a truce of Blue Shields with Casa Grande}
{2603}{}{Take a questionable package to a pusher in Phoenix}
{2604}{}{Prepare Chuck for the initiation ceremony}
{2605}{}{}
{2606}{}{}
{2607}{}{}
{2608}{}{}
{2609}{}{}

#---------------------------------------------------------
# Camp Winon
#---------------------------------------------------------
{4900}{}{}