{100}{}{There is a Guide in front of you.}
{101}{}{You see a man in an old hiking hoodie. His head and hands are wrapped in bandages.}
{102}{}{Here our paths diverge. To return to Sonora, wait for the next caravan near this flag.}
{103}{}{Glad to meet you, smooth-skinned creature.}

{200}{}{Human child, this place is dangerous for people like you.}
{201}{}{For you— too. What are you doing here?}
{202}{}{Hmm. Have you ever met DEAD PEOPLE? People with pockmarked skin who have lived forever? I'm looking for them to direct to the ruins of San Diego.}
{203}{}{And why do ghouls gather on the ruins of San Diego?}
{204}{}{Our home used to be the Necropolis. Because of the army of super mutants, the city was deserted, and the ghouls scattered across the wastelands. We were chased from everywhere. Finally, we have created a new city — the Dayglow. It is open to all ghouls and mutants who are ready to share our burden.}
{205}{}{I want to join you.}
{206}{}{So we are not on the way. Be.}
{207}{}{In the Glow, you can die from radiation, smooth-skinned. And if not, then the ghouls will hardly accept you. After all, people have always driven us away. Think about it, are you ready for such a test?}
{1207}{}{In the Glow, you can die from radiation, smooth-skinned. And if not, then the ghouls will hardly accept you. After all, people have always driven us away. Think about it, are you ready for such a test?}
{208}{}{I don't find my place in this world either. I think it will be useful for me to visit a new place.}
{209}{}{Some mysterious stranger called me into the Dayglow. I can't ignore it.}
{210}{}{It all sounds pretty repulsive. I think I'll postpone the trip. Bye.}
{211}{}{Well, the decision is yours.}
{212}{}{Tell me about the way.}
{213}{}{Why are ghouls going to San Diego?}

{220}{}{And once again our paths crossed. Is it fate?}
{221}{}{No, it's just an accident. Goodbye.}
{222}{}{I want to go with you into the Dayglow.}

{230}{}{Great Set! You remind me of Necropolis corpses in the early stages of the disease. But I don't remember you. Are you really a new child of the Creator?}
{231}{}{I am not from the Necropolis and not a child of the Creator. Someone named Levi made me like this.}
{232}{}{Levi? I know him. He is one of the best creations of the Creator. But he looks down on people like us. So you're a victim of his experiments? I feel sorry for you. Now you will know all the bitterness of the Ghoul life.}
{233}{}{And I feel good as it is. I don't know why you're sad.}
{234}{}{And that's right — everyone shuns me. Even relatives.}
{235}{}{}
{236}{}{}
{237}{}{Then come with us. We are building a house for people like you and me.}
{238}{}{A home for mutants? Where is it?}
{239}{}{The Ghouls are building a new city on the ruins of San Diego. Your own world. I'm looking for and sending there all the undead who have not yet lost the remnants of reason. And there would be a place for you there.}
{240}{}{Good. I'll go with you to San Diego.}
{241}{}{I can't leave these lands yet. But I will know that there is another place on the wastelands where they are waiting for me.}

{250}{}{I'll have to leave my friends here. Of the things you can take only the most necessary, no more than 20 pounds. Through the scorched lands you need to go light — fast as the wind.}
{251}{}{Well, no. I'm not leaving my belongings!}
{252}{}{Can I come back if I don't like it there?}
{253}{}{To return — yes. But you can count on my escort only once.}
{254}{}{Then I need to think about it. I'll find you if I dare.}
{255}{}{I'm ready to hit the road.}
{1255}{}{I'm ready to hit the road.}
{256}{}{Soon you will be in another world, friend.}
{1256}{}{Soon you'll be in another world, girlfriend.}
{257}{}{[Go on a trip]}
{258}{}{You have too many things.}
{259}{}{I have too many things. I'll come back when I hide them somewhere.}