{100}{}{You see a black scavenger.}
{101}{}{Here is a man dressed in special clothes for exploring the ruins.}
{102}{}{A competitor? Then choose the areas we're not going to. Just a warning.}
{103}{}{A fight! Who is not with us, let him get out! Fight!}
{104}{}{Okay, okay, we overreacted. We apologize.}
{105}{}{Serves them right! We are a real force here!}

{200}{}{A fight! Who is not with us, let him get out! Fight!}
{201}{}{Yes! And now you will get it from me!}
{202}{}{Stop the fight! I won't let you get rowdy in a Gulsky bar.}
{203}{}{Yes? What are you gonna do, YOU PIECE OF SHIT?}
{204}{}{I'll take out my gun and shoot the first one who makes a sudden move.}
{205}{}{Pf-ha-ha-ha! Gulsky litter! Well, you give! He'll shoot you! U-ha-ha! Okay, guys, let's get out of here. These clowns are not our rivals.}
{206}{}{Get out of here.}
{207}{}{I'll wait until you leave.}
{208}{}{What did you say, bastard? I'll shove these words back down your throat with your teeth!}
{209}{}{[Throw a handful of bottle caps into the air. Let them collect instead of fighting.]}