{100}{}{You see Fernando.}
{101}{}{In front of you is a ghoul in an old suit. A gray Mexican mustache hung on his face.}
{102}{}{Hi. Robots are not allowed to enter the station. They guard her like a mother.}
{103}{}{Hi. What am I doing here? Nothing so far, as you can see.}
{104}{}{What's going on? Why was the concert canceled?}
{105}{}{Hey, hey, buddy!}
{1105}{}{My respects, senorita!}

{110}{}{We've gone too far. The Old Town is on the other side.}
{111}{}{Is this the legendary Ghost Station?}
{112}{}{The station comes to life, and the city comes to life after it. And it's all thanks to you.}
{113}{}{I hope Bonita will work again soon.}
{114}{}{Be careful! Robots from the border service are often seen in this area.}
{115}{}{Ahead there will be a cliff leading to the Auteuil River.}
{116}{}{If we go over the bridge, then watch your feet carefully.}
{117}{}{Do you believe it — on weekends, hordes of people gathered in such places. And now — not a soul.}
{118}{}{The tract of the Otei River. Once it was beautiful here.}
{119}{}{This large building is a military hospital. It has already been looted.}
{120}{}{}
{121}{}{I don't feel like going there.}
{122}{}{We are close to the epicenter of the explosion. You shouldn't linger here.}
{123}{}{The Italian district — before the War, it was known for its cafes... and bandits and pimps.}
{124}{}{Shall we go through the park? That's right, there is lower radiation here, but more of all kinds of living creatures.}

{200}{}{I am at your service, senor.}
{1200}{}{I am at your service, senorita.}
{201}{}{Bye.}
{202}{}{Who are you?}
{203}{}{My name is Fernando.}
{204}{}{What are you doing here?}
{205}{}{Nothing yet, as you can see.}
{206}{}{Jose Solis sent me. He is trying to bring his mariachi band back to life.}
{207}{}{Good idea. I don't mind. When are we performing?}
{208}{}{I don't know yet. Wait a bit.}
{209}{}{Let's go right now. I'll take you straight to the Old Town.}
{210}{}{It will be difficult for me to walk through the ruins alone. I hope you know the way?}
{211}{}{Yes, let's go.}
{212}{}{I don't mind performing from the stage like I used to. Will you accompany me to the Old Town?}
{213}{}{Yes, let's go.}
{214}{}{No, not now.}
{215}{}{Yes?}
{216}{}{Nothing. Nevermind.}
{217}{}{Come with me. There's a scene waiting for you in the Old Town.}
{218}{}{Wait for me here. I'll be back soon.}
{219}{}{Thank you for your help, my friend. I will perform a funeral march in your honor.}
{1219}{}{Thank you for your help, senorita. I will perform a funeral march in your honor.}
{220}{}{Yeah. Enjoy it.}