{100}{}{You see Beatrice.}
{101}{}{In front of you is a dead woman in a once beautiful dress.}
{102}{}{}
{103}{}{See that handsome guy behind the counter? He makes great eggs... Oh, I hope you understand me correctly.}
{104}{}{Hey, what happened to Jose? He couldn't leave us on this stage!}
{105}{}{I'm so glad! I'm so glad!}

{200}{}{Hello, handsome. You've startled everyone here with your appearance. How are you?}
{1200}{}{Hi. You've startled everyone here with your appearance. What do you need?}
{201}{}{Bye.}
{202}{}{Who are you?}
{203}{}{Who am I? I'm Beatrice Aguirre! My name was once on all the posters in California. Oh, what a pity that times have changed.}
{204}{}{What are you doing here?}
{205}{}{That handsome guy at the bar promised me a drink. This is the only consolation in my cursed life.}
{206}{}{Jose Solis sent me. He's trying to bring his mariachi band back to life.}
{207}{}{So the old man is up to his old ways? How I understand him! Okay, I'm in. I wonder what will come of it.}
{208}{}{I'll call you when I need you. Bye.}
{209}{}{He asks me to take you straight to the Old Town. Can you go now?}
{210}{}{Go ahead! To meet our fate!}
{211}{}{Yes, let's go.}
{212}{}{I'm just burning with the desire to perform from the stage again! Will you help me get to the Old Town?}
{213}{}{Yes, let's go.}
{214}{}{Not now.}
{215}{}{I'm just burning with the desire to perform from the stage again!}
{216}{}{We'll talk about it later, Beatrice. But later.}
{217}{}{Come with me. There's a scene waiting for you in the Old Town.}
{218}{}{Wait for me here. I'll be back soon.}
{219}{}{Thank you for your help. I'll sing some sad song in your honor.}
{220}{}{Good luck on stage.}