{100}{}{You see Jeffrey.}
{101}{}{You see a ghoul in old pajamas. He calmly sips a cocktail.}
{102}{}{I can't forbid you to be here. But I forbid you to climb up to me.}
{103}{}{Smooth—skinned are big xenophobes. Am I not right?}
{104}{}{Laws? I think you wouldn't like it in the "rule of law".}

{200}{}{Hey, welcome, dead body. Where are you from?}
{201}{}{Thanks for the drink, buddy. Where are you from?}
{1201}{}{Thanks for the drink, miss. Where are you from?}
{202}{}{Welcome, my friend. Where are you from?}
{1202}{}{Welcome, lady. Where are you from?}
{203}{}{I'm from Arizona.}
{204}{}{Arizona! I didn't think there were dead people there, too. Apparently, we were not the only ones affected by this infection a hundred years ago.}
{205}{}{Us?}
{206}{}{Arizona! I didn't think there were people there either. Although it's a bit strange to say "too" about us.}
{207}{}{Us?}
{208}{}{Necropolis undead. We waited out the nuclear attack in a local Vault, but as a result, turned into ghouls. They died and went to heaven. This is my favorite joke.}
{209}{}{Then why are you here and not in the Necropolis?}
{210}{}{Don't you know this story? Oh, it happened a few years ago. In short, because of one fucking mutant who bred other mutants, normal people turned against ALL mutants. This forced us to migrate far away. And now we're here. And it wasn't so bad.}
{211}{}{In other words, you just ran away from problems?}
{212}{}{Think what you want. It doesn't matter now.}
{213}{}{It's prudent. So you show that you don't want enmity with normal people.}
{214}{}{Thanks for the kind words, my friend.}
{1214}{}{Thank you for your kind words, friend.}
{215}{}{Does it look like you like it here?}
{216}{}{In the Necropolis we would have to dig our graves. And here we live a normal life. Now I'm sipping white Russian at the bar — what could be better?}
{217}{}{[Listen]}
{218}{}{By the way, I lived here before the War. Pleasant memories. A century has passed since then. I'm here again, and there's nothing left of the house. Most of all I feel sorry for the carpet. He set the tone for the whole room.}
{219}{}{You should switch to "black Russian". It will cheer up the remnants of your brains, which, apparently, are already completely rotten.}
{220}{}{I don't know how I hurt you, smooth face. You need to change something in your opinion about this place.}
{221}{}{Maybe. Goodbye.}
{222}{}{It's so sad. It seems that I don't understand what it's like to live for a century among the ruins.}
{223}{}{So you haven't lost much in this life. I hope you like it here.}
{1223}{}{So you haven't lost much in this life. I hope you like it here.}
{224}{}{Maybe. Bye.}
{225}{}{I don't know what I've done to you, tanned face. You need to change something in your opinion about this place.}

{230}{}{You know, these lands once belonged to the Mexicans. And then the Americans came and took it away. But the War erased the boundaries. Now this land belongs to mutants without race and nationality.}
{231}{}{And you can't argue.}

{250}{}{Write "Arizona" out of the dust on the bar.}
{251}{}{Nek-kokol?}
{252}{}{[Express disgust with the cowardice of ghouls]}
{253}{}{[Show approval]}
{254}{}{Why?}
{255}{}{[Twirl your finger at the temple]}
{256}{}{[Pat on the shoulder]}
{257}{}{[Leave]}
{258}{}{Bye!}