{100}{}{You see Jose Solis.}
{101}{}{You see a ghoul in a pre-war suit. He looks much neater and cleaner than other ghouls.}
{102}{}{You seem to be new here. Do you want to buy me a drink and tell me a little about yourself?}
{103}{}{My dreams of Jose Solis' Mariachi are over.}
{104}{}{"Jose Solis' Mariachi" back in business!}
{105}{}{Don't distract me, I'm busy rehearsing. Shoo! Shoo!}

{200}{}{Hello, man. I heard that there was a normal in town, but I thought it was another stupid joke of the oldies. And now you're here, blinding me with white skin and making me remember the old days. By the way, my name is Jose Solis. And you?}
{201}{}{I }
{202}{}{.}
{203}{}{ Damn nice to meet you, }
{204}{}{. How do you like our little hell's corner? Bored already?}
{205}{}{I }
{206}{}{. Remember that name, ghoul.}
{207}{}{Okay, okay, }
{208}{}{. I see you don't like it here. Or am I wrong?}
{209}{}{Normal. You can live.}
{210}{}{It's strange to hear this from normie. It seems that you want to trick me around your finger. Okay. So what do you need here?}
{211}{}{It's kind of boring.}
{212}{}{That's for sure! I want to shake this place up a little myself. So what do you need here?}
{213}{}{Oh, nothing definite. Just looking around. Bye.}
{214}{}{Can I ask you a few questions?}
{215}{}{Greetings, friend of misfortune! I heard that a new one has appeared in the city, but not from the Necropolis. It's an amazing thing. By the way, my name is Jose Solis. And you?}
{1215}{}{Greetings, beautiful lady! I heard that a new girl appeared in the city, but not from the Necropolis. You know how to surprise an old man. By the way, my name is Jose Solis. And you?}
{216}{}{Yes, perhaps. It's even better than the Necropolis. But this is just the beginning! Someday we will restore the city to its original appearance — then you will lose your head with happiness. And how can I help you now?}
{217}{}{That's for sure! I want to shake this place up a little myself. So how can I help you?}

{220}{}{Greetings, friend of misfortune!}
{1220}{}{Greetings, my love!}
{221}{}{Welcome, }
{222}{}{.}
{223}{}{How can I help you, }
{224}{}{.}
{225}{}{I know you, }
{226}{}{. You're nothing but trouble. Be reasonable and don't bother me in vain.}
{227}{}{Greetings, senor normie.}
{1227}{}{Greetings, senora normie.}
{228}{}{Greetings, }
{229}{}{. I hope you're smart enough not to cause problems here.}
{230}{}{I think I should go.}
{231}{}{Well, thanks for the conversation. Recently, the normies tried not to talk to us but immediately fired from all barrels. Very not sociable guys.}
{232}{}{Goodbye.}

{240}{}{Sure. Spit it out.}
{241}{}{Only if you finally leave me alone after that.}
{242}{}{What's going on here?}
{243}{}{Nothing special. The usual routine life in a big city.}
{244}{}{Hmm. Okay.}

{250}{}{Do you like it here yourself?}
{251}{}{Not a bad city. Good climate, good people. But you know, San Diego used to be famous for its cultural life. And now here you can only hear the singing of the Geiger counter.}
{252}{}{Yes, I would like to listen to someone live.}
{253}{}{Are you kidding? These ruins are a hundred years old. There is no one to speak here.}
{254}{}{Then smile, baby. This is Jose Solis! My ensemble was known throughout Baja California. It was a good time. We were just giving a concert in Bakersfield when the bombs fell on the city. I miraculously survived then. And just now I'm thinking of going back to the old craft.}
{255}{}{And what's in the way?}
{256}{}{Well, first of all, I need new guitar strings. She's in my room right now. And it's not so easy to find them among these ruins.}
{257}{}{I'll find you some strings. For me, there is nothing that cannot be found in the old cities.}
{258}{}{Gracias, senor! Together we will remind the Glow of the old days.}
{1258}{}{Gracias, senorita! Together we will remind the Shining of old times.}
{259}{}{Goodbye.}
{260}{}{Can you at least pay me for this job?}
{261}{}{To be honest, I don't have any caps right now. How about a share of the first fees?}
{262}{}{I'm in. I'll find you some strings.}
{263}{}{I don't need any caps or extra hassle. Be.}
{264}{}{Sorry, it's not for me. Goodbye.}
{265}{}{Do you know where you can find guitar strings?}
{266}{}{I have already climbed all the local ruins, there are no strings here. It remains only to visit Tijuana. At one time there was a Mariachi museum and several beautiful performance stages. And now there are crowds of robots and mutants.}
{267}{}{Tijuana, then. I see.}
{268}{}{Have you tried out new guitar strings yet?}
{269}{}{Oh, it sounds great! Besides, it's easier for my stiff skin to clamp the strings now. Thank you, smooth-skinned amigo.}
{270}{}{No problem. When is the next performance?}
{271}{}{Don't be in such a hurry! I haven't prepared properly yet. And the most important thing is that I can't perform alone, without my beautiful companions!}
{272}{}{So are they here, too, in the Glow?}
{273}{}{Trumpeter Fernando works at the dam, and senorita Beatriz is at a diner in the southern camp. Surely you will pass by, will you bring them to me?}
{274}{}{Okay. Why not?}
{275}{}{If I bring your companions, what will I get for it?}
{276}{}{I'm in. I'll bring your companions.}
{277}{}{Looking forward to it!}
{278}{}{Goodbye.}
{279}{}{Where can I find Fernando?}
{280}{}{Trumpeter Fernando works at the Bonita Dam.}
{281}{}{Where can I find Beatrice?}
{282}{}{Senorita Beatriz works at a diner in the San Isidro neighborhood.}
{283}{}{Clear. Another question.}
{284}{}{Goodbye.}
{285}{}{Fernando and Beatrice are already here.}
{286}{}{Excellent! We have a lot to talk about with them. Come to our first concert in a day.}
{287}{}{Okay. Have a good rehearsal.}
{288}{}{Fernando is already here. But Beatrice died.}
{289}{}{Poor Beatrice! Finally, she has suffered in this life. Even a little enviable...}
{290}{}{Beatrice is already here. But Fernando died.}
{291}{}{Poor Fernando! Finally, he has suffered in this life. Even a little envious...}
{292}{}{Woe to me! A dream slips out of your hands like ashes between your fingers... listen, what about a hologram? I know, there is one preserved in the Chula Vista shopping center. Maybe she will replace the missing participants for me? Will you bring the holographic module? I will certainly be able to reconfigure it for my purposes.}
{293}{}{Seriously? Okay, we'll have to look for this thing, otherwise, you'll kill yourself like that.}
{294}{}{I have a holographic module. Here you go.}
{295}{}{Fernando and Beatrice are dead.}
{296}{}{Fernando and Beatrice died. I'm sorry.}
{297}{}{Excellent! I need time to prepare. Come to our first concert in a day.}
{298}{}{Okay. Have a good rehearsal.}
{299}{}{It's the old man }
{1299}{}{This is my goddess of inspiration, }
{300}{}{! It's like you brought me back to 2077. It's been a long time since I've been so happy. By the way, we made a lot of money on this performance. Here's your share, 1000 habaks. Thank you for your help, partner.}
{1300}{}{! It's like you brought me back to 2077. It's been a long time since I've been so happy. By the way, we made a lot of money on this performance. Here's your share, 1000 habaks. Thank you for your help, senora.}
{301}{}{Good luck, Jose.}
{302}{}{! It's like you brought me back to 2077. It's been a long time since I've been so happy. By the way, we made a lot of money on this performance. Here's your share, 1000 habaks. And also from me personally — this wonderful century-old whiskey. Thank you for your help, partner.}
{1302}{}{! It's like you brought me back to 2077. It's been a long time since I've been so happy. By the way, we made a lot of money on this performance. Here's your share, 1000 habaks. And also from me personally — this wonderful century-old whiskey. Thank you for your help, senora.}
{303}{}{What do you call the band?}
{304}{}{Hmm, we need something romantic. Maybe "Last Breath"? Or — "Love in hell"? Maybe "A Kiss before death"? What about...}
{305}{}{I think it would be easier to name after you.}
{306}{}{Mariachi de Jose Solis? Of course!}
{307}{}{That's nice...}
{308}{}{By the way, what do you call the band?}