{100}{}{This is John D. Butler.}
{101}{}{You see a ghoul in a worn business suit.}
{102}{}{Are you going to a military base? Private Heap wants it too!}

#Acquaintance
{200}{}{Hi. I don't think we've ever met before. I am John Butler, the elected mayor of the Shining. And who are you?}
{201}{}{Nice to meet you, Butler. I }
{202}{}{, a random mutation victim on the wastelands.}
{203}{}{It's better not to suck up to me, ghoul.}
{204}{}{(sigh) I never thought that one mutant would accuse another mutant of being a mutant.}
{205}{}{It doesn't happen on the wastelands.}
{206}{}{*Attention!* I'm John Butler. I run this city... More precisely, what's left of it. And I'm glad to see any smooth-skinned people who behave decently in my city. * Fire! Fire!*}
{207}{}{I had no intention of somehow hooliganism here.}
{208}{}{Humans and super mutants drove us from our homes. You probably already know this story. But this is not a reason to hate everyone around. On the contrary, I want to prove to people that ghouls are also people... * Keep firing!*}
{209}{}{Aren't you trying to trick me? I thought ghouls hated normies.}
{210}{}{We moved here because humans and super mutants drove us out of our homes. But this is not a reason to hate everyone around. On the contrary, I want to prove to people that ghouls are also people... * Keep firing!*}
{211}{}{Puns aren't your strong suit, John.}
{212}{}{And that's right. This soldier has a hard time with humor. You can't get rid of old habits even in a hundred years. So how can I help you?}
{213}{}{Right now, probably nothing.}
{214}{}{That's very noble of you.}
{215}{}{To hell with us old people. We have survived many wars and battles, our fate will remain in the past. More importantly, what will happen to your generation... * Attack! Go ahead!* Uh, so how can I help you?}
{216}{}{I just wanted to get to know you. But it's time for me to leave.}
{1216}{}{I just wanted to meet you. But it's time for me to leave.}

{220}{}{It's our old buddy, a bunch. And a man with him? Deadly news! It's like a snake and a rabbit have made friends. I am very happy for you.}
{1220}{}{It's our old buddy, a bunch. And a man with him? Deadly news! It's like a snake and a rabbit have made friends. I am very happy for you. It's a pity we don't have a church to marry you.}
{221}{}{Heap is my bodyguard.}
{222}{}{I'm the commander of the Pile. He can't even take a piss without my order.}

#Repeat dialog
{230}{}{Okay. How can I help you?}
{231}{}{Hello, smooth-skinned. Have a question?}
{1231}{}{Hello, smooth-skinned. Have a question?}
{232}{}{Hello, young mutation victim. How can I help you?}
{233}{}{Hi, John. Just passing by. Bye.}
{234}{}{It's a pity we didn't talk so much. If you need anything, I'm always here... * Death! Smee-ert!*}
{235}{}{Later.}
{236}{}{What do you need?}
{237}{}{The time for jokes is over. It's time to get down to business.}

{240}{}{Tell me, how did you all end up here?}
{241}{}{We lived in the north, in a city called Necropolis. But super mutants came there. And the normies came for them. They fought among themselves, but they forgot about us... * Aim! Fire!* When the dust settled, the normies decided that they didn't like ghouls either. We decided to find a new home.}
{242}{}{What city are you trying to build?}
{243}{}{Just a normal working city. With trade and economy, hotels and casinos, roads and skyscrapers. And so that there is enough room for everyone here — ghouls, humans and mutants. * At ease, soldiers!*}
{244}{}{Thanks for the reply. I have to go.}
{245}{}{Is there anything I can do to help?}
{246}{}{Do you really want to help? If it weren't for those glazed eyes, I'd be crying right now. Ask around for corpses, someone probably needs help.}
{247}{}{I'll do that. Goodbye.}
{248}{}{Is there anything else I can help with?}
{249}{}{Tell me about yourself.}
{250}{}{I've already told you. My name is John Butler. I am the mayor of Glow... well, the future Glow.}
{251}{}{Is San Isidro part of your domain?}
{252}{}{This is one of the areas of the future Glow. There are several Gulian camps on the ruins. The Old Town and San Isidro are the largest of them. And each is managed by its own administrator. * God save America! *}

#Story quests
{259}{}{Urgently! No wonder you had to fix a radio station. A caravan of Truckers has just contacted us. The guys were ambushed on the fifth highway. Ghouls are too slow and weak. All hope is in you. Come on, help your brothers in a difficult moment. *Step-march!*}
{260}{}{I'm already running as fast as I can!}
{261}{}{You, as usual, are of no use. Okay, I'll do it.}
{262}{}{A caravan at a road junction. Go straight north on the main highway.}
{263}{}{Truckers — are they alive?}
{264}{}{I haven't had a chance to see them yet. I'll be back when I find out.}
{265}{}{Mr. Rutger told me about your feat. Saving the caravan is only good for us, the ghouls. We need things from the north, and the Truckers are the most reliable caravan company. So — thank you}
{266}{}{.}
{267}{}{, smooth-skinned.}
{268}{}{No problem.}
{269}{}{I can see by your eyes that your mission has failed. Well, Rutger was the best trucker. Without him and his company, it will be more difficult to trade with people. But Gustavo will be glad to hear it. He does not want to share with the smooth-skinned finds of the Old World.}
{270}{}{That was the calculation.}
{271}{}{Sorry it happened like that. But I did my best.}
{1271}{}{Sorry it happened like that. But I did my best.}
{272}{}{Now I need to check and think about something. In the meantime, you can rest.}
{273}{}{Okay.}
{274}{}{}
{275}{}{}
{276}{}{}
{277}{}{}
{278}{}{}
{279}{}{}

#Story quests
{300}{}{Gustavo asked me to give you this CD.}
{301}{}{Give it here. Let's see what this wheezer got into his head ... hmm. Yes, this is killer news! Now Glow has electricity and radio communication. Just like in the good old days. What could be better? *Everyone to the front! All for the war!*}
{302}{}{[Next]}
{303}{}{Oh, and Gustavo again demands to break with the smooth-skinned. This senile old man doesn't understand anything. * Aim! Fire!* You see, Gustavo wants to protect the city from outsiders. And I think it's stupid. We need things and food from the Hub. And the Hub needs Glow technologies. Tell me, you're not going to indulge his nonsense, are you?}
{304}{}{I'm not going to.}
{305}{}{I don't care which one of you pays for the work.}
{306}{}{Great. Then I have a couple of small and easy tasks for you.}
{307}{}{I'm listening.}
{308}{}{What if I'm going to?}
{309}{}{It will be sad. And very stupid.}
{310}{}{Not convinced. I'm going back to San Ysidro.}
{311}{}{Okay. Convinced. What do you need to do?}
{312}{}{It will be sad. And very stupid. Tell me, don't you care who pays for the work? I need your services too.}
{313}{}{What do you need to do?}

{320}{}{Now the scavengers are disassembling the old aircraft factory by cogs. I don't mind that smooth muzzles do it. But they work without Seth's Seal and also force ghouls to work. And most importantly, we need electronics from this factory for the nearest caravan. * Attack!* Go to the Factory. Tell the scavengers that I'll give them Seth's Seal if they complete the chip collection order. Yes, and don't say a word to Gustavo!}
{321}{}{What is the "Seal of Set"?}
{322}{}{This is a mining right in San Diego and its environs. Of course, in exchange for a portion of the profits. A kind of tax. * Don't give up!* If the scavengers take all the fossils for themselves, then our city will have nothing left.}
{323}{}{Clearly. I'll try to talk to them.}
{324}{}{We need to talk about the situation with the scavengers at the Plant.}
{325}{}{So, has the mining plan been completed?}
{326}{}{No, unfortunately.}
{327}{}{I just want to ask again, what is the "Seal of Set"?}
{328}{}{Ah, now I understand.}
{329}{}{It so happened that all the scavengers at the plant died.}
{330}{}{Did everyone die? Holy saints! And the chips? Did you manage to collect them?}
{331}{}{You're always welcome.}
{332}{}{Will I get something for trying?}
{333}{}{We collected all the chips and sent them here.}
{334}{}{Great job. * Take no prisoners!*}
{335}{}{Here's your reward. But don't rush to the bar. We have a problem here.}
{336}{}{Thank you. What happened?}
{337}{}{No. Should I?}
{338}{}{They were the main point! Since the scavengers have failed, then all hope is on you. Bring the damn chips.}
{339}{}{Okay.}
{340}{}{Yes. Here they are.}
{341}{}{Only part of it.}
{342}{}{They were the main point! Since the scavengers have failed, then all hope is on you. Collect the remaining chips.}
{343}{}{The factory is now under Gustavo's control. You won't see any chips.}
{344}{}{Did Gustavo beat me to it? This is damning news! But now there is a more serious problem. We'll have to postpone this dispute.}
{345}{}{What happened?}
{346}{}{Where is the aircraft factory located?}
{347}{}{Get to Route 805. Find Paradise Valley Hospital there. The factory will be to the east.}
{348}{}{I see.}
{349}{}{}

{350}{}{So, I thought it over and made a decision! You see, Mr. Rutger was carrying a valuable contract from the Hub to exchange technology from the Coronado Military Base. This is a HUGE profit for the city. We can restore the ruins. The dream of the Dayglow will be fulfilled! *Viva, America!*}
{351}{}{From a military base? Seriously?}
{352}{}{Now you can't get there because of old military toys. Here are the access codes. They need to be sent over that radio link you set up in San Ysidro. We don't have another powerful signal source. When you do this, come to the pier, there will be an escort waiting there. And don't tell Gustavo about it!}
{353}{}{[Leave]}