{100}{}{You see Senor Gustavo.}
{101}{}{You see Senor Gustavo, the manager of San Isidro.}
{102}{}{Here I am the law!}
{103}{}{Do ghouls need radio communication? We will help them — and then they will respect us a lot.}
{104}{}{Meet me at the pier.}

#First meeting
{200}{}{Gustavo Obanel Vallejo at your service. I'm the manager of San Isidro. Now, to hell with the niceties. I want to know the reason why you violated our posthumous rest.}
{1200}{}{Gustavo Obanel Vallejo at your service. I'm the manager of San Isidro. Now, to hell with the niceties. I want to know the reason why you disturbed our posthumous rest.}
#Gustavo Obanel Vallejo at your service. I'm the manager of San Isidro. Now, to hell with the niceties. I want to know the reason why you're disturbing our posthumous peace. We don't tolerate smooth-skinned racists here. Our family has suffered enough from you. So explain clearly and without lying — why should we tolerate your presence?
{201}{}{To hell with ghouls. I'm here for profit. I was told you can make good money here.}
{202}{}{Honest answer. With people like you, you can negotiate. I'm starting to like you.}
{203}{}{It all depends on the terms of the contract and partner.}
{204}{}{I'm looking for a better place to live. Now everything is very bad in my homeland.}
{205}{}{Running away from problems, aren't you? Not impressed, slimy-skinned. But if you want, you can benefit from it.}
{1205}{}{Running away from problems, aren't you? Not impressed, slippery skin. But if you want, you can benefit from it.}
{206}{}{Okay. And what kind of work is there here?}
{207}{}{I am not a racist. I love ghouls and would like to live among them.}
{1207}{}{I'm not a racist. I adore you, ghouls, and would like to live with you.}
{208}{}{You have such slippery skin that you will be with us for sweets, normie. I won't tolerate any more lies. But I'll give you one chance. You will cope - and you will have hugs with ghouls for the rest of your days.}
{209}{}{Hey, I'm just trying to be friendly!}
{1209}{}{Hey, I'm just trying to be friendly!}
{210}{}{Gustavo Obanel Vallejo at your service. I'm the manager of San Isidro. Glad to see you in our camp, brother. Here you will find eternal rest.}
{1210}{}{Gustavo Obanel Vallejo at your service. I'm the manager of San Isidro. Glad to see you at our camp, Sister. Here you will find eternal rest.}
{211}{}{Thank you, brother. So what would I do in this beautiful city?}
{212}{}{The Dayglow still cannot shine. You can go to the station and help our workers return electricity to the city. I will reward you handsomely and let you stay in San Ysidro for the rest of your days.}
{213}{}{The Dayglow still cannot shine. You can go to the station and help our workers return electricity to the city. The city will be grateful to you until the very last days.}
{214}{}{Agreed.}
{215}{}{Too much trouble.}
{216}{}{Too many words, normie. Get back to the nuclear wasteland! We don't need you.}
{217}{}{Oh, oh...}
{218}{}{After the incident at the border, the conversation with you will be short. What do you need?}
{219}{}{What is the incident? I don't know!}
{220}{}{My faithful servants guarded the entrance. And now only the wind is walking there. And at that moment you appear. What do you say in your defense?}
{221}{}{This is some kind of coincidence. The entrance was open, so I entered.}
{1221}{}{This is some kind of coincidence. The entrance was open, so I went in.}
{222}{}{Hmm, if I find out that you're lying, I'll personally rip off your slippery skin and sprinkle radioactive ash on the bleeding meat. You will feel all the pain that ghouls experience every day of their lives.}
{223}{}{I believe every word. But who are you?}
{224}{}{That ghoul threatened me. I was just defending myself.}
{1224}{}{That ghoul threatened me. I was just defending myself.}
{225}{}{He was a loyal servant of Glow. He defended our city from the normies. Do you think you can redeem yourself?}
{226}{}{You have no right to set boundaries. This wasteland is for everyone, not just you.}
{227}{}{We just want to live like normal people. Without wars. Without grandiose missions to save humanity. You may not understand this. But since you're here, you don't have much choice — to redeem yourself or... die.}
{228}{}{I choose death. Your death!}
{229}{}{Shall we try to negotiate? By the way, we haven't introduced ourselves yet.}
{230}{}{I don't remember being warned about your appearance. How did you manage to get across the border?}
{231}{}{Well, I just walked through the gate.}
{232}{}{And the faithful servants of the Glow didn't stop you? It looks like someone is waiting for an excellent thrashing.}
{233}{}{Certainly not me. So you run everything here?}
{234}{}{To live here, you have to work. Even a mutant like you should understand that. We have enough freeloaders without you.}
{235}{}{I understand...}
{236}{}{Any ideas on how to fix a radio station?}

#Repeat dialog
{250}{}{Speak, smooth-skinned.}
{1250}{}{Speak, smooth-skinned.}
{251}{}{Goodbye, Senor Gustavo.}
{252}{}{What are you up to, normie?}
{1252}{}{What are you up to, smooth face?}
{253}{}{Look who we have here. A smooth muzzle begs for a good spanking. Don't worry, I'll save your skin for grafting onto my mortal body. In the meantime, you will tell me everything.}
{254}{}{Have a seat, amigo. I hope the ghouls in Glow have accepted you as their own.}
{255}{}{Have a seat, amigo. How do you like the Glow? Are you all right? Tell me if there's a problem.}
{256}{}{Have a seat, amigo. Tell me. Maybe I can help you.}
{257}{}{Have a seat. I think it's high time we talked.}

{260}{}{Remind me what you wanted from me.}
{261}{}{Do I speak Russian? (tired sigh) }
{262}{}{The power plant is working.}
{263}{}{The Glow is shining again! Electricity has returned to San Isidro and the Old Town. You've done a great job, amigo. Let me hug you and thank you. There are 1000 caps here.}
{1263}{}{The Glow is shining again! Electricity has returned to San Isidro and the Old Town. You've done a great job. Let me hug you and thank you. There are 1000 caps here.}
{264}{}{Thank you.}
{265}{}{Not bad.}
{266}{}{I also owe you an apology. I gave this assignment with the expectation that robots or radiation would kill you. And there will be one less smooth-skinned in the Glow. But I was wrong. You can stay in our city as long as you want.}
{267}{}{I understand you and I don't blame you.}
{268}{}{Don't expect me to shake your hand after this.}
{1268}{}{Don't expect me to hug you after that.}
{269}{}{Now that we have electricity, we need to restore the broken radio station. She is in the next room. This task is just for you.}
{270}{}{Isn't she too broken? Are you sure it can be repaired?}
{271}{}{Fix it — no. She needs a replacement. I know that the patrol center operates one of the same. And I'll pay if you bring the parts from there.}
{272}{}{OK. I'll try.}
{273}{}{If I'm in the mood, then I'll try. In the meantime, I don't want to do this. Bye.}
{274}{}{The radio station is working. More precisely, I had to replace it with a new one from the border guards office.}
{275}{}{Here's another great news in this scorched world! And I like you more and more, smooth-skinned. You were just like me when I was young.}
{1275}{}{Here's another great news in this scorched world! And I like you more and more, smooth-skinned. You were just like me when I was young.}
{276}{}{Here's another great news in this scorched world!}
{277}{}{Not the most pleasant comparison, you know.}
{278}{}{Let's just not hug, okay?}
{279}{}{Let's not waste time. Here are 500 caps for the job. And now I'm asking you to take this holodisk to Mayor Butler in the Old Town. This is very important.}
{280}{}{And that's all? After my past cases, this will turn out to be an easy walk.}
{281}{}{Ahead of you are waiting for the gloomy ruins of San Diego. Many dangers are lurking in them. Be careful. And ask Edward for supplies for the journey.}
{282}{}{Okay, see you later.}
{283}{}{Give me a gun if you want me to survive on the way to the Old Town.}
{284}{}{Hmm, that's reasonable. What weapons do you own best?}
{285}{}{[Take }
{286}{}{]}
{287}{}{ Be so kind — don't die on the way.}
{1287}{}{Be so kind — don't die on the way.}
{288}{}{I'll try...}
{289}{}{I will try to answer.}
{290}{}{Is it that important to you?}
{291}{}{We need this radio station. The areas of Glow are torn apart by impassable ruins, and radiation is jamming the usual weak radio. Constant communication will change the whole city. Try for the sake of all of us.}
{292}{}{And what is recorded on this disc?}
{293}{}{First, the data is for radio broadcasts so that we can communicate at a distance. And secondly... Secondly, some warnings to my brother so that he doesn't make big mistakes.}


{296}{}{How to get to the power plant?}
{297}{}{There are two ways. You can go directly along Federal Highway 805, and then turn east from the sign. But the highway is patrolled by military robots. A less dangerous path lies through the toxic swamps of Chula Vista.}
{298}{}{Okay, I'll try to find it.}

#Questions
{300}{}{Can I ask a few questions?}
{301}{}{Amigo, I'm always happy to listen to you and answer your questions. But there are more important things to do now. You know what to do.}
{302}{}{It's better if you get busy. You know what I mean.}
{303}{}{No talking. I'm not sure it's worth talking to you at all.}
{304}{}{I understand. We'll talk sometime later.}
{305}{}{I would say that you just don't want to see me. Bye.}
{306}{}{Amigo, I'm always happy to listen to you and answer your questions. }
{307}{}{Okay, see you later.}

{310}{}{I want to know more about you.}
{311}{}{Who am I? Strange question. I was a doctor once. But the War nullified my license. Now, as you can see, I run a small town. You can learn everything if life forces you to.}
{312}{}{By the way, about this town. I don't understand, so where is the Dayglow then? What is it?}
{313}{}{It's in our heart. Glow is a ghoul's dream. The dream of a city where we can safely meet old age. And San Isidro is one of his neighborhoods. The old border wall protects us here.}
{314}{}{So your goal is to build a Glow?}
{315}{}{A city for ghouls is my goal. We just want to live like normal people. Without harassment. Without wars. Without grandiose missions to save humanity.}
{316}{}{I see.}
{317}{}{Does the Old City also aspire to this paradise?}
{318}{}{It's not like the Old Town shares your dream.}
{319}{}{The Old Town is making a mistake. He is too close to the caravan trail and therefore cannot get rid of the corrupting influence of the normies from the northern cities.}
{320}{}{How do I get to the Old Town?}
{321}{}{Go north. You can go straight through the piers, in the most radioactive heat. Or you can make a detour through the ruins of the suburbs, providing yourself with new and not always welcome meetings.}
{322}{}{Clear.}
{323}{}{What is the Dayglow? Where is it located?}
{324}{}{Which city are you trying to build?}
{325}{}{It will be the city as it would have been a hundred years ago. We're collecting everything that's left of the Old World. No one cares about us here, so we can relax and live out our lives in peace.}
{326}{}{Tell me about yourself.}

{350}{}{I gave the holodisk to Butler. Your message didn't convince him.}
{1350}{}{I gave the holodisk to Butler. Your message didn't convince him.}
{351}{}{Not surprising. John and I are arguing about the Dayglow. About how the city of ghouls should be. He pays too much attention to the normies and completely forgot that we are people of the Old World. We can revive the city, and rebuild it anew! Yes, the ghouls are weak, but we have remnants of old cars and energy. With the help of technology, we can create for ourselves all the necessary conditions for life, even amid these scorched ruins.}
{352}{}{By the way, after reading the holodisk, he asked me to help him in the production of chips at the aircraft factory.}
{353}{}{What a fool! This plant will still serve us, the ghouls. Don't give the chips to the Old Town, give them to me. Our technician uses them to repair robots, and with their help, we will restore the city. This will give us more advantages in the future than a stupid exchange for food from the caravaneers.}
{354}{}{I'll think about it.}
{355}{}{OK. I will do so.}
{356}{}{I knew you'd say that, so I took these chips with me in advance. Here they are.}
{1356}{}{I knew you'd say that, so I took these chips with me in advance. Here they are.}
{357}{}{Thank you. Here are 1000 caps for the job. The plant will also serve us. You can't leave him to be torn to pieces. I think you should personally tell John that the plant is under my control and that I will not give him the chips.}
{358}{}{Okay.}
{359}{}{Here are the chips that Butler wanted to sell. But he won't be able to.}
{360}{}{Then I have bad news for you — Butler has already taken the chips and is preparing to sell them.}
{361}{}{This is really bad news. I think you should keep an eye on Butler. Let me know if you find out what new he's up to.}
{362}{}{OK.}
{363}{}{I have bad news for you — Butler has already taken the chips and is preparing to sell them.}
{364}{}{Yes, and also — let me know what Butler is up to if you find out.}
{365}{}{OK.}

{370}{}{Butler is going to open a military base on the island...}
{371}{}{He's making a mistake! He will sell most of the finds to people! And this will provoke a big redistribution in human settlements. As soon as the war with super mutants has subsided, the battles for old technologies will begin again. Normies don't understand how to handle the legacy of the Old World. Besides, they can use it against us. Technology should stay for free! We need them more. And we know better how to use them.}
{372}{}{What are you going to do?}
{373}{}{Butler won't back down. We have to land first and get everything for ourselves. I'll send a team to the pier to intercept. And you use the radio station, as he asked, and then go to the pier.}
{374}{}{OK.}