{100}{}{You see Edward.}
{101}{}{Here is the owner of a local drinking establishment. He is wearing a once white apron and a cap.}
{102}{}{Not interested.}

{200}{}{Hello... Oh, man!}
{201}{}{Exactly. Is this abnormal?}
{202}{}{Uh, it looks like I don't belong here. So far...}
{203}{}{Don't get me wrong, but... Don't you know that this is a city of dead people? We even raise the prices to the normies so that they don't stay here.}
{204}{}{I know. Don't worry, I won't disturb your glorious company.}
{205}{}{Just get me a drink, you fucking racist.}
{206}{}{Whatever you say.}
{207}{}{Clever. What's your name?}
{208}{}{Edward, sir.}
{1208}{}{Edward, ma'am.}
{209}{}{Okay, Edward. Show me what you have for lunch.}
{210}{}{Here is the menu, and here are the takeaway items.}
{211}{}{Thank you.}
{212}{}{What do you want, friend?}
{1212}{}{What do you want, girlfriend?}
{213}{}{What do you want, smooth face?}
{214}{}{Perhaps nothing more.}
{215}{}{Show me the menu.}
{216}{}{Come in, don't be shy. Everyone has their own here! Here we do not tolerate normics here and we double the prices. And the doors are always open to mutants.}
{217}{}{Thank you for the warm welcome. I }
{218}{}{. What's your name?}
{219}{}{I haven't agreed to join our club yet. Who are you anyway?}
{1219}{}{I haven't agreed to join our club yet. Who are you anyway?}

{220}{}{Let's have a chat, Ed?}
{221}{}{For example, about what?}
{222}{}{Enough talking. I have to go about my business.}
{223}{}{Is this a pre-war menu?}
{224}{}{To the point. What comes with caravans from the north mostly stays in the Old Town. And mere crumbs reach us. That's why I often cook from pre-war products. But we, the undead, like it even more. Oh, nostalgia! That's just one detail missing for the full range of flavors — good old coffee. How can there be a cafe without coffee?}
{225}{}{It's not fucking fair, Ed. I can look for coffee for you in the ruins.}
{226}{}{I'm sick of your whining. I'm here for a snack, not for nostalgic experiences.}
{227}{}{Would you risk it for a can of coffee? Then I will pay triple the price for each jar!}
{228}{}{Agreed. I'll bring you coffee if I find it.}
{229}{}{On the other hand, I had no plans to gather on the ruins. But I'll make a note in the Peep-Fight.}
{230}{}{You're very lucky. I just have one full jar.}
{231}{}{I have a can of coffee for your cafe.}
{232}{}{(Opens, sniffs, tastes) What a rich taste! I'll make a pretty good living on this menu. Here's your fee — }
{233}{}{ hubbucks. Bring more if you find it.}
{234}{}{Absolutely.}
{235}{}{Smooth, you've got the wrong place. They don't serve people like you here.}
{1235}{}{Smooth, you've got the wrong place. They don't serve people like you here.}
{236}{}{Make an order and get out soon.}
{237}{}{Well, I'm sorry... Or maybe we will conclude? I'll pay triple the price for each bottle.}

{240}{}{Thanks for the electricity, }
{241}{}{! It must have been a very dangerous task? Here, take the drugs for radiation sickness. I think this is the best way I can thank you.}
{242}{}{Thanks, Ed. I'll definitely need this.}
{243}{}{That's all? Okay, let's at least do this for what it is.}
{244}{}{Oh, yes, you can also count on a discount. I set other prices for ordinary smooth-skinned people.}
{245}{}{I just wanted to order something. Show me the menu.}
{246}{}{It is wonderful. But right now I need more information than nutrition.}
{247}{}{Thanks for the electricity, }
{248}{}{! It must have been a very dangerous task? Here, have a drink and lunch on me. And next time I'll give you a discount.}
{249}{}{}
{250}{}{Senor Gustavo said you owe me medicine.}
{251}{}{I'll give you Radawaye, rad-x, an antidote and a stimulant. But free cheese is only in a mousetrap. You will have to pay dearly for crossing the ruins of San Diego. I hope you can handle it. Good luck, friend.}
{1251}{}{I'll give you Radawaye, rad-x, an antidote and a stimulant. But free cheese is only in a mousetrap. You will have to pay dearly for crossing the ruins of San Diego. I hope you can handle it. Good luck, girlfriend.}
{252}{}{I need more. Show me what you have for sale?}
{253}{}{Thanks, Ed. I'll see you later.}

{260}{}{I need to exchange old money for caps.}
{261}{}{I will redeem this money for }
{262}{}{ caps. Deal?}
{263}{}{Too cheap. Sorry to bother you.}
{264}{}{No need. Better give me something edible.}
{265}{}{[Exchange 1 dollar]}
{266}{}{[Exchange $2]}
{267}{}{[Exchange 3 dollars]}
{268}{}{[Exchange $4]}
{269}{}{[Exchange $5]}
{270}{}{[Exchange 10 dollars]}
{271}{}{[Exchange ALL available dollars]}
{272}{}{What is it, a hole in your pocket? It happens.}
{273}{}{Yes, it is...}
{274}{}{Please.}
{275}{}{Thank you.}
{276}{}{[Exchange money for caps.]}
{277}{}{[Refuse and leave.]}

{280}{}{Is there a job for me?}
{281}{}{I can't offer anything serious. But you can take the groceries to the workers at the dam.}
{282}{}{No need. I don't want to do such a small thing.}
{283}{}{Good. Give me the package.}
{284}{}{There are five boxes of TV dinner with food for five people. Give it to each of them. And you need to make it in one day. It will definitely be faster for you than for ghouls. Yes, and don't eat it on the way. Otherwise the ghouls on the dam will be VERY unhappy.}
{285}{}{Okay.}
{286}{}{All the customers at the dam have received their orders.}
{287}{}{Thank you very much. Here's your salary.}
{288}{}{Bye.}
{289}{}{Thank you very much. Here's your salary. Oh, and by the way, I have leftover food here. Here, take it on the house.}
{290}{}{Thank you.}
{291}{}{Well, yes, what else can you appease me, if not objects? Bye, Ed.}

{292}{}{Do you know who owns the movie "Deep Throat" here?}
{293}{}{I know. This is Raymond. But he will never part with his favorite movie. Although it seems to me that he appreciates just a box with a disc and has never even watched the film itself. Yes, I warn you — do not take the disk from him, he will be beside himself with rage and will raise everyone in the city.}
{294}{}{Thanks for the warning.}

{295}{}{Hey, Ed, you know, in the ruins I came across a food processor with your name on the form.}
{296}{}{Well, finally she was found! She was supposed to be brought by a messenger robot, but something happened to him. You know, this processor has no price! We're dying here without proper food. And the processor would fix this problem quite well. So you're saying you have it?}
{297}{}{No, uh, I left it where I found it. Sorry.}
{298}{}{Sorry. Very sorry. We need this processor! I beg you, bring it. I'll give you 200 caps.}
{299}{}{Well, if I'm around.}
{300}{}{OK.}
{301}{}{Yes, here it is.}
{302}{}{Oh, you're saving us! Hey, guys, look, this smooth-skinned guy did a great job for us. Thank him!}
{303}{}{Glad to help. Maybe, Ed.}
{304}{}{Damn, but De-Santi would give me more... Oh, I'm talking about something else, nevermind. Uh, bye.}