{100}{}{You see the bartender.}
{101}{}{Here is an ordinary bartender... would you like to say that if he wasn't a ghoul.}
{102}{}{Again, these drunken showdowns! Stop them! They'll blow up my bar!}

{210}{}{What do you want, a bag of bones?}
{211}{}{Nothing yet. Bye.}
{212}{}{I want a drink and a snack. What do you have?}

{220}{}{Is Steve Morgan here?}
{221}{}{He just left. Why do you need this walking corpse?}
{222}{}{I have a "case" for him. This concerns the courier service.}
{223}{}{Not the best choice. He has been suffering from a thirst for profit since the War, but he cannot even earn money for a new car. Hehe, just kidding. Anyway, he said he was going to return to the Hub. I was just talking, sitting right in the same chair as you.}
{224}{}{When is he going to be back? Right now? I'll try to catch up with him on the highway...}
{225}{}{I should have said it right away, idiot!}
{226}{}{What are the black scavengers doing here?}
{227}{}{My bar is open to anyone who pays. Butler doesn't mind people in town either. He is trying to establish trade with the Hub. As long as the scavengers don't create problems, we tolerate them.}
{228}{}{I see.}

{230}{}{Do you have anything stronger than old beer?}
{231}{}{Good liquor has become a rarity. What is found in the ruins is usually sold to caravans from the north, and the bar is left with all sorts of swill.}
{232}{}{It's a pity. And I was so hoping for a good drink...}
{233}{}{I can look for supplies for you in the ruins.}
{234}{}{Bring it, I'll be happy to pay triple the price.}
{235}{}{Agreed. I'll bring all the strong alcohol I find in the ruins.}
{236}{}{You're very lucky. I just have a bottle of pre-war whiskey with me.}
{237}{}{(Opens the bottle, sniffs, tastes.) Excellent quality! This kind of booze costs good money. Here's your part — }
{238}{}{ hubbucks. Bring more if you find it.}
{239}{}{Required.}
{240}{}{I have a bottle of pre-war whiskey for your bar.}

{241}{}{A bunch of us are looking for his squad. Maybe you've heard of him?}
{242}{}{I heard that super mutants have set up a camp in Balboa Park. They are not aggressive, rather the opposite. Maybe this is the squad you're looking for.}
{243}{}{Clear. Thank you.}

{260}{}{I want to exchange dollars for caps.}
{261}{}{No problems. Today the course is }
{262}{}{ caps.}
{263}{}{Not today. I'll wait for the course change.}
{264}{}{Another time. Better let me see your menu.}
{265}{}{[Exchange 1 dollar]}
{266}{}{[Exchange $2]}
{267}{}{[Exchange 3 dollars]}
{268}{}{[Exchange $4]}
{269}{}{[Exchange $5]}
{270}{}{[Exchange 10 dollars]}
{271}{}{[Exchange ALL available dollars]}
{272}{}{What is it, a hole in your pocket? It happens.}
{273}{}{Yes, it is...}
{274}{}{Please.}
{275}{}{Thank you.}

{280}{}{I want to rent a room to rest.}
{281}{}{It will be worth it for you }
{282}{}{ hubbucks.}
{283}{}{Why so many?}
{284}{}{Because you're smooth-skinned.}
{1284}{}{Because you're smooth-skinned.}
{285}{}{This is racism!}
{286}{}{If you don't like it, sleep under the open sky.}
{287}{}{Okay, I'll pay for one night.}
{288}{}{Thank you, no need.}
{289}{}{I can't help you. All the rooms are, uh, occupied.}
{290}{}{Really? Are you not lying?}
{291}{}{It's a shame.}
{292}{}{If we had free rooms, I'd rather give them to super mutants than to you.}
{293}{}{I'll remember that, green.}
{294}{}{I didn't really want to. Forget about it.}
{295}{}{You don't have enough hubbucks for our service. Go earn something to start with.}
{296}{}{Okay.}