{100}{}{In front of you is Distraught.}
{101}{}{You see a glowing ghoul with a distraught look. He seems hostile.}
{102}{}{The distraught Gonzo does not react to you in any way.}
{103}{}{Ar-r-r!}
{104}{}{The ghoul himself is to blame. The pile has nothing to do with it.}

{200}{}{Hr-r-r... h-man... a ghoul... fear...}
{201}{}{I'm a friend, I want to help you.}
{202}{}{... friend... love... life...}
{203}{}{Yes, yes, your ghoul friends are worried about you. Let's go to them, they'll take care of you.}
{204}{}{Gonzo... wants... to friends...}
{205}{}{Let's go right now before you change your mind.}
{206}{}{No, no, it will work right now. Wait here a bit.}
{207}{}{Ah, you're crazy! I'm afraid of you!}
{208}{}{Life. And death. Your death!}