{100}{}{You see a ghoul.}
{101}{}{There's a ghoul in front of you. He's wearing a collar with a built-in shocker.}
{102}{}{Are you letting us go? Thank god! There are still good people on this earth.}

{110}{}{They have captured us and are forcing us to collect these things.}
{111}{}{Don't hit us, man. We are trying our best.}
{112}{}{One of us is distraught. Better not get caught in his eyes.}
{113}{}{These scavengers don't even know what these things are for.}

{120}{}{They make us work.}
{121}{}{Did they grab you too? Bad luck, friend.}
{122}{}{One of us is distraught. Better not get in his way.}
{123}{}{These scavengers don't even know what these things are for.}