{100}{}{You see Roy.}
{101}{}{Here is the leader of a gang of black scavengers.}
{102}{}{Adios.}

{200}{}{Hey, stop! This is our mining area. And we don't need you here. Get out of here.}
{1200}{}{Stop! This is our mining area. And we don't need you here. Go away.}
{201}{}{Ok.}
{202}{}{Why on earth would I listen to you?}
{203}{}{Are you looking for death or are you not friends with your head? So twist a little convolutions. This is OUR territory. Find yourself another factory and do whatever you want there. And don't get in here.}
{204}{}{OK.}
{205}{}{It was yours, and now it will be mine. It's simple.}
{206}{}{Where are you going? Have you lost all fear? Get out of here!}
{1206}{}{Where are you going? Have you lost all fear? Get out of here!}
{207}{}{Stop! This is our te... Damn, super mutant! All ready to fight!}
{208}{}{Oh, no, no, wait...}
{209}{}{OK. It's your own fault, asshole...}

{210}{}{I know what's going on here. You work without the permission of the Old City. And besides, you have enslaved the ghouls.}
{211}{}{Yes. And what?}
{212}{}{Nothing. Just curious how it happened.}
{213}{}{You have to let go of the ghouls.}
{214}{}{Do you feel sorry for ghouls? Their century has long passed. Let them bring at least some benefit.}
{215}{}{Why do you need ghouls?}
{216}{}{Because we are not made of steel. Do you understand? We don't have enough protection to work in a toxic zone. And ghouls can work there for hours without harm to their health. So let them work, they bring benefits to people.}
{217}{}{Clear.}
{218}{}{Why do you refuse to receive Seth's Seal?}
{219}{}{The riches of Old Times belong to the one who finds them. That's fair. And rightly so. We have the same rights to them as the undead. The hell we're going to leave them these riches!}
{220}{}{What are you looking for here anyway?}
{221}{}{Everything that will be useful for sale in the Hub. But the most relish here is the chips. There are guys in the north who will pay well for them.}
{222}{}{And now I want to know, what do you care about ghouls and our factory?}
{223}{}{None. Can I just leave?}
{224}{}{You have to let go of the ghouls.}
{225}{}{Do you feel sorry for Gulichek? Their century has long passed. Let them bring at least some benefit. Or will you work instead of them, eh?}
{226}{}{The hell with it. I'll just load the gun and shoot you all.}
{227}{}{Uh, no, this job is not for me.}
{228}{}{Then get out of our territory!}
{229}{}{OK.}
{230}{}{Why, a great idea. What needs to be done so that you let go of the ghouls?}
{231}{}{Surprised! Okay, bring 10 chips. This is enough for us to recoup our suffering. And after that we will go to trade north.}
{232}{}{Agreed.}
{233}{}{You've become quite impudent. It will be easier to take all of you out of here feet first!}
{234}{}{I'm still waiting for the chip. Come on, surprise me!}
{235}{}{Fuck you!}
{236}{}{I'm really trying. Soon they will be at your feet.}
{237}{}{Here is one chip.}
{238}{}{Here are the chips, }
{239}{}{pcs.}
{240}{}{That's what you need. There's more left }
{241}{}{ pcs. Come on, get moving.}
{242}{}{The last one? Ho-ho, and you're quicker than these guys. Great. You can have fun with your green-skinned friends. There's nothing else for us to do here. Ringing caps and hub women are waiting for us in the Maltese Falcon! Hey, brothers, get on your horses!}
{243}{}{I don't think anyone will miss you here.}
{244}{}{Bye.}
{245}{}{Ugh! I thought you were another ghoul. And you're just a freak. We don't need them. Get out of here.}

{250}{}{I was sent by the mayor of the Old Town.}
{251}{}{Yes? And what does he want?}
{252}{}{Nothing. I just had to see what you were doing here.}
{253}{}{He had some kind of suggestion. But I forgot which one. And it doesn't matter — I was going to kill you all anyway!}
{1253}{}{He had some kind of suggestion. But I forgot which one. And it doesn't matter — I was going to kill you all anyway!}
{254}{}{He has a suggestion. He will give you the Seal of Set and open a collaboration. But you have to collect chips from this factory for him in a short time and release the forced ghouls.}
{255}{}{So chips are important to gulichek, right? Ha, yes, we hit a gold mine! Okay, Seth's seal is an important thing, if you think about it. We won't have to carry tons of things far, we won't be oppressed and in general — we will now become important people in the city, right? There's just one "but".}
{256}{}{What is it?}
{257}{}{This factory is one fucking mole—rat hole! There are a lot of dangers and high radiation in places. And I also don't know a damn thing about all this technology. That's why I make ghouls work — they don't care about radiation and they know well what's what. Therefore, if the "big boss" wants to fulfill the contract quickly, someone will have to work with pens in the danger zone.}
{258}{}{Apparently, only I can speed up this process.}
{259}{}{Great. Bring 10 chips.}
{260}{}{Agreed.}
{261}{}{Completely oborzel? I'll collect the chips and give them to you instead. Get the fuck out of here!}
{262}{}{The last one? Ho-ho, and you're quicker than these guys. Great. You can have fun with your green-skinned friends. There's nothing else for us to do here. Ringing caps and hub women are waiting for us in the Maltese Falcon! Hey, brothers, get on your horses!}
{263}{}{The last one? Ho-ho, and you turned out to be more agile than these guys. Then we'll figure it out for ourselves. Jangling caps and booze are waiting for us in the Old Town. Hey, brothers, get on your horses!}
{264}{}{It's done. It's really time to go back to the Old Town.}
{265}{}{Don't get cocky. Now the ghouls are the masters here. You will work for them and follow their rules.}