{100}{}{You see a wandering ghoul.}
{101}{}{Here is one of the ghouls. There is a sly look in his distorted face.}
{102}{}{Hey, can you give me a lift to the Hub?}
{103}{}{Hi there.}

{200}{}{Hey, what a surprise! I didn't think there were purebloods here. Glad to meet you. I'm Bradley. Maybe you need to show the way?}
{201}{}{Bradley, have you met Steve Morgan?}
{202}{}{Nope. And why do you need it?}
{203}{}{He owes the Truckers something.}
{204}{}{I don't even know how to help you. Steve is afraid of purebloods and hides from them. However, I can contact him if you want and act as an intermediary.}
{205}{}{Thank you, Bradley. I would appreciate it if you find out what he wants for the product.}
{1205}{}{Thank you, Bradley. I will be grateful if you find out what he wants for the goods.}
{206}{}{ (leaves and returns soon) I found Steve. It requires 1000 hubbucks per fuel controller. Well, is it a deal?}
{207}{}{I don't have that much.}
{208}{}{Then there will be no deal. Goodbye.}
{209}{}{[Leave]}
{210}{}{Hey, wait, I actually have 1000 caps. Now bring the goods.}
{211}{}{That's what I understand — business people! Well, all the best, partner.}
{212}{}{Goodbye.}
{213}{}{And now give the caps back, you idiot.}
{214}{}{Aren't you lying? I was told that Steve Morgan had gone down this road.}
{215}{}{No, I'm not Steve Morgan. And why do you need it?}
{216}{}{Don't talk your teeth into me. Answer me, motherfucker, are you Steve Morgan?}
{217}{}{Yes, it's not me, it's not me!}
{218}{}{You're lying, bitch!}
{219}{}{Sorry. Where's Morgan then?}
{220}{}{Just don't kill me! Okay, I took the fuel controller. Truckers pay little. I was hoping to sell this thing in the Hub for a lot of money... listen, what about the deal? I will sell the controller to you for 800 caps, and you will resell it to Truckers, how do you like this option?}
{221}{}{But truckers pay half as much.}
{222}{}{Damn, that's right. But understand that this is my thing and I set the price for it, not them. So are you going to buy it?}
{223}{}{No.}
{224}{}{Then there will be no deal. Goodbye.}
{225}{}{[Leave]}
{226}{}{Wait, I've changed my mind. Here are 800 caps. Now bring the goods.}
{227}{}{If you don't want to give up the controller, then I'll take it by force...}
{228}{}{Yes. Here are 800 caps.}
{229}{}{Yes. Here are 1000 caps.}
{230}{}{Morgan still wants to sell the controller for 1000 hubbucks. Well, is it a deal?}
{231}{}{The conditions have not changed: 800 caps, and the controller is yours. So are you going to buy it?}