{200}{}{Hey, that's Private Heap! And is normie with him?}
{201}{}{Heap is my subordinate. And you should listen to me too.}
{202}{}{Geer! A bunch of traitors! Death is normal!}
{203}{}{Wait...}
{204}{}{We're friends with a bunch. Surprised, green?}
{205}{}{A bunch of friends with normie? Ho-ho-ho, I don't believe it! You are his slave-squire. Heap, you surprised me. Leave the slave aside and help us get the people out of that fortress.}
{206}{}{Don't you dare humiliate me, you green thing!}
{207}{}{You're talking too much, slave. I'm going to rip it out!}
{208}{}{Well, well.}
{209}{}{Heap, explain to them that I am not a slave and that they should leave people alone.}
{210}{}{A bunch of normies now? And that's not good! The heap has upset us all again. A bunch of traitors! Death is normal!}
{211}{}{Wait...}
{212}{}{Live, normie. You're lucky today.}
{213}{}{The Creator is looking at me from heaven. I will not disgrace his name!}
{214}{}{So you're letting me go, right? Thank you.}