{100}{}{You see a Trucker.}
{101}{}{In front of you is one of the guards of the caravan.}
{102}{}{Hush! Now the main thing is not to get caught in the eyes of the damn mutyars.}
{103}{}{Ugh! Now you can relax.}
{104}{}{OK, I'm coming for you. You know how to get out of here unnoticed, right?}
{105}{}{Yes, the right idea. We need to be below the grass so that we are not noticed.}
{106}{}{The trucker is safe.}
{107}{}{What do they allow themselves? A little more and I'll stuff their faces!}

{110}{}{Thank you for saving us.}
{111}{}{These super mutants would have already pulverized us if it weren't for you.}
{112}{}{It was a great fortune to meet you.}
{113}{}{The way back won't be any easier.}
{114}{}{I wonder if there's a bar here?}

{120}{}{Rutegra is no more. Who will negotiate with the ghouls?}
{121}{}{Without Rutger, the return journey will be especially difficult.}
{122}{}{Because of Rutger's death, we may not be paid at all.}

{130}{}{After the explosion on the island, it became clear that NOTHING could be taken out of here.}
{131}{}{Gustavo is trying to drive us out of town. He's crazy!}
{132}{}{Butler reached the military base. Soon we will be swimming in caps!}
{133}{}{}
{134}{}{Ghouls scurry like ants after napalm. This is the first time I've seen this. Well, that's good for our wallet.}