{100}{}{Here is a half-witted ghoul.}
{101}{}{You see one of the ghouls. He mumbles something indistinguishable.}

{110}{}{I am a man without a heart. Without a heart! Do you know why? Do you know?}
{111}{}{There was a monster in my heart. He ate the heart. He's gone.}
{112}{}{We don't have much time.}
{113}{}{We have one last chance left.}
{114}{}{Where's my skull scraper?}
{115}{}{We've all lost something. We are all lost.}
{116}{}{Sing something goodbye.}
{117}{}{I only want to see the light.}
{118}{}{Rest in peace, man.}
{119}{}{Welcome to hell, baby.}
{120}{}{*mumbling*}