{100}{}{You see Rutger.}
{101}{}{You see the head of the Truckers squad.}
{102}{}{Hush! All conversations will be in the camp.}
{103}{}{Rutger went to the caravan camp.}
{104}{}{Stay away, mutant! I'll fucking kill you!}

{200}{}{I expected to see anyone here, but not a normal person.}
{201}{}{I was sent to help the ghouls.}
{202}{}{The mutants were waiting for us in the ambush. Fortunately, we spotted them in time and turned them into warehouses. They don't dare to attack yet, but it's a matter of time. Can you sneak us out of here?}
{203}{}{I think I can. I managed to get here.}
{204}{}{Great. Then let's act one at a time. Get my subordinates out first.}
{205}{}{Okay.}
{206}{}{I'll distract the mutants while you get the guards out. Together, it will be harder for us to hide from super mutants.}
{207}{}{Okay.}
{208}{}{I'm left alone, right? Then let's get out of here!}
{209}{}{Leaving.}
{210}{}{It's dangerous to go out now. We need to wait a bit.}
{211}{}{I saw the mutants leave along the highway. But it could be a trap. Try to get my subordinates out first.}
{212}{}{It is unlikely that we will be able to leave unnoticed. How about attacking the enemy first?}
{213}{}{I can't risk my people. We will act with cunning. Get the guards out first.}
{214}{}{Soon there will be more people here than ghouls. It seems you need help.}