{100}{}{You see Rutger.}
{101}{}{Here is the head of the Truckers squad.}

{200}{}{We were very lucky that you were there. I don't have enough words to express my gratitude for saving our asses. Here, take a machine gun as a reward. How can I help you now?}
{1200}{}{We were very lucky that you were there. I don't have enough words to express my gratitude for saving our asses. Here, take a machine gun as a reward. How can I help you now?}
{201}{}{Let's just talk first.}
{202}{}{It seems you were carrying some kind of goods. Can I take a look?}
{203}{}{This product was intended for ghouls, but they were not interested in it... }
{204}{}{[Trade]}
{205}{}{Yes, by the way, I was hoping to buy some things from ghouls. But they don't want to get them, or they charge too much. I'll pay you if you find them for me in the ruins.}
{206}{}{OK. What kind of things do you need?}
{207}{}{No, I'm not going to search for old artifacts.}
{208}{}{What else do you need?}
{209}{}{That is all. Bye, Rutger.}
{210}{}{I want to ask you something else.}
{211}{}{I need to take another look at your products.}
{212}{}{I'm looking for these things: 1) water chip, 2) printed circuit board, 3) diagnostic board, 4) fuel controller, 5) rotorcraft drawings.}
{213}{}{If I find it, I'll bring it. Bye.}
{214}{}{About those old things you're looking for.}
{215}{}{Did you find anything you need?}
{216}{}{Not yet. If I find it, I'll bring it. Bye.}
{217}{}{Why do you need all these old artifacts?}
{218}{}{My boss Butch at the Hub will be terribly unhappy if I come back empty-handed. And the Hub needs a bunch of different things. And not just him. All of California survives due to ancient technology. And over time, it becomes less.}
{219}{}{Clear.}
{220}{}{Where can I find a water chip?}
{221}{}{This technology was used in the Vaults of the company "Vault-Tech". I know that there was one such Vault in the vicinity of San Diego. But I don't have the exact coordinates.}
{222}{}{Where can I find a printed circuit board?}
{223}{}{This technology can only be used in old printing houses. Residents of the Hub want to print their own money, and for this you need to launch a printing press. And just this detail they do not have.}
{224}{}{Where can I find a diagnostic board?}
{225}{}{This is a part from the autodoc. This technology was previously used in large hospitals.}
{226}{}{Where can I find a fuel controller?}
{227}{}{Funny thing. The merchant opposite says that this detail has already been brought from another camp. But he can't find her. Probably, the old fart lost it among all the unnecessary junk.}
{228}{}{Where can I find the drawings of the rotorcraft?}
{229}{}{Do you know about the military base on Coronado Island? And about the military airfield? So they were torn to shreds by nuclear explosions. But the ghouls say that there was also a factory that serviced military equipment. That's where the drawings could have been saved. And by the way — I have no idea what a "rotorcraft" is.}
{230}{}{I have }
{231}{}{.}
{232}{}{Great job! Here are your 400 caps. And I'll take this to the Hub.}
{233}{}{Thanks for the covers.}
{234}{}{You have completely closed the Truckers' contract. Great job!}
{235}{}{Good to see you.}
{236}{}{Bye.}
{237}{}{[Continue the conversation]}
{238}{}{It's good to see you... You, but not your mutant friend.}
{239}{}{It seems we are no longer welcome in the Shining. We'll be leaving this place soon.}

{240}{}{Where did your caravan come from?}
{241}{}{We're from the Hub. Our main office is there.}
{242}{}{Tell me about the Hub.}
{243}{}{It is the largest city in California. The center of bottle currency and trade. The main supplier of clean water. Most people and companies are located there. But there are also more problems there.}
{244}{}{I see.}
{245}{}{Phoenix also uses caps for exchange.}
{246}{}{Are there Hubbucks in Phoenix? Hmm! The Hub has been supporting the cap currency for many years. Probably, someone moved this idea to the east. Just what kind of people could cross the Toxic Divide between Arizona and California? This is interesting!}
{247}{}{Let's go back...}
{248}{}{Which company's office?}
{249}{}{Which company are you from?}
{250}{}{We are a trading company "Truckers" from the Hub. We transport goods from one settlement to another.}
{251}{}{And what kind of Hub is this, can you tell me?}
{252}{}{Must be hard work?}
{253}{}{Very. For a while we suffered from the raids of super mutants and all sorts of trash. Many people and Brahmins were lost until one person stopped it. The Asylum-Seeker - that's what everyone called him.}
{254}{}{Where did the super mutants come from here?}
{255}{}{These sons of bitches robbed caravans and kidnapped people to turn into freaks like them. No one even knew about them in the Hub. And then one person revealed their secret. Everyone was terrified.}
{256}{}{Go on.}
{257}{}{I know the story. You don't have to go on.}
{258}{}{Then that mysterious man and the guys from the Brotherhood of Steel stirred up their nest. But part of the green army survived and scattered across the Wasteland.}
{259}{}{Thanks for the story, Rutger. I didn't know all this.}
{1259}{}{Thanks for the story, Rutger. I didn't know all this.}
{260}{}{Thanks for the story, Rutger. Even in Inferno they didn't tell me about it.}
{261}{}{Speaking of super mutants. Do you know where they came from?}
{262}{}{Which office were you talking about?}
{263}{}{Some settlements were unlucky enough to get in their way. Therefore, people have been fighting mutants in recent years. No wonder some of the green fuckers ended up here — away from human settlements.}
{264}{}{What happened to this Asylum-Seeker?}
{265}{}{I don't know. He seemed to have evaporated. No one has heard from him since.}
{266}{}{Butler promises big orders. Looks like he's hit a gold mine.}