{100}{}{In front of you is a blind ghoul.}
{101}{}{You see one of the ghouls sitting in a wheelchair.}

{110}{}{Who are you? Identify yourself.}
{111}{}{Let me touch your face.}
{112}{}{So are you normal? Don't touch!}
{113}{}{Please don't hurt me!}
{114}{}{Leave the Glow alone!}

{120}{}{Who are you? Identify yourself.}
{121}{}{I know all the dead people in this hell. But I don't know you.}
{122}{}{You're a ghoul. And I'm a ghoul. Why haven't we met yet?}
{123}{}{I have been in darkness for eternity.}
{124}{}{Tell me, what does the Glow look like?}