{100}{}{You see Raymond, an autistic ghoul.}
{101}{}{You see one of the ghouls. He continuously counts and shifts something.}
{102}{}{The ghoul is happy to take your box and put it in his collection.}
{103}{}{This is my box, Bern!}
{104}{}{Boxes! Boxes! Boxes!}
{105}{}{By taking away the holodisk, you have greatly upset the ghoul. No one in San Ysidro will forgive you for this.}
{106}{}{GIVE ME BACK MY BOX, BERN!}
{107}{}{You have returned the holodisk to its owner. Your reputation has been restored.}
{108}{}{This is MY box, Bern!}

{110}{}{Bern! Bern! Bern!}
{111}{}{These people will be here all day, Bern!}
{112}{}{This is an unplanned visit, Bern!}
{113}{}{This is not a weekend visit, Bern!}
{114}{}{82! 82! 82 toothpicks!}
{115}{}{One toothpick, two toothpicks, three toothpicks...}
{116}{}{Five. Three. Five. Nine. Two. Six. Two.}
{117}{}{One box, two box, three box...}
{118}{}{Boxes, boxes, boxes...}
{119}{}{Give me back my boxes!}