{100}{}{In front of you is a ghoul.}
{101}{}{You see an ordinary ghoul.}

{102}{}{Oh, thank you, you're just in time.}
{103}{}{This food has cooled down! Okay, there's nothing you can do. Come here.}
{104}{}{You enjoy serving food, don't you? Thank you.}
{105}{}{This is exactly what I want!}
{106}{}{Thank you. But I don't have a tip.}
{107}{}{(}
{108}{}{) The customer has received his order.}
{109}{}{This customer has already received his order.}

{110}{}{Oh, mommies, it's a man!}
{111}{}{Smooth-skinned in the Glow? I don't believe my eyes!}
{112}{}{What do these normies allow themselves?}
{113}{}{We haven't had enough smooth-faces here yet.}
{114}{}{The smooth-skinned even got us here.}

{115}{}{This normie can be trusted.}
{116}{}{The Man in the Glow? Madman!}
{117}{}{The Normies made a mistake. They need time to figure it out.}
{118}{}{Perhaps not all smooth-faces are bad.}
{119}{}{We just want to live separately from the smooth-faced.}

{120}{}{The smooth-faced ones even got us here.}
{121}{}{Guess what my line is?}
{122}{}{The Dayglow is a wonderful city.}
{123}{}{It's a pity Harold isn't with us. He went north.}
{124}{}{Don't move! I dropped my brains... Haha, my favorite joke.}
{125}{}{And yet I will miss the Necropolis.}
{126}{}{The necropolis is now deader than ever.}
{127}{}{I still remember Seth's look with a shudder.}
{128}{}{Where is my hair? I left them in 2077. Ha-ha-ha!}
{129}{}{Sometimes I vaguely remember something from my past life.}

{130}{}{Everyone who could, rushed to Coronado Island.}
{131}{}{It's been a long time since there was such a movement among the ghouls!}
{132}{}{The one who opened the way for us to Coronado is our hero.}
{133}{}{Coronado is ours now!}
{134}{}{Here we will live now, with little things from Coronado!}

{135}{}{Eh, I had such plans for Coronado...}
{136}{}{Coronado could be a Klondike. Sorry.}
{137}{}{There is nothing left of Coronado Island at all.}
{138}{}{An old bomb exploded on the island. I wonder, by myself or with someone's help?}
{139}{}{I was very lucky that I was not on the pier at the time of the explosion.}

{150}{}{I'm standing, Chief! I'm standing rooted to the spot!}
{151}{}{My respects, Officer.}
{152}{}{I am a law-abiding citizen.}
{153}{}{It's nice to see the remnants of the law on the wastelands... Oh, it's not your badge!}
{154}{}{You must have almost a hundred years of service?}
{155}{}{Some played with the law like that. And in the end, they played the Third World War.}
{156}{}{Am I arrested?}