{100}{}{You see Mr. De-Santi.}
{101}{}{Here is a ghoul in a pre-war suit and a felt hat. A long scar runs through his face.}
{102}{}{This is Albert De Santi.}

{200}{}{You've come to the right place, kid. I'm Albert De Santi. And this is my establishment — the hotel and sanatorium "La Pension".}
{1200}{}{You're in the right place, baby. I'm Albert De Santi. And this is my establishment — the hotel and sanatorium "La Pension".}
{201}{}{[Next]}
{202}{}{Here you can forget about the harsh reality. Massage, retro cinema, sterile baths, radiation tan, delicious rat dishes, individual order for any whim — just tell me what you want?}
{203}{}{Seriously? Did you open a sanatorium in the middle of the scorched ruins? Yes, who will reach here?}
{204}{}{Relax, baby. It is in such a place that it is safest... Well, except for those lunatics across the street. They still treat the ghouls calmly, but it's a matter of time.}
{1204}{}{Relax, baby. It is in such a place that it is safest... Well, except for those lunatics across the street. They still treat the ghouls calmly, but it's a matter of time.}
{205}{}{Okay. I'll keep that in mind.}

{210}{}{What's on your mind, baby?}
{1210}{}{What's on your mind, baby?}
{211}{}{Nothing. See you later.}
{212}{}{See you later, Mr. De-Santi.}
{213}{}{See you again, Mr. De-Santi.}
{214}{}{Vs-s-s, a-ah! I love the smell of caps before going to bed. Okay, baby, you really deserve half.}
{215}{}{(shakes the bag with the caps) Ah! I like to listen to the clink of caps during lunch. Okay, baby, you really deserve half.}

#Quests
{220}{}{Have you tried to get rid of the distraught in the next building?}
{221}{}{I'll pay 100 hubbucks for each one. Do it and the money is yours.}
{222}{}{Don't you feel sorry for them? They're your brothers.}
{223}{}{Remember, kid, in this business you need to know only one thing: shoot first, shoot yourself, always shoot. And you won't be lost.}
{1223}{}{Baby, in this business you only need to know one thing: shoot first, shoot yourself, always shoot. And you won't be lost.}
{224}{}{Agreed. I'm just looking for a way to make money. Consider it done.}
{225}{}{No. I won't do it.}
{226}{}{All the distraught have been eliminated.}
{227}{}{Take it, baby. Easy money. I just stood there.}
{1227}{}{Take it, baby. Easy money. I just stood there.}
{228}{}{I like your approach to business, mister. I can continue to work for you. Maybe someone else needs to be eliminated?}
{229}{}{There is another problematic person. Do you know Derrick? He's bartering right at the entrance, taking part of the sales proceeds from me. It doesn't suit me! Do something with it.}
{230}{}{OK.}
{231}{}{Derrick won't bother you anymore. He swallowed lead.}
{232}{}{What a pity! Of course you don't know who did it, right? (winks and hands you 100 caps) I'll have to clean up a little shit at the entrance.}
{233}{}{[Leave]}
{234}{}{Derrick decided to reconsider his plans for the future. He is ready to work for you.}
{235}{}{Great job, kid. It's worth the increased fee. (winks and hands you 150 caps)}
{1235}{}{Great job, baby. It's worth the increased fee. (winks and hands you 150 caps)}
{236}{}{[Leave]}
{237}{}{Are you sure killing the insane is a good idea?}
{238}{}{Okay, whatever you want.}
{239}{}{Remind me, what did Derrick bother you with?}
{240}{}{He's bartering right at the entrance, taking part of the sales proceeds from me. It doesn't suit me! Do something with it.}
{241}{}{OK.}
{242}{}{Is there more work?}
{243}{}{One worthless body escaped to the Old City without paying me the caps due for services.}
{244}{}{What is the name of this body?}
{245}{}{His name is Kurt. He owes me 300 caps. Shake them out of him and half is yours.}
{246}{}{Okay.}
{247}{}{Here are the caps that Kurt owed — exactly 300 pieces.}
{248}{}{Vs-s-s, a-ah! I love the smell of caps in the morning. Okay, baby, you really deserve half.}
{249}{}{Well, of course.}

{250}{}{It seems like everything is falling apart here. Do you need an employee?}
{251}{}{There is such a thing. It's hard to cope alone. I really need an au pair.}
{252}{}{I can work for a reasonable fee.}
{253}{}{Sorry, but I can't help you with this.}
{254}{}{There is a better applicant. At least he doesn't have to pay. It is located in the storeroom opposite. His name is Mr. Handy. All you need to do is put him on his feet and appoint an administrator program. I'll pay 300 hubbucks for this non-dusty job.}
{255}{}{OK, I'll do it.}
{256}{}{Then get to work, kid. The details can be found anywhere, but I would look for the program in the Old Town.}
{1256}{}{Then get to work, baby. The details can be found anywhere, but I would look for the program in the Old City.}
{257}{}{Ok.}
{258}{}{I managed to launch the robot. But where can I get a program for him?}
{259}{}{The administrator's program. I would start looking in the Old Town.}
{260}{}{I think the administrator vacancy is now closed.}
{261}{}{Great job, kid. Here's your reward. By the way, I have more tasks for you.}
{1261}{}{Baby, great job. Here's your reward. By the way, I have more tasks for you.}
{262}{}{What is it?}
{263}{}{I see.}
{264}{}{Not interesting. I don't want to repair old equipment.}
{265}{}{One of the clients ordered an old cult movie, "Deep Throat". What, you haven't heard of this? What backwardness! In short, someone in San Ysidro has it. Get it for me and I'll share some of the money.}
{1265}{}{One of the clients ordered an old cult movie, "Deep Throat". What, you haven't heard of this? What a shame! In short, someone in San Ysidro has it. Get it for me and I'll share some of the money.}
{266}{}{OK.}
{267}{}{Where do you say you can find that movie?}
{268}{}{One of the ghouls in San Ysidro has it. I don't know exactly.}
{269}{}{I see.}
{270}{}{Here's the movie you were looking for.}
{271}{}{I love the old classics. But I don't advise you to watch. You're too young for that, kid. Just take your money and forget it.}
{1271}{}{I love the old classics. But I don't advise you to watch. You're too young for that, baby. Just take your money and forget it.}
{272}{}{OK.}
{273}{}{There is one more task. The payment will be good — as much as 500 hubbucks. But remember, baby, I will not fail.}
{274}{}{Tell me what to do.}
{275}{}{Wait, mister. Not another word! You're talking about serious things. I refuse.}
{276}{}{Somewhere on the way to San Ysidro, a courier robot with an important detail got lost. I need this detail. Bring it to me. Come on, move your ass, baby.}
{1276}{}{Somewhere on the way to San Ysidro, a courier robot with an important detail got lost. I need this detail. Bring it to me. Come on, move your legs, baby.}
{277}{}{[Leave]}
{278}{}{And you're thinking, kid. Okay, go for a walk. I don't need you anymore.}
{1278}{}{And you're thinking, baby. Okay, go for a walk. I don't need you anymore.}
{279}{}{[Leave]}
{280}{}{Can you tell me exactly where the courier robot is?}
{281}{}{Somewhere on the way to San Ysidro. Most likely somewhere on the highway.}
{282}{}{I see.}
{283}{}{Here's the part you were looking for.}
{284}{}{Good girl! I've never had such a clear—cut kid in a gang... er, I mean, in a team. Here's your reward. And perhaps I don't have any new tasks anymore. You can rest, baby.}
{1284}{}{Good girl! I knew right away that you wouldn't let me down, baby. Here's your reward. And perhaps I don't have any new tasks anymore.}
{285}{}{[Leave]}
{1285}{}{Then I'll go hang out. Come on, partner.}
{286}{}{By the way, why is this part signed as Ed's property?}
{287}{}{Don't ask too many questions, kid. I'm paying you for this.}
{1287}{}{Don't ask too many questions, baby. I'm paying you for this.}
{288}{}{[Leave]}
{289}{}{Hey, baby, did you get anything wrong? I was told that you gave the part to San Ysidro. What the hell does that mean?}
{1289}{}{Hey, baby, did you get anything wrong? I was told that you gave the part to San Ysidro. What the hell does that mean?}
{290}{}{It's not your thing, mister.}
{291}{}{If you think about it, it is. But what does it matter to you? You work FOR ME. Damn, you really upset me, baby. I don't want to see you. P'shel out!}
{1291}{}{If you think about it, it is. But what does it matter to you? You work FOR ME. Damn, you really upset me, baby. I don't want to see you. Get lost!}
{292}{}{[Leave]}
{293}{}{And now let's move on to really serious matters. A camp of black scavengers has settled nearby. They're combing through MY ruins, and they're not going to pay the tax. They have to work for me, and if they don't want to, then let them get off my land! Go deal with them.}
{294}{}{It will be done.}
{295}{}{I refuse. Your bandit ambitions were not part of my plans. I'm not going to be an accomplice in murky schemes.}
{296}{}{You shouldn't be upsetting me. I thought we were friends. And it's hard to find friends nowadays. So finally let me give you one piece of advice: go look around.}
{297}{}{I refuse to solve your problems with scavengers.}
{298}{}{The problem with the scavengers has been solved.}
{299}{}{And again, you don't let me down.}

#Services
{300}{}{I want to relax.}
{301}{}{Sorry, kid, but my services are not suitable for smooth-skinned people.}
{1301}{}{Sorry, baby, but my services are not suitable for smooth-skinned.}
{302}{}{Very sorry.}
{303}{}{Don't fit at all? But my caps are begging to be spent.}
{304}{}{Admit it, you just hate smooth-skinned people, right?}
{305}{}{It's just business, kid. It's not in my interest for the client to be hard boiled. But since you're so sensitive, I can tell my ghoul friends that you're a good smooth-skinned one. It will cost you in }
{1305}{}{It's just business, baby. It's not in my interest for the client to be hard boiled. But since you're so sensitive, I can tell my ghoul friends that you're a good smooth-skinned one. It will cost you in }
{306}{}{No need. I achieve a good reputation by honest means.}
{307}{}{It's a deal.}
{308}{}{Waiting for the lid, baby. Reputation is expensive.}
{1308}{}{Waiting for the lid, baby. Reputation is expensive.}
{309}{}{OK.}
{310}{}{(quickly counts the caps) I give you my word — I'll come up with an excellent and plausible legend for you. All ghouls will be delighted.}
{311}{}{I'm counting on you.}
{312}{}{Just let's not cheat. I don't like it.}
{313}{}{ hubbucks. Is it a deal?}

{320}{}{To begin with, I advise you to take healing baths with my charming bath attendant. And if there is nowhere to put time and money, then I can offer a full rest at the hotel with watching movies, music and medical procedures. A service specifically for mutants and ghouls!}
{321}{}{I think I'll do with a simple ablution for now. How much does it cost?}
{322}{}{ caps.}
{323}{}{Good. Here are the caps.}
{324}{}{I'll think. And how much does a full wellness complex cost?}
{325}{}{Maybe another time.}
{326}{}{I was interested in the second option.}
{327}{}{For }
{328}{}{ caps we will arrange a full range of procedures from uranium ablutions and massage to meditation and mushroom smoking. An ordinary ghoul then throws off the dirt, how much he has been saving up for ten years.}
{329}{}{I like that! Here are the caps, I'm all at your disposal.}
{330}{}{I don't have that much money. But taking a bath would probably be nice.}
{331}{}{Yes, for such money, I will arrange all these procedures for myself! Be.}
{1331}{}{Yes, for such money, I will arrange all these procedures for myself! Be.}
{332}{}{The medical procedures have done you good. Your stamina has increased.}
{333}{}{Medical procedures have restored your health. Even though you expected something more.}

{350}{}{I have one last task left for you. There is a super mutant named Flowers. Now his lonely worthless body is trampling the ground somewhere on Highway 805 in search of its destination. Bring him to me. Tell him I'll take care of him if he works for me.}
{351}{}{OK.}
{352}{}{Flowers is already here.}
{353}{}{He's already here, baby! Flowers will be an excellent defense of my possessions. And I don't have a job for you anymore. Here's your last fee. Congratulations on your retirement.}
{354}{}{[Leave]}
{355}{}{Flowers is dead.}
{356}{}{Damn bad news. And I don't like bad news. You've upset me, baby. Go away. I don't have a job for you anymore.}
{357}{}{[Leave]}
{358}{}{Flowers didn't want to work for you. He became a prospector.}