{100}{}{This is Frank.}
{101}{}{You see a ghoul in a business suit and hat, just like in the good old days.}
{102}{}{Thank you, friend. Without you, this story could have ended very badly.}
{103}{}{Don't touch me, smooth face! I'm on edge right now.}
{104}{}{Sorry, I'm too excited to talk right now.}

{110}{}{Jane, if we don't find him, I'll stop drinking. I promise.}
{111}{}{Prepare for the worst, Jane.}
{112}{}{It would have happened someday anyway.}
{113}{}{Don't cry. Otherwise, I'll cry too.}