{100}{}{This is Jane.}
{101}{}{In front of you is a dead woman in an ordinary pre-war dress.}
{102}{}{Thanks for saving Donovan. We were already preparing for the worst.}
{103}{}{Sorry, I'm too excited right now.}

{200}{}{(Jane)... Frank, I feel like something's happened to him. He would have been back long ago... Oh, we're being overheard.}
{1200}{}{(Frank)... I'm telling you, Jane, he's in trouble! Otherwise, he would have returned long ago... Hey, are you eavesdropping on us, smooth face?}
{201}{}{What do you seem excited about?}
{202}{}{(Frank) None of your business, man. This is our dead business.}
{203}{}{[Next]}
{204}{}{(Jane) Oh, sorry Frank, he's on edge right now.}
{205}{}{So what happened?}
{206}{}{I forgive you this time. Now tell me what the hell it means.}
{207}{}{(Jane) We lost our friend, Donovan. He went to San Ysidro and didn't come back. No one saw him in San Isidro either.}
{208}{}{[Next]}
{209}{}{(Frank) Jane, what the hell are you talking about in front of that smooth face? We've had enough of the smooth-faced ones. I wouldn't be surprised if Donovan was a victim of scavengers.}
{210}{}{[Next]}
{211}{}{(Jane) Frank, we need help, isn't it obvious?}
{212}{}{[Next]}
{213}{}{(Frank) Hmm, listen, smooth face, don't you have other things to do? Either help us, or go somewhere. I don't want to mess with people. Is that clear? But we could use some help.}
{214}{}{I'll help you. Whether you want it or not. Just to show you that not all people are bad.}
{215}{}{(Jane) Oh, how great! You see, Frank, you can always negotiate. Thank you, man. We will be waiting for news from you.}
{216}{}{Okay. See you later.}
{217}{}{I really don't care about your problems. Be there.}
{218}{}{(Frank) Hey, hey, hey, don't be in such a hurry! Just in case, keep in mind that our friend Donovan is somewhere in the ruins on the way to San Ysidro. If you meet him... well, at least remind him of us, okay?}
{219}{}{Okay. See you later.}
{220}{}{(Jane)... Frank, I feel like something's happened to him. He would have been back long ago... Oh, we're being overheard.}
{221}{}{[Next]}
{222}{}{(Frank) Hmm. I don't remember your face. But it's still good to see you. Will you give us some time?}
{223}{}{What do you need from me?}
{224}{}{(Jane) We lost our friend, Donovan. He went to San Ysidro and didn't come back. No one saw him in San Ysidro either.}
{225}{}{Let me guess — and you'll ask me to find him?}
{226}{}{And you're smart for a ghoul. Anyway, we need help. Donovan is somewhere in the ruins on his way to San Ysidro. If you meet him... Well, try not to leave in trouble, okay?}
{227}{}{Okay. See you later.}

{230}{}{Any news about our friend?}
{231}{}{Not yet. I'll keep looking.}
{232}{}{Where do you think he might be?}
{233}{}{He went to San Ysidro. But I didn't get there and didn't come back. So he could be somewhere along the way.}
{234}{}{Maybe he just found a case of beer and decided to open it alone?}
{235}{}{I see. I'll keep looking.}
{236}{}{What are you talking about? Donovan was the brain of our humble company.  .........}
{237}{}{I have some bad news. Here's Donovan's body. Donovan is dead.}
{238}{}{Why didn't you say Donovan was short? No wonder it was so hard to find.}
{239}{}{(Jane) Oh, my God, Donovan, wake up! (Frank) Donovan, you and your jokes again! Stop fooling around!}
{240}{}{Em. Are you stupid? He's dead. It couldn't be deader.}
{241}{}{You will have to accept the truth. The body was torn in half. This is incompatible with life.}
{242}{}{Look, he just needs to be taken to the doctor. Find Talius in San Ysidro. He'll get Donovan on his feet. We won't do it as fast as you.}
{243}{}{There's something wrong with your head! Maybe at least this Talius will explain to you that it is impossible to revive a dead person.}
{244}{}{Are you serious? Well, I hope this will calm you down a little.}
{245}{}{Don't waste your time! Take Donovan to Talius.}
{246}{}{Okay, okay.}