{100}{}{This is Donovan.}
{101}{}{You see a robot inside which Donovan's brain functions.}

{110}{}{I'm a robot now. It's so unusual. And so great!}
{111}{}{I feel much better in this body!}
{112}{}{It's like I've grown younger in a hundred years.}
{113}{}{I've never felt so great as I do now.}
{114}{}{I think all dead people should get this shape.}
{115}{}{Pathetic people, you can't even imagine how fragile you are!}
{116}{}{De Santis tried to kill me. Thank him for that.}
{117}{}{}
{118}{}{}
{119}{}{}