{100}{}{You see Isaac.}
{101}{}{Here is a ghoul in worn-out work clothes.}
{102}{}{I'll have to do everything myself again...}
{1102}{}{I'll have to do everything myself again...}
{103}{}{Great job... for a smooth-skinned person.}
{104}{}{This is the engine room. I hope everything works here, otherwise the station won't be of any use.}
{105}{}{We're already close. Take me to the console in the control room.}

{200}{}{I never thought to see normie here. You must have an awl in your ass?}
{201}{}{Brand new and straight into hell? That's what I understand! But be careful, it's very dangerous here.}
{1201}{}{New girl and straight into hell? That's what I understand! But be careful, it's very dangerous here.}
{202}{}{Senor Gustavo sent me. How can I help you?}
{203}{}{And what are you doing here?}
{204}{}{We are trying to do the impossible here — to force the dam to give electricity. That's just from above it was captured by military robots during the nuclear war. They don't let anyone in.}
{205}{}{And where do you need to get to?}
{206}{}{I need to get to the control center. It's somewhere underground. Try to find a safe way. Otherwise, I'm not ready to become a part of the local wonderful nature yet.}
{207}{}{Good. But first I'll try to do it myself.}
{208}{}{Then come with me. I know how to bypass robots.}
{209}{}{First tell me, what is this place?}
{210}{}{This is the Bonita Dam. It was created to store water. The power plant was built here already in times of crisis, when there was a shortage of liquid fuel. Its power is barely enough for the needs of Glow. But there is no other surviving station in the city.}
{211}{}{I need to get to the control center. It seems we are on the right track.}
{212}{}{This is the control center. It seems that there has not been a cleaning done for a long time. Nothing, we are not used to... And this, apparently, is the control panel? Wait a minute... so... Done. Hmm. The station is mothballed. I'll have to work with the handles.}
{213}{}{What should I do?}
{214}{}{We need to start the second turbine in the engine room. It may take a lot of effort there.}
{215}{}{Clear.}
{216}{}{This is the engine room. But now we need to get to the control center.}
{217}{}{Wait here.}
{218}{}{Follow me.}

{220}{}{This dam will remain a pathetic piece of concrete until we make it work for the benefit of the Glow.}
{221}{}{Don't tell me you're lost here.}
{1221}{}{Don't tell me you're lost here.}
{222}{}{Wait a bit. I'll be back soon.}
{223}{}{What should I do now?}
{224}{}{The second turbine is spinning.}
{225}{}{Hmm, if the turbine is working, then why is there no current coming from it? There must be a gap in the power grid. Check carefully the entire chain from the turbine to the switch.}
{226}{}{You're kidding...}
{227}{}{OK.}
{228}{}{It seems that there is no gap in the network now.}
{229}{}{Really... Now I will supply current to the substation... Damn it, the substation is not responding. Probably, it was also preserved. You'll have to go there and run it. Remember: we need to direct energy strictly to the power lines in San Isidro and the Old Town. The remaining circuits need to be disconnected.}
{230}{}{Yes!}
{231}{}{It seems like I'm doing all the work here...}
{232}{}{Bonita! Do you hear this wonderful crackling in the transformers and the hum in the wires? It's been a long time since I've heard anything like this. Thank you, amigo. I hope Gustavo will reward you well. Here, take a Geiger counter. You'll need it on your way to San Ysidro.}
{233}{}{Bye, Isaac.}
{234}{}{But impassable ruins stretch between the power plant and residential areas...}
{235}{}{You're thinking! Even though you're not from our century. Although we are ghouls, we have already launched several working robots and prepared power lines. You don't need much for this.}