{100}{}{Here is the Pec.}
{101}{}{You see a ghoul with a twisted spine. His head was thickly overgrown with small glowing mushrooms.}
{102}{}{No problem, sir. As soon as I'm done cleaning up, I'm out of here.}

{120}{}{I feel like a million.}
{121}{}{I'm Peck. Paxter. Do you want to sleep with me?}
{122}{}{Do you know how many caps I have? And I don't have caps. And I'm happy!}
{123}{}{I didn't have any money before. Now no one has any money.}
{124}{}{I live like the star of a TV show.}
{125}{}{This is the best place in the world. Wee-ee-ee!}
{126}{}{It's time for Pack to take his medicine. * Yum-yum * Bue-uh...}
{127}{}{Cops! It's the cops! But no... Just a flashback...}
{128}{}{It's okay, I'm fine... it seems.}
{129}{}{Without foreigners, Glow is not Glow.}
{130}{}{I'm not homeless. I'm free from home!}
{131}{}{I don't do drugs. My brain produces it by itself.}
{132}{}{Holy macaroni!}

{200}{}{Whoa, whoa, bro! Don't pick here, you're on my private property. Well... I don't mind you being here. But keep in mind.}
{201}{}{Seriously? Do you live in a sewer?}
{202}{}{Yes, I'm homeless. And what? But I live richly! I live in the most picturesque place of Glow. Do you understand?}
{203}{}{Have you tried to move to the rest of the city?}
{204}{}{Why? I'm fine here. There is a lot of food, there is no need to observe the laws, peace and quiet.}
{205}{}{I'm afraid to ask, what do you eat here?}
{206}{}{No wonder you're overgrown with mushrooms. Have you ever seen yourself in the mirror?}
{207}{}{Everything grows in the valley. I have enough. Here, do you want mushrooms?}
{208}{}{Come on. What will you ask in return?}
{209}{}{No need. I'm not into that.}
{210}{}{The local climate is too humid. There was no such thing in the Necropolis. But you don't have to go far to take the medicine. Do you want one too?}
{211}{}{You'll see — you'll come back for a new dose.}
{212}{}{Yeah.}

{220}{}{Hey, how are you?}
{221}{}{How are you, bro?}
{1221}{}{How are you, sister?}
{222}{}{What is it, kid, got lost in the area?}
{1222}{}{What is it, baby, got lost in the area?}
{223}{}{Be.}
{224}{}{I need more of these glowing mushrooms.}

{230}{}{How do I get out of here?}
{231}{}{The nearest bridge is destroyed, bro. That's bad luck, right? Go up to the mall, from there turn onto federal highways. And now you're free!}
{232}{}{Okay, I'll go. Have a good stay.}
{233}{}{I'll pay 300 caps if you take me to San Ysidro.}
{234}{}{I know what you mean. I understand. Peck knows all the local trails and dangerous places. You will not pass the valley without me.}
{235}{}{Then lead the way. Here }
{236}{}{ caps.}
{237}{}{Not now. Later.}
{238}{}{I need to get to the power plant. Will you take it for 500 caps?}
{239}{}{I will pay 1500 caps if you take me to the Old Town along safe paths.}