{100}{}{You see Phil.}
{101}{}{In front of you is an elderly ghoul with glasses. He sways weakly back and forth in his chair.}

{200}{}{Hey, are you a character in what book, dear? I don't remember reading about you.}
{201}{}{What are you talking about, you old fart?}
{202}{}{Oh, sorry, sorry! It is already impossible to fantasize. By the way, I'm Phil. Kind of like a scientist, if I may say so.}
{203}{}{Nice to meet you, Phil. It is rare to meet learned people in our time.}
{204}{}{Hello, Bibliophile.}
{205}{}{I'm a living person, not a character.}
{206}{}{Mm-hmm? (peering at you through his glasses) How can you be so sure? Well, anyway, it can't be proved or disproved anyway. By the way, I'm Phil. Kind of like a scientist, if I may say so.}
{207}{}{Hmm. Perhaps this is a heroic novel or something like that.}
{208}{}{Oh, I like it when people can make fun of themselves. Not like all those sullen types behind the wall. They have become so serious with the construction of their city, which they have not been all their lives. By the way, I'm Phil. Kind of like a scientist, if I may say so.}
{209}{}{}

{210}{}{Can I help you with something?}
{211}{}{No, nothing.}
{212}{}{Hey, are you a character in what book, dear? I don't remember reading about you.}
{213}{}{Ah, sorry, sorry! It is already impossible to fantasize.}
{214}{}{It looks like you're completely immersed in literature.}
{215}{}{Oh, I like it when people can make fun of themselves. Not like all those sullen types behind the wall. They have become so serious with the construction of their city, which they have not been in their entire lives.}
{216}{}{It's natural.}
{217}{}{Mmm? (peering at you through his glasses) How can you be so sure? Well, anyway, it can't be proved or disproved anyway. God, what a mediocrity!}
{218}{}{Life is generally boring if you don't cheer yourself up.}
{219}{}{I won't argue.}

{220}{}{Who are you?}
{221}{}{I'm Phil. Kind of like a scientist, if I may say so. The brain of this city, if you will.}
{222}{}{Really?}
{223}{}{Well, I helped with everything that requires pre—war knowledge - from old reference books to programs for Mr. Assistants.}
{224}{}{I see.}
{225}{}{I'm also a world chess champion. No one, not even the cunning commies, could beat me. But these were life-and-death parties!}
{226}{}{Curious.}
{227}{}{How about a game of chess? I will definitely beat you and break the world record.}
{228}{}{How about a game of chess? I will defeat you and break the world record.}
{229}{}{What are you? Don't make the old man laugh! You don't stand a chance. I am the only one who was able to beat the artificial intelligence of ZAX. What to say about you.}
{230}{}{I still want to try.}
{231}{}{Waste of time.}
{232}{}{Then forget it. I'll do something else.}
{233}{}{You've already made the mistake of saying I don't have a chance. There are always chances. I challenge you to a duel.}
{234}{}{Oh, it sounds tense, like in a good novel. I'll give you one chance. Only one batch. If you beat me, you will get access to my library.}
{235}{}{I need to prepare for the match. See you later.}
{236}{}{I'm ready for a battle on the chessboard. Let's get started!}
{1236}{}{I'm ready for a battle on the chessboard. Let's get started!}
{237}{}{Not bad. Not bad for an amateur. However, you still need a lot of practice to defeat me.}
{238}{}{Well, it didn't work out.}
{239}{}{Can we change the subject?}
{240}{}{Have you defeated me? Extraordinary!}
{241}{}{Do you want to play a game of chess?}
{242}{}{Now do you see that you should not belittle your rivals?}
{243}{}{Surely it was an accident. Sorry I broke your world record.}
{1243}{}{Surely it was an accident. Sorry I broke your world record.}
{244}{}{I don't understand how this could happen. After all, for 90 years I have studied ALL possible moves in chess. But this is your move... Why couldn't I have predicted it? Probably, without rivals, I simply squandered my skills. That's why it's important to have an enemy! We should definitely learn from each other.}
{245}{}{By the way, yes. Will you let me read your library?}

{250}{}{What can I do in this city?}
{251}{}{Let me think. Of course, the head of the city has some tasks. He is trying to bring the city back to life, and also to cope with the flow of strangers from the north. The others have problems too. Everyone has their own.}
{252}{}{And it is impossible to be more specific?}
{253}{}{Sorry, but I recently got carried away with this wonderful novel and completely stopped following what is happening in the city.}
{254}{}{Clear.}
{255}{}{What are you reading?}
{256}{}{Right now I'm reading some old book about the conquistadors in Spanish. Boring. Not mine.}
{257}{}{Do you need a specific book? I can search.}
{258}{}{Okay, whatever. Read on.}
{259}{}{Oh, there is one such book! Right before the war, Mortimer's new book was announced in San Diego. I'm curious what kind of nonsense he could make up there about this beautiful city.}
{260}{}{Where can I find her?}
{261}{}{Somewhere in the ruins, apparently. I don't know for sure.}
{262}{}{Okay, I'll look.}
{263}{}{Then look for it yourself. I have more important things to do.}
{264}{}{You're lucky. I just have this book.}
{265}{}{I found Mortimer's new book.}
{1265}{}{I found Mortimer's new book.}
{266}{}{A new book! Ah, it's been a long time since I've felt such awe of a fresh edition. Let's see what Mortimer has scraped up sensational about San Diego... Oh, yes, you're probably waiting for some kind of payment. Here are 100 hubbucks. And now go, go, don't bother reading!}
{267}{}{Bye.}

{270}{}{Right now I'm reading an old book about the conquistadors in Spanish. Boring. Not mine.}
{271}{}{Right now I'm reading the Vancouver phone directory. A very monotonous narrative.}
{272}{}{Right now I'm reading stories about the latest oil wars. You know, then whole states seized our oil tankers. It's good that it's already over.}
{273}{}{Right now I'm reading a set of rules for flying on an airship. Are you laughing? Well, someday someone will fly them into the sky again. Trust me.}
{274}{}{Right now I'm reading a story about how the Communists took over the United States and built a totalitarian state here. It looks pretty good so far.}

{280}{}{I need a program for Mr. Assistant.}
{281}{}{It's not difficult. But I'm so busy with this beautiful book. I can't tear myself away!}
{282}{}{And if I bring you more books?}
{283}{}{More books?! Yes! Bring me the five surviving books, and I'll make this program. Easy.}
{284}{}{Good.}
{285}{}{I have just such books. Here they are.}
{286}{}{Ah, a new addition! Okay, there's nothing you can do, you'll have to break away from reading. Now I'll make you a program. What did you say you had to do there?}
{287}{}{The program of the hotel administrator...}
{288}{}{Or maybe you'll just help a good person?}
{289}{}{I will certainly help a GOOD person IF I see him.}
{290}{}{Ham!}
{291}{}{So I'm definitely not a role model for you. Sad.}
{292}{}{Forget. I have books. Here they are.}
{293}{}{My friend, what kind of selfishness? We're all doing the same thing here. Come on, help me with this fucking program!}