{100}{}{You see a ghoul.}
{101}{}{You see a nasty-looking ghoul with one eye. His teeth froze in an eternal grin.}
{102}{}{Hello stranger.}
{1102}{}{Hello, stranger.}
{103}{}{Come closer, don't be afraid. I just want to "touch" your soft smooth skin...}
{104}{}{Run, normie, run! If I catch it, I'll cook it for dinner.}
{105}{}{There's really nothing special here. Enjoy the afterlife.}

{200}{}{Hey, you cheeky face. Come here. Are there caps?}
{201}{}{There are.}
{202}{}{Give me 10 caps. And hurry up.}
{203}{}{Okay, here are 10 caps. All for you guys.}
{204}{}{Watch your tongue. We're not playing games here. And now — disappear.}
{205}{}{As you say...}
{206}{}{Here are 10 caps.}
{207}{}{Good boy... I see you're also rich. Let's have 10 more caps.}
{208}{}{Here are 10 more caps. Are you satisfied now?}
{209}{}{That's all there is. Are you happy now?}
{210}{}{Quite. I love simpletons like you. Even though I don't get that drive anymore, like in the old days. But why am I talking to you? Disappear.}
{211}{}{Go to hell.}
{212}{}{Don't forget, you're nobody in this town. Better disappear.}
{213}{}{With great pleasure.}
{214}{}{Okay, that's all there is, but there are less than 10 pieces here.}
{215}{}{Will go. Now get out of here while I'm being nice.}
{216}{}{No.}
{217}{}{I do not believe. Show me what's in your backpack.}
{218}{}{Here, look.}
{219}{}{I thought so. Only lies can be heard from smooth-faced people. As a punishment for cheating, I'm taking ALL your caps. Now disappear.}
{220}{}{Whatever you say...}
{221}{}{Get my cap back, you bastard!}
{222}{}{Here, look.}
{223}{}{Ugh! You're of no use. Get off my street.}
{224}{}{With great pleasure.}
{225}{}{Just touch my things and you will be left without the last fingers.}
{226}{}{[Run as fast as you can from a beggar]}
{227}{}{[Pass by]}
{228}{}{Stop! I'm talking to you, fucking normie.}
{229}{}{[Ignore]}
{230}{}{What do you want?}
{231}{}{Okay, I have the caps. How much do you need?}
{232}{}{But I don't have caps.}
{233}{}{Go to hell.}
{234}{}{Why would I give you caps?}
{235}{}{This is the price for having to put up with your nasty smooth face in my beautiful city. Give me the caps, now.}

{250}{}{Senor, my respects! For the first time in the city? I will show you all the sights. For just 10 caps.}
{1250}{}{Senora, my respects! For the first time in the city? I will show you all the sights. For just 10 caps.}
{251}{}{Okay, here are 10 caps.}
{252}{}{Sorry, amigo, I'm broke. Maybe another time.}
{253}{}{Mucho gracia... Oh, yes, there's the monorail, and there's the Mexican border. There is another ghoul camp in the north. That is all. Be...}
{254}{}{You didn't tell a damn thing, you fucking bred!}
{255}{}{It was... educational tour. Thank you.}
{256}{}{Hi there.}
{257}{}{Bye.}
