{100}{}{There's a bunch in front of you.}
{101}{}{You see a super mutant. He is wearing an army helmet and trousers made of camouflage fabric.}

{102}{}{Don't you dare touch the shadows, normie!}
{103}{}{I won't forgive you for that, normie!}
{104}{}{My brothers, I'm with you!}
{105}{}{Are my brothers here? Ho-ho, then you know whose side I'm on.}
{106}{}{Don't you dare touch the shadows!}
{107}{}{I won't forgive you for that!}
{108}{}{My brothers, I'm with you!}
{109}{}{I see my brothers in arms. It's better not to anger them.}

{110}{}{The Creator was right — all of you had to be converted!}
{111}{}{Hello.}
{112}{}{[take in the party]}
{113}{}{[remove from party]}
{114}{}{[remove weapon from hand]}
{115}{}{Later.}
{116}{}{Right. You don't have to fight. A bunch of approves.}
{117}{}{}
{118}{}{}
{119}{}{}

{150}{}{Dead people live here. They don't like outsiders. But they will not attack themselves.}
{151}{}{The largest ghoul camp. Normies also live here.}
{152}{}{The very heart of the ruins. This place is poorly explored.}
{153}{}{I haven't been further than the outpost yet.}
{154}{}{See the island? There was a military base there. But it is destroyed.}
{155}{}{}
{156}{}{If you meet a wild animal, don't be afraid, the Pile will protect you.}
{157}{}{A bunch can't do that. The pile is too big.}
{158}{}{You don't treat ghouls well. The pile is no longer on your team.}
{159}{}{A bunch of people leave your company until you fix your reputation.}

#The first dialog
{200}{}{A man among ghouls? Suspicious!}
{201}{}{No, I... it doesn't matter. Just don't touch me, big guy. Agreed?}
{202}{}{Even a person scolds a bunch. Ghouls don't want to see a bunch either. Nobody needs a bunch!}
{203}{}{Whoa, whoa, take it easy! I don't want you to be angry. It just seemed to me that ghouls didn't get along with people like you.}
{204}{}{People are not welcome here either. The bunch was chased out of the squad. The ghouls said they would take care of the Pile if he was good and would help. A lot of trying. But they still don't like him.}
{205}{}{Who needs you, a mountain of green meat?}
{206}{}{The bunch was chased out of the squad. The ghouls said they would take care of the Pile if he helped at the mine and behaved well. A lot of trying. But they still don't like him.}
{207}{}{Sadly. But naturally. }
{208}{}{What were you hoping for, you idiot? You should have kept order while you were in the squad.}
{209}{}{A little more — and a lot of respect. Ghouls will know how good I am. I will help the ghouls, even if they don't want it.}
{210}{}{Great. I also help ghouls. Maybe we can join forces? You will protect me on the road, and I will help you earn respect.}
{211}{}{I have business here. What are you doing here? Are mutants with ghouls for one thing?}
{212}{}{Ghouls will never accept you. Forget about them, help me. I need your muscles.}
{213}{}{That's very noble of you. Well good luck. And it's time for me to move on.}
{214}{}{Go, man. I won't touch you as long as you don't touch the ghouls.}
{215}{}{Bye, A bunch.}
{216}{}{Maybe we'll unite? I need your muscles on the road. And I will help you regain respect.}
{217}{}{A mutant and a human in the same squad? Ho-ho, that's funny. But if the Heap is useful, he will be happy.}
{218}{}{Come with me. We'll make a great team together.}
{219}{}{Great. I'll be back when I need your help.}
{220}{}{What do you want, mutant brother?}
{1220}{}{What do you want, sister?}
{221}{}{I don't need anything from you. Just don't touch me, big guy. Agreed?}
{222}{}{And you don't trust the Pile. Ghouls don't want to see a bunch. Nobody needs a bunch!}
{223}{}{What are you doing here? How did you end up among the ghouls?}
{224}{}{That's the attitude! You know, we could help each other.: you will protect me on the road, and I will help you earn respect. Deal?}
{225}{}{If the Heap is useful to the ghouls, he will be happy.}
{226}{}{I need you. Come with me.}
{227}{}{Private Heap will try!}
{228}{}{At ease, soldier.}
{229}{}{Private Heap, you can be free.}
{230}{}{Sorry. A bunch wanted to help. But don't forget the private Bunch.}
{231}{}{See you later.}
{232}{}{Take the weapon out of your hands. It's not necessary right now.}
{233}{}{It is necessary to remove the weapon from your hands!}
{234}{}{Good boy.}

{240}{}{Waiting for orders, Commander.}
{241}{}{At ease.}
{242}{}{Captain! Private Heap is ready to help, Captain!}

{250}{}{Will you come with me to the wasteland of Sonora? I could use your protection on the way.}
{251}{}{Go to the people? Nope. People won't accept a bunch.}
{252}{}{Okay, whatever you say.}
{253}{}{Your brethren are besieging the caravaneers now. Can you talk them out of it?}
{254}{}{No, they won't listen to a bunch. They kicked a bunch out of the squad. They don't have a lot of orders. But the Bunch won't allow killing fellow humans!}
{255}{}{Clearly.}

{260}{}{Tell me about yourself.}
{261}{}{Private Heap. And what?}
{262}{}{Okay. Let's not talk about it.}
{263}{}{Heap is a name or a nickname?}
{264}{}{Is it... e... I completely forgot! Heap is not a real name. This is the call sign for the walkie-talkie. I don't remember the name. Everything that happened before the Initiation is forgotten.}
{265}{}{Don't you remember who you were before the mutation?}
{266}{}{That's right. And a bunch doesn't want to remember. Pathetic people. They're messing around with their little problems. The Creator was trying to fix people. But he didn't have time to finish his job.}
{267}{}{You can tell me. Surely the memories torment you at least sometimes. You can't just cross out the old life.}
{268}{}{Do you think that's why the Heap is so stupid? Is that why he talks to himself at night? A bunch doesn't like to remember. He was a man, he ...................}
{269}{}{[Encourage]}
{270}{}{[Make fun]}
{271}{}{How did you get into the Shining?}
{272}{}{Together with the squad. We walked for a long time in the desert. We were being chased by a squad of the Brotherhood of Steel. Ooh, I hate Brotherhood! They killed many brothers in arms and drove us into the wasteland. There was no point in going back. We decided to leave.}
{273}{}{[Next]}
{274}{}{On the way we came across ghouls, they told us about the Dayglow. They also fled from the Normies. Normies hate everyone.}
{275}{}{Why aren't you with your squad?}
{276}{}{It was a hungry time. The pile was so hungry that it ate all the provisions. Shamefully. For this, he was expelled from the squad. And he didn't see the squad anymore.}
{277}{}{Do you know where your squad is now?}
{278}{}{Somewhere in the ruins. A bunch will know if they listen to their radio conversations.}
{279}{}{Now we know where your squad is. Do you want to meet your comrades?}
{280}{}{A lot of people miss them. But they don't need a bunch.}
{281}{}{Don't worry about it. I'll figure it out. Let's go.}
{282}{}{Did you hear that? Your captain is in trouble.}
{283}{}{The bunch is furious! The fucking humans have already caused so much trouble! They will pay!}
{284}{}{So you want to rescue the captain from captivity, even being expelled from the squad?}
{285}{}{A bunch is willing to take a chance. Come on, little man! Go ahead!}
{286}{}{Okay. Let's go.}
{287}{}{Okay. If you don't want to, then we won't contact them.}
{288}{}{I have a walkie-talkie, but because of the high radiation, it will not be useful without a functioning radio station.}
{289}{}{I have a walkie-talkie. Let's try it?}
{290}{}{Useless. High radiation interferes. We need a strong antenna. Maybe ghouls have it?}
{291}{}{So that's why the walkie-talkie doesn't work! Okay, maybe we'll find a repeater.}
{292}{}{(The bunch adjusts the frequency and listens carefully to the negotiations. From concentration, all his veins on his face swelled. Finally he says, "They're in Balboa Park.")}
{293}{}{Good. So we're going to the park.}
{294}{}{There was a radio station in San Ysidro. Let's try to find out there.}
{295}{}{There is a radio station here. Let's try it?}
{296}{}{Useless. It doesn't work.}
{297}{}{Really. Does not work.}
{298}{}{I can't hear anything! We need to go to the area above.}
{299}{}{Okay.}

{300}{}{It's here! The damned paladins are holding the captain here.}
{301}{}{What's your plan?}
{302}{}{Plan? The pile doesn't need a plan! A bunch is stronger than any paladin. He'll kick their asses. That's the whole plan.}
{303}{}{Good plan. Reliable as an atomic clock. Go ahead, Bunch! Kick the ass of these bastards!}
{304}{}{No, a bunch, you can't kill paladins. It's dangerous and it's not right. We must rescue the captain without violence. Do you understand me?}
{305}{}{Gr-r! Fucking humans! A bunch wants to fight! The pile is not going to hide in the shadows!}
{306}{}{If you think about it, then your idea is the simplest and most reliable. Go ahead, Bunch! Kick the ass of these scum!}
{307}{}{No way! We have little chance in an open battle. Let's do a reconnaissance first.}
{308}{}{If a Bunch sees a paladin, he won't hold back. Consider this, little man.}
{309}{}{Okay. I'll take that into account.}
{310}{}{You know, it would be better if I reconnoitered first, and you wait here. This is an order, a bunch.}
{311}{}{A lot of thanks to you for saving the captain. He couldn't have done it alone without you. Thank you.}
{312}{}{Does Mutyara say "thank you"? This is something new!}
{313}{}{It's too early to thank. We have yet to meet your squad.}
{314}{}{Yes. Heap must meet the squad again.}
{315}{}{Then let's go to the camp. Let's go.}
{316}{}{So what's up with the captain?}
{317}{}{Be strong, Bunch. The captain is no more. And your squad, too.}
{318}{}{DAMN THE BROTHERHOOD! I HATE IT! I HATE IT!}
{319}{}{I think it's better to leave you alone for now.}
{320}{}{Be strong, Bunch. The captain is no more.}
{321}{}{What are you going to do now without your squad?}
{322}{}{A bunch will work hard at the ghoul mines. Ghouls need his muscles. Ghouls will not regret taking him into service! Yes. So a bunch will be useful. He will be happy doing good. This is what the Bunch wanted.}
{323}{}{Clear. Well, I hope you'll stay with me some more before I return to Sonora.}
{324}{}{The squad is ready to receive you again.}
{325}{}{Brothers in arms forgave a bunch? It brings a lot of joy! But the Heap has already promised to help the ghouls. And will he be able to justify the trust, if once he could not? Tell me, man, what should I do now? Which choice is better for the Heap?}
{326}{}{I think you need to leave with the squad. Only among your own people can you be truly happy. And ghouls don't owe you anything.}
{327}{}{You should stay with the ghouls and help them rebuild the city. Your strength will help them a lot. And your squad has already rejected you once, may reject you again. Besides, it is not known what will happen to them on the way.}
{328}{}{The heap will do everything not to lose trust anymore! The squad will not regret taking him with them. Yes. So the Heap will be calm among its own. He will benefit and be happy. This is what the Bunch wanted.}
{329}{}{It's good that we sorted out your problem. I hope you'll stay with me some more before your squad leaves the Shining.}
