{100}{}{This is Mr. Nurse.}
{101}{}{You see the medical robot of the Mr. Nurse series.}
{102}{}{Viu! Viu! Make way for the orderlies!}

{200}{}{I am very sorry that I failed to save these people!}
{201}{}{Sir, it's not safe for you to be here.}
{202}{}{Sir, if you get radiation sickness, I won't be able to help you.}
{203}{}{Sir, I'm detecting an increased level of radiation. You'd better leave this place.}
{204}{}{I'm doing my best. But these people cannot be brought back to life.}
{205}{}{I'm sorry, sir, but I need to cure these people.}
{206}{}{There are so many crippled people here, as if a war had just happened.}
{207}{}{Do you know any of these patients?}
{208}{}{}
{209}{}{Oh, I think I've got the wrong door.}

{1200}{}{I am very sorry that I was not able to save these people!}
{1201}{}{Ma'am, it's not safe for you to be here.}
{1202}{}{Ma'am, if you get radiation sickness, I won't be able to help you.}
{1203}{}{Ma'am, I'm detecting an increased level of radiation. You'd better leave this place.}
{1204}{}{I'm doing my best. But these people cannot be brought back to life.}
{1205}{}{I'm sorry, ma'am, but I need to heal these people.}
{1206}{}{There are so many crippled people here, as if a war had just happened.}
{1207}{}{Do you know any of these patients?}
{1208}{}{}
{1209}{}{Oh, I think I got the wrong door.}

{210}{}{I have a fracture. Help me, Doc!}
{211}{}{Oh, that's too bad. You need urgent hospitalization. Please lie down, I will try to help you.}
{212}{}{[Follow the nurse's instructions]}
{213}{}{You're fine. Be careful from now on.}
{214}{}{Thank you.}
{215}{}{Do you know how to heal?}
{216}{}{Of course. I am a medical assistant robot. But at the moment my options are limited due to the lack of medicines. Can I help you somehow?}
{217}{}{No, not today.}
{218}{}{No way! I won't trust my life to some soulless piece of hardware.}
{219}{}{Private Heap has a serious injury. Can you cure her?}
{220}{}{Private Heap is fine.}
{221}{}{Thank you.}