{100}{}{In front of you is the ghoul Zerah.}
{101}{}{You see an ordinary ghoul. He's a little dented after meeting with the black scavengers.}
{102}{}{Z-z-z...}
{103}{}{Leave me alone!}
{104}{}{As Zerah said, there was pre-war money in the mailbox, }
{105}{}{ pieces.}
{106}{}{Your diagnosis: this body is dead.}
{107}{}{Good idea.}

{200}{}{And who else are you?}
{201}{}{Oh, brother, help me. These bandits won't let me live.}
{1201}{}{Oh, sister, help me. These bandits won't let me live.}
{202}{}{I'm going to untie you now... Now let's get out of here. Just be quiet!}
{203}{}{I see you're in trouble. I can help if you tell me where the caps are.}
{204}{}{I'll tell you! Just get me out of here.}
{205}{}{I don't care about you. Lie down and keep quiet.}
{206}{}{Hey guys! There's some normie wandering around!}
{207}{}{Oh, you bitch...}
{208}{}{Shut up!}

{210}{}{Thank you, brother. You're proving once again that you can't trust normies.}
{1210}{}{Thank you, sister. You're proving once again that you can't trust normies.}
{211}{}{Thank you for saving my ass. I didn't think any of the normies would worry about her.}
{212}{}{What did these bandits want from you?}
{213}{}{They are ordinary black scavengers. But they don't want to risk themselves on the ruins, so they steal from those who do it. That's just I don't know any caches with valuable items.}
{214}{}{The main thing is that you remained intact. From now on, be careful on the ruins.}
{215}{}{You're lying. Tell me where the nearest cache is!}
{216}{}{Okay, okay, chill out! I threw all my bills into the mailbox at the entrance to the hospital when the scavengers were chasing me. But that's all I had.}
{217}{}{I'll check it out. Pray that they are there.}
{218}{}{You can be free.}
{219}{}{Hush! They can hear us! Let's get outside first.}
{220}{}{Okay.}
{221}{}{Don't worry. All the bandits are already dead.}