{100}{}{In front of you is a ghoul.}
{101}{}{You see an ordinary ghoul.}
{102}{}{Z-z-z...}

{110}{}{Oh...}
{111}{}{Ah...}
{112}{}{It hurts...}
{113}{}{It still hurts...}

{200}{}{Hey, man, help me! I just got caught in a landslide a little bit and broke a couple of bones. These old houses are no good at all...}
{201}{}{Hey, buddy, help me! I just got caught in a landslide a little bit and broke a couple of bones. These old houses are no good at all...}
{202}{}{Oh my God! Don't move, I'll help you now!}
{203}{}{Daydreaming. I don't even want to dirty my hands about such a freak.}
{204}{}{I'm not going to help you. I'll just take your stuff and leave you to die. And by the way — no one will hear you here anymore.}
{205}{}{Oh no! No! No...}
{206}{}{See you in the next world. Maybe.}
{207}{}{I'm kidding, man! Wait a bit, I'll cure you soon.}
{208}{}{I really didn't expect that a person would help me, and even in the heart of radioactive ruins. Thank you, friend.}
{209}{}{You're welcome. By the way, what were you doing here?}
{210}{}{Don't forget to tell the other ghouls about my feat. How did you end up here anyway?}
{211}{}{Explored the ruins, obviously. But the floors here turned out to be quite flimsy. Tread carefully, friend. Oh, and that's not the main danger. I saw a creature from the window. Huge, scary, with claws like sabers. Don't fall into his clutches. And now — good luck. I'll try to hobble to the nearest camp.}
{212}{}{Thanks for the warning. Bye.}
{213}{}{I don't remember your face. We didn't cross paths in the Necropolis, did we? It's a strange thing. But in any case, thank you, friend. I couldn't even kick down the front door without you.}
{1213}{}{I don't remember your face. We didn't cross paths in the Necropolis, did we? It's a strange thing. But in any case — thank you, girlfriend. I couldn't even kick down the front door without you.}