{100}{}{Here is a black scavenger.}
{101}{}{You see one of the local scavengers. Although he looks more like a bandit.}
{102}{}{Another disgusting ghoul. How did you get me!}
{103}{}{Who do we have here? A favorite of ghouls or a free scavenger? In any case, you will not leave here...}
{104}{}{Get out of here while I'm being nice.}

{110}{}{We don't need competitors!}
{111}{}{Get out of our ruins!}
{112}{}{Everything in the Glow will be mine!}
{113}{}{Don't even think about taking something out of these ruins without my permission!}

{120}{}{I hate mutants!}
{121}{}{I hate ghouls!}
{122}{}{All these super mutants and ghouls are a mistake of nature.}
{123}{}{Super mutants have ruined many people's lives. They cannot be pitied.}
{124}{}{Who's the mutants' favorite here? I'll shoot you on the spot!}
{125}{}{These ghouls prevent us from extracting valuables from the ruins.}
{126}{}{To hell with ghouls!}
{127}{}{No pity for mutants!}
{128}{}{}
{129}{}{}

{130}{}{Hey, you ghoul meat! Which death do you prefer?}
{131}{}{You ghouls don't let us collect resources on the ruins yourself.}
{132}{}{You're all the same to me. That ghouls, that super mutants are one shit.}
{133}{}{Look at your ugly face, dead guy.}
{134}{}{Don't argue with me, freak.}
{135}{}{Tell me, you disgusting mug, where do you keep all the most valuable things?}
{136}{}{I ask for the last time: where are the covers?}
{137}{}{}
{138}{}{}
{139}{}{}

{140}{}{Idiots! How could you miss some stinking dead guy?}
{141}{}{Where is this dead guy? Where is he, I ask?!}
{142}{}{A bunch of morons, you couldn't even keep track of the ghoul!}
{143}{}{And this ghoul turned out to be more cunning than I thought...}
{144}{}{It looks like the ghoul was not alone...}
{145}{}{If this ghoul calls his friends from San Isidro...}
{146}{}{Damn it, this ghoul will tell everyone that we're here.}
{147}{}{We need to get out of here before that ghoul tells everyone else.}
{148}{}{The little green brat ran right out from under his nose...}
{149}{}{We need to get out of here. I give everyone an hour to pack!}