{100}{}{In front of you is the ghoul Falik.}
{101}{}{You see an ordinary ghoul.}
{102}{}{You overheard the confession of a ghoul.}
{103}{}{Don't interfere with my prayer!}
{104}{}{I'm sorry I treated you so badly at first.}

{105}{}{Hey, don't eavesdrop!}
{106}{}{Actually, I'm in confession. Do your business quickly.}
{107}{}{You're interfering with my confession, little man!}
{108}{}{Are you eavesdropping?}

{110}{}{Padre, can you keep a deathly silence?}
{111}{}{Can I tell you my story?}
{112}{}{Listen to me, Padre.}
{113}{}{My friend Zerah, though he was a ghoul, has now become a ghoul literally.}
{114}{}{Well, not that it's my fault...}
{115}{}{But I left him.}
{116}{}{It was in the hospital, it was burning with hellfire.}
{117}{}{Zerakh and I were looking for scrap when we suddenly came across scavengers.}
{118}{}{I still have goosebumps! But I don't have any skin.}
{119}{}{The scavengers captured and killed Zerakh. And I hid and ran away.}
{120}{}{Tell me, Padre, will God forgive me?}

{200}{}{(Falik prays hard.)}
{201}{}{I accidentally overheard your confession.}
{1201}{}{I overheard your confession by accident.}
{202}{}{[Leave it.]}
{203}{}{Oh, you hide! Just dare to tell someone!}
{204}{}{I don't blame you. I understand you. You did the sensible thing.}
{205}{}{Oh, friend, please don't tell anyone!}
{206}{}{Really? Well, thank you. But you can't bring Zerakh back anyway.}
{207}{}{Are you even sure he's dead?}
{208}{}{A schmuck like you doesn't deserve my attention. Pathetic coward and weakling, how could you leave a friend in trouble!}
{209}{}{It's easy for you to say! You weren't there! You don't even know Zerah. What do you care?}
{210}{}{Is he really dead?}
{211}{}{There could be no other way! His body is probably still in the hospital. But I don't dare go there to pick him up and bury him with honors.}
{212}{}{I can do it. Not for nothing, of course.}
{213}{}{Okay, I'll look for his body. Your story struck a chord with me.}
{214}{}{I don't need any help from you! Better leave me alone and don't touch me anymore.}
{215}{}{Don't worry so much. Adios.}
{216}{}{I would appreciate it.}
{217}{}{Don't worry about it. Adios.}

{220}{}{(Falik is still praying hard.)}
{221}{}{[Leave him.]}
{222}{}{Zerah really died. His body is lying in the hospital.}
{223}{}{(pause) Ah-H. I knew. You shouldn't have given me hope. But at least now I know it for sure.}
{224}{}{Life is still a bitch. Be.}
{225}{}{I am very sorry.}
{226}{}{Zerah was alive. The scavengers seized him and tortured him. But I managed to get him out of trouble.}
{227}{}{IS HE ALIVE?! Good God, my prayers have been answered! Heaven must have sent you to me.}
{228}{}{But no. God has nothing to do with it.}
{229}{}{Let it be so, if you want.}
{230}{}{Can I ask you one more favor? Can you help me make peace with him? Find him and tell him I want to apologize to him!}
{231}{}{}