{102}{}{Today we are kind. But don't get in our way again.}
{103}{}{Death to the normies!}
{104}{}{Save me from these stupid mutants!}
{105}{}{The last time I was pressed like that was before the war. Mafia then, mutants now — not much has changed.}
{106}{}{Ugh, I thought I was screwed. Here, take a stimulant and words of gratitude as a reward. Thank you, friend.}
{107}{}{}
{108}{}{}
{109}{}{}

{200}{}{Who do we have here? Come here, man! You will be my sweet...}
{201}{}{Catch it first, asshole.}
{202}{}{Please don't touch me!}
{203}{}{My brothers also said when the normies killed them. DIE, BITCH!}
{204}{}{Stop, scum!}
{205}{}{Don't...}
{206}{}{Listen, I'm trying to help the ghouls. Have pity on us, we are not your enemies!}
{207}{}{You? Help? Walking? Ha-ha-ha, made me laugh! I didn't know there were such fools.}
{1207}{}{You? Help? Walking? Ha-ha-ha, made me laugh! I didn't know there were such fools.}
{208}{}{Please let me and this ghoul go. No one threatens you here.}
{209}{}{Why am I crucifying myself in front of you here? Die, you freaks!}
{210}{}{Oh, it's a pity to even dirty your hands like you. Don't get in our way again.}
{211}{}{Ugh, it's gone...}
{212}{}{And here's another body. We're lucky to be out partying today. Good catch.}
{213}{}{You look big and formidable, but you don't have any brains.}
{214}{}{Please don't touch us! We are of the same blood!}
{215}{}{We are not enemies of each other. We're both mutants. Let's be friends?}
{216}{}{What did you say? Shut your mouth, scavenger! We are not dirty mutants, we are pure-blooded soldiers of the Creator!}
{217}{}{I think I just made him angry...}
{1217}{}{I think I just made him angry...}
{218}{}{Hmm, that's true. People hate us all for it. But this is all that unites us. We're not scavengers like you. We are pure-blooded soldiers of the Creator! Remember that, half-breed.}
{219}{}{Yes, sir. I'll remember that.}
{220}{}{Heap? I didn't think you were with them for one thing.}
{221}{}{Yes, we decided to unite together. Is it bad?}
{222}{}{For normies and shadows to unite — I haven't heard that. But if the Pile is with you, then we will not interfere.}
{223}{}{That's good.}