{100}{}{You see a looter ghoul.}
{101}{}{There's a ghoul in front of you. He carefully examines the area.}
{102}{}{Hey, buddy, do you have a light? There's a lot of junk around, but here's the fire...}
{1102}{}{Hey, miss, is there a light? There's a lot of junk around, but here's the fire...}
{103}{}{Fire! Wow-oh-oh!}
{104}{}{Perhaps one lighter will be enough for you.}

{200}{}{Flames have descended from heaven! Do you see that? Everything is burning around. That's it! Even the stones are burning!}
{201}{}{You're delusional. Wake up!}
{202}{}{Am I going crazy? Nope. The flame of the Great War is still burning. It burns in my heart. And every time I think of him, when I see the slightest spark. It cannot be forgotten. So I want to do it again... remember... Look, it's burning! It burns well!}
{203}{}{So, it's clear that you have a thing about this topic. Don't you want to share fuel with others?}
{204}{}{Fire is really fascinating.}
{205}{}{Do you like FIRE too? Yes, the flame of the Great War has not yet died out. It burns in my heart. And every time I think of him, when I see the slightest spark. It cannot be forgotten. So I want to do it again... remember... Look how it burns! It burns well!}
{206}{}{And now — create your own flame!}
{207}{}{Eh, of course, it must.}
{208}{}{Actually, I just want to make some fire. Do you have any fuel?}
{209}{}{I think I'll move away while you're messing with the fire. Bye.}
{210}{}{Do you like to look at flames?}
{211}{}{You definitely need a flame. Everyone needs it.}
{212}{}{Fire cleanses. He takes everything you owned. He creates a void. Isn't it amazing?}
{213}{}{Whether you want it or not, I'll take all the fuel you have.}