{100}{}{You see a ghoul.}
{101}{}{Here is one of the ghouls. He looks particularly battered.}

{102}{}{Hi. Where did you come from so handsome?}
{1102}{}{Hi. Where did you come from so beautiful?}
{103}{}{Hi, friend. Be careful on the ruins.}
{1103}{}{Hello, friend. Be careful on the ruins.}
{104}{}{Save me from these stupid mutants!}
{105}{}{The last time I was pressed like that was before the war. Bandits then, mutants now — not much has changed.}
{106}{}{Ugh, I thought I was screwed. Here, take a stimulant and words of gratitude as a reward. Thank you, friend.}
{1106}{}{Ugh, I thought I was screwed. Here, take a stimulant and words of gratitude as a reward. Thanks, girlfriend.}

{110}{}{Don't touch me, we're the same blood!}
{111}{}{I won't tell anyone I saw you. Honestly.}
{112}{}{Not by the face! I have only one tooth left...}
{113}{}{Leave me alone!}
{114}{}{I don't have anything edible!}
{115}{}{Somebody help!}
{116}{}{What do you want from me?}
{117}{}{I'm telling you, I don't have any food.}
{118}{}{Maybe you should hunt in the wastelands, huh?}
{119}{}{Guys, let's be friends, huh?}