{100}{}{You see a guardian ghoul.}
{101}{}{You see a ghoul dressed in combat armor.}
{102}{}{We do not tolerate competitors. Get out of here!}
{103}{}{If you were actually a patrol officer, you wouldn't have the power here.}
{104}{}{Were you allowed to be here?}
{105}{}{Big changes are waiting for us.}

{200}{}{Let's decide right away, eccentrics and smoothies are not welcome here. But if you behave yourself, they won't touch you. Is that clear? Good. Come on, tell me what you need.}
{201}{}{Welcome, brother. Were you well received in San Ysidro? Do you need anything?}
{1201}{}{Welcome, Sister. Were you well received in San Ysidro? Do you need anything?}
{202}{}{I just want to ask a few questions about the Dayglow.}
{203}{}{What do you need?}
{204}{}{Nothing. Bye.}
{205}{}{Ask.}
{206}{}{It's time for me to go. Thank you for your time.}
{207}{}{I see. I'll ask you something else, okay?}
{208}{}{}
{209}{}{}
{210}{}{Tell me about yourself?}
{211}{}{Retired Sergeant Robert Newsom. Before the war, I kept order on the streets of Bakersfield, and now I keep order in the Glare of the Day. I love my job. And I will not allow anyone to bully in my domain.}
{212}{}{What do you think of Gustavo?}
{213}{}{He's a great fit for the role of mayor. And the ghouls respect him. At least not here in San Ysidro. Although not everyone in the Old City is as reasonable.}
{214}{}{And who runs the Old City?}
{215}{}{John Butler. Ex-military. Therefore, his head is full of bedlam. He gathered around him not only ghouls but also super mutants and normies. Everyone needs something from him.}
{216}{}{And in what relationship are Gustavo and Butler?}
{217}{}{They've had a lot of disagreements lately. But I'm sure it won't break their friendship.}
{218}{}{}
{219}{}{}
{220}{}{Tell us about the area around.}
{221}{}{San Isidro and the Old Town are the main Gulian settlements. Radioactive ruins and burnt-out parks are spread out between them. Black scavengers and monsters are often found in them.}
{222}{}{[Next]}
{223}{}{Most of the nuclear strikes hit a military base and an industrial zone. Downtown San Diego has been hit hard, too. Devastation, high radiation, skeletons — that's what you'll find in the ruins. And there are military robots everywhere. They scattered after the sirens turned on at the military base.}
{224}{}{Tell me how to get to Chula Vista?}
{225}{}{You need to cross the valley of the Auteuil River. There is only one surviving bridge, but it is captured by robots and mined. So we go to the county or straight through the valley. But there are many terrible creatures in the valley.}
{226}{}{Tell me how to get to the Bonita Dam?}
{227}{}{Follow Federal Highway 805 to the signpost. And then turn right.}
{228}{}{Tell me how to get to the Old Town?}
{229}{}{It will be very difficult to get there straight through the ruins. The easiest way is to get on Route 805 and go to Balboa Park. Beware of monsters in the park. Go left to the Little Italy area. And then — to the north.}
{230}{}{What is your relationship with black scavengers?}
{231}{}{They are mostly bandits. They collect fragments of the Old World, often without even understanding what they are needed for. And then they sell it to caravans. Thereby leaving the ghouls mere crumbs. Gustavo is trying to drive them away from our ruins, and Butler wants to tame them by giving Seth's Seal to the most obedient.}
{232}{}{What is your relationship with super mutants?}
{233}{}{Super mutants? The army of the Creator was divided into many fragments and scattered through the ruins. There are many such groups in the vicinity. Some of them are aggressive, some cooperate with us, the rest are on their own. Lost lost souls.}

{241}{}{A bunch of us are looking for his squad. Maybe you've heard of him?}
{242}{}{I heard that super mutants have set up a camp in Balboa Park. They are not aggressive, but rather the opposite. Maybe this is the squad you're looking for.}
{243}{}{Clear. Thank you.}