{100}{}{You see old Judy.}
{101}{}{You see a female ghoul in a pre-war dress.}
{102}{}{Ah-h!}
{103}{}{Now I know what Rupert has been doing all this time. But... I'll forgive him this time.}

{200}{}{Hello, stranger. There are more and more new faces in the Shining}
{1200}{}{Hello, stranger. There are more and more new faces in the Shining}
{201}{}{That's for sure. Bye.}
{202}{}{Who are you?}
{203}{}{My name is Grandma Judy. I came from the Necropolis, like the rest of the ghouls.}
{204}{}{Clearly. Bye, Grandma.}
{205}{}{What are you doing here, Judy?}
{206}{}{Every day I come to Gustavo to find out about the new arrivals or the dead. After all, this is a real city hall. If there's a place to look for people, it's here.}
{207}{}{What do you think about Gustavo?}
{208}{}{Oh, such a cute young ghoulie! He cares about his wards more than about himself. We have always lacked such.}
{209}{}{Who are you looking for?}
{210}{}{My husband Rupert and I missed each other while traveling. Now I can't find it. Although Cabot in the Old Town says he saw him.}
{211}{}{Sorry to hear that. Bye.}
{212}{}{I'll help you find him.}
{213}{}{What a cute little thing you are! I will accept any help.}
{1213}{}{What a clever girl you are! I will accept any help.}
{214}{}{Then I'll start with the Old Town, perhaps. Bye, Judy.}
{215}{}{Tell me again, when was the last time you saw your husband?}
{216}{}{My name is Judy. You can call me Grandma, honey. I came from the Necropolis, like the rest of the ghouls.}
{217}{}{Be strong, Grandma. Your husband Rupert died in a kneading in the Italian district.}
{218}{}{Ah! I felt it! (grabs his heart) Oh!}
{219}{}{Hey, are you feeling bad?}

{220}{}{Hello stranger.}
{1220}{}{Hello, stranger.}
{221}{}{Bye, Grandma.}