{100}{}{You see Rupert.}
{101}{}{You see a ghoul in a pre-war suit.}
{102}{}{You see a ghoul.}
{103}{}{If it wasn't for De-Santi, we would have been reunited a long time ago.}
{104}{}{Hey, hello. You look pretty good for a dead guy.}
{105}{}{Phew! I can't get used to your nasty smooth faces.}
{106}{}{Oh-h!}
{107}{}{You know how to break off pleasure.}

{200}{}{Hey, hello. You look good for a dead guy.}
{201}{}{I'm not dead.}
{202}{}{Well, then you're lucky. I'm lucky too. More points every time!}
{203}{}{Well, that's...}
{204}{}{Oh, if only I had always been so fortified! I thought that my old age would be quite sad, but in this hotel, I feel young like never before! And it's so much fun!}
{205}{}{I actually...}
{206}{}{Glad that...}
{207}{}{And now I'm sorry, Daddy needs a pair of brand-new shoes. Eh, there was no such thing! I bet on red!}
{208}{}{I won't interfere.}
{209}{}{Look, old man, don't lose your soul.}

{220}{}{Don't mumble under your arm, my card is ready!}
{221}{}{Nevermind.}
{222}{}{Tell me, old man, what's your name?}
{223}{}{My name is—The-Luckiest-Son-of-a-Bitch-in-the-World!}
{224}{}{I'm serious.}
{225}{}{Listen, don't be such a bore. I'm not going to be friends with you anyway. Call me old man if you want. I don't care.}
{226}{}{Okay. Whatever you say, old man.}
{227}{}{Your name is Rupert, isn't it?}
{228}{}{Cough-cough-cough! I don't know who you're talking about. This is the first time I've heard this name.}
{229}{}{Maybe I should ask the administrator? Or peek in the visitors' log?}
{230}{}{Really? Well, then I'm sorry to bother you.}
{231}{}{What do you want in the end? Who sent you?}
{232}{}{Miss Judy. She's looking for her missing husband. And it looks like he's burning his entire fortune in secret from her.}
{233}{}{(sigh) Listen, buddy. Do you think I would hang out here if I wanted to reunite with Judy?}
{234}{}{I don't care.}
{235}{}{Then what is the reason for this behavior?}
{236}{}{You're a man, you have to understand what it's like when your wife nags you for 80 years in a row!}
{1236}{}{You're a woman, you don't understand what it's like when your wife nags you for 80 years in a row!}
{237}{}{[Listen]}
{238}{}{I feel good here. I do what I want — I drink, watch movies, play roulette! You know, Judy never let me play that damn roulette. And that's what I've always wanted.}
{239}{}{You know it's not a real game, right?}
{240}{}{Well, yes. But it doesn't matter — it's important that I finally started playing it!}
{241}{}{She won't be happy if she finds out that you were hiding from her while she was looking for you.}
{242}{}{I know. Listen, tell her I'm dead, huh? It's not difficult for you, but I can live for some time without her total supervision.}
{243}{}{Okay. Why not?}
{244}{}{Will you really do that? Oh, I'm so lucky today! So lucky!}
{245}{}{Okay, come on.}
{246}{}{No. You have to meet her. She is the person closest to you. It is wrong to hide from her at the end of life.}
{247}{}{Well, why are you breaking my buzz? (sigh) La adno. Your truth. She'll find out the truth from you anyway.}
{248}{}{Yes. Go and talk to her. She lives in San Ysidro.}

{250}{}{As you asked, I told her you were dead. And do you know what happened? Her heart couldn't stand it and burst!}
{1250}{}{As you asked, I told her you were dead. And do you know what happened? Her heart couldn't stand it and burst!}
{251}{}{How... it can't be... I didn't expect this... oh... ugh...}
{252}{}{Just don't tell me that you're going to throw away your skates now.}