{200}{}{Senor }
{1200}{}{Senora }
{201}{}{! Don't be afraid, this robot serves as a messenger. He brought you an important message.}
{202}{}{What's the message?}
{203}{}{"Dear amigo, I know about your deeds in the Sonoran desert. Whatever you are guided by and whatever you are going for, your experience is priceless."}
{204}{}{[Listen on]}
{205}{}{"Now history is being made on the ruins of San Diego. You should be there. Local ghouls don't trust people. They are split and weak. And so they can make a big mistake. They need a hero."}
{206}{}{[Listen on]}
{207}{}{"The gathering of the caravan going to the Gulsky city is held on the outskirts of Inferno. You will be given a special permit to freely explore the city ruins around the Old City."}
{208}{}{[Listen on]}
{209}{}{"When you find yourself in the Old Town, look into a junk shop and take an encrypted holodisk with instructions from him. I count on your help and wish you good luck."}
{210}{}{[Listen to the recording again]}
{211}{}{[End Recording]}
{212}{}{Gee???}