{100}{}{Here is a mercenary.}
{101}{}{Here is one of those black scavengers who agree to any job for the sake of earning money.}

{110}{}{Mr. De Santi will pay well for your head.}
{111}{}{You shouldn't have offended Mr. De-Santi!}
{112}{}{Who goes against De-Santi, does not live long.}
{113}{}{Mr. De-Santis is terribly unhappy with you!}
{114}{}{Nothing personal. It's just that someone ordered you.}