{100}{}{You see a looter ghoul.}
{101}{}{There's a ghoul in front of you. He is carefully studying some objects.}

{200}{}{Hey, wait, don't come any closer! These are my things, I found them!}
{201}{}{If they were yours, they will become mine.}
{202}{}{Okay, whatever you say. These are your things.}
{203}{}{Hmm, it's rare to meet normal people here... Well, that is now rarely. And once whole crowds walked these streets. Here, bones are still sticking out of the sand all around.}
{204}{}{And what are you doing here?}
{205}{}{I'm looking for valuables in these ruins. Previously, scavengers rarely looked here because of the robot border guard. But someone did us a big favor by disabling it.}
{206}{}{Then good luck. Bye.}
{207}{}{Have you found anything valuable yet?}
{208}{}{Yes, here, look...}
{209}{}{[Trade]}
{210}{}{Hello, little man. Do you need any things from the ruins? I can search. I give it almost for nothing. And I'll also make a discount for you.}
{211}{}{Not today, senora.}
{212}{}{Show me what you have...}
{213}{}{Come back. Maybe I'll find something else useful in a couple of days.}
{214}{}{Goodbye.}
{215}{}{Hey, do me a favor, don't touch my stuff. Ok? I found them!}
{216}{}{Hmm, so now I'm not the only one in these ruins... But once whole crowds walked these streets. Here, bones are still sticking out of the sand all around.}