{100}{}{You see a super mutant shadow.}
{101}{}{You see a super mutant in combat gear.}
{102}{}{We, the shadows, will remain faithful to the Creator and his ideas. Even if the normies leave us alone.}

{200}{}{Hey, man, hold your gun. We won't touch you until you attack.}
{201}{}{Hey, friend, don't worry. We won't hurt you if you don't attack.}
{202}{}{Where does such benevolence come from?}
{203}{}{Why would I believe you?}
{204}{}{We're just tired of the war. Let people stop chasing! That's all we're asking.}
{205}{}{Clear. Well, bye then.}
{206}{}{Don't stare, little man. I don't like people staring.}
{207}{}{Whatever you say.}
{208}{}{}
{209}{}{}

{210}{}{Tell me, is it true that you drove a bunch out of your squad?}
{211}{}{A bunch? We don't even want to hear about him. The traitor! He lost his loyalty to the squad. There is no excuse for him.}
{212}{}{He can redeem himself.}
{213}{}{I do not believe. A bunch of dumb. He's not even fit to carry a machine gun. It's a pity the captain is not with us to tell him off again...}
{214}{}{And what happened to the captain?}
{215}{}{Captured in disgrace by the soldiers of the Brotherhood of Steel. Now he is being tortured at the patrol center near San Ysidro.}
{216}{}{So why are you standing here and not saving him?}
{217}{}{It's a trap, you stupid man! The Brotherhood soldiers want to catch us all. The captain himself said when he left: there is no need to save him.}
{218}{}{Well, you are stupid! If I were you, I'd do anything to get the captain out. Let's go, a bunch, from these losers.}
{1218}{}{Well, you are stupid! If I were you, I would do anything to get the captain out. Let's go, a bunch, from these losers.}
{219}{}{I understand. An order is an order. Come on, Bunch, we need to talk face-to-face.}
{220}{}{Well, you are stupid! If I were you, I'd do anything to get the captain out. Bye, losers.}
{1220}{}{Well, you are stupid! If I were you, I would do anything to get the captain out. Bye, losers.}
{221}{}{I understand. An order is an order.}
{222}{}{Your captain is dead. I failed to save him from the hands of the Brotherhood of Steel.}
{223}{}{This was to be expected.}
{224}{}{What are you going to do without the captain?}
{225}{}{And that's it? There will be no angry speeches and guttural roaring? Do you even know how to survive without a captain?}
{226}{}{Your captain is saved. Don't mention it.}
{227}{}{Even though you weren't asked, you're still helping the shadows. Do you really think this is how you can reconcile humans and mutants? It's impossible. But we are grateful to you anyway. I would like to show you to the Creator.}
{228}{}{What are you going to do now?}
{229}{}{Do you have any further plans? Or will you be stuck in the middle of a burnt park?}
{230}{}{We want to go east. To a place where they don't know about us yet. Away from the Brotherhood and other haters of California.}
{231}{}{What prevents you from doing this now that the captain is with you?}
{232}{}{What prevents you from doing this now that the captain no longer holds you?}
{233}{}{Then good luck on the way.}
{234}{}{Right. There is nothing to spoil the mood of normal people. I hope you won't bother anyone away.}
{235}{}{What about the Pile? Will you take him with you?}
{236}{}{If he wants to, let him return to the squad.}
{237}{}{Good. He's already got everyone here.}