{100}{}{You see the paladin.}
{101}{}{You see a paladin of the Brotherhood of Steel.}
{102}{}{Greetings, brother.}
{1102}{}{Greetings, Sister.}

{110}{}{What the hell is going on?}
{111}{}{Damn alarm!}
{112}{}{What the hell is that noise?}
{113}{}{Hmm, strange.}
{114}{}{Eh? False positive?}
{115}{}{Fucking alarm system!}

{120}{}{Cursed technology!}
{121}{}{Stop ringing already!}
{122}{}{How can I turn it off?}
{123}{}{It's a pity there are no knights nearby...}
{124}{}{How does it work?}
{125}{}{It's easier to blow up than to disable, by God!}

{130}{}{Strange. Why did it work?}
{131}{}{This siren won't ring again.}
{132}{}{Surprisingly, the alarm is still working.}
{133}{}{I think I've definitely disabled it now.}

{200}{}{Stop! This place is guarded. You'll have to leave. Immediately.}
{201}{}{OK-OK, I'll leave immediately.}
{202}{}{To begin with, try to move me, stupid!}
{203}{}{I'm also from the Brotherhood of Steel. Clerk }
{204}{}{I'm also from the Brotherhood of Steel. Knight }
{205}{}{I'm also from the Brotherhood of Steel. Paladin }
{206}{}{I'm also from the Brotherhood of Steel. Scout }
{207}{}{. Sonora Branch.}
{208}{}{Glad to meet you, brother. You can stay here, under our protection.}
{1208}{}{Glad to meet you, Sister. You can stay here, under our protection.}
{209}{}{May I know what you are doing here?}
{210}{}{We have a small mission. We have captured the captain of the super Mutants and are interrogating him now. And when we're done, we'll kill you. Nothing to worry about, he's well-guarded.}
{211}{}{Oh, that's great. Congratulations.}
{212}{}{Wait! I'll explain again — you can't come here. Go away. Immediately.}
{213}{}{Don't make us angry. This will be the last warning. to you. here. YOU CAN'T.}
{214}{}{That's enough! Morons like you can't be saved. You're going to get a big thrashing!}
{215}{}{Oh, it's going to hurt...}
{216}{}{Dreaming, imagining!}
{217}{}{I know who you're keeping locked up. And I can tell where his squad is.}
{218}{}{Then tell me! Any information will be valuable to us.}
{219}{}{The squad set up camp in Balboa Park.}
{220}{}{We have a short conversation with super mutants. They are an evil that must be eradicated. Thanks for the information. We appreciate your help.}
{221}{}{Please.}
{222}{}{And what will you do with these super mutants?}
{223}{}{We have a short conversation with super mutants. They are an evil that must be eradicated. So where are they?}
{224}{}{Eradicate? Yes, you crazy fanatics! I won't let you kill super mutants!}
{225}{}{Soon we will send a detachment there to eliminate the green threat. Thanks for the information. We appreciate your help.}