{100}{}{You see the shadow commander.}
{101}{}{You see a super mutant shadow.}
{102}{}{I won't thank you. But you deserve respect. See you again, strange creature.}
{103}{}{Heap is so glad! So glad!}

{200}{}{Leave me, man! Stop... Are you not from the Brotherhood?}
{201}{}{Listen, there's no time to explain, but I want to set you free. Just follow me and don't show yourself to the paladins.}
{202}{}{Sit still, big guy, until I call.}
{203}{}{So there's a bunch with you? Strange things. I've seen everyone, but this is the first time I've seen this.}
{204}{}{I don't understand what you're up to, little man. But don't try to deceive me.}
{205}{}{We'll talk when we get to a safe place. Let's go.}
{206}{}{You're free now.}
{207}{}{Explain, little man, what the hell does this all mean? Why would you help the shadow? Who sent you?}
{208}{}{It's a Bunch. He wanted to help his squad to redeem himself.}
{209}{}{Heap? Ho-ho, even the most stupid fighter can sometimes save a life. Surprised you, little man. Now I understand. Heap saw you as a strong commander. I don't mind. Let the Heap choose for himself with whom he will stay — with you or with the shadows. And while he's thinking, I'm going to camp. See you, strange creature.}
{210}{}{Yes, see you later.}