{100}{}{You see Jerry's knight.}
{101}{}{You see a knight of the Brotherhood of Steel. He looks pretty battered.}

{200}{}{Hush! A mutant lurked at the entrance. He'll kill us if he sees us. I'm also wounded and can't fight. You are my last hope.}
{201}{}{Is the mutant gone? Thank you, brother! And now I need to heal my wounds. Do you have a first aid kit?}
{1201}{}{Is the mutant gone? Thank you, Sister! And now I need to heal my wounds. Do you have a first aid kit?}
{202}{}{Is the mutant dead? Thank you, brother! And now I need to heal my wounds. Do you have a first aid kit?}
{1202}{}{Is the mutant dead? Thank you, Sister! And now I need to heal my wounds. Do you have a first aid kit?}
{203}{}{I'm doing what I can. Stop whining to me here!}
{204}{}{I will do my best.}
{205}{}{Thank you for the treatment. Now I can fight at full strength. Although I don't have enough bullets. Where is this mutant? Probably waiting at the entrance.}
{206}{}{Let's go, let's give him a hard time!}
{207}{}{You'd better keep your head down so that old wounds don't open up. Stay here until I deal with that bully.}
{208}{}{The danger has passed. That bully has already left.}
{209}{}{That bully won't hurt anyone else. We can come out of hiding.}
{210}{}{But no! Here he is! Careful!}
{211}{}{Don't shoot! It's a bunch, my partner.}
{212}{}{Which... Of course, I am grateful to you for saving me, but this is too much! Mutants are evil! They destroyed entire human settlements. What the hell is this piece of shit doing with you?}
{213}{}{He's harmless. Do not hate all mutants because of the misconduct of one particular group.}
{214}{}{I don't know why I need it either. But he protects me and carries things. Just don't touch him, OK?}
{215}{}{Who are you? You know, I once knew a resident of the vault. He was trying to help his brothers and sisters. And when he helped, he was simply thrown out. Good without weapons ends up with something sad.}
{1215}{}{Who are you? You know, I once knew a resident of the vault. He was trying to help his brothers and sisters. And when he helped, he was simply thrown out. Good without weapons ends up with something sad.}
{216}{}{Maybe so.}
{217}{}{Who knows?}
{218}{}{Oh, then, six years ago, we would have had people like you on the front line — how many brothers could have been saved from super mutants!}
{219}{}{At that time I worked on plantations and didn't know about any war with super mutants. That's why I love my rural life.}
{220}{}{It's enough that I managed to save you.}
{221}{}{Okay, now I need to find a place to clean up. Thank you, brother.}
{222}{}{By the way, what is the Brotherhood doing here?}
{223}{}{When the elders found out that the mutants had rushed to San Diego, I was sent along with a squad to investigate. I couldn't even think that a real hell was going on here. Radiation, monsters, super mutants, ghouls, robots — what's not here! I need to tell the commander about this. It is impossible for ordinary people to rush here too.}
{224}{}{Clearly. Well, then have a safe journey. Don't get caught by mutants anymore.}
{225}{}{Thanks again.}