{200}{}{Wa-a-ah, it's been a long time since I've been sleeping so sweetly.}
{201}{}{What are you doing here?}
{202}{}{Why the hell are you sitting in the fridge? I thought someone had hidden a corpse in it!}
{1202}{}{Why the hell are you sitting in the fridge? I thought someone had hidden a corpse in it!}
{203}{}{I hid from the mutants, and then I dozed off. How much time has passed? Probably just a couple of weeks. Okay, I'm going to sleep it off in the city.}
{204}{}{Pokedova.}
{205}{}{Don't fall asleep on the way, you strange creature.}
{206}{}{I want to sleep...}