{102}{}{Well, what else?}
{103}{}{I'll kill everyone from the Brotherhood of Steel I can find!}
{104}{}{I hate the Brotherhood! I hate it!}

{110}{}{Hey, fraternal dog, drop the gun and come out!}
{111}{}{I won't hurt you. I just want to talk.}
{112}{}{Say everything that boiled over.}
{113}{}{Do you know how many of our Lost Hills brats have killed?}
{114}{}{You took our house away from us. You have taken God away from us.}
{115}{}{Do you think we can get along after this?}
{116}{}{Oh, I'm SO angry. But I'll do you a favor—I'll kill you quickly. You won't feel anything.}
{117}{}{Agreed?}
{118}{}{Why are you suffering? Why are you resisting? I will put you out of your misery.}
{119}{}{God was behind us. And behind you are the generals. Pitiful people, how have you fallen!}

{200}{}{Hey, dead guy, be careful. There's a brat from the Brotherhood of Steel skerking around here somewhere. Look, don't be under his bullets.}
{201}{}{Ah, I see. Then I'll hurry away before it gets too hot in here.}
{202}{}{Don't you dare harass the Brotherhood people! I won't let you do that!}
{203}{}{Hey, I just saw him run off to the piers! While you were talking to the air here, he was already gone.}
{204}{}{Which... Wow, I'm going to catch up with him now! You won't leave!}
{205}{}{Hurry up, bully!}
{206}{}{Haha, you're a dumbass! It was easier to fool you than a child! What's going on, you fool?}
{207}{}{A bunch? And you're here? Hey, did you take a man as a slave? Younger-ec. And here I am trying to get the dog out of the Brotherhood of Steel. He hid in a cafe. Will you help me get rid of him?}
{208}{}{Heap, let's get out of here? It's none of our business.}
{209}{}{Heap, tell this klutz that the war is over. Stop feuding. Leave the man alone.}
{210}{}{A bunch and a person have become partners? I've never heard of it. Maybe there really is a truce? Okay, a bunch, I'll believe you.}
{211}{}{That's good. Go your own way.}
{212}{}{A-a-a! Die, stupid people!}
{213}{}{Not before you, stinky!}
{214}{}{Wait, let's talk!}
{215}{}{Wait! You and I have nothing to fight for. I don't want to hurt you.}
{216}{}{I still won't forgive what people have done to us!}
{217}{}{It's a pity that you understand in a good way...}
{218}{}{You shouldn't be so...}
{219}{}{The ghouls won't be happy with you. After all, they are building a city for everyone. Humans and mutants can live together in the Glow of the Day. Don't you really want the long-awaited peace?}
{220}{}{Ghouls are careless! Someday they will pay. People will betray them!}
{221}{}{And you protect them. Don't let people twist ghouls around your finger. After all, there will always be more people. Fighting alone can't fix this.}
{222}{}{You say great. I didn't think about it. Go to the city or something? Offer yourself to the ghouls as a guard? Why, that's a good idea! I won't let the ghouls offend, no!}
{223}{}{That's good. See? You can always negotiate.}
{224}{}{I'll have to agree with you here. So, shall we continue the fight, dumbass?}