{100}{}{There is a ghoul in front of you.}
{101}{}{Here is an ordinary ghoul.}

{200}{}{Hey, son, do you want me to tell you a fucking story?}
{1200}{}{Oh, lady, do you want me to tell you an inspiring story?}
{201}{}{But I won't tell you! Bought it, right?}
{1201}{}{But I won't tell you! Bought it, right?}
{202}{}{No, well, if you want to hear, then I would tell you over a mug of foam.}
{1202}{}{No, well, if you want to hear it, then I would tell you over a mug of foam.}

{210}{}{I lived in the sewers after the bombs fell. It fed on objects from puddles and rats. You shouldn't do that.}
{211}{}{Seth is our former leader. He held all ghouls with an iron hand. Fortunately, he is no longer with us.}
{212}{}{Even before the Great War, the oil on the planet ran out. Here a reasonable question arises — what did they fight for during the War?}
{213}{}{There are several large settlements in the north. But this is nothing compared to what megacities were before the War.}
{214}{}{The Master and his super mutants are a serious force. They tried to subdue people and ghouls. It's good that they were exhausted. But not to the end after all!}
{215}{}{Uv... I think I've been drinking too much... the interview is over...}