{100}{}{There is a ghoul in front of you.}
{101}{}{You see a ghoul in battle armor and helmet.}

{200}{}{John was talking about you. He said you were a smart guy. But how are you going to storm the island with such a pretty smooth face?}
{201}{}{Good question. I need to think about it.}
{202}{}{It's not your walking face that matters.}
{203}{}{John was talking about you. He said you were a smart guy. I hope you are aware of the risks that await you on the island?}
{204}{}{Good question. Probably, it is worth preparing in advance for disembarkation.}
{205}{}{I forgot to ask you.}
{206}{}{John was talking about you, but I didn't expect to see Gustavo's people here. What's going on?}
{207}{}{Yes, he, uh, doesn't have enough people. Gustavo will be in charge of the operation.}
{208}{}{Gustavo will be in charge of the mine. Is that clear to you?}

{210}{}{Okay. The alignment is like this. We have a transponder. Robots will not attack while we are in its area of action. It remains to launch the boat to go to the island. And then — according to the situation.}
{211}{}{I need time to prepare. Wait a bit.}
{212}{}{OK. What is my purpose on the island?}

{220}{}{Isn't this base destroyed? What is there to take?}
{221}{}{The whole island was littered with nuclear explosions. The land there is still barren. But the underground levels are partly preserved. Robots come from there and restore them there. This base is one of the largest in pre—war America. Even after the explosions, there should be many valuable relics left there.}
{222}{}{Surely there is monstrous radiation.}
{223}{}{Right. That's why only ghouls and robots will be able to work there. It's only to our advantage, yes. But you will have to prepare well so as not to get fried in the blessed isotope rays.}
{224}{}{What prevented you from landing there so far?}
{225}{}{Guns of Coronado Island. Some of them survived under the shields during the bombing. They stretch along the entire coastline and do not allow you to swim close. There are also concrete fortifications, garbage in the water, underwater mines and patrolling robots. And we also did not have a transponder, which we recently assembled at the liberated Factory. Well done, by the way, good job.}
{226}{}{What is my purpose on the island?}
{227}{}{For you, our smooth one, the goal is to disable the combat readiness system so that robots and guns stop firing at everyone in a row. And then we will figure out for ourselves what and how to take out from the island.}

{250}{}{Ah! Do you feel this beautiful fresh air?}
{251}{}{I only feel the radioactive dust from the scorched earth.}
{252}{}{Well, everyone's tastes are different. Don't forget — your goal is to disable the security system. Then we'll manage on our own. But don't try to touch everything in a row — there are still a lot of dangerous military toys that can make a handful of embers out of you.}
{253}{}{Understood, Captain obvious.}
{1253}{}{The task is clear, Captain obvious.}
{254}{}{Good.}
{255}{}{Your goal is to disable the security system. Then we'll manage on our own. But don't try to touch everything in a row — there are still a lot of dangerous military toys that can make a handful of embers out of you.}
{256}{}{The combat alert is disabled. Access to the base is open to everyone.}
{257}{}{Great job! Then we'll manage on our own. You can go back to the mainland.}
{258}{}{OK.}
{259}{}{By the way, what are you going to do with the local finds?}
{260}{}{Export, of course. Everything that can be useful, from cartridges to electronics — everything will go to the arrangement of the Dayglow or for sale.}
{261}{}{That is, some of these dangerous toys will fall into the hands of people?}
{262}{}{Of course. Any problems?}
{263}{}{No, sir. None.}
{264}{}{Stupid! These things in the wrong hands will be a disaster! I won't let you take anything out of here.}
{265}{}{Everything that can be useful, from cartridges to electronics — everything will go to the arrangement of the Dayglow.}
{266}{}{I see.}