{100}{}{You see Tobias.}
{101}{}{In front of you is a ghoul in a uniform and a border guard hat. His face is disfigured, and his gaze causes consternation.}
{104}{}{Thank you. I always felt that I was missing something here.}
{105}{}{Tobias pins a badge to his uniform. You notice the semblance of a smile on his disfigured face.}
{106}{}{Tobias already wears such a badge.}

{200}{}{[You won't pass. This place is only for ghouls.]}
{201}{}{[Okay, I'm leaving]}
{202}{}{[I will pass by force]}
{203}{}{[Give me a task to pass]}
{204}{}{[Destroy the robot in Tijuana]}
{205}{}{[Okay]}
{206}{}{[Robot neutralized]}

{210}{}{Man, you don't belong here. Go away.}
{211}{}{You have no right not to let me in.}
{212}{}{ (lifts the barrel of the machine gun) You will not pass until I give you permission.}
{213}{}{I'll pass anyway. Get out of the way, freak!}
{214}{}{Okay, okay, I don't want to go there that much...}
{215}{}{Why don't you want to let me in?}
{216}{}{There is no place for normies in the city of ghouls. You drove us into these ruins yourself.}
{217}{}{Look, I've come a long way here. Maybe we can come to an agreement?}
{1217}{}{Look, I've come a long way here. Maybe we can come to an agreement?}
{218}{}{Well, I'll have to leave. Sorry to bother you.}
{219}{}{Hmm. Maybe I'll let you through if you do us ghouls a favor.}
{220}{}{What service?}
{221}{}{A huge military robot has been wandering in the ruins of Tijuana since the War. Because of him, we cannot freely explore this area. Destroy it and I'll let you through the border.}
{222}{}{I'd rather destroy you. It's much easier.}
{223}{}{Agreed. I'll do it.}
{224}{}{The last time this robot was spotted near the Arena. We have installed electromagnetic traps there, but so far to no avail.}
{225}{}{Clear. I will keep in mind.}
{226}{}{I've already met this robot. He is no longer a danger to anyone.}
{227}{}{I'm not suicidal! It's better to go back to Sonora...}
{228}{}{You will not cross the border until I give you permission.}
{229}{}{Robot. It is destroyed.}
{230}{}{You must have a really good reason to go into town. Well, come on in. Welcome to the Dayglow.}
{231}{}{Thank you for the warm welcome.}
{232}{}{You should have let me through right away. I'm just wasting my time with you.}
{233}{}{Greetings, brother. For the first time in the Shining?}
{1233}{}{Greetings, sister. For the first time in the Shining?}
{234}{}{Yes. Will you let me into the camp?}
{235}{}{Of course! But you need to go through security. These are the rules, sorry.}
{236}{}{I understand everything.}
{237}{}{You know, I've already changed my mind about going to camp. Goodbye!}
{1237}{}{You know, I've already changed my mind about going to camp. Goodbye!}
{238}{}{Good. What is your name and where are you from?}
{239}{}{I }
{240}{}{ from Southern Arizona.}
{241}{}{Show me the backpack. Are there any prohibited items?}
{242}{}{It depends on what is forbidden here...}
{243}{}{I was joking! You can go to the camp.}
{244}{}{Seriously?}
{245}{}{Welcome to the Dayglow!}
{246}{}{Thank you.}
{247}{}{Previously, illegal border crossing was punished. But since you're already here, I just have to accept it. Don't you dare disturb the ghouls.}
{248}{}{No problem.}
{249}{}{I didn't expect it. Thank you. And — welcome to the Dayglow.}
{250}{}{You can pass.}
{251}{}{Goodbye.}
{252}{}{You can pass. I wouldn't let you in, but someone in the camp made a fuss for you.}
{253}{}{I'm going to be here for a while. Maybe you need help?}