{100}{}{Here is Ralph.}
{101}{}{You see a ghoul you already know. He is still wearing well-worn work clothes with a pre-war symbol.}
{102}{}{I wonder how the guys at the power plant are doing?}

{200}{}{What a meeting! The angel of the Electromagnetic Pulse must be bringing us together again.}
{201}{}{Ralph? What are you doing here? You were going to Texas, weren't you?}
{202}{}{I didn't want to leave Phoenix for a while. Because there are rather fat rats in the local sewers. But then a gloomy ghoul came to the city and told about the Dayglow. It dawned on me that it was better to be closer to my own people than to perish in the sands all alone. But what are you doing here?}
{203}{}{Looking for new adventures... probably.}
{204}{}{Hmm? I don't even know what to say. You're a strange man. Maybe you're not all right at home? But it will be difficult for you to get along here — radiation and traces of the Old World are all around. }
{205}{}{I know.}
{206}{}{Here, take the Radaway as a token of appreciation for the help at the power plant. It will come in handy.}
{207}{}{Thank you, Ralph. Bye.}
{208}{}{You mean, as a token of apology for what you did there? Okay, so be it, I'll take it. Bye, Ralph.}
{209}{}{Good luck then. I'll tell the others how I saw the light with your help. I think they should know, otherwise it doesn't look like you've been treated well here.}
{210}{}{Thank you, Ralph. I will be very grateful to you.}
{211}{}{Not worth it. I am satisfied with such a reputation. Goodbye.}

{220}{}{And it was fun at the power plant. I wonder how things are going there now?}
{221}{}{I don't know.}