{100}{}{This is Mr. Officer.}
{101}{}{There is a pretty worn icon painted on the board of this robot. It seems that he represents some kind of authority here.}
{102}{}{Be vigilant, citizen. It's not safe on the road right now.}

{110}{}{Stop it! You are violating traffic rules.}
{111}{}{Being on the motorway you are violating the current legislation.}
{112}{}{It is forbidden to be outside the vehicle on the motorway.}
{113}{}{You're under arrest. Leave the roadbed and lie face down on the ground.}
{114}{}{You're coming with me to the police station.}
{115}{}{Give up. You will not escape justice.}
{116}{}{I don't want to hurt you. You created this problem yourself.}
{117}{}{My program demands to stop you.}
{118}{}{All claims can be processed in the presence of a lawyer.}
{119}{}{I won't let you escape until you pay the fine.}
{120}{}{It's my duty to stop you before you cause a traffic accident.}