{100}{}{This is Kurt.}
{101}{}{Before you is an ordinary ghoul.}
{102}{}{I don't have any caps! NO WAY! NONE!}
{103}{}{OKAY! All right! Here are the caps. Just don't hit me anymore!}
{104}{}{OKAY! All right! Here are all my caps. I don't have any more!}
{105}{}{Kurt gives up.}
{106}{}{Oh, what do you want from me?}
{107}{}{What a fool!}

{200}{}{I'm just full of energy today! It's been a while since I've rested like this... Oh, what do you want from me?}
{201}{}{Who are you?}
{202}{}{My name is Kurt. And what?}
{203}{}{I'm looking for you. I'm collecting debts for Mr. De Santi.}
{204}{}{Mister is very angry, right? So let him be angry with himself! I'm not going to pay for his terrible services in a crappy room. And in general, it's a shame for a ghoul to take money from another ghoul! Who does he think he is? We're going to build communism here. Unnoticed or what?}
{205}{}{Don't fill me in here. Drive the covers!}
{206}{}{Mr. De-Santi won't leave you alone.}
{207}{}{I'm not going to pay! If you need it, you pay him!}
{208}{}{Then I'll take the caps by force. Turn out your pockets!}
{209}{}{Okay, I'll have to pay for you instead.}