{100}{}{You see Derrick.}
{101}{}{There's a ghoul in front of you. He keeps a close eye on those who walk down the street.}
{102}{}{My business collapsed with the death of De Santi.}
{103}{}{All right! All right! I'm going to work for him. Just don't touch my fragile tender body!}
{104}{}{Derrick is not going to fight anymore.}

{200}{}{Hello, smooth face. Where are you going?}
{201}{}{None of your business.}
{202}{}{Okay, whatever you say.}
{203}{}{Adios.}
{204}{}{Maybe to the Old Town, or maybe to an institution across the street, or maybe nowhere. Why are you asking?}
{205}{}{Why are you asking?}
{206}{}{I can give you a lift. Or are you going to a sanatorium? But it's only for ghouls. So I do not advise you to go there smooth-faced. And there's nothing to do there. After all, I can get all kinds of relaxation at a low price. Contact me, you won't lose.}
{207}{}{Okay, let's see what you have.}
{208}{}{I can give you a lift. Or are you going to a sanatorium? It's only for ghouls. But keep in mind that the prices there are as high as the squeak of my late wife. I can get all kinds of lawn at a low price. Contact me, you won't lose.}
{209}{}{Hmm. I will keep in mind.}
{210}{}{Hello, mutyara. Where are you going?}
{211}{}{You'll be back for a new dose.}
{212}{}{Yeah. Bye.}
{213}{}{I doubt it very much.}
{214}{}{And "I can throw" — how is it?}

{220}{}{Ah, you again. What do you want this time?}
{221}{}{Oh, nothing special. Goodbye.}
{222}{}{Show me what you have.}
{223}{}{Not "where", but "what". Let me see what you're selling here.}

{230}{}{Well, Derrick, you're on the money. De-Santi is unhappy that you are intercepting his clients.}
{231}{}{This is free land. I want to trade here — and I will.}
{232}{}{Aren't you afraid that this land will become a grave for you?}
{233}{}{I can still understand when the bandits of the Wild West are admired. They met in a fair fight. And De-Santi was just a small fry in the gang environment of Bakersfield. And so he remained. He can't intimidate me.}
{234}{}{Oh, well, okay. I don't want to mess with it.}
{235}{}{You talk too much, Derrick. I'll have to teach you a lesson.}
{236}{}{You'll regret it. Someday.}
{237}{}{Now you have a choice — to die or work for De-Santi. So, I'm waiting for an answer. Times...}
{238}{}{Hey, hey, you're not going to do the dirty work for some ex-thug, are you?}
{239}{}{I'm not going to. I'm just kidding. Bye, Derrick.}
{240}{}{I don't care as long as he pays. And I'm also spending time with you. It's time to finish with you!}
{241}{}{Two...}
{242}{}{Whoa-whoa-whoa, did De-Santi really order me? Seriously? What the hell!}
{243}{}{Three!}
{244}{}{All right! All right! I'm going to work for him. Just don't touch my fragile tender body!}
{245}{}{It's too late, Derrick. You got me. I'll have to punish you!}
{246}{}{Great. And let's not be silly. Now De Santi is the boss here.}

{250}{}{You said you could "give it a lift."}
{251}{}{Well, I haven't had a car for a long time. But I know fast and safe ways. Where do you need to go?}
{252}{}{[San Isidro for }
{253}{}{[Bonita Dam for }
{254}{}{ hubbucks]}
{255}{}{I think I'll go on my own.}
{256}{}{Not enough, right? It's a pity.}
{257}{}{Yes, I'll have to walk on my own two feet.}
{258}{}{Wait, there's something else I need to know.}
{259}{}{[Chula Vista for }