{100}{}{You see a black scavenger.}
{101}{}{You see a black scavenger.}
{102}{}{This is our neighborhood. Get out of here.}
{103}{}{We work with De-Santis. If you need anything, talk to him.}

{200}{}{This is our neighborhood. Get out of here.}
{201}{}{I apologize. I will leave your domain right now.}
{202}{}{And if I refuse, then what? Do you only know how to scare?}
{203}{}{This is not your neighborhood. This is Mr. De Santi's neighborhood.}
{204}{}{What are you doing? And who is it? Another overgrown ghoul? Why should we take him into account?}
{205}{}{You work illegally, right? De-Santi will give you Seth's seal, provided that you work for him.}
{206}{}{We don't need Seth's seal! Otherwise, we would have received it long ago. Do you understand?}
{207}{}{It seems to be useless to talk to you. You only understand brute force...}
{208}{}{[Leave]}