{100}{}{This is Flowers.}
{101}{}{You see a hefty super mutant.}
{102}{}{I want to eat!}
{103}{}{Welcome to... uh, forgot the name.}
{104}{}{Right. Ghouls and mutants should get along.}
{105}{}{Yum-yum... This is not enough!}
{106}{}{Now I'm full!}

{200}{}{You! Don't be afraid of me... Come closer... I won't eat you... Arch! Got you, stupid mouse! Oh, I ran away...}
{201}{}{Who are you catching there, big guy?}
{202}{}{I'm hungry! Hey, do you have any food? Hmm, and you're nothing like that either... But no! I can't eat you! The ghouls won't take me in then.}
{203}{}{So you're Flowers? Mr. De Santis is offering you a job. If you agree, you will have food.}
{204}{}{I'm hungry! First food, then talk!}
{205}{}{Okay.}
{206}{}{Yum-yum-yum... That's not enough!}
{207}{}{Do you want more? Then go work for De Santis.}
{208}{}{Go to De Santi. De-Santi is probably a good ghoul. I'm off!}
{209}{}{I think you'll find your way. Meet me in the Italian Quarter.}