{100}{}{Here is a bath attendant.}
{101}{}{You see an ordinary golchikha in an old dressing gown.}

{110}{}{I can massage your back, bunny. Just make the payment to the administrator first.}
{111}{}{Do you want to swim? I'll wash ALL your body parts.}
{112}{}{We have radium water, a radon bath, a uranium Jacuzzi and a plutonium shower. Choose what you like best.}
{113}{}{A good ablution costs money. And my tenderness is worth even more.}
{114}{}{With me you will forget about all your problems, zainka.}
{115}{}{Come on, take off your pants. I know where you can touch and where you can't.}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}