{100}{}{You see a mechanical ghoul.}
{101}{}{Here is a ghoul in a dilapidated work uniform. Instead of one eye, he has something like a built-in lens.}
{102}{}{Excuse me. Only ghouls and friends of ghouls are served here.}
{103}{}{I won't serve an ass like you. Go away.}
{104}{}{It won't work on me. But it looks cool.}

{200}{}{This is a workshop and a hardware store. The boss says it's possible to negotiate with you. But I will still look out for you.}
{201}{}{You'll see, it's completely in vain.}
{202}{}{That's not how they talk to customers.}
{203}{}{That's all I have. If you need more details, then go to the Old Town.}
{204}{}{Bye.}
{205}{}{Wait, I have something else to discuss.}
{206}{}{Hello, skin! It's good to see you. This is a workshop and a hardware store. Come in, choose whatever you like. I have a big discount for ghouls and mutants.}
{207}{}{That's good.}
{208}{}{I need to look at the things on the counter again.}
{209}{}{}

{210}{}{Hello, skin. How are you doing?}
{211}{}{Hello, green creature. What spare parts are needed this time?}
{212}{}{Hello, damn mutant. Sorry, but there are no extra arms and legs anymore. Haha, a joke.}
{213}{}{Hello, ugly. How are you feeling today?}
{214}{}{Need spare parts? Then choose faster and get lost.}
{215}{}{Need spare parts?}
{216}{}{Tell me what you're looking for. Nothing is too bad for you.}
{217}{}{I need to buy some items.}
{218}{}{Bye.}

{220}{}{There's a dead guy with a rebar in his head who asked me to fix it.}
{221}{}{And that's all? Okay, come here...}
{222}{}{Here.}
{223}{}{No, I want to try it myself...}
{1223}{}{No, I want to try it myself...}
{224}{}{Oh, I don't like that he messed with you. But since you're here, you'll have to help. Give me that thing...}
{225}{}{Done. Don't break it on the way.}
{226}{}{Okay. Thank you.}
{227}{}{I know without you!}

{230}{}{I have a holodisk with an old movie. Can you make a copy of it?}
{231}{}{Ah, conscience is tormented, right? Of course, to steal an important thing from an autistic person and then walk without a headache is to be a completely finished scumbag. But why should I listen to you, and not return the disk to its rightful owner?}
{232}{}{I just need a copy to return the original to him. Can you imagine, right?}
{233}{}{Oh, it changes a lot. Good. I'll make a copy for }
{234}{}{ hubbucks. Caps forward.}
{235}{}{Wait a bit, I'll go get the caps.}
{236}{}{Then do it. Here are the caps and the disk.}
{237}{}{You have received a copy of the holodisk.}

{250}{}{I need to upgrade my weapon.}
{251}{}{To begin with, show your weapon.}
{252}{}{I don't have anything worthwhile right now.}
{253}{}{[}
{254}{}{ for }
{255}{}{]}
{256}{}{Done. Do you want to improve anything else?}
{257}{}{No. Thank you.}
{258}{}{Yes. Perhaps.}
{259}{}{Tell me honestly: you can't afford it, can you?}
{260}{}{Oops.}