{100}{}{You see Cabot, the ghoul trader.}
{101}{}{Here is a local merchant.}
{102}{}{I don't serve traitors. Get out of my store.}
{103}{}{Listen, if you don't like our city, then get back to your dense wastelands, you blockhead.}

{200}{}{Hello, man. I'm a Cabot, and this is my shop. If you need something, just tell me.}
{201}{}{Hello, Cabot. What are you selling?}
{202}{}{Finds from all over the Shining are flocking to me. However, some of them are immediately taken away by caravans to the north.}
{203}{}{Why?}
{204}{}{Here in the Old City, we believe that we must help people restore civilization with the help of old things and knowledge... Well, that's what Butler says. Personally, I'm just looking for a benefit. I'm a merchant. Always has been.}
{205}{}{Let's see what kind of junk they brought you this time...}
{206}{}{I wanted to take a look at all these pre-war relics. Show your product...}
{207}{}{Sorry, man, but you can't count on discounts. The prices for you will be the same as for the rest of the smooth-skinned.}
{208}{}{Okay, whatever you say...}
{209}{}{I have special prices for mutants and ghouls. They are more... let's put it this way... democratic. Don't think I'm a racist, but we have two attitudes towards people here. And I will sell you the goods at a reasonable price.}
{210}{}{Oh, thank you, my friend.}
{211}{}{Here is all the best that was found in the ruins of the great city!}
{212}{}{Goodbye.}
{213}{}{Can I ask you a few questions?}

{220}{}{What are you looking for, friend?}
{1220}{}{What are you looking for, girlfriend?}
{221}{}{What do you need, baby?}
{222}{}{What is it this time?}
{223}{}{Goodbye.}
{224}{}{I need to buy something.}

{230}{}{Have you still not found the fuel controller for Rutger?}
{231}{}{He was definitely here! I rummaged through all the boxes, but I couldn't find it.}
{232}{}{Who else could have seen it?}
{233}{}{Well, the courier Steve Morgan brought this thing. It seems that after that he went to burn the caps in the bar. I haven't seen him since.}
{234}{}{I'll try to find him there. Later.}

{240}{}{I'm looking for a dead guy named Rupert. Do you know where he is?}
{241}{}{Rupert? He arrived in Glow a month ago. I haven't seen him since.}
{242}{}{Okay, forget it.}
{243}{}{Who else did he communicate with before he disappeared?}
{244}{}{I don't know.}
{245}{}{Where did he go?}
{246}{}{I don't know.}
{247}{}{Did he say what he was going to do?}
{248}{}{No. Although... He said he was tired and wanted to relax.}
{249}{}{And what did you say?}
{250}{}{Well, I told you about the recreation area at the La Pension Hotel. I haven't seen him since.}
{251}{}{Is that the one in the Italian district? I see, thank you.}

{260}{}{Do you know where I can get programs for Mr. Assistant?}
{261}{}{Ask Phil about it in the library. He's got a big brain, maybe he'll come up with something.}
{262}{}{Thank you.}

{270}{}{Someone left an encrypted holodisk for me.}
{271}{}{Someone, you say? You don't even know his name?}
{272}{}{Well, he didn't introduce himself.}
{273}{}{I see. There really is a holodisk. Give me your PipBoy. Let's try to load this entry into it.}
{274}{}{[Next]}
{275}{}{(You insert the holodisk and start the decryption process. It turns out that the recording is encrypted specifically for your Peep-Fight.)}
{276}{}{[ Read entry]}
{277}{}{"Sorry I didn't meet you. I have a lot to do. But you'll figure it out without me."}
{278}{}{[Next]}
{279}{}{"There is a disagreement between Gustavo and Butler about the future of the Dayglow. And honestly, I do not know which of them is more right. It is more important that people do not suffer from this. The Dayglow is not just ruins. It's full of pre-war stuff, some of it extremely dangerous. We must not allow them to fall into the wrong hands."}
{280}{}{[Next]}
{281}{}{"In addition to humans and ghouls, there is another force that is looking for these resources. The Brotherhood of Steel. They are securely locked in the old launch shaft. Try to contact them and decide whether to let them run the place. You can find them using a walkie-talkie or a radio station. Here is the frequency and cipher they use."}
{282}{}{[Next]}
{283}{}{"And one more thing. I stashed things in Balboa Park in an old pipe at the monorail substation. I think you need them more. Before communication."}
{284}{}{[Pull out the holodisk]}
{285}{}{[Read again]}