{100}{}{This is Father Talius.}
{101}{}{You see a mutant in a shabby shirt and hat. He sees a cross on his neck.}
{102}{}{You see before you Talius, a member of the sect of Followers.}
{103}{}{Give it to someone who really deserves to wear it.}
{104}{}{Fernando stayed in town.}
{105}{}{Beatrice stayed in town.}

#First meeting
{200}{}{Greetings, brother. My name is Talius. And I'm glad to see you Shining. Do you need help?}
{1200}{}{Greetings, sister. My name is Talius. And I'm glad to see you Shining. Do you need help?}
{201}{}{You're not my brother. Have you ever seen yourself in the mirror?}
{202}{}{I see you're not very smart either. But I was the same once. But learning from Followers has made me smarter.}
{203}{}{Does your skull feel tight?}
{204}{}{You know, it really happens. Sometimes I have to prune the extra convolutions through this hole in... Ah, it seems you're talking about something else. I apologize. I forget myself from time to time. Do you need some brain help?}
{205}{}{I'm sorry, I just mean there are a lot of differences between us. And this is not racism.}
{206}{}{Yes, perhaps. So you need my help?}
{207}{}{I just dropped by to see this place.}
{1207}{}{I just dropped by to see this place.}
{208}{}{Thank you for the kind welcome. It's unexpected to hear this in such a place.}
{209}{}{I understand. Ghouls are suspicious of normies. They've been through too many attacks. But show yourself on the good side — and the ghouls will be glad to see you.}
{210}{}{I hope so. But why are you so friendly?}
{211}{}{That was sarcasm, you idiot! There's no way I'm going to be friends with freaks like you.}
{212}{}{Sorry to hear that. I hope you'll change your mind over time. Maybe you need some brain help?}

{220}{}{Greetings, brother. Do you need help?}
{1220}{}{Greetings, sister. Do you need help?}
{221}{}{No, don't. Sorry to bother you.}
{222}{}{What do you want to know?}
{223}{}{Nothing else. Thank you for your time.}
{224}{}{A lot, but you still don't know anything. Bye.}
{225}{}{There will be big changes in the Glow soon. And after that, changes will overtake the rest of the world. This is both frightening and inspiring... Do you need help?}

#About Followers
{230}{}{This is the chapel of the Followers of the Apocalypse. Here I help the ghouls comprehend our teaching.}
{231}{}{Sorry to interrupt. But I want to change the subject.}
{232}{}{I know a few Followers. We met in Casa Nueva.}
{233}{}{Then you know enough. The followers of the Apocalypse are kind people. They want to bring peace to this cursed land.}
{234}{}{Where are the rest of the Followers?}
{235}{}{I'm alone here. Only ghouls and mutants can live in the midst of irradiated ruins. But almost all the Followers are ordinary people. Their main base is in another city.}
{236}{}{How did you become a Follower if you... well... ghoul?}
{237}{}{Would you believe me if I said that I have a different nature? My followers saved me from turning into a disgusting animal while I was lying unconscious under the influence of a mutagen. After that, they let me join their knowledge. They are kind people.}
{238}{}{I see.}
{239}{}{What kind of teaching?}
{240}{}{The followers of the Apocalypse want to bring peace to this cursed land. They preach altruism and non-violence. They use pre-war knowledge to improve people's lives. But the most important thing is that they will not allow people to repeat the mistake of 2077.}
{241}{}{Tell me about your faith.}
{242}{}{Your words about Followers touched me to the core. I want to make a donation.}
{243}{}{That's noble of you. How many hubbucks can you donate to good causes?}
{244}{}{Right now, not at all. I mean I'll do it in the future.}
{245}{}{100 caps.}
{246}{}{200 caps.}
{247}{}{300 caps.}
{248}{}{400 caps.}
{249}{}{500 caps.}
{250}{}{Thank you. Have a nice day!}
{251}{}{You're welcome.}
{252}{}{How relieved I am. But I want to talk to you again, Father Talius.}

# About myself
{260}{}{What's your name again?}
{261}{}{I am Talius.}
{262}{}{Okay, Talius.}
{263}{}{Where are you from, Talius?}
{264}{}{My homeland is far away from here, in an old Vault with the number 13.}
{265}{}{I know about several Vaults, but this is the first time I've heard about 13.}
{266}{}{I've never heard of it.}
{1266}{}{I've never heard of it.}
{267}{}{Of course. There were many such Vaults. And many of them are no longer working these days.}
{268}{}{Did the other ghouls also come from Vault 13?}
{269}{}{No matter. Let's change the subject.}
{270}{}{Almost all of them are from Vault 12, which is located under the city of Necropolis. I've been there too, looking for details for my hideout. And just after that mutated.}
{271}{}{So you're not a ghoul?}
{272}{}{A sad story. We need to change the subject.}
{273}{}{A mutant. I was made like this by the scientists of the Creator. They wanted to turn me into a super mutant, but something went wrong.}
{274}{}{A mutant. I was made like this by the scientists of the Creator. They wanted to turn me into a super mutant, but something went wrong. And it seems that something similar happened to you.}
{275}{}{It's really terrible. I wish I could help you with something.}
{1275}{}{It's really terrible. I wish I could help you with something.}
{276}{}{Thank you for the kind word. You know, I used to be an atheist. But after fate has made me immortal, you will involuntarily believe in God's plan. Maybe it's just such a test?}
{277}{}{It must be bad to be like that. But nothing can be done.}
{278}{}{You know, I used to be an atheist. But after fate has made me immortal, you will involuntarily believe in God's plan. Maybe it's just such a test?}
{279}{}{Can we talk about something else?}
{280}{}{Good luck, Father Talius.}

#Vault 24
{290}{}{I remembered a conversation about Vaults. Are they in the Glow?}
{291}{}{Perhaps. Why do you ask?}
{292}{}{Just logical reasoning. Nevermind.}
{293}{}{Well, I came across this thing. I think it has something to do with Vaults.}
{294}{}{Flask from Vault 24... A relic of ancient times. Where did you get it from?}
{295}{}{I found one skeleton in a jumpsuit. I think the skeleton has been lying in ruins for many decades.}
{296}{}{Perhaps it was one of the observers that the Followers sent to investigate. A lot of good people died in those hard times.}
{297}{}{Did the followers also come out of the Vault?}
{298}{}{Those who were the progenitors of the Followers. The rest were already born after leaving the Vault or joined from the outside.}
{299}{}{What happened to this Vault?}
{300}{}{I do not know the whole story. The Vault is now useless. The followers took out everything valuable from there. Besides, there are terrible creatures in those places. I don't recommend going there.}
{301}{}{I'll still take a chance. At least for the sake of history. Show me the way.}
{302}{}{The Vault can wait. I don't want any dangerous adventures yet.}
{303}{}{It is located in the center of Auteuil Park. It's hard to find him, so I'll plot a route on your PipBoy.}
{304}{}{[Go right now.]}
{305}{}{Not now. I need to get ready for a hike.}
{306}{}{I'll still take a chance. What if they haven't taken everything out yet? Lead the way.}
{307}{}{Isn't it too brazen of you to break into someone else's domain? Everything here belongs to the ghouls. Many people don't like your very presence here. I'll show you the Vault, but I'm counting on a good donation in return. Let's say 1000 caps.}
{308}{}{I can't spend that much. Let's put this question aside for now?}
{309}{}{OK. Here are 1000 caps. Show me.}
{310}{}{In return, you'll be safe, asshole. This is the best you can count on.}
{311}{}{I need to get back to Vault 24. Right now.}
{312}{}{Help me get into Vault 24.}

# Madman
{320}{}{Is there anything I can do to help your people?}
{321}{}{Our souls need salvation, and we are coping with the rest. Recently I was informed about another victim of insanity: Our friend Gonzo went berserk and fled to the ruins of Chula Vista. In this state, he is dangerous. He needs to be stopped.}
{322}{}{Is it possible to do without deaths?}
{323}{}{Are you asking me to KILL him?}
{324}{}{(sigh) Will any of the ghouls raise their hand against their fellow? I don't think so. Many ghouls will condemn it. But there is no cure for insanity either. We can only do one thing — avoid unnecessary sacrifices.}
{325}{}{You just have to chop off his head — that's it.}
{326}{}{I've seen this before in Inferno. Only death will stop such madness.}
{327}{}{You can't just take the lives of others! If it is impossible otherwise, then we will have to send Gonzo to his forefathers. But remember that Gonzo is our brother. The ghouls lived with him for many years in the Necropolis. Show some compassion.}
{328}{}{Is it possible to restore his sanity for a while?}
{329}{}{In some cases, medications help, in others, triggers from the past. And maybe nothing will help. But any solutions are temporary.}
{330}{}{I'll figure something out.}
{331}{}{God help you.}
{332}{}{I'll be back.}
{333}{}{I have a couple more questions.}
{334}{}{Even if you can't handle your own brother, I certainly can't. Sorry.}
{335}{}{I understand. In that case, just avoid Gonzo if you meet him in the ruins.}
{336}{}{Remind me where to find Gonzo?}
{337}{}{He was last seen in the old shopping district on the ruins of Chula Vista. This area is located to the north.}
{338}{}{Clear.}
{339}{}{}
{340}{}{Gonzo is dead. He left me no choice!}
{341}{}{Well, now his soul will calm down. (sigh) Good. I don't hold a grudge against you. I'm only angry at myself for not being able to help the distraught. Obviously, all ghouls will end up with this sooner or later. There is no cure for insanity.}
{342}{}{Don't blame yourself. Life goes on after all.}
{343}{}{He was a danger to society. You know it yourself.}
{344}{}{Thank you for your kind words.}
{345}{}{Let's change the subject.}
{346}{}{Gonzo's not dangerous now, right?}
{347}{}{Thank you. Gonzo the madman is securely sealed behind bars. Obviously, all ghouls will end up with this sooner or later. There is no cure for insanity. It remains only to lock up Gonzo to avoid unnecessary casualties. If you need soul and body treatment, I will also try to help.}
{348}{}{Just don't lock me up behind bars!}
{349}{}{I'll keep that in mind.}

#Treatment
{350}{}{Do you cure diseases?}
{351}{}{My followers taught me the simplest medical procedures. But the drugs here are very expensive and rare. What's hurting you?}
{352}{}{I need treatment.}
{353}{}{Nothing. Just wondering.}
{354}{}{ caps]}
{355}{}{[Treatment of wounds for }
{356}{}{[Treatment of serious injuries for }
{357}{}{[Treatment of radiation sickness for }
{358}{}{[Treatment of poisoning for }
{359}{}{You're fine.}
{360}{}{Thank you.}
{361}{}{[Heap Treatment for }
{362}{}{He's fine.}

#Donovan
{380}{}{It's a strange situation here, Doc. This is Donovan. And he's dead.}
{381}{}{Really?}
{382}{}{But his friends can't believe it. What should I do now?}
{383}{}{Dead, you say? Donovan? Come on, of course he's alive!}
{384}{}{And you're there too? Are you all gone here?}
{385}{}{Here, look. He's not breathing. And he doesn't have half of his body. He's dead.}
{386}{}{Give it to me. I'll take care of him next. That's just...}
{387}{}{Just what?}
{388}{}{I'm afraid I won't be able to help him without some items. Do you know where the hospital is? I need to get three jars of biogel out of there.}
{389}{}{Yes, you really have gone. I'm going to go about my business.}
{390}{}{Well, you know better. I'll try to get the parts and the biogel.}
{391}{}{I have what I need.}
{392}{}{Excellent! Well, let's not waste time — let's start the operation.}
{393}{}{Uh, okay...}
{394}{}{(The operation lasts several hours behind closed doors. You're waiting outside. Finally Talius comes out and says loudly: "Donovan will live!")}
{395}{}{Wow, Talius, you're doing wonders!}
{396}{}{Yeah. That's how I believed it. Well, well. Bye, charlatan Talius.}
{397}{}{About Donovan.}