{100}{}{You see a stranger.}
{101}{}{Here is a man in a blue jumpsuit.}

#Cut scenes
{110}{}{   }
{111}{}{Who are you guys?}
{112}{}{It's none of your business. You will ask questions to Butler. And now — get out of here.}
{113}{}{Mercenaries, then. Of course, Butler won't back down that easily.}
{114}{}{But it's too late. Coronado belongs to the gulyams of San Isidro. And you don't belong here.}
{115}{}{Ugh! Only in vain we grab radiation with this rags. Throw them off the pier, guys!}

{122}{}{It's none of your business. We won't let anyone sail to the island without our permission.}
{123}{}{Ah, black scavengers? Of course, everyone wants to get the Coronado treasure.}
{124}{}{But Coronado belongs to ALL ghouls! San Isidro also has a right to it!}
{125}{}{Ugh! Only in vain we grab radiation with this rags. Drive them out of here!}
{126}{}{Only Coronado belongs to the GHOULS! Get off our land, smooth-faced!}

#Final dialogue
{200}{}{Hey, hey! Are you okay? Wake up!}
{201}{}{Thu... What happened?}
{202}{}{You lost consciousness after the explosion. But everything seems to have worked out. I was afraid you didn't get my invitation.}
{1202}{}{You lost consciousness after the explosion. But everything seems to have worked out. I was afraid you didn't get my invitation.}
{203}{}{There was a fight. Someone detonated a grenade, and you lost consciousness from it. But everything seems to have worked out. I was afraid you didn't get my invitation.}
{1203}{}{There was a fight. Someone detonated a grenade, and you fainted from it. But everything seems to have worked out. I was afraid you didn't get my invitation.}
{204}{}{Who else are you?}
{205}{}{You may have heard of me. But it doesn't matter. I'm glad you managed to complete this mission.}
{1205}{}{Maybe you've heard of me. But it doesn't matter. I'm glad you managed to complete this mission.}
{206}{}{Do you think I made the right decision?}
{1206}{}{Do you think I made the right decision?}
{207}{}{I will not evaluate your choice. You did what you thought was right.}
{1207}{}{I will not evaluate your choice. You did what you thought was right.}
{208}{}{[Listen]}
{209}{}{}

{210}{}{Of course, the ghouls will be terribly upset that the fragments of the Old World will not get to them.}
{211}{}{They could give a lot of benefits to this world. But they could also fall into the wrong hands.}
{212}{}{Who knows, perhaps, thanks to that explosion, the world avoided another catastrophe. Or vice versa — it was the things from this base that were not enough to return civilization to the rails of history. Anyway, the base is finally destroyed. And with it — the discord between the ghouls.}

{220}{}{Of course, there will be some discord among the ghouls over the rights to the fragments of the Old World.}
{221}{}{Gustavo will try to take everything for himself and use it for the development of San Isidro. He will not share with human settlements, which are also in dire need of pre-war things. Butler will try to stop him.}
{222}{}{As a result, Gustavo will be stronger, he will lure most of the ghouls to his side. And then the Dayglow will live its usual dull peaceful life, shutting itself off from the rest of the world. As many ghouls wanted.}
{223}{}{Gustavo will try to take everything for himself and use it for the development of San Isidro. And he will not share with human settlements, although they are also in dire need of pre-war things.}
{224}{}{The Dayglow will heal its own little closed xenophobic life. As many ghouls wanted.}

{230}{}{Of course, there will be some discord among the ghouls over the rights to the fragments of the Old World.}
{231}{}{Butler will begin active trade with human settlements in the north. For some of them, pre—war things will be life-saving, for some - disastrous. San Isidro will get mere crumbs, which will turn it into a slum.}
{232}{}{Gradually, the resources will be exhausted. But thanks to trade, the Dayglow will survive and live its usual dull peaceful life. As many ghouls wanted.}

{240}{}{Of course, the ghouls will be terribly upset that the fragments of the Old World will not get to them.}
{241}{}{The Brotherhood of Steel won't let anyone near this gold mine. The Order will take everything valuable for itself and transport it to the main base.}
{242}{}{The Ghouls will be left with mere crumbs. Over time, people will forget about them. And then the Dayglow will live an ordinary dull life.}

{250}{}{Of course, there will be great strife among the ghouls over the rights to the fragments of the Old World.}
{251}{}{Without their leaders, they will need a lot of time to find a compromise of forces and interests. It will be a period of chaos and confusion. Including in the north, in human settlements.}
{252}{}{Some of the pre—war stuff will fall into good hands, some into bad hands. Ghouls will get the least. But they are not used to it. The Dayglow will be the same as the Necropolis was before the ghouls left there. Apparently, this is their fate.}

{260}{}{Well. My business here is over. Yours probably are, too. It was good to see you. Adios, amigo.}
{261}{}{Goodbye, stranger.}