{100}{}{You see an old ghoul.}
{101}{}{In front of you is a lonely living ghoul. If not for his frighteningly perishable appearance, he would have looked quite friendly.}
{102}{}{The border guards are looking for you. I won't help you even for a bunch of hubbucks.}
{103}{}{How did you find out about the secret passage? Even Tobias didn't know about him!}
{1103}{}{How did you find out about the secret passage? Even Tobias didn't know about him!}

#Acquaintance
{200}{}{(At first it seems to you that the shrunken body of the deceased is sitting in the chair. But when you approach, the body slowly raises its head and says in a hoarse drawling voice) Why are you here, man?}
{201}{}{I'm looking for a way to get into the Glow of the Day.}
{202}{}{Our city is open only to the dead. There's nothing for the living to do there.}
{203}{}{Oh, then I really shouldn't go there. Bye.}
{204}{}{And yet I want to get there.}
{205}{}{I won't try to dissuade you. But Tobias will hardly let you through the border.}
{206}{}{Then I'll try to convince him. Bye, old man.}
{207}{}{Is there a workaround?}
{208}{}{All other roads are extremely dangerous. But there's no need to go that far. I know one shortcut. I can spend it, but not for free. How many Hubbucks do you have?}
{209}{}{Hubbucks?}
{210}{}{So, you're offering something obviously illegal. I'm not going to go that far. Goodbye.}
{211}{}{Caps! Bottle caps! They were invented in the Hub to replace pre-war money. So how many bottle caps do you have?}
{212}{}{I don't have any bottle caps.}
{213}{}{I don't have any hubbucks.}
{214}{}{You're lying. I know you came here with caps. From where? (he pokes his temple with his finger) X-ray vision. Hehe, a joke.}
{1214}{}{You're lying. I know you came here with caps. From where? (he pokes his temple with his finger) X-ray vision. Hehe, a joke.}
#Note: In fact, this is not X-ray vision, just a gul guide studied GG and his belongings while sleeping at one of the parking lots.
{215}{}{You're delusional, old man. I'd better get out of here.}
{216}{}{Okay, here are all my caps. Now take me to the city!}
{217}{}{Now — tilt your head... Don't worry, I'll take this bag off when we go out into the city. Trust me. Hehe, you're not the first one I've led across the border.}
{1217}{}{Now — tilt your head... Don't worry, I'll take this bag off when we go out into the city. Trust me. Hehe, you're not the first one I've led across the border.}
{218}{}{Uv... Okay. But be careful.}
{219}{}{Don't even try to deceive me, old man.}
{220}{}{I believe. It's stupid, of course, to go across the border without any money at all. What should I do with you now? All right, bring me three cans of good old Mexican beer. They can still be found in the ruins on Revolution Avenue.}
{221}{}{I hope they really are there.}
{222}{}{What about irradiated Nuka-cola? I found five whole bottles in the ruins.}
{223}{}{I have five bottles of non-irradiated core Cola. Will they suit you?}
{224}{}{Here are three cans of old beer.}
{225}{}{It's a deal. Apparently, there's nothing more to take from you.}
{226}{}{So will you take me to the city?}
{227}{}{Did you manage to find what I asked for?}
{228}{}{No. Maybe I was looking in the wrong place? I'll try to walk through the ruins again.}
{1228}{}{No. Maybe I was looking in the wrong place? I'll try to walk through the ruins again.}
{229}{}{}
{230}{}{Still can't get across the border, can you? I know one shortcut. I can spend it, but not for free. How many hubbucks do you have?}
{231}{}{Are you leaving the Dayglow already? Well, you really should go.}
{232}{}{Bye.}
{233}{}{(You see an old man sitting in an armchair; he slowly raises his head, showing his disfigured face; in a hoarse drawling voice he calls you) Ah, fresh blood! Glad to see you in our dead kingdom. If you need to cross the border, then talk to Tobias, he will be happy to let you through.}
{234}{}{I'll do that. Later.}
{235}{}{Who is Tobias?}
{236}{}{Tobias is the guardian of the city gates. We can say that he is an intermediary between the world of the living and the world of the dead.}