{100}{}{Here is an arcade machine.}
{101}{}{You see an arcade-type slot machine. Ageless classics.}
{102}{}{To start the game, you need to pay. Current Record: }
{103}{}{ (Unknown).}
{104}{}{ (}
{105}{}{).}

{200}{}{"Your spaceship is heading to the center of the galaxy. Caution! There's a cluster of asteroids ahead! Dodge them up and down or release plasma charges for destruction. The longer you hold out, the more points you get!"}
{201}{}{Go ahead!}
{202}{}{Read the rules.}
{203}{}{Refuse and take the money.}
{204}{}{Refuse.}

{210}{}{Control the spaceship ( }
{211}{}{), so as not to collide with asteroids (}
{212}{}{). A collision with an asteroid takes one life. You can dodge the asteroid up or down, but only within three lines.}
{213}{}{}
{214}{}{You can also collect points in flight (}
{215}{}{) and plasma charges (}
{216}{}{). One charge destroys one obstacle, and a super—volley destroys the entire line ahead. It will be a huge success to pick up a whole life (}
{217}{}{).}
{218}{}{ Close help.}
{219}{}{Next.}

#do not delete spaces in lines!
{220}{}{-|> }
{221}{}{ [X] }
{222}{}{ -o- }
{223}{}{ -z- }
{224}{}{ ---}
{225}{}{ -Y-}
{226}{}{) }
{227}{}{ -Z-}
{228}{}{(}

{230}{}{Above.}
{231}{}{Forward.}
{232}{}{Below.}
{233}{}{-Above-}
{234}{}{-Below-}
{235}{}{Volley! (}
{236}{}{-Volley-}
{237}{}{Superzalp!}
{238}{}{)}
{239}{}{Explosion! (}

{240}{}{Pause.}
{241}{}{The game is stopped. Lives: }
{242}{}{. Charges: }
{243}{}{. Points: }
{244}{}{. Your record: }
{245}{}{.}
{246}{}{}
{247}{}{}
{248}{}{}
{249}{}{-Explosion-}

{250}{}{Continue the game.}
{251}{}{End the game.}
{252}{}{Are you sure you want to finish the game and lose the accumulated points (}
{253}{}{)?}
{254}{}{Go back and continue the game.}
{255}{}{Yes. Finish the game.}
{256}{}{You've lost!}
{257}{}{Stupid game! I won't play it anymore.}
{258}{}{Okay. I'll last longer next time.}
{259}{}{}

{260}{}{}
{261}{}{Refuse. I don't need any of these prizes.}
{262}{}{Power +1.}
{263}{}{Perception +1.}
{264}{}{Endurance +1.}
{265}{}{ Charisma +1.}
{266}{}{Intelligence +1.}
{267}{}{Dexterity +1.}
{268}{}{Luck +1.}
{269}{}{Gambling +20.}
{270}{}{"Victory! You have broken your own record. Would you like to continue?"}
{271}{}{Yes.}
{272}{}{No.}
{273}{}{Enable survival mode.}
{274}{}{Turn off survival mode.}
{275}{}{}
{276}{}{"Victory! You broke the record and became the absolute champion."}
{277}{}{Cool!}
{278}{}{Well, finally.}
{279}{}{"Take your prize coupon."}
{280}{}{"Now you can play this slot machine for free. And that's not all. If the game seemed too easy to you, then you can try the survival mode. Good luck in space!"}
{281}{}{Good.}
{282}{}{Come on?}
{283}{}{In survival mode, line transitions (up and down) count as a flight step. Therefore, you need to remember the state of affairs on the lines and think through your moves in advance.}
{284}{}{Read more.}
{285}{}{Clear.}
{286}{}{But you are given twice as many lives and volleys at the beginning, the path is viewed further by 2 steps, and an explosive volley destroys both the asteroid ahead and on neighboring lines.}
{287}{}{In addition, you get 1 point for each game step. You can exchange your points.}
{288}{}{}
{289}{}{}

{290}{}{Exchange points.}
{291}{}{You have }
{292}{}{ points.}
{293}{}{Continue the game.}
{294}{}{1 salvo for }
{295}{}{1 supervalp per }
{296}{}{1 life for }
{297}{}{.}
{298}{}{The right to explore paths before the next move for }