{102}{}{This emitter is de-energized.}
{103}{}{Now this emitter is useless.}
{104}{}{This emitter is badly damaged.}
{105}{}{You have managed to fix the problems. The emitter is ready for use again.}
{106}{}{The emitter is damaged!}
{107}{}{A powerful pulse goes into the ground and spreads around, causing damage to any electronics on the way.}
{108}{}{The emitter is damaged.}
{109}{}{The emitter is already charged.}
{110}{}{You are charging the radiator battery.}
{111}{}{This emitter burned out under its own voltage after the last use.}