{110}{}{Brute force is needed here.}
{111}{}{This valve is closed. You don't have enough strength to turn it even a couple of degrees.}
{112}{}{The blow on the pipe shook up the long-standing scum. Maybe now we can turn the damn valve.}
{113}{}{A little more!}
{114}{}{We need to make more efforts!}
{115}{}{The valve seems to have turned a fraction of an inch.}
{116}{}{It seems the valve is starting to give up under your hands.}
{117}{}{The valve is open.}
{118}{}{Uh-huh!}
{119}{}{Uv-f!}
{120}{}{Ar-rh!}