{100}{}{You see the substation computer.}
{101}{}{This is the control computer of the substation.}
{102}{}{The computer does not turn on.}
{103}{}{Probably, there is no energy coming here.}

{200}{}{The system is operating normally. Enter command.}
{201}{}{Leave the computer alone.}
{202}{}{The status of the power plant?}
{203}{}{The power plant is not responding.}
{204}{}{Substation status?}
{205}{}{The substation is not responding.}
{206}{}{Back.}
{207}{}{Turn on street lighting at the station.}
{208}{}{Street lighting is on.}
{209}{}{Turn on the internal lighting at the station.}
{210}{}{Interior lighting is on.}
{211}{}{Cancel the general siren.}
{212}{}{The general siren has been canceled.}
{213}{}{Cancel the alert mode.}
{214}{}{Attention! The combat readiness mode has been canceled. All security robots are ordered to adopt a peaceful program.}
{215}{}{Send repair robots to repair the monorail network.}
{216}{}{The power supply has been restored.}