{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Next.}
{204}{}{This system is too complicated for you.}
{205}{}{It would be nice to find the instructions... or an instructor.}
{206}{}{It won't help here. Knowledge is needed here.}
{207}{}{Now you know what to do.}
{208}{}{Hey, it's not that hard!}
{209}{}{This technology is too complicated. Here you need to study everything thoroughly.}

{210}{}{Checking the system status.}
{211}{}{The condition of the first turbine.}
{212}{}{Turbine 1: no signal.}
{213}{}{Turbine 1: active.}
{214}{}{Condition of the second turbine.}
{215}{}{Turbine 2: no signal.}
{216}{}{Turbine 2: active.}
{217}{}{Checking the substation.}
{218}{}{Substation: not responding. }
{219}{}{Substation: working. }
{220}{}{Direct energy to the substation.}
{221}{}{Completed.}
{222}{}{The substation is not responding.}
{223}{}{Turn on the lights in the engine room.}
{224}{}{Turn off the lights in the engine room.}
{225}{}{Turn on the lights in the control center.}
{226}{}{Turn off the lights in the control center.}
{227}{}{Open the door to the warehouse.}