{100}{}{Fuse switch.}
{101}{}{Judging by the instructions, this switch somehow participates in the transmission of current to the substation.}
{110}{}{You switch this lever, but nothing happens.}
{111}{}{Now there is no need for this.}
{112}{}{You release the switch. It responds with a long-drawn-out hum that goes into the depths of the premises.}
{113}{}{You lower the switch. The "CIRCUIT BREAK" signal lights up on the scoreboard next to it.}