{100}{}{A pick-up point for departure to Sonora has been announced here.}
{101}{}{From here you can return to the wasteland of Sonora.}

{110}{}{The collection point is here.}
{111}{}{[Wait for the guide and return to the Sonoran wasteland.]}
{112}{}{[To return to the Sonoran wasteland alone.]}
{113}{}{[Stay in the Glow of the Day. Sonora can wait.]}
{114}{}{Are you sure? You won't be coming back.}
{115}{}{Yes, I want to go back.}
{116}{}{No, I'm staying in the Glow.}
{117}{}{You can carry no more than 100 pounds of cargo with you.}
{118}{}{[Go to the Dayglow on your own.]}
{119}{}{[Stay in the Sonoran wasteland.]}