{100}{}{Now you can go down into the darkness.}
{101}{}{It's hard to say why there are no stairs here. But it's not there.}
{102}{}{You can't fix something that isn't there. This ladder needs to be replaced.}
{103}{}{There is a deep ventilation shaft behind the grate.}
{104}{}{There is nothing to fix here. On the contrary, a hole in the grid may be just right.}
{105}{}{This bridge is beyond repair. But you can get down from here if you tie a strong rope to the sleeper.}
{106}{}{Nothing can be done here with bare hands.}
{107}{}{Now you can go down.}
{108}{}{Here you can go down if you have a sufficiently long and strong rope.}