{100}{}{This is a publishing computer.}
{101}{}{This computer is connected to a printing press.}
{102}{}{Reading the articles of the last century gave you a new experience.}

#Dialog
{200}{}{Access has been obtained. Enter the command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Next.}
{204}{}{Go back to the main menu.}
{205}{}{Cancel.}

{210}{}{Read the headlines of recent articles.}
{211}{}{Articles for print.}
{212}{}{Business News.}
{213}{}{"Mexico has received a new batch of robots of the Mr. Assistant series. Recall that these robots have provided invaluable assistance after the last big earthquakes."}
{214}{}{Economic news.}
{215}{}{"The third economic miracle in Mexico. After the annexation, a huge number of American industries were located in Mexico. The ecology has deteriorated, but the country has started to get richer rapidly."}
{216}{}{Industry news.}
{217}{}{"Oil in the Kartes Sea is running out. Many oil platforms have already been closed. The remaining platforms will work for about ten years, pumping out the remnants of black gold."}
{218}{}{Expert opinion.}
{219}{}{"Is nuclear war threatening Mexico? We ask the experts."}
{220}{}{"Obviously, the United States will not threaten Mexico with nuclear weapons. But Mexico itself has other neighbors who sleep and see how to take over its resources and water space."}
{221}{}{"After the annexation, the States placed many factories and strategic facilities in Mexico. Obviously, the enemies of the United States will want to eliminate them in the event of war. And it will be a blow not so much to us as to the Mexicans."}
{222}{}{Police chronicles.}
{223}{}{"Mexico buys lightweight power armor from the United States for special operations on its land borders."}
{224}{}{Criminal reports.}
{225}{}{"A previously banned party sympathizing with China and the Soviet Union has been liquidated in Mexico City. There are casualties among the civilian population."}
{226}{}{Poster.}
{227}{}{"Don't miss it! This Sunday you will have an unforgettable performance by the legendary Mariachi band Jose Solis!"}