{110}{}{"there is some noise coming from the ventilation. idimo, so the agony of ventilation.}
{111}{}{This ventilation has finally subsided. Rest in peace, child of the Industrial Revolution.}
{112}{}{You have scraped a can of toxic ash from the ventilation.  The gratitude of the valve stopped making creepy noises.}
{120}{}{*sh-sh-sh*}
{121}{}{*Spÿk*}
{122}{}{*Òuk*}
{123}{}{*Òr-r-r*}
{124}{}{* rÿk*}