{100}{}{These doors cannot be locked.}
{101}{}{The monorail line is de-energized. The tram won't go anywhere.}
{102}{}{For some reason, the tram does not go by itself. Something must have broken.}
{103}{}{After almost a hundred years, the monorail has started working again!}
{104}{}{The monorail is working.}

{110}{}{"You are welcomed by the San Diego Metro Rapid Transit network. Sit back and wait for departure."}
{111}{}{[Leave the tram]}
{112}{}{[Get off at San Isidro Station]}
{113}{}{[Get off at Chula Vista Center Station]}
{114}{}{[Get off at Broadway Station]}
{115}{}{[Get off at the Old Town station]}