{100}{}{There is a substation in front of you.}
{101}{}{This is an electrical substation. The wires from it stretch towards the monorail.}
{102}{}{This is an electrical substation. You have no idea why you might need it.}
{103}{}{It seems that this is the very substation that should power the monorail.}
{104}{}{Electricity has already been sent to the monorail.}
{105}{}{Monorail power restored.}
{106}{}{This substation is dead. There is no electricity coming from the power plant.}
{106}{}{This substation is dead. There is no electricity coming from the power plant.}