{100}{}{This is Stanley.}
{101}{}{You see a terribly bony ghoul in a dirty, worn-out robe. A piece of rebar sticks out of his head.}
{102}{}{Hello, belyashik. You don't look like a real ghost anymore.}

{200}{}{A-a-a, don't take me, I still want to live!}
{201}{}{What are you talking about?}
{202}{}{What the hell are you yelling at?!}
{203}{}{Oh, Mommy, you're a human being?! Ugh, I thought you were a ghost. Why are you scaring me?}
{204}{}{I have the same question for you. You're walking around all black in the dark, only your eyes are glowing!}
{205}{}{Sorry, whitey, but I was so scared! You know, it's so lonely at these stations. But there were once rumors about a ghostly wagon that took people's souls to hell. It's silly to believe that now, of course. We're already in hell.}
{206}{}{I'm sorry, it was an accident. I didn't expect to meet anyone here either.}
{1206}{}{I'm sorry, it was an accident. I didn't expect to meet anyone here either.}
{207}{}{Once there were crowds of people at these stations. And now it's really deserted here. Probably, the ghost train has already taken everyone to hell. Don't you believe it? Well, look around — we're already in hell.}
{208}{}{So, what are you doing here anyway?}
{209}{}{My brothers asked me to prepare the Blue Line for launch. I used to work in the subway, so I can do something. But not everything.}
{210}{}{What do I need to run?}
{211}{}{First of all, we don't have any energy yet. And it seems that it can only be taken at the Bonita hydroelectric station, and it has been well guarded since the War. And it is necessary not only to start the station, but also to send it to the monorail substation.}
{212}{}{And secondly?}
{213}{}{Secondly, the monorail line needs to be repaired. Mr. Handys will do it for us when we start the power. To do this, they will disassemble some of the old lines. But the automation of the tram depot will have to be repaired by ourselves. And here I cannot do without an experienced electronics specialist. This thing is in the control room. Maybe a technician in San Ysidro will fix it, but it's damn heavy. Will you help me?}
{214}{}{Sure. After all, then I will be able to use the monorail.}
{215}{}{I'll do anything to make life easier for you guys.}
{216}{}{Wonderful! Help me, and I will share part of the fee that the city administration promised me.}
{217}{}{OK. See you again.}
{218}{}{Before I start, I'm going to ask you a few questions.}

{220}{}{What do you say, belyashik?}
{221}{}{What are you staring at, belyash?}
{1221}{}{What are you staring at, paleface?}
{222}{}{Hey, that's my pale-skinned brother! How are you?}
{1222}{}{Hey, it's my pale-skinned sister! Are you all right?}
{223}{}{For now. See you later.}

{230}{}{What is a monorail?}
{231}{}{You really don't know? That sucks! Once upon a time, elevated trains used to travel along these rails. And it was cool. Help me fix the line — then you will see it with your own eyes.}
{232}{}{I see.}
{233}{}{What should I do to start the tram?}
{234}{}{First you need to supply power to the substation of the Blue Line. And then fix the electronics in the control room. If you don't have the skills, then take the equipment to the technician in San Ysidro.}
{235}{}{Okay.}
{236}{}{Does that thing in your head bother you?}
{237}{}{Piece? Oh, you mean the fittings. She's been sticking out of this head for a hundred years. It's okay, I'm used to it. But it's better not to pull it out.}
{238}{}{Okay. Whatever you say.}
{239}{}{It's a miracle! To be honest, I thought it wouldn't work. It's so amazing that I can't even believe it. You bring back my hope for people. Maybe all is not lost for you yet.}
{240}{}{Uh, good.}
{241}{}{I'm not trying for you.}
{242}{}{Probably, I need to share the fee with you — 1000 caps. And thank you... friend.}
{1242}{}{I probably need to share the fee with you — 1000 caps. And thank you... a friend.}
{243}{}{You're welcome... friend.}
{244}{}{Probably, I need to share the fee with you — 1000 caps. And thank you... partner.}
{245}{}{You're welcome... partner.}
{246}{}{I probably need to share the fee with you — 500 caps. And thank you... partner.}
{247}{}{And that's it? You're not my "partner" anymore.}