{110}{}{In front of you is a printing press. Êonce he printed newspapers and magazines, but now he is inactive.}
{111}{}{in front of you is a printing press. he won't be able to print anything anymore because someone pulled an important part out of him.}
{112}{}{did he remove the printed circuit board.}
{113}{}{"there's nothing valuable here anymore.}
{114}{}{ at the moment, this printing press has not presentedIt's of no interest to you.}