{110}{}{This equipment is not working.}
{111}{}{This equipment is running at full capacity.}
{112}{}{s have replaced the damaged parts. The radio station is working again.}
{113}{}{This pathetic garbage will not be able to replace the destroyed parts.}
{114}{}{This radio station does not work.}
{115}{}{You can't even imagine how many problems this radio station will save us from. Thank you.}
{116}{}{NBSP teaching more than you, and he has less brains. Êucha would never have been able to fix it.}