{110}{}{This is an active radio station. It works thanks to you.}
{111}{}{This equipment is running at full capacity.}
{112}{}{This radio station is used by the undead to communicate with the rest of the Glow areas.}
{113}{}{This equipment does not need repair.}
{114}{}{You are giving the end signal to all San Isidro border patrol robots.}
{115}{}{You are transmitting data about a new transponder to a military base. Automation gives permission to disembark.}
{116}{}{There is no electricity.}