{110}{}{This radio station is still working.}
{111}{}{This radio station has not been working recently.}
{112}{}{This equipment does not need to be repaired. But it's useless without an antenna. Let him stand here for now.}
{113}{}{You have seized the amplifier and other parts needed in San Ysidro.}
{114}{}{The equipment of this radio station is in working condition. But the signal is not transmitted for some reason.}
{115}{}{Useless. This radio station has problems with signal transmission.}