{200}{}{The station is ready to work. Upload the work materials and assign a program for processing.}
{201}{}{Disable the station.}
{202}{}{Back.}
{203}{}{This weapon should be removed from the hands.}

{210}{}{Required materials: }
{211}{}{, }
{212}{}{.}
{213}{}{ Download the materials and start the program.}
{214}{}{The program has finished working. Take the product from the tray.}
{215}{}{Disable the station.}
{216}{}{Go back to the general list.}
{217}{}{Cancel and return to the general list.}
{218}{}{Not enough materials.}
{219}{}{Go back to the last section.}
{220}{}{Received: }
{221}{}{, }
{222}{}{ pcs.}
{223}{}{Repair section.}
{224}{}{Chemistry section.}
{225}{}{Section Ammunition.}
{226}{}{}

{250}{}{Homemade bottle caps.}
{251}{}{Homemade Radaway.}
{252}{}{Homemade Stimpack.}
{253}{}{Homemade antidote.}
{254}{}{Fuel for the flamethrower.}
{255}{}{Fire bomb.}
{256}{}{A pulse grenade.}

{260}{}{Recycle the salute into signal cartridges.}
{261}{}{Strengthen conventional signal cartridges to ur 1 (2 K 1).}
{262}{}{Strengthen conventional signal cartridges to ur 2 (3 K 1).}
{263}{}{Strengthen signal cartridges ur 1 to ur 2 (2 to 1).}
{264}{}{Convert a shotgun cartridge to a bullet cartridge.}
{265}{}{Convert a bullet cartridge to a shotgun.}

{270}{}{Clean the patrol badge from dirt.}
{271}{}{Replace the crystal in the laser pistol.}
{272}{}{Repair the monorail control module.}