{110}{}{These are torpedoes with a nuclear charge.}
{111}{}{It must be a damn powerful thing.}
{112}{}{These are torpedoes with a nuclear charge. And they are on alert. }
{113}{}{It's time to get out of here...}
{114}{}{Ho-ho, A bunch loves big explosions!}

{123}{}{You have activated the torpedo timer.}
{124}{}{You canceled the torpedo timer.}

{150}{}{Until the explosion left }
{151}{}{ seconds.}