{100}{}{This is a service computer.}
{101}{}{This computer is linked to the asylum database.}
{102}{}{Learning about the history of the asylum has enhanced your experience.}

#Dialog
{200}{}{Access has been obtained. Enter the command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Next.}
{204}{}{Go back to the main menu.}
{205}{}{Cancel.}

{210}{}{Read security reports.}
{211}{}{Select the reporting period.}
{212}{}{February 2131.}
{213}{}{"We have collected the data of the latest intelligence groups."}
{214}{}{"The Alpha group sent to the center of San Diego is not getting in touch. The last message spoke about the high level of radiation and large destruction of the urban environment."}
{215}{}{"Betta's group, who explored the piers, returned ahead of schedule, not even halfway there. High levels of radiation and large destruction are reported. All bridges to Coronado Island were destroyed, all military and civilian vessels on the piers were sunk or severely damaged. There is a high activity of robots along the coast, probably coming from a military base. The members of the group received radiation sickness."}
{216}{}{"The Gamma group, which explored the southern regions, returned with a small number of useful items and pre-war provisions. Moderate damage and increased radiation are reported."}
{217}{}{" The Delta group, which explored the eastern regions, reports a decrease in radiation inland and minor damage. Animals of unusual shapes or sizes have been found. Part of the group died."}
{218}{}{"None of the groups were able to find living people or traces of their recent stay."}
{219}{}{Go back to the general list.}
{220}{}{April 2131.}
{221}{}{"The Zeta group, sent to the West-Tech scientific complex, returned. Of the entire group, one person remained alive. The survivor reports an extremely high level of radiation and destruction in the complex. There are security robots and animals of unknown shape around the complex."}
{222}{}{" A medical examination showed that the scout was suffering from severe radiation sickness and unusual mutations, and his imminent death was expected. Further study of the West-Tech complex is not recommended."}
{223}{}{May 2132.}
{224}{}{"The Epsilon group has returned from Los Angeles. The Group reports on a series of small settlements and camps, the largest of which is called Aditum. It is inhabited by people who have survived the consequences of a nuclear war in various places in Southern California. These people survive by collecting pre-war items from the ruins and then trading."}
{225}{}{" It also became known about a large city called Hub north of Aditum, but there is very little information about it."}
{226}{}{"Scouts make contradictory conclusions about the local population. Part of the group is afraid of outsiders, part shows a desire to merge with them into one settlement. Probably, many scouts are experiencing culture shock."}