{110}{}{    }
{111}{}{Report, brother.}
{112}{}{They succeeded. The ghouls really started the power plant.}
{113}{}{What cretins! Now we have less time to prepare.}
{114}{}{So, can we seize the dam? It's not the case to leave such power to the dregs...}
{115}{}{No, it will only distract us from the main goal.}
{116}{}{Besides, the ghouls need the station for the city. It is unlikely that they use it to harm.}
{117}{}{We have to be proactive. We return to the base. We need to discuss everything.}