{100}{}{This cannot be done during combat.}
{101}{}{This item should be used out of hand.}
{102}{}{The walls of the cave are jamming the radio signal.}
{103}{}{Something is jamming the radio signal. These are probably ZAX's tricks.}

{210}{}{A slight static crackling sounds from the speaker.}
{211}{}{Listen to the general frequency.}
{212}{}{Listen to the frequency of Faber's mercenaries.}
{213}{}{Listen to the Ranger frequency.}
{214}{}{Listen to the frequency of fire worshippers.}
{215}{}{Listen to the frequency of the Phoenix Rebels.}
{216}{}{Listen to the frequency of tinkers.}
{217}{}{Listen to the frequency of the Brotherhood of Steel.}
{218}{}{Listen to the emergency frequency of the Vault 27.}
{219}{}{Turn it off.}

#Total frequency
{230}{}{You only hear "white noise".}
{231}{}{Leave.}
{232}{}{Apparently, I'm too far away from the negotiation zone on this frequency.}
{233}{}{Search for signals at all frequencies.}
{234}{}{...help! The jackals have trapped us, we urgently need help!}
{235}{}{I hear you. Where are you located?}
{236}{}{Damn it, finally! Listen, the Jackals have trapped us. We can't get out of here. Help us, we will not remain in debt. Here are the coordinates, north of Garage City... Be careful and bring more people... Damn, these creatures are already here... (the signal is gone)}
{237}{}{Hold on, stranger. Whoever you are.}
{238}{}{Hold on, Ranger. Help is on the way.}
{239}{}{I hear you. Commander Helford sent me to help. Where are you located?}

#Rangers
{240}{}{(You hear the boring patrolmen talking. Nothing interesting.)}
{241}{}{"...The last time we saw them in Garage City." - "They could have died on the way. Especially considering that there were children among the refugees." — "And what are they doing in Vegas?" - "I don't know. They say there are whole wars between clans and cannibalism flourishes. We should sort out our problems." — "That's right. So maybe it's a good thing they got lost in the desert. Fewer mouths to feed on the base." — "Make sure the civilians don't hear you." — "I know, I know..."}
{242}{}{"...the ration is already in the throat does not climb. When will they finally deliver normal meat to the base?" - "They say the problems have worsened in San Brahmin. Until the situation is resolved, be content with what you have." — "Damn, so the guts will knot..."}
{243}{}{*sh-sh-sh* "... and drove them into the ruins of Needles. The siege lasted three days until they gave up from hunger."— "Wow, three days in the sun is something." — "Yeah. But the bandits turned out to be naked. I couldn't take anything of value with me..."— * psh-sh*-"So, stop clogging up the ether! You will tell stories in the dining room."— *psh-shh* - "Whatever you say, I'm not used to refusing ladies." — *psh—shh* — "You'll make a joke, you wit, and I'll get your ration cut for a week."}
{244}{}{*sh-sh-sh*"...they're going on the road. What to do? Reception." — "Let them go. We don't need any extra trouble because of a few beggars."}
{245}{}{"...I'll send you to the mantises!" "Calm down, Sergeant. I will inform the guys to intercept the caravan and take the stolen goods. From now on, be more careful when communicating with unverified merchants."}
{246}{}{"...not enough provisions. I don't know if I should help them. We are also running out of rations." — "Then keep it for yourself. The nearest outpost is too far away, it's not worth the risk..."}
{247}{}{...there was one left, but he escaped into the wasteland."— "Let him run. I'll tell the nearest patrolmen, they'll intercept him." — "Thank you. But I'll catch up somehow."—"Ranger, don't try to chase him through the desert!"—"To hell with it, I'll do it anyway."—" (pause) As you know. But one more such trick, and I will inform the commander."}
{248}{}{* sh-sh-sh* — "Bravo Group, answer!" — *sh-sh*- "Bravo Group, answer!.. Damn it..."}
{249}{}{* sh-sh-sh*}

{250}{}{...I can't! Who could have done such a thing?! — The Rangers have many enemies. But if the dam was destroyed from the inside, it means that someone from their own did it. They say that before that, some newcomer was seen inside the dam. The guards were interrogated to the fullest extent. They won't see their badge anymore.}
{251}{}{...at the base, be sure to look in. This guy is a great mechanic. — I don't like messing with teenagers. The main thing is that he keeps an eye on the dam, otherwise old Rufus will soon die, and then what to do?}
{252}{}{...I noticed it too. What happened? — The signalmen seem to have hired some peasant to fix the antenna. Now the walkie-talkie works better and at a greater distance. "A peasant?" That's the twist. We should treat him to empty coffee when we meet.}
{253}{}{...that fugitive was caught after all. The bitch was hiding in the subway near the farmers on Route 95. "Right under your nose?" And we couldn't catch him for so long? — He was an excellent spy, we would like such. They say it wasn't even the Rangers who caught him, but some crook. — Well, at least some benefit from outsiders. — And don't say...}

{260}{}{Ranger }
{261}{}{ in touch. I'm in the desert near the base. I urgently need supplies support.}
{262}{}{*sh-sh-sh* Welcome, rookie. Do you know about the town of Quartz in the south? Find the ruins there in front of the bar. They have a descent into a secret cellar with our supplies. I hope this helps you.}
{263}{}{Thank you, Ranger.}
{264}{}{Search for the source of the relay of Ranger talks.}
{265}{}{You fail to capture this phenomenon. Apparently, the source is too far away.}
{266}{}{The source is still too far away. It is worth returning to the ranger base and moving away from it strictly to the east.}
{267}{}{It seems that you have detected the source of the radio echo! It remains to find him in the middle of the desert.}
{268}{}{Go to the place right now.}
{269}{}{}
{270}{}{Hey, Rangers, has anyone seen that legendary giant radscorpion?}
{271}{}{Welcome, rookie. He was last seen at these coordinates. Are you really going hunting? Be careful, it's better not to catch the eye of such a creature without a grenade launcher.}
{272}{}{[Go to the received coordinates]}
{273}{}{Roger that, Ranger. End of communication.}
{1273}{}{Roger that, Ranger. Out of touch.}
{274}{}{I'll take that into account. Before the connection.}

#Motel
{290}{}{Listen to all frequencies.}
{291}{}{You pick up a barely discernible signal for help.}
{292}{}{[Listen]}
{293}{}{[Ignore]}
{294}{}{...Somebody! Help! I'm in some old motel southwest of Phoenix. They've blocked all the exits, I can't escape. Please help...}
{295}{}{[Next]}
{296}{}{Everyone else has already died from the traps. I was left alone... Someone is coming... What do you need? Go away! Oh my God! Don't touch me, you freak! No! No need! A-a-a!}
{297}{}{An old motel to the southwest? Oh, it won't be an easy walk...}

#Vault 27
{300}{}{The emergency frequency transmits a distress signal.}
{301}{}{Obviously, I'm too far from the Vault. It's worth going back to Phoenix and trying different directions.}
{302}{}{It's pointless. I already know where the Vault is.}
{303}{}{The signal is amplified in that direction. I'll try to find out...}
{304}{}{The signal is getting stronger.}
{305}{}{There is! Looks like I found you.}
{1305}{}{There is! Looks like I found you.}
{306}{}{Go to the Vault 24.}

#Flagstaff
{310}{}{(You can hear the patrolmen talking. Nothing interesting, just the usual altercation.)}
{320}{}{All posts! We've been attacked! A whole crowd of savages! Reinforcements are needed! To everyone... A-a-a!}
{321}{}{Roger that. I'm sending a detachment from the garrison. Hold on...}
{322}{}{(Yes, empty the garrison, you idiot, that's all I need)}
{323}{}{Track the signal of the missing tinsmith.}
{324}{}{The signal is not traceable.}
{325}{}{Maybe I'm just too far away from him. We need to get back to the center of Casa Grande.}
{326}{}{You pick up the tinker's barely noticeable signal.}
{327}{}{Okay, great, he's in town somewhere. It seems the signal is coming from the east.}
{328}{}{The signal from the radio implant is clearly audible.}
{329}{}{So it's somewhere nearby. He or his body.}

#Inferno
{350}{}{Brotherhood of Steel Squad, respond. Can anyone hear me?}
{351}{}{(Only "white noise" is heard in response)}
{352}{}{I repeat. The Brotherhood of Steel squad, says a member of the rescue group. Answer.}
{353}{}{They don't seem to hear me. Hang up.}
{354}{}{This is Paladin Barkley... Glad to hear it, comrade. We are in a difficult situation. I am wounded, communication with the squad is lost. Requesting urgent assistance.}
{355}{}{Roger that. Where are you, Paladin Barkley?}
{1355}{}{I understand you. Where are you, Paladin Barkley?}
{356}{}{The point of dislocation... A manhole near a destroyed supermarket. There are a lot of mutants on the surface, be careful.}
{357}{}{Moving into position. Stay where you are. End of communication.}
{358}{}{Hey, can anyone hear me? Reception?}
{359}{}{(No one gets in touch)}
{360}{}{I repeat. Can anyone hear me? Are there still alive in this burial ground?}
{361}{}{Okay. Hang up.}
{362}{}{This is Barkley speaking... Yes, at least one is still alive here. Listen to me carefully, comrade. I'm injured, I need urgent help.}
{363}{}{Where are you, Barkley?}
{364}{}{The collector under the destroyed supermarket. Come straight to me, don't linger. And be careful, there are these mutants everywhere.}
{365}{}{Hold on, Barkley. I'm coming.}
{366}{}{Oh, mutants? It's bad.}

{370}{}{[Search for a signal]}
{371}{}{(You carefully examine the frequencies by turning the radio receiver in all directions of the world, until finally the sound comes from the speaker.)}
{372}{}{[Listen on]}
{373}{}{[Ignore]}
{374}{}{(old music is heard through the strong white noise)}
{375}{}{[Listen to music until the end]}
{376}{}{... Hey, traveler! Tired from the road? Was the desert exhausting on the way? Then wrap it up in the Hub!}
{377}{}{[Next]}
{378}{}{Here you will find everything you need for a holiday: bars, hotels, a huge market ... and, of course, the unforgettable Maltese Falcon cafe! In it you can relax and forget about the claws of death and bandits from the high road.}
{379}{}{You want to freshen up. We have stocks of Nuka-Cola! And for lovers of something hot, we will always pour a mug of the legendary Khab rum.}
{380}{}{Hey, what about slot machines? Oh, yes, baby, there are very few of them left in modern California. Don't miss this opportunity!}
{381}{}{And of course, our ladies will always TAKE CARE of dear customers who were too LONELY on the road. Check out the Maltese Falcon. The hub is waiting for you! (old music starts again)}
{382}{}{Eh, it's too far. Besides, I need to go in a completely different direction...}
{383}{}{You have gained experience for detecting a radio signal from California.}

{390}{}{[Listen on]}
{391}{}{"Brothers and sisters! This is Jerry the Knight. I'm under attack! The super mutants trapped me in an old cafe in National City. I'm hurt. I ask for immediate help!"}
{392}{}{I hasten to you, brothers. Hold the defense with all your might!}
{393}{}{Serves you right, ironheads! I hope no one will help you.}
{394}{}{Uh, some noise, I didn't hear anything, over.}
{1394}{}{Uh, some noise, I didn't hear anything, over.}
{395}{}{Hold on, I'll be there soon.}
{396}{}{The scribe is in touch }
{397}{}{The knight is in touch }
{398}{}{Paladin is in touch }
{399}{}{Scout is in touch }
{400}{}{. Can anyone hear me? I'm on the ruins of the Dayglow. I need help with supplies.}
{401}{}{The cadet is in touch }
{402}{}{Greetings, }
{403}{}{. This is Jerry from the intelligence unit. Get to Pier #9. I've stashed some supplies there. I hope they will help you.}
{404}{}{Thank you, Brother Jerry. End of communication.}
{405}{}{High radiation background on Coronado Island creates strong interference.}
{406}{}{Apparently, you need to leave the island to have a normal connection.}
{407}{}{The rock blocks the weak radio signal of your walkie-talkie.}
{408}{}{So we'll have to go back to the surface.}