###------- AMMUNITION
{100}{}{Nuclear battery}
{101}{}{A small autonomous unit of energy storage.}
{200}{}{Micro-core battery}
{201}{}{The average autonomous unit of energy storage.}
{300}{}{The cartridge .22}
{301}{}{Small-caliber unitary annular ignition cartridge.}
{400}{}{Cartridge 9 mm}
{401}{}{Pistol cartridge of ancient caliber.}
{500}{}{Cartridge 10 mm}
{501}{}{Pistol cartridge of widespread caliber.}
{600}{}{10 mm NSP cartridge}
{601}{}{Pistol cartridge with a dissected bullet made of nanostructured metal.}
{700}{}{Cartridge .44}
{701}{}{Revolver cartridge of increased power.}
{800}{}{The cartridge .50}
{801}{}{Large-caliber cartridge for especially cool pistols and revolvers.}
{900}{}{Cartridge 5 mm}
{901}{}{Cartridge for automatic weapons.}
{1000}{}{The cartridge .308}
{1001}{}{A rifle cartridge of an old but reliable caliber.}
{1100}{}{12 gauge cartridge}
{1101}{}{Shotgun cartridge loaded with shot.}
{1200}{}{Cartridge 12 cal. bullet}
{1201}{}{A shotgun cartridge loaded with a large bullet.}
{1300}{}{Grenade 40 mm}
{1301}{}{Ammunition for a hand grenade launcher.}
{1400}{}{Signal cartridge}
{1401}{}{A 4-caliber lighting cartridge for a signal pistol.}
{1500}{}{Signal cartridge}
{1501}{}{Modified 4-caliber cartridge for a signal pistol.}
{1600}{}{Signal cartridge}
{1601}{}{Reinforced 4-caliber cartridge for a signal pistol.}
{1700}{}{Universal container}
{1701}{}{A container for storing things for all occasions.}
###------- THROWING WEAPONS
{1800}{}{Rock}
{1801}{}{This is an ordinary rock, similar to granite. However, its shape is quite convenient for combat use (strengthening the blow or throwing). Min ST: 1.}
{1900}{}{Throwing knife}
{1901}{}{A knife of pre-war production, specially balanced for throwing. Made of titanium, with laser sharpening. Min ST: 2.}
{2000}{}{Fragmentation grenade}
{2001}{}{An ordinary fragmentation grenade. Contains a small amount of high explosive. Most of the dangerous fragments are formed directly from the shell of the grenade. Min ST: 3.}
{2100}{}{Plasma grenade}
{2101}{}{A grenade in which plasma sealed with magnetic fields is sealed. Detonates with an explosive, provoking an explosion of superheated plasma. Min ST: 4.}
{2200}{}{Pulse grenade}
{2201}{}{An electromagnetic pulse grenade that generates a powerful electromagnetic field during an explosion. Usually does not affect living beings. Min ST: 3.}
{2300}{}{A nuclear grenade}
{2301}{}{An improvised hand grenade assembled from a powerful nuclear projectile. In an explosion, it releases such an amount of energy that it can destroy a house. Min ST: 5.}
###------- AMMUNITION
{2400}{}{Jumpsuit}
{2401}{}{Cute tight-fitting jumpsuit from the Vault. This thing can be sold profitably on the market. Effects: +2 Reaction.}
{2500}{}{Leather jacket}
{2501}{}{Thick leather jacket of pre-war production.}
{2600}{}{Armored jacket}
{2601}{}{Thick leather jacket reinforced with thicker leather, steel sheets and shoulder pads.}
{2700}{}{Leather armor}
{2701}{}{A type of armor, elaborately made of brahmin leather. Only San Brahmin masters know the production technology.}
{2800}{}{Mantle}
{2801}{}{The Robe of the Followers of Fire. Made by secret technology with the use of special materials. Provides additional protection against radiation.}
{2900}{}{Mantle with bulletproof vest}
{2901}{}{The Robe of the Followers of Fire. Made by secret technology from special materials with additional protection from radiation. A light police bulletproof vest is discreetly hidden under the mantle.}
{3000}{}{Metal armor}
{3001}{}{Homemade armor, roughly made of polished metal plates. Provides excellent protection from bullets and blows, but burdens with heavy weight and clumsy shape.}
{3100}{}{Tesla Armor}
{3101}{}{This shiny armor provides excellent protection against energy attacks. Three electromagnetic Tesla traps partially dissipate directed energy shocks.}
{3200}{}{Combat armor}
{3201}{}{High-tech armor made of improved protective polymers.}
{3300}{}{Brotherhood Battle Armor}
{3301}{}{An improved version of combat armor. The Brotherhood of Steel has made many improvements to the standard version.}
{3400}{}{Power armor}
{3401}{}{High-tech autonomous armor T51b. This instance is partially damaged.}
{3500}{}{Power armor}
{3501}{}{High-tech autonomous armor T51b. Powered by a nuclear microreactor with a fuel reserve of a hundred years.}
{3600}{}{Road armor}
{3601}{}{An old leather jacket, tightly reinforced with road signs. Such jackets are not rarely worn by highway robbers.}
{3700}{}{Ranger's Duster}
{3701}{}{A type of armor, elaborately crafted from brahmin leather by order of the Rangers. Only San Brahmin masters know the production technology.}
###------- DIFFERENT THINGS
{3800}{}{Nuclear block}
{3801}{}{A unit for storing a large amount of energy. This is a common power supply for a small vehicle and some equipment.}
{3900}{}{!Do not use}
{3901}{}{In the original - a micro-core battery.}
{4000}{}{Stimpack}
{4001}{}{A medicinal substance that was widely used in the pre-war period. When injected, it provides rapid healing of small wounds. Effects: +(20-30) health.}
{4100}{}{Bottle caps}
{4101}{}{Your bottle caps are in this bag. Recently, they have been used in large settlements to exchange for goods.}
{4200}{}{Pre-war money}
{4201}{}{A means of payment that has long been out of use. However, some inhabitants of the Wastelands can still use it.}
{4300}{}{Casino Chips}
{4301}{}{These chips are used in the casino as the local currency. If you didn't know this, you would consider them a child's toy from the pre-war era.}
{4400}{}{Soldier's badge}
{4401}{}{On this worn badge, you can distinguish the name of the soldier and his identification number.}
{4500}{}{Pocket trash}
{4501}{}{Useless trash from your pocket. If you found it, then you are very unlucky.}
{4600}{}{Token}
{4601}{}{This token is used as its owner pleases.}
{4700}{}{!Do not use}
{4701}{}{In the original - First aid kit.}
{4800}{}{Radaway}
{4801}{}{A chemical solution whose molecules bind radioactive particles and remove them from the body. It can be addictive. Effects: -(100-150) rad.}
{4900}{}{The antidote}
{4901}{}{Several ampoules from an army first aid kit containing various potent antitoxins. These drugs are used to neutralize animal poison and its consequences. A harness is also attached. Effects: -(45-60) poisoning.}
{5000}{}{Doctor's briefcase}
{5001}{}{This briefcase contains substances and instruments for providing surgical care in the field.}
{5100}{}{!Do not use}
{5101}{}{In the original - Dynamite.}
{5200}{}{Geiger Counter}
{5201}{}{Geiger counter from Watts Electronics. Records the presence and power of radiation fields.}
{5300}{}{Mentats}
{5301}{}{Pills made of a chemical substance that expands consciousness. Improves brain functions related to memory, and also accelerates some mental processes. It can be addictive. Effects: +2 IN, +2 VS, +1 HR.}
{5400}{}{Stealth combat}
{5401}{}{Personal camouflage device "Invisible 3001" from the company Timidly. Generates a modulating field that transmits reflected light from one side of the object to the opposite. Effects: Stealth +20.}
{5500}{}{Walkie-talkie}
{5501}{}{The current walkie-talkie model 2043B from the wonderful company Watts Electronics. Reliable, durable, and camouflaged.}
{5600}{}{The Iguana Trap}
{5601}{}{A homemade device for catching desert lizards.}
{5700}{}{Breastplate}
{5701}{}{A pair of metal caps, worn on the shoulders with the help of old belts. In the absence of normal armor, even this can save a life. Or not.}
{5800}{}{Spikes}
{5801}{}{The spiked whip is a weapon of truly predatory plants.}
{5900}{}{Motion sensor}
{5901}{}{Watts Electronics motion sensor, "V-DOCK" model. Captures the movement of large objects at a distance of several yards using a small radar.}
###------- PROVISIONS
{6000}{}{Iguana-on-a-stick}
{6001}{}{A desert iguana, fried right with the skin on the fire. Tasteless and unpalatable. In addition, you do not have confidence that she lived in an environmentally friendly environment. Effects: +2 health.}
{6100}{}{Mutfruit}
{6101}{}{An unusual fruit. Without preservatives and dyes. Effects: +3 health.}
{6200}{}{Dried meat}
{6201}{}{These dried and smoked pieces of meat remain edible and even to some extent nutritious for many, many, many years... Effects: +4 health.}
{6300}{}{Pre-war noodles}
{6301}{}{Canned pasta of a brand widely known before the War. Oddly enough, they can still be eaten. Effects: +7 health.}
{6400}{}{Teleuzhin}
{6401}{}{Frozen pre-war semi-finished product. You can't say for sure what it means, but it doesn't look as attractive as it used to. Effects: +10 health, +5 speed/isc.}
{6500}{}{Larvae}
{6501}{}{Huge larvae of fly-like insects, bred inside the corpse. For a Wasteland dweller, this is a real protein feast. Effects: +2 health.}
{6600}{}{Brahmin fries}
{6601}{}{These fries are cooked according to a special recipe. In addition to the obvious brahmin scar, there may be... anything. Effects: +5 health, +5 reaction.}
{6700}{}{Rat soup}
{6701}{}{A wonderful dish of sewer rat and unidentifiable additives. A little bit of everything. Effects: +6 health.}
{6800}{}{IRP}
{6801}{}{Individual food ration for a fighter of the Brotherhood of Steel. Other inhabitants of Sonora can only dream of such a ration. Effects: +12 health, +10 speed/isc.}
{6900}{}{A rotten dish}
{6901}{}{A plate with a long-rotten meat dish. It is hardly possible to find a use for this, but you can try. Effects: +(5-15) poisoning.}
{7000}{}{Fried cockroach}
{7001}{}{Fire-roasted cockroach with a pinch of sea salt. Mmm, how crunchy! Effects: +2 health.}
{7100}{}{Chips}
{7101}{}{A box with the inscription "Frito Bandito". To your surprise, there are some old corn chips inside. Effects: +5 health.}
{7200}{}{Ammunition of black prospectors}
{7201}{}{A thick leather jacket of pre-war production, reinforced for exploring the ruins of The Glow. The homemade lining is made of foil and synthetic fabric to protect against radiation.}
###------- TOOLS
{7300}{}{!Book-reserve}
{7301}{}{Do not use (Big Book of Science).}
{7400}{}{Master key}
{7401}{}{An improvised lock pick for cracking classic mechanical locks. Do not count on a long service life.}
{7500}{}{Decoder}
{7501}{}{A powerful calculator for hacking electronic systems. The charge is barely enough for one long operation.}
{7600}{}{!Book-reserve}
{7601}{}{Do not use (Electronics).}
{7700}{}{Gas mask}
{7701}{}{An old ruined gas mask of a civilian model. It may still serve you for some time.}
{7800}{}{Tinker's Glasses}
{7801}{}{Glasses with electronics made by Two-Sun tinsmiths. Equipped with a night vision device, interchangeable lenses, and various sensors. The battery lasts for 10 minutes.}
{7900}{}{Flash}
{7901}{}{This signal flash gives illumination for a short time. The paper is somewhat frayed, but otherwise, everything is fine. To turn it on, turn the top part.}
{8000}{}{!Book-reserve}
{8001}{}{Do not use (First Aid, First Aid Book).}
{8100}{}{Boots}
{8101}{}{A pair of old but sturdy rubber boots. Judging by their appearance, they can withstand slush, at least for a while.}
{8200}{}{Shovel}
{8201}{}{This is an ordinary shovel for digging the ground. Take care of her.}
{8300}{}{Rope}
{8301}{}{Strong thick rope. Approximately 40 feet long.}
{8400}{}{Lighter}
{8401}{}{Silver gas lighter. In good condition.}
{8500}{}{Explosives}
{8501}{}{Plastic explosives of the military brand Cordex. Very stable, very powerful. Equipped with a timer.}
{8600}{}{!Book-reserve}
{8601}{}{Do not use (Scout's Handbook).}
{8700}{}{Buffout}
{8701}{}{Powerful steroids. Their effect is to increase strength and sharpen reflexes. They are highly addictive. Effects: +2 SL, +2 LV, +3 VN.}
{8800}{}{Scrap metal}
{8801}{}{Valuable parts from mechanical equipment. They can be useful in repairs or for a profitable exchange.}
{8900}{}{Electronics parts}
{8901}{}{Various parts from electronic equipment: capacitors, cathode lamps, inductors and much more. All this can be useful in repairs or for a profitable exchange.}
{9000}{}{Combustible mixture}
{9001}{}{A bottle with a mixture of various combustible substances. A relatively valuable resource in post-nuclear conditions.}
{9100}{}{!Do not use}
{9101}{}{In the original - a doctor's briefcase.}
{9200}{}{The poisonous gland}
{9201}{}{A fragment of the tail of a radscorpion, which contains some meat... and iron with a strong poison.}
{9300}{}{Trinity}
{9301}{}{A mineral formed from sand at the epicenter of a nuclear explosion. Nothing at first glance remarkable, but deadly with its radioactivity, an object.}
{9400}{}{The surviving book}
{9401}{}{One of the few surviving books of the pre-war era. Most will consider it a means to light a fire and only a few will see the most valuable source of ancient knowledge.}
{9500}{}{Maize flour}
{9501}{}{A valuable dietary product of modern production. Contains some small debris.}
{9600}{}{Cleaning agent}
{9601}{}{Petrified powder for removing sewage. Washes even the dirt of a century ago.}
{9700}{}{Wet wipes}
{9701}{}{Sealed packaging with sanitary napkins. They replace a bath during wanderings through the Wastelands.}
{9800}{}{Wasteland gum}
{9801}{}{Mature leaves of a rare wasteland plant. Many travelers appreciate them as a rich source of trace elements, and city dwellers - as a way to have fun.}
{9900}{}{Coffee}
{9901}{}{This jar contains some kind of "coffee beans". Apparently, this is a barely surviving product of the Old World.}
{10000}{}{Sandals made of tires}
{10001}{}{A pair of homemade sandals made from old tires. Better than nothing.}
{10100}{}{Ceramics}
{10101}{}{A simple vessel made of clay. Such things are appreciated in many settlements.}
{10200}{}{!Book-reserve}
{10201}{}{Do not use (Weapons and ammunition).}
{10300}{}{Cattle Breeders' Battle Shield}
{10301}{}{Part of the ammunition of local tribes. Includes a wooden shield and a leather cape.}
{10400}{}{NMR Combat Armor}
{10401}{}{High-tech pre-war armor with the distinctive signs of the New Mexican Republic.}
{10500}{}{Hiking flask}
{10501}{}{This flask is a gift from the residents of the Vault. It will make it easier for you to travel through the arid barren desert.}
{10600}{}{Nuka-cola}
{10601}{}{A bottle with a popular pre-War flavored soft drink. Warm and exhausted. Effects: +(3-5) health.}
{10700}{}{Irradiated Nuka-cola}
{10701}{}{A wonderful pre-war drink in a slightly dirty bottle. It has a wonderful taste and a very dubious glow in the dark. Effects: +(3-5) health, +3 rad.}
{10800}{}{Purified water}
{10801}{}{This vessel contains life-giving drinking water, purified from sewage and radiation. It should be used very sparingly, especially when traveling. Effects: +(7-10) health.}
{10900}{}{Rad-X}
{10901}{}{An anti-radiation drug that must be taken before irradiation. It does not cause side effects. Effects: +25 sopr.rad.}
{11000}{}{Psycho}
{11001}{}{Packaging with unusual and unknown drugs is most likely of military origin. The intended action is to increase the combat potential of a soldier. It may be highly addictive. Effects: +3 LV, -3 IN, +25 sopr.damage.}
{11100}{}{Rad-precipitation}
{11101}{}{Toxic concentrated ash formed after a nuclear explosion. Throwing this stuff in the face of the enemy, you can calmly watch as his eyes flow down his cheeks into his mouth. Effects: -2 VS, -5 reaction, -3 OD.}
{11200}{}{Empty syringe}
{11201}{}{This is a sterile empty hypodermic syringe. A rare and valuable item for modern medicine.}
{11300}{}{Knight's Badge}
{11301}{}{On this token, you can distinguish the name and identification number.}
{11400}{}{Squire's token}
{11401}{}{On this token, you can distinguish between a name and an identification number.}
{11500}{}{Mexico's Power Armor}
{11501}{}{Autonomous armor, upgraded for the needs of the Mexican Navy. Differs from the original model by reduced characteristics and lower weight.}
{11600}{}{Acid spit}
{11601}{}{A portion of strong acid.}
{11700}{}{Ghoul Battle Armor}
{11701}{}{Damaged combat armor. Some parts of it have been replaced with improvised items.}
{11800}{}{Dixon Machine gun}
{11801}{}{Machine gun designed for firing from the side of a sea vessel. Min ST: 7.}
{11900}{}{Shock Spear}
{11901}{}{Homemade weapon that emits an electric current when in contact with the victim. Min ST: 3.}
###------- ALCOHOL
{12000}{}{Pre-war beer}
{12001}{}{A can of pre-war beer. Local production. Effects: -1 SUN.}
{12100}{}{Syrup}
{12101}{}{Syrup obtained from the juice of "fire agave". Despite the terrible stench and burning taste, it contains a large amount of fructose and sugar.}
{12200}{}{Swill}
{12201}{}{Diluted low-quality alcoholic beverage. Its composition and origin can no longer be determined. Effects: -1 VS, -1 IN.}
{12300}{}{Pre-war whiskey}
{12301}{}{A strong alcoholic drink of the brand "Atomic whiskey". It is highly valued in the modern world compared to other types of alcohol. Effects: -1 SUN, +1 XP.}
{12400}{}{Homemade beer}
{12401}{}{One of the few beers of post-war production. Effects: -1 SUN.}
{12500}{}{Wasteland Tequila}
{12501}{}{A moonshine alcoholic drink from Phoenix of very dubious quality. There seems to be a little worm floating in the bottle. Effects: -1 SUN.}
###------- WEAPONS
{12600}{}{Brass Knuckles}
{12601}{}{Durable brass knuckles made of brass. Protects the hand and strengthens the blow in hand-to-hand combat. Min ST: 1.}
{12700}{}{Studded brass Knuckles}
{12701}{}{One of the varieties of the classic brass knuckles. Deals more damage due to its spikes, which pierce the enemy's flesh during the strike. Min ST: 1.}
{12800}{}{Claws}
{12801}{}{Homemade melee weapons. It consists of two old blades connected by bolts with an armband frame. Min ST: 1.}
{12900}{}{Pneumoculac}
{12901}{}{Homemade mechanical brass knuckles. During the blow, it forcefully throws forward sharp spikes that pierce the victim's body. Min ST: 1.}
{13000}{}{Shock glove}
{13001}{}{Modified police taser. Upon contact with the victim's body, this weapon transmits a powerful charge of electricity to him, and an old rubber glove protects the wearer from electric shock. Min ST: 1.}
{13100}{}{Power Fist}
{13101}{}{Power brass knuckles "Big ram" produced by the company "BitKo". Most consider it the best weapon for hand-to-hand combat. The rest are just afraid of him. Min ST: 1.}
{13200}{}{Knife}
{13201}{}{Sharp piercing and cutting weapons. Min ST: 1.}
{13300}{}{Combat Knife}
{13301}{}{High-quality combat knife model "Stallona" manufactured by the corporation "Wit". Its blade is guaranteed to remain as sharp even after ten years of use! Min ST: 1.}
{13400}{}{Impact knife}
{13401}{}{A large knife with a double-edged blade. Still surprisingly sharp. Min ST: 1.}
{13500}{}{The Ripper}
{13501}{}{Vibroknife brand "Ripper". Powered by a battery cell, the serrated blade easily tears the victim's flesh. Min ST: 1.}
{13600}{}{Power screwdriver}
{13601}{}{A working tool for cutting solid material. Breaks molecular bonds with powerful radiation. Powered by a battery on the belt. Min ST: 1.}
{13700}{}{Spear}
{13701}{}{Homemade pointed weapons. A blade from an old knife is impaled on a wooden shaft. Min ST: 4.}
{13800}{}{Pneumocopier}
{13801}{}{A peculiar invention of local engineers. Upon impact, the pneumatic system abruptly throws a sharp metal spike into the victim, and then with the help of a spring returns it to its place. Min ST: 4.}
{13900}{}{Electrocopier}
{13901}{}{An effective police tool for dispersing a crowd of troublemakers. It was repeatedly used even before the Great War. Min ST: 4.}
{14000}{}{ Baton}
{14001}{}{Non-lethal melee weapons made of rubber and steel, previously used by law enforcement forces. Min ST: 3.}
{14100}{}{Crowbar}
{14101}{}{A durable heavy tool designed for dismantling structures. Or for a good blow to the head. Min ST: 3.}
{14200}{}{The chase}
{14201}{}{Electric whip manufactured by Watts Electronics. The "Farmer's Best Friend" model. Power is provided by nuclear batteries. Min ST: 3.}
{14300}{}{Enhanced chase}
{14301}{}{Electric whip manufactured by Watts Electronics. The "Farmer's Best Friend" model. Thanks to modifications, this instance has become much more powerful. Min ST: 3.}
{14400}{}{Superstimpack}
{14401}{}{A powerful stimulant for emergency care. Briefly causes severe weakness due to the active chemicals in the composition of the drug, and after a while causes minor damage to blood vessels. Effects: +75 Health, -1 Strength.}
{14500}{}{Sledgehammer}
{14501}{}{A large hammer with a massive handle. A popular weapon among muscular types. Min ST: 6.}
{14600}{}{Hammer}
{14601}{}{Balanced lightweight hammer with increased maneuverability. And although they used to crush bricks with it, now there will be a more relevant use for it. Min ST: 5.}
{14700}{}{Supercoach}
{14701}{}{Weapons produced by the Brotherhood of Steel using the most modern technologies. Equipped with a kinetic energy storage device to enhance the impact. Min ST: 5.}
{14800}{}{An old revolver}
{14801}{}{Ancient civilian weapons. Like all revolvers, it is valued for its simplicity and reliability. Min ST: 4.}
{14900}{}{Police revolver}
{14901}{}{A reliable revolver from S&W, popular at the time among police officers and highway patrolmen. Min ST: 4.}
{15000}{}{Combat revolver}
{15001}{}{A great revolver. A favorite weapon of collectors and pretentious types. It's yours now. Min ST: 5.}
{15100}{}{Rocket launcher}
{15101}{}{A pistol for firing a flare. Although it is difficult to call it a weapon, at the right moment it is able to put the enemy to flight (especially in the presence of skillfully modified cartridges). Min ST: 3.}
{15200}{}{Submachine gun .22}
{15201}{}{Sports weapons of a bygone era. Now its main purpose is to shoot iguanas and scare away hooligans. Min ST: 3.}
{15300}{}{10 mm pistol}
{15301}{}{Self-loading pistol Colt 6520 caliber 10 mm. Each time you pull the trigger, the weapon automatically reloads until the magazine is empty. Min ST: 3.}
{15400}{}{Submachine gun 10 mm}
{15401}{}{H&K MP9 submachine gun, 10 mm caliber model. Compact weapon with the possibility of a single shot and firing bursts. Min ST: 4.}
{15500}{}{Mexican PP}
{15501}{}{The HM-23 submachine gun, developed by Mendoza CA. It was adopted by the Mexican police and proved itself well during the border riots before the Great War. Min ST: 4.}
{15600}{}{Gun.50}
{15601}{}{SIG-Sauer automatic pistol. Requires special handling skills due to the huge force of the shot and the high noise level. Min ST: 5.}
{15700}{}{Hunting rifle}
{15701}{}{Colt Rangemaster semi-automatic rifle. Outdated, but reliable. Min ST: 5.}
{15800}{}{Combat rifle}
{15801}{}{An American semi-automatic rifle of the AR series, formerly in service with the United States and Mexico. Convenient and reliable. Min ST: 5.}
{15900}{}{Fire Bomb}
{15901}{}{A bottle of flammable liquid. This is not often seen in the modern world. Min ST: 4.}
{16000}{}{Sniper rifle}
{16001}{}{DKS-501 rifle, converted to 0.308 caliber. Excellent long-range firearm. Min ST: 6.}
{16100}{}{Assault rifle}
{16101}{}{AK-112 assault rifle. An old army model that went out of use around the time of the last war. Can produce single shots and fire a burst. Min ST: 5.}
{16200}{}{Hand machine gun}
{16201}{}{Mendoza C-2075 machine gun, 5 mm caliber model. After the aggravation of relations with the United States, Mexico resumed the development of its own weapons, and this is one of them. Min ST: 6.}
{16300}{}{Minigun}
{16301}{}{Portable minigun Rockwell CZ53. A multi-barrel machine gun firing 5 mm rounds at an incredible speed. Min ST: 8.}
{16400}{}{Shotgun}
{16401}{}{Winchester "Widowmaker" is a double-barreled shotgun of 12 caliber. Short-barreled, with a trimmed mahogany butt. Min ST: 6.}
{16500}{}{Combat shotgun}
{16501}{}{Combat shotgun Winchester "City Killer", in good condition. It comes with a "Desert War" sealant that increases the reliability of weapons. Min ST: 6.}
{16600}{}{Assault shotgun}
{16601}{}{Melee assault weapon. The "bullpup" design provides a small size and ease of handling. Min ST: 6.}
{16700}{}{Grenade launcher 40 mm}
{16701}{}{Hand grenade launcher for 40 mm shells. Developed by the company "Rockwell". Min ST: 6.}
{16800}{}{Laser weapons}
{16801}{}{Homemade weapons created from parts of an industrial robot. Emits a low-power laser beam at a short distance. Min ST: 3.}
{16900}{}{Laser gun}
{16901}{}{Watts 1000 laser pistol, civilian model. Power is reduced compared to military and police models. Mines. strength: 3.}
{17000}{}{Laser rifle}
{17001}{}{Watts 2000 laser rifle. The use of crystals allows you to increase the power of weapons. Min ST: 4.}
{17100}{}{Plasma gun}
{17101}{}{The Glock 86 plasma pistol was developed by Gaston Glock's AI. Shoots a small charge of plasma heated to the limit. Min ST: 3.}
{17200}{}{Plasma rifle}
{17201}{}{The Winchester P94 plasma rifle is an energy weapon of the industrial era, firing plasma heated to the limit through a superconducting barrel. Min ST: 4.}
{17300}{}{Emitter}
{17301}{}{A unique weapon based on ultra-high-frequency radiation. Some parts are borrowed from industrial machinery. Min ST: 4.}
{17400}{}{Koa}
{17401}{}{Professional tool for cutting and processing fire agave. Made quite recently. Min ST: 4.}
{17500}{}{Pugach}
{17501}{}{A homemade pistol with a camera for one cartridge. Oddly enough, they can cause a serious wound to the enemy if it does not explode in the hands before. Min ST: 3.}
{17600}{}{Hunting rifle}
{17601}{}{Semi-automatic Colt Rangemaster rifle equipped with a 10x sniper scope. Min ST: 5.}
{17700}{}{Submachine gun .22}
{17701}{}{Sports weapons of a bygone era. Now its main purpose is to shoot iguanas and scare away hooligans. Min ST: 3.}
{17800}{}{Grenade launcher 40 mm}
{17801}{}{Hand grenade launcher for 40 mm shells. Developed by the company "Rockwell". Min ST: 6.}
{17900}{}{Winchester}
{17901}{}{A 2073 Winchester rifle with a lever-action platoon and a tubular magazine. One of the latest models. Min ST: 5.}
{18000}{}{Mop}
{18001}{}{It's a rope mop. She is. Min ST: 1.}
{18100}{}{Pistol .22}
{18101}{}{A simple and very reliable small-caliber pistol. Developed by the Mexican company "Armas Trejo". Min ST: 2.}
{18200}{}{Assault rifle}
{18201}{}{AK-112 assault rifle. An old army model that went out of use around the time of the last war. Equipped with a fairly roomy store. Min ST: 6.}
{18300}{}{Rail gun}
{18301}{}{This weapon uses the power of electromagnetism to shoot metal objects. Min ST: 7.}
{18400}{}{Flamethrower}
{18401}{}{Flamethrower model Torch-450. Shoots short jets of burning fuel. Min ST: 6.}
{18500}{}{Flamethrower fuel}
{18501}{}{A container with flammable liquid fuel.}
{18600}{}{Tehada Machine Gun}
{18601}{}{You carefully inspect this old weapon, then with a cry of "Viva Tejada!" you rush into the attack. Min ST: 6.}
{18700}{}{Blaster}
{18701}{}{This weapon looks like something out of an old science fiction movie. Shoots a beam of particles accelerated to near-light speeds. Min ST: 3.}
{18800}{}{Gatling laser}
{18801}{}{Gatling laser H&K L30. At the beginning of the war, it was a prototype. Thanks to several barrels, overheating can be avoided for some time. The power supply is carried out with the help of nuclear microreactors. Min ST: 7.}
{18900}{}{Turret gun}
{18901}{}{Twin plasma cannon for the turret.}
{19000}{}{Battle axe}
{19001}{}{An old camp hatchet. Can be used in combat. Min ST: 3.}
{19100}{}{Turboplasma rifle}
{19101}{}{The Winchester P94 plasma rifle is an energy weapon of the industrial era, firing plasma heated to the limit. Thanks to the modernization, heating is faster. Min ST: 4.}
###------- CONTAINERS
{19200}{}{Army Box}
{19201}{}{Shock-resistant metal ammunition box.}
{19300}{}{Product box}
{19301}{}{Such a box is usually used by merchants to store their goods.}
{19400}{}{The Iguana Trap}
{19401}{}{A homemade device for catching desert lizards.}
{19500}{}{Dog's Grave}
{19501}{}{This land was hastily dug up. A few bones and scraps of wool stick out of it.}
{19600}{}{Freshly dug earth}
{19601}{}{This land was recently dug up. Perhaps a treasure was buried there. Or a corpse.}
{19700}{}{Garbage heap}
{19701}{}{A small pile with various garbage.}
{19800}{}{Receiving parcels}
{19801}{}{Parcels from other cities are stored here.}
{19900}{}{Sending a parcel}
{19901}{}{Parcels to other cities are stored here.}
{20000}{}{Package to Flagstaff}
{20001}{}{A box with things for shipment to another city.}
{20100}{}{Package to Phoenix}
{20101}{}{A box with things for shipment to another city.}
{20200}{}{Package to Two-Sun}
{20201}{}{A box with things for shipment to another city.}
{20300}{}{Freshly dug earth}
{20301}{}{This land was recently dug up. Perhaps a treasure was buried there. Or a corpse.}
{20400}{}{Mailbox}
{20401}{}{A built-up wooden box. To look inside, you will have to disassemble the boards.}
{20500}{}{Flash}
{20501}{}{This signal flash gives illumination for a short time. The paper is somewhat frayed, but otherwise, everything is fine.}
{20600}{}{!Do not use}
{20601}{}{In the original - Dynamite.}
{20700}{}{Geiger Counter}
{20701}{}{Geiger counter from Watts Electronics. Records the presence and power of radiation fields. Currently enabled.}
{20800}{}{Motion sensor}
{20801}{}{Watts Electronics motion sensor, "V-DOCK" model. Captures the movement of large objects at a distance of several yards using a small radar. Currently enabled.}
{20900}{}{Explosives}
{20901}{}{Plastic explosives of the military brand Cordex. Very stable, very powerful. Equipped with a timer that is currently activated.}
{21000}{}{Stealth combat}
{21001}{}{Personal camouflage device "Invisible 3001" from the company Timidly. Generates a modulating field that transmits reflected light from one side of the object to the opposite. Enabled.}
{21100}{}{Grave}
{21101}{}{}
{21200}{}{Grave}
{21201}{}{}
{21300}{}{Grave}
{21301}{}{}
{21400}{}{Grave}
{21401}{}{}
{21500}{}{Grave}
{21501}{}{}
{21600}{}{Grave}
{21601}{}{}
{21700}{}{Grave}
{21701}{}{}
{21800}{}{Bones}
{21801}{}{A few human bones.}
{21900}{}{Cart}
{21901}{}{A caravan wagon converted from the body of an ancient car.}
{22000}{}{Cart}
{22001}{}{A caravan wagon converted from the body of an ancient car.}
{22100}{}{Pot}
{22101}{}{A large pot for storing crops or water.}
{22200}{}{Pot}
{22201}{}{An artfully made clay pot.}
{22300}{}{Pot}
{22301}{}{An artfully made clay pot.}
{22400}{}{Box}
{22401}{}{A wooden box filled with various things.}
{22500}{}{Things}
{22501}{}{A variety of objects that can be called in one word "things".}
{22600}{}{Things}
{22601}{}{A variety of objects that can be called in one word "things".}
{22700}{}{Things}
{22701}{}{A variety of objects that can be called in one word "things".}
{22800}{}{Things}
{22801}{}{A variety of objects that can be called in one word "things".}
{22900}{}{Safe}
{22901}{}{A small safe bolted to a metal table.}
{23000}{}{Chest}
{23001}{}{Homemade wooden chest.}
{23100}{}{Chest}
{23101}{}{Homemade wooden chest.}
{23200}{}{Shelves}
{23201}{}{A wooden shelf with various objects on it.}
{23300}{}{Shelves}
{23301}{}{A wooden shelf with various objects on it.}
{23400}{}{Shelving}
{23401}{}{A large wooden shelving with dusty things on the shelves.}
{23500}{}{Shelving}
{23501}{}{A large wooden shelving with dusty things on the shelves.}
{23600}{}{Shelving}
{23601}{}{A large wooden shelving with dusty things on the shelves.}
{23700}{}{Shelving}
{23701}{}{A large wooden shelving with dusty things on the shelves.}
{23800}{}{Shelving}
{23801}{}{A large wooden shelving with dusty things on the shelves.}
{23900}{}{Shelving}
{23901}{}{A large wooden shelving with dusty things on the shelves.}
{24000}{}{Trash can}
{24001}{}{It's a trash can. You can barely make out the inscription on it: "Keep the streets of your city clean!"}
{24100}{}{Refrigerator}
{24101}{}{It's a refrigerator. The cooling system is not working.}
{24200}{}{Glacier}
{24201}{}{Vintage portable refrigerator. The mechanism is still in working order.}
{24300}{}{Glacier}
{24301}{}{Vintage portable refrigerator. The mechanism is still in working order.}
{24400}{}{Table}
{24401}{}{An ordinary wooden table with many drawers.}
{24500}{}{Table}
{24501}{}{An ordinary wooden table with many drawers.}
{24600}{}{Table}
{24601}{}{Wooden table with lots of drawers. Working at such a table is a big risk.}
{24700}{}{Table}
{24701}{}{Coffee table with tempting leftovers.}
{24800}{}{Safe}
{24801}{}{Very durable wall safe.}
{24900}{}{Safe}
{24901}{}{Very durable stationary safe.}
{25000}{}{Boxes}
{25001}{}{Several reliable shipping boxes.}
{25100}{}{Boxes}
{25101}{}{Several reliable shipping boxes.}
{25200}{}{Mailbox}
{25201}{}{A very reliable shipping box.}
{25300}{}{Mailbox}
{25301}{}{Very reliable shipping box.}
{25400}{}{A box of bottles}
{25401}{}{A wooden box designed for storing bottles.}
{25500}{}{Chest of drawers}
{25501}{}{An ordinary chest of drawers, smelling of someone else's underwear.}
{25600}{}{Chest of drawers}
{25601}{}{An ordinary chest of drawers, smelling of someone else's underwear.}
{25700}{}{Chest of drawers}
{25701}{}{An ordinary chest of drawers, smelling of someone else's underwear.}
{25800}{}{Chest of drawers}
{25801}{}{An ordinary chest of drawers, smelling of someone else's underwear.}
{25900}{}{!Do not use}
{25901}{}{In the original - Screw.}
{26000}{}{!Do not use}
{26001}{}{In the original - The antidote to the screw.}
{26100}{}{Cabinet}
{26101}{}{Wooden cabinet in excellent condition.}
{26200}{}{Cabinet}
{26201}{}{Wooden cabinet in disrepair.}
{26300}{}{Cabinet}
{26301}{}{Wooden cabinet. More precisely, what's left of it.}
{26400}{}{Closet}
{26401}{}{Wooden cabinet in excellent condition.}
{26500}{}{Cabinet}
{26501}{}{Wooden cabinet in disrepair.}
{26600}{}{Cabinet}
{26601}{}{Wooden cabinet. More precisely, what's left of it.}
{26700}{}{Sink}
{26701}{}{A porcelain sink that has long since lost its ability to function.}
{26800}{}{Sink}
{26801}{}{A porcelain sink that has long since lost its ability to function.}
{26900}{}{Workbench}
{26901}{}{Yes, this is a standard, old, completely ordinary workbench.}
{27000}{}{Toolboard}
{27001}{}{Various tools are stored on this board.}
{27100}{}{Refrigerator}
{27101}{}{Refrigerator with wheels for easy transportation.}
{27200}{}{Table}
{27201}{}{An ordinary table. If you've ever seen one table, consider that you've seen them all.}
{27300}{}{Table}
{27301}{}{An ordinary table.}
{27400}{}{Table}
{27401}{}{An ordinary table.}
{27500}{}{Table}
{27501}{}{An ordinary table.}
{27600}{}{Table}
{27601}{}{An ordinary table.}
{27700}{}{Table}
{27701}{}{An ordinary table.}
{27800}{}{Table}
{27801}{}{An ordinary table.}
{27900}{}{Locker}
{27901}{}{Built-in wall metal storage box.}
{28000}{}{Locker}
{28001}{}{Built-in wall metal storage box.}
{28100}{}{Locker}
{28101}{}{Built-in wall metal storage box.}
{28200}{}{Locker}
{28201}{}{A metal storage box built into the wall.}
{28300}{}{Chest}
{28301}{}{Personal chest. Designed for storing things, conveniently located by the bed, locked with a key.}
{28400}{}{Chest}
{28401}{}{Personal chest. Designed for storing things, conveniently located by the bed, locked with a key.}
{28500}{}{Chest}
{28501}{}{Personal chest. Designed for storing things, conveniently located by the bed, locked with a key.}
{28600}{}{Chest}
{28601}{}{Personal chest. Designed for storing things, conveniently located by the bed, locked with a key.}
{28700}{}{Chest}
{28701}{}{Personal chest. Designed for storing things, conveniently located by the bed, locked with a key.}
{28800}{}{Chest}
{28801}{}{Personal chest. Designed for storing things, conveniently located by the bed, locked with a key.}
{28900}{}{Locker}
{28901}{}{Personal storage container.}
{29000}{}{Locker}
{29001}{}{Personal storage container.}
{29100}{}{Locker}
{29101}{}{Personal storage container.}
{29200}{}{Locker}
{29201}{}{Personal storage container.}
{29300}{}{Locker}
{29301}{}{Personal storage container.}
{29400}{}{Locker}
{29401}{}{Personal storage container.}
{29500}{}{Things}
{29501}{}{A variety of objects that can be called in one word "things".}
{29600}{}{Things}
{29601}{}{A variety of objects that can be called in one word "things".}
{29700}{}{Things}
{29701}{}{A variety of objects that can be called in one word "things".}
{29800}{}{Things}
{29801}{}{A variety of objects that can be called in one word "things".}
{29900}{}{Mailbox}
{29901}{}{An army box for storing and transporting weapons.}
{30000}{}{Mailbox}
{30001}{}{An army box for storing and transporting weapons.}
{30100}{}{Mailbox}
{30101}{}{Army ammunition storage and transportation box.}
{30200}{}{Mailbox}
{30201}{}{Army box for storing and transporting ammunition.}
{30300}{}{Boxes}
{30301}{}{Several reliable shipping boxes.}
{30400}{}{Boxes}
{30401}{}{Several reliable shipping boxes.}
{30500}{}{Mailbox}
{30501}{}{A very reliable shipping box.}
{30600}{}{Mailbox}
{30601}{}{A very reliable shipping box.}
{30700}{}{Locker}
{30701}{}{Personal storage container.}
{30800}{}{Locker}
{30801}{}{Personal storage container.}
{30900}{}{Locker}
{30901}{}{Personal storage container.}
{31000}{}{Locker}
{31001}{}{Personal storage container.}
{31100}{}{Container}
{31101}{}{Army transport box with radiation protection.}
{31200}{}{Container}
{31201}{}{Army transport box with radiation protection.}
{31300}{}{Moonshine still}
{31301}{}{Apparently, this is a moonshine machine running on firewood.}
{31400}{}{Backpack}
{31401}{}{Someone left this hiking backpack with all his things here.}
{31500}{}{Vending machine with a Nuka-cola}
{31501}{}{The advertisement on board this vending machine depicts a popular drink.}
{31600}{}{The corpse of a prisoner}
{31601}{}{The stiffened corpse of an escaped prisoner.}
{31700}{}{Pot with waste}
{31701}{}{I don't want to dig into this pile of dirty stuff at all.}
{31800}{}{The Destroyed Totem}
{31801}{}{A pile of garbage that once served the Jackals as a totem.}
{31900}{}{The body of a mercenary}
{31901}{}{The stiffened corpse of one of the guards of the expedition. He died of blood loss.}
{32000}{}{Overseer's post}
{32001}{}{This is the overseer's post. It has not been used for a long time.}
{32100}{}{Metal cabinet}
{32101}{}{Antique armored cabinet. Very reliable.}
{32200}{}{Tank with biomusor}
{32201}{}{The remains of human bodies after operations were sent to this tank. Apparently, the surgeon had a lot of work to do.}
{32300}{}{Remains of a sergeant}
{32301}{}{The shrunken corpse of a sergeant. Apparently, he was killed by security robots.}
{32400}{}{Newspaper vending machine}
{32401}{}{This newspaper machine is probably empty... or not.}
{32500}{}{The raiders' belongings}
{32501}{}{Fortunately for you, the raiders forgot these things before leaving.}
{32600}{}{Mycelium}
{32601}{}{These glow-in-the-dark mushrooms grow right in the middle of a toxic puddle.}
{32700}{}{Donation box}
{32701}{}{This box is used to collect donations.}
{32800}{}{Table}
{32801}{}{Elegant antique table for people with high requirements. A luxurious armchair is attached.}
{32900}{}{Fire locker}
{32901}{}{For some reason, this locker is called a "fireman". No one remembers where this name came from.}
{33000}{}{Fire locker}
{33001}{}{For some reason, this locker is called a "fireman". No one remembers where this name came from.}
{33100}{}{The Book of Beamis}
{33101}{}{One of the best books of the pre-war era. Contains a lot of exclusive information of its time.}
{33200}{}{Billiard table}
{33201}{}{It's an old pool table. No self-respecting connoisseur of billiards will play here.}
{33300}{}{Cutting table}
{33301}{}{This table is used for cutting meat. Human meat.}
{33400}{}{Ventilation unit}
{33401}{}{The old ventilation system. Over the years, a lot of dust has gathered in it.}
{33500}{}{Totem}
{33501}{}{A creepy totem collected by the rippers from various junk.}
{33600}{}{Cash register}
{33601}{}{This is a cash desk. And there is a cash register on it.}
{33700}{}{Mutant}
{33701}{}{The body of a vile mutant.}
{33800}{}{Totem}
{33801}{}{A creepy totem collected by the rippers from various junk.}
{33900}{}{Totem}
{33901}{}{A creepy totem collected by the rippers from various junk.}
{34000}{}{Totem}
{34001}{}{A creepy totem collected by the rippers from various junk.}
{34100}{}{Totem}
{34101}{}{A creepy totem collected by the rippers from various junk.}
{34200}{}{Scarecrow}
{34201}{}{A ridiculous-looking structure for repelling pests.}
{34300}{}{The marauder's body}
{34301}{}{The body of a young man torn to shreds. Apparently, but fell into the clutches of the local fauna.}
{34400}{}{Sarcophagus}
{34401}{}{Your ancestor's body rests here.}
{34500}{}{Ice Pile}
{34501}{}{Various things are frozen in this ice pile.}
{34600}{}{Locker}
{34601}{}{Personal storage container.}
{34700}{}{Ed's Bones}
{34701}{}{You see Ed's bones. They have remnants of a jumpsuit with the number 13 on them.}
{34800}{}{Trading house with mentats}
{34801}{}{Judging by the advertisement, this machine gives out mentats.}
{34900}{}{The remains of the robot}
{34901}{}{This robot was sucked into a toxic quagmire. What a terrible death!}
###------- HOLODISKI
{35000}{}{Founder's Records}
{35001}{}{An old and badly battered holodisk with the records of the Founder of the Villa. It seems it can be inserted into your Pip-Boy.}
{35100}{}{Diary from the Vault}
{35101}{}{Holo-recording of the diary of one of the inhabitants of the Vault 27.}
{35200}{}{Expedition report}
{35201}{}{The earth-stained holodisk. Judging by the inscription, it contains the expedition reports from Vault 27.}
{35300}{}{The Quartz Mission}
{35301}{}{An old holodisk, devoid of external inscriptions and markings.}
{35400}{}{McBain's record}
{35401}{}{The suicide audio recording of Sergeant McBain.}
{35500}{}{Mayor's Holodisk}
{35501}{}{A holotape with instructions for the mayor of Casa Grande. The compiler of the prescriptions is prudently not specified.}
{35600}{}{George Crook's notes}
{35601}{}{Holo-recording of field notes compiled by the commander of missionaries in San Brahmin.}
{35700}{}{A letter from Vault-Tech}
{35701}{}{Holotape of the official letter of the company "Vault-Tech".}
{35800}{}{Letter to the shore}
{35801}{}{Holo-recording of a letter from the Petro-Chico oil platform".}
{35900}{}{Luther's Records}
{35901}{}{Diary of an overseer from Vault 24.}
{36000}{}{Festive fireworks}
{36001}{}{A large box with Mexican-made pyrotechnics.}
{36100}{}{Ceremonial wreath}
{36101}{}{A wreath made of wires and light bulbs. It looks strange on the head.}
{36200}{}{Brahmin}
{36201}{}{You are bidding for this brahmin.}
{36300}{}{Magnetic key}
{36301}{}{This magnetic key opens the doors to the mobile fortress of super mutants.}
{36400}{}{Radio receiver}
{36401}{}{An ancient, but still functioning radio receiver from Watts Electronics.}
{36500}{}{Brandley's personal belongings}
{36501}{}{En Brandley's notebook and other things.}
{36600}{}{Lost package}
{36601}{}{The courier was carrying this parcel with a lot of documents and letters to Phoenix. It also contains a note: "In case of loss of the parcel, please return it to the Sonora Express office for a fee."}
{36700}{}{Madre Pendant}
{36701}{}{This pendant is an heirloom. It was transmitted through the female line of your family.}
{36800}{}{Green matter}
{36801}{}{Some kind of chemical from the Followers' lab.}
{36900}{}{Purple substance}
{36901}{}{Some kind of chemical from the Followers' lab.}
{37000}{}{Red substance}
{37001}{}{Some kind of chemical from the Followers' lab.}
{37100}{}{Library Holodisk}
{37101}{}{This holodisk was given to you by a school teacher in Casa Nueva for recording electronic books of the Brotherhood of Steel.}
{37200}{}{White matter}
{37201}{}{An odorless crystalline substance. It's hard to say what it consists of.}
{37300}{}{Laboratory records}
{37301}{}{This holodisk contains the latest reports from the Greenway Hydroponics laboratory.}
{37400}{}{Insecticide}
{37401}{}{Container with a mixture of toxic substances.}
{37500}{}{Raider Map}
{37501}{}{This map shows various places that are under the control of the raiders. In particular, their main base in the mountains in the east is marked.}
{37600}{}{Valuable relic}
{37601}{}{An object of ancient technology, a device of unclear purpose with a dial and toggle switches.}
{37700}{}{Mutagen}
{37701}{}{A mutagen sprayer. Operates from a primitive mechanism on a spring.}
{37800}{}{Chemical kit}
{37801}{}{A large set of chemical tools and substances.}
{37900}{}{Power armor helmet}
{37901}{}{Here is a helmet from the T51b power armor.}
{38000}{}{Power Armor Processor}
{38001}{}{Here is a processor from the T51b power armor.}
{38100}{}{Box with caps}
{38101}{}{A box filled to the top with the most valuable caps from Nuka-Cola. This is a fortune for an ordinary citizen.}
{38200}{}{Wooden figurine}
{38201}{}{A figurine of a long-extinct animal. Roughly carved from real wood.}
{38300}{}{!Do not use}
{38301}{}{In the original - Awl.}
{38400}{}{The lost gun}
{38401}{}{The same gun that was lost in the Rangers' warehouse.}
{38500}{}{Bimis Glasses}
{38501}{}{These are Henry Beamis reading glasses. They are just huge.}
{38600}{}{Neurochip}
{38601}{}{Implant extracted from the body of the deceased tinker.}
{38700}{}{Ranger badge}
{38701}{}{This badge turned out to be in the hands of the wrong people at the time.}
{38800}{}{Questionable package}
{38801}{}{A package with chemical raw materials for a pusher in Phoenix.}
{38900}{}{Questionable package}
{38901}{}{A bag of chemicals for Blue Shields.}
{39000}{}{!Do not use}
{39001}{}{In the original - Solar Scorcher.}
{39100}{}{Faber's passwords}
{39101}{}{There are several passwords written here. They may be useful in Flagstaff Colony.}
{39200}{}{Eugene's contract}
{39201}{}{A contract between the Rangers and Eugene Simon to accept the latter for service.}
{39300}{}{Hiram's letter}
{39301}{}{A letter of recommendation addressed to you from the preacher of Flagstaff. Addressed to Aaron, Lord of the Phoenix and Lord of the Temple of the Sacred Fire.}
{39400}{}{Adviser's report}
{39401}{}{This holodisk was given to you by Ulysses Grant. He should be taken to the military base in Puerto Penasco.}
{39500}{}{Lost Emails}
{39501}{}{Various letters for recipients in Phoenix.}
{39600}{}{Ben's head}
{39601}{}{This head once rested on the shoulders of the leader of the Blue Shields.}
{39700}{}{Hernando's head}
{39701}{}{This head once hung on the shoulders of the chieftain of Los Panchos.}
{39800}{}{Chucho's head}
{39801}{}{This head once hung on the shoulders of the chieftain of Los Panchos.}
{39900}{}{Aidy's head}
{39901}{}{This head once hung on the shoulders of the chieftain of Los Panchos.}
{40000}{}{Gil McCord's Head}
{40001}{}{This head once belonged to a legendary gunslinger from the mercenary Guild.}
{40100}{}{A fragment of a spear}
{40101}{}{A fragment of a spear taken directly from the shell of a giant radscorpion.}
{40200}{}{Glowing mushroom}
{40201}{}{An unusual fungus formed in toxic puddles. Inedible for humans.}
{40300}{}{part}
{40301}{}{The scavenger cartel will surely be interested in this subject of ancient technology.}
{40400}{}{Winch handle}
{40401}{}{A rusty, but still usable handle. They used to be able to do such things.}
{40500}{}{Signal amplifier}
{40501}{}{Electric oscillation power amplifier for a radio transmitter. Uses advanced technology of electronic vacuum tubes of the latest generation.}
{40600}{}{Welding machine}
{40601}{}{Very old, but still working welding machine.}
{40700}{}{ZAX Update}
{40701}{}{An update for one of the ZAX 1.1 routines.}
{40800}{}{!Do not use}
{40801}{}{In the original - First aid kit of a military paramedic.}
{40900}{}{!Do not use}
{40901}{}{In the original - A paramedic's bag.}
{41000}{}{Power cell for generator}
{41001}{}{A standard cell with nuclear material. Designed to generate power in Watts Electronics generators.}
{41100}{}{Fuses}
{41101}{}{Fuses of a nuclear bomb. Without them, it is impossible to activate the detonator.}
{41200}{}{Access card to the hold}
{41201}{}{Access card to some rooms on the Brotherhood of Steel destroyer.}
{41300}{}{Torpedo key}
{41301}{}{Access card to the torpedo bay control terminal.}
{41400}{}{The key to the suite}
{41401}{}{The key to the suite at the Atomic Fever Casino.}
{41500}{}{Radio station codes}
{41501}{}{Access codes from the radio station in the Cathedral are recorded here.}
{41600}{}{Access card}
{41601}{}{Electronic access card for the dam control panel.}
{41700}{}{ZAX Access Card}
{41701}{}{Top-level electronic access card for the ZAX emergency terminal.}
{41800}{}{Access card}
{41801}{}{Electronic access card from the Vault 25. The access level is limited.}
{41900}{}{Access card}
{41901}{}{Electronic access card from the Vault 25. The admission level is the highest.}
{42000}{}{Access card}
{42001}{}{Electronic access card from the Vault 27.}
{42100}{}{Aaron's Key}
{42101}{}{This key once belonged to Aaron, the Lord of the Phoenix. It looks like they are opening some special lock.}
{42200}{}{A worn key}
{42201}{}{A worn-out room key in an Old Motel.}
{42300}{}{The Keys of the Jackals}
{42301}{}{This bunch of dirty keys opens doors in the burrows of the Jackal tribe.}
{42400}{}{Irradiated key}
{42401}{}{A small key you found in Quartz. Probably opens some small lock.}
{42500}{}{Rusty key}
{42501}{}{This key opens the inventory warehouse in the Flagstaff uranium mine.}
{42600}{}{Teeth of the Rat King}
{42601}{}{The lower incisors of a huge mutant rodent that lived in the Flagstaff mines. They can be used as proof of the monster's death.}
{42700}{}{Hangar key}
{42701}{}{This key opens the gates of the hangar on the plantations of the Villa.}
{42800}{}{Family heirlooms}
{42801}{}{A blue jumpsuit, an armband computer and a hiking flask. These things were passed down in your family from generation to generation and are now rightfully passed on to you.}
{42900}{}{Monster Skull}
{42901}{}{The head of a monster. Even in dead form, this object looks terrifying.}
{43000}{}{Motorcycle key}
{43001}{}{The access key to the on-board computer of the motorcycle. Without it, it will be very difficult to hack the security system to get a bike.}
{43100}{}{Necklace}
{43101}{}{A neck ornament consisting of several still combat-ready cartridges tied with an old rope. Perhaps the previous owner did not understand the meaning of these items.}
{43200}{}{Halogen lamp}
{43201}{}{A surprisingly well-preserved 65 watt bulb. Previously, these were often used in car headlights.}
{43300}{}{Stylish glasses}
{43301}{}{This is a pair of very stylish looking mirrored glasses. The mere presence of them in the equipment gives you confidence. Effects: +1 XP when in hand.}
{43400}{}{An ancient relic}
{43401}{}{Apparently, this is a mechanism from a music box. With a smooth turn of a small lever, you wind up the spring and listen to a long-forgotten melody.}
{43500}{}{An ancient relic}
{43501}{}{Vintage atomic clock. They're five minutes behind, but they're still working.}
{43600}{}{Ancient relic}
{43601}{}{A sealed glass ball with white grains of sand floating inside. Perhaps this is what snow looks like, which you were told about as a child and which you have never seen.}
{43700}{}{An ancient relic}
{43701}{}{Medal for Bravery in the Battle of Anchorage, 2077. Apparently, it was a big event.}
{43800}{}{An ancient relic}
{43801}{}{A genuine badge of the defender of law and order. Judging by the markings, it is very old.}
{43900}{}{An ancient relic}
{43901}{}{A sacred book from the sanctuary of the Divine Brahmin. It is doubtful that anyone from the tribe understood its meaning.}
{44000}{}{An ancient relic}
{44001}{}{The picture shows a mushroom cloud behind the smoking dilapidated houses. On the back is the inscription: Mexicali, 2077.}
{44100}{}{An ancient relic}
{44101}{}{A vessel for storing water or some other liquid. This flask differs from the others by the large number 24.}
{44200}{}{An ancient relic}
{44201}{}{A dusty but surprisingly well-preserved Arizona flag.}
{44300}{}{An ancient relic}
{44301}{}{Holodisk with a game for o-very fast computers.}
{44400}{}{Phoenix Map}
{44401}{}{A marked map of the city and its surroundings. A valuable find for a novice scavenger.}
{44500}{}{Pescador token}
{44501}{}{The name of the fisherman Ferrino is engraved on this badge.}
{44600}{}{Access card}
{44601}{}{Electronic access card from the doors on the Petro-Chico oil platform.}
{44700}{}{Map fragment}
{44701}{}{One of the parts of some handwritten map.}
{44800}{}{Guitar strings}
{44801}{}{Strings for a five-string guitar.}
{44900}{}{Copper pipe}
{44901}{}{An ancient musical instrument.}
{45000}{}{Donovan's body}
{45001}{}{This is Donovan's body. Donovan is dead.}
{45100}{}{Ancient icon}
{45101}{}{It's a border patrol badge. It is covered with an obscenely thick layer of ash and dirt.}
{45200}{}{Ancient icon}
{45201}{}{It's a border patrol badge. It glitters proudly in the sun, as it once did in the days of the Old World.}
{45300}{}{Crystal Watts 3000}
{45301}{}{High-precision artificial crystal for a military-grade laser pistol.}
{45400}{}{Laser gun}
{45401}{}{Watts 1000 laser pistol, upgraded civilian model. The power has been increased to the level of military models thanks to a high-precision crystal. Min ST: 3.}
{45500}{}{Trunk}
{45501}{}{An old crate tied to the frame of the bike. Suitable for storing and transporting small items.}
{45600}{}{Bike bags}
{45601}{}{Durable leather bags. Specially made for your motorcycle.}
{45700}{}{Bonita Access Card}
{45701}{}{Access card from Bonita Power station. The access level is limited.}
{45800}{}{Bonita Access Card}
{45801}{}{Access card from Bonita Power station. The access level is the highest.}
{45900}{}{Coffee table}
{45901}{}{This table is littered with various garbage.}
{46000}{}{Pulse generator}
{46001}{}{A working tool designed for emergency failure of electrical equipment.}
{46100}{}{Tablet with recordings}
{46101}{}{A work tablet with old Isaac's notes. Here he describes the chain of actions to restore the Bonita Dam.}
{46200}{}{Gustavo's Holodisk}
{46201}{}{This holodisk Senor Gustavo asked to secretly take to the mayor in the Old Town.}
{46300}{}{Cathode lamp}
{46301}{}{High power electronic vacuum lamp. Most of these lamps have already failed, but this one is still working. That's why it costs so much.}
{46400}{}{Dispatcher module}
{46401}{}{This module is needed for the normal operation of the monorail line. But it doesn't work and needs fixing.}
{46500}{}{Dispatch module}
{46501}{}{This module is needed for the normal operation of the monorail line. It should be returned to its place.}
{46600}{}{The codes of the border Service}
{46601}{}{Here are the codes and commands for remote control of the border robots of the San Ysidro area by radio.}
{46700}{}{!Do not use}
{46701}{}{In the original - the Container of Jesse. Used by the engine in the barter system.}
{46800}{}{Holographic emitter}
{46801}{}{part for generating a holographic image.}
{46900}{}{Water chip}
{46901}{}{Control chip of a computer water treatment system. Used in Vaults of the company "Vault-Tech".}
{47000}{}{Printed circuit board}
{47001}{}{Part from the printing press.}
{47100}{}{Diagnostic board}
{47101}{}{A part from the autodoc that provides fast and accurate analysis of medical data.}
{47200}{}{Fuel controller}
{47201}{}{This chip controls the power distribution in the car's electric motor. Such chips quickly fail, which is why they have become so difficult to find.}
{47300}{}{Drawings of the rotorcraft}
{47301}{}{These are drawings of some military equipment. There is a note on the sheets: "Experimental model".}
{47400}{}{A vending machine with batteries}
{47401}{}{A vending machine for nuclear batteries. The assortment is small.}
{47500}{}{Data from Hermosillo}
{47501}{}{Spy data collected by you at the Mexican Army fort. Some people on the wastelands are willing to pay well for them.}
{47600}{}{A book about San Diego}
{47601}{}{A book of memories of San Diego, released right before the Great War. You can become one of its first readers.}
{47700}{}{Trading house with medicines}
{47701}{}{Vending machine for the sale of medicines and medical supplies. The assortment is small.}
{47800}{}{Torgomat-bar}
{47801}{}{Vending machine for various drinks. The assortment is small.}
{47900}{}{Machine oil dispenser}
{47901}{}{Automatic machine for the sale of engine oil. There is very little oil left.}
{48000}{}{Biogel}
{48001}{}{Sealed jar of shatterproof glass. The label says: "Medical biogel".}
{48100}{}{Microchips}
{48101}{}{Microchips from aviation equipment. For most people it's useless junk, but for some it's a valuable find.}
{48200}{}{Coronado Security Codes}
{48201}{}{Security codes at the Coronado Military Base. They are used by radio communication. An indispensable thing in the current realities.}
{48300}{}{Enhanced Shock Spear}
{48301}{}{Homemade weapon that emits an electric current when in contact with the victim. Min ST: 3.}
{48400}{}{Taser}
{48401}{}{A police taser. Hits the target with electricity. Min ST: 4.}
{48500}{}{Admin Program}
{48501}{}{There is a software module written on the disk for Mr. Handy. With it, the robot will perform the functions of a hotel administrator.}
{48600}{}{"Deep throat"}
{48601}{}{A classic movie that has become a cult. Of course, you won't be watching it.}
{48700}{}{Food processor}
{48701}{}{This is a part for a food processor. It is accompanied by a note "Private property. In case of loss, please return to Edward in San Isidro."}
{48800}{}{Howitzer shell}
{48801}{}{75 mm howitzer shell. Although the cartridge case is very rusty, there is still gunpowder in it. So, in theory, this projectile can be fired.}
{48900}{}{parts from the howitzer}
{48901}{}{These parts can be used to repair one of the damaged howitzers.}
{49000}{}{Coronado Pass}
{49001}{}{A military pass at the Coronado Naval Base. The color is blue.}
{49100}{}{Coronado Pass}
{49101}{}{A military pass at the Coronado Naval Base. The color is red.}
{49200}{}{}
{49201}{}{}
{49300}{}{}
{49301}{}{}
{49400}{}{}
{49401}{}{}
{49500}{}{}
{49501}{}{}
{49600}{}{}
{49601}{}{}
{49700}{}{}
{49701}{}{}
{49800}{}{}
{49801}{}{}
{49900}{}{"Viva, Villa!"}
{49901}{}{This is an old magazine of patriotic comics. It's funny that even now its content does not lose its relevance.}
{50000}{}{}
{50001}{}{}
{50100}{}{}
{50101}{}{}
{50200}{}{}
{50201}{}{}
{50300}{}{}
{50301}{}{}
{50400}{}{}
{50401}{}{}
{50500}{}{}
{50501}{}{}
{50600}{}{}
{50601}{}{}
{50700}{}{}
{50701}{}{}
{50800}{}{}
{50801}{}{}
{50900}{}{}
{50901}{}{}
{51000}{}{}
{51001}{}{}
{51100}{}{}
{51101}{}{}
{51200}{}{}
{51201}{}{}
{51300}{}{}
{51301}{}{}
{51400}{}{}
{51401}{}{}
{51500}{}{}
{51501}{}{}
{51600}{}{Peep-Fight Amplifier}
{51601}{}{The amplifier is designed for quick analysis of the environment. Designed by the Scribes of the Brotherhood of Steel, standard model.}
{51700}{}{"Traps and tricks"}
{51701}{}{Popular essays, veteran of sabotage and reconnaissance groups. The author reveals the methods of conducting sabotage operations, tells about traps and devices of mass destruction. Traps: +4, Stealth: +2}
{51800}{}{"Science for everyone"}
{51801}{}{A guide to the world of modern science containing information about various scientific disciplines. Science: +4}
{51900}{}{"Nikola Tesla"}
{51901}{}{A pre-war magazine entirely devoted to the topic of energy weapons. In the past, it was snapped up by readers like hot cakes. Energy Weapon: +4}
{52000}{}{"Trade"}
{52001}{}{A pre-war weekly published for people running their own business. And although the time is not right now, you will still be able to learn from this publication useful information for trading. Barter: +4, Eloquence: +2}
{52100}{}{"Guns and bullets"}
{52101}{}{A magazine dedicated to the practical use of light and heavy firearms, sometimes publishing biased reviews. Light weapons: +4, Heavy weapons: +4}
{52200}{}{"Medicine"}
{52201}{}{Textbook on the theory and practice of medical care. First aid: +4, Doctor: +4}
{52300}{}{"Repair"}
{52301}{}{Textbook on electronics and repair. The inscription on the cover says that he will be able to "identify a young electrician in everyone." Repair: +4}
{52400}{}{"Survival"}
{52401}{}{A book about the methods and ideals of scouts. Contains very useful information about life outside the city. Survival: +4}
{52500}{}{"Melee"}
{52501}{}{Pre-war illustrated tutorial melee. Unarmed: +4, Edged weapons: +4}
{52600}{}{"Modern castles"}
{52601}{}{This book tells about the device of various locks. Diagrams and illustrations in the manual will help even inexperienced readers to understand. Hacking: +4}
{52700}{}{}
{52701}{}{}
{52800}{}{}
{52801}{}{}
{52900}{}{}
{52901}{}{}
