{100}{}{This is Gloria.}
{101}{}{You see a girl of Mexican appearance.}
{102}{}{You have brought the patient to his senses.}
{103}{}{Madre de Dios! Que pasa?}

{110}{}{Ah-h-h...}
{111}{}{The girl is unconscious. She needs urgent medical attention.}
{112}{}{Thank you for saving my life. I need to catch my breath and recover a little. In the meantime, go to the village and tell us about what happened.}
{113}{}{Er mi salvador, te estoy muy agradecido.}
{114}{}{Okay, I'll tell you about what happened in the settlement. And you rest.}
{115}{}{Le estoy muy agradecido.}
{116}{}{Thank you again.}
{117}{}{Le estoy muy agradecido. Hable con Hector.}
{118}{}{Thank you again. Talk to Hector about what happened.}

#The first dialog
{200}{}{Ah-h-h... (says something unintelligible in Spanish)}
{201}{}{Sorry, I don't understand.}
{202}{}{What the hell are you talking about?}
{203}{}{Monstruos! Están en todos lados!}
{204}{}{Calm down, nothing threatens you now.}
{205}{}{You're not right in the head, are you?}
{206}{}{(looks around nervously)}
{207}{}{Do you want to leave here? I know a way out. Let's go, let's go...}
{208}{}{No, I don't need such noisy fellow travelers right now. Sit here!}
{209}{}{No te preocupes. Está todo bien.}
{210}{}{Monstruos! Están en todos lados! (Monsters! They are everywhere!)}
{211}{}{Calm down, nothing threatens you now.}
{212}{}{Do you want them to come here? Then be quiet, you fool.}
{213}{}{Oh, I'm sorry, they're so scary! I want to go home. Will you get me out of here?}
{214}{}{Of course, you don't belong here in this state. Let's go to the fresh air...}
{215}{}{I don't need such noisy fellow travelers right now. Sit here and make no noise!}
{216}{}{Callado como un ratón.}
{217}{}{I'll be as quiet as a mouse.}
{218}{}{Stay behind...}
{219}{}{}

#Repeat dialog
{220}{}{Por favor no me dejes aquí!}
{221}{}{Please don't leave me here!}
{222}{}{You can't stay here. Come with me...}
{223}{}{Sit here and don't make any noise.}
{224}{}{We'll be out of the cave soon. Let's move on.}

{230}{}{I need to ask you a couple of questions.}
{231}{}{Qué dices? No te entiendo.}
{232}{}{Well, yes, the expected answer. Let's be quiet then.}
{233}{}{What, right now?}
{234}{}{No, we'll talk later.}
{235}{}{Who are you?}
{236}{}{My name is Gloria.}
{237}{}{Where are you from?}
{238}{}{I'm from a fishing village on the coast. It's called San Felipe.}
{239}{}{How did you end up in the cave?}
{240}{}{I think I was walking along the sea when suddenly this monster jumped out of an old boat. I think I lost consciousness and woke up already in this cave. I think these monsters dragged me here... God, what a nightmare!}
{241}{}{What do you know about these monsters?}
{242}{}{Creepy creatures. They give me the creeps. Could nature have created such monsters? No, these are creatures from hell itself. It's not for nothing that they stink of sulfur and decomposition!}
{243}{}{Yes, they really smell unhealthy.}
{244}{}{I think this nasty air comes from their leather body bags. Maybe that's how they hover above the ground? Oh, I'd like to throw a fire there and see what happens!}
{245}{}{Good idea, a hefty flamethrower wouldn't hurt here.}
{246}{}{It looks like the smell of methane.}
{247}{}{Wow, do you know such difficult words? I don't know what that means. But I think they use the air in the leather bags on the body to float in the air. Oh, I wish I could throw some fire in there and see what happens!}
{248}{}{That's right, I urgently need a hefty flamethrower.}
{249}{}{Where are you from, Gloria?}
{250}{}{That's all I was interested in.}
{251}{}{I think I was walking along the sea when suddenly this monster jumped out of an old boat. I think I lost consciousness and woke up already in this cave. I think these monsters dragged me here... God, there were other bodies lying there! Maybe they're still alive? No, I'm not going back there...}