{100}{}{Before you Jan.}
{101}{}{You see a disheveled Mexican with a thick, shabby beard.}

{110}{}{They exist!}
{111}{}{I'm telling the truth. Why don't you believe me?}
{112}{}{They'll get here someday.}
{113}{}{We must act immediately!}

#The first dialog
{200}{}{Oh, amigo! What wind brought you to these lands?}
{201}{}{Well, I...}
{202}{}{Hush! Don't say a word! These people don't like outsiders. They even look at me with a knife in their pocket.}
{203}{}{Why? Did something happen between you?}
{204}{}{(looks around) Monsters!}
{205}{}{Monsters?}
{206}{}{Giant leeches! Creepy disgusting and terribly smelly creatures. They appear on the coast, where I collect shellfish. But these fools don't listen to me, they think I'm out of my mind! But old Yan isn't like that. I'm still in my right mind!}
{207}{}{They are making a big mistake by ignoring your words.}
{208}{}{You really don't seem to be in your right mind, old man.}
{209}{}{Don't leave me alone, amigo. I need help!}
{210}{}{Okay. Where did you say they made their lair?}
{211}{}{It's near the wrecked schooner, further along the coast. But be careful.}
{212}{}{I see. Later.}

#Repeat dialog
{220}{}{Ola, amigo.}
{221}{}{Adios, Jan.}

{230}{}{Who's in charge here?}
{231}{}{Hector. Our old captain.}
{232}{}{Why do you call him Captain?}
{233}{}{We came here on a schooner, and Hector was the captain there. Since then, it has been customary to call him that.}
{234}{}{An interesting story. Tell me something else.}
{235}{}{Now it's clear. Later.}
{236}{}{Who are you?}
{237}{}{My name is Jan. I live nearby and collect shellfish on the coast.}
{238}{}{How do you know English, Jan?}
{239}{}{They spoke two languages in my family. This has been the case since ancient times.}
{240}{}{An interesting story. Tell me something else.}
{241}{}{Now it's clear. Bye.}
{242}{}{Why don't your countrymen want to help you?}
{243}{}{They don't believe me! They think I'm a fool!}
{244}{}{Don't worry so much. I just want to know more about you and this settlement.}
{245}{}{Not very good of them. Maybe we'll talk about it later.}