{100}{}{Here is a merchant.}
{101}{}{You see a fishmonger.}
{102}{}{Hide behind the counter. I don't think these dead people will find us here.}

{200}{}{Hello, señor. How can I help you?}
{1200}{}{Hello, señora. How can I help?}
{201}{}{I don't need anything right now. I'll come back some other time.}
{202}{}{I need to exchange supplies for the road.}
{203}{}{Is that all? Then have a good trip.}
{204}{}{Bye.}
{205}{}{Thanks again for the Geiger counter.}
{206}{}{After the fire on the platform, fishing here is gradually coming to life. Thank you, amigo.}

{210}{}{Where can I buy nuclear batteries for a boat here?}
{211}{}{None of the pescadores will sell their stocks - they themselves do not have enough. The nearest place where we get batteries for boats and a generator is Puerto Penasco. Try to buy there.}
{212}{}{Thank you.}
{213}{}{Listen, if you're going there, can you do me a favor?}
{214}{}{Which one?}
{215}{}{I've been asking the knights from Puerto to send me a new Geiger counter for a long time. But when it comes to technology, they become terrible misers. By the time I wait for a new meter from them, we will all have time to die from radiation. Joke. But if you bring me a new meter, I'll exchange it for a battery. Or I'll pay with clean caps.}
{216}{}{I will keep in mind.}
{217}{}{You're lucky. I just have one such counter, and I don't need it.}
{218}{}{I have a Geiger counter for you.}
{219}{}{Where can I buy nuclear batteries for my bike here?}
{220}{}{Finally! I'll check it out now... Hmm... it seems to work. What will you take in return? bottlecaps or the battery you needed?}
{221}{}{A nuclear battery.}
{222}{}{bottlecaps.}
{223}{}{Take it for free. It's a gift to make the world cleaner.}
{224}{}{Here. Fully charged.}
{225}{}{What you need.}
{226}{}{Here are the bottlecaps, }
{227}{}{ pieces.}
{228}{}{Great.}
{229}{}{Oh, thanks, amigo!}
{230}{}{Please.}

{240}{}{Hilberto says you've been to Inferno?}
{241}{}{A scary place. Burnt ruins and... human BONES are all around.}
{242}{}{Wow, can you tell me more? I'm going there for one task.}
{243}{}{It's creepy. Don't even go on, I don't want to hear it.}
{244}{}{Do you really want to know? To be honest, I don't like to talk about it. But I'll make an exception for you.}
{245}{}{So what kind of dangers are waiting there?}
{246}{}{Do you really want to know? To be honest, I don't like to talk about it. So are you going to order something or not?}
{247}{}{Here are 20 caps for tea. I want to hear your story.}
{248}{}{I don't have any caps right now. Maybe another time.}
{249}{}{I was looking for useful things there. These ruins haven't been looted by looters like in Phoenix yet, so there are plenty of old relics there. But it is extremely dangerous to get them because of radiation and collapses. Half the way I made my way through underground passages. There, by the way, you can hide from radiation for a while.}
{250}{}{Go on.}
{251}{}{But the most terrible thing is the demons.}
{252}{}{Demons?}
{253}{}{The souls of the dead in the nuclear flame. The walking dead, they have lost their sanity and human appearance. Fortunately, they rarely go to the outskirts of the ruins.}
{254}{}{You must have suffered there for the rest of your life.}
{255}{}{Many scavengers died at the hands of demons or radiation. Therefore, you should be more careful - stock up on drugs and a good gun, if you haven't lost the desire to go there yet.}
{256}{}{Good. Thanks for the tips.}
{257}{}{I will not be intimidated by this.}
{258}{}{Judging by your appearance, you already know everything.}
{259}{}{Caught him. Okay, let's change the subject.}

{260}{}{Listen, what do you know about the treasure that Ruiz is looking for?}
{261}{}{Don't mess with that weasel. He is a cunning and dangerous man. And this treasure is doubtful. No one even knows if he really exists.}
{262}{}{Have you tried to find him?}
{263}{}{I only have one piece from the treasure map. Ruiz won't give up his part of the map for anything. And where the others are, I do not know.}
{264}{}{Maybe you can sell me your part?}
{265}{}{Hmm, on the other hand, there is still an opportunity to find the treasure. So I will sell, but for a very good price. Say for }
{266}{}{ caps.}
{267}{}{I'll pay. Here are the bottlecaps.}
{268}{}{How much? Well, no. Keep this piece of paper for yourself.}
{269}{}{No, that's not enough. Come back when you dig up. I also want to make money on someone else's greed.}
{270}{}{Uh, okay. I'll be back with the caps...}
{271}{}{(enthusiastically counts the caps) It looks like I'm going to exhaust my entire year's supply of luck today! Here is my part of the map. Good luck in finding the treasure. You'll need it.}
{272}{}{Later.}

{280}{}{Hey, you know what happened to Johnny?}
{281}{}{Yes, everyone already knows. Rumors spread quickly. It's terrible. I never thought that in our village someone would raise a hand against a person.}
{282}{}{Who do you think it could be?}
{283}{}{I don't know. Johnny was everyone's favorite. Only Ruiz treated him coolly. But he hates everyone in general. Also this comical guy... Tin-Tan, sort of. I think Johnny was avoiding him. Which is strange, because Johnny used to be very happy that his uncle was about to arrive from Phoenix. And after his arrival, the kid seemed to have been replaced.}
{284}{}{Is he really from Phoenix?}
{285}{}{Well yes. His documents are in order. All documents were processed in Sonora Express. However, there is no branch in our wilderness. That's why the caravans take correspondence to Casa Nueva when we want to send it to Phoenix.}
{286}{}{Casa Nueva or Phoenix? Well, thank you.}
{287}{}{Hey, you didn't order anything!}
{1287}{}{Hey, you didn't order anything!}
{288}{}{You will manage.}
{289}{}{Sorry, here are 5 caps for tea.}