{110}{}{Now this boat is only suitable for sailing to the seabed. Her hull needs repair, and the motor needs energy.}
{111}{}{The engine won't start. The indicator indicates that the nuclear battery has run out.}
{112}{}{The boat is ready to sail. Use scientific methods to navigate.}
{113}{}{You have patched up the cracks and holes in the hull.}
{114}{}{The battery is charged. This is enough for one long swim.}
{115}{}{The battery is already fully charged.}
{116}{}{You have nowhere to go now.}
{117}{}{The boat can't stand the weight. Remove all unnecessary items from the backpack.}
{118}{}{You can return to the shore on this boat. Use scientific methods to navigate.}
{119}{}{This boat has enough fuel to get back to shore.}