{110}{}{This body should be examined more closely.}
{111}{}{This is difficult to do during a fight.}

{200}{}{In front of you is the body of a teenager. It's been lying here quite recently.}
{201}{}{Poor guy. What could have happened to you?}
{202}{}{You're out of luck, man.}
{203}{}{It seems that this teenager died from strangulation. There are dark rope marks on his neck, and a trickle of bowel movements stretches from his pants. There are signs of a struggle in the sand around.}
{204}{}{Apparently, someone killed him. We need to inform the Pescadores about this.}
{205}{}{Leave the body alone.}