{100}{}{Here is Hilberto.}
{101}{}{You see a man with a bushy mustache. He is wearing a captain's cap.}
{102}{}{Please help me! Rippers attacked the village!}
{103}{}{The rippers! Hide!}
{104}{}{It's the rippers! Run!}
{105}{}{Rippers attacked the village!}
{106}{}{Save yourself who can! Rippers are everywhere!}
{107}{}{Hey, get off the table! It's not funny.}

{200}{}{Hi. My name is Hilberto. I run a fishing club. What brings you to our harbor?}
{201}{}{Hi, Gilberto. I'm passing through here and I need a bed for the night.}
{202}{}{Passing through? It's a strange thing. Tell me about it later. In the meantime, you can stay in the village, but be careful - we have been restless lately.}
{203}{}{Then I'll take a look around, if you don't mind. See you later.}
{204}{}{What happened?}
{205}{}{What's going on here?}
{206}{}{I'm on a mission for the Brotherhood of Steel. This does not apply to you.}
{207}{}{Then welcome! But be careful - we have been restless lately.}
{208}{}{I'll take a look around, if you don't mind. See you later.}
{209}{}{What did you warn me against?}

{210}{}{What can I do for you?}
{211}{}{It's good to see you.}
{212}{}{How long are you going to be here for?}
{213}{}{See you later, Gilberto.}

{220}{}{Can you tell me about this place?}
{221}{}{This is a fishing settlement. We occupied an old pier and repaired several boats to go fishing. That's all.}
{222}{}{Yourself? Just came and fixed it? I can't believe that a group of fishermen understood the old technology.}
{223}{}{I see.}
{224}{}{Well, not really. We are patronized by the order, which is located in Puerto Penasco. In exchange for seafood, he provides us with everything we need.}
{225}{}{Can you tell us more about the platform?}
{226}{}{A man-made structure in the middle of the sea. It has been there since time immemorial.}
{227}{}{Why was it built?}
{228}{}{It seems that oil was extracted from the seabed there. But I do not know why it is needed. Although it burns pretty well.}
{229}{}{I see. That's all I was interested in.}
{230}{}{How can I get there?}
{231}{}{By boat, of course. Ask the pescadores on the pier.}
{232}{}{Where is Puerto Penasco?}
{233}{}{About 50 miles to the south. Walk along the shore, you won't miss.}

{250}{}{We are suffering an environmental disaster. As if the sea itself punishes fishermen and peasants for the mistakes of our ancestors!}
{251}{}{What are you talking about?}
{252}{}{Take a closer look at the sea. Do you see a platform on the horizon there? It looks like black oily stuff is draining from it directly onto the water. It doesn't smell great at all, and marine life is dying from it at a terrible speed. This has happened before, but lately it has become quite unbearable.}
{253}{}{Is it that bad?}
{254}{}{At first we were delighted to see the coast littered with corpses - just come and take as many as you want. But all these animals are poisoned. Some of our people are still suffering from the poison. And I'm not sure that they will recover at all.}
{255}{}{What kind of poison is this?}
{256}{}{I think this is what used to be called "oil" and was extracted from the bottom of the sea. But I do not know what it is. In any case, you need to stop the leak. We will pay 1000 caps to the daredevil who decides to go to the platform and do it.}
{257}{}{So what's the problem?}
{258}{}{We have been bypassing the platform for a long time. Some flying animals have built their nest there and are not allowed to approach it. Several fishermen have already tried to break through there with a fight. Some came back, others died. But if we don't stop the pollution of the sea, then we will have nothing to eat.}
{259}{}{I'll think about your offer. But I'll need a boat.}
{260}{}{What are you! I can't even swim. I hope you find someone for this assignment.}
{261}{}{Thank you. You give me hope. And about the boat, talk to the pescadores on the pier.}
{262}{}{Okay.}
{263}{}{What about the Brotherhood of Steel? Why not ask them for help?}
{264}{}{The brotherhood? Ha! They would rather give a hand to cut off than allow the destruction of ancient technologies. I think the order hopes to restore this platform. But until he deals with the problems in the east, he will not have enough strength for the platform. That is, we will have to wait for their help for a long time.}
{265}{}{Clearly.}

{270}{}{All patients returned to normal. The poison no longer torments them.}
{271}{}{Thank you on behalf of the whole village!}
{272}{}{You're welcome.}
{273}{}{You don't think it was free, do you?}
{274}{}{Did we negotiate the payment? However, you probably spent some medicines. Here, take 40 caps for each patient. Thanks again.}
{1274}{}{Did we negotiate the payment? However, you probably spent some medications. Here, take 40 caps for each patient. Thanks again.}
{275}{}{Well, that's another thing.}

{280}{}{Viva! You succeeded! The whole village was watching you from the shore. Now the sea will be more merciful to us. Thank you, amigo. We are eternally indebted to you. Here are 1000 caps. We collected this award to the one who could cope with our problem. She's yours now.}
{281}{}{Keep the caps for yourself. I didn't do it for the caps, but for the sake of ordinary people in trouble. How my Villa once got into it.}
{282}{}{You really are an amazing person.}
{283}{}{Goodbye, Gilberto. It's time for me to go.}
{284}{}{Well, if you insist, you'll have to take these bottlecaps.}
{285}{}{Drop by if you're around. You're always welcome here.}
{286}{}{Goodbye, Cap. It's time for me to go.}

{290}{}{Listen, you're on your way from Puerto, aren't you? We know that there was an explosion there, and after that communication with the order stopped.}
{291}{}{The Order went to the bottom to feed the six-eyed fish.}
{292}{}{That's how... And you don't really appreciate them, do you? To be honest, we weren't ready to kiss them passionately either. But they helped us in exchange for fish. Without them, you know, it will be hard. Well, we've lived well for a while, now let's do survival again.}
{293}{}{Freedom is more precious to me than life under someone's oppression. I hope you will understand this now too. Happen.}
{294}{}{I didn't think of that. I am very sorry that it happened.}
{1294}{}{I didn't think about it. I'm really sorry about what happened.}
{295}{}{I? No, I haven't been there and I don't know anything about the explosion.}
{1295}{}{I? No, I wasn't there and I don't know anything about the explosion.}
{296}{}{Really? Okay, I'm not going to ask how you managed to get here, bypassing the only settlement on the way. I just want to say that if the Brotherhood is no more, then we will have a hard time here. After all, they helped us in exchange for fish.}
{297}{}{I think now you will feel the beauty of freedom. You'll like it.}
{298}{}{I'm really sorry about what happened.}
{299}{}{}

{300}{}{I'm going to Inferno on a mission from the Brotherhood. What do you know about this place?}
{301}{}{A lost place. That's why it's called Inferno.}
{302}{}{Have you been there?}
{303}{}{I haven't been there myself. But some brave souls went in search of useful things. The Brotherhood of Steel pays handsomely for pre-war relics. But life is more expensive, you know. The only one who has been there and returned is the bartender, he should be at the club now. Talk to him.}
{304}{}{I'll talk to him when I'm done with you.}
{305}{}{OK, thanks.}

{310}{}{The Brotherhood of Steel is talking about a settlement on the other side. What do you know about him?}
{311}{}{We don't swim that far. But it may be true. Some saw lights on the other side with binoculars. If people live there, they probably suffer from loneliness.}
{312}{}{Looks like I'll have to go there myself to find out.}
{1312}{}{Looks like I'll have to go there myself to find out.}

{320}{}{Besides the platform, what else can you do here?}
{321}{}{Well, someone is stealing fish caches and nets along the shore. I think it's some kind of beast from the wasteland. But it has not been possible to catch him yet. If you find out who is doing this, I will pay 50 caps.}
{322}{}{Agreed. I'll find this thief.}
{323}{}{This is not enough. Look for a fish lover yourself.}
{324}{}{I know what kind of creature was ruining your networks.}
{325}{}{Really? And who is it?}
{326}{}{It was a dead man. During the day he hid in the shadow of the lighthouse, and at night he went to the beach in search of fish. Now he's deader than dead.}
{327}{}{Was it the Ripper from Inferno? Oh, Holy Mary, that's not enough yet!}
{328}{}{Inferno? What is it?}
{329}{}{Burnt ruins in the northwest. Who has been there, tells about the locals, disfigured by radiation beyond recognition. This place turns people into monsters and takes away their sanity. We avoid Inferno. But the Rippers never came here either. They probably don't like the fresh sea air.}
{330}{}{However, this one got here somehow.}
{331}{}{Perhaps something forced him to leave his native ruins. I hope the others won't follow him. Oh yes, here are your 50 caps. Thank you.}
{332}{}{Good luck, Gilberto.}
{333}{}{Inferno? Yes, most likely he was from there.}
{334}{}{Is there any small job?}
{335}{}{It was a dead man. During the day he hid in the shadow of the lighthouse, and at night he went to the beach in search of fish. I managed to drive him out of the Black Lagoon.}
{336}{}{Perhaps something forced him to leave his native ruins. I hope the others won't follow him. That's just not an invention, is it? I'm not ready to pay 50 caps for bare words, I'm sorry. Here are 10 caps so that no one will be offended.}
{337}{}{You can be understood. Thanks for the 10 caps.}
{338}{}{You bastard, you're going to pay for your deception!}

{340}{}{What's new in this village?}
{341}{}{The news is not joyful. The Brotherhood of Steel is no longer with us. Something exploded on their ship, and now we are on our own. I don't know how we will get out of this old technology without them.}
{342}{}{I see. Anything else?}
{343}{}{We have problems with the oil rig and the flyers here. Big problem. And no one can solve it yet.}
{344}{}{Things are getting better! The oil rig no longer pollutes the water. I think in a few weeks the sea waters will start to delight us with fresh fish again.}
{345}{}{But things got a lot better at sea. }
{346}{}{Ruiz is obsessed with finding the treasure. Which is not. Hehe. Don't fall for his bait, amigo.}
{347}{}{Ruiz has disappeared somewhere. And I don't want to look for him.}
{348}{}{It looks like Ruiz has finally found the treasure he was looking for. Who would have thought that the treasure really exists?}
{349}{}{Sometimes the sea shows us unusual phenomena. Then some monster will appear out of the water, then the other shore is illuminated by light. But we don't usually swim that far. There's nothing to do there.}
{350}{}{It turns out that there was a whole settlement on the other side, and we didn't even know about it! Although the guys there don't look particularly cheerful.}
{351}{}{Some saw a strange greenish glow from the side of the destroyed lighthouse. But it's ruined. Where does the light come from there?}
{352}{}{After we found the dead man near the lighthouse, people began to be afraid to go in that direction. What if other zombies come here from Inferno?}
{353}{}{And there are no more stories. Our town is small and boring.}
{354}{}{Clearly. Then let's change the subject.}
{355}{}{I see. well, then have a good stay.}
{356}{}{Ruiz has been pretty angry lately. I don't know what happened.}

{360}{}{Bad news. Someone strangled a teenager at the lighthouse.}
{361}{}{This is VERY bad news! We're going there now...}
{362}{}{Okay.}
{363}{}{Hey, let's agree right away that I have nothing to do with it. Is it clear?}
{364}{}{God, poor Johnny! Who could have done it?}
{365}{}{Tell me about Johnny.}
{366}{}{He moved here with his parents three years ago. The parents died at sea when the boat capsized. But Johnny was not discouraged. He was such a good boy! He worked tirelessly to provide for himself.}
{367}{}{Does he have any relatives?}
{368}{}{Only Uncle Tin. He moved recently by an invitation letter that Johnny sent to Phoenix after the death of his parents. Tin is a little weird. He often spends time on the shore trying to catch a fish, although there is only garbage floating here. I don't know how to tell him what happened. As soon as the relatives were united, fate separated them again. It's so sad.}
{369}{}{Any idea why he might have been killed?}
{370}{}{Well, Johnny didn't have any enemies. And there was no point in robbing him.}
{371}{}{What do you say about the piece of rope with which he was strangled?}
{372}{}{Hmm, exactly the same rope Ruiz uses in his craft. But this piece looks pretty fresh, as if it was only recently taken out of the warehouse.}
{373}{}{Well, a thorough investigation is required here. It's not worth spreading yet, so as not to scare off the criminal.}
{374}{}{I want to talk to you about Johnny's murder.}
{375}{}{Poor Johnny! So did you manage to find the killer?}
{376}{}{No new leads yet. See you later.}
{377}{}{Where were you at the time of the murder?}
{378}{}{I was sleeping in my club!}
{379}{}{Tell me about him.}
{380}{}{I talked to Uncle Johnny. He says that only Ruiz has such a rope.}
{381}{}{That doesn't prove anything. Although Ruiz is always angry, he still has no motive for murder. Try talking to him too.}
{382}{}{Okay.}
{383}{}{The records of Jose Rene Ruiz say that Tin-Tan was the last one to buy his rope.}
{384}{}{That doesn't prove anything. Tin-Tan is weird, but he's still Johnny's uncle. He has no motive for murder. Try talking to him too.}
{385}{}{Okay.}
{386}{}{It could be Jose Rene Ruiz. He has that rope. And Tin-Tan. He bought it in the recent past.}
{387}{}{Well, that doesn't prove anything yet. After all, they both have no motive. But that's something. I think we should ask around at the club. Maybe someone knows something about their relationship with Johnny?}
{388}{}{Okay.}
{389}{}{The real killer is Tin-Tan.}
{390}{}{I remember our conversation. But doesn't he have a motive?}
{391}{}{To be honest, I don't know what his motive is. I should probably think about it again.}
{392}{}{He's not who he says he is. Johnny's real uncle died during the trip, and he appropriated his documents. He is a robber.}
{393}{}{So that's why he was acting like an idiot comedian! He pretended to be a fool so that no one would recognize him as a dangerous person. Sly son of a bitch!}
{394}{}{He already got what he deserved after he decided to attack me.}
{395}{}{Wow! You've got nerves of steel. Thanks for the help. We don't need any garbage here. And life is not very good without them.}
{396}{}{I hope you feel better now. Good luck.}
{397}{}{That's not the cruelest thing you've ever seen in your life, Cap. Be.}
{398}{}{It's true. You need to capture him as soon as possible and bring him to justice.}
{399}{}{Thanks for the help. We don't need any garbage here. And life is not very good without them.}

