{100}{}{You see a computer.}
{101}{}{You see a computer with access to a shared network.}

#Dialog
{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Next.}
{204}{}{Go back to the main menu.}

{210}{}{October 23, 2077, 12:00}
{211}{}{The platform calls the Operator. Reception? (silence) I repeat. The platform calls the Operator. Reception?}
{212}{}{October 23, 2077, 12:10}
{213}{}{Says the Platform! Calling the Operator. Can you hear me? (silence) What happened there...}
{214}{}{October 23, 2077, 13:00}
{215}{}{Says the Platform. There is no connection with the shore. If someone hears me, please give a counter signal.}
{216}{}{October 23, 2077, 21:00}
{217}{}{There is still no connection with the coast. We checked the radio equipment, no malfunctions were detected. Why is there no connection? Why is the Coast Guard silent? If someone hears me, give me an answer!}
{218}{}{October 24, 2077, 12:00}
{219}{}{I'm switching to emergency frequencies. Can anyone hear me? Answer me! What's going on there? Our technologist says that the day before yesterday there was a noticeable flash from Mexicali. We suspect that this may be a Chinese sabotage at the power plant. I'm asking for help from the Coast Guard. Someone, please respond!}
{220}{}{October 30, 2077, 12:00}
{221}{}{We've been out of touch for a week now. The platform is working normally, the workers are also fine. But we don't understand what is happening on the shore. The administration does not get in touch, civilian radio stations are silent. We've had bad communication before, but a whole week of complete silence is too much. We can't leave the platform yet, so as not to violate the employment contract. We hope that the situation will be resolved in the near future.}
{222}{}{November 6, 2077, 8:02}
{223}{}{Today, according to the schedule, we have to receive a cargo with food and a shift. Where the hell are they? If no one gets in touch, we will be forced to leave the platform.}
{224}{}{November 20, 2077, 5:48}
{225}{}{Attention to everyone who hears me! Says the Platform. We are leaving the station in a single lifeboat. One person remains at the station. I ask everyone who hears me to help.}
{226}{}{November 21, 2077, 12:33}
{227}{}{The platform is in touch! Who's talking?! - It's us, buddy. And we have very bad news... Mexicali is destroyed by a nuclear explosion... - Thu... Oh, my God! - ...and it looks like we've caught a hell of a lot of rads along the way. I was the only one able to get to the shore to give you this message... I'm suffocating... Don't do anything stupid there... Save food and water, but we will not return the boat. Goodbye, amigo. It was nice working with you...}
{228}{}{November 29, 2077, 15:00}
{229}{}{Says... Anyway, who cares, right? Nobody needs this station anymore. Just like me. I'm here alone and I can't go anywhere. When the station was automated, these misers from the administration left only one boat to make room for new equipment. The boat is somewhere on the shore now. I can hardly swim there on my own. Will there ever be help? I don't know. I have enough food and water for a month, no more. In the meantime, I will make sure that there is no catastrophe here. However, the coast of Cortez has already become an ecological disaster zone without our station. It's all because of human greed...}
{230}{}{December 25, 2077, 23:14}
{231}{}{Hey, you're there, on the shore! Probably celebrating Christmas already, huh? *Ic!* I just remembered about a bottle that one of the workers had saved. *Ir!* I want to say hello to everyone. You were joking, right? There was no war, was there? And the Mexicali is intact, right? Firstly, I will join you soon, I will only wear a life jacket... so... wait for me, kids! Daddy, we'll be home soon!}
