{100}{}{You see a security terminal.}
{101}{}{You see a terminal with access to a shared network.}

#Dialog
{200}{}{Enter command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Next.}
{204}{}{Go back to the main menu.}

{210}{}{Activate the security turret.}
{211}{}{Unknown user. Access is blocked. Contact the security service.}
{212}{}{Access has been obtained. Attention: The security turret will protect the platform from any hostile targets. Would you like to activate the turret?}
{213}{}{Yes.}
{214}{}{No.}
{215}{}{Security turret activated.}
{216}{}{OK.}
{217}{}{Disable the security turret.}
{218}{}{The security turret is disabled.}
