{100}{}{You see a security computer.}
{101}{}{You see a computer with access to the security system.}

#Dialog
{200}{}{Access to the security system has been obtained. Enter the command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Next.}
{204}{}{Go back to the main menu.}
{205}{}{Cancel.}

{210}{}{Deactivate security turrets.}
{211}{}{Disabling the turrets threatens the safety of the oil platform. Are you sure you want to disable the security turrets?}
{212}{}{Yes. Disable those damn turrets!}
{213}{}{Done. Security turrets deactivated.}
{214}{}{Activate the security turrets.}
{215}{}{Done. The security turrets are activated.}

{220}{}{Add a new identity to the database.}
{221}{}{Please fill out the application form for admission.}
{222}{}{Name: }
{223}{}{. Age: }
{224}{}{. Place of birth Villa, Arizona. Tolerance: full.}
{225}{}{Done. A new person has been added to the database.}
