{100}{}{You see a computer.}
{101}{}{You see a computer with access to a shared network.}

#Dialog
{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Next.}
{204}{}{Go back to the main menu.}

{210}{}{General message.}
{211}{}{Attention to all staff! The company's management has decided to fully automate the station. Only a few people will remain on the platform to control the systems, the rest of the employees will be dismissed. This is necessary to increase production efficiency, reduce financial costs and increase anti-spyware security.}
{212}{}{The management apologizes for the loss of work and will pay compensation in accordance with the employment contract. The process of replacing people with robots will be phased and will take three months.}
{213}{}{We also inform you that during this time a new protection system will be in effect on the platform. All employees will be issued identification cards.}
{214}{}{List of drilling platforms in the Cortez Sea.}
{215}{}{(You find a long list of platforms. Almost all of them are marked as closed. Apparently, the oil in the sea was on the verge of exhaustion already before the Great War. Numerous skeletons of these structures are still discernible on the horizon.)}
