{100}{}{Here is a villager.}
{101}{}{You see a fisherman with dark skin.}

{110}{}{Hello.}
{111}{}{Get out of here.}
{112}{}{You're not welcome here.}
{113}{}{You know, you should take a leaky boat and sail far out to sea.}

{120}{}{Hi.}
{121}{}{Nice to see a new face.}
{122}{}{Glad to meet you.}
{123}{}{The catch has been meager lately.}
{124}{}{If you have enough brains, don't swim far into the sea.}
{125}{}{A real monster lives in the sea!}
{126}{}{I think there will be a storm.}
{127}{}{Do not walk along the shore at night.}
{128}{}{}
{129}{}{}

{130}{}{My respects.}
{131}{}{You are always welcome here.}
{132}{}{Thank you for everything you do for us.}
{133}{}{The catch is excellent.}
{134}{}{Do you want to take a boat ride?}
{135}{}{A real monster lives in the sea!}
{136}{}{There may be a storm.}
{137}{}{At night, you should not walk along the shore.}
{138}{}{}
{139}{}{}

{140}{}{Are you sure you don't know what happened in Puerto?}
{141}{}{Puerto is destroyed! Without them, it will be difficult in these desolate lands.}
{142}{}{The Brotherhood of Steel has left us. And with them, security left us.}
{143}{}{Damn, if the Brotherhood had such explosives, how much useful could they give us?}
{144}{}{We, of course, will live without the Brotherhood. But they supplied us with everything we needed.}

{150}{}{Oh, how it burns!}
{151}{}{It's amazing that the sea is BURNING.}
{152}{}{The whole sky is from oil burning. A lot of it is spilled in the sea.}
{153}{}{Thanks for the help with the oil. I'll have to breathe a little smoke, really...}

{159}{}{Hey, are you saving the lives of the poisoned? Thank you.}

{160}{}{Someone took short Ruiz. I won't miss him.}
{161}{}{Shorty Ruiz was killed. Someday he'll end up with it.}
{162}{}{I wish I could hear Ruiz swearing at fishermen in the morning anymore.}
{163}{}{I'm terribly curious, what kind of treasure did Ruiz find with this gringo?}
{164}{}{Shorty Ruiz walks around angry, as if someone beat him at cards.}
{165}{}{So the ghost at the lighthouse really exists?}
{166}{}{Now I won't go to the ruins of the lighthouse alone.}
{167}{}{The demons of Inferno got too close to us.}
{168}{}{Oh my God, do the demons of Inferno now live next to us? A nightmare!}
{169}{}{What if the undead from Inferno move here?}