{100}{}{In front of you is a creature from the Black Lagoon.}
{101}{}{A terrible-looking creature crawls out of the ruins of the lighthouse!}
{102}{}{Uh-uh!}

{200}{}{U-a-a!}
{201}{}{Ah, monster! Die! Die!}
{202}{}{Stop! I'm just like you. I don't want to kill you. Do you understand me?}
{203}{}{Uh-huh?}
{204}{}{Nope. It will be better if you die, you beast!}
{205}{}{Listen, you need to get out of here.}
{206}{}{Uh-huh?}
{207}{}{Fishing is looking for you. And if they find it, they will kill it. Do you understand?}
{208}{}{Ry? Bucky? Ar-r! Food! My food!}
{209}{}{Yes, yes. I understand you're hungry. But this is their fish. And they are ready to kill for it. Get out of here, otherwise you will die!}
{210}{}{You don't seem to understand. Let's see how you understand the language of violence!}
{211}{}{Then you leave me no choice. You'll have to be killed.}
{212}{}{(Looks around in panic and then quickly runs away)}
{213}{}{Come on, you horrible creature, go back to the hell you came out of.}