{100}{}{Thelma is in front of you.}
{101}{}{You see a girl with a sad expression on her face.}
{102}{}{Nice to see you.}
{103}{}{Zombies all around! Is this some kind of apocalypse?}

#The first dialog
{200}{}{Hey, hello, wanderer. It's nice to see a new face in the city. My name is Thelma Ferrino. How are you?}
{1200}{}{Hey, hello, wanderer. It's nice to see a new face in the city. My name is Thelma Ferrino. How are you?}
{201}{}{Just great. And how are you doing?}
{202}{}{There have been better days. But thanks for asking.}
{1202}{}{There have been better days. But thanks for asking.}
{203}{}{Why are you asking?}
{204}{}{Well, I just want to get to know you. We rarely have guests. Especially now. It used to be busier here.}
{205}{}{What happened?}
{206}{}{Well, I can tell you if you pour me something refreshing from the bar.}
{207}{}{Okay, I'll get something now.}
{208}{}{No booze, señorita. Adios.}
{209}{}{Here are 5 caps for you, take it yourself.}
{210}{}{Muchas gracias!}
{211}{}{Now tell me what's going on here.}
{212}{}{Well, you've already shared a drink. I think I owe you.}
{1212}{}{Well, you've already shared the booze. I think I owe you one.}
{213}{}{You're not leaving. Which means you liked it here. Will you keep me company?}
{214}{}{And will you tell me about this settlement?}
{215}{}{What is going on here in general and why are you so sad?}

{220}{}{It's all because of that damn tower in the Sea of Cortez. It has been there since time immemorial. She didn't have any problems before. The Pescadores even used it for recreation until some flying monsters got there. And recently, some kind of poisonous filth began to drain from this platform. Half the sea is probably already dead because of her.}
{221}{}{Did someone die in the settlement too? Is that why you're so sad?}
{222}{}{When all this became unbearable, my uncle and the other pescadores went to the platform. They knew it was dangerous, but they had to do something.}
{223}{}{What happened there?}
{224}{}{I just saw through the binoculars how they went inside. Nothing has been heard of them since. Obviously, they all died. (takes a deep sip straight from the bottle)}
{225}{}{Sorry. You must have loved your uncle?}
{226}{}{When you live together in the same boat for so long, everyone becomes family, even if they come from different parts of the wasteland. You know, I would be happy if someone would return his things to me as a keepsake.}
{227}{}{I don't think I'll ever be on this platform. Sorry, but you're in the wrong place.}
{228}{}{I'll keep that in mind. Cheer up, Thelma.}
{229}{}{}

{230}{}{Hey, hello, wanderer. So it was you who lit the torch right in the middle of the sea? Cool!}
{1230}{}{Hey, hello, wanderer. So it was you who lit the torch right in the middle of the sea? Cool!}
{231}{}{There was a case. Oil won't hurt you anymore. And the flyers, too.}
{232}{}{Thank you from the bottom of my heart. Have you come across the remains of our pescadores on the platform? My uncle was among them.}
{233}{}{No, I'm sorry. The flyers must have eaten them.}
{234}{}{I thought so. Well, all right. It's time to come to your senses and get down to business. Now we will have a lot of work again!}
{235}{}{Be.}
{236}{}{I only came across this token among a pile of bones.}
{237}{}{Yes, this is his token! Thank you very much, I will take care of it.}
{238}{}{You're welcome.}
{239}{}{Not so fast. A reward is usually given for such cases.}
{240}{}{I didn't think you'd say that. Maybe that's why you helped us with the platform - to show yourself? Okay, here's my last hundred caps. Is that enough?}
{1240}{}{I didn't think you'd say that. Maybe that's why you helped us with the platform - to show yourself? Okay, here's my last hundred caps. Is that enough?}
{241}{}{Enough. Bye.}
{242}{}{On the platform, I came across a token among a pile of bones. Apparently it belonged to your uncle.}
{243}{}{Coincidentally, I just visited the platform and found this token there. Your last name is on it.}

{250}{}{Hi.}
{251}{}{Bye.}
{252}{}{Hi. It's good to see you.}