{100}{}{You see Ruiz.}
{101}{}{You see a local. He is wearing a bandana and a light cape.}
{102}{}{Dig.}
{103}{}{Better not try my patience.}
{104}{}{If I come across another treasure map, I will definitely call you.}
{105}{}{How are you, compañero?}
{106}{}{How are you, sir?}
{1106}{}{How are you, compañero?}

{200}{}{So, so, what do we have here?}
{201}{}{It's not yours. Get out of here.}
{202}{}{Think hard, you freak. No one will help the dead here. Besides, I found this treasure. And it belongs to me. Now kindly move over and GO to HELL!}
{1202}{}{Think hard, ugly. No one will help the dead here. Besides, I found this treasure. And it belongs to me. Now would you kindly move over and GO to HELL!}
{203}{}{Make me, shorty.}
{204}{}{Oh, please. This is your treasure.}
{205}{}{Think hard, gringo. No one can help you here. I found this treasure. And it belongs to me. Now kindly move over and GO to HELL!}
{1205}{}{Think carefully, senora. No one can help you here. I found this treasure. And it belongs to me. Now be a good girl -move over and GO TO HELL!}
{206}{}{Oh, please, look.}
{207}{}{And that's it? Not too much. The old man was a miser, he could have put something more serious. I'd like to take everything, but I'll have to share. What do you choose from this?}
{208}{}{50 pre-war dollars.}
{209}{}{Combat revolver.}
{210}{}{Radaway, 3 pcs.}
{211}{}{I choose everything. Let's get away from my things!}
{212}{}{Hmm, should I kill you? With your reputation, we can even be praised.}
{213}{}{Just try it!}
{214}{}{Everyone remained in the black. But somehow I feel uneasy at the thought of the lost profit. Okay, see you later.}
{215}{}{Bye.}