{100}{}{You see Ruiz.}
{101}{}{You see a local. He is wearing a bandana and a light cape.}
{102}{}{We meet near the treasure.}
{103}{}{Better not try my patience.}
{104}{}{If I come across another treasure map, I will definitely call you.}
{105}{}{Are you looking for treasures? There are none here.}
{106}{}{Don't even think about hiding here. The undead will surely smell your scent.}

{200}{}{Hey, new guy! My name is Jose Rene Ruiz. What are the fates in our town?}
{1200}{}{Hey, new girl! My name is Jose Rene Ruiz. What are the fates in our town?}
{201}{}{I'm looking for something.}
{202}{}{Looking for someone.}
{203}{}{I see. You know, I'm looking for something too. If you help me, I'll help you.}
{204}{}{Really? And what is it?}
{205}{}{Well, an old man hid a treasure somewhere on the coast. And then he gave up. I don't know exactly where the treasure is. There is a map, but he tore it into four fragments and hid it in different corners.}
{206}{}{Tricky.}
{207}{}{I have one fragment. If you find the rest, bring it to me, we'll divide the treasure in half.}
{208}{}{How do I know you won't cheat?}
{209}{}{Okay. If I find it, I'll come straight to you.}
{210}{}{And how do I know that you won't cheat? It's just a contract. If you don't like it, forget it and pass by.}
{211}{}{I'll think about it.}
{212}{}{What a freak you are! How are you tolerated here? However, maybe you'll be useful to me... Listen, new guy, my name is Jose Rene Ruiz. First of all, tell me why you're here?}
{1212}{}{You're so ugly! How are you tolerated here? However, maybe you'll be useful to me... Listen, new girl, my name is Jose Rene Ruiz. First of all, tell me why you're here?}

{220}{}{What news?}
{221}{}{None yet.}
{222}{}{Did you find anything?}
{223}{}{Not yet.}

{230}{}{Have you been on the platform?}
{231}{}{No. And there's nothing to do there. If there was a machine for the production of bottle caps, I would be the first to go there.}
{232}{}{Do you know where to get a battery for a boat?}
{233}{}{All batteries are distributed by the owners of the boats. I won't give up my battery. Look for fools among the other owners, they usually gather at the bar.}
{234}{}{Clear.}

{240}{}{I have the missing map fragments.}
{241}{}{Come here!}
{242}{}{Uh, okay...}
{243}{}{The hell with it! I'll find the treasure without you.}
{244}{}{Ta-ak... (Takes out his fragment, connects everything together and twirls them together for a long time) Here it is...}
{245}{}{Are you sure?}
{246}{}{Precisely! It remains to come and take it. Now find a shovel and go to the place. The treasure is buried next to the old lighthouse on the coast north of the village.}
{247}{}{I'm already running!}

{250}{}{Admit it - did you kill Johnny?}
{251}{}{What the hell are you talking about?!}
{252}{}{He was strangled with your rope. How do you explain it?}
{253}{}{Ha! I sold this rope to several fishermen. And why on earth would I kill anyone at all? Are you an idiot?}
{254}{}{And who did you sell it to?}
{255}{}{I even have it in my notes, look here... Only Tin-Tan has been buying rope lately. Hey, isn't he like Uncle Johnny? No wonder he had my rope.}
{256}{}{Okay. I'll talk to this uncle.}
{257}{}{I'm asking questions here, you idiot. Who was the last person to buy a rope from you?}
