{100}{}{This is the ship's caretaker.}
{101}{}{You see a local resident busy with his usual business.}

{110}{}{Hi there.}

{200}{}{Hey, kid. How can I help you?}
{1200}{}{My respects, lady. How can I help?}
{201}{}{Nothing, perhaps.}
{202}{}{That was a fire! The whole sky was black with smoke!}
{203}{}{Aha. Be there.}

{210}{}{I'm just wondering what you're doing.}
{211}{}{Now I'm resting and admiring the sea. Should I go through the networks?}
{212}{}{Now I'm resting and admiring the sea. Should I go and collect shellfish?}
{213}{}{Now I'm resting and admiring the sea. Should I go to a club?}
{214}{}{Not a bad idea. Later.}

{220}{}{Now I'm trying to fix this beauty boat. But she's still lying on the pier for a long time without doing anything.}
{221}{}{What's wrong with her?}
{222}{}{A couple of holes, cracks, rust. And there's nothing to charge the motor with. Everything is bad, in short, but without boats, the whole local business will die. So someone has to rejuvenate this old lady.}
{223}{}{Holes, you say? Let me see...}
{224}{}{Clearly. Can I ask you a few questions?}

{230}{}{Can I ask you a few questions?}
{231}{}{What is it about?}
{232}{}{And where are the other boats?}
{233}{}{We have, you know, a lot of tension with boats. One boat goes out to sea to fish. There are a few more boats, but you can't swim far on them. We have already lost three boats for various reasons: one did not return from the platform, another capsized during a storm, and the third, as they say, was dragged to the bottom by a sea monster. Although I'm not sure about the latter.}
{234}{}{Where do you get the power for boats?}
{235}{}{The batteries are supplied from Puerto Penasco. And if they are not enough, then we row with our hands.}
{236}{}{What do you know about the oil platform?}
{237}{}{It's a weird place. First there were some sea animals. And now black poison is flowing from there. It would be nice to get rid of it, but how?}
{238}{}{Oh, nothing.}
{239}{}{Thanks for talking. Bye.}
{240}{}{Tell me about your captain.}
{241}{}{And what kind of animals?}
{242}{}{Nasty flying things. They have built a nest on an oil platform and do not let fishermen near it. We barely managed to sail away from there when we went to explore. We were lucky - apparently, these animals are not active during the daytime.}