{100}{}{You see a villager.}
{101}{}{You see a fisherman with dark skin.}
{102}{}{You have a sick person in front of you.}
{103}{}{You see a fisherman. He looks exhausted from a long illness.}
{104}{}{Your skills are not enough to cure a patient without special medications.}
{105}{}{(}
{106}{}{/3) The patient is on the mend.}
{107}{}{I felt better. Thanks, Doc.}

{110}{}{*Cough-cough*}
{111}{}{Oh...}

{120}{}{*Cough-cough*}
{121}{}{I'm not feeling well. Are you kidding me?}
{122}{}{The disease went away as if it had never happened. You're doing wonders, Doc.}
{123}{}{Why treat me if you hate this place so much?}
