{100}{}{Here is Tin-Tan.}
{101}{}{You see a scantily dressed skinny pescador with a thin mustache with crooked teeth.}
{102}{}{Don't come near me! You, uh, smell bad.}
{103}{}{Damn it, and it's all because of that sucker...}

{200}{}{Ay-yay-yay, what a small fish! Why do I need you? Swim back to the sea, get big and then come back. Let's! See you later, little fish!}
{201}{}{Uh, I think I'm bothering you.}
{202}{}{I feel sick on the waves, and then I'm thrown into a dream. Sometimes I dream something cool, like I'm dancing surrounded by beautiful girls!}
{203}{}{Uh, I see.}
{204}{}{I think I should thank you for that oil thing. Muchas gracias! Viva!}
{205}{}{De nada.}
{206}{}{Please.}

{210}{}{Hi. I'm Tin-Tan. How are you?}
{211}{}{Bye.}

{220}{}{Have you been on the platform?}
{221}{}{In my dreams, I'm anywhere and in anyone's arms!}
{222}{}{Um, I see.}
{223}{}{Tin-Tan - what a strange name?}
{224}{}{I used to be... drum roll... Topillo! And then I became Tin-Tan. Actually, my name is... boom, boom, boom... Herman Genaro Cipriano Gomez Valdez y Castillo! But it's a little... uncomfortable, you know?}
{225}{}{Ah, now it's clear.}
{226}{}{I'd say it's a nickname, you idiot.}

{230}{}{I have some bad news. Johnny, your relative, died.}
{231}{}{Oh, how did this happen?!}
{232}{}{Someone killed him. Strangled him with this rope.}
{233}{}{What is it? Hey, Ruiz sells that kind of rope! Oh, did Ruiz do it? It can't be!}
{234}{}{Well, then I should ask Ruiz about it.}
{235}{}{But this rope is fresh, and you were the last to buy it.}
{236}{}{Why would I do this? I'm his uncle! Oh, better get out of sight and let me cry! Oh, poor Johnny!}
{237}{}{The same is true - why? We need to look for more evidence.}
{238}{}{Herman Genaro Cipriano Gomez Valdez y Castillo died. Who are you?}
{239}{}{I don't know what you're talking about!}
{240}{}{The real Herman Valdez died on the way with the stagecoach. You took his papers and impersonated him. Isn't that right?}
{241}{}{(looks around) Hey, you, the jokes are over. Listen to me, asshole. Keep your mouth shut. Or you'll end up like that kid. Truncated?}
{242}{}{It sounds like a confession. It's time to be punished, you son of a bitch!}
{243}{}{I won't say a word to anyone. I promise.}
{244}{}{Really? Well, you probably know better. Sorry to bother you.}