{100}{}{You see Geronimo.}
{101}{}{You see an old man in a national outfit made of brahmin skin.}
{102}{}{Protect me, Brahmin of Salvation! May the joints of this golem fall apart!}
{103}{}{Oh, Dark Brahmin... Why are you looking at me so intently?}
{104}{}{Really... time... it's come...}

#First meeting
{200}{}{The peasant from the Villa... I know who you are. Have a seat. If the road brought you to us, then there are reasons for that, aren't there?}
{1200}{}{A peasant woman from the Villa... I know who you are. Have a seat. If the road has brought you to us, then there are reasons for that, aren't there?}
{201}{}{My village was enslaved. Do you know something about it?}
{202}{}{Twilight covered Sonora from the eyes of the Divine Brahmin. Slavers are everywhere now. They use our brothers in mines, logging, and settlement construction. I don't know where exactly your tribesmen are. But you'll probably find out in Phoenix.}
{203}{}{Thank you. I will search further.}
{204}{}{We, too, suffer from slavers and white-skinned missionaries from Phoenix. They coveted our herds and lands. Hard times are coming, peasant from the Villa.}
{1204}{}{We, too, suffer from slavers and white-skinned missionaries from Phoenix. They coveted our herds and lands. Hard times are coming, peasant woman from the Villa.}
{205}{}{Or maybe you grabbed them, how do I know?}
{206}{}{Don't talk nonsense! We suffer from slavers and white-skinned missionaries from Phoenix. They coveted our herds and lands. Hard times are coming, peasant from the Villa.}
{1206}{}{Don't talk nonsense! We suffer from slavers and white-skinned missionaries from Phoenix. They coveted our herds and lands. Hard times are coming, peasant woman from the Villa.}
{207}{}{Well, I hope you can handle them.}
{208}{}{I hope this will somehow bypass the Villa.}
{209}{}{Your Villa cannot escape this fate. We are all cursed by the same Dark Brahmin. Do you think you can stay on the sidelines like before? Excluded!}
{210}{}{What are you going to do?}
{211}{}{I want to ally with the Rangers. This decision was not easy, but we needed an ally to defend our freedom. After all, our enemies have guns and metal armor. And we have only brahmins and sticks.}
{212}{}{We must help each other in the face of a common threat. What can I do?}
{213}{}{Villa should also stand on our side and on the side of the Rangers. This is a common cause. Find Ranger Oscar, he helps us in the fight against the missionaries. Perhaps your help will be useful to him.}
{214}{}{I will talk to him.}
{215}{}{And I, and the rest of the residents of the Villa - we are not going to participate in this war.}
{216}{}{In that case, you should remember that you are just an uninvited guest in our lands. Don't get in the way if you're not going to help.}
{217}{}{Okay. I'll be leaving soon.}
{218}{}{You can stay in the camp for now. Go.}
{219}{}{Good day, Chief.}
{220}{}{Bye.}
{221}{}{I'm here to help withstand the threat from Phoenix. The Rangers sent me.}
{222}{}{Rangers have long revered our freedom. I appreciate your help.}
{223}{}{Where should I start?}
{224}{}{Turn to Oscar, he lives in a hut at the exit of the sanctuary.}
{225}{}{See you soon, Chief.}

#Repeat dialog
{230}{}{You're trying our patience in vain. Watch your language or you will become an enemy of our tribe.}
{231}{}{What do you need from us?}
{232}{}{You're coming back very opportunely.}
{233}{}{Are you going to help us or hinder us this time?}
{234}{}{Ah, that peasant again. What else do you need?}
{1234}{}{Ah, that peasant woman again. What else do you need?}
{235}{}{I'll be leaving soon, Chief.}
{236}{}{Don't think, I remember all your good deeds. How can I help?}
{237}{}{It is a great joy to see you in our camp.}
{238}{}{You shouldn't have gone back to camp. But since you're here, we'll have to put up with you.}

#Main Quest
{240}{}{I ask you to break your alliance with the Rangers and form an alliance with the Phoenix missionaries.}
{241}{}{Hmm. You're too brave for a peasant, that's for sure. But why should I agree?}
{1241}{}{Hmm-m. You're too brave for a peasant, that's for sure. But why should I agree?}
{242}{}{Hmm. Judging by the rumors that come from the West, I doubt that this alliance was a good idea. But will the new union be better?}
{243}{}{The Rangers are just using you to fight the Phoenix Empire. They don't care about your tribe.}
{244}{}{You're saying serious things. But these are just the words of a peasant against the words of an entire army of rangers.}
{1244}{}{You're saying serious things. But these are just the words of a peasant woman against the words of an entire army of rangers.}
{245}{}{When it's too late, you'll remember my words.}
{246}{}{But even if the truth is behind you, I can't make that decision alone. The other shamans still share my point of view. I won't change it until they change theirs.}
{247}{}{Then I should talk to the other chiefs. See you later, Geronimo.}
{248}{}{The Phoenix Empire will wipe you off the face of the earth if it doesn't subdue you. Do you want such an inglorious end?}
{249}{}{To find peace in the battle for your freedom is the glorious end. I'd rather die than join the empire.}
{250}{}{So you're a fool. And someday you will regret your decision.}
{251}{}{I understand. Sorry for my words, Chief.}
{252}{}{You have united the tribe, great leader. It's up to you to decide what to do next. But by allying with the Rangers, you doom the tribe to an endless war.}
{253}{}{Perhaps the truth is yours. The Phoenix Empire is strong and great. We will not be able to resist and someday we will give up. If we join the empire, we will retain some independence.}
{254}{}{Do you agree?}
{255}{}{Apparently, I should listen to your words. Although the Rangers won't like it. Don't make me regret this decision.}
{256}{}{Thank you. I will convey your words to the commander of the missionaries.}
{257}{}{All my advisors say the same thing. An alliance with the Rangers promises only a bloody war. And the union with the Phoenix grants peace but takes away freedom.}
{258}{}{You know that the lives of fellow tribesmen are more important.}
{259}{}{Some of my advisers have left this world, and the others have turned against me. An alliance with the Rangers promises only a bloody war. And an alliance with the Phoenix grants peace but takes away freedom. In the struggle between the eagle and the snake, it remains only to hide your head in the sand.}

{260}{}{The missionaries have left your lands. Ranger Oscar and I made them leave.}
{261}{}{The missionaries have left your lands. I managed to get them to leave.}
{262}{}{Good news for the whole tribe. We have once again proved our independence and defended our freedom. Of course, the fight will not end, and for a while, we will be disturbed by pale-faced aliens from Phoenix and Ranger scouts. But we will outlive them too.}
{263}{}{[Listen]}
{264}{}{It's as if the Divine Brahmin himself sent you to us in a difficult hour! Thank you. You can stay in the camp as long as you want. I will tell everyone about your exploits so that anyone can share Vault and food with you.}
{265}{}{Thank you.}
{266}{}{I hope your search for the missing family will be even more successful. By the way, our scouts reported that a group of slaves from the Villa was seen on the way to Flagstaff. Look there.}
{267}{}{Thank you, Chief.}

{270}{}{I ask you to reopen the caravan route to Garage City.}
{271}{}{All roads and trade routes with the Phoenix colonies are closed. So the council of elders decided.}
{272}{}{Apparently, you won't change your mind until your relationship with Phoenix is better.}
{273}{}{We have already opened caravan routes with Phoenix. Let all his colonies return to peaceful trade.}
{274}{}{Great. }
{275}{}{Garage City also suffered from Aaron's empire. But now the Cathedral of Fire is destroyed, and Aaron is dead. Phoenix is no longer a threat to you.}
{276}{}{So be it. Give my consent to Ronnie, he runs the caravans in this pueblo.}
{277}{}{Thank you.}
{278}{}{I am ready to open caravan routes for Phoenix. But right in the middle of this path, a snake and an eagle started a fight. Until they agree or devour each other, it will be difficult to negotiate with buyers.}
{279}{}{Garage City also suffered from Aaron's empire. But the Cathedral of Fire was captured by the rebels, and Aaron died. Phoenix is no longer a threat to you.}

#Minor speeches
{300}{}{Who are you?}
{301}{}{You cross a valley, you walk through a whole pueblo and you don't know who is in front of you? It's strong. Then let's take care of your upbringing - I'm the one whose name is Geronimo. I am the supreme leader of my entire tribe.}
{302}{}{Tell me about yourself, Chief.}
{303}{}{Do you really have such a short memory? Then it's worth refreshing it a little - I'm the one whose name is Geronimo. I am the supreme leader of the tribe.}
{304}{}{Supreme? So there are others?}
{305}{}{The tribe consists of clans, and each clan has its leader or representative. Together we unite for a time of severe trials. The rest of the time we wander around Sonora in search of food.}
{306}{}{Now it became clear.}

{310}{}{Tell us about your people.}
{311}{}{Do you want to know the history of the tribe? We suffered a lot but remained faithful to our roots.}
{312}{}{Sorry, Chief, but I don't have time to listen to long stories right now.}
{313}{}{That's it, the young no longer want to know the history and honor their ancestors. And that bothers me.}
{314}{}{Some other time.}
{315}{}{Tell me more.}
{316}{}{We have been living in the lands of Sonora for many generations. Our ancestors lived here even before the world fell from the wrath of the Fiery Brahmin.}
{317}{}{It's hard to believe that you were able to survive in the desert for so long.}
{318}{}{It's a miracle that you managed to survive the War.}
{319}{}{For a long time, the tribe consisted of many small families scattered throughout the desert. Everyone survived as best they could. The infirm and sick died out, and the strong and healthy continued their kind. When the families multiplied and there was not enough land for everyone, clan wars began.}
{320}{}{Is there no war between the clans now?}
{321}{}{The threat to the Phoenix Empire forced us to unite. The townspeople began to steal our cattle, traders began to cheat, and slavers appeared in our lands. We couldn't take it anymore.}
{322}{}{What did you do?}
{323}{}{The elders gathered around a common fire and decided to unite. I was one of those who reconciled and gathered the tribe. It happened here, within the walls of an ancient pueblo.}
{324}{}{Thanks for the story. See you again, Geronimo.}
{325}{}{An inspiring story. Let me ask you about other things.}
{326}{}{No, I just want to talk about another topic.}

{330}{}{You said you knew me. From where? }
{331}{}{Not you, but your father. I've met him before. A strong man. Persistent. One that everyone respects.}
{332}{}{Oh, yes, he is.}
{333}{}{My padre is not worth such words. He could not resist the invaders and surrendered.}
{334}{}{But he made it clear that he did not want a stranger to set foot in the Villa. We have concluded an isolation agreement. However, our tribe does not happen in those parts anyway. There's too little grass for cattle.}
{335}{}{There's nothing but desert all around.}
{336}{}{It is all the more amazing that you are growing a crop in the middle of barren soil. It was as if the Divine Brahmin himself kept your lands... until recently. Maybe you angered him with something?}
{337}{}{It is also interesting how such a miracle arose. But enough about my village. Shall we talk about yours?}
{338}{}{I don't think so. We just lost our vigilance. And by the way, it's time for me to hit the road, to correct this stupid mistake. See you later, Chief.}

{340}{}{I know you have an ancient book, Chief. Give it to me in a good way.}
{341}{}{A book? What are you talking about? We don't read any books.}
{342}{}{You're lying. The Cathedral's bookkeeper could not be mistaken.}
{343}{}{Please, people outside your tribe need this book.}
{344}{}{Hmm, you must be talking about one of those old things that are stored in underground galleries.}
{345}{}{Underground galleries? What are you talking about?}
{346}{}{You see, this ancient building has several floors buried by a layer of sand. There are still old things downstairs, but we don't need them. Therefore, no one goes down there and no one remembers what is there and what is not. And this is not the only buried place - the whole district has gone into the sand for several generations.}
{347}{}{So can I come down and get them?}
{348}{}{Try. But prepare for the worst. A spirit test awaits you below. I myself have heard the voices of long-dead people there. You may never get out of these ancient chambers, like other treasure hunters who went down there in search of relics.}
{349}{}{I'll still take a chance. See you later, Chief.}
