{100}{}{Here is Chatto.}
{101}{}{You see a young man with a restless look.}
{102}{}{Wow, is this one of those things they invent in the City? Amazing!}
{103}{}{The old man is completely out of his mind!}
{104}{}{I will change. I promise, I will protect my tribe from outsiders from Phoenix until the end.}

{200}{}{Ugh, finally Mangas left me alone. It probably looks wild to you at all. Don't think we're all like that. This old man just lost his mind.}
{201}{}{Who are you?}
{202}{}{My name is Chatto. I am a warrior of my tribe.}
{203}{}{Hi, Chatto. Why is that old man mad at you?}
{204}{}{Mangas decided that he, as a shaman, could tell everyone what was right and what was wrong. And why can't I decide for myself? I am also a future leader!}
{205}{}{The future? And who is the real one?}
{206}{}{My father, High Chief Geronimo. Surely you've heard of him, he's a legend. It was he who rallied the tribe and founded the San Brahmin. But other leaders sometimes envy that they did not take his place.}
{1206}{}{My father, High Chief Geronimo. Surely you've heard of him, he's a legend. It was he who rallied the tribe and founded the San Brahmin. But other leaders sometimes envy that they did not take his place.}
{207}{}{And what will you do when you become the head of the tribe?}
{208}{}{To hell with old traditions and this endless war! We must make peace with Phoenix-for our safety and for our future. Such an alliance would give us many opportunities. Look at the weapons of strangers, at new objects of labor, radio communication alone is worth something...}
{209}{}{You're developing a thought...}
{210}{}{And what do the rangers give us? They only protect from bandits and dangerous animals. Many young people support me. We are tired of old people and their instructions. They are leading us to war. It's time for the tribe to change.}
{211}{}{Big ambitions, man. I hope you understand what you're doing. See you later.}

{220}{}{Hello, wanderer. Don't the locals offend you? You tell me if someone doesn't like your presence.}
{1220}{}{Hello, wanderer. Don't the locals offend you? You tell me if someone doesn't like your presence.}
{221}{}{Hello, wanderer.}
{1221}{}{Hello, wanderer.}
{222}{}{Everything is fine. I just want to say hello. See you later.}
{223}{}{And you will do the right thing. Bye.}
{224}{}{In my opinion, it's too soft, but it will do.}
{225}{}{The rebels captured the cathedral in Phoenix. Aaron is killed. Nothing is stopping the Rangers now.}

{230}{}{Chatto, don't you think it's time to take the tribe into your own hands?}
{231}{}{I've been thinking about it for a long time. Old people don't give me the right to vote. They believe that young people should fight and follow the instructions of their elders.}
{232}{}{But you don't agree with them, right?}
{233}{}{They don't understand! Life in Phoenix has not been as sick and feeble as it used to be for a long time. We have lost our superiority. Now the townspeople have acquired powerful weapons and technologies.}
{234}{}{At this rate, the Phoenix will sweep away the tribe.}
{235}{}{Precisely! The only thing that will allow us to survive is to establish contact with Phoenix in order to outwit its inhabitants. We could also acquire weapons and these technologies.}
{236}{}{Exactly. So what are you waiting for?}
{237}{}{Old people don't want to change the foundations. They are used to the idea that technology is evil, and they need to live only according to the precepts of nature.}
{238}{}{Ah, I see. Well, then I have nothing to say. Later.}
{239}{}{You have to talk some sense into them, Chatto.}
{240}{}{What can I do? The old people don't give me the right to vote while my father is alive.}
{241}{}{Well, you have few opportunities left. Good luck.}
{242}{}{When you get the power, it will be too late. Eliminate your padre, Chatto.}
{243}{}{What? Kill my father? Shut up! I won't do it.}
{244}{}{Sorry. Forget what you heard.}
{245}{}{Okay. I'll do it. Someone has to show you the power of the spirit.}
{246}{}{Wait... You're not just going to break into the sanctuary, are you? No, after that I definitely won't get on the throne.}
{247}{}{Any better suggestions? What about the poison?}
{248}{}{Scorpion venom won't work. The whole tribe teaches itself to this poison from an early age. But pre-war drugs usually led to sad consequences when someone decided to be treated with them. Therefore, the tribe abandoned the old medicine a long time ago.}
{249}{}{I think I can find old chemicals in Phoenix. Bye, Chatto.}
{250}{}{You risk missing your chance. Your padre has to give in right now. Come on, do it, Chatto.}
{251}{}{Kill my father? You're offering the unthinkable...}
{252}{}{Sorry. Forget what you heard.}
{253}{}{Do it for the future of your tribe. Your padre and the rest of the elders are leading the tribe to the abyss.}
{254}{}{(Looks at his hands, nodding at your words for a long time, then silently looks up and walks away towards the sanctuary.)}
{255}{}{Don't worry, Chatto. This conversation did not happen.}
{256}{}{Phoenix is actively developing slavery throughout Southern Arizona. The villa has already become a victim.}
{257}{}{Phoenix cooperates with the tinsmiths who enslave the tribes. None of them can be trusted.}
{258}{}{There is another person who is bothering you and your tribe. What are you going to do with Ranger?}
{259}{}{I'll have to kick him out of the pueblo. Let him leave here in peace.}

{260}{}{What's going on there? I saw shamans running into the sanctuary...}
{261}{}{Your padre has passed away. Now you have to lead the tribe. And you know where.}
{262}{}{He... died? But... Wait, let me put this in my head.}
{263}{}{Sure. Think carefully about what to do next.}
{264}{}{If you hurry, you will have time to take power into your own hands. Come on, make an alliance with the Phoenix, as you wanted.}
{265}{}{Precisely! This is my chance. And there's no way I'm going to let these stupid old men ruin everything again. (escapes to the sanctuary)}
{266}{}{Hoi, Chatto!}
{267}{}{You may have heard about the Phoenix explosion. Do you want such allies?}
{268}{}{Then you will be interested in the history of Quartz. Listen carefully...}
{269}{}{The Flagstaff colony uses slave labor on Phoenix caps.}

{270}{}{Now I will lead the tribe in a different direction. The old people won't be able to stop me.}
{271}{}{I think you know what to do. Bye.}
{272}{}{So, are you ready to form an alliance with the Phoenix missionaries?}
{273}{}{That's exactly what I'm going to do. Tell Commander Crook I'm ready to smoke a pipe of peace with him... Or sit down at the negotiating table. Isn't that what they say in the city?}
{274}{}{Peace and prosperity, Chief.}
{275}{}{Okay. Bye.}
{276}{}{By the way, it would be nice to reopen the caravan route to Garage City. What do you think?}
{277}{}{It seems to be a Phoenix colony in the north that sells old items from the ruins? I think it will be useful for the tribe to get new things. Tell Ronnie to look into this matter.}

{278}{}{You can read, can't you? Then read the diaries of the missionary commander. I managed to steal them from the camp.}
{279}{}{...What? What does he write? What does it mean? "Dirty savages.".. "drive into the reservation.".. "take away the weapons.".. And this is the plan he is going to propose to his emperor? Damn it, the Dark Brahmin himself must have clouded my mind.}
{280}{}{Chatto, the chiefs and rangers are unhappy with you and your people.}
{281}{}{I know. Otherwise, I wouldn't have had to fight this fight. The chiefs are wrong, the tribe MUST change. Because the world has changed. Otherwise, the tribe will not survive.}
{282}{}{Okay, I'm not going to argue with you.}
{283}{}{Maybe they're just not ready for change?}
{284}{}{And when will that day come? When will all the old people be in the Heavenly Pastures? During this time, the Phoenix Empire will crush us with its weapons and technologies.}
{285}{}{What does it take for you to finally open your eyes?}
{286}{}{Prove to me that Rangers are the best choice. Maybe they have already distinguished themselves somewhere in the wastelands? Or tell me what the alliance with the Phoenix promises us. Are there any examples that will change my attitude? Maybe there are bad plans in the missionaries' camp to seize San Brahmin, but until I get confirmation of this, I will not change my mind.}
{287}{}{Okay. I'll think about it.}
{288}{}{You're running ahead of everyone, Chatto. Like a brahmin straying from the herd. You don't know where you're going.}
{289}{}{I don't think so...}
{290}{}{Brahmins are herd animals. This is the only way they can protect themselves from enemies. A single brahmin is doomed.}
{291}{}{(sigh) So what should I do? Advise me, because you and I are similar, peasant. Stay in the camp and protect his lousy lifestyle? Or continue the struggle with moldy old people living in the past?}
{1291}{}{(sigh) So what should I do? Advise me, because you and I are similar, peasant. Stay in the camp and protect his lousy lifestyle? Or continue the struggle with moldy old people living in the past?}
{292}{}{I don't know, Chatto. I am also wondering this question. Let's put this conversation on hold for now, okay?}
{293}{}{Cast your vote for an alliance with the Rangers. You and your companions must return to the tribe as part of the whole.}
{294}{}{Maybe you're right. I don't know myself anymore... Okay, I'll talk to the others and try to calm them down.}
{1294}{}{Maybe you're right. I don't know myself anymore... Okay, I'll talk to the others and try to calm them down.}
{295}{}{Go, Chatto.}
{296}{}{I happened to visit Flagstaff. Phoenix created this colony on the lands of the tribe, which was immediately exterminated.}
{297}{}{It's true? For the sake of his colony, the Phoenix destroys an entire tribe? Hm... I must have seen only what I wanted to see. In war, everyone is looking for their own benefit.}
{298}{}{Now you're not going to advocate an alliance with Phoenix?}
{299}{}{To be honest, there's some kind of murky story. Never mind.}
{300}{}{Since you're in doubt, let's cast lots? Let the Wasteland Spirit decide.}
{301}{}{I will not rely on chance.}
{302}{}{As you wish.}
{303}{}{OK, let's draw lots... What's it? Does the draw speak in favor of the Rangers?}
{304}{}{OK, let's draw lots... What's it? Does the die speak in favor of Phoenix?}
{305}{}{To be honest, I don't like it's a good idea to rely on chance anymore. Forget about this case.}
{306}{}{Let's draw lots. Let the Wasteland Spirit decide for you.}