{101}{}{You see a tribal child with black and long hair.}
{102}{}{Don't push!}
{103}{}{Save yourself! It's an evil iron spirit!}
{104}{}{And you're not as bad as other outsiders. Thank you.}

{110}{}{Ts-s!}
{111}{}{Hush! They will hear us...}
{112}{}{It's better to keep silent}
{113}{}{Speak softly}
{114}{}{Mangas must not find out}
{115}{}{Shall we call for help?}
{116}{}{We can't do it on our own}
{117}{}{What should we do?}
{118}{}{I'm not going back there}
{119}{}{ }

{200}{}{"...No, you can't tell, otherwise the whole tribe will hate us!"-"Do you have a better offer? They're going to die there!" - "They're already dead, you fool!" - "I'm not going in there again, we have to admit..."}
{201}{}{Hey, guys, I heard your conversation. What happened?}
{1201}{}{Hey, guys, I heard your conversation. What happened?}
{202}{}{(one kid nervously falls forward) "What's it to you? You're an outsider!" - (the others grab him with apologies) "Calm down, fool, maybe he will help us? Or do you want to go to the shaman?" - "No, the shaman will definitely kill us." - "That's the same..."}
{1202}{}{(one kid nervously falls forward) "What's it to you? You're an outsider!" - (the others grab him with apologies) "Calm down, fool, maybe she will help us? Or do you want to go to the shaman?" - "No, the shaman will definitely kill us." - "That's the same..."}
{203}{}{Tell us what happened.}
{204}{}{Listen, stranger, promise you won't tell anyone? We were walking in the Buried City. It's west of here, where the dunes have covered the old pueblo. Then we heard a growl in the dungeon and started running!}
{205}{}{Normal reaction, guys. That's right.}
{206}{}{Yeah, you have a lot of cowardice.}
{207}{}{Two of our people did not return.}
{208}{}{You idiots!}
{209}{}{Poor children, calm down, everything is already over for you.}
{210}{}{This is a serious matter, guys.}
{211}{}{So can you save them?}
{212}{}{Why such secrecy? Why not tell the chiefs everything?}
{213}{}{Us... we were forbidden to go down to the dungeons... They say an evil spirit lives there, there are landslides, and stuff like that. But it was so interesting that we couldn't resist.}
{214}{}{I need to get ready for the road. Take your best spear and put on the most reliable shoes. Wait here, guys.}
{215}{}{Take me to these dungeons.}

{220}{}{Thank you. Now we will obey the elders.}
{221}{}{Right. You were warned, but you didn't listen. This will be a lesson for you for life.}
{222}{}{You don't have to listen to them for everything they say. Good luck, guys.}