{101}{}{You see a tribal child with black and long hair.}

{110}{}{And you're nothing for an outsider.}
{111}{}{Tell me about your tribe?}
{112}{}{Is your tribe as big as ours?}
{113}{}{Tell some story.}
{114}{}{Shamans say you're a good person.}

{120}{}{Get out of the pueblo, you're a bad person!}
{121}{}{Your tribe is weak.}
{122}{}{Is your whole tribe as shitty as you?}
{123}{}{Tell it to the fools from the City.}
{124}{}{Shamans say there is an evil spirit in you.}

{130}{}{What tribe are you from?}
{131}{}{Our tribe is better than yours.}
{132}{}{And what happened to your tribe?}
{133}{}{I want to hear a story about other lands.}
{134}{}{Shamans say you can't be listened to.}