{101}{}{You see a tribal child soiled in the ground.}

{200}{}{Who is it? A man? It's a man! Hey, save us! We are here!}
{201}{}{Didn't the elders forbid you to approach the Buried City?}
{202}{}{How did you end up here?}
{203}{}{Well... we were exploring the caves when suddenly there was a roar and there was a collapse. We couldn't find a way out.}
{204}{}{Roar?}
{205}{}{Shh! There's an evil spirit wandering around here! He is very big and very scary! Because of him, we can't get out. Help us get out of here! Help!}
{206}{}{Okay, let's get out.}
{207}{}{We'll get out of here first. And then I'll roll you with your muzzles in the sand.}

{210}{}{You're bad! You're a terrible person! Let that monster devour you!}
{211}{}{Better shut up...}

{220}{}{We're not going to die, are we?}
{221}{}{Are we going to die? Are we going to die?}
{222}{}{Please protect us from the evil spirit!}
{223}{}{Follow me. Keep up!}
{224}{}{Stay here and don't go anywhere. I'll see what's ahead.}

{230}{}{Hurray! We are free! We are saved!}
{231}{}{You're safe now.}
{232}{}{You are our savior! You must have been sent to us by the Divine Brahmin himself. Who would have thought that an outsider would save us? I guess your tribe is good. Here, take these things, we found them underground. (passes 10 mm cartridges, shotgun cartridges, a grenade and a lighter) Glory to our savior!}
{1232}{}{You are our savior! You must have been sent to us by the Divine Brahmin himself. Who would have thought that an outsider would save us? I guess your tribe is good. Here, take these things, we found them underground. (passes 10 mm cartridges, shotgun cartridges, a grenade and a lighter) Glory to our savior!}
{233}{}{Don't wait for me, guys. Go straight to the pueblo.}