{100}{}{Here is a villager.}
{101}{}{You see a dark-skinned man in brahmin skin clothes.}

{110}{}{A sandstorm is coming soon.}
{111}{}{Next season will be hot.}
{112}{}{My brahmins are very skinny.}
{113}{}{It is necessary to take more water at the next grazing.}
{114}{}{Staying in the nest is becoming more dangerous.}
{115}{}{This pueblo has always been ours.}
{116}{}{We have to protect our families from bandits.}
{117}{}{Divine Brahmin, protect us from strangers!}
{118}{}{We must obey our leaders.}

{130}{}{Old Man Mangas has already bullied everyone.}
{131}{}{But old man Mangas warned us...}
{132}{}{Genaro will certainly advocate an alliance with the Phoenix.}
{133}{}{Genaro died, and he was the best at bargaining with outsiders.}
{134}{}{Nana takes care of the tribe both as a woman and as a leader.}
{135}{}{Nana was killed by missionaries. Who else could have done it?}
{136}{}{I'm worried about the future of Chatto and his upstart friends.}
{137}{}{I haven't seen Chatto for a long time...}
{138}{}{Chatto is very young, but he has already become a leader. Yes, strange times have come.}
{139}{}{Chief Geronimo knows what is right for the tribe and what is wrong.}
{140}{}{Geronimo... May the Sun always illuminate your Heavenly Paths.}

{150}{}{So this day has come. The Phoenix conquered our tribe.}
{151}{}{The Phoenix missionaries have done their job.}
{152}{}{The Supreme Leader made a decision. It remains for us to obey.}
{153}{}{What about the pueblo? Will we have to leave it?}
{154}{}{Well, it's time for the quail to leave its roost.}
{155}{}{Anyway, I am glad to hear about the end of the war.}
{156}{}{I hope the Rangers are true to their word.}
{157}{}{I pray to the spirits of the Wasteland that this war will end.}
{158}{}{O Divine Brahmin, show us the way!}
{159}{}{The games of the Dark Brahmin led our tribe into a fog.}

{170}{}{It is not worth going to the Buried City alone.}
{171}{}{So that's why the elders forbade going down into the catacombs?}
{172}{}{A real monster lived in the catacombs.}
{173}{}{Glory to the Divine Brahmin! The evil spirit from the dungeon has left us.}
{174}{}{No wonder they talked so much bad about the Underground City.}
{175}{}{I'm still afraid to approach the Buried City.}