{100}{}{In front of you is Sid.}
{101}{}{You see a business-looking man in hiking clothes.}
{102}{}{It was great luck to meet you. Thanks for the help on the road.}
{103}{}{The path is clear.}
{104}{}{There is no one else to pay for the protection of the caravan.}
{105}{}{Vile traitor!}
{106}{}{Thanks to intelligence, you were able to pass unnoticed.}
{107}{}{ died. Now there is no one to pay you for the protection of the caravan.}

# Before receiving the quest
{200}{}{Hello, wanderer. I'm Sid, the merchant. It seems we're both stuck in this hole, right?}
{1200}{}{Greetings, ladies. I'm Sid, the merchant. It seems like we're both stuck in this hole, right?}
{201}{}{I had business here. But I'll be leaving soon.}
{202}{}{Business, you say? Okay. But even if you have a good relationship with the inhabitants of the Pueblo, the tribes in the wastelands are not so friendly. Do you think you can safely pass through their lands?}
{203}{}{Do you have any suggestions?}
{204}{}{That's for sure. I want to visit a normal big city, which they talk about so much here.}
{205}{}{The journey to Phoenix takes only a few days. But this is a dangerous road. You should take care of the escort.}
{206}{}{Do you have someone in mind?}
{207}{}{Oh yes. I'm preparing my caravan to return to Phoenix. I have few people, and the road has become restless because of the showdown with the missionaries. I'm afraid some savages will try to stop us as soon as we leave the pueblo. I need more security. I pay 500 caps for the passage to Phoenix. Well, will you come with us?}
{208}{}{I'll think about your offer.}
{209}{}{Sign me up. I'm in.}
{210}{}{What's your caravan carrying?}
{211}{}{All sorts of savage utensils, leather goods, dried meat. I was also lucky enough to get some Brahmins from Genaro. A fortune will be paid for a living brahmin in the city.}
{212}{}{Do we have to fight on the road?}
{213}{}{It is not excluded.}

{220}{}{Well, will you come with us?}
{221}{}{I still haven't decided. For now - without me.}
{1221}{}{I still haven't decided. For now - without me.}
{222}{}{Sign me up. I'm in.}

{230}{}{Glad to see you on the team. Get ready to leave and come back to me.}
{231}{}{OK.}
{232}{}{I can move out right now.}

#After receiving the quest
{250}{}{Damn, these savages will not leave us alone! We need to get rid of them somehow.}
{251}{}{These radscorpions will kill all our cattle! We have to do something!}
{252}{}{Ambush! Everyone group up! Protect the product!}
{253}{}{Clear.}
{254}{}{The way is clear. Is everyone okay? Then let's move on.}
{255}{}{Give me another minute and we can move out.}
{256}{}{OK, I can go.}
{257}{}{Damn it! We have no Brahmins left. We'll have to dump some of the cargo and carry the rest manually. It looks like I won't earn anything from this trip. Or even go into the negative.}
{258}{}{But WE stayed alive. Let's move on.}
{259}{}{Wait a bit, I need to get ready for the road.}

{260}{}{Thank you for your cooperation. It's a pleasure doing business with you. Here are 500 caps for the job, as promised. And I probably won't return to San Brahmin for another couple of years until the dust settles there. Well, you know.}
{261}{}{Have a nice day, Sid.}
{262}{}{Thank you for your cooperation. But because of the loss of the Brahmins and the cargo, I won't be able to pay you the full price. Here }
{263}{}{ caps for the job. And I probably won't return to San Brahmin for another couple of years until the dust settles there. Well, you know.}
{264}{}{Listen, maybe we'll scout the way?}
{265}{}{We're going too slow. We don't have enough reserves and patience. We need to hurry up.}
{266}{}{Listen, let's scout the ruins ahead. We will spend more time, but we are more likely to survive.}
{267}{}{I was hoping to get to town by sunset, but you're saying the right thing. Go ahead, and we'll catch up later.}
{268}{}{That's what we'll do.}
{269}{}{No, I can't go anywhere yet.}
{270}{}{It can also be dangerous ahead. I can go scouting.}
{271}{}{Will you leave and perish alone? Don't be silly. It will be easier for us to survive together.}
{272}{}{It can also be dangerous ahead. I'll go ahead and assess the situation.}
{273}{}{Be careful. I don't have enough people as it is. I didn't want to lose you yet.}
{274}{}{That's what we'll do. Wait for my signal...}
{275}{}{You're talking business. Singly, we're an easy target. Let's move together.}
{276}{}{I need to get ready. Wait a minute.}
