{100}{}{You see a woman.}
{101}{}{You see one of the women of the tribe. She is busy cooking.}

{210}{}{What do you want?}
{211}{}{Make yourself at home, hero.}
{212}{}{Were you invited here?}
{213}{}{Bye.}

{220}{}{What is that smell?}
{221}{}{I'm cooking brahmin giblets. Hands off! I won't even let you lick the plate. Shoo away!}
{222}{}{Okay, okay.}
{223}{}{I'm cooking brahmin giblets. My favorite dish, but spices are hard to get.}
{224}{}{It smells amazing! Can I try it?}
{225}{}{What a smell. Is it edible at all?}
{226}{}{Our hero is not sorry for anything. Here, take a plate.}
{227}{}{Thank you.}
