{100}{}{You see one of the tribe's warriors.}
{101}{}{You see a dark-skinned man with war paint all over his body.}

{120}{}{I fight for my tribe. What about you?}
{121}{}{If I die, I'll go to the Great Heavenly Pastures.}
{122}{}{The Divine Brahmin will protect me in battle.}
{123}{}{We will win, if we fight shoulder-to-shoulder.}
{124}{}{Whose side are you on?}
{125}{}{The tribe will remember our victories.}
{126}{}{I will protect the pueblo from raiders until my last breath.}
{127}{}{Let the enemy tremble before my shield.}
{128}{}{This amulet was made from the bone of a divine brahmin. It will protect me.}
{129}{}{The Shaman says he has hexed my amulets.}