{100}{}{Here is a warrior of the tribe.}
{101}{}{You see a dark-skinned man with war paint all over his body.}

{120}{}{I'm fighting for my tribe. And you?}
{121}{}{If I die, I will end up in the Great Pastures of Heaven.}
{122}{}{A Divine Brahmin will guard me in battle.}
{123}{}{We will win if we fight shoulder to shoulder.}
{124}{}{Whose side are you on?}
{125}{}{The tribe will remember our victories.}
{126}{}{I will defend the pueblo from the raiders to the end.}
{127}{}{Let the enemies tremble before my shield.}
{128}{}{The amulet of the sacred brahmin's bone will protect me.}
{129}{}{The shaman says he has enchanted my amulets.}