{100}{}{You see a female tribal.}
{101}{}{You see a female member of the tribe. She is busy preparing food.}

{210}{}{What is it?}
{211}{}{Make yourself at home.}
{212}{}{Did someone invite you here?}
{213}{}{Goodbye.}

{220}{}{What is that smell?}
{221}{}{I'm cooking brahmin giblets. Hands off! It's not for you. Now get out!}
{222}{}{Alright, alright.}
{223}{}{I'm cooking brahmin giblets. It's my favourite dish, but it's hard to get the correct spices.}
{224}{}{Smells wonderful! Can I try it?}
{225}{}{The smell is certainly... unique. Is it even eatable?}
{226}{}{Nothing I wouldn't give to our hero. Here, take a plate.}
{227}{}{Thank you.}
