{100}{}{You see Losen.}
{101}{}{You see an old woman in clothes that look strange for her tribe. She is mumbling something under her nose, possibly a spell.}

{200}{}{I knew that you would come here one day. A sad story happened to you.}
{201}{}{How do you know that?}
{202}{}{I see much. The blood of the holy animal tells me such things. My name is Losen.}
{203}{}{So you augur over brahmin blood, or something like that?}
{204}{}{I see the future and the past. Call it however you wish. Show me your hands, and I'll look at your future as well.}
{205}{}{No.}
{206}{}{Alright, let's try it out.}
{207}{}{Hmm... Times of great change are coming. And I see that you will be right in their center. But I need to do a full rite to learn the details.}
{208}{}{Maybe another time.}
{209}{}{Alright, I'm swallowing the bait. What do you need?}
{210}{}{You need to give up something that is valuable to you. Even caps, for instance. Only through a feeling of loss do the most intimate lines of life open.}
{211}{}{Here are 100 caps. Tell me, I want to know everything!}
{212}{}{Maybe another time.}
{213}{}{(conducts a complicated rite over the blood of a holy animal) Hum-m-m... Om-m-m... I begin to see... Yes...}
{214}{}{What do you see?}
{215}{}{I see men with a star on their foreheads... And men who create fire with thoughts... They wish to destroy one another, and you are right between them. Right in their line of fire...}
{216}{}{For some reason, this does not fill me with optimism.}
{217}{}{But the Holy Brahmin will not let you die in this fight. The way is known to you! Do not allow yourself to be deceived! A great mission awaits you!}
{218}{}{Phew, this was quite tense. But what does it all mean?}
{219}{}{You are fooling me! That is no vision of the future.}
{220}{}{Think about what I said! The Holy Brahmin does not give direct commands, it merely shows... images, which one has to figure out for themselves. Perhaps the time has not yet come. When it does, your heart and mind will be open, and you will understand it all.}
{221}{}{I see now who you really are. I just wasted my caps. Bye.}
{1221}{}{I see now who you really are. I just wasted my caps. Bye.}
{222}{}{Thank you, Losen. Your word inspire me to push on forward.}
{223}{}{So you have returned. I see that fate worries you. I could learn what awaits you, if you want.}
{1223}{}{So you have returned. I see that fate worries you. I could learn what awaits you, if you want.}
{224}{}{No, thank you, I do not.}

{240}{}{There is no more I can say to you.}
{241}{}{Alright. Goodbye.}
{242}{}{And still - what do I make of your vision?}
{243}{}{What about that brahmin whose blood you use?}
{244}{}{It's a holy animal. Henaro prepares it for the celebration of the Day of the Sun. On that day, the animal is sacrificed and it's holy blood is used to wash away bad luck and shame from oneself. I myself use such blood to augur, to see our possible future and spread that knowledge to other members of our tribe.}
{245}{}{What kind of a day is that?}
{246}{}{When the desert of Sonora is enclosed by sandstorms. The pastoralists cannot walk to the brahmin grazing areas. They wait over the storm season here, in the pueblo. In such days, when we lack food, we ask the Holy Brahmin for our collective salvation.}
{247}{}{What "holy animal"? Is it somehow different from others?}
{248}{}{The brahmin with the most perserverence. Henaro keeps it in a separate yard to avoid risks and allow the brahmin to live until the Day of the Sun. If such an animal died or fell ill, that would be a tragedy for us.}
{249}{}{Don't you feel sorry for this holy animal?}
{250}{}{What for? The brahmin sacrifice themselves for humans. Henaro chooses one of the brahmin and makes sure it's belly is full the entire year. During that year, it lives a clean, fulfilled and happy life to one day die and grant all members of the tribe forgiveness. A worthy fate for an animal.}
{251}{}{What future do you see for your tribe?}
{252}{}{We stand between a cliff and the abyss, covered in fog. It is difficult to examine anything more closely.}
{253}{}{Interesting.}