{100}{}{Lozen is in front of you.}
{101}{}{You see an old woman in an unusual outfit for her tribe. She mutters something under her breath, probably a spell.}

{200}{}{I knew you'd come here someday, villager. A sad story happened to you.}
{201}{}{How do you know?}
{202}{}{I see a lot, the blood of a sacred animal tells me about it. My name is Lozen.}
{203}{}{So you're guessing on the blood of a brahmin, or something?}
{204}{}{I see the future and the past. Call it whatever you want. Show me your hands, I'll look at your future.}
{205}{}{Well, no.}
{206}{}{Okay, look.}
{207}{}{Hmm... Big changes are coming. And I see you will be in the very center of them. But I need to perform a full rite to find out the details.}
{208}{}{Maybe another time.}
{209}{}{Okay, I'm taking the bait. What is needed for this?}
{210}{}{You need to part with something that is valuable to you. You can even give away the bottlecaps. Only in the sense of loss are revealed the most intimate lines of life.}
{211}{}{Here are 100 caps. Tell me, I want to know everything!}
{212}{}{Maybe another time.}
{213}{}{(performs a complex ritual on the blood of a sacred animal) Um-m-m... Om-m-m... I'm starting to see... yes...}
{214}{}{What do you see?}
{215}{}{I see people with a star in their forehead... And people who generate fire with the power of thought, opposite them... They want to destroy each other, and you are between them. Right in the line of fire...}
{216}{}{Not very happy about it.}
{217}{}{But the Divine Brahmin will not let you die in this battle. You have your own way! Don't let yourself be fooled! A great mission awaits you! Great!!!}
{218}{}{Ugh, it was quite stressful. But how to understand all this?}
{219}{}{You're lying to me! This is no vision of the future.}
{220}{}{Think about what I'm saying! The Divine Brahmin does not give direct instructions, he only indicates images, they need to be able to read. Maybe it's not time yet. When your heart and mind open up, you will understand it.}
{221}{}{Everything is clear with you. I just wasted the bottlecaps. Later.}
{1221}{}{Everything is clear with you. I just wasted the bottlecaps. Bye.}
{222}{}{Thank you, Lozen. Your words inspire me to continue my journey.}
{223}{}{You're back. I see fate is bothering you. I can find out what's waiting for you if you want.}
{1223}{}{You're back. I see fate is bothering you. I can find out what awaits you if you want.}
{224}{}{No, thanks, no need.}

{240}{}{I have nothing more to say to you.}
{241}{}{Okay. Goodbye.}
{242}{}{And yet - how to understand your vision?}
{243}{}{What happened to the brahmin whose blood you use?}
{244}{}{A sacred animal. Genaro is preparing him for the celebration of the Day of the Sun. On this day, the animal is sacrificed, and its sacred blood is washed away from failure and shame. I use blood for divination to see our possible future and convey it to the rest of the residents.}
{245}{}{What kind of holiday is this?}
{246}{}{When the Sonoran desert is closed by sandstorms, pastoralists cannot go out to graze Brahmins. They're waiting out the storm season here in Pueblo. These days, when we have enough food supplies, we thank the Divine Brahmin for our salvation.}
{247}{}{What is a sacred animal? Is it any different from the others?}
{248}{}{A brahmin with the highest fortitude. Genaro keeps him in a separate pen to avoid any risks and allow the brahmin to live until the Day of the Sun. The death or infirmity of such an animal would be a tragedy for us.}
{249}{}{Don't you feel sorry for this sacred animal?}
{250}{}{Don't talk nonsense! Brahmins sacrifice themselves for us humans. Genaro chooses one of the Brahmins and feeds him especially hard for a whole year. A whole year of clean, well-fed, happy life to die in one day and give the whole tribe redemption. A worthy fate for an animal.}
{251}{}{What future do you see for your tribe?}
{252}{}{We are standing between a rock and a precipice in the fog. It's hard to see anything.}
{253}{}{Interesting.}