{101}{}{You see a cattleman.}
{102}{}{Here is one of the local cattle breeders. His face seems familiar to you.}

{200}{}{Hey, look who came to us! I know this stranger. He tried to take away the Brahmins from us near Garage City.}
{201}{}{Yes. But it didn't end well, did it? At least you're still alive.}
{202}{}{Hmm... Did you manage to dissuade the raiders? Anyway, I don't like you. Don't expect confidence in yourself. I hope you get kicked out of the pueblo soon.}
{203}{}{Come on...}
{204}{}{Don't get your hopes up.}
{205}{}{I don't know what you're talking about.}
{206}{}{Is that it? Well... I hardly remember the faces of the raiders myself. Okay. As long as I believe you, stranger.}
{207}{}{Thank you. Believe me, we have no reason for enmity.}
{208}{}{Don't think that I will be afraid of your threats.}
{209}{}{What are you, it's a mistake, I wasn't there...}
{210}{}{Come on, make up fairy tales. I definitely remember your face, bastard!}
{211}{}{Okay, that was a mistake. We thought the Brahmins were wild...}
{212}{}{Yeah. Wild. They thought. It is against such outsiders that Mangas and others act. I hope you're leaving the pueblo soon, thief. Otherwise I can't vouch for myself!}
{213}{}{And what are you going to do now?}
{214}{}{I'll tell the others who you really are. Don't think you can get away with it, thief. I hope you get kicked out of the pueblo soon. Otherwise I can't vouch for myself!}
{215}{}{Bye, friend.}

{220}{}{Come on, roll somewhere else, weed.}
{221}{}{Hi. It turns out you're doing a lot of good for the tribe. Sorry, I had the wrong opinion about you.}
{222}{}{Bye.}