{101}{}{You see a pastoralist.}
{102}{}{You see one of the local pastoralists. His face looks familiar.}

{200}{}{Well, look who's here! I know this outsider. He tried to take away our brahmin near Garage City.}
{201}{}{Yeah. But it ended well, didn't it? They would have killed you. I saved your lives.}
{202}{}{You talked those raiders out of it? Whatever. I don't like you, anyway, and I don't think the others will trust you, either. The moment you'll be kicked out of the pueblo can't come soon enough.}
{203}{}{Come on...}
{204}{}{Keep dreaming.}
{205}{}{I don't know what you're talking about.}
{206}{}{So that's how it is? Just deny it ever happened? ...Fine. I suppose I might have misremembered the faces of those raiders. I'll trust you, outsider. For now.}
{207}{}{Thanks. Believe me, I would never dream of taking away your brahmin.}
{208}{}{Don't think I'll be intimidated by your thinly-veiled threats anytime soon.}
{209}{}{What are you talking about? It must be a mistake, I wasn't even in that place...}
{210}{}{Yeah, yeah, deny some more. I remember your face, you asshole!}
{211}{}{Fine. It was a mistake. We thought the brahmin were wild...}
{212}{}{Uh-uh. Wild. They thought. Outsiders like you are exactly why I know Mangas is right. It'd be best for you to leave our pueblo soon, you thief. Or I can't promise you that I'll control myself!}
{213}{}{Okay. And what are you going to do about it?}
{214}{}{I'll tell the others who you really are. Don't think you'll get away scot-free, you thief. It'd be best for you to leave our pueblo soon. Or I can't promise you that I'll control myself!}
{215}{}{Goodbye, amigo.}

{220}{}{Go to some other place, you leech.}
{221}{}{Oh, hello there. Looks like you've been doing a lot of good for the tribe lately. I'm sorry that I got the wrong impression of you at first.}
{222}{}{Goodbye.}
