{100}{}{You see priest Mangas.}
{101}{}{You see a shaman in a tribal outfit.}
{102}{}{Look! It is that evil metallic spirit! Do you still doubt me now?}
{103}{}{Old man Mangas has completely lost his mind!}

#Floating lines for the 'technology bad' speech
{110}{}{The outsiders are bringing nothing but trouble! We must drive them out!}
{111}{}{They want to break apart our unity!}
{112}{}{Look at what they are doing to our tribe!}
{113}{}{We didn't spend so many generations preserving our traditions so that one day outsiders could come and destroy them!}
{114}{}{There is now disagreement among us. What will this lead to?}
{115}{}{The tribe is once again walking down the path of division. And it is all due to Phoenix.}
{116}{}{We were once whole, but Phoenix taught us to quarrel over trivialities!}
{117}{}{Look at Chatto and his buddies. Their minds have been so corrupted that they can no longer be set on the right path!}
{118}{}{Chatto has learned to *read* from the caravaneers. What next?}
{119}{}{It will become worse! Phoenix won't even let us live in the Wasteland. Aaron's lust for more and more territory won't allow it!}
{120}{}{We can't even go to the brahmin grazing areas due to those missionaries.}
{121}{}{Bring all the items the heathens brought with them here! Burn them! Burn them all!}
{122}{}{Look at those books and technologies - is that what you want here?}
{123}{}{Phoenix is only offering us a ploy!}
{124}{}{Don't get caught in the hooks of the missionaries!}
{125}{}{Cover your ears when those missionaries try explaining something to you.}
{126}{}{We have lived here for many generations! We won't give up our land to outsiders!}

#Interrupting dialogue for the bike
{200}{}{This! This is what I was talking about! The outsiders have conquered metal! Playing God, they resurrected ancient technologies and subjugated them for their purposes. What next? Will they subjugate our bodies and souls as well?}
{201}{}{There's no need to worry. This is my bike. I use it to travel. It is no threat to you.}
{202}{}{Don't believe the words of the outsider! Who knows the true intentions of someone who goes against nature.}
{203}{}{Calm down, you're making assumptions left and right.}
{204}{}{I think you've been smoking the wrong stuff, shaman.}
{205}{}{Calm down, old man. I didn't do anything bad to you. YET.}
{1205}{}{Calm down, old man. I didn't do anything bad to you. YET.}

#First encounter
{210}{}{...Here, look what those 'advanced' people brought us with their 'progress'!}
{211}{}{[Listen to the speech]}
{212}{}{[Interrupt the speech]}
{213}{}{We were a tightly-woven community, and then the fire-worshippers brought us egoism! We used to believe in one God, but they have taught us to quarrel over religion! We only wanted good to come to our fellow man, but the clans have once again begun walking down the path of hostility...}
{214}{}{Phoenix has taught us to exchange brahmin like mere items, even though those animals are sacred. How many more of our traditions will the outsiders destroy? How much more quarreling will they cause within the tribe with their mere arrival in our lands?}
{215}{}{And now look at Chatto. He has learned to read heathen texts from the caravaneers. Reading! He says we should exchange our brahmin for the soulless technologies of the outsiders. He and his little buddies want to trade away our freedom for an alliance with Phoenix. They want to give away the pueblo to the missionaries!}
{216}{}{Look at those heathen things - books, technologies, questionable and dangerous substances... We have always rejected them, for they bring danger, for there is nothing more valuable than the lives of the tribe and it's brahmin. And now Chatto, together with his associates, is collecting heathen talismans and is trying to interpret them. The Dark Brahmin has taken control of the minds of our young generation!}
{217}{}{Is that our future? Have we fallen so low that even the youth is going against the tribe? It is the fault of the missionaries! We must drive them away! The pueblo must remain ours...}
{218}{}{Oh. I see an outsider. Who are you? What you doing in our tribe?}
{219}{}{Oh. I see a fire-worshipper. What do you want to do with us? Take away our children and our brahmin? We have told your predecessors that the tribe of San Brahmin cannot be bought like the other tribes you have taken over. Go away to your wicked Phoenix, heathen!}
{220}{}{I am going to the chieftain to represent Villa. I was allowed inside by Nana.}
{221}{}{Ah, the Holy Brahmin of Peace and Quiet! If Nana allows an outsider, there must be a reason. Alright, you can go. But keep in mind that nothing hides from my keen gaze. I will watch every step you make in our pueblo.}
{222}{}{Thank you, Mangas. Please forgive me for my intrusion.}
{223}{}{Old age has driven you insane. Leave me alone and move out of the way.}
{224}{}{Until next time, Mangas.}
{225}{}{[Continue]}

#Repeat dialogue
{230}{}{I greet you, outsider from Villa.}
{1230}{}{I greet you, woman from Villa.}
{231}{}{I am concerned about your dark spirit being on my tribe's land.}
{232}{}{Until next time, shaman.}

{240}{}{Who are you?}
{241}{}{My name is Mangas. I am the chieftain of the eastern clan.}
{242}{}{Nice to meet you, Mangas, chieftain of the eastern clan.}
{1242}{}{Nice to meet you, Mangas, chieftain of the eastern clan.}
{243}{}{I suppose you are the leader of this place, chieftain?}
{244}{}{Supreme leader Jeronimo is our leader. He is located in the Sanctuary. The chieftains of every clan have convened in San Brahmin and chose him as our representative.}
{245}{}{Then why are you here and not in the east?}
{246}{}{To resist against the warriors of Phoenix. The entire tribe has converged here to maintain our freedom and the things we hold dear. And this pueblo was always our shelter during times of drought and dust storms.}
{247}{}{Did your people build this pueblo? It looks ancient.}
{248}{}{There were always ruins here, as far as I know. The sand has covered them over many generations, and now nobody knows how this place truly looked like when it was built. But right now, it is our main camp.}
{249}{}{Alright, let's talk about that later.}

{250}{}{What's going on here?}
{251}{}{Chatto and other youngsters were collecting forbidden items. I found them and am going to burn them down so they will not bring others harm. And don't you think about bringing us more of them. It is none of your business, Villa outsider.}
{1251}{}{Chatto and other youngsters were collecting forbidden items. I found them and am going to burn them down so they will not bring others harm. And don't you think about bringing us more of them. It is none of your concern, Villa woman.}
{252}{}{Alright.}
{253}{}{But what is so bad about these things?}
{254}{}{We travel through the desert and survive on what the desert gives us. Our people and our herds are the only things that are valuable. There is no point in our young generation becoming comfortable with Old World things. They are unsafe and bring no benefit.}
{255}{}{Whatever you say. Can I take them?}
{256}{}{Your actions make no sense. These are just old things, there's plenty of them near ruins.}
{257}{}{We don't live near ruins! We travel through the Sonora desert. Our people and our herds are the only things that are valuable to us. There is no point in our young generation becoming comfortable with Old World things. They are unsafe and bring no benefit.}
{258}{}{Whatever you say. How about some barter? I could bring them back to the ruins.}
{259}{}{You're doing the right thing. We lack people like you in Villa, shaman Mangas. Please accept my words of respect.}
{260}{}{Hm-m. If you truly are from the Villa I heard of, then I should be more respectful toward you. Perhaps our tribes are similar. In some ways.}
{261}{}{You shouldn't burn down those things. Let me give you something in exchange for them. I'll bring them to some other place far away from here.}
{262}{}{I don't care what happens to heathen talismans. It is much more important to teach dissenters a lesson and show the truth to the rest. But I would be stupid to reject your proposal, if you truly have something to offer.}
{263}{}{I think we can reach an agreenment.}
{264}{}{All those things truly are unsafe for you.}
{265}{}{Exactly! The things of the outsiders bring only pestilence, chaos and death.}
{266}{}{Burn it all down! Immediately! Especially this. [Point at grenade]}
{267}{}{You are doing a big service to your entire tribe.}
{268}{}{Want to exchange it for something useful?}
{269}{}{Look at this thing filled with demonic power! Destroy it right now! [Throw a grenade into the fire]}

{270}{}{You said something about a conflict with outsiders?}
{271}{}{They bring discord and division to our tribe. Their soulless technologies are incompatible with our values. They're trying to subjugate us with their weapons so that we will do forced labor for them. Our people even argue over fiery water now.}
{272}{}{Alright. Can I ask something else?}
{273}{}{So, what are the groups that are fighting each other?}
{274}{}{The missionaries from Phoenix want an alliance with us and to gain control over land near the pueblo. The young generation is listening to them, the rest are trying to drive them away.}
{275}{}{What kind of weapons do you have against outsiders?}
{276}{}{They have fire-breathing sticks and strong metal armor. We cannot hope to defeat such an army with our arrows. Only cunning tactics and knowledge of local terrain can let us fight against such a powerful enemy.}
{277}{}{What soulless technologies are you talking about?}
{278}{}{Old things the power of which comes from other old things. You call them "powersells" and "raydiation". For a long time, nobody in the tribe even dared touch them. And now they are manufactured in Phoenix and Two Sun as easily and shrewdly as we manufacture bags from the skin of brahmin.}
{279}{}{Fiery water?}
{280}{}{That bitter, smelly liquid has come to us from Phoenix. It clouds the mind like the Dark Brahmin. Those who drink that water do strange things. I am trying to burn any of it I find, but so far it is all in vain. Until Phoenix stops manufacturing and selling the drink, such crapulence will not be stopped.}
{281}{}{I'm sure there has to be an entire moonshine distillery devoted to creating it in Phoenix.}
{282}{}{Without tequila, our tribe would have a much easier time resisting outsiders. If you will sabotage its production, I will reward you accordingly.}
{283}{}{Good. I'll do it.}
{284}{}{I will give gifts to the Holy Brahmin so that it will guide and shield you in your travels. Good luck, my friend.}
{285}{}{Until next time, Mangas.}
{286}{}{Wait, I want to know about something else.}
{287}{}{I'm sure it's full of guards. And I don't even know where that distillery is. So, no, I won't disturb the alcohol industry.}
{288}{}{Then get out of here. You're wasting my time.}

{290}{}{I carry good news, Mangas! The alcohol industry in Phoenix is effectively destroyed.}
{291}{}{The Holy Brahmin itself must have helped you in this hard mission. I see now that I was mistaken in my treatment of you. Not all outsiders are trying to subjugate or steal from us. Thank you, my friend from Villa.}
{292}{}{You're welcome.}
{293}{}{You also said something about a reward, I think.}
{294}{}{You deserve respect *and* a reward. Take these old things that I recently took away from other members of the tribe. I am sure you will find a use for them.}
{295}{}{Let's take a look. Atomic batteries, stimpaks, radaway and a bunch of caps... Pretty good.}

{300}{}{...Is this our future? Have we fallen so low that even the youth is going against the tribe? It is all the fault of those missionaries from Phoenix...}
{301}{}{It's too late to cry out about freedom, Mangas. The chieftain has already made an alliance with Phoenix.}
{302}{}{I think about the future of the tribe, and I feel great sadness. It is an uncertain future. We are just like a lost brahmin that has strayed from the herd. This is tragic. Very tragic.}
{303}{}{Uh-uh. So long.}

{310}{}{I want you to support an alliance with the Phoenixian missionaries.}
{311}{}{You're delirious, my friend. I am trying to drive away outsiders from our lands with spells and by enlightening the minds of my fellow people. And you ask me to end that and surrender to the will of the Brahmin of Fate?}
{312}{}{That's about right.}
{313}{}{It really was a bad idea, now that I think about it.}
{314}{}{What is wrong with you, outsider from Villa? It looks as if our tribe and your village are one step away from war. Is that not so?}
{1314}{}{What is wrong with you, woman of Villa? It looks as if your village and our tribe are one step away from war. Is that not so?}
{315}{}{Unfortunately, Mangas, you are detached from reality. The world is changing and living like people lived in the past is not an option anymore.}
{316}{}{And now you reveal your true self. If your tribe is so weak, sure, go for it. But WE won't allow ourselves to be brought under Aaron's heel!}
{317}{}{That was not very wise of you, Mangas. You will remember my words.}
{318}{}{Oh, sure. And as for me, I think my time to leave has come.}
{319}{}{Listen to me, Mangas. Look around you. The world is changing. The tribe has to change with it, or it will be wiped off the face of the earth.}
{320}{}{I fear the destruction of my tribe. But you say that, as if we will be allowed to exist in that new world. We will still be destroyed. Is it not so?}
{321}{}{Make an alliance with Phoenix and you will keep your traditions. If you choose to remain on the side of the Rangers, you will only doom your tribe to a war you have no chance of surviving.}
{322}{}{I don't know. You will have to choose for yourself. Goodbye.}
{323}{}{The tribe has managed to resist missionaries and bandits so far. But their ever-increasing strength makes that harder and harder every day. Even united, the tribe barely maintains it's hold on San Brahmin.}
{324}{}{So be it. For the survival of my clan, I will support this alliance. But I will not break the alliance with the Rangers. And we will break all agreements with Phoenix at the first sign of betrayal.}
{325}{}{A wise choice.}
{326}{}{You have no choice. Phoenix will win in the end.}
{327}{}{Trust me. The Rangers are not your friends, and Phoenix will always win in the end. You have no choice. If you do not establish an alliance with Phoenix, your tribe will become one with the sand.}
{328}{}{I listen to your words and feel more crushed by the minute... Is it really so hopeless that even Villa is ready to surrender to Phoenix? Then we truly have no choice.}
{329}{}{I don't know anymore, Mangas... I need to collect my thoughts.}
{330}{}{Of course. And until then, unless you convince me otherwise, I will support an alliance with the Rangers. They are the ones who truly wish us well.}
{331}{}{Alright. Goodbye.}
{332}{}{What if I bring you evidence of their treachery?}
{333}{}{Well, I will listen to it. But don't dare lie to me.}
{334}{}{Alright. Goodbye.}
{335}{}{The Rangers are scattered and weak. Their dam is destroyed.}
{336}{}{Oh, why is the Holy Brahmin of Fate so cruel!}
{337}{}{They are now concerned with their own survival. You should not expect any help from them.}
{338}{}{The Rangers have already exterminated the tribe of the Jackals. Your tribe could be next.}
{339}{}{They destroyed an entire tribe? Oh, why is the Holy Brahmin of Fate so cruel!}
{340}{}{You are all just savages to the youth.}
{341}{}{There was a convoy of civilians traveling through your lands in Garage City. The Rangers treacherously stole from them.}
{342}{}{What strange things has the Holy Brahmin of Fate prepared?}
{343}{}{The migrants simply refused to do as they said. They do it to everyone who doesn't follow their rules.}