{100}{}{You see priestess Nana.}
{101}{}{You see a priestess in tribal attire.}
{102}{}{Go away. We do not fear you or your iron toys.}

#First encounter
{200}{}{Stop. We no longer allow outsiders into the pueblo.}
{201}{}{Stop, outsider. We warned you that your group must leave our lands. Why do you continue to disturb us?}
{202}{}{I don't know what you are talking about. I'm pursuing a convoy with slaves from Villa. I was thinking it could have passed through this place.}
{203}{}{So you're from Villa? I've heard about your village! We never quarreled. But neither did we befriend one another.}
{204}{}{I also didn't know anything about you.}
{1204}{}{I also didn't know anything about you.}
{205}{}{Then we should learn more about each other.}
{206}{}{So, you too have suffered the same tragedy that has fallen upon so many others? I'm very sorry, but your people aren't here.}
{207}{}{You are also concerned about slavers?}
{208}{}{There might be a chance that the peasants of Villa are being held here. Don't even think about interrupting my search.}
{209}{}{So you're from Villa? I heard about your village. We never quarreled. Let's not start quarreling now.}
{210}{}{If you know where the slavers are holding my people, say it.}
{211}{}{So the slavers have overwhelmed your village as well? I'm very sorry. You are not the first ones to suffer this fate. But you won't find your people here.}
{212}{}{You are also concerned about slavers?}
{213}{}{Madre... padre... I just want to go home!}
{214}{}{O-ooh, poor child. The Dark Brahmin of Radiation must have cursed the seed of your father. I am sorry for you.}
{215}{}{Brah-min? No, no, padre is called Andres!}
{216}{}{Go to our chieftain, Jeronimo. Talk to him. He is wise and may be able to help you.}
{217}{}{Me go to old man.}

{220}{}{They call themselves missionaries. They march into our lands and make us follow their rules. The tribe is resisting, but the cost of maintaining our freedom is an ever-rising one. We are on the verge of war with the Phoenixians.}
{221}{}{The Wastes are vast and full of space. What resources can't you share?}
{222}{}{They want to subjugate us for our brahmin and cheap labor. But we are not such weak-willed brahmin that will do what any man with a whip tells us to do.}
{223}{}{We are similar. Villa also values it's own freedom. But it was taken away from us with force.}
{224}{}{Then we should listen closely to each other. Talk to our chieftain Jeronimo. He refuses to talk with outsiders. But you are from a neighboring tribe. And neighbors should listen to one another.}
{225}{}{Good. Where do I find this chieftain?}
{226}{}{Walk to the big house with columns. I will report your arrival to the chieftain. But do not disturb others until you gain our trust.}
{227}{}{Alright. Until we meet again.}
{228}{}{I'm looking for Ranger Oscar. I was sent here to assist him.}
{229}{}{The Rangers have done much to help us maintain our freedom. But tensions have become so high that we are now at the verge of war with the missionaries. You must talk about this with our chieftain, Jeronimo.}

{230}{}{What did Jeronimo say?}
{231}{}{I haven't talked to him yet.}
{1231}{}{I haven't talked to him yet.}
{232}{}{Talk to Jeronimo. I will not discuss anything with you until he gives you permission to stay.}
{233}{}{Alright.}
{234}{}{Can't we have that discussion right now, before I talk to Jeronimo?}
{235}{}{No.}
{236}{}{Fine.}
{237}{}{Where do I find the chieftain?}
{238}{}{In the big illuminated building with columns. Just continue walking forward. You won't miss it.}
{239}{}{Alright.}
{240}{}{He has proposed to ally against Phoenix.}
{241}{}{A wise proposal. This problem affects not only our tribe, but your Villa as well. I hope you'll help us solve it.}
{242}{}{I'll see what I can do.}

#Repeat dialogue
{250}{}{I am listening to you, peasant of Villa.}
{1250}{}{I am listening to you, peasant of Villa.}
{251}{}{Speak, peasant of Villa.}
{1251}{}{Speak, peasant of Villa.}
{252}{}{I should go. Until next time, Nana.}

{260}{}{I'm asking you to support an alliance with the Phoenixian missionaries.}
{261}{}{I did not expect you to side with them. I see no reason to hug the serpent. Phoenix will betray our tribe the moment that will bring it benefit.}
{262}{}{I don't know. You may be right.}
{263}{}{Open your eyes - Phoenix will be better for the tribe as a whole than the Rangers.}
{264}{}{We have lived our entire lives without Phoenix. We do not need it. I am against this alliance.}
{265}{}{You'll regret this, mark my words.}
{266}{}{Alright. Let's not argue.}
{267}{}{The Rangers are treacherous - they use your tribe to fight their wars. Phoenix, meanwhile, is offering a mutually-beneficial commercial alliance, and the means to solve many of your problems.}
{268}{}{Hmm. I have not thought about it like that before. Alright. You can count on my vote in the Council of Elders.}
{269}{}{You won't regret your choice.}
{270}{}{Terrific, just what I needed.}
{271}{}{An alliance with Phoenix would provide you with the means to solve many of your problems.}
{272}{}{Perhaps that is true. But if we become part of an empire, we will lose what makes us, well... us. And more importantly - we will be defenseless against outsiders. What will we do if they betray us? How will we defend ourselves?}
{273}{}{You need weapons that will work against the Phoenixians.}
{274}{}{Exactly. The kinds of weapons they won't give us. If we had those fire-spewing things that kill a healthy man in one shot, we wouldn't have anything to fear from an alliance.}
{275}{}{I'll bring you three hunting rifles. In exchange, you will support this alliance in the Council of Elders.}
{276}{}{Let it be so. Bring us the weapons of the outsiders and I will support your proposal.}
{277}{}{Agreed.}
{278}{}{Alright.}
{1278}{}{Alright.}
{279}{}{Alright. I'm always carrying various different weapons.}

{280}{}{I have the weapons.}
{281}{}{Show them to me.}
{1281}{}{Show them to me.}
{282}{}{Not right now.}
{283}{}{.}
{290}{}{Good, but this is not enough.}
{291}{}{I'll bring you some more.}
{292}{}{Good. This is enough. You can count on my support in the Council of Elders.}
{293}{}{And Jeronimo made an alliance with the Rangers still. I shouldn't have listened to you.}
{294}{}{It turned out that we were both mistaken. It happens.}
{295}{}{That mistake could cost someone their life. Think about that as best you can.}
{296}{}{Uh-uh. Bye.}
{297}{}{Ah, sorry. I forget that you savages are so used to chieftains deciding everything for you that you don't use your own brains.}
{298}{}{I will tell the Holy Brahmin to send snakes under your feet in your travels.}
{299}{}{Uh-uh. Bye.}

#Questions
{310}{}{Who are you?}
{311}{}{I am Nana, the priestess of the southern clan of my tribe.}
{312}{}{Nice to meet you, Nana.}
{313}{}{Are there other priestesess?}
{314}{}{Right now, only I, Henaro, Mangas and the supreme leader Jeronimo are present in the pueblo.}
{315}{}{Tell me about Henaro.}
{316}{}{He presides over the yards where the brahmin live and ocasionally walks out into the Wastes. That is why he knows the most about outsiders from Phoenix and the way they do things.}
{317}{}{Tell me about Mangas.}
{318}{}{Be careful with Mangas. He is very impatient when it comes to anything or anyone that breaks our traditions.}
{319}{}{Tell me about chieftain Jeronimo.}
{320}{}{He is a great chieftain. He has united the scattered tribe in the face of a new enemy. Before him, the tribe quarreled over the distribution of land. Now we live like one family.}
{321}{}{I've met this Chatto guy. What can you tell me about him?}
{322}{}{He's the son of the chieftain - making him quite important in the pueblo. The youth support him. They all collectively want change. I do not particularly like that.}
{323}{}{Alright.}