{100}{}{You see the priest Mangas.}
{101}{}{You see a shaman in a national outfit.}
{102}{}{Look! That evil iron spirit! Do you believe me now?}
{103}{}{Old man Mangas is completely out of his mind!}

#Floating phrases on the square
{110}{}{Drive the outsiders away!}
{111}{}{Outsiders are dividing our tribe!}
{112}{}{Look what these outsiders are doing to our community!}
{113}{}{We have kept traditions for so many generations not for outsiders to destroy them!}
{114}{}{Now there are dissenters among us. What will it lead to?}
{115}{}{The tribe is once again on the path of enmity. And it's all because of the Phoenix.}
{116}{}{We were one, but Phoenix taught us to argue over nothing!}
{117}{}{Look at Chatto and his comrades. There is no way to fix them!}
{118}{}{Chatto learned to read from the caravaneers. And what will happen next?}
{119}{}{It will get worse! Phoenix won't give us the wasteland. Aaron needs everything!}
{120}{}{Because of the missionaries, we can't even gather in the wasteland to graze Brahmins.}
{121}{}{Bring all the things of the pagans here! Burn them! Burn!}
{122}{}{Look at these books and technologies - do we really need this?}
{123}{}{Phoenix promises only deception!}
{124}{}{Don't fall for the tricks of the missionaries!}
{125}{}{Cover your ears when the missionaries explain something to you.}
{126}{}{We've lived here for generations! We will not give our land to strangers!}

#Stop-dialogue about the bike
{200}{}{Here! That's what I was talking about! Outsiders have conquered iron! Playing God, they resurrected old technologies and subordinated them to their will. And what's next? Will they subdue our bodies and souls?}
{201}{}{Don't worry so much. This is my personal transport. He's not threatening you.}
{202}{}{Do not believe the words of a stranger! Who knows what's on the mind of someone who goes against nature.}
{203}{}{Be simple, you're driving too hard.}
{204}{}{In my opinion, you smoked the wrong herb, shaman.}
{205}{}{Calm down, old man. I haven't done anything wrong to you. NOT done YET.}
{1205}{}{Calm down, old man. I haven't done anything wrong to you. I haven't done it YET.}

#First meeting
{210}{}{...Here, look at what these advanced people have brought us with all their progress!}
{211}{}{[Listen to speech]}
{212}{}{[Interrupt speech]}
{213}{}{We were a close-knit community, but the fire worshippers brought us selfishness! We believed in one god, but they taught us to argue about religion! We wanted to do good to our fellow tribesmen, but the clans have once again entered the path of enmity...}
{214}{}{The Phoenix taught us to trade brahmins as objects, although these animals are sacred. How many more outsiders will destroy our foundations? How many more feuds within the tribe will they cause just by their appearance in our lands?}
{215}{}{Now look at Chatto. He learned to read pagan texts from the caravaneers. Reading! He calls for the Brahmins to be exchanged for the soulless technology of outsiders. He and his friends want to trade our freedom for an alliance with Phoenix. They want to put the pueblo in the hands of missionaries!}
{216}{}{Look at these pagan things - books, technology, dubious and dangerous substances... We have always rejected them because they are dangerous, but there is nothing more valuable than the life of the tribe and the Brahmins. And now Chatto, along with his companions, collects pagan talismans and tries to read them. The Dark Brahmin has taken over the minds of our youth!}
{217}{}{And this is our future? When did we fall so low that even the youth goes against the tribe? The missionaries are to blame for this! Drive them away! The pueblo must remain ours...}
{218}{}{Oh, I see a stranger in the pueblo. Who are you? What are you doing in a strange tribe?}
{219}{}{Oh, I see a fire worshipper in the pueblo. What do you want? Take away our children and our brahmins? We have already answered your predecessors that the San Brahmin tribe cannot be bought, as you have done with the rest. Get back to your stinking Phoenix, pagan!}
{220}{}{I am going to the chief on behalf of the Villa. Nana missed me.}
{221}{}{Ah, the Divine Brahmin of Peace! If Nana lets in an outsider, there must be a reason. Okay, come on in. But keep in mind that nothing will hide from my eagle eye. I'll be watching your every move in the pueblo.}
{222}{}{Thank you, Mangas. Please don't be angry with me for my intrusion.}
{223}{}{You're just crazy in your old age. Leave me alone and let me pass.}
{224}{}{See you, Mangas.}
{225}{}{[Next]}

#Repeat dialog
{230}{}{Greetings, stranger from the Villa.}
{1230}{}{Greetings, women from the Villa.}
{231}{}{I am troubled by your dark spirit on the land of my tribe.}
{232}{}{See you later, shaman.}

{240}{}{Who are you?}
{241}{}{My name is Mangas. I am the chief of the Eastern clan.}
{242}{}{Glad to meet you, Mangas, chief of the Eastern tribe.}
{1242}{}{Glad to meet you, Mangas, chief of the Eastern tribe.}
{243}{}{I guess you're in charge here, Chief?}
{244}{}{You're talking about the supreme leader Geronimo. He is in the Sanctuary. The leaders of each clan gathered in San Brahmin and chose him as our representative.}
{245}{}{Then why are you here and not in the east?}
{246}{}{The fight against the troops from Phoenix forced the whole tribe to gather in San Brahmin to defend our freedom and our values. Besides, this pueblo has always been our seasonal haven during dust storms and droughts.}
{247}{}{Did you build this pueblo? It looks very ancient.}
{248}{}{There have always been ruins here for as long as I can remember. Sand has covered them for many generations, and no one knows what this place was like before. Now this is our main camp.}
{249}{}{OK, but we'll do it later.}

{250}{}{What's going on here?}
{251}{}{Chatto and the other boys were collecting forbidden things. I've found them and I'm going to burn them so that the others won't be offended. And don't you dare bring us new ones. It's none of your business, stranger from the Villa.}
{1251}{}{Chatto and other boys collected forbidden things. I've found them and I'm going to burn them so that the others won't be offended. And don't you dare bring us new ones. It's none of your business, the woman from the Villa.}
{252}{}{I see.}
{253}{}{But what's wrong with these old things?}
{254}{}{We wander through the desert and live by what the desert gives us. Our people and our herds are the only valuable thing. There is no need for young people to join the things of the Ancient World. It's useless and unsafe.}
{255}{}{Whatever you say. Can I take these things?}
{256}{}{You're doing some nonsense. These are just old things, there are a lot of them on the ruins.}
{257}{}{But we don't live on those ruins! We are wandering through the Sonoran desert. Our people and our herds are the only thing that is valuable to us. There is no need for young people to join the things of the Ancient World. It's not safe.}
{258}{}{Whatever you say. How about an exchange? I can take them from here back to the ruins.}
{259}{}{You're doing the right thing. We don't have enough people like you in the Villa, Shaman Mangas. Accept the words of respect.}
{260}{}{Hmm. If you truly are from the Villa I've heard about, then I should treat you more favorably. Perhaps our tribes are somewhat similar.}
{261}{}{It's not worth burning these things. Let me exchange them and take them away from here.}
{262}{}{I don't care what happens to pagan talismans. It is much more important to teach the apostates a lesson and show the rest the truth. But I don't mind getting a benefit from the exchange if you really have something to offer.}
{263}{}{I think we can negotiate.}
{264}{}{All these things are unsafe for you.}
{265}{}{That's what I'm talking about! The things of strangers bring disease, discord or death.}
{266}{}{Burn everything! Immediately! Especially this one. [Point to the grenade]}
{267}{}{You're doing a great job for your tribe.}
{268}{}{Do you want to exchange for something useful?}
{269}{}{Look, this thing is endowed with demonic power! Destroy it immediately! [Throw a grenade into the fire]}

{270}{}{What is the conflict with outsiders?}
{271}{}{They bring turmoil and discord to the tribe. Their soulless technologies contradict our precepts, and with their weapons, outsiders are trying to conquer us and force us to work. Even the firewater has become a subject of contention.}
{272}{}{I see. Let me ask you something else?}
{273}{}{Turmoil and discord? Who is against whom?}
{274}{}{The Phoenix missionaries want a union and a place near the pueblo. The youth echoes them, the others drive them away.}
{275}{}{What kind of weapons do strangers have?}
{276}{}{The aliens have fire sticks and durable metal armor. We cannot resist with our spears against such an army. Only cunning and knowledge of the wasteland help us fight against such a strong enemy.}
{277}{}{What soulless technologies are you talking about?}
{278}{}{Old things whose power comes from other old things. You call it "bat-tare" and "radiation". For a long time, no one from the tribe dared to even touch these things. And now in Phoenix and Two-Sun, they make them as easily and deftly as we make bags made of brahmin leather.}
{279}{}{What kind of firewater is this?}
{280}{}{This bitter smelly liquid came to us from Phoenix. She stupefies the head, like a Dark Brahmin. Those who drink this water do strange things. I try to burn all the supplies I find, but it's in vain. Until Phoenix stops producing and selling the tribe's drink, the general hangover will not stop.}
{281}{}{There's probably a whole moonshine distillery doing it in Phoenix.}
{282}{}{I have been looking for a long time for a person who will find and destroy this plant. Without tequila, it will be easier for our tribe to resist outsiders. Do this and I will reward you handsomely.}
{283}{}{Good. I'll do it.}
{284}{}{I will bring offerings to the Divine Brahmin to guide and protect you on the road. Good luck, my friend.}
{285}{}{See you, Mangas.}
{286}{}{Wait, I want to know something else.}
{287}{}{There must be a lot of security there. And I don't even know where this factory is. No, I will not interfere with the alcohol business.}
{288}{}{Then go. You're wasting our time.}

{290}{}{Rejoice, Mangas! The moonshine distillery in Phoenix has been destroyed.}
{291}{}{The Divine Brahmin himself must have helped you in this difficult task. Now I see that I was wrong in my attitude towards you. Not all outsiders are trying to subdue us or steal from us. Thank you, my friend from the Villa.}
{292}{}{You're welcome.}
{293}{}{Did you say something about a reward?}
{294}{}{You deserve respect and reward. Take these old things that I recently took away from the tribesmen. Surely you will find a use for all this.}
{295}{}{So, so, nuclear batteries, stimpacks, Radawaye, and a bunch of caps... Pretty good.}

{300}{}{...And this is our future? When did we fall so low that even the youth goes against the tribe? The Phoenix missionaries are to blame for this...}
{301}{}{It's too late to shout about freedom, Mangas. The chief has allied with the Phoenix. Accept it.}
{302}{}{I look with grief at the future of the tribe. It's covered in fog. We are like a lost brahmin strayed from the herd. Sadly. Very sad.}
{303}{}{Yeah. Be there.}

{310}{}{I'm asking you to advocate for an alliance with the Phoenix missionaries.}
{311}{}{You're delusional, my friend. I am trying to expel outsiders from our land with spells and enlightenment of the minds of my fellow tribesmen. And you ask me to stop and surrender to the will of the Brahmin of Fate.}
{312}{}{That's right.}
{313}{}{If you think about it, it sounds really crazy.}
{314}{}{What's wrong with you, stranger from the Villa? It seems that your village and our tribe are on the same side on the warpath. Isn't that right?}
{1314}{}{What's wrong with you, Villa woman? It seems that your village and our tribe are on the same side on the warpath. Isn't that right?}
{315}{}{Unfortunately, Mangas, you are out of touch with reality. The world is changing, and it's still impossible to live anymore.}
{316}{}{Now you're showing your true face. If your tribe is so weak, let it. But WE will not bend under strangers from Phoenix!}
{317}{}{In vain. You'll remember my words later.}
{318}{}{You know best. And I'm leaving.}
{319}{}{Unfortunately, Mangas, you are out of touch with reality. The world demands change. Otherwise, the tribe will be wiped off the face of the earth.}
{320}{}{Strong words. They make your hamstrings shake with fear. But if we bend under the New World, we will disappear anyway. Isn't that right?}
{321}{}{Ally with the Phoenix and you will keep your traditions. If you stay with the Rangers, you will only condemn yourself to a war with complete defeat.}
{322}{}{I don't know. Decide for yourself. Bye.}
{323}{}{The tribe has so far managed to resist missionaries and bandits. But their increasing power presses us more and more. Even united, the tribe barely holds on to the San Brahmin.}
{324}{}{So be it. For the sake of saving my clan, I will stand for the union. But I will also maintain an alliance with the Rangers. And at the first sign of a threat, we will break all agreements.}
{325}{}{A reasonable solution.}
{326}{}{You have no choice. Phoenix will win anyway.}
{327}{}{Trust me. Rangers are not your friends, and Phoenix will win anyway. You have no choice, otherwise you will perish in the sand.}
{328}{}{I listen to your words and I am more and more grieved... Is it really so bad that even the Villa is ready to bend under the Phoenix? Then we really have no choice.}
{329}{}{I don't know anymore, Mangas... I need to collect my thoughts.}
{330}{}{Of course. And until you convince me otherwise, I will speak at the council for an alliance with the Rangers. They are the ones who wish us well.}
{331}{}{Okay. Bye.}
{332}{}{And if I bring you proof of their treachery?}
{333}{}{Well, I will listen. But don't you dare lie to me.}
{334}{}{Okay. Bye.}
{335}{}{The Rangers are defeated. Their dam is destroyed.}
{336}{}{Oh, why is the Divine Brahmin of Fate so cruel!}
{337}{}{Now they are busy with their own survival. It is hardly worth waiting for help from them.}
{338}{}{The Rangers have already destroyed the Jackal tribe. You can be next.}
{339}{}{The whole tribe was destroyed? Oh, why is the Divine Brahmin of Fate so cruel!}
{340}{}{To these tough guys, all of you are just savages.}
{341}{}{A convoy of civilians was passing through your lands to Garage City. The Rangers treacherously robbed them.}
{342}{}{What kind of oddities did the Divine Brahmin of Fate have in store for them?}
{343}{}{The migrants simply refused to follow their demands. They do this to everyone who does not obey them.}
