{100}{}{You see the priest Genaro.}
{101}{}{You see a shaman in a national outfit.}
{102}{}{Go in peace, strange iron spirit.}

{200}{}{Greetings to you and your tribe. Aren't people whispering about you in San Brahmin? I don't know how to treat you, but I don't mind your presence.}
{201}{}{Really?}
{202}{}{You've made me happy, old man.}
{203}{}{I often do business with outsiders from the east, unlike the rest of the clans of the tribe. Time will tell if you can be trusted.}
{204}{}{Thank you for your hospitality.}
{205}{}{It's too rude for a first greeting.}

{210}{}{That thing you're driving has scared all my brahmins away! Choose a different road next time, you idiot.}
{1210}{}{That thing you're driving has scared all my brahmins away! Next time, choose a different road.}
{211}{}{Please forgive me. I didn't want to cause you any problems.}
{1211}{}{Please forgive me. I didn't want to cause you any problems.}
{212}{}{Your problem. It's not my fault that your brahmin are so skittish.}

{220}{}{I see you're not going to leave the pueblo. What's keeping you here, friend?}
{221}{}{I see you're not going to leave the pueblo. What's on your mind?}
{222}{}{Greetings, friend of the eastern tribe. How can I help you?}
{223}{}{See you later, Genaro.}

{230}{}{I ask you to advocate for an alliance with the Phoenix missionaries.}
{231}{}{Unlike the other elders, I have no prejudice against outsiders from Phoenix. My clan spent quite a lot of time with them, doing trade. But I'm not ready to go against the rest of the tribe. Maybe it's not time yet.}
{232}{}{If the elders are not convinced, then the war will not end.}
{233}{}{You underestimate the tribe. We have a wealth of combat experience and we know the Sonoran wasteland well. The Phoenix Army will be mired in this struggle for a long time, if it decides to go to the end at all.}
{234}{}{Your words sound convincing. Forget what I told you.}
{1234}{}{Your words sound convincing. Forget what I told you.}
{235}{}{You're condemning your tribe to war. Mark my words.}
{236}{}{Perhaps it is your voice that is not enough to change something. You don't want a war with the Phoenix, do you?}
{237}{}{The tribe can stand up for itself, but this war will be endless. And someday it will end in defeat before the growing technologies of missionaries.}
{238}{}{Do you agree with me?}
{239}{}{I'm not averse to trading with Phoenix myself. The other elders don't understand that the world has changed. It is better now to enter a new era with full strength than to condemn our people to a century-long war. You can count on my support at the council of Elders.}
{240}{}{You're making the right choice, Chief Genaro.}
{241}{}{Well, you can understand...}
{242}{}{You saved the children and cattle from the evil spirit. How can I refuse your request after that?}
{1242}{}{You saved the children and cattle from the evil spirit. How can I refuse your request after that?}
{243}{}{So I can count on you?}
{244}{}{Perhaps the Divine Brahmin punished me by taking the life of a sacred brahmin right before the celebration of the Day of the Sun. It's a sign. So he points out to me that I have chosen the wrong path.}
{245}{}{Now you know what to do, don't you?}
{246}{}{Great. But let's not rush things. Bye.}
{247}{}{It is sad. But let's not rush things, okay?}

{250}{}{Tell me about yourself.}
{251}{}{I am the elder of the western families of our tribe. And my name is Genaro.}
{252}{}{Hello, Elder Genaro.}
{253}{}{And who is responsible for the rest?}
{254}{}{The supreme leader of the tribe is Geronimo. He is a wise and experienced strategist, a great unifier of the tribe. You'll find him in a big house with columns.}
{255}{}{What are you doing here?}
{256}{}{I spend a lot of time in San Brahmin. We need to keep an eye on the Brahmins after their grazing, and prepare them for their future fate, after all, I arrange holidays on the day of the Big Sun. And I have more and more work, I can barely cope.}
{257}{}{I see.}
{258}{}{Can I help you?}
{259}{}{Didn't you have to cultivate maize before? So, working with the land should not be a burden for you. Take a shovel in the paddock and clean it from... brahmin filth. Brahmins must be clean while they are in captivity. Especially the ones I chose to celebrate the Day of the Sun.}
{260}{}{Okay. I will do it. I hope you will at least feed me fresh brahmin meat for this.}
{261}{}{What about? Cleaning up the shit behind the Brahmins?}
{262}{}{Isn't this a common thing for you? Well, I can't offer you another job. You can hardly handle the dressing of hides or the care of Brahmins. To be honest, I try not to let strangers into the pen at all. It's a pity that you don't appreciate the trust placed in you.}
{263}{}{I think you're just kidding me. Look for fools.}
{264}{}{The pen is cleared.}
{265}{}{I see. You did a good job.}
{1265}{}{I see. You did a good job.}
{266}{}{Are you kidding me? I'm up to my ears in brahmin shit!}
{267}{}{Oh, thank you, I love doing my job flawlessly.}
{268}{}{For such work, it's not a pity to feed and give a bed in my tent. Take this jerky. It satisfies hunger well on the road and does not spoil for a very long time.}
{269}{}{Thank you.}
{270}{}{Don't laugh at my back.}

{280}{}{There were rumors in our Villa about the Vaquero tribe that graze cattle.}
{281}{}{Hmm?}
{282}{}{These stories caused a lot of confusion. How did you manage to tame the rabid Brahmins?}
{283}{}{Come on, forget it.}
{284}{}{They weren't always like that. A few generations ago, Brahmins were common pets. Legends say that Heaven punished people for their misdeeds by making animals rabid.}
{285}{}{Go on, Shaman Genaro.}
{286}{}{The Brahmins scattered across the desert, refused to return to the stalls and hid from people. Their temper became wild. But our ancestors preserved several Brahmins thanks to prayers and offerings to the Divine Brahmin.}
{287}{}{Thanks for the story.}
{288}{}{And why does a brahmin need a second head?}
{289}{}{(shrugs his shoulders in surprise) The ways of the Divine Brahmin are inscrutable. But I believe that this is how two Brahmins merged into one body for better protection from people and animals.}
{290}{}{A reasonable explanation. In two heads it will be easier to monitor the situation around.}
{291}{}{You even find a divine explanation for ordinary ugliness. There's something unhealthy about it...}

{300}{}{Can I buy a brahmin here?}
{301}{}{Hold on to your ridiculous caps. Because of the war, we temporarily suspended the trade in both Brahmins and meat and hides.}
{302}{}{Very sorry. Can we discuss something else?}
{303}{}{The war ended and trade resumed. Do you want to buy a whole brahmin? This acquisition will cost you very much.}
{304}{}{Yes, I need a whole living Brahmin.}
{305}{}{There are only three brahmins for sale in the paddock-Breezy, River and Sierra. But first, show me what you have to exchange. Then take this fruit and give it to the brahmin you love.}
{306}{}{Thank you, Genaro.}

{310}{}{Tell me, what else is this Buried City that the children are talking about?}
{311}{}{Don't go there alone. This place has a bad reputation. Sometimes animal bones are found there, and occasionally even human remains. The spirits cannot reveal to me the secret of this place.}
{312}{}{Is that why you forbid children to appear there?}
{313}{}{Who knows what ancient evil lurks in the dark and confusing dungeon of the old pueblo?}
{314}{}{I see. Thanks for clarifying.}
{315}{}{And here is our hero. I know about your exploits in the Buried City. The children confessed. What did you find there?}
{1315}{}{And here is our heroine. I know about your exploits in the Buried City. The children confessed. What did you find there?}
{316}{}{Now I know what was hiding in the Buried City. People and Brahms were abducted by a monster.}
{317}{}{A monster! We have been trying for a long time to figure out who is stealing our cattle, but this dark spirit skillfully hid from my eagle vision. And yet it exists.}
{318}{}{The dark Spirit has fallen. He won't bother you anymore.}
{319}{}{Thank heaven! The Divine Brahmin himself must have sent you to us. Thank you, friend. We will remember your exploits for generations.}
{320}{}{Oh, yes, I can already see the children gathered around the campfire. And the shaman in the center, who tells them about me... But I have to go. There are still many lives to be saved.}
