{100}{}{You see the priestess Nana.}
{101}{}{You see a priestess in national dress.}
{102}{}{Go away. We are not afraid of you and your iron toys.}

#First meeting
{200}{}{Stop. We don't let outsiders into the camp anymore.}
{201}{}{Wait, stranger. We warned your squad to leave our land. Why do you keep bothering us?}
{202}{}{I don't know what you're talking about. I'm chasing a convoy of slaves from the Villa. He may have passed through here.}
{203}{}{So you're from the Villa? I've heard about your village! We've never been enemies. But we were never friends either.}
{204}{}{I didn't know anything about you either.}
{1204}{}{I didn't know anything about you either.}
{205}{}{Then we should get to know each other better.}
{206}{}{So you suffered the same fate as many? I'm sorry. But you won't find your fellow tribesmen here.}
{207}{}{Are you also worried about slavers?}
{208}{}{Perhaps the peasants of the Villa are kept here. Don't even think about interfering with my search.}
{209}{}{So you're from the Villa? I've heard about your village. We've never been enemies. It's not worth starting this.}
{210}{}{If you know where the slavers are keeping my people, then tell me.}
{211}{}{So the slavers broke your village too? I'm sorry. You are not the first to suffer this fate. But you won't find your people here.}
{212}{}{Are you also worried about slavers?}
{213}{}{Madre... Padre... I want to go home!}
{214}{}{Oh, poor child. Perhaps the Dark Brahmin of Radiation cursed the seed of your kind. I feel sorry for you.}
{215}{}{Bra-Min? No, no, the padre's name is Andres!}
{216}{}{Go to our chief, Geronimo. Talk to him. He is wise and can help you.}
{217}{}{My go to Grandpa.}

{220}{}{They call themselves missionaries. They came to our lands and imposed their own rules on us. The tribe resists, but the price for our freedom is getting higher. We are on the verge of war with the white-skinned citizens of Phoenix.}
{221}{}{There's plenty of room in the wastelands. What didn't you share?}
{222}{}{They want to bend us to their will for the sake of Brahmins and cheap workers. But we are not the kind of Brahmins who obey anyone with a whip.}
{223}{}{You and I are alike. Villa also values her freedom. But it was taken away by force.}
{224}{}{Then we should listen to each other. Talk to our leader, Geronimo. He refuses to talk to outsiders. But you're from a neighboring tribe. And neighbors should live in peace.}
{225}{}{Good. Where to find the leader?}
{226}{}{Go to the big house with columns. I will inform the chief of your arrival. But don't bother the other settlers until you are trusted.}
{227}{}{Okay. See you later.}
{228}{}{I'm looking for Ranger Oscar. I was sent to help him.}
{229}{}{We appreciate what the Rangers are doing for our freedom. Recently, we have been on the verge of a war with missionaries. Talk to our leader about it, Geronimo.}

{230}{}{What did Geronimo say?}
{231}{}{I haven't spoken to him yet.}
{1231}{}{I haven't spoken to him yet.}
{232}{}{Go to Geronimo. I won't discuss anything with you until he lets you stay.}
{233}{}{Okay.}
{234}{}{Can I talk to you from the beginning?}
{235}{}{No. Go to Geronimo. I won't discuss anything with you until he lets you stay.}
{236}{}{Okay.}
{237}{}{Where is the chief?}
{238}{}{In a large bright building with columns. Go ahead, you won't miss it.}
{239}{}{Clear.}
{240}{}{He offers to unite against the Phoenix.}
{241}{}{A reasonable offer. This problem concerns all of us - both our tribe and your Villa. I hope you can help us.}
{242}{}{Yes. Let's see what we can do.}

#Repeat dialog
{250}{}{I'm listening to you, peasant from the Villa.}
{1250}{}{I'm listening to you, peasant girl from the Villa.}
{251}{}{Speak, peasant from the Villa.}
{1251}{}{Speak, peasant woman from the Villa.}
{252}{}{I have to go. See you later, Nana.}

{260}{}{I ask you to advocate for an alliance with the Phoenix missionaries.}
{261}{}{I didn't expect you to take their side. But I don't see any reason to cuddle with a snake. Phoenix will betray our tribe as soon as it turns out to be profitable.}
{262}{}{I do not know what to answer. Maybe you're even right.}
{263}{}{Open your eyes - Phoenix is more profitable than rangers for the whole tribe.}
{264}{}{As we lived without Phoenix before, so we will live. I am against this union.}
{265}{}{You're going to regret this. Mark my words.}
{266}{}{Okay. Let's not argue.}
{267}{}{Rangers are treacherous. They are using you for the purposes of war. And Phoenix offers a trade union and a solution to many problems.}
{268}{}{Hmm. I hadn't thought about it before. Okay, you can count on my vote during the council of elders.}
{269}{}{You won't regret your choice.}
{270}{}{Great, that's all I need.}
{271}{}{The union would solve many of your problems.}
{272}{}{Perhaps it is. But if we become part of the empire, we will lose ourselves. More importantly, we will be defenseless against outsiders. What will we do if we are betrayed? How will we protect ourselves?}
{273}{}{You need strength. You need a weapon.}
{274}{}{Right. The kind of weapon that Phoenix won't give us. If we had those fire rifles that kill a healthy man with one shot, we wouldn't be afraid of any alliances.}
{275}{}{I'll bring you three hunting rifles. And in return, you will advocate for the union at the council of elders.}
{276}{}{So be it. Get us the alien weapons, and I'll take your side.}
{277}{}{Agreed.}
{278}{}{OK. I heard you.}
{1278}{}{Good. I heard you.}
{279}{}{Okay. I always have a lot of different weapons.}

{280}{}{I have a weapon for you.}
{281}{}{Show me what you brought?}
{1281}{}{Show me what you brought?}
{282}{}{Not now.}
{283}{}{.}
{290}{}{ All right. But that's not enough.}
{291}{}{I'll get more.}
{292}{}{OK. That's enough. You can count on my vote during the council of elders.}
{293}{}{And yet Geronimo made an alliance with the Rangers. I shouldn't have listened to you and opposed this union.}
{294}{}{We were both wrong. It happens.}
{295}{}{This mistake could cost someone their life. Think about it as best you can.}
{296}{}{Yeah. Bye.}
{297}{}{Ah, sorry. I forget that you savages are so stupid. Used to having leaders decide everything for you, right?}
{298}{}{I will ask the Divine Brahmin to send snakes under your feet during the journey.}
{299}{}{Aha. Later.}

#Questions
{310}{}{Who are you?}
{311}{}{I am Nana, a priestess of the southern clan of my tribe.}
{312}{}{Nice to meet you, Nana.}
{313}{}{Are there other priestesses?}
{314}{}{Now I, Genaro, Mangas, and the supreme leader Geronimo are in the camp.}
{315}{}{Tell me about Genaro.}
{316}{}{He runs the Brahmin pens and almost never goes out into the wastelands. Therefore, he knows the Phoenix outsiders and their customs better than anyone else.}
{317}{}{Tell me about Mangas.}
{318}{}{Be careful with Mangas. He is intolerant of anything that violates our traditions.}
{319}{}{Tell me about Chief Geronimo.}
{320}{}{The great leader. He united a disparate tribe in the face of a new enemy. Before him, the tribe was feuding over the redistribution of lands. Now we live as one family.}
{321}{}{I met Chatto here. What can you tell me about him?}
{322}{}{The chief's son is an important person in the camp. There are young people behind him. Together they want change. And I don't like it.}
{323}{}{Clear.}
