{100}{}{You see priest Henaro.}
{101}{}{You see a shaman in a tribal outfit.}
{102}{}{Go in peace, strange metallic spirit.}

{200}{}{I welcome you and your tribe. Are you the one everyone here is gossiping about? I'm not sure how to treat you, but I'm not against your presense here.}
{201}{}{Oh, really?}
{202}{}{Thank you.}
{203}{}{Unlike all the other clans of the tribe, I often conduct business with outsiders from the east. Only time will tell whether you can be trusted or not.}
{204}{}{Thank you for your hospitality.}
{205}{}{Kind of a rude way to introduce oneself.}

{210}{}{That thing you drive around on has scared all my brahmin! Choose a different route next time, idiot.}
{1210}{}{That thing you drive around on has scared all my brahmin! Choose a different route next time.}
{211}{}{Sorry. I didn't intend to cause you any trouble.}
{1211}{}{Sorry. I didn't intend to cause you any trouble.}
{212}{}{That's your own problem. Not my fault your brahmin are so fearful.}

{220}{}{I see you are not planning to leave the pueblo any time soon. What makes you stay here, friend?}
{221}{}{I see you are not going to leave the pueblo any time soon. What's on your mind?}
{222}{}{I greet you, friend of the tribe. How can I help you?}
{223}{}{Until next time, Henaro.}

{230}{}{I want you to support an alliance with the missionaries from Phoenix.}
{231}{}{Unlike the rest of the elders, I am not prejudiced against outsiders from Phoenix. My clan has spent much time near them by trading. But I am not ready to go against the rest of the tribe. Perhaps the time has not yet come.}
{232}{}{If the elders don't become convinced, this war will never end.}
{233}{}{You underestimate our tribe. We have much experience in battle and we know the Sonoran wasteland well. Phoenix's army would have to spend much time to win such a battle, if it even decides to stick around for that long.}
{234}{}{You are quite persuasive. Forget about what I told you.}
{1234}{}{You are quite persuasive. Forget about what I told you.}
{235}{}{You're dooming your tribe to war. Heed my words.}
{236}{}{Perhaps it's exactly your vote that could change that. You don't want war with Phoenix, do you?}
{237}{}{The tribe could choose to stand up for itself, but the war that would cause would be unbearable. Not to mention that it would inevitably end with our defeat at the hands of the missionaries' increasingly powerful technologies.}
{238}{}{So, you agree with me?}
{239}{}{I'm not against trading with Phoenix, personally. The other elders don't understand, however, that the world has changed. It is better to enter the new era now, with all our strength, rather than doom our people to a century-long war. You can count on my support in the council of elders.}
{240}{}{You're making the right choice, chieftain Henaro.}
{241}{}{Well, I can understand you...}
{242}{}{You have saved children and cattle from an evil spirit. How can I refuse your request after that?}
{1242}{}{You have saved children and cattle from an evil spirit. How can I refuse your request after that?}
{243}{}{So I can count of you?}
{244}{}{The Holy Brahmin must have punished me by taking the chosen animal's life right before the Day of the Sun. It is a sign. It shows me that I have chosen the wrong path.}
{245}{}{So, you know what to do now, right?}
{246}{}{Great. But let's not get ahead of ourselves. Goodbye.}
{247}{}{Tragic. But let's not get ahead of ourselves, alright?}

{250}{}{Tell me about yourself.}
{251}{}{I am the elder of the western families of our tribe. My name is Henaro.}
{252}{}{Hello, elder Henaro.}
{253}{}{Who is responsible for the others?}
{254}{}{The tribe's supreme leader is Jeronimo. He is a wise and experienced strategist, the great unifier of our tribe. You will find him in the large house with columns.}
{255}{}{What is it you do here?}
{256}{}{I spend much time in San Brahmin. The brahmin need to be looked after when their time in the grazing areas is up, they need to be prepared for what the future holds for them, and for the celebrations during the Day of the Sun. The amount of work I have keeps getting bigger and bigger, I barely manage it.}
{257}{}{Understood.}
{258}{}{Maybe I could help you?}
{259}{}{It seems you've cultivated maize before? That means working with the earth should not be too hard for you. Take the shovel in the yard and clean the... brahmin excrement off of it. The brahmin must be clean, when they are not free. Especially those that I have chosen for the celebration of the Day of the Sun.}
{260}{}{Alright. I'll do it. I hope you will at least feed me fresh brahmin meat for that.}
{261}{}{You really expect me to clean after your brahmin shit?}
{262}{}{Shouldn't that be a mundane activity for you? Well, I can't offer you anything else. I doubt you can work with skins or look after the brahmin. To be honest, I try not to let outsiders into the yard at all. A shame that you do not value the trust offered to you.}
{263}{}{I think you're just making fun of me. Go find some idiot to do it.}
{264}{}{The yard is clean.}
{265}{}{I see. You did well.}
{1265}{}{I see. You did well.}
{266}{}{Are you kidding me? I'm covered in brahmin shit up to my ears!}
{267}{}{Oh thank you, I love doing work for no compensation whatsoever.}
{268}{}{For doing that kind of work, I would be happy to feed you and give you a place to sleep in my tent. Take this jerky. It sates hunger during travel well and doesn't go bad for a very long time.}
{269}{}{Thank you.}
{270}{}{If this turns out to be some kind of joke, you'll regret it.}

{280}{}{In Villa, where I am from, I heard rumours about a tribe that shepherds horned cattle.}
{281}{}{Hm?}
{282}{}{Those tales have always caused much confusion. How did you tame mad brahmin?}
{283}{}{Nevermind. Forget it.}
{284}{}{They were not always like that. Generations ago, brahmin were simple, domesticated animals. Legends say the Heavens punished humans for their misdeeds by turning the animals mad.}
{285}{}{Go on, shaman Henaro.}
{286}{}{The brahmin ran to all corners of the desert, refusing to return to their stalls, hiding from humans. But our ancestors' brahmin were different. Thanks to many prayers and offerings to the Holy Brahmin, our brahmin remained calm and orderly.}
{287}{}{Thank you for telling me this tale.}
{288}{}{Why do brahmin need a second head?}
{289}{}{(shrugs his shoulders, suprised) The Holy Brahmin works in mysterious ways. But I think the reason is a practical one. If two brahmin merge in one body, they would better defend themselves against humans and beasts.}
{290}{}{A wise explanation. It is easier to scan the environment with four eyes.}
{291}{}{You find a divine explanation even for simple ugliness. That can't be good...}

{300}{}{Can I buy brahmin here?}
{301}{}{Keep your silly bottlecaps to yourself. Due to the war, we have temporarily ceased trading not only in brahmin, but meat and skins as well.}
{302}{}{Very sad. Can we discuss something else?}
{303}{}{The war is over and trade has been restored. Are you sure you want to get an entire brahmin? That will cost you quite a lot.}
{304}{}{Yes, I need an entire live brahmin.}
{305}{}{There are only three brahmin for sale in the yard - Breezy, River and Sierra. But first, show me what you have to exchange for it. Then take that fruit and give it to the brahmin you like the most.}
{306}{}{Thank you, Henaro.}

{310}{}{Tell me, what is this Buried City the kids are talking about?}
{311}{}{Do not go there alone. That place has a bad reputation. The bones of animals are sometimes found there, and, albeit rarely, human remains as well. The spirits have failed to reveal the true nature of that place to me.}
{312}{}{So that is why you forbid the kids from going there?}
{313}{}{Who knows what ancient evil is hiding in the dark and confusing corridors beneath the old pueblo?}
{314}{}{Alright. Thanks for explaining it to me.}
{315}{}{And here is our hero. I know of your valiant deeds in the Buried City. The kids told me everything. So, what have you found there?}
{1315}{}{And here is our heroine. I know of your valiant deeds in the Buried City. The kids told me everything. So, what have you found there?}
{316}{}{Now I know what was hiding in the Buried City. Humans and brahmin were being abducted by some terrible creature.}
{317}{}{A monster! We were trying to find out who or what was behind our cattle dissapearing for a long time, but that dark spirit has somehow managed to hide from my sharp eyes. But it's still out there. If it is not stopped, it will simply continue it's abductions.}
{318}{}{The dark spirit has fallen. It will bother you no more.}
{319}{}{Thank heavens! The Holy Brahmin itself must have sent you to us. Thank you, friend. We will remember your heroic actions for generations.}
{320}{}{Oh yes, I already see myself in front of kids around a campfire. And a shaman is in the center, telling them about me... But I have to go. There are many more lives to be saved out there.}