{100}{}{You see a pathfinder.}
{101}{}{You see one of the men of the tribe. He is wearing very light clothes.}
{102}{}{Thank you, friend of our tribe. It's amazing that there are outsiders who can be trusted.}
{103}{}{Thank you for your help in the oasis. Apparently, somewhere in you, there is still a greenhouse of goodness.}

# Before receiving the quest
{200}{}{Greetings, stranger. Although the camp is open to you, I still doubt that you will be of use to us.}
{1200}{}{Greetings, stranger. Although the camp is open to you, I still doubt that you will be of use to us.}
{201}{}{Why is that?}
{202}{}{Because of missionaries and rustlers, we have no confidence in outsiders.}
{203}{}{I understand that. Believe me, I don't wish you any harm and I don't want any problems with you.}
{204}{}{We have already forgotten how to believe words. But I'm glad to hear it.}
{205}{}{I hope you and I will find mutual understanding.}
{206}{}{I haven't done anything yet, and you're already accusing me!}
{1206}{}{I haven't done anything yet, and you're already accusing me!}
{207}{}{Not very smart of you. You won't be able to test our patience for too long.}
{208}{}{And I don't care. I'm just passing by.}
{209}{}{Sorry, that's not what I mean at all.}

{220}{}{What do you need, stranger?}
{221}{}{What do you want, man from the Villa?}
{222}{}{Glad to see you, friend.}
{223}{}{I don't need anything. Later.}

{230}{}{What are you doing?}
{231}{}{The chiefs gathered us in the pueblo to repel the outsiders. In my opinion, it was reckless.}
{232}{}{Why?}
{233}{}{Few trackers are watching the desert around now. I recently returned from one of the watering holes. There I saw a lot of huge desert scorpions. They prevent the shepherds from approaching the water.}
{234}{}{What a horror! And nothing can be done?}
{235}{}{Have you talked about this with anyone?}
{236}{}{I wanted to assemble a squad to get rid of the monsters. But the chief forbade the soldiers to be taken away from the pueblo unless absolutely necessary.}
{237}{}{I think the scorpions will someday leave those places themselves. I have to go too. Later.}
{238}{}{This is very bad. I want to help you.}
{239}{}{Can you handle a crowd of scorpions alone? It's going to be a hot battle.}
{240}{}{You know, I can't even handle one scorpion. You'll have to deal with them without me.}
{241}{}{I'll figure it out. Show me the way to this watering hole.}

{250}{}{I destroyed all the radscorpions at the watering hole.}
{1250}{}{I destroyed all the radscorpions at the watering hole.}
{251}{}{Thank heaven! Your help is necessary for our herders, for whom the oasis was an important place of rest. Thank you, friend of our tribe.}
{252}{}{You're welcome.}
