{100}{}{You see Ronny.}
{101}{}{You see the local expert in crafting leather items. He is professionally cleaning a piece of skin.}
{102}{}{Listen, metal spirit, leave our calm village in peace.}

{200}{}{Greetings, outsider. I hope you have come to us with good intentions?}
{1200}{}{Greetings, outsider. I hope you have come to us with good intentions?}
{201}{}{Who are you? And what is this place?}
{202}{}{I want to get to know you.}
{203}{}{I am Ronny, and this is my tannery.}
{204}{}{Looks like you settled here well, Ronny.}
{205}{}{Exactly. I used to travel through the Sonora desert and graze brahmin, like everyone else. Now I sit here and prepare skins for my fellow people and for outsiders to buy.}
{206}{}{Your work must be extremely important, Ronny.}
{207}{}{A solid business it must be.}
{208}{}{Understood. But as of now, I have no need of leather items. Goodbye.}

{210}{}{Greetings.}
{211}{}{Until next time.}
{212}{}{A-ah, I recognise my work. Every such piece of armor I mark with a special seal.}
{213}{}{Welcome, Ranger. How can I help you, friend of my tribe?}
{214}{}{A-ah, another representative of a strange religion. What does your church want from my tribe this time?}

{220}{}{Why did you stop trading with Garage City?}
{221}{}{Our priests decided so. They do not like that the outsiders are breaking our traditions and are fooling and stealing our brahmin. That is why we have broken trade routes with Phoenix and all it's colonies.}
{222}{}{But Garage City isn't a colony of Phoenix.}
{223}{}{As I said, the priests made that decision. You should talk to them. Until they give me permission, I will not be able to trade with that town.}
{224}{}{Alright. I'll go achieve their permission.}
{225}{}{Chieftain Jeronimo has given permission to trade.}
{226}{}{Chieftain Chatto has given permission to trade.}
{227}{}{There is no more supreme leader. Nobody's watching. Don't miss your chance to profit.}
{228}{}{I hope this is all just part of the Holy Brahmin's plan. Tell the residents of Garage City to send a negotiator.}
{229}{}{Great.}

{230}{}{Can you craft bags for my bike?}
{231}{}{That is my specialty. I'll craft bags of the highest quality. Your bike will turn into an entire caravan. But such work costs much. What can you offer in exchange?}
{232}{}{Let's see...}
{233}{}{The tannery is closed for outsiders. I work only for members of the tribe and those outsiders the shamans trust.}
{234}{}{So I'll have to deal with your local bullshit first? Fine.}
{235}{}{I'll talk to them later.}

{240}{}{I would like to take a look at your wares. Can I?}
{241}{}{I am not to trade with outsiders while this war is going on. Chieftain Jeronimo said so.}
{242}{}{Fine, I'll manage without your leather.}
{243}{}{The war is over. You can start, friendo.}
{244}{}{The chieftain must have been too busy to tell me this. Alright, take a look at what I have. Maybe you need something comissioned?}
{245}{}{Thanks, let me think for a bit.}
{246}{}{Come on, I'm from Villa. We're like neighbors to you, not outsiders.}
{247}{}{Sorry. Chieftain knows better.}
{248}{}{You sure? Well, alright.}
{249}{}{Neighbors must live in peace. Your tribe and our Villa will make for incredible allies to one another.}
{250}{}{I agree with you, outsider. The chieftain was only talking about Phoenix and it's colonies. Let's assume Villa is not one. Take a look at what I have. Maybe you need something comissioned?}
{251}{}{Thanks, let me think for a bit.}
{252}{}{Am I not deserving of your trust, Ronny?}
{253}{}{Sorry, I didn't mean to offend you. You are not one of those who have fooled and harmed our tribe. Here, take a look at what I have. Maybe you need something comissioned?}
{254}{}{Thanks, let me think for a bit.}

{260}{}{I welcome a hero when I see one. We are all incredibly thankful to you for your actions. Here, take this weapon as a show of our appreciation. Our shamans have enfused it with a sliver of the Holy Brahmin's power.}
{1260}{}{I welcome a heroine when I see one. We are all incredibly thankful to you for your actions. Here, take this weapon as a show of our appreciation. Our shamans have enfused it with a sliver of the Holy Brahmin's power.}
{261}{}{A curious object.}
{262}{}{Of course, the strength of this weapon is not infinite. When the holy energy runs out, you will need to replace the powersells.}
{263}{}{Thanks, Ronny.}

{270}{}{And so, the war is over - thanks to you. San Brahmin once again trades with Phoenix. And that is why I will once again open the doors of my tannery to everyone.}
{271}{}{And so, the war is over - thanks to you. San Brahmin will trade with the Phoenixian empire and it's vassals no more. But we are still open to our friends and the Rangers.}
{272}{}{[Continue]}
{273}{}{If you need any leather items, head right to me.}
{274}{}{Will keep that in mind.}

{280}{}{Hm. You look suspiciously close to the description of one of the bandits that attacked our pastoralists near Garage City.}
{281}{}{I don't know what you're talking about. It's a total fabrication.}
{282}{}{Ha! Even kids who have wetted their pants say their feet are dry. Go in peace.}
{283}{}{Uhh... okay...}
{284}{}{Yes, a similar event did take place. We thought it was a mad brahmin.}
{285}{}{You thought. Good for you that the pastoralists were not harmed. Otherwise, the entire pueblo would have been very angry with you. But it is good that you recognise your misdeed. And at least I know that I should be more careful with you.}
{286}{}{Uhh, alright...}
{287}{}{I will think your wise words over.}
{288}{}{Leave your moralizing for the silly kids, idiot.}

{290}{}{You know, Mangas asked me to destroy the moonshine distillery in Phoenix.}
{291}{}{Who does he think he is? A shaman can't just rid us of all of a pleasure like that. Nobody will like that. Mangas can make decisions by himself only for his clan. He isn't our supreme leader.}
{292}{}{So you are against Mangas' offer?}
{293}{}{Mangas' request was not one of a chieftain. It was simply a personal request. Instead of fulfilling the whims of that grumpy old man, you could instead get me a box of Phoenixian swill. I will find a use for it during the celebration of the Day of the Sun.}
{294}{}{What's the problem with getting alcohol?}
{295}{}{Don't you know? We ended all deals with Phoenix due to the war. Of course, we know how to make moonshine too. From cactuses. Of course, it can't even be compared to real tequila from a city.}
{296}{}{How many bottles?}
{297}{}{10 bottles of tequila and beer.}
{298}{}{Alright, I'll think over who to side with here.}
{299}{}{Remind me, how many bottles of alcohol do you need?}
{300}{}{I have exactly as much alcohol as you need.}
{301}{}{Let the Sunlike Brahmin itself glorify your name! With such reserves, our celebration will not be darkened even by the war happening all around us. Thank you. If you ever need services relating to leather, head right to me. I'll do anything for you, at a lowered price.}
{302}{}{Will keep that in mind. Bye, Ronny.}

{310}{}{What is it you trade?}
{311}{}{I create various things out of brahmin skin. But they are mainly used by other members of the tribe. I no longer conduct business with Phoenix and it's colonies. Only the Rangers can ask for commissions.}
{312}{}{Alright.}
{313}{}{What items do you make?}
{314}{}{Clothes, belts, bags, and many other things. For the Rangers, I create armor.}
{315}{}{What problems do you have with Phoenix?}
{316}{}{Once, we peacefully coexisted. But in the last couple of years, light-skinned men with weapons have come from that big city, bent on subjugating us or taking away what is ours. The tribe can tolerate it no more.}
{317}{}{You said you have good relations with the Rangers?}
{318}{}{They help us resist against the Phoenixian invaders. And they were always good clients for my tannery.}
{319}{}{And who do you personally support in this debate?}
{320}{}{Hard to say. The Rangers have treated us well so far, but I suspect that their intentions are not as pure as they make them out to be. They have their own agenda in this war.}
{321}{}{[Continue]}
{322}{}{But on the other hand, for a long time, we have lived together with Phoenix in peace, and actively traded with them, until our relations soured. Phoenix would give us more opportunities, if it was not ruled by a greedy tyrant.}
{323}{}{Understood.}