{100}{}{You see Ronnie.}
{101}{}{You see the master of leather goods. With a professional movement of his hand, he cleans a piece of leather.}
{102}{}{Listen, iron spirit, leave our peaceful village alone.}

{200}{}{Greetings, stranger. I hope you came to us with good intentions?}
{1200}{}{Greetings, stranger. I hope you came to us with good intentions?}
{201}{}{Who are you? And what is this place?}
{202}{}{I want to get acquainted.}
{203}{}{I'm Ronnie, and this is my tannery.}
{204}{}{Looks like you're pretty settled in here, Ronnie.}
{205}{}{Right. I used to travel through the Sonoran desert and herd Brahmins like the others. And now I'm sitting here and preparing leather for my tribesmen and for sale.}
{206}{}{You have an important job, Ronnie.}
{207}{}{Not a bad business, it must be.}
{208}{}{I see. But right now I don't need leather goods. Later.}

{210}{}{Greetings to you.}
{211}{}{See you later.}
{212}{}{Ah, I recognize my work. I mark each such armor with a special brand.}
{213}{}{Welcome, Ranger. How can I help you, friend of my tribe?}
{214}{}{Ah, another ambassador of a strange religion. What does your church want from my tribe this time?}

{220}{}{Why did you stop trading with Garage City?}
{221}{}{Our priests decided so. They don't like that outsiders are bringing discord into our lives, deceiving and stealing our Brahmins. Therefore, we have closed trade routes with Phoenix and all its colonies.}
{222}{}{Does this apply to Garage City?}
{223}{}{The priests know better. Talk to them. Until they give their consent, I will not be able to trade with this city.}
{224}{}{I see. I'm going to seek their favor.}
{225}{}{Chief Geronimo has agreed to trade.}
{226}{}{Chief Chatto has agreed to trade.}
{227}{}{There is no Supreme Leader yet. Don't miss your chance.}
{228}{}{I hope all this is just the Divine Brahmin's providence. Tell the residents of the Garage to send a person to negotiate.}
{229}{}{That's good.}

{230}{}{Can you make bags for my bike?}
{231}{}{That's my line. I'll do it in the best possible way, your bike will make a whole caravan. But such work is expensive. What can you offer in return?}
{232}{}{Let's see...}
{233}{}{The tannery is closed to outsiders. I work only for members of the tribe and those outsiders who are trusted by shamans.}
{234}{}{So you have to deal with the local shit first? Clear.}
{235}{}{I'll talk to them later.}

{240}{}{I wanted to look at your products. Can I?}
{241}{}{I don't trade with outsiders anymore until the war is over. So decided Chief Geronimo.}
{242}{}{Okay, I'll do without your skin.}
{243}{}{The war is over. You can start, friend.}
{244}{}{Perhaps the chief is too busy to tell me about it. Okay, look what I have. Maybe you need something to order?}
{245}{}{Thank you, give me time to think.}
{246}{}{Come on, we're neighbors, not strangers at all.}
{247}{}{Sorry, but the leader knows better.}
{248}{}{Are you sure? Well, okay.}
{249}{}{Neighbors should live in peace. Your tribe and our Villa - a good union will come out of us.}
{250}{}{I agree with you, outsider. The chief spoke only of Phoenix and its colonies. We will assume that the Villa is not one of them. Look at what I have. Maybe you need something to order?}
{251}{}{Thank you, give me time to think.}
{252}{}{Am I not trustworthy, Ronnie?}
{253}{}{Sorry, I didn't mean to offend you. You are not one of those who cheated and harmed our tribe. Here, look at my products. Maybe you need something to order?}
{254}{}{Thanks, let me think.}

{260}{}{Greetings, hero. We are all immensely grateful to you for your exploits. Here, take this weapon as a token of gratitude. Shamans endowed him with a piece of the power of the Divine Brahmin.}
{1260}{}{Greetings, heroine. We are all immensely grateful to you for your exploits. Here, take this weapon as a token of gratitude. Shamans endowed him with a piece of the power of the Divine Brahmin.}
{261}{}{Curious object.}
{262}{}{Although the power of this weapon is not unlimited. When the divine energy runs out, you need to replace the bat plates.}
{263}{}{Thanks, Ronnie.}

{270}{}{So the war ended - thanks to your intervention. San Brahmin reopens trade routes to Phoenix. Therefore, I can reopen the doors of the workshop for everyone.}
{271}{}{So the war ended - thanks to your intervention. The San Brahmin no longer believes in the Phoenix Empire and its vassals. But we are still open to our friends and rangers.}
{272}{}{[Next]}
{273}{}{If you need any leather goods, contact me directly.}
{274}{}{I'll keep that in mind.}

{280}{}{Hmm. You look suspiciously like one of the bandits who attacked our shepherds at Garage City.}
{281}{}{I don't know what you're talking about. There was nothing like that.}
{282}{}{Ha! Even children who have peed themselves say that their feet are dry. Go in peace.}
{283}{}{Okay...}
{284}{}{Yes, there was a case. We thought it was a wild brahmin.}
{285}{}{I should have thought better. It's lucky for you that the shepherds didn't get hurt. Otherwise, the whole pueblo would be mad at you. But it's good that you admit a mistake. At least I know I should be more careful with you.}
{286}{}{Uh, okay...}
{287}{}{I will think over your words, wise man.}
{288}{}{Leave your moralizing to the stupid kids, dumbass.}

{290}{}{You know, Mangas asked me to destroy the moonshine factory in Phoenix.}
{291}{}{Who does he think he is? A shaman cannot deprive us all of pleasure so easily. No one will like it. At least Mangas can't decide for all the clans at once, he's not the supreme leader.}
{292}{}{So you're against Mangas' proposal?}
{293}{}{This is everyone's business, not just the leader's. Instead of following the whims of this grumpy old man, it's better to get me a box of Phoenix swill. I will find a use for it during the celebration of the Day of the Sun.}
{294}{}{But what's the problem with getting alcohol?}
{295}{}{Don't you know? We cut off all deals with Phoenix because of the war. Of course, we also know how to make moonshine from cacti, but real tequila from the city does not go to any comparison.}
{296}{}{How many bottles do you need?}
{297}{}{Ten bottles of tequila and the same number of bottles of beer.}
{298}{}{Okay, I'll think about which one of you to support in this dispute.}
{299}{}{Remind me how many bottles of alcohol do you need?}
{300}{}{I have just as much alcohol as you need.}
{301}{}{May your name be glorified by the Sun-loving Brahmin himself! With such reserves, our holiday will not be overshadowed even by the war going on around. Thank you. If you need the services of a tanner, then remember me. I'll do anything for you for a reduced fee.}
{302}{}{I'll keep that in mind. Bye, Ronnie.}

{310}{}{What do you sell? }
{311}{}{I make various items out of Brahmin leather. But mostly they are used by members of the tribe. I no longer do business with Phoenix and its colonies. Only rangers can make their orders.}
{312}{}{I see.}
{313}{}{What items do you make?}
{314}{}{Clothes, belts, bags, and much more. I make armor for the Rangers.}
{315}{}{What's the problem with the Phoenix?}
{316}{}{We co-existed peacefully for a while. But for the last few years, white people have been coming from the big city with guns to subdue us or take away from us what belongs to us. The tribe can't stand it.}
{317}{}{You say you have a good relationship with the Rangers?}
{318}{}{They help us resist the invaders from Phoenix. And they have always been good customers in my tannery.}
{319}{}{And who do you support in this dispute?}
{320}{}{It's hard to say. The Rangers have treated us well so far, but I suspect they are not pure in mind. After all, they have their interests in this conflict.}
{321}{}{[Next]}
{322}{}{At the same time, we have been peacefully existing with Phoenix for a long time and actively traded with it until the relationship deteriorated. Phoenix would have given us more opportunities if it weren't for the greedy tyrant at the head there.}
{323}{}{I see.}
