{100}{}{you have a missionary in front of you.}
{101}{}{you see one of the soldiers. He is in full combat gear.}

{110}{}{I wish I could talk to the commander.}
{111}{}{how lucky that you are not from the tribe of cattle breeders.}
{112}{}{The commander brought us. talk to him from there.}
{113}{}{Do you want to joinÿ? Well, I'm not going to share rations.}
{114}{}{I don't know how the others are, but I'm going to *survive* this night.}
{115}{}{Looks like we're stuck here for a long time.}

{150}{}{Sings an old song, enviously chewing your carbine.}
{151}{}{Carabina Treinta Treinta}
{152}{}{Que los rebeldes portaban}
{153}{}{Y Dec?an los maderistas}
{154}{}{Que con ellas no mataban.}
{155}{}{Con mi 30/30 me voy a pelear}
{156}{}{Ingrese a las filas de la rebelion}
{157}{}{Si mi sangre piden, mi sangre les doy}
{158}{}{Por los habitantes de nuestra nacion}
{159}{}{.}

{160}{}{it's finally over.}
{161}{}{we won! Olé!}
{162}{}{we beat these aborigines like children.}
{163}{}{Ònow the savages will not dare to go against us.}
{164}{}{the rangers are fleeing to the west with their tails between their legs.}
{165}{}{yes! Now we are here, Eva.}

{170}{}{Bloody savages!}
{171}{}{I don't want to return to Enix after such a disgrace.}
{172}{}{These savages will regret that they drove us away.}
{173}{}{Finally we will return home.}
{174}{}{If the commander runs away with Paul, then we have nothing to do here.}
{175}{}{They told me that it was not worth getting into this war...}