{100}{}{You see George Crook.}
{101}{}{You see a man with a great mustache and a determined look.}
{102}{}{Exactly. Now go and kill all the savages. You do understand orders, right?}
{103}{}{Take care of yourself. Maybe we'll meet again.}
{104}{}{I'll have to return to Phoenix. Lord knows I did all I could.}

#First encounter
{200}{}{Stop. What are you doing here?}
{201}{}{I don't know. I'm just wandering here.}
{202}{}{Stop kidding around. I see through you, peasant people, like glass. You're clearly not from Phoenix, meaning, you are from somewhere in the Wasteland. Where from? Answer me, now.}
{203}{}{I don't answer to you. I don't have to do what you tell me to do.}
{1203}{}{I don't answer to you. I don't have to do what you tell me to do.}
{204}{}{Would you look at that. Another proud peasant. You think you're in the right here? Soon, the entire Wasteland will be brought under Aaron's heel by the might of his army! Then we'll see where your pride gets you.}
{1204}{}{Would you look at that. Another proud peasant. You think you're in the right here? Soon, the entire Wasteland will be brought under Aaron's heel by the might of his army! Then we'll see where your pride gets you.}
{205}{}{Really?}
{206}{}{For a peasant like you, there's nothing left to do but kneel. You'll understand soon enough. But for now, I'll give you a chance to change your ways. Go back to the wastes you came from and spread the word about the might of the Phoenixian army.}
{1206}{}{For a peasant like you, there's nothing left to do but kneel. You'll understand soon enough. But for now, I'll give you a chance to change your ways. Go back to the wastes you came from and spread the word about the might of the Phoenixian army.}
{207}{}{I'm leaving.}
{208}{}{I'm not leaving until you answer my questions.}
{209}{}{Aaron sent me here to help. Here's the order and the seal.}
{210}{}{My village was depopulated. So I'm just walking somewhere, don't know where.}
{211}{}{You've made the right choice, kid. Go to Phoenix. There's nothing to do in the desert, but in a big city there will be many opportunities open to you. Just don't get on the wrong path. If you understand what I mean.}
{212}{}{Yes, I do understand what you mean.}
{213}{}{Excellent. For now, I'll consider you on my side.}
{214}{}{Alright. What's going on in here?}
{215}{}{No, not really.}
{216}{}{I represent Aaron's might in these lands. There are two kinds of people: those that respect Aaron, and those that do not. One of them, Aaron values. The other he does not. Choose very carefully which kind of person you become.}
{217}{}{Alright.}
{218}{}{What *is* going on in here?}

{220}{}{Wait... Hmm. A familiar robe. Did Aaron send you?}
{221}{}{I don't know who you're talking about. These are just some old loose overalls.}
{222}{}{Forget, it then. What are you doing here?}
{223}{}{Yes, Aaron sent me. He wants to know what is going on in here.}
{224}{}{I don't understand what he's thinking. My unit will run out of food soon, and he sends another warrior. Tell me, in what way will you be useful?}
{225}{}{I am on a special mission. Aaron is tired of waiting for results.}
{226}{}{I think he just wants the mission to be completed as soon as possible.}
{227}{}{Hm. I am already curious what exactly you did to gain the trust of Aaron himself. I guess I should listen to your advice. But keep in mind that I am still the commander of the unit.}
{228}{}{No problem.}
{229}{}{I am not worried about your unit.}

{230}{}{I represent the Desert Rangers. Rumours that someone is trying to subjugate the pastoralist tribe have come to our attention.}
{231}{}{We are simply peaceful settlers. We have come to empty land looking to establish a settlement. Are we doing anything wrong?}
{232}{}{You are trying to drive off the tribe.}
{233}{}{Fine, I'll tell you this. Listen to me, Ranger lackey, and listen carefully. These lands do not belong to you. Neither do they belong to those savages. This entire valley belongs to Aaron of Phoenix. If you do not want to be crushed under his heel, you will return to your lands and will not stand in our way.}
{234}{}{You've said enough. I need no more information.}
{235}{}{I will not leave until I get answers to my questions. What is going on in here?}

#Repeat dialogue
{250}{}{What? Talk, I'm listening.}
{251}{}{Allow me to pass through, please.}
{252}{}{What are you all doing here?}

{260}{}{These lands belong to his majesty Aaron, Master of the Holy Fire and Overlord of Phoenix. He has decided to set up a colony here. But local savages are impeding our mission.}
{261}{}{What's wrong with them?}
{262}{}{They have never shown hostility before. Now they are trying to drive us away with threats and violence. But we do not want any unnecessary bloodshed. We're offering them a mutually beneficial alliance.}
{263}{}{Why can't you just let the tribe be?}
{264}{}{Their brahmin are too highly valued in Phoenix. There will be an economic crisis without them. And now that they have shown hostility, we can't exactly leave an enemy right on our doorstep, can we?}
{265}{}{[Continue]}
{266}{}{In any case, I am a man who answers to others. I simply follow the orders given to me by the brass. The order to settle this place is clear to me. The demands of nomadic savages who cannot even read I do not take under consideration.}
{267}{}{Understood.}
{268}{}{Listen. The tribe doesn't want to talk to me anymore. But they might be willing to talk to you. Speak with their leader, try to convince him to establish an alliance.}
{269}{}{I'm not going to become involved in someone else's war. My own problems are more important to me.}
{270}{}{Then pray this war does not touch you or your people.}
{271}{}{I have to go.}
{272}{}{I'll try. Will report the results.}

{280}{}{I have managed to talk with the chieftain. But he is flat-out refusing the notion of an alliance.}
{281}{}{Jeronimo is too stubborn. Looks like I am wasting my time with him. I need to act more decisively.}
{282}{}{What is your plan?}
{283}{}{I know that not all of those savages despise us. The young ones are even trying to help. The son of the chieftain, Chatto, is among them. Talk to him, find out what he wants. If he replaces his father, we will reach an agreenment.}
{284}{}{I'll give it a try.}
{285}{}{I have killed Jeronimo and his successor, Chatto.}
{1285}{}{I have killed Jeronimo and his successor, Chatto.}
{286}{}{That was quite reckless of you! Jeronimo resisted the alliance. But Chatto could have replaced him. Now we have nobody to negotiate with. The tribe will flee to the desert, once again broken into small packs.}
{287}{}{That was hard to foresee...}
{288}{}{But you wanted to get rid of the chieftain.}
{289}{}{In any case, the situation has become much easier. We will simply move into the pueblo and the savages will have no choice but to accept our rules. They won't be able to resist an entire colony.}
{290}{}{Well, can I congratulate you with victory, then?}
{291}{}{Not yet. My scouts have found out who was creating problems here in this pueblo. It turned out to be a man by the name of Oscar. A Desert Ranger! Now I understand how the locals knew tactics and partisan tricks.}
{292}{}{[Continue]}
{293}{}{The Ranger needs to be driven out of the pueblo! So that nobody even remembers his name. And if he does not wish to go away willingly, we'll make him with force.}
{294}{}{Good. I'll see what I can do.}
{295}{}{Chatto is now the tribe's chieftain, and he agrees to establish an alliance.}
{296}{}{Great news! Chatto's power is recognized by the rest of the tribe, and his authority won't let them run off into the desert. Very good work. You have proven yourself to be a capable diplomat.}
{297}{}{The chieftain agrees to an alliance. I managed to pursuade him, even though it was not easy.}
{298}{}{Fantastic news. I do not think he changed his views that much. He was probably pressured by the other elders who fear a potential war. But good work nonetheless. You have proven yourself to be a capable diplomat.}

{300}{}{Oscar is dead. His henchmen have been brought under your heel, commander.}
{301}{}{This is a victory! We have struck a decisive blow to the reputation of the Desert Rangers in this tribe. Now they will understand who they should conduct business with.}
{302}{}{Oscar ran from the pueblo and will no longer interfere with your plans.}
{303}{}{This is a victory! The Desert Rangers have ran away and so have become viewed as cowards by the savages. Now they will understand who they should conduct business with.}
{304}{}{Happy to help, commander!}
{1304}{}{Happy to help, commander!}
{305}{}{Don't forget whose actions allowed that to happen.}
{306}{}{Yes, you have served the empire well. If only others had that kind of strength and resilience. I am happy we ended up on the same side.}
{1306}{}{Yes, you have served the empire well. If only others had that kind of strength and resilience. I am happy we ended up on the same side.}
{307}{}{Do you think Aaron's empire needs any more heroes?}
{308}{}{Of course. I will send a letter of recommendation with your name on it straight to Phoenix. Head right to Aaron, he values my word.}
{309}{}{Thank you.}
{310}{}{No, don't thank me. We are working toward the same goal. Good luck in your travels, comrade.}
{311}{}{Good luck.}

{320}{}{Who are you? And who are all these people?}
{321}{}{Tell me about you and your unit.}
{322}{}{George Crook, field commander serving his majesty Aaron, Overlord of Phoenix. And this is my trusty unit. When we clear this territory of enemies, a group of simple settlers will follow.}
{323}{}{Nice to talk with you, even for a bit. But I have to go.}
{324}{}{Isn't that a bit too long of a title for someone who only governs one city?}
{325}{}{Watch your tongue! Aaron's empire is quite large and is constantly expanding. Soon, all of Arizona will be under his dominion.}
{326}{}{Once again - who are you?}
{327}{}{Where did you come from?}
{328}{}{We've come from Phoenix to establish a colony here. But this place was already taken by those savages.}
{329}{}{And where is this Phoenix located?}
{330}{}{A city south-east from here. Strange that you do not know that. It's supposed to be the biggest city for many miles around here.}
{331}{}{I'm actually from a village in the opposite direction of that place.}
{332}{}{Ah. I understand. That is Ranger territory. No wonder your land has only villages and no civilization. Take a look at Phoenix and you'll learn what an actual city is like.}
{333}{}{I'll do exactly that. Thanks for the tip.}
{334}{}{I don't care about your "civilization".}
{335}{}{Tell me about the tribe.}
{336}{}{It is a tribe of pastoralists and nomads. The inhabitants of Phoenix have had a complicated relationship with them for some time now.}
{337}{}{By the way, what do you know about the locals?}
{338}{}{Looks like you don't really like them.}
{339}{}{Those savages crawl through the desert like flies. And should they settle around old ruins, they immediately pretend they are entitled to that land.}
{340}{}{[Continue]}
{341}{}{Several radical clans are even attacking peaceful civilians. Phoenix has been trying to negotiate peace with them for several years. And some of the clans have switched to our side. But not all of them. Now my unit has felt the stubborness of those savages as well.}
{342}{}{Now I see why you are so well-armed. Peace be with you. And I have to go.}
{343}{}{You're from Phoenix too?}

{350}{}{You must leave San-Brahmin. You and your entire unit.}
{351}{}{What nonsense. Why would I do that?}
{352}{}{Well, you don't want to anger the tribe, right?}
{353}{}{I just want to put these savages in their place. It wouldn't hurt for you to reconsider your views as well.}
{354}{}{Fine. I won't argue with you.}
{355}{}{If you don't go away, blood will be spilled.}
{356}{}{Whoever sent you, tell them that George Crook is fearless. I cannot be scared with mere words.}
{357}{}{Well, I warned you. Now blood will flow like a river!}
{1357}{}{Well, I warned you. Now blood will flow like a river!}
{358}{}{Alright. I hear you.}
{1358}{}{Alright. I hear you.}
{359}{}{The tribe is ready to commit decisive action. Your arrival just gave them a motivation.}
{360}{}{I know that those savages won't surrender that easily. They are too primitive to understand the idea of the New World that I am helping my master to create. But that's why I'm here - to show those savages how outdated, how wrong the way they live is, how pointless and counterproductive it is to resist us. That a better world is possible, and they can be a part of it.}
{361}{}{Fine. I won't argue with you.}
{362}{}{But in angering them, you will just make the tribe look at your ideals in contempt. Give them time to think. In the end, your mission will be pointless if they attack.}
{363}{}{There are too many of them. I'm thinking of returning to Phoenix. My men are tired, there's not enough supplies, and there are those savages looking at us from behind the dunes.}
{364}{}{So, what have you decided?}
{365}{}{Alright. We will go. But only to return better prepared, in greater numbers.}
{366}{}{A fine decision, commander. Good luck in your journey.}