{100}{}{This is George Crook.}
{101}{}{You see a man with a gorgeous mustache and a determined look.}
{102}{}{Right. Now go and kill all the savages. You understand orders, don't you, robot?}
{103}{}{Take care of yourself. Maybe we'll meet again.}
{104}{}{I'll have to go back to Phoenix. God knows I did what I could.}

#First meeting
{200}{}{Wait. What are you doing here?}
{201}{}{I don't know. Just wandering around here.}
{202}{}{Don't joke with me. I can see right through you rednecks. You're obviously not from Phoenix, which means you're from somewhere in the wasteland. From where? Answer me.}
{203}{}{I don't have to answer to you.}
{1203}{}{I don't have to answer to you.}
{204}{}{First of all, what is it. In front of me is a proud and unbending redneck. Do you think you're the right one here? Soon the whole wasteland will be under the heel of Aaron and his army! And then we'll see how much your pride is enough.}
{1204}{}{First of all, what is it. In front of me is a proud and unbending hillbilly. Do you think you're the right one here? Soon the whole wasteland will be under the heel of Aaron and his army! And then we'll see how much your pride is enough.}
{205}{}{Really?}
{206}{}{You, a peasant, will have nothing left but to bow your knees. You'll find out soon enough. In the meantime, I'll give you a chance to improve. Go back to the wastelands and tell everyone about the greatness of the Phoenix regular army.}
{1206}{}{You, a peasant woman, will have nothing left but to bow your knees. You'll find out soon enough. In the meantime, I'll give you a chance to improve. Go back to the wastelands and tell everyone about the greatness of the Phoenix regular army.}
{207}{}{I'm leaving.}
{208}{}{I will not leave without answers to questions.}
{209}{}{Aaron sent me to help. Here is the order and the seal.}
{210}{}{My village is deserted. So I'm going wherever my eyes look.}
{211}{}{And that's right, baby. Go to Phoenix. There is nothing to do in the desert, and in a big city there will be many opportunities for you. Just don't mix up the road. If you know what I mean.}
{212}{}{Yes, I understand.}
{213}{}{Great. For now, I will assume that we are on the same side.}
{214}{}{Okay. What's going on here?}
{215}{}{Not really.}
{216}{}{I represent Aaron's authority in these lands. Aaron appreciates those who honor him. And he is very harsh with those who get in his way. Choose better which list to fit into.}
{217}{}{I see.}
{218}{}{What's going on here?}

{220}{}{Wait... hmm? Familiar mantle. Did Aaron send you?}
{221}{}{I don't know who you're talking about. It's just an old hoodie.}
{222}{}{Then forget it. What are you doing here?}
{223}{}{Yes, Aaron sent me. He wants to know the situation.}
{224}{}{I don't understand his train of thought. I will soon have nothing to feed my squad, and he is sending another fighter. Tell me, what use are you?}
{225}{}{I have a special assignment. Aaron is tired of waiting for results.}
{226}{}{I think he just wants to solve the problem as soon as possible.}
{227}{}{Hmm. I'm already curious how you earned so much trust from Aaron himself. Perhaps I should listen to your advice. But keep in mind that I am still the commander of the squad.}
{228}{}{No problem.}
{229}{}{I don't care about your squad.}

{230}{}{I represent the Rangers. We have heard rumors that someone is trying to break the tribe of cattle breeders.}
{231}{}{We are just peaceful colonizers. They came to an empty land to establish a settlement here. Are we doing something bad?}
{232}{}{You're trying to drive the tribe away.}
{233}{}{I'll tell you what. Listen carefully, Ranger henchman. These lands don't belong to you. And they don't belong to savages either. Aaron of Phoenix owns this whole valley. Get back to your people. And don't you dare get in our way.}
{234}{}{You've said enough. I don't need more.}
{235}{}{I'm not leaving until I get the answers to the questions. What's going on here?}

#Repeat dialog
{250}{}{Well? Speak, I'm listening.}
{251}{}{Let me go.}
{252}{}{And what are you all doing here?}

{260}{}{This land belongs to His Majesty Aaron, Lord of the Sacred Fire and Lord of the Phoenix. He decided to establish a colony here. But our mission is being harmed by local savages.}
{261}{}{What's wrong with these savages?}
{262}{}{They didn't show hostility before. Now they are trying to drive us away with threats and brute force. But we don't want extra blood and offer them a mutually beneficial alliance.}
{263}{}{So why not leave the tribe alone?}
{264}{}{Their brahmins are too valued in Phoenix. Without them, there will be a crisis. Besides, it is unforgivable to leave an enemy under your nose.}
{265}{}{[Next]}
{266}{}{In any case, I am a subordinate person. I am following the order of the high command. The settlement order is clear to me. And the demands of nomadic illiterate savages are not a decree to me.}
{267}{}{Clear.}
{268}{}{Listen. The tribe doesn't want to talk to me anymore. But you'll make a good spy. Talk to the leader, try to convince him to conclude an alliance.}
{269}{}{I'm not going to interfere in someone else's war. Your problems are more important.}
{270}{}{What are your problems compared to the war between the two peoples? Then pray that it does not touch you and your family.}
{271}{}{I have to go.}
{272}{}{I'll try. I will report on the result.}

{280}{}{I managed to talk to the chief. But he flatly refuses the union.}
{281}{}{Geronimo is too stubborn. It looks like I'm wasting time with him. We need to act more decisively.}
{282}{}{What's your plan?}
{283}{}{I know that not all savages despise us. The young are even trying to help. Among them is the chief's son, Chatto. Talk to him, find out what he wants. If he takes his father's place, then we can come to an agreement.}
{284}{}{It's worth a try.}
{285}{}{I killed Geronimo and his successor Chatto.}
{1285}{}{I killed Geronimo and his successor Chatto.}
{286}{}{It was very reckless! Geronimo resisted the union. But Chatto could have mediated in his place. Now we have no one to negotiate with. The tribe will scatter across the desert, breaking up into small flocks again.}
{287}{}{It was hard to foresee...}
{288}{}{But you wanted to get rid of the leader yourself.}
{289}{}{In any case, the situation has become easier. We will settle in the pueblo and force the savages to accept our rules by force. They won't be able to resist an entire colony.}
{290}{}{Well, can I congratulate you on your victory?}
{291}{}{Not yet. The scouts found out who was raising dust in this pueblo. It turned out to be a man named Oscar. Ranger! Now I understand how the locals know the basics of tactics and guerrilla tricks.}
{292}{}{[Next]}
{293}{}{The Ranger must be driven out of the pueblo! So that they don't even remember his name here. And if he does not want to leave, we will whip him like a stubborn brahmin.}
{294}{}{Good. I'll see what I can do.}
{295}{}{Chatto is now the chief of the tribe. And he agrees to the conclusion of the union.}
{296}{}{The beauty of the news! Chatto has power in the eyes of the rest of the tribe, his authority will not allow the tribe to scatter in the desert. Very good job. You made a great diplomat. }
{297}{}{The leader agrees to the alliance. I managed to convince him, although it was not easy.}
{298}{}{The beauty of the news. I don't think he's changed his views that much. Most likely, he was pressured by the other elders who are afraid of war. But it's a good job. You've made a great diplomat.}

{300}{}{Oscar is dead. His minions also kneel before you, Commander.}
{301}{}{This is a victory! We have dealt a decisive blow to the reputation of the Rangers before the eyes of the tribe. Now they will understand who is worth dealing with.}
{302}{}{Oscar has escaped from the pueblo and will no longer interfere with your plans.}
{303}{}{This is a victory! The Rangers fled and thus fell in the eyes of the savages to the level of a cowardly iguana. Now these savages will understand who is worth dealing with.}
{304}{}{Glad to help, Commander!}
{1304}{}{I was glad to help, Commander!}
{305}{}{Ahem. Actually, you know WHO solved this problem.}
{306}{}{You have served the empire well. The rest would have the same amount of willpower and fighting fortitude. I'm glad we ended up on the same side.}
{1306}{}{You have served the empire well. The rest would have the same amount of willpower and fighting fortitude. I'm glad we ended up on the same side.}
{307}{}{Do you think Aaron's empire still needs heroes?}
{308}{}{Of course. I will send a letter of recommendation addressed to you in Phoenix. Go straight to Aaron, he values my word.}
{309}{}{Thank you.}
{310}{}{No, don't thank me. We are doing a common cause. Good luck on the way, comrade.}
{311}{}{Good luck.}

{320}{}{Who are you? And who are all these people?}
{321}{}{Tell us about yourself and your squad.}
{322}{}{George Crook, field commander of His Majesty Aaron of Phoenix. And this is my loyal squad. When we clear the territory of the enemies, a group of ordinary settlers will come after us.}
{323}{}{It was nice to chat. But I have to go.}
{324}{}{Isn't the title too long for the lord of one city?}
{325}{}{Hold your tongue. Aaron's empire is quite large and is constantly expanding. Soon all of Arizona will be at his mercy.}
{326}{}{Once again - who are you?}
{327}{}{Where did you all come from?}
{328}{}{We came from Phoenix to establish a colony here. But this place has already been occupied by savages.}
{329}{}{And where is this Phoenix?}
{330}{}{The city is southeast of here. But it's strange that you don't know that. It seems to be the largest city for miles around.}
{331}{}{I don't know. I'm actually from a village in the opposite direction.}
{332}{}{Then it's clear. These are Ranger lands. It is not surprising that there are only villages in your area and no civilization. Take a look at Phoenix, see what a normal city is.}
{333}{}{I'll do that. Thanks for the advice.}
{334}{}{I don't care about this "civilization" of yours.}
{335}{}{Tell me about the tribe.}
{336}{}{This is a tribe of pastoralists and nomads. Phoenix residents have long had a difficult relationship with them.}
{337}{}{By the way, what do you know about the locals?}
{338}{}{It seems you don't like them?}
{339}{}{Savages! They crawl like fleas in the desert. And once you settle in the old ruins, they immediately claim this land.}
{340}{}{Go on.}
{341}{}{Some radical clans even attack civilians. Phoenix has been trying to negotiate peace for several years. And some clans even went over to our side. But not all of them. Now my squad also felt the stubbornness of the savages on their own skin. }
{342}{}{Now I understand why you are so bristling with weapons. Peace to you. And I have to go.}
{343}{}{Are you from Phoenix too?}

{350}{}{You must leave San Brahmin. You and your whole squad.}
{351}{}{What are you talking about?}
{352}{}{Well, you don't want to anger the tribe, right?}
{353}{}{First of all, I want to put these savages in their place. You would also do well to reconsider your views on life.}
{354}{}{Okay. I won't argue.}
{355}{}{If you don't leave, blood will be shed.}
{356}{}{Whoever sent you, tell them that George Crook knows no fear. Words can't intimidate me.}
{357}{}{Well, I warned you. Now the blood will flow like a river!}
{1357}{}{Well, I warned you. Now the blood will flow like a river!}
{358}{}{Okay. I heard you.}
{1358}{}{Okay. I heard you.}
{359}{}{The tribe is ready for decisive action. Your appearance only gives them a reason.}
{360}{}{I know that savages will not give up so easily. They are too far from the ideal of the New World that my lord is building. But that is why my mission is so important - to show the savages that they live in an outdated and incorrect way. Show that there is a better world.}
{361}{}{Okay. I won't argue.}
{362}{}{However, angering them will only scare the tribe away from their ideals. Give them time to think. In the end, your mission will end in nothing if they attack.}
{363}{}{Thousands of savages! I'm already thinking about returning to Phoenix myself. My people are tired, there are not enough supplies for everyone, and then there are savages watching from behind a dune.}
{364}{}{So what have you decided?}
{365}{}{Okay. We'll leave. But only to return with renewed vigor.}
{366}{}{A reasonable decision, Commander. Good luck on the way.}