{100}{}{You see a missionary.}
{101}{}{You see one of the soldiers. They are completely covered in combat gear.}

{110}{}{You should talk to the commander.}
{111}{}{Good for you that you are not from that pastoralist tribe.}
{112}{}{The commander is the one that brought us here. So talk to *him*.}
{113}{}{Want some of that food? Well, I ain't sharing a ration with you.}
{114}{}{I don't know about the others, but I intend to live.}
{115}{}{Looks like we're stuck here for a long time.}

{150}{}{Sings an old song, jealously looking at your carbine.}
{151}{}{ˆ Carabina Treinta Treinta ˆ}
{152}{}{ˆ Que los rebeldes portaban ˆ}
{153}{}{ˆ Y decšan los maderistas ˆ}
{154}{}{ˆ Que con ellas no mataban. ˆ}
{155}{}{ˆ Con mi 30/30 me voy a pelear ˆ}
{156}{}{ˆ Ingrese a las filas de la rebeliƒn ˆ}
{157}{}{ˆ Si mi sangre piden, mi sangre les doy ˆ}
{158}{}{ˆ Por los habitantes de nuestra naciƒn. ˆ}
{159}{}{ˆ}

{160}{}{Phew, this is finally over.}
{161}{}{We won! Hooray!}
{162}{}{Those savages know nothing about fighting. This was an easy victory.}
{163}{}{Now, no savage tribe will dare go against us.}
{164}{}{The Rangers flee to the west like cowards.}
{165}{}{Yes! Now we are the masters of this land.}

{170}{}{Damned savages!}
{171}{}{I don't want to go back to Phoenix after *this*.}
{172}{}{Those savages will regret driving us back.}
{173}{}{Finally, we will return home.}
{174}{}{If the commander is fleeing from the battlefield, we have no business here.}
{175}{}{I was told that I shouldn't get involved in this war. I laughed at them then. But now...}