{100}{}{You see Oscar.}
{101}{}{You see a middle-aged man. He's wearing gloves and has a revolver in his holster.}
{102}{}{I wish I could use your technologies to drive out the missionaries.}
{103}{}{Soon I will have to leave the pueblo. The Rangers aren't welcome here anymore. Very tragic.}
{104}{}{Thanks for the help. Your courage will go down in history.}
{105}{}{We'll meet again, amigo.}
{106}{}{It would be best for you if our paths don't cross in the future.}
{107}{}{I need to prepare for battle. We'll meet near the missionary camp.}

#Before receiving quest
{200}{}{Hello}
{201}{}{Bye}
{202}{}{[Cheat: get outta this pueblo, Ranger]}
{203}{}{[Cheat: you're winner]}
{204}{}{[Cheat: gib quest to terminate missionaries]}

{210}{}{Wait. Just look at that. Who are *you*? One of the missionaries?}
{211}{}{No, I'm a simple traveler. I want nothing to do with the local affairs.}
{212}{}{No, no, I'm from a ruined village to the north-west.}
{213}{}{A village? There are barely any settlements there. I think you're lying.}
{214}{}{I'm telling you... Ah, nevermind. Are you from there?}
{215}{}{That will remain a secret. Better worry about yourself.}
{216}{}{See you later, stranger.}
{217}{}{Okay. Suppose I'm lying. Then what?}
{218}{}{I don't like you. You're just like everyone who came from the east. If I learn that you're are a spy for those missionaries, you'll get a bullet to your head right away.}
{219}{}{I was allowed here by the chieftains.}
{220}{}{Good for you. If I was them, I wouldn't do that.}
{221}{}{I'm not from the east. I'm from the north-west.}
{222}{}{See you later, stranger.}
{223}{}{Why were *you* allowed? Aren't you an outsider?}
{224}{}{Supreme Leader Jeronimo sent me to you. How can I help?}
{225}{}{Well, one more person could help me out quite well.}
{226}{}{I wouldn't be so rash, if I was him. But one more person wouldn't hurt.}
{227}{}{Report the situation, Ranger.}
{228}{}{So you are Ranger Oscar? I was sent here by general Mossman. He's demanding a report.}
{229}{}{Strange... I don't understand why he sent you, and not a Ranger... But the general knows best.}

{230}{}{I was sent to San-Brahmin to restore order. The tribe is trying to retain it's freedom and independence from the Phoenixian empire. The situation is complicated and could transition from local skirmishes to real warfare any moment now.}
{231}{}{Go on.}
{232}{}{More to the point, please.}
{233}{}{A unit of Phoenixians has come from the east. They have set up their camp near the pueblo and are trying to drive out the tribe. They say they simply want to establish a trade agreenment with them, but that's an obvious lie.}
{234}{}{How so?}
{235}{}{No empire in history has been that courteous to native tribes during a time of expansion. As soon as the alliance is established, the tribe will be disarmed and the brahmin will be redistributed to those who will obey the will of the emperor.}
{236}{}{[Listen]}
{237}{}{Phoenix must not be trusted. It is a hive of bandits and opportunists. They simply don't know any other life. Meanwhile, the pastoralist tribe has spent generations creating it's own culture and traditions. We can't allow their way of life to be ended by the greed of rich city-dwellers.}
{238}{}{Alright. So, you want to drive back the missionaries to the city?}
{239}{}{Our forces are not equal. We can't fight an open battle. The Phoenixians have begun to divide the tribe by spreading their ideas among the young generation. Help me prepare a unit to drive back the missionaries. You need to treat the wounded and talk some sense into the son of the chieftain, Chatto.}
{240}{}{Alright. I'll see what I can do.}
{241}{}{I doubt your unit will manage. I'll try to find another way.}

{242}{}{Hello, cultist. What are you expecting from me? Oh, I know - a bullet to the head.}
{243}{}{Wait a minute...}
{244}{}{What are you doing...}
{245}{}{Get out of here, out of the lands of the pastoralists. Nobody asked Aaron's henchmen to come here.}
{246}{}{Fine... I'm leaving.}
{247}{}{Another Ranger? A surprise to be sure, but a welcome one. Headquarters didn't tell me about you. Are you here on your own initiative?}
{248}{}{No, I'm just passing by. What's going on here, exactly? Do you need any help?}
{249}{}{This place is just a temporary stop for me. Sorry, I'll have to go soon. Maybe we'll see each other again later.}

{250}{}{Didn't I tell you to get out of the pueblo? If you don't leave, it'll be your corpse leaving this holy land.}
{251}{}{This was a mistake. Give me a chance, I'll make it right!}
{252}{}{You have no power here. You are an outsider, just like me. So sit down and shut up.}
{253}{}{Looks like you can't drive me out of here. What's the matter, idiot? Fingers already itching? Do it! Take out the revolver, you son of a bitch!}
{254}{}{Let's discuss the plan again. What needs to be done?}

{260}{}{You must leave the pueblo immediately. Commander Crook is giving you your last chance to escape the death penalty.}
{261}{}{You can't scare me with death. I went on this mission fully aware of the risks. But my goal is more important than my life. I was trying to save a tribe from extermination or enslavement at the hands of an imperial army.}
{262}{}{It's over. The elders have given their support for a peace treaty with the missionaries.}
{263}{}{I see. Those missionaries have completely clouded their judgement. There is no sight more tragic than the powerlessness of leaders.}
{264}{}{The majority has turned against you. Now, are you going to leave?}
{265}{}{And so, I have to return to base with nothing. But don't you think the Desert Rangers are just going to leave this as it is. The Phoenixian empire cannot be allowed to destroy entire cultures for power and resources.}
{266}{}{Don't fret. You'll have an opportunity at vengeance. Probably.}
{267}{}{Right. Leave.}
{268}{}{So you're not going to leave?}
{269}{}{No. I will remain to protect the tribe during the siege. And I will not be alone. There are still people ready to fend for themselves in the tribe.}
{270}{}{Whatever you say. You've been warned.}
{271}{}{Do whatever you want. My job was just to warn you.}
{272}{}{The desert teaches to hide in the shadows and wait for the right moment to strike. Use this tactic, otherwise, you will only face defeat.}
{273}{}{Sometimes it is better to retreat, to return in greater numbers later. Is this not such a situation?}
{274}{}{Parker Dam was flooded and destroyed. Your brass will no longer be able to support fighting in San-Brahmin.}
{275}{}{It's over. The supreme leader has cut ties with the Rangers.}

#After receiving the quest
{300}{}{Report. Any information about the enemy will be invaluable.}
{301}{}{Nothing to report yet.}
{302}{}{Good to see you, Ranger.}
{303}{}{Good to see you, amigo.}

{310}{}{I want to ask you about the Desert Rangers.}
{311}{}{We represent Law and Order in these lands.}
{312}{}{Do the Rangers have a base?}
{313}{}{A headquarters to the west and many outposts all over South Arizona. But it would be a bad idea to give you their exact coordinates.}
{314}{}{A headquarters to the west and many outposts all over South Arizona. But you already know where they are located.}
{315}{}{Where's your badge, Ranger?}
{316}{}{I only removed it to not make an already complicated situation even worse. When the mess currently happening in the pueblo is resolved, the badge will be right back on my chest.}
{317}{}{I don't understand. Why are the Rangers participating in this war?}
{318}{}{We have two goals - to befriend the tribe and to stop Phoenix's expansion.}
{319}{}{Isn't being forced to follow laws against the tribe's traditions?}
{320}{}{The simple rules are equal for all - do not kill senselessly, do not steal from others. About local traditions, we Rangers have to accept them and make some adjustments.}
{321}{}{Alright.}

{330}{}{The missionaries are fleeing back to Phoenix.}
{331}{}{You have incredible diplomatic prowess. I don't know how you managed to do it, but you have my thanks.}
{332}{}{It was nothing. They were quite easily intimidated.}
{333}{}{It wasn't easy. But our great mission demands sacrifice.}
{334}{}{General Mossman didn't give you such an important mission for nothing, it seems. He's good at finding capable people. Now I will be able to return to base. This was a long and tense mission. I'll rest there for a while.}
{335}{}{Good luck, Oscar.}
{336}{}{The Rangers need people like you. Go to our base at Parker Dam. I'll send a letter of recommendation to the general.}
{337}{}{Thank you, Ranger. If I happen to be in those lands, I will head to the general right away.}

{340}{}{Chatto has refused the support of the Phoenixians.}
{341}{}{Those are good news. Our chances of victory have heavily increased.}
{342}{}{What else needs to be done?}
{343}{}{We still have to deal with the soldiers. Some of them are wounded. It is scaring the pastoralists, and some of them could participate in battle, if the soldiers were healed.}
{344}{}{I'll do it.}
{345}{}{Thank you. Excellent initiative. But if you cannot do it yourself, at least bring medicine. I'm sure some could be stolen from the missionaries.}
{346}{}{Already on my way.}
{347}{}{But I am no doctor.}
{348}{}{Then bring medicine. I'm sure some could be stolen from the missionaries.}
{349}{}{Already on my way.}
{350}{}{All the wounded are healed. We can begin the fight.}
{351}{}{Excellent. The only thing that's left is to bring them together and explain the mission to them. We'll meet to the north of the missionary camp. Expect a difficult fight.}
{352}{}{Already on my way.}
{353}{}{Chatto will no longer be able to interfere. He's dead.}
{354}{}{Those are not very good news. Chatto was the leader among the youth and could have changed the minds of his fellow tribesmen. We can only hope that none of them will stand in our way.}
{355}{}{Then you have no choice. Crook is expecting your attack. Go, show what you are capable of, Ranger!}
{356}{}{Head to Crook and tell him that I accept his challenge. If he wants a fight, he'll get one.}
{357}{}{Bye.}
{358}{}{Excellent work. But what about Chatto? Have you managed to convince him?}
{359}{}{I have not yet managed to talk to him.}

#during the fight
{360}{}{Hm. Doesn't look like the missionaries are prepared for a fight. Their self-confidence will work to our advantage. A good time to begin the assault.}
{361}{}{Ranger Oscar, could I conduct reconnaissance on them? I'll be back soon.}
{362}{}{Let the battle begin!}
{363}{}{Report: the missionaries are fleeing!}
{364}{}{Victory is with us! (the tribe's warriors rejoice) I still need some time to look around this place. You head to the pueblo. I'll be there soon.}
{365}{}{Until next time.}
{366}{}{Then you will die like a dog. Whining and vainly begging for mercy.}
{367}{}{Enough! Your time has run out, Ranger...}
{368}{}{Drive the Phoenixians back!}
{369}{}{For-ward!}
{370}{}{If Crook with all his henchmen doesn't immediately capitulate, we will have to drive him back with force.}
{371}{}{I'll tell him your requirements.}
{372}{}{The battle is over. We won!}