{100}{}{Here is a ranger.}
{101}{}{You see a ranger in combat gear. He carefully examines the pueblo.}

{110}{}{So it is to you that we owe the alliance with the tribe? Well done, good job.}
{111}{}{You're doing a great job, comrade.}
{112}{}{The general sent us to guard the leader.}
{113}{}{You're on our side, aren't you?}
{114}{}{The big chief is waiting for you. Come in.}
{115}{}{You can pass.}
{116}{}{*Salutes you*}

{120}{}{You shouldn't have come here.}