{100}{}{You see a Ranger.}
{101}{}{You see a Ranger in a combat vest. He is carefully watching over the pueblo.}

{110}{}{So you're the one we should be thanking for an alliance with the tribe? Good work, bud.}
{111}{}{You're doing very important work here, comrade.}
{112}{}{The General has sent us here to protect the chieftain.}
{113}{}{You *are* on our side, right?}
{114}{}{The head chieftain is waiting for you. Move along.}
{115}{}{You can move along.}
{116}{}{*Pays you respects*}

{120}{}{You should have never come here.}