{100}{}{You see a nomad.}
{101}{}{You see a man with long, black hair.}
{102}{}{Ooh. The mushrooms ended up being more potent than I thought...}

{200}{}{What do you need, outsider?}
{1200}{}{What do you need, outsider?}
{201}{}{Leave me alone, outsider.}
{1201}{}{Leave me alone, outsider.}
{202}{}{Why?}
{203}{}{Go on, pretend to be ignorant some more. I don't need anything from you, anyways. And while we talk, time goes on. And I have things to do, places to go.}
{204}{}{Like where?}
{205}{}{My family is preparing to head out into the desert. We must manage to do that at the beginning of the sandstorm season. And I just can't manage to repair this cart.}
{206}{}{Is that such a big problem?}
{207}{}{Before, we could barter for components or ask some of you palefaces. But now you wage war against us. Nobody can repair the cart other than me. And even I can't do it.}
{208}{}{I can.}
{209}{}{I don't need anything from outsiders.}
{210}{}{Outsiders aren't one big group. I'm not with those who are attacking you. Let me help you.}
{211}{}{So you'll do it? Hm, alright. But don't expect compensation.}
{212}{}{No problem. You can trust me.}
{213}{}{No compensation? Well, then I won't be in a hurry to fix it.}
{214}{}{I'll repair the cart, but components cost bottle caps. I'll need compensation.}
{215}{}{You say not all outsiders are the same, but I see you palefaces are all obsessed with clanking garbage. I don't have anything like that. But if you repair the cart, I will give you some jerky.}
{216}{}{I'll think about it.}
{217}{}{I doubt it's going to be good jerky. Go repair the cart yourself.}

{220}{}{What do you need, outsider?}
{1220}{}{What do you need, outsider?}
{221}{}{Leave me alone, outsider.}
{1221}{}{Leave me alone, outsider.}
{222}{}{Peace be unto your house.}
{223}{}{We'll see each other again sometime.}

{230}{}{Your cart is in working order.}
{231}{}{You really did it! There was so much harm from palefaces before that I doubted you would even finish it. A shame that we cannot live in peace.}
{1231}{}{You really did it! There was so much harm from palefaces before that I doubted you would even finish it. A shame that we cannot live in peace.}
{232}{}{And you won't give me anything for this?}
{233}{}{(sigh) I knew I couldn't trust you. You're just like all the other palefaces, you only think about yourself. And that's what distinguishes outsiders from us.}
{234}{}{Whatever.}
{235}{}{Isn't it fair to get a reward for hard labour?}
{236}{}{Fine, here, take a jerky. But I can't give you anything else. I need to get ready to head out.}
{237}{}{So long.}
{238}{}{I do not need anything in exchange. I am helping to foster peace.}
{239}{}{First time I saw a selfless outsider. Thank you. Let the Brahmin of the Wasteland show you the way in hard times.}

{250}{}{What's the problem with repairing the cart?}
{251}{}{In our tribe, we can craft things out of skin, but not repair carts. Before, we could ask palefaces to do it in exchange for meat and skin. Now there is nobody we can ask.}
{252}{}{Alright.}
{253}{}{Why are you heading out into the wasteland with your entire family?}
{254}{}{We roam the Sonora desert, and in bad seasons, we gather here with the rest of the tribe. Staying in one place, we cannot feed ourselves. Brahmin need grass, and grass needs time to grow. There isn't enough water here for everyone, either.}
{255}{}{Alright.}

{260}{}{What do you think about allying with outsiders?}
{261}{}{If you run after two pigrats at the same time, you'll tear your pants. One can't look to the east and the west at the same time.}
{262}{}{I understand what you mean.}
{263}{}{We must remain ourselves, as long as we have the strength to do so. And if we do not have the strength, then it will not be us who decides who we are allied to. Whoever is stronger will become our overlord.}
{264}{}{Sorry for asking such big questions.}