{100}{}{You see a nomad.}
{101}{}{You see a man with long black hair.}
{102}{}{Oh, these mushrooms turned out to be more powerful than I thought...}

{200}{}{What do you need, stranger?}
{1200}{}{What do you need, stranger?}
{201}{}{Leave me, stranger.}
{1201}{}{Leave me, stranger.}
{202}{}{Whoa, why so much distrust?}
{203}{}{Keep pretending you don't understand. I don't need anything from you anyway. But time flows like sand between your fingers. I have to hurry.}
{204}{}{Where are you in a hurry?}
{205}{}{My family is preparing to go out into the desert. We should be in time for the start of the dust storm season. And I still can't fix this cart.}
{206}{}{Is this that much of a problem?}
{207}{}{Previously, we could exchange parts or ask for one of your palefaces. But now you are waging a war against us. No one will fix the cart except me. And I can't do it.}
{208}{}{I can.}
{209}{}{I don't need anything from outsiders.}
{210}{}{Let me help you. I want to show you that not all outsiders are the same.}
{211}{}{Will you do it? Hmm, okay. But I won't give anything in return.}
{212}{}{No problems. You can rely on me.}
{213}{}{Nothing at all? Well, then I won't be in a hurry.}
{214}{}{I'll fix the cart, but not for nothing. The parts are worth the caps, you know.}
{215}{}{It seems that all the palefaces are obsessed with the sound of all sorts of garbage. I don't have anything like that. But if you would fix the cart, I'll give you dried meat.}
{216}{}{I will think about this proposal.}
{217}{}{Surely you will slip me bad meat. Do the cart yourself.}

{220}{}{What do you need, stranger?}
{1220}{}{What do you need, stranger?}
{221}{}{Leave me, stranger.}
{1221}{}{Leave me alone, stranger.}
{222}{}{Peace be upon your home.}
{223}{}{See you again.}

{230}{}{Your cart is in perfect order.}
{231}{}{You really did it! There was so much harm from the Palefaces that I didn't even hope. It's a pity we can't live in peace.}
{1231}{}{You really did it! There was so much harm from the Palefaces that I didn't even hope. It's a pity that we can't live in peace.}
{232}{}{And you won't give me anything for this service?}
{233}{}{(sigh) I knew I couldn't trust you. You're just like the rest of the palefaces, thinking only of yourself. That's how we differ from you.}
{234}{}{Don't even start.}
{235}{}{Isn't it fair to get a reward for your work?}
{236}{}{Okay, here's the jerky. But don't ask for anything else. I need to prepare for the journey.}
{237}{}{Happily.}
{238}{}{I don't need anything in return. I help for the sake of peace.}
{239}{}{This is the first time I've seen a disinterested outsider. Thank you. Let the Brahmin of the Wasteland show you the way in a difficult hour.}

{250}{}{What's the problem with fixing the cart?}
{251}{}{In our tribe, they know how to make leather, but not to repair carts. We used to ask the Palefaces for this in exchange for meat and skins. And now there is no one to ask.}
{252}{}{I see.}
{253}{}{Why are you going to the wasteland with your whole family?}
{254}{}{We wander through the Sonoran desert, and in bad seasons, the whole tribe gathers here. Standing still, we will not feed ourselves. Brahmins need grass, and grass needs time to grow. There is not enough local water for everyone either.}
{255}{}{I see.}

{260}{}{How do you feel about an alliance with outsiders?}
{261}{}{If you chase two mole-rats, you'll tear your pants. You can't look both west and east at the same time.}
{262}{}{I think I know what you mean.}
{263}{}{We must remain ourselves as long as we have enough strength. And if there are not enough forces, then we will no longer decide with whom to make alliances. Whoever is stronger will become a shepherd for us.}
{264}{}{Sorry for such a painful question.}
