{100}{}{You see nothing.}
{101}{}{You see nothing.}
{102}{}{The light begins to shine through your closed eyelids.}

{110}{}{The birds are singing.}
{111}{}{The weather is warm, but not too warm.}
{112}{}{Your sense of touch comes back: you begin to feel a wooden bench. You are sitting on it.}
{113}{}{Someone touches your shoulder - strangely enough, with both hands at the same time.}
{114}{}{They must be tied together.}

{120}{}{Finally, a sound you are most familiar with - }
{121}{}{human speech.}
{122}{}{Your ears fail you at first, but only a moment later...}

{200}{}{ (is that music?) }
{201}{}{ (are these hoofbeats?) }
{202}{}{ (is that a word, a name, a clue?) }
{203}{}{ (why are the letters all capital?) }

{204}{}{Hey you, you're finally awake. You were trying to cross the border, right?}
{205}{}{It all falls back apart}
