{100}{}{There is a guard in front of you.}
{101}{}{You see a man of Mexican appearance.}
{102}{}{Muchas gracias, señor.}
{1102}{}{Muchas gracias, señor.}
{103}{}{The guard breaks into a smile. It looks like he's not up to his duties right now.}

{110}{}{Vete, traidor!}
{111}{}{No hay nada.}
{112}{}{No toques la puerta.}

{120}{}{Get out!}
{121}{}{No entry allowed.}
{122}{}{Don't touch that door.}
{123}{}{You can't go there.}