{100}{}{Here is Ilario.}
{101}{}{You see a strong old man in a magnificent religious attire by local standards.}
{102}{}{You have no idea what you've done.}
{1102}{}{You have no idea what you've done.}
{103}{}{(}
{104}{}{/3) You talked to the residents about the holiday.}

{110}{}{}

#Phrases of the opening cut scene
{120}{}{Brothers and sisters! Today is an important day for us. This is the day of life.}
{121}{}{The day when we have the right to say: yes, we are still alive. We were able to live another day. Many were unlucky, but we managed.}
{122}{}{Thank our saints for this good, who protect us from wild beasts and robbers...}
{123}{}{And that's all... Only... Oh, uh...}
{124}{}{Lucia, today is your big day.}
{125}{}{Go to the church and finish the ceremony. You know what to do. And we will pray.}

#The first dialog
{200}{}{(at the sight of you, the crowd falls silent and moves aside; there is a tense pause) Uh-uh... I think we have guests... What a surprise!}
{201}{}{I was just passing by and heard the fun. What's going on here?}
{1201}{}{I was just passing by and heard the fun. What's going on here?}
{202}{}{What's going on? Oh, gringos, we celebrate the day of our saints. You're at the celebration of life! Help yourself and make yourself at home. We welcome everyone... who will not interfere with us.}
{203}{}{During my journey, I see such a happy society for the first time. I will be glad to linger on your holiday.}
{1203}{}{During my journey, I see such a happy society for the first time. I will be glad to stay on your holiday.}
{204}{}{All the friendly people I met tried to deceive me. I hope you are an exception.}
{205}{}{Well. Bienvenido, gringo. If you have any questions, please contact me immediately. My name is Ilario Lopez Andrade. I am the village headman and part-time head priest. So! Why is everyone quiet? Let's continue, brothers and sisters!}
{206}{}{Thank you for your hospitality.}
{207}{}{Okay, I'll stay here for a while.}
{208}{}{}
{209}{}{}
{210}{}{So, amigo, you probably have a lot of questions. I'd like to know more about you, too, but I'm not up to it right now. Someone stole the crown for our ceremony. And we can't find her. It is difficult to carry out a coronation without a crown. It would be a violation of our traditions.}
{211}{}{I see you're not up to talking right now. I'll come back later.}
{212}{}{Then I'll try to find this thing.}
{213}{}{Are you looking for this crown?}
{214}{}{Yes, this is it! How did you manage to find her?}
{215}{}{Well, she was lying on the ground nearby.}
{216}{}{Are you saying she disappeared by accident? Ugh, I was already worried that one of the residents had sinned. Now I'm calm. You know, we are the most peaceful settlement in the whole world of God. No one has been committing crimes here for many years.}
{217}{}{That's great.}
{218}{}{Really?}
{219}{}{It was the antics of a teenager. I don't know what motivated him.}
{220}{}{Oh, I guess... Simple excitement, hot blood in a brave body. Nevermind.}
{221}{}{Good if so.}
{222}{}{Really?}
{223}{}{Now I can finish the ceremony. This is our glorious old tradition. Every few months we hold a coronation of one of the residents to remind everyone of equality and that everyone has the opportunity to become useful to the community. This time the honor fell to Lucia. Lucia, come closer...}
{224}{}{[Watch the ceremony]}
{225}{}{The ceremony is so tiring. But I'm not quite young anymore. I need to lie down to rest.}
{226}{}{[Leave the headman alone]}
{227}{}{Why is the church locked?}
{228}{}{You shouldn't go in there. Until the ceremony is over, ordinary residents are also prohibited from entering the church. This is a sacred place for us. Please don't desecrate it.}
{229}{}{Okay.}

{230}{}{What are you doing here, you damn gringo?! How dare you desecrate our sanctuary?!}
{231}{}{Don't worry, old man. The monster in the basement is dead. You have nothing to fear anymore.}
{232}{}{M-is dead?! (contrite) You... WHAT HAVE YOU DONE!!!}
{1232}{}{ M-dead?! (contrite) You... WHAT HAVE YOU DONE!!!}
{233}{}{Well, I killed a monster. It die. Dead. Went back to hell. Do you understand?}
{1233}{}{Well, I killed a monster. It die. Dead. Went back to hell. Do you understand?}
{234}{}{Why are you doing this to us?! Do you even realize that El Diablo was our patron?}
{235}{}{Did you worship a monster? Seriously?}
{236}{}{He protected us from strangers and wild animals, he cleansed the community of lepers and the infirm, people rallied thanks to El Diablo. There has not even been theft among our people for many years. Without him, our entire long-term way of life will fall. Can you imagine what shocks are waiting for us now?}
{237}{}{Well, you'll probably come up with something. Someday your "patron" would have died anyway.}
{238}{}{Ah, so you're worried about your power, elder? Now it will be more difficult for you to unite people and rule them. That's right.}
{239}{}{I see right through you, gringo. If you die, it will make the world feel better. And I won't let you leave this church.}
{240}{}{Try to stop me, holy man.}
{241}{}{You're making a big mistake...}
{242}{}{That's what, gringo. Go away and never come back.}
{243}{}{Don't you dare threaten me, old man. Believe me, it's not in your best interest.}
{244}{}{My business here is really over. Goodbye, headman.}
{245}{}{After all you've heard and seen, it's not enough to execute you.}
{246}{}{Don't you dare come back! Do you hear? Go away!}
{247}{}{Yeah, yeah, whatever you say, silly old man.}
{248}{}{Why else is here?}
{249}{}{I'm leaving now. Just, uh, forgot my stuff. Goodbye.}
{1249}{}{I'm leaving now. I just, uh, forgot my stuff. Goodbye.}
{250}{}{You don't belong in Santa Ana. Now the whole population is against you. Go away.}
{251}{}{For fifteen years I have protected the inhabitants. And that's how they repaid me! Now that El Diablo is not with us, anyone can blame me. Do you know how hard this sacrifice was? How did I suffer the first years? But I did what I was elected headman for - I saved the residents. And now you're saying it was wrong? To hell with your opinion, gringo!}
{252}{}{Looks like you're not going to be persuaded. It's better if you just die!}
{253}{}{Whatever you say. This is already your internal affairs. Bye, headman.}
{254}{}{You don't belong in Santa Ana. Now the whole population is against you. Go away.}
{255}{}{For fifteen years I have protected the inhabitants. And that's how they repaid me! Now that El Diablo is not with us, anyone can blame me. Do you know how hard this sacrifice was? How did I suffer the first years? But I did what I was elected headman for - I saved the residents. This completes my mission. I'm clean. If you have to choose exile to give people peace, let it be. I'm leaving.}
{256}{}{Unexpectedly the right decision. You're being wise, old Ilario. Goodbye.}
{257}{}{I'll help you find a new place to live... this place is in hell!}