{100}{}{You see Ilario.}
{101}{}{You see a strong-looking old man in opulent religious clothing. At least, by local standards.}
{102}{}{You have no idea what you have just done.}
{1102}{}{You have no idea what you have just done.}
{103}{}{(}
{104}{}{/3) You talked to the inhabitants about the celebration.}

{110}{}{}

#Intro cutscene
{120}{}{Brothers and sisters! Today is an important day for us. Today is the day of life.}
{121}{}{The day when we can rightfully say: yes, we are still alive. We have managed to live another day. Not everyone was lucky enough to make it, but we did.}
{122}{}{For this, thank our saints, that protect us from the wildlife and bandits...}
{123}{}{And only... Only... Oh, uhh...}
{124}{}{Lucia, today is your great day.}
{125}{}{Go into the church and finish the ritual. You know what to do. We will be praying.}

#First dialogue
{200}{}{(upon seeing you, the crowd immediately turns quiet and makes way for you; there is an awkward silence) Ummm... It looks like we have guests... How unexpected!}
{201}{}{I was just walking by and heard people celebrating something. What's going on?}
{1201}{}{I was just walking by and heard people celebrating something. What's going on?}
{202}{}{What's going on? Ooh, gringo, we're celebrating the day of our saints. The day of life! Make yourself at home. We're happy to see people from other places... as long as they don't make trouble.}
{203}{}{I've been traveling for a long time. This is the first time I saw such a happy community. I'll be glad to spend some time here and celebrate with you.}
{1203}{}{I've been traveling for a long time. This is the first time I saw such a happy community. I'll be glad to spend some time here and celebrate with you.}
{204}{}{I've met plenty of seemingly welcoming people. They were all trying to fool me. I hope you're an exception.}
{205}{}{Well, bienvenido, gringo. If you have any questions, make sure to ask me right away. My name is Ilario Lopez Andrade. I'm both the village's elder and the head priest. So! Why is everyone so quiet? Let us continue the celebration, brothers and sister!}
{206}{}{Thank you for your hospitality.}
{207}{}{Alright. I won't be staying here for long.}
{208}{}{}
{209}{}{}
{210}{}{So, amigo, you must have many questions. I would like to learn more about yourself, too, but now is not the time. Someone stole the celemonial crown. We cannot find it. It will be very difficult to hold the coronation without a crown, and not only that - it will be a violation of our traditions.}
{211}{}{I'll talk to you again later.}
{212}{}{Then I'll try to find it.}
{213}{}{Is this the crown you're looking for?}
{214}{}{Yes, it is! Where did you find it?}
{215}{}{It was just lying on the ground not too far away from here.}
{216}{}{You mean to tell me that it wasn't stolen, but lost? And here I was, worrying that one of our people had sinned. I am at peace now. You know, we are the most peaceful communities in all of Creation. No crime has been commited here for many years.}
{217}{}{That's great.}
{218}{}{Really?}
{219}{}{A kid stole it. Don't know why.}
{220}{}{Oh, I can guess... Too much excitement in a small, youthful body. Don't mind it.}
{221}{}{Good, if that's the case.}
{222}{}{Really?}
{223}{}{Now I will be able to conclude the ceremony. It is an old, great tradition of ours. Once in a few months, we hold a coronation for one of our people, to remind us all that we are equal, and that we all can help the community. This time, Lucia received the honor. Lucia, come closer...}
{224}{}{[Watch the ceremony]}
{225}{}{These ceremonies are so tiring. My days of youthfulness are long gone. I have to rest.}
{226}{}{[Allow the elder to rest]}
{227}{}{Why is the church locked?}
{228}{}{Do not go there. Until the ceremony is concluded, no one can enter the church - this includes our people as well. It is a holy place to us, you see. To enter it during the ceremony would defile it.}
{229}{}{Okay.}

{230}{}{What are you doing here, you damned gringo?! How dare you defile our sanctuary?!}
{231}{}{Don't worry, old man. It wasn't easy, but I managed to kill that monster in the basement. You have nothing to fear anymore.}
{232}{}{D-dead?! (defeated) You... WHAT HAVE YOU DONE!!!}
{1232}{}{D-dead?! (defeated) You... WHAT HAVE YOU DONE!!!}
{233}{}{I killed the thing. It's dead. It's not a threat to anyone anymore. Don't you understand?}
{1233}{}{I killed the thing. It's dead. It's not a threat to anyone anymore. Don't you understand?}
{234}{}{What for?! Do you even realize what El Diablo meant to us? Did you realize he was our protector?}
{235}{}{You worshipped that thing?... Seriously?}
{236}{}{El Diablo protected us from outsiders and wild animals! He freed the community from the burden of the feeble and the sick! The people rallied together, all thanks to El Diablo! Even theft dissapeared among our people! You ended our way of life! Do you even begin to realize what ruin awaits us?}
{237}{}{I'm sure you'll figure out something. Besides, your "protector" wasn't immortal. One day it would have died.}
{238}{}{You're worried about your power, aren't you, elder? Yeah, you'll find it much harder to group people together into an easily-ruled group now. That's for sure.}
{239}{}{I see right through you, gringo. The world will be better off without you. I won't let you leave this church.}
{240}{}{Just try and stop me.}
{241}{}{You're making a big mistake...}
{242}{}{Listen, gringo. I will allow you to leave - but you will never come back.}
{243}{}{I just killed that monster. You think I won't be able to kill you? Believe me, old man: threatening me is not in your best interest.}
{244}{}{My job here truly is done. Goodbye, elder.}
{245}{}{After all I've heard, after all I've seen, executing you is too little of a punishment.}
{246}{}{Don't even think about coming back! You hear me? Go!}
{247}{}{Yeah, yeah, whatever you say.}
{248}{}{Why are you still here?}
{249}{}{I forgot a few of my things.}
{1249}{}{I forgot a few of my things.}
{250}{}{You have no place in Santa Ana. The entire population has now been turned against you. Go.}
{251}{}{For fifteen years, I have protected them, and this is how they repay me! Now that El Diablo has left us, anyone will be able to pin all of the blame on me. You know how hard the sacrifices were to make? How many sleepless nights I had during the first few years? But I did what I was chosen elder for - I saved them. And now you say that I was wrong? To hell with your opinions, gringo!}
{252}{}{You can't change your mind, I see. Then I'll just have to kill you!}
{253}{}{Whatever you say. These are now your internal matters. Goodbye, old man.}
{254}{}{You have no place in Santa Ana. The entire population has now been turned against you. Go.}
{255}{}{For fifteen years, I have protected them, and this is how they repay me! Now that El Diablo has left us, anyone will be able to pin all of the blame on me. You know how hard the sacrifices were to make? How many sleepless nights I had during the first few years? But I did what I was chosen elder for - I saved them. My mission is done. I am clean. If I must face exile to grant them peace, then so be it. I am leaving.}
{256}{}{I didn't expect it, but you did the right thing, old man Ilario. Goodbye.}
{257}{}{I've already found you a new place to live... in hell!}