{100}{}{You see a guard.}
{101}{}{You see a mexican-looking man.}
{102}{}{Muchas gracias, senor.}
{1102}{}{Muchas gracias, senora.}
{103}{}{The guard begins to smile. It doesn't look like he's very concerned with his job at the moment.}

{110}{}{¡Vete, traidor!}
{111}{}{No hay entrada.}
{112}{}{No toques la puerta.}

{120}{}{Get out!}
{121}{}{Entry forbidden.}
{122}{}{Don't touch that door.}
{123}{}{You can't go in there.}