{100}{}{You see a merchant.}
{101}{}{You see a merchant in dusty clothing.}

{200}{}{Hello there! Thanks to you, we have ourselves a new caravan route. I never thought that there could be a village out here.}
{201}{}{What are you even planning to sell here?}
{202}{}{Well, we are currently at the negotiation stage, but Casa Nueva could always use more workers. And the Followers are hoping to grow certain kinds of plants here, ones that don't grow so well in Casa Nueva. We'll see what more we can do here.}
{203}{}{It's good to see that things are getting better. I should go.}

{210}{}{Yes?}
{211}{}{Bye.}
{212}{}{I should go.}

{220}{}{What are you selling here?}
{221}{}{I came here for the negotiations, to look around and learn what the locals need. But if you have something useful, I'm ready to buy it for a fair price.}
{222}{}{I'll keep that in mind. Bye.}
{223}{}{Do you know what happened here?}
{224}{}{No, they aren't telling me. Though, frankly, it's probably better not to know. Everyone has their secrets, that's all well and good. What I care about is not getting shot when I turn around.}
{225}{}{Where do you plan to go after the negotiations?}
{226}{}{Back to Casa Nueva, of course. Why are you asking?}
{227}{}{Just curious. Bye.}
{228}{}{Can I come along with you?}
{229}{}{Of course, I'm very grateful to you for helping us create this new caravan route. But defending you and carrying your items will require compensation. I'm talking 300 caps.}
{230}{}{Here they are. I'm ready to move out.}
{231}{}{Forget it. I'll get there on my own.}
{232}{}{Take me with you to Casa Nueva.}