{100}{}{Here is a merchant.}
{101}{}{You see a merchant in dusty traveling clothes.}

{200}{}{Hi! Thanks to you, we have a new caravan route. And I could not even think that there is a village in these parts.}
{201}{}{How did your settlements interest each other?}
{202}{}{We are still in the negotiation stage. But there are not enough workers in Casa Nueva. And the Followers also hope to grow some plants here that hardly grow in Casa Nueva. Let's see what can be done here.}
{203}{}{It's good that things are getting better. I have to go.}

{210}{}{Yes?}
{211}{}{Bye.}
{212}{}{I have to go.}

{220}{}{What do you sell?}
{221}{}{I came rather for negotiations, to look around and learn about the needs of local residents. But if you have something useful, then I'm ready to trade.}
{222}{}{I'll keep that in mind. Bye.}
{223}{}{Do you know what happened here?}
{224}{}{No, they don't tell. And I don't want to know. Everyone has their own secrets, this is normal. It's only important to me that no one shoots in the back.}
{225}{}{Where will you go after the transaction is completed?}
{226}{}{Back to Casa Nueva, of course. And what?}
{227}{}{Oh, nothing. Bye.}
{228}{}{Can you take it with you?}
{229}{}{Of course, I am grateful to you for opening a new caravan route. But I'm not going to protect you for free and carry your things. Maintenance costs 300 caps.}
{230}{}{Here are the bottlecaps. I can move out.}
{231}{}{Then don't. I'll get there alone.}
{232}{}{Take me with you to Casa Nueva.}