{100}{}{You see Lucia.}
{101}{}{You see a girl in ceremonial attire.}
{102}{}{Thank you. For everything.}
{103}{}{Muchas gracias.}
{104}{}{The wreath has been returned to its rightful owner.}
{105}{}{Looks like this thing's yours. Take it. Do what you want with it.}
{106}{}{It's too early to give it to you.}
{107}{}{Lucia has returned to Santa Ana.}
{108}{}{I met here with Antonio, in secret. They didn't let me enter relationships with anyone.}
{109}{}{A calm, tranquil place. I liked to sit here and think about my fate.}

{110}{}{}

{200}{}{¿TŸ otra vez?}
{201}{}{There you are. I've been looking for you everywhere.}
{202}{}{(turns away)}
{203}{}{... And I'm not the only one. Antonio is looking for you, too.}
{204}{}{(turns around halfway) Antonio?}
{205}{}{Si, seœora. He's looking for you.}
{206}{}{(falls to her feet and sobs) El Diablo... *sob-sob* Tu no entiende, gringo. Vive para esto.}
{207}{}{I can't understand what you're saying, but there's no point in being upset. Let's go to the others.}
{208}{}{(grabs your sleeve) Este es mi destino! He perdido el sentido de la vida!}
{209}{}{Wait. You saying you've been groomed to be sacrificed to that thing for your entire life? I see why you don't want to accept freedom.}
{210}{}{(exhausted) Bueno. Voy a ir a casa. Dejalo Ser.}
{211}{}{That's good. I'll make sure you get home.}
{212}{}{Stay here while I take a look outside.}

{220}{}{You again, gringo?}
{221}{}{There you are. I've been looking for you everywhere.}
{222}{}{(turns away)}
{223}{}{... And I'm not the only one. Antonio is looking for you, too.}
{224}{}{(turns around halfway) Antonio?}
{225}{}{Yes, senora. He stole the wreath from the ceremony to save your life.}
{226}{}{(falls to her feet and sobs) But... El Diablo... *sob-sob* You don't understand, gringo. I was being prepared for this my entire life. I knew this day would come.}
{227}{}{You don't think it's good that you're free now?}
{228}{}{(grabs your sleeve) It was my destiny! I had to go to El Diablo to save the rest of the village!}
{229}{}{I understand why you're so sad. But in every other place I've been to, there are no such things. Nobody's sacrificing their loved ones to monsters.}
{230}{}{(exhausted) Okay... okay... I'll be right back. Come what may.}
{231}{}{That's good. I'll make sure you get home.}
{232}{}{Stay here while I take a look outside.}

{240}{}{Voy.}
{241}{}{Follow me. I'll make sure you get home.}
{242}{}{Wait here and don't go anywhere.}
{243}{}{Let's go.}
{244}{}{Estoy cansada.}
{245}{}{I'm on my way.}
{246}{}{I'm tired.}