{100}{}{You see Antonio.}
{101}{}{You see a local boy in crumpled and dirty clothes.}
{102}{}{This wreath was intended for Lucia.}

#First dialogue
{200}{}{Why are you here, gringo?}
{201}{}{Oh, you speak English?}
{202}{}{A little. I am Antonio. My parents were from the north. That's why I understand a little of the foreign language.}
{203}{}{I'm very lucky, it seems. But it doesn't look like you're very talkative. Why aren't you having fun with everyone else?}
{204}{}{I don't like this holiday. I want it to stop.}
{205}{}{Why?}
{206}{}{How can they celebrate the day of life when so many people have died? That old man and all the others are only happy because *they're* not dead. Idiots.}
{207}{}{Can't argue with that. Only an idiot would thank saints who allowed so many sacrifices.}
{208}{}{Exactly! You know, I like you, gringo.}
{209}{}{Okay, I have to go for a bit. See you later.}
{1209}{}{Okay, I have to go for a bit. See you later.}
{210}{}{Hey, don't get so depressed. You'll ruin the celebration for other people. Everyone deserves to happy.}
{211}{}{Yeah...}
{212}{}{Hmm. I'm going to go have fun. See you later.}

#Repeat dialogue
{220}{}{Hello there!}
{221}{}{Hi, gringo.}
{222}{}{What do you want, gringo?}
{223}{}{See you later.}

{230}{}{Have you heard that someone stole the crown?}
{231}{}{No, I didn't hear anything about that.}
{232}{}{I see.}
{233}{}{You told me that you wanted the party to be over.}
{234}{}{(looks down silently)}
{235}{}{Am I to take your silence as a sincere confession?}
{236}{}{I didn't want Lucia to be crowned.}
{237}{}{Why? Is it a bad thing?}
{238}{}{You gringo, you don't understand! If she wears the crown, I won't even be able to get close to her. And I... I'm her...}
{239}{}{Kid, I think you're being selfish.}
{240}{}{Maybe, I don't care!}
{241}{}{So, where's the crown, boy?}
{242}{}{I buried it in the center of the monument, so that nobody would be able to find it.}
{243}{}{What monument are you talking about?}
{244}{}{I don't really know. It was some old statue. Lucia and I were meeting there, in secret. We even scratched our names on the monument. That's why I hid it there. It was the first place that came to my mind.}
{245}{}{Thanks for telling me. See you later.}
{246}{}{No one cares about how you "didn't mean to". Tell me where you hid the crown!}
{247}{}{Remind me where the crown is.}

{250}{}{Lucia is safe now. I was thinking that I had lost her forever. Thanks.}
{251}{}{I'm glad I could help you.}
{1251}{}{I'm glad I could help you.}
{252}{}{So that's why you didn't participate in the party? You wanted to save her life?}
{253}{}{Yes. I even wanted to take her place, go to El Diablo myself. But the elder wouldn't let me. He said that there must be more men in the village, otherwise, there won't be anyone left strong enough to do hard work.}
{254}{}{That's terrible.}
{255}{}{It's over now. Here, take these comics. I don't know how else I can repay you.}
{256}{}{Interesting toys you have with you, boy. I think they'll come in handy.}
{257}{}{Fascinating. I'll read some during my travels.}

{260}{}{I saw Lucia run away from the church! What happened there? Did you really kill El Diablo?}
{1260}{}{I saw Lucia run away from the church! What happened there? Did you really kill El Diablo?}
{261}{}{Don't worry. Everything is under control.}
{262}{}{Please bring Lucia back!}
{263}{}{I'll try.}
{264}{}{Don't count on it.}