{100}{}{This is Lucia.}
{101}{}{You see a girl in ceremonial attire.}
{102}{}{Thanks for everything.}
{103}{}{Muchas gracias.}
{104}{}{The wreath has been returned to its rightful owner.}
{105}{}{It seems to be yours. Take it and do what you want with it.}
{106}{}{It's too early to give it to you yet.}
{107}{}{Lucia returned to the settlement of Santa Ana.}
{108}{}{Here Antonio and I often met in secret from the others. They forbade me to have a relationship with someone.}
{109}{}{A quiet peaceful place. I loved sitting here and thinking about my fate.}

{110}{}{}

{200}{}{¿Ò ot otra vez?}
{201}{}{There you are. And I'm looking for you everywhere.}
{202}{}{(turns away)}
{203}{}{... And I'm not the only one. Antonio is looking for you too.}
{204}{}{(turns half around) Antonio?}
{205}{}{Si, seœoga. He was looking for you.}
{206}{}{ (falls to his feet and sobs) El Diablo... *whimper-whimper* Tu no entiende, gringo. vivo para esto.}
{207}{}{I don't know what you're saying in your own language, but there's no point in getting upset. Let's go to the others.}
{208}{}{(grabs you by the sleeve) Este es mi destino! He perdido el sentido de la vida!}
{209}{}{Are you saying you've been trained for sacrifice all your life? Then it's clear why you don't want to accept freedom.}
{210}{}{(exhausted) Bueno. Voy a ir a casa. Dejalo ser.}
{211}{}{That's good. I'll make sure you get home.}
{212}{}{Stay here, I'll check the situation outside.}

{220}{}{You again, gringo?}
{221}{}{There you are. And I'm looking for you everywhere.}
{222}{}{(turns away)}
{223}{}{... And I'm not the only one. Antonio is looking for you too.}
{224}{}{(turns in half a turn) Antonio?}
{225}{}{That's the one, señora. It was he who stole the wreath from the ceremony to save it from death.}
{226}{}{ (falls to his feet and sobs) But El Diablo... * whimper-whimper* You don't understand, gringo. I've been trained for this all my life. I knew this day would come.}
{227}{}{Is it bad that you're free now? }
{228}{}{(grabs you by the sleeve) It was my destiny! I had to go to El Diablo to save the rest of the inhabitants!}
{229}{}{Then it's understandable why you're so discouraged. But everywhere I've been, there's no such damn thing. No one sacrifices their relatives to monsters.}
{230}{}{(exhausted) Okay... okay... I'll be back. Come what may.}
{231}{}{That's good. I'll make sure you get home.}
{232}{}{Stay here, I'll check the situation outside.}

{240}{}{Voy.}
{241}{}{Follow me. I'll make sure you get home.}
{242}{}{Wait here and don't go anywhere.}
{243}{}{Let's move on.}
{244}{}{Estoy cansada.}
{245}{}{I'm coming.}
{246}{}{I'm tired.}