{100}{}{You see Lucia.}
{101}{}{You see a girl in ceremonial attire.}
{102}{}{Thank you. For everything.}
{103}{}{Muchas gracias.}
{104}{}{The wreath has been returned to its rightful owner.}
{105}{}{Looks like this thing's yours. Take it. Do what you want with it.}
{106}{}{It's too early to give it to you.}

{110}{}{}

#Dialogue before ceremony
{200}{}{Buenas noches.}
{201}{}{Buenos dias.}
{202}{}{Don't mind me.}
{203}{}{Hello. Who are you? What is your name?}
{204}{}{Mi nombre es Lucia.}
{205}{}{Lucia. That's a nice name. Why are you wearing these special clothes? Is this holiday in your honor?}
{206}{}{Hoy ser' reina. Este es un gran honor para mš... (worriedly breaks eye contact) Dime honestamente, ¿te gusta nuestra ciudad?}
{207}{}{I don't understand. Are you smiling or crying?}
{208}{}{(covers face) Estoy bien.}
{209}{}{Okay. I'll go have some fun.}
{210}{}{Hi. I also speak Spanish.}
{211}{}{My name is Lucia.}
{212}{}{You seem so modest, but your outfit is anything but. Is this holiday in your honor?}
{213}{}{I will become the queen today. It's a tradition of ours. This is a great honor for me... (worriedly breaks eye contact) Tell me, do you like our city? And this holiday?}
{214}{}{This is the nicest and friendliest place I've ever seen!}
{1214}{}{This is the nicest and friendliest place I've ever seen!}
{215}{}{Really? Oh, I'm so glad. I'll do my best to keep it that way.}
{216}{}{Of course. You're the queen... Wait, are you smiling or crying?}
{217}{}{(covers face) I'm fine... You should talk to someone else.}
{218}{}{Okay, I'll go have some fun.}
{219}{}{There is nothing better than my beautiful home, Villa. You have no idea how much better it is there.}
{220}{}{Really? Oh, I'd sure like to visit that place. But I would never leave my family.}
{221}{}{I don't understand. Are you laughing at me or crying?}
{222}{}{Do you know where I could find your crown?}
{223}{}{The crown's missing? Oh, that's bad... find it, please! I must go through the ceremony, or the saints will get very angry!}
{224}{}{Okay, okay. I'll go find someone else to talk to. Maybe someone saw something.}

#Dialogue after ceremony
{230}{}{(Sits on the floor in dismay and looks down)}
{231}{}{[Leave her alone]}
{232}{}{Hey. How are you?}
{233}{}{(She lowers her head under her knees)}
{234}{}{Are you okay?}
{235}{}{(pulls her hand back and pushes you away) Idi domoy, gringo! El Diablo ya estž aquš!}
{236}{}{El Diablo? Who is it? What are you talking about? I don't understand...}
{237}{}{El Diablo is dead. Do you understand? (use gestures) Dead!}
{238}{}{(looks up in surprise) ¿El Diablo estž muerto?.. No... ¡No! No! No! (runs away from the church)}
{239}{}{Go, get some fresh air. You need it after this.}