{100}{}{This is Lucía.}
{101}{}{You see a girl in ceremonial attire.}
{102}{}{Thanks for everything.}
{103}{}{Muchas gracias.}
{104}{}{The wreath has been returned to its rightful owner.}
{105}{}{It seems to be yours. Take it and do what you want with it.}
{106}{}{It's too early to give it to you yet.}

{110}{}{}

#Dialogue before the ceremony
{200}{}{Buenas noches.}
{201}{}{Buenos dias.}
{202}{}{Nevermind to me.}
{203}{}{Hi. Who are you? What's your name?}
{204}{}{Mi nombre es Lucía.}
{205}{}{Lucia, then. What kind of special outfit are you wearing? Is this holiday really in your honor? }
{206}{}{Hoy soy reina. Este es un gran honor para mi... (excitedly hides his gaze) Dime, honestamente, te gusta nuestra ciudad?}
{207}{}{I don't understand, are you happy or crying?}
{208}{}{(bottlecaps his face) Estoy bien.}
{209}{}{Okay, I'm going to keep having fun.}
{210}{}{Hi. I speak Spanish too. Can I meet you?}
{211}{}{My name is Lucía.}
{212}{}{You seem so modest, and your outfit is so provocative. Is this holiday in your honor?}
{213}{}{I'm going to be queen today. It's such a tradition. And it's a great honor for me... (excitedly hides his gaze) Tell me, do you like our city and this holiday?}
{214}{}{Yes, this is the most beautiful and friendly place I've ever been!}
{1214}{}{Yes, this is the most beautiful and friendly place I've ever been!}
{215}{}{Really? Oh, I'm so glad. I will do everything to keep it that way.}
{216}{}{Of course, you're the queen... I don't understand, are you happy or crying?}
{217}{}{(bottlecaps his face) I am well... Talk to someone else.}
{218}{}{Okay, I'm going to keep having fun.}
{219}{}{There is nothing better than my beautiful Villa. You have no idea how much better it is.}
{220}{}{Really? Ah, I'd like to see. But I will never leave my family.}
{221}{}{I don't understand, are you laughing at me or crying?}
{222}{}{Do you know where your crown could have gone?}
{223}{}{Is it missing? Oh, that's bad... find her, please! I have to go through the ceremony, otherwise the saints will be angry!}
{224}{}{Okay, okay. I'll try to talk to someone else. Maybe someone saw something.}

#Dialogue after the ceremony
{230}{}{(He sits on the floor and looks down in frustration)}
{231}{}{[Leave]}
{232}{}{Hey, how are you?}
{233}{}{(Puts his head on his knees)}
{234}{}{Are you okay?}
{235}{}{(pulls back his hand and pushes you away) Go home, gringo! El Diablo ya está aqu?!}
{236}{}{El Diablo? Who is it? What are you talking about anyway? I don't understand...}
{237}{}{El Diablo is dead. Do you understand? (show with gestures) Dead!}
{238}{}{(looks up in amazement) El Diablo está muerto?.. No... No! (runs away from the church)}
{239}{}{Come on, get some fresh air. Now you can afford it.}