{100}{}{Here is Antonio.}
{101}{}{You see a local boy in rumpled and dirty clothes.}
{102}{}{This wreath was collected for Lucia.}

#The first dialog
{200}{}{What do you want, gringo?}
{201}{}{Oh, do you speak English?}
{202}{}{A little bit. I'm Antonio. My parents were from the north. So I understand a little foreign language.}
{203}{}{So I'm lucky. But you're not talkative. Why aren't you having fun with everyone?}
{204}{}{I don't like this holiday. And I want it to stop.}
{205}{}{Why?}
{206}{}{How can you celebrate the day of life when how many people have died? This old man and everyone else are happy just because they are alive. Fools.}
{207}{}{You can't argue with that. Only a fool would thank the saints who allowed so many sacrifices.}
{208}{}{Precisely! And I like you, gringo.}
{209}{}{Okay, I haven't looked around everywhere yet. See you later.}
{1209}{}{Okay, I haven't looked everywhere yet. See you later.}
{210}{}{Hey, don't get discouraged and spoil people's holiday. Everyone deserves to be happy.}
{211}{}{Yeah...}
{212}{}{Hmm. Anyway, I'm going to have fun. See you.}

#Repeat dialog
{220}{}{Hey, hello!}
{221}{}{Hello, gringo.}
{222}{}{What do you want, gringo?}
{223}{}{See you later.}

{230}{}{Do you know that someone stole the crown?}
{231}{}{No, I don't know anything about it.}
{232}{}{Okay. I believe.}
{233}{}{However, you let it slip that you want to stop the holiday.}
{234}{}{ (silently looks down)}
{235}{}{Can I consider your silence a sincere confession?}
{236}{}{I didn't want Lucia to be crowned.}
{237}{}{Is it bad?}
{238}{}{You're a gringo, you don't understand anything! If she wears a crown, then I won't even be able to get close to her. And I... I'm her...}
{239}{}{Boy, I think you're being selfish.}
{240}{}{Maybe so. I don't care!}
{241}{}{So where's the crown, man?}
{242}{}{I buried it in the center of the monument so that no one would find it.}
{243}{}{And what is the monument?}
{244}{}{Some kind of ancient monument. Lucia and I met there secretly and even scrawled our names on the pillars. So I immediately thought about this place.}
{245}{}{It's good that you confessed. It will be less trouble for me. See you later.}
{246}{}{Nobody cares about your "didn't want to". Tell me where you hid the crown!}
{247}{}{Remind me where the crown is.}

{250}{}{Lucia is safe now. I was already desperate and thought I had lost her forever. Thank you.}
{251}{}{Glad to help.}
{1251}{}{I was glad to help.}
{252}{}{Is that why you didn't participate in the celebration? Wanted to keep her alive?}
{253}{}{Yes. I even wanted to go to El Diablo instead of Lucia, but the headman wouldn't let me. He said that there should be more men in the village, otherwise there would be no one to work.}
{254}{}{Your fate is not enviable.}
{255}{}{But it's all over now. Here, take this magazine. I do not know how else I can repay you.}
{256}{}{Interesting toys you have, boy. I think they will be useful to me.}
{257}{}{A curious thing. I'll look through it sometime on the road.}

{260}{}{I saw Lucia run away from the church! What happened there? Did you really kill El Diablo?}
{1260}{}{I saw Lucia run away from the church! What happened there? Did you really kill El Diablo?}
{261}{}{Don't worry, everything is under control.}
{262}{}{Please bring back Lucia!}
{263}{}{I'll try.}
{264}{}{Don't count on me, man.}