{100}{}{Here is Enrique.}
{101}{}{You see a stern-looking Mexican.}

{110}{}{}

#The first dialog
{200}{}{Hola. My name is Enrique. What are you doing in our settlement?}
{201}{}{The road turned the wrong way where I'm going. I'm here by accident.}
{202}{}{It has been a long time since we had strangers from distant lands. It would be interesting to ask you, but now we have a holiday, as you can see. An important day - after all, my daughter Lucia had the honor to open this performance.}
{203}{}{And what is this tradition?}
{204}{}{Day of all the living. The day when we thank our saints that we are still alive. The coronation will be the end of the holiday. Any resident can be crowned. This allows us to appreciate each other and not forget that we are all one cohesive team in the middle of the desert.}
{205}{}{A good tradition. Well, I'll keep the fun going.}
{206}{}{A strange ceremony. But it's not my business anymore.}

#Repeat dialog
{220}{}{Hola, gringo.}
{221}{}{Hola, amigo.}
{1221}{}{Hola, amiga.}
{222}{}{Adios, Enrique.}

{230}{}{Did you know that the ceremonial crown is missing?}
{231}{}{Here is a strange case! There has never been such a thing. But she couldn't have disappeared by herself, right? I can't even imagine how this could happen. There were a lot of different people around the table, especially kids.}
{232}{}{I see.}
{233}{}{And you speak English well.}
{234}{}{We traveled a lot in Sonora. Therefore, some of us understand the Northern language a little.}
{235}{}{By the way, you have an unusually large number of children.}
{236}{}{Well, yes. And should it be otherwise? Children are our happiness and our future. Although many of them do not live to old age.}
{237}{}{What about Ilario? How old is he?}
{238}{}{He is our permanent headman. No wonder it is so carefully guarded. Although the old man is getting dirtier with age, it's with his help that we are still alive.}
{239}{}{What interesting places do you know in Sonora?}
{240}{}{Really? Can you show me some interesting places?}
{241}{}{The nearest city to us is Casa Nueva. Further to the east are the ruins of Puerto Penasco, and far to the south is the military fort in Hermosillo. We have been living in this place for ten years, so I do not know how things are there.}
{242}{}{I don't know what to say, Enrique. I'm just in shock.}

{250}{}{Hey, amigo! You already know our secret, right? What do you think about it?}
{251}{}{I don't know what to say. I'm just in shock.}
{252}{}{You are all here - gone sectarians.}
{253}{}{It's not for me to judge you. Apparently, you had no other choice.}
{254}{}{I guessed you'd say that. I think myself - and when did we fall so low that we sold our soul to the devil? But this has never happened before. I remember the days without El Diablo. Bright beautiful days...}
{255}{}{Well, now you have a chance to start over.}
{256}{}{So he's dead after all, right? What a relief! But Ilario won't let it go. He will resist the changes and lie as if El Diablo did not die. For fifteen years, he was too used to power. I want to get this freeloader out of town. Help me. Not everyone here is as opposed to him as I am.}
{257}{}{With pleasure. It'll be fun to watch him roll down the street. Go to church, I'll follow you.}
{258}{}{Let me talk to him. I'll try to convince him.}
{259}{}{My mission ended with the death of the monster. Then solve your problems yourself.}

{260}{}{So will you help drive the old man away?}
{261}{}{I'm sorry, but that's your problem. Without me.}
{262}{}{I swear - a little more and I'll finish him off!}
{263}{}{Let me talk to him.}
{264}{}{Ilario died. He won't bother you anymore.}
{265}{}{Ilario escaped. He's not coming back.}
{266}{}{Yes! How wonderful it became without him. I can already imagine how Santa Ana will be transformed without this old man and without the monster. No one else needs to be sacrificed. There is no more need to lie and pretend that nothing is happening. Thank you, friend. Here, take my gun as a token of appreciation. Now you are our guardian angel.}
{267}{}{It's always nice to help people. Goodbye, Enrique.}
{268}{}{Is there anything else I can do to help in the end?}
{269}{}{You know, I'm the village head now. And I want to establish trade with the neighboring town of Casa Nueva. We have nothing much to offer in return, but we will try to negotiate. Can you give them an offer? Let them send a caravan here for negotiations.}
{270}{}{Okay, I'll do it.}
{271}{}{I'll hardly ever be there. But I will keep in mind.}
{272}{}{Aren't there too many victims? Maybe not?}
{273}{}{If he is not stopped now, then in the future we will continue to make sacrifices to his vanity. And the further, the more difficult it will be to fix the situation.}
{274}{}{Then it's not worth wasting time. Let's go to church!}
{275}{}{In front of you is an ancient church in which the Devil was not worshipped at all. Are you ready to take another sin on yourself in this holy place?}
{276}{}{Your truth. But if Ilario goes back to his old ways, it will be the fault of all of us.}
{277}{}{It's good that you've come to your senses. Let's leave the old man alone.}
{278}{}{What are you? I'm just saying that it's better to sin once than to suffer massive transgressions. Let's go to church and put an end to this!}
{279}{}{Don't be in a hurry to give up. I just want to convince Ilario without using brute force. Wait here.}
{280}{}{And yet you were right-it was necessary to get rid of Ilario. Which I did.}
{1280}{}{And yet you were right-it was necessary to get rid of Ilario. Which I did.}
{281}{}{What are you? I'm just saying that it's better to sin once than to suffer massive transgressions. Let's put an end to this here and now!}
{282}{}{Unfortunately, Casa Nueva is going through hard times right now. You should forget about trading with this city.}
{283}{}{Sad news. It's okay, we'll survive without them somehow. Thanks for the warning.}
{1283}{}{Sad news. It's okay, we'll survive without them somehow. Thanks for the warning.}
{284}{}{Please.}
{285}{}{Hola, amigo. Recently, a caravan from Casa Nueva came to us. Thank you for your help.}
{286}{}{Here's the thing... Ilario ALSO passed away. Don't ask how it happened.}
{287}{}{Ilario fled the village when he realized that his power had come to an end. I doubt he'll come back.}

{290}{}{How did you even get to such a life?}
{291}{}{It's a long story. It started more than fifteen years ago.}
{292}{}{I don't even want to listen to this story. Let's change the subject?}
{293}{}{Tell me more.}
{294}{}{We were a nomadic people and wandered through the Sonoran desert in search of suitable places to live. One day we were accosted by this monster. He chased our caravan and periodically dragged away one person or cattle. We couldn't fight him off or run away from him - he's too strong and too fast.}
{295}{}{Go on.}
{296}{}{It's too scary! I'd rather cover my ears and go somewhere far away.}
{297}{}{Then Ilario came up with the idea of sacrificing animals to avoid human casualties. But the cattle soon ran out. And then we began to give away the elderly and the sick. Over time, they also ended. Fortunately, El Diablo had had enough by this point and began to demand fewer and fewer victims. So the balance was found.}
{298}{}{That's it.}
{299}{}{In addition, El Diablo attacked wild animals and bandits who threatened us. In fact, we became his flock, he grazed us and ate us during the famine.}
{300}{}{But you continued to make sacrifices to him?}
{301}{}{Once every few months, we gave him a sacrifice that was specially raised for these purposes. And so that no one would be discouraged, Ilario made a ceremony out of it and even began to preach the idea of divine purification. So we lived hand in hand with the real devil. Until you showed up, gringo.}
{302}{}{I hope you will be able to return to normal life. And I have to go on the road.}
{303}{}{Shame on you. We always stuck to each other at the Villa. And by the way, after this story, I wanted to return to my native land. Goodbye.}