{100}{}{You see Enrique.}
{101}{}{You see a tough-looking mexican.}

{110}{}{}

#First dialogue
{200}{}{Hola. My name is Enrique. What brings you to our settlement?}
{201}{}{I stumbled off the path to where I'm going. I didn't arrive here intentionally.}
{202}{}{We haven't seen strangers from faraway lands for a long time. It'd be interesting to ask you questions, but as you see - today is a special day. A very special day - after all, my daughter Lucia received the honor of beginning the celebration.}
{203}{}{What is this special day?}
{204}{}{The day of all living. The day when we thank our saints that we are still alive. At the end of the celebration, the coronation will occur. Anyone can be coronated. This lets us to value each other and not forget that we are one hard-working team out in the middle of a desert.}
{205}{}{Sounds like a great tradition. I'll go, continue having some fun with you all.}
{206}{}{Rather strange ceremony, in my opinion. But that's none of my business.}

#Repeat dialogue
{220}{}{Hola, gringo.}
{221}{}{Hola, amigo.}
{1221}{}{Hola, amiga.}
{222}{}{Adios, Enrique.}

{230}{}{Have you heard? The ceremonial crown is missing.}
{231}{}{How strange! Such things have never happened before. It couldn't have went missing by itself, right? There's no possible way something like that could happen. Someone must have taken it. But a lot of people were near that table, especially children.}
{232}{}{I see.}
{233}{}{You speak English well.}
{234}{}{We traveled across the Sonora desert many times. That's why some of us understand a bit of the northern language.}
{235}{}{By the way, I couldn't help but notice how many children there are around here.}
{236}{}{Why shouldn't there be many children? They are our future, even if many of them don't live to see themselves become old.}
{237}{}{What about Ilario? How old is he?}
{238}{}{He's our permanent elder. No wonder they protect him so carefully. The old man may be getting more and more ugly with age, but it is thanks to him that we are still alive.}
{239}{}{If you traveled around Sonora a lot, you must know some interesting places.}
{240}{}{Really? Can you point me to some interesting places?}
{241}{}{The closest city to us is Casa Nueva. Further to the east are the ruins of Puerto Penasco, and to the far south you'll find the Hermosillo military base. It's been ten years that I last set foot there, so I don't really know what's going on out there.}
{242}{}{I don't know what to say, Enrique. I'm just shocked.}

{250}{}{Hey, amigo! You know our... secret now, right? So, what do you think about it?}
{251}{}{I don't know what to say. I'm just shocked.}
{252}{}{You're all crazy cultists around here.}
{253}{}{Fair enough. I hear you didn't have much of a choice.}
{254}{}{I knew you'd say that. I think to myself - what was the exact moment when we sunk so low that we sold our souls to the devil? That's not how it always was, after all. I remember the days before El Diablo. Bright, beautiful days...}
{255}{}{Well, now you have a chance to start over.}
{256}{}{So he died after all, huh? What a relief! But Ilario will not just leave it like that. He'll resist change. He'll tell us lies that El Diablo never really died. Ruling for fifteen years made him far too accustomed to power. I want to drive that freeloader out of here. Help me. Not everyone is as opposed to him as I am.}
{257}{}{With pleasure. It'll be fun watching him roll down the street. Go to the church, I'll follow you.}
{258}{}{Let me talk to him. I'll try to convince him.}
{259}{}{My mission ended with the death of that monster. Deal with it yourself.}

{260}{}{So, are you going to help me drive Ilario away?}
{261}{}{Sorry, but that's your own problem, not mine.}
{262}{}{I swear, just a little more and I'll finish him off!}
{263}{}{Let me talk to him.}
{264}{}{Ilario is dead. He won't bother you anymore.}
{265}{}{Ilario escaped. He won't come back.}
{266}{}{Yes! How wonderful it'll be without him. I can already imagine how great Santa Ana will become without him and that monster. No more human sacrifice. No more lies and pretending that nothing is wrong. Thank you, friend. Here, take my pistol as a token of appreciation. You're our guardian angel, so to speak.}
{267}{}{It's always nice to help people. Farewell, Enrique.}
{268}{}{Maybe there's one last thing I can do to help?}
{269}{}{You know, I'm the elder now. I want to establish trade with the neighboring city of Casa Nueva. We have nothing special to offer in return, but we'll try to agree on something. Can you give them an offer? Have them send a caravan here to negotiate.}
{270}{}{Okay, I'll do it.}
{271}{}{I don't think I'll ever go there. But I'll keep that in mind.}
{272}{}{Don't you think that enough people have died? Are you sure that's a good idea?}
{273}{}{If we don't stop him now, then soon he'll have us making sacrifices to himself. And the longer it will go on, the harder it will be to make things right.}
{274}{}{Then let's not waste any time. Onward to the church!}
{275}{}{You're looking at an ancient church that didn't worship the Devil. Are you prepared to take on another sin in this holy place?}
{276}{}{Fair enough. But if Ilario continues the sacrifices, it will be our collective fault.}
{277}{}{I'm glad that you've come to your senses. Let's leave the old man alone.}
{278}{}{What are you talking about? All I'm saying is that it's better to sin once than to sin greatly over time. Let's go to the church and put an end to this!}
{279}{}{Don't be so quick to give up. I just want to convince Ilario without resorting to violence. Wait here.}
{280}{}{Turned out you were right - Ilario had to be disposed of. I did exactly that.}
{1280}{}{Turned out you were right - Ilario had to be disposed of. I did exactly that.}
{281}{}{What are you talking about? All I'm saying is that it's better to sin once than to sin greatly over time. Let's go to the church and put an end to this!}
{282}{}{Bad news. Casa Nueva is in a bad state right now. You can forget about trading with them.}
{283}{}{Bad news indeed. It's okay, we'll figure things out without them. Thanks for the warning.}
{1283}{}{Bad news indeed. It's okay, we'll figure things out without them. Thanks for the warning.}
{284}{}{You're welcome.}
{285}{}{Hola, amigo. A caravan from Casa Nueva came to us recently. Thanks for your help.}
{286}{}{Here's the deal... Ilario has ALSO passed away. Don't ask me how it happened.}
{287}{}{Ilario fled the village when he realized his time as a leader was at an end. I doubt he'll come back.}

{290}{}{How did this story with the monster even happen?}
{291}{}{It's a long one. It all began over fifteen years ago.}
{292}{}{I don't even want to hear this. Let's change the subject.}
{293}{}{Go on.}
{294}{}{We were nomads, wandering the Sonoran Desert in search of a place to live. One day, that creature began to follow us. He would periodically drag away one person or some cattle. We couldn't fight him off or run away - he was too strong and too fast.}
{295}{}{Go on.}
{296}{}{This is too scary! I ought to better plug my ears and go somewhere far away.}
{297}{}{Then Ilario came up with the idea of sacrificing animals to avoid human deaths. It worked for a time, until we ran out of cattle. Then we began to give him the elderly and the sick. Soon enough, we ran out of them too. Fortunately, El Diablo was somewhat sated by this point. He began to demand fewer and fewer victims. So we had achieved a balance of sorts.}
{298}{}{I see.}
{299}{}{El Diablo also attacked wild beasts and bandits who threatened us. We effectively became his herd. He grazed us and ate us when he was hungry.}
{300}{}{But you continued to make sacrifices to him?}
{301}{}{Once every few months, we gave him a victim specially raised for this purpose. And so that no one would be too sad, Ilario made a ceremony out of this. He even began to preach this idea of it being divine purification. So, we lived hand in hand with the devil himself. Until you showed up, gringo.}
{302}{}{I hope you can get things back to normal here. And as for me, I think I should go.}
{303}{}{Shame on you and your community. Where I was born, at Villa, we would never sacrifice one another. Man, hearing this story makes me miss home. Goodbye, Enrique of Santa Ana.}