{100}{}{You sees a visitor.}
{101}{}{You see a man in dusty clothes. It looks like he walked many miles in it.}
{102}{}{Wow. I knew that tinsmiths are masters, but I didn't even think about it...}
{103}{}{What's wrong with this damn city?}
{104}{}{...}

#First meeting
{200}{}{Hey, is that you? What a surprise. I didn't think I'd meet you here.}
{201}{}{And you...}
{202}{}{Do you remember you brought me a letter in Phoenix? I was very surprised at the time and thought it was some kind of deception. As it turned out, in vain.}
{1202}{}{Do you remember when you brought me the letter in Phoenix? I was very surprised at the time and thought it was some kind of deception. As it turned out, in vain.}
{203}{}{Well, but what brought you to this God-forsaken town?}
{204}{}{}
{205}{}{}
{206}{}{There is an abandoned swimming pool building in the city center. I'm looking for the owner of this establishment.}
{207}{}{A swimming pool? Here in the middle of the desert?}
{208}{}{Well yes. There is a lot of water in the city, so caravans from all around come here. However, water is not sold to everyone.}
{209}{}{Why are you looking for the owner?}
{210}{}{He's my relative. I received a letter from him with an offer to come and work in the bathhouse. And here I am. And he's nowhere to be found.}
{211}{}{Just like that, he just came to a strange city?}
{212}{}{Why not? After all, things got really bad in Phoenix after that monstrous explosion.}
{213}{}{An explosion? What's the story of the explosion?}
{214}{}{Don't you know? Yes, the whole tenth track is already cracking about this. The Church of the Sacred Fire was blown up. Poof-f! Literally.}
{215}{}{Wow. Do the locals know anything about your uncle?}
{216}{}{The locals don't know anything. The bathhouse is closed, and the owner has not been seen for a long time. I talked to the mayor, but he called me another con man and kicked me out on the street.}
{217}{}{What are you going to do?}
{218}{}{I don't know yet. I'll stay here a little longer, maybe my uncle will finally show up. If you find out anything, let me know, okay? I will not remain in debt.}
{219}{}{Well, good luck with the search.}
{220}{}{Yeah. Be.}
{221}{}{Bye.}
{222}{}{Surely this is some kind of mistake.}
{223}{}{I don't think so.}
{224}{}{Well, well. Stay deluded.}
{225}{}{Hmm. Or maybe you're just pretending to be his relative to take his place?}
{226}{}{Nonsense. We really haven't seen each other for a long time. But the uncle himself sent the letter through couriers, it can be checked. Besides, it was you who gave me his letter.}
{1226}{}{Nonsense. We really haven't seen each other for a long time. But the uncle himself sent the letter through couriers, it can be checked. Besides, it was you who gave me his letter.}

#Repeated dialogue at the parking lot
{250}{}{Ah, it's you. I was just thinking about you. Two strangers in the same city. We should stick together, huh?}
{251}{}{Sounds very far-fetched. Bye.}
{252}{}{Sure. See you again.}
{253}{}{By the way, what's your name?}
{254}{}{Just call me Steve.}
{255}{}{Okay, Steve. How about you tell me again what you're doing here?}
{256}{}{See you later, Steve.}
{257}{}{Tell me again, who are you looking for?}

#stage 1
{260}{}{Have you been to the local cemetery? Looks like your uncle is there.}
{261}{}{What? So he's dead? Now I understand why the mayor is trying to kick me out. But how did it happen?}
{262}{}{Judging by the mass graves, many people died here. Do you know something about this?}
{263}{}{Hmm. As far as I know, clan wars have been waged here recently. That's why the locals get nervous when you try to ask them about the past. If my uncle fell victim to this war, then it remains only to accept.}
{264}{}{Will you leave with nothing?}
{265}{}{Well, no. The bathhouse belonged to my uncle. And I am his relative. Shouldn't I inherit it?}
{266}{}{Are you kidding? After all these threats, are you going to stay?}
{267}{}{You see... To be honest, things weren't going well in Phoenix either. I was completely desperate, trying to earn caps on the fights. But here you can revive my uncle's business and get rich. Why the hell should I miss my chance?}
{268}{}{Ah, that's it. The death of your relative was very convenient, wasn't it?}
{269}{}{What are you talking about? I can revive my uncle's business and get rich. It would be stupid to miss such a chance.}
{270}{}{Great idea. It's worth a try. Do you need partners?}
{271}{}{You have to be absolutely desperate to take such a risk.}
{272}{}{Well, the main thing now is to win the mayor's favor. He doesn't want to make contact with me, the guards won't let him in. Can you talk to him?}
{273}{}{And what will I get for this mediation?}
{274}{}{And, of course, everyone wants to make money. Don't worry, I'll pay when I get rich. We're partners. We just have to wait a bit.}
{275}{}{I'll try to convince him.}
{276}{}{Thank you, partner. What would I do without you?}
{277}{}{See you later.}
{278}{}{The very thought of talking to this tyrant scares me. Find someone else.}
{279}{}{I understand. It's okay, I'll figure it out somehow. Anyway, thanks for the help.}
{280}{}{Bye, loser.}
{281}{}{I'm just passing through here, I don't have time to wait for the first customers.}

#stage 2
{300}{}{So what did the mayor say? Did you manage to talk to him?}
{301}{}{No, I wasn't up to him. Wait a little longer.}
{302}{}{The mayor of the city is dead. Now there's nothing stopping you from starting your own business.}
{303}{}{Dead? What the hell is wrong with this city? Okay, I don't want the details. But your truth is - I need to occupy the bathhouse before someone else does it.}
{304}{}{OK, we'll meet there...}
{305}{}{The mayor has recognized your right to a bathing place. You can start your own business.}
{306}{}{Wow, you know how to negotiate with people. Now we need to occupy the bathhouse before the mayor changes his mind.}
{307}{}{OK, we'll meet on the spot...}
{308}{}{The mayor demands that you leave the city. Immediately.}
{309}{}{What happened to you? Can't you see that it's not fair? I rightfully own this bathhouse. It's empty now anyway.}
{310}{}{Sorry, I'll try to convey this idea to the mayor.}
{311}{}{If you value your life, you will leave right now.}
{312}{}{Ah, that's it. I thought we were partners. It turned out that you are an ordinary corrupt dog.}
{1312}{}{Ah, that's it. I thought we were partners. It turned out that you are an ordinary selling bitch.}
{313}{}{We will discuss this further. But later.}
{314}{}{I'm not kidding. Get out of town.}
{315}{}{I'm not leaving. This is my family business. And I won't leave him.}
{316}{}{You leave me no choice. If you don't want to leave, I'll make you.}
{317}{}{However, do what you want.}
{318}{}{Listen to me. I'll count to five, and then I'll get the gun. One... two...}
{319}{}{Hey, hey, wait...}
{320}{}{...three.}
{321}{}{Come on, it's a joke. Of course, stay, it's your problem.}
{322}{}{Okay, that's it, I'm leaving, look.}
{323}{}{And don't come back.}

{330}{}{Look what the locals have done with this once wonderful institution. Dirty barbarians.}
{331}{}{I'll take a look around if you don't mind.}
{332}{}{What's wrong?}
{333}{}{Apart from the fact that all the most valuable things were stolen from here, the real problem is in the water heating system.}
{334}{}{Is it not working?}
{335}{}{Someone tried to steal the tank, but knocked it over and damaged it. I don't know how to fix it yet.}
{336}{}{Well, good luck. I'm definitely not going to do this.}
{337}{}{Let me see. I'm sure I'll fix this monster with a piece of scrap metal.}
{338}{}{The tank is in perfect order. You can warm the water and wash it.}
{339}{}{Did you manage to fix it? Cool. Now the business will definitely be trampled. Thank you, you've done a lot for me. Drop by if you need to freshen up.}
{1339}{}{Did you manage to fix it? Cool. Now the business will definitely be trampled. Thank you, you've done a lot for me. Drop by if you need to freshen up.}
{340}{}{I'll keep that in mind. Be there.}

{350}{}{How are you?}
{351}{}{How are you? Do you want to wash up?}
{352}{}{Do you want to wash up? Come on, I just found some old sea salt.}
{353}{}{Do you want to wash up? It's about time when it's so hot outside.}
{354}{}{Now you definitely need to wash up. Don't be shy, I won't charge you too much.}
{355}{}{The bathroom is free. Get in, it's time to wash off this road dirt.}
{356}{}{Bye, Stephen.}

#The rest
{400}{}{I need to wash up. How much does it cost?}
{401}{}{I'll only charge you for firewood and water. It will cost in }
{402}{}{ caps.}
{403}{}{I can't afford that luxury. Another time.}
{404}{}{Sounds acceptable. Here...}

{410}{}{For such a period of time, your business should have already brought good results.}
{411}{}{You know, not really. Caravanners travel seasonally, so there are times when there are no visitors in the city at all. Not everyone is willing to pay caps for such a service. But enough to live on.}
{412}{}{Have you not forgotten our agreement?}
{413}{}{My patience is running out. Where is my share of the business?}
{414}{}{What are you talking about? I don't owe you anything. Come on, get out of here, you're stopping me from cleaning the tub.}
{415}{}{What?}
{416}{}{You're a scum.}
{417}{}{Of course, partner. I've been saving up caps just for you. Here, 200 pieces. And now I'm sorry, this tub needs to be cleaned properly.}
{418}{}{Thank you, it's a pleasure doing business with you. Have a nice day, Steve.}
{419}{}{And that's it? Shit is your business, Steve. And change the sign. It looks lousy.}
{420}{}{If you don't want to give up the bottlecaps, I'll take them by force. Stand still, you bastard...}

{430}{}{The tinsmiths sent an ambassador here. Do you know anything about it?}
{431}{}{I saw this tinker, but he didn't talk to anyone and immediately went to the mayor. I never saw him again.}
{432}{}{At least some information. Bye.}
{433}{}{You're of no use. Bye.}
