{100}{}{Its the leader of the gang.}
{101}{}{You see one of the highway robbers. Looks like he's running everything here.}
{102}{}{We're already leaving. Give the mayor our "deepest apologies."}

{200}{}{Climbing right under a bullet and not afraid? You're either brave or just a fool. Who are you?}
{1200}{}{The count is so pathetic that he sends a woman to negotiate. Okay. But who are you?}
{201}{}{I'm the last thing you'll see.}
{202}{}{It doesn't matter who I am. The mayor sent me to negotiate.}
{203}{}{Well of course. Bustos does not change. He is ready to sacrifice any life except his own. Let's see if he values his daughter's life.}
{204}{}{The mayor demands to release the hostage. Otherwise, you won't get out of here alive.}
{205}{}{The mayor can't be trusted. He's meaner than a wasteland snake. Tell him that if he does not fulfill our demands, we will kill his daughter.}
{206}{}{What do you want?}
{207}{}{To hell with talking. You deserve only death.}
{208}{}{Ten thousand caps.}
{209}{}{Ten thousand? You can't get that much in the whole city.}
{210}{}{It's not our problem. So, there is only one thing left - the life of the mayor. Let him take his daughter's place.}
{211}{}{I'll let him know your requirements.}
{212}{}{What's wrong with you?}
{213}{}{Hmm. You're not from around here, are you? Otherwise, I would have known you.}
{214}{}{What does it matter?}
{215}{}{caps are not the main thing for me. There is an old cemetery in the east of the city. A mass grave. In this place, where only dry grass grows, the inhabitants of Casa Grande rest. My parents are among them.}
{216}{}{[Listen]}
{217}{}{They were trying to establish a peaceful life in this city. They worked tirelessly to launch a water pump and equip the city. But then Bustos came, killed them, and took the city for himself. He left no one alive who stood in his way.}
{218}{}{And now you're taking revenge?}
{219}{}{Why would I lie? I'm telling the truth. Tell the mayor my words. Although it is unlikely that he will want to listen to you.}
{220}{}{I will convey your demands to the mayor.}
{221}{}{You're lying. And I will kill you so that others will not be offended...}
{222}{}{Are you sure you want even more blood on the land of your ancestors?}
{223}{}{I'm not going to argue with you. Bring me the mayor. I will only talk to him.}
{224}{}{This city is already knee-deep in blood. Only now have we managed to achieve at least some peace.}
{225}{}{There will be no more negotiations. You're going to die right now...}
{226}{}{Are you saying I'm just being selfish? How do you think I should live after the mayor banished me from my land? I eat carrion and rob caravans on the highway just to survive. And all because of one greedy scoundrel.}
{227}{}{So get off this road. You can live in Phoenix or another city.}
{228}{}{I don't think I'm ready to start over. It's too late to change anything. And yet your words have sunk into my soul. The girl can leave. It's not her fault. But if the mayor has any dignity left, then let him come to me. Let's have a duel with him, just like in the good old days.}
{229}{}{Glad you listened to reason.}
{1229}{}{Glad you listened to reason.}
{230}{}{What did the mayor say?}
{231}{}{That he promised a reward for your head. And I will get it.}
{232}{}{The situation has not changed. He will let you go if you release the hostage.}
{233}{}{What are these spy tricks? Do you really hope that I don't recognize you as a stranger under these signs?}
{234}{}{Well...}
{235}{}{You will only get a thousand caps and leave the city. Otherwise, you won't get out of here alive.}
{236}{}{Surprisingly. I thought Bustos wouldn't give ten caps...}
{237}{}{[Next]}
{238}{}{(One of the accomplices interrupts the leader, takes him into a corner and begins to actively discuss something with him) And ... yes... You're right, buddy, calm down... (comes back to you) We accept your terms. Give me the caps and you can take the girl.}
{239}{}{Why would the count be so nice to robbers? I'll just kill you and take the bottlecaps for myself...}
{240}{}{We'll have to wait a bit. I'll go get the caps.}
{241}{}{The whole amount is here.}
{242}{}{Tell the count that we're leaving, and don't let him try to send a tail after us.}
{243}{}{It would be foolish to lose such a sum of caps. I will kill you and take them back.}
{244}{}{The Count keeps his word.}
