{100}{}{Here is Count Bustos.}
{101}{}{You see a man in a solid but dilapidated suit. His gray temples seem to hint at a difficult past.}
{102}{}{Thanks for the help. See you at my mansion.}
{103}{}{Go back to the mansion. We'll talk there.}

#The first dialog
{200}{}{(Approaching the building of the bar, you find a crowd of armed people; the mayor is actively discussing something with them).}
{201}{}{Ahem.}
{202}{}{Ah, it's you... Come closer. We need any help right now.}
{203}{}{What's going on here?}
{204}{}{There are robbers in the bar. They have seized my daughter and are demanding a ransom. It seems that it will not be possible to negotiate with them. I will pay any money to the one who will save Kristina.}
{205}{}{Yes, a difficult case.}
{206}{}{And what do I have to do with it?}

#Repeat dialog
{210}{}{What are the suggestions?}
{211}{}{Hey, my life is dear to me, don't count on me.}
{212}{}{Then stand aside and don't interfere. Perhaps the sight of a large crowd will frighten the robbers.}
{213}{}{It doesn't make sense. I'll take a look from the side.}
{214}{}{Let me talk to them. Maybe I can convince them to leave.}
{215}{}{Talk to highway robbers? It's impossible. And I won't save your ass if they take you hostage too.}
{216}{}{Then I'll just see from the outside how it ends. Good luck.}
{217}{}{Don't worry about me. I know how to negotiate.}
{218}{}{I suggest a frontal attack. Talking to them is pointless.}
{219}{}{I don't seem to have a choice... Who is ready to participate? I will pay everyone who will help save my daughter.}
{220}{}{Wait, let's not rush it. Let me assess the situation.}
{221}{}{I'm participating. Let's give these bastards a hard time!}
{222}{}{Go ahead!}
{223}{}{Yes!}
{224}{}{Why not pay them a ransom?}
{225}{}{They demand too much. The city will be devastated. And more...}
{226}{}{More?}
{227}{}{They want to trade Christina for me to clear their way into the wastelands. They cannot be trusted.}
{228}{}{Do you want to sneak in there in THIS? Not a bad idea, but you will be identified very quickly. Any other ideas?}
{229}{}{I see...}

{250}{}{As you can see, your daughter is safe.}
{251}{}{Ah, Christina... How are you? I'll make these bastards pay for what they did!}
{252}{}{Are you going to attack the bar?}
{253}{}{Of course. If other robbers find out this story, then my daughter will be kidnapped every single day. They need to be finished right now.}
{254}{}{You can't argue with that. Criminals must be punished. When do we start the attack?}
{255}{}{Don't count on me. I will not participate in this massacre.}
{256}{}{Your daughter is dead. I saw it with my own eyes.}
{1256}{}{Your daughter is dead. I saw it with my own eyes.}
{257}{}{No! No!}
{258}{}{I'm sorry.}
{259}{}{(frantically) These bastards will pay cruelly. Listen UP, EVERYONE! I'll pay for the head of every son of a bitch who's stuck in a bar!}
{260}{}{Great, I'm in.}
{261}{}{Without me. I don't want to participate in shootouts.}
{262}{}{Bring my daughter. Immediately.}
{263}{}{Now is not the time to talk. These highways will not give up so easily.}
{264}{}{They deserve to be punished. But attacking while they're in the bar is too dangerous. Let them go, so at least you will save people.}
{265}{}{I don't want another massacre in my city either. We already have a bloody reputation. Let them go. We're going back to the mansion.}
{266}{}{The right decision, Mr. Mayor...}
{267}{}{It doesn't make much sense. They are already leaving the city.}
{268}{}{You have incredible powers of persuasion. Even a little suspicious. Well, let them get out of here. And we're going back to the mansion.}
{269}{}{The right decision, Mr. Mayor...}
{270}{}{The goal is clear...}
{271}{}{Don't count on me. I will not shed someone's blood.}
{272}{}{The bandits will not go anywhere until you fulfill their demands.}
{273}{}{So there is no choice. They'll all have to be shot. Can you get my daughter out of the bar unnoticed?}
{274}{}{Give me time, I'll try to get her out unnoticed.}
{275}{}{It's impossible. I propose a frontal attack right now!}
{276}{}{Relax, Count. All the invaders in the bar are already dead.}
{277}{}{Amazing! I've never had helpers like you.}
{278}{}{So you're very lucky.}

{280}{}{}
{281}{}{[Eavesdrop on negotiations]}
{282}{}{Bustos: What's the news, John?}
{283}{}{[Listen]}
{284}{}{Sullivan: They say there are four or so criminals. Your daughter is being held hostage. They have not made any demands yet. We need to send a person to negotiate.}
{285}{}{[Listen]}
{286}{}{Bustos: Gr-rm... They knew how to catch her and who to aim at... Damn it, if other robbers find out about this, then this story will repeat itself from day to day.}
{287}{}{[Listen]}
{288}{}{Sullivan: I had to keep an eye on her. The mayor of the whole city, but can't keep track of his own girl.}
{289}{}{[Listen]}
{290}{}{Bustos: Shut up, John! Better find a way to free my girl.}
{291}{}{[Listen]}
{292}{}{Sullivan: Don't you dare tell me, Bustos. These are not the times you remember at the bottom of a tequila bottle. Better get all your ransom caps ready. And hurry up ... (seeing you) And? And what do you need?}
{293}{}{What's going on here?}