{100}{}{You see a bartender.}
{101}{}{You see an ordinary bartender.}
{102}{}{I'm sorry, but you can't come here in THIS.}

{110}{}{Hey, come in to get your throat wet from the road.}
{111}{}{Do you want a drink?}
{112}{}{I thought there would be more customers.}
{113}{}{Don't worry, everyone's here.}
{114}{}{Oh, I finally see a client.}

{200}{}{Hey, hello! Well done for stopping by.}
{1200}{}{Oh, lady. My respects. Thanks for stopping by.}
{201}{}{Wasn't this bar abandoned?}
{202}{}{Yes, it was. But now things have gone up in the city, and I decided to restore this bar.}
{203}{}{And the mayor was not against it?}
{204}{}{Previously, he didn't even allow you to enter this bar, and now suddenly he's got a lot of money. I don't know what came over him, but I'd better take this place before it's too late.}
{205}{}{Clear. Can I have a drink?}

{210}{}{Have a seat. The selection is limited, but it's better than nothing.}
{211}{}{I have to go.}
