{100}{}{Here is Kristina.}
{101}{}{You see the daughter of Count Bustos.}
{102}{}{If the robbers see us, they will surely shoot us.}
{103}{}{I'm so glad it's over.}
{104}{}{*Crying*}

#The first dialog
{200}{}{Don't touch me, you dirty highway man!}
{201}{}{Calm down. Your father sent me.}
{202}{}{Mine... Dad? Daddy... Let's get out of here soon.}
{203}{}{I'm going to untie you now... Let's go, but quietly.}
{204}{}{We shouldn't be noticed. If the robbers see us, they'll probably shoot us.}
{205}{}{Okay, let's go.}
{206}{}{Now is not the time. You'll have to wait a little longer.}
{207}{}{What? Are you leaving me? Release me immediately!}
{208}{}{Be a good boy and I'll be back soon.}
{209}{}{Indeed, it is not worth staying here.}

#Repeat dialog
{210}{}{Hello.}
{211}{}{Bye.}
{212}{}{You're free. I managed to negotiate with the bandits.}
{213}{}{Really? Then let's get out of here quickly, what if they change their minds?}
{214}{}{Sure, let's go.}