{100}{}{Here is a robber.}
{101}{}{You see one of the highway robbers. The type is not pleasant.}

{110}{}{If we don't get paid, someone will die.}
{111}{}{We are not here from a good life.}
{112}{}{Let the count count the caps if he wants to see his daughter alive.}
{113}{}{I don't want to dirty my hands about the girl, but someone has to do it.}
{114}{}{What did Bustos decide? Come on, spit it out.}
{115}{}{I'm running out of patience.}
{116}{}{My fingers are itching to shoot someone.}
{117}{}{}
{118}{}{Don't even think about following us.}
{119}{}{Get out of here.}