{100}{}{You see the guard.}
{101}{}{In front of you is a caravan guard. He is resting after a tiring journey.}

{110}{}{Hi. How is the road?}
{111}{}{Sorry, but I need to rest.}
{112}{}{There's water here, but otherwise it's a lousy place.}
{113}{}{Casa Grande has violent morals.}
{114}{}{The local mayor is not to be trifled with.}
{115}{}{You need to talk to the boss.}
{116}{}{There is a restless road between Phoenix and Fog.}
{117}{}{It is dangerous on the highway because of the mainline drivers.}
{118}{}{It is better not to face the mainline drivers.}
{119}{}{We are only a source of income for the locals.}