{100}{}{Here is a merchant.}
{101}{}{You see the caravan manager.}
{102}{}{I've heard of such armor, but I thought it was fiction.}

{200}{}{Greetings, traveler. I have been driving my caravan to this city for several months now. And that's why I'm a little aware of what's what here. Can I help you with something?}
{1200}{}{Greetings, traveler. I have been driving my caravan to this city for several months now. And that's why I'm a little aware of what's what here. Can I help you with something?}
{201}{}{What can a tramp like you advise me? Obviously, I'm just wasting time with you.}
{202}{}{Yes. I could definitely use some advice.}

{210}{}{Do you want to know more?}
{211}{}{Nothing. Later.}

#Questions
{220}{}{Tell me about this place.}
{221}{}{Casa Grande is the only oasis on the way from Tu San to Phoenix. Many caravans stop here to rest on the way and get clean water. Otherwise, the city has nothing to offer the traveler.}
{222}{}{Why is this city so poor?}
{223}{}{Honestly? I have no idea. The locals earn a lot of caps from us, the caravaneers. But they can't afford basic things themselves. Partly because of the highway robbers who are ruining the highway, but this is clearly not all the reasons.}
{224}{}{It's noticeable. The city is more like a garbage dump.}
{225}{}{Don't treat the locals like that. They are just trying to survive in these difficult conditions.}
{226}{}{I would like to know more.}
{227}{}{What are these huge containers behind the fence?}
{228}{}{Water station. The main attraction of Casa Grande nowadays. Without it, these ruins would remain uninhabited.}
{229}{}{}

{230}{}{Who's in charge here?}
{231}{}{Formally, the mayor of the city is Count Bustos. To be honest, I don't quite understand what he does, but no one here dares to take a step without him.}
{232}{}{After the death of Count Bustos, John Sullivan was appointed head of the city. Or maybe he appointed himself, it's hard to say.}
{233}{}{It's hard to say. After the death of the mayor and the owner of the station, no one wants to become the new head of the city.}
{234}{}{I see. Another question.}
{235}{}{Where can I find the mayor?}
{236}{}{His mansion is down the main road. If you find yourself inside, keep your weapon in a holster and do not make sudden movements. His bodyguards don't like it.}
{237}{}{Maybe I'll look in on him, but later. In the meantime, let's continue the conversation.}
{238}{}{I'm going to see him right now. Later.}
{239}{}{}

{240}{}{What's new here?}
{241}{}{Nothing special.}
{242}{}{I see.}
{243}{}{Someone desecrated the local cemetery. The mayor was very angry and promised a reward for the capture of the scoundrel. And who could have thought of such a thing?}
{244}{}{Is this all news?}
{245}{}{A flock of radscorpions was seen in the vicinity. Be careful and take the antidote with you if you're going to the wasteland.}
{246}{}{Is this all news?}
{247}{}{Count Bustos was killed by robbers, as they say. I don't know how it happened. The locals don't want to go into details.}
{248}{}{What else?}
{249}{}{They say Count Bustos is quietly drinking in his mansion. Yes, the old beast is starting to lose its grip. Tequila has never made anyone stronger.}
{250}{}{Something else?}
{251}{}{The bathhouse has started working again in the city. It's so nice to feel clean.}
{252}{}{This... curious. Something else?}
{253}{}{There was a swimming pool in the city, but now it is closed. And no one knows where her master is. And I was so hoping to wash up.}
{254}{}{Curious. Any other news?}
{255}{}{Now everyone is discussing the hostage-taking in the bar in the neighborhood. You seem to know this story better than me.}
{256}{}{The water pump raised prices after the fall of tinsmiths. It seems that this caravan route has begun to become obsolete.}
{257}{}{This is useful information. What else can you tell me?}
{258}{}{The Blue Shield Gang has stopped attacking caravans. It is not yet clear what happened there, people are talking different things. But the fact that the highways have become safer is a fact.}
{259}{}{That's for sure.}

{260}{}{How can you earn a glass of water here?}
{261}{}{Hmm, there is nothing but trade for a visitor. However, every mayor has a job, if, of course, you can find a common language with him.}
{262}{}{I'll take note of that.}
{263}{}{Otherwise nothing new.}
{264}{}{I see.}

#Sending to Phoenix
{300}{}{Where is your caravan going?}
{301}{}{We'll be heading back to Phoenix soon.}
{302}{}{Have a good trip. And before you leave, can I ask a couple of questions?}
{303}{}{Take me with you. I also need to go to the big city.}
{304}{}{Sorry, all the seats are taken. We don't need an extra tail.}
{305}{}{I'll pay.}
{306}{}{I understand. But can you answer the questions?}
{307}{}{I don't want to offend you, but I don't need questionable fellow travelers. The route is too dangerous to take such a risk.}
{308}{}{I understand, don't worry.}
{309}{}{Just get me on the highway and I'll remember it for you.}
{310}{}{Good. For }
{311}{}{ caps I'm ready to tolerate ballast. But don't take too many things, we don't have an extra brahmin to carry them.}
{312}{}{I don't have that many caps. I'll have to go alone. See you later.}
{313}{}{Right now I need answers to questions more.}
{314}{}{Here are the bottlecaps. I'm ready to go.}
{1314}{}{Here are the bottlecaps. I'm ready to go.}
{315}{}{Who will carry these things? I'm telling you, it's too much. Leave no more than fifty pounds.}
{316}{}{Okay.}
{317}{}{I don't work for free.}
{318}{}{Of course...}
{319}{}{Don't worry, you're safe with my caravan.}
{320}{}{[Wait for the caravan to depart]}
{321}{}{I promise it will remain my problem.}
{322}{}{Now you're saying one thing. But anything can happen on the way.}
{323}{}{Well, yes...}
{324}{}{If it's a problem, you can leave me in the middle of the track with all these things.}
{325}{}{OK. We will consider this part of the contract. But I don't work for free.}
{326}{}{Of course...}
{327}{}{Good. We will consider this part of the contract.}
{328}{}{Great.}
{329}{}{I'll pay more }
{330}{}{ caps for the luggage.}