{100}{}{You see a settler.}
{101}{}{Here is one of the locals.}
{102}{}{ }

{110}{}{Z-z-z}
{111}{}{Hr-r-r}
{112}{}{. . .}

{120}{}{The mainline robbed the second caravan in a week.}
{121}{}{These mainline workers know no pity.}
{122}{}{They say they saw highway workers nearby.}
{123}{}{It costs nothing for the mainline workers to take over the whole city.}
{124}{}{There are fewer caravaneers because of the Blue Shields.}

{125}{}{How long will the truce with the Blue Shields last?}
{126}{}{What? Are the Blue Shields our friends now? It can't be.}
{127}{}{After everything the Blue Shields have done, I won't even go near them.}
{128}{}{The Blue Shields engaged in trade. The world seems to have gone crazy.}
{129}{}{You can't trust the Blue Shields. The time will come, and they will stick a knife in the back.}

{130}{}{The Blue Shields got what they deserved.}
{131}{}{Ben and his gang weren't so scary, huh?}
{132}{}{Ben's gang won't be around for a long time.}
{133}{}{I hope that now the mainline workers will be finished.}
{134}{}{There will be more caravans without Ben's gang.}

{135}{}{Without Ben, you can forget about his gang.}
{136}{}{Ben got what he deserved.}
{137}{}{I remember when Ben was a good guy.}
{138}{}{I still don't understand why Ben turned into a robber.}
{139}{}{Now Ben is not scary at all. He's ugly and smelly.}

{140}{}{These tinsmiths scare me with their very appearance.}
{141}{}{What sane person would team up with a machine?}
{142}{}{Tinsmiths despise people like us.}
{143}{}{If it weren't for the tinsmiths, there wouldn't be so many caravans.}
{144}{}{Thanks to the tinsmiths for a safe highway.}

{145}{}{Now trade will decrease and the city will become even poorer.}
{146}{}{There will be fewer caravans without tinsmiths.}
{147}{}{As much as I didn't like tinsmiths, but they were useful.}
{148}{}{Finally, someone pulled the plug out of the socket in Two-Sun.}
{149}{}{The sun will not rise again in Two-Sun. Never.}

{150}{}{The big City beckons with lights... like fire beckons a moth.}
{151}{}{I would like to see Phoenix.}
{152}{}{I've been hearing so much about Phoenix lately.}
{153}{}{They say there's a casino in Phoenix. But I don't understand what it is.}
{154}{}{The idea with the caps came from Phoenix. This has never happened before.}

{155}{}{}
{156}{}{Finally, the bathhouse is working again.}
{157}{}{After closing the bathhouse, I was covered with a layer of mud.}
{158}{}{Someone is digging burials in the Burial Ground. Now I'm scared.}
{159}{}{The mail caravan will be delayed because the manager was killed in Phoenix.}

{160}{}{These mummers from the cult sometimes frighten me.}
{162}{}{I don't understand these fire worshippers.}
{163}{}{Fire worshippers, tinkerers, Blue Shields... Are we the only ones normal here?}
{161}{}{That sectarian offered me writing lessons. Fool, hehe.}
{164}{}{These fire worshippers seem to be pious, but they themselves have a sharp knife under their mantle.}

{165}{}{The caravaneers are talking about the big bang in Phoenix.}
{166}{}{I'm telling you - the Cathedral of fire worshippers has really been destroyed.}
{167}{}{Now instead of the Cathedral in Phoenix, there is one big hole.}
{168}{}{When you're in Phoenix, don't mess with sectarians.}
{169}{}{I've never liked sectarians. But without them, trade will decline.}

{170}{}{Giant radscorpions were seen on the railway again.}
{171}{}{I'm tired of eating only iguanas.}
{172}{}{When will the caravaneers bring something edible?}
{173}{}{You won't be satisfied with water alone.}
{174}{}{I miss our bar. And no one will replace its owner.}
{175}{}{People come and go. And I'm staying.}
{176}{}{We need to stick together. Otherwise we will end up the same as the others before us.}
{177}{}{Have you seen a stranger? If he finds out...}
{178}{}{Don't talk about it. And, however, who cares?}
{179}{}{}

{180}{}{Things have gotten really bad since this stranger showed up.}
{181}{}{We must all pile in at once and throw the stranger out of the city.}
{182}{}{What does this stranger allow himself?}
{183}{}{Another stranger was blown away by the wind.}
{184}{}{Well, it's going to get a little tighter in the city.}
{185}{}{Don't talk to this stranger.}
{186}{}{I don't like this newbie. In general, I don't like any newcomer.}
{187}{}{Since this stranger showed up, things have gone up the hill.}
{188}{}{We have this stranger to thank for everything.}
{189}{}{I can't believe that an outsider has done so much for us.}

{1180}{}{Things have gotten really bad since this outsider showed up.}
{1181}{}{We must all pile up at once and throw the stranger out of the city.}
{1182}{}{What does this stranger allow herself?}
{1183}{}{Another stranger was blown away by the wind.}
{1184}{}{Well, it's going to get a little tighter in the city.}
{1185}{}{Don't talk to this stranger.}
{1186}{}{I don't like this newbie. In general, I don't like any newcomer.}
{1187}{}{Since this stranger showed up, things have gone up the hill.}
{1188}{}{We have this stranger to thank for everything.}
{1189}{}{I can't believe that an outsider has done so much for us.}

{190}{}{Bustos was a tyrant, but without him the city will weaken.}
{191}{}{Everyone in the neighborhood was afraid of Count Bustos.}
{192}{}{Bustos is dead. A new war for the throne is about to begin.}
{193}{}{Sullivan and Bustos had another fight?}
{194}{}{Bustos is fat on our taxes, and we live in poverty.}
{195}{}{Don't say anything bad about Count Bustos. Don't.}
{196}{}{All those who opposed the count are silent.}
{197}{}{Only John Sullivan knew how to solve problems at the water pump.}
{198}{}{Who will manage the water pump now?}
{199}{}{The head of the water pump was a tough man.}

#Retaliatory remarks
{200}{}{Hi. Where are you from?}
{201}{}{Sorry, I'm not in the mood to talk.}
{202}{}{Sorry, uh, I'm in a hurry.}
{203}{}{Get someone else.}
{204}{}{We have a small town. Everyone knows about everyone.}
{205}{}{Tell me about yourself. However, no, don't.}
{206}{}{You're not going to stay here, are you?}
{207}{}{Good luck on the road.}
{208}{}{No, don't ask me anything.}
{209}{}{You're passing through, and I still have to live here.}

{210}{}{Get out of here while your legs are intact.}
{211}{}{We didn't call you.}
{212}{}{Get out of town.}
{213}{}{We don't need bandits like you.}
{214}{}{One more step and I'll defend myself.}
{215}{}{Go away. Immediately.}
{216}{}{If you don't leave, I'll call for help.}
{217}{}{When will a stray bullet find you, eh?}
{218}{}{I don't understand how they still tolerate you here.}
{219}{}{Go away. My patience is not unlimited.}

{220}{}{Hi, how are you?}
{221}{}{I'm sorry that you were so poorly received at the beginning.}
{222}{}{You're a real hero to us now.}
{223}{}{Let me shake your hand.}
{224}{}{My home is your home.}
{225}{}{Oh, it's you! Glad to see you.}
{226}{}{Are you here for a long time?}
{227}{}{I can't imagine what we would do without you.}
{228}{}{We're lucky to have you around.}
{229}{}{Thank you for everything.}

{1220}{}{Hi, how are you?}
{1221}{}{I'm sorry that you were so poorly received at the beginning.}
{1222}{}{You are now a real heroine for us.}
{1223}{}{Let me hug you.}
{1224}{}{My home is your home.}
{1225}{}{Oh, it's you! Glad to see you.}
{1226}{}{Are you here for a long time?}
{1227}{}{I can't imagine what we would do without you.}
{1228}{}{We're lucky to have you around.}
{1229}{}{Thank you for everything.}