{100}{}{Here is the old man Gallegos.}
{101}{}{You see a thin settler with a shaggy beard and shabby clothes. He hobbles along the street, leaning on a stick.}
{102}{}{Don't touch me, you piece of iron, I can still stand up for myself. Shoo, shoo.}

{200}{}{ququê quieres de mi?}
{201}{}{I just want to talk. Do you understand me?}
{202}{}{DÈjame en paz. No te entiendo.}
{203}{}{Uh, never mind. Forget it.}
{204}{}{Don't talk your teeth into me. It can't be that you don't know English.}
{205}{}{Yo no hablo inglês. DÈjame en paz!}
{206}{}{If you don't stop this performance, I'll knock your teeth out.}
{207}{}{Stop! Stop! Maldito seas, what do you want?}
{208}{}{Todo est· bien, amigo. Quiero hablar contigo.}
{209}{}{Shah! yEntonces hablas espaúol? Gusto escuchar mi lengua matera! (Ah, so you speak Spanish? How glad I am to hear my native language!)}
{210}{}{Todo... est... bien?}
{211}{}{Eh? quieres decir? No entiendo nada, habla m·s claro.}
{212}{}{It's too complicated for my mind. Goodbye, old man.}
{213}{}{Oh, now you understand me, right?}
{214}{}{That's better. Why all this representation?}
{215}{}{It can't be that you don't understand English at least a little.}
{216}{}{Have pity on the old man, seÒor. Strangers come and go. And I have to look for food. I'm hungry, maldita sea.}
{1216}{}{Have pity on the old man, seÒora. Strangers come and go. And I have to look for food. I'm hungry, maldita sea.}
{217}{}{OK, I'll look for food for you.}
{218}{}{It looks like you and I won't be able to have a conversation. And fuck you.}
{219}{}{It looks like you and I won't be able to have a conversation. Fuck you, el decrepito viejo.}

{240}{}{(raising his hands, begging for mercy) Ah, the robber! Don't touch me! I have nothing!}
{1240}{}{ (raising his hands, begging for mercy) Ah, the robber! Don't touch me! I have nothing!}
{241}{}{Hey, I'm not a robber.}
{1241}{}{Hey, I'm not a robber.}
{242}{}{If you scream, I'll kill you.}
{243}{}{ (raising his hands, begging for mercy) YNo me mates! Shno tengo nada!}

{250}{}{(Gestures ready to talk)}
{251}{}{Bye, old man.}
{252}{}{Ah, the food! Thank you, seÒor.}
{1252}{}{Ah, the food! Thank you, seÒorita.}
{253}{}{Shah, comida! Gracias, Seúog.}
{1253}{}{Shah, comida! Gracias, SeúOrita.}
{254}{}{You are welcome. Now can you tell us a little about yourself and the city?}
{255}{}{Just don't get drunk until you lose your pulse.}

{260}{}{Who are you, old man?}
{261}{}{Me? Well, my name is Gallegos. I live here.}
{262}{}{yMe hablas a mi? Mi nombre es Fernando Gallegos. Yo vivo aqui.}
{263}{}{Nice to meet you, Gallegos. Let's have a chat?}
{264}{}{That's all I wanted to know. Bye, Gallegos.}
{265}{}{How old are you, Gallegos?}
{266}{}{You look worse than a wrinkled mole rat. How old are you?}
{267}{}{I didn't count. I think I have already lived forty winters.}
{268}{}{No los he contado. Creo que por lo menos cuarenta primaveras, eso creo.}
{269}{}{A long time. Many have not lived even half. Aren't you from around here?}
{270}{}{You have an unusual accent. Aren't you from these parts?}
{271}{}{It's understandable why you look like a dead man. It's strange that you survived in these places at all.}
{272}{}{So you know a lot. Let's talk about something else.}
{273}{}{It's impressive. It's time for me to go. See you later.}
{274}{}{Right. Spanish is spoken in the south. I don't know your language well yet.}
{275}{}{Efectivamente. En el sur hablan espaúol, y no hablo bien tu idioma.}
{276}{}{So you came from the south? It must have been a hard road.}
{277}{}{You're delusional, old man. There's a barren desert in the south, you couldn't cross it.}
{278}{}{It's a real miracle that you survived.}
{279}{}{It was difficult to cross the desert. But we managed, because we had no choice. First we got to the city of Tucson, and they kicked us out. Then we came to Casa Grande and stayed here.}
{280}{}{Fue muy dificil cruzar el desierto. Pero lo logramos, porque no teniamos otra orsiÉp. Primero llegamos a la ciudad de Tucson, y de ahi nos echaron. Luego nos quedamos en Casa Grande.}
{281}{}{You say "we". Who else was with you?}
{282}{}{A few peasants. I'm the only one left alive.}
{283}{}{Varios campesinos. Pero yo soy el üpiso que aüp est·vivo.}
{284}{}{A sad story. I'm sorry.}
{285}{}{How interesting. I would like to ask more.}
{286}{}{Stop pouring this lies into my ears.}
{287}{}{Very interesting. But I have to go. Bye.}
{288}{}{}
{289}{}{}

{290}{}{What are you doing?}
{291}{}{A little bit of everything. What the residents need, I do. Yesterday I was looking for firewood for the bathhouse. It's good that she's working again.}
{292}{}{A little bit of everything. What the residents need, I do. Yesterday I was looking for firewood for the mayor. He likes to take a bath to relax.}
{293}{}{A little bit of everything. What the residents need, I do.}
{294}{}{Chambitas.}
{295}{}{Yeah, that was a pointless question. What else would I ask you?}
{296}{}{I'll keep that in mind. In the meantime, let's break up on this.}
{297}{}{Why are you limping?}
{298}{}{An old wound. What's it to you? Do you like to make fun of others?}
{299}{}{Es por una vieja herida.}
{300}{}{I'm sorry, I shouldn't have brought this up. Let's talk about something else?}
{301}{}{If you don't want to talk, it's your business. I'll find others to talk to. Bye.}
{302}{}{Hobbling like a pregnant brahmin before a sacrifice. Have you ever seen this?}
{303}{}{You're hobbling around like a mole rat that's drunk on uranium crumbs. Have you ever seen this?}
{304}{}{Even Uncle Jose, with his bad leg, worked on the plantations. And you're just a whiner and a loser.}
{305}{}{Laugh, yeah. I'll look at you when a stray bullet tears the fibers of your triceps.}
{306}{}{Callate, sinverguenza. Era una bala perdida.}
{307}{}{A stray bullet? This should be taken into account.}
{308}{}{It looks like this place is dangerous. I think I should get out of here, and as soon as possible.}
{309}{}{Come on, tell me how it happened. This will remain between us.}
{310}{}{Leave me alone.}
{311}{}{Dejame, canalla.}
{312}{}{Not until I hear everything you know.}
{313}{}{Okay, whatever you say.}
{314}{}{It's a pity that it happened. Tell me, how did it happen? I promise this will stay between us.}
{315}{}{A stray bullet. You know that abandoned bar up north? I was there when the shooting happened. The bullet hit me in the leg. Just an accident.}
{316}{}{Fue un accidente durante un tiroteo en el antiguo bar. Una bala me higiÉ la pierna.}
{317}{}{A stray bullet? This should be taken into account.}
{318}{}{It looks like this place is dangerous. I think I should get out of here, and as soon as possible.}
{319}{}{}

{320}{}{Tell me about the city.}
{321}{}{What is there to tell? We survive only thanks to the water station. She gives us water and attracts merchants from afar.}
{322}{}{La ciudad sobrevive gracias a la bomba de agua. El agua da vida a este desierto y atrae a comerciantes lejanos.}
{323}{}{Then why are the streets so empty here?}
{324}{}{Water attracts not only merchants. We are afraid of highway robbers and all sorts of speculators.}
{325}{}{El agua no solo atrae a los comerciantes. Tenemos miedo a los bandidos y a los ladrones.}
{326}{}{Ugh, and it already seemed to me that this is another ghost town.}
{327}{}{Tell us about the manager of your city.}
{328}{}{Count Bustos. He runs the city from that huge mansion.}
{329}{}{El conde Bustos gobierna la ciudad desde esa gran mapsi.}
{330}{}{Thank you, it helped me.}
{331}{}{In that mansion, right? I think I should check on him right now.}
{332}{}{No, I mean, what kind of person is he. How do you feel about him?}
{333}{}{It's dangerous to discuss those who are sitting over you. We don't know each other that well.}
{334}{}{No quiero hablar de êl.}
{335}{}{Indeed, your fears are not in vain. Maybe another topic will be less slippery?}
{336}{}{You're afraid of Bustos, and that says a lot. Now I don't want to ask anything either.}
{337}{}{I mean, what kind of person is he. Do people admire him or fear him?}
{338}{}{A terrible man. Cruel, greedy, keeps everyone in subjection. No one will say anything against him here.}
{339}{}{Es una persona terrible, es un tirano. aqui, nadie dirû nada malo de êl.}
{340}{}{So he's holding on tight to the city. Thank you for your honesty.}
{341}{}{Count Bustos is dead. Do you think the city will be better off without him?}
{342}{}{He was a terrible man. Greedy and cruel, he ruled everything with an iron hand. Everyone was afraid to say something bad about him. But without him, we are an easy target for robbers.}
{343}{}{êl era un tirano. Pero sin êl, nos convertimos en un blanco f·cil para los ladrones.}
{344}{}{Yes, even his tyranny had a certain meaning.}

{350}{}{I'm going to head south. Will you come with me?}
{351}{}{You're delusional. This is a deadly road.}
{352}{}{Estes completamente loco. Es un camino mortal.}
{353}{}{Sorry. I could use a guide in unfamiliar lands.}
{354}{}{If you get to Rancho Dominguez, tell him that I'm alive and that there are settlements in the north too.}
{355}{}{Cuando encuentres el rancho de Dominguez, cuentale sobre mi. Di que estoy vivo. Di que hay asentamientos en el norte.}
{356}{}{Rancho Dominguez? Thank you, I'll give him your regards. But it won't be soon, let's continue the conversation for now.}
{357}{}{I'll tell this Dominguez about you if I meet him. Bye.}
{358}{}{I'm not going anywhere with you.}
{359}{}{No voy a ninguna parte contigo.}
{360}{}{Expected. Can you at least answer the questions?}
{361}{}{Then stay here. Goodbye, el viejo.}