{100}{}{Here is a settler.}
{101}{}{You see one of the residents of Casa Grande. He shakes and throws into a fever.}
{102}{}{You see one of the residents of Casa Grande.}
{103}{}{You have successfully cured the patient.}
{104}{}{This man is suffering from scorpion venom. Your skills are powerless without powerful medicines.}

{110}{}{*Uv-f-f*}
{111}{}{Oh, I'm shaking all over from scorpion venom.}
{112}{}{I was stung by a damn radscorpion on the outskirts of the city.}

{115}{}{Thank you, I'm much better now.}
{116}{}{I was stung by a damn radscorpion on the outskirts of the city.}
{117}{}{There is no price for doctors like you.}
{118}{}{Thanks, Doc. There have been a lot of radscorpions in the area lately. Be careful. Here, take some cartridges with buckshot for protection.}

{120}{}{Oh...}
{121}{}{*Cough-cough*}
{122}{}{*Hack*}
{123}{}{Uv...}
{124}{}{*Groan*}
{125}{}{Hr-r...}