{100}{}{Here is a settler.}
{101}{}{You see an ordinary resident of Casa Grande.}
{102}{}{I will tell other residents about who saved me. Thank you.}
{103}{}{These arthropods appear quite suddenly. So let's keep our eyes open.}
{104}{}{These robbers are probably hiding somewhere nearby. So keep your eyes peeled.}

{110}{}{Help!}
{111}{}{Hey, somebody!}
{112}{}{Shoo, damn radscorpions!}
{113}{}{Go away, arthropods!}
{114}{}{You can't get to me, you creatures!}
{115}{}{I'll sit here until they leave.}
{116}{}{Is anyone looking for me?}
{117}{}{Hey, can anyone hear me?}
{118}{}{Help, I'm trapped!}
{119}{}{Somebody help me!}

{120}{}{Help!}
{121}{}{Hey, somebody!}
{122}{}{Here!}
{123}{}{I was locked up by robbers.}
{124}{}{I'm hungry.}
{125}{}{Are they going to save me?}
{126}{}{Is anyone looking for me?}
{127}{}{Hey, can anyone hear me?}
{128}{}{Help, I'm trapped!}
{129}{}{Somebody help me!}

{200}{}{Ugh, finally. I was afraid no one would save me.}
{201}{}{What are you doing here?}
{202}{}{Hiding from the radscorpions, of course. These creatures caught up with me while I was catching iguanas in the grass. I was lucky that I managed to hide in this shack.}
{203}{}{Have you been waiting for help for a long time?}
{204}{}{These arthropods are terribly patient. They can lie in the sun for days without food and water. I thought I'd starve to death while they were gone.}
{205}{}{Do you want to go back to the city?}
{206}{}{Sure. Is the way clear? Look, if everything's okay, I'm with you.}
{207}{}{Wait here, I'll deal with these creatures first.}
{208}{}{Then let's go to the city. They're probably already looking for you.}
{209}{}{Yes, exactly... (cautiously looks out from under the door) Uh, you first...}
{210}{}{Of course.}
{211}{}{Forward.}
{212}{}{Fool. I'm not a savior, I'm a robber. Give away everything valuable.}
{213}{}{Save me! I have nothing!}
{214}{}{Well, well.}
{215}{}{The hell with you. I don't want to get my hands dirty on you.}
{216}{}{What's there? Can I go out?}
{217}{}{No, there are still scorpions left. Sit here and keep your head down.}

{300}{}{Ugh, finally. I already thought no one would save me.}
{301}{}{Who locked you in here?}
{302}{}{They were highway robbers. They saw me in the desert and decided that I could warn the city about them. So they grabbed me and tied me up. It's a good thing they didn't kill me.}
{303}{}{Did you hear their conversations? Where did they go?}
{304}{}{Oh, listen, they're up to something! This attack on the caravan was a distraction. Look, they even left almost all the goods, except for weapons.}
{305}{}{We need to warn the mayor as soon as possible. Let's go to the city.}
{306}{}{Maybe the bandits are still nearby. While you sit here and wait for the right moment.}
{307}{}{What's there? Can I go out?}
{308}{}{Let's go. We have to tell Count Bustos about what happened.}
{309}{}{Going out can be dangerous for now. You'd better stay here.}