{100}{}{You see a settler.}
{101}{}{Here is a local resident of a rather repulsive appearance. It seems that local life was bleak for him.}

{200}{}{What do you want?}
{201}{}{I just want to know how life is in this small town.}
{202}{}{Life is bad. Just like everywhere else nowadays. But we have plenty of clean water. It's already worth it to choose Casa Grande for your stay.}
{203}{}{Then why are the streets so deserted here?}
{204}{}{I'll tell you what, stranger. Casa Grande has a complicated history. And what we have learned from this story is that it is better not to ask questions about the past. Do you understand me? That's great.}
{205}{}{Sounds like you have something to regret.}
{206}{}{Everyone in this city has had losses. And we are no exception. We lost our old house and our son. Therefore, no one here is going to reveal their soul to the first person they meet.}
{207}{}{Yes, I understand. I hope you'll forgive my curiosity. Goodbye.}
{208}{}{And they also say that everyone has as much shit as he managed to swallow. So I leave you with no regrets.}
{209}{}{Nothing.}

{210}{}{You again?}
{211}{}{Forget it, I'm just passing by.}

{220}{}{I'm looking for relatives of a boy named Cody.}
{221}{}{Cody? That was our son's name... I haven't heard from him for several years- since the tinsmiths took him away.}
{222}{}{Apparently we're talking about the same person.}
{223}{}{So he's alive? It's a miracle, we didn't even hope... That is, I want to say that there are terrible rumors about tinsmiths. How is he feeling?}
{224}{}{He is brainwashed and forced to work, but outwardly he looks fine.}
{225}{}{Yes, of course. He's already a different person... He was brought up as a tinsmith, deals with his hardware and probably doesn't even remember about us. It will be better if it stays that way. I just hope he doesn't hold a grudge against us.}
{226}{}{Hmm. I think I should clarify this point with him. Goodbye.}

{230}{}{I have evidence that Cody wasn't just taken away. You *sold* it.}
{231}{}{Shut up! Who are you to meddle in our affairs?}
{232}{}{Wait a minute...}
{233}{}{We were on the verge! The settlement was bent without water, we *had* to give everything to fix the water pump. Including our children. And now you come after so many years and stir up the past. You'd better leave us. Just leave us alone.}
{234}{}{You're right there - it's not for me to judge you. Goodbye.}
{235}{}{I hope that Cody has fallen into good hands and will live a better life than we do.}