{100}{}You see an orphan.}
{101}{}{You see a disheveled boy with a childish look.}
{102}{}{Hr-r-r...}
{1102}{}{Ma... ma... hr-r...}
{103}{}{I have shoes.}
{104}{}{Wow, thank you so much!}
{105}{}{Changing shoes makes a child happy.}

{200}{}{(On the side of the street you notice a boy with a wild look. His hair is disheveled, his clothes are soiled, and he cautiously throws a small metal object in his palms, intently studying your reaction.)}
{201}{}{Hey, boy. Do you know that this thing is dangerous?}
{202}{}{(He stops throwing the grenade and tenses up, as if waiting for a predator to jump) I'm not a boy.}
{203}{}{Okay, uh, I'll know. But this thing is still dangerous. You shouldn't do that.}
{204}{}{No. You're a boy. Kid. The immature child of man. And you are holding a thing that is extremely dangerous for others.}
{205}{}{ (the boy puts a grenade in his pocket and defiantly spits) And what?}
{206}{}{Oh, nothing.}

{210}{}{What do you need?}
{211}{}{Oh, nothing. Forget.}

{212}{}{Mmm, nice clothes. I want one. But it catches the eye too much. You need color to blend in with the sand. Otherwise, the enemies will find and kill.}
{213}{}{Well, yes, this jumpsuit is not for military purposes, you know.}
{214}{}{You want too much.}
{215}{}{Don't come near me, ugly face.}
{216}{}{The mainline operator! There's a trunk driver here!}
{217}{}{But no...}
{218}{}{Hey, you...}

{220}{}{When a ranger says to put the gun away, it makes sense, man.}
{221}{}{(looks at you in a puzzled way, then at the grenade, then back at you and shakes his head)}
{222}{}{Yes, man. I've seen people like you who mindlessly played with weapons.}
{223}{}{Nothing, you'll remember my words again.}
{224}{}{What happened to them?}
{225}{}{A sad sight. The explosion tears off the hands, the eyes burst and flow out of the sockets. Survivors writhe in pain for hours...}
{226}{}{Nothing special. Keep it up and you'll find out for yourself.}
{227}{}{(The boy throws a grenade like a hot potato and runs away.)}
{228}{}{Hey, I haven't told you a couple of instructive examples yet...}
{1228}{}{Hey, I haven't told you a couple of edifying examples yet...}

{230}{}{I want this grenade. Shall we exchange?}
{231}{}{What do you have?}
{232}{}{Let's see...}
{233}{}{(Waiting for your suggestions.)}
{234}{}{[Done]}

{240}{}{Do you know what will happen if you take out the ring?}
{241}{}{I know.}
{242}{}{Well, I'm happy for you. Later.}
{1242}{}{Well, I'm happy for you. Bye.}
{243}{}{Nope. This thing will play cool music. Come on, try it.}
{244}{}{(thinks for a while, then pulls his hand to the ring)}
{245}{}{No, no, I'm not really sure. Don't be in such a hurry.}
{1245}{}{No, no, I'm not really sure. Don't be in such a hurry.}
{246}{}{[Let him pull out the ring]}

{250}{}{Do you know what will happen if you take out this ring?}
{251}{}{I know.}
{252}{}{No, you don't. First, the force of the explosion will tear off both your hands. They will fly apart in the form of many bloody pieces.}
{253}{}{ (listening, eyes wide open)}
{254}{}{Then the shrapnel from the grenade will pierce through your chest and stomach. Your guts will fall out, and you'll start choking on blood.}
{255}{}{(listens with a gasp)}
{256}{}{The fragments will also damage the eyes, and they will flow out of the eye sockets. You'll go blind and lose consciousness. And when you wake up, you will have several hours of unbearable pain in a pool of your own blood, until...}
{257}{}{(the boy throws a grenade like a red-hot potato and runs away)}
{258}{}{Hey, I haven't told you about the internal hemorrhages yet...}

{260}{}{Give me the grenade, immediately.}
{261}{}{(having seen through your bluff, makes a mocking sound)}
{262}{}{Oh, that's how you are...}
{263}{}{}
{264}{}{Give me the grenade and no one will get hurt. You won't get hurt.}
{265}{}{(Bristles like a cub before danger)}
{266}{}{Do you hear? Give me a grenade. RIGHT NOW.}
{267}{}{Don't worry, I don't want to hurt you.}
{268}{}{(Speechless, he gives the grenade, but soon recovers and runs away in fright.)}
{269}{}{That's it, you piece of shit.}
{270}{}{Good boy.}

{271}{}{And let's play a game. If I lose, I will give you 5 caps, otherwise you will give the grenade.}
{272}{}{(Excitement appears in the boy's eyes) Okay.}
{273}{}{Great, then let's start...}
{274}{}{We'll do it later, now I have things to do.}
{275}{}{Let's play a game. If you lose, you will give away the grenade.}
{276}{}{Nah, I'm not that stupid.}
{277}{}{Okay, whatever you say.}
{278}{}{Yeah, I can tell by you. Ciao.}
{279}{}{You don't have 5 caps to start the game.}
{280}{}{No!}
{281}{}{Oh yes. And the grenade is mine now. That's fair, kid.}
{282}{}{You'd better shut up. It's mine now.}
{283}{}{Ha! You can't beat me.}
{284}{}{Well, well, we'll see about that.}
{285}{}{If you continue to make fun of me, I'll take both my caps and your grenade.}

{290}{}{Where are your parents, baby?}
{291}{}{I don't have any. What's it to you?}
{292}{}{Oh, sorry, I didn't think of that.}
{1292}{}{I'm sorry, I didn't think about it.}
{293}{}{But I don't need to be rude at all, you little brat.}

{300}{}{[Get the part from the music box and start the mechanism]}
{301}{}{(The child listens to the melody with fascination; surprise suddenly appears on his wild face, which has not known children's feelings for a long time.)}
{302}{}{What is it? Do you want it?}
{303}{}{(The boy nods happily, expressing in every possible way the desire to master an unusual subject.)}
{304}{}{Here you go.}
{305}{}{[Stretch out the mechanism, but then pull back the hand]}
{306}{}{(The boy smiles nervously, expressing in every way his desire to master an unusual object.)}
{307}{}{Eh? [repeat the process]}
{308}{}{(the boy stops trusting you)}
{309}{}{Yes, here you go.}
{310}{}{(The boy grabs the object, the emotions of simple childish delight appear on his face for the first time in his life.)}
{311}{}{And now tell me where did you find your grenade?}
{312}{}{It's in an old abandoned school over there. But sometimes there are highway workers there, it's dangerous.}
{313}{}{I don't give a damn about the mainline workers. Take me there.}
{314}{}{This is my thing. And I won't give it up.}
