{100}{}{This is Gil McCord.}
{101}{}{You see a wiry, unshaven man with a very sharp look. He looks at you doubtfully from under a cowboy hat.}
{102}{}{Are you still here? You must have no sense of fear at all.}

{200}{}{So the executioner for the executioner has arrived. Don't worry, I know all about you. I should have killed you right after killing the first Los Panchos. Apparently, I underestimated your strength.}
{201}{}{I'm still full of surprises, Gil McCord.}
{1201}{}{I'm still full of surprises, Gil McCord.}
{202}{}{Then take out ALL your cards, because someone's life is at stake. Mine or yours.}
{203}{}{I don't want to fight you.}
{204}{}{Now we will find out...}
{205}{}{It turns out you're one of those fools that life doesn't teach anything to. There is neither good nor evil in the world. If you take pity on someone, they will shoot you in the back at the first opportunity. This is the law of this world.}
{206}{}{What a heartbreaking speech. But stop talking. I'll take your head to Bruce Turner...}
{207}{}{Let's disperse peacefully. We don't need to fight.}
{208}{}{To give you a more convenient moment to attack? No. This number won't work with me.}
{209}{}{[Repel the attack]}
{210}{}{Then fight like a real shooter - we'll arrange a duel.}
{211}{}{You deserve respect. I agree.}
{212}{}{[Get out on the road waiting for a shootout]}
{213}{}{I really don't want another death on my conscience.}
{214}{}{What are you talking about? You cut off the heads of three sons of bitches and who knows how many others in cold blood. And then he carried them for several miles, enjoying the stench of decaying flesh. And now you're saying you don't want another death? You can't fool me with that.}
{1214}{}{What are you talking about? You cold-bloodedly cut off the heads of three sons of bitches and who knows how many more. And then I carried them for miles, enjoying the stench of decaying flesh. And now you're saying you don't want another death? You can't fool me with that.}
{215}{}{It wasn't quite like that. They did all the dirty work for me.}
{216}{}{(He pauses in bewilderment, then spreads into a satisfied grin). Ha! I thought so. You're just a charlatan. Now get out of my sight, you are not worthy of my attention.}
{1216}{}{(He pauses in bewilderment, then spreads into a satisfied grin). Ha! I thought so. You're an ordinary charlatan. Now get out of my sight, you are not worthy of my attention.}
{217}{}{And that was in vain-ah. Now you won't get rid of me so easily, you bastard...}
{218}{}{Whatever you say, sir.}