{100}{}{You see Gill McCord.}
{101}{}{You see a muscular, unshaven man with a very keen gaze. He's examining you from beneath his cowboy hat. You can tell that he doesn't trust you.}
{102}{}{You still here? You must not be afraid of death.}

{200}{}{So, the executioner's executioner has arrived. Don't move. I know all about you. I should've killed you back then, when you killed the first Los Panchos. Well, I underestimated your abilities. Now it's time to remedy this mistake.}
{201}{}{I'm still full of surprises, McCord.}
{1201}{}{I'm still full of surprises, McCord.}
{202}{}{Then take out ALL your cards, 'cause only one of us is getting out of here alive.}
{203}{}{I don't want to fight you.}
{204}{}{We'll see about that...}
{205}{}{You're an idiot. You ignore reality and remain wilfully ignorant to life's lessons. There is no good, no evil in the world. If you spare somebody, he will stab you in the back as soon as he gets the opportunity. *That's* how it works.}
{206}{}{What a harrowing speech. But enough philosophy. I need to bring your head to Bruce Turner...}
{207}{}{Why don't we both just turn around and leave? There's no need for us to fight.}
{208}{}{To give you a more convenient time to strike? No. I'm not an idiot.}
{209}{}{[Dodge attack]}
{210}{}{Then fight like a true marksman - let us arrange a duel.}
{211}{}{You deserve respect. I agree to a duel.}
{212}{}{[Head to the road and wait for the shootout]}
{213}{}{I don't want any more deaths on my conscience.}
{214}{}{... Are you fucking with me? You cut off the heads of three children and I don't how many other people in cold blood. You carried them around for miles, enjoying the smell of their decomposing flesh. And now you're saying you don't want to kill me? I'm not an idiot.}
{1214}{}{... Are you fucking with me? You cut off the heads of three children and I don't how many other people in cold blood. You carried them around for miles, enjoying the smell of their decomposing flesh. And now you're saying you don't want to kill me? I'm not an idiot.}
{215}{}{I don't like doing the dirty work myself. I pay others to do it.}
{216}{}{(Pauses, confused, then makes a satisfied smirk). Heh! Just like I thought. You're a simple fraud. Begone from my sight, charlatan.}
{1216}{}{(Pauses, confused, then makes a satisfied smirk). Heh! Just like I thought. You're a simple fraud. Begone from my sight, charlatan.}
{217}{}{Now that was unnecessary. You won't get rid of me that easily now, you bastard...}
{218}{}{Okay.}