{100}{}{You have a bodyguard in front of you.}
{101}{}{You see a man in combat gear. He's watching you closely.}
{102}{}{Hey, piece of iron, go back to the tinsmiths, we don't need such.}

{110}{}{The count is too busy for scum like you.}
{111}{}{What are you staring at?}
{112}{}{Do you need something?}
{113}{}{Don't even think about stealing something.}
{114}{}{Looks like someone is going to make trouble.}
{115}{}{You have to be quite desperate to come here.}
{116}{}{Are you looking for problems?}

{120}{}{Count Bustos is at home.}
{121}{}{Are you going to the mayor? Okay, come on in.}
{122}{}{Okay, come on in. But look, no nonsense.}
{123}{}{Don't try to disappoint the count.}
{124}{}{You can go now. But I'll keep an eye on you.}

{130}{}{Damn it, now I have to look for a new job.}
{131}{}{A city without a mayor will become more dangerous.}
{132}{}{Damn, the count paid good caps. And there was plenty of water.}
{133}{}{Although Bustos was a usurper, he regularly paid for his work.}
{134}{}{Well. Now I'm out of a job.}

{140}{}{You made the wrong city, raider.}
{141}{}{Hey, aren't you from the Blue Shields?}
{142}{}{The raiders are completely brazen, they are already walking freely around the city.}
{143}{}{Are the magistrates going to negotiate? Strange times have come...}