{100}{}{Here is Count Bustos.}
{101}{}{You see a man in a solid but dilapidated suit. His gray temples seem to hint at a difficult past.}
{102}{}{I've heard of such armor, but I thought it was fiction.}
{103}{}{I will not tolerate this major infection in my city.}
{104}{}{I advise you two to leave the city immediately.}

#First meeting
{200}{}{(When you enter the office of the local mayor, you immediately feel the unpleasant smell of alcohol. Looking around, you finally notice a man in a chair, wearily looking at you through his fingers. "M?" he says after a short pause.)}
{201}{}{And where is the mayor? I have a conversation with him.}
{202}{}{(With a heavy sigh, the man in the chair frees himself from the bent posture and leans back wearily). He's in front of you. But who are you?}
{203}{}{Are you the mayor? And he looks like an ordinary clerk who spends the entire fee in a bar.}
{204}{}{Let's get something straight. I am the legitimate mayor of this city. If you're not going to recognize the local government and accept the local rules, then get out of Casa Grande immediately. My city doesn't need troublesome outsiders. Is that clear?}
{205}{}{Yeah, I see.}
{206}{}{Excuse me, Mr. Mayor. I'm not going to cause any problems.}
{207}{}{That's good. So where did you come from?}
{1207}{}{That's good. So where did you come from?}
{208}{}{My name is }
{209}{}{, I'm traveling.}
{210}{}{Okay, }
{211}{}{. And where are you from?}
{212}{}{Why is this so important?}
{213}{}{Because in such a small town, everyone wants to know who you're dealing with and how much you can trust him. And no one here knows you at all.}
{214}{}{No one should care about my background.}
{215}{}{That's how, you don't want to accept the rules? You're walking a dangerous path, stranger. Then explain to me what the hell are you doing here?}
{1215}{}{That's how, you don't want to accept the rules? You're walking a dangerous path, stranger. Then explain to me what the hell are you doing here?}
{216}{}{I'm from a small village far from here. We just call it the Villa.}
{217}{}{I've never heard of such a thing. Let's assume it's true. What are you doing in my city so far from home?}
{218}{}{I'm just traveling. Can I spend the night at your place?}
{219}{}{I don't mind. Usually visitors spend the night near the water pump, in the barracks of the caravans.}
{220}{}{Thank you, Mr. Mayor.}
{221}{}{What kind of city do you have if you don't even have a motel? Okay, the barracks will do. Goodbye, Mayor.}
{222}{}{Bustos. My name is Alfred Bustos. Now go. I've spent too much time on you.}
{223}{}{[Leave]}

{224}{}{I'm looking for my people. They were captured by slavers.}
{225}{}{(raises one eyebrow) Slaves? And are you counting on something else?}
{226}{}{Have you heard anything about them?}
{227}{}{Slaveholders sometimes lead their slaves through my town. But I don't ask where they get them from.}
{228}{}{Where are they being taken?}
{229}{}{Some are being taken to work in the south. Others are just pulling the load... listen, stranger... what's your name there?}
{1229}{}{Some are being taken to work in the south. Others are just pulling the load... listen, woman... what's your name there?}
{230}{}{It doesn't matter.}
{231}{}{.}
{232}{}{Slaveholders are a serious force. If they took your family, then you have no chance to return their freedom. In addition, my city lives at the expense of caravanners. Don't you dare break this pattern.}
{233}{}{I'm not afraid of the slavers or you. Goodbye, Mayor.}
{234}{}{I just want my family back. You have to understand that, Mr. Mayor.}

{235}{}{There are no empty seats in the city. You can spend the night in the barracks with the caravans near the water station.}
{236}{}{Bustos. My name is Alfred Bustos. Welcome to my city.}
{237}{}{I need the mayor of this city. I'm from the Sacred Fire Church.}
{238}{}{What a surprise. Usually I am warned about the appearance of the ambassador of your church.}
{239}{}{Come in. Make yourself at home.}
{240}{}{What is it this time?}
{241}{}{You again? What is it this time?}
{242}{}{You again? I told you to get out of my city.}
{243}{}{Goodbye, Count Bustos.}
{244}{}{(When you enter the office, you find the local mayor leaning wearily on the table. In the second hand he holds a bottle of alcohol. "Oh ..." - he says, seeing your colorful robe.) What a surprise. Usually I am warned about the appearance of the ambassador of your church.}
{245}{}{I'm passing through here.}
{246}{}{Sure. Make yourself comfortable. Are you on your way to Two-Sun? Is there anything I can do to help?}
{247}{}{I'm interested in a slave convoy. Perhaps such a one took place here recently.}
{248}{}{Recently, the tinkerers have been collecting slaves for some important business. Several such caravans passed through my city. But I don't ask where they got the slaves from.}
{249}{}{So Two-Sun... Thank you, Mr. Mayor. I'll see you again.}

#Bathhouse
{250}{}{I need to talk to you about the bathhouse.}
{251}{}{The old abandoned building across the street? What do you care about him?}
{252}{}{Just idle curiosity. I don't dare to distract you any more, Mr. Mayor.}
{253}{}{Well, there is a person applying for this place.}
{254}{}{We have already discussed this with him. In our small town, everyone knows each other. People have been building relationships here for years, and many do not like the appearance of a stranger with a dubious past in the neighborhood. I will not tolerate scammers in my city.}
{255}{}{Hmm. And where then is the real owner of the bathhouse?}
{256}{}{Must have been eaten by radscorpions. These creatures are frequent in our area.}
{257}{}{It's so awful. I'll have to tell him your refusal.}
{258}{}{And then remember that I don't like people poking their noses into other people's affairs.}
{259}{}{Uh, okay, I'll remember.}
{260}{}{I see. I can rid you of this type once and for all.}
{261}{}{Sounds good. I'll pay 100 caps, but don't mention my name anywhere. I don't want my reputation to suffer.}
{262}{}{You can rely on me, Mr. Mayor.}
{263}{}{In that case, I want to buy the rights to the bathhouse for 250 caps.}
{264}{}{Well, that's fair. Bring the bottlecaps in, I'll draw up a bill of sale for the bathhouse.}
{265}{}{OK, see you later.}
{266}{}{Here are the bottlecaps, Mr. Mayor.}
{267}{}{I hope you understand what you're signing up for.}
{268}{}{Thank you, Mr. Mayor.}
{269}{}{He has a letter confirming the right to own the bathhouse.}
{270}{}{And no one knows where he got it. Stop trying my patience.}
{271}{}{Excuse me, Mr. Mayor.}
{272}{}{That's pretty rude of you.}
{273}{}{He has a letter confirming the rights to the bathhouse. And I confirm his identity.}
{274}{}{Well, you managed to convince me. But let this scoundrel know that no one was waiting for him here.}
{275}{}{As you say, Mr. Mayor.}
{276}{}{That's not very kind of you.}
{277}{}{It has something to do with the recent war in Casa Grande, doesn't it? Are you afraid of revenge?}
{278}{}{(sigh) Although I didn't kill the owner of the bathhouse, others did... against the background of the war that I started.}
{279}{}{I think the guy already knows. But it seems that he is only interested in business.}
{280}{}{Then it's a big risk for you. I'll tell the guy your refusal.}
{281}{}{It's true? Then it's worth talking to him. Although it is unlikely to atone for my sins.}
{282}{}{Great. I'll go to cheer him up.}
{283}{}{We know each other well. I guarantee that he can be trusted.}
{284}{}{Then it's worth talking to him. Although it is unlikely to atone for my sins.}
{285}{}{Great. I'll go to cheer him up.}
{286}{}{? It is not surprising that a person with such a name cannot sit still. }
{287}{}{If it's a joke, it's a bad one. If something happens to you, they will think about me, because no one will realize that there are two people with the same name in the city. It will be very unpleasant... }

{290}{}{The stranger won't bother you anymore.}
{291}{}{Very good. I don't like to dirty my hands.}
{292}{}{[Next]}
{293}{}{All work should be paid adequately. Here are your 100 caps. But don't forget - I have nothing to do with this incident.}
{294}{}{No one will know anything, Mr. Mayor.}
{295}{}{It is not in my interest to destroy relationships with potential clients.}

#Stop dialog
{300}{}{I don't know what you want to achieve, but there are more enemies on your list. Get out of my town. I don't need idiots like you.}
{301}{}{[Exit the building]}
{302}{}{The guards take you outside.}

{308}{}{Hi. Imagine some idiot digging graves in our cemetery. Maybe you know who does it?}
{309}{}{Is someone digging graves? I don't know anything about it.}
{310}{}{I remember you. After your appearance, graves were found dug in the cemetery.}
{311}{}{Strange coincidence, isn't it?}
{312}{}{So what? Are you accusing me of something?}
{313}{}{I don't believe in coincidences. If at least one piece of evidence appears against you in this case, then you will be severely punished. Understand this and don't do anything stupid.}
{314}{}{Wow, how scary.}
{315}{}{It seems that you are out of your mind if you behave like this with a representative of the authorities. Usually there is a lot of leniency for fools, but not in this city. We are tired of endless problems. So don't try my patience. Is that clear?}
{316}{}{I see.}
{317}{}{I have nothing to do with it, Mr. Mayor.}
{318}{}{Good. For now, we will consider it that way. Don't disappoint me.}
{319}{}{Of course, Count Bustos. No problem.}

{320}{}{Security says you fixed the street lamp?}
{1320}{}{Security says you fixed the street lamp?}
{321}{}{Exactly.}
{322}{}{I don't understand why you want to do this. But if you wanted to make an impression, then you succeeded. Thank you.}
{1322}{}{I don't understand why you want to do this. But if you wanted to make an impression, then you succeeded. Thank you.}
{323}{}{Won't they give me something for this?}
{324}{}{I didn't ask you to fix the lantern. But you can take clean water as a reward.}
{325}{}{Thank you, Mr. Mayor.}
{326}{}{And this is all your gratitude? Yeah.}
{327}{}{I just like to dig into old technology. You're welcome.}
{328}{}{You have raised your status in the eyes of the mayor, and therefore the rest of the city.}
{329}{}{Aha.}

{330}{}{Your appearance is one continuous trouble.}
{331}{}{Really?}
{332}{}{What are you talking about?}
{333}{}{A corpse of one of the residents was found near the railway station. Do you know anything about this?}
{334}{}{No, I don't know anything.}
{335}{}{Okay. We have yet to find out what happened there. Don't try to keep silent if you know something. Now go, I have a lot of work to do.}
{336}{}{[Leave the mayor alone]}
{337}{}{One of the residents has disappeared. She was last seen near the train station, where she was catching iguanas. Do you know anything about it?}
{338}{}{The Radscorpions must have eaten her. There are plenty of them there.}
{339}{}{Most likely. And yet you know that Radscorpions have turned up there. If you find out, be sure to let me know. Now go, I have a lot of work to do.}
{340}{}{She was not destined to reach the city. Radscorpions are to blame for this.}
{341}{}{That's it. Well, that sounds plausible. While you can go.}
{342}{}{[Leave]}

#Questions
{350}{}{I'm looking for a tinsmith who was sent to you as an ambassador.}
{351}{}{Didn't he go back to Two-Sun? In that case, I do not know where he can be.}
{352}{}{He was here?}
{353}{}{Yes, but he disappeared without saying a word. I thought he just left.}
{354}{}{And you didn't see anything strange about it?}
{355}{}{The tinkerers consider us mere mortals to be something like savages. They are a strange people, you can expect anything from them. Therefore, I did not worry about the quiet departure of our guest. Surely he is already among his own.}
{356}{}{No, he didn't go back to Two-Sun. Master Hard asked me to find him.}
{357}{}{Ah, I understand. Well, I've told you everything I know. You can ask around somewhere else.}
{358}{}{I will do so. Goodbye.}
{359}{}{In my opinion, something is not clean here. You're lucky, Mayor, if his disappearance has nothing to do with you.}
{360}{}{It seems that the locals don't like tinsmiths. Who could wish him harm?}
{361}{}{Hold your tongue, mercenary. We are indebted to the tinsmiths for repairing the water pump and regular caravans. None of the locals would dream of harming them.}
{1361}{}{Hold your tongue, mercenary. We are indebted to the tinsmiths for repairing the water pump and regular caravans. None of the locals would dream of harming them.}
{362}{}{And yet I will check this version. Goodbye.}
{363}{}{Such confidence breeds even more doubts, Mayor. Hope she doesn't let you down.}
{364}{}{Don't you think his disappearance is strange?}
{365}{}{Is he sure he got to Casa Grande?}
{366}{}{He never returned to Two-Sun. I was asked to find him.}
{367}{}{Looks like I'm wasting my time with you. I'm going to look for a tinsmith elsewhere.}
{368}{}{Surely this is so. Sorry for distracting you from business.}
{1368}{}{Surely this is so. Sorry to distract you from your business.}
{369}{}{And where did he stay during the visit?}

{370}{}{I want to ask about the city, I don't know it well yet.}
{371}{}{Casa Grande is my treasure. What do you want to know?}
{372}{}{All you need to know is the direction to the exit of the city.}
{373}{}{No one knows Casa Grande better than me. What do you want to know?}
{374}{}{Now I know enough. Goodbye.}
{375}{}{Let me take a little more of your time.}
{376}{}{In a former moonshiner's shack in the east. Tinsmiths don't like to be around... "ordinary" people.}

{380}{}{What can I do in this city?}
{381}{}{Casa Grande is a small town. We used to have a saloon that was famous all over the neighborhood for its own booze and old music. But the bar is closed, and the jukebox is broken, and now people are entertaining themselves.}
{382}{}{What happened?}
{383}{}{A robbery shootout in a bar. But this is a thing of the past. Just keep in mind that the bar is closed.}
{384}{}{We both know that it wasn't exactly a "rogue" shootout.}
{385}{}{You talk too much. Then in the bar my people ambushed the enemy clan. The bartender got a stray bullet. I'm sorry, he was a sincere person.}
{386}{}{Thank you for the honest answer. I think it's better to change the subject.}
{387}{}{Wow, your own booze?}
{388}{}{Yes, local production. Have you ever tasted this wonderful drink? The moonshiner supplied us with beer and traded it with Phoenix. Eh, if it weren't for those damn radscorpions, he would still continue to bring a good income to the treasury.}
{389}{}{I've seen tequila production in Phoenix before.}
{390}{}{Really? Sometimes caravans bring fire agave juice from the south for the Phoenix. This competition was like a lump in our brewer's throat. And now we are buying this Phoenix swill ourselves.}
{391}{}{Enough of the sad stuff. We need to change the subject.}
{392}{}{Is there a store here?}
{393}{}{If you need water, contact the water station. We take the rest of the goods from the caravaneers in the parking lot nearby.}
{394}{}{Why are there so many caravans here?}
{395}{}{Because we have a lot of water and we are halfway between Phoenix and Two-Sun settlement. A good position, except for the damn highway robbers.}
{396}{}{Rumor has it that the tinsmiths are no longer in business. How will this affect Casa Grande?}
{397}{}{In addition to the tinsmiths, there are other settlements in the south. And we can still trade water. Besides, after hearing this story, a lot of looters rushed to the south. Therefore, we will stay afloat for now, but what will happen next?}
{398}{}{They say the Phoenix Fire Church has been destroyed.}
{399}{}{Yes, and that's a problem. In a sense, the Church actively supported this caravan route. There will be fewer caravans without it. But over time, someone will surely take their place.}
{400}{}{What are these highway robbers?}
{401}{}{Different rabble comes across along the tenth highway. These bandits rob caravans and other travelers, which is why we suffer losses.}
{402}{}{Did you try to catch them?}
{403}{}{Who? Two dozen disparate and constantly changing gangs? This fight will never end. You kill some, others will come in their place. It is more important to deal with security inside the city.}
{404}{}{Let's forget about the mainline workers for now, there are other questions.}
{405}{}{I'm interested in that water station.}
{406}{}{Talk to Joe Sullivan at the station about it. He knows her like the back of his hand.}
{407}{}{Talk to someone at the station about it.}
{408}{}{OK, I'll look in there later.}
{409}{}{Great idea, I'll go there right now.}
{410}{}{Tell Sullivan about it. Who is he?}
{411}{}{I don't discuss my people with strangers. If you want to get to know Sullivan, get to know him personally.}
{412}{}{One more question before leaving.}
{413}{}{Then I'll go straight to him. Goodbye.}
{414}{}{Tell Sullivan about it. Is he a good person?}
{415}{}{He's like a brother to me. We started out together. I knew how to negotiate with people, and he knew how to solve problems. It would be hard without John.}
{416}{}{Looks like you're really like brothers. But I'm more interested in the city.}
{417}{}{Usually the word "brother" loses all meaning when it comes to business.}
{418}{}{I'll let it pass. Perhaps, in a big city, the caps are separated, but this is not the case here. I appreciate John as a reliable person. The most reliable in Casa Grande.}
{419}{}{Was Sullivan a friend to you?}
{420}{}{Don't mention his name. We started out together, and I could not have expected such a betrayal. Now I don't even want to hear about him.}
{421}{}{Didn't you previously call him "the most reliable person in Casa Grande"?}
{422}{}{It looks like you're really hurt by this. Let's not talk about it anymore.}
{423}{}{(fist bump on the table) Sullivan... He got what he deserved for his meanness. I can only erase this traitor from my life. And you'd better keep quiet until our relationship has completely deteriorated.}
{424}{}{Sorry, we won't talk about it anymore.}
{425}{}{If you want to close your eyes to past mistakes, it's up to you. Change the subject?}
{426}{}{You really are bringing one death to your city. I've had enough of these creepy stories.}
{427}{}{}
{428}{}{I shouldn't have gotten involved in this shit at all. Goodbye, Mayor.}
{429}{}{Weak argument, Mayor. Very weak.}

{430}{}{You have an unusually large cemetery for such a small population.}
{431}{}{You shouldn't go in there. And ask about things that don't concern you in any way.}
{432}{}{Sorry, I won't do it anymore.}
{433}{}{And yet. What happened here?}
{434}{}{A little bit of everything - robbers, scorpions... And enough about it. People don't like it when their past is stirred up.}
{435}{}{I know what happened here in the past. You seized power in Casa Grande by force.}
{436}{}{That robber claimed that you killed half the population to come to power.}
{437}{}{Difficult times require difficult decisions. If I hadn't started the fight then, someone else would have started it. This is the natural state of things.}
{438}{}{Was it inevitable?}
{439}{}{Too many people and too few resources. This city survives by a water pump and as a camp for caravans. There is nothing else in this desert that could give life. As a result, many did not find a place for themselves, looting and clan wars began.}
{440}{}{Now I understand why you are constantly drunk.}
{441}{}{So that's why you have so many bodyguards.}
{442}{}{You can't say goodbye to the past. This is our cross.}
{443}{}{I happened to visit a place where an ancient factory was restored. There, too, many people died fighting for him.}
{444}{}{Really? Heh, poor consolation. But I am glad that the wastelands are finally being transformed. I hope that during my lifetime I will still see Korvega on the move, as in old books.}
{445}{}{You're a monster. How could you kill dozens of people for your own benefit?}
{446}{}{If this conversation is too hard for you, then let's talk about something else.}
{447}{}{Now I know what to do with my head for the near future. Goodbye.}
{448}{}{Close your mouth and listen. I AM THE MAYOR OF THIS CITY. I'm responsible for him. And I will not allow ANYONE to desecrate its good name. Who are you to judge me? Just a stranger who was passing by. So go your own way.}
{449}{}{Your truth. I'm just a traveler who stopped by to drink. Goodbye, Mayor.}
{1449}{}{Your truth. I'm just a traveler who stopped by to drink. Goodbye, Mayor.}

#The first quest
{450}{}{Is there a job in the city? I could use some money while I'm here.}
{451}{}{I don't have a job for you.}
{452}{}{Clear. But maybe you can answer a couple of questions?}
{453}{}{OK, I'll go ask the rest of the residents.}
{454}{}{I don't have a job for you... However, you can solve one problem.}
{455}{}{What are we talking about?}
{456}{}{Highway robbers robbed one of the caravans near the railway station and locked themselves in with the goods inside. It seems that they are not going to leave, as if they are provoking or testing us. Go there and find out what they want.}
{457}{}{Are your guys standing here for show?}
{458}{}{Is there really no sheriff here for these purposes?}
{459}{}{No one wants to risk their lives for a box of old rags. We hope that the bandits will get tired of being locked up and they will leave on their own.}
{460}{}{I need caps, but I'm not going to take that risk. Look for someone else.}
{461}{}{OK, I'll get rid of these robbers.}
{462}{}{Great. The station is south of here.}
{463}{}{Prepare the reward. Soon the scum will regret their audacity.}

{470}{}{And here you are. Come in, have a seat. After that mess at the bar, I wanted to relax a little and have a drink. Pour yourself something. After all, it is thanks to you that my daughter and I still enjoy our freedom.}
{471}{}{A strange story. Count, why did the robbers get so close to the city?}
{472}{}{Highway workers usually rob travelers on the highway and are afraid to come close to the city. But they knew what to do, because their leader once lived in Casa Grande... However, it's a long story, and I still haven't paid you for your help.}
{473}{}{[Next]}
{474}{}{Here are 250 caps. And you can earn more.}
{475}{}{More? How much more?}
{476}{}{I'm listening. Who's the problem this time?}
{477}{}{Your freedom cost someone their life, didn't it?}
{478}{}{Your tongue is too loose for a mercenary. As you know, highway workers rob travelers on the highway. But the robbers in the bar had personal scores. However, it's a long story, and I still haven't paid you.}
{479}{}{[Next]}
{480}{}{And here you are... Come in. After that bar fight, I need a drink.}
{481}{}{I am very sorry that your daughter died.}
{482}{}{To hell with regrets! I once made the mistake of driving some residents out of the city instead of executing them. And they came back. Now I have to take cruel revenge on the mainline...}
{483}{}{[Next]}
{484}{}{Are you trying to wash down the problem with alcohol? It won't work.}
{485}{}{What do you understand... (calms himself) Your truth. I once made the mistake of driving some residents out of the city instead of executing them. And they came back. Now I have to take cruel revenge on the mainline...}
{486}{}{[Next]}
{487}{}{I think you needed the caps? I will not pay for the disassembly in the bar. But I will pay for a new case.}
{488}{}{What should I do?}
{489}{}{Those bandits in the bar belonged to the largest clan of highway workers-the Blue Shield Clan. He is known throughout the neighborhood for his ruthless crimes. After robbing the last caravans, these scum got good equipment. So now the whole city is at risk of being held hostage.}
{490}{}{Are you suggesting we stop them? But how?}
{491}{}{Kill their leader, Ben. I'll pay 500 caps for his head.}
{492}{}{I've been looking for smart people like you for a long time to find their lair and finish off their leader Ben. Without him, the clan will fall apart and, at least for a while, leave us alone.}
{493}{}{There is no need to explain the whole story. What is the price?}

#The second quest
{500}{}{Highway robbers are like scavengers - they stick together in packs and hunt down easy prey on the highways. Small clans do not pose a threat to the city. But there is one big one.}
{501}{}{Let me guess - is that where the robbers who captured your daughter came from?}
{502}{}{Yes. And this is not their first major attack. The Blue Shield Clan is known throughout the district for its ruthless crimes. It includes the most desperate and reckless bastards who have no place in a civilized society.}
{503}{}{Sounds terrible. But is it possible to stop an entire gang by force of mercenaries?}
{504}{}{To hell with the background. Just tell me how to find them.}
{505}{}{There's no need to kill a whole crowd. I will pay 500 caps for the head of their leader, Ben. You'll get the same amount if you destroy their fuel depot.}
{506}{}{All these deaths will be in my nightmares for more than one night. I'm washing my hands of it this time.}
{507}{}{Well, it's a pity. I was already hoping that this was really a real fighter in front of me. But don't rush to a decision. The problem won't solve itself, and I'm always willing to pay for a good job.}
{508}{}{Goodbye.}
{509}{}{Great, consider this Ben's skull already in your hands.}
{510}{}{Everything is simple. Bring the head and you'll get a reward. Good luck.}
{511}{}{Goodbye.}
{512}{}{I need to know more about these mainline drivers.}

{520}{}{About the mainline workers.}
{521}{}{What news?}
{522}{}{None yet. I just want to say that I am working on this problem. Goodbye.}
{523}{}{Why is this clan so strong?}
{524}{}{After the attacks on the last caravans, these robbers received good equipment, which the tinsmiths produced on their machines. In addition, they have huge reserves of combustible mixture. If this goes on, the whole city will soon be held hostage.}
{525}{}{Where did they get so much fuel from?}
{526}{}{They say they have occupied an old gasoline warehouse and are using it as a fortress. And fuel serves as their weapon.}
{527}{}{Tell me about their leader.}
{528}{}{His name is Ben. He used to live among us, but I drove him and his gang out of town. That's why he's so familiar to me.}
{529}{}{Why is it so important to kill the leader?}
{530}{}{Without a leader, the clan will fall apart and leave us alone at least for a while.}
{531}{}{What's the point of destroying a fuel depot?}
{532}{}{Fuel serves as a weapon for the gang and helps in survival. And in the future it could be used for trading. In addition, with the burned capacity, it will become more difficult to use the citadel. In any case, such a diversion will greatly shake the gang.}
{533}{}{And how will you know if I blow up these warehouses?}
{534}{}{I'll see the smoke through binoculars. There are eyes and ears everywhere, such an event will not hide from anyone.}
{535}{}{Where is the main base of the Blue Shields?}
{536}{}{Judging by the words of the caravaneers, it is somewhere in the northeast of us.}
{537}{}{How did it happen that the residents of Casa Grande got mixed up among the mainline workers?}
{538}{}{It's an old and long story. When I got to the post of mayor, the first thing I did was evict all the scum from the city. As it turned out, some of them survived and began to terrorize highways.}
{539}{}{I've learned enough. See you later, Count.}
{1539}{}{I've learned enough. See you later, Count.}
{540}{}{Here is the head of your enemy. You recognize him, don't you?}
{541}{}{(silently looks at the head with contempt and hatred for a while, then waves his hand away) Throw this stuff out on the wastelands. Let the radscorpions eat the last reminder of the mainline workers.}
{542}{}{Whatever you say, Count.}
{543}{}{No, don't touch it. I'll hang this head on the railroad at the entrance to the city. Let people know what awaits them in case of disobedience to the authorities.}
{544}{}{Good idea. }
{545}{}{Then don't forget to sign who killed him.}
{546}{}{I appreciate people who do their job flawlessly. You deserve a reward... (takes the lid out of the safe) Here are 500 caps, as we agreed. Now leave me alone. I want to rest.}
{547}{}{Goodbye, Count.}
{548}{}{Hey, where's my reward? I didn't just trudge along hot highways with rotting flesh in a bag.}
{549}{}{Sure. This is your honestly earned right... (takes the caps out of the safe) There are 500 caps here, as we agreed. Now leave me alone.}

{550}{}{I've destroyed the Blue Shield fuel depots. This will surely weaken the gang.}
{1550}{}{I've destroyed the Blue Shield fuel depots. This will surely weaken the gang.}
{551}{}{So the rumors are true. The caravaneers saw smoke away from the trade route. If the fuel is destroyed, then a hard time will come for the raiders.}
{552}{}{Ahem. The services are not free, wasn't that the deal?}
{553}{}{Of course, here's the reward - 500 caps. And thank you. Your service is invaluable for the city.}
{554}{}{You're welcome, Count. As long as the city brings caps, it has a future.}
{555}{}{I know well from my community how to tolerate violence against you. Therefore, I consider it my duty to stop the mainline workers.}
{556}{}{That's how? Now it's clear where you got so much strength to fight. I really hope you will save your people from captivity. Take the reward, there are 500 caps here. And thank you. Your service is invaluable for the city.}
{557}{}{Goodbye, Count Bustos.}
{558}{}{That was the calculation. For a while, the raiders will weaken and start fighting with each other.}
{559}{}{Great job. It's not a pity to pay all 500 caps for this. And thank you. Your service is invaluable for the city.}
{560}{}{You're welcome, Count Bustos.}

{569}{}{Your city is already suffering from robbers. So there will be fewer of them.}
{570}{}{They say you caught one of the highway robbers?}
{571}{}{It's true. We keep him locked up. First we need to get all the information about the gang out of him, and then we will publicly execute him.}
{572}{}{Are you sure he's a criminal?}
{573}{}{Some residents identified him as a highway worker. I believe them. In addition, he was wearing road shields, highway workers often use them as armor during attacks.}
{574}{}{Well, congratulations, Mayor. And I have to go.}
{575}{}{I need to see him. Maybe I can find out something from him.}
{576}{}{He's locked up downstairs. Tell the guards to let you through.}
{577}{}{You've got the wrong guy. He needs to be released.}
{578}{}{Am I supposed to let him go just by taking your word for it? Too naive a move. It's interesting to hear your arguments.}
{579}{}{My job is to inform, the rest is on your conscience.}
{580}{}{Isn't my testimony enough?}
{581}{}{No. I trust my people, but not you.}
{582}{}{Then this decision will remain on your conscience. Goodbye.}
{583}{}{We, well, worked with him in the same caravan. I can guarantee that he does not pose a threat to you.}
{584}{}{Hmm. To be honest, I myself do not know who he is or where he comes from, and residents always see an enemy in an outsider. Okay, I'll let this guy go for now, but on the condition that he has to get out of my city within an hour.}
{585}{}{Thank you, Mr. Mayor.}
{586}{}{How about a deposit? I'll pay 100 caps for his freedom.}
{587}{}{Sounds acceptable. But tell him to get out of town within an hour.}
{588}{}{Thank you, Mr. Mayor.}
{589}{}{Sounds acceptable.}
{590}{}{I'll bring the bottlecaps in soon.}
{591}{}{The Blue Shields offer an alliance. They have already agreed with the tinsmiths.}
{592}{}{What? Are these bandits protected by tinkerers? What an injustice!}
{593}{}{The tinsmiths recognized them as a peaceful independent settlement.}
{594}{}{I should have acted faster. It's good that the gang will leave us and the caravans behind for a while. But bandits can't be trusted. In addition, many of them seek revenge on me personally or the entire Casa Grande.}
{595}{}{You don't have a choice. The tinkerers won't approve of resistance.}
{596}{}{Obviously, it is. I will sign the contract, considering your past achievements. But I will do everything to make the Shields pay dearly for it.}
{597}{}{I'll tell Ben what you said. Goodbye.}
{598}{}{I'll be damned if I sign this union. Get out and tell Ben that the tinkers won't protect him and his gang from a righteous judgment.}
{599}{}{I'll tell Ben what you said. Goodbye.}