{100}{}{You have a bodyguard in front of you.}
{101}{}{You see a man in combat gear. He's watching you closely.}
{102}{}{Hey, piece of iron, go back to the tinsmiths, we don't need such.}
{103}{}{T-you... What do you want? Get out of here!}

{200}{}{The count and the others are now at the abandoned bar. Something happened there, but I do not know what exactly.}
{201}{}{So, at the bar. Thanks, bye.}
{202}{}{Why aren't you there?}
{203}{}{I'm guarding the mansion. It is unwise to leave all this luxury unattended.}
{204}{}{Well yes. So, at the old bar...}

{210}{}{The Count is no more. He's dead. Do you understand? Do you understand, eh? Yes, the whole city is over now!}
{211}{}{Because of one person, the city will not disappear from the face of the earth. Calm down.}
{212}{}{I'm calm. Yes, I am calm. I just found myself a normal fucking job. And now, because of an accident, I'm back on the street. Without work, without caps and without connections. What should I do now?}
{213}{}{The city is now free from the usurper and tyrant. Aren't you happy?}
{214}{}{I'm glad. yes, of course. After all, I just found a normal fucking job. From this tyrant himself. And here I am again on the street because of an accident. And what should I do now?}
{215}{}{Really. Any ideas?}
{216}{}{Well, you can go to robbers. And why not? There are many caravans, but I am alone. It's okay, it's necessary to survive somehow.}
{217}{}{Yes, you are a danger to society. You need to be executed immediately.}
{218}{}{Uh, I can't agree with you. I hope you find a job. Bye.}
{219}{}{What do you want?}
{220}{}{Nothing, perhaps.}
{221}{}{Your death.}

{230}{}{Ah, hello. The Count is in his room.}
{231}{}{Ah, hello. The Count was just looking for you. He wants to talk about something with you.}
{232}{}{I need to go to him.}

{250}{}{Uh, wait. Where are you going?}
{251}{}{Just wandering around the city.}
{252}{}{It looks suspicious. But, uh, I forgive you for the first time.}
{253}{}{Forgive me? For what?}
{254}{}{Well... listen, this is Count Bustos' house. He REALLY doesn't like it when someone is around doing nothing. Do you understand? So get out of here. Come on, don't give me any trouble.}
{255}{}{Okay, see you later.}
{256}{}{By the way, tell me about this count. Who is he and what does he do?}
{257}{}{I'm just curious, who lives in such a posh mansion?}
{258}{}{Count Bustos. He's the head of the city.}
{259}{}{So I should see him. Is he receiving visitors now?}
{260}{}{Maybe. But he REALLY does not like to be disturbed without doing anything.}
{261}{}{Still, I need to talk to him. Bye.}
{262}{}{Tell me more about him. You say he's the mayor of the city?}
{263}{}{Thank you. That's all I wanted to know.}

{300}{}{Tell me about the count.}
{301}{}{Count Alfred Bustos. He is the mayor of the city and the head of the Chamber of Commerce. He's also my boss. However, I'm still only on probation.}
{302}{}{Why is he called a graph?}
{303}{}{Well, he's a graph. It's something like a title. I do not know, to be honest, what it means. But it sounds cool.}
{304}{}{Do you think he needs another guard?}
{305}{}{I don't know. Talk to him.}
{306}{}{Who are you anyway?}
{307}{}{Tell me more about Count Bustos.}

{310}{}{Who are you?}
{311}{}{I'm just a security guard.}
{312}{}{Are you local?}
{313}{}{No, from a small community near Phoenix. The community went bankrupt, so I went to the big city. Things didn't work out there either, so I joined the caravan to earn caps. But they left me here on the way. I haven't seen the caravan since. Hell, they didn't even pay me the full amount.}
{314}{}{Have you been working here as a security guard since then?}
{315}{}{No, just a few months. The count needed people, and there was no one among the locals to recruit for protection. Otherwise I wouldn't be here.}
{316}{}{And correctly. No one needs a useless "ballast" on the tail.}
{317}{}{I'm not useless! And why are you asking me? You'd better go your own way, Uncle. I don't have to talk to you at all.}
{1317}{}{I'm not useless! Don't, lady, I know these ladies' tricks. You'd better go your own way. I don't have to communicate with you at all.}
{318}{}{Well, well.}
{319}{}{I have to go.}
{320}{}{By the way, why are these streets so deserted?}
{321}{}{This isn't Phoenix, it's a small town here. But I don't understand either. After all, there are a lot of bottlecaps and caravans often pass here.}
{322}{}{And it already began to seem to me that this is another ghost town. Okay, I'm going for a walk.}
{323}{}{It turns out that you were taken out of desperation. I'm wasting my time with you.}
{324}{}{Surely the count understood who he was hiring. I need to meet him.}
{325}{}{What an injustice. You definitely don't deserve this.}
{326}{}{Exactly. I hope they were eaten by radscorpions. But now I work in a good position with a normal salary. Great, right?}
{327}{}{You're just lucky. Make no mistake.}
{328}{}{Well yes. By the way, it's time for me to see your employer. Bye.}