{100}{}{You see Kristina.}
{101}{}{You see a girl with a puzzling look. It seems that the easy life has not taught her anything yet.}
{102}{}{You see a girl with a sad look. It seems that recent events have made her think deeply.}
{103}{}{Wow, how do you go to the toilet in this thing?}
{104}{}{Daddy... daddy... he's gone...}
{105}{}{Where did you get THIS? Hide it immediately before anyone sees it. Dad's bodyguards immediately shoot at any highway worker.}
{106}{}{What's going on? Where's my dad?}

{110}{}{Z-z-z...}
{111}{}{Hr-r...}
{112}{}{...Daddy, it's too early...}
{113}{}{...It's not a dream...}
{114}{}{I'm... dreaming...}
{115}{}{...It's... a dream...}
{116}{}{Do you know what time it is now?}
{117}{}{I want to sleep.}
{118}{}{Don't disturb my sleep.}
{119}{}{Let me sleep.}

{120}{}{*Humming*}
{121}{}{A great day for practical jokes.}
{122}{}{Maybe offer that newcomer a poker game?}
{123}{}{We need to ask for more caps from Daddy.}
{124}{}{Nothing, Daddy will forgive me.}
{125}{}{Eh, how boring...}
{126}{}{What would you like to do?}
{127}{}{Water, caps. caps, water. They can't think of anything else?}
{128}{}{I would like to see the neon Phoenix again.}
{129}{}{It got really boring without the bar.}

{130}{}{Ah...}
{131}{}{*Sigh*}
{132}{}{I don't even want to play cards.}
{133}{}{Why did it happen like this?}
{134}{}{A terrible story.}
{135}{}{I won't be able to live as before.}
{136}{}{I don't understand how it could have turned out like this?}
{137}{}{Why did people become so angry?}
{138}{}{}
{139}{}{}

#Acquaintance
{200}{}{Oh, hello. New faces are always so interesting. My name is Kristina. Are you here for a long time?}
{201}{}{Well, I...}
{202}{}{Come on, stay, it's good here. Although the city, of course, is boring. I'm just dying without gambling.}
{203}{}{Not a bad idea, but I need to talk to the mayor.}
{204}{}{As usual. Okay, go ahead. He's probably in his office. Don't forget to knock before entering.}
{205}{}{OK.}
{206}{}{I'm not up to games right now. Need to look around.}
{207}{}{Ah, what a disappointment. Okay, go ahead. I hope you change your mind. Just don't hang around our house doing nothing. My daddy doesn't like it.}
{208}{}{OK.}
{209}{}{He should be more friendly.}

{210}{}{Oh, hi.}
{211}{}{Bye.}
{212}{}{I want to ask you about the city.}
{213}{}{Uh, listen, I don't want to talk to you, okay? If you insist, I'll call the bodyguards.}
{214}{}{Well, sit alone, bitch. Now it's clear why no one registered you.}
{215}{}{Why is the whole city so mad at me? Okay, forget it.}

#Game
{220}{}{Oh, hello. Do you want to play cards?}
{221}{}{Let's play. I'm putting 10 caps on.}
{222}{}{Oh, hi. Do you want to play cards? I haven't played with anyone for so long that I'm dying of boredom.}
{223}{}{Sorry, but I don't gamble.}
{224}{}{And in my opinion, you're being nice.}
{225}{}{Uh, I don't think so. Bye.}
{226}{}{Gambling?}
{227}{}{What else! Without betting, the game becomes boring. And when you know that you can lose your valuables - that's when a real drive appears.}
{228}{}{Um, do you really have caps on the game?}
{229}{}{Of course! My daddy is the head of the city. Even if I lose, he will give me more pocket caps, he has the whole safe full of them.}
{230}{}{I'm sorry, but I can't waste time playing games right now. Maybe another time.}
{231}{}{What a pity. Okay, go solve your *important things*.}
{232}{}{You know, it's time for me to relax. I'll put 10 caps on.}
{233}{}{Uh, bye.}
{234}{}{OK, let's play. I put 10 caps.}
{235}{}{Great. This is already intriguing...}
{236}{}{And he will do the right thing. Stop wasting his capital.}
{237}{}{See you later. Don't miss.}
{238}{}{Oops. And where are my bottlecaps...}
{239}{}{[Start the game]}
{240}{}{Hurray! The card went!}
{241}{}{What? No, I want to win back.}
{242}{}{I'll leave you.}
{243}{}{What about? Why so early? We've only just started. Well, that's fine. It's boring with you anyway.}
{244}{}{Bye.}
{245}{}{What? Did I lose? Oh no, Daddy's gonna kill me... However, this is only 10 caps. But I was happy to kill time.}
{246}{}{Do you want to play again?}
{247}{}{I will leave you.}
{248}{}{No, I'm afraid Dad won't give me any more gambling caps.}
{249}{}{Pf. That's so boring!}

#Questions
{300}{}{Who are you?}
{301}{}{Christina. Have you lost your memory?}
{302}{}{Are you the mayor's daughter?}
{303}{}{Well yes. Don't we look alike? Look - we have the same nose and eyes.}
{304}{}{Exactly. And I have a feeling that I need to meet your father urgently. Right now.}
{305}{}{It's great. Surely you know a lot about this city?}
{306}{}{What can you tell us about the city?}
{307}{}{Just that it's deadly boring here. Although there are seasons when caravans flock to the city. Then a lot of interesting things happen.}
{308}{}{How interesting. But who are you?}
{309}{}{There's no help from you. I'm going to look for other experts.}
{310}{}{Why do you have such a big cemetery in the east?}
{311}{}{And why not? People are dying, they need to be buried somewhere. Is it not so in other places?}
{312}{}{I have never come across a larger cemetery.}
{313}{}{I don't know. I've been here all my life and have only been to Phoenix once.}
{314}{}{I have to go.}

{320}{}{Hi. How are you?}
{321}{}{I wanted to check on you. You're doing great. Bye.}
{322}{}{Do you want to play cards?}
{323}{}{No, I don't play cards anymore. And no games at all.}
{324}{}{I understand. Be.}
{325}{}{So what did those robbers want from you?}
{326}{}{Revenge on my father for past misdeeds. I didn't know what horrors he had done in this city before.}
{327}{}{I see. Don't lose heart.}

{330}{}{Oh, it's you... They killed my dad, do you know?}
{331}{}{Yes, I saw it with my own eyes. How are you?}
{1331}{}{Yes, I saw it with my own eyes. How are you?}
{332}{}{I am well. Honestly. While I was being held hostage, the bandits were discussing my father. They said that he took power from the last mayor and that he ruthlessly exterminated half of the residents who opposed his power. I was too young to remember those days. Is that really true?}
{333}{}{Stop being a naive fool, open your eyes - any power is violence. Your daddy is just an example.}
{334}{}{I understand... Perhaps he was a tyrant and committed terrible atrocities. But for me, he was a loving dad. He always tolerated my whims and gave me the best. How could it have turned out like this?}
{335}{}{Welcome to the world of reality, baby. A world built on blood.}
{336}{}{Yes. Now I understand. And I will do everything so that this does not happen again.}
{337}{}{As you wish. And my business in this city is over. It's time to hit the road.}
{338}{}{It looks like it. I'm sorry.}
{339}{}{At least he loved you. So, deep down, he was not a tyrant. It's just the way things happened.}
{340}{}{Wait. You probably need bottlecaps for the road. Here, take this. These are the remnants of my pocket bottlecaps. You need them more now.}
{341}{}{Thank you. And goodbye.}
{342}{}{Wait. You probably need bottlecaps for the road. Here, take this. These are my pocket bottlecaps. And also all the ones that you safely lost to me at cards. You need them more now.}
{1342}{}{Wait. You probably need bottlecaps for the road. Here, take this. These are my pocket bottlecaps. And also all the ones that you safely lost to me at cards. You need them more now.}
{343}{}{Good luck to you. And it's time for me to go on a long journey.}
{344}{}{Goodbye, stranger.}
{345}{}{Goodbye.}
{346}{}{Oh, it's you... I am eternally grateful to you for saving me.}
{347}{}{Then why do you have such a sad face?}
{348}{}{Hey, where's that gambling look of a naive girl?}
{349}{}{At least he loves you. Which means he's not a tyrant at heart. It's just the way things happened.}