{100}{}{You see a ranger.}
{101}{}{You see a man in leather armor.}
{102}{}{We have nothing more to talk about.}

{200}{}{Well, well. Looks like we've got a troublemaker here. }
{201}{}{Oops...}
{202}{}{What are you doing, you fool?}
{1202}{}{What is such a lady doing in a cemetery?}
{203}{}{It's none of your business. I won't tell you anything.}
{204}{}{Very sorry. It's a pity that people like you interfere with normal people's lives.}
{205}{}{[Next]}
{206}{}{(pulls out a weapon) By the authority vested in me by the Arizona Ranger Department and the constitution, I sentence you... to death. The sentence should be carried out immediately.}
{207}{}{Thu...}
{208}{}{Go to hell.}
{209}{}{Stop! The tinsmiths asked me. They are looking for their comrade, he is lying in this grave.}

{210}{}{Looking for valuables, sir.}
{211}{}{Valuables in the grave? Did it ever occur to you that it would upset someone VERY much?}
{212}{}{Spit. And what's next? Will you try to stop me?}
{213}{}{The dead don't need it.}
{214}{}{Maybe so. But it's not up to you to decide. And it is in my power to punish you for such a misdemeanor.}
{215}{}{Who are you?}
{216}{}{Yes, sir. I admit my guilt, sir.}
{217}{}{These tricks won't work with me, buddy. I have an eye for people like you.}
{1217}{}{These tricks won't work with me, lady. I have an eye for people like you.}
{218}{}{Who are you?}
{219}{}{Oh no, this person's relatives won't mind. And do you know why?}

{220}{}{I'm a ranger. But who are you? Why do you come to this city and act like you can do anything?}
{221}{}{The tinsmiths are looking for their comrade. He was killed. And it looks like you know something about it.}
{222}{}{Who are you anyway?}
{223}{}{None of your business.}

{230}{}{Oh no, no, you misunderstood me, I'll explain everything now.}
{231}{}{Work hard, I'm listening carefully.}
{232}{}{You see, I'm looking... [Get a weapon and attack]}
{233}{}{It's none of your business. I won't tell you anything.}
{234}{}{The tinsmiths asked me. They are looking for their brother. He's here.}

{240}{}{I know. I killed him.}
{241}{}{But why? What's wrong with the tinker?}
{242}{}{Scum like tinsmiths should be lying in the ground. They consider themselves gods as if everything is allowed to them. They oppress the residents, take away the latest technologies from them, and force them to work. Their power casts doubt on any hopes for justice in the lands of Southern Arizona. And their very existence, combined (contemptuously) with technology, is inhumane. As for me, this is quite enough.}
{243}{}{[Next]}
{244}{}{And what attracted you so much to tinsmiths? Bribed by the ringing of rusty caps?}
{245}{}{Maybe so. I'm a simple mercenary, I don't care about your Arizona and justice.}
{1245}{}{Maybe so. I'm a simple mercenary, I don't care about your Arizona and justice.}
{246}{}{Well. You work for the enemies of the wasteland, so you are an enemy yourself.}
{1246}{}{Well, if you work for the enemies of the wasteland, then you are an enemy yourself.}
{247}{}{[Next]}
{248}{}{No need. Please.}
{249}{}{Oh shit...}
{250}{}{So, you confessed. Tell me the reason why you should be left alive.}
{251}{}{(pulls out a weapon) I have six reasons, you fool. Listen carefully...}
{1251}{}{ (pulls out a weapon) I have six reasons, you fool. Listen carefully...}
{252}{}{Oh shit...}
{253}{}{Oh, don't...}
{254}{}{I'm a ranger too. And I'm on a mission. I have been ordered to infiltrate the ranks of the tinsmiths to find their weaknesses.}
{255}{}{Hmm. An unexpected meeting, comrade. It's good to see you. Well, in that case, I have no more questions. We will assume that this meeting did not take place.}
{256}{}{Sure. No one saw anything.}
{257}{}{Let me carry the remains. Tinsmiths deserve respect.}
{258}{}{I can't let you keep working for these bastards.}
{259}{}{[Next]}
{260}{}{You can hate them. But as a ranger, you have to respect a strong enemy. Let me take the remains to them.}
{261}{}{Hmm. These words make you think. Okay, do your dirty work, mercenary. And tell the tinsmiths that the wastelands will not always kneel before them.}
{1261}{}{Hmm. These words make you think. Okay, do your dirty work, mercenary. And tell the tinsmiths that the wastelands won't always be on their knees before them.}
{262}{}{Uh, yes, sir. As you say, sir.}
{263}{}{Just leave me alone.}
{264}{}{Sir, I have no complaints against you. I'm just fulfilling a peace contract.}
{265}{}{(mockery) Okay, do your dirty work, mercenary. And tell the tinsmiths that the wastelands will not always kneel before them.}
{1265}{}{(mockery) Okay, do your dirty work, mercenary. And tell the tinsmiths that the wastelands will not always kneel before them.}
{266}{}{I'm just fulfilling a contract. What problems?}
