{100}{}{You see the mainline driver.}
{101}{}{In front of you is a tanned man in road armor.}
{102}{}{Go your own way.}

{200}{}{Hey, you. What are you doing here?}
{201}{}{It seems that this land is nobody's land. What's the problem?}
{202}{}{Yes. Problems. At you. You're on our land and rummaging through our warehouse.}
{203}{}{But how was I supposed to know? You should at least hang a warning.}
{204}{}{What kind of road dust has darkened your eyes? I can't write... Wait, are you kidding me? A thousand quicksand miles, you can't get away with it.}

{210}{}{It's none of your business.}
{211}{}{No, this is MY warehouse and MY business.}
{212}{}{Really? I should have put a sign on the door.}
{213}{}{Bad luck, dude.}
{214}{}{You need to be done. We don't need any extra rumors.}
{215}{}{Sounds pretty serious...}
{216}{}{You should wash your eyes. And you look like you haven't washed in years.}

{220}{}{It seems that we are of the same clan. It makes no sense for us to share the same road, brother.}
{221}{}{Are you from the citadel? It's been a long time since I've been there. What news?}
{222}{}{Now it's just fine. The clan is protected, we have proved our right to independence.}
{223}{}{Yes, I heard. I should take a look there. Have a good trip, brother. Let the dust cover your tracks on the road.}
{1223}{}{Yes, I heard. I should take a look there. Have a good trip, Sister. Let the dust cover your tracks on the road.}
{224}{}{Have a good trip to you.}

{230}{}{I'm just a simple collector. Don't kill me, good man.}
{231}{}{So you're from around here? Probably a beginner. Everyone knows not to cross our path. Get out. If I see you here again, you're a dead man.}
{232}{}{As you say, sir...}
{233}{}{I'm just looking around. What's wrong with that?}
{234}{}{And the fact that we don't like them here. You're on our territory. I'll have to kill you to avoid unnecessary rumors.}
{235}{}{Yours? Come on...}