{100}{}{You see a guard.}
{101}{}{You see a water station guard. He doesn't know what to do with himself.}


{110}{}{What do you want?}
{111}{}{Better get out of our territory.}
{112}{}{If you need water, contact the merchant at the entrance.}
{113}{}{Talk to my boss.}
{114}{}{Do you know our mayor?}
{115}{}{We have the cleanest water.}
{116}{}{Just know that hands are cut off for stealing here.}
{117}{}{We are always on the alert.}
{118}{}{Guarding the station has become tedious.}
{119}{}{The mainline workers are hurting our business.}
{120}{}{It is better not to face the mainline drivers.}
