{100}{}{You see a water merchant.}
{101}{}{You see a strangely clean person. With his profession, he doesn't seem to need to do dirty work.}
{102}{}{You from the tinsmiths? Then you shouldn't scare people with this piece of junk.}
{103}{}{Our town is no place for highwaymen. Get outta here before I shoot you.}
{104}{}{This is the reward for your greed, you bastard.}
{105}{}{Remember these words? This is the reward you get for your greed.}
{106}{}{From this moment forward, the amount of goods the water merchant is ready to sell to you will be higher.}
{107}{}{I cannot speak to two people simultaneously.}

#First dialogue
{200}{}{(examines you, squinting, drying hands with a dirty towel) I don't remember you. First time here?}
{201}{}{Yes, you're right. What is this place?}
{202}{}{No, I was raised and born here. Got it?}
{1202}{}{No, I was raised and born here. Got it?}
{203}{}{Got it. But keep in mind that we don't like comedians here. These are not the times to be happy and satisfied with life.}
{204}{}{Oh, sorry. That was rather silly from my side. What is this place?}
{205}{}{Not hard to see. Relax, dude. And by the way, where did I end up?}
{1205}{}{Not hard to see. Relax, dude. And by the way, where did I end up?}
{206}{}{This is a water pumping station. We extract water from below the ground and sell it to the needy. And that is a bottler. You need water?}
{207}{}{No, I am searching for something else.}
{208}{}{I am too busy to chat. Don't interfere with my work.}
{209}{}{Bleh. So unfriendly...}
{210}{}{Yes, I need water immediately.}
{211}{}{Of course. Everybody needs water. But if you want to drink - then pay. There is nothing free here.}
{212}{}{Alright. I'll take a look when I need to refill my reserves. Bye.}
{213}{}{Oh, please, give some water to a tired Ranger. It will be kept in mind in the future.}
{214}{}{(grimaces face) Ranger... I don't remember the Rangers doing anything good for us. Still, the caravaneers have been talking a lot about you lately.}
{215}{}{[Continue]}
{216}{}{Fine. Here is a little bit of water. But do not ask for any more. We are a commercial organization here, not a charity.}
{217}{}{Thank you, mister.}
{218}{}{Water! Water! I'm dying of thirst...}
{219}{}{You really think I'll give you water after seeing that? What a pathetic parody of dehydration.}
{220}{}{I will remember this day. One day you will pay dearly for your greed.}
{221}{}{Get outta here.}
{222}{}{[Leave]}
{223}{}{Yes, it was a failed attempt. See you later.}
{224}{}{Will you really not spare a single cup of water to save a Ranger? I am not asking for much.}
{225}{}{Water! Water! I'm dying of thirst...}
{226}{}{Oh my god, how many miles have you walked under the sun? Alright, here, take some water. Don't you die on my watch.}
{227}{}{Thank you very much...}
{1227}{}{Thank you very much...}

{230}{}{Hey, not so fast. Show me your neck. Show it, now.}
{231}{}{Why?}
{232}{}{Sorry for being insistent. But after the fall of the Two Sun tinsmiths, many slaves have escaped. There's nothing good to expect from them. I simply want to make sure that I am speaking with a worthy person.}
{233}{}{You have bad manners.}
{234}{}{We don't need any conflict here.}
{235}{}{Alright, no signs of a collar. That's good... for both of us.}
{236}{}{Exactly. And under other circumstances it would have cost you dearly.}
{237}{}{No problem, I understand. Everything is fine.}
{238}{}{I am not going to do what someone else orders me to do.}
{239}{}{Look, let's just go our ways, okay? You can just pretend that I was never here...}
{240}{}{Well, well, well, here's our fleeing convict. So what exactly am I supposed to do with you?}
{241}{}{Nothing, I suppose. Let me just get out of this town, okay?}
{242}{}{Uh-uh. Get out of here. Leave this town and do not return.}
{243}{}{[Leave]}
{244}{}{Who the fuck are you to tell me what to do? Mind your own business.}
{245}{}{Well, well, well. If it isn't our little fleeing slave. You want to ruin my reputation, you piece of shit?}
{246}{}{What, again? I want to warn you right away - we raised prices on water.}
{247}{}{Why?}
{248}{}{We have to. There are no more tinsmiths, and because of that, the entire caravan trail is shrinking. We must now stock up on caps, otherwise trade will be completely pointless.}
{249}{}{Alright.}

#Repeated dialogue
{250}{}{You need water?}
{251}{}{Bye.}
{252}{}{Yes, of course.}
{253}{}{You know, I need to fill my water reserves.}
{254}{}{Yes, I need to fill my water reserves.}
{255}{}{Thank you. Use this water wisely.}
{256}{}{Goodbye.}

{257}{}{No, I need answers to questions.}
{258}{}{Look, I'm not going to answer any questions. I just sell water. You need answers - talk to my manager or someone else.}
{259}{}{Fine. Bye.}
{260}{}{I am pursuing a convoy with slaves...}
{261}{}{Wait, I'm looking for one tinsmith...}
{262}{}{I don't know anything about that. You need water or not?}
{263}{}{No.}
{264}{}{Who owns this establishment?}
{265}{}{John Sullivan. Right now, he is in the generator room, probably busy dealing with something broken.}
{266}{}{Alright.}
{267}{}{How are you holding up without your manager?}
{268}{}{Now I solve all the things he used to. In a way, he has helped me by "leaving" his position.}
{269}{}{Alright.}

{270}{}{Thank you for helping me deal with this loony. He has deserved such a fate for a long time. And he will serve as a warning to the rest.}
{271}{}{You're welcome.}
{272}{}{It was a difficult situation.}
{273}{}{Here, take some clean water. But do not spread word about this situation.}
{274}{}{Okay, I got it.}
{1274}{}{Okay, I got it.}
{275}{}{Don't pay attention to that loony. He has deserved such a fate for a long time. And he will serve as a warning to the rest.}
{276}{}{Yeah, looks like you have a madhouse here.}
{277}{}{I don't even know what to think of this.}
{278}{}{Just mind your own business. And don't spread word about this story, if you like not having problems.}
{279}{}{Thanks for helping me with that loony. It looked as if he was ready to attack me. Here, take some water. But do not spread word about this situation.}
{280}{}{Why did that settler attack you?}
{281}{}{Believe me, it's better to not know. In the past there was fighting between various clans around the pumping station. And this fool decided that the water should be shared.}
{282}{}{I doubt the situation is that simple.}
{283}{}{Yes. Some of his loved ones have died due to that fighting... But, as I said - it is none of your business. It is not even any of my business. It is the business of the past.}
{284}{}{That past almost ended your life.}
{285}{}{Really, there is no point in focusing on someone else's past mistakes. It is the time to grasp our future. Until next time.}

#Commodity Circulation
{300}{}{I need a very large amount of water.}
{301}{}{We don't give very large amounts of water to random people on the street.}
{302}{}{Fine, forget it.}
{303}{}{What stupid rule is that?}
{304}{}{We need to conserve water for regular clients. Especially in hot seasons.}
{305}{}{I also have my own business. Will you include me in your list of partners?}
{306}{}{What kind of a "business" can a regular person walking on the street have? It's clear to me that these bottles will be fine for you.}
{307}{}{What dumbass rule is that?!}
{308}{}{Fine, I won't buy anything from you from this moment on. Out of principles. Goodbye.}
{309}{}{Okay, okay, you know better.}
{310}{}{I am searching for new commercial connections. Let us realize a trial batch for a start.}
{311}{}{Hm. Alright. Let's see where this goes.}
{312}{}{You won't regret it, partner.}
{313}{}{Oh, darkness of Nuclear Fission! You would not refuse a man of Atom's request, would you?}
{314}{}{Ah, so you are from that religion? You pay well for fulfilling contracts. Alright, I'll consider you a trusted partner.}
{315}{}{Thank you, dear merchant.}
{316}{}{No worries, friend. Here, everyone's on the same team. Why all these formalities?}
{317}{}{I do not know you very well.}
{318}{}{Then it's just the time to take care of the local population. Isn't it?}
{319}{}{Heh-heh, of course. Anything for you, sir.}
{1319}{}{Heh-heh, of course. Anything for you, maam.}
{320}{}{Thank you, dear merchant.}
{321}{}{Khard will be most displeased with such behaviour toward me.}
{322}{}{So you are the one the caravaneers have been talking about? The one outsider who managed to gain the trust of the tinsmiths? If *they* trust you, I should certainly do so, too.}
{323}{}{You won't regret it, partner.}
{324}{}{I have managed to fix your filters. Am I not deserving of respect?}
{325}{}{So *you* did it? Well, good job. That certainly changes things.}
{326}{}{It can't be helped. Give me as much as you can.}

{330}{}{Hey, hello. They say you killed the leader of the highwaymen. Is that true?}
{1330}{}{Hey, hello. They say you killed the leader of the highwaymen. Is that true?}
{331}{}{Hey, hello. They say you managed to blow up the fuel tanks of the highwaymen. Is that true?}
{332}{}{Yes, a similar event did take place.}
{333}{}{Well, yeah. You got any problem with that?}
{334}{}{You're now our local hero, dammit. Thanks. If you need clean water, you can count on a good discount.}
{1334}{}{You're now our local heroine, dammit. Thanks. If you need clean water, you can count on a good discount.}
{335}{}{Thank you. That's very kind of you.}
{336}{}{That's how it should have been from the start.}
{337}{}{The water merchant has now lowered his prices for you two-fold.}