{100}{}{You see a guard.}
{101}{}{You see the pumping station's guard. He doesn't know how to pass the time.}

{110}{}{What do you want?}
{111}{}{You better get out of our territory.}
{112}{}{If you need water, head to the merchant near the entrance.}
{113}{}{Talk to my manager.}
{114}{}{Are you familiar with our mayor?}
{115}{}{The water here is clean. The cleanest you'll find out here, anyway.}
{116}{}{Just for your information, theft here is punished by cutting off hands.}
{117}{}{We are always vigilant.}
{118}{}{It's getting pretty tiresome guarding the pumping station.}
{119}{}{The highwaymen are hurting our business.}
{120}{}{It's better not to meet the highwaymen.}