{100}{}{You see John Sullivan.}
{101}{}{You see a person who inspires respect. It looks very clean and well-groomed.}
{102}{}{You're not going to wander around in this, are you?}
{103}{}{Are you tired of living? Get out of town, you damned highway guy.}

# Before repair
{200}{}{Hey, stranger. I don't like it when outsiders get into my territory.}
{1200}{}{Oh, lady, what a surprise to see a lady here. Although I usually don't like it when outsiders get in my territory.}
{201}{}{Is this your water pump? Do you own it?}
{202}{}{Exactly. I'm John Sullivan. And I own this whole station. Do you have business with me? If not, then go outside. I need to fix this filter, not chat with strangers.}
{203}{}{Sorry to bother you. I will leave immediately.}
{204}{}{I'm new here. Can I ask you a couple of questions about the city?}
{205}{}{Did I speak softly? I DON'T HAVE TIME to chat with you.}
{206}{}{Oh, then I'll leave you immediately.}
{207}{}{And who would I talk to about the city?}
{208}{}{Old Bustos, his mansion is down the road.}
{209}{}{Thank you. Goodbye.}
{210}{}{Why not give it to repair?}
{211}{}{Is there really no one else to fix it?}
{212}{}{The tinsmiths charge us three skins for any service. They know that water is a profitable business, but we can't give them everything. And apart from the tinkerers, no one can handle this kind of work. Only they have working machines and the necessary skills.}
{213}{}{Oh, I'm sorry, then I won't interfere.}
{214}{}{And you hope to fix it with your own hands?}
{215}{}{Sometimes it succeeds. This is one of the filters, it's just clogged with dirt... Or not.}
{216}{}{I can fix it.}
{217}{}{Really? If you fix the filter, I'll pay. Less than the tinsmiths, of course. But in the end, everyone will win.}
{218}{}{Wait for the results. It will take some time.}
{219}{}{Hmm, the technology is too complicated for me. I'm afraid I can't do it.}
{220}{}{You again? What is it this time?}
{221}{}{No, nothing.}
{222}{}{About the pump. Why not give it to repair?}
{223}{}{The filter is fine. Dirt and sand ruined some parts, but I managed to restore them.}
{224}{}{I love diligence in people. It's not a pity to pay for such work. Take it, there are 200 caps here.}
{225}{}{Thank you.}
{226}{}{That's too little.}
{227}{}{You've had enough. For a large sum, I wouldn't offer you this job at all.}
{228}{}{What a miser you are.}
{229}{}{Thanks anyway.}
{230}{}{This amount barely bottlecaps the cost of additional details.}
{231}{}{Then here are 50 more caps. And don't ask anymore.}
{232}{}{What a miser you are.}
{233}{}{That's enough, thank you.}

{234}{}{I'm looking for a tinker. Was there one here?}
{235}{}{Yes, I was. Silently inspected the station, discussed minor repairs, and went to the mayor. I haven't seen him since.}
{236}{}{Thanks, I'll go ask the mayor.}
{237}{}{I'm actually chasing slaves. They were being taken to Two-Sun.}
{238}{}{Well, go to Two-Sun. Why are you asking me? Our business is small - serve the caravan and let it go on all four sides. It's just business.}
{239}{}{Found excuses, right?}
{240}{}{That's a reasonable thought.}

{241}{}{What kind of disagreement did you have with the mayor?}
{242}{}{Time and children have changed the seasoned tyrant. He went limp and lost the right to tell me. Previously, because of him, I had to be content with the role of manager. It's my time to live beautifully.}
{243}{}{You will not be denied this. At least - now.}
{244}{}{Find someone else to chat with. I have neither the time nor the desire for this.}
{245}{}{Well, then I will not interfere.}

# After the repair
{250}{}{Now we can talk a little. What's on your mind?}
{251}{}{Nothing special. Later.}

{260}{}{Is all this a water station? Impressive.}
{261}{}{This station is more than a hundred years old. We only keep the old equipment in working order.}
{262}{}{Why do you need so much water?}
{263}{}{I have to go. See you later.}
{264}{}{There is another question.}
{265}{}{And why not? Everyone needs water. There is no life in the desert without it, as they say. For me, it is primarily a source of income. What's there, for the whole city, this is the main feeder.}
{266}{}{Aren't you holding the station in your hands?}
{267}{}{Water attracts caravans, and they give other types of earnings to residents. Besides, I have to pay to the treasury. The mayor needs caps too.}
{268}{}{And you are, of course, dissatisfied with this?}
{269}{}{Someone has to do the paperwork and negotiate. I'm better at hitting iron on iron. The only thing I would like from Alfred is for him to be tougher with clients. I'm tired of living from water to water.}
{270}{}{That's how it is. Let's go back a bit.}
{271}{}{Where did you get so much knowledge in pre-war technology?}
{272}{}{To tell the truth, the tinsmiths were engaged in the repair. I can still do something thanks to experience, but the rest of the guys only know which buttons to press.}
{273}{}{It's like you don't trust them?}
{274}{}{}
{275}{}{ Tinkerers? Why are you so honored?}
{276}{}{I had to give a lot for the reconstruction. But no one else would have done it. Besides, the tinsmiths themselves are interested in developing the trade route.}
{277}{}{Do you know that these technocrats have fallen from their own technologies?}
{278}{}{I heard. I don't care about the tinkerers. But what should we do when the station again requires serious repairs? I'm afraid to even imagine.}
{279}{}{Let's go back a bit.}
{280}{}{Who is in charge in the city?}
{281}{}{I'm in charge here.}
{282}{}{That's a twist. So it's you I need to talk to.}
{283}{}{The mayor and I are a couple. The mayor's name is Bustos, he lives in a mansion down the road.}
{284}{}{Tell me about the mayor. What kind of person is he?}
{285}{}{We've known each other for a long time and get along well. Although there are disagreements, for example, on the basis of his daughter. He lets her do too much.}
{286}{}{Does he have a daughter?}
{287}{}{Nice, but windy girl. I never understood why Bustos forgives her everything. I would have taken up the belt a long time ago in his place.}
{288}{}{I see. But let's go back a bit.}
{289}{}{How do you feel about the mayor?}
{290}{}{Holy simplicity. And you expect me to discuss my best friend with you? What's your business anyway?}
{291}{}{And really. I'm just passing through here.}
{292}{}{Is there a job in the city?}
{293}{}{Try asking the mayor. There is no more work for you at my station.}
{294}{}{I don't think so. There is no more work for you at this station.}
{295}{}{Okay. Let's change the subject.}
{296}{}{In that case, I'm stuck in this city for nothing. Goodbye.}
{297}{}{I can't offer anything other than fixing this damn filter. Do you understand technology?}
{298}{}{No, this is not my profile. Let's change the subject.}
{299}{}{Let me see, maybe I'll find a solution.}

{300}{}{I know about what happened at the merchant's. Never mind, poverty makes people crazy.}
{301}{}{Are you threatening me?}
{302}{}{If your mind is in order, you won't do anything stupid. Don't spread this story. We need to maintain a reputation.}
{303}{}{No problems. I didn't see or hear anything.}
{1303}{}{No problems. I didn't see or hear anything.}
{304}{}{Right answer. Maybe you and I will get along.}
{305}{}{Yes... of course.}
{306}{}{You have to pay for silence.}
{307}{}{Don't open your mouth, and you won't have any problems. It's simple.}
{308}{}{Ah, that's how it is...}
{309}{}{You have to pay for silence. You don't expect this story to bury itself, do you?}
{310}{}{Business approach. (counts down 10 caps) But watch your tongue. Otherwise, you'll be in big trouble in this city.}
{311}{}{Oh, I understand you perfectly...}
