{100}{}{You see a local resident.}
{101}{}{You see an emaciated settler. He looks very unfriendly.}

{110}{}{I don't care about you at all.}
{111}{}{He got what he deserved.}
{112}{}{*Ignores you*}
{113}{}{Damn it all.}
{114}{}{Sorry. I don't know what came over me.}

{120}{}{Again? I told you - no water without...}
{121}{}{Shut up. You TOOK the water from the residents.}
{122}{}{What are you talking about? You should wash your mouth with soap...}
{123}{}{Give me the water. Immediately.}
{124}{}{Get out of my hangar, you piece of dirt.}
{125}{}{Bastard, I'll smash your head!}
{126}{}{Hey, what are you up to? Take it away, you idiot!}
{127}{}{. . .}
{128}{}{ }

{200}{}{I swear, I'll smear this fat guy's head if he doesn't give me water!}
{201}{}{You wouldn't do that, would you?}
{202}{}{Don't get involved, stranger. You have no idea how much blood was shed for the sake of this water pump. They took it away from people! And now they are demanding payment from us. This is our water! Give me some water, you son of a bitch!}
{203}{}{I don't care. Do whatever you want.}
{204}{}{I won't let you swing a sledgehammer. Get out.}
{205}{}{Relax, it's not worth the sacrifice.}
{206}{}{Victims. What do you know about the victims? Crowds of people lay down on the ground for the sake of this cursed water. I have nothing left to lose. Say goodbye to life, bastard!}
{207}{}{Give me the sledgehammer. Immediately.}
{208}{}{Exactly. Kick his ass.}
{209}{}{Calm down, my friend, it's not worth such sacrifices.}
{210}{}{Sacrifices. What do you know about the victims? Crowds of people lay down on the ground for the sake of this cursed water. I have nothing left to lose...}
{211}{}{Okay, if you say so. Come on, kick his ass.}
{212}{}{It's all in the past. No need for new victims.}
{213}{}{(looks around in confusion, then looks at his sledgehammer) God... I think I've completely lost my head. Me... I need to collect my thoughts.}
{214}{}{That's for sure.}
