{100}{}{You see a water merchant.}
{101}{}{You see an unusually clean person. He doesn't have to get dirty with such work.}
{102}{}{Are you from the tinsmiths? Then don't scare people with this tin can.}
{103}{}{There is no place for highway workers in this city. Get out before I shoot you.}
{104}{}{This is the price for your greed, bitch.}
{105}{}{Do you remember your words? This is your payback for greed.}
{106}{}{From now on, the water merchant's product has been expanded for you.}
{107}{}{I can't talk to two at the same time.}

#The first dialog
{200}{}{(squints at you, rubbing his hands on a dirty towel) I don't remember you. For the first time in the city?}
{201}{}{Yes, it is. And what is this place?}
{202}{}{No, I was born and raised here. Got it?}
{1202}{}{No, I was born and raised here. Got it?}
{203}{}{Got it. But keep in mind that they don't like jokers here. These are not the times to enjoy life.}
{204}{}{Oh, I'm sorry. It was stupid of me. And what is this place?}
{205}{}{I can tell by you. Relax, man. By the way, where did I get to anyway?}
{1205}{}{I can tell by you. Relax, man. By the way, where did I get to anyway?}
{206}{}{This is a water station. We extract water from the ground and sell it to the needy. And this is the spill point. Do you need water?}
{207}{}{No, I'm looking for something else.}
{208}{}{I'm too busy to chat. Don't stop me from working.}
{209}{}{Ugh, how unfriendly...}
{210}{}{Yes, I urgently need water.}
{211}{}{Of course. Everyone needs water. But if you want to drink, pay. There is nothing free here.}
{212}{}{I see. I'll drop by when I need to restock. Bye.}
{213}{}{Please give some water to a tired ranger. It'll count for you.}
{214}{}{(making a face) Ranger... I don't remember what the Rangers did so well for us. However, the caravaneers have been talking a lot about you lately.}
{215}{}{[Next]}
{216}{}{Okay. Here's some water for you. But don't ask anymore. We are engaged in trade here, not charity.}
{217}{}{Thank you, dear.}
{218}{}{Water! Water! I'm dying of thirst...}
{219}{}{And you expect me to buy it? What a pathetic parody of dehydration.}
{220}{}{I will remember this day. And someday you will pay dearly for your greed.}
{221}{}{Get out of here.}
{222}{}{[Leave]}
{223}{}{Yes, it was a failed attempt. See you again.}
{224}{}{Would you really refuse a mug of life-saving water to a ranger? I'm not asking for much.}
{225}{}{Water! Water! I'm dying of thirst...}
{226}{}{My God, how many miles did you have to walk under the sun? Okay, take some water. Just don't die on my floor.}
{227}{}{Thank you very much...}
{1227}{}{Thank you very much...}

{230}{}{Hey, not so fast. Show me your neck. Come on, show me.}
{231}{}{Why is this?}
{232}{}{I'm sorry for being so insistent. But after the fall of the tinsmiths, many slaves escaped from Two-Sun. Nothing good can be expected from them. I just want to make sure I'm talking to a decent person.}
{233}{}{You have bad manners.}
{234}{}{We don't need conflicts.}
{235}{}{So, there are no traces of the collar. It's good... for both of us.}
{236}{}{Exactly. Under other circumstances, it would have cost you dearly.}
{237}{}{Nothing, I understand. It's fine.}
{238}{}{I'm not going to curry favor with you.}
{239}{}{Look, let's just break up, okay? Consider that I'm not here...}
{240}{}{Well, well, and here's our escaped convict. And what should I do with you?}
{241}{}{Nothing, I guess. Can I just leave?}
{242}{}{Yeah. Go. Get out of town and don't come back.}
{243}{}{[Leave]}
{244}{}{Who are you to tell me? Mind your own business.}
{245}{}{Well, well. Yes, this is our runaway slave. You want to ruin my reputation, you piece of shit?}
{246}{}{What, again? I want to warn you right away - we have raised water prices.}
{247}{}{Why?}
{248}{}{I have to get out of it. There are no more tinsmiths, and with them, the entire caravan trail is shrinking. We must stock up on caps, otherwise, trading will be meaningless at all.}
{249}{}{I see.}

#Repeat dialog
{250}{}{Do you need water?}
{251}{}{Bye.}
{252}{}{Yes, of course.}
{253}{}{You know, I just need to replenish my water supplies.}
{254}{}{Yes, I need to replenish my water supplies.}
{255}{}{Thank you. Use this water wisely.}
{256}{}{Bye.}

{257}{}{No, I need answers to questions.}
{258}{}{Look, I'm not going to answer any questions. I only sell water. If you need answers, talk to my boss or someone else.}
{259}{}{Okay. Bye.}
{260}{}{I'm chasing a slave convoy...}
{261}{}{Wait, I'm looking for a tinker...}
{262}{}{I don't know anything. Do you need water or not?}
{263}{}{No.}
{264}{}{Who owns this company?}
{265}{}{John Sullivan. He's in the generator room right now, tinkering with another breakdown.}
{266}{}{I see.}
{267}{}{How do you cope without your boss?}
{268}{}{Now I solve all the issues in his place. To some extent, he did me a favor by "leaving" his post.}
{269}{}{I see.}

{270}{}{Thanks for the help with this half-wit. He deserved such a fate for a long time. At the same time, it will serve as an example to others.}
{271}{}{You're welcome.}
{272}{}{It was a difficult situation.}
{273}{}{Here, take some clean water. But don't spread about this story.}
{274}{}{Okay, I get you.}
{1274}{}{Okay, I get you.}
{275}{}{Don't pay any attention to this half-wit. He deserved such a fate for a long time. At the same time, it will serve as an example to others.}
{276}{}{Yes, you have a madhouse here.}
{277}{}{I don't even know what to think about it.}
{278}{}{Just mind your own business. And don't spread this story if you don't want problems.}
{279}{}{Thanks for the help with this half-wit. It already seemed to me that he was ready to pounce on me. Here, take some water. And don't spread about this story.}
{280}{}{Why did this settler attack you?}
{281}{}{Believe me, it's better for you not to know. In the past, there was a struggle between different clans around the station. And this fool decided that the water should be shared.}
{282}{}{I doubt it's just that.}
{283}{}{Yes. Someone among his loved ones died in that struggle... But as I said before, it's none of your business. And not even mine. This is a thing of the past.}
{284}{}{That past almost ruined your life. And now I'll leave you with this thought.}
{285}{}{Indeed, it makes no sense to stir up someone's past mistakes. It's time to tackle our future. See you.}

#Turnover
{300}{}{I need a really big batch of water.}
{301}{}{We don't trade in large batches with just anyone.}
{302}{}{Then forget it.}
{303}{}{What's the ridiculous rule?}
{304}{}{It is necessary to save water for permanent buyers. Especially in the hot season.}
{305}{}{I also run my own business. Will you put me on the list of partners?}
{306}{}{What the hell is the "business" of a person walking by? Obviously, these bottles are enough for you.}
{307}{}{What is this stupid rule?}
{308}{}{Well, now I won't buy anything at all. On principle. Bye.}
{309}{}{Okay, okay, you know better.}
{310}{}{I'm looking for new trade connections. Let's implement a trial batch to begin with.}
{311}{}{Hmm. Good. Let's see what happens.}
{312}{}{You won't regret it, partner.}
{313}{}{Oh, the darkness of Nuclear Fission! You won't refuse a clergyman his request, will you?}
{314}{}{Oh, so you're from that church? Your people pay well on contracts. So be it, we will assume that you are also included in the list of trusted persons.}
{315}{}{Thank you, my dear.}
{316}{}{Come on, buddy. Everyone is their own here. Why these formalities?}
{317}{}{I don't know you that well.}
{318}{}{Then it's time to take care of the local population. Don't you find it?}
{319}{}{Hehe, of course. Anything for you, sir.}
{1319}{}{Hehe, of course. Anything for you, ma'am.}
{320}{}{Thank you, my dear.}
{321}{}{You're selling water to Two-Sun. Hard won't like this attitude towards me.}
{322}{}{Is that what the caravaneers are saying about you? The only outsider who has taken root among the tinsmiths. Yes, you're worth dealing with.}
{323}{}{You won't regret it, partner.}
{324}{}{I managed to fix your filters. Don't I deserve better treatment?}
{325}{}{So this is your merit? Well done. This changes the case.}
{326}{}{There's nothing to be done. Give as much as you can.}

{330}{}{Hey, hello. They say you killed the leader of the highway workers. Is it true?}
{1330}{}{Hey, hello. They say you killed the leader of the highway workers. Is it true?}
{331}{}{Hey, hello. They say you managed to blow up the tanks of the mainline workers. Is it true?}
{332}{}{Yes, there was a case.}
{333}{}{Well yes. Any problems?}
{334}{}{Damn it, you're our hero now. Thank you. If you need clean water, you can count on a good discount.}
{1334}{}{Damn it, you're our heroine now. Thank you. If you need clean water, you can count on a good discount.}
{335}{}{Thank you, that's very kind of you.}
{336}{}{That's where we should have started.}
{337}{}{The water merchant has halved his prices for you.}
