{100}{}{You see a road warrior.}
{101}{}{You see one of the highwaymen.}
{102}{}{Good luck.}

{200}{}{Hey, thanks for the help, bro. These people, they've been chasing me for several days in the roadless. But why'd you save me?}
{1200}{}{Hey, thanks for the help, girl. These people, they've been chasing me for several days in the roadless. But why'd you save me?}
{201}{}{I always help people in need.}
{202}{}{Nonsense! I don't believe you. There's no such thing as "honor". Everyone is out only for themselves. But if you don't mind taking the hit for someone else - I'm using the opportunity. Oh, and by the way, do you want to get acquainted with my gang? The boss would be interested in people like you.}
{203}{}{What gang?}
{204}{}{Blue Shields. They call us that because of these road signs. You really haven't heard of us? Then you should visit our base. It's in that direction. I'll tell them to let you see Ben.}
{205}{}{Alright. Good luck.}
{206}{}{I want to join your gang.}
{207}{}{Ha! Not the best idea. Only people who settle down in it are those who have nothing at all to lose in the "civilized world". In any case, it's Ben, our leader, who personally deals with that. You should talk to him.}
{208}{}{Alright. Will do exactly that.}
{209}{}{Base's in that direction. I'll tell them to let you see Ben. Good luck.}
{210}{}{Alright. Good luck to you too.}
{211}{}{Hey, thanks for the help, bro. These people, they've been chasing me for several days in the roadless.}
{1211}{}{Hey, thanks for the help, girl. These people, they've been chasing me for several days in the roadless.}
{212}{}{What did they want from you?}
{213}{}{They were bounty hunters. People in Casa Grande and Phoenix sometimes hire them to drive our gang off the highways. But these are *our* highways! They won't succeed.}
{214}{}{I see.}
{215}{}{I'll tell this story to Ben and the others. See you at the base.}
{216}{}{Good luck.}
