{100}{}{Before you is a warrior of the road.}
{101}{}{This is one of the highway robbers.}
{102}{}{Good luck on the way.}

{200}{}{Hey, thanks for the help, bro. These cops chased me for several days off-road. But why did you save me?}
{1200}{}{Hey, thanks for the help, girlfriend. These cops chased me for several days off-road. But why did you save me?}
{201}{}{I always help people in need.}
{202}{}{Nonsense! I don't believe in any nobility. Everyone cares only about their own skin. But if you don't mind putting yourself under attack for the sake of an outsider, it's only better for me. By the way, do you want to meet my gang? The boss will probably be interested in you.}
{203}{}{What kind of gang?}
{204}{}{Blue Shields. We are so called because of these road signs. Don't you know? Then look at our base, it's over there. I'll tell them to let you through to Ben.}
{205}{}{OK. Good luck on the road.}
{206}{}{I want to join your gang.}
{207}{}{Ha! Not the best idea. Only those who really have nothing to lose in the "civilized world" take root here. In any case, this is handled personally by Ben, our leader. You need to talk to him.}
{208}{}{Okay. I will do so.}
{209}{}{The base is over there. I'll tell them to let you through to Ben. Have a good trip.}
{210}{}{Good. Good luck on the road.}
{211}{}{Hey, thanks for the help, bro. These cops chased me for several days off-road.}
{1211}{}{Hey, thanks for the help, girlfriend. These cops chased me off-road for several days.}
{212}{}{What did they want from you?}
{213}{}{They were bounty hunters. They are sometimes hired in Casa Grande or Phoenix to drive our gang off the tracks. But these are our tracks! They won't succeed.}
{214}{}{Clear.}
{215}{}{I'll tell Ben and the others this story. See you at the base.}
{216}{}{Have a good trip.}