{100}{}{This is Henry Beamis.}
{101}{}{This is Henry Beamis. Part of a ruined landscape. A chip. A fragment of what humanity has done to itself.}
{102}{}{Well, I will certainly be forgiven.}
{103}{}{*Hmm* I had an eternity to read. But I lost my glasses. It's not fair. It's not fair at all.}
{104}{}{Ah, books! I have enough of them for the rest of my life.}
{105}{}{Ah! I see! I can read! You save me from eternal longing... Here, take it, read it with me, it's a very interesting book.}
{106}{}{I need reading glasses. Do you understand?}

{110}{}{Nothing, uh, it's okay.}
{111}{}{I didn't have the opportunity to live in solitude.}
{112}{}{What am I going to do now?}
{113}{}{*Whimper*}
{114}{}{*Crying*}
{115}{}{Yes, uh, I'm lucky... Very lucky... Help! Somebody!}
{116}{}{Am I all alone here?}
{117}{}{If there wasn't this loneliness...}
{118}{}{If it were possible to DO something...}
{119}{}{To do... we have to do something...}
{120}{}{It's not fair. It's not fair at all.}

{150}{}{Oh, how many books are there!}
{151}{}{The collected works of Dickens!}
{152}{}{The Collected Works of George Bernard Shaw!}
{153}{}{Poems by Browning, Shelley and Keats!}
{154}{}{"David Copperfield", "The Great Gatsby", "Uncle Tom's Cabin"...}
{155}{}{Books... Great treasures of the world...}
{156}{}{Books, books, books... ah!}
{157}{}{January... february... March... this year... next year...}
{158}{}{The main thing is that I now have all my time.}
{159}{}{*Happy cooing*}
{160}{}{I was very lucky... really...}
{161}{}{Everything I wanted is here.}
{162}{}{Now I will have something to occupy my thoughts.}