{100}{}{You see a bankrupt person.}
{101}{}{You see a farmer who's mad at the whole world.}

{110}{}{Die, you sons of bitches!}
{111}{}{I won't leave it like this!}
{112}{}{I'll take my land back with force!}
{113}{}{They took my farm, I'm taking everything else.}
{114}{}{Those fucking Rangers are going to pay for everything!}
{115}{}{You think I'm insane? No-o! I want justice.}
{116}{}{Why the heck should I pay someone for land?}
{117}{}{I don't care about those laws and rules anymore!}
{118}{}{The Rangers put me on trial, I'll do the same to them.}
{119}{}{You're gonna pay for everything!}
