{100}{}{This is Don Reavis.}
{101}{}{You see a man with a beautiful black beard and a noble bearing.}

{200}{}{Thanks for helping me deal with the rebels, friend. Some day a severe punishment will overtake them.}
{1200}{}{Thank you for helping me deal with the rebels, lady. Some day a severe punishment will overtake them.}
{201}{}{Who are you anyway?}
{202}{}{I always lend a helping hand to those in need. But who are you and how have you angered these peasants?}
{203}{}{This is Don James Reavis. I am the owner of the entire territory of the state of Arizona. A state that was barbarously taken from my ancestors.}
{204}{}{Are you serious?}
{205}{}{How can you prove it?}
{206}{}{I can show documents and an old tombstone with the names of my ancestors, but will it convince anyone? Therefore, I am not going to prove anything, but I will simply return the lands to the rightful heir. I am the Baron of Arizona. That should be enough.}
{207}{}{And do you seriously think that you can bend the free peasants before you?}
{208}{}{And so it will be. As you can see, many have already done it. Those who resist to the end will face a shameful fate. Bend down and you. If you take the oath, I will not forget your loyalty for the rest of my life.}
{209}{}{I'm sorry, Baron, but I have obligations only to my native house.}
{210}{}{Well, for your help, I recognize the independence of your house. Go in peace, friend.}
{211}{}{Goodbye.}
{212}{}{You're just a fraud. I shouldn't have broken up this fight.}
{213}{}{Hurtful words for the person to whom I owe my life. Well, we're probably not on our way. But if we ever cross paths again, I hope for your prudence.}
{214}{}{It would be better if the peasants lynched you. Goodbye.}
{215}{}{I will finish what the peasants could not finish. Die, you bastard!}
{216}{}{I will take the oath, O Don Reavis, Baron of beautiful Arizona.}
{217}{}{Did you believe that? Idiot, I'd rather kill you than take your side!}
{218}{}{[Other options]}

{220}{}{I am glad to welcome you into my ranks, noble man. Kneel down and say the words of the oath...}
{221}{}{I swear to protect you and your possessions. [+1 Strength]}
{222}{}{I swear to be your loyal subject. [+1 Perception]}
{1222}{}{I swear to be your loyal subject. [+1 Perception]}
{223}{}{I swear never to leave you in trouble. [+1 Stamina]}
{224}{}{I swear to always be your friend, Risis. [+1 Charisma]}
{225}{}{I swear to be your loyal supporter. [+1 Intelligence]}
{1225}{}{I swear to be your loyal supporter. [+1 Intelligence]}
{226}{}{I swear to find a better way for your Arizona. [+1 Dexterity]}
{227}{}{I swear to bring good luck to you and your possessions. [+1 Luck]}
{228}{}{Stand up, my friend. From now on, your seal is equal to my seal. Protect Arizona, rule it on my behalf.}
{229}{}{My compliments, Baron Reavis.}

{230}{}{God bless you.}
{231}{}{Goodbye.}