{100}{}{You are completely bankrupt.}
{101}{}{You see a farmer angry at the whole world.}

{110}{}{Die, you bastards!}
{111}{}{I won't leave it so easy!}
{112}{}{I will take back my land by force!}
{113}{}{My farm was taken away from me, and I will take everything else.}
{114}{}{The Rangers will fucking pay for everything!}
{115}{}{Do you think I'm going crazy? No, I just want justice.}
{116}{}{Why should I pay someone for land?}
{117}{}{Now I don't care about laws and regulations!}
{118}{}{The Rangers have tried me, and I will try them.}
{119}{}{You will all pay!}