{100}{}{You see Don Rivis.}
{101}{}{You see a man with a handsome black beard and noble posture.}

{200}{}{Thank you for helping me deal with those rebels, friend. Someday, they will be severely punished.}
{1200}{}{Thank you for helping me deal with those rebels, lady. Someday, they will be severely punished.}
{201}{}{Who the hell are you?}
{202}{}{I always extend a helping hand to those in need. But I want to know who you are. And why did you anger those peasants?}
{203}{}{Before you stands Don James Rivis. I am the owner of the entire state of Arizona. A state that was savagely taken away from my ancestors.}
{204}{}{You serious?}
{205}{}{How can you prove it?}
{206}{}{Oh, I could show documents and the old tombstone with the names of my ancestors, but do you really think that will convince anyone? So, I do not intend to show anything. I will simply return the land to their rightful heir. I am the baron of Arizona. That should be enough.}
{207}{}{And you really think you can convince those peasants to serve you?}
{208}{}{Yes, I do. As you can see, many have done so already. A most ignominious lot awaits those that would resist me to the end. Why don't you kneel before me as well? If you do, I will remember your loyalty until my death.}
{209}{}{I'm sorry, baron, but my commitment is only to my home.}
{210}{}{Well. For your assistance, I recognize your home's independence. Go in peace, friend.}
{211}{}{Farewell.}
{212}{}{You're just a con man. I shouldn't have interfered in this fight.}
{213}{}{Hurtful words for a person I owe my life to. Well, our ways almost certainly separate here. But if we ever meet again, I hope you will act with more wisdom.}
{214}{}{Those peasants should've lynched you. Bye.}
{215}{}{I'll finish what the peasants couldn't. Die, bastard!}
{216}{}{I kneel before you, oh Don Rivis, baron of fair Arizona.}
{217}{}{What, you believed me? I would never join an idiot like you! I'd rather kill you.}
{218}{}{[Other variants]}

{220}{}{I am happy to accept you in my ranks, honorable friend. Bend your knee and say your oath...}
{221}{}{I swear to protect you and your holdings. [+1 Strength]}
{222}{}{I swear I will be your faithful subject. [+1 Perception]}
{1222}{}{I swear I will be your faithful subject. [+1 Perception]}
{223}{}{I swear I will never abandon you in times of trouble. [+1 Endurance]}
{224}{}{I swear I will always remain your friend, Rivis. [+1 Charisma]}
{225}{}{I swear I will always advocate for you. [+1 Intelligence]}
{1225}{}{I swear I will always advocate for you. [+1 Intelligence]}
{226}{}{I swear I will find the best path for your Arizona. [+1 Agility]}
{227}{}{I swear I will bring fortune to you and your holdings. [+1 Luck]}
{228}{}{Stand up, my friend. From this moment on, your seal is equal to my seal. Defend Arizona, and rule it on my behalf.}
{229}{}{My regards, baron Rivis.}

{230}{}{God bless you.}
{231}{}{Farewell.}

