{100}{}{You see a settler.}
{101}{}{You see of the residents of the cafe.}
{102}{}{Get out!}

{110}{}{Are you leaving already?}
{111}{}{Don't hurry to leave, the pies will be baked soon.}
{112}{}{Would you like some coffee?}
{113}{}{Ah, your sunken cheeks hint at a lack of protein.}
{114}{}{You just have to try our dishes.}
{115}{}{Please make yourself comfortable.}
{116}{}{We always welcome travelers.}
{117}{}{Do you want to relax a little?}
{118}{}{I can do a relaxing massage.}
{119}{}{You look... attractive.}
{120}{}{Surely you're thirsty from the road.}
{121}{}{Oh, we always welcome new faces}
{122}{}{Come on, sit down, put all this nonsense aside.}
{123}{}{Here you can completely relax.}
{124}{}{Don't worry, it's completely safe here.}
