{100}{}{You see a settler.}
{101}{}{You see one of the residents of the cafe.}
{102}{}{Leave before I change my mind.}
{103}{}{Ugh, this family definitely has something to hide.}
{104}{}{He looks delicious. Honey, cut off my thigh.}
{105}{}{The filth in this place is over.}
{106}{}{You should have been nicer to me.}

{200}{}{Ah, a traveler straight from the wasteland! It's nice to see a new face in these sparsely populated areas. Where are you from?}
{201}{}{From a small village far from here.}
{202}{}{Better not ask me about it. Is that clear?}
{203}{}{Okay, whatever you say. And we have been living here for many years. Do you want to spend the night? Please - we have a lot of free space. Besides, the pies will be ready soon. You should stay, believe me, they're just great.}
{204}{}{Uh, I'll think about your offer.}

{210}{}{How can we help?}
{211}{}{I'm just looking around.}
{212}{}{Can I look around here?}
{213}{}{Sure. But don't go into the back room. This is our private property.}
{214}{}{Of course, no problem.}
{215}{}{Sounds like something not very good. I will keep that in mind.}
{216}{}{How do you survive in the middle of a scorched desert?}
{217}{}{If you want to live, you'll find ways. We feed on lizards, scorpions, and all sorts of small animals. We collect water from the night condensate. It happens that rare travelers leave some things like cartridges. This is quite enough for us in such a modest company.}
{218}{}{Do you live here alone?}
{219}{}{Well yes. Our parents used to live with us, but the wasteland took them away from us. Occasionally travelers and caravaneers stop here.}
{220}{}{You know, it's hard to find genuine friendliness nowadays.}
{221}{}{Oh, yes, I understand. People in the villages do not trust each other, there is not enough food and water for everyone. Don't worry, there are other mores here. We do not condemn anyone and we do not want to deceive anyone.}
{222}{}{This cafe looks very old. How long have you lived here?}
{223}{}{We got this cafe from our parents. And to them - from their parents. And so many generations ago. This is a very old place.}
{224}{}{What is so important in your back room?}
{225}{}{Only personal belongings and a place to sleep. Don't get me wrong, this is our personal space. None of the outsiders can go in there. And this is the only thing we ask of outsiders.}
{226}{}{Do you have anything to exchange?}
{227}{}{If you have something useful, then I don't mind exchanging. Look around, what do you need?}
{228}{}{Do you accept bottle caps?}
{229}{}{What are you talking about? Why do I need caps? Leave this nonsense. I would never believe that people in cities are exchanging for these useless things. We always threw them away like garbage.}
{230}{}{Do you mind chatting about something else?}
{231}{}{Something else?}
{232}{}{Nothing, I'm going to rest from the road.}

{250}{}{Well, well. I should have shot you right away. I always told my sister not to talk too much with strangers.}
{251}{}{Remember when I said I didn't believe in pleasantries on the wastelands? And it was not in vain.}
{1251}{}{Remember when I said I didn't believe in pleasantries on the wastelands? And it was not in vain.}
{252}{}{What do you understand? We live in the middle of the desert, where there is nothing - no crops, no animals, no settlements. Rare travelers are the only way to survive in such difficult conditions.}
{253}{}{So why not get out of this hell? Somewhere in the distance, there are whole cities...}
{254}{}{Nonsense! You all tell these stories, but they are all different. I don't trust outsiders anymore. To leave this cafe, where you have lived all your life, for the sake of dubious stories is certain death. And we want to live.}
{255}{}{So you're just a fool.}
{256}{}{Yes... perhaps. But this fool has outsmarted the stranger for the hundredth time. And he will survive. But you don't.}
{257}{}{Hey...}
{258}{}{Exactly. You had a chance before. And now it's too late, you fool...}
{1258}{}{Exactly. You had a chance before. And now it's too late, stupid...}
{259}{}{So, how do you survive in this barren desert - kill travelers and make a kebab out of them?}
{260}{}{So this conversation will have only one outcome. Your death.}
{261}{}{Stop talking. I will rid the wasteland of such parasites as your family.}
{262}{}{Wait, you're making a big mistake...}
{263}{}{Wait. I'm telling the truth. There are big cities in the wastelands. There's plenty of room for your family. Living in the desert, you only condemn yourself to a slow death.}
{264}{}{Hmm... It's strange that outsiders talk about cities so often. Maybe it's true... Do you know where we can go? Show me. I want to know.}
{265}{}{OK, but after that you'll let me go. Okay?}
{266}{}{To hell with it. People like you have no place in a civilized society.}
{267}{}{Eh? Who is it we have here? A thief. I've been told that thieves have their hands cut off in cities. I'll do the same. It's going to be very, very painful.}
{268}{}{Go to hell, you filthy cannibal.}
