{100}{}{You see a settler.}
{101}{}{You see one of the cafe's inhabitants.}
{102}{}{Get out!}

{110}{}{Already leaving?}
{111}{}{I think you should stay. We're just about to finish making the pies.}
{112}{}{Would you like some coffee?}
{113}{}{Ah, your sunken cheeks are a clear sign of protein deficiency.}
{114}{}{You just *have* to try our food.}
{115}{}{Please, make yourself comfortable.}
{116}{}{We're always happy to meet wanderers.}
{117}{}{Want to rest?}
{118}{}{I can give you a highly relaxing massage.}
{119}{}{You look so... attractive.}
{120}{}{All that walking must be giving you terrible thirst.}
{121}{}{O-oh, we're always happy to see new faces around here.}
{122}{}{Sit down, relax and put aside all your worries.}
{123}{}{You can relax here. Trust me.}
{124}{}{Don't worry, this place is perfectly safe.}
