{100}{}{You see an escapee.}
{101}{}{You see a man in a business suit. He is bleeding heavily.}
{102}{}{Please help me... I have gold... so much gold...}

{200}{}{(A man in a business suit is walking in your direction; blood is pouring out of his head, and he can barely stand.)}
{201}{}{You don't look good, pardner.}
{202}{}{Oh god, you're injured!}
{203}{}{P-please... help... (falls at your feet, clinging to your clothes on his knees with the last of his strength) I'll give you everything... I have gold... (falls to the ground) So... much... gold...}
{204}{}{Hey, man. Gold stopped being valuable a long time ago. Do you hear me?}
{205}{}{Everything is going to be okay, hang on...}
