{100}{}{Here is a fugitive.}
{101}{}{You see a man in a business suit. He's bleeding out.}
{102}{}{Please save me... I have gold... a lot of gold...}

{200}{}{(A man in a business suit is walking to meet you; his head is bleeding, and he can barely stand on his feet.)}
{201}{}{You look like shit, buddy.}
{202}{}{Oh my God, you're hurt!}
{203}{}{P-please... help... (falls at your feet, clinging to your clothes with the last of his strength) I'll give it all away... I have gold... (falls to the ground) A lot... gold...}
{204}{}{Hey, man. Gold has long since depreciated. Do you hear?}
{205}{}{Everything will be fine, hold on...}