{100}{}{You see Harvey.}

{110}{}{Harvey hates humans!}
{111}{}{Fight, worthless insect!}
{112}{}{Humans hate those like me.}
{113}{}{Why can't you leave us alone?!}
{114}{}{Humans follow us everywhere!}
{115}{}{Humans always shot us first!}
{116}{}{Master, give me the strength to defend this place from the normies!}
{117}{}{Levi didn't want to see humans in our city.}
{118}{}{Harvey just defends the city from normies!}
{119}{}{Harvey's good. Harvey works hard for Levi.}

{120}{}{Levi said to defend the city from humans.}
{121}{}{Sorry. You can't stay here.}
{122}{}{Harvey remembers who helped Levi. Harvey grateful.}
{123}{}{Harvey's good. Harvey defends city from humans.}
{124}{}{Do you honor Levi like I do?}
{125}{}{Do you honor the Master?}
{126}{}{I miss the Master...}
{127}{}{Harvey!}
{128}{}{}
{129}{}{}
