{100}{}{in front of you Õarvi.}

{110}{}{ÕArvi hates people!}
{111}{}{Come on, you little bug!}
{112}{}{People don't like people like you.}
{113}{}{Why won't you leave us alone?!}
{114}{}{People are chasing us everywhere!}
{115}{}{People always shoot at us first!}
{116}{}{Ñcreator, give me the strength to protect this place from the normies!}
{117}{}{Levi did not want to see people in our city.}
{118}{}{Õarvi just protects the city from the normies!}
{119}{}{Õarvi is good. ÕArvi triesÿfor the sake of Leviÿ.}

{120}{}{Levi instructed to guard the city from people.}
{121}{}{"Sorry, but you can't stay here."}
{122}{}{Õarvi remembers who helped Levi. Õarvi is grateful.}
{123}{}{Õarvi is good. arvi protects the city from people.}
{124}{}{ÒDo you read meÿ as well as ÿ?}
{125}{}{Ò Do you read the creator?}
{126}{}{I miss the creator...}
{127}{}{Õarvi!}
{128}{}{}
{129}{}{}