{100}{}{Here is Lamont.}
{101}{}{You see an emaciated man. His gaze seems empty.}
{102}{}{Run before it's too late. You still have a chance...}

{200}{}{Who's here? Answer me! God, I hope you're not a figment of my imagination... N-don't touch the weeds! They are dangerous!}
{201}{}{Okay, calm down.}
{202}{}{I'm Lamont. I have a farm in the canyon. Well, it used to be a farm.}
{203}{}{Why? Are there weeds there too?}
{204}{}{They are worse than mantises... (looks around in panic) Weeds! They're everywhere! Everywhere!}
{205}{}{Come on, it's just a tumbleweed...}

{210}{}{I have a farm in the canyon.}
{211}{}{Yes, you said that.}
{212}{}{Did I tell you there's nothing left of her? At least - nothing good. It's better not to show up there. But there's nowhere else to go.}
{213}{}{Wait a minute. If there are so many problems from these weeds, why did you stay?}
{214}{}{Why... Well, out of curiosity. They don't behave like unusual tumbleweeds. So I watched them. But I did it for too long.}
{215}{}{So you can't leave here anymore?}
{216}{}{Neither to me, nor to you. No one will leave.}
{217}{}{What are you...}

{220}{}{There is no way out. That's all. THEY won't give.}
{221}{}{Who are these "they"?}
{222}{}{As far as I remember, this invasion began a couple of weeks ago, when that "thing" landed on earth.}
{223}{}{Thing?}
{224}{}{I don't know. Probably a meteorite. I saw a flash in the sky. Then I heard a crash.}
{225}{}{Have you tried to find out what it was?}
{226}{}{The next day I went to see. But I didn't even find a hole in the ground. And then these events began.}
{227}{}{Go on.}
{228}{}{At first I didn't pay attention. It just seemed like the tumbleweed was bigger than usual. And then they began to behave as if they were alive. They wouldn't even let me leave the canyon-they blocked the road or clung to my legs when I tried to leave. I haven't tried since...}
{229}{}{Hmm.}
{230}{}{Go away! You still have a chance to get out of here. Run while you can!}
{231}{}{Oh...}