{100}{}{You see a robot administrator.}

{200}{}{Welcome to the world of the Wild West and adventure!}
{201}{}{Welcome to Legend City!}
{202}{}{Welcome to Arizona's largest amusement park!}
{203}{}{Wow, that sounds great.}
{204}{}{Don't get in the way, bucket of nuts.}

{210}{}{How can I help, se-er?}
{1210}{}{How can I help, me-em?}
{211}{}{Nothing else.}
{212}{}{That's all I was interested in. Now let me have some fun.}

{220}{}{What is this place?}
{221}{}{You are in Legend City - this is the largest amusement park in all of Arizona!}
{222}{}{Tell me, what can I do here?}
{223}{}{Attractions, virtual play area, shooting gallery, cafeteria - what are you interested in?}
{224}{}{Perhaps it would be better if I examined everything myself. Free.}
{225}{}{But what kind of place is this?}
{226}{}{I'm interested in rides.}
{227}{}{I'm sorry, sir, but the rides are currently closed for technical reasons. We apologize.}
{1227}{}{I'm sorry, ma'am, but the rides are currently closed for technical reasons. We apologize.}
{228}{}{Can I shoot at the shooting range?}
{229}{}{I'm sorry, sir, but the shooting range has run out of ammunition.}
{1229}{}{I'm sorry, ma'am, but the shooting range has run out of ammunition.}
{230}{}{Is the cafeteria open?}
{231}{}{We apologize, sir, but the cafe is temporarily out of service.}
{1231}{}{We apologize, ma'am, but the cafe is temporarily out of service.}
{232}{}{Does anything work here?}
{233}{}{You can try virtual games in our new game room. Enjoy your stay, sir.}
{1233}{}{You can try virtual games in our new game room. Enjoy your stay, ma-uh.}
{234}{}{Okay, let's look at it in action.}
{235}{}{Then stand aside, piece of iron, big victories are waiting for me!}
{236}{}{Does the cafeteria even work?}