{100}{}{You see Lamont.}
{101}{}{You see an emaciated man. His eyes look empty.}
{102}{}{Run while you still can. You still have a chance...}

{200}{}{Who's there? Respond! God, I hope you're not just a figment of my imagination... D-don't touch the weeds! They're dangerous!}
{201}{}{It's okay, calm down.}
{202}{}{My name's Lamont. I have a farm in the canyon. Well, it used to be a farm.}
{203}{}{Why? There are weeds there, too?}
{204}{}{They're worse than praying mantises... (looks back in panic) The weeds! They're everywhere! Everywhere!}
{205}{}{Calm down, it's just tumbleweeds...}

{210}{}{I have a farm in the canyon.}
{211}{}{Yes, you said that already.}
{212}{}{Did I tell you that nothing was left of it? Nothing good, anyway. It's best not to show up there. But there's nowhere else to go.}
{213}{}{Wait a minute. If these weeds are so bad, why did you stay?}
{214}{}{Why... Well, I was curious. They don't behave like regular tumbleweeds, you know. That's why I've been watching them. But it turned out that I've been watching for too long.}
{215}{}{So, you can't get out?}
{216}{}{Not me, not you. No one can leave anymore.}
{217}{}{What the heck are you talking about...}

{220}{}{There's no way out. That's it. THEY won't let you leave.}
{221}{}{Who are "they"?}
{222}{}{It all started a few weeks back. When that "thing" landed.}
{223}{}{Thing?}
{224}{}{I don't know. It's something from outer space. A meteorite, probably. I saw a flash in the sky. And then, I heard a crash.}
{225}{}{Did you try to find out what it was?}
{226}{}{The next day, I walked there and didn't find even a hole in the ground. And then it all started.}
{227}{}{Go on.}
{228}{}{At first, I didn't pay attention. It just looked like there were more tumbleweeds than usual. And then, it was like they became alive. They didn't let me leave the canyon. They blocked the road or clinged to my legs when I tried to leave. I stopped trying since then...}
{229}{}{Hm.}
{230}{}{Go! You still have a chance to get out of here. Run while you still can!}
{231}{}{Oh...}
