{100}{}{You see a supermutant.}
{101}{}{You see a giant supermutant.}

{110}{}{I'm hungry.}
{111}{}{You're hungry too?}
{112}{}{If I don't eat, I'll kill someone.}
{113}{}{Why not measure our strength?}
{114}{}{The puny humans will die out. We'll all outlive them.}
{115}{}{The Master hears my prayers.}
{116}{}{Who farted?}
{117}{}{I hate it I'm stared at.}
{118}{}{What year is it?}
{119}{}{So slow. When will we leave this desert?}

{120}{}{For the Master!}
