{100}{}{You see a super mutant.}
{101}{}{Here is a huge super mutant.}
{102}{}{ }

{120}{}{For the Creator!}
{121}{}{I hate it when people stare at me.}

{150}{}{Are we in the Texas lands yet?}
{151}{}{No, the Captain says we're still in Arizona.}
{152}{}{Ar-r! We crawl like a legless ghoul with a chainsaw in the ass.}
{153}{}{It can't be faster, it's dangerous for the fortress.}
{154}{}{I don't want to wait! The captain promised us a glorious battle and the seizure of lands.}
{155}{}{Should I remind you why we left Mariposa?}
{156}{}{I remember. I'm not stupid. But the Creator would not approve.}
{157}{}{Yes. But the Creator is no more...}
{158}{}{Ar-r-r! We shouldn't have left, we should have fought back!}
{159}{}{We have suffered too many losses. The captain knows what he's doing.}
{160}{}{Yes, the Captain is in charge now. But I can be a captain too!}
{161}{}{And what would you do?}
{162}{}{I would go back and take over the Lost Hills Citadel. And would demolish all the cities on the way.}
{163}{}{That's why you're not the captain. The captain is smart. You're stupid.}
{164}{}{Be silent! I'm not stupid!}
{165}{}{Nothing, the Captain will straighten your brains.}
{166}{}{Ar-r-r!}