{100}{}{You see a mexican.}
{101}{}{You see a mexican that suddenly appeared in the middle of the desert.}
{102}{}{Muchas gracias.}

{200}{}{Muchas gracias. (Gives you a flask of clean water as a reward) Bebe, amigo.}
{1200}{}{Muchas gracias. (Gives you a flask of clean water as a reward) Bebe, amiga.}
{201}{}{You don't speak english?}
{202}{}{Iiglês? No.}
{203}{}{I see. Well, safe travels, then.}
{204}{}{De nada. Where are you from, by the way?}
{205}{}{Hermosillo. There aren't any other cities in this region. Though calling it a city would be a stretch.}
{206}{}{What are you doing out in the desert?}
{207}{}{Surveying land. The army has to know where water sources here are, or some other stuff. Though, to be honest, there's nothing valuable here - just sand and giant insects. I thought I was done for. I was very lucky to have met you.}
{208}{}{I see. Well, safe travels, then.}
