{100}{}{You see a supermutant.}
{101}{}{You see a giant supermutant.}
{102}{}{   }

{120}{}{For the Master!}
{121}{}{I hate it when the humans stare at me.}

{150}{}{Are we in Texas yet?}
{151}{}{No. Captain says we're still in Arizona.}
{152}{}{Ar-rgh! We're crawling like a legless ghoul with a chainsaw in the ass.}
{153}{}{We can't go faster, it's too dangerous.}
{154}{}{I don't wanna wait! Captain promised us a glorious battle and the conquest of lands.}
{155}{}{Do I need to remind you why we left Mariposa?}
{156}{}{I remember. I'm not stupid. But the Master wouldn't approve.}
{157}{}{Yes. But the Master is no more...}
{158}{}{Ar-rrr-gh! We shouldn't have left! We should have fought back!}
{159}{}{We lost far too many people already. Captain knows what he's doing.}
{160}{}{Yes, Captain's in charge. But I want to be captain too!}
{161}{}{What would *you* do?}
{162}{}{I'd go back. Capture the Lost Hills citadel. Destroy all the cities we see along the way.}
{163}{}{This is why you're not captain. The Captain's smart. You, on the other hand, are stupid.}
{164}{}{Shut up! I'm not stupid!}
{165}{}{Don't worry. Captain will fix your brains up.}
{166}{}{Ar-rrr-gh!}
