{100}{}{You see a super mutant.}
{101}{}{Here is a huge super mutant.}

{110}{}{I'm hungry.}
{111}{}{Do you want to eat too?}
{112}{}{If I don't eat, I'll kill someone.}
{113}{}{Shall we face off?}
{114}{}{The pathetic little men will die out. We will outlive them all.}
{115}{}{The Creator hears my prayers.}
{116}{}{Who started the gas?}
{117}{}{I hate it when people stare at me.}
{118}{}{What year is it now?}
{119}{}{Gradually. When will we leave this desert?}

{120}{}{For the Creator!}