{100}{}{You see Paul.}
{101}{}{You see a very emaciated man.}

{200}{}{A human! So you... Listen, you shouldn't be here. The mutants will kill you if they find out.}
{201}{}{They didn't kill *you*. By the way, who are you?}
{202}{}{I know. So sit tight and don't make any noise.}

{210}{}{You're risking a lot.}
{211}{}{If they catch you, I won't be able to help you.}
{212}{}{Why are you still here?}
{213}{}{What do you think?}
{214}{}{You still have a chance to get out of here.}
{219}{}{See you.}

{220}{}{Who are you?}
{221}{}{My name's Paul. I used to be responsible for the maintenance of this platform.}
{222}{}{Amazing. How do you know how to operate this kind of technology?}
{223}{}{Can't be. No one alive today can operate this kind of machinery.}
{224}{}{Well, I'm an engineer. Trust me, they were preparing me for it my whole life.}
{225}{}{Really? Where?}
{226}{}{Does "Brotherhood of Steel" ring any bells to you? I'm a knight of that ancient order. And the job of the knights is to know how ancient tech works. Though, I'm actually an energy weapons specialist. It wasn't easy learning how to operate this platform, but I did it.}
{227}{}{I'm a member of the Brotherhood too, though only a recent one. Glad to meet you, brother.}
{1227}{}{I'm a member of the Brotherhood too, though only a recent one. Glad to meet you, brother.}
{228}{}{Alright, I believe you. As if I have a choice. In the entire history of the Brotherhood, only one man in the Wasteland managed to join our ranks as an equal. His deeds were enormous.}

{230}{}{How'd you end up here?}
{231}{}{The supermutants captured me somewhere near Necropolis. At first they wanted to kill me, but then they learned that I'm an engineer, and left me alive to maintain the platform. Ever since then, I've been kept here in captivity.}
{232}{}{Necropolis? Where is that place located?}
{233}{}{California. We're so far away, no wonder you don't know.}
{234}{}{Tell me about the Brotherhood of Steel.}
{235}{}{For a long time, we lived in our bunker and didn't leave for the surface. But then all of California was under the existential threat of supermutant invasion. Thanks to the bravery of our brothers and sisters, the army was destroyed. But we maintain our vigilance. Remains of it are still being found and driven out to this very day.}
{236}{}{But how did you learn about the army if you were just sitting in your bunker?}
{237}{}{A Wasteland wanderer discovered the threat. He was made an initiate soon after. It was he who sabotaged the enemy base in Mariposa. But the brutal fights with the supermutant remnants - that's our doing, and it's why we tell outsiders that it was our order that stopped the invasion.}
{238}{}{I hate your Brotherhood. You're a bunch of vile invaders.}
{239}{}{You're not the first and certainly not the last person to think this way. But against such abominations as the supermutants and the deathclaws, the ordinary population was completely powerless. The Wastes need the Brotherhood, whether you like it or not.}

{240}{}{Do you know where the supermutants are heading?}
{241}{}{They don't know themselves. The captain promised them that he will capture some nice region and create a supermutant government there.}
{242}{}{Have you tried escaping?}
{243}{}{Already lost my chance. There's nothing but desert around here - the mutants will easily catch up to me. But even if I leave this place, I doubt I'll be able to get back to my home, Lost Hills. I don't even know where we are.}
{244}{}{We're in the Sonora desert.}
{245}{}{Really? Well, then not all is lost. As far as I know, Rocky Point has an outpost where I could return to the Brotherhood.}
{246}{}{Then what are you waiting for?}
{247}{}{First, we've got to immobilize the platform. The lower level has a reactor that powers the whole system. If you disable it, the platform won't be able to move.}
{248}{}{I'll deal with it.}
{249}{}{The reactor is destroyed.}

{250}{}{The reactor is shut down. Time to get out of here.}
{251}{}{As an engineer, I want to cry at the destruction of this kind of technology. But there is no other way. The mutants are unlikely to figure out how to repair it. And here, in the middle of the desert, they pose no threat to anyone.}
{252}{}{Let's go.}
{253}{}{Don't draw attention to yourself.}
{254}{}{Let's go.}
{255}{}{You're free.}
{256}{}{I don't know how I'll get back to my brothers and sisters in Rocky Point. It's time to put everything they taught me in Lost Hills to good use. Thanks. If I survive, I'll tell the order about you.}
{257}{}{Godspeed.}
{258}{}{Sorry, pal, but I can't let you go. After all, your Brotherhood of Steel is evil incarnate. I'll kill you, like I killed all your friends at Puerto Penasco!}
{1258}{}{Sorry, pal, but I can't let you go. After all, your Brotherhood of Steel is evil incarnate. I'll kill you, like I killed all your friends at Puerto Penasco!}
{259}{}{All the mutants are dead. You're free.}
{260}{}{That was quite a battle. Without the mutants, this thing won't go far. Which is good. Eh, if only we had more soldiers like you back during the Great Mutant War.}
{261}{}{Let's go.}
