{100}{}{You see Paul.}
{101}{}{You see a very emaciated man.}

{200}{}{Man! How did you... Look, you don't belong here. Mutants won't let you live if they find you.}
{201}{}{They left you. Who are you?}
{202}{}{I know. So stay quiet and don't make a fuss.}

{210}{}{You're taking a big risk.}
{211}{}{If you get caught, I won't be able to help you.}
{212}{}{Why are you still here?}
{213}{}{What's on your mind?}
{214}{}{You still have a chance to escape from here.}
{219}{}{See you later.}

{220}{}{Who are you?}
{221}{}{My name is Paul. I follow the work of this platform.}
{222}{}{It's amazing. How do you know how to handle this technology?}
{223}{}{You're lying. No one living can control the old technologies.}
{224}{}{Well, I'm an engineer, I've been trained for this all my life.}
{225}{}{Really? Where did you get your knowledge?}
{226}{}{Does the name Brotherhood of Steel mean something to you? I am a knight of this ancient order. And the main task of knights is to deal with ancient technologies. However, I am an expert in energy weapons. I had to make every effort to manage the platform.}
{227}{}{I have also been a member of the Brotherhood of Steel since recently. Glad to meet you, brother.}
{1227}{}{I have also been a member of the Brotherhood of Steel since recently. Nice to meet you, brother.}
{228}{}{Okay, I'll believe you. What choice do I have? However, in the entire history of the Brotherhood, only one person from the Wasteland managed to join our ranks on common rights. And his merits were enormous.}

{230}{}{How did you end up here?}
{231}{}{The super Mutants grabbed me somewhere under Necropolis. First, they wanted to kill me. But then they found out that I was an engineer, and decided to leave the platform for debugging. I've been here in captivity ever since.}
{232}{}{Necropolis? Where is it?}
{233}{}{It's in California. No wonder you don't know because we are far from those places.}
{234}{}{Tell me about the Brotherhood of Steel.}
{235}{}{For a long time we lived in a bunker and kept our heads down until the whole of California was under threat of conquest by super mutants. But thanks to the bravery of our brothers and sisters, the army was defeated, and its remnants are still being persecuted.}
{236}{}{But if you were sitting in a bunker, how did you find out about the army?}
{237}{}{To be honest, the whole exploration was conducted by one stranger from the wasteland. Soon he was made an initiate. It was he who managed to sabotage the main enemy base in Mariposa. But we tell everyone that it was our order that stopped the army. And this is true, given the fierce battles that followed with the remnants of super mutants.}
{238}{}{I hate the Brotherhood. You are vile invaders.}
{239}{}{You are not the first and not the last person who thinks so. But in the face of a threat like super mutants or death claws, the ordinary population was powerless. The Wastelands need brotherhood, whether you like it or not.}

{240}{}{Do you know where the super mutants are going?}
{241}{}{They don't know themselves. The captain promised them that he would seize some rich district and create a super mutant state there.}
{242}{}{Have you tried to escape from here?}
{243}{}{I've already missed my chance. There's a desert all around, so the mutants will easily catch up with me. But even if I leave the fortress, I can hardly go back to my native Lost Hills. I don't even know where we are.}
{244}{}{We are in the Sonoran desert.}
{245}{}{That's how? Then all is not lost. As far as I know, there is an outpost in Rocky Point, they will be able to accept me there.}
{246}{}{Then what are you waiting for?}
{247}{}{First you need to immobilize the platform. At the lower level, there is a reactor that feeds the entire system. If you disable it, the platform will not be able to move.}
{248}{}{I'll take care of it.}
{249}{}{The reactor is destroyed.}

{250}{}{The reactor stalled. It's time to get out.}
{251}{}{As an engineer, I want to cry, looking at the destruction of such equipment. But there is no other way. It is unlikely that mutants will be able to restore the platform. And in the middle of the desert, they pose no danger to anyone.}
{252}{}{Leaving.}
{253}{}{The main thing now is to not attract attention to yourself.}
{254}{}{Leaving.}
{255}{}{You're free.}
{256}{}{I don't know how I'm going to get to my brothers and sisters in Rocky Point. It's time to remember everything I was taught in Lost Hills. Thank you. If I survive, I will inform the order about you.}
{257}{}{Have a good trip.}
{258}{}{I'm sorry, buddy, but I can't let you go. After all, you, the Brotherhood of Steel, are evil in the flesh. I will kill you, as I killed all your comrades in Puerto Penasco!}
{1258}{}{I'm sorry, buddy, but I can't let you go. After all, you, the Brotherhood of Steel, are evil in the flesh. I will kill you, as I killed all your comrades in Puerto Penasco!}
{259}{}{All the mutants are dead. You're free.}
{260}{}{It was strong. Without mutants, this thing won't get far. And that's good. Eh, we would have soldiers like you during the Great Mutant War.}
{261}{}{We're leaving.}
