{100}{}{You see a Mexican.}
{101}{}{The Mexican who suddenly appeared in the middle of the desert.}
{102}{}{Muchas gracias.}

{200}{}{Muchas gracias. (Gives you pure water as a reward) Bebe, amigo.}
{1200}{}{Muchas gracias. (Gives you pure water as a reward) Bebe, amiga.}
{201}{}{Don't you speak English?}
{202}{}{Iigl?No.}
{203}{}{I see. Well, then have a good trip.}
{204}{}{De nada. By the way, where are you from?}
{205}{}{I'm from Hermosillo. There are no other cities around here. Although you can't call it a city.}
{206}{}{And what are you doing in the middle of the desert?}
{207}{}{I'm conducting land exploration. The army should know where there are water sources or something else. However, there is nothing of value here - only the desert and giant insects. I thought I was finished. It was a great luck to meet you.}
{208}{}{I see. Well, then have a good trip.}
