{100}{}{This is Fred Stadtmaller.}
{101}{}{You see the padre in simple and ascetic clothes.}
{102}{}{Goodbye, my child}

{200}{}{Greetings, my son. I didn't think I'd meet a man in the middle of the desert. Are you lost? Do you need help?}
{1200}{}{Greetings, my child. I didn't think I'd meet a man in the middle of the desert. Are you lost? Do you need help?}
{201}{}{Who are you?}
{202}{}{I'm Padre Fred Stadtmaller. And I travel around Arizona in search of those whose soul needs my help - the offended, the sick, just the dead.}
{203}{}{Glad to meet you, Holy Father.}
{1203}{}{Glad to meet you, Holy Father.}
{204}{}{You're not my padre.}
{205}{}{Oh, no, no. Of course I'm not your father. Holy Father - that's how people of my rank have been called since ancient times. I'm sorry if it bothered you somehow.}
{206}{}{Okay.}

{210}{}{Is there anything I can help you with, my child?}
{211}{}{No, I'll figure it out somehow without divine intervention. Have a nice day, Padre.}

{220}{}{In the meantime, I'd like to talk to you.}
{221}{}{Sure. What do you want to know?}
{222}{}{Shall we go back a bit?}
{223}{}{Who are you?}
{224}{}{My name is Fred Stadtmaller. I am engaged in spreading the word of God in these lands. Just as before the Great War, the clergy of the Catholic Church were engaged in this... But many have already forgotten this and see me as just a strange person.}
{225}{}{One more question, please.}
{226}{}{Who gave you this rank, priest?}
{227}{}{It was in a monastic order on the outskirts of Phoenix. Even before the Phoenix was mired in the abyss of discord, and the order settled in the Cathedral of the Sacred Fire and began to interfere in worldly life.}
{228}{}{So you're from the Sacred Fire Church? And why did you leave your cell?}
{229}{}{We have disagreements with the current bishop of the Cathedral. Previously, our little church did not seek either power or wealth. We didn't meddle in the affairs of big cities. We only helped the suffering and kept ancient relics.}
{230}{}{Go on.}
{231}{}{But there have been big changes in the Cathedral, I can no longer carry my mass in this accumulation of evil and vice. Now I conduct my mass as the monks of the order would have conducted it before. That is, I continue the old traditions.}
{232}{}{In truth, your deeds are admirable, Holy Father.}
{233}{}{I don't think the order likes to tolerate crazy fanatics.}

{240}{}{How did you learn to control an iron bird?}
{241}{}{Ancient books store not only knowledge about civil aviation... But what am I talking about if Phoenix and other settlements lived by candlelight a few years ago.}

{250}{}{Yes, I need your help.}
{251}{}{Think as best you can, because they are waiting for me. I'll be leaving soon, and maybe we'll never see each other again.}
{252}{}{Actually, I'd just like to talk to you.}
{253}{}{In that case, I won't detain you any longer, Padre.}
{254}{}{I need treatment.}
{255}{}{Now your body is in perfect order. I'm not sure about the soul. But you'll have to deal with this on your own. It's time for me to hurry - sick children are waiting for me in St. Mary's Chapel.}
{256}{}{Adios, santo padre.}
{257}{}{I want to repent, Holy Father. There have been many transgressions in my past.}
{258}{}{I will not relieve you of your burden. But I can make it easier. Get down on your knees, my child....}
{259}{}{Thank you, Padre.}
{260}{}{I need all your stuff. Come on, give me everything you've got. And take off your clothes too.}
{261}{}{May Saint Joseph forgive you...}
{262}{}{Shut up.}
{263}{}{I'm tired of the cactus society and I want to get back to people. Can you carry me on your iron bird?}
{1263}{}{I'm tired of the cactus society and I want to get back to people. Can you carry me on your iron bird?}
{264}{}{Of course. It won't take long.}
{265}{}{Where would you recommend to go?}
{266}{}{Hmm. It all depends on what your soul desires.}
{267}{}{Give me a little time to think.}
{268}{}{She wants revenge for my family. They were taken away to the east of the Villa.}
{269}{}{So be it. I think you need to get to Garage City or Flagstaff.}
{270}{}{We flew to Garage City.}
{271}{}{Flew to Flagstaff.}
{272}{}{No, not now.}
{273}{}{All I need now is to get hold of a good weapon and ammunition. And earn extra money for daily bread.}
{274}{}{Then the road will certainly lead you to Phoenix. It is the largest and most developed city for miles around.}
{275}{}{Flew to Phoenix.}
{276}{}{I just want to settle down in some quiet place.}
{277}{}{I know this right in the middle of the Sonoran desert. It is called Casa Nueva for a reason. This is a real oasis in the middle of the desert.}
{278}{}{Flew to Casa Nueva.}
{279}{}{She dreams of exploring new worlds.}
{280}{}{Then you will probably want to go south, far into the Mexican territory.}
{281}{}{Then we flew south to the nearest Mexican city.}