{100}{}{You see the curator.}
{101}{}{In front of you is a man in a mantle of defiant color. Looking around the convoy, he seems to rise above the whole world.}
{102}{}{This person doesn't want to talk to you.}

{200}{}{A peaceful traveler in these parts? What a surprise. But we don't need fellow travelers. And don't bother us or our slaves. Is that clear to you? Now go your own way.}
{201}{}{Can I ask a question?}
{202}{}{Why don't the brothers in Fire share information?}
{203}{}{I'm not leaving here without answers.}
{204}{}{Clear. I'm leaving.}

{205}{}{It is a pity that your thinking is as insignificant as a single atom in a nuclear womb. I'll have to split you until you completely disappear!}
{206}{}{What are you carrying...}
{207}{}{If you really are a brother of Fire, then you should know: if you are not initiated into the most important things, then you are not worthy of it.}
{208}{}{So can I ask a question?}
{209}{}{Looks like you're a well-read person. And you don't want to share your knowledge.}

{210}{}{Only one.}
{211}{}{What are you transporting?}
{212}{}{Ancient... an artifact. Too important to talk about with the uninitiated.}
{213}{}{Who are you?}
{214}{}{Of all the questions, you choose the most meaningless. These are my mercenaries. These are my slaves. And I'm in charge of this whole convoy.}
{215}{}{Is it hot in this cassock in the middle of the desert?}
{216}{}{ (grinning) No. Synthetic fiber and capillary-liquid compressor make the cassock ideal for the desert.}
{217}{}{I'd like to get to the nearest town. Tell me the way?}
{218}{}{Hmm? (raises an eyebrow mysteriously)}
{219}{}{Uh, thanks for the answer.}
{220}{}{And that's it? I expected more.}
{221}{}{(shows Flagstaff city on your map)}
{222}{}{(shows Phoenix city on your map)}
{223}{}{(shows the city of Two-Sun on your map)}
{224}{}{Your question is settled. Leave if your miserable life is worth something to you.}
{225}{}{I'm dying of thirst! Give me a sip of water!}
{226}{}{Saving a worthless life is not in my plans. But on the other hand, any convention is valuable for the revival of the world. Take a sip of this pure water. And tell everyone you meet that the Followers of Fire dream of giving everyone water to drink... everyone who deserves it.}
{227}{}{I'm not going to waste time on those who are ready to talk, but not ready to listen. Go away.}