{100}{}{You see the Curator.}
{101}{}{You see a man in robes of a striking color. He's looking at the convoy like he's on the top of the world.}
{102}{}{This person does not wish to speak with you.}

{200}{}{A peaceful wanderer at this time of day, in this part of the Wastes? How unexpected. But we have no need of companions. Go, and don't bother us or the slaves. Got it?}
{201}{}{Can I ask you a question?}
{202}{}{Why can't brothers-in-Fire share information with each other?}
{203}{}{I'm not leaving until I get some answers.}
{204}{}{Got it.}

{205}{}{How sad that your thinking is as pathetic as a lone atom in an atomic womb. We will have to Придется split you into total oblivion!}
{206}{}{What the fuck are you talk-...}
{207}{}{If you are truly a brother of Fire, then you must know that if you do not know about this, you are unworthy of knowing.}
{208}{}{So... can I ask you a question?}
{209}{}{You're a wise man. But don't want to share the wisdom.}

{210}{}{Yes. Just one.}
{211}{}{What are you transporting?}
{212}{}{An ancient... let's say, artifact. It is too important to talk about with uniniciated.}
{213}{}{Who *are* you?}
{214}{}{Out of all the questions you could ask, you chose the most pointless one. These are my mercenaries, and these are my slaves. And me - I oversee this convoy.}
{215}{}{Don't you get hot, wearing those robes in the middle of the desert?}
{216}{}{(grins) No. It's made of synthetic fiber and has a liquid-capillary compressor. Ideal for desert conditions.}
{217}{}{I need to get to the nearest settlement. Mind showing me the way?}
{218}{}{Hm? (raises an eyebrow, mysteriously)}
{219}{}{Uhh, thank you for your answer.}
{220}{}{That's all? I expected more.}
{221}{}{(shows the location on Flagstaff on your map)}
{222}{}{(shows the location on Phoenix on your map)}
{223}{}{(shows the location on Two Sun on your map)}
{224}{}{Your one question has been answered. If your pathetic life is worth anything to you, go.}
{225}{}{I'm dying of thirst! Give me some water, please!}
{226}{}{Saving your pathetic life is not part of my plans. But for the cause of restoring the world, all prices are worth paying. Take a sip from this purest of waters, and tell that the Followers of the Holy Fire dream of fulfilling the thirst of all... all worthy of it.}
{227}{}{I will not spend my time on those who are ready to talk, but not ready to listen. Go.}
