{100}{}{You see a slave.}
{101}{}{You see an exhausted slave. His hands are covered with bloody calluses, and the shoulders have gone blue from the ropes.}
{102}{}{This person's condition prevents them from talking.}

{110}{}{U-gh...}
{111}{}{Oof...}
{112}{}{E-eh...}
{113}{}{Welp...}
{114}{}{What?}
{115}{}{Run.}
{116}{}{Don't talk to me.}
{117}{}{They should just shoot me.}
{118}{}{}
{119}{}{}
