{100}{}{You see a scribe.}
{101}{}{You see one of the Brotherhood of Steel's scribes.}
{102}{}{Thanks again.}

{200}{}{Hey, thanks for the help. Those bandits wanted to force me into giving them information about the Brotherhood. But now, thanks to you, they won't learn anything.}
{201}{}{What Brotherhood?}
{202}{}{Oh, so you don't know? It's an ancient order, devoted to the preservation and study of ancient technology. Our fortress here is located in the old port by the ruins of Puerto Penasco.}
{203}{}{Thanks.}
{204}{}{Thanks again for helping me. When I return to the fortress, I'll tell them about you right away. You should visit that place if you happen to be near.}
{205}{}{No problem. Goodbye.}
{206}{}{I can't walk by without helping my fellow brother.}
{207}{}{I hate the Brotherhood! Die, all of you!}
