{100}{}{You see a clerk.}
{101}{}{You see one of the clerks of the Brotherhood of Steel.}
{102}{}{Thanks again.}

{200}{}{Hey, thanks for the help. The bandits were hoping to get information about the Brotherhood out of me. But thanks to you, they won't know anything.}
{201}{}{What kind of Brotherhood?}
{202}{}{Oh, so you don't know? It's an ancient order dedicated to the preservation and study of ancient technologies. Our fortress is located in the old port on the ruins of Puerto Penasco.}
{203}{}{I see.}
{204}{}{Thanks again for saving me. When I get back to the fortress, I will definitely tell them about you. Come visit, if you happen to be around.}
{205}{}{Good. Bye.}
{206}{}{I can't pass by without giving a helping hand to my brother.}
{207}{}{I hate the Brotherhood! Why don't you all die!}
