{100}{}{You see a cyberpsych.}
{101}{}{You see a distraught tinker whose mind has been taken over by technology.}

{110}{}{How my head hurts!}
{111}{}{Stop those numbers! I can't do this anymore!}
{112}{}{Why? Why? Why?}
{113}{}{There are only numbers all around!}
{114}{}{The program tells me to kill.}
{115}{}{I'm a machine, I'm a machine, I'm not a person...}
{116}{}{This voice in my head does not allow me to execute the program!}
{117}{}{I'm just a variable in a big program. Don't stop her from working!}
{118}{}{You have interfered with my program!}
{119}{}{You should be erased from the database!}
