{100}{}{You see a cyberpsycho.}
{101}{}{You see crazy tinsmith. His mind is posessed by technology.}

{110}{}{My head! It hurts so much!}
{111}{}{Stop those numbers! I can't take it anymore!}
{112}{}{Why? Why? Why?}
{113}{}{Numbers everywhere!}
{114}{}{The program tells me to kill.}
{115}{}{I'm a machine, a machine, not a human...}
{116}{}{The voice in my head doesn't let me execute the program!}
{117}{}{I'm just a variable in a big program. Don't attempt to interfere!}
{118}{}{You interfered!}
{119}{}{You ought to be deleted from the database!}
