{100}{}{You see a Vault resident.}
{101}{}{You see a resident of the local Vault. They look incredibly clean.}

{110}{}{Good day... or is it night? What's going on out there?}
{111}{}{Please don't hurt us. We're peaceful people!}
{112}{}{We've been living in this Vault for a long time. Where did you come from?}
{113}{}{The raiders have been spending several months trying to break in.}
{114}{}{How did you get in?}
{115}{}{This is our home. We have nowhere else to go.}
{116}{}{We won't survive in the desert. Please don't make us go!}

{120}{}{Thank you for saving us from the horrible outside world!}
{121}{}{Thank you for repairing our life support system!}
{122}{}{Ah, how fresh the Vault air is now!}
{123}{}{If not for you, we'd have to leave the Vault.}
{124}{}{You're a good person. Unlike those raiders.}
{125}{}{You know, you remind me a bit of our first Overseer. His name was Van Buren, I think.}
{126}{}{Thanks for the help.}
{127}{}{We wouldn't survive in the desert.}
