{100}{}{You see Frank.}
{101}{}{You see a resident of the asylum. He looks pretty fresh and clean compared to any inhabitant of the wasteland.}

{200}{}{P-please don't hurt us! We are peaceful people. We don't want any problems.}
{201}{}{Why are you afraid of me? I didn't do anything wrong.}
{1201}{}{Why are you afraid of me? I didn't do anything wrong.}
{202}{}{Then stop bleating, it annoys me.}
{203}{}{So... aren't you a raider?}
{204}{}{No, I'm }
{205}{}{. And who are you?}
{206}{}{I'm Frank. Since the overseer died, I've been in charge of everything here. And I got off to a terribly bad start.}
{207}{}{Why?}
{208}{}{This old Vault crumbles at the slightest touch. The life support system is out of order, the generator is not working at full capacity. And we don't know how to fix it.}
{209}{}{Yes, a real disaster.}
{210}{}{And are these your problems? Ugh!}
{211}{}{Besides, there are raiders waiting for us outside. Over the past few months, they have carried out a dozen raids to seize the Vault. So far, they are being held back by a large door, but with such problems, we will soon go outside so we don't suffocate. I'm afraid to imagine what they will do to us. They've already caught Fred and are probably torturing him.}
{212}{}{How can I help you?}
{213}{}{Well, I'm just solving all sorts of problems. Not for nothing, of course.}
{214}{}{Will you really help us? Then this is a great success for us. We need to fix the generator and get the computer to turn on life support.}
{215}{}{Okay, I'll do it.}
{216}{}{And now stand and look at the work of a professional.}

{220}{}{Have you restored asylum support yet? It doesn't look like it. We need to fix the generator and get the computer to turn on life support.}
{1220}{}{Have you restored asylum support yet? It doesn't look like it. We need to fix the generator and get the computer to turn on life support.}
{221}{}{It's time to get busy. See you later.}

{230}{}{Where is the generator room?}
{231}{}{The generator room is at the end of the corridor, to our left. But it doesn't make sense without tools. The door is locked there.}
{232}{}{Later.}
{233}{}{Where is the computer room?}
{234}{}{The computer room is further down the corridor on the right. But the computer will not work due to lack of electricity.}
{235}{}{How to restore life support?}
{236}{}{After starting the generator, just use the computer to turn on the life support system. Then all we'll have to do is fix the robo-eye so that it can patrol the Vault and protect us from enemies.}
{237}{}{Tell me about this Vault.}
{238}{}{The Vault was built a hundred years ago. Our ancestors survived the nuclear war here. But it is no longer possible to fully survive in the Vault. We lock ourselves in here only when there is some kind of threat.}

{240}{}{Thanks for the life support systems. We already feel better!}
{241}{}{No problem.}
{242}{}{Gladly.}
{243}{}{Anything else you want to say?}
{244}{}{We don't have many useful things. Here, take this jumpsuit. He's a bit battered but still copes well with the effects of the forces of nature.}
{245}{}{We don't have many useful things. Here, take this camping flask. The overseer said that she brought him good luck when he traveled through the desert. With her, he never ran out of water, even in the hottest and driest places.}
{246}{}{And thanks for that.}
{247}{}{Are you kidding? A pathetic flask for such a difficult job? Take off your jumpsuit, and hurry up!}
{248}{}{All right! All right! I don't know how I can live without him... Here, take it.}
{249}{}{And don't look at me so pityingly. This is an honest payment for the work.}
