{100}{}{You see the administrator.}
{101}{}{You see a hot-tempered manager. He mutters something to himself.}
{102}{}{The mine is temporarily closed. Without Faber, the city went crazy!}
{103}{}{That's what happens when they raise their voice at me.}
{104}{}{Oh, finally my beloved brahmnin fries! The only joy in this crazy place.}

#Random replicas
{110}{}{Cretins! Idiots! We've missed all deadlines again!}
{111}{}{How many times can I repeat to these fools?!}
{112}{}{The mine will just get up without me.}
{113}{}{I have the hardest job.}
{114}{}{The boss doesn't understand how hard I'm trying.}
{115}{}{I would work even better, but such earnings kill any desire.}
{116}{}{Ore, ore... What do I live for?}
{117}{}{I'll rewrite a couple of notes. No one will ever suspect.}
{118}{}{This report needs to be written again.}
{119}{}{No one can handle this position better than me.}

{120}{}{Damn, damn, damn! The mines are blown up, there are not enough workers, and what should I do now?}
{121}{}{What kind of crazy psychopath wanted to blow up a mine?!}
{122}{}{These mines won't work again without me.}
{123}{}{Everything is gone...}
{124}{}{Well all... Now I'm going to get slapped for sure.}
{125}{}{Maybe I should pack up my belongings and run away?}
{126}{}{Ore, ore... Ore again. Tired.}
{127}{}{My caps were crying... Soon the city will become impoverished.}
{128}{}{The mine collapsed, but the reports didn't go away.}
{129}{}{Just a little more and I'll go completely crazy.}

#Dialog
{200}{}{This is the administration, not a brothel! What do you need?!}
{201}{}{Raise your voice at me again, and I'll knock out all your teeth.}
{202}{}{Don't be so nervous. I just want to ask a couple of questions.}
{203}{}{Do you even know who I am?! I am the administrator of this mine! You could say Roy Faber's own right-hand man. And you dare to talk to me like that? Get out before I get really mad!}
{204}{}{Well all. It's going to *really* hurt, Mr. Big Boss.}
{205}{}{ (voice changes) Okay, okay, don't let go of your hands! It's unlikely that the caravaneers will respect me if I'm covered in bruises... (to myself) Damn, and where do people like you come from...}
{206}{}{So now you're ready to talk?}
{207}{}{A couple of questions?! I don't get paid for idle chatter. I'm doing business here. Do you understand? BUSINESS! So let's get this over with.}
{208}{}{So are you ready to talk now?}

{209}{}{Clearly. I'm leaving.}
{210}{}{What's the matter?}
{211}{}{Nothing. Happily.}

# About myself
{212}{}{Who are you and what are you doing here?}
{213}{}{I'm the administrator! I repeat: ad-mi-ni-stra-tor! This means that the work of this entire mine rests on my shoulders. In other words, I am the main face of this company... well, after Roy Faber, of course.}
{214}{}{Must be a hard job for you?}
{215}{}{Of course. What do you think, redneck? Managing ore production and cultivating beds is not the same thing at all.}
{216}{}{It looks like you have a very nervous job. And no one understands this except you.}
{217}{}{(pause) You... you have no idea how close this is to the truth. I put all my strength into this work, and what in return? Pathetic caps that don't even have anything to buy. And old housing without amenities.}
{218}{}{[Listen]}
{219}{}{Roy doesn't seem to hear me. He just doesn't realize my importance and the size of my contribution. For him, I'm just as much a worker as the others. (to myself) Damn, I shouldn't have left Phoenix for this hole...}
{220}{}{It's horrible. But let me change the subject.}
{221}{}{This... it's none of your business. And not another word about it!}
{222}{}{OK. Let's talk about something else.}
{223}{}{And what does Roy Faber have to do with it?}
{224}{}{Do you really not understand or are you just kidding me? He *owns* this mine. As well as the whole colony.}

{230}{}{Is this where the caravans leave for Phoenix?}
{231}{}{Only a special cargo caravan. Is he the one you need? Then look for the leader in the building opposite.}
{232}{}{OK.}
{233}{}{Slaves have recently disappeared here. What do you know about it?}
{234}{}{Workers periodically disappear here. Some are overwhelmed by landslides, others are devoured by huge rats. There is no one to investigate each case. Look for answers in the depths of the mine, and don't come to me with this question.}
{235}{}{What a shame.}
{236}{}{Why is the mine closed?}
{237}{}{It's over! The mine is closed. Because some cretin blew up the entrance. We will be shoveling this collapse for at least a month. And we don't have such resources - the mine is bankrupt.}
{238}{}{It looks like this "cretin" has given you a headache. Have a good stay.}
{239}{}{What about my assignment?}
{240}{}{Forget. The mine has been destroyed, and there is no way to get inside now.}
{241}{}{Well, we will have to look for another source of earnings. Bye.}
{242}{}{The bartender asked me to take this to you.}
{243}{}{Oh, finally my beloved bramfrey! The only joy in this crazy place. I hope you didn't touch anything here. Otherwise, I will be VERY angry. Well, what are you looking at? Go do something.}
{1243}{}{Oh, finally my beloved brahmnin fries! The only joy in this crazy place. I hope you didn't touch anything here. Otherwise, I will be VERY angry. Well, what are you looking at? Go do something.}
{244}{}{OK.}
{245}{}{Do you know that the warden beats up prisoners?}
{246}{}{I'm not going to discuss this with you!}
{247}{}{Uh, don't strain yourself so much...}

#Quests in mines
{250}{}{Faber told me to sort out the problems.}
{251}{}{We can't keep up with the deadlines, and these stupid people from the garrison can't find new workers. I'm doing everything I can, but it's not enough!}
{252}{}{Is it that bad? What will help change the situation?}
{253}{}{The robot driller broke down. Its repair will significantly reduce the need for workers. So someone will have to find the parts and fix this piece of iron.}
{254}{}{What else?}
{255}{}{There are huge rodents in the mines. They rush at the workers and gnaw the equipment. The first thing you need to do is kill the rat king, this is the most dangerous creature.}
{256}{}{Clear. As soon as I figure it out, I'll let you know.}
{257}{}{However, it doesn't matter.}
{258}{}{It was predictable.}

{260}{}{About the drilling robot.}
{261}{}{Has it been repaired yet? If not, I don't even want to hear anything.}
{262}{}{Where can I find parts for such an unusual technology?}
{263}{}{Obviously where they are. Do you understand? I don't know! Remember all the scrap dumps that you happened to meet on the way.}
{264}{}{The robot is in perfect order and ready to work.}
{265}{}{I really didn't expect that the redneck would cope with such a delicate problem. Well, here's your fee, there's 200 caps. Good job.}
{266}{}{OK.}
{267}{}{I will inform Faber about your merits. Go talk to him.}
{268}{}{I will definitely look into him.}
{269}{}{Only when there is free time.}

{270}{}{About the rat king.}
{271}{}{What, is this creature really dead?}
{272}{}{Of course. Deader than dead.}
{273}{}{Really? Explain now why I should believe you?}
{274}{}{Here are the monster's teeth as proof.}
{275}{}{If you want to get rid of the creature, then give me explosives.}
{276}{}{Damn it, do you even know how hard we got this army reserve? Timing... But the rat is more important now. Here's the key to the warehouse in the mine. Use stocks wisely.}
{277}{}{OK.}
{278}{}{This is ridiculous. I won't give you anything.}
{279}{}{Maybe I would have given you the explosives, but my key is missing somewhere. (lowering his voice) I think it was stolen.}
{280}{}{Oh, what a surprise.}
{281}{}{Excellent! I love executive people. There was a reward for this creature. Here are your 200 caps. I advise you to spend all of them at a local bar.}
{282}{}{Absolutely.}
{283}{}{A thief? Here? Damn him!}

{290}{}{How are things going in the mine?}
{291}{}{Another question.}
{292}{}{Clear.}
{293}{}{After the sabotage, we spend all our strength on manually clearing the rubble. It will take a lot of time and effort. I don't know if we have enough resources and patience.}
{294}{}{After the death of our boss, the city became dangerous. And the fate of the mine is even more unclear. We can only hope for the best.}
{295}{}{After the escape of the prisoners, there is no one to mine ore. Deadlines have already been disrupted, and now this...}
{296}{}{Thanks to your efforts, the mine is at the peak of production! I'm not even sure we'll sell out all the uranium this season. Keep it up! Now I can channel my genius in the right direction.}
{297}{}{Things are bad. Deadlines are disrupted, there are not enough workers, and the boss breaks down on subordinates. Not the best times for the mine, that's for sure.}
{298}{}{Can I help you with anything?}
{299}{}{Production was stopped due to the collapse. If you want to help, just don't ask stupid questions.}
{300}{}{The mine is temporarily closed. Without Faber, the city has gone crazy!}
{301}{}{Oh, it looks like you have serious problems here. Well, then there's nothing for me to do here. Bye.}
{302}{}{But what about those problems with the drilling robot and the rat king?}
{303}{}{Forget it. I'm getting out of here.}
{304}{}{OK.}