{100}{}{Here is a bar visitor.}
{101}{}{You see a strung-out colonist. He's a little drunk.}
{102}{}{Don't come near me.}
{103}{}{Stop, that's enough! I'm guilty, I admit!}
{104}{}{Ah, now I see potential in you.}
{105}{}{Okay, let's assume we're reconciled.}
{106}{}{Okay, you've had enough. Now go get me a drink.}
{107}{}{Ah, someone's showing off with their shining armor.}

{200}{}{Hey, you! I don't know you. For the first time in the city? Then get me a drink. Right now.}
{201}{}{Why should I buy you a drink?}
{1201}{}{Why should I buy you a drink?}
{202}{}{Look, I don't want any trouble, just don't bother me, okay?}
{1202}{}{Look, I don't want any trouble, just don't touch me, okay?}
{203}{}{The hell with it.}

{204}{}{Because in front of you is the living embodiment of power and law in this city! I work for Roy Faber himself. Got it? Then bring a drink, otherwise you'll run into a fight.}
{205}{}{I don't want any trouble, don't touch me.}
{206}{}{You can only scream. Haven't you been hit in the ribs for a long time?}

{207}{}{Ha! Pathetic village pussy. Get out of the bar if you don't have the guts. There's no place for weaklings like you in this town.}
{1207}{}{For me to touch a village brat like you? Better go outside, that's where you belong.}
{208}{}{Okay, okay, whatever you say. You're the boss here.}
{209}{}{And that was unpleasant. Did you want a fight? So get it!}

{210}{}{What about? The way you talk to me, you empty shit! Now you will beg for mercy from me...}
{211}{}{Just don't hit me in the face...}
{212}{}{Great, show me what you're capable of.}

{213}{}{I work for him too. So shut up.}
{214}{}{ (through his teeth) W-damn... (returns to his bottle and looks dejectedly at the table)}
{215}{}{That's it.}

{216}{}{Faber is dead! Do you hear? He's dead!}
{217}{}{Yes, yes, uh, I hear, calm down...}
{218}{}{I found something to be proud of. You get off on drunks in a bar just because you're a six, right?}
{219}{}{Well, no. I'm just... me... Go to hell!}

{220}{}{What do I need?}
{221}{}{Nothing anymore.}
{222}{}{Which is to be expected.}
{223}{}{Fuck off.}
{224}{}{With pleasure.}
{225}{}{Don't come near me!}
{226}{}{And I'm not going to.}
{227}{}{The peasants from the Villa are kept in prison. They need to be released.}
{228}{}{What?! It's the craziest idea I've ever heard. Faber will not part with the prisoners just like that. And you shouldn't even think about escaping - you'll just sign a death sentence for yourself.}
{229}{}{Then you tell me.}
{230}{}{Well, if the prisoners break free, they will be killed by collars. Just a few miles of freedom, and then boom! - and there is no head.}
{231}{}{How cruel.}
{232}{}{Collars can be turned off at the radio station. But only two people know how to do it: Faber and Smart Guy. So you have almost no chance.}
{233}{}{We'll see about that.}