{100}{}{This is Joe.}
{101}{}{You see a bartender, a local celebrity.}
{102}{}{The bar is closed, come in the morning.}
{103}{}{Z-z-z...}
{104}{}{Cool armor. But you should wear something simpler for the bar.}
{105}{}{Sorry, but no guns in the bar. Such a rule.}

#Floating replicas
{109}{}{What is heard in the world?}

{110}{}{It looks like a good deal is planned with Garage City.}
{111}{}{Silence hung over the streets of Garage City. As if no one had ever lived there.}
{112}{}{Faber and Garage City signed a contract. I think it will benefit everyone.}

{113}{}{San Brahmin has the best meat, but they stopped selling it.}
{114}{}{They say there was a big commotion in San Brahmin. But it's all right now.}
{115}{}{Those stupid cattlemen have closed all their trade routes with Phoenix.}

{116}{}{These sectarians from the south clearly have something on their mind.}
{117}{}{The Church of the Sacred Fire burned to the ground. That's the irony.}
{118}{}{These sectarians from the south clearly have something on their mind.}

{119}{}{There are more and more people from the south, and fewer and fewer goods.}
{120}{}{They say there is unrest in Phoenix right now.}
{121}{}{Eh, I would like to take another look at the Big City.}

{122}{}{Someone is killing patrolmen in the old town.}
{123}{}{I had no idea that rangers were behind the attacks on the patrolmen.}
{124}{}{Who do these Rangers think they are?}

{125}{}{Faber knows what to do, he will rebuild the city.}
{126}{}{The city will have a hard time without Roy Faber.}
{127}{}{The mine is working at full capacity again.}

{128}{}{The jailers took up the slave trade. This is a little alarming.}
{129}{}{Prisoners escaped from the jailers. We have to be more careful.}
{130}{}{This is the first time I've seen jailers release prisoners.}

{131}{}{Ugh, sometimes a busty maid is not enough for complete happiness.}
{132}{}{This is a bar, not a store.}
{133}{}{Do you want it stronger?}
{134}{}{The new batch will arrive with a delay.}
{135}{}{This is the best alcohol north of Phoenix.}
{136}{}{Should I pour some more?}

#The first dialog
{200}{}{Hello.}
{201}{}{Can I ask a couple of questions?}
{202}{}{Bye.}
{203}{}{Come in, you're always welcome here.}
{204}{}{Come in. But don't make trouble.}

#Questions
{210}{}{What do you want to know?}
{211}{}{Tell me something else.}
{212}{}{Let's return to the conversation about the bar.}
{213}{}{Can I ask a couple of questions on another topic?}
{214}{}{Let's go back a bit.}
{215}{}{Well, the choice is small. The mine needs workers all the time. And the garrison was looking for people for special tasks.}

{220}{}{Where can I earn extra money here?}
{221}{}{Well, the choice is small. The mine needs workers all the time. The garrison was looking for people for special tasks. I can also give you a couple of small orders. Choose what is closer to you.}

{222}{}{I'm new here. Tell me about Flagstaff.}
{223}{}{Then you need to know that this is a labor colony with a strict regime. The main places here are the garrison in the east and the uranium mine in the north.}
{224}{}{Tell me about the mines.}
{225}{}{The whole city owes this mine. The colony was created from the very beginning to produce uranium. The mine brought a good income, but recently things have been going tight due to a shortage of workers.}
{226}{}{Tell me about the prison.}
{227}{}{Faber's mercenaries set up a camp among the ruins and drove the criminals there. They were recruited from everywhere, from all over the wasteland. Now the prisoners are working out their crimes, and the colony is thriving thanks to their work.}
{228}{}{Tell us about the postal service.}
{229}{}{A branch of the company from Phoenix. Engaged in the delivery of small parcels between settlements.}
{230}{}{There are rumors that slavery is flourishing here.}
{231}{}{I'll give you a free tip: don't say that word out loud anymore. The workers consist of criminals and peons. Some are serving their sentences, while others are working off their debts. Of course, there are enslaved savages, but they should be called servants, not slaves.}
{232}{}{Why keep former criminals in custody?}
{233}{}{For hard labor. Here in this area, much has been restored by the hands of prisoners. It would be much more difficult to equip the Flagstaff without them.}
{234}{}{Do you think this is right?}
{235}{}{Or else! We have rebuilt the city and set up production thanks to these prisoners. Are there many more such beautiful places around?}
{236}{}{Where did you get all this alcohol?}
{237}{}{Oh, these drinks are made in Phoenix, and they are brought here once a month with caravans. Of course, this drink can not be compared with the pre-war, but it is cheap and affordable.}
{238}{}{I want to buy drinks for everyone present.}
{239}{}{That's generosity. It will cost you 50 caps.}
{240}{}{The price does not matter - pour for everyone, I treat!}
{241}{}{How much? I'm afraid I can't afford generosity today.}
{242}{}{No, wait, I need to know something first.}
{243}{}{It's too expensive. Some other time.}
{244}{}{Not a bad start. People will appreciate it. But I'll give you a tip - one drink is not enough to earn a reputation here.}
{245}{}{Before the booze runs out, let's chat.}
{246}{}{I'll remember. And now it's time for me to do more important things.}
{247}{}{How do you feel about Roy Faber?}
{248}{}{He is our leader. There wouldn't be a city without him. (leaning towards you and lowering his voice) Listen, this is not the person you can discuss. If you want to live, don't say his name for no reason. I hope you understand me.}
{249}{}{He is our leader. There wouldn't be a city without him.}

# The rat king's teeth from the mines
{250}{}{Look, it's the tooth of that rat king from the mines.}
{251}{}{Seriously? I'll be damned if this mutant wasn't the size of a brahmin! They've told me all sorts of things about him... listen, sell him to me. I'll pay 100 caps.}
{252}{}{Why do you need these teeth?}
{253}{}{Okay, take it.}
{254}{}{No, I'll make an amulet out of it to intimidate enemies.}
{255}{}{I'll think about your offer.}
{256}{}{This attraction is sure to attract customers.}
{257}{}{Eh, these rural superstitions of yours... In vain you refuse the bottlecaps. Think again.}
{258}{}{(grins ominously) Now I'm going to unwind with this thing... Oh, yes - your 100 caps.}
{259}{}{Good deal.}
{260}{}{Goodbye, speculator.}
{261}{}{Looks like you're not ready to discuss it. Tell me about something else.}
{262}{}{I'm not afraid of anyone. But since that's the case, let's change the subject.}
{263}{}{Take it for free. But don't forget to mention me in your stories.}
{264}{}{Oh-ho-ho, now I'm going to unwind with this thing. Are you sure you don't need a reward? Take at least a bottle of beer.}
{265}{}{Have a nice day, Joe.}
{266}{}{Please, I really need medicines. Aren't we friends?}
{267}{}{Come on. You don't want me to get hurt, do you?}

#About trading
{270}{}{What are you selling?}
{271}{}{Alcohol and snacks. What else can you trade in a bar? Although sometimes you have to be a whole store.}
{272}{}{Do you only accept caps for payment?}
{273}{}{Yeah. Merchants from the south now accept only bottle caps. And pre-war money has already completely gone out of circulation.}
{274}{}{Tell me where to buy medicines here?}
{275}{}{Well, nowhere but caravans. I keep my own reserves for myself.}
{276}{}{I don't have any more medicines.}
{277}{}{Surely you won't need them. Better sell it to me before they go bad.}
{278}{}{Hmm. There is some truth in these words. Here's what I can offer. (puts a modest supply of medicines on the counter)}
{279}{}{Uh, no. Even in a safe place like Flagstaff, you need to keep a couple of stimpacks ready.}

{280}{}{A client with my reputation deserves special prices. What do you think?}
{281}{}{I think I'll agree. Both me and other customers will be pleased to see you in this bar. You can count on a discount in 20%.}
{282}{}{ Wonderful. What do you have for today?}
{283}{}{They say one outsider created a lot of problems in this town. I hope he doesn't stay here too long.}
{284}{}{Have you raised the prices? Why?}
{285}{}{Yeah, there was a trade "crisis". And if you don't like the prices, look for another bar in this city. By the way, there is no other bar here.}
{286}{}{Clear.}

#Disassembly in the bar
{287}{}{I've been dreaming for a long time that someone would put this arrogant mercenary in his place. Here, have a beer on me. But don't relax. The garrison will remember this story for a long time.}
{288}{}{I'll get over it somehow. Thanks for the beer.}
{289}{}{Yeah, special prices... twice as big.}

# About your relatives in the city
{290}{}{I'm looking for my relatives from a village in the west.}
{291}{}{Are they here of their own free will? No? Then they can only be in one place - in the pen for prisoners. Go straight down the main street to the east.}
{292}{}{Why do you think they can only be there?}
{293}{}{Because I don't remember any newcomers in the city, but recently there was a large replenishment of savages in the penal servitude.}
{294}{}{Why keep people in a pen?}
{295}{}{So that they work in the mine and rebuild the city. This whole colony owes hard labor.}
{296}{}{Then it's time for me to see the head jailer.}
{297}{}{As you know. Watch yourself and don't get into trouble. Faber is not to be trifled with, many are afraid of him.}
{298}{}{Thanks for the help. I have to go.}

#The sale of tequila has been discontinued
{300}{}{Where did the normal booze go?}
{301}{}{They say the moonshiners' shop in Phoenix has a rusty lid. Now I have to take any alcohol that the caravaneers can get. By the way, that's why the prices had to be raised.}
{302}{}{I think I know the story. Um, bye.}
{303}{}{Yeah, it's a terrible story. I have to go.}
{304}{}{Show me what you have.}
{305}{}{Great, now let's see what I can offer you...}

#Quest - return the debt
{310}{}{Is there another task for me?}
{311}{}{There is one. A mercenary named Davis owes me a hundred caps. I stopped letting him in the bar, but it's bad for business.}
{312}{}{What do you suggest?}
{313}{}{If you make him pay the debt, I'll give you half.}
{314}{}{OK. His debts will be mine from now on.}
{315}{}{It's risky, figure it out for yourself.}
{316}{}{I'll think about it.}
{317}{}{Agreed. Remember, Davis has 100 caps, and you have 50.}
{318}{}{I'll remember.}
{319}{}{Of course, there is no problem. But my offer is still valid.}
{320}{}{Clear.}
{321}{}{Think about it. You have a lot of time, because Davis is in no hurry to pay the debt.}
{322}{}{Clear.}
{323}{}{I want to repay the debt to the bar.}
{324}{}{Really? And I thought you couldn't do it. Thank you. Give me 50 caps, the rest is yours, as agreed.}
{325}{}{I like the ringing of the caps more and more. See you soon.}

#Slot machine
{330}{}{That slot machine doesn't work.}
{331}{}{Yes, I know. But it was a good thing, it attracted customers.}
{332}{}{Why isn't it working?}
{333}{}{It looks like something burned out. There is nothing to replace, there are no suitable parts in this city. You seem to travel a lot, don't you? If you find something to fix the Starball, I'll pay 50 caps.}
{334}{}{Agreed.}

{335}{}{That's great.}
{336}{}{First I want to ask you about this machine.}
{337}{}{Let's change the subject.}
{338}{}{Be there.}

{339}{}{This is not my profile.}
{340}{}{As you wish. I'll find someone else.}
{341}{}{Do you know what your bar is missing?}
{342}{}{What is it?}
{343}{}{I don't know either. I'll let you know as soon as I think of it.}
{344}{}{A patriotic flag on the wall. And I have just such a one.}
{345}{}{Good God, these old flags have long since decayed. I thought I wouldn't find any. And here you are. I offer an exchange. I'll give this carbine for the Arizona flag. It's in good condition, but it's hard to find cartridges, at least in these parts. Deal?}
{346}{}{Yes, we have a whole club of lovers of antiquity here. Let's change.}
{347}{}{One old thing in exchange for another? No thanks.}
{348}{}{After closing, I'll hang the flag on the wall. Thank you.}
{349}{}{Good luck.}

{350}{}{About the slot machine.}
{351}{}{What is it?}
{352}{}{No, nothing.}
{353}{}{Where did this machine come from?}
{354}{}{Stood in the pantry from the very beginning. I pulled it out, and Uncle Tom cleaned the dust for a couple of caps and launched it.}
{355}{}{What are the rules of the game?}
{356}{}{Use the side buttons to kick the ball with a star so that it bypasses all the slots with points. The longer the ball lasts on the field until it hits the "black hole", the more points you earn. Just be careful, sometimes electromagnetic coils shock players.}
{357}{}{Is there a win for the game?}
{358}{}{It's a fun game. But I promised to give free drinks to everyone who earns 1000 points.}
{359}{}{Is it even possible?}
{360}{}{One almost succeeded. He died of exhaustion without getting a few points.}
{361}{}{I managed to fix the Starball.}
{362}{}{I see. Great job. Here are your 50 caps and another beer from me personally.}
{363}{}{Can I play this?}
{364}{}{Try. Just don't break it.}
{365}{}{No problem.}
{366}{}{I see. Great job. Here are your 50 caps.}
{367}{}{Wow! To beat this slot machine is strong. Here, take a relaxing one at my expense. You should unload your head after such a strain.}
{368}{}{Thank you.}
{369}{}{I could pour more.}
{370}{}{I think I'll go.}

{380}{}{Is that some kind of pendant?}
{381}{}{Yes. One of the residents sold it to pay a debt. It looks like pure gold.}
{382}{}{I know the woman who used to own it. And she says that the pendant was taken away from her.}
{383}{}{Well... listen, it's not my problem. I acquired it honestly. If you want to return it, give me something in return.}
{384}{}{Give me the pendant. Immediately!}
{385}{}{You're in the wrong town, baby. Pay or roll out on the street.}
{386}{}{OK. Have it your way.}
{387}{}{Not interested.}
{388}{}{You'll regret it later!}

{390}{}{The bartender in Garage City just needs a drink.}
{391}{}{It seemed to me that this city was finally bent. Wait a minute, though... Oh, yes, it's probably because of the cattle breeders' tribe. They rebelled and no longer allow caravans to cross their lands.}
{392}{}{Besides the booze, there's nothing relaxing left in the Garage.}
{393}{}{Well, I can share the surplus. But I doubt that the bartender will be enough for a long time. After all, courier delivery is expensive.}
{394}{}{I think everything is not lost at the Garage yet. I'll tell the bartender about your consent.}
{395}{}{Great. But let's talk more about the booze before I go back to Garage City.}

{400}{}{Did you deliver lunch to the mine administrator?}
{1400}{}{Did you deliver lunch to the mine administrator?}
{401}{}{Not yet, sir.}
{402}{}{Hurry up before the food goes missing.}
{403}{}{OK.}
{404}{}{No, sir.}
{405}{}{And I immediately suspected that you couldn't be trusted. Get out of my bar.}
{406}{}{. . .}
{407}{}{A terrible thing. It turned out that the administrator was killed. The whole mine is on edge because of this.}
{408}{}{Oh... that's how... It's sad to hear that. After all, he paid well for the dinners. I hope the new administrator will continue his glorious tradition. And as for you, you can take the lunch as a fee.}
{409}{}{That's not what I wanted. But I won't starve to death.}
{410}{}{Lunch instead of the promised caps? Pray that your greed is not found out in the garrison, you bastard.}
{411}{}{Yes, the order was delivered on time.}
{412}{}{Well done. Here are your bottlecaps. I've already found a new courier, so your services are no longer needed. But you look in anyway.}
{413}{}{Bye, Joe.}

{420}{}{Tell me about your first task.}
{421}{}{We need to take lunch to the administrator at the mine. He sometimes makes an order and pays well for it, but my courier got sick at the wrong time. I will pay two caps for delivery, but it needs to be done in the next six hours.}
{422}{}{No, I have more urgent business.}
{423}{}{OK, I'll do it.}
{424}{}{Then hurry up. Lunch is in this TV dinner box. Don't eat it on the way.}
{425}{}{Accepted.}
{426}{}{And who is your courier?}
{427}{}{This is the boy from the house near the courier service. I don't know what happened to him, but his father won't let anyone see him.}
{428}{}{And what happened to your courier?}

{430}{}{Is there any other work?}
{431}{}{Yes. I'm waiting for a batch of meat from the hunters' camp. But they are late and do not respond by radio. I don't understand what could have happened there. We need to go to the camp and find out the reason for the delays. What if they need some help?}
{432}{}{Okay, I'll do it.}
{433}{}{Sorry, but I can't waste too much time right now. I think they can do it without me.}
{434}{}{Camp Winon is 60 miles to the east, in the forested mountains. Be careful, there are wild animals there.}
{435}{}{Wish me luck.}
{436}{}{I hope these hunters didn't get drunk there from idleness. Otherwise I'll give them a beating worse than any pig-rat.}
{437}{}{There is a conversation. About that hunter camp.}
{438}{}{Is there any news?}
{439}{}{Not yet. I didn't have time to go to camp.}
{440}{}{Remind me which camp you were talking about?}
{441}{}{The camp is called Winon and is located in the northeast.}
{442}{}{Now it's clear. Well, I'll go.}
{443}{}{I've been to Winon Camp. The hunters were killed by savages.}
{1443}{}{I've been to Winon Camp. The hunters were killed by savages.}
{444}{}{What a horror! This camp supplied the city with food. We cannot allow some savages to take away our hunting grounds so easily.}
{445}{}{What should we do then?}
{446}{}{Perhaps Faber will be able to allocate a squad? These idlers from the garrison still have nothing to do, let them work off our taxes. And if not, then in any case it is necessary to drive the savages from this place.}
{447}{}{They need to be driven from this place! It's a pity Faber isn't with us. This is the case when we desperately need an active garrison.}
{448}{}{Okay. Bye.}
{449}{}{Don't worry about it - savages are no longer a hindrance.}
{450}{}{Really? But how did you manage it?}
{451}{}{What can a crowd of savages do against modern weapons? That's right - nothing.}
{452}{}{I managed to turn their own superstitions against them. Just a little trick with amulets.}
{453}{}{Wow, I won't envy those who cross your path. This camp was one of the most important sources of meat for me and for the whole city. Without him, we would have suffered a lot. So now we're all in your debt. Thank you.}
{454}{}{Ordinary people should not suffer because of the mistakes of our leaders.}
{455}{}{You can't put thanks in your mouth.}
{456}{}{I was thinking of paying you 20 caps for the courier service. But considering how this assignment turned out, it won't take me a year to somehow respect you. You know, I'll give you a 50% discount on all my products. That would be fair.}
{457}{}{You're too generous, buddy. But it's time for me to go and restore justice further.}
{458}{}{Don't worry, I'll deal with them.}