{100}{}{Here is a bar visitor.}
{101}{}{You see a regular of the bar. This man is not averse to chatting over a mug of something stronger.}

{200}{}{Hey, hi.}
{201}{}{Bye.}
{202}{}{Hey, great, buddy. Would you buy me a drink? Or do you go into a bar just to watch?}
{1202}{}{Hey, great, girlfriend. Would you buy me a drink? Or do you go into a bar just to watch?}
{203}{}{Hey, it was a cool fight. Would you buy me a drink? Or do you go into a bar just for a fight?}

{204}{}{I don't have many bottlecaps.}
{205}{}{Ha! Miser...}
{206}{}{What's what? Did you call me a miser? Yes? Me?}
{207}{}{Uh, bye.}
{208}{}{Yes. And what?}
{209}{}{It looks like you're looking for rudeness. Do you want to hear a couple? Then: go to hell!}
{210}{}{Eh, nothing.}
{211}{}{Okay, cool it, cowboy. In this city, it's better not to make a fuss about nothing.}
{1211}{}{Okay, lady, chill out. In this city, it's better not to make a fuss about nothing.}
{212}{}{That's the same thing.}

{220}{}{Absolutely, just let me get to the counter.}
{221}{}{I'll take you at your word, cowboy.}
{1221}{}{I'm taking you at your word, girlfriend.}
{222}{}{Uh, bye.}
{223}{}{Here's a nuclear beer. A cheap but sure way to keep the conversation going, right?}
{224}{}{Let's open this bottle of wasteland tequila. A great way to relax, don't you think?}
{225}{}{Thanks for the drink. (pours a glass and falls silent)}
{226}{}{What is it? Something happened?}
{227}{}{Don't... (takes a rough sip) It's been better.}
{228}{}{Hey, listen, since I'm treating you, can you tell me about the city?}

{229}{}{I've only been here a month. And during this time, I realized this: it's better not to make friends in this city.}
{230}{}{This can be said about any foreign city.}
{231}{}{You sound like you've seen a lot.}
{232}{}{I didn't ask for your opinion. But... your truth.}
{233}{}{Then will you tell your story?}
{234}{}{Heh, I wish it wasn't like that.}
{235}{}{Then will you tell your story?}
{236}{}{I came here with my boyfriend. Everything was going well. We collected everything in the ruins and paid the colony a "tax" for it.}
{237}{}{[Next]}

{238}{}{But when there were not enough caps, Karl got into debt. Further - more. And in the end Faber gave the order to put Karl behind bars. Now he's there and I'm here. And I don't know what to do.}
{239}{}{Is he there for life?}
{240}{}{Faber obliged him to one year of hard labor. But Karl will not survive such a period. Me too.}
{241}{}{Is there any way to get him out of prison?}
{242}{}{Only if you pay off part of the debts. And there's nowhere to get so many caps.}
{243}{}{A sad story. Well, come on.}
{244}{}{Yeah. Happily.}
{245}{}{[Leave a girl alone with a bottle]}
{246}{}{What are you going to do?}
{247}{}{They won't let me live here after this story. We need to go somewhere else. Maybe I'll go back to the south.}
{248}{}{Remind me, what happened to your boyfriend there?}