{100}{}{Here is Preacher Hiram.}
{101}{}{You see a man in a shabby cassock.}
{102}{}{What... what are you doing...}
{103}{}{...kx-x... hr-r-r...}
{104}{}{Heretic! The technology of the Ancients is not for simple walks. This armor belongs in our main temple, in Phoenix.}

#The first dialog
{200}{}{Hello, traveler. It was a big mistake on your part to come to this city.}
{1200}{}{Hello, traveler. It was a big mistake on your part to come to this city.}
{201}{}{Why is that?}
{202}{}{Flagstaff is one of the few places in the wastelands where order is accepted... in a way. Some outsiders in this city are condemned to forced labor, and some to the death penalty in order to become fuel for the Sacred Fire. But ultimately it's up to you.}
{203}{}{Clearly. I want to talk to you.}
{204}{}{Okay, I'll take that into account. Goodbye.}
{205}{}{Hello, traveler. What a blessing that the rays of the Sacred Fire sent you to this city. I hope you won't condemn the local order?}
{206}{}{What other orders?}
{207}{}{Hello, traveler. Is there anything I can do to help you?}
{208}{}{Perhaps. I'm new here, I could use some advice.}
{209}{}{Well, not the best start for dating. Learn to accept faith as it is. Words are just a shell for meaning.}

#Repeat dialog
{210}{}{How can I help?}
{211}{}{Goodbye.}
{212}{}{Who are you and what is this place?}
{213}{}{This is the temple of the Great Sacred Fire. And I am Hiram, his priest. Welcome to His radiant abode.}
{214}{}{Why so many pretentious words?}
{215}{}{Well... to be honest, I'm already forgetting the days when I said otherwise. The teaching of the Sacred Fire changed my whole life.}

# About knowledge
{216}{}{Is your temple somehow useful to Flagstaff?}
{217}{}{Oh, of course! Let's start with the fact that Flagstaff is built on the roof of our church... or rather, the main temple, which is located in Phoenix.}
{218}{}{Why do you need this?}
{219}{}{Uranium is one of the sacred resources inherited from our ancestors. We collect its radiant energy and use it for the glory of the Sacred Fire...}
{220}{}{More?}
{221}{}{We teach literacy and pre-war knowledge to everyone who expresses such a desire. And I, a humble servant of the Sacred Fire, am endowed with the gift of healing.}
{222}{}{I don't think you're doing this for free.}
{223}{}{Skeptics! Skeptics are all around! However, I have to admit - it is. To get closer to the ancient wisdom, you need to pay with caps or become a member of our church. After all, not all people are ready to accept the knowledge of the Old World.}
{224}{}{Clearly. Tell me more.}
{225}{}{That's the end of it. Goodbye.}
{226}{}{I would like to share your knowledge.}
{227}{}{Oh, undoubtedly. But I'm afraid I can't accept you as a brother in faith until I get consent from the main temple. That is, you will have to pay. Can you read?}
{1227}{}{Oh, absolutely. But I'm afraid I can't accept you as a sister in faith until I get consent from the main temple. That is, you will have to pay. Can you read?}
{228}{}{Yes.}
{229}{}{I can barely read the syllables.}
{230}{}{So the secrets of the Sacred Fire will not reach your mind! We will start with the basics - with literacy. One lesson will cost a hundred caps.}
{231}{}{Here are the bottlecaps. I want to get smarter!}
{232}{}{Not now. Answer the other questions first.}
{233}{}{I can't afford such expenses yet.}
{234}{}{Well, that's enough for today. From now on, you will be able to learn pre-war knowledge yourself if you practice reading and writing more. And don't forget who revealed this sacrament to you!}
{235}{}{So... a lot... information. I already have a headache. Let's take a break.}
{236}{}{Anyone should not be allowed to enter the mysteries of the Sacred Fire. After all, this knowledge can be used both for good and for harm. Prove your devotion to our faith - make a solid donation. 300 caps - that's the price.}
{237}{}{I think I've had enough donations for your church.}
{238}{}{Then I want to make a donation.}
{239}{}{Oh, yeah. Really. Well, I have to keep my word. Welcome to my abode. Ancient writings are kept there. Treat them with care and respect.}
{240}{}{Great, there will be something to read before going to bed.}
{241}{}{Thank you, your benefactor knows no bounds!}
{242}{}{Enough about the temple, now I know enough.}

# About faith
{245}{}{Tell us about your faith.}
{246}{}{I can talk about this forever. The world was created by the Sacred Fire that fell to earth a hundred years ago. He incinerated the sinful people and left only small families for the human race to continue its existence.}
{247}{}{[Next]}
{248}{}{Now we, the descendants of the survivors, are trying to build a New World devoid of the mistakes and vices of the past.}
{249}{}{Who are we?}
{250}{}{Our church and its followers, of course. Other people, alas, have forgotten the lessons of the past. We are called to reason with them.}
{251}{}{I thought it was a war.}
{252}{}{This is the trouble of many living people. You have lost faith in the soul and have condescended to simple material truths. The Great War is only a disguise of what the Sacred Fire was. It was not nuclear bombs that punished humanity, but human stupidity and greed. That's the point.}
{253}{}{How far has your faith spread?}
{254}{}{Our main temple is in Phoenix, but it's not that important. After all, many tribes carry faith in the Sacred Fire, calling It by other names and interpreting ancient events differently. That's why our church is expanding so easily. Our teaching is known throughout Sonora.}
{255}{}{How do the colonists relate to this faith?}
{256}{}{Most of the inhabitants believe in the Sacred Fire or pretend to believe. But alas, Faber's mercenaries are mostly godless, and there are skeptics among the population. Do not worry, the Sacred Fire will open their eyes sooner or later. I am more concerned about those who are hiding from His X-ray vision.}
{257}{}{}
{258}{}{Allow me, Holy Father, to stay with you a little longer.}
{259}{}{Eh, goodbye.}

#Donation
{260}{}{I would like to help your church.}
{261}{}{Any donation will bring us closer to the spirit of the Sacred Fire. What can you offer?}
{262}{}{Unfortunately, nothing of value. But I have a bunch of questions.}
{263}{}{Nothing today. Goodbye.}
{264}{}{Only 10 caps.}
{265}{}{Here are 50 caps.}
{266}{}{As many as 100 caps.}
{267}{}{(quickly hides a handful of caps in the folds of his cassock) Thank you.}
{268}{}{(hastily pours your caps into a leather pouch on his belt) Truly, your generosity knows no bounds!}
{269}{}{(pours your caps into a leather pouch on his belt) May the Sacred Fire be with you!}

#Treatment
{270}{}{I need treatment.}
{271}{}{In the name of the Sacred Fire, what happened?}
{272}{}{Injury.}
{273}{}{Injury.}
{274}{}{Irradiation.}
{275}{}{Poisoning.}
{276}{}{However, nothing significant.}
{277}{}{Of course, the church will help you, but don't you want to reward her with a small donation? It 's about the amount in }
{278}{}{ caps.}
{279}{}{Here are the bottlecaps.}
{280}{}{I don't have so many bottlecaps!}
{281}{}{Very sorry. In that case, I can't do anything to help.}
{282}{}{How so...}
{283}{}{No need, it will heal itself.}
{284}{}{Praise the Sacred Fire for giving you a little more time!}
{285}{}{Uh, that's much better.}
{286}{}{}
{287}{}{ The man in the bag! Gee!}
{288}{}{Are you talking about my cassock? (shakes his head) Oh, poor Atom child, I feel sorry for you. I would like to help you regain the Atoms of Consciousness you have lost, but I am powerless here. Go outside, Child of Radiation.}
{289}{}{Street? The street is what I love.}

#Receiving a letter of recommendation
{290}{}{I can help the church a lot more if I get closer to its top leadership.}
{291}{}{Perhaps. It is in my power to write a letter of recommendation in your name for the main temple. But it looks like you haven't penetrated our faith enough yet.}
{1291}{}{Perhaps. It is in my power to write a letter of recommendation in your name for the main temple. But it looks like you haven't penetrated our faith enough yet.}
{292}{}{As you say.}
{293}{}{Perhaps. It is in my power to write a letter of recommendation in your name for the main temple in Phoenix. This will be the beginning of your thorny path. Are you sure you're ready to accept this burden?}
{1293}{}{Perhaps. It is in my power to write a letter of recommendation in your name for the main temple in Phoenix. This will be the beginning of your thorny path. Are you sure you're ready to accept this burden?}
{294}{}{Undoubtedly!}
{295}{}{I need to think.}
{296}{}{Very good. Very. Here's the letter. Take care of it until you come to the main temple. This will be your first test.}
{297}{}{I will carry this letter in the name of the Sacred Fire! Well, or something like that.}
{298}{}{Taking into account your reputation in Flagstaff, I doubt that you will be of use in the main temple.}
{299}{}{}

#Quest - start:
{300}{}{Are the bottlecaps the only problem?}
{301}{}{Many despise our faith, but usually keep it to themselves. Some are not so restrained.}
{302}{}{Is someone threatening you?}
{303}{}{Someone unknown commits despicable acts at night - draws crosses on the walls, sets fires, dirties the door with mud. Obviously, he is trying to intimidate me and persuade me to escape from the colony. But I did not manage to meet this infidel face to face.}
{304}{}{Maybe I can find him. It's interesting to find out why he disliked you so much.}
{305}{}{I don't want to get involved in such dark matters. Let's change the subject.}
{306}{}{I would be extremely grateful.}
{307}{}{Okay.}
{308}{}{I'm not going to "plunge anyone into darkness."}

#Quest - detection of a saboteur:
{310}{}{Let's talk about night stalking.}
{311}{}{Did you find out anything?}
{312}{}{Not yet, but I want to ask about something else.}
{313}{}{Nothing new. I'll come back when I know more.}
{314}{}{I managed to catch this vandal by surprise. It turned out to be a balding colonist from a house to the south.}
{315}{}{Festus... A hopeless victim of atomic fission.}
{316}{}{Do you know each other?}
{317}{}{He came to the sermons, but could not penetrate the radiant truths of Fire. When the time came, Festus was blinded by anger and pride. And I closed the doors of the temple before him.}
{318}{}{What happened?}
{319}{}{Festus' child became a quantum of discord. I begged to send this gifted youngster to study at the temple, but Festus refused in a rage. Alas, even in Flagstaff, many do not understand the value of knowledge and rely only on brute force.}
{320}{}{[Next]}
{321}{}{When the boy was seized by a radiant illness, I promised free treatment if the father changed his mind and gave his son to the temple. But Festus' hatred proved irresistible. Obviously, he's taking revenge now.}
{322}{}{What can I do?}
{323}{}{To reason with Festus so that he would abandon the threats and give the child to the temple? This is extremely difficult.}
{324}{}{It remains... murder?}
{325}{}{Uh, I'll try the first option.}
{326}{}{I need time to think.}
{327}{}{When nuclear fuel becomes harmful, it is isolated and plunged into darkness. Otherwise it will be dangerous to others.}
{328}{}{Well, may the Sacred Fire help you.}
{329}{}{Uh, okay.}

#Quest - quest completion:
{330}{}{Let's talk about the Festus problem.}
{331}{}{I'm listening.}
{332}{}{I would like to ask questions about something else.}
{333}{}{I'll come back when I solve the problem.}
{334}{}{I managed to convince Festus. He will give his son to study and stop the persecution.}
{335}{}{Truly great is the Power of the Atom! Festus is waiting for public repentance, but his son has a great future as a scribe and scientist in the temple of Fire. Great job.}
{336}{}{It happened to Festus... accident. He's not a problem anymore.}
{337}{}{May the Sacred Fire incinerate his soul! Festus could not be reformed anyway, and his conversion to our faith would only serve to harm. But his son has a great future as a scribe and scientist in the temple of Fire. Good job.}
{338}{}{How can I reward you for your efforts?}
{339}{}{Do not mention it. All for the sake of faith.}
{340}{}{I need medications - Radaway and two stimpacks.}
{341}{}{Can I count on a 20% discount for treatment?}
{342}{}{I need caps to release my fellow tribesmen from prison.}
{343}{}{I have a big dream - to get to the main temple of Fire and turn to its leader.}
{344}{}{I need access to your library.}
{345}{}{[Next]}
{346}{}{}
{347}{}{But how to do this without drawing the wrath of the rest of the colonists?}
{348}{}{Hmm. Festus suffers from the effects of radiation. It is enough to throw him something highly radioactive to speed up the process of decomposition of his soul into atoms. Surely there is such an object in the uranium mine.}
{349}{}{An accident? Lethal radiation dose? Poison? I am not an expert on such issues.}

{350}{}{Thank you.}
{351}{}{May the Flame of Heaven protect you. At the next sermon I will tell you about your benefactor. I'm sure it will raise your reputation in the eyes of ordinary colonists.}
{352}{}{Well, it's deserved. Take it.}
{353}{}{Well, it's deserved. You can count on... "discount".}
{354}{}{I can only offer 100 caps, as parishioners are stingy with donations. However, this is enough to get Faber to talk.}
{355}{}{Hmm. I can write a letter of recommendation to the main Fire temple in Phoenix. But still your merit is not so great. We'll have to make some more donations.}
{356}{}{This collection of priceless pre-war knowledge requires special treatment. Treat him with respect.}
{357}{}{Forget about Festus and his baby. You're late.}
{358}{}{Is he cured again? It seemed to me that this problem would never be solved without my intervention. Well, with great regret I have to give up my demands.}
{359}{}{This will be a lesson to you.}

#Treatment of Festus' son
{360}{}{Festus' son needs treatment.}
{361}{}{And I will gladly help him if he agrees to visit the temple.}
{362}{}{Okay.}
{363}{}{We've already eliminated Festus. It's time to fulfill the promise.}
{364}{}{Delaying the process will not please the main temple of Fire.}
{365}{}{Your integrity will only turn people against us.}
{366}{}{The temple will increase its reputation if it concedes in this situation.}
{367}{}{Then I'll start treatment as soon as I'm ready.}
{368}{}{That's good.}
{369}{}{I'll stay on my own.}
{370}{}{Expected...}
{371}{}{Why such unscrupulousness?}
{372}{}{It's hard to change adults. And often it doesn't make much sense. It is through children that the roots of faith must be planted. And the treatment will be forgotten. After all, people are not distinguished by gratitude now.}
{373}{}{I see.}

#Dialogue corrections after the events at the Phoenix Temple
{400}{}{Leave me in the po... Oh, it's you. Nevermind.}
{401}{}{Is someone bothering you?}
{402}{}{The colonists became intolerant of my faith when they learned about the events in the south. Some people want to expel me from the city. But from now on I have nowhere to go.}
{403}{}{Looks like you're in big trouble. I'd better get out of here.}
{404}{}{Greetings to you. I am glad to see a brother in faith in my monastery. Welcome to the radiant Flagstaff!}
{1404}{}{Greetings to you. I am glad to see a sister in faith in my monastery. Welcome to the radiant Flagstaff!}
{405}{}{How did you find out about my promotion?}
{406}{}{For our faith, distance is an insignificant barrier. The Messengers of Rebirth have reported about you.}
{407}{}{Oh yes, the postal service...}
{408}{}{}
{409}{}{}
{410}{}{So how can I help, brother?}
{1410}{}{So how can I help, Sister?}
{411}{}{Stop! And what do you, brother in faith, know about what happened in Phoenix?}
{1411}{}{Stop! And what do you, a sister in faith, know about what happened in Phoenix?}
{412}{}{Uh, the same as you.}
{413}{}{I blew up the temple of Fire. Because of him, a tragedy has befallen the Villa, so taste the same.}
{1413}{}{I blew up the temple of Fire. Because of him, a tragedy struck the Villa, so taste the same.}
{414}{}{Hmm. Very sorry. Very.}
{415}{}{Uh, I think I'll go.}
{416}{}{That's how. It was revenge... What a barbaric motive! But if I am not a member of the cult now, then it remains to throw off the robe of a preacher and get away from Flagstaff. Your action gives me the right to start all over again. Maybe it's not so bad.}
{417}{}{Well, come on.}
{418}{}{I have received news of your expulsion from the Brotherhood of Fire. I need to know the reasons.}
{419}{}{Do you need reasons? Shove them up your ass, sectarian!}
{420}{}{I will not tolerate abuse of my faith! The Sacred Fire is not a fiction. He was actually a hundred years ago! If even after all my sermons you do not believe the obvious, we can only hope for your speedy splitting into atoms.}
{421}{}{Well, well.}
{422}{}{Your faith preaches the wrong ideas.}
{423}{}{Are you saying there was no Sacred Fire? And that we shouldn't restore the world to its former greatness by correcting its arrogant mistakes? What should we do then? Still dragging out a miserable existence among the ruins and barren wasteland? Then stay in your blissful blindness.}
{424}{}{Well, well.}
{425}{}{I still believe in Fire and still long for Rebirth, brother.}
{426}{}{Your lies are only an outrage on faith. Get out of Flagstaff until the Fire opens your eyes to the truth.}
{427}{}{Well, well.}
{428}{}{Can I trust you... brother? Perhaps you are not lost to our mission yet. Go ahead. And show your devotion to the faith with real deeds. Under the flag of the temple or without it.}
{1428}{}{Can I trust you... sister? Perhaps you are not lost to our mission yet. Go ahead. And show your devotion to the faith with real deeds. Under the flag of the temple or without it.}
{429}{}{Okay.}
{430}{}{By your very existence you are already helping the church. But we always need bottlecaps from any hands.}
{431}{}{Anyone should not be allowed to enter the mysteries of the Sacred Fire. After all, this knowledge can be used both for good and for harm...}
{432}{}{Of course. And I have already proved my devotion to the faith.}
{1432}{}{Of course. And I have already proved my devotion to faith.}
{433}{}{A strange question for a fellow believer. I am Hiram, the priest of this temple.}
{1433}{}{A strange question for a sister in faith. I am Hiram, the priest of this temple.}
{434}{}{Oh, absolutely. But can you read?}