{100}{}{This is Roy Faber.}
{101}{}{You see the colony manager. It's hard for you to bear his heavy gaze.}
{102}{}{Your reign is over, bastard.}
{103}{}{Your reign is over.}

#The first dialog
{200}{}{(looks at you appraisingly, as if he wants to understand how much you are worth) I haven't seen you before. Who are you?}
{1200}{}{I'm sorry for my ignorance, but ladies should not wander in such places without permission. I haven't seen you before. Where are you from?}
{201}{}{I will not introduce myself to the slaveholder.}
{202}{}{Hmm? No one has been impertinent to me for a long time. Some tried, but they didn't live long. For your courage, I'll give you a minute's head start. I'm interested in listening.}
{203}{}{No talking. Now I see that you need to be killed!}
{204}{}{Seriously?}
{205}{}{I'm looking for my people, the peasants of the Villa. They say they are in your pen.}
{206}{}{(pronouncing the words with indifference) Yes, these dirty peasants are here.}
{207}{}{But why do you keep them in captivity?}
{208}{}{I already wanted to shoot you. But I remembered in time that I had met a couple of ghouls in Phoenix. Are you one of them? Then what the hell are you doing here in Flagstaff?}
{1208}{}{I already wanted to shoot you. But I remembered in time that I had met a couple of ghouls in Phoenix. Are you one of them? Then what the hell are you doing here in Flagstaff?}
{209}{}{I just want to talk.}

{210}{}{What do you say?}
{211}{}{Let me talk to my relatives.}
{212}{}{I demand the release of the residents of the Villa.}
{213}{}{Why do you need so many prisoners?}
{214}{}{Is there a job for me here?}
{215}{}{}
{216}{}{Let's go back.}
{217}{}{Let's talk about something else.}
{218}{}{Let's change the subject.}
{219}{}{That's it, I'll go.}

#Admission to the paddock
{220}{}{And that's it? A minute of conversation will cost you 100 caps.}
{221}{}{Here are the bottlecaps. Can I go into the pen now?}
{222}{}{Wait, tell me about something else first.}
{223}{}{I don't have that many caps. I'll be back when I collect it.}
{224}{}{No problem. I guarantee that you will be let in and let out... if you behave yourself.}
{225}{}{I'll try.}
{226}{}{I don't have that many caps. Give us just a minute!}
{227}{}{I named my price. If you can't pay, then get lost.}
{228}{}{Ugh...}
{229}{}{You peasants have an amazingly developed sense of gregariousness... Okay, go ahead. But if you behave badly, you will stay there forever.}

#Slave theme
{230}{}{Here, in penal servitude, these useless scum of society will be able to give at least some benefit.}
{231}{}{What kind of hard labor are we talking about?}
{232}{}{Uranium mines in the north, caravans in the south, Flagstaff restoration, sometimes orders come from Phoenix... I can't remember everything.}
{233}{}{So this is not a slave pen, but a prison?}
{234}{}{Until recently, it was. Half of the garbage in our colony has fallen into the clutches of lawyers in the southern lands. Then they were brought here. Bandits, rapists, card debtors - we will find a use for everyone.}
{235}{}{Call it what you want, but you keep people against their will.}
{236}{}{Look around - Flagstaff is thriving thanks to our prison. We are the only force that can restore order here. Besides, the mere mention of us scares people away from crimes. Still don't trust me? Then go to hell.}
{237}{}{However, the residents of the Villa are not criminals.}
{238}{}{It so happened that there were not enough convicts, and the fastest way to find them replenishment was to recruit local savages. The villa was on the way. Great stuff, it was hard to resist.}
{239}{}{Is the shortage of convicts so significant?}
{240}{}{A redneck like you has a narrow view of things. Do you know about the cities in the south? A real civilization is being revived there. As before.}
{241}{}{And?}
{242}{}{Flagstaff supplies uranium, and our convicts are the main working link in this chain. There will be no progress in the south without us. We are making history, and now your miserable village can become a part of it. You will do at least something useful for the rest of the world.}
{243}{}{However, you don't look like lawyers yourself.}
{244}{}{Do you think there's a difference nowadays? Lawyers live at the expense of criminals. They take taxes from settlements in exchange for protection from rebels. Why are we worse? (picks up the brass knuckles and examines it with emotion) Power gives power. And how you dispose of it depends only on you.}
{245}{}{Why do we need uranium ore?}
{246}{}{Oh, yes, the hillbillies have already forgotten the Old World. Several generations ago, people received energy from radioactive ore. With its help, old technology worked - from an ordinary light bulb to the most advanced electronics. In large cities, remnants of these technologies are still used.}
{247}{}{Who buys it?}
{248}{}{There are several buyers in the south, the main one is the cult of fire worshippers.}
{249}{}{There are several buyers in the south. Previously, the bulk of the goods were bought by fire worshippers. Now it has become a little more difficult with clients.}

#Liberation
{250}{}{I don't see any reason to do this.}
{251}{}{I managed to solve your problems in the mine.}
{252}{}{Oh, yes, I've already been informed. It's hard to believe that some peasant managed to solve old painful problems. Okay, I'm keeping my word. Go to the pen and please the tribesmen. They are free.}
{1252}{}{Oh, yes, I've already been informed. It's hard to believe that some peasant woman managed to solve old painful problems. Okay, I'm keeping my word. Go to the pen and please the tribesmen. They are free.}
{253}{}{By all means.}
{254}{}{So, such a reason should appear.}
{255}{}{Great, let's make a deal. There are several problems that need to be solved. If you manage, I will release those few peasants who remained in the pen.}
{256}{}{What do you need?}
{257}{}{I need to restore the normal operation of the mine. Talk to the administrator, he will bring you up to date.}
{258}{}{I'll think about it, but first I need to ask a couple of questions.}
{259}{}{Great, I'll talk to him and come back later.}
{260}{}{What are you talking about?! The mines are destroyed, and it will take months to clear them! Does this look like a problem solver? No. Now get out!}
{261}{}{That's how it is...}
{262}{}{Remind me about our deal.}
{263}{}{Don't you understand the first time? Go to the administrator at the mine. He will tell you what to do.}
{264}{}{You'll see in a week when the peasants will infect the whole colony.}
{265}{}{What the hell are you talking about?}
{266}{}{About the "wasteland disease", of course. The residents of the Villa are immune to it, but the colonists are unlikely. Haven't you heard?}
{267}{}{Damn, but in the south whole settlements died out from some kind of infection... What can you prove?}
{268}{}{When the disease manifests, you'll see for yourself. Decide for yourself whether it's worth the risk.}
{269}{}{Damn it... So, I'll let your peasants go, but to get out of the colony right now!}
{270}{}{That's the right decision.}
{271}{}{Well... the peasants are sick. Can't you see?}
{272}{}{If you continue to put pressure on my brain, you will end up even worse than your fellow tribesmen.}
{273}{}{Hey, take it easy...}

{274}{}{They say someone is sniffing out information among my people. I don't like it. If I get at least one more denunciation against you, you will go straight to the gallows.}
{275}{}{This is some kind of mistake! Your informants are lying!}
{276}{}{Uh... okay.}
{277}{}{Shut up! This colony is based on strict rules. If you break one thing, you get punished. Violated the second - and you get a noose around your neck. And I set the rules here.}

{278}{}{(screaming) Rat brat, do you even realize that the whole Flagstaff is under threat because of a handful of dirty peasants! Years of work on the arrangement and control of the whole city, the hopes of the whole south for prosperity - all this is down the drain for the Brahmin. Come on, show ALL your will to live!}
{279}{}{So, wait a minute...}

#Quests
{280}{}{Maybe I can work off these bottlecaps?}
{281}{}{Perhaps. There is one annoying problem that has been bothering me for a long time.}
{282}{}{Tell me more.}
{283}{}{Several patrols disappeared in the city ruins to the east. They say they heard a gunfight. Find the reason and fix it - I'll pay 300 caps for it.}
{284}{}{It's a deal. I will come back when I solve this problem.}
{285}{}{I'll think about your offer.}
{286}{}{Okay, but if I have to kill someone, then I'll pass.}
{287}{}{Why won't your mercenaries do it?}
{288}{}{The ruins of the old city are too confusing and dangerous. I'll lose more people if I send them to scout. But now I have you... What is it? Are you already refusing?}
{289}{}{Then I have no choice. You're going to die!}
{290}{}{A ranger? An ordinary criminal who fancies himself a hero. Well, not a bad job. Here are your 300 caps.}
{291}{}{Just like that? For you, a person's life is really worth nothing.}
{292}{}{Great.}
{293}{}{Exactly. Including *your* miserable worthless life. Until now, the surrounding savages only cared about personal survival. I have a colony - the only place in Sonora where a person lives for something *more*... However, you won't understand it.}
{294}{}{Yeah. Bye.}
{295}{}{A ranger? An ordinary criminal who fancies himself a hero. Well, not a bad job. Here are your 200 caps.}
{296}{}{Hey, we agreed on 300!}
{297}{}{Your memory is failing you. You won't get any more.}
{298}{}{That's how it is... Okay, bye.}
{299}{}{Any suggestions what it could be?}
{300}{}{Most likely, another healthy creature or a gang has settled in the ruins. You'll know for sure when you find the missing patrols.}

{301}{}{One of your subordinates owes the bar 100 caps.}
{302}{}{I've heard these rumors, but I'm not going to interfere because of such a small amount.}
{303}{}{Then I'll step in.}
{304}{}{Hmm. As you wish. I will give a command to my people not to touch you during the fight.}

{305}{}{I want to get my reward. A saboteur ranger has settled in the ruins, but now he is dead.}
{306}{}{A saboteur ranger has settled in the ruins, but he has already left Flagstaff.}
{307}{}{A ranger? An unexpected but predictable case. I guessed that sooner or later we would have problems with these narrow-minded lawyers.}
{308}{}{What about payment?}
{309}{}{The result is too insignificant to pay for it. But I'll pay you 50 caps for the information.}
{310}{}{Hey, we agreed on 300!}
{311}{}{Anything is better than nothing.}
{312}{}{Our deal meant *fixing* the problem, not postponing it. Better take the bottlecaps and get out before I change my mind.}
{313}{}{Gr-r-r!}
{314}{}{Okay, I'll leave.}
{315}{}{If this is a joke, then you can lose your life for it. Get out of here before I change my mind.}
{316}{}{Okay, I'll leave.}
{317}{}{It's hard to believe that a peasant managed to solve all these problems. I am even more puzzled by your diligence. After all, your tribesmen have been free for a long time.}
{1317}{}{It's hard to believe that a peasant woman managed to solve all these problems. I am even more puzzled by your diligence. After all, your tribesmen have been free for a long time.}
{318}{}{It's just that people at our Villa keep their word. If I promise to do a job, I do it. Adios, the overseer.}
{319}{}{Life in the village is boring. I just wanted an adventure. Come on, boss.}
{320}{}{That's your problem. I am interested in other questions.}
{321}{}{You're just sick in the head. You need to be finished!}
{322}{}{And there may be some truth in your words. I need to think about them.}
{323}{}{Slavery remains slavery, than you don't cover it up. And I'll have to stop you before it's too late.}
{324}{}{Your words make me think. Can you tell me anything else?}
{325}{}{The Winon camp is overrun by savages. Need help!}
{326}{}{Damn savages! Again, they get in the way at the most inopportune moment. Hunting grounds are too important for the city. We'll have to allocate people to clear the camp.}
{327}{}{Great idea. I'll join you on the spot, too. See you later.}
{328}{}{It's not worth it yet. Perhaps I can figure it out without using the brute force of your mercenaries.}

{330}{}{Who! I? Uh... well...}
{331}{}{I don't need idiots here. Get lost.}
{332}{}{Prova... ah! Yes, yes, I'm going home. The villa is my home, yes.}
{333}{}{Wait... What are you saying? We recently received a batch of slaves from the Villa. Are you from there too? No wonder they left you at home - you can't even trust such idiots with a shovel.}
{334}{}{What is a lop-pat?}
{335}{}{I think you're looking for your friends. They're here in the pen. But if you want to see me, you'll have to fulfill a little request for me. Do you understand?}
{336}{}{Oh! Yes! Friends!}
{337}{}{Yes, your friends... Listen to me, you moron piece. Go to the mine and go down. There's a big rat there. Kill the rat and I'll take you to your friends. Understand?}
{338}{}{No, I want to go to friends now!}
{339}{}{A rat! Kill the rat! Kill!}
{340}{}{You won't see them until you kill a big rat in the mines. And don't make me angry anymore.}
{341}{}{Ooh, evil uncle.}
{342}{}{A rat! Kill the rat! Kill it!}
{343}{}{Mine... this... it's all right. Yes, there are no problems.}

{344}{}{I am an honorary member of the Brotherhood of Steel. And I demand: let these blessed ones go, otherwise the order will bring down its wrath on you.}
{345}{}{P-fu. Is everyone in your Brotherhood so pompous? Okay. But why such a change? After all, you yourself demanded the implementation of the plan by all available means.}
{346}{}{None of your business. So the command decided.}
{347}{}{Okay, I don't want any problems. I will let the peasants go.}
{348}{}{Great. Let's get the paperwork done.}
{349}{}{Make sure it doesn't happen again.}

{350}{}{The warden whips the prisoners.}
{351}{}{I know. It is for his firm hand that I appreciate him. She won't flinch when she has to shoot on the spot.}
{352}{}{Well, I won't argue with that.}
{353}{}{But he doesn't just hit, he cripples. And without serious reasons.}
{354}{}{Okay, slow down. What are you talking about?}
{355}{}{The whip forces the administrator to fake reports and write off injuries as accidents.}
{356}{}{I don't like it at all anymore. I put Knut in charge of the order, relying on his inflexibility. And if he really allows himself too much, then I will not leave it so easily. Workers are too expensive to spend so carelessly.}
{357}{}{Why don't you do a check and fire this pest?}
{358}{}{I'm not asking for your opinion on what I should do. But if you're not lying, then it won't be easy to replace the Whip. I'll be looking for a replacement for him, but I don't think I'll find one anytime soon... Here, take five caps for the information.}
{359}{}{Thank you, sir.}
{360}{}{[Leave silently]}
{361}{}{About the Whip. I know one suitable candidate...}
{362}{}{...Okay. I don't mind Knut resigning from his post. It will be fun to see how one warden moves another. Although I still don't understand why you care about it.}
{363}{}{Yes, nothing.}
{364}{}{I just can't stand injustice.}