{100}{}{You have a child in front of you.}
{101}{}{You see a child of a colonist family.}
{102}{}{I'll tell everyone that you're pushing!}
{103}{}{Z-z-z...}
{104}{}{It's there, on the ruins at the entrance to the city.}

#Retaliatory remarks
{110}{}{Hi!}
{111}{}{Will you play with me?}
{112}{}{And you're not scary at all.}
{113}{}{I have nothing to do.}
{114}{}{I'm not allowed to go to the ruins.}

{115}{}{Don't come near me!}
{116}{}{I was told that I can't talk to you.}
{117}{}{You're bad!}
{118}{}{Leave me alone, or I'll scream.}
{119}{}{Do you really eat children?}

{120}{}{Hi.}
{121}{}{Hi.}
{122}{}{Hi there.}
{123}{}{Hi.}
{124}{}{Hi there.}

{200}{}{Uh, hello. Are you looking for someone?}
{201}{}{No, no one, calm down.}
{202}{}{Yes. I'm looking for little thieves like that.}
{203}{}{We didn't steal anything! It wasn't us!}
{204}{}{Really?}
{205}{}{Yes... true...}
{206}{}{I know you stole Mrs. Brandley's personal belongings. But don't worry - I won't turn you in.}
{207}{}{Well... We just wanted to help Dad. He doesn't have the caps to pay for the house, so we might get kicked out of here. And this nasty aunt always had caps. But there was very little in the wallet.}
{208}{}{Where did you put the rest of the stuff?}
{209}{}{Stop lying, a trifle, otherwise it will be worse.}
{210}{}{We dumped them in a landfill near the entrance to the city. There were some love notes and bills... And you won't tell anyone, will you? We just wanted to help Dad, we won't do that anymore!}
{211}{}{You can sleep in peace, guys. I understand everything.}
{212}{}{How many caps were there in her purse? Give them all, and then I'll forget about your offense.}
{213}{}{Whatever you say, sir... Here are five caps.}
{1213}{}{Whatever you say, ma'am... Here are five caps.}
{214}{}{That's the same thing.}