{100}{}{You see a colonist.}
{101}{}{You see a citizen of the colony.}
{102}{}{I want to sleep, leave me alone.}
{103}{}{Z-z-z...}
{104}{}{...}
{105}{}{ }
{106}{}{*Yawns*}
{107}{}{Where did you come from?}
{108}{}{I want to sleep, leave me alone.}

#Floating replicas (they are responses when trying to speak)
{110}{}{Do you know about the curfew? You can't go outside after it.}
{111}{}{So far it's the safest city in Arizona.}
{112}{}{Sometimes I miss the Phoenix night lights.}
{113}{}{My hamstrings tremble when I see Faber.}
{114}{}{They say there are bandits in the abandoned ruins.}
{115}{}{When will the new stagecoach arrive?}
{116}{}{Never trust a servant.}
{117}{}{I'm a little afraid to go into the garrison area.}
{118}{}{Don't forget about the evening sermon.}
{119}{}{Taxes are high here, but it's worth it.}
{120}{}{Humphries Peak has a great view.}

{150}{}{Now I'm afraid to go outside.}
{151}{}{Even in the den of scorpions is safer than here.}
{152}{}{We shouldn't have moved here.}
{153}{}{How could we be wrong about the Faber Swarm?}
{154}{}{They say there are bandits in the suburbs.}
{155}{}{There are fewer and fewer caravans.}
{156}{}{Hire a maid? Well, no.}
{157}{}{Not a step into the garrison now.}
{158}{}{Let this preacher bring the bandits to reason first.}
{159}{}{And what do we pay taxes for?}
{160}{}{As soon as it smells fried, I'll run to Humphries Peak.}