{100}{}{You see a guard in front of you.}
{101}{}{You see the guard. He seems tired after a long flight.}

{110}{}{What would you like to do before the shipment?}
{111}{}{Do you want to play "Caravan"?}
{112}{}{Wake me up when the packing starts.}
{113}{}{In the south, this ore is very much expected.}
{114}{}{Each shopping trip can be the last.}
{115}{}{I don't know what I would do if there wasn't a colony here.}
{116}{}{Talk to the chief, I'm just a security guard.}
{117}{}{We usually don't take fellow travelers.}
{118}{}{Dust storms kept us in San Brahmin for a whole week.}
{119}{}{This flight is going to be tough.}