{100}{}{This is merchant Joshua.}
{101}{}{You see the caravan manager. His skin has acquired a bronze tan after countless days spent under the sun.}
{102}{}{Have a good trip.}
{103}{}{This is Phoenix - the largest city on the wastelands. You always have to be on your guard here.}

{200}{}{What is it this time?}
{201}{}{Bye.}

#The first dialog
{210}{}{Looking for someone?}
{211}{}{Perhaps. Who are you?}
{212}{}{He's not here. Bye.}
{213}{}{I don't think we can do business with you. We only work with the administration of this mine.}
{214}{}{And what are you doing?}
{215}{}{As a rule, we transport heavy loads. And what?}
{216}{}{Hmm, I just have questions on this topic.}
{217}{}{Nothing. Be.}
{218}{}{Got a minute? I want to know more about your work.}

#Questions
{220}{}{Go ahead. What's on your mind?}

{221}{}{Where is your caravan route?}
{222}{}{Our target is Phoenix City in the south. On the way, we look into small parking lots along Route 17 and pass by San Brahmin.}
{223}{}{Tell me about San Brahmin.}
{224}{}{A large town on the way to Phoenix. The locals are mainly engaged in cattle breeding and therefore see us outsiders as only Brahmin buyers.}
{225}{}{Tell me about Phoenix.}
{226}{}{The biggest city I know of. You'll find everything there that you can find in the Wastelands, but you have to be careful. It's not safe in the city, even after the fire worshippers seized power there.}
{227}{}{The direction is south. But why would I share with you the subtleties of my craft?}
{228}{}{Fire worshippers?}
{229}{}{Strange guys. They worship pre-war atomic energy - that's all I understand. There are too many words to delve into. But they don't sit there idle either - it's with them that Phoenix has become a real city.}

{230}{}{What kind of cargo are you transporting?}
{231}{}{The uranium that is mined here in this mine.}
{232}{}{Yes, who needs it?}
{233}{}{To everyone who has a good old nuclear-powered technology. But the fire worshippers in Phoenix are the first to buy uranium, and then they sell it to smaller buyers at five times the price.}
{234}{}{Doesn't uranium lead to radiation sickness?}
{235}{}{Leads... if you eat it for breakfast, lunch and dinner. This ore is weakly radioactive and harmless until it is in the reactor. That's when it's best to stay as far away as possible.}

{236}{}{You realize that you're not helping at all... honest people?}
{237}{}{Are you talking about Faber's mercenaries? I don't care. My people and I need work. And the colony provides jobs and stable earnings. That's enough for me.}
{238}{}{I will pay 30 caps.}
{239}{}{This changes a lot.}
{240}{}{So what?}
{241}{}{In your leaky pockets, even the dust of the road is not worth hoping for.}
{242}{}{Oops, it's gone somewhere...}
{243}{}{The local sect worships atomic energy. However, after the destruction of their main temple, little remained of them. Anyway, it was under them that Phoenix became a real city.}

#Emergency adjustments
{250}{}{...I'm telling you, we're not going anywhere... Wait, you're not from the administration, are you? Then forget it.}
{251}{}{What's the problem with the caravan?}
{252}{}{Don't you know the latest developments? The mine is about to close, which means our business too.}
{253}{}{What's wrong with the mine?}
{254}{}{For now.}
{255}{}{The mine is destroyed, and it will take a lot of time and effort to clear it. I doubt this place will have a future.}
{256}{}{After the fire worshippers in Phoenix were atomized, the mine lost its main customer. Of course, there is a demand for ore, other settlements are ready to buy it, but it is unlikely that this will pay for the work of the mine.}
{257}{}{The garrison of Flagstaff is defeated, the prisoners have escaped, the manager is dead. Now we don't even know who we work for. It seems that no one needs our vacancy now.}
{258}{}{You're caravan drivers. Do you care who you work for?}
{259}{}{We have a special reputation. Because of the connection with the fire worshippers and Faber's mercenaries, not everyone will want to work with us. Competitors especially do not like us out of envy. After recent events, it will be very difficult to change patrons. If at all possible.}
{260}{}{So you canceled all flights?}
{261}{}{Exactly. Until the situation gets better, we will have to stay in Flagstaff. I don't know what we're going to do yet, but we'll figure something out.}

#Journey to the south
{300}{}{Hey, we're kind of on our way. Will you take me to Phoenix?}
{301}{}{We don't take fellow travelers. The customer gets nervous when unverified people enter the convoy.}
{302}{}{Can you at least answer the questions?}
{303}{}{Then goodbye.}
{304}{}{In Phoenix, only gallows on lampposts are waiting for us. We don't know what to do yet.}
{305}{}{Severe case.}
{306}{}{In Phoenix, the tongue is cut off for cheating. You're lucky we're not in Phoenix.}
{307}{}{Uh, I'll remember that...}

{310}{}{500 caps will make me tested?}
{311}{}{OK. A good welding for a fellow traveler. I'll take you to the convoy, but on general terms.}
{312}{}{Here are the bottlecaps. And what are the conditions?}
{313}{}{Then another time.}
{314}{}{}
{315}{}{And that's right. There's something in you, so I'll take you in the convoy. But on some conditions.}
{316}{}{What are the conditions?}
{317}{}{Let's do it another time.}
{318}{}{We have been taught by experience that you should not trust unverified people.}
{319}{}{Then goodbye.}

{320}{}{Firstly, the weight of the luggage is not more than 50 pounds. Secondly, we will make a stop in San Brahmin for the night and only then we will go to Phoenix. Will it suit you? Then come when you're ready.}
{321}{}{Great, give me time to get ready.}
{322}{}{I can be useful on the way. Don't you need a free employee?}
{323}{}{You shouldn't refuse.}

{330}{}{I want to go with the caravan.}
{331}{}{Clean up this trash, I say! I'm not going to risk the caravan for your belongings.}
{332}{}{Will you carry these things too? That won't do. I'm not going to slow down the whole caravan because of a burden in the tail. Take only the most necessary things with you, and no more than 50 pounds.}
{333}{}{Okay, I'll try to scatter my luggage.}
{334}{}{I'll take care of my things. Your caravan will not be affected in any way.}
{335}{}{Let's talk about your work.}
{336}{}{Agreed. But no one will carry your things for you and wait for you to hobble on your two to the camp. If you fall behind, blame yourself.}
{337}{}{No problems.}
{338}{}{(After passing the night with the guards, you finally go south)}
{339}{}{[Go on a journey]}

#Other locations
{400}{}{We'll be here for one day. You can look around if you want. But keep in mind, the caravan will not wait for you if you are late.}
{401}{}{Tell me about San Brahmin.}
{402}{}{The town of cattle breeders. This is a bit of a closed community, strangers are not liked here, but they are always ready to trade with them. Don't get into trouble if you want to find a common language with them.}
{403}{}{I'll try not to be late.}
{404}{}{[Wait for the caravan to leave for Phoenix]}
{405}{}{Leave without me, I'll be late.}
{406}{}{Whatever you say.}
{407}{}{Happily.}