{100}{}{You see a colonist.}
{101}{}{You see a citizen of the colony.}
{102}{}{It's curfew. Leave immediately.}

#Dialog
{200}{}{Hey, can't you see? This house is occupied. What do you want?}
{201}{}{It's not very kind to greet a guest like that.}
{202}{}{Who said you were called? However, there is nothing to be surprised about. Just know that this is a small town, everyone here knows each other by sight. And your face is unfamiliar to me.}
{203}{}{Mutually.}
{204}{}{Here, pull me here.}
{205}{}{Do you mind a couple of questions?}
{206}{}{I'll take that into account.}
{207}{}{It's good that we understand each other.}
{208}{}{Thank you for the advice. Sorry to bother you.}
{209}{}{Good manners? This is encouraging.}

{210}{}{What do you need?}
{211}{}{Goodbye.}

{212}{}{Why do you dislike strangers?}
{213}{}{Only savages live north of Phoenix. Am I not right? Are you from there?}
{214}{}{No. I'm from a small village in the west.}
{215}{}{So you're a peasant? Digging in the ground and all that, right?}
{1215}{}{So you're a peasant? Digging in the ground and all that, right?}
{216}{}{Exactly. Unlike the city worms, at least I'm busy with an important matter.}
{1216}{}{Exactly. Unlike the city worms, at least I'm busy with an important matter.}
{217}{}{Actually, not really. Why is this so important?}
{218}{}{Sort of. To get a harvest, you need to work from dawn to dusk.}
{219}{}{Well, it's hard for people like you to understand the charms of life in the south - where a *real* civilization is being revived. Is that all?}
{220}{}{Actually, no.}
{221}{}{Goodbye.}
{222}{}{I'm from Phoenix.}
{223}{}{Oh, you don't look it... I hope you enjoy your stay in our humble colony. Any more questions?}
{224}{}{Actually, yes.}
{225}{}{None of your business.}
{226}{}{Then there is nothing to ask the lady stupid questions.}
{227}{}{Yeah.}
{228}{}{}
{229}{}{It's good to see you.}

{230}{}{What do you do in this colony?}
{231}{}{While my husband is busy serving in the garrison, I keep an eye on his house. It used to be called a "household". Repeat?}
{232}{}{I think I know what it means.}
{233}{}{Do you like it here?}
{234}{}{Well... It's a little boring here. If it wasn't for my husband, I would have preferred to stay in Phoenix. Nevertheless, you can live and work here, and the garrison protects you from the rabble. You can even hire a maid if you don't mind spending some caps. There aren't many places in the world where you can do that.}
{235}{}{Are you kidding me? After jailbreak, I can't go outside without a knife! You can't find a worse place in all of Arizona. Even in Phoenix, life was quieter.}
{236}{}{Then can I ask another question?}
{237}{}{Clearly. Well, have a good stay.}
{238}{}{Have you lived here long?}
{239}{}{No, I came with the second wave of colonists from a big city in the south.}
{240}{}{Why did you leave?}
{241}{}{I wanted to start all over again. I thought there would be more freedom and opportunities here.}