{100}{}{Here is a colonist.}
{101}{}{You see a citizen of the colony.}
{102}{}{What are you doing here during curfew?}
{103}{}{I have better things to do than talk to strangers and strangers.}
{104}{}{Don't piss me off. After the death of my son, I am not myself.}
{105}{}{Oh, you... nit...}
{106}{}{...Can't... breathe...}

#Dialog
{200}{}{Wait, don't come near me! What are you doing here during curfew?}
{201}{}{I'm looking for a troublemaker who spoils the life of a local preacher. Hi there.}
{202}{}{So you're in league with this sectarian. I don't want to see you! I'm going home. And don't you dare follow me.}
{203}{}{I don't think it's necessary.}
{204}{}{Wait, let's go back a bit.}

{210}{}{What do you want from me?}
{211}{}{Don't mind me.}
{212}{}{How do you feel about the cult of the Sacred Fire?}
{213}{}{I've never liked this cult. What kind of crazy idea is it to worship old things and some mythical Fire? Any normal person has more important things to do.}
{214}{}{Isn't a preacher engaged in healing and teaching?}
{215}{}{Yes... if you properly appease him with a bunch of caps and then listen to idiotic nonsense. I can tell this nonsense about radiance, rent genes and other atoms for free myself. The whole church of the Sacred Fire consists of ordinary charlatans who help only for huge donations.}
{216}{}{I fully share your hatred for this stupid cult. What can we do?}
{217}{}{I'll have to leave you with your skepticism. Be there.}
{218}{}{Hmm-m. I don't know if I should believe you. But if you really want to cleanse the city of this filth, then one of two things - either we kill this sectarian, or the city will drive him away.}
{219}{}{How to do it?}
{220}{}{I don't even know, buddy. If we attack him in the open, then the city will not leave it so easily. Too many people in the colony believe his nonsense. We need to eliminate it quietly.}
{221}{}{If you coax me well, then I will rid the city of the preacher.}
{222}{}{The task requires time for reflection. I'll be back later.}
{223}{}{They say your relatives were enslaved. Then you should know that the sectarian has blessed the mercenaries for this "God-pleasing" enterprise. Some of your relatives were taken away by other fire worshippers and taken somewhere out of the city. If this is not enough, then think about the medicines that the sectarian receives from the south. That's where the real "uranium vein" is, eh?}
{224}{}{How glad I am to see you!}
{225}{}{Glad to see you.}
{226}{}{Hiram tells my son's story at Sunday sermons. Nothing depends on me now.}

{230}{}{I want you to come to the temple and publicly confess what you have done.}
{231}{}{Are you out of your mind? So I will turn the whole city against me.}
{232}{}{Not if you pretend that now you also sympathize with the sect.}
{233}{}{Really, a stupid idea. Forget it.}
{234}{}{Nonsense! Why would I do that?}
{235}{}{Your son will be saved. In addition, Hiram already knows who is behind the night diversions, and will not leave it so easily.}
{236}{}{Damn it... Well, you're right, there's nothing else I can do.}
{237}{}{The cultist probably irradiated your brain. Leave me alone.}
{238}{}{Okay. But blame yourself.}
{239}{}{Hell, even away from Phoenix, you can't avoid these crazy fire worshippers... Okay, I'll talk to Hiram. I will try to establish a common language, but only to avoid conflict.}
{240}{}{Great, keep it up.}
{241}{}{The job is done - Hiram is no more.}
{242}{}{Ah-h, wonderful news. Now that this fanatic is gone, the city will get better. Take a hundred caps, you deserve them.}
{243}{}{What about your son's treatment?}
{244}{}{Hiram saved your son.}
{245}{}{Not bad. Later.}

{250}{}{Why are you trying to drive the priest away?}
{251}{}{An idiotic cult that brainwashes people and pulls the bottlecaps out of them is *already* a weighty reason. But there is another one - this is my son suffering from the effects of radiation.}
{252}{}{Sad story, let's change the subject.}
{253}{}{Hiram refused to help you?}
{254}{}{He demanded conversion to his faith. Not me, of course, but my son. He should become a servant of the temple, go to classes and morning prayers. Damn it. We moved away from these damned fanatics, and they still get into our personal life.}
{255}{}{Even the caps don't help?}
{256}{}{The local temple is just a branch of the main temple from Phoenix. They have caps above the roof. Therefore, Hiram has enough means to exist. It's more important for him to impose his stupid faith on the colonists. And he will stop at nothing.}
{257}{}{I can help with the treatment if you let me.}
{258}{}{Really? I will be glad of any help and will pay with caps, just not to mess with this sect.}
{259}{}{I managed to cure your son. Without resorting to the services of the church.}
{260}{}{Hiram cured your son as a sign of reconciliation.}
{261}{}{How glad I am! Thanks! Here, take 100 caps for services.}
{262}{}{I'm not healing for the caps. Keep them and be happy.}
{263}{}{You're an incredible person. I'll tell everyone about your merits. Thanks again.}
{264}{}{Please.}
{265}{}{Great, they compensate for the cost of medicines.}
{266}{}{Thanks again.}
{267}{}{You're welcome.}
{268}{}{I'll see what I can do.}
{269}{}{Damn sectarians! Don't think I owe you anything now. But I'll try not to bother the preacher anymore.}
{270}{}{That's agreed.}
{271}{}{What's the problem of finding a cure for radiation sickness?}
{272}{}{Hiram receives medical supplies from the main temple in the south. There's nowhere else to get medicine. Only sometimes caravans deliver a small batch at inflated prices.}