{100}{}{You see an invader.}
{101}{}{You see a tattooed man with prominent features of the skull. He is not like the other inhabitants of Flagstaff.}
{102}{}{We are leaving this earth.}
{103}{}{This is our land!}

{200}{}{Stop. You're defiling this land. It is in our power to stop it.}
{201}{}{Uh...}
{202}{}{People like you don't belong here.}
{203}{}{[Defend]}
{204}{}{I came in peace. The farmer says you took his house and land.}
{1204}{}{I came in peace. The farmer says you took his house and land.}
{205}{}{The alien is a hypocrite like everyone else. You came to these lands, killed our people, and took our lands. We take it back.}
{206}{}{Yes, you are ordinary robbers.}
{207}{}{I do not know this story. What are we talking about?}
{208}{}{Yes, you don't know. Our ancestors lived here for three generations. Then Faber's men came and took everyone to work, and the dissenters were killed. It was just us when we were kids. Now we want revenge. Blood for blood is our custom.}
{209}{}{But the farmer is not to blame for anything. Leave him alone.}
{210}{}{We saved his life. Let him thank you and leave. But you're not going anywhere.}
{211}{}{[Show middle finger]}
{212}{}{Hey, I don't want to fight...}
{213}{}{I'm sorry to hear that. But the farmer is not to blame for anything. He's a civilian, leave him.}
{214}{}{We know. That's why they kept him alive. Let him thank you and leave.}
{215}{}{He put a lot of work into this meager land. You should appreciate his efforts.}
{216}{}{Perhaps. None of us wanted war until the colonists crossed the line. But we can't fight the garrison.}
{217}{}{Now it is the land of the colonists. And there's nothing you can do about it. All you have to do is leave Flagstaff and start all over again.}
{218}{}{If you're so eager for retribution, I'll have to stop you. Stop by force.}
{219}{}{You outsiders are too talkative. But you're making a point. We've been thinking about this for a long time. In the struggle, we will simply die, and after going to the mountains, we will continue the race. So be it. We need to gather the remnants of the clan and resolve this issue. (looks at the other tribesmen) And we are not interested in the farm. (gives a sign to the others)}
{220}{}{A wise decision. Good luck.}
{221}{}{Yes, get out of here, uh, that is, good luck, and stuff like that.}

{250}{}{Arrh! A man in armor! Damn colonists, what else will you come up with to get us off our lands?}
{251}{}{What are you talking about?}
{252}{}{It's not my problem.}
{253}{}{We don't want a fight with you, man in armor. We'll leave. Don't follow us.}
{254}{}{Yes, get out of here.}
{255}{}{Oh, no, you'll have to pay for the inconvenience first. Pay with blood.}

{260}{}{Stranger... Why do you look like a mutfruit skin that's been lying in the sun all day?}
{261}{}{What do you think, dark-skinned? Eh, there are only racists around...}
{262}{}{You're suffering, right? You suffer from others who don't look like you. We are the same, we understand you.}
{263}{}{Don't even laugh at my appearance.}
{264}{}{Actually, I'm here for my farmer friend. He is also very lonely.}
{265}{}{Farmer? We saved his life. Let him thank you and leave.}
{266}{}{No matter how you hide behind it, you just seized his land. It's bad. Very bad.}