{100}{}{This is Randy.}
{101}{}{You see an unwashed farmer. He stinks terribly.}
{102}{}{They're there. Be careful.}
{103}{}{It's good to see you. But right now I need to do my farm.}

#Dialog - on the city map
{200}{}{(a disheveled man looks at you with a sad look) Hello, stranger. I want to say right away that I have nothing of value.}
{1200}{}{(a disheveled man looks at you with a sad look) Hello, stranger. I want to say right away that I have nothing of value.}
{201}{}{That's what everyone says. Show me what you're hiding.}
{202}{}{I'm telling you, there's nothing. The Raiders kicked me out of my own house. I am a beggar and homeless.}
{203}{}{Ugh, it's disgusting to even look at you.}
{204}{}{Sorry to hear that. But I need to talk to you.}
{205}{}{I see you're on edge. Calm down, I'm not going to rob you.}
{206}{}{Sorry. I lost my trust in people after the raiders kicked me out of the farm. Now I'm a beggar and homeless, as you can see.}
{207}{}{Sorry to hear that. Do you mind if I sit next to you?}
{208}{}{So I don't need you. Sit on with your sorrows, loser.}
{209}{}{Clearly, there are no more questions.}
{210}{}{Yes?}
{211}{}{Nothing yet.}
{212}{}{Who are you?}
{213}{}{I'm Randy. He arrived with the colonists a few years ago and set up his small farm away from everyone. It is unlikely that you will be interested in the rest of my biography.}
{214}{}{Did the raiders kick you out of the house?}
{215}{}{Yeah, these smart-ass guys know how to ambush. I was in their hands faster than I could say "mole rat". They turned over the whole house while looking for food. And then they threw me out into the open sky. And they said I don't live here anymore.}
{216}{}{Have you tried to kick them out of there?}
{217}{}{One against three armed raiders is too much. It's better to lose your home than to lose your life.}
{218}{}{Why not ask the garrison for help?}
{219}{}{Because then I will have to give them almost all of my harvest for ten years. Such are the conditions. And my farm can only feed a couple of people, no more.}
{220}{}{I will solve the problem with the raiders if you give me your food.}
{221}{}{Our problems are somewhat similar. I want to help you.}
{222}{}{Tell me about yourself.}
{223}{}{Did the Raiders kick you out of the house?}
{224}{}{Yes, of course. There are small food supplies on the farm. And they will get to someone anyway. But not to me.}
{225}{}{Lead the way.}
{226}{}{Tempting offer, but I don't want to mess with the raiders.}
{227}{}{Will you drive them away? That would be very helpful. I hope you know how to fight, because it's hardly possible to negotiate with them.}
{228}{}{I'll find a way. Just show me the way.}
{229}{}{Indeed, it is too dangerous for one person. Sorry, I can't help.}

#Dialog - on the farm map
{300}{}{They're there. Be careful.}
{301}{}{Wait here.}

{310}{}{Is this your farm?}
{311}{}{Sure. This is my house and my garden beds.}
{312}{}{Do you live here alone?}
{313}{}{Yes, recently. At first there were more of us, and everyone worked for the farm. One was killed by thieves for the harvest, the other died of some kind of infection. So gradually I was left alone. But I still don't want to leave here.}
{314}{}{Why is this farm so important to you? There are lots of abandoned lands and houses all around.}
{315}{}{This land has become fruitful only thanks to our sweat and our blood! I put in too much work to give it to some robbers. They're going to leave some day anyway.}
{316}{}{And why is there a sign at the entrance "Morrison brothers"?}
{317}{}{( confused) Morrison... No matter. This sign is probably a hundred years old. Now *I* own this land!}
{318}{}{What do you know about the invaders?}
{319}{}{They lived here before us. Savages, that is. They did not adapt to the new life, but they learned to rob. The garrisons took out almost everyone, but this gang turned out to be too tenacious.}
{320}{}{You didn't talk about it.}
{321}{}{And why? Look, they're just raiders. They come and take what doesn't belong to them. Nothing else matters.}

{350}{}{The invaders are dead, Randy. You can go back to your sweet home.}
{351}{}{I can't believe you did it. Eh, I could use your skills... Maybe you'll move in with me for good, huh?}
{352}{}{Can't. I have a house too. And he's in danger.}
{353}{}{Into this hole? Well, no. There are plantations in my native village that you never dreamed of.}
{354}{}{Well, if that's the case... I understand. Thank you for your help and good luck.}
{355}{}{Not so fast. Give all the food you have.}
{356}{}{Glad to help.}
{1356}{}{I was glad to help.}
{357}{}{Ah, of course. Some invaders pushed others. Nothing changes, right? You can take everything that was left in that refrigerator.}
{358}{}{That would be right away.}
{359}{}{These savages won't bother you anymore. You can go back to your house.}