{100}{}{There is a sentry in front of you.}
{101}{}{You see one of the local mercenaries. He's leisurely patrolling the streets.}
{102}{}{Damn, I already wanted to knock you down. There's no need to hang out on the street during curfew.}

{110}{}{Greetings.}
{111}{}{Welcome to Flagstaff.}
{112}{}{Move on.}
{113}{}{Any problems?}
{114}{}{How can I help?}
{115}{}{Do you have a gun? If so, keep it in your holster.}
{116}{}{Have a nice time.}
{117}{}{There are good drinks at the Galactic Lunch.}
{118}{}{If you see anything suspicious, let me know.}