{100}{}{Grey is in front of you.}
{101}{}{You see a citizen of the colony.}
{102}{}{I want to sleep, leave me alone.}
{103}{}{*Yawns*}
{104}{}{Z-z-z}
{105}{}{Now things will go uphill.}
{106}{}{I'm not leaving until that stupid brahmin moves.}

#On the city map
{200}{}{What do you want?}
{201}{}{Oh, nothing. I'm wandering around here, looking around the city.}
{202}{}{Your kids say they're trying to kick you out of town?}
{203}{}{Yes, after losing my job I can't pay the residence tax.}
{204}{}{And who did you work for?}
{205}{}{Chief of patrol in the garrison.}
{206}{}{Wow. Garrison work is honorable in this city, isn't it? What happened?}
{207}{}{Yes, I was stripped of my rank after inappropriate behavior... simply put, I got drunk like a pig-rat and allowed myself too much.}
{208}{}{Is there really no work for the former commander here?}
{209}{}{If you are forced to resign, then no - everyone is wary and unfriendly to you.}
{210}{}{[Next]}
{211}{}{And what remains? Well, work in the mine. But no, don't. I have a big family, and I have to support it. Most likely, you will have to get a job as a security guard in a caravan. And it's not far from moving back to Phoenix.}
{212}{}{Is it that bad?}
{213}{}{We moved here precisely because there were opportunities for growth and earnings here. I gave up everything I had in the big city. No one is waiting for us there. But it's too late to decide anything. My career at Flagstaff is over. A pity. It all started so well.}
{214}{}{If I find out about vacancies, I will let you know. Bye.}
{215}{}{A sad story. Well, I have to go.}
{216}{}{The new supervisor in the mine is not coping with his duties. You could take his place.}

{220}{}{The mine needs a new supervisor. You could take the place of this tyrant.}
{221}{}{Whip? I know him, he's an evil man. And I think he's not right in the head.}
{222}{}{He mutilates slaves and then blames it on an accident. The workers want a new supervisor.}
{223}{}{It is unlikely that he will give up this place voluntarily. How can I move it?}
{224}{}{Leave it to me. I'll arrange everything.}
{225}{}{What's up with the warden? I think you're just messing with my head.}
{226}{}{Now I'm earning great caps, things have gone uphill. And all thanks to you.}

{230}{}{Faber has agreed to give you the post of overseer.}
{231}{}{I can't imagine how you managed to convince him. Thank you.}
{232}{}{There is one problem - you will have to take the order to the Whip yourself.}
{233}{}{It sounds easy, but the Whip probably won't want to leave voluntarily. I need someone to back me up. Just stay close while I negotiate with him, OK?}
{234}{}{Okay. Meet me at the mine...}
{235}{}{Good luck. Later.}

#On the mine map (used by the FCMinPap script)
{240}{}{Ugh, what a tenacious son of a bitch! If it wasn't for you, I wouldn't have made it. Thank you.}
{241}{}{Come on. It was fun.}
{242}{}{He almost killed us!}
{243}{}{I don't know why you're helping me, but I'll remember you and I won't go overboard like Knut did. Under my command, justice and law will be above personal ambitions.}
{244}{}{Good luck. Bye.}
{245}{}{If it wasn't for you, the conversation would have ended in a fight. Thank you.}
{246}{}{As you can see, you can negotiate with everyone.}
{247}{}{And you know, the fists were moaning for a good fight.}
{248}{}{This is your doing, right? Don't worry, I'm just glad there's one less problem. The whip could give me a lot of trouble.}
{249}{}{He deserved it.}