{100}{}{This is your madre.}
{101}{}{You see a woman you know well. His mother.}
{102}{}{Goodbye, Madre. Now I'll take care of myself on my own.}
{103}{}{You get }
{104}{}{ experience for the liberation of their fellow tribesmen.}
{105}{}{Your Madre is dead. It remains to find other members of the Villa.}
{106}{}{Your Madre is dead. There's nothing else to do here.}
{107}{}{We'll talk when we get out of the garrison.}

#The first dialog
{200}{}{? How are you... For God's sake, you shouldn't have taken that risk! We would have been able to find salvation... But of course, I'm glad to see you. And how proud your padre would be if he learned about the feat of his child! You're doing great.}
{201}{}{It's disgusting to listen to you, Madre. I'm old enough to make decisions.}
{1201}{}{It's disgusting to listen to you, Madre. I'm old enough to make decisions.}
{202}{}{I would not forgive myself if something happened to you because of my inaction.}
{1202}{}{I wouldn't forgive myself if something happened to you because of my inaction.}
{203}{}{Oh, yes, of course... I understand. Perhaps it's all about this raid. He changed something in all of us. I see changes in your eyes, I see a slightly different person. And I don't know if it's good or not.}
{204}{}{Well, that's the strength of our whole Villa - we're all like one big family. Everyone is responsible for each other. And I am glad to see that the journey has not changed these ideals in you.}
{205}{}{Now let's think about how we can get out of this mess.}

{206}{}{I'm afraid it won't be easy. As you can see, there are only three of our people in the pen. Two more were lost in the mines. The rest, including your padre, were taken south to the big city of Phoenix.}
{207}{}{What were these mercenaries doing to you?}
{208}{}{How do I get to Phoenix?}
{209}{}{What do you know about the lost group?}
{210}{}{How can I free you from this pen?}
{211}{}{I will try to solve these problems. Wait for the signal.}
{212}{}{Nice to see you.}
{213}{}{I'm still working on your release. Wait.}
{214}{}{Yes?}
{215}{}{Bye.}
{216}{}{I see.}
{217}{}{Nothing special, don't worry. Basically, I was doing the same household chores as at the Villa. Only bigger and heavier. These colonists are so ill-mannered. But men are forced to work in the mines. It's really hard for them.}
{218}{}{They say it's a big city in the south, but I've never been there. Trade caravans travel between Flagstaff and Phoenix. Ask the locals, they should know something about it.}
{219}{}{Hugo and Sancho went into the mines to find a secret passage. Since then, there has been no news from them.}
{220}{}{The colonists won't let us go voluntarily. You can talk to their boss, but he is unlikely to make concessions without serious benefits.}
{221}{}{How about an escape?}
{222}{}{We would have run a long time ago if it weren't for these collars. They'll kill us instantly if we get too far from the camp. They say that they are controlled by that big antenna opposite the pen, but none of the prisoners understands this.}
{223}{}{You don't want to let me go there, do you?}
{224}{}{It's not even about the dangers of traveling, but about the city itself. They tell a lot about him, but nothing good. Besides, your uncle Miguel once went with a caravan to Phoenix and never came back. Try to find him, maybe he will help.}
{225}{}{Faber gave you freedom. It's time to go back to the Villa.}
{226}{}{We are free! Don't worry about us, we'll get to the Villa on our own. But you need to help your padre soon, he was sent to the south. Good luck.}
{227}{}{See you at the Villa.}
{228}{}{The guards are dead, you can leave.}
{229}{}{Collars are no longer dangerous. Take them off and get out of here.}
{230}{}{That's good, but how do we get past the guards?}
{231}{}{This problem has yet to be considered.}
{232}{}{Leave the guards to me. I'll get you out of here.}
{233}{}{Do you really know what to do? As soon as we leave the pen, the guards will attack us. We won't be able to resist so many armed people.}
{234}{}{Don't mind the guards, I know what I'm doing.}
{235}{}{Stay in the pen until I give the command.}
{236}{}{OK. Lead us. As soon as we get out of the garrison, then we'll talk.}
{237}{}{Let's go.}
{238}{}{It's a bad thing. I can't get you out alone. Who could help us?}
{239}{}{The only ones who can help us are the Rangers. They live south of the Villa on the Colorado River. But don't rush to fall at their feet. Rangers offer their protection for a reason.}
{240}{}{What about escape?}