{100}{}{In front of you is the overseer Knut.}
{101}{}{You see an angry shouting man.}
{102}{}{Where's your shovel, slave? Ah, you're not one of ours... Your luck, otherwise I would have whipped you until you lost your pulse.}
{1102}{}{You shouldn't be here, lady. This place is only for criminals and slaves.}
{103}{}{Get out of here!}
{104}{}{Don't get in my way, rat.}

{110}{}{Work, devils, you're building America!}
{111}{}{Work harder!}
{112}{}{Move your mother!}
{113}{}{If I see a loafer, I'll whip the pig-rat to hell!}
{114}{}{You'll get pig-rat shit for dinner}
{115}{}{Who will work well, will get real meat}
{116}{}{Hey, where are you going? Over there! There, I say!}
{117}{}{}
{118}{}{}
{119}{}{}

{200}{}{Looking for a problem?}
{1200}{}{Yes, amochka, what a surprise. I will be unbearably sorry to force you to dirty such beautiful hands in this ore.}
{201}{}{And you provide them, right?}
{1201}{}{As sorry as that slave you beat half to death?}
{202}{}{Yes. I like to kick the ass of all sorts of scum, which withers without the right to vote.}
{203}{}{Are you talking about me now, asshole?}
{204}{}{Would you consider me one of them, too, asshole?}
{205}{}{Be silent! What are you doing, you piece of shit? Did you want to go to hard labor? Rot alive! You're going to eat the earth from me! You'll drink your own urine instead of water! Is that clear to you?}
{206}{}{Yes, sir. I'm sorry, sir.}
{207}{}{You can't intimidate me. Go fuck yourself, you idiot.}
{208}{}{I'll KILL you, YOU SON of A BITCH!!!}
{1208}{}{ I'LL KILL YOU, BITCH!!!}
{209}{}{Oh, how strange...}
{210}{}{That slave did not deserve such treatment.}
{211}{}{How do you know that? Only criminals and charlatans work in this mine. So if you pretend to be an arbitrator, you will instantly take the vacant place. Is that clear to you?}
{212}{}{Just try it and I'll show you the top of justice, scum.}
{213}{}{Yes, sir. I'm sorry, sir.}
{214}{}{Not at all, sir.}

{220}{}{Everyone back up! This is a criminal conspiracy! You're all under arrest! You will crumble the ore with your teeth!}
{221}{}{You're not sane. Now we'll put your brains in the right place...}
{222}{}{Hey, it's nothing to do with me. Here's your competitor.}
{223}{}{Let's discuss everything peacefully, eh?}
{224}{}{I'm not buying these tricks! If you want to get rid of the warden, wait for the consequences.}
{225}{}{Faber personally signed the order. Give up now, then it will be too late.}
{226}{}{Gr-rm... Do not think that I will leave it so easily. You're all going to pay for me! I swear!}
{227}{}{Well, well.}