{100}{}{You see the operator.}
{101}{}{You see the operator of the processing machine.}

#Dialog
{200}{}{(without looking up from his work) And? What do you need?}
{201}{}{Nothing.}
{202}{}{(continuing his work) Let's go faster.}
{203}{}{Bye.}
{204}{}{Wait, tell me something else.}

{210}{}{Tell us about your work.}
{211}{}{What's there to tell? I take the ore, load it into the machine, and it grinds and cleans it. The purified ore is sent to the enrichment machine, the rest is thrown out. That's it.}
{212}{}{Why clean the ore?}
{213}{}{Because uranium must be free of impurities, otherwise it will not give the necessary energy. However, I don't fully understand the whole technology myself.}
{214}{}{Is it safe to work with uranium?}
{215}{}{If you're talking about radiation, then it's not terrible until the ore is cleaned. But it is quite possible to get injured from this damned ancient machine.}

{220}{}{Where does this equipment come from?}
{221}{}{Left over from the old days. Although these are small things compared to what was here before.}
{222}{}{That is, before the war, uranium was also mined and purified here?}
{223}{}{Yeah. The underground galleries are well preserved, but some of the equipment and buildings have fallen into disrepair.}
{224}{}{Something is missing here, don't you find?}
{225}{}{Eh? What are you talking about?}
{226}{}{Just simple doubts.}
{227}{}{It can't be that people just came and started these ancient machines. Where did so much lost knowledge come from?}
{228}{}{That's right. They say that before the creation of the colony, Faber hired some types who repaired and prepared the equipment. And only after that he brought people here and started production. But none of the locals could have done it.}
{229}{}{How interesting. Tell me something else.}

{230}{}{Are you here of your own free will?}
{231}{}{Formally. I have nowhere to go, so I'm kind of a willing slave.}
{232}{}{What do you think about slavery?}
{233}{}{I don't know. It's probably not good to force others to work for you. But here's what I think - we're all in the same cage here.}

{240}{}{The mines are blown up. What are you going to do now?}
{241}{}{I don't know. I will do what I am ordered to do. I have nowhere to go anyway.}
{242}{}{The whip won't bother anyone anymore. Look outside.}

{250}{}{Does the supervisor often beat up the workers?}
{251}{}{(sigh) This Whip... he's a real psycho, snaps at everyone. I get it from him too, but not so often. I wish I could get rid of him, but Faber appoints the guards himself.}
{252}{}{What about the administrator? Can't he do anything?}
{253}{}{I don't know why I'm telling you this. But the Whip forces him to rewrite reports as if the imprisoned workers were hit by a landslide or injured themselves. He doesn't want to tarnish his reputation, the bastard. But he also keeps the administrator in check.}
{254}{}{But what's the point of crippled slaves?}
{255}{}{I'm telling you, Knut is just an evil person. I think Faber specifically chose such a tough warden to strengthen control over the prisoners because there have been a lot of problems with them lately. Besides, Roy and Knut are on good terms. But Faber hardly knows the whole truth.}
{256}{}{I can kill him for you and the rest of the prisoners.}
{257}{}{What nonsense is this? Are you serious? Would you kill a man for a handful of prisoners? Even the mercenaries in the garrison aren't that bloodthirsty. Besides, it may not make sense if another tyrant takes the place of the Whip. In any case, don't try to involve me in this. I have nothing to do with it!}
{258}{}{It is ok. I have no conscience because of any scum.}
{259}{}{Perhaps you're right. A delicate and legal way is needed here.}
{260}{}{I'll tell Faber what's really going on. It's sure to piss him off.}
{261}{}{I doubt he'll listen to you. But don't get me involved in this. I have nothing to do with it!}
{262}{}{Still, it's worth a try. Bye.}
{263}{}{Then I'll just finish this Whip. Wait for the corpse near the entrance.}
{264}{}{How do you like the new supervisor?}
{265}{}{Better than before. He does not wring too much and keeps himself in hand. I'm glad you managed to fire Knut.}
{266}{}{It was easy. Be.}
{267}{}{This Whip won't bother you or anyone else anymore.}
{268}{}{You... killed him? You're crazy! In any case, this does not solve the problem, because an even bigger tyrant can be put after the Whip. Haven't you thought about that? Okay, I didn't hear anything, and I had nothing to do with it.}
{1268}{}{You... killed him? You're crazy! In any case, this does not solve the problem, because an even bigger tyrant can be put after the Whip. Haven't you thought about that? So, okay, I didn't hear anything, and I had nothing to do with it.}
{269}{}{And this is all your gratitude? Not much.}