{100}{}{Here is En Brandley.}
{101}{}{You see a not particularly remarkable woman in business clothes.}
{102}{}{Z-z-z}
{103}{}{Sorry, we're closed. In these parts, no one needs our services anymore...}

#Replicas when a prisoner is attacked
{120}{}{Please calm down!}
{121}{}{I really have an empty cash register!}
{122}{}{Don't touch anything here!}
{123}{}{Listen, I really feel for you...}
{124}{}{I really can't help you!}
{125}{}{Please go away, I have nothing!}
{126}{}{Leave me alone!}
{127}{}{}
{128}{}{}
{129}{}{Help! I'm being robbed!}

#Dialog
{200}{}{(you see a woman in an unusually decent outfit; it looks like she is watching herself and looks down on others)}
{201}{}{My respects, Miss...}
{202}{}{Hey, hello.}
{203}{}{En Brandley. And call me Mrs..}
{204}{}{Whatever you say, Mrs. Brandley.}
{205}{}{(throws a contemptuous glance) Hmm. Good afternoon. Where did they teach you to talk to ladies like that? In the woods?}
# Quote from the movie "Prison Rock": "Where did they teach you to talk to ladies like that? In the forest?"
{206}{}{I wasn't taught that at all.}

{210}{}{How can I help?}
{211}{}{Goodbye.}
{212}{}{Let's go back to the beginning of the conversation.}
{213}{}{Let's go back a bit.}

{218}{}{Thank you for saving me! It was a dangerous case. In gratitude, I will give you a big discount if you need our transportation services.}
{219}{}{Sounds good.}

#Sending a parcel
{220}{}{I need to send a package to Phoenix.}
{221}{}{I need to send a package to Two-Sun.}
{222}{}{Wonderful. The cost of shipment will be }
{223}{}{ caps. Place the package in this box against the wall and let us know that it is ready. After payment, we will take them to Phoenix.}
{224}{}{Here is the payment, the parcel can be sent.}
{225}{}{The package will wait. Let's talk about something better?}
{226}{}{I don't have so many caps with me. I'll come back later.}
{227}{}{(stumbling over every word, she draws up a contract and enters your name in the journal) Thank you for choosing our company. The package will be waiting at the destination.}
{228}{}{}
{229}{}{Wonderful. Goodbye.}
{230}{}{I'm sorry, but that's not enough.}
{231}{}{Can we talk about something then?}
{232}{}{Well, I'm going to collect the caps.}

{240}{}{Do you accept old money for payment?}
{241}{}{That is, pre-war dollars and cents? No, no, they have long been out of use. However, in Phoenix, a local casino can exchange them for caps, but only for their customers.}
{242}{}{Back to the subject of my parcel.}
{243}{}{Hmm. That makes a difference. I'll wait with the package for now.}
{244}{}{I expect active deliveries to the south. We should cooperate.}
{245}{}{I'm afraid we can't go for discounts. This will not cover our transportation costs.}
{246}{}{Too bad.}
{247}{}{Sounds tempting. Perhaps we can reduce the price by 50 caps.}
{248}{}{You won't regret it.}
{249}{}{How reliable is this contract?}

{250}{}{You sure can... write?}
{251}{}{Much better than most of the "literate" residents of the city. I took courses with the Followers of Fire... But I really don't have enough practice.}
{252}{}{Uh, yes, of course.}
{253}{}{We transport parcels once a month. And the cases of their loss can be counted on the fingers. We have experienced couriers. They know the terrain and ways of survival well. In case of loss of the parcel, you can claim compensation.}
{254}{}{OF COURSE I can write! Otherwise I wouldn't be able to work here.}
{255}{}{Well, yes, well, yes.}

#Quest
{270}{}{I'm looking for a job. Do you have any vacancies?}
{271}{}{Unfortunately, no. To be honest, there is a whole queue to guard the caravans.}
{272}{}{It's a pity. I really need to earn some extra money.}
{273}{}{Are there really no jobs in this hole?}
{274}{}{In that case, can you do a little favor? I recently lost my wallet. There were a few small things, but the most important thing was a notebook. Most likely, they were stolen. If you find it, bring it to me, I'll pay.}
{275}{}{No problem. I have a nose for thieves.}
{276}{}{Oh, then your nose will have to distinguish hundreds of smells in this city. Good luck.}
{277}{}{Don't worry, lady. I will find the missing without much difficulty.}
{278}{}{Not yet.}
{279}{}{A mess! And where are the soldiers from the garrison looking? Why do we pay taxes to these idlers?}

{280}{}{About lost things. }
{281}{}{What is it? Have you found them?}
{282}{}{Just wondering if you have any ideas?}
{283}{}{I don't know. In the morning, my things were with me, and after a walk around the city, they disappeared. Maybe someone saw from passers-by?}
{284}{}{Good idea, we should try.}
{285}{}{Oh yes. Here are your things.}
{286}{}{Oh, really! I was afraid I'd lost them forever. You know, there is a lot of important information for me here. But who was that brazen thief?}
{287}{}{They were the neighborhood kids.}
{288}{}{Kids? I can't believe it! Residents have always appreciated Flagstaff for its safety, because there is a garrison nearby, and there is an impassable wall of barricades around. And here's the result - the thieves were inside, not outside. Yes, and children!}
{289}{}{Yes, it's just awful. You can't trust anyone here.}
{290}{}{Of course, I will not write a denunciation to the garrison, but I will not forgive the neighbors so easily. Someone has to keep order here.}
{291}{}{They're kids. This is not theft, but a simple prank.}
{292}{}{People with such a prank end up in correctional labor. Of course, I will not write a denunciation to the garrison, but I will not forgive the neighbors so easily.}
{293}{}{It seems, uh, that you dropped your things yourself, I found them on the street.}
{1293}{}{It seems, uh, that you dropped your things yourself, I found them on the street.}
{294}{}{That's how? I'm starting to doubt something. In any case, it doesn't matter anymore.}
{295}{}{It's good that you solved your problem.}
{296}{}{Ahem. The job is done, but the reward is not visible.}
{297}{}{Thank you very much. Here are 20 caps for the find.}
{298}{}{A good start.}
{299}{}{Better than nothing.}

#Questions
{300}{}{What is this place?}
{301}{}{This is the office of Sonora Express, the only delivery service in all of Arizona.}
{302}{}{And what are you transporting?}
{303}{}{Any small parcels, cover transfers and letters. There is another company for larger shipments, it cooperates with a uranium mine.}
{304}{}{Unusual business in these places.}
{305}{}{That's right. Previously, there was no need for parcels and letters, many did not even know how to write. But after the revolution, a lot has changed in the south. Sonora Express is one example.}
{306}{}{So what is this place?}
{307}{}{Are you here alone, without a guard?}
{308}{}{It's safe in the colony, bandits don't come here because of the garrison and patrolmen. But outside the valley, especially along the trails, there are more and more bandits.}
{309}{}{Why?}
{310}{}{Previously, only wolves and rare tribes came across along the route, bandits had nowhere to profit. Now the growing Flagstaff attracts people to work.}

{320}{}{Tell me about yourself.}
{321}{}{My name is Ann Brandley, I own this office.}
{322}{}{Where are you from?}
{323}{}{From the south, from Phoenix. I spent all my childhood and youth there. Then I delivered packages and traded until I got to Sonora Express.}
{324}{}{What made you leave Phoenix?}
{325}{}{This is a big, but stuffy city in which competition does not allow anyone to turn around. I lacked freedom and security there.}
{326}{}{Was it hard to get here?}
{327}{}{I arrived by stagecoach on the wave of the first settlers. The road was difficult - we walked slowly because of the luggage, there was not enough clean water, hostile tribes attacked us several times. But in those days there were not so many bandits on the way as now.}
{328}{}{Don't mercenaries bother you?}
{329}{}{Soldiers in the garrison? Not at all. As long as my husband is one of them, this institution is not in danger.}
{330}{}{Why do you call them soldiers?}
{331}{}{Well, they grew out of a gang of slavers a long time ago. Now it's a real little army defending the city. With his general, as in those stories from the pre-war era. But then, I don't think you've ever read it.}
{332}{}{How do you live in this town?}
{333}{}{Not bad if you put up with strict rules. I'm here more for a living.}

{350}{}{How do I get to Phoenix?}
{351}{}{It's a big city in the south, right here. (shows on the map) Go along Route 17 without turning off.}
{352}{}{May I join your messengers?}
{353}{}{We do not provide stagecoach services, it is against the company's rules. It is worth talking to the carriers of uranium ore, they sometimes need hired movers.}
{354}{}{Great, I'll look in on them when I have time.}
{355}{}{Thanks, I'll go to them right now.}