{100}{}{Here is a robber.}
{101}{}{You see an escaped prisoner. He is armed and very dangerous.}
{102}{}{Come closer and you're dead!}
{103}{}{It seems that the city has become unsafe.}
{104}{}{Put your weapon away, otherwise I'll cut everyone here!}

#Floating replicas
{110}{}{caps on the table! Quickly!}
{111}{}{If you don't want it in a good way, it will be in a bad way.}
{112}{}{Drive the bottlecaps, I said!}
{113}{}{I'm going to lose my temper.}
{114}{}{You're going to die, bitch, if you don't give up all the caps.}
{115}{}{Face down! Quickly!}

#Dialog
{200}{}{Hey, you. Give me all your caps. Now!}
{201}{}{Okay, okay, here are 50 caps for you, just don't use violence...}
{202}{}{This is all? Damn, I won't get far this way... Now stand by the wall and count to a thousand. Do you understand?}
{203}{}{Uh, whatever you say...}
{204}{}{That's it, I've had enough. It's time to beat the shit out of you!}
{205}{}{Calm down, it's not worth shedding blood. You still have a way out.}
{206}{}{I said, give-all-your-caps. Immediately!}
{207}{}{Okay, okay, here are all my bottlecaps, just don't use violence...}
{208}{}{What the hell are you talking about?! After escaping, I can only go to another city, and what will I do there without bottlecaps?}
{209}{}{But on the way, the bottlecaps will definitely not help you.}
{210}{}{Damn, that's right... So, this... Turn to the wall and count to a thousand. Understand?}
{211}{}{You won't get anything.}
{212}{}{Really? Let's take a look at it!}
{213}{}{Hey, be careful with that!}
{214}{}{Great, let's start the fun!}
{215}{}{I don't have caps. Honestly!}
{216}{}{You'RE LYING!}