{100}{}{You have a child in front of you.}
{101}{}{You see the child of one of the colonists.}
{102}{}{I'll tell everyone that you're pushing!}

{104}{}{A real doctor is needed here. Or several servings of Radawaye.}

#Retaliatory remarks
{110}{}{Hello.}
{111}{}{Z-z-z}
{112}{}{Here are my ulcers. Here and here. And here too.}
{113}{}{I feel much better now!}

{116}{}{The situation is running.}
{117}{}{As soon as you find an exhausted vein, you inject an Radaway solution. This will significantly facilitate the treatment process.}
{118}{}{Now you can start treatment.}
{119}{}{The patient is on the mend. Great job!}
{120}{}{Keep it up.}