{100}{}{You see the ranger.}
{101}{}{You see a ranger. His look expresses complete determination.}
{102}{}{As soon as I pack my things, I'm on my way.}

#The first dialog
{200}{}{Stop, don't move! One more step and I'll shoot you in the head.}
{201}{}{Okay, I'm not twitching. Don't shoot.}
{202}{}{Great. I hit without a miss, so no tricks.}
{203}{}{[Next]}
{204}{}{Threats? For me? Fuck you!}
{205}{}{(quickly points the gun at you)}
{206}{}{Stop! Don't shoot!}
{207}{}{Die!}
{208}{}{Eh? What's going on?}
{209}{}{There's something wrong with your head, isn't there? It's a gun. Present. And it shoots. If you twitch, you'll die. Is that clear?}
{210}{}{Si.}

{211}{}{Hmm. (lowers the muzzle of the gun) You don't look like mercenaries. Who are you and what are you doing here?}
{212}{}{Well, tell me before I smear your brains on the wall.}
{213}{}{Someone is going to die. But it won't be me. Got it, cowboy?}

{214}{}{Eh? What's going on?}
{215}{}{(lowers the weapon) Hmm. You don't understand, do you? I feel infinitely sorry for people like you. Maybe I should shoot you to put you out of your misery?}
{216}{}{Shoot? Me? Mummification?}
{217}{}{Probably not. You will serve as bait for mercenaries. Go outside, take a walk there. This is my place. Do you understand? Go, GO!}
{218}{}{Uh, walk. Walk!}

{220}{}{I am a simple traveler, looking for useful junk in these ruins.}
{1220}{}{I am a simple traveler, looking for useful junk in these ruins.}
{221}{}{Unconvincing. Either you're not here of your own free will, or you're working for mercenaries from the garrison.}
{222}{}{You can't ask for food in the garrison. We have to look for it in the ruins.}
{223}{}{I just need scrap metal.}
{224}{}{This is the Museum of Northern Arizona. In the past, one of the attractions of the city.}
{225}{}{I'm telling the truth.}
{226}{}{Your truth. I'm not here by chance.}
{227}{}{Exactly. And I'm going to bring them your head.}

{230}{}{(raises his weapon again) Looks like you think I'm an idiot.}
{231}{}{I see you can't be fooled. I'm here for another reason.}
{232}{}{It's a long time to explain. I'd rather kill you right now.}

{233}{}{Okay. Let's say. Then how did you manage to get around my traps?}
{234}{}{Who did you want to stop with them, children? Maybe it will work for them, but I am an experienced trapper.}
{235}{}{I just have developed mindfulness.}
{236}{}{Traps? Seriously? Chinga tu madre! You should have put a sign at the entrance.}
{237}{}{(show wounds) In fact, this is not quite true.}
{238}{}{I don't know, lucky.}

{240}{}{Damn it, I should have listened more attentively to the saboteur's courses.}
{241}{}{So what, you're not going to shoot?}
{242}{}{What an idiotic answer... (preparing to shoot)}
{243}{}{Stop, stop, stop! I'm here for another reason.}
{244}{}{[Parry the attack]}
{250}{}{Not yet. You can go now. But don't bring a tail with you.}
{251}{}{No problem.}
{252}{}{I need to talk to you.}

{260}{}{The bounty hunter. They say there's a good reward for yours.}
{261}{}{It's true. Faber is haunted by the fact that there is a higher justice over him. Well, your death will serve as a reminder to him...}
{262}{}{Then let's start the fun.}
{263}{}{Wait, I don't want to fight you.}
{264}{}{Sure. After all, you're trapped.}
{265}{}{I need Faber's head a lot more. We could join forces.}
{266}{}{To hell with it, let's fight!}
{267}{}{What are you talking about?}
{268}{}{My people are being held in the garrison, I have to release them.}
{1268}{}{My people are being held in the garrison, I have to release them.}
{269}{}{So that's what motivated you to go hunting? This is quite in the spirit of Faber.}
{270}{}{So you won't shoot?}
{271}{}{But in vain. Get it!}

{280}{}{I'm trying to free my relatives from the pen.}
{281}{}{Were they enslaved too? Faber's people are getting bolder every day. Previously, they forced only criminals to work, and now they enslave innocent citizens.}
{282}{}{What about weapons? You're not going to shoot, are you?}

{283}{}{I'm a ranger. And I'm here to restore justice.}
{284}{}{Glad to meet you. But I don't recall asking for support. This will jeopardize my cover.}
{285}{}{I'm here rather of my own free will.}
{286}{}{Then we will find a common language. But make sure that there is no tail behind you.}
{287}{}{Of course.}

#Repeat dialog
{300}{}{Speak.}
{301}{}{See you later, Ranger.}

#Traps
{310}{}{Show me your traps, otherwise I won't get out of here.}
{311}{}{Either fools or traitors ask for this. I'm alive because of this secret, and you're asking me to reveal it.}
{312}{}{Clearly. Then my death will be on your conscience. Later.}

{313}{}{I'm a ranger too, you can trust me.}
{314}{}{Heh, recruits are always pussies. Go around doorways and don't touch the back door.}
{315}{}{Thank you.}

{316}{}{You need a spy in town, don't you?}
{317}{}{Hmm, maybe... Go around doorways and don't touch the back door.}
{318}{}{Thank you.}
{319}{}{No.}
{320}{}{Ranger showed all his traps within the building.}
{321}{}{Do you want me dead?}
{322}{}{No... Okay, I'll show you. Go around doorways and don't touch the back door.}
{323}{}{Thank you.}

#Questions
{330}{}{Tell me about yourself.}
{331}{}{Ranger Keruk, Eastern Branch of the Arizona Rangers.}
{332}{}{I want to know more about you.}
{333}{}{Now I know enough about you.}
{334}{}{How did you become a ranger?}
{335}{}{The Rangers took me in when I was a kid. My village was burned by slavers, and the inhabitants were subdued. Since then, I have been training hard to prevent a similar story in the future.}
{336}{}{Are you alone here?}
{337}{}{It is more profitable to act alone in Flagstaff. It's easier to avoid mercenaries this way.}
{338}{}{I don't think that only one ranger was sent to eliminate an entire gang.}
{339}{}{Damn right. Our commanders don't want to interfere in local affairs. So I had to take the situation into my own hands. However, no one stopped me when I left.}
{340}{}{Do you think the Rangers will take you back after that?}
{341}{}{I'm still a ranger! The badge and rank are still with me. They will reprimand you for complacency, but these are small things.}
{342}{}{You have an unusual name.}
{343}{}{There are not many people of my tribe left. You've hardly heard of us.}
{344}{}{Sounds like an Indian name. Mojave, Hopi... Navajo?}
{345}{}{Hmm. I'm surprised. Usually, our tribes stayed hidden from the white people after the Fire Rain. I left the Reservation when the slavers came.}
{346}{}{Our stories have something in common. My village was also enslaved and burned.}
{347}{}{I'm sorry... (puts some rifle cartridges in your hands) You should get revenge.}
{348}{}{Uh, thanks.}
{349}{}{Absolutely.}

{370}{}{Tell me about the Rangers.}
{371}{}{For example?}
{372}{}{Tell me more about the Rangers.}
{373}{}{Enough about the Rangers.}
{374}{}{Who are you anyway?}
{375}{}{We are defenders of Law and Order. We catch criminals, protect settlers, and help in restoring a normal peaceful life.}
{376}{}{[Next]}
{377}{}{Therefore, an ordinary ranger is primarily an elite fighter and a master of survival in the desert.}
{378}{}{Why have I heard so little about you?}
{1378}{}{Why have I heard so little about you?}
{379}{}{Because we are not proud of our achievements. Or because the rest of the world sees us only as bounty hunters.}
{380}{}{What does it take to become a ranger?}
{381}{}{Go through 5 years of combat training, and then prove your readiness on a combat mission. But many cadets can't stand training and deprivation.}
{382}{}{Uh, what happens to those who failed?}
{383}{}{Some die on a mission, and others go to the wastelands to become guards, mercenaries, or caravanners. Some are lucky to find their place on the base as staff workers.}
{384}{}{Where is your base located?}
{385}{}{Why would I disclose this information to you?}
{386}{}{My interest has no evil intentions.}
{387}{}{I want to join the Rangers.}
{388}{}{The Rangers can help me rescue the slaves.}
{389}{}{}
{390}{}{You can give the coordinates to my enemies. I can't let that happen.}
{391}{}{Your doubts are understandable. Forget about this question.}
{392}{}{OK, I'll manage. Forget it.}
{393}{}{Okay, I'll show you on the map. The base is located on the Colorado River, right inside the walls of the old dam.}
{394}{}{Thank you.}

{400}{}{Shall we talk about your mission?}
{401}{}{I'm a ranger. My duty is to protect the law and justice in these lands. The colonists broke the rules by taking the path of slavery. My bullets will be their punishment.}
{402}{}{What did you say about your mission there?}
{403}{}{Let's change the subject.}
{404}{}{Back to the topic of your mission.}
{405}{}{Outsiders suffer from your actions, not just criminals.}
{406}{}{For the sake of eradicating a greater evil, one has to resort to a lesser one. These are justified losses.}
{407}{}{Does your conscience bother you?}
{408}{}{No.}
{409}{}{The colonists also maintain law and order.}
{410}{}{Yes, but only within the framework of its disgusting colonial society to the detriment of the rest of the inhabitants. You can't do that. No one invited them here, they were not asked to build a city and restore mines by slaves.}
{411}{}{What are you trying to achieve?}
{412}{}{I won't rest until Roy Faber breathes the air of Arizona. And while there are people in his pen.}
{413}{}{Faber's death or the prisoners' escape? You have serious ambitions...}
{414}{}{So it was you who shot the patrolmen from the garrison?}
{415}{}{That's right. They got what they deserved.}
{416}{}{What "merits" are you talking about?}
{417}{}{Involvement in the criminal acts of Roy Faber: tyranny, slavery, banditry.}
{418}{}{Do the Rangers encourage killing?}
{419}{}{Only for good purposes or self-defense.}
{420}{}{Do you know that Faber has put a bounty on your head?}
{421}{}{He should raise the price three times.}
{422}{}{What do you know about Faber?}
{423}{}{A tyrant with ambitions. Dreaming of his empire. But in fact, just a criminal who oppresses other criminals.}

{450}{}{I'm asking you to leave Flagstaff.}
{451}{}{I'll stay here.}
{452}{}{OK, stay, I don't mind.}
{453}{}{You'll regret it. You'll see.}
{454}{}{What could make you change your mind?}
{455}{}{I will not rest while slavery reigns in this place.}
{456}{}{Your base is flooded. Don't you need to hurry to help your own?}
{457}{}{What are you talking about?}
{458}{}{I don't know. Just rumors. Forget it.}
{459}{}{Well, yes, you kept radio silence, so you don't know yet that the dam is washed out.}
{460}{}{This is very bad news... I'll have to contact the outpost. If they confirm your words there, I will return to the base.}
{461}{}{That's settled.}
{462}{}{The general demands to return to the base. This is an order.}
{463}{}{Damn it, why can't he leave me alone?! My mission is too important to give up now.}
{464}{}{You forgot about the rest of the world. Your help at the base may be more important and more useful.}
{465}{}{Hmm. Maybe so. I must have been drugged by a thirst for revenge. Okay. I will break the radio silence and then return to base.}
{466}{}{That's good.}
{467}{}{You're not being honest with yourself. Think about your motives.}
{468}{}{My motives are to eradicate injustice in these lands.}
{469}{}{Well, it's hard to argue with that. Stay if you want so much.}
{470}{}{Looks like you can't be persuaded. I'm leaving.}
{471}{}{No. You're just obsessed with your past.}
{472}{}{What do you know about my past? I fought so much that I forgot about peace... Home, family... They are gone because of scum like Faber!}
{473}{}{Stop killing. Go back to your people. They need you.}
{474}{}{Well, if that's the case, then I can't convince you otherwise. Fight on.}
{475}{}{I'm staying.}
{476}{}{It looks like I was obsessed. But the general warned... Okay, I will leave Flagstaff and return to base. Thanks, buddy.}
{1476}{}{It looks like I was obsessed. But the general warned... Okay, I will leave Flagstaff and return to base. Thank you, miss.}
{477}{}{Good luck.}
{478}{}{Better hurry up.}

{480}{}{Faber is dead. Is that enough for you?}
{481}{}{So is it true? (inhales noisily and pauses) You know, I don't feel anything about this. It seemed to me that having eradicated evil, I would find peace. But now I finally understand. A new one will take the place of one Faber. And so it will continue again and again... Because people don't change. The General was right when he said I was possessed. Thanks for the help. I have to get back to base.}
{482}{}{Ugh, it's good that we solved this issue.}
{483}{}{Yeah, go ahead.}