{100}{}{You see a Smart Guy.}
{101}{}{You see a skinny man with glasses. He is busy with some calculations.}
{102}{}{Finally... peace...}

#Floating replicas
{110}{}{So, uh, how much is eight by six?}
{111}{}{I don't know what these numbers mean.}
{112}{}{If I finish early, will they give me another fried rat?}
{113}{}{Power failure again.}
{114}{}{This iron will last no more than a year.}
{115}{}{It seems it's not just "white noise".}
{116}{}{Sometimes strange sounds are heard at low frequencies.}
{117}{}{We need to update the call signs for patrols.}
{118}{}{The last patrol never got in touch.}
{119}{}{We may be bugged.}

#Dialog
{200}{}{(adjusts his glasses, peering into your face) Oh, Mom, what are you doing here?}
{201}{}{I'm looking for my relatives. Have you heard anything about the peasants from the Villa?}
{202}{}{That's it... Okay, okay, I know about them. The mercenaries dragged a whole crowd of peasants here and locked them up with the rest of the prisoners. Don't even think about going to their rescue - it will end badly.}
{203}{}{Is there a way to get into the pen?}
{204}{}{Well, if you have a lot of caps, then Faber will let you in. I just don't know if it will *release*... I'll tell you one thing - the prison guards have a lazy job, so try to suck up to one of them.}
{205}{}{Wait a minute, I need to know more.}
{206}{}{Then I'll do it myself.}
{1206}{}{Then I'll do it myself.}
{207}{}{What do you want?}

{208}{}{What is this place?}
{209}{}{This is a radio station. It is used to communicate with mercenaries at a distance. And you should get out of here as soon as possible, otherwise there is no place for outsiders here.}
{210}{}{Where did all this equipment come from?}
{211}{}{I don't know. It was already standing here when I was brought in.}
{212}{}{How interesting. And on what frequency do the mercenaries talk?}
{213}{}{That's exactly what I shouldn't say. If you want to know, go to the boss and ask him.}
{214}{}{You're scoffing too much, four-eyes. Tell me the frequency, now!}
{215}{}{Be quiet! They'll hear us... Okay, look, this is the frequency for patrolmen, and this is for jailers. Just don't tell anyone!}
{216}{}{Yeah.}
{217}{}{I'm going to scream! I'll scream and they'll catch you!}
{218}{}{But you don't have to do that. Calm down.}

{219}{}{So much equipment for the sake of communication alone?}
{220}{}{Well yes... Except for the management of collars.}
{221}{}{Do you know how to disable prisoners' collars?}
{222}{}{We need an access code to the terminal. Only Faber and I have it. And I won't tell it to you.}
{223}{}{Come on, do something useful for the oppressed like you. This is your chance for salvation.}
{224}{}{You're going crazy! Get caught by one of the mercenaries - and you and I are waiting for something worse than the gallows! You'd better get out of here before they see us together. I don't want any problems.}
{225}{}{Well... Maybe so. I don't know if I can trust you, but we can pay with our lives for such sabotage. Here is the password, but proceed as carefully as possible!}
{226}{}{The correct solution.}
{227}{}{It looks like the equipment is not from here.}
{228}{}{How should I know? I'm just pushing buttons.}
{229}{}{Well, maybe so. The building is dilapidated, but the equipment will be newer. And the antenna is clearly out of place.}
{230}{}{We'll see about that.}
{231}{}{For now.}

{250}{}{Who are you?}
{251}{}{They called me a Smartass here. I wasn't good enough to work in the mine, so they put me here to monitor radio communications.}
{252}{}{Do you want to get out?}
{253}{}{Me? To freedom? But... What am I going to do there? The boss, though angry, at least feeds and protects from robbers. And where can I go without him? I don't know...}
{254}{}{Bitch, you pawned me to Faber!}
{255}{}{P-wait! Have mercy! Don't hit me! I'm just a prisoner! What was I supposed to do? After all, you have zero chances against mercenaries, and I will live here until the end of my days. If Faber had found out, he would have just killed me!}
{256}{}{Better shut up, pussy, before I shove your glasses down your throat.}
{1256}{}{Better shut up, pussy, before I shove glasses down your throat.}
{257}{}{Okay, live for now. I really shouldn't have trusted the first person I met.}
{258}{}{While the equipment was in working order, it was a radio station. Now it's just a warehouse of all sorts of junk. But outsiders don't belong here anyway.}

{260}{}{Faber is dead. You're free.}
{261}{}{God, why?! Without Faber, the whole of Flagstaff will come to an end! The mercenaries will now fight over his place, and pogroms and looting will begin in the city! Do you have any idea how much work has been invested in the arrangement of this place? Thank you, of course, for freedom, but I don't need it anymore.}
{262}{}{Hmm...}
{263}{}{Why didn't you run away with the rest of the prisoners?}
{264}{}{And where should I run? In the wasteland? The first mole-rat will bite me there. And in the city, they won't even look at me. Prison is the only place where my talents were appreciated, and given food and protection. Think what you want, but I was satisfied with this life.}
{265}{}{That's the irony. Okay, stay here, loser.}