{100}{}{You see a servant.}
{101}{}{You see a servant with traces of beatings all over his emaciated body.}
{102}{}{Can I really go?}
{103}{}{Help! The owner will kill me!}

#The first dialog
{200}{}{(looks around in confusion) The owner... dead?}
{201}{}{Aren't you happy?}
{202}{}{What am I going to do without a host?! Master... Yes! I have to find a new owner! We need to get back to the paddock. There is no other way...}
{203}{}{It seems like you don't know anything else in life. Well, come on.}
{204}{}{ (the servant falls at your feet and diligently bows with his bald forehead) Thank you, mi señor! I am very grateful to you, señor! Thank you!}
{1204}{}{ (the servant falls at your feet and diligently bows with his bald forehead) Thank you, mi señora! I am very grateful to you, señora! Thank you!}
{205}{}{Come on, calm down. By the way, I want to ask you.}
{206}{}{Looks like you're not used to being treated kindly. I'll be back when you come to your senses.}
{207}{}{Hey, don't get me dirty with your dirty hands! Away!}

{210}{}{Si, mi señor?}
{1210}{}{Si, mi señora?}
{211}{}{Free.}
{212}{}{Another question.}

{220}{}{Tell me why the owner beat you.}
{221}{}{For the cap, señor. I, an insignificant lump of dirt, probably dropped it when I went shopping for the owner.}
{1221}{}{For the cap, señora. I, an insignificant lump of dirt, probably dropped it when I went shopping for the owner.}
{222}{}{Did he beat you because of ONE cap?}
{223}{}{The cap is a lot, señor. On the cap you can buy... half an iguana. But... (decides to look up at you and immediately drops down) Yes, it's a small amount, señor. The owner is angry because of the debts because the city is now restless.}
{1223}{}{The cap is a lot, señora. On the cap you can buy... half an iguana. But... (decides to look up at you and immediately drops down) Yes, it's a small amount, señora. The owner is angry because of the debts because the city is restless now.}
{224}{}{It can be seen that things are not going well here.}

{230}{}{I'm looking for my relatives. They were enslaved just like you.}
{231}{}{All slaves are kept in a pen until they have a job. The paddock is further down the main street.}
{232}{}{Do you know how to help them escape?}
{233}{}{Escape? It's impossible, mi señor. There are guards all over the city, a siren is working, and prisoners are wearing collars. But you can negotiate with the commander of the garrison. He was looking for people for some special job.}
{1233}{}{Escape? It's impossible, mi señora. There are guards all over the city, a siren is working, and prisoners are wearing collars. But you can negotiate with the commander of the garrison. He was looking for people for some special job.}
{234}{}{So there is still a chance to solve the problem in peace? This is encouraging.}

{240}{}{How did you get into slavery?}
{241}{}{I was sold from one hand to another until I ended up here.}
{242}{}{So you've lived in slavery all your life?}
{243}{}{Si, señor. Except for the early years... when I was taking care of myself.}
{1243}{}{Si, señora. Except for the early years... when I was taking care of myself.}
{244}{}{An unenviable fate.}