{100}{}{There is a guard in front of you.}
{101}{}{You see an ordinary mercenary who watches the entrance to the colony.}
{102}{}{That would be right away.}
{103}{}{Until this guard comes to his senses, you can sneak into the pen.}
{104}{}{Hr-r-r... Eh? Come in...}
{105}{}{Wait, closed territory, entrance only with the permission of the boss.}
{106}{}{I warned you!}
{107}{}{This is a high-security area. Don't try to create problems.}

#Retaliatory remarks - a good attitude
{110}{}{I'm watching you.}
{111}{}{Don't try to get into the pen without permission.}
{112}{}{What's behind that door? Your death if you go there.}
{113}{}{Login only with the permission of the boss.}
{114}{}{You can't go there.}

{120}{}{That's right, you have a security clearance.}
{121}{}{You can go to the pen.}
{122}{}{Come in, the door is open.}
{123}{}{Do you have a security clearance? Then come on in.}