{100}{}{In front of you is a clockwork device.}
{101}{}{You see an ordinary mercenary who keeps order in the garrison.}
{102}{}{Enough! I'll give you my caps if you calm down!}

{200}{}{Stop! What's your business in the garrison?}
{201}{}{None of your business.}
{202}{}{As far as I understand, my tribesmen are being held here.}
{203}{}{Probably none.}
{204}{}{Okay, come on in. Actually, I don't care, but I have to ask.}
{205}{}{Clear.}
{206}{}{It is forbidden to go outside at night. Get back to the apartment block before I blow your head off.}

{210}{}{What do you want?}
{211}{}{I bought your debt from the bar. Now you have to tell me.}
{1211}{}{I bought your debt from the bar. Now you have to tell me.}
{212}{}{Nothing.}
{213}{}{Ha! So you'll never get them.}
{214}{}{Why can't we just give the bottlecaps away?}
{215}{}{This is a crime. And for crimes they work in the mines here.}
{216}{}{In that case, I'll have to take them by force.}
{217}{}{We'll see about that.}

{218}{}{Why would I do that? I work in a position where it's easier to pick up than to return. Do you want to experience it the hard way?}
{219}{}{There is also power over you. If you do not return the bottlecaps, you will end up in hard labor.}
{220}{}{It's useless to talk to you. I'll just take the bottlecaps by force.}
{221}{}{I don't think I want to. Later.}

{222}{}{You're bluffing. Besides me, there's a whole crowd of mercenaries here.}
{223}{}{Well, well.}
{224}{}{You'd better disappear. Before I get mad.}
{225}{}{Calm down, don't get angry... Here are the bottlecaps. Will you leave me alone now, eh?}
{226}{}{That would be right away.}
{227}{}{Here, take all the bottlecaps, just don't touch me!}
{228}{}{That would be right away.}
{229}{}{Okay. I don't want to make anyone angry.}