{100}{}{You have a prisoner in front of you.}
{101}{}{You see an unpleasant-looking person. He is depressed and exhausted.}

#Retaliatory remarks
{110}{}{If you get here, there will be no way out.}
{111}{}{Don't even dream of escaping.}
{112}{}{Hey! Don't know how to get rid of the collar?}
{113}{}{My relatives don't know I'm here.}
{114}{}{When will the ration be issued?}
{115}{}{Do you have anything to eat?}
{116}{}{Hey, how is it out there?}
{117}{}{The warden has a heavy hand.}
{118}{}{I'm so tired I want to die!}
{119}{}{Hi.}