{100}{}{You have a prisoner in front of you.}
{101}{}{You see one of the prisoners of the colony. His look does not inspire confidence.}

#Dialog
{200}{}{What do you need?}
{201}{}{Bye.}
{202}{}{What are you serving time for?}
{203}{}{(crooked grin) For murder.}
{204}{}{Just one murder?}
{205}{}{I've lost count. Highway 17 was strewn with the bones of travelers whom my brothers and I had robbed. Eh, there were times.}
{206}{}{There are hardly so many travelers there.}
{207}{}{Damn, maybe I lied a little. Or maybe he didn't kill anyone at all. But in recent years, the highways have been really restless. There are more people, and there are not enough places for everyone. So they wander along the highways who where.}
{208}{}{How did you end up here?}
{209}{}{We stole cattle from the distillers. It turned out that the cattle were intended for influential people in Phoenix. So they hired bounty hunters. They pinned our gang in the old ruins. Real combat vehicles, trained, in gear, all business. I had to give up. Now it remains to regret that I chose hard labor instead of execution.}
{210}{}{If there is a massacre with the jailers, will you help me?}
{211}{}{Two against a crowd? You're delusional!}
{212}{}{Two against a crowd? Well, if you think about it, there is a chance, and if I die, it's even better. Okay, it's a deal. Can you get me a weapon?}
{213}{}{That's reasonable. Cover your rags so no one can see...}