{100}{}{Here is a mercenary.}
{101}{}{You see an ordinary mercenary who keeps order in the colony.}
{102}{}{*Muttering something to himself*}

#Retaliatory remarks - a good attitude
{110}{}{I'm watching you.}
{111}{}{Do you want to become a warden?}
{112}{}{What are you doing here?}
{113}{}{Our colony is open to everyone... Well, you know.}
{114}{}{You can make good money here.}
{115}{}{They say that raid on the Villa brought excellent bottlecaps.}
{116}{}{Don't hang around here doing nothing.}
{117}{}{Don't talk to prisoners.}
{118}{}{It's better not to bother the boss when he's furious.}
{119}{}{Talk to the boss, not me.}

#Retaliatory remarks - bad attitude
{120}{}{I'm watching you.}
{121}{}{I hate people like you.}
{122}{}{Looking for trouble?}
{123}{}{This is a colony, go for a walk somewhere else.}
{124}{}{Don't bother me.}
{125}{}{Go away, this is a closed area.}
{126}{}{You weren't invited here.}
{127}{}{Do you want to go to the pen? Now we'll arrange it for you...}
{128}{}{Better not piss me off.}
{129}{}{Don't linger.}