{100}{}{You see a colonist.}
{101}{}{You see a citizen of the colony.}
{102}{}{Better not bother me.}
{103}{}{Damn psycho, why did you kill my servant?! And who will pay me back the bottlecaps for it?}

#Random replicas
{110}{}{You're nothing}
{111}{}{Mole-rat brat!}
{112}{}{You're good for nothing.}
{113}{}{Get up and wipe your snot, you trash.}
{114}{}{I don't even want to dirty my shoes about you.}
{115}{}{Did I pay my caps for *this*?}
{116}{}{It looks like the jailers overestimated your price, a lump of dirt.}
{117}{}{*Pushes the servant with his foot*}
{118}{}{Are you *showing me* your teeth?!}
{119}{}{Are you getting sleepy? How about a shoe in your teeth?}
{120}{}{Remember who your master is.}

#The first dialog
{200}{}{(a funny sight unfolds right in front of you, as a skinny peasant angrily beats and kicks the constantly apologizing servant)}
{201}{}{Hey! Why are you hitting this man?}
{202}{}{This is not a person, but my property. I bought him out of the pen as a servant. And he's a shoddy servant. We'll have to knock this dirt off him thoroughly to make sense. What's it to you? Pass by and don't get involved in other people's business.}
{203}{}{You're right, it's none of my business.}
{204}{}{It's good that we found mutual understanding. Stand up! You'll sleep outside tonight. In the meantime, clean the kitchen floor. And to shine!}
{205}{}{[Next]}
{206}{}{A beaten and exhausted servant only spoils the reputation of his master.}
{207}{}{NO one is interested in your opinion HERE!}
{208}{}{Hmm, these words make you think. Okay, I'll be lenient today. But only today.}
{209}{}{[Next]}
{210}{}{I'll pay 5 caps if you leave him alone.}
{211}{}{Oh, do you hear, you jerk? For your peace of mind, I get paid as much as five caps! Who would have thought that you could earn this way, huh?}
{212}{}{Here are 5 caps.}
{213}{}{Not bad. Slave! You can be free for today.}
{214}{}{[Next]}
{215}{}{If you hurt him again, you'll regret it.}
{216}{}{really? Then listen to me, redneck. This city has its own rules. And if you intend to break them, then someone will call the guards. And then we'll see which of us will "regret".}
{217}{}{Okay, okay, I'm really hot today... But just dare to touch me and I'll call the guards. You definitely won't like it.}
{218}{}{[Next]}
{219}{}{}
{220}{}{Let me give you some advice. I don't know what's on your mind, but the servants in this colony have to be kept on a leash. Otherwise, it will end badly... All the best.}
{221}{}{Goodbye.}