{100}{}{You see a miner.}
{101}{}{You see a terribly dirty man. His manners are no better.}

#Retaliatory remarks
{110}{}{*Chokes while coughing*}
{111}{}{We survive only thanks to this mine.}
{112}{}{Each shift underground may be the last.}
{113}{}{This shift is going to be a long one.}
{114}{}{These mole rats are real giants.}
{115}{}{Mole rats eat the body, but do not touch the head and clothes.}
{116}{}{I'm telling you - the king of rats exists!}
{117}{}{I want to eat.}
{118}{}{Hey, you! Do you know how to get rid of the collar?}
{119}{}{If you got here, then you can forget about the will.}