{100}{}{Here is a miner.}
{101}{}{You see a dirty emaciated man.}
{102}{}{You save me from torment.}
{103}{}{Wow, you're one of the brave people. I won't tell anyone who killed Knut.}

{110}{}{Ouch! Oh-oh!}
{111}{}{Have mercy, master!}
{112}{}{It hurts me a lot!}
{113}{}{Help me! Please!}
{114}{}{Ah! Help me, I'm dying!}

{120}{}{You're the best.}
{121}{}{I want to become a righteous man. Like you.}
{122}{}{Words are not enough to convey my gratitude.}
{123}{}{The new supervisor is better than the old one.}
{124}{}{Knut was a terrible man.}
{125}{}{How did you manage to fire Knut?}

#Dialog
{200}{}{Thank you, friend. I thought I was finished. Although I no longer know which is better - to continue the torment in this penal servitude or to immediately go to a better world?}
{1200}{}{Thank you, ma'am. I thought I was finished. Although I no longer know which is better - to continue the torment in this penal servitude or to immediately go to a better world?}
{201}{}{Who beat you up like that?}
{202}{}{It was that warden over there. All the prisoners hate him here, even the nickname was given - the Whip. He's as evil as the devil himself. Just give me a reason - and immediately grabs a stick.}
{203}{}{And what did you do to make him angry this time?}
{204}{}{I have no strength left because of the work. So I fell to the ground with the cart. He scattered all the ore under his feet.}
{205}{}{And it pissed him off? You have a nervous situation here...}
{206}{}{That's not the word. We are not keeping up with the schedule, and then there are these rumors about giant rodents in the mine. So the bosses are angry, they break down at every opportunity.}
{207}{}{I see.}
{208}{}{Hey, you don't seem to be one of the wardens. A caravan driver, or what?}
{209}{}{No. I'm looking for my family. Peasants from the Villa. Do you know anything about them?}
{210}{}{And how - everyone knows them here! But I have to disappoint you - Sancho and Hugo have gone underground and have not yet returned.}
{211}{}{Thanks for the information. Rest if you can.}
{212}{}{None of your business.}
{213}{}{Okay, okay. My business is to obey, master. But thanks for patching it up anyway. I am forever in your debt now.}
{1213}{}{Okay, okay. My business is to obey, mistress. But thanks for patching it up anyway. I am forever in your debt now.}
{214}{}{Exactly. Get out of the way.}
{215}{}{I was glad to help. Goodbye.}
{1215}{}{I was glad to help. Goodbye.}
{216}{}{Actually, I'm looking for my family. Peasants from the Villa. Do you know anything about them?}

{220}{}{Hey, this is my savior!}
{1220}{}{Hey, this is my savior!}
{221}{}{Bye.}
{222}{}{Hush, you fool.}