{100}{}{You see a miner.}
{101}{}{You see a terribly dirty man with an extremely intense look.}
{102}{}{It's over for me, friend.}
{1102}{}{It's over for me.}

{200}{}{(in front of you is an emaciated man in dirty torn clothes; he is tensely holding a knife near a slave collar, and drops of cold sweat are running down his forehead)}
{201}{}{What are you doing?}
{202}{}{Uh...}
{203}{}{Stay away! I will do it! It is better to die than to endure this hard labor!}
{204}{}{You can not. Look at you - you're a weakling.}
{205}{}{Don't say that! I was placed here by force. What could I do?}
{206}{}{That's it. Some excuses...}
{207}{}{Shut up! Shut up!}
{208}{}{Does it really hurt your eyes, sucker?}
{209}{}{And now you want to run. But won't the collar kill you?}
{210}{}{Don't do that. This collar will kill you!}
{211}{}{I'm sorry, I can't help you. You just have to open up. Come on - what are you waiting for?}
{212}{}{I KNOW! But my life is already over. If I die, at least I'll get rid of the torment. And if not? If they lie to us about collars, I can escape from here.}
{213}{}{Then it's a good idea. What if it turns out? Come on, do it. Be bold!}
{214}{}{Wuss. I'll turn you over to the warden. It will be fun to watch.}
{215}{}{You should think it over carefully. Don't give in to emotions.}
{216}{}{What do you know? I'm in hard labor! Yes, I was put in jail for the case, but do I have to endure humiliation and beatings from the guards? It's not fair!}
{217}{}{Whatever you did, it's your fault. No one will feel sorry for a creature like you.}
{218}{}{So come on, do it. What are you waiting for?}
{219}{}{Okay. I'll try to help you. After all, I still need to get my family out of here.}
{220}{}{It's true? Then I'm sorry, I overreacted. Listen, they say the collars are controlled by a radio antenna on the territory of the garrison. You just need to disable it or destroy it. Can you handle it?}
{221}{}{Okay. I'll try. Wait for the signal.}