{100}{}{Here is a savage.}
{101}{}{You see one of the prisoners of the colony. He is distinguished from the others by his prominent facial features.}

#Dialog
{200}{}{Don't talk to me, stranger. The others won't understand you.}
{1200}{}{Don't talk to me, woman. The others won't understand you.}
{201}{}{Yet.}
{202}{}{What's your name?}
{203}{}{The locals call me Howler. But my real name is much more complicated.}
{204}{}{Aren't you from around here?}
{205}{}{In front of. My tribe has lived in these mountains for three generations. Now I'm the only local left.}
{206}{}{What happened to your tribe?}
{207}{}{Evil people came with weapons. They took everything from us and forced us to work in the mine. Since then, only I have remained of the entire tribe.}
{208}{}{Would you like to escape from here?}
{209}{}{I have nowhere to run. My house was destroyed, and my relatives died. It remains only to wait for the Day of the Last Exhalation.}

{210}{}{If there is a massacre with the jailers, will you help me?}
{211}{}{Such a senseless battle is not for me.}
{212}{}{Hmm. To die in battle is death for a real warrior. I agree.}
{213}{}{Great. Wait for the signal to attack.}
{214}{}{As you wish, but then it will be too late.}