{100}{}{You see Uncle Tom.}
{101}{}{You see a strong and serene resident of the colony. Judging by the look, he's been through a lot.}

{200}{}{Hi. My name is Tom. And I live in this shack. Let me know what brought you to me.}
{201}{}{I'm new here. I just want to get to know you.}
{202}{}{Oh, so are you trying to find your "uranium vein" too? Forget. This city is no longer the one that was once on the posters. If you want to earn money, you will plow like a damn.}
{203}{}{I'm not here for a living. I'm looking for my relatives.}
{204}{}{Well, good luck then. You'll need it.}
{205}{}{Can I ask you a couple of questions?}
{206}{}{Okay. Later.}

{210}{}{How can I help?}
{211}{}{Nothing today. Goodbye.}

{220}{}{Who are you?}
{221}{}{They called me Uncle Tom.}
{222}{}{Anything else you want to tell me?}
{223}{}{No.}
{224}{}{Okay, forget it.}
{225}{}{Come on, tell your story, I won't tell anyone.}
{226}{}{The thing is, I just don't want to.}
{227}{}{Okay, forget it.}
{228}{}{It looks like you've had a hard time keeping your mouth shut.}
{229}{}{Damn right. Perhaps I am the only one who was able to survive hard labor and gain a foothold in this city. But the colonists still look down on me.}
{230}{}{Why did they treat you like that?}
{231}{}{So, so, are you an ex-criminal?}
{232}{}{Caught stealing mutfruits. I have served my time in hard labor and am now clean as a whistle before the world and before myself.}
{233}{}{Then why is your house so dirty?}
{234}{}{You mean the writing on the walls? The local guys don't know where to blow off steam. They found a target in me. After all, the bastards know that I don't want to create problems for myself.}
{235}{}{Thank you for your frankness, Tom.}
{236}{}{If I were you, I'd rip their hands off. But you know better.}
{1236}{}{If I were you, I'd rip their hands off. But you know better.}

{240}{}{What are you doing in Flagstaff?}
{241}{}{I work part-time here and there, and in my spare time, I dig through the ruins in search of useful scrap. There is enough for life so far.}
{242}{}{Clear.}
{243}{}{How long have you been living in this colony?}
{244}{}{A few years, probably. I can't count, sorry.}
{245}{}{Clear.}
{246}{}{Roy Faber is dead. You should be happy.}
{247}{}{Rejoice? I don't know... The colony taught me to obey and live by the laws of others. It's cruel, but it's right. Look at the order Faber achieved with his dictatorship. But now others will take his place. And no one knows how it will end. So I do not know whether to be happy or not.}
{248}{}{Hmm, this point of view is worth considering.}
{249}{}{You're just a weakling, Tom. Accept it.}
{250}{}{Do you know where to get scrap metal to fix the robot in the mine?}
{251}{}{Some parts you can buy from me, but these are the last stocks.}
{252}{}{That's not enough, Tom. Where can I get more details?}
{253}{}{Are you kidding? How can I fix a huge complex machine with this junk?}
{254}{}{Let me think. There are still unexplored areas in the old city, but these are dangerous places. But the easiest way is to find scrap metal from garbage collectors in Garage City. It's a small town west of here.}
{255}{}{Thank you.}
{256}{}{I see.}

{260}{}{Do you know that someone robbed the Sonoran Express?}
{261}{}{Heard something like that. But I have nothing to do with it.}
{262}{}{If you know who did it, you'd better tell me.}
{263}{}{Hmm... Listen, buddy, I don't want anyone to get hurt, okay? And this arrogant lady from the postal service still deserves her fate.}
{264}{}{This clarifies everything. Okay, have a good stay.}
{265}{}{I'll pay 10 caps if you tell me who did it.}
{266}{}{You can say a lot for 10 caps. But do you have them?}
{267}{}{I don't have them with me. But I'll drop it off at an opportunity. Bye.}
{268}{}{Here are 10 caps.}
{269}{}{Wait a minute, I'll check if there's anyone outside the window... Yes, it was through this window that I saw everything. The neighborhood kids did it. But keep in mind that this conversation did not happen. And don't you dare hurt the children.}
{270}{}{Thanks for being honest, Uncle Tom. I promise that no one will get hurt.}
{271}{}{You don't order me. And in general, pray that I don't turn you in as a patron of young thieves.}
{1271}{}{You don't order me. And in general, pray that I don't turn you in as a patron of young thieves.}
{272}{}{Please tell me what you know. I want to help.}
{273}{}{Help who? Help yourself to earn caps on someone else's grief? No, I'm not signing up for this.}
{274}{}{It's worse for you. Ciao.}
{275}{}{It looks like you don't know anything. Bye, Uncle Tom.}
{276}{}{I promise - I will not betray a real thief. I just want to return the stolen goods.}
{277}{}{Promise? (sigh) The neighborhood guys did it. I saw everything through the window. But keep in mind that this conversation did not happen.}