{100}{}{You see a mercenary.}
{101}{}{You see one of Faber's mercenaries. He is ready to help you in expelling the savages.}

{110}{}{Don't worry, I'll help.}
{111}{}{Soon there won't be a single savage left here.}
{112}{}{Just show me who to shoot. The rest is up to me.}
{113}{}{Together we have more chances.}
{114}{}{Look what Arizona was like before Faber came.}
{115}{}{Damn savages...}
{116}{}{This tribe constantly put a stick in our wheels.}
{117}{}{If you see a savage, let me know.}
{118}{}{}
{119}{}{}