{100}{}{You see a hunter.}
{101}{}{This man looks haggard.}
{102}{}{PC! Open the gate. Just don't show up in front of savages.}
{103}{}{The hunter successfully left his camp.}

{200}{}{Hey! You're just in time. Just be quiet! These savages have excellent hearing. Did they send you from Flagstaff?}
{201}{}{Yes. The bartender wants to know what's going on here.}
{202}{}{Shit's going on here, that's what I'll tell you. The savages killed the hunters, and I was locked up in reserve.}
{203}{}{Actually, no. I got lost and was hoping to find a place to sleep.}
{1203}{}{Actually, no. I got lost and was hoping to find a place to sleep.}
{204}{}{Well, welcome to Winon. I'm sorry I'm not offering herbal tea. The savages killed the hunters, and I was locked up in reserve.}
{205}{}{It's terrible.}
{206}{}{}
{207}{}{Help me get out of here? Just be quiet! We cannot cope with such a crowd without weapons.}
{208}{}{Now is not the right time for this. I'll tell you when you can leave.}
{209}{}{I'm sorry, but you'll have to sit in this cage for a while longer.}
{210}{}{OK. I'll take you out.}
{211}{}{Help me get out of the forest, then I'll find my own way.}
{212}{}{Okay.}

{220}{}{Why did the savages attack you?}
{221}{}{Isn't it clear? They wanted to profit from our prey, and at the same time - to show who is the boss here. This tribe has a grudge against our brother for a long time.}
{222}{}{Enough talking.}
{223}{}{And what happened between you?}
{224}{}{When Faber set up a colony in Flagstaff, he first drove the local tribe out of their homes. He killed someone, drove someone to distant lands, and this group remained to rob the inhabitants of the colony. In a word - savages.}
{225}{}{And how did the savages with their sticks manage to defeat you?}
{226}{}{Caught by surprise at night when everyone was asleep, that's the whole trick. They are more adept at such things than us city dwellers.}
{227}{}{Tell me about the surroundings.}
{228}{}{Wild lands. There are almost no people, but there are a lot of different animals. Forests and mountains stretch for miles around. By the way, we set traps for animals around the camp, be careful.}
{229}{}{Can you show me where your traps are?}
{230}{}{Traps are set in the forest thicket in front of the entrance to the camp. Look carefully at your feet.}
{231}{}{Thank you.}
{232}{}{What do you know about these savages?}
{233}{}{This is a clan of a tribe that once lived in these lands. A small number of people. Faber destroyed the main part of them and drove away the rest. But for some reason, these returned. Probably couldn't find places as rich in game.}
{234}{}{Any ideas on how to get rid of them?}
{235}{}{Now it would be a good old shotgun or a detachment of mercenaries from the garrison. In the meantime, I can't even imagine what you can scare them with. They seem to be very superstitious. Otherwise, they would not have placed these totems around the perimeter of the camp.}
{236}{}{Name the nearest city?}
{237}{}{Flagstaff. It's a mining colony southwest of here.}
{238}{}{Thank you.}

{240}{}{You're safe now.}
{241}{}{When they find out I've escaped, they'll raise the alarm. But I'll be far away by then. Thanks for the help. The whole of Flagstaff will know about your help when I get there.}
{242}{}{Good luck.}