{100}{}{Ugo is in front of you.}
{101}{}{You see a slave. If you look closely, you will recognize in his dirty, emaciated face your fellow tribesman.}
{102}{}{Oops, I hope no one at the Villa finds out about this...}
{103}{}{The traitor! You're possessed by Diablo!}
{104}{}{Now Hugo will not be able to return to the Villa.}
{105}{}{Hugo returns to the Villa.}
{106}{}{Of course, friend, as you wish.}
{107}{}{See you at the Villa, amigo.}

#The first dialog
{200}{}{? Good heavens, it's you! And we are already completely desperate.}
{201}{}{I'm here to set you free.}
{202}{}{You're just in time! We would only get to the exit, and then somehow ourselves.}
{203}{}{Tell me what happened first.}
{204}{}{It's all Sancho! He came up with this stupid idea with explosives. None of us knew how to handle it, but he decided to try anyway. You ask him! Sancho has become the main one here.}
{205}{}{Stay here. I'll talk to him first.}
{206}{}{We're at the entrance. Freedom is very close.}

{207}{}{Si?}
{208}{}{That was a rat! I've never seen such a huge and vicious one! Eh, I would like to roast her now...}
{209}{}{Okay, let's go.}

{210}{}{Hey, Hugo, do you remember when you turned me in once?}
{211}{}{What... wait...}
{212}{}{I took the padre's things without asking, and then you told him. And I was punished. Remember?}
{1212}{}{I took the padre's things without asking, and then you told him. And I was punished. Remember?}
{213}{}{(smiling) Yeah, hehe, it was... (confused) like this...}
{214}{}{I'm here now. Saving your skin. How do you feel, Hugo?}
{215}{}{(mutters under his breath) P-sorry... I'm sorry for everything! (wipes away tears)}
{216}{}{That's the same thing. Remember this day... "friend".}
{217}{}{Come on, I'm not angry, calm down. Let's get out of here.}
{218}{}{Come on, forget it.}
{219}{}{It's all right, Hugo, don't worry.}

{222}{}{Ugh, thanks for the help! Then we'll find our own way. But you will have to save the rest of the residents of the Villa. We're of little use now after what we've been through. Good luck.}
{223}{}{Okay. I'll meet you at the Villa.}
{224}{}{Yes, listen, Sancho says we should blow up the mines. Otherwise, the tragedy will repeat itself. If blown up, the company will go bankrupt and stop looking for new slaves.}
{225}{}{Blow up the mines? The idea is for me.}
{226}{}{Sancho is talking nonsense. The explosion will only add work to the slaves.}
{227}{}{Really, will you do it? Then find the explosives in the warehouse inside the mine, the administrator keeps the key to the warehouse with him. Good luck.}
{228}{}{But the company will continue to search for and use slaves. Our escape won't change anything, don't you understand? Okay, you think about it, and it's time for us to hit the road. Good luck.}
{229}{}{I'll think. Now get out of here.}