{100}{}{You see Sancho.}
{101}{}{You see a slave. If you look closely, you will recognize in his dirty, emaciated face your fellow tribesman.}
{102}{}{Oops, I hope no one at the Villa finds out about this...}
{103}{}{The traitor! You're possessed by Diablo!}
{104}{}{Now Sancho will not be able to return to the Villa.}
{105}{}{Sancho returns to the Villa.}
{106}{}{Okay, if it's necessary.}
{107}{}{See you at the Villa, amigo.}

#The first dialog
{200}{}{? It's you? What a surprise! And we already thought we were finished.}
{201}{}{I'm here to set you free.}
{202}{}{Great, you're just in time. Help us get to the exit. Then we will find our own way.}
{203}{}{We're at the entrance. Freedom is very close.}
{204}{}{Where are the others?}
{205}{}{How did you end up in this trap?}
{206}{}{How did you manage to remove the collars?}
{207}{}{What can you tell us about these mines?}
{208}{}{Sancho, I remember you disliked me at the Villa and called me a "one-legged mantis".}
{209}{}{Okay, let's go.}

{210}{}{We were separated when we were brought to this city. Some were left in the pen, including senora Maria, your madre. The others were taken away somewhere, I haven't seen them since.}
{211}{}{It was a failed plan. We wanted to dig a tunnel right into the wasteland and run through it, and for this we had to steal explosives. But everything went wrong. The explosion caused a chain of collapses, and we were cut off from the world.}
{212}{}{One of the slaves said that collars do not work in the mines. }
{213}{}{Just a deep, damp hole. And there are these giant rodents all around. You won't find them in our Villa. They say that there are even more. Lucky we didn't come across them.}
{214}{}{Why did the mercenaries bring you here?}
{215}{}{They made me shovel the damn ore. At the top, it is cleaned and taken to another city. They say that it gives energy, but how it happens - I never understood. We have firewood and oil in our Villa for this, but you can't set fire to the stones! We're probably just being fooled.}
{216}{}{Okay, okay, I was wrong! Let's forget what happened, we're from the same village! I won't say another bad word about you. Honestly.}
{217}{}{Wait, first tell me what happened.}

{220}{}{What?}
{221}{}{That rat was fucking huge!}
{222}{}{Ugh, thanks for the help! Then we'll find our own way. It will be easier for a small group to escape from the mercenaries. In the meantime, take care of saving the rest of the residents of the Villa. We would have helped, but you understand that we are of little use after what we have experienced. Good luck.}
{223}{}{Okay. We'll meet at the Villa.}
{224}{}{Yes, you know, I wouldn't want this tragedy to happen again. Try to blow up these damned mines. Maybe then the company will go bankrupt and stop looking for new slaves.}
{225}{}{Blow up the mines? I like this idea!}
{226}{}{Very doubtful. This will only add work to the slaves.}
{227}{}{That's good. Explosives are in a warehouse inside the mine, and the administrator keeps the key to the warehouse with him. Good luck.}
{228}{}{Yes, leaving these mines is like feeding a rat king! The enterprise will simply find new slaves and continue its inhuman work. Don't you understand? Or are you still shaking from what you've been through? Okay, you think about it, and it's time for us to hit the road. Good luck.}
{229}{}{I'll think. Now get out of here.}