{100}{}{This is Faber's computer.}
{101}{}{Here is an ancient computer. It's amazing that it still works.}

#Dialog
{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Back.}

{210}{}{Request for new prisoners.}
{211}{}{The report of the mine administration: "Due to a shortage of workers, deadlines have been disrupted again. The mine destroys prisoners too quickly. We'll have to look for new blood in the surrounding settlements. There are rumors about wild tribes in the west. It's worth checking out."}
{212}{}{Report on the expedition to the west.}
{213}{}{The mercenaries returned with new blood. The peasants of the Villa turned out to be surprisingly excellent material - strong, healthy, hardy. Savages are worse, but they will also give odds to prisoners from the south. In addition to the peasants, there were provisions and other useful things in the Villa. On the way we found the town of Garage City; the locals offered a business, we need to think about it.}
{214}{}{The incident in the mine.}
{215}{}{A group of convicts disappeared in the mine again, they turned out to be the same peasants from the Villa. Either I underestimated these hillbillies, or our defense system is not reliable enough. We will have to carry out punitive prevention among prisoners.}
{216}{}{Sending prisoners to Phoenix.}
{217}{}{As expected, the fire worshippers immediately bought out the strongest peasants of the Villa and some savages. Compared to the rest of the prisoners, it was the highest quality product. In exchange, we received new weapons and ammunition, which were so lacking. Great deal.}
{218}{}{Reduction of meat supplies.}
{219}{}{Due to problems in San Brahmin, the supply of meat has decreased. We'll have to start hunting for mole rats and get a trapper camp in the mountains. Damn it, more unexpected expenses! On the other hand, this is another incentive for the development of the city.}
{220}{}{Completion of excavations in Navajo.}
{221}{}{The Navajo military camp turned out to be almost useless. Almost all local resources were destroyed by explosions in warehouses. Only the burnt pillars of the old buildings remained. It is unprofitable to extract the remaining resources due to labor losses. The camp will have to be closed. But such a jackpot was planned...}
{222}{}{Personal note.}
{223}{}{When I created this colony, I counted on understanding the idea of a New World. But visitors are only interested in bottlecaps. Dirty little bastards, I will force them to adopt new laws and change!}