{101}{}{The stiffened corpse of a prisoner. Cause of death unknown.}
{102}{}{The stiffened corpse of a prisoner. He died while trying to get rid of the collar.}
{103}{}{You buried the corpse of a prisoner. Someone had to do it.}
{104}{}{Digging during a fight is not your best idea.}
{105}{}{The prisoner died from a strong electric discharge while trying to get rid of the collar.}
{106}{}{His fate is not to be envied.}
{107}{}{Ha! Pathetic loser.}