{110}{}{The inscription on the glass reads: "The slot machine temporarily does not work."}
{111}{}{" Hey, starfighter! Throw a coin into that slot and find yourself in the incredible world of Space!"}
{112}{}{You managed to repair the burnt-out parts of the slot machine. We need to tell the bartender about this.}

{120}{}{For some reason, you no longer enjoy this game.}
{121}{}{I'm sick of just the sight of this machine.}
{122}{}{To play, use special tokens on this slot machine.}
{123}{}{M-m-m! It looks fantastic.}
{124}{}{"Hey, starship! Give up the helm to a more experienced pilot."}
{125}{}{I have *no* chance against this machine.}
{126}{}{"Hey, starship! The onboard medic cannot allow you to take the helm in this condition!"}
{127}{}{I'm not able to play right now.}

#Phrases when playing
{130}{}{Well done, pilot! You earned it }
{131}{}{ points!}
{132}{}{Total account: }
{133}{}{.}
{134}{}{}
{135}{}{From the screw!}
{136}{}{Show aerobatics!}
{137}{}{Fly, ball!}
{138}{}{I want to win!}
{139}{}{Come on! Come on!}
{140}{}{It was a bad flight! Lost }
{141}{}{ points!}
{142}{}{.}
{145}{}{Yes, not there!}
{146}{}{Damn the gamer!}
{147}{}{You disappoint me, piece of iron!}
{148}{}{I'll conquer you anyway!}
{149}{}{No!}
{150}{}{"It was aerobatics, Captain! You've conquered Space and you can be proud of yourself!"}
{151}{}{Phew, it's finally over... It's strange, I feel something... emptiness after victory.}
{152}{}{During the game you had a seizure!}