{110}{}{The equipment fails.}
{111}{}{You managed to disable the radio transmitter. The whole colony was left without radio communication.}
{112}{}{You have no idea how it works.}
{113}{}{Not subject to repair.}

#Dialog
{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{The radio transmitter is not responding.}

{210}{}{Disable collar control.}
{211}{}{Attention! Disabling collars reduces control over prisoners. Are you sure you want to use this option?}
{212}{}{Yes, disable collars.}
{213}{}{The control of collars is disabled.}

{214}{}{Copy the frequencies of the mercenaries. So I can eavesdrop on their radio conversations.}
{215}{}{Radio frequencies are copied.}

{216}{}{Debugger's comment.}
{217}{}{This sacred equipment was brought from the Navajo camp, 11 miles from Flagstaff, and installed in the colony for the glory of the Sacred Fire in 2*** year by His humble servant *** on the orders of Aaron, the Lord of the Phoenix. May heaven fall upon the one who defiles this gift.}