{200}{}{"Welcome to Flagstaff -the best city north of Phoenix! The year of the colony 's foundation - 2163."}
{201}{}{ I've had enough of this information.}
{202}{}{The best city, right? Perhaps it's worth looking around here.}

{210}{}{What does it say about the special regime?}
{211}{}{"Curfew from 00:00 to 06:00. The open carrying of weapons is prohibited in the city."}

{220}{}{I am interested in the colony map.}
{221}{}{4 districts are signed on the crookedly drawn diagram: Block A (this residential area), Block B (garrison and prison) in the east, Block C (uranium mine) in the north, as well as the uninhabited ruins of the old city in the east.}
{222}{}{Something about the old town.}
{223}{}{"Attention! A group of robbers allegedly operates in abandoned neighborhoods. Be careful!"}
{224}{}{The text is filled in. Apparently, this ad has lost its relevance.}

{230}{}{Checking the text.}
{231}{}{(You find a lot of grammatical errors in the declarations.)}
{232}{}{God, there are so many mistakes here! This misunderstanding needs to be corrected...}
{233}{}{(The text is fine now.)}
{234}{}{Yes. That's better.}
{235}{}{(You don't find any errors.)}
{236}{}{The text is fine. Well, it seems so to me...}