{110}{}{It looks like this product of ancient technology could fly high in the sky. Very high.}
{111}{}{Another pile of scrap metal in another old building.}
{112}{}{You have dismantled all the useful parts from this relic.}

{113}{}{It won't help here.}
{114}{}{Although it didn't make sense, you still put the details back in their places.}
{115}{}{Uh, stranger things I've never had to do.}
{116}{}{Wow, our ancestors were smart.}