{101}{}{Here is an old table equipped for the repair of collars.}
{110}{}{Prisoners' collars are being repaired on this table.}
{111}{}{All components are used up. There's nothing else to do here.}
{112}{}{Having disassembled the details, you received a micro-core battery for 8 charges.}
{113}{}{Having disassembled the details, you received a micro-core battery for 16 charges.}
{114}{}{Having disassembled the details, you received a 20-charge micro-core battery.}