{100}{}{Here is the bartender.}
{101}{}{You see a strong man in an apron. Apparently, he owns this place.}
{102}{}{So, I won't serve you while this armor is in the bar. Is that clear?}
{103}{}{Sorry, but no guns in the bar.}

#The first dialog
{200}{}{(Approaching the bar, you notice the wariness in the eyes of the bartender and the surrounding visitors). What do you want?}
{201}{}{Please, empty coffee and a bun with sweet syrup for me.}
{202}{}{(the alertness of others is replaced by bewilderment and laughter) I don't have anything like that. Do you really not understand where you are?}
{203}{}{Well then I want to know more about this place.}
{204}{}{I just wanted to take a look. Interesting place you have.}
{205}{}{ (raises one eyebrow, then returns to his daily business, cleaning the bar from some stains) It's a bar. I hope you know what "drinking establishment" means.}
{206}{}{Then I would like to rest here.}
{207}{}{I'm chasing a slave convoy.}
{208}{}{(visitors fall silent and turn tensely in your direction) A slave convoy? No. There were no such people here.}
{209}{}{Hmm. I think I'm going to stay here a little longer.}

#Repeat dialog
{210}{}{Yes?}
{211}{}{Be there.}

#Pocket trash
{220}{}{There is nothing easier. But do you have something to pay with?}
{221}{}{Listen, I've got a lot of trash in my pockets here. Take a look, which of these can be useful?}
{222}{}{Wait a minute, I'm rummaging in my pockets...}
{223}{}{(you dump pocket garbage on the counter, the bartender is perplexed sorting through this stuff) If I had such pockets, I would have become rich a long time ago. Look, there's a pre-war bill here, a couple of caps and a cartridge. With all this you can buy... a whole tail from a fried iguana, ha ha!}
{224}{}{Ugh, finally, at least some benefit from this garbage.}

# Chris from the Villa
{230}{}{Did a guy from my area pass by here? His name is Chris.}
{231}{}{By the way. There was a guy who passed by, wasn't he from your area? His name was Chris.}
{232}{}{Yes, he was. Where did he go?}
{233}{}{He left with a caravan, but he doesn't know where he's going.}
{234}{}{Great. Looks like I won't hear from him again.}
{235}{}{Chris? I don't know that.}
{236}{}{Ah, well, then I'm sorry.}

{240}{}{Hmm. You look like an inveterate brawler.}
{1240}{}{Hmm. You look like an inveterate rebel.}
{241}{}{Are you sure?}
{242}{}{I am sure. I hope you're not going to make trouble for me?}
{243}{}{No, no problem, sir. I'm a regular visitor.}
{1243}{}{No, no problem, sir. I'm an ordinary visitor.}
{244}{}{And it seems to me that bars were invented just for fights.}
{245}{}{Then remember a simple rule. If someone decides to make a scandal here, he will immediately be on the street and will not come back.}
{246}{}{I understand. No problem, sir.}
{247}{}{Don't tell me. Otherwise I'll get angry.}

#About the bar
{250}{}{What drinks do you sell?}
{251}{}{Watch and choose. This is the best alcohol you can find in our area.}
{252}{}{Let me think.}

{253}{}{So all this is firewater? I should have warned you right away!}
{254}{}{It looks like you're from a place where no one has ever heard of bars. It's hard to imagine what will happen to you after a couple of sips. Still want to try it?}
{255}{}{Wow, I've never seen so many hot drinks before!}
{1255}{}{Wow, I've never met so many hot drinks before!}
{256}{}{Then congratulations on joining civilization. So what will you order?}
{257}{}{Where did you get this alcohol from?}
{258}{}{Some are brought by caravans, and some are brought by scavengers. All this is missing. I was thinking of starting my own production, but the business stopped giving the necessary income to recoup the raw materials.}
{259}{}{I see.}

{260}{}{Any hot drinks that you can get in these parts.}
{261}{}{Why are you paying with caps here? We usually sell something *useful*.}
{262}{}{Ah, you're from the wasteland. I don't know the whole story myself, but in big cities they came up with the idea of using caps as currency. It's like money before the Great War... You don't know anything about money either? Well... In general, this is all for exchange.}
{263}{}{[Next]}
{264}{}{However, the bottlecaps have taken root only in large cities, and in the wastelands they are rarely used.}
{265}{}{A curious idea.}
{266}{}{And what kind of assholes thought of that?}

{270}{}{Hey, where did you get this flour?}
{271}{}{A couple of strangers sold it on the cheap. Do you want to buy?}
{272}{}{This flour was stolen from the Villa by looters. You're selling stolen goods!}
{273}{}{Maybe so, but I honestly purchased this product.}
{274}{}{[Next]}
{275}{}{Now listen to me. You're a new person here and you don't deserve respect yet. If you dig around, you'll find yourself outside the door. This is at best. So, will you calm down? That's the same.}
{276}{}{Not angry. I'm not to blame for your tragedy.}
{277}{}{Now you're on my blacklist, huckster.}
{278}{}{Okay. I forgive you this time.}

{280}{}{Get a drink for everyone here. I }
{281}{}{ from the Villa. And I'm buying.}
{282}{}{Do you want to earn a good reputation among scavengers? It would be like that right away. But it will cost you 50 caps.}
{283}{}{No problem, here are the bottlecaps.}
{284}{}{So many caps for all these beggars? So, I'm leaving here.}
{285}{}{I can't afford it right now. Another time.}
{286}{}{And you're having trouble counting cash, right?}
{287}{}{...}
{288}{}{Hey, guys! A newcomer from the wasteland wishes to introduce himself. It's at his expense.}
{1288}{}{Hey, guys! A stranger from the wasteland wants to introduce herself. It's at her expense.}
{289}{}{Stretch out the fun, guys!}

{290}{}{Hi. We're celebrating the extermination of Jackals here. These savages caused problems for scavengers and travelers, now it will be easier without them.}
{291}{}{Yes, they fought like wild dogs.}
{292}{}{Are you trying to tell me that you're involved in this?}
{1292}{}{Do you really want to say that you are involved in this?}
{293}{}{We went camping with your people. The gatekeeper knows about it.}
{294}{}{Damn it, is it true? For the sake of such a case, I'll buy you a drink on the house. Thanks, buddy.}
{295}{}{Please.}
{296}{}{I told the rangers, and they exterminated the tribe.}
{1296}{}{I told the rangers, and they exterminated the tribe.}
{297}{}{Well, well. In general, whoever did this did us a great favor.}
{298}{}{Uh, so celebrate, guys. And my exploits are waiting in other places.}
{299}{}{Yes, just rumors.}

{300}{}{Can you tell me about this city?}
{301}{}{What do you want to know?}
{302}{}{Nothing else.}
{303}{}{You either order something, or get others.}
{304}{}{Why is everyone squinting at me?}
{305}{}{Uh, okay. The hint is understood.}
{306}{}{Don't be rude to me, bartender.}
{307}{}{Why don't you ask them about it?}
{308}{}{What's going on here anyway?}
{309}{}{Nothing special. The city is impoverished, and no one knows what to do about it.}
{310}{}{The good news is that the cartel has finally launched one of the factories. It will breathe life into a dying city.}
{311}{}{Why do you live in such terrible huts?}
{312}{}{And you find better houses among the local ruins.}
{313}{}{I have no more questions about the city.}

{320}{}{If you're going to get rowdy, then go outside. I don't need drunken brawls here.}
{321}{}{He was looking for it himself.}
{322}{}{I don't care which one of you started the fight. Just watch yourself and don't let go of your hands while you're here.}
{323}{}{Don't worry, it won't happen again.}
{324}{}{Yes, in this hole, only drunken fights can entertain.}

#Slave convoy
{330}{}{I'm chasing a slave convoy. What do you know about it?}
{331}{}{I don't know anything. How about a glass of something hot?}
{332}{}{Okay, forget it, I'll ask someone else.}
{333}{}{You should know.}
{334}{}{Look, I don't want any trouble with Mr. Kogan. He did business with these slaveholders. So talk to him.}
{335}{}{Maybe later. I want to sit here a little longer.}
{336}{}{Okay, I'll go to him.}
{337}{}{Don't worry, Kogan and I don't have any friction.}
{338}{}{Tell it to someone else. But don't involve me.}
{339}{}{Looks like you're all tied up here.}
{340}{}{Really? You know, there are rumors about you... not particularly flattering.}
{341}{}{Seriously? I didn't notice something.}
{1341}{}{Seriously? I didn't notice something.}
{342}{}{If you don't tell me, I'll blow up this bar like the mug of that harasser.}
{343}{}{Okay, okay. No need to deliver anything. Agreed?}
{344}{}{Then be a good girl and tell me everything you know.}

{350}{}{Yes, they stopped by on their way back to the city. It's been a long time since I've had such an influx of customers.}
{351}{}{It's good that your business has developed. But I need to know where the convoy went.}
{352}{}{I don't care about your bar. Tell me where they went.}
{353}{}{Wait a minute, do you mean to say that the city has only benefited from this story with slaves?}
{354}{}{The motel guy and I made good money, and Mr. Kogan signed a couple of new contracts. Even ordinary scavengers found a use. These slavers seemed to breathe life into our dump. At least for a little while.}
{355}{}{The convoy went east to the city of Flagstaff. By the way, Mr. Kogan did business with the slave owners. Now that he's dead, you can study his records in the garage, if that's so important to you.}
{356}{}{The convoy went east to the city of Flagstaff. Go along the 40th federal highway, you won't miss. The way there should take about a week.}
{357}{}{Thanks for the information. I have to go.}
{358}{}{Now I know that you are also to blame for the raid. And I'll remember that.}

{360}{}{What's the problem with getting alcohol?}
{361}{}{Previously, tequila and beer were brought from the south. And now this route is closed. I don't mind buying booze from Flagstaff at an increased price, but we don't have a permanent caravan even with this neighboring town. I need at least a courier for negotiations.}
{362}{}{I'm just going there. I can talk to someone about the supply of alcohol.}
{363}{}{Things are really bad for you. I hope you'll figure it out somehow.}
{364}{}{Try. Otherwise I can't even send a letter there. Find a local bartender and convince him to send drinks here.}
{365}{}{Agreed. I'll find him and come back with an answer.}
{366}{}{Bye.}
{367}{}{The bartender from Flagstaff agrees to supply drinks.}
{368}{}{Great job! Let alcohol go up in price, but my shelves will stop being so empty.}
{369}{}{Ahem. You're not thinking of leaving my job unpaid, are you?}
{370}{}{I'm happy for you, my friend. Now the whole city will cheer up.}
{371}{}{Here are 100 caps for the courier service and my old gun. I know it's not much, but I'm expecting big expenses!}
{372}{}{I've never had to endure such a scam before. Goodbye, miser.}
{373}{}{Thank you, that's enough. And I'll sell the gun in the next town. Happily.}
{374}{}{Agreed. But for now, I'll stay here a little longer.}

#Trade Route Quest
{400}{}{Do you have anything edible?}
{401}{}{Something like meat? There are problems with this.}
{402}{}{Why?}
{403}{}{Trade turnover has fallen recently. Fewer and fewer caravans with provisions come into the city, because we have nothing to trade with. We have to survive on our own. Someone hunts coyotes, someone catches lizards, and someone unsuccessfully tries to grow crops.}
{404}{}{Hunting? I would have participated.}
{1404}{}{Hunting? I would have participated.}
{405}{}{Is there really nothing you can do?}
{406}{}{And that's all you can do?}
{407}{}{Well, the gatekeeper said that wild Brahmins were spotted in the desert. Some scavengers are going to find them. You can join the hunt too.}
{408}{}{Interesting. I'll talk to this gatekeeper first. See you again.}
{409}{}{It's not in my line. Be there.}

{410}{}{The gatekeeper says, did you also participate in the search for a brahmin?}
{1410}{}{The gatekeeper says, did you also participate in the search for a Brahmin?}
{411}{}{Yes, there was a case.}
{412}{}{Maybe so. Do you have something against it?}
{413}{}{Then explain what the hell happened there and where are our people?!}
{414}{}{Your people, uh, fell to a wild brahmin. He was stronger than anyone could have imagined.}
{415}{}{Damn it. No meat, no people. Eh, it looks like the hungry season is waiting for us again...}
{416}{}{Is it really that bad?}
{417}{}{So you know what really happened there. You're not going to talk about it, are you?}
{418}{}{I? Nope. I won't.}
{419}{}{Cut off my tongue if I tell you that you stole a tame brahmin.}
{420}{}{OK. Here's your share of the total carcass. Thank you, you are saving us from hunger.}
{421}{}{So are you having a hungry season?}
{422}{}{It turns out that you just ran away, leaving the others alone with the problem. Do you even know how much our guys had to endure there?}
{1422}{}{So you just ran away. I left the others alone with the problem. Do you even know how much our guys had to endure there?}
{423}{}{Don't even ask.}
{424}{}{I guessed it. Don't think that such a thing is quickly forgotten in these parts. Especially in conditions of hungry time.}
{425}{}{So you have a hungry season?}
{426}{}{Because of you, we lost a whole carcass of pure meat! She could feed one person for a whole year!}
{427}{}{I have some ideas in stock.}
{428}{}{Really? Very good. Because otherwise we'll have to roast you instead of a brahmin. We have a hungry season here, there is not enough food for everyone.}
{429}{}{Is it that bad?}

{430}{}{Exactly. We used to trade with southern cities, exchanging parts for products. But not only do we now have almost nothing to trade with, they have also announced a boycott in San Brahmin. They don't sell their meat to anyone anymore.}
{431}{}{And nothing can be done?}
{432}{}{I don't know. We don't have any more caravans. I can't even contact the merchants.}
{433}{}{Looks like you have a problem here.}
{434}{}{And another one. Listen, you're going to those parts, aren't you? If you find yourself nearby, let the merchant in the square know, maybe he will open our trade route.}
{435}{}{I doubt I'll ever be in those places.}
{436}{}{Okay, I'll talk to him if I'm around.}
{437}{}{I can do it.}
{438}{}{You'll be doing this a great favor. Find a merchant in the square in San Brahmin and persuade him to reopen the trade route.}

{440}{}{So, have the caravans from the south returned?}
{441}{}{Business is coming to life. Thanks to you, we are getting meat from the San Brahmin again. So hunger does not threaten the city. And the turnover of caps in the bar has also increased. Thanks! Here, take a hundred as a share of the deal.}
{442}{}{You're welcome.}
{443}{}{The resumption of trade will increase the turnover of dried meat and caps in the bar.}
{444}{}{There will be no caravans. San Brahmin made an alliance with the Rangers.}
{445}{}{It's bad... The city will not last long on the meat of coyotes and iguanas.}
{446}{}{And what should we do now?}
{447}{}{So now buy meat from the rangers.}
{448}{}{I can buy meat from the rangers. But it will be much more expensive. And I'm not at all happy about the prospect of walking under the heel of these guys. We have a pretty strained relationship with them in the Garage, you know. But it seems that there is no choice anymore.}
{449}{}{It's better than nothing. I'll talk to someone on their territory.}
{450}{}{It's better than nothing. Good luck.}
{451}{}{Unfortunately, none of the locals will listen to me. This is already a passed stage.}
{452}{}{I have some bad news. No one from Ranger territory wants to trade food with you.}
{453}{}{I understand. Thanks for trying.}
{454}{}{Good luck. You're holding on here.}
{455}{}{Someone in Ranger territory has agreed to trade food with you.}
{456}{}{Business is coming to life. Thanks to you, we are getting food again. So hunger does not threaten the city. But the boots of the rangers have already trampled the entrance to my establishment. Or maybe it's for the best? I don't know. In any case, thank you. Take a hundred as a share of the deal.}
{457}{}{You're welcome.}
{458}{}{There will be no caravans. The tribe became angry at the outsiders after a series of murders.}