{100}{}{This is Larry.}
{101}{}{You see a bar patron with a shabby look and bad manners.}
{102}{}{Another thing. Now dance. Although no, go to hell.}
{103}{}{Hey, you! Get us a drink.}

{200}{}{Hey! Battered asses don't usually stop in Garage City.}
{201}{}{[Ignore]}
{202}{}{Life here seems too fast for them. You probably thought you could keep up with her, huh?}
{1202}{}{Life here seems too fast for them. You probably thought you could keep up with her, huh?}
{203}{}{I'm faster than you think.}
{204}{}{ (the molester changes her face and returns to the table after a short pause) Okay, if you say so. But usually those who are in a hurry forget a lot. For example, about giving the good guys a drink.}
{205}{}{I'm not going to give someone a drink for free.}
{206}{}{I'll remember that.}
{207}{}{Listen, leave me alone. I'm just trying to find my family.}
{208}{}{I see you don't like my company? And if so, then you won't like the rest of the city either. If I were you, I'd pour everyone a drink to leave a good impression.}
{209}{}{Fuck off, I don't have time for this nonsense.}
{210}{}{ (purses his lip with contempt and hatred) For such rudeness in this city, you can get a pipe on the head. I'll forget about what I heard if you buy me a drink.}
{211}{}{Who are you calling an ass, stupid?}
{212}{}{What is it, you can't keep up with my speech? Life here is too fast for people from the desert. You probably think you can keep up with her, huh?}
{213}{}{Okay, let me just leave. Right now, without further ado.}
{214}{}{So you're breaking into our sweet town, disturbing the tranquility of this bar, and you think you can just leave?}
{215}{}{Uh, yeah.}
{216}{}{Get us a drink. And go to hell.}

{220}{}{What do I need?}
{221}{}{Nothing.}
{222}{}{Nothing? Then why the hell are you pulling me?}
{223}{}{Just forget it.}

{230}{}{Who are you?}
{231}{}{Who am I? I'm the one who knows this whole damn city like the back of my hand. I am the one with whom it is customary to share and talk, choosing my words carefully.}
{232}{}{Do you even have a name?}
{233}{}{My name is Larry. Repeat? Or will you remember it the first time?}
{234}{}{Whatever you say, Larry.}
{235}{}{I'm tired of your mockery. It's time to stuff your face!}
{236}{}{My name is Larry. I'm here... I do various things. For example, I guard the city when necessary. Not for free, of course.}
{237}{}{So you're not one of the scavengers?}
{238}{}{No, stupid. I'm from an elite squad of fighters who don't like it when questionable types appear in their city.}
{239}{}{And it looks like I'm on their list.}
{240}{}{So what are you going to do? Come on, show me what you're capable of, sucker!}
{241}{}{No, I'm not collecting anymore. As long as Mr. Kogan pays the caps, I don't need it.}
{242}{}{No, I'm not collecting anymore. It's a dirty business.}
{243}{}{I see.}

{250}{}{It looks like you're not getting out of this bar?}
{251}{}{I have a lot to do. I'm just here to get my throat wet. Any more questions?}
{252}{}{No, perhaps not.}
{253}{}{The bartender serves a crappy drink. But it warms at night. All year I've been waiting for something invigorating. And he only has bad beer. We are a year old.}
{254}{}{Sorry to hear that.}
{255}{}{Someday your ass will have to go outside.}
{256}{}{Have you seen a slave convoy here?}
{257}{}{Saw. But I won't tell you anything about it. Get lost.}
{258}{}{Okay. If not you, then someone else will tell.}
{259}{}{You're going to regret this.}

{300}{}{What's wrong with you? Don't like our company?}
{301}{}{Fuck off, asshole.}
{302}{}{Are you looking for something? I'll have to teach you some manners!}
{303}{}{[Defend]}
{304}{}{Listen, I really have to get going. This is very important.}
{305}{}{Important? Hey, did you hear someone has important business here!}
{306}{}{I'm going to save my people...}
{307}{}{Ooh! A noble peasant is coming to save people! Everyone make way!}
{1307}{}{Wow! A noble peasant woman is coming to save people! Everyone make way!}
{308}{}{Okay, that's enough! I'll rip out your fucking tongue, you bastard!}
{309}{}{I really have to go.}
{310}{}{Let me just give you 10 caps. And we'll forget about everything.}
{311}{}{The right decision, amigo. Now get out of the bar.}
{312}{}{I've changed my mind. Give me my bottlecaps, bitch!}
{313}{}{Ah, yeah...}