{100}{}{Here is a bar visitor.}
{101}{}{You see the customer. He has already gone over his daily allowance and is actively telling others something.}

{110}{}{I don't know you.}
{111}{}{Sorry, this table is occupied.}
{112}{}{*Ic*}
{113}{}{I don't have a drink for you. Got it?}
{114}{}{Come on, get out of here.}
{115}{}{If you want to introduce yourself, order everyone a drink.}
{116}{}{Yes, you won't even give a couple of caps to a friend.}
{117}{}{Nah, don't touch it.}
{118}{}{You weren't invited here, find another table.}
{119}{}{I don't drink with strangers.}

{120}{}{Hey, thanks for the drink.}
{121}{}{I like you.}
{122}{}{And you're nothing... for hillbillies.}
{123}{}{What's your name there? Well, glad to meet you.}
{124}{}{The best way to get acquainted is drinking. And you do.}

{130}{}{You'd better leave this town. I'm serious.}
{131}{}{Move out of town.}
{132}{}{Looking for trouble?}
{133}{}{You're not welcome here anymore.}
{134}{}{A thousand nuts, don't come near me!}
{135}{}{Can't you get out of here? I can help with a kick in the ass.}

{140}{}{Have a seat, you're always welcome here.}
{141}{}{How are you, buddy?}
{142}{}{Everything is the same with us. And you?}
{143}{}{Oh, don't even ask. How are you doing?}
{144}{}{Yes, life is as empty as a tin can.}