{100}{}{You see a bar visitor.}
{101}{}{You see a relaxed hard worker.}
{102}{}{Hey, amigo, do you want to put on a drink as a sign of our friendship?}
{103}{}{Thanks for the drink, amigo.}
{104}{}{I have nothing else to put on the line. Another time.}

{200}{}{Hey, look what I've got. It's a stimpack. A real cure for all problems - once I was injected, and there seemed to be no wounds. Do you want to?}
{201}{}{What is it?}
{202}{}{I'm telling you, this is pre-war medicine. I don't know what it was made of, but it still works.}
{203}{}{Perhaps this may come in handy. What will you take in return?}
{204}{}{Yeah. What will you take in return?}
{205}{}{I don't know. It has become difficult to get something worthwhile in the city, even if you have caps. How about a card game? You put 10 caps, and I'm a stimpack. So at least I will spend time with excitement.}
{206}{}{I don't gamble, sorry.}
{207}{}{Not interested. Be.}
{208}{}{Great, I accept the terms. Who distributes?}
{209}{}{First the caps on the table.}
{210}{}{As soon as I earn them, we will continue. Bye.}
{211}{}{Oh, yeah, baby. It's not as easy as it seems. You think that everything depends on luck, but it is equally important to know the rules and be able to count... So, let's see what happened there...}
{212}{}{Putting the cards on the table.}
{213}{}{You talk too much.}
{214}{}{So, you see, I have an ace. Did I say that not everything depends on luck? Haha, these bottlecaps are mine now.}
{215}{}{Damn, I won't forget this defeat. Don't even hope.}
{216}{}{Well, you won. At least it was a fair game.}
{217}{}{So, you see, I have a king... Oh, where did you get the ace? Damn it, you're cheating!}
{218}{}{Well, well. It was a fair game. All the witnesses are here.}
{219}{}{Yeah, okay. Yours took it. But don't think that after that I'll be glad to see your face in this bar.}
{220}{}{Haha, now give me the stimpack and the caps. Good luck, amigo.}
{221}{}{Watch your tongue. And I'll take this.}