{100}{}{This is Mr. Kogan.}
{101}{}{You see a sloppy fat man in a dirty business suit. Looks like he's in charge here.}
{102}{}{Choke on lead, you fat pig-rat!}
{103}{}{What does a scavenger feel when his fate depends on garbage?}
{104}{}{Hey! I had nothing to do with it. He's having a heart attack!}
{105}{}{I'm not against peace talks, but first get out of this tin can.}
{106}{}{Get out of my city.}
{107}{}{Get out of my garage.}

#Floating replicas (do not delete empty lines!)
{110}{}{*Cough-cough*}
{111}{}{*Uv-f*}
{112}{}{*Urp*}
{113}{}{*Burp*}
{114}{}{Damn heartburn...}
{115}{}{ }
{116}{}{ }
{117}{}{ }
{118}{}{ }
{119}{}{ }

#Cut scene
{120}{}{   }
{121}{}{Mr. Kogan! Mr. Kogan!}
{122}{}{Larry, for fuck's sake! Why the hell are you breaking into my office?}
{123}{}{What's the matter? No one dares to break into my office...}
{124}{}{Mr. Kogan! There, in the dormitory, a serious mess began!}
{125}{}{Well, what else can happen in this hole? Probably another drunken brawl.}
{126}{}{No, it doesn't look like it. I didn't understand the reason for the fight, I immediately ran here...}
{127}{}{So go figure it out, idiot!}

#Dialog
{170}{}{I've seen such a garment before. What do you have to do with the Followers of Fire?}
{171}{}{The most direct. I'm part of this church.}
{172}{}{Hmm... What a curious coincidence. I usually try to bypass any religion. But Followers contribute to progress in Arizona and, as a result, the development of my cartel. You can feel protected here.}
{173}{}{Well, that's great news.}
{174}{}{Can I expect full service in the garage?}
{175}{}{Sure. I'll give instructions to Pete.}
{176}{}{Thank you.}
{177}{}{This is the first time I hear about these "pursuers". And he took off his mantle from a corpse in the desert.}
{1177}{}{This is the first time I hear about these "pursuers". And she took the mantle off a corpse in the desert.}
{178}{}{It's true? Then forget about our conversation.}
{179}{}{I'll do that.}

{180}{}{They say you had some kind of grater with Larry?}
{181}{}{Nothing special. He was just looking for trouble at the bar.}
{182}{}{You must have nerves of steel if you think you can kill my people. But on the other hand, I've been wanting to get rid of this devil for a long time. He makes too much noise.}
{183}{}{So you're not going to chase me?}
{184}{}{You'll have to work hard to earn my respect. It all depends on you.}
{185}{}{That's how...}
{186}{}{He started it first! I was just defending myself.}
{1186}{}{He started it first! I was just defending myself.}
{187}{}{This is our grater with him. They don't concern you.}

{190}{}{You again... (sigh) Do you know about the Rangers? I hate these guys. They're always poking their noses into other people's business, as if the whole wasteland belongs to them. You're not going to do the same in *my* city, are you?}
{191}{}{No, Mr. Kogan. I'm here solely on business.}
{192}{}{OK. I think we understand each other. Don't forget who this place belongs to.}
{193}{}{No problems.}
{194}{}{You'd better talk about the Rangers in a respectful tone. Someday we will control the whole of Arizona.}
{195}{}{I doubt it very much. The rangers have a lot of enemies, and their numbers are too small to independently manage the population. And they'll certainly never get control of this city while I'm alive.}
{196}{}{What's your problem with the Rangers?}
{197}{}{I have *no* problems with them. But I'm not going to share power with anyone. I put too much work into this mine and created this whole city practically from scratch.}
{198}{}{Yes, you can think about it.}
{199}{}{Rangers are busy with narrow interests. They are not able to create a new production. And this is exactly what people need right now.}

{200}{}{(In front of you is a very well-fed man in a worn business suit, looking out of place against the background of the surrounding landfill. When he sees you, he gets distracted from some device and removes the headphones connected to it.)}
{201}{}{Ahem. Are you in charge here?}
{202}{}{(puts down the headphones and presses some buttons on the device, then points to the device) It's an old record player. These were produced by the famous Watts Electronics company before the Great War. The model is not the most expensive, but very reliable, since it has survived to this day.}
{203}{}{[Listen]}
{204}{}{That's why I love old things. Our ancestors made a lot of mistakes, but they knew how to make players. At that time, many factories of various specializations were operating throughout Arizona. Now none of them work.}
{205}{}{Who needs all this junk?}
{206}{}{I knew you wouldn't appreciate it. So what's on your mind, man?}
{1206}{}{I knew you wouldn't appreciate it. So what's on your mind, lady?}
{207}{}{Yeah... The world has definitely lost a lot.}
{208}{}{M? I thought you'd have a different opinion. In any case, we have very few opportunities to fix it. So what's on your mind, man?}
{1208}{}{M? I thought you'd have a different opinion. In any case, we have very few opportunities to fix it. So what's on your mind, lady?}
{209}{}{End this nonsense. I didn't come here to cross the desert.}
{1209}{}{Finish this nonsense. I didn't come here to cross the desert.}
{210}{}{You're not the talkative type, are you? So what's on your mind, man?}
{1210}{}{You're not the talkative type, are you? So what's on your mind, lady?}

{211}{}{I am here because someone enslaved the peasants of the Villa and took them in this direction.}
{212}{}{No one likes it when their usual way of life is violated. I don't like it when the ruins run out of minerals, as a result of which you need to look for new places to mine. But I have dozens of scavengers and several contracts under my command.}
{213}{}{[Next]}
{214}{}{Villa was lucky. But it's hard for people of your type to understand. While you are busy with your internal worries, we, the scavengers, provide equipment for the whole of Southern Arizona. I don't think anyone else cares about the fate of the Villa, except the local peasants.}
{215}{}{Bastard, so it was you who ordered the peasants to be captured?}
{216}{}{So you don't deny your involvement?}
{217}{}{Me? Of course not. It was a project of another, more influential organization. We just happened to be on the way. And if I were you, I would forget this story and go back to my empty house to start all over again.}
{218}{}{Do you think it's that simple?}
{219}{}{There are no other ways for you. However, you can stay here and work as a garbage collector if you like it. What do you say?}
{220}{}{I...}
{221}{}{It's like you're rejoicing at our tragedy.}
{222}{}{Am I happy? No. But when WE needed help in times of famine, YOU meanwhile profited from it and demanded double rates from us. Well, is it nice to feel like a litter this time?}
{223}{}{That's not what I'm asking.}

{230}{}{These scavengers can be unbearable when they get drunk... Listen, if you're going to stay in town, you're going to need my protection. And now a great opportunity has turned up to show itself.}
{231}{}{Are you suggesting I calm down the workers?}
{232}{}{Go to the dorm and find out what happened there. I don't need any extra problems in the city.}
{233}{}{I'll see what I can do.}
{234}{}{I don't think I want to work for you.}
{235}{}{Great. Oh, yes, I didn't introduce myself. Karl Kogan. Now get busy.}
{236}{}{. . .}
{237}{}{Then you don't belong in Garage City. Get out of my garage.}
{238}{}{. . .}
{239}{}{Why would I get involved in a local showdown?}
{240}{}{Is my loyalty not enough? Don't forget that I know everything about your enemies - more than anyone in Garage City.}
{241}{}{What did you find out about the fight in the dorm?}
{1241}{}{What did you find out about the fight in the dorm?}
{242}{}{Nothing. I'll do it right now.}
{243}{}{Can I ask a couple of questions?}
{244}{}{First prove that you are worthy of my attention. Or do you already want to get out of town?}
{1244}{}{First prove that you are worthy of my attention. Or do you already want to get out of town?}
{245}{}{Okay, I'll do your errand.}
{246}{}{That's exactly what I'm going to do.}
{247}{}{Lucas's men robbed Trayvon's men and left town. They were talking about some kind of decoder.}
{248}{}{I know, you idiot! How long has it been since I gave you this assignment? Your chances of proving your usefulness are rapidly disappearing.}
{1248}{}{I know, damn it! How long has it been since I gave you the assignment? Your chances of proving your usefulness are rapidly disappearing.}
{249}{}{What's going on anyway?}
{250}{}{I didn't expect this from Lucas. His clan had a reputation for being a small but punchy team. If he decides to go against me, he will have to pay dearly for it.}
{251}{}{I have questions about this story with Lucas.}
{252}{}{Is there anything else I can do for you, Mr. Kogan?}
{1252}{}{Is there anything else I can do for you, Mr. Kogan?}

{253}{}{I have the answers.}
{254}{}{Why are the clans so bitter against each other?}
{255}{}{Recently, mine revenues have been falling, so it has become difficult for scavengers to survive. Previously, the clans got along well - there was enough work for everyone. Now they have become fierce competitors.}
{256}{}{What's the story with the decoder?}
{257}{}{A rare device for hacking electronic systems. I ordered a decoder for a large amount of caps through the southern caravans and gave it to the Trayvon clan to open the old factory. It's the only place we couldn't get to because of the damn security system. It looks like Lucas decided to bypass all of us in this operation.}
{258}{}{Why was it necessary to divide the scavengers into clans?}
{259}{}{They wanted it themselves. People need authorities, that's how their thinking works. I don't care who I give instructions to. The main thing is that they obey and do not create problems.}
{260}{}{Enough about the scavengers.}
{261}{}{Enough talk about the cartel.}
{262}{}{I've had enough of these muddy stories. Goodbye.}

{270}{}{Are you the local headman?}
{271}{}{Elder... Is that what the peasants call the mayor? No, the city doesn't need a mayor. At least for now. I'm the head of a cartel of scavengers. But since the whole city is tied up in this business, no important decision can do without me. In this sense, you can consider me a "prefect".}
{272}{}{So you're the mayor of this town?}
{273}{}{I'm telling you, the city doesn't need a mayor. At least for now. I'm the head of a cartel of scavengers. But since the whole city is tied up in this business, no important decision can do without me. In this sense, you can consider me the mayor.}
{274}{}{How did you become the head of the company? Surely went over the heads of competitors?}
{275}{}{Stupid stereotypes. I started out as an ordinary garbage man in a Big City. The cartel already existed, I just took a vacant place in the administration. And then we opened a branch on these ruins, and I decided to move here to control the work.}
{276}{}{It's not like you want to come back.}
{277}{}{I'm afraid we have some with the main office... disagreements.}
{278}{}{What is your cartel doing?}
{279}{}{Mainly extracts minerals from old ruins. For a hundred years after the Great War, many things have deteriorated, but some have survived and can be useful to society. We also try to fix some things, but things are much more complicated with this.}

{280}{}{My village does not like that you are restoring an old factory.}
{281}{}{Why is that? Oh, yes, I've heard a lot about your superstitions and fear of old technology. Well, you have no choice. Accept it.}
{282}{}{Really?}
{283}{}{From now on, no one will let your peaceful village prosper by manual labor alone and live according to the laws of conscience. Cities are being reborn. If not now, then later someone will come here to restore production. It's inevitable.}
{284}{}{It seems impossible to fight this. Goodbye.}
{285}{}{The elders want isolation. They don't like that strangers will come to the valley again.}
{286}{}{As I said, it's inevitable. All you can do is prepare. You could buy weapons, build fences, restore lost property, and even create a more efficient irrigation system. And for this, oddly enough, you just need the services of my company.}
{287}{}{Are you offering a deal?}
{288}{}{Considering that the whole city is to blame for your troubles and that the factory was opened by your own hands, I propose to provide services to your Villa at a very low price. This will give jobs to the city and allow your people to prepare for the inevitable. Everyone will benefit.}
{289}{}{Sounds interesting. But there is a problem in convincing the elders. I'll think about it.}

{300}{}{What's on your mind?}
{301}{}{Nothing special. I'm going to do something.}

#Quest 2
{310}{}{Old Lucas made an unforgivable mistake. He hit my reputation. And more importantly, he ruined my plans.}
{311}{}{[Listen]}
{312}{}{But that's not the main thing right now, I'll deal with it later. It is much more important to get radio components out of the factory. I need them as soon as possible. Can you do it?}
{313}{}{What if I kill Lucas?}
{314}{}{I doubt you have the guts and the skills. And if they kill you, then our whole conversation will be meaningless. Just get me what I'm asking for.}
{315}{}{I see. I'll do it.}
{316}{}{Well, no. Look for fools.}
{317}{}{Sure. I will do it.}
{318}{}{What will I get for it?}
{319}{}{Of course, I'll pay you for this job. But my respect is worth much more.}
{320}{}{Is there anything else I can do for you, Mr. Kogan?}
{1320}{}{Is there anything else I can do for you, Mr. Kogan?}

{330}{}{These are the parts from the abandoned factory.}
{331}{}{Great. I'm starting to like you. Now it's a small matter - to give this thing to the client.}
{332}{}{What about my reward?}
{333}{}{You will receive it after the successful completion of the transaction.}
{334}{}{What is the deal?}
{335}{}{I am waiting for one very important caravan, with which a new milestone in the history of this city will begin. The caravan is following this detail. And I need reliable people to protect me during the transaction. Are you with us?}
{336}{}{And if I refuse?}
{337}{}{Then you'll upset me a lot. And it's better not to upset me.}
{338}{}{Then I have to upset you a lot, fat man.}
{1338}{}{Then I have to make you very sad, fat man.}
{339}{}{Well, that was very stupid of you. Get out of my town. And you won't get any reward.}
{340}{}{...}
{341}{}{ Yes. I'm with you.}
{342}{}{Very good. Get ready for the meeting, take everything you need. And then come back to me.}
{343}{}{OK.}
{344}{}{Okay, what should I do?}

#Quest 3
{350}{}{}
{351}{}{Are you ready?}
{1351}{}{Are you ready?}
{352}{}{Yes, I'm ready.}
{1352}{}{Yes, I'm ready.}
{353}{}{No, I need to get something else. It won't take long.}
{354}{}{Be careful. Nobody knows about this deal, but anything can happen. I will talk to the caravan, your task is to make sure that everything goes as it should. The client should leave satisfied.}
{355}{}{The goal is clear.}
{356}{}{I could use a pee before an important case. Come back soon.}

{360}{}{The transaction was successful, wasn't it?}
{361}{}{It was a great deal. You have no idea how much. We didn't just earn caps. We gave the city a chance to survive.}
{362}{}{What do you mean?}
{363}{}{This city is degenerating. We used to survive by extracting minerals from the ruins, but their reserves have become scarce. To survive, the city needs not just new orders, but a whole new production.}
{364}{}{So are you going to rebuild that factory?}
{365}{}{Right. However, this will be a meaningless activity without a powerful source of energy. This can only be obtained in Flagstaff, the city where that caravan came from.}
{366}{}{Great idea. This is exactly what the ruined world lacks.}
{367}{}{I am glad that we have reached an agreement. Someday you'll see Garage City like in the good old days - in shining vacuum tubes with a perky be-bop and bikers on motorcycles.}
{368}{}{So what about our deal?}
{369}{}{The current plant is madness!}
{370}{}{So many people think. But I am confident in my abilities. And someday you'll see Garage City like in the good old days - in shining vacuum tubes with a perky be-bop and bikers on motorcycles.}
{371}{}{So what about our deal?}
{372}{}{Yeah, cool. So what about the payment?}
{373}{}{I don't care. I'm only interested in our agreement.}

{380}{}{I appreciate my business partners. Here's your fee for your work - here are 200 caps. I'll also tell Pete to serve you to the fullest. Make yourself at home.}
{381}{}{I'm going to spend the bottlecaps.}
{382}{}{What about the Villa and the raiders?}
{383}{}{And you still won't calm down... The slave convoy has gone to the city of Flagstaff, it is located to the east, a week away from here. Go along the 40th federal highway, you won't miss.}
{384}{}{Great, now I'm going to deal with these damn raiders.}
{385}{}{I hope there will be something to spend the earned caps on.}
{386}{}{How could you accept slavers? Does your conscience torment you?}
{387}{}{You know, fat guy. If I had a nuclear bomb, I would blow up this whole town after what I heard. But I don't have it. Unfortunately.}
{1387}{}{You know, fat guy. If I had a nuclear bomb, I would blow up this whole city after hearing what I heard. But I don't have it. Unfortunately.}
{388}{}{A. Well okay. Later.}

{390}{}{You might be pleased to hear that Lucas is dead.}
{391}{}{Good job. Here's your reward, 100 caps. You can spend it at a local bar, although I don't think that after this you will be met there amicably.}
{392}{}{Thank you for the bottlecaps, Mr. Kogan.}
{393}{}{I was hoping for a different amount for such dirty work. But this one will do.}
{1393}{}{I was hoping for a different amount for such dirty work. But this one will do.}
{394}{}{Can I ask you a question? What do you feel after getting rid of a competitor?}
{395}{}{And what does a person feel after getting rid of garbage? Relief, I suppose. Although, I confess, I am also haunted by a faint sense of loss.}
{396}{}{Go ahead.}
{397}{}{Really?}
{398}{}{Lucas was one of the best scavengers. We were friends at one time. But even such an experienced and valuable person eventually turned out to be a traitor and set a bad example to others. And I'm absolutely not going to worry about it for a long time.}
{399}{}{An original point of view.}