{100}{}{This is Mr. Kogan.}
{101}{}{You see Mr. Kogan. He's still wearing his dirty business suit.}
{102}{}{The transaction was successful.}

{110}{}{Watch the terrain. It is impossible for anyone to interfere with this transaction.}
{111}{}{Deal with these idiots while I'm busy with the caravan.}
{112}{}{Go back to the garage, we'll talk there.}
{113}{}{Get out, I don't even want to see you.}
{114}{}{I'll go back to my garage, but Lucas will have to pay dearly for his insolence.}
{115}{}{This caravan was our only hope for a bright future...}

{120}{}{Everything seems to be clear.}
{121}{}{Damn, these are Lucas's people. Deal with them.}
{122}{}{It's done, you can go back to the garage.}

{200}{}{I don't care about you. Just leave the city, and then you won't get hurt.}
{201}{}{Lucas offers a deal. Give him the plant under management.}
{202}{}{Lucas has lost my trust. He robbed other scavengers and took over Trayvon's territory. Tell him that if he doesn't disappear from my city, it will be the last day in his busy but short life.}
{203}{}{Lucas is not going anywhere. So make a decision right now.}
{204}{}{Okay, I'll tell him about it.}
{205}{}{Okay, guys, you need to get Lucas' people out before they hurt the deal. Do what I say!}
{206}{}{It seems to have started...}
{207}{}{Only Lucas and his people will be able to fully restore the Plant. You should cooperate with him.}
{208}{}{Hmm... Trayvon and his team really don't know anything about this. They are good at rummaging through the ruins, but the Factory needs other skills that Lucas just has.}
{209}{}{So what should I tell him?}
{210}{}{Oh no, he's not going to leave empty-handed.}
{211}{}{Good. Let him get down to business. But let him not count on low taxes. I will not forget his deception.}
{212}{}{Thank you, Mr. Kogan.}