{100}{}{You see a brahmin.}
{101}{}{You see a brahmin, he is looking for sparse vegetation on dry land.}
{102}{}{Moo!}
{103}{}{Moo?}
{104}{}{You were too far away. The brahmin has lost sight of you.}
{105}{}{?}

{200}{}{Mo-o?}
{201}{}{Don't worry so much. I'm just walking by.}
{202}{}{Follow me, animal, I'll give you something delicious.}
{203}{}{Moo!}
{204}{}{No, don't follow me. The shepherds won't like it.}
{205}{}{Let's go, let's go before the savages see...}