{100}{}{This is the senior shepherd.}
{101}{}{You see a cattleman in worn desert clothes.}

{111}{}{All right, stranger, take the brahmin. And may our paths part.}
{1111}{}{All right, stranger, take the brahmin. And may our paths part.}
{112}{}{I hope our paths will never meet again.}

{200}{}{Hey, stranger, don't get too close to the brahmin. What do you want from our peaceful camp?}
{1200}{}{Hey, woman, don't get too close to a brahmin. What do you want from our peaceful camp?}
{201}{}{I need your brahmin... No, the whole Garage City needs your brahmin.}
{202}{}{We don't share sacred animals with scum. Leave us.}
{203}{}{Okay, I'll leave.}
{204}{}{It's worse for you. Go away!}

{220}{}{How did you manage to tame this animal?}
{221}{}{It was born among people. From another brahmin who also lived among people.}
{222}{}{So are you from San Brahmin?}
{223}{}{The Northern Horn Clan. Our people do not like a noisy city, we try to visit San Brahmin only on business.}
{224}{}{I see. Well, I won't bother you.}
{225}{}{This is the first time I've heard of anyone succeeding.}
{226}{}{We've been keeping our secrets from outsiders for generations. If you find yourself in our city, which strangers call San Brahmin, you will see everything with your own eyes.}
{227}{}{I see. Well, I won't bother you.}

{230}{}{There are some scavengers over there. If you don't give them the brahmin, they will take him by force.}
{231}{}{Threats are a common thing for palefaces. Tell them we'll defend ourselves. They cannot defeat those who are protected by the Spirit of the Wasteland.}
{232}{}{Abandon the brahmin if life is precious.}
{233}{}{We cannot be intimidated. I've said it all.}
{234}{}{Damn pale faces! We'll leave. But let the meat of this sacred animal become poison for you. Ar-r!}
{235}{}{A reasonable solution.}
{236}{}{Trust me, I'm trying to save your skins. I am from Villa, we are friends for San Brahmin tribes.}
{237}{}{I've heard about you. If you say that we will be killed, it remains to believe. Tell these savages not to touch us.}
{238}{}{You will not be able to resist their weapons. Hand over the brahmin or you will be killed.}
{239}{}{I'm trying to avoid bloodshed. }

{240}{}{Maybe I can buy out a brahmin?}
{241}{}{(exchange glances) What can you offer in return?}
{242}{}{Let's see...}
{243}{}{To be honest, I don't have anything. Sorry to bother you in vain.}
{244}{}{I'm offering you a pitchfork. Eat, stupid rednecks!}
{245}{}{Shepherds are no longer a hindrance to your plans.}
{246}{}{This is where our paths diverge, stranger.}
{1246}{}{This is where our paths diverge, stranger.}
{247}{}{[Leave]}