{100}{}{Here is a scavenger.}
{101}{}{You see a scavenger ready to hunt a brahmin.}
{102}{}{Damn it! This brahmin has a master. But we still have to take him away. Is that clear?}

{110}{}{Don't make us regret it.}
{111}{}{The Brahmin is ours. Go back to town and please the bartender.}
{112}{}{We didn't think it would end like this!}

{200}{}{It turns out that this brahmin is not wild at all, eh? Listen, we have to get him.}
{201}{}{Are you going to attack the cattlemen?}

{202}{}{The city is dying without food, trade has almost stopped, we NEED this brahmin! So, do you have any better ideas?}
{203}{}{I'm in. Let's get started!}
{204}{}{Don't rush to commit a crime, maybe I can negotiate with these guys.}
{205}{}{But there must be a way to do without bloodshed!}
{206}{}{You're a soft-hearted fool. If you don't want to participate in the attack, then just stand aside. Or will you try to take the brahmin away unnoticed from the shepherds?}
{1206}{}{You're a soft-hearted fool. If you don't want to participate in the attack, then just stand aside. Or will you try to take the brahmin away unnoticed from the shepherds?}
{207}{}{OK, let's do it. Go ahead!}
{208}{}{I won't let you do it.}
{209}{}{Really? And what will you do?}
{210}{}{I know how to fight, unlike these cattlemen. Go away!}
{211}{}{Just let me talk to the shepherds. I will find a common language with them.}
{212}{}{You'll regret it. (spits at your feet) Let's go, guys.}
{213}{}{I've changed my mind. Now you're going to die!}
{1213}{}{I've changed my mind. Now you're going to die!}
{214}{}{Yeah, get out of here.}
{215}{}{I will somehow solve your food problem.}
{216}{}{Your word means nothing to us.}
{217}{}{Then there is nothing left but to attack the shepherds. I'm with you.}
{218}{}{Wait, give me a few minutes. Maybe I can negotiate.}
{219}{}{Will you bring the trade caravans back to the city? Hmm, and you can be trusted. But don't make us regret it... Let's go, guys.}
{220}{}{The correct solution.}
{221}{}{Great idea. I will try to bring this brahmin to you.}
{222}{}{I will solve your food problem. I give you my word.}

{250}{}{Take your time, let me negotiate with the shepherds. Perhaps I can persuade them to hand over the brahmin peacefully.}
{251}{}{Ha! Hermits do not just graze their flocks, they DEIFY their brahmins. Therefore, persuading them to give up a brahmin is like persuading them to cut off their own hand.}
{252}{}{I'll try anyway.}
{253}{}{So we have no other choice. Guys, surround them from all sides!}
{254}{}{Are you really going to attack peaceful shepherds?}
{255}{}{Here's a brahmin. Take him away before the shepherds come to their senses.}
{256}{}{The Brahmin is ours. The savages won't take any chances over his carcass.}
{257}{}{This is a great success! Imagine what kind of feast we will throw from this body? Thank you.}
{258}{}{See you in Garage City.}
{259}{}{The Brahmin is almost in our hands. Wait until I bring him closer...}