{100}{}{This is Trayvon.}
{101}{}{You see a dark-skinned man in dirty clothes.}
{110}{}{Get someone else.}

#Floating replicas during disassembly
{111}{}{Tell me what you're up to.}
{112}{}{Did you really think you could escape?}
{113}{}{Damn rats, I never liked you!}
{114}{}{What the hell does all this mean?}
{115}{}{Hold them tight, otherwise they will escape.}
{116}{}{Now you can't get out of it.}
{117}{}{What do you say in your defense?}
{118}{}{You won't get away with it.}
{119}{}{That was your last mistake.}

#Dialogue during a skirmish
{200}{}{(a tense scene opens up before you - a crowd of scavengers has surrounded a couple of other scavengers and intends to beat them up; but your appearance violates these plans) Who else are you?}
{201}{}{Mr. Kogan sent me. What the hell is going on here?}
{202}{}{What's happening is that we're going to polish the faces of Lucas' guys with sandpaper. These runts allow themselves too much, stealing our equipment and fishing in our areas.}
{203}{}{Aren't you in the same company?}
{204}{}{We're all in Mr. Kogan's cartel. But each clan has its own section of the mine. So far, we've been honest until Lucas's people crossed the line.}
{205}{}{So what exactly did they do?}
{206}{}{I'm telling you, Lucas's people stole the decoder that Mr. Kogan entrusted to us. And then they fled the city. We managed to detain the same two. And now they will be severely punished.}

{207}{}{I know enough. You can continue what you were doing there.}
{208}{}{Then go to the boss and tell him everything. We won't let it go that easily... Stop, bitch! Where to?! (taking advantage of the moment, the detainees tried to escape)}
{209}{}{Er...}

{210}{}{Are you sure lynching is worth it? You're from the same city and the same company.}
{211}{}{Yes, we all took up arms. Our city is dying. Factories in the north remained the only means of salvation. But Lucas is not going to share his findings. He'll just get his hands on it. We have to do something!}
{212}{}{You're right, do what you have to do.}

{213}{}{Let them go. Why do you need extra blood?}
{214}{}{I can't let Lucas get his hands on my mines.}
{215}{}{I'm sorry I can't talk you out of it.}
{216}{}{You're right, do what you have to do.}

{217}{}{Are you suggesting letting them go so that Lucas has more people? Yes, it's stupid!}
{218}{}{You're right, it's stupid. Do whatever you want.}
{219}{}{Calm down, old man. Two lives will remain on your conscience, and it won't change the situation with Lucas.}
{220}{}{Well yes. Maybe you will do something to return the plant to us? I don't think so. (pause) Let them go.}
{221}{}{The right decision. In the meantime, I'll tell Mr. Kogan about it.}
{222}{}{The right decision.}

{230}{}{And who else are you?}
{231}{}{Mr. Kogan sent me. What happened between you?}
{232}{}{Lucas turned out to be a mean rat. He stole the decoder that Mr. Kogan gave us and went to the factory. But this factory is our territory!}
{233}{}{I see. I'll go tell the boss about it.}

#Normal dialog
{300}{}{Hey, what do you want?}
{301}{}{Bye.}
{302}{}{Damn it, how could Kogan trade us for Lucas?! We've worked with him for so many years, and he doesn't put us in anything! I'm not going to put up with it. Someday we'll knock the sons of bitches out of the Factory!}
{303}{}{Great idea. I'm with you.}
{304}{}{Lucas is in charge here now. Suck it up.}
{305}{}{Damn it! My people and I have been working with Kogan for many years. Although he didn't put us in anything, we were sure of his inflexibility. And now Lucas came and just took away his business! Yeah, it's a difficult time right now.}