{100}{}{Here is a buyer.}
{101}{}{You see the merchant. He looks like he's been on the road for several days.}

{110}{}{Where's your boss? Let him hurry up. We're not going to linger in this hole.}
{111}{}{The buyer does not want to communicate with you.}
{112}{}{A great deal for such a forgotten hole.}
{113}{}{A complete disappointment was to be expected from such a hole. I'll have to leave with nothing.}
{114}{}{I'll be damned! What is a Follower of Fire doing in such a hole?}
{115}{}{Hmm. I didn't think I'd see power armor in such a hole. Curious.}