{100}{}{Here is a settler.}
{101}{}{You see one of the few residents of Garage City.}

{110}{}{Stay away from me.}
{111}{}{What do you need?}
{112}{}{Hi. How are you?}

{200}{}{Do you always break into other people's houses uninvited? Okay, whatever. I can't help you anyway.}
{201}{}{I just want to ask about the city.}
{202}{}{I don't need anything from you.}
{210}{}{You again? Great. What is it this time?}
{211}{}{I want to ask about this city.}
{212}{}{Nothing.}
{213}{}{Why would I want to talk to you? I don't see the point in it. Only poison the stomach with empty talk.}
{214}{}{I'll think about how I can butter you up.}
{215}{}{And you always demand payment from strangers for answers, right? I think I won't stay here after this.}

{220}{}{Well, Garage City is a city of scavengers. Everyone here lives off a mine run by Mr. Kogan's cartel.}
{221}{}{Thank you, it was an exhaustive answer.}
{222}{}{Scavengers?}
{223}{}{Just workers who find old things and take them to the garage for repair.}
{224}{}{Who is this Kogan?}
{225}{}{He runs a cartel of scavengers, and practically the whole city. With such a person, you need to be respectful and careful in choosing words.}
{226}{}{What is the mine?}
{227}{}{Just a place where old things are found. Go into the garage building opposite and talk to Pete if you're interested.}
{228}{}{How are you doing here?}
{229}{}{It couldn't be worse. Previously, the cartel provided excellent earnings, but not now. And even after earning the caps, there is nothing to spend them on, because trade with other cities has almost stopped. A little more, and the city will come to an end, unless someone comes up with something.}
{230}{}{It couldn't be worse. Previously, the cartel provided excellent earnings, but not now. However, after the restoration of the Plant, some progress has been made. It seems to me that the city still has chances for a bright future.}
{231}{}{He used to run a cartel of scavengers. But that's history.}