{100}{}{Here is a settler.}
{101}{}{You see one of the few residents of Garage City.}

{110}{}{So you're here in passing? That's good.}
{111}{}{You'd better go. There is no place for new settlers here.}
{112}{}{For the first time in a big city?}
{113}{}{Garage City is a great place, you'll love it here.}
{114}{}{Are you going to stay here?}
{115}{}{We have our own rules here, peasant.}
{116}{}{I don't understand why people still go to this forgotten city.}

{120}{}{Hi! How are you?}
{121}{}{Wow, what people. Are you here for a long time?}
{122}{}{How is the harvest, amigo, on the rise?}
{123}{}{Hello, amigo.}
{124}{}{Sorry we didn't meet you very well.}
{125}{}{We didn't know that the peasants of the Villa were so friendly.}
{126}{}{Do you need help?}

{130}{}{Stay away from me.}
{131}{}{Dig in your garden beds, peasant, but don't come near me.}
{132}{}{Tell your headman that he is a greedy and arrogant bastard.}
{133}{}{Your Villa has never been distinguished by good people.}
{134}{}{Are all the residents in your Villa as cunning and greedy?}
{135}{}{Now it is clear why the Villa set such high prices.}
{136}{}{I'll tell you how it is. I was glad to see your relatives on their knees.}
{137}{}{When we were hungry, you raised prices.}
{138}{}{Fuck off, you dirty peasant.}
{139}{}{The villa got what it deserved.}