{100}{}{Here is a sick scavenger.}
{101}{}{You see one of Trayvon's scavengers. He is suffering from the effects of some kind of illness.}
{102}{}{You have successfully cured the scavenger's disease.}
{103}{}{You are unable to analyze the disease and even more so to cure a person without medication.}
{104}{}{This scavenger is suffering from the effects of radiation sickness. Your skills do not allow you to cure him without special medications.}

{110}{}{*Cough-cough*}
{111}{}{I'm sorry, I'm not feeling well.}
{112}{}{I got sick after another trip to the ruins.}
{113}{}{*hack* ...I'm sick, as you can see.}
{114}{}{...It's not contagious, don't worry.}

{115}{}{Thank you for your help, I have already said goodbye to life.}
{116}{}{If it wasn't for you, I would have suffered until I was completely exhausted.}
{117}{}{There is no price for doctors like you.}
{118}{}{I got sick after another foray into the ruins.}
{119}{}{Are you looking for your people? They were taken east, that's all I know.}

{120}{}{Oh...}
{121}{}{*Cough-cough*}
{122}{}{*Hack*}
{123}{}{Uv...}
{124}{}{*Groan*}
{125}{}{Hr-r...}