{100}{}{This is Frank.}
{101}{}{You see one of the few residents of Garage City.}
{102}{}{Oh, oh, I need to go to the bathroom right now...}
{103}{}{Frank is not able to talk right now.}
{104}{}{Boo-uh...}
{105}{}{Hr-r-r...}
{106}{}{After a good drink, Frank passes out in his torn chair.}
{107}{}{Oh-oh...}
{108}{}{Something is not good for me...}

# Before the quest
{200}{}{Hey, hey, this is my house. What do you want here?}
{201}{}{I'm a thief.}
{202}{}{That's how. Fine. Great. It's just magical. Get out of here, you fool!}
{1202}{}{That's how. Fine. Great. It's just magical... Get out of here, cheeky!}
{203}{}{Bye.}
{204}{}{Hey, it's just a joke. I'm your new neighbor.}
{1204}{}{Hey, it's just a joke. I'm your new neighbor.}
{205}{}{Listen, who are you kidding? No one has been going to our city on their own for a long time. There is no work here! But if you really want to live next door, then do me a favor - don't bother me.}
{206}{}{Okay. Whatever you say.}
{207}{}{I want to meet new neighbors.}
{208}{}{Why so much distrust of neighbors?}
{209}{}{}
{210}{}{Do me a favor and stay out of my way.}
{211}{}{Why so much distrust of neighbors?}
{212}{}{Okay. Whatever you say.}
{213}{}{You can't trust anyone in this city. Even to your neighbors, who are only looking at your good. It's worth going out the door - and here someone climbs into your lock with a lock pick.}
{214}{}{Was something stolen from you?}
{215}{}{Yes, everyone here has something that periodically disappears. It started as soon as things in the mine began to decline and a lot of workers were left without earnings.}
{216}{}{What exactly was stolen from you?}
{217}{}{Welding machine. This is a very valuable item. There are only a few such devices in working condition for the whole city. He's been giving me a great income so far. But what should I do now?}
{218}{}{I see. I can look for the missing.}
{219}{}{Really? Or maybe it's a cunning plan - to steal first and then resell? Although why am I? You're new here, and the loss happened much earlier. Okay, if you find my things, I'll try to buy them back.}
{220}{}{Okay, I'll do it.}
{221}{}{Don't worry about it. The thief will be punished. After all, as a ranger, I swore to protect the law in these lands.}
{1221}{}{Don't worry about it. The thief will be punished. After all, as a ranger, I swore to protect the law in these lands.}
{222}{}{Hey, hey, so you're a ranger? Why the hell would I find out at the last moment? I don't need anything like that, I'm a free resident and I'm not going to kneel in front of you!}
{223}{}{It's not your concern anymore. I'll deal with the thief, whether you want it or not. Wait for the result.}

#After receiving the quest
{230}{}{You again? What do you need?}
{231}{}{Is that what they've been saying about you lately? Well, to what do I owe your visit?}
{232}{}{Hello, neighbor. What's new?}
{233}{}{Yes, I just wanted to say hello before leaving.}

{240}{}{What are you doing, Frank?}
{241}{}{I make statues, baby. They sell well all over the Wasteland.}
{242}{}{Must be a profitable business?}
{243}{}{Seriously?}
{244}{}{And what else is there to do in this hole? I used to work in a cartel like the others. Mined and repaired old things. Except there's almost no work left in the city, I'm barely making ends meet.}
{245}{}{Sorry. Can I ask you another question?}
{246}{}{A sad story. Later.}

{250}{}{About that welding machine.}
{251}{}{Any leads?}
{252}{}{No, but I still hope to find it.}
{253}{}{Any idea who could do this?}
{254}{}{If I had any ideas, I would have found and returned my device a long time ago. Obviously, the thief will not shine them for a very long time. Here you need to act with cunning so that the thief gives himself away.}
{255}{}{I see.}
{256}{}{Here's your welding machine.}
{257}{}{It's really him. And I thought it was hopeless. So who was the thief?}
{258}{}{He was, uh, lying in a dump. I don't know who put it there.}
{259}{}{Hmm, either you have incredible instincts, or you're just covering for a thief. Thanks anyway. Here are yours }
{260}{}{ caps.}
{261}{}{Please.}
{262}{}{It was Todd from the trailer.}
{263}{}{Ha! Todd thinks he's the smartest one here. But sooner or later justice will find anyone, anywhere. Now give me my phone. Here are your }
{264}{}{ caps. But not a word to anyone.}
{265}{}{No problems.}