{100}{}{This is Todd.}
{101}{}{You see one of the few residents of Garage City.}
{102}{}{Hi. Thanks for the help with the coyotes.}

{200}{}{Hey, you. I don't remember seeing you in our city. Where are you from?}
{201}{}{I'm just passing through here. And what?}
{202}{}{Just like that. Strangers have become a rarity in our city... Yes, my name is Todd.}
{203}{}{Nice to meet you.}
{204}{}{If you are ingratiating yourself into trust, then keep in mind that it does not work on me.}

{210}{}{Hi. What is it this time?}
{211}{}{Hi. How can I help you?}
{212}{}{Nothing. Later.}

{220}{}{What are you doing here, Todd?}
{221}{}{Well, I'm more of a specialist in collecting and cleaning iron. I've been honing my skills for years.}
{222}{}{Must be a profitable business?}
{223}{}{I see.}
{224}{}{Actually, not really. The mine is closing, there is not enough work here. And then there are animals next to my trailer.}
{225}{}{Animals?}
{226}{}{Damn coyotes. I don't know what they smelled, but there's a whole pack of them. I'm afraid to get too close. And after all, all my tools are in my house. Will you help me get rid of the coyotes? I'll pay five caps for each of them if I just get to my place.}
{227}{}{Okay, that's settled.}
{228}{}{I'm not a hunter, but I'll think about the offer.}
{229}{}{Actually, not really. The mine is closing, there is not enough work here. Besides, it's a dirty and hard business.}
{230}{}{I see.}
{231}{}{I'll get rid of the coyotes. But first answer the questions.}
{232}{}{Where is your trailer located?}
{233}{}{Go to the Watts Electronics plant. And then turn left along the road.}
{234}{}{I see. Another question.}
{235}{}{I'm going there right now.}
{236}{}{The coyotes are over.}
{237}{}{Oh, cool. Looks like it's time to pay, right? Otherwise you won't leave me alone...}
{238}{}{Unusually clean caps. Where are they from?}
{239}{}{Happily.}
{240}{}{They're just well preserved. Don't you care? Take it in silence and spend it on something.}
{241}{}{Then there are no questions.}
{242}{}{And it seems to me that you made them from the scrap metal that you collect near the factory. What do you say to that?}
{243}{}{Hush! Don't tell anyone. Don't you care where and how these bottlecaps were produced? The pre-war caps are already rusted, but at least these are intact. Take it and keep quiet. No one will believe you anyway.}
{244}{}{I'm not judging you. Just be careful next time. Happily.}
{245}{}{Silence is expensive. For 100 caps, I will close my eyes to this case.}
{246}{}{Damn, do you have any idea how much work it takes to make one cap? Well, let it be your way. But don't you dare tell anyone!}
{247}{}{Whatever you say. Happily.}

{250}{}{Tell me about the Garage.}
{251}{}{This is a scavenger camp. Nearby are the ruins of the old city, from which we pull out useful things, repair them and sell them to the south.}
{252}{}{Sounds good.}
{253}{}{But the mine is completely depleted. It seems that soon you will have to collect things and look for new ruins, if the city suddenly does not have an additional source of income.}
{254}{}{And what do you get in exchange for work? Corn cobs?}
{255}{}{caps, redneck! bottlecaps! We use them the way we used money in ancient times. Hmm. It wouldn't hurt for you to get a wallet, too. Remember - now nothing goes without caps in big cities.}
{256}{}{And you know a lot. Can I ask you a couple more questions?}
{257}{}{Thanks for the advice. I have to go now.}
{258}{}{I see. Can I ask you one more question?}