{100}{}{You see an old man.}
{101}{}{You see a swarthy old man with a thick beard.}
{102}{}{This is old Carmelo.}

#Acquaintance
{200}{}{Wait, don't get too close! Everyone here knows better than to mess with you.}
{201}{}{And they are right. So shut your mouth, old man.}
{202}{}{Okay, okay, but know that I'm still able to stand up for myself.}
{203}{}{Keep your distrust to yourself. I'm interested in something else.}
{204}{}{I won't hurt you. Don't believe the rumors.}
{205}{}{I hope so. But keep in mind that I am still able to stand up for myself.}
{206}{}{These threats are unnecessary. Let's just talk.}
{207}{}{Ah, this is our new celebrity. To what do I owe?}
{208}{}{What can an old man like you offer me?}
{209}{}{Well, nothing, probably. Why would I offer you something?}
{210}{}{Then just talk.}
{211}{}{Then I'm not interested in you. Goodbye.}
{212}{}{I'm looking at you and I think we should get to know each other.}
{213}{}{Usually people don't impose themselves just like that. But for some reason, I believe you.}
{214}{}{Just wonderful. Shall we talk?}
{215}{}{You're right, you shouldn't force yourself into a conversation with a beggar like you. Be.}
{216}{}{What do you want? If it's an iguana, I won't give it to you. I have nothing to eat myself.}
{217}{}{Come on, I'm not going to rip it out of your mouth.}
{218}{}{That's good. And then you'll be left without a hand. What do you want?}
{219}{}{Just to talk.}
{220}{}{Looking at you, I understand that nothing.}
{221}{}{Come on, give me an iguana! Now!}
{222}{}{Yes on! Take it! And there's nothing to wave your arms around here. And where do you come from in such a wilderness...}
{223}{}{I'm not done with you yet. I need answers to questions.}
{1223}{}{I'm not done with you yet. I need answers to questions.}
{224}{}{That's enough for now. But I'll be back.}
{225}{}{Hands off! This is my prey! If you need a lizard, go and catch it in the desert.}
{226}{}{Don't be angry, old man. It's just a joke.}
{227}{}{I'll do that. Anyway, I don't want to communicate with such a greedy person anymore.}
{228}{}{I have no evil intentions. Here, take the cap as a sign of my honesty.}
{229}{}{Is this a joke?}

#Repeat dialog
{230}{}{Really?}
{231}{}{You again?}
{232}{}{}
{233}{}{Bye, old man, the trumpet is calling.}
{234}{}{There would be something to buy in this city... But thanks for the cap.}

{239}{}{Well, there's nothing to pull an iguana by the tail. Tell me straight out, what do you want?}
{240}{}{Who are you?}
{241}{}{My name is Carmelo. I just live here.}
{242}{}{Have you lost your memory? My name is Carmelo.}
{243}{}{Actually, I want to ask something else.}
{244}{}{Goodbye, old Carmelo.}
{245}{}{What are you doing here?}
{246}{}{I catch lizards and sell them to the rest of the residents. And it's not so easy to catch them.}
{247}{}{Did you also work as a garbage man?}
{248}{}{Yes. I had a great nose for useful things. After all, even a handful of garbage can be used. (sigh) But the mine has become impoverished, now I'm looking for lizards instead of old utensils.}
{249}{}{I see. Actually, I want to ask something else.}
{250}{}{I gotta go, man. See you again.}
{251}{}{Did you work as a garbage man?}
{252}{}{Why are you so distrustful, old Carmelo?}
{253}{}{Live here as long as I have lived, you will also become distrustful.}
{254}{}{Are you always so distrustful?}
{255}{}{Remind me, what are you doing here?}
{256}{}{Did you also work at the mine?}
{257}{}{Indeed, you don't often meet an elder in these places.}
{258}{}{They say they used to live up to a hundred, but now rare lucky people manage to reach my age. It probably saved me that I didn't get into all sorts of scrapes.}
{259}{}{By the way, what are you doing here?}

{260}{}{Seriously? I just had some garbage in my pocket. Take a look...}
{261}{}{Well ... (with interest sorting through the trash from your pocket) If I had such pockets, I would have gotten rich a long time ago.}
{262}{}{Is there something useful here?}
{263}{}{Look, there's a pre-war bill here, a couple of caps, and a small-caliber cartridge. At best, you can buy an iguana for all this. But it's better than nothing, right?}
{264}{}{Ugh, I really thought this garbage wouldn't be of any use.}
{265}{}{So I still have everything ahead of me. I'm going to look for an investor.}

{266}{}{Hey, old man, do you know anyone with a welding machine?}
{267}{}{There's definitely one in the garage. Frank also owned the machine, but he's still a miser. Oh, yeah, I smelled welding from Todd's cabin recently. Maybe I just imagined it, but ask him just in case.}
{268}{}{Thank you.}
{269}{}{You can't do much without welding. Therefore, Mr. Kogan once outbid most welding machines. There weren't enough of them already.}

{270}{}{Tell me, did a slave convoy pass through here?}
{271}{}{Yes, there were such. But then I went to the wastelands so as not to cross paths with such dangerous people.}
{272}{}{Do you know where the convoy went?}
{273}{}{Somewhere to the east. I haven't been to those parts.}
{274}{}{Thank you. But I still have questions.}
{275}{}{That's it, I'm already going in that direction. Bye.}
{276}{}{After the question about slaves, this raises suspicions.}

{280}{}{Tell me about this mine.}
{281}{}{What's there to tell? No one used to live in these parts. And when the cartel opened, crowds of scavengers came here.}
{282}{}{I have no more questions about the mine.}
{283}{}{I think I should go.}
{284}{}{What is the cartel doing?}
{285}{}{Buys finds from scavengers, then repairs and takes them to auction in other cities.}
{286}{}{Who are the scavengers?}
{287}{}{scavengers, looters, call it what you want. They mine useful things in the ruins and carry them to the garage for recycling.}
{288}{}{Does this job attract people?}
{289}{}{Of course! Many come here hoping to earn a mountain of caps and go to more trustworthy settlements. But more often this stop turns out to be the last for them.}
{290}{}{You say that like the end of the city has come.}
{291}{}{It hasn't come yet. But there's not much left. The resources in the ruins are depleted, and people have nothing else to earn. Therefore, the city is dying out. And it will die out if someone doesn't come up with something.}
{292}{}{Nothing will help this dump for sure.}
{293}{}{A sad story. Let's change the subject.}
{294}{}{Is there really nothing we can do?}
{295}{}{Well, if the garage still decides to restore the old factory, then it can save the settlement and give jobs. But something I hardly believe in it.}
{296}{}{What's the story with the plant?}
{297}{}{It's a crazy idea to restore an old factory. Such an enterprise needs a lot of energy and a lot of workers. And what is even more important - knowledge that no one has now. People can only hope for a miracle.}
{298}{}{Who needs all this old industry? We do without her at the Villa, with our own hands.}
{299}{}{Believe me, there are places in the south that are waiting for all these pre-war wonders. You can't do much with your hands alone.}

{300}{}{If no one lived here before, then where did these ruins come from?}
{301}{}{Earlier - this is before the arrival of the cartel. Don't twist the words. Of course, before the War, there was a whole town called Kingman. But that was almost a hundred years ago.}
{302}{}{What are you talking about? Is there a war going on somewhere?}
{303}{}{Don't you know? It's an old story. There are many legends about her. They say that a hundred years ago there were large states that could not get along and divide the remnants of "garbage". Just like now in our Garage City.}
{304}{}{So they destroyed each other?}
{305}{}{They came up with a very formidable weapon that wiped entire cities off the face of the earth. Few survived. And we are their descendants. Already five or six generations have changed since then.}
{306}{}{There can't be such a powerful weapon. It's all stories!}
{307}{}{Here you will visit the cities in the south and see with your own eyes. Although why am I arguing with you - I've heard these stories in retellings myself.}
{308}{}{Exactly. Leave your horror stories to the kids by the fireplace.}
{309}{}{Surely there is some truth in this sad story.}
{310}{}{And you have a chatty tongue. It's not good.}

{320}{}{Tell me about catching iguanas.}
{321}{}{An iguana? Desert lizard. Catching them is still a concern. But there is no better snack for any swill in the world. Do you want a piece? I won't give it for free.}
{322}{}{Enough about lizards. My stomach is already rumbling.}
{323}{}{That's great. Otherwise, if everyone around starts catching lizards, then I will have nothing left.}
{324}{}{Is there really no other food here?}
{325}{}{So where does it come from? There are deserts and mountains all around. Previously, the products were brought by traders from the south. But lately, there are fewer and fewer caravans, and the products are getting dirtier. We have to catch lizards, and at least some food.}
{326}{}{What about coyotes and scorpions?}
{327}{}{Things are more dangerous with them. A coyote can bite off a leg. And scorpions are poisonous, and there is less meat in them.}
{328}{}{Have you tried growing crops?}
{329}{}{Where, here? Apart from dry grass and mold, nothing grows here in the old basements. There is a hydroponic farm nearby, but this one will feed only a few people.}
{330}{}{How do you catch them?}
{331}{}{Don't expect me to tell you. I don't need competitors here.}
{332}{}{I wonder where you got such questions from? As if you know how to grow maize in the desert.}
{333}{}{Come on, old man, everyone here is their own.}
{334}{}{Good people should share their experience.}
{335}{}{And if I pay 25 caps?}
{336}{}{I doubt you have any. Probably robbed someone or took it off a corpse. And I don't need that.}
{337}{}{Well, well.}
{338}{}{Earn your trust first, then we'll talk.}
{339}{}{Are you trying to humiliate me now, an old man in rags?}
{340}{}{I didn't allow myself to be rude.}
{341}{}{Of course, no problem.}
{342}{}{And if I pay?}
{343}{}{How will you pay? caps? Now there is nothing to buy with them in this city.}
{344}{}{Well, if you think about it, the bottlecaps are back in business after all these events at the Factory. Give me 50 caps.}
{345}{}{You're not going to keep deceiving me, are you?}
{346}{}{Hmm... Agreed. But first, fulfill one of my little requests.}
{347}{}{Just tell me how you catch lizards.}
{348}{}{No, that won't do.}
{349}{}{Which one?}
{350}{}{So what do you want?}
{351}{}{Mushrooms. Those strange green mushrooms that grow in toxic puddles near the Plant. Bring some, and then I'll tell you about my trapper tricks.}
{352}{}{Okay, I'll try to get it.}
{353}{}{That's good. Come on, move.}
{354}{}{Mushrooms from toxic puddles? What for?}
{355}{}{That's my business. Just get it and bring it.}
{356}{}{Agreed. But don't try to deceive me, old man.}
{357}{}{No problem.}
{358}{}{If you catch a parish from them, then it's not my problem. See you later.}

{360}{}{Share your wisdom, how do I get these damn mushrooms?}
{361}{}{Toxic puddles are burning, you need tight shoes. Rubber boots will do, but they won't last long.}
{362}{}{Clear.}
{363}{}{Why don't you climb into this sewer yourself?}
{364}{}{Because I have you.}
{365}{}{Don't worry. Grab the mushrooms and run back.}
{366}{}{And that's it? Not enough. Bring more.}
{367}{}{It's starting to make me nervous.}
{368}{}{Okay, no problem.}

{370}{}{Here are your mushrooms. I hope you know what you're doing.}
{371}{}{I can smell these mushrooms a mile away.}
{372}{}{But where are they? We were here...}
{373}{}{Oh, yes, that's enough for me for a long time.}
{374}{}{So how do you catch iguanas?}
{375}{}{That's how I catch.}
{376}{}{Eh, for mushrooms?}
{377}{}{Not quite. These mushrooms attract some insects, and already insects attract lizards. Few people know about this trick.}
{378}{}{That's it! And you know a lot.}
{379}{}{A curious scheme. Surely not the only one in your craft.}
{380}{}{Sure. But tell me, what exactly are you going to do?}
{381}{}{Tell us about iguanas, their habits, and habitats. [Survival +3]}
{382}{}{Tell me about the trapper's tricks. It could save my life. [Traps +3]}
{383}{}{Better share your scavenger skills. You worked in the cartel once. [Repair +3]}
{384}{}{Then listen carefully, I won't repeat it twice.}
{385}{}{Speak up, old man. I want to absorb all your experience...}