{100}{}{This is Eugene.}
{101}{}{You see a teenager. His hands are dirty with dirt and rust, apparently he likes to tinker with technology.}
{102}{}{Did you want a happy life, man? This is the best I can offer.}
{103}{}{Sorry, man, but in this life you were expected only pain and suffering.}
{104}{}{Eugene has reached his destination.}
{105}{}{Wow!}
{106}{}{While Eugene is on your team, you get a bonus of 20 points to repair broken equipment.}

#Floating replicas when visiting locations:
{120}{}{ }
{121}{}{Wow! I've never seen anything like it!}
{122}{}{Is this a real live radio station? Awesome!}
{123}{}{ }
{124}{}{Let's get out of here, this place scares me.}
{125}{}{You're lucky to have a house like this. But I have to live in a barrack made of garbage.}
{126}{}{I've heard about this city, but I didn't even hope to be here!}
{127}{}{I don't know why, but I don't like this place.}
{128}{}{It doesn't look like a ranger base. Don't you think we've lost our way?}
{129}{}{What are all these people doing?}
{130}{}{What... what happened here?!}

#Final dialogue
{190}{}{Thanks for everything. These rangers are tough guys, and their dam is a real fortress. I'm so happy!}
{191}{}{It's good that you like it here. Have a good stay.}
{192}{}{Pull up your pants, sucker. You still have a lot to learn.}
{193}{}{Hi.}
{194}{}{For now.}

{195}{}{They say a lot of bad things about you in the wastelands. Don't you want to explain?}
{196}{}{To be honest, you are just an object of earnings for me. No more than that.}
{197}{}{This is the gossip of my enemies. Nevermind.}
{198}{}{I thought so...}
{199}{}{M?}

#The first dialog
{200}{}{And who else are you? Hey, you're not from around here!}
{201}{}{Uh, yeah.}
{202}{}{Then where are you from? Are you also engaged in enslaving peasants?}
{203}{}{Actually... YES!}
{204}{}{Get away from me!}
{205}{}{Hey, don't be so nervous...}
{206}{}{On the contrary, I release them. What do you know about the attack on the Villa?}
{207}{}{Nothing. Better leave before the others give you a "warm" welcome.}
{208}{}{Why would they do that?}
{209}{}{Okay, okay, I'm hardly going to stay here.}
{210}{}{This place is dying. Soon there will be no resources left in the ruins. Then the cartel will close, and the residents will be left with only a bandit's share. How I wish I could get out of this damn place!}
{211}{}{Where, for example?}
{212}{}{To the Rangers. Or just to the south, where there is at least some kind of civilization.}
{213}{}{You have ambitious plans. Adios, muchacho.}
{214}{}{What do you know about the enslavement of the Villa?}
{215}{}{Hi.}
{216}{}{Bye.}
{217}{}{Todd lives here. He doesn't like uninvited guests.}

#In the team
{220}{}{Why are we still here?}

{221}{}{Are we going to be with the Rangers soon?}
{222}{}{Do we have a long way to go?}
{223}{}{I'm tired...}
{224}{}{Let's make a halt, eh?}
{225}{}{I can't wait to see the Ranger Dam.}
{226}{}{Do you know exactly where to go?}
{227}{}{It must be great to travel in the company of rangers.}
{228}{}{Is it true that rangers drink their urine while traveling?}
{229}{}{I wish I could see the Ranger General himself!}

{230}{}{Wait here, I'll be back soon.}
{231}{}{Let's go.}
{232}{}{Get it out of your hands.}
{233}{}{But you will protect me, won't you?}
{234}{}{Take it off yourself.}
{235}{}{Whatever you say.}

{236}{}{I want to get home as soon as possible... However, I don't know what I want anymore.}
{237}{}{I don't like your team. Are they coming with us too? Then I'm staying.}
{238}{}{That's not a good idea, man.}
{239}{}{Eugene doesn't trust your noisy team, he'll only go with you.}

#Joining the team
{300}{}{Hey, man, the Rangers are interested in your skills. I'm here to take you to the base.}
{301}{}{What?! Is it true?! Wow! Yes, I've been dreaming about this since the day I first saw Ranger. But...}
{302}{}{But?}
{303}{}{My father won't let me go. He doesn't even want to hear about Rangers and thinks I should be like him, a scavenger. But I'm not interested in digging into scrap metal, I want to repair this scrap metal!}
{304}{}{Exactly. Your talents won't be able to reveal themselves in this place. Go to the Rangers.}
{305}{}{I can't run away. And if I run away, the locals will become bitter against the rangers. They already treat them with contempt. Please talk to your father! Maybe he'll listen to you?}
{306}{}{Okay, I'll talk to him.}
{307}{}{The offer about the Rangers is still valid.}
{308}{}{It's great... But I can't leave until my father agrees.}
{309}{}{Okay, I'll talk to him.}
{310}{}{Your padre has agreed. You can be free.}
{311}{}{Really?! I didn't even hope. I thought he'd never let me... So when do we leave?}
{312}{}{Right now. Let's go.}
{313}{}{Your padre is dead. You're free now.}
{314}{}{How?! But... I didn't think it would turn out like this. (sobbing) Whatever he was, he wanted only the best for me... (calms down) Well, now I definitely have nothing to lose. When do we leave?}
{315}{}{Right now. Come on.}
{316}{}{How about an inconspicuous portion of scorpion venom?}
{317}{}{It's not serious, is it? I will never forgive you then!}
{318}{}{Don't you want to just run away?}
{319}{}{Then the Rangers will be treated even worse here than they are now. And I won't run far.}

# If the dam is destroyed
{320}{}{I have bad news for you: the Ranger base has been destroyed.}
{321}{}{It can't be! I was so hoping that everything would get better... that you don't have to pick through the trash anymore for a couple of caps... But I don't want to go home now either. What should I do?}
{322}{}{You won't survive alone in the desert, and the Rangers aren't up to you right now. Come home.}
{323}{}{Now no one will pay me to guard your ass. Which means you're on your own. Disappear.}
{324}{}{My father warned me not to trust you. I'll find my own way!}
{325}{}{That's great.}
{326}{}{Yes, of course... I can't believe it was all in vain!}
{327}{}{Well, maybe life in a landfill isn't so bad. Let's go.}
{328}{}{Here you are at home. What's the matter?}
{329}{}{You know... This journey with you has not been in vain. I've seen so much, discovered a whole world I didn't know anything about. After all this, I will not be able to live in the old way. Someday I will definitely go south.}
{330}{}{Sounds flattering, though sad. Goodbye.}
{331}{}{Well, you now have the right to decide for yourself. My job is done. Have a good stay.}