{100}{}{You see a scavenger.}
{101}{}{You see a man burned by labor and time.}
{102}{}{*Clutching his chest convulsively*}
{103}{}{Arch...}
{104}{}{You have made a successful transaction. It's time to make Eugene happy with this news.}
{105}{}{You'd better not disturb me.}

#The first dialog
{200}{}{What do you need, stranger?}
{1200}{}{What do you need, stranger?}
{201}{}{Why such rudeness?}
{202}{}{(spits as if casually) We're not used to sissies here, I'm sorry.}
{203}{}{Eh, nothing...}
{204}{}{And I'm not used to seeing ragamuffins. Later.}

#Repeat dialog
{210}{}{So what do you need?}
{211}{}{Nothing.}
{212}{}{Can you tell us about this settlement?}
{213}{}{I don't have time for an ass like you.}
{214}{}{Why is there a crossed-out star painted on your door?}
{215}{}{Rangers. These filthy lovers of other people's goods want to take away from me the most valuable thing - my son. I'm trying to shield him from this stupidity.}
{216}{}{Why do they need your son?}
{217}{}{They recruit young animals and then prepare warriors and scouts from them. I didn't work at this mine in order for my son to become a murderer in the name of someone else's idea. Let him plow, like me, on the ruins and benefit his home, not someone else's.}
{218}{}{What's the situation with the Rangers?}
{219}{}{A crowd of armed guys who are trying to get their hands on the whole neighborhood. They promise security and order in exchange for resources and recruits.}
{220}{}{And what's the catch?}
{221}{}{Sounds quite acceptable.}
{222}{}{Yes, only life has taught that you can not believe such. They just row for themselves, and share only the surplus. The same raiders, only they speak in beautiful words.}
{223}{}{I see.}
{224}{}{Okay.}

#Quest
{250}{}{I'm here to take your son to the Rangers.}
{251}{}{Get out, Ranger henchman! You won't get anything here except a piece of scrap between your eyes.}
{252}{}{So that's what you're teaching him - using scrap to harm, not benefit?}
{253}{}{I said get out!}
{254}{}{...He can do more. He can be engaged in complex technology, and not collecting dirty garbage.}
{255}{}{I know better what he needs!}
{256}{}{This city will die sooner or later, and Eugene will have nothing left but junk.}
{257}{}{Yes, it's true... So what? How do I know these Rangers really mean well to Eugene? I don't believe them!}
{258}{}{Trust Eugene. Look how he's wasting away in this dump. Is this what you want? He will gain at least some future from the Rangers.}
{259}{}{You speak with the words of a Garbage Devil... Take Eugene and take him to a better place. But keep in mind and remember - if something happens to him, you will answer for it with your head!}
{260}{}{You don't have to worry about anything. Eugene is in good hands}
{261}{}{I don't think I can convince you.}
{262}{}{One more word and you'll pay for it!}
{263}{}{Listen to my words - it will be better for him.}

{270}{}{I can buy Eugene out. How much do you want for the contract?}
{271}{}{You will never collect so much valuable junk in your whole life.}
{272}{}{Take a look at my offer first...}
{273}{}{Then forget it.}
{274}{}{Ha-ha! Get out of here.}
{275}{}{[Leave]}
{276}{}{Finally, this brat has brought me at least some benefit. And what is this? A contract? I can't write! Okay, I'll put a cross, if that's what you want. Now take my son. But if something happens to him on the way, I will personally rip your head off! Clear?}
{277}{}{Clear.}
{278}{}{(scratching his unshaven cheek in thought)}
{279}{}{[Next]}