{100}{}{Here is the gatekeeper.}
{101}{}{You see a very tanned and not shaved guard for a long time. His steady gaze drills right through you.}
{102}{}{I'll be damned! Is this bike really on the move?!}
{103}{}{That's another conversation! Welcome to Garage City.}
{104}{}{Welcome to Garage City. But to get into the city, you will have to answer a couple of questions.}

#The first dialog
{200}{}{Wait, stranger. What are you doing in town?}
{201}{}{I'm looking for my fellow tribesmen. They were enslaved and taken away in this direction.}
{202}{}{I need a bed for the night.}
{203}{}{Probably none.}

{204}{}{I don't know anything about it.}
{205}{}{So can I pass?}
{206}{}{And I know for sure that they were here.}
{207}{}{Maybe so. You need to talk to the guys at the bar or the cartel boss.}
{208}{}{OK. So can I pass?}
{209}{}{I said I don't know.}
{210}{}{I want to ask the other settlers. Can I pass?}

{211}{}{We have a hotel, but I'm not sure there are available seats there.}
{212}{}{Maybe I'll go there and ask?}
{213}{}{Sounds unconvincing. If you really are here by chance, then you should not bother the residents.}
{214}{}{Still, I want to look around.}

{215}{}{Are you leaving already? And correctly... After Mr. Kogan's death, people in the city went wild.}
{216}{}{Sorry to hear that.}
{217}{}{Serves you right. There was nothing to make friends with slavers.}
{218}{}{You mean the convoy from Flagstaff? Yes, the deal was not the best, but it brought the city a good income. I doubt that these two cases were connected... Or not?}
{219}{}{Think about it. And my business here is really already over.}

{220}{}{Stop! Show me your hands.}
{221}{}{Hands? What for?}
{222}{}{(raises his gun threateningly) Just show me your hands!}
{223}{}{I'll show you the right hook first!}
{224}{}{Okay, calm down. I don't want to get into a fight over some little thing. But keep in mind that we don't like them.}
{225}{}{And what does the hands have to do with it?}
{226}{}{Okay, here, look.}
{227}{}{Hmm? Looks like you're fine. Come on in.}
{228}{}{What the hell does that mean?}
{229}{}{A routine check for shakes. All Jackals have this syndrome, but we don't need them.}
{230}{}{It looks like the consequences of cannibalism.}
{231}{}{If you say so... I've never thought about it, but there have been such rumors about Jackals for a long time.}
{232}{}{Next time I'll take it as a personal insult. Now step aside.}
{233}{}{Can you explain what it was?}
{234}{}{I hope this misunderstanding is settled. Now let me go into the city.}
{235}{}{Be calm, I'm not one of them.}
{236}{}{Wait. Don't get me wrong, but before you enter the city, show your hands.}
{237}{}{Maybe it's their nature?}
{238}{}{How should I know? I won't even talk to them - I'll put a bullet in their forehead right away, and that's the end of it.}

#Repeat dialog
{240}{}{Welcome to the landfill. Make yourself at home.}
{241}{}{Welcome to Garage City. You'll like it here... if you get used to it a little.}
{242}{}{Don't you want to leave so much?}
{243}{}{This dump is our home. Our sweet cozy home.}
{244}{}{That's a cool thing on your arm. Is it a computer? I've never seen anything like it.}
{245}{}{Wait, who's coming? Oh, it's you...}

{246}{}{Ah, you're still here. Strange, I thought you didn't like it here.}
{247}{}{Listen, the people here are uncooperative, you better not shine on the street once again.}
{248}{}{Are you on business? It would be better this way, otherwise the locals may misunderstand it.}
{249}{}{Listen, get someone else, I can have problems because of you anyway.}

{250}{}{Do you know the guy who asked to join the Rangers?}
{251}{}{Or maybe so. But why would I help the Rangers?}
{252}{}{It won't affect you.}
{253}{}{OK. Eugene Simon is the one you're looking for. His shack near the dorm.}
{254}{}{Thank you.}
{255}{}{It's none of your business. Just step back and don't get in the way.}
{256}{}{Oh no, everything that passes through this gate concerns me.}
{257}{}{I'm sorry for being rude. It's just unusual to talk at gunpoint. So you let people in for the night?}
{258}{}{I just want to spend the night. I won't be here tomorrow.}
{259}{}{For now.}

{260}{}{You mentioned some Jackals. Who is this?}
{261}{}{This tribe of savages lives in the desert, but almost nothing is known about them. All we know is that these are cunning sons of bitches, they lure into traps or attack weak travelers in a crowd.}
{262}{}{I see.}
{263}{}{Why not finish them off with the whole crowd?}
{264}{}{We'd be glad to unsheathe our weapons, but we don't know where these damn jackals are hiding. Do you know their main camp?}
{265}{}{Actually, no.}
{266}{}{I thought so.}
{267}{}{Enough talk about these jackals.}
{268}{}{Actually, yes.}
{269}{}{Really? This changes things! Listen, we have a couple of guys here who have been thinking about a raid on Jackals for a long time. If you show the lair, it will be easier for you to cope together.}
{270}{}{Great, agreed. I'll be waiting for them in the burrows.}
{271}{}{You know, it's too risky. I'll go without partners.}
{272}{}{Have you heard the news about Jackals?}
{273}{}{Yes, I have. And you, it turns out, are not as bad as they thought you were. After all these events, now you will have more friends in Garage City.}
{1273}{}{Yes, I heard. And you, it turns out, are not as bad as they thought you were. After all these events, now you will have more friends in Garage City.}
{274}{}{That's good.}
{275}{}{Getting rid of the Jackal tribe has boosted your reputation in Garage City.}
{276}{}{Yes, I heard. The Rangers are completely crazy. After this, the road to Garage City will be closed to them. Tell them so if you meet them on your way.}
{277}{}{OK.}
{278}{}{Hi. By the way, cool armor.}

#Refugees
{280}{}{They say refugees have arrived to you?}
{281}{}{Yeah. They are holed up in an abandoned hut in a residential area. But I don't think they will stay here for long.}
{282}{}{Why?}
{283}{}{There is no work for them. And not every city will be able to settle down in such a place.}
{284}{}{I see. You say they're in a residential area? I just need to go to them.}
{285}{}{You're right - it's better not to linger in such a hole. I think I should go too.}

#Brahmins
{287}{}{I can go after a brahmin.}
{288}{}{Great. Let's wait for the others...}
{289}{}{[Go to the wasteland]}
{290}{}{They say a Brahmin hunt is planned?}
{291}{}{Yeah. A wild brahmin was seen in the desert, our guys are going to catch him and cut him into pieces. But it's not so easy to finish off such a strong beast. We need people to attack. Do you want to join?}
{292}{}{First explain what kind of animal it is.}
{293}{}{A brahmin is... well... a large two-headed and four-legged beast. Lives in the desert, eats grass. Is that clear?}
{294}{}{I need some time to pack. Don't leave without me.}
{295}{}{I'm not interested in hunting. Shall we talk about something else?}
{296}{}{Great, I'm in. When do we move out?}
{297}{}{When everyone is ready. Check your gear and come back to me.}
{298}{}{OK.}
{299}{}{Oh, no, wait a little longer, I'll be back soon.}

#Questions
{300}{}{It's the first time I've been so far from home. Can you tell us about this settlement?}
{301}{}{Let's talk about Garage City?}
{302}{}{Get some alcohol at a local bar and use it directly on the gatekeeper to get him to talk.}
{303}{}{I'd love to chat, but my throat is dry.}
{304}{}{Wait, I'll get you something to drink.}
{305}{}{More like a scam. You'll find a drink without me.}
{306}{}{What do you want to know?}
{307}{}{Another question.}
{308}{}{Enough talking, I have to go.}

{310}{}{How does this city live? It doesn't look like maize is being grown here.}
{311}{}{Are you kidding? The whole city is obliged to mine on the ruins. Scavengers mine old things there, and then the cartel sells them to caravans.}
{312}{}{Who runs everything here?}
{313}{}{We don't have a mayor or a sheriff. Scavengers are divided into clans, and each has its own leader. But they all obey Mr. Kogan. However, he is only interested in the work of the mine.}
{314}{}{Tell me about Kogan.}
{315}{}{Mr. Kogan runs a cartel of scavengers and does business with merchants. Don't ask me about him anymore. The boss doesn't like to be discussed.}
{316}{}{We don't have a mayor or a sheriff. Scavengers are divided into clans, and each has its own leader. They used to obey Mr. Kogan, but after his death, a serious fight for his chair began in the city.}
{317}{}{Tell me about yourself.}
{318}{}{There's nothing to tell. I came with the others in the hope of making money on the mine. Fortunately, Mr. Kogan gave me a job as a gatekeeper. Now I make sure that no extra people go here, and scare away the animals.}
{319}{}{And what kind of animals are found here?}
{320}{}{Mostly coyotes and small radscorpions. Large rats can be found in the ruins. In general, this place will disappoint any trapper. They say that hunting is flourishing in the mountains in the east. I'm thinking about going there when it gets really bad in the Garage.}
{321}{}{How old are these ruins?}
{322}{}{Much more than you and me. They say the Great War happened 90 years ago. Since then, this place has been rusting and sinking into the sand.}
{323}{}{What was here *before* The Great War?}
{324}{}{Some town called Kingman. But what's the difference? This is ancient history. Nobody cares anymore.}
{325}{}{Simple curiosity. Let's talk about something more important.}
{326}{}{Why do you live among all this junk?}
{327}{}{Do you have any better ideas? The old buildings are already unusable, we had to build new ones out of garbage.}

# About the slave convoy
{330}{}{A slave convoy passed through here. You should know that.}
{331}{}{I don't know what you're talking about. There was no slave convoy here. Talk to the guys at the bar or the cartel boss. Maybe the scavengers know something.}
{332}{}{Please tell me if you know. My relatives were there. Have you ever lost loved ones?}
{333}{}{Okay, I'll talk to them.}
{334}{}{(sighs) I didn't tell you that. The convoy left for the city of Flagstaff. Go east along the 40th Federal Highway. They say it takes a week to get there.}
{335}{}{So Flagstaff. Thank you, amigo, you're a good guy.}
{336}{}{So why the hell didn't you say so right away?! That's right, Jose told me about this hole.}
{337}{}{I'm sorry for you, but I can't help you.}
{338}{}{If you lie to me, you will pay cruelly for it.}
{339}{}{Okay, I'll talk to the other residents.}
{340}{}{And keep in mind that the convoy is well armed and organized. These are not man-eating savages from the wasteland.}
{341}{}{Thanks for the information.}
{342}{}{Bye, it's time for me to hit the road.}

#Weapons
{350}{}{You have a great gun.}
{351}{}{Yeah.}
{352}{}{Uh, let's not talk about it.}
{353}{}{So we talked. Later.}

{354}{}{Where did you get it?}
{355}{}{I bought it from a loser who was doing badly.}
{356}{}{If it was a really good weapon, he wouldn't be a loser. There's clearly something you're not telling me.}
{357}{}{Does it shoot?}
{358}{}{You never dreamed. This gun has saved my life on duty more than once.}
{359}{}{Judging by the dirt on the hull, it has not been fired from it for a very long time.}
{360}{}{Don't you want to sell?}
{361}{}{Hmm... no.}
{362}{}{The pause in the answer gives away that your gun is not that good. It doesn't shoot, right?}

{363}{}{Damn it, how did you guess? (sigh) Your truth, it doesn't shoot. And count the cartridges on your fingers. What's next?}
{1363}{}{Damn it, how did you guess? (sigh) Your truth, it doesn't shoot. And count the cartridges on your fingers. Come on, laugh at the top of your voice.}
{364}{}{Why do you need a non-firing gun?}
{365}{}{To intimidate, stupid! And when it's necessary, I can put a hole in my groin with a muzzle. Is that clear?}
{366}{}{Is there really no one here to fix this gun?}
{367}{}{Our mechanic doesn't have the right parts. It is difficult to find firearms in working condition in these parts. And even if he fixes the gun, there's still nothing to shoot with.}
{368}{}{I can fix it.}
{369}{}{Seriously? That would be very helpful. I'll pay 25 caps if you succeed.}
{370}{}{I can't handle your gun right now. We'll talk about it later.}
{371}{}{Yes, it doesn't fire. And count the cartridges on your fingers. What's next?}
{372}{}{I want to buy this gun.}
{373}{}{Oh, nothing.}
{374}{}{I see. It's clear that it's better for me to leave you.}
{375}{}{Looks like you're in trouble, man. Well, I'll go.}
{376}{}{Let's see...}
{377}{}{I'll be damned, you did it! And it seemed to me that the peasants had never held weapons in their hands. Uh, I mean, I'm grateful to you. Here are 25 caps, as agreed. Eh, I would still like to find more cartridges...}
{378}{}{Enjoy, my business here is over.}
{379}{}{No, I can't fix it.}
{380}{}{I thought so.}
{381}{}{I mean, I can't fix it right now. Maybe later.}
{382}{}{Now I definitely won't even touch your gun.}
{383}{}{For such bottlecaps, I can only carry your barrel to the nearest trash can. Look for someone else.}