{100}{}{Here is a refugee.}
{101}{}{You see one of the new arrivals.}
{102}{}{To feed a refugee, use food on him.}

#The first dialog
{200}{}{ (a piercing wild look stared at you from under dirty curls) What do you want? What do you want? Eh?}
{201}{}{Don't worry so much. I won't hurt you.}
{202}{}{And you're not too trusting of strangers, right?}
{203}{}{What do you want? I haven't eaten for the second day and I'm being kicked out of this city. Give me something to eat or leave me alone.}
{204}{}{Okay, I'll look for something edible in my backpack.}
{205}{}{Feed you? Go to hell, beggar!}
{206}{}{I will feed you with my fist so that it will not seem enough.}
{207}{}{Rub it again - and you'll eat your own hand.}
{208}{}{Stop! Don't touch me!}
{209}{}{Okay, calm down. I just want to ask a question.}
{210}{}{I won't if you answer my questions.}
{211}{}{Leave me alone.}
{212}{}{Well, that's fine.}
{213}{}{So it was your group that went to the Rangers and turned off the path?}

#Repeat dialog
{220}{}{What do you want?}
{221}{}{Bye.}
{222}{}{Thanks for the food. How can I thank you?}
{223}{}{Nothing today. Bye.}
{224}{}{I see.}

{230}{}{What are you doing in this city?}
{231}{}{We're running from trouble. Terrible things are happening in the southeast: power is changing in cities, people are being enslaved, farmers are being driven from their legitimate lands. We hoped to find salvation in the Ranger lands, but they turned out to be no better.}
{232}{}{How did you manage to get across the desert?}
{233}{}{It was an ordeal. It's cold at night, and it was so hot during the day that we fried lizards right on the rocks. The main way was overcome in the evening and early in the morning. Sometimes it seemed that we would not survive. We will definitely not survive the second such way.}
{234}{}{Yes, it's really not easy.}
{235}{}{Tell me again, how did you end up here?}

{240}{}{What made you leave the Ranger lands?}
{241}{}{Rangers? Ha! We were told that they protect law and order. But in fact they are ordinary bandits.}
{242}{}{Why did you decide that?}
{243}{}{How dare you talk about Rangers like that?}
{244}{}{First they took away everything of value from us, and then they told us to get out of their lands.}
{245}{}{But why would they send you away?}
{246}{}{Look at these rags - there is nothing to take from us, we are poor refugees. And we have neither the strength nor the desire to work for them as free slaves. They don't need us. So they drove us away like useless garbage.}
{247}{}{Why did you decide it was the Rangers?}
{248}{}{One of them showed a badge. Besides, the bandits wouldn't chase us away, but would simply rob or kill us.}
{249}{}{A strange story... I need to know the details, and you don't leave town yet.}

{250}{}{I need to find these rangers.}
{251}{}{Find it? What for? Don't push your luck. They'll rob you or kill you.}
{252}{}{I'll deal with them. Just show me this place.}
{253}{}{Really, it's too dangerous. Forget it.}
{254}{}{Uh no, I'm too weak to travel. I would like to refresh myself before the road.}
{255}{}{I'll come back when you're stronger. Later.}
{256}{}{You'll chew your own teeth if you don't show me this place.}
{257}{}{Fair. Here are 20 caps, you can buy food at a local bar with them.}
{258}{}{(greedily watching you rummage through your pockets)}
{259}{}{Uh, I think I left cash at the motel.}
{1259}{}{Uh, I think I left cash at the motel.}