{100}{}{You see a scavenger.}
{101}{}{You see a bandit in a protective welding mask.}

{110}{}{What are you doing here?}
{111}{}{Spying?}
{112}{}{Did Kogan send you?}

{120}{}{Lucas knows what he's doing.}
{121}{}{Lucas and I have been through a lot together.}
{122}{}{I can imagine how angry Trayvon is right now.}
{123}{}{This plant is the last hope for us.}
{124}{}{We were the first to open the plant, so now it's ours.}
{125}{}{Kogan will have to make concessions.}

{130}{}{We are very lucky to have you.}
{131}{}{Thanks for the help.}
{132}{}{You're always welcome here.}
{133}{}{We're in charge here now. Thank you.}
{134}{}{I don't know how it would have ended if it wasn't for you.}