{100}{}{This is Lucas.}
{101}{}{You see Lucas.}
{102}{}{The transaction was successful.}

{110}{}{Watch with both eyes. It is impossible for the bloodhounds of Kogan or Trayvon to interfere with the deal.}
{111}{}{Deal with Kogan's people while I'm busy with the caravan.}
{112}{}{Go back to the factory, we'll talk there.}
{113}{}{You better get out of here. And as soon as possible.}
{114}{}{We'll leave, Kogan won't hear from us anymore.}

{120}{}{Everything seems to be clear.}
{121}{}{Damn, these are Kogan's people. Tell them to get out.}
{122}{}{It's done, go back to the factory and wait for me.}

{200}{}{We have no complaints about you. Just get out of here and you won't get hurt.}
{201}{}{Kogan warns you not to interfere in the transaction.}
{202}{}{Tell the fat bastard his reign is over. Now we are at the helm of this city.}
{203}{}{You made the biggest mistake of your life by going against Kogan. And you will pay for it. Right now!}
{204}{}{Okay, I'll tell him about it.}
{205}{}{Hey, people, get your asses off the ground. We are performing!}
{206}{}{It seems to have started...}
{207}{}{It is not worth going against this person. You will never rise to his position.}
{208}{}{We had no choice. There was no work and the city became cramped for all of us. It looks like now we just have to go and lay low. There is a lot of space in the wastelands for this purpose.}
{209}{}{Sound solution.}
{210}{}{Only a fool would go against Kogan himself.}