{100}{}{This is Lucas.}
{101}{}{You see a seasoned scavenger in a protective welding mask.}
{102}{}{Get out of my factory!}

# The first quest
{150}{}{(you see a seasoned scavenger; he frowns at you, sitting in a free pose) I didn't expect Kogan to send an outsider. Who are you?}
{1150}{}{(you see a seasoned scavenger; he frowns at you, sitting in a free pose) I didn't expect Kogan to send a foreigner. Who are you?}
{151}{}{I have no idea who Kogan is. I'm chasing a slave convoy.}
{152}{}{Hmm. So you're from the village that the colonists captured? I know the story. Kogan tried to get along with the raiders in the hope of future contracts. He told them about the Villa because those guys were following the savages, they didn't even hear about you.}
{153}{}{Kogan demands an explanation.}
{154}{}{He'll get them. But I want to know, why are YOU working for this greedy rich man? What did he promise you for the job?}
{155}{}{In fact, I am persecuting people who took my relatives away against their will. Kogan knows something about it.}
{156}{}{Do you know where the slaves were taken?}
{157}{}{Yes, I know. I'll tell you everything if you do me a favor. You're not going to work for Kogan after all you've heard, are you?}
{158}{}{Just tell me. And you won't get hurt.}
{159}{}{Do you have a brain? Then take care of their safety. Because here you can lose them.}
{160}{}{What should I do?}
{161}{}{Okay, I'll listen to your "demands".}
{162}{}{I need all of Kogan's latest contracts. They should be recorded on the computer in his garage. Just copy it and bring it to me. Then we'll talk.}
{163}{}{Okay, I'll do what you ask. See you soon.}
{164}{}{The hell I'm going to take that risk. You're asking too much.}
{165}{}{Do you want to know about the raiders? Then go and don't come back without information.}
{166}{}{Yes, of course.}
{167}{}{I'll *think* and *maybe* agree.}
{168}{}{I have some questions.}
{169}{}{Hey, I see you! Come out into the light, you son of a bitch. Are you spying for Kogan?}
{170}{}{Well, did you manage to get the contracts?}
{171}{}{Not yet.}
{172}{}{Who says I'm even going to do this?}
{173}{}{You probably don't know, but Kogan is dead.}
{174}{}{So it will be easier for you to get contracts. I still need this data.}
{175}{}{Then I'll go and do it.}
{176}{}{You know, I'm allergic to computers. Therefore, it will be very difficult to complete your task.}
{177}{}{Damn, I didn't think about it. Most likely, Kogan keeps the computer under a password. I don't want to do this, but I'll have to give you the decoder. He will hack the system himself, you just have to wait a little.}
{178}{}{That makes a difference. Then you can try.}
{179}{}{}
{180}{}{Here's the data from the computer you asked for.}
{181}{}{So, let's see... yeah... clear...}
{182}{}{What is clear to you?}
{183}{}{You talk to yourself a lot, don't you?}
{184}{}{Kogan agreed with a neighboring city on the supply of parts from this plant. The caravan is on its way. All we need is to get ahead of him and meet the caravan earlier.}
{185}{}{Why do you need this?}
{186}{}{This plant is an inexhaustible vein! You just need to launch it and find customers. There are not many of them, but they are there.}
{187}{}{Hey, what about our deal?}
{188}{}{You'd better stick with us. We'll talk about it when it's done.}
{189}{}{But I don't want to be a part of it!}
{190}{}{If everything goes smoothly, then you won't have to. Just meet with the caravan, exchange things, and disperse.}
{191}{}{Do as you like. I don't care.}
{192}{}{Great idea. When do we move out?}
{193}{}{First you need to assemble the parts. Walk around the factory and bring what is written in the contract. There should be everything you need here.}
{194}{}{Okay.}
{195}{}{I need to ask you.}
{196}{}{No talking until I get the contracts.}
{197}{}{OK, there will be contracts for you...}
{198}{}{Oh, really!}

# After the first quest
{210}{}{Tell me.}
{211}{}{I think I'll go.}

{220}{}{What is this place?}
{221}{}{Do you really not know what a factory is? And you look like you have dark skin. You probably live in the desert... The factories used to produce machinery and utensils. Now, of course, they do not produce.}
{222}{}{I'm not interested in the factory topic anymore. Can we talk about something else?}
{223}{}{Why?}
{224}{}{You said that the factories are now inactive. Why?}
{225}{}{Nowadays there is nowhere to take so much energy. And if there is a source, then only a few have the necessary skills and knowledge to use it. Since the Great War, people have squandered their achievements...}
{226}{}{And what was produced here?}
{227}{}{This is a factory of Watts Electronics. Parts for electronic equipment and nuclear batteries were manufactured here.}
{228}{}{Where does so much light come from?}
{229}{}{Old lamps. They are powered by electricity, and it is produced by backup generators because the local reactor has been idle since the "big boom". It can still be started. But this requires nuclear fuel. And there is nowhere to take it yet.}
{230}{}{How do you know so much about pre-war production?}
{231}{}{I'm a garbage man, I've been working with old items for many years.}
{232}{}{You know, these pieces of iron do not inspire confidence.}
{233}{}{Robots? They still wouldn't let us get into the factory. Only thanks to the decoder was it possible to hack the system and disable the alarm. Robots are safe now. But they can be used instead of workers.}

{240}{}{Do you know that Kogan is dead?}
{241}{}{Yes, rumors spread quickly in the Garage. To be honest, I'm even a little sorry.}
{242}{}{[Next]}
{243}{}{Kogan was a greedy bastard, but he was a decent entrepreneur. And it was possible to negotiate with him. Without him, the scavengers will tear everything down here.}
{244}{}{It looks like you're having problems here. Let's talk about something more pleasant.}
{245}{}{It seems you've upset your boss a lot.}
{246}{}{Spit. The boss needs new investments in the business, and only I can provide them among all the garbage collectors in the city. He will have to make concessions.}
{247}{}{Your position is clear.}
{248}{}{What about the rest of the scavengers? Have you thought about them?}
{249}{}{Wipe your eyes - Garage City is devastated. There is no place for so many workers here anymore. Let them go to other places.}

{250}{}{Here is the detail mentioned in the contract.}
{251}{}{(attentively studies the subject of ancient technologies) Yes, that's her. Get ready to meet the caravan. We meet near the old water pump. I do not know what can happen there, so take stronger weapons and stronger clothes.}
{252}{}{I can move out right now.}
{253}{}{I need time to pack.}
{254}{}{Relax for now, it will take some time...}
{255}{}{[Go with the scavengers]}
{256}{}{No, wait, I need some time.}
{257}{}{Okay. Meet me at the water pump.}

{260}{}{The transaction was successful! Without your help, it would have been much more difficult for us, and we are now in debt to you. Here, take 200 caps. This is your share of the deal.}
{261}{}{What are you going to do now?}
{262}{}{I will restore the plant. We were promised to bring fuel for the reactor, then we would be able to start the machines and start producing new parts.}
{263}{}{Good luck then. And my business here is finished.}
{264}{}{Well, well, I'll look at your efforts in the future. Goodbye, dreamer-scavenger.}
{265}{}{The transaction was successful! It would have been a little harder for us without your help. But we consulted and decided that you don't deserve your share.}
{266}{}{caps are good. What are you going to do now?}
{267}{}{Your weapon would be more useful to me than these bottlecaps.}
{268}{}{Of course, take it. This is a laser emitter. I put it together from local parts. And I'll probably collect more.}

{270}{}{You promised to tell me about the raiders.}
{271}{}{Yes, it's not an easy story. You see, they were actually mercenaries gathered from all the nearby settlements. And they were led by some dudes from Flagstaff. This is a city in the east, a week away from here.}
{272}{}{Why do they need peasants?}
{273}{}{At first they were looking for a den of Jackals to force them to work in some mines. But then Kogan sensed a profit and suggested an attack on the Villa. He knows where to put the caps. Because Flagstaff promises to be a good client for the cartel.}
{274}{}{So you're all tied up here, right?}
{275}{}{You understand, such a deal provided Garage City with good welding. And our meeting with the caravan was part of this process. You may not like it, but we scavengers need to survive on our own.}
{276}{}{I forgive you. And now I have to go to this one... Flagstaff.}
{277}{}{Don't think we'll ever forget this story. The peasants of the Villa have a long memory.}

{280}{}{Hi, Lucas. About production. My community fears that it will have a bad effect on the Villa.}
{281}{}{Nonsense. New workers will come here, and the city's turnover will increase. It's better for you because you will be able to trade crops and ceramics with big cities.}
{282}{}{Perhaps. However, our elders want isolation.}
{283}{}{Old people don't want change? So let them change! The world is changing, they will have to too.}
{284}{}{I'll think about it.}
{285}{}{Perhaps, after all my wanderings, I will agree with you. But how can I dissuade the old people? They need guarantees of immunity.}
{286}{}{Ha, what kind of world do you live in there? There are no guarantees, there are only agreements. But you know what - we *can* agree.}
{287}{}{Really?}
{288}{}{There are many unemployed people left in the city. My factory will not provide all of them with work in the near future. We could provide your Villa with various services at a very low price. You will rebuild the village, strengthen your lands, and we will earn some money. And more importantly, we will avoid neighborhood conflicts.}
{289}{}{I will pass on your proposal to the community. Perhaps they will agree.}
{290}{}{I'm afraid the elders won't like it. Bye.}