{100}{}{Here is a scavenger.}
{101}{}{You see a guy red with tension.}

{110}{}{Don't you dare blab}
{111}{}{Please don't hit me! I will improve, honestly!}

{200}{}{Which... Who are you anyway? What do you need?}
{201}{}{I'm just watching you guys having all the fun.}
{202}{}{Yeah. Any problems?}
{203}{}{Hey, what are you doing?}
{204}{}{We're dancing here. On the mattress. Got it?}
{205}{}{I want to join.}
{206}{}{You're not right in the head. Get lost, you idiot!}
{1206}{}{You're not right in the head. And we have nothing to do with women who are knocked out. Get lost!}
{207}{}{Chill out, man, I'm already leaving...}
{208}{}{I won't let you go on.}
{209}{}{Uh-oh, we have the very Nobility here.  And what will you do? Well, tell me, BITCH?}
{210}{}{I'll just leave and not bother you. Have fun, guys.}
{211}{}{I'll kill you. Die, you creatures!}
{212}{}{I'll take out my gun and wait exactly three seconds. One... two...}
{213}{}{}
{214}{}{Okay, okay! Calm down, man! Keep the gun to yourself. We are not such animals, eh, we can calmly solve everything.}
{1214}{}{Okay, okay! Calm down, dude! Keep the gun to yourself. We are not such animals, eh, we can calmly solve everything.}
{215}{}{Get out of here.}
{216}{}{The doors are open.}
{217}{}{You're disturbing my sleep.}
{218}{}{Hey, we paid for the room and we can do whatever we want. Do you understand?}
{219}{}{If you don't stop, you will have problems with the whole city.}
{220}{}{We know who you are, you lousy digger. No one invited you to our city. So you can't intimidate us.}
{221}{}{Okay. But you'll remember me again.}
{222}{}{Know your place, punk. If you don't calm down, you will have problems.}
{223}{}{Uh, okay... We don't need any problems. We'll leave as if we weren't there...}