{100}{}{There is a girl in front of you.}
{101}{}{You see a half-naked girl.}

{110}{}{I didn't mean to! They undressed me themselves!}

{200}{}{(sits down contritely on the bed and slowly straightens his rags) With... thank you...}
{201}{}{How did you get involved in this?}
{202}{}{I don't know... I didn't think this would end...}
{203}{}{You're just a fool. That's it.}
{204}{}{From now on you will be smarter.}
{205}{}{Animal! Why was it necessary to kill them? They weren't as violent as you! Do you understand that now everyone will avoid me?}
{206}{}{Is this case not enough for you?}
{207}{}{And how else can I make money in this dying city? I can't even leave here... I wish you weren't here... It would be better if this city did not exist at all! Wa-a-a...}
{208}{}{Um, you should calm down. Goodbye...}
{209}{}{Come to your senses, you fool. I did what I had to do.}
{1209}{}{Come to your senses, you fool. I did what I had to do.}
{210}{}{I didn't want that. But how else can I make money in this dying city? I can't even leave here... It would be better if this whole city didn't exist! Wa-a-a...}
{211}{}{Hmm... Hmm... Oh, it's you... Hi there.}
{212}{}{Hmm... Hmm... Oh, it's you... Go away, I don't want to see you.}
{213}{}{Bye.}