{100}{}{Here is the administrator.}
{101}{}{You see a bald, short man in badly worn clothes.}
{102}{}{You have had a good rest and gained strength.}

#Reaction to armor
{160}{}{Nice suit you have. Even too much. Are you selling?}
{161}{}{It's not for sale. It's a family heirloom.}
{162}{}{(purses his lip significantly) Hmm. Attachment to old things is probably in your blood.}
{163}{}{And no one asked you.}
{164}{}{I don't know, these things are just inherited. And that's it.}
{165}{}{(looks at the star on your new armor with disdain) So you're a Ranger? And what the hell are you doing here? Are you going to read morals and impose the orders of your *gang*? Anyway, we don't need it. We're on our own here, we'll figure it out without you.}
{166}{}{Hold your tongue, you fool. Someday this city will kneel before the Law.}
{167}{}{I don't know what you're talking about. This armor was just lying around in the desert.}
{168}{}{Hey, aren't you one of those sectarians from the south? I've heard that they wear such ridiculous robes and worship a nuclear bomb. If so, then I don't even want to hear anything about your faith.}
{169}{}{May the Holy Fire enlighten you, fool.}
{170}{}{So that I can be enrolled in some sect? Well, no!}
{171}{}{T-you... y-you are this... You're not going to sleep in that tin can, are you? And why do you need a motel with such and such equipment?}
{172}{}{First get yourself a power armor to tell me what to do.}
{173}{}{Don't worry, I won't hurt you.}
{174}{}{Hmm. I would never have thought of making armor out of road signs.}
{175}{}{You will mock my armor - you will not be well. Got it?}
{176}{}{Me too. It's just a trophy.}

#Stop dialog
{180}{}{I know there was a fight at the bar because of you. Are you going to create problems here too?}
{181}{}{No, no, it was an accident. Just a local drunk fell on my shoe. In ordinary life, I'm quieter than a corncob!}
{182}{}{I'll "believe" you. But if you order a room, you will pay double the price.}
{183}{}{I don't care about your fucking number.}
{184}{}{But this is a motel. If you're not going to book a room, then why are you here?}
{185}{}{I ask myself the same question. I think I should go.}
{186}{}{I needed someone to talk to.}
{187}{}{Thank you for not kicking me out on the street.}
{188}{}{I'll do without a number. I'm leaving.}
{189}{}{What the hell do you want? Sit in your chair quietly and don't dig.}
{190}{}{Okay. Whatever you say. But if you order a room, you will pay double the price.}
{191}{}{You're taking too much on yourself, bitch!}
{192}{}{And you're not in the right city to set conditions, baby. Go and get some fresh air.}
{193}{}{Fuck you!}
{194}{}{The others in this city have a better opinion of me.}
{195}{}{Okay, sorry. I don't want any more trouble, you understand?}
{196}{}{Of course.}
{197}{}{Ask your fellow countrymen about me. Surely they will say something good.}
{198}{}{I doubt it very much.}
{199}{}{Let's not fight. I'm here for peaceful purposes.}

#The first dialog
{200}{}{(in front of you is a balding man in a worn jacket; he looks at you incredulously through the gloom of a stuffy barrack)}
{201}{}{Hi there.}
{202}{}{Hey, hey! These guys were just hooligans. I didn't want problems and turned a blind eye to their tricks. What else could I do? I am also a victim of circumstances. But killing guys... Let me say I didn't see anything, and you just leave, okay?}
{203}{}{Don't worry, I won't inconvenience you anymore.}
{204}{}{Stay quiet and keep your head down. Don't think you'll get rid of me so easily.}

#Repeat dialog
{210}{}{How can I help?}
{211}{}{Goodbye.}

{219}{}{Forget it, I don't have so many caps right now.}
{220}{}{I'm looking for a slave convoy that passed by the city. Do you know anything about it?}
{221}{}{Perhaps. But sometimes there are gaps in my memory. And only the ringing of a hundred caps can fix it.}
{222}{}{Yes, this is robbery! I'll ask someone else.}
{223}{}{Speak, you beast! My patience is running out!}
{224}{}{That's not very kind of you. Every scavenger in this town knows me, and you're just a stranger from the wasteland. So get out of the motel before I call for help.}
{225}{}{Let it be your way, here are a hundred caps. Now tell me everything you know.}
{226}{}{Okay, I'll leave peacefully.}
{227}{}{Here are the bottlecaps. Now tell me everything you know.}
{228}{}{I know that you have to be careful with these guys. Why do you ask?}
{229}{}{I'm chasing this convoy. Do you know where he went?}

{230}{}{(scrapes the bottlecaps under the table in amazement) I didn't think you were serious... yes, these guys have raised a fuss in our quiet town. It's been a long time since it's been so lively here. But the whole city got an excellent welding from them.}
{231}{}{What are you talking about? What kind of welding?}
{232}{}{Yes, almost any institution in the city got something of its own. In my motel, for example, there is not a single empty seat left. Almost all the drinks were drunk at the bar. And Mr. Kogan was counting on some contracts. The city lived for a whole week at the expense of all this mess with slaves.}
{233}{}{Who are these slaveholders?}
{234}{}{The squad was assembled from various mercenaries, but I do not know who the customer was. Obviously, he didn't want to drag himself so far.}
{235}{}{So where did the squad go?}
{236}{}{A town called Flagstaff. Follow Route 40 east. They say the journey takes about a week.}
{237}{}{Damn...}
{238}{}{And what did you say about welding there?}
{239}{}{I think it's time for me to hit the road.}

#Room
{250}{}{It seems that you rent rooms for the night?}
{251}{}{Does the word "motel" mean anything to you? Yes. I rent rooms.}
{252}{}{Tell me about the numbers.}
{253}{}{A room for one person. Moderately *reliable* lock. The bed and furniture are attached, but I do not accept claims to cleanliness. At night, the lighting turns on in the corridor. The most important advantage is protection. No bandit will get through here so easily. So, you can sleep peacefully.}
{254}{}{Is this business really in demand?}
{255}{}{Previously, the city actively traded with southern cities, crowds of seekers and caravanners flocked here. Recently, there have been few visitors. (sigh) Barely making ends meet.}
{256}{}{How long have you been running this motel?}
{257}{}{I came here a few years ago, like many others, hoping to earn some caps. Then the city needed a motel, and I thought that this could get more than a dirty and unsafe mine.}
{258}{}{It's weird that you call it a motel.}
{259}{}{I don't know. So it happened. The Old Town is full of garages and auto repair shops. And caravanners use these hefty trailers from pickups.}
{260}{}{Okay, that was a ridiculous question.}
{261}{}{Tempting. I'll think about this proposal.}
{262}{}{Enough of the story. Let's return to the more relevant issues.}
{263}{}{Whatever you call it, but now I would like to change the subject.}
{264}{}{Wow, you can give a lot for a quiet, peaceful sleep. How much does one night cost? }
{265}{}{Oh, you should know about the wonderful adobe houses in my village... And how much does a night in this bedbug cost?}
{266}{}{For you, it will cost in }
{267}{}{ caps.}
{268}{}{I want to rent a room.}
{269}{}{Here are the bottlecaps.}
{270}{}{I will think about this proposal.}
{271}{}{It's too expensive. I'm going to sleep under the open sky.}

{280}{}{Hey, someone is being raped in the next room!}
{281}{}{It's none of your business. If you don't want problems, then pass by and keep quiet.}
{282}{}{And you're not going to do anything?}
{283}{}{So you're with them for one thing, or what?}
{284}{}{The girl herself has sunk to such a life. If she didn't want to, she wouldn't have gotten involved with these guys. Don't feel sorry for her. And nothing terrible is happening. The guys will play and let them go... I'm telling you - it's none of your business!}
{285}{}{Damn, I can't just leave it like that.}
{286}{}{Ah, well, then I really should pass by.}