{100}{}{You see a mechanic.}
{101}{}{You see a simple hard worker. He is hard at work repairing old junk.}
{102}{}{Now there will be more useful things and bottlecaps in the mechanic's product.}
{103}{}{Now there will be even more useful things and bottlecaps in the mechanic's product.}
{104}{}{No creo en mis ojos! Is this really power armor?!}

{200}{}{Oh! Salute, compañero! First time in the city?}
{201}{}{Is this a city?}
{202}{}{And why not, señor? There is everything that the city should have - a bar, a hotel, housing, work. Live a little, you'll see for yourself.}
{1202}{}{And why not, señorita? There is everything that the city should have - a bar, a hotel, housing, and work. Live a little, you'll see for yourself.}
{203}{}{Uh, I'll think about it. And who are you?}
{204}{}{My name is Pedro Fuerte... or just Pete.}
{205}{}{I'll call you Pete.}
{206}{}{As it will be more convenient, señor. As it will be more convenient.}
{1206}{}{As it will be more convenient, señora. As it will be more convenient.}
{207}{}{Nice to meet you, Pedro.}
{208}{}{(smiles) And to me, amigo, the garage doors are always open to good people. How can I help?}
{209}{}{I think I'll come back later.}

{210}{}{Salute!}
{211}{}{Adios.}
{212}{}{Will you answer a couple of questions?}
{213}{}{Enough talking. Now I want to look around.}
{214}{}{Tell me more.}
{215}{}{Do you call this handful of dirty shacks a city?}

#Questions
{220}{}{Si, señor?}
{1220}{}{Si, señora?}
{221}{}{What is this place?}
{222}{}{This is Mr. Kogan's own garage-the main office of the scavenger cartel. Here we recycle garbage from the ruins. Useful things go with caravans, and the rest - as it turns out. Do you need parts or wires? I can exchange it.}
{223}{}{Tell me about your work.}
{224}{}{I'm a mechanic, sir. I recycle what the scavengers bring. I fix it, if necessary, and prepare it for shipment.}
{1224}{}{I'm a mechanic, señora. I recycle what the scavengers bring. I fix it, if necessary, and prepare it for shipment.}
{225}{}{How does the boss feel about you?}
{226}{}{He appreciates my work! I am his main assistant in working with scavengers.}
{227}{}{Sounds more like he's pushing you around.}
{228}{}{Oh, no... Although I also think I should get a fee for a couple of caps more.}
{229}{}{He's just playing you... Okay, never mind.}
{230}{}{No, no, Mr. Kogan - he's the boss, there's no way without him.}
{231}{}{The question wasn't about that, but it doesn't matter.}
{232}{}{Where does the garbage go?}
{233}{}{From where the caravan will come, we agree with those. Nowadays, everyone needs spare parts.}
{234}{}{Who are the scavengers?}
{235}{}{scavengers. They extract useful resources from local ruins - what remains of the Old World. Then they carry these resources for processing and receive caps for it. The scavengers are divided into clans, and they all work under contract with the cartel.}
{236}{}{Can someone trade on the side?}
{237}{}{Oh, Mr. Kogan doesn't like that. And if not him, then the rest of the scavengers will not forgive. Such people don't stay here for long.}
{238}{}{Scavengers do not forgive this, no way. Within the clan, all the extracted resource is given to the leader, and the income is divided among all. If someone breaks the rules, then he doesn't stay here for long.}

{240}{}{Your boss is dead. What are you going to do now?}
{241}{}{This is bad, señor. The boss humiliated me and paid half a penny for hard work, but without him... without him, the whole Garage City would become a dump!}
{1241}{}{This is bad, señora. The boss humiliated me and paid half a penny for hard work, but without him... without him, the whole Garage City would become a dump!}
{242}{}{Are you sure?}
{243}{}{Only he knew how to run a business. And now there will be a war for the mine among the scavengers. I don't know what to do... Maybe it's time to leave these places. But where will I go?}
{244}{}{Looks like you don't have a choice. Let's talk about something more pleasant.}

#About the product
{250}{}{What do you sell?}
{251}{}{What the scavengers found, and by what I fixed.}
{252}{}{What the scavengers found, and by what I fixed. Only Mr. Kogan keeps the best goods for the most important merchants. So I can offer far from everything.}
{253}{}{Uh, no, the boss knows what he's talking about.}
{254}{}{You know, you don't have to always be so executive.}
{255}{}{Great. So what do you say you're selling?}
{256}{}{Just look at this junk. You'll be selling it forever! And I can buy it right now.}
{257}{}{Your truth, señor. (reveals some part of the product)}
{1257}{}{Your truth, señora. (reveals some part of the product)}
{258}{}{If you refuse me a good product, you will miss a valuable customer.}
{259}{}{Your truth, señor. (reveals all his goods)}
{1259}{}{Your truth, señora. (reveals all his goods)}
{260}{}{Mr. Kogan has been dead for a long time. Can I count on full service now?}
{261}{}{Si, señor. (reveals all his goods)}
{1261}{}{Si, señora. (reveals all his goods)}
{262}{}{Mr. Kogan recognized my right to a good product. Open everything you have.}
{263}{}{Si, señor. (reveals all his goods)}
{1263}{}{Si, señora. (reveals all his goods)}
{264}{}{What kind of device is this?}
{265}{}{Geiger counter? (takes the device and holds it over your body) Oh, señor, yes, you should buy this thing! The meter shows the radiation level, many scavengers would like to get it. But it's too expensive for them.}
{1265}{}{Geiger counter? (takes the device and holds it over your body) Oh, señora, yes, you should buy this thing! The meter shows the radiation level, many scavengers would like to get it. But it's too expensive for them.}
{266}{}{I'll think about it.}
{267}{}{I need the parts to fix the radio station.}
{268}{}{Seriously? You must have big plans. Few people use their radio stations nowadays. Rangers, for example. Did they send you?}
{269}{}{I don't know what you're talking about. So do you have an amplifier? Or should I go to another city?}
{270}{}{Hey, take your time, amigo! Yes, there are a couple of modules, maybe they will fit, or maybe not.}
{271}{}{Then let's take a look at this thing.}

{276}{}{In Todd's trailer there was a machine for the production of bottlecaps. Now the machine is destroyed.}
{277}{}{Good job, amigo. Here are the bottlecaps, as I promised. The main thing is not to spread about this situation. I don't want anyone to be lynched because of me.}
{278}{}{Bye, Pete.}
{279}{}{I'll pay with REAL caps.}

{280}{}{What are these, bottle caps?}
{281}{}{Well, yes, we used them as money before the Great War. Don't you know about it?}
{282}{}{It looks a bit... strange.}
{283}{}{Everyone is already used to it. And it's just convenient. Just be careful, someone started minting their own caps. This is bad because if there are too many caps, they will become worthless. And the richest person will be the one who makes them.}
{284}{}{Yes, it's a little unfair.}
{285}{}{We've been trying to track down this Pendejo for a long time. If you find out who is minting fake caps, tell me.}
{286}{}{Required.}
{287}{}{Okay.}
{288}{}{About the fake caps.}
{289}{}{Yes? Any leads?}
{290}{}{No, not yet.}
{291}{}{It looks like it's Todd. He paid me with brand-new caps.}
{292}{}{He himself could have been a victim of deception. Let's not blame him ahead of time. But it doesn't hurt to check.}
{293}{}{What do you suggest?}
{294}{}{What do you think, amigo? Trailer... tools... boom! Someone has to do it, you know? I would appeal to other residents, but I'm afraid Todd will be lynched. And I don't want to hurt anyone.}
{295}{}{I understand now. Get into the trailer and look for tools for the production of bottlecaps there. And if they are there, then they need to be destroyed.}
{296}{}{So will you do it?}
{297}{}{Okay. But breaking into someone else's home is a serious offense. What will I do for such a big risk?}
{298}{}{OK. I'll do it.}
{299}{}{No, look for fools.}

#Repair services
{300}{}{What services does the garage provide?}
{301}{}{We repair everything that needs to be repaired - weapons, armor, your favorite lawn mower. The only question is how many caps can you pay.}
{302}{}{Do they repair cars or something like that here?}
{303}{}{Oh, if only! Basically, I disassemble old equipment into useful parts. Fixing something self-propelled is my dream.}
{304}{}{Take a look at my bike.}
{305}{}{In that case, take a look at my bike.}
{306}{}{I see. Then what are you repairing?}
{307}{}{A real bike in working condition?! I swear by all the gears, I'll be happy to dig into this iron!}
{308}{}{No, I don't think you should be allowed near him.}
{309}{}{It's high time for this bike to update its tires.}
{310}{}{Oh, finding good tires nowadays is a great success. But I have what I need. That's why it's a garage!}
{311}{}{I need a bigger container on a motorcycle.}
{312}{}{Let me see. Hmm, I can make a new box, there's plenty of iron around and I have welding.}
{313}{}{Conduct a technical inspection of the motor system.}
{314}{}{Yes, there is something to work on here! This bike hasn't been cleaned for a hundred years. In addition, I can find a replacement for worn-out engine parts. So you can reduce energy consumption somewhere by 50%.}
{315}{}{How much will you charge for the job?}
{316}{}{ caps. And no barter!}
{317}{}{Okay, here are the bottlecaps.}
{318}{}{I'll think about it, but in the meantime, watch something else.}
{319}{}{It's too expensive, I can't afford it.}

{320}{}{(shakes his head) That's not enough.}
{321}{}{Oh, really...}
{322}{}{Changing tires will increase the speed of your bike by about 15%.}
{323}{}{Your motorcycle has a trunk with a capacity of 100 units.}
{324}{}{Mechanic Pete did a great job - now the motorcycle will consume 50% less energy.}
{325}{}{Done!}
{326}{}{Great. Let's see what else you can do.}
{327}{}{Thank you. I'm going to check how it works now.}