{100}{}{You see Mr. Kogan's computer.}
{101}{}{You see an ancient computer, skillfully restored by garage mechanics.}
{102}{}{The machine is destroyed!}
{103}{}{[test: there is damage]}

#Dialog
{200}{}{Enter command.}
{201}{}{End session.}
{202}{}{Back.}

{210}{}{View the cartel's reports for the entire period.}
{211}{}{(Since 2160, scavengers have been actively extracting resources from the ruins of Kingman. For the first six years, the mine yielded huge profits, but after the production and trading schedule began to steadily slide down.)}
{212}{}{Contracts with Flagstaff.}
{213}{}{(Mr. Kogan has signed several contracts with the Flagstaff Colony to exchange scrap metal and repair services for food, medicine, and nuclear fuel. He also expects new contracts, even more significant.)}
{214}{}{Deployment Support contract.}
{215}{}{(Mr. Kogan actively assisted the raiding party before and after the enslavement of the Villa. According to the contract, he provided sleeping places, clean water, and equipment repair services. And although the profit was low, the prospects that opened up justified these investments.)}
{216}{}{Next.}
{217}{}{(Among the materials you found out that the raiders are a group of mercenaries from a colony called Flagstaff. Apparently, the enslaved population of the Villa was also taken there.)}

{220}{}{Copy the contracts for Lucas.}
{221}{}{The data has been copied successfully.}
{222}{}{Great.}