{102}{}{Intruder alert!}

{200}{}{Dios mio, who are you?}
{201}{}{The one who brings death to tyrants like you.}
{202}{}{I was thinking about joining your unit.}
{203}{}{What the hell are they talking about? Capture the spy!}
{204}{}{Fine...}
{205}{}{You're making a big mistake, general.}
{206}{}{A civilian. I want to join your army, general!}
{207}{}{Rather commendable. But with the way you got in, there is no military service waiting for you. The Commissar will escort you to the exit. You come back - there will be dire consequences. Understood? Now get out. Don't say a word. There isn't anything you could have done to change this.}
{1207}{}{Rather commendable. But with the way you got in, there is no military service waiting for you. The Commissar will escort you to the exit. You come back - there will be dire consequences. Understood? I won't make an exception for ladies. Now get out. Don't say a word. There isn't anything you could have done to change this.}
{208}{}{As you wish, general.}
{209}{}{I'm not going anywhere.}

{210}{}{I warned you. Bring him to the detention room! Let him suffer with the other prisoners of war.}
{1210}{}{I warned you. Bring her to the detention room! Let her suffer with the other prisoners of war.}
{211}{}{No, no, you can't do this to me! I'm claustrophic...}
{212}{}{No one is bringing me anywhere.}