{102}{}{The intruder! Alarm!}

{200}{}{Dios mio, who are you?}
{201}{}{I am death to tyrants like you.}
{202}{}{I was thinking about joining your squad.}
{203}{}{What are you talking about? Capture the spy!}
{204}{}{Well, okay...}
{205}{}{You're making a mistake, General.}
{206}{}{Civilian. I want to join your army, General!}
{207}{}{Very commendable. But considering how you got into the fort, you won't get any service. The commissioner will escort you to the exit. If you come back, it's worse for you. Is that clear? Now get out.}
{1207}{}{Very commendable. But considering how you got into the fort, you won't get any service. The commissioner will escort you to the exit. If you come back, it's worse for you. And I will not look at the fact that you are a woman. Understand?}
{208}{}{As you say, General.}
{209}{}{I'm not going anywhere.}

{210}{}{I warned you. Put him in the brig! Let him suffer with the rest of the prisoners of war.}
{1210}{}{I warned you. Put her in the brig! Let him suffer with the rest of the prisoners of war.}
{211}{}{No, no, you can't go to the punishment cell, I have claustrophobia...}
{212}{}{No one will drag me there.}