{100}{}{You see the sentry.}
{101}{}{Here is a private in a typical army armor with a recognizable symbol. He makes sure that outsiders do not enter the garrison.}
{102}{}{Un intruso!}

{110}{}{*Yawn*}
{111}{}{Estoy aburrido...}
{112}{}{Viene alguien?}
{113}{}{Donde esta el cambio de guardia?}
{114}{}{Hoy es un dia caluroso.}
{115}{}{Tengo que informar sobre esto.}
{116}{}{Malditos insectos.}
{117}{}{Necesito zapatos nuevo.}
{118}{}{}
{119}{}{}

{120}{}{*Yawn*}
{121}{}{Boring...}
{122}{}{Is someone coming?}
{123}{}{Where is the shift guard?}
{124}{}{It's a hot day today.}
{125}{}{This will have to be reported.}
{126}{}{Damn insects...}
{127}{}{I need new shoes.}
{128}{}{}
{129}{}{}

{200}{}{Shalto ahi! No te muevas.}
{201}{}{What?}
{202}{}{Eres un gringo, No? Hablas espanol?}
{203}{}{Mine speak the language of the fists. Look and be surprised, native...}
{204}{}{Unfortunately, I don't speak Spanish.}
{205}{}{American - road - stop. Do you understand? Go back. Quickly.}
{206}{}{Are you sending me away? But why?}
{207}{}{How dare you tell me where to go? Get out of the way yourself!}
{208}{}{Civilian - entry is prohibited. You go - or I shoot. Go away! Go!}
{209}{}{You have a serious attitude. OK, I'll leave.}
{210}{}{Fuck you!}
{211}{}{Hablo un poco de espaœol.}
{212}{}{Are you threatening me?}

{220}{}{The intruder! Alarm!}
{221}{}{Shel intruso! Shalerta!}
{222}{}{You shouldn't have done that...}
{223}{}{Hey, you just misunderstood me...}

{230}{}{Me alegro de escucharlo. Hm. De donde vienes?}
{231}{}{[switching to Spanish] I'm from a small village far to the north. I had to travel a long way in search of my relatives.}
{232}{}{Have you crossed the Sonoran desert? It's hard to believe. But in any case, turn around and go back.}
{1232}{}{Have you crossed the Sonoran desert? It's hard to believe. But in any case, turn around and go back.}
{233}{}{Why are you sending me away?}
{234}{}{In front of you is the fort of the united Mexican Army. Civilians are not allowed here. I have orders to shoot anyone who violates the garrison border without permission.}
{235}{}{I understand. OK, I'll leave.}
{236}{}{Can I join your ranks?}
{237}{}{For a gringo from the north to become one of us? This is ridiculous. Just get out of here. Believe me, you have nothing to do here.}
{238}{}{Oh...}
{239}{}{The hell with two. I'm not going anywhere.}

{240}{}{Don't you understand the first time? If you go into the garrison, you'll get a bullet in the forehead. Got it?}
{241}{}{OK, OK, I'll leave...}
{242}{}{If you do that again, I can't vouch for myself.}
{243}{}{You're not otra vez? (raises his weapon threateningly) Shvete! Savoy a dispararte!}
{244}{}{You know, one of you took away a radio transmitter from the Dominguez family.}
{245}{}{Seriously? I didn't know that. It's a pity they were treated like that.}
{246}{}{Can you return the radio?}
{247}{}{To be honest, I don't believe you care about the fate of these farmers. You're probably being tricky.}
{248}{}{I understand them well. I have also experienced injustice from people with guns.}
{249}{}{I'm just trying to help.}
{250}{}{Forget it, it's really not worth it.}
{251}{}{[Threatening with a weapon] Radio or life?}
{252}{}{Gringos cannot be trusted.}
{253}{}{Beautiful speech. I almost shed tears. Okay, I'll talk to the commander...}
{254}{}{I'll wait...}
{255}{}{We found a radio in the barracks. Give it to Dominguez's family. We don't want to get a bad name about us.}
{256}{}{Smart guys. And it was also possible to behave like this from the very beginning.}
{257}{}{Gracias.}
{258}{}{And if I give you this bottle of invigorating?}
{259}{}{Okay, I'll talk to the commander...}
{260}{}{Return it.}
{261}{}{Please return it. It's terribly unfair.}