{100}{}{You see a patrolman.}
{101}{}{You see a private in typical military armor with a recognizable symbol. He's making sure that no outsiders enter the base.}
{102}{}{¡El intruso!}

{110}{}{*Yawn*}
{111}{}{Estoy aburrido...}
{112}{}{¿Alguien viene?}
{113}{}{¿Dƒnde estž el cambio de guardia?}
{114}{}{Hoy es un dša caluroso.}
{115}{}{Tengo que informar sobre esto.}
{116}{}{Malditos insectos.}
{117}{}{Necesito zapatos nuevo.}
{118}{}{}
{119}{}{}

{120}{}{*Yawn*}
{121}{}{Boring...}
{122}{}{Someone near?}
{123}{}{Where's the next shift?}
{124}{}{Hot day today.}
{125}{}{This will need to be reported.}
{126}{}{Damn insects...}
{127}{}{I need new shoes.}
{128}{}{}
{129}{}{}

{200}{}{¡Alto ahš! No te muevas.}
{201}{}{What?}
{202}{}{Eres un gringo, ¿No? ¿Hablas espaœol?}
{203}{}{I speak language of the kulaks. Gaze in awe, native...}
{204}{}{Unfortunately, I don't speak spanish.}
{205}{}{American - road - end. Understand? Go back. Fast.}
{206}{}{You want me to leave? Why?}
{207}{}{How dare you tell me to leave? Go back yourself!}
{208}{}{Civilian - entry forbidden. You leave - or I kill you. Go! Go!}
{209}{}{Serious attitude. Okay. I'm leaving.}
{210}{}{Fuck you!}
{211}{}{Hablo un poco de espaœol.}
{212}{}{Are you threatening me?}

{220}{}{Intruder! Alert!}
{221}{}{¡El intruso! ¡Alerta!}
{222}{}{Shouldn't have done that...}
{223}{}{Hey, this is all a big misunderstanding...}

{230}{}{Me alegro de escucharlo. Hm. ¿De dƒnde vienes?}
{231}{}{[in spanish] I'm from a small village to the far north. I have traveled a long way in search of my relatives.}
{232}{}{You crossed the Sonora desert? I find that hard to believe. In any case, turn around and head back.}
{1232}{}{You crossed the Sonora desert? I find that hard to believe. In any case, turn around and head back.}
{233}{}{Why?}
{234}{}{This fort belongs to the United Mexican Army. Civilian entry is forbidden. My orders are to kill anyone who tries to enter without permission.}
{235}{}{I understand. Alright, I'm leaving.}
{236}{}{Could I join you?}
{237}{}{A northern gringo becoming one of us? No. Just get out.}
{238}{}{Ouch...}
{239}{}{To hell with that. I'm not leaving.}

{240}{}{Don't understand? Don't leave - you get a bullet in your head. Got it?}
{241}{}{Okay, okay, I'm leaving...}
{242}{}{You do that again - I can't vouch for myself.}
{243}{}{¿Eres TŸ otra vez? (raises weapon threateningly) ¡Vete! ¡Voy a dispararte!}