{100}{}{Here is a prisoner of war.}
{101}{}{You see a man with traces of beatings.}
{102}{}{Jack is in front of you.}
{103}{}{And this is your house? A little old-fashioned, but peaceful. I like it here.}
{104}{}{And you've done well! I have seen so many plants only in Casa Nueva.}
{105}{}{Just don't tell me we have to climb into some hole again.}
{106}{}{Phoenix... Although I grew up here, and somehow I don't want to go back.}

{200}{}{Who are you? What do you need?}
{201}{}{It doesn't matter. Just sit there and be quiet.}
{202}{}{Don't make any noise, I'm not here quite "legally". Why are they keeping you locked up?}
{203}{}{Is this some kind of trick to loosen my tongue? I've already told you everything during the interrogation! I was hired by merchants to explore these lands. They hoped for the opening of new caravan routes. That's all. Leave me alone!}
{204}{}{Sounds unconvincing.}
{205}{}{And what else do you expect in these barren lands? In the north, no one has any idea that a whole military fort is located here.}
{206}{}{I believe you. Do you want to run away from here? I could use a partner.}
{207}{}{Well, well. In your position, there are not many lies. Stay here and don't make too much noise.}
{208}{}{I don't know if I can trust you, but there's nothing to lose. If I stay here, they'll hang me anyway. Although without weapons and armor, I will be of little use. Do you know where they have a warehouse?}
{209}{}{We'll figure it out along the way. Come on.}

{210}{}{I've already told you everything. Leave me alone!}
{211}{}{Your words sound unconvincing.}
{212}{}{It's okay, we're in this together. Do you want to run away from here?}
{213}{}{Sit here and don't make too much noise.}
{214}{}{It's too early to go out. Wait for my signal.}

{220}{}{Hey, where are we going?}
{221}{}{Don't make any noise. You'll find out soon.}
{222}{}{They've already arrived. You'll have to wait for me here.}
{223}{}{I already thought you weren't coming back. Moving out?}
{224}{}{Yes, we have to go.}
{225}{}{No, it's not time yet.}
{226}{}{Lead the way, amigo.}
{227}{}{Let's go.}
{228}{}{Okay. But don't forget about me.}
{229}{}{Don't go anywhere.}

{230}{}{You should hide your weapon.}
{231}{}{Sounds like a pretty bad idea. Okay, I'll take it away. Until the first occasion.}
{232}{}{It's not worth showing your hostility now.}
{233}{}{We'll have to take off this armor.}
{234}{}{OK. It's really quite stuffy in there.}
{235}{}{That's good.}
{236}{}{Wait. Are you going to raise the alarm with the whole crowd? Well, no, I'd rather try to escape alone.}
{237}{}{Are you sure? Your business.}
{238}{}{Okay, I'll leave the team in a safe place and come back for you.}

{250}{}{What do you know about this place?}
{251}{}{These places are unfamiliar to me. But I think it's not worth staying here.}
{252}{}{I see.}
{253}{}{Hermosillo is the ruins of a very old town. There were no residents here until the Mexican troops founded their fort. Apart from the old ruins, the military and a few civilians, there is nothing remarkable here.}
{254}{}{This is Phoenix, the biggest city I know of. But don't think that you can relax here. This city is treacherous.}
{255}{}{Poor neighborhoods of Phoenix. I wouldn't live here. In any case, keep the gun close to your hands.}
{256}{}{Sewage system? Well... listen, what are we even doing here?}
{257}{}{I've been here a few times, but I've never been to the tinsmiths' base. They don't like newcomers and consider them second-class people. However, if you get along with technology, you will quickly find a common language with them.}
{258}{}{A small oasis on the trade route. Literally. The water pump is still operating here, so the caravans willingly stop for the night. There won't be any special problems with the locals if you don't meddle in their affairs yourself.}
{259}{}{This is a peaceful, but semi-closed town. Mostly agave and maize are grown here... listen, further west is Puerto Penasco. It would be nice to go there right now. It won't take long.}
{260}{}{I've never been to these parts. We've gone too far. Hey, I'll never get to Puerto Penasco like this!}
{261}{}{The Church of the Fire Worshippers is a local landmark. Although these people are pious, they also know how to hold weapons in their hands.}
{262}{}{This place is creepy. It seems as if a pair of eyes are staring at you through the cracks.}
{263}{}{Are you kidding? There is no brotherhood anymore!}
{264}{}{The Brotherhood of Steel runs everything here. Great guys, if you don't piss them off. Keep your gun in your holster and watch your tongue, they don't like upstarts and provocateurs.}
{265}{}{Some call this place the Devil's City. They say there are the living dead roaming the streets here or something like that. Listen, do we have to go there?}
{266}{}{It turns out that the monks have been hiding this refuge from the rest of the city for many years? Damn, what other secrets do they keep in their dark storerooms?}

{300}{}{Tell me about yourself?}
{301}{}{There's nothing to tell. Call me Jack, if you like. I'm here by order of the caravaneers from the north. They needed guys to scout the southern lands. They hoped to find settlements suitable for trade here. But it seems that the idea is doomed to failure.}
{302}{}{Why were you locked up in prison?}
{303}{}{The military did not believe my explanations and decided that I was a spy. In their opinion, apparently, enemies are all around.}
{304}{}{What are your plans now?}
{305}{}{First we need to get out of Hermosillo, away from the garrison. And then we'll see.}
{306}{}{Then let's get out of here.}
{307}{}{And you really can be trusted. Listen, I need to get to Puerto Penasco. This is a small old port on the shore of the Gulf of California. I can't get there alone, maybe we can get there together? I think you will also find a job there.}
{308}{}{And what is there in this port?}
{309}{}{My customers are there. After all, I need to report on the work done... But I couldn't find out anything special. It would be good to collect more data for them in Hermosillo.}
{310}{}{It looks like it smells like a good profit. Great, I'm in.}
{311}{}{Glad to hear it, partner. You won't regret it.}
{312}{}{Then we're on our way to Puerto Penasco...}
{313}{}{I'll take you to the port, but if it's a trap, you'll pay cruelly.}
{314}{}{I'm telling you - this is business. Don't worry, you'll get your interest from the fee too.}
{315}{}{OK, we're on our way to Puerto Penasco...}
{316}{}{Sorry, but we're not on the way.}
{317}{}{Okay, whatever you say. In this case, I suggest we get to the nearest settlement, and then we will disperse peacefully.}
{318}{}{Okay.}
{319}{}{Looks like we've lost it. What are you going to do now?}

{320}{}{Remind me where you need to get to?}
{321}{}{Puerto Penasco is a port city on the Gulf of California.}
{322}{}{Then let's not waste time.}
{323}{}{I can't go there right now, sorry.}
{324}{}{I hasten to disappoint you - one of the ships in Puerto was blown up. This place is no longer inhabited.}
{325}{}{Are you kidding me? I won't believe it until I see it with my own eyes.}
{326}{}{Okay, then let's go to Puerto.}
{327}{}{My job is to warn.}

{330}{}{Which... What happened here?}
{331}{}{So this is where you were supposed to meet the customer?}
{332}{}{Yes, but... What force could destroy an entire port?}
{333}{}{It looks like the local "caravaneers" were selling something very killer, isn't it?}
{334}{}{Wait... okay... let me explain. I did lie a little. I was hired not by the caravaneers, but by the Brotherhood of Steel. And I had to scout not trade routes, but the military potential of the Mexican army. But what difference does it make now? After all, the Brotherhood's post has been destroyed!}
{335}{}{Oh, yes, someone was left without a fee.}
{336}{}{Are you laughing? After all, we were left without bottlecaps. Well, this trip turned out to be pointless.}
{337}{}{What are you going to do now?}
{338}{}{I don't know. Without the Brotherhood, there will be a decline in these parts, and without the caps, there is no point in me returning to Phoenix. I'll have to wander the wastelands in search of work.}
{339}{}{You know, we should stick together. I need an assistant on the way, and you will surely find a place at the Villa when everything settles down there.}
{340}{}{Do you think your relatives will accept me? Well, it's worth a try. It must be great to have your own home and family. Come on, partner. I'll watch your back.}
{341}{}{Come on, Jack.}
{342}{}{You're right. You're totally fucked. I think from now on our paths diverge.}
{343}{}{Will you leave me like this? After everything we've been through together?}
{344}{}{Yes. You've proved that you can't be trusted. Give me my things and go your own way.}
{345}{}{And you know, I enjoyed escaping from the blazing Hermosillo with you. I think there will be a place for you at our Villa when everything settles down there.}

{350}{}{We're here. You'll have to wait a bit while I talk to my customer.}
{351}{}{Wait a minute, are your customers the Brotherhood of Steel? But you said that...}
{352}{}{Yes, yes, I lied about the caravaneers. The Brotherhood of Steel pays excellent caps for exploration of the southern lands... Now wait here, it will take a little time.}
{353}{}{[Next]}
{354}{}{(Three hours later, Jack comes out to you with a contrite look)}
{355}{}{How did the negotiations go?}
{356}{}{These scum don't want to pay! In their opinion, I didn't get any valuable information. I had to tell you about you and my rescue from captivity. And for some reason they were interested in your personality. Go talk to Paladin Latham, he wants to see you. I'll rest here for now.}
{357}{}{Okay, Jack. See you later.}
{358}{}{The chief of the patrol service wanted to see you. Do you remember?}
{359}{}{Something has changed. Now we are not welcome here. It's better to get out of here while your legs are intact.}
{360}{}{What's up with the caps? Did they pay you?}
{361}{}{Yes, but they broke your contract. Sorry.}
{362}{}{S-bitches... Why did I go through so much? It looks like this trip turned out to be pointless.}
{363}{}{What are you going to do now, Jack?}
{364}{}{I don't know. Since the contract with the Brotherhood is broken, and I have no caps, I will have to wander the wastelands in search of work.}
{365}{}{We'll talk about it later.}
{366}{}{No, I couldn't find a common language with Latham.}
{367}{}{Jack has temporarily left you.}
{368}{}{We didn't have any useful information about Hermosillo. We'll have to go back there to collect more data on the Mexican army.}