{100}{}{You see a prioner of war.}
{101}{}{You see a man that looks to have been beaten.}
{102}{}{You see Jack.}
{103}{}{So this is your home? A bit old faschioned, but peaceful. I like it here.}
{104}{}{You're pretty well off! I only saw this level of plant life in Casa Nueva.}
{105}{}{Just don't tell me we need to go inside another hole.}
{106}{}{Phoenix... Though I grew up here, I never really wanted to return.}

{200}{}{Who are you? What do you want?}
{201}{}{That doesn't matter. Just sit tight and keep your mouth shut.}
{202}{}{Be quiet. I'm not exactly supposed to be here. Why do they keep you shut?}
{203}{}{What is this, some kind of trick to get me to talk? I already told everything during the interrogation! I was hired by traders to survey these lands. They hoped to find new caravan routes. That's all. Leave me alone!}
{204}{}{Doesn't sound very convincing.}
{205}{}{What else do you expect in these barren lands? Nobody up north has any idea that an entire military base is located here.}
{206}{}{I believe you. Want to run? I could use another hand.}
{207}{}{Your situation doesn't leave you much room for lying. Stay here and don't make noise.}
{208}{}{I'm not sure if I can trust you, but at this point, I have nothing left to lose. If I stay here, they'll hang me anyway. Though with no weapons or armor, I'm not going to be of much use. You know where they store that kind of stuff?}
{209}{}{We'll figure things out on the go. On your feet.}

{210}{}{I told you everything already. Leave me alone!}
{211}{}{Your words don't sound too convincing.}
{212}{}{Everything's okay. I'm on your side. Want to get outta here?}
{213}{}{Stay here and don't make noise.}
{214}{}{It's too early to leave right now. Wait for my signal.}

{220}{}{Hey, where are we going?}
{221}{}{Don't make noise. You'll find out soon.}
{222}{}{We're already there. You'll have to wait for me here.}
{223}{}{I was thinking you wouldn't come back. So, we're moving out?}
{224}{}{Yeah, it's time.}
{225}{}{No, not yet.}
{226}{}{Show me the road, amigo.}
{227}{}{Let's go.}
{228}{}{Fine. But don't forget about me.}
{229}{}{Don't go anywhere.}

{230}{}{You should conceal your weapon.}
{231}{}{Sounds like a rather bad idea. Fine, I'll put it away. But I'm taking it out as soon as I smell trouble.}
{232}{}{It's best not to show hostility right now.}
{233}{}{You have to take this armor off.}
{234}{}{Good. It's getting rather hot.}
{235}{}{Good.}
{236}{}{Wait a minute. A whole party? No way! I'll have better chances trying to escape by myself.}
{237}{}{You sure? Fine.}
{238}{}{Alright. I'll leave my team in a safe place and then come back for you.}

{250}{}{What do you know about this place?}
{251}{}{Not too familiar with this one. But I don't think we should stay here.}
{252}{}{I see.}
{253}{}{Hermosillo is the ruins of a very old city. It was uninhabited, until the Mexican troops established their base here. Aside from some remains of old buildings, a few soldiers and civilians, there's really nothing of note here whatsoever.}
{254}{}{This is Phoenix. The biggest city out of all I know about. But don't think it's somewhere you can relax. This city is insidious.}
{255}{}{The slums of Phoenix. Personally, I wouldn't live here. In any case, keep your weapon close.}
{256}{}{Sewers? Well... Listen, what are we even doing here?}
{257}{}{Though I've passed this place a few times, I never went inside the tinsmith base. They don't like outsiders. To them, they're inferior beings. Though, if you know how to work with tech, you'll be quick to reach an agreement.}
{258}{}{A small oasis on a trade route. Literally. There's still a working water pump here. That's why the caravans are eager to stay and rest here. If you mind your business, the locals won't be a problem.}
{259}{}{Peaceful, but somewhat closed town. They mostly grow agave and maize here... Listen, Puerto Penasco is to the west. It'd be great to go there right now. It won't take much time.}
{260}{}{I've never been here. We've strayed too far. Hey, I'm never getting to Puerto Penasco if we keep doing this!}
{261}{}{The fire-worshipper church is a local landmark. Those people are devout, but they're better with weapons than you might think.}
{262}{}{This place gives me the creeps. Feels like there are eyes looking at you through the holes.}
{263}{}{Are you kidding me? The Brotherhood's gone!}
{264}{}{The Brotherhood runs everything here. Great guys, if you don't make them mad. Keep your weapon concealed and watch your tongue. They don't like upstarts and provocateurs.}
{265}{}{Some call this place the City of the Devil. They say that the living dead roam the streets, or something like that. Listen, do we really need to go there?}
{266}{}{So, for all these years, the monks have been hiding this Vault from the rest of the city? Damn. I wonder what other mysteries they're hiding in their dark corridors.}

{300}{}{Tell me about yourself.}
{301}{}{There's nothing to talk about, really. Call me Jack, if you want. I'm here because I signed a contract with the northern caravaneers. They needed guys to scout the southern areas. They were hoping to find settlements they could trade with. But it looks like that idea is doomed.}
{302}{}{Why'd they lock you up?}
{303}{}{They didn't believe what I was saying, and decided that I was a spy. They seem to think they are surrounded by enemies on all sides.}
{304}{}{What are you planning on doing now?}
{305}{}{First, I need to get out of Hermosillo and travel somewhere far away from the military base. After that, we'll see.}
{306}{}{Then let's get out of here.}
{307}{}{You really *can* be trusted. Listen, I need to get to Puerto Penasco. It's a small, old port on the coast of the Gulf of California. I can't get there by myself. Maybe we can go there together? I think you'll find something to do there, too.}
{308}{}{What does that port contain?}
{309}{}{My clients are located there. I do need to report back, after all.}
{310}{}{I smell profit. I'm in.}
{311}{}{Glad to hear it, pardner. You won't regret it.}
{312}{}{Then let's head to Puerto Penasco...}
{313}{}{I'll bring you to the port, but if it's a trap, you're going to suffer.}
{314}{}{I'm telling you - it's business. Don't worry. You'll receive a part of the money.}
{315}{}{Good. Let's head to Puerto Penasco...}
{316}{}{Sorry, it's not the way I'm heading.}
{317}{}{Alright. In that case, I propose that we head to the closest settlement, and there we'll part our ways.}
{318}{}{Fine.}
{319}{}{Looks like the situation has changed. What will you do now?}

{320}{}{Remind me, where do you need to get to?}
{321}{}{Puerto Penasco. An old port on the coast of the Gulf of California.}
{322}{}{Then let's not waste any time.}
{323}{}{I can't go there right now, sorry.}
{324}{}{Sorry to dissapoint you - one of the ships in Puerto blew up. The place is completely uninhabitable now.}
{325}{}{You're kidding, right? I don't believe it. Not until I see it with my own eyes.}
{326}{}{Fine, let's go to Puerto then.}
{327}{}{Don't say I didn't tell you.}

{330}{}{What the... What even happened here?}
{331}{}{So this is where you were supposed to meet your clients?}
{332}{}{Yeah, but... what thing on this earth could destroy an entire port?}
{333}{}{Looks like the local "caravaneers" were trading something quite dangerous, no?}
{334}{}{Wait, wait... okay... let me explain. I wasn't entirely telling the truth. I was hired, but not by caravaneers. They call themselves the Brotherhood of Steel. And I wasn't supposed to find trade routes, but record what military potential the Mexican army has. But what difference does it make now? The entire Brotherhood base has been destroyed!}
{335}{}{Oh yeah, someone isn't going to get paid.}
{336}{}{You kidding? We're almost out of caps. This entire trip was completely pointless.}
{337}{}{What are you going to do now?}
{338}{}{Dunno. Without the Brotherhood, these lands are going to decay, and without any caps, there's no point returning to Phoenix. I'll have to wander the wastes in search of work.}
{339}{}{You know, we should stick together. I need someone to help me in my travels. Plus, I'm sure you'll find a place in Villa, when things settle down there.}
{340}{}{You think your fellows will accept me? Well, I suppose it wouldn't hurt to try. It's probably great to have a home and a family. Let's go, partner. I'll be watching your back.}
{341}{}{Let's go, Jack.}
{342}{}{You're right - you're basically fucked. And this, I think, is the best moment for our paths to diverge.}
{343}{}{You're abandoning me? Just like that? After everything we've lived through together?}
{344}{}{You've shown that you cannot be trusted. So, yeah. Absolutely. Give me back my stuff and go wherevever you please.}
{345}{}{You know, I liked running away from the blazing Hermosillo base with you. You could probably find a place in Villa, when things settle down there.}

{350}{}{Well, we're here. You'll have to wait for a bit while I talk to my clients.}
{351}{}{Now wait a minute, your clients are the Brotherhood of Steel? But you told me...}
{352}{}{Yeah, I lied about the caravaneers. The Brotherhood pays excellent caps for scouting the southern areas... Now, just wait here. This should only take a moment.}
{353}{}{[Continue]}
{354}{}{(Three hours pass. Jack comes back to you with a completely defeated look)}
{355}{}{How did it go?}
{356}{}{The bastards don't want to pay! They don't think I got any useful information. I had to tell them about you and how you rescued me. For some reason, you interested them. Go there, talk to paladin Latham. He wants to see you. I'll rest here.}
{357}{}{Okay, Jack. See you later.}
{358}{}{The patrol chief wanted to see you. Remember?}
{359}{}{Something changed. We're no longer welcome here. We better get out of here, and fast.}
{360}{}{What about the caps? Did you get paid?}
{361}{}{Yeah, but your contract with them is no more. Sorry.}
{362}{}{F-fuckers... Why'd I live through all this? This whole journey has turned out to be completely pointless.}
{363}{}{What are you going to do now, Jack?}
{364}{}{Dunno. Without the Brotherhood contract, with no caps, the only thing left to do might be to wander the wastes in search of work.}
{365}{}{We'll talk about that later.}
{366}{}{No, I didn't manage to reach an agreement with Latham.}
{367}{}{Jack has temporarily left you.}