{100}{}{You see Dominguez.}
{101}{}{You see a typical peasant.}
{102}{}{Damn military, always armed and armored, huh?}
{103}{}{Get out before I knock your brains out.}
{104}{}{Previous shoes are still okay.}
{105}{}{Sandals from old rubber? Why didn't I think of this before?!}
{106}{}{It seems that you've solved Dominguez's shoe problem. Dominguez is very happy.}

{200}{}{Stop. Why are you here?}
{201}{}{I just want to talk. Why so hostile?}
{202}{}{Military's nearby, and I don't know you. If you're here for no particular reason, you better head back.}
{203}{}{Will do exactly that. Too dangerous here...}
{204}{}{Are you really going to deny hospitality to a traveler from the north? I just want to ask some questions about this place.}
{205}{}{(raises rifle threateningly) Get. Out.}
{206}{}{Fine, whatever you say...}
{207}{}{You're going to regret this...}
{208}{}{You again. I told you - get outta here.}
{209}{}{Okay, man. No problem.}

{210}{}{Good. Ask them. But you will leave afterwards.}
{211}{}{Already leaving, relax.}
{212}{}{Do you live here alone?}
{213}{}{No. There are a few other families of civilians nearby. Military doesn't like it when civilians are nearby.}
{214}{}{Military? What military?}
{215}{}{You don't know? Down the main highway is a New Mexican Republic base. These lands are now under the protection of general Sarabia.}
{216}{}{So I can't exactly expect to settle in these lands?}
{217}{}{You really don't know? Listen, the country's in a tough situation. The president's army is trying to unify the disparate lands, and we are the ones who pay for it - simple, peaceful peasants. They didn't even ask us. That's why it's not a good idea to live near the fort. They don't tolerate people like that.}
{218}{}{How did you end up here?}
{219}{}{I had connections. And the fort needs food. My ranch is under their protection, though sometimes I need to give them almost all my meat.}
{220}{}{I see. Thanks for telling me. I should go.}
{221}{}{Oh, this changes much. I think I should get out of here. Now.}
{222}{}{What do you know about general Sarabia?}
{223}{}{Manuel Sarabia. I saw him a few times during ceremonies, but he spends most of his time in the headquarters building. It's up that mountain over there.}
{224}{}{I think I should go meet him. Hopefully he'll have some time to talk.}
{225}{}{Are people allowed to see him?}
{226}{}{Civilians? No. No way. I don't want to meet anyone who would be permitted to do that. They say he drips his bread into the blood of his enemies.}
{227}{}{Such a general is deserving of respect. I *have* to see him. Goodbye.}
{228}{}{Oh. This changes things. I should go somewhere else. Farewell.}
{229}{}{What were you saying about the general?}
{230}{}{Do you know the military's plans for Arizona?}
{231}{}{I doubt the military is going to go into Arizona for quite some time. They'd need to cross a huge barren desert, and for a long time, we didn't even think life existed out there. But if the government orders them to - the military will, no questions about it.}
{232}{}{Thanks. That was valuable information. I have to go now. Goodbye.}
{233}{}{Maybe you've heard about the military's plans for Arizona?}
{234}{}{Do you know the general's plans for Arizona?}
{235}{}{Good. Ask them.}
{236}{}{Of course, ask them.}
{237}{}{I'm just a peaceful wanderer, I mean you no harm. Let's talk, amigo?}

{238}{}{Thanks for the radio. It brightens these gray days, even if not by much.}
{239}{}{Can I talk to you?}

{240}{}{Do you know old man Gallegos? He came to the north from these lands.}
{241}{}{You know about Gallegos? How unexpected. So he did cross the desert after all. I thought that idea was, effectively, suicide.}
{242}{}{Only he survived. Everyone else died. So, you're not entirely wrong.}
{243}{}{Gallegos and the others were desperate. The military and the new government aren't kind to the peasantry. People like me are lucky. The rest work like slaves. Trying to escape to the north seemed like the only reasonable option.}
{244}{}{He lost much of his health along the way.}
{245}{}{I wouldn't wish what he survived out in that scorching desert upon my worst enemies. Though the old man betrayed his nation, to us, he showed us the kind of will and endurance we must strive for. Thank you for telling me this. I have been wondering what happened to my old friend for a long time. And the friends of my friends are my friends as well.}
{246}{}{No problem.}
{247}{}{Old man Gallegos talked about Dominguez and his ranch. He said that he is a good and honest man who wouldn't deny a glass of water to a wanderer.}

{250}{}{Where did you get those brahmin from?}
{251}{}{Brahmin? What's that?}
{252}{}{The animals in your ranch.}
{253}{}{You don't know how the animals you have are called? Funny.}
{254}{}{A-ah, the vak. You northeners always complicate everything. I bought these ones from the military after they conducted a vak raid. That's how they used to get meat, before they started taking it from me. In a way, it was a loan that I'm now paying for with food.}
{255}{}{Can I ask you a question?}
{256}{}{I was just curious. Bye.}
{257}{}{I was in this place called San Brahmin. The locals there revere these animals. They think they're holy.}
{258}{}{Holy Brahmin? Never heard of it. Sounds rather stupid.}
{259}{}{Maybe. It could have been a way to survive for them.}
{260}{}{Exactly. The most stupid thing I've ever seen.}
{261}{}{Your questions tire me. I must go back to my business.}
{262}{}{I'm already leaving, don't worry.}

{270}{}{You said that Mexico is in a tough situation. What's the deal?}
{271}{}{Yes. You see, during La Gran Guerra, our capital was destroyed, which resulted in many provinces gaining independence. Most of them acquired a small army and defended their borders.}
{272}{}{Go on.}
{273}{}{Spare me the details. I get the overall picture.}
{274}{}{I don't know much myself. But they say the northern states were captured by bandit cartels. Before that, they traded weapons, drugs and people. Without this business, they focused on defending their territories. Now they are private properties of the descendants.}
{275}{}{What about the rest of the country?}
{276}{}{The situation in the south was especially bad. Various groups of nationalists divided the land into small governments. Yucatan, Chiapas, Tabasco, and even Guerrero still argue over which one is the most important.}
{277}{}{That's all history. What is the situation like now?}
{278}{}{Thankfully, everything changed after the new president came to power. He gathered a powerful army and subjugated all the central states: from Durango to Veracruz. At the moment, he is conducting brutal battles to the east of the Isthmus of Tehuantepec. The local tribes are too proud, so that war will last for several more years. And the northern states are just waiting for their turn.}
{279}{}{Thanks for telling me all this.}
{280}{}{De nada. I'm happy to share the history of my nation with people like you. Who knows, maybe your distant ancestors were from Mexico too.}
{281}{}{Listen, you talk about a lot of interesting stuff. Can you spare a few more minutes?}
{282}{}{Okay, Dominguez. Bye.}