{100}{}{You see Dominguez's child.}
{101}{}{You see a typical peasant boy. The smell is appropriate.}
{102}{}{Zz-z-z...}
{103}{}{Previous shoes are still okay.}
{104}{}{The child is pleased with the new shoes.}
{105}{}{Thanks!}

{110}{}{Hi. Did you really come from the north?}
{111}{}{Strange. You don't look like a savage cannibal to me.}
{112}{}{They always told us that only savages live out there.}
{113}{}{Do you really eat people there?}
{114}{}{General Sarabia will conquer Arizona one day.}
{115}{}{Want to push the vak?}
{116}{}{Maybe it's best for you not to come close to our vak. They hate unfamiliar people.}
{117}{}{Want to ride the vak? Double pesos.}
{118}{}{You actually pay with bottle caps? Ph-ha-ha-ha!}
{119}{}{Silly northener! Silly northener! Be-be-be!}
{120}{}{My shoes got torn. Do you have any shoes you could spare?}

{1110}{}{Hi. Did you really come from the north?}
{1111}{}{Strange. You don't look like a savage cannibal to me.}
{1112}{}{They always told us that only savages live out there.}
{1113}{}{Do you really eat people there?}
{1114}{}{General Sarabia will conquer Arizona one day.}
{1115}{}{Want to push the vak?}
{1116}{}{Maybe it's best for you not to come close to our vak. They hate unfamiliar people.}
{1117}{}{Want to ride the vak? Double pesos.}
{1118}{}{You actually pay with bottle caps? Ph-ha-ha-ha!}
{1119}{}{Silly northener! Silly northener! Be-be-be!}