{100}{}{You see Dominguez.}
{101}{}{Here is a typical peasant.}
{102}{}{Damn military, you're always armored and fully armed, right?}
{103}{}{Get out before I blow your brains out.}
{104}{}{The old shoes haven't worn out yet.}
{105}{}{Sandals made of old rubber? How did I not guess earlier!}
{106}{}{It looks like you've solved Dominguez's old shoe problem. Dominguez is very happy about this.}

{200}{}{Wait. What do you need?}
{201}{}{I just want to talk. Why such hostility?}
{202}{}{The military is nearby, but I do not know you. If you're here by chance, you'd better leave.}
{203}{}{I'll do that. I don't want to meet even more resistance from the locals...}
{204}{}{Would you refuse a favor to a traveler from the north? I just want to ask about this city.}
{205}{}{(raises his gun threateningly) Get off my ranch.}
{206}{}{Okay, whatever you say...}
{207}{}{You'll regret it...}
{208}{}{You again. I told you to get off my ranch.}
{209}{}{Sure, man, no problem.}

{210}{}{OK, ask. But after that you will leave.}
{211}{}{I'm already leaving, relax.}
{212}{}{Do you live here alone?}
{213}{}{No, there are still a few peaceful families in the vicinity. The military does not like civilians under their noses.}
{214}{}{Military? Who are you talking about?}
{215}{}{Don't you know? Further along the main highway, the garrison of the New Mexican Republic is located. Now these lands are under the protection of General Sarabiy.}
{216}{}{So I won't be able to count on my house in these parts?}
{217}{}{You really don't know anything? Listen, the situation in the country is difficult. The president's army is trying to unite disparate lands, and we, simple peaceful peasants, are paying for it. And they didn't even ask us. Therefore, living near the fort is not the best idea. The military does not tolerate self-settlers.}
{218}{}{And how did you get here?}
{219}{}{I had connections. And the fort needs food. My ranch is under the protection of the garrison, although in return I have to give almost all my meat.}
{220}{}{That's how it is. Thanks for the clarification. I think I should go.}
{221}{}{Oh, that changes a lot. Perhaps I should retire from here. Urgent.}
{222}{}{General Sarabia - what do you know about him?}
{223}{}{Manuel Sarabia. I saw him several times in the motorcade and at general training camps. He's usually at the General Staff at the top of that mountain.}
{224}{}{I think I should see him. I hope he has a minute.}
{225}{}{Are they allowed to talk to him?}
{226}{}{Civilians? No. And I don't really want to face such a person. They say he eats bread by dipping it in the blood of slain enemies.}
{227}{}{This general is admirable. I just need to meet him. Bye.}
{228}{}{So it changes things. I think I'd better go somewhere else. Goodbye.}
{229}{}{And what did you say about the general?}
{230}{}{Are you aware of this army's plans for Arizona?}
{231}{}{I doubt the garrison is going to Arizona anytime soon. To do this, it is necessary to overcome a huge barren desert, and for a long time we even believed that there was no life in the north. But if the government orders it, the army will go.}
{232}{}{Thank you, it was valuable information. I think I need to do something. Later.}
{233}{}{Maybe you've heard about his army's plans for Arizona?}
{234}{}{Do you know General Sarabia's plans for Arizona?}
{235}{}{OK, ask.}
{236}{}{Of course, ask.}
{237}{}{I'm just a peaceful wanderer and I don't want to hurt you. Let's talk, amigo?}

{238}{}{Thanks for the radio. He embellishes our gray everyday life at least a little.}
{239}{}{Can I talk to you?}

{240}{}{Do you know old Gallegos? He came to the north from these parts.}
{241}{}{Do you know Gallegos? What a surprise. So he managed to cross the desert. I thought this crazy idea was tantamount to suicide.}
{242}{}{Of the entire group, only he survived. So you were almost right.}
{243}{}{Gallegos and the others had a desperate situation. The new government and troops oppressed the peasants. People like me are lucky, but many work like slaves. Running north seemed like the only solution.}
{244}{}{However, judging by his condition, he had wasted all his health along the way.}
{245}{}{I can imagine what he had to go through in this hot desert. Although the old man was a traitor to the country, he showed us an example of will and perseverance. Thank you, I was glad to hear the news about an old friend. And my friends' friends are also my friends.}
{246}{}{Please.}
{247}{}{Old Gallegos was talking about the Dominguez ranch. He said he was a good and honest man who would not refuse a traveler a glass of water.}

{250}{}{Where did you get the Brahmins?}
{251}{}{Brahmins? What is it?}
{252}{}{Your animals are on the ranch.}
{253}{}{Do you know the name of your cattle? It's ridiculous.}
{254}{}{Ah, waki. You Northerners always complicate things. I bought this animal young from the military after their raid for the vaks. They used to get their meat this way, now they take it from me. In a sense, this is a loan for which I pay with provisions.}
{255}{}{Can I ask another question?}
{256}{}{I was just curious. Later.}
{257}{}{I have been to San Brahmin. The locals revered these animals as sacred.}
{258}{}{Holy Brahmin? I've never heard of it. I think it's stupid.}
{259}{}{Perhaps. But for them it was a matter of survival.}
{260}{}{To the point. It's the stupidest thing I've ever seen.}
{261}{}{Your questions are tiring. I have to mind my own business.}
{262}{}{I'm leaving now, don't worry.}

{270}{}{You were talking about the difficult situation in Mexico. What's the matter?}
{271}{}{Yes. You see, during La Gran Guerra, our capital was destroyed, as a result of which many provinces gained independence. Most of them got a small army and defended their borders.}
{272}{}{Go on.}
{273}{}{No need for details. The overall picture is already clear.}
{274}{}{I know a little myself. But they say that the northern states have been seized by gangster cartels that in the past traded in weapons, drugs and people. Having lost their business, they took up the defense of their territories. Now it is the private property of their descendants.}
{275}{}{The rest of the country?}
{276}{}{It was especially difficult in the south of the country, where the nationalists divided the territory into separate small states. Yucatan, Chiapas, Tabasco and Guerrero are still arguing who is in charge.}
{277}{}{It's all history. And how are things now?}
{278}{}{Everything changed with the coming to power of the new president. He gathered a strong army and subdued all the central states from Durango to Veracruz. Right now he is fighting fierce battles east of the isthmus of Tehuantepec. The local tribes are too proud, so this war will last for many years. The northern states are also gradually losing ground.}
{279}{}{Thanks for the story.}
{280}{}{De nada. It is my joy to share the history of my people with people like you. Who knows, maybe your ancestors also came from Mexico once.}
{281}{}{Listen, you tell a lot of interesting things. Will you give me some more time?}
{282}{}{Okay, Dominguez. Bye.}