{100}{}{You see Dominguez's baby.}
{101}{}{Here is a typical country boy. And he smells like it.}
{102}{}{Hr-r-r...}
{103}{}{The old shoes haven't worn out yet.}
{104}{}{The child is very happy about the new shoes.}
{105}{}{Thank you!}

{110}{}{Hi. Did you really come from the north?}
{111}{}{Strange. You don't look like a man-eating savage.}
{112}{}{We have always been told that only savages live in the north.}
{113}{}{Do you really eat people there in the north?}
{114}{}{Someday General Sarabia will capture Arizona.}
{115}{}{Do you want to push Vaka?}
{116}{}{It's better not to approach our waka. They don't tolerate strangers.}
{117}{}{Do you want to ride the vaks? Then pay double the peso.}
{118}{}{Are you really paying with caps? Pf-ha-ha-ha!}
{119}{}{Stupid Northerner! Stupid Northerner! Be-be-be!}
{120}{}{My shoes are torn. Do you have anything to replace it?}

{1110}{}{Hi. Did you really come from the north?}
{1111}{}{Strange. You don't look like a man-eating savage.}
{1112}{}{We have always been told that only savages live in the north.}
{1113}{}{Do you really eat people there, in the north?}
{1114}{}{Someday General Sarabia will take Arizona.}
{1115}{}{Do you want to push vaka?}
{1116}{}{It's better not to approach our waka. They don't tolerate strangers.}
{1117}{}{Do you want to ride the vaks? Then pay double the peso.}
{1118}{}{Do you really pay with caps? Pf-ha-ha-ha!}
{1119}{}{Stupid Northerner! Stupid Northerner! Be-be-be!}