{100}{}{You see Dominguez's partner.}
{101}{}{You see a typical peasant's wife.}
{102}{}{Please be careful! You'll break all the plates in that thing!}
{103}{}{Previous shoes are still okay.}
{104}{}{The woman is crazy about her new shoes.}
{105}{}{Thank you! It's so hard to find new shows out here...}

{110}{}{Ah... what... dear, check the... *yawn* door...}
{111}{}{Eh... que... Querido, mira... *yawn* la puerta.}
{112}{}{Get out, damn gringo!}
{113}{}{Vete, sucio gringo!}
{114}{}{I'm too tired. Talk to my husband.}
{115}{}{I'm too tired to talk right now. Talk to my husband instead.}
{116}{}{You better go. We don't like it when intruders break into our house and interrogate us.}

{200}{}{Ah, excuse my husband. He's still shaken up after that night when the patrolment got into our house at night and threw a party.}
{201}{}{Isn't the military supposed to protect you?}
{202}{}{Oh yes, absolutely. For the most part, they don't bother us. After all, we supply their base with meat. The order to defend us was signed by the general himself. But these soldiers were all worked up, I think because of some spy chase. So they lost their temper. In the end, they even catched him, but were still knee-deep in trouble.}
{203}{}{What did they want from you?}
{204}{}{They thought the spy could be hiding in our house. In the end, they caught him in the desert. On their way back, they visited us to rest, eat and collect water. It's just a very unpleasant situation.}
{205}{}{[Continue]}
{206}{}{One of them must have stolen our radio. We could be using it to "eavesdrop on military communications". What nonsense!}
{207}{}{Agreed - not good behavior at all. I think I should get out of here. Farewell, senora.}
{208}{}{What happened to that spy?}
{209}{}{Why do you need a radio?}

{210}{}{I'm too tired to talk right now. Talk to my husband instead.}
{211}{}{Goodbye.}

{220}{}{What happened to that spy?}
{221}{}{Well, they took him to the prison they have in their base. That's all I know.}
{222}{}{I see.}
{223}{}{Why do you need a radio?}
{224}{}{When the weather is just right, we can receive news from Los Mochis. A small population under the control of the new government exists there. We want to know what's happening in the country, too.}
{225}{}{Alright.}
{226}{}{Is this radio yours?}
{227}{}{It really is! How did you manage to get it?}
{228}{}{Easily. You just enter and take everything you can.}
{229}{}{Well, I had to make sure they wouldn't notice me.}
{230}{}{Unbelievable! We tried to ask people inside the base, but they didn't let us in. We even wanted to forget about the radio. Muchas gracias!}
{231}{}{De nada, seœora.}
{232}{}{No problem at all.}