{100}{}{You see Dominguez's wife.}
{101}{}{Here is a typical peasant's wife.}
{102}{}{Please be careful! You'll break all my dishes in this thing!}
{103}{}{The old shoes haven't worn out yet.}
{104}{}{A woman is crazy about new shoes.}
{105}{}{Thank you very much! It's so hard to find shoes in these desolate lands...}

{110}{}{And... what... Honey, check it out... *yawn* door...}
{111}{}{Eh... que... Querido, mira... *yawn* la puerta.}
{112}{}{Get out, you damn gringo!}
{113}{}{Vete, maldito gringo!}
{114}{}{I'm too busy. Talk to your husband.}
{115}{}{I'm too busy to talk. Talk to your husband.}
{116}{}{You'd better leave. We do not like outsiders who brazenly break into the house with questions.}

{200}{}{Oh, I'm sorry about my husband. He's still worried after that night when the patrolmen broke into our house and had a night party here.}
{201}{}{Aren't the military supposed to protect you?}
{202}{}{Oh, yes, mostly they don't touch us, because we supply meat to the garrison. The general himself signed a decree on our protection. But these soldiers turned out to be nervous because of the pursuit of some spy, so they allowed themselves too much. In the end, they even caught him, but at the same time they were up to their ears in mud.}
{203}{}{And what did they want from you?}
{204}{}{They thought the spy might have been hiding with us, but in the end he was caught up in the desert. On the way back, they stopped by to rest, eat and get water. It's just a very unpleasant story.}
{205}{}{[Next]}
{206}{}{However, one of them secretly took our radio. As if with its help we can eavesdrop on military negotiations. What nonsense!}
{207}{}{And the truth is that this is not very good behavior. I think it's time for me to run away from here as fast as I can. Goodbye, señora.}
{208}{}{And what happened to that spy?}
{209}{}{Why do you need a radio?}

{210}{}{I'm too busy to talk. Talk to your husband.}
{211}{}{Goodbye.}

{220}{}{What happened to that spy?}
{221}{}{Well, he was taken to the garrison prison. That's all I know.}
{222}{}{Clear.}
{223}{}{Why do you need a radio?}
{224}{}{Sometimes, in particularly good weather, we manage to catch news from Los Mochis. There is a small settlement under the new government. We also want to know what is happening in the country.}
{225}{}{Clear.}
{226}{}{Is this your radio?}
{227}{}{It's really him! How did you manage to get it?}
{228}{}{Nothing complicated. You just come in and take everything that's not lying well.}
{229}{}{Well, I had to try not to be noticed.}
{230}{}{Unbelievable! We tried to talk to someone from the garrison, but they wouldn't let us in. We even wanted to forget about this story. Muchas gracias!}
{231}{}{De nada, señora.}
{232}{}{You're welcome.}