{100}{}{You see a computer.}
{101}{}{You see an ancient computer with a spanish keyboard.}

#Dialogue
{200}{}{Enter command.}
{201}{}{Conclude session.}
{202}{}{Back.}

{210}{}{Base report.}
{211}{}{(2162 report intended for general HQ in Monterrey. General Sarabia's unit entered the lifeless city of Hermosillo and created a temporary base. After a week, an order demanding permanent presense came.)}
{212}{}{El Paso base.}
{213}{}{(The entry describes deliveries and communication codes for a similar base in El Paso. Looks like real battles are being waged there right now.)}
{214}{}{Goals and objectives.}
{215}{}{(Primary objective - hold position to expand territory of the new government.)}
{216}{}{Assessment of the situation.}
{217}{}{(Latest data suggests that the base thinks the biggest threat is a "Brotherhood of Steel" located in the ruins of Puerto Penasco and a settlement of "tinsmiths" near the Pre-War city of Tucson. The base is readying scouts to investigate the military power of these potential enemies.)}
{218}{}{Copy the data onto a holodisk.}
{219}{}{Data copied.}
{220}{}{(The data is in spanish. You don't understand a word of it.)}