{100}{}{It's a computer.}
{101}{}{You see an ancient computer. The keyboard is in Spanish.}

#Dialog
{200}{}{Enter command.}
{201}{}{End session.}
{202}{}{Back.}

{210}{}{Report on the quartering of the fort.}
{211}{}{(Report of 2162 for the General Staff in Monterrey. The detachment of General Sarabia entered the deserted Hermosillo and organized a temporary base. A week later, the order for permanent housing came.)}
{212}{}{Fort in El Paso.}
{213}{}{(This describes the supplies and communication codes with another similar fort in El Paso. It looks like real battles are taking place there now.)}
{214}{}{Goals and objectives.}
{215}{}{(The main task is to hold the position for the expansion of the possessions of the new state.)}
{216}{}{Assessment of the situation.}
{217}{}{(According to the latest data, the fort considers a certain Brotherhood of Steel on the ruins of Puerto Penasco and a settlement of tinsmiths near pre-war Tucson to be the main threat. The fort trains scouts to study the forces of these potential opponents.)}
{218}{}{Copy the computer data to the holodisk.}
{219}{}{The data archive has been copied.}
{220}{}{(The data is entered in Spanish. You don't understand what it says here.)}