{100}{}{You see Diana.}
{101}{}{You see a bald woman with a thoughtful gaze.}
{102}{}{Oh, of course, go ahead.}
{103}{}{Happy to see you.}

{110}{}{Hey, are we there yet?}
{111}{}{Big city. Almost like the Hub. Heh, brings back memories...}
{112}{}{This city is like a prison. I doubt the people are pleased.}
{113}{}{A city of nomadic pastoralists. The things you can find...}
{114}{}{This place gives me the creeps.}
{115}{}{I don't like this place. Watch your back.}
{116}{}{So, this is your home? Your people's industriousness is admirable.}
{117}{}{Can't believe my eyes. The legendary Desert Rangers!}
{118}{}{Don't you think we're a bit too far to the south?}
{119}{}{We finally got out of this hellhole.}
{120}{}{Hm. Doesn't look like the locals here particularly like outsiders.}

#First dialogue
{200}{}{Thank god I'm not the only one with a human face here!}
{201}{}{Who are you?}
{202}{}{Diana. I'm from the Followers of the Apocalypse and I'm heading to the Casa Nueva settlement. Or rather, was - my convoy was attacked by the things that live here. I was captured and brought here. I have no idea whether anyone else from my group survived.}
{203}{}{I'm very sorry, Diana.}
{204}{}{Understood.}
{205}{}{And what are you doing here? Did they capture you, too?}
{206}{}{I'm here by accident. The people of my village were taken away by slavers, and I'm searching for them.}
{207}{}{Hm. Makes sense. I've heard that slave trade is increasing in the east. But I don't think you'll find anyone here other than mutants.}
{208}{}{So are you planning on escaping this place?}
{209}{}{That is irrelevant. Are you planning on escaping this place?}
{210}{}{The Brotherhood of Steel sent me to help.}
{211}{}{Yes, the Brotherhood never leaves its brothers and sisters behind. For all their faults, one has to admit that, at the very least.}
{212}{}{So you're planning to escape this place?}
{213}{}{I'm afraid getting out of here will be quite difficult. If we try to walk out, security will shoot us down. But even if we do somehow get out without security noticing, the ghouls will tear us apart.}
{214}{}{This calls for a more cunning approach.}
{215}{}{Exactly. I don't want blood to be spilled. Not ours, not anybody else's. And neither does Levi, I think. He promised to set us free if I help him with his research.}
{216}{}{Is there any way to fight back?}
{217}{}{I do not want unnecessary bloodshed. Levi promised to set us free if I help him with his research. But if you truly think it's the best solution, you'll most definitely have to acquire the power armor.}
{218}{}{I need some time to think and assess the situation.}
{219}{}{}
{220}{}{Of course. But don't leave me behind. The children of Casa Nueva are waiting for their biology lessons.}
{221}{}{Okay...}

#Repeat dialogue
{250}{}{So? You got a plan?}
{251}{}{Wait for my instructions.}
{252}{}{What does Levi say?}

{260}{}{Tell me what's going on here.}
{261}{}{Okay. What is it exactly that you want to know?}
{262}{}{That's all.}

#- about the mission
{270}{}{I am interested in your mission.}
{271}{}{I was heading to Casa Nueva. That settlement is in dire need of scientists and teachers. Several Followers are already conducting some kind of experiments there.}
{272}{}{That's all.}
{273}{}{Can you show me where it is located?}
{274}{}{Of course. Open your map, I'll mark it...}
{275}{}{Thanks.}
{276}{}{I was in that town for a bit. Seemed like a lovely place.}
{277}{}{Really? That's great. I just want to get there faster.}
{278}{}{We'll get back to this... If we get out of here.}
{279}{}{I visited that place. It's built by slaves and the plantations are worked by peons. Those Followers are parasitizing on the labor of others.}
{280}{}{I know from experience it's hard to combine research and manual labor. But we are commited to making the world a better place. We would never use slavery ourselves. But the Brotherhood of Steel was our only option to establish Casa Nueva, and they unfortunately do.}
{281}{}{You convinced me.}
{282}{}{Uh-uh, as if this changes anything.}

{290}{}{Who are these "Followers of the Apocalypse"?}
{291}{}{Well, we are something of a humanitarian organization. We teach literacy, cure diseases and enlighten people with Pre-War knowledge.}
{292}{}{So you want to bring back the Old World?}
{293}{}{Not quite. Some say history does not exactly repeat itself, but rather, it rhymes. The Old World can't be returned in the way it existed. But even if we could, we wouldn't do it.}
{294}{}{Oof, and I thought you were mad.}
{295}{}{Alright.}
{296}{}{You're mad! The Old World fell because of this exact knowledge.}
{297}{}{Knowledge itself is neither good nor bad. It is a tool. We see to it that nobody repeats the mistakes of the Old World.}
{298}{}{Uh-uh. Like you can watch over everyone.}
{299}{}{Your goals are honorable and noble. I hope others see them this way, too.}
{300}{}{So you walked into an ambush?}
{301}{}{We were attacked by ghouls. They did set up an ambush, but not only that, a smoke screen. They snatched me from the group. I was saved by Levi's people, who happened to be nearby. They then brought me here.}
{302}{}{And you are thanking them for it?}
{303}{}{I don't believe any of these people to be evil in their hearts. Levi simply walks the path he thinks is the right one. He has no other choice.}
{304}{}{What about your companions?}
{305}{}{So the ghouls were acting on behalf of Levi?}
{306}{}{Most likely. For them, Levi is some kind of god... or devil. They try to appease him and perform his orders. But this is just my speculation.}
{307}{}{What happened to your companions?}
{308}{}{The unit consisted of several Brotherhood of Steel members. Paladin Barkley lead the unit. I haven't heard from any of them ever since I was abducted. I have no idea if they're still alive or not.}
{309}{}{Alright.}

{310}{}{You mentioned a "Brotherhood of Steel". Tell me more about it.}
{311}{}{Well, it's a closed military organization in California. They have strained relations with the Followers, which was why my inclusion in the convoy was not met very positively.}
{312}{}{What is it they do?}
{313}{}{For the most part, nothing. But lately, the Brotherhood has clearly started suffering from energy shortages. They started buying up all nuclear batteries in the region. They are also the best specialists in energy weapons and other advanced Pre-War technology. But they keep all of it for themselves. They don't want to share it with the outside world.}
{314}{}{Alright. Enough about that Brotherhood.}
{315}{}{Then what are they doing in Arizona?}
{316}{}{I think they are collecting technology and energy sources. There are many untouched Pre-War assets in Arizona.}
{317}{}{Do you know where their base is located?}
{318}{}{Their only outpost in this region is the old warship in Puerto Penasco, on the coast of the Gulf of California.}
{319}{}{What could they be doing in Arizona?}
{320}{}{Thanks. This is all that I needed.}

#about this place
{330}{}{What do you know about this town?}
{331}{}{Before the War, it was called Mexicali. A big town by the border. It was destroyed during the bombardment of surrounding  factories.}
{332}{}{Fine, forget it.}
{333}{}{What are those things that keep walking in circles here?}
{334}{}{Mexicali's residents that survived the atomic bombings of 2077. The souls of those who were once humans. I feel so very sorry for these poor people. These ruins have become their eternal hell.}
{335}{}{Understood. Let us not dwell on the tragic.}
{336}{}{Why are they building totems out of bones?}
{337}{}{They gather into something resembling animal packs. Every group has it's territory, and the totems are a kind of mark.}
{338}{}{Okay. Enough about the ghouls.}
{339}{}{Do they have weak spots? I need to know where to aim if I run into them again.}
{340}{}{Well, they are quite fast, lively and gather in groups. It's best to stay away from them. Weapons with a large area of effect may prove useful if you catch them in a tight group. But keep in mind that they were people, too, even if a long time ago.}
{341}{}{Don't worry. I'm asking in case they ambush us.}
{342}{}{Yes, they were once people. And now they're monsters that attack without hesitation. It's dumb of you to say this kind of stuff, Diana.}
{343}{}{I'm curious as to why they need totems made of bones.}
{344}{}{They are almost a hundred years old?! How?}
{345}{}{So you insist that they are almost a hundred years old?}
{346}{}{It's a long story. Are you sure you want to hear all of it?}
{347}{}{No. I'm just curious as to what they are.}
{348}{}{Yes. It may be just a story, but I would like to know more.}
{349}{}{Not too far away from here, there was a laboratory, where researchers conducted experiments with one very dangerous virus. An atomic blast damaged the complex, and so the virus broke free and enveloped roughly half of the world.}
{350}{}{[Continue]}
{351}{}{This city was quickly consumed by the poisonous cloud. The virus, combined with radiation, created a strange effect. It granted the residents effective biological immortality. But to be honest, I don't think they're too happy about that. And they're not the only product of these mutations. All the wildlife around here is, too.}
{352}{}{What was this virus?}
{353}{}{The Forced Evolutionary Virus. Secret military project. Not too long ago the Master was using it to create an entire army of supermutants. Levi's people are the result of these inhuman experiments.}
{354}{}{Judging by his unit, the virus had many side effects.}
{355}{}{The Master conducted a multitude of experiments and achieved a variety of different results. Many died until he discovered a balance. But even his best mutants have to periodically take some kind of drugs to stabilize the mutagen. And not the same drugs, either - many mutants have their own unique properties. So, to sum it all up, it is all quite complicated.}
{356}{}{I see. Thank you for telling me this.}

{360}{}{About the power armor.}
{361}{}{It was being delivered to the Puerto Penasco military base. When the ghouls ambushed the convoy, nobody had time to utilize this Pre-War technological marvel.}
{362}{}{It still works?}
{363}{}{Yeah. It was a bit shaken up during transport, but the main systems are fully operational. The problem is that some of the components were put away in different places.}
{364}{}{What exactly does this armor lack?}
{365}{}{The nuclear reactor was demounted for study. Looks like Levi is trying to find other uses for it.}
{366}{}{Anything else?}
{367}{}{Levi is holding the main processor, so that nobody can activate the armor on their own accord.}
{368}{}{Isn't there supposed to be a helmet included?}
{369}{}{The helmet was lost, likely in the place the ghouls ambushed us.}
{370}{}{I see now what I need to look for.}
{371}{}{Alright, I'll think this over.}
{372}{}{I found this helmet near a monument. Will it do?}
{1372}{}{I found this helmet near a monument. Will it do?}
{373}{}{Yes, it's the one we lost. Just connect it to the armor.}
{374}{}{Alright.}

{380}{}{What do you know about Levi and his cult?}
{381}{}{Only a bit. But enough to respect and hate him at the same time.}
{382}{}{Enough about the cult.}
{383}{}{So, who is he?}
{384}{}{Levi was once one of the Master's henchmen. He followed his leader until the very end, until the year 2161, when the cult was destroyed.}
{385}{}{He's a mutant too?}
{386}{}{Levi accepted the mutagen as part of an initiation ritual. And now he suffers from the side effects. Air is poisonous to him. That's why he wears a mask. His subordinates have no need for this.}
{387}{}{What made him go to these ruins?}
{388}{}{You see, in our time, the people of California have driven those like him away. I think Levi thought these ruins were a good place to hide from the rest of the world. After all, no normal human would ever go to a place like this. Well, except us.}
{389}{}{What does Levi want from you?}
{390}{}{He needs my scientific expertise for his "complementation project". That's how it calls this.}
{391}{}{The what?}
{392}{}{What does that even mean?}
{393}{}{It's hard to explain. Even I'm not given all the information about it. You see, Levi's people, they are the result of an old experiment. Do you want to know the details?}
{394}{}{This is no time for stories. I need to think of a way to get out of this hellhole.}
{395}{}{No, let's put the story aside. What exactly does Levi want?}
{396}{}{Yes, tell me, what are these experiments?}
{397}{}{A few years ago, the Master's cult prospered in the west. He used biotechnology from before the War to create his own personal army of supermutants. But the Master was killed before he could use it, and his army ran off in many different directions.}
{398}{}{And Levi's people are the remains of that cult?}
{399}{}{Yes. But the Master's experiments had a large spectrum of side effects, both positive and fatal. All those mutants are suffering from defects one way or the other.}
{400}{}{And so Levi is trying to cure them?}
{401}{}{First, the virus in the bloodstream of those people needs to be stabilized. Some are dying from a virus deficiency, others from an excess. They all have their own unique problems.}
{402}{}{Go on.}
{403}{}{It's interesting that Levi is trying to tame wild ghouls, make them his servants, even though their nature is quite different compared to Levi's ghouls.}
{404}{}{So, what's the goal?}
{405}{}{Some kind of a miniature empire of mutants. A radioactive heaven for the chosen few. The way will, of course, be closed for normal humans.}
{406}{}{Interesting. But let's go back a bit. What exactly does Levi want from you?}
{407}{}{Levi is demanding a stabilizer for the virus, which he could give to his flock. The problem is, some of his people need more of the mutagen, so they are forced to choose between periodically taking stimulaton drugs or tolerating the pain. Others, on the other hand, have far too much mutagen in them, and are looking for a way to supress the virus, to not be turned into a carrot.}
{408}{}{Doesn't sound like there are any easy answers here.}
{409}{}{Umm, forget it.}
{410}{}{Exactly. Luckily, Levi has brought with him a small laboratory. The issue is that there is a lack of synthesizable materials, especially benzene and pesticides. If I had more materials, I could find a solution for the mutagen problem.}
{411}{}{You're mad! You want to cure those mutants? How about spreading the poison all over this unholy cathedral?}
{412}{}{I understand why you are not happy with this. But still, I can understand them. They went through much. Perhaps my help will change them for the better.}
{413}{}{Uh-uh. I still insist on poisoning them all. If it's possible.}
{414}{}{Let us hope that you are right.}
{415}{}{If you make the mutagen, then Levi will set us free. We should try. It can't get any worse than this, anyways.}
{416}{}{Exactly. My heart swells when I try to imagine what they went through.}
{417}{}{It would be simpler to just kill 'em all. What do you need for that mutagen?}
{418}{}{Alright. But where can I get all those chemicals?}
{419}{}{I had a kit full of chemicals with me. It should have everything we need. But Levi's people couldn't find it. Maybe it's around the place where we were ambushed.}
{420}{}{Well, I'm already finding someone or something all the time.}
{421}{}{Please find this kit. The ambush was by the monument at the fifth highway. It's not too far away from here, just a bit to the west.}
{422}{}{Await my return.}
{423}{}{Alright. But be careful to not regret it.}
{424}{}{Remind me, what am I looking for?}

{430}{}{Here is the kit you were looking for.}
{431}{}{Thank god! I was afraid the ghouls trashed it. Let's have a look... Yes, this has everything we need. There are just a few tests necessary beforehand. Put it on that table...}
{432}{}{[Continue]}
{433}{}{...Well... Hm... Give me that test tube... Look, it's turning green. Now everything hinges on the small one - we need to conduct clinical tests. Luckily, we have experienced samples.}
{434}{}{You want to use the ghouls? Looks like we have no other choice.}
{435}{}{You're really sadistic, Diana. I'm beginning to like you.}
{436}{}{Hm-m... How interesting. Look how the test subjects became more calm. Let me take a look at their blood cells... Wait a minute... Hey, I think we did it! I think this is exactly what Levi wanted.}
{437}{}{Good news. I'll go speak to Levi.}
{438}{}{It just so happened that I already had your kit.}
{439}{}{Nobody had to die. I won't be able to test the mutagen's effectiveness on the dead.}

{450}{}{We're leaving.}
{451}{}{Are you sure this is the right choice? I'd hate to be caught in crossfire again.}
{1451}{}{Are you sure this is the right choice? I'd hate to be caught in crossfire again.}
{452}{}{You're right, I need to scout first. I'll be back... soon.}
{453}{}{Levi is dead. I doubt the other mutants will be particularly happy to see us.}
{454}{}{Levi is dead? How tragic... Welp, it's definitely not safe in there anymore. I doubt I'll be of any use there.}
{455}{}{Exactly. We have to get out of here. As soon as possible.}
{456}{}{Actually, I'm not exactly sure whether this is correct or not. Wait here while I check.}
{457}{}{This is dangerous. But it's becoming more dangerous here with every hour. We have to hurry if we want to survive. Let's go.}
{458}{}{I very much hope you know what you're doing.}
{459}{}{Trust me. I'll get you out of this hellhole.}
{460}{}{Hm. Your words are thought-provoking. Wait here for a bit. I'll go scout.}
{461}{}{Levi has set us free. We can go now.}
{462}{}{Thank god! I knew Levi was good at heart. He wouldn't break his word.}
{463}{}{Then pack your things. We must leave.}
{464}{}{You'll have to wait for a bit. I need some time to get ready.}

#Team
{500}{}{Where are we heading, commander?}
{501}{}{Just follow me.}
{502}{}{Where do you need to go?}
{503}{}{Casa Nueva.}
{504}{}{Why?}
{505}{}{There's an outpost set up by my brothers and sisters there. I am supposed to be helping them in the local school.}
{506}{}{Can you mark this place on my map?}
{507}{}{Of course. Show me your map first... Oh, you have a Pip-Boy. How unexpected. Relic, you say? Alright... Here. It's roughly in this spot in the Sonora desert, to the south-east.}
{508}{}{Alright. Let's go.}
{509}{}{But why do you need to go there?}

{510}{}{Diana, we must now part our ways.}
{511}{}{So soon? Ugh, I never had any luck with long-term relationships.}
{512}{}{There's nothing you can do. Give me back my things and go wherever you want.}
{513}{}{You're right. We should stick together.}
{514}{}{Enough fooling around. It's time to go.}
{515}{}{Whatever you say, captain.}
{516}{}{Let's go.}
{517}{}{I need to leave you here for just a bit. Stay here.}
{518}{}{You're not going to abandon me, my love? Fine, as you wish.}
{519}{}{Just wait here.}
{520}{}{Sorry, now I understand that I need you. Will you come with me?}
{521}{}{About the weapon. It's best to put it away.}
{522}{}{Oh, now you worry that it could harm someone. So kind of you.}
{523}{}{No sarcasm, please.}
{524}{}{No, Diana, I want to ensure my safety.}
{525}{}{Take off that armor.}
{526}{}{You aren't going to tell me to strip naked, right? Though sometimes I think about it.}
{527}{}{Um, no. I didn't mean that.}
{528}{}{You came back for me? How romantic.}
{1528}{}{You came back for me? How romantic.}

{530}{}{I was wounded. Do something!}
{531}{}{Sorry, but you'll have to push through it. Your wounds aren't serious enough to spend our last medicine on.}
{532}{}{So this is how the Followers treat their patients? Alright. I'll keep that in mind in the future.}
{533}{}{Yes, you're right. We should reserve medicine for emergencies.}
{534}{}{Your wounds aren't fatal, but the traumas will significantly impair travel. I'll have to remember what I was taught about surgery. Though, I do have a little practice ...}
{535}{}{How about you do something!}
{536}{}{I trust you, doc.}
{537}{}{My god, you're covered in blood! This is no good. Lie down, I'll have to spend the last of our medicine on you...}
{1537}{}{My god, you're covered in blood! This is no good. Lie down, I'll have to spend the last of our medicine on you...}
{538}{}{Don't let me fall asleep, doc...}
{539}{}{You'll have to push through it. Were you ever concerned for the injuries of others? That's how it feels. Perhaps you'll learn to be kinder this way.}
{540}{}{So that's how it is, then? You dump me because of bad reputation? Fine. But don't think I'll forget this. Bitch.}
{541}{}{Fine. But if I die, it will all be your fault.}
{542}{}{Look, no offense, but your lousy company will just slow us down. And I need to get to Casa Nueva as soon as possible.}
{543}{}{Then you'll get by without my help. Bye.}
{544}{}{I'll talk with them. Wait for a bit.}

{550}{}{Let's talk.}
{551}{}{What do you want to know?}
{552}{}{Nothing, forget it.}

{560}{}{Why were you so concerned when you saw my Pip-Boy?}
{561}{}{Well, it is old technology. Such computers were given to the inhabitants of special fallout shelters. I did not expect to encounter this thing away from the big cities.}
{562}{}{Yes, it's a piece of equipment from Vault 27. It's currently only inhabited by ghosts.}
{563}{}{Heh-heh. You have an interesting sense of humor.}
{564}{}{Let's continue.}
{565}{}{Wait. Do you mean the Vault he came from is somewhere in Arizona?}
{566}{}{Show me the markings on the back... Well, well, well. Yes, it is from Vault 27. I don't know where it is exactly, but I think it is located somewhere around Phoenix.}
{567}{}{Thank you, Diana. This is valuable information.}

{570}{}{What kind of weapons do you have an affinity for?}
{571}{}{I'd rather not get involved in fights. If, of course, you let me.}
{572}{}{Do you at least know why a pistol needs a trigger?}
{573}{}{Oh god... I can handle laser and plasma weaponry well, but I'm terrible with firearms and hand-to-hand combat. That good enough for you?}
{574}{}{Good enough for me.}
{575}{}{It's like traveling with a cactus.}

{580}{}{What do you think of this place?}
{581}{}{Alright.}
{582}{}{Nothing special. A typical landscape for this season.}
{583}{}{Looks like this is that city where I was supposed to get to. Let's ask the locals about the Followers.}
{584}{}{Big city. Almost like the Hub. Let's go shopping.}
{585}{}{Big city. But this region doesn't look welcoming. Be vigilant, don't let the locals fool you.}
{586}{}{Big cathedral? It reminds me of something. Look, I feel uneasy in this place. Let's get out of here as quickly as we can, okay?}
{587}{}{Oh wow, they settled in this bunker well. And the technology is in excellent condition. Amazing. Oh, if only my brothers and sisters came here, think of how many people we could help then!}
{588}{}{You kidding me? Let me wipe the rat shit off my cloak - I'll try to answer then...}
{589}{}{The town looks dreary. I feel there's something about this place the locals aren't telling us.}
{590}{}{Unbelievable! They even mastered microchipping. I need to speak to their scientists immediately... Though I doubt they would allow it.}
{591}{}{We need to get out of here. As soon as possible.}
{592}{}{The Brotherhood of Steel outpost. The very one my convoy was heading to. Let's go to the quartermaster and replenish our supplies.}
{593}{}{Before the War, this was Mexicali, a big town by the border. It was destroyed when the surrounding factories were bombarded. There were many of them here.}
{594}{}{Finally, we found something alive in this desert! But listen, I don't think they're too pleased to see us.}
{595}{}{I feel uneasy here.}
{596}{}{Don't you think we went too far away from our destination? I remind you, I need to get to Casa Nueva.}
{597}{}{What is your mission?}

#Arrival in Casa Nueva
{600}{}{We're there. Looks like the time has come to say goodbye.}
{601}{}{Yes. This is now my new home. A wonderful place - so much greenery, while beyond it lies the endless, lifeless desert. Likely the result of much effort. I'm itching to learn how they achieved this.}
{602}{}{This probably marks a new chapter in your life.}
{603}{}{Thank you so much. You're saving not only me, but the people that live here. Together, we will try to make New Home an oasis where people can live in peace and harmony.}
{604}{}{Oh, please. It was obvious from the beginning that this was the right thing to do.}
{605}{}{I'll tell my colleagues about you. Thank you once more.}
{606}{}{Goodbye, Diana.}
{607}{}{So you're leaving me without offering anything?}
{608}{}{Sorry, there isn't much I can offer. I'll try asking for locally produced medicine and food for the journey. Thank you once again.}
{609}{}{Well, at least something. Goodbye, Diana.}

{610}{}{Happy to see you.}
{611}{}{Hi. Hm. Are the locals really avoiding you, or am I just imagining it?}
{612}{}{I didn't even know. It turns out you're considered a hero here.}
{1612}{}{I didn't even know. It turns out you're considered a heroine here.}
{613}{}{I'm just here to say hi. And already I need to go.}
{614}{}{My god, what's happening here? The locals look like they went mad. Looks like there's a lot of work I'll have to do here.}