{100}{}{This is Diana.}
{101}{}{You see a bald woman with a very thoughtful look.}
{102}{}{Oh, of course, please.}
{103}{}{It's good to see you.}

{110}{}{Hey, are we here yet?}
{111}{}{A big city. Almost a Hub. Eh, brings back memories...}
{112}{}{This city is like a prison. I wonder if the locals are happy?}
{113}{}{The city of nomadic cattle breeders. That's so unexpected.}
{114}{}{This place gives me the creeps.}
{115}{}{I don't like this place. Be careful.}
{116}{}{Is this your home village? Your diligence is admirable.}
{117}{}{I can't believe my eyes. These are the legendary Desert Rangers!}
{118}{}{Don't you think we've gone too far south?}
{119}{}{Finally we got out of this hell.}
{120}{}{Hmm. It seems the locals don't like outsiders.}

#The first dialog
{200}{}{Thank God there is someone else with a human face here!}
{201}{}{Who are you?}
{202}{}{Diane. I am a Follower of the Apocalypse and am on my way to the settlement of Casa Nueva. But my convoy was attacked by rippers. I was captured and brought here. I don't even know if anyone else from my group survived.}
{203}{}{I'm really sorry, Diana.}
{204}{}{Clear.}
{205}{}{And what are you doing here? Were you captured by the rippers too?}
{206}{}{Actually, I'm here by accident. The inhabitants of my village were taken away by slavers, and I'm looking for them.}
{207}{}{Hmm. I've heard that the slave trade is developing in the east. But I don't think you'll find anyone here except mutants.}
{208}{}{So are you going to run away from here?}
{209}{}{It doesn't matter. Are you going to run away from here?}
{210}{}{The Brotherhood of Steel sent me to help.}
{211}{}{Yes, the Brotherhood never abandons its brothers and sisters. You can't blame them for that.}
{212}{}{So you're going to run away from here?}
{213}{}{I'm afraid it won't be easy to get out of here. If we try to leave the cathedral, the guards will grab us. But even if we are outside, we will be torn apart by the rippers.}
{214}{}{We need to be smarter here.}
{215}{}{Exactly. I don't want bloodshed. And Levi, it seems, too. He promised to let us go if I helped him with his research.}
{216}{}{Is there any way to fight them off?}
{217}{}{I'm not a fan of bloodshed. Levi promised to let us go if I helped him with his research. But if you really crave battle, then you can't do without power armor here.}
{218}{}{I need to assess the situation and think.}
{219}{}{}
{220}{}{Sure. But don't leave me. The children of Casa Nueva are waiting for my biology lessons.}
{221}{}{Okay...}

#Repeat dialog
{250}{}{So what? What's your plan?}
{251}{}{Wait for my instructions.}
{252}{}{What does Levi say?}

{260}{}{Tell me what's going on here.}
{261}{}{OK. What exactly do you want to know?}
{262}{}{Perhaps that's all.}

#- about your mission
{270}{}{I'm interested in your mission.}
{271}{}{I was going to Casa Nueva. This settlement needs scientists and teachers. Several Followers are already doing some research there.}
{272}{}{Perhaps that's all.}
{273}{}{Can you show me where it is?}
{274}{}{Sure. Open your card, I'll show you...}
{275}{}{Thank you.}
{276}{}{I happened to visit this city. Nice place.}
{277}{}{Really? Great. The faster I want to get there.}
{278}{}{We'll come back to that later... If we get out of here.}
{279}{}{Casa Nueva was built by slaves, and peons work on the plantations there. Scientists are parasitic on someone else's work.}
{280}{}{Yes, it is difficult to combine science and manual labor. And, of course, it is wrong to oppress someone. But we strive to make the world a better place. Besides, slaves were not used by us, but by the mercenaries of the Brotherhood of Steel.}
{281}{}{Okay, that sounds convincing.}
{282}{}{Yeah, like that changes anything.}

{290}{}{Who are these Followers of the Apocalypse?}
{291}{}{Well, we are something like a charitable foundation. We teach people to read and write, treat diseases and enlighten them with pre-war knowledge.}
{292}{}{So you want to bring back the Old World?}
{293}{}{Not quite. They say history repeats itself, but it doesn't copy itself at every turn. In other words, the Old World cannot be returned as it was. Yes, it is not necessary.}
{294}{}{Ugh, I thought you were crazy.}
{295}{}{I see.}
{296}{}{You're crazy! The old World fell because of this very knowledge.}
{297}{}{I do not think so. It's not about knowledge, it's about using it. We make sure that no one repeats the mistakes of the Old World.}
{298}{}{Well, well. As if you can keep track of everyone.}
{299}{}{Your goals are noble and pure. I hope others understand them the same way.}
{300}{}{How did you get ambushed?}
{301}{}{We were attacked by rippers. They set up an ambush, created a dust curtain and pulled me out of the group. I was rescued by Levi's men, who happened to be nearby, and then brought here.}
{302}{}{And you're still thanking him for that?}
{303}{}{I don't believe these people are bad at heart. Levi is just following the path that seems right to him. And besides, he has to do it.}
{304}{}{What about your companions?}
{305}{}{So the Rippers were acting on Levi's orders?}
{306}{}{Probably, yes. Levi is a kind of god for them... or the devil. They try to please him and follow simple orders. But these are just my guesses.}
{307}{}{And what happened to your companions?}
{308}{}{The squad consisted of several members of the Brotherhood of Steel. The squad was led by Paladin Barkley. After I was kidnapped, I didn't hear anything about them. I don't know if they're alive or dead.}
{309}{}{Clear.}

{310}{}{You mentioned the Brotherhood of Steel. Tell me about him.}
{311}{}{Well, it's a closed military organization in California. The Followers have strained relations with them, so I was taken into the convoy with great dissatisfaction.}
{312}{}{What are they doing?}
{313}{}{Mostly nothing. But lately the Brotherhood is clearly lacking energy. They started buying up all the nuclear batteries in the region. They are also the best specialists in energy weapons and high pre-war technologies. But they keep almost all of this for themselves and do not want to share it with the outside world.}
{314}{}{I see. Enough about this Brotherhood.}
{315}{}{Then what are they doing in Arizona?}
{316}{}{I think they are also collecting technologies and energy sources. There are many untouched pre-war sites left in Arizona.}
{317}{}{Do you know where their base is?}
{318}{}{Their only outpost is on an old warship in Puerto Penasco, on the Gulf coast of California.}
{319}{}{What are they doing in Arizona?}
{320}{}{Thank you. That's what I needed.}

# about this city
{330}{}{What do you know about this city?}
{331}{}{Before the War it was called Mexicali. A large border town. The Reds destroyed it when they bombed numerous local factories.}
{332}{}{Okay, whatever.}
{333}{}{About these rippers. Who are they?}
{334}{}{These are Mexicali residents who survived the nuclear bombing in 2077. The souls of those who were once human. I am immensely sorry for these poor people. For them, the ruins have become an eternal hell.}
{335}{}{I see. Let's not talk about the sad.}
{336}{}{Why do they build totems out of bones?}
{337}{}{The Rippers gather in a kind of animal pack. Each group has its own territory assigned to it, and totems are a kind of label.}
{338}{}{I see. Enough about the rippers.}
{339}{}{Do they have weaknesses? I need to know where to aim if I run into them again.}
{340}{}{Well, they are pretty fast, tenacious and often gather in a pack. It will be better to keep a long distance from them. And against the crowd, weapons of mass destruction have always been the most effective. But don't forget that they were once people too.}
{341}{}{Don't worry, these are notes in case of an ambush.}
{342}{}{Are you protecting these animals? You're stupid, Diana.}
{343}{}{I wonder why they need bone totems?}
{344}{}{They are almost a hundred years old?! How so?}
{345}{}{Are you saying they're almost a hundred years old?}
{346}{}{It's an old story. Do you want to hear it in its entirety?}
{347}{}{No. I'm just wondering who they are.}
{348}{}{Yes. Let it be just a story, but I want to know.}
{349}{}{Not far from here there was a laboratory where experiments were carried out with a very dangerous virus. A nuclear explosion damaged the complex, as a result, the virus broke free and flew around half the world.}
{350}{}{Go on.}
{351}{}{This city was quickly covered by a poisonous cloud. The virus combined with radiation had a strange effect, giving the inhabitants immortality. However, I don't think they are happy about it. And by the way, not only ghouls were the result of mutation, but also all the wild animals in the area.}
{352}{}{What kind of virus was it?}
{353}{}{The Virus Of Man-Made Evolution. Secret military development. Already in our time, the Creator used VRE to create an army of super mutants. Levi's people are the result of these inhuman experiments.}
{354}{}{Judging by his squad, the virus had many side effects.}
{355}{}{The creator conducted many experiments and got different results. Many died before he came to balance. But even his best mutants have to periodically take some substances to stabilize the mutagen. In addition, many mutants have their own unique features. In general, everything is very complicated.}
{356}{}{I see. Thanks for the story.}

{360}{}{About the power armor.}
{361}{}{She was being taken to a military base in Puerto Penasco. When the rippers attacked the convoy, no one had time to use this miracle of pre-war technology.}
{362}{}{Is she still working?}
{363}{}{Almost. During transportation, it was a little battered, but the main systems are normal. The problem is that some parts were stolen in different corners.}
{364}{}{What exactly is missing in this armor?}
{365}{}{The nuclear reactor was dismantled for study. Apparently, Levi is considering alternative options for using this energy source.}
{366}{}{Something else?}
{367}{}{Levy keeps the main processor with him so that no one can launch the armor without permission.}
{368}{}{Does the helmet come with this car?}
{369}{}{The helmet was completely lost somewhere during transportation. Most likely, it lies where the ghouls attacked us.}
{370}{}{Now it's clear what to look for.}
{371}{}{Okay, I'll think about it.}
{372}{}{I found this helmet near the monument. Will he do?}
{1372}{}{I found this helmet near the monument. Will he do?}
{373}{}{Yes, that's him. Just connect it to the armor.}
{374}{}{OK.}

{380}{}{What do you know about Levi and his cult?}
{381}{}{Quite a bit. But it's enough to respect and hate him at the same time.}
{382}{}{Enough about the cult.}
{383}{}{Who is he?}
{384}{}{Levi was one of the minions of the Creator, like Morpheus and other close associates. He followed his leader to the end until the cult was destroyed in 2161.}
{385}{}{Is he a mutant too?}
{386}{}{Levi accepted the mutagen as part of the initiation. And now he's suffering from side effects. Therefore, he wears a mask to reduce the harmful effects of poisonous air. Although his subordinates don't need it.}
{387}{}{What brought him to these ruins?}
{388}{}{You see, these days the people of California have expelled people like him. I think these ruins seemed to Levi a reliable Vault from the rest of the world. After all, no normal person would climb into such radioactive dirt. Well, except for you and me.}
{389}{}{What does Levi want from you?}
{390}{}{He needs my scientific skills for the "complementation project". That's what he calls it.}
{391}{}{Project of what?}
{392}{}{Complementation project - what does it mean?}
{393}{}{It's hard to explain, and I wasn't privy to everything. You see, Levi's people are the fruit of an old experiment. Do you want to know the details?}
{394}{}{I'm not up to history right now. We need to think about how to get out of this hell.}
{395}{}{No, let's skip the story. What exactly does Levi need?}
{396}{}{Yes, tell me, what kind of experiments?}
{397}{}{A few years ago, the cult of the Creator flourished in the West. He used the pre-war virus to create his own army of super mutants. The Creator was killed, and his army fled in different directions.}
{398}{}{Levi's people are the remnants of this cult?}
{399}{}{Right. But the Creator's experiments had a very wide range of consequences. Both successful and fatal. All these mutants suffer from defects in one way or another.}
{400}{}{And Levi is trying to heal them?}
{401}{}{To begin with, it is necessary to stabilize the virus in the blood of these people. Some of them are wasting away from the lack of the virus, others from its excess, and all have their own individual pathologies.}
{402}{}{Go on.}
{403}{}{It is also curious that Levi is trying to tame wild rippers, make them his servants, although their nature is significantly different from Levi's ghouls.}
{404}{}{And what will happen in the end?}
{405}{}{Something like a small mutant empire. A radioactive paradise for the elite. The path here will be closed to a mere mortal.}
{406}{}{Interesting. But let's go back. What exactly does Levi want from you?}
{407}{}{Levi demands a virus stabilizer for his flock. The fact is that some of his people lack mutagen, so they are forced to take stimpack medications or endure pain. Others, on the contrary, are looking for a way to suppress the virus so as not to turn completely into a carrot.}
{408}{}{Sounds too difficult, given the surrounding mess.}
{409}{}{Um, forget it.}
{410}{}{Exactly. Fortunately, Levi brought a small laboratory with him. The main problem is the lack of synthesized substances, especially benzene and pesticides. If I had more raw materials, I would have found a solution to the mutagen problem.}
{411}{}{Crazy! Do you want to cure these mutants? How about spraying mutagenic poison all over this devil's church?}
{412}{}{I understand your displeasure. And yet these people can also be understood. They've been through a lot. Perhaps my help will change them for the better.}
{413}{}{Well, well. And yet I insist on poison. If possible.}
{414}{}{Perhaps. I really hope that you are not mistaken in your calculations.}
{415}{}{If you make a mutagen, then Levi will let us go. It's worth a try. It won't get any worse anyway.}
{416}{}{Exactly. My heart sinks when I try to imagine what these people went through.}
{417}{}{Although it would be easier to shoot them all. And what is needed there for the mutagen?}
{418}{}{Okay. But where can I get all these substances?}
{419}{}{I was carrying a chemical bag with me. There was everything you needed. But Levi's men could not find him. Surely one of the rippers dragged the box to the ruins.}
{420}{}{Well, I'm always looking for someone or something.}
{421}{}{Please find this box. The ambush was near the monument on the fifth highway. It's not far west of here.}
{422}{}{Wait for my return.}
{423}{}{Okay. But don't regret it.}
{424}{}{Remind me what I need to find?}

{430}{}{Here's your chemical kit.}
{431}{}{Thank god! I was already afraid that the ghouls had gutted him. So... Yes, there is what you need here. First you need to conduct some experiments. Put the kit on that lab table over there...}
{432}{}{[Next]}
{433}{}{... so... hmm... Hand me that test tube over there... Look, it's turning green. Now it's a small matter - we need to conduct clinical trials. Fortunately, we have prototypes.}
{434}{}{Do you want to use those rippers? It looks like we have no other choice.}
{435}{}{You're a real sadie, Diana. And I'm starting to like you.}
{436}{}{Hmm-m... How interesting. Please note that the test subjects have become calmer. Now I'm going to look at their blood cells through a microscope... so... Hey, we did it! I think this is exactly what Levi wanted.}
{437}{}{Good news. I'll talk to Levi.}
{438}{}{It so happened that I already have your things.}
{439}{}{There is no need to kill anyone. I won't be able to test the mutagen on the dead. }

{450}{}{Get ready. We're leaving.}
{451}{}{Are you sure this is the right thing to do? I wouldn't want to be caught in the crossfire again.}
{1451}{}{Are you sure this is the right thing to do? I don't want to be caught in the crossfire again.}
{452}{}{You're right, we need to scout the situation first. I'll be back soon.}
{453}{}{Levi is dead. I doubt that the rest of the mutants will be happy to see us as well.}
{454}{}{Is Levi dead? How sad it is... Well, it's really not safe in the temple now. I doubt that I will be of any use here.}
{455}{}{Exactly. We need to get out of here. And as soon as possible.}
{456}{}{Actually, this is not accurate information. Wait until I check.}
{457}{}{It's dangerous. But it's getting more dangerous by the hour. We must hurry if we want to survive. Let's go.}
{458}{}{I really hope you know what you're doing.}
{459}{}{Trust me. I'll get you out of this hell.}
{460}{}{Hmm. Your words make me think. Wait a little longer. I'm on a reconnaissance mission.}
{461}{}{Levi gave us freedom. We can leave.}
{462}{}{Thank god! I believed that Levi was a good man and he would keep his word.}
{463}{}{Then pack your things. We have to go.}
{464}{}{We'll have to wait a little longer. I need to get ready for the road.}

#Party
{500}{}{Where are we going, Commander?}
{501}{}{Just follow me.}
{502}{}{And where do you need to go?}
{503}{}{To the city of Casa Nueva.}
{504}{}{Why?}
{505}{}{There is an outpost of my brothers and sisters there. I have to help them at the local school.}
{506}{}{Can you show this place on the map?}
{507}{}{Sure. Open your card... Oh, you have a PipBoy. What a surprise. A relic, you say? Okay... so. It's right here in the Sonoran desert, in the southeast.}
{508}{}{Clear. Let's go.}
{509}{}{But why do you need to go there?}

{510}{}{Diana, we have to break up.}
{511}{}{So soon? Eh, I've always been unlucky in a long-term relationship.}
{512}{}{Nothing can be done. Return my things and go wherever you want.}
{513}{}{You're right. We'd better stick together.}
{514}{}{Stop hanging around. We have to go.}
{515}{}{Whatever you say, Captain.}
{516}{}{Come on.}
{517}{}{I need to leave you for a while. Wait here for now.}
{518}{}{You're not going to leave me, are you, my love? Okay, have it your way.}
{519}{}{Just wait here.}
{520}{}{I'm sorry, now I understand that I need you. Will you come with me?}
{521}{}{About the weapons. It's better to hide it.}
{522}{}{Oh, now you're worried about hurting someone. That's so sweet of you.}
{523}{}{Can I not be sarcastic?}
{524}{}{No, you fool, I want to protect myself.}
{525}{}{Take off this armor.}
{526}{}{You're not going to strip me naked, are you? Although sometimes I want to feel free.}
{527}{}{Um, I don't really mean that.}
{528}{}{Did you come back for me? How romantic it is.}
{1528}{}{Did you come back for me? How romantic it is.}

{530}{}{I was wounded. Do something!}
{531}{}{I'm sorry, but you'll have to be patient. Your wounds aren't serious enough to waste our last medicines.}
{532}{}{So this is how Followers treat patients? I'll keep that in mind for the future.}
{533}{}{Yes, you're right. It is worth saving medicines as a last resort.}
{534}{}{Your wounds are not fatal, but injuries will greatly interfere with the journey. We'll have to remember the course of surgery. However, I have little practice...}
{535}{}{Yes, do something already!}
{536}{}{I trust you, Doc.}
{537}{}{My God, you're covered in blood! This is no good. Go to bed, I'll have to spend the last medicines on you...}
{1537}{}{My God, you're covered in blood! This is no good. Go to bed, I'll have to spend the last medicines on you...}
{538}{}{Don't let me fall asleep, Doc...}
{539}{}{We'll have to be patient. You didn't care about the wounds of others, did you? Feel what it's like. Maybe that's how you'll learn kindness.}
{540}{}{That's it, then? Did you decide to leave me because of my bad reputation? La-adno, I'll remember that, bitch.}
{541}{}{Okay. But if I die, it will be on your conscience.}
{542}{}{Look, I don't want to offend anyone, but your noisy company will slow us down. And I need to get to Casa Nueva as soon as possible.}
{543}{}{Then you can do without my help. Bye.}
{544}{}{I'll talk to them. Wait a bit.}

{550}{}{Let's talk.}
{551}{}{What do you want to know?}
{552}{}{Never mind, forget it.}

{560}{}{Why are you so excited about my Peep Fight?}
{561}{}{Well, it's an old technology. Such computers were distributed to residents of special bomb Vaults. I didn't expect to find this thing far from major cities.}
{562}{}{Yes, this is a device from Vault 27. There are only ghosts there now.}
{563}{}{Haha, good joke.}
{564}{}{Let's keep going.}
{565}{}{Wait. Do you mean his native hideout is somewhere in Arizona?}
{566}{}{Show me the markings on the back... right. Yes, it's from Vault 27. I don't know for sure, but I think the bunker is probably located somewhere near Phoenix.}
{567}{}{Thank you, Diana. This is valuable information.}

{570}{}{What weapons do you own best?}
{571}{}{I'd rather not get into any fights at all. If, of course, you let me.}
{572}{}{Do you even know why a gun needs a trigger?}
{573}{}{Oh, my God... Well, I'm good with laser and plasma weapons, but I'm very bad at shooting firearms and even more so at fighting with my hands. Is that okay with you?}
{574}{}{That's enough.}
{575}{}{It's like traveling with a cactus. Everything is clear with you.}

{580}{}{What do you think about this place?}
{581}{}{I see.}
{582}{}{Nothing remarkable. The usual landscape for this season.}
{583}{}{This must be the city where I'm supposed to arrive. Let's ask the locals about Followers?}
{584}{}{A big city. Almost a Hub. Let's go shopping?}
{585}{}{A big city. But this area looks unfriendly. Be on your guard, don't let the locals fool you.}
{586}{}{A big church? It reminds me of something. Look, I'm not comfortable here. Let's leave quickly?}
{587}{}{Wow, they are well settled in this bunker. And the equipment has been preserved in excellent condition. Amazingly. Oh, if my brothers and sisters had come here, how many people would we have been able to help then!}
{588}{}{Are you kidding? Let me just wipe the rat droppings off my raincoat and I'll try to answer you...}
{589}{}{The town looks dreary. In such places, locals often keep some terrible secrets.}
{590}{}{Unbelievable! These people have even learned microchipping. I urgently need to talk to their scientists... However, I doubt they will talk to me.}
{591}{}{We need to get out of here. And as soon as possible.}
{592}{}{An outpost of the Brotherhood of Steel. The one where my convoy was heading. Shall we go to the quartermaster to restock?}
{593}{}{Before the War, it was a large border town of Mexicali. The Reds destroyed it when they bombed local factories. There were many of them here.}
{594}{}{We've finally found something alive in this desert! But listen, it seems we're not welcome here.}
{595}{}{I'm not comfortable with this place.}
{596}{}{Don't you think we've gone too far from our intended goal? Let me remind you that I need to get to Casa Nueva.}
{597}{}{What is your mission?}

#Coming to Casa Nueva
{600}{}{We're here. I think it's time to say goodbye?}
{601}{}{Yes. This is my new home now. It's an amazing place - so much greenery, and there's an endless desert around. Surely this is the fruit of a huge effort. And I'm already eager to find out how they achieved this.}
{602}{}{A new stage in your life begins for you.}
{603}{}{Thank you very much. You are saving not only me, but also the people who live here. Together we will try to make the New House an oasis where people will live in peace and harmony.}
{604}{}{Yes, please. It immediately became clear to me that this was the right thing to do.}
{605}{}{I'll tell my brothers about you. Thanks again.}
{606}{}{Goodbye, Diana.}
{607}{}{And what, will you let me go with nothing like this?}
{608}{}{Sorry, I can't offer much. I'll try to get you some locally produced medicines and food for the road. Thanks again.}
{609}{}{Well, at least something. Goodbye, Diana.}

{610}{}{Nice to see you.}
{611}{}{Hi. Hmm. It seems to me, or are the locals really avoiding you?}
{612}{}{I didn't know. It turns out that you are considered a hero here.}
{1612}{}{I didn't know. It turns out that you are considered a heroine here.}
{613}{}{I'm just saying hello. We have to run already.}
{614}{}{Good God, what's going on here? The locals went crazy. Looks like I'm going to get a lot of work here.}