{100}{}{In front of you is Shrunken.}
{101}{}{This withered creature stares at you with distraught eyes.}
{102}{}{I will eat you and become stronger... but I'm so disgusted with myself for it.}
{103}{}{The shrunken one attacked you when you turned your back on him!}
{104}{}{My horn is starting to hurt. You better go!}

{110}{}{Pain... How painful...}
{111}{}{The pain is gone... Now I feel weak...}

{200}{}{(In front of you is a creature in rags, vaguely resembling a human. His crazy eyes are frightened and at the same time greedily looking at you)}
{201}{}{Ah, the demon! Die! Die!}
{202}{}{Wait, I won't hurt you. Who are you, man?}
{203}{}{Stop, you freak. Tell me who you are.}
{204}{}{(grabs his head; you notice several horny appendages on his head)}
{205}{}{Are you a local?}
{206}{}{Speak when someone is talking to you.}
{207}{}{(gets up and looks around) That's right. But you? Where are you from? I haven't seen a normal person for a long time. And these clothes... I remember. Yes. It was given to residents of Vaults. (walks around, examining you) I wasn't in the Vault. That's why I'm here.}
{208}{}{Wait a minute, my friend. I have a lot of questions for you.}
{209}{}{Sit tight, freak. Just throw something out and I'll shoot you to hell.}

{220}{}{(bottlecaps his face with his hands) What do you want? The city is destroyed. There's no one here. Go away.}
{221}{}{Okay, I'm leaving. Don't try to follow me.}
{222}{}{(gets up and looks around) That's right. But you? Where are you from? I haven't seen a normal person for a long time. Since then... (walks around, examining you) Ever since people took refuge in Vaults. And I didn't have enough space there, so I'm here.}

# About myself
{230}{}{Who are you? Are you a demon?}
{231}{}{Demon? (looks away) Or maybe so... I was a human once... I was a farmer. I poured milk on the ground so that prices would not fall on it. I was burying potatoes and vegetables in the ground... How stupid.}
{232}{}{Is there anyone else here besides you?}
{233}{}{Is this where your farm was, among these ruins?}
{234}{}{How did you manage to survive?}
{235}{}{Survive? No. This is not life. This is hell. We all live in hell. We can't die. Radiation has made us like this. This is our punishment. Someone was lucky to be in the epicenter of nuclear explosions. But I don't.}
{236}{}{What happened to the other survivors?}
{237}{}{It was a big city here, wasn't it?}
{238}{}{And now what are you doing? It doesn't look like there was a lot of harvest here.}
{239}{}{There's no food here! We used to eat what we found in the ruins. And now we eat each other. But rarely. We are used to hunger.}
{240}{}{So there are others here... like you?}
{241}{}{No wonder - there are only city ruins around.}
{242}{}{Farm, you say? Wait a minute, when was that?}
{243}{}{It was a long time ago. When the bombs fell on the city. You weren't there yet.}
{244}{}{Did you really see the Great War with your own eyes?}
{245}{}{Did anyone else survive that inferno besides you?}
{246}{}{By the way, what kind of city was here before?}
{247}{}{That's not what I wanted to hear at all. Let's talk about something else.}

# About packs
{250}{}{There aren't many of us left. But even now we have a division into rich demons and poor ones like me. The rich glow in the dark. They keep everyone else in check and take all the best.}
{251}{}{[Listen]}
{252}{}{They used to be important and influential. And now that they have become demons, they are also crushing the others under them. (laughs) Okay, let it be as they want. Let them shine, let them live forever in torment.}
{253}{}{[Next]}
{254}{}{This is hell, worse than death. They can't die. Even if they really want to. This is their punishment - immortality. Tormented by their sins, they must suffer forever.}
{255}{}{Are you a demon too? Like those glowing ones?}
{256}{}{But what is this cursed place that converts people so much?}
{257}{}{So you were kicked out of the pack? Is that why you're so skinny?}
{258}{}{The pack divides the food. You can't survive here alone. And the glowing ones take all the best for themselves. And when there is no food at all, they eat the weakest... like me. I will be eaten, and I will be freed from torment. But I don't want to be eaten. That's why I'm hiding.}
{259}{}{Something is becoming clear to me. But let's change the subject.}
{260}{}{So there aren't any normal people here, are there?}
{261}{}{Oh, I know, I know! Someone lives in a mansion. The lights are on there in the evening. But I didn't see who it was. Many people want to get there, but they can't.}
{262}{}{Do you know a safe way to this mansion?}
{263}{}{I could show. But they'll eat me there. And they'll eat you, too. But if you want... if you want, go through the sewer. This is the safest way.}
{264}{}{How interesting. But you probably know something else.}
{265}{}{Who else lives on these ruins besides you?}
{266}{}{What kind of city is this?}

# About the city
{270}{}{(looks around for a long time) A long time ago there was a big city here. It was called Mexicali. A beautiful city. Then the atomic bombs fell...}
{271}{}{[Listen]}
{272}{}{They turned it into fields of burnt garbage and scrap metal. The Reds did it. They were aiming at aircraft factories, but... they destroyed everything else, too. Now, because of the radioactive fallout, there is no life left here. Even the grass doesn't grow.}
{273}{}{[Next]}
{274}{}{Everything here is infected with radiation. It's because of her such mutations as I have.}
{275}{}{But how did you manage to survive in that inferno?}
{276}{}{So you're not alone here? Are there other survivors living in the ruins?}
{277}{}{Why is this city destroyed? Was there some kind of war?}

# About the War
{280}{}{Stupid people did it. They turned the planet into a waste dump, spent all the oil and began to take the last crumbs from each other. The cities and nature that we loved so much have disappeared from the face of the Earth.}
{281}{}{[Listen]}
{282}{}{Recently I saw a giant ant. There have never been such. This is not right. There must be ants... ma-scarlet. Less than a nail on your little finger. But they are not like that.}
{283}{}{[Next]}
{284}{}{It's because of the fallout... Shh! Do you hear that? It's the demons howling in pain. When night comes, all the demons get hurt.}
{285}{}{Are these demons the other survivors?}
{286}{}{Tell me, what was this city like before the bombing?}
{287}{}{So, let's stop here so that this information settles down in my head.}
{288}{}{And you? Are you a demon too?}
{289}{}{Are you the only survivor? Is there anyone else here?}

{300}{}{Have you seen the Brotherhood of Steel squad? He had to go down this road.}
{301}{}{Oh, oh, my head hurts! How painful...}
{302}{}{Don't mess with my balls. Tell me what happened to the convoy!}
{1302}{}{These tricks don't work on me. Tell me what happened to the convoy!}
{303}{}{Sorry, but this is very important. Try to remember.}
{304}{}{Ah, those pale-skinned people couldn't get out of our underworld. Gee, like the others, they will have to burn here forever.}
{305}{}{So are they alive?}
{306}{}{They are kept in the old church. But you can't go there, hehe. No, no, don't pass! There are crowds of demons around and no one knows what's going on inside. This is a cursed place, the lair of Lucifer himself. No one came back from there.}
{307}{}{It looks like getting there won't be easy...}