{100}{}{You see the Withered.}
{101}{}{This withered creature stares at you with maddened eyes.}
{102}{}{I'll eat you and become stronger... but you have no idea how disgusted I am with myself for that.}
{103}{}{The Withered attacked you when you turned your back on him!}
{104}{}{My horn's hurting. You better go!}

{110}{}{It hurts... so much...}
{111}{}{The pain has left me... Now I feel... weak...}

{200}{}{(You see a creature in ragged clothes that slightly resembles a human, but only slightly. It's maddened eyes are examining you. You see in them both desire and fear)}
{201}{}{A-aa, demon! Die! Die! Die!}
{202}{}{Wait, I won't hurt you. Who are you, human?}
{203}{}{Stop, uglie. Tell me who you are.}
{204}{}{(grabs his head; you notice several horny processes on it)}
{205}{}{You a local?}
{206}{}{Talk when you are asked something.}
{207}{}{(stands up and looks around) Yes. But who are you? Where are you from? I haven't seen a normal human in a long time. And these clothes... I remember. Yes. It was given to Vault dwellers. (walks around, examining you) I wasn't in a Vault. That's why I'm here now.}
{208}{}{Wait, friend. I have a lot of questions for you.}
{209}{}{Sit tightly, uglie. You vomit something up - I'll shoot you back to hell.}

{220}{}{(hides face with hands) What do you want? The town's destroyed. No one is here. Go.}
{221}{}{Fine, I'm leaving. Don't even think of going after me.}
{222}{}{(stands up and looks around) Right. But you? Where are you from? I haven't seen a normal human in a long time. Ever since... (walks around, examining you) Since the people hid in the Vaults. They didn't have enough space to fit me, so I'm here.}

#About himself
{230}{}{Who are you? Are you some kind of demon?}
{231}{}{Demon? (looks away) Maybe... Once, I was human... I was a farmer. I poured milk on the earth, so that prices wouldn't fall. I buried potatoes and vegetables in the ground... How stupid I was.}
{232}{}{Is there anyone else here other than you?}
{233}{}{Was your farm right here, amidst these ruins?}
{234}{}{How did you manage to live?}
{235}{}{Live? No. This isn't life. It's hell. We all live in hell. We can't die. The radiation did that. It's our punishment. Some were lucky enough to be in the center of the atomic blasts. I wasn't.}
{236}{}{What happened to the other survivors?}
{237}{}{This used to be a big city, right?}
{238}{}{What is it you do here? Doesn't look like there is much place to grow crops here.}
{239}{}{There is no food here! In the past, we used to eat whatever we would find in the ruins. Now we eat each other. But rarely. We're used to the hunger now.}
{240}{}{So there are others here... others like you?}
{241}{}{No wonder - there are only city ruins around this place.}
{242}{}{Farm, you say? Wait, when was that?}
{243}{}{It was a long time ago. When the bombs dropped. You weren't alive then.}
{244}{}{Did you really see the Great War unfold with your own eyes?}
{245}{}{Did anyone other than you survive that hell?}
{246}{}{By the way, what was that city like?}
{247}{}{This is exactly not what I wanted to hear. Let's talk about something else.}

#About the packs
{250}{}{There are not too many of us. But even now there is division into the rich demons and poor ones, like me. The rich ones glow in the dark. They keep all the others in check and take the best things.}
{251}{}{[Listen]}
{252}{}{Once, they were important and influencial. And now, when they became demons, they rise above others in exactly the same manner. (laughs) Fine, let it be so, like they want. Let them glow, let them live forever in agony.}
{253}{}{[Continue]}
{254}{}{This is hell, eternal torment. After all, they can't die. Even if they very much want to. Their punishment is immortality. Suffering for their sins, they must do so for all eternity.}
{255}{}{You a demon too? Like those glowing ones?}
{256}{}{What is this damned place that turns people into such things?}
{257}{}{Were you driven out of your pack? Is this why you're so thin?}
{258}{}{The pack distributes the food. You can't survive here alone. And the glowing ones take the best for themselves. When there is no food at all, they eat the weak... like me. I'll be eaten, I'll be free from the suffering. But I don't want to be eaten. This is why I hide.}
{259}{}{The situation has become clearer. But let's change the topic.}
{260}{}{So there are no normal people here, yes?}
{261}{}{Oh, I know, I know! Someone lives in the Mansion. There's light there during the evenings. But I haven't seen who it is. Many want to get there, but can't.}
{262}{}{Do you know a safe route to this mansion?}
{263}{}{I could show it. But I would be eaten there. You too. But if you really want to... if you want to, go through the sewers. It's the safest way.}
{264}{}{How interesting. But you clearly know something else.}
{265}{}{Who else inhabits these ruins other than you?}
{266}{}{What is this city?}

#About the town
{270}{}{(spends a long time looking around) Very long ago, there was a big city here. It was called Mexicali. Very good town. Then the atomic bombs fell...}
{271}{}{[Listen]}
{272}{}{And turned it into fields of burnt junk and scrap metal. The reds did it. They were targeting the aircraft factories, but... they destroyed everything else, too. Now, because of the radiation, there is no life here. Not even grass grows here.}
{273}{}{[Continue]}
{274}{}{Everything here is irradiated. It is the cause of those mutations, like the ones you see on me.}
{275}{}{But how did you survive in that hell?}
{276}{}{So you are not alone here? Other survivors live in the ruins?}
{277}{}{Why is the city destoyed? Was there some kind of war?}

#About the War
{280}{}{It was done by stupid men. They turned the planet into a landfill, used up all the oil and then started taking from each other the last crumbs left. Cities and nature itself, which we loved so much, dissapeared from the face of the Earth.}
{281}{}{[Listen]}
{282}{}{Recently I saw a giant ant. They never existed before. This isn't right. Ants are supposed to be... small. Less than the nail on your little finger. But they aren't now.}
{283}{}{[Continue]}
{284}{}{It's because of the radioactive... Shush! You hear this? The demons are howling from pain. When night comes, pain comes to visit all the demons.}
{285}{}{Are these demons the remaining survivors?}
{286}{}{Tell me, what was the town like before the bombardment?}
{287}{}{Let's stop here, so that this information makes it's way to my brain and isn't instead forgotten.}
{288}{}{What about you? Are you a demon too?}
{289}{}{Are you the only one that survived? Is there anyone else here?}

{300}{}{Did you see a unit from the Brotherhood of Steel? It should have passed through this region.}
{301}{}{Ugh, oh, my head! So painful...}
{302}{}{These tricks don't work on me. Tell me what happened to the convoy!}
{1302}{}{These tricks don't work on me. Tell me what happened to the convoy!}
{303}{}{Sorry, but this is very important. Try to remember.}
{304}{}{Ah, these paleskins couldn't get out of our underworld. Uuh-uuh, they'll have to burn here forever, like the rest.}
{305}{}{So they're alive?}
{306}{}{They're being held in the old church building. But you won't be able to get there, heh-heh. No-oo, you shall not pass! Entire crowds of demons surround it and no one knows what's going on inside. It's a damned place, the lair of Lucifer himself. No one who came in came out.}
{307}{}{Looks like getting there will be hard...}