{100}{}{You see Garret.}
{105}{}{Bastards! You'll pay for the deaths of my comrades!}

{200}{}{What? Another normie? That came to us willingly? Oh-hoh-hoh, we are very lucky today.}
{201}{}{Where am I? Who are you?}
{202}{}{Are you wearing a "big fat troll" costume or something?}
{203}{}{Put your weapon away and follow me. Levi will speak with you.}
{204}{}{Okay. Bring me to Levi. I want to ask him a couple of questions.}
{205}{}{No, you big dumb mutant, I'll only speak with you.}
{206}{}{I'm telling you - go to Levi. If you resist, I'll break your legs, bring you to him, and throw you on the floor like an old rag.}
{207}{}{Alright, I'm going, just don't hurt me.}
{208}{}{Just try and touch me, fat uglie.}
{209}{}{I am asking to be heard. I come in peace.}
{1209}{}{I am asking to be heard. I come in peace.}

{210}{}{What do you want, normie?}
{211}{}{Nothing, for now.}
{212}{}{Yes, sir.}

{220}{}{Let's talk. What's your name?}
{221}{}{My name is Garret. And I don't talk with normies.}
{222}{}{My name is Garret. And I don't trust normies.}
{223}{}{}
{224}{}{Alright. It's good that we managed to introduce ourselves to each other. Bye.}
{225}{}{Why? Something happened in your past?}
{226}{}{You better shut up before I get angry.}
{227}{}{Your subordinates don't want to talk too much, either. Where is all this hate for humans coming from?}
{228}{}{Hate? No. The Master taught us to treat every living thing with respect. But those like you drove us from the western territories. So if you don't shut up, I'll gladly allow myself to do what I want with you.}
{229}{}{Okay...}
{230}{}{Were you always so... unusual?}
{231}{}{Once, I was human, like you. I remember my emotions - fear, hate and envy. But the Master showed me a new way, and I got rid of my human flaws. But then, the normies took the Master away from me.}
{232}{}{Sorry, I see this question irritates you. I better go.}
{233}{}{When you say "new way", do you mean talking the mutagen?}
{234}{}{The mutagen is part of a big ritual. It's almost a year long. I prepared - fasted, meditated in ruins, trained my body and will. The mutagen is not given to those unworthy of it.}
{235}{}{Looks like you went through much. It's time for me to deal with my own problems. Bye.}
{236}{}{Who is this Master?}
{237}{}{Who is this Master fellow you all keep talking about?}
{238}{}{It is my God.}
{239}{}{This... doesn't explain much.}
{240}{}{Ha-ha, stupid normie. You will never see God. Those like you have killed him.}
{241}{}{Killing God? Is that even possible?}
{242}{}{There is no God. We are on our own. That's it.}
{243}{}{Fine. Let's stop there.}
{244}{}{So Levi is the head of this place?}
{245}{}{He is God's hand. I'd sacrifice my life for him.}
{246}{}{I used to think you were the coolest one here.}
{247}{}{Your valor is inspiring.}
{248}{}{Levi is saving our souls - without them, we have no future. This is why I serve him just like I served my Master. But you, normie, will never understand what we went through.}
{249}{}{Okay, let's assume that's true.}

{250}{}{Hello, Garret. How are things?}
{251}{}{It's quiet. My people will protect you, if that will prove necessary.}
{252}{}{Looks like for now, the situation's the opposite.}
{253}{}{Heh-heh, you're right, normie. Still, some defense wouldn't hurt you. Here, take this weapon.}
{254}{}{Looks like this is one of Levi's contraptions. Will you teach me how to use it?}
{255}{}{You normies need to be taught everything. Fine, I'll teach you... If you bring me food.}
{256}{}{Okay, I'll look for something like it.}
{257}{}{Food? In this place? You're asking for too much, greenie.}

{260}{}{You promised to teach me how to fire that weapon Levi made.}
{261}{}{I wanna eat!}
{262}{}{Okay. I'll teach you. It's not hard.}
{263}{}{Then let's not lose time. I don't want to end up in a situation where you become hungry again in the middle of training...}
{264}{}{Excellent, but let's do it a bit later.}
{265}{}{Actually, I'm not too interested in energy weapons. Now, that barrel - that's something. Teach me how to handle big guns!}