{100}{}{This is Garrett.}
{105}{}{Bastards! You will pay for the death of my comrades!}

{200}{}{What? Another normie? And he came to us? Oh-ho-ho, yes we are lucky today.}
{201}{}{And where am I? And who are you?}
{202}{}{Are you wearing a fat green troll costume?}
{203}{}{Lay down your weapons and follow me. Levi will speak to you.}
{204}{}{Okay. Take me to Levi. I want to ask him a couple of questions.}
{205}{}{No, stupid big guy, I'll only talk to you.}
{206}{}{I tell you - go to Levi. If you resist, I'll break your legs, take you to him, and throw you on the floor like an old rag.}
{207}{}{OK, I'm coming, just don't hit me.}
{208}{}{Just try to touch me, you fat freak.}
{209}{}{Please listen to me first. I came in peace.}
{1209}{}{Please listen to me first. I came in peace.}

{210}{}{What do you want, normie?}
{211}{}{Nothing yet.}
{212}{}{Yes, sir.}

{220}{}{Let's talk. What's your name?}
{221}{}{My name is Garrett. And I don't talk to normies.}
{222}{}{My name is Garrett. And I don't trust normies.}
{223}{}{}
{224}{}{Okay. It's already good that we were able to get acquainted. Bye.}
{225}{}{Why? Did something happen in the past?}
{226}{}{Better shut up before I lose my temper.}
{227}{}{Your subordinates aren't talkative either. Why so much anger towards people?}
{228}{}{Anger? No. The Creator taught us to treat all living things with respect. And people like you drove us out of the western lands. So if you don't shut up, I'll be happy to let myself go.}
{229}{}{Okay...}
{230}{}{You've always been like this... so unusual?}
{231}{}{I was once a man like you. I remember my feelings, of fear, hatred, and envy. But the Creator opened a new path for me, and I got rid of human vices. And then the Normies took the Creator away from me.}
{232}{}{Sorry, this question seems to annoy you. I'd rather leave.}
{233}{}{By the words "gave a new life" do you mean taking a mutagen?}
{234}{}{The mutagen is part of a big ceremony. It lasts almost a year. I was preparing - fasting, meditating on the ruins, training my body and will. Mutagen will not be given to someone who does not deserve it.}
{235}{}{Looks like you've been through a lot. It's time for me to deal with my own problems, too. Later.}
{236}{}{The Creator - who is it?}
{237}{}{Yes, who is this Creator of yours?}
{238}{}{This is my god.}
{239}{}{This... doesn't explain much.}
{240}{}{Haha, stupid normie. You'll never see God anyway. People like you killed him.}
{241}{}{Killed God? Is it possible?}
{242}{}{There is no God. We're on our own. And that says it all.}
{243}{}{Okay. Let's stop there for now.}
{244}{}{So Levi is in charge here?}
{245}{}{He is the hand of my god. I will give my life for him.}
{246}{}{I thought you were supposed to be the coolest here.}
{247}{}{Your valor is inspiring.}
{248}{}{Levi saves our souls. We have no future without him. Therefore, I serve him the same way I served my Creator. But you, a normie, cannot understand our suffering.}
{249}{}{Okay, let's assume that it is.}

{250}{}{Hey, Garrett. How is the service?}
{251}{}{Everything is calm. My people will protect you if necessary.}
{252}{}{It seems to be the opposite so far.}
{253}{}{Haha, you're right, normie. Still, you could use some protection. Here, take this weapon.}
{254}{}{Microwave? This is one of Levi's developments. Will you teach me how to use it?}
{255}{}{And you normies need to be taught everything. Okay, I'll show you... If you bring me a proper meal.}
{256}{}{Okay, I'll look for something.}
{257}{}{Food? Here? You want too much, green.}

{260}{}{You promised to teach me how to shoot a microwave.}
{261}{}{I want to eat!}
{262}{}{Okay. I'll show you. It's not difficult.}
{263}{}{Then let's not waste time. I don't want to be in a situation where you get hungry again in the middle of training...}
{264}{}{Great, but we'll do it a little later.}
{265}{}{Actually, I'm not interested in energy weapons. But this trunk is something. Show me how to handle heavy weapons!}