{100}{}{You see a supermutant.}
{105}{}{Bastards! You'll pay for the deaths of my comrades!}

{110}{}{Talk to Levi.}
{111}{}{Pathetic human.}
{112}{}{Don't you dare stare at me.}
{113}{}{I hate it when people stare at me.}
{114}{}{Hm-m-m...}
{115}{}{Do you play dice?}
{116}{}{Don't awaken the beast inside me.}
{117}{}{Levi will answer all your questions. If he wants to.}
{118}{}{Don't talk to me, normie.}
{119}{}{If I get tired of you, I'll rip you to pieces and throw them to the ghouls.}

{120}{}{Hello, normie.}
{121}{}{Levi says you're a friend.}
{122}{}{It's good that you haven't died yet.}
{123}{}{Maybe we could compare our strength?}
{124}{}{It's getting boring...}
{125}{}{Levi says that there will be a cure soon.}
{126}{}{You want to be like me?}
{127}{}{Ah-hah-hah, my suffering nears it's end!}
{128}{}{I love angering the ghouls. There's nothing they can do to me.}
{129}{}{The ghouls are stupid. I'm smart.}