{100}{}{You see a super mutant.}
{105}{}{Bastards! You will pay for the death of my comrades!}

{110}{}{Talk to the Blade.}
{111}{}{Pathetic man.}
{112}{}{Don't you dare stare at me.}
{113}{}{I hate it when people stare at me.}
{114}{}{Hmm...}
{115}{}{Do you play dice?}
{116}{}{Don't wake up the beast in me.}
{117}{}{Levi will answer all the questions. If he wants to.}
{118}{}{Don't talk to me, normie.}
{119}{}{If you bother me, I'll tear you to pieces and throw you to the rippers.}

{120}{}{Hello, normie.}
{121}{}{Levi says you're a friend.}
{122}{}{It's good that you're not dead yet.}
{123}{}{Maybe we'll face off?}
{124}{}{It got boring...}
{125}{}{Levi says there will be a cure soon.}
{126}{}{Do you want to become like me?}
{127}{}{A-ha-ha, my suffering is coming to an end!}
{128}{}{I like to piss off the rippers. They can't do anything to me.}
{129}{}{Rippers are stupid. I'm smart.}