{100}{}{Here is an assistant.}
{101}{}{You see a disfigured person. His face slides down like wax.}

{110}{}{It's strange that they let you in here.}
{111}{}{I don't have time to talk to pagans.}
{112}{}{I don't have anything for you.}
{113}{}{Leave me alone or I'll call my green brothers.}
{114}{}{What's wrong with your skin? Well, you're ugly.}
{115}{}{I don't understand how you normies can survive in the modern world.}
{116}{}{Desert dwellers are stupid.}
{117}{}{Obey Levi.}
{118}{}{I don't trust you or strangers like you.}
{119}{}{Our people have suffered so much from normics...}

{120}{}{Oh, come in, friend, have a seat.}
{121}{}{Even though you are a pagan, but at least harmless.}
{122}{}{Should I make you some radioactive coffee?}
{123}{}{Excuse my green brothers, they are out of the habit of normal people.}
{124}{}{What's wrong with your skin? How did you manage to save it?}
{125}{}{You normies are doing great in this new world.}
{126}{}{People amaze me with their vitality.}
{127}{}{Obey Levi, he was God's own confidant!}
{128}{}{I trust you. But not to these racists from the Brotherhood of Steel.}
{129}{}{Our people have been through a lot. You wouldn't understand.}