{100}{}{You see an assistant.}
{101}{}{You see a disfigured man. His face is sliding down like wax.}

{110}{}{It's strange that you were allowed here.}
{111}{}{I don't have time to talk to heathens.}
{112}{}{I have nothing you would be interested in.}
{113}{}{Leave me alone or I'll call my green brothers.}
{114}{}{What's wrong with your skin? It's so ugly.}
{115}{}{I have no idea how you, normies, can survive in the modern world.}
{116}{}{The people of the desert are stupid.}
{117}{}{Listen to Levi.}
{118}{}{I trust neither you, nor outsiders like you.}
{119}{}{Our people have suffered so much because of normies...}

{120}{}{Oh, come, friend, sit down.}
{121}{}{You may be a heathen, but at least you are a harmless one.}
{122}{}{You want some coffee? It's radioactive, though.}
{123}{}{Excuse my green brothers, they are not used to normal humans.}
{124}{}{What happened to your skin? How did you manage to save it?}
{125}{}{You, normies, settled quite well in this new world.}
{126}{}{Humans surprise me with their persistence.}
{127}{}{Listen to Levi, he was close to God Himself!}
{128}{}{I trust you. But not the hateful ones from that Steel Brotherhood.}
{129}{}{Our people went through much. You wouldn't get it.}