{100}{}{You see Levi.}
{105}{}{Bastards! You will pay for the death of my comrades!}

{110}{}{In the name of the Creator...}
{111}{}{In the name of His Holy Spirit...}
{112}{}{Accept the sinful soul of your slave...}
{113}{}{Servant of God, kneel and repent of your sins before the face of the Creator.}
{114}{}{Drink from the holy chalice of the Holy Virus.}
{115}{}{May the Holy Spirit be with you.}
{116}{}{Amen.}

{200}{}{Greetings, stranger. I am Levi, the guide of my small flock.}
{1200}{}{Greetings, stranger. I am Levi, the guide of my small flock.}
{201}{}{And I}
{202}{}{. Just a traveler.}
{203}{}{A church and a saint in the middle of burnt ruins - it looks very strange.}
{204}{}{You are in our holy monastery, and your appearance is alarming. Let's make a deal right away - you'll stay safe here as long as you follow the rules and behave friendly.}
{205}{}{I don't want any quarrels. Especially in this position.}
{206}{}{Whatever you say.}
{207}{}{Very good. It's unexpected to see a normal person here. Tell me what brought you.}
{208}{}{Being polite at the muzzle of a six-barrel minigun? And you're not too nice for a priest.}
{209}{}{If you come into our situation, you will think differently. Now tell me, what brought you to these ruins? And don't try to lie - I will feel any lie.}
{210}{}{I'm looking for useful things on the ruins. There are probably plenty of pre-war treasures left here.}
{211}{}{Your desire for profit has led you straight to hell. Which is to be expected.}
{212}{}{But what are you doing in this hell?}
{213}{}{I'm looking for my relatives. They were abducted by slavers.}
{214}{}{Obviously, they are not here. You have a small mind if you're looking for a slave convoy in such a lifeless place.}
{215}{}{Still, I had to check. But what are YOU doing here?}
{216}{}{I'm looking for the Brotherhood of Steel convoy. He was lost somewhere in these ruins.}
{217}{}{Oh yes. So the Brotherhood sent a mercenary instead of risking their people. As I expected, they do not have enough forces in this region for full-fledged rescue operations. So much the better for us.}
{218}{}{Why is that? Are you up to something?}
{219}{}{It's a long story. Some people think I'm the devil and I'm trying to create my hell. But in fact, I'm trying to create a paradise for my people in the middle of hell.}
{220}{}{Sounds like a diabolical plan.}
{221}{}{Go on.}
{222}{}{That's very noble of you.}
{223}{}{We can't live in a normal world anymore. The pagans burn our brothers in the west, and the east does not accept either our faith or ourselves. North and south are empty. It remains for us to create our own world.}
{224}{}{[Next]}
{225}{}{Now you understand that your presence here is highly undesirable. Especially considering our recent meeting with other "normal".}
{226}{}{Wait, so there are other "normal" people like me here?}
{227}{}{A group of pagans crossed the ruins to the south. They were not destined to leave these lands. Like you, they will stay here forever.}
{228}{}{If I help you "find paradise", will you let me go free?}
{229}{}{One name for two? Strange vicissitudes of fate... But it doesn't matter. }
{230}{}{What the hell? Let me go immediately!}
{231}{}{There's no way out for you here. Garrett, explain this to our guest...}
{232}{}{I'm getting out of here anyway. And don't even think about stopping me.}
{233}{}{Wait a minute! What if I help you? Will you let me go then?}
{234}{}{Do you want to make a deal with the devil? Good.}
{235}{}{[Next]}
{236}{}{Go down to the basement and talk to Diana. She will tell you what kind of research we are conducting and what is needed to complete them. Everyone will receive their reward according to their result.}
{237}{}{Good. I'm coming.}
{238}{}{Well, no. I don't make deals with devils.}
{239}{}{Sorry to hear the rejection after such a frank conversation. Garrett, I leave this body to your discretion...}
{240}{}{What?}
{241}{}{Don't come near me, big guy!}

{242}{}{Batvas? Great.. What?}
{243}{}{(heavy sigh) Poor child... Amazingly, you managed to survive and get here. But don't worry. We're your friends. We will help. You won't hurt your friends, right?}
{244}{}{Oh, friends! Friends!}
{245}{}{You're lying. You're bad. I don't have a friend.}
{246}{}{Well, I understand. You're lonely, like the rest of us. But now we're your friends. I give you my word, you'll be fine with us.}
{247}{}{No! Don't believe it! Deception!}
{248}{}{There will be too many problems with this body. Garrett, end his suffering...}
{249}{}{Yeah!}

{250}{}{What can you tell me?}
{251}{}{It's time for me to get busy.}
{252}{}{Calm down, my child. You're in the church, you're safe. No one will touch you here. Why don't you do something for your new friends? Diana lives in the basement. You will find a lot in common with her. Go talk to her. Go...}
{253}{}{U, the girl is in the basement. Yes, I'm coming.}
{254}{}{Still here? Do you really want to stay in this sacred place?}

{255}{}{You have a part from the power armor. Will you give it to me?}
{256}{}{Take. I believe you're using this armor for good. Besides, we can't use it anyway.}
{257}{}{Thank you. I will find a worthy use for this.}
{258}{}{Thanks, but I'd like to know something else.}
{259}{}{Greetings, brother.}
{1259}{}{Greetings, sister.}

{260}{}{Who are you?}
{261}{}{I am Levi, the shepherd of these poor souls.}
{262}{}{I've heard that before. Let's do something else.}
{1262}{}{I've heard that before. Let's do something else.}
{263}{}{The shepherd? Are you a priest or something?}
{264}{}{Our church was destroyed by pagans like you. Our god died in the atomic flame, so I led my flock according to his precepts. But far from those lands where our faith has turned into shame.}
{265}{}{And what kind of faith and what is it?}
{266}{}{You won't understand the basics even for an entire mass. I will only say that our God, the Creator, wanted to rid people of their vices and shortcomings by offering a different way.}
{267}{}{Is the other way a path of mutations and deformity?}
{268}{}{Your view is limited. Thanks to the Creator, we are devoid of human vices and can survive even in such a perilous place as these ruins. And you?}
{269}{}{I don't think I would have settled here at all. But why did you come to these ruins?}
{1269}{}{I don't think I would have settled here at all. But why did you come to these ruins?}
{270}{}{Why did you choose this particular place for your flock?}
{271}{}{A simple tactic. Here we are safe from pagans and heretics. We are gathering our strength for the Second Coming when the Creator will rise again from the ashes.}
{272}{}{Your story is interesting. But there are more important things to do.}
{273}{}{So what is this faith that you cling to so much?}
{274}{}{It looks like this Creator was really important to you.}
{275}{}{We are the Children Of the Cathedral. We were crucified for our faith, but we will continue our prayers until the end of the world. This is our burden.}
{276}{}{And in my opinion, you are just another sect. I don't believe you.}
{277}{}{It looks like you believe what you're saying.}
{278}{}{Your devotion to faith is worthy of respect.}

{280}{}{How did you and the others become like this?}
{281}{}{Ugly? Fortunately, we have long ceased to perceive this word with resentment. For us, the appearance has long lost its meaning. What made us like this? Our sins and dirty thoughts when we were human.}
{282}{}{Speaking of God, who do you mean?}
{283}{}{God is no more. God has fallen at the hands of fools. We are the only ones who bring light to this hell after his death.}
{284}{}{Hmm. I have already met such a mantle. The followers of Fire in Phoenix wear something similar.}
{285}{}{We have already encountered imitators who parasitized small settlements under our banner. Don't believe these blasphemers, their faith is fake.}
{286}{}{And who did you mean when you spoke about God?}
{287}{}{Not before you finish your task.}
{288}{}{Okay.}

{290}{}{What do you know about Diana?}
{291}{}{The followers of the Apocalypse are kind but stupid people. They try to help others to the best of their understanding of this help. They treat people like me with condescension, as if we need their care. But it's the opposite.}
{292}{}{Why do you need Diana?}
{293}{}{She is a medic and a scientist. Exactly the one I need to complete the mission.}
{294}{}{And what kind of mission is this?}
{295}{}{Paradise in the middle of hell.}
{296}{}{Clear.}
{297}{}{What do you know about the Followers of the Apocalypse?}

{300}{}{What do you know about the Brotherhood of Steel?}
{301}{}{Heretics who have lost all faith in God. They believe only in the power of technology. Poor people.}
{302}{}{You have an unkind relationship with them, don't you?}
{303}{}{The Brotherhood is guilty of killing our god. Their forgiveness will come only at the epicenter of atomic fission.}
{304}{}{Clearly.}

{310}{}{Diana has developed a mutagen.}
{311}{}{Her work is priceless. But for now, I can't risk giving medicine to my people.}
{312}{}{Do you want to check it out? But how?}
{313}{}{Let's see how the mutagen acts on our distraught brothers living in ruins. Take these sprayers and place them in the busiest places. Where the rippers hold their demonic rites.}
{314}{}{You do realize that I could die on this mission?}
{315}{}{Are you talking about their totems? Okay, we'll have to act secretly so as not to make a lot of noise.}
{316}{}{You're almost dead as it is. But I believe that you will succeed if you don't get into fights. Believe in our mission, believe in yourself.}
{317}{}{Yes, uh, of course, no problem. Sneak up to the crowd of ghouls and throw a spray gun. There is nothing easier. Uh, bye.}
{318}{}{You're sending me to my death. But if I survive, you will answer for everything.}
{319}{}{Thank heaven for your appearance. Now go.}
{320}{}{I will try not to die.}
{321}{}{If I survive, you will pay dearly for it.}
{322}{}{It's too dangerous. Maybe there is another option?}

{330}{}{Your work is priceless. But I can't accept it yet.}
{331}{}{We have completed the task. What's wrong? Do you need any guarantors?}
{332}{}{The lives of my people depend on this medicine. Prove that it is safe.}
{333}{}{We did everything you wanted. If you don't want to keep your word, then go to hell.}
{334}{}{It's very rude. Garrett, show our guest that he is no longer welcome here...}
{335}{}{Die!}
{336}{}{No, wait! I can take a mutagen to prove its effectiveness. Is that okay with you?}
{337}{}{Wait. What if I install mutagen sprayers on the ruins? Will that satisfy you?}
{338}{}{In that case, I can take the mutagen. Anyway, I'm so glad that I can't survive otherwise.}
{339}{}{Commendable dedication. If you take the mutagen, you will become a different person, one of us. You will find friends and a new home, but you will lose your human form.}
{340}{}{Idiot, are you seriously buying this bluff? I'm not going to turn into a green freak and believe in all sorts of nonsense.}
{341}{}{Everything will be fine. I am not afraid of mutation.}
{342}{}{Is there no other alternative? For example, I can test the mutagen on rippers.}
{343}{}{Okay. I can install mutagen sprayers in places where rippers congregate.}
{344}{}{Yes, this will clarify a lot. Let's see how the mutagen affects the inhabitants of the ruins.}
{345}{}{Good.}
{346}{}{We will make the sprayers ourselves. Your task is to install them in the busiest places on the ruins. Now go and don't distract me anymore until you complete the task.}
{347}{}{I'm on my way.}
{348}{}{Get ready for the ceremony. I will personally conduct the dedication according to the canons of the church.}
{349}{}{[Wait for the ceremony]}

{350}{}{I installed the sprayers. And it had a certain effect on the rippers.}
{1350}{}{I installed the sprayers. And it had a certain effect on the rippers.}
{351}{}{That's how? What happened to them?}
{352}{}{They became... smarter and calmer.}
{353}{}{I think the mutagen lowered their aggressiveness threshold and eliminated the chronic pain syndrome.}
{354}{}{Good. It's just like Diana said. You did a great job. To be honest, I didn't expect this.}
{355}{}{So can we go now?}
{356}{}{You have earned your freedom and our gratitude. You can get ready for the road and leave, no one will bother you. However, the entrance here to all "normal" will be closed from now on.}
{357}{}{It suits me. Goodbye, Levi.}
{358}{}{I won't take another step into that hole. Goodbye.}

{360}{}{You have proved your loyalty to our sacred alliance. You have renounced the human for the spiritual. You're welcome, brother.}
{1360}{}{You have proved your loyalty to our sacred alliance. You have renounced the human for the spiritual. We are glad to see you, Sister.}
{361}{}{Ugh, I'm experiencing unusual sensations. It's like I've been... reborn.}
{1361}{}{Ugh, I'm experiencing unusual sensations. It's like I'm... reborn.}
{362}{}{That's right, brother. You're a new person now. Forget the past and live in the present. Consider your past mission complete.}
{1362}{}{That's right, Sister. You're a new person now. Forget the past and live in the present. Consider your past mission complete.}
{363}{}{Will you let Diana go now?}
{364}{}{Of course. She had fulfilled her mission and deserved forgiveness. But let him remember that Inferno is now under my control. All "normal" entrances here will be closed. I'll let her go and get her things, but don't let her come back.}
{365}{}{Let me take my leave, Brother Levi.}
{366}{}{So what have we decided about the mutagen?}
{367}{}{Your task is to install mutagen sprayers in the busiest places where the most rippers gather.}
{368}{}{Okay, I'll try.}
{369}{}{You'll have to run fast to avoid falling into the clutches of ghouls.}
{370}{}{I can't survive outside without this armor.}
{371}{}{But you've done it before, haven't you? In any case, I cannot entrust such a dangerous object that can be turned against my flock.}
{372}{}{I wish I could use this armor.}
{373}{}{Levi, I'm asking you to return the parts from the power armor. With her help, my chances will increase tenfold.}
{374}{}{So be it. Here's the detail. Use the armor only for good.}
{375}{}{Thank you.}
{376}{}{Scientific research requires investments, didn't you know that?}
{377}{}{I cannot entrust such a dangerous object that can be turned against my flock.}
{378}{}{Diana and I are scientists, not warriors. We need at least some protection.}