{100}{}{You see Levi.}
{105}{}{Bastards! You will pay for the deaths of my comrades!}

{110}{}{In the name of the Master...}
{111}{}{In the name of His Holy Spirit...}
{112}{}{Accept the sinful soul of your servant...}
{113}{}{Stand on your knees, servant, and repent for your transgressions to the face of the Master.}
{114}{}{Bib from the sacred bowl the Holy Virus.}
{115}{}{May the Holy Spirit be with you.}
{116}{}{Amen.}

{200}{}{I welcome you, stranger. I am Levi, the shepherd of my small flock.}
{1200}{}{I welcome you, stranger. I am Levi, the shepherd of my small flock.}
{201}{}{And I'm }
{202}{}{. I'm just a traveler.}
{203}{}{A functioning church among scorched ruins looks quite strange.}
{204}{}{You are in our holy habitat, and your arrival is most alarming. Let us reach an agrement up front - you will be safe here so long as you follow our rules and act in a respectful manner.}
{205}{}{I don't want there to be conflict between us. Especially considering my unfavorable position.}
{206}{}{Whatever you say.}
{207}{}{Very good. It is quite unexpected to see a normal human here. Tell me what brings you here.}
{208}{}{Be polite while a six-barreled minigun is pointed in your face? Not too friendly for a priest.}
{209}{}{You would not say this if you understood our situation. And now the time has come for you to tell me what has brought you to these ruins. Do not even think of lying - I will feel it.}
{210}{}{I'm looking for valuable items here. This place must be full of Pre-War treasure.}
{211}{}{Your desire for profit has brought you straight to hell. As should have been expected.}
{212}{}{And what are *you* doing in this hell?}
{213}{}{I'm looking for my people. They were abducted by slavers.}
{214}{}{It is quite obvious that they are not here. Your mind must not be particularly developed if you are looking for a slave convoy in such a lifeless place.}
{215}{}{I had to make sure. And what are YOU doing here?}
{216}{}{I'm looking for a Brotherhood of Steel convoy. It was lost somewhere around here.}
{217}{}{Oh. So the Brotherhood has sent a hired gun instead of risking it's own people. As I expected - their presense in this region does not allow for full rescue operations. Which is good for us.}
{218}{}{Why? Are you planning something here?}
{219}{}{It is a long story. Some believe that I am a devil, that I am trying to create my own personal hell. But the truth of the matter is that I am trying to create heaven for my people amidst hell.}
{220}{}{Sounds rather devilish.}
{221}{}{Continue.}
{222}{}{That's very kind of you.}
{223}{}{We can no longer live in the normal world. Heathens are burning our brothers at stakes to the west, and the east accepts neither our faith nor us as a people. The north and south are empty. All that is left for us is to create our own world.}
{224}{}{[Continue]}
{225}{}{Now you see why your presense here is unwelcome. Especially considering our recent interaction with other "normals".}
{226}{}{Wait, so there are others like me here?}
{227}{}{A unit of heathens was traversing the ruins, going to the south. They are not to leave this place. Like you, they will remain here for all eternity.}
{228}{}{If I help you... "achieve heaven", will you set me free?}
{229}{}{One name for two? The odd vicissitudes of fate... But it is irrelevant.}
{230}{}{What the hell?! Release me immediately!}
{231}{}{There is no way out of this place for you. Garret, would you kindly explain this to our little guest?}
{232}{}{I'll get out of here. Don't even think about trying to stop me.}
{233}{}{Wait! What if I help you? Will you set me free then?}
{234}{}{So you desire to make a deal with a devil? Good.}
{235}{}{[Continue]}
{236}{}{Go down into the basement and speak with Diana. She will explain to you what kind of research we do and what is necessary to finish it. All will receive what they deserve when it is done.}
{237}{}{Good. I am on my way.}
{238}{}{No way. I don't make no deals with no devils.}
{239}{}{It is disheartening to hear this after a conversation so frank. Garret, I leave this body to you...}
{240}{}{What?}
{241}{}{Don't come any closer, you big 10-feet tall...}

{242}{}{Big green people?}
{243}{}{(deep sigh) Poor child... It is incredible that you managed to survive and get here. But do not worry. We are your friends. We will help you. You would not hurt your friends, would you?}
{244}{}{Oh, friends! Friends!}
{245}{}{You lie. You bad. You no friend of mine.}
{246}{}{I understand. You are alone, like all of us. But now we are your friends. I promise you, with us, everything is going to be okay.}
{247}{}{No! Not believe! Lie!}
{248}{}{This body is proving itself too troublesome. Garret, put an end to their suffering...}
{249}{}{Aha!}

{250}{}{What can you tell me?}
{251}{}{It's time for me to get to work.}
{252}{}{Calm down, my child. You are in the church, you are safe. Nobody will harm you here. Perhaps you could do something for your new friends? Diana lives in the basement. You will find that you have much in common with her. Go, talk to her..}
{253}{}{Ooh, basement person. Yes, me go.}
{254}{}{You are still here? Do you really want to stay in this place?}

{255}{}{You have a power armor component. Will you give it to me?}
{256}{}{Take it. I believe that you will use this armor for good. In any case, we ourselves do not posess the ability to utilize it properly.}
{257}{}{Thank you. I will find a worthy use for it.}
{258}{}{Thanks, but I want to learn some information.}
{259}{}{I greet you, brother.}
{1259}{}{I greet you, sister.}

{260}{}{Who are you?}
{261}{}{I am Levi, the shepherd of these poor souls.}
{262}{}{I have already heard that. I want information you didn't tell me yet.}
{1262}{}{I have already heard that. I want information you didn't tell me yet.}
{263}{}{Shepherd? So you're a priest or something like that?}
{264}{}{Our church was destroyed by heathens just like you. Our god died in atomic flame, which is why I guide my flock according to his testaments. But I do it far away from those lands where our faith turned to shame.}
{265}{}{What is this faith and what are it's basic principles?}
{266}{}{You could not begin to comprehend even it's foundations in a whole mass. I will say simply that our god, the Master, wanted to rid humankind of its faults and deficiencies by offering another way.}
{267}{}{Is this other way the path of mutations and ugliness?}
{268}{}{Your viewpoint is narrow. Thanks to the Master, we lack human flaws and are able to survive even in such a deathly place as these ruins. What about you? Would you be able to live here?}
{269}{}{I don't think I would settle here at all. Now, why did you come to these ruins?}
{1269}{}{I don't think I would settle here at all. Now, why did you come to these ruins?}
{270}{}{Why did you choose this place specifically for your flock?}
{271}{}{Simple tactics. Here, we are safe from heathens and heretics. We gather strength while we wait for the Second Coming, when the Master will rise once more from ash.}
{272}{}{This is interesting. But there are more important things.}
{273}{}{So what is this faith that you so cherish?}
{274}{}{Looks like that Master was really important to you.}
{275}{}{We are the Children of the Cathedral. We were crucified for our faith, but we shall continue uttering our prayers until the ending of the world. Such is our burden.}
{276}{}{I think you're just another cult. I don't believe you.}
{277}{}{Looks like you really believe what you say.}
{278}{}{The devotion you have toward your faith is worthy of respect.}

{280}{}{How did you and the others here become like this?}
{281}{}{Ugly? Thankfully, we have stopped seeing this word as insulting long ago. For us, the exterior of the body has lost it's meaning many, many years ago. What made us become like this? Our sins and evil thoughts while we were still human.}
{282}{}{When you say "god", which one do you mean?}
{283}{}{God is dead. Dead at the hands of fools. We were the only ones who carry light into this hell after his passing.}
{284}{}{Hm. I have already encountered a similar robe. The Followers of the Holy Fire in Phoenix wear something like this.}
{285}{}{We have already encountered imitators who parasitize on small settlements under our banner. Do not believe these blasphemers. Their faith is only a tool to them.}
{286}{}{When you said "god", which one did you mean?}
{287}{}{Not before you finish your mission.}
{288}{}{Alright.}

{290}{}{What do you know about Diana?}
{291}{}{The Followers of the Apocalypse are well-meaning, but ignorant humans. They try to help others to the best of their understanding of the word. To those like me they react with condescension, as if we need their guidance, when in reality, the situation is the opposite.}
{292}{}{Why do you need Diana?}
{293}{}{She has medical and scientific expertise. And this is exactly what I need to complete my mission.}
{294}{}{What is this mission?}
{295}{}{Heaven in hell.}
{296}{}{Right.}
{297}{}{What do you know about the Followers of the Apocalypse?}

{300}{}{What do you know about the Brotherhood of Steel?}
{301}{}{They are heretics who have lost any semblance of faith in god. They believe only in the power of technology. Poor humans.}
{302}{}{Your relations with them aren't too good, aren't they?}
{303}{}{The Brotherhood has killed our god. Their forgiveness will come only when they are be in the center of an atomic blast.}
{304}{}{I see.}

{310}{}{Diana has developed a mutagen.}
{311}{}{Her work is invaluable. But for now, I cannot risk giving this cure to my people.}
{312}{}{You want to test it? But how?}
{313}{}{We shall see how the mutagen reacts to our maddened brothers living among the ruins. Take these sprayers and set them up in the most lively of places there. Where they conduct their demonic rituals.}
{314}{}{You do realize that I could die out there, right?}
{315}{}{You mean their totems? Alright. I'll need to employ stealth to not raise too much noise.}
{316}{}{You are barely alive as it is. But I believe that it will all go well, if you do not get into fights. Believe in our mission. Believe in yourself.}
{317}{}{Yes, uhh, of course, no problem. Get to the crowd of ghouls and set up a sprayer. Nothing easier than that. Uhh, bye.}
{318}{}{You are sending me to certain death. But if I survive, you will pay for everything.}
{319}{}{Thank heavens for your arrival. Now go.}
{320}{}{I'll try not to die.}
{321}{}{If I survive, you'll pay for everything dearly.}
{322}{}{This is far too dangerous. Perhaps there is another way?}

{330}{}{Your work is invaluable. However, as of now, I cannot accept it.}
{331}{}{We completed the task. Is something wrong? Do you need some kind of guarantee?}
{332}{}{The lives of my people hinge on this cure. Show me that it is truly safe.}
{333}{}{We did all you asked. If you don't want to keep your word - then go to hell.}
{334}{}{This was quite impolite of you. Garret, show our guest that they are no longer welcome...}
{335}{}{Die!}
{336}{}{No, wait! I could take the mutagen to prove it's effectiveness. Will that be enough?}
{337}{}{Wait. What if I set up mutagen sprayers in the ruins? Will that satisfy you?}
{338}{}{In that case, I can take the mutagen. I am so irradiated that I will die if I don't.}
{339}{}{You posess commendable dedication. If you do take the mutagen, you will become a new man, one of us. You will acquire friends and a new home, but you will lose your human form.}
{340}{}{You idiot, you seriously didn't realize it was a bluff? I'm not about to drink something that'll turn me into a big green ugly mutant and make me believe in some bullshit. No way.}
{341}{}{Everything is going to be okay. Mutations do not scare me.}
{342}{}{Is there no other alternative? Maybe I could test the mutagen on the ghouls?}
{343}{}{Fine. I can set up mutagen sprayers in areas crowded with ghouls.}
{344}{}{Yes, this reveals much. Let us see how the mutagen reacts to the inhabitants of these ruins.}
{345}{}{Good.}
{346}{}{We shall produce the sprayers ourselves. Your goal is to set them up in the most lively of places among these ruins. Now go and do not disturb me any further until the moment when you complete the mission.}
{347}{}{Already on my way.}
{348}{}{Prepare for the ceremony. I will personally conduct an initiation according to the canons of the church.}
{349}{}{[Wait for the ceremony]}

{350}{}{I have set the sprayers up. It had a certain effect on the ghouls.}
{1350}{}{I have set the sprayers up. It had a certain effect on the ghouls.}
{351}{}{Really? What happened to them?}
{352}{}{They became smarter... and calmer.}
{353}{}{I believe the mutagen lowered their levels of aggression and healed the chronic pain syndrome.}
{354}{}{Good. It works just like Diana described. You have completed the mission wonderfully. Frankly, I did not expect this.}
{355}{}{Are we set free now?}
{356}{}{You have earned not only your freedom, but also our gratitude. You can prepare to leave. No one will stand in your way. However, after that, entry to those of your kind will be forbidden.}
{357}{}{Sounds fine to me. Goodbye, Levi.}
{358}{}{I won't make even a single step toward this dump. Bye.}

{360}{}{You have showed dedication toward our holy union. You have rejected humanity in favor of the spiritual. We are happy to have you, brother.}
{1360}{}{You have showed dedication toward our holy union. You have rejected humanity in favor of the spiritual. We are happy to have you, sister.}
{361}{}{Oof, I feel like I'm experiencing strange sensations. Like I was... reborn.}
{1361}{}{Oof, I feel like I'm experiencing strange sensations. Like I was... reborn.}
{362}{}{And you are right, brother. You are now a new man. Forget about the past and live in the present. Consider your mission completed.}
{1362}{}{And you are right, sister. You are now like a new man. Forget about the past and live in the present. Consider your mission completed.}
{363}{}{Will you set Diana free?}
{364}{}{Of course. She has completed her mission and earned forgiveness. But she must remember that Inferno is under my control. Entry to those of her kind will be closed. I will allow her to leave and carry her things with her, but she must not come back.}
{365}{}{Let me take my leave, brother Levi.}
{366}{}{So, what did we decide on regarding the mutagen?}
{367}{}{Your goal is to set up sprayers in places crowded with ghouls.}
{368}{}{Fine, I'll try.}
{369}{}{I'll have to run fast to not get caught by them.}
{370}{}{I won't survive outside without this armor.}
{371}{}{Then how did you manage to do it before? In any case, I cannot trust you with such a dangerous item, one that could be easily turned against my flock.}
{372}{}{What a shame. I could have really used that armor.}
{373}{}{Levi, I ask you to return the power armor components. With it, my chances of success will rise ten-fold.}
{374}{}{Let it be so. Here is the component. Use the armor strictly for good.}
{375}{}{Thank you.}
{376}{}{Research requires investment, did you not know this?}
{377}{}{I cannot trust you with such a dangerous item, one that could be easily turned against my flock.}
{378}{}{Diana and I are scientists, not warriors. We need at least *some* protection.}