{100}{}{You see paladin Barkley.}
{101}{}{You see a thick-skinned fighter. His unswerving face shows complete readiness for battle.}
{102}{}{Repositioning.}
{103}{}{Thanks, doc.}
{104}{}{Traitor! You'll die a dog's death!}
{105}{}{Bastards! You'll pay for the deaths of my comrades!}
{106}{}{M-mutants, damn them! A bit more and I'll shoot 'em all down. What, are you with them?}

{110}{}{Can't believe my eyes! How did this happen?}
{111}{}{Welcome to the Brotherhood.}
{112}{}{I didn't become a paladin for this shit.}
{113}{}{Hmm, looks like, reconnaissance was mistaken about the enemy's numbers by a couple of zeroes.}
{114}{}{Eh, reminds me of the good old days...}

#Meeting dialogue
{200}{}{Agh, dammit... I almost shot you. Thought you were another mutant. Are you from the support group?}
{201}{}{What group? What are you talking about?}
{202}{}{Shit. So the Brotherhood didn't send you to help? Fuck. Then what are you doing in this forsaken place?}
{203}{}{You know, looking for valuable stuff. Usually there is a lot of it in desolate ruins.}
{204}{}{Dammit. So you're a scavenger? (sigh) Looks like all my luck ran out last year.}
{205}{}{What is it?}
{206}{}{I'm looking for someone. But it's personal.}
{207}{}{Okay... Let's assume that's true. You sure you don't want to find someone else for me?}
{208}{}{Did you lose someone?}
{209}{}{I answered the radio request for help.}
{1209}{}{I answered the radio request for help.}
{210}{}{At least some good news this terrible day.}
{211}{}{Tell me what happened.}
{212}{}{You should have shot, you fool. Now is my turn...}
{213}{}{So you're from the Brotherhood of Steel? I hate you all. Die, scum!}

{220}{}{Yes, the Brotherhood of Steel sent me on a rescue operation.}
{221}{}{Hmm. I don't remember you. Show me your dog tag.}
{222}{}{Dog tag? But I don't serve the Brotherhood. I was just hired.}
{223}{}{So that's how it is. I was warned the Brotherhood in Arizona isn't in the best shape. Sad. And where are the others?}
{224}{}{Who are you talking about? I'm alone.}
{1224}{}{Who are you talking about? I'm alone.}
{225}{}{Dammit! What were they thinking? That one hired gun would resolve such a situation? Though, a small group does have a tactical advantage among ruins... Fine, I very much hope that at the very least you won't get in the way.}
{226}{}{So what happened?}
{227}{}{Umm... Here, look, I have a Brotherhood dog tag. Do you believe me now?}
{228}{}{I know the name on that dog tag. You have exactly one chance to explain yourself.}
{229}{}{Umm... Eh, go to hell. Die!}
{230}{}{Yes, I am not from the Brotherhood. It just looked like you were going to shoot me...}
{231}{}{Dammit, cowardly piece of shit, and how am I supposed to trust you now?}
{232}{}{Maybe you could tell me what happened, and then we could try helping each other out?}
{233}{}{Look, I know that you're in trouble. Right now who serves who is not important - helping each other out is.}
{234}{}{Okay. But don't you dare try and fool me. I don't tolerate lying.}
{235}{}{Uhh, okay. Maybe you should then tell the truth about why you're here?}

{240}{}{My unit walked into an ambush made by these... by the things that live here. Amidst the chaos and confusion, I lost the other team members and now I can't establish communications with them. And I hurt my leg while fighting.}
{241}{}{But aren't you military? And more than that, fully equipped.}
{242}{}{I see. The operation failed before it could even begin.}
{243}{}{Nobody expected to encounter resistance in these ruins. We were assuming there was no life here, so we chose to walk through the city to not deal with the mutants in the desert.}
{244}{}{Alright. What's the plan, then?}
{245}{}{I need to gather the unit, if there is anyone left to gather, that is. And somehow deal with my leg, otherwise I won't be able to go to the destination... Hey, can you do your civic duty - that is, do me a favor?}
{246}{}{Of course. I can't just leave a fellow human being in trouble.}
{247}{}{I knew I could count on you. If I continue my mission, then I won't owe anything to anyone.}
{248}{}{Damn right.}
{249}{}{You really aren't a lucky person, soldier. I am not the kind of person to care about other people's problems. Now, you can give me your ammo either the easy way, or the hard way...}
{250}{}{You're talking about quite a dangerous activity. Why should I take that kind of risk?}
{251}{}{Don't worry about the reward. When we get to the base, you will be generously rewarded.}
{252}{}{Very much hope so.}
{253}{}{Oh, and by the way. My name is Barkley. Paladin Barkley. You can take a look around, but be careful at the exit, I set up a couple of traps.}
{254}{}{Okay.}
{255}{}{I need no reward. My village needs protection.}
{256}{}{If we get to the base, I'll talk about your problem with the elders. And right now, you help me.}
{257}{}{Okay.}

{260}{}{Show me how I can safely get out of here.}
{261}{}{The corridor has a few traps. Look where you step.}
{262}{}{Thank you.}
{263}{}{Listen, I have a ton of questions.}

#Repeated dialogue
{300}{}{Report the situation.}
{301}{}{All clear.}
{302}{}{Yes?}
{303}{}{We need to talk.}
{304}{}{What do you want to know?}
{305}{}{Enough talk.}
{306}{}{No talk. This is not the time.}
{307}{}{Yes, I suppose you're right.}
{308}{}{A bit more and I'll shoot 'em all down!}
{309}{}{Fine, forget it.}

{310}{}{Alright, what do I need to do?}
{311}{}{Heal my trauma and find the other members of the team. After that, we'll make a plan of what to do next.}
{312}{}{The goal is clear.}
{313}{}{A serious injury. I won't be able to do it.}
{314}{}{Just find medicine. They were among the things in our convoy. Hurry up before the ghouls scatter them.}
{315}{}{How did this happen to you?}
{316}{}{The fuckers set up traps behind us and put up a smoke screen. I walked into one. Dammit, they played us like a fiddle...}
{317}{}{Alright. Could you repeat our plan?}
{318}{}{Beginning task.}
{319}{}{I'm off to find them.}

{320}{}{Who else is in the unit?}
{321}{}{A few people. A half are definitely dead, and about the others I have no idea.}
{322}{}{Go on.}
{323}{}{I'm off to find them.}
{324}{}{The last time the squire talked to me was around the supermarket, since then I lost contact with him.}
{325}{}{The knight was holding them off right in the middle of the ambush, by the monument.}
{326}{}{Diana was also with us, she's from the Followers of the Apocalypse. I heard her screaming in the distance. Looks like the ghouls were carrying her somewhere.}
{327}{}{Who else was in the team?}
{328}{}{And what if they're all dead?}
{329}{}{Then it is my duty to collect all their dog tags, to inform my superiors and honor their memory.}
{330}{}{Where was the convoy attacked?}
{331}{}{To the north-west, on the fifth highway. Right beside some kind of monument.}
{332}{}{Alright.}
{333}{}{How come ghouls could defeat an armed convoy?}
{334}{}{These things may be closer to animal than humankind, but they have enough intelligence left to fight. Looks like their long lives among the ruins taught them well.}
{335}{}{What did they do?}
{336}{}{We walked right into an ambush. The ghouls set up traps along the road and lured us into a hard-to-defend place. We were surrounded and were bombarded with bags containing dust. This caused a smoke screen to appear, which the ghouls promptly used to capture them all.}
{337}{}{Go on.}
{338}{}{We killed some, but there was just too damn many of them. And when they attacked us head-on, only I managed to get out. I had to retreat... Dammit, if only I could have used the power armor!}
{339}{}{I'm very sorry.}
{340}{}{Everyone fails sometimes, paladin. You are no exception.}
{341}{}{Anything else?}
{342}{}{Good. Let's see what's left there.}
{343}{}{You have a serious wound. What can I do?}
{344}{}{I'm almost back to normal. We need to find the missing members of the unit. We'll discuss what to do next after that.}
{345}{}{We have to find Diana. It may be possible that she is still alive and is in need of help.}
{346}{}{We have to find Diana. It may be possible that she is still alive and is in need of help. And I would use some medical help.}
{347}{}{I managed to find the body of a knight. I will continue searching.}
{348}{}{I managed to find the body of a squire. I will continue searching.}

{350}{}{Your brothers are dead. Here are their dog tags. I'm very sorry.}
{351}{}{They died in battle like true warriors. Blessed be their memory... And what about the girl? There was a civilian with us, a teacher from the Followers of the Apocalypse.}
{352}{}{I don't know anything about her.}
{353}{}{I need to know everything about her. Command gave a clear directive - escort her to the destination. She was supposed to be under my protection. I can't disobey orders by leaving her behind.}
{354}{}{I'll try to find out what happened to her.}
{355}{}{Diana is being forcibly kept in the old church building.}
{356}{}{Forcibly kept? By who? These mutants can't even really talk in the same way we do.}
{357}{}{No, not them, other mutants. They have some kind of cult there.}
{358}{}{What the hell is going on. Maybe the cult is operated by rippers? We need to know more. But more importantly - save Diana.}
{359}{}{I'll try to conjure up a way to do that.}
{360}{}{Diana surely is dead.}
{361}{}{Bad business. I will be heavily reprimanded, and maybe even be court-martialed because of that girl. I wouldn't want to return to the suffocating air in the California bunker. Alright, thanks for the help, comrade.}
{362}{}{Is this everyone you were looking for?}
{363}{}{Diana is awaiting us by the entrance. You can go talk to her.}
{364}{}{Excellent work, comrade. I'm in your debt.}
{365}{}{Is this everyone you have been looking for?}
{366}{}{Diana already left. She didn't want to stay in this hellish place.}
{367}{}{Left without telling me? What a bitch. Here I was risking my own life to find her... Fine, fuck her. She is now no longer under my command.}
{368}{}{Is this everyone you have been looking for?}
{369}{}{I managed to find Diana.}
{370}{}{What happened to her? Is she alive?}
{371}{}{I'll go find the others.}
{372}{}{They died in battle like true warriors. Blessed be their memory...}
{373}{}{Exactly. But still, I can't return to base until I complete the main objective.}
{374}{}{What kind of objective?}
{375}{}{Delivering a set of power armor. This was the main object that we were delivering to the Puerto base. Now it's under their control. This is a terrible loss.}
{376}{}{There was no power armor in the place where you were attacked. The mutants carried it away to the old church building just as they did with all your other items.}
{377}{}{That needs it has to be returned. Looks like you already know how to go in and out of there without much risk. I'm relying on your resourcefulness, comrade.}
{378}{}{It'll be hard carrying that hunk of metal out of there. But it's true - if not me, who else? Proceeding.}
{379}{}{I have the power armor. If not for it, I wouldn't get out of there alive.}
{1379}{}{I have the power armor. If not for it, I wouldn't get out of there alive.}
{380}{}{Power armor delivery. We were delivering it to the Puerto base. You'll have to return it to our base.}
{381}{}{Excellent work. But you'll have to return it to our base.}
{382}{}{Wha-at, giving up this cool armor? Aren't you asking a bit too much?}
{383}{}{This set of T-51b powered infantry armor is the property of the Brotherhood of Steel. You got a problem with that, civilian?}
{384}{}{Yes, someone here has problems. It's you. Take it if you can, that power armor is mine now!}
{385}{}{No, no problems at all. I'm happy to get rid of this excess cargo.}
{386}{}{Of course, I'll happily get rid of this excess cargo.}
{387}{}{Thanks for the help. You'll make a fine warrior. When I get to the base, I'll explain everything to command. But for now, bring the armor to the quartermaster. And for now, I need some rest.}
{388}{}{See you at the base, paladin Barkley.}
{389}{}{Sorry, but I already delivered the armor to the quartermaster in Puerto.}
{1389}{}{Sorry, but I already delivered the armor to the quartermaster in Puerto.}
{390}{}{Thanks for the help. You'll make a fine warrior. When I get to the base, I'll explain everything to command. And for now, I need some rest.}
{391}{}{See you at the base, paladin Barkley.}
{392}{}{Thanks for the help. You know, you remind me of one Vault dweller, he helped us get rid of the supermutants in California. Since then, no civilian has been as helpful as they were. Right on, warrior.}
{393}{}{The Brotherhood is worth fighting for. Maybe we could continue our adventure, if you don't mind?}
{394}{}{Exactly. Now I can go back to the base with a clear conscience. Even though I can already imagine the kind of shame that is waiting for me there. The entire unit wiped out, the cargo lost. This will be remembered for a long time, even if the tribunal admits I did everything right.}
{395}{}{I'm sure your brothers will understand.}
{396}{}{Yeah, trouble definitely is waiting for you. Without a doubt.}
{397}{}{Thanks for the help. You'll make a fine warrior. When I get to the base, I'll explain everything to command. And for now, I need some rest.}
{398}{}{Perhaps we'll see each other again sometime. Good luck.}
{399}{}{Then why not come with me? I need combat support.}

#Team
{400}{}{Will you come with me? Having an experienced warrior defend me would definitely help.}
{401}{}{Sure. But, as you see, I am not in the best shape. With that kind of trauma I'll have a hard time defending even myself.}
{402}{}{Alright. But can you at least talk?}
{403}{}{Fine, I'll do it myself.}
{404}{}{Yes. But with two, it's easier to glow in front of these things. At the moment, this is not the best approach.}
{405}{}{If you were soldiers, I'd give you orders. But with this kind of unit we'll lose any kind of tactical superiority we could have. Get rid of the ballast if you want me to defend you.}
{406}{}{Then I am no longer interested.}
{407}{}{Fine, I'll talk to the others.}
{408}{}{I'm in your debt. If you're going to our base in Puerto, then I can escort you there.}
{409}{}{Yes, I'm heading right there. Let's go there together.}
{410}{}{No. My destination is different. Perhaps some other time our paths will cross.}
{411}{}{We need to put away our weapons for now.}
{412}{}{Are you out of your mind? You want to stab me in the back or something?}
{413}{}{On a second thought, you're right, it was a dumb idea. Forget it.}
{414}{}{No, we need to show that we are friendly. To avoid creating conflict.}
{415}{}{Hm-m. Fine. But keep in mind - I can take out my gun in 0,75 seconds.}
{416}{}{Great.}
{417}{}{Why don't you wear your previous armor, and give this one to me?}
{418}{}{With pleasure. The previous one was tailored for me.}
{419}{}{Great.}
{420}{}{Defend this position. I need to go somewhere nearby.}
{421}{}{Good idea. Go scout while I clean the ammunition.}
{422}{}{Uhh, okay.}
{423}{}{Prepare to go further.}
{424}{}{Lead the way. I hope you know of a safe route.}
{425}{}{Uhh, of course. Let's go.}
{426}{}{It is time to say goodbye. This is where our paths diverge.}
{427}{}{You sure? Fine. But don't forget about Barkley, friend.}
{1427}{}{You sure? Fine. But don't forget about Barkley, friend.}
{428}{}{I won't. Until we meet again, paladin Barkley.}
{429}{}{What was I even thinking of doing? I need you to not be breakfast for glowing ants.}
{430}{}{Let's go. I need an experienced warrior to defend me.}
{431}{}{But I could die without your help.}
{432}{}{Believe me, alone you have a much better chance of remaining in the dark. I'll draw the attention of too many ghouls.}
{433}{}{Alright.}
{434}{}{I'll definitely not manage to do it without you. If you refuse, then I'm outta here.}
{435}{}{I just knew I couldn't count on you... Fine, the leg doesn't hurt that much, I can move.}
{436}{}{Good.}
{437}{}{You know, you really will be a burden. It will be better to go alone. Bye.}
{438}{}{I'm in your debt. If you need help, I'm listening to you.}
{439}{}{Let's go. A long and dangerous trek awaits us.}

{450}{}{What do you think of this place?}
{451}{}{Not much. There is no point staying here.}
{452}{}{Right.}
{453}{}{This is a Brotherhood outpost. Welcome. But keep in mind that there are strict rules here. Command won't like you going around without permission.}
{454}{}{I still can't believe our fort was destroyed. The best of the best served there.}
{455}{}{Just some more ruins of an old city. All of California is in a similar shape.}
{456}{}{This place looks like heaven after Inferno. But still, the Brotherhood was there too.}
{457}{}{Looks like tinsmiths live here. They had an agreenment with the Brotherhood to maintain technology in the outpost.}
{458}{}{A big developing city. Only place in California one could compare it to is the Hub. It's good to see civilization getting back on it's feet.}
{459}{}{I read about this church in the reports made by the scribes. Looks like the local leader has good relations with the Brotherhood.}
{460}{}{Sorry, this is classified information, I can't discuss it with you.}
{461}{}{The way they organize themselves isn't bad. Even though they have a long way to go to achieve the kind of order we have in our Brotherhood.}
{462}{}{This is no vault. It's a crypt.}
{463}{}{This is our outpost. Of course, one can't even begin to compare to the main base, but it's better than nothing.}
{464}{}{I'd say a lot, but you know it perfectly well, brother.}
{1464}{}{I'd say a lot, but you know it perfectly well, sister.}
{465}{}{There's nothing left for me. Without the Brotherhood, I can only help people like you.}
{466}{}{Isn't this the fort you were heading to. Are you not happy?}
{467}{}{Just pure dissapointment. California HQ will be mad if they know how things are going here. You know, I wouldn't mind following you to the nearby settlements. I want to breathe some fresh air before returning to service.}
{468}{}{Still having nightmares about Inferno, yes? I understand.}

{470}{}{Tell me about your Brotherhood.}
{471}{}{I can't say much. Some of the information may be strategically important.}
{472}{}{Then forget it.}
{473}{}{Where is the main base of the Brotherhood located?}
{474}{}{Alright. This is everything I wanted to know about the Brotherhood.}
{475}{}{Where is your local base located?}
{476}{}{On the coast of the bay, in Rocky Point. Locals just call it Puerto.}
{477}{}{That question should be reserved for command. I'm just a soldier fulfilling my orders.}
{478}{}{What are you doing in the Sonora desert?}
{479}{}{HQ is a long way from here, in California. And here, in the Sonora desert, we have a small fort.}
{480}{}{I don't want to talk about it. Such a preposterous defeat in Puerto only fills me with anger.}
{481}{}{I can't believe it...}
{482}{}{Are you okay?}
{483}{}{My brothers and sisters... Such a ridiculous death... What could have happened?}
{484}{}{Probably some negligent quartermaster интенданта или какая-нибудь протечка.}
{485}{}{Nonsense! We were always very careful with our technology and weaponry! I refuse to believe it was an error on behalf of the personnel. It could have only been sabotage.}
{486}{}{Well, you do have plenty of enemies...}
{487}{}{Fine, I'm sorry that I yelled at you. It's just after the events in Inferno, to discover such a blow to the Brotherhood - it's too much.}
{488}{}{I understand. But on the bright side, you're now completely free and no longer have to fulfill orders, no?}
{489}{}{I don't think I could ever be fine with rural life in these wild lands. We should continue moving on. Lead the way, I'm still with you, comrade.}
{490}{}{Let's go.}
{491}{}{Looks like someone really didn't like your Brotherhood.}
{492}{}{Exactly! It could have only been sabotage.}
{493}{}{I blew up a couple of torpedoes in the hold. Problem?}
{1493}{}{I blew up a couple of torpedoes in the hold. Problem?}
{494}{}{Why?! What did the Brotherhood even do to you?!}
{495}{}{You have caused too much trouble in Sonora. There is no place for you here.}
{496}{}{I dunno, really. I just wanted to watch the big explosion.}
{497}{}{Looks like I hit the wrong button. I have no idea how it happened.}
{1497}{}{Looks like I hit the wrong button. I have no idea how it happened.}
{498}{}{You're an idiot redneck! You should have died in the womb!}
{499}{}{Hey, hey.}
