{100}{}{You see Paladin Barkley.}
{101}{}{You see a thick-skinned soldier. His unwavering face depicts full readiness for battle.}
{102}{}{Change of construction.}
{103}{}{Thanks, doc.}
{104}{}{The traitor! You'll die like a lousy dog!}
{105}{}{Bastards! You will pay for the death of my comrades!}
{106}{}{M-mutants, fuck them! A little more, and I'll shoot them. Are you with them for the same thing?}

{110}{}{I can't believe my eyes! How did this happen?}
{111}{}{Welcome to the Brotherhood.}
{112}{}{That's not why I serve as a paladin.}
{113}{}{Hmm, it looks like the intelligence made a mistake by a couple of zeros in the number of the enemy.}
{114}{}{Eh, reminds me of the old days...}

#Counter dialogue
{200}{}{Argh, damn... I almost shot you. I thought you were another mutant. Are you from a support group?}
{201}{}{What kind of group? What are we talking about?}
{202}{}{Damn it. So the Brotherhood didn't send you to help? It's a bad business. Then what are you doing in this cursed place?}
{203}{}{Just looking for useful things. Usually, deserted ruins are full of them.}
{204}{}{Ugh. So you're a scavenger? (sigh) It looks like all my luck came out last year.}
{205}{}{What is it?}
{206}{}{I'm looking for someone. But it's personal.}
{207}{}{OK... Let's assume that this is true. Do you want to look for someone else for me?}
{208}{}{Have you lost someone?}
{209}{}{It was I who responded to a radio request for help.}
{1209}{}{It was me who responded to a radio request for help.}
{210}{}{At least one happy news for the whole day.}
{211}{}{Tell me what happened.}
{212}{}{You should have shot, you idiot. Now it's my turn...}
{213}{}{So you're from the Brotherhood of Steel? I hate you all. Die, scum!}

{220}{}{Yes, the Brotherhood of Steel sent me on a rescue mission.}
{221}{}{Hmm. I don't remember you. Show me your badge.}
{222}{}{Token? But I don't serve the Brotherhood. I was just hired.}
{223}{}{That's it. I was warned that the Brotherhood in Arizona is not in the best shape. Sadly. Where are the others?}
{224}{}{Who are you talking about? I'm alone.}
{1224}{}{Who are you talking about? I'm alone.}
{225}{}{Damn it! What are they thinking about? That one mercenary can handle such a situation? However, a small group has a tactical advantage among the ruins... Okay, I hope that at least you won't get in the way.}
{226}{}{So what happened?}
{227}{}{Em... Here, I have the Brotherhood badge. Do you believe it now?}
{228}{}{I know the name on this badge. You have one attempt to justify your lies.}
{229}{}{Em... To hell with it. Die!}
{230}{}{Yes, I'm not from the Brotherhood. I just thought you were about to shoot me...}
{231}{}{Ugh, you pussy shit, and how can I trust you now?}
{232}{}{Why don't you tell me what happened and we'll try to help each other?}
{233}{}{Look, I know you're in trouble. Now it doesn't matter who serves where. It is important to help each other.}
{234}{}{OK. Don't try to fool my balls anymore. I don't tolerate lies.}
{235}{}{Uh, okay. Maybe then you'll tell the truth, what are you doing here?}

{240}{}{My squad was ambushed by local creatures. In all this turmoil, I have lost the rest of the team and cannot contact them. Besides, I injured my leg during the fight.}
{241}{}{Aren't you military? And even with a full set.}
{242}{}{Clear. The operation failed before it even started.}
{243}{}{No one expected to encounter resistance in these ruins. We thought there was no life here, so we went through the city so as not to encounter mutants in the desert.}
{244}{}{Okay. So what's your plan?}
{245}{}{I need to assemble a squad if there is anyone else to assemble. And somehow put yourself in order to continue to follow to the destination... Hey, show your civic duty - do me a favor.}
{246}{}{Sure. I can't leave a man in trouble.}
{247}{}{I knew I could rely on you. If I complete my mission, I will not remain in debt.}
{248}{}{That's right.}
{249}{}{You're out of luck, soldier. I'm not the kind of person who cares about other people's problems. Give away all your ammunition in a good way...}
{250}{}{You're talking about a dangerous event. Why on earth would I take such a risk?}
{251}{}{Don't worry about the payment. When we get to the base, you will be rewarded handsomely.}
{252}{}{I really hope so.}
{253}{}{Yes, by the way. My name is Paladin Barkley. You can look around for now. But be careful on the way out, I've set a couple of traps there.}
{254}{}{OK.}
{255}{}{I'm not interested in awards. My village needs protection.}
{256}{}{If we get to the base, I'll talk about your problem with the elders. In the meantime, help me.}
{257}{}{Okay.}

{260}{}{Show me how to get out of here safely.}
{261}{}{There are several traps in the corridor. Watch your feet carefully.}
{262}{}{Thank you.}
{263}{}{Listen, I have a bunch of questions.}

#Repeat dialog
{300}{}{Report the situation.}
{301}{}{Everything is calm.}
{302}{}{Yes?}
{303}{}{We need to talk.}
{304}{}{What do you want to know?}
{305}{}{Enough talking.}
{306}{}{Put aside the conversations. We're not up to it right now.}
{307}{}{Yes, I guess you're right.}
{308}{}{A little more, and I'll shoot all these mutants!}
{309}{}{Come on, never mind.}

{310}{}{So, what should I do?}
{311}{}{Heal my injury and find the rest of the team. After that, we will discuss the further plan.}
{312}{}{The task is clear.}
{313}{}{A serious wound. I may not be able to cope.}
{314}{}{Just find the medicines. They were among the things in our convoy. Hurry up, while the ghouls haven't gutted everything yet.}
{315}{}{How did you manage to do that?}
{316}{}{Caught in a trap. These creatures set traps in our path and set a smoke screen. Sons of bitches, got caught like a rookie...}
{317}{}{Clearly. Let's repeat our plan.}
{318}{}{I'm starting the task.}
{319}{}{I'm going on a search.}

{320}{}{Who else was in the squad?}
{321}{}{Several people. Half of them are dead, I don't know anything about the rest.}
{322}{}{Go on.}
{323}{}{I'm going on a search.}
{324}{}{The last time I was contacted by a squire in the supermarket area, but since then the connection with him has been lost.}
{325}{}{The knight held the defense at the ambush point, right next to the monument.}
{326}{}{Diana was also with us, she is one of the Followers of the Apocalypse. I heard her screams in the distance the ghouls were dragging her somewhere.}
{327}{}{Who else was on the team?}
{328}{}{What if they're all dead?}
{329}{}{Then I am obliged to collect their name tags to inform the command and honor their memory.}
{330}{}{Where did the attack on the convoy take place?}
{331}{}{It's in the northwest, on the fifth highway. Right next to some monument.}
{332}{}{Clear.}
{333}{}{I don't understand how the ghouls were able to overcome an armed convoy.}
{334}{}{These creatures are wild, but they are smart enough to fight. A long life in the ruins has taught them a lot.}
{335}{}{What did they do?}
{336}{}{We were ambushed. Ghouls set traps on the road and lured us to the most inconvenient place for protection. We were surrounded and began to throw bags of dust. A smoke screen rose around them, from which everyone was dragged away in turn.}
{337}{}{Go on.}
{338}{}{We killed a few of the creatures, but there were too many of them. And when the frontal attack began, only I managed to cope. I had to retreat... Damn, what a pity I didn't have time to use the power armor!}
{339}{}{I'm sorry.}
{340}{}{Everyone has failures, Paladin. You are no exception.}
{341}{}{Someone else?}
{342}{}{OK. Let's see what's left there.}
{343}{}{You have a serious wound. What can I do?}
{344}{}{I'm almost back to normal. It remains to find the missing members of the squad. After that, we will discuss the further plan.}
{345}{}{We need to find Diana. Perhaps she is still alive and needs help.}
{346}{}{We need to find Diana. Maybe she's still alive and needs help. I would also like to get some treatment.}
{347}{}{I managed to find the knight's body. I will continue to search.}
{348}{}{I managed to find the squire's body. I will continue to search.}

{350}{}{Your brothers are dead. Here are their tokens. I'm sorry.}
{351}{}{They died fighting like real warriors. Bright memory to them... What about the girl? We had a civilian with us, a teacher from the Followers of the Apocalypse.}
{352}{}{I don't know anything about her.}
{353}{}{I need to know for sure. The command gave a clear instruction to escort her to her destination. She was entrusted to my protection. I can't break orders by leaving her to her own devices.}
{354}{}{I'll try to find out what happened to her.}
{355}{}{Diana is forcibly detained in the building of the old church.}
{356}{}{Holding back? Who! These mutants don't even have articulate speech.}
{357}{}{No, not these, others. They have some kind of cult there.}
{358}{}{I don't understand anything. Maybe this cult controls the rippers? We need to find out more information. But even more important is to save Diana from captivity.}
{359}{}{I'll think about how it can be done.}
{360}{}{Diana is dead. That's right.}
{361}{}{It's a bad business. I'm going to get a big reprimand, and maybe a tribunal because of this girl. I wouldn't want to go back to a stuffy bunker in California. Okay, thanks for the help, comrade.}
{362}{}{Is that all you've been looking for?}
{363}{}{Diana is waiting for us at the exit. You can talk to her.}
{364}{}{Great job, comrade. I owe you.}
{365}{}{Is that all you've been looking for?}
{366}{}{Diana has already left the city. She didn't want to linger in this hell.}
{367}{}{She left and didn't warn you? What a bitch. I've been risking my life here trying to find her... Okay, let him roll wherever he wants. Now she is not under my command.}
{368}{}{Is that all you've been looking for?}
{369}{}{I managed to find Diana.}
{370}{}{What's wrong with her? Is she alive?}
{371}{}{I'm going to look for the others.}
{372}{}{They died fighting like real warriors. Bright memory to them...}
{373}{}{That's right. But I still can't return to the base without completing the main task.}
{374}{}{What kind of task?}
{375}{}{Delivery of power armor. This was the main cargo that we were taking to the base in Puerto. Now the armor is in the hands of the Rippers. This is a huge loss.}
{376}{}{There is no power armor where you were attacked. The mutants dragged her along with other things to the old church.}
{377}{}{So we need to return it. You already know how to get in and out there without much risk. I rely on your resourcefulness, comrade.}
{378}{}{It won't be easy to get this piece of hardware out. But really - who else, if not me? I'm going on a mission.}
{379}{}{The armor is with me. If it wasn't for her, I wouldn't have gotten out of there alive.}
{1379}{}{The armor is with me. If it wasn't for her, I wouldn't have gotten out of there alive.}
{380}{}{Delivery of power armor. We were taking her to the base in Puerto. You'll have to bring her back to our base.}
{381}{}{Great job. But you'll have to bring her back to our base.}
{382}{}{What, to give away such a cool armor? Don't you want too much?}
{383}{}{This is the property of the Brotherhood of Steel. Is there a problem, civilian?}
{384}{}{Yes. Problems. At you. Suck it, because the armor is mine now!}
{385}{}{No, no problem. I will be happy to get rid of the extra load.}
{386}{}{Of course, I will be happy to get rid of the extra load.}
{387}{}{Thank you for your help. You'll make a great fighter. When I get to the base, I'll tell the command about everything. In the meantime, take the armor to the quartermaster. I still need to recuperate before sending it.}
{388}{}{See you at the base, Paladin Barkley.}
{389}{}{Sorry, but I've already taken the armor to the quartermaster in Puerto.}
{1389}{}{Sorry, but I already took the armor to the quartermaster in Puerto.}
{390}{}{Thank you for your help. You'll make a great fighter. When I get to the base, I'll tell the command about everything. In the meantime, I need to recuperate before leaving.}
{391}{}{See you at the base, Paladin Barkley.}
{392}{}{Thank you for your help. You remind me of a resident from the vault who helped us deal with super mutants in California. No civilian has ever been so useful to the Brotherhood. Keep it up, fighter.}
{393}{}{For the sake of the Brotherhood, it's worth trying. Do you mind if we continue our journey?}
{394}{}{That's right. Now I can go to the base with a clear conscience. Although I can already imagine what a shame awaits me there. The whole squad was killed, and the cargo was lost. It will be remembered for a long time, even if the tribunal recognizes that I did everything right.}
{395}{}{Surely your brothers will understand you.}
{396}{}{You're definitely in trouble. Beyond any doubt.}
{397}{}{Thank you for your help. You'll make a great fighter. When I get to the base, I'll tell the command about everything. In the meantime, I need to recuperate before sending.}
{398}{}{Maybe we'll see each other again. Good luck.}
{399}{}{Then come along with me? I need combat support.}

#Team
{400}{}{Will you come with me? I could use the protection of an experienced soldier.}
{401}{}{I have no doubt. But, as you can see, I'm not in proper shape right now. With such an injury, I can hardly even defend myself.}
{402}{}{Clearly. But can you at least talk?}
{403}{}{Okay, I'll manage on my own.}
{404}{}{I have no doubt. But it's easier to show up in front of the rippers together. This is not the best tactic right now.}
{405}{}{If you were soldiers, I would still take command of you. But with such a squad, we will lose any tactical advantage. Get rid of the ballast if you want my protection.}
{406}{}{Then I withdraw my offer.}
{407}{}{Okay, I'll talk to the others.}
{408}{}{I'm in your debt. If you're going to our base in Puerto, then I can accompany you.}
{409}{}{Yes. That's where I'm going. Let's go together.}
{410}{}{No. I have another destination. Maybe another time our paths will converge.}
{411}{}{Now we need to put the weapons away.}
{412}{}{Are you out of your mind? Do you want to put me under attack?}
{413}{}{Really, a stupid idea. Forget it.}
{414}{}{No, we need to show our friendliness so as not to create a conflict.}
{415}{}{Hmm. Okay. But keep in mind - I'm pulling out a gun at a speed of 0.75 seconds.}
{416}{}{That's great.}
{417}{}{Let's get your old armor back. And give this one to me.}
{418}{}{With pleasure. The old one was my size.}
{419}{}{That's great.}
{420}{}{Defend this position. I need to get close.}
{421}{}{Good idea. Go scouting, and I'll clean the ammunition.}
{422}{}{Uh, okay.}
{423}{}{Get ready. We can move on.}
{424}{}{Lead the way. I hope you know a safe route.}
{425}{}{Uh, sure. Let's go.}
{426}{}{It's time to say goodbye. Then our paths diverge.}
{427}{}{Are you sure? Okay. But don't forget about Barclay, old man.}
{1427}{}{Are you sure? Okay. But don't forget about Barclay, Sister.}
{428}{}{I won't forget. See you later, Paladin Barkley.}
{429}{}{What am I doing? I need you not to become a breakfast of glowing ants.}
{430}{}{Come with me. I need the protection of an experienced soldier.}
{431}{}{But without your protection, I could die.}
{432}{}{Believe me, alone you have more chances to stay in the shadows. It'll attract too much ghoul attention.}
{433}{}{Clear.}
{434}{}{I definitely can't do it without you. If you refuse to participate, then I'm leaving town.}
{435}{}{I knew I couldn't rely on you... Okay, my leg doesn't hurt so much anymore, I can move.}
{436}{}{That's good.}
{437}{}{You know, you're going to be a burden. I'd rather walk alone. Later.}
{438}{}{I'm in your debt. If you need protection and escort, then I am at your disposal.}
{439}{}{Let's go, we are waiting for a long and dangerous road.}

{450}{}{What do you think about this place?}
{451}{}{Nothing special. There's no point in lingering here.}
{452}{}{Clear.}
{453}{}{This is an outpost of the Brotherhood. Welcome. But keep in mind that this is a strict regime object. The command won't like it if you flit around here without permission.}
{454}{}{I still can't believe our fort has been destroyed. The best of the best served in it.}
{455}{}{The next ruins of the old city. All of California lies in similar ruins.}
{456}{}{After Inferno, this place seems like paradise. And it seems that there was not without the Brotherhood of Steel.}
{457}{}{It seems that tinsmiths live here. The Brotherhood had a contract with them to maintain the outpost.}
{458}{}{A big developing city. In California, only the Hub can compare with it. It's nice to see that civilization is getting back on its feet.}
{459}{}{I read about this church in the scribes' reports. It seems the local leader is on good terms with the Brotherhood.}
{460}{}{Sorry, this is classified information, I can't discuss it with you.}
{461}{}{Not bad organization. Although they are far from the order in our Brotherhood.}
{462}{}{This is not a Vault. This is a crypt.}
{463}{}{This is our outpost. Of course, it does not compare with the main base. But it's better than nothing.}
{464}{}{I would tell you a lot, but you already know everything perfectly, brother.}
{1464}{}{I would tell you a lot, but you already know everything perfectly, sister.}
{465}{}{There's nothing else I can do. Without Brotherhood, I can only help people like you.}
{466}{}{This is the fort you were going to. Aren't you happy?}
{467}{}{A complete disappointment. The General Staff in California will be angry if they find out how things are going here. You know, I wouldn't mind accompanying you to the nearest settlements. I want to get some fresh air before returning to work.}
{468}{}{Inferno still dreams in nightmares, right? I understand.}

{470}{}{Tell me about your Brotherhood.}
{471}{}{I can't tell you much. Some information may have strategic value.}
{472}{}{Then let's go.}
{473}{}{Where is the main base of the Brotherhood?}
{474}{}{I see. That's all I was interested in about the Brotherhood.}
{475}{}{Where is your local base located?}
{476}{}{On the Gulf coast, in Rocky Point. Locals call it simply Puerto.}
{477}{}{This question should be asked to the command. I'm just a soldier, following orders.}
{478}{}{What are you doing in the Sonoran desert?}
{479}{}{The General Staff is far away in California. And here, in the Sonoran desert, we have a small fort.}
{480}{}{I don't want to talk about it. Such a ridiculous defeat in Puerto only fills me with anger.}
{481}{}{I can't believe...}
{482}{}{Are you okay?}
{483}{}{My brothers and sisters... Such a ridiculous death... What could have happened?}
{484}{}{Probably the negligence of the quartermaster or some kind of leak.}
{485}{}{Nonsense!  We have always been careful about weapons and equipment! I refuse to believe that it was a mistake by someone from the staff. It could only be a diversion.}
{486}{}{Well, you have a lot of enemies...}
{487}{}{Okay, I'm sorry I yelled. After the events in Inferno, it's too much to get such a blow to the Brotherhood.}
{488}{}{I understand. But now you are completely free from regulations and orders, aren't you?}
{489}{}{I don't think I can put up with rural life in these wild lands. We should move on. Lead on, I'm still with you, comrade.}
{490}{}{Let's go.}
{491}{}{Apparently, someone didn't like your Brotherhood very much.}
{492}{}{Precisely! It could only be a diversion.}
{493}{}{I blew up a couple of torpedoes in the hold. Are you not satisfied with this?}
{1493}{}{I blew up a couple of torpedoes in the hold. Are you not satisfied with this?}
{494}{}{Why?! What did the Brotherhood do to you?!}
{495}{}{You have created too many troubles in Sonora. You don't belong here.}
{496}{}{I don't even know. I just wanted to see the big bang.}
{497}{}{I think I pressed the wrong button. I don't know how it happened.}
{1497}{}{I think I pressed the wrong button. I don't know how it happened.}
{498}{}{You're a beaten-up redneck! You should have died in the womb!}
{499}{}{Well, well.}