{102}{}{ gets one bottle cap.}
{103}{}{This item won't help here.}
{104}{}{This won't help here}
{105}{}{This skill won't help here.}
{106}{}{This man refuses to go any further.}
{107}{}{This creature refuses to go any further.}
{108}{}{This hostile person refuses to obey you.}
{109}{}{This hostile creature refuses to obey you.}

#---------------------------------------------
# Names of skills and basic parameters
#---------------------------------------------
{110}{}{Small arms}
{111}{}{A big weapon}
{112}{}{Energy weapons}
{113}{}{Hand-to-hand combat}
{114}{}{Edged weapons}
{115}{}{Throwing}
{116}{}{First aid}
{117}{}{Doctor}
{118}{}{Stealth}
{119}{}{Hacking}
{120}{}{Theft}
{121}{}{Traps}
{122}{}{Science}
{123}{}{Repair}
{124}{}{Eloquence}
{125}{}{Trade}
{126}{}{Gambling}
{127}{}{Survival}

{130}{}{You have improved the skill "}
{131}{}{" on }
{132}{}{.}

{133}{}{[}
{134}{}{] }

{135}{}{Attitude}
{136}{}{Reputation}
{137}{}{Glory}
{138}{}{Level}

{140}{}{}
{141}{}{With your skills, this is not possible.}
{142}{}{This creature cannot be robbed.}
{143}{}{The victim didn't recognize your deception. You got out of the situation without consequences.}
{144}{}{This time you managed to convince the victim that there was a misunderstanding.}
{145}{}{The robot cannot be robbed while it is in active mode.}
{146}{}{ it is watching you too closely.}
{147}{}{Your skills do not allow you to heal these wounds without medication.}
{148}{}{In power armor, it is impossible to commit pickpocketing.}
{149}{}{It can't be done.}

{150}{}{Power}
{151}{}{Perception}
{152}{}{Endurance}
{153}{}{Charisma}
{154}{}{Intelligence}
{155}{}{Dexterity}
{156}{}{Luck}

#---------------------------------------------
# Gaining experience
#---------------------------------------------

{200}{}{You have received }
{201}{}{ experience points.}
{202}{}{experience points for successful dialogue.}
{203}{}{ experience points and reputation enhancement.}

#---------------------------------------------
# Injuries
#---------------------------------------------

{300}{}{Your left leg is crippled! You are suffering from severe pain.}
{301}{}{Your right leg is crippled! You are suffering from severe pain.}
{302}{}{Your left arm is crippled! You are suffering from acute pain.}
{303}{}{Your right arm is crippled! You are suffering from acute pain.}
{304}{}{Your eyes are crippled! You are suffering from unbearable pain.}
{305}{}{Ugh, it's going to take a very long time to heal...}

#---------------------------------------------
# Messages in battle
#---------------------------------------------

{320}{}{ hesitates to make an attack.}
{321}{}{ regenerates and restores some health.}
{322}{}{!!!}
{323}{}{Scared of fire }
{324}{}{flees.}
{325}{}{Damn it!}
{326}{}{ loses power and perception when an e/m pulse disables part of its electronics.}
{327}{}{!}
{328}{}{This cannot be done during combat.}
{329}{}{Pi!}

#---------------------------------------------
# Replicas of futility (the wrong object, skill, etc. was used)
#---------------------------------------------

{330}{}{Useless}
{331}{}{Not that}
{332}{}{Something's wrong}
{333}{}{To no avail}
{334}{}{It doesn't work}
{335}{}{Hmm?}
{336}{}{Too complicated}
{337}{}{Useless}
{338}{}{Useless}
{339}{}{Useless}

#---------------------------------------------
# Replicas upon completion of cases (mine clearance, repair, refueling of the bike, etc.)
#---------------------------------------------

{340}{}{Done}
{341}{}{Okay}
{342}{}{Great}
{343}{}{Done}
{344}{}{It turned out}
{345}{}{Success}
{346}{}{There is}
{347}{}{Done}
{348}{}{Done}
{349}{}{Done}

#---------------------------------------------
# The use of different items on the NPC
#---------------------------------------------

#Consumer goods
{400}{}{ refuses to eat it.}
{401}{}{This experience brought you resourcefulness.}
{402}{}{ will not eat during the fight.}
{403}{}{ refuses to take it out of your hands.}
{404}{}{This does not apply to robots.}
{405}{}{The free distribution of food has brought you experience and fame.}
{406}{}{It doesn't apply to plants.}
{407}{}{ refuses to accept it.}
{408}{}{This creature becomes more friendly to you.}
{409}{}{stimpacks only work on people.}
{410}{}{Animals and mutants do not drink alcohol.}
{411}{}{It won't work on flyers.}
{412}{}{ succumbs to the harmful effects of the chemical and becomes enraged.}
{413}{}{Alcohol? Not interested...}
{414}{}{That's what I've been missing!}
{415}{}{It is not necessary to tease the members of the Brotherhood with their own rations. You may be mistaken for a thief.}
{416}{}{Wow, that's generosity!}
{417}{}{Will you really just give it to me?}
{418}{}{This item will not work through the protective helmet of power armor.}
{419}{}{The free distribution of valuable liquid has brought you experience and fame.}

#Clutter items
{420}{}{I think it will be useful to me}
{421}{}{Wow! Thank you!}
{422}{}{The child accepts your gift with joy. Surely he will tell his friends about your action.}
{423}{}{The child does not want to accept your gift. He seems to sense a hidden threat in you.}
{424}{}{A shovel will definitely not help here.}
{425}{}{Hacking a robot requires skills, a decoder will not help here.}
{426}{}{poisoned!}
{427}{}{dies in terrible convulsions.}
{428}{}{falls dead.}
{429}{}{ loses consciousness and soon dies.}
{430}{}{ stops breathing.}
{431}{}{This cannot be done during combat.}
{432}{}{Your partner knows what this leads to.}
{433}{}{U-u-u!}
{434}{}{You're needlessly scaring the child. There will surely be a more worthy use for this trafei.}
{435}{}{You have made 20 signal cartridges from old festive pyrotechnics.}

#Ammunition items
{440}{}{}
{441}{}{}
{442}{}{}
{443}{}{}
{444}{}{}
{445}{}{}
{446}{}{}
{447}{}{}
{448}{}{}
{449}{}{}
{450}{}{}
{451}{}{}
{452}{}{}
{453}{}{}
{454}{}{}
{455}{}{}
{456}{}{}
{457}{}{}
{458}{}{}
{459}{}{}

#Items ammunition
{460}{}{}
{461}{}{}
{462}{}{}
{463}{}{}
{464}{}{}
{465}{}{}
{466}{}{}
{467}{}{}
{468}{}{}
{469}{}{}
{470}{}{}
{471}{}{}
{472}{}{}
{473}{}{}
{474}{}{}
{475}{}{}
{476}{}{}
{477}{}{}
{478}{}{}
{479}{}{}

#Other items
{480}{}{Usually keys are used on locks.}
{481}{}{Amazingly. And as soon as it occurred to you...}
{482}{}{The weapon should be used in combat mode, holding it in your hands.}
{483}{}{With the help of a surgical kit, you have cured all your injuries.}
{484}{}{With the help of a surgical kit, you cured the patient's injuries.}
{485}{}{This item should be used out of hand.}
{486}{}{It is unlikely that this will help in fixing the robot.}
{487}{}{ refuses your treatment.}
{488}{}{You don't need surgical treatment.}
{489}{}{This item should be used on a motorcycle.}
{490}{}{It won't help here.}
{491}{}{You have found the use of an ancient relic.}
{492}{}{Your shovel has fallen into disrepair.}
{493}{}{A surgical kit won't help here.}

#---------------------------------------------
# Dialog Options
#---------------------------------------------

#Critter
{500}{}{This hostile person will not talk to you.}
{501}{}{This robot has already been reprogrammed for your protection.}
{502}{}{You have reprogrammed the robot for your protection.}
{503}{}{}
{504}{}{You can't reconfigure the robot to protect yourself.}
{505}{}{What is it? Are you threatening me?}
{506}{}{This person will not communicate with you while you are holding a weapon in your hands.}
{507}{}{This person is near death and cannot talk right now.}
{508}{}{. . .}
{509}{}{The negotiations failed.}
{510}{}{?}
{511}{}{You see a Madman.}
{512}{}{Without access to fresh air }
{513}{}{suffocating in the freezer.}
{514}{}{What is it? Are you threatening me?}
{515}{}{Put away your weapon, otherwise I'll get mine}
{516}{}{Power armor alarms your interlocutor.}
{517}{}{...}
{518}{}{It seems this robot can't talk.}
{519}{}{This person refuses to obey you.}

#Computers
{550}{}{Access denied.}
{551}{}{This cannot be done during combat.}
{552}{}{The defense system has already been hacked.}
{553}{}{The defense system has been hacked!}
{554}{}{Access received.}
{555}{}{The game turned out to be very exciting.}
{556}{}{You can't find the password.}
{557}{}{You have installed the decoder. Now hacking a computer will become much easier.}
{558}{}{The decoder won't help here anymore. It's time to use skills.}
{559}{}{}

#Repair of equipment
{570}{}{ not in need of repair.}
{571}{}{This cannot be done during combat.}
{572}{}{}
{573}{}{You have no idea how it can be fixed. Perhaps the lack of skills will be solved by replacing parts.}
{574}{}{You have no idea how it can be fixed.}
{575}{}{Failure! You were unlucky and you were electrocuted.}
{576}{}{With these details, the repair will become a little easier.}
{577}{}{With these parts, the repair will become much easier.}
{578}{}{Additional details won't help here. It's time to use skills.}
{579}{}{You see the ripper.}

#---------------------------------------------
# Ring nicknames
#---------------------------------------------

#Important: male and female nicknames are antipodes and match by numbers with a difference of 50.
#- men's
{600}{}{Crusader}
{601}{}{Scorpio}
{602}{}{Cannibal}
{603}{}{The King}
{604}{}{Caesar}
{605}{}{Hidalgo}
{606}{}{Sergeant}
{607}{}{Fang}
{608}{}{Sledgehammer}
{609}{}{Dynamite}
{610}{}{Smoker}
{611}{}{Hulk}
{612}{}{Sniper}
{613}{}{Macho}
{614}{}{Mr. X}
{615}{}{Big Brother}
{616}{}{Mad Dog}
{617}{}{Rip}
{618}{}{The Ripper}
{619}{}{Butcher}
{620}{}{Leprechaun}
{621}{}{Whisperer}

#- female
{650}{}{Black Widow}
{651}{}{Scolopendra}
{652}{}{Brain Eater}
{653}{}{The Queen}
{654}{}{Cleopatra}
{655}{}{Duchess}
{656}{}{Sergeant}
{657}{}{Claws}
{658}{}{Machete}
{659}{}{Magnum}
{660}{}{Napalm}
{661}{}{Ross}
{662}{}{Marine}
{663}{}{Muchacho}
{664}{}{Mrs. X}
{665}{}{Big Mama}
{666}{}{Crazy Bitch}
{667}{}{Bad Girl}
{668}{}{Angel}
{669}{}{Wild Jane}
{670}{}{Snow White}
{671}{}{Ruby}

#---------------------------------------------
# Cartography
#---------------------------------------------

{1400}{}{A new place has been opened on the world map}
{1401}{}{: }
{1402}{}{.}
{1403}{}{ Suspicious sounds are coming from the cave.}

#Attention! The list should be copied unchanged from the file .../game/MAP.MSG
{1500}{}{Villa}
{1501}{}{Flagstaff}
{1502}{}{Garage City}
{1503}{}{San Brahmin}
{1504}{}{Two-Sun}
{1505}{}{Puerto}
{1506}{}{Rangers}
{1507}{}{Phoenix}
{1508}{}{Platform}
{1509}{}{Casa Grande}
{1510}{}{Hermosillo}
{1511}{}{San Felipe}
{1512}{}{Inferno}
{1513}{}{Casa Nueva}
{1514}{}{-}
{1515}{}{The motel}
{1516}{}{The Dayglow}
{1517}{}{-}
{1518}{}{Santa Ana}
{1519}{}{-}
{1520}{}{Jackals}
{1521}{}{Pit stop}
{1522}{}{Villa}
{1523}{}{Vault 27}
{1524}{}{Brotherhood Camp}
{1525}{}{Raiders}
{1526}{}{Wasteland}
{1527}{}{Mountainous terrain}
{1528}{}{Ruins}
{1529}{}{The coast}
{1530}{}{Puerto}
{1531}{}{Gold!}
{1532}{}{Henry Beamis}
{1533}{}{Roadside cafe}
{1534}{}{Bomber}
{1535}{}{Petro-Chico truck}
{1536}{}{The cry of silence}
{1537}{}{Outdoor cinema}
{1538}{}{Padre}
{1539}{}{Baron of Arizona}
{1540}{}{Snowfall}
{1541}{}{The Lost Refuge}
{1542}{}{Mobile Fortress}
{1543}{}{Legend City}
{1544}{}{-}
{1545}{}{-}
{1546}{}{Quartzsite}
{1547}{}{A chance meeting}
{1548}{}{Winon Camp}