{102}{}{ receives one bottle cap.}
{103}{}{This item won't help here.}
{104}{}{This won't help here.}
{105}{}{This skill won't help here.}
{106}{}{This person refuses to go further.}
{107}{}{This creature refuses to go further.}
{108}{}{This hostile person refuses to obey you.}
{109}{}{This hostile creature refuses to obey you.}

#---------------------------------------------
#   Skill and character variable names
#---------------------------------------------
{110}{}{Small Guns}
{111}{}{Big Guns}
{112}{}{Energy Weapons}
{113}{}{Unarmed}
{114}{}{Melee Weapons}
{115}{}{Throwing}
{116}{}{First Aid}
{117}{}{Doctor}
{118}{}{Sneak}
{119}{}{Lockpick}
{120}{}{Steal}
{121}{}{Traps}
{122}{}{Science}
{123}{}{Repair}
{124}{}{Speech}
{125}{}{Barter}
{126}{}{Gambling}
{127}{}{Survival}

{130}{}{You've raised your "}
{131}{}{" skill by }
{132}{}{.}

{133}{}{[}
{134}{}{] }

{135}{}{Attitude}
{136}{}{Reputation}
{137}{}{Fame}
{138}{}{Level}

{140}{}{}
{141}{}{Impossible with your level of skill.}
{142}{}{This creature cannot be stolen from.}
{143}{}{The victim did not recognize your deception. You suffer no consequences.}
{144}{}{You managed to convince the victim that a misunderstanding ocurred. This time.}
{145}{}{A robot cannot be stolen from while it is active.}
{146}{}{ is keeping too close of an eye on you.}
{147}{}{Your skills are too low to heal these wounds without proper medicine.}
{148}{}{Pickpocketing while in power armor is impossible.}
{149}{}{Impossible to do.}

{150}{}{Strength}
{151}{}{Perception}
{152}{}{Endurance}
{153}{}{Charisma}
{154}{}{Intelligence}
{155}{}{Agility}
{156}{}{Luck}

#---------------------------------------------
#   Receiving experience
#---------------------------------------------

{200}{}{You receive }
{201}{}{ experience.}
{202}{}{ experience for successful conversation.}
{203}{}{ experience and a reputation increase.}

#---------------------------------------------
#   Traumas
#---------------------------------------------

{300}{}{Your left leg is crippled! You are in serious pain.}
{301}{}{Your right leg is crippled! You are in serious pain.}
{302}{}{Your left arm is crippled! You are in intense pain.}
{303}{}{Your right arm is crippled! You are in intense pain.}
{304}{}{Your eyes are crippled! You are in unbearable pain.}
{305}{}{Oh, this is going to take a long time to heal...}

#---------------------------------------------
#   Combat messages
#---------------------------------------------

{320}{}{ hesitates to attack.}
{321}{}{ regenerates a part of their health.}
{322}{}{!!!}
{323}{}{Fearing fire, }
{324}{}{ runs away.}
{325}{}{Dammit!}
{326}{}{ loses strength and perception due to the EMP disabling part of it's electronics.}
{327}{}{!}
{328}{}{Impossible to do while in combat.}
{329}{}{Squeak!}

#---------------------------------------------
#   Lines for an action yielding no results (using the wrong item, skill, etc.)
#---------------------------------------------

{330}{}{Useless.}
{331}{}{I'm doing it wrong.}
{332}{}{Something's wrong.}
{333}{}{Nothing changed.}
{334}{}{Doesn't work.}
{335}{}{Hm-m?}
{336}{}{Too difficult.}
{337}{}{Useless.}
{338}{}{Useless.}
{339}{}{Useless.}

#---------------------------------------------
#   Lines for completing an action (disabling a trap, repairing an object, refueling the bike, etc.)
#---------------------------------------------

{340}{}{Done.}
{341}{}{Okay.}
{342}{}{Great.}
{343}{}{Done.}
{344}{}{I did it.}
{345}{}{Success.}
{346}{}{I did it.}
{347}{}{Done.}
{348}{}{Done.}
{349}{}{Done.}

#---------------------------------------------
#   Using items on NPCs
#---------------------------------------------

#Consumption items
{400}{}{ refuses to eat this.}
{401}{}{Your resourcefulness has brought you experience.}
{402}{}{ will not eat during combat.}
{403}{}{ refuses to take this item from your hands.}
{404}{}{Cannot be used on robots.}
{405}{}{Freely giving out food has brought you experience and fame.}
{406}{}{Cannot be used on plants.}
{407}{}{ refuses to use this item.}
{408}{}{This creature becomes more receptive toward you.}
{409}{}{Stimpaks only work on human beings.}
{410}{}{Animals and mutants do not drink alcohol.}
{411}{}{Has no effect on floaters.}
{412}{}{ succumbs to the harmful effects of the chemical and falls into a rage.}
{413}{}{Alcohol? Not interested...}
{414}{}{That's what I was missing!}
{415}{}{Teasing members of the Brotherhood with their own rations is not the best idea. You could be seen as a thief.}
{416}{}{How generous!}
{417}{}{You're really just giving this to me?}
{418}{}{This item will have no effect so long as you're wearing the power armor's protective helmet.}
{419}{}{Freely giving out a valuable liquid has brought you experience and fame.}

#Clutter items
{420}{}{I'll find a use for this.}
{421}{}{Wow! Thank you!}
{422}{}{The child graciously accepts your gift. Perhaps they will tell others about you.}
{423}{}{The child doesn't want to accept your gift. Perhaps they feel that you are a threat, somehow.}
{424}{}{A shovel is certainly not going to help here.}
{425}{}{Hacking robots requires skill. A decoder won't help here.}
{426}{}{ is poisoned!}
{427}{}{ dies in terrible agony.}
{428}{}{ falls dead.}
{429}{}{ falls unconscious and soon dies.}
{430}{}{ stops breathing.}
{431}{}{Impossible to do in combat.}
{432}{}{Your companion knows what this leads to.}
{433}{}{Ou-u-u!}
{434}{}{You're just scaring the child for no reason. Surely this trophey has a more worthy use.}
{435}{}{You produce 20 signal flares from old pyrotechnics.}

#Ammo
{440}{}{}
{441}{}{}
{442}{}{}
{443}{}{}
{444}{}{}
{445}{}{}
{446}{}{}
{447}{}{}
{448}{}{}
{449}{}{}
{450}{}{}
{451}{}{}
{452}{}{}
{453}{}{}
{454}{}{}
{455}{}{}
{456}{}{}
{457}{}{}
{458}{}{}
{459}{}{}

#Ammo
{460}{}{}
{461}{}{}
{462}{}{}
{463}{}{}
{464}{}{}
{465}{}{}
{466}{}{}
{467}{}{}
{468}{}{}
{469}{}{}
{470}{}{}
{471}{}{}
{472}{}{}
{473}{}{}
{474}{}{}
{475}{}{}
{476}{}{}
{477}{}{}
{478}{}{}
{479}{}{}

#Other items
{480}{}{Keys are usually used on locks.}
{481}{}{Incredible. One can only wonder how such amazing ideas can enter one's head...}
{482}{}{Weapons should be used in combat, while being held in one's arms.}
{483}{}{Using the surgery kit, you heal all your traumas.}
{484}{}{Using the surgery kit, you heal the patient's traumas.}
{485}{}{This item should be used while being held in one's arms.}
{486}{}{I doubt this will help repair the robot.}
{487}{}{ refuses your medical assistance.}
{488}{}{You are not in need of surgery.}
{489}{}{This item should be used on the motorcycle.}
{490}{}{This won't help here.}
{491}{}{You find a use for an ancient relic.}
{492}{}{Your shovel is no longer functional.}
{493}{}{A surgery kit won't help here.}

#---------------------------------------------
#   Dialogue
#---------------------------------------------

#Critters
{500}{}{This hostile person refuses to talk to you.}
{501}{}{This robot has already been reprogrammed to defend you.}
{502}{}{You reprogram the robot to defend you.}
{503}{}{}
{504}{}{You fail to reprogram the robot to defend you.}
{505}{}{What? Are you threatening me?}
{506}{}{This person will not talk to you while you are holding a weapon.}
{507}{}{This person is near death and cannot speak right now.}
{508}{}{. . .}
{509}{}{Negotiations failed.}
{510}{}{?}
{511}{}{You see a Crazed One.}
{512}{}{Having breathed in all oxygen, }
{513}{}{ suffocates in the freezer.}
{514}{}{What? Are you threatening me?}
{515}{}{Put your weapon away or I'll draw mine.}
{516}{}{This person won't talk to you while you are wearing power armor.}
{517}{}{...}
{518}{}{It doesn't seem like this robot was designed with the ability to talk.}
{519}{}{This person refuses to obey you.} 

#Computers
{550}{}{Access denied.}
{551}{}{Cannot be done in combat.}
{552}{}{Security system already hacked.}
{553}{}{Security system hacked!}
{554}{}{Access granted.}
{555}{}{The game turned out to be quite fun.}
{556}{}{You fail to guess the password.}
{557}{}{You have installed a decoder. Hacking this computer will be much easier now.}
{558}{}{The decoder won't be of any further help to you here. It's time to use your skills.}
{559}{}{}

#Equipment repair
{570}{}{ does not require any repairs.}
{571}{}{Cannot be done in combat.}
{572}{}{}
{573}{}{You have no idea how this can be fixed. Perhaps simply replacing components will make up for your lack of skills.}
{574}{}{You have no idea how this can be fixed.}
{575}{}{Failure! You were unlucky and got electrocuted.}
{576}{}{These components make repairs a little easier.}
{577}{}{These components will make repairs much easier.}
{578}{}{Additional components won't be of any further help to you here. It's time to use your skills.}
{579}{}{You see a ghoul.}

#---------------------------------------------
#   Phoenix Fighting Ring Nicknames
#---------------------------------------------

#Important: male and female nicknames are opposites. The difference between their numbers is 50.
#- male
{600}{}{Crusader}
{601}{}{Scorpion}
{602}{}{Cannibal}
{603}{}{King}
{604}{}{Caesar}
{605}{}{Hidalgo}
{606}{}{Sergeant}
{607}{}{Fang}
{608}{}{Sledgehammer}
{609}{}{Dynamite}
{610}{}{Smoker}
{611}{}{Hulk}
{612}{}{Sniper}
{613}{}{Macho}
{614}{}{Mr. X}
{615}{}{Big Brother}
{616}{}{Mad Dog}
{617}{}{Dudd}
{618}{}{Ripper}
{619}{}{Butcher}
{620}{}{Leprechaun}
{621}{}{Whisperer}

#-female
{650}{}{Black Widow}
{651}{}{Scolopendra}
{652}{}{Brain Eater}
{653}{}{Queen}
{654}{}{Cleopatra}
{655}{}{Duchess}
{656}{}{Sergeant}
{657}{}{Claws}
{658}{}{Machete}
{659}{}{Magnum}
{660}{}{Napalm}
{661}{}{Ross}
{662}{}{Marine}
{663}{}{Muchacho}
{664}{}{Mrs X}
{665}{}{Big Mom}
{666}{}{Mad Bitch}
{667}{}{Bad Girl}
{668}{}{Angel}
{669}{}{Wild Jane}
{670}{}{Snow White}
{671}{}{Ruby} 

#---------------------------------------------
#   Map
#---------------------------------------------

{1400}{}{A new location has been added to the world map}
{1401}{}{: }
{1402}{}{.}
{1403}{}{Suspicious noises are coming out of the cave.}

#Warning! List of names is to be copied (no changes) from the file .../game/MAP.MSG
{1500}{}{Villa}
{1501}{}{Flagstaff}
{1502}{}{Garage City}
{1503}{}{San Brahmin}
{1504}{}{Two Sun}
{1505}{}{Puerto}
{1506}{}{Rangers}
{1507}{}{Phoenix}
{1508}{}{Platform}
{1509}{}{Casa Grande}
{1510}{}{Hermosillo}
{1511}{}{San Filipe}
{1512}{}{Inferno}
{1513}{}{Casa Nueva}
{1514}{}{-}
{1515}{}{Motel}
{1516}{}{Dayglow}
{1517}{}{-}
{1518}{}{Santa Ana}
{1519}{}{-}
{1520}{}{Jackals}
{1521}{}{Bike}
{1522}{}{Villa}
{1523}{}{Vault 27}
{1524}{}{Brotherhood Camp}
{1525}{}{Raiders}
{1526}{}{Wasteland}
{1527}{}{Rocky area}
{1528}{}{Ruins}
{1529}{}{Coast}
{1530}{}{Puerto}
{1531}{}{Gold!}
{1532}{}{Henry Bemis}
{1533}{}{Roadside Cafe}
{1534}{}{Bomber}
{1535}{}{Petro Chico Truck}
{1536}{}{The Cry of Silence}
{1537}{}{Outdoor cinema}
{1538}{}{Padre}
{1539}{}{Baron of Arizona}
{1540}{}{Snowfall}
{1541}{}{Lost Vault}
{1542}{}{Mobile Fortress}
{1543}{}{Legend City}
{1544}{}{-}
{1545}{}{-}
{1546}{}{Quartz}
{1547}{}{Random Encounter}
{1548}{}{Camp Wynon} 
