{100}{}{This is a computer.}
{101}{}{You see an ancient computer. It's a wonder it still works.}

#Dialogue
{200}{}{System loading complete.}
{201}{}{Complete session.}
{202}{}{Go back.}
{203}{}{Welcome to the digital card index of the Mexicali police departament.}
{204}{}{Database loadidng in progress...}

{210}{}{Attack in the supermarket.}
{211}{}{"...You have known him for a long time. What do you think was the reason he commited such an act?}
{212}{}{Continue.}
{213}{}{What is there to talk about? He's a war veteran. You know what happened in Anchorage. He may have been rewarded for his service, but it did nothing to resolve the trauma in his head.}
{214}{}{Continue.}
{215}{}{In the head? He was injured?}
{216}{}{Continue.}
{217}{}{No! He went crazy! It was for you that he took a machine gun and started shooting down people in the supermarket. For him, it's a continuation of the war. He thought he was shooting the reds..."}
{218}{}{Stop playback.}

{220}{}{Complaints regarding a construction project.}
{221}{}{"...I'm telling ya - they agreed with my plan! It's perfectly legal! And how will the neighbors prove that I got into their house while digging?}
{222}{}{Continue.}
{223}{}{Let's assume that what you just said is true. But what about the vibrations from your construction project that don't allow them to relax? And what about the dust, the broken glass and the endless trucks? I was also told that you are using the labor of hired workers without a license.}
{224}{}{Continue.}
{225}{}{It's an expensive project... Ar-rgh, don't you get it?! When the next world war starts, and it definitely will, nobody will care about vibrations and trucks! I'm creating a fallout shelter to save myself and my family. And what will the neighbors do? O-oh, they'll come right to me to beg me to let them in. You'll see, officer. You'll see..."}
{226}{}{Stop playback.}

{230}{}{Accusation of racism.}
{231}{}{"...Ma'am, please calm down-}
{232}{}{Continue.}
{233}{}{Calm down?! These barbarians want me to die! My neighbors have been trying to drive me out of time for a long time. This is not the first year I had to tolerate their transgressions. But now their arrogance has grown out of any and all bounds! I pay a lot of money for my house and I will not let anyone accuse me of having connections with the reds just because I have chinese blood. Do something! You're police for god's sake!}
{234}{}{Continue.}
{235}{}{Of course, ma'am... uhh, we have no tolerance towards racism, either... But you see, what you told us about is not enough to accuse your neighbors of anything. A dead cat, some writing on walls and anonymous notes - none of this suggests any real threat. We won't b-}
{236}{}{Continue.}
{237}{}{Why am I even spending time with you?! It's obvious already that you're in league with them! Give me my statement back, I'm leaving...}
{238}{}{Continue.}
{239}{}{Oof... What a bitch. Third one this month. Rodrigo, do you think she's really one of them?}
{240}{}{Continue.}
{241}{}{Let her go, Nick. Better if her neighbors drive her mad than if she really turns out to be one of the reds... Oh, dammit, I didn't even turn off the dictaphone..."}
{242}{}{Stop playback.}

{250}{}{The cactus incident.}
{251}{}{"Well, well, well, boys. Tell me how it all went down, but this time, the *truth*.}
{252}{}{Continue.}
{253}{}{Well, we were just walking in the desert and sat beside a cactus. And this thing fell on Paco! We didn't do anything bad, really, seignior!}
{254}{}{Continue.}
{255}{}{Uh-uh. Then how do you explain the charred laser trails on the cactus stump? [silence] Guys, I don't want to put pressure on you. I want to help. Tell me the truth, and the only thing you'll receive is a warning. [silence] Okay, okay. Let me help you remember.}
{256}{}{Continue.}
{257}{}{Paco took a laser pistol from his father without permission, after which you decided to test it on a cactus. Was that how it went down? [silence] But the cactus turned out to be more durable than you expected, and the energy was used up too quickly, so you decided to finish it with your hands? [silence] Guys, you do know that shooting cactuses is forbidden in our state. Not to mention the use of energy weapons by minors.}
{258}{}{Continue.}
{259}{}{Seignior! Seignior! Just please don't tell our parents!"}
{260}{}{Stop playback.}

{270}{}{The robot case.}
{271}{}{"...So you insist that the robot was not defective, and that it was acting independently?}
{272}{}{Continue.}
{273}{}{I'm afraid that doesn't quite sound right, seignior officer... The robot series "Mr. Handy" only executes given tasks. But look at the Wilson family inquiries! I think they had... issues in their relations with each other.}
{274}{}{Continue.}
{275}{}{Relationship issues? Yes, we know that there were frequent arguments. But how could have this influenced the robot, which "only executes given tasks"?}
{276}{}{Continue.}
{277}{}{Well... the robot's interpreter isn't perfect. And when the mother threatens to "chop" her son, and the son asks the robot to "kill the parents", you can see how something could have been interpreted the wrong way...}
{278}{}{Continue.}
{279}{}{...do you even understand the implications of what you are insisting on? Your service-center services robots whose program strictly forbids harming humans. And now these robots, you see, "misunderstood" something. Stop trying to confuse us! Admit the defect, and we will lower the punishment!"}
{280}{}{Stop playback.}

{290}{}{Anti-american protest.}
{291}{}{"So you do admit your guilt, that you joined an illegal rally the goal of which was to overthrow the current government?}
{292}{}{Continue.}
{293}{}{Guilt? No way! These americans enslaved all of Sonora! It is they who are the criminals! They and our sellout government! How can you call this rally illegal?...}
{294}{}{Continue.}
{295}{}{I repeat my que..."}
{296}{}{Continue.}
{297}{}{A group of people begins to shout. You make out the words "Mexico for Mexicans".}
{298}{}{Continue.}
{299}{}{"Stop! Silence! Everyone shut up!"}
{300}{}{Continue.}
{301}{}{The group of people begin to shout even louder. You can barely make out anything.}
{302}{}{Stop playback.}