{100}{}{It's a computer.}
{101}{}{You see an ancient computer. It's amazing that it still works.}

#Dialog
{200}{}{The system is loaded.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Welcome to the electronic file of the Mexicali Police Department.}
{204}{}{The database is being loaded...}

{210}{}{Supermarket attack.}
{211}{}{"...You've known him for a long time. What do you think caused such an act?"}
{212}{}{Next.}
{213}{}{"What's there to tell? He's a war veteran. You know, all this horror at Anchorage. And although he was awarded for excellent service, the injury in his head remained."}
{214}{}{Next.}
{215}{}{"In the head? Was he injured?"}
{216}{}{Further.}
{217}{}{"No, he's gone mad! It was for you that he took a machine gun and shot people in a supermarket. And for him, it is a continuation of the war. He thought he was shooting at the Reds..."}
{218}{}{Stop recording.}

{220}{}{Complaints about construction work.}
{221}{}{"...I'm telling you - my plan is fully coordinated! Everything is according to the law! And how will the neighbors prove that I got into their bowels when mining the soil?"}
{222}{}{Next.}
{223}{}{"Suppose. But what about the vibrations from the construction work that prevent them from resting? As well as dust, broken windows, and endless trucks? They also say that you use the labor of hired workers without a license."}
{224}{}{Next.}
{225}{}{"This is an expensive project... Ar-rh, yes, you understand! When the world war begins, and it will definitely begin, no one will care about vibrations and trucks! I'm building a bomb Vault to save myself and my family. And what will the neighbors do? Oh, they'll run to me to ask for Vault. You'll see, Officer. You'll see..."}
{226}{}{Stop recording.}

{230}{}{Accusation of racism.}
{231}{}{"...Ma'am, please calm down..."}
{232}{}{Next.}
{233}{}{"Calm down? These barbarians want me dead! The neighbors have been trying to drive me out of town for a long time. I've been putting up with their antics for years. But they have already crossed all the boundaries! I pay dearly for the house and will not allow anyone to accuse me of having ties with the Reds just because I have Chinese blood in me. Do something, you're the police!"}
{234}{}{Next.}
{235}{}{"Of course, ma'am... uh, we don't tolerate racism either... But understand - your evidence is not enough to accuse the neighbors. A dead cat, notes on the walls, and anonymous notes - all this does not indicate a real threat. We are not smo..."}
{236}{}{Next.}
{237}{}{"Why am I wasting my time here with you! And so it is clear - you are all racists here! Racists! Give me my application, I'm leaving..."}
{238}{}{Next.}
{239}{}{"Ugh... What a bitch. This is the third one in a month. Do you think, Rodrigo, is she really one of "these"?"}
{240}{}{Next.}
{241}{}{"Let him go, Nick. It is better to let the neighbors push her to the limit than suddenly she will find herself in ties with the Reds... Oh, shit, I didn't turn off the recorder..."}
{242}{}{Stop recording.}

{250}{}{The case of the cactus.}
{251}{}{"So, guys. Tell us how it happened."}
{252}{}{Next.}
{253}{}{"Well, we were just walking in the desert and sat down near a cactus. And then this thing fell on Paco! We didn't do anything wrong, honestly, señor!"}
{254}{}{Next.}
{255}{}{"Yeah. Then how do you explain the charred laser marks on the stump of the cactus? [silence] Guys, I don't want to put pressure on you. I want to help. Tell me the truth, and you'll only get off with a warning. [silence] All right. Let me help you remember."}
{256}{}{Next.}
{257}{}{"Paco took his father's laser pistol without permission, after which you decided to test it on a cactus. Is that how it was? [silence] But the cactus turned out to be stronger, and the charge ended too quickly, and you decided to finish off the cactus manually? [silence] Guys, you know that shooting at cacti is prohibited in the state. Not to mention the use of weapons..."}
{258}{}{Next.}
{259}{}{"señor! señor! Just don't tell your parents!"}
{260}{}{Stop recording.}

{270}{}{The case of the robot.}
{271}{}{"...So you're saying that the robot had no defects, and it acted independently?"}
{272}{}{Next.}
{273}{}{"I'm afraid it doesn't sound quite right in this form, señor Officer... The robot of the "Mr. Handy" series only performs the assigned tasks. But look at the requests of the Wilson family! I think they had... some relationship problems."}
{274}{}{Next.}
{275}{}{"Relationship problems? Yes, we know that there were regular quarrels in their family. But how could this affect a robot that "only performs the assigned tasks"?"}
{276}{}{Next.}
{277}{}{"Well... The robot interpreter is not perfect. And when the Wilsons' mother threatens to "cook a chop" out of her son, and the son asks the robot to "kill the parents," then something here could be misunderstood..."}
{278}{}{Next.}
{279}{}{"So. Do you understand what you're saying? Your service center serves robots that are banned from harming people in the program. And now these robots, you see, have "misunderstood" something there. Stop misleading the investigation! Admit the defect and we will reduce the penalty!"}
{280}{}{Stop recording.}

{290}{}{Anti-American protest.}
{291}{}{"So do you admit your guilt in participating in an illegal rally aimed at overthrowing the current government?"}
{292}{}{Next.}
{293}{}{"Guilt? Well, no! These Americans have enslaved all of Sonora! They are the criminals! They and our corrupt government! How can you call the rally illegal?..."}
{294}{}{Next.}
{295}{}{"So. I will repeat my question..."}
{296}{}{Next.}
{297}{}{"Mexico to Mexicans! Mexico to Mexicans!"}
{298}{}{Next.}
{299}{}{"Stop it! Silence! Everyone be silent!"}
{300}{}{Next.}
{301}{}{"Or are you going to put us in jail?" - "We demand a lawyer!" - "Are you happy with your salary?" - "While Madera was in power, the Americans did not climb to us..." - "Have you already forgotten that massacre on the border?" - "Mexico to Mexicans!"}
{302}{}{Stop recording.}