{100}{}{You see a slot machine.}

{110}{}{The slot machine doesn't work.}
{111}{}{Sorry, please insert coins into the machine to start the game.}
{112}{}{Filling the entire hall with a simple melody, the slot machine comes to life!}

{120}{}{Surviving that stress one more time? The machine doesn't even have any prize coupons left.}
{121}{}{Enough gambling.}
{122}{}{You are too tired for gambling at this time.}
{123}{}{You need to heal first.}
{124}{}{Due to disrepair, the machine has problems with responses. With your skills, it is impossible to beat it.}
{125}{}{This will be ve-ery hard.}

{130}{}{You beat the machine by }
{131}{}{ points.}
{132}{}{In total, you have collected }
{133}{}{ points out of the 1000 possible ones.}
{134}{}{Yes!}
{135}{}{More of that!}
{136}{}{Eat this!}
{137}{}{Heh!}
{138}{}{Deal with it!}
{139}{}{Who's the best now?}
{140}{}{You lost. The machine took }
{141}{}{points away from you.}
{142}{}{Hey!}
{143}{}{No!}
{144}{}{Dammit!}
{145}{}{Damn this piece of Pre-War junk!}
{146}{}{Dang it!}
{147}{}{HM-M!}
{148}{}{HOW?!}
{149}{}{This angers me.}

{200}{}{Congratulations for winning! You are our *first* winner! Please choose a prize coupon.}
{201}{}{I'll take the super-strength coupon.}
{202}{}{I'll take the hyper-perception coupon.}
{203}{}{I'll take the trans-endurance coupon.}
{204}{}{I'll take the extra-tractiveness coupon.}
{205}{}{I'll take the mega-intellect coupon.}
{206}{}{I'll take the supra-agility coupon.}
{207}{}{I'll take the multi-luck coupon.}
{208}{}{I don't need any coupon.}