{100}{}{Here is a slot machine.}

{110}{}{The slot machine is not working.}
{111}{}{Please insert coins into the slot machine to start the game.}
{112}{}{Having thundered to the whole hall with an uncomplicated melody, the slot machine came to life!}

{120}{}{Relive such tension again? The slot machine still has no prize coupons left.}
{121}{}{I've had enough of gambling.}
{122}{}{You're too weak to gamble right now.}
{123}{}{The first thing you need to heal.}
{124}{}{Due to the dilapidation of the machine, there are problems with the response. With your skills, it is impossible to beat him.}
{125}{}{It's going to be very, very difficult.}

{130}{}{You beat the slot machine on }
{131}{}{ points.}
{132}{}{Total you have earned }
{133}{}{ points out of 1000 possible.}
{134}{} {Yes!}
{135}{}{Yes!}
{136}{}{That's it!}
{137}{}{Ha!}
{138}{}{Get it!}
{139}{}{Who's the best here?}
{140}{}{You've lost. The machine was removed }
{141}{}{points from your account.}
{142}{}{Hey!}
{143}{}{No!}
{144}{}{Damn!}
{145}{}{Damn tin can!}
{146}{}{Damn it!}
{147}{}{Um-m!}
{148}{}{How is that?!}
{149}{}{It makes me angry}

{200}{}{Congratulations on your victory! You are our first winner! Take the prize coupon.}
{201}{}{I'll take the superpower coupon.}
{202}{}{I'll take the ultra perception coupon.}
{203}{}{I'll take a super-tolerance coupon.}
{204}{}{I'll take the extra-attractiveness coupon.}
{205}{}{I'll take the megaintellect coupon.}
{206}{}{I'll take the hyper-agility coupon.}
{207}{}{I'll take a multi-issue coupon.}
{208}{}{I don't need it.}