{110}{}{This jukebox is broken.}
{111}{}{The jukebox has been restored and is ready to make terrible creaking noises called music.}
{112}{}{The jukebox has been successfully restored. Oh, how loud!}
{113}{}{The musical automaton is finally coming out of the string.}

{120}{}{*Boom boom*}
{121}{}{*sh-sh-sh*}
{122}{}{*sadum-padum*}
{123}{}{*Shi-boom, shi-boom*}
{124}{}{*Sha-la-la*}
{125}{}{*Òrum-pum-pum*}