#---------------------------------------------------------
#  Translated by Georg; revised by garwert.
#---------------------------------------------------------
{100}{}{You see a pup.}
{101}{}{You see a young member of the Jackal tribe.}
{102}{}{*Hisses*}

#Replies
{200}{}{*Grits teeth*}
{201}{}{*Hisses*}
{202}{}{Woof!}
{203}{}{Come any closer and I'll bite you.}
{204}{}{*Whines and pushes away from you*}
{205}{}{Grrr!}

{210}{}{*Snorts*}
{211}{}{*Sniffs you*}
{212}{}{Woof!}
{213}{}{Woof-woof!}
{214}{}{My teeth are sharper than yours.}

{220}{}{*Cheerful whooping*}
{221}{}{*Jumps at you playfully*}
{222}{}{Play with me.}
{223}{}{Can we roll on the ground together?}
