{100}{}{You see a puppy.}
{101}{}{Here is a young savage from the tribe of Jackals.}
{102}{}{*Hisses*}

#Response remarks
{200}{}{*Baring his teeth*}
{201}{}{*Hisses*}
{202}{}{Woof!}
{203}{}{Stay away or I'll bite.}
{204}{}{*Whining and huddling away from you*}
{205}{}{R-r-r!}

{210}{}{*Snorts*}
{211}{}{*Sniffing at you*}
{212}{}{Woof!}
{213}{}{Woof-woof!}
{214}{}{My teeth are sharper than yours.}

{220}{}{*Cheers*}
{221}{}{*Jumps to show you*}
{222}{}{Play with me.}
{223}{}{Let's have a roll?}