{100}{}{You see a bitch.}
{101}{}{Here is one of the bitches of the Jackal tribe.}

#Retaliatory remarks
{200}{}{ (baring his teeth) Shh! Don't come near me, stranger!}
{201}{}{Bye.}
{202}{}{I just want to talk to you about the tribe.}
{203}{}{Empty barking only teases my stomach. Bring food or leave me.}
{204}{}{Okay.}
{205}{}{The food was delicious. What do you want to know?}
{206}{}{Enough talking. Goodbye.}
{207}{}{Where did you all come from?}
{208}{}{I remember the days when I was a puppy. Hostile tribes drove us from our former lands. Therefore, we wandered for a long time in the desert in search of a suitable place. But they found only this. Here we waited out the season of dust storms. It was a hungry time. Only the most persistent survived. Since then, two generations of puppies have grown up in these burrows.}
{209}{}{What do you eat?}
{210}{}{Whatever you have to. Anything we find or catch in the wastelands.}
{211}{}{Is it normal to eat human flesh, in your opinion?}
{212}{}{What else can we eat if there is nothing else? Not even grass grows in the desert. Even the water in the river makes the bellies swell and bleed... hmm. Do you have food.}
{213}{}{Are there other strangers here besides me?}
{214}{}{Yes... our lunch. A tough outsider. Very good meat. (grinning) You can't get to him, the Nocturnal Beast protects the warehouses well. Only a Rabid Bitch knows how to talk to him.}
{215}{}{How do you feel about a Rabid Bitch?}
{216}{}{(with a touch of timidity and trepidation) She's in charge here, she speaks for all of us. Don't ask me about the Bitch anymore!}
{217}{}{How do you feel about Black Fang?}
{218}{}{Fang... (disapproving growl) Impudent dog. Beats women, takes away food. Beat the Fang if you want to take his place.}
{219}{}{What is this gear of skulls in the main hall?}
{220}{}{Just a sign from the past. Ask the Crazy Bitch about him.}
{221}{}{Tell me more.}
{222}{}{No one. Last lunch slipped away from us. Left us hungry... (spits angrily)}