#---------------------------------------------------------
#  Translated by Georg, garwert.
#---------------------------------------------------------
{100}{}{You see Slithery Skull.}
{101}{}{You see one of the members of the Jackal tribe.}
{102}{}{Don't come any closer to me.}

#Replies
{200}{}{Keep your distance, outsider.}
{201}{}{Alright.}
{202}{}{Tell me about Black Fang.}
{203}{}{The best warrior out of them all. Fear him, outsider. Show him respect. He has brought us more food using his traps than any other man. And that is worth excusing his bad temper.}
{204}{}{Tell me about Rabid Bitch.}
{205}{}{The pack is not supposed to badmouth their alpha. So we try to show respect and share our prey with her. Although in these hungry times, I wouldn't want to share a single leather strip with a leader like her, let alone food.}
{206}{}{Which one of them is more worthy of being the leader of your tribe?}
{207}{}{Fang has to drive the tribe into the mountains, away from these barren lands. Rabid Bitch wants to establish an alliance with outsiders. Which one is better? Let the pack decide. I'll follow.}
{208}{}{Bye.}
