#---------------------------------------------------------
#  Translated by Georg, garwert.
#---------------------------------------------------------
{100}{}{You see a female Jackal.}
{101}{}{You see a female member of the Jackal tribe. She was "lucky" to survive the Ranger raid.}
{102}{}{What do I do now?}

#Replies
{200}{}{Wait! Have mercy! Don't kill me!}
{201}{}{So be it. You can live for now.}
{202}{}{Tell me what happened here.}
{203}{}{It's the Rangers! They attacked us with their fiery sticks and killed all the males... and the females... and the pups...}
{204}{}{How did you manage to survive?}
{205}{}{I was catching iguanas for my pups in the wastes. When the outsiders came, I was watching from afar... Damned Rangers!}
{206}{}{And you left your pups for dead?}
{207}{}{I... (falls to her knees) I couldn't... I was terrified and hungry... I couldn't do anything...}
{208}{}{Now live with it. I'm leaving.}
