{100}{}{You have a Slippery Skull in front of you.}
{101}{}{You see one of the savages of the Jackal tribe.}
{102}{}{Stay away from me.}

#Retaliatory remarks
{200}{}{Keep your distance from me, stranger.}
{201}{}{Okay.}
{202}{}{Tell me about Black Fang.}
{203}{}{The best warrior of all. Fear him, stranger. Show him respect. With his traps, he brought more food than any other. And it's worth it to forgive his bad temper.}
{204}{}{Tell me about the Rabid Bitch.}
{205}{}{They don't talk bad about a bitch. She is our leader, everyone should honor her and share food. But in a hungry time, it is difficult for such a leader to sell even a piece of old clothes.}
{206}{}{Which of them is more worthy to be the leader of the tribe?}
{207}{}{Fang must lead the tribe into the mountains, away from these barren lands. The Mad Bitch wants to find an alliance with outsiders. Which is better? Let the pack decide. I'll follow everyone.}
{208}{}{Bye.}