{100}{}{You see a female Jackal.}
{101}{}{Here is a wild woman of the Jackal tribe. She was "lucky" to survive the Ranger raid.}
{102}{}{What should I do now?}

#Retaliatory remarks
{200}{}{Stop! Have mercy! Don't kill!}
{201}{}{So be it. Live for now.}
{202}{}{Tell me what happened here.}
{203}{}{It's all Rangers! They attacked with their fire sticks and killed all the males... and then all the females... and all the puppies...}
{204}{}{How did you manage to survive?}
{205}{}{I used to catch iguanas for my puppies in the wastelands. When the strangers came, I was watching from the side... Damn rangers!}
{206}{}{And you left your puppies to their own devices?}
{207}{}{I... (falls to his knees) I could not... Terror and hunger gave me legs...}
{208}{}{Now live with it. And I'm leaving.}