{100}{}{You see a Nocturnal Beast.}
{101}{}{You see the guardian of the Jackals. He faithfully guards the warehouses of his tribe.}
{102}{}{Sh-what for sh-jokes?!}

#Replicas floating
{120}{}{No one will dare to take my place.}
{121}{}{Only I can guard these burrows, only I!}
{122}{}{R-I will tear anyone who breaks into the warehouses!}
{123}{}{The tribe needs me.}
{124}{}{The Crazy Bitch wants me to guard the warehouses. And I'm guarding.}
{125}{}{They say a stranger is wandering in the burrows.}
{126}{}{R-r-r! I smell c-surveillance!}
{127}{}{*Sniffing*}
{128}{}{I smell a stranger.}
{129}{}{These burrows lack the heart-rending moan of strangers.}

#Retaliatory remarks
{200}{}{Get out! A stranger has no place in these warehouses!}
{201}{}{Okay.}