#---------------------------------------------------------
#  Translated by Georg; revised by garwert.
#---------------------------------------------------------
{100}{}{You see Night Beast.}
{101}{}{You see the Jackal guard, watching his tribe's storerooms.}
{102}{}{Wh-at kind of t-rick is this?!}

#Floating lines
{120}{}{Nobody dar-res take my place.}
{121}{}{Only I can guard these bur-rrows, only I!}
{122}{}{I'll r-rrip and tear-rr anyone who breaks into the storerooms!}
{123}{}{The tribe needs me.}
{124}{}{Rabid Bitch wants me to guard the storerooms. And so I guard.}
{125}{}{They say there is an outsider-r in the burrows.}
{126}{}{Grrr! I feel like someone's watchin-ng me!}
{127}{}{*Sniffs*}
{128}{}{I feel the smell of an outsider.}
{129}{}{These burrows lack the heartr-rrending screams of outsiders.}

#Replies
{200}{}{Get out of here! Don't come near the storerooms, outs-sider!}
{201}{}{Alright.}
