{100}{}{You see a savage.}
{101}{}{You see one of the males of the Jackal tribe. His gaze excites like the gaze of a wolf.}
{102}{}{ }

#Replicas floating
{120}{}{When my stomach is empty, I howl at the moon.}
{121}{}{A beautiful day for sacrifice.}
{122}{}{This skin is completely bald.}
{123}{}{Shhh, stop barking! A stranger will hear...}
{124}{}{Parasites on my body do not let me sleep.}
{125}{}{This s-bitch will be mine!}
{126}{}{*Sniffing*}
{127}{}{*He scratches behind his ear with a flourish*}
{128}{}{Traps need bait.}
{129}{}{It's time to sharpen your fangs.}

#Retaliatory remarks
{200}{}{*Baring his teeth*}
{201}{}{When you die, I'll rip your meat off your braids.}
{202}{}{My fangs are hungry for your blood.}
{203}{}{Your brain will be mine when you die.}
{204}{}{}

{205}{}{Killing you will earn me fame and respect.}
{206}{}{Do you want to die, a stranger?}
{207}{}{Mmm, what a juicy stranger.}
{208}{}{}
{209}{}{}

{210}{}{My life is yours now, stranger-jacques.}
{211}{}{*Plaintive whining*}
{212}{}{}
{213}{}{}
{214}{}{}