{100}{}{You see a raider.}
{101}{}{You see your partner in the raid on the burrows.}
{102}{}{It was a glorious battle, wasn't it?}

#Retaliatory remarks
{200}{}{It's time for an offensive. Are you still with us?}
{201}{}{What do you recommend for an effective fight?}
{202}{}{The jackals are pretty weak, so we won't need any serious weapons. But they are pressed by numbers and huddle in packs in cramped corridors. It would be nice to throw a grenade there or charge them with a shot.}
{203}{}{Sure. Let's go.}
{204}{}{Let's go.}
{205}{}{More?}
{206}{}{Beware of their poisoned blades and claws. And we need to do something about this impenetrable darkness. Surely there are torches in the burrows, it's worth finding them and setting them on fire.}
{207}{}{This is not a good time to chat. Let's move on.}
{208}{}{I didn't expect to see a ranger here. Yes, even in custody. They don't seem to be as cool as everyone thinks they are.}
{209}{}{What do you think - were these the last ones?}
{210}{}{It looks like it. These burrows are cleared of parasites. It remains to feel the corpses for valuables and get home.}
{211}{}{OK.}
{212}{}{[Next]}