{100}{}{You see the delegate.}
{101}{}{You see a negotiator from the Rangers.}
{102}{}{The ambassador was killed... jackals. And I have nothing to do with it.}
{103}{}{What kind of cretin started a massacre? All my work went down the jackal's ass!}
{104}{}{Something happened. Now the Jackals are chasing me away.}

#Retaliatory remarks
{200}{}{And here is our hero. I can only envy your diplomacy. It is given to units to reach the mind of such a wild tribe. Well done! Keep it up.}
{1200}{}{And here is our heroine. I can only envy your diplomacy. It is given to units to reach the mind of such a wild tribe. Well done! Keep it up.}
{201}{}{I try. How are the negotiations going?}
{202}{}{Yes, yes?}
{203}{}{Let's try another topic.}
{204}{}{Goodbye, Ambassador.}

{210}{}{How are the negotiations going?}
{211}{}{It's hard, but progress is tangible. The first thing you need is to appease the Jackals with a small present of provisions. And then we will teach them to lead a civilized way of life.}
{212}{}{What do you think? Someone broke all the plans by killing the Jackals. It remains to be hoped that these savages will not scatter across Sonora and Mojave in search of new victims.}
{213}{}{Will Jackals be of use?}
{214}{}{Rangers can learn tactics and survival from them. And they can also be used to monitor the terrain. It's already worth a lot. But I'm worried about their stupid principles - cannibalism, belief in the Spirit of the vault, underground lifestyle and other nonsense. It will take a long time to get rid of this.}
{215}{}{How do you feel about an alliance with Jackals?}
{216}{}{A difficult question. Many are dissatisfied with the concessions and believe that the Jackals should simply be eliminated. From this, the reputation of the Rangers was a little shaken. But after communicating with the tribe, I realized that this is not the way out. Their "flock" is scattered throughout the Mojave Desert and further west. By eliminating this lair, we will only anger the other clans. It's like throwing a stone into a river to change its course.}
{217}{}{Why *in fact* did the Rangers agree to the alliance?}
{218}{}{Obviously, there are other motives besides your diplomacy. Jackals have been terrorizing this district for many years. But there are no other ways to the north. Rangers have a special interest in the northern lands, it's a long story. In addition, the tribe can become a means of pressure on the surrounding settlements.}
{219}{}{So far I haven't even managed to meet with the manager. I think these negotiations will not get off the ground without your help.}