{100}{}{Here is a ranger.}
{101}{}{You see the prisoner. The jackals pretty much beat up this poor guy.}
{102}{}{Great. So I can live a little longer.}
{103}{}{Is that all you've learned, Ranger?}
{104}{}{Ranger successfully left the valley of Jackals.}

#Dialogue BEFORE escape
{200}{}{Leave me alone, dirty dick... Damn it, you're not one of the savages, right? Did the Jackals catch you too?}
{201}{}{In a way.}
{202}{}{No, dummy, I'm sunbathing here.}
{203}{}{Ugh, I thought I'd never see a normal person again...}
{204}{}{So you're very lucky, buddy.}
{205}{}{Is it that bad?}

{210}{}{Look, I have to get out of here. Help me! My ranger friends won't forget this help.}
{211}{}{It's too early to leave. Wait here.}

{220}{}{Can you walk?}
{221}{}{With difficulty. The jackals scratched my legs so I wouldn't run away. Do you know how to heal wounds? If not, then find my stimpack. Surely it was taken by one of the savages.}
{222}{}{What is a "stimpack"?}
{223}{}{You really don't know? Damn it, I'm a dead man! Listen, this is such an ancient thing with a needle and a red liquid. Find it soon!}
{224}{}{Okay, I'll try to find him.}
{225}{}{Maybe I can find another way to get you back on your feet.}
{226}{}{I think so. At least I can get out.}
{227}{}{Great. Let's get out of here.}
{228}{}{It's too early to leave. Wait here.}

{230}{}{Can you fight?}
{231}{}{Only if you give me a weapon. The jackals took all my things, including my rifle. It can be anywhere and at anyone.}
{232}{}{Clearly. I'll take a note.}
{233}{}{Tell me how you got here.}
{234}{}{My group explored the area. And these cunning sons of bitches lured us into a trap. I'm the only one who survived.}
{235}{}{I see.}
{236}{}{Jackals did not dare to open battle?}
{237}{}{It's not their style. Individually, they are cowardly, attacking only as a whole pack... Arch, my legs are burning... Damn these savages!}
{238}{}{What were you looking for in such a wilderness?}
{239}{}{We were given a task. And orders are not discussed. This is the Rangers' charter.}
{240}{}{Okay, I'll take your word for it.}
{241}{}{It's too desolate and wild a place for the Rangers to be interested in.}
{242}{}{And you have an eye for lies... The commanders believed that the Jackals would be a good reason for a contract with a neighboring city.}
{243}{}{What kind of contract?}
{244}{}{Are you Rangers always keeping something back?}
{245}{}{Local settlements suffer from Jackals. If we got rid of them, we would increase our reputation in the neighboring settlements. Yes, they could also impose a lucrative contract on them. But first you need to collect strategic information about the enemy and the terrain... But how about you stop talking and get out of here faster?}
{246}{}{Not until I get more information.}
{247}{}{Good idea.}
{248}{}{What do you know about these burrows?}
{249}{}{I didn't see much. Be careful on the surface - there are a lot of traps around the hut.}
{250}{}{Clear.}

#Dialogue during and after the escape
{260}{}{I'll cover the rear. The main thing is not to attract attention.}
{261}{}{Let's go.}
{262}{}{We need to get out of here faster. Let's talk on the surface.}
{263}{}{Be careful. This building is full of traps. We need to move away.}
{264}{}{There is no sign of pursuit. It seems to have come off!}
{265}{}{Let's go.}
{266}{}{Don't worry about me, I'll find my way}
{267}{}{Have a safe journey.}

{270}{}{There is no sign of pursuit. It seems to have come off!}
{271}{}{Relax, we're safe.}
{272}{}{It won't be for long. Besides, I'll have to hobble on my sick legs to the nearest outpost and call for help. But I can handle it.}
{273}{}{Are you sure you don't need any help?}
{274}{}{Exactly. I know a couple of places here where you can take a break and gain strength.}
{275}{}{Well, you know better.}
{276}{}{I advise you to go along the river in short runs. So you will save energy.}
{277}{}{Yes, a good idea, although the path will be a little longer.}
{278}{}{[Next]}
{279}{}{Then have a good trip, Ranger.}
{280}{}{Thank you for your help, I will tell my colleagues at the base about your feat. If you ever find yourself there, ask Jason, it's me. And now it's time for me to go.}
{281}{}{See you later, Ranger.}

{290}{}{Stay here. I'm going to scout.}
{291}{}{Follow me.}
{292}{}{Put down your weapon, you're too noisy with it.}
{293}{}{Take off this armor. She gives you away in the dark.}