{100}{}{Here is Black Fang.}
{101}{}{You see a strong warrior of the Jackal tribe.}
{102}{}{}
{103}{}{You didn't have to piss me off, you geek.}
{104}{}{Sh-what for sh-jokes?!}
{105}{}{I'll kill you!}

#Floating replicas
{120}{}{Everyone should be afraid of me!}
{121}{}{I won't forgive, I won't forgive, I won't forgive!}
{122}{}{A rabid Bitch will crawl at my feet.}
{123}{}{Someday I will become the leader of the tribe.}
{124}{}{No one will dare to take my place!}
{125}{}{Someday I'll bring a Rabid Bitch to her knees.}
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

#Dialogue at the first meeting
{200}{}{You're trapped! Don't even try to resist. You're my prey now. Sha-a-a!}
{201}{}{I'm not going to hurt anyone.}
{202}{}{Wipe your dirty eyes, dog. You think too much about yourself.}
{203}{}{You will die in agony for your words!}
{204}{}{So, I'll have to subdue you...}
{205}{}{Yes... It's better this way. Now go ahead. I want to show you to a Rabid Bitch. You are my prey. Everyone should know this!}
{206}{}{Okay, lead on.}
{207}{}{A rabid Bitch went crazy, letting a stranger into our burrows. Just give me a reason and I'll rip your heart out with my claws!}
{208}{}{It won't come to that.}
{209}{}{You! You won't escape anymore, you piece of meat!}
{210}{}{We'll see about that...}
{211}{}{What do you need?}
{212}{}{Nothing. Bye.}
{213}{}{Wait, I don't want to hurt anyone!}
{214}{}{You're trapped, alien... Ar-r-r! The man with the iron skin! Who are you? What do you need?}
{215}{}{I need your death. Take off your capes and give me the spear.}
{216}{}{Everyone over here! Evil iron spirit in the burrows!}
{217}{}{But this was not worth doing ...}
{218}{}{Who's in charge?}
{219}{}{Do you want to talk to the chief? She's A Rabid Bitch. Let her deal with you, and I'll see you off.}

#Necklace
{220}{}{This necklace of cartridges doesn't suit you.}
{221}{}{What are you talking about? Don't fill my ears with your vile speech. I collected this trophy from the bodies of the Rangers. He tells everyone about my services to the pack.}
{222}{}{And he also says that you are stupid if you are showing off in enemy ammunition.}
{223}{}{Gr-rm! (viciously rips off the necklace and throws it at your feet) I don't need my enemies' stuff!}
{224}{}{Exactly.}
{225}{}{Can we play on this thing?}
{226}{}{Then forget it.}
{227}{}{Bite your tongue, puppy, otherwise I'll rip it out of your mouth!}
{228}{}{Let's play by my rules. If you lose, I'll take a glass of your blood. If you win, the trophy will be yours.}
{229}{}{Let's play.}
{230}{}{This rate does not suit me. I -pass.}
{231}{}{Gr-rm! (viciously rips off the necklace and throws it at your feet) You have won, stranger!}
{1231}{}{Gr-rm! (viciously rips off the necklace and throws it at your feet) You won, bitch!}
{232}{}{I think I'll leave you until you calm down...}
{233}{}{Ha-ha! Black Fang is the winner again! I'm the winner!}
{234}{}{Hey, wait, what are you doing...}
{235}{}{Games are not for warriors. And for puppies like you.}
{236}{}{I won't argue.}
{237}{}{Not worth it. I'll just kill you one by one. And I'll start with you, you idiot.}

#Grooming services
{240}{}{You don't look in the best shape. Is the security of the entrance so unnerving?}
{241}{}{I protect the pack from aliens and get food! The others look at me and look up to me. This fight is exhausting, but I have to. After all, I will have to lead the pack when the Rabid Bitch leaves her post.}
{242}{}{You're too tense. Let me help you relax.}
{243}{}{Ah, then it's clear.}
{244}{}{To have a stranger hanging around me? Okay, so I'll rise even higher in the eyes of the pack.}
{1244}{}{To have a stranger hanging around me? Okay, so I'll rise even higher in the eyes of the pack.}
{245}{}{Of course, you're the leader, sit down, I'll rub your back...}
{246}{}{I didn't feel like it.}
{247}{}{I don't trust outsiders. And you're a stranger.}
{248}{}{Mutually.}
{249}{}{Grooming services have raised your reputation in the eyes of Jackals. But do not spread this among other tribes.}

#Questions
{250}{}{Who are you?}
{251}{}{I am a warrior. The pack calls me Black Fang.}
{252}{}{How do you feel about a Rabid Bitch?}
{253}{}{The bitch is brazen. Sometimes I'm ready to pounce on her and strangle her with my claws. But she's loyal to the pack. Although it leads her to the wrong place.}
{254}{}{}
{255}{}{}
{256}{}{I see.}