{103}{}{One less bitch}
{104}{}{Stupid man, this poison doesn't work on Jackals!}

#Counter dialogue
{200}{}{Grab the stranger! Tear him to shreds! Bring me his head!}
{1200}{}{Grab the stranger! Tear her to shreds! Bring me her head!}
{201}{}{Grab the stranger! Get him out of his shell! Bring me his head!}
{1201}{}{Grab the stranger! Get her out of her shell! Bring me her head!}
{202}{}{Don't be so nervous, lady...}
{203}{}{Get back, you creatures, everyone back!}

{210}{}{S-look who came to us. A stranger from a strange tribe. What luck that you don't have to chase him across the wastelands.}
{1210}{}{S-look who came to us. A bitch from a strange tribe. What luck that you don't have to chase her across the wastelands.}
{211}{}{Why do you need me?}
{1211}{}{Why do you need me?}
{212}{}{Yes, I don't want to run in the desert at all.}
{213}{}{I'm not going to tolerate these taunts. I'm leaving.}
{214}{}{(laughter) Someone else-Jacques does not understand. The stranger still has a glimmer of hope to get out of here alive. And I like it.}
{1214}{}{(laughter) S-bitch doesn't understand. The bitch still has a glimmer of hope to get out of here alive. And I like it.}
{215}{}{So you're going to kill me?}
{216}{}{Uh, you're not going to eat me, right?}
{217}{}{(face changes dramatically) We want to eat! We kill to survive. We are starving, and the stranger will become food for us. We will feed our children with his body! (the approving howl of a dozen mouths spreads through the burrows)}
{218}{}{Actually, I had other plans...}
{219}{}{You're not serious, are you?}

{220}{}{Tell me your nickname, stranger, and we'll get started.}
{1220}{}{Tell me your nickname, stranger, and we'll get started.}
{221}{}{My nickname Is: Go-Ass-Stupid-Bitch!}
{222}{}{Do you have to know that?}
{223}{}{(snorts like a dog) Your tongue is so deceitful that I will give it to the rats to eat.}
{224}{}{That's not very kind of you.}
{225}{}{It won't come to that, lady.}
{226}{}{So be it. The burrows are open to you. But don't look into the warehouses. The Nocturnal Beast guards them too jealously.}
{227}{}{OK, I'll take that into account. Now I'll take a look around, if you don't mind.}
{228}{}{What is it? A man in an iron shell? What a surprise. You scared a lot of people, Shell Man. But you can't fool me with that. Give up, we'll get you out of this ugly thing anyway.}

{230}{}{I am the messenger of the Spirit of Vaults. My costume is proof of that.}
{1230}{}{I am the messenger of the Spirit of Vaults. My costume is proof of that.}
{231}{}{Holy Jackal, now I remember! Our ancestors wore the same blue robes as you. So we all came out of the same hole, are we members of the same tribe?}
{232}{}{More precisely, Vaults.}
{233}{}{Then tell me, why did the Spirit of Refuge abandon us? Why was he punished with pestilence and starvation? We called Him at night, brought Him sacrifices. If He finally heard us barking, then explain what we should do?}
{234}{}{Give me time to get to know the pack and explore your life. Maybe I can help you.}
{235}{}{They call me a ghoul for a reason. Having tasted my dead flesh, you will become dead yourself.}
{236}{}{The living dead! The spirits are punishing us with pestilence again. (a plaintive howl echoes through the burrows) But maybe YOU can teach us how to survive in this world? If you manage to keep breathing in a dead body, then we could also linger before being sent to the Great Kennels.}
{237}{}{Give me time to get to know the pack and explore your life. Maybe I can help you.}
{238}{}{I want to help you.}
{239}{}{I am an ambassador from the outside world. Neighboring cities are tired of enmity and want to solve your hunger problem.}
{240}{}{Will our enemies give us food in exchange for peace? This could be a trap. Or maybe a union that will save us from problems.}
{241}{}{Killing me won't gain you much anyway. So what do you say?}
{242}{}{By killing me, you will anger the Holy Jackal.}
{243}{}{I am moved by the Spirit of the Holy Jackal. He sent me to solve the hunger problem.}
{244}{}{We prayed to the Spirit and offered sacrifices to Him. But He never helped us. Generation after generation, brood after brood - we only dwindled and died out. Has he taken pity on his servants now? Then tell me what we should do!}
{245}{}{First I need to get to know the pack.}
{246}{}{No, you fool, no one is going to help you. Everyone wants only your death!}

#Repeat dialog
{250}{}{The burrows are open for you.}
{251}{}{The burrows are open to you. But don't try to deceive us.}
{252}{}{I think I'll go.}
{253}{}{The Rangers fed us as promised. And although we do not like plant foods, hunger no longer threatens our stomachs. The whole pack owes it to you, the messenger of the Holy Jackal.}

{260}{}{Let's talk about the problem of hunger.}
{261}{}{There is a desert around, little food and little water. Hunger forces us to attack strangers.}
{262}{}{Give me time, I'll try to find a solution to this problem.}
{263}{}{And eat their flesh to calm your own? That's why you are shunned by everyone who has even heard of you.}
{264}{}{Strangers have always driven us away. And why would anyone share food with us? Of course, we have to extract it against our will.}
{265}{}{In other words, to take away or steal. Do you really have nothing to give for exchange?}
{266}{}{Exchange for food? We have nothing to offer.}
{267}{}{It won't be easy to find allies for you. But I'll try.}
{268}{}{I'm waiting, stranger. You gave your word that you would find us food.}
{1268}{}{I'm waiting, stranger. You gave your word that you would find us food.}
{269}{}{I'm working on it.}
{270}{}{The Rangers are ready to make an alliance with you.}
{271}{}{(hisses) Shh! Rangers are enemies! They always attacked us first. And you want to bring them to the valley?}
{272}{}{They are also tired of this war. For now, just listen to them. They will send a delegate to negotiate.}
{273}{}{Conversations... They will not satisfy hunger. But they won't make it worse either. Tell this one... to the s-strangers that I will listen to them.}
{274}{}{As a sign of reconciliation, let go of the ranger you keep. Otherwise, you will lose the only chance to find an ally.}
{275}{}{I will give them your consent.}
{276}{}{Such juicy meat... I can feed a whole brood of them. But if this is a fraud, then you will pay cruelly.}
{277}{}{Now disappear. I'm not going to wait until the end of my days.}
{278}{}{OK.}

{300}{}{Tell me about your tribe.}
{301}{}{We are all of the same blood. We have been living in these burrows for the third generation. Previously, the flock was larger, but hunger reduced the number of livestock, and the brood began to be born sick and unviable more and more often. What else do you want to know?}
{302}{}{Let's not talk about it.}
{303}{}{So you haven't always lived in this valley?}
{304}{}{The ancestors wandered a lot. They came from a place they called "Vault 15." I don't know what that means. But then everything was different than now.}
{305}{}{I see.}
{306}{}{This gear-shaped structure is a reminder of those days, right?}
{307}{}{Yes... that's right.}
{308}{}{You don't know what it represents, do you?}
{309}{}{The spirits don't talk to me about it. And the ancestors didn't tell me anything. And with the advent of the hungry seasons, history has lost all meaning.}
{310}{}{This is not surprising. Can I ask you something else?}
{311}{}{This is an image of an armored door. Your ancestors came out of the Vault-Tech Vault.}
{312}{}{(thoughtfully) Vault-Tech... You really know a lot. Then tell us how to fight hunger! Too many jackals and too little food. That's what's really important.}
{313}{}{You can't argue with that. But before we start fighting over a handful of maggots, let me ask you one more question?}
{314}{}{Why can't I enter warehouses?}
{315}{}{Water and food supplies are stored in warehouses. My loyal jackals are trained to guard this place. They'll tear you apart if you end up there alone.}
{316}{}{Looks like you've trained everyone well here. Let me ask you something else?}
{317}{}{How do you feel about Black Fang?}
{318}{}{He is the best warrior of the tribe. The strongest, the most persistent, is the best controlled by a spear and brings prey to the burrows the most. }
{319}{}{It seemed to me that you are not on the best terms with him.}
{320}{}{At the same time, he is the most arrogant, stubborn and stupid male of all that I have seen. When he becomes infirm, I will be the first to tear out his eyes and tear his chest.}
{321}{}{The mores here are harsh. I hope this fate will not affect me.}