{100}{}{Before you is a savage.}
{101}{}{You see one of the females of the Jackal tribe. Her little red eyes stared at you out of the twilight.}

#Replicas floating
{120}{}{There are only maggots for lunch again.}
{121}{}{Shhh, don't bark in vain!}
{122}{}{They say a stranger is wandering in the mountains.}
{123}{}{The brood will die out if we don't find food.}
{124}{}{It's time to sharpen the claws.}
{125}{}{Strangers know no mercy.}
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

#Response remarks
{200}{}{Just give me a reason and I'll rip the meat off your bones!}
{201}{}{I will feed my puppies with your meat.}
{202}{}{My claws are hungry for your flesh.}
{203}{}{}
{204}{}{}

{205}{}{My children are hungry for your blood.}
{206}{}{My children are hungry and want your meat.}
{207}{}{Do you want to die, a stranger?}
{208}{}{Mmm, you smell delicious.}
{209}{}{*Licking his lips while examining your body*}

{210}{}{Hit me!}
{211}{}{I want to be your bitch!}
{212}{}{Can you bite my neck.}
{213}{}{}
{214}{}{}