#---------------------------------------------------------
#  Translated by Georg; revised by garwert.
#---------------------------------------------------------
{100}{}{You see a pack member.}
{101}{}{You see a female member of the Jackal tribe. Her little red eyes are staring at you from the dark.}

#Floating lines
{120}{}{More grubs for lunch.}
{121}{}{Shush, don't woof for no reason!}
{122}{}{They say an outsider is in the bur-rows.}
{123}{}{The br-rood will die if we don't find more food.}
{124}{}{Time to sharpen my claws.}
{125}{}{Outsiders know no mercy.}
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

#Replies
{200}{}{Give me a reason, and I'll tear the flesh off your bones!}
{201}{}{I'll feed your flesh to my pups.}
{202}{}{My claws crave your flesh.}
{203}{}{}
{204}{}{}

{205}{}{My kids crave your blood.}
{206}{}{My kids are hungry and want your flesh.}
{207}{}{Wan-nna die, outs-sider?}
{208}{}{M-m-m, you smell nice.}
{209}{}{*Licks her lips examining your body*}

{210}{}{Hit me!}
{211}{}{I wanna be your bitch!}
{212}{}{You can bite my neck.}
{213}{}{}
{214}{}{}
