#---------------------------------------------------------
#  Translated by Georg; revised by garwert.
#---------------------------------------------------------
{110}{}{This weapon is lying in pieces. Looks like tribals had no idea how it worked.}
{111}{}{There is nothing useful here.}
{112}{}{You managed to restore the hunting rifle. It will serve you for awhile.}
{113}{}{ is now in your backback.}
