#---------------------------------------------------------
#  Translated by Georg, garwert.
#---------------------------------------------------------
{110}{}{You see a tribal totem, built out of skulls and whatever else tribals consider to be "garbage". However, you don't fully agree with their assessment.}
{111}{}{The totem is destroyed. There might be something useful in this pile of junk.}
