{100}{}{You see a raider.}
{101}{}{You see a bandit you already know. He hasn't changed at all since the meeting in the Casa Grande bar.}
{102}{}{You can't be here. Go away. Let's assume I didn't see you.}

{200}{}{So, you're here. What a surprise. How are the mayor and his spoiled daughter?}
{201}{}{I think they have a lot to think about. So, after that story in the bar, will you continue to rob and take hostages?}
{202}{}{Hmm, not a bad idea. But it's not that simple. Ben has a plan. Let's see what happens. Talk to him, maybe he'll need you.}
{203}{}{I will do so.}
{204}{}{Wait. I kept thinking about that story at the bar. I don't know why you helped us, but it would be unfair to remain unanswered. I told the other guys about you so that they would treat you better. And also take a gun and a pack of cartridges. Maybe you don't want to cause pain, but you should still think about your protection.}
{205}{}{Thank you.}
{206}{}{Real highway workers don't say "thank you" and "please." Remember that.}
{207}{}{Yes, bye.}
{208}{}{Not a bad survival kit.}
{209}{}{Good luck on the tracks. Let the dust of the road hit you in the back, and the eyes of the enemies are blurred.}

{210}{}{Hi. How is it?}
{211}{}{Nothing, yet.}