{100}{}{You see Ben.}
{101}{}{Hiding his face with a mask, this man inspires fear in his subordinates.}
{102}{}{Nothing personal. It's just that I'm sure I'll get a reward for your head.}
{103}{}{You've been running these tracks for too long.}
{104}{}{Good shoes.}
{105}{}{Ben's polished armor reflects the laser beam directly into your eyes.}

{200}{}{What a surprise. Outsiders usually avoid us. (Gives a sign to the others). Search!}
{201}{}{No one here will lay a finger on me, do you hear?}
{202}{}{[Don't resist]}
{203}{}{No, please, you can't do this, how am I going to survive in the desert?}
{204}{}{You are in my domain, pay tribute if you want to live.}
{205}{}{Okay, you got it. Take all my things.}
{206}{}{So you're an ordinary robber. I have a short conversation with such people...}
{207}{}{I can't stand idiots...}
{1207}{}{I can't stand idiots...}
{208}{}{Hey, what are you taking out?}
{209}{}{You shouldn't do that to an ambassador of the outside world. It's in your best interest to keep me alive.}
{210}{}{What the fuck are you talking about? And Bustos sent you. This fool thinks that a couple of snipers can get rid of us. You know, the corpse of another mercenary is already lying behind the fence. But no one tried to talk to us until this moment.}
{211}{}{Thank you, I hope for your understanding.}
{212}{}{It was a pass fee. Now I'm ready to listen to you.}
{213}{}{Thank you, uh, for letting me live.}
{214}{}{How am I going to survive without things in the desert now?}
{215}{}{Give me back my stuff, you son of a bitch.}
{216}{}{So it was you who saved my man from bounty hunters?}
{1216}{}{So it was you who saved my man from bounty hunters?}
{217}{}{Exactly. And I want to join a gang.}
{218}{}{Yes. He said you'd take me to the gang.}
{219}{}{Don't rush things. I still don't trust you, despite the excellent recommendation. If you want to join a gang, you'll have to prove your loyalty.}

{220}{}{The pleasantries ended there. Why are you here?}
{221}{}{Actually, I'm here by accident. Looks like I'd better leave.}
{222}{}{I don't know what you're talking about. You're confusing me with someone else.}
{223}{}{To tarnish yourself with such a bad reputation? Well, no. You made a mistake, asshole.}

{230}{}{I am looking for allies to free my people from slavery.}
{231}{}{What do we care about your problems? There are too big forces behind the slave trade to go against them.}
{232}{}{How about mutual help? You probably need someone with connections in the outside world.}
{233}{}{So you won't help me?}
{234}{}{No. Get out.}
{235}{}{Okay...}
{236}{}{Don't you dare talk to me like that, you freak.}
{237}{}{Hmm. There is one thing. My guys were captured by mercenaries and are now being tortured in Casa Grande. We need to solve this problem.}
{238}{}{Are you suggesting an escape?}
{239}{}{The hostages must be silenced. I'm not interested in which way. If they cannot be saved, they must be killed.}
{240}{}{I refuse. Go to hell with you and your guys.}
{241}{}{The task is clear. I'll do it.}
{242}{}{Give me time to think about a solution. I wouldn't want to kill anyone in the middle of an entire city.}
{243}{}{Do as you see fit. We can't have the mayor of Casa Grande getting information out of my people.}
{244}{}{OK. I'll come back when I solve the problem.}

{250}{}{To stop you and your whole gang.}
{251}{}{I've never met anyone stupider than you. It will be fun to hear your posthumous words.}
{252}{}{Eh, what are you up to? Oh no, not that...}
{253}{}{Fuck you.}
{254}{}{}
{255}{}{I'm here on behalf of the mayor of Casa Grande. He considers you guilty of robbing caravans.}
{256}{}{He knows perfectly well who is robbing caravans and why. What's the point of this performance, mercenary?}
{1256}{}{He knows perfectly well who is robbing caravans and why. What's the point of this performance, mercenary?}
{257}{}{So, you admit your guilt. In the name of the law, you are all sentenced to death.}
{258}{}{But why are you doing this? Aren't there other possibilities?}
{259}{}{I lived in Casa Grande as a normal and law-abiding citizen. But Bustos came. He declared himself a count and seized power in the city. He declared the dissenter's criminals and began to pursue them.}
{260}{}{And now you have nowhere to go?}
{261}{}{We are busy surviving through the fault of a tyrant and dictator. Robbing caravans, we just take our own - what was taken away from us. Besides, we are not bloodthirsty, we mercifully release the caravaneers who do not want a fight.}
{262}{}{You're letting them go so they can lead a caravan again that can be robbed, aren't you? Oh, you bastards...}
{263}{}{I don't care what you think about it..}
{264}{}{}
{265}{}{ And I don't care how you justify your crimes. You deserve the death penalty.}
{266}{}{You can be understood. I had to go through enslavement in Two-Sun. I can help you.}
{267}{}{To be honest, I didn't know about this story. Now I don't want to help Bustos.}

{270}{}{I want to join your gang.}
{271}{}{Why?}
{272}{}{Because you guys are cool, I want to be with you.}
{273}{}{Do I look like an idiot to you? I'm tired of listening to this nonsense. Finish him off...}
{1273}{}{Do I look like an idiot to you? I'm tired of listening to this nonsense. Finish her off...}
{274}{}{What about...}
{275}{}{Wait. I saved your people at the Casa Grande bar. You can trust me.}
{1275}{}{Wait. I saved your people at the Casa Grande bar. You can trust me.}
{276}{}{I want to be part of a big pack like before.}
{277}{}{Then to set the heat. And I know how to do it.}
{278}{}{In order to create the good old ultra-violence. I'm not good for anything else anyway.}

{280}{}{I've heard the story. But you will have to prove your loyalty.}
{281}{}{Sure. What should I do?}
{282}{}{Sounds convincing. But you will have to prove your loyalty.}
{283}{}{Sure. What should I do?}
{284}{}{I have nowhere to hide in this world. Slavers ravaged my village.}
{285}{}{That is, you want to survive by joining a strong pack. So, at any moment you can betray her.}
{286}{}{I can prove my loyalty. Try me.}
{287}{}{You're smarter than you look. Now there's only one thing left for me... Die, you son of a bitch!}
{288}{}{I saved your people at the Casa Grande bar. You can trust me.}
{1288}{}{I saved your people at the Casa Grande bar. You can trust me.}

{290}{}{I escaped from the slave pen of the tinsmiths. Now I have nowhere to go.}
{1290}{}{I escaped from the slave pen of the tinsmiths. Now I have nowhere to go.}
{291}{}{You can be understood. Tinsmiths have annoyed many people in these lands. We have become a victim of their expansion.}
{292}{}{Does that mean you'll accept me?}
{293}{}{You'll have to prove your loyalty to the gang.}
{294}{}{Sure. What should I do?}
{295}{}{The arena in Phoenix taught me only one thing - to punch others in the face.}

#Repeat dialogue (after receiving quests)
{300}{}{What news?}
{301}{}{Hi, Ben.}

{310}{}{Tell me about the gang.}
{311}{}{You're not worth my time. Show yourself in action first.}
{312}{}{The hint is understood.}
{313}{}{What do you want to know?}
{314}{}{That is all. It was nice chatting.}
{315}{}{There is another question.}
{316}{}{Why are you called Blue Shields?}
{317}{}{Federal highway signs on our jackets. They look like shields. And they're blue. Catching the connection?}
{318}{}{I think so.}
{319}{}{How can you survive in these lands at all?}
{320}{}{We rob caravans, hunt game, collect valuables from the ruins. The fuel depot provides us with a good service. Fire, like water, gives life. The water merchants in Casa Grande cannot understand our rage.}
{321}{}{That's it. Interesting.}
{322}{}{But how did you come to such a life? Where did all these guys come from?}
{323}{}{Everyone has their own story. But we are all exiles. Some were kicked out of Casa Grande when Count Bustos came to power. Others were driven from their homes by tinsmiths. There are also those who fled from problems in Phoenix. We have no other way.}
{324}{}{It's really a turbulent time now.}
{325}{}{What did the tinsmiths annoy you with?}
{326}{}{Their power is expanding, and the inhabitants of the Wasteland take it for granted. They brazenly seize technologies and resources, impose their own rules in settlements, and force them to work for the glory of their ideas. Now we are doing the same with their caravans.}
{327}{}{[Listen]}
{328}{}{They came with their understanding of life and began to set their own rules for us. Who asked them? Who gave them the right to decide what is good and what is bad? It used to be easier. Previously, everyone knew that the one who can stand up for his truth is right.}
{329}{}{So you are fighting the invaders with their methods? Curious.}
{330}{}{Tell me about Rio. He's not particularly open to me.}
{331}{}{We are old friends. He is my right-hand man, I trust Rio more than anyone else. I know he doesn't like anyone who tries to gain my respect. You'll have to accept it and find a common language with him.}
{332}{}{Clear.}
{333}{}{What kind of place is this anyway?}
{334}{}{Petro-Chico distillation station. Before the War, fuel was stored here. It seems that it was very valuable since such a powerful fence was erected around it. Now it's giving us fire.}
{335}{}{Clear.}
{336}{}{What's your problem with the mayor of Casa Grande?}
{337}{}{Count Bustos is a tyrant. He seized power in the city by cunning, killed or drove away all the dissenters. Now he enjoys a clean bath to the music of King Cole while we survive in the barren desert through his fault.}
{338}{}{Looks like you've got a grudge against him. Let's change the subject.}

{350}{}{It's done. Your buddy is dead.}
{351}{}{Your friend was killed by the locals. They organized a lynching right in the center of the city.}
{352}{}{It's done. Your friend escaped from prison in Casa Grande.}
{353}{}{He's not my buddy. He's just a cog in my system. He owes his life to me, let him pay with it.}
{354}{}{Well, then you'll figure it out for yourself.}
{355}{}{Beautiful speech.}
{356}{}{Now I see that you can be dealt with. The gang needs contact with the rest of the world, you will be our intermediary.}
{357}{}{Where should I go this time?}
{358}{}{Well, it finally dawned on you that I'm here for a reason.}
{359}{}{I sent that guy to investigate for a reason. The tinkerers are expanding their power, there are more caravans, and the mayor of Casa Grande is hiring more and more cool mercenaries. A new order is coming to these lands and Great Road Wars are brewing. My gang needs to strengthen in this new world.}
{360}{}{What are you up to?}
{361}{}{We are outlawed now. We are considered criminals. I want to negotiate a truce with the tinkerers. Go to Two-Sun and convince Master Hard to sign a contract - our fuel in exchange for independence.}
{362}{}{And if he refuses?}
{363}{}{He must not refuse. Do everything to win his favor.}
{364}{}{Clear. I'm going on a mission.}
{365}{}{What do you know about tinsmiths?}
{366}{}{A closed community. They worship technology and dislike outsiders, consider us inferior to themselves. But thanks to their production, these lands came to life again, a water station started working and trade appeared.}
{367}{}{I see.}
{368}{}{About the contract. Isn't the fuel supply in the tanks limited?}
{369}{}{Look at these stocks. Only its transportation will take months. During this time, we will earn a lot of caps and we will be able to decide what to do next. I expect to order some technologies from the tinsmiths, for example, for the production of cartridges. So we can move to places rich in game.}

{370}{}{The bad news is that the tinkerers have been defeated by artificial intelligence. There is no one else to negotiate with.}
{371}{}{The bad news is that Master Hard has died, and other tinkerers are too aggressive towards outsiders.}
{372}{}{So is it true? Damn it, without tinsmiths, the tracks will be empty again. There will be fewer caravans, it will hurt all residents. It looks like hard times are coming.}
{373}{}{What are the plans?}
{374}{}{Rob as much as we can carry. And when the tracks are completely empty, you will have to go to the mountains in search of game.}
{375}{}{I see.}
{376}{}{There are no more tasks for you. You can go.}
{377}{}{Bye, Ben.}

{380}{}{Good news - Hard has agreed to a trade contract.}
{381}{}{Hmm, things seem to be getting better. Although I was sure that the idea would not work. However, it is not enough to negotiate with the tinsmiths.}
{382}{}{Who else is bothering you?}
{383}{}{Count Bustos, mayor of Casa Grande. If he refuses to recognize us as a peaceful settlement, then the caravaneers will have nothing to do with us. We need to convince him to sign the contract... or - get rid of the mayor.}
{384}{}{Kill Bustos so he doesn't get in the way? It seems more realistic than negotiations.}
{385}{}{I will still try to negotiate with him. It's hard to say what will happen to the city without him.}
{386}{}{Do it for the gang. For the sake of our long-awaited freedom.}
{387}{}{You can count on me, Ben.}

{390}{}{Count Bustos did not want to make an alliance. He had to be "persuaded".}
{391}{}{Count Bustos has made an alliance. He had to be persuaded for a long time.}
{392}{}{Thanks to you, the gang will live a new life. A new Time is coming when tinsmiths will open their technologies to the rest of the world. And we will be among the chosen ones. There will be no need to rob travelers anymore.}
{393}{}{[Next]}
{394}{}{I never imagined that your help would be so useful. You have proved your loyalty to the gang and can proudly wear the title of Blue Shield. Take this jacket and a flamethrower as a reward.}
{1394}{}{I never imagined that your help would be so useful. You have proved your loyalty to the gang and can proudly wear the title of Blue Shield. Take this jacket and a flamethrower as a reward.}
{395}{}{[Next]}
{396}{}{It seems you have a long road ahead of you. I remember you needed allies. You can take the bike from Rio. With it, you will quickly get to any point on the highway.}
{397}{}{Thanks, Ben. You are a true friend.}
{398}{}{Don't say "thank you." We don't know that word. Just take what you deserve. It's your right.}
{399}{}{Then goodbye, Ben.}