{100}{}{You see a raider.}
{101}{}{One of the highway robbers.}

{110}{}{Hey, how's business?}
{111}{}{Good luck on the track.}
{112}{}{You're cooler than we thought.}
{113}{}{I can't believe we're the defenders of the trails now.}
{114}{}{The tracks are now under our control.}
{115}{}{You bring us luck.}
{116}{}{Ben trusts you.}

{120}{}{If you stare at me, I'll arrange a sun-out.}
{121}{}{What do you need, scum?}
{122}{}{*Spits back*}
{123}{}{Ben let you in, but you're not a gang member yet.}
{124}{}{I am bored. Entertain me.}
{125}{}{You're taking a big risk by being here.}

{130}{}{What the fuck are you?}
{131}{}{You're it, keep it down there. }
{132}{}{I wish I had armor like yours.}
{133}{}{Are you a tinker's invention?}