{100}{}{You see the mutant Edmond.}
{101}{}{You see a terribly disfigured person.}
{102}{}{A mutant suddenly appears from the shadows.}

{110}{}{Go away and don't touch us}
{111}{}{Leave me alone!}
{112}{}{I don't want to talk to you}
{113}{}{Strangers cannot be trusted}

{120}{}{Uh-oh! U-a!}
{121}{}{Ar-r!}
{122}{}{Ar-r-r!}
{123}{}{Ba! Ba-ba!}

{200}{}{ (The mutant blocks your way, but only swings something dangerous.) Uh-oh!}

{201}{}{[Step back, showing your friendliness]}
{202}{}{Ar-r! (sensing your softness and unwillingness to fight, the mutant decides to attack!)}
{203}{}{No, don't touch me!}
{204}{}{You brute!}
{205}{}{Stop! Not a step forward!}
{206}{}{ (your words only angered the mutant, he decides to attack!)}

{210}{}{[Take a provocative step forward]}
{211}{}{Ar-r! (mutant backs away, his gaze becomes even crazier)}
{212}{}{Look, I don't want a fight. Trust me.}
{213}{}{Die, monster!}
{214}{}{Stop! Not a step to the side!}

{220}{}{(The mutant slows down sharply and takes a step back. It looks like your determination scared him.)}
{221}{}{What is it, handsome? You don't want a fight, right?}
{222}{}{That's better. And don't try to twitch, you piece of shit.}
{223}{}{(The mutant stands in numbness and indecision. You look closely at his disfigured face, on which horror and years of pain are imprinted. His body turns out to be thin and skewed.)}
{224}{}{Ha, no wonder you're holed up in the basement when the others are fighting upstairs. How did you even survive with such pathologies?}
{225}{}{Poor guy, have you been like this from the very beginning? It's a miracle you're even still alive.}
{226}{}{(Suddenly, behind the mutant's back, someone is crying hysterically from the next room. The sound brings the mutant to his senses, and he stands in a defensive pose, blocking the passage into the room.)}
{227}{}{Who's there? Who are you torturing there?}
{228}{}{Ar-r! (shows you to go away)}
{229}{}{Answer your mother!}
{230}{}{A-r-r! A-r-r!}
{231}{}{Damn son of a bitch! Die!}
{232}{}{Step aside and don't get in the way, you piece of shit.}
{233}{}{Can't you talk? Then I'll go through and find out what's going on there.}
{234}{}{(shakes his head piteously)}
{235}{}{Get out of here. If you come back, you'll die. Is that clear?}
{236}{}{I won't kill you if you leave and don't get in the way. Come on, get some fresh air.}