{100}{}{This is Miss Bates.}
{101}{}{You see a terribly disfigured woman.}
{102}{}{*Sobbing*}
{103}{}{My kids will kill you and eat you.}

{200}{}{(In the twilight of the barracks you see a woman on the bed; she is barely audible sobbing, turning away from you).}
{201}{}{Hey, ma'am...}
{202}{}{Get out! Get out!}
{203}{}{Calm down, ma'am, I want to help you.}
{204}{}{Stop yelling, otherwise these mutants will come running to the screams.}
{205}{}{No! Don't touch me! A-a-a!}
{206}{}{It's all good. Those monsters don't threaten you anymore.}
{207}{}{Either you shut up yourself, or I'll gag you. What do you choose?}
{208}{}{(The woman stops screaming; in the pause that ensues, you notice terrible scars all over her body).}
{209}{}{Good God, you need a doctor. I'll help you get out of here.}
{210}{}{Follow me if you want to live.}
{211}{}{Why?}
{212}{}{What?}
{213}{}{Why should I go outside? This is my home. I'm not leaving.}
{214}{}{But... Then who are these monsters?}
{215}{}{Sherman, George, Edmond - they're good guys, you can be proud of them. My guys are golden.}
{216}{}{Are these cannibals and murderers your sons?}
{217}{}{Bitch, are you saying these freaks are your kids?}
{218}{}{Ha, it's immediately obvious that you don't have children. They are my pride and love. No one will break the Bates family. None of the outsiders could.}
{219}{}{It's too late to brag about family achievements. Your geeks are dead. All three of them.}
{220}{}{The murderer! My kids just wanted to live. All the outsiders tried to kill them. Just like you. Why are you so angry? (the woman turns her disfigured face sharply towards you) We haven't let anyone in since. Strangers bring us death!}
{221}{}{I'm not...}
{222}{}{It's so familiar...}
{223}{}{But that's nothing. We are all one family. No one will break the Bates. There will be new ones. Someday. Ha! Ha-ha! A-ha-ha! U-i-i-i...}
{224}{}{[Leave the mutant alone]}
{225}{}{You're just crazy.}
{226}{}{You have killed many people. This needs to be stopped.}
{227}{}{Do you think I can't handle a few freaks?}
{228}{}{My sons will kill you! And any other outsider. Because we're family. No one will break the Bates. Ha! Ha-ha! A-ha-ha! U-i-i-i...}
{229}{}{In fact, I understand you well. Outsiders also tried to break my village. And that's why I'm not going to die yet.}
{230}{}{Outsiders also tried to break my village. I won't let you stop me. Your sons tried-and now they're dead.}