{100}{}{You see a victim of cannibalism.}
{101}{}{You see an exhausted man.}
{102}{}{It's better here than in that old motel. I will never stop there for the night again.}

{200}{}{Ah! Don't touch me!}
{201}{}{I'm not going to touch you. Calm down.}
{202}{}{Shut up, you idiot. They'll hear us.}
{203}{}{Eh? Aren't you a mutant? Oh... How glad I am to see you...}
{204}{}{Why did the mutants lock you up?}
{205}{}{Don't you see all these bones? They're cannibals! They lure people into traps and then butcher them like cattle.}
{206}{}{What a horror.}

{210}{}{We need to get out of here! They killed everyone else... They will kill us too!}
{211}{}{For now, sit here, and I'll see if there's any danger ahead.}
{212}{}{Okay. I'll walk you to the nearest settlement. Let's go. Just be quiet.}
{213}{}{I'm still shaking with fear. We need to leave this place as soon as possible.}
{214}{}{So let's not waste time. Let's go.}
{215}{}{Sit here and keep your head down. I'm on a reconnaissance mission.}

{220}{}{We're safe now. Ugh. If it wasn't for you, I would have been eaten by now. Thank you. I will tell all my friends who saved me.}
{221}{}{Happily. Good luck.}