{100}{}{Here is a migrant from Phoenix.}
{101}{}{You see a man in dusty clothes. His hands are soiled in mud.}
{102}{}{Hello}

{200}{}{What a surprise. We knew that sometimes travelers pass here. But we didn't expect to meet a new face so soon.}
{201}{}{Have you been here recently?}
{202}{}{Yes, just checked in. If you're looking for an overnight stay, then I'm sorry - we don't have enough space, all the rooms are occupied.}
{203}{}{No, I just want to talk.}
{204}{}{Overnight at this motel? Well, no. I'd rather spend the night in the desert under the open sky.}
{205}{}{Yes, just checked in. If you're looking for an overnight stay, then I'm sorry - there are no available rooms. But I don't mind exchanging a few words with a rare traveler.}

{210}{}{There are no empty seats. But I don't mind exchanging a few words with a rare traveler.}
{211}{}{Where did you come from?}
{212}{}{We are immigrants from Phoenix. We are here to found a new community. Aaron himself gave us a deed of sale for this land.}
{213}{}{And for what such merits?}
{214}{}{For work in the glory of His ideas. Besides, it was easy, because Aaron is interested in colonizing the neighborhood under his banners.}
{215}{}{Well, well. What can you prove?}
{216}{}{We have a bill of sale. We got it for working for the glory of Aaron's ideas. But what do you have to put forward your doubts?}
{217}{}{And how did he have the right to this motel?}
{218}{}{Only Aaron can dispose of the lands around Phoenix. And try to say that it is not so.}
{219}{}{It's not like that.}
{220}{}{How dare you defile the name of a holy man? Keep your fucking mouth shut before I lose my temper. Away! Pro-och!}
{221}{}{Okay, okay...}
{222}{}{Hey, take it easy...}
{223}{}{He's doing a great job.}
{224}{}{May the name of Aaron be glorified! A man who gives life to the desert.}
{225}{}{Aaron is killed. Do you know about it?}
{226}{}{Aaron and his cathedral are destroyed. Do you know about it?}
{227}{}{How dare you talk about such a thing? Of course, Aaron is alive, and his cathedral stands where it stood. Cover your vile mouth before I lose my temper.}
{228}{}{The truth is always offended.}
{229}{}{Hey, take it easy...}

{230}{}{Do you know that mutants used to live here?}
{231}{}{What was, was. We need to start anew, and not mess around in the past.}
{232}{}{And are you ready to settle here, knowing about the horrors that were happening in the walls of the motel?}
{233}{}{Although these mutants were cannibals and sadists, they were watching the motel at the same time. That's why we stopped here. Because this is the only place suitable for living in the district!}
{234}{}{Did the mutants try?}
{235}{}{They repaired the roof and fence, fertilized the beds, put up desert water storage - this is a great place to start anew.}
{236}{}{That is, you have come to everything ready.}
{237}{}{I think it's time for you to go.}
{238}{}{Yes, I have to go. Goodbye.}
{239}{}{That was rude of you. Now I definitely don't want to linger here.}
{240}{}{We can be happy for you. At least this cursed place will bring some benefit.}
{241}{}{Now everything will be different. Aaron gave us and the motel a second chance. I promise - we will make the promised land out of this desert.}
{242}{}{Amen.}
{243}{}{Good luck.}