{100}{}{There is a sentry in front of you.}
{101}{}{One of the highway robbers.}
{102}{}{It looks like I'm hallucinating...}

{110}{}{Looking for trouble, trash?}
{1110}{}{Looking for trouble, bitch?}

{200}{}{(A sentry dozing in the sun raises his head at your footsteps; he drops his weapon in surprise, but quickly regains consciousness).}
{201}{}{[Next]}
{202}{}{Which... Who the fuck are you? What do you need?}
{203}{}{Which... Motherfucker, freak, you can't sneak up on people like that. What do you need?}
{204}{}{Wait, and you're someone else... Hey, guys, there's a spy here!}
{205}{}{But this was not worth doing ...}
{206}{}{Who is the spy? Me?}

{210}{}{Good question. And what is this place?}
{211}{}{Great fucking place. Don't you know who the Blue Shields are? We run all the highways in the area. And this is our camp.}
{212}{}{So it's you who rob travelers on the highways? What luck that I won't have to look for you. I will destroy you all.}
{213}{}{Are you? You can't even fill up a tent. A bunch of losers in an old dump - that's who you are.}
{214}{}{Shut your filthy mouth, road carrion... (grabs his weapon in an evil grin)}
{215}{}{And then what?}
{216}{}{Oh, oh...}
{217}{}{Wow. You guys are great. Do you have any available seats in the gang? I'm thinking of joining.}
{218}{}{Ha, there's no place for road carrion like you. Get out of here while I'm being nice.}
{219}{}{Okay, okay, I'm leaving now.}
{220}{}{Take me to the leader. Perhaps he will have a different opinion.}
{221}{}{Here *I* decide who to let in. Is that clear? And you won't pass. Get out of here.}
{222}{}{Let me through. I'll pass anyway.}
{1222}{}{Let me through, or I'll come in myself.}
{223}{}{Try it, bitch.}
{224}{}{It looks like you only understand brute force. Now I'm explaining everything...}
{225}{}{Okay, you're the boss here, let me just leave.}
{226}{}{Take me to the leader. Immediately.}
{227}{}{OK, follow me.}
{228}{}{[Follow him]}
{229}{}{What if I meet you halfway? For example, I'll give you 25 caps.}
{230}{}{(takes the caps, then looks around) OK, follow me.}
{231}{}{[Follow him]}
{232}{}{(Looks carefully at how you are looking for non-existent bottlecaps in your pockets).}
{233}{}{Uh, I'll get them now. Honestly...}
{234}{}{To hell with it. It's easier to kill you right here and now...}
{235}{}{I should have started with that right away. Let me just leave.}
{236}{}{Not so fast, bitch. Give me all your caps, and then you can go.}

{240}{}{I travel. Is there a place for me to sleep here?}
{241}{}{(He lowers his weapon and spreads out in an unkind grin). That's how. Do you even know where you are, bitch? This is a Blue Shield camp, bitch. We hang people like you on road billboards, okay? Now get lost if life is precious.}
{242}{}{Fie, how rude. What are you doing?}
{243}{}{(the grin slips off his face, exposing the grin) What are you saying, bitch? Tell me again, maybe I heard it?}
{244}{}{I repeat again: you are a piece of shit.}
{245}{}{Oh, I'm sorry! I'm new here. You won't see me again.}
{246}{}{Hehe, road carrion, you've gone too far. Now give up all your caps.}
{1246}{}{Hehe, road carrion, you've gone too far. Now give me all your caps.}
{247}{}{You won't get anything.}
{248}{}{Of course, of course, here are all my bottlecaps, please...}
{249}{}{And where am I? Tell me what this place is.}
{250}{}{This time I will ignore your rudeness. Now take me to your leader.}
{251}{}{Take me to your leader. I need to talk to him.}
{252}{}{ (scratching his dirty neck in thought) Do you want to meet Ben? Do you even know where you are?}
{253}{}{I know. I'm in a rotten hole. And right now I will cleanse this place of filth.}
{254}{}{Really. And where am I?}
{255}{}{I'm here on behalf of the mayor of Casa Grande. Take me to your boss immediately.}
{256}{}{[Obey and go back to the desert]}

{300}{}{Are you still here? Looks like you're looking for trouble.}
{301}{}{I need to talk to your leader.}
{302}{}{Are you still here? I don't know what you're trying to achieve, but I won't refuse another bottle.}
{303}{}{I can get alcohol if you skip to your boss.}
{304}{}{To hell with it. I'm coming in.}
{305}{}{OK, OK, I'm already leaving.}
{306}{}{Let me in.}
{307}{}{I came across one of yours in the desert. He said I could talk to Ben.}
{308}{}{Ah, that changes a lot. Ben is waiting for you. Come in, but watch your tongue so as not to provoke anyone.}
{309}{}{Okay.}

{310}{}{Good luck on the track, brother}
{1310}{}{Good luck on the track, Sister}
{311}{}{What do you need, brother?}
{1311}{}{What do you need, sister?}
{312}{}{Fuck off.}
{313}{}{I don't like you. Get out of the gang, you scum.}
{314}{}{I've been itching to dust your snout for a long time.}
{315}{}{Later.}

{320}{}{Have you been in the gang long?}
{321}{}{Yeah. What's it to you? Watch your ass.}
{322}{}{Really. And yet it's cool here.}
{323}{}{Umgu.}
{324}{}{Is this how you always greet newcomers, asshole?}
{325}{}{You're lucky Ben let you walk around the base. But don't do it.}
{326}{}{Why?}
{327}{}{We won't like it. Besides, there are a lot of traps around the base, be careful.}
{328}{}{Traps? Can you show me?}
{329}{}{They're not there for beauty, you know? I've said it all.}
{330}{}{Okay. Clear. Bye.}
{331}{}{About the traps. Can you show me the dangerous places more specifically?}
{332}{}{I'll pay 50 caps. Don't worry, no one will know about it.}
{333}{}{No. For an ass like you, it will cost 100 caps.}
{334}{}{It's too expensive.}
{335}{}{Good. Let there be 100 caps.}
{336}{}{I need to know for sure. Ben allowed it.}
{337}{}{Look... We mined the outer walls around the perimeter, except for the gate and the wall near the fuel tank. Especially dangerous on the west side. Sometimes scorpions fall into traps, look carefully at your feet.}
{338}{}{Great, this will help.}