{100}{}{You have a criminal in front of you.}
{101}{}{One of the highway robbers who fell into the hands of justice.}
{102}{}{S-su-uka...}
{103}{}{*Cough-cough*}
{104}{}{See you at the base. If we survive.}

{200}{}{(a half-naked bandit is sitting on the floor in front of you; his body eloquently shows bruises) What do you need? I've already told you everything.}

{210}{}{What do you need?}
{211}{}{Here I ask questions.}
{212}{}{Well, ask. But I still won't answer.}
{213}{}{Ben sent me. He wants to save you.}
{214}{}{So save me, what are you standing for? Or didn't Ben send you?}
{215}{}{Have a good stay.}
{216}{}{Will you just leave me like that?}

{220}{}{Why are you being kept locked up?}
{221}{}{Because I'm dangerous, you know? The mayor needs to know something, but he's asking the wrong thing.}
{222}{}{What does the mayor want from you?}
{223}{}{All I know about some Ben and some of his base. I have no idea who this is about.}
{224}{}{How were you captured?}
{225}{}{I was burned by peasant bitches when I approached the city. They thought I was a bandit and ratted out the mayor about it.}
{226}{}{Do you have any ideas how to get you out of here?}
{227}{}{Can you convince the mayor that I'm not involved? Then give me the gun and I'll just walk out of here.}
{228}{}{I have some bad news, trash. Ben said to kill you if there was no other way out.}
{229}{}{(shows middle finger) Fuck you.}
{1229}{}{(shows middle finger) Fuck you.}
{230}{}{Now you definitely can't get out of here.}
{231}{}{But anyway, you might think.}
{232}{}{We'll have to fight our way through. You have no other choice anyway. Let's go.}
{233}{}{Great, let's set the heat in this hole. But let's not be heroic. I just need to get out of the city, to a safe place.}
{234}{}{Let's go.}
{235}{}{Stay here, I'll scout the situation outside.}

{250}{}{You're free. The mayor signed your release.}
{251}{}{Just like that? Listen, I need an escort, otherwise the peasants will tear me apart.}
{252}{}{OK, let's go.}
{253}{}{I'll go on by myself. It will be easier to cover your tracks alone.}
{254}{}{As you wish. By the way, Ben said that if you fail, you will have to be shot.}
{255}{}{(swallows) If it wasn't for Ben and his thirst for revenge, I wouldn't have gone to prison at all. He sent me to find a weak spot in the defense of the city. But everyone here knows each other. So I immediately found myself in the clutches of the peasants. Eh. Now I have to go back to Ben with nothing.}
{256}{}{Do you think he'll get mad?}
{257}{}{Well yes. But if I don't come back, he will declare me a traitor. And this is even worse.}
{258}{}{You're totally fucked. Happily.}
{259}{}{Surely he will understand your failure. Be.}
{260}{}{We need to get out of the city before they lift us on a pitchfork.}
{261}{}{Right. Come on.}
{262}{}{It seems to have passed. I already thought I'd have to knock you down and run as fast as I could. Are you sure you're from Ben? I haven't seen you before.}
{263}{}{Yes, I recently joined his gang. That's why he sent me to find you.}