{100}{}{Before you is a warrior of the road.}
{101}{}{This is one of the highway robbers.}
{102}{}{The Raider does not want to negotiate.}

{110}{}{Hey, how's business?}
{111}{}{Good luck on the track.}
{112}{}{You're cooler than we thought.}
{113}{}{I can't believe we're the defenders of the trails now.}
{114}{}{The tracks are now under our control.}
{115}{}{You bring us luck.}
{116}{}{Ben trusts you.}

{120}{}{If you stare at me, I'll arrange a sun-out.}
{121}{}{What do you need, trash?}
{122}{}{*Spits back*}
{123}{}{Although Ben let you in, you're not a gang member yet.}
{124}{}{I am bored. Entertain me.}
{125}{}{You're taking a big risk being here.}
{126}{}{Don't cross our path.}

{130}{}{Who the fuck are you? Are you from the tinsmiths?}
{131}{}{You're it, keep it down there.}
{132}{}{I wish I had armor like yours.}

{199}{}{    }
{200}{}{What are you staring at, cowboy?}
{201}{}{At you, bitch.}
{202}{}{I hate being called that.}
{203}{}{Well, get used to it, BITCH.}
{204}{}{Watch your mouth, you piece of roadside shit, otherwise...}
{205}{}{Otherwise what? Ooh, will you resist?}
{206}{}{Well, one more word, and...}
{207}{}{What are you gonna do, baby? I have a palm. The palm I'm going to slap you with...}
{208}{}{Do you want me, trash?}
{209}{}{You want to, huh?}
{210}{}{*Ugh*}
{211}{}{No, it's fine... Sorry, I got confused...}
{212}{}{Talk to me here.}
{213}{}{. . .}