{100}{}{You see Chuck.}
{101}{}{This is one of the highway robbers.}
{102}{}{Hey, hello, how are you?}

{200}{}{Hey, hello. My name is Chuck. And I haven't seen you before. Who are you?}
{201}{}{You shouldn't know my name.}
{202}{}{Seriously? Okay, whatever you say. Although I don't understand why you need such secrecy.}
{203}{}{Your affability doesn't fit into the spirit of the gang. Don't you find it?}
{204}{}{Damn, that's right. I'm a newbie. I still don't know much, I haven't even been initiated.}
{205}{}{Dedication?}
{206}{}{I }
{207}{}{ and I'm new here.}
{208}{}{Oh, so you're a newbie too? Finally, I'm not the only one here. Nice to meet you. Have you already been initiated?}
{1208}{}{Oh, so you're new too? Finally, I'm not the only one here. Nice to meet you. Have you already been initiated?}
{209}{}{Dedication?}
{210}{}{Oh, hello. Uh, I'm training here... I want to be as cool as you.}
{211}{}{If you want to take my place next to Ben, then you're too late.}
{212}{}{No, no, I'm not up to you. That's why I train hard before initiation.}
{213}{}{Dedication?}
{214}{}{I have to go through an initiation ceremony to prove my right to a place in the gang. Experienced people say that they will beat me with a crowd and see how I can stand it. But it seems that it will not be limited to this.}
{215}{}{Does it bother you?}
{216}{}{Sure. I'm not sure I have enough strength and endurance. They might even kill me.}
{217}{}{Then why are you continuing to prepare?}
{218}{}{I have no choice. I do not know where else to go after the mayor of Casa Grande killed half the population. He declared me a traitor and even charged a fee for my capture. Ben is the only one who took me in.}
{219}{}{Well, good luck with the workout.}

{220}{}{Hey, hi.}
{221}{}{Bye.}
{222}{}{I can help you with the test.}
{223}{}{Really? How?}
{224}{}{They say pre-war chemistry can relieve pain.}
{225}{}{Yes, I've thought about it. Psycho is perfect for me to be able to take a beating. But it is a very expensive and rare drug. Can you get it for me?}
{226}{}{Yes, but I need time for that.}
{227}{}{Great. I will wait.}
{228}{}{Bye.}
{229}{}{No, sorry, I don't have one.}
{230}{}{Sorry. Psycho can be bought in Phoenix. For me, the way there is closed, because the local thugs have a warrant for my capture.}
{231}{}{Clear. If I find a psycho, I'll bring it. Later.}
{232}{}{You don't belong in a gang. I want to rid you of the stigma of a criminal.}
{233}{}{Have you thought about getting rid of the stigma of a criminal? Surely you can break the contract with the bounty hunters.}
{234}{}{Damn, I would be grateful to you for life. The contract for my capture is kept in Phoenix, and the customer is the mayor of Casa Grande.}
{235}{}{It's too complicated. It will be easier to find you some kind of drug to endure the pain.}
{236}{}{Have you ever thought to get rid of the stigma of a criminal and return to normal life in the city?}
{237}{}{I got you a psycho.}
{1237}{}{I got you a psycho.}
{238}{}{This dose is enough for the whole ceremony. Thank you, friend, what would I do without you?}
{1238}{}{This dose is enough for the whole ceremony. Thank you, miss, what would I do without you?}
{239}{}{Just a quid pro quo. Remember who your real amigo is here.}
{240}{}{All charges have been dropped against you. You're free.}
{241}{}{It's true? So now I can go to the city and continue the life of a normal person?}
{242}{}{Goodbye, Chuck.}
{243}{}{Don't mess with questionable types anymore, buddy.}
{244}{}{I'll think about what I can do. Bye.}
{245}{}{Why do you keep preparing if you can die?}
{246}{}{Mayor Bustos is dead, which means his contract with the thugs is worthless.}
{247}{}{Really? Wow. I did not know. So now I can go back to the city and continue the life of a normal person?}
{248}{}{How is the preparation for the initiation going?}
{249}{}{I do not know what awaits me. But they say that I will be beaten by the whole crowd to test my endurance. And it scares me. What if I can't stand it?}
{250}{}{Clear.}
{251}{}{Tell your story.}
{252}{}{I lived with my parents in Casa Grande. They belonged to the clan that owned the water station. But then Mayor Bustos seized power in the city. He took away the station and killed everyone who interfered with him.}
{253}{}{How did you survive?}
{254}{}{I escaped from the city in time, and then I found out that I, too, was being hunted under some invented pretext. I have wandered a lot and have completely despaired of finding a new home. Fortunately, Ben accepted me into the gang.}
{255}{}{Sad story.}
{256}{}{Given the circumstances, any story here seems doubtful.}
{257}{}{Exactly, Chuck.}
{258}{}{Thanks! Here, take a stimpack. I was thinking of using it during the ceremony, but now I won't need it. (looks around and lowers his voice) The main thing is that no one finds out that I'm going to run.}