{100}{}{You see the raider.}
{101}{}{You see a highway robber. He is wounded in the shoulder.}
{102}{}{You see a highway robber. He looks much more cheerful since you last saw him.}
{103}{}{I would have died like that if it wasn't for you, Doc.}
{104}{}{S-bitches from the caravan shot through the shoulder during the raid... How it hurts!}
{105}{}{I was shot in the shoulder during a raid on a caravan. But we took everything they had anyway.}
{106}{}{Are you sure this is medicine, Doc? Something is only getting worse for me...}
{107}{}{Oops! He, uh, had an advanced stage...}
{108}{}{Who let you in?}

{200}{}{I would have died like this if it wasn't for you, Doc.}
{201}{}{You're welcome.}

{210}{}{How can I help, Doc?}
{211}{}{Bye.}

{220}{}{Tell me how you got injured?}
{221}{}{I was shot in the shoulder during a raid on a caravan. But we took everything they had anyway. Ha!}
{222}{}{How did it happen that you joined the Blue Shields?}
{223}{}{I had nowhere to go, so I decided to sign up for Ben as an assistant. It wasn't easy. I need to go through a difficult initiation ceremony, I still have scars from it. But I proved that I am fit for the Blue Shields. A day I'll be proud of for the rest of my life.}
{224}{}{What do you do in a gang?}
{225}{}{Yes, by any tasks that Ben or Rio will set. Lately, I've been in charge of distributing fuel before sorties. Ben is very jealous of the useless waste of our supplies, so he tries to control the spill.}
{226}{}{Can you squeeze me a liter or two?}
{227}{}{After my healing? Of course! I'll make you fire bombs or a fuel supply, but not an unlimited amount, you know.}
{228}{}{Cool...}