{100}{}{Here is Rio.}
{101}{}{One of the highway robbers.}
{102}{}{Well, well, we've got a mole rat here.}
{103}{}{Not a bad armor. But it lacks the most important thing - speed.}
{104}{}{Rel: }
{105}{}{+20}
{106}{}{-20}
{107}{}{exit}

# Having received the title of Road Warrior
{200}{}{(he grits his teeth, looking straight into your eyes like an animal) So now I have to move. It's getting a little tight around Ben, huh?}
{201}{}{Yes, Ben and I are on great terms now...}
{202}{}{Then remember that *I* am the first one here after Ben. Don't cross my path.}
{203}{}{OK.}
{204}{}{}
{205}{}{( showing a grin with one side of his face) Look who came to us. It's Ben's new pet.}
{206}{}{And you're jealous, right? Do you feel that you have to move?}
{207}{}{What is it, bitch, are you going to twist my balls? Then remember - NO one will take my place next to Ben. We have known each other for a long time, he trusts me. And you? No one here knows you at all.}
{208}{}{Don't be nervous, Rio, I'm not going to challenge your place at the throne.}
{209}{}{That's the right answer, bitch. Know your place. Ben and I have known each other for a long time, he trusts me. And who are you? I've only seen you a few times.}
{210}{}{You should wash your mouth with soap.}
{211}{}{Ah, so Ben's place still gives you a sense of superiority. Don't think about crossing my path, carrion.}
{212}{}{OK.}
{213}{}{Take it easy, buddy. I'm in your gang too.}
{214}{}{Exactly. Don't think about crossing me.}
{215}{}{OK.}

#Acquaintance
{220}{}{What the hell are you walking around here, carrion road?}
{221}{}{Just looking around. And who are you?}
{222}{}{I want to get acquainted. I'm new here.}
{223}{}{Get to know each other, huh? MEET YOU, bitch? Do I look like a prostitute to you? You will get acquainted with corpses in the wastelands, and we have a gang. They don't like soft-bodied brats here. Get this straight.}
{224}{}{You have shitty manners, bro.}
{225}{}{Yes, that's right, bro. I see you're starting to learn something. Maybe we'll work together again.}
{226}{}{Great, the first contact is estaablished.}
{227}{}{This is not a good start.}
{228}{}{Then shove your manners up your ass and dance a jig on the hot asphalt, bitch.}
{229}{}{Whoa, take it easy. I just want to talk to you.}
{230}{}{I'm looking for someone to deal with in this dump. And it looks like you're one of them.}
{231}{}{Okay, I see you're not one of the timid guys. Consider that the first contact was a success. But don't count on trust just because Ben lets you walk around the base. Show yourself in action, then we'll talk.}
{232}{}{Okay. Who are you anyway?}
{233}{}{My name is Rio, baby. And this is the end of our acquaintance, until you show yourself in action.}
{234}{}{You'll have to answer the questaions.}
{235}{}{Well, that's fine.}

#Repeat dialog
{250}{}{What do you need?}
{251}{}{What do you need, carrion?}
{252}{}{How's it going?}
{253}{}{Bye, Rio.}

{260}{}{I'm wondering how someone like you ended up in a gang.}
{261}{}{There were overlays. I had to wander around the highways with different gangs until I ended up here.}
{262}{}{What, kicked out of all normal cities?}
{263}{}{What are you implying, bitch? Do you think the gang just appeared like that? We are all victims of circumstances, understand this.}
{264}{}{Yeah, sure, that sounds a lot better.}
{265}{}{What did you do?}
{266}{}{Is it really so bad in the cities?}
{267}{}{The gang didn't just show up. We're all victims of circumstances, you know?}
{268}{}{I understand. I was also forced to leave my home.}
{269}{}{Exactly. Here everyone was driven from their homes.}
{270}{}{It seems that everyone here is inclined to blame external circumstances for their problems.}
{271}{}{And what made you?}
{272}{}{In Phoenix, I played for the wrong team when Aaron took over. So I had to flee to Casa Grande, fleeing from the punitive fires.}
{273}{}{Didn't you please the local authorities there, too?}
{274}{}{What happened in Casa Grande?}
{275}{}{Aaron is a real tyrant. You did the right thing to escape from this hell.}
{276}{}{The water pump was repaired in Casa Grande at that time. Clan wars started around him. Guess whose team won this time.}
{277}{}{You're a born loser.}
{278}{}{Bad luck again?}
{279}{}{I hope these tyrants will be severely punished.}
{280}{}{But things are different in Ben's gang. Everyone here is their own, everyone gets what they deserve... But why the hell am I talking to you about this? This chatter is starting to get boring. Fuck off, I need to do my favorite hardware.}
{281}{}{Not before I find out something else.}
{282}{}{With pleasure. Later.}

{290}{}{What do you do in a gang?}
{291}{}{I am the second face of the Blue Shields. After Ben, of course. While he's gone, I run everything here- I keep order, I distribute rations, I teach youngsters, I make lazy sons of bitches work. }
{292}{}{[Next]}
{293}{}{And when Ben comes back, I do everything to make him feel at home - dope, girls, iron.}
{294}{}{Clear.}
{295}{}{What can you teach?}
{296}{}{Training? Interestaing, tell me more.}
{297}{}{We need to be in shape. I teach the use of weapons, conduct fights and initiation rites. It is especially valuable for us to handle fire bombs and cold weapons.}
{298}{}{It wouldn't hurt me to learn how to throw fire cocktails.}
{299}{}{I'm not interestaed in that.}
{300}{}{Teach you? I'll tell you what it is - I don't like you.}
{301}{}{Okay, we'll come back to that.}
{302}{}{Imagine - you are to me too.}
{303}{}{Well, you are here recently. So if you want to be trained, bring me something valuable.}
{304}{}{OK. But you'll have to wait.}
{305}{}{Well, no. I thought there should be other relationships in the gang.}
{306}{}{But I'm already in a gang. Why not?}
{307}{}{Either pay or fuck off.}
{308}{}{Okay...}
{309}{}{Come on, bro. Don't I deserve respect?}
{310}{}{Damn, you're twisting my balls. Okay, get ready for a fight, I'm kind today.}
{311}{}{Great, let's start the fun...}
{312}{}{Not now, I need to do something first.}
{313}{}{I have 250 caps. Is that enough?}
{314}{}{Quite. Go get ready for a fight.}
{315}{}{Great, let's start the fun...}
{316}{}{Will you teach me how to fight with knives?}

{320}{}{About this motorcycle.}
{321}{}{For Ben, it's not just a toy, it's part of his life. I make sure he doesn't need anything. Fixing a bike, looking for dope, looking for women - and everything else that Ben needs.}
{322}{}{Cool. I will know.}
{323}{}{Wow, so he's on the move?}
{324}{}{Sure. Who do you think I am? If Ben said to watch his bike, then the bike will be fine.}
{325}{}{Is it for sale?}
{326}{}{You're delusional. Ben appreciates this iron more than any of the gang. He won't give it up for anything.}
{327}{}{Ben lent me his motorcycle. Give me the key.}
{328}{}{What are you doing, bitch? I took care of Ben's motorcycle like it was my own dick. Now you come and want to take him away? I want to know what kind of shit you're rubbing his ears that he's getting so kind.}
{329}{}{I'm sorry, I don't want to fight with you. Of course, keep the keys. It's okay, bro.}
{330}{}{Great, let's figure out our relationship once and for all. Right here and now.}
{331}{}{Yes. Now you're going to dance for me on the hot asphalt.}
{332}{}{. . .}
{333}{}{Shut up and give me the keys.}
{334}{}{Oh, now we're angry. Bitch, it's *me* who's angry here!}
{335}{}{I understand your feelings. Let me pay 250 caps as compensation.}
{336}{}{Are you trying to bribe me? ME? I'll take these bottlecaps. But when the time is right, I'll shove them down your throat and make you shoot your anus on the tires. Bitch, you'll remember this day again.}
{337}{}{Maybe. Now give me the key.}
{338}{}{Shut your mouth and give me the key.}
{339}{}{Calm down, Rio. Ben is still loyal to you. And me too.}

{340}{}{Ben lent me his motorcycle. Give me the key.}
{341}{}{If someone else were in your place, I would finish him off. Do you know why?}
{342}{}{Yes, I somehow...}
{343}{}{Why?}
{344}{}{I took care of Ben's motorcycle like it was my own dick. Blew away every speck of dust to please him. Do you think I like that Ben treats my work like this?}
{345}{}{Wait...}
{346}{}{Damn it, why is he doing this to me? For what! I was loyal to him, I fulfilled all his whims, and he just gave you the bike. I can't believe it.}
{347}{}{Rio, don't be so jealous. He just borrowed a bike, that's all.}
{348}{}{Jealous? Ha! Yes, you are a soft-bodied snake, you show what you are worth.}
{349}{}{Give me the key.}
{350}{}{Shut your mouth and give me the key.}
{351}{}{It's time to understand, Rio, that you're not alone in the gang. Sometimes you have to share with others.}
{352}{}{It's all because of you! You're like a snake sneaking into bed. While you were away, everything was going well between Ben and me.}
{353}{}{You'd better discuss this with Ben. Now give me the key.}
{354}{}{Shut your mouth and give me the key.}
{355}{}{Here's the key. I hope you will do me a counter favor and crash in the first canyon.}
{356}{}{Relax, man.}
{357}{}{You can't intimidate me.}

#Delivery of dope
{400}{}{You said something about a business in Phoenix. Maybe I can help in some way?}
{401}{}{Maybe. But what's it to you?}
{402}{}{I want to benefit the gang. }
{403}{}{Well, wow. You want to be ahead of everyone. And you're a sly son of a bitch.}
{1403}{}{Well, wow. You want to be ahead of everyone. And you're a sly son of a bitch.}
{404}{}{I want to change your fucking attitude towards me.}
{405}{}{You're thinking right. My respect must be EARNED.}
{406}{}{Just business. Quid pro quo.}
{407}{}{So this is how you imagine membership in Blue Shields? At least it's fair.}
{408}{}{So what's your problem?}
{409}{}{Our courier from the Big City has disappeared somewhere. He must have been killed or something. You need to take the parcel to the customer instead.}
{410}{}{What kind of goods do you deliver to Phoenix?}
{411}{}{Hydrocarbons, do you understand? We have a whole tank of them. And the craftsmen in Phoenix make all kinds of dope and other useful liquid out of it.}
{412}{}{Who should I take the package to?}
{413}{}{Usually the raw materials are bought by a dealer in the slums. Don't forget to take a counter package from him.}
{414}{}{OK, I'll take the package.}
{415}{}{I love performance. But fill in - the dealer shouldn't get hurt.}
{416}{}{Clear.}
{417}{}{You're kidding. I didn't join the gang to carry parcels. Look for the six of the other raiders.}
{1417}{}{You're kidding. I didn't join the gang to carry parcels. Look for the six of the other raiders.}

{420}{}{I have your drugs.}
{421}{}{Hmm, you really keep your word. I probably should have treated you better.}
{422}{}{[Next]}
{423}{}{Here's your payment and some dope. Now you have the right to relax.}
{424}{}{That's right.}
{425}{}{Your dealer leaned back. Looks like you're out of dope.}
{426}{}{How did this happen?}
{427}{}{I have no idea.}
{428}{}{I see. S-bitches, I'll kill you if I find it. Okay, there's nothing to do now.}
{429}{}{Bye, Rio.}