{100}{}{You have a prisoner in front of you.}
{101}{}{It looks like the bandits are forcing this man to hard work.}
{102}{}{Am I free? Really?!}

{110}{}{They grabbed me and make me work.}
{111}{}{Are you in a gang too?}
{112}{}{I can't do it anymore, I don't have the strength.}
{113}{}{When will they leave me alone?}
{114}{}{Save me, you're better than these robbers.}

{120}{}{They grabbed me and make me work.}
{121}{}{Are you in a gang too?}
{122}{}{Kill me, I can't take it anymore.}
{123}{}{When will you leave me alone?}
{124}{}{You'd better kill me.}

{200}{}{hello}
{201}{}{for now}

{210}{}{hello}
{211}{}{for now}