{100}{}{You see a captive.}
{101}{}{It looks like this man is doing forced labor on behalf of the bandits.}
{102}{}{I'm free? Really?!}

{110}{}{They captured me and are making me work.}
{111}{}{You're in the gang too?}
{112}{}{I can't do this anymore, I have no strength left.}
{113}{}{When will they leave me alone?}
{114}{}{Save me! You're better than those bandits, right?}

{120}{}{They captured me and are making me work.}
{121}{}{You're in the gang too?}
{122}{}{Kill me, I can't endure any more of this.}
{123}{}{When will you leave me alone?}
{124}{}{You should kill me instead.}

{200}{}{hi}
{201}{}{bye}

{210}{}{hi}
{211}{}{bye}