{100}{}{You see Ben's concubine.}
{101}{}{You see a woman. Her tormented face is contorting in a hysterical fit.}
{102}{}{Consider this a favor, bitch.}
{103}{}{I hope you will rest in peace now.}

{110}{}{Please kill me!}
{111}{}{I won't be able to live after what they've done to me.}
{112}{}{They were so cruel.}
{113}{}{I can't endure any more of this.}
{114}{}{You must kill me.}
{115}{}{I simply want to rest in peace.}

{120}{}{I can't believe they are all dead! Thank you.}