{100}{}{Here is Ben's concubine.}
{101}{}{You see a woman. Her exhausted face contorts in a hysterical fit.}
{102}{}{Consider it a favor, bitch.}
{103}{}{I hope you find peace now.}

{110}{}{Please kill me!}
{111}{}{I can't live after what they did.}
{112}{}{They mistreated me.}
{113}{}{I can't take it anymore.}
{114}{}{You have to kill me.}
{115}{}{I just want to find peace.}

{120}{}{I can't believe they're all dead! Thank you.}