{100}{}{You see gates.}

{110}{}{The gates are locked from the inside.}
{111}{}{These gates are locked.}
{112}{}{You take the heavy bar off the gates. Now the way outside is open.}
{113}{}{The gates are locked from the inside. They cannot be opened from here.}
{114}{}{You have already taken the bar off these gates.}
{115}{}{You have returned the bar to it's place. The gates are locked once more.}
{116}{}{You must close these gates first.}
{117}{}{The bar is put only inside.}
{118}{}{There is no lock here. These gates are locked by a bar.}
{119}{}{These gates are too durable to be knocked out this way.}