{100}{}{There is a gate in front of you.}

{110}{}{This gate is locked from the inside.}
{111}{}{These gates are locked.}
{112}{}{You remove the heavy bolt from the gate. Now the way out is clear.}
{113}{}{The gate is locked from the inside. You can't open them from here.}
{114}{}{You have already removed the bolt from this gate.}
{115}{}{You have returned the bolt to its place. The gate is locked again.}
{116}{}{First you have to close this gate.}
{117}{}{The bolt is locked only from the inside.}
{118}{}{There is no lock here. These gates are bolted.}
{119}{}{These gates are too strong to knock them out in this way.}