{102}{}{This poor sod was tied to a stake for all to see. He is losing his mind from the heat, talking to himself.}
{103}{}{Humans can't be repaired. Unfortunately.}

{200}{}{Hey, water! I beg of you, give me some water!}
{201}{}{[Walk past the man]}
{202}{}{[spit on the ground] Here is your water.}
{203}{}{Mercy, senor! I am dying of thirst!}
{1203}{}{Mercy, senora! I am dying of thirst!}
{204}{}{You should have thought of that before you were tied to this stake. Bye.}
{205}{}{Fine, I'll go find you some water.}
{206}{}{Oh god, of course, I'll get you water right away.}

{210}{}{Gulp, gulp, ahh, water! Never before was I so happy to just have water. Thank you, senor, you are saving me from certain death.}
{1210}{}{Gulp, gulp, a-ahh, water! Never before was I so happy to just have water. Thank you, senora, you are saving me from certain death.}
{211}{}{Tell me, what were you tied to this stake for?}
{212}{}{Who is the animal who tied you to this stake and left you to suffer under the sun?}
{213}{}{It was Frank. He punishes everyone who is guilty of trivial things like that.}
{214}{}{What are you guilty of?}
{215}{}{Isn't this too heavy a punishment?}
{216}{}{Well, I just had some tequila... and then I started screaming and kicking things. My fault, I admit that. But I would have gotten away with it had I not screamed at Frank himself. That was a mistake.}
{217}{}{Still, he had a reason. It's good that you admit that.}
{218}{}{That guy has no right to act like this. You did nothing wrong.}
{219}{}{I understood that I was not in the right. This won't happen ever again. If only the rest would forgive me... Agh-h, now my head's splitting...}
{220}{}{Do you want me to untie you?}
{221}{}{Okay, so long.}
{222}{}{No, senor. Thank you, but Frank won't like this one bit. He'll tie me again, this time for a day. Or maybe even two. There is no need to provoke him, senor. This is how things go here - either you follow the rules, or you are forced to follow them. I already felt it on my own skin and won't repeat this mistake again.}
{1222}{}{No, senora. Thank you, but Frank won't like this one bit. He'll tie me again, this time for a day. Or maybe even two. There is no need to provoke him, senor. This is how things go here - either you follow the rules, or you are forced to follow them. I already felt it on my own skin and won't repeat this mistake again.}
{223}{}{And who is this Frank?}
{224}{}{He's our commandant. Perhaps the most important person in the town. He's there, in the prison by the gates.}

{230}{}{Thank you, senor, you're saving me from death.}
{1230}{}{Thank you, senora, you're saving me from death.}
{231}{}{Goodbye.}
{232}{}{I can untie you.}