{102}{}{This poor guy was tied to a pole for everyone to see. From the heat he goes crazy and talks to himself.}
{103}{}{A person cannot be repaired. Unfortunately.}

{200}{}{Hey, water! Please give me some water!}
{201}{}{[Pass by]}
{202}{}{[spit on the ground] Here's some water for you.}
{203}{}{Mercy, señor! I'm dying of thirst!}
{1203}{}{Mercy, señora! I'm dying of thirst!}
{204}{}{You should have thought of that before you were tied to the stake. Goodbye.}
{205}{}{Okay, I'll get you some water.}
{206}{}{Oh my God, of course, I'll get you some water now.}

{210}{}{Urp, urp, ah, water! I've never been so happy with plain water. Thank you, señor, you are saving me from death.}
{1210}{}{Urp, urp, ah, water! I've never been so happy with plain water. Thank you, señora, you are saving me from death.}
{211}{}{Tell me, why were you tied to a post?}
{212}{}{Who is the knacker who tied you up and left you to suffer under the sun?}
{213}{}{It was Frank. This is how He punishes everyone who is guilty of every little thing.}
{214}{}{What have you done wrong?}
{215}{}{Isn't the punishment for wrongdoing too heavy?}
{216}{}{Well, I just had too much tequila... and then he became violent. My fault, I admit. But I would have gotten away with it if I hadn't yelled at Frank himself back then. That was a mistake.}
{217}{}{Still, Frank had a reason. It's good that you admit it.}
{218}{}{Frank can't do that. You didn't do anything wrong.}
{219}{}{I realized that I was wrong. It won't happen again. If only the others would forgive me... Ah-h, now my head is splitting...}
{220}{}{Do you want me to untie you from the post?}
{221}{}{Okay, come on.}
{222}{}{Nope, señor. Thanks, but Frank won't like it. He'll tie me up again for a day. Or even two. Don't provoke him, señor. This is how everything works here - either you obey the rules, or you are forcibly subordinated. I have already felt it on my own skin and I will not make this mistake again.}
{1222}{}{Nope, señora. Thanks, but Frank won't like it. He'll tie me up again for a day. Or even two. Don't provoke him, señora. This is how everything works here - either you obey the rules, or you are forcibly subordinated. I've already felt it the hard way and I won't make this mistake again.}
{223}{}{And who is this Frank?}
{224}{}{This is our commandant. Probably the most important person in town. He's here, in the prison near the front gate.}

{230}{}{Thank you, señor, you are saving me from death.}
{1230}{}{Thank you, señora, you are saving me from death.}
{231}{}{Be there.}
{232}{}{I can untie you from the post.}