{100}{}{You see Alexandra.}
{101}{}{You see a smiling girl. It looks like she doesn't fully understood where she ended up.}
{102}{}{I'm sorry, you can't come in here openly carrying weapons.}
{103}{}{I'm sorry, you can't come in here wearing armor.}
{104}{}{I'm... ya-a-a... I want to sleep. Come back in the morning...}

{200}{}{Oh, hi! First time I'm seeing you.}
{201}{}{I'm }
{202}{}{. What's your name?}
{203}{}{Likewise. Who are you?}
{204}{}{Alexandra Titova. I'm Nestor's assistant. Happy to meet you.}
{205}{}{You have an unusual surname.}
{206}{}{What kind of name is that?}
{207}{}{My forebears were from a different part of the Earth. But none of it matters now. And the name is just a tribute to the memory.}
{208}{}{Alright.}
{209}{}{I think it's a tribute to insanity.}

{220}{}{How can I help you?}
{221}{}{I don't need help right now. See you later.}
{222}{}{What's happening? Why are there so many people over there?}
{223}{}{The people are worried about the explosion in Puerto. It's unclear how we'll survive without the Brotherhood of Steel. I very much hope they aren't going to incite a revolution and will instead calm down.}
{224}{}{So that's how it is...}
{225}{}{I require medicine.}

{230}{}{Tell me about Nestor.}
{231}{}{Well, he's the only real doctor in town. He's also a nerd, but of the cool variety.}
{232}{}{And what about you?}
{233}{}{I'm only learning from him. I'm nowhere close to the title of doctor. But I can stich up a wound... I think.}
{234}{}{Alright.}
{235}{}{What is this place?}
{236}{}{A Follower of the Apocalypse charity clinic in the name of Saint Diego.}
{237}{}{I see why the smell is so bad now.}
{238}{}{Oh wow, a real hospital! So, can I heal my wounds here?}
{239}{}{We heal all those in need, conduct experiments and make medicine. Yes, due to all of this, it often smells badly here. But you get used to it rather quickly.}
{240}{}{Can I buy medicine here, for traveling? I could use an antidote for radscorpion venom.}
{241}{}{Of course. Just tell me what you need. But we do hope that you'll give something useful to our hospital in exchange.}
{242}{}{Of course. Will keep that in mind.}
{243}{}{Hey, you're back! Though, to be honest, we're in a difficult situation.}
{1243}{}{Hey, you're back! Though, to be honest, we're in a difficult situation.}
{244}{}{What do you mean?}
{245}{}{The Brotherhood of Steel's outpost blew up! They say the explosion looked like it came from an atomic bomb. Without the Brotherhood, fewer and fewer traders will come to Casa Nueva. And we'll have to spend a whole lot of caps for security...}
{246}{}{And?}
{247}{}{So basically, keep in mind that prices have become higher. Including our clinic's services.}
{248}{}{Alright. I *will* keep that in mind.}

{250}{}{Listen, do you have anything stronger than bandages and stimpaks?}
{251}{}{Like what?}
{252}{}{Nothing, forget it.}
{253}{}{You know, pre-War medicine was obviously better than the stuff we have nowadays.}
{254}{}{Yeah, I think that way as well. But we're forbidden from selling some old medicines and chemicals such as buffout or psycho. They're considered unsafe.}
{255}{}{Then we shouldn't even be discussing this. Let's change the subject.}
{256}{}{Yes, that's exactly what I'm looking for. Is there really no way to acquire even a bit? For science?}
{257}{}{I don't know what science it is you need them for, but I have clear instructions. Go to Nestor if you don't like this.}
{258}{}{Fine. Looks like there's no point continuing this conversation. Bye.}
{259}{}{Come on - it's basically a giant amount of caps!}
{260}{}{Ahem. I think you urgently need some fresh air. The door is over there.}
{261}{}{Don't even think about telling anyone!}
{262}{}{Fine, I don't want trouble. I'm leaving.}
{263}{}{Just think about it for a second, how does your clinic benefit from spoiled goods that aren't being bought or used?}
{264}{}{Yes... of course... Hm, maybe Nestor will make an exception for you. We really *are* in need of caps.}
{265}{}{Thank you.}
{266}{}{Please make an exception for me. I won't tell anyone.}
{267}{}{Nestor will allow it. I'm effectively already a member of your team, after all.}
{268}{}{I need a dose for... what were they called... for experiments, yes.}
{269}{}{I have a purely scientific interest in them, colleague. We both know how important it is for scientists to support one another.}
{270}{}{That has really become a problem in Phoenix, believe it or not. I personally know the story of one drug addict from the slums.}
{271}{}{Poor fellows. Because of someone's stupidity, science suffers. Is drug addiction the fault of medicine?}
{272}{}{So, is there really no way to acquire even a bit of those substances? You know, for science?}
{273}{}{We shouldn't discuss this any longer. Let's change the subject?}
{274}{}{Diana knows that I don't suffer from stupidity.}