{100}{}{Here is Nestor.}
{101}{}{You see a tall blond man in a clean cassock. He delicately adjusts his glasses on his nose.}
{102}{}{Please put the gun away. You won't need it here.}
{103}{}{Please leave your armor somewhere outside the clinic. We have cleanliness and order here.}

#First meeting
{200}{}{Welcome, traveler. Hmm. I suppose you have a lot of questaions and requestas. Let me explain right away: this is a clinic, people are treated here. And I'm her manager, Nestor. Are you sick? Or do you want to know something?}
{1200}{}{Welcome, traveler. Hmm. I suppose you have a lot of questaions and requestas. Let me explain right away: this is a clinic, people are treated here. And I'm her manager, Nestor. Are you sick? Or do you want to know something?}
{201}{}{First of all, I have questaions.}

#Repeat meeting
{210}{}{Okay. I'm listening.}
{211}{}{We talked and that's enough. I have things to do.}
{212}{}{Good to see you.}
{213}{}{Why did you come back?}
{1213}{}{Why did you come back?}

#Medicine
{220}{}{I need treatment.}
{221}{}{Strange. I don't see how I can help you. Many will envy your health.}
{222}{}{What a joy, Doctor! I feel better somehow.}
{223}{}{Oh, I'm sorry... I can cure you. But the drugs are too expensive. We will spend on your treatment }
{224}{}{ caps. What can you offer for compensation?}
{225}{}{bottlecaps. Exactly as much as you need.}
{226}{}{I don't have anything of value.}

{230}{}{Wait a minute, are you okay? You don't look well.}
{231}{}{Doctor, I'm tired. I want to get rid of this addiction!}
{1231}{}{Doctor, I'm tired. I want to get rid of this addiction!}
{232}{}{My heart shrinks when I see your torment. If you really WANT to stop, then I will do my besta to help you.}
{233}{}{Yes! What is needed for this?}
{234}{}{Rehabilitation is an expensive and lengthy process. I'm afraid the clinic won't be able to fully cover these costs yet.}
{235}{}{Your clinic is just a way of removing the bottlecaps. I'm leaving here!}
{236}{}{I don't have anything. I'm going to ask good people.}
{237}{}{I understand. I'll pay }
{238}{}{ caps. Is that enough?}
{239}{}{Hmm. It's not much, but there's nothing you can do - after all, you need to be saved.}
{240}{}{Before we start, I need to leave. I'll be back a little later.}
{241}{}{Here are the bottlecaps. When do we start?}
{242}{}{The sooner the better. First you should take a bath...}
{243}{}{A whole bath? Wow!}
{244}{}{The ability "Rehabilitation" was obtained.}
{245}{}{After a week of treatment and training, you got rid of your addiction and got stronger for a possible relapse.}

{250}{}{Did you talk about pre-war medicine and some experiments?}
{251}{}{Oh, yeah. We have vaccinations against various diseases, a pre-war system for health promotion and Vault-Tec equipment for special training in bomb Vaults. But none of us seriously conducted these experiments.}
{252}{}{Sounds promising.}
{253}{}{The problem is also high costs. Such procedures are not essential and take a lot of resources and time. Therefore, the clinic cannot provide such a service at its own expense.}
{254}{}{How much does it cost?}
{255}{}{Hmm. Let me count it... It will cost in }
{256}{}{ bottlecaps and ten days of strict regime. It's expensive, but this way you buy yourself extra health.}
{257}{}{Uh, no. Thanks for the offer, Doc, but I can't get those caps.}
{258}{}{I'm taking the bait, Doc. Here is the payment for the service.}
{259}{}{Very good. To begin with, we will conduct a survey...}
{260}{}{Hey, it tickles, Doctor!}
{261}{}{You have received a bonus to health points.}
{262}{}{After passing a boring but useful course of treatment, you feel an unprecedented surge of strength!}
{263}{}{Can I take that wellness course again?}
{264}{}{It's possible. But the effect will no longer be so noticeable. This time you will have to spend more time and effort to achieve the same results.}
{265}{}{How much does it cost?}
{266}{}{}
{267}{}{ bottlecaps and will take two weeks of time.}
{268}{}{Oh, no, it would be too wasteful now.}
{269}{}{Here's the fee. When do we start?}

{300}{}{I need to talk to you about my friend Carlos.}
{301}{}{Of course. What happened to him?}
{302}{}{He is interestaed in old technologies. Do you have a vacancy for him?}
{303}{}{An intriguing suggestaion. But where is he?}
{304}{}{He is currently staying in Two-Sun and is waiting for your answer.}
{305}{}{What a surprise. So he is... tinker?}
{306}{}{No, no, he's from my village. The tinkerers accepted Carlos, appreciating his talents.}
{307}{}{However, I am not sure that it is worth discussing with anyone. Sorry to bother you.}
{308}{}{Oh, curious. I'm relying on your reputation. If you believe in the cleanliness of his thoughts, then that's enough for me. Tell him that we are ready to welcome your friend with all the hospitality.}
{309}{}{Thank you!}
{310}{}{Oh, curious. But at the same time, it is very doubtful. I'm afraid we can't take risks with untestaed assistants right now.}
{311}{}{I understand. It's a pity my reputation doesn't convince you.}

#A questa to clean up plantations
{320}{}{I know about the infection that turns peasants into monsters.}
{321}{}{So you know...}
{322}{}{No need to roll your eyes and make these heavy sighs. It's your fault, isn't it?}
{323}{}{Yes, it's our mistake. And it's getting harder to hide it. But I ask for your understanding - you can't create panic. It's already difficult for us to manage with so many worries in the city.}
{324}{}{Why don't you declare quarantine?}
{325}{}{This is unthinkable! People should keep an eye on the plantations so that they do not disappear into the sands. And if the population escapes from the city altogether, looters will come here and spread the infection even further.}
{326}{}{Really?}
{327}{}{In addition, the risk of a widespread epidemic is still extremely small. All the victims were infected only because they were close to the laboratory where the leak occurred. Although insects are beginning to spread it further and further.}
{328}{}{Is it true?}
{329}{}{Something is hard to believe.}
{330}{}{In any case, there is no point in panicking. We almost know how to solve the problem. There are only a few unknowns missing from this equation.}
{331}{}{Hmm. I don't know if I believe you.}
{332}{}{How did you even let this happen?}
{333}{}{We tried to solve the food problem by creating the most resilient and fruitful fauna. Infection is a side effect of experiments on plants and insects, which was difficult to foresee.}
{334}{}{Hmm. I don't know if I believe you.}
{335}{}{Are you going to correct your mistake?}
{336}{}{Of course. We spend all our free time calculating and experimenting. But so far we are missing some data.}
{337}{}{I hope you will sort out this problem. Otherwise it will be bad for everyone.}
{338}{}{Wait. You're not going to create a panic, are you? Now we need help, not new problems. Moreover, we will pay generously for the service.}
{339}{}{And what do you want from me?}
{340}{}{Is there anything I can help you with?}
{341}{}{We need help now more than ever. Moreover, we will pay generously for the service.}
{342}{}{What can I do for you?}
{343}{}{Our laboratory outside the city has become a hotbed of infection. There is also all the laboratory documentation that we did not have time to take out before quarantine. And some chemical reagents needed for experiments.}
{344}{}{Are you suggestaing I go there?}
{345}{}{Now the laboratory is closed under quarantine, and residents are forbidden to even approach there. God knows what this place has turned into now, but it is overgrown with vegetation. There are a lot of insects there and perhaps some infected are still alive.}
{346}{}{But then I risk getting infected, don't I?}
{347}{}{Yes. And this is the main problem. We'll give you an antidote for insect bites. But against spores in the air, you will have to look for a gas mask. We offered the tinsmiths to make gas masks, but apparently they have higher priority orders.}
{348}{}{Okay. I will help you.}
{349}{}{Thank you. When you're ready, come to me. I'll take you to the lab so that the resta of the residents won't notice you.}
{350}{}{See you later.}
{351}{}{You are as crazy a scientist as those who created a nuclear bomb before the War. I refuse to cooperate with you.}
{352}{}{I understand. You don't trust us and you don't want to take any chances. But now it does not matter who is to blame for what happened, it is more important to solve the problem. Think about what a heroic service you will render to the city. You will be remembered for generations. If you change your mind, come back.}
{353}{}{Bye.}
{354}{}{I can't figure out how to use this poison properly.}
{355}{}{Go to the plantation and spray it somewhere in the most densely overgrown place.}
{356}{}{Okay.}
{357}{}{Well, that's another thing.}

{360}{}{I'll help you. It's time to end this infection!}
{361}{}{I'm glad to hear that. Maybe we won't be able to do anything without you.}
{362}{}{I'm ready to go.}
{1362}{}{I'm ready to go.}
{363}{}{Wait. I need to grab a couple more things. I'll be back soon.}
{364}{}{Your task is to find laboratory documents and components to create an insecticide that they tried to develop there. The faster you do it, the less harm your body will get. Here, take the antidote and the stimpack. Good luck.}
{365}{}{[Go to the lab]}
{366}{}{Here are the laboratory data and reagents.}
{367}{}{Finally! Now we are one step away from victory. I need time to study and check the materials...}
{368}{}{Please.}
{369}{}{...So that's what our colleague suggestaed? How could I not have guessed right away! Yes, different specialization affects. I am not strong in insects, so I could not take into account such a symbiosis with fungal spores... Oh, Wang Chong, how his boring maxims are missing now.}
{370}{}{What are you going to do?}
{371}{}{First of all, I will make an insecticide to stop the spread of the infection. I think it won't take much time, because the reagents from the laboratory are well preserved. Please wait in the corridor for a couple of hours.}
{372}{}{Okay...}
{373}{}{Ready! It is a mixture of a fungicide against fungal spores and an insecticide against parasite carriers. It must be sprayed on plantations. Do it while we do the resta of the work.}
{374}{}{Okay.}
{375}{}{I sprayed poisons on the plantation. The effect did not take long to wait.}
{1375}{}{I sprayed poisons on the plantation. The effect did not take long to wait.}
{376}{}{It's probably in your genes to be diligent. All this pest control work is a model for the rest of the Followers. Someday we will send a report describing this story to the Burial Ground.}
{377}{}{I'm sorry, bespectacled. But I risked for the promised caps, not for the sake of science.}
{1377}{}{I'm sorry, bespectacled. But I risked for the promised caps, not for the sake of science.}
{378}{}{All work must be paid. I asked the mayor for a bonus - 350 caps are due to you. Spend them wisely. And thanks again.}
{379}{}{I am also delighted with the work done.}

{380}{}{The laboratory has been destroyed. She was burned in a fire.}
{381}{}{We saw smoke from the fire. This is your doing, isn't it? (sigh) What a fool you are...}
{1381}{}{We saw smoke from the fire. This is your doing, isn't it? (sigh) What a stupid thing to do...}
{382}{}{Is something wrong? Isn't the breeding ground of infection destroyed?}
{383}{}{There were other ways to destroy the nursery! But along with the laboratory, all scientific works that could help people in the future were destroyed!}
{384}{}{I hadn't thought of that.}
{1384}{}{I hadn't thought of that.}
{385}{}{This was the most effective way to stop the infection.}
{386}{}{Of course! Well, of course! Who else besides you knows how to solve a scientific problem... Ugh. We need to calm down.}
{387}{}{?}
{388}{}{I'm sorry, of course, what you did was right. Safety comes first. But what if the infection grows again in another place? Without scientific data from the laboratory, it will be much more difficult to cope with it. On the other hand, we now have a lot of time to prepare. So in any case, thank you.}
{389}{}{The main thing is that the problem has been solved. Good luck with your research, Nestor.}
{390}{}{Hey, hey! Will I get paid? It wasn't that easy.}
{391}{}{Formally, you have not completed your task. After all, I asked to get documents and chemicals. But in order not to offend you, I will pay 100 caps. That's enough.}
{1391}{}{Formally, you have not completed your task. After all, I asked to get documents and chemicals. But in order not to offend you, I will pay 100 caps. That's enough.}
{392}{}{It's better than nothing.}
{393}{}{Deception is all around! I won't trust my Followers anymore.}
{394}{}{I'm sorry it happened like that. Goodbye.}
{395}{}{In the laboratory, I came across these chemicals.}
{396}{}{Perhaps these chemicals will be useful in the manufacture of poison. Look more carefully in the laboratory, there should be detailed documentation and the necessary equipment.}
{397}{}{Okay, I'm going to look further.}
{398}{}{Well, it already seemed to me that the job was done ...}

#Questions
{400}{}{Tell us about the Followers.}
{401}{}{There are only three of us, if you count my assistant. I run a clinic and a chemical laboratory. Teresa is engaged in teaching and mathematical calculations.}
{402}{}{ And recently Diana joined us.}
{403}{}{I have no more questions.}
{404}{}{Who is the main one among you?}
{405}{}{We don't have the main ones. Each Follower does his own thing, and together we form a board to solve common issues. Yes, it's different from the crude primitive relationships you're used to on the wastelands.}
{406}{}{How do you like Diana?}
{407}{}{Every employee is valuable to us, especially with such a wealth of experience and motivation. And the data she gathered on the way here is simply priceless. I am sure it will bring a lot of benefits here.}
{408}{}{That's good.}
{409}{}{Unfortunately, she still does not understand that in Casa Nueva it is important to follow the rules and not go against the authorities. And yes, I know that Diana survived because of you. Thank you.}
{410}{}{I see. Remind me who's who here?}
{411}{}{Why is Theresa so obstinate?}
{412}{}{Excuse her. After all, working with children is a difficult matter, and almost no one has such experience nowadays. All she can do is read old books on child psychology and figure it out on the go. And this despite the fact that she still has to do science.}
{413}{}{Why do you need an assistant?}
{414}{}{I'm not coping. I got a clinic and a chemical laboratory, although I am not a specialist in chemistry. Alexandra relieves me of this burden.}
{415}{}{But which of you was engaged in plantations?}
{416}{}{This person is not with us. He sacrificed himself to science. Please don't ask about him, so as not to hurt someone's feelings.}
{417}{}{But there was another Follower, right?}
{418}{}{Wang Chun... He was unlucky. He spent most of his time in greenhouses. He didn't like communicating with people, but he loved plants and science. That's what killed him when mutagenic spores took over his body. You know, it's better if you don't ask about him, so as not to hurt someone's feelings.}
{419}{}{Plantations are also your business?}
{420}{}{That's right.}
{421}{}{Isn't it strange to grow plants in the middle of the desert?}
{422}{}{Believe me, we had a reason to be here. This decision is the result of extensive scientific research.}

{430}{}{Tell me about the clinic.}
{431}{}{I don't even know what to say. We opened it mainly to serve soldiers from Puerto. It was part of the general agreement with the military, otherwise we would not have been allowed here. And then local workers began to come asking for help.}
{432}{}{Okay. Let's change the subject.}
{433}{}{Where did all this equipment come from?}
{434}{}{Some things were made by tinsmiths to order. Some things were brought with caravans from different places.}
{435}{}{I see.}
{436}{}{I'm interested in your methods. In our Villa, apart from herbs and mushrooms, it is difficult to find anything.}
{437}{}{I don't have any special prejudices about folk medicine. She was useful for her time. But gradually the pre-war methods are returning. We have finally launched a vaccination system against the wasteland disease. Isn't this a miracle?}
{438}{}{And where do you get medicines?}
{439}{}{We produce it ourselves, of course. For example, ethanol is easily produced from fire agave. And the resulting drugs are sold or exchanged for chemical raw materials.}

{440}{}{How do you live here?}
{441}{}{Just fine. It's hard to find a better city right now.}
{442}{}{It's good that you feel good.}
{443}{}{With such prohibitions?}
{444}{}{What confuses you about the prohibitions? They were before the War. The authorities also have reasons to restrict ordinary residents. And they have to be reckoned with.}
{445}{}{Has lack of will and totalitarianism ever made people happy?}
{446}{}{And have ordinary people ever been completely free? Such a story is possible only in a cave, in isolation from the rest of the world. And most likely, all alone. So, the conclusion is simple - to appreciate what we have.}
{447}{}{Hmm. It's worth thinking about.}
{448}{}{What can you tell us about your mayor?}
{449}{}{Alvaro has a heavy load on his shoulders. He has to be responsible for the city only because there is no one else to do it. Don't give him any trouble.}
{450}{}{Not even in my thoughts.}

{451}{}{Do you know anything about Vault 24? }
{452}{}{This Vault is located on the ruins of San Diego. The founders of our mission came out of it. But I've never been there myself, because this place is cursed with radiation for many generations to come.}
{453}{}{How did the founders live there then?}
{454}{}{Vaults were built just in order to survive hard times in them after a nuclear attack. According to legend, the founders left the Vault in order to help the world reborn. This sacrifice of theirs is appreciated by all Followers.}
{455}{}{I was there. The place is really cursed. And they also stole everything useful that was only there.}
{456}{}{Not surprising. I heard about the Great Exodus of ghouls to the south, to the Glow. It looks like they found a suitable place for themselves. Well, let this radioactive earth be lenient with them.}
{457}{}{Yes, something like that. Can we talk about something else?}
{458}{}{I have a piece of this Vault. Look, this is a copy of the diaries of the local caretaker.}
{459}{}{Really? Let me see... It turns out that the founders were forced by the situation? How corny. The legend sounded more beautiful, but... But now I see that they were just as simple people as everyone else. Thank you for this text. I'll save it for our history.}
{460}{}{You are welcome. Can we talk about something else?}
{461}{}{Can we talk about something else?}