{100}{}{This is Wang Chun.}
{101}{}{You see a large spreading tree. The pattern on its bark reminds you of a man's face. Wait a minute...}
{102}{}{*Cough-cough*}
{103}{}{It's hard to talk in this smoke. We need to get out into the fresh air faster.}

{110}{}{Hr-r-r}
{111}{}{Z-z-z}
{112}{}{Here, my sweet mantissas, yes, get in your mouth.}
{113}{}{Yum, yum, what a juicy mantissa.}
{114}{}{My roots feel a stranger.}
{115}{}{Hmm, I smell an unfamiliar footstep.}
{116}{}{What is it? What are you saying?}
{117}{}{Herbert, Bob, Nestor - you've grown so much lately.}
{118}{}{Now I understand how you miss the sunlight.}
{119}{}{We need more fertilizers from human compost.}
{120}{}{Oh-x...}
{121}{}{*Heavy sigh*}

{150}{}{Go ahead, my little green friends!}
{151}{}{Grab them and tear them to shreds!}
{152}{}{Show your grip!}
{153}{}{Grab them with your sharp paws!}

{200}{}{Ah... uh... Wow. How long I slept... Oh, Mom. So that's why the servants woke me up.}
{201}{}{Eh, who are you... or what are you?}
{202}{}{Horror! A talking plant!}
{203}{}{I am Wang Chun, the scientist who created these gardens of paradise. And who are you? Oh, yes, I know. People like you flock to the smell of nectar, like stupid dummies, so that soon they will be eaten by predatory plants. In any case, coming here is a big mistake on your part.}
{204}{}{Why so?}
{205}{}{You know, if I wasn't obsessed with science and the prosperity of the world, I would have run away from here long ago. But now I belong here. My grave will be here. If you come out of the earth, you will return to it.}
{206}{}{What are you talking about?}
{207}{}{Circular circulation of matter in nature. We are all a lump of sticky mud. Look at me. I won't be able to walk anymore. Rooted to the ground where he used to wander like an amaranth tumbleweed.}
{208}{}{You're too talkative for a plant.}
{209}{}{Funny. I can no longer work with my hands and feet, but my brain is still in action. I'm holding on with the last of my strength so as not to go crazy. But I had a lot of time to think about myself and the world around me.}
{210}{}{I am so sorry. Are you in pain?}
{211}{}{Not anymore. My body is replaced by spores and plant cells. I can't work with my hands and feet, but my brain is still in action. I'm holding on with the last of my strength so as not to go crazy. But I had a lot of time to think about myself and the world around me.}
{212}{}{It's sad to see you like this. But I have business here. Bye.}
{213}{}{No! Stop! I was just as stupid and careless when I came to this dome hoping to taste the fruits of the Ancients. I was in too much of a hurry and made a number of mistakes. Now the whole valley is a paradise for mutants. And if this is not stopped, the whole wasteland will change. People will see the birth of a new world, but there will be no place for them in it.}
{214}{}{I'm here on Nestor's assignment. I need documents and chemicals to fight the infection.}
{215}{}{I don't want to be exposed to the same infection. Is there any medicine against it?}
{216}{}{And what is "contagion"? People parasitizing on the remnants of an old civilization? Oh, how blind I was when I came to this dome hoping to taste the fruits of the Ancients! I was in too much of a hurry and made a number of mistakes. Now the whole valley is a paradise for mutants. And if this is not stopped, the whole wasteland will change. And people... there will be no place for people in this new world.}
{217}{}{How so? Can't this infection be stopped?}
{218}{}{May. But if the Followers receive laboratory records and other materials of the complex, someday they will continue their research. And the trouble will happen again.}
{219}{}{Then what do you suggest?}
{220}{}{We need to destroy the WHOLE complex! Fire is the best way to stop the spread of infection beyond the valley. After all, the dome is its main breeding ground.}
{221}{}{The main thing is to stop mutations. I'll do it.}
{222}{}{Oh-very good, pilgrim. Find the gas pipes. It's not easy to set them on fire, but someone has already tried. Find his digested remains in the greenhouses and take the explosives.}
{223}{}{Okay. I'll try.}
{224}{}{Too risky. Bye, Wang Chun.}
{225}{}{You're definitely going crazy. There is no place in the wastelands more colorful and lively than the dome. Surely there is a way to stop the infection without a fire.}
{226}{}{Stupid! I was looking for ways to limit the growth of harmful spores. But no one knows if it will work! Suddenly the growth will continue? Find the gas pipes and blow them up! This is the only way!}

{230}{}{*Heavy sigh*}
{231}{}{Z-z-z}
{232}{}{Hr-r-r}
{233}{}{Whatever it is, this creature is fast asleep.}