{100}{}{You see Teresa.}
{101}{}{You see a short-haired woman in a hoodie. She has a very strict facial expression.}
{102}{}{I apologize. But I need to get some sleep before class.}
{103}{}{How dare you scare children with your terrible armor?}
{104}{}{School is not a place for weapons.}

{200}{}{Hello. To what do I owe such attention?}
{201}{}{What is this place?}
{202}{}{Oh, how sad that modern people have forgotten what "school" means. Here we teach children the simplest sciences like literacy and mathematics. We are probably the only operating school in Sonora and Arizona.}
{203}{}{But why do they need it?}
{204}{}{So that the world does not slide into the Stone Age. Even now there is not a single school in the wastelands, much less a university. Ancient knowledge is forgotten, but new knowledge is not accumulated. After all, people are busy surviving, although a scientific approach would solve this problem as well.}
{205}{}{Who do you take me for, woman? I know what "school" is!}
{206}{}{Well, if so. But it's unlikely that you studied there, judging by your tone.}
{1206}{}{Well, if so. But it's unlikely you studied there, judging by your tone.}
{207}{}{Amazing! A real school! I thought they all closed down after the Great War.}
{208}{}{All right. We had to work hard to revive the good old tradition. Many residents did not even want to give up their children.}
{209}{}{By the way, who are you that teach children to write and count?}
{210}{}{Who are you anyway to teach children to write and count?}
{211}{}{How interesting. And who created this school?}
{212}{}{We Are Followers Of the Apocalypse. Our mission is to bring enlightenment to the lands of Sonora.}
{213}{}{I see.}
{214}{}{By the way, I have come across Followers of Fire. They also have a library and they also teach children.}
{215}{}{Ugh, these half-wits don't know what they're talking about. What can they teach with their twisted faith? Do not confuse the scientific school and theology. We, the Followers of the Apocalypse, are direct carriers of pre-war science.}
{216}{}{Really?}
{217}{}{Don't believe religious fanatics. God only knows what's on their minds.}
{218}{}{Good.}

{220}{}{So what do you want to know?}
{221}{}{I know enough. Goodbye.}
{222}{}{Wait a minute. Let's be clear - they teach knowledge here, not combat... "arts". We don't like violence, and we certainly won't tolerate it at school. So keep your fists, knives, and whatever else you have in stock with you. And there's nothing to smile so brazenly. You have been warned.}
{223}{}{Agreed. My fighting skills will remain outside of school.}
{224}{}{You watch your tongue, too, if you don't want problems.}

{230}{}{Tell the story of the Followers.}
{231}{}{Initially, we were a small group of free residents on the ruins of San Diego. But it was impossible to live there, and then we moved to the ruins of Los Angeles. There, in the barely surviving library, we founded the headquarters, which exists to this day.}
{232}{}{Go on.}
{233}{}{Look at this picture. It was made a hundred years ago in Inferno.}
{234}{}{What is it... Oh my God, unbelievable! If the date is correct, then we have a real piece of ancient history in front of us!}
{235}{}{I see you are very pleased with this thing.}
{236}{}{We have not yet seen a single document from the time of the Great War. You see, they say the War passed in just a couple of hours. Thousands of nuclear bombs exploded all over the planet in this short period. Besides, a lot of time has passed since then, and many documents have simply not been preserved. Needless to say, even if books have become very rare.}
{237}{}{Go on.}
{238}{}{Here we have direct evidence of what the nuclear explosion in Mexicali looked like... Well, that's what this city was called before the War.}
{239}{}{Now it is called Inferno. Do you want to buy this thing?}
{240}{}{Of course! Give it to us, for the sake of science.}
{241}{}{Of course, take it. Consider it my donation to the school.}
{242}{}{Thank you very much. We will add your name to the list of benefactors.}
{243}{}{Not so fast. It cost me a lot of effort to get this thing and bring it here.}
{244}{}{OK. I'm going to talk to the other Followers now. We will try to collect a set of medicines for you. This is the most valuable thing in our city.}
{245}{}{Here. Another thing.}
{246}{}{I will give this thing away, but in return, I want to listen to lectures about that era.}
{247}{}{Oh, what an honor.}
{248}{}{Since then, many people have joined us. And some, like me, go to remote lands for missionary purposes to establish a new temple of science there.}
{249}{}{The temple of science? So are you still a religious organization?}
{250}{}{No, no, it's just an old expression. Science and religion have little overlap. In any case, we don't want churches, because they will teach us to argue about God and belittle the gentiles.}
{251}{}{Thanks for the story.}

{260}{}{Where did these old books come from?}
{261}{}{Mostly they are brought by caravans. What has been preserved in the surrounding ruins, we have collected for a long time.}
{262}{}{I see.}
{263}{}{Alas, these four small cabinets are a pitiful trifle compared to what is in the Los Angeles library. Most of these books are of little use for teaching or science.}
{264}{}{I can bring books that I find when traveling.}
{265}{}{Oh, that would be great. We have to appreciate any find. Of course, we will pay for the work.}
{266}{}{I'll keep that in mind. Goodbye.}
{267}{}{I have an old book for your library.}
{268}{}{Just fine. Where is she?}
{269}{}{She's in a different place. I'll bring it soon.}
{270}{}{This is the book.}
{271}{}{There are two whole books here.}
{272}{}{There are actually three of them. Here they are.}
{273}{}{Take all the books I have. There's a whole stack of them here.}
{274}{}{Thank you very much. Here is the payment - }
{275}{}{ caps.}
{276}{}{I'll bring more if I find it. Goodbye.}
{277}{}{Leave the bottlecaps to your school. This is my donation.}
{278}{}{Thank you. This will help our school.}
{279}{}{Goodbye.}

{280}{}{Where can I get old books?}
{281}{}{We and our mercenaries have already surveyed the nearest ruins. I doubt that there are deposits of ancient books somewhere nearby. However, there is one place, but access to it is closed. This is a military base in Puerto.}
{282}{}{Where would books come from on a military base?}
{283}{}{These are not really books, but their electronic version. I know about it through communication with the scribes of the Brotherhood of Steel. But they gave an unequivocal refusal to my requests to share knowledge.}
{284}{}{Here are the misers.}
{285}{}{They probably have their reasons.}
{286}{}{But old books are the property of all mankind, not just the chosen ones. Maybe you can get into the base and copy the texts? I'll pay and give you an empty holodisk to record.}
{287}{}{I'm not on my way at all. Sorry.}
{288}{}{OK, I'll do it. Let's have a holodisk.}
{289}{}{Thank you. Here's a holodisk. Copy on it at least the most important and necessary for our school. Good luck.}
{290}{}{Goodbye.}
{291}{}{We and our mercenaries have already surveyed the nearest ruins. I doubt that there are deposits of ancient books somewhere nearby.}
{292}{}{I see. We'll have to look in more remote counties.}
{293}{}{I managed to infiltrate the Brotherhood's base and record their books.}
{294}{}{What wonderful news! We need books in any form. The Brotherhood has no moral right to hide them from the public.}
{295}{}{Here is the holodisk.}
{296}{}{I'll pay 100 caps for it. Thank you very much.}
{297}{}{Please.}