{100}{}{You see Nestor.}
{101}{}{You see a tall, blonde man in clean robes. He is gently adjusting his glasses.}
{102}{}{Please put away your weapon. You will not need it here.}
{103}{}{Please put your armor away, somewhere outside the clinic. This environment must be kept clean and orderly.}

#First encounter
{200}{}{Welcome, wanderer. Hm-m. I suppose that you have many questions and requests. Let me say this up front: this is a clinic, people are healed here. And I'm it's manager, Nestor. Are you hurt? Or do you want to learn something?}
{1200}{}{Welcome, traveler. Hm-m. I suppose that you have many questions and requests. Let me say this up front: this is a clinic, people are healed here. And I'm it's manager, Nestor. Are you hurt? Or do you want to learn something?}
{201}{}{Questions first.}

#Repeated encounters
{210}{}{Alright. I'm listening.}
{211}{}{That's enough talk for now. I've got stuff to do.}
{212}{}{Happy to see you.}
{213}{}{Why did you come back?}
{1213}{}{Why did you come back?}

#Medicine
{220}{}{I need to be healed.}
{221}{}{Strange. I don't see any way I could help you. Many would envy your health.}
{222}{}{That's very good, doc! I don't even feel that bad now.}
{223}{}{Oh, I'm sorry... I can heal you, but the medicine is far too expensive. We will have to spend }
{224}{}{ caps on it. What can you offer as compensation?}
{225}{}{Cold hard caps. Exactly how many are necessary, no more, no less.}
{226}{}{I don't have anything of value.}

{230}{}{Wait, are you alright? You don't look good.}
{231}{}{Doc, I'm sick of this. I want to get rid of my addiction!}
{1231}{}{Doc, I'm sick of this. I want to get rid of my addiction!}
{232}{}{My heart aches when I see your suffering. If you really do WANT to stop, then I will do everything in my power to help you.}
{233}{}{Yes! What is needed for this?}
{234}{}{Rehabilitation is a long and expensive process. I'm afraid the clinic won't be able to fully cover the costs.}
{235}{}{Your clinic is just a way of extorting caps. I'm outta here!}
{236}{}{I don't have anything. I'll go ask kinder people.}
{237}{}{I understand. I'll pay }
{238}{}{ caps. Will that be enough?}
{239}{}{Hm-m. It's not much, but we don't have a choice - we do need to help you.}
{240}{}{Before we start, I need to do some things. I'll be back later.}
{241}{}{Here are the caps. When do we start?}
{242}{}{The earlier, the better. First, you should take a bath...}
{243}{}{An entire bath? Wow!}
{244}{}{You have received the "Rehabilitation" perk.}
{245}{}{After a week of healing and training, you have dealt with your addiction and have gained resistance to relapses.}

{250}{}{I recall you talking about Pre-War medicine and some experiments.}
{251}{}{Ah, yes. We have vaccines for various illnesses, a Pre-War system for improving health and Vault-Tec equipment for special training in a fallout shelter environment. But none of us have conducted these experiments in a serious fashion.}
{252}{}{Sounds promising.}
{253}{}{The problem also lies in the high costs. Such procedures are not top priority and also demand many resources and time. Which is why the clinic cannot finance them by itself.}
{254}{}{How much does it cost?}
{255}{}{Hm-m. Let me calculate it... It will cost }
{256}{}{ caps and ten days of strict regime. Expensive, but you are effectively buying additional health.}
{257}{}{Uhh, no. Thanks for the offer, doc, but I just can't get that kind of money.}
{258}{}{I'm swallowing the bait, doc. Here is the payment.}
{259}{}{Very good. First, let's begin with an examination...}
{260}{}{Hey, it tickles, doctor!}
{261}{}{You have received additional health points.}
{262}{}{After completing a boring, but useful course, you feel like you have become much stronger!}
{263}{}{Can I go through this wellness course again?}
{264}{}{You can. But the effects will not be as noticable. This time you'll have to spend more time and energy to achieve the same results.}
{265}{}{How much does it cost?}
{266}{}{}
{267}{}{ caps and two weeks of your life.}
{268}{}{No, this will be too wasteful at this moment.}
{269}{}{Here is the money. When will we begin?}

{300}{}{I need to talk to you about my friend Carlos.}
{301}{}{Of course. What happened to him?}
{302}{}{He is interested in old technologies. Will you find a place for him?}
{303}{}{An intriguing offer. But where is he?}
{304}{}{Right now, he's in Two Sun and is awaiting your reply.}
{305}{}{How unexpected. So he is a... tinsmith?}
{306}{}{No, he's from my village. The tinsmiths accepted Carlos, seeing value in his talents.}
{307}{}{Now that I think of it, I'm not actually sure whether this is worth discussing with anyone. I apologize for the disturbance.}
{308}{}{Huh, curious. I'm relying on your reputation. If you believe in the purity of his motives, that is enough for me. Tell him that we are ready to offer your friend a place among us.}
{309}{}{Thank you!}
{310}{}{Huh, curious. But at the same time, suspicious. I'm afraid at the moment we cannot take risks with our assistants.}
{311}{}{I understand. It is a shame that my reputation has not convinced you.}

#Plantation cleanup quest
{320}{}{I know all about the disease turning peasants into monsters.}
{321}{}{So you are aware...}
{322}{}{No need to roll your eyes and make deep sighs. You're responsible, aren't you?}
{323}{}{Yes, it was an error on our part. And it is becoming more and more difficult to hide it. But you must understand - under no circumstances can there be panic in the population. It's difficult enough dealing with the currently present problems of this town.}
{324}{}{Why haven't you declared quarantine?}
{325}{}{It's out of the question! People must look after the plantations so that they don't dissapear into the sands. And if the population flees the town entirely, marauders will come and spread the disease even further.}
{326}{}{Really?}
{327}{}{And even then, the risk of an epidemic is quite low at the moment. All the victims became infected only because they happened to be near the laboratory where the leak occured. Though data suggests insects are starting to spread it further and further.}
{328}{}{Is this true?}
{329}{}{I find that hard to believe.}
{330}{}{In any case, panic is pointless. We almost know how to solve this. There are only a few unknowns in this equation.}
{331}{}{Hm-m. I don't know whether I can trust you or not.}
{332}{}{How did you make this happen anyway?}
{333}{}{We were trying to end food scarcity here by creating the most lively and fertile flora possible. The disease is but a side effect of experiments on plants and insects, which was hard to predict.}
{334}{}{Hm-m. I don't know whether I can trust you or not.}
{335}{}{You *are* going to be cleaning after the mess you made, right?}
{336}{}{Of course. We're spending all the time we have on calculations and experiments. But right now, we lack some data.}
{337}{}{I hope you're going to solve this problem. Otherwise, everyone will suffer.}
{338}{}{Wait. You aren't going to make the people panic, right? We need help now, not more problems. And more than that - we will provide proper compensation.}
{339}{}{And what is it you want me to do?}
{340}{}{Can I help you in any way?}
{341}{}{Right now, we need help like never before. And more than that - we will provide proper compensation.}
{342}{}{What can I do for you?}
{343}{}{Our laboratory outside of the town is spreading the disease. All the documentation that we didn't manage to take with us before quarantine is also located there. In addition to some chemical reagents needed for our experiments.}
{344}{}{And you're saying I need to go there?}
{345}{}{Right now, the laboratory is under quarantine, and the population is prohibited from even going near it. God knows what that place has turned into, but we know for certain that it has been overtaken by vegetation. There are many insects there, and it is possible some of the infected are still alive.}
{346}{}{But am I not risking infection, then?}
{347}{}{Yes. That's the main problem. We'll give you an antidote for the insect bites. But to not inhale the spores in the air, you'll have to find a gas mask. We offered the tinsmiths to make them, but it seems they have prioritized other offers.}
{348}{}{Okay. I'll help you.}
{349}{}{Thank you. When you're ready, come to me. I'll show you a way to the laboratory that will avoid you being seen by the population.}
{350}{}{See you.}
{351}{}{You're a mad scientist, no different from the ones that created the atom bomb before the War. I refuse to work with you.}
{352}{}{I understand. You don't trust us and don't want to risk yourself. But who is responsible is irrelevant now. Solving the problem is the important thing. Think what a heroic deed you'll do for the town. You'll be remembered for generations. If you change your mind, come back.}
{353}{}{Bye.}
{354}{}{I have no idea how to correctly use this poison.}
{355}{}{Go to the plantation and spray it in the most overgrown place you see.}
{356}{}{Understood.}
{357}{}{Now we're talking.}

{360}{}{I'll help you. Time to rid the world of this disease!}
{361}{}{Happy to hear it. It may very well be possible that we won't be able to do anything without you.}
{362}{}{I'm ready to head out.}
{1362}{}{I'm ready to head out.}
{363}{}{Wait. I need some time to pick a few things. I'll be back.}
{364}{}{Your goal is to find the documents and chemicals needed to create the insecticide that we were trying to develop there. The quicker you do it, the less harm will be done to your body. Here, take this antidote and stimpak. Good luck and godspeed.}
{365}{}{[Head out to the laboratory]}
{366}{}{Here are the reagents and the data from the laboratory.}
{367}{}{Finally! Victory is practically already in our reach. But I need some time to examine and check the materials...}
{368}{}{Go on.}
{369}{}{...So this was what our colleague was proposing? How did I not think of it right away! The fact that we are specialized in different fields is obvious here. I am not particularly knowledgable in entomology, which is why I could not have considered the development of such a symbiotic relationship with the spores of the fungi... Oh, Van Chun, you have no idea how much we miss you.}
{370}{}{What are you going to do?}
{371}{}{First things first, create an insecticide that will prevent the disease from spreading. I don't think it should take much time. After all, the reagents from the laboratory are quite well-preserved. Please wait in the corridor for a few hours.}
{372}{}{Okay...}
{373}{}{We did it! This is a mixture of a fungicide against fungi spores and an insecticide against the parasitic disease carriers. It must be sprayed over the plantations. Go do that while we conclude other tasks.}
{374}{}{Okay.}
{375}{}{I sprayed the poison all over the plantation. The results showed themselves quickly.}
{1375}{}{I sprayed the poison all over the plantation. The results showed themselves quickly.}
{376}{}{Diligence must be part of your DNA. All this pest control is an example other Followers ought to look up to. One day we'll send a report describing this story to the Boneyard.}
{377}{}{Sorry, nerd. I took this risk for the caps, not for science.}
{1377}{}{Sorry, nerd. I took this risk for the caps, not for science.}
{378}{}{Effort must be rewarded. I asked the mayor for a reward - these 350 caps belong to you. Spend them wisely. And once again, thank you.}
{379}{}{I'm amazed too.}

{380}{}{The laboratory is destroyed. Burned down.}
{381}{}{We saw the smoke. It was your doing, wasn't it? (sigh) What an idiot you are...}
{1381}{}{We saw the smoke. It was your doing, wasn't it? (sigh) How stupid...}
{382}{}{What's wrong? Wasn't the thing that was spreading the disease destroyed?}
{383}{}{It could have been destroyed in other ways! But along with the laboratory, all the scientific efforts that could have helped people in the future have been destroyed as well!}
{384}{}{I didn't think of that.}
{1384}{}{I didn't think of that.}
{385}{}{It was the most effective way to stop the disease.}
{386}{}{Of course! Oh, surely! Who else but you knows how to solve a scientific problem... Ooh. I need to calm down.}
{387}{}{Excuse me?}
{388}{}{I apologize, your actions were, of course, called for. Safety above all else. But what if the disease springs up again in another place? Without the scientific data from the laboratory it will be much more difficult to deal with it. On the other hand, we now have a lot of time to prepare. So, in any case - thank you.}
{389}{}{The most important thing is that the problem is solved. Good luck with your research, Nestor.}
{390}{}{Hey, hey! Will I get paid? That wasn't easy, you know.}
{391}{}{Strictly speaking, you have not completed your objective. After all, I asked you to get the documents and the chemicals. But to avoid any grievances, I will give you 100 caps. That will be enough.}
{1391}{}{Strictly speaking, you have not completed your objective. After all, I asked you to get the documents and the chemicals. But to avoid any grievances, I will give you 100 caps. That will be enough.}
{392}{}{Better than nothing, I suppose.}
{393}{}{Deceit, deceit everywhere! I will not believe a single word coming from the mouth of a Follower.}
{394}{}{I'm sorry it ended this way. Farewell.}
{395}{}{I managed to find these chemicals in the laboratory.}
{396}{}{Perhaps they will prove useful in manufacturing a poison. Search more carefully in the laboratory, there has to be detailed documentation and the necessary equipment there.}
{397}{}{Alright, I'll go continue my search.}
{398}{}{And here I thought I was done with this...}

#Questions
{400}{}{Tell me about the Followers.}
{401}{}{There are three of us, if you count my assistant. I manage the clinic and the chemical laboratory. Teresa teaches and deals with mathematical calculations.}
{402}{}{Diana has joined you lately.}
{403}{}{My questions have come to an end.}
{404}{}{Who's the leader here?}
{405}{}{We don't have leaders. Every Follower does their part, but together, we form the board - made to give everyone a voice in solving common problems. Yes, I know that's not like the crude, primitive relationships you, people from the Wastes are used to.}
{406}{}{What do you think about Diana?}
{407}{}{Every person is valuable, and one with such experience and motivation - especially so. The data she collected while on her way here has proved itself invaluable. I am sure she will prove very useful here.}
{408}{}{That's great.}
{409}{}{Unfortunately, she still fails to understand that in Casa Nueva, it is important to follow the rules and not go against authority. And yes, I know Diana survived thanks to you. You have done us a great service.}
{410}{}{Alright. Remind me, who are the important people here?}
{411}{}{Why is Teresa so obstinate?}
{412}{}{Excuse her. After all, working with kids is hard, and in the times we live in, barely anyone has any kind of experience in that field. The only thing she can do is read old books about child psychology and figure things out on the go. That is not even mentioning the scientific endeavors she is also involved in.}
{413}{}{Why do you need an assistant?}
{414}{}{I can't handle all the things I have to do. I'm responsible for the clinic and the chemical laboratory, even though I'm not specialized in chemistry. Alexandra takes off that pressure from me.}
{415}{}{But which one of you is responsible for the plantations?}
{416}{}{That man is no longer with us. He has sacrificed himself. For science. Please, do not ask anymore about him. It could hurt someone's feelings.}
{417}{}{But he was a Follower too, right?}
{418}{}{Van Chun... He got unlucky. Essentially, he spent a lot of time in the greenhouses. He did not like talking to other people, but he did love plants and science. That proved to be fatal when the mutagenic spores took over his body. You know, it would be better if you did not ask anyone about him. You know, to avoid hurting someone's feelings.}
{419}{}{The plantations are also your creation?}
{420}{}{Yes.}
{421}{}{Isn't it strange to grow plants in the middle of the desert?}
{422}{}{Oh, believe me, we had our reasons to be exactly in this spot. This decision was the result of extensive research.}

{430}{}{Tell me about the clinic.}
{431}{}{I really don't know what to say. We opened it mainly to serve soldiers from Puerto. That was part of our agreement with the military, otherwise we wouldn't be let in here. And then the local workers started asking us for help.}
{432}{}{Fine. Let's change the subject.}
{433}{}{Where is all this equipment from?}
{434}{}{Some of it was made by the tinsmiths as part of contracts. Some brought in by various caravans.}
{435}{}{Alright.}
{436}{}{I'm interested in your methods. It's hard to find anything other than herbs and mushrooms in Villa, where my people live.}
{437}{}{I am not prejudiced against folk medicine. For it's time, it was useful. But gradually, Pre-War methods are returning. We have finally launched a vaccination program against wasteland disease. Isn't that a miracle?}
{438}{}{Where do you get the medicine from?}
{439}{}{From our own labor. For instance, ethanol can be easily produced from fiery agave. And the resulting drugs can be sold or are exchanged for raw chemical material.}

{440}{}{How is life here?}
{441}{}{Close to perfect. In our times it's hard to find a better place.}
{442}{}{It's good that your lives are good.}
{443}{}{With these kinds of rules?}
{444}{}{Why do rules bother you? They were there before the War, too. The powers that be have their own reasons to limit the things ordinary people can do. And they have to be reckoned with.}
{445}{}{Has the lack of choice and totalitarianism ever made people happy?}
{446}{}{Was there ever a time when people were truly, completely free? That is possible only in a cave, detached from the rest of the world. And most likely, completely alone while you're at it. The conclusion is obvious - we must value what we have.}
{447}{}{I see.}
{448}{}{What can you tell me about your mayor?}
{449}{}{Alvaro carries much on his shoulders. He has to take care of the town only because nobody else can do it. You shouldn't bother him.}
{450}{}{I wasn't thinking about doing that at all.}

{451}{}{Do you have any information regarding Vault 24?}
{452}{}{It's located in the ruins of San Diego. The first Followers originated from it. But I've never been there myself, and don't plan to visit it. It's so irradiated that it will remain unsafe to visit for many generations.}
{453}{}{If it's so irradiated, how did those first Followers live there?}
{454}{}{The Vaults were built for this exact purpose, to allow those inside to survive the aftermath of nuclear attack. Legends say those first Followers decided to leave the Vault to assist in the restoration of the world. Every Follower values their sacrifice greatly.}
{455}{}{I've been there. It is irradiated, indeed. There wasn't even anything particularly useful. Everything valuable was taken away a while ago.}
{456}{}{Unsurprising. I've heard about it, the Great Exodus of ghouls to the south, towards the Glow. Looks like they found themselves a nice place to settle. Well, may that irradiated land be kind to them.}
{457}{}{Yeah, something like that. Let's change the subject.}
{458}{}{I've got something from that Vault. Take a look. It's a copy of the journals of the Vault's overseer.}
{459}{}{Really? Let's see... Huh. So the first Followers didn't leave to improve the world? The legends were more inspiring, but... But now I see that they were just people. Like us. Thank you for these documents. I'll save them as an addition to our history.}
{460}{}{You're welcome. Why don't we talk about something else?}
{461}{}{Let's change the subject.}