{100}{}{You see Teresa.}
{101}{}{You see a short-haired woman in a hoodie. She has a distinctive stern look on her face.}
{102}{}{I'm sorry, but I need to get enough sleep today.}
{103}{}{How dare you scare the children with your terrible armor?}
{104}{}{Weapons have no place in a school.}

{200}{}{Greetings. To whom do I owe the pleasure?}
{201}{}{What is this place?}
{202}{}{How sad that people today have forgotten what a "school" is. We teach children the basic sciences here, such as literacy and mathematics. It's likely that we're the only functioning school not only in all of Sonora, but the entire Arizona area.}
{203}{}{But why do they need to be taught all that?}
{204}{}{So the world doesn't slide back to the stone age. There is not a single school in the wastes, let alone a university. Ancient knowledge is being forgotten, and no new knowledge is being stored. All because humanity is now busy with surviving, even though science would solve that problem.}
{205}{}{Who do you take me for, woman? I know what a "school" is!}
{206}{}{Good, if it's true. But I do doubt you ever actually went to one, considering your tone.}
{1206}{}{Good, if it's true. But I do doubt you ever actually went to one, considering your tone.}
{207}{}{Amazing! A real school! And I thought they were all closed since the Great War.}
{208}{}{Indeed. We had to spend a lot of effort to restore this great old tradition. Many citizens did not even want to allow their children to come here.}
{209}{}{By the way, who are you that you can teach children how to write and count?}
{210}{}{Who the hell are you to be teaching children this kind of stuff?}
{211}{}{How interesting. And who created this school?}
{212}{}{We are the Followers of the Apocalypse. Our mission is to carry enlightenment into the lands of Sonora.}
{213}{}{Alright.}
{214}{}{I came across a similar organization - the Followers of the Holy Fire. They also have a library and they also teach children.}
{215}{}{Bleh, those loonies have no idea what they're even talking about. What can they teach with their perverted faith? Don't confuse a scientific school with a religious one. We, the Followers of the Apocalypse, are the direct carriers of Pre-War science.}
{216}{}{Oh really?}
{217}{}{Don't listen to religious fanatics. Who knows what's on their mind.}
{218}{}{Alright.}

{220}{}{So, what do you want to know?}
{221}{}{I know enough. Goodbye.}
{222}{}{Wait a minute. Let me make this clear. We teach knowledge here, not martial... "arts". We do not condone violence and will tolerate it here under no circumstances. So keep your fists, knives and whatever other things you have with you to yourself. You have been warned.}
{223}{}{Deal. My fighting skills will remain outside of this school's limits.}
{224}{}{You should watch yourself too, if you don't want trouble.}

{230}{}{Tell me the history of the Followers.}
{231}{}{At first, we were a small group of free people living in the ruins of San Diego. But it was impossible to live there, and so we went to the remains of Los Angeles. There, in a library that barely survived the War, we founded our headquarters, which still exist to this day.}
{232}{}{Go on.}
{233}{}{Look at this photograph. It was made a hundred years ago in Inferno.}
{234}{}{What is... Oh my god, that's incredible! If the date is correct, we have a real piece of ancient history on our hands!}
{235}{}{I see that this thing has made you very excited.}
{236}{}{We have not encountered a single document dating to the time of the Great War until now. You see, they say the War happened across a literal couple of hours. During this short timespan, thousands of atomic bombs were detonated all over the globe. And so much time has passed since then that many documents have simply not survived. Which is to be expected, considering even books have become a rare commodity.}
{237}{}{Go on.}
{238}{}{This is direct evidence of how the atomic blast in Mexicali looked like... That's how they called that town before the War.}
{239}{}{Nowadays, it's called Inferno. Do you want to acquire this thing?}
{240}{}{Of course! Give it to us. For science.}
{241}{}{Sure, take it. Consider it my donation to the school.}
{242}{}{Thank you so much. We'll enter your name in our list of patrons.}
{243}{}{Not so fast. I had to spend a lot of effort to get that thing and bring it here.}
{244}{}{Alright. I'll go talk to the other Followers. We'll try to gather together a set of medicines. They're the most valuable things we have in our town.}
{245}{}{Now we're talking.}
{246}{}{I'll give it to you, but in exchange, I want to listen to lectures about that era.}
{247}{}{Ooh, what an honor.}
{248}{}{Since then, many people joined us. And some, like me, go to distant places as missionaries to found new temples of science there.}
{249}{}{Temples of science? So you're a religious organization after all?}
{250}{}{No, no, it's just an old saying. Science and religion rarely intertwine. In any case, we do not want churches. They would bring only intolerance and division.}
{251}{}{Thanks for telling me this.}

{260}{}{Where are those old books from?}
{261}{}{They are mainly brought by caravans. We have collected everything that can be found in ruins around here a long time ago.}
{262}{}{Alright.}
{263}{}{Unfortunately, these small four bookshelves are nothing in comparison to what we have in the Los Angeles library. And most of these books are not useful for education or research.}
{264}{}{I could bring you books that I find in my travels.}
{265}{}{Ooh, that would be fantastic. We're forced to value any find. Of course, we'll pay you for it.}
{266}{}{I'll keep that in mind. Goodbye.}
{267}{}{I have an old book for your library.}
{268}{}{Great. Where is it?}
{269}{}{It's somewhere else. I'll bring it to you soon.}
{270}{}{Here is the book.}
{271}{}{I have two whole books.}
{272}{}{I actually have three. Here they are.}
{273}{}{Take all these books. There's an entire pile of them.}
{274}{}{Thank you very much. Here is the payment - }
{275}{}{ caps.}
{276}{}{I'll bring more if I find them. Goodbye.}
{277}{}{Leave the caps for your school. This is my donation.}
{278}{}{Thank you. This will help us a lot.}
{279}{}{Goodbye.}

{280}{}{Where can I find old books?}
{281}{}{We and our freelancers have already explored all nearby ruins. I doubt you'll find old books anywhere around here. Though there is one place, but access to it is restricted. The Puerto military base.}
{282}{}{Why would there be books on a military base?}
{283}{}{Not exactly books, but an electronic version of them. I know about them from conversations I've had with the scribes of the Brotherhood of Steel. To my requests to share this knowledge they gave unequivocal refusal.}
{284}{}{What a bunch of scrooges.}
{285}{}{I suppose they have their reasons.}
{286}{}{But old books belong to all mankind, not just a few select people. Maybe you could get inside the base and copy the texts? I'll pay and give you a blank holodisk for a recording.}
{287}{}{My destination is the opposite of that place. Sorry.}
{288}{}{Alright, I'll do it. Give me the holodisk.}
{289}{}{Thank you. Here is the holodisk. Copy at least the things that would be the most important and useful for our school. Good luck.}
{290}{}{Goodbye.}
{291}{}{We and our freelancers have already explored all nearby ruins. I doubt you'll find old books anywhere around here.}
{292}{}{Alright. I'll have to look for them in more distant regions.}
{293}{}{I managed to get on the Brotherhood's base and record their books.}
{294}{}{What wonderful news! We need books of any kind. The Brotherhood has no moral right to hide them from the rest of humanity.}
{295}{}{Here is the holodisk.}
{296}{}{I'll pay you 100 caps for it. Thank you very much.}
{297}{}{You're welcome.}