{100}{}{You see Van Chun.}
{101}{}{You see a big, sprawling tree. The pattern on it's bark reminds you of a human face. Wait a minute...}
{102}{}{*Cough-cough*}
{103}{}{It's hard to talk in this smoke. I need to get to fresh air as soon as possible.}

{110}{}{Hur-r-r}
{111}{}{Z-z-z}
{112}{}{Come, my sweet mantises, yes, come right into my mouth.}
{113}{}{Om-nom-nom, what a succulent mantis.}
{114}{}{My roots sense an outsider.}
{115}{}{Hm, I feel a stranger walking.}
{116}{}{What is this? What are you saying?}
{117}{}{Gerbert, Bob, Nestor - you've grown so much lately.}
{118}{}{Now I see how much you lack sunlight.}
{119}{}{We need more fertilizer from human compost.}
{120}{}{Oh-h...}
{121}{}{*Deep sigh*}

{150}{}{Go, my little green friends!}
{151}{}{Grab them and tear them to pieces!}
{152}{}{Show how you grab!}
{153}{}{Grab them with your sharp paws!}

{200}{}{Ah... Ooh... Ya-à. I've been sleeping for so long... Oh my. So that's why my servants have woken me up.}
{201}{}{Uhh, who are you... or rather, what are you?}
{202}{}{My god! A talking plant!}
{203}{}{I am Van Chun, the scientist that created these gardens of eden. And who are you? Oh yes, I know. Humans like you gather around the smell of nectar like stupid bloatflies to be eaten by predators. In any case, coming here was a grave mistake on your part.}
{204}{}{Why?}
{205}{}{You know, if I wasn't as focused on science and the world's prosperity, I would have escaped long ago. But now, this place will be my grave. I deserve it. I came out of the earth and will return to it.}
{206}{}{What the hell are you talking about?}
{207}{}{The circulation of matter in nature. We are all but a lump of sticky mud. Look at me. I cannot walk any longer. My roots have bound me to the earth that I once traveled across like an amaranthian tumbleweed.}
{208}{}{You're far too talkative for a plant.}
{209}{}{It's funny. My arms and legs don't work anymore, but my brain is still functioning. I'm doing all I can to not go mad. But on the other hand, I've had much time to think about myself and the world around me.}
{210}{}{I'm very sorry. Does it hurt?}
{211}{}{Not anymore. My whole body has been replaced with spores and plant cells. My legs and arms don't work anymore, but my brain is still functioning. I'm doing all I can to not go mad. But on the other hand, I've had much time to think about myself and the world around me.}
{212}{}{It's sad to see you like this. But I have business here. Goodbye.}
{213}{}{No! Stop! I was just as stupid and careless as you when I came into this dome in the hopes of tasting the fruit of the Ancients' knowledge. I hurried and made several mistakes. Now, this entire valley is a mutant paradise. And if this is not stopped, the entire wasteland will change. Humanity will see the birth of a new world, but will not find a place for itself in it.}
{214}{}{I'm here to do the task Nestor gave me. I need documents and chemicals to fight the disease.}
{215}{}{I don't want to be subjected to that disease. Is there any cure for it?}
{216}{}{Define "disease". Why not, "humans involved in a parasitic relationship with the remains of an old civilization?" Oh, how blind I was when I came into this dome in the hopes of tasting the fruit of the Ancients' knowledge. I hurried and made several mistakes. Now, this entire valley is a mutant paradise. And if this is not stopped, the entire wasteland will change. And as for mankind... there will be no place for humans in that new world.}
{217}{}{How? Is this disease impossible to stop?}
{218}{}{No. But if the Followers receive the data from the laboratory and other materials from the complex, they will one day decide to continue the research. And history will repeat itself.}
{219}{}{What are you proposing then?}
{220}{}{The ENTIRE complex must be destroyed! The research, the plants, nothing can survive. Fire is the best way to stop the disease from spreading beyond the valley's limits. For it's the dome that is the main source.}
{221}{}{The important thing is to stop the mutations. I'll do it.}
{222}{}{Very good, pilgrim. Find the gas pipes. They cannot simply be set on fire, but someone has already tried. Find their digested remains in the greenhouses and take the explosive from them.}
{223}{}{Alright. I'll try.}
{224}{}{Far too risky. Goodbye, Van Chun.}
{225}{}{You're definitely going mad. There is no place in the wastes more beautiful and full of life than this dome. There has to be a way to stop the disease without burning it all down.}
{226}{}{Foolish! I've tried finding ways to stop the growth of the harmful spores. But there is no guarantee that they will work! What if the growth continues? Find the gas pipes and blow them up! It's the only way!}

{230}{}{*Deep sigh*}
{231}{}{Z-z-z}
{232}{}{Hur-r-r}
{233}{}{Whatever it is, the creature is in a state of deep sleep.}