{100}{}{Here is Alexandra.}
{101}{}{You see a smiling girl. It seems as if she doesn't quite understand where she got to yet.}
{102}{}{Sorry, you can't bring weapons here.}
{103}{}{Sorry, you can't come here in armor.}
{104}{}{I... uh-huh... I want to sleep. Come back in the morning...}

{200}{}{Oh, hello! This is the first time I've seen you.}
{201}{}{I }
{202}{}{. What's your name?}
{203}{}{Similarly. Who are you anyway?}
{204}{}{Alexandra Titova. I'm Nestor's assistant. Nice to meet you.}
{205}{}{You have an unusual surname.}
{206}{}{What a ridiculous name?}
{207}{}{My ancestors were from another part of the globe. But it doesn't matter now. And the name is just a tribute to memory.}
{208}{}{I see.}
{209}{}{In my opinion, this is a tribute to senility.}

{220}{}{Can I help you with something?}
{221}{}{I don't need any help right now. See you later.}
{222}{}{What's going on? Why are there so many people in the square?}
{223}{}{Residents are excited about the explosion in Puerto. It is unclear how we will survive now without the Brotherhood of Steel. I really hope that they will not start a revolution and will calm down soon.}
{224}{}{That's how it is...}
{225}{}{I need medical supplies.}

{230}{}{Tell me about Nestor.}
{231}{}{Well, he's the only real doctor in town. He's also boring, but cool.}
{232}{}{What about you?}
{233}{}{I'm just learning from him. I'm still a long way from being a doctor. But I can sew up the wound already... I think so.}
{234}{}{I see.}
{235}{}{And what is this place?}
{236}{}{Charity Clinic of the Followers of the Apocalypse named after St. Diego.}
{237}{}{Now it's clear why it stinks so much here.}
{238}{}{Wow, a real hospital! So can I heal the wounds here?}
{239}{}{We treat all those in need, conduct experiments and manufacture medicines. Yes, because of all this, it sometimes smells bad here. But you get used to it quickly.}
{240}{}{And here you can buy medicines for the road? I could use an antidote to radscorpions.}
{241}{}{Sure. Just tell me what you need. But we hope that in return you will also contribute something useful to our hospital.}
{242}{}{Great. I will know.}
{243}{}{Hey, you're back! However, we have difficult times here.}
{1243}{}{Hey, you're back! However, we have difficult times here.}
{244}{}{What do you mean?}
{245}{}{Imagine, the Brotherhood of Steel fort exploded! They say the explosion was like a nuclear bomb. Well, without them, trade in Casa Nueva is declining. And you will have to spend a lot of caps on security...}
{246}{}{And?}
{247}{}{In general, keep in mind that prices have increased. Including the services of our clinic.}
{248}{}{I see. I'll keep that in mind.}

{250}{}{Listen, is there anything stronger than bandages and stimpacks?}
{251}{}{What, for example?}
{252}{}{No, forget it.}
{253}{}{Well, you know, pre-war medicine was clearly better than the current one.}
{254}{}{Yes, I think so too. But we are forbidden to sell some old medicines and chemicals like buffout and psycho. They are considered unsafe.}
{255}{}{Then it's not even worth discussing. Let's change the subject?}
{256}{}{Yes, that's exactly what I'm looking for. Is there really no way to get at least a pinch? For scientific purposes?}
{257}{}{I don't know what your scientific goals are there, but I have clear instructions. Talk to Nestor if you don't like it.}
{258}{}{Okay. There doesn't seem to be any point in continuing. Later.}
{259}{}{Come on - it's a mountain of caps!}
{260}{}{Ahem. In my opinion, you urgently need fresh air. The door is over there.}
{261}{}{Don't even think about blabbing!}
{262}{}{Okay, I don't want any problems. I'm leaving.}
{263}{}{Think about it, what good is your clinic from a damaged product that is not bought and not used?}
{264}{}{Yes... of course... Hmm, maybe Nestor will make an exception for you. We really don't have enough caps.}
{265}{}{Thank you.}
{266}{}{Please make an exception for me. I won't tell anyone.}
{267}{}{Nestor will allow it. You could say I'm already a member of your team.}
{268}{}{I need a dose for... what's their name... for experiments, yes.}
{269}{}{I have a purely scientific interest, colleague. We both understand how important it is for scientists to support each other.}
{270}{}{You'd be surprised, but it really became a problem in Phoenix. I personally know the story of a drug addict from the slums.}
{271}{}{Poor devils. That's how science suffers because of someone's stupidity. Is drug addiction the fault of medicine?}
{272}{}{So is there really no way to purchase at least a pinch of the drug? For scientific purposes?}
{273}{}{It's not worth discussing any more. Let's change the subject?}
{274}{}{Diana knows I won't do anything stupid.}