{100}{}{You see Carlos.}
{101}{}{You see one of Villa's peasants. But he has become... different.}
{102}{}{Hello. So nice to see you.}
{103}{}{Don't talk to me. The whole town's looking for you.}

{200}{}{What a surprise! Happy to see you, }
{201}{}{.}
{202}{}{How did the Followers treat you?}
{203}{}{Quite well. They're good people, which can't be said about the tinsmiths.}
{204}{}{Have you already figured out your place in Casa Nueva?}
{205}{}{There's enough work here for me. And I signed a contract for a few years... Well, put an X. Now I have shelter and everything needed to survive. I won't starve, that's for sure.}
{206}{}{Great. Can you help me in any way?}
{207}{}{You know, they gave me a medkit, but I doubt it will be very useful here. Here, take it, you need it more than I do.}
{208}{}{Thank you, Carlos. And goodbye.}

{210}{}{Hi, }
{211}{}{. How nice to see you.}
{212}{}{Goodbye, Carlos.}