{100}{}{You see Carlos.}
{101}{}{Here is one of the peasants of the Villa. However, he became somehow... other.}
{102}{}{Hi. Good to see you.}
{103}{}{Don't talk to me. The whole city is looking for you.}

{200}{}{What a surprise! Glad to see you, }
{201}{}{.}
{202}{}{How did your Followers receive you?}
{203}{}{Quite kindly. They are good people, which cannot be said about the tinsmiths.}
{204}{}{Have you sorted out your place in Casa Nueva yet?}
{205}{}{There's a lot of work for me here. Besides, I signed a contract for several years... Well, I put a cross. Now I have a home and all the conditions for survival. I won't starve, that's for sure.}
{206}{}{Cool. Is there anything you can help me with?}
{207}{}{You know, they gave me a first aid kit, but I doubt that it will be of any use here. Here, take it, you need it more.}
{208}{}{Thank you, Carlos. And goodbye.}

{210}{}{Hello, }
{211}{}{. Good to see you.}
{212}{}{Bye, Carlos.}