{100}{}{You see Chip.}
{101}{}{You see a local child.}
{102}{}{Wow, is that a real weapon? Do you have permission to carry it around?}
{103}{}{Oh wow, is that power armor? I thought Frank was just making stuff up.}
{104}{}{What are you doing?}
{105}{}{I miss Pinky.}
{106}{}{You cruel, cruel person! Why did you do it?}
{1106}{}{You cruel, cruel person! Why did you do it?}

#Floating dialogue
{110}{}{Hey, Pinky!}
{111}{}{Sit, Pinky!}
{112}{}{What a silly animal.}
{113}{}{No, Pinky!}
{114}{}{Don't scratch the floor!}
{115}{}{Pinky, stop gnawing the furniture.}
{116}{}{Oh, dad will be mad about this.}
{117}{}{Wait, I'll pour you some water.}
{118}{}{Are you hungry?}
{119}{}{You want something tasty?}
{120}{}{Look, I have a mantis' foot.}
{121}{}{Great, Pinky. Good Pinky.}
{122}{}{Here, take the yummy.}
{123}{}{Want some more?}
{124}{}{Give me your paw!}

{130}{}{Hey, Pinky!}
{131}{}{Stop whimpering, Pinky.}
{132}{}{The whole house has heard you by now.}
{133}{}{You want the neighbors to hear you?}
{134}{}{Stop scratching me!}
{135}{}{I worry about you, after all.}
{136}{}{Ugh, what's wrong with you?}
{137}{}{Maybe I should give you some water?}
{138}{}{Look at what you did!}
{139}{}{Where does it hurt?}

{200}{}{Hi. Do you need to talk to my dad? He should be in his cabinet.}
{201}{}{Yes. And you're his son?}
{202}{}{Uh-uh. I'm Chip.}
{203}{}{Alright.}
{204}{}{And what's that?}
{205}{}{That... That is Pinky. I'm watching after him...}
{206}{}{Hm. Interesting.}

#Dialogue
{210}{}{What are you doing?}
{211}{}{Oh my. I thought you were driven out of the town.}
{212}{}{Hey, so it's you they're talking about? That's cool.}
{213}{}{Look at him go! Seems like Pinky is finally back on his feet.}
{214}{}{You watch over Pinky.}

{219}{}{Bye, Chip.}

{220}{}{Do you know where your dad is?}
{221}{}{In his cabinet, probably. As usual. He spends all his time with his papers, and tells me to go away so I won't disturb him.}
{222}{}{Uhh, believe me, you really shouldn't "disturb" him.}

{230}{}{You sure have an unusual pet.}
{231}{}{This is Pinky. He's cool, but people don't want to see him in the town.}
{232}{}{Why?}
{233}{}{Well, they make up stuff. That he's dangerous, that he spreads disease or harms the plantations. Nonsense, basically. Frank is the one the most unhappy with him. He screams that he'll kill Pinky the moment he finds a convenient excuse.}
{234}{}{Pigrats really *can* be dangerous.}
{235}{}{But Pinky isn't like that! He still hasn't done anything bad. He just scratches at night. And he's become sick with something lately. While the others want him to die, he very much needs help right now.}
{236}{}{Maybe it's for the best. Bye.}
{237}{}{That's terrible. Hold on, boy.}
{238}{}{Let me examine that animal. Perhaps I'll be able to heal him.}
{239}{}{I had to do an entire operation on Pinky. But now that's all behind him.}
{240}{}{He really has gotten better! Amazing! Thank you so much. You know, I think he likes you. You can play with him, if you want. But don't go beyond the plantations. He could escape into the desert.}
{241}{}{Happy to help. Goodbye, Chip.}
{1241}{}{Happy to help. Goodbye, Chip.}
{242}{}{How unfair!}
{243}{}{I want to go for a walk with Pinky.}
{244}{}{If he wants to come with you, I'm not against it. Just don't go too far away from home.}
{245}{}{Thanks. I'll walk him around the closest regions.}