{100}{}{Here is a Chip.}
{101}{}{You see a local child.}
{102}{}{Wow, is this a real weapon? Do you have a permit?}
{103}{}{Wow, is that power armor? I thought it was Frank's invention.}
{104}{}{What are you doing?}
{105}{}{I miss Pinkie.}
{106}{}{Cruel! Why did you do that?}
{1106}{}{Cruel! Why did you do that?}

#Floating phrases
{110}{}{Hey, Pinkie!}
{111}{}{Sit down, Pinkie!}
{112}{}{What a stupid animal.}
{113}{}{No, Pinkie!}
{114}{}{Don't scratch the floor!}
{115}{}{Pinkie, stop gnawing on the furniture.}
{116}{}{Oh, Dad will scold for this.}
{117}{}{Wait, I'll pour you some water.}
{118}{}{Are you hungry?}
{119}{}{Do you want yummy?}
{120}{}{Look, I have a mantis foot.}
{121}{}{Well done, Pinkie. Good Pinky.}
{122}{}{Hold the yummy.}
{123}{}{Do you want more?}
{124}{}{Give me a paw!}

{130}{}{Hey, Pinkie!}
{131}{}{Stop whining, Pinkie.}
{132}{}{You've got the whole house on edge.}
{133}{}{Do you want the neighbors to hear?}
{134}{}{Stop scratching me!}
{135}{}{I'm worried about you.}
{136}{}{Oh, what's wrong with you?}
{137}{}{Can I give you some water?}
{138}{}{Look what you've done!}
{139}{}{What's hurting you?}

{200}{}{Hi. Are you going to my dad? He should be in his office.}
{201}{}{Yes. Are you his son?}
{202}{}{Yeah. I'm Chipo.}
{203}{}{I see.}
{204}{}{And who is this?}
{205}{}{This... It's Pinkie. I'm watching him...}
{206}{}{Hmm. Curious.}

#Dialog
{210}{}{What are you doing?}
{211}{}{Wow. I thought you were kicked out of town.}
{212}{}{Hey, isn't there so much talk about you around? Cool.}
{213}{}{Lately, Pinkie's been kind of groovy. It looks like he's completely recovered.}
{214}{}{You keep an eye on Pinkie there.}

{219}{}{Bye, Chip.}

{220}{}{Do you know where your dad is?}
{221}{}{In the office, probably. As usual. He's always sitting there over his papers, and he throws me out so that I don't bother him.}
{222}{}{Uh, believe me, you really shouldn't "bother" him.}

{230}{}{Unusual pet you have.}
{231}{}{It's Pinkie. He's cool, but people don't want him in town.}
{232}{}{Why?}
{233}{}{Well, they come up with all sorts of things. That he is dangerous, that he spreads the infection or harms the plantations. Some nonsense. Frank is most displeased with everyone. Shouts that he will kill Pinkie at any opportunity.}
{234}{}{Pig rats can really be dangerous.}
{235}{}{But Pinkie is not like that! He hasn't done anything wrong yet. Only scratching at night. And lately he's also been sick. While the others want him dead, he really needs help right now.}
{236}{}{Maybe it's for the best. Later.}
{237}{}{This is sad news. Hold on, man.}
{238}{}{Let me see this beast. Maybe I can cure him.}
{239}{}{I had to do a whole Pinky operation. But it's all over now.}
{240}{}{So he really recovered! Fantastic! Thank you very much. You know, he seems to like you. You can play with him if you want. But do not go further than the plantations, so that he does not escape into the desert.}
{241}{}{Glad to help. Good luck, Chipo.}
{1241}{}{I was glad to help. Good luck, Chipo.}
{242}{}{What an injustice!}
{243}{}{I'd like to take a walk with Pinkie.}
{244}{}{If he wants to go with you, then I don't mind. Just don't take him far from home.}
{245}{}{Thank you. I will walk with him in the nearest neighborhoods.}