{100}{}{You see a child.}
{101}{}{You see an unexpectedly clean and tidy child.}
{102}{}{Don't push me!}

{110}{}{Say "Hi" to the savages.}
{111}{}{Where are you from?}
{112}{}{Will you play with me?}
{113}{}{Mom and dad are away.}
{114}{}{Why do I have to do adult work?}
{115}{}{You're lucky - you don't need to work.}
{116}{}{I want to sleep.}
{117}{}{The night is cool. But you need to sleep when it's night.}
{118}{}{Do you grow plants too?}
{119}{}{I want to visit other towns.}

{120}{}{Z-z-z}
{121}{}{*Hur-r-r*}

{130}{}{Tra-la-la, tra-la-la. I don't hear you.}
{131}{}{Go back into the desert.}
{132}{}{Leave me alone.}
{133}{}{They say you're a criminal.}
{134}{}{Are you a thief?}

{1130}{}{Tra-la-la, tra-la-la. I don't hear you.}
{1131}{}{Go back into the desert.}
{1132}{}{Leave me alone.}
{1133}{}{They say you're a criminal.}
{1134}{}{Are you a thief?}