{100}{}{You have a child in front of you.}
{101}{}{You see an unexpectedly clean and tidy child.}
{102}{}{Don't push!}

{110}{}{Greetings to the savages.}
{111}{}{Where are you from?}
{112}{}{Will you play with me?}
{113}{}{Mom and Dad are gone.}
{114}{}{Why do I have to do adult work?}
{115}{}{You're lucky - you don't have to work.}
{116}{}{I want to sleep.}
{117}{}{It's cool at night. But you have to sleep at night.}
{118}{}{Do you grow plants too?}
{119}{}{I want to see other cities.}

{120}{}{Z-z-z}
{121}{}{*Hr-r-r*}

{130}{}{Tra-la-la, tra-la-la. I can't hear you.}
{131}{}{Go back to the desert.}
{132}{}{Leave me alone.}
{133}{}{They say you're a criminal.}
{134}{}{Are you a thief?}

{1130}{}{Tra-la-la, tra-la-la. I can't hear you.}
{1131}{}{Goes back to the desert.}
{1132}{}{Leave me alone.}
{1133}{}{They say you're a criminal.}
{1134}{}{Are you a thief?}