{100}{}{You see a resident of Casa Nueva.}
{101}{}{You see a local. Compared to the inhabitants of other settlements, they look quite well-fed and healthy.}

{110}{}{Hello. Where are you from?}
{111}{}{Don't go to the plantations, they'll think you're a thief.}
{112}{}{Sorry, I have too much work to do, I can't talk to you.}
{113}{}{I'd be happy to chat, but now is not the time.}
{114}{}{Follow the rules if you don't want trouble.}

{120}{}{I'll call the others if you don't leave me alone.}
{121}{}{Are you mad? It's night outside!}
{122}{}{Don't awaken the beast within me.}
{123}{}{Go away. Don't make me scream.}
{124}{}{How rude. Such uneducated outsiders...}
{125}{}{Now is not the time to talk. Go away.}
{126}{}{Listen, it's curfew. We'll both have problems.}

{130}{}{Hola! How are things?}
{131}{}{Our towns should unite together.}
{132}{}{We are happy to see you.}
{133}{}{My home is your home.}
{134}{}{Peasants should remain around each other.}

{140}{}{How will we survive now?}
{141}{}{Without the Brotherhood, we will be easy pickings for bandits.}
{142}{}{Let Alvaro tell us what to do!}
{143}{}{Down with restrictions on weapons!}
{144}{}{To hell with restrictions in our troubled times.}
{145}{}{We have suffered this persecution long enough! Down with that sort of thing!}
{146}{}{Now WE will rule the town!}
{147}{}{A rifle for every family!}