{100}{}{You see a resident of Casa Nueva.}
{101}{}{You see a local. Compared to the inhabitants of other settlements, he looks quite well-fed and healthy.}

{110}{}{Hi. Where are you from?}
{111}{}{Don't go to the plantation, otherwise they'll take you for a thief.}
{112}{}{Sorry, I have too much work, not up to talking.}
{113}{}{I'll be happy to chat, but I'm not up to it right now.}
{114}{}{Follow the rules if you don't want problems.}

{120}{}{I'll call the others if you don't leave me alone.}
{121}{}{Are you crazy? The night is outside the window!}
{122}{}{Don't wake up the beast in me.}
{123}{}{Go away. Don't make me scream.}
{124}{}{What impudence. Strangers are so ill-mannered...}
{125}{}{Now is not the time to talk. Go away.}
{126}{}{Listen, it's curfew time. We're going to have problems.}

{130}{}{Ola! How are you?}
{131}{}{Our cities should unite.}
{132}{}{You're welcome.}
{133}{}{My home is your home.}
{134}{}{Peasants should stick together.}

{140}{}{How are we going to survive now?}
{141}{}{Without the Brotherhood, we are an easy target for bandits.}
{142}{}{Let Alvaro tell us what to do!}
{143}{}{Down with the prohibition of weapons!}
{144}{}{To hell with prohibitions when this happens.}
{145}{}{We have endured this oppression for a long time. Enough!}
{146}{}{Now WE will rule the city!}
{147}{}{Each family has a rifle!}