{100}{}{You see Nick.}
{101}{}{You see one of Casa Nueva's commoners.}
{102}{}{During the night, we sleep and don't bother others. It's best not to break this rule.}

{200}{}{Hi, I'm Nick. How can I help you?}
{201}{}{Nice to meet you, Nick. Could I ask you a few questions?}
{202}{}{I am not interested in knowing your name. I am, however, interested in knowing something else.}
{203}{}{You can't. I should go.}

{210}{}{How can I help you?}
{211}{}{What do you need from me?}
{212}{}{I should go.}
{213}{}{Could I ask you a few questions?}

{220}{}{Of course.}
{221}{}{Thanks, Nick. Goodbye.}
{222}{}{Sorry, uhh, but you should first speak to the mayor. Otherwise, we'll have problems.}
{223}{}{You serious? Well, alright...}

{230}{}{Who are you?}
{231}{}{My name's Nick, I'm telling you.}
{232}{}{What is it you do here, Nick?}
{233}{}{What could a man with a name like that be doing in a place like this?}
{234}{}{Work, you know. I used to work in a concrete factory, but that place has been closed sometime ago.}
{235}{}{Your industriousness is commendable. Few are ready to devote themselves to their work. But I wanted to ask you about something else.}
{236}{}{Is this all you achieved? Then do something useful - answer a few of my questions.}
{237}{}{I'm sure you have plenty of free time. Could you answer some more of my questions?}

{240}{}{How'd you end up in this town?}
{241}{}{You know, asking about the past is not too accepted here. We're building a new life, one to replace the old one. But if it's that important to you, I came here from Casa Grande. It's a small town located in the direction of Phoenix. I'm sure you already were there?}
{242}{}{Casa Grande, you say? Thanks for the information. And what else can you tell me?}
{243}{}{You too smart for your own good? Of course I know about that place. Now tell me something else.}
{244}{}{Alright. How about some other questions?}
{245}{}{How free are you here? Can you go away if you wanted to?}
{246}{}{Why would one go away from this paradise? There's only desert around, and the big settlements are filled with nothing but suffering. Yes, I lose a part of my freedom. But in exchange I receive shelter and food. First, we must survive and build a new world, and only then start talking about freedom. Such are the times we live in.}
{247}{}{An inspiring speech, Nick. People really do live better lives here than in the rest of Arizona. Can you tell me something else?}
{248}{}{Only the weak don't go against the flow. I hope you are strong enough to at least answer a couple of my questions.}
{249}{}{I understand how you feel. Could I ask you one more question?}
{250}{}{Where is Casa Grande?}
{251}{}{Between the 10th highway that goes from Phoenix to Two Sun. I can mark it on your map.}
{252}{}{Thanks.}