{100}{}{You see Nick.}
{101}{}{You see one of the inhabitants of Casa Nueva.}
{102}{}{At night we sleep and do not interfere with each other. It is better not to break this rule.}

{200}{}{Hi, I'm Nick. How can I help you?}
{201}{}{Nice to meet you, Nick. Can I ask you a few questions?}
{202}{}{I'm not interested in your name. But I need to know something.}
{203}{}{Nothing. I'll go.}

{210}{}{How can I help you?}
{211}{}{What do you need from me?}
{212}{}{I'll go.}
{213}{}{Can I ask you a few questions?}

{220}{}{Of course.}
{221}{}{Thanks, Nick. Goodbye.}
{222}{}{I'm sorry, uh, but you'd better talk to the mayor first. Otherwise, we will have problems.}
{223}{}{Are you serious? Well, okay...}

{230}{}{Who are you?}
{231}{}{My name is Nick, I'm telling you.}
{232}{}{What are you doing here, Nick?}
{233}{}{What can a person with that name do in a place like this?}
{234}{}{I'm working, you know. I used to work at a concrete plant, but the plant has recently been closed.}
{235}{}{Your diligence is commendable. Few are willing to give themselves up to their work. But I wanted to ask something else.}
{236}{}{And that's all you've achieved? Then do at least something valuable - answer me a couple of questions.}
{237}{}{Surely you have plenty of free time. Will you answer a couple more questions?}

{240}{}{How did you end up in this city?}
{241}{}{You know, it's not customary to ask about the past here. We are building a new life to replace the old one. But if that's what you're worried about, I came from Casa Grande. It's a small town on the way to Phoenix. Surely you've been through it?}
{242}{}{Casa Grande, you say? Thanks for the information. What else can you tell me?}
{243}{}{Too smart? Of course, I know about this place. Better tell me something else.}
{244}{}{I see. What about the rest of the questions?}
{245}{}{How free are you here? Can you leave if you want?}
{246}{}{Why leave this paradise? There is only a desert around, and in large settlements, there is nothing but suffering. Yes, I'm losing some of my freedom here. But in exchange, I get Vault and food. First, we have to survive and build a new world, and only after that, we can talk about freedom. Such times.}
{247}{}{Inspiring speech, Nick. Life is really better here than in the rest of Arizona. Will you tell me something else?}
{248}{}{Only weak people don't go against the wind. I hope you have the strength to at least answer a couple of questions.}
{249}{}{I understand you. Let me ask you one more question.}
{250}{}{Casa Grande is where?}
{251}{}{In the middle of the tenth highway between Phoenix and Two-Sun. I can show it on the map.}
{252}{}{Thank you.}