{100}{}{You see a himador.}
{101}{}{You see a a heavily tanned man in a straw hat and a fresh linen shirt.}
{102}{}{Weapons are forbidden in the town. Hide that, quickly.}
{103}{}{Oh, my regards, mister... I, uhh, I need to get back to work... if you'll excuse me...}
{104}{}{Don't talk to me during curfew...}

#First encounter
{200}{}{Hola, senor. My name is Juan. And I haven't seen you before.}
{1200}{}{Hola, senora. My name is Juan. And I haven't seen you before.}
{201}{}{Are you always so unwelcoming when you meet new people?}
{202}{}{Listen, our community is somewhat closed. Everybody knows each other here. I just wanna know what to expect of you, that's all.}
{203}{}{Alright. Sorry.}
{204}{}{You've already shown how you treat outsiders. I don't think I'll stay here.}
{205}{}{Glad to meet you, Juan. I'm }
{206}{}{ of a far-away village to the north.}
{207}{}{A-ah, so you're a peasant as well! Then welcome aboard.}
{1207}{}{A-ah, so you're a peasant as well! Then welcome aboard.}
{208}{}{Thank you. I see kind people live here.}
{209}{}{You would have driven me away otherwise, yeah? How "hospitable" of you.}

#Repeated encounter
{210}{}{Hola. Buenas noches.}
{211}{}{Hola. Buenos dias.}
{212}{}{Adios, hombre.}
{213}{}{I need fiery agave juice.}

{220}{}{Tell me about this town. Who's in charge here?}
{221}{}{You go to mayor Alvaro. He loves to chat with outsiders.}
{222}{}{Thanks, I'll talk to him later.}
{223}{}{Tell me about yourself.}
{224}{}{I'm himador Juan. What else is there to say?}
{225}{}{What is it you do here, himador Juan?}
{226}{}{Process fiery agave and other plants. And while it isn't ripe, I ship goods to caravans and other industries.}
{227}{}{Juan... are you here voluntarily?}
{228}{}{Si, senor. I work as a peoon. I could go at any moment, but there is nowhere to go. I have to follow the rules and fulfill the contract.}
{1228}{}{Si, senora. I work as a peoon. I could go at any moment, but there is nowhere to go. I have to follow the rules and fulfill the contract.}
{229}{}{Alright. Thanks for the answer.}

{230}{}{I want to ask you about the plantations.}
{231}{}{We mainly grow maize and fiery agave. But why has this interested you?}
{232}{}{You know, I'm just curious - what is the "fiery agave"?}
{233}{}{I know of regular agave, but this is the first time I hear about a fiery one. What is it?}
{234}{}{Followers say it's a mutated agave that was grown before the Great War. Since then, plant became bigger, spikier and more poisonous. But there's still useful flesh inside. So we mainly harvest that flesh.}
{235}{}{But in what way is it useful?}
{236}{}{U-uh, amigo, everything here works only thanks to the plant. Flesh and juice - use as food. Stems - as fertilizer and straw. Followers even make cures from agave refuse!}
{237}{}{And where are the plantations located?}
{238}{}{To the east... But I do not recommend you go there. Ma-any won't like it here.}
{239}{}{How interesting. Could I buy a bit of the harvest?}
{240}{}{Actually, there isn't enough harvest for everyone who wants it. That's why I'm forbidden from trading with everyone I see.}
{241}{}{Alright. Thanks for the answer.}
{242}{}{I really need agave juice. Sell it to me, please.}
{243}{}{Sorry, amigo. Can't. If mayor learns who the buyer was, he's probably going to scream at me.}
{244}{}{Fine, forget it.}
{245}{}{Who's in charge here?}
{246}{}{I'm sure you have a small surplus that nobody will notice. And I have a surplus of caps...}
{247}{}{I see you can bargain well. Alright, if you need agave juice, head to me. Though I don't understand why you need it. Do you want to make some tequila or something?}
{248}{}{I'm thinking about it.}
{249}{}{Come on, Juan, it's me. Who treats their friends like this?}

{250}{}{Why are weapons forbidden here?}
{251}{}{One shouldn't break the rules, dear viajero. Those rules written by the front gates, they're written in blood.}
{252}{}{Sorry, that question didn't need to be asked. Forget about this.}
{253}{}{And why are you carrying this strange spear?}
{254}{}{Ah-hah-hah, that's no weapon, it'a a koa. I chop agave leaves with it during harvest. I have mayor's permission. And without permission, you can't openly carry even a koa around here.}
{255}{}{I've never seen anything like that.}
{1255}{}{I've never seen anything like that.}
{256}{}{Mayor asked the tinsmiths to make them. They took part of harvest as payment. Very big part, but back then, without tools, working was very hard. And nobody other than the tismiths can do this sort of thing anymore.}
{257}{}{How familiar. Back in Villa, where I'm from, we also do everything by hand.}
{258}{}{Really? I've never heard of other plantations. You're not lying, are you?}
{259}{}{If you don't believe me, let's change the subject.}
{260}{}{I see. Let's talk about something else.}
{261}{}{First time I saw a tool like that.}
{262}{}{Am I everybody to you or something?}
{263}{}{Why?}
{264}{}{How would you like it if someone walked around your home without permission? And we sometimes catch thieves who try to steal the harvest. Their fate is often tragic.}