{100}{}{Before you Himador.}
{101}{}{You see a very tanned man in a straw hat and a fresh linen shirt.}
{102}{}{Guns are prohibited in the city. Hide it quickly.}
{103}{}{Oh, my respects, sir... I, uh, need to work... if I may...}
{104}{}{Don't talk to me while there's a curfew in town...}

#First meeting
{200}{}{Hola, señor. My name is Juan. But I haven't seen you before.}
{1200}{}{Hola, señora. My name is Juan. But I haven't seen you before.}
{201}{}{Do you always meet new people so unfriendly?}
{202}{}{Listen, we have a semi-closed community here. Everyone knows each other. I just want to understand what to expect from you, and that's it.}
{203}{}{Okay. Sorry.}
{204}{}{You've already shown your attitude towards outsiders. I don't think I'll be here long.}
{205}{}{Nice to meet you, Juan. I }
{206}{}{from a distant village in the north.}
{207}{}{Ah, so you're a peasant too! Then welcome.}
{1207}{}{Ah, so you're a peasant too! Then welcome.}
{208}{}{Thank you. I see good people live here.}
{209}{}{Otherwise, you would have sent me away, right? You're so "hospitable."}

#Repeat meeting
{210}{}{Hola. Buenas noches.}
{211}{}{Hola. Buenos dias.}
{212}{}{Adios, hombre.}
{213}{}{I need fire agave juice.}

{220}{}{Tell me about this city. Who's in charge here?}
{221}{}{You need to see Mayor Alvaro. He likes to chat with strangers.}
{222}{}{Thanks, I'll talk to him later.}
{223}{}{Tell me about yourself.}
{224}{}{I'm Himador Juan. What else can I tell you?}
{225}{}{What are you doing here, Himador Juan?}
{226}{}{I process fire agave and other crops. And while he is still not in time, I am engaged in shipping goods to caravans and other household.}
{227}{}{Juan, tell me... are you here of your own free will?}
{228}{}{Si, señor. I work as a peon. I could have left at any moment, but there's nowhere to go. We have to live by the rules and work out the contract.}
{1228}{}{Si, señora. I work as a peon. I could have left at any moment, but there's nowhere to go. We have to live by the rules and work out the contract.}
{229}{}{I see. Thanks for the answer.}

{230}{}{I want to ask you about the plantations.}
{231}{}{We mainly grow maize and fire agave. But why are you suddenly interested in this?}
{232}{}{Yes, just curious - what else is a "fiery agave"?}
{233}{}{I know about the usual agave, but this is the first time I hear about the fiery one. What is it?}
{234}{}{Followers say it's a mutated agave that was grown before the Great War. Since then, the plant has become bigger, more poisonous and needle-like. But there is still a useful pulp inside. That's what we get mainly.}
{235}{}{But what's the use of this plant?}
{236}{}{Uh, amigo, everything comes from the plant. Pulp and juice - for food. And the stems are for fertilizer and straw. Followers even make medicines from agave pomace!}
{237}{}{And where are the plantations?}
{238}{}{In the east... But I do not advise you to go there. Many of us won't like it.}
{239}{}{How interesting. Can I buy some crops?}
{240}{}{Actually, there is not enough harvest for everyone. Therefore, I am forbidden to trade with everyone in a row.}
{241}{}{I see. Thanks for the answer.}
{242}{}{I really need agave juice. Sell, please.}
{243}{}{Sorry, amigo. Can't. If the mayor finds out who the buyer is, he'll probably yell at me.}
{244}{}{Okay, forget it.}
{245}{}{And who's in charge here?}
{246}{}{You probably have a surplus that no one will notice. And I have extra caps...}
{247}{}{I see you know how to bargain. Okay, if you need agave juice, contact us. Although I don't understand why you need it. Do you really want to make tequila?}
{248}{}{I'm thinking about it.}
{249}{}{Come on, Juan, it's me. Is that the way to treat friends?}

{250}{}{Why are weapons prohibited here?}
{251}{}{Don't go against the rules, dear viajero. These prohibitions at the front gate are written in blood.}
{252}{}{Sorry, that was an unnecessary question. Forget about it.}
{253}{}{Why are you carrying this strange spear?}
{254}{}{A-ha-ha, it's not a weapon, it's a koa. I chop agave leaves with them when I harvest. And I have permission from the mayor for this. And if there is no permission, then even the koa cannot be worn openly.}
{255}{}{I've never seen anything like it.}
{1255}{}{I've never seen anything like it.}
{256}{}{The mayor was making an order from the tinsmiths. They then took payment with the harvest. It is very expensive, but without tools we will have a hard time working. And besides tinsmiths, no one else can do it.}
{257}{}{How familiar. At our Villa, we also have to do everything manually.}
{258}{}{Really? I've never heard of other plantations. Aren't you lying?}
{259}{}{If you don't believe me, let's change the subject.}
{260}{}{Now it's clear. Let's talk about something else?}
{261}{}{This is the first time I've seen such a tool.}
{262}{}{Is it me "all in a row"?}
{263}{}{Why?}
{264}{}{Would you like it if someone walked around your house without asking? Besides, sometimes we catch crop robbers. Usually their fate is deplorable.}