{100}{}{You see mayor Alvaro.}
{101}{}{You see a puny-looking mexican with a thin mustache and an apologetic look.}
{102}{}{Put that away immediately. No weapons while you're in the town.}
{103}{}{This is a quiet settlement. No need to walk around in that thing and scare peaceful citizens.}
{104}{}{Did something happen? Then get back to your bed immediately! There's curfew in the town at night.}
{105}{}{They're demanding that I make decisions. But what can I actually do? I only signed papers for the Brotherhood!}

#First encounter
{200}{}{Oh, a new face in town! A very pleasant surprise... Welcome. I suppose I could be called the mayor of this city. And as for my name, it's Alvaro.}
{201}{}{Hello, mayor.}
{202}{}{Hm. You don't want to say your name? Well, I won't insist. You must have your own reasons for that.}
{203}{}{That is correct.}
{204}{}{I'm }
{205}{}{. Very nice to meet you, senor Alvaro.}
{206}{}{Good manners? I think you and I will get along just fine.}
{207}{}{Thank you for your warm welcome.}
{208}{}{What is this sad sight, mayor? You call this a city?}
{209}{}{Uhh, yes, I admit that it's not as big as Phoenix or it's surroundings. And yes, I did not see anything else in my life other than the Sonora desert. But look around - isn't this perfect?}
{210}{}{Maybe.}
{211}{}{This place is terrible - no civilization whatsoever.}
{212}{}{Can you tell me where you're heading?}
{213}{}{I dunno. I'm just walking.}
{214}{}{Well, fine, I'll believe you. It really is none of my business.}
{215}{}{Thanks for the understanding.}
{216}{}{Damn right.}
{217}{}{You can stay in our town for some time. But only if you follow the rules. You aren't going to cause trouble, are you?}
{218}{}{Of course. Thanks for the offer.}
{219}{}{I don't bite if I'm not disturbed. Keep that in mind.}
{220}{}{I serve the Brotherhood of Steel. Here is my badge.}
{221}{}{Oh, welcome! I didn't recognize you... Uhh... We're always happy to see our defenders. Make yourself at home.}
{222}{}{Thank you.}
{223}{}{If only you behaved like that from the start.}
{224}{}{I'm heading to Puerto. I have business there.}
{225}{}{How unexpected. Usually only caravans go there by their own accord. But if you don't want to tell me, I won't insist.}
{226}{}{Thanks for your understanding.}
{227}{}{Very good. As they say, silence is worth more than a bag of maize.}
{228}{}{None of your business.}
{229}{}{Well, let's assume it really is none of my business. But you shouldn't be rude to us. We're a peaceful settlement, after all.}
{230}{}{Sorry, I'm really tired after such a long way...}
{231}{}{You don't want conflict - then don't start it. Got it?}
{232}{}{I'm glad we had this conversation. But sorry, right now I have tons of paperwork to do.}
{233}{}{See you later.}
{234}{}{We have the same names? An interesting coincidence. We'll surely get along well.}

{239}{}{So, the town is doomed. Flee before the crowd overthrows you... "mayor".}
{240}{}{(clutching his head with his hands, the mayor sits at the table and does not pay attention to anything happening around him) E-e-eh...}
{241}{}{You don't look particularly happy. What happened?}
{242}{}{It's over... We managed to survive up to this point thanks to the Brotherhood of Steel. But recently, a messenger brought bad news...}
{243}{}{Yes, I know - the Brotherhood is destroyed. Probably some explosion in the ammunition depot.}
{244}{}{And what are we supposed to do now? Who will protect us? Who will tell us what to do?}
{245}{}{What about the Followers?}
{246}{}{They aren't warriors, and there are far too few of them to solve so many problems. There is no hope... It's over... it's all over...}
{247}{}{Hey, Alvaro, bring yourself together! You're the mayor, after all. Everything is now in your hands. You're free from total control and persecution. Isn't *that* perfect?}
{248}{}{Yes... of course... But can I really even be called a mayor? I just did paperwork under the oversight of people from the order. Now, we're going to have to survive, and do it all by ourselves. It will not be easy.}
{249}{}{It'll work out. I believe in you.}

#Repeated encounter
{250}{}{Sorry, I have too much paperwork at the moment.}
{251}{}{Goodbye.}
{252}{}{How can I help you, my dear friend?}
{253}{}{Greetings to our new hero. How can I help you?}
{1253}{}{Greetings to our new heroine. How can I help you?}

{260}{}{They say people are going missing in this settlement. Is this true?}
{261}{}{Who does?}
{262}{}{I won't tell you.}
{263}{}{No, it's not true. Nobody goes missing here! If you don't count a few criminals that fled by their own accord when the town was being built.}
{264}{}{Alright.}
{265}{}{I very much hope you aren't going to spread this misinformation any further.}
{266}{}{Of course. No problem.}
{267}{}{I will do so only if I find out you're lying. Adios, mister mayor.}
{268}{}{It's Rosalia. She's telling me that you're forbidding her from searching for her husband.}
{269}{}{What nonsense! I'm not forbidding her from searching, let her search as much as she pleases. But she just can't find him because her husband fled from the town. Probably because he couldn't tolerate her grumpiness.}
{270}{}{Alright.}
{271}{}{Don't mind her - the old witch is going mad.}

{280}{}{Could you please tell me about the town?}
{281}{}{This is a peaceful peasant community. Half of the people work on the plantations, the rest do other peaceful activities. Look, the Followers even have their own school.}
{282}{}{Thanks for your answer.}
{283}{}{What do you grow here?}
{284}{}{Mainly maize and the fiery agave. Without the plantations, the town wouldn't exist.}
{285}{}{So you trade with other towns?}
{286}{}{The harvest is only enough to fulfill our own needs and to supply nearby settlements. There is also a caravan that arrives from Phoenix like clockwork to buy the agave juice.}
{287}{}{By the way, what are the settlements that are nearby?}
{288}{}{Alright.}
{289}{}{Puerto is to the west and Two Sun is to the east. That's all, really, if you don't count a few small villages and outposts, but those are mostly seasonal.}
{290}{}{Thanks.}
{291}{}{A true oasis among the desert. How did it become possible?}
{292}{}{We can thank the Followers of the Apocalypse for their knowledge and kindness. In their laboratories, they made new kinds of plants that can grow well even in the dry desert.}
{293}{}{Do other towns also buy your harvest?}
{294}{}{Who are those Followers?}
{295}{}{By the way, who are those Followers?}
{296}{}{The Followers of the Apocalypse... A strange name, but we got used to it. They conduct research, teach children, heal illnesses. And that's not to mention the fact that it was thanks to their experiments that plantations became possible among the desert. But it would be easier for you to ask the Followers themselves.}
{297}{}{I also know about some other group of followers - The Followers of the Holy Fire. Their base of operations is in Phoenix.}
{298}{}{I heard some things about them, but our paths never crossed. If you don't count the caravans that come from Phoenix.}
{299}{}{By the way, why is alcohol forbidden here?}
{300}{}{Why is alcohol forbidden here?}
{301}{}{Officially, only strong alcohol is forbidden here. We have too much work to do to spend time on entertainment. Though after the harvest, peasants do get a couple of days of full freedom.}
{302}{}{It's interesting that you don't have guards. Aren't you afraid of slavers or bandits?}
{303}{}{Speaking of the "peaceful community" you said this place is. Aren't you afraid of slavers or bandits?}
{304}{}{Why should we be afraid of them? Our benefactors ensure order in these lands. We're peaceful people and are involved in purely peaceful activities. We're even forbidden from having weaponry. That's why there's nothing to fear here.}
{305}{}{Yes, it's a true oasis you have here. How did it become possible?}
{306}{}{Benefactors? Who are they?}
{307}{}{You don't know about the Puerto military base? Then I shouldn't discuss this with you. Just be aware that there is someone who will stand up for us.}
{308}{}{You know who I'm talking about - the Brotherhood of Steel. They now have direct control over these lands.}

{310}{}{What do you think about the Brotherhood of Steel?}
{311}{}{They are our benefactors. Without them, we wouldn't be able to survive.}
{312}{}{Got it.}
{313}{}{And what if you were to be honest?}
{314}{}{I am already being honest.}
{315}{}{That's good.}
{316}{}{Alright - I'll believe you.}
{317}{}{You don't sound particularly happy or excited.}
{318}{}{It's not exactly as rosy as one might think. We don't talk about it much, but everyone here is mainly a peon. Effectively - slaves for life. After all, you need to pay unaffordably high taxes to receive protection and a place to live.}
{319}{}{Go on...}
{320}{}{Because they don't have so much money, the people enter peonage, effectively renting themselves out for the rest of their life.}
{321}{}{That's sad.}
{322}{}{Q.E.D.}
{323}{}{But really, even then, it's worth it. We're given freedom in everything that doesn't go against the law and the interests of the Brotherhood of Steel. And we really do get very strong defense and a lot of help. After all, the Brotherhood needs products and trade routes. And they wouldn't have those without us.}
{324}{}{You're okay with this state of affairs?}
{325}{}{You say that as if we have a choice! It was only with the help of the Brotherhood and the tinsmiths that we were able to build such a perfect city and have such bountiful harvests. Without them, we would be living out a pathetic life of scavenging in the desert.}
{326}{}{Those truly are difficult conditions. I don't know what I would choose in this situation.}
{327}{}{I struggle to see how one could think exchanging their freedom to live as cattle is a good idea. You've clearly made a grave mistake. Farewell.}
{328}{}{I know about all about your dirty little secret, the disease. And the pressure on the citizens, and the dozens of rules. If the Brotherhood is not involved, isn't this tyranny all your fault?}
{329}{}{If you can't become a deathclaw, pretend to be a blind pigrat. That what you wanted to say, weakling?}

{330}{}{Do you know that your son's pet is dying?}
{331}{}{Yes... That pigrat has completely pissed me off with it's whining and noise-making during the night. I told Chip that he shouldn't keep an animal in the house, but he doesn't listen to me. Now I need to put up with that and deal with the neighbors' complaints.}
{332}{}{How did Pinky wrong you all?}
{333}{}{Well.. uhh, to be honest, he hasn't, aside from the noises he makes at night. It's just that his appearance scares people. And that's enough. If he was of some help, maybe we would view him differently.}
{334}{}{An interesting observation.}

{340}{}{The Santa Ana settlement wishes to start trading with you.}
{341}{}{Santa Ana? I haven't heard that name in a long time. The villagers avoided any and all contact with us. What changed?}
{342}{}{Let's just say it is controlled by a new order now.}
{343}{}{Ooh, that sounds intriguing. I will ready a caravan. Perhaps we'll find new workers in Santa Ana, since we often lack them. Thanks for the information.}
{344}{}{You're welcome.}