{100}{}{Here is Mayor Alvaro.}
{101}{}{You see a puny-looking Mexican with a thin mustache and an apologetic look.}
{102}{}{Hide it immediately. No weapons while you're in town.}
{103}{}{We have a quiet settlement. It's not worth walking around here in this thing and scaring civilians.}
{104}{}{Did something happen? Then get back to bed immediately! There is a curfew in the city at night.}
{105}{}{They demand solutions from me. What can I do? I was just signing papers for the Brotherhood!}

#First meeting
{200}{}{Oh, a new face in town! What a pleasant surprise... Greetings to you. I am, one might say, the mayor of this city. And my name is Alvaro.}
{201}{}{Hello, Mayor.}
{202}{}{Hmm. Don't you want to tell me your name? I won't insist. Surely you have a reason for that.}
{203}{}{Yes, that's right.}
{204}{}{I }
{205}{}{. Very nice, senor Alvaro.}
{206}{}{Good manners? Then you and I will meet.}
{207}{}{Thank you for the warm welcome.}
{208}{}{What a pathetic sight, Mayor? And this, in your opinion, is a city?}
{209}{}{Uh, yes, I realize that it's not as big as Phoenix or its outskirts. And besides the Sonoran desert, I've never seen anything in my life. But look - isn't it beautiful here?}
{210}{}{Maybe.}
{211}{}{It's just terrible here - there is no civilization.}
{212}{}{May I know where you're going?}
{213}{}{I don't know. I'm going wherever my eyes look.}
{214}{}{Well, okay, I'll take your word for it. It's really none of my business.}
{215}{}{Thank you for understanding.}
{216}{}{Exactly.}
{217}{}{You can count on an overnight stay in our city. But subject to the rules. You're not going to make trouble for us, are you?}
{218}{}{Of course. Thanks for the offer.}
{219}{}{I don't bite until I'm disturbed. Keep in mind.}
{220}{}{I serve the Brotherhood of Steel. Here's my badge.}
{221}{}{Oh, welcome! Did not recognize... er... we are always glad to have our defenders. Make yourself as comfortable as you like.}
{222}{}{Thank you.}
{223}{}{That would be right away.}
{224}{}{I'm heading to Puerto. I have business there.}
{225}{}{What a surprise. Usually only caravans go in that direction without permission. But if you don't want to talk, I can't insist.}
{226}{}{Thank you for understanding.}
{227}{}{That's good. As they say, silence is more expensive than a bag of corn.}
{228}{}{It's none of your business.}
{229}{}{Well, let's assume that it's really none of my business. But don't be rude to us, because we are a peaceful settlement.}
{230}{}{Sorry, it was in a hurry - just fatigue from the road...}
{231}{}{If you don't want a conflict, don't start it yourself. Got it?}
{232}{}{I was glad to chat. But I'm sorry, I have a lot of paperwork right now.}
{233}{}{See you again.}
{234}{}{Do we have the same names? Funny coincidence. Then you and I will surely meet.}

{239}{}{So your town will come to an end. Run away from here before the crowd overthrows you, the mayor is a loser.}
{240}{}{(clutching his head with his hands, the mayor sits at the table and does not pay attention to others) Eh...}
{241}{}{You look like shit. Did something happen?}
{242}{}{Everything is gone... We used to survive thanks to the Brotherhood of Steel. And recently a messenger came with bad news...}
{243}{}{Yes, I know - the Brotherhood has been destaroyed. Probably an explosion at the ammunition depot.}
{244}{}{What should we do now? Who will protect us? Who will give us instructions?}
{245}{}{What about the Followers?}
{246}{}{They are not warriors and there are very few of them to solve so many issues. It's hopeless... Everything is gone... it's all gone...}
{247}{}{Hey, Alvaro, get it together! You're the mayor. Everything is in your hands now. You are free from total control and oppression. Isn't that wonderful?}
{248}{}{Yes... of course... But what kind of mayor am I? I was just doing paperwork under the supervision of people from the order. Now we have to survive on our own. It won't be easy.}
{249}{}{You will succeed. I believe in you.}

#Repeat meeting
{250}{}{Sorry, I have a lot of paperwork right now.}
{251}{}{Goodbye.}
{252}{}{How can I help, dear friend?}
{253}{}{Hello, our new hero. How can I help you?}
{1253}{}{Hello, our new heroine. How can I help you?}

{260}{}{They say people are disappearing from you. Is it true?}
{261}{}{Who's talking?}
{262}{}{I won't say.}
{263}{}{Ah, of course, no one disappears from us! Except for some criminals who escaped themselves during the construction of the city.}
{264}{}{I see.}
{265}{}{I really hope that you will not spread these dirty false rumors further.}
{266}{}{Sure. No problem.}
{267}{}{Only until it turns out that you're lying. Adios, Mr. Mayor.}
{268}{}{This is Rosalia. She says you forbid looking for her husband.}
{269}{}{What nonsense! I do not forbid the search, let him search. But she can't find it because her hubby just ran away from town. Surely her grumpy nature could not stand it.}
{270}{}{I see.}
{271}{}{Nevermind- the old witch is going crazy.}

{280}{}{Tell me, please, about the city?}
{281}{}{We have a peaceful peasant community. Half of the people work on plantations, the resta - various peaceful affairs. There, the Followers even have their own school.}
{282}{}{Thanks for the reply.}
{283}{}{What is grown here?}
{284}{}{These are mainly maize and fire agave. The whole city lives on these plantations.}
{285}{}{So do you trade with other cities?}
{286}{}{The harvesta is enough only for their own needs and for the nearesta settlements. We also have a stable caravan coming from Phoenix for agave juice.}
{287}{}{By the way, what settlements are there around?}
{288}{}{I see.}
{289}{}{Puerto in the westa and Tu San in the east. This is all, except for a few small villages and outposts, but they are mostly seasonal.}
{290}{}{Thank you.}
{291}{}{A real oasis in the middle of the desert. How did this become possible?}
{292}{}{We thank the Followers of the Apocalypse for their intelligence and kindness. It was they who brought out in their laboratory varieties of plants that can take root in a dry desert.}
{293}{}{Do other cities also buy your crops?}
{294}{}{Who are the Followers?}
{295}{}{By the way, who are these Followers?}
{296}{}{Followers of the Apocalypse... It's a strange name, but we're already used to it. They conduct scientific research, teach children, treat diseases. Needless to say, the plantation itself appeared in the middle of the desert thanks to their experiments. But it's easier for you to ask the Followers themselves.}
{297}{}{I know about some other followers - Followers of Fire in Phoenix.}
{298}{}{I heard something about them, but we never crossed paths. Except for the caravans that come from Phoenix.}
{299}{}{By the way, why is alcohol banned here?}
{300}{}{Why is alcohol banned here?}
{301}{}{Formally, only strong alcohol is prohibited. We have too much work to waste time on entertainment. However, after the harvesta, the peasants get a couple of days of complete freedom.}
{302}{}{Curiously, there are no guards here. Are you not afraid of slavers or bandits?}
{303}{}{About the "peaceful community". Are you not afraid of slavers or bandits?}
{304}{}{Why should we be afraid of them? Our patrons keep order in these lands. We are peaceful people and do only peaceful things. We are not even allowed to have weapons. Therefore, there is nothing to be afraid of here.}
{305}{}{Yes, you have a real oasis here. How did this become possible?}
{306}{}{Patrons? Who is it?}
{307}{}{What, you don't know about the military base in Puerto? Then I shouldn't discuss it with you. Just know that there is someone to stand up for us.}
{308}{}{You know who we're talking about-the Brotherhood of Steel. They are now the owners of these lands.}

{310}{}{How do you feel about the Brotherhood of Steel?}
{311}{}{They are our patrons. We wouldn't have survived without them.}
{312}{}{I see.}
{313}{}{And to be honesta?}
{314}{}{This is the honesta answer.}
{315}{}{That's good.}
{316}{}{So be it - I'll believe it.}
{317}{}{I do not hear joy and admiration in your words.}
{318}{}{I can talk to you frankly, right? We try not to talk about it, but everyone here lives by and large on the rights of peons. That is, lifelong slaves. After all, in order to obtain protection and a place of residence, you need to pay unaffordable taxes.}
{319}{}{So, go on...}
{320}{}{Due to the lack of so many funds, residents conclude a peonage contract, in fact, renting themselves out for the resta of their lives.}
{321}{}{It's sad to hear that.}
{322}{}{Which was required to be proved.}
{323}{}{But it's not that bad. We are given free rein in everything that does not contradict the laws and interestas of the Brotherhood of Steel. And we really get reliable protection and help. After all, the Brotherhood needs products and a trade route. And without us, none of this will happen.}
{324}{}{And are you ready to put up with this situation?}
{325}{}{We have no choice! It is thanks to the Brotherhood and the tinsmiths that we have built such a beautiful city and grown such a harvesta. Without them, we would have dragged out a miserable life of scavengers in the desert.}
{326}{}{And it's true - difficult conditions. I don't know what I would have to choose in such a situation.}
{327}{}{It's hard for me to understand how freedom can be exchanged for a life in a stall. You clearly made a mistake. Goodbye.}
{328}{}{I know your secret about the infection and its silencing. And also - pressure on residents and continuous bans. Isn't it your tyranny if the Brotherhood has nothing to do with it?}
{329}{}{If you can't become a death claw, pretend to be a blind pig-rat. Is that what you mean, weakling?}

{330}{}{Do you know that your son's pet is dying?}
{331}{}{Yes... This pig-rat has already bored me with his whining and night fuss. I told Chip not to keep the beast in the house, but he won't listen to me. Now we have to put up with and fend off the attacks of neighbors.}
{332}{}{What did Pinkie do to all of you?}
{333}{}{Well.. uh, to be honesta, nothing in particular, except for the night noises. He scares just by his appearance. And that's enough. If he had been useful, perhaps the attitude towards Pinkie would have changed.}
{334}{}{An interestaing observation.}

{340}{}{In the settlement of Santa Ana, they want to start trading with you.}
{341}{}{Santa Ana? I haven't heard of this village for many years. Its inhabitants avoided all contact with us. What has changed there?}
{342}{}{Well, let's just say that the government has changed there.}
{343}{}{Oh, that sounds intriguing. I'll prepare the caravan. Perhaps we will recruit new workers among the residents of Santa Ana, which are sometimes so lacking. Thank you for the message.}
{344}{}{Please.}