{100}{}{in front of you are the pins.}
{101}{}{you see... a tame pig-rat. from so unexpected!}
{102}{}{si!}
{103}{}{si-pi!}
{104}{}{pinkie died suddenly.}
{105}{}{si-i-i...}
{106}{}{Ôr-r-r...}
{107}{}{si-pi-pi!}

{200}{}{si!}
{201}{}{Yes, and "pi" for you.}
{202}{}{search for me here.}
{203}{}{Hey, pinkie, follow me.}
{204}{}{si! Si!}
{205}{}{Õoroshie pinkie.}
{206}{}{Ædi here, pinkie.}
{207}{}{Return home, pinkie.}