{100}{}{You see Pinky.}
{101}{}{You see... a pet pigrat. How unexpected!}
{102}{}{Squeak!}
{103}{}{Squeak-squeak!}
{104}{}{Pinky's existence has unexpectedly ended.}
{105}{}{Sque-e-eak...}
{106}{}{Fr-r-r...}
{107}{}{Squeak-squeak-squeak!}

{200}{}{Squeak!}
{201}{}{Yeah, yeah, "squeak" to you too.}
{202}{}{Don't you squeak at me.}
{203}{}{Hey, Pinky, come with me.}
{204}{}{Squeak! Squeak!}
{205}{}{Good Pinky.}
{206}{}{Wait here, Pinky.}
{207}{}{Go home, Pinky.}