{100}{}{You see Lo the peasant.}
{101}{}{You see an elderly peasant woman with weary hands. She kneads her back with a crunch.}
{102}{}{I'll call for help if you don't leave immediately.}

{210}{}{What do you need?}
{211}{}{What do you want?}
{212}{}{Who are you?}
{213}{}{I don't trade, sorry.}
{214}{}{You better go talk to the mayor. We're just workers.}
{215}{}{Looks like you got the wrong door.}

{220}{}{Happy to see you.}
{221}{}{Have you settled down in your new place yet?}
{222}{}{What do you want to talk about?}
{223}{}{Hola! It's great that you're still here.}
{224}{}{We are all very grateful to you for the help you offered.}

{229}{}{Bye.}

{230}{}{Who are you?}
{231}{}{My name is Lo.}
{232}{}{What do you do, Lo?}
{233}{}{I work. On the plantations, for instance.}
{234}{}{Must be hard?}
{235}{}{Work is always harder than lying in an ambush on the caravan routes. Right? Oh, sorry, I thought you were one of "them"...}
{236}{}{I'll be offended the next time.}
{237}{}{It's okay. I understand your mistrust for the outsider.}

{240}{}{What is life like here?}
{241}{}{Great! This is the best place in the wastes. Of course, in exchange for protection and food we do have to work a lot. But it's only fair. Thank the Followers and thank mayor Alvaro!}
{242}{}{It's good that your lives are good.}
{243}{}{Now what if you answered honestly?}
{244}{}{I'm telling you - there is no place better than Casa Nueva. Those who don't like it here don't stay for long.}
{245}{}{Alright. I'll believe you. This time}
{246}{}{That's great. Good luck.}
{247}{}{I think you're exaggerating. After all I've seen it feels like you're living like slaves here.}
{248}{}{Wait a minute... (looks around) I shouldn't be telling you this... There really are many rules here. Many, many rules. Some can't put up with the pressure. We're forbidden from even discussing the resulting situation.}
{249}{}{Then why aren't you fighting for your rights?}
{250}{}{Because we don't have any. We're just life-long peons, almost slaves... Any and all insolence here is strongly punished. Riots are a direct path to the afterlife. Let's stop this conversation here. One shouldn't touch the sleeping beast.}
{251}{}{I see, I see...}
{252}{}{Wait... Hm. I *can* speak openly with our hero, right?}
{1252}{}{Wait... Hm. I *can* speak openly with our heroine, right?}
{253}{}{Of course. What's on your mind?}
{254}{}{Well, depends on what it is you want to say.}
{255}{}{All this time, deep down, I doubted that this place would exist for long. So I kept some bullets just in case I change my mind and decide to escape.}
{256}{}{Go on.}
{257}{}{And?}
{258}{}{I suppose I should forget about the past, for the future is much better. Here, take these bullets. You need them more than I do.}
{259}{}{Thanks. They really will come in handy.}
{260}{}{If it's so important, then I'll take them.}