{100}{}{Here is a peasant woman Lo.}
{101}{}{You see an elderly peasant woman with overworked hands. She crunches her back.}
{102}{}{I'll call for help if you don't leave now.}

{210}{}{What do you need?}
{211}{}{What do you want?}
{212}{}{Who are you?}
{213}{}{I don't sell anything, sorry.}
{214}{}{You'd better talk to the mayor. We're just workers.}
{215}{}{It seems you have the wrong door.}

{220}{}{Nice to see you.}
{221}{}{Well, have you settled in a new place?}
{222}{}{What do you want to talk about?}
{223}{}{Hola! It's great that you're still here.}
{224}{}{We are all grateful to you for your help.}

{229}{}{Bye.}

{230}{}{Who are you?}
{231}{}{My name is Lo.}
{232}{}{What are you doing, Lo?}
{233}{}{I'm working. On plantations, for example.}
{234}{}{Must be hard?}
{235}{}{Work is always harder than sitting in ambush on caravan routes. Isn't it? Oh, sorry, I thought you were one of those...}
{236}{}{I'll be offended next time.}
{237}{}{Nothing. I understand your distrust of an outsider.}

{240}{}{How are you living here?}
{241}{}{Just wonderful! This is the best place on the wastelands. Of course, in exchange for protection and food, you have to work a lot. But it's fair. Thanks to the Followers and Mayor Alvaro!}
{242}{}{It's good that you're doing well.}
{243}{}{And to be honest?}
{244}{}{I'm telling you, there's no place like Casa Nueva. And those who don't like it - they don't stay here for a long time.}
{245}{}{Okay. I'll believe it this time.}
{246}{}{It's good. Good luck to you.}
{247}{}{I think you're exaggerating. After all that you have seen, it seems that you are here in slave conditions.}
{248}{}{Wait... (looks around) You shouldn't talk about it... There really are a lot of prohibitions and requirements. Some can't stand it. We are forbidden even to discuss the established order.}
{249}{}{Why don't you fight for your rights?}
{250}{}{Because we don't have them. We are just peasants with lifelong peonage, almost slaves... Any insolence is strictly punished here, and riots are a direct road to the next world. Let's leave it at that. Do not provoke the beast while he sleeps.}
{251}{}{Everything is clear with you...}
{252}{}{Wait... hmm. I can speak frankly with our hero, right?}
{1252}{}{Wait... hmm. Can I speak frankly with our heroine?}
{253}{}{Sure. Tell me what's on your mind?}
{254}{}{Well, it depends on what it's about.}
{255}{}{All this time, in the depths of my soul, I doubted the relative nature of this place and how long it would last. That's why I kept some bullets with me in case I changed my mind and wanted to escape from here.}
{256}{}{Go on.}
{257}{}{So?}
{258}{}{Perhaps I should forget about the past, because the future is much more beautiful. Here, take these cartridges, you need them more.}
{259}{}{Thank you. This will really come in handy.}
{260}{}{If it's so important, then I'll take them.}