{100}{}{You see Rosalia.}
{101}{}{You see a woman in tidy peasant clothes.}
{102}{}{Hello, stranger. Any news from the wastes?}
{1102}{}{Hello, stranger. Any news from the wastes?}
{103}{}{Bastards! They're keeping me locked in so that I won't say anything and so that the others stop trusting me.}

#First encounter
{200}{}{Hey, stranger... Uhh, hi. This is your first time here, right?}
{1200}{}{Hey, stranger... Uhh, hi. This is your first time here, right?}
{201}{}{Why do you ask?}
{202}{}{Well, I wanted to talk to you... alone, if you don't mind.}
{203}{}{Of course. Why not?}
{204}{}{Sounds suspicious. What do you want from me?}
{205}{}{It's important. Let's meet beyond the city gates, where nobody can eavesdrop on us, okay?}
{206}{}{Okay. We'll meet by the billboard.}
{207}{}{Okay, but don't even think of fooling me.}
{208}{}{Would you kindly fuck off?}

{210}{}{Thank you for coming here. Are you sure you aren't being followed?}
{1210}{}{Thank you for coming here. Are you sure you aren't being followed?}
{211}{}{What do you want?}
{212}{}{You see... My husband went missing lately. He went to the plantations and never came back. I searched for him, but couldn't find any trace of him. I need your help!}
{213}{}{Why such caution?}
{214}{}{I'm forbidden from speaking about this! To not cause panic - that's what the mayor said. It's a conspiracy and they're all in it! Hiding something.}
{215}{}{What about the others? Why isn't the whole village looking for him?}
{216}{}{This place isn't as perfect as it seems. We're being forced to keep quiet, but believe me - this isn't the first time a person went missing.}
{217}{}{Forced? How?}
{218}{}{There are very strict rules here. On the outside, the town looks prosperous, but in reality we pay for that with our freedom. Any dissenters are punished or thrown out.}
{219}{}{Alright. I'll go find him. How does he look?}
{220}{}{Dark skin, not too tall, has a mustache... Ah yes, he also had a marriage pendant. The mayor gives them to everyone who gets married in our city.}
{221}{}{Don't worry, I'll look for him.}
{222}{}{I can't promise anything.}
{223}{}{The situation's uncertain and looks dangerous. I'll take a look, but I expect compensation.}
{224}{}{Of course. I'll get you some food and give you all my caps - I don't have anything left anyway.}
{225}{}{Please, find my husband! I have nobody else to turn to!}
{226}{}{It's fine, calm down.}

{230}{}{How are you? Personally, I'm not too well, as you can see.}
{231}{}{So? Did you manage to find him?}
{232}{}{Not yet.}
{233}{}{I see. Bye.}

{240}{}{I don't believe you introduced yourself to me. Who are you?}
{241}{}{Ah, sorry. My name is Rosalia. I'm responsible for crop processing.}
{242}{}{I should go, Rosalia.}
{243}{}{They say you had arguments with your husband?}
{244}{}{Of course we had arguments! After all, we didn't marry out of love. The mayor wants there to be more marriages and gives us some priveleges. But in the couple of years I was with my husband, we got used to each other...}
{245}{}{Alright...}
{246}{}{Wait, who told you this? I hope you didn't discuss this with mayor Alvaro. He can't be trusted! You hear me? Don't even think of mentioning the missing people to him.}
{1246}{}{Wait, who told you this? I hope you didn't discuss this with mayor Alvaro. He can't be trusted! You hear me? Don't even think of mentioning the missing people to him.}
{247}{}{Alright, calm down...}

{250}{}{Your husband died. I'm very sorry.}
{251}{}{Was your husband green and ugly? Then you should know that he's completely withered and is lying on the floor of the barn near the plantations.}
{252}{}{I didn't have any doubts remaining on that part. He was murdered, yes? Yes? Tell me the truth!}
{253}{}{Strange things happened to him. It looked like a disease. You really should go and take a look yourself.}
{254}{}{What in the world... We knew that some insects carried infection, but for the disease to spread across the body LIKE THAT?}
{255}{}{So this isn't the first time?}
{256}{}{It's all the fault of the Followers. They with their science experiments, they killed him! And not just him! Monsters!}
{257}{}{The Followers of the Apocalypse? What experiments?}
{258}{}{They have a laboratory out in the desert. But we're forbidden from even going close to it... Agh, those damned scientists! They gave us a bountiful harvest alright, but took our souls.}
{259}{}{[Remain silent]}
{260}{}{You have a kind heart, senor. God bless you. Stay away from those scientists.}
{1260}{}{You have a kind heart, senora. God bless you. Stay away from those scientists.}
{261}{}{Don't despair, Rosalia. Goodbye.}
{262}{}{I still think I should talk to them about this. Goodbye.}
{263}{}{My job here is done. What about payment?}
{264}{}{What do you want? Caps? Here! Take them all and leave me alone! You materialistic outsiders only think about yourselves...}
{265}{}{No need to be all worked up, lady.}