{100}{}{Here is Rosalia.}
{101}{}{You see a woman in well-groomed peasant clothes.}
{102}{}{Hello, stranger. What news from the wastelands?}
{1102}{}{Hello, stranger. What news from the wastelands?}
{103}{}{Bastards! They keep me locked up so that I don't stir up too much and so that others stop trusting me.}

#First meeting
{200}{}{Hey, stranger... Uh, hi. It's your first time here, right?}
{1200}{}{Hey, stranger... Uh, hi. It's your first time here, right?}
{201}{}{Why are you asking?}
{202}{}{Well, I'd like to talk to you... in private, if you don't mind.}
{203}{}{Sure. Why not?}
{204}{}{Sounds doubtful. What do you want from me?}
{205}{}{It is important. Let's meet outside the city gates, where no one will overhear us, okay?}
{206}{}{Okay. Meet me at the billboard.}
{207}{}{Okay, but don't even think about deceiving me.}
{208}{}{Fuck off in a good way.}

{210}{}{Thank you for coming. Were you not followed?}
{1210}{}{Thank you for coming. You weren't followed?}
{211}{}{What do you want from me?}
{212}{}{You see... My husband has recently disappeared. He went to the plantation and never came back. I was looking for him, but I didn't find him. I need your help!}
{213}{}{But why be so careful?}
{214}{}{I am forbidden to talk about it! In order not to raise panic - that's what the mayor says. This is definitely a conspiracy! They're obviously hiding something there.}
{215}{}{What about the others? Why don't you look for him with the whole village?}
{216}{}{This place is not as beautiful as it seems. We are being silenced, but believe me - this is not the first case of people disappearing.}
{217}{}{Forced? How so?}
{218}{}{There are very strict rules here. From the outside, the city looks plausible, but in fact we pay for it with our freedom. Any dissenters will be punished or thrown out of the gate.}
{219}{}{Okay. I'll look for him. What does he look like?}
{220}{}{Swarthy, short, wears a mustache... Oh, yes, he had a marriage pendant with him. These are issued by the mayor to everyone who marries in our city.}
{221}{}{Don't worry, I'll try to find him.}
{222}{}{I promise nothing.}
{223}{}{The case is vague and looks dangerous. So I'll look, but for a fee.}
{224}{}{Sure. I'll get you some food and give you all my caps-I don't have anything else anyway.}
{225}{}{Please find a husband! I have no one else to turn to!}
{226}{}{Okay, calm down.}

{230}{}{How are you? I don't have much, as you can see.}
{231}{}{So what? Did you manage to find it?}
{232}{}{Not yet.}
{233}{}{I see. Later.}

{240}{}{We never met. Who are you?}
{241}{}{Ah, sorry. I'm Rosalia, I'm processing crops.}
{242}{}{I have to go, Rosalia.}
{243}{}{They say you fought with your husband?}
{244}{}{Of course we had quarrels! After all, this is not a marriage for love. The mayor's office is interested in marriages and gives us some benefits. But in a few years, my husband and I have somehow got used to each other...}
{245}{}{I see...}
{246}{}{Wait a minute, who told you that? I hope you haven't discussed this with Mayor Alvaro? He can't be trusted! Do you hear? Don't talk to him about missing people.}
{1246}{}{Wait a minute, who told you that? I hope you haven't discussed this with Mayor Alvaro? He can't be trusted! Do you hear? Don't talk to him about missing people.}
{247}{}{Okay, calm down...}

{250}{}{Your husband is dead. I'm sorry.}
{251}{}{Was your husband a green freak? Then know that he has completely withered and is lying in a barn on the plantation.}
{252}{}{I no longer had any doubts. He was killed, wasn't he? Isn't it? Tell the truth!}
{253}{}{A strange thing happened to him. It's like a disease. You'd better go and see.}
{254}{}{What is it... We knew that some insects spread the infection, but for the infection to spread through the body like THIS?}
{255}{}{So this is not the first case?}
{256}{}{The Followers are to blame for everything. It was they who ruined him with their experiments! And not only him! Devils!}
{257}{}{Followers of the Apocalypse? What kind of experiments?}
{258}{}{They have a laboratory in the desert. But we are forbidden to even approach there... Ah, the damned scientists! They gave us the harvest, but took the souls.}
{259}{}{[Keep silent]}
{260}{}{You have a good heart, señor. Go with God. And avoid these scientists.}
{1260}{}{You have a good heart, señora. Go with God. And avoid these scientists.}
{261}{}{Don't despair, Rosalia. Goodbye.}
{262}{}{I think I should still discuss this with them. Goodbye.}
{263}{}{My job is done. How about payment?}
{264}{}{What do you need? bottlecaps? On! Take everything and leave me alone! You outsiders think only of yourself...}
{265}{}{Don't be so tense, woman.}