{100}{}{You see Arthur Carrington.}
{101}{}{You see the Vault 27 archeologist.}

#First dialogue
{200}{}{Happy to see you again, hero.}
{1200}{}{Happy to see you again, heroine.}
{201}{}{I see you have already established yourself in this new place. Could I take just a minute of your precious time?}
{202}{}{Yes?}
{203}{}{Bye.}
{204}{}{Another question.}

{220}{}{What is it you do here?}
{221}{}{I'm being offered to teach kids literacy. It's not something I am experienced in. But better than working at the plantation. They don't let me near more important research. And this annoys me, after all, I managed several important projects in the past.}
{222}{}{I think you'll do just fine. Relax.}
{223}{}{What do you think about the Followers?}
{224}{}{At first, I was charmed by their pursuit of knowledge. But their unrestricted altruism is shocking. You can't just spend resources on and share knowledge with everyone you see. Many simply don't deserve it. And even if they do, their stupidity does not allow them to properly use the gift they were handed.}
{225}{}{You just have different opinions on an issue. That's normal.}