{100}{}{This is Arthur Carrington.}
{101}{}{You see the same archaeologist from Vault 27.}

#The first dialog
{200}{}{Glad to see you again, hero.}
{1200}{}{Glad to see you again, heroine.}
{201}{}{I see you've already settled into your new place. Can you give me a minute?}
{202}{}{Yes?}
{203}{}{Bye.}
{204}{}{Another question.}

{220}{}{What are you doing here?}
{221}{}{I am offered to teach children to read and write. It's an unusual experience. But it's better than messing around on a plantation. I am not allowed to do more serious research yet. And it's annoying, because I used to manage several serious projects.}
{222}{}{I think you'll get along with time. In the meantime, relax.}
{223}{}{What do you think about Followers?}
{224}{}{At first I was fascinated by their thirst for knowledge. But their kindness is shocking. It is impossible to help everyone so indiscriminately and share knowledge. Many simply do not deserve it. And if they deserve it, then because of stupidity they are not able to properly dispose of the received good.}
{225}{}{You have different views on the same thing. This is normal.}