{100}{}{This is Frank.}
{101}{}{You see a sullen man in combat gear.}
{102}{}{Put your weapon away immediately.}
{103}{}{Leave this armor immediately.}
{104}{}{Weapons! Remove!}
{105}{}{There is a hostile personality in the city. Everyone find Vault!}

{200}{}{Did something happen?}
{201}{}{No. Should it have?}
{202}{}{I'm not going to waste a lot of time on you. Can you read? Then remember the rules written at the main gate, and nothing will happen to you.}
{203}{}{Oh yes, the rules...}
{204}{}{Glad to meet you, brother! Congratulations on the promotion.}
{1204}{}{Glad to meet you, Sister! Congratulations on the promotion.}
{205}{}{Are you from the Brotherhood too?}
{206}{}{That's right. The Order keeps order in this city. Our patrols stop here periodically. Don't worry, this place is calm and safe. Some fighters are even sent here for rest and treatment. On the ship, as you understand, the conditions are not the most pleasant.}
{207}{}{Well yes. Do you mind if I stay here for a while? Great.}

{210}{}{I'm listening.}
{211}{}{I'm listening to you carefully.}
{212}{}{Are you still here?}
{213}{}{I won't distract you anymore. Later.}

{220}{}{They say people disappear on plantations, and you do nothing.}
{221}{}{There must be serious grounds for such statements.}
{222}{}{That's what people say...}
{223}{}{Remember, stranger, I don't like it when they create panic and spread rumors in my city. If you don't want problems, don't aggravate your situation. It's simple.}
{224}{}{Yes, indeed. I don't want any problems.}
{225}{}{The same goes for you. Remember - sooner or later justice will overtake anyone.}

{230}{}{Isn't it forbidden to openly carry weapons here?}
{231}{}{That's right - it's forbidden. And you should honor our laws like your own mother.}
{232}{}{But why do you carry a gun?}
{233}{}{I am the one who defines such rules.}
{234}{}{I understand now. I'm sorry for asking ridiculous questions. Can I go?}
{235}{}{Well yes. It's so convenient...}
{236}{}{I don't like you. You come to a place where you were not invited, and you dare to doubt our rules. But I'll give you a choice. One of two.}
{237}{}{And what is it?}
{238}{}{Or you accept the rules and stop annoying others. Either you get the hell out of here. Think carefully about the answer.}
{239}{}{The only one who bothers everyone here is you. And I'll do anything to ruin your watch.}
{240}{}{Good. I'll make a choice. The most correct choice.}
{241}{}{Yes - forbidden. The peasants must know who their master is. Yes, you should follow these rules too.}
{242}{}{Of course.}

{250}{}{Any problems? Why are you violating public order?}
{251}{}{I just can't sleep. So I wanted to breathe the night air.}
{252}{}{Don't talk your teeth into me. Everyone has to sleep in their holes during curfew. I'll give you two minutes to get into bed and not crawl out of there until six in the morning.}
{253}{}{I will, sir. No problem, sir...}
{254}{}{Any problems?}
{255}{}{No, none.}
{256}{}{I'm on patrol. If there are no good reasons, it is better not to go outside at this time. I might take you for a robber or a beast from the desert.}
{257}{}{Sorry, I'll be leaving soon.}
{258}{}{You know the rules. Don't make me angry is the main one.}
{259}{}{Sorry, I'll be leaving soon.}
{260}{}{You again. We've already discussed what not to do at night. So what's the problem?}
{261}{}{Uh, insomnia, sir. I'm sorry, sir...}
{262}{}{Well, that's it, I was trying to be kind. It's time to teach you a lesson. You'll sit in a cell for a dozen hours and think about your behavior. Get moving. And don't try to run away from me.}
{263}{}{Okay, sir, I won't resist...}
{264}{}{Suck it!}
{265}{}{I'm sick of it!}
{266}{}{Oh, oh...}
{267}{}{Suck it!}

{270}{}{So we met, scum. Good-I won't have to look for you. Do you think you'll just run away from the order?}
{271}{}{Sure. And you're not a hindrance to me.}
{272}{}{Nothing will be hidden from the order. You're a criminal. The Brotherhood of Steel demands that you be brought to justice on the spot. Do you have the last word? No, to hell with it. You have no right to...}
{273}{}{Oops...}
{274}{}{I don't know what you're talking about. Surely you are confusing me with someone...}
{275}{}{You're confusing me with someone else. I do not know about any order.}
{276}{}{Hmm, maybe. Although the description is very similar to you. Okay, for now I'll consider you a suspect.}
{277}{}{Ugh, it's gone...}

{280}{}{Can you tell me about the city?}
{281}{}{Here's what I'll tell you about the city, stranger. Follow the rules and don't bother the residents. Then you can settle in if you want. In general, except for the mayor and Followers, it is better not to communicate with anyone.}
{1281}{}{Here's what I'll tell you about the city, stranger. Follow the rules and don't bother the residents. Then you can settle in if you want. And in general, except for the mayor and Followers, it is better not to communicate with anyone.}
{282}{}{Clear.}
{283}{}{Who's in charge here?}
{284}{}{The city is ruled by Mayor Alvaro. It's down the street in a big building with arches.}
{285}{}{Clear.}
{286}{}{What are you doing?}
{287}{}{I am the commandant of this city. I am responsible for the security and enforcement of the law.}
{288}{}{I see. I wish you a successful service.}
{289}{}{So how is security here?}
{290}{}{Full order.}
{291}{}{Really?}
{292}{}{I believe it willingly.}
{293}{}{The law. Security. Boring. Want to fight!}
{294}{}{Hmm-m... There is one damn place where it is better not to go. I want to warn you right away so that I don't have to pull you out of there.}
{295}{}{Tell me.}
{296}{}{A concrete plant outside the city and a quarry near it. The plant was closed after people began to disappear there. There are various rumors, but still no one knows what happened there.}
{297}{}{Clearly. Thanks for the warning.}

#El Gigante
{300}{}{About the concrete plant.}
{301}{}{Yes?}
{302}{}{Please don't tell me any more about this creepy place.}
{303}{}{I will solve the problem for 300 caps.}
{304}{}{I have already heard these words from past mercenaries. If life is precious, then don't go to the silo.}
{305}{}{Still, I'll try. Take me to the silo right now.}
{306}{}{I think I'll listen to your words.}
{307}{}{There was a monster in the factory. I managed to finish him off. The tenacious bastard got caught...}
{308}{}{...I'll be damned! Death claw? Here? How far have these creatures made their way.}
{309}{}{He's not threatening you now.}
{310}{}{Great job. The whole city owes you. So be it, I will beat out a reward for you from the city treasury.}
{311}{}{Thank you.}
{312}{}{How do you know about the claws?}
{313}{}{I've heard a lot in school, but I've never encountered it myself. Veterans said that the claws live in the mountains in the west, where almost no one lives.}
{314}{}{Curious.}
{315}{}{I know of only one case when the claws were in the city and caused a lot of noise. It was in the Burial Ground. There was a uterus in an abandoned basement. She even laid eggs. But one brave mercenary found them and shot them, and broke their eggs. It's scary to think what would have happened if these creatures had hatched.}
{316}{}{What a horror.}
{317}{}{In general, well done, fighter. You should serve in our ranks.}
{318}{}{Bye.}
{319}{}{You let it slip about school. Where was it?}
{320}{}{I am a paladin of the Brotherhood of Steel. Our local base is in Puerto Penasco, and the general staff is far away in California. That's where I learned the basics of service until I volunteered for a mission to this desert.}
{321}{}{Wow. I will know.}
{322}{}{I want to help you with this problem. Will you show me this place?}

#Kicks
{330}{}{I got Pinky here. They say you want him dead.}
{331}{}{Chipo should be shortened for such words. I'm not bloodthirsty. But I have a mission - to ensure the safety of the city. Formally, there is no reason to exterminate the pig-rat yet. But let him give at least one reason - and he will begin his big rat journey to heaven.}
{332}{}{Why do you dislike him so much?}
{333}{}{Now it's a harmless cub, but what will happen when it grows up and smells blood? Pig rats are aggressive predators, they have no place among people.}
{334}{}{Hmm.}
{335}{}{Your position is clear. It couldn't be clearer.}
{336}{}{What do you care about a pig-rat? Obviously, one curiosity. Then I have a suggestion. I'll pay 30 caps if you kill this beast. What do you say?}
{337}{}{Well, no. I don't want to hurt a teenager.}
{338}{}{Chipo is to blame! There was nothing to bring a cub into the house. Alvaro also did not have the courage and courage to put everything in its place. Sorry. It's a pity that there are only weaklings around.}
{339}{}{Bye, Commandant.}
{340}{}{It won't take long. Count off the caps, buddy.}
{341}{}{I'm counting on you.}
{342}{}{See you, Commandant.}
{343}{}{That pig-rat isn't breathing anymore.}
{344}{}{Chipo must have been very upset. Sorry for the kid, but it's his own fault. This loss will serve him as a good lesson.}
{345}{}{Whatever you say.}
{346}{}{Make sure that the conclusions from the lesson are correct.}
{347}{}{You have a good grip. Maybe you'll come in handy again. So here are 30 caps, as I promised.}
{348}{}{See you later, Commandant.}

{350}{}{Listen, I really need to know if Tin-Tan has been here?}
{351}{}{Tin-Tan? Sounds like a nickname. Is there a real name?}
{352}{}{Herman Genaro Cipriano Gomez Valdez y Castillo. He traveled by stagecoach from Phoenix to the Platform.}
{353}{}{Now I'll look at the migration log... Wait a minute. I have no record of him visiting Casa Nueva.}
{354}{}{What about the Sonora Express stagecoach?}
{355}{}{Wait a minute... Yes, there is that name here, but... I have it recorded that the whole stagecoach died at the hands of highway robbers, never reaching us.}
{356}{}{Well, not fate. Thanks, Cap.}