{100}{}{You see Frank.}
{101}{}{You see a gloomy man in combat gear.}
{102}{}{Put the weapon away immediately.}
{103}{}{Put the armor away immediately.}
{104}{}{Weapon! Put it away!}
{105}{}{Hostile in town. Everyone find shelter!}

{200}{}{Did something happen?}
{201}{}{No. Was it supposed to?}
{202}{}{I'm not going to spend much time on you. Can you read? Then remember the rules written near the main gates, and nothing will happen to you.}
{203}{}{Ah yes, the rules...}
{204}{}{Happy to meet you, brother! Congratulations with the promotion.}
{1204}{}{Happy to meet you, sister! Congratulations with the promotion.}
{205}{}{Are you from the Brotherhood too?}
{206}{}{Yes. The order maintains stability in this town. Our patrols stop here periodically. Don't worry, this place is calm and safe. They even send some soldiers here to rest and heal. The conditions on the ship, as you know, aren't the most pleasant.}
{207}{}{Alright. Are you okay with me staying here? Great.}

{210}{}{I'm listening.}
{211}{}{I'm all ears.}
{212}{}{You still here?}
{213}{}{I won't distract you any longer. Bye.}

{220}{}{They say people are going missing on the plantations, and you aren't doing anything about it.}
{221}{}{Such serious claims require serious evidence.}
{222}{}{The people say...}
{223}{}{Now remember this, outsider, I don't like it when people cause panic and spread rumours in my town. You don't want trouble - don't make your situation worse. It's that simple.}
{224}{}{Yeah, it really is. I don't want trouble.}
{225}{}{The same applies to you. Remember - sooner or later, justice will reach everyone.}

{230}{}{Isn't openly carrying weapons not allowed here?}
{231}{}{That's right - it is. You should respect our laws like you respect your own mother.}
{232}{}{Then why are you walking around with one?}
{233}{}{I am the one who makes these kinds of rules.}
{234}{}{I see. Sorry that I'm asking stupid questions. Can I go?}
{235}{}{Oh, of course. That's so convenient...}
{236}{}{I don't like you. You come to a place nobody asked you to come to, and then you dare to question our rules. But I'll give you a choice. Two, in fact.}
{237}{}{And what are they?}
{238}{}{Either you choose to accept our rules and stop bothering those around you, or you choose to get the fuck outta here. Think hard before answering.}
{239}{}{The only one who's bothering everyone here is you. And I'll do everything in my power to make your job a living nightmare.}
{240}{}{Good. I've made my choice. The correct one.}
{241}{}{Yes - not allowed. We don't need the peasants getting any ideas. Yes, you too should follow these rules.}
{242}{}{Of course.}

{250}{}{Problem? Why are you disrupting public order?}
{251}{}{I can't sleep. I wanted to go for a walk and breathe some night air.}
{252}{}{Don't "I can't sleep" on me. The rules clearly state that during curfew, everyone must be in their houses, sleeping. I'm giving you two minutes to get to bed and not come out of it until 6 o'clock.}
{253}{}{I'll do just that, sir. No problem, sir, no problem at all...}
{254}{}{Problem?}
{255}{}{None.}
{256}{}{I'm patrolling. If there isn't some very important reason, it's best not to be on the street during this time. I could think you're a thief or some beast from the desert.}
{257}{}{Sorry, I'll go away soon.}
{258}{}{You know the rules. Not angering me is on the top of the list.}
{259}{}{Sorry, I'll go away soon.}
{260}{}{You again. We already discussed what one must not do during the night. What's your problem?}
{261}{}{Uhh, insomnia, sir. I apologize, sir...}
{262}{}{That's it. I tried to ask nicely, that didn't work. Now it's time for me to teach you a lesson. You'll spend some ten hours in a cell and think hard about your behavior. Now get moving. And don't even think about running away from me.}
{263}{}{Alright, sir, I won't resist...}
{264}{}{Make me!}
{265}{}{I'm tired of this shit!}
{266}{}{Oops...}
{267}{}{Make me!}

{270}{}{So, we meet at last, scum. You know, it's very good - we didn't even have to search for you. You think you can simply escape from the order?}
{271}{}{Yes.}
{272}{}{No one hides from the order forever. You're a criminal. The Brotherhood of Steel demands that you be put to justice on the spot. Any last words? No, to hell with that. You don't have the rights to say them...}
{273}{}{Oops...}
{274}{}{I have no idea what you're talking about. You must be confusing me with someone else...}
{275}{}{You must be confusing me with someone else. I don't know of any order.}
{276}{}{Your appearance fits *very* neatly into the description. But if there's a real possibility you're not who I think you are, I can't kill you. I will, however, consider you suspicious.}
{277}{}{Oof, certain death averted...}

{280}{}{Can you tell me about the town?}
{281}{}{Here's what I'll tell you about the town, outsider. Follow the rules and don't annoy the people. If you want, you can live here then. Actually, it's better not to talk to anyone except the mayor and the Followers.}
{1281}{}{Here's what I'll tell you about the town, outsider. Follow the rules and don't annoy the people. If you want, you can live here then. Actually, it's better not to talk to anyone except the mayor and the Followers.}
{282}{}{Alright.}
{283}{}{Who's in charge here?}
{284}{}{The town is ruled by mayor Alvaro. He's located in the big building with arches.}
{285}{}{Alright.}
{286}{}{What do you do?}
{287}{}{I'm this city's commandant. I'm responsible for safety and upholding the law.}
{288}{}{Alright. I wish you a successful service.}
{289}{}{What's the safety like here?}
{290}{}{Total.}
{291}{}{Really?}
{292}{}{Yeah, I totally believe you.}
{293}{}{Law. Sa-feti. Boring. Me wanna fight!}
{294}{}{Hm-m... There is one cursed place where one shouldn't go. I want to warn you right away, so that I won't have to drag you away from it.}
{295}{}{Tell me about it.}
{296}{}{The concrete factory beyond the town and the quarry near it. The factory was closed after people started going missing there. There are various rumours, but even now, nobody knows what the hell happened there.}
{297}{}{Alright. Thanks for the warning.}

#El Gigante
{300}{}{About the concrete factory.}
{301}{}{Yes?}
{302}{}{Please, don't tell me anything else about this scary place.}
{303}{}{I'll solve this problem for 300 caps.}
{304}{}{I heard such words from previous mercenaries. If you value your life, don't come close to the silo.}
{305}{}{I'll still try. Show me the way to it right away.}
{306}{}{I'll heed your words.}
{307}{}{A monster lived in the factory. I managed to kill it. The bastard had a real problem with dying though...}
{308}{}{...Well I'll be damned! A deathclaw? Here? These fuckers sure spread far.}
{309}{}{It's not a threat to you anymore.}
{310}{}{Great work. The whole town is in your debt. Alright, I'll give you a reward from the treasury.}
{311}{}{Thanks.}
{312}{}{Where did you learn about the deathclaws?}
{313}{}{During training, but I never actually met one. The veterans said they live in the western mountains, where there are barely any people.}
{314}{}{Interesting.}
{315}{}{I know of only one time they were in a city and caused a lot of trouble. It was in the Boneyard. Los Angeles. A mutant 'mother' deathclaw lived in some abandoned basement. It could lay eggs. But one brave merc found and killed it, and broke the eggs. It's scary to think what could have happened if these things actually hatched.}
{316}{}{Scary.}
{317}{}{I say, you did good job. We could use you in our ranks.}
{318}{}{Bye.}
{319}{}{You talked about training. Where did it happen?}
{320}{}{I'm a Brotherhood of Steel paladin. Our local base is in Puerto Penasco, and the HQ is far off in California. That's where I went through the basics until I had to go to this desert on a mission.}
{321}{}{Wow.}
{322}{}{I want to help you with your problem. Can you show me the place?}

#Pinky
{330}{}{I saw a certain Pinky. They say you want it dead.}
{331}{}{Chippo should have his tongue cut for such words. I'm not bloodthirsty. But I do have a mission - provide the town with safety. Strictly speaking, I have no reason to exterminate the pigrat yet. But if it gives me the smallest one - it can kiss it's ass goodbye.}
{332}{}{Why do you dislike it so much?}
{333}{}{Right now it's just a harmless young, but what will happen when it grows up and smells blood? Pigrats are aggressive predators, they have no place among humans.}
{334}{}{Hm.}
{335}{}{Your position is very clear. In fact, it couldn't be any clearer.}
{336}{}{And why do you care about the pigrat? Clearly, simple curiosity. Then I have an offer. I'll pay you 30 caps if you rid the town of that animal. What do you say?}
{337}{}{No way. I don't want to hurt a teenager like that.}
{338}{}{It's Chippo's own damn fault! He shouldn't have brought that thing into his home in the first place. And Alvaro doesn't have the guts to make things right. Sad. Sad that everyone's so weak here.}
{339}{}{Goodbye, commandant.}
{340}{}{This won't take long. Start counting the caps, buddy.}
{341}{}{I'm counting on you.}
{342}{}{See you, commandant.}
{343}{}{The pigrat is dead.}
{344}{}{Chippo must be really sad. I feel sorry for him, but the animal would need to be killed in the future, anyway. This will serve as a good lesson to him.}
{345}{}{Whatever you say.}
{346}{}{Make sure that the conclusions he makes from this lesson are the right ones.}
{347}{}{You seem like someone with potential. Maybe I could have some use for you in the future. So here, take the 30 caps I promised you.}
{348}{}{Until next time, commandant.}

{350}{}{Hey. I really need to know, has someone called "Tin Tan" visited this place? It's very important.}
{351}{}{Tin Tan? Sounds like a nickname. Do you know their real name?}
{352}{}{Germán Genaro Cipriano Gomez Valdes y Castillo. He was traveling by stagecoach from Phoenix to the Platform.}
{353}{}{Let me take a look at our migration log... Wait a minute. There are no records of him visiting Casa Nueva.}
{354}{}{What about Sonora Express?}
{355}{}{Let me take a look... Yes. His name is there, but... It reads that the entire stagecoach was killed by the highwaymen before reaching Casa Nueva.}
{356}{}{Welp, I suppose it wasn't meant to be. Thank you for your time, mister.}