{100}{}{Here is the manager.}
{101}{}{You see a man in work clothes.}

{200}{}{Ah, that's our hero. I know, I know, that thing is your doing, right? The whole city is grateful to you.}
{1200}{}{Ah, this is our heroine. I know, I know, that thing is your doing, right? The whole city is grateful to you.}
{201}{}{I see you didn't waste any time.}
{202}{}{We were preparing concrete and bricks here until El Gigante appeared. He killed many workers, so the plant had to be closed. Well, now there is no monster - and the work continues.}
{203}{}{I see.}
{204}{}{Come in, I'm always glad to see such useful people.}
{205}{}{I have to go now.}
{206}{}{I see.}

{210}{}{How much do you pay workers?}
{211}{}{They are mostly convicts and slaves. They have enough water, food and work clothes. There are also free mercenaries, but there are not many of them.}
{212}{}{Is this career really that important to you?}
{213}{}{I do not know of any operating concrete plant other than ours. Not one! When someone needs to build a house, he drags bricks from old ruins. And only we in Casa Nueva are building houses from scratch.}
{214}{}{Do you sell cement and bricks?}
{215}{}{At first, the plant served the colony of Casa Nueva, and now we carry mixtures to construction sites in Puerto and Tu San. We will soon arrange delivery to Phoenix, if everything goes well there with the local authorities. But first you need to restore normal operating mode.}