{100}{}{You see a worker.}
{101}{}{You see a man in work clothes. He looks exhausted.}

{110}{}{So it's because of you that I'm being forced to work here?}
{111}{}{If it wasn't for you, I wouldn't have been sent to this penal servitude.}
{112}{}{Administrator in that building over there.}
{113}{}{Do you know how to escape from this penal servitude?}
{114}{}{Many here work against their will. The rest are for beggarly wages.}
{115}{}{Do you want to knead this shit too?}
{116}{}{They say a monster lived here. Pray that he is the only one.}
{117}{}{If this monster shows up again, let them kill me right away.}
{118}{}{The request for concrete and bricks is huge.}
{119}{}{There is a lot of work. We work in three shifts.}