{100}{}{You see a worker.}
{101}{}{You see a man in working clothes. He looks exhausted.}

{110}{}{So it's because of you that I'm working here?}
{111}{}{If it wasn't for you, I wouldn't have been sent here.}
{112}{}{The administrator is in the building over there.}
{113}{}{Do you know of any way to escape this place?}
{114}{}{Many people here are not working by their own free will. The ones that are, though, receive pathetic income.}
{115}{}{You want to knead this shit too?}
{116}{}{They say a monster lived here. Pray it's the only one.}
{117}{}{If this monster appears again, I hope it just kills me on the spot.}
{118}{}{The demand for concrete and bricks is enormous.}
{119}{}{There's a lot of things to do. We work three shifts.}