{100}{}{You see a manager.}
{101}{}{You see a man in working clothes.}

{200}{}{A-ah, here comes our hero. The death of the abomination there was your doing, yes? The whole town is thankful to you.}
{1200}{}{A-ah, here comes our heroine. The death of the abomination there was your doing, yes? The whole town is thankful to you.}
{201}{}{I see you didn't waste time.}
{202}{}{We were preparing concrete and bricks here until El Gigante appeared. It killed many workers, so the factory had to be closed. Now the monster's gone - work continues.}
{203}{}{Understood.}
{204}{}{Come, I am always happy to see such helpful people.}
{205}{}{I should already go.}
{206}{}{Understood.}

{210}{}{How much do you pay the workers?}
{211}{}{For the most part, they are convicts and slaves. They're content with food, water and clothes. There are some mercenaries willing to do it, but not many.}
{212}{}{Is this place really so important to you?}
{213}{}{I know of no other functioning concrete factory other than ours. No other! When someone needs to build a house, they haul bricks from old ruins. Only here in Casa Nueva do we build it from the ground up.}
{214}{}{Do you trade the concrete and bricks?}
{215}{}{First the factory was servicing the Casa Nueva colony, but now we deliver our product to construction sites in Puerto and Two Sun. Soon we'll add Phoenix to the list, that is, if the situation with the local rulers there ends in a satisfactory way. But first, we need to restore a normal working environment.}