{100}{}{In front of you is a gas mixer.}
{101}{}{You see a system of gas cylinders and pipes with access to ventilation. It looks like it's part of managing the local climate.}
{102}{}{This is part of the local climate system. A sign with the inscription "Caution! Explosive".}
{103}{}{The system is out of order and is about to burn everything around.}
{104}{}{It won't do anything. The system is out of order and is about to burn everything around.}
{105}{}{Burn! Burn-and-and!}
{106}{}{The system is failing. A little more, and a fire will start here...}