{100}{}{You see a gas mixer.}
{101}{}{You see a system made out of gas cylinders and pipes that go into the vents. Looks like this is part of the microclimate control system.}
{102}{}{This is part of the microclimate system. There's a sign nearby that reads "Danger! Volatile!".}
{103}{}{The system stopped working and is about to burn down everything around here.}
{104}{}{This doesn't do anything. The system stopped working and is about to burn everything around here.}
{105}{}{Burn! Bu-u-urn!}
{106}{}{The system has stopped working. A bit more and a fire will start here...}