{100}{}{You see the microclimate control panel.}
{101}{}{You see a panel to control the microclimate in the greenhouses.}
{102}{}{Doesn't work.}

{110}{}{The microclimate system isn't working. The most likely cause is a lack of power.}
{111}{}{The climate system performs the task given to it very well.}
{112}{}{You turn on the ventilation in the central dome.}
{113}{}{You turn on the ventilation in the eastern greenhouses.}
{114}{}{You turn on the ventilation in the western greenhouses.}