{100}{}{Here is the microclimate management.}
{101}{}{You can see the panel for controlling the microclimate in greenhouses.}
{102}{}{Does not work.}

{110}{}{The climate system is not working. It's probably de-energized.}
{111}{}{The climate system successfully copes with its tasks.}
{112}{}{You turn on the ventilation in the central dome.}
{113}{}{You turn on the ventilation in the eastern greenhouses.}
{114}{}{You turn on the ventilation in the western greenhouses.}