{100}{}{You see a laboratory computer.}
{101}{}{You see a laboratory computer.}
{102}{}{The computer doesn't turn on because of the lack of power.}
{103}{}{Not turning on.}

#Dialogue
{200}{}{Enter command.}
{201}{}{Conclude session.}
{202}{}{Previous.}
{203}{}{Next.}
{204}{}{Return to main menu.}

{210}{}{Research Notes by Van Chun.}
{211}{}{"The goal of research for the next five years: creation of dry climate resistant plants that still bear fruit suitable for mass cultivation. Would prove a solution for the food problem that the contemporary rising population in Arizona and California is encountering".}
{212}{}{Material base for experiments.}
{213}{}{"Work is carried out in the well-preserved "Greenway Hydroponics" laboratory, where, before the Great War, various experiments to create plants resistant to drought and radiation were conducted. The materials made here also included the standard Vault-Tec fallout shelter equipment, meant for a population to survive after an atomic war".}
{214}{}{Continue.}
{215}{}{"Within the laboratory, the following was preserved: work equipment, automated hydroponic machinery, non-radiated seeds of various plants and fungi, detailed documentation and Pre-War literature, as well as a a diverse set of chemicals, biological additives and viruses".}
{216}{}{Goals of the project.}
{217}{}{"Goal No. 1 - study the research and baterial base "Greenway Hydroponics" with the goal of restoring the complex and laboratory. Among the local developments are ready-made solutions that could be used to fulfill the nutritional needs of Casa Nueva".}
{218}{}{Continue.}
{219}{}{"Goal No. 2 - plant breeding purely to increase the seed reserves. Work must be done in the isolated greenhouses of the complex to create the most clean and suitable environment possible".}
{220}{}{Continue.}
{221}{}{"Goal No. 3 - breeding new varieties of plants fit to survive in the Sonora desert's sand and in the radioactive wastelands of California".}
{222}{}{Important note.}
{223}{}{"One of the most important conditions for the experiment is the stimulation of plant growth, most importantly, of the root system. Various methods of achieving this stimulation have been proposed: biological additives, irradiation, fungi spores and even viruses from the "Greenway Hydroponics" reserves. To ensure safety, access to the laboratory should be highly restricted".}
{224}{}{Copy the research data.}
{225}{}{The archives have been successfully copied onto the holodisk.}