{100}{}{You see a lab computer.}
{101}{}{Here is a laboratory computer.}
{102}{}{The computer does not start due to lack of electricity.}
{103}{}{Does not turn on.}

#Dialog
{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Next.}
{204}{}{Go back to the main menu.}

{210}{}{Wang Chong's research notes.}
{211}{}{"Setting the research goal for the next five years: the creation of dry climate resistant and at the same time fruit-bearing crops suitable for mass cultivation. Thus - to solve the food problem in Arizona and California, which is faced by the modern growing population."}
{212}{}{The material base of the experiment.}
{213}{}{"The work is being carried out on the basis of the well-preserved laboratory "Greenway Hydroponics", where, even before the Great War, various experiments were conducted to create drought-resistant and radiation-resistant plants. In particular, it was here that the materials included in the standard set of Vault-Tec Vaults for the survival of the population after a nuclear war were prepared."}
{214}{}{Next.}
{215}{}{"The laboratory has preserved: working inventory, automated hydroponic equipment, seeds of various plants and fungi not spoiled by radiation, rich laboratory documentation and pre-war literature, as well as a diverse set of chemicals, biological additives and viruses."}
{216}{}{Project objectives.}
{217}{}{"The first task is to study the research and material base of Greenway Hydroponics in order to restore the operation of the complex and laboratory. Among the local developments, there are ready-made solutions that can be used for the needs of Casa Nueva."}
{218}{}{Next.}
{219}{}{"The second task is the cultivation of plants solely to increase seed stocks. The work should be carried out in isolated greenhouses of the complex to create the cleanest and most comfortable environment."}
{220}{}{Next.}
{221}{}{"The third task is to breed new varieties suitable for survival on the sands of the Sonoran desert and in the radioactive wastelands of California."}
{222}{}{Important note.}
{223}{}{"One of the important conditions of the experiment is to stimulate the growth of plants, especially their root system. Various ways of this stimulation are assumed: biological additives, irradiation, fungal spores and even viruses from Greenway Hydroponics stocks. In order to increase safety, access to the laboratory should be strictly limited."}
{224}{}{Copy the research data.}
{225}{}{The archives have been successfully copied to the holodisk.}