{110}{}{Does not need repair.}
{111}{}{Raw materials are out.}
{112}{}{You have no idea how it works.}
{113}{}{This device is configured only for mature leaves of fire agave.}
{114}{}{This device is used to make juice, and not vice versa.}

{120}{}{You have prepared one bottle of agave juice.}
{121}{}{You have prepared two bottles of agave juice.}
{122}{}{You have prepared three bottles of agave juice.}
{123}{}{You have prepared four bottles of agave juice.}
{124}{}{You have prepared five bottles of agave juice.}
{125}{}{You have prepared six bottles of agave juice.}
{126}{}{You have prepared seven bottles of agave juice.}
{127}{}{You have prepared eight bottles of agave juice.}
{128}{}{You have prepared nine bottles of agave juice.}
{129}{}{You have prepared ten bottles of agave juice.}