{110}{}{Doesn't need to be repaired.}
{111}{}{Out of raw material.}
{112}{}{You have no idea how this works.}
{113}{}{The machine is set up to only be able to deal with fresh leaves of the fiery agave.}
{114}{}{This machine is for producing juice, not the other way around.}

{120}{}{You have made one bottle of agave juice.}
{121}{}{You have made two bottles of agave juice.}
{122}{}{You have made three bottles of agave juice.}
{123}{}{You have made four bottles of agave juice.}
{124}{}{You have made five bottles of agave juice.}
{125}{}{You have made six bottles of agave juice.}
{126}{}{You have made seven bottles of agave juice.}
{127}{}{You have made eight bottles of agave juice.}
{128}{}{You have made nine bottles of agave juice.}
{129}{}{You have made ten bottles of agave juice.}