{100}{}{You see a laboratory.}
{101}{}{You see a chemical laboratory.}
{102}{}{You see a chemical laboratory. Working with it requires using the ways of science.}
{103}{}{The compound is ready for the chemical process and is placed inside of a special container.}
{104}{}{Compounds are necessary to complete the chemical process.}
{105}{}{You've made the poison. Exactly what the Followers need.}
{106}{}{You need the research notes to properly make the poison.}
{107}{}{Your job here is done.}
{108}{}{You need compounds and instructions.}
{109}{}{I need the instructions.}
{110}{}{Ready.}