{100}{}{You can see the lab.}
{101}{}{Here is a chemical laboratory.}
{102}{}{This is a chemical laboratory. Scientific methods are required to work with it.}
{103}{}{The component is prepared for the chemical process and loaded into a special vessel.}
{104}{}{Components are needed to complete the chemical process.}
{105}{}{The poison is made. This is exactly what Followers need.}
{106}{}{We need laboratory data to make the poison properly.}
{107}{}{There's nothing else to do here.}
{108}{}{Components and instructions are needed.}
{109}{}{I need instructions.}
{110}{}{Done}