#Using items
{200}{}{This is not related to the trunk. Try it on the bike itself.}
{201}{}{You have replaced the old mounting. The luggage compartment's capacity has been increased by 5 units.}
{202}{}{You have already replaced this. Doing it again is pointless.}
{203}{}{Hardly possible during combat.}
{204}{}{You have installed a new luggage container. The bike can now hold more cargo.}
{205}{}{The bike has no more room for additional luggage containers.}
{206}{}{The bike does not belong to you.}

#Using skills
{300}{}{Nothing to hack here.}
{301}{}{After taking a good look at the trunk, you come to the conclusion that it's volume is equal to }
{302}{}{ units.}
{303}{}{Your skill is too low to improve the luggage container.}
{304}{}{Nothing to repair here.}
{305}{}{You cannot repair this bike until it becomes your property.}
{306}{}{The repair increased the luggage container's capacity by 5.}