{100}{}{+}
{101}{}{-}

#Using hands
{110}{}{Without power, the bike won't go anywhere.}
{111}{}{Damn, I need to insert a power block.}
{112}{}{The bike isn't starting. It seems that the navigation computer is locked. You will have to acquire an access key.}
{113}{}{Hmm. Looks like this thing needs an access key.}
{114}{}{Now is not the right time for remote travel.}
{115}{}{I have some unfinished business.}
{116}{}{You steal the bike from the highwaymen! Your reputation among them lowers accordingly.}
{117}{}{The bike can only fit two passengers.}

#Using items
{200}{}{Access granted. The bike is now fully operational.}
{201}{}{Not suitable.}
{202}{}{This vehicle uses a different power source.}
{203}{}{The bike doesn't need lubrication yet.}
{204}{}{The bike doesn't need to have it's components replaced yet.}
{205}{}{The navigation computer is not yet in need of repair.}
{206}{}{This skull will make for a fine addition to the bike's steering wheel. Others will see that you are not to be trifled with.}
{207}{}{Can only be done once you own the bike.}
{208}{}{The steering wheel is already adorned with a skull.}
{209}{}{You have replaced the broken headlight. It will now light the way for you.}
{210}{}{All the headlights on this bike are fully operational.}
{211}{}{This is related to the luggage compartment more.}

#Using skills
{300}{}{Nothing to hack here.}
{301}{}{The navigation computer is already under your control.}
{302}{}{This is too hard for you. Try to find the access key.}
{303}{}{Nothing to repair here.}
{304}{}{There's nothing to repair here. Though you haven't checked the trunk yet.}
{305}{}{You can't repair the bike until it becomes your property.} 