{100}{}{+}
{101}{}{-}

#Using hands
{110}{}{Without energy, the motorcycle will not go anywhere.}
{111}{}{Damn, I need to charge the power supply.}
{112}{}{The bike won't start. The on-board computer is locked and requires an access key.}
{113}{}{Hmm, it seems that a key is needed here.}
{114}{}{Now is not the right time for a remote trip.}
{115}{}{I have unfinished business.}
{116}{}{You stole a bike from bandits! I don't think they'll like it.}
{117}{}{The motorcycle can accommodate only two passengers.}

#Using items
{200}{}{Access has been obtained. Now the bike is ready to ride.}
{201}{}{It doesn't fit.}
{202}{}{This transport is charged from another energy carrier.}
{203}{}{The motorcycle does not need lubrication yet.}
{204}{}{The motorcycle does not need to change parts yet.}
{205}{}{The onboard computer does not need repair yet.}
{206}{}{This skull will serve as a great decoration for your steering wheel. And remind others that you are not to be trifled with.}
{207}{}{You can't do this until the motorcycle belongs to you.}
{208}{}{The steering wheel is already decorated with one skull.}
{209}{}{You have restored the blind headlight. Now she will light your way.}
{210}{}{This motorcycle has all the headlights in working order.}
{211}{}{This applies more to the luggage compartment.}

#Using skills
{300}{}{There's nothing to hack here.}
{301}{}{The onboard computer is already under your control.}
{302}{}{It's too complicated for you. Try to find the access key.}
{303}{}{There is nothing to repair here.}
{304}{}{There is nothing to repair here. However, you haven't examined the trunk yet.}
{305}{}{You cannot repair this bike until it’s yours.}