{100}{}{}
{101}{}{}
{102}{}{!Cheat: Volumetric heads are included.}
{103}{}{!Cheat: Volumetric heads are disabled.}

#The use of items on GG
{110}{}{A curious thing. It's worth looking for some use for it.}
{111}{}{These things are better to use when you get out.}
{112}{}{It's nice to pay yourself. But it doesn't make sense.}
{113}{}{You got one bottle cap.}
{114}{}{It will be more useful to sell this to urban upstarts.}
{118}{}{Use this item from your hand.}
{119}{}{Use this through your backpack or out of your hand.}

{120}{}{At the sight of this useless garbage, you involuntarily have an idea... the idea of burning this world in a new atomic war.}
{121}{}{This update is intended exclusively for the ZAX logic module.}
{122}{}{It's not like you're a nuclear bomb.}
{123}{}{These passwords should be used on computers and other electronic systems.}
{124}{}{You tore up this letter, trying to forget everything that connected you with the sect of fire worshippers.}
{125}{}{This letter should be presented to the Followers of Fire in Phoenix.}
{126}{}{Damn sectarians...}
{127}{}{I don't want to think about them anymore.}
{128}{}{Drinking this liquid in its pure form will only lead to an upset stomach.}
{129}{}{Hey, be careful! You almost cut off your head.}
{1129}{}{Hey, be careful! You almost cut off your own head.}

{130}{}{Setting your hair on fire is not the best idea.}
{131}{}{You've changed your boots. Now you can safely walk on burning and caustic substances. However, only a couple of minutes.}
{132}{}{This is not necessary yet, since the old boots are in excellent condition.}
{133}{}{This is not necessary yet, since the old glasses are still in working condition.}
{134}{}{Wearing these strange glasses, you seem to fall into another dimension.}
{135}{}{The battery of electronic glasses is depleted. Night vision is disabled.}
{136}{}{Take the glasses in your hand to feel like a handsome man.}
{1136}{}{Take the glasses in your hand to feel like a real fashionista.}
{137}{}{This is not necessary yet, since a gas mask can cope with protection.}
{138}{}{You've changed your gas mask. It will protect you from harmful gas and dust for a while.}
{139}{}{Yes, put it on your head and scare the village kids. It'll be fun.}

#Reset items
{140}{}{Your family members would not be happy to know that you are throwing away family heirlooms.}
{141}{}{Beggars will be very happy to find your caps.}
{142}{}{Imagining yourself a patron of the arts, you generously scatter money to the wind.}
{143}{}{These sandals will help you survive in caustic substances, but only for a short time.}
{144}{}{The bait is set.}

#Different replicas
{150}{}{A light heat comes from a radioactive object in your backpack.}
{151}{}{Your Pip-Boy shows the degree of exposure: }
{152}{}{This cannot be done during combat.}
{153}{}{One-two, the radio is working.}
{154}{}{Your legs can't stand the huge weight of the backpack.}
{155}{}{What a pain!}
{156}{}{Don't do it.}
{157}{}{It could be dangerous! Your recklessness almost ruined your character. And how upset Granny Adonsia would be...}
{158}{}{You should look for more reliable shoes. And this one can be sold at the nearest market.}
{159}{}{To parse this item, you will need a workbench.}
{160}{}{You need to collect ALL the parts of the map.}
{161}{}{You have collected all the parts of the treasure map. It looks like it's buried near the ruins of a local lighthouse.}

#Achievements
{200}{}{Your good fame is growing.}
{201}{}{Your notoriety is growing.}
{202}{}{A high dose of radiation permanently reduces your health.}
{203}{}{A high dose of radiation again permanently reduces your health.}
{204}{}{I'm getting worse.}
{205}{}{I'm getting MUCH worse.}
{206}{}{For a large number of beatings you get the achievement "Seasoned Fighter".}
{207}{}{I think I'm getting used to this pain.}
{208}{}{For your dastardly betrayal, you were stripped of all your ranks in the Brotherhood of Steel.}
{209}{}{For your dastardly betrayal, you were excluded from the Rangers.}
{210}{}{For your vile betrayal, you were excluded from the mainline.}
{211}{}{For your vile betrayal, you were excluded from the cult of Fire.}
{212}{}{After such a long journey, you have earned the title of a peace-loving wanderer.}
{213}{}{The title of the peace-loving wanderer is lost. But it is not too late to return to the righteous path.}