{100}{}{}
{101}{}{}
{102}{}{!Cheat: volumetric heads disabled.}
{103}{}{!Cheat: volumetric heads disabled.}

#Using items on the player character
{110}{}{A curious thing. You should find a way to use it.}
{111}{}{These items are better off used when you get to the surface.}
{112}{}{It feels nice to pay yourself. But pointless.}
{113}{}{You receive a bottle cap.}
{114}{}{It would be a better idea to sell it to city-dwelling upstarts.}
{118}{}{Use this item with your hands.}
{119}{}{Use this item with your hands or via the backpack.}

{120}{}{Seeing this junk, you can't help but get an idea... to set the world on fire again in another nuclear war.}
{121}{}{The update is meant exclusively for the hardware of ZAX supercomputers.}
{122}{}{It doesn't look like you're an atomic bomb.}
{123}{}{These passwords should be used on computers and other electronics.}
{124}{}{You tear the letter apart, trying to forget everything that linked you to the Fire-worshipper cult.}
{125}{}{This letter should be given to the Followers of the Holy Fire in Phoenix.}
{126}{}{Damn cultists...}
{127}{}{I don't want to remember them.}
{128}{}{Drinking this liquid pure is just going to give you indigestion.}
{129}{}{Hey, careful there! You almost cut your head off.}
{1129}{}{Hey, careful there! You almost cut your head off.}

{130}{}{Setting your head on fire isn't the best idea.}
{131}{}{You change your shoes. You can now safely walk on caustic substances, if only for a few minutes.}
{132}{}{There is no need to do this yet, as the shoes are currently in good condition.}
{133}{}{There is no need to do this yet, as the goggles are currently in good condition.}
{134}{}{You put on the strange goggles and flip the switch. Immediately, you feel like you have been transported to another dimension.}
{135}{}{The battery of the light amplification goggles has run out of energy. Night-vision disabled.}
{136}{}{Take the glasses with your hand to look fabulous.}
{1136}{}{Take the glasses with your hand to look fabulous.}
{137}{}{There is no need to do this yet, as the gas mask you are currently wearing is in good condition.}
{138}{}{You change your gas mask. For some time, it will protect you from dangerous gas and dust.}
{139}{}{You get an idea to put it on your head and scare village childen. That would be fun.}

#Dropping items
{140}{}{Your family members would be very dissapointed in you if they learned that you're droppin family relics like nothing.}
{141}{}{The poor will be very pleased to find the caps you dropped.}
{142}{}{Fancying yourself a philantropist, you generously throw money into the air.}
{143}{}{These sandals will help you stay alive in caustic substances, if not for long.}
{144}{}{Bait installed.}

#Various log messages
{150}{}{The radioactive item in your backpack produces a light heat.}
{151}{}{Your Pip-Boy shows you the irradiation level: }
{152}{}{Cannot be done during combat.}
{153}{}{Test. Test. Radio is fully operational.}
{154}{}{Your legs fail to support the incredible weight of the backpack.}
{155}{}{OW!}
{156}{}{I shouldn't have done that.}
{157}{}{That could have been very dangerous! Your recklessness almost led to your demise. Think about how sad grandma Adonsia would have been...}
{158}{}{Time for you to find more reliable clothing. This pair can be sold at the nearest marketplace.}
{159}{}{You will need a workbench to dismantle this item.}
{160}{}{You need to collect ALL map pieces.}
{161}{}{You have collected all the treasure map pieces. It appears to be buried near the ruins of a local lighthouse.} 

#Achievements
{200}{}{Your fame increases.}
{201}{}{Your infamy increases.}
{202}{}{The high dose of radiation has permanently reduced your health.}
{203}{}{A high dose of radiation has permanently reduced your health. Again.}
{204}{}{I'm feeling worse.}
{205}{}{I'm feeling MUCH worse.}
{206}{}{For surviving so many injuries received in such a large number of battles, you receive the achievement "Battle-hardened".}
{207}{}{I seem to be getting used to the pain.}
{208}{}{For your vile betrayal, the Brotherhood of Steel has stripped you of all your ranks.}
{209}{}{You have been expelled from the Rangers for your vile betrayal.}
{210}{}{You have been expelled from the Highwaymen for your vile betrayal.}
{211}{}{You have been expelled from the Cult of the Holy Fire for your vile betrayal.}
{212}{}{The difficulties you encountered over your long journey were harsh, but you always strived to avoid hurting others. You have rightfully earned the title of peaceful wanderer.}
{213}{}{You have lost the title of peaceful wanderer. But it's not too late to return to the righteous path.} 
