#Using items
{200}{}{This does not apply to the trunk. Try it on a motorcycle.}
{201}{}{Replacing the old mount, you have increased the capacity of the luggage compartment by 5 units.}
{202}{}{You have already replaced the fastening rope. Doing it again is pointless.}
{203}{}{This is hardly possible during combat.}
{204}{}{You have installed a new luggage container. Now the bike holds a larger load.}
{205}{}{There is no room for additional containers on the motorcycle.}
{206}{}{This bike doesn't belong to you.}

#Using skills
{300}{}{There's nothing to hack here.}
{301}{}{Having carefully measured the trunk, you come to the conclusion that its volume is }
{302}{}{ units.}
{303}{}{This luggage box will not improve with your skills.}
{304}{}{There is nothing to repair here.}
{305}{}{You cannot repair this bike until it’s yours.}
{306}{}{After the repair, the capacity of the luggage compartment increased by 5 units.}