{100}{}{There is a Shadow in front of you.}
{101}{}{You see a disfigured man with pale skin. He seems insane and aggressive.}
{102}{}{?}
{103}{}{I don't want to kill you. Don't make me.}

#Dialog
{200}{}{(walking along the cloaca, you feel someone's gaze on you; looking back, you immediately notice a pale shadow with a pair of shining eyes; the shadow begins to move dangerously)}
{201}{}{Stop! I won't hurt you...}
{202}{}{Who the hell are you?}
{203}{}{Stop! You won't leave, bitch!}

{210}{}{(in response, you hear only a short ominous mockery; suddenly the shadow makes a sharp throw ...)}
{211}{}{Ah...}
{212}{}{(in response, you hear a short ominous mockery; soon a man with a disfigured body and pale skin comes into the light; his hungry eyes seem to see right through you) W-a pathetic h-man.}
{213}{}{Look, you and I are alike. Look at me, at my face... People upstairs are laughing at my appearance.}
{214}{}{What are you talking about?}
{215}{}{(mockery) Stupid man. Don't resist.}
{216}{}{Er...}
{217}{}{They're laughing, right? It's true. We remember. People. The sun. A lot of bad words...}
{218}{}{Yes, yes, it's terrible there. Everyone is so angry.}
{219}{}{Looks like you've had a good time.}
{220}{}{They thought we wouldn't survive. But no-et. (laughter) Stupid people.}
{221}{}{So you were driven here by people from above?}
{222}{}{(face changes from bitter memories) War... Bombs... (baring his teeth, clutching his head) We remember! Houses are on fire. People are on fire. Moans. Screams. We are here to survive...}
{223}{}{Listen, it was a long time ago, wasn't it?}
{224}{}{Now I understand why you look like that.}
{225}{}{(looks sharply around) Lily! She got lost... (grabs her head, but suddenly remembers something) No, she's dead. I killed her... yes. She was suffering... I did what I had to do. Lily! Lily! (with a cry of "Lily!" runs away)}
{226}{}{Eh, have a good trip, Mr. Survivalist.}
{227}{}{That's right, run away from here, idiot.}