#---------------------------------------------------------
#  Translated by Georg; revised by garwert, nuk.
#---------------------------------------------------------
{100}{}{You see a shadow.}
{101}{}{You see a pale-skinned, horribly disfigured person. His twitching and aggressive growls do not paint a pleasant mental picture.}
{102}{}{?}
{103}{}{I don't want to kill you. Don't make me do it.}

#Dialogue
{200}{}{(walking through the sewers, you begin to feel like you're being watched; looking around, you notice a pale shadow... with a pair of faintly glowing eyes. Just as you notice it, the shadowy figure starts creeping closer)}
{201}{}{Wait! I mean no harm...}
{202}{}{What the hell are you?}
{203}{}{Stop right there! I will fucking get you!}

{210}{}{(you only hear a short sinister laugh mocking you in response; suddenly, the shadow leaps towards you...)}
{211}{}{Agh!...}
{212}{}{(you only hear a short sinister laugh mocking you in response; shortly after, you see a disfigured, pale-skinned man step into the light; his hungry eyes looking as if they can see right through you) P-pathetic h-human.}
{213}{}{Listen, you and I... we have a lot in common. Just look at me; look at my face... The surface-dwellers laugh at the way I look.}
{214}{}{What are you talking about?}
{215}{}{(laughter) Silly human. Do not resist.}
{216}{}{Ugh...}
{217}{}{Mhmm... They laugh, yes? It is the truth. We remember. People. The sun. So many bad words...}
{218}{}{Oh yes, it's terrible out there. Everyone is so awful.}
{219}{}{Looks like you've been through a lot.}
{220}{}{They thought we wouldn't survive. But no-no-noh. (laughter) Silly humans.}
{221}{}{So the surface people forced you down here?}
{222}{}{(as bitter memories resurface, he becomes visibly distraught) The War... The bombs... (clutching his head, he grinds his teeth) We remember! Buildings on fire. People on fire. Moans. Screams. Here, here we can survive...}
{223}{}{But that was a very long time ago, was it not?}
{224}{}{Now I see why you look like that.}
{225}{}{(expression suddenly shifting from anguish to alert, he begins looking around with agitation) Lily! She got lost... (clutches his head, remembering something) Oh no, no-no-no... She's dead. I did kill her... yes. She was suffering... suffering... I did what I had to do. Lily! Lily! (runs away, repeatedly screaming the name)}
{226}{}{Uh, so long, Mr. Survivalist.}
{227}{}{That's right, scurry outta here, weirdo.}
