#---------------------------------------------------------
#  Translated by Georg; revised by garwert, nuk.
#---------------------------------------------------------
{100}{}{You see an atomic worker.}
{101}{}{You see a person covered in old burns. He is wearing is a visibly aged, tattered uniform with a pre-War symbol on it.}
{102}{}{Thanks for patching me up, doc. I really appreciate it.}
{103}{}{I've got a problem here, you see. Any chance you could recommend a doctor?}

{200}{}{Golly, I'm really grateful for that. Didn't think there were any doctors left around these days.}
{201}{}{How did you manage to end up like that?}
{202}{}{When we were repairing broken pipes, the pressure blasted me away into the railing. I'm lucky I didn't fall to the bottom level. Then I would have been swimming around in radioactive goo like a goldfish in a bowl.}
{203}{}{Sounds like you've had a stroke of luck back there. So long.}
{204}{}{You must've been born with hard luck. Bye.}
{205}{}{A goldfish?}
{206}{}{Well, you know, some of us had pet fish back then. Before the atomic war. I'm sure no one keeps them anymore - I sure as hell haven't seen one in a long, long while. Wouldn't be surprised if they went extinct. Like the dinosaurs...}
{207}{}{Dino-sores?}
{208}{}{Eh, never mind.}

{210}{}{Hey, doc. Thanks again.}
{211}{}{Take care.}
