{100}{}{Here is Ralph.}
{101}{}{You see a man with burnt skin. He is wearing well-worn work clothes with a pre-war symbol.}
{102}{}{I have nothing to do with traitors.}
{103}{}{Thanks for the help. She was very helpful.}

{200}{}{Wait, strangers can't go any further. What do you need?}
{201}{}{I thought this place had been abandoned for a long time. What are you doing here?}
{202}{}{We have been living here for many years. But the whole city knows about it. So I don't advise you to lie anymore.}
{203}{}{But I'm not a local. I'm from a village northeast of here.}
{1203}{}{But I'm not local. I'm from a village northeast of here.}
{204}{}{Oh, that's a surprise. You really don't look like an ordinary citizen - your skin is tanned, your accent is unusual. Curious...}
{1204}{}{Oh, this is a surprise. You really don't look like an ordinary citizen - your skin is tanned, your accent is unusual. Curious...}
{205}{}{Hmm. Let me just leave.}
{206}{}{Why is that?}
{207}{}{Okay, listen, we have an emergency here. Maybe you can help. Go to the manager, and then - as you agree.}
{208}{}{OK.}

{210}{}{Wait, what... Is that makeup?}
{211}{}{This is real leather. A little green, but you can live.}
{212}{}{With such jokes, you are seriously risking.}
{213}{}{But I'm telling the truth. It's all because of the experiments in Inferno. They are real madmen.}
{214}{}{Damn it, but it's true. I don't remember what I looked like before the Transformation. It must have been hard for you. Glad to meet you.}
{215}{}{Oh, so I'm welcome here now? Well, of course.}
{216}{}{Mutually. So you live here?}
{217}{}{I haven't introduced myself yet. My name is Ralph. I am, one might say, Theodore's right-hand man. Sorry for the cold reception, but we haven't been in the mood for pleasantries lately.}
{218}{}{Can I ask you a few questions, Ralph?}

{220}{}{Hello again.}
{221}{}{See you again.}

{230}{}{Has this station been operating since before the war?}
{231}{}{It has been preserved for a long time. And only recently it was possible to start the main reactor.}
{232}{}{How did it work out?}
{233}{}{Thank the fire worshippers and their colony in Flagstaff for this. Uranium is mined there on the church lid. And some of this uranium comes to us. It was a profitable contract for the whole city.}
{234}{}{Wow, it turns out that people in the church don't just pray.}
{235}{}{It would be better to feed the people than to force slaves to work ore.}
{236}{}{How did you all end up here?}
{237}{}{We came from the west, from California. But this is a separate story. Coincidentally, we were offered to restore the station. After all, you, the modern generation, don't know a damn thing about the old technology.}
{238}{}{Wait a minute, do you really mean to say that you have lived for a hundred years?}
{239}{}{Well preserved, aren't they? Our favorite joke. They say that the cause of our mutation was some kind of virus that accidentally got into the air during the bombing of the old laboratory. But these are just rumors.}
{240}{}{Tell me, what was the world like before the war?}
{241}{}{Hmm... A hundred years have passed, much is in a fog. I remember cars, skyscrapers and military checkpoints. I remember the war when the bombs fell on the city. But is it possible to explain all this to a person like you? It's just a story for you.}
{242}{}{I see it's hard for you to remember this. Let's change the subject.}
{243}{}{Are you trying to humiliate me now? Not another word, Mr. Pockmarked Skin.}
{244}{}{Your boss says the pipeline was blown up. What do you think about it?}
{245}{}{Wow, that's a strong word. Don't take that old man's words into your head. He's losing his mind a little.}
{246}{}{But he has to pay me for the work.}
{247}{}{Then do what he says. He needs the culprits - find them. How to do it? That's bad luck... You know, most likely the bombers penetrated through the sewers. But I thought we sealed all the entrances well.}
{248}{}{Good idea. This needs to be checked.}
{249}{}{Most likely, the bombers penetrated through the sewers. But it seemed to me that we had sealed all the passages well.}

{250}{}{Fiend of the Electromagnetic Hell, disappear! Everything was going well while you were away.}
{251}{}{The game is over, Ralph. You've lost. }
{252}{}{Oh no, we just started the fun. Now you will see the real power of the Old World!}
{253}{}{Don't, don't do this...}
{254}{}{It's worse for you, you idiot.}
{255}{}{Listen to me, Ralph. Everything was bad from the very beginning. You were used.}
{256}{}{This is a mutually beneficial contract. Only fire worshippers could give the station a new life and revive a piece of the Old World. No one else had the knowledge and resources to do this. And old Theodore is just losing his mind. It's scary to think how this story will end under his leadership.}
{257}{}{Even so, you won't get out of here alive.}
{258}{}{Yes, the church does not care about all of you and the world around you. Don't you see?}
{259}{}{Enough of this chatter! Now you will see the real power of the Old World.}
{260}{}{I understand you. You want to bring back the old world that you knew. But look around - fire worshippers create another world.}
{261}{}{Another... Yes. Aaron is just using them to create an empire. I didn't think about it. But if you think about it... Damn it, what should I do? Go back to ruined California? Or go with the guys to the east? Who knows, maybe it will be possible to find oil in Texas or restore the old Chrysler Motors plants.}
{262}{}{Believe me, they won't let you live here. You will become only a weapon in the hands of the emperor.}
{263}{}{To hell with it. You can't let a schizoid like you go. You will die here and now.}
{264}{}{That's a strong word. I'll leave. Peacefully. Tell Theodore to remove the guards from the doors.}
{265}{}{A reasonable solution, Ralph.}
{266}{}{Your boss suggested I fix the cooling system. Can you tell me where to start?}
{267}{}{What is this old man thinking about, letting a stranger into the very heart of the station? Okay, let's see. First, inspect the damage on the lower level. We will need materials and equipment for repairs. The easiest way to get them is at the tinsmith factory. It's somewhere to the south of the city, the caravaneers should know for sure.}
{268}{}{Thank you.}

{270}{}{I know that the cardinals acted through you. There was information about this in the Cathedral.}
{271}{}{Keep your voice down, there's no need for such rudeness. So, let's go to a secluded place...}
{272}{}{[Next]}
{273}{}{I understand that you have connections with the fire worshippers, otherwise how did you get information about our secret contract?}
{274}{}{I have a lot of connections. But what are you trying to achieve? Do you want to take your boss's place?}
{275}{}{What narrow-minded motives. Don't forget that I'm a hundred years old. If we were in the Old World, I would crave a career promotion. But what do we have now? The devastation, the lack of transport and roads, even street lighting, people saw only thanks to us and the Church of Fire.}
{276}{}{Isn't the church sponsoring you with uranium?}
{277}{}{That's not enough. Theodore doesn't let them go to the station's affairs, and without them, business is moving too slowly. At first it seemed like a purely technical matter - they took uranium and got energy from it. Now comes the time of the economy, business and taxes. Theodore does not understand anything about this and believes that it is enough just to sell energy left and right.}
{278}{}{So you want to renegotiate the contract. What about Theodore?}
{279}{}{The problem is that the old man is out of his mind, but there are workers behind him. I need to be at the helm of the station for something to change. Help me. Get rid of Theodore, and you will receive a reward and respect. Moreover, you will do a useful thing for the whole city.}
{280}{}{I'll think about it.}
{281}{}{My plan has already partially failed because you fixed the cooler. Don't let me down this time.}
{1281}{}{My plan has already partially failed because you fixed the cooler. Don't let me down this time.}
{282}{}{Bye.}
{283}{}{We've already discussed everything. Don't disappoint me again.}
{284}{}{Bye.}
{285}{}{But how do I eliminate Theodore? This is a dangerous task.}
{286}{}{I've been thinking about it. An open murder will cause too much controversy and suspicion. Try mixing poison from strong drugs. The old ghoul's heart probably won't stand it.}
{287}{}{Good idea. There was a pusher somewhere in the slums.}
{288}{}{It's done. The stationmaster's post is yours now.}
{289}{}{The angel of the Electromagnetic Pulse must have sent you to us. Thank you. You did the right thing. Now go to the storekeeper and ask him for a reward. He'll find something to thank you with.}
{1289}{}{The angel of the Electromagnetic Pulse must have sent you to us. Thank you. You did the right thing. Now go to the storekeeper and ask him for a reward. He will find something to thank you with.}
{290}{}{Goodbye, Ralph.}

{291}{}{I heard that you are getting uranium from Flagstaff.}
{1291}{}{I heard that you are getting uranium from Flagstaff.}
{292}{}{Not quite. We get fuel elements with uranium filling, and they are produced in the south. Uranium ore is also being transported there. And what?}
{293}{}{Does it bother you that this ore is mined by slave labor?}
{294}{}{We don't care who gets it and how. We need uranium, and the rest is not our concern.}
{295}{}{Hmm. It makes sense. But you are still indirectly guilty.}
{296}{}{I understand. It's just business.}