{100}{}{Here is an atomist.}
{101}{}{You see a man with burnt skin. He is wearing well-worn work clothes with a pre-war symbol.}
{102}{}{Well, well, and here is our main pest. Get out of here while your legs are intact.}

{110}{}{Shh, the stranger will hear.}

{200}{}{Hey, hello, tramp. Strangers are rarely allowed in here.}
{201}{}{Do you have a pass? Okay, whatever.}
{202}{}{Yes, look around. It's interesting here.}
{203}{}{What are you sniffing around for?}
{204}{}{Eh? Speak up, I'm a little deaf.}
{205}{}{The entrance to the station is prohibited. But you can pass.}
{206}{}{It's strange that they let you in. You know, all these racists...}
{207}{}{We don't look like this from a good life, baby.}