{100}{}{You see an atomist.}
{101}{}{You see a man with burnt skin. He is wearing well-worn work clothes with a pre-war symbol.}

{200}{}{Holy Om! Don't scare me like that. You with your pale skin wander around the station like a ghost...}
{201}{}{There are people here who look like they're. But it's not me.}
{202}{}{Sorry, I had no idea of scaring anyone.}
{203}{}{Haha. Never mind, we can only laugh at death... I'm Herbert, the warehouse manager.}
{204}{}{Warehouse? So, you probably have something useful.}

{210}{}{What do you need, tramp?}
{211}{}{Nothing today. Bye, Herbert.}
{212}{}{Do you have anything for sale? I could use a couple of charged batteries.}
{213}{}{Sorry, but we only trade with caravans with which a contract has been concluded. And we have almost nothing but energy.}
{214}{}{Clearly. Bye, Herbert.}

{220}{}{Your boss promised to pay me for the job.}
{221}{}{Yes, yes, I remember. You can choose a reward.}
{222}{}{Let me think a little. I'll be back soon.}
{223}{}{Well, sign here and here. Come on, I'm kidding. You probably don't even know how to write. By the way, if you need batteries, contact us. The boss says it's okay to trade with you.}
{224}{}{I'll remember that. Bye, Herbert.}
{225}{}{250 caps.}
{226}{}{Laser gun.}
{227}{}{Radaway, 3 pcs.}