{100}{}{You see an atomist.}
{101}{}{You see a man with burnt skin. He is wearing well-worn work clothes with a pre-war symbol.}
{102}{}{Thanks, Doc. Thank you very much.}
{103}{}{I have a problem here, you know. Don't you know a doctor?}

{200}{}{Hey, thank you very much. I didn't think that there were still doctors in our time.}
{201}{}{How did you manage it?}
{202}{}{It was when we were repairing the broken pipes that the pressure threw me onto the railing. It's good that at least he didn't fly to the lower level. He would have been dangling in the radioactive sludge, like a duck in an ice hole.}
{203}{}{You're definitely lucky. Well, come on.}
{204}{}{You're a born loser. Bye.}
{205}{}{Duck?}
{206}{}{Well, you know, the bird was like that. Even before the nuclear war. I haven't seen a single live duck since. Probably died out like a dinosaur...}
{207}{}{A dinosaur?}
{208}{}{Oh, okay, let's go.}

{210}{}{Hey, Doc. Thanks again.}
{211}{}{Don't hurt.}