{100}{}{You see Ralph.}
{101}{}{You see a person with burned skin. On him is a very old, tattered uniform with a Pre-War symbol.}
{102}{}{I do not deal with traitors.}
{103}{}{Thank you for your timely help.}

{200}{}{Stop. Outsiders can go no further. What do you need?}
{201}{}{I thought this place was abandoned a long time ago. What do you do here?}
{202}{}{We've been living here for many years. But the entire city knows about that. So I suggest you stop lying.}
{203}{}{But I'm not a local. I'm from a village to the north-east.}
{1203}{}{But I'm not a local. I'm from a village to the north-east.}
{204}{}{Oh, what an unexpected surprise. Now that I think about it, you really don't look like a local - tanned skin, an unusual accent. Interesting...}
{1204}{}{Oh, what an unexpected surprise. Now that I think about it, you really don't look like a local - tanned skin, an unusual accent. Interesting...}
{205}{}{Hm. I should just leave this place.}
{206}{}{Why?}
{207}{}{Fine, listen, we have an emergency situation here. Maybe you will be able to help. Go to the manager, and then do whatever you agree to.}
{208}{}{Good.}

{210}{}{Wait, what the... Is that... makeup?}
{211}{}{It's real skin. It's a bit green, but you can live in it.}
{212}{}{You're taking a serious risk making these jokes.}
{213}{}{I'm telling you the truth. I was subjected to experiments in Inferno. They're real madmen.}
{214}{}{Dammit, you *are* telling the truth. I don't even remember how I myself looked before the Transformation. I suppose it was not easy for you. It's good to see you.}
{215}{}{Ah, so now that I have green skin like you, you like me? Of course. Of course.}
{216}{}{The feeling is mutual. So, you live here?}
{217}{}{I haven't even introduced myself. My name is Ralph. I suppose you could say I'm Theodore's right hand. I apologize for the cold welcome, but in these times, politeness becomes a secondary priority.}
{218}{}{Can I ask you a couple of questions, Ralph?}

{220}{}{Hello again.}
{221}{}{We'll see each other again.}

{230}{}{Is this plant really working since before the War?}
{231}{}{For a long time, it was preserved. And only recently have we managed to activate the main reactor.}
{232}{}{How did you do it?}
{233}{}{Thank the Fire-worshippers and their colony in Flagstaff. There, uranium is mined thanks to the cathedral's caps. And part of that uranium goes to us. It was an arrangement beneficial to the whole city.}
{234}{}{Oh wow, it turns out people in the cathedral don't spend all their day praying.}
{235}{}{They should feed the people before making slaves mine ore.}
{236}{}{So, how did you all end up here?}
{237}{}{We came from the west, from California. But that's another story. It so happened that we were offered to restore the plant. Since you, the current generation don't know jack shit about old technology.}
{238}{}{Wait, are you saying that you've been living here for a hundred years?}
{239}{}{We aged rather well, wouldn't you agree? It's our favourite joke. They say the reason for our mutation was some kind of virus that ended up in the air by mistake when an old laboratory was bombarded. But these are just rumours.}
{240}{}{Tell me, what was the world like before the War?}
{241}{}{Hm... A hundred years have passed, much in our memories is covered in fog. I remember automobiles, skyscrapers and military checkpoints. I remember the War, when the bombs dropped upon the city. But how could that all be explained to a person like you? For you, it's just a story.}
{242}{}{I see that it is hard for you to remember things like these. Let's change the subject.}
{243}{}{Are you trying to humiliate me? Silence, Mr. Pockmarked.}
{244}{}{Your boss says me the pipeline was blown up. What do you think of this?}
{245}{}{Wow, that's heavy stuff. Don't pay attention to what that old man says, what's left of his mind is slowly deteriorating.}
{246}{}{But he's supposed to pay me for the job.}
{247}{}{Then do what he says. He needs those responsible - find them. How? That's a bit problematic... You know, it's most likely that whoever blew it up went here through the sewers. But I thought that we sealed all entrances well.}
{248}{}{Good idea. I should check that.}
{249}{}{It's most likely that whoever blew it up went here through the sewers. But I thought that we sealed all entrances well.}

{250}{}{Fiend of Electromagnetic Hell, vanish! Everything was going well until you showed up.}
{251}{}{Game over, Ralph. You lost.}
{252}{}{Oh no, the fun's just starting. Now you'll see the true power of the Old World!}
{253}{}{Don't do it, don't...}
{254}{}{Your funeral, imbecile.}
{255}{}{Listen to me, Ralph. The game was rigged from the start, you were used.}
{256}{}{It was a mutually beneficial contract. Only the Fire-worshippers could have bigen the power plant life and restore a piece of the Old World. Nobody else had the knowledge or resources to do something like this. Old man Theodore has little to no mind left. It's scary to think how this story will end under his leadership.}
{257}{}{Even if so, you're not walking out of here alive.}
{258}{}{The cathedral spits on you and the world around them. Don't you see?}
{259}{}{Enough of this chit-chat! Now you'll see the true power of the Old World.}
{260}{}{I understand you. You want to return the old world that you know. But look around, the Fire-worshippers, they're creating a different world.}
{261}{}{Different... Yes. Aaron is simply using us to create an empire. I didn't think about that. But if you think about it... Dammit, what will I do now? Head back to what remains of California? Or go with the others to the east? Who knows, maybe we'll find oil in Texas or restore the old "Chrysalis Motors" factories.}
{262}{}{Belive me, you won't be allowed to live here. You'll just become a weapon in the hands of an emperor.}
{263}{}{To hell with that. I can't let out a schizoid like you. You will die here and now.}
{264}{}{Strong words. I'll leave. Peacefully. Tell Theodore to remove the guards near the doors.}
{265}{}{Wise choice, Ralph.}
{266}{}{Your boss has offered me to fix the cooling system. Can you give me a tip where to start first?}
{267}{}{What the hell is that old man even thinking, letting an outsider into the very heart of the plant? Fine, let's see. First, examine the damage at the lowest level. You'll need materials and equipment for repairs. Easiest place to get them is the factory with scavengers. It's somewhere south from the city, the caravaneers should know.}
{268}{}{Thanks.}

{270}{}{I know that the Cardinals acted through you. The Cathedral contained that information.}
{271}{}{Talk quietly, no need for such insults. Now, let's head to a secluded place...}
{272}{}{[Continue]}
{273}{}{So, as I understand, you have connections with the Fire-worshippers, otherwise, where could you get the information about our secret arrangement?}
{274}{}{I have a lot of connections. And what are you trying to achieve? You want to take your boss' place?}
{275}{}{What narrow-minded motives. Don't forget that I'm a hundred years old. If we were in the Old World, I would want promotions in my career. But what do we have now? Collapse, the lack of transport and roads, even streetlight only work because of us and the Church of the Fire.}
{276}{}{Doesn't the church supply you with uranium?}
{277}{}{It's not enough. Theodore doesn't allow them to interfere with the inner workings of the plant, and without them, business is moving at a very slow pace. At first, it seemed like a purely technical task - we take uranium and get energy out of it. Now comes the time of economics, business and taxes. Theodore doesn't understand anything there and thinks that it's enough to just sell energy left and right.}
{278}{}{So you want to change the arrangement. What about Theodore?}
{279}{}{The problem is that his mind hasn't aged well, but the workers support him. I need to take control of the plant if something is to change. Help me. Get rid of Theodore and you'll receive a reward and respect. Furthermore, you'll do a great thing for the whole city.}
{280}{}{I'll think about it.}
{281}{}{My plan has already partially failed because you fixed the cooling system. Don't let me down this time.}
{1281}{}{My plan has already partially failed because you fixed the cooling system. Don't let me down this time.}
{282}{}{Bye.}
{283}{}{We have already discussed everything. Don't dissapoint me again.}
{284}{}{Bye.}
{285}{}{But how do I get rid of Theodore? It's a dangerous mission.}
{286}{}{I thought about it. An open murder would cause too much arguing and suspicion. Try to make a poison from several strong drugs. The old ghoul's heart is unlikely to survive that.}
{287}{}{Good idea. There was a pusher in the slums, I'll go to him.}
{288}{}{The deed is done. The position of the manager of this power plant is yours.}
{289}{}{The angel of the Electromagnetic Impulse must have sent you. Thank you, you did the right thing. Now go to the stockman and ask for a reward. He'll find something to thank you with.}
{1289}{}{The angel of the Electromagnetic Impulse must have sent you. Thank you, you did the right thing. Now go to the stockman and ask for a reward. He'll find something to thank you with.}
{290}{}{Goodbye, Ralph.}

{291}{}{I heard you get your uranium from Flagstaff.}
{1291}{}{I heard you get your uranium from Flagstaff.}
{292}{}{Not quite. We get heat-generating elements with a uranium filling, they are produced in the south. Uranium ore is also brought there. Why are you asking?}
{293}{}{Aren't you concerned that the ore is being mined by slaves?}
{294}{}{We don't care who and how it is mined. We need uranium. Anything else is not out concern.}
{295}{}{Hm. That makes a bit of sense. But you are all still indirectly guilty.}
{296}{}{I see. It's just business.}
