{100}{}{You see a monk.}
{101}{}{You see a man covered in robes. He is definitely not here by accident.}
{102}{}{Your place is in the desert, savage.}
{1102}{}{Your place is in the desert, savage.}
{103}{}{Holy Flame bless you.}
{104}{}{By staying here, you risk ending up in punitive fire.}

{200}{}{Greetings, kind man. May I learn how your path entangled with the inhabitants of this nuclear power plant?}
{201}{}{I don't even know. By accident, maybe. What are you doing here?}
{202}{}{Oh, I am simply a peaceful pilgrim of the Church of the Holy Flame. Our religion bows down to old knowledge and aims to revive the world. This nuclear plant is very important for our mission. It would be very unfortunate if it ended up in the wrong hands.}
{203}{}{I don't think you have anything to fear. Ralph is now the head of the power plant. He intends to sign a contract with the Church once again. You will be pleased, I think.}
{204}{}{Thank the Atom! I suppose we must thank you for this? The world is improving thanks to your help. Thank you, stranger. Visit our church when you have the time.}
{1204}{}{Thank the Atom! I suppose we must thank you for this? The world is improving thanks to your help. Thank you, stranger. Visit our church when you have the time.}
{205}{}{Of course. Goodbye.}

{250}{}{So it is because of you our plans have collaped, much like the Old World? Why are you doing this?}
{251}{}{I don't like you.}
{252}{}{Do you not like the idea of Revival? Or do you not like our Church due to it's symbols? In any case, you are simply an egoist. A worthless molecule with a heightened value of itself. The Church has given the world Knowledge. With it's help, we brought illumination into homes and knowledge of things forgotten into people's minds. And you? What are you aiming for?}
{253}{}{Your "revival" emptied my home. That is reason enough.}
{254}{}{So, your motivation is revenge. An animalistic implulse. In that case, I have nothing more to say to you. Animals don't understand words. Only the whip. Get out of here back into your desert and continue your primitive, savage way of life. The New World has no place for those like you.}
{255}{}{Not before I beat all this crap out of you.}
{256}{}{With pleasure. I don't want to remain in such a sinful place any longer.}
{257}{}{Ralph paid less.}
{258}{}{Bottle caps have become your trusted advisors? In that case, you are a regular egoist. The Church has given the world Knowledge. With it's help, we brought illumination into homes and knowledge of things forgotten into people's minds. What will a handful of bottle caps give your town?}
{259}{}{I am simply fulfilling a deal. This is an honest contract.}
{260}{}{The Old World fell due to the greed of people like you. And that is why the New World has no place for them. From this moment forward, your presense in the city is not wanted by the Church of the Flame. It will be best for everyone if you simply leave.}
{261}{}{Not before I beat all this crap out of you.}
{262}{}{With pleasure. I don't want to remain in such an unjust place any longer.}
{263}{}{You won't know that if you're dead.}