#---------------------------------------------------------
#  Translated by Georg; revised by garwert, nuk.
#---------------------------------------------------------
{100}{}{You see an atomic worker.}
{101}{}{You see a person covered in old burns. He is wearing is a visibly aged, tattered uniform with a pre-War symbol on it.}
{102}{}{Well, well, well, if it ain't our little vermin. Get out. Right now, while your kneecaps are still intact.}

{110}{}{Shhh! The outsider is going to h-hear you.)

{200}{}{Oh. Hey there, wanderer. We don't let many outsiders in here.}
{201}{}{Do you have an entry pass?... Eh, whatever.}
{202}{}{Ah yes, look around. It's interesting in here.}
{203}{}{What are you snooping around here for?}
{204}{}{Huh? Speak up, I'm a bit on the deaf side.}
{205}{}{The power plant is off-limits. But you can go in, sure.}
{206}{}{It's strange to see how someone like you was allowed in. You know, considering all the racism...}
{207}{}{Listen, baby: the life we live ain't sweet. There's a reason we look like this.}
