{100}{}{You see Theodore.}
{101}{}{You see a person with burned skin. On him is a very old, tattered uniform with a Pre-War symbol.}
{102}{}{Security! Intruder!}
{103}{}{We'll talk when Ralph meets Electromagnetic Retribution.}
{104}{}{I have a lot of work to do, but thank you for visiting such an old man as myself. By the way, who are you?}
{105}{}{Oh, I do not feel good...}

{110}{}{   }
{111}{}{Boss! Theodore! There's trouble!}
{112}{}{What in Atom's name happened? I'm trying to sleep here...}
{113}{}{Ralph and the others have locked themselves in the control room. He isn't kidding around!}
{114}{}{Ralph? I told you to bring him to me. BRING. HIM. TO. ME. Do I have to repeat myself?}
{115}{}{No, boss, but it's not just that he's locked in there, he isn't letting anybody else enter. We've got to do something!}

{200}{}{Well, well, well. The first messenger of evil arrives. Or maybe not? Looks like I've started messing up the days of the week. I really do need to get that clock working.}
{201}{}{Uhh, I don't know what you're talking about. I'm new here, I'm looking for my relatives.}
{202}{}{Hmm, really? Well, yes, I saw many people over the course of a century. Excuse my skepticism, but in these times it's very important to tread lightly.}
{203}{}{Did something go wrong?}
{204}{}{The pipes going to the reactor cooling system exploded. They burst open like a vile worm. We cut off the coolant supply, but the reserves won't last long. The reactor will overheat at times, and we will eventually have to shut it down.}
{205}{}{Doesn't sound good at all. Can it be repaired?}
{206}{}{Of course. But not by us. This is a nuclear power plant, not a factory. We need components and equipment, and to find them, one will have to search hard. Could you do it? You will be compensated.}
{207}{}{I have no experience in that kind of work.}
{208}{}{Neither do I, he-he. Just bring us the materials for repair. I think there's a functioning factory somewhere to the south. Ask the locals.}
{209}{}{I'll think about it.}
{210}{}{It's too far away and not in the direction I was already going. Sorry.}
{211}{}{Of course. I'm always up for earning some money.}
{212}{}{Great, I'm counting on you. Go, but don't tell anyone about our little deal... Hm-m. Re-e-volting seaworms. They want to lunge right at you, with their razor-sharp teeth.}
{213}{}{Uhh... Goodbye.}
{214}{}{But don't tell anyone about our deal. Especially those crazy fire-worshippers.}

{220}{}{Yes, yes, I'm listening.}
{221}{}{Goodbye.}
{222}{}{I'm awaiting results. Don't forget that you'll be given compensation for doing this job.}

{230}{}{Can I ask you a couple of questions about this plant?}
{231}{}{Don't waste my time. Just letting you in was already a favor.}
{232}{}{Alright.}
{233}{}{I fixed the cooling system.}
{234}{}{By Amper, you did it! I can't believe it! How did you do it?}
{235}{}{Well, I had to spend an entire day working with this piece of junk.}
{236}{}{Singing like a bird, smoothskin. Your arrival coinciding with the sabotage can't be a mere coincidence.}
{237}{}{Uhh, what sabotage?}
{238}{}{We studied the wreckage. And what did we find? The system was blown up with dynamite. How do you explain that, my little slippery smoothskin friend?}
{239}{}{Uhh, I had nothing to do with it. It was you yourself who let me in, and then there also was the...}
{240}{}{Enough with talking people to death, my dear. Let me tell you this - you find those responsible for this. And only then will I decide whether to pay you or not.}
{241}{}{Gimme my caps, old man, or you'll go meet your great-grandparents.}
{242}{}{My great-grandparents are long-dead. I don't see how I could meet them. Well, in any case, that plant undoubtedly had many ways for malefactors to get in without anyone noticing.}
{243}{}{You are thinking correctly. Now go and do not return without information. Ha-ha-ha, I'll be merrily walking with a single leg!}
{244}{}{O-kay... uhh, I'll be going. Goodbye.}
{245}{}{I know the law! What about you? Pay some respect to an officer on duty.}
{246}{}{Uhh... What?}
{247}{}{Get over here, you decrepit puppet, and I'll fix your brain up.}

{250}{}{I know who blew up the cooling system.}
{251}{}{Oh, how intriguing. It's like I'm in a real detective story... So who was it?}
{252}{}{I have no idea - which is why I am in a state of absolute despair. I better go drown it in alcohol to ease the pain.}
{253}{}{The sabotage was commited by the Red Cardinals on behalf of the Fire-worshippers. A devoted assistant of yours has been helping them. His name is Ralph.}
{254}{}{Dammit! Why would *he* get involved in this?}
{255}{}{I have no idea, but it's the truth.}
{256}{}{The Cathedral has been trying to make you accept a one-sided contract. But Ralph... He thinks the time has come for him to take the role of managing the plant.}
{257}{}{Guards! Bring Ralph to me. And don't let your guard down around him, don't let him talk you into anything... He's crazy. Just like an overripe cherry. Can you even comprehend how much effort it took to launch this plant?}
{258}{}{I don't care in the slightest...}
{259}{}{Let me guess. A lot.}
{260}{}{Oh yes, very much so - it was all work and no play. Ralph thinks the cultists would run things better if they were in charge. But as a former officer, I know better than to let people with convictions anywhere near power. Oh, how I love giving people fines for walking in restricted areas. I feel so... powerful.}
{261}{}{I see...}
{262}{}{The fuck you talking about?}

{270}{}{What does that debauched old man have on his mind? Listen, go deal with Ralph. This case is becoming too dangerous.}
{271}{}{I'll do it, sure.}
{272}{}{It would be prudent to speak to him first.}

{280}{}{It's an honor to meet our nuclear power plant's hero. It's a shame I ran out of rewards. But don't fret. I know what will make you happy. Go to the quartermaster and ask him to receive anything you want from the warehouse.}
{1280}{}{It's an honor to meet our nuclear power plant's heroine. It's a shame I ran out of rewards. But don't fret. I know what will make you happy. Go to the quartermaster and ask him to receive anything you want from the warehouse.}
{281}{}{Happy to help.}
{1281}{}{Happy to help.}
{282}{}{After all I've seen, I don't understand how you even survived this long with such madness. Let alone manage a power plant.}
{283}{}{What did you say? Miasma? It's a serious problem, yes. I try to wash myself, but the smell only intensifies. You should worry more about your own personal hygiene.}
{284}{}{Goodbye, old man.}
{285}{}{I hope we never meet again.}