{100}{}{Here is Theodore.}
{101}{}{You see a man with burnt skin. He is wearing well-worn work clothes with a pre-war symbol.}
{102}{}{Security! An outsider!}
{103}{}{We'll talk when Ralph is overtaken by Electromagnetic Retaliation.}
{104}{}{I have a lot to do. But thanks for visiting Grandpa. By the way, who are you?}
{105}{}{Oh, I don't feel well...}

{110}{}{   }
{111}{}{Boss! Theodore! Trouble!}
{112}{}{What happened? I'm trying to sleep here...}
{113}{}{Ralph and the others locked themselves at the control panel. And he's not joking!}
{114}{}{Ralph? I asked you to bring him to me. for me. Repeat?}
{115}{}{No, Chief, he's locked himself in and won't let anyone in there. We have to do something!}

{200}{}{Well, well. And here is the first messenger of evil. Or not? I'm getting confused about the days of the week, I need to wind up the clock.}
{201}{}{Um, I don't understand what you're talking about? I'm in town recently, looking for my family.}
{202}{}{Hmm, really? Well, yes, I've seen a lot in a hundred years. Sorry for the skepticism, but it's very important to be careful right now.}
{203}{}{Did something happen?}
{204}{}{The pipeline from the reactor cooling system exploded. Burst like a nasty worm. We've cut off the liquid supply, but there won't be enough reserves for a long time. The reactor will overheat from month to month and sooner or later it will have to be turned off.}
{205}{}{Doesn't sound very good. Can it be fixed?}
{206}{}{Sure. But not by our forces. This is a nuclear power plant, not a factory. We need parts and equipment, and we'll have to do a good job of finding them. Can you handle it? Our payment is timely.}
{207}{}{I don't understand it.}
{208}{}{Me too, hehe. Just bring us the materials to fix it. It seems there is an operating factory somewhere in the south. Ask around the locals.}
{209}{}{I'll think about it.}
{210}{}{It's too far and out of the way. Sorry.}
{211}{}{Sure. I always want to earn money.}
{212}{}{Fine, I'm counting on you. Go, but don't tell anyone about our agreement... Hmm. M-nasty sea worms. They are trying to pounce on you with their copper teeth.}
{213}{}{e... Goodbye.}
{214}{}{But don't tell anyone about our agreement. Especially those crazy fire worshippers.}

{220}{}{Yes, yes, I'm listening.}
{221}{}{Goodbye.}
{222}{}{I'm waiting for the results. Don't forget that this job is paid.}

{230}{}{Can I ask a couple of questions about this station?}
{231}{}{Don't waste my time. I've already done you the courtesy of letting you in.}
{232}{}{Okay.}
{233}{}{I managed to fix the cooling system.}
{234}{}{Thank Ampere, you succeeded! I can't believe it, and how did you do it?}
{235}{}{Well, I had to tinker with this hardware all day.}
{236}{}{You sing sweetly, smooth skin. It can't be that your appearance coincidentally coincided with a diversion.}
{237}{}{Uh, sabotage?}
{238}{}{We studied the wreckage. So what? The system was deliberately blown up with dynamite. How do you explain this, my slippery pale-skinned friend?}
{239}{}{Uh, I have nothing to do with it. You let me in yourself and then...}
{240}{}{Enough of these soporific speeches, dear. I'll tell you what - find the culprits who are behind the terrorist attack. And only then will I decide whether to pay you or not.}
{241}{}{Give me my bottlecaps, old man, or you'll go to your forefathers.}
{242}{}{How am I going to do that? However, such a station probably has a lot of moves for the secret penetration of intruders.}
{243}{}{You're thinking right. Now go and don't come back without information. U-ha-ha, I'll have fun treading on one foot!}
{244}{}{OK... Uh, I'll go. Goodbye.}
{245}{}{I know the laws! And you? So do not contradict the officer on duty.}
{246}{}{E... What?}
{247}{}{Come here, you decrepit doll, now I'll put your brains in place.}

{250}{}{I know who blew up the cooler.}
{251}{}{Wow, how curious. Like in a real detective story... And who is it?}
{252}{}{I don't know. I'm just desperate. I'd better go get a drink.}
{253}{}{The explosion was carried out by the Red Cardinals on the order of the fire worshippers. And your devoted assistant, Ralph, helped them in this.}
{254}{}{Close my contacts! Why would he interfere in this?}
{255}{}{I have no idea, but it's a fact.}
{256}{}{The Church tried to persuade you to an unprofitable contract. And Ralph... He thinks it's time for him to take up the post of stationmaster.}
{257}{}{Hey, security! Bring Ralph to me. And do not take your eyes off him, so that there are no discounts for him... He's crazy. Like an overripe cherry. Do you know how much work it cost to launch this station?}
{258}{}{I don't care...}
{259}{}{Must be pretty damn hard?}
{260}{}{Oh yeah. All worries. Ralph thinks the cultists will do better if they take command here. But as a former officer, I know that people with convictions should not be allowed to come to power. Oh, I love to write out fines for crossing in the wrong place. You feel like that... big.}
{261}{}{N-well...}
{262}{}{What are you talking about?}

{270}{}{What is this old libertine up to? Look, deal with Ralph. This case is getting too dangerous.}
{271}{}{Will do. Like two fingers on asphalt.}
{272}{}{It's worth talking to him first.}

{280}{}{And here is our hero. A real hard worker of the nuclear power plant. I'm sorry, I ran out of awards. But don't worry. I know how to comfort you. Go to the storekeeper and ask him for anything you want in the warehouse.}
{1280}{}{And here is our heroine. A real hard worker of the nuclear power plant. I'm sorry, I ran out of awards. But don't worry. I know how to comfort you. Go to the storekeeper and ask him for anything you want.}
{281}{}{Glad to try.}
{1281}{}{Glad to try.}
{282}{}{After all I've seen, I don't understand how you even exist with such insanity. Yes, and you control the station.}
{283}{}{What are you saying? Miasma? Yeah, that's a problem. I tried to wash, but the smell only intensifies. You're it, you better worry about yourself.}
{284}{}{Goodbye, old man.}
{285}{}{I hope we never cross paths again.}