#---------------------------------------------------------
#  Translated by Georg; revised by garwert, nuk.
#---------------------------------------------------------
{100}{}{You see an atomic worker.}
{101}{}{You see a person covered in old burns. He is wearing is a visibly aged, tattered uniform with a pre-War symbol on it.}

{200}{}{Holy Ohm! Don't scare people like that. You, creeping around the plant with that pale skin of yours, looking like a ghost...}
{201}{}{There are definitely others here who look much more like the undead than me.}
{202}{}{Sorry, I didn't mean to scare you.}
{203}{}{Heh. Don't worry. The only thing left for us to do is to laugh in the face of death... I'm Herbert, the storeroom keeper.}
{204}{}{Ah, a storeroom, you say? I'm hoping you'll have something useful then.}

{210}{}{What is it you need, wanderer?}
{211}{}{Nothing for now. Goodbye, Herbert.}
{212}{}{Do you sell anything? I could use a couple of charged batteries.}
{213}{}{Sorry, but we only trade with caravans, and even then, only those we have a contract with. Besides, we barely have anything to offer apart from energy.}
{214}{}{I see. Bye, Herbert.}

{220}{}{Your boss promised to pay me for my work.}
{221}{}{Yes, yes, I remember something like that. Pick whatever catches your eye.}
{222}{}{Let me think for a moment. I'll be back soon.}
{223}{}{Alright, sign here and here. I'm kidding, you probably don't even know how to write. By the way, if you ever need batteries, I'll be able to help you out. Boss says we can trade with you now.}
{224}{}{I'll keep that in mind. Bye, Herbert.}
{225}{}{250 caps.}
{226}{}{Laser pistol.}
{227}{}{3 packs of RadAway.}
