{100}{}{You see a monk.}
{101}{}{You see a man in a cassock. He was clearly not here by chance.}
{102}{}{Your place is in the desert, savage.}
{1102}{}{Your place is in the desert, savage.}
{103}{}{May the Sacred Fire bless you.}
{104}{}{Being here, you risk being on a punitive bonfire.}

{200}{}{Greetings, kind man. Can I find out how your path crossed with the atomists?}
{201}{}{I don't even know. An accident, probably. What are you doing here?}
{202}{}{Oh, I'm just a peaceful pilgrim of the Sacred Fire Church. Our religion worships old knowledge and strives for the rebirth of the world. This nuclear power plant is very important for our mission. It would be very sad to know that she fell into the wrong hands.}
{203}{}{I think you have nothing to fear. Now Ralph is at the head of the station. He's going to renegotiate the contract with the church. You will be satisfied.}
{204}{}{Glory to the Atom! Is that what we should be thanking you for? The world is getting better, with your help. Thank you, stranger. Visit our church when you have time.}
{1204}{}{Glory to the Atom! Is that what we should be thanking you for? The world is getting better, with your help. Thank you, stranger. Visit our church when you have time.}
{205}{}{Necessarily. Goodbye.}

{250}{}{So, is it because of you that our plans collapsed, like the Old World? Why are you doing this?}
{251}{}{I don't like you.}
{252}{}{Don't you like the idea of Rebirth? Or don't you like our church with its symbols? In either case, you're just an egoist. An atomic nonentity with an inflated conceit. The Church has given the world Knowledge. With their help, we turned on the lights in the houses and taught some people forgotten literacy. And you? What are you trying to achieve?}
{253}{}{Because of your "rebirth" my house is empty. That's enough.}
{254}{}{Oh, so we're dealing with animal revenge. In that case, we have nothing more to talk about. Animals do not understand speech but only understand the whip. Get back to the desert and lead your wildlife like a savage. There is no place for people like you in the New World.}
{255}{}{Not before I beat the shit out of you, holy man.}
{256}{}{With pleasure. I don't want to see this whole bastion of sin.}
{257}{}{Ralph paid less.}
{258}{}{Have the bottlecaps become a reliable adviser for you? In that case, you're just an ordinary egoist. The Church has given the world Knowledge. With their help, we turned on the lights in the houses and taught some people forgotten literacy. And what will a handful of caps in your pocket give this city?}
{259}{}{I'm just fulfilling a deal. This is a fair contract.}
{260}{}{Perhaps. Perhaps the Old World has fallen because of the greed of your kind. And that's why people like you have no place in the New World. From now on, your presence in the city does not please the Church of Fire. Everyone will be better off if you leave.}
{261}{}{Not before I beat the shit out of you.}
{262}{}{With pleasure. I don't want to stay in such an unfair city anymore.}
{263}{}{You won't know it, dead man.}