{100}{}{You see a slum dweller.}
{101}{}{You see a woman with a bewildered look. She's clearly uncomfortable here.}
{102}{}{Some bastard killed him!}
{103}{}{Ah? What? Well... Do you have food?}
{104}{}{Thank you for the food, seignior.}
{1104}{}{Thank you for the food, seigniora.}

{200}{}{Hello. Can I help you?}
{201}{}{I suppose no.}

{210}{}{Who are you?}
{211}{}{My name is Susie. My husband and I relocated here from a small ranch in the desert. Life was too hard there. So we decided to try our luck here, in this big city.}
{212}{}{Goodbye, Susie.}

{220}{}{Why are you living in this horrid building?}
{221}{}{We don't have the caps to move to more better-off regions. And it is far too dangerous to live on the streets. Here, at least we are watched by Vernon and his gang.}
{222}{}{What Vernon?}
{223}{}{The manager of this communal housing. His office is to the right, down this corridor.}
{224}{}{What gang?}
{225}{}{Some people with a threatening appearance. We try to keep away from them. Their camp is in the abandoned building in a nearby region.}
{226}{}{Will keep that in mind. Bye.}
{227}{}{Remind me, what is your name?}
{228}{}{Who are you?}

{230}{}{What can you tell me about this region?}
{231}{}{It's the worst one in this whole city.}