{100}{}{Here is Bob.}
{101}{}{You see a dark-skinned man with a beard and in hiking clothes.}
{102}{}{You see old Bob. As usual, he indulges in drunkenness.}

#The first dialog
{200}{}{Hey, kid, are you lost?}
{1200}{}{Hey, lady, are you lost?}
{201}{}{Sort of. Do you really live here?}
{202}{}{(grunting with discontent) Well yes. This is a communal house, and this is my room.}
{203}{}{And you...}
{204}{}{I'm Bob, a garbage man and a handyman. But who are you and who are you looking for here?}
{205}{}{None of your business.}
{206}{}{First of all, how. Are you rude to me in my room? I don't know who you are, but you'd better get out of here.}
{207}{}{Don't you dare tell me.}
{208}{}{Excuse me, I will leave this room immediately.}
{209}{}{My name is }
{210}{}{, I'm passing through Phoenix, looking for an overnight stay.}
{211}{}{Ask Vernon, he runs everything here.}
{212}{}{Thank you.}
{213}{}{Okay.}
{214}{}{Again? I hope you're not going to start a fight here.}
{215}{}{That's what I want most right now.}
{216}{}{No, I'm not going to. Bye.}
{217}{}{Sorry about last time. I }
{218}{}{, and I'm here looking for a place to sleep.}
{219}{}{Necessarily. But first I want to talk to you.}

#Repeat dialog
{220}{}{Hello.}
{221}{}{What do you want?}
{222}{}{Looking for something?}
{223}{}{Yep?}

{225}{}{Stay away from me. I don't want to be seen next to you.}
{226}{}{You shouldn't be wandering around this dangerous area alone.}
{227}{}{I don't know what you need, but you'd better leave.}
{228}{}{}
{229}{}{See you later, Bob.}

{230}{}{Hey, great fight, }
{231}{}{. You fight like an Iron Mike. It's a pity I didn't bet, otherwise I would have gotten rich.}
{232}{}{I know. Shut up.}
{233}{}{Thanks for the support, Bob.}
{234}{}{You know, it was a regular fight. Nothing special.}
{235}{}{Whatever you say, champ. Whatever you say.}
{236}{}{Hmm.}

#Questions - about scavengers
{250}{}{You let it slip that you worked as a garbage man.}
{251}{}{(incredulously) N-well, yes. And what?}
{252}{}{Just clarifying. Can you tell me the latest news?}
{253}{}{Uh, nothing.}
{254}{}{Yes, there was a golden time when scavengers rummaged through the ruins of Phoenix in droves. Now only really dangerous areas with high radiation remain untouched... And what?}
{255}{}{Tell me about the scavengers.}
{256}{}{You really don't know about us? Hmm, we are really quite inconspicuous.}
{257}{}{I've been to Garage City, where the scavengers live too.}
{258}{}{Ah, old Kogan must have gone completely crazy, right? Eh, many went there to work when all this hype with the branch rose. I was afraid to go on such a long journey. And now it makes no sense to go - they say the branch is bent.}
{259}{}{So what do you do?}
{260}{}{For the first time I hear. What do you do?}
{261}{}{}
{262}{}{Oh, it's you... uh, scavengers... exactly. Can we talk about something else?}
{263}{}{We look for valuables in the ruins and then sell them to the market or customers. The case is dangerous and difficult. Therefore, for large-scale work, the scavengers united in a whole guild.}
{264}{}{Was it such a sought-after job?}
{265}{}{Sure. The city grew and demanded more and more things. Now, however, there is not much left in the ruins. In recent years I have been looking mainly for parts from electronics and books for fire worshippers.}
{266}{}{By the way, can you tell us about the latest news in the city?}
{267}{}{Details and books? I wish you success. And I think it's time for me.}

{270}{}{Do you know anything about Vaults?}
{271}{}{Vaults? What are you talking about? Any basement will be your refuge.}
{272}{}{No, no, I'm talking about Great Vaults.}
{273}{}{Ah, the Vault-Tec project. I came across one of them, number 26.}
{274}{}{Really? And where was it?}
{275}{}{In the western ruins, on the edge of the crater. The Scavengers Guild once made an expedition there, but the Vault was so destroyed that we returned empty-handed.}
{276}{}{Sorry to hear that. What about other Vaults?}
{277}{}{So eager to find the real treasure, huh? Many tried, but found only brain cancer. Or a bandit bullet. If anyone knows about the Vaults, it's probably the fire worshippers. But they are reluctant to share information.}
{278}{}{Thank you, maybe they will help me there.}
{279}{}{You're no good, you old fart.}
{280}{}{I see. Can we talk about something else?}

{290}{}{Can you teach me some tricks?}
{291}{}{I don't want to teach you anything. I don't like you. You walk around the city and run into trouble. Which casador stung you in the ass?}
{292}{}{Uh, let's change the subject.}
{293}{}{Then forget it.}
{294}{}{Believe me, this is a dangerous and thankless task.}
{295}{}{It seems you just don't want to mess with me.}
{296}{}{It seems right to you. I don't like you.}
{297}{}{I understand. I hope you will change your mind someday.}
{298}{}{Likewise, Bob. I don't like you either.}
{299}{}{I travel a lot. I could use your knowledge.}
{300}{}{Of course. But I'm not the one to travel anymore. I can only tell you about various places around the city, if it helps you.}
{301}{}{Great. Let me expand the map...}
{302}{}{The most difficult thing is to avoid unnecessary meetings.}
{303}{}{Thanks, Bob. This will help me a lot.}

#Questions - what's new
{350}{}{Hey, Bob, what's new?}
{351}{}{(squinting) I don't remember getting along so well with you to tell local news.}
{352}{}{Didn't you say you were a scavenger?}
{353}{}{I understand, then let's stop there.}
{354}{}{Everything is the same in our ghetto. Gangs, sectarians and poverty.}
{355}{}{I see. Let's not talk about the bad.}
{356}{}{What kind of gangs are threatening you?}
{357}{}{They don't threaten. Own. A gang of Red Cardinals is in control of the entire area. There are a few other small gangs, but they are afraid to come here.}
{358}{}{What do fire worshippers care about your neighborhood?}
{359}{}{And what does the fire worshippers care about your neighborhood?}
{360}{}{They want to take over the whole city. Slums are just a source of cheap labor for them. All this is covered up by benevolent missions to collect alms to the needy, but we ourselves need more than anyone in the city.}
{361}{}{Don't you believe them?}
{362}{}{(looks around) Hush! It's better not to ask about sectarians if you don't want problems with them.}
{363}{}{What did you say about gangs that threaten you?}
{364}{}{Is it that serious? I'll take that into account.}
{365}{}{}
{366}{}{Come on, tell me, it's all yours.}
{367}{}{(shakes his head in anguish) I doubt it very much.}
{368}{}{Your truth.}
{369}{}{Pathetic pussy.}
{370}{}{I can stand up for myself. And for you, too. Tell me, what's wrong with these guys?}
{371}{}{Fire worshippers are not what they seem. In the world, they look like good-natured simpletons and talk about the benefits of literacy. But behind the walls of the Cathedral they become silent recluses. What happens at their secret meetings, only they know.}
{372}{}{Go on.}
{373}{}{I know that they collect pre-war knowledge and technology. They say that this is how they try to revive the world. But all this is inaccessible to mere mortals. And if we consider that Aaron came to power through revolutions under the banners of the Sacred Fire, it is not difficult to draw some conclusions about their real interests.}
{374}{}{Seize control of the city?}
{375}{}{It was once said that war does not change its goals. It's the same here. Nobody cares about ordinary people. Those who tried to go against the church ended up in hard labor or on a punitive bonfire. And if you join the ranks of Followers, then you can only get out of there feet first.}
{376}{}{Sounds ominous.}
{377}{}{And by the way, some have noticed that more people enter the Cathedral than come out. I don't know what this is related to. But there are rumors that the building is actually bigger than it looks, and has a connection to underground utilities. That's how it is. But keep your mouth shut. Some particularly talkative ones went missing.}
{378}{}{In that case, we won't bring up this topic anymore.}
{379}{}{I don't believe in your stories, garbage man Bob. Bye.}
{380}{}{They lied that the cathedral was used exclusively for peaceful purposes. But there was a whole bunker with nuclear weapons under the building. And after the explosion, many residents became emboldened and began to talk about how the sectarians intimidated them. Of course, I don't believe them. Nobody believes them now.}
{381}{}{I see. How about a couple more questions?}
{382}{}{It's a pity you don't know the whole story. Bye, Scavenger Bob.}