{100}{}{You see a junkie.}
{101}{}{You see a guy with ruffled hair. Based on his look, it doesn't look that things are going well for him.}
{102}{}{Ugh... I'm... suffocating...}

#Dialogue after stopping drug use
{110}{}{Leave me alone.}
{111}{}{I need to rest.}
{112}{}{Tommorow I'll turn my life around.}
{113}{}{You have any of that stuff?}
{114}{}{You aren't going to tell anyone, right?}

{115}{}{(looks to the sides) Someone could be watching.}
{116}{}{Why did they kill Gonzalez?}
{117}{}{Gonzalez could get anything, but I couldn't pay.}
{118}{}{I'm sure Gonzalez was killed by the Followers.}
{119}{}{If they got to Gonzalez, I'm in danger, too.}

#First dialogue
{200}{}{(flinching as if in a fever) W-what?}
{201}{}{You don't look well. Ill?}
{202}{}{I'm v-very g-good.}
{203}{}{I don't believe you.}
{204}{}{L-look, I'm f-fine. Leave me alone.}
{205}{}{Whatever you say.}
{206}{}{With pleasure. You could infect me.}
{207}{}{Not so fast. First, answer my questions.}

#Repeat dialogue
{210}{}{Le-leave me al-alone.}
{211}{}{Bye.}

{212}{}{You again?}
{213}{}{I see your condition is improving. You look better than when I first met you.}
{214}{}{I'm doing worse than ever before! Gonzalez is gone and now I can't get that drug he made at all. Where will I get another dose?}
{215}{}{When the withdrawal period is over, you aren't going to want another one. That's the point. Bye.}
{216}{}{Exactly. And say "thank you" that you didn't meet your pusher.}

{220}{}{Who are you, anyway?}
{221}{}{Me? I'm Larry. Why are you asking?}
{222}{}{What do you do, Larry?}
{223}{}{Why are you bothering me? I just live here and earn money as I go.}
{1223}{}{Why are you bothering me? I just live here and earn money as I go.}
{224}{}{Looks like you aren't doing anything at all. Bye.}
{225}{}{I'm sad just seeing you in such a condition. Don't fret.}

{230}{}{You look bad. You need a doctor.}
{231}{}{I don't need a doctor! I'm fine! Leave me alone!}
{232}{}{Whoa, no need to be so nervous...}
{233}{}{Let me examine you. I'm a doctor.}
{234}{}{I don't need a doctor, just a little bit of cure. And then I'll be completely fine.}
{235}{}{I doubt that. Judging by your expanded pupils and other symptoms, you're definitely addicted to some kind of drug.}
{236}{}{Maybe. Why do you care?}
{237}{}{Who's supplying you?}
{238}{}{Gonzalez. Everyone knows that he's pushing that stuff on the street near the arena. He has killer stuff, but I don't have the caps for another dose. Just let me rest, tommorow I'll be good as new.}
{239}{}{You're right. Those are your own problems.}

{240}{}{So you are the one the locals are talking about?}
{241}{}{Go to hell! It's my business what drugs I take and when.}
{242}{}{What drugs do you take?}
{243}{}{A mix of psycho, painkillers and mentats. Killer stuff, you start seeing leprechauns and flying automobiles. And not just any regular leprechauns. Small ones. Small, about this size... At least some happiness in these damned slums.}
{244}{}{Why did you become hooked up on this shit in the first place?}
{245}{}{Well, you know, at first it was a cure for fever. And it did cure me, but then I realized I couldn't stop. It's not easy to quit stuff like this.}
{246}{}{Who's supplying you?}
{247}{}{All chems in the slums are from Gonzalez and scavengers.}
{248}{}{Hmm. I'll go talk with this Gonzalez.}

{250}{}{Larry, you have to quit.}
{251}{}{Go to hell. I'm fine. I don't need help. I know what I'm doing.}
{252}{}{We'll see about that.}
{253}{}{Your pusher isn't going to sell you any more doses.}
{254}{}{What?! But why?}
{255}{}{Because it's time to quit.}
{256}{}{I need that cure! Where will I get my next dose now?}
{257}{}{Think of your future. This isn't a solution, Larry.}
{258}{}{You don't understand. I've got everything completely under control. I know when I need to stop.}
{259}{}{We'll see about that.}
{260}{}{Stop ruining your life. Your wife and kids need you, Larry.}
{261}{}{Yeah... I already forgot about them... God, what a fool I am... Thank you. I'll try to start over.}
{262}{}{I hope so. Goodbye, Larry.}
{263}{}{Nothing good will come out of continuing to do this.}
{264}{}{Your body is not doing well, Larry. You will die soon unless you stop taking that stuff.}
{265}{}{So you're a doctor? Why the hell are you scaring me like that?}
{266}{}{Yes, I am a doctor. I'm not scaring you, I'm just telling you the truth.}
{267}{}{Dammit... I know I don't have much time left. But I can't quit. What do I do now?}
{268}{}{Well, you could try to neutralize your addiction with another addiction. Try that.}
{269}{}{Wow, this will help? Looks like I don't have a choice. Thanks, doc.}
{270}{}{Goodbye, Larry.}
{271}{}{No, sorry, I am not a doctor.}
{272}{}{This stuff will kill you one day. I have mentats. Try them, maybe they'll clear up your head.}