{100}{}{This is Vernon.}
{101}{}{You see a man in a badly worn suit. Circles under his eyes and a nervous tic indicate overwork.}
{102}{}{We have, of course, a dangerous area, but to be so...}
{103}{}{Please stop them! They'll tear everything down here!}

#The first dialog
{200}{}{(noticing you, the man frowns and nervously twitches his right eye) I don't think I've seen you before. What are you looking for here?}
{201}{}{I need a place to sleep. Rooms for rent here?}
{202}{}{I'm sorry, but all the rooms are occupied. We have nowhere to breathe without you.}
{203}{}{And what is this place?}
{204}{}{Something like a community house. If you're here by chance, you'd better leave.}
{205}{}{Why?}
{206}{}{Harsh local customs. All residents know each other by sight and are wary of newcomers.}
{207}{}{I understand. In that case, I really should leave.}
{208}{}{Nothing surprising for such a lousy neighborhood. Bye.}
{209}{}{I'm not leaving until I get the answers to the questions.}

{210}{}{I don't even know. And what is this place?}
{211}{}{This is a community house. Do you have business here or do you have acquaintances? If not, you'd better leave.}
{212}{}{Why are you kicking me out?}
{213}{}{(dissatisfied sleepy grumbling) Burke... burke... Pr-k-lyatye, do you even know what time it is...}
{214}{}{Sorry to distract you from sleep.}
{215}{}{I don't care.}

{220}{}{(your appearance makes a man freeze in amazement, and then nervously twitch his right eye) What a surprise to see such a respected person in our ghetto. Are you looking for something?}
{221}{}{I'm actually looking for a place to stay. Are there any rooms available here?}
{222}{}{I'm afraid all the rooms are occupied. Besides, you probably won't like it here.}
{223}{}{Why?}
{224}{}{How should I put it... You don't quite fit in with these slums. We have poor housing conditions and harsh tenants. You may even be robbed.}
{225}{}{Nothing surprising for such a lousy neighborhood. Bye.}
{226}{}{Looks like I really should leave.}
{227}{}{Before I leave, I want to ask a few questions.}
{228}{}{I was curious, what kind of place is this?}
{229}{}{Something like a community house. If you are here by chance, then you should not linger here.}
{230}{}{Why is that?}

{240}{}{Hey, champ! It was a great fight. How can I help such a respected person?}
{241}{}{I don't even know. And what is this place?}
{242}{}{This is a community house, and I am its manager. However, I don't think people of your rank will be interested here. They live in our ghetto... less successful citizens.}
{243}{}{Then be kind enough to answer a couple of questions.}
{244}{}{It was clear from the very beginning that this was a hole. They won't see me here anymore.}
{245}{}{Do you mind if I take a look around? Great, see you later.}
{246}{}{Hey, champ! It was a great fight. How can I help such a respected person?}
{247}{}{I want to talk to you.}

#Death of a pusher
{250}{}{(Vernon is sitting at the table with his head in his hands; he sways a little, making a soft moan)}
{251}{}{What's wrong with you?}
{252}{}{Eh? Oh, it's you... This damn headache... I used to take medications that Gonzalez found. But now he's dead, and I don't know where to get them... Um...}
{253}{}{Sucks. Well, come on.}
{254}{}{Oh, I'm sorry, it seemed to me that the death of this pusher would be for everyone's good.}
{255}{}{WHAT did you think? Damn it! Yes, Gonzalez was getting drugs to some residents, from whom they were stupid. But to others he supplied medicines for diseases and painkillers. Why the hell would you want to kill him?}
{256}{}{It's none of your business anymore.}
{257}{}{Well yes... of course... Then get the hell out of my office.}
{258}{}{Watch your tongue, otherwise you'll end up like your pusher.}
{259}{}{Yeah.}
{260}{}{His product was not of sufficient quality.}
{261}{}{And this is the only reason? Damn it, you're out of your mind! Get out of this area, now.}
{262}{}{}
{263}{}{I don't even know. Is there really a reason?}
{264}{}{You're out of your mind! Better get out of this neighborhood and never come back here.}

#Reket after the game finale
{270}{}{Oh, thank you, amigo. If it wasn't for you, these hooligans would have destroyed everything here, and maybe even injured someone.}
{271}{}{What did they want from you?}
{272}{}{It's just a racket. After the gang of Cardinals broke up, the devil knows what started in the slums. Now any scumbags who used to be afraid to even stick out on the street can rob and beat people with impunity.}
{273}{}{Weren't the cardinals bandits themselves?}
{274}{}{Yes, but they were watching the area and didn't let that happen. I really hope that soon this wave of robbery will calm down. Someone will surely take power over the area into their own hands. And everything will start anew.}
{275}{}{It's fun here with you. Visit.}
{276}{}{This could not have been foreseen. Good luck here.}

#Repeat dialog
{300}{}{So what do you need?}
{301}{}{How can I help you?}
{302}{}{You'd better leave.}
{303}{}{Goodbye.}
{304}{}{What are you doing here?}

{310}{}{I'm investigating an attack on Followers. What do you know about it?}
{311}{}{The situation has become a little clearer.}
{312}{}{The situation has become a little clearer. It's time to discuss this with Aaron.}
{313}{}{ (frowning, gives a nervous tic) So you're another Follower tracker? I have already told the monks everything. Leave us alone.}
{314}{}{(frowning reproduces a nervous tic) I didn't expect that they recruited you too. But I have already told the monks everything I know.}
{315}{}{I'll have to tell you again.}
{316}{}{We didn't kill anyone. The monks went around the residents in search of alms and, of course, left with nothing. Already on the street they were seized by masked men and strung up on lampposts. We don't know who it was. But they were clearly well prepared for the attack.}
{317}{}{Is any of the residents involved in this?}
{318}{}{The locals are afraid of people from the church. No one would commit such a crime, besides in front of their own house.}
{319}{}{There are rumors that the locals dislike monks.}
{320}{}{And why should we love them? When we live in poverty, monks bathe in luxury. They take away our weapons and forbid Gonzalez to sell medicines. But look at the locals. Could any of these poor people have carried out such a well-organized attack?}
{321}{}{Who is capable of such an audacious attack?}
{322}{}{Only the Atomists and the Orris gang. But the former always stayed away from the city. And the second hardly needs problems with the church.}
{323}{}{There are no more questions.}
{324}{}{I don't believe you. You must be hiding something.}
{325}{}{I know what I'm talking about. If you don't believe me, prove the opposite.}
{326}{}{Today I will be kind and break only two fingers for you until I know everything I want.}
{1326}{}{Today I will be kind and break only two fingers for you until I know everything I want.}
{327}{}{Grm...}
{328}{}{Stop it! Think about it, would we attack monks near our own house? It's too reckless. But there are rumors about a secret club of fire-phobes. After all, in the past, Aaron, with the help of the Church of Fire, staged a revolution and ruined the whole city. Surely many people have been wanting to take revenge on him since then.}
{329}{}{A curious thought. Perhaps you deserve my mercy for today.}
{330}{}{Enough lies! I will kill you, atomic nonentity.}
{331}{}{Don't rush to poke your fire stick, sectarian. We can fight when we need to, too.}
{332}{}{Gr-r!}
{333}{}{Tell me again about the attack on the monks.}

#Questions
{350}{}{Who are you and what is this place?}
{351}{}{I'm telling you, this is a community house. And I'm Vernon, his manager.}
{352}{}{That's all I wanted to know.}
{353}{}{And why did you say that this area is dangerous?}
{354}{}{Poor people and bandits are not the best roommates for any city.}
{355}{}{What kind of bandits are we talking about?}
{356}{}{I shouldn't have said that. There are several gangs in the neighborhood. Atomic scientists in the east, Orris's people in the north, there are several other small gangs in every block.}
{357}{}{What can you tell us about atomic scientists?}
{358}{}{These are secretive guys, they adhere to neutrality and try not to interfere in the affairs of the city. But they let a few people near them.}
{359}{}{Who is Orris and what is his gang famous for?}
{360}{}{Orris practically owns our entire block. Don't try to rebel against his guys, otherwise you won't survive here.}
{361}{}{I'm looking for Steve. They say he lives here.}
{362}{}{I don't know why you need this rascal, and I don't want to know. Lately, he's been hanging out in the ring, hoping to make money on betting. Fool.}
{363}{}{So, in the ring.}

#Quests
{370}{}{It seems you have a problem. I can help.}
{371}{}{Really? You know, the city has taught me not to trust anyone who offers help with a smile. What are you really trying to achieve?}
{372}{}{I want to help. It's true.}
{373}{}{Tell it to someone else. In any case, you won't earn caps here.}
{374}{}{Well, you're right there. I need to get a foothold in the city.}
{375}{}{Ha. You see. But you won't earn caps here. Although it is also useful to get good fame.}
{376}{}{If you don't want to, that's fine. My business is to offer.}
{377}{}{And yet- what are your problems?}
{378}{}{Well. There are a couple of annoying tenants here, from whom there are continuous problems. Can you kick them out?}
{379}{}{Quite. Who are they?}
{380}{}{Uh, no. I don't interfere in personal disputes.}
{381}{}{One is named Larry. He's hooked on drugs and lets all his caps down on them. He's a smart man, but chemistry has completely clouded his head. I can't kick him out openly, because the pusher obviously won't like losing a client.}
{382}{}{Clear. Who is the second?}
{383}{}{Badi. He lives in the room opposite. There was no problem with him until he got hooked on gambling. Now he has accumulated such a debt that bouncers threaten even me.}
{384}{}{No one wants to mess with him anymore. It's clear that he can't pay me either. Let him pay the rent or get out on the street. I'm sick of it.}
{385}{}{Remind me which drug addict you were talking about?}
{386}{}{Larry. He's probably in his dirty room right now, wasting his life.}
{387}{}{Clearly. Bye.}
{388}{}{Remind me which of the tenants owed the rent.}
{389}{}{Yes, everyone is in debt. But Badie will owe the most. Besides, he has problems with the casino, and I don't need that.}
{390}{}{Damn, games are serious business.}
{391}{}{Larry won't bother the residents of the house anymore. He's dead.}
{392}{}{WHAT? My God, why did you have to bring it to this?}
{393}{}{Well, you wanted to get rid of him.}
{394}{}{But that's not what I meant! The slums already have a bad reputation, and now people will say unkind things about me personally.}
{395}{}{It was necessary to clarify the task. And now it's too late.}
{396}{}{Well yes. Sure. I really hope that this will be quickly forgotten. Besides, it will be much calmer without Larry.}
{397}{}{Exactly. Bye, Vernon.}
{398}{}{Larry won't bother the residents of the house anymore. He managed to overcome his addiction.}
{399}{}{Unbelievable! How did you manage to inspire him? No one believed in Larry anymore. Everyone considered him an incorrigible scum.}
{400}{}{I have my own methods. He just needed motivation.}
{401}{}{I don't even know what to say. Thank you.}
{402}{}{You're welcome, Vernon.}
{403}{}{OK. I'll talk to them first.}

{404}{}{Badie will soon pay the rent debt.}
{405}{}{Great job! I already thought that nothing would save him from a bloody reckoning. How did you manage to set his mind straight?}
{406}{}{The main thing is to find your own approach to each client. Bye, Vernon.}
{407}{}{Badie doesn't live here anymore. He lives on the street like a lousy stray dog.}
{408}{}{And correctly. We don't need any extra problems here. Thank you for your help.}
{409}{}{Please.}
{410}{}{Badie doesn't live here anymore. He is no longer a tenant at all.}
{411}{}{His... killed? My God, these bouncers are real beasts.}
{412}{}{There was no other way out.}
{413}{}{Don't tell me the details. I really hope that his debt to the casino will not affect me and the other tenants. It would be better if he just went somewhere else.}
{414}{}{Yeah, it didn't come out in the cleanest way. But your problem was solved. Bye.}
{415}{}{Badie paid off his debts at the casino. He'll pay your rent soon.}
{416}{}{Sounds great! How did you manage to set his mind straight?}
{417}{}{The main thing is to find your own approach to each client.}
{418}{}{Great job. And I already thought that nothing would save him from a bloody reckoning. You know, those bouncers at the casino are real beasts. Thank you for your help.}
{419}{}{You're welcome, Vernon.}

{420}{}{All your orders are fulfilled. How else can I help?}
{421}{}{I can't believe you're helping us poor people for free. You're an unusual person. But these were trifles compared to what we have to endure from day to day.}
{422}{}{What are you talking about?}
{423}{}{Our main headache is a gang of Red Cardinals. They, in fact, own the whole area and all its inhabitants. No one dares to go against them. Even the guild mercenaries don't want to get involved in this. Nobody cares about us, and the gang is constantly growing and putting pressure on us.}
{424}{}{You're crazy. Do you even know what you're asking?}
{425}{}{Please? Uh, no, I'm just complaining. Eliminating such a gang sounds fantastic. But you've already done so much for us. Do you have any ideas? Actually, we've dropped all our last caps over Orris' head here. Without him, the gang will fall apart. This will give at least some respite to us, ordinary residents.}
{426}{}{You will have to think carefully about this task. See you later, Vernon.}
{427}{}{Okay, I'll help you. I hope the payment will be decent.}
{428}{}{Do you want to get rid of the gang? Yes, easily. These street dogs haven't seen a real fight.}
{429}{}{Oh! We'll pay all the caps we have if you kill their leader, Orris. Without him, the gang will weaken. This will give at least some respite to us, ordinary residents.}
{430}{}{Don't worry about the caps. I will deal with this problem.}
{431}{}{Get the caps ready, because I'll take EVERYTHING you have for his head.}
{432}{}{Tell me more about the Red Cardinals and their gang.}
{433}{}{The gang owns the whole area. There are dozens of people in it. They know how to fight well and they have weapons. Their leader is Orris. He's a scary guy, he won't let anyone down. Neither us, nor the bandits themselves. Please spare us from his lawlessness. Besides you, no one else will want to help us.}
{434}{}{Orris is no longer in business. His gang is losing power.}
{435}{}{You are a real hero! We've been hoping for a miracle for so long, and now you're giving us hope for a new life. Thank you so much.}
{1435}{}{You are a real heroine! We've been hoping for a miracle for so long, and now you're giving us hope for a new life. Thank you so much.}
{436}{}{That's good. The main thing is that no one is threatening you now.}
{437}{}{To hell with these tearful speeches. Drive the bottlecaps. Do you think I'm taking such a risk out of the kindness of my heart?}
{438}{}{Uh, yes, take these caps, there are 217 pieces here. This is all we managed to collect.}
{439}{}{Idiot! I wouldn't risk it for such bottlecaps. Well, we'll have to take what we have.}
{1439}{}{Idiot! I wouldn't take the risk for such bottlecaps. Well, we'll have to take what we have.}
{440}{}{Better than nothing.}
{441}{}{Sorry it's so little. You can spend the night in our house as much as you want.}
{442}{}{Goodbye, Vernon.}
{443}{}{Leave the caps to those from whom you collected them. It was important for me to get justice.}
{444}{}{You're an extraordinary person. Know that you are always welcome in our house.}
{445}{}{Goodbye, Vernon.}
{446}{}{Thanks, of course, for helping with Larry and Badie, but you'd better leave. I'm sorry, but I don't want to have anything to do with you.}
{447}{}{That's not good of you.}
{448}{}{It's worse for you, buddy.}