{100}{}{You see a slum dweller.}
{101}{}{You see a woman with a confused look. She is clearly uncomfortable here.}
{102}{}{Some bastard killed him!}
{103}{}{Eh? What? Well... Do you have food?}
{104}{}{Thank you for the meal, señor.}
{1104}{}{Thank you for the food, señora.}

{200}{}{Hi. Can I help you with something?}
{201}{}{Probably nothing.}

{210}{}{Who are you?}
{211}{}{My name is Susie. My husband and I moved from a small ranch in the desert. It was too hard to live there. And we decided to try our luck in the big city.}
{212}{}{Bye, Susie.}

{220}{}{Why did you live in such a terrible building?}
{221}{}{We don't have the caps to settle in more prosperous areas. And living on the street is too dangerous. At least Vernon and his gang are watching us here.}
{222}{}{Who is Vernon?}
{223}{}{The manager of the community house. His office is on the right down the corridor.}
{224}{}{What kind of gang?}
{225}{}{Some people of frightening appearance. We try to stay away from them. Their camp is in an abandoned building in a nearby neighborhood.}
{226}{}{Clear. Bye.}
{227}{}{Remind me, what's your name?}
{228}{}{And who are you?}

{230}{}{What can you tell us about this area?}
{231}{}{This is the worst residential area in the city.}