{100}{}{You see Steve.}
{101}{}{You see an arena fan.}
{102}{}{Wow. I knew the tinsmiths were good, but I could never imagine something like this...}
{103}{}{That letter was very handy. Thanks for the delivery.}
{104}{}{Are you making bets too?}

{200}{}{What? Are you participating in the fights, too?}
{201}{}{No. I am searching for a man named Steve. He lives in *that* house.}
{202}{}{Wait a minute, it's you! Wow, listen, the last couple of fights were, of course, incredible. But why can't you set up a couple more? I'd raise great caps for that.}
{203}{}{That doesn't depend on me.}
{204}{}{Ah, I see. That shorty's hungry for caps as well, right? Fine, forget it.}
{205}{}{I am searching for a man by the name of Steve. He lives in *that* house.}
{206}{}{I'm not fighting anymore. Period.}
{207}{}{Calm down, buddy, no need to stress like that.}
{208}{}{I don't care. Just tell me who here is the Steve who lives in *that* house.}
{209}{}{It's me. What do you want?}
{210}{}{I'm from the delivery service. Here's the letter. Sign and receive.}
{211}{}{Is this some kind of joke? I can barely read. Who could have sent this to me?}
{212}{}{So you are not the Steve I'm looking for. Bye.}
{213}{}{Hey, wait. Of course I'll sign. Are fingerprints enough? Great, give it to me...}
{214}{}{[Continue]}
{215}{}{I don't know who sent this to you. But you need to pay five caps for the delivery.}
{216}{}{So I also need to *pay* for this? No way. No way, definitely a scam. I'm not stupid.}
{217}{}{Very well. Take the letter for free. It's only unnecessary weight in my backpack.}
{218}{}{This is intriguing. Fine, here are your five caps. I very much hope it's worth it.}
{219}{}{Take it.}
{220}{}{It's fine. Just sign here and take the letter.}
{221}{}{What? Do you participate in the fights too?}
{222}{}{No, I am simply looking for a person to hand a letter to. But the letter is missing.}
{223}{}{Yeah, that's a problem.}
{224}{}{Uhh, I'll go searching. Bye.}

{227}{}{Hi. I'm still trying to get caps in the arena. But I can't do it. Looks like it's time to get out of this packed city.}
{228}{}{Speak for yourself. I'm tired to death of primitive life in plantations. Bye.}
{229}{}{Yeah, life is more simple and calm away from the big, noisy city. Bye.}

{230}{}{(takes the letter, unfolds it and slowly reads it) Well, well, well...}
{231}{}{Is this letter really for you?}
{232}{}{It's from my uncle who lives in Casa Grande. Looks like I'm supposed to meet him. Thanks, this was a very important letter. Really.}
{233}{}{What did he write?}
{234}{}{Looks like I will be able to leave with a deep feeling of pride and accomplishment. Wish you the best.}