{100}{}{You see a slum dweller.}
{101}{}{You see a slum dweller. It's a sad sight.}
{102}{}{You see a slum dweller. He's picking his ear.}
{103}{}{You see a slum dweller. He's scratching his hair trying to remove the dirt.}
{104}{}{You see a slum dweller. He's lovingly cleaning what few rags he's wearing.}
{105}{}{You see a local. His bald spots show the hardship of living in the slums.}

{110}{}{I want to eat.}
{111}{}{I would be so happy if I caught a rat that I could grill for dinner.}
{112}{}{I can't believe people once poured *clean* water down the toilet.}
{113}{}{Smalltalk only makes the hunger worse.}
{114}{}{We need food.}
{115}{}{They say mutated humans have been living in the sewers since the War.}
{116}{}{They found another body in the neighboring block.}
{117}{}{Don't play in the casino unless you want to become a slave.}
{118}{}{That fire cult has eyes and ears everywhere.}
{119}{}{I wouldn't want to be one of those cultists.}
{120}{}{Hello.}
{121}{}{See you.}
{122}{}{Have to go.}
{123}{}{Don't cause us trouble.}
{124}{}{Do you ever take off that thing on your arm?}
{125}{}{What's "tele-vision"?}
{126}{}{Aren't those "mail boxes" just garbage cans?}
{127}{}{Sorry, I have to return to doing nothing.}
{128}{}{You shouldn't even put out fires with this muddy water.}
{129}{}{Is it true that there is white, hard water up in the mountains?}
{130}{}{Here, the sky is always filled with smog.}
{131}{}{There hasn't been rain here for many years.}
{132}{}{Another day has passed, and I'm still alive. I'm lucky.}
{133}{}{After the scavengers went there, there's nothing valuable in the ruins anymore.}