{100}{}{You see a bandit.}
{101}{}{You see a defiant young man.}
{102}{}{This is your bike? Oh, I'm very sorry. It looked to me like it didn't belong to anyone. Of course, uhh, take it, we don't mind at all.}
{103}{}{Fuck off.}
{104}{}{Hey, is this your bike?}

{200}{}{Hey, is this your bike?}
{201}{}{Yep.}
{202}{}{Maybe. What is it to you?}
{203}{}{You're mistaken. This is *my* bike. Problem? A-a-ah, you probably want to BUY it. Good choice. The price will be... 500 caps. I'd advise you to hurry up. Such a good deal won't last for very long.}
{204}{}{What's it to you? You can't use it anyway.}
{205}{}{You take me for an idiot? Everyone with power in the city will be interested in this bike. If you don't pay me - someone else will.}
{206}{}{Give me my bike back. I won't ask you nicely again.}
{207}{}{Give me time to collect the caps.}

{210}{}{You brought 500 caps?}
{1210}{}{You brought 500 caps?}
{211}{}{You brought 700 caps?}
{1211}{}{You brought 700 caps?}
{212}{}{Give me time to collect the caps.}

{220}{}{This is *my* bike. Give me the key. Now.}
{221}{}{Or what? You think you can do anything about it? Our gang *owns* this region. You scream at me - you scream at the whole band. Understand?}
{222}{}{I don't give a fuck about you or your gang. Give me the key or die.}
{223}{}{Sorry. I don't want any trouble with you or your buddies.}
{224}{}{Oh, and by the way, the price is now 700 caps.}
{225}{}{Hr-rm...}
{226}{}{Talking to you was stupid. I should have just killed you right from the start.}

{230}{}{Here are the caps. Now give me the key.}
{231}{}{(offhandedly drops the key on the ground) Take it. I didn't know how to use this thing anyways. (walks away with a smirk, weighing the caps with a satisfied look)}
{232}{}{Uhh, thanks, this was a good purchase.}
{233}{}{Laugh while you still can. One day I'll find you, you son of a bitch.}
{234}{}{Not so fast, jerk. Hand over all my caps.}

{240}{}{Only an idiot would talk that way to an arena champion. A smart man would give the champion the key. Now.}
{241}{}{You know, I'm a Follower. It would be unfortunate if I had to go tell my brothers about this. How about you give me the key, and I don't tell anyone what you did?}
{242}{}{Have you heard of the highwaymen? I'm one of them. Don't underestimate us.}
{243}{}{(the man grins his teeth like a cornered dog) D-damn, I didn't know... Sorry, take the key... Is it fine now? I'll, uhh, go away.}
{244}{}{Get outta here.}
{245}{}{No problem. I will forget that this misunderstanding ever happened.}