{100}{}{You see Bob.}
{101}{}{You see a dark-skinned, weary man in hiking clothes.}
{102}{}{You see old man Bob. As usual, he's very drunk.}

#First dialogue
{200}{}{Hey, fella, you lost?}
{1200}{}{Hey, lady, you lost?}
{201}{}{Kind of. Do you really live here?}
{202}{}{(groaning with displeasure) Yea. It's communal housing, and this is my room.}
{203}{}{And you are...}
{204}{}{I'm Bob, scavenger and handyman. Now, who exactly are you and who are you looking for here?}
{205}{}{None of your business.}
{206}{}{So *that's* how you roll? Insulting me in my own room? I don't know who you are, but it would be better for you to get outta here.}
{207}{}{Don't you tell me what to do.}
{208}{}{Sorry, I'll leave this room immediately.}
{209}{}{My name is }
{210}{}{, I'm stopping in Phoenix on my way to another place. I'm looking for a place to sleep.}
{211}{}{Ask Vernon, he manages everything here.}
{212}{}{Thanks.}
{213}{}{Okay.}
{214}{}{Again? I hope you're not here to start a fight.}
{215}{}{I am.}
{216}{}{I'm not. Bye.}
{217}{}{Sorry about last time. I'm }
{218}{}{, and I'm here in search of a place to sleep.}
{219}{}{Sure. But first I want to talk to you.}

#Repeating dialogue
{220}{}{Hi.}
{221}{}{What do you want?}
{222}{}{You looking for something?}
{223}{}{Yep?}

{225}{}{Stay away from me. I don't want to be seen near you.}
{226}{}{You shouldn't walk around a dangerous region alone.}
{227}{}{I don't know what you need, but you better go.}
{228}{}{}
{229}{}{See you, Bob.}

{230}{}{Hey, what a fight, }
{231}{}{. You fight no worse than Iron Mike. It's a shame I didn't place bets, I could have become rich.}
{232}{}{I know. Shut up.}
{233}{}{Thanks for the support, Bob.}
{234}{}{You know, it was just a regular fight. Nothing out of the ordinary.}
{235}{}{Whatever you say, champion. Whatever you say.}
{236}{}{Hm.}

#Tell me about - the scavengers
{250}{}{You said that you once were a scavenger.}
{251}{}{(mistrustfully) W-well, yeah. Why are you asking?}
{252}{}{Just making sure. Maybe you could tell me about what has been happening lately?}
{253}{}{Uhh, nothing.}
{254}{}{There was once this golden age, when scavengers were swarming the ruins of Phoenix in droves. Now only the truly dangerous regions with high levels of radiation have anything valuable... Why are you asking?}
{255}{}{Tell me about the scavengers.}
{256}{}{You really don't know about us? Hm, I suppose we are not really very noticable.}
{257}{}{I happened to be in Garage-City, there are also scavengers there.}
{258}{}{A-ah, old man Cogan must have went completely rabid, yeah? *Sigh*, many went there to earn money during the time when there was much noise about a subsidiary. I myself was afraid of going so far away. Now there's no point going there - I hear the subsidiary has declined.}
{259}{}{So, what is it you do?}
{260}{}{First time I'm hearing about this kind of stuff. What is it you do?}
{261}{}{}
{262}{}{Ah yes, you're those people who... uhh, scavenge. Right. Let's talk about something else.}
{263}{}{We find valuable items in the ruins and then sell them on the market or to customers. It's hard and dangerous. That is why for large projects, the scavengers united into a guild.}
{264}{}{The demand was so high?}
{265}{}{Of course. The city was growing and demanding more and more. Though, to be honest, at this point there's almost nothing in the ruins. Lately, I've mainly been searching for electronic components and books for the fire-worshippers.}
{266}{}{Oh, and by the way, could you tell me about recent happenings in here?}
{267}{}{Components and books? Good luck, I suppose. And as for me, I think I should go.}

{270}{}{Do you know anything about vaults?}
{271}{}{Vaults? What nonsense are you saying? Any basememnt can be a vault.}
{272}{}{No, I'm talking about the Great Vaults.}
{273}{}{A-ah, the Vault-Tec projects. I stumbled upon one such vault at a time, the number was 26.}
{274}{}{Really? Where was that?}
{275}{}{In the western ruins, on the edge of the crater. The scavenger guild once funded an expedition there, but the Vault turned out to be so ruined that they returned with nothing.}
{276}{}{Sorry to hear that. And what about the other Vaults?}
{277}{}{Itching to find some of the real stuff, huh? Many tried, but got only brain cancer. Or a bullet from some bandit. If anyone knows about the Vaults, it's probably the fire-worshippers. But they hesitate to share information.}
{278}{}{Thanks. Maybe they'll help me.}
{279}{}{You're of no use whatsoever, you old twat.}
{280}{}{Alright. Maybe we could talk about something else?}

{290}{}{Can you teach me some tricks?}
{291}{}{I don't want to teach you anything. I don't like you. You waltz around the city and look for trouble. What cazador bit you in the ass?}
{292}{}{Uhh, let's change the subject.}
{293}{}{Fine, forget it.}
{294}{}{Believe me, it's a dangerous and thankless job.}
{295}{}{It looks to me like you just don't want to associate with me.}
{296}{}{It looks just like it is. I don't like you.}
{297}{}{Alright. I hope you change your mind someday.}
{298}{}{The feeling's mutual, Bob. I don't like you either.}
{299}{}{I travel a lot. I would use your knowledge.}
{300}{}{Of course. But I'm in no shape to travel. I can only tell you about some places around the city, if that would be of any help.}
{301}{}{Great. Let me take out my map...}
{302}{}{The most difficult thing is avoiding unneeded encounters.}
{303}{}{Thanks, Bob. This will greatly help me.}

#Tell me about - what's happening
{350}{}{Hey, Bob, what's up?}
{351}{}{(squinting) I don't recall our relationship being so good as to share local news.}
{352}{}{I think you told me you were a scavenger.}
{353}{}{Fine, let's leave it at that.}
{354}{}{Business as usual in our ghetto. Gangs, cultists and poverty.}
{355}{}{Alright. Let's not talk about the bad stuff.}
{356}{}{What gangs are threatening you?}
{357}{}{They don't threaten us, they *own* us. The Red Cardinal gang controls the entire region. There are some smaller gangs, but they're afraid of coming here.}
{358}{}{Why do the fire-worshippers care about your region?}
{359}{}{Why are the fire-worshippers interested in your region?}
{360}{}{They want to take over the whole city. For them, the slums are just a source of cheap labor. It's all covered up with their noble missions to raise money for the poor, but we ourselves are the poor this money should be going toward.}
{361}{}{You don't believe them?}
{362}{}{(looks around) Shush! Don't ask people about the cultists, if you don't want trouble with them.}
{363}{}{You said something about gangs that were threatening you, I think?}
{364}{}{It's so bad? I'll keep that in mind.}
{365}{}{}
{366}{}{Calm down, tell me, everyone's a friend here.}
{367}{}{(shakes head in pain) Ve-ery much doubt that.}
{368}{}{True, I suppose.}
{369}{}{Pathetic coward.}
{370}{}{I can stand up for myself. And for you. Tell me, what's wrong with them?}
{371}{}{The fire-worshippers are not who they seem to be. Outside, they look like simple, good-natured people, they talk about the benefits of literacy. But in the walls of the Cathedral they become silent hermits. Nobody but they know what happens at their secret meetings.}
{372}{}{Go on, please.}
{373}{}{I know that they are collecting Pre-War knowledge and technology. They say they want to rebuild the world. But this is impossible for mere mortals. And if one considers that Aaron came to power through a revolution under the banner of the Holy Flame, it is hard not to see at least some hints as to their true goal.}
{374}{}{Complete control over the city?}
{375}{}{People once said that war never changes. Same situation here. Nobody cared about the people then, nobody cares about the people now. Those that try and go against the church end up doing hard labor or burned at the stake. And if one joins the ranks of the Followers, then the only way out is death.}
{376}{}{Sure sounds ominous.}
{377}{}{And by the way, some people told me that they see more people going inside the Cathedral than people leaving it. I don't know what this means, but there are rumours. That the building is actually bigger than it looks, that it has some kind of connection to underground communication. That's how it seems to be. But don't tell anyone. I saw some especially talkative people go missing without a trace.}
{378}{}{Well, then in that case, let's not talk about this any longer.}
{379}{}{I'm not really inclined to believe in this story, Bob. Bye.}
{380}{}{They were lying when they said the Cathedral was used for exclusively peaceful purposes. There was a whole bunker underground, with nuclear weaponry. After the explosion, many became more bold and started talking about how they were scared of the cultists. Of course, I don't believe them. Nobody believes them anymore.}
{381}{}{Alright. What about a couple of questions?}
{382}{}{It's a shame you don't know the whole story. Bye, scavenger Bob.}