{100}{}{You see Buddy.}
{101}{}{You see a regular bum, incapable of doing anything. It is a wonder how he is still alive.}
{102}{}{Howdy, pardner?}
{103}{}{One day I'll make revenge upon you.}

{110}{}{My situation's hopeless.}
{111}{}{This will be the end of me.}
{112}{}{I only got one more cap.}
{113}{}{I wasted everything I got lately in the casino.}
{114}{}{I have no idea how to get out of this debt.}
{115}{}{I ended up living in poverty in just a couple of days.}
{116}{}{This may be the last day of my life.}
{117}{}{Can you lend me a thousand caps? I'll return them all back, you have my word.}
{118}{}{Looks like they'll make a slave out of me soon.}
{119}{}{They'll soon kick me onto the streets.}

{200}{}{Phew, don't you frighten me like that. Lately, I've been avoiding strangers.}
{201}{}{Who are you?}
{202}{}{My name is Buddy, I live here. Don't recall you doing that, though.}
{203}{}{Don't you even think of insulting me, you piece of shit.}
{204}{}{Well, hello, Buddy. I'm }
{205}{}{.}

{210}{}{What do you want?}
{211}{}{From you specifically? Nothing. At least, yet.}

{220}{}{Vernon has had enough of your endless debt. Pay up or get the fuck out.}
{221}{}{No, please don't evict me! I'll pay Vernon right away, as soon as I pay the casino. I just need some time!}
{222}{}{You owe the casino?}
{223}{}{Well, yeah. I admit, that was a stupid decision. I shouldn't have hoped to get lucky. But that day, everything was so bad, I couldn't stop myself.}
{224}{}{I don't care about your reasons. Now, go out there and breathe some fresh air.}
{225}{}{I've been living here for years! And that's how Vernon deals with residents? Fine, we'll see who's in the right.}
{226}{}{Get outta here.}
{227}{}{I can understand your reasons. How much do you owe Vernon?}
{228}{}{37 caps for the last quarter of the year.}
{229}{}{I know what it's like to lose one's home. Don't worry about the caps, I'll pay for your rent.}
{230}{}{Really? Thank God! Thank you! Thank you!}
{231}{}{It's nothing to me, really. I'm }
{232}{}{ by the way. Remember that name.}
{233}{}{Bye.}
{234}{}{Alright, I'll give you some more time.}
{235}{}{Really? Thank you! I'll collect the caps as soon as I can, I promise.}
{236}{}{I hope this promise will be backed by actual results soon enough.}

{250}{}{You owe the casino quite a lot. Time to pay up.}
{251}{}{I gave everything I had! I have nothing left! I beg of you, give me some time. I'll give everything back!}
{252}{}{You had enough time already. What's the problem with getting enough caps?}
{253}{}{There's unemployment all over the city, and my reputation is in a bad place due to the debt. I'm surviving just on collecting junk in the ruins.}
{254}{}{Looks like there really is nothing left to take from you anymore. I'll just leave you to wallow in your own shit.}
{255}{}{You want to stop my fist, tell me something that gives hope your situation might improve.}
{256}{}{Wait, don't go that far. If don Diego wants to get his caps, he needs me alive and unharmed. Isn't that so? And if not, he would have sent me into slavery long ago. Get the situation?}
{257}{}{Dammit, I'm wasting my time with you.}
{258}{}{So how exactly are you planning to pay your debts?}
{259}{}{I have a plan. I just need some time to prepare.}
{260}{}{What's that, another deceitful excuse?}
{261}{}{What do you have on your mind? Go on, tell me.}
{262}{}{Enough of this shit. Give me the caps or I'm gonna break your bones.}
{263}{}{Umm, listen, you too will be able to earn some money. I see it in you - don Diego doesn't just offer jobs to random people on the street.}
{264}{}{An intriguing offer. Continue.}
{265}{}{Your arrogance knows no bounds. But I'll listen to what you came up with this time.}
{266}{}{There is this place that has MOUNTAINS of caps. I'm not lying, it's true. Nobody knows about it except me. We'll go there, break open the warehouse, take everything there, and each one of us will take half of the caps. So, what do you say?}
{267}{}{Something's not right here. Why didn't you do it yourself earlier?}
{268}{}{Sounds like an arrogant lie. What's the catch?}
{269}{}{There's just one problem. It looks like the warehouse is guarded by a couple of old robots. Somebody tried to get past them already and got shocked right in the balls. But you would be able to stand your ground. The important thing is to get the right weapons.}
{270}{}{Oh wow, sounds good. Tell me where it's located.}
{271}{}{You're fooling me. Show me that place first.}
{272}{}{Uhh, no, what if you're trying to fool *me*? This is my only opportunity to pay back the debt. But I need reliable partners for such an enterprise. So what do you say, are you coming with me?}
{273}{}{I need time to prepare.}
{274}{}{Of course. Take weapons to use against the robots, but don't take anything you don't need. And by the way, that place is located in the impact zone of a nuke. There are still some radioactive zones there, but I know how to get past them.}
{275}{}{Alright. See you.}
{276}{}{I see right through people the likes of you. Today I'll walk away, but next time I may come back. With a baseball bat.}
{277}{}{Hey, I'm just making a business offer. I'm looking for partners, understand? But still, think about the offer.}
{278}{}{I'll be back.}

{280}{}{About your offer, I can now move out to the warehouse.}
{281}{}{Yes, fantastic! You definitely won't regret it. Let's go, I want to deal with my debt as soon as possible.}
{282}{}{Step forward.}