{100}{}{You see a slum dweller.}
{101}{}{You see a resident of the local slums.}
{102}{}{Some bastard killed her!}
{103}{}{I don't mind talking, but my stomach is rumbling. Well, you know.}
{104}{}{Thank you for the meal, señor.}
{1104}{}{Thank you for the food, señora.}

{110}{}{Are you all right?}
{111}{}{What's up?}
{112}{}{And everything is still the same with us.}
{113}{}{Come again if you want.}

{200}{}{Hi. What can I do for you?}
{201}{}{You? Probably nothing.}

{210}{}{Who are you?}
{211}{}{I'm Fred. My wife and I recently moved from the desert, where we raised a small herd of Brahmins. Or rather, they tried to grow it. In the end, our ranch collapsed due to drought and bandit raids. And so we decided to try our luck in the big city.}
{212}{}{Bye, Fred.}

{220}{}{Why do you live in this old building?}
{221}{}{It's not that bad. Better than living on the street. Vernon made an agreement with one gang to protect the area. But to live here, you have to pay tribute or work out your place in some other way.}
{222}{}{Who is Vernon?}
{223}{}{The manager of the community house. His office is on the right down the corridor.}
{224}{}{What kind of gang?}
{225}{}{Some muddy types in leather jackets and with nasty hairstyles. They're holed up in an old building in a nearby neighborhood. But it's better not to meddle with them.}
{226}{}{Clearly. Bye.}
{227}{}{Remind me, what's your name?}
{228}{}{And who are you?}

{230}{}{What can you tell us about this area?}
{231}{}{Many believe that this is the worst residential area in the city. But to Rednecks like us, even this seems like a great achievement.}