{100}{}{You see Buddy.}
{101}{}{You see a regular bum, incapable of doing anything. It is a wonder how he is still alive.}
{102}{}{Hey there, pardner. How are you?}

{200}{}{It's here. Be careful, robots are supposed to be inside. If you disable them, all the caps there will be ours.}
{201}{}{Then let's not waste our time. Wait here.}
{202}{}{I know that already.}
{203}{}{I need to learn more about that place first.}

{210}{}{We shouldn't stay here for too long.}
{211}{}{Wait here.}
{212}{}{The sun will set down soon. Let's hurry up, okay?}

{220}{}{What is this place anyway?}
{221}{}{A Pre-War Nuka-Cola warehouse. Looks like they stored the drinks here and then transported them to the shops. The factory where they poured it into the bottles was destroyed by a nuclear blast.}
{222}{}{It's a wonder why this place hasn't been looted into nothing by scavengers.}
{223}{}{The surrounding ruins make getting here hard. Plus, a nuclear impact zone is nearby, that scares off a lot of people. And, of course, the damned robots.}
{224}{}{Do you have any ideas on how to disable them?}
{225}{}{I thought *you* would have some. There's probably a switch inside, or something like that. I know little about technology. Especially Pre-War tech. Really, nobody knows how they work, except for the members of the church.}
{226}{}{Remind me, what are we searching for?}
{227}{}{Caps! A loooot of bottlecaps.}
{228}{}{Alright.}
{229}{}{I'll be back.}

{250}{}{Here are all the caps that were left in the warehouse.}
{251}{}{A whole box? Damn, this is an entire fortune! We're in luck. We're now richer than the majority of the city's inhabitants, understand?}
{252}{}{Not so fast. Pay back the casino debt first.}
{253}{}{Ah, yeah. Uh, sure. I completely forgot about it from the excitement. Here, take it.}
{254}{}{Great. Now, give me my share - half of what remains.}
{255}{}{Oof, that's less than I expected. The remaining caps will be barely enough to pay for rent and other things. And then I'll be left with nothing again.}
{256}{}{That's fair. You shouldn't have brought yourself to this state. And now I better get back to the city. Bye.}
{257}{}{You know, I changed my mind. I'm taking ALL the caps.}
{1257}{}{You know, I changed my mind. I'm taking ALL the caps.}
{258}{}{No! You can't do this to me! We're partners, I told you about this place... Dammit, one day... one day I'll earn a lot of caps and I'll put a bounty on your head, and then I'll play football with it. You'll remember this day.}
{259}{}{Sure. Bye, loser.}
{260}{}{In that case, you leave me no other choice - I will end you right now.}