{100}{}{This is Steve.}
{101}{}{You see one of the fans of the ring.}
{102}{}{Wow. I knew that tinsmiths are masters, but I didn't even think about it...}
{103}{}{That letter was very helpful. Thanks for the delivery.}
{104}{}{Do you also take risks on betting?}

{200}{}{What? Do you also play in fights?}
{201}{}{No. I'm looking for a man named Steve. He lives in the house opposite.}
{202}{}{Wait a minute, it's you! Wow, listen, the last fights were, of course, stunning. But why don't you have a couple more rings? I would lift great caps on you.}
{203}{}{It's not up to me.}
{204}{}{Ah, I see. That little guy is also greedy for caps, right? Okay, let's go.}
{205}{}{I'm looking for a man named Steve. He lives in the house opposite.}
{206}{}{I'm not fighting anymore. And period.}
{207}{}{Okay, okay, right-hook man, don't strain yourself so much.}
{208}{}{Spit. Just tell me who's Steve, who lives across the street.}
{209}{}{It's me. What do you want?}
{210}{}{I'm from the delivery service. A letter for you. Sign up and get it.}
{211}{}{Is this some kind of joke? I can barely read. Who could have texted me?}
{212}{}{So you're not the Steve I need. Goodbye.}
{213}{}{Hey, wait. Of course I'll sign it. So, are there enough fingerprints? Great, come here...}
{214}{}{[Next]}
{215}{}{I don't know who's texting you. But you have five caps for delivery.}
{216}{}{So do I have to pay for it yet? Well, no. This is definitely some kind of deception. Don't expect me to fall for it.}
{217}{}{Well good. Take the letter like this. It only interferes with things in the backpack.}
{218}{}{It's intriguing. Okay, here are five caps. I really hope it's worth it.}
{219}{}{Here you go.}
{220}{}{Yes, everything is fine. Just sign and take the letter.}
{221}{}{What? Do you also play in fights?}
{222}{}{No, I'm looking for someone to give the letter to. And the letter is missing somewhere.}
{223}{}{Yes, the problem.}
{224}{}{Uh, I'm going to look. Later.}

{227}{}{Hi. I'm still trying to lift the bottlecaps in the ring. But something doesn't work out. It looks like it's time to get out of this stuffy city.}
{228}{}{Speak for yourself. I've had enough of country life on the plantations. Bye.}
{229}{}{Well yes. Life is easier and calmer away from the noisy city. Later.}

{230}{}{ (takes the letter, unfolds it and reads it slowly) So... so...}
{231}{}{Is this really a letter for you?}
{232}{}{My uncle writes from Casa Grande. It looks like we have a meeting scheduled with him. Thank you, it was a very valuable letter. True.}
{233}{}{What do they write?}
{234}{}{So I can leave with a feeling of deep satisfaction. Have a nice day.}