{100}{}{You see a bandit.}
{101}{}{You see a young man with a defiant behavior.}
{102}{}{Is this your motorcycle? Oh, I'm sorry. I thought he was nobody's. Of course, uh, take it, we don't mind.}
{103}{}{Fuck off}
{104}{}{Hey, is that your bike?}

{200}{}{Hey, is that your bike?}
{201}{}{Exactly.}
{202}{}{Maybe so. What's it to you?}
{203}{}{You're wrong. This is my bike. Any problems? Ah, you probably want to buy it. A good choice. The price is 500 caps. And hurry up before I change my mind.}
{204}{}{Why do you need it? You can't use it anyway.}
{205}{}{Do you take me for an idiot? This bike will interest any boss in the city. If you don't pay, someone else will.}
{206}{}{Give me my bike. Now I'm asking nicely, but there won't be a second time.}
{207}{}{Give me time to pack the bottlecaps.}

{210}{}{Brought 500 caps?}
{1210}{}{Did you bring 500 caps?}
{211}{}{Did you bring 700 caps?}
{1211}{}{Did you bring 700 caps?}
{212}{}{Give me time to pack the bottlecaps.}

{220}{}{This is my motorcycle. Give me the ignition key. Immediately.}
{221}{}{And then what? Will you start digging? Yes, our gang *owns* the whole area. You snap at me, you snap at the whole gang. Do you understand?}
{222}{}{I don't give a damn about you and your whole gang. Give me the key or you'll die.}
{223}{}{Sorry, I don't want problems with you and your guys.}
{224}{}{By the way, I've changed my mind. The price has increased to 700 caps.}
{225}{}{Gr-rm...}
{226}{}{It's stupid. I'll just kill you.}

{230}{}{Here are the bottlecaps. Now give me the ignition key.}
{231}{}{(casually throws the key on the ground) Take it. I didn't know how to use it anyway. (with a grin, he heads deeper into the area, weighing the caps in his hand with a satisfied look)}
{232}{}{Thanks, uh, good purchase.}
{233}{}{Someday I'll lie in wait for you in bed at night and cut your throat. And I will laugh. Yes, laugh.}
{234}{}{Not so fast, you bastard. Now give me all my caps.}

{240}{}{You're a fool if you decided to run into a champion. Do you want to make sure of this?}
{241}{}{You're a fool if you decide to go against a Follower. My brothers won't let it go so easily.}
{242}{}{Do you know who the magistrals are? I'm one of them. Don't underestimate us.}
{243}{}{ (grinning like a dog cornered) H-damn, I didn't know... Sorry, here's the key... Is everything okay now? I'll, uh, go.}
{244}{}{Get out.}
{245}{}{No problems. Let's forget about this misunderstanding.}