{100}{}{You see a slum dweller.}
{101}{}{You see a slum dweller. A pitiful sight.}
{102}{}{You see a slum dweller. He picks at his ear.}
{103}{}{You see a slum dweller. He combs the dirt out of his hair.}
{104}{}{You see a slum dweller. He lovingly adjusts his only rags.}
{105}{}{You see a local. His bald spots speak of an unhealthy situation in the slums.}

{110}{}{I'm hungry.}
{111}{}{I wish I was lucky enough to catch a rat and roast it for dinner.}
{112}{}{I can't believe that once *clean* water was drained into the toilet.}
{113}{}{Empty talk only increases hunger.}
{114}{}{We need food.}
{115}{}{They say that mutant people have been living in sewers since the day of the Great War.}
{116}{}{A corpse was found again in the next block.}
{117}{}{Don't play in the casino if you don't want to be enslaved.}
{118}{}{The cult of Fire has eyes and ears everywhere.}
{119}{}{I would not like to be among these sectarians.}
{120}{}{Hi.}
{121}{}{See you later.}
{122}{}{It's time for me to go.}
{123}{}{Don't make trouble for us.}
{124}{}{Do you ever take this thing off on your hand?}
{125}{}{What is a "tele-visor"?}
{126}{}{Isn't a "mailbox" a garbage can?}
{127}{}{I'm sorry, but I have to get back to my idleness.}
{128}{}{This dirty water is not even worth extinguishing fires.}
{129}{}{Is it true that there is white solid water in the mountains?}
{130}{}{Here the sky is always covered with smog.}
{131}{}{Not a single rain in many years.}
{132}{}{The day has passed, and I'm still alive. This is luck.}
{133}{}{After the scavengers, nothing of value remains on the ruins.}