{100}{}{You see a junkie.}
{101}{}{You see a disheveled guy. Judging by his appearance, things are going badly for him.}
{102}{}{Ah... I'm... suffocating...}

#Answers after healing
{110}{}{Leave me alone.}
{111}{}{I need to lie down.}
{112}{}{I'll start a new life tomorrow.}
{113}{}{Do you have any dope?}
{114}{}{You won't tell anyone, will you?}

{115}{}{(looking around) They may be watching us.}
{116}{}{Why did they kill Gonzalez?}
{117}{}{Gonzalez would get anything, but I had nothing to pay with.}
{118}{}{Surely Gonzalez was killed by Followers.}
{119}{}{If they got to Gonzalez, I'm in danger too.}

#The first dialog
{200}{}{(shuddering as if in a fever) W-what do you want?}
{201}{}{You don't look well. Are you sick with something?}
{202}{}{I'm s-totally s-okay.}
{203}{}{I can't believe it.}
{204}{}{S-listen, I'm s-okay. Leave me alone.}
{205}{}{Whatever you say.}
{206}{}{With pleasure. Suddenly you will infect.}
{207}{}{Not so fast. Answer my questions first.}

#Repeat dialog
{210}{}{Os-put m-me.}
{211}{}{Bye.}

{212}{}{You again?}
{213}{}{I see you're coming back to normal. You look better than when we last met.}
{214}{}{I'm worse off than ever! Gonzalez leaned back, and now there's nowhere to get the drugs he was preparing. Where will I take a new dose?}
{215}{}{When the withdrawal is over, you won't want to go back to it. That's the point. Be.}
{216}{}{Exactly. And say "thank you" that you didn't go after your pusher.}

{220}{}{Who are you anyway?}
{221}{}{Me? I'm Larry. And what?}
{222}{}{What are you doing, Larry?}
{223}{}{Why are you bothering me? I just live here and earn as I have to.}
{1223}{}{Why are you bothering me? I just live here and earn as I have to.}
{224}{}{You don't seem to be doing anything at all. Bye.}
{225}{}{I'm sorry to see you like this. Don't despair.}

{230}{}{You don't look well. You need a doctor.}
{231}{}{I don't need a doctor! I'm fine! Leave me alone!}
{232}{}{Whoa, don't be so nervous...}
{233}{}{Let me examine you, I'm a doctor.}
{234}{}{I don't need a doctor, I just need some medicine. And I'll be fine again.}
{235}{}{I doubt. Judging by the dilated pupils and other symptoms, you're pretty hooked on some kind of trash.}
{236}{}{Maybe so. What's it to you?}
{237}{}{Who supplies you?}
{238}{}{Gonzalez. Everyone knows that he is pushing a treat on the street near the arena. He can have a killer dope, but I don't have enough caps for a new dose. Let me lie down quietly, tomorrow I'll be as good as new.}
{239}{}{Right. That's your problem.}

{240}{}{So are you cursed by all the locals?}
{241}{}{Go to hell! It's my business what kind of dope and when to take it.}
{242}{}{What kind of drugs do you take?}
{243}{}{A mixture of psycho, painkillers, and mentats. Killer dope, you start seeing leprechauns and flying cars. Yes, not simple leprechauns. Small ones. Tiny ones like that... At least some joy in these fucking slums.}
{244}{}{Why did you even take up this stuff?}
{245}{}{Well, you know, initially it was a cure for fever. And it cured me, but then I realized that I couldn't stop. It's not so easy to quit.}
{246}{}{And who supplies you?}
{247}{}{All the chemistry in the slums is from Gonzalez and the scavengers.}
{248}{}{Hmm. I'm gonna go talk to this Gonzalez guy.}

{250}{}{Larry, you have to give it up.}
{251}{}{Go to hell. I feel good. I don't need any help. I know what I'm doing.}
{252}{}{Well, well.}
{253}{}{Your pusher won't sell you any more doses.}
{254}{}{What?! But why?}
{255}{}{Because it's time for you to quit.}
{256}{}{Yes, I'll die without medicine! Where will I take a new dose now?}
{257}{}{Think about the future. This is not the way out, Larry.}
{258}{}{What do you understand? I have everything under control. I know when to stop.}
{259}{}{Well, well.}
{260}{}{Stop poisoning your life. Your wife and kids need you, Larry.}
{261}{}{Yes... I've already forgotten about them... What a fool I am... Thanks, I'll try to start over.}
{262}{}{I take you at your word. Goodbye, Larry.}
{263}{}{If you continue like this, you will recline.}
{264}{}{Your body is on edge, Larry. You're going to die soon.}
{265}{}{Are you a doctor? Why the hell are you scaring me so much?}
{266}{}{Yes, I'm a doctor. And I'm telling the truth.}
{267}{}{Damn it... I know I don't have long left. But I can't stop. What should I do?}
{268}{}{Well, you can neutralize addiction with another addiction. Try this recipe.}
{269}{}{Wow, will that help? It looks like I have no choice. Thank you, doc.}
{270}{}{Be healthy, Larry.}
{271}{}{No, sorry, I'm not a doctor.}
{272}{}{This stuff will kill you someday. I have mentats. Try it, maybe it will clear your head.}