{100}{}{You see a child living in these slums.}
{101}{}{You see a child from the local slums. Life has taught him much.}

{110}{}{Hi.}
{111}{}{You got a gun?}
{112}{}{Dad promised to get a gun. Then I'll kill everyone who's treating me badly.}
{113}{}{When I grow up, I want to become a pimp.}
{114}{}{How are you doing?}
{115}{}{I don't know you.}
{116}{}{What are you asking me for?}
{117}{}{Don't touch me.}
{118}{}{I can't talk to strangers.}
{119}{}{What will you give me?}