{100}{}{Here is a child of the slums.}
{101}{}{You see a child from the local slums. Life has taught him a lot.}

{110}{}{Hello.}
{111}{}{Do you have a gun?}
{112}{}{Dad promised to get a gun. Then I will kill everyone who treated me badly.}
{113}{}{When I grow up, I will become a pimp.}
{114}{}{How are you?}
{115}{}{I don't know you.}
{116}{}{What do I need?}
{117}{}{Don't touch me.}
{118}{}{I can't talk to strangers.}
{119}{}{And what will you give me?}