{100}{}{You see Vernon.}
{101}{}{You see a man in a worn-out suit. The circles under his eyes and a nervous tic suggest exhaustion.}
{102}{}{This is, of course, a dangerous region, but this...}
{103}{}{Please stop them! They'll ruin everything here!}

#First dialogue
{200}{}{(noticing you, the man frowns and the man frowns and nervously twitches his right eye) I don't think I saw you before. What are you looking for here?}
{201}{}{I need a place to sleep. You rent rooms?}
{202}{}{Sorry, they're all taken. There's barely any room here, even without you.}
{203}{}{What is this place?}
{204}{}{It's a kind of communal housing. If you just wandered in here, it's best for you to go.}
{205}{}{Why?}
{206}{}{Harsh local customs. All people here know each other well and treat newcomers with suspicion.}
{207}{}{I see. In that case I really *should* go.}
{208}{}{Not surprising for such a shitty region. Bye.}
{209}{}{I'm not leaving until I get some answers to my questions.}

{210}{}{I dunno. And what place is this anyway?}
{211}{}{This is communal housing. You have business here? Or maybe acquaintances? If not, you better go.}
{212}{}{Why are you trying to drive me away?}
{213}{}{(displeased sleepy grunting) Wh... wha... Dam-m-it, do you even know how late it is...}
{214}{}{I apologize that I'm disturbing you.}
{215}{}{I don't give a shit.}

{220}{}{(your arrival makes the man stand in awe, then nervously twitch his right eye) How unexpected, to see such a respected figure in our ghetto. Are you looking for something?}
{221}{}{In truth, I am searching for a place to sleep. Are there any availaible rooms?}
{222}{}{I'm afraid all of them are taken. And you surely wouldn't like it here anyway.}
{223}{}{Why?}
{224}{}{How do I put it... You don't exactly fit in here, in the slums. We have bad living conditions and harsh tenants. You could even be robbed.}
{225}{}{Not surprising for such a shitty region. Bye.}
{226}{}{I see. In that case I really *should* go.}
{227}{}{Before I go, I want to ask a few questions.}
{228}{}{I was curious about what this place is, exactly.}
{229}{}{It's a kind of communal housing. If you just wandered in here, it's best for you to go.}
{230}{}{Why?}

{240}{}{Hey, champion! That was an incredible fight. How can I help such a respected figure?}
{241}{}{I don't know. What is this place anyways?}
{242}{}{This is called "communal housing". I am the manager here. Though I do not think people of your status would find this place interesting. Our ghetto is inhabited by the... less successful residents of the city.}
{243}{}{Then please answer a couple of my questions.}
{244}{}{It was obvious from the start that this place is a hellhole. I will not be seen here again.}
{245}{}{Is it okay if I take a look at this place? Great, see you later.}
{246}{}{Hey, champion! That was an incredible fight. How can I help such a respected figure?}
{247}{}{I want to talk to you.}

#Pusher death
{250}{}{(Vernon is sitting at the table, covering his head with his hands; he sways a little, quietly moaning)}
{251}{}{What's new with you?}
{252}{}{Ah? Ah, it's you... That damn headache... Before, I took medicine that Gonzales found. But now he's dead and I don't know where to find them anymore... Ouch...}
{253}{}{Sucks to be you, I guess. Well, so long.}
{254}{}{I'm sorry. When I killed that pusher, I thought the situation for everyone here would improve.}
{255}{}{You thought WHAT? Shit! Yes, Gonzales got drugs for some people who wanted them, but for others he got medicine and painkillers. Why the fuck did you need to kill him?}
{256}{}{None of your business.}
{257}{}{Yes... of course... Get the hell out of my office.}
{258}{}{Watch your tongue or you'll end up like your pusher.}
{259}{}{Uh-uh.}
{260}{}{His goods were not of sufficient quality.}
{261}{}{And that's the only reason? You're insane! Get the hell out of here, immediately.}
{262}{}{}
{263}{}{I dunno. You need a reason to do that?}
{264}{}{You're insane! Get out of here and never come back.}

#Racket after the ending
{270}{}{Oh, thanks, amigo. If not for you, these hooligans would have ruined this entire place, and quite possibly would have injured someone.}
{271}{}{What did they want from you?}
{272}{}{It's just a racket. After the Cardinal gang fell apart, all hell broke loose in the slums. Now any loser who, before this, feared even showing up on the streets can rob and beat people consequence-free.}
{273}{}{Weren't the cardinals bandits themselves?}
{274}{}{Yes, but they watched over the region and didn't allow such things to happen. I very much hope that this wave of chaos ends soon. Someone is bound to try and take power over the region for themselves. And then it will all begin anew.}
{275}{}{What a fun place you have here. Catch you later.}
{276}{}{Nobody could have predicted this. Good luck out here.}

#Repeated dialogue
{300}{}{So, what do you need?}
{301}{}{How can I help you?}
{302}{}{You better go.}
{303}{}{Goodbye.}
{304}{}{Why are you standing around here?}

{310}{}{I'm investigating an attack on the Followers. What do you know about this?}
{311}{}{The situation has become somewhat more clear.}
{312}{}{The situation has become somewhat more clear. It is time to discuss this with Aaron.}
{313}{}{(frowning, gives out a nervous tic) So you are another of the Followers' bloodhounds? I told everything to the monks. Leave us alone.}
{314}{}{(frowning, reproduces a nervous tic) I did not expect you to be initiated too. But I already told the monks all I know.}
{315}{}{Well then you'll have to tell it again.}
{316}{}{We didn't kill anyone. The monks were going around the tenants in search of alms and, of course, left with nothing. When they went *outside* they were captured by people in masks and were hanged on the street lights. We do not know who they were. But they were clearly well-prepared to commit this attack.}
{317}{}{Is any one of the tenants involved in this?}
{318}{}{The locals are afraid of people from the church. Nobody would dare commit such a crime, especially right by their own home.}
{319}{}{There are rumours that the residents of this building do not like the monks.}
{320}{}{And why exactly *should* we like them? The monks bathe in luxury while we drown in poverty. They take weapons from us and forbid Gonzales from selling medicine. But look at the tenants. You think any one of these poor sods could commit such a well-organized attack?}
{321}{}{Who would be capable of commiting such a daring attack, then?}
{322}{}{Only the Atomicists and Orris's gang. But the former always kept far away from the city. And the latter don't need problems with the church.}
{323}{}{I have no more questions.}
{324}{}{I don't believe you. You must be hiding something.}
{325}{}{I know what I'm talking about. If you don't believe me, prove otherwise.}
{326}{}{I am in a kind mood today and thus will break only two of your fingers until I learn everything I want.}
{1326}{}{I am in a kind mood today and thus will break only two of your fingers until I learn everything I want.}
{327}{}{Agh...}
{328}{}{Wait! Think about it, would we attack the monks near our own home? It's far too reckless. But there are rumours of a secret society of fire-haters. After all, in the past, Aaron caused a revolution with the help of the Church of the Fire and ravaged the entire city. Many likely want to take revenge upon him.}
{329}{}{An interesting idea. I suppose that today you are worthy of my mercy.}
{330}{}{Enough lies! I will kill you, worthess molecule.}
{331}{}{Don't rush to poke with your fiery stick, cultist. We can fight too, when we need to.}
{332}{}{Gr-r!}
{333}{}{Tell me about the attack on the monks again.}

#Interrogation
{350}{}{Who are you and what is this place?}
{351}{}{I'm telling you, this is communal housing. And I am Vernon, it's manager.}
{352}{}{That is everything I wanted to know.}
{353}{}{Why did you say the region is dangerous?}
{354}{}{Bums and bandits are not the best people to be among in any city.}
{355}{}{What kind of bandits are you talking about?}
{356}{}{I should not have said that. There are several gangs nearby. The Atomicists to the east, Orris' men to the north and a couple of small gangs in every block.}
{357}{}{What can you tell me about the atomicists?}
{358}{}{Strange people. They remain neutral at all times and try not to get involved in what happens here. But they do let some people near.}
{359}{}{Who is Orris and why is his gang well-known?}
{360}{}{Orris practically owns our entire block. Don't even think about rebelling against his goons if you like living.}
{361}{}{I'm searching for Steve. I have been told he lives here.}
{363}{}{So he's in the arena.}
{362}{}{I don't know why you would be searching for that rascal and I don't want to know. Lately he's been spending most of his time in the arena, hoping to earn money on bets, the fool.}

#Quests
{370}{}{Looks like you have problems. I can help, you know.}
{371}{}{Oh really? You know, the city has taught me not to trust anyone who offers to help with a smile on their face. What are you really trying to achieve?}
{372}{}{I want to help. That's the truth of the matter.}
{373}{}{Tell that to someone else. In any case, you won't earn caps here.}
{374}{}{Well, you're right about that. I need to establish myself in this city.}
{375}{}{Heh. I see. But you won't earn caps here. Though earning some good old-fashioned reputation can be good as well.}
{376}{}{You don't want it - fine. My job is to make an offer.}
{377}{}{And still - what problems do you have?}
{378}{}{Well, there's a couple tenants who are walking problems. Can you evict them?}
{379}{}{Sure. Who are they?}
{380}{}{Uhh, no. I don't get involved in such things.}
{381}{}{One is called Larry. He became addicted to drugs and is spending all his caps on them. He's a smart man, but the drugs have clouded his mind. I can't get rid of him openly, since the pusher is definitely not going to like losing a client.}
{382}{}{Alright. Who's the second one?}
{383}{}{Buddy. He lives in a room nearby. He didn't cause problems until he became addicted to gambling. Now he has so much debt that even I am threatened by loan sharks.}
{384}{}{Nobody wants to be associated with him anymore. Obviously, he can't pay me as well. He either pays the rent or gets out onto the streets. I've had enough.}
{385}{}{Remind me, what drug addict were you talking about?}
{386}{}{Larry. Right now he's probably in his dirty room, wasting his life.}
{387}{}{Got it. Bye.}
{388}{}{Remind me what tenant owes rent.}
{389}{}{All of them, really, but Buddy owes the most. And he has problems with the casino, and I don't need that here.}
{390}{}{Damn, gambling is serious stuff.}
{391}{}{Larry won't disturb the tenants any longer. He's dead.}
{392}{}{WHAT? My god, why did you have to resort to that?}
{393}{}{Well, you told me to get rid of him.}
{394}{}{But that's not what I meant! The slums already have a terrible reputation, and now people will talk behind my own back.}
{395}{}{Well, maybe you should have specified the mission better. Now it's too late.}
{396}{}{Yeah. Of course. I do hope they forget about all of this soon. And it will get a bit more calm here without Larry.}
{397}{}{Exactly. Goodbye, Vernon.}
{398}{}{Larry will not disturb the tenants any longer. He managed to deal with his addiction.}
{399}{}{Unbelievable! How did you do it? Nobody believed Larry could do something like that. Everyone thought fixing him was hopeless.}
{400}{}{I have my methods. He simply needed motivation.}
{401}{}{I don't even know what to say. Thank you.}
{402}{}{You're welcome, Vernon.}
{403}{}{Good. I'll talk with them first.}

{404}{}{Buddy will soon pay rent.}
{405}{}{Great work! I didn't think anyone or anything could save him from a bloody reckoning. How did you manage to fix his mind up?}
{406}{}{The most important thing is to find a special approach for every client. Goodbye, Vernon.}
{407}{}{Buddy no longer lives here. He lives on the street, like a lousy stray dog.}
{408}{}{Good. We don't need unnecessary problems here. Thanks for the help.}
{409}{}{You're welcome.}
{410}{}{Buddy no longer lives here. In fact, he is no longer living at all.}
{411}{}{He was... killed? My god, these loan sharks are real beasts.}
{412}{}{There was no other way.}
{413}{}{Don't tell me the details. I very much hope that his debt in the casino doesn't affect me and the other tenants. It would have been better if he simply went to another place.}
{414}{}{Yeah, this wasn't the cleanest way. But on the other hand, your problem is solved. Bye.}
{415}{}{Buddy has dealt with his casino debt. He will soon pay you rent.}
{416}{}{Sounds great! How did you manage to fix his mind up?}
{417}{}{The most important thing is to find a special approach for every client.}
{418}{}{Great work! I didn't think anyone or anything could save him from a bloody reckoning. You know, these loan sharks are real beasts. Thanks for the help.}
{419}{}{You're welcome, Vernon.}

{420}{}{All your assignments have been completed. How else can I help you?}
{421}{}{I can't believe you're helping us, poor people for free. You're an unusual person. But that was nothing compared to what we have to suffer day after day.}
{422}{}{What are you talking about?}
{423}{}{Our primary problem is the Red Cardinal gang. Essentially, they own this entire region and it's inhabitants. Nobody dares go against them. Even the mercenaries from the guild don't want to get involved. Nobody cares about us, and the gang is constantly growing and putting more pressure on us.}
{424}{}{You're out of your mind. Do you even realize what you're asking for?}
{425}{}{Asking? Uhh, no, not really, just complaining. Getting rid of a gang like that sounds great. But you already did so much for us. Maybe you have some ideas? Actually, we spent all our latest caps putting a bounty on Orris' head. Without him, the gang will fall apart. That would give us, ordinary people some rest.}
{426}{}{I'll have to think long and hard about this assignment. See you later, Vernon.}
{427}{}{Fine, I'll help you. I'm hoping the payment will be adequate.}
{428}{}{You want to get rid of the gang? That's easy. These street dogs have never seen a real fight.}
{429}{}{Oh! We'll give you all the caps we have if you kill their leader Orris. Without him, the gang will be weakened. That will give us, ordinary people some rest.}
{430}{}{Don't worry about the caps. I'll deal with that problem.}
{431}{}{Get your caps ready, because for his head I'll take EVERYTHING you have.}
{432}{}{Tell me more about the Red Cardinals and their gang.}
{433}{}{The gang owns this entire region. They have tens of members. They can fight well and they have weapons. The leader is called Orris. Scary type, gives rest to no one. Not us, not the bandits themselves. Please, rid us of his recklessness. Nobody will want to help us except you.}
{434}{}{Orris has been removed. His gang is losing power.}
{435}{}{You're a true hero! We were long hoping for a miracle, and you give us hope for a new life. Thank you sincerely.}
{1435}{}{You're a true heroine! We were long hoping for a miracle, and you give us hope for a new life. Thank you sincerely.}
{436}{}{Good. The important thing is, nobody is threatening you now.}
{437}{}{To hell with these tearful speeches. Give me the caps. You think I risk like that out of the goodness of my heart?}
{438}{}{Uhh, yes, take these caps, there are 217 here. It's all we could collect.}
{439}{}{You fool! I wouldn't take that risk if I knew I would receive so little. Well, I'll have to take what is availaible.}
{1439}{}{You fool! I wouldn't take that risk if I knew I would receive so little. Well, I'll have to take what is availaible.}
{440}{}{Better than nothing.}
{441}{}{Sorry that there is so little. You can rest in our house for however many times you want.}
{442}{}{Goodbye, Vernon.}
{443}{}{Give your caps to those you collected them from. All I wanted was to make the world more just.}
{444}{}{You truly are an unusual person. You will always be a welcomed guest in this house.}
{445}{}{Goodbye, Vernon.}
{446}{}{I of course, thank you for your help with Larry and Buddy, but you better go. I'm sorry, but I don't want to be associated you.}
{447}{}{Not good from your side.}
{448}{}{Your loss, friendo.}