{100}{}{Badie is in front of you.}
{101}{}{You see an ordinary beggar who is not capable of anything. It's amazing that he's still alive.}
{102}{}{Hello, partner. How are you?}
{103}{}{Someday I will take revenge on you.}

{110}{}{I'm hopeless.}
{111}{}{I'm finished.}
{112}{}{There is only one lid left.}
{113}{}{I lost the last one at the casino.}
{114}{}{I don't know how I'm going to get out of debt.}
{115}{}{Impoverished in a couple of days.}
{116}{}{This may be the last day of my life.}
{117}{}{Can you borrow a thousand caps? I will return, ches-word.}
{118}{}{It looks like they're going to make a slave out of me soon.}
{119}{}{Soon I will be evicted to the street.}

{200}{}{Phew, don't scare me like that. I've been avoiding strangers lately.}
{201}{}{Who are you?}
{202}{}{My name is Badi, I live here. But I don't remember you.}
{203}{}{Don't be rude to me, you piece of shit.}
{204}{}{Well, hello, Badie. I }
{205}{}{.}

{210}{}{What do you want from me?}
{211}{}{From you? Nothing. Later.}

{220}{}{Vernon is tired of your endless debts. Pay or get out on the street.}
{221}{}{No, please don't kick me out! I'll pay Vernon, I just need some time to pay off the casino.}
{222}{}{Are you in debt to the casino?}
{223}{}{Well yes. I admit it was stupid. There was no need to hope for luck. But that day I was so lucky that I couldn't stop.}
{224}{}{I don't care what you have. Come on, get some fresh air.}
{225}{}{I've lived here for years! Is that how Vernon treats the guests? Okay, we'll see who's who.}
{226}{}{Get out of here.}
{227}{}{You can be understood. How much do you owe Vernon?}
{228}{}{37 caps for last quarter.}
{229}{}{I know what kind of home to lose. Don't worry about the caps, I'll pay your rent.}
{230}{}{Really? God bless you! Thanks! Thank you!}
{231}{}{For me, these are small things. I }
{232}{}{. Remember my name.}
{233}{}{Bye.}
{234}{}{Okay, I'll give you some more time.}
{235}{}{Really? Thanks! I will collect the bottlecaps soon, I promise.}
{236}{}{Do your best.}

{250}{}{You owe the casino a round sum. It's time to pay the bills.}
{251}{}{I gave everything I had! There's nothing left! Please give me a little more time. I will return everything!}
{252}{}{You've had enough time. What is the problem to assemble the bottlecaps?}
{253}{}{There is unemployment in the city, and besides, my reputation is undermined because of debts. I survive only by collecting garbage from the ruins.}
{254}{}{Looks like you really have nothing to charge. Sit in your shit and continue.}
{255}{}{If you want to stop my fist, say something encouraging.}
{256}{}{Wait, don't go that far. If Don Diego wants his caps back, he needs me alive and unharmed. Is that right? And if not, he would have sent me into slavery long ago. You get it, what's the deal?}
{257}{}{Damn, I'm wasting my time with you.}
{258}{}{How are you going to repay your debts?}
{259}{}{I have a plan. I just need a little time to prepare.}
{260}{}{What, another one of your lying excuses?}
{261}{}{What are you up to? Come on, tell me.}
{262}{}{Enough of this shit. Give me the bottlecaps or I'll break your bones.}
{263}{}{Um, listen, you can make money, too. It's obvious from you that Don Diego doesn't take anyone to work.}
{264}{}{It's intriguing. Tell me.}
{265}{}{Your insolence knows no bounds. But I'll listen to what you come up with this time.}
{266}{}{There is one place where there are just MOUNTAINS of caps. I'm not lying, it's true. Nobody knows about him except me. We'll go there, open the warehouse and take out everything that has survived, and we'll divide the bottlecaps in half. Well, is it a deal?}
{267}{}{Something is wrong here. Why didn't you do it before?}
{268}{}{Sounds like a blatant lie. Tell me right away - what's the catch?}
{269}{}{There is one overlay. It seems that the warehouse is guarded by a couple of old robots. Someone had already tried to get past them and received a shocker in the balls. But you will definitely resist. The main thing is to take a suitable weapon.}
{270}{}{Wow, that sounds encouraging. Where is it located?}
{271}{}{You're lying to me. Show me this place first.}
{272}{}{Uh, no, what if you outsmart me? This is the only way for me to get even with my debts. But I need reliable partners for such a business. What do you say, will you come with me?}
{273}{}{I need time to prepare.}
{274}{}{Sure. Take weapons against robots, but don't take anything extra. Yes, by the way, it is located in the zone of nuclear destruction. There are still radioactive zones there, but I know how to get around them.}
{275}{}{I see. See you later.}
{276}{}{I can see through people like you. I'll leave peacefully today, but next time I can come back with a baseball bat.}
{277}{}{Hey, I'm just offering a business. This is a partnership deal, you know? But you still think about the offer.}
{278}{}{I'll be back.}

{280}{}{About your offer. I can move out to the warehouse.}
{281}{}{Yes, great! You definitely won't regret it. Come on, I want to get even with my debts as soon as possible.}
{282}{}{Go ahead.}