{100}{}{You see a slum dweller.}
{101}{}{You see an inhabitant of the local slums.}
{102}{}{Some bastard killed her!}
{103}{}{I'm not against talking, but I have rumbling in my stomach. You understand.}
{104}{}{Thank you for the food, seignior.}
{1104}{}{Thank you for the food, seigniora.}

{110}{}{Is everything alright?}
{111}{}{How are you?}
{112}{}{As usual.}
{113}{}{Come by later if you want.}

{200}{}{Hello. How may I be of service?}
{201}{}{You? I suppose, not at all.}

{210}{}{Who are you?}
{211}{}{I'm Fred. Recently, my wife and I relocated here from the desert, where we were growing a small herd of brahmin. Or rather, tried to grow. In the end, our ranch failed due to drought and raiders. So we decided to try our luck living in a big city.}
{212}{}{Bye, Fred.}

{220}{}{Why are you living in this old building?}
{221}{}{It's not so bad. Better than living on the streets. Vernon has managed to make an agreenment with a gang to defend the region. But to live here, you have to pay tribute or otherwise earn your lot.}
{222}{}{Who's Vernon?}
{223}{}{The manager of this communal housing. His office is to the right, down this corridor.}
{224}{}{What gang?}
{225}{}{Some shady types in leather jackets and tasteless haircuts. They're in the old building in the neighboring region. But it's best not to go there.}
{226}{}{Will keep that in mind. Bye.}
{227}{}{Remind me, what is your name?}
{228}{}{Who are you?}

{230}{}{What can you tell me about this region?}
{231}{}{Many believe it to be the worst residential region in the city. But to rednecks like us, even that feels like a big achievement.}