{100}{}{Badie is in front of you.}
{101}{}{You see an ordinary beggar, incapable of anything. It's amazing that he's still alive.}
{102}{}{Hello, partner. How are you?}

{200}{}{It's here. Be careful, there must be robots inside. If you turn them off, then all the bottlecaps will be ours.}
{201}{}{Then let's not waste time. Wait here.}
{202}{}{I know without you.}
{203}{}{I need to know about this place first.}

{210}{}{Don't stand here too long.}
{211}{}{Wait here.}
{212}{}{Night is coming soon. Let's hurry up, okay?}
{220}{}{What kind of place is this anyway?}

{221}{}{Pre-war warehouse of cola kernels. Apparently, the drink was stored here and then taken to the shops. The factory itself, where it was bottled, was destroyed by a nuclear explosion.}
{222}{}{It's amazing why this place hasn't been looted by scavengers yet?}
{223}{}{It's hard to get here because of the surrounding ruins, so many people just don't know about it. In addition, there is a nuclear explosion zone nearby, which scares many away. And, of course, the damn robots.}
{224}{}{Any ideas on how to disable robots?}
{225}{}{I thought you'd take it on yourself. There's probably a switch somewhere inside, or something. I don't know anything about technology. Especially pre-war. No one understands it at all, except the ministers of the Cathedral.}
{226}{}{Remind me, what are we looking for?}
{227}{}{bottlecaps! Lots and lots of bottle caps.}
{228}{}{Clear.}
{229}{}{I'll be back soon.}

{250}{}{Here are all the bottlecaps that have been preserved in stock.}
{251}{}{A full box? Hell, it's a fortune! That's luck. We are now richer than most of the residents of the city, can you imagine?}
{252}{}{Not so fast. Pay back the casino's debt first.}
{253}{}{Oh, yes. Uh, right. In my joy, I completely forgot. Here you go.}
{254}{}{Great. Now give me my share - half of what's left.}
{255}{}{Ugh, it turned out to be less than I expected. The remaining caps are barely enough for me to pay off my rent and other debts. And I will find myself with nothing again.}
{256}{}{That's fair enough. There was nothing to bring yourself to such a state. And now it's time to go back to the city. Later.}
{257}{}{You know, I've changed my mind. I'm taking ALL the caps for myself.}
{1257}{}{You know, I've changed my mind. I'm taking ALL the caps for myself.}
{258}{}{No! You can't do that! We're partners, I showed you this place... Hell, someday... Someday I'll earn a lot of caps and hire mercenaries on your head. And then I'll play football with it. You'll remember this day again.}
{259}{}{Well, well. Goodbye, loser.}
{260}{}{In that case, you leave me no choice -I'll kill you right now.}