{100}{}{This is Bart Thur.}
{101}{}{You see the owner of the gun shop. He seems to be obsessed with weapons.}
{102}{}{Oh, it's power armor! I've heard so much about her, but I've never seen...}
{103}{}{Don't touch it. I don't serve addicts. Who knows what's on your mind?}

#Start of the dialog
{200}{}{(looks closely and skeptically at you, assessing the prospects of trading) What kind of weapon do you need, sir? For hunting or to intimidate bandits? I have plenty of guns for any purpose.}
{1200}{}{(looks closely and skeptically at you, assessing the prospects of trading) What are you looking for, ma'am? There are plenty of weapons here for any purpose and for any level of prosperity.}
{201}{}{Let me see...}
{202}{}{Let me take a closer look at your guns.}

{210}{}{(silently waiting for your remarks, lovingly wiping the weapon from the dust)}
{211}{}{I think I'll go.}
{212}{}{I see.}

{213}{}{Someone broke into the mercenary guild and killed Bruce Turner.}
{214}{}{Yes, I know.}
{215}{}{I hope that son of a bitch got what he deserved. Because because of him, I lost a good welding from the guild.}
{216}{}{Cheer up, a new guild will surely appear.}
{217}{}{So you sponsored them with guns? You shouldn't have done that.}

#Questions
{220}{}{Where did you get this weapon?}
{221}{}{Everyone here has their own story. This revolver, for example, was sold by an unlucky casino player. But this gun was taken from local bandits during the storming of their camp. Something was brought by caravans from the south. But don't you care? The main thing is not to fail in battle.}
{222}{}{What did you say about caravans from the south?}
{223}{}{In the south there is a settlement of tinsmiths. These guys know a lot about old technologies and almost pray to them. They have restored the machines and are now engaged in repair and production. For example, here is their development... (takes it out and shows it)}
{224}{}{[Next]}
{225}{}{A pneumatic spear. It operates on a spring-piston mechanism. No electronics and questionable gunpowder. (with pomp shows the work of the spear) You rest against the enemy's body, and boom! - the thorn flies out of the spear and pierces the body. Don't worry, it will return to its place by itself with the help of a return spring. Then it's just a question of your skills.}
{226}{}{Are they still carrying weapons from the south?}
{227}{}{Some adventurers went there in search of valuable finds. But sooner or later this flow will stop. It is much more important that the tinkerers no longer produce new weapons and do not repair old technologies. They were very useful to the whole Phoenix.}

#Product Disclosure
{230}{}{And what do you have on those covered shelves?}
{231}{}{The best thing I have. But this product is waiting for special customers. You're not one of them yet.}
{232}{}{Why be so careful?}
{233}{}{The followers of Fire don't like it when I sell good weapons to untested types. They think that sooner or later he will be turned against the church. Therefore, all the best is bought by the followers themselves, as well as casino security, the bounty hunters guild and other respected people of the city who can be trusted.}
{234}{}{Why did you cover part of the product?}
{235}{}{I want to take a look at those special guns.}
{236}{}{I'm sorry, but all the best I have is kept for special customers. You're not one of them yet.}
{237}{}{Why be so careful?}
{238}{}{Apparently, I have nothing else to do here.}
{239}{}{Okay, let me see what you have for a commoner like me.}

{240}{}{Hmm... sounds convincing. (opens the product and spreads his hands with a satisfied look) Here is all the best that there is in Phoenix...}
{241}{}{Damn, it's enough to take over the whole city.}
{242}{}{And this is what you keep for the most important customers? What a pathetic sight.}

{243}{}{The fire worshippers are on the run, their sect doesn't have long left. It's time to forget about your agreement.}
{244}{}{I have recently been initiated in the Cathedral.}
{1244}{}{I have recently been initiated in the Cathedral.}
{245}{}{Am I really not trustworthy after so many victories in the ring?}
{246}{}{I'm from the Arizona Rangers. And I really need a reliable trunk.}
{247}{}{Don Diego advised me to buy a gun here. Don't let him down.}
{248}{}{You have quite diverse clients, right? [Name the rebel password]}
{249}{}{You will be happy with this contract.}
{250}{}{Sounds unconvincing.}
{251}{}{Okay, what about the rest of the weapons?}
{252}{}{Then I'm out of here.}
{253}{}{I have connections all over Arizona. Such a contract will be beneficial to both of us.}
{254}{}{I'll vouch for my reputation.}
{255}{}{You won't have any problems because of me. I guarantee my reputation.}
{256}{}{If you don't cooperate with me, I'll kill you.}
{257}{}{Do you want me to call my friends from an influential gang?}
{258}{}{I understand. Let's see what you have for ordinary citizens.}
{259}{}{Trust me, too. "There are no people more loyal to the emperor than a handful of peasants."}

{260}{}{Anything else?}
{261}{}{Yes, I wanted to ask something else.}
{262}{}{That's all I need. Later.}

#Discounts and penalties
{280}{}{(recognizing your person, the seller suddenly perks up) Ah, it's you. Glad to see you in my store.}
{281}{}{Sounds like a hint of a bargain.}
{282}{}{We'll see... Dear people, I make a small discount. After all, it is necessary to support the development of the city, even doing business.}
{283}{}{Discount? Great, I'll need it.}
{284}{}{(Having recognized your person, the seller warily changes his position, as if expecting a trick) Hey. Do you need something?}
{285}{}{I'm thinking of buying a weapon...}
{286}{}{Then choose quickly and get lost. This isn't a gang hangout. And keep in mind, I won't sell anything to assholes like you at a normal price.}
{287}{}{Whatever you say, man. Still, I need a weapon. Even at an increased price.}
{288}{}{You should appreciate any buyer. You know, the world is changing too fast.}

{290}{}{Hey, do you think you can just show up here after the explosion in the Cathedral? The townspeople will be unhappy if I continue to trade weapons with you sectarians...}
{291}{}{That's why I need a weapon for self-defense.}
{292}{}{Hmm, okay. I'll sell you something. But no discounts, okay?}
{293}{}{caps are not a problem. Just show your product.}
{294}{}{I don't need your condescension, you fool.}
{295}{}{Looks like I'm not welcome here. I'd better go.}

#Training
{300}{}{Can you just shoot a gun without buying it?}
{301}{}{Pay for ammo and rental of weapons - and you can shoot skills in the dash as much as you want.}
{302}{}{Here are 500 caps for shooting light weapons.}
{303}{}{Here are 1000 caps for firing heavy weapons.}
{304}{}{Here are 2000 caps if you let me shoot with an energy weapon.}
{305}{}{Here are 250 caps for learning the throwing skill.}
{306}{}{Then it's easier for me to buy a gun.}
{307}{}{This is robbery. I'm leaving here.}
{308}{}{Save caps if you want to learn shooting.}
{309}{}{OK.}

#Ammunition equipment
{330}{}{I need to refit the cartridges.}
{331}{}{I can re-equip signal cartridges and cartridges with buckshot. And it doesn't make much sense to mess with pistol and rifle ones.}
{332}{}{[Strengthen the signal cartridge]}
{333}{}{[Strengthen the modified signal cartridge]}
{334}{}{[Replace buckshot with a bullet in a 12-gauge cartridge]}
{335}{}{Each cartridge for 1 cap. How old are you?}
{336}{}{Each cartridge for 2 caps. How old are you?}
{337}{}{Not at all yet. I just wanted to know the prices.}
{338}{}{Too weak, right? They are not designed to hit a live target. But you can strengthen them and add something killer.}
{339}{}{I don't need it.}

{340}{}{Done. Anything else?}
{341}{}{I have more cartridges that need to be reloaded.}
{342}{}{I might be interested in something other than cartridges.}
{343}{}{No, goodbye.}
{344}{}{Something is missing, right? Look around, I have a lot of other products.}
{345}{}{One cartridge.}
{346}{}{Two cartridges.}
{347}{}{Three rounds.}
{348}{}{Four rounds.}
{349}{}{Five rounds.}

#Improving weapons
{350}{}{Do you repair weapons?}
{351}{}{Show me your toys, I'll think about what I can do with them.}
{352}{}{It seems that nothing can be done about it.}
{353}{}{Perhaps not this time.}
{354}{}{}
{355}{}{Is there a sight for a hunting rifle?}
{356}{}{I can put a 10-fold sniper scope of the Yunertl brand. A great thing when you need to shoot at a *long* distance.}
{357}{}{How much does it cost?}
{358}{}{ caps. bottlecaps forward.}
{359}{}{I need this scope. Here are the bottlecaps and the rifle.}
{360}{}{What is missing?}
{361}{}{Yes, it will have to be postponed.}
{362}{}{(with a satisfied look evaluates his work and gives you the finished product) Anything else?}
{363}{}{Yes, don't rush to close.}
{364}{}{No, I don't need anything else.}
{365}{}{I need a more spacious magazine for PP 0.22.}
{366}{}{Yes, such a small caliber of such a store will not be enough. But you're lucky, I have a drum just for the caliber of 0.22.}
{367}{}{I want this drum. Here are the bottlecaps and weapons.}
{368}{}{Is it possible to somehow strengthen this cattle-chasing?}
{369}{}{Yes, perhaps.}
{370}{}{It's worth it. Do it.}
{371}{}{Is there a big store for my AK-112?}
{372}{}{Yes, there is a magazine for forty rounds instead of the usual twenty-four. Just the last one left.}
{373}{}{Give it here.}
{374}{}{Ten rounds.}
{375}{}{All the ammo I have.}

#Quests
{400}{}{Was it your gun that shot the monks at the casino?}
{401}{}{And who are you to ask me questions?}
{402}{}{Sorry. I'm investigating an attack ordered by Aaron. So can I ask you a few questions?}
{403}{}{I don't know any more about the attack than you do. And I doubt that they fired from weapons bought in my store.}
{404}{}{Why is that?}
{405}{}{Here I ask questions and you answer. Or do you want problems with Followers?}
{406}{}{I've been interrogated by four people before you. I've already told them everything I know. And I don't know any more than you do. And I doubt that they fired from weapons bought in my store.}
{407}{}{Something is doubtful. This is the only gun shop, right?}
{408}{}{Although my shop is the only one in the city, you can get weapons anywhere. The most armed people in the city are, perhaps, the Followers of Fire themselves. At one time, all the trunks were collected by them to make a revolution. Besides, I supply the best weapons to them, such an agreement.}
{409}{}{Then who could attack the monks?}
{410}{}{Are you *asking* me that? You're a shitty detective. My advice to you is to talk to people in the market, they saw everything with their own eyes.}
{411}{}{Okay, I'll talk to them. But remember that no one will get away from Followers unpunished.}
{412}{}{Thank you, you helped me a lot. Have a nice day.}