{100}{}{In front of you is a vendor of a diner.}
{101}{}{You see a dark-skinned guy with his hair spread out and in a dirty apron.}

#Floating replicas
{110}{}{A fly in the soup? Well... eat it.}
{111}{}{Cut off this mold - and into soup.}
{112}{}{The meat of the mole rat has to be boiled for a long time.}
{113}{}{Come up before the best is sorted out.}
{114}{}{More additives? Super.}
{115}{}{Fresh rats!}
{116}{}{Damn, my whole body itches.}
{117}{}{These cattle ranchers in San Brahmin have crazy prices.}
{118}{}{This meat is a bit strange. But you'll like it.}
{119}{}{Meat from the best trappers of the city.}

#Start of the dialog
{200}{}{(seeing you, the merchant stops waving away the flies in confusion and pretends that they are not flying in a cloud around the diner) Hey, what are you going to order?}
{201}{}{And what do you have?}
{202}{}{I have only the freshest, straight from the wastelands. Do you want rat soup? Mmm, a delicious rat! I was running around the sewers this morning.}
{203}{}{Uh, let me think...}
{204}{}{By the way, I had to raise the prices after all the hype in the Cathedral.}
{205}{}{Well, your right.}

{210}{}{So what will you order?}
{211}{}{Nothing.}
{220}{}{I'm afraid to ask, but where did all this meat come from?}
{221}{}{Hey, don't you care which sewer the rat is caught in? They bring them to me from all over the city. I'm not going to clarify every time, right?}
{222}{}{I shouldn't have asked that...}
{223}{}{Do you have anything less disgusting?}
{224}{}{Sometimes the scavengers bring those unforgettable pre-war dinners. Mmm! But I keep them for special clients.}
{225}{}{Sell it to me before it goes bad.}
{226}{}{Eat the pre-war carrion yourself. And I need fresh food.}
{227}{}{Pre-war? Then that's not what I need.}
{228}{}{Hmm. Well okay. (puts out some old boxes from the refrigerator)}
{229}{}{[Next]}
{230}{}{Your list of "special clients" simply must have Followers of Fire.}
{231}{}{I think you won't refuse a generous tip. Here are 10 caps.}
{232}{}{(smiling with crooked teeth) Thank you, mister.}
{233}{}{So what about those pre-war dinners?}
{234}{}{Half the city knows me. Don't I deserve respect?}
{235}{}{Don't I deserve respect?}
{236}{}{Don't piss me off, or I'll smash your fucking place. And I can do it.}
{237}{}{You know, there are respectable clients who ask to put aside a couple of boxes for them. It is more profitable for me to hold the goods to a regular customer than to sell to the first person I meet.}
{238}{}{Yes, it wasn't really necessary.}
{239}{}{ (throws up his hands) Is this a joke? If there are no caps, then get out of here! I don't feed beggars.}
{240}{}{[Leave]}
{241}{}{Where did all of a sudden so much fresh meat come from, my friend?}
{242}{}{Oh, it's from a tribe of cattle breeders in the west. Finally, they got smart and started trading with Phoenix.}
{243}{}{I think I know the story.}
{244}{}{Really? Well, then you know I'm not lying. The purest fresh! Beef of the highest grade. Expensive, but worth it. Look, I'm already fat from one steak, like a pregnant rat. A-ha-ha!}
{245}{}{Yeah, I'm happy for you. I really hope that you still keep it all right.}

{250}{}{What happened to Lloyd?}
{251}{}{Some street robber stabbed him like a dog. There was nothing to shine with your new suit.}
{252}{}{It was from my caps that he bought it.}
{253}{}{Well, then you are in some sense an accomplice, hehe... Oh.}
{1253}{}{Well, then you are in some sense an accomplice, hehe... Oh.}
{254}{}{Hmm. A curious thought.}
{255}{}{Watch your mouth before you go after Lloyd.}

#Attack on Followers
{300}{}{Tell me about the attack on Followers.}
{301}{}{Hey, I need to cook here. Would you like some rat soup? Take a portion, you won't regret it.}
{302}{}{I don't have caps to buy.}
{303}{}{And I don't have time to talk. Excuse me.}
{304}{}{I see, goodbye.}
{305}{}{Great, here are 10 caps, and while I'm eating your soup, you'll tell me how it was. OK?}
{306}{}{Sorry, but even a spoonful of soup won't pay for such caps.}
{307}{}{Uh, I think I miscalculated a little.}
{1307}{}{Uh, I think I miscalculated a little.}
{308}{}{Well, that's another conversation. Eat, don't get wet. So what was it about?}
{309}{}{About the attack near the casino.}
{310}{}{You miserable worm, stick this rat in your anus and tell me what you saw.}
{311}{}{Hey, hey! I understand everything. Sorry, I didn't recognize it.}
{312}{}{Tell me.}
{313}{}{It was a terrible thing. The monks were walking down the street, then these people in balaclavas jumped out of the corners, just like rats from the sewer. Surrounded and began to shoot from machine guns. I've never heard so many shots fired at once. And then they ran away as if they had never been. Everything happened very quickly.}
{314}{}{I see. But you shouldn't have confused me, my friend. Next time you'll talk to my fist.}
{315}{}{The situation has cleared up a bit.}
{316}{}{The situation is becoming clearer. It's time to talk to Aaron about this.}
{317}{}{Thank you, you helped a lot.}