{100}{}{Here is a hoarder.}
{101}{}{You see a short man in ridiculous clothes. A helmet with a lot of devices was clumsily placed on his head.}

#Floating replicas
{110}{}{The best quality junk!}
{111}{}{I will find details for any utensils.}
{112}{}{The ancient things were beautiful.}
{113}{}{Buy drumsticks, they'll come in handy.}
{114}{}{If the toaster is malfunctioning, bring it to me.}
{115}{}{The hardest thing is to find whole light bulbs.}
{116}{}{Although rusty, but it works.}
{117}{}{There are instructions for Mr. Assistant.}
{118}{}{Buy from me, so as not to rummage through the ruins.}
{119}{}{It is worth turning away, as something disappears from the counter.}

#The first dialog
{200}{}{Come here, señor! Junk and junk - that's what you need. And all this you will find in my shop.}
{1200}{}{Come on, señorita! Junk and junk - that's what you need. And all this you will find in my shop.}
{201}{}{Wow, there's a whole carload of garbage here.}
{202}{}{}
{203}{}{Not garbage, no, no! Everything you need is here. Take a closer look. Maybe you need those rusty spoons? Or do you prefer to eat with dirty hands? Then you will surely be interested in this toaster. It has a bit of a button jam, but it definitely works. Or maybe you need...}
{204}{}{Hey, slow down, man. Let me figure it out on my own.}
{205}{}{Shut up, you stupid mole rat. You're making too much noise.}
{206}{}{Oh, by the way. I want to warn you that I raised the prices after all this hype in the Cathedral. The whole market has raised prices.}
{207}{}{Why?}
{208}{}{The caps were Aaron's idea. His church kept the course on the same level. And now there is no church, and the caps are depreciating. We may have to give them up altogether.}
{209}{}{I see. So, it's time to buy up everything you need.}

{210}{}{Have you chosen anything yet?}
{1210}{}{Have you chosen anything yet?}
{211}{}{No, another time.}
{212}{}{Can I take a closer look?}

#Questions
{220}{}{Where did you get these things from?}
{221}{}{Usually they bring scavengers, sometimes caravanners. But I don't ask where they get them from.}
{222}{}{Obviously, not all of your goods were obtained in an honest way.}
{223}{}{Okay, this question was superfluous.}

{224}{}{Who needs this junk if it's full of ruins?}
{225}{}{Do you want to rummage through the ruins and search on your own? You are welcome! Just don't forget about radiation, animals, bandits, landslides and a bunch of other problems that can leave you only a wet spot. And I not only sell, but also repair all these things so that they serve the new owners at least a little time.}
{226}{}{Don't tell me any more about it.}
{227}{}{I think I should take a closer look at your product.}

{228}{}{You're crazy. These things became obsolete 90 years ago.}
{229}{}{Do you have better sources? I'd like to see it. However, caravans from the south have become more frequent lately. They bring really new things.}
{230}{}{Then stop wasting my time with idle chatter.}
{231}{}{Thanks, I'll keep that in mind.}

#Quest to find Vault 27
{240}{}{Have you come across items from Vaults?}
{241}{}{Vaults? What are you talking about... Ah, I see! Vault-Tec Vaults are a true legend. They say some of our ancestors lived there after the Great War. But so much time has passed that no one knows the location of these Vaults.}
{242}{}{And who can know?}
{243}{}{You need to go to the Followers of Fire. There is so much knowledge in their library that they themselves no longer know what to do with it. Maybe the coordinates of the Vaults are there. That's just they won't want to share without a good reason.}
{244}{}{But what about the scavengers?}
{245}{}{Heh, do you think a normal scavenger would disclose the location of Vaults? After all, according to legend, there are a hell of a lot of relics stored there! But if you have a chatty tongue, then visit Bob in the slums. He's one of the oldest scavengers in Phoenix.}
{246}{}{Clear.}

#Consultation on subjects
{250}{}{I need advice on old subjects.}
{251}{}{This is what I live by - Old World stuff. But my knowledge is also worth something. A couple of caps will be enough for me.}
{252}{}{[}
{253}{}{]}
{254}{}{Not worth it. Maybe another time.}
{255}{}{Look at another subject now.}
{256}{}{Stop talking about old things. It's time to do something more relevant.}
{257}{}{Happily.}
{258}{}{Tell us about your product.}
{259}{}{Of course I'll pay.}

{260}{}{What exactly are you interested in?}
{261}{}{[Music box]}
{262}{}{Surprisingly, the mechanism is still working. Kids are sure to like this.}
{263}{}{[Atomic clock]}
{264}{}{Wow, it's rare to find a pocket watch in working condition. And this brand has always been distinguished by quality. In addition, the atomic battery lasts for decades. If the tinsmiths were here, they would tear this thing off with their hands.}
{265}{}{[Snow globe]}
{266}{}{Snow! I've never seen real snow, except for a few mountain peaks in the distance. Yes, any rich man will fork out for such a thing. You know, I can find a use for this trinket.}
{267}{}{[Medal for Bravery]}
{268}{}{Operation Anchorage... Somewhere in the old newspapers I read about this massacre. It seems that the USA was proud of its victory then. I don't even know who can be pleased with such a find now. Do you know the notorious patriots of "that country"? I'm not.}
{269}{}{[Ranger Star]}
{270}{}{It looks very old... The Arizona Ranger? I heard that the Ranger base is in the west. But I don't know where exactly.}
{271}{}{[Holy Book]}
{272}{}{I think it's a religious book. Surely the Followers of Fire will be interested in her.}
{273}{}{[Photo]}
{274}{}{A snapshot of the big bang? So that's how it was... Scary. It is not necessary to show this thing to mere mortals. Better find a bald connoisseur of ancient history if you want to talk about the Great War.}
{275}{}{[Tooth with crown]}
{276}{}{It's just a tooth with a crown. Let me take a look under a magnifying glass... so... No, there's something here. We need a microscope... so... wow. Yes, it's not just a crown, it's some kind of chip. Or a magnetic key. Or maybe an information storage device. It's too complicated for me. Only tinkerers understand such high technologies.}
{277}{}{[Arizona Flag]}
{278}{}{One of the flags of the Old World. Most of these flags have decayed, but this one is surprisingly well preserved. They should be waving at the colonizers in the north at the right time. And there are few conservatives left in our city.}
{279}{}{[Game disc]}
{280}{}{It looks like an ordinary holodisk. But it seems that it does not contain information, but some kind of program. Try inserting it into some work computer. The power of your Pip-Boy may not be enough here.}
{281}{}{[My Portable Pip-Boy]}
{282}{}{Hmm, this is the first time I've seen such a compact computer... Wait, there should be an output section here... So, Pip-Boy, model 2000, serial number... wow, this thing is straight from 27! This is one of those Vault-Tec Vaults that are legendary. So it does exist after all.}
{283}{}{[The surviving book]}
{284}{}{A rare find. A valuable source of pre-war wisdom - that's what the Followers of Fire say about them. Basically, they buy them. After all, few people in Phoenix can read. And the knowledge in these books does not really help ordinary residents.}
{285}{}{[Can of coffee]}
{286}{}{You're very lucky. After all, these are coffee beans. They were used to make a popular drink in the Old World. And now coffee has become so rare that it is served only to rich aesthetes in the casino opposite.}

{289}{}{The merchant lowered his prices by 5%.}
{290}{}{You'll probably be interested in this. Look, if you shake it, it starts snowing inside...}
{291}{}{Snow! I've never seen real snow, except for a few mountain peaks in the distance. Yes, any rich man will fork out for such a thing... Hey, listen, sell this trinket to me? You definitely won't need it.}
{292}{}{Are you crazy? I just needed to know what it was. That's where we'll part ways. Bye.}
{293}{}{Let me think. In the meantime, let's do other things...}
{294}{}{Take it for free. I'm just glad to get rid of the extra stuff in my backpack.}
{1294}{}{Take it for free. I'm just glad to get rid of the extra stuff in my backpack.}
{295}{}{Seriously? Will you just give it to me? Thank you. If you need old things, come to me right away. I will lay out all the best and at the best prices.}
{296}{}{It's worth remembering. See you later.}
{297}{}{You know, it took a lot of work to get it. I'll give the thing for 350 caps. And no less!}
{298}{}{So expensive? Ugh... it will be difficult to find a buyer, but the chances remain. Okay, here are 350 caps. Now give me the snow globe. (grabs the ball and looks at it with fascination at the light) U-u-u...}
{299}{}{You're there, be careful... Oh, okay. Later.}

#Attack on Followers
{300}{}{Did you see the attack on the Followers at the casino?}
{301}{}{Well yes. Some bandits attacked the monks. Desperate guys. But what do you care?}
{302}{}{Aaron asked me to investigate this case.}
{303}{}{Aaron himself, you say? And you have a lot of courage. You come to the market, you ask people, you lie about our great lord. But I have already told my Followers everything, and several times. Get out of here, I won't tell you anything.}
{304}{}{Sorry to bother you.}
{305}{}{I don't care who you testified to or how many times. NOW you're going to tell it to ME.}
{306}{}{Okay, okay... damn you...}
{307}{}{How was it?}
{308}{}{Relax, you can trust me.}
{309}{}{You're not very nice to me, such a respected person in the city.}
{310}{}{Don't flatter yourself, tramp.}
{311}{}{You'll pay for your words someday.}
{312}{}{I apologize. Not another word about it.}
{313}{}{EITHER you tell me, OR I'll break your arm.}
{314}{}{In general, the monks were walking peacefully down the street. Suddenly, people in balaclavas flew out of several alleys. There were about five or so of them. They fired mainly from submachine guns. They killed the monks and immediately disappeared back. These bandits planned the attack well.}
{315}{}{I see. But if you were hiding something, it will cost you dearly.}
{316}{}{Thank you, you helped me a lot.}
{317}{}{The situation has become a little clearer.}
{318}{}{The situation is becoming clearer. It's time to talk to Aaron about this.}