{100}{}{Here is a dress merchant.}
{101}{}{You see a woman with a mohawk wearing a leather jacket. She knows a lot about modern fashion.}

#Floating replicas
{110}{}{Throw away your rags, I have normal clothes.}
{111}{}{You definitely need to change your image.}
{112}{}{I can sew torn pockets.}
{113}{}{This jacket is bursting at the seams.}
{114}{}{Do you need shoes made of car tires?}
{115}{}{Fresh footcloths!}
{116}{}{These pajamas will hide your many shortcomings.}
{117}{}{Clothes straight from pre-war warehouses.}
{118}{}{Felt hats and business suits are no longer in fashion.}
{119}{}{Fire worshippers know a lot about clothes.}

{200}{}{Hi. I have different casual clothes and some work clothes. Look, don't be shy.}
{201}{}{Wow. It's better than the burlap my whole village wears.}
{202}{}{God, these clothes are probably a hundred years old. No wonder the locals look so intimidating.}

{210}{}{So, did you like something?}
{211}{}{Not yet.}
{212}{}{And let's try this on...}

#Questions
{220}{}{Where do you get all these clothes?}
{221}{}{Half of the goods are handmade. And the other half is brought by scavengers. Sometimes, a couple of times, they found surviving warehouses with pre-war clothes, but nowadays it looks strange.}
{222}{}{I see.}
{223}{}{Where do the Followers of Fire get their robes from?}
{224}{}{Obviously, they make it themselves. And they are in no hurry to share this technology with ordinary mortals.}
{225}{}{Before the War, it was considered good clothes.}
{226}{}{Apparently, it is. After all, no one expected to walk around the ruins of Phoenix in it. Now people need different clothes - more practical, or something.}
{227}{}{Uh-huh.}
{228}{}{I don't want to walk in this old stuff.}
{229}{}{Hmm. It seems to me that the ancestors considered these costumes something decent. Oh, the old days... Okay, forget it.}

#Glasses
{230}{}{Is this all your product?}
{231}{}{I can make something to order.}
{232}{}{Look, I need something special to impress people.}
{233}{}{I'll think about it.}
{234}{}{Seriously? Nowadays people have little taste in clothes. But you're lucky. I have sunglasses in excellent condition. Such are rarely found now.}
{235}{}{It definitely won't hurt you. Try to cover your burns with these sunglasses. So at least from a distance you won't scare people.}
{236}{}{Yes, it definitely won't hurt you. I have great stylish glasses. It's good to hide your eyes in them so that no one will guess about your uncertainty.}
{237}{}{Put it aside for now, I'll think about it.}
{238}{}{So, let's see what I can offer in return...}
{239}{}{Show me what you have.}

#Metal armor
{240}{}{What about the armor?}
{241}{}{This is a bit not my profile. Ordinary citizens don't need armor, and few can afford it. If anyone needs it, I make an order with prepayment.}
{242}{}{I will pay 50 caps for the work.}
{243}{}{Come on, you probably have something in a secret drawer for special clients.}
{244}{}{Listen, why do you need armor? Better take an armored jacket, you're not going to war.}
{245}{}{And maybe so. Okay, let's go.}
{246}{}{Okay, let's go.}
{247}{}{Well good. But keep in mind - no return. And I don't give guarantees against bullets either.}
{248}{}{Your business is to sell. And it's up to me to decide.}
{249}{}{Thanks for the warning.}
{250}{}{Do you even know what such a sum looks like?}
{251}{}{Wait, they definitely were!}

#The Mantle of Followers
{260}{}{I need the robe of a Follower of Fire.}
{261}{}{(looks around warily) Listen, I'm not going to ask why you need this, but I don't need problems.}
{262}{}{I'll pay whatever you say. And no one will know about our secret deal.}
{263}{}{Don't worry, our mutual friends sent me to you.}
{264}{}{Are you out of your mind? Yes, they will kill me for this!}
{265}{}{You just lost a mountain of caps. Congratulations.}
{266}{}{Sorry to bother you.}
{267}{}{Oh, that changes a lot. But I hope you know what you're doing.}
{268}{}{No problems. I'm just passing by.}
{269}{}{Okay, here's what I have. But don't ask to get any more - it's too dangerous.}
{270}{}{OK.}

#Jumpsuit
{280}{}{Hey, isn't this the same jumpsuit from the legendary hideouts? Where did you get it from?}
{281}{}{Found.}
{1281}{}{Found it.}
{282}{}{Inherited from the ancestors.}
{283}{}{That's lucky. And you certainly don't know where to get more, right? Just know that these jumpsuits are a real find. If you find more, bring it to me, I'll buy it for real caps at an increased price.}
{284}{}{OK. But before that, I want to look at your products.}
{285}{}{I'm going on a search right now.}
{286}{}{Here's the coverall from the Vault you wanted.}
{287}{}{Super! I'm finally going to change out of this smelly jacket. Hey, don't forget the caps. And thank you.}
{288}{}{Please.}
{289}{}{The main thing is the bottlecaps. And keep the gratitude for yourself.}
{290}{}{What's the story with the overalls?}
{291}{}{Well, it's an old legend. They say that before the Great War, several Vaults were built around Phoenix. Some people survived the War there and then came out to revive the city. True, the rumors are contradictory.}
{292}{}{[Next]}
{293}{}{Besides, my parents had such a jumpsuit. This is a special memory for me. Unfortunately, that jumpsuit has long since decayed.}
{294}{}{A curious story.}
{295}{}{I have a coverall from the Vault for you.}
{296}{}{More? Wow, and you know how to get good things. Here are the bottlecaps.}
{297}{}{You're welcome.}
{298}{}{Great. But I need something else.}

#Attack on monks
{300}{}{What did you see during the attack on the Followers?}
{301}{}{Hey! Don't get me involved. I'm just selling clothes. And I didn't see anything.}
{302}{}{Then I'm sorry, there are no more questions.}
{303}{}{Speak up, bitch, or I'll smash your despicable shop.}
{304}{}{What do you want? Well, masked men ran out of the alleys and started shooting at the monks. Then they also quickly disappeared. They didn't touch anyone else. That's all I know!}
{305}{}{I'm sorry about the shop - of course, I'm not going to carry it.}
{306}{}{I'll believe you. This time.}
{307}{}{Relax, you can trust me.}
{308}{}{I have no doubt. But I really don't know anything about the attack. Leave me alone.}
{309}{}{I promise you won't be in any danger.}
{310}{}{As if not so. Here either you will not please the Followers, or the enemies who pursue them.}
{311}{}{This is something interesting. Tell me how it was.}
{312}{}{Well, masked people ran out of the alleys and started shooting at the monks. Then they also quickly disappeared. They didn't touch anyone else. That's all I know!}
{313}{}{Hmm, a curious story. Thank you.}
{314}{}{I'll believe you. But only this time.}
{315}{}{The situation has cleared up a bit.}
{316}{}{The situation is becoming clearer. It's time to talk to Aaron about this.}