{100}{}{You see a croupier.}
{101}{}{You see a man with a sharp look and businesslike habits.}
{102}{}{Because in-you can't sit at roulette in THIS...}
{103}{}{If you don't leave, I'll call security.}

{200}{}{(Here is a roulette in nuclear coloring. The betting table is divided into black and red cells, and two cells labeled "0" and "00" are highlighted with a nuclear explosion pattern. The dealer takes a bright yellow ball, which for some reason is called a "bomb" here. With a habitual movement of his hand, he launches it along the wheel under the intense gazes of the players.)}
{201}{}{Ugh, I don't know how to play this.}
{202}{}{It's probably worth a try.}
{203}{}{I'm just looking, never mind.}
{204}{}{Of course, sir. Join us.}
{1204}{}{Of course, ma'am. Join us.}
{205}{}{So, what do we have here...}

{210}{}{Place your bets.}
{211}{}{I'm not playing anymore.}
{212}{}{I put 5 chips on red.}
{213}{}{I bet 5 chips on black.}
{214}{}{I bet 5 chips on zero.}
{215}{}{I don't have any chips left. We'll have to look in another time.}

{220}{}{Bets are made.}
{221}{}{Come on, ball, don't let me down.}
{222}{}{Let's see who gets lucky.}
{223}{}{Keep playing.}
{224}{}{We play on.}
{225}{}{Launch!}
{226}{}{Stop. I'm doubling my bet.}
{227}{}{Let. I'm tripling the bid.}
{228}{}{Uh, please, sir.}
{1228}{}{Uh, please, ma'am.}
{229}{}{I think I've run out of chips. Okay, keep playing.}

{230}{}{There are no more bets.}
{231}{}{[Wait]}
{232}{}{The bomb is on red. You lost.}
{233}{}{Bomb on black. You lost.}
{234}{}{Bomb on zero! You lost.}
{235}{}{A bomb on double zero! All bets go to the casino.}
{236}{}{I want to keep playing.}
{237}{}{I think I've had enough for today.}
{238}{}{The bomb is on red. You've won.}
{239}{}{A bomb on black. You won.}
{240}{}{The bomb is on zero. You've won! The payout will be 1 to 8.}
{241}{}{Great, let's play on.}
{242}{}{I don't play anymore. I need a break.}