{100}{}{You see a player.}

{101}{}{Looks like this player is having a very lucky day today.}
{102}{}{You see a casino client. He is becoming very excited with a string of wins.}
{103}{}{This player is in a state of boredom. It looks like he is neither winning, nor losing.}
{104}{}{You see a casino client. He's becoming very angry after a string of losses.}
{105}{}{This player is covering his head in panic. Looks like he lost all his money.}

{109}{}{How did they let you here in that armor?}

#Replies
#- good
{110}{}{Great place, no?}
{111}{}{I'm doing great,you?}
{112}{}{I'm very lucky today.}
{113}{}{This casino is heaven on earth.}
{114}{}{I know how to win. Rreally.}
{115}{}{Do you like this game? Sheer euphoria.}
{116}{}{Caps! Caps! Caps!}
{117}{}{Don't scare away my luck.}
{118}{}{Why does this happen specifically to me all the time?}
{119}{}{I just had a breakthrough.}
{120}{}{Please move away.}
{121}{}{Don't stand here.}
{122}{}{Today, all the chips will be mine!}
{123}{}{I already feel like I'm part of the slot machine.}
#Similar to alleged quote from Star Trek (Original series? wasn't said which star trek series) Season 1 Episode 2 "I already feel like I'm part of the control panel". Could not find it so just translated directly
{124}{}{Me and this slot machine are old friends.}
{125}{}{Don't count on a drink.}
{126}{}{Dare to play against me?}
{127}{}{These damn poor tourists...}
{128}{}{Don't get in my way while I'm playing.}
{129}{}{Want to share your luck with me? If not, go for a walk outta here.}

#- bad
{150}{}{This is a terrible place, I can't win anything.}
{151}{}{I'm doing worse than ever before, what about you?}
{152}{}{Today is not my lucky day.}
{153}{}{This isn't a casino, it's à den of one-handed thieves.}
{154}{}{I never win here.}
{155}{}{I made a mistake even playing this game. It's hopeless.}
{156}{}{Hey, lend me a couple of caps.}
{157}{}{If I win, I'll buy everyone a drink.}
{158}{}{I hope you get more lucky than me.}
{159}{}{This string of bad luck will never end.}
{160}{}{I really need to win.}
{161}{}{Welp, it's just a game.}
{162}{}{Dice aren't good.}
{163}{}{This is clearly rigged.}
{164}{}{Fortune turned it's back on me.}
{165}{}{Scams - I see them everywhere I go.}
{166}{}{I already ran out of chips.}
{167}{}{Luck is a mad bitch.}
{168}{}{I managed to win 60 chips, imagine that! But then...}
{169}{}{My entire life is at stake here!}
{170}{}{Careful, deceit is everywhere here.}
{171}{}{The machines are clearly rigged.}

#Random lines
#- bad
{200}{}{Come on!}
{201}{}{Why is this game so cruel to me?}
{202}{}{Today is not my lucky day.}
{203}{}{Damn game!}
{204}{}{I hate this game.}
{205}{}{I have a fever!}
{206}{}{But it began so well...}
{207}{}{Either I die, or I'm dead.}
{208}{}{If I lose one more time, I swear I'll destroy this damn establishment!}
{209}{}{I'm not going anywhere until I win.}
{210}{}{I can't win.}
{211}{}{Money's almost out!}
{212}{}{A bit more and I'm bankrupt.}
{213}{}{I'm tired of losing.}
{214}{}{Were those really my last chips?}
{215}{}{Dammit!}
{216}{}{If I don't get lucky now, I'm leaving.}
{217}{}{My pockets are empty.}
{218}{}{I almost managed to do it...}
{219}{}{Not this!}
{220}{}{My situation is terrible.}
{221}{}{Ugh, one more time?}
{222}{}{No, no. Stop!}
{223}{}{Oops.}
{224}{}{Almost!}
{225}{}{Dang it!}
{226}{}{How did this happen?}
{227}{}{Why me?}
{228}{}{What, again?!}
{229}{}{That's really unlucky...}
{230}{}{I need a drink.}
{231}{}{Everything was rigged against me.}
{232}{}{So close!}
{233}{}{Watch as I get a jackpot.}
{234}{}{Great, one more poor person.}
{235}{}{Oof, time to go to the toilet.}
{236}{}{Maybe if I sell my spleen, I could play some more...}
{237}{}{No, not in this life!}
{238}{}{Stop making fun of me!}
{239}{}{This is not one of my good days.}
{240}{}{Dammit!}
{241}{}{Oh no!}

#- good
{300}{}{Yes!}
{301}{}{Don't fail me this time.}
{302}{}{Today I'm lucky.}
{303}{}{Great game!}
{304}{}{I love this game.}
{305}{}{Am I dreaming or not?}
{306}{}{Great, let's continue.}
{307}{}{Today I can live the good life.}
{308}{}{If I win, I'll buy everyone a drink.}
{309}{}{Never stop when you're getting lucky.}
{310}{}{I cannot lose, not now.}
{311}{}{I smell a jackpot.}
{312}{}{At this pace, I'll become the richest man in the city.}
{313}{}{Could have been better.}
{314}{}{Caps! Caps! Caps!}
{315}{}{YES!}
{316}{}{I'm definitely going to get lucky today.}
{317}{}{The chips don't fit in my pockets anymore.}
{318}{}{If only I was always this lucky.}
{319}{}{Hooray! I won!}
{320}{}{Jump one more time!}
{321}{}{More!}
{322}{}{Go! Go!}
{323}{}{Great!}
{324}{}{Amazing!}
{325}{}{Waiter, give me another drink!}
{326}{}{Luck, don't fail me.}
{327}{}{Who won today? Me!}
{328}{}{Ha-ha!}
{329}{}{I'll get enough sleep in my grave.}

#- Before the scene
{350}{}{Veronica sings well.}
{351}{}{Veronica is perfect.}
{352}{}{The way she moves isn't good.}
{353}{}{It's like the singer was tortured right before this.}
{354}{}{Her songs are sad.}
{355}{}{What is she even singing about?}
{356}{}{Change your repertoire.}
{357}{}{I suppose I could listen for a bit.}
{358}{}{Only here can you see a live concert.}
{359}{}{This is the only place that has a singer.}
{360}{}{I love the casino for this.}
{361}{}{There is no other thing like this in the city.}
{362}{}{Bartender, one more cocktail.}
{363}{}{How much do I need to pay, bartender?}
{364}{}{Bartender, come here!}
{365}{}{Looks like I have nothing to pay with.}
{366}{}{Best bar in the city.}
{367}{}{Excellent steaks here.}
{368}{}{It's a pity to have leave after this.}
{369}{}{}