{100}{}{You see a croupier.}
{101}{}{You see a well-dressed man. You spend some time looking at how skillfully he shuffles the cards, almost hypnotized.}
{102}{}{Uhh, I'm afraid you won't be able to hold cards in THAT...}
{103}{}{Sorry, sir, I'm forbidden from serving you.}
{1103}{}{Sorry, ma'am, I'm forbidden from serving you.}

#Meeting the man
{200}{}{(You see a table for playing various card games, in front of it a well-dressed man with a serious look, shuffling cards.) Do you play nukejack?}
{201}{}{Not today.}
{202}{}{No, I don't know the rules.}
{203}{}{Challenge accepted. But first, explain the rules.}
{204}{}{For the most part, it's a variant of blackjack. You need to collect a sum of 21 points with the smallest amount of cards with nuclear bombs on them. Upon collecting the right number you can "bomb" the deck. This game demands a slightly higher amount of intellectual prowess than roulette or a slot machine. But the stakes here are higher. Of course, if you are willing to take the risk.}
{205}{}{Of course.}
{206}{}{So, will you play?}
{207}{}{Yes.}
{208}{}{No.}

#Bets
{210}{}{New game. Place your bets.}
{211}{}{ chips)}
{212}{}{I don't want to play.}
{213}{}{I would be happy to join, but I have no chips.}
{1213}{}{I would be happy to join, but I have no chips.}
{214}{}{My bet is 10 chips.}
{215}{}{My bet is 20 chips.}
{216}{}{My bet is 30 chips.}
{217}{}{My bet is 40 chips.}
{218}{}{The bets are accepted. Starting distribution now.}
{219}{}{Let us begin.}

{220}{}{Remind me, what was the last score?}
{221}{}{}
{222}{}{ to }
{223}{}{ in your favor.}
{224}{}{ in the casino's favor.}
{225}{}{Good. Let us continue.}
{226}{}{My bet is 50 chips.}

{230}{}{(The croupier takes out two cards and places them near himself upside down. He then flips one, it showing that there are }
{231}{}{ points)}
{232}{}{To me.}
{233}{}{(You are dealt two cards for }
{234}{}{ points)}
{235}{}{[Continue]}
{236}{}{(You have cards worth }
{237}{}{ points. The croupier has cards worth }
{238}{}{ points.) Your move?}

{240}{}{I resign.}
{241}{}{Player one leaves the game. Half of the stake burns out.}
{242}{}{Ladies and gentlemen, I will now leave you.}
{243}{}{Double the stake.}
{244}{}{The stake is doubled. I remind you, the stake can only be doubled once per game.}
{245}{}{Dtake is doubled.}
{246}{}{[Continue the game]}
{247}{}{Pass.}
{248}{}{Player one skips the card. Distribution is continued...}
{249}{}{[Continue the game]}
{250}{}{More.}
{251}{}{Player one takes a card...}
{252}{}{[Continue the game]}

{260}{}{Player one: nukejack! Do you want to play some more?}
{261}{}{No thank you.}
{262}{}{Oh yes, I want more.}
{263}{}{Casino: nukejack. Your bet has burned out. Do you want to play more?}
{264}{}{Eh, no, I just wanted to play a bit.}
{265}{}{Definitely not.}
{266}{}{Player one: defeat. Your bet has burned out. Do you want to play more?}
{267}{}{Casino: defeat. Do you want to continue?}
{268}{}{Draw. Players retain what they had. Do you wish to continue?}
{269}{}{Card limit reached.}