{100}{}{You see a croupier.}
{101}{}{You see a man with a sharp gaze and businesslike habits.}
{102}{}{Sor-ry, y-you can't sit at the roulette in THAT...}
{103}{}{I'll notify security if you don't leave.}

{200}{}{(You see a nuclear-themed roulette. The betting table is divided into black and red cells. Two different cells labeled "0" and "00" are highlighted with a picture of a nuclear explosion. The croupier takes a bright yellow ball, which for some reason is called a "bomb" here. With a movement of his hand he is clearly accustomed to, he launches it along the wheel under the intense gaze of the players.)}
{201}{}{Oof, I have no idea how to play this.}
{202}{}{I suppose I should try.}
{203}{}{Don't mind me, I'm just observing.}
{204}{}{Of course, sir. Feel free to join us.}
{1204}{}{Of course, madam. Feel free to join us.}
{205}{}{Well, well, well, what do we have here...}

{210}{}{Place your bets.}
{211}{}{I have decided to not play anymore.}
{212}{}{I bet 5 chips on red.}
{213}{}{I bet 5 chips on black.}
{214}{}{I bet 5 chips on zero.}
{215}{}{I don't have enough chips left. I'll have to look here another time.}

{220}{}{The bets are placed.}
{221}{}{Come on, ball, don't fail me.}
{222}{}{Let's see who gets lucky.}
{223}{}{Continue the game.}
{224}{}{The game continues.}
{225}{}{Go!}
{226}{}{Stop. I double my bet.}
{227}{}{Wait. I am doubling my bet.}
{228}{}{Please, sir.}
{1228}{}{Please, madam.}
{229}{}{Looks like I don't have enough chips. Alright, continue the game.}

{230}{}{There are no more bets.}
{231}{}{[Wait]}
{232}{}{The bomb is on a red cell. You lose.}
{233}{}{The bomb is on a black cell. You lose.}
{234}{}{The bomb is on zero! You lose.}
{235}{}{The bomb is on a double zero! All the bets go to the casino.}
{236}{}{I want to play more.}
{237}{}{I suppose this is enough for today.}
{238}{}{The bomb is on a red cell. You win.}
{239}{}{The bomb is on a black cell. You win.}
{240}{}{The bomb is on zero. You won! You get 8 chips per every 1 chip in your bet.}
{241}{}{Great, let's play some more.}
{242}{}{I'm not playing anymore. I need some rest.}