{100}{}{You see a cashier.}
{101}{}{You see a strangely diligent cashier. Looks like she was taught to obey well.}
{102}{}{I'm s-sorry, but you'll have to take that off... O-or I'll call security...}

{105}{}{Security! Thief!}
{106}{}{Security! Intruder!}
{107}{}{Leave immediately.}
{108}{}{Leave immediately. This is a service space.}
{109}{}{}

#First dialogue
{200}{}{Greetings, sir. First time in our casino?}
{1200}{}{Greetings, ma'am. First time in our casino?}
{201}{}{Yes, exactly. I'm assuming you'll tell me the rules here?}
{202}{}{The rules of the game you choose to play will be told to you by the croupier. My job is to exchange the chips. Inside the casino, they replace any currency, but you will always be able to exchange them here.}
{203}{}{Alright.}
{204}{}{Not exactly. Keep in mind that I'm a good friend of Don Diego.}
{205}{}{Oh, excuse me, I wasn't given this information. But keep in mind that the rules in the casino are equal for everyone. Including friends of Don Diego.}
{206}{}{Alright.}
{209}{}{I, as a valued member of the club, should be trusted, no?}

#Repeated dialogue
{210}{}{How may I help you?}
{211}{}{Thanks, that'll be all.}
{212}{}{Uhh... yes, what is it?}
{213}{}{So the casino is still open?}
{214}{}{Oh yes. We are still restoring the interior after that explosion in the cathedral, but you can already use all the standard means of entertainment... if you are okay with this little bit of disorder.}
{215}{}{Disorder? Do you have any idea what kind of world we live in? I deal with disorder every day.}
{216}{}{So the casino is open while in such a dire condition? I have heard enough. I'm outta here.}
{217}{}{I'm sorry, but I am forbidden from serving you. I can only exchange all your chips, if you still have some left. If you have any problems with this, please go to the administrator.}
{218}{}{The service here is awful.}
{219}{}{Then I will go and find myself another casino. Goodbye.}

#Unlocking being able to use goods for collateral
{220}{}{Can I leave a deposit or some of my belongings?}
{221}{}{I'm afraid that is not in the best interests of the casino. It is better for us to accept only bottle caps. But sometimes we make exceptions.}
{222}{}{Fine, forget it.}
{223}{}{Can friends of Don Diego count on such exceptions?}
{224}{}{Of course, we'll make one. But the amount of caps for such things is limited.}
{225}{}{Thanks. I'll keep in mind that you have caps.}
{226}{}{Yes, but I'm sorry, there is no order to do so for you.}
{227}{}{No problem.}
{228}{}{I'm a trader, you can be sure about the prospects of doing business with me.}
{229}{}{I believe you. I think we'll make an exception for you. But the amount of caps for such things is limited.}
{230}{}{Thanks. I'll keep in mind that you have caps.}
{231}{}{I believe you. But it is better for the casino to accept caps. You can exchange your goods on the local marketplace.}
{232}{}{You should've accepted my offer.}
{233}{}{Tell me, does my name mean nothing in this city?}
{234}{}{I'm sorry, you're right. From this moment on, you can count on a deposit.}
{235}{}{Thanks. I'll keep in mind that you have caps.}
{236}{}{I'm sorry, but you yourself already know your reputation in *this* city.}
{237}{}{You bitch, are you saying people don't like me here?}
{238}{}{I'm sorry, but we can't help you.}
{239}{}{I didn't need your help anyways.}

#No more casino for you
{240}{}{It is hard for me to say this to you, but the administrator said that I must no longer serve you.}
{241}{}{What? I won't be able to play in the casino anymore?}
{242}{}{He's gone mad. What is this, dammit?!}
{243}{}{I'm sorry, but this is a very strict order! Direct any concerns to the administrator. I can exchange your chips, but I can't give you any new ones.}
{244}{}{In that case I just need to speak to the administrator. So long.}
{245}{}{Of course, deceit is everywhere. Damn casino...}
{246}{}{Wait! Uhh, I'm sorry... sir...}
{1246}{}{Wait! Uhh, I'm sorry... ma'am...}
{247}{}{Is something wrong?}

#Exchange
{250}{}{I want to exchange caps for chips.}
{251}{}{How many caps do you want to exchange?}
{252}{}{10 caps.}
{253}{}{50 caps.}
{254}{}{100 caps.}
{255}{}{500 caps.}
{256}{}{1000 caps.}
{257}{}{None.}
{258}{}{Here. (you receive the chips you got from exchanging your caps)}
{259}{}{Thank you.}
{260}{}{You do not have enough caps.}
{261}{}{Okay.}
{262}{}{Here. (you receive the caps you got from exchanging your chips)}
{263}{}{Thank you.}
{264}{}{You do not have enough chips.}
{265}{}{Okay.}
{266}{}{You do not have enough money.}
{267}{}{Here are all the caps that I have.}
{268}{}{Here. (you receive the caps you got from exchanging your pre-war money)}
{269}{}{Thank you.}

{270}{}{I want to exchange chips for bottle caps.}
{271}{}{How many chips do you want to exchange?}
{272}{}{10 chips.}
{273}{}{50 chips.}
{274}{}{100 chips.}
{275}{}{500 chips.}
{276}{}{1000 chips.}
{277}{}{None.}
{278}{}{Here are all the chips that I have.}

{280}{}{Why are caps so important?}
{281}{}{Caps are a currency. Like Pre-War money. They are exchanged for goods. But unlike the depreciated dollars, the rate of bottle caps is set by the Followers of the Holy Fire. This is one of the wise ideas the Followers have shared with Phoenix.}
{282}{}{So you accept Pre-War dollars?}
{283}{}{Yes. Even though Pre-War dollars are depreciated, they add confusion to the rate of bottle caps. Do you want to exchange them?}
{284}{}{No thank you. But I will keep that in mind.}
{285}{}{}
{286}{}{Yes, that would be handy.}
{287}{}{Yes. But I should remind you that the value of dollars has fallen by half. The rate used to be controlled by the Followers of the Holy Fire, but in this time of crisis they can no longer do this.}
{288}{}{Alright.}
{289}{}{Here are all the Pre-War dollars that I have.}

{290}{}{I want to exchange Pre-War money.}
{291}{}{How many dollars do you want to exchange?}
{292}{}{1 dollar.}
{293}{}{2 dollars.}
{294}{}{3 dollars.}
{295}{}{4 dollars.}
{296}{}{5 dollars.}
{297}{}{10 dollars.}
{298}{}{50 dollars.}
{299}{}{None.}