{100}{}{This is Veronica.}
{101}{}{You see quite an attractive singer.}
{102}{}{Now the singer can't communicate with you.}

#Song 1 "Nature Boy" 1947, translated from the Internet
{110}{}{*Once upon a time there was a boy.*}
{111}{}{*A very strange and enchanted boy.*}
{112}{}{*They say he wandered far, far away.*}
{113}{}{*On the other side of land and sea.*}
{114}{}{*A little shy and sad-eyed,*}
{115}{}{*But he was very wise.*}
{116}{}{*And then one day, one magical day, *}
{117}{}{*He was walking my way.*}
{118}{}{*And we talked about different things,*}
{119}{}{*Fools and kings,*}
{120}{}{*And this is what he said to me:*}
{121}{}{*" The greatest thing you can know,*}
{122}{}{*It's just loving and being loved in return."*}

#Song 2 "Mexicali Rose" of 1923, free translation by A.V. Poshelyuzhin
{150}{}{*Mexicali Rose, don't cry.*}
{151}{}{*I'll come back to you on a sunny day.*}
{152}{}{*I'll miss you, remember that every night.*}
{153}{}{*Every hour while I'm gone.*}
{154}{}{*Dry your brown eyes and smile.*}
{155}{}{*Banish the tears and don't sigh.*}
{156}{}{*Kiss me again and hug me.*}
{157}{}{*Mexicali Rose, goodbye.*}

#Dialog
{200}{}{Hey, hi.}
{201}{}{Bye.}

{210}{}{Hey, hi.}
{211}{}{Bye.}