{100}{}{You see a guard.}
{101}{}{You see a casino bouncer. He's diligently ensuring order around this place.}
{102}{}{You see a casino bouncer. He's looking for thieves.}
{103}{}{You see a casino bouncer. He's watching over the main door.}
{104}{}{You see a casino bouncer. He's watching over a pair of suspicious visitors.}
{105}{}{You see a casino bouncer. He's looking around in boredom.}
{106}{}{You see a casino bouncer with a fierce, serious look.}
{107}{}{You see a man in a suit holding a weapon. It looks like these people are called guards.}

{110}{}{Put the weapon away immediately.}
{111}{}{I repeat - put the weapon away.}
{112}{}{You were warned.}
{113}{}{There are offices behind this door. You can't go there.}
{114}{}{Hey, leave the stage.}
{115}{}{You'll have to put this away. Openly carrying weapons in the casino is forbidden.}

#Trying to talk
{200}{}{Sorry, you're looking for someone else.}
{201}{}{You're looking for the administrator.}
{202}{}{I'm forbidden from speaking to clients.}
{203}{}{The administrator does not like it when we interfere with clients.}
{204}{}{Just relax. Everything else is the personnel's concern.}
{205}{}{You can expect total security here.}
{206}{}{This is a fair casino, there is no reason to worry.}
{207}{}{We have a zero-tolerance policy regarding theft.}
{208}{}{I hope you are passing your time here spectacularly.}
{209}{}{Have you tried our tequila yet?}
{210}{}{Try the "Atomic Coctail", you feel it to the bone.}
{211}{}{The bar is to that side.}
{212}{}{There are many exceptional drinks in the bar.}
{213}{}{We do not like agressive clients, but it depends on their income.}
{214}{}{Problems?}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}

{250}{}{Don't annoy me, it will end badly for you.}
{251}{}{Don't make your situation worse.}
{252}{}{You want to play - play. But don't annoy security.}
{253}{}{If you behave agressively, you'll end up on the street. Got it?}
{254}{}{You better go away, stupid peasant.}
{255}{}{I'm not here to act as furniture.}
{256}{}{Looking for trouble? You are not in the right place.}
{257}{}{A person with your reputation would better run from the city.}
{258}{}{Your arrogance knows no bounds.}
{259}{}{*ignores you*}

{280}{}{You'll, uhh, have to change that, uhh, suit.}
{281}{}{We can't let you in with that... Uhh, fine, move along.}
{282}{}{You won't cause us trouble, right?}
{283}{}{I have no idea how you intend to play in THAT.}
{284}{}{It's not that we are against it, but you can't just walk in here while wearing such armor.}
{285}{}{Could you leave your armor somewhere... else?}
{286}{}{Yes, yes, of course, uhh, we're always happy to see you, sir... or ma'am...}
{287}{}{Please leave the building. You're going to damage our furniture.}
{288}{}{We can't let you walk around in that... thing.}
{289}{}{You look quite... defiantly in that armor.}

{290}{}{Put away the weapon.}
{291}{}{I suggest you immediately put away the weapon.}
{292}{}{We have a zero-tolerance policy toward the flashing of weapons in the casino.}
{293}{}{If your finger is itching to be on the trigger, get out of the building.}
{294}{}{This isn't an arena, put away the weapon.}
{295}{}{Are you threatening me?}
{296}{}{Carrying a weapon is forbidden in the casino.}
{297}{}{Hey, you. Put away the weapon. We don't want any trouble here.}
{298}{}{Put away the weapon and nobody will get hurt.}
{299}{}{This is a peaceful casino. Don't you dare threaten anyone.}