{100}{}{You see the cashier.}
{101}{}{You see a surprisingly diligent and executive cashier. It looks like she's been well-trained to obey.}
{102}{}{P-sorry, but you'll have to take it off... And-or I'll call security...}

{105}{}{Security! There's a robber here!}
{106}{}{Security! Outsider!}
{107}{}{Leave this room immediately.}
{108}{}{Leave immediately. This is a service room.}
{109}{}{}

#The first dialog
{200}{}{Hello, sir. For the first time in our casino?}
{1200}{}{Hello, ma'am. For the first time in our casino?}
{201}{}{Exactly. I hope you'll explain the local rules?}
{202}{}{The croupier will tell you the rules of the game. And my task is to exchange game chips. Inside the casino, they replace any currency, but you can always exchange them here at the checkout.}
{203}{}{I see.}
{204}{}{Not quite. We are good friends with Don Diego, keep that in mind.}
{205}{}{Oh, I'm sorry, I wasn't warned about you. But keep in mind that the casino rules are the same for everyone. Including Don Diego's friends.}
{206}{}{I see.}
{209}{}{As an honorary member of the club, I should be trusted, shouldn't I?}

#Repeat dialog
{210}{}{What can I do for you?}
{211}{}{Thank you, that's all.}
{212}{}{Uh... yeah?}
{213}{}{Is the casino still working?}
{214}{}{Oh, yes. We are still restoring the interior after the explosion in the cathedral, but you can already use all the standard types of entertainment... if you are satisfied with this mess.}
{215}{}{Mess? Do you even know what kind of world we live in? I'm no stranger to this devastation.}
{216}{}{So the casino is in a state of disrepair? That's it, I'm leaving here.}
{217}{}{I'm sorry, but I'm not allowed to serve you. I can only exchange all your chips if you have any left. Complaints should be addressed to the administrator.}
{218}{}{The service here is just awful.}
{219}{}{Then I'll find another casino. Goodbye.}

#Disclosure of goods for collateral
{220}{}{Can I leave a deposit or some of my things?}
{221}{}{I'm afraid it's not in the interests of the casino. Bottle caps are preferable for us. However, sometimes we make such exceptions.}
{222}{}{Okay, whatever.}
{223}{}{Can Don Diego's friends count on this attitude too?}
{224}{}{Of course, we will make an exception for you. But the limit of caps for such purposes is limited.}
{225}{}{Thank you. I will keep in mind that now you have caps.}
{226}{}{Yes, but I'm sorry, I have no orders in your name.}
{227}{}{No problem.}
{228}{}{I am a merchant, you can not doubt the prospects of my business.}
{229}{}{I believe it willingly. I think we'll make an exception for you. But the limit of caps for such purposes is limited.}
{230}{}{Thank you. I'll keep in mind that now you have caps.}
{231}{}{I believe it willingly. But for a casino, caps are preferable. You can exchange your things at the local market.}
{232}{}{You refuse in vain.}
{233}{}{Tell me, doesn't my name mean anything in this city?}
{234}{}{I'm sorry, you're absolutely right. From now on, you can count on a deposit.}
{235}{}{Thank you. I'll keep in mind that now you have caps.}
{236}{}{I'm sorry, but you know your reputation in *this* city.}
{237}{}{Bitch, are you implying that I'm despised here?}
{238}{}{I'm sorry, but we can't help you.}
{239}{}{Well, that's fine.}

#Denial of the game
{240}{}{It's embarrassing to say this, but the receptionist told me not to serve you anymore.}
{241}{}{How is that? Will I not be able to play at the casino anymore?}
{242}{}{He's crazy. What the hell does that mean?}
{243}{}{Excuse me, I have the strictest orders! All complaints should be addressed to the administrator. I can exchange all your game chips, but I'm not allowed to give out new ones.}
{244}{}{In this case, I just need to talk to the administrator. Have a nice day.}
{245}{}{Of course, there is deception all around. Damn casino...}
{246}{}{Wait! Uh, excuse me... sir...}
{1246}{}{Wait! Uh, excuse me... ma'am...}
{247}{}{Is something wrong?}

#Exchange
{250}{}{I want to exchange the caps for casino chips.}
{251}{}{How many caps do you want to exchange?}
{252}{}{10 caps.}
{253}{}{50 caps.}
{254}{}{100 caps.}
{255}{}{500 caps.}
{256}{}{1000 caps.}
{257}{}{Not at all.}
{258}{}{You are welcome. (you received casino chips in exchange for caps)}
{259}{}{Thank you.}
{260}{}{You don't have enough caps.}
{261}{}{Okay.}
{262}{}{You are welcome. (you got caps in exchange for casino chips)}
{263}{}{Thank you.}
{264}{}{You don't have enough chips.}
{265}{}{Okay.}
{266}{}{You don't have enough money.}
{267}{}{All the bottlecaps I have.}
{268}{}{You are welcome. (you got the caps in exchange for pre-war money)}
{269}{}{Thank you.}

{270}{}{I want to exchange game chips for bottle caps.}
{271}{}{How many chips do you want to exchange?}
{272}{}{10 chips.}
{273}{}{50 chips.}
{274}{}{100 chips.}
{275}{}{500 chips.}
{276}{}{1000 chips.}
{277}{}{Not at all.}
{278}{}{All the chips I have.}

{280}{}{Why are caps so important?}
{281}{}{Caps are a currency. Like pre-war money. They are used to exchange for goods. But unlike depreciated dollars, the rate of caps is set by Followers of Fire. This is one of those wise ideas that the Followers have bestowed on Phoenix.}
{282}{}{So you accept pre-war money?}
{283}{}{Yes, it's possible. Although the pre-war dollars have depreciated, they still bring some confusion to the exchange rate of the caps. Would you like to exchange?}
{284}{}{No, thanks. But I will keep it in mind.}
{285}{}{}
{286}{}{ Yes, I'll need it.}
{287}{}{It's possible. But note that dollars have halved in value. Previously, the course was controlled by the Followers of Fire, but due to the crisis, they can no longer perform this function.}
{288}{}{I see.}
{289}{}{All the pre-war dollars I have.}

{290}{}{I want to exchange pre-war money.}
{291}{}{How many dollars do you want to exchange?}
{292}{}{1 dollar.}
{293}{}{$2.}
{294}{}{$3.}
{295}{}{$4.}
{296}{}{$5.}
{297}{}{$10.}
{298}{}{$50.}
{299}{}{Not at all.}