{100}{}{You see Diego's man.}
{101}{}{You see one of don Diego's men.}

{110}{}{My regards. How is Don Diego?}
{111}{}{I don't understand how you managed to have this relationship with the boss.}
{112}{}{How can I help you?}
{113}{}{Please inform Don Diego of my deep respect toward him.}
{114}{}{Could you you ask the Don to promote me?}

{115}{}{My regards.}
{116}{}{How are you?}
{117}{}{Return to the casino.}
{118}{}{The boss won't like you being here.}
{119}{}{My job is to ensure safety around here.}

{120}{}{It's best not to spend too much time here, for you at least.}
{121}{}{These are offices, what are you doing here?}
{122}{}{You have something you need to say to the boss? Well, then go to him.}
{123}{}{The boss won't like me talking to you.}
{124}{}{If I find out you're a spy...}

{125}{}{What are you doing here?}
{126}{}{Spying?}
{127}{}{Hey, return to the casino immediately.}
{128}{}{These are offices.}
{129}{}{This is no place for you to be in.}