{100}{}{You see the casino manager.}
{101}{}{You see a well-dressed man. He is looking around the casino.}
{102}{}{You can't wear this inside the casino.}

#First dialogue
{200}{}{Welcome to our casino. Note - the *only* functioning casino in all of Arizona.}
{201}{}{Not too impressive. I imagined that this place would be more... lively.}
{202}{}{You're not exactly wrong. It's not the best time to be an inhabitant of Phoenix, and this affects our business as well. In any case, there's nothing we can really do, no?}
{203}{}{Can't argue with that.}
{204}{}{The casino is absolutely amazing. I wonder how you even managed to restore it.}
{205}{}{A very high amount of very hard work. All thanks to Don Diego.}
{206}{}{Interesting.}

#Repeated dialogue
{210}{}{Can I help you with anything?}
{211}{}{There's nothing you could help me with, at least, at this moment.}

#No more casino for you
{220}{}{What is this? Why am I no longer allowed to play at the casino?}
{221}{}{}
{222}{}{We do not interfere with your ability to play. But you can only plays with those chips that you have left. We won't be giving you any new ones.}
{223}{}{Why?}
{224}{}{Explain yourself.}
{225}{}{It is not hard to figure out that when players win, the income of the casino is hurt. And you have won so very, very much. You have earned enough caps to live out the rest of your life in luxury. Isn't it time to make way for new players?}
{226}{}{Pathetic speculator. You won't fool me.}
{227}{}{I understand your thought process. But it still feels like I was cheated.}
{228}{}{Don't fret. We are always happy to have wealthy clients. Let me give you a small present from our casino to maintain a friendly attitude. This bottle contains *real* Pre-War whiskey. No poison and no radiation. An expensive and rare delight in our time.}
{229}{}{And that's all I get? Too little to restore the damage this has caused.}
{230}{}{Thanks for the present.}
{231}{}{I also suggest spending some time in our de luxe suite and and tasting all the delights of life in luxury. It is rarely used, anyways. Here is the key.}
{232}{}{That's more like it.}
{233}{}{You are courtesy itself.}
{234}{}{Please enjoy yourself... Oh, by the way. Don Diego has become interested in you and would like to discuss some kind of mutual business. I already told the guards to let you in.}
{235}{}{Tell him that I'll visit him when I find the time. Goodbye.}
{236}{}{I will go there immediately. I too would like to chat with Don Diego.}
{237}{}{Please enjoy yourself.}
{238}{}{Uh-uh.}
{239}{}{See you later.}

#Asking questions
{250}{}{Do you manage the casino?}
{251}{}{In a way. My name is Bill Gatsby. I am the administrator, but this establishment is owned by Don Diego.}
{252}{}{Who is this Don Diego fellow?}
{253}{}{Alright.}
{254}{}{Have you really never heard of him? He's not just the man, he's *the* man. One of the most respected people in the city. But usually he is reluctant to go out near the clients. He prefers to manage business from his own cabinet.}
{1254}{}{Have you really never heard of him? He's not just the man, he's *the* man. One of the most respected people in the city. But usually he is reluctant to go out near the clients. He prefers to manage business from his own cabinet.}
{256}{}{I suppose it's a sign of reverence. I don't know how and why they started calling him that either.}
{257}{}{Can I meet with him?}
{258}{}{Not a chance. He only allows people to meet him for very important matters.}
{259}{}{In a way. My name is Bill Gatsby, I am the administrator.}

{270}{}{How are you holding up here after the death of Don Diego?}
{271}{}{We could work without him even before. Of course, now I have to work for two. But those are only temporary problems. In the end, Diego was just sitting in his chair all day, while *I* was doing the real work.}
{272}{}{Alright.}
{273}{}{I think you underestimate his contributions. But let's change the subject.}

{275}{}{I see the casino is still operational, even after that explosion.}
{276}{}{Yes, terrible tragedy. We were lucky the blast was underground and was quite far away. Still, the building suffered serious damage. We'll restore everything in a year... Well, at least, if my calculations are correct.}
{277}{}{Alright.}
{278}{}{I find it hard to take what you are saying seriously.}

{280}{}{I heard the Followers were attacked near the casino?}
{281}{}{Yes, terrible tragedy. Personally, I didn't see anything. And I wouldn't like to just paraphrase the rumours I've heard. You should talk to the people who were on the street that day.}
{282}{}{Of course, I'll do exactly that.}
{283}{}{What if you're just drawing away suspicion from your casino? It can't be a coincidence that the attack happened nearby.}
{284}{}{(the administrator becomes uncomfortable) We have done nothing to deserve such an attitude being directed at us. Do you have hard evidence against us? Just as I thought. Then we better end this conversation. Thank you for your understanding.}
{285}{}{Uh-uh. You're lucky if the casino really is not involved.}
{286}{}{Of course, I believe you. Forget about my question.}

#Main character is allied
{290}{}{Come here, amigo. Welcome to the Don Diego family. Now you're now a member, and the family values it's members and doesn't leave them be in bad situations. But you must follow the rules. Rule number one is don't dissapoint the boss.}
{291}{}{Of course, Bill, I understand.}
{292}{}{Great, now I can say that you're are a shit administrator to your face. What are you gonna do?}
{293}{}{You know, there is a bit of truth in your insult. But Don Diego couldn't find anyone better. At the very least, there is mutual trust regarding the casino.}
{294}{}{Why yes, of course.}
{295}{}{Come here, sit down. Now you're a member of the family, and the family values it's members and doesn't leave them be in bad situations. But you should know that the family does not tolerate traitors. Don't dissapoint Don Diego - and you'll save not only your skin, but your whole family. I hope I don't need to repeat this a second time.}
{296}{}{Of course, Bill, I understand.}
{297}{}{I know that you don't really like me, but we are going to work together.}
{298}{}{As an administrator, I am above such things. If the boss trusts you, I'll have to ignore my own opinion of you.}
{299}{}{You're thinking the right way, Bill.}
{300}{}{It's good that we understand each other. (gives a key with a tag) Boss ordered me to settle you into the de luxe suite. Not even I had that honor. Appreciate this generosity.}
{301}{}{Oh wow. Finally, I'll be able to live in acceptable conditions.}
{302}{}{Oh, and by the way, if you think of relaxing in the casino, keep in mind that the rules are the same for everyone. You want to play roulette - buy the chips and play like other players. You get in debt - the casino won't erase it. Understood? Good.}
{303}{}{Fair. Well, I'll be going.}
{304}{}{That won't stop me.}

#Work and access to the boss
{320}{}{You have any vacancies? I'm looking for a job.}
{321}{}{Oh, no, we have plenty of people. Don Diego asked me to no longer concern him with such questions.}
{322}{}{My offer will remain for some time. Goodbye.}
{323}{}{Give me a chance, I'll complete any assignment.}
{324}{}{Fair. Show yourself in action, and we'll see whether we should associate with you or not.}
{325}{}{I'l listening.}
{326}{}{Still, tell his to your boss. What if he becomes interested in having me as a partner?}
{327}{}{It would be pointless. You... don't have the kind of skill we require of partners. Understand what I mean?}
{328}{}{Uh-uh. I understand. That someone here is arrogant.}
{329}{}{No problem. I understand.}
{330}{}{Two respected people in the city should listen to one another, wouldn't you agree?}
{331}{}{Oh, of course. You're quite a famous individual. Perhaps Don Diego really would be interested in talking with you.}
{332}{}{Great. When will I be able to meet him?}
{333}{}{I'm sure your boss has a job for someone like me. I'm an arena champion.}
{334}{}{Huh, we really do sometimes lack strong people. Especially SUCH strong people.}
{335}{}{Great. So, I can go meet your boss?}
{336}{}{Don Diego sent me here for a job. What are the problems you are having?}
{337}{}{A-ah, our new employee. It is so nice to get rid of the burden of responsibility, even if in trivial matters.}
{338}{}{Please continue.}
{339}{}{After the death of Don Diego, everything here has gone to hell. I could really use an intelligent employee.}

{340}{}{I'll tell security to let you in. Don Diego's cabinet is on the second floor. Be polite, don't make sudden movements, keep the weapon in your holster. You got all that? Then go.}
{341}{}{Uh-uh. But you didn't need to explain obvious things.}
{342}{}{Oh, don't worry, I'll be courtesy itself.}

{350}{}{One of our regular clients has completely forgotten about paying up debts. He needs to be reminded. But in such a way so that the debt will be paid.}
{351}{}{Sounds incredibly trivial. What's the catch?}
{352}{}{I don't know if he even has the caps. We heard that he spends all his time drinking and is on the verge of getting thrown out onto the streets. If so, we'll be losing a client, and with him }
{353}{}{ caps... Let's write that down.}
{354}{}{You'll find that son of a bitch in the slums. Go, I have work to do.}
{355}{}{Yeah, see you later.}
{356}{}{About that debtor and his debt.}
{357}{}{Any success there?}
{358}{}{Unfortunately, no.}
{359}{}{Remind me, where does that goner live?}
{360}{}{He lives in the eastern slums. Name is Buddy.}
{361}{}{Understood. Thank you.}
{362}{}{How much does the client owe?}
{363}{}{ caps. We only accept cash. Don't let that speculator fool you with barter or some service. One needs to be vigilant when around people like him.}
{364}{}{ shiny contributions to our bank.}
{365}{}{The client is dead. I can't do anything more.}
{366}{}{Dead? I'm afraid that these unpleasant news will very much dissapoint my boss. Welp, looks like we are no longer going to receive the caps that are lawfully ours. Get lost. We don't need mercs who have no idea how to do the job.}
{367}{}{Hey!}
{368}{}{Here is the debt, }
{369}{}{ caps. Don't ask me how I managed to get it.}
{370}{}{How diligent. I thank you for your assistance. Excellent job. Here is your reward - one fifth of the debt.}
{371}{}{Goodbye.}
{372}{}{If my first assignment went so successfully, maybe your boss will have another one for me?}