{100}{}{Here is a player.}

{101}{}{It looks like this player is very lucky today.}
{102}{}{You see a casino customer. He gets into a rage from a string of wins.}
{103}{}{This player is bored. It looks like he's not winning, but he's not losing either.}
{104}{}{You see a casino customer. He is angry from a string of losses.}
{105}{}{This player panicked his head. Apparently, he lost his entire fortune.}

{109}{}{How did they let you through in such armor?}

#Retaliatory remarks
#- good
{110}{}{Great place, right?}
{111}{}{I'm doing great, and you?}
{112}{}{I'm lucky today.}
{113}{}{This casino is the best place in the world.}
{114}{}{I know how to win, honestly.}
{115}{}{Do you like this game? Sheer pleasure.}
{116}{}{bottlecaps! bottlecaps! bottlecaps!}
{117}{}{Don't scare my luck.}
{118}{}{Why does this always happen to me?}
{119}{}{I just had a breakthrough.}
{120}{}{Step back.}
{121}{}{Don't stand here.}
{122}{}{Today all the chips will be mine!}
{123}{}{I already feel like a part of the machine.}
#Quote from the TV series Star Track season 1 episode 2: I already feel like a part of the remote.
{124}{}{We are old acquaintances with this machine.}
{125}{}{Don't count on a drink.}
{126}{}{Dare to play against me?}
{127}{}{These damn beggar tourists...}
{128}{}{Don't get caught when I'm playing.}
{129}{}{Do you want to share my luck? No, go for a walk.}

#- bad
{150}{}{Terrible place, I can't win anything.}
{151}{}{I'm doing the worst, aren't you?}
{152}{}{I'm really unlucky today.}
{153}{}{This is not a casino, but a den of one-armed robbers.}
{154}{}{I will never win here.}
{155}{}{I shouldn't be playing this game at all. It's hopeless.}
{156}{}{Hey, borrow a couple of caps.}
{157}{}{If I win, I'll give everyone a drink.}
{158}{}{I hope you have better luck than me.}
{159}{}{This streak of bad luck will never end.}
{160}{}{I really need to win.}
{161}{}{Well, it's just a game.}
{162}{}{The dice don't go.}
{163}{}{They are clearly cheating.}
{164}{}{Fortune has turned away from me.}
{165}{}{Wherever you go, there are scammers all around.}
{166}{}{I've already run out of chips.}
{167}{}{Luck is a flighty bitch.}
{168}{}{I managed to win as many as 60 chips! But then...}
{169}{}{My whole life is at stake!}
{170}{}{Be careful, there's deception all around.}
{171}{}{They must have screwed up the machines.}

#Random replicas
#- bad
{200}{}{Come on!}
{201}{}{Why is this game so cruel to me?}
{202}{}{I'm out of luck today.}
{203}{}{Crappy game!}
{204}{}{I hate this game}
{205}{}{I have a fever!}
{206}{}{But it started so well...}
{207}{}{Either I win, or I'm dead.}
{208}{}{If I lose again, I will demolish this place.}
{209}{}{I'm not going anywhere without winning.}
{210}{}{I can't win.}
{211}{}{I'm almost at zero!}
{212}{}{A little more and I'm bankrupt.}
{213}{}{I'm tired of losing.}
{214}{}{Were there really the last chips?}
{215}{}{Damn it!}
{216}{}{If I'm not lucky now, then I'm leaving.}
{217}{}{My pockets are empty.}
{218}{}{Almost got it...}
{219}{}{Not that!}
{220}{}{My affairs are bad.}
{221}{}{Eh, one more time?}
{222}{}{No, no. Stop!}
{223}{}{Oops}
{224}{}{Almost!}
{225}{}{Damn it!}
{226}{}{How did this happen?}
{227}{}{Why me?}
{228}{}{What, again?!}
{229}{}{That's really unlucky...}
{230}{}{I need a drink.}
{231}{}{Everything was against me.}
{232}{}{So close!}
{233}{}{Watch me break the bank.}
{234}{}{Great, one more beggar.}
{235}{}{Ugh, it's time to take a leak.}
{236}{}{By selling my spleen, I can recoup...}
{237}{}{Not in this life.}
{238}{}{Stop mocking me!}
{239}{}{Today is not my day.}
{240}{}{Your mother!}
{241}{}{Oh, no!}

#- good
{300}{}{Yes!}
{301}{}{Don't let me down this time.}
{302}{}{I'm lucky today.}
{303}{}{Great game!}
{304}{}{I love this game.}
{305}{}{Am I dreaming or is it true?}
{306}{}{Great, let's continue.}
{307}{}{Today I can live beautifully.}
{308}{}{If I win, I'll give everyone a drink.}
{309}{}{You can't stop while you're lucky.}
{310}{}{I can't lose, not now.}
{311}{}{I smell a good jackpot.}
{312}{}{At this rate, I will become the richest in the city.}
{313}{}{It's been better.}
{314}{}{bottlecaps! bottlecaps! bottlecaps!}
{315}{}{Yes-s-s!}
{316}{}{I'm definitely going to get lucky now.}
{317}{}{Chips are already out of my pockets.}
{318}{}{That's how it would always be.}
{319}{}{Hurray! Win!}
{320}{}{Jump up again!}
{321}{}{Of course!}
{322}{}{Let's! Come on!}
{323}{}{Great!}
{324}{}{Good!}
{325}{}{Waiter, another drink!}
{326}{}{Lady Luck, don't let me down.}
{327}{}{Who is the winner today? It's me!}
{328}{}{Ha-ha!}
{329}{}{I'll sleep in my coffin.}

#- In front of the stage
{350}{}{Veronica sings well.}
{351}{}{Veronica is beautiful.}
{352}{}{She lacks mobility.}
{353}{}{The singer seemed to be tortured before the performance.}
{354}{}{Her songs are sad.}
{355}{}{What is she singing about?}
{356}{}{Change your repertoire.}
{357}{}{I guess I'll just listen.}
{358}{}{Only here there is a live concert.}
{359}{}{This is the only place where there is a singer.}
{360}{}{I love the casino for this scene.}
{361}{}{There is no other active stage in the city.}
{362}{}{Bartender, another cocktail.}
{363}{}{How much is it, bartender?}
{364}{}{Bartender, the bill!}
{365}{}{I don't seem to have anything to pay with.}
{366}{}{This is the best bar in town.}
{367}{}{They serve great steaks here.}
{368}{}{It's a pity to leave after this.}
{369}{}{}