{100}{}{You see a client.}
{101}{}{You see a client. He has already exceeded his usual daily amount and is actively talking about something to those around him.}

#Before drinking alcohol
{200}{}{(You see a smiling man with an outstanding moustache. His tanned skin and cowboy hat imply a tendency to travel, and the sober look - a dire lack of alcohol in the blood.)}
{201}{}{[Sit nearby]}
{202}{}{(turns around with a sly grin) Hey, friendo, why don't you give me a drink? That one-armed bandit took a-all my money.}
{1202}{}{(turns around with a sly grin) Hey, gurl, why don't you give me a drink? That one-armed bandit took a-all my money.}
{203}{}{Give a total stranger a drink for free? I haven't lost my mind. Not yet, anyway.}
{1203}{}{Asking a lady to give you a free drink? Aren't you ashamed of yourself?}
{204}{}{Whatever you say, pardner. But if you sit next to someone in a bar, be ready to be asked for a drink.}
{1204}{}{Okay, lady, you win. Excuse this old traveler for his tasteless behavior. But that damned slot machine did take the last of my money. I won't be able to give you a drink either, fair lady.}
{205}{}{Next time you'll find a fight, cowboy.}
{1205}{}{I see right through you. Bye, loser.}
{206}{}{Of course, buddy, I'll go and buy you something warm...}
{207}{}{Sorry, I can't. Another time.}
{208}{}{I understand. So long.}
{209}{}{[Get back to more important matters]}
{210}{}{Fine, I'll order you a drink...}
{211}{}{Looks like someone here has nerves of steel. By the way, my request hasn't gone anywhere.}
{1211}{}{Looks like someone here has nerves of steel. By the way, my request hasn't gone anywhere.}

#After drinking alcohol
{220}{}{(takes a sip) A-ah, Oh, that's like an angel dancing over the tip of your tongue. It seems a shame to even digest this alcohol. }
#       Quote from 1957 movie "Jailhouse Rock": "Oh, that's like an angel dancing over the tip of your tongue. It seems a shame to even digest this bourbon."
{221}{}{You speak like you have a lot of experience.}
{222}{}{Oh, these legs have walked many, many miles 'round Phoenix and across the caravan routes. You really interested in that?}
{223}{}{Not really, but continue.}
{224}{}{Most definitely. Tell me about your travels.}
{225}{}{Thanks for the drink.}
{226}{}{You can continue to entertain yourself, but I need some fresh air.}
{227}{}{Enjoy yourself, fellow.}
{228}{}{Only to not deal with you any longer.}
{229}{}{Thanks. People willing to share something with a stranger are rare.}

#The story
{230}{}{I work for caravans as a kind of gun for hire. Sometimes I travel alone in search of wealth. Everyone knows me as an excellent marksman and desert survivalist. Which is why there's no end to the offers I receive. But traveling is becoming more and more dangerous.}
{231}{}{What do you mean?}
{232}{}{You're talking as if it once wasn't.}
{233}{}{Sandstorms have become more common. They say in the past it was much worse. But even now, unfortunate weather can cover entire settlements, and if you encounter a sandstorm in the desert - your chances of survival are 50-50. And that's not even mentioning giant tornadoes or clouds of shining radioactive dust from the west. Looks like nature doesn't want to give the world back to mankind.}
{234}{}{Yes, there can be nothing worse than that when you're going somewhere.}
{235}{}{Heh, an excellent survivalist is scared of some wind with sand.}

{236}{}{Sandstorms are not the worst enemy in travel, no. You can see them from afar and just go around the edge. But people - people are much worse. On caravan routes, we often encountered corpses left behind by bandits. Usually there's nothing left that can even remotely be seen as valuable. But sometimes we see bodies without even meat on the bones.}
{237}{}{I'd resort to cannibalism too. When you're hungry in a vast desert, any food would be welcome, no?}
{1237}{}{I'd resort to cannibalism too. When you're hungry in a vast desert, any food would be welcome, no?}
{238}{}{Really? I wouldn't. There can be more problems from eating human meat than say, a meal consisting of leaves and insects. But I certainly wouldn't judge if someone starving did that.}
{239}{}{Why did you even start talking about that?}
{240}{}{It's terrible, even if someone's starving. What kind of animal can resort to that?}
{241}{}{There's all kinds of evil people outside the city. The highwaymen on the 10th route are the worst of them all. They act like they're the masters of that place. If you're lucky, they'll tell you to pay a tax for passing by - or die. But many don't even ask. They just take everything by force.}
{242}{}{Why did you even start talking about that?}
{243}{}{You're exaggerating. I don't believe there are that many people in the desert.}
{244}{}{Oh, believe me, there are settlements, however rare they are. Usually they're pretty closed to outsiders and don't do anything that attracts attention without good reason. People cling to life even in one of the most hostile of environments.}
{245}{}{Why did you even start talking about that?}

{250}{}{(sighs and after a short pause, takes a sip) There was that one time...}
{251}{}{Go on, tell me what's on your mind, friend. That's what a bar is for.}
{1251}{}{Go on, tell me what's on the mind of the great survivalist. That's what a bar is for.}
{252}{}{And I thought this conversation was coming to an end. But no, we're just getting started.}
{253}{}{...We went to trade in Gila Bend. Turns out the locals left that dry region a long time ago, so we had to return to Phoenix with nothing. On our way back, supplies ran out. And as ill luck would have it, there was nothing edible around - no animals, no plants. Nothing. And to add to that, the heat and the constantly changing desert landscape constantly led us astray.}
{254}{}{How did you survive?}
{255}{}{We met a person along the way. Looked like he was a refugee from Phoenix, looking for a new place to settle down. Unlike us, he had food left.}
{256}{}{So you robbed him?}
{257}{}{One of the guards lost his mind from hunger. We didn't even stop him. We just stood nearby. It was only the 27th stabbing that he calmed down.}
{258}{}{But you survived. Nobody could fault you for doing this in THAT kind of situation.}
{259}{}{You really think so? Welp, means I wasn't mistaken in my choice of who to talk to. I feel a bit better. But still, I could have stopped that madman. And the fact we ran out of supplies was partly my fault. This story will continue to haunt me for some time.}
{260}{}{Nature has no such thing as morals or ethics. In nature, people do whatever it takes to survive. Just forget it.}
{261}{}{Are you kidding me? After knowing what kind of person you are, I don't want to look at you for a second more. Begone from my sight, bandit.}
{262}{}{How did you know how many stab woulds there were?}
{263}{}{I counted them.}
{264}{}{There's no excuse for what you did. No wonder you're seeking comfort in a bar. I hope you never find it.}
{265}{}{Eh... You're right. But isn't the point of a bar to talk about the things that hurt us? At least I feel a bit better.}
{266}{}{Forget it. I'll, uhh, go play roulette. Bye.}
{267}{}{So long, loser. I hope our paths never cross.}

{268}{}{Along the way we saw an old motel. It didn't look completely abandoned. In fact, the doors to the restaraunt were open and there were tempting adverts for nuka-cola.}
{269}{}{Was someone in there?}
{270}{}{There was food and water in there. And because of that, we all lost our minds. The water turned out to be poisoned, and the motel's territory was completely covered in deadly traps. Only I managed to get out of there alive.}
{271}{}{Who could have done such a thing?}
{272}{}{Bandits? Cannibals? The souls of those killed in the Great War? I don't know. But there were legends about that ghostly motel before.}
{273}{}{Great. You kept your mind under control even in such a terrible situation.}
{274}{}{You really think I should be proud? Welp, means I wasn't mistaken in my choice of who to talk to. I feel a bit better. It's a shame I couldn't reason with other people from the caravan.}
{275}{}{Wow, there's a lot to think about here. Don't fret, friendo.}
{276}{}{You aren't thinking that I'll just believe you like that with no hard evidence? Bye, storyteller.}
{277}{}{Yeah, you speak so sadly but in that situation, it could have very well been you who set up that trap.}
{278}{}{You know, you're not the first person who said stuff like that. People talk behind my back. They say that I abandoned or even killed my comrades. But believe me, it's harder surviving in the desert alone than in a noisy group.}
{1278}{}{You know, you're not the first person who said stuff like that. People talk behind my back. They say that I abandoned or even killed my comrades. But believe me, it's harder surviving in the desert alone than in a noisy group.}

{280}{}{I can't get that story about a ghostly motel out of my head. Where is it located?}
{281}{}{Well, I wouldn't want to experience such a thing ever again. But, you see, that place is lost somewhere in the desert. I could't determine it's location on the map. I only know that it's located somewhere to the south-west of Phoenix.}
{282}{}{I only want to know of danger beforehand. So long.}
{283}{}{Will you feel better if I went searching for that place?}
{284}{}{You won't bring back the dead, but you could help other travelers. In any case, be vigilant. It's already bad enough without you being killed in that damned place.}
{285}{}{So long.}
{286}{}{Remind me, what's the direction where the scary motel can be found?}
{287}{}{That place is lost somewhere in the desert. I could't determine it's location on the map. I only know that it's located somewhere to the south-west of Phoenix.}
{288}{}{So long.}
{289}{}{That spooky motel you were talking about turned out to be a real hellhole. Damn, I still feel goosebumps all over my body.}
{290}{}{Wow! Did you really manage to find it?}
{291}{}{Yes. It turned out that a family of monstrous cannibals ran the place. Cunning sons of bitches. But now I can assure you that their enterprise is closed down for good.}
{292}{}{So that's what happened... I immediately had the feeling someone was watching us. Yes, everyone tries to survive in any way they can. But there's no place for stuff like that even in our time. I'm glad you managed to deal with them and avenge my comrades. Thanks. Here, have a drink.}
{293}{}{Goodbye.}