{100}{}{You see a bellboy.}
{101}{}{You see a fairly helpful-looking young man with a look that shows he's looking for approval.}
{102}{}{Y-you're not planning on going to the suite in that... in this... r-right?}
{103}{}{Sorry, buddy, but I'm no longer authorized to serve an asshole like you.}
{1103}{}{Sorry, but I'm no longer authorized to serve a bitch like you.}

{200}{}{How may I help you, sir?}
{1200}{}{How may I help you, ma'am?}
{201}{}{Who are you?}
{202}{}{I am a bellboy. I do small tasks for small rewards.}
{203}{}{Alright.}
{204}{}{Have you achieved any success? I definitely have... Heh-heh.}

{210}{}{Good night, sir.}
{1210}{}{Good night, ma'am.}
{211}{}{Good morning, sir.}
{1211}{}{Good morning, ma'am.}
{212}{}{Good day, sir.}
{1212}{}{Good day, ma'am.}
{213}{}{Good evening, sir.}
{1213}{}{Good evening, ma'am.}
{214}{}{My regards, sir.}
{1214}{}{My regards, ma'am.}
{218}{}{Alright.}
{219}{}{Bye.}

{220}{}{What is this place?}
{221}{}{This is the inside of the casino. There is a small hotel on the second floor. Here, one can rest and gamble.}
{222}{}{Remind me, what is it you do here?}
{223}{}{I do small tasks, sir. I am a bellboy.}
{1223}{}{I do small tasks, ma'am. I am a bellboy.}
{224}{}{What is it you do here?}
{225}{}{So this is a hotel?}
{226}{}{I want to rent a room.}
{227}{}{There is one availaible room. It will cost you }
{228}{}{ caps per night.}
{229}{}{On a second thought, I changed my mind, I don't need a room.}
{1229}{}{On a second thought, I changed my mind, I don't need a room.}
{230}{}{It's a shame I don't have so many caps.}
{231}{}{Great. Here are the caps.}
{232}{}{You have rested well and gathered strength.}

#Improving the de luxe suite
{250}{}{I have settled in the de luxe suite. Can you bring some furniture there?}
{1250}{}{I have settled in the de luxe suite. Can you bring some furniture there?}
{251}{}{Of course, sir. What is it you need?}
{1251}{}{Of course, ma'am. What is it you need?}
{252}{}{On a second thought, there's enough stuff there anyways.}
{253}{}{A pot. [5 caps]}
{254}{}{Small shelves for items. [20 caps]}
{255}{}{A spacious cabinet. [50 caps]}
{256}{}{A refrigerator. [50 caps]}
{257}{}{}
{258}{}{Hmm. Caps first.}
{259}{}{Yes, uhh, of course...}
{260}{}{Done, sir.}
{1260}{}{Done, ma'am.}
{261}{}{Excellent.}
{262}{}{Hmm. Service sure is awful when there are no competitors.}

#Skill increase
{300}{}{Tell me, are the games in this casino really fair?}
{301}{}{Fair... Yeah, I suppose.}
{302}{}{Why did you hesitate?}
{303}{}{Well, it really depends on a lot on stuff. And, in general, chances are better for the casino than the player. But that doesn't mean you can't win and get rich.}
{304}{}{Tell me how to do it. There have to be some tricks, right?}
{305}{}{Uhh, no. (looks in the direction of security and lowers his voice) The boss won't like it.}
{306}{}{Nobody will ever find out. [temptingly show your caps]}
{307}{}{Forget it, then.}
{308}{}{H-heh, anything for our clients. For 300 caps I'll do a little... master-class, yeah. "How you can raise your chances by 5 percent and why that's a lot". Something like that.}
{309}{}{I'll easily win those caps back. When will we start?}
{310}{}{I can't afford this. See you later.}
{311}{}{We'll meet each other at the billiard table on the second floor. And... don't forget about the caps.}
{312}{}{No problem.}

{320}{}{I'm ready to start any moment now.}
{321}{}{Here are the 300 caps. }
{322}{}{Wait a bit. I'll go get the caps.}
{323}{}{Thank you. (looks around, the hides the caps) I suppose we should start with the basic rules...}
{324}{}{[Continue]}
{325}{}{...And never split on fives, then the sum will be ten.}
{326}{}{Oh wow, how complicated. Now I definitely know what NOT to do.}
{327}{}{That's all I know. In the end, this 5 percent will decide your success within the game. And now I have to go. Before the boss suspects anything.}
{328}{}{Thanks for the tips, pal.}
{329}{}{Scram, you're of no use to me anymore.}