{100}{}{You see Veronica.}
{101}{}{You see a quite attractive singer.}
{102}{}{Veronia cannot talk to you at this moment.}

#Song 1 "Nature Boy" 1947
{110}{}{*There was a boy.*}
{111}{}{*A very strange enchanted boy.*}
{112}{}{*They say he wandered very far, very far.*}
{113}{}{*Over land and sea.*}
{114}{}{*A little shy and sad of eye,*}
{115}{}{*But very wise was he.*}
{116}{}{*And then one day,*}
{117}{}{*A magic day he passed my way.*}
{118}{}{*And while we spoke of many things,*}
{119}{}{*Fools and kings,*}
{120}{}{*This he said to me:*}
{121}{}{*«The greatest thing you'll ever learn,*}
{122}{}{*Is just to love and be loved in return».*}

#Song 2 "Mexicali Rose"
{150}{}{*Mexicali Rose, stop crying.*}
{151}{}{*I'll come back to you some sunny day.*}
{152}{}{*Ev'ry night you'll know that I'll be pining.*}
{153}{}{*Ev'ry hour a year while I'm away.*}
{154}{}{*Dry those big brown eyes and smile, dear.*}
{155}{}{*Banish all those tears and please don't sigh.*}
{156}{}{*Kiss me once again and hold me.*}
{157}{}{*Mexicali Rose goodbye.*}

#Dialogue
{200}{}{Oh, hi.}
{201}{}{Bye.}

{210}{}{Oh, hi.}
{211}{}{Bye.}
