{100}{}{You see a bartender.}
{101}{}{You see a bartender. As you fully expected to.}
{102}{}{No, no, you'll break all the dishes in that "suit"...}
{103}{}{This is a service space. Please sit at the counter.}
{104}{}{I need to get back to the bar.}

#Floating lines
{110}{}{"Fires of Vegas" and brahmin steak.}
{111}{}{I'm sorry, we're out of "Nuka-Rum".}
{112}{}{"Ashes of Los Angeles" are done.}
{113}{}{Here's your "Nuclear Mary".}
{114}{}{Who ordered the "Atomic Cocktail"?}
{115}{}{That's enough, pal.}
{116}{}{Don't swallow it all at once.}
{117}{}{Trust me, this one will give you a steel boner.}
{118}{}{Wouldn't your parents be against it? Just kidding.}
{119}{}{Coffee? O-o-oh, you're a real connoisseur.}

#Dialogue
{200}{}{First time in the casino? I hope you like it here.}
{201}{}{Maybe.}
{202}{}{Oh, why so much skepticism? Relax. This is the only place in the city where one can truly do that, after all.}
{203}{}{I don't require your support, bartender.}
{204}{}{Really? Well, in that case I should stay here for some time.}
{205}{}{Pour me something strong, buddy. Because I intend to hit a jackpot.}
{206}{}{Now that's the spirit. I wish you luck.}
{207}{}{I don't need luck. This establishment does.}
{208}{}{Thank you.}

{210}{}{Do you want a drink?}
{211}{}{I will abstain for now.}

{212}{}{Hey, look, it's the new arena champion! How unexpected. Oh, wait, I know this is not fully following the rules, but I just want to offer you a bottle of beer, personally, from myself. Because that was awesome. (speaking to himself) I'll tell everyone about this...}
{213}{}{Thanks, dude. Really kind from you.}
{214}{}{This looks more like piss than alcohol to me. But I certainly like your attitude.}

{215}{}{Oh, it's you. How is Don Diego doing? I see you found a common tongue.}
{216}{}{Just shut up and pour me a drink.}
{217}{}{Yeah, he's doing excellent. What's the alcohol he was touting so much in this bar?}
{218}{}{I'm offering you to try some tequila of our own production. The best you can find today. (leans over and lowers his voice) By the way, there are special prices for our men in the casino.}
{219}{}{50% discount? That's nice.}

{220}{}{What do you know about the shootout that happened on the street?}
{221}{}{Shady stuff, let me tell ya. Someone attacked monks who were just peacefully going somewhere. I didn't see anything myself, but heard a lot of versions of what happened. Don't believe all of those rumours.}
{222}{}{What if I pay you good money?}
{223}{}{Look, we don't like talking about this subject here. Let's end this conversation.}
{224}{}{If I find out you're hiding something - you're dead.}
{225}{}{Of course I believe you. Forget about this whole question, friend.}

{230}{}{Who runs this place?}
{231}{}{Right now, our administrator took over. He got this whole establishment almost for nothing. Someone did him a huge favor by killing Don Diego. (contemplating) Well, in any case, I still work here.}
{232}{}{I understand.}
{233}{}{You need the administrator? He's in that room near the stage.}
{234}{}{No, I mean the owner of the casino.}
{235}{}{This whole establishment is owned by Don Diego. It was he who gathered people and restored the casino. Why do you ask?}
{236}{}{Just curious. Don't mind me.}
{237}{}{I want to meet him.}
{238}{}{I'm afraid that will be more difficult than you think - one does not simply go meet Don Diego. Go talk to the administrator. He decides who meets the boss.}
{239}{}{Alright.}

{240}{}{Have you seen George Crook?}
{241}{}{(unhappily points above)}
{242}{}{What? He is already in the kingdom of heaven? Oh no. what a tragedy... Or do you mean he's on the second floor?}
{243}{}{Room on the second floor? Got it.}

{250}{}{You know everything that happens around here, right?}
{251}{}{I'm sorry, but I don't spread rumours and information. Boss won't like it.}
{252}{}{Then I have nothing to do here.}
{253}{}{Alright, no problem.}
{254}{}{I thought bartenders knew everything.}
{255}{}{That's not far from the truth. But I am also taught to follow the rules.}
{256}{}{I'll give you a tip.}
{257}{}{That won't change anyting, sir.}
{1257}{}{That won't change anyting, ma'am.}
{258}{}{Hmm. Let's do the opposite - I'll pay you to spread positive rumours about me.}
{259}{}{I don't understand, is this some kind of joke? You have an excellent reputation in the city. I can't believe you really need heroic legends about yourself.}
{260}{}{You're right... Fine, forget it then.}
{261}{}{Welp, off I go spending caps on more important things.}
{262}{}{A-ah, I understand. You need a good reputation to kickstart a career? Yeah, I could think of something.}
{263}{}{We aren't in a hurry. Let's get back to this topic later.}
{264}{}{I have to go get my cash. So long.}
{265}{}{I'll pay you 100 caps. I just need rumours of good deeds.}
{266}{}{A small tale about your trustworthiness? That's easy.}
{267}{}{I'll pay you 200 caps. Make up something... outstanding, but no fanaticism.}
{268}{}{An impressive story on the streets? Or a captivating scuffle in the desert? I'll find something to talk about.}
{269}{}{I'll pay 300 caps. But you must do everything within your power.}
{270}{}{Heroic legend? (snaps fingers) I have an idea! I know what to do, you can count on me.}
{271}{}{Here are the caps. I will await results with great anticipation, partner.}
{272}{}{I'll spread rumours of the highest quality, sir.}
{1272}{}{I'll spread rumours of the highest quality, ma'am.}
{273}{}{See you later.}
{274}{}{Any problems? Don't worry, I'll wait.}
{275}{}{Uhh, I just need to count them all one more time...}

{280}{}{Do you only have alcoholic beverages?}
{281}{}{For the most part, yeah. I can also offer clean water, if you'd like. But few are able to obtain that luxury.}
{282}{}{Where do you get the beverages from?}
{283}{}{We have numerous sources. The beer is produced by a couple of moonshiners. Sometimes we find something out of the ordinary in ancient ruins. For instance, Pre-War whiskey. But the tequila we produce ourselves.}
{284}{}{Yourselves? Are you kidding me?}
{285}{}{Tequila is our specialty. We order raw material from the southern plantations and turn it into drinks and rubbing alcohol right here. As far as I know, we are the only ones doing such things.}
{286}{}{Real production in our times? Very impressive.}
{287}{}{Hmm, homemade alcohol? Always alarmed me.}
{288}{}{Water, beer, whiskey and, of course, our own tequila.}
{289}{}{Well yes, of course.}
{290}{}{Where is your famed tequila? I'd like to order some, but the shelves are empty.}
{291}{}{I'm sorry, there's a small force majeure at the production site. We're in the process of solving the problem, but it will take some time.}
{292}{}{What a terrible tragedy. I hope you find a solution soon.}
{293}{}{What kind of a casino is this that you can't even order a drink? One truly can't find a worse establishment.}
{294}{}{We have numerous sources. The beer is produced by a couple of moonshiners. Sometimes we find something out of the ordinary in the ancient ruins. For instance, Pre-War whiskey. The tequila we used to produce ourselves, but the machine stopped working. We're still working on that problem.}
{295}{}{You made your own tequila? Go on, I'm curious.}
{296}{}{You made it yourselves? What a shame it ended.}