{100}{}{There is a guard in front of you.}
{101}{}{You see the casino bouncer. He keeps a close eye on the order.}
{102}{}{You see the casino bouncer. He's looking out for thieves.}
{103}{}{You see the casino bouncer. He's watching the front door.}
{104}{}{You see the casino bouncer. He's following a couple of questionable visitors.}
{105}{}{You see the casino bouncer. He looks around bored.}
{106}{}{You see a casino bouncer with a fake stern look.}
{107}{}{You see a man in a suit and with a gun. I think they call them guards.}

{110}{}{Put the weapon away immediately.}
{111}{}{I repeat - put your weapon away.}
{112}{}{You were warned.}
{113}{}{There are service rooms behind this door. You can't go there.}
{114}{}{Hey, get off the stage.}
{115}{}{You'll have to clean it up. The open carrying of weapons is prohibited in the casino.}

# Trying to talk
{200}{}{Sorry, it's not for me.}
{201}{}{You need an administrator.}
{202}{}{I am forbidden to communicate with clients.}
{203}{}{The administrator does not like it when we interfere with clients.}
{204}{}{Have fun, the staff will take care of the rest.}
{205}{}{You are completely safe here.}
{206}{}{This is an honest casino, there's nothing to worry about.}
{207}{}{We do not tolerate theft here.}
{208}{}{I hope you have a great time.}
{209}{}{Have you tried our tequila yet?}
{210}{}{Try the "Atomic Cocktail", it burns to the bone.}
{211}{}{The bar is that way.}
{212}{}{There are a lot of great drinks in the bar.}
{213}{}{We don't like violent, but it depends on the profit.}
{214}{}{Any problems?}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}

{250}{}{Don't bother me, otherwise it will end badly.}
{251}{}{Don't make your situation worse.}
{252}{}{If you want to play, play. But don't mess with the guards.}
{253}{}{If you run amok, you'll fly out into the street. Is it clear?}
{254}{}{Better go away, you stupid peasant mug.}
{255}{}{I'm not here for furniture.}
{256}{}{Looking for problems? You're not in the best place for this.}
{257}{}{A man with your reputation should run out of town.}
{258}{}{There is no limit to your arrogance.}
{259}{}{*ignores you*}

{280}{}{You, uh, have to leave this, uh, suit.}
{281}{}{We can't let you in on this... Uh, okay, come on in.}
{282}{}{You won't cause us any problems, will you?}
{283}{}{I can't imagine how you will play in THIS.}
{284}{}{Not that we mind, but you can't come here in this armor.}
{285}{}{Could you please leave your armor somewhere... elsewhere?}
{286}{}{Yes, yes, of course, uh, you're always welcome, sir... or ma'am...}
{287}{}{Please leave the room. You will ruin our furniture.}
{288}{}{We can't let you walk in this one... piece.}
{289}{}{You look, uh, defiant in that armor.}

{290}{}{Put away your weapon.}
{291}{}{I advise you to remove your weapon immediately.}
{292}{}{We do not tolerate when weapons are shone in the casino.}
{293}{}{If your fingers itch on the trigger, then go outside.}
{294}{}{There's no ring here, put your weapon away.}
{295}{}{Are you threatening me?}
{296}{}{It is forbidden to bring weapons into the casino.}
{297}{}{Hey you, put the gun away. We don't need any problems here.}
{298}{}{Put away your weapon and no one will get hurt.}
{299}{}{We have a peaceful casino, don't you dare threaten anyone.}