{100}{}{You see a croupier.}
{101}{}{You see a neat man in a suit. For a while, you watch in fascination how deftly he shuffles the cards.}
{102}{}{Uh, I'm afraid you won't be able to hold the cards in THIS...}
{103}{}{Sorry, sir, I'm forbidden to serve you.}
{1103}{}{Sorry, ma'am, But I'm not allowed to serve you.}

#Acquaintance
{200}{}{(There is a table in front of you for playing card games, and at the table, a neat man with a serious look deftly shuffles a deck of cards.) Do you play blackjack?}
{201}{}{Not today.}
{202}{}{No, I don't know the rules.}
{203}{}{The call is accepted. But first, explain the rules.}
{204}{}{For the most part, this is a kind of blackjack. You need to collect the sum of 21 points with the minimum number of cards with nuclear bombs. Having collected the right number, you can "bomb" the deck. This game requires a little more intelligence than roulette or a slot machine. But the stakes are higher here, too. If, of course, you are willing to take the risk.}
{205}{}{Undoubtedly.}
{206}{}{Are you playing?}
{207}{}{Yes.}
{208}{}{No.}

#Bids
{210}{}{A new batch. Place your bets.}
{211}{}{ chips)}
{212}{}{I'm not playing.}
{213}{}{I would love to join, but I don't have any chips.}
{1213}{}{I would love to join, but I don't have any chips.}
{214}{}{My bet is 10 chips.}
{215}{}{My bet is 20 chips.}
{216}{}{My bet is 30 chips.}
{217}{}{My bet is 40 chips.}
{218}{}{Bets are accepted. I'm starting the distribution.}
{219}{}{Start.}

{220}{}{Remind me, what was the last bill?}
{221}{}{Account }
{222}{}{ k }
{223}{}{in your favor.}
{224}{}{in favor of the casino.}
{225}{}{Good. Let's continue.}
{226}{}{My bet is 50 chips.}

{230}{}{(The dealer takes out two cards and puts them face down. Then he turns one of them over, showing the nominal value in }
{231}{}{ points)}
{232}{}{Me.}
{233}{}{(You got two face value cards }
{234}{}{ points)}
{235}{}{[Next]}
{236}{}{(On your hand are cards worth }
{237}{}{ points. The dealer has open cards worth }
{238}{}{ points.) Your actions?}

{240}{}{I give up.}
{241}{}{The first player leaves the game. Half of the bet burns out.}
{242}{}{Gentlemen, I will leave you.}
{243}{}{Double the bet.}
{244}{}{The bid is doubled. Let me remind you that you can raise the bet only once per game.}
{245}{}{The bid has been doubled.}
{246}{}{[Continue playing]}
{247}{}{Pass.}
{248}{}{The first player skips a card. We continue the distribution ...}
{249}{}{[Continue playing]}
{250}{}{More.}
{251}{}{The first player takes a card...}
{252}{}{[Continue playing]}

{260}{}{First player: Nuclear Jack! Would you like to play more?}
{261}{}{No thanks.}
{262}{}{Oh yes, I want to play more.}
{263}{}{Casino: Blackjack. Your bet is burning out. Do you want to recoup?}
{264}{}{Yes, I just need to recoup.}
{265}{}{Well, no.}
{266}{}{First player: defeat. Your bet is burning out. Do you want to recoup?}
{267}{}{Casino: defeat. Would you like to continue?}
{268}{}{Draw. The players stay with their own. Do you want to continue?}
{269}{}{The card limit is exhausted.}