{100}{}{Here is bellboy.}
{101}{}{You see a very helpful young man with an ingratiating look.}
{102}{}{Q-you're not going to check into the room in this one... in this...}
{103}{}{Sorry, buddy, but I was forbidden to serve an ass like you.}
{1103}{}{Sorry, but I was forbidden to serve a bitch like you.}

{200}{}{What can I do for you, sir?}
{1200}{}{What can I do for you, ma'am?}
{201}{}{Who are you?}
{202}{}{I'm a bellboy. I run small errands for a small fee.}
{203}{}{Clear.}
{204}{}{Any progress? I definitely have... Heh heh.}

{210}{}{Good night, sir.}
{1210}{}{Good night, ma'am.}
{211}{}{Good morning, sir.}
{1211}{}{Good morning, ma'am.}
{212}{}{Good afternoon, sir.}
{1212}{}{Good afternoon, ma'am.}
{213}{}{Good evening, sir.}
{1213}{}{Good evening, ma'am.}
{214}{}{My respects, sir.}
{1214}{}{My respects, ma'am.}
{218}{}{I see.}
{219}{}{Bye.}

{220}{}{What is this place?}
{221}{}{Inside the casino, and on the second floor there is a small hotel. Here you can relax and gamble.}
{222}{}{Remind me, what are you doing here?}
{223}{}{Running small errands, sir. I'm a bellboy.}
{1223}{}{Running errands, ma'am. I'm a bellboy.}
{224}{}{What are you doing here?}
{225}{}{So this is a hotel?}
{226}{}{I want to rent a hotel room.}
{227}{}{There is one spare room. With you }
{228}{}{ caps per night.}
{229}{}{Don't, I've changed my mind.}
{1229}{}{Don't, I've changed my mind.}
{230}{}{I wish I had so many caps.}
{231}{}{Good. Here are the bottlecaps.}
{232}{}{You have had a good rest and gained strength.}

#Arrangement of the suite
{250}{}{I checked into a suite. Can you get some furniture in there?}
{1250}{}{I moved into a suite. Can you bring some furniture in there?}
{251}{}{Of course, sir. What do you need?}
{1251}{}{Of course, ma'am. What do you need?}
{252}{}{However, everything is already forced there.}
{253}{}{Pot. [5 caps]}
{254}{}{Small shelves for things. [20 caps]}
{255}{}{Roomy cabinet. [50 caps]}
{256}{}{Refrigerator. [50 caps]}
{257}{}{}
{258}{}{Ahem. bottlecaps forward.}
{259}{}{Yes, yes, uh, of course...}
{260}{}{All ready, sir.}
{1260}{}{All set, ma'am.}
{261}{}{Great.}
{262}{}{Yeah. The service is terrible when there are no competitors.}

#Skill Enhancement
{300}{}{Tell me, is the game in this casino really fair?}
{301}{}{Honest... Yes, perhaps.}
{302}{}{Why did you hesitate?}
{303}{}{Well, it depends a lot on probabilities. And they are generally slightly higher at the casino than at the player. But that doesn't mean you can't win and get rich.}
{304}{}{Tell me how to do it. Surely there are all sorts of tricks?}
{305}{}{Uh, no. (looks around at the guard and lowers his voice) The boss won't like it.}
{306}{}{No one will know about it. [it's tempting to show your caps]}
{307}{}{Then forget it.}
{308}{}{H-hy, everything is for our customers. For 300 caps, I will spend a small one... a master class, yes. "How can you raise your chances by five percent and why is it a lot". Something like this.}
{309}{}{I can easily win back such caps. When do we start?}
{310}{}{I can't afford it. See you later.}
{311}{}{Meet me at the billiard table on the second floor. And this... don't forget the caps.}
{312}{}{No problems.}

{320}{}{I'm ready to start anytime.}
{321}{}{Here are 300 caps. }
{322}{}{Wait a little longer. I'll have to go get the caps.}
{323}{}{Thank you. (looking around hides the bottlecaps) Let's start with the general rules...}
{324}{}{[Continue]}
{325}{}{...And never split on fives, then the sum will be equal to ten.}
{326}{}{Wow, it's not easy. Now I know exactly what NOT to do.}
{327}{}{That's all I know. Ultimately, these five percent of luck will decide your fate in the game. Okay, I'll go before the boss suspects anything.}
{328}{}{Thanks for the tips, man.}
{329}{}{Get lost, I don't need you anymore.}