{100}{}{You see the casino barker.}
{101}{}{There's a man in front of you. He accosts passersby, inviting them inside the casino.}
{102}{}{Someone killed the barker at the casino. It seems that Don Diego's death has untied the hands of street bandits.}
{103}{}{Wait a minute, isn't that security looking for you? Oh, yeah, you'd better stay out of the casino.}

{110}{}{Hey, do you need to lift the caps quickly?}
{111}{}{Stop rummaging through the ruins! Here you will earn caps without leaving the place!}
{112}{}{The only casino in all of Arizona!}
{113}{}{Open your uranium vein right in Phoenix!}
{114}{}{Uranium and caps! Caps and uranium!}
{115}{}{Never before has the radiation sign meant a mountain of caps!}
{116}{}{Come in, fortune's favorites.}
{117}{}{Are you passing by? Maybe you're missing the last chance to get rich!}
{118}{}{Don't pass by!}
{119}{}{The casino is open to everyone, including babies and mutants.}