{100}{}{You see the bartender.}
{101}{}{You see the bartender. You are not at all surprised to see him here.}
{102}{}{No, no, in this "suit" you will break all the dishes...}
{103}{}{This is a service area. Please sit at the counter.}
{104}{}{I need to get back to the bar.}

#Floating replicas
{110}{}{"Vegas Lights" and brahmin steak.}
{111}{}{I'm sorry, the "Core-Rom" is over.}
{112}{}{"Ashen Los Angeles" is ready.}
{113}{}{Here is your "Nuclear Mary".}
{114}{}{Who ordered the "Atomic Cocktail"?}
{115}{}{You've had enough, buddy.}
{116}{}{Don't swallow it all at once.}
{117}{}{Believe me, this cocktail is an inflexible boner.}
{118}{}{Do your parents mind? Come on, I'm kidding.}
{119}{}{Coffee? Wow, you're a real connoisseur.}

#Dialog
{200}{}{For the first time in a casino? I hope you like it here.}
{201}{}{Maybe.}
{202}{}{Oh, why so much skepticism? Relax, this is the only place in the city where you can relax.}
{203}{}{I don't need your support, bartender.}
{204}{}{Really? In that case, I should stay here.}
{205}{}{Pour me something stronger, buddy. Because I'm going to break the bank.}
{206}{}{That's the attitude. Good luck.}
{207}{}{Your institution will need it.}
{208}{}{Thank you.}

{210}{}{Would you like something to drink?}
{211}{}{I'll abstain for now.}

{212}{}{Hey, look, it's the new arena champion! This is a surprise. Oh, wait, I know it's not really according to the rules, but I want to put a bottle of beer on. Because it's cool. (about myself) I will tell everyone now...}
{213}{}{Thanks, man. That's very kind of you.}
{214}{}{This swill is urine. But I like your attitude.}

{215}{}{Oh, it's you. How is Don Diego? I see you've found a common language.}
{216}{}{Shut up and pour me a drink.}
{217}{}{Yes, just fine. What kind of alcohol did he praise so much in this bar?}
{218}{}{I suggest you try tequila of our production. The best of what you can find today. (leans over and lowers his voice) By the way, there are special prices for their own in the casino.}
{219}{}{Half discount? That's cool.}

{220}{}{What's the story of the shooting on the street?}
{221}{}{A dark matter. Someone attacked the monks walking peacefully. I didn't see anything myself, but I heard a lot of versions. Do not trust all these rumors.}
{222}{}{And if I pay well?}
{223}{}{Listen, we don't like to talk about this topic. Let's end this conversation.}
{224}{}{If I find out that you're hiding something, you're finished.}
{225}{}{Of course I believe you. Forget about my question, buddy.}

{230}{}{Who runs everything here?}
{231}{}{Now our administrator has taken up the case. He got the whole business, consider it a gift. Someone had done him a great favor by killing Don Diego. (thoughtfully) Well, at least I'm still working here.}
{232}{}{I see.}
{233}{}{Do you need an administrator? He's in that room near the stage.}
{234}{}{No, I'm talking about the casino owner.}
{235}{}{Don Diego owns all this property. It was he who gathered people and restored the casino. Why do you ask?}
{236}{}{Simple curiosity. Nevermind.}
{237}{}{I want to meet him.}
{238}{}{It won't be easy. Talk to the administrator. He decides who to let see the boss.}
{239}{}{OK.}

{240}{}{Have you seen George Crook?}
{241}{}{(pointing up with a gesture of displeasure)}
{242}{}{What? Is he already in heaven? Oh no, what a grief... Oh, he's just on the second floor.}
{243}{}{A room on the second floor? Clearly.}

{250}{}{You know everything that's going on here, right?}
{251}{}{I'm sorry, but I don't sell rumors and information. The boss doesn't like it.}
{252}{}{I have nothing else to do here.}
{253}{}{I understand, no problem.}
{254}{}{I thought the bartenders knew everything.}
{255}{}{This is not far from the truth. But I'm also trained to follow the rules.}
{256}{}{I'll tip you.}
{257}{}{It won't change anything, sir.}
{1257}{}{It won't change anything, ma'am.}
{258}{}{Hmm. Let's do the opposite - I'll pay if you spread good rumors about me.}
{259}{}{I don't understand, is this some kind of prank? You have a great reputation in the city. I can't believe you really need a heroic legend.}
{260}{}{But you're right... Okay, forget it.}
{261}{}{Well, I'm going to spend the caps on something more meaningful.}
{262}{}{Ah, I understand, you need a good reputation to start a career. Yes, something can be thought of.}
{263}{}{Don't be in a hurry. We will return to this topic later.}
{264}{}{I'll have to go get the cash. See you later.}
{265}{}{I'll pay 100 caps. I just need good rumors.}
{266}{}{A short story about your trustworthiness? It's not difficult.}
{267}{}{I'll pay 200 caps. Come up with something outstanding, but without fanaticism.}
{268}{}{An impressive story from the streets? Or an exciting brawl in the desert? I'll find something to tell you about.}
{269}{}{I'll pay 300 caps. But you have to do your best.}
{270}{}{A heroic legend? (snapping fingers) Idea! I know what to do, you can count on me.}
{271}{}{Here are the bottlecaps. I'm waiting for the results, partner.}
{272}{}{I'll do it in the best possible way, sir.}
{1272}{}{I'll do it in the best possible way, ma'am.}
{273}{}{See you later.}
{274}{}{Any problems? Nothing, I'll wait.}
{275}{}{Uh, we need to recalculate...}

{280}{}{Do you only have alcoholic beverages?}
{281}{}{Basically, yes. I can also offer clean water if you like. But few are willing to afford this luxury.}
{282}{}{Where do you get your drinks from?}
{283}{}{We have many sources. Beer is produced by a couple of moonshiners. Sometimes something special, like pre-war whiskey, can be found in old ruins. But we produce tequila ourselves.}
{284}{}{Ourselves? Are you kidding?}
{285}{}{This is our pride. We order raw materials from southern plantations. Already here we are preparing drinks and medical alcohol from it. As far as I know, we are the only ones in this case.}
{286}{}{Real production nowadays? That's impressive.}
{287}{}{Hmm, homemade alcohol? This always worries me.}
{288}{}{Water, beer, whiskey, and, of course, tequila of our production.}
{289}{}{Well, yes, of course.}
{290}{}{Where is your famous tequila? I wanted to order a couple of bottles, but the shelves are empty.}
{291}{}{I apologize. A small force majeure in production. We are solving the problem, but it will take some time.}
{292}{}{Very sorry. I hope you will find a solution.}
{293}{}{What kind of casino is this if you can't even drink here? It is impossible to find a worse institution.}
{294}{}{We have many sources. Beer is produced by a couple of moonshiners. Sometimes something special, like pre-war whiskey, can be found in old ruins. We made tequila ourselves, but the moonshine machine fell into disrepair. We are still working on this problem.}
{295}{}{Did you make tequila yourself? Well, well, pour on.}
{296}{}{Own production? It's a pity that it went down.}