{100}{}{You see the manager of the casino.}
{101}{}{You see a well-dressed man. He's looking around the casino.}
{102}{}{It is not necessary to walk in this within the casino.}

#The first dialog
{200}{}{Welcome to our casino. Note - *the only* operating casino in all of Arizona.}
{201}{}{Not impressive. I thought it would be more... lively.}
{202}{}{Your truth. The population of Phoenix is going through a bad time, it affects our business as well. In any case, there is no choice, is there?}
{203}{}{You can't argue with that.}
{204}{}{The casino is just super. It's amazing how soon you managed to restore it.}
{205}{}{We have come to this through long and hard work. All thanks to Don Diego.}
{206}{}{Curious.}

#Repeat dialog
{210}{}{Can I be of any help?}
{211}{}{Nothing yet.}

#Ban casino games
{220}{}{What do you allow yourself? Why am I not allowed to play at the casino?}
{221}{}{}
{222}{}{We're not bothering you to play. But only for the chips that you have left. We will not give out new chips.}
{223}{}{Why?}
{224}{}{Take the trouble to explain.}
{225}{}{It is not difficult to guess that other people's winnings hurt the casino's capital. And you've already earned enough caps for a comfortable old age. It's time to make way for new players. Don't you think?}
{226}{}{Pathetic speculator, you can't trick me around your finger.}
{227}{}{I can understand your logic, but it's still a shame.}
{228}{}{Don't get upset. After all, we are always happy to have wealthy clients. Let me make a little present from our casino to keep a friendly mood. This bottle contains *real* pre-war whiskey. He is not poisoned or irradiated. An expensive and rare pleasure in our time.}
{229}{}{And that's it? Not enough to heal the wound in my soul.}
{230}{}{Thank you for the gift.}
{231}{}{I also propose to settle in a suite for a while and taste all the delights of living in luxury. This number is rarely used anyway. Here's the key.}
{232}{}{Already something.}
{233}{}{You're all courtesy.}
{234}{}{Have a nice time... Oh, by the way. Don Diego is interested in your person and would like to discuss some common business. I already told the guards to let you through.}
{235}{}{Tell him I'll drop by when I have some free time. Later.}
{236}{}{Certainly. I would also like to chat with Don Diego.}
{237}{}{Have a nice time.}
{238}{}{Yeah.}
{239}{}{See you later.}

#Questions
{250}{}{Are you the one running the casino?}
{251}{}{In a way. My name is Bill Gatsby. I am an administrator, but Don Diego owns this place.}
{252}{}{Don Diego - who is this?}
{253}{}{I see.}
{254}{}{What, you've never heard of him? This is a man with a capital letter. One of the most respected people in the city. But usually, he is reluctant to show himself to clients and manages things from his office.}
{1254}{}{What, you've never heard of him? This is a man with a capital letter. One of the most respected people in the city. But usually, he is reluctant to show himself to clients and manages things from his office.}
{255}{}{Why is he called Don?}
{256}{}{It's probably a sign of respect. I don't know how and why they started calling him that.}
{257}{}{Can I meet him?}
{258}{}{Hardly. He accepts only on a particularly important matter.}
{259}{}{In a way. My name is Bill Gatsby, I'm an administrator.}

{270}{}{How are you coping here after Don Diego's death?}
{271}{}{We could work autonomously before. Of course, now I have to work for two. But these are temporary problems. In the end, Diego was just sitting in his pants in his chair, and it was me who did the real work.}
{272}{}{I see.}
{273}{}{I think you underestimate his contribution to the business... Shall we change the subject?}

{275}{}{I see the casino is still working after that explosion?}
{276}{}{Yes, a terrible story. We were lucky that the explosion was underground and was far enough away. And yet the building has suffered serious damage. We will restore it to its former form in a year... Well, I'm counting on it.}
{277}{}{I see.}
{278}{}{I hardly believe it.}

{280}{}{They say that Followers were killed near the casino.}
{281}{}{Yes, a terrible story. Personally, I didn't see anything. And retelling rumors is an unpleasant business. Talk to those who were on the street that day.}
{282}{}{Of course I will.}
{283}{}{Or maybe you're protecting your casino? After all, the attack happened nearby for a reason.}
{284}{}{ (the administrator's face is distorted in tension) We did not deserve such distrust. Do you have any hard evidence against us? I knew it. Then we'd better end this conversation. Thank you for understanding.}
{285}{}{You're singing too sweetly. You're lucky if the casino is really not in business.}
{286}{}{Of course I believe you. Forget about my question.}

#GG - your man
{290}{}{Come in, amigo. Welcome to Don Diego's family. Now you are your own person, and the family values its people and does not leave them in trouble. But you follow the rules, too. Don't upset the boss - this is the first of them.}
{291}{}{Of course, Bill, I understand everything.}
{292}{}{Great, now I can tell you straight - you're a shitty administrator. Well, did you eat it?}
{293}{}{You know, there is some truth in your hurtful words. But Don Diego did not find anyone better for this position. At least he and I have full confidence in the casino's work.}
{294}{}{Well, yes, of course.}
{295}{}{Come in, have a seat. Now you are your own person, and the family values its people and does not leave them in trouble. But keep in mind that he does not tolerate traitors. Don't upset Don Diego - and you will save not only your skin but the whole family. I hope I won't have to repeat it twice.}
{296}{}{Of course, Bill, I understand that.}
{297}{}{I know you don't like me. But we have to work together.}
{298}{}{As an administrator, I'm above that. If the boss trusts you, then I can close my eyes to personal prejudices against you.}
{299}{}{You're thinking right, Bill.}
{300}{}{It's good that we understand each other. (holds out a key with a tag) The boss told me to put you in a suite. Even I haven't had the honor. Appreciate this generosity.}
{301}{}{Wow. Finally, I will be able to live in human conditions.}
{302}{}{By the way, if you decide to relax in the casino, then keep in mind - the rules of the game are the same for everyone. If you want to play roulette, buy the chips and play like a regular player. If you get into debt, the casino will not write them off from the account. Is that clear? That's good.}
{303}{}{Honest rules. Well, I'll go.}
{304}{}{It won't stop me.}

#Work and admission to the boss
{320}{}{Do you have any vacancies open? I'm looking for a job.}
{321}{}{Oh no, we have enough people. Don Diego asked me not to bother him with such questions anymore.}
{322}{}{My offer will remain valid for a while. Goodbye.}
{323}{}{Give me a chance, I'll do any task.}
{324}{}{That's fair. Show yourself in action, and we'll see if it's worth contacting you.}
{325}{}{I'm listening.}
{326}{}{Still, tell your boss. What if he's interested in our partnership?}
{327}{}{It's useless. Your candidacy... not quite the level to talk about partnership. Do you understand?}
{328}{}{Yeah. I understand. Someone here is quite arrogant.}
{329}{}{No problems. I understand everything.}
{330}{}{Two respected people in the city should listen to each other. Don't you find it?}
{331}{}{Oh, of course, you are a well-known person in the city. Perhaps Don Diego will be interested in talking to you.}
{332}{}{Great. When can I meet him?}
{333}{}{Surely your boss will have a job for me. I'm the champion of the ring.}
{334}{}{Hmm, sometimes we don't have enough strong guys. Especially SO strong.}
{335}{}{Great. So can I meet your boss?}
{336}{}{Don Diego sent me to work. What are your problems?}
{337}{}{Ah, this is our new employee. How nice it is to get rid of the burden of responsibility, at least in small things.}
{338}{}{Go on.}
{339}{}{After Don Diego's death, we had a real hell. I really could use a smart employee.}

{340}{}{I'll tell the guards to let you through. Don Diego's office is on the second floor. Behave politely with him, do not make sudden movements, and keep your weapon in a holster. Is everything clear? Go.}
{341}{}{Yeah, you didn't have to explain the obvious things.}
{342}{}{Oh, don't worry, I'll be the nicest.}

{350}{}{One of our regular customers completely forgot about paying debts. It is necessary to remind him. But so that the debt is paid.}
{351}{}{Sounds incredibly banal. What's the catch?}
{352}{}{I don't think it has bottlecaps at all. They say he's completely drunk and is on the verge. If so, we will lose the client, and with it our bottlecaps. And this by the way }
{353}{}{ caps... So let's write it down.}
{354}{}{You'll find that son of a bitch in the slums. Go, I have a lot of work to do.}
{355}{}{Yes, I'll see you.}
{356}{}{About that debtor and his debt.}
{357}{}{What are the successes in this case?}
{358}{}{Unfortunately, none. But I'm working on it.}
{359}{}{Remind me, where does this guy live?}
{360}{}{He lives in the eastern slums. His name is Badi.}
{361}{}{I see. Thank you.}
{362}{}{How much does the client owe the casino bank?}
{363}{}{ caps. We accept cash only. Don't let this speculator cheat with barter or some kind of service. With people like him, you have to be on your guard.}
{364}{}{ ringing investments in the bank.}
{365}{}{The client is dead. There's nothing more I can do.}
{366}{}{Dead? I'm afraid this unpleasant news will upset my boss terribly. Well, it turns out that we all lost our legal caps. Get lost. We don't need mercenaries who don't know how to work.}
{367}{}{Hey!}
{368}{}{That's his duty, }
{369}{}{ caps. Don't ask me how I did it.}
{370}{}{That's how dutiful it is. Thank you for your cooperation. Great job. Here is your fee - one-fifth of the amount owed.}
{371}{}{Have a nice day.}
{372}{}{If my first assignment is so successful, then maybe your boss has another job for me?}