{100}{}{You see Diego's man.}
{101}{}{You see one of Don Diego's men.}

{110}{}{My respects. How is Don Diego?}
{111}{}{I can't understand how they got along with the boss.}
{112}{}{Can I help you with something?}
{113}{}{Give my deep respects to Don Diego.}
{114}{}{Could you ask Don for my promotion?}

{115}{}{My respects.}
{116}{}{How are you?}
{117}{}{Go back to the casino.}
{118}{}{The boss won't like you being here.}
{119}{}{My job is to monitor security.}

{120}{}{You'd better not linger here.}
{121}{}{These are office premises, what are you doing here?}
{122}{}{Do you have business with your boss? So go to him.}
{123}{}{The boss won't like me talking to you.}
{124}{}{If I find out you're a spy...}

{125}{}{What are you doing here?}
{126}{}{Spying?}
{127}{}{Hey, get back to the casino right away.}
{128}{}{These are office premises.}
{129}{}{You don't belong here.}