{100}{}{You have a client in front of you.}
{101}{}{You see the client. He has already gone over his daily allowance and is actively telling others something.}

#Before the use of alcohol
{200}{}{(In front of you is a smiling man with a gorgeous mustache. His tanned skin and cowboy hat indicate a propensity to travel, and a sober look indicates an acute lack of alcohol in the blood.)}
{201}{}{[Sit next to the counter]}
{202}{}{(turns around with a sly grin) Hey, buddy, can you buy me a drink? This one-armed bandit took all my cash from me.}
{1202}{}{(turns around with a sly grin) Hey, miss, can you buy me a drink? This one-armed bandit took all my cash from me.}
{203}{}{Give someone a drink for free? I'm not completely out of my mind yet.}
{1203}{}{Asking a lady for a drink? Aren't you ashamed?}
{204}{}{Whatever you say, buddy. But if you sit down with someone in a bar, be prepared to be asked for a drink.}
{1204}{}{Okay, lady. Yours took it. Excuse the old traveler for his tactlessness. But that damn slot machine took my last cash. I won't be able to buy you a drink, too, beauty.}
{205}{}{Next time you'll get into a fight, cowboy.}
{1205}{}{Everything is clear with you. Goodbye, loser.}
{206}{}{Of course, buddy, now I'll buy you something hot...}
{207}{}{Sorry, I can't. Another time.}
{208}{}{I understand. Be.}
{209}{}{[Get back to your important business]}
{210}{}{Okay, I'll order you a drink...}
{211}{}{Someone must have balls of steel here. By the way, my request is still valid.}
{1211}{}{Someone must have nerves of steel here. By the way, my request is still valid.}

#After using alcohol
{220}{}{ (takes a sip) Ah, as if angels are dancing on the tip of the tongue. It's a pity to even swallow such alcohol. }
# Quote from the movie "Prison Rock" 1957: "It's like angels dancing on the tip of your tongue. It's a pity to even swallow such bourbon."
{221}{}{You say that as if you have a wealth of experience.}
{222}{}{Oh, these feet have trampled many miles around Phoenix and along the caravan routes. Are you interested in this?}
{223}{}{Actually, no, but keep going.}
{224}{}{Definitely. Tell us about your travels.}
{225}{}{Thanks for the drink.}
{226}{}{Have fun, and it's time for me to get some fresh air.}
{227}{}{Enjoy it, buddy.}
{228}{}{It's just to get you behind.}
{229}{}{Thank you. It's not often you meet people who are ready to share something with a stranger.}

#Story
{230}{}{I work for the caravans, as a free mercenary. Sometimes I travel alone in search of wealth. Everyone knows me as a great shooter and survivalist in the desert. Therefore, there is no end to offers. But traveling is getting more dangerous.}
{231}{}{What do you mean?}
{232}{}{You'd think they were once safe.}
{233}{}{Dust storms have become more frequent. They say it used to be much worse. But even now, in a bad season, whole settlements are brought in, and if you are caught by a storm in the desert, the chances of survival are 50-50. What to say about giant tornadoes or clouds of poisonous glowing dust from the west. Apparently, nature does not want to give the world to man again.}
{234}{}{Yes, nothing can be worse than this on the way.}
{235}{}{Ha, an experienced survivalist, but I was afraid of a breeze with sand.}

{236}{}{Dust storms are not the most formidable opponent on the road. You can see it from afar and can walk around the edge. But people - people are much more insidious. On the caravan routes we often met corpses left by robbers. And if they usually remove all valuable junk from them, then they come across bodies without meat on the bones.}
{237}{}{I would also resort to cannibalism. In a hungry desert, all food will be of use, won't it?}
{1237}{}{I would also resort to cannibalism. In a hungry desert, all food will be of use, won't it?}
{238}{}{Seriously? I wouldn't. There can be more harm from human meat than from dry rations from leaves and insects. But I certainly won't condemn such an act in conditions of hunger.}
{239}{}{Why are you even talking about this?}
{240}{}{It's horrible. Even in conditions of hunger. What kind of animals are capable of this?}
{241}{}{There are enough rabble outside the city. The angriest of all are the mainline drivers on Route 10. They behave like the owners of the road. Pay the tax for the passage - or you will die. Although many do not even ask and take everything by force.}
{242}{}{Why are you even talking about this?}
{243}{}{You're just escalating the situation. I do not believe that the desert is so crowded.}
{244}{}{Oh, believe me, there are settlements there, even if few. Usually they are quite closed and do not stick out for no reason. People cling to life even in the driest regions.}
{245}{}{Why are you even talking about this?}

{250}{}{(sighs and takes a sip after a short pause) I had one case...}
{251}{}{Come on, tell me what's on your mind, buddy. That's why it's a bar.}
{1251}{}{Come on, tell me what's on the soul of the great survivalist. That's why it's a bar.}
{252}{}{Well, it's started. It already seemed to me that the conversation was coming to an end.}
{253}{}{...We went to trade in Gila Bend. It turned out that the locals had long since left this arid area, and we had to return to Phoenix with nothing. We ran out of supplies on the way back. As luck would have it, there was nothing edible in the area - no animal, no vegetation. And the heat and the changing sandy landscape constantly led us astray.}
{254}{}{How did you survive?}
{255}{}{On the way we met a man. Apparently, he was a refugee from Phoenix, looking for a new place to live. Unlike us, he still had provisions left.}
{256}{}{So you robbed him?}
{257}{}{One of the guards lost his head from hunger. And we didn't even stop him and just stood there. He plunged the knife into the traveler's body twenty-seven times until he calmed down.}
{258}{}{However, you survived. You can hardly be blamed for SUCH a situation.}
{259}{}{Do you really think so? Well, then, I was not mistaken in choosing an interlocutor. I felt a little better. And yet I could have stopped that madman. Besides, the lack of provisions was partly my fault. This story will still torment my soul for a while.}
{260}{}{There is no morality and ethics in nature. In nature, people survive. Just forget this story.}
{261}{}{Are you kidding? Yes, after such a story, I don't want to see you. Get out of my sight, bandit.}
{262}{}{How do you know how many times he stabbed?}
{263}{}{I was counting.}
{264}{}{There is no excuse for you. No wonder you're looking for comfort in a bar now. I hope you won't find it.}
{265}{}{Eh... Your truth. But that's what this bar is for, to talk about the painful, right? At least I got a little better.}
{266}{}{Never mind, never mind. I'm, uh, going to play roulette. Be there.}
{267}{}{Come on, loser. I hope our paths will never cross again.}

{268}{}{On the way we came across an old motel. It didn't look completely abandoned. On the contrary, the doors to the restaurant were open and beckoned with advertisements for life-giving Nuka-Cola.}
{269}{}{Was there someone inside?}
{270}{}{There was water and food inside. As a result, we all lost our heads. The water turned out to be poisoned, and the territory of the motel is riddled with deadly traps. Only I could get out of there alive.}
{271}{}{Who could have arranged such a thing?}
{272}{}{Bandits? Cannibals? The souls of the dead during the Great War? I don't know. But there have been legends about this ghostly motel before.}
{273}{}{Cool. You kept your mind under control even in a critical situation.}
{274}{}{Do you really think I should be proud of that? Well, then, I was not mistaken in choosing an interlocutor. I felt a little better. It's a pity that I couldn't bring my brothers from the caravan to reason.}
{275}{}{Wow, there's a lot to think about. Cheer up, my friend.}
{276}{}{Well, well, you don't think I'll take your word for it, do you? Come on, storyteller.}
{277}{}{You sing beautifully. In such a situation, you could have set this trap yourself.}
{278}{}{You know, you're not the first one to say that. People are whispering behind their backs. They say that I abandoned or even killed my comrades. But believe me - it's harder to survive alone in the desert than a noisy company.}
{1278}{}{You know, you're not the first one to say that. People are whispering behind their backs. They say that I abandoned or even killed my comrades. But believe me - it's harder to survive alone in the desert than a noisy company.}

{280}{}{I can't get the ghost motel story out of my head. Where is it located?}
{281}{}{Well, yes, I wouldn't want to be in such a mess either. But you see, this place is lost somewhere in the desert. I couldn't determine its location on the map. I only know that it is located southwest of Phoenix.}
{282}{}{I just want to know about the danger in advance. Be.}
{283}{}{Will it make you feel better if I look for this place?}
{284}{}{You can't bring back the dead, but you can help these other travelers. In any case, be careful. It was not enough for your soul to stay in that cursed place.}
{285}{}{Be.}
{286}{}{Remind me, which direction was that creepy motel?}
{287}{}{This place is lost somewhere in the desert. I couldn't determine its location on the map. I only know that it is located southwest of Phoenix.}
{288}{}{Be.}
{289}{}{That creepy motel you were talking about turned out to be a real hell. Damn, I still have goosebumps all over my body.}
{290}{}{Oh! Did you manage to find him?}
{291}{}{Well yes. It turned out that a devilish family of cannibal monsters runs everything there. Sly sons of bitches. But now their shop is securely closed.}
{292}{}{That's it... And I immediately felt that someone was watching us. Yes, everyone survives as best they can. But this is not the place even in our time. I am glad that you managed to cope with them and avenge my comrades. Thank you. Here, have a drink on me.}
{293}{}{Be there.}