{100}{}{You see the casino's advertiser.}
{101}{}{You see a man. He is bothering people walking by, inviting them to visit the casino.}
{102}{}{Someone killed the casino's advertiser. Looks like the death of Don Diego has untied the hands of the local street bandits.}
{103}{}{Wait, aren't you that person security's been looking for? In that case, I do *not* recommend you visit our casino.}

{110}{}{Hey, need a way to earn caps fast?}
{111}{}{Stop being like a rat looking around ruins! Here, you can earn caps without even moving!}
{112}{}{The only casino in all of Arizona!}
{113}{}{Strike your own uranium vein right in Phoenix!}
{114}{}{Caps 'n Uranium! Caps 'n Uranium!}
{115}{}{Never before has the sign of radiation meant a whole load of caps!}
{116}{}{Come, lovers of radfortune.}
{117}{}{Passing by? Maybe you're missing out on your last chance to become rich!}
{118}{}{Don't pass by!}
{119}{}{The casino is open for all who want to play, including children and mutants.}