{100}{}{You see a tramp.}
{101}{}{This tramp wanders aimlessly around the square.}
{102}{}{This inadequate tramp is actively chanting something in honor of the church.}
{103}{}{This guy barely moves across the square.}
{104}{}{This refugee wanders aimlessly around the square.}

#Floating replicas
#- beggar
{110}{}{Leave me alone.}
{111}{}{I do not know what to do.}
{112}{}{Such as me, nothing shines in the city.}
{113}{}{I'm going to lie down here... you don't mind?}
{114}{}{I want to quit this street life, but I can't.}
{115}{}{Phoenix is thriving, and I'm falling further and further.}
{116}{}{This, do you have some food for the poor brother from the street?}
{117}{}{Borrow some caps, I'll give it, honestly.}
{118}{}{I really need medicine for the baby. Help me out, huh?}
{119}{}{I'm starving, at least give me a rat's tail.}
{120}{}{Do you want to join? Sorry, but the area won't fit so many.}
{121}{}{I'm waiting for the fanatics to bring us free food.}
{122}{}{The cathedral sometimes distributes leftovers after lunch.}
{123}{}{When the food is taken out, you need to kiss the priest's feet.}
{124}{}{Praise the Fire! All people are brothers! See, I'm a believer too.}

#- adept
{130}{}{I want to become a novice, but they won't take me.}
{131}{}{I'm telling you - I'll become a novice!}
{132}{}{We'll have to pray a lot to be accepted into the order.}
{133}{}{Peace! Love! Sacred Fire!}
{134}{}{Do you also believe in something-there?}
{135}{}{What do YOU believe in?}
{136}{}{Hail the Sacred Fire!}
{137}{}{Hail Phoenix! Hail, Aaron!}
{138}{}{I love Aaron! Hail, Aaron, Lord of the Phoenix!}
{139}{}{My life belongs to Saint Aaron}

#- sick or disabled
{150}{}{I am here to ask for healing from an illness.}
{151}{}{There is no escape from my illness, but the monks promised to help.}
{152}{}{They say monks possess the ancient sacrament of healing.}
{153}{}{I pray to Aaron every day to heal my sores.}
{154}{}{I gave all my savings to the church, but I never cured my illness.}
{155}{}{The monks treat me with prayers. And I feel a surge of strength! Oh, no...}
{156}{}{The monks say I need to purify my soul. And for this you need to give everything to the church.}
{157}{}{I'm so worthless, right?}
{158}{}{I ask my followers to help me.}
{159}{}{Only Followers of Fire can heal as well as before the Great War.}

#- refugee
{170}{}{I am here to seek refuge from the Followers of Fire.}
{171}{}{I was told that the church accepts refugees, but this is not the case.}
{172}{}{We fled from bandits, but the church does not want to receive us.}
{173}{}{Followers of Fire help refugees.}
{174}{}{The monks here are unusually round-cheeked. They are probably ill with something.}
{175}{}{Only near the temple do I feel safe.}
{176}{}{They are strange - these fire worshippers.}
{177}{}{These fanatics promise paradise on earth.}
{178}{}{They say we should be afraid, but I don't understand what or who.}
{179}{}{It's better to give food, and everyone can preach.}