{100}{}{You see Mathias.}
{101}{}{You see one of the Followers. It looks as if he has retreated deep into himself.}
{102}{}{Act, adept.}
{103}{}{The man performs rapid prayer about the salvation of all mankind.}
{104}{}{. . .}
{105}{}{Now the church shall return to it's original mission. I will forever be thankful to you.}
{106}{}{So, the operation failed? But this is not the end. Aaron and his Advisor must be killed for the good of the city.}
{107}{}{So, the operation failed? But this is not the end. Aaron must be killed for the good of the city.}
{108}{}{So, the operation failed? But this is not the end. The Advisor must be killed for the good of the city.}

{200}{}{How dare you distract me from my prayer? Go away.}
{201}{}{Uhh...}

#Questions
{210}{}{I asked you not to distract me from my prayer.}
{211}{}{Whatever you say.}
{212}{}{Who are you?}
{213}{}{My name is Mathias. Now go and close the door behind you.}
{214}{}{But...}
{215}{}{What is it you do here, Mathias?}
{216}{}{At this moment, I believe I am talking to you. And thus pointlessly wasting my time. Go away.}
{217}{}{Wait...}
{218}{}{Doesn't look like you're too concentrated on your prayer.}
{219}{}{Ugh... If someone wasn't interfering with my ability to meditate, it would be much easier.}
{220}{}{So is it prayer or meditation? Looks like you mixed something up.}
{221}{}{Hm. You are persistent, I'll give you that. Like lice in old robes. What do you want?}
{222}{}{I want to talk.}
{223}{}{Nothing, nothing.}

{230}{}{This is pointless. If you need answers, head to the preachers on the first floor.}
{231}{}{I will do exactly that. Goodbye.}
{232}{}{Of course, brother Mathias. I'm sorry for disturbing you.}
{233}{}{Who do I go to if I want to find myself a mentor?}
{234}{}{It is obvious that you do not need one.}
{235}{}{Before asking that question, think whether you need one at all.}

#The rebels' quest
{250}{}{I am here on behalf of Marcos.}
{1250}{}{I am here on behalf of Marcos.}
{251}{}{Marcos... Who is that?}
{252}{}{What do you mean "who is that"? Wasn't he supposed to contact you?}
{253}{}{Your uncertainty is like a groan of an atom in the womb of a mushroom cloud. Go and return only when your thoughts are in order.}
{254}{}{Uhh, okay...}
{255}{}{You know who I'm talking about. The one who sits underground and desires the same revenge you do.}
{256}{}{Ah, yes, of course... Revenge... A pathetic emotion of primitive creatures living out a meaningless existence. Don't you dare compare yourself, an inhabitant of the fetid sewers, to me. My whole body is oppressed by the very thought of what Aaron did to our church.}
{257}{}{So you are against his politics?}
{258}{}{We are not interested in your motives. The important thing is that our goal is the same.}
{259}{}{In the past, the church carried the light of Pre-War wisdom into this devastated world. We did not participate in conflict. Our banner was not a symbol of tyranny. But Aaron has sold his soul to the Atomic Devil. And I can tolerate this no more.}
{260}{}{Good. So, how do we get rid of him?}
{261}{}{Getting rid of Aaron is not our main objective. For the church is now far greater than it seems. We are intertwined with other forces in Arizona, our banner directs whole settlements to a new way. You can't just kill one man to stop this process.}
{262}{}{So, what are you proposing, prior Mathias?}
{263}{}{I say we blow up the Ccathedral. I know, it sounds crazy. But there is a way it could be done. There are underground levels below this building, where, for several years, scientists have been creating a new weapon. One capable of destroying this entire building.}
{264}{}{A weapon of such power is hard to even imagine. But wouldn't it hurt the rest of the city?}
{265}{}{The church has already caused enough damage to this fragile world. But do not worry, the city will remain intact.}
{266}{}{Why couldn't you do this yourself?}
{267}{}{I tried, once. And now I am forbidden from descending there without permission. But you have the element of surprise.}
{268}{}{Don't get me wrong, the idea isn't bad, but I'd also like to live.}
{269}{}{Find the fuses in the professor's office. After their activation, you will have a couple of minutes to escape.}
{270}{}{Good. But how do I get in? It's a restricted area, after all.}
{271}{}{I will give you a key and Follower robes. Pretend to be someone new and unfamiliar with this place, who was sent there to bring the professor a report.}
{272}{}{Give me the key and robes. I'll head there immediately.}
{273}{}{May the Holy Fire forgive us. Amen.}
{274}{}{Uhh, whatever you say, prior. Farewell.}

{275}{}{Aaron and his Advisor are guarded well, but you will be able to succeed if you act quickly and decisively. We must catch them off-guard in different parts of the cathedral, so that they will not be able to fight together. I shall arrange it so that peaceful monks will not interfere with your battle.}
{276}{}{Great. I'll tell you when we'll start. Meanwhile, you go warn the monks.}
{277}{}{But could this be resolved without bloodshed?}
{278}{}{Unfortunately, Aaron and his allies will not go down without a fight. But there is another way. Below the cathedral there are entire underground levels. The Advisor has been spending the last few years developing a new weapon there. One so powerful that it could destroy this entire building.}
{279}{}{Nonsense. We don't have to destroy anything, we'll just take the cathedral over. I'll tell you when we'll start. Meanwhile, you go warn the monks.}
{280}{}{That's a crazy plan. But it just so happens that I like crazy.}
{281}{}{You're the last best hope for peace. I will give you the key to the basement where the Advisor is located. I will also tell my accomplices that they are not to interfere. Go, act.}
{282}{}{Great.}

#Aaron's quest
{300}{}{I think there's something we need to discuss. It is related to the recent attacks on the monks.}
{301}{}{It is obvious that your investigation is not progressing well if you are talking about it with the first person you see.}
{302}{}{I mean, you're not wrong. Maybe you could give me some advice?}
{303}{}{Do not fret. And watch yourself. Not merely novices could become victims. But also those who stand in the way of our enemies.}
{304}{}{You're no help at all.}
{305}{}{Uhh, thanks for the "advice".}

{310}{}{Actually, the situation is completely the opposite. Upon reading the library records it becomes obvious that you examined the schedules of the novices.}
{311}{}{Of course. As one of the temple caretakers, I have access to this data. And if you do not want to end up burned at the stake, I suggest you find something better to say to me. Now go.}
{312}{}{Not so fast. I also know that you've been sending encrypted messages via the radio station.}
{313}{}{But...}
{314}{}{Actually, there is something else. You've been sending encrypted messages. To whom and for what purpose, I do not know. I'm hoping you have a satisfactory answer ready.}
{315}{}{As a temple caretaker, I cannot let outsiders hear my transmissions. And where did YOU get access to the radio station? This is very suspicious.}
{316}{}{You should be more concerned about the records at the library. You were clearly examining the schedules of the novices.}
{317}{}{It's not what you think...}
{318}{}{I only have to say a word and Aaron will be conduct a full inspection of your activities and contacts. What do you say in response?}
{319}{}{You are testing my patience, atomic worm. Get out.}
{320}{}{Your loss.}
{321}{}{Ah, heavens! You only recently came into this temple, yet you dig deeper than the prophets of Vault-Tek.}
{322}{}{Vault... What?}
{323}{}{So you admit that you have been sending information to enemies of the church?}
{324}{}{It is not wise to disturb the peace contained within these bedrooms. If you need answers, I shall give them to you in a safer place. Meet me in the confessional on the first floor. Don't worry, my legs have not experienced running for a long time.}
{325}{}{Good. But don't even think of setting up some trick.}
{326}{}{Of course, the walls might have ears.}

#Dialogue in the confessional
{330}{}{I must admit I did not expect that some outsider from the wasteland could solve this case. I managed to hide my actions even from Aaron. But you...}
{331}{}{But why are you, a servant of Aaron, helping his enemies?}
{332}{}{Under Aaron's leadership, the church has betrayed it's every founding principle. What was once stronghold of holiness and wisdom has now become a repository of sin. I cannot look at it any longer.}
{333}{}{Tell me about it.}
{334}{}{About a decade ago, we were but a peaceful church far away from the people. We stored Pre-War relics and knowledge to give them to someone worthy of it.}
{335}{}{I see you found such someone?}
{336}{}{Men from the south came. They convinced our priors to switch sides and using the church as a tool, they arranged a revolution in the city. Aaron became the Overlord of Phoenix, even though before this he was a mere middle-level cleric.}
{337}{}{And this does not suit you?}
{338}{}{Our mission was the protection of ancient knowledge. We should have been more careful with whom we let near ourselves. We have commited a terrible mistake, for which we will all end up in the Atomic Underworld.}
{339}{}{Who are these people who are attacking the novices?}
{340}{}{Who are these people that you're helping?}
{341}{}{It's a long story. Since the beginning of the Phoenixian revolution, a group of rebels existed that call themselves the "Liberation Party". Until now, thir plan was to stay out of the limelight, gather strength and then one day overthrow Aaron with the element of surprise. Even though I do not agree with them on everything, we had a deal about the church leaving the city.}
{342}{}{Now explain why I shouldn't ruin your plans.}
{1342}{}{Now explain why I shouldn't ruin your plans.}
{343}{}{But why are you, a prior of the Cathedral, helping it's enemies?}
{344}{}{I do not care what drives you. Simply say why I should keep this case open.}
{345}{}{Sooner or later, Aaron will find the one who leaked the information. But I am concerned not for my material shell, but for the church's mission.}
{346}{}{So you want to convince me to join your side?}
{347}{}{For a start, I suggest you meet the rebels and discuss everything with them personally.}
{348}{}{This is stupid. I'm going to Aaron.}
{349}{}{In that case you leave me no choice. May the Holy Fire forgive us...}
{350}{}{Uhh...}
{351}{}{Alright, I agree. It will be interesting to hear out the other side of the story.}
{1351}{}{Alright, I agree. It will be interesting to hear out the other side of the story.}
{352}{}{Let it be so. Find the Party headquarters under the "Union" station. You can only get there via the underground. Tell them that you are there on my behalf, and meanwhile, I will try to warn them. Good luck.}
{353}{}{Until we meet again, prior Mathias.}
{354}{}{I changed my mind. I'm going to Aaron.}
{1354}{}{I changed my mind. I'm going to Aaron.}
{355}{}{Act, novice.}
{356}{}{Good.}
{357}{}{I must know which one of the cardinals is leaking you information about the gang.}
{358}{}{What is this haughty question? Even if I knew, I wouldn't tell you.}
{359}{}{But you're not denying that?}
{360}{}{We have spies all over the city. And we receive information from them in many different ways. There is nothing surprising about this.}
{361}{}{I do not have any more questions.}
{362}{}{I can trust you, yes? Murphy is one of us. He joined the gang to show these poor, ignorant people the righteous path.}
{363}{}{It is very good that you told me this. Thank you.}