{100}{}{You see a Follower of the Holy Fire.}
{101}{}{You see one of the Followers. He's either whispering a prayer or total nonsense.}
{102}{}{His Majesty Aaron is waiting for you.}
{103}{}{The Overlord of Phoenix is waiting for you.}

{110}{}{*Incomprehensible mumbling*}
{111}{}{Would you like to join the Church of the Holy Fire?}
{112}{}{The ignorant who fail to embrace the Fire will perish in its flames.}
{113}{}{The Holy Fire punished the ancients for their sins.}
{114}{}{The Fire is the only way to salvation.}
{115}{}{Greetings, brother.}
{116}{}{Has the Holy Fire illuminated you as well?}
{117}{}{Soon the Holy Fire will illuminate all of Arizona.}
{118}{}{We are all but descendants of one protoflame.}
{119}{}{To be illuminated is to illuminate others.}

{1114}{}{The Fire is the only way to salvation.}
{1115}{}{Greetings, sister.}
{1116}{}{Has the Holy Fire illuminated you as well?}
{1117}{}{Soon the Holy Fire will illuminate all of Arizona.}
{1118}{}{We are all but descendants of one protoflame.}
{1119}{}{To be illuminated is to illuminate others.}
