{100}{}{You see the signalman.}
{101}{}{Here is one of the Followers.}
{102}{}{What is it? Lost? The exit is over there, but outsiders are not allowed here.}
{1102}{}{What is it? Lost? The exit is over there, but outsiders are not allowed here.}
{103}{}{Greetings, brother. May the Sacred Fire light you up.}
{1103}{}{Greetings, Sister. May the Sacred Fire light you up.}
{104}{}{Merciful Atom... what's wrong with me?}
{105}{}{...I see... Sacred Fire...}
{106}{}{I think I've had enough... Don't tempt me anymore, please...}