{100}{}{You see an old friend.}
{101}{}{This is one of the Followers of the Holy Fire... that has only recently joined them.}

{200}{}{(You see your old friend that once spied on the Rangers; he seems depressed and weak-willed, his eyes have dimmed, and the old bandit-like manners seem to have completely become a thing of the past)}
{201}{}{Well, well, well, what a surprise...}
{202}{}{(the muddy eyes rise up with some effort and barely identify you) You... I remember you. Looks like the Holy Fire brought us together that day. Thanks to you, I am now here, among the Followers. Thank you.}
{203}{}{Uhh, you're welcome. It's good to be participating in someone else's personal growth.}
{204}{}{I didn't think you'd survive that journey. But that doesn't matter.}

{210}{}{I must now pray. Please, don't bother me.}
{211}{}{Bye.}

{220}{}{How did you manage to come here all the way from Parker Dam?}
{221}{}{Don't ask me about such nonsense. I am above such things now.}
{222}{}{Then I'll leave you alone with your... prayer.}
{223}{}{What is it like being a novice in the Temple of Fire?}
{224}{}{Labor and prayer. This is all that we need. Until I become mature enough for something more important. And that can be decided only by my mentor.}
{225}{}{Hm, let me take a look at your pupils.}
{226}{}{What are these? The silly jokes of a peasant?}
{227}{}{Well, uhh, yes, kind of.}
{228}{}{Looks like you're being pumped full of drugs here.}
{229}{}{Well... Our lunch does contain a few laxatives. It's all part of the initiation process. We must rid our mind of hubris, the monks say... oof... I think I ought to go...}
{230}{}{Uhh, I should leave you alone.}