{100}{}{You see a Follower of the Holy Fire.}
{101}{}{You see one of the Followers. He has completely withdrawn into his own world from frantic prayer.}

{200}{}{...Heaven will become earth... the Fire that giveth... pitiful before His very face... Fire... for the unfaithful are doomed... And the sun in the palms of our hands...}
{201}{}{Hey, what are you bumbling about?}
{202}{}{...the Fire is strength...}
{203}{}{Your Fire is a myth.}
{204}{}{(interrupts prayer and stares through you blankly) The Fire... is... truth...}
{205}{}{Oh, well this explains everything. Bye.}
{206}{}{Uhh, it's best not to disturb him...}
