{100}{}{You see a delegate.}
{101}{}{You see a man not from the cult. He looks like a real savage inside the walls of the Cathedral.}

{200}{}{Hey, you. Bring me some of your fruit. I want to eat.}
{201}{}{Why would I do that?}
{202}{}{Ah, so you are not from the Followers? Then get lost, I don't care about you. Only the Church of the Holy Fire is deserving of my respect. They are the future of these lands! The others are mere trash.}
{203}{}{Who are you, anyway?}
{204}{}{I'm the chieftain of the eastern tribe. We're making an alliance with the Followers. We want to become part of this great nation.}
{205}{}{An alliance between a cult and a tribe? Why would the church want that?}
{206}{}{The church cares about the people of the Wasteland. What, this your first time in the city? Just look at how much good the Church has brought here. The Followers have conquered the Sun and have imprisoned it within sticks and lamps. Is this not proof of their greatness, their divine strength?}
{207}{}{Do you even understand at least a part of their teachings?}
{208}{}{Well, no. But the Followers promised to explain! They will set up a temple in our valley, they will teach us to understand the language of the Ancients and conquer the Sun ourselves. They promised so.}
{209}{}{And what do they get in return?}
{210}{}{We will become servants - it is a worthy title for the tribe! We will work for the benefit of the church, and we will receive the church's help. We're not just saving ourselves, we're becoming better, smarter and stronger.}
{211}{}{Alright. Goodbye.}
{212}{}{You again? Go, I will only speak with Aaron.}