{100}{}{You see a Follower of Fire.}
{101}{}{You see one of the Followers. He whispers to himself either a prayer or some kind of nonsense.}
{102}{}{His Majesty Aaron is waiting for you.}
{103}{}{The Lord of the Phoenix is waiting for you.}

{110}{}{*Unintelligible mumbling*}
{111}{}{Do you want to join the Church of Fire?}
{112}{}{The ignorant who have not known Fire will perish in its flame.}
{113}{}{The Sacred Fire punished the ancestors for their sins.}
{114}{}{Faith in Fire is the only way to save body and soul.}
{115}{}{Greetings, brother.}
{116}{}{Did the Sacred Fire light you up too?}
{117}{}{Soon the Sacred Fire will light up all of Sonora.}
{118}{}{We all came from the same protoplasm.}
{119}{}{To be enlightened means to enlighten others.}

{1114}{}{Faith in Fire is the only way to save body and soul.}
{1115}{}{Greetings, Sister.}
{1116}{}{Did the Sacred Fire light you up too?}
{1117}{}{Soon the Sacred Fire will light up the whole of Sonora.}
{1118}{}{We all came from the same protoplasm.}
{1119}{}{To be enlightened means to enlighten others.}