{100}{}{This is Marcos.}
{101}{}{You see Marcos.}
{102}{}{This day will go down in history.}

{200}{}{What does Mathias say? Will he help us?}
{201}{}{I haven't been able to talk to him yet. Wait a little longer.}
{202}{}{Mathias promised to help. You can start the operation.}
{203}{}{Then let's get to work! Our target is Aaron and his Advisor. The rest should not be distracted.}
{204}{}{Yes!}
{205}{}{He, uh, won't help us. We'll have to do it on our own.}
{206}{}{Sorry. I thought he was with us.}
{207}{}{You know, I have that feeling too. I'll try to convince him again...}
{208}{}{I don't think you should trust him. Act without him.}
{209}{}{Mathias is dead. He won't help us.}

{210}{}{Go back to the others in the cathedral. Our target is Aaron and his Advisor. The rest should not be distracted.}
{211}{}{Good.}
{212}{}{Aaron and the Counselor died.}
{213}{}{Great news! This day will go down in history as the day of the liberation of Phoenix. Thank you, Guerrero.}
{214}{}{I hope your rule will be more just. Goodbye, Marcos.}