{100}{}{You see a Follower of Fire.}
{101}{}{Here is one of the Followers. He completely withdrew into himself because of the frantic prayer.}

{200}{}{...Heaven will become earth... Fire is God... And He said that He was pitiful before His face... Fire... The infidels will fall... The sun is in our hands... Flowers...}
{201}{}{Hey, what are you mumbling?}
{202}{}{...Fire is power...}
{203}{}{Your Fire is just a mythical image.}
{204}{}{(he is distracted from prayer and looks through you with an empty gaze) Fire... I am... really...}
{205}{}{Ah, well, that explains it all, for now.}
{206}{}{Uh, it's better not to bother him...}