{100}{}{You see a preacher.}
{101}{}{You see one of the Followers of the Holy Fire. He's diligently serving his mass.}
{102}{}{The preacher is too busy with the mass to spend his time on you.}

{110}{}{This is merely a test from the Great Atom. Everyone remain calm.}
{111}{}{I am certain that very soon, the Holy Fire will illuminate our Cathedral once again.}
{112}{}{Do not become distracted. Mere lack of light is no obstacle for us.}
{113}{}{Look at how scared you are of simple darkness. And you call yourselves believers!}

#Prayer ("A Canticle for Leibowitz" Walter M. Miller Jr., page 22)
{120}{}{...Let us begin our prayer, brothers and sisters!}
{121}{}{Let us praise the Holy Fire, for it cleansed the world to restore it anew in the form it was originally created.}
{122}{}{Of lightning and storm, Holy Fire, rid us.}
{123}{}{Of earthquakes, Holy Fire, rid us.}
{124}{}{Of plague, hunger and war, Holy Fire, rid us.}
{125}{}{Of the epicenter and the hypocenter, Holy Fire, rid us.}
{126}{}{Of cobalt rain, Holy Fire, rid us.}
{127}{}{Of strontium rain, Holy Fire, rid us.}
{128}{}{Of precipitation made of cesium, Holy Fire, rid us.}
{129}{}{Of the curse of Raditation, Holy Fire, rid us.}
{130}{}{Of the conception of monsters, Holy Fire, rid us.}
{131}{}{Of the curse of Mutation, Holy Fire, rid us.}
{132}{}{We are sinners, we ask you to hear us.}
{133}{}{Have mercy upon us, we beg of you.}
{134}{}{Forgive us, we beg of you.}
{135}{}{Help us repent, te rogamus, audi nos.}
{136}{}{...and now, for a minute of silence.}
{137}{}{. . .}