{100}{}{Here is a refugee.}
{101}{}{You see a very agitated person.}
{102}{}{We're leaving. Our foot will no longer be in this vicious city.}

{110}{}{We have to leave.}
{111}{}{There is no other way.}
{112}{}{It's better to go south.}
{113}{}{Where are the others?}
{114}{}{We will not cross the desert.}
{115}{}{Walking through the desert is certain death.}
{116}{}{If not to the south, then where?}
{117}{}{Maybe we'll go to the mountains in the west?}
{118}{}{There were rumors about a Vault, but where is it?}
{119}{}{It's time to leave.}

{200}{}{(several people are actively discussing something in front of you)}
{201}{}{Hey, what's up?}
{202}{}{(attention shifts abruptly to you; you notice some fright and tension in your eyes) I think you know what happened. There was a great tragedy that put an end to the progress of soul and body in this city.}
{203}{}{Are you talking about the explosion of the cathedral?}
{204}{}{Sure. What will happen to Phoenix now? After all, half of the city was supported by the cathedral! We want to get out of here, find a more peaceful place to live.}
{205}{}{A sensible solution. Well, good luck in your search.}
{206}{}{Well, well, if you find something better, let me know. I'll look at you.}
{207}{}{It is doubtful that the explosion alone scared you. Were you addicted to a cult?}
{208}{}{(exchanging glances) It doesn't matter anymore... Our close relatives were members of the cult, so we occupied a special place in this city. Others looked at us with envy. But now there is no one to protect us, the townspeople have turned against the cult. If we stay, the city will not forgive this.}
{209}{}{It looks like you really don't have a choice. Good luck on the way.}
{210}{}{Well, that's right. Get out of Phoenix, you arrogant bastards.}