{100}{}{You see Marcos.}
{101}{}{You see Marcos.}
{102}{}{This day will go down in history.}

{200}{}{What does Mathias say? Will he help us?}
{201}{}{I haven't talked to him yet.}
{202}{}{Mathias promised to help. We can begin the operation.}
{203}{}{Then let's get to work!}
{204}{}{Yes!}
{205}{}{He, uhh, won't be helping us. We'll have to do this on our own.}
{206}{}{A shame. I thought he was on our side.}
{207}{}{You know, I feel the same. I should try convincing him again...}
{208}{}{You know, I don't feel he's to be trusted. Let's do this without him.}
{209}{}{Mathias is dead. He won't be helping us.}

{210}{}{Aaron and his Advisor are our targets. We shouldn't waste effort on the others.}
{211}{}{Good.}
{212}{}{Aaron and the Advisor have died.}
{213}{}{Great news! This day will be remembered as the day Phoenix was liberated. Thank you.}
{214}{}{I hope your rule will be more just. Goodbye, Marcos.}