{100}{}{You see a Follower of Fire.}
{101}{}{Here is one of the Followers. He whispers to himself either a prayer or some kind of nonsense.}

{200}{}{Greetings, stranger.}
{1200}{}{Greetings, stranger.}
{201}{}{Greetings, brother.}
{1201}{}{Greetings, Sister.}
{202}{}{Goodbye.}
{203}{}{May the Sacred Fire enlighten you.}
{204}{}{Eh, yes, of course.}

{210}{}{How did you become a Follower?}
{211}{}{I was as worthless a creature as the people of the wasteland-I cared only about survival and had no idea about the Sacred Fire. Having sunk to the bottom and being persecuted, I was looking for solace and one day came across this temple. I was Vaulted here and given a purpose in life.}
{212}{}{What did faith give you?}
{213}{}{The church cares about its followers. We get medical care, education and, of course, protection from enemies.}
{214}{}{And others? Those who do not enter the church?}
{215}{}{We don't have that many resources to provide for outsiders. Therefore, you have to be selective and careful in choosing friends.}
{216}{}{What do you do in the cathedral?}
{217}{}{While I study our doctrine and pray to the Sacred Fire. But when I am ready, a great journey to other lands awaits me. I will preach the teachings of the Sacred Fire so that our faith will be strengthened in these fallen lands.}
{218}{}{Who's in charge here?}
{219}{}{There are no main ones here. But our guide is Aaron, the Lord of the Phoenix. It is located in the throne room on the top floor of the Cathedral.}
{220}{}{They say that one of the monks is closely connected with the red cardinals. What do you know about it?}
{221}{}{This is not excluded. We are ready to carry the Word of the Atom even to the most fallen souls.}
{222}{}{How can I find out the agent?}
{223}{}{Do you think I'll say his name? No, and I don't know him. But all the "agent" correspondence is kept by the radio operator. Few people are allowed to access such information.}
{224}{}{Clearly. Thank you.}
{225}{}{Orris had almost figured him out! If you don't help, your brother will die.}
{226}{}{I can't get involved in this. Sorry.}
{227}{}{Clearly...}
{228}{}{Is it that bad? Then tell Murphy about it. He knows what to do.}
{229}{}{So it was Murphy? Thank you, that's all I needed.}