{100}{}{You see a child.}
{101}{}{You see an ordinary city child in rags.}
{102}{}{Uh, I have to go.}

{200}{}{Excuse me, sir!}
{1200}{}{Sorry, ma'am!}
{201}{}{I don't serve beggars. Get lost.}
{202}{}{What do you want, youngster?}
{203}{}{I was asked to give this to you. (holds out a note)}
{204}{}{If this is some kind of deception, you will pay cruelly for it.}
{205}{}{Thank you, child, that's very kind of you.}
{206}{}{Give it here.}
{207}{}{(After passing the note, the child immediately runs away. You unfold a piece of paper, it says: "The sectarians got what they deserved. Stop your investigation, otherwise the same fate awaits you.")}
{208}{}{If that youngster wrote it, then it remains to tremble with fear.}
{209}{}{It seems that not ordinary bandits are behind the attacks.}