{100}{}{You see the delegate.}
{101}{}{You see an outsider to the cult. Among the walls of the Cathedral, he looks like a real savage.}

{200}{}{Hey, you. Bring me these fruits of yours, I'm hungry.}
{201}{}{Why would I bring you food?}
{202}{}{Ah, so you're not a Follower? Then fuck off, I don't care about you. Only the Church of Fire is worthy of my reverence. They are the future of these lands, the rest are just garbage.}
{203}{}{And who are you?}
{204}{}{I am the chief of the Eastern tribe. We form an alliance with Followers and want to become part of this great nation.}
{205}{}{An alliance of cult and savages? Why does the church need this?}
{206}{}{The church cares about people from the wastelands. Is this your first time in this city? Look how many benefits the Church of the Sacred Fire has brought to these lands. The followers conquered the Sun and imprisoned it in sticks and lamps, isn't this an indicator of their greatness, their divine power?}
{207}{}{Do you understand anything of their teachings?}
{208}{}{Not much, to be honest. But the Followers promised to teach. They will open their temple in our valley, teach you to understand the language of the Ancients, and even conquer the Sun. Well, that's what they promised.}
{209}{}{And in return?}
{210}{}{We will become ministers - this is an honorary title for the tribe! We will work for the good of the church, and the church will help us. This way we will not only save ourselves but also become better, smarter, and stronger.}
{211}{}{I see. Well, bye.}
{212}{}{You again? Go away, I'll only talk to Aaron.}