{100}{}{You see the preacher.}
{101}{}{Here is one of the Followers of Fire. He diligently serves his next mass.}
{102}{}{The preacher is too busy with mass to be distracted by you.}

{110}{}{This is the test of the Great Atom. Everyone stay calm.}
{111}{}{I am sure that soon the Sacred Fire will light up our cathedral again.}
{112}{}{Do not be distracted from the service. Darkness is not a hindrance to us.}
{113}{}{Look, they were afraid of some kind of darkness. And you call yourself believers!}

#Prayer (see "Hymn to Leibowitz" by W. Miller, page 22)
{120}{}{...Let's start the prayer, brothers and sisters!}
{121}{}{Let us praise the Sacred Fire, for it has purified the world in order to revive it in its original form.}
{122}{}{From the lightning and from the storm, Holy Fire, deliver us.}
{123}{}{From the earthquake, Holy Fire, deliver us.}
{124}{}{From plague, famine and wars, Holy Fire, deliver us.}
{125}{}{From the epicenter and hypocenter, Holy Fire, deliver us.}
{126}{}{From the rain of cobalt, Holy Fire, deliver us.}
{127}{}{From the rain of strontium, Holy Fire, deliver us.}
{128}{}{From the precipitation of caesium, Holy Fire, deliver us.}
{129}{}{From the curse of Radiation, Holy Fire, deliver us.}
{130}{}{From the conception of monsters, Holy Fire, deliver us.}
{131}{}{From the curse of Mutation, Holy Fire, deliver us.}
{132}{}{Sinners, we pray You, hear us.}
{133}{}{Have mercy on us, we pray you.}
{134}{}{Forgive us, we beg you.}
{135}{}{Help us to repent, te rogamus, audi nos.}
{136}{}{...And now a minute of silence.}
{137}{}{. . .}