{100}{}{You see Mathias.}
{101}{}{Here is one of the Followers. He seems to have gone deep into himself.}
{102}{}{Act, novice.}
{103}{}{This man is rapidly saying prayers for the salvation of all mankind.}
{104}{}{. . .}
{105}{}{Now the church will return to its original mission. I will be eternally grateful to you.}
{106}{}{So, the operation failed? But this is not the end. For the good of the whole city, we need to kill Aaron and his Adviser.}
{107}{}{So, the operation failed? But this is not the end. For the good of the whole city, we need to kill Aaron.}
{108}{}{So, the operation failed? But this is not the end. For the good of the whole city, you need to kill the Adviser.}

{200}{}{How dare you distract me from my prayer? Go away.}
{201}{}{Uh...}

#Questaions
{210}{}{Please do not distract me from prayer.}
{211}{}{Whatever you say.}
{212}{}{Who are you?}
{213}{}{I'm Mathias. Now come out and close the door.}
{214}{}{But...}
{215}{}{What are you doing here, Mathias?}
{216}{}{I'm talking to you right now. And thus I'm wasting my time. Get out.}
{217}{}{Wait...}
{218}{}{It's not like you're focusing on your prayer.}
{219}{}{Urh... If someone didn't interfere with my meditation, it would be easier.}
{220}{}{So prayer or meditation? You seem confused.}
{221}{}{Hmm. Your persistence is like the persistence of a louse in an old cassock. What do you need?}
{222}{}{I want to talk.}
{223}{}{Nothing, nothing anymore.}

{230}{}{It's stupid. If you need answers, go to the preachers in the auditorium on the first floor.}
{231}{}{I will do that. Goodbye.}
{232}{}{Absolutely, Brother Mathias. Sorry to bother you.}
{233}{}{Where should I turn to find a mentor?}
{234}{}{Obviously, you don't need it.}
{235}{}{Before you ask yourself this questaion, think about whether you need it.}

#Rebel Questa
{250}{}{I came on behalf of Marcos.}
{1250}{}{I came on behalf of Marcos.}
{251}{}{Marcos... Who is this?}
{252}{}{How, he was supposed to contact you?}
{253}{}{Your uncertainty is like an atomic moan in the belly of a mushroom cloud. Go away and come back only when you organize your thoughts.}
{254}{}{Uh, okay...}
{255}{}{You know who I mean. The one who sits in the subway and wants the same revenge with you.}
{256}{}{Yes, of course... Revenge... The base feeling of atomic beings dragging out a miserable existence. Don't you dare compare me to you, the inhabitants of the fetid sewers. My whole being is oppressed only by the thought of what Aaron did to the church of the Sacred Fire.}
{257}{}{So are you against his policy?}
{258}{}{We don't care about your motives. The main thing is that we have one goal.}
{259}{}{Previously, the church carried the light of pre-war wisdom into this ruined world. We did not participate in any bloodshed, our banner was not a symbol of tyranny. But Aaron sold his soul to the devil. I can't take it anymore.}
{260}{}{Good. What can we do to eliminate it?}
{261}{}{Eliminating Aaron is not the main thing. After all, the church is now much bigger than it seems. We are connected with other forces in Arizona, our banner directs entire settlements on a new path. You can't just eliminate one person to stop the whole process.}
{262}{}{What do you suggesta, Prior Mathias?}
{263}{}{We have to destaroy the whole church. It sounds crazy. But there is such a possibility. There are underground levels under the cathedral, where scientists have been creating new weapons for several years. It's capable of destaroying this whole cathedral.}
{264}{}{Such a powerful weapon sounds incredible. But won't it hurt the resta of the city?}
{265}{}{The Church has already done a lot of damage to this fragile world. Don't worry, the city will remain intact.}
{266}{}{Why don't you do it?}
{267}{}{I am forbidden to go down without a good reason after I have already tried to do it once. But you have the advantage of surprise.}
{268}{}{The idea is probably not the worst, but I would like to survive at the same time.}
{269}{}{Find the fuses in the professor's office. After activating them, you will have a few minutes to escape from the cathedral.}
{270}{}{Well good. But how do I get in there? This is a closed zone.}
{271}{}{I will give you the key and the mantle of a Follower. Introduce yourself to the guards as a novice who was sent with a report to the professor.}
{272}{}{Give me the key and the robe. I'm going there immediately.}
{273}{}{May the Sacred Fire forgive us. Amen.}
{274}{}{Eh, as you say, Prior. Goodbye.}

{275}{}{Aaron and his Advisor are well protected, but you will have enough strength if you act quickly and decisively. It is necessary to catch them by surprise in different parts of the cathedral so that they cannot unite. I will make sure that peaceful monks do not interfere with your battle.}
{276}{}{Great. I'll give the signal to advance. In the meantime, warn the monks.}
{277}{}{But is it possible to do without bloodshed?}
{278}{}{Alas, Aaron and his allies will not yield without a fight. But there is another option. There are underground levels under the cathedral, where the Adviser has been creating new weapons for several years. It is capable of destaroying this whole cathedral.}
{279}{}{It's kind of stupid. We'll just take over the church. I'll give the signal to advance. In the meantime, warn the monks.}
{280}{}{It's a crazy plan. But that's what I like about him.}
{281}{}{You are the last hope for peace. I will give you the key to the basement where the Adviser is located, and I will give a signal to my like-minded people so that they do not interfere with you. Act.}
{282}{}{Great.}

#Aaron's Questa
{300}{}{I think we have something to discuss. This concerns the recent attacks on monks.}
{301}{}{Obviously, your search has reached a dead end if you talk about it with the first person you meet.}
{302}{}{To be honesta, it is. Can you give me some advice?}
{303}{}{Don't despair. And watch yourself. Not only novices can become victims. But also those who hinder our enemies.}
{304}{}{No help from you.}
{305}{}{Uh, thanks for the "advice".}

{310}{}{In front of. From the notes in the library, it becomes clear that you followed the novices' routine.}
{311}{}{Of course. As one of the caretakers of the temple, I have access to this information. And if you don't want to be burned at a heretical bonfire, then I advise you to find something more weighty in my address. Now disappear.}
{312}{}{Not so fast. I also know that you sent encrypted messages through the radio station.}
{313}{}{But...}
{314}{}{Actually, there's a lead. You were sending encrypted radio messages. To whom and why?}
{315}{}{As the caretaker of the temple, I cannot allow outsiders to hear my negotiations. But where did YOU get access to the radio station? This raises great suspicions.}
{316}{}{You should be concerned about the library records right now. You obviously followed the novices.}
{317}{}{It's not what you think...}
{318}{}{I can convince Aaron to do a full search of your belongings and contacts. What do you say to that?}
{319}{}{You're trying my patience, nuclear worm. Get out.}
{320}{}{It's worse for you.}
{321}{}{Oh, good heavens! You've only recently been in this temple, and you're already digging deeper than the prophets of Vault-Tech.}
{322}{}{Volt... What?}
{323}{}{So you admit that you leaked information to the enemies of the church?}
{324}{}{Do not disturb the peace of these bedrooms. If you need answers to questaions, I'll give them in a safer place. Meet me in the confessional on the ground floor. Don't worry, my legs haven't had to run for a long time.}
{325}{}{Good. But don't try to do some kind of trick.}
{326}{}{Of course, the walls can have ears.}

#Dialogue in the confessional
{330}{}{I have to say, I didn't expect a newcomer from the wasteland to be able to unravel this case. I managed to hide my actions even from Aaron. But you...}
{331}{}{But why do you, a servant of Aaron, help his enemies?}
{332}{}{Under Aaron's leadership, the church changed its beliefs. The stronghold of holiness and wisdom has become a receptacle of sin. I can't look at it anymore.}
{333}{}{Tell this story.}
{334}{}{A dozen years ago we were a peaceful church away from people. We kept pre-war relics and knowledge to pass them on to those who would be worthy to receive them.}
{335}{}{Apparently, such a person was found?}
{336}{}{People came from the south. They lured our priors to their side and with the help of the church staged a revolution in the city. Aaron became the Lord of the Phoenix, although before that he was only a mid-level cleric.}
{337}{}{And that doesn't suit you?}
{338}{}{Our mission was to protect ancient knowledge. We should have been more attentive to those whom we let near them. We made a terrible mistake, for which we will all end up in a Nuclear Hell.}
{339}{}{And who are the people who attack novices?}
{340}{}{Who are the people you help?}
{341}{}{It's a long story. Ever since the revolution in Phoenix, there has been a detachment of rebels who call themselves the "Liberation Party". So far, they have tried to keep a low profile in order to accumulate strength and unexpectedly overthrow Aaron. Although I do not agree with them in everything, but we had an agreement about the departure of the church from the city.}
{342}{}{Now explain why I shouldn't upset your plans?}
{1342}{}{Now explain why I shouldn't upset your plans?}
{343}{}{But why are you, the prior of the Cathedral, helping his enemies.}
{344}{}{I don't care what drives you. Just tell me, why would I leave the case open?}
{345}{}{Sooner or later, Aaron will figure out the source of the information leak. But it is not my bodily shell that worries me, but the mission of the church.}
{346}{}{Do you want to win me over to your side?}
{347}{}{To begin with, I propose to meet with the rebels and discuss everything face to face.}
{348}{}{It's stupid. I'll tell Aaron everything.}
{349}{}{In that case, you leave me no choice. May the Sacred Fire forgive us...}
{350}{}{Er...}
{351}{}{OK, I agree. It will be interestaing to hear the other side of the conflict.}
{1351}{}{OK, I agree. It will be interestaing to hear the other side of the conflict.}
{352}{}{So be it. Find the general Staff of the Party under the Union station. You can get there only through collectors. Tell them you're from me, and in the meantime I'll try to warn them. Good luck.}
{353}{}{See you, Prior Mathias.}
{354}{}{I've changed my mind. I'll tell Aaron everything.}
{1354}{}{I've changed my mind. I'll tell Aaron everything.}
{355}{}{Act, novice.}
{356}{}{Good.}
{357}{}{I need to know which of the cardinals is leaking information about the gang to you.}
{358}{}{What kind of arrogant question is that? If I knew, I wouldn't tell you.}
{359}{}{But you don't deny it, do you? }
{360}{}{We have spies all over the city. And we get information from them in a variety of ways. There is nothing surprising in this.}
{361}{}{I have no more questions.}
{362}{}{I can trust you, can't I? Murphy is one of us. He infiltrated the ranks of the gang to direct these poor unreasonable people to the righteous side.}
{363}{}{It's very good that you warned me. Thank you.}