{100}{}{You see an old acquaintance.}
{101}{}{This is one of the Followers of Fire... since recently.}

{200}{}{(In front of you is your old acquaintance who spied on the rangers; he seems depressed and weak-willed, his gaze has dimmed, and his former gangster manners seem to be in the past)}
{201}{}{Well, wow, what a meeting ...}
{202}{}{ (cloudy eyes rise heavily and barely distinguish you) You... I remember you. The Sacred Fire must have brought us together that day. Thanks to you, I am here among the Followers. Thank you.}
{203}{}{Uh, please. It's nice to participate in someone's personal growth.}
{204}{}{I thought you wouldn't survive this journey. Oh well.}

{210}{}{I have to pray. Please leave me alone.}
{211}{}{Bye.}

{220}{}{How did you manage to overcome the path from Parker Dam?}
{221}{}{Don't ask me about such nonsense. Now I'm above that.}
{222}{}{Then stay alone with your own... prayers.}
{223}{}{What is it like to be a novice in the Temple of Fire?}
{224}{}{Work and prayers. That's all we need. Until I'm ready for something more important. And only my mentor can determine that.}
{225}{}{Hmm, let me take a look at your pupils.}
{226}{}{What is it? Stupid jokes of a villager?}
{227}{}{Yeah, uh, sort of.}
{228}{}{Looks like they're drugging you here, huh?}
{229}{}{Well... We are given a couple of relaxing pills at lunch, this is part of the dedication. We have to clear our minds of arrogance, that's what the monks say... Ugh... I think I need to go to the toilet...}
{230}{}{Uh, it's better to leave you.}