{100}{}{You see a Follower of the Holy Fire.}
{101}{}{You see one of the Followers. He's whispering either a prayer or total nonsense.}

{200}{}{Greetings, stranger.}
{1200}{}{Greetings, stranger.}
{201}{}{Greetings, brother.}
{1201}{}{Greetings, sister.}
{202}{}{Goodbye.}
{203}{}{May the Holy Fire illuminate your mind.}
{204}{}{Uhh, yes, of course.}

{210}{}{How did you become a Follower?}
{211}{}{I was once as pathetic a creature as any other inhabitants of the Wasteland - I cared for nothing more than survival and knew nothing about the Holy Fire. Having ended up at the bottom and persecuted, I was looking for solace and ended up stumbling upon this temple. Here, I was given shelter and purpose.}
{212}{}{What has your faith given you?}
{213}{}{The church cares about the wellbeing of it's followers. We receive medical care, education and protection from any enemies.}
{214}{}{What about the others? Those not members of the church?}
{215}{}{We do not have enough resources to provide these things to outsiders. This is why we have to be careful and selective in our choice of friends.}
{216}{}{What is it you do here?}
{217}{}{For now, I'm studying our doctrine and worshipping the Holy Fire. But when I will be ready, a great journey to far-off lands awaits me. I shall spread the teachings of the Holy Fire so that our faith grows stronger in these fallen lands.}
{218}{}{Who is the leader here?}
{219}{}{There is no leader here. But there is a man who guides us - Aaron, Overlord of Phoenix. He is located in the throne room on the top floor of the Cathedral.}
{220}{}{They say some of the monks are closely involved with the Red Cardinals. What do you know about this?}
{221}{}{It is not out of the question. We are ready to carry the Word of the Atom even to souls as fallen as those.}
{222}{}{How would one recognize the agent?}
{223}{}{You think I will tell you their name? Even if I knew, you would never get it out of me. But all "undercover" correspondence is archived by the radio operator. Not many have access to such information.}
{224}{}{Got it. Thanks.}
{225}{}{Orris almost found him! If you don't help, your fellow follower could die.}
{226}{}{I cannot get involved in this. Sorry.}
{227}{}{Alright...}
{228}{}{It it so bad? Then tell Murphy about this. He will know what to do.}
{229}{}{So it was Murphy all along? Thanks, that's all I needed to know.}