{100}{}{You see brother Francis.}
{101}{}{You see one of the Followers of the Holy Fire. He is busy copying ancient blueprints.}
{102}{}{How will I copy blueprints in this darkness?}

{200}{}{Greetings, stranger. Can I help you in your search?}
{1200}{}{Greetings, stranger. Can I help you in your search?}
{201}{}{First, tell me about this place.}
{202}{}{Very much doubt it. HOW can you help me?}
{203}{}{Please leave. This is no place for rude behavior.}
{204}{}{Sorry, I got up on the wrong foot today. So, what is this place?}
{205}{}{Oh I'll leave. But you'll hear more about me.}

{210}{}{What do you need, stranger?}
{1210}{}{What do you need, stranger?}
{211}{}{How can I help you, novice?}
{1211}{}{How can I help you, novice?}
{212}{}{Goodbye.}
{213}{}{You must know much. Could you tell me about something else?}

#Questions
{220}{}{Tell me about yourself.}
{221}{}{My name is Francis, I am a keeper of books.}
{222}{}{How did you become a follower?}
{223}{}{I was a follower from my youth. By that time the church was not well-known and did not get involved with the city.}
{224}{}{And you blindly believe the dogmas of your church?}
{225}{}{"Nisi videro, non credam. Non credam, nisi videro". There is no point discussing this any further.}
{226}{}{And what is it exactly you do here, keeper of books?}
{227}{}{I restore old books, copy ancient writings, make lists. Right now I am busy with this great blueprint.}
{228}{}{What is the purpose of copying ancient writings?}
{229}{}{We must save the knowledge of our incredibly wise ancestors for our descendants. But the paper on which they were written is almost completely decayed. These texts won't survive for long, especially out in the open air. This is why we restore, copy and then conserve ancient writings.}
{230}{}{But if you conserve them, they become inaccessible, correct?}
{231}{}{Correct. This is why we make copies that are stored in our library. They are not as good as the original sometimes, but that is a complex topic.}

{240}{}{What is this place?}
{241}{}{This is a library. This is a place where knowledge is stored in paper form... mostly Pre-War knowledge. I understand that this looks a bit strange, after all, there is not a single library left in the world except this one. But this only serves to make what we do more important.}
{242}{}{Where are all these books coming from?}
{243}{}{From everywhere. We buy all Pre-War books and writings we can. A part of this collection we got from our ancestors, who buried them in the desert.}
{244}{}{But why do you need these old books?}
{245}{}{They contain the knowledge of our predecessors. Unfortunately, we are not able to interpret a large part of it. But one day that time will come, and the secrets contained in these books will be revealed.}
{246}{}{Do you think this knowledge is safe? Have our predecessors not destroyed themselves by using this same knowledge?}
{247}{}{It is true. But people learn from past mistakes. Besides, we only share knowledge with those who are worthy of it.}
{248}{}{Buried in the desert? How?}
{249}{}{After the Great War, scientists were treated much less respectfully. It was thought that they were the ones that brought forth the Apocalypse, and scientific writings were burned. At least, so do the records say. Our ancestors hid these books in barrels and buried those barrels in the desert. We are still yet to find many of them.}

{250}{}{About this blueprint. Tell me, what does "transformer unit 6-B" mean?}
{251}{}{Well... it's... the name of the document, that's obvious.}
{252}{}{That I understand. But WHAT does it mean?}
{253}{}{It's the *name* of the drawing that you are looking at. What does your name mean?}
{254}{}{Nothing, I think.}
{255}{}{Same thing here.}
{256}{}{Alright. Looks like this is a pointless conversation.}
{257}{}{Almost nothing, I think. But what does the drawing symbolize, brother Francis?}
{258}{}{It... symbolizes... (rotates blueprint and reads name) transformer unit 6-Â.}
{259}{}{I see, brother Francis. I see.}

#Study the books
{260}{}{You truly have a fine collection. Could I study these books?}
{261}{}{I'm afraid we are very careful with who to give access to our library. These books are very valuable, and the knowledge in them could be dangerous for commoners.}
{262}{}{Fine, forget it.}
{263}{}{In my opinion, you're just a bunch of morons. Bye.}
{264}{}{Are you really going to refuse a brother-in-faith?}
{1264}{}{Are you really going to refuse a sister-in-faith?}
{265}{}{Oh, I did not know you were considered a novice. Of course, take any of the books, but be careful, they're quite fragile.}
{266}{}{Thank you, brother Francis. I will be very careful.}
{1266}{}{Thank you, brother Francis. I will be very careful.}
{267}{}{Can't promise you anything.}
{268}{}{I could make a donation of 300 caps to the library.}
{269}{}{Well, this changes things. You can study our books, but be careful, they're quite fragile.}
{270}{}{}
{271}{}{Well, this changes things.}
{272}{}{Sorry, I don't have this many caps yet. I'll be back.}
{273}{}{Even after helping I still should not expect to be trusted?}
{274}{}{Oh, it's true that you helped. Study our books, but be careful, they're quite fragile.}

#Aaron's quest
{280}{}{Brother Francis, is it you who has the novice mission schedule?}
{281}{}{Yes. But I will, of course, not show these scrolls to you. Only a few select people have access to them. Why do you need them?}
{282}{}{I'm really not at liberty to say. Can you tell me who examined them lately?}
{283}{}{Hm. These documents are quite rarely used. I suppose I could use the stamps of the visitors. But tell me the dates you are interested in.}
{284}{}{I'm interested in these days...}
{285}{}{...Well, it looks like during those days only prior Mathias could have been examining the documents.}
{286}{}{Where can I find him?}
{287}{}{His chambers are higher up the corridor. But be quiet, brother Mathias is quite nervous when he is suddenly distracted from meditation.}
{288}{}{Thank you, brother Francis, you have helped me greatly.}
{289}{}{Alright. I'll leave you alone with those papers.}

#Books
{300}{}{You told me about buying books. And I travel a lot.}
{301}{}{Of course. If you find old books, bring them to me. The church will generously reward your efforts.}
{302}{}{I'll keep that in mind.}
{303}{}{You do need new books?}
{304}{}{I have intact books.}
{305}{}{Very good. How many books can you donate to the library?}
{306}{}{Looks like this is not exactly what you were looking for. Sorry for the disturbance.}
{307}{}{I wanted to say that I'll come look for intact books. Goodbye.}
{308}{}{All the books I have.}
{309}{}{Just one.}
{310}{}{Two books.}
{311}{}{Three books.}
{312}{}{A fine addition to our collection. You're helping the progress of all mankind. Thank you.}
{313}{}{I don't need any money. This is my donation to the church.}
{314}{}{Your generocity truly knows no bounds. Thank you.}
{315}{}{But I would like to ask about something.}
{316}{}{You're welcome. Goodbye.}
{317}{}{I'd like to receive caps.}
{318}{}{Of course, that's fair. Here is your reward - }
{319}{}{ caps.}
{320}{}{Perhaps the library needs some specific books?}
{321}{}{Oh yes. Some people simply don't want to share old knowledge. Perhaps you could manage to plough through their stupidity and convince them to change their minds?}
{322}{}{I would like to know more. Who are those selfish fools?}
{323}{}{Personally, I prefer to to talk to fools in the language of violence.}
{324}{}{I was recently told that there is a very old book in the town known as San Brahmin. And that it is far older than even the day of the Great War. Can you imagine that? Unfortunately, the locals can't read it, but they still don't let us near it due to the recent trade war.}
{325}{}{Are you proposing stealing it?}
{326}{}{I suppose this sound a bit too harsh. Understand - the local savages have no idea what the true meaning of the book is and can't ensure it's safety. This relic would bring much more good if it were in our hands. So, will you get this book? I'll pay you for it.}
{327}{}{My answer is no. I do not want to participate in the plundering of churches.}
{328}{}{Well, I understand. Forget everything I said.}
{329}{}{Of course.}
{330}{}{I think you know what to do with that thing better than they do. I'll get you that holy book.}
{331}{}{Very good. I am awaiting for you with great anticipation.}
{332}{}{I have the holy book.}
{333}{}{Oh, look at those pages! The pale whiteness of them... My god, it even has latin. It's perfect. Oof, the anticipation makes it hard for me to even breathe...}
{334}{}{If this is so important for the church, take it for free. I just want to do something good.}
{335}{}{I will pray for you, brother. The world needs more people like you.}
{1335}{}{I will pray for you, sister. The world needs more people like you.}
{336}{}{I wish you great success in your endeavors, brother Francis.}
{337}{}{It was very hard acquiring that thing. I demand 300 caps in exchange.}
{338}{}{Of course, here they are. Caps are worthless compared to such a relic.}
{339}{}{I wish you great success in your endeavors, brother Francis.}
{340}{}{Wait, brother. I think you should talk to Aaron himself. I shall tell him about the help you gave to our church. If you happen to need my recommendation, you can count on it.}
{1340}{}{Wait, sister. I think you should talk to Aaron himself. I shall tell him about the help you gave to our church. If you happen to need my recommendation, you can count on it.}
{341}{}{Good.}
{342}{}{See you.}
{343}{}{It just so happened that I have this book already.}
