{100}{}{You see a radio operator.}
{101}{}{You see one of the Followers.}
{102}{}{What happened? Did you get lost? The exit is there, outsiders can't come here.}
{1102}{}{What happened? Did you get lost? The exit is there, outsiders can't come here.}
{103}{}{Greetings, brother. May the Holy Fire illuminate you.}
{1103}{}{Greetings, sister. May the Holy Fire illuminate you.}
{104}{}{Gracious Atom... what's happening to me?}
{105}{}{I see... the Holy Fire...}
{106}{}{This is enough... Tempt me no more, please...}