{100}{}{You see a refugee.}
{101}{}{You see a very worried person.}
{102}{}{We're leaving. Our legs won't take another step towards this vicious city.}

{110}{}{We must leave.}
{111}{}{There is no other way.}
{112}{}{We better go to the south.}
{113}{}{And where are the others?}
{114}{}{We won't cross the desert.}
{115}{}{To go across the desert is certain death.}
{116}{}{If not to the south, then where?}
{117}{}{Maybe we could go to the western mountains?}
{118}{}{There were rumours of a Vault, but where is that Vault located?}
{119}{}{Time to go.}

{200}{}{(you see a group of people actively discussing something)}
{201}{}{Hey, what's going on?}
{202}{}{(suddenly, their attention becomes directed towards you; you notice a hint of fear and tension in their eyes) I think you already know. A great tragedy ocurred, one that put an end to progress for the soul and body in this city.}
{203}{}{You're talking about the destruction of the Cathedral?}
{204}{}{Of course. What will happen to Phoenix now? Half of the city was reliant on it! We want to get out of here, find a more peaceful, stable place to live.}
{205}{}{Smart move. Well, good luck in your search.}
{206}{}{Uh-uh. You find anything better, tell me.}
{207}{}{I doubt it was only the blast that scared you. Were you dependent on the cult?}
{208}{}{(exchange glances) I suppose that doesn't really matter now... But our relatives were members of the cult. We were in a special position in the city. Others looked upon us with envy. But now that there is no one to protect us, the citizenry is taking up arms against the cult. If we remain, the city won't forgive us.}
{209}{}{Looks like you really do have no choice. Good luck.}
{210}{}{Good. Get out of Phoenix, arrogant bastards.}