{100}{}{You see an adept.}
{101}{}{You see one of the Followers of Fire. He's chanting something crazy to attract attention.}

#Floating replicas
{110}{}{Fear the Sacred Fire!}
{111}{}{Fear the punishment of the Fiery Heavens!}
{112}{}{The Lord is the power in nuclear fission!}
{113}{}{All-eat, all-eat we need to repent!}
{114}{}{Who! Who dares to resist the voice of our Lord?}
{115}{}{Ske-eptics! Skeptics will fall first!}
{116}{}{These people gave their souls to the Nuclear Devil!}
{117}{}{Hearken, victims of Radiation and Devastation!}
{118}{}{They have fallen from their dirty thoughts!}
{119}{}{Honor your father Aaron, the Lord of the Phoenix, for He gives life to this desert!}
{120}{}{A new era is coming!}
{121}{}{Only a fool would resist progress!}

#The first dialog
{200}{}{Come closer, child of Radiation and Desolation. Everyone should see that justice prevails. No one will escape the punishment of heaven!}
{201}{}{Wait a minute, Venerable one, what's going on?}
{202}{}{We, the servants of the Sacred Fire, have been hiding from ordinary people for years. For their hearts and minds could not contain simple truths. We were chased away, beaten, and killed! But we waited patiently for the right hour.}
{203}{}{[Next]}
{204}{}{Hey, you freak in rags, what are you yelling at?}
{205}{}{Here it is! Intolerance! Foul language! We, the servants of the Sacred Fire, have been hiding from ordinary people for years. For their hearts and minds could not contain simple truths. We were chased away, beaten, and killed! But we waited patiently for the right hour.}
{206}{}{The hour when the Lord gets tired of human stupidity and sends us peace. These people, whose bodies have become the receptacle of the Nuclear Devil, are proof of that. They have been plotting their atrocities against the church for many years. They robbed and killed our monks, who bring light truths to the whole world. Ungrateful! They will burn in the Nuclear Flames of Hell!}
{207}{}{What a horror. These bastards got what they deserved.}
{208}{}{May the Sacred Fire be with you! Go in peace and tell the common people about the persecution of the peaceful church.}
{209}{}{Necessarily. After what I have heard, it is impossible to put up with such injustice.}
{210}{}{You don't have to make me an agitator. I'll just go about my business.}
{211}{}{So far I have heard only one side of the conflict. It will not be possible to listen to the second one.}
{212}{}{Skeptics! Have we done so little for the city? See how the Phoenix blossomed when it accepted the wisdom of Ruler Aaron. Go and think about it. And fear the Sacred Fire! Fear The Fire!}
{213}{}{I'm sorry, please, this is my first time here and I don't know a lot. I will take a closer look at your church.}
{214}{}{Man, after what I've seen, your speeches look very dubious. I will decide for myself how to treat your church.}

{220}{}{Greetings, brother. I am glad to observe your epiphany from our last meeting. I remember you were skeptical and looked at me with hostility. Now I will stretch out my hand to you and say crede firmiter et pecca fortiter.}
{1220}{}{Greetings, Sister. I am glad to observe your epiphany from our last meeting. I remember you were skeptical and looked at me with hostility. Now I will stretch out my hand to you and say crede firmiter et pecca fortiter.}
{221}{}{Greetings, brother. I am glad to see that you have been accepted into the service. It is a great honor and responsibility. Crede firmiter et pecca fortiter.}
{1221}{}{Greetings, Sister. I am glad to see that you have been accepted into the service. It is a great honor and responsibility. Crede firmiter et pecca fortiter.}
{222}{}{Now, if you don't mind, I'd like to talk to you.}
{223}{}{Crede firmi... what? I am still far from the sacred texts. See you.}

#Repeat dialog
{250}{}{I see that the talk about the Sacred Fire does not give you peace. So what do you want to know this time?}
{251}{}{And again you, the servant of the Nuclear Devil, come to test me.}
{252}{}{Greetings, brother. Are you all right? Don't the commoners bother you?}
{1252}{}{Greetings, Sister. Are you all right? Are the commoners bothering you?}
{253}{}{I think I'll go.}

{260}{}{Who are you?}
{261}{}{I would like to get to know you better.}
{262}{}{I am a priest and a humble servant of Aaron, the Lord of the Phoenix. My name is Gabriel.}
{263}{}{I doubt that's your real name.}
{264}{}{So we talked. See you later.}
{265}{}{What kind of religion do you represent, Gabriel?}
{266}{}{Right. After being accepted into the service, we change our names, thereby putting an end to our past life.}
{267}{}{}
{268}{}{By the way, could you help me in understanding our faith?}
{269}{}{After what I heard, I wanted to get to know your faith better.}
{270}{}{Tell me about the religion you represent.}
{271}{}{Can I discuss our faith with you?}
{272}{}{The Church of the Sacred Fire is located to the north of the city. Walk along the main street, the road itself will lead you to the cathedral. It is better to learn about faith in sermons than from me.}
{273}{}{And who are you?}
{274}{}{A cheap trick to lure, sectarian. You can't fool me with that.}
{275}{}{Great, I'll head straight there.}
{276}{}{Is your church so influential that you arrange public executions?}
{277}{}{No, no, the execution was carried out by other people, but under our supervision. And yet, the whole city owes a debt to the church. I am obliged for water, for electricity, for peace and order. Soon you will see it all with your own eyes, a child of Radiation and Devastation.}
{278}{}{You're singing too sweetly, old man. I'm going to see if you're lying.}
{279}{}{In that case, I just need to explore the city. Bye.}
{280}{}{Forgive my bad temper, but such questions are not discussed on the street. And you should not fill your head with skepticism, so the Nuclear Devil penetrates the souls of young monks. Fear the Sacred Fire, novice, fear the Fire!}
{281}{}{Apparently, I will have to turn to the ministers in the cathedral. See you later.}
{282}{}{And then what are you doing?}
{283}{}{By the way, what are these poor people punished for?}
{284}{}{Those guys behind you weren't afraid. Why were they executed?}
{285}{}{What are these people punished for?}
{286}{}{Fools, they succumbed to the temptations of the Nuclear Devil. Some of them spread false rumors about our church and its leader Aaron, may he be famous forever and ever. Others are punished for robbing our monks or the church itself. From now on, their souls will have no rest in the Nuclear Underworld.}
{287}{}{Don't you think it's too much... harsh punishment?}
{288}{}{They got what they deserved. Now I'll be more careful. Be.}
{289}{}{Execution on a religious basis? I'm going to get out of here before I get swept up with them.}
{290}{}{Who are you that oversees this execution?}
{291}{}{What do you know about the rebels who are fighting the church?}
{292}{}{Heretics and cowards! Ah, IF we knew the position of their headquarters, they should all burn at the punitive bonfire.}
{293}{}{Clearly. You don't know anything. I'll go ask the others.}

#Quest
{300}{}{I'm investigating the attack on the monks at Aaron's request. What can you tell us about it?}
{301}{}{Tell me again about the attacks on Followers.}
{302}{}{Followers often became victims of robberies or ridicule. When Aaron came to power, may his name be famous, any bandit in the city began to bypass us. However, the attacks have recently resumed.}
{303}{}{[Next]}
{304}{}{Shooting during the execution, murder in the slums, and an attack near the casino - these are the most audacious crimes against our brothers in recent times.}
{305}{}{Thank you, that's enough.}

{310}{}{Tell me about the shooting during the execution.}
{311}{}{They shot from the roof of these ruins when we carried out the execution. There were several shooters, they were in the crossfire and were aiming at me. Perhaps this is how the supporters of the criminals tried to save their accomplices, but by the will of the Eye of the Phoenix, they failed.}
{312}{}{Was there a shootout near the casino?}
{313}{}{Ignorant bandits shot our brothers near the casino like some pig rats on a ranch. It's hard to say what happened because people talk about different things.}
{314}{}{And what kind of incident in the slums?}
{315}{}{A very dark matter. Our novices came to the slums to praise Aaron and ask for donations to the temple. They were soon found hanging from lampposts. Of course, the locals don't want to say that no one saw anything. So let us pray for the souls of our brothers.}
{316}{}{Do you have any leads on these attacks?}
{317}{}{Do you think Aaron himself would have given you this case if it wasn't so dark? Ask people in casinos and slums, maybe they will be more trusting of you. After all, many Followers are known by sight, and you are a new person.}