{100}{}{You see Brother Francis.}
{101}{}{Here is one of the Followers. He's busy copying ancient blueprints.}
{102}{}{How am I going to copy the blueprints in such darkness?}

{200}{}{Greetings, stranger. Can I help you in your search?}
{1200}{}{Greetings, stranger. Can I help in your search?}
{201}{}{First, tell me about this place.}
{202}{}{I doubt it very much. WHAT can you do for me?}
{203}{}{Please go away. There is no place for rudeness here.}
{204}{}{I'm sorry, I'm not in a good mood today. So what is this place?}
{205}{}{I'll leave. But you'll hear from me again.}

{210}{}{What do you need, stranger?}
{1210}{}{What do you need, stranger?}
{211}{}{How can I help you, novice?}
{1211}{}{How can I help you, novice?}
{212}{}{Goodbye.}
{213}{}{You know a lot. Tell me something else?}

#Questions
{220}{}{Tell me about yourself.}
{221}{}{My name is Francis, I am a book keeper.}
{222}{}{How did you become a follower?}
{223}{}{I've been a follower since I was a teenager. Then the church was little known and did not participate in the fate of the city.}
{224}{}{And you blindly believe in the dogmas of your church?}
{225}{}{"Nisi videro, non credam. Non credam, nisi videro". There is no point in discussing this.}
{226}{}{And what exactly are you doing, bookkeeper?}
{227}{}{I restore old books, copy old writings, make lists. For example, I am currently busy with this magnificent drawing.}
{228}{}{Why copy old writing?}
{229}{}{We must preserve for posterity the knowledge of our infinitely wise ancestors. But the paper of the old writings has almost decayed, such texts will not live long, especially in the fresh air. Therefore, we restore, copy and then preserve the old scriptures.}
{230}{}{But if they are preserved, they will become inaccessible, right?}
{231}{}{Right. And that's why we make copies that are stored in our library. True, they are often inferior in quality to the original, but this is a difficult question.}

{240}{}{What is this place?}
{241}{}{This is a library. A place where paper sources of knowledge are stored... mostly pre-war. I understand that this looks a little strange, because there is not a single library left in the world anymore. But our work is all the more valuable.}
{242}{}{Where did all these books come from?}
{243}{}{From everywhere. We buy up all pre-war books and manuscripts. Part of this collection came to us from our predecessors, who buried them in the desert.}
{244}{}{But why do we need old books?}
{245}{}{They keep the knowledge of our ancestors. Unfortunately, we are not able to understand most of them. But someday the time will come, and these books will reveal their secrets.}
{246}{}{Do you think this knowledge is safe? Didn't the ancestors ruin themselves with their help?}
{247}{}{Right. But people learn from old mistakes. Besides, we share knowledge only with those who are worthy of it.}
{248}{}{Buried in the desert? How is that?}
{249}{}{After the Great War, scientists were treated with great disrespect. They were considered the culprits of the Apocalypse, and scientific books were burned at the stake. At least, that's what the chronicles say. Then our predecessors hid the books in barrels and buried them in the desert. We still haven't found many of them.}

{250}{}{About the drawing. Tell me, what does "transformer unit 6-B" mean?}
{251}{}{This is... well... the name of the document, obviously.}
{252}{}{I understand that. But WHAT does it mean?}
{253}{}{This is the *name* of the drawing you're looking at. And what does your name mean?}
{254}{}{I think nothing.}
{255}{}{That's it.}
{256}{}{Clearly. It seems like this is a meaningless conversation.}
{257}{}{I think almost nothing. But what does the drawing symbolize, Brother Francis?}
{258}{}{He... symbolizes ... (turns over the drawing and reads the inscription) transformer unit 6-In.}
{259}{}{It's all clear, Brother Francis. It's all clear to me now.}

#Study books
{260}{}{You really have a huge collection. Can I study these books?}
{261}{}{I'm sorry, but we are very careful about admitting to our library. These books are too valuable, and their knowledge can be dangerous for ordinary people.}
{262}{}{Okay, forget it.}
{263}{}{I think you're just idiots. Bye.}
{264}{}{Will you really refuse me, a brother in faith?}
{1264}{}{Will you really refuse me, a sister in faith?}
{265}{}{Oh, I didn't know that you were ordained a novice. Of course, take any books, but be careful, they are very fragile.}
{266}{}{Thank you, Brother Francis. I will be extremely careful.}
{1266}{}{Thank you, Brother Francis. I will be extremely careful.}
{267}{}{I can't promise anything.}
{268}{}{I can make a donation to the library in the amount of 300 caps.}
{269}{}{Well, that changes things. You can study our books, but be careful, they are very fragile.}
{270}{}{}
{271}{}{Well, that changes things.}
{272}{}{I don't have that many bottlecaps right now. I'll come back later.}
{273}{}{Even after help, I can't count on trust?}
{274}{}{Oh, of course it's true. Study the books, but be careful, they are very fragile.}

#Aaron's Quest
{280}{}{Brother Francis, do you keep the novices' mission schedule?}
{281}{}{Yes. But I won't show you these scrolls, of course. Only a few ministers have access to them. Why do you need them?}
{282}{}{I can't talk about it. Can you tell me who has been studying them lately?}
{283}{}{Hmm. These documents are used quite rarely. I think I can match it with the seals of the visitors. But name the dates you need.}
{284}{}{I am interested in these days...}
{285}{}{...Well, apparently, in those days only Prior Mathias could study the documents.}
{286}{}{Where can I find him?}
{287}{}{His chambers are up the corridor. But be quiet, Brother Mathias is very nervous when he is sharply distracted from meditation.}
{288}{}{Thank you, Brother Francis, you helped me a lot.}
{289}{}{Clear. I'll leave you alone with these papers.}

#Books
{300}{}{You were talking about buying books. And I travel a lot.}
{301}{}{Sure. If you find old books, bring them to me. The Church will generously pay for your labors.}
{302}{}{I will keep in mind.}
{303}{}{Don't you need new books?}
{304}{}{I have the surviving books.}
{305}{}{Very good. How many books can you donate to the library?}
{306}{}{It doesn't seem to be exactly what you need. Sorry to bother you.}
{307}{}{I mean, I'm going to look for books. Goodbye.}
{308}{}{All the books I have.}
{309}{}{Just one.}
{310}{}{Two books.}
{311}{}{Three books.}
{312}{}{An excellent addition. You are helping the progress of all mankind. Thanks a lot.}
{313}{}{Take it for free. This is my donation to the church.}
{314}{}{Truly, your generosity knows no bounds. Thank you.}
{315}{}{But I would like to ask you something.}
{316}{}{You are welcome. Goodbye.}
{317}{}{I want to get caps for this.}
{318}{}{Sure. That's fair. Here's your reward - }
{319}{}{ caps.}
{320}{}{Maybe the library needs some specific books?}
{321}{}{Oh, yes. Some people don't want to share old knowledge. Perhaps you can get through their stupidity?}
{322}{}{Tell me more. Who is this greedy miser?}
{323}{}{I have a short conversation with fools. The first - in the snout, the second - in the groin.}
{324}{}{Recently I was informed that a very ancient book is kept in the town of San Brahmin. And it is much older than the day of the Great War. Can you imagine? Unfortunately, the locals can't read it, but they don't let us near it either because of the recent trade war.}
{325}{}{Are you suggesting we steal her?}
{326}{}{I guess that sounds a bit rude. But get it right. The local savages do not understand the true meaning of this book and cannot ensure its safe preservation. In our hands, this relic will do more good. So will you get this book? I'll pay for it.}
{327}{}{My answer is no. I don't want to participate in the looting of any churches.}
{328}{}{Well, I understand. Forget everything you've heard here.}
{329}{}{Of course.}
{330}{}{I think you know better what to do with such junk. I'll get you the holy book.}
{331}{}{Very good. I'm looking forward to it.}
{332}{}{I have the holy Book.}
{333}{}{Oh, these pages are beautiful! God, there's even Latin here. Ugh, it takes my breath away with anticipation...}
{334}{}{If it's so important to the church, then take it for free. I just want to do something good.}
{335}{}{I will pray for you, my brother. The world lacks people like you.}
{1335}{}{I will pray for you, Sister. The world lacks people like you.}
{336}{}{Good luck, Brother Francis.}
{337}{}{It was very difficult to get this thing. I demand 300 caps in return.}
{338}{}{Of course, here are the bottlecaps. It's not a pity for this relic of caps.}
{339}{}{Good luck, Brother Francis.}
{340}{}{Wait, brother. I think you should talk to Aaron himself. I will inform him about the help you have given to our church. And if you need my recommendation, you can count on it.}
{1340}{}{Wait, Sister. I think you should talk to Aaron himself. I'll let him know about the help you've given our church. And if you need my recommendation, you can count on it.}
{341}{}{OK.}
{342}{}{See you later.}
{343}{}{It so happened that I already have this book.}