{100}{}{You see a person.}
{101}{}{This person is wandering around aimlessly.}
{102}{}{This person is chanting something vaguely positive about the church.}
{103}{}{This goner can barely move around.}
{104}{}{This refugee is wandering around aimlessly.}

#Floating dialogue
#- poor
{110}{}{Don't bother me.}
{111}{}{I don't know what to do.}
{112}{}{There is no future in this city for people like me.}
{113}{}{I'll just lie down here... are you okay with that?}
{114}{}{I want to leave this street life behind, but I can't.}
{115}{}{Phoenix may be prospering, but my situation is getting worse and worse.}
{116}{}{Hey, do you have some food you could share with your fellow man living on the streets?}
{117}{}{Could I borrow a couple of caps? I'll give them back, I promise.}
{118}{}{I really need medicine for my kid. Help me out, eh?}
{119}{}{I'm starving, give me a rat's tail at the very least.}
{120}{}{Want to join me? Sorry, this place can't fit so many people.}
{121}{}{I'm waiting for the fanatics to give us free food.}
{122}{}{Those in the cathedral sometimes give us leftovers after lunch.}
{123}{}{We have to kiss the priest's legs when they give us the food.}
{124}{}{Glory to the Fire! All humans are brothers! See, I'm a believer too.}

#- adept
{130}{}{I want to become a novice, but they are not accepting me.}
{131}{}{I'm telling you, I'll become a novice!}
{132}{}{I'll have to pray a lot to be accepted into the order.}
{133}{}{Peace! Love! Holy Fire!}
{134}{}{Do you also believe in something?}
{135}{}{What do YOU believe in?}
{136}{}{Glory to the Holy Fire!}
{137}{}{Glory to Phoenix! Glory to Aaron!}
{138}{}{I love Aaron! Glory to Aaron, the Overlord of Phoenix!}
{139}{}{My life belongs to Aaron!}

#- sick or disabled
{150}{}{I'm here to ask them to heal my ailment.}
{151}{}{There is no saving me from my illness, but the monks promised to help.}
{152}{}{They say the monks know the ancient sacrament of healing.}
{153}{}{I pray to Aaron every day so that my ulcers are healed.}
{154}{}{I gave all my savings to the church, but I haven't yet healed my illness.}
{155}{}{The monks cure me with prayers. And I feel strength coming back to me! Ow, or maybe not...}
{156}{}{The monks say my soul must be cleansed. And for that I need to give everything I have to the church.}
{157}{}{I'm that pathetic, yes?}
{158}{}{I'm only asking the followers to help me.}
{159}{}{Only the Followers of the Holy Fire can heal as well as people could before the Great War.}

#- refugee
{170}{}{I'm here to ask the Followers of the Holy Fire for refuge.}
{171}{}{I was told the church accepts refugees, but that's not true.}
{172}{}{We were running away from bandits, but the church doesn't want to accept us.}
{173}{}{The Followers of the Holy Fire help refugees.}
{174}{}{The monks here have incredibly large stomachs. Must be some kind of illness.}
{175}{}{Only near the temple do I feel safe.}
{176}{}{The Fire-worshippers are strange people.}
{177}{}{They promise heaven on earth.}
{178}{}{They say we must fear something, but I don't understand why, or who they're talking about.}
{179}{}{They better give some food, anyone can preach.}