{100}{}{You see a child.}
{101}{}{You see a regular city child covered in rags.}
{102}{}{Uhh, I have to go.}

{200}{}{Excuse me, sir!}
{1200}{}{Excuse me, ma'am!}
{201}{}{I don't help beggars. Get lost.}
{202}{}{What do you need, youngster?}
{203}{}{I was asked to bring this to you. (hands note)}
{204}{}{If this is part of some deceitful plan, you will pay for it dearly.}
{205}{}{Thanks, kid. That's very kind of you.}
{206}{}{Give it to me.}
{207}{}{(The child runs away mere moments after handing you the note. You unfold it, and see that it reads this: "The cultists got what they deserved. End your investigation or suffer the same fate.")}
{208}{}{If that kid wrote this, then all I have left to do is tremble in fear.}
{209}{}{Looks like it's not just regular bandits behind the attacks.}