{100}{}{You see an adept.}
{101}{}{You see one of the Followers of the Holy Fire. He's chanting something like a madman to attract attention.}

#Floating dialogue
{110}{}{Fear the Holy Fire!}
{111}{}{Fear the retribution of the Fiery Heavens!}
{112}{}{The Lord liveth within the power of nuclear fissio!}
{113}{}{A-a-all, a-a-a-all must repent!}
{114}{}{What? Who-î dares resist the voice of our lord?}
{115}{}{Ske-eptics! Ske-eptics will be the first to fall!}
{116}{}{These people gave up their souls to the Atomic Devil!}
{117}{}{Heed these words, victims of Radiation and Devastation!}
{118}{}{They fell due to their sinful thoughts!}
{119}{}{Respect thy father Aaron, Overlord of Phoenix, for it is He who giveth life to this desert!}
{120}{}{A new era begins!}
{121}{}{Only a fool resists progress!}

#First dialogue
{200}{}{Come closer, child of Radiation and Devastation. All must see that justice triumphs. No one will escape their divine punishment!}
{201}{}{Wait a minute, what's going on?}
{202}{}{We, the servants of the Holy Fire, have spent years hiding from ordinary people. For their hearts and minds could not accept simple truths. We were driven away, we were beaten, even killed! But we waited patiently for the right moment.}
{203}{}{[Continue]}
{204}{}{Hey you, idiot in purple rags, what the hell are you screaming about?}
{205}{}{Observe! Intolerance! Foul language! We, the servants of the Holy Fire, have spent years hiding from ordinary people. For their hearts and minds could not accept simple truths. We were driven away, we were beaten, even killed! But we waited patiently for the right moment.}
{206}{}{The moment when the lord grows tired of human stupidity and gives us respite. These people, whose bodies became vehicle for the Atomic Devil, are proof of this. They have spent many years planning various evil acts against the church. They robbed and killed our monks who simply taught the world truth. They were ungrateful! They shall burn in the Atomic Flame of the Underworld!}
{207}{}{How horrible. These bastards definitely got what they deserved.}
{208}{}{May the Holy Fire be with you! Go in peace and tell the commoners about the persecution of a peaceful church.}
{209}{}{Of course. I can't just stand around after I hear about such injustice.}
{210}{}{I'm not going to become an agitator. I'll just go about my business.}
{211}{}{Right now I've only heard one side of the story. It's obvious that I won't be able to listen to the other.}
{212}{}{Skeptics! Have we truly done so little for the city? Look at how Phoenix prospered after accepting Aaron's wisdom. Go and contemplate this. And above all, fear the Holy Fire! Fear the Fire!}
{213}{}{I'm terribly sorry. I'm not a local, I don't know much about this place. I will take a look at your church.}
{214}{}{Dude, after what I saw, your speeches sound pretty questionable. I'll decide what to think of your church for myself.}

{220}{}{Greetings, brother. I am happy to observe your illumination after our last encounter. I remember you were once a skeptic and looked at me with hostility. Now I shake your hand and tell you 'crede firmiter et pecca fortiter'.}
{1220}{}{Greetings, sister. I am happy to observe your illumination after our last encounter. I remember you were once a skeptic and looked at me with hostility. Now I shake your hand and tell you 'crede firmiter et pecca fortiter'.}
{221}{}{Greetings, brother. I am happy to see that you too have been welcomed into the church. It is a great honor, but with great honor also comes great responsibility. Crede firmiter et pecca fortiter.}
{1221}{}{Greetings, sister. I am happy to see that you too have been welcomed into the church. It is a great honor, but with great honor also comes great responsibility. Crede firmiter et pecca fortiter.}
{222}{}{Now, if you don't mind, I'd like to talk to you.}
{223}{}{Crede firmi... What? I've got a long way to go before understanding the holy texts. See you later.}

#Repeated dialogue
{250}{}{I see my speeches about the Holy Fire give you no rest, yes? So what is it exactly that you want to learn this time?}
{251}{}{So, servant of the Atomic Devil, you come to tempt me once again.}
{252}{}{Hello, brother. Is everything going well? Are the commoners disturbing you?}
{1252}{}{Hello, sister. Is everything going well? Are the commoners disturbing you?}
{253}{}{I suppose I should go.}

{260}{}{Who are you?}
{261}{}{I would like to know more about you.}
{262}{}{I am an ecclesiastic and obedient servant of Aaron, Overlord of Phoenix. My name is Gabriel.}
{263}{}{I doubt this is your real name.}
{264}{}{Enough talk. See you later.}
{265}{}{What religion exactly are you representing, Gabriel?}
{266}{}{Correct. After being accepted into the church, we change our names. By doing this, we effectively rejecting our past life.}
{267}{}{}
{268}{}{By the way, could you help me understand our faith?}
{269}{}{I want to learn more about your faith after what I heard.}
{270}{}{Tell me about the religion that you represent.}
{271}{}{Could I discuss our faith with you?}
{272}{}{The Church of the Holy Fire is in the north end of town. Go along the main street and the road itself shall bring you to the cathedral. It is better to learn about the faith during sermons rather than from me.}
{273}{}{Who are you, exactly?}
{274}{}{A cheap way to lure people in, cultist. Your trickery has no power over me.}
{275}{}{Great, I'm heading right there.}
{276}{}{So your church is so influential that you are holding public executions?}
{277}{}{No, no, the execution performed by others, under our supervision. Still, even then, the entire city has got the church to thank for many things. Water, electricity, peace and security. You will soon see it with your very own eyes, child of Radiation and Devastation.}
{278}{}{What you're saying is too good to be true, old man. I'll take a look, see whether you're saying the truth or not.}
{279}{}{In that case I simply need to explore the town. Farewell.}
{280}{}{Excuse my bad temper, but such questions are not simply discussed on the street. And one must not fill their head with skepticism. This is exactly how the Atomic Devil enters the souls of young monks. Fear the Holy Fire, novice, fear the Fire!}
{281}{}{I suppose I should pay a visit to the ministers in the cathedral. Talk to you later.}
{282}{}{What is it you do then?}
{283}{}{By the way, what were these poor sods punished for?}
{284}{}{These guys behind you definitely didn't. Why were they executed?}
{285}{}{What were those people punished for?}
{286}{}{They were fools who gave into the temptations of the Atomic Devil. Some of them spread false rumours about our church and it's leader, Aaron, may he be praised forever and ever. Others were punished for robbing our monks or stealing from the church itself. Their souls shall know no rest from this point onward in the Atomic Underworld.}
{287}{}{Don't you think this is a bit too... harsh of a punishment?}
{288}{}{They got what they deserved. I will be more careful now too. Farewell.}
{289}{}{Execution on a religious basis? I better get out of here before I wind up with them.}
{290}{}{Who are you to oversee this execution?}
{291}{}{What do you know about the rebels resisting the church?}
{292}{}{Heretics and cowards! Oh, if ONLY we knew the location of their headquarters, may they all burn in the punitive fire.}
{293}{}{Alright. You don't know anything. I'll go ask others.}

#Quest
{300}{}{I was asked to investigate the attacks on the monks by Aaron. What can you tell me about them?}
{301}{}{Tell me once again about the attacks on the Followers.}
{302}{}{The Followers were often the victims of theft and insults. When Aaron came to power, glory to him, all bandits in the city started avoiding us. But lately, the attacks have begun again.}
{303}{}{[Continue]}
{304}{}{Gunfire during the execution, a murder in the slums and an attack near the casino - here are the most daring of the crimes that have recently been commited against our brothers.}
{305}{}{Thanks, that's enough.}

{310}{}{Tell me about the gunfire during the execution.}
{311}{}{Gunfire came from the roofs of these ruins while we were executing these people. It was not one person, but rather a group. The bullets were clearly supposed to be directed at me. It is possible that the supporters of those criminals were trying to save them, but by the will of the Eye of Phoenix, they failed.}
{312}{}{There was a skirmish near the casino?}
{313}{}{Ignorant bandits shot down our brothers near the casino, like pigrats on a ranch. It is hard to tell what really happened, as there are many rumours that are inconsistent with each other.}
{314}{}{What about the incident in the slums?}
{315}{}{Very bad business. Our novices came to the slums to glorify Aaron and ask for donations to the temple. Soon they were found hanged on the lampposts. Of course, the people living nearby don't want to say anything, as if they never saw anything. So let us pray for the souls of our brothers.}
{316}{}{Do you know of any piece of information I could investigate to come closer to solving this case?}
{317}{}{Do you think Aaron would give you this case if it was not so clouded in mystery? Ask the people in the slums and the casino, maybe they will trust you more. After all, many know the faces of the Followers, and you are new in the city.}
