{100}{}{You see a guard.}
{101}{}{You see a caravan guard. He's getting ready for the coming journey.}

{110}{}{Great.}
{111}{}{Let me rest.}
{112}{}{The thirst is terrible.}
{113}{}{Time to move out.}
{114}{}{Man, the heat is so bad.}

{115}{}{Talk to the boss, I just guard the cargo.}
{116}{}{All places are taken, if that's what you wanted to ask.}
{117}{}{We need to sell everything, otherwise we're bankrupt.}
{118}{}{We deliver goods to nearly every corner of the wastes.}
{119}{}{You should visit the "Atomic fever" once, we often relax there.}

{120}{}{This is gonna be a long day.}
{121}{}{Can't wait for us to finish.}
{122}{}{What day is it today?}
{123}{}{I'm so tired.}
{124}{}{Time to go to sleep, I presume.}

{125}{}{This is a dangerous job.}
{126}{}{The dust storms are often more dangerous than bandits.}
{127}{}{To go along the highway in these times is suicide.}
{128}{}{Yeah, there are bandits and raiders on all the highways.}
{129}{}{If this cart falls apart en route, I ain't fixing it.}