{100}{}{You see the merchant Marko.}
{101}{}{You see the caravan manager. His dark skin speaks of countless miles traveled.}
{102}{}{Have a good trip.}
{103}{}{This settlement is called Two-Sun. The locals are distrustful of outsiders, so watch yourself.}

{200}{}{Hi. What do you need?}
{201}{}{Are you the manager of this caravan?}
{202}{}{Yes. If you need transportation services, then contact someone else. I try not to be distracted by small orders.}
{203}{}{Looks like your business is booming.}

{210}{}{What do you want?}
{211}{}{Nothing.}
{212}{}{Enough about it.}
{213}{}{I see.}

#Questions
{220}{}{What are you doing?}
{221}{}{I'm getting ready to ship and waiting for the rest of the cargo. My clients don't like to rush, they try to keep detailed records of every damn nut that we have to translate.}
{222}{}{Have you been doing caravan driving for a long time?}
{223}{}{Six years or so. I have a flair for the "uranium vein", do you understand? At that time, no one believed that a contract with tinsmiths would become a regular thing. I was lucky to take the vacant seat.}
{224}{}{What are you transporting?}
{225}{}{Tinsmiths are primarily interested in uranium ore, provisions, and medicines. They exchange them for technology items that they assemble or repair in their workshops.}
{226}{}{And slaves?}
{227}{}{Not my profile, slaves are too troublesome. For such a case, they usually organize a special convoy in the mercenary guild or recruit people from the population.}
{228}{}{Who are these tinsmiths?}
{229}{}{A strange, closed people, obsessed with technology. They have restored ancient machines and are now repairing broken machinery. No one in all of Arizona can match their skills.}
{230}{}{Where is their settlement?}
{231}{}{Two-Sun. That's what they call their city. Go south along the 10th highway, you won't miss it.}
{232}{}{Thank you.}
{233}{}{And who are your customers?}
{234}{}{I was hired by the Followers of Fire. That's the end of the questions. I have a rule not to discuss clients with the first person I meet.}
{235}{}{Okay, forget it.}
{236}{}{And who are the tinsmiths?}

{240}{}{Damn it! Why did Followers decide to leave this world right now, when business was booming?}
{241}{}{Were they that important to your caravan?}
{242}{}{After the Followers, no one will want to do business with me. We only worked with them. Besides, without Followers, the tinsmiths themselves will probably reduce the turnover. Hell, the entire Phoenix economy will come to an end because of some ridiculous explosion. What the hell happened there?}
{243}{}{How should I know? I generally go about my business. Bye.}
{244}{}{I have nothing to do with it! It's definitely not because of me.}
{245}{}{Well of course. As if the Followers would let an ordinary peasant into their chambers. Well, well.}
{246}{}{Ugh, I thought for a second that you suspected me. It's easier now. Bye-bye.}
{247}{}{Do you think they blew themselves up?}
{248}{}{Well, there is such an opinion. They're crazy about all this nuclear technology. Rumor has it that they were assembling a nuclear bomb in the basement of the cathedral. Something went wrong - and here is the result.}
{249}{}{But why does it bother you so much? Did your caravan depend on the temple?}

{250}{}{I'm looking for some slaves. They were brought from Flagstaff colony.}
{251}{}{Straight from the colony? Aww... Well, I drive caravans and have nothing to do with slaves. You'd better talk to someone from the city.}
{252}{}{For example? Who is doing this here?}
{253}{}{The mercenary guild will find anyone. It's in the business center, to the left of the city gate.}
{254}{}{You're of no use. Goodbye.}
{255}{}{Thanks, bye.}

#Support
{300}{}{I need to get to Two-Sun.}
{301}{}{Why should we take you to the group? An extra tail on the road will only slow down.}
{302}{}{Caravaneers should help each other.}
{303}{}{Do you know how to get to Puerto Penasco?}
{304}{}{As a Follower of Fire, I will be useful in your contracts in the future.}
{305}{}{Sorry. But maybe you know about other things.}
{306}{}{So are you another adventurer who decided to covet the remnants of a great nation? It's up to you, but we have postponed any trips to Two-Sun for now.}
{1306}{}{So are you another adventurer who decided to covet the remnants of a great nation? It's up to you, but we have postponed any trips to Two-Sun for now.}
{307}{}{Clear. So you won't help me.}
{308}{}{Perhaps. But not in your case.}
{309}{}{I think I heard about this city from the tinsmiths in Two-Sun. They trade with this city, but I don't know anything else.}

{310}{}{OK. Looks like I can do business with you. You can come with us. But keep in mind that the tinsmiths reliably guard their settlement and do not tolerate idle strangers. To get inside, you'll have to find a good reason.}
{311}{}{When are the fees?}
{312}{}{The fees are at 6 am. Take no more than 150 pounds of cargo with you. Also keep in mind that we will make a stop at Casa Grande, whether you like it or not.}
{313}{}{I can go.}
{314}{}{I will come at the appointed time.}
{315}{}{No one will drag your things. Take away the extra load or we'll leave without you.}
{316}{}{These will be my problems.}
{317}{}{Whatever you say.}
{318}{}{Hurry up, brahmin asses, we have a long way to go!}
{319}{}{[Go on a trip]}
{320}{}{Maybe so. Or maybe not.}
{321}{}{Okay, I'll review my backpack again.}
{322}{}{I will pay 1000 caps for the escort.}
{323}{}{A substantial sum. Are you sure you have that many caps?}
{324}{}{Let me count...}
{325}{}{I am on an important mission for the Church of Fire.}
{326}{}{I see. Later.}

#Other locations
{400}{}{This is a great place to relax on the way to Two-Sun. We'll replenish our water supplies, spend the night, and go on. If you are late for the shipment, we will not wait for you.}
{401}{}{What can you tell us about this settlement?}
{402}{}{Casa Grande is a small town. Usually, they stop here on the way between Two-Sun and Phoenix. Its main attraction is the water pump up the street. It is not so common to find such a source of fresh clean water in the wastelands.}
{403}{}{See you later.}
{404}{}{[Wait for the caravan to be sent to Two-Sun]}
{405}{}{Leave without me, I'll be late.}
{406}{}{As you wish. We won't wait.}
{407}{}{Okay, bye.}