{100}{}{You see merchant Marco.}
{101}{}{You see the caravan's leader. The dark skin shows that this man has traveled countless miles.}
{102}{}{Good luck.}
{103}{}{This settlement is called Two Sun. The locals don't trust outsiders, so watch your back.}

{200}{}{Hi. What do you need?}
{201}{}{Are you the leader of this caravan?}
{202}{}{Yes. If you need transport, go ask someone else. I try not to get distracted by small jobs.}
{203}{}{Looks like your business is prospering.}

{210}{}{What?}
{211}{}{Nothing.}
{212}{}{Enough about that.}
{213}{}{Understood.}

#Questions
{220}{}{What are you doing?}
{221}{}{Preparing for departure and waiting for the rest of the cargo. My clients don't like to hurry, they try to keep detailed reports about every single damn thing we deliver.}
{222}{}{Have you been doing this for a long time?}
{223}{}{About six years. I know where to find places where I can "strike uranium", get it? In those times nobody would have believed that contracts with the tinsmiths would become a regular occurence. I was lucky enough to negotiate one.}
{224}{}{What is it you deliver?}
{225}{}{The tinsmiths are, above all else, interested in uranium ore, food and medicine. They exchange them for technology which they collect or repair in their workshops.}
{226}{}{What about slaves?}
{227}{}{Not my kind of thing. There's just too much work involved. Usually, the mercenary guild organizes a special convoy, or they take people directly from the population.}
{228}{}{Who are those tinsmith guys, anyway?}
{229}{}{A strange and largely closed people obsessed with technology. They restored ancient tools and now repair broken things. Nobody in Arizona is better than them in that regard.}
{230}{}{Where is their settlement located?}
{231}{}{Two Sun. That's how they call their town. Go south along the 10th highway, you won't miss it.}
{232}{}{Thanks.}
{233}{}{And who are your clients?}
{234}{}{I was hired by the Followers of the Holy Fire. Stop those questions now. I have a rule - don't discuss the clients with the first person I see.}
{235}{}{Fine, forget it.}
{236}{}{But who are those tinsmiths?}

{240}{}{Dammit! Why, why did Followers have to leave this world just as my business was prospering?}
{241}{}{They were that important for your caravan?}
{242}{}{After that, nobody wants to deal with me anymore. We only worked with them. And even then, without the Followers, the tinsmiths themselves are most likely not going to sell so much. Damn. The entire economy of Phoenix will wither and die, all because of some ridiculous explosion. What happened there, anyway?}
{243}{}{How am I supposed to know? I should go already, anyway. Bye.}
{244}{}{Are you implying I had something to do with it?}
{245}{}{Of course! I'm sure the Followers would totally let a simple peasant into their base of operations, who would then proceed to some destroy them, all alone. Uh-uh.}
{246}{}{Oof, for a second there, I thought you actually *were* suspecting me. Now I feel better. Bye.}
{247}{}{Do you think they blew themselves up?}
{248}{}{Some think that is the case. After all, they were obsessed with nuclear technologies. Some say they made an entire nuclear bomb in the basement of their cathedral. And then something went wrong - this is the result.}
{249}{}{But why are you so mad about it? Was your caravan dependent on the temple or something?}

{250}{}{I'm looking for a couple of slaves. They were brought here from the Flagstaff colony.}
{251}{}{Right from the colony? Oh... Well, I just deal with caravans. I am not involved with slaves at all. You better talk to the locals.}
{252}{}{Like who? Who is involved with slaves here?}
{253}{}{The mercenary guild can find anyone. You can find that place in the business-center, to the left of the city gates.}
{254}{}{You're no help at all. Bye.}
{255}{}{Thanks, bye.}

#Escort
{300}{}{I need to get to Two Sun.}
{301}{}{Why should I add you to our group? You'll just slow us down.}
{302}{}{Caravaneers should help each other.}
{303}{}{Do you know how to get to Puerto Penasco?}
{304}{}{As a Follower of the Holy Fire, I would help you negotiate future contracts.}
{305}{}{Shame. But maybe you know something about other things.}
{306}{}{So you're another deadbeat wanting to gaze at the remnants of a once-great people? It's your business, not mine, but we have indefinitely cancelled all trips to Two Sun.}
{1306}{}{So you're another deadbeat wanting to gaze at the remnants of a once-great people? It's your business, not mine, but we have indefinitely cancelled all trips to Two Sun.}
{307}{}{Well, it looks like we won't be working together.}
{308}{}{Perhaps. Not in this case.}
{309}{}{I think I heard about that town from the tinsmiths in Two Sun. They trade with that place, but that's where my knowledge of it ends.}

{310}{}{Okay. Looks like I can conduct business with you. You can come with us, but be warned - the tinsmiths guard their settlement well and don't tolerate strangers going there without a very good reason. You'll have to find one if you wish to be allowed inside.}
{311}{}{When are we preparing to depart?}
{312}{}{6 o'clock in the morning. You can't take more than 150 pounds of cargo with you. Also, keep in mind that we will take a break in Casa Grande, whether you like it or not.}
{313}{}{I can head out.}
{314}{}{I'll come here in the appointed time.}
{315}{}{Nobody is going to haul your stuff. Put the excess cargo away or we're going without you.}
{316}{}{That'll be my problem.}
{317}{}{Whatever you say.}
{318}{}{Move your fat brahmin asses, we've got a long journey ahead of us!}
{319}{}{[Head out]}
{320}{}{Maybe. Or maybe not.}
{321}{}{Fine, I'll take a look inside my backpack one more time.}
{322}{}{I am willing to pay you 1000 caps for escort.}
{323}{}{A solid amount. You sure you have so many?}
{324}{}{Let me count them one more time...}
{325}{}{I'm on an important mission for the church of the Holy Fire.}
{326}{}{Alright. Bye.}

#Other locations
{400}{}{This is an excellent place to rest on our way to Two Sun. We'll replenish our water supplies, sleep and then continue on our way. If you're late, we won't wait for you.}
{401}{}{What can you tell me about this settlement?}
{402}{}{Casa Grande is a small town. Usually, people stop here while they're traveling from Phoenix to Two Sun, or vice versa. The main sight here is the water pump up the street. You don't find such a source of clean water in the desert often.}
{403}{}{Goodbye.}
{404}{}{[Wait until the caravan heads out to Two Sun]}
{405}{}{Leave without me, I'll stay here.}
{406}{}{Whatever you say. We won't wait for you.}
{407}{}{Alright, bye.}