{100}{}{You see the guard.}
{101}{}{In front of you is a caravan guard. He is preparing for the upcoming journey.}

{110}{}{Great.}
{111}{}{Let me rest.}
{112}{}{I'm thirsty.}
{113}{}{It's time to move out.}
{114}{}{What a heat.}

{115}{}{Talk to the boss, I'm just guarding the cargo.}
{116}{}{We've got all the seats taken, if that's what you're interested in.}
{117}{}{We need to sell all the goods, otherwise we are bankrupt.}
{118}{}{We take the goods to almost all corners of the wastelands.}
{119}{}{You should look into the "Atomic Fever", we often hang out there.}

{120}{}{It's going to be a long day today.}
{121}{}{I can't wait for us to finish.}
{122}{}{What day is it today?}
{123}{}{I'm so tired.}
{124}{}{It's time to go to bed, I guess.}

{125}{}{We have a dangerous job.}
{126}{}{Dust storms are sometimes more dangerous than bandits on the road.}
{127}{}{Walking on the highway now is like looking for death.}
{128}{}{Yes, I turned these raiders and bandits on all the routes.}
{129}{}{If this cart falls apart on the way, I won't fix it.}