{100}{}{You see an city dweller.}
{101}{}{You see a phoenixian.}
{102}{}{You see a phoenixian.}
{103}{}{    }

{110}{}{You see a regular inhabitant of Phoenix. Nothing special.}
{111}{}{You see a regular man. He is aimlessly walking along the street.}
{112}{}{You see a man in dirty clothes. It looks like he is suffering from a hangover.}
{113}{}{You see a local. His gaze is not welcoming.}
{114}{}{You see a local. He quickly stops looking at you, as if he doesn't notice you.}

{120}{}{You see a regular inhabitant of Phoenix. Nothing special.}
{121}{}{You see a regular woman. She is aimlessly walking along the street.}
{122}{}{You see a woman in shabby clothes. It wouldn't hurt to change them.}
{123}{}{You see a female inhabitant of Phoenix. Her gaza indicates irritation.}
{124}{}{You see a female inhabitant of Phoenix. She snorts when she catches you looking at her.}

#########################################
#Replies
#########################################

#- reputation
{200}{}{Good day.}
{201}{}{After you.}
{202}{}{*Waves hand in a friendly manner*}
{203}{}{Of course, of course, I shouldn't waste your time.}
{204}{}{Can I help you?}
{205}{}{I'd buy you a drink, but I have a hangover.}
{206}{}{Hello. How are you?}
{207}{}{One should stick to people like you.}
{208}{}{I don't know why, but I heard a lot of good things about you.}
{209}{}{My respect.}

{210}{}{Hello.}
{211}{}{Watch where you're heading.}
{212}{}{Damn tourists...}
{213}{}{Don't annoy people, someone is bound to punch you between the eyes.}
{214}{}{It's obvious you aren't a local.}
{215}{}{First time in Phoenix, huh?}
{216}{}{*Shakes you off*}
{217}{}{Great, one more bum.}
{218}{}{Stop bothering me.}
{219}{}{What?}

{220}{}{Fuck off.}
{221}{}{Get off the street.}
{222}{}{Get off the road.}
{223}{}{I'll make sure to see your execution.}
{224}{}{Great, another peasant. Why do you people rush here, eh?}
{225}{}{What, wasteland too crowded for you?}
{226}{}{Don't come close to me.}
{227}{}{Phoenix has no place for people like you.}
{228}{}{You'll get hanged too.}
{229}{}{The city would be a better place without you.}

#- power armor
{230}{}{Don't touch me, Iron Man!}
{231}{}{Hello, uhh, sir... or ma'am... or whoever is inside of this thing.}
{232}{}{Can I ride on you?}
{233}{}{Hey, can you kill a few people I don't like?}
{234}{}{You're looking for other robots? Well, are those like you?}
{235}{}{If you're looking for your fellow robots, I'm sorry, there aren't many of you left.}
{236}{}{I feel so bad for you, robot. You are alone in a world of men.}
{237}{}{*Knock-knock* Hey, who's there?}
{238}{}{Sorry, but there is no Scarecrow or Toto here.}
{239}{}{Don't make me oil you up.}

#- player is a follower
{240}{}{I pray to the Holy Fire every day... I'm telling the truth.}
{241}{}{I'm sorry, I'll get off the road immediately...}
{242}{}{I promise I'll be good.}
{243}{}{Glory to the Holy Fire... What's after that?}
{244}{}{I'm sorry, I won't breathe YOUR air any longer.}
{245}{}{I respect Aaron, our liberator.}
{246}{}{How does one become a Follower?}
{247}{}{I don't need trouble.}
{248}{}{Is it true that you're forbidden from fucking?}
{249}{}{Don't even ask for donations to the temple - I don't have anything.}

#- player is a champion of the arena
{250}{}{I'd buy you a drink, but the person I put my bet on in the last fight lost.}
{251}{}{Damn, you should have lost. I would've gotten money that way.}
{252}{}{I'm sorry, I'll get off the road immediately... and leave the city.}
{253}{}{You know, you don't look like a champion to me.}
{254}{}{How long have you been exercising?}
{255}{}{I'll be SO sad if you lose the next fight.}
{256}{}{I'll bring my kids with me to watch the next fight.}
{257}{}{That was an awesome fight, champion.}
{258}{}{Why aren't you fighting on the arena anymore?}
{259}{}{Fights on the arena have become boring without you.}

{1250}{}{I'd buy you a drink, but the person I put my bet on in the last fight lost.}
{1251}{}{Damn, you should have lost. I would've gotten money that way.}
{1252}{}{I'm sorry, I'll get off the road immediately... and leave the city.}
{1253}{}{You know, you don't look like a champion to me.}
{1254}{}{How long have you been exercising?}
{1255}{}{I'll be SO sad if you lose the next fight.}
{1256}{}{I'll bring my kids with me to watch the next fight.}
{1257}{}{That was an awesome fight, champion.}
{1258}{}{Why aren't you fighting on the arena anymore?}
{1259}{}{Fights on the arena have become boring without you.}

#- player is on drugs
{260}{}{Yes, yes, uhh, the leprechauns are just beyond that corner.}
{261}{}{Are you on drugs or what?}
{262}{}{I had problems with that too.}
{263}{}{No, I don't have any drugs for you.}
{264}{}{Scram, damn drug addict.}
{265}{}{I feel sorry for those like you.}
{266}{}{Everything alright?}
{267}{}{Looks like you feel good... judging by the dilated pupils.}
{268}{}{This won't lead to anything good.}
{269}{}{You need drugs? Go find them in the slums, loser.}

#- about the city
{270}{}{This sky will never become clear.}
{271}{}{This night will be a hot one.}
{272}{}{The eastern winds bring only dust and ashes.}
{273}{}{There was always smog here.}
{274}{}{The dust storm season is near.}

{275}{}{I hate this damn city.}
{276}{}{I've spent too much time here.}
{277}{}{The city is becoming crowded.}
{278}{}{Time to get out of this city.}
{279}{}{Phoenix is full of people... and problems.}

{280}{}{Fortune has turned it's back on me.}
{281}{}{I'm gonna hit the jackpot in that casino.}
{282}{}{I'm TRYING to stop, but...}
{283}{}{Evening's gonna be a party!}
{284}{}{I'll try my luck in the casino.}

{285}{}{Can't wait for Veronica's new performances.}
{286}{}{I envy Veronica's shape.}
{287}{}{Another pathetic day.}
{288}{}{Go to the arena if you have nothing to do.}
{289}{}{Not one drop of rain for so many years.}

{290}{}{They say the mercs are readying a new batch of slaves.}
{291}{}{The casino's just full of cheaters.}
{292}{}{The street bandits can do anything they want.}
{293}{}{Only death awaits those who enter the slums.}
{294}{}{Caravaneers, caravaneers everywhere...}

{295}{}{}
{296}{}{}
{297}{}{}
{298}{}{}
{299}{}{}

#########################################
#Floating dialogue
#########################################

#- reputation
{300}{}{}

#- power armor
{330}{}{Oh no, oh no, IT'S looking in my direction!}
{331}{}{You think it wants to attack someone?}
{332}{}{Just ignore it, just ignore it...}
{333}{}{Just looking at that... THING gives me the creeps.}
{334}{}{This doesn't look like a robot.}
{335}{}{So that's what it looks like - the legendary power armor.}
{336}{}{I hope this thing isn't radioactive.}
{337}{}{What is this? Some kind of moving washing machine?}
{338}{}{They say this thing killed five people just yesterday.}
{339}{}{Oops, better get off the road.}

#- player is a follower
{340}{}{Don't get close to that person.}
{341}{}{Those uniforms look so evil.}
{342}{}{There are so many cultists around... oops, better not say anything.}
{343}{}{Don't say anything bad about the Followers.}
{344}{}{Don't look at the Followers while they're near you, it's not a good sign.}
{345}{}{Is that a follower? I need to come up with something flattering...}
{346}{}{These Followers have spies everywhere.}
{347}{}{Walking across the city so openly? The arrogance of those cultists knows no bounds.}
{348}{}{These Followers think they own Phoenix.}
{349}{}{I hope that cultist isn't going to make me donate to the temple.}

#- player is an arena champion - male
{350}{}{So this is that unusual one from the arena.}
{351}{}{You think if I come close, he'll punch me?}
{352}{}{He must be the best fighter in the world.}
{353}{}{Don't look at him, don't look at him...}
{354}{}{Hey, great fight, champion!}
{355}{}{*whistles* Hey! Champion!}
{356}{}{I wonder whether this giant will pay attention to me.}
{357}{}{Men earn by fighting. What is this world coming to...}
{358}{}{Why aren't you participating in the fights anymore?}
{359}{}{Hey, giant, show us your left hook!}

#- player is an arena champion - female
{360}{}{So this is that unusual one from the arena.}
{361}{}{You think if I come close, she'll punch me?}
{362}{}{This bitch will put anyone down on the ground.}
{363}{}{Don't look at her, don't look at her...}
{364}{}{Hey, great fight, champion!}
{365}{}{whistles* Hey! Champion!}
{366}{}{I wonder whether this star will pay attention to me.}
{367}{}{A woman being an arena champion? What are we coming to...}
{368}{}{Why aren't you participating in the fights anymore?}
{369}{}{Hey, woman, show us your left hook!}

#- about the city
{370}{}{*Achoo!*}
{371}{}{It's hard to breathe this air.}
{372}{}{You can't see the city even from a mountain due to all this smog.}
{373}{}{Someone needs to do something about all this trash.}
{374}{}{This night will be a hot one.}

{375}{}{This city is becoming crowded.}
{376}{}{It's good that they hanged that guy...}
{377}{}{Everywhere I go there are only hobos and slackers...}
{378}{}{I can't live in these conditions anymore.}
{379}{}{Time to get out of this city.}

{380}{}{The bank had mercy upon me.}
{381}{}{I'm not going in the casino at all from now on.}
{382}{}{I'll go to the casino for just an hour... or a bit more.}
{383}{}{Fortune has turned it's back on me.}
{384}{}{It was all set up against me.}

{385}{}{I swear, if the Followers try to moralize me one more time...}
{386}{}{During the day, even the slums are dangerous.}
{387}{}{There are more and more caravans now.}
{388}{}{Is there really life beyond the city?}
{389}{}{Only the desperate can travel across the desert.}

#- explosion of the cathedral
{390}{}{These cultists got what they deserved.}
{391}{}{Phoenix will have a hard time existing without the Followers.}
{392}{}{Cathedral destroyed, Followers fleeing. What a world...}
{393}{}{I don't know whether life is better or worse without the Followers.}
{394}{}{I can't believe it was an atomic bomb.}
{395}{}{So those idiots were building an atomic bomb?}
{396}{}{An atomic bomb? Yes, they were definitely not all right in the head.}
{397}{}{After the destruction of the Cathedral the value of caps is going down and down.}
{398}{}{Who will control the rate of the caps now?}
{399}{}{Looks like bottle caps will become useless junk once again.}