{100}{}{You see a beggar.}
{101}{}{You see an ordinary street dweller.}
{102}{}{You have witnessed a crime.}
{103}{}{What am I standing for? We need to remove the witnesses!}

{110}{}{Am I... a murderer?}
{111}{}{I didn't mean to!}
{112}{}{She forced me.}
{113}{}{If she hadn't shown her caps...}
{114}{}{Why did I do it?}
{115}{}{I think I killed her.}
{116}{}{My God, I killed a man!}
{117}{}{There's nothing to be done now.}
{118}{}{You won't tell anyone, will you?}
{119}{}{Looks like I'm going to have to get out of town.}