{100}{}{You see a bum.}
{101}{}{You see an average inhabitant of the steets.}
{102}{}{You have become a crime witness.}
{103}{}{Why am I standing around? I need to deal with the witnesses!}

{110}{}{I'm... a murderer?}
{111}{}{I didn't want to do it!}
{112}{}{She forced me.}
{113}{}{If she didn't show me her caps...}
{114}{}{Why did I do it?}
{115}{}{Looks like I killed her.}
{116}{}{Oh my god, I just killed a person!}
{117}{}{Can't do anything now.}
{118}{}{You're not gonna tell anyone, right?}
{119}{}{Looks like I'll have to get out of the city.}