{100}{}{Here is a citizen.}
{101}{}{Here is a Phoenician.}
{102}{}{Here is a Phoenician woman.}
{103}{}{ }

{110}{}{You see an ordinary resident of Phoenix. Nothing outstanding.}
{111}{}{You see an inconspicuous man. He mindlessly hobbles along the street.}
{112}{}{You see a man in dirty clothes. He seems to be suffering from a hangover.}
{113}{}{You see a local. His gaze is unfriendly.}
{114}{}{You see a local. He quickly looks away from you, as if he doesn't notice.}

{120}{}{You see an ordinary resident of Phoenix. Nothing outstanding.}
{121}{}{You see an inconspicuous woman. She walks listlessly along the street.}
{122}{}{You see a woman in old clothes. It won't hurt her to change her wardrobe.}
{123}{}{You see a Phoenix resident. Her look expresses annoyance.}
{124}{}{You see a Phoenix resident. She snorts when she catches your eye.}

#########################################
#Retaliatory remarks
#########################################

#- reputation
{200}{}{Good afternoon.}
{201}{}{Only after you.}
{202}{}{*Waving to you affably*}
{203}{}{Of course, of course, I dare not delay.}
{204}{}{Is there anything I can do to help?}
{205}{}{I want to buy you a drink, but I'm broke.}
{206}{}{Hello. How are you?}
{207}{}{We need to stick with people like you.}
{208}{}{I don't know why, but they say a lot of good things about you.}
{209}{}{My respects.}

{210}{}{Hello.}
{211}{}{Watch where you're going.}
{212}{}{Damn tourists...}
{213}{}{Don't bother passersby, otherwise you'll get between the eyes.}
{214}{}{You're not from the locals, it's obvious right away.}
{215}{}{First time in Phoenix, huh?}
{216}{}{*Dismisses you*}
{217}{}{Great, another beggar.}
{218}{}{Stop bothering me.}
{219}{}{What do you need?}

{220}{}{Fuck off.}
{221}{}{Get off the street.}
{222}{}{Get out of the way.}
{223}{}{When they hang you, I'll laugh. LAUGH!}
{224}{}{Great, one more peasant. Why are you coming here, huh?}
{225}{}{Is there not enough room for you in the wastelands?}
{226}{}{Don't come near me.}
{227}{}{People like you don't belong in Phoenix.}
{228}{}{You'll end up being hanged, too.}
{229}{}{The city would be a better place without you.}

#- power armor
{230}{}{Don't touch me, Iron Man!}
{231}{}{Hello, uh, sir... or ma'am... or whoever it is.}
{232}{}{Can I ride you?}
{233}{}{This, can you kill a couple of my enemies?}
{234}{}{Are you looking for other robots? Well, the same as you?}
{235}{}{If you're looking for your fellow robots, there aren't many left.}
{236}{}{I feel so sorry for you, robot, you are so lonely in the world of people.}
{237}{}{*Knock-knock* Hey, is anyone there?}
{238}{}{Sorry, but the Scarecrow and Toto are not here.}
{239}{}{Don't make me oil you.}

#- GG follower
{240}{}{I pray to the Sacred Fire every day... the truth is true.}
{241}{}{I'm sorry, I'll get out of the way immediately...}
{242}{}{I promise I'll be good.}
{243}{}{May the Sacred Fire be glorified... What's next?}
{244}{}{I'm sorry, I won't breathe YOUR air anymore.}
{245}{}{I honor Aaron, our liberator.}
{246}{}{How to become a novice?}
{247}{}{I don't want any trouble.}
{248}{}{Is it true that you are forbidden to fuck?}
{249}{}{Don't even ask for donations to the temple, I have nothing.}

#- GG arena champion
{250}{}{I would have bet you a drink, but my bet on the last fight burned out.}
{251}{}{Damn, if you lost, my bet would have won.}
{252}{}{I'm sorry, I'll get out of the way immediately... And I'll leave town.}
{253}{}{And you don't look like you're a champion.}
{254}{}{How long did you have to train?}
{255}{}{If you lose the next fight, I'll be SO upset.}
{256}{}{I'll take my kids to the next fight.}
{257}{}{It was a great fight, champion.}
{258}{}{Why don't you fight in the ring anymore?}
{259}{}{Arena fights have become boring without you.}

{1250}{}{I would have bet you a drink, but my bet on the last fight burned out.}
{1251}{}{Damn, if you lost, my bet would have won.}
{1252}{}{I'm sorry, I'll get out of the way immediately... And I'll leave town.}
{1253}{}{And you don't look like you're a champion.}
{1254}{}{How long did you have to train?}
{1255}{}{If you lose in the next fight, I'll be SO upset.}
{1256}{}{I'll take my kids to the next fight.}
{1257}{}{It was a great fight, champion.}
{1258}{}{Why don't you fight in the ring anymore?}
{1259}{}{Arena fights have become boring without you.}

#- GG stoned
{260}{}{Yeah, yeah, uh, the leprechauns are over there, around the corner.}
{261}{}{Are you high?}
{262}{}{I also had problems with this stuff.}
{263}{}{I don't have any drugs for you.}
{264}{}{Go away, you fucking junkie.}
{265}{}{I feel sorry for people like you.}
{266}{}{Are you all right?}
{267}{}{Looks like you're doing well... judging by the dilated pupils.}
{268}{}{It won't do any good.}
{269}{}{Need drugs? Look for them in the slums, loser.}

#- about the city
{270}{}{This sky will never be clear.}
{271}{}{It's going to be a hot night.}
{272}{}{Easterly winds bring only dust and ashes.}
{273}{}{There is always such a smog here.}
{274}{}{Dust storm season is coming soon.}

{275}{}{I hate this damn city.}
{276}{}{I've been living here too long.}
{277}{}{It's getting a little crowded in the city.}
{278}{}{It's time to get out of this city.}
{279}{}{Phoenix is crowded with people... and problems.}

{280}{}{Fortune has turned away from me.}
{281}{}{I'm going to break the bank at the casino.}
{282}{}{I'm trying to quit, but...}
{283}{}{I'm having fun tonight!}
{284}{}{I want to try my luck at the casino.}

{285}{}{I can't wait for Veronica's new performances.}
{286}{}{Veronica has an enviable figure.}
{287}{}{Another worthless day.}
{288}{}{Go to the ring if you have nothing to do.}
{289}{}{Not a single rain in many years.}

{290}{}{They say the mercenaries are preparing a new batch of slaves.}
{291}{}{There are only crooks in the casino.}
{292}{}{Street thugs got completely out of hand.}
{293}{}{Death awaits you in the slums.}
{294}{}{Caravaneers, caravaneers all around...}

{295}{}{}
{296}{}{}
{297}{}{}
{298}{}{}
{299}{}{}

#########################################
#Floating replicas
#########################################

#- reputation
{300}{}{}

#- power armor
{330}{}{Oh, no, no, IT's looking my way!}
{331}{}{Do you think it wants to attack someone?}
{332}{}{Just ignore, just ignore...}
{333}{}{From the sight of this one... THINGS are getting uncomfortable.}
{334}{}{It doesn't look like a robot.}
{335}{}{So that's what it is - the legendary power armor.}
{336}{}{I hope this thing isn't radioactive.}
{337}{}{Is this some kind of self-propelled washing machine?}
{338}{}{They say this piece of iron just killed five people yesterday.}
{339}{}{Oh, it's better to get out of the way.}

#- GG follower
{340}{}{Stay away from this guy.}
{341}{}{It looks ominous.}
{342}{}{These sectarians are divorced... oops, it's better to be silent.}
{343}{}{Don't speak ill of Followers.}
{344}{}{Don't look at the followers point-blank, it's a bad sign.}
{345}{}{Is it a follower? I have to say something flattering...}
{346}{}{These followers have spies everywhere.}
{347}{}{Walking around the city openly like this? These sectarians have become quite arrogant.}
{348}{}{These followers feel like masters of the Phoenix.}
{349}{}{I hope this sectarian is not going to demand donations from me.}

#- GG arena champion - husband
{350}{}{It's that crazy guy from the ring.}
{351}{}{Do you think if I come up, he will hit me?}
{352}{}{This fighter is a fighter to all fighters.}
{353}{}{Just don't look at him, just don't look...}
{354}{}{Hey, great fight, champion!}
{355}{}{*whistles* Hey! Champion!}
{356}{}{I wonder if this bully will pay attention to me.}
{357}{}{Men earn money from fights. What the world has come to...}
{358}{}{Why aren't you fighting anymore?}
{359}{}{Come on, big guy, show me your left hook!}

#- GG arena champion - Women
{360}{}{It's the crazy one from the ring.}
{361}{}{Do you think if I come up, she'll hit me?}
{362}{}{This bitch will put anyone on the shoulder blades.}
{363}{}{Just don't look at her, just don't look...}
{364}{}{Hey, great fight, champion!}
{365}{}{*whistles* Hey! Champion!}
{366}{}{I wonder if this star will pay attention to me.}
{367}{}{A woman and an arena champion? What have we come to...}
{368}{}{Why aren't you fighting anymore?}
{369}{}{Come on, woman, show me your right hook!}

#- about the city
{370}{}{*Apchi!*}
{371}{}{It's hard to breathe this air.}
{372}{}{Because of the smog, the city is not even visible from the mountain.}
{373}{}{Someone has to clean up all this garbage.}
{374}{}{It's going to be a hot night.}

{375}{}{It's getting a little crowded in the city.}
{376}{}{It's good that that guy was hanged...}
{377}{}{There are only tramps and idlers around...}
{378}{}{I can't live in such conditions anymore.}
{379}{}{It's time to get out of the city.}

{380}{}{The bank took pity on me.}
{381}{}{Not a foot in the casino anymore.}
{382}{}{I'll go to the casino for an hour... or more.}
{383}{}{Fortune has turned away from me.}
{384}{}{Everything was against me.}

{385}{}{If Followers start reading me another moral...}
{386}{}{Even during the day it is dangerous in the slums.}
{387}{}{There are more caravans.}
{388}{}{Is there really life outside the city?}
{389}{}{Only the desperate can travel through the desert.}

#- Cathedral explosion
{390}{}{These sectarians got what they deserved.}
{391}{}{Phoenix will have a hard time without Followers.}
{392}{}{The cathedral was destroyed, and the followers fled. Business...}
{393}{}{I don't know which is better - with or without followers.}
{394}{}{I can't believe it was a nuclear bomb.}
{395}{}{So these idiots were building a nuclear bomb?}
{396}{}{A nuclear bomb? Yes, they were definitely abnormal.}
{397}{}{After the explosion in the Cathedral, the caps began to depreciate.}
{398}{}{Who will now control the course of the caps?}
{399}{}{It looks like the caps will become useless junk again.}