{102}{}{I will not tolerate this in my casino. Leave your toys on the street.}
{103}{}{Are you threatening me?}

#Meeting
{200}{}{One must have balls of steel to barge into my office so boldly. Who are you? What do you want?}
{1200}{}{One must have nerves of steel to barge into my office so boldly. Who are you? What do you want?}
{201}{}{I'm }
{202}{}{ from Villa. I want to work for you, Don Diego.}
{203}{}{Many say the same thing, but then run away at the first hint of having to bear responsibility. You see, this casino is not simply a place to earn money to me. It's a family. I need good reasons to accept the first person I see into it.}
{204}{}{If you need reasons, I'll find them. Until we meet again, Don Diego.}
{205}{}{Bill told me that you'd come. Who are you? What do you want?}
{206}{}{Don Diego, listen to me. The commune from which I stepped forth became victim to slavers. I am trying to make things right.}
{207}{}{So why don't you ask Aaron himself for help? From what I know, it's exactly his cult that's giving caps to the slave traders in various colonies. I cannot and do not want to help you.}
{208}{}{It is very sad to hear this. Goodbye, Don Diego.}
{209}{}{Curious. You are asking for my help?}
{210}{}{Not exactly. I'm offering a partnership. It looks as if we have a common enemy - the Fire-worshippers.}
{211}{}{You're talking about simple business. As I said, the casino is family for me, not just business. I don't want to risk myself and my people in direct battle with the cultists and be the aggressor in that situation. But Aaron's pressure is becoming stronger and stronger, and one day I will have to take decisive action.}
{212}{}{It is very sad to hear this. Goodbye, Don Diego.}
{213}{}{Give me a chance. You won't regret it.}
{214}{}{It's not help I'm asking for, Don Diego. It's justice.}
{215}{}{You know, I used to be just like you once, a regular peasant. I dug in the dirt, dealt with mouses in an old barn. I had to spend a lot of effort to get out of that hole and establish my presense in the city.}
{216}{}{I'm very happy that you understand me.}
{217}{}{But a lot of time has passed since then. I sympathise with you. But I need good reasons to trust me.}
{218}{}{Give me something to do. I'll do it and prove that your mistrust is unfounded.}
{219}{}{It is very sad to hear this. Goodbye, Don Diego.}
{220}{}{Talk to Garcia. He'll give you a couple of simple tasks for a start. We'll see how well you'll manage.}
{221}{}{I won't dissapoint you, Don Diego.}
{222}{}{Alright. Whatever you say.}
{223}{}{Unfortunately, right now I don't have any tasks for you.}
{224}{}{It is very sad to hear this.}

{250}{}{What do you want?}
{251}{}{What are you going to tell me?}
{252}{}{Did something happen?}
{253}{}{My regards, Don Diego.}

{260}{}{Don Diego, I'm curious, what are you going to do now that the cathedral is destroyed?}
{261}{}{You ask questions unsuited for your position.}
{262}{}{I apologize, Don Diego.}
{263}{}{Alright, I was just curious.}
{264}{}{The same things as before. Earn money, expand my influence. It's easier to do now than ever.}
{265}{}{The Cult of the Holy Fire was standing in your way, right?}
{266}{}{The Fire-worshippers' departure from Phoenix as a force opens up many good vacancies, but at the same time, it has negatively impacted many people in the city. Without the Cathedral, it will be difficult to support the rate of bottlecap currency, a part of the caravans will lose their jobs, and some people are already fleeing the city. Not to mention the increased crime rate. These conditions force me to re-examine my entire business. But yes, it only helps me.}
{267}{}{Thank you for your answer, Don Diego.}

#Attack on the Followers
{300}{}{I am investigating attacks on monks. What do you know about this?}
{301}{}{I will not let you break into my office to interrogate me. Security, throw this one out of the casino.}
{302}{}{Just try it!}
{303}{}{Alright, alright, I'm leaving.}
{304}{}{Has breaking in to interrogate people become the norm for the Followers? Alright, I'll answer out of respect for the church which feeds the city.}
{305}{}{Great, let me take out my notebook... Let's begin.}
{306}{}{I. Don't. Know. Anything.}
{307}{}{Uhh, what?}
{308}{}{Someone surrounded monks on the street and shot them. Point-blank. I was not there, there are many different rumours and my men assure me that they are not involved. I have nothing more to say.}
{309}{}{Oh, I'm sorry, Don Diego. I see now that I am just wasting your time.}
{310}{}{Good luck in your investigation. And don't distract me with this topic anymore.}
{311}{}{Goodbye.}
{312}{}{What alibi do you and your subordinates have?}
{313}{}{What fucking alibi? Our casino owes the church of the Holy Fire for what it did for the city. It regulates cap turnover and grants people jobs. You don't bucher the brahmin you're milking, understand? Especially so openly and right at our front doors.}
{314}{}{Hm-m, this whole case still looks suspicious. I will leave, but know that I am keeping an eye on you.}
{315}{}{I understand now. Goodbye.}
{316}{}{Let's change things up, Don Diego, and stop talking so formally.}
{317}{}{Hey, Garcia, what does this peasant say? He thinks he can talk to me as an equal? This man is definitely stupid. Throw him out of the casino.}
{1317}{}{Hey, Garcia, what does this peasant say? She thinks she can talk to me as an equal? This woman is definitely missing her mental faculties today. Throw her out of the casino.}
{318}{}{Then remember this, young adept of a dubious cult. Many in this city would like the Followers to be destroyed.}
{319}{}{Why?}
{320}{}{First there was the revolution which brought Aaron to power. Then the giant inquisition set up by this ruler to consolidate power. The people don't forget such things. The ones you seek are well-organized and equipped with good weaponry. They do not spare bullets and are not afraid of going against authority. These are not mere thieves or mercenaries.}
{321}{}{A good observation. I should think about this.}
{322}{}{Well-organized and well-armed. Just like your casino... Not to say I'm accusing you of anything. Goodbye, Don Diego.}