{100}{}{You see Diego's woman.}
{101}{}{You see one of Don Diego's wives.}

{110}{}{What are you even doing?}
{111}{}{There is no place for you here.}
{112}{}{If the husband learns about this, we'll both have problems.}
{113}{}{You better get out of here.}
{114}{}{Diego won't like your presense.}
{115}{}{If you have something you want to tell Diego, then head right to him.}

{1110}{}{Don't even think about replacing us.}
{1111}{}{This position is taken, dear.}
{1112}{}{Oh, did you want to become part of our family?}
{1113}{}{You better get out of here.}
{1114}{}{We are not going to tolerate new competition.}
{1115}{}{Diego's OURS. Don't even dream of him sharing his bed with you.}

{120}{}{We don't know what to do anymore.}
{121}{}{Diego protected us.}
{122}{}{There is so much conflict here now, ever since we lost our husband.}
{123}{}{Ever since Diego died, it's as if no one is bothering hiding their true selves anymore.}
{124}{}{Ah, Diego... Who could have done this to you?}