{102}{}{I will not tolerate this in my casino. Leave your toys outside.}
{103}{}{Are you threatening me?}

#Acquaintance
{200}{}{To break into me so brazenly, you need balls of steel. Who are you? What do you need?}
{1200}{}{To break into me so brazenly, you need nerves of steel. Who are you? What do you need?}
{201}{}{I }
{202}{}{ from the Villa. And I want to work for you, Don Diego.}
{203}{}{Many say the same thing, and then run away at the slightest hint of responsibility. You see, this casino is not just a place for me to earn money. It's a family. I need serious reasons to accept the first person I meet into it.}
{204}{}{If you need a foundation, I'll find something to strengthen it. See you later, Don Diego.}
{205}{}{Bill warned me about your arrival. Who are you? What do you need?}
{206}{}{Don Diego, listen to me. The community I came from fell victim to the slavers. I'm trying to get it back the way it was.}
{207}{}{So why don't you ask Aaron himself for help? As far as I know, it is his cult that supplies caps to slavers in various colonies. I can't and don't want to help you.}
{208}{}{Sorry to hear that. Goodbye, Don Diego.}
{209}{}{Curious. Are you asking for my help?}
{210}{}{Rather, I offer cooperation. It seems that we have a common enemy - the fire worshippers.}
{211}{}{You're talking about a simple business. As I said, this casino is a family for me, not just a business. I don't want to put myself and my "relatives" at risk in a direct fight against sectarians and act as an aggressor at the same time. But Aaron's pressure is getting stronger, and someday I will have to take drastic measures.}
{212}{}{I'm sorry to hear that. Goodbye, Don Diego.}
{213}{}{Give me a chance. You won't regret it.}
{214}{}{I'm not asking for help. I ask for justice, Don Diego.}
{215}{}{You know, once I was just like you, an ordinary peasant. I was digging in the dirt, doing mouse scuffling in an old barn. It took a lot of effort to get out of that hole and strengthen in the city.}
{216}{}{I'm glad you understand me.}
{217}{}{That's just a lot of time has passed since then. I like you. But I need serious reasons to trust you.}
{218}{}{Check me out in the case. I will prove that your distrust is in vain.}
{219}{}{I'm sorry to hear that. Farewell, Don Diego.}
{220}{}{Talk to Garcia. He'll give you a couple of simple tasks to start with. Let's see how you do.}
{221}{}{I will not disappoint you, Don Diego.}
{222}{}{Okay. As you say.}
{223}{}{Unfortunately, I don't have a job for you right now.}
{224}{}{I'm sorry to hear that.}

{250}{}{What do you want?}
{251}{}{What will you tell me?}
{252}{}{Did something happen?}
{253}{}{My respects, Don Diego.}

{260}{}{Don Diego, I wonder what you intend to do now that the cathedral has been destroyed?}
{261}{}{You allow yourself questions not on the status.}
{262}{}{I'm sorry, Don Diego.}
{263}{}{Okay, I'm just wondering.}
{264}{}{The same as before. Earn, expand your influence. It's easier to do this now than ever.}
{265}{}{The Cult of Fire interfered with you, didn't it?}
{266}{}{The departure of fire worshippers from the Phoenix stage opens up good vacancies, but at the same time it is a blow to many areas of activity in the city. Without the cathedral, it will be difficult to maintain the exchange rate of the cap currency, some caravans will lose their jobs, some people are already fleeing the city. What to say about the increased crime. In such conditions, you have to reconsider your entire business. But yes, it's just to my advantage.}
{267}{}{Thank you for your answer, Don Diego.}

#Attack on Followers
{300}{}{I'm investigating an attack on monks. What do you know about it?}
{301}{}{I won't let you barge in on me with an interrogation. Security, throw this persistent man out of the casino.}
{302}{}{Just touch it!}
{303}{}{OK, I'll leave.}
{304}{}{Breaking in with an interrogation has become the norm for Followers? Okay, I'll answer out of respect for the church that feeds the city.}
{305}{}{Great, let me open the notebook... Here we go.}
{306}{}{Ya. Nothing. I don't know.}
{307}{}{Uh, what?}
{308}{}{Someone surrounded the monks on the street and shot them at point-blank range. I wasn't there, there are different rumors, my people assure me that they are not in business. I have nothing more to say.}
{309}{}{Oh, sorry, Don Diego. Now I see that I'm wasting your time.}
{310}{}{Success in the investigation. And don't bother me about this case anymore.}
{311}{}{Goodbye.}
{312}{}{And what alibi do you and your subordinates have?}
{313}{}{What the fuck is an alibi? Our casino owes a debt to the Sacred Fire Church for what it has done for the city. The church regulates the turnover of caps and gives people jobs. It makes no sense for us to chop down the brahmin we are milking, do you understand that? Moreover, it is so open and at its own doors.}
{314}{}{Hmm, nevertheless it looks doubtful. I'll leave, but I'll still take you on a pencil.}
{315}{}{I understand now. Have a nice day.}
{316}{}{Come on, Don Diego, let's talk informally.}
{317}{}{Hey, Garcia, what is this peasant carrying? Do you think he can talk to me on equal terms? This man is definitely stupid. Throw him out on the street.}
{1317}{}{Hey, Garcia, what is this peasant woman carrying? Does she think she can talk to me on equal terms? This woman is definitely not herself. Throw her out on the street.}
{318}{}{Then remember, young adept of a dubious cult, that in this city many have a grudge against Followers.}
{319}{}{Why is that?}
{320}{}{First, the revolution that brought Aaron to power. And then the mass inquisition, arranged by this ruler to strengthen power. People do not soon forget this. The ones you're looking for are well organized and equipped with good weapons. They do not spare bullets and are not afraid to go against the authorities. These are not simple robbers or mercenaries.}
{321}{}{A reasonable remark. I should think about it.}
{322}{}{Well organized and armed. Just like your casino... No, no, I'm not accusing you of anything. Farewell, Don Diego.}