{100}{}{You see a Diego's woman.}
{101}{}{You see one of Don Diego's wives.}

{110}{}{What do you allow yourself?}
{111}{}{We don't have a place for you.}
{112}{}{If the husband finds out, then we will all have problems.}
{113}{}{You better get out of here.}
{114}{}{Diego won't like your presence.}
{115}{}{If you have business with Diego, then go to him.}

{1110}{}{Don't even hope to become one of us.}
{1111}{}{Honey, this place is taken}
{1112}{}{Are you in our family too?}
{1113}{}{You better get out of here.}
{1114}{}{We will not tolerate a new competitor.}
{1115}{}{Diego IS OURS. Don't even dream of sharing a bed with him.}

{120}{}{We don't know what to do now.}
{121}{}{Diego was our patron.}
{122}{}{Without a husband, a real fight started around us.}
{123}{}{After Diego's death, everyone around seemed to break loose.}
{124}{}{Ah, Diego... Who just raised their hand?}