{100}{}{You see a pusher.}
{101}{}{You see a drug dealer or something like that.}
{102}{}{Pusher raised the prices of his goods.}
{103}{}{You have received a discount on pusher products.}
{104}{}{Be careful with that, baby. You're looking for serious trouble.}

#First meeting
{200}{}{Hey, man, you look like a million. Don't you want to hang out in this city before Fortune turns around?}
{1200}{}{Hey, baby, you look like a million. Don't you want to hang out in this city before Fortune turns backwards?}
{201}{}{What exactly are you suggesting?}
{202}{}{Different kinds of pleasures. Just take this pill and you will get such a buzz that no gambling game gives. I know what I'm talking about. I checked it on myself.}
{203}{}{So are you selling drugs or something like that?}
{204}{}{I doubt you can offer me anything worthwhile.}
{205}{}{Of course, of course, whatever you say, man. But trust me, you're giving up the last pleasure in this lousy world.}
{206}{}{Pleasure? Come on, come on, that's where we should have started.}
{207}{}{What are you trying to sell me?}
{208}{}{I don't know what you're talking about. I have pure stimpacks and mentats. Who would want to call it a drug? The question is how well you will use it. But this is already (winks) none of my business.}
{209}{}{Everything is clear with you.}

#Repeat dialog
{210}{}{Hi. Do you need something?}
{211}{}{Ah, my regular customer. I am at your service.}
{212}{}{Do you want more?}
{213}{}{Are you looking for a new dose?}
{214}{}{Didn't you have enough of the last portion? I'll do more for you.}
{215}{}{I knew you'd be back. What kind of high will you try today?}

{216}{}{See you.}
{217}{}{Bye.}
{218}{}{Don't talk too much. See you later.}
{219}{}{We didn't see each other. Later.}

#Rude response and going into battle
{220}{}{Listen to me carefully, estupida. There are people behind me who *own* this area. And who are you to set your own rules here? Do you think they'll just let it go? Don't make any noise, otherwise, there will be problems.}
{221}{}{I don't care, you're going to die anyway.}
{222}{}{Sorry, that was stupid. No problem, bro.}
{223}{}{Dude, you're starting to get on my nerves. Calm down, otherwise, I'll call my guys.}
{1223}{}{Lady, you're getting on my nerves. Calm down, otherwise, I will introduce you to my palm.}
{224}{}{Come on, bitch! Come on!}
{225}{}{Sorry, no need to call anyone. I'm already calming down.}
{226}{}{You're crazy! Die, pendejo!}
{1226}{}{You're crazy! Die, pendeja!}
{227}{}{Die yourself, faggot!}
{228}{}{You need to be subdued.}

#Questions
{230}{}{So what kind of medicines are you selling?}
{231}{}{And what do you need? Tell me, I can get a stimpack, Radawaye, or... (winks) something more serious. Do you understand?}
{232}{}{I'll keep that in mind. See you later.}
{233}{}{But where did you get all this chemistry from?}
{234}{}{More serious? Like buffout and psycho?}
{235}{}{I'm sorry, but the fire worshippers forbade me to sell such goods. They buy all the army drugs themselves.}
{236}{}{But why did they need old army drugs?}
{237}{}{They hide behind caring for the residents of the city... look, I really don't know why they do this, but I don't want to go against the rules. However... (goes into a whisper)}
{238}{}{Yes?}
{239}{}{I have a lot of connections. For a modest reward of 100 caps, I can become your dealer. But this has to stay between us. Do you understand?}
{240}{}{I'll think about your offer.}
{241}{}{Yes, you are a danger to society. You need to be eliminated urgently.}
{242}{}{Not so fast. First, tell me where you got all this chemistry from.}
{243}{}{Here are the bottlecaps. Now show everything you hide from ordinary customers.}
{244}{}{We've been through this before. So do you need dope or not?}
{245}{}{No, not today.}
{246}{}{By the way, where do you get this chemistry from?}
{247}{}{I'm a Follower. Do you want the Cathedral to know about your deceptions? I can arrange it.}
{248}{}{Wait, don't rush! Why these fatal measures? We can always agree.}
{249}{}{Then I'm counting on full service.}
{250}{}{S-listen, m-seth was shaking me. Don't break off and give treats!}
{251}{}{I need any dope that will allow me to win fights in the arena.}
{252}{}{Forget. The sectarians have big problems now, they are not up to your nonsense.}
{253}{}{I'll be honest, I'm interested in your product.}
{254}{}{Stay away from me.}
{255}{}{Orris advised me to contact you.}
{256}{}{Show me what you have.}

{260}{}{Damn, I have everything I need. Don't worry, you'll feel good now...}
{261}{}{Ugh, my eyes are running away from the choice. Now I will know where to buy dope.}
{262}{}{Another thing. But don't you dare talk? This will be our little secret.}
{263}{}{I don't see the point in that. I don't need third parties for sales.}
{264}{}{I'll be back later.}
{265}{}{You're just a fool. Bye.}
{266}{}{Then I'll break your fingers.}

{270}{}{Where did you get all this chemistry from?}
{271}{}{From different places, obviously. I buy something from scavengers, something from caravans from the south, and I cook some preparations myself on the stove. Don't worry, everything is sterile.}
{272}{}{Doesn't sound very reliable, don't you think?}
{273}{}{Calmly. Chemistry is almost without impurities. You can't find the best dope in the city... Except, perhaps, the Followers of Fire. But they don't share it with anyone.}
{274}{}{And what kind of "dope" do you sell?}
{275}{}{Almost? I need *really* quality medicines.}
{276}{}{I'm telling you - I have the best chemistry. If you don't trust me, then get out of here.}
{277}{}{Okay, okay, I'm leaving...}
{278}{}{Just try to be rude to me again - you will be left without teeth.}
{279}{}{I need *really* high-quality medicines. The lives of my patients depend on it.}
{280}{}{So you're a doctor? That was the place to start. Doctors in our time can be counted on our fingers, and I am glad of any such meeting. Don't worry, I'll give you the best. And also at a discount.}
{281}{}{Thank you, colleague, this will help me.}
{282}{}{Another thing.}
{283}{}{It's still too doubtful. I'm leaving.}
{284}{}{I'm from Murphy. And I need medicine for eternal sleep.}
{285}{}{I don't know why you need it, and I don't want to know. But I have poison from the tail of a radscorpion and various drugs for overdose. Choose what you have enough caps for.}
{286}{}{Let's see...}
{287}{}{But if anyone asks, I have nothing to do with it.}
{288}{}{OK.}

{290}{}{What's your name?}
{291}{}{Call me Gonzalez.}
{292}{}{I doubt that's your real name.}
{293}{}{Ha. What an insight. What's it to you?}
{294}{}{But why such secrecy?}
{295}{}{There are those who don't like my business. Competitors, fuck them. Or those sectarians from the Cathedral. They want to take over the entire turnover of medicines for themselves, and dealers like me are paid pennies. It's more profitable for me to work for myself, but you can't explain it to them.}
{296}{}{If not from Followers, then where do you get the drugs?}
{297}{}{Working for yourself in such a place is a risky business.}
{298}{}{Damn, don't twist my balls. Do you know the Red Cardinals? They are usually cleaned in the old building of the sports club. Orris is their leader. He makes sure that nothing interferes with my business. Not for free, of course.}
{299}{}{Damn, don't twist my balls. I used to be protected by Orris's guys. But his death hurt my business. I don't know how I'm going to survive now.}

#Drug addict died at the hands of GG
{300}{}{They say you killed Larry. Why the hell are you killing my clients?}
{301}{}{I'm ridding the world of garbage. Any problems?}
{302}{}{Then do it somewhere else! Larry, even though he was trash, but he had periods of epiphany. At such moments, he managed to earn caps and then lowered them to a new batch of dope. I had a good income from this, do you understand? And what will I have with a cold corpse?}
{303}{}{Eh, what?}
{304}{}{I don't care.}
{305}{}{Um-M... Remember, it will cost you dearly. I will take my lost profit from our transactions.}
{306}{}{So now I won't be able to count on discounts? Sorry to hear that.}
{307}{}{I'm not going to shop at your shady shop anyway. Bye.}
{308}{}{Sorry, it happened by accident.}
{309}{}{Excuse me? You killed my client and say I'm SORRY?! You son of a bitch, do you think I'm just going to let it go?}
{1309}{}{Excuse me? You killed my client and say I'm SORRY?! You son of a bitch, do you think I'm just going to let it go?}
{310}{}{Uh, yeah.}
{311}{}{What is it, are you looking for a fight?}
{312}{}{This is our business with him.}
{313}{}{ (squinting) What business could you have with Larry?}
{314}{}{It doesn't concern you.}
{315}{}{If I tell you, I'll have to kill you, too.}
{316}{}{Damn, I hate it when someone takes away my clients.}
{317}{}{You mean that junkie... What's his name... Larry?}
{318}{}{Larry. Even though he was trash, he had periods of epiphany. At such moments, I managed to earn light caps on it. And what will I have now?}
{319}{}{You wouldn't be able to make money on someone else's problem for a long time. Think about it.}

{320}{}{With those guys who took your bike, you should be careful. They're from the Red Cardinals gang, and this gang practically owns this neighborhood. Make one of them angry, and you won't live. But of course, it's yours.}
{321}{}{I'll take that into account.}
{322}{}{I have a package for you from the Blue Shields.}
{323}{}{Finally. Give it here. I've been waiting. Do you know how hard it is to get hydrocarbons?}
{324}{}{Eh, how?}
{325}{}{No matter. Here, take the finished product. And tell your people that because of the fire worshippers, it's getting harder to do dope.}
{326}{}{Bye.}
{327}{}{There was an overlay with the last courier. You know how hard it is to cross the tenth highway.}
{328}{}{Well yes. And how to make dope without raw materials, stupid? Okay, here's the finished product. Give it to Rio, let him take care of the courier before the fire worshippers shut down my shop.}
{329}{}{Bye.}

{330}{}{Are you supplying drugs to Larry?}
{331}{}{If not me, then someone else. What's it to you?}
{332}{}{You're right. None.}
{333}{}{Then don't poke your nose into other people's business.}
{334}{}{Uh, okay...}
{335}{}{The residents of the house are dissatisfied with this.}
{336}{}{Let them figure it out for themselves. It's not my problem, it's Larry's problem. I'm just selling him medicine.}
{337}{}{Medications? Really?}
{338}{}{Well, you know, he was feverish from a wasteland disease. So he turned to me for treatment. How can I refuse urgent care to those in need?}
{339}{}{How "nice" of you. Bye, doc.}
{340}{}{If you sell him at least one more dose, you're in big trouble.}
{341}{}{What did you say? Say it again, asshole, maybe I misheard?}
{1341}{}{What did you say? Repeat, bitch, maybe I misheard?}
{342}{}{Uh, we need to calm down a little. Goodbye, friend.}
{343}{}{I repeat it only once. Stop bullying Larry. Or you will die.}
{344}{}{Sorry, I got confused. Of course, Larry won't get a single dose from me. No problem.}
{345}{}{I'll see to it.}
{346}{}{I don't recommend it. Arguing with me is the same as arguing with Orris.}
{347}{}{Oh, so you're one of the cardinals now? Now, uh, I'll know. Just, uh, don't strain yourself, friend.}
{348}{}{That's right.}
{349}{}{Now Larry is under my protection. And therefore, under the patronage of Don Diego.}
{350}{}{I can tell Aaron about your business at any time. You're lucky I haven't done it yet.}
{1350}{}{I can tell Aaron about your business at any time. You're lucky I haven't done it yet.}