{100}{}{You see a pusher.}
{101}{}{You see a man who sells drugs.}
{102}{}{The pusher has increased the prices of his goods.}
{103}{}{You have received a discount for the pusher's goods.}
{104}{}{Careful with that, baby. It's almost like you're looking for serious trouble.}

#First encounter
{200}{}{Hey, buddy, you're look like a million. Don't you want to relax in this city before Fortune turns it's back on you?}
{1200}{}{Hey, you, you're look like a million. Don't you want to relax in this city before Fortune turns it's back on you?}
{201}{}{What exactly are you offering?}
{202}{}{Different kinds of pleasure. Just swallow this pill and you'll get rush no game can give you. I know what I'm talking about. I tried it myself.}
{203}{}{So, you sell drugs or something?}
{204}{}{I doubt you can give me anything worth my money.}
{205}{}{Well, of course, whatever you say. But really, you're just refusing the last kind of happiness this shitty world has to offer.}
{206}{}{Happiness? Well, well, well, why didn't you start with that?}
{207}{}{What are you trying to make me buy?}
{208}{}{I have no idea what you're talking about. I only have completely clean stimpaks and mentats. Who in their right mind would call them drugs? It's all about how you use them. But that (wink) is none of my business.}
{209}{}{I see.}

#Repeated dialogue
{210}{}{Hi. You need something?}
{211}{}{A-a-ah, my regular client. I am at your service.}
{212}{}{Want some more?}
{213}{}{You're for another dose, right?}
{214}{}{Previous one not enough for you? I'll give you some more.}
{215}{}{I knew you'd come back. What do you wanna try today?}

{216}{}{See you later.}
{217}{}{Bye.}
{218}{}{Don't say anything about this to anyone. Goodbye.}
{219}{}{We didn't see each other. Bye.}

#Rude reply and entering combat
{220}{}{Now listen to me carefully, estupida. I'm backed by people who *own* this region. Who the hell are you to go here and set up your own rules? You think they'll just shrug their shoulders at this? Be quiet, or there will be trouble.}
{221}{}{I don't care. You're dead either way.}
{222}{}{Sorry, that was stupid. No problem, bro.}
{223}{}{Dude, you are seriously starting to get at my nerves. Calm down or I'll bring over my friends.}
{1223}{}{Lady, you are seriously starting to get at my nerves. Calm down or I'll familiarize you with my hand.}
{224}{}{Do it, bitch. I dare you.}
{225}{}{I'm sorry. There's no need to bring over any of your friends. I'm calming down already.}
{226}{}{You're insane! Die, pendejo!}
{1226}{}{You're insane! Die, pendeja!}
{227}{}{Go die yourself, you fuck!}
{228}{}{You must be pacified.}

#Questions
{230}{}{So, what medicine do you sell?}
{231}{}{What is it you need? Tell me, I can get you a stimpak, radaway... or (winks) something more serious. If you know what I mean.}
{232}{}{I'll keep that in mind. See ya.}
{233}{}{But where are all these things coming from?}
{234}{}{More serious? Like buffout and psycho?}
{235}{}{Sorry, but the Fire-worshippers have forbidden me from selling that stuff. They buy all the military drugs for themselves.}
{236}{}{But why would they need old military drugs?}
{237}{}{They say it's for the "welfare of the city's inhabitants", but that's obviously an excuse... Listen, I really have no idea why they need that stuff, and I don't want to go against the rules. However... (starts whispering)}
{238}{}{Yes?}
{239}{}{I have many connections. For a small price of just 100 caps I could become your personal dealer. But that will have to stay between us. Understand what I mean?}
{240}{}{I'll think about your offer.}
{241}{}{You're a danger to society. You must be dealt with immediately.}
{242}{}{Not so fast. First, tell me, where do you get all this stuff from?}
{243}{}{Here are the caps. Now show me everything you hide from your usual clients.}
{244}{}{We already talked about that. So, do you need the stuff or not?}
{245}{}{No, not today.}
{246}{}{By the way, where do you get all this stuff from?}
{247}{}{I'm from the Followers. You want everyone in the Cathedral to learn of your deceit? I could arrange that.}
{248}{}{Wait, wait! Why resort to such extreme measures when we can always talk like reasonable people?}
{249}{}{I'm expecting full service.}
{250}{}{L-listen, I-I'm sh-haking. Don't just stand there, give me some of that goodness!}
{251}{}{I need anything that could help me win fights in the arena.}
{252}{}{Forget it. The cultists have bigger problems than you selling drugs now.}
{253}{}{I'll tell you this - I was intersted in your product right away.}
{254}{}{Stay away from me.}
{255}{}{Orris told me to go talk to you.}
{256}{}{Show me what you got.}

{260}{}{Damn, I have everything you need. Don't worry, you'll start feeling better right away...}
{261}{}{Oof, I'm overwhelmed with how much there is. I'll know where to buy that kind of stuff in the future.}
{262}{}{Now we're talking. But don't even think about telling anyone. This will remain our little secret.}
{263}{}{Don't see the point. I have no use for third parties.}
{264}{}{I'll be back.}
{265}{}{You're just an idiot. Bye.}
{266}{}{Then I'll break your fingers.}

{270}{}{Where are all those drugs coming from?}
{271}{}{From various places, obviously. Some of them I buy from scrappers, some from the southern caravans, and others I make myself on the stove. Don't worry, it's sterile there.}
{272}{}{Doesn't sound too comforting, don't you think?}
{273}{}{Relax. The drugs are almost fully clean. You can't find better drugs anywhere else in the city... Well, except for the Followers, I suppose. But they don't share with anyone.}
{274}{}{So what kind of "drugs" do you sell?}
{275}{}{Almost? I need *really* quality medicine.}
{276}{}{I'm telling you - I've got the best stuff in the city. Don't believe me - get outta here.}
{277}{}{Fine, fine, I'm getting out...}
{278}{}{Just you try being rude to me again - suddenly your teeth are going to be missing.}
{279}{}{I need *really* quality medicine. The lives of my patients depend on it.}
{280}{}{So you're a doctor? Why didn't you tell me right away? Doctors in our time truly are rare, I'm happy to meet one. Don't worry, I'll give you the best. With a discount, I might add.}
{281}{}{Thanks, colleague, this will help.}
{282}{}{Now we're talking.}
{283}{}{Still too suspicious. I'm leaving.}
{284}{}{I'm here on behalf of Murphy. I need sleep aid. For the permanent kind of sleep.}
{285}{}{I don't know why you need this, and I don't want to know. But I have radscorpion poison and other drugs that can cause a fatal overdose. Choose which ones you can afford.}
{286}{}{Let's take a look...}
{287}{}{But if anybody comes asking - I never even heard of you.}
{288}{}{Okay.}

{290}{}{What's your name?}
{291}{}{Call me Gonzalez.}
{292}{}{I doubt it is your real name.}
{293}{}{Heh. Such insight. Why do you care?}
{294}{}{Why the secrecy?}
{295}{}{There are those who do not like my business. Competition, damn them. Or those cultists from the Cathedral. They want to take all medicine for themselves, and pay dealers like me mere percentages. It's more profitable to work for yourself, but you can't explain that to them.}
{296}{}{If not from the Followers, who are you getting this stuff from?}
{297}{}{To work for yourself in such a place is risky business.}
{298}{}{Damn, stop twisting my balls. You know the Red Cardinals? They usually hang out in that old sports club building. Orris is their leader. He makes sure nothing stands in the way of my business. Not for free, of course.}
{299}{}{Damn, stop twisting my balls. In the past, Orris' guys covered me. But his death hit my business hard. I don't know how I'm going to survive now.}

#Drug addict is killed by player
{300}{}{They say you killed Larry. Why in the goddamn are you reducing my number of clients?}
{301}{}{The world is full of trash, and I'm the garbageman. Problem?}
{302}{}{Then do it somewhere else! Larry may have been trash, but he had moments of epiphany. In these moments, he managed to earn caps and then used them on another dose of drugs. I had a decent income from that, get it? Now what will I get from a cold corpse?}
{303}{}{Uhh, I dunno. What *will* you get?}
{304}{}{I don't give a shit.}
{305}{}{Um-m... Remember, you will pay for this. I'll take the lost profit from your purchases.}
{306}{}{So now I won't be able to receive discounts? How sad.}
{307}{}{I wasn't planning on buying anything in this suspicious place anyways. Bye.}
{308}{}{Sorry, it just kinda happened.}
{309}{}{Sorry? You killed my client and you say SORRY?! You fucking piece of shit, you think I'll just leave it at that?}
{1309}{}{Sorry? You killed my client and you say SORRY?! You fucking piece of shit, you think I'll just leave it at that?}
{310}{}{You aren't?}
{311}{}{What, you looking for a fight?}
{312}{}{Personal business. It's between us.}
{313}{}{(squinting) What business could you have had with Larry?}
{314}{}{Not the kind that's yours.}
{315}{}{I'd tell you, but then I'd have to kill you too.}
{316}{}{Fuck, I hate it when someone takes my clients away from me.}
{317}{}{You talking about that drug addict? What was his name... Larry, right?}
{318}{}{Yeah, Larry! He may have been trash, but he had moments of epiphany. And in those moments I could make easy caps. What will I have now?}
{319}{}{Profiting off other people's personal problems would never be a long-term source of income. Get over it.}

{320}{}{Careful with those guys that took your bike. They're from the Red Cardinal gang, they practically own this region. You anger one of them - you're already dead. But that's your business, of course, not mine.}
{321}{}{I'll keep that in mind.}
{322}{}{I've got a package for you, from the Blue Shields.}
{323}{}{Finally. Give it to me. I've waited too long for this. Do you have any idea how hard it is to acquire hydrocarbons?}
{324}{}{Uhh, how?}
{325}{}{Forget it. That's not important. Here, take the product. And tell your guys that because of the Fire-worshippers, it's getting harder and harder for me to produce this kind of stuff.}
{326}{}{Bye.}
{327}{}{There was a problem with the previous courier. You know how hard it is traveling across the 10th highway.}
{328}{}{Yeah. And how exactly do you make something without the raw ingredients, dumbass? Fine, here, take it. The product. Give it to Rio, let him take care of the courier before the Fire-worshippers close down my little enterprise.}
{329}{}{Bye.}

{330}{}{Are you supplying Larry with narcotics?}
{331}{}{If not me, somebody else would. What's your problem?}
{332}{}{You're right. It's not.}
{333}{}{Then don't interfere with other people's business.}
{334}{}{Uhh, okay...}
{335}{}{Others are dissatisfied with this situation.}
{336}{}{Why don't they deal with that themselves? It's not my problem, it's Larry's problem. I'm just selling him medicine.}
{337}{}{Medicine? Really?}
{338}{}{Well, you know, he had fever from some wasteland disease. So he asked me to heal him. And could I refuse someone in dire need of medical assistance?}
{339}{}{How very kind of you. Bye, doc.}
{340}{}{If you sell him even one more dose, you'll be in big trouble.}
{341}{}{What did you just say? Say it again, idiot, maybe I misheard?}
{1341}{}{What did you just say? Say it again, bitch, maybe I misheard?}
{342}{}{We need to calm down a bit. Goodbye, friend.}
{343}{}{I'll repeat myself only once. Stop poisoning Larry. Or you're dead.}
{344}{}{Oh, sorry, I don't know what I was thinking. Of course, Larry won't receive another dose from me. No problem.}
{345}{}{I'll make sure of that.}
{346}{}{I don't recommend doing that. To argue with me is to essentially argue with Orris.}
{347}{}{Oh, so now you're one of the Cardinals? I'll, uhh, keep that in mind from now on. Just, uhh, calm down, friend.}
{348}{}{Damn right.}
{349}{}{Larry is now under my protection. And thus, under the protection of Don Diego.}
{350}{}{I could tell Aaron what you're doing at any moment. Maybe I should go do that right now. What do you think?}
{1350}{}{I could tell Aaron what you're doing at any moment. Maybe I should go do that right now. What do you think?}