{100}{}{You see a racketeer.}
{101}{}{You see an ordinary bandit. He is very determined.}
{102}{}{All right! We're leaving! It's okay, don't get excited!}

{110}{}{Where are you going? Get out, this is our territory now.}
{111}{}{You only know how to scare. Prove your right to own this place, you piece of shit.}
{112}{}{Oh, I'm sorry...}
{113}{}{Please leave, the locals don't want problems...}
{114}{}{Then you will GET them! Got it? Get lost, you moron piece, while your legs are intact!}
{115}{}{You're in the Cardinals' territory. They don't tolerate competitors. Get lost.}
{116}{}{The Cardinals have been squabbling for a long time. Where do you see them?}
{117}{}{No matter. I'm going to clean up here now. Out!}
{118}{}{The cardinals still rule the area. Get out.}
{119}{}{Ar-r-r! (grinning, waving his fists, and backing away to the exit)}
{120}{}{Yes, right outside. And don't come back, morons...}
{121}{}{Guys, here are 100 caps for you. Just don't touch us, okay?}
{122}{}{You see. I just needed MOTIVATION. See you next month, morons.}
{123}{}{Yes, uh, bye...}