{100}{}{You see a Phoenixian.}
{101}{}{You see a regular inhabitant of Phoenix. He looks nervous and is clearly waiting for someone.}
{102}{}{Go on your way.}

{200}{}{What's the rush, cultist? You want to run away from the city? Smart move. We'll help you.}
{201}{}{Really? That's very kind of you...}
{202}{}{You're confusing me with someone else.}
{203}{}{We know that you're from the Fire-worshippers. And you know what? We won't tolerate your "atomic magic" here any longer. Get out of the city, scum.}
{204}{}{You got the wrong guy. I'm not a member of the Fire-worshippers anymore.}
{205}{}{Shut up! After the explosion in the cathedral, half the city's destroyed and a real war has begun between people here. We won't rest until there are no cultists in this city, current or former. Got it?}
{206}{}{Yes, got it.}
{207}{}{Now get out of the city. You take a step here again - and you're dead.}
{208}{}{Uhh...}
{209}{}{No, I didn't. You mumble so much that I barely understood you. Explain it to me again.}
{210}{}{I'll explain everything to you right here, scum...}
{211}{}{Uhh, what are you doing?}
{212}{}{Attack one by one, boys.}
{213}{}{Wait, folks. You and I - we're not so different. We're on the same team! You see, it's thanks to me that the church has been consumed by that big hole.}
{214}{}{Wh... Do you think I'm an idiot? No one is going to believe *that*.}
{215}{}{That would be a mistake. These cultists sponsored slavers that abducted my relatives. The explosion was my revenge.}
{216}{}{Uh-uh... Too perfect to be true. But if it is, then the destruction happening all across Phoenix is your fault. Get outta here. You go back - and you're dead. Got it?}
{217}{}{No problem. You won't see me ever again.}
{218}{}{You shouldn't threaten me. Otherwise, someone else is going to be dead. Someone in front of me.}
{219}{}{I don't give a shit about what you believe.}
{220}{}{Looks like this sucker doesn't understand words. We'll have to use fists now...}
{1220}{}{Looks like this bitch doesn't understand words. We'll have to use brute force now...}
{221}{}{Be gentle, boys...}
{222}{}{This will be the last mistake you'll ever make.}
{223}{}{You threaten me. I should have expected that. Those that threaten me don't live long enough to warn others.}

{230}{}{Hey, you. Your burned skin.}
{231}{}{Yeah? What about it?}
{232}{}{Who did this to you? I heard there were experiments to create elite fighters beneath the Cathedral. And you were last seen in the cathedral.}
{233}{}{This must be a mistake. I'm simply a victim of radiation. I was searching for a cure in there.}
{1233}{}{This must be a mistake. I'm simply a victim of radiation. I was searching for a cure in there.}
{234}{}{Maybe... We're looking for remnants of the cultists to drive them out of the city. So don't get in our way.}
{235}{}{Of course. I won't obstruct justice.}
{236}{}{Hm... (looks at you from head to toe, not even bothering hiding the disgust) You can go.}
{237}{}{...}
{238}{}{A man like me has a hard time hiding. What do you have against the Fire-worshippers?}
{239}{}{We're expunging all cultists from the city. This is no place for them here after the destruction of the Cathedral. Neither is there place for you.}
{240}{}{Why so rude? Did the Fire-worshippers not teach tolerance and love?}
{241}{}{Maybe in their speeches. Meanwhile, they were preparing a damn nuclear bomb inside their dark underground lair. There is no trusting people like that... In any case, you are not welcome here. Get outta the city, you atomic junk.}
{242}{}{Can't argue with that. Good luck, boys.}
{243}{}{I'll tear out your eyes and suck your brains out from your skull for these words.}
{244}{}{Looks like this thing doesn't understand words. Guys...}
{245}{}{Hey, there is no need for violence...}
{246}{}{You ghoul-haters are all the same.}
{247}{}{Exactly. I'm a victim, not a cultist.}
{248}{}{I don't believe you. Guys, don't let it escape...}
{1248}{}{I don't believe you. Guys, don't let it escape...}
{249}{}{Don't touch me! You'll... uhh... melt!}
{250}{}{Maybe... Fine, go. But if we learn you really are a Fire-worshipper, you'll be burned at the stake with all the others.}

{260}{}{Wait. I don't want to get involved in a fight, but I want to say. We know that you're a former Fire-worshipper. These kind of people aren't welcome in this city now. Go away and do not return. If you do, none of this ammunition will save you from retribution.}
{261}{}{I understand. You won't see me ever again. Goodbye.}
{262}{}{I'm not going anywhere. Who's going to stop me?}
{263}{}{(nervously look at each other) We don't want a fight. Yet. But if we need to, we'll set one up. Get out of the city by the next day.}
{264}{}{Not so fast, pussy. *I* want a fight. Right here, right now.}
{265}{}{You're confusing me with someone else.}
{266}{}{Oh really? I don't think so. Get out of the city. We don't want a fight, but if we need to - we'll set one up.}
{267}{}{Fuck it. Let's have a fight.}
{268}{}{I'll think about your words.}