{100}{}{You see a racketeer.}
{101}{}{You see a regular bandit. He looks quite determined.}
{102}{}{Fine! We're leaving! It's all good, don't get angry.}

{110}{}{What are you doing here? Scram, this is now our territory.}
{111}{}{The only thing you can do is frighten. Prove me your right to own this place, you piece of shit.}
{112}{}{Oh, I'm sorry...}
{113}{}{Please go away. The locals don't want problems...}
{114}{}{Then you'll GET THEM! Got it? Get the fuck out of here, you stupid piece of shit, while your legs are still intact!}
{115}{}{You're on Cardinal territory. They don't tolerate any competition. Scram.}
{116}{}{The Cardinals aren't a relevant organization here anymore. You see signs of their presense here? Where?}
{117}{}{That's completely irrelevant. I'm gonna clean things up here. Out!}
{118}{}{The Cardinals still control this region. Get outta here.}
{119}{}{Ar-r-rgh! (shows teeth, waving his fists and backing towards the door)}
{120}{}{Yeah, out onto the streets. And don't come back, idiots...}
{121}{}{Take these 100 caps. Just don't hurt the locals.}
{122}{}{See? All that was needed was some MOTIVATION. See you next month, idiots.}
{123}{}{Yeah, uhh, bye...}