{100}{}{You see a Phoenician.}
{101}{}{You see an ordinary citizen of Phoenix. He seems tense and is waiting for someone.}
{102}{}{Go your own way.}

{200}{}{Where are you in a hurry, sectarian? Decided to get out of town? The right decision. We will help you.}
{201}{}{Really? That's so kind...}
{202}{}{You're confusing me with someone else.}
{203}{}{We know you're a fire worshipper. And you know what? We will no longer tolerate this "nuclear magic" of yours here. Get out of town, scum.}
{204}{}{No, no, I'm not a member of this sect anymore.}
{205}{}{Shut your mouth! After the explosion in the cathedral, half of the city was destroyed, and a real war began among the people. We will not rest until there is not a single sectarian left in the city, active or former. Is that clear to you?}
{206}{}{Yes, it's clear to me.}
{207}{}{Now get out of town. Pop in again and you're dead.}
{208}{}{Uh...}
{209}{}{No, I don't understand. Explain it again, stupid.}
{210}{}{Now I'll explain everything, scum...}
{211}{}{What are you doing... stop...}
{212}{}{Attack one at a time, guys.}
{213}{}{Wait, guys. We're in this together. It was thanks to me that the church was swallowed up by a big hole.}
{214}{}{Thu... Do you take me for a fool? No one will believe it.}
{215}{}{In vain. These sectarians sponsored the slavers who kidnapped my relatives. The explosion was retribution.}
{216}{}{Yeah... You're singing too sweetly. If that's true, then you're responsible for the destruction all over Phoenix. Do you think this should make us happy? Get out of town. You go back and you're dead. Is that clear to you?}
{217}{}{No problems. You won't see me again.}
{218}{}{But you don't need to threaten me. Otherwise, I'll see a corpse in front of me.}
{219}{}{I don't care what you believe.}
{220}{}{It looks like this little bitch doesn't understand human language. I'll have to explain with my fists...}
{1220}{}{It looks like this bitch doesn't understand human language. We'll have to explain it by brute force...}
{221}{}{Just be gentle, guys...}
{222}{}{This is your last mistake.}
{223}{}{You're threatening me. And those who threatened me ended their lives very quickly.}

{230}{}{Hey, you. Your burnt skin.}
{231}{}{Yes? What about her?}
{232}{}{Who made you like this? I heard that experiments were conducted under the cathedral to create elite fighters. And you were just seen in the cathedral.}
{233}{}{This is some kind of mistake. I'm just a victim of radiation, and I was looking for a cure in the cathedral.}
{1233}{}{This is some kind of mistake. I'm just a victim of radiation, and I was looking for a cure in the cathedral.}
{234}{}{Maybe... We are looking for the remnants of the sectarians to expel them from the city. So don't get caught in the hot hand.}
{235}{}{Of course, I will behave peacefully.}
{236}{}{Hmm... (looks around from head to toe, expressing undisguised disgust) You can go now.}
{237}{}{...}
{238}{}{ It's hard for a person with my face to hide. What do you have against fire worshippers?}
{239}{}{We are eradicating all sectarians in the city. After the explosion in the cathedral, they have no place here. And you too.}
{240}{}{Why so much rudeness? Didn't the fire worshippers teach patience and love?}
{241}{}{In words, maybe. But they were preparing a nuclear bomb in their dark dungeon. There is no faith in such anymore... In any case, you're not welcome here. Get out of town, atomic litter.}
{242}{}{I can't argue with you. Good luck, guys.}
{243}{}{For such words I will tear out your eyes and suck the brains out of your cooling skull.}
{244}{}{It seems that this creature does not understand human language. Guys...}
{245}{}{Oh, no violence...}
{246}{}{You gulen-haters are all the same.}
{247}{}{Exactly. I am a victim, not a sectarian.}
{248}{}{I don't believe you. Guys, don't let him escape...}
{1248}{}{I don't believe you. Guys, don't let her escape...}
{249}{}{Just not in the face...}
{250}{}{Maybe so... Okay, go ahead. But if we find out that you are a fire worshipper, then you will burn at the stake with the others.}

{260}{}{Wait. I don't want to get into a fight, but I have to say it. We know that you are a former fire worshipper. In this city, such people are no longer welcome. Go away and don't come back. If you come back, all this ammunition will not save you from retribution.}
{261}{}{I understand. You won't see me again. Goodbye.}
{262}{}{I'm not going anywhere. Who dares to stop me?}
{263}{}{(they look at each other nervously) We don't want a fight. We don't want to yet. But if necessary, we will arrange it. So that you won't be here tomorrow.}
{264}{}{Not so fast, pussy. Whether you like it or not, the fight is going to happen right now.}
{265}{}{You're confusing me with someone else.}
{266}{}{Really? I don't think so. Get out of town. We don't want a fight, but if necessary, we will arrange it.}
{267}{}{Spit. Let's fight.}
{268}{}{I'll think about your words.}