{100}{}{You see a refugee from Flagstaff.}
{101}{}{You see a person in dust-covered clothes. Looks like she traversed great distances before ending up here.}
{102}{}{*Cries in response*}
{103}{}{Thank you, you're saving me from starvation.}
{104}{}{Don't you even dare come close to me, you freak.}
{1104}{}{Don't you even dare come close to me, you freak.}
{105}{}{What the hell is going on here?!}

{110}{}{Why are you doing this to us?}
{111}{}{We've known each other since childhood.}
{112}{}{I promise you I'll get the caps, just wait a bit.}
{113}{}{I know how to earn enough money to pay rent.}
{114}{}{Right now I haven't got anything to pay with, but this is only a temporary state of affairs.}
{115}{}{Give me a chance, I'll earn you caps.}
{116}{}{I'm telling you, I'll FIND a job.}
{117}{}{Listen, I don't want to argue with you.}
{118}{}{So that's how it is, someone's still angry about that, huh?}
{119}{}{Let me spend at least one night here.}

{200}{}{...How can you do this to us? You used to be polite to us. Now we're just bums from the street to you, huh?}
{201}{}{What's going on here?}
{202}{}{This arrogant couch potato wants to evict us, his old friends. We don't have enough caps to pay rent, but that's only a temporary problem that will be resolved when we find a job.}
{203}{}{So you came from afar?}
{204}{}{Actually, we're locals, but the last few years we worked in Flagstaff. After the uranium mine there was closed, many lost their jobs, and civil unrest started in the town. We had to go back. The trek was hard, and the caps quickly ended.}
{205}{}{Everything comes to an end eventually.}
{206}{}{A tragic story.}

{210}{}{Listen, could you give me 10 caps? I'll give them back as soon as I earn enough, I promise.}
{211}{}{I've got problems with caps too, sorry.}
{212}{}{Yes, of course, everyone has their problems. It's okay, I'll deal with it somehow.}
{213}{}{Bye.}
{214}{}{Looks like you really do need caps. Here, take them.}
{215}{}{Alright, here, take 'em.}
{216}{}{Really? (hides caps quickly) Oh, thank you, stranger. What's your name?}
{217}{}{It is of no concern. I'm just trying to do what's right. Goodbye.}
{218}{}{}
{219}{}{. Remember that name. Tell your children about me.}

{220}{}{I'll give you 35 caps on the condition that you will provide me with a small service. You see, I need some "bedside relaxation".}
{221}{}{(Lowers her gaze, depressed from the taunts of an observant manager)}
{222}{}{So, what do you say?}
{223}{}{Fine, forget it. It's obvious it's not going to work out.}
{224}{}{I still have some pride left. Don't even dare say something like this ever again, you fuck!}
{225}{}{Hey, easy.}
{226}{}{When I was living in the colony, I never would have thought I would have to earn money this way.}
{227}{}{Everything happens for the first time, eventually. Let's move, we'll find ourselves a nice place.}
{228}{}{Sorry, that was a terrible idea. Forget it. As for me, I should probably just go...}
{229}{}{(after an hour of dirty violence you rise from the bed full of satisfaction and look at the limp body below; you take out the caps and silently throw them onto the dirty sheets; the woman turns her back on you and starts to silently cry)}
{230}{}{[Leave]}