{100}{}{You see a refugee from Flagstaff.}
{101}{}{You see a man in dusty clothes. It looks like he traveled a long distance before he got here.}
{102}{}{*Sobbing in response*}
{103}{}{Thank you, you're saving me from starvation.}
{104}{}{Don't you dare come near me, you pervert.}
{1104}{}{Don't even dare come near me, pervert.}
{105}{}{What's going on here?!}

{110}{}{Why are you doing this to us?}
{111}{}{We've known each other since childhood.}
{112}{}{I promise there will be caps, just wait a bit.}
{113}{}{I know how to earn my rent.}
{114}{}{Now I have nothing to pay with, but it won't be for long.}
{115}{}{Give me a chance, I'll earn caps.}
{116}{}{I'm telling you - I'll FIND a job.}
{117}{}{Listen, I don't want to fight with you.}
{118}{}{That's it, someone still has a grudge, huh?}
{119}{}{Let me stay at least one night.}

{200}{}{...How can you? You used to be nice to us. And now we are people from the street for you, eh?}
{201}{}{What's going on here?}
{202}{}{This arrogant homebody is going to evict us, his old friends. We don't have enough rent caps. But this is a temporary problem until we find a job.}
{203}{}{So you came from far away?}
{204}{}{Actually, we're local, but we've been working in Flagstaff for the last few years. After the uranium mine closed there, many lost their jobs, and riots broke out in the city. We had to go back. The way was hard, and the bottlecaps quickly ran out.}
{205}{}{Everything comes to an end sometime.}
{206}{}{A sad story.}

{210}{}{Listen, can I borrow ten caps? I'll give it back as soon as I earn it, honestly.}
{211}{}{I also have problems with caps, sorry.}
{212}{}{Yes, of course, everyone has their problems. Nothing, I'll figure it out somehow.}
{213}{}{Bye.}
{214}{}{Looks like you need the bottlecaps. Here, take it.}
{215}{}{Okay, here you go.}
{216}{}{Really? (quickly hides the bottlecaps) Oh, thank you, kind man. What's your name?}
{217}{}{It doesn't matter. This is how I try to atone for past sins. Goodbye.}
{218}{}{My name is }
{219}{}{. Remember that name. And tell your children about me.}

{220}{}{I'll give you 35 caps, but on condition of a small favor. You see, I need a little "rest in bed".}
{221}{}{(Dejectedly lowers his gaze under the ridicule of the observant manager)}
{222}{}{What do you say?}
{223}{}{Okay, forget it. We won't have a relationship.}
{224}{}{I still have some pride left. Don't even dare say that, you ugly thing!}
{225}{}{Hey, take it easy.}
{226}{}{Living in a colony, I would never have thought that I would have to earn this way.}
{227}{}{Everything happens for the first time sometime. Move your hips, now we'll find a secluded place.}
{228}{}{Sorry, it was a bad idea. Forget it, let me just leave...}
{229}{}{ (after an hour of dirty violence, you get out of bed with satisfaction and look at the limp body below; you take out the bottlecaps and silently throw them on the dirty sheet; the woman turns away and begins to sob quietly)}
{230}{}{[Leave]}