{100}{}{You see a ghost!}
{101}{}{You see... the soul of a people who burned up in an atomic blast.}

{102}{}{What the hell is this?}
{103}{}{This wasn't real. It better not be.}
{104}{}{Am I going insane... Or what?}
{105}{}{These souls - they're everywhere!}

{110}{}{Look at what you did!}
{111}{}{You're guilty of this!}
{112}{}{Why did you do this to us?}
{113}{}{Why did you murder us?}
{114}{}{We will pursue you your whole life.}
{115}{}{Murderer!}

{1110}{}{Look at what you did!}
{1111}{}{You're guilty of this!}
{1112}{}{Why did you do this to us?}
{1113}{}{Why did you murder us?}
{1114}{}{We will pursue you your whole life.}
{1115}{}{Murderer!}