{100}{}{There's a ghost in front of you!}
{101}{}{You see... the soul of a man burned in a nuclear flame.}

{102}{}{What the hell is this?}
{103}{}{It wasn't real, was it?}
{104}{}{I think I'm going crazy... Or not?}
{105}{}{These souls are everywhere!}

{110}{}{Look what you've done!}
{111}{}{It's your fault!}
{112}{}{Why did you do this to us?}
{113}{}{Why did you kill us?}
{114}{}{We will haunt you all your life.}
{115}{}{The murderer!}

{1110}{}{Look what you've done!}
{1111}{}{It's your fault!}
{1112}{}{Why did you do this to us?}
{1113}{}{Why did you kill us?}
{1114}{}{We will haunt you all your life.}
{1115}{}{The murderer!}