{100}{}{You see a passerby.}
{101}{}{You see a robber.}
{102}{}{You see a passerby in a cloak. Looks like he doesn't want to be noticed until the right moment.}
{103}{}{You see a street robber. It's best not to get in his way.}
{104}{}{You watching me or something?}
{105}{}{The robber cowardly runs away.}

#Dialogue
{200}{}{(Walking along the street, you notice that you are being watched. For some time, an unsure man in stealthy clothes follows you. When you enter an empty alley, he runs up to you and takes out what appears to be a pistol.)}
{201}{}{[Continue]}
{202}{}{Stop! Give me all your caps or I'll shoot.}
{203}{}{Hey, easy...}
{204}{}{Caps! Now! Or I'll swear I'll shoot! (looking over your shoulder you examine your opponent: his face is covered with a headscarf)}
{205}{}{Caps! Now!}
{206}{}{Try and take them, bitch.}
{207}{}{Wh... This is a pistol. It's loaded. Do you understand the situation you are in? Don't make me shoot you.}
{208}{}{Then you'll have to. I'm attacking!}

{210}{}{Here are 30 caps, just don't shoot.}
{211}{}{Give them to me. (takes caps and looks around) Now go along the street. You turn your back - you're dead.}
{212}{}{Whatever you say...}
{213}{}{[Turn around and attack the robber]}
{214}{}{I only have one cap. Here, take it, but I don't have any more.}
{215}{}{Here are two caps. I don't have any more. Really.}
{216}{}{Here are three caps. I don't have any more. Really.}
{217}{}{Dammit, give them to me... There. Now go along the street. You turn your back - you're dead.}
{218}{}{Don't shoot. Here are all the caps I have.}

{220}{}{I have no caps. Really.}
{221}{}{Don't make me mad, bitch, and GIVE ME THE CAPS!}
{222}{}{I really have no caps. Check my pockets.}
{223}{}{Fuck... (looks around stressed) There... Now go along the street and don't turn back.}
{224}{}{Don't come any closer or I'll shoot!}
{225}{}{Whoa, easy.}
{226}{}{So shoot me, bitch.}
{227}{}{You're making me resort to extreme measures, bastard.}

{230}{}{Listen, are you a guy or a gal?}
{231}{}{Wh... Don't make me mad or I'll SHOOT!}
{232}{}{Really. I can't tell because of those rags...}
{233}{}{One more word and you're dead. GIVE ME THE CAPS!}
{234}{}{Uhh, maybe we could talk?}
{235}{}{Then aim for the head. You've got no other choice.}
{236}{}{Damn, who the fuck are you... (robber is nervous and looks around stressed) There... Don't turn around. Or I'll shoot. Really, I'll shoot!}
{237}{}{Of course, I believe you...}
{238}{}{So shoot already, bitch, shoot!}
{239}{}{You're taking a serious risk, kid. You know who I am? The undefeatable Mario died at my hands.}
{240}{}{Dammit... I don't want to shoot you... Fine. Go along and don't turn back. Clear?}
{241}{}{Of course, you're the boss.}
{242}{}{Not so fast. You will have to answer for your words...}
{243}{}{How dare you stop a peaceful monk? The Atomic Flame shall punish you, worm!}
{244}{}{You're pathetic. We highwaymen hang people like you on road signs and let the blood flow.}
{245}{}{Keep in mind that you're aiming at a Ranger. You won't get away with this.}
{246}{}{It's not me, but you who's going to be dead soon.}