{100}{}{There is a passerby in front of you.}
{101}{}{You see a robber.}
{102}{}{You see a passerby in secretive clothes. He does not want to attract attention to himself ahead of time.}
{103}{}{You see a street robber. He better not get in the way.}
{104}{}{Are you following me?}
{105}{}{The robber cowardly escaped.}

#Dialog
{200}{}{(Walking down the street, you notice that you are being followed. For a while, a young man in secretive clothes follows you uncertainly. When you enter a deserted alley, he runs up and pulls out something like a gun.)}
{201}{}{[Next]}
{202}{}{Stop! Give me your caps or I'll shoot.}
{203}{}{Hey, take it easy...}
{204}{}{bottlecaps! Now! Or, I swear, I'll shoot! (looking over your shoulder, you examine your opponent: his face is covered with a handkerchief, ...... )}
{205}{}{bottlecaps! Now!}
{206}{}{Try to take it, bitch.}
{207}{}{Thu... It's a gun. It's loaded. Do you understand? Don't make me shoot.}
{208}{}{So you have to. I'm attacking!}

{210}{}{Here are 30 caps, just don't shoot.}
{211}{}{Give it here. (picks up the bottlecaps and looks around) Now go along the street. If you turn around, you're dead.}
{212}{}{Whatever you say...}
{213}{}{[Turn around and attack the robber]}
{214}{}{I only have one cap. Here, take it, but not anymore.}
{215}{}{Here are two bottlecaps. Not anymore. True.}
{216}{}{Here are three bottlecaps. Not anymore. Really.}
{217}{}{Damn, come here... so. Now walk along the street. Turn around and you're dead.}
{218}{}{Don't shoot. Here are all the bottlecaps I have.}

{220}{}{I don't have caps. True.}
{221}{}{Don't piss me off, bitch, and GIVE ME THE bottlecaps!}
{222}{}{I don't have caps. Check your pockets.}
{223}{}{Damn... (looks around in difficulty) So... Walk along the street and don't turn around.}
{224}{}{Stay back or I'll shoot!}
{225}{}{Whoa, take it easy.}
{226}{}{So shoot, bitch.}
{227}{}{You're forcing me to take extreme measures, you bastard.}

{230}{}{Listen, are you a guy or a girl?}
{231}{}{Thu... Don't piss me off or I'm going TO SHOOT!}
{232}{}{Seriously. Because of these rags, I can't make out...}
{233}{}{One more word and you're a corpse. LET'S GET THE bottlecaps!}
{234}{}{Eh, can we talk?}
{235}{}{Then aim for the head right away. You have no other chance.}
{236}{}{Damn, who are you... (the robber starts to get nervous and looks around in difficulty) So... Don't turn around. Or I'll shoot. Seriously, I'm going to shoot!}
{237}{}{Of course I believe you...}
{238}{}{So shoot, bitch, shoot!}
{239}{}{You're taking a serious risk, baby. Do you know who I am? The invincible Mario fell from my hands in the ring.}
{240}{}{Damn it... I don't want to shoot you... Okay. Go on and don't look back. Understand?}
{241}{}{Of course you're the boss.}
{242}{}{Not so fast. You'll have to answer for your words...}
{243}{}{How dare you stop a peaceful monk? The punishment of the Nuclear Flame will punish you, worm!}
{244}{}{You're pathetic. We, the highway workers, hang the likes of you on road signs and drain the blood.}
{245}{}{Mind you, you've got a ranger in your sights. You won't get away with it that easily.}
{246}{}{Now it's not me, but you who will become a corpse.}