{100}{}{This is Lloyd.}
{101}{}{You see a beggar scurrying down the street in search of food.}
{102}{}{People like this just litter the world.}
{103}{}{Eh, are you talking to me, piece of iron? There must have been something else in that bottle...}
{104}{}{Oh, Lloyd...}

{200}{}{Hey, you look like you're a newbie. And newcomers in the city have a hard time. Want some free advice? Make friends, it's appreciated here.}
{201}{}{What's your name, buddy?}
{202}{}{It's strange to hear this from a homeless beggar.}
{203}{}{I'm Lloyd. A simple street dweller. But make no mistake, I know the whole city like the back of my hand.}
{204}{}{I could use a Phoenix expert. Can you answer a couple of questions?}
{205}{}{And in my opinion, you're just a loser. I don't want to deal with someone like you. Goodbye.}
{206}{}{Hey, you look like you have a lot of caps. I can give you free advice. Share a little thing and you will get grateful and loyal friends in this city.}
{207}{}{Bye, Lloyd.}
{208}{}{See you later, Lloyd.}
{209}{}{You know, I'm not in a hurry.}

{210}{}{Share the cap, you won't regret it.}
{211}{}{Yes, this is my favorite client. How can I help this time?}
{212}{}{Some other time.}

{213}{}{Phew, that was an earthquake! But the rumors did not lie that the sectarians were making a nuclear bomb. Real crazy. Now the whole city has hated them, and I have one less dot to earn. Damn...}
{214}{}{They got what they deserved, Lloyd.}
{215}{}{Yeah.}

{220}{}{Here's the bottle cap.}
{221}{}{Here's the bottle cap. A beginner needs advice.}
{222}{}{Here's the bottle cap. What are you going to tell me this time?}
{223}{}{Here's the bottle cap. Share interesting rumors.}
{224}{}{[Next]}
{225}{}{Thank you, sir.}
{1225}{}{Thank you, señora.}
{226}{}{Thank you, señor. But the advice from old Lloyd is over.}
{1226}{}{Thank you, señora. But the advice from old Lloyd is over.}
{227}{}{Nothing, I understand. After all, I'm a beggar like you. See you.}
{228}{}{Uh, yeah, bye.}
{229}{}{Nothing today. Later.}

{230}{}{Ah, the rumors. That's what I live by.}
{231}{}{(looks around) N-well...}
{232}{}{Lloyd sees everything from this street. That's right.}
{233}{}{You know, I hear a lot here.}
{234}{}{Latest news? I heard something.}
{235}{}{Yeah. I have some advice for you.}
{236}{}{Hmm... (scratches unwashed stubble)}
{237}{}{You know, people talk all sorts of things...}
{238}{}{(humming) Ah, the cap, crack...}
{239}{}{Thank you very much.}

{240}{}{So?}
{241}{}{Go on.}
{242}{}{Speak.}
{243}{}{[Listen]}
{244}{}{[Next]}
{245}{}{What do you say?}

{250}{}{Hi. How do you like my new clothes? I bought them with your caps, so thank you. Sometimes I think I can get out of this hole and start a new life. Although who am I kidding...}
{251}{}{All is not lost, Lloyd. It still won't work to fall lower.}
{252}{}{People like you have no future. Accept it.}
{253}{}{Listen, I earn so much now that I can afford even this little joy. With such a suit, all doors are open to me. And it's thanks to you.}
{254}{}{Listen, I earn so much now that I can afford even this little joy. With this suit, it's time for me to move into the suite. Too bad he's already busy.}
{255}{}{Glad for you, Lloyd.}
{256}{}{I can't believe it. You're just lucky, nothing more.}

# About the Vault
{260}{}{Do you know anything about Vault 27?}
{261}{}{Quite a bit. For 10 caps, I'll tell you what I know.}
{262}{}{Then forget it.}
{263}{}{Here are 10 caps. Tell me.}
{264}{}{I've heard various legends about this Vault. Someone said that the rulers of Phoenix had set up a secret laboratory there. And someone - that the Vault has been inhabited by real ghosts since the day of the nuclear war. Maybe it doesn't exist at all.}
{265}{}{Sorry to hear that.}
{266}{}{If you are going to go in search of this legend, then I advise you to start with the scavenger Bob. He lives in a slum east of here and knows the Phoenix neighborhood like no one else.}
{267}{}{Thank you, you helped me a lot.}
{268}{}{You're of no use. Maybe at least this Bob knows something.}

{270}{}{This city is amazing in scale. But I need to find my relative.}
{271}{}{Yes, it's not so easy to find a person in a big city. Besides, not everyone wants to be found. But there is one possibility. I'll tell you for 5 caps.}
{272}{}{Here are 5 caps. What kind of opportunity?}
{273}{}{Maybe later.}
{274}{}{There is a recruitment agency nearby. Anyone will be found there for the bottlecaps, even El Diablo himself will be taken out of the ground.}
{275}{}{Thank you, friend, you helped me a lot.}
{276}{}{And for this you begged for five caps? Well, you're an extortionist.}
{277}{}{I personally know a dozen Migels. One of them is a woman at all. But if your relative came from far away, then he could change his name. I'm afraid it won't be easy to find him. Try asking the mercenary guild. They are also engaged in the search for people there.}

{280}{}{What do you know about the attack on the monks?}
{281}{}{Such information is not cheap. It will cost you 20 caps.}
{282}{}{That's fair. Hold it and tell me.}
{283}{}{No, I'll try to find a less demanding source.}
{284}{}{I'm sorry, sir, but I don't sell such dangerous information. Talk to someone at the market.}
{1284}{}{My apologies, señora, but I don't sell such dangerous information. Talk to someone at the market.}
{285}{}{I understand.}

#Tips and rumors
{300}{}{For several years now, a cap currency has been operating in the city. It's like dollars before the Great War, and the Cathedral of Fire acts as its guarantor. However, many still do not trust such an idea.}
{301}{}{Speaking of caps. Here's another one. What about pre-war dollars?}
{302}{}{There are problems with this. Usually no one uses them, but for some reason the casino buys up all the old currency. If you find a bill, bring it to the cashier, maybe you'll get a couple of caps from it.}
{303}{}{Have you ever been to the Atomic Fever Casino? It's worth taking a look and spending a couple of caps to assess your chances. But don't let luck fool you. After all, no matter how hard you try, the casino will still win.}
{304}{}{Even without luck, I can give you a cover. By the way, who runs everything there? Maybe I can make some extra money there.}
{305}{}{I doubt the casino will accept a man from the street. They have a kind of family there. And the head of this family, Don Diego, is very selective about the choice of employees. If you want to work for him, you'll have to ingratiate yourself with one of his henchmen first. Or have a good reputation in the city.}
{306}{}{Be careful when you find yourself in the eastern slums. Orris's gang runs everything there, it's better not to mess with it.}
{307}{}{Here's another cover. Tell me about this gang.}
{308}{}{Orris has assembled a gang of Red Cardinals and with its help sets the rules in the slums. But he's not a bad guy like his guys. If you find yourself in his sights, try to negotiate.}
{309}{}{The atomic scientists raised prices again and gave an ultimatum to Aaron. I don't know who will win this battle, but the city will have a hard time anyway.}
{310}{}{I'll give you another cover if you tell me about that area.}
{311}{}{Well, there's a toxic waste moat around the station, traps and barbed wire. I also know that the subway leads directly to the station. Most likely, it is also stuffed with traps against uninvited guests.}
{312}{}{Something is happening in the Cathedral of Fire. Caravans are going there more and more often, and Aaron is becoming more assertive and putting pressure on the residents of the city.}
{313}{}{Here's another cover. What do you know about this Aaron?}
{314}{}{Not much. They talk about him in different ways, but it is clear that the man is overbearing and obsessed with his ideas. And they also say that he is on some kind of pills, without which he cannot live.}
{315}{}{Recently, corpses of people have been found more and more often in the subway. Nobody used to go there except squatters. But they have been harmless so far.}
{316}{}{Here's another cover. Tell me about these squatters.}
{317}{}{Strange guys living in sewers. They dislike the outside world and only occasionally come to the surface to exchange rat carcasses. If you happen to communicate with them, my advice is just give them something you need, it will immediately loosen their tongue.}
{318}{}{One alien type told legends about some kind of Vault, where there is plenty of food and operating technologies. Those who fell for his stories and went in search of this refuge have gone missing.}
{319}{}{Here's another cover if you tell me how to find this guy.}
{320}{}{He just disappeared. If you're interested in the Phoenix neighborhood, then talk to Bob the garbage man in the eastern slums. He has a wealth of experience picking at local ruins.}
{321}{}{The stagecoach regularly goes to Flagstaff. This new colony is growing rapidly thanks to the patronage of the Cathedral of Fire.}
{322}{}{They say there was a brawl in San Brahmin. They also say that fire worshippers are somehow connected with this. Nobody knows exactly what's going on there.}
{323}{}{The rumors from Casa Grande do not lie - the city is torn apart by a constant struggle for power. One mayor replaces another as soon as the sun rises. When you're in those parts, be prepared that you may be deceived or involved in trouble.}
{324}{}{There are a lot of rumors about tinsmiths living in the south. Caravans go there, but few of them can trade with this mysterious people.}
{325}{}{When the caravans began to go south, bandits immediately lined up along the highways. Highway workers, as they are called, rob and kill travelers.}
{326}{}{Here's another cover. How can I protect myself on the way?}
{327}{}{If you don't want to meet with the magistrates, then there are two options. The first is to go around through the hot desert. The second is to join one of the well-protected caravans.}