{100}{}{You see Lloyd.}
{101}{}{You see a poor man, scurrying down the street, looking for food.}
{102}{}{People like this are just trash, and I'm the garbageman.}
{103}{}{Uhh, are you talking to me, piece of metal? I knew that bottle had something else in it...}
{104}{}{Oh, Lloyd...}

{200}{}{Hey. You obviously look like you're new here. And new people have a hard time in this city. Want a free tip? Make some friends, that's valued here.}
{201}{}{What's your name, friend?}
{202}{}{It's strange to hear this from a bum.}
{203}{}{I'm Lloyd. Just a regular person living on the streets. But don't worry, I know the city like my four fingers.}
{204}{}{I sure would use an expert on Phoenix. Could you answer a few of my questions?}
{205}{}{I think you're just a loser. I don't want to associate with someone like you. Bye.}
{206}{}{Hey, it's obvious that you have a lot of caps. I can give you a free tip. Share trivial, small things - and you'll make grateful and loyal friends in this city.}
{207}{}{Bye, Lloyd.}
{208}{}{See you, Lloyd.}
{209}{}{You know, I'm not in a hurry.}

{210}{}{Share a cap, you won't regret it.}
{211}{}{Here comes my favourite client. How can I help you this time?}
{212}{}{Maybe another time.}

{213}{}{Phew, what an earthquake that was! The rumours that the cultists were making an atomic bomb turned out to be true in the end. Real madmen. Now the whole city's starting to hate them and I have one less thing I can use to earn money. Shit...}
{214}{}{They got what they deserved, Lloyd.}
{215}{}{Uh-uh.}

{220}{}{Here's a bottlecap.}
{221}{}{Here's a bottlecap. The new person in the city needs advice.}
{222}{}{Here's a bottlecap. What will you tell me this time?}
{223}{}{Here's a bottlecap. Share some interesting rumours.}
{224}{}{[Continue]}
{225}{}{Thank you, senor.}
{1225}{}{Thank you, senora.}
{226}{}{Thank you, senor. But old man Lloyd has run out of tips.}
{1226}{}{Thank you, senora. But old man Lloyd has run out of tips.}
{227}{}{It's okay, I understand. After all, I'm just as poor as you are. See you later.}
{228}{}{Uhh, yeah, bye.}
{229}{}{Nothing today. Bye.}

{230}{}{Ah, rumours. What I use to earn a living.}
{231}{}{(Looks around) W-well...}
{232}{}{Lloyd sees all from this street. That's for sure.}
{233}{}{You know, I hear a lot of stuff from here.}
{234}{}{Recent news? I heard some things.}
{235}{}{Uh-uh. I have a tip for ya.}
{236}{}{Hm... (scrubs unwashed stubble)}
{237}{}{You know, people talk about a lot...}
{238}{}{(hums) Oh, cap, bo-tt-le-cap...}
{239}{}{Thank you very much.}

{240}{}{Well?}
{241}{}{Go on.}
{242}{}{Speak.}
{243}{}{[Listen]}
{244}{}{[Continue]}
{245}{}{What do you say?}

{250}{}{Hi. What do you think of my new clothes? I bought them with the caps you gave me, so thanks. Sometimes I even think I could get out of this hole and start a new life. Though, who am I kidding...}
{251}{}{Not all is lost, Lloyd. You can't go lower than this, anyway.}
{252}{}{People like you have no future. Make peace with it.}
{253}{}{Listen, I'm earning so much now that I can even afford myself this little treat. With this costume, all the doors are open to me. All thanks to you.}
{254}{}{Listen, I'm earning so much now that I can even afford myself this little treat. With this costume, it might be time for me to relocate to the de luxe suite. A shame it's already taken.}
{255}{}{I'm happy for you, Lloyd.}
{256}{}{I can't believe you. You're just being lucky, nothing more.}

#About a Vault
{260}{}{Do you know anything about Vault 27?}
{261}{}{Just a bit. For 10 caps, I'll tell you all I know.}
{262}{}{Then forget it.}
{263}{}{Here are 10 caps. Tell me what you know.}
{264}{}{I heard different legends about that vault. Somebody said that the rulers of Phoenix made a secret laboratory there. And some other guy told me that since the day of the nuclear war, actual ghosts have been living there. Maybe it doesn't even exist.}
{265}{}{That's sad to hear.}
{266}{}{If you plan on trying to find that place, I suggest you start by heading to Bob the scrapper. He lives in the slums to the east, and he knows Phoenix's surroundings better than anybody else.}
{267}{}{Thanks, you really helped.}
{268}{}{You're of no help at all. Though this Bob person could know something.}

{270}{}{This city's size is incredible. But I must find my relative.}
{271}{}{Yes, finding a man in a big city is not easy. And not everybody wants to be found. But there is one opportunity. I'll tell you about it for 5 caps.}
{272}{}{Here are those 5 caps. What is this opportunity?}
{273}{}{Maybe later.}
{274}{}{There's a recruiting agency nearby. You pay them enough caps, they'll find anyone, alsolutely anyone. They'd bring over El Diablo himself from deep beneath the earth if that would make them caps.}
{275}{}{Thanks, friend, you've been very helpful.}
{276}{}{And you asked me 5 caps for that? What a fine extortionist you are.}
{277}{}{I personally know of 10 Miguels. One of them is even a woman. But if your relative arrived here from far away, he could have changed his name. I'm afraid finding him won't be easy. You should go to the mercenary guild. They also find people there.}

{280}{}{What do you know about the attack on the monks?}
{281}{}{Such information isn't cheap. It will cost you 20 caps.}
{282}{}{That's fair. Take them and tell me.}
{283}{}{No, I'll go try to find a less demanding source.}
{284}{}{Sorry, senor, but I don't trade such dangerous information. Talk to someone in the marketplace.}
{1284}{}{My apologies, senora, but I don't trade such dangerous information. Talk to someone in the marketplace.}
{285}{}{I understand.}

#Tips 'n rumours
{300}{}{The bottlecap currency has been in place in the city for a few years. It's like dollars before the Great War, and the Cathedral serves as a guarantor. Though, to be honest, many still don't trust this idea.}
{301}{}{Speaking of caps, take another one. What about Pre-War dollars?}
{302}{}{There are problems with them. Usually nobody uses them, but the casino buys up all old currencies for some reason. You find them - bring them to the cashier, maybe you'll get a few caps from her.}
{303}{}{Have you been to the "Atomic Fever" casino? You should go have a look, spend some caps, weigh your chances. But don't let luck deceive you. After all, regardless of how hard you try, the house will always win.}
{304}{}{I can give you a cap even without luck. By the way, who's behind all that? Maybe I could earn some money there.}
{305}{}{I doubt that the casino would accept a man from the streets. They have something of a family there. And the head of that family, Don Diego, is very selective with who to work with. You want to do that - you'll have to earn the trust of one of his subordinates first. Or have a good reputation in the city.}
{306}{}{Be careful when you are in the eastern slums. There, Orris' band runs everything, and it's best not to associate with it.}
{307}{}{Here's another cap. Tell me about this gang.}
{308}{}{Orris created the Red Cardinal gang and with it's help, sets up rules in the slums. But he isn't as bad of a guy as his men. If you find yourself in the sights of his gun, try to negotiate.}
{309}{}{The Atomicists raised prices again and have given Aaron an ultimatum. I don't know who'll win in this fight, but the city's going to go through a bad time either way.}
{310}{}{I'll give you another cap if you tell me about that region.}
{311}{}{Well, there's a moat of toxic waste there, traps, and barbed wire. I also know that the underground leads right into the station. It must also be full of traps meant to discourage uninvited guests.}
{312}{}{There's something going on in the Cathedral. More and more caravans are going there, and Aaron is becoming more assertive by the day, applying more pressure on the city's inhabitants.}
{313}{}{Here's another cap. What do you know about this Aaron?}
{314}{}{Not much. They say a lot of things about him, but it's clear that he's an authoritative man and is obsessed with his ideas. They also gossip about how he's addicted to some kind of pills, that he can't live without them.}
{315}{}{Lately, more and more bodies are being found in the underground. Nobody but the squatters went there before. But they were still harmless.}
{316}{}{Here's another cap. Tell me about those squatters.}
{317}{}{Strange folk who live in the sewers. They don't really like the outside world and only go to the surface to exchange rat carcasses. If you happen to run into them, my advice is, give them something useful, that's bound to make them more talkative.}
{318}{}{Some strange person was talking about a legend of a Vault full of food and functioning technology. Those who believed his tales and headed off to find it went missing without a trace.}
{319}{}{You can have another cap if you tell me how to find that person.}
{320}{}{He just went missing. If you're interested in Phoenix's surroundings, then go talk to Bob the scrapper in the eastern slums. He is very experienced in picking local ruins.}
{321}{}{The postal stagecoach is now regularly going to and from Flagstaff. That new colony is growing fast thanks to the Cathedral of Fire's patronage.}
{322}{}{They say a scuffle happened in San Brahmin. They also say the Fire-worshippers are involved somehow. As of right now, nobody is quite sure what's going on there.}
{323}{}{The rumours from Casa Grande aren't lying - the city is being torn apart by the constant power struggles. A new mayor replaces the old one as soon as the sun rises. If you end up around that area, be prepared for people fooling you or getting you into trouble.}
{324}{}{There are many rumours about the tinsmiths, who live to the south. Caravans head there, but not many of them can trade with that mysterious group.}
{325}{}{When caravans started going to the south, bandits flocked to the highways. The highwaymen, as they are called, rob and kill travelers.}
{326}{}{Here's another cap. How can I travel more safely?}
{327}{}{If you don't want to encounter the highwaymen, there are two options. First - go through the scorching desert instead. Second - travel with the protection of a well-defended caravan.}