{100}{}{You see the Lord of the Phoenix.}
{101}{}{In front of you is a serious-looking man in a ceremonial robe. His imperious gaze makes me feel uncomfortable.}
{102}{}{This is a peaceful church. Why such drastic security measures?}
{103}{}{You have officially given up the Ranger badge.}
{104}{}{You have officially joined the brotherhood of monks.}

#The first dialogue (acquaintance)
{200}{}{I don't remember being warned about your visit. Who are you and what do you need? In the name of the Sacred Fire, answer immediately.}
{201}{}{I thought I'd never see you again. What is it this time?}
{202}{}{I just want to talk to you.}
{203}{}{I want to talk to you.}
{204}{}{My name is }
{205}{}{. And I represent the Villa community.}
{206}{}{I want to join the church, Father.}

{210}{}{I think I'm lost. Tell me, where is the exit here?}
{1210}{}{I think I'm lost. Tell me, where is the exit here?}
{211}{}{What an absurdity. I'll give you one more try. what do you need?}
{212}{}{I'm telling you, I'm looking for a way out.}
{213}{}{You're either extremely stupid, or you're looking for trouble on purpose. Security! Capture the spy!}
{1213}{}{You're either extremely stupid, or you're looking for trouble on purpose. Security! Capture the spy!}
{214}{}{Who is the spy? Me?}
{215}{}{Try to catch it!}
{216}{}{Wait a minute! I'm not going to fight. Maybe we can solve the case in peace?}
{217}{}{Poor victim of radiation. Go in peace. I'm sorry to see you suffer. I hope some street thug will graduate soon.}
{218}{}{You can't wait, Dad.}
{219}{}{Never mind, I'll find my way.}

{220}{}{Very good. We don't like pugnacious visitors here. So what are you trying to achieve?}
{221}{}{Only meetings with you. I have a few questions.}
{222}{}{Here I will ask questions. And you will sit and answer.}
{223}{}{I am the messenger of the Brotherhood of Steel.}
{224}{}{You're forcing me... (one of the advisers interrupts and whispers something in my ear) Hmm. Good. I won't keep you. But don't bother distracting me anymore. Get out!}
{225}{}{Of course, Mr. Aaron. Sorry to bother you.}
{226}{}{Yeah.}
{227}{}{Villa? This place is unfamiliar to me. What do you want, }
{228}{}{from the Villa?}
{229}{}{It is very important. I need to talk to you, Mr. Aaron.}

{230}{}{That's enough! You will be publicly flogged and hanged! Capture the heretic!}
{1230}{}{That's enough! You will be publicly flogged and hanged! Capture the heretic!}
{231}{}{This is an outrage! Down with the tyrant!}
{232}{}{Yes, you went...}
{233}{}{It's a killer! In the name of Fire, stop him!}
{234}{}{Relax, I'm in charge here now.}
{235}{}{They won't help you.}
{236}{}{Brothers, in the name of Fire, throw this garbage out into the street.}
{237}{}{Security! Kill the spy! Immediately!}
{238}{}{They won't stop me...}
{239}{}{I want you dead. You are a vile oppressor and tyrant!}

{240}{}{And you're not very nice to me, dear.}
{241}{}{Continue in the same spirit - and you will go to hard labor, like many before you.}
{242}{}{So this is how they solve their problems in the church? And I thought there was an atmosphere of peace and brotherhood here.}
{243}{}{All right. Until an atomic nonentity like you comes to us and starts rioting. The world around is so wild that even a peaceful church has to take up arms. You savages from the wasteland still have a lot to learn.}
{244}{}{[Next]}
{245}{}{I'm asking you for the last time - what do you need?}
{246}{}{I just want to talk to you.}
{247}{}{After our short conversation, I don't see the point in continuing it. Go away.}
{248}{}{Will you ever pay for such treatment! I swear!}
{249}{}{Okay, I'll leave the cathedral peacefully.}

{250}{}{I'm sorry, but I don't have time for idle conversations. Do you have any BUSINESS with me?}
{251}{}{Well, if you think about it, there is one. My village.}
{252}{}{Actually, no. I'm sorry I took up your time because of my idle curiosity.}
{1252}{}{Actually, no. I'm sorry I took up your time because of my idle curiosity.}
{253}{}{No, I'm just hanging around. If they don't listen to me here, I'll go somewhere else.}
{254}{}{Please, it is important for me to hear firsthand.}

{255}{}{Great. The brothers will show the exit to the street.}
{256}{}{No, no, I'll find my way without a guide.}
{257}{}{You're so kind.}

{260}{}{This is already getting curious. WHAT business do you have with me?}
{261}{}{Obviously, this is your death. It would be rash to leave a tyrant like you alive.}
{262}{}{This concerns the Villa. I }
{263}{}{, a representative of this once thriving community.}

{264}{}{I am the messenger of the Brotherhood of Steel. And I count on a warm welcome and assistance.}
{1264}{}{I am the messenger of the Brotherhood of Steel. And I count on a warm welcome and assistance.}
{265}{}{The Brotherhood of Steel is our faithful friend and our reliable support. I'm glad to meet you. You will be given all the necessary assistance.}
{266}{}{I didn't think that such arrogant recruits began to get into the Brotherhood. But the Brotherhood is our faithful friend and our reliable support. Stay in the cathedral. You will be given all the necessary assistance.}
{267}{}{Thank you, Mr. Aaron. You are very kind.}
{268}{}{Cut the pleasantries, Aaron. I'm here on business.}

{270}{}{Ulysses warned me about your visit. According to him, you will bring a lot of benefit to our cause. Well, don't let my expectations down, }
{271}{}{ from the Villa.}
{272}{}{I will do everything possible, Mr. Aaron.}
{273}{}{I'm the best at what I do. Be sure.}
{1273}{}{I'm the best at what I do. Be sure.}
{274}{}{Ulysses Grant sent me.}

#After being sent to Tusan
{280}{}{Holy Atom! I sent you to penal servitude in Two-Sun. Why are you free?}
{281}{}{I managed to escape. And now you will answer for everything!}
{282}{}{Brothers, stop him! Stop it!}
{283}{}{They can't stop me!}
{284}{}{I managed to negotiate with the tinsmiths.}
{285}{}{It looks extremely suspicious. But until I get a rebuttal, you can breathe the air of freedom. Appreciate this time allotted to you by the Sacred Fire.}
{286}{}{Suspicious? You're right. Because I'm here to get revenge.}
{287}{}{I'm trying.}
{288}{}{Wipe your eyes, you're not omnipotent.}
{289}{}{Grm-M. You can breathe the air of freedom until I know more. Appreciate this time allotted to you by the Sacred Fire. Now get out of here!}
{290}{}{Not so fast, Mr. Tyrant. I'm not leaving while you're breathing this air.}
{291}{}{This is a reasonable solution.}

#Repeat dialog
{300}{}{So what do you need?}
{301}{}{Once again, you, a peasant, dare to distract me from important matters.}
{1301}{}{And again, you, a peasant, dare to distract me from important matters.}
{302}{}{So. What can you tell me?}
{303}{}{I am glad to see you, messenger of the Brotherhood of Steel.}
{1303}{}{I am glad to see you, messenger of the Brotherhood of Steel.}
{304}{}{Good to see you.}
{305}{}{Glad to see you, novice.}
{1305}{}{Glad to see you, novice.}
{306}{}{I thought I'd never see you again. What is it this time?}
{307}{}{May the Sacred Fire bless you.}
{308}{}{Goodbye.}
{309}{}{I'll go, with your permission.}

#Questions about the church and faith
{310}{}{Can I find out more about your faith?}
{311}{}{I would like to get to know your religion better.}
{312}{}{This is regularly preached in the auditorium on the first floor. I don't have time for this.}
{313}{}{I would like to hear the most reliable source.}
{314}{}{This is regularly preached in the auditorium on the first floor. I don't have time to explain this to a simple counter.}
{315}{}{Then I'll ask someone else.}
{316}{}{A simple counter? Now everything is clear.}
{317}{}{}
{318}{}{Fear the Sacred Fire, my child.}
{319}{}{Yes, uh, of course.}

{320}{}{If you are interested in our faith, then come to mass in the auditorium on the first floor. I don't have time to answer everyone. Maybe you have something to do with me?}
{321}{}{Well, if you think about it, there is one. My village.}
{322}{}{Actually, no. I'm sorry I took up your time because of my idle curiosity.}
{1322}{}{Actually, no. I'm sorry I took up your time because of my idle curiosity.}
{323}{}{No, I'm just hanging around. If they don't listen to me here, I'll go somewhere else.}
{324}{}{Please, it is important for me to hear firsthand.}

{330}{}{This is already getting curious. WHAT business do you have with me?}
{331}{}{This concerns the Villa.}
{332}{}{Obviously, this is your death. It would be rash to leave a tyrant like you alive.}
{333}{}{Great. The brothers will show the exit to the street.}
{334}{}{No, no, I'll find my way without a guide.}
{335}{}{You're so kind.}
{336}{}{It's a killer! In the name of Fire, stop him!}
{337}{}{Relax, I'm in charge here now.}
{338}{}{They won't help you.}
{339}{}{Blessings on getting out of here.}

{340}{}{Of course. Please.}
{341}{}{Can we talk about the Villa?}
{342}{}{So what is the essence of your faith?}
{343}{}{You're the leader of this church, right?}
{344}{}{I've heard enough today. Thank you for the conversation.}
{345}{}{I repeat - I don't have time for this.}
{346}{}{Okay, I'll talk to the others.}
{347}{}{You're just trying to get rid of me.}

{350}{}{You already know everything you need.}
{351}{}{I respect your interest in our teaching. But not everyone can comprehend it.}
{352}{}{[Next]}
{353}{}{Our church calls to accept the Sacred Fire as an act of healing, as a chance to start life anew. After all, instead of rebirth, people are still waging a senseless struggle among themselves.}
{354}{}{What is this Sacred Fire?}
{355}{}{Now everything is clear, you don't have to continue.}
{356}{}{The fire that incinerated the world a hundred years ago. We call it sacred because it punished fallen humanity and cleansed the earth of filth, thereby giving descendants the opportunity to live a new life.}
{357}{}{Wasn't it some kind of powerful weapon?}
{358}{}{Technically, yes. But it doesn't matter. For the Lord has punished people with their own hands. The layman sees a nuclear bomb as a nuclear bomb, but we see God's plan in it.}
{359}{}{You said "live anew." So the church is trying to change the world?}
{360}{}{By uniting and rallying the lands for the benefit of a common goal of survival. To do this, it is necessary to return and rethink ancient technologies, revive nuclear energy and teach people to read and write.}
{361}{}{So do you force others to your faith?}
{362}{}{No, no. Such novices would be to the detriment of the church. Joining the abbey must be voluntary. In addition, we are very careful in accepting people into the service, every member of the church needs a guarantor.}
{363}{}{What does "unite the lands" mean?}
{364}{}{One banner, one country, one people... one faith. People should abandon all internecine conflicts and give themselves up to Rebirth in full.}
{365}{}{And how far has the church spread?}
{366}{}{We have chapels in the Phoenix area and in several neighboring cities. By modern standards, this is a huge territory. But we still have room to grow.}
{367}{}{Now I understand how the church is connected with the slavers.}
{368}{}{You are fighting yourself. Aren't you considered a tyrant who usurped power?}

{370}{}{The ordinary population has fallen to the level of animals and is not able to participate in the great work of Rebirth voluntarily. Slavery is only a necessary and temporary means for our mission. Besides, we have never enslaved anyone ourselves, but only paid mercenaries for their work, turning a blind eye to their wild measures.}
{371}{}{Sounds inspiring. Can I join your cult?}
{372}{}{That's enough! Such a religion has no place in our world. I will destroy you all.}
{373}{}{Thanks for the conversation, now I understand a lot more.}
{374}{}{By the way, aren't you behind the abduction of the peasants of the Villa?}
{375}{}{By the way, about the abduction of the peasants of the Villa.}

{380}{}{Are you the one who manages this whole process?}
{381}{}{Of course.}
{382}{}{So you can explain to me the essence of your religion better than others.}
{383}{}{Nice to meet you. Nothing else interested me.}
{384}{}{The people consider you a tyrant. Do you know about this?}
{385}{}{Evil tongues. Apparently, such a reputation was fixed for the church after the revolution. Yes, we came to power by force. It was a forced measure. But there has always been peace in our hearts.}
{386}{}{I got the impression that the cult owns this city...}
{387}{}{The church has really become something big for Phoenix. Science, education and medicine have returned to the city from our submission. We have introduced a cap currency and are establishing trade relations. Thanks to us, crime has decreased in the city. But the bulk of the townspeople live outside of our attention.}
{388}{}{Wow, that's a twist. I want to know more about your religion.}
{389}{}{No matter how much you hide behind beautiful words, and you are an ordinary tyrant. And I will kill you so that others will not be offended.}
{390}{}{I'm afraid I have to go. My respects, Mr. Aaron.}
{391}{}{You look more like a tyrant than an abbot.}
{392}{}{The Church had to take over the management of this city. This is a necessary measure until society is ready to create a full-fledged city hall and police.}

#Villa
{400}{}{I want to talk to you about the Villa.}
{401}{}{}
{402}{}{ Villa... Yes, I remember our conversation about this village.}
{403}{}{I think we have already discussed everything. Goodbye, Mr. Aaron.}
{404}{}{Hmm... Villa... Is this some kind of village? I've never heard of her.}
{405}{}{I'm actually looking for my relatives. They were enslaved.}
{406}{}{Oh, poor people. I have infinite sympathy for you and will pray for the salvation of your souls. But why did your search lead you to us?}
{407}{}{Your sect is clearly involved in this! Bring back my relatives!}
{408}{}{That wasn't very kind of you. We are just a peaceful church, we do not enslave anyone.}
{409}{}{You're lying.}
{410}{}{Well, it's sad to see such wild ignorance. I have to... (one of the advisers interrupts the Ruler and whispers something in his ear) That's it. So do you want to be reunited with your family? We can provide it.}
{411}{}{Really? In what way?}
{412}{}{Lay down your weapons and raise your hands. Don't try to resist. You will be sent to hard labor, to the rest of your tribesmen.}
{413}{}{Well, if it helps to find relatives, I voluntarily give myself into slavery.}
{414}{}{You can't intimidate me. I will leave here the same way I entered.}
{1414}{}{You can't intimidate me. I will leave here the same way I entered.}
{415}{}{It's a pity that it came to this. Grab him!}
{1415}{}{It's a pity that it came to this. Grab her!}
{416}{}{Your words sound more insignificant than the moan of an atom in a fiery cloud. Send him to our brothers in Two-Sun, let him serve the Sacred Fire.}
{1416}{}{Your words sound more insignificant than the moan of an atom in a fiery cloud. Send her to our brothers in Two-Sun, let her serve the Sacred Fire.}
{417}{}{(one of the councillors interrupts the Ruler and whispers something in his ear) Hmm. Looks like I'm going to have to let you go. But for the future, remember that no one will go unpunished if they go against the Church of the Sacred Fire.}
{418}{}{Okay, I'll remember that.}
{419}{}{Just tell me what to do.}
{420}{}{I thought you knew everything here.}
{421}{}{Alas, this is not the case.}
{422}{}{Well, sorry. I think I'll go look further...}
{423}{}{Wait, I'm not going to resist.}
{424}{}{As a member of the Brotherhood of Steel, I count on assistance in finding the missing peasants.}
{425}{}{It is strange that the Brotherhood of Steel became interested in these peasants. Of course we will help you.}
{426}{}{So what do you know about this case?}
{427}{}{You're lying. I'm not leaving until I know the whole truth.}
{428}{}{Everyone stop! Don't come near! I will defend myself!}
{429}{}{No one here will touch me. Got it?}

{430}{}{Enough of these representations. I KNOW that this church sponsored a slave convoy.}
{431}{}{Your audacity knows no bounds.}
{432}{}{I'm not leaving until I know what's going on.}
{433}{}{Go in peace, messenger of the Brotherhood of Steel.}
{434}{}{My respects.}
{435}{}{Are you pretending to be kind? I'll keep that in mind.}

{436}{}{Who dared to lay a hand on your family? I will not tolerate such an attitude towards my bishop!}
{437}{}{That's what I want to know. Will you help me?}
{438}{}{ (gives a sign to the scribe, who searches for something in the computer and then whispers the result) I'm sorry, but your relatives have already gone to work in the sacred mines in the south.}

{450}{}{Hmm. Remind me, what is the name of this village? (one of the councillors approaches the Ruler and whispers something in his ear) Umgu... Yes, we know where your people are. They got a second chance and are now working out their karma in the south.}
{452}{}{I remember our conversation. The peasants got a second chance and are working off their karma in the south.}
{453}{}{In the south? And where exactly?}
{454}{}{Some of them were left in Flagstaff to work in the mines. The rest were sent to Two-Sun to serve for the benefit of Progress. Local tinsmiths do not have enough workers to work on protected lands. Such a fate is honorable, because these slaves will help the whole world with their sacrifice.}
{459}{}{Why these unnecessary questions? During your subordination, you were given the opportunity to get to know the tinsmiths better. This tribe reveres ancient technologies, although it sees them in a very narrow light.}
{460}{}{Who are these tinsmiths?}
{461}{}{An occult tribe of admirers of ancient technologies. Like us, they advocate the revival of the ancient world, but they see it exclusively in a technological way. Now we have common goals with them, but someday misunderstanding will become a conflict.}
{462}{}{What do you care about their technologies?}
{463}{}{Without the production base of tinsmiths, we will not even be able to conduct electricity in this cathedral. We need their machines and skills.}
{464}{}{Yes, you both need to be eliminated. And we need to start with this pitiful godless cathedral.}
{465}{}{That explains everything. I have no more questions.}
{466}{}{The prison in Flagstaff is also your handiwork?}
{467}{}{The Flagstaff colony was created on our bottlecaps. But over time it became more and more free and independent.}
{468}{}{Why do you need this colony?}
{469}{}{Obviously, for the production of uranium in local mines.}
{470}{}{But why does the church need uranium ore?}
{471}{}{Uranium is necessary for the production of nuclear energy. After all, it is impossible to use old technologies without it. And without them, there can be no question of any revival of civilization.}
{472}{}{Does Faber cause you any problems?}
{473}{}{Is Faber starting to step on his heels?}
{474}{}{In a way. Sometimes you eat a mole rat, and sometimes he eats you. Faber shares many of our views, but sees them in his own way. This sometimes creates small conflicts.}
#- Quote from the movie "The Big Lebowski": Sometimes you eat a bear, and sometimes he eats you.
{475}{}{Great. Then I will follow his example and seize power over this defenseless cathedral.}
{476}{}{I think I should go to Flagstaff and find out everything in the first person. Goodbye.}
{477}{}{In a way. Allowing people to power, you always risk making an enemy out of a friend. However, it became known that Faber was no longer in business. It is unclear whether he was killed by accident or this is a cunning plan of the local revolution. We are still dealing with this problem.}
{478}{}{And what did you say about tinsmiths?}

{480}{}{I've had enough of this lie. I'm leaving here.}
{481}{}{It looks like you have big plans. Now I can leave here with peace of mind.}
{482}{}{But why do you patronize slavery?}
{483}{}{Is that why you patronize slavery?}
{484}{}{Society is not ready to be independent. These people will never rise from their knees on their own. They need tyrants and guides.}
{485}{}{So it is you who are guilty of enslaving the Villa?}
{486}{}{Don't rush into accusations. We only sponsor our colonies and various projects with caps. And if slave power is needed to provide them, then the caps will be used to buy slaves.}
{487}{}{It's a disgrace to the church. You should disappear.}
{488}{}{An interesting point of view. Although it is unlikely to take root with us.}
{489}{}{Coercion is the worst method of development of society.}
{490}{}{Oh, you're wrong. Society is not ready to be independent. He needs tyrants and guides.}
{491}{}{And what does this have to do with the tinsmiths in Two-Sun?}
{492}{}{Now it's clear what you have to do with the Flagstaff jailers.}

#Become A Follower
{500}{}{I'm thinking of joining your church.}
{501}{}{It's not as easy as you think. To be accepted for service, a guarantor or some merit significant for our mission is required. What can you say to that?}
{502}{}{I don't have a guarantor.}
{503}{}{Our church is constantly under attack. Prove that we can trust you - and then we'll talk about your dedication.}
{504}{}{I'll try to find a guarantor.}
{505}{}{How can I prove my loyalty?}
{506}{}{. . . [test task]}
{507}{}{I'll be back when the issue is resolved.}
{508}{}{I will do anything for the radiance of the Sacred Fire.}
{509}{}{Too pompous words for a crook.}
{510}{}{Okay, I'm going to look for a guarantor.}
{511}{}{But I really want to join your church.}
{512}{}{A guarantor is required for admission to the service... But I doubt the purity of your thoughts, peasant from the Villa.}
{1512}{}{A guarantor is required for admission to the service... But I doubt the purity of your thoughts, peasant woman from the Villa.}
{513}{}{Ulysses Grant advised me to talk to you.}
{514}{}{Membership in the Brotherhood of Steel is a sufficient reason?}
{515}{}{Here is a letter of recommendation from a preacher from Flagstaff.}
{516}{}{(listens to the whisper of the adviser) This letter doesn't mean anything anymore. Get out.}
{517}{}{Um, but...}
{518}{}{I had a letter of recommendation from Flagstaff. But it's gone somewhere.}
{519}{}{I no longer want to join your religion. Happily.}
{520}{}{Arthur Carrington can recommend me.}
{521}{}{The bookkeeper Francis will be my sponsor.}
{522}{}{Give me a chance.}
{523}{}{Here is a letter of recommendation from George Crook.}

{530}{}{In that case, I am glad to see you in the abode of wisdom and progress. Our church is trying to heal the world from the wounds of the Great War. And you will help us in this difficult mission.}
{531}{}{Great. What can I do for the church?}
{532}{}{I hope it makes no sense to explain that the church has many enemies. The hostility has intensified recently. Several novices were killed right on the streets of the city in full view of everyone. I ask you to investigate these crimes.}
{533}{}{The attackers chose the wrong target. But where should I start?}
{534}{}{Find Gabriel, he preaches at the city gates and is well informed about the affairs in the city. But be... gently. His fanaticism sometimes frightens even members of our church.}
{535}{}{I will return when the issue is resolved.}
{536}{}{I'll do my best.}

#The first quest
{550}{}{About those crimes against the church.}
{551}{}{Did you find out anything?}
{552}{}{Unfortunately, nothing. This case is too dark.}
{553}{}{Sorry to hear that. But I'm not giving up hope. Talk to Gabriel at the city gate, he will tell you the details of the attacks.}
{554}{}{Okay, I'll go.}
{555}{}{It looks like you've made some serious enemies. They are well organized and well equipped. More importantly, they're watching you.}
{556}{}{Are you saying these attacks weren't spontaneous? That someone was watching the novices and preparing for an attack in advance?}
{557}{}{That's right.}
{558}{}{(pursing his lips in thought, approaches the altar) Probably it is. But no one outside the cathedral knows our routines. The novices' schedule is drawn up for the whole week. If the attackers, as you say, were preparing for an attack, then how did they find out about these plans?}
{559}{}{Who has access to the schedule?}
{560}{}{Each abbot draws up a schedule of his novices and passes it to the library. Only a few people have access to the general list.}
{561}{}{It looks like it's time for me to visit this storehouse of old books. Let me take my leave.}
{562}{}{Okay, so be it, I'll go there and find out.}
{563}{}{Well, I don't know. It could be true...}

{570}{}{The spy turned out to be Mathias. He followed the novices' routine and transmitted the data through the radio station to the enemies of the church.}
{571}{}{ (Aaron's lips turn red with anger) Mathias... I should have guessed sooner. How could one of my closest advisers betray me? Guards! Mathias is under arrest.}
{572}{}{Be polite to this respectable man.}
{573}{}{Right. And fry his eggs with a shocker.}
{574}{}{ (wandering around the hall in thought) There is a solid deception all around... I can't even trust my closest subordinates. No one could have thought that Mathias hated the state of things in the church so much.}
{575}{}{He was against your policy, wasn't he?}
{576}{}{Mathias advocated the isolation of the cathedral from the world and the complete preservation of our relics. He didn't want to share them with outsiders and didn't see anyone who was worthy of them. I didn't agree. The time has come when this knowledge should be extracted from dust and mold in the name of the Sacred Fire.}
{577}{}{Apparently, not everyone liked it.}
{578}{}{(makes a gracious face) You've done a good job, brother. And more importantly, he remained loyal. I need your further help to cleanse the Phoenix lands of filth.}
{1578}{}{ (makes a gracious face) You've done a good job, Sister. And more importantly, she remained loyal. I need your further help to cleanse the lands of the Phoenix from filth.}
{579}{}{Anything for the sake of the Sacred Fire, Your Holiness.}
{580}{}{What is required of me this time?}
{581}{}{Obviously, a gang of fire-haters is operating in the city. Well-organized and armed. We'll get all the information about them out of Mathias, but that's not enough. You are required to find their lair and infiltrate their ranks. Can you handle it?}
{582}{}{Perhaps. But why me?}
{583}{}{You are still a new person for our church. It's unlikely the rebels will identify you as one of us.}
{584}{}{If I find their lair, what should I do next?}
{585}{}{Let me know about it. We will decide what to do next.}
{586}{}{How do I do this?}
{587}{}{Mathias used the radio to communicate with the rebels. Besides, many residents in the city are probably connected with this gang. Try all possible means.}
{588}{}{I'll do my best. Let me take my leave.}
{589}{}{But why me?}
{590}{}{However, you turned out to be very selective about the "worthy", right?}

#The second quest
{600}{}{The situation with the rebels has cleared up.}
{601}{}{Really? Tell me.}
{602}{}{To be honest, these are all dubious rumors. Let's not jump to conclusions.}
{603}{}{The rebels were hiding in the sewers. Now their leader is dead, and the party is split and suppressed...}
{604}{}{...Very good. I will send people to clean up the lair of these criminals, and you should pay tribute. It seems that the Sacred Fire itself has sent us enlightenment in your body.}
{605}{}{I can continue to serve the church if it is useful.}
{606}{}{I have no doubt, my child. And more than that - right now we need friends more than ever.}
{607}{}{How can I help, Mr. Aaron?}
{608}{}{I know where the general staff of the Liberation Party is located.}
{609}{}{You may have already come across our preachers outside of Phoenix. The church is growing and opening its chapels where people are ready to listen to us. But the village of San Brahmin has become a stumbling block for our faith.}
{610}{}{[Next]}
{611}{}{The locals, friendly at first, got angry at the church for some reason. Our attempts to reason with them only made the situation worse. We don't know exactly what's going on. George Crook's detachment is now on the outskirts of the village. Find him and offer your help. It is necessary to return our trade agreements with this village.}
{612}{}{[Next]}
{613}{}{Here are 350 caps for the road and the purchase of everything you need. Go ahead. May the Sacred Fire bless you.}
{614}{}{I'm going, Mr. Aaron. The San Brahmin will believe in the power of the Sacred Fire.}
{615}{}{I will do my best.}
{616}{}{You've already helped a lot, my friend. George Crook told me about your feat. I was thinking of sending you to help him, but you managed to get ahead of me. Now I want to know everything from your mouth: how is our business in San Brahmin progressing?}
{1616}{}{You've already helped a lot, Virgo Atom. George Crook told me about your feat. I was thinking of sending you to help him, but you managed to get ahead of me. Now I want to know everything from your mouth: how is our business in San Brahmin progressing?}
{617}{}{Indeed, I have something to tell you.}

#The third quest
{630}{}{I need to talk to you about the situation in San Brahmin.}
{631}{}{Of course. What news, my child?}
{632}{}{Soon I will visit the place and find out the details. Goodbye.}
{633}{}{[CHEAT: it's done with the best result for the Lord]}
{634}{}{[Blah blah glory to the Fire - blah blah talk to the Adviser in the Vault, here's the key and access - blah blah eliminate George Crook]}
{635}{}{[CHEAT: completing quests - getting a title + sending to a Vault + reward + cathedral radio frequency]}
{636}{}{I bring the news of victory, Mr. Aaron. The chief of the tribe signed the union, and Kruk's detachment settled down near the village.}
{1636}{}{I bring the news of victory, Mr. Aaron. The chief of the tribe signed the union, and Kruk's detachment was located near the village.}
{637}{}{Glory to the Sacred Fire! Did God himself send you to us in a difficult moment? It's a miracle. And you deserve the highest reward.}
{638}{}{It was a sacred duty for me.}
{639}{}{I don't know if the Sacred Fire helped, but it's done.}
{640}{}{Hmm, in his report, George Crook highly appreciates your personal qualities and loyalty to the empire. Considering your past services to the church, I cannot pass by and not reward you.}
{641}{}{I would be honored, Your Holiness.}
{642}{}{In what way?}
{643}{}{For your services to the Phoenix Empire, I solemnly appoint you as my bishop. Take this consecrated robe as a token of gratitude. Let her protect you from enemy bullets and lies.}
{644}{}{Thank you.}
{645}{}{It's also time to initiate you into our secret circle. Here's the key to the basement. There you will find an ancient sanctuary. Tell the guards to take you to Ulysses Grant. I will warn him about your visit.}
{646}{}{[Next]}
{647}{}{Go, my friend. May the Fire bless you.}
{648}{}{Thank you for the honor, Mr. Aaron.}

{650}{}{My lord, I have disturbing news - George Crook died during his mission.}
{651}{}{(takes a heavy sigh and crosses his fingers) May the Sacred Fire calm his soul. He was the best warrior I've ever known. And even if he failed to resist the savages, who will be able to fulfill his mission?}
{652}{}{I don't think I can handle it.}
{653}{}{Maybe I can do it.}
{654}{}{Go back to San Brahmin and conquer the tribe in the name of Fire! This is your sacred duty. And if you can't, then sow discord in the tribe. Kill the supreme leader so that the savages will fight for his lousy throne. Make the rangers escape from the pueblo. Go ahead. Go!}
{655}{}{Yes, my lord...}
{656}{}{Bad news. The tribe made an alliance with the rangers, who drove the missionaries out of the pueblo and the surrounding lands.}
{657}{}{ (makes a heavy sigh and crosses his fingers) We're too late. How much effort was spent on conquering the tribe, and all in vain!}
{658}{}{Is everything really lost?}
{659}{}{Perhaps I can convince the chief.}
{660}{}{The leader died. The tribe is divided. Now it will be difficult for the Rangers to take advantage of the situation.}
{661}{}{It's hard to realize defeat. But how many persecutions have we endured before? Nothing, we'll wait. Savages have fallen to their level for generations. Perhaps it will take no less to pull them to a civilized state.}
{662}{}{[Listen]}
{663}{}{And your service is over. As much as I would like to kick you out of the cathedral after so many failures, my advisers have come to a different conclusion. I'll let you meet with my chief advisor, Ulysses Grant. Take this key and go down to the basement. The guards will take you to Ulysses. He is waiting for your meeting.}
{664}{}{Thank you, my lord.}