{100}{}{You see the Overlord of Phoenix.}
{101}{}{You see a serious-looking man in grand robes. His authoritative gaze makes you feel uneasy.}
{102}{}{This is a peaceful church. Why such security measures?}
{103}{}{You have officially rejected your Ranger badge.}
{104}{}{You are now officially a member of the monk brotherhood.}

#First dialogue (meeting)
{200}{}{I do not recall being informed about your visit. Who are you and what do you want? In the name of the Holy Fire, answer immediately.}
{201}{}{I thought I would never see you again. What happened this time?}
{202}{}{I just want to talk to you.}
{203}{}{I just want to chat with you.}
{204}{}{My name is }
{205}{}{, and I represent the commune of Villa.}
{206}{}{I wish to join the church, holy father.}

{210}{}{Looks like I got lost. Can you tell me where the exit is?}
{1210}{}{Looks like I got lost. Can you tell me where the exit is?}
{211}{}{How absurd. I will give you a second chance to explain yourself. *What* do you want?}
{212}{}{I'm telling you, to know where the exit is.}
{213}{}{You are either incredibly stupid, or are just intentionally looking for trouble. Guards! Capture the spy!}
{1213}{}{You are either incredibly foolish, or are just intentionally looking for trouble. Guards! Capture the spy!}
{214}{}{Wait, what spy? Me?}
{215}{}{Try it!}
{216}{}{Wait! I'm not here to fight anyone. Perhaps we could resolve this situation without bloodshed?}
{217}{}{Oh, poor victim of radiation. Go in peace. I am deeply saddened to see such suffering. I do hope some street bandit ends it soon enough.}
{218}{}{Keep dreaming.}
{219}{}{It's okay, I'll find a way.}

{220}{}{Very good. We do not like aggressive visitors. So, what is it you are trying to achieve?}
{221}{}{Just a meeting with you. I have several questions.}
{222}{}{I'll be asking you the questions here. And you'll sit down, shut up and answer them.}
{223}{}{I'm a messenger from the Brotherhood of Steel.}
{224}{}{You force me... (one of the advisors interrupts and whispers something in his ear) Hm. Fine. I will not keep you here any longer. But don't even think of wasting my time in the future. Get out of here!}
{225}{}{Of course, lord Aaron. I apologize for the disturbance.}
{226}{}{Uh-uh.}
{227}{}{Villa? I am not familiar with that place. What do you want, }
{228}{}{ from Villa?}
{229}{}{This is very important. I need to speak with you, lord Aaron.}

{230}{}{Enough! You will be publicly whipped and hanged! Capture the heretic!}
{1230}{}{Enough! You will be publicly whipped and hanged! Capture the heretic!}
{231}{}{This is despotism! Down with the tyrant!}
{232}{}{You're insane...}
{233}{}{This is a murderer! In the name of the Fire, stop them!}
{234}{}{Relax, now I'm in charge here.}
{235}{}{They won't be helping you.}
{236}{}{Brothers, in the name of the Fire, throw this heathen trash out onto the streets.}
{237}{}{Guards! Kill the spy! Immediately!}
{238}{}{They won't stop me...}
{239}{}{I want your death. You're a disgusting tyrant and oppressor!}

{240}{}{You aren't being particularly polite with me, dear sir.}
{241}{}{Continue acting in this manner and you'll be sent to do hard labor, like many before you.}
{242}{}{So that's how problems are solved in the church? And I thought there was an atmosphere of peace and fellowship here.}
{243}{}{There is one, indeed. It dissapears only when pathetic creatures such as you come in and bring instability. The world around us has become so savage that even a peaceful church has to take up arms. You primitives from the Wastes have a lot to learn.}
{244}{}{[Continue]}
{245}{}{I am asking you for the last time - what do you want?}
{246}{}{Nothing more than to speak with you.}
{247}{}{After having experienced our short conversation, I see no point in continuing it. Go.}
{248}{}{One day you will pay for treating people like this! I swear!}
{249}{}{Fine, I'll leave the building peacefully.}

{250}{}{I'm afraid I don't have time for smalltalk. Do you have something IMPORTANT to discuss with me?}
{251}{}{Well, actually, yes. There is one such thing - my village.}
{252}{}{No, I'm afraid. I apologize that I wasted your time because of my curiosity.}
{1252}{}{No, I'm afraid. I apologize that I wasted your time because of my curiosity.}
{253}{}{No, I'm just walking around, having nothing to do. If nobody will listen to me here, then I'll go to another place.}
{254}{}{Please, it's important for me to hear something from the first person I talk to.}

{255}{}{Good. My brothers will show you the way.}
{256}{}{No, I'll find it myself.}
{257}{}{You're so kind.}

{260}{}{Now this is becoming interesting. What *do* you want from me?}
{261}{}{Obviously, your life. It would be reckless to leave a tyrant the likes of you alive.}
{262}{}{It's about Villa. My name is }
{263}{}{, I'm a representative of this once-prosperous commune.}

{264}{}{I am a messenger from the Brotherhood of Steel. I'm expecting a warm welcome and cooperation.}
{1264}{}{I am a messenger from the Brotherhood of Steel. I'm expecting a warm welcome and cooperation.}
{265}{}{The Brotherhood of Steel are our loyal allies and provide us with support. I'm happy to meet you. You will have all the cooperation you need.}
{266}{}{I did not think the Brotherhood of Steel could have such haughty recruits. But the Brotherhood are our loyal allies and provide us with support. Remain in the building. You will be given all the cooperation you require.}
{267}{}{Thank you, lord Aaron. You're very kind.}
{268}{}{Enough with the pleasantries, Aaron. I'm here on a mission.}

{270}{}{Ulysses told me you'd come. He says you will quite useful for our cause. Well, do not dissapoint me, }
{271}{}{ of Villa.}
{272}{}{I will do everything in my power to ensure this does not happen, lord Aaron.}
{273}{}{I'm the best in my field, don't worry.}
{1273}{}{I'm the best in my field, don't worry.}
{274}{}{I was sent here by Ulysses Grant.}

#After being forcefully sent to Two Sun
{280}{}{Holy Atom! I sent you to do hard labor in Two Sun! Why do you walk free?}
{281}{}{I managed to escape. And now you're going to pay for everything!}
{282}{}{Brothers, stop them! Stop them!}
{283}{}{They won't!}
{284}{}{I managed to reach an agreement with the tinsmiths.}
{285}{}{This looks quite suspicious. But until I receive something that invalidates your words, you can breathe the air of freedom. Value the time the Holy Fire has given you.}
{286}{}{Suspicious? Absolutely. That's because I'm here for revenge.}
{287}{}{I'll try to.}
{288}{}{Open your eyes, you're not all-powerful.}
{289}{}{Hmgh-h. You can breathe the air of freedom until I learn more. Value the time the Holy Fire has given you. And now, get out!}
{290}{}{Not so fast, Mister Tyrant. I'm not leaving without your life.}
{291}{}{Smart move.}

#Repeated dialogue
{300}{}{What is it you want?}
{301}{}{And once again you, the peasant dare to distract me from important matters.}
{1301}{}{And once again you, the peasant dare to distract me from important matters.}
{302}{}{So. What can you tell me?}
{303}{}{I am happy to see you, the messenger from the Brotherhood of Steel.}
{1303}{}{I am happy to see you, the messenger from the Brotherhood of Steel.}
{304}{}{Happy to see you.}
{305}{}{Happy to see you, novice.}
{1305}{}{Happy to see you, novice.}
{306}{}{I thought I would never see you again. What happened this time?}
{307}{}{Holy Fire bless you.}
{308}{}{Goodbye.}
{309}{}{I will leave, with your permission.}

#Questions about the church and the faith
{310}{}{Could I learn more about your faith?}
{311}{}{I would like to become more familiar with your religion.}
{312}{}{There are regular sermons on this topic on the first floor. I don't have time for this.}
{313}{}{I would like to hear it from the most trustworthy source.}
{314}{}{There are regular sermons on this topic on the first floor. I don't have time to explain this to some passerby.}
{315}{}{Then I'll ask someone else.}
{316}{}{Passerby, huh? I see, I see.}
{317}{}{}
{318}{}{Fear the Holy Fire, my child.}
{319}{}{Yes, uhh, of course.}

{320}{}{If you are interested in our faith, then go to a mass. They are held on the first floor. I don't have time to answer every person's questions, after all. Maybe you have something actually *important* to discuss with me?}
{321}{}{Well, actually, yes. There is one such thing - my village.}
{322}{}{No, I'm afraid. I apologize that I wasted your time because of my curiosity.}
{1322}{}{No, I'm afraid. I apologize that I wasted your time because of my curiosity.}
{323}{}{No, I'm just walking around, having nothing to do. If nobody will listen to me here, then I'll go to another place.}
{324}{}{Please, it's important for me to hear something from the first person I talk to.}

{330}{}{Now this is becoming interesting. What *do* you want from me?}
{331}{}{It's about Villa.}
{332}{}{Obviously, your life. It would be reckless to leave a tyrant the likes of you alive.}
{333}{}{Good. My brothers will show you the way.}
{334}{}{No, I'll find it myself.}
{335}{}{You're so kind.}
{336}{}{This is a murderer! In the name of the Fire, stop them!}
{337}{}{Relax, now I'm in charge here.}
{338}{}{They won't be helping you.}
{339}{}{Permission to leave.}

{340}{}{Of course.}
{341}{}{Perhaps we could talk about Villa?}
{342}{}{So, what's your faith about?}
{343}{}{You're the leader of this place, right?}
{344}{}{I've heard enough for now. Thank you for this conversation.}
{345}{}{I say it again - I don't have time for that.}
{346}{}{Fine, I'll go talk to others.}
{347}{}{You're just trying to shake me off.}

{350}{}{You already know all one needs to know about this.}
{351}{}{I respect the fact that you are interested in our teachings. But not all have the power to comprehend them.}
{352}{}{[Continue]}
{353}{}{Our church calls upon people to accept the Holy Fire as an act of healing, as a chance to begin life anew. After all, instead of a rebirth, people have continued pointlessly fighting each other.}
{354}{}{What is this Holy Fire?}
{355}{}{I see it now, you don't have to continue.}
{356}{}{The fire that turned the world to ash a hundred years ago. We call it holy for it punished the fallen mankind and cleansed the world of filth, thus giving the descendants the chance to live a new life.}
{357}{}{Wasn't it some kind of really powerful weapon?}
{358}{}{Technically, yes. But that is irrelevant. For the lord punished humans with their own hands. The average person sees in an atomic bomb just that, an atomic bomb, but we see in it god's plan.}
{359}{}{You said "begin life anew". So the church is trying to change the world?}
{360}{}{By uniting and rallying together the lands for the common goal of survival. To do that, we must return and rethink ancient technology, restore nuclear energy and teach the people literacy.}
{361}{}{So you force others to accept your faith?}
{362}{}{No, of course not. Such novices would harm the church. Only the willing must join. And even then, we are very careful with who we accept. This is why every member of the church needs someone to vouch for them.}
{363}{}{What do you mean "unite the lands"?}
{364}{}{One banner, one nation, one people... one faith. Humanity must reject these mutually-devastating conflicts and fully devote itself toward Rebirth.}
{365}{}{How far has your church spread?}
{366}{}{We have chapels around Phoenix and in a few neighboring towns. In our time, we can say that we have spread very far. But we have many places to spread to yet.}
{367}{}{Now I see how the church is connected to the slavers.}
{368}{}{You create conflict too. Aren't you considered a tyrant who usurped power?}

{370}{}{The average person has fallen to the level of an animal. They are incapable of participating in our great mission of Rebirth willingly. Slavery is merely a temporary, but necessary measure to ensure our success. And even then, we haven't enslaved anyone ourselves. We simply pay mercenaries.}
{371}{}{Sounds inspiring. Could I join your organization?}
{372}{}{Enough! A religion like this has no place in our world. I'll destroy you all.}
{373}{}{Thank you for this conversation, I now know a great deal more.}
{374}{}{By the way, aren't you behind the abduction of Villa's peasants?}
{375}{}{By the way, about the abduction of Villa's peasants.}

{380}{}{And you are the one who manages this entire process?}
{381}{}{Of course.}
{382}{}{That means you'll be the best person to explain the essense of your religion to me.}
{383}{}{Nice to meet you. I wasn't interested in hearing anything else.}
{384}{}{The people consider you a tyrant? Do you know about this?}
{385}{}{Nothing but gossip. Looks like the church got that reputation after the revolution. Yes, we used force to come to power. It was a necessary measure. But our hearts were always full of peace.}
{386}{}{I was under the impression that the cult practically controlled the city...}
{387}{}{The church truly has become something big for Phoenix. We have returned science, education and medicine to the city. We have introduced the bottlecap currency and set up trade routes. Thanks to us, crime rates in the city have been lowered. But most of the population lives outside of our attention.}
{388}{}{Oh wow, this changes things. I would like to know more about your religion.}
{389}{}{Regardless of how many nice-sounding words you hide behind, you will always remain a regular old tyrant. And I will kill you to discourage others.}
{390}{}{I'm afraid I have to go. My regards, lord Aaron.}
{391}{}{You look more like a tyrant than an abbot.}
{392}{}{The church had to take the burden of ruling this city. It is a necessary measure, for society is not yet mature enough for there to be a full-fledged mayor and police force.}

#Villa
{400}{}{I want to talk to you about Villa.}
{401}{}{}
{402}{}{Villa... Yes, I remember our conversation about that village.}
{403}{}{I think we have discussed everything necessary. Goodbye, lord Aaron.}
{404}{}{Hm... Villa... Is that some kind of village? Never heard of it.}
{405}{}{I'm really looking for my relatives. They were enslaved.}
{406}{}{Oh, poor people. I sympathize with you endlessly and will pray for the salvation of your souls. But why has your search brought you here?}
{407}{}{Your cult is clearly involved with this! Give me my relatives back!}
{408}{}{That was not particularly polite of you. We are but a peaceful church, we enslave no one.}
{409}{}{You're lying.}
{410}{}{It is sad to see such ignorance. I am forced to... (one of the advisors interrupts the Overlord and whispers something in his ear) So that's how it is. You wish to reunite with your family? We can arrange that.}
{411}{}{Really? How?}
{412}{}{Put away your weapon and raise your hands. Don't even think of resisting. You will be sent to do hard labor, like your fellow villagers.}
{413}{}{Well, if it helps me find my people, I am going to willingly become a slave.}
{414}{}{You won't scare me. I'll walk out of here the same way I walked in.}
{1414}{}{You won't scare me. I'll walk out of here the same way I walked in.}
{415}{}{It is regretful that it came to this. Capture him!}
{1415}{}{It is regretful that it came to this. Capture her!}
{416}{}{Your words sound more pathetic than the groan of an atom in a fire cloud. Take him to our brothers in Two Sun, let him serve the Holy Fire.}
{1416}{}{Your words sound more pathetic than the groan of an atom in a fire cloud. Take her to our brothers in Two Sun, let her serve the Holy Fire.}
{417}{}{(one of the advisors interrupts the Overlord and whispers something in his ear) Hm. Looks like I'll have to release you. But keep in mind that no person who goes against the church of the Holy Fire goes unpunished.}
{418}{}{Okay, I'll keep that in mind.}
{419}{}{Just tell me what I need to do.}
{420}{}{I thought you knew everything here.}
{421}{}{Unfortunately, that is not true.}
{422}{}{Well, excuse me. I suppose I'll just go somewhere else...}
{423}{}{Wait, I'm not going to resist.}
{424}{}{As a member of the Brotherhood of Steel, I expect full cooperation in the search for the missing peasants.}
{425}{}{It's strange that the Brotherhood has become interested in those peasants. Yes, of course, we'll help you.}
{426}{}{So what do you know about this case?}
{427}{}{You're lying. I'm not leaving until I learn the whole truth.}
{428}{}{Everyone, stop! Don't come any closer! I will defend myself!}
{429}{}{No one here will touch me. Got it?}

{430}{}{Enough of this theater. I KNOW the church sponsored a slave convoy.}
{431}{}{Your arrogance knows no bounds.}
{432}{}{I won't leave until I learn what is going on.}
{433}{}{Go in peace, Brotherhood messenger.}
{434}{}{My regards.}
{435}{}{Pretending to be nice? I'll keep that in mind.}

{436}{}{Who dared to do this to your people? I will not tolerate my bishop being treated like that!}
{437}{}{That's what I want to know, too. Will you help me?}
{438}{}{(gives a sign to a scribe, the scribe searches for something in a computer and then whispers the result) I'm very sorry, but your relatives have already been sent to work in the holy mines to the south.}

{450}{}{Hm. Remind me, how is that village called? (one of the advisors interrupts the Overlord and whispers something in his ear) Uh-uh... Yes, we do know where your relatives are. They received a second chance and are working to restore their karma to the south.}
{452}{}{I remember our conversation. The peasants received a second chance and are working to restore their karma to the south.}
{453}{}{The south? Where exactly?}
{454}{}{Some were left in Flagstaff to work in the mines. The rest were sent to Two Sun to work for the good of Progress. The tinsmiths who live there don't have enough people to work on the forbidden lands. Such a fate is honorable, for with their sacrifice the slaves will help the entire world.}
{459}{}{Why these pointless questions? While you were under their control, you were given an opportunity to learn more about the tinsmiths. The tribe worships ancient technology, though it's definition of that is quite narrow.}
{460}{}{Who are those tinsmiths?}
{461}{}{An occult tribe consisting of worshippers of ancient technology. Like us, they advocate for the rebirth of the old world, but they see it in a purely technological way. At the moment, we have the same goals, but one day misunderstanding will turn to conflict.}
{462}{}{Why do you care for their technology?}
{463}{}{Without the tinsmiths' production base, we wouldn't even have electricity in this building. We need their tools and skills.}
{464}{}{You both need to be destroyed. I think it's better to begin with this pathetic, godless cathedral.}
{465}{}{This explains everything. I have no more questions.}
{466}{}{The Flagstaff prison - that your doing too?}
{467}{}{The Flagstaff colony was created using our caps. But over time, it became more free and independent.}
{468}{}{Why do you need that colony?}
{469}{}{Obviously, for the uranium extracted in the local mines.}
{470}{}{But why does the church need uranium ore?}
{471}{}{Uranium is necessary to produce nuclear energy. Without it, it is impossible to utilize old technologies. And without them, restoring civilization would be an impossible dream.}
{472}{}{Does Faber create problems for you?}
{473}{}{Faber starting to tread on your feet?}
{474}{}{In a way. Sometimes you eat the pigrat and sometimes the pigrat eats you. Faber shares many of our views, but has his own interpretation. This sometimes causes small conflicts.}
#- Quote from the movie "The Big Lebowski": Sometimes you eat the bear and, well, sometimes the bear eats you.
{475}{}{Great. Then I'll follow in his footsteps and take over this defenseless church.}
{476}{}{I think I should head to Flagstaff and find everything out myself, personally. Goodbye.}
{477}{}{In a way. By allowing people to come to power, you always risk making an enemy from someone who was once a friend. But it has become known that Faber is no longer in power. Whether he was killed by accident or it was a cunning plan of a local revolution is unknown. We are still dealing with that problem.}
{478}{}{What did you say about the tinsmiths?}

{480}{}{Enough lies. I'm outta here.}
{481}{}{Looks like you have grand plans. Now I can walk out of here in peace.}
{482}{}{But why do you defend slavery?}
{483}{}{But why do you defend slavery?}
{484}{}{Society is not ready to be free. These people will never rise from the ground on their own. They need tyrants and strong, guiding leaders.}
{485}{}{So you are responsible for the enslavement of Villa?}
{486}{}{Don't be so rash with accusations. We simply sponsor our colonies and various other projects with caps. And if the effort of slaves is necessary to support them, the caps will be used to buy them.}
{487}{}{This is shameful for the church. You must dissapear.}
{488}{}{An interesting point of view. Even though it won't become common where I live.}
{489}{}{Coercion is the worst way to develop a society.}
{490}{}{Oh, you're wrong. Society is not ready to be free. It needs tyrants and strong, guiding leaders.}
{491}{}{How is this related to the tinsmiths of Two Sun?}
{492}{}{I see now the relationship between you and the Flagstaff jailers.}

#Becoming a Follower
{500}{}{I am thinking of joining your church.}
{501}{}{That is not as easy as you think. To be accepted, one needs to have someone vouch for them or do important tasks. What can you say in response?}
{502}{}{I don't have anyone who could vouch for me.}
{503}{}{Our church often finds itself the target of attacks. Prove that we can trust you - and then we will talk about your initiation.}
{504}{}{I'll try to find someone to vouch for me.}
{505}{}{How can I prove my devotion?}
{506}{}{. . . [test assignment]}
{507}{}{I will return when the matter is settled.}
{508}{}{I'll do anything I need to in order to receive illumination from the Holy Fire.}
{509}{}{These words are far too pompous for a passerby.}
{510}{}{Fine, I'll go find someone to vouch for me.}
{511}{}{But I really do want to join your church.}
{512}{}{To be accepted, one needs to have someone vouch for them... But I doubt the pureness of your moties, peasant from Villa.}
{1512}{}{To be accepted, one needs to have someone vouch for them... But I doubt the pureness of your moties, peasant from Villa.}
{513}{}{Ulysses Grant suggested I talk to you.}
{514}{}{Is being a member of the Brotherhood of Steel enough?}
{515}{}{Here is a letter of recommendation written from a preacher in Flagstaff.}
{516}{}{(listens to the whispers of the advisor) This letter doesn't mean anything anymore. Get out.}
{517}{}{Umm, but...}
{518}{}{I had a letter of recommendation from Flagstaff. But it was lost somewhere.}
{519}{}{I lost the desire to become part of your religion anyways. Goodbye.}
{520}{}{Arthur Carrington can vouch for me.}
{521}{}{Francis will vouch for me.}
{522}{}{Give me a chance.}
{523}{}{Here is a letter of recommendation from George Crook.}

{530}{}{In that case, I'm happy to see you in our abode of wisdom and progress. Our church is trying to heal the world from the wounds inflicted on it by the Great War. And you will help us in this hard mission.}
{531}{}{Great. What can I do for the church?}
{532}{}{I do not think there is any need to explain that the church has many enemies. Lately, hostility has been rising. Several novices were killed right on the city's streets, in full view of everybody. I am asking you to investigate these crimes.}
{533}{}{They will regret ever choosing to attack them. But where should I start?}
{534}{}{Find Gabriel, he preaches by the city gates and knows much about local happenings. But... be gentle. His fanaticism often scares even members of the church.}
{535}{}{I will return when the matter is settled.}
{536}{}{I will do everything in my power.}

#First quest
{550}{}{Regarding the crimes against the church.}
{551}{}{Have you managed to come closer to the truth?}
{552}{}{Unfortunately, no. This case has too many unknowns.}
{553}{}{It is regretful to hear this. But I have not lost hope yet. Speak to Gabriel by the city gates, he will tell you the details of the attacks.}
{554}{}{Okay, I'll go to him.}
{555}{}{Looks like you've earned yourself serious enemies. They're well-organized and have excellent equipment. And more importantly - they're watching you.}
{556}{}{You mean to tell me those attacks weren't spontaneous? That someone was watching the novices and prepared for the attacks?}
{557}{}{Yes.}
{558}{}{(pursing his lips in thought, approaches the altar) It is likely so. But nobody beyond this building knows our routines. The schedules for the novices are made a week beforehand. If the attackers were preparing, as you said, then how did they learn of those plans?}
{559}{}{Who has access to the schedule?}
{560}{}{Each person who vouched for someone makes their schedule and brings it to the library. Only a few people have access to them all.}
{561}{}{Looks like it's time for me to visit that treasure trove of ancient books. I will go, with your permission.}
{562}{}{Alright, I'll go there and find out.}
{563}{}{Well, I dunno. It could be the truth...}

{570}{}{Mathias turned out to be the spy. He watched the novices' schedules and sent the data to enemies of the church with a radio station.}
{571}{}{(Aaron's lips become filled with blood from the anger) Mathias... I should have guessed beforehand. How could one of my closest advisors betray me? Guards! Put Mathias under arrest.}
{572}{}{Be gentle with him.}
{573}{}{That's right. Shock his balls off.}
{574}{}{(wanders around the room in thought) Deceit is all around me... I cannot even trust my closest subordinates. Nobody could have imagined that Mathias hated the situation in the church so much.}
{575}{}{He was against your policies, wasn't he?}
{576}{}{Mathias advocated for the isolation of the church from the outside world and the total conservation of our artifacts. He did not want to share them with other groups and did not see anybody who would be worthy of them. I did not agree. The time has come for that knowledge to be taken out of the dust and mold in the name of the Holy Fire.}
{577}{}{Looks like that didn't sit well with everyone.}
{578}{}{(makes a gracious face) You've done well, brother. And more importantly - remained loyal. I need more of your help to purge filth from the lands of Phoenix.}
{1578}{}{(makes a gracious face) You've done well, sister. And more importantly - remained loyal. I need more of your help to purge filth from the lands of Phoenix.}
{579}{}{Anything for the Holy Fire, your holiness.}
{580}{}{What is needed from me this time?}
{581}{}{It is obvious that there is a gang of Fire-haters in the city. Well-organized and well-equipped ones. We'll extract all the information we can from Mathias, but that won't be enough. You are to find their nest and infiltrate their ranks. Will you be able to do it?}
{582}{}{Perhaps. But why me?}
{583}{}{You are still quite new to our church. I doubt the rebels will recognize you as one of us.}
{584}{}{If I find where they are hiding, what am I to do next?}
{585}{}{Go back to me and tell me where that place is. We will then decide what to do next.}
{586}{}{How am I to do this?}
{587}{}{Mathias used a radio to contact the rebels. And many people in the city must be connected to this group. Use all the means availaible to you.}
{588}{}{I will do everything in my power. I will leave now, with your permission.}
{589}{}{But why me?}
{590}{}{But you ended up very selective when considering who is "worthy", right?}

#Second quest
{600}{}{The situation with the rebels has become more clear.}
{601}{}{Really? Do tell me all about it.}
{602}{}{Though, to be honest, it's all questionable rumours. We shouldn't rush with conclusions.}
{603}{}{The rebels were hiding in the sewers. Now their leader is dead, the party split and crushed...}
{604}{}{...Very good. I will send my people to clean up the nest of those criminals and hand it to you. Looks like the Holy Fire itself has given us illumination in the form of your body.}
{605}{}{I can continue serving the church, if that will prove useful.}
{606}{}{I have no doubts about that, my child. And more than that - we need friends more than ever in this time.}
{607}{}{How can I help, lord Aaron?}
{608}{}{I know where the headquarters of the Liberation Party are located.}
{609}{}{Perhaps you managed to come across our preachers beyond Phoenix's limits. The church is growing and is opening it's chapels where the people are ready to listen. But the village of San Brahmin has become a stumbling block for our faith.}
{610}{}{[Continue]}
{611}{}{The locals, at first friendly, for some reason have become angry at the church. Our attempts at talking sense into them have only served to make the situation worse. We do not know what exactly is going on out there. Right now, George Crook's unit is on the outskirts of the village. Find it and offer your help. We need to restore our trade agreements with that settlement.}
{612}{}{[Continue]}
{613}{}{Here are 350 caps for the trip and for the purchase of everything necessary. Go. May the Holy Fire bless you.}
{614}{}{I'm already going, lord Aaron. San Brahmin will soon come to believe in the strength of the Holy Fire.}
{615}{}{I will do everything in my power.}
{616}{}{You have already helped many people, my friend. George Crook told me of your deeds. I was thinking of sending you to help him, but you managed to get ahead of me. Now I want to hear it from you personally: what is the situation in San Brahmin?}
{1616}{}{You have already helped many people, Atom's fair lady. George Crook told me of your deeds. I was thinking of sending you to help him, but you managed to get ahead of me. Now I want to hear it from you personally: what is the situation in San Brahmin?}
{617}{}{I do have much to tell you.}

#Third quest
{630}{}{I have to talk to you about the situation in San Brahmin.}
{631}{}{Of course. What news do you carry, my child?}
{632}{}{I will soon arrive to that place and learn all the details. Goodbye.}
{633}{}{[CHEAT: situation resolved in the best way for the Overlord]}
{634}{}{[Blah-blah glory to the Fire - blah-blah talk to Advisor in vault, here be the key and access - blah blah liquidate George Crook]}
{635}{}{[CHEAT: conclusion of quests - receive title + get sent to vault + reward + church radio frequency]}
{636}{}{I carry news of victory, lord Aaron. The tribe's chieftain has agreed to an alliance, and Crook's unit has relocated closer to the village.}
{1636}{}{I carry news of victory, lord Aaron. The tribe's chieftain has agreed to an alliance, and Crook's unit has relocated closer to the village.}
{637}{}{Glory to the Holy Fire! Are you sure god himself has not sent you to help us in this trying time? This is a miracle. You deserve the highest reward.}
{638}{}{It was my holy duty.}
{639}{}{I don't know whether the Holy Fire helped me or not, but I did it.}
{640}{}{Hm, in his report, George Crook praises your personal qualities and loyalty to the empire. Considering your previous help to the church, I am obligated to give you a reward.}
{641}{}{This is a great honor, your holiness.}
{642}{}{In what way?}
{643}{}{For your help to the Phoenixian empire, I am proud to call you my bishop. Take in a sign of gratitide these consecrated robes. May they protect you from lies and the bullets of your enemies.}
{644}{}{Thank you.}
{645}{}{The time has also come for you to become a member of our secret group. Here are the keys to the basement. There, you will find an ancient sanctuary. Tell the guards that you are to be brought to Ulysses Grant. I will inform him of your arrival.}
{646}{}{[Continue]}
{647}{}{Go, my friend. May the Fire bless you.}
{648}{}{Thank you, lord Aaron.}

{650}{}{My lord, I have worrying news - George Crook has died in the course of completing his mission.}
{651}{}{(sighs heavily and prays) May the Holy Fire rest his soul. He was the best warrior I knew. If even he couldn't resist the savages, who can complete his mission?}
{652}{}{I don't think I'll be able to.}
{653}{}{Perhaps I will be able to.}
{654}{}{Go back to San Brahmin and conquer the tribe in the name of the Fire! This is your holy duty. And if you can't, then sow discord in the tribe. Kill their head chieftain, so that the savages fight each other for his lousy throne. Force the Rangers to flee the pueblo. Go. Go!}
{655}{}{Yes, my lord...}
{656}{}{Bad news. The tribe has made an alliance with the Rangers, and the Rangers forced the missionaries to leave the pueblo and the nearby lands.}
{657}{}{(sighs heavily and prays) We are too late. So many resources, so much effort spent on conquering the tribe, now wasted!}
{658}{}{Is it truly all lost?}
{659}{}{Perhaps I will be able to change the chieftain's mind.}
{660}{}{The chieftain is dead. The tribe is	no longer united. Now even the Rangers will have a hard time taking advantage of the situation.}
{661}{}{It is hard to recognize defeat. But how many persecutions did we endure before? It's nothing. We'll wait. They have been gradually sinking lower and lower for many generations. I suspect it will take just as much time to drag them back to our civilized way of living.}
{662}{}{[Listen]}
{663}{}{Your service ends now. Regardless of how much I'd like to kick you out of the cathedral for so many failures, my advisors have come to a different conclusion. I will allow you to meet my main advisor, Ulysses Grant. Take this key and go down to the basement. Security will escort you to Ulysses. He is waiting for you.}
{664}{}{Thank you, my lord.}
