{100}{}{You see a mercenary.}
{101}{}{Here is a strong man dressed in heavy armor.}
{102}{}{You have lost your personal bodyguard.}
{103}{}{Time is up, your bodyguard has returned to the caravan park.}

{110}{}{This caravan site is probably the safest place in the city.}
{111}{}{This is the shopping center of the city. They won't kill you here, but they'll clean your pockets so that you won't have time to whistle.}
{112}{}{Be careful. A gang of cardinals rules in these slums. If you get into trouble, I can't help you.}
{113}{}{An ancient power plant is ahead. It still provides electricity thanks to local ghouls.}
{114}{}{In front of you is the Cathedral of the Sacred Fire. I'm sorry, but I'm not going inside.}

#Dialogue without accompaniment
{200}{}{Hey, you're new in town, aren't you?}
{201}{}{Exactly. I'm wondering what the city has to offer a newcomer like me.}
{202}{}{Of course, Phoenix is huge! The biggest city these days.}
{203}{}{It's like you want to add a "but".}
{204}{}{Great, I can't wait to see everything here.}
{205}{}{But I'll tell you what - be careful, now is not the best season for sightseeing.}
{206}{}{Why?}
{207}{}{Really? Aren't you talking my teeth out?}
{208}{}{What's your business?}
{209}{}{Whoa, don't be so tense. I'm the one who takes all the strain on himself. Surely you want to see the sights of the great Phoenix?}
{210}{}{Suppose yes.}
{211}{}{Of course!}
{212}{}{Then I'll tell you what - be careful, now is not the best season for this.}
{213}{}{The city has been restless for several years now. There are areas where thugs run everything, and thefts happen in the market. It's better not to appear on the streets alone.}
{214}{}{What do you suggest?}
{215}{}{And of course, you know how to protect yourself?}
{216}{}{I accompany important people within the city. Just the sight of an armed guard is enough to get all the trash behind you. But you already have security, I see. If you are left without protection, apply. I am a professional in this business.}
{217}{}{I'll keep that in mind. Bye.}
{218}{}{I accompany important people within the city. Just the sight of an armed guard is enough to get all the trash behind you. If you decide to get security, contact me, I'm a professional in this business.}
{219}{}{I'll think about it. And now I have an urgent matter. Bye.}
{220}{}{I can take care of myself.}
{221}{}{I do not argue! Hit me if you have any doubts. But if you change your mind, you know where to find me.}
{1221}{}{Oh, I willingly believe, lady! But if you change your mind, you know where to find me.}
{222}{}{I'll think. Bye.}
{223}{}{It seems that every big city begins with deception. I'm leaving.}
{224}{}{Consider me interested in you. How much do your services cost?}
{225}{}{For you, it will cost in }
{226}{}{ caps per hour. But no barter.}
{227}{}{I can't afford it. Goodbye.}
{228}{}{Persuaded. Here are the bottlecaps.}

{230}{}{Phoenix to your hands, baby, while I watch my back.}
{231}{}{I'm all at your disposal.}
{232}{}{You won't need a doctor or a priest while I'm around.}
{233}{}{I'll be damned if something happens to you.}
{234}{}{Don't worry, every dog here knows me.}
{235}{}{Don't worry, I know every corner in this metropolis.}
{236}{}{Now you can relax and have a good time.}

{239}{}{Cool. Now I have a personal bodyguard.}

{240}{}{Do you need a bodyguard? I advise you to get one or a hefty grenade launcher like that.}
{241}{}{Yeah. Bye.}
{242}{}{Are you still doing security?}

#Dialogue during escort
{250}{}{Oh, please.}
{251}{}{Clear ahead.}
{252}{}{The way is clear.}
{253}{}{Don't piss in your pants. There's nothing to be afraid of.}
{254}{}{Relax, I'll get you out of any scrape.}
{255}{}{What?}
{256}{}{Any problems?}
{257}{}{Yes?}
{258}{}{This area is controlled by a gang of cardinals. If life is precious, then I advise you to leave here immediately.}
{259}{}{Okay, let's go.}

{260}{}{Wait for me here until I get back.}
{261}{}{Whatever you say. But if time runs out, I will return to the caravan site.}
{262}{}{Don't go anywhere.}
{263}{}{Follow me.}
{264}{}{Whatever you say, Chief.}
{265}{}{Forward.}
{266}{}{I don't need your services anymore.}
{267}{}{Are you sure? I will not return the bottlecaps for the rest of the time.}
{1267}{}{Are you sure? I will not return the bottlecaps for the rest of the time.}
{268}{}{Yes, you're free. If I need you, I know where to find you.}
{269}{}{Okay, I'll tolerate your presence for a while longer.}