{100}{}{You see Bruce.}
{101}{}{You see a man in a business suit. His calm gaze shows indifference to human life.}
{102}{}{Power armor, right? Impressive. But one doesn't talk to others while wearing it.}
{103}{}{Well, well, well, another junkie from the streets. Come back when you get yourself in order.}

#Introductory dialogue trees
{200}{}{Welcome. I'm Bruce Turner, and this is the recruiting agency. You need some tough people for security? Or are you looking for a fugitive?}
{201}{}{Perhaps.}
{202}{}{...}

{210}{}{Well I'll be damned, what the hell is wrong with your skin?}
{211}{}{A bit of a virus and radiation. Nothing too bad.}
{212}{}{Hm. I wouldn't joke about it if I were you.}
{213}{}{If you were me, you would already be dead.}
{214}{}{I'm just used to it, mister.}
{215}{}{You laughing at me, smoothskin?}
{216}{}{(raises brow) No. No problem, greenie.}
{217}{}{Good.}
{218}{}{I could get really offended the next time.}

{220}{}{Good day, sir. Happy to see you. Is anybody bothering you?}
{1220}{}{Good day, ma'am. Happy to see you. Is anybody bothering you?}
{221}{}{Why are you being so nice to me all of a sudden?}
{222}{}{Obviously, you earned it... sir.}
{1222}{}{Obviously, you earned it... ma'am.}
{223}{}{Well, well, well, here comes our new celebrity. Your activity in this city has went too far. You think you'll get away with this?}
{224}{}{The people here are so vile and dastardly. We, peasants live in a much better environment.}
{225}{}{You shouldn't have crawled out of your desert. I'll return your body to the sands... your dead body.}
{226}{}{What are you...}
{227}{}{I'll defend myself.}
{228}{}{I'm surviving as best I can. It's not your place to judge me.}
{229}{}{It's not just my place, the city pays me to find criminals. You are one. Guys... (gives a sign)}
{230}{}{Don't do it, Bruce...}
{231}{}{I'll defend myself.}
{232}{}{I don't want to get involved in a fight. Let's negotiate.}
{233}{}{Everyone uses all availaible means to survive. You aren't doing entirely honest work here either. Am I right?}
{234}{}{Hm. Interesting. I don't know who to believe. But I do know that if you don't leave the city, you'll soon be hanging from a lamp post. Am I clear?}
{235}{}{Very.}
{236}{}{Go to hell, Bruce. You and your entire agency.}
{237}{}{Happy to hear it.}
{238}{}{Flattery doesn't fit a merc boss. But I value it.}

{240}{}{Don't move. First, I want to know what happened between you and the followers of the Fire.}
{241}{}{It's between us both. Not for you to know.}
{242}{}{You're wrong. This is a mercenary guild, not a brothel. I worked with the Fire-worshippers for years, transporting slaves and those sentenced to hard labor across the desert. And then you waltz in and deny me a huge amount of contracts. What the hell?}
{243}{}{I'm telling you - it's personal.}
{244}{}{A-ah, we're talking about revenge? I understand. Good for you that the followers can't pay for your head yet. But if that does happen, I promise you - your head will be lying on this table in days.}
{245}{}{You're scaring me. It would be better if I left this building.}
{246}{}{I doubt that it will come to that, Bruce. Until next time.}

{247}{}{Adios, banditos.}
{248}{}{[Show middle finger]}
{249}{}{Whatever you say, you're the boss.}
{250}{}{How unexpected. Usually WE chase criminals, not vice versa.}
{251}{}{Who *is* the criminal here?}
{252}{}{But I'm not a criminal.}
{253}{}{Do you know that Flagstaff has declared you public enemy number one? Luckily for you, the town can't reward us for catching you. But now I know who you are and where I can find you. Keep that in mind and don't cause any problems.}
{254}{}{No problem, sheriff.}
{255}{}{I'm not a sheriff, you idiot. But if I need to, I'll be worse than any sheriff can be.}
{1255}{}{I'm not a sheriff, you idiot. But if I need to, I'll be worse than any sheriff can be.}
{256}{}{Suure.}
{257}{}{I don't like your tone. I'll come back when you calm down.}
{258}{}{Then stock up on ammunition. Because you won't take me so easily.}
{259}{}{(slowly places hand on machine gun while looking into your eyes) Get out of my office.}

{260}{}{Welco... Wait. Show me your neck. Those are collar marks. Strange for a runaway slave to go here. What do you want, slave?}
{261}{}{Don't call me like that. Or you'll regret it.}
{262}{}{Looks like you don't understand your precarious position. Guys... (gives sign)}
{263}{}{Just not the face...}
{264}{}{I'll kill all slavers in Arizona.}
{265}{}{I want my freedom back. The tinsmiths treated me badly.}
{266}{}{Hm. The tinsmiths aren't going to buy a runaway slave again for the same price. You're putting me in a difficult situation. Well, I'm ready to buy back your rights and officially declare it. But that will cost you 1000 caps. I doubt you have that kind of money.}
{267}{}{I'll find it.}
{268}{}{Then I have no other choice... I'll kill you.}
{269}{}{Hm. Okay, deal. I'm waiting for the 1000 caps.}

{270}{}{(squints, examining your face) Hm. Some information about one particular highwayman was sent to me. And you remind me of the description.}
{271}{}{It's a coincidence. Do you even have any proof?}
{272}{}{No. But I'll keep my eye on you.}
{273}{}{Of course.}
{274}{}{Don't even think about it.}
{275}{}{The highwaymen made me an intermediary in negotiations.}
{276}{}{How unexpected. If that's the case, maybe it's for the best. Well, while you're in the city, watch yourself. The locals aren't exactly thrilled with the highwaymen.}
{277}{}{They have many enemies, that's for sure.}
{278}{}{You know too much, Bruce. It's regretful, but I'll have to shut you up...}

{280}{}{That's highwayman armor. Where did you get it from?}
{281}{}{A battle. It's a trophy.}
{282}{}{Hm. Fine, I can buy that. But it's best to not wear it in thir city. Many heard about the higwaymen here and could think you are one.}
{283}{}{Thanks for the warning.}
{284}{}{I don't give a shit about the locals.}
{285}{}{A gift from one really nice man.}
{286}{}{You have dangerous friends. I suggest you hide this somewhere away while you're in the city. The locals heard about the highwaymen. You could accidentally walk into a bullet.}

{290}{}{Well, well, well, here comes another victim of the desert. They say you stirred up hell in Casa Grande. Is that true?}
{1290}{}{Well, well, well, here comes another victim of the desert. They say you stirred up hell in Casa Grande. Is that true?}
{291}{}{What are you talking about? I have excellent relations with the locals.}
{292}{}{Don't lie to me, friendo. My sources can't be that mistaken.}
{1292}{}{Don't lie to me, dear. My sources can't be that mistaken.}
{293}{}{Why do you care?}
{294}{}{Yeah, I had to shut a few people up. The locals are too suspicious.}
{295}{}{(raises brow) So you admit it? This greatly simplifies the case.}
{296}{}{Why do you care?}
{297}{}{You're lucky that the locals can't put a bounty on your head. But keep in mind that this could change at any time.}
{298}{}{Of course. I'll be quiet.}
{299}{}{I really doubt that.}

#Main dialogue
{300}{}{Welcome. How can I help?}
{301}{}{I do not recommend making sudden movements. What do you want?}
{302}{}{I represent the interests of Chuck from the Blue Shield gang.}
{303}{}{Just a minute... Yes, it is some kind of petty thief the mayor of Casa Grande is giving a reward for. Do you want to prove his innocence or pay for his head? That reward I mentioned is 250 caps.}
{304}{}{Pay. Here are the caps.}
{305}{}{The criminal is now officially free. I will also send these news to Casa Grande.}
{306}{}{Thank you.}
{307}{}{I don't have that kind of money. Goodbye.}
{308}{}{}
{309}{}{Until next time.}

#Slave reputation
{310}{}{I want to buy back my freedom.}
{311}{}{We have already discussed this. Do you have 1000 caps?}
{312}{}{No.}
{313}{}{Then the matter is settled.}
{314}{}{Fuck...}
{315}{}{Here are the caps.}
{316}{}{To be honest, I'm surprised. I doubt those caps were obtained legitimately, but I really don't want to know.}
{317}{}{What about your end of the bargain?}
{318}{}{It will take some time...}
{319}{}{I'll wait...}
{320}{}{Done. You are now officially free. Congratulations. Value your second chance.}
{1320}{}{Done. You are now officially free. Congratulations. Value your second chance.}
{321}{}{Of course. Farewell.}
{322}{}{Hey, don't you pretend that you were freeing a former criminal. The reality is completely the opposite.}

#Cardinal quest
{323}{}{You'll regret this.}
{324}{}{Bruce, release the guy. He's my old friend. You wouldn't refuse my request, right?}
{325}{}{You're a respected man. Of course, I trust you. But don't get into trouble with those cardinals. It's easy to ruin your reputation by associating with them.}
{326}{}{I'll deal with it. Thanks for the understanding, Bruce.}
{327}{}{He's my old friend. He's an innocent man. Release him.}
{328}{}{I don't know you, and your words mean nothing in this city. If you continue to stand in the way of my work - you'll end up in the same cell for aiding a known criminal.}
{329}{}{Okay.}
{330}{}{I know that you've apprehended a Red Cardinal.}
{331}{}{Yeah, he should spend some time in that cell and think about his future. But how do YOU know this? Nobody but the capture groups were in the know.}
{332}{}{I have sources. What's he guilty of?}
{333}{}{This case isn't worth publicity. The client told me to stop the deal, I don't know anything beyond that either.}
{334}{}{Alright. Good luck.}
{335}{}{I need to see him. I'll pay 10 caps for it.}
{336}{}{Good. You have 10 minutes.}
{337}{}{Here are the caps.}
{338}{}{Not now.}
{339}{}{How much did you get paid to find him? I'll pay you more to release him.}
{340}{}{Hm. If you think about it, he's nothing. I'll release him on a bail of 100 caps.}
{341}{}{Good. Here are the 100 caps.}
{342}{}{This is too much. He isn't worth it.}
{343}{}{Can I just talk to him? I'll pay 10 caps for it.}
{344}{}{Though it doesn't guarantee that we won't see him again. You know those cardinals? A bunch of degenerate hooligans. They're a threat to society.}
{345}{}{I won't argue with that.}
{346}{}{People in the Temple of Fire are worried about what happened. That guy was a part of our spy network. Release him. Immediately.}
{347}{}{So that's how it is. I did think that espionage was likely involved in this case. Alright, I don't want any problems with your church. He'll be free to go. But if that's not true - you'll be responsible.}
{348}{}{Thanks for the understanding, Bruce.}
{349}{}{Okay.}

#Questions about slaves
{350}{}{Tell me what is it you do here.}
{351}{}{This is a recruiting agency. We're looking for some real tough people to do dangerous missions. Usually it's guarding someone or finding criminals. Do you need anything out of that?}
{352}{}{No, I don't.}
{353}{}{Well, if you end up needing it, I'll be glad to help. For a price, of course.}
{354}{}{Of course.}

{360}{}{Are you involved in slave trading?}
{361}{}{Slave contracts? Few can afford such luxury.}
{362}{}{Who could those few be?}
{363}{}{Main clients are the Flagstaff colony and the tinsmiths. Though I wouldn't call those goods slaves. Usually they are criminals serving their sentences. Why are you asking?}
{364}{}{I'm curious.}
{365}{}{Just being curious is suspicious. I hope you know what this means.}
{366}{}{Uhh, yeah, I think I do.}
{367}{}{I'm thinking of buying a few slaves.}
{368}{}{That's stupid. We won't give you a single one.}
{369}{}{Forget it then.}
{370}{}{I'm looking for slaves from Villa.}
{371}{}{Villa... This doesn't say anything to me.}
{372}{}{I'm looking for slaves from Villa. They were brought here from Flagstaff.}
{373}{}{Villa... This doesn't say anything to me. If those slaves were in Flagstaff, then finding them will be a hard task indeed.}
{374}{}{Alright. Sorry for the disturbance.}
{375}{}{Ugh, I'll have to figure everything myself again. Farewell.}
{376}{}{I'll pay 100 caps for the information.}
{377}{}{Sounds acceptable. I can study the invoices for the latest transfers and contact our agents. Payment first.}
{378}{}{Here are the caps. I'll wait.}
{379}{}{No need to, I'll try to figure everything out myself.}
{380}{}{Some things have become more clear. A few slaves from Villa really did end up in the Flagstaff colony. They were bought by the Fire-worshippers and sent to their Cathedral. Looks like they were damn good slaves, if they were transported over such distances. Only the monks know what happened to them. }
{381}{}{Thanks, Bruce. Time to head into that Cathedral of Fire. Or whatever they call it.}
{382}{}{Dammit. I would have figured that out myself.}
{1382}{}{Dammit. I would have figured that out myself.}
{383}{}{Some things have become more clear. A few slaves from Villa really did end up in the Flagstaff colony. They were bought by the Fire-worshippers and sent to do hard labor in Two Sun. Looks like they were damn good slaves, if they were transported over such distances.}
{384}{}{Thanks, Bruce. Time for me to visit that questionable little settlement. I hope caravans go there.}
{385}{}{You know, Bruce, you weren't particularly helpful. Bye.}
{386}{}{I'll be back later. I don't have so many caps at the moment.}

{390}{}{I need to get rid of a certain troublemaker. His name is George Crook.}
{391}{}{The commander Crook that subjugated the western tribe? Why do you want to get rid of him?}
{392}{}{I am only representing the interests of my client.}
{393}{}{Understood. The old fighter managed to get on the wrong side of many people in the city. And more than that - the best men I had switched over to his unit. And now Crook is just throwing money away, having no idea what to do. I have no idea how the casino manages to tolerate his drunken antics.}
{394}{}{So you're taking this on?}
{395}{}{Well, I did not say this, but for 500 caps, the world will forget he ever existed.}
{396}{}{I need some time to think it over. This is serious stuff, you know.}
{397}{}{Deal. Here are the caps. And yes, I did not say this either. I was not here.}
{398}{}{Don't worry, we'll make sure it goes smoothly.}
{399}{}{I'm counting on you, guys.}

#Bounty hunting
{400}{}{I'm interested in hunting criminals. Who is being paid for and how much?}
{401}{}{(sigh) Another bounty hunter...}
{1401}{}{A bounty huntress in a lace apron? What's this world coming to...}
{402}{}{Something wrong?}
{1402}{}{Ahem. Do I need to remind you that your guard is a woman?}
{403}{}{A-ah, so it's you the whole city is praising for the last few fights in the arena? This changes things.}
{404}{}{I can stand up for myself. That's for sure.}
{405}{}{}
{406}{}{}
{407}{}{Do you even have a rifle? This is dangerous stuff, there's no room for amateurs. But if you want to risk your skin - that's your business.}
{408}{}{I'll manage to do it.}
{409}{}{There's a notice board on the street. It has the most up-to-date information. The system's simple. You find a criminal that fits the description, bring back his head to me and receive a reward. Any questions? Then go ahead. Good luck.}
{410}{}{Until next time, Bruce Turner.}
{411}{}{I want to talk to you about bounty hunting.}
{412}{}{Managed to catch anyone?}
{413}{}{No. Not yet.}
{414}{}{Just like I thought. Come back when you catch at least one.}
{415}{}{Fine.}
{416}{}{I'm a Ranger. I'm looking for a job.}
{417}{}{Usually the Rangers don't have a high opinion of our agency. It's strange that this appeals to you.}
{418}{}{I'm a lone Ranger.}
{419}{}{Okay...}

{420}{}{Here's the head of Ernando Aviles.}
{421}{}{A-ah, our old friend Ernando. Looks like you won't be making any more jokes about me, am I right, you fucking bastard?}
{422}{}{Here's the head of Chucho Navarro.}
{423}{}{What a son of a gun, he stirred up so much trouble. I'm glad his noisy mouth will not make a single sound from now on.}
{424}{}{Here's the head of Adie Gorme.}
{425}{}{Oh, and to think she was once a beautiful woman that performed in the casino. A strange fate. I don't get what caused her to lose her mind.}
{426}{}{[Continue]}
{427}{}{Ernando Aviles is dead. But I didn't manage to acquire his head.}
{428}{}{Chucho Navarro is dead. But I didn't manage to bring his head.}
{429}{}{Adie Gorme is dead. Unfortunately, her head has been left in the desert.}
{430}{}{No head - no reward. But I'm happy to hear this. Until I receive information that says otherwise, I'll assume you're speaking the truth.}
{431}{}{Uhh, alright.}
{432}{}{I won't receive caps? That's very bad.}
{433}{}{Excellent work. Here are your 500 caps. I hope you aren't going to be abandoning this kind of thing? We need people like you.}
{434}{}{I'll think about it.}
{435}{}{I dunno, this kind of activity is too dangerous.}

{440}{}{Wait. So that was the last Los Panchos chieftain? The damned gang has finally fallen. Imagine how these news will spread all over Phoenix. O-oh, this will be a real celebration for the people.}
{441}{}{No doubt. But are there no other chieftains?}
{442}{}{The trio controlled the biggest and most dangerous Los Panchos clans. The rest did not pose a significant threat. Now, without their atamans, their entire empire will dissolve, and the regular bandits will be severely weakened. No doubt the clans already declared war on each other, trying to get more power.}
{443}{}{This is a bit strange. But even stranger is that the atamans had the same mark that you and your mercs have.}
{444}{}{Hm. This would become known some day anyway... We made them out to be a bit worse than they were. In reality, the trio worked as mercenaries in our guild. Here, they learned a lot. But when they felt like they had power and control over people, they stopped being interested in honest work.}
{445}{}{You should have warned me about this.}
{446}{}{Those people would be terrible for the guild's reputation. We can't allow that to happen.}
{447}{}{A prudent decision.}
{448}{}{Actually, I don't care.}
{449}{}{That's enough fulfilled contracts from you. Go rest and relax for now. And meanwhile, I'll think what job I could give you later.}
{450}{}{More work? Great, I'll be awaiting with great anticipation.}
{451}{}{I doubt that I would want to work for you after what I've heard. Farewell, Bruce.}
{452}{}{Well, those are great news.}
{453}{}{I'm more concerned about the caps. You'll handle the other stuff.}
{454}{}{Exactly. Go rest and relax for now. And meanwhile, I'll think what job I could give you later.}
{455}{}{More work? Great, I'll be awaiting with great anticipation.}
{456}{}{I have enough caps to leave this business. Farewell, Bruce.}
{457}{}{What about a new job?}

{460}{}{You're just in time. I wanted to send someone to find you. There's a new target. And this time, I'll pay more.}
{461}{}{It's kind of obvious that the new target is worth that kind of money. What is he guilty of?}
{462}{}{(shows a portrait) This is Gil McCord. AKA one of the best marksmen and pathfinders in the world. He knows his field well and can get out of anything. That's why he can't be left alive.}
{463}{}{Hm. That's strange. It's almost like you're not telling me something. Why are mercenaries chasing after a mercenary?}
{464}{}{(sigh) You see, I somewhat made our achievements to be better than they are. In reality, the Los Panchos chieftains were once our mercenaries. Here they learned many things and that's exactly how they were able to establish themselves outside the city.}
{465}{}{And what about Gil McCord?}
{466}{}{He was their intermediary and spy. That was discovered after we cleaned up Los Panchos bases. Looks like Gil was too greedy and untrusting, so he was playing both sides to come out on top in the end, regardless of what happens.}
{467}{}{You should have told me the truth about the gang from the very beginning.}
{468}{}{Those people would be terrible for the guild's reputation. We can't allow that to happen.}
{469}{}{Actually, I don't care.}
{470}{}{A prudent decision.}
{471}{}{Kill Gil McCord and bring back his head.}
{472}{}{I'll do it. You can count on me.}
{473}{}{I doubt that I would want to work for you after what I've heard. Farewell, Bruce.}

{474}{}{I did your dirty work. Here is his head.}
{1474}{}{I did your dirty work. Here is his head.}
{475}{}{(nods sadly) Gil McCord. You were one of us. And look where greed has brought you. Your story will serve as a warning to the rest. You will get 750 caps, as we agreed upon. I very much hope this kind of money won't drive you mad like it did with Gil. And, in the future, try not to spread our little secret.}
{476}{}{No problem, boss. Farewell.}
{477}{}{After what I've seen? I won't make a step in this building in the future.}

{480}{}{Regarding Gil McCord.}
{481}{}{Any news?}
{482}{}{None so far.}
{483}{}{How do I find him?}
{484}{}{I doubt he's in the city. And our agents are reporting that they've seen a man similar to the description going to the south with a caravan. There aren't a lot of settlements there, you can check them all.}
{485}{}{So he can be anywhere. No need to waste time.}
{486}{}{Will I be given something for the trip?}
{487}{}{I'm already paying a lot for this.}
{488}{}{Of course.}
{489}{}{I'll need to spend some money during the trip. And I could use some ammo.}
{490}{}{But how will I find this marksman?}
{491}{}{Sounds good. Here are 100 caps. Now, about bullets, for what kind of weapon do you need them?}
{492}{}{A pistol.}
{493}{}{A revolver.}
{494}{}{A rifle.}
{495}{}{A machine gun.}
{496}{}{Could I get some ammo for a grenade launcher?}
{497}{}{I exclusively use energy weapons.}
{498}{}{Now go and find the son of a bitch. And until you get his head, don't even think of coming back.}
{499}{}{Got it, boss.}
{1499}{}{Got it, boss.}

{500}{}{How much can I trust your people? What are their skills?}
{501}{}{My people practice regularly. They know their price. And I know which one of them's the right one for any given job. Don't worry, they're highly trained professionals in their field.}
{502}{}{The field being the art of killing people?}
{503}{}{That's right. They're real killers. Cold-blooded and precise.}
{504}{}{Sounds great. How do I become like them? Are there courses I could go through to learn how they do it?}
{505}{}{Oh, it's probably better not to know. Let's change the subject, okay?}
{506}{}{There are. However, they are very expensive. And you are not yet in our guild. Considering all the costs involved, this will cost you 50 thousand caps. However, after you finish the courses, you should be able to earn quite a lot of profit.}
{507}{}{I've never had that much money, ever, in my life. And I doubt I will. Farewell.}
{508}{}{Your terms are satisfactory.}
{509}{}{Caps on the table, and we can begin.}
{510}{}{Not now. I need to prepare.}
{511}{}{[Silently give caps]}
{512}{}{Your will is strong, you son of a bitch. You'll make an excellent bounty hunter.}
{1512}{}{Your will is strong, you bitch. You'll make an excellent bounty hunter.}
{513}{}{You have gained the perk "Fatal Blow".}
{514}{}{Though you're already in our guild, you will still have to cover the costs. It is not cheap. 35 thousand caps.}
{515}{}{After your last contract, it's probably your own turn to teach the rookies. Welp. Just for you, I'm making an exception. All expenses are covered. You won't have to pay anything.}
{516}{}{[Silently follow Bruce's commands]}
{517}{}{It's too early for you to be thinking of this stuff. Grow up a little.}
{518}{}{Okay.}