{100}{}{There is a guard in front of you.}
{101}{}{This is one of the guild's mercenaries. He's watching you closely.}

{110}{}{Bruce has a difficult character.}
{111}{}{Bruce, straighten everyone's brains.}
{112}{}{No matter how much I tried, Bruce never smiled.}
{113}{}{Bruce gets nervous when customers walk around with guns.}
{114}{}{I'm watching you.}
{115}{}{You. Stand against the wall and take off your pants... I'm kidding.}
{116}{}{Hands behind your head. Muzzle to the floor... Joke, don't worry.}
{117}{}{Smile, you're in the funniest place in Phoenix.}
{118}{}{Straight out of the wasteland, eh? You're still an innocent kid for a big city.}
{119}{}{Oh, my God, and how did you come to us?}
{120}{}{Say it loud, why are you whispering?}
{121}{}{Got a smoke?}
{122}{}{Is this the first time you've seen such armor? You can touch it.}
{123}{}{Open the bag and take out all the valuables. A joke...}