{100}{}{You see a mercenary.}
{101}{}{You see a tough man clad in heavy armor.}
{102}{}{You have lost your own personal bodyguard.}
{103}{}{The time is up, your bodyguard has returned to the caravan parking ara.}

{110}{}{The caravan parking area is perhaps the only safe place in the city.}
{111}{}{This is the trading center of the city. You won't get killed there, but your pockets will be cleaned up before you can even whistle.}
{112}{}{Be careful. The Cardinals rule these slums. If you get into trouble with them, I won't be able to help you.}
{113}{}{The ancient power plant is up ahead. It still makes electricity thanks to the local ghouls.}
{114}{}{The Cathedral of the Holy Fire is in front of you. Sorry, but I won't go inside with you.}

#Dialogue while not following you
{200}{}{Hey, you're new in the city, right?}
{201}{}{Exactly. I'm interested in what the city can offer to someone like me.}
{202}{}{Of course, Phoenix is gigantic! The biggest city in our time.}
{203}{}{It's almost like you want to add "but".}
{204}{}{Excellent, my fingers are itching to look at everything here.}
{205}{}{But let me tell you - be careful, now is not the best time for sightseeing.}
{206}{}{Why not?}
{207}{}{Oh really? Aren't you trying to fool me?}
{208}{}{Why do you care?}
{209}{}{Whoa, no need to get all worked up. I'm the one that takes all the pressure. You probably do want to look at all the sights the great city of Phoenix has?}
{210}{}{Let's assume yes.}
{211}{}{Of course!}
{212}{}{Then let me tell you this - be careful, now is not the best time for this kind of thing.}
{213}{}{The situation in the city has been unstable for a few years now. There are entire regions ruled over by cutthroats, and theft happens on the marketplace relatively commonly. It's best not to show up alone on the streets either.}
{214}{}{What is it you're proposing?}
{215}{}{And you, of course, know just the way to ensure one's safety?}
{216}{}{I escort important persons within the limits of the city. Usually, the mere sight of an equipped guard is enough to ward off any scum. But you already have security, as I can see. If you happen to find yourself without it, head to me. I'm a professional in this field.}
{217}{}{I'll keep that in mind. Bye.}
{218}{}{I escort important persons within the limits of the city. Usually, the mere sight of an equipped guard is enough to ward off any scum. If you happen to think about acquiring security - head to me. I'm a professional in this field.}
{219}{}{I'll think about it. And for now, I've got urgent stuff to do. Bye.}
{220}{}{I can stand up for myself.}
{221}{}{No doubt! Hit me if you question that even a little. But if you change your mind - you know where to find me.}
{1221}{}{Oh, I very much believe you, lady! But if you change your mind - you know where to find me.}
{222}{}{I'll think about it. Bye.}
{223}{}{Looks like any big city begins with deceit. I'm out of here.}
{224}{}{Listen, I'm interested in your services. How much do they cost?}
{225}{}{For you - }
{226}{}{ caps an hour. But no bartering.}
{227}{}{I can't afford this. Bye.}
{228}{}{You've convinced me. Here are the caps.}

{230}{}{Phoenix is at your fingertips while I'm covering your back, baby.}
{231}{}{I'm at your disposal.}
{232}{}{You won't need a priest or a doctor while I'm near you.}
{233}{}{I'll be damned if something happens to you.}
{234}{}{Don't worry, every dog here knows me.}
{235}{}{Don't worry, I know every corner of this megapolis..}
{236}{}{Now you can relax and have fun without worrying.}

{239}{}{Cool. Now I have my own personal bodyguard.}

{240}{}{You need a bodyguard? I suggest getting one or a giant grenade launcher like this one.}
{241}{}{Uh-uh. Bye.}
{242}{}{Are you still in the security business?}

#Dialogue while following you
{250}{}{Oh please.}
{251}{}{All clear up ahead.}
{252}{}{The path is clear.}
{253}{}{Don't shit your pants. There's nothing to fear here.}
{254}{}{Relax, I'll bring you out of any bad situation.}
{255}{}{What?}
{256}{}{Are there any problems?}
{257}{}{Ys?}
{258}{}{This region is controlled by the cardinal gang. If you value your life, it'd be best to get out of here immediately.}
{259}{}{Okay, let's go.}

{260}{}{Wait for me here until I come back.}
{261}{}{Alright. But if the time runs out, I'll head back to the caravan parking area.}
{262}{}{Don't go anywhere.}
{263}{}{Follow me.}
{264}{}{Whatever you say, boss.}
{265}{}{Forward.}
{266}{}{I no longer require your services.}
{267}{}{You sure? I won't return you the caps for the time you have left.}
{1267}{}{You sure? I won't return you the caps for the time you have left.}
{268}{}{Yes, you're free to go. If I need you, I know where to find you.}
{269}{}{Alright, I'll tolerate your presense a little while longer.}