{100}{}{You see one of the guards.}
{101}{}{This is one of the guild's mercenaries. They're watching you very closely.}

{110}{}{Bruce has a tough temper.}
{111}{}{Bruce will fix everyone's brains up.}
{112}{}{However many times I've tried, Bruce didn't smile. Not even once.}
{113}{}{Bruce is nervous when clients walk around with weapons.}
{114}{}{I'm watching you.}
{115}{}{You. Face the wall and take off your pants... just kidding.}
{116}{}{Put your hands behind your head. Face the floor... Relax, it's just a joke.}
{117}{}{Smile, you're in the most joyous place in Phoenix.}
{118}{}{Right from the wasteland, huh? You're an innocent child in a big city.}
{119}{}{Oh my god, how did you end up here?}
{120}{}{Talk louder, what is it you're whispering?}
{121}{}{You got a smoke?}
{122}{}{First time seeing an armor like that? You can touch it.}
{123}{}{Open your purse and take out all belongings... Relax. Just a joke...}