{100}{}{This is Bruce.}
{101}{}{You see a man in a business suit. His calm gaze expresses indifference to human life.}
{102}{}{It's power armor, right? Impressive. But the dialogue will not work through it.}
{103}{}{Well, well, another junkie from the street. Come back when you've cleaned yourself up.}

#Introductory branches
{200}{}{Welcome. I'm Bruce Turner, and this is an employment agency. Do you need strong guys for security or are you looking for someone among the fugitive criminals?}
{201}{}{Perhaps.}
{202}{}{...}

{210}{}{I'll be damned, what's wrong with your skin?}
{211}{}{A little virus and radiation. It's okay.}
{212}{}{Hmm. In your situation, I wouldn't be joking.}
{213}{}{In my situation, you would already be dead.}
{214}{}{It's a matter of habit, mister.}
{215}{}{Are you laughing at me, smooth-skinned?}
{216}{}{ (raises one eyebrow) No. No problem, green.}
{217}{}{That's good.}
{218}{}{Next time I may be seriously offended.}

{220}{}{Good afternoon, sir. I am glad to meet you. Is someone bothering you?}
{1220}{}{Good afternoon, ma'am. I am glad to meet you. Is someone bothering you?}
{221}{}{Why are you suddenly so nice?}
{222}{}{Obviously, you deserve good treatment... sir.}
{1222}{}{Obviously, you deserve good treatment... ma'am.}
{223}{}{Well, well, here's our new star. You allow yourself too much in this city. Do you think you can get away with it?}
{224}{}{The townspeople are so mean and mean. We peasants are much better.}
{225}{}{You shouldn't have crawled out of your desert. I will return your body to the sands... a dead body.}
{226}{}{What are you...}
{227}{}{I will defend myself.}
{228}{}{I survive as best I can. It's not for you to judge me.}
{229}{}{Oh no. The city pays me to catch criminals. And you're one of them. Guys... (gives a sign)}
{230}{}{Don't do this, Bruce...}
{231}{}{I will defend myself.}
{232}{}{I don't want a fight. Let's make a deal?}
{233}{}{Everyone survives by available means. You're not exactly doing honest work here either. Isn't that right?}
{234}{}{Hmm. Curious. I do not know who to trust. But what I know for sure is that if you don't leave the city, you'll be strung up on a lamppost. Is that clear?}
{235}{}{I see.}
{236}{}{Go to hell, Bruce. You and your whole sales agency.}
{237}{}{That's nice to hear.}
{238}{}{Flattery doesn't suit a mercenary boss. But I appreciate it.}

{240}{}{Don't move. First I want to know what happened between you and the followers of Fire.}
{241}{}{This is our personal business. It doesn't concern you.}
{242}{}{Oh no. This is a mercenary guild, not a brothel. I've been working with the fire worshippers for years, ferrying slaves and convicts across the desert. And all of a sudden you come and block me a damn bunch of contracts. What the hell?}
{243}{}{I'm telling you, it's personal.}
{244}{}{Ah, is this about revenge? I understand. It's lucky for you that your followers can't pay for your head yet. But if that happens, I promise - your head will be on my desk.}
{245}{}{You're scaring me. It would be better if I left here.}
{246}{}{I doubt it'll come to that, Bruce. I'll see you again.}

{247}{}{Adios, bandidos.}
{248}{}{[Show middle finger]}
{249}{}{Whatever you say, you're the boss here.}
{250}{}{What a surprise. We usually chase criminals, not the other way around.}
{251}{}{Who is the criminal here?}
{252}{}{But I'm not a criminal.}
{253}{}{Did you know that Flagstaff declared you the number one criminal? It's lucky for you that the city can't pay the reward for you. However, now I know who you are and where to look for you. Keep that in mind and be quiet.}
{254}{}{No problem, Sheriff.}
{255}{}{I'm not the sheriff, you idiot. But if necessary, I'll be worse than any sheriff.}
{1255}{}{I'm not the sheriff, you idiot. But if necessary, I'll be worse than any sheriff.}
{256}{}{I believe it willingly.}
{257}{}{I don't like that tone. I'll be back when you cool off.}
{258}{}{Then stock up on ammo. Because you won't take me so easily.}
{259}{}{(slowly puts his hand on his machine gun, peering into your eyes) Get out of my office.}

{260}{}{Welcome back... Stop. Show me your neck. These are the marks from the collar. It's strange for a runaway slave to come here. What do you want, slave?}
{261}{}{Don't call me that. Or you'll regret it.}
{262}{}{You don't seem to understand your precarious position. Guys... (gives a sign)}
{263}{}{Not in the face...}
{264}{}{I will kill all the slavers in Arizona.}
{265}{}{I want my freedom back. The tinkerers treated me badly.}
{266}{}{Hmm. Tinkerers will not want to buy a runaway slave again at the same price. You're putting me in an awkward position. Well, I'm ready to buy your rights and sign a free one. But it will cost 1000 caps. I doubt you have that amount.}
{267}{}{I'll find it.}
{268}{}{Then there's nothing left for me... I'll kill you.}
{269}{}{Hmm. Okay, that's settled. I'm waiting for 1000 caps.}

{270}{}{(squints, peering into your face) Hmm. Recently I received information about one of the main bandits. And you look suspiciously like his description.}
{271}{}{It's a coincidence. Do you have any evidence?}
{272}{}{No. But I'll keep an eye on you.}
{273}{}{Of course.}
{274}{}{Don't even think about it.}
{275}{}{The mainline workers made me a mediator in the negotiations.}
{276}{}{This is a surprise. And if that's true, you might be good. Well, while you're in this city, take care of yourself. After all, the locals are not in the spirit of the mainline workers.}
{277}{}{They have a lot of enemies, that's right.}
{278}{}{You know too much, Bruce. I'm sorry, but I'm going to have to keep you quiet...}

{280}{}{This is the armor of the mainline workers. Where did you get it from?}
{281}{}{A battle trophy.}
{282}{}{Hmm. Okay, I can believe it. But it's better not to shine in it in this city. Many people here have heard about highway bandits and may take you for one of them.}
{283}{}{Thanks for the warning.}
{284}{}{I don't care about the locals.}
{285}{}{A gift from a good man.}
{286}{}{You have dangerous friends. I advise you to hide it away while you're in town. The locals have heard about highway bandits. You can accidentally grab a bullet in the forehead.}

{290}{}{Well, well, and here's another victim of the desert. They say you made a lot of noise in Casa Grande. Is it true?}
{1290}{}{Well, well, and here's another victim of the desert. They say you made a lot of noise in Casa Grande. Is it true?}
{291}{}{What are you talking about? I have a great relationship with the locals.}
{292}{}{Don't lie to me, buddy. My sources can't be so wrong.}
{1292}{}{Don't lie to me, darling. My sources can't be so wrong.}
{293}{}{What's it to you?}
{294}{}{Yes, I had to shut someone's mouth. The locals are too suspicious.}
{295}{}{ (raises one eyebrow) Honest confession? This simplifies things.}
{296}{}{What's the deal?}
{297}{}{You're lucky the locals can't pay for your head. But keep in mind, this can change at any time.}
{298}{}{Sure. I'll be quiet.}
{299}{}{I doubt it very much.}

#Main dialog
{300}{}{Welcome. How can I help?}
{301}{}{I do not advise making sudden movements. What do you need?}
{302}{}{I represent Chuck from the Blue Shield Gang.}
{303}{}{Just a minute... Yes, this is some petty thief, for whom a reward has been appointed by the mayor of Casa Grande. Do you want to exonerate him or pay for his head? The reward is 250 caps.}
{304}{}{Pay. Here are the bottlecaps.}
{305}{}{Now this criminal is officially free. I will also transmit this alert to Casa Grande.}
{306}{}{Thank you.}
{307}{}{I can't afford it. Goodbye.}
{308}{}{}
{309}{}{See you later.}

#Slave title
{310}{}{I want to redeem my slavery.}
{311}{}{We've already discussed this. Do you have 1000 caps?}
{312}{}{No.}
{313}{}{Then the question is closed.}
{314}{}{Damn...}
{315}{}{Here are the bottlecaps.}
{316}{}{To be honest, I'm surprised. I doubt that these caps were obtained honestly, but I don't want to know for sure.}
{317}{}{And the free one?}
{318}{}{It will take some time...}
{319}{}{I'll wait...}
{320}{}{Done. You're officially free now. Congratulations. Appreciate your second chance.}
{1320}{}{Done. You're officially free now. Congratulations. Appreciate your second chance.}
{321}{}{Necessarily. Goodbye.}
{322}{}{Hey, don't act like you freed an ex-con. It's quite the opposite.}

#The Cardinals' Quest
{323}{}{You'll regret it.}
{324}{}{Bruce, let the guy go. He's an old friend of mine. You won't refuse my request, will you?}
{325}{}{You are a respected person. Of course I trust you. But don't get into trouble with these cardinals. It's easy to get your reputation dirty about them.}
{326}{}{I'll figure it out. Thanks for understanding, Bruce.}
{327}{}{He's an old friend of mine. And it's not his fault. Let him go.}
{328}{}{I don't know you, and your word means nothing in this city. And if you interfere with my work, you will end up in the same cage for complicity.}
{329}{}{OK.}
{330}{}{I know that you have detained the red Cardinal.}
{331}{}{Yes, let him sit in prison and think about his future. But how do YOU know that? No one except the capture group was aware.}
{332}{}{I have operational sources. What is he accused of?}
{333}{}{This case is not worth the publicity. The client demanded to stop the transaction, and I don't know more myself.}
{334}{}{Clearly. Have a good service.}
{335}{}{I need to see him. I'll pay 10 caps for the meeting.}
{336}{}{OK. You have ten minutes.}
{337}{}{Here are the bottlecaps.}
{338}{}{Not now.}
{339}{}{How much were you paid to catch him? I'll pay more for the release.}
{340}{}{Hmm. If you think about it, it's a pathetic little thing. I'll release him on 100 caps bail.}
{341}{}{OK. Here are 100 caps.}
{342}{}{It's too much. He's not worth it.}
{343}{}{Can I just talk to him? I'll pay 10 caps for it.}
{344}{}{However, this does not guarantee that he will not get caught again. You know these cardinals, don't you? They are all hooligans and rebels. They are a threat to society.}
{345}{}{I won't argue with that.}
{346}{}{The Cathedral of Fire is concerned about what happened. This guy was part of our intelligence. Let him go. Immediately.}
{347}{}{That's it. I guessed that this case smacks of espionage. Okay, I don't want any problems with your church. Let him go. But if something is wrong, you will be responsible.}
{348}{}{Thanks for understanding, Bruce.}
{349}{}{OK.}

#Questions about slaves
{350}{}{Tell me what you're doing here.}
{351}{}{This is a recruitment agency. We are looking for strong guys to perform dangerous tasks. Usually it's security or the search for criminals. Do you need any of this?}
{352}{}{No, nothing like that.}
{353}{}{Well, if necessary, I will be happy to help. For a fee, of course.}
{354}{}{Of course.}

{360}{}{Do you also sell slaves?}
{361}{}{Slave contracts? Few can afford such a luxury.}
{362}{}{Who, for example?}
{363}{}{The main clients are the Flagstaff Colony and the tinsmiths. But I wouldn't call such a commodity slaves. Usually these are criminals serving their sentences. And what is your interest?}
{364}{}{Just curious.}
{365}{}{Mere curiosity arouses suspicion. I hope you understand what that means.}
{366}{}{Uh, I think so.}
{367}{}{I'm thinking of buying a couple of slaves.}
{368}{}{It's stupid. We won't give you a single prisoner.}
{369}{}{Then forget it.}
{370}{}{I'm looking for slaves originally from Villa.}
{371}{}{Villa... It doesn't mean anything to me.}
{372}{}{I'm looking for slaves originally from the Villa. They were brought here from Flagstaff.}
{373}{}{Villa... It doesn't mean anything to me. If these slaves have been to Flagstaff, it won't be easy to find them.}
{374}{}{I see. Sorry to bother you.}
{375}{}{Eh, we'll have to figure everything out on our own again. Goodbye.}
{376}{}{I'll pay 100 caps for the information.}
{377}{}{Sounds acceptable. I can study the invoices for the latest shipments and contact our agents. Payment in advance.}
{378}{}{Here are the bottlecaps. I'll wait.}
{379}{}{It's not worth it, I'll try to figure it out on my own.}
{380}{}{Something has become clear. Several slaves originally from the Villa actually ended up in the Flagstaff colony. They were bought by fire worshippers and transported to their Cathedral. They must have been damn good slaves if they had to be driven over such distances. What became of them is known only to the monks. }
{381}{}{Thank you, Bruce. It's time for me to visit this very Cathedral of Fire. Or whatever his name is.}
{382}{}{Ugh. I would have found out without you.}
{1382}{}{Ugh. I would have found out without you.}
{383}{}{Something has become clear. Several slaves originally from the Villa ended up in the Flagstaff colony. They were bought by fire worshippers and transported to penal servitude in Two-Sun. Apparently, they were damn good slaves if they had to be driven over such distances.}
{384}{}{Thank you, Bruce. It's time for me to visit this dubious town. I hope caravans go there.}
{385}{}{You know, Bruce, your help wasn't very helpful. Goodbye.}
{386}{}{I'll come back later. Now I don't have so many caps with me.}

{390}{}{We need to eliminate one rowdy. His name is George Crook.}
{391}{}{The same Commander Crook who subdued the Western tribe? Why do you want to remove it?}
{392}{}{I'm just representing the customer.}
{393}{}{Clearly. This old soldier has already managed to annoy many people in the city. Moreover, my best guys defected to his squad at one time. And now Crook just throws the bottlecaps to the wind, not knowing what to do with himself. I don't understand how the casino tolerates his drunken antics.}
{394}{}{So will you take on this task?}
{395}{}{Well, I didn't say that, but for 500 caps the world will forget about his existence.}
{396}{}{I need to think about it. It's a responsible business, you see.}
{397}{}{Agreed. Here are the bottlecaps. And yes, there was no such conversation.}
{398}{}{Don't worry, we'll take care of everything.}
{399}{}{I'm counting on you guys.}

#Bounty hunting
{400}{}{I'm interested in finding criminals. For whom and how much do they pay?}
{401}{}{(sigh) Another bounty hunter...}
{1401}{}{A bounty hunter in a lace apron? Where are we going...}
{402}{}{Is something wrong?}
{1402}{}{Ahem. Should I remind you that your security guard is a woman?}
{403}{}{Ah, isn't it you that the whole city is praising for the last matches in the arena? This changes the case.}
{404}{}{I can take care of myself. That's for sure.}
{405}{}{}
{406}{}{}
{407}{}{Do you even have a rifle? This is a dangerous business, there is no place for beginners here. But if you want to risk your neck, it's up to you.}
{408}{}{I can handle it.}
{409}{}{There is a bulletin board on the street. It has the latest information. The system is simple. You find the criminal according to the description, bring his head to me and get a reward for it. Any questions? Then go ahead. Good luck.}
{410}{}{See you later, Bruce Turner.}
{411}{}{I want to talk about bounty hunting.}
{412}{}{Did you manage to catch anyone?}
{413}{}{No. Not yet.}
{414}{}{I thought so. Come back when you catch at least one.}
{415}{}{Okay.}
{416}{}{I'm a ranger. I am interested in work.}
{417}{}{Usually the Rangers don't like our agency. It's strange that you're attracted to this prospect.}
{418}{}{I'm a lone ranger.}
{419}{}{Okay...}

{420}{}{Here is the head of Hernando Aviles.}
{421}{}{Ah, this is our old acquaintance, Hernando. Well, will there be no more jokes in my address, you fucking bastard?}
{422}{}{Here is the head of Chucho Navarro.}
{423}{}{Son of a bitch, there was a lot of noise from him. I am glad that his loud mouth will never make a single sound again.}
{424}{}{Here's Aidy Gorme's head.}
{425}{}{Eh, but once she was a beauty and performed in a casino. A strange fate. I don't understand what blew her head off.}
{426}{}{[Next]}
{427}{}{Hernando Aviles is dead. But I couldn't get his head.}
{428}{}{Chucho Navarro is dead. But I could not bring his head.}
{429}{}{Aidy Gorme is dead. Alas, her head was left lying in the desert.}
{430}{}{No head, no reward. But I am glad to hear such news. Until the refutation arrives, we will assume that you are telling the truth.}
{431}{}{Uh, okay.}
{432}{}{I won't get the caps? This is very bad.}
{433}{}{Great job. Here are your 500 caps. I hope you're not going to give up this activity? We need such people.}
{434}{}{I'll think about it.}
{435}{}{I don't know, this activity is too dangerous.}

{440}{}{Wait. So it was the last ataman of Los Panchos? The damn gang has finally fallen. Imagine how this news will spread all over Phoenix. Oh, it's going to be a real celebration for the townspeople.}
{441}{}{Certainly. But aren't there other atamans?}
{442}{}{These three held the largest and most dangerous clans of Los Panchos. The others didn't pose much of a threat. Now, without their atamans, their entire empire will disintegrate, and ordinary robbers will be greatly weakened. Surely the clans have already declared war on each other, starting the redistribution of influence.}
{443}{}{It's a little weird. But it is even more strange that the chieftains had the same brand as you and your mercenaries.}
{444}{}{Hmm. It had to be revealed sometime... We have embellished their legend a little. In fact, these three worked as mercenaries in our guild. They learned a lot here. But having felt the power and authority over people, they stopped being interested in honest work.}
{445}{}{You should have warned me about this.}
{446}{}{These people are a disgrace to the guild. We cannot allow our reputation to suffer because of them.}
{447}{}{This is reasonable.}
{448}{}{Actually, I don't care.}
{449}{}{You've had enough of completed contracts. For now, rest and have fun. And I'll think about what other job you can leave.}
{450}{}{More work? Great, I'm looking forward to it.}
{451}{}{I doubt that after what I've heard, I'll want to work for you. Goodbye, Bruce.}
{452}{}{Well, that's great news.}
{453}{}{The cap is more important to me. You'll figure out the rest yourself.}
{454}{}{Right. For now, rest and have fun. And I'll think about what other job you can leave.}
{455}{}{More work? Great, I'm looking forward to it.}
{456}{}{I have enough caps to get out of this business. Goodbye, Bruce.}
{457}{}{What about a new job?}

{460}{}{You're just in time. I was about to send for you. There is a new goal. And this time I'm paying a higher price.}
{461}{}{It's not hard to guess that a new goal is worth that much money. What did he do wrong?}
{462}{}{(shows the portrait) This is Gil McCord. He is known as one of the best shooters and trackers. He knows his job well and can get out of any scrape. Therefore, he cannot be left alive.}
{463}{}{Hmm. This is strange. It's like you're not telling me something. Why are mercenaries chasing a mercenary?}
{464}{}{(sigh) You see, I embellished our merits a little. In fact, the atamans of Los Panchos were once also our mercenaries. They learned a lot and that's why they were able to gain a foothold outside the city.}
{465}{}{And Gil McCord?}
{466}{}{He was their go-between and spy. This was revealed after we cleaned up the Los Panchos bases. It seems that Gil was too greedy and distrustful, so he worked on both sides to always have a trump ace up his sleeve.}
{467}{}{You should have told the truth about the gang from the beginning.}
{468}{}{These people are a disgrace to the guild. We cannot allow our reputation to suffer because of them.}
{469}{}{Actually, I don't care.}
{470}{}{This is reasonable.}
{471}{}{Kill Gil McCord and bring his head.}
{472}{}{I'll do it. You can count on me.}
{473}{}{I doubt that after what I've heard, I'll want to work for you. Goodbye, Bruce.}

{474}{}{I've done your dirty work. Here is his head.}
{1474}{}{I've done your dirty work. Here's his head.}
{475}{}{(nods sadly) Gil McCord. You were one of us. And that's what greed has brought you to. His story will serve as an example to others. You're owed 750 caps, as we agreed. I really hope that this amount will not turn your head, as it turned Gila. And from now on, try not to spread about our little secret.}
{476}{}{No problem, boss. Goodbye.}
{477}{}{After everything you've seen? I won't even take a step here.}

{480}{}{About Gil McCord.}
{481}{}{What news?}
{482}{}{None yet.}
{483}{}{How do I find him?}
{484}{}{I doubt he's in town. In addition, our agents report that a man similar in description was seen leaving for the south with a caravan. There aren't many settlements there, you can check them all.}
{485}{}{So he could be anywhere. Don't waste time.}
{486}{}{Will they give me something for the road?}
{487}{}{I'm paying an already high price for this job.}
{488}{}{Of course.}
{489}{}{I'll need extra travel expenses and some ammo.}
{490}{}{But how will I find this shooter?}
{491}{}{That's reasonable. Here are 100 caps for travel expenses. What kind of ammo might you need?}
{492}{}{Pistol.}
{493}{}{Revolver.}
{494}{}{Rifle.}
{495}{}{For the machine.}
{496}{}{Are there any shells for a grenade launcher?}
{497}{}{I only use energy weapons.}
{498}{}{Now go and find that son of a bitch. And until you get his head, you don't have to come back here.}
{499}{}{Roger that, boss.}
{1499}{}{Got it, boss.}

{500}{}{How much can I trust your people? What are their skills?}
{501}{}{My people go through regular training. They know their worth. And I know who is best suited for this or that job. Don't worry, they are professionals in their field.}
{502}{}{In the murder case?}
{503}{}{Exactly. Real killers. Cold-blooded and precise.}
{504}{}{Sounds cool. How do I become a real KILLER? Can I go through your training to learn this ability?}
{505}{}{Oh, I'd rather not know about it. Let's change the subject, okay?}
{506}{}{You know, this is a very expensive thing. And you're not in our guild yet. Considering all the costs, it will cost 50,000 caps. But after the course you will be able to make good money on all sorts of garbage.}
{507}{}{I don't have that kind of money and never have. And I'm unlikely to earn them even with such a powerful skill. Goodbye.}
{508}{}{It suits me.}
{509}{}{caps on the table - and we can start.}
{510}{}{Not now, I need to get ready.}
{511}{}{[Silently give away the bottlecaps]}
{512}{}{You have a strong mind, you son of a bitch. You'll make a great bounty hunter.}
{1512}{}{You have a strong mind, bitch. You'll make a great bounty hunter.}
{513}{}{You have acquired the "Death Strike" ability.}
{514}{}{Although you are already in our guild, you will have to pay the costs. It's not cheap and will cost 35,000 caps.}
{515}{}{After the last contract, it's time for you to teach the recruits yourself. Well, especially for you, I will make an exception and pay all costs in full.}
{516}{}{[Silently follow Bruce's instructions]}
{517}{}{It's too early for you to think about such things. Grow up a little.}
{518}{}{OK.}