{100}{}{You see one of Diego's men.}
{101}{}{You see Miguel.}
{102}{}{You see a charming man with a mustache. He reminds you of someone.}
{103}{}{You see Miguel, your uncle, who once escaped from the Villa.}

{110}{}{Wait a minute, who else are you?}
{111}{}{Who are you?}
{112}{}{Who let you in?}
{113}{}{What are you doing here?}
{114}{}{A little more and I'll call security.}
{115}{}{Don't tell me you're hiding from security.}
{116}{}{Your face is somehow familiar to me.}
{117}{}{Do we know each other?}
{118}{}{Hey, do we know each other?}
{119}{}{}

{120}{}{I'm busy with, uh, important research. Yes, that's right.}
{121}{}{I'm doing science here, baby.}
{122}{}{What do you know about plasma accelerators? I thought so...}
{123}{}{Pour some tequila, do something useful.}
{124}{}{If you bother me, I'll throw it back to the casino.}
{125}{}{I'm doing a lot of research. You don't understand.}
{126}{}{Today I'm going to get drunk to the point of losing my pulse!}
{127}{}{}
{128}{}{}
{129}{}{}

#First meeting
{200}{}{Hey, who let you in? It's closed... }
{201}{}{?! I'll be damned, }
{202}{}{, what the...}
{203}{}{Uncle Miguel, is that you? Long time no see!}
{204}{}{Oh, how you've grown! I didn't recognize you right away. Although the facial features still resemble your padre... But, look, this is so unexpected. What are you doing here?}
{1204}{}{Oh, how you've grown! I didn't recognize you right away. Although the facial features still resemble your padre... But, look, this is so unexpected. What are you doing here?}
{205}{}{I'm looking for my padre. It's a long story. In short, he and the other residents of the Villa were taken away by slavers.}
{206}{}{That's how... I am so sorry. But I don't know anything about it. In any case, it's best if you leave this city as soon as possible.}
{207}{}{Why are you sending me away? Uncle Miguel, I've come so many miles to find you!}
{1207}{}{Why are you sending me away? Uncle Miguel, I've come so many miles to find you!}
{208}{}{Do you even understand what's going on around you? Phoenix is not a Villa for you, there are completely different mores here. I don't want to put you in danger. If the boss finds out, it will be bad for both of us.}
{209}{}{Don't worry about it. Don Diego is no more. He had an "accident".}
{210}{}{Is this your doing? Idiot! Diego was my only means of survival in this city. What am I going to do now?}
{1210}{}{Is this your doing? You fool! Diego was my only means of survival in this city. What am I going to do now?}
{211}{}{It seemed to me that you were almost in his thrall.}
{212}{}{You shouldn't have come here. Everything is too fragile. Diego was a criminal type, it's true. But he was developing the city. And now what? The fire worshippers will surely take control of the casino. Do you know what that means? I can see by my eyes that there isn't.}
{213}{}{So will you help me find the padre?}
{214}{}{Look, I'm well settled in this city and I don't want any problems. Look for help elsewhere. For example... The Followers of Fire. They're the ones who pay mercenaries all over Arizona for their missionary projects.}
{215}{}{Okay. Goodbye, Uncle Miguel.}
{216}{}{Don't worry about it. I'm leaving Phoenix soon, my business is already over.}
{217}{}{Do you think so? I'm afraid things have only just begun at the Villa. This story of enslavement will not pass without a trace. I wonder how you and your padre will cope next.}
{218}{}{We will try. Goodbye, Uncle Miguel.}
{219}{}{Don't worry about it. Don Diego and I have a great relationship.}
{220}{}{I'm surprised. And you are much quicker and smarter than your padre. He didn't want to hear about the new opportunities that the rest of the world could give Villa. And now you're here and already making friends with one of the best people in the city. Well done.}
{221}{}{So will you help me find the padre?}
{222}{}{It's time for me to get back to the Villa. Goodbye, Uncle Miguel.}
{223}{}{Are you enslaved to Don Diego?}
{224}{}{Slavery? No... No, I don't think so. But if he wants to, he will sell anyone into slavery. He's an important person here, runs the entire business center.}
{225}{}{Even more so. Maybe he can help in the search for the padre?}
{226}{}{So you're doing great. And I have to go to the Villa, my business here is already over.}

{230}{}{Hey, who let you in? It's closed... }
{1230}{}{Hey, who let you in? It's closed... }
{231}{}{?! Damn me, it's my favorite nephew! It's good to see you, especially after all these events.}
{1231}{}{?! Damn me, it's my favorite nephew! Glad to see you, especially after all these events.}
{232}{}{It's been a long time, Uncle Miguel.}
{233}{}{And you're growing up. I remember you at table level. A lot has changed since then.}
{234}{}{Oh yes. And I have something to tell you. About the Villa, about the padre, about the robbers...}
{235}{}{Wait, to be honest, I knew about you and your mission. I even wanted to come out of the shadows and help you while you were in Phoenix. But something was missing for me. It seemed to me that the Villa had become the past for me, and now I regret that I was so careless.}
{236}{}{Yes, the Villa is not the same as before.}
{237}{}{I'm glad. And I am amazed at how you managed to save the Villa in such difficult conditions. You know, it seemed to me that these moldy old men would sooner or later lead the Villa to extinction. And they almost succeeded if it wasn't for you. I don't know how much more they will last.}
{238}{}{I'm glad. But it seems that you didn't manage to convince these moldy old people of the need for change, right? Yes, I can see it in your eyes. Villa needs people like you and me.}
{239}{}{Does it feel like you don't believe in the future of the Villa?}
{240}{}{That's why I left my homeland. He became a man without a home and severed all ties with the past. While you're busy with the eternal mouse fuss, you don't think about it. You need to get out of your box and see the world around you to understand this. And you succeeded. You're doing great.}
{241}{}{Thank you, Uncle Miguel.}
{242}{}{No problem. But it's time for you to save the world. I don't want anyone in the casino to find out about our past.}
{243}{}{Goodbye.}
{244}{}{It sounds blasphemous coming from you. After all, you left your family when you could help.}
{245}{}{Your truth. And I won't change your mind. But it seems it's time for you to save the world. I don't want anyone in the casino to find out about our past.}
{246}{}{Goodbye.}

#Repeat dialog
{300}{}{Don't even come near me while we're at the casino.}
{301}{}{Goodbye.}

{310}{}{Do you know what happened at the Villa?}
{311}{}{The news reached me out of the corner of my ear.}
{312}{}{Do you know where our people are being held?}
{313}{}{I don't know for sure. The Followers of the Fire in the Cathedral may have this information.}
{314}{}{And what do the Followers have to do with it?}
{315}{}{Slaves are used by mercenaries, and mercenaries perform the tasks of Followers. They are in some way customers or patrons of the slave trade, although not everyone understands this. A colony in Flagstaff, built with the money of the Cathedral, or tinsmiths who signed many contracts with Followers - slaves are needed everywhere now.}
{316}{}{Your relatives are being forced to work, and you're talking about it so calmly?}
{317}{}{It's my brother's fault. If he had listened to me, this tragedy would not have happened at all.}
{318}{}{Everything is clear with you, Uncle. Let's change the subject.}

{320}{}{Tell me about your escape from the Villa.}
{321}{}{ESCAPE? Is that what my brother calls it? I knew that he was ready for any meanness to be forgotten about me... Know, dear nephew, that I didn't want to leave, I was KICKED out of there. Although I'm even glad of it.}
{1321}{}{ESCAPE? Is that what my brother calls it? I knew that he was ready for any meanness to be forgotten about me... Know, dear niece, that I didn't want to leave, I was KICKED out of there. Although I'm even glad of it.}
{322}{}{Why were you kicked out?}
{323}{}{After the death of our padre, your grandfather, Andres, as an older brother, began to manage the Villa. He followed the traditions, but I tried to come up with new ideas. Even then I understood that the Villa had to change.}
{324}{}{Why?}
{325}{}{Even then, we were faced with scoundrels from the wasteland, rangers, and caravans from the neighboring town. We knew there was life outside the valley, too. But Andres carefully hid it from the rest of the residents. Just like the other elders did before him.}
{326}{}{And you argued about it?}
{327}{}{We did not agree on the fate of the Villa. I offered to establish contacts with neighboring cities and use old equipment for cultivating the land, but he wouldn't let me open my mouth. He said it wasn't the time, that Diablo had possessed me... In the end, I said I would tell people the truth, but he just kicked me out of the settlement.}
{328}{}{What happened then?}
{329}{}{I got to the next town. At that time, there was an active mine there, and I managed to make good money there. And at the same time, I got acquainted with old technologies. Then the mine was crushed, and I went straight to Phoenix.}
{330}{}{Go on.}
{331}{}{Here I saw all the charm of civilization in its full grandeur! But even here, residents do not understand or appreciate old things well. I was lucky that Don Diego hired me. He needed experts in old technology to set up a casino. I've been here ever since.}
{332}{}{So that's what you do here - drink and immerse yourself in women's pleasures?}
{333}{}{Take your time, dear nephew. I've worked hard enough to live beautifully. Besides, my machine is always ready to work.}
{1333}{}{Take your time, dear niece. I've worked hard enough to live beautifully. Besides, my machine is always ready to work.}
{334}{}{What kind of machine?}
{335}{}{Are you talking about the machine in your pants?}
{336}{}{How to say it... I'm doing some technical work for Don Diego.}
{337}{}{For example?}
{338}{}{Sorry, but the boss won't like me talking about it.}
{339}{}{Okay, let's change the subject.}
{340}{}{Will this story ever end?}
{341}{}{"Old technology" is not just slot machines, right?}
{342}{}{Heh-heh, and you're smart, nephew. I'll tell you this - Diego wants to be aware of everything that brings power, strength, and power. I was an extremely important find for him.}
