{100}{}{This is George Crook.}
{101}{}{You see your old acquaintance, Field Commander Kruk, who has returned from San Brahmin. He is cheerful and drunk.}
{102}{}{Hey, buddy, how did they miss you in this thing? Bar-r-duck!}
{103}{}{Your mother...}

{200}{}{Leave me alone - my head hurts.}
{201}{}{Leave me alone with this beautiful bed.}
{202}{}{I need to sleep after so many liters of tequila.}
{203}{}{Ya. Want. Sleep!}
{204}{}{*Ir*}
{205}{}{Bring me some water. Or a revolver.}
{206}{}{I just need to take a little nap.}
{207}{}{Let me rest and then we'll continue.}
{208}{}{}
{209}{}{}

{210}{}{Ah, it's you! Pour yourself a drink.}
{211}{}{Hey, how did we beat these savages!}
{212}{}{Do you remember how we put the leader in his place?}
{213}{}{Now the whole neighborhood is afraid of you and me, amigo.}
{214}{}{Has Aaron already given you an award?}
{215}{}{Hey, let's get drunk and kick this bartender's ass?}
{216}{}{Hey, bring me that girl from the stage.}
{217}{}{Damn, with a whole bottle of tequila, I'm just pissing with boiling water.}
{218}{}{Watch the rear, amigo.}
{219}{}{A fight! Let's have a fight!}