{100}{}{You see George Crook.}
{101}{}{You see your old acquaintance - field commander Crook, who has returned from San Brahmin. He's happily drunk.}
{102}{}{Hey, friend, how'd they even let you here while wearing this thing? What a m-mess!}
{103}{}{You mother...}

{200}{}{Don't bother me - my head hurts.}
{201}{}{Leave me alone with this fine bed.}
{202}{}{I need to sleep after so many litres of tequila.}
{203}{}{I. Want. To. Sleep!}
{204}{}{*Hic*}
{205}{}{Bring me water. Or a revolver.}
{206}{}{I just need to sleep a bit.}
{207}{}{Let me rest and then we'll continue.}
{208}{}{}
{209}{}{}

{210}{}{A-ah, it's you! Have a drink.}
{211}{}{Hey, we dealt with those savages so well, didn't we?}
{212}{}{Remember how we put their chieftain in his place?}
{213}{}{Now you and me are feared by all around us, amigo.}
{214}{}{Aaron already gave you a reward, yeah?}
{215}{}{Hey, let's have a drink and kick that bartender's ass, huh?}
{216}{}{Hey, bring me that girl on the stage.}
{217}{}{Fuck, after a whole bottle of tequila, I just piss boiling water.}
{218}{}{Watch your rear, amigo.}
{219}{}{Fight! Let's have a big, good ol' fight!}