{100}{}{You see a beggar.}
{101}{}{You see a girl with two maracas. She is trying to use them to perform something.}
{102}{}{Thank you, mister.}
{1102}{}{Thank you, miss.}
{103}{}{Don't come close to me!}
{104}{}{*Yawns and silently rubs eyes in response*}

{200}{}{(The girl, upon seeing you, starts shaking the maracas, crooning a barely comprehensible song). "Rad-scorpion, Rad-scorpion. It can't run anymore..."}
{201}{}{[Listen]}
{202}{}{[Walk by]}
{203}{}{"All beca-u-se, all beca-u-se... It lost it's hindlegs in a fight".}
{204}{}{[Listen further]}
{205}{}{"It's hard to live without it's feet. But still, it runs, runs, runs".}
{206}{}{[Listen further]}
{207}{}{"And steadily, not looking back. It wants to live, it wants to live".}
{208}{}{}
{209}{}{(silently extends a begging jar)}
{210}{}{I don't have anything valuable either. Maybe another time.}
{211}{}{Here is 1 cap, don't deny yourself anything.}
{212}{}{Take 2 caps, you've earned them.}
{213}{}{Take 3 caps and spend them on food.}
{214}{}{I'm in a generous mood today. Here are 4 caps.}
{1214}{}{I'm in a generous mood today. Here are 4 caps.}
{215}{}{I can't bear to see you suffering on the street. Here, take these 5 caps.}
{216}{}{What horrifying torture for my ears! Don't make this sound ever again.}
{217}{}{Bravo! You're doing very well, young lady.}
{218}{}{An interesting song. But the execution could definitely be better.}

{220}{}{Thank you, sir...}
{1220}{}{Thank you, ma'am...}
{221}{}{Hm. You could have said that more respectfully. But what can you expect from someone like this...}
{222}{}{You're welcome. I hope this helps you.}

{230}{}{You foolish girl, it's you who's going to give me all your caps!}
{231}{}{(silently shakes head, horrified, making a step back)}
{232}{}{I'm sorry for sounding a bit unhinged. Of course I won't take anything from you.}
{233}{}{Stop, give me all your caps!}
{234}{}{(The girl nibly breaks free from your hands, using your clumsiness.)}
{235}{}{Run away, you little bitch, I'll get you anyways!}
{236}{}{You got lucky this time.}
{237}{}{Let me go! (Holding the girl by the elbow, you find 10 caps and take them for yourself.) Someone! Help!}
{238}{}{Don't even think of bringing anyone after me, got it? Now scram.}
{239}{}{You can go. I was only interested in the caps.}