{100}{}{You see a beggar.}
{101}{}{You see a girl with two maracas. With their help, she is going to do something.}
{102}{}{Thank you, mister.}
{1102}{}{Thank you, miss.}
{103}{}{Don't come near me!}
{104}{}{*Yawns and silently rubs his eyes in response*}

{200}{}{(The girl, seeing you, starts shaking her maracas and humming some barely understandable song). "Glad-cockroach-chick, glad-cockroach-chick. He can't run anymore..."}
{201}{}{[Listen]}
{202}{}{[Pass by]}
{203}{}{"All because of what, all because of what... He is deprived of his hind legs in battle".}
{204}{}{[Listen on]}
{205}{}{"It's difficult without a paw, it's difficult without a paw. But he's running, running, running".}
{206}{}{[Listen on]}
{207}{}{"And steadily, and without looking back. He wants to live, he wants to live".}
{208}{}{}
{209}{}{(silently holds out the begging jar)}
{210}{}{I don't have anything of value either. Maybe another time.}
{211}{}{Here's one cap, don't deny yourself anything.}
{212}{}{Keep two caps, you deserve it.}
{213}{}{Take these three caps and spend them on food.}
{214}{}{Today I am generous. Here are four bottlecaps.}
{1214}{}{I'm generous today. Here are four bottlecaps.}
{215}{}{I can't bear to see you suffer on the street. Take these five caps.}
{216}{}{What a terrible ordeal for my ears! Don't make that noise anymore.}
{217}{}{Bravo! You're doing great, young lady.}
{218}{}{A curious song. But it's worth working on the execution.}

{220}{}{Thank you, sir...}
{1220}{}{Thank you, ma'am...}
{221}{}{Hmm. You could have said it more respectfully. But what can you expect from such a mongrel...}
{222}{}{You are welcome. I hope this helps you.}

{230}{}{You're a fool, you're going to give all your caps now!}
{231}{}{(silently and with horror shakes his head, taking a step back)}
{232}{}{I'm sorry I'm snapping. Of course, I won't take anything from you.}
{233}{}{Stop, give me all the bottlecaps!}
{234}{}{(The girl quickly breaks out of your hands, taking advantage of your clumsiness.)}
{235}{}{Run, little bitch, I'll get you anyway!}
{236}{}{You're lucky this time.}
{237}{}{Let go! (Holding the girl by the elbow, you find ten caps in her things and take them for yourself.) Somebody! Help!}
{238}{}{Don't bring anyone after me, okay? Now get lost.}
{239}{}{You can go now. I was only interested in the caps.}