{100}{}{You see the administrator.}
{101}{}{You see a middle-aged woman. Based on her clothes, you can see that she has quite a high level of income.}
{102}{}{*Looks at your armor at first with a frenzy, then fear*}
{103}{}{We're closed. Please return during our working hours.}

#Dialogue
{200}{}{Yes?}
{201}{}{Goodbye.}
{202}{}{I need to send a package to Flagstaff.}
{203}{}{I need to send a package to Two Sun.}
{204}{}{Maybe we could just chat?}
{205}{}{I don't have time for idle chatting. So, are you going to send something?}
{206}{}{Maybe.}

#Sending something
{210}{}{The cost is }
{211}{}{ caps. You can use that box by the wall. After payment, we'll send your things to the destination point.}
{212}{}{Here is the payment, you can send the package.}
{213}{}{Not now.}

{214}{}{I already named the price. Do you want me to call security?}
{215}{}{}
{216}{}{This is just a misunderstanding. I'll be back.}

{217}{}{Wait while I fill the journal. There. You can receive your package in an identical "Sonora Express" office.}
{218}{}{Good.}

{220}{}{Can I, as a Follower of the Fire, expect special prices?}
{1220}{}{Can I, as a Follower of the Fire, expect special prices?}
{221}{}{Yes, of course. We have special agreements with the temple.}
{222}{}{Very good.}
{223}{}{It's good that you came here. But don't expect a discount. I was given orders from the top, so don't even think of complaining.}
{224}{}{I understand. No problem.}
{225}{}{What the hell do you think you're doing, you bitch?!}
{226}{}{No. I'm planning on going out of this building and never returning. Ever.}

{230}{}{Welcome. How can I help you?}
{231}{}{I'm sorry, what is this place?}
{232}{}{This is a courier delivery service. Does the sign outside not mean anything to you?}
{233}{}{Such a service is somewhat... strange, considering scorched desert around. What do you deliver?}
{234}{}{We're ready to deliver anything, even a dead fly, if we're paid a sufficient price for it. Are you simply curious, or are you ready to make an order?}
{235}{}{Perhaps. I would like to know more.}
{236}{}{No, not at all. The sign simply made me interested. Goodbye.}
{237}{}{I think you're making fun me. With such service, I won't make another step in this building.}

{280}{}{I need to know if a person called "Tin Tan" has traveled with one of your caravans lately.}
{281}{}{We keep a journal containing records about every person who travels with the caravan. But I'm not looking in there unless I'm getting something out of it.}
{282}{}{Fine. 10 caps. How does that sound?}
{283}{}{Forget it, then. Goodbye.}
{284}{}{Satisfactory. Who are you looking for, exactly?}
{285}{}{Germán Genaro Cipriano Gomez Valdes y Castillo. He was heading to a settlement called the Platform through Casa Nueva.}
{286}{}{The journal says that a man with this name traveled with one of our stagecoaches. But it also says that the stagecoach did not reach its destination. It was robbed by the highwaymen. No survivors.}
{287}{}{I see. Thank you.}

#Lost package on world map
{290}{}{I stumbled upon this while traveling.}
{291}{}{What is it?}
{292}{}{I think these are letters from the eastern colonies. The courier must have ended up in a bandit ambush and couldn't bring them here.}
{293}{}{Oh, I understand now. Many are awaiting news from the new colonies. But due to the bandits, we're losing one caravan after the other. Well, I'll have to buy those letters from you for half of the courier's reward.}
{294}{}{Better than nothing.}
{295}{}{Here. Thank you for the delivery.}
{296}{}{Goodbye.}
{297}{}{Keep the caps. Knowing that simple people are waiting for those letters is enough for me.}
{298}{}{This is the first time I saw someone refuse caps. You truly are a striking person. But thank you for the delivery.}
{299}{}{Happy to help. Goodbye.}
{1299}{}{Happy to help. Goodbye.}

#Quest
{300}{}{I need legal income. Do you have any free vacancies?}
{301}{}{We have enough staff.}
{302}{}{Alright.}
{303}{}{Though... there is one... delicate situation that nobody wants to deal with.}
{304}{}{I'm listening.}
{305}{}{Our courier was attacked in the eastern slums and the robbers took all his things, including new letters. You must find and return them. Are you ready to do this? Risky, but the company will pay 50 caps for the returned letters.}
{306}{}{Looks like one of the local gangs. I don't think finding them will prove to be a problem. I'm in.}
{307}{}{Very good. Payment upon delivery of the item. Good luck.}
{308}{}{Yeah, bye.}
{309}{}{Robbers, slums... No, I won't take such a risk for some measly caps.}
{310}{}{Of course, I understand. Goodbye.}
{311}{}{Yeah, bye.}
{312}{}{Remind me, where were the letters stolen?}
{313}{}{The eastern slum area. Where poor people live. That inhumane arena is also located there. They arrange fights to the death there. Barbarism.}
{314}{}{Thank you. Another question, please.}
{315}{}{Alright, goodbye.}
{316}{}{I got some people's letters. Doesn't look like they reached their destinations.}
{317}{}{Let me have a look... Ah, finally! Those letters were considered lost after our courier was robbed in the slums. You have no idea how helpful you've just been.}
{318}{}{You're welcome. Am I going to receive a reward for this?}

{320}{}{Are these the letters you were talking about? A member of the Red Cardinal gang had them.}
{321}{}{Ah, finally! You have no idea how helpful you've just been. Let me have a look... Yes, they are those ones.}
{322}{}{And my caps?}
{323}{}{Of course, here are 50 caps. You know what, I'll pay you some additional 25 caps for their delivery. Or, to be more precise, the delivery of one of those letters. It's adressed to a certain Steve who lives in those dangerous slums. Looks like you can walk there without worry, and this time we need a *guaranteed* delivery.}
{324}{}{Of course. I could always use more caps.}
{325}{}{Just as always. You help someone one time - and they all go to you. Fine, give it to me.}
{326}{}{Let's sign a short contract. There... wonderful. Now head to the slums and deliver the letter. Good luck.}
{327}{}{[Leave the office]}

{330}{}{The letter is delivered. Here is the recepient's signature.}
{331}{}{Wonderful. Here are your honestly earned 25 caps. I hope I don't need to clarify that we will not tolerate deception.}
{332}{}{Of course.}
{333}{}{Thank you for your assistance, it was very nice to work with you. I'm afraid, however, that there will be no new deliveries for the foreseeable future.}
{334}{}{Goodbye.}
{335}{}{Speaking of that letter. Nobody can receive it anymore. The recepient is dead.}
{336}{}{How terrible. Well, it happens. There was a part of the contract made specifically for this possibility. You receive only half of the reward. Here are your 12 caps.}
{337}{}{This is outrageous! I demand the full amount!}
{338}{}{Read the contract. You signed it. No point being all outraged.}
{339}{}{Wh... How... Ur-gh.}
{340}{}{Welp, that's fair. No complaints here.}
{341}{}{[Leave the office with a feeling of pride and accomplishment]}
{342}{}{Remind me, where do I need to deliver the letter to?}
{343}{}{(makes a sad sigh) The letter is adressed to a certain Steve, who lives in the slums near the arena. I repeat: in the slums, near the arena. Did you get it? I suggest you write it down to not forget it.}
{344}{}{I hear you, woman.}
{345}{}{Thanks, I see it now.}