{100}{}{You see the administrator.}
{101}{}{You see a middle-aged woman. Judging by her clothes, she has a good level of prosperity.}
{102}{}{*Looks at your armor with a frenzy that is replaced by fear*}
{103}{}{We're closed. Come during business hours.}

#Dialog
{200}{}{Yes?}
{201}{}{Goodbye.}
{202}{}{I need to send a package to Flagstaff.}
{203}{}{I need to send a package to Two-Sun.}
{204}{}{Can we just have a chat?}
{205}{}{I don't have time for idle chatter. So are you going to send a package?}
{206}{}{Perhaps.}

#Sending a parcel
{210}{}{Shipping cost }
{211}{}{ bottlecaps. You can use this box against the wall. After payment, we will take your things to your destination.}
{212}{}{Here is the fee, the parcel can be sent.}
{213}{}{Not now.}

{214}{}{I've already named the price. Do you want me to call security?}
{215}{}{}
{216}{}{Just a misunderstanding. I'll be back.}

{217}{}{Wait while I fill out the log. So. You can pick up the parcel at the same Sonora Express office.}
{218}{}{Good.}

{220}{}{Can I, as a follower of Fire, count on special prices?}
{1220}{}{Can I, as a follower of Fire, count on special prices?}
{222}{}{That's good.}Y
{221}{}{Yes, of course. We have special agreements with the temple.}
{223}{}{It's good that you stopped by. But don't count on a discount. I was given instructions from above, so don't even think about making claims against me.}
{224}{}{I understand. No problem.}
{225}{}{What the hell are you doing, bitch!}
{226}{}{No. I'm going to get out of here. Absolutely.}

{230}{}{Welcome. How can I help?}
{231}{}{Excuse me, what is this place?}
{232}{}{This is a courier delivery service. Does the sign outside mean anything to you?}
{233}{}{Such a service is not much... unusual, considering the scorched desert around. What are you transporting?}
{234}{}{We are ready to transfer anything, even a dead flea if the right price is right. Are you just curious or are you ready to place an order?}
{235}{}{Perhaps. I want to know more.}
{236}{}{No, no, I was just attracted by the sign. Goodbye.}
{237}{}{I think you're being rude to me. With such a service, I will not take another step here.}

{280}{}{I need to know, did your caravans accompany Tin-Tan?}
{281}{}{We keep a journal. But I'm not just going in there.}
{282}{}{Good. I will pay 10 caps.}
{283}{}{Then don't. Goodbye.}
{284}{}{Okay. Who are you looking for?}
{285}{}{Herman Genaro Cipriano Gomez Valdez y Castillo. He was heading to the Platform settlement via Casa Nueva.}
{286}{}{The magazine says that this man went with the stagecoach. But there is also a record that the stagecoach did not reach its destination. He was robbed by highway robbers.}
{287}{}{Clearly. Thank you.}

#Lost parcel from the world map
{290}{}{While traveling, I came across this package.}
{291}{}{What is it?}
{292}{}{Apparently, letters from the eastern colonies. The courier was ambushed by bandits and could not bring them here.}
{293}{}{Oh, I understand now. Many people are waiting for news from the new colonies. But because of the bandits, we lose one caravan after another. Well, I'll have to buy these letters from you for half the courier fee.}
{294}{}{Better than nothing.}
{295}{}{Ask you. Thanks for the delivery.}
{296}{}{Happily.}
{297}{}{Keep the caps for yourself. It's enough for me that ordinary people are waiting for these letters.}
{298}{}{This is the first time I've seen someone refuse caps. You are an amazing person. But thanks for the delivery.}
{299}{}{Glad to help. Happily.}
{1299}{}{Glad to help. Happily.}

#Quest
{300}{}{I need a legal income. Do you have any vacancies?}
{301}{}{We have enough employees.}
{302}{}{I see.}
{303}{}{However... there is one "delicate" matter that everyone refuses.}
{304}{}{I'm listening.}
{305}{}{In the eastern slums, our courier was attacked by robbers and took all his belongings, including fresh letters. We need to find and return them. Are you ready to do this? It's a risky business, but the company will pay 50 caps for the return of letters.}
{306}{}{Looks like one of the local gangs. I don't think finding them will be a big problem. I'm in.}
{307}{}{Very good. Payment upon return. Good luck.}
{308}{}{Yes, bye.}
{309}{}{Robbers, slums... No, I won't take that risk for some caps.}
{310}{}{Of course I understand. Have a nice day.}
{311}{}{Yes, bye.}
{312}{}{Remind me where the letters were stolen.}
{313}{}{The area of the eastern slums where the poor live. There's also this inhuman arena where they fight to the death.}
{314}{}{Thank you. One more question, please.}
{315}{}{I see, goodbye.}
{316}{}{I came across someone's letters. It doesn't look like they reached the recipients.}
{317}{}{Let me see... Ah, finally! These letters were considered lost after our courier was robbed in the slums. You have no idea what a service you have rendered us.}
{318}{}{You're welcome. Is there a fee due for the find?}

{320}{}{Are these the letters in question? They were taken over by a man from the gang of Red Cardinals.}
{321}{}{Ah, finally! You have no idea what kind of service you are providing us. Let me see... Yes, it's them.}
{322}{}{And my caps?}
{323}{}{Of course, here are 50 caps. You know what, I'll pay you another 25 caps for their delivery. More precisely, for the delivery of one of these letters. It is addressed to a certain Steve, who lives in those very dangerous slums. It looks like you managed to walk there safely, and we just need *guaranteed* delivery.}
{324}{}{Of course, more caps won't hurt me.}
{325}{}{That's how it always is. If you help once, everyone will reach out to you. Okay, give it here.}
{326}{}{Let's sign a short contract. So... Great. Now go to the slums and hand over the letter on receipt. Good luck.}
{327}{}{[Leave the office]}

{330}{}{The letter was delivered to the address. Here is the recipient's receipt.}
{331}{}{Wonderful. Here are your honestly earned 25 caps. I hope it is not necessary to clarify that we will not tolerate deception.}
{332}{}{Of course.}
{333}{}{Thank you for your cooperation, it was a pleasure to work with you. But I'm afraid there won't be any new deliveries in the near future.}
{334}{}{Goodbye.}
{335}{}{About that letter. There is no one else to receive it. The addressee died.}
{336}{}{What a pity. Well, it happens. The contract takes into account such an overlay. You only get half the fee. Here are your 12 caps.}
{337}{}{This is outrageous! I demand full payment!}
{338}{}{Read the contract. You signed it. And there's nothing to shout here now.}
{339}{}{Wh... how... Ur-rh.}
{340}{}{Well, that's fair. There are no complaints.}
{341}{}{[Leave the office with a sense of accomplishment]}
{342}{}{Remind me where I had to take this letter.}
{343}{}{(sighs in frustration) The letter is addressed to a certain Steve, who lives in a slum near the arena. I repeat: in the slums near the arena. Is that clear? Write it down so you don't forget.}
{344}{}{I hear you, woman.}
{345}{}{Thanks, I see now.}