{100}{}{You see a rebel.}
{101}{}{You see a person in a balaclave. He's busy checking his equipment.}
{102}{}{You see a person in a balaclave. He's clearly ready to fight for his goals.}
{103}{}{You see a person in a balaclave. He looks ready for battle.}
{104}{}{You see a person in a balaclave. He starts to knead his fists upon seeing you.}

{110}{}{Hm-m...}
{111}{}{Even HQ isn't safe.}
{112}{}{We'll win.}
{113}{}{Damn fanatics.}
{114}{}{Those fanatics will get what they deserve.}
{115}{}{I don't like what they're doing.}
{116}{}{When we come to power, Phoenix will be different.}
{117}{}{It's time for us to get out of the shadows.}
{118}{}{I have a fungal infection from the underground.}
{119}{}{Right now, this is the best place for our HQ to be.}