{100}{}{You see an inquisitor.}
{101}{}{You see a man in robes. He's clearly looking for someone among these ruins.}
{102}{}{You will die in the name of the Fire.}
{103}{}{Fear the Holy Fire, scrapper.}
{104}{}{Glorify the Holy Fire.}

#First dialogue
{200}{}{Stop. In the name of the Holy Fire, answer what it is you're doing here.}
{201}{}{What I'm doing here is none of your concern. Step away.}
{202}{}{Spoken like a heretic and blasphemer. Pray to the Holy Fire that it doesn't punish you for your foul language.}
{203}{}{Your words aren't any better. The only thing you can do is wave around a stick and make idle threats, right?}
{204}{}{I see you have a determined attitude. Please, I won't be here any longer.}
{205}{}{I'm, uhh, looking for valuable items.}
{206}{}{Look for them elsewhere, scrapper. Your dirty work interferes with the glorious acts of the Atom.}
{207}{}{Where is all this hostility coming from?}
{208}{}{Go away. Or you will learn the wrath of the Atom in form of my spear.}
{209}{}{You're threatening me with a rusty pipe? Get out of my way.}
{210}{}{Okay, okay...}
{211}{}{You again? In the name of the Holy Fire - go away.}
{212}{}{Okay, okay...}

{220}{}{I have a meeting with a guy here. Did you see him?}
{221}{}{Oh, perhaps. What connects you with this spy?}
{222}{}{You misunderstood me. I, uh, I just trade junk I find in ruins. What did the guy do?}
{223}{}{Stay out of this, scrapper. Go, continue to pick your dirt.}
{224}{}{Uhh, okay...}
{225}{}{You will pay dearly for your insults, you pigrat.}
{226}{}{I don't believe a single one of your deceptive words. Stand on your knees, pathetic creature...}
{227}{}{Hey, keep your hands off me...}
{228}{}{Spy? No, we're just looking for valuable items among those ruins together.}
{229}{}{Spy? No, you must have made a mistake.}
{230}{}{Is this true? Well, we don't have any evidence but a few rumours. We'll just have to release you both.}
{231}{}{Oh, thanks.}
{232}{}{Don't dare speak of what happened here. And fear the Holy Fire.}
{233}{}{Yeah, yeah, uhh, of course...}
{234}{}{Oops...}

{250}{}{Initiate? What are you doing here?}
{251}{}{I think we are here for one and the same purpose, looking for one and the same man. And you are to step away if you do not wish to learn Aaron's wrath.}
{252}{}{Aaron sent you? Well, this changes a lot. We will not interfere with your mission.}
{253}{}{Thank you for your understanding.}
{254}{}{Just looking for ancient relics. See you, brother.}

{260}{}{Initiate? Hm, I didn't see you before? What are you doing here?}
{261}{}{You've made a mistake, you fool. I am no initiate. And this mistake will cost you your life!}
{262}{}{Just looking for ancient relics. See you, brother.}
{263}{}{Initiate? No, I have no idea what you're talking about...}
{264}{}{This is a spy! Get them, brothers!}
{265}{}{Oops...}