{100}{}{There is a rebel in front of you.}
{101}{}{You see a man in a balaclava. He seems to be hiding from someone.}
{102}{}{It seems to have passed. Then I'll find my way. See you at the base.}
{103}{}{Thanks for the help. Together we will achieve freedom for Phoenix.}
{104}{}{In front of you are the ruins of a once large city. There's probably an increased level of radiation here.}

#The first dialog
{200}{}{And... who else are you?}
{201}{}{Alice and Marcos sent me. They've lost touch with you.}
{202}{}{Finally... But quiet! We must not be heard. I don't know how these monks figured me out. They're smarter than they look. Will you help me get back to base?}
{203}{}{What about your assignment?}
{204}{}{To hell with it. Now we need to get out of the clutches of these sectarians. In addition, the lighthouse remained in the opposite building, it is now impossible to get close to it.}
{205}{}{We need to leave.}
{206}{}{It will not be possible to pass by the cultists unnoticed ... Hmm, but how did you manage it?}
{207}{}{We'll have to fight our way to the exit. Are you ready? Then let's go.}
{208}{}{First you need to finish your assignment. Wait here.}

#Repeat dialog
{210}{}{We need to get back to headquarters. And in no case bring the tail there.}
{211}{}{Sure. Let's get out of here.}
{212}{}{Wait here, I'll go scouting.}
{213}{}{Let's go. They're waiting for us at the General Staff.}
{214}{}{Wait here, I'll scout the situation.}
{215}{}{Remind me of your assignment?}
{216}{}{I had to install a beacon in that old building. He's still there. I had to throw all the equipment in order not to get burned. And I'm not going back there, it's too risky. What if they set up an ambush?}
{217}{}{It seems to have passed. Then I'll find my way. See you at the base.}
{218}{}{OK, see you later.}
{219}{}{It seems to have passed. If it weren't for you, I'd be in for a sad fate. Thanks for the help.}