{100}{}{You see Alice.}
{101}{}{You see a woman with a very persistent look. If you wanted to convince her of something, you would have a complete failure.}
{102}{}{I've got you in my sights. But let Marcos decide what to do with you.}
{103}{}{It's because of you that we failed our mission!}
{104}{}{We won thanks to you. Thank you.}

#Dialog
{200}{}{Marcos has permitted you to be at headquarters. But don't think that it immediately gives you confidence. Earn it by deeds and watch your tongue.}
{201}{}{Of course I understand.}
{202}{}{Given your reception, there is no need to talk about trust.}

{210}{}{Greetings, brother. How can I help you?}
{1210}{}{Greetings, Sister. How can I help you?}
{211}{}{See you later, Sister.}

{220}{}{Tell me about yourself.}
{221}{}{It is not customary for us to talk about our past. We are gathered here not for the sake of communication, but for the sake of a common cause.}
{222}{}{How did you get into this movement?}
{223}{}{Of course, I'm sorry.}
{224}{}{I'm telling you, it doesn't matter. I will only say that initially, I had personal motives. Now I'm fighting for an idea, it's much higher.}
{225}{}{A sad story. Do you mind if I ask you something else?}
{226}{}{Tell me about Marcos.}
{227}{}{He is a great man.}
{228}{}{Um, is that it?}
{229}{}{Well, he has a dark past. I only know that before the creation of the Party, he experienced some kind of tragedy.}
{230}{}{Are you in love with him?}
{231}{}{Wh... how... listen, of course, I admire him as a leader. After all, he gathered so many people under a common noble goal. But I don't even know his face, he never took off his balaclava in front of me.}
{232}{}{Thank you for such a, uh, detailed answer.}
{233}{}{I see. Thanks for the reply.}
{234}{}{And what are you doing here?}
{235}{}{This is our general staff. Here we discuss plans, and store and prepare equipment.}
{236}{}{Can I use your workbenches?}
{237}{}{I don't mind if it helps our common struggle.}
{238}{}{Thank you.}
{239}{}{What is this place?}
{240}{}{Once it was an underground tram station. The passageways collapsed during the nuclear bombing, leaving only an exit to the sewer. Therefore, few people can find this place.}

#Issue of equipment
{250}{}{I need equipment to complete the task.}
{251}{}{OK. Marcos says you should be trusted. You can inspect our supplies. What do you need for the task?}
{252}{}{Nothing now. We will return to this a little later.}
{253}{}{If this is not enough, then you can contact a gun store in downtown. The owner sells us the goods in secret from the sectarians. Just tell him the code phrase: "There are no people more loyal to the emperor than a handful of peasants."}
{254}{}{Great. I'm going on a mission. Bye, Alice.}
{255}{}{}
{256}{}{What you need.}
{257}{}{Sniper equipment.}
{258}{}{Here's a hunting rifle and a box of cartridges. That's enough for you.}
{259}{}{Equipment for the assault.}
{260}{}{Isn't it too risky to go ahead? Okay, you and Marcos know better. Here is a submachine gun and a box of cartridges, 10 mm caliber. Take also a couple of grenades and a stimpack in case of injury.}
{261}{}{Equipment for espionage.}
{262}{}{Let's see. Flash in case of darkness, stealth combat for stealth, and explosives in case of emergency. Take a stimpack as well, in case the disguise doesn't work.}

{270}{}{Are you the one fueling the local explosives? I could use such a skill.}
{271}{}{I'm sorry, but I don't have time for lectures.}
{272}{}{I can pay with caps. This compensates for your labor costs.}
{273}{}{These bottlecaps can be used for the work of our Party and save a lot of time. If you get 350 caps, I'll teach you the tricks I know.}
{274}{}{Agreed. I'll be back with the caps.}
{275}{}{I understand, forget it.}
{276}{}{Considering that I saved the Party agent, you could have been more loyal to me.}
{277}{}{Your truth. Sorry, there's too much going on right now. And yet it would be fair to donate a hundred caps to our cause.}
{278}{}{Here are a hundred caps...}
{279}{}{Here are 350 caps...}

#Tasks
{300}{}{Marcos sent me to the surface. What should I do?}
{301}{}{Okay, listen carefully. One of our agents went to the ruins on the surface to install a radio beacon. Since then, the connection with him has been lost. We don't know what happened. Find him and finish his job.}
{302}{}{Why do you need a beacon on the ruins?}
{303}{}{We use radio communication for our negotiations and wiretapping of sectarians. But the signal is jammed underground. That's why we need an amplifier on the surface.}
{304}{}{Clear. I'm going to the surface.}
{305}{}{Will they give me equipment?}
{306}{}{A simple foray into the ruins awaits you. If you can't handle this situation, how did you get here in the first place? In any case, Marcos did not permit to give you equipment.}
{307}{}{Really. See you later.}
{308}{}{If I die, it will be on your conscience.}

{310}{}{Where exactly to look for an agent?}
{311}{}{Go to the big collector and turn west. You need to get out into the ruins of the old town near the Union station. I hope you don't get lost.}
{312}{}{Let's talk about my assignment.}
{313}{}{What are the successes in the case?}
{314}{}{None yet. I'll do it right now.}
{315}{}{About that agent. He's dead.}
{316}{}{Damn... It's bad. And what about the signal amplifier?}
{317}{}{I don't know yet.}
{318}{}{The amplifier is installed. You can check the signal strength.}
{319}{}{Then let's not waste time...}
{320}{}{[Next]}
{321}{}{This is much more important. Find an amplifier and install it on the surface. We don't have another one like that.}
{322}{}{I'm going to deal with this issue.}
{323}{}{The lost agent was ambushed by the monks. But I managed to get him out.}
{324}{}{Thank you, we appreciate saving the agent. But someone still has to install radio equipment on the surface.}
{325}{}{}
{326}{}{I will deal with this problem.}
{327}{}{I managed to find and start the radio signal amplifier.}
{328}{}{Very good. Wait a bit, I need to check the signal strength...}
{329}{}{[Next]}
{330}{}{Great job. And what about our agent?}
{331}{}{Your agent is dead.}
{332}{}{It's bad... Very bad. Wait a bit, I need to check the equipment...}
{333}{}{[Next]}
{334}{}{I couldn't find it. Maybe he ran away?}
{335}{}{It is more likely that he was captured by sectarians. Try to find out what happened to him while I'm dealing with this equipment.}
{336}{}{OK, I'll take care of this issue.}
{337}{}{Great job. Now it will be easier for us to listen to the fire worshippers' broadcasts. Tell Marcos about your success.}
{338}{}{OK. Bye, Alice.}