{100}{}{Here is an Inquisitor.}
{101}{}{You see a man in a cassock. He's obviously looking for someone among these ruins.}
{102}{}{You will die in the name of Fire.}
{103}{}{Fear the Sacred Fire, scavenger.}
{104}{}{Praise the Sacred Fire.}

#The first dialog
{200}{}{Wait. In the name of the Sacred Fire, answer what you are doing here.}
{201}{}{This case does not concern you. Step aside, mummers.}
{202}{}{Words worthy of a heretic and a blasphemer. Pray to the Sacred Fire that it does not punish you for swearing.}
{203}{}{Your words are no better. All you can do is wave a stick with empty threats, right?}
{204}{}{I see you have a serious attitude. Please, I won't be here anymore.}
{205}{}{I'm, uh, looking for useful things.}
{206}{}{Look elsewhere, scavenger. Your dirty work interferes with the bright affairs of the Atom.}
{207}{}{Why so much ill will?}
{208}{}{Get out. Otherwise you will know the wrath of the Atom from my spear.}
{209}{}{Are you threatening me with a piece of rusty pipe? Get out of the way, mummers.}
{210}{}{Okay, okay...}
{211}{}{You again? In the name of the Sacred Fire, go away.}
{212}{}{Okay, okay...}

{220}{}{I have a meeting with a guy. Have you seen him?}
{221}{}{Oh, maybe. What is your connection with this spy?}
{222}{}{You misunderstood. I'm, uh, just selling trash from the ruins. What did he do?}
{223}{}{Stay out of trouble, scavenger. Go on digging in your dirt.}
{224}{}{Uh, okay...}
{225}{}{Now you will pay cruelly for your insults, you mummified pig-rat.}
{226}{}{I don't believe your lying words. Get on your knees, atomic creature...}
{227}{}{Hey, no hands...}
{228}{}{Spy? No, we're just looking for useful things with him in the ruins.}
{229}{}{Spy? No, you were wrong.}
{230}{}{It's true? Well, we have nothing but rumors. I'll have to let you both go.}
{231}{}{Ugh, thanks.}
{232}{}{Don't you dare talk about what happened here. And fear the Sacred Fire.}
{233}{}{Yes, yes, uh, of course...}
{234}{}{Oh, oh...}

{250}{}{Dedicated? What are you doing here?}
{251}{}{I think we're looking for the same person. And you should give in if you don't want to know the wrath of Aaron.}
{252}{}{Did Aaron send you? Well, that changes a lot. We will not interfere with your mission.}
{253}{}{Thank you for your understanding.}
{254}{}{Just looking for ancient relics. See you later, brother.}

{260}{}{Dedicated? Hmm, I haven't seen you before. What are you doing here?}
{261}{}{You made a mistake, you fool. I'm not an initiate. And this mistake will cost you your life!}
{262}{}{Just looking for ancient relics. See you, brother.}
{263}{}{Dedicated? No, I don't even know what...}
{264}{}{It's a spy! Grab him, brothers!}
{265}{}{Oh, oh...}