{100}{}{You see a rebel.}
{101}{}{You see a man in a balaclave. Looks like he's hiding from someone.}
{102}{}{Looks like we're in the clear. I'll find the way myself. See you at the base.}
{103}{}{Thanks for the help. Together, we will ensure Phoenix's freedom.}
{104}{}{You see the ruins of a once-giant city. They are sure to have an increased level of radiation.}

#First dialogue
{200}{}{Ah... who are you?}
{201}{}{I was sent here by Marcos and Eliza. They lost contact with you.}
{202}{}{Finally... But be quiet! We must not be heard. I don't know how those monks found me. They're smarter than they look. Will you help me get back to the base?}
{203}{}{What about your mission?}
{204}{}{To hell with it. First, we need to get out of the cultists' claws. And I left the beacon in a building all over there anyway, we won't get to it now.}
{205}{}{We must go.}
{206}{}{We won't be able to walk past those cultists undetected... Hm, how did you manage to do it?}
{207}{}{We'll have to use force to get out. Are you ready? Then let's go.}
{208}{}{I need to finish your mission first. Wait here.}

#Repeated dialogue
{210}{}{We have to return to HQ. And under no circumstances let ourselves be followed.}
{211}{}{Of course. Let's get out of here.}
{212}{}{Wait here, I'll go scout.}
{213}{}{Let's go. They're waiting for us in HQ.}
{214}{}{Wait here, I'll go check the situation.}
{215}{}{Remind me, what was your mission?}
{216}{}{I was to set up a radio beacon in that old building. It's still there. I had to leave all the equipment behind. And I won't return there, it's too risky. What if they ambush me?}
{217}{}{Looks like we're in the clear. I'll find the way myself. See you at the base.}
{218}{}{Great, until next time.}
{219}{}{Looks like we're in the clear. If you didn't help me, I'd meet a sad end. Thanks.}