{100}{}{You see Eliza.}
{101}{}{You see a woman with a very determined look. If you wanted to change her mind, you would completely fail.}
{102}{}{You're in my gun's sights. But Marcos is to choose what to do with you.}
{103}{}{We failed because of you!}
{104}{}{We won thanks to you.}

#Dialogue
{200}{}{Marcos allowed you to walk in our headquarters. But don't think that this means everyone trusts you here. Earn this trust and watch your mouth.}
{201}{}{Of course, I understand.}
{202}{}{Considering your welcome, there's no point talking about trust.}

{210}{}{Welcome, brother. How can I help you?}
{1210}{}{Welcome, sister. How can I help you?}
{211}{}{Until next time, sister.}

{220}{}{Tell me about yourself.}
{221}{}{Usually we don't talk about the past. We're here because of a common cause, not because we want to chat.}
{222}{}{How did you become a part of this movement?}
{223}{}{Of course, sorry.}
{224}{}{I'm telling you - it doesn't matter. I will tell you only that at first, I had personal motives. But now, I fight for the idea, for it is much higher than any of us.}
{225}{}{A sad story. You won't mind if I ask you something else?}
{226}{}{Tell me about Marcus.}
{227}{}{He's a great man.}
{228}{}{Um, is that all?}
{229}{}{Well, he has a dark past. I know only that before the creation of the Party, he experienced some kind of tragedy.}
{230}{}{I get the feeling that you have feelings for him.}
{231}{}{Wh... how... Listen, of course I'm delighted with him as a leader. After all, he brought together so many people for one noble goal. But I don't even know what he looks like. He never took off his balaclave near me.}
{232}{}{Thanks for the, uhh, detailed answer.}
{233}{}{Understood. Thanks for answering.}
{234}{}{And what is it you do here?}
{235}{}{These are our headquarters. Obviously, we discuss plans here, store and prepare equipment.}
{236}{}{Could I utilize your workbenches?}
{237}{}{I don't mind, if it helps our cause.}
{238}{}{Thanks.}
{239}{}{What is this place?}
{240}{}{This was once an underground tram station. The passages collapsed during the atomic bombardment, and only the exit into the sewers is left. That's why so few can find this place.}

#Equipment given out
{250}{}{I need equipment to complete this task.}
{251}{}{Alright. Marcos says you can be trusted. You can examine what we have. What do you need exactly?}
{252}{}{Nothing for now. Let's return to this a bit later.}
{253}{}{If that isn't enough, you can simply head to the gun store in the downtown area. The owner sells us goods in secret, without the knowledge of the cultists. Just tell him the code phrase: "No man is more loyal to the king than a poor peasant".}
{254}{}{Great. I'm off to do the task. Goodbye, Eliza.}
{255}{}{}
{256}{}{Just what I need.}
{257}{}{Sniper equipment.}
{258}{}{Here's a hunting rifle and a box of bullets. That will be enough.}
{259}{}{Assault equipment.}
{260}{}{Isn't it a bit too risky to go in guns blazing? Well, you and Marcos know better. Here is a sub-machine gun and a box of 10 mm bullets. Take a couple of grenades and a stimpak if you get hurt.}
{261}{}{Espionage equipment.}
{262}{}{Let's have a look. Flare in case of darkness, stealth boy for, well... stealth, and an explosive for an emergency. Also take a stimpak in case you are detected.}

{270}{}{So, you seem to be an expert in explosives here? I would sure use that skill.}
{271}{}{Sorry, but I don't have time to hold lectures.}
{272}{}{I could pay you caps. That will be compensation for the effort you've spent.}
{273}{}{Those caps could go toward the cause of our Party and save a lot of time. If you get 350 caps, I'll teach you all the tricks I know.}
{274}{}{Deal. I'll return with the caps.}
{275}{}{I understand, forget it.}
{276}{}{Considering that I've saved a Party agent, I think you could help me out.}
{277}{}{True. Sorry, there's so much going on lately. But still, a donation of 100 caps toward our cause would be fair.}
{278}{}{Here are 100 caps...}
{279}{}{Here are 350 caps...}

#Tasks
{300}{}{Marcos sent me to the surface. What do I need to do?}
{301}{}{Alright, listen carefully. One of our agents went to ruins on the surface to set up a radio beacon. Since then, we lost contact with him. We don't know what happened to him. Find him and finish what he went there to do.}
{302}{}{Why do you need a radio beacon in the ruins?}
{303}{}{We're using radio communication to communicate among ourselves and to eavesdrop on the cultists. But underground, the signal is not as strong. This is why we need an amplifier on the surface.}
{304}{}{Got it. Heading out onto the surface.}
{305}{}{Will I be given equipment?}
{306}{}{It's just a simple ruin excursion. If you can't deal with a situation like that, how did you even get here? In any case, Marcos didn't give me permission to give you out equipment.}
{307}{}{That makes sense. See you later.}
{308}{}{If I die, it will on your conscience.}

{310}{}{Where exactly do I need to look for the agent?}
{311}{}{Go into the sewers and then to the west. You need to exit in the remains of the old city, by the "Union" station. I hope you don't get lost.}
{312}{}{Let's talk about my assignment.}
{313}{}{What successes did you have?}
{314}{}{None, so far. I'll go change that right away.}
{315}{}{Speaking of that agent, he's dead.}
{316}{}{Shit... That's bad. What about the signal amplifier?}
{317}{}{I don't know yet.}
{318}{}{Amplifier's set up. You can check the signal right away.}
{319}{}{Then let's not waste any time...}
{320}{}{[Continue]}
{321}{}{This is much more important. Find the amplifier and set it up on the surface. We don't have another.}
{322}{}{I'll go deal with this.}
{323}{}{The lost agent happened to be ambushed by monks. But I managed to get him out.}
{324}{}{Thank you, we value you saving the agent. But someone still needs to set up the radio equipment on the surface.}
{325}{}{}
{326}{}{I'll go deal with this problem.}
{327}{}{I managed to find and turn on the radio signal amplifier.}
{328}{}{Very good. Wait a bit, I need to check the signal level...}
{329}{}{[Continue]}
{330}{}{Excellent work. Now, what about our agent?}
{331}{}{Your agent is dead.}
{332}{}{That's bad... Very bad. Wait a bit, I need to check equipment...}
{333}{}{[Continue]}
{334}{}{I didn't manage to find him. Perhaps he ran away?}
{335}{}{The more likely scenario is that the cultists captured him. Try to find out what happened to him while I check the equipment.}
{336}{}{I'll go deal with that.}
{337}{}{Excellent work. Now eavesdropping on the cultists' radio transmissions will be much easier. Tell Marcos of your success.}
{338}{}{Good. Bye, Eliza.}