{100}{}{There is a rebel in front of you.}
{101}{}{You see a man in a balaclava. He's busy checking his gear.}
{102}{}{You see a man in a balaclava. He is definitely ready to defend his goals.}
{103}{}{You see a man in a balaclava. He looks ready for battle.}
{104}{}{You see a man in a balaclava. When he sees you, he kneads his fists.}

{110}{}{Hmm...}
{111}{}{Even the headquarters is not safe.}
{112}{}{We will win.}
{113}{}{Damn fanatics.}
{114}{}{These fanatics will get what they deserve.}
{115}{}{I don't like what they're doing.}
{116}{}{When we come to power, Phoenix will be different.}
{117}{}{It's time for us to come out of the shadows.}
{118}{}{I developed a fungus from this subway.}
{119}{}{Now this is the best place for the general Staff.}