{100}{}{This is Marcos.}
{101}{}{You see a man in a balaclava. His look betrays a willingness to fight.}
{102}{}{Go ahead, comrade. The whole Phoenix is waiting for your feat.}
{103}{}{Now everything will be different. No inquisition, no tyranny, no wars with neighbors. Thank you, comrade.}

#Dialog
{200}{}{I am surprised by your visit. Few people know about this place, and traps scare away even the most experienced. But you're here. And it's pretty damn inspiring. What brought you to our Party?}
{201}{}{A party? Yes, I'm here by accident. And what do you do in general?}
{202}{}{Are you saying that you managed to find this box and circumvent our traps solely out of luck? It sounds very doubtful. But now there is no point in hiding - we are fighting against the Followers of Fire and their leader Aaron. What do you think about it?}
{203}{}{I'm here to eliminate your entire criminal gang.}
{204}{}{Oh-very good. Capture the spy!}
{205}{}{Just try...}
{206}{}{Hey, I was misunderstood...}

{210}{}{Your cause is worthy of respect. I don't tolerate all these sectarians, just like you.}
{211}{}{You are ordinary criminals. You need to be stopped.}
{212}{}{Hmm, so far I like you. Since we have common interests, I hope for your cooperation. Will you help in our fight?}
{213}{}{You can count on me.}
{214}{}{It depends on what you need to do.}
{215}{}{Hey, don't involve me in anything!}
{216}{}{I am very sorry to hear such an answer. The first impression is always deceptive.}
{217}{}{I won't tell anyone. I promise.}
{218}{}{And you're more perceptive than you seem. I'll have to eliminate you.}
{219}{}{I'm afraid this answer doesn't suit me. Capture the spy!}
{220}{}{Oh...}
{221}{}{It was in vain...}
{222}{}{Why don't I just leave and we'll forget about everything that happened here?}
{223}{}{You don't expect to leave here without consequences, do you? Let's see what happens.}
{224}{}{Uh, I think I'll just leave. Bye.}
{225}{}{I want to join your Party.}
{226}{}{Very good. But we can't risk trusting the first person we meet. Tell me about yourself. Who are you and how do you know about the Liberation Party?}
{227}{}{I'm looking for my family. They were enslaved and brought to this city. I need help finding them.}
{228}{}{In fact, I'm on the lookout for dubious dangerous types that need to be eliminated. And it looks like I found them.}
{1228}{}{In fact, I'm on the lookout for dubious dangerous types that need to be eliminated. And it looks like I found them.}
{229}{}{ (nods significantly) I understand you. Everyone here has lost someone. Apparently, our paths did not meet by chance. After all, few people know that the main customer for slave labor is a sect of fire worshippers. We are fighting against these bastards. We should join forces.}
{230}{}{Hmm-m. Take a look around and get to know the team while I figure out a plan.}
{231}{}{OK.}
{232}{}{If it helps to get my people back, then I'm in.}
{233}{}{How can I be useful to your movement?}
{1233}{}{What can I do for your movement?}
{234}{}{The Rangers sent me. They offer their help in the fight against Aaron.}
{235}{}{Rangers. I was hoping for their help, but I was counting on more... impressive reinforcements. In any case, we welcome any help.}
{236}{}{Our cause is right.}
{237}{}{Waiting for instructions.}
{238}{}{Prior Mathias sent me from the Cathedral. I am aware of your affairs, and I want to help.}
{239}{}{Mathias doesn't throw words around for no reason. Apparently, we have less and less time left, we must act more decisively.}

{250}{}{Greetings, brother.}
{1250}{}{Greetings, sister.}
{251}{}{See you later.}

{260}{}{Tell us about your organization.}
{261}{}{We are the Phoenix Liberation Party. Our goal is to rid the city of Aaron's power and undermine the false church.}
{262}{}{Why did you call the church false?}
{263}{}{Fire worshippers misinterpret the old religion, trying to justify the inhumane actions of their leader. They forgot about the pre-war covenants.}
{264}{}{Why is it so important for you to overthrow Aaron?}
{265}{}{Without its leader, the church will fall in the eyes of the city.}
{266}{}{And what are you going to do after you achieve your goal?}
{267}{}{Building a new society. A society based on community and equality, not on separation and subordination.}
{268}{}{Thank you. Now I know enough.}

{270}{}{Tell me about your past.}
{271}{}{It doesn't matter.}
{272}{}{Whatever you say.}
{273}{}{We have to trust each other, don't we?}
{274}{}{Sure, but don't forget we're not here for a party.}
{275}{}{Yeah, uh, it's over.}
{276}{}{I was born a few years ago when Aaron came to power in the city. The man I was before is dead.}
{277}{}{Surely there was a personal reason for this. Have you lost someone close to you?}
{278}{}{And you are more perceptive than you seem. When he came to power, Aaron destroyed all the objectionable ones who could have prevented him and whom he could reach. Punitive bonfires lit up the whole city.}
{279}{}{[Next]}
{280}{}{Many then lost their loved ones. But, as I said, the past doesn't matter.}
{281}{}{Why was this tolerated?}
{282}{}{There was a famine in Phoenix then. Getting rid of extra mouths and oppressing the weak was to many's advantage. Aaron himself is only trying to strengthen himself in power, and all this church nonsense attaches importance to his words.}
{283}{}{Ugh, it must have been a tragedy for the city. Now let's talk about today.}

#Quests
{300}{}{What will be the orders?}
{301}{}{I have a task for you. One of our agents on the surface is missing. Alice will tell you the details of the task.}
{302}{}{OK, I'll talk to her.}
{303}{}{I need equipment for our fight.}
{304}{}{Talk to Alice about it, she's in charge of the warehouse, I'm busy with more important issues.}
{305}{}{OK.}

{310}{}{Alice told me about your success. Well done. With your help, our business is moving faster.}
{311}{}{Well, if you say so.}
{312}{}{Oh, I'm really cooler than all your fighters. Don't doubt it.}
{313}{}{It is a pity that our agent could not be saved. But perhaps it's for the best, because no one knows what information he could tell the sectarians.}
{314}{}{Leaving him in the clutches of the monks would be too risky. It was the only way out.}
{315}{}{Actually, I had nothing to do with it. It just so happened.}
{316}{}{The fighter you saved told you what happened. Getting out of such a trap is impressive.}
{317}{}{Oh yes. Crossfire, explosions... You should have seen what a shootout there was. Our lives were hanging by a thread.}
{318}{}{It wasn't difficult.}

{320}{}{Well, we need your skills. I think it's worth getting down to business in a big way, and you will help in this.}
{321}{}{What are you up to?}
{322}{}{Thanks to the signal booster, we learned a lot about sectarians. A rumor has been confirmed that there are secret levels under the cathedral. We don't know what the monks are doing there. But there are rumors that they are collecting powerful weapons. This is unacceptable.}
{323}{}{Are you suggesting we get in there and destroy the weapons? But HOW?}
{324}{}{There is a person in the cathedral who sympathizes with our ideas. His name is Mathias. However, he has his own scores with Aaron, and it is impossible to call him our agent in any way. Your task is to contact Mathias and get further instructions from him.}
{325}{}{The task is clear.}
{326}{}{Good luck. The city can no longer tolerate Aaron's unlimited power.}
{327}{}{Contact Mathias, infiltrate the lab and destroy the weapon. Clear.}
{328}{}{There is a person in the cathedral who sympathizes with our ideas. His name is Mathias. However, he has his own scores with Aaron, so it is impossible to call him our agent in any way. Your task is to contact Mathias so that we can prepare for the capture of the cathedral. He will give further instructions.}
{329}{}{See you again, Marcos.}

{330}{}{Aaron is defeated.}
{331}{}{Wonderful news! But that's not enough. We have to destroy the WHOLE cult. As long as Aaron's followers are alive, this fight will not end. Moreover, it is unknown what decisions the new leaders of the church will make.}
{332}{}{What to do?}
{333}{}{This news does not change your main mission - to get into the secret lair under the Cathedral and destroy it with the help of local weapons. Our agent, Mathias, will help you. Good luck, comrade.}
{334}{}{It was easy now.}