{100}{}{You see Marcos.}
{101}{}{You see a man in a balaclava. His gaze shows readiness to fight.}
{102}{}{Act, comrade. All of Phoenix is waiting for you to do it.}
{103}{}{Things will be different now. No inquisition, no tyranny, no war with our neighbors. Thank you, comrade.}

#Dialogue
{200}{}{I'm very surprised with your visit. Few know about this place, and the traps scare away even the most experienced. But you're here. And that's damn encouraging. What brought you to our Party?}
{201}{}{Party? I'm just here by accident. It doesn't look like any party I've ever seen in here.}
{202}{}{You mean to tell me that you managed to find this place and not get caught in our traps just out of luck? Sounds quite suspicious. But there's no point in hiding it now - we're fighting against the Followers of the Fire and their leader, Aaron. What do you think about this?}
{203}{}{I'm here to terminate your entire criminal group.}
{204}{}{Very good. Capture the spy!}
{205}{}{Just try it...}
{206}{}{Hey, you misunderstood...}

{210}{}{Your cause is worthy of respect. Just like you, I can't stand all those cultists.}
{211}{}{You're just regular criminals. You need to be stopped.}
{212}{}{Hm-m, I like you. At the moment. Since we have common interests, I'm hoping for your cooperation. Will you help us in our fight?}
{213}{}{You can count on me.}
{214}{}{Depends on what that help is.}
{215}{}{Hey, don't get me involved in anything!}
{216}{}{It's very sad to hear such an answer. Covers always lie.}
{217}{}{I won't tell anyone. I swear.}
{218}{}{You're more discerning than you look. You'll have to be removed.}
{219}{}{I'm afraid that answer won't suit me. Capture the spy!}
{220}{}{Oh...}
{221}{}{That wasn't the best decision...}
{222}{}{Why don't I just go and we both forget this ever happened?}
{223}{}{You aren't counting on walking out of here without consequences, are you? Let's see what this results in.}
{224}{}{Uhh, I think I'll just go. Bye.}
{225}{}{I want to join your Party.}
{226}{}{Very good. But we can't risk by trusting every person we see. Tell me about yourself. Who are you and where did you learn about the Liberation Party?}
{227}{}{I'm looking for my people. They were enslaved and brought into this city. I need help finding them.}
{228}{}{I'm really looking for suspicious, dangerous kinds of people that need to be terminated. And it looks like I found them.}
{1228}{}{I'm really looking for suspicious, dangerous kinds of people that need to be terminated. And it looks like I found them.}
{229}{}{(nods empathetically) I understand you. Everyone here lost someone. It looks like our paths didn't cross for nothing. Few know that the main client for the slavers is the Fire-worshipper cult. We are fighting those bastards. We should join forces.}
{230}{}{Hm-m. Take a look around, meet the team while I think over the plan.}
{231}{}{Good.}
{232}{}{If it helps me bring back my people, I'm in.}
{233}{}{How can I help your movement?}
{1233}{}{How can I help your movement?}
{234}{}{I was sent here by the Rangers. They are offering their help to fight Aaron.}
{235}{}{The Desert Rangers. I was hoping they would help, but I expected more... impressive reinforcements. In any case - we are happy to get any help.}
{236}{}{Our cause is just.}
{237}{}{Awaiting orders.}
{238}{}{I was sent here by prior Mathias from the Cathedral. I know about your cause, and I want to help.}
{239}{}{Mathias doesn't speak for nothing. Looks like we are running out of time. We must act more decisively.}

{250}{}{Welcome, brother.}
{1250}{}{Welcome, sister.}
{251}{}{Until next time.}

{260}{}{Tell me about your organization.}
{261}{}{We are the Phoenixian Liberation Party. Our goal is to rid the city of Aaron's rule and destroy the false church.}
{262}{}{Why did you call the church false?}
{263}{}{The Fire-worshipper are incorrectly interpreting an old religion in their attempt at justifying the inhuman acts of their leader. They have forgotten about Pre-War testaments.}
{264}{}{Why is overthrowing Aaron so important?}
{265}{}{Without it's leader, public opinion of the church will fall.}
{266}{}{What are you going to do after you get your way?}
{267}{}{Build a new society. A society based around community and equality, not separation and subjugation.}
{268}{}{Thank you. I know enough.}

{270}{}{Tell me about your past.}
{271}{}{It doesn't matter.}
{272}{}{Whatever you say.}
{273}{}{We must trust each other, no?}
{274}{}{Of course, but don't forget that we aren't here to chat.}
{275}{}{Yes, uhh, of course.}
{276}{}{I was born a few years before Aaron came to power. The man I was before that died.}
{277}{}{I'm sure you had some personal reason. Did you lose someone close to you?}
{278}{}{You're more discerning than you look. When Aaron came to power, he killed everyone he considered unfit for the new order, that is, anyone who could theoretically try to stop him he could get his hands on. Fires lit the entire city.}
{279}{}{[Continue]}
{280}{}{Many lost their relatives then. But, as I said - the past doesn't matter.}
{281}{}{Why was that tolerated?}
{282}{}{Back then there was a time of hunger in Phoenix. Many supported the idea of getting rid of excess people and persecuting the weak. Aaron himself was just consolidating power, and the religion is what he uses to justify his actions to others.}
{283}{}{Ooh, that must have been a tragedy for the city. Let's talk about things closer to the present.}

#Quests
{300}{}{What are your orders?}
{301}{}{I have an assignment for you. One of our agents went missing on the surface. Eliza will tell you the details.}
{302}{}{Okay, I'll talk to her.}
{303}{}{To wage our fight, I need equipment.}
{304}{}{Talk to Eliza about that. She's responsible for the warehouse, while I am responsible for more important things.}
{305}{}{Okay.}

{310}{}{Eliza told me about your successes. Good work. Thanks to your help, we're becoming closer and closer to achieving our goal.}
{311}{}{Well, if you say so.}
{312}{}{Oh, I really am cooler than all your other fighters. Don't worry about it.}
{313}{}{It's very sad that you did not manage to save our agent. But perhaps it's for the best. Who knows what kind of information the cultists could have gotten out of him.}
{314}{}{Leaving him in the hands of the monks would have been far too risky. It was the only way.}
{315}{}{Actually, I'm not involved in this at all. It just happened that way.}
{316}{}{The fighter you rescued told me what happened. Getting out of an ambush like that is certainly impressive.}
{317}{}{Oh yeah. Crossfire, explosions... If only you saw the shootout that occured there. We almost lost our lives.}
{318}{}{It wasn't hard.}

{320}{}{Well, we need your skills. I think it's time to engage in more large-scale activity, and you will help us.}
{321}{}{What did you come up with?}
{322}{}{Thanks to the signal amplifier, we have learned a lot of new stuff about the cultists. The rumour that there are secret underground levels underneath the cathedral has been confirmed. What the monks do there, we have no idea. But there are rumours that they are constructing a powerful weapon. That cannot be allowed.}
{323}{}{You're proposing getting there and destroying the weapon? But how?}
{324}{}{There is a man in the cathedral that sympathizes with our ideas. His name is Mathias. Though he has his own problems with Aaron, and he can't really be called our agent. Your task is to contact Mathias and receive further instructions from him.}
{325}{}{The task is clear.}
{326}{}{Good luck. The city can't tolerate Aaron's unlimited authority any longer.}
{327}{}{Contact Mathias, get into laboratory, destroy weapon. Got it.}
{328}{}{There is a man in the cathedral that sympathizes with our ideas. His name is Mathias. Though he has his own problems with Aaron, and he can't really be called our agent. Your task is to contact Mathias, so that we will be able to further prepare to take over the cathedral. He'll give you further instructions.}
{329}{}{See you again, Marcos.}

{330}{}{Aaron is defeated.}
{331}{}{Great news! But that is not enough. We have to destroy the ENTIRE cult. While Aaron's followers are alive, this battle will not end. And more than that - we have no idea what decisions the church's new leaders will make.}
{332}{}{What do I have to do?}
{333}{}{These news don't change your main mission - get into the underground lair underneath the Cathedral and destroy it with the weapon being made here. Our agent Mathias will help you. Good luck, comrade.}
{334}{}{Now that was easy.}