{100}{}{You see Orris.}
{101}{}{You see the leader of the Red Cardinals.}
{102}{}{I need that armor. Gimme.}
{103}{}{...Fuh, this junk is hot as hell...}
{104}{}{I don't deal with cultists anymore.}

#Meeting
{200}{}{[Murphy] Look, guys, we've got a rat here. You *do* know where you are, you idiot? Hey, Orris, let me do some exercise on him...}
{1200}{}{[Murphy] Look, guys, we've got a rat here. You *do* know where you are, you bitch? Hey, Orris, let me relax with her...}
{201}{}{[Continue]}
{202}{}{[Orris] Murphy, stop. Don't be so bloodthirsty when it's our guests we're talking about. You. What do you want?}
{203}{}{I need just one thing - for scum like you to vanish off the face of the earth.}
{204}{}{If you're looking for trouble - you're in the right place.}
{205}{}{Great. Who's first?}
{206}{}{They say you're a force the local authorities have to reckon with. I want to join you.}
{207}{}{[Murphy] We have more than enough men. You think we need you? Get outta here, you fool.}
{1207}{}{[Murphy] We have more than enough men. You think we need you? Run while you still can, you bitch.}
{208}{}{[Continue]}
{209}{}{Murphy, friend, calm down. I need a messenger. Did you forget? Now, you. Come here.}
{210}{}{No way. I don't deal with bandits.}
{211}{}{We don't need idiots. Guys, deal with him.}
{1211}{}{We don't need idiots. Guys, deal with her.}
{212}{}{No. Don't do it. I beg you...}
{213}{}{You were beaten up and thrown on the streets. Your pockets were emptied.}
{214}{}{You were raped and thrown on the streets. Your pockets were emptied.}
{215}{}{Let's see what you're made of. Who's first?}
{216}{}{What do you want from me?}
{217}{}{To be honest, I'm here by accident. Release me. Please.}
{218}{}{[Murphy] I'm telling you - another idiot from the streets. We'll just empty his pockets and be done with it.}
{1218}{}{[Murphy] I'm telling you - the babe's head isn't set right. We'll just empty her pockets, polish her up and be done with it.}
{219}{}{[Continue]}
{220}{}{No, Murphy. I need a messenger. Did you forget? Now, you. Come here.}
{221}{}{What do you want from me?}
{222}{}{No way. I don't negotiate with bandits.}
{223}{}{You again? What is it you want so damn much?}
{224}{}{Hey, champion, nice to see you. That was an amazing fight. It's a shame you don't fight in the arena anymore.}
{1224}{}{Hey, champion, nice to see you. That was an amazing fight. It's a shame you don't fight in the arena anymore.}
{225}{}{Yeah. Can't rely on income from there now.}
{226}{}{You need caps? I could use more tough people right now... Goddammit, Murphy, shut up! I know who to trust. Now... listen. I have a job specifically for you.}
{227}{}{I'm all ears.}
{228}{}{No way. I don't want to be involved with bandits.}
{229}{}{Nothing out of the ordinary. A pal of mine was supposed to meet a courier, but went missing. Go to the caravan parking place and head down into the sewers there. That's where they were supposed to meet. Find out what happened, then head back to me. If you do everything right, you'll be rewarded.}

#First quest
{230}{}{Nothing out of the ordinary. You just need to find an old pal of mine. You see, he got lost somewhere in the big city.}
{231}{}{I'm not getting myself involved in shady things like that.}
{232}{}{You have a lot of people here. Why me?}
{233}{}{Everyone knows what my men look like. They shouldn't go flashing their face in the center of the city.}
{234}{}{Okay, I'll do it.}
{235}{}{See, Murphy? Everyone can be reasoned with. I get you, though...}
{236}{}{[Continue]}
{237}{}{Now listen closely. Go to the caravan parking place and head down into the sewers there. That's where my man was supposed to meet a courier. Find out what happened to them, then head back to me. If you do everything right, you'll be rewarded.}
{238}{}{You convinced me.}
{239}{}{Already on my way.}
{240}{}{Will I get paid if I do this?}
{241}{}{Of course.}
{242}{}{Remind me, where was the meeting supposed to take place?}
{243}{}{Go to the caravan parking place and head down into the sewers there. That's where my man was supposed to meet a courier. Find out what happened to them, then head back to me.}
{244}{}{Alright. Already on my way.}
{245}{}{My people shouldn't go flashing their face in the center of the city. Their reputation isn't as "good" as yours.}
{246}{}{Enough! I'll kill you PERSONALLY.}
{247}{}{Weak nerves you've got...}
{248}{}{Come on, dude, take it easy...}

{250}{}{Did you find the ones I was talking about?}
{1250}{}{Did you find the ones I was talking about?}
{251}{}{No. Not yet.}
{252}{}{Your pal and contact were attacked by Bruce's mercs. They took your pal.}
{253}{}{What the... Hey, Murphy, did you hear this? Those are bad news. He knew too much. If they push on him, they'll learn all our plans. We have to act quickly.}
{254}{}{What happened?}
{255}{}{Listen, you're not from here, right? I'll tell you something. In this city, only the strong survive. It can't be any other way. We're alive right now for one reason: we don't allow any trash to sharpen their knives against us. You want to secure your position in Phoenix - keep close to the right people.}
{256}{}{You mean... your people.}
{257}{}{And I want to offer you a deal. I don't care how, but I need to get my man out of jail or shut him up forever. You catch my drift? It's risky for us to show up in the center, but not for you. Come up with a way to do this, and I'll pay you 200 caps.}
{258}{}{I'll see what I can do.}
{259}{}{This is an impossible mission. It's too difficult for me.}

{260}{}{Anything new?}
{261}{}{Not for now. Your man is still in jail.}
{262}{}{Dammit, if they crack him during interrogation, you'll come under fire too - got it?}
{263}{}{Yeah. Got it...}
{264}{}{If there's one thing you shouldn't do, it's threatening me.}
{265}{}{I'm tired of this. I won't just not work for you, I'll hand over your whole damn gang to the mercs. So long, you son of a bitch.}
{266}{}{Your pal is dead. It wasn't easy, but I did it.}
{267}{}{Your pal is free. It wasn't easy, but I did it.}
{268}{}{You're a capable man. I was lucky to find you. Here is your reward: the caps and a stimpak. You can relax while I deal with this shit.}
{1268}{}{You're a capable woman. I was lucky to find you. Here is your reward: the caps and a stimpak. You can relax while I deal with this shit.}
{269}{}{Okay. I'll be back later.}

{270}{}{Looks like your men were set up. What will you do now?}
{271}{}{That could have been done only by the cultists in the Temple of Fire. Looks like they decided to get rid of us now that they've used us for their goals. But they don't care about us anymore after that explosion.}
{272}{}{So, you're free now?}
{273}{}{We have to make a grab for the unclaimed regions before someone else does it. By the way, we don't need you anymore. But I don't forget those who have been useful. Talk to the pusher in the slums. We have special relations with him.}
{1273}{}{We have to make a grab for the unclaimed regions before someone else does it. By the way, we don't need you anymore. But I don't forget those who have been useful. Talk to the pusher in the slums. We have special relations with him.}
{274}{}{Great, I'll keep that in mind. Bye, Orris.}
{275}{}{That could have been done only by the cultists in the Temple of Fire. Looks like they decided to get rid of us now that they've used us for their goals. But what I don't understand is how they learned of our secret deal.}
{276}{}{Could someone have told them?}
{277}{}{One of us? I find that hard to believe. We're just bandits to the cultists...}
{278}{}{[Continue]}
{279}{}{Listen, I need someone in the Temple. If you learn who betrayed us, I'll pay you a nice sum of caps. Deal?}
{280}{}{Deal. I'll find the rat in your gang.}
{281}{}{Getting inside the Temple? You're mad. I won't be able to do it.}
{282}{}{Did you find out who set us up?}
{1282}{}{Did you find out who set us up?}
{283}{}{It was Murphy. He's Aaron's agent.}
{284}{}{Murphy? I would have never thought that one of our best... Though, now that I think about it... He knew more about my plans than anybody else.}
{285}{}{It is definitely Murphy. I managed to listen in on him talking on the radio to a person in the Temple. Aaron wanted to control your gang by placing one of his men in a key position.}
{286}{}{Well, Aaron's plans have just been foiled. I'll get rid of Murphy. And I should reward you for your efforts. I wouldn't want to lose such a valuable agent. Here are the caps. And talk to the pusher in the slums. I have a special agreement with him.}
{287}{}{Bye, Orris.}
{288}{}{Murphy won't help the enemy any longer. Bye, Orris.}
{289}{}{I think that your men were set up by the cultists. But after the explosion, we'll never find out the truth.}
{290}{}{What's the situation between you and the fire-worshippers?}
{291}{}{The cultists consider us bandits and don't recognize our power over the slums. But when they need to, they're more than ready to negotiate.}
{292}{}{You said you performed an assignment for them.}
{293}{}{They paid us to sabotage the atomicists. We blew up their cooling system, but after that, it turned out we weren't useful to the cultists anymore, and they ghosted us.}
{294}{}{I see.}
{295}{}{But how do I do it?}
{296}{}{I don't know. But those monks have got to have everything recorded in dossiers.}
{297}{}{I'm still thinking on how to find the rat in the Temple?}

#Dialogue outside of quest
{300}{}{Say what you need.}
{301}{}{How are you, vagabond?}
{302}{}{Just wanted to see you. Already leaving.}

{310}{}{Did your men take the letters from the courier?}
{311}{}{I have no idea what you're talking about. Ask my people. If someone admits it, then we'll see.}
{312}{}{I'll do just that. Bye.}
{313}{}{I'll find the guilty, make no mistake.}

{320}{}{They say you killed my people in the slums. And now, you dare come before me. I will give you exactly one chance to convince me not to kill you.}
{1320}{}{They say you killed my people in the slums. And now, you dare come before me. I will give you exactly one chance to convince me not to kill you.}
{321}{}{It's their own fault.}
{322}{}{My region - my rules. People have to see that my power is to be reckoned with. Guys, deal with this trash...}
{1322}{}{My region - my rules. People have to see that my power is to be reckoned with. Guys, deal with this trash...}
{323}{}{Not in the face...}
{324}{}{You and your gang can go to hell.}
{325}{}{It's their own fault. Consider it something between us.}
{326}{}{Yes. Between them. And you. And don't you dare suggest otherwise to anyone. People have to see that my power is to be reckoned with.}
{327}{}{You have nothing to do with it.}
{328}{}{You've got me confused with someone else. It wasn't me.}
{1328}{}{You've got me confused with someone else. It wasn't me.}
{329}{}{You're lying. Guys, deal with this trash...}
{330}{}{Not in the face...}
{331}{}{Go to hell.}
{332}{}{I must have been confused with someone else. I mean, just look at me. You think I could I actually kill your men?}
{333}{}{The case is murky. I'll release you, for now. But if you're lying, we'll fuck you up. People have to see that my power is to be reckoned with.}
{334}{}{Of course...}
{335}{}{After what happened, I don't fear you. You and your band deserve nothing but death.}

{340}{}{Did you attack the monks?}
{341}{}{No, it wasn't us. You have my word.}
{342}{}{If it wasn't you, then who was it?}
{343}{}{I heard that there's some other gang. Guys that want to overthrow Aaron and set the people against the church. But they're cunning - they never show their faces.}
{344}{}{You don't like them, do you?}
{345}{}{We don't like the fact that they hide. We value truthfulness and being straight-forward. If you want to rob someone, look them in the eyes.}
{346}{}{I see. I will relay your words to Aaron.}

{350}{}{They say you killed Gonzalez. What the hell happened between you? Did it really have to come to that?}
{1350}{}{They say you killed Gonzalez. I know the guy had problems with women, but why the hell did it have to come to that?}
{351}{}{People like him have no place in a healthy society.}
{352}{}{He got what you deserved. You will, too.}
{353}{}{No one dares speak to me like that. NO ONE.}
{354}{}{It happens to everyone. Or can you only shout at people?}
{355}{}{Sorry, it's just that the situation with Gonzalez saddened me a little.}
{356}{}{I didn't think people like you would value the lives of others.}
{357}{}{Gonzalez was especially useful to us. He supplied people with chems and medicine. Where will we get those things now, huh?}
{358}{}{It's GOOD that the likes of you don't have a dealer anymore.}
{359}{}{He deserved death.}
{360}{}{If you weren't a woman, I'd publicly hang you on a lamppost in the slums. Get out before I change my mind.}
{361}{}{Fine...}
{362}{}{That's a personal problem.}
{363}{}{Not anymore. Because of you, an excellent supplier is gone. You won't get away with it.}
{364}{}{You're just a regular bandit...}
{365}{}{We had a bad relationship. But how was I to know that Gonzalez cooperated with you?}
{366}{}{In that case, you owe us. Don't think you'll get away with it.}
{367}{}{Of course. You can trust me.}
{368}{}{I'm sorry. It was a complete accident, really.}
{369}{}{That's not enough. Blood for blood - such is the law of the street. Strip down if you want it to end quickly.}
{370}{}{Don't do it...}
{371}{}{He got what he deserved. But now it's too late to change anything. Perhaps I could make amends?}
{372}{}{You owe us. Bring us 10 stimpaks, and that MAY earn my forgiveness.}
{373}{}{Okay.}
{374}{}{Don't get brazen. You weren't involved with the situation in any way.}
{375}{}{Here are your 10 stimpaks. That covers it?}
{376}{}{Yes. Consider yourself forgiven.}
{377}{}{Great.}
{378}{}{I'll do anything, just don't kill me!}
{379}{}{}

{380}{}{I'm investigating sabotage at the nuclear power plant. Did you do it?}
{381}{}{What are you talking about? You trying my patience?}
{382}{}{Not at all, sir. Just interested.}
{383}{}{You're lying. The sewers here lead directly to the power plant.}
{384}{}{Tell the atomicists that my gang wants nothing to do with them. Now get lost, you piece of shit.}
{385}{}{Okay...}
{386}{}{Tell me the truth, Orris. As partner to partner. Are you involved with this?}
{387}{}{After everything I did for you, you can trust me. Are you involved with this?}
{388}{}{We're just surviving. More caps never hurt. Especially such easy ones.}
{389}{}{What do you mean? You had help?}
{390}{}{The cultists, damn them. They had connections with someone in the power planet. With the one who was interested in sabotage. My men just went in the open basement and blew up some pipes. What could be easier than that? But keep in mind - I never told you this.}
{391}{}{Okay, Orris. No problem.}
{392}{}{You already told me everything. Say goodbye to life now, idiot.}
{393}{}{You've said too much today. You're lucky that I'm not your enemy.}