{100}{}{You have a prisoner in front of you.}
{101}{}{You see one of the red cardinals.}
{102}{}{*Ugh*}
{103}{}{...Sons of bitches...}

{110}{}{Hey, help me out. I will not remain in debt.}
{111}{}{Do you know Orris? Tell him I'm in jail.}
{112}{}{The mercenaries won't let you go. Tell Orris I have a case being sewn.}

{115}{}{Did Orris send you? He won't like this story.}
{116}{}{See you at the base. Orris won't like what I'm going to tell him.}
{117}{}{I think someone set us up.}