{100}{}{You see an imprisoned cardinal.}
{101}{}{You see one of the red cardinals.}
{102}{}{*Oof*}
{103}{}{Fucking bastards ...}

{110}{}{Hey buddy, help me get outta here. I won't stay in debt to you for long.}
{111}{}{You know Orris? Tell him I'm jailed.}
{112}{}{The mercs won't let me out. Tell Orris they're framing me.}

{115}{}{Orris sent you? He won't like that story one bit.}
{116}{}{See ya at the base. Orris won't like what I have to tell him.}
{117}{}{Looks like we were set up by someone.}