{100}{}{You see a cardinal.}
{101}{}{You see a bandit with stylish hair and a gang emblem on his back.}

{200}{}{Hey, what are you doing here? Don't you know who owns this region?}
{201}{}{I dunno. Who does?}
{202}{}{You've really never heard of the Red Cardinals? I wonder where you're from.}
{1202}{}{You've really never heard of the Red Cardinals? I wonder where you're from.}
{203}{}{From far away.}
{204}{}{Uh-uh. Got it. Go back if you value your life. I'm just warning you now.}
{205}{}{Okay.}
{206}{}{I'm going to go forward still.}
{207}{}{Whatever you say. But Orris and the others won't like that one bit. Or do you need Orris? He's there, but you better have a reason to meet him.}
{208}{}{I'll figure it out. Bye.}
{209}{}{Nonsense. The land belongs to everyone. Nobody can own it.}
{210}{}{What you've just said is the most idiotic thing I have ever heard. Get lost.}
{211}{}{It would be better for you if you left.}
{212}{}{I'm doing that already.}
{213}{}{Hi. How's life?}

{214}{}{Are you aware that someone leaked what you're doing to the Fire-worshippers?}
{215}{}{What? There's a cultist agent among us? It can't be. I have no idea who that could be.}
{216}{}{If I find out you did it, you'll be in big trouble.}
{217}{}{Don't worry, I'll find out who did it.}

#Letter quest
{220}{}{One of your guys robbed the courier and took his letters.}
{221}{}{Well?}
{222}{}{Do you know who that was?}
{223}{}{Yeah.}
{224}{}{Umm, and who is he?}
{225}{}{Me.}
{226}{}{Gotcha. Give me the letters.}
{227}{}{Ha-ha, are you telling me what to do? ME? Gimme at least one reason to listen to you. One that doesn't sound worse than bottle caps will do.}
{228}{}{So all of this is just because of caps?}
{229}{}{What do you want for these letters?}
{230}{}{Something that doesn't sound worse than bottle caps, baby. Get what I mean?}
{231}{}{So all of this is just because of caps?}
{232}{}{You think I'm doing this because I'm living a good life? Everyone needs caps. But there are no legal ways to earn them for someone like me. And if the "correct" places won't take me, I'll earn caps any way I can.}
{233}{}{Alright. I'll pay you 30 caps.}
{234}{}{}
{235}{}{Speaking of the "Sonora Express" letters. You still have them?}
{236}{}{They won't go anywhere until I get what I deserve.}
{237}{}{You need caps, right?}
{238}{}{I remember. But I need more time to collect that amount.}
{239}{}{What? Looks like you need caps even more than me.}
{240}{}{I'll collect this sum. Give me some time.}
{241}{}{You know, this is pointless. I'll just kill you and take the letters from your cold dead hands...}
{242}{}{Solid amount. If you have more caps - bring 'em here.}
{243}{}{Yeah, uhh, bye.}
{244}{}{To hell with talking. I'll just kill you and take the letters...}
{245}{}{You know, I don't want to get involved in this. Bye.}
{246}{}{Atomic worm. Your transgressions are worthy of punitive fire.}
{247}{}{Argh. Should have started with that. I don't want problems with your cult - you've already taken over the whole city. Here, take those damned letter.}
{248}{}{May the Holy Fire have mercy upon thee, oh victim of Radiation and Devastation.}
{249}{}{You've crossed one of Don Diego's men. Don't anger my boss.}
{250}{}{(overacting) Ah, my apologies, senor. You should have started with this. Who could have thought that such a famous man would visit this place. (gives the letters) Tell your boss I said hi. Adi-os.}
{1250}{}{(overacting) Ah, my apologies, senora. You should have started with this. Who could have thought that such a famous woman would visit this place. (gives the letters) Tell your boss I said hi. Adi-os.}
{251}{}{Know your place, cardinal. There are forces more powerful than your gang in this city.}
{252}{}{Orris warned me about your obstinance. You want to get kicked out of the gang? I'll arrange that.}
{253}{}{You're too cruel even for our gang. Take those letters and leave me alone. I'm bored of them anyways.}
{1253}{}{You're too cruel even for our gang. Take those letters and leave me alone. I'm bored of them anyways.}
{254}{}{Uh-uh.}
{255}{}{I'm also earning caps "any way I can". You know what that way is? Angelo at the arena will tell you.}
{256}{}{Oh, yeah. You're one of those stupid jocks the arena couldn't break. My respect. Maybe you could show me a few of your tricks once?}
{257}{}{I'll think about it. And now I better bring the letters back to the office.}