{100}{}{This is Murphy.}
{101}{}{You see one of the red cardinals.}
{102}{}{I could use your armor.}
{103}{}{Ratting? Come here, we have a conversation.}
{104}{}{Stay away from me, little rat.}
{1104}{}{Stay away from me, rat.}
{105}{}{Glad to see you.}
{106}{}{Murphy is waiting for you in the arena.}

{200}{}{Hey, rat. Be careful. I don't want to get dirty about you.}
{201}{}{Come on, Murphy. We're going to do a lot of things together.}
{202}{}{Don't count on it. Unlike Orris, I'm not that trusting.}
{203}{}{Yeah. Bye, Murphy.}
{204}{}{Mutually. You should wash up, slug.}
{205}{}{As long as Orris needs you. But just give me a chance and you'll be lying at my feet. Figure it out.}
{206}{}{Yeah. Bye, Murphy.}
{207}{}{You won't have to.}
{208}{}{Yes. Know your place.}
{209}{}{Bye, Murphy.}

{210}{}{What do you need?}
{1210}{}{What do you need, bitch?}
{211}{}{Whoa, take it easy, I'm already leaving.}
{212}{}{What do I need?}
{213}{}{Nothing. Bye.}
{214}{}{Hi. What's up? Nobody bothers you from the locals?}
{215}{}{Everything is just fine. Bye.}
{216}{}{Good to see you.}
{217}{}{Bye.}

{220}{}{They say you've been betrayed. Who do you think it could be?}
{221}{}{You're delusional. We can't stand the spirit of fire worshippers. None of us can even get close to the cathedral. They consider us criminals there.}
{222}{}{Sounds quite convincing.}
{223}{}{I will prove that there is a traitor among you.}
{224}{}{I know who you are, Murphy. There's a file on you in the Cathedral. Do you want to discuss it?}
{225}{}{Damn it, what are you talking about? What the hell kind of dossier? I have nothing to do with sectarians. Is it clear?}
{226}{}{Of course, of course. But if you want to discuss it, come to the arena tonight. Let's talk quietly.}
{227}{}{Well, if you think about it, not one Murphy in the whole city. Okay, forget it.}

{230}{}{I've told you everything. Think carefully about your decision.}
{231}{}{OK.}
{232}{}{So what the hell does that mean? Were you sent from the Cathedral?}
{233}{}{I know you're a Follower agent. Must have been hard to ingratiate yourself with Orris?}
{234}{}{Aaron needs agents all over the city. This is my mission. Do you think it was easy? I'm taking a big risk already dating you. By the way, who are you?}
{235}{}{You could say I'm playing my game.}
{236}{}{The answer is not credible. At least it means we can come to an agreement. The thing is, I want to take Orris' place and reform the gang for the good of the church. If these guys only know how to beat their faces, then at least let them beat the right people.}
{237}{}{You have ambitious plans.}
{238}{}{So will you help me? The Church of Fire will remember your deeds. I can't depose Orris on my own without consequences.}
{239}{}{You're a traitor. And I don't believe traitors.}
{240}{}{It's worse for you. Don't get in my way.}
{241}{}{Well, well.}
{242}{}{Orris and his gang must be stopped. But how to do it?}
{243}{}{I've been watching Orris for a long time. It will be difficult to shoot him unnoticed, because he is constantly in the spotlight. Think about how you can do it quietly, without making a fuss. Maybe a gunsmith or a pusher has something suitable?}
{244}{}{I'll think about it.}
{245}{}{Orris is dead, I know. Thanks to you, the city will become calmer, and the cause of the Sacred Fire will shine again over the ruins.}
{246}{}{It had to be done.}
{247}{}{I will tell you about your feat in the Cathedral to avoid misunderstandings in the future. Goodbye, friend.}
{1247}{}{I will tell you about your feat in the Cathedral to avoid misunderstandings in the future. Goodbye, sister.}
{248}{}{Goodbye, Murphy.}
{249}{}{And although the cathedral is destroyed, thanks to you there is hope. Perhaps all is not lost yet.}

{250}{}{What are you doing, Murphy?}
{251}{}{Everything that Orris's right hand should be doing. He trusts me with the most difficult problems.}
{252}{}{So you're Orris' deputy? Well settled.}
{253}{}{How did you join the gang?}
{254}{}{They don't keep Belarusians here. I was cleaning up extra people for Orris until he saw my real potential.}
{255}{}{You're a dangerous guy. I need to be careful with you.}
{256}{}{Why is your gang outlawed? They say the fire worshippers are pinching you.}
{257}{}{Damn sectarians, I can't stand them. They tell us what is right and what is wrong. Why on earth? There is only one law on the streets - whoever is stronger is right. We proved it with our deeds. Only we have the right to manage this territory.}
{258}{}{Sounds reasonable.}
{259}{}{I'm on your side, Murphy. But how do I get to Orris?}

{260}{}{Listen, do you know who committed the sabotage at the power plant?}
{261}{}{Perhaps. Why are you asking?}
{262}{}{I'm doing an investigation commissioned by Theodore.}
{263}{}{I don't like these ghouls. But I don't want to hand over their enemies either.}
{264}{}{Then forget it. I'll try to ask someone else.}
{265}{}{Come on, tell me. You can trust me.}
{266}{}{Not you.}
{267}{}{Sorry you don't trust me.}
{268}{}{You have nothing to fear. Even if you're involved, I won't turn you in.}
{269}{}{Fear? For me? Ha! To be honest, I'm involved in this shit myself. Someone from the Cathedral asked for a diversion in order to persuade the ghouls to cooperate, because they themselves will not be able to fix anything. It turned out to be easy, because one of the undead himself was eager to get used to the fire worshippers.}
{270}{}{Wow, that's a story! Now I'll know who's the main dude here. Bye, Murphy.}
{271}{}{Why would you hide something? You're a cool dude, come on, tell me.}
{272}{}{Are you afraid of something? And I thought the Cardinals were cool guys...}