{100}{}{You see a cardinal.}
{101}{}{You see a bandit with a stylish hairstyle and a gang emblem on his back.}

{200}{}{Hey, what are you doing here? Don't you know whose neighborhood this is?}
{201}{}{I don't know. And whose?}
{202}{}{Haven't you ever heard of the Red Cardinals? I wonder where you came from?}
{1202}{}{Haven't you ever heard of the Red Cardinals? I wonder where you came from?}
{203}{}{From afar.}
{204}{}{Yeah. I see. Turn around if life is precious. So far I'm just warning.}
{205}{}{OK.}
{206}{}{I'll still pass.}
{207}{}{As you wish. But Orris and the others won't like it. Or do you need Orris? He's in, but you'd better have a reason to meet him.}
{208}{}{I'll figure it out. Happily.}
{209}{}{This is nonsense. The land is shared and cannot belong to anyone.}
{210}{}{This is the most nonsense I've ever heard. Get lost.}
{211}{}{It's better for you if you leave here.}
{212}{}{I'm already leaving.}
{213}{}{Hi. How are you?}

{214}{}{Are you aware that someone leaked your business to the fire worshippers?}
{215}{}{What? Is there a sectarian agent among us? Yes, it can't be. I can't even imagine who it could be.}
{216}{}{If it turns out that you did it, you'll be in big trouble.}
{217}{}{Don't worry, I'll find out who did it.}

#Quest for letters
{220}{}{One of your guys robbed the courier and took the letters from him.}
{221}{}{So?}
{222}{}{Do you know who?}
{223}{}{Yes.}
{224}{}{Um, and who?}
{225}{}{It was me.}
{226}{}{So you're on my hook. Give me the letters.}
{227}{}{Haha, are you telling me? FOR ME? Find at least one reason to listen to you. The one that sounds no worse than bottle caps will do.}
{228}{}{So it's all corny because of the caps?}
{229}{}{What do you want for these letters?}
{230}{}{Something that sounds as good as bottle caps, baby. Do you understand what I'm talking about?}
{231}{}{So it's all corny because of the caps?}
{232}{}{Do you think I'm doing this for the good life? Everyone needs caps. But there is no legal work for people like me in the city. And if they don't take me to the "right" places, I will earn as I can.}
{233}{}{Okay. I'll pay 30 caps.}
{234}{}{}
{235}{}{About the Sonora Express letters. Do you still have them?}
{236}{}{They're not going anywhere until I get what I'm owed.}
{237}{}{You need caps, don't you?}
{238}{}{I remember. But I need more time to collect the required amount.}
{239}{}{What is it? It looks like you need caps even more than I do.}
{240}{}{I'll collect the necessary amount. Give me some time.}
{241}{}{You know, it doesn't make sense. I'll just kill you and take the letters...}
{242}{}{Not bad. There will be more caps - bring them in.}
{243}{}{Yes, uh, bye.}
{244}{}{To hell with negotiations. I'll just kill you and take the letters...}
{245}{}{You know, I don't want to get involved in this problem anymore. Bye.}
{246}{}{Atomic worm. Your actions are worthy of a punitive bonfire.}
{247}{}{Argh. I should have started with that right away. I don't want any problems with your sect. You've already taken over the whole city. Here, take these damn letters.}
{248}{}{May the Sacred Fire have mercy on you, O victim of Radiation and Devastation.}
{249}{}{You crossed one of Don Diego's men. Don't piss off my boss.}
{250}{}{(replaying) Ah, I'm sorry, señor. I should have started with that right away. Who would have thought that such a famous person would visit our hole? (gives letters) Give a salute to your boss. Adyo-os.}
{1250}{}{(replaying) Ah, I'm sorry, señora. I should have started with that right away. Who would have thought that such a famous person would visit our hole. (gives letters) Give a salute to your boss. Adyo-os.}
{251}{}{Know your place, Cardinal. There are more serious forces in the city than your gang.}
{252}{}{Orris warned me about your obstinacy. Do you want to get out of the gang? I'll arrange it.}
{253}{}{You're too violent even for our gang. Take the letters and leave me. They bored me anyway.}
{1253}{}{You're too violent even for our gang. Take the letters and leave me. They bored me anyway.}
{254}{}{Yeah.}
{255}{}{I also earn "as I can". You know how? Angelo will tell you in the ring.}
{256}{}{Well yes. You're one of those dumb jocks that the ring couldn't break. I respect you. Will you show me a couple of tricks sometime?}
{257}{}{I'll think about it. And now I need to take the letters to the office.}