{100}{}{You see a cardinal.}
{101}{}{You see a bandit with stylish hair and a gang emblem on his back.}
{102}{}{If I had an armor like yours, the whole city would bow down to me.}

{110}{}{Looking for trouble?}
{111}{}{Who are you, anyway?}
{112}{}{Our territory - our rules.}
{113}{}{Everyone in that region is controlled by us.}
{114}{}{Careful with your words.}
{115}{}{Shut up if you don't want to get one in the nose.}
{116}{}{Do you even know who we are?}
{117}{}{Got an opinion? Shove it up your ass.}
{118}{}{What are you doing?}
{119}{}{Looking for something in our region?}

{120}{}{Damn, we shouldn't have doubted you.}
{121}{}{You're cooler than you look.}
{122}{}{Hey, how's life?}
{123}{}{Want a drink?}
{124}{}{Want to do a "procedure"? I say "hell yeah".}
{125}{}{Don't worry, I'm on your side.}
{126}{}{Everyone's a friend here. Make yourself comfortable.}
{127}{}{}
{128}{}{}
{129}{}{}