{100}{}{You see Orris.}
{101}{}{You see the leader of the Red Cardinals.}
{102}{}{I need this armor. Give it back.}
{103}{}{...Phew, this stuff fries like hell...}
{104}{}{I don't do business with sectarians anymore.}

#Acquaintance
{200}{}{[Murphy] Op-pa, we've got a rat here. Do you know where you are, asshole? Hey, Orris, let me hang out with him...}
{1200}{}{[Murphy] Op-pa, we've got a rat here. Do you know where you are, you fool? Hey, Orris, let me have some fun with her...}
{201}{}{[Next]}
{202}{}{[Orris] Wait, Murphy. Don't be so bloodthirsty when it comes to our guests. You. What do you need?}
{203}{}{All I need is for scum like you to disappear from the face of the earth.}
{204}{}{If you're looking for problems, you're in the right place.}
{205}{}{Great. Who is the first?}
{206}{}{They say you are a force to be reckoned with by the local authorities. I want to be with you.}
{207}{}{[Murphy] We have enough of our people over our throats. Do you think we need you? Get out, asshole.}
{1207}{}{[Murphy] We have enough of our people over our throats. Do you think we need you? Run, you fool, while you can.}
{208}{}{[Next]}
{209}{}{Murphy, my friend, calm down. I need a contact. Forgot? So, you. Come here.}
{210}{}{Well, no. I have nothing to do with bandits.}
{211}{}{We don't need idiots. Guys, finish with him.}
{1211}{}{We don't need idiots. Guys, finish with her.}
{212}{}{No. No need. Please...}
{213}{}{You were beaten and kicked out into the street, and your pockets were turned inside out.}
{214}{}{You were raped and kicked out into the street, and your pockets were turned inside out.}
{215}{}{Let's see what you can do. Who's the first?}
{216}{}{What do you want from me?}
{217}{}{To be honest, I'm here by accident. Let me go. Please.}
{218}{}{[Murphy] I'm telling you - another half-wit from the street. Let's empty our pockets and be done with it.}
{1218}{}{[Murphy] I'm telling you - the woman is not all right with her head. Turn out the pockets, polish, and be done with it.}
{219}{}{[Next]}
{220}{}{No, Murphy. I need a contact. Forgot? So. You. Come here.}
{221}{}{What do you want from me?}
{222}{}{Well, no. I don't negotiate with bandits.}
{223}{}{You again? What do you need?}
{224}{}{Hey, champ, good to see you. It was a great fight. It's a pity that now you don't perform in the ring.}
{1224}{}{Hey, champ, good to see you. It was a great fight. It's a pity that now you don't perform in the ring.}
{225}{}{That's for sure. Besides, you can no longer count on fees.}
{226}{}{Need caps? I just need strong guys... Damn it, Murphy, shut up! I know who I can trust and who I can't. So... listen, there's a job just for you.}
{227}{}{I'm listening.}
{228}{}{Well, no. I don't want to mess with bandits.}
{229}{}{Nothing special. A friend of mine was supposed to meet with a courier, but he disappeared. Go to the caravan park and go down to the local collector. This is their meeting place. Find out what happened to them and come back to me. If you do everything right, you will get a reward.}

#The first questa
{230}{}{Nothing special. I just need to find my old friend. You see, he got lost somewhere in a big city.}
{231}{}{I'm not going to get involved in muddy affairs.}
{232}{}{You have a lot of people. Why me?}
{233}{}{They know my guys by sight. They should not shine once again in the city center.}
{234}{}{OK, I'll do it.}
{235}{}{You see, Murphy. You can negotiate with everyone. Although I understand you...}
{236}{}{[Next]}
{237}{}{Now listen carefully. Go to the caravan park and go down to the local collector. My man was supposed to meet the courier there. Find out what happened to them and come back to me. If you do everything right, you will get a reward.}
{238}{}{Okay, persuaded.}
{239}{}{I'm on my way.}
{240}{}{If I do this, will you pay me?}
{241}{}{I promise.}
{242}{}{Remind me where the meeting was supposed to take place?}
{243}{}{Go to the caravan park and go down to the local collector. My man was supposed to meet the courier there. Find out what happened to them and come back to me.}
{244}{}{Clear. I'll go check it out.}
{245}{}{It's better for my guys not to shine once again in the city center. They don't have as "good" a reputation as you do.}
{246}{}{I've had enough! I will PERSONALLY kill you.}
{247}{}{Your nerves are a little weak...}
{248}{}{Come on, man, calm down...}

{250}{}{Did you find the ones I was talking about?}
{1250}{}{Did you find the ones I was talking about?}
{251}{}{No. Not yet.}
{252}{}{Your friend and contact were attacked by Bruce's mercenaries.}
{253}{}{What the... Hey, Murphy, did you hear that? It's bad. He knew too much. If they put pressure on him, they will find out all our plans. We need to act quickly.}
{254}{}{What happened?}
{255}{}{Look, you're not from around here, are you? I'll tell you something. In this city, the strongest survive. It can't be any other way. And we are still alive only because we do not allow any trash to sharpen knives against us. If you want to gain a foothold in Phoenix, stay close to the right people.}
{256}{}{So... to you.}
{257}{}{And I want to offer you a contract. I don't care how, but I need to get my man out of jail or shut him up for good. Do you see what I'm getting at? It's risky for us to show up at the center, but not for you. Think about how to do it, and then I'll pay 200 caps.}
{258}{}{I'll see what I can do.}
{259}{}{This is too difficult a task. I can't do it.}

{260}{}{What news?}
{261}{}{None yet. Your man is still in jail.}
{262}{}{Damn it, if he cracks during the interrogation, you will also fall under the distribution. Understand this.}
{263}{}{The hint is clear...}
{264}{}{You don't have to threaten me.}
{265}{}{I'm sick of it. Not only am I not going to work for you. But I'll also hand over your whole damn gang to the mercenaries. Come on, you son of a bitch.}
{266}{}{Your buddy is dead. It wasn't easy, but I succeeded.}
{267}{}{Your buddy's out there. It wasn't easy, but I succeeded.}
{268}{}{And you're not a miss guy. I was very lucky that you were there. Here are the caps for the job and the stimpack. Have fun while I'm dealing with this shit.}
{1268}{}{And you're a good girl. I was very lucky that you were there. Here are the caps for the job and the stimpack. Have fun while I deal with this shit.}
{269}{}{Okay, I'll be back later.}

{270}{}{It seems your people have been framed. What are you going to do now?}
{271}{}{This could only be done by sectarians from the Temple of Fire. It looks like they decided to get rid of us after they used us for their purposes. But after the explosion of the Cathedral, they are not up to us.}
{272}{}{So you're free now?}
{273}{}{It's time to occupy vacant areas before someone else does. By the way, I don't need you anymore. But I don't forget those who proved useful. Talk to the pusher in the slums. We have a special relationship with him.}
{1273}{}{It's time to occupy vacant areas before someone else does. By the way, I don't need you anymore. But I don't forget those who proved useful. Talk to the pusher in the slums. We have a special relationship with him.}
{274}{}{Great, I'll keep that in mind. Bye, Orris.}
{275}{}{This could only be done by sectarians from the Temple of Fire. It looks like they decided to get rid of us after they used us for their purposes. But I don't understand how they found out about our secret deal.}
{276}{}{Could someone have told them?}
{277}{}{One of our own? It's hard to believe. We are just bandits for the sectarians...}
{278}{}{[Next]}
{279}{}{Listen, I need a man in the Cathedral. If you find out who turned us in, I'll pay good caps. Agreed?}
{280}{}{Accepted. I'll take out the rats in your gang.}
{281}{}{Infiltrate the Cathedral? You're crazy. I can't do it.}
{282}{}{Did you find out who set us up?}
{1282}{}{Did you find out who set us up?}
{283}{}{It was Murphy. He's Aaron's agent.}
{284}{}{Murphy? I couldn't even think, because he's the best of the best... However, if you think about it... He knew more about my plans than anyone else.}
{285}{}{It's definitely Murphy. I managed to listen to his dialogue on the radio with the Cathedral's signalman. Aaron wanted to control your gang by putting his own man in charge.}
{286}{}{Aaron's plans won't come true anymore. I'll get rid of Murphy. And you should be rewarded for your efforts. I don't want to lose such a useful agent. Here are the bottlecaps. Also, talk to the pusher in the slums, I have a special agreement with him.}
{287}{}{Bye, Orris.}
{288}{}{Murphy won't compete with you anymore. Bye, Orris.}
{289}{}{I think your people were framed by sectarians. But after the explosion of the cathedral, we will not know the truth.}
{290}{}{What's the story with the fire worshippers?}
{291}{}{These sectarians consider us bandits and do not recognize our authority over the slums. But when necessary, they are ready to negotiate.}
{292}{}{You said you were running an errand for them.}
{293}{}{They paid for sabotage at the nuclear plant. We blew up the cooling system of the station, but after that, we were not needed by the sectarians. They threw us.}
{294}{}{Clear.}
{295}{}{But how do I do it?}
{296}{}{I don't know myself. But the monks probably have everything written down in some dossiers.}
{297}{}{I keep thinking - how do I find a rat in a cathedral?}

#Dialogue outside the questa
{300}{}{Tell me what you need.}
{301}{}{How are you, tramp?}
{302}{}{I wanted to see you. I'm leaving now.}

{310}{}{Did your people take the letters from the courier?}
{311}{}{I have no idea what you're talking about. Ask my people. If someone confesses, then we'll see.}
{312}{}{I will do so. Bye.}
{313}{}{I'll find the culprit, don't doubt it.}

{320}{}{They say you killed my guys in the slums. And after that, you dare to come to me. I will only give you one attempt to persuade me to let you live.}
{1320}{}{They say you killed my guys in the slums. And after that, you dare to come to me. I will give you only one attempt to persuade me to let you live.}
{321}{}{It's their fault.}
{322}{}{My neighborhood is my rules. People need to see that my strength has to be reckoned with. Guys, deal with this garbage...}
{1322}{}{My neighborhood is my rules. People need to see that my strength has to be reckoned with. Guys, deal with this stuff...}
{323}{}{Oh, not in the face...}
{324}{}{Go to hell with your whole gang.}
{325}{}{It's their fault. Consider this our showdown with them.}
{326}{}{Yes. Your. Personal. And don't you dare tell anyone the opposite? People should see that my strength must be reckoned with.}
{327}{}{You have nothing to do with it.}
{328}{}{You've confused me with someone else. It's not me.}
{1328}{}{You've confused me with someone else. It wasn't me.}
{329}{}{You're lying. Guys, deal with this garbage...}
{330}{}{Oh no, not by the face...}
{331}{}{Go to hell.}
{332}{}{I must have been confused with someone else. Well, look at me, how can I beat your guys?}
{333}{}{The case is murky. Until I let you go. But if you are lying, you will be severely punished. People need to see that my strength has to be reckoned with.}
{334}{}{Of course...}
{335}{}{After what happened, I'm not afraid of you. You and your gang deserve nothing but death.}

{340}{}{Did you attack the monks?}
{341}{}{No, not us. I give you my word.}
{342}{}{If not you, then who?}
{343}{}{I'll tell you what I've heard about another gang. These guys want to overthrow Aaron and turn the people against the Church of Fire. But they are too cunning to show faces.}
{344}{}{You don't get along with them, do you?}
{345}{}{I don't like them hiding. We love straightforwardness. If you want to rob a passerby, look into his eyes.}
{346}{}{Clear. I'll pass on your words to Aaron.}

{350}{}{They say you killed Gonzalez. What the hell didn't you share with him? Was it necessary to bring it to this?}
{1350}{}{They say you killed Gonzalez. I know he had problems with women, but what the hell was it necessary to bring to this?}
{351}{}{There is no place for people like him in a healthy society.}
{352}{}{He got what he deserved. And you'll get it too.}
{353}{}{No one dares to talk to me like that. NOBODY.}
{354}{}{It's the first time for everyone. Or can you just scream?}
{355}{}{Sorry, it's just that the Gonzalez story upset me.}
{356}{}{It seemed to me that bandits like you don't appreciate someone else's life.}
{357}{}{Gonzalez was especially helpful to us. He supplied chemicals and medicines. And where are we going to get them now, eh?}
{358}{}{You know, it's GOOD that people like you don't have a dealer anymore.}
{359}{}{He deserved to die.}
{360}{}{If you weren't a woman, I'd publicly hang you from a lamppost in the slums. Disappear before I change my mind.}
{361}{}{Yes...}
{362}{}{This is our problem with him.}
{363}{}{Not anymore. Because of you, we lost a great supplier. You won't get away with it.}
{364}{}{You're a typical bandit...}
{365}{}{This is our relationship with him. How was I supposed to know that Gonzalez was cooperating with you?}
{366}{}{In that case, you owe me. Don't think about getting out of it so easily.}
{367}{}{Sure. You can count on me.}
{368}{}{Please forgive me, it happened completely by accident.}
{369}{}{That's not enough. Blood for blood is the law of the streets. Take off your clothes if you want it to end quickly.}
{370}{}{No, don't...}
{371}{}{He got what he deserved. But it's too late to deal with it. Can I make it up to you?}
{372}{}{You owe me. Bring ten stimulants, then MAYBE I'll forgive you.}
{373}{}{OK.}
{374}{}{Don't be impudent. You have nothing to do with it at all.}
{375}{}{Here are 10 stimulants. Are we even now?}
{376}{}{Yes. Consider us even.}
{377}{}{Wonderful.}
{378}{}{I'll do anything, just don't kill me!}
{379}{}{}

{380}{}{I'm investigating a sabotage at a nuclear power plant. Did you do that?}
{381}{}{What are you talking about? Do you want to test my patience?}
{382}{}{Not at all, sir. Just wondering.}
{383}{}{You're lying. The collector goes from you directly to the nuclear power plant.}
{384}{}{Tell the atomists that my gang wants nothing to do with them. Now get lost, you piece of shit.}
{385}{}{Okay...}
{386}{}{Tell me the truth, Orris. As a partner to a partner. Are you involved in this?}
{387}{}{After our common affairs, you can trust me. Are you involved in this?}
{388}{}{We're just surviving. Caps are never superfluous. Especially so light.}
{389}{}{What do you mean? Did they help you?}
{390}{}{Sectarians, fuck them. They had connections with someone at the station. With someone interested in sabotage. My guys just went into the open basement and blew up the pipes. What could be simpler? But keep in mind - I didn't tell you that.}
{391}{}{Okay, Orris. No problem.}
{392}{}{You've already said it all. Now say goodbye to life, you fool.}
{393}{}{You're too talkative today. Be glad I'm not your enemy.}