{100}{}{You see the messenger.}
{101}{}{You see a man with a knife in his side. He won't last long.}
{102}{}{You see a wounded man. He barely stumbles, clutching his wounded side.}
{103}{}{...Bruce's mercs... they attacked...}
{104}{}{I lost all hope. Thought I was gonna die. Thanks, doc.}

{110}{}{...I'm wounded...}
{111}{}{...Ug-h... it hurts so much...}
{112}{}{...H-help...}
{113}{}{...I'll tell you everything, just help me...}
{114}{}{...Th-ey attacked... ambushed us...}
{115}{}{Help me already!}
{116}{}{Fine... fine... I'll tell you...}
{117}{}{...Bruce's mercs...}
{118}{}{...They took... the cardinal... and...}
{119}{}{...Ar-rgh...}
{120}{}{Sorry, buddy, but help isn't arriving in time.}

{200}{}{Thanks, doc. I'll forever be grateful to you.}
{201}{}{Who attacked you?}
{202}{}{Mercs from Bruce's guild. I think they were waiting for us. They took the man I was going to meet, and stabbed me. Didn't finish me, probably thought I was a dead man already.}
{203}{}{How did you get involved with this story in the first place?}
{204}{}{Listen, I'm just another unemployed person. I was asked to carry a note and give it to someone. That's all. I don't know anything else.}
{205}{}{Easy caps have hard consequences. And now it's time for me to go to the mercenary guild.}
{206}{}{I'm very sorry, pal. You just got unlucky. Bye.}
{207}{}{Bye.}