{100}{}{Here is a cardinal.}
{101}{}{You see a bandit with a stylish hairstyle and a gang emblem on his back.}
{102}{}{I wish I had armor like yours, the whole city is lying at my feet.}

{110}{}{Looking for trouble?}
{111}{}{Who are you anyway?}
{112}{}{Our territory is our rules.}
{113}{}{Everyone in the area lies below us.}
{114}{}{Be careful with the words.}
{115}{}{Shut up if you don't want to get in the snout.}
{116}{}{Do you even know who we are?}
{117}{}{Have an opinion? Shove it up your ass.}
{118}{}{What are you selling there?}
{119}{}{Are you looking for something in our neighborhood?}

{120}{}{Damn, we shouldn't have doubted you.}
{121}{}{And you're cooler than you look.}
{122}{}{Hey, how are you?}
{123}{}{Do you want a beer?}
{124}{}{Shall we do some business? I'm only "for".}
{125}{}{If anything, I'm with you.}
{126}{}{Everyone's here. Make yourself comfortable.}
{127}{}{}
{128}{}{}
{129}{}{}