{100}{}{You have a contact in front of you.}
{101}{}{You see a man with a knife in his side. He won't last long.}
{102}{}{You see a wounded man. He barely hobbles, clutching his wounded side.}
{103}{}{...Bruce's mercenaries... they attacked...}
{104}{}{I was already desperate, I thought I was going to die. Thanks, Doc.}

{110}{}{...I'm hurt...}
{111}{}{...Ah-h... how painful...}
{112}{}{...C-save...}
{113}{}{...I'll tell you everything, just help...}
{114}{}{...The Ooni attacked... they were waiting for us...}
{115}{}{Help me!}
{116}{}{Okay... okay... I'll say...}
{117}{}{...They were Bruce's mercenaries...}
{118}{}{...They grabbed it... cardinal... and...}
{119}{}{...Ar-rh...}
{120}{}{Sorry, buddy, but there won't be time for help.}

{200}{}{Thanks, Doc. I am eternally indebted to you.}
{201}{}{Who attacked you?}
{202}{}{They were mercenaries from Bruce's guild. I think they were waiting for us. They grabbed the man I was supposed to meet, and they just stabbed me. They didn't finish me off, apparently they decided that I was already a dead man.}
{203}{}{How did you get into this mess in the first place?}
{204}{}{Listen, I'm just an unemployed resident of the city. They asked me to take the note and give it to them. That's all. I don't know anything else.}
{205}{}{There are no easy bottlecaps. Remember that. And now it's time for me to visit the mercenary guild.}
{206}{}{I'm really sorry, buddy. You're just unlucky. Bye.}
{207}{}{Bye.}