{100}{}{Here is a fighter.}
{101}{}{You see an arena fighter. It looks like he overdid it in training.}
{102}{}{You see an arena fighter. He looks cheerful.}
{103}{}{Thanks, Doc, that's much better}

{110}{}{*Groan*}
{111}{}{It hurts}
{112}{}{Uv...}
{113}{}{*Cough-cough*}
{114}{}{Um-m-m...}
{115}{}{Filth...}
{116}{}{Not another step into the ring.}
{117}{}{Where is this damn pusher?}
{118}{}{I need anesthesia.}
{119}{}{It's getting worse every hour.}

{150}{}{Broken in the ring.}
{151}{}{As you can see, I'm dying here.}
{152}{}{The last fight turned out to be difficult.}
{153}{}{I think I got a concussion.}
{154}{}{I need a doctor...}
{155}{}{Do you have painkillers?}
{156}{}{Pusher, bitch, can't get a stimpack.}
{157}{}{These fights are exhausting.}
{158}{}{*Moans in response, clutching his head*}
{159}{}{Um-m-m... My head hurts!}

{170}{}{Thank you for saving me.}
{171}{}{If it wasn't for you, I could have died.}
{172}{}{Who taught you first aid?}
{173}{}{What luck that you're around.}
{174}{}{Many of my friends could have survived if you were around.}
{175}{}{I hope you're not going to go to the ring?}
{176}{}{You're going to patch me up after the next fight, aren't you?}
{177}{}{Another fight? Why not!}
{178}{}{Your help came in very handy.}
{179}{}{Now I'm going to get back in the ring.}