{100}{}{This is your opponent.}
{101}{}{This is a Savage.}
{102}{}{This is Canelo.}
{103}{}{This is Big Mario.}
{104}{}{It's a Super Mutant.}

{105}{}{You see your opponent. He seems to hint that he put it on you.}
{106}{}{You see your opponent. He seems to be hinting that you are not his equal.}
{107}{}{You see your opponent. He only sees you as a target.}
{108}{}{You see your opponent. And in his eyes - unspeakable rage.}
{109}{}{You see your opponent. But you'd better not see him.}

{110}{}{DIE!}