{100}{}{You see a fan.}
{101}{}{You see a man waiting listlessly for a new fight.}
{102}{}{You see a wild-looking man. He shouts furiously at the top of his voice.}

#Retaliatory remarks
{110}{}{Waiting for a new fight}
{111}{}{How do you like the last fight?}
{112}{}{Iron Mike no longer trains fighters.}
{113}{}{Not a single good fight after Iron Mike.}
{114}{}{Boring. When is the new fight?}
{115}{}{I'm putting all my caps on this fighter.}
{116}{}{Are you betting or participating?}
{117}{}{This bet will be the last one.}
{118}{}{}
{119}{}{}

{150}{}{Hello, champion.}
{151}{}{How are you, champ?}
{152}{}{Are you talking to me?}
{153}{}{Oh my God, the champion is talking to me!}
{154}{}{Why don't you fight anymore?}
{155}{}{Hit me! I will tell the children.}
{156}{}{Hey, let me touch your biceps!}
{157}{}{Thanks to you, I'm in a good win.}
{158}{}{}
{159}{}{}

{160}{}{Hi. }
{161}{}{Enjoying the victory?}
{162}{}{Hey, hey, take it easy!}
{163}{}{Cool, champ, but I bet on your opponent. So now I'm bankrupt...}
{164}{}{Why don't you fight anymore?}
{165}{}{Just try to hit me.}
{166}{}{Aren't your biceps tight?}
{167}{}{My bet went down because of you. Well, save for.}
{168}{}{}
{169}{}{}

#Random phrases outside of combat
{170}{}{When is the new fight?}
{171}{}{Boring.}
{172}{}{The ring is missing something.}
{173}{}{   }
{174}{}{  }
{175}{}{   }
{176}{}{   }
{177}{}{   }
{178}{}{   }
{179}{}{   }

#Random phrases during combat
{180}{}{I'm betting on this fighter.}
{181}{}{Go ahead!}
{182}{}{Finish him off!}
{183}{}{I adore you!}
{184}{}{On the right! Right, come in!}
{185}{}{Defend yourself!}
{186}{}{You won't see a more boring fight.}
{187}{}{I will never forget this fight.}
{188}{}{I can't stand this heat.}
{189}{}{*Whistles*}
{190}{}{*Screams*}
{191}{}{Hit him! Hit!}
{192}{}{Come on!}
{193}{}{Don't slow down!}

{194}{}{!}
{195}{}{Forward, }
{196}{}{You're the best, }
{197}{}{Finish him off, }
{198}{}{I'm betting on you, }
{199}{}{Make it, }