{100}{}{Here is Rico.}
{101}{}{You see a huge fellow with a silly expression on his face, but a very impressive look.}

{110}{}{Shlushayu?}
{111}{}{Don't, talk like a dwarf.}
{112}{}{Angelo is in charge here.}
{113}{}{What do you need?}
{114}{}{I hit without a miss.}
{115}{}{I want to eat.}
{116}{}{Keep your hands where I can see them.}
{117}{}{You're looking for it, aren't you?}
{118}{}{Sit. I say SIT DOWN!}
{119}{}{Suck it!}
{120}{}{*Grumbling*}
{121}{}{*Kneads his hands in response*}
{122}{}{You smell like a baby.}
{123}{}{Don't burn me.}
{124}{}{Stop talking.}
{125}{}{It's time for me to go to sleep.}
{126}{}{Do you need a coach?}
{127}{}{Yeah}
{128}{}{The exit is there.}
{129}{}{Don't come near me.}
{130}{}{*Looks at you blankly*}
{131}{}{What do you need?}

{150}{}{(enviously) Otl-personal fight.}
{151}{}{You fight like a mad dog.}
{152}{}{Who taught you how to fight?}
{153}{}{Don't hit me!}
{154}{}{You're cute. I'm weak.}
{155}{}{I'm far away from you}
{156}{}{I won't fight you.}
{157}{}{You're not human. You're a beast.}
{158}{}{I need a coach.}
{159}{}{Finish me off.}
{160}{}{*Grumbling*}
{161}{}{*Smiling with a toothless mouth*}
{162}{}{*Nods stupidly*}

{200}{}{*Crying like a baby*}
{201}{}{Ange-e-e!}
{202}{}{Ange-ate! Ange-ate!}
{203}{}{*Whimper*}
{204}{}{Uh-uh...}
{205}{}{*Groan*}
{206}{}{Don't look! Don't look!}
{207}{}{I'll kill you! I'll kill everyone!}
{208}{}{Bitches! Bitches!}
{209}{}{Angelo was smart, I was stupid.}
{210}{}{Who did this?!}
{211}{}{Show me who did it!}
{212}{}{Who killed my Angelo?}
{213}{}{*Takes a deep breath*}