{100}{}{You see a small trader.}
{101}{}{You see a local merchant. He prepares drinks for the arena audience.}

{110}{}{Well, that's it, the end of my business.}
{111}{}{What kind of idiot would want to kill Angelo?}
{112}{}{Sorry, but the product is no more.}
{113}{}{The arena is no longer working. My business too.}
{114}{}{I'll be lucky if I get out of here alive.}

{200}{}{Need a drink before the match? I sell cheap.}
{201}{}{No, no booze today.}
{202}{}{Hi. I didn't think that after such victories you would want to drink in a place like this.}
{203}{}{Great fight, }
{204}{}{. Keep it up.}

{210}{}{Need a drink before the match? I sell cheap.}
{211}{}{So far.}
{212}{}{Is it possible to place bets in the arena?}
{213}{}{I do not know when the new fight is. Talk to the people downstairs. Do you need a drink or not?}
{214}{}{No, no booze today.}
{215}{}{I'll think about it.}