{100}{}{This is Angelo.}
{101}{}{You see a small boss, not a small business. He examines you carefully.}
{102}{}{There will be no conversation until I see you without armor.}
{103}{}{DIE!}
{104}{}{SEE YOU IN HELL!}
{105}{}{GET READY FOR DEATH!}
{106}{}{AR-RGH!}
{107}{}{DEATH TO HUMANS!}

# Before participating in the battles
{200}{}{ (in front of you is a short man in a children's suit, but with business habits) What do you need? Do you want to bet on a fight or participate?}
{201}{}{Neither one nor the other. I'm just wondering how someone like you can control the ring?}
{202}{}{(pulls back the bristling bodyguard) Stop, Rico! Calm down, brother, it's okay. These savages from the wasteland don't understand how life is in the city. Relax...}
{203}{}{[Next]}
{204}{}{And I'll give you a free tip - watch your filthy tongue. (he pours tequila into a dirty glass, like a born mafioso) You see, BRAINS are valued in the city, not BRAWN. I'm the brain of this neighborhood. I set up a local business and get the biggest jackpot. You better talk to me respectfully, otherwise Rico will make a chop out of you. Do you understand?}
{205}{}{Yes... sir.}
{206}{}{Great. So what do you want?}
{207}{}{I want to bet on the fight.}
{208}{}{I want to get into fights.}
{209}{}{Looks like I'm wasting my time. Goodbye, Mr. Brain.}

{210}{}{I don't care about your Rico. You can't intimidate me.}
{211}{}{Rico, take that bitch outside...}
{212}{}{Just touch it and you're finished.}
{213}{}{Okay, okay, don't push...}
{214}{}{Again? You're starting to get on my nerves.}
{215}{}{I demand compensation for such treatment. Immediately.}
{216}{}{I apologize. Now I see that I am talking to a very respected person.}
{217}{}{Rico, throw this shit out on the street. If he comes in again, you can break his neck.}
{1217}{}{Rico, throw that bitch out on the street. If she comes in again, you can break her neck.}
{218}{}{Don't you have any brains at all? Rico!}
{219}{}{Don't you dare...}

{220}{}{I want to put.}
{221}{}{Well, now is not the right time. We haven't made a list of fights yet, there's not enough new blood.}
{222}{}{What about me? Will I be able to participate?}
{223}{}{Sorry. I'll come by when the season starts.}
{224}{}{And who runs this club?}
{225}{}{I'm the manager. My name is Angelo Rossitto. Anything else?}
{226}{}{You? Come on! It can't be.}
{227}{}{It's all. Happily.}
{228}{}{In this case, I have a suggestion - I want to participate in the battles.}
{229}{}{Can I participate?}
{230}{}{(examines you from head to toe, then gives a signal to the bodyguard) Rico, inspect the goods.}
{1230}{}{Woman and boxing? Where the world is going... However, a good advertising move can come out of this. Rico, inspect the goods.}
{231}{}{Hey, hey, what are you up to?}
{232}{}{Be gentle, honey.}
{233}{}{(Rico examines your muscles and evaluates reflexes, then shakes his head looking at the boss)}
{234}{}{What does this mean?}
{235}{}{It means that shit like you is good for nothing. To begin with, pump up your hands, then we say.}
{236}{}{I doubt that after such a reception I will come back here. Goodbye.}
{237}{}{Then here's my answer: The challenge is accepted.}
{238}{}{(Rico examines your muscles and assesses your reflexes, then nods his head looking at the boss)}
{239}{}{What does it mean?}
{240}{}{You have potential. We will be able to find you an opponent within your strength, but to be honest, I doubt your skills. You should practice before the fight. If you still decide, then come back, we will arrange a fight in the best possible way.}
{241}{}{Great, I'm in.}
{242}{}{You have potential. But this is a risky business. Think about yourself and your kids. And if you *really* want a fight, then come back, we'll arrange a fight in the best possible way.}
{243}{}{Give me time to think.}

{250}{}{So what do you need?}
{251}{}{I wanted to say hello. I'm leaving now. Later.}
{252}{}{Can I bet on the fight?}
{253}{}{I want to fight in the ring. Seriously.}
{254}{}{Call me the manager.}

{260}{}{How are you, champ? The audience misses you. But sorry, it's time to give way to the young.}
{261}{}{It's all good. Bye, Angelo.}
{262}{}{I'm going to get out of here so as not to listen to these excuses.}
{263}{}{How are you, }
{264}{}{? The audience misses you. But I'm sorry, it's time to give way to the young.}

{270}{}{What do you want to know?}
{271}{}{Bye.}
{272}{}{How did you become a ring manager?}
{273}{}{Ask me what you want, }
{274}{}{.}
{275}{}{I see. That's all I was interested in.}

{280}{}{Where can I practice?}
{281}{}{The training hall is near the stairs. But if you need a coach, that's a problem. Iron Mike used to take fighters for training, but now he got drunk and retired.}
{282}{}{Where can I find him?}
{283}{}{He lives in a dorm right across from the arena, just cross the street. But he may not open the door, be more persistent.}
{284}{}{How did you become a ring manager?}
{285}{}{If an experienced fighter became a coach, then how did you become a manager?}
{286}{}{You need to move your brains. I am the brain. Do you understand? Rico- these are my muscles. It's simple.}
{287}{}{I see. If you're so smart, then tell me where you can practice here?}
{288}{}{There's still something missing in your success formula. Getting a foothold in the city is not so easy.}
{289}{}{Consider it ........}
{290}{}{ What happened to Mike?}
{291}{}{I don't know if I can tell you this, but once Mike's students killed his girlfriend during a robbery. At that moment, he was disappointed in people.}

#Participation in battles
{300}{}{(examines and nods in approval) Very well, we just have a couple for you. Are you going to fight?}
{301}{}{Wait. I need to ask something first.}
{302}{}{Sure. Who is my opponent?}
{303}{}{I'm not in shape yet. Give me a little more time.}
{304}{}{A tramp from the wasteland. As gray and unknown as you.}
{305}{}{How much will I earn if I knock him down in the ring?}
{306}{}{Immediately about the caps? Don't count on a quick start, baby. First, show your capabilities. I pay 100 caps for the first fight. In Phoenix, no one will pay you that much for an ordinary fight.}
{307}{}{And the last question - should he die during the battle?}
{308}{}{It depends on your desire and your capabilities. But when someone dies in the ring, it gets the audience excited and increases your fame. So what do you say?}
{309}{}{All this is good, but now I am worried about completely different issues.}
{310}{}{I can enter the ring. When does it start?}
{311}{}{Give me time to prepare.}
{312}{}{Come by 20:00. Yes, one more thing. You need a sonorous nickname if you decide to fight regularly. Something powerful or dangerous. To be remembered and sound cool on the streets. Well? Any ideas?}
{313}{}{[Next]}
{314}{}{[Previous]}
{315}{}{? Not bad. Don't forget about the time. We are waiting for you by 20:00. If you're late, I'll have to put other fighters. So don't let me down, }
{316}{}{OK. I'll be there on time.}
{317}{}{You're too early. Come to 20:00.}
{318}{}{OK.}
{319}{}{And here is our rising star. I was starting to think you didn't have the guts to get in the ring. But it looks like you have a little bit of courage.}
{320}{}{There is more of it than you think. Take me to the ring.}
{321}{}{Wait, wait, I need to go to the bathroom. I'll be back soon.}
{322}{}{I know. I just wanted to chat with you before the start.}
{323}{}{You're just in time. The audience is already warmed up, it's time to put on a show.}
{324}{}{I'm ready to kick ass. Take me to the ring!}
{1324}{}{I'm ready to kick ass. Take me to the ring!}
{325}{}{Give me a little more time to tune in before the fight.}
{326}{}{Big Mario is waiting for you. And not only him, but also real fame... if, of course, you can beat him. So, }
{327}{}{? Are you ready for the decisive battle?}
{328}{}{Today Big Mario Albright will see his defeat. Take me to the ring, Angelo. Behave like a future champion.}
{329}{}{Big Mario will wait a bit. I'll be back soon.}

#- the first fight
{330}{}{Pretty good for a beginner. Even though you've been pretty battered. And yet the potential is visible. You shouldn't stop.}
{331}{}{Pretty good for a beginner. You have good inclinations, they should be developed.}
{332}{}{Really? Wow, that's encouraging.}
{333}{}{I'm not here for show-offs. And for the sake of the bottlecaps.}
{334}{}{Here's your fee, 100 caps. A fair win. If there is a desire, come back, we will organize another fight.}
{335}{}{I am not afraid of a new fight. Prepare an opponent for me.}
{336}{}{You know, Angelo, today the ring showed me something terrible. Death. I don't want to see it anymore. Goodbye.}
{337}{}{There won't be a next time.}
{338}{}{.}

#- the second fight
{340}{}{You're making progress, }
{341}{}{. Very good. Very. I hope you're not going to stop in the middle of the road?}
{342}{}{Oh-very good. The public is starting to like you and, more importantly, ME.}
{343}{}{And my fee?}
{344}{}{Everything is fair with me. Here are your 200 caps. Don't drink it all at once. Better get ready for a new fight.}
{345}{}{Who are you going to bet against me next time?}
{346}{}{Let me think. Now I see that you need a bigger opponent. What about Canelo? He won ten fights in a row. A serious opponent. You have chances, and the audience loves good fights.}
{347}{}{Great, I'll do this Canelo. He won't have a chance.}
{348}{}{I'll think about your offer. Bye, Angelo.}

#- the third fight
{350}{}{Great fight, }
{351}{}{. It's been a long time since there have been such powerful matches here. You're almost at the top of the championship title. ALMOST.}
{352}{}{Do you want to have another fight?}
{353}{}{Yes, IF you still have gunpowder for the battle. But first take your fee, there are 400 caps here.}
{354}{}{It follows from your words that the next fight will be with some serious pro.}
{355}{}{This is not just a professional. This is the invincible Big Mario Albright himself! He wants to fight you himself. But prepare for the battle thoroughly. No one has ever managed to get this bully on his back.}
{356}{}{The beast begins to wake up in me. I just can't not answer this call.}
{357}{}{I don't think I can handle another fight like this. Goodbye, Angelo.}
{358}{}{Almost? So I have to smear another face in the ring to become the best?}
{1358}{}{Almost? So I have to smear another face in the ring to become the best?}

#- the last fight
{360}{}{It was a brilliant fight, }
{361}{}{! The audience is delighted, there has not been such a stir for a long time. We collected huge bets, because many believed that Big Mario was invincible. But you managed to make it! Well done. Here are your 800 caps. But now let's talk about the bad.}
{362}{}{Is something wrong?}
{363}{}{You see, now you're like a champion. Invincible. Do you understand? We don't have any fighters who can be opposed to you. And I don't think they will appear any time soon. And if the public starts betting on you and winning, then we won't get anything from it. After all, we earn mainly on LOST bets. Do you understand?}
{364}{}{Does this mean I won't be able to participate in battles anymore?}
{365}{}{What the hell are you kicking me out of the ring for?}
{366}{}{Exactly. Sorry, amigo, but everyone had their golden time. It's been a pleasure doing business with you, but it's time for us to say goodbye.}
{367}{}{Damn, Angelo, aren't you interested in anything but caps? It looks like there's nothing left for me to catch in this ring.}
{368}{}{Fuck you!}

{370}{}{Tell me about my opponent.}
{371}{}{Tell me about my new opponent.}
{372}{}{Tell me about my next opponent.}
{373}{}{Tell me about my opponent.}
{374}{}{A tramp from the wasteland. This is a common opponent for the ring.}
{375}{}{A former bandit from the desert, his nickname is Savage. After the defeat of the gang, he came to Phoenix and is trying to make money from the fights, because he can't do anything else. He likes to fight, but he's not in the best shape. Which is not surprising for a highway bum.}
{376}{}{Canelo is one of the best fighters in the ring. You're worth each other. He has been diligently preparing for fights, be careful with him, he is stronger and faster than your past rivals.}
{377}{}{This time you will have to fight with a real beast in human skin. His nickname is Big Mario. He won so many victories that I lost count. No one wants to go against him anymore, you are the only one who is able to fight him. It's going to be a tough fight, but think about how many caps we'll get from this.}
{1377}{}{This time you will have to fight with a real beast in human skin. His nickname is Big Mario. He won so many victories that I lost count. No one wants to go against him anymore, only you can defeat him. It's going to be a tough fight, but think about how many caps we'll get from this.}
{378}{}{I see. I need to prepare for the fight.}

{380}{}{How are you, }
{381}{}{? The audience missed you. And you know, suddenly there was one rival just for you. It's like you were made for each other. Interested?}
{382}{}{No. I'm done fighting.}
{1382}{}{No. I'm done fighting.}
{383}{}{Sorry to hear that. Well, if you change your mind, let me know.}
{384}{}{Okay.}
{385}{}{But anyway, why not? Tell me about the opponent.}
{386}{}{Of course!}
{387}{}{That's the zeal! You won't regret it.}
{388}{}{Tell me about the opponent.}
{389}{}{Then a stupid green-skinned big guy wandered into town. A fucking mutant. Biceps are like supports from a bridge. No one could beat him. But you have a chance.}
{390}{}{Then prepare the ring. I'll be there at 20:00 as usual.}
{391}{}{Oh, no, I've seen them before. I pass.}
{392}{}{The big Green Son of a Bitch is waiting for you in the ring, }
{393}{}{}
{394}{}{Only death awaits him there.}
{395}{}{I need, uh, a drink of water. Give me a couple of minutes.}
{396}{}{This has never happened in Phoenix before! The sight was unforgettable. Legends will be made about this fight. How are you doing? It looks like you've been pretty battered by this fight. Here are 1500 caps, you'll need them to get back to normal.}
{397}{}{You're especially caring today, Angelo. I appreciate it. Thank you.}
{398}{}{I was almost killed, and here you are rejoicing like a child. My foot will not enter here again.}