{100}{}{You see Arthur Carrington.}
{101}{}{You see the archeologist from Vault 27.}
{102}{}{Thank you for everything! We'll meet in Casa Nueva.}
{103}{}{Thank you for everything! We'll meet in Villa.}

#First dialogue
{200}{}{Ah, it's my savior. Happy to see you.}
{201}{}{What are you doing here? I thought after the whole Vault ordeal, you were going to head to the Temple of Fire and dive deep into doing science.}
{202}{}{I would have. But the temple of Fire was destroyed by the time I arrived. I don't know what happened there, but the Fire-worshippers are now being persecuted, and no one needs a scientist like me around anymore.}
{203}{}{You sure?}
{204}{}{There's one thing I found that is interesting. A while ago, I saw reports in the Temple about a cult revering science, called the "Followers of the Apocalypse". Their base is somewhere to the south, but the files had rather little information. If you meet those guys, let me know, okay?}
{205}{}{Can't promise you anything. Thanks for the information, though.}

{210}{}{So, what now?}
{211}{}{Nothing. Bye.}
{212}{}{Bye.}

{220}{}{Why do you think the temple of Fire fell?}
{221}{}{I know they were making a nuclear bomb in the Vault underneath the building. But it spontaneously exploding is effectively impossible. There's only one thing it could be - sabotage. The Fire-worshippers had many enemies, but it's surprising that whoever did this managed to get so deep inside. Hm, it was obviously someone they trusted...}
{222}{}{It was me.}
{1222}{}{It was me.}
{223}{}{... I don't know what to say. Frankly, I think you might be lying. Regardless, don't say that to anybody. It won't do you any good, believe me.}
{224}{}{Why did they need a bomb, anyways?}
{225}{}{I know only that they were building it for someone else.}
{226}{}{What are you going to do?}
{227}{}{I'll look for a place where scientists like me are needed. Aside from those questionable rumours about the Followers of the Apocalypse, I have no other ideas.}
{228}{}{Why don't you come to Villa? More people will make restoring the place after that raid easier. And we could definitely use fresh brains that aren't restricted by our traditions.}
{229}{}{The Villa you were talking about in the Vault, right? I read various reports and figured out it's a closed commune of peasants. The Cult of the Fire has detailed files on you. As for your offer, well, I think it should be a great place to test and introduce new technologies.}
{1229}{}{The Villa you were talking about in the Vault, right? I read various reports and figured out it's a closed commune of peasants. The Cult of the Fire has detailed files on you. As for your offer, well, I think it should be a great place to test and introduce new technologies.}
{230}{}{Deal. Tell them I sent you when you get there. See you in Villa.}
{231}{}{Don't rush it. I'll still try to learn about the Followers of the Apocalypse.}
{232}{}{I managed to find the Followers in Casa Nueva. They'll be glad to accept a fellow man of science.}
{233}{}{You sure have a lot of connections for a farmer. Thank you.}
{234}{}{See you in Casa Nueva.}

{240}{}{I'll look for a place where scientists like me are needed. But so far, I only know of the Casa Nueva science base. But my reputation... doesn't quite match that place. Maybe you know of other places?}
{241}{}{Why don't you come to Villa? More people will make restoring the place after that raid easier. And we could definitely use fresh brains that aren't restricted by our traditions.}
{242}{}{The Villa you were talking about in the Vault, right? I read various reports and figured out it's a closed commune of peasants. The Cult of the Fire has detailed files on you. As for your offer, well, I think it should be a great place to test and introduce new technologies.}
{1242}{}{The Villa you were talking about in the Vault, right? I read various reports and figured out it's a closed commune of peasants. The Cult of the Fire has detailed files on you. As for your offer, well, I think it should be a great place to test and introduce new technologies.}
{243}{}{Deal. Tell them I sent you when you get there. See you in Villa.}
{244}{}{You know, now that I think about it, that's a terrible idea. They won't accept you there, they have a problem with scientists in general. You better go to Casa Nueva. Or wherever you were thinking of going.}
{245}{}{I'm sure the Followers will be glad to accept a fellow man of science. Maybe I'll head to Casa Nueva one day and we'll see each other again.}
{246}{}{That's right. Though the passage through the desert won't be easy. Maybe we'll see each other again sometime.}
{247}{}{Exactly. See you in Casa Nueva.}
{248}{}{That's probably not going to happen. Farewell, Arthur.}