{100}{}{You see the squatter.}
{101}{}{In front of you is a thin man in dirty clothes.}
{102}{}{*Crunch-crunch*}
{103}{}{It was the cardinals! They blew up the station!}

#Dialog
{200}{}{Oh, Mom, don't scare me like that! People rarely come here.}
{201}{}{Sorry, I didn't mean to. What are you doing here?}
{1201}{}{Sorry, I didn't mean to. What are you doing here?}
{202}{}{Idiot! You made my heart sink into my heels. What are you doing here anyway?}
{203}{}{Catching rats. They are fast and cunning, they will not fall into the trap so easily. Sometimes you have to wait for hours in ambush.}
{204}{}{Well, good luck in your difficult task. Bye.}
{205}{}{If you've been here for a long time, then surely you know who passed into the eastern sewers?}
{206}{}{Yeah. And what will happen to me if I tell you?}
{207}{}{I'll give you some food. Wait, I'll get something now...}
{208}{}{You've already had enough food. Now tell me.}
{209}{}{Here are ten caps for your food.}
{210}{}{Oh, thank you very much.}
{211}{}{Now tell me.}
{212}{}{Sorry, but my wallet is empty.}
{213}{}{I'll keep you alive, you piece of shit.}
{214}{}{Go away! Or I'll set a pack of rats on you. Shoo! Shoo!}
{215}{}{Well, well. }
{216}{}{Still have to get your hands dirty. Tell me what you saw!}
{217}{}{I'll keep you alive, you piece of shit.}
{218}{}{Have mercy! I'll tell you everything!}
{219}{}{Come on, tell me.}
{220}{}{They were cardinals. There was also a monk and a dead man with them. They said they wanted to blow up some pipes in order to deceive the chief at the station. Well, they have some kind of complicated history, I didn't understand anything.}
{221}{}{Well done, live for now.}
{222}{}{Thanks, buddy. You've helped me a lot.}

{250}{}{Hello. I've been seeing a lot of people here lately.}
{251}{}{Thanks for the food. Is there more?}
{252}{}{What are you doing here?}
{253}{}{Bye.}