{100}{}{You see Gut.}
{101}{}{You see a thin man in dirty clothes.}
{102}{}{*Chomp-chomp* Ta-asty. Now we can talk.}
{103}{}{Uh-h, how did you get this thing down here? It's so damn big.}

{110}{}{The squatter is too hungry to talk.}
{111}{}{Got food?}
{112}{}{Mind sharing something edible?}
{113}{}{Maybe share supplies?}
{114}{}{Everyone's a friend here. So everyone shares what they caught.}
{115}{}{Newbies must share something. It's a rule.}

#Dialogue
{200}{}{Thanks for the food. We don't have a lot of tourists around here. Usually, when someone comes down here, they aren't here for good reasons. You aren't going to cause us trouble, right?}
{201}{}{Depends on the answers I receive.}
{202}{}{No, I'm not going to cause you any trouble at all, friend.}

{210}{}{So, what brought you underground, cleanskin?}
{1210}{}{So, what brought you underground, cleanskin?}
{211}{}{Bye.}
{212}{}{I suppose that's enough. Farewell.}
{213}{}{Very interesting. Mind telling me about something else?}

{220}{}{Who are you?}
{221}{}{Surface people call us squatters. We have no home, no job, no friends up there. We live here, in the underground.}
{222}{}{Do you have a leader?}
{223}{}{No. Everyone's equal here.}
{224}{}{And who are you?}
{225}{}{Among my friends, I'm Gut. But you can call me senor Hidalgo. He-he. It be a joke. Didn't get it? Well... Fine, forget it.}
{226}{}{Have you been living in the underground for long?}
{227}{}{How long have you been living in the underground, Gut?}
{228}{}{I've been catching rats here ever since I was a kid. In dark times, my family hid in the underground, to get away from trouble. Now, I don't even want to come back.}

{230}{}{Why do you live in the underground?}
{231}{}{It's actually quite nice, when you get used to it. Up there, people are shooting and stabbing each other. We don't do that sort of thing here. We help each other, share what we catch. Live together, peacefully.}
{232}{}{What do you survive on?}
{233}{}{We catch rats and collect glowing fungus. We go to the surface sometimes to exchange that for somethin' useful.}
{234}{}{Hm. So that's where that trader in the marketplace gets his rats from?}
{235}{}{We're the best in that field. No one can catch rats quite as well as we can.}
{236}{}{Very interesting. I'd like to learn more about your people.}
{237}{}{That's enough. I'm leaving right now.}

{240}{}{Have you noticed anything interesting in the underground?}
{241}{}{Not really. Though lately, we're seeing outsiders more and more, and hearing unusual sounds.}
{242}{}{Unusual sounds?}
{243}{}{I dunno. Usually it's pretty quiet down here. But sometimes there are these sounds, like voices are whispering down a pipe. Some of us think it's a ghost, heh-heh. But I don't believe 'em.}
{244}{}{Tell me the legend about the ghost.}
{245}{}{They say one noble family man hid in the underground during the War. But hunger broke him. First, he ate his wife, then his own child. And when it came time for him to die, his spirit was left to wander around the sewers, looking for his lost family. (looks around) Hear that? Sometimes it feels like there's a bit of truth in that tale.}
{246}{}{A sad story. But I have a lot to ask you about still.}
{247}{}{There's nothing more idiotic than tales about wandering souls. I don't want to hear anything else from you.}
{248}{}{You believe in ghosts? Really?}

{250}{}{Do you know how to get deeper into the underground?}
{251}{}{No way to do that from here. You'll have to head up the surface and find another manhole. But believe me, you shouldn't go there alone.}
{252}{}{Why?}
{253}{}{Oh, there's stuff that's dangerous like you wouldn't believe. Hives of monsters, collapses, toxic pits, practically anything you can think of. Even we, the squatters, don't know about all the mysteries the underground holds. Lately, we've been finding more and more cleanskin corpses. I have no idea what they were there for.}
{254}{}{Oh wow, you're basically a scholar on these sewers. Mind telling me something else?}
{255}{}{That's it, I'm heading for the surface. Right now.}