{100}{}{You see the Gut.}
{101}{}{In front of you is a thin man in dirty clothes.}
{102}{}{*Crunch-crunch* Vcu-usno. Now we can talk.}
{103}{}{Uh, how did you manage to get this thing down here? It's so damn big.}

{110}{}{The squatter is too hungry to talk.}
{111}{}{Is there food?}
{112}{}{Do you want to share something edible?}
{113}{}{Why don't you share your supplies?}
{114}{}{Everyone has their own here. So, everyone shares their catch.}
{115}{}{Newcomers should share something. The rule is this.}

#Dialog
{200}{}{Thanks for the food. We don't often have tourists here. Usually, if someone shows up, it's not good. You're not going to create problems for us, are you?}
{201}{}{Depends on what answers I hear from you.}
{202}{}{No, no problem, buddy.}

{210}{}{So what brings you to this dungeon, pureskin?}
{1210}{}{So what brings you to this dungeon, pureskin?}
{211}{}{Bye.}
{212}{}{I think you've had enough. Goodbye.}
{213}{}{Very interesting. Can you tell me anything else?}

{220}{}{Who are you?}
{221}{}{People on the surface call us squatters. We have no home, no job, no friends on the surface. We live here in the subway.}
{222}{}{Do you have a leader?}
{223}{}{No, everyone is equal here.}
{224}{}{And who are you?}
{225}{}{I'm a Gut among my own. But you can call me señor Hidalgo. Hee-hee. This is a joke. Unclear? Well... Okay, forget it.}
{226}{}{How long have you been living in the subway?}
{227}{}{How long have you been living in the subway, Gut?}
{228}{}{From an early age, I caught rats here. And in troubled times, my family hid in the subway from problems. Now I don't want to go back up.}

{230}{}{Why do you live in a dungeon?}
{231}{}{It's not bad here if you get used to it. Upstairs, people are shooting at each other, but here we have everyone equal. Do you understand? We help each other, share the catch. That's how we live.}
{232}{}{How do you survive here?}
{233}{}{We catch rats and collect glowing mushrooms. Sometimes we go to the surface to exchange them for something we need.}
{234}{}{Hmm. So that's where the trader in the market gets the rats.}
{235}{}{We are the best in this business. No one knows how to catch rats like we do.}
{236}{}{Surprisingly. I want to know more about your people.}
{237}{}{That's it, I've had enough. I'm leaving here right now.}

{240}{}{Have you noticed anything interesting in these catacombs?}
{241}{}{Not really. Lately, outsiders have been increasingly seen here and unusual sounds are heard.}
{242}{}{Sounds?}
{243}{}{I don't know. It's usually pretty quiet here. But it happens that a noise rises, as if many voices are whispering into the pipe. Some people think it's a ghost, hehe. But I don't believe them.}
{244}{}{Tell me this legend about the ghost.}
{245}{}{They say a noble family man hid in the subway during the War. But hunger broke his spirit. First he ate his wife, and then his child. And when it came time to die, his spirit was left wandering through the sewers in search of a long-lost family. (looks around) Do you hear? Sometimes it seems to me that there is some truth in this story.}
{246}{}{A sad story. But I still have a lot to ask you.}
{247}{}{There is nothing more stupid than stories about wandering souls. I don't want to hear anything more from you.}
{248}{}{Do you believe in ghosts? Seriously?}

{250}{}{Do you know how to go deep into the collectors?}
{251}{}{From here - no way. You'll have to go up to the surface and find another hatch. But trust me, it's better not to go there alone.}
{252}{}{What's there?}
{253}{}{Hordes of monsters, landslides, poisonous pits - what is not here. But even we squatters don't know all the secrets of the subway. Lately we have been finding corpses of pureskins more and more often. I do not know what they are looking for here.}
{254}{}{Wow, you know all about this sewer. Will you tell me something else?}
{255}{}{That's it, I'm going back to the surface. Right now.}