{100}{}{You see a squatter.}
{101}{}{You see a dirty man in rags. The smell is fitting.}

#Floating dialogue
{110}{}{Ah? What?}
{111}{}{Do you hear me?}
{112}{}{I feel a cleanskin. We have guests?}
{113}{}{Looks like we have some tourists.}
{114}{}{It ain't rat season yet.}
{115}{}{I need to check the mousetraps.}
{116}{}{Skin's shedding again.}
{117}{}{Oof. I need to empty my stomach...}
{118}{}{*Scratches skin lazily*}
{119}{}{*Cough-cough-cough*}

#Replies

#- Player has tinsmith glasses
{130}{}{Good choice. Watch your back in those glasses.}
{131}{}{If only I had these glasses - I wouldn't have broken my leg last week. Twice.}
{132}{}{If you settle down in the sewers, like us, you wouldn't need these glasses.}
{133}{}{Live here for a while - you'll get used to the darkness.}
{134}{}{Can you see through clothes in these glasses of yours?}

#- Player sneaking
{135}{}{Why are you sneaking?}
{136}{}{Hiding from someone?}
{137}{}{Uh-uh, you're pretending to be a wall. I see you anyway.}
{138}{}{You always move like this?}
{139}{}{Damn drunk tourists.}

#- General replies
{150}{}{Hello.}
{151}{}{What are you looking for in the underground?}
{152}{}{New here? It's okay, I'm fine with that.}
{153}{}{Got lost? City's up there.}
{154}{}{It's not common that tourists come down here.}

{155}{}{It's actually quite nice here. Really.}
{156}{}{We have this custom - if you meet someone, share your food with them.}
{157}{}{Shush! Talk quietly.}
{158}{}{Hear that? The city up there breathes.}
{159}{}{Usually it's tranquil and quiet here... until someone from the surface comes.}

{160}{}{Hi.}
{161}{}{What are you looking for in the underground, beauty?}
{162}{}{New here? It's okay, I'm fine with that.}
{163}{}{Got lost? City's up there.}
{164}{}{It's not common that tourists come down here.}