{100}{}{Here is a squatter.}
{101}{}{You see a dirty man in rags. He smells like it.}

#Floating replicas
{110}{}{Eh? What is it?}
{111}{}{Do you hear?}
{112}{}{I smell pureskins. Do we have guests?}
{113}{}{Looks like we have new tourists.}
{114}{}{It's not rat season yet.}
{115}{}{We need to check the rat traps.}
{116}{}{The skin is shedding again.}
{117}{}{Uv. I need to empty my stomach...}
{118}{}{*Lazily itching*}
{119}{}{*Cough-cough-cough*}

#Response remarks

#- GG with tinker glasses
{130}{}{The right decision. Keep your eyes peeled in those glasses of yours.}
{131}{}{I would have such glasses - I wouldn't have broken my leg twice last week.}
{132}{}{If you live in sewers like we do, then you won't need glasses.}
{133}{}{Live here for a while - you'll get used to the dark too.}
{134}{}{Can you look through your clothes with those glasses of yours?}

#- GG sneaks
{135}{}{Why are you sneaking around?}
{136}{}{Hiding from someone?}
{137}{}{Yeah, merge with the wall. But I can still see you.}
{138}{}{Do you always move like this?}
{139}{}{Damn drunk tourists.}

#- Common phrases
{150}{}{Great.}
{151}{}{What are you looking for in the dungeon, handsome?}
{152}{}{The new guy? Okay, I don't mind.}
{153}{}{Lost? The city is above.}
{154}{}{It's not often that tourists come down to us.}

{155}{}{It's not bad here. The truth is true.}
{156}{}{It is customary for us to share food for dating.}
{157}{}{Shh! Speak softly.}
{158}{}{Do you hear? It breathes the city above.}
{159}{}{It's usually quiet and peaceful here... until someone from above comes down here.}

{160}{}{Hello.}
{161}{}{What are you looking for in the dungeon, beauty?}
{162}{}{New girl? Okay, I don't mind.}
{163}{}{Lost? The city is above.}
{164}{}{It's not often that tourists come down to us.}