{100}{}{You see a squatter.}
{101}{}{You see a thin man in dirty clothes.}
{102}{}{*Chomp-chomp*}
{103}{}{The Cardinals! They blew up the station!}

#Dialogue
{200}{}{Mamma mia, don't scare me like that! You rarely see people here.}
{201}{}{Sorry, I didn't mean to. And what are you doing here?}
{1201}{}{Sorry, I didn't mean to. And what are you doing here?}
{202}{}{You idiot! Because of you, I nearly had a heart attack. What are you doing here, anyway?}
{203}{}{Catching rats. They're fast, smart, don't get into a trap that easily. I often have to wait for hours to ambush one.}
{204}{}{Well, good luck in your difficult profession. Bye.}
{205}{}{If you've been here for a while, you wouldn't happen to know who went into the eastern part of the sewers, would you?}
{206}{}{Uh-uh. Now, what will I get in return for telling you?}
{207}{}{Food. Let me find something for you...}
{208}{}{You already got enough food. Now talk.}
{209}{}{Here are ten caps for food.}
{210}{}{O-oh, thank you.}
{211}{}{Now talk.}
{212}{}{Sorry, but my wallet is empty.}
{213}{}{I won't kill you that way. Sound good?}
{214}{}{Get away! Or I'll set the rats on you. Go! Go!}
{215}{}{We'll see about that.}
{216}{}{Do I have to get my hands dirty to get the information I want? Tell me what you saw!}
{217}{}{Me not ending your pathetic little life.}
{218}{}{Have mercy! I'll tell you everything!}
{219}{}{Do it.}
{220}{}{The Cardinals did it. They also had a monk and a dead-lookin' person. They said they wanted to blow up some pipes to fool the person in charge of the plant. Well, I think they have a complicated relationship, but I didn't make sense of anything.}
{221}{}{Good boy. Live some more.}
{222}{}{Thanks, friend. You really helped me.}

{250}{}{Hello there. I'm seeing too many people here lately.}
{251}{}{Thanks for the food. Got any more?}
{252}{}{What are you doin' here?}
{253}{}{Bye.}