{100}{}{This is Arthur Carrington.}
{101}{}{You see the same archaeologist from Vault 27.}
{102}{}{Thanks for everything! Meet me in Casa Nueva.}
{103}{}{Thanks for everything! I'll meet you at the Villa.}

#The first dialog
{200}{}{And here is my savior. Good to see you.}
{201}{}{What are you doing here? It seemed to me that after the Vault you would go to the Temple of Fire and plunge into science.}
{202}{}{That's what I did. But the Temple of Fire was destroyed. I don't know what happened there, but the fire worshippers are now in exile, and no one needs a scientist like me anymore.}
{203}{}{Are you sure?}
{204}{}{There is one clue. In the Temple, I came across scant reports about a cult with a scientific bias called Followers of the Apocalypse. Their base is somewhere in the south, but there is too little information. If you meet these guys, let me know. Okay?}
{205}{}{I promise nothing. And thanks for the tip.}

{210}{}{So what now?}
{211}{}{Nothing. Bye.}
{212}{}{Later.}

{220}{}{Why do you think the Temple of Fire fell?}
{221}{}{I know that a nuclear bomb was made in the Vault under the temple. But a spontaneous explosion is almost impossible. It looks very much like a diversion. The fire worshippers had many enemies, the only wonder is that they were able to penetrate so deeply. Hmm, obviously it was someone they trusted...}
{222}{}{It was me.}
{1222}{}{It was me.}
{223}{}{Don't say such things. I won't take your word for it anyway, and you don't need any extra rumors in the city, believe me.}
{224}{}{And why do they need a bomb?}
{225}{}{All I know is that it was made to order.}
{226}{}{What are you going to do?}
{227}{}{I will look for a place where scientists like me are needed. Apart from the dubious rumors about the Followers of the Apocalypse, I have no other ideas.}
{228}{}{Move to the Villa. We need workers to recover from the raid. And fresh brains that won't be limited by our foundations.}
{229}{}{The villa you were talking about in the Vault, right? I made inquiries and found out that this is a closed rural community. The Cult of Fire has managed to collect quite a lot of information about you. Well, I think this is a great place for research and the introduction of new technologies.}
{1229}{}{The villa you were talking about in the Vault, right? I made inquiries and found out that this is a closed rural community. The Cult of Fire has managed to collect quite a lot of information about you. Well, I think this is a great place for research and the introduction of new technologies.}
{230}{}{Agreed. When you get there, tell me you're from me. See you at the Villa.}
{231}{}{Take your time, I'll still try to find out about the Followers of the Apocalypse.}
{232}{}{I managed to find Followers in Casa Nueva. They will gladly accept a fellow scientist. So hit the road.}
{233}{}{For a farm dweller, you have an amazing amount of connections. Thank you, you're a real hero.}
{234}{}{See you in Casa Nueva.}

{240}{}{I will look for a place where scientists like me are needed. So far, I only know about the scientific base in Casa Nueva. But my reputation... doesn't quite answer this place. Do you know other places?}
{241}{}{Move to the Villa. We need workers to recover from the raid. And fresh brains that will not be limited by our foundations.}
{242}{}{The villa you were talking about in the Vault, right? I made inquiries and found out that this is a closed rural community. The Cult of Fire has managed to collect quite a lot of information about you. Well, I think this is a great place for research and the introduction of new technologies.}
{1242}{}{The villa you were talking about in the Vault, right? I made inquiries and found out that this is a closed rural community. The Cult of Fire has managed to collect quite a lot of information about you. Well, I think this is a great place for research and the introduction of new technologies.}
{243}{}{Agreed. When you get there, tell me you're from me. See you at the Villa.}
{244}{}{You know, it's a bad idea. They won't accept you there, they generally have a bad attitude towards scientists there. You'd better go to Casa Nueva. Or wherever you were going.}
{245}{}{Surely Casa Nueva will be happy to welcome a fellow scientist. Maybe I'll look there someday.}
{246}{}{That's for sure. Although the way through the desert is not easy. Maybe I'll see you again.}
{247}{}{Exactly. See you in Casa Nueva.}
{248}{}{It's unlikely. Goodbye, Arthur.}