{100}{}{You see a player.}
{101}{}{You see a casino visitor. He looks dissatisfied with both the service, and the whole world in general.}
{102}{}{Leave me alone, all I want is get drunk and smash the whole place down.}

{110}{}{How dare you throw me on the streets?!}
{111}{}{I demand an apology!}
{112}{}{If it wasn't for me, this whole city wouldn't have electricity!}
{113}{}{Do you know who I am?!}
{114}{}{You're laughing, aren't you? Laughing at ME, you fuckers?!}

{200}{}{(shouts in the general direction of the casino) ...Hey, you! You'll hear more about me, you greedy bastards...}
{201}{}{What's going on here?}
{202}{}{And who are you? You want to hit the jackpot? In the casino? No, n-no way. It's just ch-cheating and deception there...}
{203}{}{Are you drunk, sir?}
{204}{}{Drunk? I just had a *drink*. Half the city does. Women and children included.}
{205}{}{Uhh, I see.}
{206}{}{What *do* you see? Ugh... (brushes you off) You won't get it. I worked on the best caravan, and now they don't want to give me a ti-iny discount in this nicotine-filled shithole of a bar. So much for gratitude...}
{207}{}{Caravan? What caravan?}
{208}{}{The one that carried ore to Two Sun. Now that the tinsmiths are rusting under the baking sun, I'm unemployed. Thanks to whatever idiot that killed them all.}
{209}{}{You know, I don't think they did it to make you lose your job...}
{210}{}{Oh, fuck off! (brushes you off and walks away)}
{1210}{}{Oh, fuck off! (brushes you off and walks away)}
{211}{}{Uhh...}
{212}{}{It's your own fault that you associated with that questionable group.}
{213}{}{Tinsmiths? They supplied the whole city with energy... Ugh, you won't get it. (brushes you off and walks away, mumbling something)}
{214}{}{Uhh, whatever you say, man.}