{100}{}{You see the player.}
{101}{}{You see a casino visitor. He portrays in every possible way dissatisfaction with the service and at the same time with the whole world.}
{102}{}{Leave me alone, I want to get drunk and blow up the whole city.}

{110}{}{How dare you throw me out on the street?}
{111}{}{I demand an apology.}
{112}{}{Yes, if not for me, the whole city would have been left without energy.}
{113}{}{Do you know who I am?}
{114}{}{You're laughing, aren't you? Are you laughing at me, creatures?}

{200}{}{ (shouts towards the casino)...Hey, you! You'll hear from me again, you dirty misers...}
{201}{}{What's going on here?}
{202}{}{Oh, who else are you? Do you also want to hit the jackpot at the casino? No, nothing will come out. There are only f-crooks...}
{203}{}{Are you drunk, sir?}
{204}{}{Drunk? I just had a drink. Like half the city does. Women and children inclusive.}
{205}{}{Uh, I see.}
{206}{}{What do you understand there? And... (he waves it off) You don't understand. I worked in the best caravan, and now they don't even want to give me a little discount in this dirty smoky bar. So much for gratitude...}
{207}{}{A caravan? What kind of caravan?}
{208}{}{And of course, the one who carried ore to Two-Sun. Now the tinsmiths are rusting under the sun, and I don't have a job. Thanks to the idiot who arranged it.}
{209}{}{You know, I don't think he wanted such consequences...}
{210}{}{Fuck you! (he waves it away and walks away)}
{1210}{}{Fuck you! (he waves it away and walks away)}
{211}{}{Er...}
{212}{}{It's your fault that you got involved with these dubious types.}
{213}{}{Tinsmiths? Yes, they supplied the whole city with energy... Eh, you wouldn't understand. (he waves it away and walks away, muttering something under his breath)}
{214}{}{Uh, whatever you say, man.}