{100}{}{Here is Iron Mike.}
{101}{}{You see a still strong, but already senile fighter.}
{102}{}{Which... I don't talk to cowards who hide in power armor from a defenseless person.}
{103}{}{Someone killed Angelo. I'll find that son of a bitch and personally break his neck.}
{104}{}{Another junkie... The exit is there. I say THE EXIT IS THERE.}
{105}{}{Uh, no, buddy, I don't want to have anything to do with cardinals.}

#First dialog 1
{200}{}{(After entering the twilight of a stuffy room, you spend some time trying to get used to the vile smells of alcohol and desolation. Soon, something on an old torn chair makes a dangerous movement and screams "Hey, get out of my room!" throws a bottle at you.)}
{201}{}{What are you doing, you bastard?!}
{202}{}{Sorry, I didn't mean to disturb you...}
{1202}{}{Sorry, I didn't mean to disturb you...}
{203}{}{(You can distinguish a naked man with a very strong build in the chair; his arms and bald head are covered with clouded combat tattoos). I don't want to see anyone. Get out!}
{204}{}{Okay, whatever you say...}
{205}{}{Don't think you can get away with it.}
{206}{}{Go away. I don't want to see anyone.}
{207}{}{Let's talk?}
{208}{}{Don't you understand the first time? Get out!}
{209}{}{I just...}

#First dialog 2
{210}{}{I'm sorry I yelled. Sometimes I can't help myself, especially after the second bottle of tequila.}
{211}{}{I understand.}
{212}{}{Next time I can respond in kind.}
{213}{}{My name is Mike. They are also sometimes called Iron, because no one managed to beat me in the ring. But you know what? To hell with them! I'm tired of these fights. People fight only for the caps, and I fought for the right to be the besta. It's not the same thing.}
{214}{}{If you don't fight anymore, then what do you do?}
{215}{}{(sips the leftovers from the bottle and sighs) I'm drinking! And I remember the old days. Seriously, it won't be difficult for me to earn extra money on "power actions". But I don't want. The city is mired in sin... Are you listening?}
{216}{}{Yes, uh, in sin. What do you mean?}
{217}{}{Hey, leave me at least a couple drops.}
{218}{}{I used to teach young fighters the basics of street fighting. But after that, they went into the shadow business, became bandits or auxiliary criminal bosses. I don't teach anyone else. I drink - and it makes everyone feel good.}
{219}{}{It doesn't sound like fun.}
{220}{}{Yes, you're a complete loser.}
{221}{}{All these revolutionaries, sectarians, bandits, black market dealers - nobody cares about you and the city. Everyone cares about their own benefit... By the way, what are you doing here?}
{222}{}{Just looking for new acquaintances. I'm new in town.}
{223}{}{ (scratches his stubble and makes an indifferent grimace) You're not in the besta place for this, baby. But a fight in the ring may attract some attention to you.}
{224}{}{That's how? Great, I'm just thinking of going there.}
{225}{}{In fact, I'm here in search of my family. They were abducted by slavers.}
{226}{}{I'm sorry, I don't get involved in such things. But I know that the fire worshippers are somehow connected with the slavers. Be careful with this - it's a risky business.}
{227}{}{Thanks, Mike. Looks like it's time for me to talk to these fire worshippers.}
{228}{}{I want to learn the art of fighting.}
{229}{}{I've already said that I'm not going to train anyone.}
{230}{}{Sorry to hear that.}

{240}{}{Tell me about the arena.}
{241}{}{Angelo Rossitto runs everything there. He's a nice guy, knows how to keep a business acumen. Although because of the nature, sometimes you want to pack it into a toilet bowl push and press the flush pedal.}
{242}{}{Tell us about your victories in the ring.}
{243}{}{I have won all my battles. The street taught me how to fight, and constant training allowed me to consolidate my skills. I looked at some technologies in old books and movies.}
{244}{}{Movies?}
{245}{}{I was lucky. At that time, the scavengers found a surviving projector and old films. Someone used them for movie shows. Then it was the only normal entertainment in the city. But the theater did not last long. The owner was killed by robbers, and the projector was taken away. I don't know what happened to all this.}

{250}{}{Ah, this is the new champion. (looks appraisingly from head to toe with the air of a connoisseur) Of course, I wouldn't let you into the ring, but Angelo still has no choice. Enjoy the victory. And get out of my room.}
{251}{}{You won't see me again.}
{252}{}{Surely you're just jealous. Stay in your shit, alcoholic.}
{253}{}{Ah, this is the new champion. I see our training has not been in vain for you. I hope you will continue to use your skills for peaceful purposes.}
{254}{}{Don't doubt it, Mike. Later.}
{255}{}{Ah, this is the new champion. (looks appraisingly from head to toe with the air of a connoisseur) I don't understand why you're fighting at all. But I am glad that there is at least one normal guy among the fighters. (picks up the beer bottle) Your health.}
{256}{}{Bye.}

{260}{}{Angelo told me about your tragedy. Let's talk about it?}
{261}{}{I'm not like that, Mike. I will not cause harm without a reason.}
{1261}{}{I'm not like that, Mike. I will not cause harm without a reason.}
{262}{}{The temptation is great. You won't understand it until you're at a crossroads. I learned this lesson well.}
{263}{}{Did something happen?}
{264}{}{You say that as if the irreparable has already happened. Will you tell me?}
{265}{}{I'll pay, Mike. How much will you charge for one lesson?}
{266}{}{bottlecaps. Sure. Now everything is solved by these rattles, which a few years ago were worthless. But I'm not selling the right to violence anymore, if you know what I mean.}
{267}{}{Shall I tell you? (sigh) Then listen. I used to prepare everyone indiscriminately for the fight. I didn't care, as long as they paid properly. And I knew that some of my students went into street gangs or engaged in robbery, but I turned a blind eye to it... Until the tragedy happened.}
{268}{}{Go on.}
{269}{}{Well, yes, as usual, they think about the consequences only at the last moment.}
{270}{}{Late one night I was seeing off my girlfriend, Sabrina. We were attacked by robbers. I was able to fight them off, but I didn't have time to save Sabrina. During the fight, I recognized my students among the attackers.}
{271}{}{What happened to them?}
{272}{}{I hope you smeared them all on the asphalt?}
{273}{}{After the attack, they lay low and enlisted the support of gangs. I couldn't get close to them. But bandits don't live long. Now there is only one of the attackers left. He works as a security guard at a casino. If I touch him, the whole Don Diego dynasty will rise up against me. All I can do is forget myself with a bottle of tequila, which is prepared in the same casino.}
{274}{}{A sad story. Now I see why you don't want to teach me. Goodbye, Mike.}
{275}{}{I'll avenge you, Mike. I will get justice.}
{276}{}{Do you think this will be a consolation for me? No. I just want to look that bastard in the eye alone.}
{277}{}{That is, they have become an instrument of robbery?}
{278}{}{And what were you thinking, teaching these fools?}
{279}{}{I think I know what you're talking about. Is it because of the story with your girlfriend?}
{280}{}{Let's talk about that attack?}
{281}{}{I don't want to talk about it. Only one of the attackers is still alive. He works at a casino.}
{282}{}{Okay, forget it.}
{283}{}{I think you should know that he had an "accident". Are you satisfied?}
{284}{}{Partly. Although I don't know what I would do myself .......}
{285}{}{Fortunately, bandits don't live long. And I'm not going to join their ranks with new forces. All I have to do is forget myself with a bottle of tequila. I drink and don't touch anyone. It's good for everyone.}
{286}{}{It's a sad story, Mike. Now I see why you don't want to teach me.}
{287}{}{Come when you become a saint and begin to exude waves of goodness and peace. Then I'll teach you everything I know.}
{288}{}{Okay. I'll prove to you that you can trust me.}
{289}{}{I doubt that I will be able to change this city for the better even a little. Goodbye, Mike.}
{290}{}{Are you still against my training?}
{291}{}{I've heard about how much good you do to the residents of these slums. But why? What do you care about these poor people?}
{292}{}{I just can't stand injustice.}
{293}{}{I've heard about how much good you do to the people of this fallen city. But why? Why do you need this?}
{294}{}{They say you're a real hero, even if not in this city. You're helping the people of the wasteland. But why? Why do you need this?}
{1294}{}{They say you are the savior of the poor and oppressed, even if not in this city. You're helping the people of the wasteland. But why? Why do you need this?}
{295}{}{You know, I like you. I don't know why, but your presence makes me happier. I don't want the same thing to happen to you that happened to Sabrina or something.}
{296}{}{Will you teach me?}

#Training
{300}{}{Come in. But if I don't like something, you'll fly out of here into the street.}
{301}{}{Come in, friend. Did you bring another drink?}
{1301}{}{Come on in, baby. Did you bring more drinks?}
{302}{}{Make yourself comfortable.}
{303}{}{I have nothing else to teach you. Train yourself. I believe in you.}
{309}{}{See you later, Mike.}

{310}{}{Teach me to fight, master.}
{311}{}{Train a woman? I've never had to do this before. However, they say that women participated in the Great War. At least there are conscripts on the old posters.}
{312}{}{Exactly.}
{313}{}{I have already said that I am not going to train anyone.}
{314}{}{But why?}
{315}{}{You can rob people on the streets. Many have done so. I don't want to repeat this mistake.}
{316}{}{It's useless to argue with you. Bye, Mike.}
{317}{}{I'll pay.}
{318}{}{bottlecaps. Sure. Now everything is solved by bottlecaps. But first tell me, how are you going to use the acquired skills? For self-defense? To earn money in the ring? Okay, promise me, right now and here... No, SWEAR that you will use your skills for the benefit of ordinary people.}
{319}{}{I can't take such an oath.}
{320}{}{First of all. Exactly. Now go away. We have nothing more to talk about.}
{321}{}{Okay.}
{322}{}{I swear, Mike. I will not let down your expectations.}
{323}{}{Caps. Sure. Now everything is solved with caps. But I just don't want to waste time and effort on an ass like you. Go away.}
{324}{}{Okay.}
{325}{}{Hmm... I don't know... Give me time to think. And bring more drinks.}
{326}{}{Okay.}
{327}{}{So what have you decided? Will you train me?}
{328}{}{Maybe I've been wrong all these years... Good. But for each workout I will take 500 caps. As soon as you save up, come.}
{329}{}{See you later, Mike.}
{330}{}{Maybe I've been wrong all these years... Good. Get ready for training and come back tomorrow morning.}
{331}{}{I'll definitely come, Mike.}

{332}{}{(contemptuously) I knew I couldn't trust you. You swore an oath that you would use your skills for good. Now I don't believe a word you say. Go away and don't come back.}
{333}{}{E...}
{334}{}{Disappear, I don't want to see you. You're a disgrace to me.}
{335}{}{Okay, forget it.}

{340}{}{I'm here to learn the art of melee combat.}
{341}{}{Sounds a bit pompous, but it doesn't matter. Brought 500 caps?}
{1341}{}{Sounds a bit pompous, but it doesn't matter. Did you bring 500 caps?}
{342}{}{No, I didn't think of that somehow, sorry.}
{1342}{}{No, I didn't think about that somehow, I'm sorry.}
{343}{}{Maybe I would teach you for free, but when you pay for training, you appreciate it much more.}
{344}{}{Yes, of course.}
{345}{}{Here are the covers. What are we going to do today?}
{346}{}{Sounds inspiring. And you can keep the lids. Today I train for you for free. Just because I like you.}
{347}{}{Cool. What are we going to do today?}
{348}{}{I've heard rumors that you're involved in the murder of some children. I don't know if this is true, but I trust my source. From this day on, you are no longer my disciple. Go away.}
{1348}{}{I've heard rumors that you're involved in the murder of children. I don't know if it's true, but I don't want to check either. I don't want to see you from now on. Get out.}
{349}{}{...}

{350}{}{Let's start with the basics. Correct stance, breathing and concentration.}
{351}{}{It's time to move on to action. Let's work out the main blows and capture.}
{352}{}{I think you've learned a lot. Starting from this day, the hardest workouts will begin. We will work on endurance and fight against an armed enemy.}
{1352}{}{I think you've learned a lot. Starting from this day, the hardest workouts will begin. We will work on endurance and fight against an armed enemy.}
{353}{}{I've taught you a lot. The most important thing left is the ability to take care of yourself. This is important for the correct alignment of forces and control in a critical situation. It might save your life one day.}
{354}{}{[Start training]}
{355}{}{We're both too tired. Come back in a day.}
{356}{}{OK, master.}