{102}{}{Admission received.}
{103}{}{Only silence responds to your call signs.}
{104}{}{You press the buttons, but nothing happens. This intercom doesn't seem to be working.}
{105}{}{It won't help here.}
{106}{}{No one answers your call signs.}

{200}{}{You press the buttons, but nothing happens.}
{201}{}{Hey, is anyone home?}
{202}{}{Only silence answers your call.}
{203}{}{Leave.}
{204}{}{[CHEAT: open]}
{205}{}{(You hear a click and the door opens)}
{206}{}{It looks like taciturn guys are sitting there...}
{207}{}{I'm from the Rangers. Here are my call signs.}
{208}{}{Prior Mathias sent me to help the Liberation Party.}