{100}{}{It's a computer.}
{101}{}{Here is a computer with access to a shared network.}

#Dialog
{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Back.}

{210}{}{Activate the alarm system and lock the control room.}
{211}{}{Attention! All personnel urgently leave the control room.}
{212}{}{Disable the alarm system.}
{213}{}{The system is disabled.}

{220}{}{The act of conservation of the station.}
{221}{}{October 23, 2077. A state of emergency has been introduced at the station. Automatic protection protocols have been activated. An emergency shutdown of the reactor has been initiated.}
{222}{}{Next.}
{223}{}{August 16, 2163. Cancellation of the state of emergency at the station. Automatic protection protocols have been deactivated. Reactor start initiated.}
{224}{}{Hmm. These ghouls knew what to do.}

{230}{}{A contract with the Church of the Sacred Fire.}
{231}{}{Agreement on the supply of fuel cells for the reactor of the Theodore Roosevelt Nuclear Power Plant, Phoenix, Arizona, August 17, 2163.}
{232}{}{General information about the station.}
{233}{}{.....}
{234}{}{Contract for parts from... Garage City?}
{235}{}{(As it turned out, the tinsmiths received from the Followers of Fire the very detail that you handed over to the caravaneers in Garage City. She was sent here to replace the old damaged one.)}
{236}{}{Hey, I remember that story!}