{110}{}{"here we keep valuable pre-war knowledge. It would be useful to study them.}
{111}{}{"Here we keep valuable pre-war knowledge." you have already studied them.}
{112}{}{You have already studied these sources of pre-war knowledgeÿ.}
{113}{}{Ö you spent the whole day studying this storehouse of pre-war knowledge. Ònow a lot has become clearer.}
{114}{}{ The bodyguard will not allow you to study books without proper permission.}