{100}{}{This is a wanted poster.}
{101}{}{This poster shows a man suspiciously similar to you.}
{102}{}{You see a poster with your portrait and the inscription: "Wanted for crimes against the Church of the Sacred Fire."}
{103}{}{You see a poster with your portrait and the inscription: "Wanted for crimes against the city. Reward 500 caps."}
{104}{}{You see a poster with your portrait and the inscription: "Wanted for crimes against the city. The reward is 1000 caps."}
{105}{}{You see a poster with your portrait and the inscription: "Wanted for crimes against the city. Reward 2000 caps".}
{106}{}{The poster was torn down and destroyed.}