{100}{}{There are ads in front of you.}
{101}{}{You see a board with some ads.}
{102}{}{In front of you is a bulletin board. It is worth studying them more carefully.}

{200}{}{(In front of you is a fairly scribbled bulletin board)}
{201}{}{Leave.}
{202}{}{I see.}
{203}{}{Back.}

{210}{}{Dangerous areas.}
{211}{}{(You are looking at the map of Phoenix, where the most unfavorable areas are marked. The largest of them are signed: "Orris Territory", "Atomic Scientists", "Red Cardinals".)}

{220}{}{Beware of the mainline drivers!}
{221}{}{Beware of highway robbers on highways 10 and 17. Most of them are poorly armed and few in number, but there are particularly dangerous clans. These bandits attack travelers and caravans without pity and regret. Don't even try to negotiate with them.}

{230}{}{The Los Panchos Gang.}
{231}{}{Attention! Especially dangerous criminals are wanted - the atamans of the Los Panchos gang. (their portraits are attached) Payment of 500 caps per head of each.}
{232}{}{Hernando Aviles.}
{233}{}{[Crossed out] Hernando Aviles.}
{234}{}{Former security guard. Killed his own master and his entire family during a robbery. After that, he began to wander through the desert, where he joined the ranks of the Los Panchos gang. By nature, he is calm and cold-blooded. Likes to talk to his victims before killing.}
{235}{}{Chucho Navarro.}
{236}{}{[Crossed out] Chucho Navarro.}
{237}{}{In the past, an ordinary handyman. He escaped from slavery after he got there for debts. He is known for a craving for torture. Mentally unstable.}
{238}{}{Aidi Gorme.}
{239}{}{[Crossed out] Aidy Gorme.}
{240}{}{Former singer. Robbed the casino where she worked. After that, she disappeared with her accomplices in the desert, where she joined the Los Panchos gang. Having earned the respect of the gang, she eventually rose to the rank of ataman. She is known for her special cruelty, emotional intemperance and craving for cannibalism.}

{250}{}{Gil McCord is wanted.}
{251}{}{The former shooter Gil McCord is wanted for attacks on representatives of the mercenary guild. Reward 750 caps for dead or alive.}
{252}{}{[Crossed out] Gil McCord is wanted.}

{260}{}{Wanted }
{261}{}{ from the Villa... what?}
{262}{}{Wanted for numerous crimes against Phoenix residents. Any contact with this person can cost you your life.}
{263}{}{Wanted for numerous crimes against the Church of the Sacred Fire. Any contact with this heretic can cost you your reputation and well-being.}