{110}{}{The equipment fails.}
{111}{}{You managed to disable the radio transmitter. The fire worshippers were left without radio communication.}

#Dialog
{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{The radio transmitter is not responding.}
{204}{}{The radio station is not working because the cathedral is de-energized.}

{210}{}{Copy the frequencies and the cipher. This way I can eavesdrop on the fire worshippers' radio conversations.}
{211}{}{Radio frequencies copied.}
{212}{}{Examine the request history. I wonder if anyone could have shared information to organize attacks on the monks?}
{213}{}{You find the remains of an encrypted transmission. The access code to the terminal belonged to Prior Mathias.}
{214}{}{Got you, holy man?}

{220}{}{Listen to radio conversations with an agent of the Red Cardinals.}
{221}{}{"...I have information for Aaron. The Red Cardinals have begun to act".}
{222}{}{[Next]}
{223}{}{"Clarify the information, my dear. Every little thing is important to us".}
{224}{}{[Next]}
{225}{}{"Orris sent a man to sign a contract for the supply of weapons. He's going to strengthen his position in the slums. I've already talked about it, but you didn't listen to me".}
{226}{}{[Next]}
{227}{}{"Where will the transaction take place?"}
{228}{}{[Next]}
{229}{}{"In the collector near the main city gate. Most likely they will be sent a fake courier, but it does not matter. We have to break the deal in any way if we don't want a civil war in the slums".}
{230}{}{[Next]}
{231}{}{"Accepted. We are sending an agent. Be careful, Murphy. Orris must not suspect that you are working for us. Out of touch."}
{232}{}{What? Is Murphy an agent of the Cathedral? What a surprise...}
{233}{}{What? Are you kidding? First the atomists, and now Murphy. This is becoming the norm.}

{250}{}{Listen to radio conversations on the topic of sabotage at the nuclear power plant.}
{251}{}{"...Report, our dear observer. How is the operation progressing?"}
{252}{}{[Next]}
{253}{}{"Thank the Atom, everything went well. The Cardinals fulfilled their part of the contract flawlessly. They got into the basements of the station and blew up the cooler where they were told. There is no danger for the city".}
{254}{}{[Next]}
{255}{}{"Now it's up to Ralph and your diplomats. Don't miss the opportunity, they say they found a mercenary to fix the cooler. I don't think he will succeed, but you shouldn't delay".}
{256}{}{[Next]}
{257}{}{"Accepted. Keep us informed and may the Fire be with you."}
{258}{}{What? Ralph sold out to the church? That's the story...}
{259}{}{What? Are you kidding? First Murphy, and now the atomists. This is becoming the norm.}