{100}{}{You see Louis.}
{101}{}{You see a resident of the vault 25.}
{102}{}{As you say...}
{103}{}{Do it, I beg you!}
{104}{}{As you wish, Mr....}
{1104}{}{As you wish, Mr. Lady...}

{200}{}{(You see a man with a toolbox. At the sight of you, he hesitantly backs away and, looking at his feet, says: "M-my respects".)}
{201}{}{Wait a minute, who are you?}
{202}{}{M-my name is Louis... with your permission.}
{203}{}{And what are you doing here, Louis?}
{204}{}{P-checking the t-pipeline... with your permission.}
{205}{}{Will you stop repeating yourself?}
{206}{}{P-excuse me, sir. I will leave immediately, sir.}
{1206}{}{P-excuse me, madam. I will leave immediately, madam.}
{207}{}{Do not rush. I want to ask you.}
{208}{}{Uh, okay.}
{209}{}{I'm asking who you are, not what your name is.}

{210}{}{How can I help?}
{211}{}{Nothing yet.}
{212}{}{Enough about that.}

{220}{}{Tell me about yourself.}
{221}{}{(confused) M-my name is Louis... I was born here... And grew up.}
{222}{}{And that's it?}
{223}{}{P-sorry, sir. I've been setting up equipment here all my life. I have nothing more to tell about myself.}
{1223}{}{P-excuse me, madam. I've been setting up equipment here all my life. I have nothing more to tell about myself.}
{224}{}{Have you ever left the Vault?}
{225}{}{When I go up to the cathedral... but I've never been to the city of n-.}
{226}{}{It seems that you are attached to this Vault.}
{227}{}{I m-pray to our Lord for leaving me alive and giving me a job. Glory to the Lord!}
{228}{}{It turns out that you are a forced person here. But maybe you can answer a couple more questions.}

{230}{}{Would you like to escape from here?}
{231}{}{No way, sir! Without Vault, I will perish. That's what the Lord says, but I know it myself.}
{1231}{}{No way, madam! Without Vault, I will perish. That's what the Lord says, but I know it myself.}
{232}{}{I see this question has scared you pretty much.}
{233}{}{Excuse me, sir! I've been here all my life... I-don't know how to behave from outside. I'm afraid, sir!}
{1233}{}{Excuse me, madam! I've been here all my life... I-don't know how to behave from outside. I'm afraid, mistress!}
{234}{}{I see. But at least answer the questions?}
{235}{}{What are you doing here?}
{236}{}{I humbly serve the Lord of the Phoenix and his Advisor for the benefit of the Sacred Fire. I was assigned to set up the equipment, as this is my sacred duty.}
{237}{}{I see.}
{238}{}{You don't think so, do you?}
{239}{}{(He looks down, not knowing what to say; it looks like he was seriously beaten by fire worshippers.)}

{240}{}{Tell me about the Vault.}
{241}{}{Vault number 25, built by Vault-Tec to protect people from nuclear war and its consequences...}
{242}{}{Wait, but how did the fire worshippers end up here?}
{243}{}{(hesitantly) They... they came from outside and... p-settled here.}
{244}{}{You're not telling me something.}
{245}{}{You can find out the story on the computer network, it's true.}
{246}{}{I'll try. In the meantime, tell me more about the Vault.}
{247}{}{They don't talk about it here... The cult has taken over the sanctuary... And I was left to debug the equipment.}
{248}{}{A sad story. We're talking about something else.}

{250}{}{You know the Vault like the back of your hand, right?}
{251}{}{(smiling wryly) That's right, sir. I know, sir.}
{1251}{}{(smiling crookedly) That's right, mistress. I know, madam.}
{252}{}{Some doors are locked. Do you know how to open them?}
{253}{}{N-need an access card. Everyone has their level of access, the guards have the highest.}
{254}{}{Were there other Vaults?}
{255}{}{Yes, and a lot! Scientists in the laboratory know about them.}
{256}{}{Tell us about the days when the Vault was free.}
{257}{}{Here... it was wonderful. We lived our lives peacefully and amicably. And we had enough food and energy. No one was going outside. Then the outsiders came. They used a special signal to open the armored door and then burst inside. Only then the cult of the Sacred Fire appeared, and the Vault became its base.}

{260}{}{Bring me some clean water.}
{261}{}{(leaves and soon returns) Your water, sir.}
{1261}{}{(leaves and soon returns) Your water, lady.}
{262}{}{And now jump on one leg and get out of here!}
{263}{}{Thank you, my dear.}
{264}{}{As you wish...}
{265}{}{Do you always fulfill the requests of strangers?}
{266}{}{(looks up in amazement for a moment, but immediately turns it back down)}
{267}{}{Do you always fulfill the requests of strangers?}
{268}{}{There are no outsiders in the Vault, only Followers of Fire. And my sacred mission is to be useful to them...}
{269}{}{Did you decide that yourself?}
{270}{}{The adviser gives me instructions.}
{271}{}{Don't you obey the Phoenix Lord?}
{272}{}{Only as long as it does not contradict the words of the Adviser.}
{273}{}{While your master is not looking, let's talk about something else.}
{274}{}{Clearly. Later.}

{280}{}{Louis, do you want to end this life?}
{281}{}{I've been thinking about it. There's n-none of my loved ones left here. I can't leave the Vault, even if the doors are opened. What's left for me? To benefit the Adviser...}
{282}{}{But that's not what you want in your heart, right?}
{283}{}{Wait, this dialogue is going the wrong way. Let's go back.}
{284}{}{Well, it turns out you're a big loser. Have a good stay.}
{285}{}{I am insignificant... Insignificant! These people have never cared about me, I am a slave to them, and it will always be so!}
{286}{}{It's high time for you to end your suffering. Help me - we will destroy the Vault together.}
{287}{}{I... ask you, let me do my job for the benefit of the Sacred Fire!}
{288}{}{Then stay here, loser.}
{289}{}{Destroy it? That's it... How did I not guess earlier!}
{290}{}{Do you have an idea?}
{291}{}{There's a nuclear bomb down there. It's almost finished, scientists are waiting for only minor details, but it can already be started and ... (stammers and gets covered in cold sweat)}
{292}{}{And what? Blow it up? That's what we need, Louis. Tell me how to run it.}
{293}{}{The professor has details in his office, it is impossible to detonate a bomb without them...}
{294}{}{I'll need an access card to get into his office.}
{295}{}{Yes... This card has a high level of access. I will pray that everything will work out for you...}
{296}{}{Thank you, Louis, you have done a service not only to me but to the whole Wasteland. And now I have to go.}
{297}{}{It's easy to ingratiate myself with you, Louis. And now I will tell the Adviser about it. Bye, dummy.}
{298}{}{Why does the cult need a uranium bomb?}
{299}{}{I don't know, but after the complete assembly, it was going to be transported to the southwest, across the desert.}