{100}{}{You see Luis.}
{101}{}{You see an inhabitant of Vault 25.}
{102}{}{As you say...}
{103}{}{Do it, I beg you!}
{104}{}{As you wish, m-master...}
{1104}{}{As you wish, m-mistress...}

{200}{}{(You see a man with a toolbox. Seeing you, he hesitantly backs away and, looking at his feet, says: "It is an h-honor".)}
{201}{}{Wait a minute, who are you?}
{202}{}{M-my name is Luis... with your permission.}
{203}{}{What is it you do here, Luis?}
{204}{}{Ch-checking the p-pipeling... with your permission.}
{205}{}{Maybe you could stop repeating yourself?}
{206}{}{I a-apologize, master. I will leave immediately, m-master.}
{1206}{}{ a-apologize, mistress. I will leave immediately, m-mistress.}
{207}{}{Don't rush. There's something I want to ask you.}
{208}{}{Uhh, okay.}
{209}{}{I'm asking who you are, not what your name is.}

{210}{}{How can I help you?}
{211}{}{You can't, at the moment.}
{212}{}{Enough about that.}

{220}{}{Tell me about yourself.}
{221}{}{(bewildered) I-I'm Luis... I was born here... And grew up here.}
{222}{}{Is that all?}
{223}{}{I a-apologize, master. I spent all my life repairing equipment here. I have nothing more to say about myself.}
{1223}{}{I a-apologize, mistress. I spent all my life repairing equipment here. I have nothing more to say about myself.}
{224}{}{Did you ever actually leave the Vault?}
{225}{}{S-sometimes I go up the cathedral... but I was never in the city.}
{226}{}{It looks like you're attached to this Vault.}
{227}{}{I pray that our Overlord leaves me alive and gives me a job. Hail the Overlord!}
{228}{}{So you're not a free man. Maybe you could answer a few more questions?}

{230}{}{Do you want to escape this place?}
{231}{}{No way, master! I'll die without the Vault. The Overlord says that, but it's self-evident to me.}
{1231}{}{No way, mistress! I'll die without the Vault. The Overlord says that, but it's self-evident to me.}
{232}{}{I see thinking about this topic scared you geatly.}
{233}{}{I apologize, master! I spent all my life here... I-I don't know how to behave out-outside. I'm afraid, master!}
{1233}{}{I apologize, mistress! I spent all my life here... I-I don't know how to behave out-outside. I'm afraid, mistress!}
{234}{}{I see. But you *are* in a condition to answer my questions, right?}
{235}{}{What is it you do here?}
{236}{}{I humbly serve the Overlord of Phoenix and his Advisor for the good of the Holy Fire. I was t-told to repair the equipment, that is m-my holy duty.}
{237}{}{I see.}
{238}{}{You don't actually believe that, do you?}
{239}{}{(Looks at his feet, not knowing what to say; looks like the Fire-worshippers seriously messed him up.)}

{240}{}{Tell me about the Vault.}
{241}{}{Vault number 25, built by the Vault-Tec Corporation to protect humans from nuclear war and it's consequences...}
{242}{}{Wait, how did the Fire-worshippers find their way here?}
{243}{}{(hesitantly) They... came inside and... s-settled here.}
{244}{}{You're clearly not telling something.}
{245}{}{You can learn the story on the computer network. It's true.}
{246}{}{I'll try. For now, tell me about the Vault.}
{247}{}{They don't talk about that here... The cult captured the Vault... They left me alive to repair the equipment.}
{248}{}{A sad story. Let's talk about something else.}

{250}{}{You know the Vault like the back of your hand, right?}
{251}{}{(vaguely smiling) That's right, master. I do, master.}
{1251}{}{(vaguely smiling) That's right, mistress. I do, mistress.}
{252}{}{Some doors are locked. You know a way to open them?}
{253}{}{Y-you need a keycard. Every one has a clearance level, security has the highest one.}
{254}{}{There were other Vaults?}
{255}{}{Yes, many of them! The scientists in the laboratory know about them.}
{256}{}{Tell me about the days the Vault was free.}
{257}{}{It... it was... perfect. We lived together peacefully, we had enough food and energy for everyone. No one wanted to go outside. But then the outside came for us. They used a special kind of signal to open the large door and then barged inside. Then came the cult of the Holy Fire, and the Vault became it's main base.}

{260}{}{Bring me clean water.}
{261}{}{(walks away and returns soon after) Here is your water, master.}
{1261}{}{(walks away and returns soon after) Here is your water, mistress.}
{262}{}{Now jump on one leg 10 times and scram!}
{263}{}{Thank you, dear.}
{264}{}{As you wish...}
{265}{}{Do you always do whatever other people tell you?}
{266}{}{(looks up for a moment, amazed, but immediately looks back down)}
{267}{}{Do you always do whatever other people tell you?}
{268}{}{There are no "other" people in the Vault. Only Followers of the Holy Fire. And my holy mission is to be useful to them...}
{269}{}{Did you come up with that yourself?}
{270}{}{The Advisor tells me what to think.}
{271}{}{Don't you serve the Overlord of Phoenix?}
{272}{}{Only if it doesn't go against what the Advisor says.}
{273}{}{While your overlord's back is turned, let's talk about something else.}
{274}{}{Alright. Bye.}

{280}{}{Luis. I'm going to ask you a question. Do you want to end your life?}
{281}{}{I was... thinking about it. N-none of my friends or relatives are left. I can't leave the Vault, even if they opened the doors and told me to. What's left for me to do? Be useful to the Advisor...}
{282}{}{But deep down in your heart, you don't want that, do you?}
{283}{}{Wait, this conversation is going where it shouldn't. Let's go a bit back.}
{284}{}{Well, it looks like you're just one big loser. Enjoy your stay.}
{285}{}{I'm pathetic... Pathetic! These people never cared about me. I'm a slave! A slave! And always will be!}
{286}{}{Your suffering should have been ended long ago. Help me - we'll destroy this Vault together.}
{287}{}{I... Please, let me do my duties for the good of the Holy Fire!}
{288}{}{Then stay here, loser.}
{289}{}{Destroy? So that's how it must end... How did I not think of it sooner!}
{290}{}{You have an idea?}
{291}{}{There, down below, is an atomic bomb. It's almost completed, the scientists are just waiting for secondary components, but it can already be turned on and... (stumbles and starts sweating)}
{292}{}{And what? Be used to blow this place up? That's exactly what we need to do, Luis. Tell me how to turn it on.}
{293}{}{The professor's office has some components, without it, using the bomb is im-mpossible...}
{294}{}{I'll need a keycard to get inside of his office.}
{295}{}{Yes... Here. This one has a high clearance level. I'll pray that you succeed...}
{296}{}{Thank you, Luis. You've helped greatly not just me, but the entire Wasteland. Farewell.}
{297}{}{You know, it's so easy to earn your trust, Luis. Laughably so. Now if you'll excuse me, I'm off to the Advisor. Bye-bye, idiot.}
{298}{}{Why does the cult need a uranium bomb anyways?}
{299}{}{I... I don't know, but after it's complete, they were going to send it somewhere to the south-west, across the entire desert.}