{100}{}{You see a surgeon.}
{101}{}{You see a surgeon in a blood-stained lab coat.}
{102}{}{If I don't hurry, no kind of medicine will help me here...}

#First dialogue
{200}{}{What's the problem?}
{201}{}{Do you always have such a cavalier attitude to patients?}
{202}{}{(folds his gloves and rubs his hands) I am one, and my patients are many. Are you somehow special?}
{1202}{}{(folds his gloves and rubs his hands) I am one, and my patients are many. Are you somehow special?}
{203}{}{I don't know... What makes one special?}
{1203}{}{I don't know... What makes one special?}
{204}{}{Being a Follower of the Holy Fire... Or posessing a large amount of caps. So, do you need anything?}
{205}{}{I suppose.}
{206}{}{No, I don't. I was just curious.}

#Repeated dialogue
{210}{}{What's the problem?}
{211}{}{There isn't any.}

#Healing
{220}{}{I require healing.}
{221}{}{Well, let's see. What will we be healing?}
{222}{}{Injury.}
{223}{}{Physical trauma.}
{224}{}{Irradiation.}
{225}{}{Poisoning.}
{226}{}{Forget it, it will heal by itself.}
{227}{}{Regular case. Will deal with. But seeing as you're not a Follower, you will have to make a donation - }
{228}{}{ caps.}
{229}{}{Here they are.}
{230}{}{Regular case. Will deal with.}
{231}{}{Very sad. In that case, I can't help you.}
{232}{}{How can this be...}
{233}{}{Forget it, it will heal by itself.}
{234}{}{Praise the Holy Fire. Now, get out, I have other patients to take care of.}
{235}{}{That's not all, doc.}
{236}{}{Make it so, doc.}
{237}{}{With pleasure.}

{240}{}{Did you happen to see peasants from Villa?}
{241}{}{Hm, one of the slaves mentioned Villa during examination.}
{242}{}{What happened to him?}
{243}{}{I have no idea. The reports about slave transfers are made in the Cathedral. My job is to medically examine them.}
{244}{}{Alright.}