{100}{}{You see the surgeon.}
{101}{}{You see a surgeon in a blood-stained robe.}
{102}{}{If I don't hurry up, then no medicine will help me...}

#The first dialog
{200}{}{What's the problem?}
{201}{}{Are you always so cavalier with patients?}
{202}{}{(folds gloves and rubs hands) I am alone, but there are many patients. Are you something special?}
{1202}{}{(folds gloves and rubs his hands) I am alone, but there are many patients. Are you something special?}
{203}{}{I don't know... What will make me special?}
{1203}{}{I don't know... What will make me special?}
{204}{}{A special title of a Follower of Fire... Or a large amount of caps. So do you need something?}
{205}{}{Perhaps.}
{206}{}{No, nothing. I was just curious.}

#Repeat dialog
{210}{}{What's the problem?}
{211}{}{Nothing.}

#Treatment
{220}{}{I need treatment.}
{221}{}{Well, let's see. What will we treat?}
{222}{}{Injury.}
{223}{}{Injury.}
{224}{}{Irradiation.}
{225}{}{Poisoning.}
{226}{}{Come on, it'll pass by itself.}
{227}{}{The usual case. We will cure it. But since you are not a Follower, you will have to make a donation - }
{228}{}{ caps.}
{229}{}{Here are the bottlecaps.}
{230}{}{The usual case. We will cure it.}
{231}{}{Very sorry. In that case, I can't do anything to help.}
{232}{}{How so...}
{233}{}{No need, it will heal itself.}
{234}{}{Praise the Sacred Fire. Now get out of the office, I have other patients on the waiting list.}
{235}{}{That's not all, doc.}
{236}{}{Do it, doc.}
{237}{}{With pleasure.}

{240}{}{Have you come across any peasants from the Villa?}
{241}{}{Hmm, one of the slaves mentioned the Villa during the survey.}
{242}{}{What happened to him?}
{243}{}{I don't know. Reports on the supply of slaves are kept in the Cathedral. My job is only to conduct a medical examination.}
{244}{}{I see.}