{102}{}{Unnoticed theft in such conditions is simply impossible.}
{103}{}{We... are not... stop...}
{104}{}{}
{105}{}{Get out!}

#The first dialog
{200}{}{Impressive. You managed to get into the Vault without raising an alarm, get past the guards and get to the command center itself. Such a level of espionage is extremely rare. So why are you here?}
{201}{}{Impressive. Even after raising the alarm throughout the Vault, you managed to get to the command center itself. Few people are capable of this. What do you want?}
{202}{}{Hmm. A stranger in a Vault is always suspicious. Why are you here?}
{203}{}{Aaron sent me. I want to serve the Sacred Fire.}
{204}{}{I'm here for one purpose - to kill you.}
{205}{}{Then let's not waste time...}
{206}{}{Die for the freedom of the Villa!}
{207}{}{I won't answer until I know who I'm talking to.}
{208}{}{Apparently, you don't understand your situation well. Well, my name is Ulysses Grant, I am the first advisor to the Phoenix Lord Aaron. That should be enough for you.}
{209}{}{You're exactly who I'm looking for. Looking to finish it off.}

#The first dialogue if GG is a peasant
{210}{}{I'm looking for my tribesmen from the Villa. They say the Followers of Fire enslaved them.}
{211}{}{Villa... I remember. One of the primitive villages in the northwest. The slaves were transported from there to Two-Sun and now they will become fuel in the progress machine. It's a great honor, even if you don't like it.}
{212}{}{Why do you need slaves?}
{213}{}{Oh, there are many reasons - infrastructure restoration, work in mines, transportation between cities and much of what will be much more difficult to do by the forces of free mercenaries. The development of civilization requires large labor resources. And slavery is the most appropriate way to get them.}
{214}{}{Is it possible to enslave innocent people?}
{215}{}{Most of the locals are busy surviving and do not contribute to the development of the region at all. On the contrary, they are ready to fight and are not ready to cooperate. Narrow-minded egoism is what tribes like your Villa live by. To turn the power of these savages to the benefit of the whole region is a worthy goal to sacrifice the ethical side of the issue.}
{216}{}{What kind of progress are you talking about?}
{217}{}{You've come a long way, haven't you? The usual landscape now is a barren wasteland or the ruins of ancient cities. Life in such conditions is difficult and dangerous. But there are places where civilization returns. Electricity, medicine, education - all this has returned to the lands of Sonora thanks to us. And compared to this, the small household concerns of the Villa are nothing more than a mouse fuss.}
{218}{}{And what's next - are you going to enslave the whole of Sonora?}
{219}{}{That would be too wasteful. It is much easier to create habitable centers of civilization. By themselves, these colonies will be an example - a model to which the rest of the savages will catch up.}
{220}{}{The villa didn't need your "civilization". We had a lot of food and a complete order in the community.}
{221}{}{You're wrong. Your community is living out the last generations. Exhaustion of fertility, accumulation of mutations, high mortality rate, insecurity from external enemies and ordinary narrow-mindedness - all this limits your community and leads to imminent death. Don't you believe it? In vain. We have seen entire settlements go crazy just because the only water pump there broke down.}
{222}{}{And what does your cult offer?}
{223}{}{A return to civilization, of course. And we have already achieved a lot.}
{224}{}{Nonsense. You are simply parasitizing other people.}
{225}{}{That's reasonable. Sonora clearly lacks a strong hand to unite the fallen population.}
{226}{}{It's a pity that you didn't manage to get into our ideas. However, nothing new. You're just an ordinary hindrance to our plans. I'll have to eliminate you...}
{227}{}{Wait, we haven't...}
{228}{}{To do this, it is necessary to abandon the past - from superstitions, traditions and even family ties. Are you ready for such hardships?}
{1228}{}{To do this, it is necessary to abandon the past - from superstitions, traditions and even family ties. Are you ready for such hardships?}
{229}{}{Quite. I wish the Villa to join the path of progress and civilization.}
{230}{}{You're offering the impossible. Go to hell!}
{231}{}{In this case, prove your intentions - become a part of the cult of the Sacred Fire. By this you will give an example to your fellow tribesmen.}
{232}{}{Become a Follower? I'll have to talk to Aaron first. And what's next?}
{233}{}{The villa must become our new colony, otherwise time will wipe it off the face of the earth. Try to explain this to the rest of the peasants. And if you succeed, I will free all the slaves from the Villa.}
{234}{}{Agreed.}
{235}{}{You're offering the impossible. Go to hell!}
{236}{}{Talk to Aaron. He will give further instructions.}
{237}{}{OK.}
{238}{}{It's unthinkable. People like you need to be destroyed urgently!}
{239}{}{Yes, you're just covering up ordinary evil with beautiful words. You can't confuse me.}

#The first dialogue if GG became a member of BS
{240}{}{Glad to meet you, brother. The Brotherhood's agents have already passed on information about you and your service. The General Staff considers you promising, but my agents have a slightly different opinion.}
{1240}{}{Glad to meet you, Sister. The Brotherhood's agents have already passed on information about you and your service. The General Staff considers you promising, but my agents have a slightly different opinion.}
{241}{}{Glad to meet you, brother. The Brotherhood's agents have already passed on information about you and your service. I must say, you're showing great promise.}
{1241}{}{Glad to meet you, Sister. The Brotherhood's agents have already passed on information about you and your service. I must say, you're showing great promise.}
{242}{}{Aren't you also a member of the Brotherhood of Steel?}
{243}{}{Paladin Ulysses Grant. But in the Cathedral they call me a Counselor. I try to stay incognito in this city.}
{244}{}{What is the Brotherhood paladin doing in the heart of a strange cult?}
{245}{}{In fact, I run this cult, although few people know about it. The fact is that the Church of the Sacred Fire was organized by the Brotherhood of Steel a few years ago. Back then there was a time of troubles in Phoenix, we helped one of the clans seize power over the city and then put the people we needed at the helm. I still lead this elite for the sake of the Brotherhood.}
{246}{}{In other words, are Aaron and the other sectarians just a puppet in the hands of the Brotherhood?}
{247}{}{All right. The Brotherhood needs various resources and power over the region. But there are too few of us to keep the situation under control on our own. The idea of a revolution and the creation of a subsidiary cult turned out to be an ideal solution. Now we can only give commands, the real work is done by people accountable to us.}
{248}{}{It should be convenient. And what about the slavery in which the cult is seen?}
{249}{}{The elders of the order dislike slavery. But at the moment it is an inevitable sacrifice for the benefit of the development of the region. It will take a couple of generations until we can give up forced labor. Unfortunately, the local savages are not yet ready to take an independent step towards progress.}
{250}{}{What about the Villa?}
{251}{}{Oh, yes, the Villa... One of the primitive villages in the northwest. The report says you're from there. I'm sorry about what happened. In any case, your tribesmen have become fuel in the progress machine, and this is a great honor. And as a member of the Brotherhood of Steel, you should understand and accept this.}
{252}{}{Is it possible to free the Villa from bondage?}
{253}{}{Of course. But the Villa should become one of our colonies. Unfortunately, right now I have too much work to deal with this issue. You're going to have to help me. Talk to Aaron, he will give further instructions.}
{254}{}{Okay, I'll talk to him.}
{255}{}{Of course. But the Villa should become one of our colonies. This question will take some time.}
{256}{}{Then we'll talk about it a little later.}
{257}{}{Glad to meet you, brother. The Brotherhood's agents have already passed on information about you and your service. I must say, you're showing great promise. However, it was very rash of you to raise the alarm on the way here.}
{1257}{}{Glad to meet you, Sister. The Brotherhood's agents have already passed on information about you and your service. I must say, you're showing great promise. However, it was very rash of you to raise the alarm on the way here.}
{258}{}{}
{259}{}{The brotherhood informed me about your promotion. Glad to see you, brother.}
{1259}{}{The brotherhood informed me about your promotion. Good to see you, Sister.}

#After the destruction of Puerto
{260}{}{I knew you'd show up... Savage! Even after destroying our base in Puerto, you can't stop in your thirst for revenge? This is the problem of all local tribes - you cling to the past, although a bright future is revealed to you. We just need to accept progress and abandon old prejudices. But no, it's too difficult for you!}
{261}{}{In other words, the Brotherhood has failed in the lands of Sonora. Get over it, you idiot.}
{262}{}{It's just a postponement of the inevitable. The elders in California will open a new fort in Sonora sooner or later. By this time I will have time to prepare the Phoenix. Everything is just beginning.}
{263}{}{Hey, why do you need these machine guns... wait, you're not going to...}
{264}{}{You're wrong. The Brotherhood failed because of mistakes in its ideology, not because of the backwardness of the region.}
{265}{}{Nonsense!}
{266}{}{Not at all. You imposed ideas on the population that they were not ready to accept. So they were rebuffed.}
{267}{}{We tried to change you, to make you better! And instead of gratitude, they got a knife in the back. Look at how much the Brotherhood has done for you-electricity, education, economy. Does all this mean nothing?}
{268}{}{No, you weren't trying to make us better. You tried to make us your subjects. We are secondary to you. And we will always be like this.}
{269}{}{Maybe so. But peaceful means did not work. All we had to do was impose our ideas by force.}
{270}{}{But who decided that your ideas about the world are correct? Because they are taken from the pre-war era? But you know how that story ended.}
{271}{}{War... war doesn't change. We wanted to restore the former greatness of these lands.}
{272}{}{And as a result, they became ordinary invaders.}
{273}{}{Enough! Get back to your garden beds, savage. These lands are unworthy of our attention...}
{274}{}{Hmm...}
{275}{}{Looks like I can't change your mind.}

#Repeat dialog
{300}{}{Report.}
{301}{}{There's nothing to report yet. Well, I'll go.}
{302}{}{Can I get free access to the Vault?}
{303}{}{I don't see the need.}
{304}{}{The members of the Brotherhood of Steel should trust each other.}
{305}{}{As a member of the Sacred Fire Church, I swear to be careful.}
{306}{}{It is difficult to fulfill your mission without basic support.}
{307}{}{Okay, I'll manage.}
{308}{}{That's reasonable. Here's the magnetic card. She gives an average level of admission, that's enough for you.}
{309}{}{Better than nothing.}
{310}{}{I can't give you clearance yet.}
{311}{}{Thank you.}

#Questions
{320}{}{Can I know something?}
{321}{}{About what?}
{322}{}{I think I'll go. With your permission, Counselor.}
{323}{}{Can I ask one more question?}
{324}{}{Can we talk about the Sacred Fire Church?}
{325}{}{A cult that spiritualizes progress and knowledge.}
{326}{}{Is this cult also created by the Brotherhood of Steel?}
{327}{}{In a way. To be honest, we used the experience of another cult that had recently operated in California. It turned out to be a good idea.}
{328}{}{What kind of Vault is this?}
{329}{}{Before the Great War, similar Vaults were built all over the United States of America. They were intended to protect the population from nuclear strikes and their consequences. This Vault had the number 25.}
{330}{}{What do you know about the Great War?}
{331}{}{Many countries have exterminated each other for a handful of natural resources and world domination. The usual thing with the only difference is that wars have never had such large-scale and destructive consequences.}
{332}{}{How do you feel about Aaron?}
{333}{}{I'm not going to discuss this person with you.}
{334}{}{A fairly reliable doll with imperious ambitions and an insufficiently developed mind. Exactly the one we need.}
{335}{}{Someday he will resist his position.}
{336}{}{Without the support of the Brotherhood, this man has little chance of strengthening himself in the region. Fortunately, he understood this well.}
{337}{}{How about another question?}
{338}{}{Why do you need a nuclear bomb?}
{339}{}{I'm not going to discuss this with you.}
{340}{}{The Brotherhood of Steel has many reasons to keep such weapons in their hands. Especially after the recent events in California. However, it won't tell you anything.}
{341}{}{Can we talk about the Brotherhood of Steel?}
{342}{}{The Brotherhood of Steel is an organization that surpasses the locals in everything... In everything except numbers.}
{343}{}{How did it turn out that the Brotherhood runs a cult?}
{344}{}{The Brotherhood needs control over the surrounding lands. We cannot provide it on our own. Therefore, it was decided to establish a puppet government in Phoenix and manage the region through it. We created this cult and staged a revolution under its banners.}
{345}{}{What are the Brotherhood's plans for this region?}
{346}{}{We collect pre-war technologies and some resources. Mainly the general staff in California needs nuclear fuel. To ensure supplies, we need workers. And for this - the power in all of Arizona. To establish, strengthen and expand this power is our immediate task.}

{350}{}{I'll be in Phoenix for a while. Maybe there is a task for me in this city?}
{351}{}{No. Go to Puerto, there is nothing more important for you right now.}
{352}{}{The task is clear.}
{353}{}{Perhaps, yes. Upon returning to Phoenix, George Crook began to create problems. The old soldier talks too much and demands too much. It is necessary to shut it up.}
{354}{}{What's the catch?}
{355}{}{Crook and Aaron are old friends. I wouldn't want Aaron to know who ordered this murder. But Crook does not get out of the casino, so you need to eliminate him quietly.}
{356}{}{How can I go unnoticed then?}
{357}{}{Think about it. I will pay 500 caps for the elimination of the commander.}
{358}{}{Okay. I'll take the case. I will report on the result.}
{359}{}{Too risky. I'd rather do a holodisk.}
{360}{}{A "misfortune" happened to Commander Kruk.}
{361}{}{I've already heard the rumors. Good job.}
{362}{}{Glad to try.}
{1362}{}{Glad to try.}
{363}{}{Here's your fee. Don't you dare tell anyone about our agreement. No one will believe you anyway.}
{364}{}{Only one question - why was it necessary to kill Crook? Didn't he serve for the glory of the empire?}
{365}{}{Roger that, sir. Can I go?}
{1365}{}{Copy that, sir. Can I go now?}
{366}{}{There are two reasons for this. First of all, Commander Crook has done his job, he will only be a burden. The empire no longer has strong enemies, and the old war wolves don't like to sit around.}
{367}{}{And the second reason?}
{368}{}{Aaron deserved a little punishment. Thanks to his recent victories, he began to think too much of himself, began to demand a lot. We need to remind him where he started and who is the true master here.}
{369}{}{I see.}
{370}{}{It doesn't change anything for you, recruit. You know your task - they are waiting for you in Puerto. Go.}
{371}{}{I have the honor.}

#Your quest
{400}{}{You managed to outsmart Aaron and ingratiate yourself with him. But this number won't work with me. After all this history at the Villa, you must have very different ambitions.}
{401}{}{Thu... How are you...}
{402}{}{I know everything that happens in this city. There are eyes and ears everywhere. Of course, the Villa reports did not pass by. So what are you trying to achieve with all this conspiracy?}
{403}{}{I only want freedom for my people.}
{404}{}{A worthy goal for a person who knows nothing about freedom. As the Ancients said, freedom has a price. Your little people are not able to survive and even more so to preserve freedom in this world. Your only way out is to join the progress and become a part of this world.}
{405}{}{So... become a colony?}
{406}{}{After such a long journey, I realize that the Villa has to change.}
{407}{}{Hmm, curious. In that case, the only way out for your people is to become our colony.}
{408}{}{A colony?}
{409}{}{Exactly. You will partially lose your independence, but in return you will receive a profitable exchange of knowledge, technologies and products. Everyone will be in the black, but there is one problem - your society must change. You will have to explain to your fellow tribesmen the need to destroy outdated traditions and transition to a new way of life.}
{410}{}{It won't be easy. But I'll do whatever it takes. They'll listen to me.}
{411}{}{Good. In this case, you will have to make a small and dangerous journey. Take this holodisk with an important message. It must be taken to the military base in the Steel Port. It is safest to move there accompanied by caravans.}
{412}{}{But what about the enslaved peasants?}
{413}{}{You don't have to worry about it, I'll pass on the orders for their safety. But the issue of colonization should be decided by the General Staff. Get back to Puerto Penasco and show my report to the Commander-in-Chief.}
{414}{}{I'm leaving right now.}
{415}{}{I've completed Aaron's assignments. Now I ask you to free the peasants of the Villa from bondage.}
{1415}{}{I've completed Aaron's assignments. Now I ask you to free the peasants of the Villa from bondage.}
{416}{}{Your prowess amazes people like Aaron. But I have more information. What do you really want for your small and proud people?}
{417}{}{What is this base to which you need to take the holodisk?}
{418}{}{A military base in the port of Puerto Penasco on the shore of the Gulf of California. Few people know about it. You'll find out everything on the spot when you get there.}
{419}{}{Clear. Can I ask other questions?}
{420}{}{I will go there immediately.}
{421}{}{I could explain a little bit. Well, okay, I'll go take a look.}
{422}{}{And what is written on the holodisc?}
{423}{}{A secret report to the General Staff, among other things, it relates to the situation with the Villa. Don't show the disk to anyone and don't try to read it, it's encrypted anyway.}
{424}{}{Looks like you've figured out my plan. I'll have to kill you!}
{425}{}{That's enough! This will never happen. You are just robbers and extortionists.}
{426}{}{What narrowness of views... It looks like you can't be of any use to us.}
{1426}{}{What narrowness of views... It looks like you can't be of any use to us.}
{427}{}{Hey, is that a gun?}