{102}{}{It's impossible to steal unnoticed in such conditions.}
{103}{}{We... cannot... be stopped...}
{104}{}{}
{105}{}{Go away!}

#First dialogue
{200}{}{Impressive. You managed to get into the Vault without raising alarm, evade security and get to the very command center. Such skill in espionage is quite rare. So, why are you here?}
{201}{}{Impressive. You managed to get into the Vault without raising alarm, evade security and get to the very command center. Such skill in espionage is quite rare. So, why are you here?}
{202}{}{Hm. A stranger in the Vault - always quite suspicious. Why are you here?}
{203}{}{I was sent by Aaron. I wish to serve the Holy Fire.}
{204}{}{I'm here for one goal and one goal only - to kill you.}
{205}{}{Then let's not waste time...}
{206}{}{Die! For Villa's freedom!}
{207}{}{I won't answer until I learn who I'm talking to.}
{208}{}{It looks like you really don't understand your situation. My name? Ulysses. Ulysses Grant. Head advisor of the Overlord of Phoenix, Aaron. That should be enough for you.}
{209}{}{You're the one I'm looking for. Looking to kill.}

#First dialogue if player is a peasant
{210}{}{I'm looking for my fellow tribesmen from Villa. They say the Followers of the Fire enslaved them.}
{211}{}{Villa... I recall it. One of those primitive villages to the north-west. The slaves were relocated from there to Two Sun, and they will now become fuel for the machine of progress. It is an honor to receive this fate, even if you don't understand that.}
{212}{}{Why do you need slaves?}
{213}{}{Oh, there are lots of reasons - restoring infrastructure, mining ore, moving cargo between settlements and many other things that would be much harder to do with freelancers. Rebuilding civilization requires a lot of manpower. And slavery is the most efficient way of getting it in our situation.}
{214}{}{It's wrong to enslave innocent people.}
{215}{}{Most of them are concerned chiefly with survival, and do not contribute to the region's development in any way. Moreover - they are willing to fight, and are not willing to cooperate. Narrow-minded egoism is what tribes like your Villa are based on. To harness the capabilities of those primitives for the good of the entire region is a goal worthy of putting aside ethical and moral considerations.}
{216}{}{What kind of progress are you talking about?}
{217}{}{You've come a long way, haven't you? The usual terrain you see these days is either the lifeless wasteland or the remains of ancient, once-great cities. Life in such conditions is hard and dangerous. But there are places where civilization is being reborn. Electricity, medicine, education - all of that and more has come back into the lands of Sonora, thanks to us. Compared to this, what you've achieved in your Villa is nothing.}
{218}{}{What's next - you're going to enslave all of Sonora?}
{219}{}{That would be far too wasteful. It would be much easier to create bastions of civilization, where life is easy and comfortable. These colonies will, with their very existence, serve as an examples to the primitives - examples they will look up to.}
{220}{}{Villa had no need of your "civilization". We had plenty of food as well as stability and order within the communinty.}
{221}{}{Wrong. Your community was living out it's last few generations. Exhaustion of genetic diversity, build-up of mutations, a high death rate, lack of defense against external enemies and the usual narrow-mindedness - all of this restricts your potential and leads to an inevitable demise. Don't believe me? You should. We saw entire settlements get consumed by madness simply because their last remaining water pump broke down.}
{222}{}{And what does your cult offer?}
{223}{}{A return to civilization, naturally. We have achieved much. And we have much to achieve yet.}
{224}{}{Nonsense. You're simply parasitising on other people.}
{225}{}{Standing here, I realize you're right. Sonora lacks a strong, guiding hand that would unite the fallen population.}
{226}{}{It's a shame you've failed to see the greatness of our ideas. Well, nothing out of the ordinary. Like so many others, you're an obstruction to progress. An obstruction that's about to be removed...}
{227}{}{Wait, we haven't even...}
{228}{}{For that, the past must be rejected - superstition, traditions and perhaps even family ties. Are you ready for such sacrifice?}
{1228}{}{For that, the past must be rejected - superstition, traditions and perhaps even family ties. Are you ready for such sacrifice?}
{229}{}{Entirely. I want Villa to be set on the right path - the path of progress and civilization.}
{230}{}{You're offering the impossible. Go to hell!}
{231}{}{In that case, prove your intentions - become part of the cult of the Holy Fire. That way, you will be an example for your other tribesmen to look up to.}
{232}{}{I'm to become a Follower. Got it. I'll have to talk to Aaron first. Then what?}
{233}{}{Villa must become our colony, otherwise, time will wipe it off the face of the earth. Try to explain this to the other villagers. If you succeed, I'll give all slaves from Villa freedom.}
{234}{}{Deal.}
{235}{}{You're offering the impossible. Go to hell!}
{236}{}{Talk to Aaron. He will give you further instructions.}
{237}{}{Okay.}
{238}{}{Unthinkable! Those like you need to be destroyed!}
{239}{}{You're just covering up regular evil with pretty words about the greater good. You won't trick me into thinking you're on the right side of history.}

#First dialogue if player is a member of the brotherhood of steel
{240}{}{Happy to see you, brother. The Brotherhood's agents have given me information about you and your service. HQ thinks you have high potential, but my agents have a different opinion.}
{1240}{}{Happy to see you, sister. The Brotherhood's agents have given me information about you and your service. HQ thinks you have high potential, but my agents have a different opinion.}
{241}{}{Happy to see you, brother. The Brotherhood's agents have given me information about you and your service. I've got to say - you have high potential.}
{1241}{}{Happy to see you, sister. The Brotherhood's agents have given me information about you and your service. I've got to say - you have high potential.}
{242}{}{You're a member of the Brotherhood too?}
{243}{}{Paladin Ulysses Grant. But in the Cathedral, they call me the Advisor. I try to hide my true identity in this city.}
{244}{}{What is a Brotherhood paladin doing at the heart of a strange cult?}
{245}{}{I am the de facto leader of this cult, though few know about it. The truth is that the church of the Fire was created by the Brotherhood a few years ago. Those were troubled times for Phoenix. We helped one of the clans take over the city and then placed those we needed in it's leadership. I'm overseeing this elite to further Brotherhood interests.}
{246}{}{So, in other words, Aaron and the other cultists are mere puppets the Brotherhood controls?}
{247}{}{Exactly. We need resources and power over the region. But there are simply far too few of us to maintain control directly. The cult proved to be a perfect solution. Now we can just give orders while the real work is done by those accountable to us.}
{248}{}{Must be convenient. And what about the slavery the cult is involved in?}
{249}{}{The order's elders do not approve of slavery. But it is currently an unavoidable sacrifice we must make for the good of the region's development. It will take a few generations until we can phase out forced labor entirely. The unfortunate reality is that the local tribals are not ready to take steps toward progress on their own.}
{250}{}{And what about Villa?}
{251}{}{Ah yes, Villa... One of the primitive villages to the north-west. The report says you're from there. I'm sorry about that. But as a member of the Brotherhood, you have to understand that to become fuel and allow the machine of progress to endure is a great honor.}
{252}{}{Can Villa be freed from slavery?}
{253}{}{Of course. But Villa must become one of our colonies. Unfortunately, right now I'm far too busy to deal with this problem. You'll have to help me. Talk to Aaron, he'll tell you what to do next.}
{254}{}{Alright, I'll go talk to him.}
{255}{}{Of course. But Villa must become one of our colonies. Resolving this will take some time.}
{256}{}{Then let's talk about it a bit later.}
{257}{}{Happy to see you, brother. The Brotherhood's agents have given me information about you and your service. I've got to say - you have high potential. Though it was quite reckless of you to raise the alarm on your way here.}
{1257}{}{Happy to see you, sister. The Brotherhood's agents have given me information about you and your service. I've got to say - you have high potential. Though it was quite reckless of you to raise the alarm on your way here.}
{258}{}{}
{259}{}{The Brotherhood told me about your promotion. Happy to see you, brother.}
{1259}{}{The Brotherhood told me about your promotion. Happy to see you, sister.}

#After Puerto's destruction
{260}{}{I knew you'd come here... Primitive! Even after destroying our base in Puerto, you still can't stop in your lust for vengeance, huh? That's the problem with all you tribals - you cling to the past even though a glorious tommorow has been revealed right in front of your eyes. And to receive all it's benefits, one only has to accept progress and reject old superstition. But no, even that's too hard for you!}
{261}{}{In other words, the Brotherhood has suffered defeat in the lands of Sonora.}
{262}{}{You are merely delaying the inevitable. Sooner or later, the elders in California will set up a new fort in Sonora. And by that time, I will have prepared Phoenix. This is only the beginning.}
{263}{}{Hey, why do you need those big guns... wait, you aren't going to...}
{264}{}{The Brotherhood has failed here not because of the region's supposed primitiveness, but due to the errors in its ideology. You're implementing the exact same plan again and are somehow expecting a different result.}
{265}{}{Nonsense!}
{266}{}{Not at all. You tried to force the population to accept ideas it was not *ready* to accept. So you encountered resistance.}
{267}{}{We tried to uplift you, to improve your lives! And instead of gratitude, we get stabbed in the back. Look at all the things the Brotherhood has brought back - electricity, education, a functional economy. Does all of this truly mean nothing to you?}
{268}{}{No. You didn't try to 'uplift' us. You tried to make us your subjects. We're second-class to you. And always will be.}
{269}{}{What other course of action could we have undertaken when peaceful measures failed? The only thing we could do was force our ideas to be accepted.}
{270}{}{Who said your views on what the world should be like are right? Because they come from before the War? You know how the civilization that created those ideas ended.}
{271}{}{War... war never changes. We wanted to return greatness to these lands.}
{272}{}{And in the end, became regular invaders.}
{273}{}{Enough. Go back to your tribe, primitive. These lands are unworthy of our attention...}
{274}{}{Hm...}
{275}{}{Looks like I can't change your mind.}

#Repeated dialogue
{300}{}{Report.}
{301}{}{I have nothing to report. I'll be going.}
{302}{}{Can I receive free access to the various rooms in the Vault?}
{303}{}{I fail to see the necessity of this.}
{304}{}{Members of the Brotherhood should trust each other.}
{305}{}{As a member of the church of the Holy Fire, I swear to be careful.}
{306}{}{You know, it's kind of hard to do my mission when I don't get even basic support.}
{307}{}{Fine, I'll do without it.}
{308}{}{Good point. Take the keycard. It will grant you a medium clearance level, that will be enough.}
{309}{}{Better than nothing.}
{310}{}{I cannot give you access at this moment.}
{311}{}{Thank you.}

#Questions
{320}{}{Can I ask you about something?}
{321}{}{What exactly?}
{322}{}{I suppose I'll go. With your permission, Advisor.}
{323}{}{Can I ask you one more question?}
{324}{}{Can we talk about the church of the Holy Fire?}
{325}{}{A cult that spiritualizes progress and knowledge.}
{326}{}{Was that cult created by the Brotherhood too?}
{327}{}{In a way. To be honest, we didn't come up with the idea ourselves. We based it off another cult that once existed in California. The idea ended up being ingenious.}
{328}{}{What kind of a vault is this?}
{329}{}{Before the Great War, Vaults like these were constructed all across the United States of America. They were meant to protect the population from atomic blasts and their consequences. This particular Vault was given the designation 25.}
{330}{}{What do you know about the Great War?}
{331}{}{Many different nations exterminated one another for world domination and a handful of natural resources. The usual, with the one exception that wars never had such massive and destructive consequences before.}
{332}{}{What do you think about Aaron?}
{333}{}{I am not discussing this person with you.}
{334}{}{A fairly reliable puppet with large ambitions and an insuffiently developed mind. Just the man we need.}
{335}{}{He'll start to resist his position one day.}
{336}{}{Without Brotherhood support, he has little chance of establishing himself in the region. Luckily, he has learned that lesson well already.}
{337}{}{How about another question?}
{338}{}{Why do you need an atom bomb?}
{339}{}{I'm not discussing this topic with you.}
{340}{}{The Brotherhood of Steel has loads of reasons to keep such a weapon. Especially after the recent events in California. Though this won't mean anything to you.}
{341}{}{Can we talk about the Brotherhood of Steel?}
{342}{}{The Brotherhood is superior to this region's locals in every way... Every way except numbers.}
{343}{}{So, how did the Brotherhood end up controlling a cult?}
{344}{}{It needed control over these lands. Maintaining that control with our own forces would be next to impossible. So it was decided upon to establish a puppet state in Phoenix and control the region through it. We created this cult and under it's banners, incited a revolution.}
{345}{}{What plans does the Brotherhood have for the region?}
{346}{}{We are collecting old world technology and some resources. The one California HQ needs the most is nuclear fuel. To ensure delivery, we need manpower. And for that - control over all of Arizona. Obtaining, ensuring and expanding this control - these are our immediate goals.}

{350}{}{I'll still be in Phoenix for some time. Maybe you have some assignment for me that I'll be able to do while in the city?}
{351}{}{No. Head right to Puerto, there's nothing more important for you here.}
{352}{}{The task is clear.}
{353}{}{As a matter of fact, I do. Since his return to Phoenix, George Crook has done nothing but cause trouble. The old warrior talks too much and demands too much. The time has come to shut him up.}
{354}{}{What's the catch?}
{355}{}{Crook and Aaron are old friends. I wouldn't want Aaron to know who arranged the murder. But Crook is not taking a step outside of the casino, so he needs to be removed quietly.}
{356}{}{How do I stay undetected?}
{357}{}{Find a way. I'll pay you 500 caps for the commander's removal.}
{358}{}{Alright. I'll take on this case. Will report when it's done.}
{359}{}{Far too risky. I better deal with the holodisk.}
{360}{}{Commander Crook had an "unfortunate accident".}
{361}{}{I've already heard the rumours. Good job.}
{362}{}{Happy to help.}
{1362}{}{Happy to help.}
{363}{}{Here is your reward. I trust you will not disclose anything about our agreement.}
{364}{}{Just one question - why did you have to kill Crook? Did he not serve the empire well?}
{365}{}{Understood, sir. Can I go?}
{1365}{}{Understood, sir. I can go, right?}
{366}{}{There were two reasons. First, commander Crook was not only no longer useful, but a liability. The empire has no strong enemies anymore, and old wolves don't like to sit around twiddling their thumbs.}
{367}{}{And the second?}
{368}{}{A little punishment for Aaron was in order. Thanks to his latest victories, the man started to think too much of himself, demand too much. It was time to remind him where he started and who's really in charge.}
{369}{}{Alright.}
{370}{}{But for you, recruit, this changes nothing. You know your goal - they're waiting for you. In Puerto. Go.}
{371}{}{Farewell.}

#His own quest
{400}{}{You've managed to trick Aaron and earn his trust. But this trick won't work on me. After the whole Villa incident, you must have entirely different ambitions.}
{401}{}{Wh... So you...}
{402}{}{I know everything that happens in this city. I have eyes and ears everywhere. Obviously, the reports about Villa did not escape me. So, what are you trying to achieve with this conspiracy of yours?}
{403}{}{I want nothing but for my people to be free.}
{404}{}{A worthy goal, for someone who knows nothing about freedom. As the Ancients said, freedom has a price. If your small tribe did receive freedom, it would be incapable of retaining it, or even surviving. Your only choice is to merge with progress and join with the rest of the world.}
{405}{}{So... become a colony?}
{406}{}{After such a long way, I recognize that Villa has to change.}
{407}{}{Hm, interesting. In that case - the only future for your people is to become our colony.}
{408}{}{Colony?}
{409}{}{Exactly. You'll lose some of your independence, yes, but in return, you'll benefit greatly from the exchange of knowledge, technology and products. It is a mutually beneficial system, but there is one problem. Your society will have to change. You will have explain to your tribesmen the necessity of getting rid of old traditions and converting to a new way of life.}
{410}{}{It won't be easy. But I'll do everything that is necessary. They'll listen to me.}
{411}{}{Good. In that case, you'll have to make a small but dangerous trip. Take this holodisk. It contains an important message. It must be brought to the Steel Port military base. The safest way to get there is to be escorted by caravans.}
{412}{}{But what about the enslaved peasants?}
{413}{}{Don't worry about that, I'll deal with them. But a solution to the Villa question must be found in headquarters. Head to Puerto Penasco and give my report to the commander-in-chief.}
{414}{}{I'm heading there right away.}
{415}{}{I've done all of Aaron's assignments. Now I ask you to free Villa's peasants.}
{1415}{}{I've done all of Aaron's assignments. Now I ask you to free Villa's peasants.}
{416}{}{Your valor impresses people like him. But I have more detailed files. What is it you really want for your small and proud tribe?}
{417}{}{What is the base where I have to carry the holodisk?}
{418}{}{The military base in the Puerto Penasco port, on the shores of the Gulf of California. Few know about it. You'll learn everything when you get there.}
{419}{}{Alright. Can I ask you some other questions?}
{420}{}{I'll head there right away.}
{421}{}{You could have at least explained things more. Fine, I'll go there.}
{422}{}{What's on the holodisk?}
{423}{}{A secret report to HQ, concerning, among other things, the Villa situation. Do not show the disk to anyone and don't waste your time trying to read it - it's encrypted.}
{424}{}{Looks like you figured out my plan. I'll have to kill you!}
{425}{}{Enough is enough! No way! You're just a bunch of bandits and extortionists.}
{426}{}{Such narrow-mindedness is truly something to behold... But we have work to do. As we won't be working together, we will have to remove you out of our way.}
{1426}{}{Such narrow-mindedness is truly something to behold... But we have work to do. As we won't be working together, we will have to remove you out of our way.}
{427}{}{Hey, is that a gun?}