{100}{}{You see a guard.}
{101}{}{You see one of the members of the cult's security team. He looks indistinguishable from other guards.}

{104}{}{Someone raised the alarm. Looks like I'll have to stop you...}
{105}{}{Leaving already? Good.}
{106}{}{Stop! Who's there?}
{107}{}{Intruder alert!}
{108}{}{Stop! Who's... Ooh, it's almost like I saw a ghost.}

{200}{}{Stop! State your name and the purpose of your visit.}
{201}{}{Sorry, brother, I haven't been here very long and just wanted to have a look around.}
{1201}{}{Sorry, brother, I haven't been here very long and just wanted to have a look around.}
{202}{}{Sorry, brother, I'm new here and just wanted to have a look around.}
{203}{}{Why all these questions, brother? Aren't my robes enough?}
{204}{}{Uhh, I better get outta here...}
{205}{}{Tell your boss I have information for him.}
{206}{}{I am heading to meet Ulysses Grant. I was sent by Aaron himself.}
{207}{}{Let me express how deeply we respect you, secondary advisor. Head down to the lowest level, Ulysses is at his post.}

{210}{}{Intruder alert!}
{211}{}{Fuck, now I'll have to shut you up!}
{212}{}{But I didn't do anything!}
{213}{}{Alright, you can come in, brother.}
{1213}{}{Alright, you can come in, sister.}
{214}{}{Praise the Holy Fire, Brother.}
{215}{}{Thank you... brother.}

{220}{}{Leaving so soon?}
{221}{}{Yeah. Goodbye.}
{222}{}{Go. You'll find the way without us.}
{223}{}{Okay.}
{224}{}{I'm going to the Advisor. I was sent by his highness Aaron, Overlord of Phoenix.}