{100}{}{You see the guard.}
{101}{}{You see one of the guardians of the cult. He looks indistinguishable from the rest of the guards.}

{104}{}{Someone raised the alarm. Looks like I'm going to have to detain you...}
{105}{}{Are you leaving already? That's good.}
{106}{}{Stop! Who's coming?}
{107}{}{The intruder! Raise the alarm!}
{108}{}{Stop! Who did... uh, I think I saw a ghost.}

{200}{}{Stop! Tell me the name and purpose of the visit.}
{201}{}{Sorry, brother, I'm new here and just wanted to look around.}
{1201}{}{Sorry, brother, I'm new here and just wanted to look around.}
{202}{}{Sorry, brother, I'm new and I just want to look around.}
{203}{}{Why these questions, brother? Isn't my cassock enough?}
{204}{}{Eh, I'd better get out of here...}
{205}{}{Tell your boss that I have information for him.}
{206}{}{I'm going to Ulysses Grant. I was sent by Aaron himself.}
{207}{}{Let me express our deepest respect, Counselor. Go down to the lower level, Ulysses is at his post.}

{210}{}{The intruder! Raise the alarm!}
{211}{}{Damn, I'll have to shut you up!}
{212}{}{But I didn't do anything!}
{213}{}{Okay, come on in, brother.}
{1213}{}{Okay, come on in, Sister.}
{214}{}{Praise the Sacred Fire, brother.}
{215}{}{Thank you... brother.}

{220}{}{Are you leaving already?}
{221}{}{Yes, see you later.}
{222}{}{Come on in. You'll find your way without us.}
{223}{}{OK.}
{224}{}{I'm going to the Counselor. I was sent by His Holiness Aaron, the Lord of the Phoenix.}