{100}{}{You see a test subject.}

{101}{}{In front of you is distraught. He silently stared up somewhere.}
{102}{}{Here is a woman with disheveled hair and reddened eyes. She turned to the wall.}
{103}{}{This is a psychopath. He sits on the floor and sways, clutching his head.}

{111}{}{Uh-uh...}
{112}{}{I won't fall for your tricks! Get out, you damned sectarian!}
{113}{}{My head! I hear so many thoughts... Your thoughts... they're terrible!}