{100}{}{You see Professor Zimmer.}
{101}{}{Here is the leader of the scientific group. He looks weird.}
{102}{}{Now is not the time for scientific controversy...}

#The first dialog
{200}{}{(in front of you is a scientist in a lab coat with a crazy look and tousled hair; he speaks without looking up from his tablet) I'm busy, get out.}
{201}{}{I'm new here, can I have a couple of questions?}
{202}{}{How dare you talk to me like that?!}
{203}{}{Then I'm sorry to bother you.}

{207}{}{That's what I'm trying to explain - I'm new here and...}
{208}{}{Security! We have an outsider!}
{209}{}{You shouldn't have done that...}

{210}{}{(irritated) I told you, I don't have time for everyone... Stop. And who are YOU?}
{1210}{}{(irritated) I told you, I don't have time for everyone... Stop. And who are YOU?}

{211}{}{I'm a Follower.}
{212}{}{That's it. (gradually raises his voice) And now you think you can break into the lab and distract ME from my business?! (raises his voice again) Understand, you piece of social decay, that the work of this laboratory is above all your mouse fuss in the Cathedral! And no matter how high a title you hold in your "sect", it doesn't matter here! Do you understand that? Now get lost.}
{1212}{}{That's it. (gradually raises his voice) And now you think you can break into the lab and distract ME from my business?! (raises his voice again) Understand, you piece of social decay, that the work of this laboratory is above all your mouse fuss in the Cathedral! And no matter how high a title you hold in your "sect", it doesn't matter here! Do you understand that? Now disappear.}
{213}{}{I see.}
{214}{}{Yeah.}

{215}{}{I was allowed to look around.}
{216}{}{In this case, you can not count on the tour. Get out before I call security!}
{217}{}{No problems.}

{219}{}{I was sent to fix something.}
{220}{}{So go and fix it, idiot!}
{1220}{}{So go and fix it, idiot!}
{221}{}{Yes, uh, of course.}

{223}{}{I am also a scientist, and I was referred to you.}
{224}{}{Really? (puts down the tablet) Very curious... quite... But no one has reported to me about a new laboratory assistant. Bring the order, then we'll talk.}
{225}{}{OK.}

{227}{}{I was allowed to look around.}

#Repeat dialog
{300}{}{Good. And now - what do you need?}
{301}{}{Nothing else.}
{302}{}{Goodbye.}
{303}{}{Can we change the subject?}
{304}{}{Let me ask you another question.}
{305}{}{With all due respect, colleague, here *I* am in charge. And I have the right to kick anyone out of the lab, even Aaron himself. Get out!}
{306}{}{Okay, okay...}

#Questions about yourself
{310}{}{I'm sorry, but who are you?}
{311}{}{ (waves his hand in frustration) That's what it means to be in the shadows... My name is Zach Zimmer. Professor Zach Zimmer. And I'm in charge of this research department. Practically, I am the third person in the whole church, after Aaron and the Counselor. You don't have to bend the knee.}

{312}{}{A scientist in our time is unusual.}
{313}{}{That's why I'm sitting in a Vault under the protection of the largest organization. Scientists without patrons can not survive in our time.}
{314}{}{And the Professor is the name?}
{315}{}{(sighs) Stupider question I have not heard.}
{316}{}{Professor is a title. And it is issued collectively.}
{317}{}{What an insight! I'll tell you a secret - at one time I took courses in a little-known organization in these parts. That's where I was awarded this title.}
{318}{}{And how did you end up here, Professor?}
{319}{}{You must have a very interesting story.}
{320}{}{It's a long story, and it's not for your ears. Let's just say there wasn't enough room for my ambitions in the West.}
{321}{}{In the west of California. I don't think you could have crossed the desert that separates us.}
{322}{}{Ahem. You ask too many questions.}
{323}{}{I'm a member of the Brotherhood of Steel. Surely, there is a detailed dossier on you at the base.}
{324}{}{It changes a lot. Yes, I came here with the Brotherhood of Steel. And he received the title from the Followers of the Apocalypse in the Burial Ground. But my colleagues and I disagreed, and I had to leave for Arizona.}
{325}{}{What were the contradictions?}
{326}{}{Let's put it this way... The followers of the Apocalypse are too soft. They oppose experiments on living people. And this slowed down many medical projects.}
{327}{}{And what kind of Burial Ground?}
{328}{}{Ruins to the west, beyond the Sonoran Desert. It's very far away, you can't get there.}

{330}{}{So you're also a Follower of Fire?}
{331}{}{What nonsense is this? I'm a scientist, not a preacher! Besides, many things in the teaching seem to me just ridiculous.}
{332}{}{Can you tell me about Aaron?}
{333}{}{Discussing leaders has always been dangerous. Even among cult members.}
{334}{}{I'm not a cult member.}
{335}{}{Then we have nothing more to talk about.}
{336}{}{I am a member of the Brotherhood of Steel.}
{337}{}{Oh... It changes a lot... Well, then you'd better talk to the Counselor, not me.}
{338}{}{This will remain between us.}
{339}{}{Aaron would have been nothing if he hadn't been put in charge of the city and the church. He still feels like a puppet, sometimes it pisses him off... However, I'm talking too much today.}
{340}{}{You can't trust anyone here.}
{341}{}{For example?}
{342}{}{I'm already tired of explaining simple things to all these monks. Better read the scientific literature.}
{343}{}{For example, the deification of elementary particles?}
{344}{}{Precisely! What kind of ridiculous fiction is this, that a certain deity punished people with a Fiery Flood for their sins? It was a nuclear war! That is, an ordinary war with very powerful bombs.}
{345}{}{Don't they know that?}
{346}{}{I'm afraid too much time has passed. The events of a bygone era are overgrown with myths and legends. On the other hand, the faith of Followers is useful for society... so far, it is not going against progress.}

{350}{}{Why are you snapping at subordinates?}
{351}{}{Because I'm tired of idiots and ignorant monkeys.}
{352}{}{And that's it?}
{353}{}{I'm not going to discuss it.}
{354}{}{I think this is a projection of unfulfilled hopes. Aren't you being given proper freedom?}

{355}{}{(adjusts glasses in perplexity) Well, wow! Look, the first psychologist of a post-nuclear civilization! Leave these sweet consoling speeches to those who are sitting at the top. If they paid more RESPECT to my cause, I wouldn't have to raise my voice to everyone I met.}
{356}{}{Of course, whatever you say.}
{357}{}{What is a "monkey"?}
{358}{}{( sighs) It's you.}
{359}{}{[Science 20] They say that labor has made people out of monkeys.}
{360}{}{Nonsense! I managed to find old texts where it is clearly stated that these are two different branches of evolution with the same ancestors. However... it is much more important that I hear it from the mouth of a commoner.}

#Questions about the bomb
{378}{}{And you designed all this yourself?}
{379}{}{Of course. Many years of painstaking work of a handful of scientists.}
{380}{}{Is that a nuclear bomb you have? Impressive.}
{381}{}{Perhaps this is the most difficult thing we have managed. No one, up to California and Texas, could have done it. And we are on the verge of completion! It remains only to wait for some details from Two-Sun.}
{382}{}{California and... Texas?}
{383}{}{(disappointed) Texas! These are parts of a bygone country, dumbass. Maybe they are called differently now, but before the War they were called that way.}
{384}{}{But you wouldn't be able to construct it without instructions.}
{385}{}{Hmm, you catch on the fly! Without instructions, we wouldn't have been able to get anything but cancer and leukemia. And the instructions were brought by order from an old military base, it's very far from here.}
{386}{}{And where do you get nuclear material?}
{387}{}{From Flagstaff, there is an operating uranium mine and a processing plant. The quality is low and the production is slow, but we have no other sources.}
{388}{}{Why do you need such a powerful weapon?}
{389}{}{Good question. Let's just say there are many reasons. And all of them are known only to one person in all of Phoenix - the Adviser himself.}

#Research questions
{400}{}{What kind of research does the laboratory do?}
{401}{}{Different, obviously. (goes into his thoughts) Our mission is... in order to first provide the Followers of Fire with everything they need... yes. And then take up the reconstruction of the city and its industrial facilities. After all, we need workers... And this is only the first part of the plan. The most important thing now is to eliminate the shortage of food and clean water in Phoenix.}
{402}{}{And how are you doing?}
{403}{}{There is progress, but it is too slow. The city is badly destroyed, old equipment is destroyed or worn out, and the production base of this Vault will only be enough to provide for the Cathedral. Add to this squabbles between individual clans in the city, illiteracy and a whole list of other problems. And if you don't have any more stupid questions, then I'll go back to finding solutions.}
{404}{}{It seemed to me that the Followers were not so generous as to distribute food.}
{405}{}{What are you talking about? No one is going to feed this rabble on the streets! Food and water are unconditional power over the whole city. In exchange for food, the locals are ready to do any job, and we need cheap workers.}
{406}{}{Power? What a banality.}
{407}{}{What narrowness of views! Power is just a mechanism. When we created the cult of Fire, there was no power in this city. And there were pathetic primates feuding among themselves over a dead rat. And look at the city now. With our submission, electricity and currency returned here, industry and education were born, even gambling appeared! And all this thanks to the heavy hand of the cult, which put the local monkeys straight.}
{408}{}{[Science 100] How confident are you that society is ready for such innovations?}
{409}{}{I've been thinking about it a lot......}