{100}{}{You see professor Zimmer.}
{101}{}{You see the leader of the science team. He looks strange.}
{102}{}{Now is not the time for heated scientific discussions...}

#First dialogue
{200}{}{(you see a scientist in a lab coat, with a crazy-looking gaze and tousled hair; he speaks without looking away from his tablet) I'm busy, go away.}
{201}{}{I haven't been here for too long, could I ask you a couple of questions?}
{202}{}{How dare you talk to me like that?!}
{203}{}{Sorry for disturbing you.}

{207}{}{I'm trying to tell you just that - I'm new here and...}
{208}{}{Security! Intruder!}
{209}{}{You shouldn't have done that...}

{210}{}{(irritated) I told you, I don't have time for... Wait. Who are YOU?}
{1210}{}{(irritated) I told you, I don't have time for... Wait. Who are YOU?}

{211}{}{I'm from the Followers.}
{212}{}{Oh, I see. (slowly starts raising voice) And now you think that you can waltz into my lab and distract ME from my projects?! (raises voice again) Learn this once and for all, you nobody, that the work conducted here is higher than the pathetic things you do in your Cathedral! And whatever rank you achieved in your "organization", here it means nothing! Got all that? Good. Now begone from my sight.}
{1212}{}{Oh, I see. (slowly starts raising voice) And now you think that you can waltz into my lab and distract ME from my projects?! (raises voice again) Learn this once and for all, you nobody, that the work conducted here is higher than the pathetic things you do in your Cathedral! And whatever rank you achieved in your "organization", here it means nothing! Got all that? Good. Now begone from my sight.}
{213}{}{Alright.}
{214}{}{Uh-uh.}

{215}{}{I was given permission to familiarize myself with this place.}
{216}{}{In that case, don't count on a tour. Get out before I call security!}
{217}{}{No problem.}

{219}{}{I was sent to fix something.}
{220}{}{Then go and fix it, you idiot!}
{1220}{}{Then go and fix it, you idiot!}
{221}{}{Yes, uhh, of course.}

{223}{}{You know, I'm something of a scientist myself. They told me to go meet you.}
{224}{}{Oh really? (puts tablet aside) Very interesting... very... But nobody told me about a new assistant. Bring me the written order, and then we'll talk.}
{225}{}{Okay.}

{227}{}{I was given permission to look around.}

#Repeated questions
{300}{}{Good. Now - what do you want?}
{301}{}{Nothing else.}
{302}{}{Goodbye.}
{303}{}{Maybe we could change the subject?}
{304}{}{Let me ask one more question.}
{305}{}{With all due respect, colleague, *I'm* in charge here. I have the right to make anyone get out of this lab, even Aaron himself, if he came down here. Now leave!}
{306}{}{Fine, fine...}

#Personal questions
{310}{}{Excuse me, but who are you?}
{311}{}{(waves his hand in dissapointment) So that's what it means to "be in the shadow"... My name is Zack Zimmer. Professor Zack Zimmer. I'm in charge of the science team here. I'm basically the third most important person in the entire church, after Aaron and the Advisor. You don't have to bend your knee.}

{312}{}{Scientists are rather rare in our time.}
{313}{}{That's why I'm sitting in this Vault, under the protection of the most powerful organization in the region. Scientists can't survive without overlords in this age.}
{314}{}{Is Professor a name?}
{315}{}{(sighs) And they used to say there were no stupid questions.}
{316}{}{Professor is a title. It's issued by other people.}
{317}{}{How perceptive! I'll reveal a secret - in my time, I passed courses from one small organization few know about in this region. They gave me the title.}
{318}{}{How did you end up here, professor?}
{319}{}{You must have had an interesting life.}
{320}{}{It's a long story, and it's not for your ears. Let's just say there was no place for my ambitions in the west.}
{321}{}{California is to the west. I don't think you would have managed to traverse the desert that separates that region from this one that easily.}
{322}{}{Ahem. You're asking too many questions.}
{323}{}{I'm a member of the Brotherhood of Steel. I'm sure there is a detailed dossier about you on the base.}
{324}{}{This changes much. Yes, I came here with the Brotherhood. I received the title from the Followers of the Apocalypse in the Boneyard. But I and my colleagues disagreed on things, and I had to go to Arizona.}
{325}{}{What did you disagree with them about?}
{326}{}{Let's just say the Followers of the Apocalypse were too... weak. They were against experiments on living human subjects. This ethical inflexibility inhibited the progress of many medical projects.}
{327}{}{What Boneyard?}
{328}{}{Ruins to the west, beyond Sonora. They are too far away. You can't get there.}

{330}{}{So you're a Follower of the Holy Fire as well?}
{331}{}{What nonsense are you talking about? I'm a *scientist*, not a priest. I completely reject many things they believe.}
{332}{}{What can you tell me about Aaron?}
{333}{}{Discussing leaders was dangerous in all times. Even among members of the cult.}
{334}{}{I'm not a member of the cult.}
{335}{}{Then we have nothing more to talk about on that topic.}
{336}{}{I'm a member of the Brotherhood of Steel.}
{337}{}{Oh... Well, this changes a lot... I think you should talk to the Advisor instead of me.}
{338}{}{This will remain between us.}
{339}{}{Aaron would be no one if he wasn't placed in charge of the city and the church. He knows he's nothing but a fraud, a puppet, and at times it drives him mad... Though I'm already saying too much.}
{340}{}{No one can be trusted here.}
{341}{}{Like?}
{342}{}{I'm tired of explaining elementary things to these monks. Go read scientific literature.}
{343}{}{Like saying elementary particles are divine?}
{344}{}{Exactly! What is this nonsense that some kind of divine entity punished humans for their sins with a flood of fire? It was a nuclear war! A regular war, with the only difference of really powerful bombs!}
{345}{}{Don't they know that?}
{346}{}{I'm afraid too much time has passed. The events of the previous age have turned to myth and legend. On the other hand, the faith of the Followers is beneficial to society... until it goes against progress.}

{350}{}{Why are you screaming at your subordinates?}
{351}{}{Because I'm tired of being surrounded by idiots and ignorant primates.}
{352}{}{Is that all?}
{353}{}{I have no intention of discussing this with you.}
{354}{}{I think it's just a result of your unrealized hopes. They keep you on a leash, don't they?}

{355}{}{(adjusts glasses in disbelief) Would you look at that! The first psychologist in a post-nuclear civilization! Leave these comforting, reassuring speeches to those above. If they had more RESPECT for what I do, I wouldn't have to scream at every person who passes me by.}
{356}{}{Of course, whatever you say.}
{357}{}{What's a "primate"?}
{358}{}{(sighs) It's you.}
{359}{}{[Science 20] They say labor turned primates into man.}
{360}{}{Nonsense! I managed to find old texts - they clearly say these are two different lines of evolution with common ancestors. Though... to hear something like this from the lips of a commoner...}

#Questions about a bomb
{378}{}{Did you make all of this yourself?}
{379}{}{Of course. Many decades of labor from a small group of scientists.}
{380}{}{You have an atomic bomb? Impressive.}
{381}{}{It is perhaps the most complex project we have succeeded at. Nobody from California to Texas would manage to do this. And we're on the brink of finishing it! We just have to wait until a few components from Two Sun arrive.}
{382}{}{California and... Teehas?}
{383}{}{(sighs) Texas! Part of the country that's now gone, you imbecile. They may call the states differently now, but before the War, they were called exactly that.}
{384}{}{But you couldn't have built it without instructions, right?}
{385}{}{Hm, you're learning as we go! Without instructions, we would have got ourselves nothing more than leukemia. The instructions came from an old military base, one very far away.}
{386}{}{Where are you getting your nuclear material from?}
{387}{}{From Flagstaff. They have a functioning uranium mine and an enrichment plant. Quality's low, production slow, but there's no other source.}
{388}{}{Why do you need such a powerful weapon?}
{389}{}{Good question. Let's just say there are many reasons. They are known to only one man in Phoenix - the Advisor himself.}

#Questions about studies
{400}{}{What is the laboratory studying?}
{401}{}{Many things, obviously. (retreats into his thoughts) Our goal is to... our goal is to, at first, supply the Followers with all they need... Yes. And then focus on reconstructing the city and it's industry. We do need workers... And that's only Phase One of our plan. Right now, the most important thing is to solve the scarcity of food and clean water in Phoenix.}
{402}{}{And are you successful at this?}
{403}{}{There is progress being made, but it's far too slow. The city is very devastated, old technology is destroyed or worn out, and the productivity of one Vault will only be enough to supply the Cathedral. Add the pathetic squabbles between the various clans of the city, lack of literacy and a whole other list of problems. If you don't have any more stupid questions, I'll go back to solving them all.}
{404}{}{I didn't think the Followers were generous enough to hand out food.}
{405}{}{What are you talking about? Nobody is going to give out food to that rabble in the streets! If the Followers gain control over food and water, they gain complete control over the entire city. In exchange for supplying their basic needs, the population will be ready to do anything, and we need cheap workers.}
{406}{}{Control? How trivial.}
{407}{}{What narrow-mindedness! Control is but a mechanism. When we were creating the cult of Fire, there was no organization that had any meaningful kind of control over the city. There were pathetic primates, fighting each over over dead rats. Look at the city now. Our work has allowed electricity and currency to come back, industry and education to be recreated, even for gambling to exist! All of that thanks to the strong hand of the cult, that set the animals on the right path.}
{408}{}{[Science 100] Are you sure that society is ready for such changes?}
{409}{}{I thought a lot about it......}