{100}{}{You see a test subject.}

{101}{}{You see a madman. He's silently looking at the ceiling.}
{102}{}{You see a woman with ruffled hair and red eyes. She is turning away from you, toward the wall.}
{103}{}{You see a psycho. He's sitting on the floor and is swinging whilst grasping his head.}

{111}{}{Uh-h-h-h-h...}
{112}{}{Your tricks won't work on me! Get away, you damned cultist!}
{113}{}{My head! I hear so many thoughts... so many... Your thoughts... are horrible!}