{110}{}{This bomb can be very dangerous, but lacks only a few components.}
{111}{}{Bomb ready to explode.}
{112}{}{You have successfully installed the fuses.}
{113}{}{The bomb is ready to explode. Use the traps skill to activate it.}
{114}{}{Damn, this has got to be the biggest bomb imaginable.}
{115}{}{There is no need. History has already been corrected.}

{120}{}{You see a low-yield nuclear warhead. Though not finished, it can still be blown up.}
{121}{}{The bomb lacks fuses, which at the moment means it's safe.}
{122}{}{You've successfully activated the timer on the atomic bomb.}
{123}{}{You've successfully deactivated the timer on the atomic bomb.}
{124}{}{Repairing a warhead is pointless.}
{125}{}{Deactivating the timer is impossible.}

{505}{}{}
{506}{}{ seconds to detonation.}