{110}{}{This bomb can be very dangerous, but it lacks some components.}
{111}{}{This bomb is ready to explode.}
{112}{}{You have successfully installed the fuses.}
{113}{}{The bomb is ready to explode. Use the trap skill to activate it.}
{114}{}{Damn, this is the biggest bomb you can find.}
{115}{}{There's no need for that. The story has already gone according to the right scenario.}

{120}{}{This is a low-power nuclear warhead. Although it is not finished, it can still be blown up.}
{121}{}{This bomb is devoid of fuses, so it is safe at the moment.}
{122}{}{You have successfully activated the nuclear bomb timer.}
{123}{}{You have successfully deactivated the timer of a nuclear bomb.}
{124}{}{There is no point in repairing the warhead.}
{125}{}{It is impossible to deactivate the timer.}

{505}{}{Until the explosion left }
{506}{}{ seconds.}