{100}{}{You see the Adviser's computer.}
{101}{}{You see a powerful computer with a slot for an access card.}

#Dialog
{200}{}{Enter command.}
{201}{}{End session.}
{202}{}{Back.}

{210}{}{Alarm cancellation.}
{211}{}{The alarm is disabled.}
{212}{}{Disable traps in the corridor.}
{213}{}{The traps are deactivated.}

{220}{}{Sabotage in Flagstaff.}
{221}{}{(Flagstaff's agents report a sabotage in a uranium mine. Presumably, the sabotage was committed by prisoners. In any case, we should reconsider our policy regarding this colony and Mr. Faber's methods.)}

{230}{}{Old report on the Phoenix coup.}
{231}{}{(The adviser describes the details of the coup that happened a few years ago in Phoenix. It follows from the records that a certain third force established the power of the cult of Fire in the city, putting the people he needed. The goals of this unnamed organization are to form a society to create a subsequent raw materials and reconstruction base and to provide the general staff with basic resources. In other words, the cult of Fire is a puppet in someone else's game..)}
{232}{}{Financial report.}
{233}{}{Thanks to our systematic work, a new bottle cap currency borrowed from the Hub has firmly established itself in Phoenix. However since the residents were not used to such a currency, it took several years to instill this idea in the population and stabilize the exchange rate of caps. I attach to the report statistics and analysis of financial processes in the city and prospects for the development of the cap currency in the future.}

{240}{}{Report on the status of the cult.}
{241}{}{...Conclusion 1. As expected, the cult of Fire created on the model of the Chad Cathedral showed high results. He captured almost all spheres of life in the city and firmly established himself in his position. The population of Phoenix either remains loyal to the fire worshippers or is afraid of them. Thus, we can flexibly change the local society at our discretion by the Followers of Fire. Although the rebels hiding in the sewers are still causing problems, they do not pose a significant threat to our plan.}
{242}{}{Read more.}
{243}{}{Conclusion 2. We manage to remain incognito, limited only to a small circle of selected persons. The cult leader is ready to follow our instructions without question, regardless of his own ambitions. He is aware of his puppet nature and is ready to reckon with it, but he does not suspect our plans. Presumably, this relationship will continue for the next 3-4 years, after which it will be useful to eliminate Aaron and put in a new person.}
{244}{}{Read more.}
{245}{}{Conclusion 3. I think that the cult is ready to expand. We are starting the expansion of the ideas of the Sacred Fire in San Brahmin with the aim of organizing a new raw materials and transport colony there.}

{250}{}{GECK search report.}
{251}{}{Information about the current Generator of the Eden Tabernacles is still missing, the search continues. I have attached the expedition reports.}
{252}{}{Expedition to the Vault 26.}
{253}{}{The expedition to Vault 26 gave a negative result. The Vault was destroyed by a nuclear strike. Excavation is impossible.}
{254}{}{Expedition to the Vault 27.}
{255}{}{The expedition to Vault 27 could not confirm the presence of the GECK. Long-term excavations are currently underway. It is confirmed that the Vault has been looted and is in poor condition. Some equipment was taken out by convoy to Two-Sun, the list is attached. I also attached copies of the expedition reports.}
{256}{}{Remark.}
{257}{}{There is information that the population of Phoenix largely consists of descendants of the inhabitants of vault 27. And there is also a legend about the discord of their ancestors who went different ways. It can be assumed that one of the groups of immigrants took the GECK with them. This hypothesis should be worked out if we don't find the device.}
{258}{}{Search for the coordinates of the Vault 27.}
{259}{}{(You enter the coordinates in your Pip-Boy)}

{260}{}{Report on the nuclear bomb project.}
{261}{}{At the moment, the project is 92% ready. We are expecting new mechanical components from Two-Sun workshops. Progress is hindered by the lack of scientific personnel and the slowness of uranium production in the Flagstaff mines. The fire worshippers still have no idea about the true customer and the purpose of the bomb.}