{100}{}{You see the Advisor's computer.}
{101}{}{You see a powerful computer with a slot for an access card.}

#Dialogue
{200}{}{Enter command.}
{201}{}{Complete session.}
{202}{}{Back.}

{210}{}{Cancel alert.}
{211}{}{Alert signal disabled.}
{212}{}{Deactivate traps in the corridor.}
{213}{}{Traps deactivated.}

{220}{}{Flagstaff sabotage.}
{221}{}{(Agents in Flagstaff report that the uranium mine has been sabotaged. The operation was, presumably, conducted by the imprisoned. Regardless of the perpetrators, we should reconsider how we treat the colony and Mr. Faber's methods.)}

{230}{}{Old report about the Phoenix coup.}
{231}{}{(The Advisor describes the coup in detail. The coup happened a few years ago. The records say that some kind of third party established control over the city with the cult of the Holy Fire, by placing chosen individuals at the top. The goal of this organization, whose name is not mentioned, is to form a society that would serve as a "reconstruction and raw material extraction hub" which would also supply "headquarters" with "primary resources". In other words, the cult of the Holy Fire is nothing but a puppet controlled by an even larger, even more powerful organization...)}
{232}{}{Financial report.}
{233}{}{Thanks to our work, the bottlecap currency (borrowed from the Hub) has been firmly established in Phoenix. But considering the inhabitants aren't used to the idea of currency itself, it took a few years to make the population accept the system and to stabilize the cap rate. Attached to the report you will see a file containing statistics and an analysis of financial processes in the city, as well as opportunities to develop the bottlecap currency further.}

{240}{}{Report containing conclusions about the cult.}
{241}{}{...Conclusion 1. As was expected, the "Holy Fire" cult, based on the Children of the Cathedral, proved highly successful. It has a large presense in all activities being conducted in the city and has firmly established itself. The population of Phoenix has either become loyal to the cult members, or has begun to fear them. This way, the Followers can be used to shape local society as deemed necessary. Though the rebels hiding in the underground are causing slight complications, they do not represent a substantial threat to our plans in any way.}
{242}{}{[Continue reading]}
{243}{}{Conclusion 2. We are successfully maintaining anonymity outside a small circle of chosen individuals. The cult's leader is ready to follow our orders in spite of his personal ambitions. He undersands and accepts his role as a middleman, but does not suspect of our true plans. This state of affairs is likely to remain for approximately 3-4 years, after which it would be prudent to terminate and replace Aaron.}
{244}{}{[Continue reading]}
{245}{}{Conclusion 3. I consider the cult ready to expand. We will begin this in San Brahmin, with the goal of creating a new colony that will serve as a raw material extraction center and transportation hub.}

{250}{}{Report about seaching for the GECK.}
{251}{}{There is no information about a functional Garden of Eden Creation Kit at this time, though it is still being searched for. Included are reports regarding expeditions.}
{252}{}{Vault 26 expedition.}
{253}{}{Vault 26 expedition result: negative. Vault was found out to have been destroyed by an atomic blast. Excavation impossible.}
{254}{}{Vault 27 expedition.}
{255}{}{Vault 27 expedition result: inconclusive. Long-term excavation is currently being conducted. It has been confirmed that the Vault has been largely stripped of valuable items and is in a bad condition. A part of the discovered equipment has been shipped to Two Sun via convoy. Attached is the list of equipment and copies of expedition reports.}
{256}{}{Note.}
{257}{}{There is evidence that a large part of Phoenix's population can trace it's lineage directly to Vault 27. A legend has been recorded of the forebears breaking up into two groups and each heading their own way. It can be assumed that one of these groups, if it existed, took the GECK with them. We should research this possibility if we fail to acquire the device in other Vaults.}
{258}{}{Search for coordinates of Vault 27.}
{259}{}{(You enter the coordinates into your Pip-Boy)}

{260}{}{Report about the atomic bomb project.}
{261}{}{At this time, the project is 92% complete. We are awaiting new mechanical components from Two Sun. The lack of scientific personnel and the low productivity in the Flagstaff uranium mines are slowing down the project. The cult members do not know of the purpose and destination of the bomb, as considered necessary.}