{100}{}{You see a console.}
{101}{}{You see a prison block console. It can be used to control the force fields.}
{102}{}{Prison block force fields disabled.}
{103}{}{Insuffiently high clearance level.}

{200}{}{Enter command.}
{201}{}{Disable force field in chamber 1.}
{202}{}{Activate force field in chamber 1.}
{203}{}{Disable force field in chamber 2.}
{204}{}{Activate force field in chamber 2.}
{205}{}{Disable force field in chamber 3.}
{206}{}{Activate force field in chamber 3.}
{207}{}{Back.}
{208}{}{Complete session.}