{100}{}{You can see the console.}
{101}{}{In front of you is the console of the prison block. Force fields can be controlled through it.}
{102}{}{The force fields of the prison block are disabled.}
{103}{}{The security clearance level is not high enough.}

{200}{}{Enter command.}
{201}{}{Disable the force field of camera 1.}
{202}{}{Activate the force field of camera 1.}
{203}{}{Disable the force field of camera 2.}
{204}{}{Activate the force field of camera 2.}
{205}{}{Disable the camera's force field 3.}
{206}{}{Activate the camera's force field 3.}
{207}{}{Back.}
{208}{}{End session.}