{100}{}{This is a lab computer.}
{101}{}{Here is a laboratory computer.}

#Dialog
{200}{}{Enter the request.}
{201}{}{End session.}
{202}{}{Back.}

{210}{}{Copy geographical data.}
{211}{}{Geographical data has been successfully entered into the maps section of your Pip-Boy.}

{220}{}{Information about the Vault 25.}
{221}{}{The number of the Vault is 25. The start of construction is March 2064. Completion of construction - January 2068. Construction Contractor: Vault-Tec. The purpose is to protect civilians during a nuclear strike. The estimated number of inhabitants is 450. The duration of sealing is 15 years.}
{222}{}{The history of the asylum 25.}
{223}{}{During the Great War in 2077, the asylum was opened to ordinary citizens of Phoenix. However, the proximity and suddenness of the nuclear strikes forced the Vault workers to seal the armored door without waiting for the majority of the population. Thus, only 12% of the planned residents managed to get access inside.}
{224}{}{Next.}
{225}{}{The excess of resources and space allowed the survivors to live a happy and carefree life without ever coming to the surface. The discovery and colonization of the refuge was made by the expedition of Ulysses Grant in 2162.}
{226}{}{Characteristics of the inhabitants.}
{227}{}{The population of the Vault had excellent physical health, but weak endurance. The population is not adapted for heavy physical labor. Mental health in general remained good, although many suffered from phobias about the outside world.}

{230}{}{Medical experiments.}
{231}{}{The followers of Fire are conducting various medical experiments thanks to the perfectly preserved equipment of the Vault.}
{232}{}{Projects in development.}
{233}{}{Increased resistance to radiation; increased combat capability of guards with chemical agents; antivirus for "wasteland disease".}
{234}{}{Suspended projects.}
{235}{}{Standard Med-Tec vaccinations (due to lack of raw materials); Remote control of consciousness (due to lack of equipment).}

{240}{}{Affordable food project.}
{241}{}{Followers of Fire are conducting various research to solve the food problem in Phoenix. These are experiments on plants (the project has been transferred to the Casa Nueva department), mushroom and microbiological farms, the manufacture of new food processors in Two-Sun, research on the GECK technology.}
{242}{}{What else is GECK?}
{243}{}{The Eden Bushes Compact Generator is an ancient technology for restoring the earth after being hit by a nuclear strike. The technology turned out to be too complex to be repeated in the laboratory conditions of Vault 25. In search of a GECK worker, the Followers equipped expeditions to other Vaults.}
{244}{}{Expedition to the Vault 26.}
{245}{}{The Vault was destroyed by a nuclear strike, the GECK was not preserved.}
{246}{}{Expedition to the Vault 27.}
{247}{}{Excavations are currently underway under the direction of Arthur Carrington. The coordinates of the Vault are attached. The presence of the GECK in the Vault has not been confirmed.}

{250}{}{The project of a nuclear bomb.}
{251}{}{The production of a uranium bomb "Baby Phoenix" using raw materials from Flagstaff. Curator: Professor Zach Zimmer. Completeness: 92%.}
{252}{}{Disable the force field in the section with a nuclear bomb.}
{253}{}{The force field is deactivated.}

{260}{}{Reports on the supply of uranium and slaves.}
{261}{}{(The usual quarterly routine is described here. Uranium from Flagstaff and slaves from all over the region are partially used by the cult at its discretion, and partially transported by convoy to the south via Two-Sun)}
{262}{}{Search for information about slaves from the Villa.}
{263}{}{(You find data on several prisoners from the Villa. Alas, they have already been sent to Two-Sun.)}