{100}{}{You see a lab computer.}
{101}{}{You see a computer made for research purposes.}

#Dialogue
{200}{}{Enter command.}
{201}{}{Complete session.}
{202}{}{Back.}

{210}{}{Copy geographical data.}
{211}{}{Geographical data successfully added to your Pip-Boy's map folder.}

{220}{}{Information about Vault 25.}
{221}{}{Vault number - 25. Beginning of construction - March 2064. End of construction - January 2068. Construction contractor: Vault-Tec Industries. Purpose - protection of civilian population during nuclear war. Estimated number of inhabitants - 450. Duration of sealing - 15 years.}
{222}{}{Vault 25's history.}
{223}{}{During the Great War of 2077, the Vault was open for Phoenix's regular inhabitants. However, the close-by and unexpected nuclear blast forced the workers to seal the Vault door without the majority of the population having made it inside. Thus, only 12% of the registered inhabitants could get into the Vault.}
{224}{}{Continue.}
{225}{}{An excess of resources and space allowed those inside to lead carefree and hedonistic lives without ever going to the surface. The 2162 expedition, carried out by Ulysses Grant, managed to successfully unseal and colonize the Vault.}
{226}{}{Characteristics of inhabitants.}
{227}{}{The Vault's population was of excellent physical health, though had little endurance. The population was incapable of hard physical labor. Mental health largely good, though many posessed agoraphobia.}

{230}{}{Medical experiments.}
{231}{}{The Followers of the Fire are conducting various medical experiments thanks to the very well-preserved Vault equipment.}
{232}{}{Projects currently in development.}
{233}{}{Increased body resistance to radiation; increasing the security team's combat potential with chemical means; cure for "wasteland illness".}
{234}{}{Suspended projects.}
{235}{}{Standard Med-Tec vaccinations (due to lack of raw material); remote consciousness control (due to lack of equipment).}

{240}{}{Accessible nutrition project.}
{241}{}{The Followers of the Fire are conducting various studies with the goal of putting an end to the food problem in Phoenix. These include experiments on plants (project relocated to Casa Nueva), fungi and microbiological farms, creation of new food processors in Two Sun, research concerning the GECK technology.}
{242}{}{Define "GECK".}
{243}{}{The Garden of Eden Creation Kit is an ancient terraforming technology made to restore the biosphere after it's destruction during an atomic war. The technology has turned out to be too complex for it to be recreated in Vault 25's laboratory conditions. The Followers are sending expeditions to other Vaults in order to find a functional GECK unit.}
{244}{}{Vault 26 expedition.}
{245}{}{Vault destroyed by an atomic blast. GECK unit did not survive.}
{246}{}{Vault 27 expedition.}
{247}{}{Excavation is currently being conducted, with Arthur Carrington in charge of the operation. Attached are the Vault's coordinates. GECK presense in the Vault unconfirmed.}

{250}{}{Atomic bomb project.}
{251}{}{The creation of a uranium bomb "Baby Phoenix" using raw material from Flagstaff. Curator: professor Zack Zimmer. Total completion status: 92%.}
{252}{}{Disable force field preventing access to the room in which the atomic bomb is located.}
{253}{}{Force field deactivated.}

{260}{}{Report about uranium and slave deliveries.}
{261}{}{(A typical quarterly routine is described here. The Flagstaff uranium and slaves from the entirety of the region are partly used by the cult for their own ends, and partly delivered to the southern Two Sun settlement by convoys)}
{262}{}{Find a report about slaves from Villa.}
{263}{}{(You find data about some captives from Villa. Alas, they have already been sent to Two Sun.)}