{102}{}{You have filled a container with synthetic raw materials.}

{200}{}{Enter command.}
{201}{}{Complete session.}
{202}{}{Check for presense of synthetic material.}

{210}{}{Synthetic raw material cartridge empty.}
{211}{}{Synthetic raw material cartridge at }
{212}{}{% capacity.}
{213}{}{Fabricate Vault jumpsuit (spend 25% of material).}
{214}{}{Fabricate Fire-worshipper robes (spend 50% of material).}
{215}{}{Done.}