{102}{}{You have filled a container with synthetic raw materials.}

{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Check for synthetic material.}

{210}{}{Cartridge of synthetic material let.}
{211}{}{The cartridge of synthetic material is filled with }
{212}{}{%.}
{213}{}{ To make a overall of Vault (consumption of 25% of the material).}
{214}{}{To make a cassock of Followers of Fire (consumption of 50% of the material).}
{215}{}{Done.}