{100}{}{You see a settler.}
{101}{}{Here is an ordinary resident of the Aqueduct.}

{110}{}{I need to rest.}
{111}{}{I need to check the networks tomorrow morning.}
{112}{}{Hr-r-r}
{113}{}{It's too late to talk.}
{114}{}{What's going on?}
{115}{}{Why the hell are you waking people up in the middle of the night?}
{116}{}{You'll wake me up in the middle of the night again...}
{117}{}{}
{118}{}{}
{119}{}{}

{120}{}{Everyone here already knows about you. Get out.}
{121}{}{People like you don't belong here.}
{122}{}{We know what kind of person you are. Such people don't belong here.}
{123}{}{Get out of here.}
{124}{}{Get out before the Rangers hang you from a tree.}
{125}{}{Garth will knock the brains out of you if you bother the locals.}
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

{130}{}{Welcome to the Aqueduct.}
{131}{}{I hope you'll be here for a while.}
{132}{}{Hey, hi.}
{133}{}{Glad to see you.}
{134}{}{Do you want to stay overnight?}
{135}{}{I have a free seat, don't be shy.}
{136}{}{Did the Rangers send you?}
{137}{}{People like you are appreciated here.}
{138}{}{Will you help me with cleaning up the networks?}
{139}{}{We need people like you here.}

{140}{}{Sorry, new people always arouse suspicion.}
{141}{}{What do you want?}
{142}{}{Look, I don't know anything and I don't have anything. Understand?}
{143}{}{Better leave me alone.}
{144}{}{Today was a hard day, we'll talk later.}
{145}{}{I have to go through the nets all day.}
{146}{}{Smell? It's from fish and from water. We are already used to it.}
{147}{}{Somewhere at the bottom of Colorado lives an Arizona Monster.}
{148}{}{Don't swim too far, there's an Arizona Monster in the water.}
{149}{}{There was no catch today.}