{100}{}{You see a child.}
{101}{}{Here is a local child. He smells of fish and mud.}
{102}{}{Thank you, mister! I'll need it.}
{1102}{}{Thank you, miss! I'll need it.}
{103}{}{Thank you, mister. But I already have a pair of sandals.}
{1103}{}{Thank you, miss. But I already have a pair of sandals.}
{104}{}{It was very noble of you.}

{200}{}{I saw them! I'm telling you! It's true! Ouch... Who else are you? Also an alien?}
{201}{}{Who did you see?}
{202}{}{Who are you calling an alien, little guy?}
{203}{}{Monsters! They live in an aqueduct and crawl out at night. I saw it myself! Now it is clear why it is forbidden to descend into the aqueduct. There must be a whole pack of these monsters living there.}
{204}{}{Hmm-m.}
{205}{}{Yes, you're all lying.}
{206}{}{I told you, I saw them! They are bald and disgusting, they make some strange noises with their noses. What if they come to the surface and attack us? Eh?}
{207}{}{Calm down, nothing will happen if you don't go to them yourself.}
{208}{}{That's for sure. What are the local authorities thinking about?}
{209}{}{Well... Honestly, I don't know. Maybe Garth has a plan. He's cool. I even saw him go down into the aqueduct himself. Garth is not afraid of anything. He will protect us from any enemies!}
{210}{}{By the way, what were YOU doing at the aqueduct?}
{211}{}{Well... this... I was walking. But you can't walk there, so I was punished and forced to sort through the seaweed nets. Be-e, they are so dirty.}
{212}{}{Did you find anything interesting?}
{213}{}{Nope. Although... Do you need ammo? I found them near the aqueduct. Probably, one of the hunters dropped it. I can exchange it for something useful.}
{214}{}{I'll keep that in mind.}
{215}{}{No need, surely these cartridges are damp.}
{216}{}{Judging by your bare feet, you will need any things.}

{220}{}{I saw them! I'm telling you! It's true!}
{221}{}{I believe you. Later.}

{230}{}{Is that why you go barefoot?}
{231}{}{Well yes. As soon as I saw these monsters, I immediately ran here. I ran so fast that I didn't notice how I tore my sandals. Now we'll have to find a replacement for them.}
{232}{}{So did you find anything interesting while walking by the aqueduct?}