{100}{}{You see a child.}
{101}{}{Here is a local child. He smells of fish and mud.}

{110}{}{Garth Ranger. He kills people like you.}
{111}{}{Don't touch me.}
{112}{}{What kind of hole are you from, huh?}
{113}{}{You're talking strangely..}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{* Yawns*}
{119}{}{Z-z-z}

{120}{}{Are you here for a long time?}
{121}{}{Where are you from?}
{122}{}{Do you want to play?}
{123}{}{Do you know interesting places around?}
{124}{}{A monster lives at the bottom of the bay.}
{125}{}{If you swim in this water, horns will grow.}
{126}{}{Do you have anything delicious?}
{127}{}{Be, this fish is rotten.}
{128}{}{I'm looking for something useful.}
{129}{}{}

{130}{}{It's called a motorcycle, right?}
{131}{}{Wow, does this thing really know how to drive itself?}
{132}{}{So do you also command old technology, like old Rufus?}
{133}{}{Can you ride this motorcycle?}
{134}{}{Can this bike catch fish or predict the weather?}
{135}{}{In my opinion, the Rangers should also get themselves motorcycles.}
{136}{}{Where did you get a motorcycle from?}