{100}{}{You see a stranger.}
{101}{}{Here is a boy in worn-out clothes.}
{102}{}{Good luck. I'm leaving the Aqueduct soon. I'll try to find a place to live upstream of Colorado.}
{103}{}{What happened... in that water...}
{104}{}{Ah-x...}

#Dialog
{200}{}{Uh, hello?}
{201}{}{I'm new here. Looking for dating.}
{202}{}{That's how... great. I'm new here too. And I'm not lucky at dating.}
{203}{}{Did something happen?}
{204}{}{I came with two friends, but they disappeared, and the locals don't want to do business with me. Now I'm sitting by the fire, fishing and thinking about the future.}
{205}{}{A sad story. I'm sorry.}
{206}{}{The distrust of the locals is understandable.}

{210}{}{What do you want?}
{211}{}{Nothing. So far.}
{212}{}{Well, how's the search going?}
{213}{}{Sorry, but I haven't been able to find out anything yet.}
{214}{}{Hello.}
{215}{}{Later.}

{220}{}{What about the Rangers? They can't find your group?}
{221}{}{I talked to Garth, he's kind of the sheriff here. But it doesn't look like he's doing anything. And what can he do? I've already interviewed the locals myself, no one knows anything.}
{222}{}{Where are you and your band from?}
{223}{}{We fled from a small village far from here when life there became unbearable. We were told that the Rangers were ready to take everyone under their protection. Although it doesn't look like we're welcome here.}
{224}{}{I'll look for your people and if I find out something, I'll let you know.}
{225}{}{Thank you. Tell me everything you find out.}
{226}{}{Bye. See you later.}

{230}{}{I managed to find your friends... at the bottom of the aqueduct.}
{231}{}{They're dead, aren't they? Damn... Now I understand why Garth forbids going to that ancient structure. Surely we're not the first ones he and his henchmen have killed. Damn Rangers...}
{232}{}{What are you going to do now?}
{233}{}{I would like to take revenge on this bastard so that history does not repeat itself. But this way I will only make enemies for myself. In any case, I can't stay here.}
{234}{}{How about a report to the base? I don't think the command is aware.}
{235}{}{They won't let me see the commander, I've already tried. Can you do it? If Garth is not stopped, he will continue to eliminate all objectionable.}
{236}{}{I will try to reach the general. Although it won't be easy.}
{237}{}{You're a wonderful person. Thank you.}
{238}{}{Wait for news, man.}
{239}{}{Go to hell, I'm already up to my ears in shit because of you.}
{240}{}{Of course, forget it. I'll just walk out of here, and Garth will go unpunished... yes. It's BETTER this WAY.}
{241}{}{Just don't put pressure on my feelings! Adios, man.}
{242}{}{Let's just kill Garth? It will be easier and more fun.}
{243}{}{Finish off a ranger and end up on the list of criminals? Damn, I don't want to run away from the Rangers for the rest of my life. It's better if I just leave here.}
{244}{}{Well, have a good trip, man.}

{250}{}{Ranger Garth got what he deserved. Your friends are avenged.}
{251}{}{Yes... although it won't bring them back. You know, we're actually friends rather by misfortune. A lot happened along the way. We had to rob travelers and small settlements. Only here we felt part of something and were able to live a normal life. Even despite the distrust of the locals. But this ranger ruined everything.}
{252}{}{Yeah. It's a pity that this happened.}
{253}{}{He was not far off in his doubts about your gang.}
{254}{}{Thanks for everything. Take these cartridges. To be honest, I stole them from the Rangers, it would be fair to give them to you as a reward. And it's time for me to hit the road. There will be no life for me here.}
{255}{}{Have a safe journey.}