{100}{}{You see a settler.}
{101}{}{Here is an ordinary resident of the Aqueduct.}

{200}{}{Is it too late for a visit?}
{201}{}{I'm just...}
{202}{}{Away! Away!}
{203}{}{Okay, man. We'll talk in the afternoon.}

{210}{}{Eh? I don't have time to talk. You should talk to Garth or one of the local bums.}
{211}{}{Eh? I don't have time to talk. Find someone who has nothing to do.}
{212}{}{I had no idea that Garth was behind all these disappearances. Now I understand why he forbade meddling in the catacombs of the aqueduct. But on the other hand, who will protect us from unwanted roommates now?}
{213}{}{Hey, Ranger. How are you?}
{214}{}{Goodbye.}

{220}{}{What are you doing?}
{221}{}{I'm getting ready for a big fishing trip on the reservoir. And this is a troublesome business, you know.}
{222}{}{Who built this aqueduct?}
{223}{}{To be honest, I don't know myself. Perhaps it was the Rangers themselves. In any case, these structures have been standing here since time immemorial.}
{224}{}{What do you think about Garth?}
{225}{}{A good man, solid and incorruptible. He stands behind our people like a mountain and has helped many times in protecting them from bandits, robbers and animals. He lives in the house opposite.}
{226}{}{How do you live in these parts under the protection of rangers?}
{227}{}{Life is great. The Rangers protect us from bandits and beasts. And we pay them for it with part of our food. I have no complaints against the Rangers.}
{228}{}{What do you know about the disappearances of people?}
{229}{}{Obviously, they were animals. Along the river valley there are wolves and vile pig rats. And outsiders often do not know about this danger.}
{230}{}{They say you have an epidemic here?}
{231}{}{Yes, suddenly several people have come down with a fever. Some managed to recover, and some are still suffering from extreme heat. In the hut opposite, one is suffering right now.}

{240}{}{The Garage City community sent me. There is an acute shortage of food.}
{241}{}{Hmm. They say this city is full of specialists in working with iron. And we just need parts at least for boat repairs. But they also say that the residents are not particularly friendly to the rangers. The problem of hunger there must be really terrifying if they are ready to "give up".}
{242}{}{Do you agree?}
{243}{}{I have yet to convince the Rangers to give their consent for the trade. But this case smacks of too much profit, they are unlikely to refuse. Yes, I would send a caravan with dried fish to this disgusting and smelly town.}
{244}{}{People are starving in the Garage, and you're already rubbing your hands in anticipation of the benefits. Think about it.}
{245}{}{OK, I'll give your consent to Garage City.}