{100}{}{You see Keel.}
{101}{}{You see a guy in a leather jacket. He defiantly plays with his spear.}
{102}{}{Everyone will be better off if you leave.}
{103}{}{Uh... I think I've had too much...}

{110}{}{What do you need, huh?}
{111}{}{Don't offend the locals.}
{112}{}{I don't know you.}
{113}{}{Go where you're going.}
{114}{}{Only normal people get along in the Aqueduct.}
{115}{}{I don't think you'll find a place to sleep here.}
{116}{}{Thieves get their hands chopped off here. It's just by the way.}

#Dialog
{200}{}{Wait. What are you doing here?}
{201}{}{None of your business.}
{202}{}{You're wrong. And you will pay dearly for this mistake...}
{203}{}{Hey, stop...}
{204}{}{Just try it.}
{205}{}{There are corpses of people below. Do you know anything about it?}
{206}{}{Oh, yeah. These must be the idiots who were forbidden to meddle in the aqueduct. They didn't listen. Just like you.}
{207}{}{They were killed. And not a beast, but a man.}
{208}{}{Wow, and you are a master of guesswork. And what are you going to do now?}
{209}{}{I'll kill everyone involved in this. And it looks like you're one of them.}
{210}{}{Garth warned me you were dangerous. Come on, stranger, try it.}
{1210}{}{Garth warned me you were dangerous. Come on, stranger, try it.}
{211}{}{Hmm...}
{212}{}{Actually, I'm here by accident. Why don't I just leave and we'll forget about everything?}
{213}{}{Are you really such a naive fool? Garth ordered me to kill you if you got wind of anything. Sorry, nothing personal...}
{1213}{}{Are you really such a naive fool? Garth ordered me to kill you if you got wind of anything. I'm sorry, nothing personal...}
{214}{}{Wait, I don't want a fight...}
{215}{}{You leave me no choice.}
{216}{}{Are you seriously counting on me to cope with one spear?}
{217}{}{This spear has saved my life more than once. Do you want to check it out?}
{218}{}{Oh, it will be interesting. Give me a performance...}
{219}{}{Then you should know that my location is known at Ranger headquarters. No one will leave this so easily. Do you want problems?}
{220}{}{No... I don't want any problems. But they will be when Garth finds out.}
{221}{}{I can stop it. Garth has crossed a line that a ranger cannot cross. Don't you understand?}
{222}{}{To hell with it. It's useless to talk to you. Let the battle determine the right.}
{223}{}{Now I understand that you pose a great threat to our peaceful town. Garth didn't just kill all these scum from the wasteland. We don't need people like you. Go to hell, you creature...}
{224}{}{It's a pity we didn't...}
{225}{}{So Garth is behind all this? We have to stop him. He's crossed a line that a ranger can't cross. You understand that, don't you?}
{226}{}{Garth is going crazy. He's too suspicious. First he got rid of those who were creating problems. And now - from any newcomers that he doesn't like. I agree, this has gone too far. I hope you know what to do.}
{227}{}{Thanks, I'll figure it out. You're a good guy.}
{228}{}{However, I don't trust you. It would be better to eliminate you right now...}
{229}{}{I'll have to tell Ranger headquarters about it.}
{230}{}{Garth told me to kill you if you got wind of anything. Sorry. Nothing personal...}
{231}{}{Are you going to kill a ranger?}
{232}{}{I have no choice. Garth ordered me to stop you. If I don't, it will be bad for all of us.}
{233}{}{Well. You're just a fool. And you will die a fool...}
{234}{}{Are you really going to kill a lady? How cruel you are!}
{235}{}{Damn, I don't raise my hand against women. But what can I do? Garth won't forgive mistakes, and you shouldn't have meddled in your own business...}
{236}{}{So come on, animal, take a chance to do your dirty work.}

{240}{}{What the... Look, I don't want to fight you. But Garth ordered you to be stopped.}
{241}{}{Right. Your spear can't penetrate the power armor. It's nice to hear the voice of reason.}
{242}{}{What are you going to do? Are you going to kill us all or hand us over to the authorities?}
{243}{}{Oh yes. And you will be the first...}
{244}{}{First tell me what happened. There are corpses of people below. And they were not killed by a beast.}
{245}{}{Garth gets rid of strangers who, in his opinion, are not worthy to live here. At first, he solved real problems in this way. But now something has broken in him, he puts anyone who arouses suspicion under the knife.}
{246}{}{What a disgusting story. I will rid the world of the likes of this Garth and you...}
{247}{}{Do you go to his sixes? Listen, we have to stop him.}
{248}{}{I'm just doing his dirty work for him. I hope you know what to do.}
{249}{}{Sit here and keep your head down. You're lucky if the Rangers' trial is fair.}
{250}{}{I know. I'll kill him and you. And you will be the first.}

{260}{}{Wait, you freak. It's obvious from you that you love every sewer. What are you doing here?}
{1260}{}{Wait, ugly. It's obvious from you that you love every sewer. What are you doing here?}