{100}{}{Here is Ranger Agatha.}
{101}{}{You see a veteran ranger in combat armor.}
{102}{}{Great armor. I'm almost jealous.}

#The first dialog
{200}{}{It's better for civilians not to wander around the base doing nothing. Have a question? Then contact the information center. It's that barrack over there by the road.}
{201}{}{I know.}
{202}{}{At ease, Ranger. It's nice to see you in our citadel. Feel free to ask questions.}
{203}{}{Thank you, Captain.}
{204}{}{Attention, Ranger! Address me according to the regulations or go to all four sides. I don't have time for an ass like you.}
{205}{}{Looks like my reputation pisses you off. Let's talk?}
{206}{}{(In front of you is a strong woman in combat armor. Her strict army look is emphasized by a short standing haircut and a rough voice)}
{207}{}{May I apply?}

#Repeat dialog
{210}{}{What do you want, wanderer?}
{1210}{}{What do you want, wanderer?}
{211}{}{What do you want, Ranger?}
{212}{}{Later.}

{213}{}{Oh... (studies your ghoulish appearance in dismay) You... Are you sick of anything? Look, don't infect anyone here.}
{214}{}{Don't worry about that.}

{220}{}{So it was you who excited the cadets with your bike? Where did you get it from?}
{1220}{}{So it was you who excited the cadets with your bike? Where did you get it from?}
{221}{}{This is a trophy.}
{222}{}{A thing obtained by blood in battle is worthy of respect. (proudly adjusts his armor)}
{223}{}{I should have expected you to like it.}
{224}{}{Gift.}
{225}{}{Well, if you say so, it remains to believe.}
{226}{}{Yeah.}
{227}{}{And you wouldn't mind a ride with me, baby?}

#Questions
{230}{}{Let me ask you a couple of questions about yourself.}
{231}{}{My name is Agatha, I am the curator of the training team.}
{232}{}{}
{233}{}{}
{234}{}{It seems that for you the Rangers are like a big family, and the cadets are like children.}
{235}{}{You could say that. But my personal motives don't matter when it comes down to it.}
{236}{}{Let me ask you a couple more questions.}
{237}{}{Where did you get this battle armor from?}
{238}{}{A trophy obtained during one of the combat operations. I had to repaint it so that they wouldn't take it for an outsider.}
{239}{}{And what do these stripes mean?}
{240}{}{Veteran service, son. When a ranger has been doing justice in the Wastelands long enough and successfully enough, he is given such a badge of distinction. And my experience counts for years.}
{241}{}{What are you doing here?}
{242}{}{Lately I've been teaching a young fighter course for cadets.}
{243}{}{A veteran messing with brats?}
{244}{}{I shot mine. It's time to pass the skills to the young.}
{245}{}{Why did you shave all the cadets bald?}
{246}{}{So that people like you ask a question. And to suppress the excessive tendency of young people to self-love.}
{247}{}{Psychological suppression of personality? Clever.}
{248}{}{Not suppression. And the inoculation of perseverance and self-control. In addition, it is useful for hygiene.}
{249}{}{Okay, I won't argue.}

#Training
{250}{}{Can I get training?}
{251}{}{Maybe I should give you a minigun right away? We only teach our cadets. I don't remember you being included in their list.}
{252}{}{Then let's go.}
{253}{}{Not only can you, but you also have to. However, I was warned about your special status. I'll have to conduct a compressed course of a young fighter.}
{254}{}{I think I'm ready to take the course.}
{255}{}{Great, but let's postpone the training, now I have other responsibilities.}
{256}{}{Let's see. The basics of survival are the first thing any ranger needs to master.}
{257}{}{OK.}
{258}{}{Next, weapon skills. We will touch on each species a little, but any ranger has personal preferences in choosing weapons. What do you choose?}
{259}{}{}
{260}{}{Shooting from revolvers (light weapons).}
{261}{}{Sniper fire (heavy weapons).}
{262}{}{Ranger Throw (throwing weapon).}
{263}{}{Fight with improvised means (hand-to-hand combat).}
{264}{}{Knife fight (cold weapons).}
{265}{}{Okay, Ranger! Run to the parade ground! Let's see what you have enough for.}
{266}{}{There is!}

#Personal history
{270}{}{How did you become a ranger?}
{271}{}{Tell me, how did you become a ranger?}
{272}{}{I am no longer the little girl to whom you can ask personal questions.}
{273}{}{Okay, got it, no problem.}
{1273}{}{Okay, got it, no problem.}
{274}{}{Then I want to know too.}
{275}{}{Are you really interested? It's an old story. I was a child when our camp was attacked by bandits...}
{276}{}{Go on.}
{277}{}{Uh, not now, we'll finish it another time.}
{278}{}{I managed to hide in the ruins and wait out the siege. When the bandits finished their work, no one was left alive.}
{279}{}{Wow, that's a sad story.}
{280}{}{It's perfectly reasonable to sit in a dark corner when you can't do anything.}
{281}{}{At first I was confused. And then I got angry and promised that I would avenge my family.}
{282}{}{Did you succeed?}
{283}{}{Revenge on the whole gang? You don't have to have brains to decide on such a thing.}
{284}{}{I went to the wastelands and honed my skills, searched for weapons and supplies, studied the terrain and eventually killed all the bandits one by one in their lair. It took a long time.}
{285}{}{Destroying a gang with traps and tricks alone is something incredible.}
{286}{}{Pf, traps for weaklings. However, you were a teenager...}
{287}{}{But after all this suffering, I realized that murder remains murder. The Wastelands don't need a man with a rifle, but law and order. And only the Rangers shared the same views. After the story with the bandits, I was accepted into the cadets without further ado.}
{288}{}{That's the story.}
{289}{}{Familiar story. One of my friends also hid from the raiders. The community has not forgiven him for this.}

#Cadet Presley
{300}{}{Why aren't you letting Cadet Presley on a mission?}
{301}{}{Even if he is ready to hold a rifle in his hands, he needs to be knocked down a little arrogance. This applies to many cadets.}
{302}{}{So he's too wayward?}
{303}{}{Rather ambitious and impatient. Such rangers don't live long and usually end up pretty badly.}
{304}{}{Maybe you're just pushing him?}
{305}{}{Should I kiss his ass? So you can't make warriors out of teenagers. If he can't handle this pressure, then he won't be able to be a full-fledged ranger.}
{306}{}{Why not let him prove himself?}
{307}{}{I would let him go so that he would finally come to his senses and open his eyes to the world. But I can't change my mind in front of the other cadets, so as not to lose my reputation. Do you understand?}
{308}{}{You know better how to educate cadets. And I have to go.}
{309}{}{Then let him go with me under the pretext of an escort. I also have an interest in this.}
{310}{}{I don't understand why you should mind your own business. But maybe it's even for the best. I will assign Presley to accompany you and order him to return his equipment.}
{311}{}{Great, I'll go make him happy.}
{312}{}{That would be right away.}
{313}{}{Where is Cadet Presley? You're the last person he was seen with.}
{1313}{}{Where is Cadet Presley? You're the last person he was seen with.}
{314}{}{He died in the line of duty.}
{315}{}{Damn it! Why did I trust such an idiot! Get out, otherwise I can't vouch for myself!}
{1315}{}{Damn it! Why did I trust such an idiot! Get out, otherwise I can't vouch for myself!}
{316}{}{Er...}

{320}{}{Do you know that the quartermaster has lost a weapon from the warehouse?}
{321}{}{Yes. And of course you're trying to figure this shit out, right? But you know what, it's time for this junk keeper to clean up his dark, dusty storerooms. Because I don't believe my cadets could have stolen anything.}
{322}{}{[Next]}
{323}{}{And I won't let anyone blame them. Do you understand that? And now I need to continue training.}
{324}{}{Of course, no problem.}
{325}{}{Well, well.}