{100}{}{Here is a woman.}
{101}{}{You see a middle-aged woman. She is exhausted from a long journey.}
{102}{}{May luck accompany you.}
{103}{}{Bastards!!! What would you all die!}
{104}{}{It's over... Leave me, let the wolves eat me.}

#Dialogue on the Ranger map
{200}{}{Hey, you! Call the general immediately!}
{201}{}{Woman, stop yelling, you can be heard well enough.}
{202}{}{You're confusing something, I'm here in passing.}
{203}{}{Yes, of course, also tell me that you don't serve the damn rangers! In these lands, even coyotes suck up to those who are stronger.}
{204}{}{Did the Rangers annoy you somehow?}
{205}{}{That's not the word! And I'm not going to let it go that easily. If the general doesn't come out here to answer, I'll fight my way to him myself.}
{206}{}{You again? If you don't want to help, then you'd better disappear from my eyes.}
{207}{}{Stay here, I'll talk to the Rangers.}
{208}{}{Tell me what happened.}
{209}{}{These "defenders of the law" executed my husband and left me and my child to the mercy of the desert. We miraculously managed to survive the way here.}
{210}{}{Was he guilty?}
{211}{}{Guilty? Yes, everyone in the wastelands is guilty of a variety of atrocities, if you follow the stupid law that the rangers cherish so much. But this does not mean that now we have to execute everyone in a row!}
{212}{}{Eh, I understand what you want to say.}
{213}{}{Why do you need a general?}
{214}{}{To look him in the eye. He may not know what his henchmen are doing, but I will still make him answer for their mistakes and pay me compensation.}
{215}{}{A bold decision.}
{216}{}{Is that all you wanted to ask?}
{217}{}{Is this your baby?}
{218}{}{Yes. What's it to you?}
{219}{}{I was just curious. Forget.}

{220}{}{You can't stay here. The Rangers do not want to take you under protection, and your reputation will not allow you to settle in neighboring settlements.}
{221}{}{I know! But where do we go now? There is a desert around, we will not survive another such trip. However, you can try to go to California... This is the only way out. But the Rangers blocked the only crossing of the river!}
{222}{}{They say there is a ferry downstream. But it's not a safe place.}
{223}{}{Exactly. I don't even have a gun to protect me from wolves and pig rats. I can't get to the ferry with my child without help.}
{224}{}{I'll accompany you. Get ready to ship.}
{225}{}{I'll accompany you. But not right now.}

{226}{}{The guards are dead.}
{227}{}{I see, but it doesn't change anything. We can't get to the General anyway. There are also a lot of rangers inside the dam. We won't even be able to approach the citadel on the other side of the dam. We will either be shot by snipers or caught by patrolmen.}
{228}{}{The General is dead.}
{229}{}{Are you sure you know that? Is this not a trick? However, I have already heard this news. It looks like he really gave up the ghost. Great. I feel better. But I don't understand what to do now.}

{230}{}{Hey, traveler. You're trying to escape from this hell too, right?}
{1230}{}{Hey, wayfarer. You're trying to escape from this hell too, right?}
{231}{}{What are you talking about?}
{232}{}{Maybe.}
{233}{}{The Rangers have ruined our family's life. I don't want to tell you the details. After all, they already got what they deserved, if you look at this dam.}
{234}{}{[Next]}
{235}{}{Hmm, you don't look like a dangerous person. We have to stick together. Will you help me get to the other side? There is a ferry downstream, but I'm afraid to go there without an escort. They say there are wolves in those places.}
{236}{}{Okay, I'll escort you. We're leaving right now.}
{237}{}{I can't help you. Maybe later.}
{238}{}{Have you changed your mind after all? Come with us. Why do you need these desolate lands? In California, you can forget about the past and start all over again.}
{1238}{}{Have you changed your mind after all? Come with us. Why do you need these desolate lands? In California, you can forget about the past and start all over again.}
{239}{}{[Next]}
{240}{}{You know, I don't get along with the Rangers either.}
{241}{}{Is that supposed to make me feel better? Hmm. Listen, since we're in the same boat, then we should help each other to survive.}

#On the ferry map
{300}{}{Let's talk when we get to the ferry. Now we can attract wolves with our voice.}
{301}{}{You're right, let's put aside talking for now.}
{302}{}{I see.}

{303}{}{I don't like the way you look at the baby. Don't try to scare him, otherwise you won't see anything else for the rest of your life.}
{304}{}{I had no such thoughts!}
{305}{}{It's not in your best interest to threaten me, woman.}

{310}{}{What's your name, woman?}
{311}{}{My name is Cecilia, and this is my son.}
{312}{}{Your son has different facial features.}
{313}{}{Because he's adopted. I found it in the ruins and couldn't get past it.}
{314}{}{Was your husband really a criminal?}
{315}{}{I didn't ask where he gets his food and things from. But it was obvious that he was robbing travelers and farmers. So he protected the family. We had to survive somehow. It was worse in Phoenix, he was forced to do much dirtier work.}
{316}{}{Have you escaped from Phoenix?}
{317}{}{Yes... A big city. A lot of people, few resources. On the wastelands you are honest with fate, but in the city you always have to be on someone's side and fulfill someone's whims.}
{318}{}{Do you hate Rangers now?}
{319}{}{Of course.}
{320}{}{They try to make sure that there are no stories like yours.}
{321}{}{But it happened. It's their fault. You can't fix it.}
{322}{}{In my village, this would not be approved either.}
{323}{}{Hmm, in our Villa, every peasant also stands below the community and fulfills its whims. But it's not the same thing.}
{324}{}{This is commendable.}
{325}{}{I should have warned you in advance.}

{330}{}{The ferry is ready to depart. Get on the platform, I'll ferry you.}
{331}{}{I am immensely grateful to you. Not everyone would help us, especially in the Ranger lands. But what about you? Will you come to California with us?}
{332}{}{I can't yet. I have obligations to my family and home.}
{333}{}{That's how. It's not often that you find communities so strong that someone owes them something. Then good luck to you. Thanks for everything.}
{334}{}{[Next]}
{335}{}{I wish I had something to thank you for. But if you find yourself in Phoenix, tell the bartender at the casino about me, maybe he'll give you a discount. And now goodbye.}
{336}{}{[Send the family to the other shore]}