{100}{}{Here is a Ranger general.}
{101}{}{You see a strong gray-haired old man who has seen life in all its manifestations.}
{102}{}{I'm used to talking to real people, not robots. Do you understand?}
{103}{}{Goodbye, Ranger. Your ideals have turned out... not viable.}
{104}{}{Sorry, but this lady needs to cool down a bit.}
{105}{}{Glad to see you in good health. But I'm not in the mood to talk right now-the evil sown by the Brotherhood still glows in the wastelands.}

#The first dialog
{200}{}{I was informed that a certain peasant was seeking a meeting with me on an important issue. But usually scouts and ambassadors are engaged in external contacts. So I hope it's really something important?}
{1200}{}{I was informed that a certain peasant woman was seeking a meeting with me on an important issue. But usually scouts and ambassadors are engaged in external contacts. So I hope it's really something important?}
{201}{}{[Next]}
{202}{}{So, why are you here?}
{203}{}{You know, now I understand that I have nothing to do here. It was a mistake. I will leave, and you will forget about me.}
{204}{}{This joke sounds ridiculous.}
{205}{}{I'm serious. Sorry to bother you.}
{206}{}{You know, I have a lot of questions for you.}

#Repeat dialog
{210}{}{I'm listening.}
{211}{}{Goodbye.}
{212}{}{Good heavens, judging by your appearance, you've taken a lot of heat by the ruthless Wasteland. I'm really sorry.}
{213}{}{Thank you, General, for your kind words. Most would just send me away.}
{214}{}{I don't need pity. Look at yourself, old man.}
{215}{}{Report, Ranger.}

#The criminal's family
{220}{}{One angry woman demanded your meeting.}
{221}{}{Yes, I was informed. I endlessly sympathize with such people, but nothing can be done. Families of criminals have always been branded, even in the Old World.}
{222}{}{There must be a way to resolve the conflict.}
{223}{}{Me сomming out won't change anything. This woman will always hate the Rangers, no matter how much good we have done her. And in the neighboring settlements, the locals will not give her life if they find out about her husband's dark past.}
{224}{}{Continue.}
{225}{}{You are developing an interesting idea.}
{226}{}{I'm afraid the only way out for this family is to leave the Sonoran lands and go east to California, where they can start all over again.}
{227}{}{I will try to convey this idea to her.}
{228}{}{Maybe not the worst idea.}

#Lone Ranger in Flagstaff
{230}{}{What is Ranger Keruk doing in Flagstaff?}
{231}{}{(sighs) Our walking trouble with a rifle on the back. The General Staff was against sabotage in Flagstaff, but one ranger's personal ambitions were higher than the charter. It's hard to blame him for that.}
{232}{}{Do you justify him?}
{233}{}{Keruk had a difficult fate due to the enslavement of his village. Apparently, he found a way in Flagstaff to get revenge for his past. We let him go so that he could make sense of his life and find peace of mind.}
{234}{}{So are you going to pull him out of there?}
{235}{}{To injure one of our best shooters? There must be a really good reason for this.}
{236}{}{I think you're right, General. You shouldn't pull him out of there until he wants to.}
{237}{}{I don't believe my ears! Is that what the general says? That's it, I'm leaving here.}
{238}{}{He takes revenge on everyone. His actions harm ordinary peaceful colonists.}
{239}{}{I don't care about his problems. Just get him out of there.}
{240}{}{That makes a difference. It looks like the situation has gone too far.}
{241}{}{You are a general. He will not disobey your order.}
{242}{}{Most likely. Please give him the order to return to base if you find yourself in the vicinity. He adheres to radio silence and for some reason shuns the rest of the rangers.}
{243}{}{There is!}
{244}{}{Only if I'm nearby.}

#Villa Union
{250}{}{Times are hard in my native village. We need the Rangers' help.}
{251}{}{Hard times... This can be said about almost any settlement in Arizona and California. But unlike ordinary inhabitants, we really have the opportunity to fight for the rights of people in the wastelands.}
{252}{}{[Next]}
{253}{}{Maintaining order requires serious investments in training rangers, equipping squads and patrols, intelligence and combat operations. Not everyone can invest in such an alliance, but we try to respond to everyone.}
{254}{}{I think it will not be a problem for the Villa to supply you with food and ceramics.}
{255}{}{You know, we really have nothing to offer. It looks like this union will be short-lived.}
{256}{}{So you charge something for your protection?}
{257}{}{Of course. This is a kind of security tax - a normal practice in the Old World.}
{258}{}{And if the population has nothing to pay tax with?}
{259}{}{We are able to benefit from any cooperation. Some can build homes, others can grow crops, and some make good cadets. With the right approach, everyone can become useful to society.}

{260}{}{Villa... The Rangers have always respected your independence. But you've always stayed away from the rest of the world. When we needed food in the hungry years, you drove us away. Now you're asking for help. Tell me, who sent you to us?}
{261}{}{The community council has decided that it is time to conclude an alliance with you.}
{262}{}{Nobody. Many peasants were enslaved and taken to Flagstaff.}
{263}{}{Nobody. Many peasants were enslaved and taken to another city.}
{264}{}{I am here without the consent of the community.}

{270}{}{That's how... Well, an alliance with the Villa would be very useful, because now we need food more than ever. But I'm afraid the arrogance of your relatives will spoil the blood of our fighters.}
{271}{}{It's hard to argue with this. And yet you are ready to help us?}
{272}{}{I don't care about your fighters. I'm only interested in saving the Villa.}
{273}{}{I'm afraid now is not the best time to do this. There are big problems on the southeastern front, we have thrown all our forces in that direction.}
{274}{}{Problems are my little hobby, General.}
{275}{}{Talk to Commander Helford. Perhaps he will allocate people to live in the Villa. And then we will discuss the terms of the union... if your community really wants it.}
{276}{}{Thank you, General. I'll talk to Helford.}
{277}{}{Not yet. Keep in mind that you will have to be our right hand in negotiations with the peasants. Your task is to convince them of our friendliness and the need for an alliance.}
{278}{}{No problems.}
{279}{}{You promised to help. So some residents of the Villa are still in slavery.}

{280}{}{Commander Helford has approved my request to protect the Villa.}
{281}{}{(nods his head significantly and ponders the answer for a while) Times are changing...}
{282}{}{Eh, what?}
{283}{}{[Listen]}
{284}{}{Previously, the residents of the Villa sought isolation and drove the rangers away. But times are changing. And you change with them, unwittingly. I think it's time to forget our past differences.}
{285}{}{So are you ready to make an alliance?}
{286}{}{I will give the order to Commander Helford to assemble a detachment to be quartered in your valley. Talk to him about the details. Keep in mind that you will have to be our right hand in negotiations with the peasants. When your community is ready, we will officially sign the union.}
{287}{}{Thank you, General.}
{288}{}{Unfortunately, several of our people are still being held as slaves in another city.}
{289}{}{Are you talking about the Flagstaff mines? We know this situation and have been trying to solve it for a long time. Well, I think we'll be able to buy some of your people out of the slave stall. Your compañeros tribales will be coming home soon.}
{290}{}{How do you know so much about us?}
{291}{}{We collect information about any settlements in the wastelands. It's part of our job. Besides, the leader of your community has already visited us once... What was his name? Adolf... no, Andres Tejada.}
{292}{}{That's my father! I didn't know that he had left the community so far away.}
{1292}{}{That's my father! I didn't know that he had left the community so far away.}
{293}{}{Yes. But those negotiations, unfortunately, did not lead to anything.}

{294}{}{The villa is ready to make an alliance with you.}
{295}{}{Very good. From this day on, I declare our union complete. Go back to the Villa and celebrate this day with the whole community.}
{296}{}{OK.}
{297}{}{Finish the mission first. Then we'll talk.}
{298}{}{OK.}
# Jackals
{300}{}{Let's talk about Jackals.}
{301}{}{Jackals are one of the sick calluses on the body of this earth. What exactly did you want to discuss?}
{302}{}{I know the location of their main base. And I managed to examine it from the inside.}
{303}{}{A very dubious and at the same time intriguing statement. No one has ever managed to find this place and, moreover, get out of there alive.}
{304}{}{What about the rescued ranger?}
{305}{}{So this is your merit? Well, Ranger Jackson was let down by inexperience - on the way back he got lost and wandered through the desert for a long time until he found one of our abandoned outposts. We never found out the exact coordinates, and combing a whole dangerous area in search of burrows was too big a task.}
{306}{}{It turns out that even a ranger is primarily concerned with survival...}
{307}{}{Trust me. I am the only source of information for you.}
{308}{}{So, where is this base?}
{309}{}{On the border of the Mojave and Sonora deserts, north of the Villa.}
{310}{}{I need to check the maps. Wait a bit.}
{311}{}{Yes, it seems to be true. I think we should do some scouting there. And after finding the base... destroy it.}
{312}{}{Great plan. These jackals don't deserve their place in the sun. Destroy them all!}
{313}{}{Good. A guide will be useful to us in this operation. Participation will allow you to collect trophies. Agree to help?}
{1313}{}{OK. A guide will be useful to us in this operation. Participation will allow you to collect trophies. Do you agree to help?}
{314}{}{Yes.}
{315}{}{No.}
{316}{}{That is, I have to... kill?}
{317}{}{I like your attitude. In the location you indicated, a squad of punishers will be waiting. Go there immediately.}
{1317}{}{I like your attitude. In the location you indicated, a squad of punishers will be waiting. Go there immediately.}
{318}{}{The journey is not easy. Is there any way to make it easier for me?}
{319}{}{It will be done, General!}
{320}{}{Contact the patrolmen. They'll take you into the squad.}
{321}{}{It's sad to hear that. Well, as usual, we'll do everything ourselves. Thank you for the information, you can go.}
{322}{}{I've changed my mind! Let me participate in the siege.}
{323}{}{Goodbye.}
{324}{}{You can just stand and watch... Watch as your saviors and protectors are killed. Or you can take up arms and help them with something. So do you agree?}
{1324}{}{You can just stand and watch... Watch as your saviors and protectors are killed. Or you can take up arms and help them with something. So do you agree?}
{325}{}{Well, you know better what to do next.}
{326}{}{OK. Then we'll manage on our own. Thank you for the information.}
{327}{}{Glad to try.}
{1327}{}{I'm glad to try.}

{330}{}{Don't be in such a hurry. Jackals are ready to form an alliance with outsiders if it solves their hunger problem.}
{331}{}{What nonsense is this? These savages have already drunk so much blood from the Rangers and the surrounding settlements that negotiations are out of the question!}
{332}{}{I think it's worth trying to negotiate with them. They lead such an aggressive lifestyle only because of widespread hunger.}
{333}{}{Hmm. Then, if it's not too much trouble for you, explain to me what is the advantage of an alliance with cannibal savages?}
{334}{}{They are disorganized and scattered all over the wasteland. By destroying the main base, you will only anger the remaining clans. This feud will last for generations.}
{335}{}{The thought of a war with savages is not so much frightening as annoying. Well, we'll try diplomacy. Perhaps this approach will unite and calm the Jackal clans. Thanks for the information. You can go now.}
{336}{}{Glad to try, General. I will return to the Jackals and tell them about the upcoming negotiations.}
{1336}{}{Glad to try, General. I will return to the Jackals and tell them about the upcoming negotiations.}
{337}{}{Indeed, the last time they tried to kill me and devour me. I don't think I'll be able to negotiate with them again.}
{338}{}{Nothing. These jackals don't deserve their place in the sun. Destroy them all!}

{340}{}{I want to report Ranger Garth's crimes.}
{341}{}{A ranger in an Aqueduct? We placed him there to establish order. What crimes did he commit?}
{342}{}{Numerous murders of refugees on the grounds of distrust of outsiders. He dumped their bodies into the aqueduct shafts.}
{343}{}{Can you show them? In this case, we have a big trial ahead of us. We'll take Garth into custody. Thanks for the information... although this news crushes me. Especially in such a difficult time.}
{344}{}{Yes, I understand... Goodbye, General.}

#Ranger Title
{350}{}{I want to join the ranks of the Rangers.}
{351}{}{Commendable zeal. But the title of ranger must be earned. Many cadets have been training and participating in missions for years to get a badge. What merits can you name?}
{352}{}{I don't seem to have anything to answer that.}
{353}{}{That's what I thought. Join the cadet corps and serve for several years for the benefit of our mission.}
{354}{}{I'll think about it.}
{355}{}{Let me take a little more of your time, General.}
{356}{}{Is there a faster way?}
{357}{}{Hmm. Talk to Commander Helford, he's been looking for recruits for special assignments for a long time.}
{358}{}{I'll think about it.}
{359}{}{Yes, this is a serious statement. But it is not enough for the rank of ranger.}
{360}{}{I destroyed a tribe of Jackals.}
{1360}{}{I destroyed a tribe of Jackals.}
{361}{}{With my help, you have made an alliance with the Jackals.}
{362}{}{Thanks to me, the slave trade in Flagstaff was eliminated.}
{363}{}{I freed the slaves in Flagstaff.}
{1363}{}{I freed the slaves in Flagstaff.}
{364}{}{I managed to resolve the conflict in San Brahmin in favor of the Rangers.}
{365}{}{I destroyed the Phoenix Cathedral of Fire.}
{1365}{}{I destroyed the Phoenix Cathedral of Fire.}
{366}{}{I destroyed the Brotherhood of Steel.}
{1366}{}{I destroyed the Brotherhood of Steel.}
{367}{}{Thanks to me, the expansion of tinsmiths was stopped.}
{368}{}{With my help, the Liberation Party overthrew Aaron.}
{369}{}{[CHEAT: I deserve this title, General]}
{370}{}{Well, such a list inspires confidence. Let me take a look at the report of your actions... Yes, our scouts collect information about some "outstanding" personalities. Don't worry, it's just part of the general routine.}
{371}{}{Hmm. Okay...}
{372}{}{It looks like your reputation in the wastelands is going against your actions. Many consider you... not a decent enough person.}
{373}{}{You know what the mores are there. You won't please everyone.}
{374}{}{Do the Rangers take into account the opinion of dirty beggars? Don't make me laugh.}
{375}{}{Some rangers give a negative assessment of your personality. Not to say that this is a serious offense, but sometimes it does not hurt to listen.}
{376}{}{Over time, they will think better of me.}
{377}{}{I'm not thrilled with some of the rangers either. But I'm not running with reports to the general. Here are the s-s-bitches...}
{378}{}{They're talking about your connection with the mainline. Sometimes it's worth staying away from the bad guys.}
{379}{}{They're not bad guys, believe me, General.}
{380}{}{Who's the bad guy here? Me? Let them dare to say it to your face.}
{381}{}{They say you belong to a sect of Followers of Fire. This is far from the best recommendation.}
{382}{}{The Rangers just need their own man in this church.}
{383}{}{It is sad that you have disagreements with our faith. You should repent before the Sacred Fire.}
{384}{}{So, it says here that you are part of a dubious organization called the Brotherhood of Steel.}
{385}{}{Right. It seemed like a good idea at the time. But not now.}
{386}{}{Oh yes. And the Rangers should treat this "organization" with all respect.}
{387}{}{As you understand, with such recommendations, I cannot accept you into our ranks. You need to earn more trust.}
{388}{}{No problem, General, nothing will crush my confidence.}
{389}{}{Here's another thing, after this I won't even want to come back here.}
{390}{}{Hmm. Such situations are exceptional. Only a few were able to get their badge, bypassing many years of hard training. But I'm glad to dedicate you to the Rangers.}
{391}{}{So I can get a badge?}
{392}{}{This is normal for me. I always get my way.}
{393}{}{Are you ready to accept this burden? Swear that you will carry Law and Order and not tarnish the honor of the Rangers.}
{1393}{}{Are you ready to accept this burden? Swear that you will carry Law and Order and will not tarnish the honor of the Rangers.}
{394}{}{I swear!}
{395}{}{Great. Wear your badge with pride. And talk to the quartermaster, he will give out the primary equipment. In the meantime, I will prepare the papers on your enrollment.}
{396}{}{Thank you, General!}

#Questions
{400}{}{Can I ask you a few questions?}
{401}{}{Try not to drag out. I don't have much time for idle conversations.}
{402}{}{You're right, enough talking.}
{403}{}{Let me ask you another question.}

{410}{}{How did you become a ranger?}
{411}{}{I passed all the milestones of ranger development and honestly rose to the rank of general.}
{412}{}{You must have traveled a lot?}
{413}{}{Oh yes, I've been to different parts of the Southwest, including Los Angeles, Las Vegas and Phoenix. The same problems are everywhere - hunger, devastation and desertification.}
{420}{}{Can you tell us about this place?}
{421}{}{This is the main base of the rangers in Arizona. The power plant serves us as a citadel, and the dam as a fortress. Outside, as you already know, there is an information center and a training ground.}
{422}{}{So there are other bases?}
{423}{}{That's right. There are several large forts like this one in Nevada and California. We keep in touch with them, but each has its own rules and principles.}
{424}{}{What is the mission of the Rangers?}
{425}{}{We bring Law and Order to this chaotic world. To begin with, this means protecting settlements and caravan routes from bandits and mutants. But protection is only the first frontier.}
{426}{}{[Next]}
{427}{}{The residents who have joined us are obliged to adopt the Law, pay taxes and do useful work. Such as growing crops or hunting game.}
{428}{}{Why did you dam the waters of Colorado?}
{429}{}{(sighs mockingly) This dam has been standing here for a long time. It uses water pressure to generate electricity... I hope you know what it is. We have only restored the work of the dam and turned it into a fort for protection from enemies and bad weather.}
{430}{}{But you have taken the only place to cross the Colorado for miles around.}
{431}{}{Roadblocks allow you to save the dam and the power plant from stupid commoners. This is a unique equipment, it is critically important for us and for the surrounding lands. And to cross the river there is a ferry downstream with very reasonable prices.}
{432}{}{What Law were you talking about, General?}
{433}{}{Simple truths for any prosperous society. Don't kill unless absolutely necessary. Don't take someone else's without asking. Act for the good of your community. There is a set of similar rules. But unfortunately, many in the Wastelands do not know how to read, so we have to explain in a simpler and more intelligible language.}
{434}{}{Human relations are much more important than any laws.}
{435}{}{(tired sigh) As they used to say in the Old World, the law is harsh, but it's the law. People couldn't think of anything better for self-organization and discipline. Rejection of the Law leads to chaos. And we have learned this well over the last hundred years.}
{436}{}{You mentioned the Old World. But it has been in ruins for a long time.}
{437}{}{Right. The nuclear Apocalypse was the fruit of pride and stupidity. Now we're paying for it. But everyone makes mistakes. The only question is what conclusions we will draw from them.}
{438}{}{I just want to let you know that the case has moved forward. It remains to negotiate with the leader. I'll do it very soon.}

#Ulysses Grant's Holodisk
{450}{}{You will surely be interested in this report from the Cathedral.}
{451}{}{From the Cathedral of the Sacred Fire in Phoenix? Curious. Where did you get this holodisk?}
{452}{}{I managed to ingratiate myself with the Adviser. He asked me to take this report to the military base in Puerto Penasco.}
{453}{}{Although this information is a little late, but thank you for your assistance.}
{454}{}{You're welcome.}
{455}{}{Well, well. Very curious. We have been monitoring this database for a long time and we know that the Cathedral is somehow connected with it. This secret report clarifies the situation a little... I don't understand why you're giving it to us?}
{456}{}{Let's just say I'm... disappointed in the ideas of the Sacred Fire.}
{1456}{}{Let's just say I'm... disappointed in the ideas of the Sacred Fire.}
{457}{}{I have a personal score to settle with this Cathedral. They patronized the slaveholders who captured my relatives.}
{458}{}{Well, that sounds convincing. Thank you for your assistance, this information can be very valuable.}
{459}{}{You're welcome.}

#San Brahmin quest
{460}{}{Oh yes. I hope this union is not too late. This is a difficult time, and we will need all the support. But as long as your community gets back to normal and harvests a new crop, the situation may change.}
{461}{}{What are you talking about?}
{462}{}{The tragedy has only affected your small peaceful commune. The real threat bottlecaps all of Southern Arizona. Already now the rangers are trying to recapture the town of San Brahmin from the invaders.}
{463}{}{But we weren't going to get involved in a war.}
{464}{}{No matter how hard you try to stay isolated from the rest of the world, this world ALREADY knows about the Villa. And if San Brahmin falls, your peaceful community may be next.}
{465}{}{Damn, something has to be done about it.}
{466}{}{I have to ask you for one simple favor while we're busy with the Villa. Take my instructions to Agent Oscar in San Brahmin. He helps the local resistance forces. Consider it part of our union.}
{467}{}{The work seems to be simple. Permission to go, General?}
{468}{}{It looks like I'll have to deal with this issue before the threat gets to the Villa. See you, General.}
{469}{}{I'm listening carefully. What news from San Brahmin?}

{470}{}{I need to talk to you about the situation in San Brahmin.}
{471}{}{Unfortunately, I haven't been able to carry your instructions yet.}
{472}{}{Then hurry up. The more we do nothing, the stronger our enemy is.}
{473}{}{That's right, General.}
{474}{}{[CHEAT: It's done!]}
{475}{}{The missionaries left San Brahmin. This is good news. But we must not forget that they can return. It was a great moment to form an alliance with the tribal leader. Now the moment is lost.}
{476}{}{[Next]}
{477}{}{Hmm-m. That's what I was most afraid of. A detachment of missionaries in San Brahmin acted on orders from Phoenix. Apparently, Aaron's dreams of empire were not far from reality.}
{478}{}{How do we stop this Phoenix Lord?}
{479}{}{It won't be easy. But I am aware of a group of rebels in Phoenix who are also fighting against Aaron and his church. Try to contact them and offer our help. I'm asking you because it's hard for rangers to work in a crowded urban environment.}
{480}{}{Can I learn more about the purpose of my mission?}
{481}{}{We had to get involved in several local conflicts to prevent the spread of the "red contagion" from Phoenix. The situation is difficult and requires a speedy resolution.}
{482}{}{[Next]}
{483}{}{Go to San Brahmin and find Ranger Oscar there. He oversees the locals to fight the invaders. Take the report to him and, if necessary, assist in resolving the conflict.}
{484}{}{Understood, General.}
{1484}{}{Understood, General.}
{485}{}{Looks like I'm going to have to get involved in your war. I hope it's worth it.}
{486}{}{Just take the report? Sounds easy.}
{487}{}{Ranger Oscar died in battle defending the freedom of the tribe.}
{488}{}{Sad news. But he was aware of the risk he was taking. We will always remember Oscar as a hero.}
{489}{}{I'm really sorry.}
{490}{}{Ranger Oscar escaped from San Brahmin. The situation there is very bad.}
{491}{}{I am aware of his defeat. And I don't blame him. Oscar did everything he could.}
{492}{}{I'm sorry.}
{493}{}{Ranger Oscar has completed his mission in San Brahmin. The situation there has changed a lot.}
{494}{}{I haven't heard his full report yet. But I'm sure you two have something to tell.}
{495}{}{Of course.}
{496}{}{So how did it end in San Brahmin? Waiting for the full report...}
{497}{}{[Report]}
{498}{}{Great job. Thanks to us, the tribe gained freedom. This victory will show everyone else how useful the Rangers are. Not to mention the much-needed supply of brahmin meat now.}
{499}{}{[Next]}

#Phoenix - quest completion
{500}{}{I need to talk to you about Phoenix.}
{501}{}{I'm listening carefully. What news?}
{502}{}{Unfortunately, everything is still the same.}
{503}{}{How do I find the rebels in question?}
{504}{}{As far as I know, they hide in underground communications and conduct an encrypted radio transmission. You can also ask around people, there will certainly be their supporters among the locals. But be careful with the questions.}
{505}{}{Thank you, it may help.}
{506}{}{Why is it so important to get rid of Aaron and his church?}
{507}{}{The cult is just a puppet in the hands of Aaron, the local ruler. He seeks to create an empire, therefore he conducts an aggressive policy and physically exterminates dissent.}
{508}{}{[Next]}
{509}{}{So we need to find those rebels as soon as possible. How to do it?}
{510}{}{But why is it so important to get rid of the Phoenix Fire Church?}
{511}{}{The Cathedral of the Sacred Fire in Phoenix has been destroyed.}
{512}{}{(sigh of relief) I heard the news. Great job. At least one less enemy.}
{513}{}{[Next]}
{514}{}{You did the right thing by taking extreme measures. Who knows what secrets were kept in the chambers of the temple? And how much trouble they could bring to the unprepared people of our time.}
{1514}{}{You did the right thing by taking extreme measures. Who knows what secrets were kept in the chambers of the temple? And how much trouble they could bring to the unprepared people of our time.}
{515}{}{[Next]}
{516}{}{But I'm afraid we're in for an even tougher ordeal. While you rest from the road, I need to gather the field commanders. Meet me in the meeting room, you need to be there too.}
{517}{}{I'll come back later, General.}
{518}{}{Aaron, the Lord of the Phoenix, is dead.}
{519}{}{(sigh of relief) I heard the news. Great job. At least one less enemy.}
{520}{}{[Next]}
{521}{}{Without its ruler, the city will fall victim to discord. The governors of Aaron will begin to fight among themselves for the throne, the peaceful population will "remember" the old grievances of the church, and the rebels will be able to act more openly and decisively. It will be a difficult period for the city, but I believe it's for the best.}
{522}{}{[Next]}
{523}{}{It was with his filing that slavery, harmful pre-war technologies and drugs returned to Arizona. Our world is already too fragile to admit tyrants to it.}
{524}{}{I see.}
{525}{}{What a coincidence - I'm just from there!}
{526}{}{The Liberation Party led by Marcos stormed the cathedral. The Phoenix Lord is dead.}
#Dialog block
{550}{}{I'm not going to cuddle with a snake. Prove that you can be trusted. Then we'll talk. You know where the exit is.}
{551}{}{Yes, General Mossman, I know.}
{552}{}{You're making a big mistake, General. You'll see.}
{553}{}{And here is our main failure. So, are you here to restore justice? Oh no, you're here for your own selfish purposes.}
{554}{}{Why was I stripped of my rank?}
{555}{}{Being on two fronts, it is impossible to maintain loyalty. Conflict is inevitable. If you choose the side of a colonizer who subjugates Southern Arizona to his will, then you have no place among the rangers.}
{556}{}{There has always been a gap between religion and law. In such a situation, it is impossible to maintain understanding, conflict is inevitable. If you choose the path of a sectarian, then you have no place among the rangers.}
{557}{}{Obviously, your actions differ from the principles of Law and Order. You may be misinterpreting them, but this does not deprive you of responsibility. We can't have a man like you wearing a ranger badge.}
{558}{}{[Next]}
{559}{}{Go in peace. Out of respect for your past achievements, we are only depriving you of your rank. Under other circumstances, the penalty for betrayal would be execution.}
{560}{}{I understand, General. You won't hear from me again.}
{561}{}{Learn to forgive, General. You'll need it someday.}
{562}{}{We know what you're doing here. Go away. A sentry will escort you outside.}
{563}{}{[Leave the room]}

{570}{}{A very unexpected visit. I thought your church hated our brother.}
{571}{}{Can't we live in peace?}
{572}{}{Only if we put barricades with a moat of radioactive liquid on the border.}
{573}{}{[Next]}
{574}{}{Your church imposes its perverted dogmas on others and punishes those who disagree with them. Your leader creates an empire under the flag of the church and develops slavery. We have nothing to negotiate with the snake. Go and tell this to your prior. This concludes our negotiations.}
{575}{}{[Leave the room]}
{576}{}{So, here is a goodwill ambassador from the Brotherhood of Steel itself. Are you going to hand over the armistice agreement to us? Or maybe it's a demand for surrender?}
{577}{}{I don't know what you're talking about. I'm here of my own free will.}
{578}{}{Perhaps. Anyway, we can't let you be in our database. The sentry will show the exit to the outside.}
{579}{}{[Leave the room]}
{580}{}{If you fail to reach an agreement with the Brotherhood, it will wipe your dam off the face of the earth.}
{581}{}{These threats only prove the hostility of the Brotherhood of Steel. Military services are created for war, not for the creation of a new world. Your Brotherhood should learn to live in peace. Now go and tell this to your general. This concludes our negotiations.}
{582}{}{[Leave the room]}

{590}{}{Is everyone here? Then let's start.}
{591}{}{[Next]}
{592}{}{As you know, our new ally, }
{1592}{}{As you know, our new ally, }
{593}{}{ from the Villa, has rid the wasteland of the oppressor Aaron. Reports are coming in from all over the state about the fall of his cult. Soon this struggle will go down in history.}
{1593}{}{ from the Villa, delivered the wasteland from the oppressor Aaron. Reports are coming in from all over the state about the fall of his cult. Soon this struggle will go down in history.}
{594}{}{[Next]}
{595}{}{But this is not the end. As we expected, Aaron was just part of a big game. Tinsmiths helped him with weapons and equipment for the sake of cheap uranium.}
{596}{}{[Next]}
{597}{}{However, it's even more interesting - a certain third party was in the contract. Otherwise, Aaron and the tinsmiths would not have been able to agree on cooperation, and Aaron himself would never have come to power.}
{598}{}{[Next]}
{599}{}{We know almost nothing about this mysterious organization. It is based in the old port of Puerto Penasco and conducts an aggressive military policy.}
{600}{}{[Next]}
{601}{}{We know for sure that the uranium ore from Flagstaff is transported to the tinsmiths, and the finished batteries from the uranium chips are exported mainly to the outpost in Puerto.}
{602}{}{[Next]}
{603}{}{In other words, this organization decided to subjugate Southern Arizona in order to obtain resources with cheap labor. They put their vassals in charge of the settlements, as was the case with Casa Grande. They start revolutions, as it was in San Brahmin. They seize resources and use slaves for this. And we don't even know who we're dealing with.}
{604}{}{[Next]}
{605}{}{, now you understand that your Villa just got "under fire". If this army continues to enslave Southern Arizona, then Villa, like all other small settlements, will lose its freedom. The best way to avoid this is to ally with the Rangers and present a united front against the invader.}
{606}{}{What is required of me now?}
{607}{}{Go to Puerto Penasco and find the weak points of the enemy. Our scouts have not been able to find out any valuable information yet - this military base is too far away and too well organized.}
{608}{}{Then how do I do it?}
{609}{}{You're a peasant. You'll be less suspicious. Besides, you have a good reason - the enslavement of the Villa. Good luck.}
{1609}{}{You're a peasant. You'll be less suspicious. Besides, you have a good reason - the enslavement of the Villa. Good luck.}
{610}{}{Let me go, General.}
{611}{}{In my opinion, this is suicide. I wash my hands of it, General.}
{612}{}{Think about everything that has been said here. Perhaps it is your support that will not be enough to win this war.}
{613}{}{You're right, General. I will try to find out more about this mysterious organization.}
{614}{}{Look for fools. And I'm going home, my native Villa is waiting for me, General.}

{620}{}{I managed to infiltrate the Brotherhood of Steel base.}
{621}{}{Good news. What did you find out? What are their weaknesses?}
{622}{}{I don't know their weaknesses yet. They are too well organized and protected.}
{623}{}{Sorry to hear that. But I believe that you will succeed. Keep scouting.}
{624}{}{Let me go, General.}
{625}{}{May I take another minute of your time?}
{626}{}{Their ship is full of explosives. But I don't know how to approach it yet.}
{627}{}{Great idea. If you find a way to blow up their entire ship, it will erase the Brotherhood from the map of Arizona. Their vassals and small outposts will remain helpless. Try to do it. I believe you will succeed.}
{628}{}{You know, I was released only because I was offered a similar task.}
{629}{}{That's how... And what did you decide? Whose side are you on?}
{1629}{}{That's how... And what did you decide? Whose side are you on?}
{630}{}{Of course, on yours, General.}
{631}{}{Then do me a favor - use the trust you have gained to destroy our common enemy.}
{632}{}{Permission to go, General?}
{633}{}{You can't handle them, General. Admit defeat.}
{634}{}{Admit defeat because of one message? It's a pity that everything turned out this way. Now I can't let you go until we get all the answers. It was not worth going against the Rangers.}
{635}{}{No, General. I'll get out of here. And no one will touch me.}
{636}{}{We are no longer allies. So fuck off, old man. You can't intimidate me.}
{637}{}{I managed to infiltrate the Brotherhood ship and detonate the torpedoes. The base is completely destroyed.}
{638}{}{There has never been such good news in many years! Having driven out the Brotherhood, we have preserved our native lands for ourselves and our descendants. What could be better?}
{639}{}{Of course.}
{640}{}{We still have a lot to do to eradicate the remnants of the evil sown by the Brotherhood. Your mission is over. I suggest you become a ranger and serve in your native Villa.}
{641}{}{Thank you, General. But I want to preserve my freedom and the freedom of my village.}
{642}{}{Well, then go to your family at the Villa and tell the good news.}
{643}{}{Glad to have served, General.}
{1643}{}{It was a pleasure to serve, General.}
{644}{}{Thank you for the honor of becoming a ranger.}
{645}{}{From now on, you're one of the Rangers. Keep Law and Order in your native land. Now go back to the Villa and tell your family the good news.}
{1645}{}{From now on, you're one of the Rangers. Keep Law and Order in your native land. Now go back to the Villa and tell your family the good news.}
{646}{}{Glad to serve, General.}
{1646}{}{Glad to serve, General.}
{647}{}{We still have a lot to do to eradicate the remnants of the evil sown by the Brotherhood. Your mission is over. Go back to the Villa and tell your family the good news.}
{648}{}{Why not just attack this fort with a whole squad of rangers?}
{649}{}{Our opponent is strong and well organized. In an open fight against him, we have no chance. In such a case, we say: if you want to defeat a strong beast, cut his legs and finish him off from afar.}
{650}{}{I want to talk about our new enemy.}
{651}{}{Sure. Did you find out anything?}
{652}{}{Absolutely not.}
{653}{}{What do you know about the base in Puerto?}
{654}{}{Not much. The old ship appeared in the port a few years ago. They are not allowed inside, the perimeter is well guarded. It is difficult for scouts to get there through the desert, besides, we have directed all our forces in another direction. You'll have to find out the details yourself.}
{655}{}{I don't understand how such a closed organization was able to subdue so many settlements?}
{656}{}{Competent policy and good technical equipment. The Puerto military itself does not get involved in the internecine wars of Arizona. But they successfully provoke them. And when the shooting subsides, the settlements are headed by the people they need - puppets like Aaron.}
{657}{}{Why is this bad for Arizona?}
{658}{}{They carry their worldview by means of force, and this is unacceptable. Because of their policy, the settlements lose their sovereignty and find themselves in a servile position. After all, society is not ready for their progressive ideas.}
{659}{}{I see. Let's go back a bit.}