{100}{}{You see a cadet.}
{101}{}{Here is a cadet. Today he serves in the kitchen.}
{102}{}{You're not on the ration lists.}

{200}{}{Okay, stop... Civilian? What are you doing here?}
{201}{}{I'm watching you. Got it?}
{202}{}{E... These are office premises. Go away.}
{203}{}{Try to kick it out, sucker.}
{204}{}{Of course I don't want any problems.}
{205}{}{Don't worry, I have clearance.}
{206}{}{You're not supposed to know that. But I have a clearance, relax.}

{210}{}{I'm the kitchen attendant today. But we don't serve outsiders.}
{211}{}{So I have nothing to do here. Bye.}
{212}{}{I'm the kitchen attendant today. But you're not on the ration lists.}

{220}{}{Who's your supervisor, cadet?}
{221}{}{Captain Agatha. And what?}
{222}{}{How do you like her training?}
{223}{}{Very tiring. But it will benefit in the conditions of a hungry desert. It's a shame that we, the cadets, are not allowed to shoot serious weapons. I've been dreaming about him since the very beginning of my studies. And even after receiving the badge, we will have to save ammo. Annoying.}
{224}{}{Shoot some more. It's not such a big deal, really.}
{225}{}{Did you think you were in a fairy tale? Naive.}
{226}{}{Nothing, I just wanted to talk. Bye.}
{227}{}{Is she a good commander?}
{228}{}{Of course. She takes care of her cadets as if they were her own children. I am glad that she is the one who trains our squad.}
{229}{}{You're lucky to have her. Later.}

{230}{}{So it was after your training that the quartermaster lost his weapon?}
{231}{}{But... We have returned the weapon.}
{232}{}{And then they quietly took it back, right? Or have you changed the signature in the issue log? Speak.}
{233}{}{Indeed, it is difficult to argue with this. You can be free, cadet.}
{234}{}{Thu... uh... uh... Listen. I told them it was a bad idea.}
{235}{}{So. Tell me.}
{236}{}{Yeah. So you confessed.}
{237}{}{We returned the weapon after training, and then stole it along with a box of cartridges. We just wanted to practice shooting a little. Otherwise, which of us are rangers?}
{238}{}{And you hoped it would go unnoticed?}
{239}{}{We were really going to get the gun back. But the shooting attracted the radscorpions. I had to run, and the gun was left lying in the desert. It is not possible to return for him without arousing suspicion yet. Besides, the quartermaster, as luck would have it, has started reinventarization.}
{240}{}{Well, I can understand you. Although others will judge.}
{241}{}{What an interesting excuse. I wonder what the Rangers will do to you for such an offense?}
{242}{}{You know, the others won't like that I'm telling this. But something has to be done. You're a new person at the base. Can we come to an agreement?}
{243}{}{Business approach. What do you suggest?}
{244}{}{I'll give you the rest of the cartridges if you return the gun to me. I'll find a way to sneak it back to the warehouse so our asses don't get hurt. The weapon lies under a large cactus opposite the farm. What do you say?}
{245}{}{Not a bad deal. I'll think about your offer.}
{246}{}{I'm not going to cover for petty thieves. Have a nice stay, cadet.}
{247}{}{Don't worry, it's between us.}
{248}{}{Em... Listen. I told them it was a bad idea. They didn't listen to me.}
{249}{}{Remind me where the gun is?}

{250}{}{It's him! Thanks, you're saving our asses. Now the guys and I will be more careful. Yes, and here are the cartridges, as agreed. }
{251}{}{Be.}
{252}{}{You had to lick the quartermaster's ass, didn't you? Now every cadet will know that it's better not to mess with you.}
{253}{}{Sorry, I had no choice.}
{254}{}{You screwed up yourself. Blame only yourself for this.}
{255}{}{Is this the gun we were talking about?}