#---------------------------------------------------------
#  Translated by Georg; revised by garwert.
#---------------------------------------------------------
{100}{}{You see Cadet Birk.}
{101}{}{You see a quite inexperienced scrawny-looking cadet. No wonder he was assigned here.}

{200}{}{(you see a young man with a thin neck; looking at you, he can't look away, often making a short stretched smirk) Greetings! How may I help you?}
{201}{}{What is this place?}
{202}{}{This is the information center... well, actually a reception room, or more of a... (straightens his back) Here we discuss business with outsiders, sir!}
{1202}{}{This is the information center... well, actually a reception room, or more of a... (straightens his back) Here we discuss business with outsiders, ma'am!}

{203}{}{Who are "we"?}
{204}{}{(makes a confused face) The rangers... That is... (straightens up) Cadet Birk at your service! If you need a ranger of a senior rank, you'll have to make an appointment.}
{205}{}{Who's behind that door?}
{206}{}{Field Commander Helford... But you haven't made an appointment yet, so I can't...}
{207}{}{Great, maybe he can help me.}
{208}{}{Hey, wait!}
{209}{}{[Leave]}

{210}{}{I need to see your leader.}
{211}{}{The general? Oh. No, I'm afraid you can't visit the general.}
{212}{}{Who *can* I visit then?}
{213}{}{Field Commander Helford is behind that door... But you must make an appointment, I can't le...}
{214}{}{Great, maybe he can help me.}
{215}{}{Hey, wait!}
{216}{}{[Leave]}

{220}{}{Just don't create any trouble for me.}
{221}{}{I won't.}
{222}{}{Hi, uhh, congratulations with the promotion. And I still have years of service ahead before I can receive the title of a ranger.}
{223}{}{Goodbye.}
