{100}{}{You see a cadet.}
{101}{}{You see one of the recruits.}

{110}{}{They say it's easier in battle than in training.}
{111}{}{Captain Agatha is a beast, not a man.}
{112}{}{I admire Commander Halford.}
{113}{}{They say the general has hair all over his body, so he wears an anther.}
{114}{}{I wonder what's out there in California?}
{115}{}{It would be more like lunchtime.}
{116}{}{After stories about monsters, I don't want to sleep.}
{117}{}{These exercises will end someday.}
{118}{}{I like it here so far.}
{119}{}{Do you want to become a cadet too?}