{100}{}{This is Cadet Burke.}
{101}{}{You see a skinny and very inexperienced cadet. It is not surprising that he was placed on this post.}

{200}{}{ (in front of you is a young man with a thin neck; looking at you, he cannot cross eyes in any way and every minute makes a short strained grin) I wish you good health! What can I do for you?}
{201}{}{What is this place?}
{202}{}{This is an information center... more precisely, this is the reception room, more precisely... (straightens up) Here we discuss business with strangers, sir!}
{1202}{}{This is an information center... more precisely, this is the reception room, more precisely... (straightens up) Here we discuss business with strangers, ma'am!}

{203}{}{Who is "we"?}
{204}{}{( makes a confused face) Rangers... That is... (straightens up) Cadet Burke at your service! If you need a senior ranger, you'll have to make an appointment.}
{205}{}{And who is behind this door?}
{206}{}{Field Commander Helford... But you haven't made an appointment yet, so I can't...}
{207}{}{Great, maybe he can help me.}
{208}{}{Hey, wait!}
{209}{}{[Leave]}

{210}{}{I need your main one.}
{211}{}{The General? Oh no, you can't go to the general in any way.}
{212}{}{And who can I go to?}
{213}{}{Field Commander Helford is behind this door... But you have to make an appointment, I can't let in...}
{214}{}{Great, maybe he can help me.}
{215}{}{Hey, wait!}
{216}{}{[Leave]}

{220}{}{Just don't cause me any problems.}
{221}{}{I won't.}
{222}{}{Hi, uh, congratulations on the promotion. And I still have to serve for years to the rank of ranger.}
{223}{}{Bye.}