#---------------------------------------------------------
#  Translated by Georg; revised by garwert.
#---------------------------------------------------------
{100}{}{You see a cadet.}
{101}{}{You see one of the recruits.}

{110}{}{They say it's easier in combat than in training.}
{111}{}{Captain Agatha is a beast, not a human.}
{112}{}{I admire commander Helford.}
{113}{}{They say that the general's entire body is covered in hair, that's why he wears a duster.}
{114}{}{Would be nice to know what's going on in California.}
{115}{}{I wish lunchtime was sooner.}
{116}{}{I don't feel like sleeping after hearing the stories about monsters.}
{117}{}{This training will end one day.}
{118}{}{I like it here so far.}
{119}{}{You want to become a cadet too?}
