#---------------------------------------------------------
#  Translated by Georg; revised by garwert.
#---------------------------------------------------------
{100}{}{You see a cadet.}
{101}{}{You see a cadet. Today he is serving in the kitchen.}
{102}{}{Your name's not on the list, so you're not authorized to get field rations.}

{200}{}{Wait a minute... a civilian? What are you doing here?}
{201}{}{Watching you. Got it?}
{202}{}{Uhh... These are service rooms. Go away.}
{203}{}{Yeah, go make me, sucker.}
{204}{}{Sure, I don't want any problems.}
{205}{}{Don't worry, I have clearance.}
{206}{}{This is none of your concern, but I do have clearance to be here. Relax.}

{210}{}{Today I am on duty in the kitchen. But we don't serve outsiders.}
{211}{}{Then I have no reason to stay here. Goodbye.}
{212}{}{Today I am on duty in the kitchen. But you aren't on the list. So, not authorized to receive a field ration.}

{220}{}{Who is your curator, cadet?}
{221}{}{Captain Agatha, why?}
{222}{}{What do you think of her training exercises?}
{223}{}{They are very tiring. But the lessons they teach will be useful in barren desert. The only thing that sucks is that we cadets are not allowed to touch serious weaponry. I dreamt of it since the start of the training. And even when I receive a badge we will still have to conserve ammo. A bummer.}
{224}{}{You will get to fire them later. It's not that big of a deal, really.}
{225}{}{Did you think you are in some fairytale? How naive.}
{226}{}{Nothing, just wanted to talk. Bye.}
{227}{}{Is she a good commander?}
{228}{}{Of course. She cares about her cadets as if we were her own children. I'm glad that it's her training our unit.}
{229}{}{You got lucky with her. Bye.}

{230}{}{So the quartermaster got a missing weapon after your training exercise?}
{231}{}{But... we returned the weapon.}
{232}{}{And then quietly took it back, yeah? Or changed a signature in the issue log? Speak.}
{233}{}{Hmm, hard to argue against that. Dismissed, cadet.}
{234}{}{Wh... Um... Ugh... Listen. I told them it was a bad idea.}
{235}{}{So, tell me about it.}
{236}{}{Aha. You admitted to it.}
{237}{}{We returned the weapon after the training exercise, and then stole it back along with some ammunition. We just wanted to have a bit of shooting practice. What kind of a ranger can't shoot?}
{238}{}{And you hoped this would remain unnoticed?}
{239}{}{We really were planning to return the gun. But the shooting attracted radscorpions. We had to run, and the gun is left lying in the desert. So far we haven't succeeded in getting it back without causing suspicion. And the quartermaster, as luck would have it, began his re-inventory.}
{240}{}{Alright, I won't be the one to judge your actions, even if I didn't understand. But know that others will.}
{241}{}{What an interesting excuse. I wonder what the rangers will do to you all for such an offense.}
{242}{}{You know, the others won't like that I am telling you this. But something has to be done. You're new on this base. Maybe we can reach an agreement?}
{243}{}{Straight to the point, eh? Alright, tell me your proposal.}
{244}{}{I'll give you what's left of the bullets if you return the gun to me. I'll find a way to return it to the warehouse without anyone noticing so that we don't get our asses kicked. The weapon lies under a large cactus in front of the farm. So, what do you say?}
{245}{}{Not a bad proposal. I'll think about it.}
{246}{}{I'm not gonna help some petty thieves. Goodbye, cadet.}
{247}{}{Don't worry, this will remain between us.}
{248}{}{Umm... Listen. I told them it was a bad idea. They didn't listen.}
{249}{}{Remind me, where is the gun again?}

{250}{}{That's the gun! Thanks, you really saved our hides. We'll be more careful from now on. Yeah, and here is the ammo I mentioned.}
{251}{}{Goodbye.}
{252}{}{You really had to kiss the quartermaster's ass, yeah? Now every cadet will know that it's best not to deal with you.}
{253}{}{Sorry, I had no choice.}
{254}{}{You were the ones who screwed up. You can only blame yourselves.}
{255}{}{Is this the gun we were talking about?}

