{100}{}{This is Helford.}
{101}{}{You see one of the field commanders.}
{102}{}{Saving Jason has boosted your reputation among the Rangers.}

#The first dialog
{200}{}{(takes a cursory glance at you and returns to studying some reports) You're talking to a field commander. My name is Helford. And I have too much work to waste time on trifles.}
{201}{}{Can you spare a few minutes for poor campesino?}
{202}{}{I'm not here for idle talk, Commander.}

#Repeat dialog
{210}{}{What can I do for you?}
{211}{}{Goodbye.}
{212}{}{Of course, you don't have to continue.}
{213}{}{May I ask a question?}
{214}{}{I allow it.}
{215}{}{Another question.}

#Questions
{220}{}{How did you become a ranger?}
{221}{}{Learning from an early age and a lot of practice in the desert. Serve with me - and also, perhaps, you will become a field commander.}
{222}{}{What is this place?}
{223}{}{This is the main base of the Rangers. The command center is located inside the power plant, here we train and meet "guests".}
{224}{}{Which "guests" are we talking about?}
{225}{}{Merchants and representatives for negotiations. If you don't know yet, we are engaged in restoring order in this region. And that requires allies.}
{226}{}{I don't know much about Rangers. Tell us more?}
{227}{}{Rangers are elite fighters and masters of desert survival. These skills allow us to protect the law and restore order in the Wastelands. To return the Law to these lands is our main mission.}
{228}{}{Are you doing this for free?}
{229}{}{Our patronage is taxed and subject to a number of restrictions. If people refuse to accept the Law and our other conditions, we refuse to help them.}
{230}{}{What kind of Law is this?}
{231}{}{A small set of simple rules and prohibitions that should be strictly adhered to. Those who grossly violate the Law will be punished. Often fatal.}

#Ranger at the Jackals
{233}{}{But thanks for the search anyway. These savages have drunk too much blood from our brother. I am very glad that they paid with their lives for this.}
{234}{}{This is no longer required. We found the remains of a patrol in a jackal den in the north. You know about this place.}
{235}{}{What a surprise. Sad to hear that.}
{236}{}{How do I find the missing patrol?}
{237}{}{Most likely, it will be possible to locate their coordinates with the help of a walkie-talkie, if it still works for them. Perhaps they heard about the patrolmen in the nearest settlements. Finally, you can just go to that area and look for traces of rangers blindly in the middle of the desert.}
{238}{}{The latter is not pleasing, but it is at least something.}

{239}{}{Strangely enough, the Jackals are ready to make an alliance.}
{240}{}{It's out of the question! Jackals are cunning and aggressive, they are not inclined to dialogue. If they need an alliance, then it's probably a trick for profit, nothing more. I am sure that the General will fully agree with me.}
{241}{}{The rangers from the Northern Patrol are dead. They were killed by Jackals.}
{242}{}{Damn it... I felt in my gut that it would come out that way. These savages have drunk too much blood from our brother. But thanks for the search. I will send the investigation report to the General.}
{243}{}{You're welcome.}
{244}{}{The ranger from the northern Patrol has returned. True, one.}
{245}{}{I've already been informed. Great job, Ranger. Keep it up.}
{246}{}{I've already been informed. Great job, peasant. I see you have a charge of gunpowder, which we sometimes lack. Keep it up.}
{1246}{}{I've already been informed. Great job, peasant girl. I see you have a charge of gunpowder, which we sometimes lack. Keep it up.}
{247}{}{You're welcome.}
{248}{}{What do you think about Jackals?}
{249}{}{The Jackals are one of the most disgusting gangs in the Wastelands. They are so wild that even their children cannot be distinguished from puppies. It breaks my heart to see an entire nation slide into such a life. Cannibalism, a ridiculous cult, hostility to all outsiders, even neighboring clans - is it possible to fall lower?}

# The criminal's family
{250}{}{What do you say in defense of the murdered husband of that woman?}
{251}{}{Oh, this lady took you on the hook? Look, her husband was a criminal. He was engaged in robberies from farmers and attacks on travelers. For all this, he was justly executed in accordance with the Law. No one would have thought that he had a family.}
{252}{}{[Next]}
{253}{}{It's just a story for you. And for me, to be honest, too. But you have no idea what stupid things an angry female radscorpion can do. Something has to be done about it.}
{254}{}{[Next]}
{255}{}{But you can find a common language with her. No offense, but you look more like a peasant than a ranger, which means you can win her favor with great success.}
{256}{}{What should I do?}
{257}{}{Just explain to her that she is no longer welcome in these lands. It will be better for everyone if she and her offspring go to another place.}
{258}{}{Okay, I'll try.}
{259}{}{I'm not going to sort out other people's problems.}
{260}{}{I see you somehow managed to deal with this bitch. Good diplomacy. Here, take some cartridges from me personally as a token of appreciation.}
{261}{}{You're welcome.}
{262}{}{Wait a minute. I was informed of a very tragic event. The ferryman was found dead, and recently you and the refugees were seen at the ferry. A remarkable coincidence, isn't it?}
{263}{}{I, uh, have nothing to do with it.}
{264}{}{I hope so. Because sooner or later our guys will get to the truth. And you know how we honor the Law, especially so close to our citadel.}
{265}{}{Of course, uh, you'll surely find the culprits. Well, I have to go...}

#Farm Spy
{270}{}{I want to report a spy. He's hiding in a shack on the old road...}
{271}{}{...Thanks for the tip. We'll send scouts there and try to catch him off guard. It's time to nail this bastard.}
{272}{}{Success in the operation.}
{273}{}{Did you know that the quartermaster's weapon was missing?}
{274}{}{No, I was not informed about this. I have more important things to do than to dig into the intendant's dusters.}
{275}{}{I understand.}

#Stop dialog
{280}{}{Damn it... You look like those ghouls from the south. I don't want to say anything bad, but you should be careful about appearing in public.}
{281}{}{I know. Not for the first time.}

{282}{}{And you still have the audacity to come here after what you've done?}
{283}{}{He sold me a crappy product.}
{284}{}{And you're ready to kill a man for that? Damn, did it ever occur to you that the punishment should be proportionate to the crime?}
{1284}{}{And you're ready to kill a man for that? Damn, did it ever occur to you that the punishment should be proportionate to the crime?}
{285}{}{Nope.}
{286}{}{I am infinitely sorry for what I did.}
{287}{}{His guard attacked first.}
{288}{}{That is, his feeble-minded son? Some inappropriate actions were often expected of him, but so far there have been no fights. Well, I'm going to have to believe this story. But was it really impossible to just run away?}
{289}{}{And what do I have to do with it?}
{290}{}{You mean you just happened to be there? And that you have nothing to do with the merchant's death? Damn, it will be difficult to prove the opposite without witnesses.}
{1290}{}{You mean you just happened to be there? And that you have nothing to do with the merchant's death? Damn, it will be difficult to prove the opposite without witnesses.}
{291}{}{That's how it was, Commander.}
{292}{}{(shakes his head) Rednecks... What else can I expect from you? You're lucky no one saw the crime itself and that Flick's reputation was as shoddy as his merchandise. You can go now. But don't forget that we are always on guard.}
{293}{}{As you say, Commander.}
{294}{}{It would be better this way. I'll believe you for now, but don't forget that we are always on guard. And now you can go.}
{295}{}{Thank you, Commander.}
{296}{}{Uh...}
{297}{}{Okay, first I'll listen to what happened between you and Flick.}

#Villa Protection
{300}{}{I'm here on behalf of the Villa. We need the Rangers' help.}
{301}{}{I ask for help in freeing the peasants of the Villa from slavery.}
{302}{}{The peasants of the Villa still need help.}
{303}{}{ (looking up from his reports with a frown) Is the villa the oasis where, by some miracle, maize is grown in the middle of the desert? I sympathize with you. It's not easy for many now. The Red plague from Phoenix is spreading throughout Arizona, enslaving the population and seizing resources.}
{304}{}{I remember our conversation about the Villa.}
{305}{}{So will you help?}

{306}{}{Unfortunately, we don't have enough rangers. We have thrown all our forces in other directions.}
{307}{}{It's a pity.}
{308}{}{You Rangers are of no use.}
{309}{}{}
{310}{}{Do my errands first, as we agreed. Until then, I won't be able to let you see the general, much less recall people from other missions.}
{311}{}{I have completed all your orders.}
{1311}{}{I have completed all your orders.}
{312}{}{Really. To be honest, I did not expect this and gave the tasks only for the go-ahead. It's nice to see the performance.}
{313}{}{[Next]}
{314}{}{But as for the situation with the Villa, this issue should be decided by the general himself. Go straight to him, I'll tell the guards to let you through. Then it all depends on how you agree with him.}
{315}{}{Thank you, Commander.}
{316}{}{OK. If all this running around was in vain, I'll ruin your reputation for all of you.}

{320}{}{The general promised people to help the Villa.}
{321}{}{Damn it, did you still manage to persuade the old man?! We have more important things to do than save the skins of a few arrogant and arrogant peasants. You've always seen us as robbers. But - an order is an order. The villa is now under reliable protection.}
{322}{}{To be honest, I'm not happy with this deal. You peasants of the Villa have always looked at us as robbers. And when the situation turned out to be critical, you try to take advantage of us. But don't worry, we keep our word - the Villa is now under reliable protection. I really hope that this union will not be an empty chatter.}
{323}{}{I understand you, Commander. I hope we work together.}
{324}{}{With this attitude, it's not surprising that the Rangers have a lot of enemies. Goodbye... "amigo."}
#Story quests
{330}{}{Maybe I can help in some way?}
{331}{}{Usually *we* help someone... But in this case, I will be glad of any assistance. Even from a simple peasant.}
{1331}{}{Usually *we* help someone... But in this case, I will be glad of any assistance. Even from a simple peasant woman.}
{332}{}{What should I do?}

{333}{}{Talk to the communications officer at the radio station, she needed some hardware. As soon as you deal with this problem, come back to me.}
{334}{}{It doesn't sound difficult, I'll do it.}
{335}{}{Too long. But it looks like I don't have a choice.}

{336}{}{That's not all. There is a Quartz camp not far to the south. Recently, a group of migrants settled there, but scouts report that they all disappeared without a trace. Find out what happened there. By the way, the cartographer was interested in this area, talk to him too.}
{337}{}{I will sort out this dark story.}
{338}{}{In other words, they dumped something on me that you can't figure out yourself.}

{340}{}{And one more request. We lost one of our reconnaissance teams in the Mojave Desert to the north. There is no one to send for a rescue operation yet. Try to find out what happened to the Rangers.}
{341}{}{It will be done, Commander.}
{342}{}{Well, if I'm around, I'll try.}

{343}{}{Great, I'm waiting for the results. Free.}
{344}{}{[Leave]}

{350}{}{About the errands.}
{351}{}{Report.}
{352}{}{Honestly, there's nothing to report.}

{353}{}{The radio station is out of order. And it's not my fault.}
{354}{}{(irritated) I already know. You're of no use! (pulls himself together) Okay... Of course, I believe it's not your fault, because the Rangers' help was in your best interest.}
{355}{}{I'm sorry about that.}
{356}{}{Just don't yell at me.}
{357}{}{Can I clarify about the repair of the radio station?}
{358}{}{Talk to the communications officer about it. I'm only interested in the result.}
{359}{}{Okay, I'll talk to her.}
{360}{}{The radio station is in perfect order. I managed to modify it.}
{361}{}{Great job. The expansion of the broadcasting area will help our guys in combat and in peacetime. And that's what we've been missing. But I was also informed about some complications.}
{362}{}{That's right. Someone relayed the Rangers' talks to the east.}
{363}{}{So someone was spying on our broadcasts? This is not surprising. Our fight against crime causes rejection by many influential organizations in the east. The only strange thing is that someone else has mastered the technology of broadcasting. This is hardly possible for a simple gang from the wasteland. Thanks for the help. Your information may be useful in the future. And as a reward, you can take this hunting rifle.}
{364}{}{Glad to try.}
{1364}{}{Glad to try.}
{365}{}{The main thing is that it helps our union.}

{370}{}{I know what happened in Quartz.}
{371}{}{So what the hell is it?}
{372}{}{The locals stupidly caused the irradiation of the area, and they themselves went mad.}
{373}{}{All the information is in this holo.}
{374}{}{Uh, I have no idea.}
{375}{}{(sighs) Idiots... Here is an example of how thoughtless admiration for the technology of the Ancients destroys people. What were they thinking? That they can just run this old technology? Information about it was lost many generations ago! No wonder these fools paid so cruelly for their vanity.}
{376}{}{And yet they were almost there.}
{377}{}{It's all the better that now no one will get this relic.}
{378}{}{Perhaps so. Anyway, you did a good job. We'll put up warning signs around the perimeter and notify all patrolmen. Thank you for your cooperation.}
{1378}{}{Perhaps so. Anyway, you did a good job. We'll put up warning signs around the perimeter and notify all patrolmen. Thank you for your cooperation.}
{379}{}{You're welcome.}
{380}{}{OK.}

{390}{}{I want to report Ranger Garth's crimes.}
{391}{}{Aren't you taking on too much? I regularly have to deal with slander against the Rangers. Besides, Ranger Garth has a lot of good references. Anyway, I don't have time for this nonsense, get out of here.}
{392}{}{Um...}
{393}{}{And yet William Garth turned out to be a criminal. Who would have thought? So many awards and recommendations... You know, peaceful life has spoiled this soldier. Once "retired", he began to see any outsider as a potential enemy. I'm afraid to imagine what will happen to me in such conditions.}
{394}{}{We all have our own problems. This is normal, Commander.}
{395}{}{His story will be edifying for the rest of the rangers. And for you, Commander.}

#Additional quests
{400}{}{I want to continue helping the Rangers cause.}
{401}{}{Commendable zeal. We really need extra pairs of legs, arms and eyes.}
{402}{}{Great, I'm going to do something.}
{403}{}{Unfortunately, I'm not on my way. Maybe there are other tasks?}

{410}{}{I can help with long-range reconnaissance.}
{411}{}{That would be very helpful. We lost one of our reconnaissance teams in the north, in the Mojave Desert. There is no one to send for a rescue operation yet. Try to find out what happened to the Rangers.}
{412}{}{I'll do my best.}
{413}{}{Well, if I'm around, I'll try.}
{414}{}{Great, waiting for the report.}
{415}{}{Are there any more tasks?}
{416}{}{[Leave]}

{420}{}{Do you need a person to negotiate?}
{421}{}{There is one case just for you. We were waiting for a group of refugees from the east. But the scouts say that they turned off the path and moved towards Garage City. You'll probably be nearby, so look there and find out what made them change their route.}
{422}{}{Of course, I'll find these guys and shake the whole truth out of them.}

{430}{}{I managed to find refugees in Garage City. But they were already dead by my arrival.}
{431}{}{Damn it. What happened?}
{432}{}{They were killed like dogs. Locals don't like outsiders.}
{433}{}{Well, you could say they were in the wrong place at the wrong time.}
{434}{}{I have no idea.}
{435}{}{Eh. Even scavengers nowadays are ready to commit crimes because of hatred for outsiders. As you can see, this world needs a firm hand capable of keeping people behind the criminal line.}
{436}{}{[Next]}
{437}{}{Thank you for your cooperation. You're saving us a lot of extra work.}
{438}{}{You're welcome.}
{439}{}{It's not for you, but for the safety of the Villa.}
{440}{}{I managed to find refugees in Garage City. They were intimidated on behalf of the Rangers.}
{441}{}{So someone was posing as a ranger?}
{442}{}{Exactly. Here is the badge of this scoundrel. He won't bother you anymore.}
{443}{}{What tricks criminals will not go to to get their way. Surely he had many excuses for his lawlessness.}
{444}{}{[Next]}
{445}{}{This is not the first time someone has staged sabotage in order to undermine our reputation. There are forces in the east that have our actions across their throats. But the world is changing - if criminals used to be engaged in survival, now they are organized and sponsored by customers. But nothing - we will cope with this infection.}

{450}{}{I plan to stay here for a while. Are there any tasks closer to the base?}
{451}{}{We were informed about an epidemic in Aqueduct, this is one of the communities on the Colorado coast. Go there and find out how we can help.}
{452}{}{It will be done, Commander.}

{453}{}{I know what caused the epidemic - Flick's irradiated product.}
{454}{}{Did Flick sell radioactive products? There have been similar rumors behind him before, but no one has ever been able to prove his deceptions.}
{455}{}{Obviously, he won't bother anyone else except earthworms.}
{456}{}{Yes, I know about his death. Justice found him before we did. Thanks for the help, we'll figure it out for ourselves.}
{457}{}{Please.}
{458}{}{Goodbye.}
{459}{}{Now he will not be able to get away.}
{460}{}{Exactly. But Flick had already gone to the wasteland for the trading circle. Hurry up before he goes too far. You should take all his irradiated goods... any way.}
{461}{}{It will be done!}
{462}{}{Oh, to go roasting in the wasteland again...}
{463}{}{There will be no more problems from the Flick. Now he's trading in hell.}
{464}{}{Is Flick dead? Damn, I didn't expect that you would decide on such an extreme measure. However, I don't want to know anything about this story. Thanks for getting rid of this problem.}
{465}{}{Goodbye.}
{466}{}{Flick was left without his product. He will remember this lesson for a long time.}
{467}{}{Great job! Flick may be a son of a bitch, but he's also an irreplaceable merchant. It's good that he saved his life and lost only the goods. Unfortunately, we don't have a reward for such a case, so take some of my supplies. (gives two stimpacks and an antidote) You can sell it to someone if you don't need it.}
{468}{}{Glad to help.}
{1468}{}{I was glad to help.}
{469}{}{Not much, but better than nothing.}