#---------------------------------------------------------
#  Translated by Georg; revised by garwert.
#---------------------------------------------------------
{100}{}{You see Helford.}
{101}{}{You see one of the field commanders.}
{102}{}{Rescuing Jason increased your reputation among the Rangers.}

#First dialogue
{200}{}{(takes a quick look at you and continues examining some reports) You're speaking to Field Commander Helford. If you want to waste my time, you better go someplace else, because I've got work to do.}
{201}{}{Could you please spend a few minutes of your precious time for a poor campensino?}
{202}{}{I'm not here for idle talk, commander.}

#Repeated dialogue
{210}{}{How can I help you?}
{211}{}{Goodbye.}
{212}{}{Understood, you don't need to continue.}
{213}{}{May I ask a question?}
{214}{}{You may.}
{215}{}{One more.}

#Questions
{220}{}{How did you become a Ranger?}
{221}{}{I began learning at a young age and had a lot of practice in the desert. Serve the amount of time I did and maybe you too will become a field captain.}
{222}{}{What is this place?}
{223}{}{The main base of the Rangers, that's what it is. The command center is inside our power plant; here we do training and meet "guests".}
{224}{}{What "guests" are you talking about?}
{225}{}{Traders and representatives to negotiate with. If you didn't know, we are restoring order in this region. And for, that we need allies.}
{226}{}{I know little about the Rangers. Could you tell me more?}
{227}{}{The Rangers are elite fighters and masters at surviving in the desert. These skills allow us to enforce law and order in the Wastes. Bringing the Law back to these lands is our primary mission.}
{228}{}{You do it for free?}
{229}{}{Our territories are taxed and are subject to some restrictions. If people refuse to adopt the Law and our other conditions, we refuse to help them.}
{230}{}{What is this "Law" you are talking about?}
{231}{}{A small collection of rules and forbidden actions which must be strictly adhered to. Those who gravely violate the Law receive punishment, usually of a lethal nature.}

#Ranger -- Jackals
{233}{}{But thank you for assisting in the search regardless. Those savages sucked out too much blood from our brother. I'm very glad they paid for it with their lives.}
{234}{}{That is no longer necessary. We've discovered the remains of a patrol in the lair of the Jackals to the north. You already know about that place.}
{235}{}{Didn't expect that. Sad.}
{236}{}{How do I find the missing patrol?}
{237}{}{You could probably track their coordinates with a radio, if theirs still works. Perhaps others heard of the patrolmen in nearby settlements. Or you could just go into that region and try to find the Rangers blindly in the desert.}
{238}{}{I hope it won't get to that, the last part doesn't seem fun at all.}

{239}{}{Surprisingly, the Jackals are ready to form an alliance.}
{240}{}{Out of the question! The Jackals are cunning and aggressive, they don't negotiate. If they need an alliance, then I'm sure it is just a trick that they are planning to benefit from, nothing else. I'm certain the general would fully agree with me.}
{241}{}{The Rangers in the northern patrol are dead. The Jackals killed them.}
{242}{}{Dammit... I felt that this was the most likely thing to have happened to them. Those savages sucked out too much blood from our brother. But thank you for assisting in the search. I'll file an investigation report to the general.}
{243}{}{You're welcome.}
{244}{}{The Ranger from the northern patrol is back. But just him.}
{245}{}{I was already told. Excellent work, Ranger. Keep it up.}
{246}{}{I was already told. Excellent work, peasant. I see you got what it takes to do the job, something we often lack here. Keep it up.}
{1246}{}{I was already told. Excellent work, peasant. I see you got what it takes to do the job, something we often lack here. Keep it up.}
{247}{}{You're welcome.}
{248}{}{What do you think about the Jackals?}
{249}{}{The Jackals are one of the most disgusting gangs in the Wastes. They have regressed so much you can't distinguish their young from dogs. My heart aches when I see that an entire nation has resorted to living like this. Cannibalism, a ridiculous cult, hostility to all outsiders, even neighboring clans - can you go any lower?}

#Criminal's family
{250}{}{What do you say to justify murdering the husband of that woman? }
{251}{}{Ah, that lady hooked you too? Listen, her husband was a criminal. He stole from farmers and attacked travelers. For this he was justly executed in accordance with the Law. Nobody could have thought he had a family.}
{252}{}{[Continue]}
{253}{}{For you, it is just a story. And to be honest, for me, too. But you have no idea what kind of folly a female radscorpion can do. Something has to be done about this.}
{254}{}{[Continue]}
{255}{}{I suppose you could talk sense into her. No offense, but you look more like a peasant than a Ranger, and that means you will get her trust more easily.}
{256}{}{What do I need to do?}
{257}{}{Just explain to her that she is no longer welcome here. It would be better for everyone if she and her little offspring went away somewhere else.}
{258}{}{Okay, I'll try to.}
{259}{}{I'm not going to deal with other people's problems.}
{260}{}{I see you managed to deal with that bitch. Good diplomacy. Here, take a bit of ammo from me personally, as a sign of gratitude.}
{261}{}{You're welcome.}
{262}{}{Wait a minute. I was told of a tragic event. The ferryman was found dead and you were recently seen with the refugees on the ferry. An interesting coincidence, don't you think?}
{263}{}{I, uhh, had nothing to do with it.}
{264}{}{I hope that is the case. Because sooner or later, our guys will get to the truth. And you know how we enforce the Law, especially so close to our citadel.}
{265}{}{Of course, uhh, you will surely find those responsible. And now I better get out of here...}

#Farm spy
{270}{}{I'm here to report a spy. He is hiding in the shack on the old road...}
{271}{}{...Thanks for the tip. We'll send scouts there and will try to catch him off-guard. Time to get the bastard.}
{272}{}{Wish you luck.}
{273}{}{Did you know that the quartermaster has a missing weapon?}
{274}{}{No, I was not informed of that, nor do I need to be. I have more important things to do than to concern myself with his problems.}
{275}{}{I understand.}

#Stop-dialogue
{280}{}{Dammit... You're like those ghouls from the south. No offense, but you should be careful appearing in public.}
{281}{}{I know. Not the first time.}

{282}{}{You have the audacity to come here after what you did?}
{283}{}{He sold me shoddy goods.}
{284}{}{And you're ready to kill a man for that? Damn, did it ever occur to you that the punishment should fit the crime?}
{1284}{}{And you're ready to kill a man for that? Damn, did it ever occur to you that the punishment should fit the crime?}
{285}{}{Nope.}
{286}{}{I am infinitely repentant for what I did. }
{287}{}{His guard attacked first.}
{288}{}{That is, his idiot son? We often expected him to behave inadequately, but so far we managed without fights. Well, I'll have to believe this story. But couldn't you just run away?}
{289}{}{So what do I have to do with this?}
{290}{}{You're telling me that you just happened to be there? And that you have nothing to do with the death of the trader? Shit, without witnesses that will be hard to disprove.}
{1290}{}{You're telling me that you just happened to be there? And that you have nothing to do with the death of the trader? Shit, without witnesses that will be hard to disprove.}
{291}{}{It happened just as you described, commander.}
{292}{}{(shakes head) Hillbillies... Shouldn't have expected anything less. You're lucky nobody saw the crime and that Flick's reputation was as shoddy as his goods. You can go now. But don't forget, we are here to keep the peace.}
{293}{}{As you say, commander.}
{294}{}{Better this way. For now I'll believe you, but don't forget that we are here to keep the peace. You can go now.}
{295}{}{Thank you, commander.}
{296}{}{Uhh...}
{297}{}{Okay, I'll listen what happened between you and Flick first.}

#Villa -- Protection
{300}{}{I'm here on behalf of Villa. We need the Rangers' help.}
{301}{}{I am asking for help in freeing Villa's peasants from slavery.}
{302}{}{The peasants of Villa still need help.}
{303}{}{(stops reading his reports, frowning) Villa is that oasis, where by some miracle, maize is grown in the middle of the desert? You have my condolences. This is a hard time for many. The red scourge from Phoenix is expanding across the entirety of Arizona, enslaving the population and taking control of resources.}
{304}{}{I remember our conversation about Villa.}
{305}{}{So you will help?}

{306}{}{Unfortunately, we don't have enough Rangers for that. We have deployed all our forces in other directions.}
{307}{}{A pity.}
{308}{}{No help from you Rangers at all.}
{309}{}{}
{310}{}{First, complete my assignments, as we agreed upon. Until then, I can't allow you to visit the general and especially recall people from other missions.}
{311}{}{I completed all of your assignments.}
{1311}{}{I completed all of your assignments.}
{312}{}{That seems to be the case. To be honest, I did not expect this and gave you the assignments so that you wouldn't bother me. It's pleasant to see such diligence.}
{313}{}{[Continue]}
{314}{}{But regarding the Villa situation, that question must be resolved by the general himself. Go directly to him, I'll tell the guards to let you pass. What happens next depends on how your conversation with him goes.}
{315}{}{Thank you, commander.}
{316}{}{Okay. If all this running around was for nothing, I'll make sure to mess up your Rangers' reputation.}

{320}{}{The general promised to send some people to assist Villa.}
{321}{}{Dammit, you managed to convince the old man?! We have more important things to do than saving the skin of some arrogant peasants. You always saw us as bandits. But an order is an order. From now on, the Villa has reliable protection.}
{322}{}{To be perfectly honest, I'm not happy with this deal. You, Villa's peasants, always saw us as bandits. And when the situation becomes critical you try to use us. But don't worry, we keep our promises - from this day on, the Villa is under reliable protection. I very much hope this alliance doensn't turn out to be just empty words.}
{323}{}{I understand you, commander. I hope we will manage to work together.}
{324}{}{With that attitude it's no surprise the Rangers have so many enemies. Goodbye... "amigo".}

#Main quests
{330}{}{Perhaps I could help you somehow?}
{331}{}{Usually *we* help others... But in this situation I'm glad to have any assistance. Even from a mere peasant.}
{1331}{}{Usually *we* help others... But in this situation I'm glad to have any assistance. Even from a mere peasant.}
{332}{}{What do I need to do?}

{333}{}{Talk to the communications officer at the radio station, she needed some scrap. When you take care of that problem, return to me.}
{334}{}{Doesn't sound too hard, I'll do it.}
{335}{}{That will take long. But it doesn't look like I have a choice.}

{336}{}{That's not all. Not far to the south there is the Quartz camp. Some time ago a group of settlers moved there, but scouts report they all dissapeared without a trace. Go there and find out what happened. Oh, and by the way, a cartographer is interested in that region, go talk to him as well.}
{337}{}{I'll find out the truth behind this dark story.}
{338}{}{In other words, you're making me do something you don't want to deal with yourself.}

{340}{}{And one other request. We lost one of our scout groups in the Mojave desert to the north. Right now we can't send anyone to do a rescue operation there. Try to find out what happened to the Rangers.}
{341}{}{Will do, commander.}
{342}{}{Well, I'll consider it if I happen to be near that place.}

{343}{}{Great, I'm waiting for results. Dismissed.}
{344}{}{[Leave him alone]}

{350}{}{Regarding the assignments.}
{351}{}{Report.}
{352}{}{To be honest, there's nothing to report.}

{353}{}{The radio station went offline. And it was not my fault.}
{354}{}{(irritated) I already know. You're no help at all! (calms down) Okay... Of course I believe it is not your fault. After all, getting Rangers on your side is in your best interest.}
{355}{}{I'm sorry about what happened.}
{356}{}{Don't you scream at me like that.}
{357}{}{Can you elaborate on repairing the radio station?}
{358}{}{Talk about that with the communications officer. I'm only interested in your results.}
{359}{}{Okay, I'll go talk to her.}
{360}{}{The radio station is now operational. I managed to modify it.}
{361}{}{Great work. Expanding the broadcasting area will help our guys both in times of peace and in times of war. And that is what we lacked so much. But I was also told of some complications.}
{362}{}{Exactly. Someone relayed conversations between Rangers to the east.}
{363}{}{So someone was spying on our broadcasts? That is not surprising. Our fight against crime makes us disliked by many influencial organizations to the east. The only strange this is that someone else figured out broadcasting technology. That's hardly possible for some simple wasteland gang. Thanks for the help. Your information may prove useful in the future. Here, take this hunting rifle. Since you've been helping us, you might be a target.}
{364}{}{Happy to help.}
{1364}{}{Happy to help.}
{365}{}{Hopefully this helps further our alliance.}

{370}{}{I know what happened in Quartz.}
{371}{}{So what was it, dammit?}
{372}{}{The locals were stupid enough to irradiate the area; then went insane because of it.}
{373}{}{This holotape contains all the information.}
{374}{}{Uhh, I have no idea.}
{375}{}{(sighs) Fools... This is an example of how thoughtless admiration of Ancient technology hurts people. What were they thinking? That they can just activate that pre-War machinery? The information about it was lost generations ago! No wonder those idiots paid heavily for their vanity.}
{376}{}{And yet they were very close to reaching their goal.}
{377}{}{All the better. Now nobody will be able to get their hands on that relic.}
{378}{}{Perhaps. In any case, you did good today. We'll set up warning signs on the perimeter and notify all patrols. I'm very grateful for your help.}
{1378}{}{Perhaps. In any case, you did good today. We'll set up warning signs on the perimeter and notify all patrols. I'm very grateful for your help.}
{379}{}{You're welcome.}
{380}{}{Okay.}

{390}{}{I want to report the crimes of Ranger Gart.}
{391}{}{Aren't you overstepping the mark here a little too much? I regularly encounter slander against Rangers. And Ranger Gart has many good recommendations. All in all, I don't have time for this nonsense. Get outta here.}
{392}{}{Umm...}
{393}{}{So, William Gart ended up being a criminal. Who could've thought? So many awards and recommendations... You know, it's living in peace that messed up this old figher. When he became "retired", he began to see a potential enemy in every outsider. I'm afraid to imagine what will become of me in such conditions.}
{394}{}{We all have our own personal problems. And that's okay, commander.}
{395}{}{His story will become a lesson for the other Rangers. And for you, commander.}

#Side quests
{400}{}{I wish to continue supporting the Ranger cause.}
{401}{}{Such enthusiasm is commendable. We truly do need additional pairs of legs, hands and eyes.}
{402}{}{Great, I'll go do something.}
{403}{}{Unfortunately that is not where I plan to go. Perhaps there are other assignments?}

{410}{}{I can help with long-range reconnaissance.}
{411}{}{That would be very helpful. We lost one of our scout groups in the Mojave desert to the north. There's nobody we can send on a rescue operation right now. Try to find out what happened to the Rangers.}
{412}{}{I'll do what I can.}
{413}{}{If I happen to be nearby, I'll consider it.}
{414}{}{Great, I'm waiting for a report.}
{415}{}{Got any more of them assignments?}
{416}{}{[Leave]}

{420}{}{You need someone to do some negotiation?}
{421}{}{There's one mission just for you. We were waiting for a group of refugees from the east. But scouts say they went toward Garage City instead. You likely have to go there anyways, so take a look and find out what made them change their course.}
{422}{}{Of course, I'll find those guys and get the truth out of 'em.}

{430}{}{I managed to find refugees in Garage City. But they were already dead by the time I arrived.}
{431}{}{Dammit. What happened?}
{432}{}{They were put down like dogs. Locals don't take kindly to outsiders.}
{433}{}{Well, one can say they ended up in the wrong place at the wrong time.}
{434}{}{I have no idea.}
{435}{}{Eh. Even scavengers are ready to commit crime out of hate toward outsiders in our times. As you see, this world needs a firm hand, able to keep people out of the point of crime.}
{436}{}{[Continue]}
{437}{}{I thank you for your assitance. You are continuing to rid us of excess work.}
{438}{}{You're welcome.}
{439}{}{This isn't for you, this is for Villa's safety.}
{440}{}{I managed to find refugees in Garage City. They were intimidated by a "Ranger".}
{441}{}{So someone pretended to be a one of us?}
{442}{}{Exactly. Here's the bastard's badge. He won't bother you anymore.}
{443}{}{What tricks criminals *won't* use to get what they want. I'm sure he had many justifications for his for his lawlessness.}
{444}{}{[Continue]}
{445}{}{This isn't the first time someone did something like this with the intent of ruining our reputation. There are powers in the north that hate us for what we do. But the world is changing - in the past, criminals were busy with basic surival; now they are organized and sponsored by their clients. But it's okay - we'll deal with that scourge too.}

{450}{}{I plan to stay here for a while. You got any assignments closer to the base?}
{451}{}{We were told of an epidemic in the Aqueduct, that's one of the communities on Colorado's coast. Go there and find out how we can help.}
{452}{}{Will do, commander.}

{453}{}{I know what caused the epidemic - Flick's radiated goods.}
{454}{}{Flick sold radioactive goods? He had some rumours about him like this before, but nobody could ever prove his guilt.}
{455}{}{It seems he'll never bother anyone but earthworms now.}
{456}{}{Yes, I know of his demise. Justice found him before we did. Thanks for the help, we'll deal with this ourselves from now on.}
{457}{}{My pleasure.}
{458}{}{Goodbye.}
{459}{}{He won't wriggle out of this, not this time.}
{460}{}{Damn right. But Flick already left for the wasteland to his trading circle. Hurry before he walks too far away from here. You should take all his radiated goods... with whatever means necessary.}
{461}{}{Will do!}
{462}{}{Ugh, I'll have to go fry in the desert once again...}
{463}{}{There won't be any more problems from Flick ever again. Now he's trading his wares in hell.}
{464}{}{Flick's dead? Damn, I didn't think you were willing to go this far. Not that I want to hear about that story ever again. Thanks for getting rid of that problem.}
{465}{}{Goodbye.}
{466}{}{Flick's now without his goods. He'll remember this lesson for a long time.}
{467}{}{Great work! Flick may be a son of a bitch, but he's also an indispensable trader. It's good that he only lost his goods, not his life. Unfortunately, we don't have a reward for this kind of situation, so take some of my supplies. (gives two stimpacks and an antivenom) You could sell these if you don't need them.}
{468}{}{Glad to help.}
{1468}{}{Glad to help.}
{469}{}{Not the best reward, but better than nothing.}
