#---------------------------------------------------------
#  Translated by Georg; revised by garwert.
#---------------------------------------------------------
{100}{}{You see a sick man.}
{101}{}{You see a sick man. He looks feverish and really thirsty.}
{102}{}{Your examination has revealed that the patient is suffering from radiation sickness.}
{103}{}{Patient is ready for examination.}

{210}{}{(you see a sick villager; he is suffering from thirst, cold sweat, chills and dyspnea)}
{211}{}{[Leave the sick man alone]}
{212}{}{How are you feeling, buddy?}
{213}{}{Cough-cough... getting back to normal. Yesterday it was very bad, I didn't think I would survive.}
{214}{}{What do you think caused the illness?}
{215}{}{Nothing I can think of. We ate the same fish we usually eat, we went to the same places as before.}
{216}{}{Could you have contracted it from someone else?}
{217}{}{Probably... cough-cough... But then others would have been infected too.}
{218}{}{I need to know the cause of the illness. Can I examine you?}
{219}{}{Okay. Do I need to take off my clothes?}
{220}{}{Yeah...}
{221}{}{Alright.}
{222}{}{Looks like you'ven been exposed to heavy doses of radiation.}
{223}{}{What? How? There aren't any real sources of radiation around here.}
{224}{}{Then the radiation came from outside. What have you eaten lately?}
{225}{}{Just fish and bread given out in the community... No, wait, I also bought some Nuka-Cola from Flick. You think a couple of bottles could have irradiated me?}
{226}{}{It's within the realm of possibility. I should check that out...}
