{100}{}{You have a patient in front of you.}
{101}{}{You see a sick person. He is tormented by thirst and chills.}
{102}{}{The examination showed that the patient was suffering from the effects of radiation sickness.}
{103}{}{The patient is ready for examination.}

{210}{}{(here is a sick villager; he is tormented by thirst, cold sweat, chills and shortness of breath)}
{211}{}{[Leave the patient]}
{212}{}{How are you feeling, buddy?}
{213}{}{Cough-cough... I'm getting back to normal. Yesterday it was really bad, I thought I wouldn't survive.}
{214}{}{What do you think caused the disease?}
{215}{}{Nothing comes to mind. We ate the same fish as usual, went to the same places as before.}
{216}{}{Could you have been infected by someone else?}
{217}{}{Maybe... cough-cough... But then others would have been infected.}
{218}{}{I need to know the cause of the illness. Can I examine you?}
{219}{}{Okay. Take off your clothes?}
{220}{}{Yeah...}
{221}{}{I see.}
{222}{}{It looks like you're suffering from a serious dose of radiation.}
{223}{}{What? But how? There are no powerful sources of radiation here.}
{224}{}{So the radiation came from outside. What have you been eating lately?}
{225}{}{Only fish and bread, which is distributed in the community... No, wait, I also bought a core Cola from Flick. Do you think a couple of bottles could have irradiated me?}
{226}{}{It is not excluded. I should check it out...}