{100}{}{You see Old Rufus.}
{101}{}{Here is the dam keeper, an unshaven, wiry old man in overalls.}

#The first dialog
{200}{}{(you see a gray-haired, unshaven man of about fifty; dirty work clothes on him betray his occupation) What? I'm sorry, I've become a little deaf. Work for so many years among these noisy machines and you will also go deaf.}
{201}{}{I will keep in mind.}
{202}{}{And who are you? I don't remember you, but I know everyone here. Recruits are usually not allowed to the station, and the quartermaster does business with the caravans. So...}
{203}{}{I'm here on business.}
{204}{}{Yeah. On business. Let it be so. The main thing is not to interfere with other things to do.}
{205}{}{What are you doing, old man?}
{206}{}{Then I won't interfere.}

#Repeat dialog
{210}{}{Speak up, what are you mumbling about?}
{211}{}{I say goodbye.}
{212}{}{I need to ask something else.}
{213}{}{Another question.}

#Questions
{220}{}{And who are you, exactly?}
{221}{}{My name is Rufus. I'm the dam keeper. I make sure that nothing falls apart here.}
{222}{}{What is your rank, Rufus?}
{223}{}{I don't have any rank. I'm doing business here, not currying favor.}
{224}{}{How long have you been in office?}
{225}{}{Let me think, it's been thirty years, probably. No one here counts the year.}
{226}{}{Why did the Rangers settle on this dam?}
{227}{}{There are many reasons for this: it is an impregnable fortress for enemies, protection from dust storms, an abundant source of water and endless energy. We can say that it happened historically.}
{228}{}{I'm the dam keeper. I make sure that nothing falls apart here.}
{229}{}{So what are you doing, Rufus?}

{230}{}{Is the aqueduct also part of the power plant?}
{232}{}{No, no, the station works without an aqueduct. But the aqueduct would not be able to perform its functions without our dam. However, it still doesn't work anymore.}
{231}{}{What's wrong with him?}
{233}{}{Time takes its toll. The pumps have been out of order for a long time and it is impossible to repair them. In addition, the flow of water in the river has decreased. But even if the aqueduct was working, it would be idling. After all, there are no more plantations and settlements on his path that would benefit from this water.}
{234}{}{An amazing structure. Who built all this?}
{235}{}{The people of the past were smart. No one living today is capable of such a thing.}
{236}{}{Have you forgotten that they destroyed themselves with their own mind?}
{237}{}{Yes... But this does not negate the fact that they created an aqueduct to irrigate desert lands.}

#The first quest
{250}{}{Is there such a risk?}
{251}{}{Oh, this old lady has seen the sights! This controller, for example, does not want to work in any way. And there is nowhere to find a replacement - all the equipment here is unique.}
{252}{}{So this thing doesn't work? Maybe I can fix it?}
{253}{}{Where are you going! Here you can hardly do with skills alone. However, you travel a lot, right? If you find parts from electronic equipment, then bring them here, maybe they can be restored with their help.}
{254}{}{I'll see what I can do.}
{255}{}{I'm afraid that's really not my profile. But I can find the details.}
{256}{}{That's good. And while you're making a hero out of yourself, I think I'll get busy. No offense.}
{257}{}{Uh, no, I need to know more.}
{258}{}{Then we'll talk later.}

{260}{}{Let's talk about that broken controller?}
{261}{}{Eh? What are you up to?}
{1261}{}{Eh? What are you up to?}
{262}{}{Yes, the question is about nothing.}

{263}{}{What's the problem with getting parts from electronics?}
{264}{}{Do you think we haven't been looking? All patrols and traders are aware. But there is a rural area in the district, where can electronics come from here? And it's far and expensive to drive from big cities. There are plenty of their customers there.}
{265}{}{Why do we need this controller?}
{266}{}{Look at that big thing in the middle of the hall. Inside she has a screw submerged in the water of the Colorado River. It turns and generates electricity... You know what "electricity" is, right?}
{267}{}{I think I can guess...}
{268}{}{Through the controller, the current is directed to the power transformers outside, and then to the power lines. But now nothing works there - just bare and useless wires.}
{269}{}{I need to know more.}

{270}{}{I managed to fix the equipment.}
{271}{}{Keep in mind that Rangers sometimes have problems with humor. Especially on the topic of this dam.}
{272}{}{But it works. Take a look.}

{273}{}{Well, let's see... Holy heavens, it really worked!}
{274}{}{This job is not for nothing, you know.}
{275}{}{Yes... of course. Here's a pack of nuclear batteries for your trouble. If you don't need them, exchange them in the nearest city for something useful.}
{276}{}{You're welcome.}
{277}{}{Rangers don't forget their friends. Here's a pack of nuclear batteries for your trouble. If you don't need them, exchange them in the nearest city for something useful.}
{278}{}{[Next]}
{279}{}{Thank you. It's a pity that you won't be able to replace me in this post when I retire. Now leave me with this baby for a while. She needs extra care.}
{280}{}{Okay, I'll be back later... when you bring this iron to life.}
{281}{}{Don't overdo it, old man. The wires can respond to your caresses with an electric current.}
{282}{}{}
{283}{}{Where can I find parts from electronics?}
{284}{}{The nearest place I know of is Garage City. Yes, but we have already sent a request there.}

#The second quest
{300}{}{How does the station work after repair?}
{301}{}{That's great! The repair of the station is not in danger in the coming years. It's a pity that you won't be able to replace me in this post when I retire.}
{302}{}{So you're the one manning the dam?}
{303}{}{(sighs) Sometimes I listen to the noise of hydraulic units. Their rusty rotation reminds me of the years I've lived.}
{304}{}{So you need a shift.}
{305}{}{That's right, sir. This station needs a new caretaker - a young man gifted with technical skills, and you won't find such people in our time during the day with fire.}
{1305}{}{That's right, ma'am. This station needs a new caretaker - a young man gifted with technical skills, and you won't find such people in our time during the day with fire.}
{306}{}{Is there anyone in mind?}
{307}{}{The caravaneers told about one such young talent. He lives in Garage City and suffers from a waste of time. I would like to take a look at him and bring him up to replace me. The problem is that the local population treats the Rangers without much sympathy, you know? And you can't just come and pick up the child, you need him to want to.}
{308}{}{I'll take the job.}
{309}{}{Whoever wants something in that dump, and I'll bring you a kid.}
{310}{}{Well, it looks like you'll have to look for a replacement elsewhere. Bye, old man.}
{311}{}{What a determination! It distinguishes greens from old people. Agreed. I will be waiting for your return.}
{312}{}{Later.}

{320}{}{Bad news - that guy from Garage City died on the way.}
{321}{}{Sorry for the guy, he would be extremely useful to the Rangers in the future... Well, we'll have to work with local guys, although there is not a single one among them who is passionate about technology. I don't have any more assignments for you either. Thank you for your service.}
{322}{}{Will I get nothing for my efforts?}
{323}{}{Your labors were useless. Go somewhere already, don't interfere with work.}
{324}{}{That's it, then...}

{330}{}{This is the gifted guy you were looking for.}
{331}{}{Hello, son! Here, at the Rangers, you will surely like it. I can see it in your eyes. But first you need to wash a little...}
{332}{}{Ahem...}
{333}{}{...And you've done a great service to the Rangers by bringing this guy in. Look to the quartermaster, let him pick up a reward for you.}
{1333}{}{...And you've done a great service to the Rangers by bringing this guy in. Look to the quartermaster, let him pick up a reward for you.}
{334}{}{Great, wait for me, reward! I'm on my way.}