{100}{}{You see Old Man Rufus.}
{101}{}{You see the overseer of the dam, an unshaven, wiry old man in overalls.}

#Первый диалог
{200}{}{(you see a bald, unshaven man around 50 years old; the dirty overalls he wears reveals the kind of job he has) Eh? Sorry, my hearing's not that good nowadays. Work as many years as I did around these loud machines and you'll get deafness too.}
{201}{}{Will keep that in mind.}
{202}{}{And who are you? I don't remember you, and I know everyone around 'ere. Rookies aren't usually allowed at the plant, and the quartermaster deals with the caravans. Meaning...}
{203}{}{I'm here for business.}
{204}{}{Uh-uh. For business. So be it. Just don't interfere with others' business.}
{205}{}{So, what are you doing here, old man?}
{206}{}{Then I won't disturb you any longer.}

#Повторный диалог
{210}{}{Speak louder, why are you mumbling?}
{211}{}{I said "goodbye".}
{212}{}{I need to ask about another thing.}
{213}{}{Another question.}

#Расспросы
{220}{}{And who are you?}
{221}{}{I'm called Rufus. I'm the dam's overseer. I make sure nothing breaks down here.}
{222}{}{What's your rank, Rufus?}
{223}{}{I don't have a rank. I'm working here, not serving.}
{224}{}{How long have you been in this position?}
{225}{}{Let me think, 30 years, probably. Nobody here counts years.}
{226}{}{Why have the Rangers chosen this dam as their headquarters?}
{227}{}{Oh, many reasons: it's an impregnable fortress for enemies, it defends against dust storms, it's an abundant source of water and endless energy. You can say it happened historically.}
{228}{}{I'm the dam's overseer. I make sure nothing breaks down here.}
{229}{}{So what is it exactly you do here, Rufus?}

{230}{}{The aqueduct is part of the power plant too?}
{232}{}{No, no, the plant works without the aqueduct. The aqueduct would not be able to perform it's functions without our power plant. In any case, it stopped working a long time ago.}
{231}{}{What's wrong with it?}
{233}{}{Time takes it's toll. The pumps went offline a long time ago and are impossible to repair. Besides, the amount of water in the river is much lower. But even if the aqueduct did work, it would be useless. Since there are no more plantations and settlements along the way that would have a use for that water.}
{234}{}{An amazing structure. Who built it?}
{235}{}{The people of the past were smart. Nobody alive today can create such a thing.}
{236}{}{You forgot they also destroyed themselves with that exact intellect?}
{237}{}{Yes... But that doesn't change the fact that they created an aqueduct to irrigate the desert.}

#Первый квест
{250}{}{There's such a risk?}
{251}{}{Oh, that old lady has seen much! That controller, for example, just doesn't want to work. And we can't find a replacement - all the equipment here is unique.}
{252}{}{So that thing doesn't work? Perhaps I could fix it?}
{253}{}{Heck no! You can't do this with just skill. Though you do travel a lot, right? If you find components of electronic equipment, then bring em' here, maybe we could restore it using them.}
{254}{}{I'll see what I can do.}
{255}{}{I'm afraid repair's really not my thing. But I could find the details.}
{256}{}{Great. While you here pretend to be a hero, I'll maybe go do something. No offense.}
{257}{}{Uhh, no, I need to know more.}
{258}{}{Then we'll talk later.}

{260}{}{Can we talk about that idle controller?}
{261}{}{Eh? What were you thinking of?}
{1261}{}{Eh? What were you thinking of?}
{262}{}{Nothing, just a pointless question.}

{263}{}{What's the problem with getting electronic components?}
{264}{}{You think we haven't searched for 'em? All patrols and traders are aware. But everywhere 'round here is just a big rural area, where do you get electronics from in places like this? Transporting them from big cities is costly and long. They have enough of their own customers.}
{265}{}{Why is that controller needed?}
{266}{}{Look at that big thing in the center of the hall. There's a screw inside it, submerged into the Colorado river's water. It spins and generates electricity... You do know what "electricity" means, right?}
{267}{}{I guess I do...}
{268}{}{The electic current heads through the controller to the power transformers outside, and then to the power lines. But now nothing works there - only bare and useless wires.}
{269}{}{I need to know more.}

{270}{}{I managed to repair the equipment.}
{271}{}{You should keep in mind that Rangers sometimes have problems understanding humour. Especially regarding this dam.}
{272}{}{But it does work. Take a look.}

{273}{}{Welp, let's have a look... Good heavens, it really is working!}
{274}{}{This isn't volunteer work I'm doing here, as you understand.}
{275}{}{Yes... of course. Here, take a bunch of nuclear batteries for your trouble. If you don't need 'em, exchange them in some neighboring town for something useful.}
{276}{}{You're welcome.}
{277}{}{The Rangers don't forget their friends. Here, take a bunch of nuclear batteries for your trouble. If you don't need 'em, exchange them in some neighboring town for something useful.}
{278}{}{[Continue]}
{279}{}{Thanks. It's a shame you can't replace me on this post when I retire. Now if you were so kind to leave me with this baby for some time. She needs additional care.}
{280}{}{Okay, I'll come back later... when you bring this hunk of metal to life.}
{281}{}{Don't try too hard, old man. The wires may respond to your petting with electic current.}
{282}{}{}
{283}{}{Where can I find electronic components?}
{284}{}{Nearest place I know of is Garage-City. We sent a request there some time ago already, though.}

#Второй квест
{300}{}{How does the plant work after I fixed it?}
{301}{}{Very well! I don't see any repairs being needed for the plant in the coming years. It's a shame you won't be able to replace me on this post when I retire.}
{302}{}{So you service the dam alone?}
{303}{}{(sighs) Sometimes I listen to the hum of the hydraulic units. Their rotation, squeaky with rust, reminds me of the years gone by.}
{304}{}{So you need a replacement.}
{305}{}{Exactly, sir. This plant needs a new overseer - a young man, gifted in technical skills, and those are hard to find these days.}
{1305}{}{Exactly, ma'am. This plant needs a new overseer - a young man, gifted in technical skills, and those are hard to find these days.}
{306}{}{Is there anyone you're keeping an eye on?}
{307}{}{The caravaneers told about one such young, gifted mind. He lives in Garage-City and suffers from pointlessly wasting his time. I'd like to take a look at him and train him to be my replacement. Problem is the residents don't take too kindly to the Rangers, understand? And you can't just go and take the kid, you need him willing to go.}
{308}{}{I'll take on this job.}
{309}{}{Whoever wants him in that scrapyard, I'll bring you the kid.}
{310}{}{Welp, looks like you'll have to find a replacement in another place. So long, old man.}
{311}{}{That's the spirit! That's the thing that separates the greens from the old. Deal. Will await your return.}
{312}{}{Bye.}

{320}{}{Bad news - the guy from Garage-City died along the way.}
{321}{}{A pity about the guy, he would have been very useful to the rangers in the future... Oh well, I'll have to work with the local guys, even though there isn't anyone particularly interested in technology among 'em. I don't have any more assignments for you. Thank you for your service.}
{322}{}{So I won't receive anything for my troubles?}
{323}{}{Your troubles ended up being fruitless. Go somewhere else already, don't bother me, I'm working.}
{324}{}{So that's how it is, then...}

{330}{}{Here's the gifted guy you were searching for.}
{331}{}{Hi, son! You'll probably like it here, among the Rangers. See it in your eyes. But first you can certainly use a shower....}
{332}{}{Ahem...}
{333}{}{...And you have done an excellent service to the Rangers by bringing this guy here. Take a visit to the quartermaster, let him choose a reward for you.}
{1333}{}{...And you have done an excellent service to the Rangers by bringing this guy here. Take a visit to the quartermaster, let him choose a reward for you.}
{334}{}{Great! Wait for me, reward, I'm already on my way.}
