{100}{}{You see Flick's guard.}
{101}{}{You see a mentally deficient, but musled man.}

{110}{}{Talk to Flick, he knows everything.}
{111}{}{Flick's smart, he exchanges unwanted for useful.}
{112}{}{You need useful things? Master has everything.}
{113}{}{Me guard goods, got it?}
{114}{}{You got fire water?}
{115}{}{When Flick does boo-boo, me cry.}
{116}{}{Don't you dare steal from Master.}
{117}{}{Me break hands of people who steal from Flick.}
{118}{}{Me will watch you.}
{119}{}{Want me to hit you with spear?}
{120}{}{Master says we need to go.}
