{100}{}{Flick's guard is in front of you.}
{101}{}{You see an imbecile jock.}

{110}{}{Talk to Flick, he knows everything.}
{111}{}{Flick is smart, he changes unnecessary to necessary.}
{112}{}{Do you need useful things? The owner has everything.}
{113}{}{I'm just guarding the goods, got it?}
{114}{}{Do you have firewater?}
{115}{}{When Flick does bo-bo, I cry.}
{116}{}{Don't try to rob the owner.}
{117}{}{I break the hands of those who steal from Flick.}
{118}{}{I'll be watching you.}
{119}{}{Do you want to hit with a spear?}
{120}{}{The owner says it's time to go.}