{100}{}{You see Flick the trader.}
{101}{}{You see Flick the wandering trader.}
{102}{}{No more nuka-cola... honest.}
{103}{}{The merchant lost his harmful goods. Only thing left is report the success to commander Helford.}

#Начало диалога
{200}{}{Hey, wanderer, you need any useful things for your travels? I can get you absolutely anything... Wait, I already sold all my goods to those Rangers. Shit.}
{201}{}{So you're a trader?}
{202}{}{Name's Flick. I trade some stuff in Ranger territory. What are you looking for? Tell me, maybe I know where to find it?}
{203}{}{I doubt you have what I need. So long, Flick.}

{210}{}{What are you looking for? Tell me, maybe I know where to find it?}
{211}{}{So long.}
{212}{}{Let's change the subject.}

#Вопросы
{220}{}{What exactly do you trade, Flick?}
{221}{}{Whatever I manage to - food, clothing, utensils. But now I have nothing left but caps.}
{222}{}{What's the deal with those caps?}
{223}{}{You don't know? In a big city to the east someone thought of using bottle caps as currency. As in, exchange them for goods. Strange idea, but convenient! Only problem is the Rangers don't recognize caps and refuse to trade for them.}
{224}{}{Why's that?}
{225}{}{Well, they consider currency to be a speculative thing. Since you never know the true value of caps. But bartering is fair and not subject to some "in-flation". But still, many now have bags for caps, maybe the Rangers too will be forced to change their ways.}
{226}{}{How interesting. Let's talk some more, since you don't seem to be in a hurry.}
{227}{}{I'm concerned about my family, not currency. So long.}

{230}{}{Where did you get that brahmin?}
{231}{}{Bought it, from pastoralists in a neighboring town. It was a big investment, but paid for itself in no time.}
{232}{}{I believe you. But enough about brahmin.}
{233}{}{Alright. Bye.}
{234}{}{I happened to be in San-Brahmin. They have very high prices for such animals.}
{235}{}{What are you implying? Hey, I didn't steal this beast! Where the person I bought it from got it, I cannot say, however.}
{236}{}{Uh-uh. Of course. Any other interesting stuff you want to say?}
{237}{}{Uhh, I don't want to hear about anything else. Farewell.}

{240}{}{You aren't afraid of wandering through the desert?}
{241}{}{This is Ranger territory - the most secure places I know of.}
{242}{}{I don't like the way your guard is looking at me.}
{243}{}{Then you will surely answer a few more of my questions.}
{244}{}{Oh and it so happens that I have to prepare to leave this place right now. Goodbye, Flick.}
{245}{}{(sighs) This is my son. He's a bit of an... idiot, so don't bother him.}
{246}{}{I won't. I should instead bother you with a couple of new questions.}
{247}{}{You should have warned me right away. I think I'll move away from you... to the other side of the road.}

{250}{}{You ever been to Quartz?}
{251}{}{I was, exactly one time. The locals turned out to be so poor and unfriendly to outsiders I lost any desire to trade with them right away.}
{252}{}{It's really so bad there? Will keep that in mind.}

{260}{}{I need to meet the Ranger general.}
{261}{}{Well, I don't think I can help you with that. But, you know what? I can tell you that the Rangers won't let you on the dam without a good reason. Make a few friends among them, maybe that will help. But why do you need the general?}
{262}{}{Nothing, just wanted to see him.}
{263}{}{Hmmm. Whatever you say.}
{264}{}{Hmmm. (thinks, assessing the prospects) Damn, too far and dangerous... Uhhh, I just wanted to say that I can't help you.}
{265}{}{My people were abducted by slavers. Hopefully the Rangers will help me bring them back.}
{266}{}{I seriously doubt that, buddy. But go speak with the commander in the infocenter. And where is that settlement you come from located?}
{267}{}{It's... far away from here.}
{268}{}{Hmmm. Well, alright.}
{269}{}{To the north. People call that place "Villa".}

{270}{}{Hey, I know you. You were here right before the dam was washed away by the waters of Colorado.}
{271}{}{Yep. And what are you doing here after accident?}
{272}{}{The Rangers are in big trouble now, and that smelss of chaos. But you know what - my goods are still valued, even in this mess. I'll just have to... somewhat change what I'm offering.}
{273}{}{Like sell weapons, drugs and alcohol?}
{274}{}{Don't talk about this here, someone could hear. But until the rangers restore their control over their territory, there are some big profits to be made in previously unwanted business. You catch my drift?}
{275}{}{Act as you see fit.}
{276}{}{That business will meet it's end sooner or later. Our conversation, however, will do so right now.}

#Диалог на карте дороги
{300}{}{What do you need? The Rangers sent you?}
{301}{}{I sense nervousness in your voice. You do know you're a wanted man?}
{302}{}{Yes, I know. But first prove that the epidemic was caused by irradiated cola! My goods are *safe*. Got it?}
{303}{}{Everyone says that. How about a radiation check with a geiger counter?}
{304}{}{Wh... Hell no, I won't let you near my goods! Get away from the cart!}
{305}{}{...}

{310}{}{Leave me alone. I won't give you my goods.}
{311}{}{Fine.}
{312}{}{I could buy all your irradiated nuka-cola.}
{313}{}{That will cost you a hefty sum of caps. But I'm always happy to exchange garbage for something useful. Show me what you have.}
{314}{}{[Continue]}
{315}{}{So long.}
{316}{}{You will give me *all* of the irradiated cola. No objections.}
{317}{}{Just try it!}
{318}{}{[Attack]}
{319}{}{You should have listened to me.}
