{100}{}{You see the trader Flick.}
{101}{}{This is Flick, a traveling merchant.}
{102}{}{No more Nuka-Cola... honestly.}
{103}{}{The merchant lost the harmful goods. It remains to report the success to Commander Helford.}

#Start of the dialog
{200}{}{Hey, traveler, do you need useful things for the road? I can get anything... But wait, I sold all the goods to these rangers. Damn.}
{201}{}{So you're a merchant?}
{202}{}{My name is Flick. I sell all sorts of small things in the Ranger lands. What are you looking for? Tell me, maybe I know where to get it?}
{203}{}{You hardly have what I need. Come on, Flick.}

{210}{}{What are you looking for? Tell me, maybe I know where to get it?}
{211}{}{See you later.}
{212}{}{Let's change the subject.}

#Questions
{220}{}{What do you sell, Flick?}
{221}{}{I sell what I can -food, clothes, household utensils. But now I have nothing but caps left.}
{222}{}{What's the story with caps?}
{223}{}{Don't you know? In a big city in the east, someone thought of using caps as currency. That is, to exchange them for goods. It's a strange idea, but it's convenient! The only problem is that the Rangers do not recognize the caps and refuse to trade with them.}
{224}{}{What kind of principle is this?}
{225}{}{Well, they think currency is a speculative thing. After all, you never know the true price of caps. And barter exchange is honest and not subject to any kind of "inflation". And yet many now have bags for caps, someday the rangers will be forced to change.}
{226}{}{How interesting. Let's talk some more, aren't you in a hurry?}
{227}{}{I care about my relatives, not the currency. So come on.}

{230}{}{Where did you get this brahmin?}
{231}{}{I bought it from cattlemen in a neighboring town. It was an expensive purchase, but it paid off in two bills.}
{232}{}{I believe. But enough about the Brahmins.}
{233}{}{Clear. Bye.}
{234}{}{I have been to San Brahmin. They have very high prices for such animals.}
{235}{}{What are you implying? Hey, I didn't steal that brute! But where the seller brought it from, I can't know.}
{236}{}{Yeah. Sure. What else can you tell me interesting?}
{237}{}{Uh, I don't want to know anything more. Goodbye.}

{240}{}{Aren't you afraid to wander in the desert?}
{241}{}{These are Ranger lands-the safest places I know of.}
{242}{}{I don't like the way your guard looks at me.}
{243}{}{Then you'll probably answer a couple more questions.}
{244}{}{It's time for me to get on the road. Bye, Flick.}
{245}{}{(sighs) This is my son. He's a bit of an imbecile, so don't bother him.}
{246}{}{I will not. I'd rather stick to you with a couple of new questions.}
{247}{}{I should have warned you right away. I think I'll move away... on the other side of the road.}

{250}{}{Have you ever been to Quartz?}
{251}{}{Looked in exactly once. The locals turned out to be so poor and hostile to outsiders that there was no desire to trade with them.}
{252}{}{Is everything that bad for them? I'll keep that in mind.}

{260}{}{I need to get to the Ranger general.}
{261}{}{Well, I can hardly help you with that. But you know what, they won't let you on the dam without a good reason. Make friends among the rangers, maybe it will help. And why do you need a general?}
{262}{}{Yes, I wanted to see you.}
{263}{}{Hmm-m-m. Whatever you say.}
{264}{}{Hmm-m-m. (ponders, assessing the prospects) Damn, it's too far and dangerous... Uh, I mean, there's nothing I can do to help you.}
{265}{}{My people were kidnapped by slavers. I hope the Rangers will help bring them back.}
{266}{}{I doubt it, my friend. But you talk to the commander in the info center. And where is your village located?}
{267}{}{This... far from here.}
{268}{}{Hmm-m-m. Well, okay.}
{269}{}{In the north. This place is called a Villa.}

{270}{}{Hey, I remember you. You were cleaning up here before the dam was washed away by the waters of Colorado.}
{271}{}{Yeah. What are you doing here after this accident?}
{272}{}{The Rangers are in big trouble now, and this smacks of chaos. But you know what - in all this mess, my services and goods are still appreciated. I just have to now... slightly change the assortment.}
{273}{}{For example, to sell weapons, alcohol and drugs?}
{274}{}{Don't talk about it here, they might hear us. But until the Rangers regain control of their lands, it offers great prospects for previously unwanted business. You get the idea, huh?}
{275}{}{Do as you like.}
{276}{}{Such a business will come to an end sooner or later. And our conversation - right now.}

#Dialog on the road map
{300}{}{What do you want? Did the Rangers send you?}
{301}{}{I hear a note of nervousness in your words. You know they're already looking for you, right?}
{302}{}{Yes, I know. But first, prove that the epidemic was caused by an irradiated Nuka-cola! My product was *safe*. Got it?}
{303}{}{That's what everyone says. How about checking with a radiometer?}
{304}{}{Thu... The hell I'm going to let you near my product. Step away from the cart!}
{305}{}{...}

{310}{}{Leave me alone. I will not give away my goods.}
{311}{}{Well, that's fine.}
{312}{}{I can buy back all the irradiated Nuka-cola.}
{313}{}{This will cost you a round sum of caps. But I'm always happy to exchange junk for something useful. Show me what you have.}
{314}{}{[Next]}
{315}{}{See you later.}
{316}{}{You will give away all the irradiated Cola. No objections.}
{317}{}{Just try it!}
{318}{}{[Attack]}
{319}{}{You should have listened to me.}