{100}{}{You see the farmer's wife.}
{101}{}{Here is a farmer's wife, busy with ordinary farm chores.}

#Random replicas
{110}{}{*Humming*}
{111}{}{The wind is rising.}
{112}{}{No matter how the sandstorm starts.}
{113}{}{There will be another crop failure this season.}
{114}{}{I wish those peasants in the north would share their seeds.}
{115}{}{I'm so tired...}
{116}{}{I'll have to get a new dog.}
{117}{}{These radscorpions are real hooligans.}
{118}{}{There are more and more travelers.}
{119}{}{This is our land.}

{120}{}{Nothing, the Rangers will protect us.}
{121}{}{I hope there won't be any guests today.}
{122}{}{I don't know what we would have done without the Rangers.}
{123}{}{As long as the Rangers are around, you can sleep peacefully.}
{124}{}{The Rangers know their stuff.}

{125}{}{Who will protect us now?}
{126}{}{Without the Rangers, we'll be easy prey for bandits.}
{127}{}{I will not leave the land in which I have invested my whole life!}
{128}{}{Whoever destroyed the dam killed all the settlers in the area.}
{129}{}{And what scoundrel decided on your crime?}

{130}{}{Hr-r-r}
{131}{}{*Yawns*}
{132}{}{...I have to get up early tomorrow...}
{133}{}{...How tired I am...}
{134}{}{Z-z-z}
{135}{}{*Snoring*}

#Dialog
{200}{}{Oh, we have guests! I don't think I've seen you before. What's your name?}
{201}{}{.}
{202}{}{ Man from the Wasteland.}
{203}{}{Well, nice to meet you, }
{204}{}{. But if you need a place to sleep or food, then contact the rangers. Their settlement is up the road, just a couple of hours away.}
{205}{}{Well, nice to meet you... a man with a strange name}
{206}{}{Then why do you live here?}
{207}{}{Looks like you're just trying to kick me out.}
{208}{}{Why such rudeness? We have a peaceful farm. And if you're going to get rowdy, then remember that this is Ranger territory. And Rangers don't like brawlers...}
{209}{}{Okay, okay, I get it.}
{210}{}{That's good.}
{211}{}{But why do you live separately?}
{212}{}{Crops do not grow on stones. Besides, we don't like crowded places.}
{213}{}{Can I get some water from you?}
{214}{}{I see. Well, I won't distract you from your household chores.}
{215}{}{All questions in the house are solved by the husband. Talk to him.}

{220}{}{Ah, I remember you.}
{221}{}{Goodbye.}
{222}{}{You should get out of here as soon as possible before the Rangers find you. And they, you can be sure, will get at least a devil out of the ground.}
{1222}{}{You should get out of here as soon as possible before the Rangers find you. And they, be sure, will get at least a devil out of the ground.}
{223}{}{Sit still, old woman.}
{224}{}{I'm sorry, I won't bother you anymore.}