{100}{}{You see a farmer.}
{101}{}{You see a typical farmer, busy with his familiar peaceful business.}

#Первый диалог
{200}{}{Go away and never return! Don't you ruin peaceful peoples' lives. How does the earth even tolerate your presense...}
{201}{}{Chill, old man.}
{202}{}{I won't cause you any problems.}

{210}{}{(You see a farmer in a plaid shirt, frayed work pants and a leaky hat; when you move closer, he grabs his rake and examines you from head to feet, squinting; looks like he isn't a fan of having long conversations.) }
{211}{}{Sorry for the disturbance. I'm searching for the nearest settlement.}
{212}{}{Hey, old man, where's the nearest bar? I need to have a drink *immediately*.}
{213}{}{First time here? Well, welcome to Ranger territory. If you need protection or a place to sleep, go further along the road - there the Rangers set up their citadel, right on the old dam.}
{214}{}{Can I ask you a few questions?}
{215}{}{Thanks, I'll head right there.}
{216}{}{I doubt you'll find whatever you are looking for here. Along the road is the Ranger base, right on the old dam. They won't like it if you go there and ask them the same question.}

{220}{}{So, what do you say?}
{221}{}{Don't pull the iguana by it's tail, ask.}
{222}{}{How interesting. Could you tell me about something else?}
{223}{}{Looks like you settled well. Let's talk about something else.}
{224}{}{Sorry, I have to prepare to leave now.}
{225}{}{}
{226}{}{Just wanted to say hi. Goodbye.}

{227}{}{You again? Hmm... your look's cloudy. Like those mad cultists from the east. Say, you don't happen to worship old things and radioactivity signs? If so, keep in mind the Rangers don't really like those kinds of people.}
{228}{}{Thanks for the warning, but I don't worship radioactivity.}
{229}{}{Don't you laugh at the truth, pathetic atom! Otherwise I'll laugh at your grave.}

#Расспросы
{230}{}{Tell me about yourself and your farm.}
{231}{}{What's there to tell about? We grow crops as best we can and the Rangers protect us from enemies and spare whatever they can.}
{232}{}{How long have you been living here?}
{233}{}{We lived through more than 10 winters in these lands. If not for the Rangers, nobody could have lasted that long.}
{234}{}{Who else lives here, except you, of course?}
{235}{}{Further along the road, the Rangers have set up their citadel on the old dam. It's the largest settlement here and individual families, farms, outposts and seasonal hunter camps are scattered all around it.}
{236}{}{And who lives in that shack over there?}
{237}{}{After the old owner died from radscorpion poison, nobody lives there anymore.}
{238}{}{Why are the crops withering?}
{239}{}{Because the drought doesn't let the seedlings grow. Things would be better if we had a functional irrigation system.}

{240}{}{Is it safe here?}
{241}{}{In our times, nowhere is. But compared to other places I heard of, it may be the most peaceful. Bandits rarely ever show up here - the Rangers scare them off. Regarding the mutants - only radscorpions, we got some problems with them. Especially during drought season, when they are migrating from the south.}
{242}{}{Tell me about the radscorpions.}
{243}{}{Giant beasts in impenetrable shells. The further south, the further into the desert, the bigger and more dangerous they become. In especially hot seasons they go here, then it's better to not go outside at all. Especially during the night, that's when their hunting instinct wakes up.}
{244}{}{You know of their weak spots?}
{245}{}{Well, the softest place in their body is the belly, but it seems to be hard to hit. You could try fracturing their legs and then kill the beast from a distance. But the most reliable weapon against them is fire. Light the bastard up and the flame will burn like the brightest star.}
{246}{}{Looks like there's been a fight on the road.}
{247}{}{Uh-uh. The Rangers have been searching for this spy all throughout the valley for several days. And he ended up being in that shack right over there. Can you believe it? Now all enemies will know who is the true master of these lands!}

{250}{}{Tell me about the Rangers.}
{251}{}{Aren't you one of them? Then I won't be able to tell you anything you haven't heard already. Go ask other Rangers in the citadel.}
{252}{}{And still I have other questions for you.}
{253}{}{Then enough of this pointless talk.}
{254}{}{I'll tell you what - they're the protectors and guardians of these lands. The only ones ready to give up their lives for justice and law in our harsh world.}
{255}{}{So they protect you?}
{256}{}{Exactly. We pay them a tax with our crops, and they protect us from bandits and mutants. That's the simplification.}
{257}{}{And if you don't want to share with the Rangers?}
{258}{}{The Wastes are vast. If you don't like the Rangers, then go somewhere else. But I'll tell you what - they're better than anyone else.}
{259}{}{I feel like you are omitting something. What's *really* happening around here?}
{260}{}{Exactly what I said. The Rangers bring justice and order to the Wasteland. And for that, we pay them a tax. Isn't that fair?}
{261}{}{Hmm...}
{262}{}{The Rangers may be protecting us, but for that they drink our blood. Giving them part of our crops, which we spent so much effort growing, feels like giving up a child. But if there were no Rangers, there would be bandits, who would take *everything* from us. So you have to pay, there is no choice anyways.}
{263}{}{So that's the way it is...}
{264}{}{I need to get to the Ranger leader. How do I do that?}
{265}{}{Well, they won't let you to the general that easily. Usually he is sitting inside the dam, and the entrance is under heavy guard. If you want to get inside, you'll have to find a truly good reason.}

{266}{}{The residents of Garage-City are in dire need of foodstuffs.}
{267}{}{That's that scavenger settlement the Rangers were having some trouble with? No wonder that they brought themselves to this state.}
{268}{}{You could trade with them. Exchange your crops for technology and repairs.}
{269}{}{You're right. I suppose the other farmers would be happy to get some technology too, the ones useful in farming, at least. I think the Rangers will be interested in that business for their own interests. Let's see what happens.}
{270}{}{Great, I'll tell the residents of Garage-City that you agree.}

#Дать воды
{288}{}{Get outta here peacefully.}
{289}{}{Whatever you say. I wouldn't want to start a conflict for no good reason.}
{290}{}{Could you share clean water?}
{291}{}{Why should we share our supplies with you? What if you're an enemy of the Rangers or some bandit? Show yourself first, then we'll see.}
{292}{}{Fair. But can I count on answers to some questions?}
{293}{}{I'll remember this when you are the ones needing something...}
{294}{}{Here, drink as much as you want. Don't be shy, ranger, I'm happy to share water with you.}
{295}{}{Thanks...}
{296}{}{I'm not a bandit. I'm the opposite - my caravan was plundered by them.}
{297}{}{Must have been hard, wandering through the desert? Here, take a sip. But I can't give you more, ask the Rangers.}
{298}{}{Come on, don't be greedy. Let a good guest have a couple more sips.}
{1298}{}{Come on, don't be greedy. Let a good guest have a couple more sips.}
{299}{}{Hmm, alright. I'll let you have a couple more sips. Here, hold it tight.}

#Починка бака
{300}{}{Can't the Rangers repair the water tank?}
{301}{}{The Rangers are of course, pretty good folks, but they aren't that good with technology. There is no person in this entire settlement that could repair the water tank. So I have to work with my hands, and that's even harder in my age.}
{302}{}{I can fix it.}
{303}{}{Really? That would be truly useful work! If you manage to do it - we'll share food and water, we can't pay with anything else.}
{304}{}{I'll think about it.}
{305}{}{The water tank isn't leaky anymore.}
{306}{}{Seems to be the case... You're actually very good at this! Listen, you should go visit the Rangers, they need people like you.}
{1306}{}{Seems to be the case... You're actually very good at this! Listen, you should go visit the Rangers, they need people like you.}
{307}{}{Hmm. I was hoping to get my reward.}
{1307}{}{Hmm. I was hoping to get my reward.}
{308}{}{Well here's what I can give you for it - some clean water and a few fruits. Sorry that it's not much, but due to the drought and the leaky tank we barely have enough for ourselves.}
{309}{}{Well, even then, thank you.}
{310}{}{Take care.}
{311}{}{Goodbye.}
{312}{}{I didn't work for some scraps. Give the rest of your supplies, otherwise I'll slam that damn tank.}
{1312}{}{I didn't work for some scraps. Give the rest of your supplies, otherwise I'll slam that damn tank.}
{313}{}{Alright, alright, calm down, you'll get more food and more water. But it's all we have left. Take it and go in peace.}
{314}{}{Good, old man.}
{315}{}{Alright. I don't need a reward.}
{316}{}{You really don't want anything for your work? Strange, but I am very thankful to you. Take care of yourself.}
{317}{}{Goodbye.}

#Поиск собаки
{350}{}{Sounds like something bad has happened.}
{351}{}{You're right. Our dog went missing and someone is clearly eating our crops. I think it's the radscorpions. If you find any dog remains, let me know.}
{352}{}{Absolutely.}
{353}{}{I found the remains of your dog. She was killed.}
{1353}{}{I found the remains of your dog. She was killed.}
{354}{}{What are you talking about?! Who could have done that?!}
{355}{}{It was a bandit who escaped from the Rangers. The dog tried to stop him from stealing your crops.}
{356}{}{I don't know yet. Maybe it will become clearer later.}
{357}{}{So that's who devastated our farm! If there's a bandit living so near, the situation is bad. Listen, go to the Rangers and tell them about this, as soon as you can!}
{358}{}{I'm actually going in another direction. You'll have to deal with this yourselves.}
{359}{}{Absolutely. Will do once I get there.}
{360}{}{Relax - that bandit won't bother you anymore.}
