{100}{}{You see the farmer's wife.}
{101}{}{You see the farmer's wife, busy with typical farmer things.}

#Случайные реплики
{110}{}{*Hums*}
{111}{}{The wind is rising.}
{112}{}{I sure hope there won't be a sandstorm today.}
{113}{}{We'll have another crop failure this season.}
{114}{}{If only those peasants to the north would share their seeds.}
{115}{}{I'm so tired...}
{116}{}{We'll have to get a new dog now.}
{117}{}{Those radscorpions are real hooligans.}
{118}{}{There's more and more wanderers as of late.}
{119}{}{This is our land.}

{120}{}{It's okay, the Rangers will protect us.}
{121}{}{I hope we won't have any guests today.}
{122}{}{I don't know what we would do without the Rangers.}
{123}{}{We can sleep calmly while the Rangers are around here.}
{124}{}{The Rangers know what they're doing.}

{125}{}{Who will protect us now?}
{126}{}{Without the Rangers, we'll be easy pickings for bandits.}
{127}{}{I won't leave this land I put all my life into!}
{128}{}{Whoever destroyed the dam has doomed all those who lived around it.}
{129}{}{What bastard could have done such evil?}

{130}{}{Z-z-z}
{131}{}{*Yawns*}
{132}{}{...I have to get up early tommorow...}
{133}{}{...I'm so tired...}
{134}{}{Z-z-z}
{135}{}{*Snore*}

#Диалог
{200}{}{Ooh, we have guests! I don't think I saw you here before. What's your name?}
{201}{}{.}
{202}{}{Just a person from the Wasteland.}
{203}{}{Well, nice to meet you, }
{204}{}{. But if you need food or somewhere to sleep, then you should talk to the Rangers. Their settlement is further along the road, just a few hours of walking.}
{205}{}{Well, nice to meet you... a person with a strange name}
{206}{}{Then why do you live here?}
{207}{}{Looks like you're trying to drive me away.}
{208}{}{Why so rude? This is just a peaceful farm. And if you're going to brawl, remember, this is Ranger territory. And the Rangers don't like brawls...}
{209}{}{Okay, okay, I understand.}
{210}{}{Good.}
{211}{}{But why do you live separately?}
{212}{}{Crops don't grow on stones. And we don't like densely settled places.}
{213}{}{Can I collect a bit of water here?}
{214}{}{Alright. Well, I won't distract you from your household chores any longer.}
{215}{}{My husband decides everything in this house. Speak to him.}

{220}{}{Aah, I remember you.}
{221}{}{Goodbye.}
{222}{}{You should go away from here as soon as possible so that the Rangers don't find you. If they really want something they can bring the devil out the ground.}
{1222}{}{You should go away from here as soon as possible so that the Rangers don't find you. If they really want something they can bring the devil out the ground.}
{223}{}{Be quiet, old woman.}
{224}{}{I'm sorry, I won't disturb you any longer.}
