{100}{}{You see a farmer.}
{101}{}{Here is a typical farmer, busy with his usual peaceful business.}

#The first dialog
{200}{}{Get out of here and don't come back! There is nothing to spoil the lives of peaceful people. And as soon as the earth tolerates you...}
{201}{}{Don't get excited, old man.}
{202}{}{I won't cause you any problems.}

{210}{}{(Here is a farmer in a plaid shirt, worn work pants and a holey hat; when you get closer, he grabs a rake in his hands and, squinting, looks you up and down; it seems that he is not a particular fan of long conversations.) }
{211}{}{I'm sorry to bother you. I'm looking for the nearest settlement.}
{212}{}{Hey, old man, where's the nearest bar? I urgently need a drink.}
{213}{}{For the first time in these parts? Well, welcome to the Ranger lands. If you need Vault or protection, go higher up the road - there the rangers have set up their citadel, right on the old dam.}
{214}{}{Can I ask a few questions?}
{215}{}{Thanks, I'll head straight there.}
{216}{}{I doubt you'll find what you're looking for here. There's a ranger base up the road, right on the old dam. And they won't like it if you show up there with the same question.}

{220}{}{Well, what do you say?}
{221}{}{Don't pull the iguana by the tail, ask.}
{222}{}{How interesting. Tell me something else?}
{223}{}{Looks like you've settled in pretty well. Let's talk about something else.}
{224}{}{I'm sorry, but I have to get ready for the road..}
{225}{}{}
{226}{}{Just to say hello. Have a nice day.}

{227}{}{You again? Hmm... your eyes are cloudy. Like those crazy sectarians from the east. Do you by any chance worship old things and radioactivity signs? If so, keep in mind that the Rangers do not like such.}
{228}{}{Thanks for the warning, but I'm not one of those who worship radioactivity.}
{229}{}{Don't laugh at the true teaching, you insignificant atom! Otherwise I'll laugh at your grave.}

#Questions
{230}{}{Tell us about yourself and your farm.}
{231}{}{What is there to tell? We grow crops as much as we can, and the rangers protect us from enemies and help us in any way they can.}
{232}{}{How long have you lived here?}
{233}{}{We have already experienced more than a dozen winters in these lands. If it wasn't for the Rangers, no one would have lasted this long here.}
{234}{}{Who else lives in these parts besides you?}
{235}{}{Up the road, the Rangers have set up their citadel on an old dam. This is the largest settlement, and scattered around it are individual families, farms, outposts and seasonal hunting camps.}
{236}{}{And who lives in the shack opposite?}
{237}{}{After the former owner died of radscorpion poison, no one lives there anymore.}
{238}{}{Why are crops drying up?}
{239}{}{Because the drought does not allow the seedlings to grow. Things would be better if we had an irrigation system working.}

{240}{}{Is it safe here?}
{241}{}{Nowadays, everywhere is unsafe. But compared to other places I've heard of, it's probably the most peaceful. There are almost no bandits here - they are scared off by rangers. Of the mutants, only radscorpions, that's with them there are problems. Especially during the dry season when they migrate from the south.}
{242}{}{Tell me about the radscorpions.}
{243}{}{Huge creatures in impenetrable shells. The further south, into the desert, the bigger and more dangerous they are. In especially hot seasons, they move here, then it's better not to stick out on the street. Especially at night, when their hunting instinct wakes up.}
{244}{}{Do you know their weaknesses?}
{245}{}{Well, the most tender place they have is the abdomen, but it's very difficult to get there. You can try to break the paws, and then finish off the creature from afar. But the most reliable remedy against them is fire. Set fire to the creature - and this torch will flare brighter than the sun.}
{246}{}{Looks like there was a massacre on the road?}
{247}{}{Yeah. The Rangers have been tracking this spy all over the valley for several days. And he ended up right in the shack across from us. Can you imagine? Now the enemies will know who is the owner of these lands!}

{250}{}{Tell me about these rangers.}
{251}{}{Aren't you one of them? Then I won't tell you anything new. Ask around the other rangers in the citadel.}
{252}{}{And yet I have other questions for you.}
{253}{}{Then enough of this useless talk.}
{254}{}{I'll tell you what - they are the protectors and guardians of these lands. The only ones who are ready to give their lives for justice and the law in our harsh world.}
{255}{}{So they are your patrons?}
{256}{}{Exactly. We pay them a tax on our crops, and they protect us from bandits and mutants. This is if you explain it in a very simple way.}
{257}{}{And if you don't want to share with the Rangers?}
{258}{}{The wastelands are huge. If you don't like rangers, go somewhere else. But I'll tell you what - they're better than anyone else.}
{259}{}{I feel like you're not telling me something. How are things really going?}
{260}{}{Just like I said. Rangers bring justice and justice to the wasteland. And we pay a tax for it. That's fair, isn't it?}
{261}{}{Hmm...}
{262}{}{The Rangers protect us, but they drink blood afterwards. To give them a part of your harvest, which has been grown so hard, is like giving away a child. But if there were no rangers, there would be bandits who would take everything away. You have to pay, there is no choice anyway.}
{263}{}{That's how it is...}
{264}{}{I need to get to the leader of the Rangers. How to do it?}
{265}{}{Well, they won't let you go to the general so easily. He usually sits inside the dam, and the entrance there is securely guarded. If you want to get inside, you'll have to find a really serious reason.}

{266}{}{Garage City residents are in dire need of food.}
{267}{}{Isn't this a scavenger settlement that the Rangers had some kind of trouble with? No wonder they brought themselves to such a state.}
{268}{}{You could trade your crops with them in exchange for machinery and repair services.}
{269}{}{Right. Perhaps the rest of the farmers would also be happy to get some equipment that is useful on the farm. I think the Rangers will have their own interest in this business. Let's see what happens.}
{270}{}{Great, I'll give the residents of Garage City your consent.}

# Give water
{288}{}{Get out of here in a good way.}
{289}{}{Whatever you say. I would not like to create a conflict from scratch.}
{290}{}{Maybe share some clean water?}
{291}{}{Why would we share supplies with you? What if you're an enemy of the Rangers or a runaway bandit? Show yourself first, and then we'll see.}
{292}{}{Fair. But at least you can count on answers?}
{293}{}{I'll remember it to you as soon as the opportunity presents itself...}
{294}{}{Here, drink as much as you want. Don't squeeze, Ranger, it's not a pity for you to have water.}
{295}{}{Thank you...}
{296}{}{I am not one of the bandits, on the contrary - my caravan was looted.}
{297}{}{It must have been hard to walk through the desert? Here, have a little drink. But we won't give any more, ask the Rangers.}
{298}{}{Come on, don't spare a couple of sips for a kind guest.}
{1298}{}{Come on, don't spare a couple of sips for a kind guest.}
{299}{}{Hmm, it's not a pity for you. Here, hold it tight.}

#Tank repair
{300}{}{Can't the Rangers fix the water tank?}
{301}{}{Rangers, of course, are cool guys, but they don't have anything to do with technology. You won't find a person in the whole settlement who would help fix the water tank. So we have to work with our hands, and this is especially difficult at our age.}
{302}{}{I can fix it.}
{303}{}{Really? That would be a really useful thing! If you manage, we'll share food and water, we have nothing else to repay you with.}
{304}{}{I'll think about it.}
{305}{}{The water tank is no longer leaking.}
{306}{}{It's true... Yes, you are a real master! Listen, you should stop by the Rangers, they need people like you.}
{1306}{}{It's true... Yes, you are a real craftswoman! Listen, you should stop by the Rangers, they need people like you.}
{307}{}{Ahem. Actually, I was hoping for a reward.}
{1307}{}{Ahem. Actually, I was hoping for a reward.}
{308}{}{Well, here's what I can give you for it - clean water and some mutafruits. I'm sorry it's so small, but because of the drought and this leaky tank, the harvest is barely enough.}
{309}{}{And thanks for that.}
{310}{}{Take care of yourself.}
{311}{}{Goodbye.}
{312}{}{I didn't work for scraps. Give me the rest of the supplies, otherwise I'll blow up the damn tank.}
{1312}{}{I didn't work for scraps. Give me the rest of the supplies, otherwise I'll blow up the damn tank.}
{313}{}{Okay, don't get too excited, there will be more food and water for you. But that's all we have left. Take it and leave in peace.}
{314}{}{That's it, old man.}
{315}{}{Good. And no reward needed.}
{316}{}{Are you really not taking anything in return? It's strange, but I'm very grateful to you. Take care of yourself.}
{317}{}{Goodbye.}

#Dog search
{350}{}{Sounds like something bad happened.}
{351}{}{That's right. We have a missing dog and someone is clearly eating our crops. I think it's radscorpions. If you come across dog remains, let me know.}
{352}{}{Absolutely.}
{353}{}{I found the remains of your dog. She was killed.}
{1353}{}{I found the remains of your dog. She was killed.}
{354}{}{What are you saying?! Who needed to do this?!}
{355}{}{It was a bandit who escaped from the Rangers. The dog prevented him from stealing food from your beds.}
{356}{}{I don't know yet. Maybe something will clear up later.}
{357}{}{So that's who devastated our farm! If there is a bandit in the neighborhood, then it's bad. Listen, go to the Rangers and tell them about it, but soon!}
{358}{}{I'm actually going the other way. You'll have to figure it out on your own.}
{359}{}{I will definitely let you know when I get there.}
{360}{}{Relax - that bandit won't bother you anymore.}