{100}{}{You see a fugitive.}
{101}{}{You see an exhausted young man in a dirty jacket. It looks like he got beaten pretty badly.}
{102}{}{What... what did you gi...}
{103}{}{...Oh you... bastard...}
{104}{}{Looks like the Rangers finally caught the spy. His lifeless body on the road will serve as a reminder to other mercenaries.}
{105}{}{I owe you my life, doc.}
{106}{}{See you in the Temple of Fire.}

#Первый диалог
{200}{}{(you can barely catch someone's movement in the twilight; there is an exhausted young man in a dirty jacket sitting on an old matress) Stop! Who are you and what are you doing here?}
{201}{}{I'm traveling. This house seemed like a good place to sleep.}
{202}{}{As you see, this place is already taken.}
{203}{}{I shouldn't have come here. Alright, I'll go...}
{204}{}{Wait! Have you got even a little water? Help me, I'm completely exhausted!}
{205}{}{I don't have any water as well. Where's the nearest place I can get some?}
{206}{}{The farmers nearby have a well. But those bitches won't share even a drop unless you pay them everything you have... Listen, help me recover! I have many connections, I'll help you in the future.}
{207}{}{Deal with your own problems yourself. That's the law of the Wastes.}
{208}{}{Wait here, I'll be back soon with clean water...}
{209}{}{Of course, here, take it.}
{210}{}{(Grabs the flask with trembling hands and greedily swallows water from it; his thirst satisfied, he takes off his jacket and rinses a blackened wound with water, whining in pain like a dog.)}
{211}{}{Are you better now?}
{212}{}{You're saving me... but not for long.}
{213}{}{Looks like you won't last long with that kind of wound. I'll ask the Rangers to help...}
{214}{}{NO! Those bastards won't want to help me. It's 'cause of them that I ended up in this situation! Like you, I was just traveling in search of a new place to call home. The Rangers thought I was a bandit and, not caring just shot me. I was lucky I survived, the bullet I removed with a knife, but this wound will finish me!}
{215}{}{A complicated situation...}
{216}{}{Do something! I'll die without you!}
{217}{}{The unbutton your jacket and prepare for an examination. The good doctor here will heal you.}
{218}{}{But I'm not a doctor.}
{219}{}{Then go to the Rangers and get medicine from them. I'll die without a stimpak!}
{220}{}{Wait just a little longer, I'll be quick.}
{221}{}{Deal with your own problems yourself.}
{222}{}{I'll heal your wounds.}
{223}{}{Have you brought the water?}
{1223}{}{Have you brought the water?}
{224}{}{Here's your clean water.}
{225}{}{Not yet, just wait a little longer.}
{226}{}{Then what the hell are you doing here? Move!}
{227}{}{I'm not gonna share my supplies with you. Go survive yourself.}
{228}{}{You pig rat! I'll take all your things!}
{229}{}{Hey-hey, put that away...}

{250}{}{You like watching my suffering?}
{251}{}{I'm working on your problem...}
{252}{}{Maybe yes. Remember on who your life depends.}
{253}{}{To be honest, I didn't expect help. That's... honorable from you. Maybe I should reconsider something in my attitude to people.}
{254}{}{Looks like you need an injection of good dialogue. Let's talk.}
{255}{}{I think my mission here is done. Goodbye.}
{256}{}{Use healing skills or medicine to heal the stranger.}

#Повторный диалог
{300}{}{Hello.}
{301}{}{I'll be back soon.}

{310}{}{What do you eat here?}
{311}{}{Whatever I find in the desert - lizards, fruit, larvae. Not much choice but I have to deal with it.}
{312}{}{The farmers told me someone is stealing fruit from their garden.}
{313}{}{(pause) I need to survive. To hell with what others think.}
{314}{}{Hmm...}
{315}{}{Alright.}
{316}{}{So, what brought you to Ranger territory?}
{317}{}{The rumours about the Rangers and their justice. They are false and exaggerated. You want to get the support of those warmongers - then give them everything you have first. And then MAYBE they will help you.}

{320}{}{You seen the farmers' dog around here?}
{321}{}{Saw one but don't know where it escaped. Farmers should have fed her better.}
{322}{}{Alright.}
{323}{}{So you butchered the farmers' dog?}
{324}{}{Is it that obvious? No point denying it then. I needed food, and that damned thing didnt let me near the plantation. And she nearly revealed my presense to the farmers! I needed to do something.}
{325}{}{A risky move...}
{326}{}{Hey! You understand it's not in your own interests to talk about that? Got it?}
{327}{}{Uhh, sure, no problem.}

{330}{}{Can you tell me what really happened now?}
{331}{}{I know a couple of guys in Phoenix who need the Rangers' radio code. They promised to pay well for it.}
{332}{}{And you got that wound while you were searching for information?}
{333}{}{Sometimes you have to risk to get caps. I tried to enter the radio station at night, but only got shot. Since then I've been hiding in this basement and I can't do anything... Hey, you wanna earn some money together with me?}
{334}{}{Who are those guys who need the radio code?}
{335}{}{I would tell you but then I could lose a very good income. Got it?}
{336}{}{You have any idea how to get the radio code?}
{337}{}{The Ranger radio station has all the information. But convincing someone to share it is practically impossible.}
{338}{}{I'm sure there are other mercenaries.}
{339}{}{Maybe. But I don't know them.}
{340}{}{I'll think about your offer.}
{341}{}{Let me guess - your clients were the Fire-worshippers, right? In that case - bad news. The Temple of Fire is destroyed.}
{342}{}{It can't be! Do you realize what that means?! Not only have I lost my income, but the entire Wasteland will soon fall into disorder! Now I should definitely not return to Phoenix... I need to go into the mountains and survive on carrion until the dust settles down... Forget about the radio code, I don't need it anymore.}
{343}{}{Yeah, you have nothing to remain here for anymore.}
{344}{}{Why don't you leave? The Rangers must be searching for you.}
{345}{}{I don't have a choice. If I don't get the radio code, my clients will kill me... and if not then, then the borrowers I owe debt to.}
{346}{}{Another question about the same topic.}
{347}{}{Whadda you want?}
{348}{}{Let's talk about the radio code.}
{349}{}{Tell me more about that situation.}
{350}{}{I know the radio code.}
{351}{}{Well? What's the code?}
{352}{}{Not so fast. What will I get for it?}
{353}{}{A bunch of caps. I hid them in a secure place. But first, I must know whether you're telling the truth.}
{354}{}{Here's the code.}
{355}{}{I'm not telling you anything!}
{356}{}{Smart move, don't you agree? Now the fire-worshippers will give me a bunch of caps. They'll be *forced* to accept me into their ranks! I'll become part of the Phoenixian elite, get it?!}
{357}{}{Sounds good. If I end up in Phoenix, will you help me become part of that elite?}
{358}{}{You don't even need the caps, right? We need people with the right idea. So, see ya. I have to go.}
{359}{}{Goodbye!}
{360}{}{I'm only interested in my caps.}
{361}{}{Yeah... You'll get 'em now! (prepares to attack)}
{362}{}{Hey, that's not what we agreed upon!}
{363}{}{You son of a bitch!}
{364}{}{I have a better idea. You'll just shut up... forever!}
{365}{}{Hey, where are my fucking caps?!}
{366}{}{The Temple of Fire needs new blood нужна. But you, pathetic atom, are unworthy of initiation!}
{367}{}{I won't tolerate the expansion of that religion. Die!}
{368}{}{So we'll become brothers-in-faith?}
{1368}{}{So we'll become relatives-in-faith?}
{369}{}{I don't really believe you're actually from the Temple. Though... your medical knowledge... Well, so long. I have to go.}
{370}{}{Goodbye... initiate.}
