{100}{}{You see a fugitive.}
{101}{}{Here is an exhausted young man in a dirty jacket. It looks like he got pretty bad.}
{102}{}{What... what are you giving me...}
{103}{}{...Oh, you... trash...}
{104}{}{Looks like the Rangers finally caught up with the spy. His lifeless body on the road will be a reminder to the rest of the mercenaries.}
{105}{}{I owe you my life, Doc.}
{106}{}{See you at the Temple of Fire.}

#The first dialog
{200}{}{(in the twilight you barely catch someone's movement; an exhausted young man in a dirty jacket is sitting on an old mattress) Stop! Who are you and what are you looking for here?}
{201}{}{I travel. This house seemed like a great place to spend the night.}
{202}{}{As you can see, this place is already occupied.}
{203}{}{I probably shouldn't have looked in here. Okay, I'll go...}
{204}{}{Wait! Do you have any water? Help me, I'm completely exhausted!}
{205}{}{My supplies are also empty. Where is the nearest water source here?}
{206}{}{The farmers opposite have a well. But these bitches won't share a drop until you pay them with everything you have... Listen, help me regain my strength! I have many connections, I will help you in the future.}
{207}{}{Solve your own problems. This is the law of the Wastelands.}
{208}{}{Wait here, I'll be back soon with clean water...}
{209}{}{Of course, here you go.}
{210}{}{(With shaking hands, he grabs a flask and greedily swallows water from it; when he is full, he takes off his jacket and washes the blackened wound with water, whining like a dog in pain.)}
{211}{}{Are you feeling better?}
{212}{}{You're saving me... but it won't be for long.}
{213}{}{It looks like you won't last long with such a wound. I'll call the Rangers for help...}
{214}{}{no! These bastards won't want to help me. It's because of them that I got into such a mess! Like you, I was just traveling in search of a new place to live. The Rangers mistook me for a bandit and, not wanting to figure it out, just shot me. I was lucky to survive, and pulled out the bullet with a knife, but this wound will finish me!}
{215}{}{A difficult case...}
{216}{}{Do something! I'll die without you!}
{217}{}{Then unbutton your jacket and get ready for the examination. The good doctor will cure you now.}
{218}{}{But I'm not a doctor.}
{219}{}{So go to the Rangers and get their medicines. I'm going to die without a stimpack!}
{220}{}{Be patient a little more, I'll be quick.}
{221}{}{Solve your own problems.}
{222}{}{I will heal your wounds.}
{223}{}{Did you bring water?}
{1223}{}{Did you bring water?}
{224}{}{Here is pure water.}
{225}{}{Not yet, be patient a little.}
{226}{}{So why the hell are you stuck here? Move!}
{227}{}{I'm not going to share my supplies with you. Survive as you can.}
{228}{}{Pig-rat geek! I'll take all your stuff!}
{229}{}{Whoa, whoa, put that away...}

{250}{}{Do you like to watch me suffer?}
{251}{}{I'm working on your problem...}
{252}{}{And maybe so. Remember who your life depends on.}
{253}{}{To be honest, I didn't expect help. This... that's noble of you. Maybe I need to reconsider something in my attitude to people.}
{254}{}{It looks like you also need an injection of good dialogue. Shall we talk?}
{255}{}{I think that's my mission accomplished. Have a good stay.}
{256}{}{To treat a stranger, use medical skills or medications.}

#Repeat dialog
{300}{}{Hello.}
{301}{}{I'll be back soon.}

{310}{}{What do you eat here?}
{311}{}{The things I'll find in the desert - lizards, plant fruits, larvae. The choice is not rich, but I'm not used to it.}
{312}{}{And farmers say that someone is stealing fruits from their beds.}
{313}{}{(pause) I need to survive. I don't care what others think about it.}
{314}{}{Hmm...}
{315}{}{I see.}
{316}{}{So what brings you to the Ranger lands?}
{317}{}{Rumors about the Rangers and their justice. The rumors are false and exaggerated. If you want to get the support of these warriors, first give them everything you have. And then MAYBE they'll help you.}

{320}{}{Have you ever come across a farmer's dog?}
{321}{}{I saw one of them, but I don't know where she ran off to. Farmers should have fed her better.}
{322}{}{I see.}
{323}{}{Did you kill the farmers' dog?}
{324}{}{Is it that obvious? Then there's no point in denying it. I needed food, and that damn thing wouldn't let me near the plantation. Besides, she almost betrayed my presence to the farmers! It was necessary to solve something.}
{325}{}{Quite a risky decision...}
{326}{}{Hey! You know it's not in your best interest to talk about it, right? Do you understand?}
{327}{}{Uh, of course, no problem.}

{330}{}{Now will you tell me what really happened?}
{331}{}{I know a couple of guys from Phoenix who need a code from the Rangers broadcasting. They promised to pay well.}
{332}{}{Did you get wounded when you were looking for information?}
{333}{}{For the sake of bottlecaps, you have to take risks. I tried to break into the radio station at night, but only ran into a bullet. I've been hiding in this cellar ever since and I can't do anything... Hey, do you want to earn money with me?}
{334}{}{Who are the guys who need a cipher?}
{335}{}{I would say, but then I could lose a great income. Do you understand?}
{336}{}{Any ideas how to find out the cipher?}
{337}{}{The Ranger radio station has all the information. And it's almost impossible to persuade someone to share it.}
{338}{}{Surely there are other mercenaries.}
{339}{}{Maybe. But I don't know about them.}
{340}{}{I'll think about your offer.}
{341}{}{Let me guess- your customer was fire worshippers, right? In that case, I have bad news - the Temple of Fire has been destroyed.}
{342}{}{It can't be! Do you have any idea what that means?! Not only have I lost my earnings, but the whole wasteland will fall in riots! I definitely shouldn't go back to Phoenix now... We must go to the mountains and eat carrion until the dust settles... Forget about the cipher, I don't need it anymore.}
{343}{}{That's right, there's nothing else for you to do here.}
{344}{}{Why don't you leave? The Rangers are probably looking for you.}
{345}{}{I have no choice. If I don't get the cipher, the customers will kill me... and if not them, then the borrowers to whom I owe.}
{346}{}{Another question on the same topic.}
{347}{}{What do I need?}
{348}{}{Let's talk about the cipher.}
{349}{}{Tell us more about this situation.}
{350}{}{I know the cipher.}
{351}{}{Well? What is this cipher?}
{352}{}{Not so fast. What will I get for it?}
{353}{}{A mountain of caps. I hid them in a safe place. But first I have to find out if you're telling the truth.}
{354}{}{Here is the cipher.}
{355}{}{I won't tell you anything!}
{356}{}{That was a smart move, don't you think? Now the fire worshippers will give me a lot of caps. They will be *forced* to accept me into their ranks! I'm going to join the Phoenix elite, you know?!}
{357}{}{Sounds great. If I end up in Phoenix, will you help me join the elite?}
{358}{}{You don't even need caps, right? We need people with an idea. Anyway, see you later. I have to go.}
{359}{}{See you later!}
{360}{}{I'm only interested in my bottlecaps.}
{361}{}{Yes... You're going to get them now! (preparing to attack)}
{362}{}{Hey, we didn't agree on that!}
{363}{}{You son of a bitch!}
{364}{}{I have a better idea. You'll just shut up... forever!}
{365}{}{Hey, and my caps?!}
{366}{}{The Temple of Fire needs new blood. But you, a miserable atom, are not worthy of initiation!}
{367}{}{I will not tolerate the expansion of this religion. Die!}
{368}{}{So, you and I will become brothers in faith?}
{1368}{}{So, you and I will become relatives by faith?}
{369}{}{Something I can't believe that you really are from the Temple. However... your medical knowledge... Anyway, see you later. I have to go.}
{370}{}{See you... dedicated.}