{100}{}{You see William Gart.}
{101}{}{You see a veteran Ranger.}
{102}{}{Don't forget who represents real power here.}
{103}{}{And whose body lies here, you pigrat's head?}
{104}{}{If this is some kind of trick you'll pay dearly for it.}

{200}{}{Hmm? I don't remember meeting you. Welcome to Aqueduct. What brings you here to us?}
{201}{}{I have business here.}
{202}{}{Whatever you say. But make sure your "business" doesn't become mine. I don't like it when new arrivals try to make new rules.}
{203}{}{And who are you?}
{204}{}{Don't recognize a fellow Ranger? I got that rank recently.}
{1204}{}{Don't recognize a fellow Ranger? I got that rank recently.}
{205}{}{Congratulations with the promotion. Make yourself at home, here everyone's on the same side.}
{206}{}{And you...}
{207}{}{My settlement needed the Rangers' help.}
{208}{}{Then talk with the person in the infocenter near the dam. Here nobody will help you.}
{209}{}{What are you doing here?}
{210}{}{William Gart, former field commander, now a retired Ranger. I distanced myself from action after a long period of service - the years take their toll. Sometimes people think I'm a local sheriff, but that's not really the case. HQ sometimes pays me a "pension" for me watching over Aqueduct.}
{211}{}{Since you have a lot of free time, maybe you'll answer some of my questions?}
{212}{}{Nice to meet you, but I should go.}

{220}{}{What's on your mind?}
{221}{}{Speak, don't be shy.}
{222}{}{Speak.}
{223}{}{I'm listening.}
{224}{}{What do you want to know?}
{229}{}{Until next time, Ranger.}

{230}{}{They say there's an epidemic here?}
{231}{}{Several people fell ill with a fever. They're recovering, but we couldn't determine the cause of the illness.}
{232}{}{What are the symptoms?}
{233}{}{Speak with the ill, they are lying in their huts.}
{234}{}{Okay, I'll go do that.}

{250}{}{Tell me about this place.}
{251}{}{Several peaceful families live here. The river gives us food and water, and the Ranger base - protection from various threats.}
{252}{}{Thanks for telling me.}
{253}{}{Can I stay here to sleep?}
{254}{}{Well, I won't protest, as long as you watch yourself. Locals are a bit mistrusting of outsiders.}
{255}{}{Can I find a job here?}
{256}{}{Don't think so. Talk to the locals.}
{257}{}{I'm curious what is that big destroyed structure across the road?}
{258}{}{It's an aqueduct. An artificial river, built by the people of the Old World. It stretches for hundreds of miles across the entirety of Arizona. Impressive, isn't it? But you shouldn't go there - it's not safe.}
{259}{}{Aren't the Rangers against civilians near their base?}
{260}{}{Of course, such a closeby settlement causes a slight discomfort. But the Rangers are called upon to protect these lands and their inhabitants.}

#квест - пропавшие жители
{300}{}{They say people are going missing.}
{301}{}{Who says?}
{302}{}{That refugee near the campfire.}
{303}{}{Just answer the question.}
{304}{}{Sometimes strangers show up here, like you, but they can't get along. That's fine. Then they go somewhere else. Sometimes the Rangers find their remains in the forest, where there are many wolves.}
{305}{}{You're kind of the sheriff here. Don't you want to go find those missing people?}
{306}{}{My job is to look after Aqueduct, not things beyond it's borders. And besides, the missing people were just homeless strangers. So, not locals. If you want to find 'em, go do it yourself.}
{307}{}{I understand. No problem. Bye, Ranger.}
{308}{}{You're a terrible sheriff. I'll deal with this without you.}

{310}{}{There are dead bodies in the aqueduct. And you're clearly involved.}
{311}{}{Dammit, I *told* Kill to stop you. Where is that moron?}
{312}{}{I don't know how to say it, but it looks like he can't carry out your orders anymore.}
{313}{}{He tried but failed. And you too won't keep me shut.}
{314}{}{Who the hell are you to go here and ruin our lives? Those cultists sent you? Or you're scouting so your buddies can carry out a bandit raid? Or maybe you're just a regular old thief who wants our fish. You outsiders bring only trouble to this peaceful community. I'm only carrying out my duty - to protect Aqueduct from threats.}
{315}{}{No. You're just paranoid. And you have to be stopped.}
{316}{}{So that's how it is. I exit this room and you DON'T touch me. You'll be very lucky if I don't decide to tell everyone what really happened.}
{317}{}{Believe me, I'm on your side. And if your subordinate didn't manage to do the job, I could help.}
{318}{}{Then prove your loyalty to the Ranger cause - get rid of the last refugee. I don't care how you do it - with a bullet, or some clever trick. Right now he's a threat to me and the other inhabitants of this community.}
{319}{}{Okay, I'll do it.}
{320}{}{No, this is too much. I'll go kill YOU.}
{321}{}{Why? Aren't there enough deaths already?}
{322}{}{Do you know anything about these people? Clearly not. They arrived here from afar. One of them had the mark of the highwaymen - a gang on a big road. Maybe it's just me being paranoid, and that's not enough to conduct a fair trial. But it's enough for ME to act.}
{323}{}{Let's look who you're pretending to be.}
{324}{}{Bye.}
{325}{}{As a fellow Ranger you must understand me. Aqueduct is a small peaceful community of fishermen and gatherers. Unchecked arrivals could harm the delicate balance in this settlement. Cultists, bandits, thieves - whoever the wastes bring to us. I'm only carrying out my duty - to protect Aqueduct from threats.}
{1325}{}{As a fellow Ranger you must understand me. Aqueduct is a small peaceful community of fishermen and gatherers. Unchecked arrivals could harm the delicate balance in this settlement. Cultists, bandits, thieves - whoever the wastes bring to us. I'm only carrying out my duty - to protect Aqueduct from threats.}

{330}{}{I got rid of the refugee.}
{1330}{}{I got rid of the refugee.}
{331}{}{Excellent work. You're doing better than that spineless Kill. I think you and I will work together beautifully in the future. Here, take some ammo. I hope I don't need to specify this being a secret?}
{332}{}{No problems, William. Nobody saw anything.}
{333}{}{There's a... there's a corpse near the aqueduct. Uhh, you should take a look.}
{334}{}{Dammit, I don't need this. Show it to me.}
{335}{}{It's right there...}
