{100}{}{This is William Garth.}
{101}{}{You see a veteran ranger.}
{102}{}{Don't forget who represents the real power here.}
{103}{}{And whose corpse is lying here, you pig-rat head?}
{104}{}{If this is some kind of trick, you will pay dearly for it.}

{200}{}{M? I don't remember that we ever met. Welcome to the Aqueduct. What brought you to us?}
{201}{}{I have business here.}
{202}{}{Whatever you say. But make sure that your "deeds" do not become mine. I don't like it when new arrivals try to impose new rules.}
{203}{}{And who are you anyway?}
{204}{}{Don't you recognize a fellow ranger? I recently received this title.}
{1204}{}{Don't you recognize the Ranger? I recently received this title.}
{205}{}{Congratulations on the promotion. Make yourself at home, everyone is here.}
{206}{}{And you...}
{207}{}{My village needed the help of rangers.}
{208}{}{Then contact the person on duty at the information center on the dam. No one can help you here.}
{209}{}{What are you doing here?}
{210}{}{William Garth, former field commander, now a retired ranger. I retired after a long service - the years take their toll. Sometimes I'm mistaken for the local sheriff, but that's not quite true. At the headquarters they pay me a "pension" for keeping order in the Aqueduct.}
{211}{}{Since you have a lot of free time, maybe you can answer a couple of questions?}
{212}{}{It was nice to meet you, but I have to go.}

{220}{}{What's on your mind?}
{221}{}{Speak up, don't be shy.}
{222}{}{Speak.}
{223}{}{I'm listening.}
{224}{}{What do you want to know?}
{229}{}{See you later, Ranger.}

{230}{}{They say you have an epidemic here?}
{231}{}{Several people came down with a fever. They are on the mend, but we could not determine the cause of the disease.}
{232}{}{What are the symptoms?}
{233}{}{Talk to the sick, they are lying in their huts.}
{234}{}{Okay, I'll do that.}

{250}{}{Tell me about this place.}
{251}{}{Several peaceful families live here. The river gives us food and water, and the ranger base provides protection from various threats.}
{252}{}{Thanks for the reply.}
{253}{}{Can I stay here for the night?}
{254}{}{I don't mind if you watch yourself. Locals are distrustful of newcomers.}
{255}{}{Is there a job for me here?}
{256}{}{I don't think so. Talk to the locals.}
{257}{}{Curious, what is this big ruined structure across the street?}
{258}{}{This is an aqueduct. An artificial river built by the people of the Old World. It stretches for hundreds of miles across Arizona. Impressive, isn't it? But don't go there - it's not safe.}
{259}{}{Aren't the Rangers against civilians near their base?}
{260}{}{Of course, such a close location of the village causes a little discomfort. But the rangers are called to protect these lands and their inhabitants.}

#quest - missing residents
{300}{}{They say people are disappearing here?}
{301}{}{Who's talking?}
{302}{}{That refugee by the campfire.}
{303}{}{Just answer the question.}
{304}{}{Sometimes newcomers like you come here, but they can't get along. It is ok. Then they go wherever they look. Sometimes rangers find their remains in the forest, where there are many wolves.}
{305}{}{You're kind of the sheriff. Don't you want to look for the missing?}
{306}{}{My job is to keep order in the Aqueduct, not outside it. In addition, the missing were homeless newcomers. That is, not local. If you want to find them, look for them yourself.}
{307}{}{I understand. No problems. Bye, Ranger.}
{308}{}{You're a terrible sheriff. I'll figure it out without you.}

{310}{}{There are corpses in the aqueduct. And you are clearly involved in this.}
{311}{}{Damn it, I told Keel to stop you. Where is this fool?}
{312}{}{How should I put it, it looks like he's not able to follow your orders right now.}
{313}{}{He didn't succeed. And you won't be able to keep me quiet.}
{314}{}{Who the hell are you to come here and ruin our lives? Did those sectarians send you? Or are you sniffing around for a bandit raid? Or maybe you're just another thief who coveted fish. You outsiders bring nothing but trouble to this peaceful community. I'm just doing my duty- protecting the Aqueduct from problems.}
{315}{}{No. You're just being paranoid. And you have to be stopped.}
{316}{}{So that's it. I walk out of this room and you don'T touch me. And you're lucky if I don't decide to tell you what happened.}
{317}{}{Believe me, I'm on your side. And if your assistant can't cope, I can help.}
{318}{}{Then prove your dedication to the Rangers' cause - eliminate the last refugee. I don't care how you do it -with a bullet or a trick. Now he is a threat to me and other residents.}
{319}{}{OK, I'll do it.}
{320}{}{No, this is too much. I'll kill YOU.}
{321}{}{Why? Aren't there too many deaths?}
{322}{}{Do you know anything about these people? Obviously not. They came from far away. One of them had the label of a highway gang - a gang from the high road. Perhaps these are just my conjectures, they are not enough to make an honest trial. But it's enough for ME to start acting.}
{323}{}{Let's see what you are like.}
{324}{}{Bye.}
{325}{}{As a ranger, you have to understand me. Aqueduct is a small peaceful community of fishermen and gatherers. Untested settlers can harm the fragile balance of this settlement. Sectarians, bandits, thieves - who just does not bring us the wasteland. I'm just doing my duty - protecting the Aqueduct from problems.}
{1325}{}{As a ranger, you have to understand me. Aqueduct is a small peaceful community of fishermen and gatherers. Untested settlers can harm the fragile balance of this settlement. Sectarians, bandits, thieves - who just does not bring us the wasteland. I'm just doing my duty- protecting the Aqueduct from problems.}

{330}{}{I got rid of the refugee.}
{1330}{}{I got rid of the refugee.}
{331}{}{Great job. You're doing better than a soft-bodied Kil. I think you and I will work together. Take some ammo for the future. I hope there is no need to clarify about the secret of silence?}
{332}{}{No problem, William. No one saw anything.}
{333}{}{This... there's someone's corpse lying by the aqueduct. Uh, you should take a look.}
{334}{}{Damn it, I don't need that at all. Show me this place.}
{335}{}{It's over there...}