{100}{}{You see an old man.}
{101}{}{You see an emaciated man with overworked hands. His skin was blackened from constant work under the sun.}

#Retaliatory remarks after the dialogue
{110}{}{Perhaps it's enough to indulge in oblivion.}
{111}{}{I have to get back to the farm.}
{112}{}{Thank you for the opportunity to speak out.}
{113}{}{The dead man will wait, but the harvest will wither.}
{114}{}{I hope you'll forgive me for being sentimental.}

#Dialog
{200}{}{(You see an old man standing thoughtfully in front of the grave)}
{201}{}{[Next]}

{210}{}{What do you want from me?}
{211}{}{Nevermind.}
{212}{}{I see.}
{213}{}{.}

{220}{}{Who are you, old man?}
{221}{}{The old man? Heh, I'm barely forty years old, and I already look like a petrified antiquity, right? I'm a farmer. Growing crops two miles from here.}
{222}{}{So you're not a Ranger?}
{223}{}{Don't talk nonsense. What kind of ranger am I at my age and with these dirty hands? My job is to keep an eye on the farm, not to chase bandits.}
{224}{}{I came across one farm on the way.}
{225}{}{There are several farms and ranches in the area. The Rangers cover our brother, but they take their percentages of the harvest for it... Sometimes this leaves us pitiful crumbs for living... But things get better over time. The Earth is recovering from a lot of Pollution from year to year.}
{226}{}{Pollution?}
{227}{}{The general once told me over a cup of herbal tea. When the nuclear bombs fell a hundred years ago, these lands were covered with clouds of radioactive ash. The clouds came from the west, east, and south, depending on where the wind was blowing from. It was bad everywhere in those years. They say the land here has been barren for generations. Only cacti managed to maintain their life cycle thanks to deep roots. And only now the earth has begun to recover.}

{230}{}{What are you doing here?}
{231}{}{What can a saddened old man do in a cemetery? I've come to remember the old days. Here is my son's grave. The inscription on the cross is almost erased, but I still have the sense not to forget his name and the location of the grave.}
{232}{}{Tell me how he died.}
{233}{}{Young people are impatient. Working on plantations is exhausting for them. But the earth gives its fruits only to those who have worked hard for many years. So is my Jacob. He went to the rangers, so as not to mess around in the beds. The first encounter with the raiders during the patrol took his life.}
{234}{}{Do you hate Rangers now?}
{235}{}{I drive away such thoughts. Rangers are doing a noble thing - restoring order in the wastelands. Yes, at the same time, someone dies. You can't please everyone. If you help one, you will offend the other. This is the true face of justice.}

{240}{}{Whose graves are these?}
{241}{}{Rangers bury their brothers according to the old tradition - they bury them in the ground. A cartridge is placed in the grave, usually a revolver caliber. If there is no revolver, any other one will do. And if there is no such thing, then they put a cartridge case or a fired bullet. By this, they mean to say that even after death one should not lose the strength of the spirit.}