{100}{}{You see an old man.}
{101}{}{You see very thin man with weary hands. His skin is blackened from constand work under the sun.}

#Ответные реплики после диалога
{110}{}{I suppose I should stop indulging in memories.}
{111}{}{It's time to go back to my farm.}
{112}{}{Thank you for giving me an opportunity to speak my mind.}
{113}{}{The dead will wait, but the crops won't.}
{114}{}{I hope you forgive my sentimentality.}

#Диалог
{200}{}{(You see an old man, thoughtfully standing in front of a grave)}
{201}{}{[Continue]}

{210}{}{What do you want?}
{211}{}{Pay no attention.}
{212}{}{Alright.}
{213}{}{.}

{220}{}{Who are you, old man?}
{221}{}{Old man? Heh, I'm barely even fourty and I look like some ancient fossil, right? I'm a farmer. I grow crops about two miles from here.}
{222}{}{So you are not one of the Rangers?}
{223}{}{Don't talk nonsense like that. What kind of Ranger could I be, with my age and with those dirty hands? My job is to look after the farm, not chase after bandits.}
{224}{}{I did notice one farm along the way here.}
{225}{}{There are a few farms and ranches around here. The Rangers protect our brother, but for that they take a lion's share of our crops... That is, they mostly leave us pitiful crumbs to live on... But overall things are getting better. The soil is slowly recovering from the Great Contamination, year by year.}
{226}{}{Contamination?}
{227}{}{The general once told about that over a cup of herbal tea. When the atomic bombs dropped a hundred years ago, these lands were covered with clouds of radioactive ashes. The clouds arrived from the west, east or the south, depending from where the wind blew. It was terrible everywhere those years. They say that for generations, the land here was barren. Only the cacti managed to survive thanks to their deep roots. And only now has the soil begun to recover.}

{230}{}{What is it you do here?}
{231}{}{What could a sad old man be doing in a graveyard? Obviously, I have come here to remember the olden days. Here is my son's grave. The label on the cross is almost fully erased, but I will never forget his name and the location of the grave.}
{232}{}{Tell me how he died.}
{233}{}{Young people are impatient. Work on the plantation is exhausting for them. But the earth only gives crops to those who have worked hard for many years. That was true of my Jacob. He went to the Rangers to get away from working in the garden. He died in his first encounter with raiders during a patrol.}
{234}{}{And now you hate the Rangers?}
{235}{}{I try not to have such thoughts. The Rangers are doing a good thing - they bring order to the Wastes. Yes, some die along the way. You can't save everyone. Help one man - you doom another. That is what justice truly is.}

{240}{}{And whose graves are these?}
{241}{}{The Rangers bury their comrades according to old traditions - they put their bodies in the earth. In the grave they put a bullet, usually from a revolver. If there is no bullet from a revolver, one from any gun will do. And if even that is not availaible, they put a case or a used bullet. This they do because they think that even in death one must not lose their fortitude.}
