{100}{}{This is Henry.}
{101}{}{You see the Ranger supplier.}
{102}{}{E-t-what else is it? Stop! I will shoot!}

#The first dialog
{200}{}{Damn it, I don't know where the hell that is... Oh, I thought it was the inspector again.}
{201}{}{No, I'm not an auditor.}
{202}{}{Next time I might be offended.}
{203}{}{Hmm, a new face. Here's a surprise. My name is Henry, I am the quartermaster and quartermaster at this base. Keep in mind, that there is a strict schedule here. If you want to settle down, you will have to comply with it.}
{204}{}{I don't like being pointed out to me.}
{205}{}{No problems.}

{206}{}{Wait a minute, we're having a heated discussion about the latest news. Some bastard is digging ranger graves in the cemetery. Don't you know anything about it?}
{207}{}{Me? Uh, no, sir.}
{208}{}{Sorry. The Rangers decided to chip in for a rifle to whoever finds and shoots the son of a bitch. Mind you.}
{209}{}{Uh, of course, sir.}

#Repeat dialog
{210}{}{So what do you want?}
{211}{}{Nothing yet.}
{212}{}{That's enough, let's talk about something more useful.}
{213}{}{I'm still curious about your story.}

{220}{}{Tell me about yourself.}
{221}{}{Are you interested in this?}
{222}{}{What are you doing here?}
{223}{}{I am the quartermaster and quartermaster at this base.}
{224}{}{Do you trade anything with outsiders?}
{225}{}{The command does not like casual trade with lone travelers. We have reliable supply caravans. However, because of all this mess in San Brahmin, trade has declined.}
{226}{}{Tell me about this trade commotion.}
{227}{}{San Brahmin is a city in the east. We trade with local cattle breeders for leather goods and meat. We also protect their trade routes and pastures. But there is a conflict inside the city. It is unknown how all this will end.}
{228}{}{I have a large retail network. You should not give up such a profitable partner.}
{229}{}{Okay, let's see what happens.}
{230}{}{Thank you.}
{231}{}{I doubt your business will be useful to the Rangers.}
{232}{}{As you wish...}
{233}{}{}
{234}{}{Where are you from?}
{235}{}{My family often changed their place of residence, so the most accurate answer to your question is that I came from the west.}
{236}{}{Tell me about those lands.}
{237}{}{Southern California? A living hell compared to this region. Cities lie in ruins, the land is barren, and cannibalism flourishes among the population. But at the same time, there is much more population there than in Arizona.}
{238}{}{How did you become a ranger?}
{239}{}{I was forced by the wasteland itself when I was separated from my family during the trip. I was only alive thanks to the Rangers who happened to be nearby. Since then I have been working out my salvation. But my data was only enough for this position.}

#Ranger
{250}{}{I think I should register with your registry. I'm a rookie.}
{251}{}{I've already heard about your acceptance, Ranger. You have an enviable case. Many people have been training for years to earn this title, and you managed to get it in such a short time.}
{252}{}{[Next]}
{253}{}{Okay, if you need anything, you say it, don't be shy. I'll give you a bed, but be careful with the equipment. Here's your leather armor and a travel flask. Now - which weapon would you prefer?}
{254}{}{[Hunting rifle with cartridges]}
{255}{}{[Signal pistol with ammunition]}
{256}{}{[Throwing knives, 5 pieces]}
{257}{}{Get it and sign it. Keep in mind that all this is in a single copy.}
{258}{}{Thank you, I will take care of this equipment.}
{259}{}{I know without you, smartass. Come here quickly.}

{270}{}{It seems that Rufus sent it to you for a reward.}
{271}{}{Yes, the old man ordered to reward you. Here is the list, choose only one.}
{272}{}{Another time.}
{273}{}{stimpacks (3 pcs)}
{274}{}{0.44 caliber cartridges (35 pcs)}
{275}{}{Rifle cartridges (20 pcs)}
{276}{}{Leather armor.}
{277}{}{}
{278}{}{Here you go.}
{279}{}{Thank you.}

{280}{}{I'm going to Puerto to investigate.}
{281}{}{Good luck then. The Rangers on the front line are having a hard time right now. The new enemy turned out to be a tough nut to crack.}
{282}{}{That's right.}
{283}{}{We conduct propaganda in the settlements and even pay extra for every enemy soldier killed. You just need to prove it.}
{284}{}{How to prove it?}
{285}{}{It's simple. Everyone has a token with a personal number and name. Bring a token and you'll get caps. We don't usually deal with caps, but otherwise, it's hard to interest ordinary residents from the wasteland.}
{286}{}{I'll remember that. Bye.}
{287}{}{I have a badge of the Brotherhood of Steel.}
{288}{}{The more invaders fall, the freer the Arizona air will be. Your reward is 10 caps per token.}
{289}{}{Better than nothing. Here's the token.}
{290}{}{No caps needed. Save them for someone else.}
{291}{}{Each such token increases the fighting spirit of ordinary rangers. Thank you. And good luck in the wastelands.}
{292}{}{See you again.}
{293}{}{Wait, that's not all.}

#Missing Person Quest
{300}{}{About the auditor. Have you lost something?}
{301}{}{Yes... According to the invoices, there should be a Colt 6520 pistol and a box of cartridges for it. But there are none.}
{302}{}{Okay, I won't bother you in their search.}
{303}{}{Error in records?}
{304}{}{I doubt that I entered a gun that wasn't there. I don't even want to think that one of my own could have committed theft. But this is the only explanation.}
{305}{}{I can search. Who was the last person to use this gun?}
{306}{}{Surely this weapon has fallen somewhere. Keep looking.}
{307}{}{Yeah, here you need to keep your pockets closed. Maybe I should double-check my stuff.}
{308}{}{Captain Agatha assigned the pistol to her group for general training. But then he was returned safe and sound. If, of course, you believe the records.}
{309}{}{Looks like it's worth talking to her and her cadets. Bye.}
{310}{}{I'll talk to them, of course. But keep in mind that you are also a suspect.}
{311}{}{Remember we talked about the lost weapon?}
{312}{}{What do you know?}
{313}{}{Nothing. No leads. At all.}
{314}{}{Remind me, what exactly is missing from the warehouse?}
{315}{}{Colt 6520 pistol with full ammunition. This instance was mainly used for training.}
{316}{}{Thank you, I will continue to investigate.}
{317}{}{Tell me again, who took the gun last?}
{318}{}{Captain Agatha's cadets. They used it for training and then returned it safe and sound.}

{320}{}{Here's the missing weapon. It was stolen by Agatha's cadets along with the cartridges. They wanted to practice shooting.}
{321}{}{Oh, finally. Where was it?}
{322}{}{It was stolen by Agatha's cadets along with the cartridges. They wanted to practice shooting.}
{323}{}{Damn dam rats... They won't get away with it. And you deserve some of the bullets that were meant for these cadets. Thank you for your help.}
{324}{}{Glad to help.}
{1324}{}{Glad to help.}
{325}{}{It wasn't worth it.}
{326}{}{He was forgotten at the shooting range. It looks like you messed up something in your notes.}
{327}{}{Damn it. Now I have to report to the commander. But thanks for the help. I'll tell the others, I hope it will help you strengthen your base.}

#Relic
{350}{}{A curious thing I came across. Look at this icon.}
{351}{}{It's not our badge. Hmm... It looks authentic! A very rare find.}
{352}{}{It's like you've changed your face. Is it that important to you?}
{353}{}{Such insignia remind us of our roots and prove that we are the keepers of local traditions. Of course, this is important.}
{354}{}{Do you want to buy it back?}
{355}{}{Sure. Such things boost the morale of the Rangers. I'll give you a pack of cartridges for this badge.}
{356}{}{Your badge is for a box of rifle cartridges.}
{357}{}{Give me the badge. Here are the cartridges.}
{358}{}{It was worth it.}
{359}{}{I think I'll take the cartridges for the revolver.}
{360}{}{Give me the badge. Here is a box of revolver-caliber cartridges.}
{361}{}{I am satisfied with this exchange.}
{362}{}{I need a small caliber like 0.22 for practice.}
{363}{}{I've got plenty of that to do. Here's the box, give me the badge.}
{364}{}{Good deal.}
{365}{}{I need signal cartridges.}
{366}{}{Give me the badge, I have a whole box of these cartridges, and they are of little use.}
{367}{}{Great deal.}
{368}{}{Take it for free. I don't need it anyway.}
{369}{}{Just give it away like that, right? Thank you. I won't forget it.}
{370}{}{Take it, I'm not sorry.}
{371}{}{What about the shooting range? It wouldn't hurt for me to get some experience in light weapons.}
{372}{}{It's possible. I have ammo and weapons for just such purposes. Good luck at the shooting range.}
{373}{}{Thank you...}
{374}{}{The quartermaster reduced the cost of his goods by 10%.}