{100}{}{You see Henry.}
{101}{}{You see the Rangers' supplier.}
{102}{}{W-wh-o's there? Stop! I'm gonna shoot!}

#Первый диалог
{200}{}{For the last time, no, I DON'T know where that fucki... Oh, I thought it was the inspector.}
{201}{}{Uhh, no, I'm definitely not an inspector.}
{202}{}{Next time I will take that personally.}
{203}{}{Hmm, an unfamiliar face. Didn't expect that. My name's Henry, I'm the quartermaster on this base. Keep in mind there are strict rules here. If you want to do things here, you'll have to follow it.}
{204}{}{I don't like it when people tell me what to do.}
{205}{}{Sure, no problem.}

{206}{}{Wait a minute, we already had several heated discussions about an event that happened recently. Some bastard is digging up the graves of Rangers on the cemetary. You know anything about that?}
{207}{}{Me? Uhh, no, sir.}
{208}{}{A pity. The Rangers are promising to give away a rifle to whoever, finds and shoots the son of a bitch. Keep that in mind.}
{209}{}{Uhh, of course, sir.}

#Повторный диалог
{210}{}{So what do you want?}
{211}{}{Nothing, for now.}
{212}{}{Enough, let's talk about something more important.}
{213}{}{I'm still curious about your story.}

{220}{}{Tell me about yourself.}
{221}{}{You're really interested in that?}
{222}{}{What is it you do here?}
{223}{}{I'm the quartermaster on this base.}
{224}{}{You trade anything with outsiders?}
{225}{}{Command doesn't like random trade with lone wanderers. We have reliable caravans to get supplies from. Though recently the mess in San-Brahmin has started a decline in trade around here.}
{226}{}{Tell me about that decline in trading.}
{227}{}{San-Brahmin is a city to the east. We trade with the local shepherds for leather goods and meat. We also protect their trade routes and pastures. But a conflict has brewed up inside the town. We don't know how that situation will turn out.}
{228}{}{I have a big trade-related connections. You shouldn't refuse such a good partner.}
{229}{}{Alright, let's see how this will turn out.}
{230}{}{Thanks.}
{231}{}{I doubt your business will be useful to the Rangers.}
{232}{}{Whatever you say...}
{233}{}{}
{234}{}{Where are you from?}
{235}{}{My family often moved between places, so the most accurate answer to your question - I came from the west.}
{236}{}{Tell me about those lands.}
{237}{}{Southern California? Hellish, really, compared to this region. The cities lie in ruins, the soil barren and cannibalism is prospering among the population. But even with all that the population is still higher than in Arizona.}
{238}{}{How did you become a Ranger?}
{239}{}{The Wasteland forced me to when she parted me with my family while traveling. I only lived thanks to the Rangers, who happened to be nearby. Since then I'm helping them in gratitude for my salvation. But the kind of person I am is only really suited to a role like this.}

#Рейнджер
{250}{}{I think I am supposed to come here and be registered. I'm a rookie.}
{251}{}{Already heard your promotion, Ranger. I envy you. Many train for years to get that title, but you managed to receive it in such a short time-span.}
{252}{}{[Continue]}
{253}{}{Alright, if you need anything, say it to me, don't be shy. I'll give you a bunk bed, but be more careful with equipment. Here's your leather armor and a flask for traveling. Now - what weapon would you prefer?}
{254}{}{[Hunting rifle with ammo]}
{255}{}{[Flare gun with ammo]}
{256}{}{[5 throwing knives]}
{257}{}{Take it and sign here. Keep in mind this is unique and won't be replaced if you lose it.}
{258}{}{Thank you, I will take good care of this equipment.}
{259}{}{I know that, smartass. Now give it to me and hurry while you're at it.}

{270}{}{I think Rufus told me to head to you to get a reward?}
{271}{}{Yes, that old chap authorized me to give you compensation for your efforts. Here's a list, you can only choose one.}
{272}{}{Maybe I'll do it later.}
{273}{}{3 Stimpaks}
{274}{}{35 bullets of the 0.44th caliber}
{275}{}{20 rifle bullets}
{276}{}{Leather armor.}
{277}{}{}
{278}{}{Here, take it.}
{279}{}{Thank you.}

{280}{}{I'm heading to Puerto to do reconnaissance.}
{281}{}{Well, good luck then. Rangers on the front lines are worried. This new enemy won't die easily.}
{282}{}{Absolutely.}
{283}{}{We are spreading propaganda in settlements and are even compensating for every killed enemy soldier. You just need to show proof.}
{284}{}{What kind of proof?}
{285}{}{Each one of them has a dog tag with their name and personal number. Bring the dog tag here - you get caps. Usually we don't deal with caps, but it seems to be hard for any people from the Wasteland to be interested in this without them.}
{286}{}{I'll keep this in mind. Bye.}
{287}{}{I have a Brotherhood of Steel dog tag.}
{288}{}{The more of the invaders fall, the freer Arizona will be. Here's your reward - 10 caps per dog tag.}
{289}{}{Well, better than nothing. Here, take the dog tag.}
{290}{}{I don't need caps. Save them for someone else.}
{291}{}{Each such dog tag raises the morale of every Ranger. Thank you. And good luck in the wastes.}
{292}{}{See you later.}
{293}{}{Wait, that's not all.}

#Квест на пропажу
{300}{}{About the inspector. Did something go missing?}
{301}{}{Yes... The shipping list said there was supposed to be a Colt 6520 pistol and a box of bullets for it. But they're not there.}
{302}{}{Alright, I won't disturb you in your search for them any longer.}
{303}{}{Maybe a mistake?}
{304}{}{I doubt that I could have written down there was a gun when that was not the case. I don't even want to think about the possibility of one of our own stealing it. But it's the only possible explanation.}
{305}{}{I could search for it. Who last used this pistol?}
{306}{}{I'm sure that weapon just got lost somewhere. Keep looking for it.}
{307}{}{Yeah, seems like you should keep your pockets shut around here. I should check my things too.}
{308}{}{Captain Agatha assigned a pistol to her group for general training purposes. But later, it was returned safe and sound. At least, the records say it was.}
{309}{}{Looks like I shouls go talk to her and her cadets. Goodbye.}
{310}{}{I'll talk to them, of course. But keep in mind that you too are a suspected individual.}
{311}{}{Remember how we talked about a lost weapon?}
{312}{}{Anything new?}
{313}{}{Nothing. No leads. At all.}
{314}{}{Remind me what exactly went missing from the warehouse?}
{315}{}{A Colt 6520 pistol with it's ammo. That one was mainly used for training purposes.}
{316}{}{Thanks, I'll continue the investigation.}
{317}{}{Tell me again, who last used the pistol?}
{318}{}{Captain Agatha's cadets. They used it for training purposes and then returned it safe and sound.}

{320}{}{Here's the missing weapon. Captain Agatha's cadets stole it, along with the bullets. They wanted to practice shooting.}
{321}{}{Oh, finally. Where did you find it?}
{322}{}{Captain Agatha's cadets stole it, along with the bullets. They wanted to practice shooting.}
{323}{}{Those damn dam rats... They won't get away with this. And you deserve a bit of ammo that was meant for those cadets. Thanks for the help.}
{324}{}{Happy to assist.}
{1324}{}{Happy to assist.}
{325}{}{It wasn't worth it.}
{326}{}{It was forgotten on the shooting range. Looks like you messed something up in your records.}
{327}{}{Dammit. Now I'll have to report to the commander. But thanks for the help. I'll tell the others, hopefully this will help you settle down on the base.}

#Реликвия
{350}{}{I found an interesting thing. Look at this badge.}
{351}{}{This is definitely not our badge. Hmm... Looks like it's genuine! A very rare find.}
{352}{}{I swear your face changed. How important is this for you?}
{353}{}{Such insignia remind us of our roots and are proof that we are guardians of local traditions. Of course this is important.}
{354}{}{You want to buy this?}
{355}{}{Of course. Such things raise Ranger morale. I'll give you a bunch of bullets for that badge.}
{356}{}{The badge is yours for a cartridge of rifle ammo.}
{357}{}{Give me the badge. And here's your ammo.}
{358}{}{It was worth it.}
{359}{}{I suppose I'll take revolver ammo.}
{360}{}{Give me the badge. Here's your revolver ammo.}
{361}{}{I am satisfied by this exchange.}
{362}{}{I need a small caliber, like a 0,22. For practice.}
{363}{}{I have more than enough of these. Take this whole cartridge, give me the badge.}
{364}{}{A good deal.}
{365}{}{I need signal cartridges.}
{366}{}{Give me the badge, I have a lot of them lying around not doing anything.}
{367}{}{An excellent deal.}
{368}{}{Take it for free. I don't need this anyway.}
{369}{}{You'll give it away for free, yes? Well, thank you. I won't forget this.}
{370}{}{Take it, I don't mind.}
{371}{}{What about the shooting range? I wouldn't mind increasing my skill in light weapons.}
{372}{}{You can do that. I have the ammo and the weaponry for just that situation. Good luck out there, on the shooting range.}
{373}{}{Thanks...}
{374}{}{The quartermaster has lowered the price of his goods by 10%.}
