{100}{}{You see a bandit.}
{101}{}{You see a man who looks almost, but not quite, entirely unlike a Ranger.}
{102}{}{Scram before I shoot you.}

#Первый диалог
{200}{}{Stop. You're in Ranger territory. And I don't like that. What are you doing here in our dominion?}
{201}{}{What are you even talking about? This land doesn't belong to anyone. Only thieves claim for themselves what belongs to everyone.}
{202}{}{An interesting point of view. And a completely pointless one. But I asked you a question - WHAT are you doing here?}
{203}{}{Maybe I'm looking for you. Some have said you're stealing from travelers while pretending to be a Ranger.}
{204}{}{I *am* a Ranger, here's my badge. And I'm not stealing anything. Sometimes I take things as fee for crossing borders. It's my job. You too will have to pay it, by the way.}
{205}{}{This is your territory? You're lying. Prove it.}
{206}{}{You're just a regular old thief.}

{210}{}{Desert heat fried your brain, no? You're not in a position to demand anything. Gimme everything you have and you can go.}
{211}{}{Alright, I'll give you everything I have, just don't hurt me.}
{212}{}{Now scram so I won't see your sorry face again here.}
{213}{}{Whatever you say...}
{214}{}{Hey, give me my stuff back! Right now.}
{215}{}{I won't give you anything back.}
{216}{}{Eh, your loss. Guys, you know what to do...}
{217}{}{Stand up!}
{218}{}{Alright, alright, I'll give you everything. Here, take it...}
{219}{}{These things are awfully radioactive, by the way. You want to risk your health for that?}
{220}{}{I don't buy your tricks. Last warning or you're dead.}
{221}{}{Fine. Just be careful with those things. They're awfully radioactive.}
{222}{}{Put that away, you idiot! Why the hell would you even be carrying that stuff with you?}
{223}{}{For cases like these.}
{224}{}{I need it for a mission.}
{225}{}{No. First, I want to know who you REALLY are. A Ranger wouldn't break the charter.}
{226}{}{You're not a Ranger. A true Ranger would not break the Law.}

{230}{}{I AM the Law. I hold the power here, and who are you to question me? Do as I say!}
{231}{}{To hell with that...}
{232}{}{If you're a Ranger, you're not worthy of your badge. I strip you of your rank. Give me the badge.}
{233}{}{A Ranger who has broken the Law is stripped of their rank. Give me the badge.}

{240}{}{Huh, Law and Order. Those words are empty and meaningless. Rangers come to these lands, declare it their property and force people to pay them taxes. Just because they CAN. How are we worse? If they steal, so will we.}
{241}{}{People receive protection in exchange. And you can always go to another place.}
{242}{}{So the Rangers don't protect their lands?}
{243}{}{People for them are like social fodder. Understand? Nobody will stick their neck out for someone else. I know that. Rangers promised us defense from bandits. But where were they when my village was attacked by bandits?}
{244}{}{Maybe they just didn't make it in time?}
{245}{}{I'm supposed to feel better because of that? For two entire years they taxed us to hell and back. We were malnourished because of that, but they didn't care. And of course, they took the most powerful weapons for themselves. The ones that could have maybe repelled those bandits if we had them.}
{246}{}{A very sad story. You must be very angry now.}
{247}{}{Of course. And don't you think I'll just let you go. Give me all your things. And the clothes.}
{248}{}{I'm not involved with this. Leave me alone.}
{249}{}{The crimes of others are no justification. Give me your badge and I'll spare your miserable life.}
{250}{}{That's terrible. But you should forgive them.}
{251}{}{You take me for an idiot? Give me all your stuff. Slowly so I see it.}
{252}{}{That's terrible. I understand you, my own village was destroyed by slavers.}
{253}{}{I think I heard something about that. So we're both outside the law.}
{254}{}{Exactly. And nobody will notice if I just kill you. Say your last words, loser...}
{255}{}{I beg you - don't kill any more civilians. They aren't guilty of anything. You're taking revenge on the wrong people.}
{256}{}{I KNOW. But what can we do? We're outside the law, we have nowhere to go.}
{257}{}{How about hunting animals or protecting caravans? You can always find a legal way.}
{258}{}{To hell with this conversation. You can't change a criminal's mind...}
{259}{}{We discussed this a lot in our gang. We're tired of living like this. There's not a lot of people in these wastes, and the risks just keep getting bigger and bigger. It's time to do something. The badge? Yeah, sure, take it. It's worthless to me anyway.}
{260}{}{This is a very wise decision. Thank you.}
{261}{}{Scram before I shoot you.}
{262}{}{I'm going, I'm going...}

{300}{}{You again? You didn't get it the first time?}
{301}{}{There's nothing to "get" here. You're a regular old thief. And I don't talk long with those.}
{302}{}{You don't own this land and can't tell me where to go.}
{303}{}{You really are a Ranger?}
