{100}{}{Here is a bandit.}
{101}{}{You see a man who doesn't look like a ranger at all.}
{102}{}{Get out of here before I shoot you.}

#The first dialog
{200}{}{Wait. You're in Ranger land. And I don't like it. What are you doing in our domain?}
{201}{}{What are you talking about? The land is nobody's land. Only robbers appropriate the common property to themselves.}
{202}{}{An interesting point of view. And completely meaningless. But I asked the question - WHAT are you doing here?}
{203}{}{Maybe I'm looking for you. They say you rob travelers under the guise of a ranger.}
{204}{}{I am a ranger, here is my badge. And I'm not robbing anyone. It happens that I take something as a fee for crossing the border. This is my job. By the way, you will also have to pay.}
{205}{}{Is this your territory? You're lying. Prove it.}
{206}{}{You're a simple robber.}

{210}{}{Did the heat of the desert heat your brains? You're not in a position to demand anything. Give everything you have and you can go.}
{211}{}{OK, I'll give it all, just don't hit me.}
{212}{}{And now get out so I don't see you here.}
{213}{}{As you say...}
{214}{}{Hey, give me my stuff! Immediately.}
{215}{}{I'm not giving you anything.}
{216}{}{It's worse for you. Guys, you know what to do...}
{217}{}{Everyone stop!}
{218}{}{OK, I'll give it all. Here, take it...}
{219}{}{These things are terribly radioactive. Do you want to make sure of this on your health?}
{220}{}{I'm not buying these tricks. Last warning, or you're dead.}
{221}{}{Okay. Just be careful with these things. They are terribly radioactive.}
{222}{}{Put it away, you idiot! Why the hell do you carry such stuff with you?}
{223}{}{Just in case.}
{224}{}{This is necessary for one case.}
{225}{}{No. First I want to know who you really are. A ranger wouldn't break the rules.}
{226}{}{You're not a ranger. A real ranger wouldn't break the law.}

{230}{}{I represent the LAW. The power is in my hands, and who are you? Obey!}
{231}{}{The hell with two...}
{232}{}{If you're a ranger, then you're not worthy of your badge. I'm stripping you of your rank. Give me the badge.}
{233}{}{A ranger who has violated the Law is deprived of his rank. Give me the badge.}

{240}{}{Ha, Law and Order. These words are empty and mean nothing. The Rangers came to these lands, declared them their property and levied a tax. Just because they CAN. And why are we worse? If they rob, then we will rob.}
{241}{}{In exchange, residents receive protection. And besides, you can always go somewhere else.}
{242}{}{So are the Rangers not defending their lands?}
{243}{}{People are social fodder for them. Do you understand? No one will risk their own skin for the sake of others. I know it. The Rangers promised us protection from bandits. But where were they when the robbers attacked my village?}
{244}{}{Maybe they just didn't have time?}
{245}{}{Is that supposed to make me feel better? They've been charging us a game tax for two years. We were malnourished, and they didn't care. Besides, they took all the most powerful weapons. If not for that, maybe we would have fought off the attackers.}
{246}{}{What a sad story. You must be very angry now.}
{247}{}{Sure. And don't think I'll let you go so easily now. Take off all your things. And clothes too.}
{248}{}{I have nothing to do with it. Leave me alone.}
{249}{}{Someone else's misdeeds cannot be an excuse. Give me the badge, and I'll have mercy on your miserable life.}
{250}{}{It's horrible. But you have to forgive them.}
{251}{}{Do you take me for an idiot? Take off your things. Slow so I can see.}
{252}{}{It's horrible. I understand you well, because my village was also destroyed by slavers.}
{253}{}{I think I've heard something about it. So you and I are both outlaws.}
{254}{}{Exactly. And no one will notice if I just kill you. Say goodbye to life, loser...}
{255}{}{I ask you - no unnecessary civilian casualties. It's not to blame for anything. You're taking revenge on the wrong people.}
{256}{}{I KNOW. But what should we do? We are outlaws, we have nowhere to go.}
{257}{}{What about hunting game or protecting caravans? You can always find a legal way.}
{258}{}{To hell with talking. Such a criminal cannot be persuaded...}
{259}{}{We discussed it a lot in the gang. We have already been bullied by such a life. There are few people in these wastelands, and the risks are getting higher. It's time to decide something. A badge? Yes, take it. He's no good anyway.}
{260}{}{This is a very wise decision. Thank you.}
{261}{}{Get out before I shoot you.}
{262}{}{I'm already leaving...}

{300}{}{You again? Don't you understand the first time?}
{301}{}{There is nothing to understand here. You're a simple robber. And I have a short dialogue with such people.}
{302}{}{You have no rights to this land and you can't tell me where to go.}
{303}{}{Are you really a ranger?}