{100}{}{You see a bandit.}
{101}{}{You see a man who looks almost, but not quite, entirely unlike a Ranger.}

{110}{}{Come closer if you dare.}
{111}{}{You got no fear at all in you?}
{112}{}{You should fear us.}
{113}{}{Understand one thing - this is OUR territory.}
{114}{}{Today is a good day. I won't have to run around searching for a new victim.}
{115}{}{Show everything valuable you have.}
{116}{}{*Warms up his fists with a grin*}
{117}{}{Looking for trouble, eh?}
{118}{}{Pray that our commander spares you.}
{119}{}{What are you doing here on our land?}
