{100}{}{You see a bandit.}
{101}{}{You see a man who doesn't look like a ranger at all.}

{110}{}{Come closer if you dare.}
{111}{}{Don't you have any fear at all?}
{112}{}{You should be afraid of us.}
{113}{}{Understand - this is OUR territory.}
{114}{}{Today is a good day. You won't have to chase a new victim.}
{115}{}{Show all the valuable things you have.}
{116}{}{*Grinning, he kneads his fists*}
{117}{}{Looking for trouble, huh?}
{118}{}{Pray that the commander will take pity on you.}
{119}{}{What are you doing on our land?}