{100}{}{Here is a ferryman.}
{101}{}{You see a balding Redneck with a distorted face.}
{102}{}{Oh, yes, you know how to please old Redneck.}

#The first dialog
{200}{}{Hey, what are you doing in this wilderness?}
{201}{}{Maybe I'm looking for you.}
{202}{}{Well, I'm Joe. I live here. And I'm guarding this ferry. Do you want to move to the other side? Easily, but this crossing is not for nothing, you know.}
{1202}{}{Well, I'm Joe. I live here. And I'm guarding this ferry. Do you want to move to the other side? Easily, but this crossing is not for nothing, you know.}
{203}{}{I'll think about your offer.}

#Repeat dialog
{210}{}{Healthy.}
{211}{}{Bye.}

{220}{}{How is life in these wild places?}
{221}{}{I'm not complaining. Places are not so remote. A couple of times a day, someone will appear - then rangers, then fishermen, then random travelers. Everyone will share something for the crossing. I have enough to live on.}
{222}{}{[Next]}
{223}{}{Of course, wolves and pig rats sometimes do not give rest, but over the years I have learned to get along with them. By the way, I'm setting snares in the woods, so don't turn off the trail so I don't have to pull you out of my own traps.}

{224}{}{Tell me about the ferry.}
{225}{}{The Rangers offered, and I built. I've been living here ever since. Anyone who needs to go to the other shore is always happy to help.}
{226}{}{Why would someone move to the other shore?}
{227}{}{Basically, patrol rangers need it. But even without them there are enough willing. Many flee to other lands in the hope of finding a cleaner nest. But I'll tell you what - wherever you run, it's the same shit everywhere.}
{228}{}{Are the Rangers okay with you charging?}
{229}{}{They are only happy, because I pay tax on it. I give away, then, once a month all the valuable surpluses - skins, meat, finds of travelers. Sometimes I don't understand what kind of thing they are carrying to me, but the rangers will figure it out.}

{230}{}{How did the dam accident affect your business?}
{231}{}{When this water discharge happened, everything flooded to hell here. I still haven't cleaned all the dirt out of this hut yet! I don't know who could have arranged such a thing. But it's only to my advantage - now the ferry brings more profit.}
{232}{}{Interesting. Tell me more.}
{233}{}{Right now I wanted to talk to you more.}

{250}{}{This family needs to move to the other side.}
{251}{}{Then you'll have to pay. It's inexpensive. And if you don't pay, you won't be able to start the winch. Because I always keep the handle of it with me.}
{252}{}{Let's see what it's worth.}
{253}{}{I'm asking you on behalf of the Rangers.}
{254}{}{Damn, another wasted day... Here, hold the handle. But you will twist it yourself.}
{1254}{}{Damn, another wasted day... Here, hold the handle. But you will twist it yourself.}
{255}{}{Thank you.}
{256}{}{Well, you're a rat after that.}
{257}{}{Wait, I need to ask my mom about the cash.}
{258}{}{Just shut up and get busy. Otherwise you'll get something you don't want to get.}
{259}{}{Come on, show me your hands, you piece of dirt! I strangled my wolves with my own, what are your empty threats to me?}
{260}{}{That's enough!}
{261}{}{I don't like to bargain, you know.}
{262}{}{[Next]}