{100}{}{You see a ferryman.}
{101}{}{You see a balding redneck with a twisted face.}
{102}{}{Oh yeah, you do know how to satisfy an old redneck.}

#Первый диалог
{200}{}{Hey, what are you doing here in these wilds?}
{201}{}{Maybe I'm searching for you.}
{202}{}{Well, I'm Jo. I live here. And guard this ferry. Want to go to the other side? That's easy... but not for free, as I'm sure you already understand.}
{1202}{}{Well, I'm Jo. I live here. And guard this ferry. Want to go to the other side? That's easy... but not for free, as I'm sure you already understand.}
{203}{}{I'll think about your offer.}

#Повторный диалог
{210}{}{Hello there.}
{211}{}{Goodbye.}

{220}{}{What's it like to live in such wild places?}
{221}{}{No complaints. Place isn't that quiet. People show up several times a day - Rangers, fishers, or just some wanderers. Everyone gives something to go to the other side. And it's enough for me to live.}
{222}{}{[Continue]}
{223}{}{Of course, the wolves and pigrats know no rest, but in the years I lived here, I learned to deal with them. Hey, I set up snares in the forest, so don't go away from the road, so I won't have to rescue you from my own traps.}

{224}{}{Tell me about the ferry.}
{225}{}{The Rangers proposed it, and I built it. Been living here ever since. Anyone needs to get to the other side - I'm happy to lend a helping hand.}
{226}{}{Why would someone need to get to the other side?}
{227}{}{Mostly patroling Rangers need it. But there are enough people without them. Many travel to other lands in hope of finding a better place to live. But let me tell you something - wherever you go, it's just as shitty as anywhere else.}
{228}{}{Rangers aren't against you asking for payment?}
{229}{}{They aren't since I pay them taxes from it. Once a month I give them every expensive thing - hides, meat, curiosities found by wanderers. Sometimes I don't even understand what some of the stuff I get is, but the Rangers will find out.}

{230}{}{How has the accident at the dam affected your business?}
{231}{}{When this water discharge happened, everything here was flooded to hell and back. I haven't even managed to scrape off all the dirt in my shack! I can't imagine who would so such a thing. But for me it's helpful - now the ferry is bringing more income than ever.}
{232}{}{Interesting. Tell me more.}
{233}{}{Right now I wanted to talk to you a bit more.}

{250}{}{This family needs to get to the other side.}
{251}{}{Then you'll have to pay. It's cheap. And if you don't pay, you won't be able to turn on the winch. Because I always keep the handle for it with myself.}
{252}{}{Let's see how much this costs.}
{253}{}{I'm asking you on behalf of the Rangers.}
{254}{}{Shit, another day wasted... Here, take the handle. But you'll twist it yourself.}
{1254}{}{Shit, another day wasted... Here, take the handle. But you'll twist it yourself.}
{255}{}{Thank you.}
{256}{}{What a rat you are.}
{257}{}{Wait, I have to ask my mom for money.}
{258}{}{Just shut up and do it. Otherwise you'll get something you'll wish you didn't.}
{259}{}{Fine, show your hands, you piece of shit! I strangled wolves with mine, what are your empty threats to me?}
{260}{}{Fine, stop!}
{261}{}{I don't like to haggle, you know.}
{262}{}{[Continue]}
