{100}{}{There is a lookout in front of you.}
{101}{}{You see a ranger on duty. He guards the entrance to the dam.}

#Passage inside
{110}{}{Talk to Jack if you want to get through.}
{111}{}{Here Jack decides whether to let crooks like you in.}
{112}{}{Do you want to pass? Tell Jack about it.}
{113}{}{I have no orders to let you in.}
{114}{}{Get out of here, this is not a place to walk.}

{115}{}{Come on in and don't bother me.}
{116}{}{They gave you a pass, what else do you need?}
{117}{}{We do not serve tourists.}
{118}{}{If you want to inspect the dam, then go and inspect it.}
{119}{}{It is not necessary to distract the sentry at the post.}

#Ranger Title
{120}{}{Don't you dare distract me at my post.}
{121}{}{Want some advice? Get out of here and don't linger.}
{122}{}{Crooks like you have a lot to learn from the Rangers.}
{123}{}{They don't like idle onlookers hanging around here.}
{124}{}{If you become a cadet, the commander will beat all this nonsense out of you.}

{125}{}{Congratulations on joining, Ranger.}
{126}{}{Even if you were given a badge, but you need to earn my respect separately.}
{127}{}{I'll keep an eye on you... ranger.}
{128}{}{Keep order on the Wastelands.}
{129}{}{I hope now you feel responsible for the affairs in the Wastelands.}

#Robes
{130}{}{Get out of here, you damned sectarian!}
{131}{}{In this robe you look like a walking target.}

{132}{}{More ridiculous armor I have never met.}
{133}{}{Who allowed you to touch the road signs?}

{134}{}{You know, in that blue jumpsuit, you're an easy target against the gray desert.}
{135}{}{Funny clothes you have.}

{136}{}{Hey, who gave you this armor? Answer immediately!}
{137}{}{Hello, rain... Hey, I don't remember you being enlisted in our ranks!}

{138}{}{What's that jar on you? Take it off immediately!}
{139}{}{Cadets are given an excellent uniform made of brahmin skin.}

#Reputation
{140}{}{Get off me.}
{141}{}{I'm not going to chat with you.}
{142}{}{Do you have something to say?}
{143}{}{You shouldn't linger in this settlement.}

{144}{}{Our bullets carry mercy.}
{145}{}{Hello.}
{146}{}{Don't do anything stupid if you want to keep a good reputation.}

{147}{}{Good to see you.}
{148}{}{How are you?}
{149}{}{Have a good trip.}