{100}{}{This is Jack the Lookout.}
{101}{}{You see a ranger on duty. He guards the entrance to the dam.}
{102}{}{Hey, hey, get out of that damn tin can! I'm not kidding!}
{103}{}{We do not negotiate with sectarians of all stripes. Get out!}

#The first dialog
{200}{}{(As you approach the lookouts, you notice how they raise their weapons and change their faces.) Wait, outsiders are not allowed here.}
{201}{}{What's there?}
{202}{}{Over there, right? Behind *this* door? There is the main headquarters of the Rangers.}
{203}{}{Ah, that's it. Then I don't need to go there.}
{204}{}{Then there's nothing to hang around here.}
{205}{}{OK.}
{206}{}{Wait, what are you doing at the base?}
{207}{}{None.}
{208}{}{I just need to talk to your commander.}
{209}{}{Well, well. Not every cadet is allowed to go down. And even more so for you. Do you have a pass?}
{210}{}{You'll regret it later.}
{211}{}{Okay, no problem.}
{212}{}{Listen, this is very important.}
{213}{}{If one of the rangers recommends you, then MAYBE you'll get inside. And now name a more weighty reason. Or get lost.}
{214}{}{Okay, you can come through. But keep in mind, we will be watching your every move. Go to the general and don't turn off anywhere. Keep your weapon in the holster.}
{215}{}{It was possible not to specify.}
{216}{}{Thank you, Ranger.}
{217}{}{I need to talk to your commander.}
{218}{}{Your quartermaster will be interested in my goods.}
{219}{}{You'll regret it if you keep running into trouble. Get out.}

{220}{}{You should not walk around the base in this rag. Many may mistake you for a saboteur.}
{221}{}{Why?}
{222}{}{You know why. This is the mantle of the Followers of Fire, and we don't like these guys. They climb with their charter into someone else's monastery. This is unacceptable.}
{223}{}{I see.}
{224}{}{Isn't that the guy Old Rufus was waiting for? Well done for bringing him. Let it benefit the Wastelands. Such craftsmen have no place in the garbage heap.}
{1224}{}{Isn't that the guy Old Rufus was waiting for? Well done for bringing him. Let it benefit the Wastelands. Such craftsmen have no place in the garbage heap.}
{225}{}{It's not my business anymore. Then you'll figure it out without me.}
{226}{}{It's good that you find a common language.}
{227}{}{Hey, are you tired of living?! What the hell happened to Flick?}
{228}{}{Were you close to him?}
{229}{}{Are we? Half the base thought he was a bitch. But that's no reason to kill the merchant! Okay, I don't know what happened there. This will be handled by the commission. And if you are somehow involved in this, then do not expect good from the rangers.}
{1229}{}{We? Half the base thought he was a bitch. But that's no reason to kill the merchant! Okay, I don't know what happened there. This will be handled by the commission. And if you are somehow involved in this, then do not expect good from the rangers.}

{230}{}{Commander Helford guaranteed me a pass.}
{231}{}{Perhaps the general will be interested in the story of Keruk from Flagstaff.}
{232}{}{I helped the rangers in San Brahmin.}
{1232}{}{I helped the rangers in San Brahmin.}
{233}{}{I have information from a spy in Two-Sun.}
{234}{}{The base should know about my connection with the Phoenix Rebels.}
{235}{}{I have very important information. This concerns the Brotherhood of Steel.}
{236}{}{Hey, I'm just passing by.}
{237}{}{I have a report straight from the Phoenix Cathedral.}

#Repeat dialog
{250}{}{Hi.}
{251}{}{Bye.}

{260}{}{I want to report a fugitive spy who is hiding in a shack on the old road...}
{261}{}{...Thanks for the tip. We will send scouts there and try to catch the bastard by surprise.}
{262}{}{}
{263}{}{Success in the operation.}

{270}{}{Is it possible to cross to the other shore here?}
{271}{}{Only by the decision of the commanders. Passage on the dam is prohibited for civilians. If you need to go to the other shore, I suggest you swim.}
{272}{}{Where is the nearest ferry?}
{273}{}{There is a ferry fifteen miles downstream.}
{274}{}{So you took the only crossing to the other side?}
{275}{}{Yes. And this is our right. Any problems?}
{276}{}{Uh, no, none.}
{277}{}{Yes. It's not fair.}
{278}{}{Then shove this injustice back where it came from.}
{279}{}{That's how it is...}
{280}{}{Why don't you let this woman see the General?}
{281}{}{The General is too busy.}
{282}{}{Really? And it seems to me that he simply does not want to be responsible for the misdeeds of his soldiers.}
{283}{}{What nonsense is this? This woman served a criminal and got what she deserved. If you want to help her, you'd better get her away from the base before I lose my temper completely.}
{284}{}{Okay, never mind.}