{100}{}{You see a lookout.}
{101}{}{You see a Ranger at his post. He's protecting the entrance to the dam.}

#Проход внутрь
{110}{}{Talk to Jack if you want to get inside.}
{111}{}{Here Jack decides whether to allow people like you inside or not.}
{112}{}{Want to get inside this dam? Tell Jack about it.}
{113}{}{I don't have the clearance to let you in.}
{114}{}{Get outta here, this is no place for walks.}

{115}{}{Get inside and don't disturb me.}
{116}{}{You were given the clearance, what more do you need?}
{117}{}{We don't serve tourists.}
{118}{}{You want to see the dam? Then go and see it.}
{119}{}{You shouldn't distract a lookout while he's at his post.}

#Титул рейнджера
{120}{}{Don't dare to distract me on my post.}
{121}{}{You want a tip? Get outta here and don't take too long.}
{122}{}{People like you have a lot you could learn from the Rangers.}
{123}{}{Here we don't like people like you, who idly yawn and wander without any purpose.}
{124}{}{If you become a cadet, the commander will beat all this nonsense out of you.}

{125}{}{Congratulations with the promotion, Ranger.}
{126}{}{You may have received a badge but you'll have to earn my respect separately.}
{127}{}{I'll be watching you... Ranger.}
{128}{}{Maintain order out there in the Wastes.}
{129}{}{I hope now you feel responsibility for your actions in the Wastes.}

#Одеяния
{130}{}{Scram, you damn cultist!}
{131}{}{You look like a walking target in those robes.}

{132}{}{I have never seen a more ridiculous piece of armor in my life.}
{133}{}{Who allowed you to touch the road signs?}

{134}{}{You know, you look like an easy target in this blue jumpsuit while walking through the gray desert.}
{135}{}{You have funny clothes.}

{136}{}{Hey, who gave you this piece of armor? Answer immediately!}
{137}{}{Greetings, Rang... Hey, I don't remember you being enlisted in our ranks!}

{138}{}{Why is there a tin can on your clothes? Take it off right now!}
{139}{}{Our cadets are given an excellent uniform made from brahmin skin.}

#Репутация
{140}{}{Buzz off.}
{141}{}{I ain't gonna chat with you.}
{142}{}{Anything to say?}
{143}{}{You shouldn't spend too much time here in this settlement.}

{144}{}{Our bullets carry mercy.}
{145}{}{Hello.}
{146}{}{Don't do anything stupid if you want to maintain a good reputation.}

{147}{}{Happy to see you.}
{148}{}{How are you?}
{149}{}{Good luck in your travels.}
