{100}{}{You see lookout Jack.}
{101}{}{You see a Ranger at his post. He's protecting the entrance to the dam.}
{102}{}{Hey-hey, get out of that damn hunk of metal! I'm not kidding!}
{103}{}{We don't negotiate with cultists of whatever organization. Get outta here!}

#Первый диалог
{200}{}{(Walking up to the lookouts, you notice as they, raising their weapons, change their faces in their tone.) Stop. Outsiders are not allowed here.}
{201}{}{What's there?}
{202}{}{*There*, huh? Behind *that* door? Ranger headquarters.}
{203}{}{Ah, so that's what's there. Then I don't need to go there.}
{204}{}{Then there's no reason for you to wobble around.}
{205}{}{Okay.}
{206}{}{Stop, what business do you have on the base?}
{207}{}{No business.}
{208}{}{I need to speak with your commander.}
{209}{}{No. Very few *cadets* are allowd to go down there. And you're not even a cadet. Do you have a permit?}
{210}{}{You'll regret this.}
{211}{}{Alright, no problem.}
{212}{}{Listen, it's very important.}
{213}{}{If one of the Rangers recommends you, then MAYBE you'll be allowed to go inside. Now name a better reason. Or get outta here.}
{214}{}{Okay, you can go inside. But keep in mind that we'll be watching your every step. Go straight to the general and nowhere else. Keep your weapon in your holster.}
{215}{}{That did not need to be specified.}
{216}{}{Thank you, Ranger.}
{217}{}{I need to speak to your commander.}
{218}{}{Your quartermaster will be interested in my goods.}
{219}{}{You'll regret this if you keep looking for trouble. Get outta here.}

{220}{}{You shouldn't walk in this rag in the base. Some may take you for a saboteur.}
{221}{}{Why?}
{222}{}{You know why. These are the robes of the Followers of the "Holy" Fire, and we don't like those guys. They push their faith into other people's temples. This is unacceptable.}
{223}{}{Alright.}
{224}{}{This is that guy Old Man Rufus was waiting for? Great that you brought him here. Let him benefit the Wasteland here. Such minds aren't meant to rot away in scrapyards.}
{1224}{}{This is that guy Old Man Rufus was waiting for? Great that you brought him here. Let him benefit the Wasteland here. Such minds aren't meant to rot away in scrapyards.}
{225}{}{I done what I was asked for. You'll figure it out without me from this point on.}
{226}{}{It's great that you are understanding one another.}
{227}{}{Hey, you tired of living?! What the hell happened to Flick?}
{228}{}{You two were close?}
{229}{}{We? Half the base thought he was a son of a bitch. But that isn't a reason to kill the guy! Fine, I don't know how it all happened. The commision will figure that out. And if you're somehow involved in that, don't expect any kindness from the Rangers.}
{1229}{}{We? Half the base thought he was a son of a bitch. But that isn't a reason to kill the guy! Fine, I don't know how it all happened. The commision will figure that out. And if you're somehow involved in that, don't expect any kindness from the Rangers.}

{230}{}{Commander Helford promised me permission to enter.}
{231}{}{Perhaps the general will be interested in what Kheruc from Flagstaff has to say.}
{232}{}{I have helped Rangers in San-Brahmin.}
{1232}{}{I have helped Rangers in San-Brahmin.}
{233}{}{I have information from a spy in Two Sun.}
{234}{}{Those on the base must know of my connections to the Phoenix rebels.}
{235}{}{I have very important information. It's about the Brotherhood of Steel.}
{236}{}{Hey, I'm just passing by.}
{237}{}{I have a report straight from the Cathedral in Phoenix.}

#Повторный диалог
{250}{}{Hi.}
{251}{}{Bye.}

{260}{}{I want to report a fugitive spy who is hiding in the shack on the old road...}
{261}{}{...Thanks for reporting this. We'll send scouts there and try to catch the bastard off-guard.}
{262}{}{}
{263}{}{Good luck in your operation.}

{270}{}{Can I go to the other side from here?}
{271}{}{Only if you get the commanders' approval. Civilian movement across the dam is strictly forbidden. If you need to get to the other side, I suggest you go down and start swimming.}
{272}{}{Where's the nearest ferry?}
{273}{}{Fifteen miles downstream.}
{274}{}{So you claimed the only passage to the other side?}
{275}{}{Yes. And it's our right to do so. Problem?}
{276}{}{Uhh, no, no problems at all.}
{277}{}{Yeah. It's unfair.}
{278}{}{Then push your unfairness back to where it crawled from.}
{279}{}{So this is how it is...}
{280}{}{Why are you not letting this woman see the general?}
{281}{}{The general is too busy.}
{282}{}{Is that so? To me it seems liek he isn't willing to take responsibility for what his soldiers have done.}
{283}{}{What is this nonsense? The woman served a criminal and got what she deserved. You want to help her - better bring her away from the base, before I finally lose my temper.}
{284}{}{Fine, let's end this discussion.}
