{100}{}{You see Cadet Presley.}
{101}{}{You see one of the recruits.}
{102}{}{Rest in peace, Cadet Presley.}
{103}{}{Hey, Cadet, don't you dare die!}
{104}{}{Good luck on the road.}
{105}{}{The Milton hut is ahead, but we need to find the entrance to the cave.}
{106}{}{Do you have any problems with the Milton family?}

#The first dialog
{200}{}{(in front of you is a young cadet with a very dissatisfied look; he sits in an expectant pose and from time to time kicks the garbage under his feet to relieve tension.)}
{201}{}{Why aren't you in the ranks?}
{202}{}{Commander Agatha reprimanded me for my willfulness. What's it to you?}
{203}{}{And you're one of the obstinate soldiers, right?}
{204}{}{Damn, I'm just tired of this senseless drill! I want *real* field assignments, not shooting coyotes on caravan routes.}
{205}{}{Looks like you have big ambitions, man.}
{206}{}{Maybe so. But I think it's pointless to wait another three years before the first test. If Commander Agatha does not return my equipment and does not let me go to work, I will go there with only one spear.}
{207}{}{As you know. In the meantime, I'll talk to your commander.}
{208}{}{You're just a narcissistic bully. Bye, loser.}
{209}{}{Don't you dare be rude to me, you greenhorn.}

#Repeat dialog
{210}{}{What do you want?}
{211}{}{Nothing. Later.}

{220}{}{Why did you take the rifle from the warehouse?}
{221}{}{Combat weapons are issued only for the duration of tasks and training. Besides, cartridges need to be saved. I wanted to take a rifle and go to the cave of Giers Wash. But the quartermaster quickly sensed my plan.}
{222}{}{What is so important in that cave?}
{223}{}{Locals say that rodents live in the cave, and they annoy them a lot. But all the rangers are busy for such a small matter, and the commanders refuse to send cadets, they consider us not ready.}
{224}{}{[Next]}
{225}{}{I wanted to deal with the problem alone, to wipe the nose of all the old men with stripes. We have to do something, not shake in the gym!}
{226}{}{Your dedication inspires respect.}
{227}{}{In my opinion, you only wanted to show yourself.}
{228}{}{What did you say about the Giers Wash Cave?}

{230}{}{Do you get along with the other cadets?}
{231}{}{It's different with everyone. Some people make me mad, I try to ignore them.}
{232}{}{I see.}
{233}{}{Tell me honestly, you've killed before... a person?}
{234}{}{Not yet. Cadets are sent at best to shoot wolves. But I will kill the criminal bastards, as any ranger should.}
{235}{}{I didn't even think about it.}

#Quest
{300}{}{About that outing. We can do it together.}
{301}{}{Seriously? But why would you risk it?}
{302}{}{I also want to participate in the roundup. It'll be fun.}
{303}{}{That's for sure. We are not allowed to shoot from serious weapons, they save ammunition, and it makes sense to shoot from pneumatics only at dead targets.}
{304}{}{I want to help the Rangers in their difficult task.}
{305}{}{Are you looking for friends among our brothers? Tricky. Everyone in the wastelands needs a strong patron.}
{306}{}{Agatha asked me to keep an eye on you.}
{307}{}{Really? Do you think I need a mentor to shoot ordinary rodents? Although... I really could use a partner... and I need a witness, just in case.}
{308}{}{So?}
{309}{}{It's a deal! But I can't go there without a gun.}
{310}{}{The extradition order is already on the quartermaster's desk. Thank your supervisor.}
{311}{}{What?! How did you manage it?! Cool, I'm going to the warehouse right now. You, too, prepare for a sortie. Meet me outside, near the info center.}
{312}{}{See you.}

{320}{}{I'm ready to move out. And you?}
{321}{}{Wait a little longer.}
{322}{}{What can we use?}
{323}{}{It will be dark in the cave, so you should stock up on a couple of flares. And most likely there are a lot of pig rats. Alone they are weak, but all together they can become a problem. The best weapon against such a crowd is a shotgun. However, I have no idea where to get one.}
{324}{}{It's worth considering.}
{325}{}{Then let's move out.}
{326}{}{Why did we come back? Did you forget something?}
{1326}{}{Why did we come back? Did you forget something?}
{327}{}{Don't worry, I won't be long.}
{328}{}{Okay, but let's hurry up.}
{329}{}{OK.}
{330}{}{Such a crowd? This is not the best tactic for cramped caves. Besides, we'll scare the animals away. Someone will have to leave.}
{331}{}{I'll talk to my partner about it.}
{332}{}{Listen, about that story with the Milton family. Let's agree that we have nothing to do with it, okay? I shouldn't have gone on this damn hike. I don't think the pig-rat's head was worth it. Goodbye.}
{333}{}{Goodbye, Cadet Presley.}
{334}{}{Why... why did he do it?}
{335}{}{Are you all right?}
{336}{}{I don't know... This bandit... He had a weapon, he could have found another way to survive. But he attacked a defenseless family. Why did he do it?}
{337}{}{He didn't know any other way.}
{338}{}{I'm no better, right? Now I understand why all this training was needed at the base. And why we are not allowed to do important tasks. Now I will take the words of veterans more seriously.}
{339}{}{Thanks to this outing, you've become a little wiser. Goodbye, cadet.}
{340}{}{Remember the main lesson of the Wasteland - kill or you will be killed yourself. And it's time for me to go back to the desert.}
{341}{}{It was a great operation, wasn't it? I'm going to show the head to the others in the dining room. Good luck on the road.}
{342}{}{Goodbye, Cadet Presley.}

{350}{}{Keep an eye on the sides.}
{351}{}{Let's move on.}
{352}{}{So what is our task?}
{353}{}{Find and kill Nat-Aani. So the locals called it the biggest and most dangerous pig-rat of this cave.}
{354}{}{What does this name mean?}
{355}{}{Just that he's the leader of the pack. This means that he is the strongest and fiercest of his fellows.}
{356}{}{What do you know about the Milton family?}
{357}{}{Don't you care? Well, they're ordinary low-income residents. They live mainly by gathering and fishing. There is nothing to tell about them.}
{358}{}{Let's not talk about it.}
{359}{}{What the hell happened with the Miltons? They never seemed to be hostile.}

{360}{}{We did it! I'll cut off this pig's head and show it to the old folks at the base. Now they will know that I am ready for serious business!}
{361}{}{Is that what you're hunting for?}
{362}{}{Sure. And why else would I help these beggars? They are of little use, the rewards will not be paid and the reputation will not be raised. But with such a feat of service, I am entitled to at least a double ration. Ha!}
{363}{}{Hmm. Let's get out.}

{364}{}{What?! Is this a joke? I didn't count on fighting a bandit when I came here!}
{365}{}{What is it, Cadet? You've just been bloodthirsty rejoicing, cutting off the head of a pig-rat.}
{366}{}{But this is different! Oh, damn, it's such a bad time... What should I do now?}
{367}{}{We need to act now. While we wait for help, he will have time to escape or prepare for a siege. Someone will surely die.}
{368}{}{Right. Now we have every chance. He is not expecting our appearance and is busy with other things. But let's be careful - man is not an animal, he is smarter.}
{369}{}{Let's go.}
{370}{}{We can't stand up to a gunman with a shotgun. We have to escape to the base.}
{371}{}{Right. But during this time, he will thoroughly prepare himself and will surely kill someone. We'd better get out of here and not tell anyone about this.}
{372}{}{Come on.}