{100}{}{You see cadet Presley.}
{101}{}{You see one of the new recruits.}
{102}{}{Rest in peace, cadet Presley.}
{103}{}{Hey cadet, this is no time to die!}
{104}{}{Good luck in your travels.}
{105}{}{The Milton shack is in front of us, but we need to find the entrance to the cave.}
{106}{}{You have something against the Milton family?}

#Первый диалог
{200}{}{(you see a young cadet in a clearly unhappy mood; he is sitting like he is waiting for something and kicks the rubbish near his feet to relieve tension from time to time.)}
{201}{}{Why are you not in line?}
{202}{}{Captain Agatha reprimanded me for not following orders. Why are you asking?}
{203}{}{You're not one of those obstinate soldiers, right?}
{204}{}{Damn, I was just tired of these pointless drills! I want *real* field missions, not shooting coyotes on caravan routes.}
{205}{}{Looks like you have a lot of ambition, buddy.}
{206}{}{Maybe so. But I think waiting three more years for the first real challenge is pointless. If commander Agatha doesn't return my equipment and doensn't send me on a mission, I'll go there with just a spear.}
{207}{}{Whatever you say. In the meantime I'll go speak to your commander.}
{208}{}{You're just a narcissistic bully. Bye-bye, loser.}
{209}{}{Don't you dare be rude to me, you green.}

#Повторный диалог
{210}{}{What?}
{211}{}{Nothing. Bye.}

{220}{}{Why did you take the rifle from the warehouse?}
{221}{}{Weapons are only given out for missions and drills only. And you have to conserve ammo. I wanted to take the rifle and head to the Giers Wash cave. But the quartermaster figured out my plan quickly.}
{222}{}{What's so important about that desert?}
{223}{}{Locals say that there's a lot of rodents living in that cave, and they are seriously harming the villagers. But the Rangers are too busy to deal with such a small thing, and the commanders refuse to send cadets, since they say we're "not ready".}
{224}{}{[Continue]}
{225}{}{I wanted to solve the problem alone, myself, to show those striped old people how wrong they are. We should be doing something, not fooling around in the gym!}
{226}{}{Your dedication demands respect.}
{227}{}{I think you just wanted to show what *you* were capable of.}
{228}{}{What did you say about that Giers Wash cave?}

{230}{}{What is your relationship with the other cadets?}
{231}{}{Different with each. Some make me mad so I try to ignore them.}
{232}{}{Alright.}
{233}{}{Be honest, have you ever killed... a human being?}
{234}{}{Not yet. Best thing we cadets can hope for is to be sent to exterminate wolves. But I *will* kill criminal scum, as every Ranger is supposed to.}
{235}{}{Never even thought about it.}

#Квест
{300}{}{About that sally. Maybe we could do it together.}
{301}{}{Really? But why should you risk your own hide?}
{302}{}{I want to participate in the raid. It'll be fun.}
{303}{}{That's right. They don't let us fire the serious weaponry, they make us conserve ammo, and the pneumatic stuff they give us is only good for firing on dead targets.}
{304}{}{I want to help the Rangers in their hard mission.}
{305}{}{Seeking friends around here? Sly. Everyone in the wasteland needs someone strong, someone to protect them.}
{306}{}{Agatha asked me to watch over you.}
{307}{}{Really? You think I need a mentor for shooting regular rodents? Though... having a companion wouldn't hurt... And a witness, just in case.}
{308}{}{So?}
{309}{}{Let's go! But I can't go there without weapons.}
{310}{}{The order to issue it is already on the quartermaster's table. Thank your inspector.}
{311}{}{What?! So you did it?! Great, I'll head to the warehouse immediately. You should also prepare for the sally. We'll meet outside, by the infocenter.}
{312}{}{See you later.}

{320}{}{I'm ready to move out. You?}
{321}{}{Wait a tiny bit.}
{322}{}{What stuff would be useful?}
{323}{}{It'll be dark in the cave, we should take a couple of flares. And there is likely to be a lot of pigrats. Alone they're weak, but together they could be a problem. Best weapon against such a group is a shotgun. Though to be honest, I have absolutely no idea where we could get one.}
{324}{}{That is worth considering.}
{325}{}{Then we move out.}
{326}{}{Why did we go back? You forgot something?}
{1326}{}{Why did we go back? You forgot something?}
{327}{}{Don't worry, I won't take long.}
{328}{}{Fine, but do it fast.}
{329}{}{Ok.}
{330}{}{In a group like this? That isn't the best tactic for tight caves. And we'll just frighten the animals. Someone must be left behind.}
{331}{}{I'll talk this over with my companion.}
{332}{}{Listen, about that story with the Milton family. Let's agree that we are not related to this at all, okay? I knew it was a mistake to go into this fucking sally. I don't think this pigrat head was even worth it. Bye.}
{333}{}{Goodbye, cadet Presley.}
{334}{}{Why... why did he do that?}
{335}{}{Are you okay?}
{336}{}{I don't know... This bandit... He had a weapon, he could have found another way to survive. But he attacked a defenseless family. Why did he do that?}
{337}{}{He did not know of any other way.}
{338}{}{I'm not any better, right? Now I see why we had to go through all the drills at the base. Why we aren't yet allowed to do serious assignments. I'll take what the veterans say more seriously from now on.}
{339}{}{You became a bit wiser thanks to this sally. Goodbye, cadet.}
{340}{}{Remember the key lesson of the Wasteland - kill or be killed. As for me, I have to go back to the desert.}
{341}{}{This was great, wasn't it? I'll go show the head to the others in the dining room. Good luck in your travels.}
{342}{}{Goodbye, cadet Presley.}

{350}{}{Watch your back.}
{351}{}{Let's go.}
{352}{}{So, what's our goal here?}
{353}{}{Find and kill Nataani. That's how the locals call the biggest and most dangerous pigrat of this cave.}
{354}{}{What does that name mean?}
{355}{}{Only that it's the pack leader. Which means it's the strongest and most ferocious out of them all.}
{356}{}{What do you know about the Milton family?}
{357}{}{Why do you care? Well, they're average, they're poor, and they live here. They survive on fishing and gathering. Not much to say about them.}
{358}{}{Let's not talk about this any longer.}
{359}{}{What the hell happened between you and the Miltons? They never seemed to be aggressive before.}

{360}{}{We did it! I'll cut that pig's head off and show it to the old guys on the base. They'll see that I'm ready for serious assignments!}
{361}{}{You planned this hunt just for that?}
{362}{}{Of course. Why else would I help those bums? They're of little use, they won't give you a reward and won't raise your reputation. But for this kind of deed I'll get a double ration minimum. Ha!}
{363}{}{Hmm. Let's get out of this place.}

{364}{}{What?! What is this, a joke? I didn't expect a fight with a bandit when I was coming here!}
{365}{}{What's the matter, cadet? You were just reveling in blood, cutting off a pigrat's head a couple of minutes ago.}
{366}{}{But that's different! Ugh, dammit, what inconvenient timing... What do we do now?}
{367}{}{We have to act. Now. If we wait for help, he'll just run away or prepare for a siege. Someone would surely die then.}
{368}{}{Exactly. Right now the odds are stacked in our favor. He isn't expecting us to show up and is busy with other things. But still, we should be careful - man isn't an animal, he's smarter.}
{369}{}{Let's go.}
{370}{}{We can't deal with a bandit with just a shotgun. We have to run for the base.}
{371}{}{Exactly. But during that time he'll thoroughly prepare and will surely kill someone. It would be better to get outta here and don't tell anybody about this.}
{372}{}{Let's go.}
