{100}{}{Here is a ranger.}
{101}{}{You see a private ranger.}
{102}{}{This is a temporary isolation ward, there is no place for outsiders here.}

#Floating replicas
{110}{}{Until we eliminate the Jackals, the way to the north is closed.}
{111}{}{I would like to put a mug of root beer to the one who saved us from the Jackals.}
{112}{}{I can't believe we're putting up with these Jackals!}

{113}{}{They say there are green plantations in the north in the middle of a barren desert.}
{114}{}{Damn, even the peasants in the Villa bent under our enemy.}
{115}{}{These peasants in the north demand too much for their ears.}

{116}{}{Without rangers, the ranchers in San Brahmin will not survive.}
{117}{}{These pastoralists in San Brahmin will regret that they betrayed our union.}
{118}{}{The Red menace almost captured San Brahmin, but everything went well.}

{119}{}{Flagstaff will pay for slavery someday.}
{120}{}{As long as Flagstaff doesn't do slavery, I don't care what happens there.}
{121}{}{Flagstaff is expanding. This is not good.}

{122}{}{The fire worshippers must be stopped before they finally burn out these lands.}
{123}{}{The Cult of fire is defeated by its own weapon}
{124}{}{The damned sectarians are seizing more and more land.}

{125}{}{What is this mysterious "threat from the south"?}
{126}{}{The Brotherhood of Steel got what it deserved. There is nothing to climb on foreign lands.}
{127}{}{But will we be able to resist the Brotherhood of Steel?}

{128}{}{The Parker Dam was the fruit of the wisdom of the people of the Old World.}
{129}{}{Damn, it won't be easy to create a new base instead of this one.}
{130}{}{Old Rufus did something at the power plant.}

{131}{}{That peasant has great prospects.}
{132}{}{Are all the peasants in the Villa the same great guys?}

{133}{}{We need to keep an eye on this peasant.}
{134}{}{We need to get to know that peasant better.}

{135}{}{That peasant looks suspicious.}
{136}{}{I don't like this peasant.}

{137}{}{Someday we will change the Wastelands.}
{138}{}{They say someone killed the ferryman.}
{139}{}{Someone was digging the graves of our brothers. And it doesn't look like mutants from the wastelands.}

{140}{}{There is peace and quiet in the Aqueduct.}
{141}{}{It was hard to imagine that Garth was behind the disappearances.}
{142}{}{William Garth is paranoid.}

#Retaliatory remarks
{150}{}{The Rangers are loyal to their service. Until the last breath.}
{151}{}{Our bullets hit without a miss.}
{152}{}{Someday we will change the Wastelands.}
{153}{}{It would be great to have a car on the move...}
{154}{}{It's high time to deal with these bloodthirsty Jackals.}
{155}{}{The red threat is rising in the east.}
{156}{}{Be careful on the wastelands.}
{157}{}{Here you are under full protection.}
{158}{}{Don't ask me anything.}
{159}{}{You'd make a good ranger.}
{160}{}{The most frightening desert monsters appear at night.}
{161}{}{Good luck.}

{170}{}{Looking for trouble?}
{171}{}{Our bullets hit without a miss, keep in mind.}
{172}{}{You're on time - we need live targets at the shooting range.}
{173}{}{You're not going to choose the best place to walk.}
{174}{}{What's on your mind?}
{175}{}{Hmm, you look suspicious.}
{176}{}{Don't ask me anything.}
{177}{}{No one will protect you here.}
{178}{}{We will change the Wastelands.}
{179}{}{Any problems?}

{180}{}{Nice to meet you, Ranger.}
{181}{}{Sorry, but I can't escort you to the base.}
{182}{}{You make the Wastelands better.}
{183}{}{We're glad you're on our side.}
{184}{}{Drop by our base.}
{185}{}{Be careful, Ranger.}
{186}{}{I can't wait to hear your story about the new lands.}
{187}{}{It would be great to have a car on the move...}
{188}{}{Someday we will change the Wastelands.}
{189}{}{Don't let the hucksters fool you.}