{100}{}{You see a Ranger.}
{101}{}{You see a common Ranger.}
{102}{}{This is a temporary infirmary, no place for outsiders.}

#Плавающие реплики
{110}{}{Until we terminate the Jackals the way north is essentially off-limits.}
{111}{}{I wish I could give a root beer to whoever got rid of the Jackals.}
{112}{}{I can't believe we made peace with those Jackals!}

{113}{}{There are rumours about green plantations among barren desert to the north.}
{114}{}{Dammit, even those Villa peasants are now under the enemy's banner.}
{115}{}{Those peasants to the north demand far too much for their corn cobs.}

{116}{}{The pastoralists in San-Brahmin won't last long without the Rangers.}
{117}{}{Those pastoralists will regret betraying our alliance.}
{118}{}{The red menace almost captured San-Brahmin but it ended up okay.}

{119}{}{Flagstaff will one day pay for using slavery.}
{120}{}{As long as Flagstaff doesn't use slavery I don't care what happens there.}
{121}{}{Flagstaff is expanding. This doesn't mean anything good.}

{122}{}{The fire-worshippers must be stopped before they burn up these lands forever.}
{123}{}{The fire cult, defeated by it's own weapon.}
{124}{}{The damned cultists are conquering more and more territory.}

{125}{}{What's this mysterious "threat from the south"?}
{126}{}{The Brotherhood of Steel got what it deserved. Messing with things in other people's lands is not good at all.}
{127}{}{But can we resist the Brotherhood of Steel?}

{128}{}{Parker Dam was the product of the wiseness of Old World people.}
{129}{}{Damn, it will be hard to create a new base to replace this one.}
{130}{}{Old man Rufus adjusted something in the power plant.}

{131}{}{That peasant has big perspectives.}
{132}{}{Are all peasants in Villa as great as this one?}

{133}{}{I should watch this peasant.}
{134}{}{I should get to know this peasant better.}

{135}{}{That peasant looks suspicious.}
{136}{}{I don't like that peasant.}

{137}{}{One day we'll change the Wastes.}
{138}{}{They say someone killed the ferryman.}
{139}{}{Someone has dug the graves of our fellows. And it doesn't look like any mutant from the Wastes.}

{140}{}{There's peace and quiet in Aqueduct.}
{141}{}{It's hard to imagine that Gart was behind the dissapearances all along.}
{142}{}{William Gart is quite the paranoiac.}

#Ответные реплики
{150}{}{The Rangers serve their cause till their last breath.}
{151}{}{Our bullets hit without missing.}
{152}{}{One day we'll change the Wastes.}
{153}{}{It would be good to have a functioning automobile...}
{154}{}{We should have already dealt with those bloodthirsty Jackals a long time ago.}
{155}{}{The red threat is rising in the east.}
{156}{}{Be careful in the wastes.}
{157}{}{Here you are fully protected.}
{158}{}{Don't ask me anything.}
{159}{}{You would make a fine Ranger.}
{160}{}{The scariest monsters of the desert show up during the night.}
{161}{}{Good luck.}

{170}{}{Looking for trouble?}
{171}{}{Our bullets hit without missing, keep that in mind.}
{172}{}{You're just in time - we need live targets at our shooting range.}
{173}{}{You have not chosen the best place to take a walk.}
{174}{}{What's on your mind?}
{175}{}{Hmm, you look suspicious.}
{176}{}{Don't ask me anything.}
{177}{}{No-one here is going to protect you.}
{178}{}{We'll change the Wastes.}
{179}{}{Problem?}

{180}{}{Glad to meet you, Ranger.}
{181}{}{Sorry, but I can't accompany you to the base.}
{182}{}{You're improving the Wastes.}
{183}{}{We're glad to have you on our side.}
{184}{}{Visit the base from time to time.}
{185}{}{Be careful, Ranger.}
{186}{}{Can't wait to hear your report about the new lands.}
{187}{}{It would be good to have a functioning automobile...}
{188}{}{One day we'll change the Wastes.}
{189}{}{Don't let traders fool you.}
