{100}{}{You see Ranger Agatha.}
{101}{}{You see a veteran ranger in combat armor.}
{102}{}{The Ranger is not paying attention to you. It's better to wait a bit.}
{103}{}{I don't want to see you.}
{104}{}{Agatha ignores you.}

#Cut-scene of an argument with the general:
{110}{}{This is crazy!}
{111}{}{Do you know how many of our fighters have fallen from the claws of Jackals?!}
{112}{}{These scum must be destroyed!}
{113}{}{All to the very last puppy!}
{114}{}{And you... you ally with them!}
{115}{}{It's disgusting!}
{116}{}{You can reprimand me as much as you like for insubordination...}
{117}{}{But other rangers agree with me - it's wrong!}
{118}{}{No alliance will change these savages...}
{119}{}{...and certainly will not bring back the dead rangers.}
{120}{}{And I won't let it go so easily!}

{200}{}{Hey! It's your fault! Jackals have been terrorizing the lands in the north for years. A lot of great rangers died because of their tricks. I'm not going to tolerate this blasphemous alliance with savages. Now get lost!}
{201}{}{Learn forgiveness. Maybe you'll change your mind when you see the real prospects of this union.}
{202}{}{Your combat brain doesn't have enough convolutions to appreciate this truce. Stay in the dark, lady.}