{100}{}{This is Ranger Jason.}
{101}{}{You see your old friend from the Jackal holes. He seems to be coming back to normal.}

{200}{}{So we met. As you can see, with your help, I'm still alive and can even keep the formation.}
{201}{}{You look a little better after the Jackals.}
{202}{}{The journey was difficult, but we are being prepared for such difficulties. Look, we need people like you. Join the Rangers! However, my recommendation alone is not enough for acceptance. But I told Commander Helford about your feat. Talk to him.}
{203}{}{I'll think about your offer.}
{204}{}{The path was difficult, but we are being prepared for such difficulties. However, since I saw you on the rookie list, it's not for me to tell you about it. Congratulations on your acceptance, Ranger. Use your position for the benefit of the inhabitants of the wastelands.}
{205}{}{Thank you, Ranger Jason, for the kind welcome. But I have to go.}
{206}{}{A lot of words, and a personal rifle will not be given out. Okay, we'll meet again.}

{210}{}{Glad you dropped by for a light.}
{211}{}{See you later.}
{212}{}{What do you think about the Rangers and Jackals alliance?}
{213}{}{After what I've been through, it seems like a ridiculous nightmare. Where is the command center looking?! But my job is to obey orders, not to discuss them.}
{214}{}{Clearly.}