{100}{}{You see Ranger Jason.}
{101}{}{You see your old friend from the Jackal burrows. Looks like he's recovering.}

{200}{}{So we meet again. As you see, with your help I'm still alive and can even hold the line.}
{201}{}{You look slightly better after that incident with the Jackals.}
{202}{}{The journey was hard but we are trained for such hardships. Listen, we need people like you. Join the Rangers! Though to be fair, just one recommendation from me is not enough to be accepted. But I told of what you did to commander Helford. You should talk to him.}
{203}{}{I'll think about your offer.}
{204}{}{The journey was hard but we are trained for such hardships. Anyways, I saw you in the list of new recruits. Congradulations with being accepted, Ranger. Use your position for the good of the inhabitants of the wastes.}
{205}{}{Thank you, Ranger Jason, for such a kind welcome. But I have to go.}
{206}{}{So many word yet still they won't give me a personal rifle. Fine, we'll meet again.}

{210}{}{I'm glad you visited us.}
{211}{}{See ya.}
{212}{}{What do you think of the alliance between the Rangers and the Jackals?}
{213}{}{After what I survived it feels like a ridiculous nightmare. What was the command center thinking?! But my duty is to follow orders, not discuss them.}
{214}{}{I see.}
