{100}{}{Here is a ranger.}
{101}{}{You see a ranger in desert clothes. He shows you a greeting sign.}
{102}{}{Yes, I'll need it.}

#The first dialog
{200}{}{Hey, traveler, slow down! You don't often meet people in these parts. Can you tell me what you're doing here?}
{1200}{}{Hey, traveler, slow down! You don't often meet people in these parts. Can you tell me what you're doing here?}
{201}{}{I'm running an errand for Captain Helford.}
{202}{}{This is not surprising. The captain has long said that he does not have enough people. Then be careful, this place is not safe.}
{203}{}{The Ranger cartographer asked me to take measurements.}
{204}{}{It was high time to do it. But now it's too dangerous here to do peaceful cartography.}
{205}{}{I'm here in search of ancient artifacts.}
{206}{}{A relic finder, right? The road has brought you far in search of profit. But this is not the best place to look, believe me. Everything of value has long been lost, and it has become unsafe to be here.}
{207}{}{It's none of your business.}
{208}{}{Okay. Let's say. But keep in mind that these ruins are too dangerous. If you get into trouble, don't ask me or the other rangers for help.}
{209}{}{Why is this place dangerous?}
{210}{}{Recently, the radioactive background has increased here. The locals have gone mad and are now attacking anyone they meet. Be careful. I warned you, and then do as you want.}
{211}{}{Thanks for the warning.}
{212}{}{You're just trying to scare me. Better give way.}
{213}{}{I'll figure it out. Happily.}

#Repeat dialog
{220}{}{Yes?}
{221}{}{Bye.}
{222}{}{Let's go back a bit.}
{223}{}{It looks like it was the last one. God rest their souls.}

{230}{}{Are there any residents left here?}
{231}{}{I'm here at the request of Commander Helford. Where is the refugee camp located?}
{232}{}{You can't call the locals people anymore. They are distraught, do not understand speech and attack anyone they meet. Their camp is located in a trailer park opposite a gas station. Go down the street and then turn left.}
{233}{}{Who are they?}
{234}{}{Ordinary refugees from the east. They came here hoping to start a new life, but they found only suffering. If you meet them, it's better to shoot them right away so that they don't suffer and don't create problems for others.}
{235}{}{Why are they mad?}
{236}{}{I do not know, but I think it's because of radiation.}
{237}{}{You can't call the locals people anymore. They are distraught, do not understand speech and attack anyone they meet. Their camp is in this trailer park.}

{240}{}{Why is it radioactive here?}
{241}{}{I'd like to know, too. After the Great War, there was a high radiation background due to winds from California. But over time, the radiation level returned to normal. Surely the locals did their best. Maybe they found something they shouldn't have found.}

{250}{}{Who are you?}
{251}{}{I'm a ranger. My task is to set up radiation warnings and, if possible, shoot all the Distraught. After that I will return to my service in the east.}
{252}{}{Are you alone here?}
{253}{}{Yes. Many rangers were sent to the east, and there were rare patrols in this direction. However, it has always been sparsely populated here.}
{254}{}{I need an escort. Will you come with me?}
{255}{}{It's too dangerous. The two of us attract more attention, and my skills are more useful in the wastelands than in the city limits.}
{256}{}{I won't get out alive without your protection.}
{257}{}{I'm a ranger too. Together it will be easier for us to get rid of the Distraught.}
{258}{}{I don't protect people like you.}
{259}{}{You speak as if you see me as a fugitive criminal.}
{260}{}{Just leave these ruins if you don't have the strength to fight.}
{261}{}{Not before I get all the necessary answers from you.}
{262}{}{That's exactly what I'll do. Bye.}
{263}{}{(incredulous) Okay But don't forget about radiation.}
{264}{}{Go ahead!}
{265}{}{Come on.}