{100}{}{You see Ranger Agatha.}
{101}{}{You see a veteran Ranger in combat armor.}
{102}{}{The Ranger pays you no attention. It would be wise to wait a bit.}
{103}{}{I don't want to see you.}
{104}{}{Agatha is ignoring you.}

#Кат-сцена спора с генералом:
{110}{}{This is madness!}
{111}{}{You do know how many of our warriors fell to the claws of the Jackals?!}
{112}{}{That scum must be completely destoyed!}
{113}{}{All of them to the last dog!}
{114}{}{And you... you form an alliance with them!}
{115}{}{That's disgusting!}
{116}{}{You can reprimand me as much as you like for breaking the chain of command...}
{117}{}{But other Rangers agree with me that this is wrong!}
{118}{}{No alliance will change those savages...}
{119}{}{...and especially return the lives of the fallen Rangers.}
{120}{}{I won't accept this!}

{200}{}{Hey! This is all your fault! The Jackals have been terrorizing territories in the north for years. Many excellent Rangers died because of their tricks. I am not going to tolerate this blasphemous alliance with savages. Now begone from my sight!}
{201}{}{Learn to forgive. Maybe you'll change your mind when you'll see the real possibilities of this alliance.}
{202}{}{Your warmongering brain is too smooth to see the potential in a ceasefire. Remain ignorant, lady.}
