{100}{}{You see a radio operator.}
{101}{}{You see a woman with a stiff look.}

{200}{}{Hi.}
{201}{}{Bye.}

{210}{}{What's the matter?}
{211}{}{Bye.}

{220}{}{Tell me about yourself.}
{221}{}{Liaison officer Jain.}
{222}{}{How did you become a Ranger?}
{223}{}{I became one.}
{224}{}{Uhh, this cleared a lot up.}
{225}{}{Any more stupid questions?}
{226}{}{Yes.}
{227}{}{No.}
{228}{}{}
{229}{}{Let's change the subject.}

{230}{}{What is this place?}
{231}{}{It's a radio station. Raid-io-station. Don't mix it up with radiation... Dammit, looks like it'll take a while to explain it to you. In short, we use this equipment to communicate with our patrols from a distance.}
{232}{}{It's a wonder how all this technology still works.}
{233}{}{Yes. It works. And it is kept so only with external connections. We get spare parts from trade caravans, and the energy from the local dam.}
{234}{}{Few in the wastes have Old World technology.}
{235}{}{Bingo. Technologies are a necessity, not a luxury. Many even fear places such as these. But in our case, knowledge about this technology has been passed down from previous generations and was recorded on holotapes. It is also a relic to us, in a way.}
{236}{}{Where's all the personnel? There's almost noone here.}
{237}{}{I have enough chatter on the radio. And I'm especially not going to tolerate outsiders here.}
{238}{}{Don't you want to go somewhere and relax?}
{239}{}{Like? I'm not against shooting some coyotes, but I have no business with your society.}
{240}{}{Angry at people?}
{241}{}{Maybe so. There only seem to be idiots around. When another cadet creates problems or another sergeant goes against commander's orders, you unwillingly get dissapointed in people.}
{242}{}{What's that field with crosses near the station?}
{243}{}{A cemetary. Rangers and their loved ones are buried there. I hope you're not going to defile the graves. Otherwise, that would be the last mistake you would make in your short life.}
{244}{}{Can I ask another question about that... rad-station?}

{250}{}{I need the radio codes.}
{251}{}{That is official information not meant to be known by simple peasants.}
{252}{}{I'm a new recruit.}
{253}{}{Fine, forget it.}
{254}{}{Then push your codes deeper up you-know-where.}
{255}{}{Sorry then. Here are the codes and the cipher for the main communication frequencies. Don't even think of showing it to anyone other than other Rangers.}
{256}{}{Thank you, officer.}
{257}{}{I know that already.}

{260}{}{The dam is destroyed. Why are you still here?}
{261}{}{In these hard times my job is even more important. The leadership is searching for a new place to call a base, and without remote communication they'll be blind in their search.}
{262}{}{[Continue]}
{263}{}{In any case, this won't last long, since the energy in the standby generators is limited. When the energy ends or they break this radio station will become useless. Still, there's a good view of the valley from the top.}
{264}{}{Understood.}

{270}{}{They say that spy hiding near the farmers was caught thanks to you. Good job.}
{271}{}{Happy to help.}
{1271}{}{Happy to help.}
{272}{}{Oh, it's nothing.}
{273}{}{So it was thanks to you that Jason got out of the Jackals' paws? Great. We were thinking that we lost everyone from that patrol.}
{274}{}{Happy to help.}
{1274}{}{Happy to help.}
{275}{}{You're welcome.}

#—южетный квест
{278}{}{Really?}
{279}{}{The thing is that half of the signal amplifiers went offline a long time ago. They need to be repaired or replaced. Then the connection will be gooe enough to control territory up to Phoenix... Or at least up to San-Brahmin.}
{280}{}{I was sent here by commander Helford.}
{281}{}{Great, just great. The station nees repairs and Helford sends peasants to do it! Do you even begin to imagine how a radio station works?}
{282}{}{I'll figure it out. What do I need to do?}
{283}{}{Right now, our guys have a lot of work to do in the eastern and south-eastern fronts. But the radio communications don't reach some of the outposts. Even though it could.}
{284}{}{Where is the broken equipment?}
{285}{}{Head down to the backroom under the antenna. I'm afraid tin cans and forks won't be enough for repairs. Maybe you'll find useful components in Garage-City, from the Scavengers, but they don't like the Rangers. Can you help us with this problem?}
{286}{}{I'll go see what's going on there...}
{287}{}{Wait just a minute. You are going to Garage to get components, right? Then I have another request. We lost a patrol in that region. Try to learn what happened to them. This station isn't strong enough to reach that region, but closeby, radios can detect signals from one another. If you manage to do it the Rangers will be very grateful.}
{288}{}{I'll definitely find that patrol.}
{289}{}{I can't promise you anything.}
{290}{}{The radio transmitter is restored.}
{291}{}{The source of the "echo" is destroyed. It was a spy repeater.}
{292}{}{Remind me what I need to do.}
{293}{}{So it *is* too complicated for your mind, yes? Find the source that is creating "echoes" in our broadcasts. To do that, head to the wastes east from our base. You'll need to track the signal with a radio to pinpoint the location of the source.}
{294}{}{Great. Let's see what this ended up in...}
{295}{}{[Continue]}
{296}{}{Amazing! Now we will be able to increase our control over the territories near... Wait. Are you hearing this?}
{297}{}{An echo? Something is repeating your signal?}
{298}{}{Looks like it... The signal is very weak, it's from the east. We couldn't detect this before. It might be a mistake in the new equipment, but... Listen, we have to know what it is for sure. We musn't ignore this noise.}
{299}{}{[Continue]}
{300}{}{Head to the signal bearing and find out what is causing the echo. I'll give you a radio to search for it.}
{301}{}{Eh, and here I thought this assignment was complete...}

{302}{}{This is unexpected! I thought we were the only ones with the technologies for such powerful  radio broadcasts. Report to captain Helford immediately to tell him about the results of this operation.}
{303}{}{[Continue]}
{304}{}{You have something in you... Tell commander Helford about the results of the operation.}
{305}{}{Aye-aye!}
