{100}{}{You see a Ranger.}
{101}{}{You see a Ranger in desert clothes. He's greeting you with some kind of gesture.}
{102}{}{Yeah, this will be useful to me.}

#Первый диалог
{200}{}{Hey, wanderer, stop! Not too common that you see people in these lands. Maybe you could tell me what it is you're doing here?}
{1200}{}{Hey, wanderer, stop! Not too common that you see people in these lands. Maybe you could tell me what it is you're doing here?}
{201}{}{I'm doing an assigment given to me by captain Helford.}
{202}{}{No wonder. The captain's been saying he lacks manpower for a long time. Then be vigilant, this place is not safe.}
{203}{}{The Ranger cartograph asked me to make measurements.}
{204}{}{That should have been done a long time ago already. But now it's too dangerous here to conduct peaceful cartography.}
{205}{}{I'm here in search of ancient artifacts.}
{206}{}{Relic hunter, yeah? You wandered far in search of profit. But this is not the best place to search, believe me. Everything valuable has been lost a long time ago and staying here has become unsafe.}
{207}{}{That's none of your business.}
{208}{}{Fine. Let's suppose that is the case. But keep in mind that those ruins are too dangerous. If you end up in a bad situation don't ask me or other Rangers for help.}
{209}{}{Why's this place so dangerous anyways?}
{210}{}{Recently the radiation level has increased. The locals went mad and are now attacking anyone who walks here. Be vigilant. I warned you, now do whatever you want.}
{211}{}{Thanks for the warning.}
{212}{}{You're just trying to scare me away, are you not. You better make way.}
{213}{}{I'll deal with it. So long.}

#Повторный диалог
{220}{}{Yeah?}
{221}{}{Bye.}
{222}{}{Let's go a little back.}
{223}{}{Looks like this was the last one. Lord rest their souls.}

{230}{}{Are there any locals left in here?}
{231}{}{I'm here on behalf of commander Helford. Where is the refugee camp located?}
{232}{}{You can't really call the locals people. They went mad, they don't understand speech and attack any passerby. Their camp is located in the trailer park near the gas station. Head down the street and then turn left.}
{233}{}{Who are they?}
{234}{}{Regular refugees from the east. Came here in hope of starting a new life but got only suffering. If you find them just shoot them, so that they don't suffer and cause problems to others.}
{235}{}{Why have they become mad?}
{236}{}{I do not know but I think it is because of the radiation.}
{237}{}{You can't really call the locals people. They went mad, they don't understand speech and attack any passerby. Their camp is located in this trailer park.}

{240}{}{Why is it still radioactive here?}
{241}{}{I'd like to know as well. After the Great War there was a high radiation level here due to winds from California. But with time it went down to normal. Probably the work of the locals. Perhaps they found something that should not have been found.}

{250}{}{Who are you?}
{251}{}{I'm a Ranger. My mission is to set up warning signs about radiation and if possible, shoot all Distraught. After that I will return to my duty in the east.}
{252}{}{You're alone here?}
{253}{}{Yes. Many Rangers were sent to the east, and only rare patrols were left in this direction. Though to be honest, people were always hard to come by in this place.}
{254}{}{I need assistance. Will you come with me?}
{255}{}{It's too dangerous. Together we'll attract more attention and my skills are more useful in the desert than in urban environments anyways.}
{256}{}{Without your help I won't get outta here alive.}
{257}{}{I'm a Ranger too. Together we will get rid of the Distraught more easily.}
{258}{}{I don't protect people like you.}
{259}{}{You say that like I am some kind of fugitive.}
{260}{}{Just leave these ruins if you don't have the stength to fight.}
{261}{}{Not before I get all the answers I need out of you.}
{262}{}{Will do exactly that. Bye.}
{263}{}{(not trusting) Okay. But don't forget about the radiation.}
{264}{}{Let's go!}
{265}{}{Let's go.}
