{100}{}{Here is a radio operator.}
{101}{}{You see a woman with a prim look.}

{200}{}{Hi.}
{201}{}{Bye.}

{210}{}{What's the matter?}
{211}{}{Bye.}

{220}{}{Tell me about yourself.}
{221}{}{Jane's communications officer.}
{222}{}{How did you become a ranger?}
{223}{}{So it happened.}
{224}{}{Uh, a lot has become clear.}
{225}{}{Any more stupid questions?}
{226}{}{Yes.}
{227}{}{No.}
{228}{}{}
{229}{}{Let's change the subject.}

{230}{}{What is this place?}
{231}{}{This is a radio station. Ra-di-o-station. Don't confuse it with radiation... Damn, it looks like you're going to have to explain this for a long time. In short, we use this equipment to communicate remotely with our patrols.}
{232}{}{It's amazing that all this technology still works.}
{233}{}{Yes. Works. And it keeps "afloat" only thanks to external relations. We get spare parts from trade caravans, and energy from the local dam.}
{234}{}{In the wastelands, few have the technology of the Old World.}
{235}{}{That's for sure. Technology is a necessity, not a luxury. Many are even afraid of such places. But in our case, knowledge about this technology has been passed down for generations and recorded on holodisks. For us, this is also a relic in some way.}
{236}{}{And where are all the staff? There's almost no one here.}
{237}{}{I have enough chatter on the radio. And even more so, I'm not going to tolerate outsiders here.}
{238}{}{Do you want to go somewhere to relax?}
{239}{}{For example? I don't mind shooting coyotes, but I don't care about your company.}
{240}{}{You seem to be mad at people?}
{241}{}{Maybe so. There are only fools around. When another cadet causes problems or another sergeant goes against the commander, you involuntarily get disappointed in people.}
{242}{}{What is this field with crosses near the station?}
{243}{}{Cemetery. Rangers and their loved ones are buried there. I hope you're not going to desecrate the graves, otherwise it will be the last mistake in your short life.}
{244}{}{Can I ask another question about this one... a radio station?}

{250}{}{I need radio codes.}
{251}{}{This is official information, ordinary peasants are not supposed to know.}
{252}{}{I'm a rookie.}
{253}{}{Okay, forget it.}
{254}{}{Then shove your codes deeper.}
{255}{}{Then I'm sorry. Here are the codes and the cipher of the main negotiation frequencies. Don't you dare show it to anyone except other rangers.}
{256}{}{Thank you, Officer.}
{257}{}{I know without you.}

{260}{}{The dam is destroyed. Why are you still here?}
{261}{}{In this difficult time, my work is especially important. The management is looking for a new place to base, and without remote communication they will be blind in their search.}
{262}{}{[Next]}
{263}{}{In any case, it will not last long, because the resource of backup generators is limited. When they run out or break down, the radio station will become useless. However, from the top there is a good view of the valley.}
{264}{}{I see.}

{270}{}{They say it was thanks to you that the spy who was hiding with the farmers was discovered? Good job.}
{271}{}{Glad to try.}
{1271}{}{Glad to try.}
{272}{}{It's nothing.}
{273}{}{So it was thanks to you that Jason got out of the clutches of the Jackals? Well done. We thought we'd lost everyone from that patrol.}
{274}{}{Glad to try.}
{1274}{}{Glad to try.}
{275}{}{You're welcome.}

#Story quest
{278}{}{Really?}
{279}{}{The fact is that half of the signal amplifiers have long been out of order. We need to fix them or find a replacement for them. Then the connection will be enough to control the territory up to Phoenix... Well, or at least to San Brahmin.}
{280}{}{Commander Helford sent me.}
{281}{}{Great. The station is in need of repair, and Helford is sending peasants for this! Do you have any idea how a radio station works?}
{282}{}{I'll figure it out. What needs to be done?}
{283}{}{Now our guys have a lot of work on the eastern and southeastern front. But radio communication does not reach some outposts. Although I could.}
{284}{}{Where is the broken equipment located?}
{285}{}{Go down to the utility room under the antenna. I'm afraid there won't be enough cans and forks to fix it. Perhaps the scavengers will have useful parts in Garage City, but they don't like rangers. Can you help us with this problem?}
{286}{}{I'm going to see what it is...}
{287}{}{Wait a minute. You're probably going to the Garage for the parts, right? Then there is one more request. We lost patrolmen in that area. Try to find out what happened to them. Our communication does not reach far, but near the radios will be able to detect each other's signals. If you manage, the Rangers will be grateful to you.}
{288}{}{I will definitely find them.}
{289}{}{I can't promise anything.}
{290}{}{The radio transmitter has been restored.}
{291}{}{The echo source has been destroyed. It was a spy relay.}
{292}{}{Remind me what I needed to do.}
{293}{}{Still, it's difficult for your mind, isn't it? Find the source that creates the "echo" in our broadcasts. To do this, go to the wasteland to the east of our base. You will need to monitor the signal on the walkie-talkie to determine the location of the source.}
{294}{}{Great. Let's see what came of it...}
{295}{}{[Next]}
{296}{}{Amazing! Now we will be able to expand control over the territory... Wait a minute. Do you hear that?}
{297}{}{Echo? Is something duplicating your signal?}
{298}{}{It looks like it... The signal is very low, coming in an easterly direction. We couldn't detect it before. It may be a mistake of the new equipment, but... look, we need to know exactly what it is. This hindrance should not be ignored.}
{299}{}{[Next]}
{300}{}{Go to the signal bearing and find out what causes the radio echo. I'll give you a walkie-talkie to find him.}
{301}{}{Eh, and it already seemed to me that the task was completed ...}

{302}{}{What a surprise! It seemed to me that only we possess the technology of such powerful radio broadcasts. Tell Captain Helford about the results of the operation immediately.}
{303}{}{[Next]}
{304}{}{And you have the makings. Tell Commander Helford about the results of the operation.}
{305}{}{Yes!}