#---------------------------------------------------------
#  Translated by gb1983, Georg; revised by garwert.
#---------------------------------------------------------
{100}{}{You see a cartographer.}
{101}{}{You see a ranger in loose clothing with a large eyepiece on his forehead. It seems like constant work in the dark has worsened his vision.}

{200}{}{[You see a frail-looking Ranger; his uniform hangs on him like on a hanger, an eyepiece with interchangeable lenses dangles on his head; when he sees you, he adjusts the lenses and frowns, peering into your face] Huh? Who let you in? Only rangers can come in here.}
{201}{}{Don't worry, I was allowed to.}

{210}{}{Hello.}
{211}{}{Bye.}
{212}{}{Let's go back a little.}
{213}{}{Uh, hi?}

#Questions
{220}{}{What is it you do here?}
{221}{}{My job is to create new maps of the wastes. An extremely painstaking and laborious task, if you ask me.}
{222}{}{What's wrong with the old maps?}
{223}{}{They become outdated. Of course, the terrain has not changed much since the Great War, but some lakes and rivers have dried up, radioactive areas have appeared, and new settlements have formed. Nowadays, only Rangers and caravan drivers know the geography of the surrounding areas in detail. But even our patrols often need precise coordinates. And no one makes new maps... No one but me.}
{224}{}{What do you mark on these maps?}
{225}{}{Everything that might be useful to our people on the way: settlements, farms, outposts, radioactive areas, oases. Almost any kind of cartographic information can prove useful to the command center.}
{226}{}{Can I examine your maps?}
{227}{}{Only with the permission of a superior commanding officer.}
{228}{}{Yes, of course. We have no secrets among our own.}
{229}{}{Do you have other duties besides mapping?}
{230}{}{They give me anything that requires reading and writing.}
{231}{}{Is that why you keep scowling and wincing like that?}
{232}{}{Are you kidding me? For years I have been crawling over maps and texts in darkness. That's why without my eyepiece I can hardly see anything... Hell, you know, if they make me leave into the Wastes, it will be the last day of my life.}
{233}{}{Why are you still here?}
{234}{}{Although the command center has been destroyed, it does not excuse me from my duties.}

#Quartz
{250}{}{Commander Helford told me to head for Quartz.}
{251}{}{Really? The commander probably doesn't have enough men... I have long asked him to conduct geodetic measurements there.}
{252}{}{Well, forget it.}
{253}{}{What can you tell me about the place?}
{254}{}{Some old ruins of an ancient town. (shows on the map) For a long time after the Great War, they remained radioactive. Combined with the scorching desert climate, this place scared away any settlers or travelers. Only recently have the radiation levels decreased enough to be deemed acceptable. That's why we didn't pay much attention to those ruins until recently.}
{255}{}{I need to know more about Quartz.}
{256}{}{That should be enough.}
{257}{}{Why was Quartz radioactive?}
{258}{}{The western storms of California brought that radiation there. Those lands were badly damaged by nuclear explosions during the Great War.}
{259}{}{What dangers may await me there?}
{260}{}{Residual radioactive background, radscorpions, collapses of dilapidated buildings... In general, Quartz has been a fairly quiet place so far.}
{261}{}{What measurements do you need to make?}
{262}{}{I'm afraid this is too much work for one person: radioactive background, condition of the surroundings, vegetation ...}
{263}{}{My Pip-Boy has a built-in cartographic sensor.}
{264}{}{Really? Wow, it seems you were made for this job. I'll show you the locations where the readings need to be taken. Your task is simple: go there and write down the data.}
{265}{}{Noted. I'll be back when I finish the job.}
{266}{}{I'm not going to waste my time on any maps. But I do need to know more about Quartz.}
{267}{}{Perfect! You'll be doing a great service to all Rangers.}
{268}{}{Okay, but I still have questions about Quartz.}
{269}{}{See you later.}
{270}{}{Here are the measurements from Quartz that you needed.}
{271}{}{Unbelievable! There's more data here than I'd hoped! That thing on your arm just works wonders. You can use my maps as a reward. Thanks.}
{272}{}{You're welcome, happy to help the Rangers.}
{1272}{}{You're welcome, happy to help the Rangers.}
{273}{}{It would be better if you gave me some ammo, but improving my reputation isn't bad either.}
{274}{}{Why do you need maps of that hellhole?}
{275}{}{We don't need them right now, but we need to be prepared for everything. There could be a nest of mutants or a lair of bandits hiding in those ruins. After all, Quartz is the gateway to California. They may still be sealed by the desert, but it's only a matter of time.}
