{100}{}{You see a cartographer.}
{101}{}{You see a ranger in free clothes with a large eyepiece on his forehead. It seems that the constant work at dusk has worsened his eyesight.}

{200}{}{(In front of you is a frail-looking ranger; his uniform hangs on him like on a hanger, and an eyepiece with interchangeable lenses dangles on his head; when he sees you, he adjusts the lenses and winces, peering into your face) And? Who let you in? Only rangers can come here.}
{201}{}{Don't worry, I'm allowed.}

{210}{}{Hello.}
{211}{}{Bye.}
{212}{}{Let's go back a bit.}
{213}{}{Hey, hello?}

#Questions
{220}{}{What are you doing here?}
{221}{}{My job is to make new maps of the Wastelands. It's painstaking and very time-consuming.}
{222}{}{What's wrong with old maps?}
{223}{}{They are becoming obsolete. Of course, the relief has hardly changed since the Great War, but some lakes and rivers have dried up, radioactive areas have appeared and new settlements have formed. Nowadays, only rangers and caravan drivers know the geography of the surrounding area in detail. But even our patrols sometimes need precise coordinates. And no one makes new maps... No one but me.}
{224}{}{What are you pointing at on these cards?}
{225}{}{Everything that will be useful to our brother on the way: settlements, farms, outposts, radioactive areas, oases. And for the command center, any cartographic information can be useful at all.}
{226}{}{Can I study your maps?}
{227}{}{Only with the permission of a superior commander.}
{228}{}{Yes, of course. We have no secrets among our own.}
{229}{}{Do you have other duties besides cartography?}
{230}{}{They dump on me any job where you need to read and write.}
{231}{}{Is that why you're always making those grimaces?}
{232}{}{Are you kidding? I've been dribbling over maps and texts in the semi-darkness for years. Therefore, without an eyepiece, I can hardly see anything... Damn, you know, if I'm forced to leave in the wastelands, it will be my last day in my life.}
{233}{}{Why are you still here?}
{234}{}{Although the command center has been destroyed, this does not cancel my duties.}

#Quartz
{250}{}{Commander Helford sent me to Quartz.}
{251}{}{Really? Probably, the commander does not have enough people... I have long asked him to conduct geodetic measurements there.}
{252}{}{Come on, forget it.}
{253}{}{What can you tell me about this place?}
{254}{}{These are the old ruins of an ancient town. (shows on the map) For a long time after the Great War, they remained radioactive. Combined with the hot desert climate, this place scared off any settlers and travelers. Only recently has the radiation level dropped to an acceptable level. Therefore, we did not attach importance to these ruins until recently.}
{255}{}{I need to know more about Quartz.}
{256}{}{You don't have to continue.}
{257}{}{Why was Quartz radioactive?}
{258}{}{Radiation was brought there by storms from the west, from California. Those lands were pretty battered by nuclear explosions during the Great War.}
{259}{}{What dangers can I face there?}
{260}{}{Residual radioactive background, radscorpions, collapses of dilapidated buildings... Overall Quartz has been a pretty quiet place so far.}
{261}{}{What measurements do you need to take?}
{262}{}{I'm afraid it's too much work for one person: relief, radioactive background, condition of neighborhoods, vegetation...}
{263}{}{My Pip-Boy has a built-in map sensor.}
{264}{}{Really? Wow, then you're a real godsend for my work. I'll show you the positions for observations. Your task is just to go there and record the data.}
{265}{}{Noted. I'll be back when I'm done.}
{266}{}{I'm not going to waste time on any maps. But I need to know more about Quartz.}
{267}{}{Great! You will do this good service to all the Rangers.}
{268}{}{OK, but I still have questions about Quartz.}
{269}{}{See you later.}
{270}{}{Here are the Quartz measurements you needed.}
{271}{}{Unbelievable! There's more data here than I was hoping for! That thing on your arm just works wonders. You can use my cards as a reward. Thank you.}
{272}{}{Please, I was glad to help the Rangers.}
{1272}{}{Please, I was happy to help the Rangers.}
{273}{}{It would be better to give cartridges, but it's not bad to raise your reputation either.}
{274}{}{Why do you need the cards of this hole?}
{275}{}{There's no need for them right now, but we have to be ready for anything. Mutant nests or bandit camps may be hiding in old ruins. After all, Quartz is the "gateway" to California. They may be sealed by the desert for now, but it's only a matter of time.}