#---------------------------------------------------------
#  Translated by Georg; revised by garwert.
#---------------------------------------------------------
{100}{}{You see a handyman.}
{101}{}{You see an average inhabitant of the wasteland.}

#First dialogue
{200}{}{(a young man in dirty clothes is in front of you; he wearily looks up to you, clearly displeased) What do you want?}
{201}{}{You're not one of the rangers?}
{202}{}{Of course not. I don't give a shit about those rangers. But they defend our community. As compensation, they force me to do work.}
{203}{}{Okay. I won't bother you anymore.}

#Second dialogue
{210}{}{You again?}
{211}{}{Bye.}
{212}{}{Can you refuse to carry out your work?}
{213}{}{Probably not. If the rangers become angry, they'll take all our supplies and stop defending us from bandits and mutants. That's why we have to do cater to every single whim of theirs. And that list is quite long.}
{214}{}{Tell me about your community.}
{215}{}{We live near the Aqueduct on the shore of Colorado. Trying to survive on fish and small game. Don't know what else to tell you.}
{216}{}{What do you think about the rangers?}
{217}{}{When needed, they will become our only hope for salvation. But in between, they're just mooching off of our commune, taking a part of our catch and forcing us to work for their own benefit.}
{218}{}{Do you know of a way to get inside the base?}
{219}{}{I don't know. They're not exactly big on hosting tours inside of it. You need to help the rangers a lot or have a *really* good reason.}
