{100}{}{You see a handyman.}
{101}{}{You see an ordinary inhabitant from the wasteland.}

#The first dialog
{200}{}{ (in front of you is a young man in dirty clothes; he wearily raises a dissatisfied look at you) What do you want?}
{201}{}{Are you not a Ranger?}
{202}{}{No, of course not. I don't give a shit about these rangers. But they give protection to our community. They make me work as a payment.}
{203}{}{I see. Well, I won't distract you.}

#Repeat dialog
{210}{}{You again?}
{211}{}{Bye.}
{212}{}{Can you refuse to perform your services?}
{213}{}{It's unlikely. If the rangers get angry, they will take all our supplies from us and stop protecting us from bandits and mutants. Therefore, we have to fulfill all their whims. And the list of works is quite long.}
{214}{}{Tell us about your community.}
{215}{}{We live near an Aqueduct on the Colorado shore. We survive at the expense of fish and small game. I don't know what else to tell you.}
{216}{}{What do you think about the Rangers?}
{217}{}{When necessary, they will become the only hope for salvation. But the rest of the time they just parasitize our community, taking the catch and forcing them to work for their benefit.}
{218}{}{Do you know a way to get into the base?}
{219}{}{I don't know. Excursions for tourists are not taken there. You need to do the Rangers a good service or have a really good reason.}