{100}{}{This is Ranger Stark.}
{101}{}{You see an ordinary Ranger.}
{102}{}{Thanks, Doc. I thought I was going to be lame for the rest of my life.}

#The first dialog
{200}{}{(a bored ranger seems to come to life when a stranger appears in the dining room; he cordially invites you to a table) Hello, stranger! Haven't seen you before. Where are you from?}
{1200}{}{(a bored ranger seems to come to life when a stranger appears in the dining room; he cordially invites you to a table) Hello, stranger! Haven't seen you before. Where are you from?}
{201}{}{From a village in the north. We call it Villa.}
{202}{}{Well, I've been patrolling in other directions. But I heard something about the Villa. Is it about you who was told that you grow crops in the middle of a barren desert? Surprisingly. I thought it was the usual bullshit you hear in the dining room.}
{203}{}{And you...}
{204}{}{None of your business.}
{205}{}{Hey, I wasn't rude to you, was I? But I understand your distrust. If you don't want to, don't tell me.}
{206}{}{And who are you?}
{207}{}{I'm Stark, a private Ranger, if that means anything to you.}
{208}{}{Hey, Stark. Do you have a minute to talk?}
{209}{}{Hey, Stark. And so far.}

#Repeat dialog
{210}{}{I'm all ears.}
{211}{}{Bye.}
{212}{}{Another question.}

#Questions
{220}{}{Why do you live right on the dam?}
{221}{}{Why? This is an excellent fortification against enemies and bad weather. No one will even think of storming here or trying to spy.}
{222}{}{Is this an unsafe place?}
{223}{}{This dam will stand here for another couple of centuries. At least that's what Old Rufus says. And what can happen here? It's just a piece of concrete in the middle of the mountains.}
{224}{}{Who is this Old Man Rufus?}
{225}{}{The caretaker of the Dam. He has been in this position for more than a dozen years. Although many believe that he gets his ration for nothing. He seems to be at the power plant right now.}
{226}{}{So this is where all the Arizona Rangers live?}
{227}{}{Of course not. It's just a barracks for temporary accommodation. You can get a bed here only for a certain period or for some reason. And the rest of the time, look for a place in the sun, as a normal ranger should.}

{230}{}{I'm just wondering how to become a cadet?}
{231}{}{Well, there are different ways. Usually we need a recommendation from someone with whom we have good relations - traders, leaders of friendly settlements, other rangers. And if there are no recommendations, then you need to show yourself in action.}
{232}{}{How long does the training last?}
{233}{}{At least five years, but it all depends on the cadet. The decision to raise must be earned by real merits in the field.}
{234}{}{Are you a cadet too?}
{235}{}{I? Nope. But I have to help the greenery grow up. It's our way - you can't be useful in the field, help at the base.}
{236}{}{What prevents you from participating in operations?}
{237}{}{And you, it turns out, are not capable of more, right?}
{238}{}{ (raises the bandaged leg) Damn wolves. They attacked me while on patrol on the Colorado River. I lost my vigilance - and here is my reckoning.}
{239}{}{Maybe I can cure her?}
{240}{}{If you pay, I'll cure her.}
{241}{}{Oh, that's definitely a problem. Can we talk about something more positive?}
{242}{}{Seriously? I would be grateful. But do you really know what to do?}
{243}{}{Let me see...}
{244}{}{Use medical skills or medications to treat the injury.}

{250}{}{Probably, such an experienced ranger knows a lot of interesting stories.}
{251}{}{I never miss an opportunity to ask travelers about what I saw. However, usually many of them lie in their stories.}

{270}{}{You mentioned wolves. What other creatures are found along the Colorado?}
{271}{}{Oh, this is not a desert, there are a lot of different animals here.}
{272}{}{For example?}
{273}{}{Oh, yeah, I see.}
{274}{}{Horned lizards the size of a dog can be found in the thickets. At first glance, not such a strong opponent, but her spikes all over her body do not allow her to get close for a close-range attack. Besides, it's a damn smart thing with an excellent disguise.}
{275}{}{How interesting! Tell me more?}
{276}{}{There's a lot of such game, nothing special.}
{277}{}{Do you want a scarier one? The caves are inhabited by bulldog bats - real demons. They are waiting for the victim at the entrance and quickly fly out at her, not letting her come to her senses. One such creature can lift a man into the air and drag him back into the cave. He can't go back.}
{278}{}{Seriously? My hamstrings are already shaking.}
{279}{}{Somehow it's hard to believe. And these are all local inhabitants?}
{280}{}{Between the Colorado rocks, there are scolopendras up to two yards long. From their bite, death occurs within one second. Their carapace cannot be pierced even with a knife, and their jaws are so strong that they can cut a person in half.}
{281}{}{Oh, Mom! Don't tell me there's something scarier!}
{282}{}{Someone has a poor fantasy on history. Don't you find it?}
{283}{}{There are also rumors about pitiful hypnotic butterflies and armadillos that use old cars as a shell. But I myself have only met wolves, lizards and rodents of all stripes.}
{284}{}{Thanks for the story. It was very... informative.}
{285}{}{Don't lose your vigilance.}
{286}{}{Let's chat a little more.}
{287}{}{Then see you later, I have to go.}
{288}{}{Your chatter makes my head hurt. Are you trying to intimidate all strangers?}
{289}{}{Well... I've heard it all from other people. Don't quibble. But don't doubt that there are plenty of hostile creatures around. Stay vigilant.}
{290}{}{Tell me about the creatures of the Colorado River.}

#Promotion party
{310}{}{Hey, it's a new *star* in person!}
{311}{}{Yes, it wasn't easy to get a badge. But how do you know?}
{312}{}{Rumors spread quickly at the base. But you know what? You don't have to wait for a gift from me. The others have been earning a star for years, and you just come and take it!}
{313}{}{It looks like you don't like me from the first meeting. But I don't care.}
{314}{}{I hope you will change your attitude towards me someday.}
{315}{}{Well, well.}
{316}{}{You're not busy, are you? Got a minute?}
{317}{}{I think I'll go.}
{318}{}{Enjoy. You're a hero today.}
{1318}{}{Enjoy. You're a star today.}

{320}{}{Are you kidding me?}
{321}{}{How did you guess? Maybe it's because they don't throw fireworks in your honor? The rest of us have been earning a star for years, and you just come and take it! So don't expect a gift from me.}
{322}{}{Rumors spread quickly at the base. I'm happy for you. Few manage to get a badge at the very beginning of the service. Or rather, no one succeeds. Let me supply you with personal supplies in honor of such a holiday. Well done!}
{323}{}{Thank you, a party at the top of the dam is what I've always wanted.}
{324}{}{The badge is not a reason for fun. But I think I'll take the fruit.}

{330}{}{Listen, is there any truth in your stories?}
{331}{}{Well... there is one story that is definitely not fiction. Interesting?}
{332}{}{I'm listening.}
{333}{}{Another time.}
{334}{}{A truly gigantic radscorpion lives in the desert, larger than any known radscorpion. They say this creature devoured several groups of travelers. If you find and kill her, you will do the world a great service.}
{335}{}{You know, I don't want to listen to this.}
{336}{}{Aren't all radscorpions gigantic?}
{337}{}{Yes, but this one will outshine everyone with its size!}
{338}{}{Why don't the Rangers hunt him down and attack him all at once?}
{339}{}{This creature is hiding in a barren desert, where even an experienced ranger is hard to hold out for a few days. She crawls out of the desert while hunting and then goes back. To meet such a monster, you will have to become its victim in some sense.}
{340}{}{But why do you think all this is true and not fiction?}
{341}{}{Because I saw everything with my own eyes. And I'm not the only one. One day we were lucky enough to track down this game in the desert between Quartz and San Brahmin. There was a serious massacre, we barely got out of there, and since then we decided that it was better to avoid this scorpion.}
{342}{}{Clearly, I will try to hunt down and kill this creature.}
{343}{}{Seriously? Commendable zeal. But if you become a monster's lunch, then blame yourself.}
{344}{}{Happily. I'll bring you some souvenir.}
{345}{}{Oh, it looks like this monster needs to be avoided. Thanks for the warning.}
{346}{}{Exactly.}
{347}{}{Happily.}

{350}{}{I want to ask again about that legendary radscorpion.}
{351}{}{Ah, after such a story, I don't want to go out into the wasteland, right?}
{352}{}{Let's change the subject.}
{353}{}{I killed a scorpion.}
{1353}{}{I killed a scorpion.}
{354}{}{COME ON?! And of course you have no proof, right?}
{355}{}{A corpse is easy to find in the middle of the desert. Give the task to the patrolmen, they will confirm.}
{356}{}{Hmm, this can be arranged. If this is true, then thanks from all the Rangers. You've done a great service to the whole Wasteland.}
{1356}{}{Hmm, that can be arranged. If this is true, then thanks from all the Rangers. You have done a great service to the whole Wasteland.}
{357}{}{It seemed to me that such services should be paid for.}
{358}{}{And it seemed to me that such statements should be supported by evidence. Is not it so?}
{359}{}{Ugh, it's too late to look for evidence. So just mentioning me in the chronicles is enough.}
{360}{}{That's enough for me. Happily.}
{361}{}{I can only show this stump of a spear that was sticking out of the shell.}
{362}{}{Damn me! I remember him... Did you really manage to defeat this monster? But... how?}
{363}{}{He is big, but clumsy.}
{364}{}{There is no price for people like you. Here, take some cartridges from me and this old revolver as a token of appreciation. Don't be modest, I have something to shoot back from mutants in the desert. Thank you again.}
{365}{}{Please.}