{100}{}{You see a kid.}
{101}{}{You see the child from the Milton family.}

#Диалог
{110}{}{Hi. You've come to rid us of the rodents?}
{111}{}{Save my parents!}
{112}{}{Rangers *are* cool. When I grow up I'll also become a cadet.}
{113}{}{This is all your fault! Get out of here!}
{114}{}{This is all your fault! Get out of here!}
{115}{}{Don't come close to me!}
{116}{}{Thanks for saving us from that terrible monster.}

{200}{}{Wait! There's a... there's... there's a bandit!}
{201}{}{Where?}
{202}{}{Calm down, I don't understand a word of what you're saying.}
{203}{}{A bandit in our shack! He has a gun and he tied mom and dad! Save them!}
{204}{}{Remain here. We'll go there and see what we can do.}
{205}{}{Then move, kid. This is a situation for professionals.}
{206}{}{Nah, kid. It was just a big pigrat...}