{100}{}{You see miss Milton.}
{101}{}{You see the mother from the Milton family.}

#Диалог
{110}{}{Please, save us from those damned pigrats!}
{111}{}{Stop him before he shoots someone!}
{112}{}{Thank you for saving us. If it wasn't for you, he would have surely killed us.}
{113}{}{Thank you for your help. Now leave. I have to bury my husband.}
{114}{}{What use is there of you, you damned Rangers?! Get lost!}
{115}{}{Don't come any closer!}
{116}{}{Thank you for your help. I hope Nataani's spirit will not decide to take revenge on us.}
