{100}{}{This is Mr. Milton.}
{101}{}{You see the father of the Milton family.}

#Dialog
{110}{}{We have nothing to pay with, but you won't leave us alone with these pig rats, will you?}
{111}{}{Stop him, you're rangers!}
{112}{}{Thank you for saving us. Now I have a better opinion of you.}
{113}{}{Thank you for your help, but it won't bring my wife back.}
{114}{}{What's the use of you, damn rangers?! Get out!}
{115}{}{Don't come near me!}
{116}{}{Did Nat-Aani give up the ghost? Ugh, what a relief!}