{100}{}{You have a child in front of you.}
{101}{}{You see the child of the Milton family.}

#Dialog
{110}{}{Hi. Have you come to rid us of rodents?}
{111}{}{Save my parents!}
{112}{}{Rangers are really cool. When I grow up, I will also become a cadet.}
{113}{}{It's all because of you! Go away!}
{114}{}{It's all because of you! Go away!}
{115}{}{Don't come near me!}
{116}{}{Thank you for saving us from this terrible monster.}

{200}{}{Wait! There... there... There's a bandit!}
{201}{}{Where is the bandit?}
{202}{}{Calm down, I won't understand what you're saying.}
{203}{}{The bandit is in our hut! He's got a gun, he's tied up Dad and Mom! Save them!}
{204}{}{Stay here. We'll see what we can do.}
{205}{}{Then move over, little ones, this is a case for real pros.}
{206}{}{No, kid, it was a big pig-rat...}