{100}{}{You see a bandit.}
{101}{}{You see a dangerous criminal with a shotgun in his hands. And he's ready to shoot it.}

{110}{}{Lie still and don't dig!}
{111}{}{Where is this cute little bitch?}
{112}{}{If the kid doesn't come back, I'll shoot someone.}
{113}{}{Hey, Dad, do you want a shot of fractions?}
{114}{}{Where do they keep the caps?}
{115}{}{Damn, these beggars don't have any food!}
{116}{}{Bitches, who do you take me for?!}
{117}{}{I'll cut off her fingers if your geek doesn't come back with food.}
{118}{}{Fingers are dancing on the hook.}
{119}{}{}

#Dialog
{200}{}{Stop! Hands up so I can see!}
{201}{}{You will die.}
{202}{}{You're surrounded, give up if you're not tired of living.}
{203}{}{(thinks for a second) Fuck you!}
{204}{}{Ugh...}
{205}{}{(thinks for a second and then rushes away)}
{206}{}{Come on, run away from here.}
{207}{}{Your hostages have escaped. Surrender or die.}
{208}{}{Which... So, don't forget who has a gun here. And now I'm leaving the valley. And you shut up and stay here. Understand?}
{209}{}{Come on, run away from here.}