{100}{}{You see mister Milton.}
{101}{}{You see the father from the Milton family.}

#Диалог
{110}{}{We can't pay you with anything but you're not going to just leave us here with those pigrats, right?}
{111}{}{Stop him, you're Rangers!}
{112}{}{Thanks for saving us. I now think more highly of you.}
{113}{}{I thank you for your help, but that won't return my wife...}
{114}{}{What use is there of you, you damned Rangers?! Get lost!}
{115}{}{Don't come any closer!}
{116}{}{Nataani has released it's final breath? Phew, what a relief!}
