{100}{}{You see a bandit.}
{101}{}{You see a dangerous criminal with a shotgun in his hands. And he's very prepared to fire from it.}

{110}{}{Lie down quietly and don't make noise!}
{111}{}{Where is that sonovabitch?}
{112}{}{If that kid doesn't come back I'll definitely shoot somebody.}
{113}{}{Hey daddy, wanna eat some lead?}
{114}{}{Where are they holding all the caps?}
{115}{}{Dammit, those bums don't even have any food!}
{116}{}{Who do you take me for, fuckers?!}
{117}{}{I'll cut her fingers off if your kid doesn't come back with food.}
{118}{}{Fingers play when hooked.}
{119}{}{}

#Диалог
{200}{}{Stop! Hands up so I can see 'em!}
{201}{}{You're gonna die.}
{202}{}{You're surrounded, surrender if you're not tired of living.}
{203}{}{(thinks this over for a second) Fuck off!}
{204}{}{Oof...}
{205}{}{(thinks this over for a second then runs away)}
{206}{}{Yeah, get outta here.}
{207}{}{Your hostages ran away. Surrender or die.}
{208}{}{What... Don't you forget who has a gun here. And now I'm gonna leave this valley. And you'll shut up and remain here. Get it?}
{209}{}{Yeah, get outta here.}
