{100}{}{This is Miss Milton.}
{101}{}{You see the mother of the Milton family.}

#Dialog
{110}{}{Please get rid of these damn pig rats!}
{111}{}{Stop him before he shoots someone!}
{112}{}{Thank you for saving us. If it wasn't for you, he would have killed us for sure.}
{113}{}{Thank you for your help, and now leave me, I have to bury my husband.}
{114}{}{What's the use of you, damn rangers?! Get out!}
{115}{}{Don't come near me!}
{116}{}{Thanks for the help. I hope the spirit of Nathan will not take revenge on us.}