{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Back.}

{210}{}{Checking the status of the station.}
{211}{}{Hydraulic unit 1 is active. Hydraulic unit 2 is active. Hydraulic unit 3 - stopped. Gateways lowered: 1,2,3,5. Gateways raised: 4.}
{212}{}{Lower the lock 4. It will be fun when the water floods the superstructure on the dam.}
{213}{}{Attention! The mode of complete dam closure is selected. This is to change the hydrological regime of the reservoir. Do you confirm the command?}
{214}{}{I confirm the command.}
{215}{}{Gateway 4 is down. Attention! All gateways are in the lowered position.}
{216}{}{It's time for me to get out of here...}
{217}{}{What? No, no, don't lower the floodgates! Canceling the command.}