{100}{}{You see a Ranger computer.}
{101}{}{You see a computer with access to a shared server.}

#Dialog
{200}{}{Enter command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Connect to the server.}
{204}{}{Access to the central server has been obtained.}
{205}{}{Great.}

{210}{}{Ranger dossier.}
{211}{}{Select a directory.}

{212}{}{Jackals.}
{213}{}{Jackals are a tribe of cannibal savages living in the Mojave Desert. Very little is known about their history and internal order, as the tribe behaves extremely hostile to outsiders.}
{214}{}{[Next]}
{215}{}{There are more than a dozen clans, each with its own territory and its own rules. They all practice cannibalism.}
{216}{}{Current threat.}
{217}{}{The largest clan of Jackals is dying out, the rest pose a passive or delayed threat.}
{218}{}{A peace treaty has been concluded between the Rangers and the Jackals. All rangers are instructed to avoid conflicts with this tribe unless absolutely necessary.}
{219}{}{Jackals are one of the main threats to travelers between north and south. They are skilled and cunning hunters of people and can be dangerous even for a trained ranger. The Council of Elders decided that the tribe should be destroyed.}

{230}{}{Villa.}
{231}{}{A closed rural community living by subsistence farming. Tries to avoid contact with outsiders and maintains neutrality in external processes.}
{232}{}{The current threat.}
{233}{}{The peasants of the Villa have gone over to the enemy's side, but by themselves, they hardly pose a threat to us. Conflicts with this settlement should be avoided, but try to stop any friendly relations between them and the Brotherhood of Steel.}
{234}{}{A mutual assistance contract has been signed between the peasants of the Villa and the Rangers.}
{235}{}{The Villa peasants have great potential for Rangers, but they categorically refuse the contract. Friendly relations should be established with this settlement.}
{236}{}{Sabotage at the Villa.}
{237}{}{The peasants of the Villa have refused our cooperation, but in themselves, they hardly pose a threat. We should avoid conflicts with this settlement, but try to stop any friendly relations between them and our enemies.}

{250}{}{Red Threat.}
{251}{}{The Followers of Fire are a sect of worship of nuclear power and technology of the Old World.}
{252}{}{The current threat.}
{253}{}{The sect is in a state of disintegration and persecution. The main base of Followers was destroyed, presumably by an underground nuclear explosion. Details of the incident are unknown. At the moment, only individual clans and detachments are dangerous, they can parasitize settlements that were previously friendly to them or engage in open banditry.}
{254}{}{The sect is rapidly spreading its influence to the entire surrounding region, including Southern Arizona and the entire Sonora wasteland. The Council of Elders has identified their threat as the highest priority.}
{255}{}{Conducting operations against the red threat.}
{256}{}{Sabotage in Flagstaff (suspended), support for the struggle in San Brahmin, support for the struggle of runaway slaves in Tu San.}
{257}{}{Sabotage in Flagstaff.}
{258}{}{The colony actively uses slave labor and is sponsored by the Church of the Sacred Fire. All sabotage operations in Flagstaff are temporarily suspended.}
{259}{}{Support for the struggle in San Brahmin.}
{260}{}{The sect of fire worshippers actively sponsors revolutionary sentiments in the city of San Brahmin in order to expand its empire. We are forced to intervene in the course of events. Consultants have been sent to San Brahmin to fight the empire.}
{261}{}{Espionage in Phoenix.}
{262}{}{Several rangers are operating in Phoenix for the purpose of reconnaissance. Now their priority task is to establish contact with a mysterious group of guerrillas acting against the cult of Fire.}
{263}{}{Support for runaway slaves in Two-Sun.}
{264}{}{The activities of the techno-worshippers of the city of Two-Sun pose a particular threat to the well-being of other settlements. Phoenix Fire worshippers actively cooperate with them to obtain various goods and services. Due to the remoteness of the territory, it is difficult to control the situation, so we have sent spies to help runaway slaves who are conducting sabotage activities there. }

{290}{}{Threat from the south.}
{291}{}{Scouts report on the elimination of the main fort of the Brotherhood of Steel in the south. This day will go down in the history of the whole of Arizona as the day of freedom and independence!}
{292}{}{The Brotherhood of Steel is a closed militarized organization with imperial ambitions. Practices slavery, forcing settlements to cooperate against their will, military incursions, and other criminal acts. At the moment, the puppet controls a significant part of the settlements of Southern Arizona, including the city of Phoenix. We are obliged to prevent the further spread of this force.}
{293}{}{Scouts report on a little-known mysterious organization in the south. Evaluation is currently impossible due to a lack of information.}