{200}{}{Enter command.}
{201}{}{Finish session.}
{202}{}{Back.}

{210}{}{Power plant status check.}
{211}{}{Hydraulic unit 1 - online. Hydraulic unit 2 - online. Hydraulic unit 3 - turned off. Hatches lowered: 1,2,3,5. Hatches raised: 4.}
{212}{}{Lower hatch 4. It'll be fun when the water floods the dam superstructure.}
{213}{}{Warning! Complete dam lockdown mode selected. This will change the hydrological situation of the water reservoir. Confirm command?}
{214}{}{Command confirmed.}
{215}{}{Hatch 4 lowered. Warning! All hatches are in a lowered state.}
{216}{}{I should get outta here...}
{217}{}{What? No, no, don't lower the hatches! Cancel command.}
