{110}{}{Great plan... for a suicide.}
{111}{}{This cannot be done during combat.}
{112}{}{The rangers at the post forbid you to go there.}
{113}{}{The Rangers allowed only you to enter the dam, but not your partners.}
{114}{}{[Stealth 120] All your distractions are futile.}
{115}{}{The rangers at the post forbid you to carry power armor.}

{120}{}{You can't do it unnoticed. We'll have to negotiate with the guards.}
{121}{}{It's pointless.}
{122}{}{This door is hardly dangerous.}
{123}{}{A sturdy homemade door. It remains to praise the master who made it.}
{124}{}{Does not need repair.}
{125}{}{It does not need repair. What can't be said about the dam behind the door.}