{110}{}{This lifting mechanism holds the dam gate with steel cables.}
{111}{}{The lifting mechanism is out of order. It can hardly be repaired.}
{112}{}{There was not even a scratch on the mechanism.}
{113}{}{The lifting mechanism shatters into pieces, and the load-bearing cables fall into the darkness with a whoosh. Soon, at the bottom of the mine, you hear a strong rumble of a falling shutter.}
{114}{}{It seems the Rangers are waiting... a small flood.}