{100}{}{This is Officer Bell.}
{101}{}{You see a soldier with a very exhausted look.}
{102}{}{This patient is not injured or concussed. He received a severe mental trauma.}
{103}{}{This will clear your head a little, soldier...}
{104}{}{They come to me in my dreams... Don't let me fall asleep!}
{105}{}{Thank you, I feel much better now. All of this now comes back to me as an ordinary nightmare.}
{106}{}{Bell refuses to accept it.}

#Floating dialog (do not delete problems!)
{110}{}{ }
{111}{}{Doc! Doctor! Don't let me fall asleep!}
{112}{}{Calm down, Bell. It's all right. Are you having nightmares again?}
{113}{}{They come to me in a dream... These eyes look straight into the soul...}
{114}{}{Who?}
{115}{}{Doc! They'll take me to hell!}
{116}{}{Calm down, Bell, old man. No one will pick you up while you're sleeping. It's just a nightmare...}
{117}{}{No! They definitely exist... These voices are in my head... I hear them!}
{118}{}{Pull yourself together, soldier! There are no voices.}
{119}{}{So... is it my imagination? Sorry, Doc...}
{120}{}{Exactly, Bell. It's just a mental disorder. You just need to rest.}
{121}{}{Doc, you've said this before, but sleeping pills don't help...}
{122}{}{I'll give you a double dose. Everything will be fine.}
{123}{}{Thanks, Doc... I'll try to fall asleep...}
{124}{}{That's good. Sleep, Bell. No one will bother you this time.}
{125}{}{*Hr-r-r*}
{126}{}{Ugh, he finally shut up.}
{127}{}{*Z-z-z*}
{128}{}{Well, the long-awaited moment of peace...}
{129}{}{*N-n-n*}
{130}{}{   }

{200}{}{They come to me in my dreams... Don't let me fall asleep!}
{201}{}{Who! Who comes to you in a dream?}
{202}{}{They! Huge... scary...}
{203}{}{Look, Bell, I want to help. Describe who you're afraid of.}
{204}{}{Soldier! Pull yourself together!}
{205}{}{Scary... burning eyes in the dark... I don't remember anything...}
{206}{}{It looks like you buried your memories in the subconscious.}
{207}{}{Stop snotting like a woman.}
{208}{}{It's a huge shadow. With burning eyes. She comes to me in a dream... I can't move... She's watching... Huge...}
{209}{}{What else do you see around you? Come on, remember.}
{210}{}{Who's watching? Where is he looking? I don't understand anything!}
{211}{}{There's darkness all around... And the gray desert... No, it's not gray sand, it's ash... This is hell! I try to run, but nothing works... It doesn't work!}
{212}{}{The ash desert? Where can this be?}
{213}{}{You're delusional. The desert does not happen like this.}
{214}{}{I don't know! I don't know! Leave me alone!}
{215}{}{Uh, okay.}
{216}{}{OK. Your whining is already pretty tired.}

{220}{}{I want to sleep... But don't let me fall asleep! Otherwise it will come for me... Yeah, it's going to come and take me straight to hell.}
{221}{}{Um, I need to get out. Later.}

{230}{}{Bell, look. Here's the head of the thing you're so afraid of.}
{231}{}{Bell, I know who you saw there in the quarry. That thing is dead. Residents of Casa Nueva are already dancing around her effigy.}
{232}{}{What... This is... ah, ha-ha! She's dead! Dead! And in the light of day, it's not so scary. Ugh! What a fool I was! So much fear because of some ugly mutant. Ha ha!}
{233}{}{Well yes. It's over. She won't come to you again in a dream.}
{234}{}{Who would doubt.}
{235}{}{Now I remember everything. This creature appeared right in front of me during the night watch in the quarry. She looked me straight in the eye! I was one step away from death. But I was lucky, she attacked my partner... I think I was so scared that I hid that night far away in my subconscious.}
{236}{}{In your place, anyone could be scared.}
{237}{}{And this creature didn't scare me.}
{238}{}{But now I'm free! Thank you, you deserve the title of paladin much more than I do. Let me share the bullets with you. It's the least I can do for you.}
{239}{}{Take care of yourself, soldier.}
{240}{}{Yeah, you definitely don't need bullets. Happily.}