{100}{}{You see General Dixon.}
{101}{}{You see the general himself - an incredibly vain and assertive soldier.}
{102}{}{I'm not up to talking right now.}
{103}{}{?}
{104}{}{ What are you allowing yourself?! Any power armor is the property of the Brotherhood of Steel. Return it to the quartermaster immediately.}
{105}{}{Thanks for the help with the Rangers. But I have a lot to do right now. Contact someone from below.}
{106}{}{You have officially given up the Ranger badge.}
{107}{}{You have officially joined the Order of the Brotherhood of Steel.}
{108}{}{[Head test]}
{109}{}{[Smile]}
{110}{}{[Norms]}
{111}{}{[Boo-y]}
{112}{}{[Exit]}

#The first dialog
{200}{}{Civilian? What are you doing here?}
{201}{}{I... uh...}
{202}{}{I'm destroying your ship, you idiot.}
{203}{}{A rat on a ship! All battle alert!}
{204}{}{Damn...}
{205}{}{It won't save you...}

{210}{}{What the fuck are these jokes? Someone is going to be severely reprimanded today for missing civilians. Okay, tell me who you are and what you want.}
{211}{}{I'm here to wipe out your vile colonization squad. Death to the invaders!}
{212}{}{Let me go, General.}
{213}{}{Ulysses Grant sent you a report.}
{214}{}{Ah, finally. They say the recent events in Phoenix should make me happy. Look, courier, don't disappoint.}
{215}{}{That's right, General.}
{216}{}{I'll try, General.}
{217}{}{But I also wonder why Ulysses chose YOU to report? This is a responsible matter, he would not entrust it to a simple crook. Tell me about yourself, who are you and what do you have to do with sectarians in Phoenix?}
{218}{}{I have a long history, General. I'm from a village in the north. You've hardly heard of her.}
{219}{}{A village? So are you growing something? Or are you engaged in hunting and gathering?}
{220}{}{We cultivate the land and grow maize. But recently there have been problems with colonizers from Flagstaff...}
{221}{}{Ah, that's it. I have already been informed that there is a shortage of labor in the uranium mines. Well, the costs are inevitable. It's not fucking fair, son.}
{1221}{}{Ah, that's it. I have already been informed that there is a shortage of labor in the uranium mines. Well, the costs are inevitable. It's damn unfair, lady.}
{222}{}{That's right, General. Unfair.}
{223}{}{I was sent by Hard from Two-Sun for service. Here is his recommendation.}
{224}{}{Hard must have a really good reason for your recommendation. I heard that there have been major changes in Two-Sun recently. But tell me about yourself, who are you and how did you earn such trust among tinkerers?}
{1224}{}{Hard must have a really good reason for your recommendation. I heard that there have been major changes in Two-Sun recently. But tell me about yourself, who are you and how have you earned such trust among tinkerers?}
{225}{}{The Rangers sent me. They want to stop you, but I'm interested in listening to both sides.}
{226}{}{Ha, we know the Rangers are scouting. But I respect your courage. Tell me, what did the Rangers promise you in exchange for our secrets?}
{227}{}{Actually, they promised freedom and protection of my native village.}
{228}{}{I am here because you are responsible for the troubles that plague my village. Because you crave energy sources, the Flagstaff colony enslaves villages like ours.}
{229}{}{I demand freedom and independence for my native village.}
{230}{}{Perhaps you dream of freedom for your village? So that the bandits do not disturb your brother, and the maize grows without blood and sweat.}
{231}{}{Is that possible, General?}
{232}{}{Of course, General.}
{233}{}{The Brotherhood of Steel knows how to get justice. We are the only ones who have preserved the wisdom of the Old World.}
{234}{}{It's hard to argue with that.}
{235}{}{Really?}
{236}{}{If your village needs freedom, then join our Brotherhood. We will protect the Villa from enemies and help with technology. In exchange, of course, for a small surplus crop. But no creature in Arizona will dare to encroach on your sacred freedom.}
{237}{}{But we know almost nothing about your Brotherhood.}
{238}{}{Too loud a speech, General. What kind of Brotherhood are you anyway?}
{239}{}{The Brotherhood of Steel is an ancient order. We are collecting and reviving technologies and knowledge that were lost after the Great War. For a long time, we hid in the shadow of history, studying the situation and gathering strength. And now the end of our isolation has come. The brotherhood came out of its bunker a few years ago. Our scribes will tell you the details.}
{240}{}{.......}
{241}{}{I'm just walking by and wondering if you have a job.}
{242}{}{I don't do mercenaries. There is a special post outside for this. Now I ask you to leave our fortress immediately.}
{243}{}{Excuse me, General...}
{244}{}{OK, I'm leaving peacefully.}
{245}{}{How are you going to change the Wastelands?}
{246}{}{But what are you trying to achieve with your expansion?}
{247}{}{The wastelands themselves must be reborn. We just happened to provide a little assistance. A small push that did not arise by our will. But it will give you an incentive for a big move. Tell me, surely people still work manually in your Villa, don't they?}
{248}{}{[Nod]}
{249}{}{Imagine how the village will change if we bring water pumps, generators, and new tools there. Not to mention medicine and means of protection from bandits.}
{250}{}{You will simply occupy us and force us to work for the good of the Brotherhood. This is not freedom.}
{251}{}{In that case, I'm wasting my time trying to be nice to you. Your village WILL supply us with food even against its own will. You had a chance to choose an easy path, but this chance was missed. Put down your weapons and put your hands up.}
{252}{}{Uh, don't, General...}
{253}{}{The hell with it. You will not intimidate the free peasant people.}
{254}{}{Sounds amazing. I'll talk to the elders.}
{255}{}{A reasonable solution, mi querido amigo. However, even with the consent of your community, there is one significant obstacle - the rangers prevent us from developing in the northern direction, and also sabotage the world around Phoenix. And we are just conducting reconnaissance in their lands to pacify these self-styled robbers.}
{256}{}{Then they need to be eliminated. Their lands just lie in my way.}
{257}{}{I like to be understood from the first word. Find the Ranger base and scout there. As far as I know, they use the old dam as a fort. One crack is enough to destroy it. Act.}
{258}{}{It will be done, General!}
{259}{}{Whatever you say, Mr. Dixon.}
{260}{}{Here we are, you fucking bastard. I knew you'd come here someday. Yes, the whole of Arizona is crying for you already.}
{1260}{}{Here we are, you fucking bitch. I knew you'd come here someday. Yes, the whole of Arizona is crying for you already.}
{261}{}{Here we are, you fucking bastard. I knew you'd come here someday. Yes, the whole of Arizona is already talking about you.}
{1261}{}{Here we are, you fucking bitch. I knew you'd come here someday. Yes, the whole of Arizona is already talking about you.}
{262}{}{How do you know about me?}
{263}{}{Naive Redneck, do you really think that your antics will go unnoticed? We have enough ears in the wastelands to know all the most important events.}
{1263}{}{Naive redneck, do you really think that your antics will go unnoticed? We have enough ears in the wastelands to know all the most important events.}
{264}{}{And what do you think about it, General?}
{265}{}{I don't care. I'm here to kill you and your whole gang.}
{266}{}{Son of a bitch, do you have any idea how much work it took to create a cult in Phoenix? All this grandiose work was aimed at the revival of the city. But now the only possibility has burned down in a nuclear fire because of some handful of peasants. This is a tragedy for the whole of Arizona, damn it!}
{267}{}{Continue.}
{268}{}{Do you know how much work we have put into an alliance with the tinsmiths? Our diplomats have shown miracles in establishing contact with them. It was still necessary to establish caravan routes. Now everything in the Two-Sun district will die out because of you.}
{269}{}{Go ahead.}
{270}{}{The Flagstaff mines were a critical element in the entire system. Uranium ore provides energy, and without it, all other development in Arizona is impossible. And now this source is blocked for the coming decades. Can you imagine the scale of this tragedy?}
{271}{}{Continue.}
{272}{}{.....}
{273}{}{Go on.}
{274}{}{And now I have a question for you - what are you trying to achieve, you son of a bitch?}
{1274}{}{And now I have a question for you - what are you trying to achieve?}
{275}{}{Because of all this movement, my family got into a difficult situation. I am seeking freedom for my Villa.}
{276}{}{Maybe I would feel compassion for you, trying to find a compromise. But such a grandiose work on the establishment of social, economic, and technological processes in the whole state is going down the drain because of one dirty rebellious village!}
{277}{}{Yes, that's right. You can't take away our freedom. Something you don't like, General?}
{278}{}{You are committing a crime against residents, hiding behind noble goals. But you didn't even ask our opinion.}
{279}{}{If housewives had ordered politics before the War, the world would not have been able to live a day!}
{280}{}{Nonsense. Housewives don't want the world to burn. And because of your intervention, Dixon, the whole of Arizona is on fire.}
{281}{}{Perhaps you're right about that, General.}
{282}{}{Well, for all your antics, you should be given credit. I could not have expected that Redneck alone would be able to pull off such a complicated case. But you know, I'm ready to forgive you these crimes.}
{283}{}{Really?}
{284}{}{Oh, how "noble" of you.}
{285}{}{Your rebellious village will receive forgiveness and immunity from the Brotherhood. But for this to happen, it is necessary to eliminate our main competitor in Arizona - the Rangers. They say they built a fort on an old hydroelectric station. Conduct a reconnaissance and find a way to destroy their dam.}
{286}{}{The hell with two. The Rangers will protect us, and you will go to hell.}
{287}{}{Very sorry. So, by the laws of the Old World, you will face the death penalty for your crimes. Get ready to accept your fate, you piece of shit...}
{288}{}{Go to hell.}
{289}{}{But I'm not a criminal...}
{1289}{}{But I'm not a criminal...}
{290}{}{If you leave us alone, then I will try to do it.}
{291}{}{As the supreme Paladin, I will keep my word. Act.}
{292}{}{Goodbye.}
{293}{}{It is strange to hear this from the mouth of someone guilty of this.}
{294}{}{What the hell are you talking about? We are just the final buyers of nuclear batteries. They are made by Two-Sun tinsmiths, and uranium is brought for them from Flagstaff. I am also not in the mood that the colony's leadership has fallen victim to its greed. But we have to turn a blind eye to this. We need these batteries!}
{295}{}{Yeah. It sounds like you're out of business. But really?}
{296}{}{Listen, son, we're not slavers. We are an ancient noble order whose purpose is to keep order in the wastelands. And California is a complete mess right now. Right now there is a war being waged with an army of super mutants. If the Brotherhood fails to contain this green threat, it will soon get to you. Do you want this?}
{1296}{}{Look, lady, we're not slavers. We are an ancient noble order whose purpose is to keep order in the wastelands. And California is a complete mess right now. Right now there is a war being waged with an army of super mutants. If the Brotherhood fails to contain this green threat, it will soon get to you. Do you want this?}
{297}{}{No way, sir.}
{298}{}{Stop pouring this shit on my ears. I see the threat right in front of me!}
{299}{}{}

#Repeat dialog
{300}{}{Report.}
{301}{}{Permission to go, General.}

{310}{}{I have a message for you from Ulysses Grant.}
{311}{}{I have been waiting for this report for a long time. Come here.}
{312}{}{Here it is.}
{313}{}{Actually, the film deteriorated on the way. I'm sorry.}
{314}{}{}
{315}{}{Why don't you put a sign on your chest that says: "Cretin"? I don't care how, but do your job and bring me this report!}
{1315}{}{Why don't you put a sign on your chest that says, "Brainless fool"? I don't care how, but do your job and bring me this report!}
{316}{}{Uh, yes, General.}
{317}{}{It was a joke, General. The holodisk is in perfect order.}
{318}{}{Do you think that's funny? Damn, savages! I have a whole army under my command, and you're joking here? Pray that there is no sedition against you in the report. Otherwise, I'll skin you alive. So where is the report?}
{319}{}{Here it is, General.}
{320}{}{Not so fast. I was promised a reward for this work.}
{321}{}{Your job is to do the job and shut your mouth until a senior officer turns to you. Shut up! So where's the report?}
{322}{}{So. Umgu. Curious. Good news. It also talks about your services to the Cathedral. Ulysses wouldn't pay so much attention to you without a good reason.}
{323}{}{Well, my task is done. I think I should go.}
{324}{}{The journey through the desert must have taken a lot out of you. Don't worry, we'll pay for the job. Contact the quartermaster, he will reward you.}
{325}{}{Thank you, General.}
{326}{}{Just curious - what does it say?}
{327}{}{It's not very smart of you to get involved in such questions. However, judging by the report, you already know a lot.}
{328}{}{Indeed.}
{329}{}{I'm just doing my job. So what about the payment?}
{330}{}{Do you want caps, but don't want to choose? It is a pity that among your mercantile interests, there is no concept of honor and justice. But you do your job properly, and this is appreciated in the Brotherhood. Don't worry, we'll pay. Contact the quartermaster, he will give you a fee.}
{331}{}{Thank you, General.}

#Questions about BS
{350}{}{Tell me about the Brotherhood of Steel.}
{351}{}{You're talking to the general, damn it. I have neither the time nor the desire to have explanatory conversations with you.}
{352}{}{}
{353}{}{Okay, I'll try to ask someone else.}
{354}{}{General Dixon, may I ask a question about the Brotherhood?}
{355}{}{We are a closed organization from California with an army charter and a great past.}
{356}{}{It doesn't look like you're closed.}
{357}{}{Previously, the Brotherhood lived in an underground bunker and did not stick out of there unnecessarily. Rare heroes managed to get inside. We did not interfere in the affairs of the region, only traded and kept order in the vicinity.}
{358}{}{Continue.}
{359}{}{It must have been terribly boring.}
{360}{}{After some events that you probably don't know about, the elders finally decided to get out of the stuffy dungeon and start exploring the neighboring lands.}
{361}{}{Now it's clear. You know, I have even more questions about the Brotherhood.}
{362}{}{And you are glad to leave the stuffy bunker, aren't you? It looks like the Brotherhood needs fresh air.}
{363}{}{Thank you for your time. I dare not detain you any longer.}
{364}{}{Why are you quartered in this particular port?}
{365}{}{This is a good place to organize an impregnable fortress. Besides, there is no reactor in the area better than our destroyer.}
{366}{}{I see. May I ask another question about the Brotherhood?}

{367}{}{Why are you interfering in the affairs of this region?}
{368}{}{We just need resources. To get them, you need a workforce and a well-established infrastructure. None of this is here, and our little squad is not enough for this. Therefore, there is only one way - to connect the local savages by teaching them to hold a shovel straight.}
{369}{}{Isn't there another answer?}
{370}{}{Look at your tribes. They are feuding over minor troubles. For a pathetic sip of water, they are ready to cut each other's throats. Phoenix City is envied by all the surrounding settlements, and the settlements themselves hate each other even more. These lands need a force that could unite them and direct them to the revival of civilization.}
{371}{}{[Next]}
{372}{}{Is there such a force in these parts? No. But here we come. Of course, we have our own personal interests - pre-war resources and knowledge. You savages, in any case, are not able to properly use these deposits of priceless human creations.}
{373}{}{[Next]}
{374}{}{To get them, we push the tribes on the path of progress and unification. Thus, they gain valuable experience. We brought to these lands the economy, currency, medicine, and the first school in the entire post-war history! No matter how much the local savages hate us, the whole of Arizona owes us its new achievements.}
{375}{}{Those are your words, Dixon. Does the General Staff know?}
{376}{}{This fort is worth several... aside from the decisions of the General Staff. I was given "broad powers" to successfully complete the main mission.}
{377}{}{I see. May I ask another question about the Brotherhood?}
{380}{}{What are your global goals?}
{381}{}{The answer will be ambiguous. There have been disputes between scribes for decades. Some believe that we should throw our efforts at restoring civilization according to the ideals of the Old World. Others consider the world not worthy of our knowledge and technology.}
{382}{}{[Next]}
{383}{}{In any case, the leadership was not going to influence Arizona. Here the order hoped only to replenish stocks of nuclear material and launch several surviving workshops. Exclusively for their own internal purposes and for the war with the super mutants. But it turned out to be much more complicated.}
{384}{}{What do you mean?}
{385}{}{They don't understand that you can't just come and take old batteries from a pile of garbage. We need workers, caravans, and even a postal service. We need a functioning infrastructure and economy! None of this happened until my squad entered these wild lands.}
{386}{}{I see. Let me ask you another question about the Brotherhood?}
{387}{}{Tell us about California.}
{388}{}{The lands of California are devastated by war and time. Los Angeles is in ruins. But gradually civilization rises from the ashes.}

{400}{}{I need to talk to you about the Rangers.}
{401}{}{These upstarts are always getting in the way and won't let us work. Did you manage to find out the weaknesses of their defense?}
{402}{}{No, sir. They are too well organized.}
{403}{}{It is difficult to expect something from a simple peasant. But I am sure that you will succeed. Keep me posted.}
{1403}{}{It's hard to expect anything from a simple peasant woman. But I am sure that you will succeed. Keep me posted.}
{404}{}{Let me go.}
{405}{}{Why are the Rangers bothering you? Don't they represent the law, just like you?}
{406}{}{Firstly, they consider us invaders and turn the population against us. And this directly interferes with our plans. Secondly, they restrain the development of progress, for example, sabotage the work of caravans and work camps. Finally, they have crushed huge lands under themselves and take a tax from the population. Who do they think they are?!}
{407}{}{Perhaps they have a reason for that?}
{408}{}{Reminds me of someone, don't you think?}
{409}{}{Ahem... In the end, they don't let us connect California and Arizona. Moreover, they have already shown their meanness in the Battle of Nogales, when they tried to quarrel with the tinsmiths and oust us from the territory of the state. This is more than enough.}
{410}{}{Permission to go, General?}
{411}{}{I managed to blow up the Rangers' dam.}
{412}{}{I've already been informed. Good job. With your help, we will drive these invaders out of Arizona and restore order to the lands, as in the good old days.}
{413}{}{And our agreement?}
{414}{}{Of course, the Villa is now under our protection. We will send an ambassador to the village to conclude an alliance.}
{415}{}{Good news.}
{416}{}{In addition, for your services to the United States, I invite you to become a member of the Brotherhood of Steel. Previously, none of the civilians had such an honor. But I have special powers and I see great potential in you. Think about it and let me know your decision. You can go.}
{417}{}{Thank you, General Dixon.}

{420}{}{I want to join the Brotherhood.}
{421}{}{Kneel and tell me your name.}
{422}{}{I }
{423}{}{ from the Villa. And I swear allegiance to the Brotherhood of Steel.}
{424}{}{Choose your division.}
{425}{}{I want to become a scribe and carry the wisdom of the Old World.}
{426}{}{I want to become a paladin and bring death to the enemies of the Brotherhood.}
{427}{}{I want to become a knight to carry the light of technology.}
{428}{}{I want to become a scout, in this, I will be of the greatest benefit to the Brotherhood.}
{429}{}{So be it. }
{430}{}{ from the Villa. From now on, you are an honorary member of the Order of the Brotherhood of Steel. Do not disgrace our name and honor the laws. Remain faithful until death.}
{431}{}{I swear loyalty!}
{432}{}{Although I promised to give you a rank in the order, it turned out that there is an evil reputation about you among our brothers. I'll have to hold off on the order until you prove yourself again.}
{433}{}{Damn. Reputation is quite a thing...}
{434}{}{Our order can be entered only for outstanding merits. And your exploits aren't that impressive.}
{435}{}{I will try my best.}
{436}{}{Okay. You'll hear more about it, General.}
{437}{}{Your services to the Brotherhood are invaluable. I am ready to accept you into our order.}
{438}{}{[Next]}