{100}{}{You see general Dickson.}
{101}{}{You see the general himself - an unbelievably conceited and assertive warrior.}
{102}{}{Now is not the time to talk.}
{103}{}{?}
{104}{}{What do you think you're doing?! Any and all power armor is property of the Brotherhood of Steel. Return it to the quartermaster immediately.}
{105}{}{Thanks for helping us deal with those Rangers. But I have a lot to do right now. Talk to someone with a lower rank.}
{106}{}{You've officially refused your Desert Ranger badge.}
{107}{}{You've officially joined the Brotherhood of Steel.}
{108}{}{[Тест головы]}
{109}{}{[Улыбочка]}
{110}{}{[Норм]}
{111}{}{[Бу-у]}
{112}{}{[Выход]}

#First dialogue
{200}{}{Civilian? What are you doing here?}
{201}{}{I'm... uhh...}
{202}{}{Destroying your ship, you idiot.}
{203}{}{Intruder on the ship! Full battle alert!}
{204}{}{Dammit...}
{205}{}{That won't save you...}

{210}{}{What is this fucking joke? Someone will be severely reprimanded today for allowing civilians on the ship. Now, tell me who are you and what are you here for?}
{211}{}{I'm here to wipe your vile, no-good colonialist organization off the face of the earth. Death to invaders!}
{212}{}{Permission to leave, general?}
{213}{}{Ulysses Grant asked me to give you this report.}
{214}{}{Ah, finally. They say the recent events in Phoenix should lift my spirits. Don't dissapoint me, courier.}
{215}{}{Yes, sir.}
{216}{}{I'll try not to, general.}
{217}{}{But I'm also interested in knowing why Ulysses chose YOU to deliver this. This task demands responsibility, he wouldn't give it to some random passerby. Tell me about yourself. Who are you? What is your relationship with the cultists in Phoenix?}
{218}{}{It's a long story, general. I come from a village to the far north. You likely never heard of it.}
{219}{}{Village? So, you grow stuff? Or do you hunt and gather instead?}
{220}{}{We grow maize. But lately we've had problems with the colonizers in Flagstaff...}
{221}{}{Ah, so that's what you're talking about. I was told that a labor shortage ocurred in the uranium mines. Well, such things are inevitable. It's damn unfair, son.}
{1221}{}{Ah, so that's what you're talking about. I was told that a labor shortage ocurred in the uranium mines. Well, such things are inevitable. It's damn unfair, lady.}
{222}{}{Exactly, general. Terribly so.}
{223}{}{I was sent to serve you by Khard from Two Sun. Here is his letter of recommendation.}
{224}{}{Khard must have some really good reasons to do that. I've heard that there were some serious changes in Two Sun lately? But never mind. Tell me about yourself. Who are you? What did you do to earn the tinsmiths' trust?}
{1224}{}{Khard must have some really good reasons to do that. I've heard that there were some serious changes in Two Sun lately? But never mind. Tell me about yourself. Who are you? What did you do to earn the tinsmiths' trust?}
{225}{}{The Desert Rangers sent me. They want to stop you, but I'm interested in hearing you out.}
{226}{}{Ha, we know the Rangers are already conducting reconnaissance. But I respect your courage. Tell me, what did the Rangers promise you in return for our secrets?}
{227}{}{They promised freedom and security for my home village.}
{228}{}{I'm here because you are responsible for all the trouble my village is in. Because of your lust for energy, the Flagstaff colony is enslaving communities like mine.}
{229}{}{I demand freedom and independence for my home village.}
{230}{}{You must dream of liberty for your village, yes? Of bandits not disturbing your fellow man, of maize being grown without blood and sweat?}
{231}{}{Is that even possible, general?}
{232}{}{Of course I do, general.}
{233}{}{The Brotherhood of Steel knows how to achieve justice. We're the only ones who have preserved the wisdom of the Old World.}
{234}{}{It's hard to argue with that.}
{235}{}{Oh really?}
{236}{}{If your village needs liberty, then join our Brotherhood. We'll defend Villa from enemies and assist it technologically. In exchange for a small part of the crop surplus, of course. But no scum in Arizona will dare threaten your freedom ever again.}
{237}{}{But we know next to nothing about the Brotherhood.}
{238}{}{Sounds too good to be true, general. What is this Brotherhood, anyway?}
{239}{}{The Brotherhood of Steel is an ancient order. We gather and restore technology and knowledge that was lost in the Great War. For a long time, we have been hiding in the shadow of history. Studying our surroundings, gathering strength. But then we realized it was time to end the isolation. The Brotherhood came out of it's bunker a few years ago. Our scribes will tell you the details.}
{240}{}{.......}
{241}{}{I'm just passing by and then I think - maybe you have a job for me?}
{242}{}{I don't deal with mercenaries. There's a special post outside for that. Now, I ask you to immediately leave our fortress.}
{243}{}{Sorry, general...}
{244}{}{Okay, I'm already leaving on my own.}
{245}{}{How are you going to change the Wastes?}
{246}{}{But what are you trying to achieve with your expansion?}
{247}{}{The Wastes must rebuild themselves on their own. We just happened to give a little help. A small push, done not of our own will. But that push will give you momentum to set yourselves in great motion. Say, on your Villa, you must still work manually, right?}
{248}{}{[Nod]}
{249}{}{Just imagine how your village will change when we bring water pumps, power generators and new tools. Not even speaking of medicine and means of defending against bandits.}
{250}{}{You'll just occupy us and force us to work for your Brotherhood. That's not freedom.}
{251}{}{Then I'm just wasting my time trying to convince you. Your village WILL supply us with food, regardless of whether it wants to or not. You had an opportunity to choose the easy way - but now that opportunity is gone.}
{252}{}{Don't do it, general.}
{253}{}{Your guns don't scare me. You will never conquer us.}
{254}{}{That sounds great. I'll speak to the elders about this.}
{255}{}{You've made the right choice, mi querido amigo. But even if your entire commune agrees, there is one major obstacle - the Rangers stand in the way of us developing the northern regions - they even threaten the peace around Phoenix. We are already conducting reconnaissance in their territory to pacify these bandits with delusions of grandeur.}
{256}{}{Then they must be removed. And their lands are near my destination.}
{257}{}{I like it when people understand me right away. Find the Ranger base. Collect data. As far as I know, they're using an old dam as a fort. One crack, and it's all gone. Act.}
{258}{}{Will do, general!}
{259}{}{Whatever you say, mister Dickson.}

{260}{}{So, we've finally met, you bastard. I knew you'd come here one day. Yes, all of Arizona is crying for you.}
{1260}{}{So, we've finally met, you bitch. I knew you'd come here one day. Yes, all of Arizona is crying for you.}
{261}{}{So, we've finally met, you bastard. I knew you'd come here one day. Yes, all of Arizona is talking about you.}
{1261}{}{So, we've finally met, you bitch. I knew you'd come here one day. Yes, all of Arizona is talking about you.}
{262}{}{How did you learn that?}
{263}{}{Do you really think your actions go by unnoticed? We have enough ears out in the wastes to be aware of all important events.}
{1263}{}{Do you really think your actions go by unnoticed? We have enough ears out in the wastes to be aware of all important events.}
{264}{}{And what do you think, general?}
{265}{}{I don't care in the slightest. I'm here to end you and your entire organization.}
{266}{}{You fuck, do you even know how much effort went into creating that cult in Phoenix? All of that grand work was to restore the city. But now, the only opportunity to do so burned in atomic flame because of a bunch of peasants. This is a tragedy for the entire state of Arizona, dammit!}
{267}{}{[Continue]}
{268}{}{Do you know how much effort we spent on making an alliance with the tinsmiths? Our diplomats worked wonders establishing contact with them. We were going to set up entire caravan routes. But now, all life in the entire Two Sun area will die. All because of you.}
{269}{}{[Continue]}
{270}{}{The mines in Flagstaff were the critical component for the entire system. Without uranium ore to provide energy, development of any kind in the rest of Arizona is next to impossible. And now, we are cut off from the source for the next few decades. Do you even realize the scope of this tragedy?}
{271}{}{[Continue]}
{272}{}{.....}
{273}{}{[Continue]}
{274}{}{And now, I have a question for you. Just one - what are you trying to achieve with all of this, you son of a bitch?}
{1274}{}{And now, I have a question for you. Just one - what are you trying to achieve with all of this?}
{275}{}{{My people were enslaved by that system. Everything I've done was to free them.}
{276}{}{Maybe I would empathise with you. Maybe I would have tried to find some way to compromise. But for such grand work on creating sociological, economic and technological change in an entire state to go bust all because of one small, dirty village-}
{277}{}{That's right. We won't sit idly by and let you subjugate us. Problem with that, Mr. Dickson?}
{278}{}{All your talk of progress is just an excuse for your crimes. We were never asked about our opinion on being enslaved.}
{279}{}{If before the War, politics were decided based on the people's whims, the world wouldn't have survived a day!}
{280}{}{Nonsense. A system that doesn't care about the people practically invites rebellion. You're the one plunging Arizona into chaos by trying to implement it. Not me.}
{281}{}{You may be right about that, general.}
{282}{}{Though, even knowing of your transgressions, I must admit - I never expected that one single peasant could perform such complex operations. Thus, I'm willing to forgive those crimes.}
{283}{}{Really?}
{284}{}{Oh, how "honorable" of you.}
{285}{}{Your village, unruly it may be, will receive forgiveness and untouchability from the Brotherhood. But for that to happen, our main competitors in Arizona - the Desert Rangers, need to be eliminated. They say that group set up a fort on an old hydroelectric power plant. Conduct reconnaissance. Find a way to destroy their dam.}
{286}{}{No way. The Rangers will defend us and you'll go to hell.}
{287}{}{Shame. In accordance with the laws of the Old World, you are to be punished for your multitude of crimes with the death penalty. Get ready, you piece of shit...}
{288}{}{Go fuck yourself.}
{289}{}{I'm innocent.}
{1289}{}{I'm innocent.}
{290}{}{If you will leave my people alone, I will find a way to destroy the Rangers.}
{291}{}{As head paladin, you have my word. Now, act.}
{292}{}{Goodbye.}
{293}{}{Rather strange to hear this from the lips of the one guilty of it themselves.}
{294}{}{О чем ты говоришь, черт возьми? Мы всего лишь конечные покупатели ядерных батарей. Их изготавливают жестянщики Ту-Сана, а уран для них привозят из Флагпула. Я тоже не в духе, что руководство колонии пало жертвой своей жадности. Но мы вынуждены закрывать на это глаза. Нам нужны эти батареи!}
{295}{}{Ага. Звучит так, будто вы не при делах. А на самом деле?}
{296}{}{Слушай, сынок, мы не работорговцы. Мы древний благородный орден, цель которого - следить за порядком на пустошах. И в Калифорнии сейчас полнейший бардак. Прямо сейчас там ведется война с армией супермутантов. Если Братство не сумеет сдержать эту зеленую угрозу, то скоро она доберется и до вас. Ты хочешь этого?}
{1296}{}{Слушай, леди, мы не работорговцы. Мы древний благородный орден, цель которого - следить за порядком на пустошах. И в Калифорнии сейчас полнейший бардак. Прямо сейчас там ведется война с армией супермутантов. Если Братство не сумеет сдержать эту зеленую угрозу, то скоро она доберется и до вас. Ты хочешь этого?}
{297}{}{Никак нет, сэр.}
{298}{}{Хватит лить это дерьмо на мои уши. Угрозу я вижу прямо перед собой!}
{299}{}{}

#Repeated dialogue
{300}{}{Report.}
{301}{}{Permission to leave, general?}

{310}{}{I have a holodisk from Ulysses Grant.}
{311}{}{I've been waiting for that report for a long time. Give it to me.}
{312}{}{Here it is.}
{313}{}{Actually, it was damaged on it's way here. I'm very sorry.}
{314}{}{}
{315}{}{Why don't you carry a sign with you that says: "Idiot"? I don't care how, but finish the job and bring me that report!}
{1315}{}{Why don't you carry a sign with you that says: "Idiot"? I don't care how, but finish the job and bring me that report!}
{316}{}{Uhh, yes, sir - general.}
{317}{}{It was merely a joke, general. The holodisk is perfectly fine.}
{318}{}{You think that's funny? Those fucking locals! I manage an entire army and you're here making jokes? You better hope there isn't anything suggesting you have problems with authority in that report. So, where is the holodisk?}
{319}{}{Here it is, general.}
{320}{}{Not so fast. I was told I would be paid for this.}
{321}{}{Your job is to do what you're told to do and shut your mouth until someone of a higher rank starts talking to you. Silence! Where is the report?}
{322}{}{Hmm. Uh-uh. Interesting. Those are good news. It also says you have helped the Cathedral greatly. Ulysses wouldn't pay attention to you without good reasons.}
{323}{}{Well, my job here is done. I suppose I should go.}
{324}{}{All that walking through the desert must have been tiresome. Don't worry, we'll pay for the job. Head to the quartermaster, he will give out the compensation.}
{325}{}{Thank you, general.}
{326}{}{Just curious - what's written there?}
{327}{}{Not too smart of you to ask such questions. Though, based on the report, you already know a great deal.}
{328}{}{Indeed I do.}
{329}{}{I'm just doing my job. Now, what about payment?}
{330}{}{You want caps but you don't want to choose? A shame that there is no understanding of honor and justice among your mercantile interests. But you do your job well, and we value that in the Brotherhood. Don't worry, payment will be provided. Head to the quartermaster, he will give out the compensation.}
{331}{}{Thank you, general.}

#Questions about the Brotherhood
{350}{}{Tell me about the Brotherhood of Steel.}
{351}{}{You're talking to a general, dammit. I have neither the time nor the willingness to have long conversations where I explain everything to someone.}
{352}{}{}
{353}{}{Alright, I'll try to ask someone else.}
{354}{}{General Dickson, could I ask you a question about the Brotherhood?}
{355}{}{We're a closed organization from California with army regulations and a rich history.}
{356}{}{Doesn't look like you're very closed.}
{357}{}{The Brotherhood used to inhabit an underground bunker in the past. We did not go out of it unless it was absolutely necessary. The few outsiders that managed to get inside were heroes. We did not interfere in the region. We only traded and maintained order around our base.}
{358}{}{Go on.}
{359}{}{Must have been very boring.}
{360}{}{But after a series of events that you likely know nothing about, the elders decided to finally go outside the suffocating underground and begin scouting nearby regions.}
{361}{}{I see. You know, I have even more questions about the Brotherhood now.}
{362}{}{And you're happy to do so, right? Looks like the Brotherhood needed fresh air.}
{363}{}{Thank you for spending a part of your time on me. I won't dare disturb you any longer.}
{364}{}{Why did you set up an outpost here?}
{365}{}{This is a good place for an untouchable fortress. And there is no reactor better around here than the one in our ship.}
{366}{}{Got it. Could I ask you another question about the Brotherhood?}

{367}{}{Why are you interfering in this region?}
{368}{}{Officially - we need resources. To get them, we need manpower, infrastructure. Setting all that up in such an underdeveloped region on our own is impossible. There is only one way - offsourcing the work to the locals, teaching them how to hold a shovel straight.}
{369}{}{There's another answer too, right?}
{370}{}{Look at your tribes. They fight for the pettiest of causes. You're ready to slit each others' throats for something as pathetic as a sip of water. All surrounding settlements envy the city of Phoenix, and those settlements hate each other even more. These lands need a force, a force that could unite them and harness their efforts for a single cause - the restoration of civilization.}
{371}{}{[Continue]}
{372}{}{Is there such a force in these lands? No. But that's where we come in. Of course, we have our own interests - the acquisition of Pre-War resources and knowledge. But it's not like you primitives were ever in a position to use those priceless artifacts properly, anyways.}
{373}{}{[Continue]}
{374}{}{To get what we need, we push the tribes toward the path of progress and unification. But in return, they receive benefits that only we can provide. We have brought a working economy to these lands, currency, medicine, the first school in all of Post-War history! Regardless of how much the locals hate us, only we can restore Arizona and bring it to prosperity.}
{375}{}{That's you speaking, general Dickson. Does California HQ know?}
{376}{}{This fort is somewhat... independent of the decisions made in Californian Headquarters. I was given "broad powers" to ensure the success of this mission.}
{377}{}{Alright. Could I ask you another question about the Brotherhood?}

{380}{}{What are your global goals?}
{381}{}{You won't receive one single answer. The scribes have been arguing about this for decades. Some think we should focus all our efforts on restoring civilization based on Pre-War ideals. Others think the world is not deserving of our knowledge and technology.}
{382}{}{[Continue]}
{383}{}{In any case, the elders didn't *want* to influence Arizona. The order just hoped to expand it's reserves of nuclear material and restore a few intact facilities. Purely for it's own internal goals. But in reality, nothing ever works out so easily.}
{384}{}{What do you mean?}
{385}{}{They don't understand that we can't just come in here and take nuclear batteries out of a pile of trash. We need workers, caravans. Even a postal service. We need functional infrastructure and an economy! None of that was here, until my unit arrived.}
{386}{}{Alright. Could I ask you another question about the Brotherhood?}
{387}{}{Tell me about California.}
{388}{}{The lands of California have been ravaged by time and war. Los Angeles lies in ruins. But slowly, civilization is rising from the ashes.}

{400}{}{I need to talk to you about the Rangers.}
{401}{}{These upstarts are endlessly standing in our way, interfering with our work. Have you managed to find their weak spots yet?}
{402}{}{No, sir. They are far too well-organized.}
{403}{}{It's hard to expect something like this from a simple peasant. But I'm confident, given enough time, you'll succeed. Keep me in the know.}
{1403}{}{It's hard to expect something like this from a simple peasant. But I'm confident, given enough time, you'll succeed. Keep me in the know.}
{404}{}{Permission to leave?}
{405}{}{How are the Rangers interfering with your work? Don't they also represent the Law, just like you?}
{406}{}{Firstly, they consider us to be invaders and are setting the population against us. This directly interferes with our plans. Secondly, they are holding back progress. Things like sabotaging caravans and work camps. Finally, they are aggressively expansionist and their territory has gotten very large. They even tax the population in the lands they control. Who the hell do they think they are?!}
{407}{}{Maybe they have their reasons?}
{408}{}{Sounds similar to another organization that wants to control the region, wouldn't you agree?}
{409}{}{If they do, it doesn't matter. They aren't letting us connect California and Arizona. They have shown their villainy in the Battle for Nogales, when they tried to ruin our relations with the tinsmiths and force us out of the region. This alone shows there can be no negotiation with them.}
{410}{}{Permission to leave, general?}
{411}{}{I managed to undermine the Ranger dam.}
{412}{}{I was already told. Good job. With your help, we'll drive these invaders out of Arizona and restore order. We'll make things here like they were back then, before the War.}
{413}{}{And our agreement?}
{414}{}{Of course. From this day forward, Villa is under our protection. We'll send an ambassador to the village to sign an alliance.}
{415}{}{Good news.}
{416}{}{And more than that, for your service to the United States of America, I am offering you an opportunity to become a member of the Brotherhood of Steel. No civilian has received such an honor before. But I am endowed with special powers and see much potential in you. Think about it and go back to me when you decide. Dismissed.}
{417}{}{Thank you, general Dickson.}

{420}{}{I want to join the Brotherhood.}
{421}{}{Bend your knee and say your name.}
{422}{}{I am }
{423}{}{ of Villa. I swear allegiance to the Brotherhood of Steel.}
{424}{}{Choose who you want to be.}
{425}{}{I want to be a scribe and carry the wisdom of the Old World.}
{426}{}{I want to be a paladin and bring death to enemies of the Brotherhood.}
{427}{}{I want to become a knight, to carry the light of technology.}
{428}{}{I want to become a scout, that way I will be the most useful for the Brotherhood.}
{429}{}{Let it be so. }
{430}{}{ of Villa. From this moment on, you are a respected member of the Brotherhood of Steel. Do not disgrace our name. Honor our laws. Stay faithful to the day of your death.}
{431}{}{I swear I will stay faithful to the Brotherhood until the day of my death.}
{432}{}{Even though I promised to give you a rank in our order, it turned out that there are rumours being exchanged between our brothers, concerning you. They don't say anything good. I will have to delay this until the day when you prove yourself once again.}
{433}{}{Dammit. Reputation is a harsh mistress...}
{434}{}{Only those who have commited extraordinary feats can join our order. And your feats are nowhere near the level of extraordinary we're looking for.}
{435}{}{I'll do everything in my power to change that.}
{436}{}{Fine. You'll hear about it all later, general.}
{437}{}{Your help to the Brotherhood has proved itself invaluable. I'm ready to accept you into our order.}
{438}{}{[Continue]}