{100}{}{This is Paladin Dobbs.}
{101}{}{You see a strong unshaven man.}
{102}{}{Watch the rear, rookie.}
{103}{}{Return to the base and report the results to Paladin Latham. Are free.}
{104}{}{It was an honor to fight with you.}
{105}{}{A tribunal awaits you!}

{200}{}{How long can I wait for you, soldier? You get paid for service, not sightseeing!}
{201}{}{I'm sorry, sir! But I, uh, need to take a leak, sir! I'll be back soon, sir!}
{202}{}{What kind of slack locals you all are. I'll give you five minutes, rookie!}
{203}{}{Copy that, sir!}
{204}{}{Arrived for the operation. Waiting for further instructions.}
{1204}{}{Arrived for the operation. Waiting for further instructions.}
{205}{}{Everyone! Listen to me! We have an enemy camp in front of us. Our main goal is to free the caravan driver who was taken hostage. We need him alive. Bandits - neutralize by all available means. Any questions? Moving into position!}
{206}{}{Yes, sir.}
{207}{}{Listen to me! The hour has come for a glorious battle! This time we have a well-fortified enemy fort in front of us. Be careful, there may be traps around the perimeter, and when entering the ruins, keep an eye on the rear. Our main goal is to get information about the location of the bandit base. After that, we have to destroy the camp. Any questions? Let's move out!}
{208}{}{Soldiers! It's time for you to become real American heroes! In front of us is the main base of bandits. We have been trying to find it for a long time, and finally succeeded. It's time to burn out all the mole-rat offspring from there! Come on, brothers and sisters! For the glory of the Brotherhood!}
{209}{}{Yes!}
{210}{}{...Wait. There is a separate task for you. Find the cargo that the raiders captured from the caravaneers.}
{211}{}{You're just in time.}
{212}{}{We've been waiting for you.}

{220}{}{Report.}
{221}{}{Report the situation.}
{222}{}{What's the matter, rookie?}
{223}{}{Going ahead, sir.}
{224}{}{[CHEAT: I have completed my task]}
{225}{}{Now go to our base with a report for Paladin Latham. Have a good trip.}
{226}{}{It will be done, Sir Dobbs.}

{230}{}{I need fire support. Follow me...}
{231}{}{I'll go on alone so as not to attract attention. Wait for the signal.}
{1231}{}{Then I'll go alone, so as not to attract attention. Wait for the signal.}
{232}{}{Stop, rookie! How dare you leave the area of the operation without permission? Did you at least complete the task? Well? I'm waiting for an explanation!}
{1232}{}{Stop, rookie! How dare you leave the area of the operation without permission? Did you at least complete the task? Well? I'm waiting for an explanation!}
{233}{}{No, I failed the assignment. Excuse me, Sir paladin...}
{1233}{}{No, I failed the assignment. Excuse me, Sir paladin...}
{234}{}{A deserter! A tribunal awaits you! Not another step to the base!}
{235}{}{As you say, sir...}
{236}{}{I don't care.}

{240}{}{Remind me what my task is.}
{241}{}{I should have listened to the briefing more carefully, rookie! Find the hostage and take him to a safe place - to the evacuation point. That's your main task, we'll figure out the rest.}
{242}{}{Find out information about the location of the main bandit base. Beat that information out of anyone or find some fucking map, soldier. Get the fuck moving!}
{243}{}{Find the cargo that the bandits stole from the caravaneers. Among the things there should be a valuable pre-war relic. We have to get her back to base. Your participation in the fighting is not necessary. Is everything clear? Good luck, soldier.}
{244}{}{I see.}
{245}{}{The hostage is safe.}
{246}{}{Very good. It would be an unforgivable luxury to lose such a valuable caravan.}
{247}{}{Glad to try.}
{1247}{}{I'm glad to try.}
{248}{}{The hostage died. I'm sorry, sir.}
{249}{}{Died? Damn it... So, now we have no reason to be polite to these scum.}
{250}{}{As you say, sir...}
{251}{}{I managed to find out where the base is located.}
{252}{}{Great job, rookie. That's why we came here.}
{253}{}{I managed to get a sacred relic. Here she is, Sir Dobbs.}
{254}{}{Great job, warrior!}