{100}{}{You see a caravan driver.}
{101}{}{You see a man in dusty clothes. It looks like he walked many miles in it.}
{102}{}{Only after you.}
{103}{}{Thank you for your help, soldier.}

{200}{}{Hey! You're from the Brotherhood, aren't you? Well, finally, I thought you had abandoned me.}
{201}{}{How dare you doubt the honor and valor of the order?}
{202}{}{Actually, it's because of your order that I got into this mess. So it's YOU who owes me. Now get me out of here to a safe place immediately.}
{203}{}{Okay, let's go. I'll take you to the evacuation point from where we launched the attack.}
{204}{}{You'd better keep your head down for now. Close your ears and wait for it to be over.}
{205}{}{The brotherhood cares about you. My orders are to escort you to a safe place.}
{206}{}{Very good. I rely on your experience, soldier. But if the shooting starts, I'll run wherever I look.}
{207}{}{Let's go. Paladin Dobbs demands to take you to a safe place.}
{208}{}{Then you'd better sit here until this is over. Wait for my instructions.}
{209}{}{Hide here and keep your head down. I need to assess the situation.}
{210}{}{Where are your paladins? I'm already getting uneasy.}
{211}{}{We're here. Paladins will pick you up here after the operation is completed.}
{212}{}{Clear. Thank you for your help, soldier. I thought I'd never see a brahmin's ass on a scorching road again.}
{213}{}{Happily.}

{220}{}{Tell me about the attack.}
{221}{}{We were carrying cargo for the Brotherhood from the Tinsmiths. The bandits somehow tracked us down before we spent the night in Casa Nueva. But they were in no hurry to attack they were gathering people from all over the desert. As a result, halfway to Puerto, we were simply squeezed into a ring and crushed by a huge crowd. There was no escape.}
{222}{}{What was in the cargo you were taking to Puerto?}
{223}{}{Some kind of fucking electronics. I don't understand it. But the Brotherhood demanded especially careful handling of some items.}
{224}{}{What do you know about the attackers?}
{225}{}{Local renegades. Judging by their accents, they came from the south or lived here before the Brotherhood came.}
{226}{}{I see. Enough talking for now.}