{100}{}{You see Corwin.}
{101}{}{In front of you is the kitchen attendant. He hums a silly song about beans and beans under his nose.}
{102}{}{Now is not the time to chat with the locals.}
{103}{}{?}

#(Cook hums the words from the movie "Deserters" 1950)
{110}{}{ˆ Beans... pea... green bean.. beans... ˆ}
{111}{}{ˆ In morphlot, everyone is friendly and strong. ˆ}
{112}{}{ˆ After all, they eat cutlets, pasta and dumplings... ˆ}
{113}{}{ˆ ...And the landsmen eat garbage. ˆ}
{114}{}{ˆ Morphlot gets first-class trout. ˆ}
{115}{}{ˆ ...And to the landsmen - one bean. ˆ}
{116}{}{ˆ Beans... pea... green bean.. Beans... }
{117}{}{ And this sausage is as hard as a paladin's hand. ˆ}
{118}{}{ˆ Morphlot is served on the table with napkins and salt... ˆ}
{119}{}{ˆ ...And one bean for the landsmen. One bean. ˆ}

{200}{}{Na-na-na... Loo-boo-doo... Cough-cough-cough... Ugh.}
{201}{}{Hey.}
{202}{}{Ah! What? What is it? Don't scare me like that.}
{203}{}{What are you doing?}
{204}{}{Me? I sing...}
{205}{}{And you call this singing?}
{206}{}{Don't you like it very much?}
{207}{}{I really don't like it.}
{208}{}{But I can't change the voice... And who are you? I haven't seen you before.}
{209}{}{None of your business, Private. Keep working.}
{210}{}{What are you. The main thing is that you like it. I'm just here in passing.}
{211}{}{Exactly. Who are you anyway? I haven't seen you before.}
{212}{}{I have recently been in the service of the Brotherhood.}
{213}{}{Oh, congratulations. Can I continue working?}
{214}{}{Of course, go on, novice.}
{215}{}{A civilian. I have a security clearance.}
{216}{}{Well, it's none of my business. But no outsiders are allowed in the kitchen.}
{217}{}{Of course, I'm coming out now.}
{218}{}{Don't distract him.}
{219}{}{See you later.}

{220}{}{Novice Corwin, se... Oh, it's you.}
{221}{}{Do you really have a security clearance?}
{222}{}{You're lucky, you can go to the wastelands whenever you want. And I've been waiting for a furlough for a hundred years.}
{223}{}{Na-na, na-na, boo-boo, boo-boo...}
{224}{}{Beans... pea... green bean.. beans...}
{225}{}{Did they send you from the infirmary? I don't like all these needles.}
{226}{}{"Hurry up, Corwin!", "Wash up, Corwin!", "Boo-boo-boo, Corwin". Big bosses...}

{229}{}{Hi... So... Novice Corwin, sir!}
{1229}{}{Hi... So... Novice Corwin, ma'am!}

{230}{}{I was told you can have lunch here. I'm a rookie.}
{231}{}{Ah, welcome to the ship. Here's your lunch. And you will have to pay for the supplement with a salary. Here are the rules.}
{232}{}{Thank you, novice.}
{233}{}{And it seemed to me that the Brotherhood would be fed better than in a roadside eatery.}
{234}{}{Can I buy food from you?}
{235}{}{Absolutely not. Without an order, I can only sell surplus to Brotherhood employees.}
{236}{}{Sorry. Apparently, there's nothing you can do about it.}
{237}{}{You just missed an opportunity to get rich. Fool.}
{238}{}{Come on, you probably have a surplus lying around.}
{239}{}{Listen, you can get your neck slapped for this case. And you're not even from the Brotherhood. Get out of here, don't bother me cooking.}
{240}{}{Fool, you just missed an opportunity to get rich. For now.}
{241}{}{}
{242}{}{Come on, no one will notice the loss of a couple of plates of soup, and you will get caps.}
{243}{}{Wow, that was good. You can't buy much on my salary. The main thing is that no one finds out.}
{244}{}{Of course. Everyone will get their own, Corwin.}
{245}{}{Everything is fine. I have permission.}
{246}{}{Well, that's another thing then.}
{247}{}{Thank you.}

{250}{}{What's your name, Private?}
{251}{}{Alvin Corwin. Currently on duty in the kitchen.}
{252}{}{Working in the kitchen is a disgrace for a paladin.}
{253}{}{No, I'm not a paladin. I haven't decided on a division yet.}
{254}{}{Are you a paladin or a scribe?}
{255}{}{Absolutely not. I haven't decided on a division yet.}
{256}{}{Then why aren't you in school?}
{257}{}{I'm serving my sentence. I missed morning training because I was looking for the sergeant all morning.}
{258}{}{Of course. Who will put a good soldier in the kitchen.}
{259}{}{Are you kidding me? I wanted to ask for a shore leave, so I was looking for the sergeant all morning, but he was nowhere to be found.}
{260}{}{Is it so hard to study?}
{261}{}{I need to rest. I was on leave a hundred years ago.}
{262}{}{What an injustice. So it's not even your fault that you got into this mess?}
{263}{}{Exactly. I urgently need a shore leave, but no one could sign the petition. So I ran all over the ship.}
{264}{}{What if I ask for a leave of absence for you? What will I get for it?}
{265}{}{Can you? Oh, I'll pay with provisions then. Or I'll share my cartridges.}
{266}{}{It's been noticed. Consider the order already in your pocket.}
{267}{}{And the truth is, I have neither connections nor authority. It's unlikely to work.}
{268}{}{I can get an order for you. Or at least I'll try.}
{269}{}{Can you? You are my last hope.}
{270}{}{And yet you can try.}
{271}{}{Come to think of it, I can hardly do it. Be.}
{272}{}{About the leave ticket.}
{273}{}{Did you really succeed?}
{274}{}{No, to be honest.}
{275}{}{Why do you need a shore leave? There's nothing but desert all around.}
{276}{}{No, there is a settlement of Casa Nueva in the west. Our people are on patrol there and sometimes rest. Nice place, lots of people, fresh air. Not like this rusty vessel. At noon it's so stuffy here that you walk around in your underpants.}
{277}{}{Clear. Well, have a good stay.}
{278}{}{Yes, I keep thinking, but how would you get a leave of absence? Any ideas?}
{279}{}{But HOW can I get you a furlough?}
{280}{}{But why would you go to a deserted beach?}
{281}{}{I would have known, I would have begged for it long ago. In general, such orders can only be signed by higher ranks. And you can also get an order for a task from one of the divisions. But inexperienced people like me don't like to be sent on free assignments. How to carry heavy things is always welcome. And as soon as the orders are taken to the camp, half of the squad gets in line.}
{282}{}{The order has been issued. You're free for the next four days.}
{283}{}{Wow, that's news! Are you serious?}
{284}{}{It's true. It's my joy to help people.}
{285}{}{What kind of jokes? I'm serious. But you have to pay for everything.}
{286}{}{But I'll need caps on the shore. Let me share the bullets? These armor-piercing ones have never been useful to me anyway.}
{287}{}{Great, I'll find a use for them.}
{288}{}{Thank you. I'll go to the sergeant, let him burst with envy.}
{289}{}{Come on, have a good trip.}

{300}{}{What are you doing, Private?}
{301}{}{Cooking beans, sir.}
{1301}{}{Cooking beans, ma'am.}
{302}{}{Beans? And that's it?}
{303}{}{Well yes. Novices are not given a good ration. Paladins eat the best.}
{304}{}{Is that why everyone here looks unhappy?}
{305}{}{They have it. And I have to cook it. Of course, we are supplied with fish, meat, and maize flour. But there are supply failures, and sometimes there are not enough stocks. Eh, now I would like to roast a good steak.}
{306}{}{Well, I go to different places.}
{307}{}{Hey, can you get some coffee? We would have folded and paid for each jar.}
{308}{}{Okay. If I find it, I'll bring it.}
{309}{}{This rarely comes across. I don't think I'll find at least one jar.}
{310}{}{I can't help you with anything. Bye.}
{311}{}{Look what I have. This is a can of real coffee.}
{312}{}{Super! Sell it to me. I'll pay }
{313}{}{ caps per jar.}
{314}{}{Well, no. I want to, too. I won't give it.}
{315}{}{A profitable exchange. In settlements, they pay less for coffee.}
{316}{}{Thank you. If there's more, bring it to me right away.}
{317}{}{Okay.}
{318}{}{Take it for free. So I want to thank the Brotherhood of Steel.}
{319}{}{Thank you. All of our people will appreciate such generosity.}
{320}{}{You are welcome. All for you guys.}
{321}{}{Cooking pasta, sir.}
{1321}{}{Cooking pasta, ma'am.}
{322}{}{Pasta? Is that all?}