{100}{}{This is Raymond.}
{101}{}{You see the quartermaster of the Brotherhood of Steel. He looks through the lists through a large eyepiece mounted on his forehead.}
{102}{}{Now is not the time to chat with the locals.}
{103}{}{?}
{104}{}{ Damn it, I've already told you a hundred times - don't go into the warehouse in power armor! You're like death claws in a pottery shop here.}

#Floating replicas
{110}{}{We need to fill out the ammunition lists.}
{111}{}{Next time I will personally make you wash this dirt.}
{112}{}{The Brotherhood of Steel highly appreciates my signature.}
{113}{}{This rust makes my nose ache.}
{114}{}{The effectiveness of grenades is greatly overestimated.}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}

#Dialog
{200}{}{Oh, a new face on the ship. It's always interesting. Can I help you with something?}
{201}{}{Nothing today. Maybe another time.}
{202}{}{Well, maybe. Tell me, what is this place?}
{203}{}{This is the main ship's warehouse. And I'm his quartermaster. My name is Knight Raymond.}
{204}{}{It is an honor to meet you, Knight Raymond.}
{205}{}{I see.}
{206}{}{Ah, just a warehouse. And I thought there would be something interesting here.}

{210}{}{So how can I help?}
{211}{}{I'll come back later.}
{212}{}{Do you mind if I ask you a few questions?}
{213}{}{About what?}
{214}{}{Just idle curiosity.}
{215}{}{How can I help you, brother?}
{1215}{}{How can I help you, sister?}

{220}{}{I got a medal for bravery. Do you know anything about it?}
{221}{}{Let me take a look... Operation Anchorage? Of course, it was one of the most striking victories of the United States before the Great War. The armed forces of America entered the battle against the red invaders in Alaska. However, this did not save us from nuclear bombing.}
{222}{}{It looks like it's not just a story for you.}
{223}{}{The Brotherhood of Steel consists of the descendants of the military. Including those who participated in that battle. We use power armor, which was first used in the operation at Anchorage. Listen, you don't need this medal, do you? I want to get it for the story. What do you want in return?}
{224}{}{What kind of medal? Show me.}
{225}{}{I'll bring it later.}
{226}{}{350 caps.}
{227}{}{What a banality. Here are the bottlecaps.}
{228}{}{Thank you.}
{229}{}{Take it for free. I just want to help the Brotherhood of Steel in its difficult task.}
{230}{}{I think the brothers in arms will appreciate it. Thank you. If you need any of my products, you can count on a small discount.}
{231}{}{That's pretty good. I will keep in mind.}
{232}{}{What I really need is the ability to shoot from an army weapon. Heavy battles are ahead.}
{233}{}{Then shooting in our shooting range with a training weapon will help you. I'll arrange everything.}
{234}{}{That's what you need...}
{235}{}{The quartermaster reduced the cost of his goods by 10%.}

{240}{}{Can you tell me about the Brotherhood?}
{241}{}{Talk about it with the scribes or the general himself. If they don't want to talk, then I certainly shouldn't.}
{242}{}{Good. I'll find someone else.}
{243}{}{Okay, let's talk about something else?}
{244}{}{Remind me, what is this place?}
{245}{}{This is the main ship's warehouse. And I'm his quartermaster. My name is Knight Raymond.}
{246}{}{Thank you, I'll remember it now.}
{247}{}{What are these strange 10 mm cartridges? It's the first time I've seen them.}
{248}{}{This is our own development. The bullet in them consists of a particularly strong alloy and has an unusual piercing shape. Just right against well-protected enemies. Let such enemies be rare, but it is better to have a clip in reserve with you.}
{249}{}{I see.}

{250}{}{Can I see what you have?}
{251}{}{Of course. All the best for you.}
{252}{}{Do you want to exchange? The Brotherhood is not interested in one-time spontaneous bidding. We prefer permanent caravans. But if your things will be useful to us, then I can offer something.}
{253}{}{Something? I need a really good weapon!}
{254}{}{The commanders believe that good weapons and explosives can be directed against us. I'm sorry, but you'll have to be content with what they offer until you earn more trust.}
{255}{}{And how is it usually deserved?}
{256}{}{By deed, obviously.}
{257}{}{Clearly.}
{258}{}{Okay, let's go.}
{259}{}{About the caravans. I can also become a caravan driver.}
{260}{}{Maybe, but we need regular suppliers.}
{261}{}{You will not be fooled...}
{262}{}{I have a lot of trading partners all over Arizona. I can attract many good caravans here.}
{263}{}{That's how? Well, you've convinced me. I think I'll include you in the list of our suppliers.}
{264}{}{Thank you.}
{265}{}{Everything is fine. I have a clearance from the general himself.}
{266}{}{Really. I recall such an order. You can count on the full range.}
{267}{}{Thank you.}
{268}{}{Come on, Raymond. Everyone here knows that I can be trusted.}
{269}{}{Yeah... Okay, I'll put you on the list of our suppliers.}
{270}{}{Thank you.}
{271}{}{Everything is fine. I have a clearance from the Supreme clerk.}
{272}{}{Everything is fine. I have a security clearance from the patrol commander.}
{273}{}{We just lost one of our troops there. Talk about it with the patrol chief at the entrance to the ship.}
{274}{}{OK.}
{275}{}{I managed to find this token in the ruins of Inferno.}

{280}{}{I came across the tokens of the Brotherhood. What to do with them?}
{281}{}{Each token speaks of a fallen brother or sister. A sad fate. Tell me how this token got to you, and I will redeem it for 10 caps.}
{282}{}{Perhaps the caps will be useful to me.}
{283}{}{Take it for free. I don't want to profit from someone else's tragedy.}
{284}{}{Thank you. Every token is important to us.}
{285}{}{I understand. But I still have questions.}
{286}{}{Please.}
{287}{}{General Dixon promised a reward for delivering the report.}

{288}{}{Yes, that's right. A warrant has already been issued in your name. Your fee is 250 caps, as well as stimpacks (three pieces) and Radaway (two pieces). Get it and sign it.}
{289}{}{Thank you.}

{290}{}{Do you have any magazine for my grenade launcher?}
{291}{}{Yes, there is a drum magazine for this model. Literally one thing. I will install for }
{292}{}{ caps.}
{293}{}{A big store will increase my chances of survival. Do it. Here are the bottlecaps.}
{294}{}{Not yet.}

{300}{}{It seems that I should be given service equipment here.}
{301}{}{That's right. Welcome to the Brotherhood, rookie.}
{302}{}{What am I supposed to do?}
{303}{}{Your equipment depends on your specialization and rank. Everything that does not belong to the service set, you will have to buy or beg for specific tasks. Of course, my warehouse is now fully open for you, and the prices are much lower than for civilians. So what kind of equipment do you need?}
{304}{}{Can we postpone the issue for a while? I need to clarify something. Goodbye.}
{305}{}{Scribe's kit.}
{306}{}{Great. Here are your things: a laser pistol with a supply of batteries for it, a decoder, a Geiger counter. Get it and sign it.}
{307}{}{Paladin Set.}
{308}{}{You like big guns, don't you? The young are often eager to become paladins. Here are your weapons: a light machine gun, a box of cartridges for it and combat armor. Get it and sign it.}
{309}{}{Knight's Set.}
{310}{}{Ah, so you and I are in the same rank, brother. Very good. Here's your gear: a power screwdriver, a super hammer, and rubber boots. Get and sign.}
{311}{}{Scout Kit.}
{312}{}{A smart choice, considering you're from the wasteland, too... Oh, I'm sorry, I don't mean to offend you. Here's your gear: a rocket launcher with ammo, a shock glove, stealth combat. Get it and sign it.}
{313}{}{Thank you, Knight Raymond.}
{314}{}{Is that all? Okay, that'll do, too.}

{320}{}{It seems that the lost power armor needs to be handed over here?}
{321}{}{Ah, the one we've been waiting for for so long? Is she here with you?}
{322}{}{She's, uh, nearby. Wait until I stomp it on the ship.}
{323}{}{Yes, here it is. I return it to you, the rightful owners.}
{324}{}{Ah, look how the chrome glitters in the light of the lamp! There is nothing more beautiful among the old technologies than this war machine... Yes, and thanks for the help. The brotherhood appreciates your action.}
{325}{}{Unfortunately, she got a little battered on the ruins of Inferno.}
{326}{}{I see. It's not a big deal. The damage is quite fixable, although the recovery process may take a couple of weeks.}
{327}{}{And if I need this armor again?}
{328}{}{Of course, we are grateful for her return. But this armor is the property of the Brotherhood of Steel. And you have no rights to it. However, the general can take into account your merits and issue a permit. Talk to him. In the meantime, I'll have to do the repairs. Damn, and what a fool tore off this part...}
{329}{}{An order has already been received in your name. You can exercise your sacred right to wear power armor... when I finish fixing it. Damn, and what a fool tore off this part...}
{330}{}{I'll drop by in a couple of weeks.}
{331}{}{I just want to know if I can use it after I return it?}
{332}{}{What a stupid question? This is the property of the Brotherhood of Steel. And to use it, you need to have a permit or be a member of our union. But first you need to RETURN the armor to the warehouse. Go ahead, don't waste your time.}
{333}{}{Yes, there she is. I am handing over to the rightful owners.}
{334}{}{Wait until I stomp it on the ship.}
{335}{}{Oh, so this is the one that was taken through the ruins of Inferno? Just fine. Come on, crawl out of it, I can't wait to do an inspection.}
{336}{}{It will take some time, maybe while we talk?}
{337}{}{Oh, of course, now I will get rid of this shell.}

{340}{}{Have you finished repairing the power armor?}
{341}{}{No. It's not as easy as it seems.}
{342}{}{Okay.}
{343}{}{Oh yeah. Looks like new!}
{344}{}{Can I take it?}
{345}{}{I need this armor for business.}
{346}{}{What a stupid question? This is the property of the Brotherhood of Steel. And to use it, you need to have a permit or be a member of our union.}
{347}{}{Okay...}
{348}{}{An order has already been received in your name. You can exercise your sacred right to wear power armor.}
{349}{}{Thank you... Yes, she looks better now.}