{100}{}{You see the instructor.}
{101}{}{This is a junior paladin. At every opportunity, he shouts commands and blows the whistle.}

{200}{}{Civilian? Stop talking!}
{201}{}{Whatever you say.}
{202}{}{Wait. What is this place?}
{203}{}{Obviously, this is a training hall! What do you have a head for, stupid?}
{204}{}{You need a head to hit it, sir.}
{205}{}{Idiot! Go out into the corridor and don't come back!}
{1205}{}{Idiot! Go out into the corridor and don't come back!}
{206}{}{As you say, sir...}
{207}{}{Oh, I see, and I'm looking for a toilet...}
{208}{}{Wow, can I do one of the workouts?}
{209}{}{Wait, I also want to participate in training.}
{210}{}{Idiot! This is a military base, civilians are not allowed to appear here at all.}
{1210}{}{Idiot! This is a military base, civilians are not allowed to appear here at all.}
{211}{}{Ah, well, then let's pass. Goodbye.}
{212}{}{Isn't there some way around these formalities? I have a lot of bottlecaps. Let's say 500 pieces.}
{213}{}{Hmm. Good. Let's see how much you have enough, lizard. What are you trying to achieve anyway?}
{214}{}{It doesn't matter yet. I'll get the caps first.}
{215}{}{Shooting with small arms.}
{216}{}{Shooting with heavy weapons.}
{217}{}{Shooting with energy weapons.}
{218}{}{Hand-to-hand combat technology.}
{219}{}{The technology of combat with cold weapons.}
{220}{}{The technology of throwing grenades and blades.}
{221}{}{I should go through one of the training sessions. After all, now I am a paladin of the Brotherhood.}
{222}{}{I should go through one of the training sessions. After all, now I am a scout of the Brotherhood.}
{223}{}{For ME, you're still a smelly sucker who can't be trusted with sticks for stirring shit! Now stand still and name your specialty, soldier!}
{1223}{}{For ME, you're still a smelly rag that can't even be trusted with a mop! Now stand still and name your specialty, soldier!}
{224}{}{I, uh, need to check with my commanding officer. Give me a minute, sir.}
{225}{}{Don't whine, don't piss, don't call your mom! You can go to the front line. Step march!}
{226}{}{Yes, sir!}