{100}{}{In front of you is a Pockmarked one.}
{101}{}{You see a ghoul. It looks like he's in a lot of pain. If it wasn't for your bike, the poor guy wouldn't have been hurt.}
{102}{}{Where did you get your driver's license? In a TV box?}
{1102}{}{Where did you get your driver's license? In a TV box?}
{103}{}{Oh shit!}

{110}{}{Oh-oh-oh! How painful!}
{111}{}{Ouch! My hip joint!}
{112}{}{Has anyone seen my gallbladder?}
{113}{}{My spine! My spine!}
{114}{}{Doctors...}
{115}{}{Can anyone help me?}
{116}{}{Why is this happening to me?}
{117}{}{First a truck, then a pickup truck, and now a bike...}
{118}{}{This is already becoming the norm...}
{119}{}{}

{200}{}{Oh, oh, how it hurts! Well, why do I always find myself under the wheels?}
{201}{}{Oh, I'm sorry, are you all right?}
{202}{}{Are you okay? Well... A couple of fractured vertebrae, a crack in the hip joint, a torn bladder... yes. I'm totally fine.}
{203}{}{Sorry, I didn't mean to.}
{204}{}{Of course not on purpose! I told those freaks that road signs were needed here. And they never listen! Like when I was run over by a hefty truck with a core-Cola. Bottle caps were scattered all over the desert.}
{205}{}{It's terrible.}
{206}{}{Wow! Imagine if someone came across this in the middle of the desert.}
{207}{}{Or else... Gr-rh! Oh! I hate to interrupt this wonderful conversation, but I still need to get up somehow. Will you help?}
{208}{}{Are you sure?}
{209}{}{Are you sure? Maybe you shouldn't move now...}
{210}{}{Oh, don't worry. Sooner or later, everything will grow together by itself. Okay. Good luck, man.}
{211}{}{Bye.}
{212}{}{Oops...}
{213}{}{What, are you going to stare? Aren't you going to give me first aid and mouth-to-mouth breathing? Okay. I'll get up without you somehow.}
{214}{}{Well, thank God. It seemed to me that you were really sick. Well, see you later.}
{215}{}{Damn it, I can barely move! No, don't think about it, I'm not whining at all. It's been worse. Like when I was run over by a hefty truck with a core-Cola. Bottle caps were scattered all over the desert.}