{100}{}{You see a doctor.}
{101}{}{You see a doctor. If it wasn't for the robe, you wouldn't have distinguished him from an ordinary soldier.}
{102}{}{If I don't hurry up, then I won't need the services of a doctor anymore.}
{103}{}{?}

{200}{}{(he rubs his hands, carefully examining you) A civilian? I don't remember the order about recruits.}
{201}{}{Yes, I don't serve the Brotherhood.}
{202}{}{We have an infirmary here. And I am forbidden to serve civilians without an appropriate order.}
{203}{}{Sorry to distract.}
{204}{}{Clear. Goodbye.}
{205}{}{So are you the rookie?}
{206}{}{Yes, I'm a rookie. The enrollment order has already been issued.}
{207}{}{Good. Because otherwise, I would have thrown you out of the infirmary. Civilians are not allowed to appear here.}
{208}{}{I just need treatment.}
{209}{}{It won't be necessary. I'm leaving anyway.}

{210}{}{What happened?}
{211}{}{Nothing. See you later, doc.}
{212}{}{Is something wrong?}

{213}{}{Can I ask you a few questions?}
{214}{}{Not worth it. The position of a military doctor taught me to keep my mouth shut in peacetime. Except, of course, conversations with senior officials. They need to know everything about everything.}
{215}{}{Okay, Doc, in that case, I'll look for another victim.}

{220}{}{I want to talk about Novice Corwin.}
{221}{}{What about him? Is this bugger in some kind of trouble again?}
{222}{}{He needs a shore leave.}
{223}{}{What, again? The guy is too flimsy for this kind of work. They shouldn't have taken him with them. I would sit at the base and clean my guns. But what does that have to do with me?}
{224}{}{I don't even know. I just wanted to discuss it with someone. Goodbye.}
{225}{}{It occurred to me that you could write him a discharge ticket for health reasons.}
{226}{}{Could. But why would I do that?}
{227}{}{Probably not for anything. I'm sorry to distract you for nothing. Bye.}
{228}{}{Well, I can get some medical supplies. You must be missing something.}
{229}{}{Good. Bring five stimpacks or one of the army drugs, and then your friend will get a ticket from me.}
{230}{}{I will think about this proposal.}
{231}{}{Here are five stimpacks.}
{232}{}{I can share psycho.}
{233}{}{I have a buffout.}
{234}{}{That's enough. Good deal.}
{235}{}{I'm going to please the novice.}

{240}{}{Hey, Doc. I was recently enlisted in the Brotherhood's intelligence squad.}
{241}{}{So, great. That is, now I will have more work. Well, congratulations on the promotion.}
{242}{}{What's wrong with the scouts?}
{243}{}{Scouts are most often exposed to radiation and poisoning. Therefore, you consume medicines the most and even take them with you on the road. And medicines are hard to get in our conditions. Especially Radaway.}
{244}{}{So, wait, do I get some kind of set of medications?}
{245}{}{Radaway, antidote, and stimpack - here is your survival kit. Spend it wisely, or even better - avoid dangerous places altogether.}
{246}{}{Okay. Thanks, Doc.}

{250}{}{Can you fix me up, Doc?}
{251}{}{I'm not allowed to serve civilians without a special order. Otherwise, we may not have enough medicines ourselves. Turn to the Followers of the Apocalypse in Casa Nueva, they will cure anyone for just one kiss.}
{252}{}{Thanks for the referral. I will try not to die before I get there.}
{253}{}{And it immediately became clear to me that ordinary citizens mean nothing to you. Goodbye, knacker.}
{254}{}{Treat me, doc.}
{255}{}{You're all right now. Now take your rifle and go back to the front line.}
{256}{}{It will be done, Doc!}
{257}{}{Stupid joke, smartass.}

{260}{}{What's that shouting, Doc? Are you torturing someone?}
{261}{}{Oh no. This is our valiant soldier going crazy. Severe case with acute mental disorder.}
{262}{}{What is the expression of his illness?}
{263}{}{The patient cannot serve due to insomnia and headaches. He even claims to hear voices in his head... Just a minute. I can't discuss this with outsiders. Although the case is complicated.}
{264}{}{Maybe he's faking it?}
{265}{}{What about? For the Brotherhood soldier to fake it? I do not think so. But it is not excluded. Lately, everyone in our fort has been homesick in California.}
{266}{}{If you can't handle it, let me try.}
{267}{}{Hmm, otherwise I'd spank you and throw you out the door. But this problem cannot be solved without outside help. I'm not a psychologist, but what can you do?}
{268}{}{I need to talk to the patient first. Give me five minutes, Doc.}
{269}{}{Are you sure he's not faking it?}
{270}{}{And what is the expression of his illness?}
{271}{}{Surely you know how to cure it. Goodbye, doc.}
{272}{}{It looks like Bell is suffering from severe psychological trauma.}
{273}{}{I've already figured that out. But what to do?}
{274}{}{He was talking about some kind of ash desert. What could it mean?}
{275}{}{Hmm. I don't even have any ideas. Actually, the disease manifested itself after one of the forays into the desert. Talk to his companions in the mess, perhaps they will be able to unravel this image.}
{276}{}{Okay, goodbye, doc.}
{277}{}{After your conversation, Bell became calm. He had a good night's sleep and was refreshed. What did you tell him?}
{1277}{}{After your conversation, Bell became calm. He had a good night's sleep and was refreshed. What did you tell him?}
{278}{}{Nothing special. Just good old-fashioned psychotherapy.}
{279}{}{That's how. Interesting. I wish I could succeed in this business. I'm more into lacerations and contusions. And it's a little scary to climb into the subconscious.}
{280}{}{All is not lost yet, doc.}
{281}{}{That's for sure. Better mind your own business.}
{282}{}{Thank you. I also want to share my medical experience with you. Here, take this surgical kit and a couple of stimpacks as a token of gratitude.}
{283}{}{Thanks, Doc. Goodbye.}