{100}{}{You see Paladin Latham.}
{101}{}{You see a strong unshaven man.}
{102}{}{Well, no, not now.}
{103}{}{?}

{200}{}{Wait. This is a closed area, civilians are not allowed to enter the base.}
{201}{}{Civilian? Are you some kind of army?}
{202}{}{No. We are an ancient order called the Brotherhood of Steel. Although we do have military discipline at our base.}
{203}{}{I see. And who are you?}
{204}{}{It's amazing. And with whom do I have the honor to speak?}
{205}{}{I am Paladin Latham, chief of Patrol. Any more questions?}
{206}{}{Not at all, sir.}
{207}{}{Oh, I have a lot of questions. But you still won't answer them.}
{208}{}{Okay. Now tell me, amigo, what brought you to us?}
{209}{}{I'm from a village in the north. We were attacked by slavers, and now I'm trying to save the village...}
{210}{}{That's exactly what I need. My village was enslaved by slavers, and I'm trying to save it...}
{211}{}{I'm sorry, but I won't bother the general about one village. We just don't have time for this.}
{212}{}{No, you don't understand. You are the slavers. I'll destroy your whole gang!}
{213}{}{What's going on? What's the fuss?}
{214}{}{I see. I see they won't help me here. Permission to go, paladin?}
{215}{}{You again? I told you - we don't have time to deal with your village. Sorry, but we don't have time for this yet.}
{216}{}{There is an enemy army coming from the south, mutants in the west, and a complete mess in the east. We recently lost a squad in the north and can't even send a rescue team there.}
{217}{}{And if I help you, will you let me see the general?}
{218}{}{Can you help me? Are you for us? Haha, the peasant wants to help the Brotherhood! Did you guys hear that? Okay, let's see what happens.}
{1218}{}{Can you help me? Are you for us? Haha, the peasant woman wants to help the Brotherhood! Did you guys hear that? Okay, let's see what happens.}
{219}{}{So what's up with the squad?}
{220}{}{There are ruins of a big city in the north. We call them Infernos. A convoy was coming through the ruins to us. But the connection was interrupted, now we don't know anything about the fate of the squad.}
{221}{}{I see. Anything else?}
{222}{}{Go there and find out what happened to our brothers. But be careful, the scribes say there are places with high levels of radiation.}
{223}{}{Good. I'll do it.}
{224}{}{Agreed. But you can't get away from me, Paladin.}
{225}{}{M-mutants... Ugh! When will you all rest?}
{226}{}{Give me a minute, boss, I'm not doing anything wrong.}
{227}{}{Oh, it won't be soon, my pale-skinned friend...}

{230}{}{What do you need?}
{231}{}{Nothing. Goodbye.}
{232}{}{What do you need, warrior?}

{240}{}{I need to know more about Inferno.}
{241}{}{I don't have much information. Scribes consider these ruins lifeless and warn of radiation near the site of a nuclear explosion.}
{242}{}{What can you say about the convoy?}
{243}{}{Several members of the Brotherhood were carrying important cargo from California. They should have been in touch a long time ago.}
{244}{}{Thank you, that's enough.}
{245}{}{Indeed - a little information.}
{246}{}{Let me take a little more of your time, paladin.}
{247}{}{I know what happened in Inferno...}
{248}{}{...The scribes were telling the truth - this is a CURSED place. Thank you. You need to talk to our general.}
{249}{}{By the general himself?}
{250}{}{He'll be interested in your story. I'll tell the guards to let you on the ship.}
{251}{}{Excellent.}
{252}{}{That would be right away.}
{253}{}{Okay, slow down. WHERE did you get this power armor from?}
{254}{}{It was a terrible place. Well, you know, dead people on the streets, ruins all around...}
{255}{}{It looks like a description of the Inferno through which our lost convoy passed. Have you come across people who carried this armor?}
{256}{}{Now I'll tell you what I know...}
{257}{}{I won't tell you anything. This is my trophy, and I won't give it up.}

{260}{}{Is there any other way I can help the Brotherhood?}
{261}{}{Did you say something about an enemy army?}
{262}{}{Yes, army units are pulling together from the south to the Mexican border. We don't know much about the new enemy yet. Even the location of the enemy general staff is unknown.}
{263}{}{But in the south there is an endless desert. Where would a military base come from there?}
{264}{}{It is this desert that keeps the enemy army from occupying Arizona. While holding back.}
{265}{}{I hope you can handle this threat. Adios.}
{266}{}{I can find out. I've always wanted to visit those parts.}
{267}{}{I can scout the southern lands if it helps.}
{268}{}{We sent several scouts to the south, but none of them returned. Still want to take a chance? Then go ahead. The brotherhood will pay for information about the objectives of the Mexican army.}
{269}{}{I'll be back when I find out something.}
{270}{}{There is a Mexican army fort in Hermosillo...}
{271}{}{...Great job! Your intelligence will give us an advantage over the enemy if it comes to an offensive.}
{272}{}{Hermosillo is quite far across the desert. I doubt that the Mexicans will reach these places in the near future.}
{273}{}{I don't care why you need it. Just a quid pro quo.}
{274}{}{Here, take the payment for the work. We value good scouts.}
{275}{}{Thank you.}
{276}{}{This loser claims that he owes his salvation to you. He wasn't much use. But what can you tell me?}
{277}{}{Jack said you need information about the Mexican army.}
{278}{}{So did you manage to go there? And what did you find out?}
{1278}{}{So did you manage to go there? And what did you find out?}
{279}{}{Honestly, nothing that would be useful to you. If I find myself there again, I will collect more detailed information.}

{280}{}{There is a request. Take Novice Corwin on your next patrol.}
{281}{}{Corwin? Why doesn't he apply himself?}
{282}{}{He's been begging for a shore leave ticket for a long time.}
{283}{}{Ah, that's the thing. No, we don't need ballast on the way. And even more so, I will not be convinced by the words of a crook like you.}
{284}{}{A crook, then? Okay...}
{285}{}{Ah, that's the thing. No, we don't need ballast on the way. And your authority in this matter does not change anything. I don't know you well enough to answer your requests.}
{286}{}{You can understand...}
{287}{}{Ah, that's the thing. Well, I listen to the requests of those who have shown themselves to be a worthy warrior. Tell Corwin I'll take him on patrol to Casa Nueva and back. It's not exactly a furlough, but it's enough for him to get some fresh air.}
{288}{}{Thank you, Paladin Latham. You've been very helpful.}
{289}{}{Here is a holo recording with the data that was stored in the computer of the General Staff. They're in Spanish.}

{300}{}{Let me know what your service does.}
{301}{}{This is a patrol service. We keep order in the neighborhood. Any more questions?}
{302}{}{No way, sir.}
{303}{}{Yes, let me ask you something.}
{304}{}{I understand that. But there's a desert all around. What order can be maintained here?}
{305}{}{First of all, we protect the caravan routes. There are fishing settlements on the coast under our protection. Sometimes requests come from Casa Nueva. And yes, even in such a wilderness there are bandits. You should always be on your guard.}
{306}{}{I see.}
{307}{}{Interesting. Will you take me on patrol?}
{308}{}{Taking a stranger on patrol is too dubious an idea. Even if your thoughts are pure.}
{309}{}{Okay. Maybe you'll change your mind when I do something important.}
{310}{}{You probably need experienced mercenaries. You said to yourself that there are not enough people.}
{311}{}{Yes, but you are clearly not the level of fruit to fight shoulder to shoulder with you. Start with something simpler.}
{312}{}{Yes, but you... However, we don't have enough people for one big operation.}
{313}{}{Great. Tell me what's what.}
{314}{}{Take me on patrol.}
{315}{}{The General was talking about you. I will be glad if you help us in one difficult operation.}
{316}{}{Sure. Tell me what's what.}
{317}{}{Is there any other way I can help the Brotherhood?}
{318}{}{After Hermosillo, I want to help the Brotherhood even more. Will you take me on patrol?}
{319}{}{Yes, we don't have enough people like you for one big operation.}
{320}{}{Great. I'm listening carefully.}
{321}{}{Bandits have been bothering us lately. They stuck to the main trade routes and local settlements. Recently they robbed one of our caravans, and this is no good at all.}
{322}{}{They don't know who they've contacted yet, Paladin Latham.}
{323}{}{They must be serious guys since they robbed the Brotherhood caravan.}
{324}{}{We tracked the attackers to one of their camps in the desert and want to visit them. It's time to pin the tail of these sons of bitches!}
{325}{}{Great. When are the fees?}
{326}{}{Go to the collection point, which I will indicate on the map. Field Commander Dobbs will meet you there and instruct you on the spot. And take care of your protection in advance. Good luck.}
{327}{}{Roger that. I'm leaving immediately.}
{1327}{}{The task is clear. I'm leaving immediately.}
{328}{}{Is it okay if they wait a bit? That's fine.}
{329}{}{Take me on patrol, Paladin Latham.}

{330}{}{Here is my report on the raid on the bandit camp...}
{331}{}{...Very good. Obviously, it was just a small field camp. After the attack on the caravan, the bandits split up. The second group took the goods to their main base. Rescuing a caravan is an important mission, but it is even more important to get the stolen cargo.}
{332}{}{So there is another sortie ahead?}
{333}{}{We don't know where the bandits' main base is. However, during the operation, information appeared about a large outpost on the ruins of Kaborka. This outpost must be destroyed anyway. And at the same time, you can get information about the location of the main base there.}
{334}{}{So what are the instructions, sir?}
{335}{}{Go to Commander Dobbs and give my next order.}
{336}{}{Yes, Paladin Latham.}
{337}{}{If there are no other leads, then it's worth taking the risk.}
{338}{}{Did I ask for your opinion? Ahem... Well, never mind. You're doing well. It would be a little harder for us without you.}
{339}{}{So what are the instructions, sir?}
{340}{}{...It turns out that the camp in Kaborka was organized only to attack our caravan routes. The main base of the bandits is in the mountains to the east. No wonder it took us so long to figure them out.}
{341}{}{So are you going to attack their general staff?}
{342}{}{The General Staff? It's just a group of rural bandits. Call it a den or just a hole.}
{343}{}{Acknowledged, sir.}
{344}{}{Give the commander the order to attack. This time the operation will be harder than the previous ones. Let him gather the best guys. You, too, take your best weapons and armor. Good luck, soldier.}
{345}{}{Yes, Paladin Latham.}
{346}{}{...So we set up their main camp. The bandits were destroyed, the leaders were caught and put to death, and the loot was returned to the order. Congratulations, warrior.}
{347}{}{Yes, the wastelands will remember this for a long time.}
{348}{}{It was a glorious day of victories! We have eradicated evil in these lands and once again showed the world our strength. After the defeat of the bandits, the roads will become safer, and the fame of the Brotherhood will spread further to the mainland. Thank you for your assistance.}
{349}{}{I serve the Brotherhood of Steel!}
{350}{}{I want to complain. I was excluded from the task force!}
{351}{}{And rightly so. If not for your previous achievements, you would have been executed to the fullest extent of the law. And now do the most reasonable thing you can - disappear from our base.}
{352}{}{Yes, sir.}
{353}{}{Gr-r!}
{354}{}{I have bad news - Commander Dobbs died during the operation.}
{355}{}{It's a bad thing. He was our best field commander. Besides, only he had a complete picture of what was happening, without him it would become much harder to defeat the bandits.}
{356}{}{But what about the operation?}
{357}{}{We will have to suspend the operation and reorganize the combat personnel. If we need you, we'll call. In the meantime, you can be free.}
{1357}{}{We will have to suspend the operation and reorganize the combat personnel. If we need you, we'll call. In the meantime, you can be free.}
{358}{}{Yes, sir.}

{360}{}{I need equipment to participate in the raid.}
{361}{}{Your equipment is your responsibility. All I can help is to give access to the goods of the quartermaster. Talk to him, maybe you can trade your gun for something stronger.}
{362}{}{And thanks for that.}