{100}{}{You see Paul.}
{101}{}{You see a very emaciated man.}

{200}{}{Glad to see you again, friend. Do you remember how you and I ran away from super mutants? It was great.}
{1201}{}{It's good to see you again, Sister. Do you remember how you and I ran away from super mutants? It was great.}
{201}{}{Yes, those were great times.}
{202}{}{I told the order about it, it seems to have improved the opinion of you. Also, as a token of appreciation, take three stimpacks and a laser pistol with batteries. Good luck on the wastelands.}
{203}{}{Thank you. Good luck.}

{210}{}{Welcome aboard. How can I help you?}
{211}{}{Nothing, thank you.}

{220}{}{Remind me, what rank are you in?}
{221}{}{I am the knight Paul. He used to be the head of the Energy Weapons Research Department. Then I was sent to fieldwork to help the paladins. And then I was captured by super mutants.}
{222}{}{Can I get a weapon here?}
{223}{}{Contact the quartermaster. I don't have a free weapon. But I can upgrade something.}
{224}{}{Work days for you. Be.}
{225}{}{Thank you. I have to go.}
{226}{}{I have to go. Goodbye.}
{227}{}{Thanks, I have to go now.}
{228}{}{Thanks for the information, come on.}
{229}{}{}
{230}{}{Will you help me save my village?}
{231}{}{I'm sorry, but I have duties at this port. And I've had enough adventures, perhaps.}
{232}{}{Do you have spare parts for power armor?}
{233}{}{I'm not good at it. Give the armor to the quartermaster, maybe he has spare parts. Although if you don't get along with him, then he won't give up the armor so easily.}
{234}{}{Is there another option?}
{235}{}{They say tinsmiths are capable of it. But I suspect that they will take off three skins for such a service.}
{236}{}{Look at this plasma rifle. Is there any way to improve it?}
{237}{}{It's a P94 Hard Drive! A fine weapon. Every time I admire its reliability and power. It always seemed to me that it couldn't be better.}
{238}{}{Go on.}
{239}{}{But you know, one man once showed me a unique upgrade of his rifle. The plasma in it was heating up faster than usual. I think I can repeat this experience here.}
{240}{}{Do it! Here's a rifle.}
{241}{}{No, thanks. What if you break something else...}