{100}{}{You see Christopher.}
{101}{}{You see a young military man with a very sad and thoughtful look.}
{102}{}{Watch out for super mutants, buddy.}

{200}{}{Hello... E... I didn't know there were civilians on board... e... Welcome aboard.}
{201}{}{It seems that your thoughts are far from here.}
{202}{}{Exactly. What are you mumbling about? Not in a military way somehow.}

{210}{}{Khym. I've been thinking about home. Junior Paladin Christopher. What can I do for you?}
{211}{}{Sorry for worrying. I'll leave.}
{212}{}{Junior Paladin Christopher. What can I do for you?}

{220}{}{You were talking about home. Is it far from here?}
{221}{}{Lost Hills Bunker. I was born and raised there. It's in California, far northwest of here. Convoys need at best a month to cover this distance. But usually much more.}
{222}{}{Tell me about life in the bunker.}
{223}{}{Bunker, you say? The man was born to live under the sun, not in dark basements.}
{224}{}{I miss the cute dark corridors and dangling wires. There, in the bunker, we had everything we needed - food, energy, even entertainment. And here we are free, but we live in terrible conditions.}
{225}{}{Don't you like Arizona?}
{226}{}{It is not proper for a soldier to whine about a change of location.}
{227}{}{A bare, suffocating desert for miles to Phoenix? No, thanks. I've already seen the sands in California. But there the sands were their own, native. Everything is alien here. And it will remain a stranger to most members of the Brotherhood.}
{228}{}{You just haven't seen all the local beauties.}
{229}{}{So you crawled out of your dark dungeon after all?}
{230}{}{I was called up to the punitive squad just at the moment of initiation. And as soon as I received the official title, it was at this time that the Creator's army began to seize the settlements. I was thrown into battles, as if from heaven to hell.}
{231}{}{Was it hard in battle?}
{232}{}{What, nerves are too weak for service?}
{233}{}{If it wasn't for the training, I wouldn't have been able to stand it. It's easier now. The hardest thing was to survive the loss of brothers in arms. I still keep this photo. Our whole squad before a sortie to the Necropolis. Out of seven people, two survived - me and the commander.}
{234}{}{Go on.}
{235}{}{It's not even worth starting.}
{236}{}{I pulled him out of the crossfire of super mutants and dragged him into the sewer at the last moment. After that, the mutants hit the hatch with a rocket, and the exit crumbled.}
{237}{}{I'm really sorry.}
{238}{}{You just got lucky.}
{239}{}{So the two of us survived. But other groups were already engaged in cleaning up the mutants... I'm sorry, I must have tired you with stories... You're not one of us anyway, you wouldn't understand... And in general, why am I talking to you? Okay, good luck in the desert, or whatever you're doing there.}
{240}{}{Thanks for the story. Sometimes it's worth talking out, even if you're in front of a stranger. Good luck, Paladin.}
{241}{}{Yes, I don't understand how someone like you is still alive. I hope they'll take you back to the dark bunker.}