{100}{}{You see the paladin.}
{101}{}{Short haircut, strong armor, pumped-up muscles - in front of you is a paladin of the Brotherhood of Steel.}

{200}{}{I report the situation: everything is calm.}
{201}{}{How is the service? We are still quiet.}
{202}{}{It's good to see you. But why aren't you on patrol?}
{203}{}{Do you want to join the patrol? Turn to Paladin Latham.}
{204}{}{There is no paladin more experienced than General Dixon. That's why he's here.}
{205}{}{We need soldiers like you.}
{206}{}{Welcome to the Brotherhood.}
{207}{}{*Salutes you*}
{208}{}{}
{209}{}{}

{210}{}{Go to the wastelands, savage.}
{211}{}{Your curiosity may cost you dearly.}
{212}{}{There is nothing to wander around a military base like at home.}
{213}{}{Do you have a pass? Your happiness that you have it...}
{214}{}{Just give me a reason - and you'll fly overboard in a jiffy.}
{215}{}{My tactic is simple - hit first until you get hit in the back.}
{216}{}{I'm just curious, who let you in?}
{217}{}{Now civilians are allowed to wander around the ship? Bar-rdak...}
{218}{}{Freely. I don't bite until they give me a reason.}
{219}{}{}

{220}{}{In our Brotherhood they say: "A good ally is a dead ally."}
{221}{}{Wait, do you have a pass? Show me...}
{222}{}{Better not piss me off, stupid redneck.}
{223}{}{Showing up here unannounced and demanding answers? There's something wrong with your head.}
{224}{}{Stay here and don't move until I find out who you are and how you got through the guards.}
{225}{}{Well, well, we've got a rat here...}
{226}{}{I don't negotiate with civilians.}
{227}{}{Does the guard know that you're on the ship?}
{228}{}{What, a stranger on board? I give you five seconds to explain, otherwise...}
{229}{}{Do you even realize that you're on a warship?}

{230}{}{Did something happen?}
{231}{}{You need to talk to our commander.}
{232}{}{This is a closed area. You can't be here without permission.}
{233}{}{What brought you to the Brotherhood?}
{234}{}{Do you want to join the Brotherhood?}
{235}{}{We don't normally accept outsiders into the order, but there have been exceptions.}
{236}{}{Where are you from?}