{100}{}{You see a sentry in front of you.}
{101}{}{You see a man in power armor. Looks impressive.}
{102}{}{Now is not the time to chat with the locals.}
{103}{}{?}
{104}{}{You're taking a big risk coming back here.}
{105}{}{Greetings, brother in arms. How was the patrol?}

#The first dialog
{200}{}{Wait. Name the purpose of your visit.}
{201}{}{It doesn't matter, I'm already leaving.}
{202}{}{I'm traveling along the coast, and here you are. It became interesting, what would it be for?}
{203}{}{You don't want to know. Go your own way.}
{204}{}{You don't seem friendly.}
{205}{}{Wait... What the hell are you staring at? We don't need drug addicts here. Get out of here and don't come back. Come on, move...}
{206}{}{Uh... uh...}
{207}{}{Closed? How is that? I don't know.}
{208}{}{So. We've got a little crazy here. Not enough convolutions, eh? You should have our clerks put tests on you. But I don't want to get dirty. (menacingly) Get out of here.}
{209}{}{Oh, go. I understand that. Yes.}

#Repeat dialog
{210}{}{You can pass.}
{211}{}{Thank you.}
{212}{}{Greetings, brother in arms.}
{1212}{}{Greetings, sister in arms.}
{213}{}{See you later, brother.}
{214}{}{(mockingly evaluates your armor) Come on in. The galley just lacks a lid for the pan.}
{215}{}{Can I come on board?}
{216}{}{Are you still asking? Of course, come in, brother.}
{1216}{}{Are you still asking? Of course, come in, Sister.}
{217}{}{Thank you, brother.}

{220}{}{Can I ask you a few questions?}
{221}{}{I am forbidden to have idle conversations, especially about our Brotherhood.}
{222}{}{Clearly. Well, you can't trample on the charter. Goodbye.}
{223}{}{What are you doing here?}
{224}{}{Guarding the ramp. Outsiders are not allowed to board without permission. And you don't have it.}
{225}{}{What are you doing here?}
{226}{}{What is this place?}
{227}{}{This is our fort. If these are all questions, then you'd better leave. Nothing to distract the sentries on duty.}
{228}{}{OK, I'm leaving.}
{229}{}{Then tell me, what is this place?}
{230}{}{You guys are cool. I want to join you.}
{231}{}{Don't count on it.}
{232}{}{Ugh, he said how he cut it off.}
{233}{}{Maybe you have a job for me?}
{234}{}{I don't think so. But talk to the head of the patrol service, maybe he has a task for you.}
{235}{}{Okay, thanks.}
{236}{}{Wait. Can I ask you a few questions?}

{240}{}{I need to meet with your command.}
{241}{}{On what issue?}
{242}{}{It's, uh, personal. Can I pass?}
{243}{}{No.}
{244}{}{Very sorry.}
{245}{}{I'll find a way anyway, you'll see.}
{246}{}{OK, you can pass.}
{247}{}{Thank you.}
{248}{}{While you're inside, keep your gun holstered, and don't do anything stupid. The general's office is on the middle deck, the warehouse is to the left of the entrance. It is strictly forbidden to enter the other compartments. Is that clear?}
{249}{}{I see.}

{250}{}{I was sent by Master Hard from Two-Sun. Here is his recommendation.}
{251}{}{A report from Ulysses Grant. Personally for General Dixon.}
{252}{}{Paladin Latham permitted me to meet the general.}
{253}{}{General Dixon is waiting for me. This concerns the fort in Hermosillo.}
{254}{}{It's probably a problem to get some raw materials in this fort. And my caravan is idle.}
{255}{}{I have a lot of great products for sale. Interested?}
{256}{}{No, we don't deal with solitary pilgrims.}
{257}{}{Very sorry.}
{258}{}{It's clear to me. But you should clean your armor. You look like a rusty bucket.}
{259}{}{Paladin Latham permitted me to meet with the quartermaster.}