{100}{}{You see a guard.}
{101}{}{You see a man in power armor. He looks fantastic.}
{102}{}{Now is not the time to chat with locals.}
{103}{}{?}
{104}{}{You're risking much by coming back here.}
{105}{}{Welcome, brother-in-arms. How did your patrol go?}

#First dialogue
{200}{}{Stop. State the purpose of your visit.}
{201}{}{Nevermind, I'm already on my way.}
{202}{}{I'm traveling along the coast, minding my own business, then I see you fellas. And I became curious, what are you doing here?}
{203}{}{For you, it's better not to know. Go on the path you were traversing.}
{204}{}{Not particularly welcoming.}
{205}{}{Stop... What the hell are you looking at? We don't need junkies here. Get outta here and don't come back...}
{206}{}{Ugh... Uhh...}
{207}{}{Closed? How? I don't see how.}
{208}{}{Well, well, well. We've got a somewhat slow one. It's in the brains, right? Not enough of them. The scribes should be running tests on you. But you'd just make a mess. (threatening) Go to some different place.}
{209}{}{Oh, go to other place. I understand. Yes.}

#Repeated dialogue
{210}{}{You can go inside.}
{211}{}{Thank you.}
{212}{}{Welcome, brother-in-arms.}
{1212}{}{Welcome, sister-in-arms.}
{213}{}{See you, brother.}
{214}{}{(examines your armor, chuckling) You can go in. We just lost a saucepan lid.}
{215}{}{Can I get inside of the vessel?}
{216}{}{You're still asking? Of course, go right in, brother.}
{1216}{}{You're still asking? Of course, go right in, sister.}
{217}{}{Thank you, brother.}

{220}{}{Can I ask you a few questions?}
{221}{}{I'm forbidden from having idle conversation, especially about our Brotherhood.}
{222}{}{Welp, rules are rules. Goodbye.}
{223}{}{What is it you do here?}
{224}{}{Guarding the ladder, obviously. Outsiders cannot get inside of the vessel without permission. Which you don't have.}
{225}{}{What's your job here?}
{226}{}{What is this place anyway?}
{227}{}{It's our fort. If you're done with your questions, you better go. You shouldn't distract guards.}
{228}{}{Alright, I'm going.}
{229}{}{Then tell me, what is this place?}
{230}{}{You look like cool fellas. I wanna join you.}
{231}{}{Don't count on it.}
{232}{}{Damn.}
{233}{}{Maybe you have some job I can do?}
{234}{}{I don't think so. But talk to the patrol chief, maybe he'll find you an assignment.}
{235}{}{Got it, thanks.}
{236}{}{Wait. Can I ask you a few questions?}

{240}{}{I need to see your leader.}
{241}{}{For what reason?}
{242}{}{It's, uhh, personal. Can I go in?}
{243}{}{No.}
{244}{}{How unfortunate.}
{245}{}{I'll find a way, you just wait.}
{246}{}{Good, you can come onboard.}
{247}{}{Thank you.}
{248}{}{While you are inside, keep your weapon holstered and don't do anything stupid. The general's office is on the middle deck, the warehouse is to the left of the entrance. Entering other compartments is strictly forbidden. Understood?}
{249}{}{Understood.}

{250}{}{I was told to go here by Master Khard of Two Sun. Here is his letter of recommendation.}
{251}{}{A report from Ulysses Grant. For general Dickson himself.}
{252}{}{Paladin Latam has given me permission to meet the general.}
{253}{}{General Dickson is waiting for me. This is about the Hermosillo fort.}
{254}{}{Your fort must have problems getting some materials. And my caravan is just sitting there doing nothing.}
{255}{}{I have many fine goods I am willing to sell. Interested?}
{256}{}{No, we do not deal with lone pilgrims.}
{257}{}{How unfortunate.}
{258}{}{Oh, I know. And you should clean your armor. You look like a rusty bucket.}
{259}{}{Paladin Latam has given me permission to see the quartermaster.}
