{100}{}{You see the clerk.}
{101}{}{Here is an ordinary clerk of the Brotherhood of Steel.}

{210}{}{What are you doing here? Who let you on board?}
{211}{}{Don't distract me, I'm doing important research.}
{212}{}{Welcome to the Brotherhood. Now do something useful.}
{213}{}{Would you like to talk about science?}
{214}{}{Is your heart open to quantum physics?}
{215}{}{Do you accept the teaching of our Isaac Newton, who took an apple blow from our ignorance, our misunderstanding, yes, for our fears?}