{100}{}{You see Maura.}
{101}{}{You see the supreme clerk of the Brotherhood of Steel.}
{102}{}{I'm not up to talking right now.}
{103}{}{}

{110}{}{Ah, I miss Sofia's lectures.}
{111}{}{Sometimes I miss Vreya's advice.}
{112}{}{There have been no letters from Lost Hills for a long time.}
{113}{}{Nonsense. Experiments in Casa Nueva are safe.}
{114}{}{It's inhumane, but research is more important than the life of one Aboriginal.}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}

#The first dialog
{200}{}{Wait. Do you have access to the ship?}
{201}{}{I don't have a security clearance. I don't need him. Got it?}
{202}{}{That's how. Interesting. Stand still and don't twitch. I'll summon the paladins now... Stop, I say! Damn...}
{203}{}{Oh, oh...}
{204}{}{Yes, I have permission. It's all right.}
{205}{}{In that case, greetings, stranger. I am Maura, the supreme scribe of the Brotherhood of Steel. Civilians are not often allowed here. What are you doing on our ship?}
{1205}{}{In that case, greetings, stranger. I am Maura, the supreme scribe of the Brotherhood of Steel. Civilians are not often allowed here. What are you doing on our ship?}
{206}{}{I have an important mission.}
{207}{}{Good. But still, I will find out from the sentries why you were missed.}
{208}{}{I count on your loyalty, Clerk Maura.}
{209}{}{Better mind your own business, clerk.}

#Repeat dialog
{210}{}{Greetings, stranger.}
{1210}{}{Greetings, stranger.}
{211}{}{Greetings, brother.}
{1211}{}{Greetings, sister.}
{212}{}{Goodbye.}
{213}{}{Let me ask you a few questions?}
{214}{}{Hmm. Perhaps I can tell you something.}
{215}{}{No more questions.}

#Questions
{220}{}{I met a prisoner on the way.}
{221}{}{Yes, we use the prisoners' labor to rebuild the ship. Don't talk to them.}
{222}{}{A very rational decision.}
{223}{}{A person has committed a crime and is serving a sentence. He was given a second chance. Let him be grateful for our mercy.}
{224}{}{However, he says that he took only a few cobs on a huge plantation.}
{225}{}{First of all, this is not an excuse. And secondly, criminals are always trying to belittle their guilt. Of course, he does not admit that there were more cobs or that the robbery also took place in city houses. The usual thing.}
{226}{}{I understand now. May I ask another question?}
{227}{}{Either that or you are covering up your slaveholding ambitions.}
{228}{}{Nonsense! History shows well that forced labor is effective only in the short term. Besides, there is no need to resort to such measures when there are so many real criminals around. Grab any of them and make them benefit society. Here's a reasonable approach.}
{229}{}{Perhaps you are right.}
{230}{}{Well, well, tell me more.}
{231}{}{Is it humane to put a collar on him and make him work?}
{232}{}{Humane? A person has committed a crime, let him be grateful for the preservation of his worthless life.}
{233}{}{He says that he took only a few cobs on a huge plantation to survive.}
{234}{}{Can you tell me who is who on the ship?}
{235}{}{So you're not the one behind slavery in Arizona?}
{236}{}{No, of course not. However, I know that some of our allies sometimes abuse their position. It's just a cost.}

{240}{}{Tell me about this ship.}
{241}{}{This vessel is the destroyer Vokelgazing DD-1862. Length 130 yards, width 13.6, draft 4.77 ... Ah, if this car was on the move, it would develop a speed of up to 35 nautical knots.}
{242}{}{Sounds cool. What else can you tell me?}
{243}{}{Destroyer - what does it mean?}
{244}{}{That there are several damn nuclear torpedoes on board the ship, each of which is capable of destroying a small city. Any soldier on a ship dreams of seeing such an explosion. But, fortunately, there was no reason for this yet.}
{245}{}{This ship can't go to sea?}
{246}{}{Just not now. The ship will not have enough nuclear fuel for a long voyage. In addition, repair of old equipment and housing is required. We knew it was a one-way voyage until we set up a base in this port.}
{247}{}{Why are some doors blocked?}
{248}{}{There are reasons. Some things on the ship require particularly careful care. But even among their own mistakes happen. Therefore, there are places where only the Supreme Paladin Dixon has access.}
{249}{}{I see. Thanks for the answers.}

{250}{}{Tell me about the Brotherhood of Steel.}
{251}{}{What exactly do you want to know about our order?}
{252}{}{Enough talk about the Brotherhood. Now I know enough.}
{253}{}{Where did you all come from?}
{254}{}{We came from California. Previously, they sat quietly in their bunker and did not meddle in worldly affairs. But our time has come. This is just one of our remote outposts.}
{255}{}{Tell the story of the Brotherhood.}
{256}{}{Well, General Maxon gathered us during the Great War and brought us to the old military base. We went through the hardest times there. Several generations have passed, and now his descendant rules our ranks.}
{257}{}{What is your mission? What are you trying to achieve in the end?}
{258}{}{The main goal of our order is the search and preservation of ancient technologies to someday restore order to the lands of a once great country. However, there are numerous disputes about this in the order. For a long time we did not dare to start our "crusade", only recent events in California forced us to reconsider our strategy and come out of the shadows.}
{259}{}{Countries? What country are we talking about?}
{260}{}{United States of America.}
{261}{}{What are these events in California that you mentioned?}
{262}{}{A big story about the Creator and his army. Do you want to know the details?}
{263}{}{Yes, please tell me.}
{264}{}{This story doesn't interest me. We'd better change the subject.}
{265}{}{Um, let's go back a bit.}
{266}{}{Thank you. This concludes the conversation about the Brotherhood.}
{267}{}{Since I am now also a member of the Brotherhood, I want to hear an honest answer. What is the management really trying to achieve?}
{268}{}{I didn't say that, but our main goal in Arizona is to get nuclear material for the general staff in California. The General Staff needs other resources as well. Without them, the order will last for some time, but sooner or later our isolation will come to an end. And then the Brotherhood will be forced to take drastic measures to provide for itself.}
{269}{}{That is, first the order needs to survive, for which the locals can go to the expense. Oh, yes, I understand now.}

{270}{}{The creator is a tyrant. Considering himself something like a god, he opened his church and created a cult around his person. His sect included many people. Some of them were used as material for experiments. The most successful copies subsequently made up the personal army of the Creator.}
{271}{}{An army of super mutants? The Creator must have been pretty damn smart.}
{272}{}{And, of course, you didn't want to share power with the dictator?}
{273}{}{Our scouts studied the situation, risking their lives. The church was destroyed. The army is defeated. The remnants of the army settled in the wastelands, but our detachments quickly found them and erased them from history.}
{274}{}{It looks like you know how to wage war. If you think about it, no one in modern Arizona can compare with you.}
{275}{}{Arizona doesn't know problems of this magnitude yet. You're lucky we're here. However, we have slightly different goals.}
{276}{}{Thank you so much for the story.}
{277}{}{Oh, great. Great. Uh, bye.}
{278}{}{}
{279}{}{I do not believe. Surely the Brotherhood has embellished its merits.}
{280}{}{Are you saying I'm lying? When you're in California, ask the locals. However, everyone in the Wastelands will say that it was he who detonated the nuclear bomb. Like, for example, that story with the Vault-Seeker who was just our mercenary.}
{281}{}{Indeed, it is not a good idea to believe private rumors.}
{282}{}{Exactly. Your words are nothing more than your words.}

{288}{}{What kind of person is he?}
{289}{}{Be afraid of Dixon. It is enough for him to snap his finger to turn someone's village into dust. That's all you need to know, Native.}
{1289}{}{Be afraid of Dixon. It is enough for him to snap his finger to turn someone's village into dust. That's all you need to know, native.}
{290}{}{Can you tell me about your commander-in-chief?}
{291}{}{General Dixon is one of the supreme paladins of the Brotherhood. His combat and political experience will be the envy of any modern ruler.}
{292}{}{Eh, I see.}
{293}{}{General Dixon is one of the supreme paladins of the Brotherhood. Only a few people in the entire order have such extensive experience in conducting combat operations and long campaigns away from home. The Brotherhood Council trusts him.}
{294}{}{And you?}
{295}{}{Thank you. I shouldn't know more.}
{296}{}{He's a fighter, and I'm a clerk. Because of this, we often do not find understanding. Dixon does not tolerate bureaucracy and is prone to solving problems quickly. It is easier for him to capture than to negotiate.}
{297}{}{And the General Staff trusts a stubborn soldier?}
{298}{}{The Council of Elders does not approve of some of Dixon's measures. But our outpost is too far from the general Staff and performs too complex a task to rely on conventional methods. Therefore, the general is endowed with special powers that greatly untie his fists. And I think it is quite justified.}
{299}{}{Thank you. This clarifies a lot.}
{300}{}{I think I'm under your command now. I am also a clerk.}
{301}{}{I'm glad you're choosing enlightenment over guns. Let me help you in this endeavor.}
{302}{}{I'm listening.}
{303}{}{Oh, please.}
{304}{}{This is an analytical neuro link for a Pip Fight. The standard model used by our scribes. Use it to be more attentive and smarter.}
{305}{}{Thank you, Sister Maura. I will use this valuable gift for the benefit of the Brotherhood.}
{306}{}{Well okay. Maybe it will come in handy somewhere.}

#Belief in mistakes
{310}{}{That is, you are ordinary invaders.}
{311}{}{I don't understand why I have to listen to this. Should I call the paladins to get you kicked off the ship?}
{312}{}{I apologize. I got a little overreacted...}
{1312}{}{I apologize. I got a little overreacted...}
{313}{}{Does it really hurt your eyes? You will not change this by my exile.}
{314}{}{You can't shut me up! And just try it - I'll chew everyone's throat out!}
{315}{}{In other words, you have come to take what does not belong to you.}
{316}{}{You should choose your expressions more carefully. And no, the Brotherhood doesn't think so. Thanks to Dixon's sensitive policy, Arizona got an opportunity to develop. The local savages have education, medicine, and production at a level that has not been here for almost a hundred years. Isn't this a miracle?}
{317}{}{Maybe a miracle. Or maybe it's a mirage?}
{318}{}{It's hard to argue with this. You got it, Scribe Maura.}
{319}{}{Propaganda doesn't work on me, clerk. Have a good stay.}
{320}{}{Are you still not going to calm down? You better calm down before I summon the paladins.}
{321}{}{I apologize. I don't want any trouble. Goodbye.}
{322}{}{Weak argument, clerk. Goodbye.}
{323}{}{General Dixon is wrong. You know that perfectly well.}
{324}{}{Perhaps. But what do YOU mean by saying he's wrong?}
{325}{}{Dixon is playing an inhumane game. Through his vassals on the ground, he imposes tyranny, seizes resources, takes technology, and practices slavery.}
{326}{}{I don't even know what to say. Perhaps we'll leave it on his conscience.}
{327}{}{Partly I agree. However, all these are forced measures. The locals have lost their roots in the Old World. They went wild and lost their hearts. Without our intervention, it will take centuries before they can return to the bosom of civilization.}
{328}{}{I don't know who to believe. Let me think a little.}
{329}{}{I have visited many settlements. Your influence on these lands is not as unambiguous and majestic as you present it.}
{1329}{}{I have visited many settlements. Your influence on these lands is not as majestic as you present it.}
{330}{}{Really? Didn't our henchmen in Phoenix establish peace and order in this city? Didn't our intervention give Arizona a cap currency? Didn't the Two-Sun caravan routes and Flagstaff mines provide a lot of jobs?}
{331}{}{Not without that. But your expansion does not so much give people freedom and development, as it breeds slavery and destroys traditions.}
{332}{}{Indeed, there is no arguing. So I wash my hands of it.}
{333}{}{Hmm. Give me examples from the places you've been.}
{334}{}{Let's do without it for now. I don't want to go that far into this argument.}
{335}{}{Aaron, having risen to power in Phoenix, creates an empire and burns out dissent. What kind of freedom is there?}
{336}{}{A whole war broke out in San Brahmin. Is that what you wanted?}
{337}{}{Two-Sun's tinsmiths are very strong. They take technology from others and condemn people to death in Sacred Mines.}
{338}{}{Casa Grande. Visit the local cemetery to see how technology has doomed the population to bloody wars over water.}
{339}{}{Casa Nueva is like a paddock with a herd of Brahmins. Without you, these people are weak-willed and helpless.}
{340}{}{Well, I doubt our way too. But I couldn't find a solution that could satisfy everyone.}
{341}{}{Really?}
{342}{}{This outpost has done too little good for Arizona. We have no right to parasitize on foreign lands, take resources from local residents, and force them to work for their greatness. This is contrary to the spirit and principles of the order.}
{343}{}{That's right.}
{344}{}{And this is not so much a mistake of the order or the elders, as the result of Dixon's ambitions. But it cannot be stopped, and the new general is unlikely to change course.}
{345}{}{It's very good that you have seen the light. But I think we've gone too far in our conversation. Let's finish with this.}
{346}{}{We must stop this evil. Help me.}
{347}{}{I am so sorry. But I can't help.}
{348}{}{Goodbye, Scribe Maura.}
{349}{}{We must stop this evil. Help me. Your mistakes led to the fact that my native Villa fell victim to slave owners.}
{350}{}{I am so sorry. Take this key. He launches nuclear torpedoes in the lower hold of the ship. Set the time before the explosion and run as fast as you can into the desert. The Brotherhood has no place in the lands of Sonora.}
{351}{}{Thank you, Scribe Maura.}
{352}{}{Act, dear friend}