{100}{}{You see Deckie.}
{101}{}{You see a boy. Aged about five.}
{102}{}{When I grow up, I'll wear that kind of armor, too.}
{103}{}{Don't come any closer! I'll defend myself!}

{200}{}{Hi. I haven't seen you before.}
{201}{}{And won't see you again. Bye.}
{202}{}{Well of course you haven't, you silly boy. I'm right from the desert.}
{203}{}{What, you live in the desert? So weird. I wouldn't live there. What's your name?}
{204}{}{Give me your name first, kiddo.}
{205}{}{}
{206}{}{. And you?}
{207}{}{Hey there, kid. What's your name?}
{208}{}{State your name, slob.}
{209}{}{My name is Deckie, sir.}
{1209}{}{My name is Deckie, ma'am.}
{210}{}{Good training, Deckie. You've got an unusual name.}
{211}{}{My parents named me that. I don't know why.}
{212}{}{What idiots gave you a name like that?}
{213}{}{My parents. They're not idiots. They're better than outsiders like you.}
{214}{}{Where are your parents, by the way?}
{215}{}{Somewhere around here. My dad is paladin Latham. Mom's somewhere on the shore. Washing his clothes, probably.}
{216}{}{What, your mom washes paladin underpants?}
{217}{}{She's not a paladin. She doesn't have a rank.}
{218}{}{Is your mom a paladin, too?}
{219}{}{Not at all, sir. She doesn't have a rank.}
{1219}{}{Not at all, ma'am. She doesn't have a rank.}
{220}{}{Wait a minute. So you're a son of a paladin and a peasant? Is that allowed?}
{221}{}{My dad is the best! He can do anything!}
{222}{}{Curious norms here.}

{250}{}{Oh, hi.}
{251}{}{Deckie ready for tasks!}
{252}{}{Are you really from the Brotherhood?}
{253}{}{What rank do you have?}
{254}{}{}
{255}{}{Bye, youngster.}

{260}{}{Remind me again, who are you?}
{261}{}{I'm Deckie. My dad's a paladin, and my mom is a peasant. Do you understand now?}
{262}{}{Yeah.}
{263}{}{What do you do on this ship?}
{264}{}{Various stuff. They constantly give me tasks. Bring this, bring that.}
{265}{}{I see.}
{266}{}{What are you doing right now?}
{267}{}{Looking for my animal. I don't know where he might be. He's small, has four paws. If you find him, bring him back to me, okay?}
{268}{}{Sorry, I definitely don't have time for games right now.}
{269}{}{I could take a look for you. Where do you think he could be?}
{270}{}{Well, I was all over the ship. I don't know.}
{271}{}{Hmm. This doesn't help much.}
{272}{}{Is this the toy you were looking for?}
{273}{}{Yeah! That's the one!}
{274}{}{Here, take it. And don't lose it anymore.}
{275}{}{Thank you, sir...}
{1275}{}{Thank you, ma'am...}
{276}{}{No problem.}
{277}{}{You know, in the Wastes, people get paid for work. What can you give me in return?}
{278}{}{(hesitantly takes out a magnetic keycard)}
{279}{}{A magnetic keycard for doors? That's all? Fine, hand it over.}
