{100}{}{You see the Cabin Boy.}
{101}{}{You see a boy about five years old.}
{102}{}{When I grow up, I will also wear such armor.}
{103}{}{Stay away! I will defend myself!}

{200}{}{Hello, I haven't seen you before.}
{201}{}{And you won't see it again. So far.}
{202}{}{Well, of course, I haven't, silly. I'm straight from the desert.}
{203}{}{What, do you live in the desert? How strange. I wouldn't live there. And what is your name?}
{204}{}{First name yourself, ignoramus.}
{205}{}{My name is }
{206}{}{. And you?}
{207}{}{Hello, boy. What's your name?}
{208}{}{Tell me your name, you slob.}
{209}{}{My name is the cabin boy, sir.}
{1209}{}{My name is, Cabin boy, ma'am.}
{210}{}{Good training, Cabin Boy. You have an unusual name.}
{211}{}{That's what my parents called me. I don't know why.}
{212}{}{What kind of idiots called you by that name?}
{213}{}{That's what my parents called me. And they're not idiots. They're better than outsiders like you.}
{214}{}{And by the way, where are they, your parents?}
{215}{}{Somewhere here. Paladin Latham is my dad. And Mom is somewhere on the shore. Probably washing his underwear.}
{216}{}{What, does your mom wash the underpants of the paladins?}
{217}{}{She's not a paladin. She has no rank at all.}
{218}{}{Is your mom a paladin too?}
{219}{}{Not at all, sir. She has no rank.}
{1219}{}{No way, ma'am. She has no rank.}
{220}{}{Wait a minute, so it turns out that you are the son of a paladin and a peasant woman? Is it possible?}
{221}{}{My dad is the best! He can do anything!}
{222}{}{Curious mores here.}

{250}{}{Oh, hello.}
{251}{}{The cabin boy is ready for tasks!}
{252}{}{Are you really from the Brotherhood?}
{253}{}{And what rank are you in?}
{254}{}{}
{255}{}{Bye, youngster.}

{260}{}{Remind me again, who are you anyway?}
{261}{}{I am a cabin boy, my dad is a paladin, and my mom is a peasant. Is it clear now?}
{262}{}{I see.}
{263}{}{What are you doing on this ship?}
{264}{}{Well, everyone. I am constantly given some tasks. Bring this, bring that.}
{265}{}{I see.}
{266}{}{What are you doing now?}
{267}{}{I'm looking for my beast. I don't know where he's gone. A small one, with four paws. If you find it, give it back to me, okay?}
{268}{}{Sorry, I'm not up to games right now.}
{269}{}{I can search for you. Where do you think he might be?}
{270}{}{Well, I've been running all over the ship. I don't know.}
{271}{}{Yeah. This clarifies a little.}
{272}{}{Is this the toy you were looking for?}
{273}{}{Yes! It's her!}
{274}{}{Here you go. And don't lose any more.}
{275}{}{Thank you, sir...}
{1275}{}{Thank you, ma'am...}
{276}{}{Please.}
{277}{}{We usually get paid for work in the wastelands. What can you give me in return?}
{278}{}{(hesitantly takes a magnetic card out of his pocket)}
{279}{}{A magnetic door key? Is that all? Okay, give it here.}

{280}{}{Run away from here. It's going to get very hot here soon.}
{281}{}{What are you talking about, sir?}
{1281}{}{What are you talking about, ma'am?}
{282}{}{Don't waste your time! If you don't want to die, then I advise you to hide away from here in the ruins.}
{283}{}{Just kidding. Ha-ha. Never mind.}
{284}{}{*whimper-whimper*}
{285}{}{Sp... thank you...}