{100}{}{You see Graham.}
{101}{}{You see one of the Brotherhood knights.}
{102}{}{Stop. Show me your clearance.}

#First dialogue
{200}{}{Hey, outsider. Even if they gave you clearance, that doesn't mean you can waltz around the ship and distract people from work.}
{1200}{}{Hey, outsider. Even if they gave you clearance, that doesn't mean you can waltz around the ship and distract people from work.}
{201}{}{I'm sorry, I was just terribly curious. This place is so unusual...}
{202}{}{Amazing, isn't it? A real warship. With a big, well-trained and well-armed team. Tell me, outsider, have you ever seen something more spectacular? That's right. You haven't.}
{1202}{}{Amazing, isn't it? A real warship. With a big, well-trained and well-armed team. Tell me, outsider, have you ever seen something more spectacular? That's right. You haven't.}
{203}{}{Work? You're not doing any work, you're just sitting here doing absolutely nothing.}
{204}{}{This entire base only functions thanks to me and my efforts. But of course, a desert primitive like you wouldn't understand. You simply cannot comprehend the greatness of Old World technology. Tell me, outsider, have you ever seen something more spectacular? That's right. You haven't.}
{1204}{}{This entire base only functions thanks to me and my efforts. But of course, a desert primitive like you wouldn't understand. You simply cannot comprehend the greatness of Old World technology. Tell me, outsider, have you ever seen something more spectacular? That's right. You haven't.}
{205}{}{Who are you, by the way?}
{206}{}{I'm knight Graham. I operate the equipment here. I'm on a small break right now, so ask what questions you have, if you have any.}
{207}{}{Nice to meet you, Graham.}
{208}{}{Okay.}
{209}{}{Now I know who's responsible for this junk lying around.}
{210}{}{Ah, here goes our new hero. The damn desert upstart who's better than all the veterans combined. Impressive. But don't you think you'll be accepted into the Brotherhood that simply.}
{211}{}{I understand your suspicion. I'll do everything in my power to make the Brotherhood accept me.}
{212}{}{Then mark these words well: Many swore on blood they wouldn't betray our Brotherhood. Those who tried to - have paid for it. In a way more terrible than you can imagine.}
{213}{}{I don't care what you think. Or what anyone else thinks, for that matter. Someone doesn't like me - they can go to hell.}
{214}{}{Hm. You've got enough iron in your blood. Let's see how long it will last.}

#Repeated dialogue
{220}{}{Hey, outsider. You're not counting on eating here, are you? Or are you seeking a source of veteran wisdom? Tell me straight, what do you want?}
{1220}{}{Hey, outsider. You're not counting on eating here, are you? Or are you seeking a source of veteran wisdom? Tell me straight, what do you want?}
{221}{}{Hey, soldier. Want to fill your miserable time with food, or chat with a veteran?}
{222}{}{Neither. I'm getting ready to leave.}
{223}{}{Okay. But if you ever want to hear a tip from a veteran, don't be afraid to ask.}
{224}{}{Goodbye, Graham.}

{230}{}{I need food.}
{231}{}{Cook's over there, in the kitchen. Be gentle with him if you want extra.}
{232}{}{I actually wanted to talk to you.}
{233}{}{Thanks. Goodbye.}
{234}{}{I actually wanted to talk to you.}
{235}{}{Oh, I don't even know where to begin. So many things have happened lately.}
{236}{}{Thanks for telling me your story. Goodbye, Graham.}

#Gambling
{250}{}{Wanna play cards?}
{251}{}{Playing just for fun doesn't interest me. What are you betting on? Caps? I'm going to bet on 5mm bullets. 10 bullets per 25 caps.}
{252}{}{Not today.}
{253}{}{Very well. I accept the challenge. Let's play.}
{254}{}{I want the ration pack.}
{255}{}{Isn't that too fat for a desert outsider? Fine. But for 50 caps, not 25.}
{256}{}{}
{257}{}{You're asking me to go gambling while on duty? Don't forget where you are.}
{258}{}{I'm sorry, Graham.}
{259}{}{It was pretty inappropriate, yeah.}
{260}{}{So, let's begin... Dealing cards... Yours... Mine... Your turn.}
{261}{}{Continue...}
{262}{}{I give up.}
{263}{}{What the hell? I lost to some desert punk? Damn, today is NOT my lucky day...}
{1263}{}{What the hell? I lost to some girl from the desert? Damn, today is NOT my lucky day...}
{264}{}{Game over, Graham.}
{265}{}{That should bring you down a notch. Bye, loser.}
{266}{}{Even in gambling, the Brotherhood always has the advantage. As I demonstrated.}
{267}{}{I'll win it back next time, Graham.}
{268}{}{You may have won this game, but you're still going to lose the war.}

{270}{}{Maybe we could play cards again?}
{271}{}{If I lose more of my supplies, I'll be left with only my dirty pants. As a Brotherhood knight, I declare the game over.}
{272}{}{Fine, whatever you say...}

#Inquiries
{280}{}{What's that kid doing running around on the upper deck?}
{281}{}{Ah, that's Deckie. A son of one of our paladins. Don't mind him. We're not too happy with that monkey either.}
{282}{}{Fine. Let's talk about something else.}
{283}{}{What's bad about having a kid aboard?}
{284}{}{This is, above all, a military base. Well, an outpost. This is no place for civilian concerns.}
{285}{}{The father is a paladin. Who's the mother?}
{286}{}{Listen, this is none of your business, got it? Why are you so hung up on somebody else's past? Worry more about the present.}
{287}{}{What's a "monkey"?}
{288}{}{Umm... I dunno. Just an old phrase.}

{290}{}{Tell me about your Brotherhood.}
{291}{}{Heh, what does a person of your sort need to know about the Brotherhood? Only that there's no force in the Wastelands greater than us.}
{292}{}{I believe you alright. And on that note, let's talk about something else.}
{293}{}{You talk a big game. But I don't hear much about you in Arizona.}
{294}{}{We're very well-known in California. Known and feared, for it was us who destroyed the Master and his whole army. What, you don't know? Good lord, where is this country heading...}
{295}{}{I won't argue with that. But what did you do to become feared?}
{296}{}{We've a lot to do, here in Arizona, but the common folk don't know much about us. In California, every Wasteland mutt knows it was us who destroyed the Master's army.}
{297}{}{That's why I'm here, by the magnificent Brotherhood. But what exactly brought your order to such fame?}
{298}{}{We've won many glorious victories as of late. Heard anything about a fellow called the Master? Rumors of that war have traveled even as far as Arizona.}
{299}{}{What Master?}
{300}{}{Please tell me more.}
{301}{}{You started this, so go on.}
{302}{}{The Master was a damn psychopath. His mutated brains got the idea to turn all people into mutants. He thought he was saving humankind from extinction that way.}
{303}{}{Continue.}
{304}{}{Not a bad idea.}
{305}{}{He managed to build a cult around himself and gather a whole army of supermutants. Nobody in the Wastes could contend with such a force. Except us.}
{306}{}{So what did you do?}
{307}{}{And you, of course, didn't like that?}
{308}{}{It was a year of glorious battles and great victories. We smashed the Master's army and destroyed him with a nuclear blast. From time to time, some of his remaining henchmen are discovered, but they're no longer the threat they once posed.}
{309}{}{Did you participate in that war, too?}
{310}{}{That's cool. I wish I could've seen it.}
{311}{}{Oh yes. Everybody here has a war story. I, for instance, held the line in the battle of Dayglow. A glorious battle.}
{312}{}{You're embellishing it.}
{313}{}{The Brotherhood never lies. Talk to any knight or paladin - many here participated in those battles. I myself held the line in the battle of Dayglow.}
{314}{}{Can you tell me what it was like?}
{315}{}{I don't think I can shut you up at this point.}
{316}{}{After we decimated them, the supermutants ran away in all directions away from their base. The largest groups captured small settlements along their way. Junktown, Necropolis, Dayglow, even the Hub itself, received attacks. We tried to respond to the calls for help.}
{317}{}{It was very honorable of you to help them.}
{318}{}{Uh-uh. Like you did it out of the goodness of your hearts.}
{319}{}{Intelligence said the supermutants established a big outpost in Dayglow. Our unit was supposed to destroy them, but it proved to be a difficult task. The enemy built a fort, and around the fort, put up a complicated system of anti-infantry traps and trenches. And, though they wanted to get rid of those monsters, the locals weren't happy with us either.}
{320}{}{Go on.}
{321}{}{Well, that's fair. Who would like being in the middle of two lines of fire?}
{322}{}{The seige lasted for two weeks. Because we were far away from our main base, we couldn't count on supplies improvised as best we could - smoked the enemy out, flooded their bunkers with toxic waste, used local criminals to make barriers. The supermutants were cut off from the outside world and couldn't receive supplies.}
{323}{}{You starved them to death?}
{324}{}{And you think that's a glorious battle?}
{325}{}{By the end of week two, the supermutants didn't have a choice. Part of them surrendered, the rest tried to break out. That last fight was the most ferocious and hard-fought. Our commander showed unprecedented tactical mastery. If we had tried beseiging their fort at the start, I might not have been here, telling you this story.}
{326}{}{Wow. You really are stronger than anybody else around in our time.}
{327}{}{Yeah. You can fight, alright.}
{328}{}{Seiges aren't particularly spectacular.}
{329}{}{Don't worry, son. We'll turn Arizona into a civilized place, too. Just give us some time.}
{1329}{}{Don't worry, lady. We'll turn Arizona into a civilized place, too. Just give us some time.}
{330}{}{Oh, that's great. That's excellent. Uhh, bye.}
{331}{}{After all you've told me, I don't doubt you anymore. And thanks a lot for the story.}
{332}{}{I wouldn't want anything like that to happen here in Arizona. Thank you, soldier.}

{340}{}{Do you know what happened with paladin Bell?}
{341}{}{Why do you care? You don't even know him, and I fought with him shoulder-to-shoulder. Leave him alone. It's none of your business.}
{1341}{}{Why do you care? You don't even know him, and I fought with him shoulder-to-shoulder. Leave him alone. It's none of your business.}
{342}{}{I'm trying to help him. I need details.}
{343}{}{Was it during those battles that he lost his mind?}
{344}{}{What are you... Uh, fine. Listen, we were in different patrols. He lost his mind here. Could've received his trauma anywhere.}
{345}{}{He talked about some kind of ash, in hell. What do you think it could mean?}
{346}{}{An ash-colored desert? I don't even know... Though there is one place, near Casa Nueva. They mined cement there, so the whole area is gray.}
{347}{}{Were you ever sent there?}
{348}{}{If anybody asks, I did not tell you this, but at some point, workers started to dissapear in the quarry. One after another. We were sent to deal with this problem.}
{349}{}{Go on.}
{350}{}{We found gutted human remains. Like something mauled them. But we didn't find any maniac or beast. Bell was with us, too. It was the first time we felt something was wrong with him.}
{351}{}{So, a quarry in Casa Nueva. That's something. Thank you and goodbye.}
