{100}{}{You see Graham.}
{101}{}{Here is one of the knights of the Brotherhood of Steel.}
{102}{}{Stop. Show me the pass.}

#The first dialog
{200}{}{Hey, native. Even if you were given a pass, this does not mean that you can walk around the ship and distract people from their service.}
{1200}{}{Hey, native. Even if you were given a pass, it does not mean that you can walk around the ship and distract people from their service.}
{201}{}{I'm sorry, but I was terribly curious. This place is so unusual...}
{202}{}{Impressive, right? A real ship. With a huge well-trained and armed team. Tell me, Native, have you come across anything more impressive? That's it.}
{1202}{}{Impressive, right? A real ship. With a huge well-trained and armed team. Tell me, native, have you come across anything more impressive? That's it.}
{203}{}{Distract from the service? You're just sitting in the dining room and doing nothing.}
{204}{}{All this base works thanks to me and my service. But you, a savage from the desert, do not understand the greatness of old technologies. Tell me, Native, have you come across anything more impressive? That's it.}
{1204}{}{All this base works thanks to me and my service. But you, a savage from the desert, do not understand the greatness of old technologies. Tell me, native, have you come across anything more impressive? That's it.}
{205}{}{By the way, who are you?}
{206}{}{I'm Knight Graham. I'm in charge of onboard equipment. I'm on a short break right now, so ask me questions if you have any.}
{207}{}{Nice to meet you, Knight Graham.}
{208}{}{Okay.}
{209}{}{Now I will know who is responsible for all this mess on the ship.}
{210}{}{Ah, this is our new hero. A damn upstart from the desert, who surpassed all the veterans put together. Not bad. But don't think that you will be accepted into the Brotherhood so easily.}
{211}{}{I understand your displeasure. And I will do everything to make the brotherhood accept me.}
{212}{}{Then remember. Many swore in blood that they would not betray our brotherhood. Those who tried paid for it with their lives in the most horrific way.}
{213}{}{I don't care about your opinion. And the opinion of others. If someone doesn't like my presence, let them go to hell.}
{214}{}{Hmm. There's enough iron in your blood. Let's see how much it will last.}

#Repeat dialog
{220}{}{Hey, native. You don't expect to fill your belly here, do you? Or are you looking for a source of veteran wisdom? Tell me straight out, what do you need?}
{1220}{}{Hey, native. You don't expect to fill your belly here, do you? Or are you looking for a source of veteran wisdom? Tell me straight out, what do you need?}
{221}{}{Hey, soldier. Do you want to fill your worthless time with food or chat with a veteran about the service?}
{222}{}{Neither one nor the other. I'm going on the road.}
{223}{}{Okay. But if you need advice from a veteran, then ask.}
{224}{}{Goodbye, Knight Graham.}

{230}{}{I need food.}
{231}{}{Cook's over there in the kitchen. Be gentle with him if you want more.}
{232}{}{I really want to chat.}
{233}{}{Thank you. Goodbye.}
{234}{}{I really want to chat.}
{235}{}{Ah, I don't even know where to start. So much has happened.}
{236}{}{Thanks for the story. Goodbye, Knight Graham.}

#Gambling
{250}{}{Let's play cards?}
{251}{}{Playing for interest is not interesting. What will you bet? bottlecaps? Okay, and I'll put 5 mm cartridges. The bet is 10 rounds for 25 caps.}
{252}{}{Not today.}
{253}{}{OK. I accept the challenge. Let's play.}
{254}{}{No, I want IRP.}
{255}{}{Isn't it too fat for a stranger from the desert? Okay, but your bid will be higher - 50 caps.}
{256}{}{}
{257}{}{For me to play games instead of the service? Don't forget where you are.}
{258}{}{I'm sorry, Knight Graham.}
{259}{}{It was very rude.}
{260}{}{So, let's get started... Distribution... You... me... Your move.}
{261}{}{We continue...}
{262}{}{I give up.}
{263}{}{What? Did I lose to a wasteland brat? Damn, today is definitely not my day...}
{1263}{}{What? Did I lose to a wasteland girl? Damn, today is definitely not my day...}
{264}{}{Your card is broken, Knight Graham.}
{265}{}{That should knock you down a little. Bye, loser.}
{266}{}{Even in gambling, the Brotherhood always has an advantage. Which was required to be proved.}
{267}{}{Next time I'll get my revenge, Knight Graham.}
{268}{}{You may have won the game, but you're going to lose the war anyway.}

{270}{}{Can we play cards again?}
{271}{}{If I keep losing my stocks, I'll be left in nothing but dirty leggings. Being a knight of the Brotherhood, I say "stop" to the game.}
{272}{}{Okay, whatever you say...}

#Questions
{280}{}{And whose kid is this running around the upper deck?}
{281}{}{Ah, it's the Cabin Boy. The son of one of our paladins. Do not pay attention. We are not particularly happy about the powder monkeys.}
{282}{}{Clearly. Let's forget about the cabin boy for now.}
{283}{}{What's wrong with a child on a ship?}
{284}{}{First of all, it is a military base. More precisely, an outpost. There is no place for worldly concerns here.}
{285}{}{The father is a paladin. And who is the mother?}
{286}{}{Look, it's none of your business. Is that clear? Why do you care so much about someone else's past? Worry about your present.}
{287}{}{And what is a "monkey"?}
{288}{}{Em... I don't know. Just an old expression.}

{290}{}{Tell me about your Brotherhood.}
{291}{}{Heh, what does ignorance like you need to know about Brotherhood? Only that there is no greater power in the Wastelands than we are.}
{292}{}{I believe it willingly. That's the end of the conversation about the Brotherhood.}
{293}{}{It sounds loud, but I don't hear much about you in Arizona.}
{294}{}{But we are well known in California. They know and are afraid, because it was we who destroyed the Creator and his entire army. What, you don't know that? Good God, where is this country going...}
{295}{}{I won't argue. But what have you done to be feared?}
{296}{}{Here in Arizona, we have a lot to do, but the commoners don't know much about us yet. But in California, every mutt on the Wastelands knows that it was we who destroyed the Creator's army.}
{297}{}{That's why I'm here, next to a powerful Brotherhood. But what brought your order to such glory?}
{298}{}{We have won many glorious victories recently. Do you know anything about the Creator? Even rumors of this war have reached Arizona.}
{299}{}{What else is the Creator?}
{300}{}{Please tell me more.}
{301}{}{Once you've started, then tell me more.}
{302}{}{The creator is a damn psychopath whose mutated brains gave rise to the idea of universal transformation of people into mutants. He thought it would save humanity from extinction.}
{303}{}{Go on.}
{304}{}{That's not a bad idea.}
{305}{}{He managed to create a cult around himself and gather an army of super mutants. No one on the Wastelands could match such strength. No one but us.}
{306}{}{And what did you do?}
{307}{}{And you didn't like it, of course?}
{308}{}{It was a year of glorious battles and great victories. We defeated the Creator's army and destroyed him with a nuclear explosion. There are still remnants of his henchmen in some places, but they no longer pose the former threat.}
{309}{}{Did you also participate in this war?}
{310}{}{Cool. I would like to see these battles.}
{311}{}{Oh, of course. Everyone here has their own combat history. For example, I was on the defensive in the battle of the Dayglow. It was a glorious massacre.}
{312}{}{Surely you've embellished everything.}
{313}{}{The brotherhood never lies. Talk to any knight or paladin - there are many who participated in those battles. I myself held the defense in the battle at the Dayglow.}
{314}{}{Will you tell me how it was?}
{315}{}{It seems there's no stopping you.}
{316}{}{After the defeat, the super mutants fled in all directions from their base. The largest groups captured small settlements on their way. Junktown, Necropolis, Dayglow, even the Hub was attacked. We tried to respond to requests for help.}
{317}{}{It's very noble of you to help ordinary residents.}
{318}{}{Yeah. As if you were doing it out of the goodness of your heart.}
{319}{}{Intelligence reported that the super Mutants had set up a major outpost in the Glare of the Day. Our squad was supposed to destroy them, but the task was not easy. The enemy organized a fort, and around the fort - a complex system of anti-personnel traps and trenches. In addition, although the locals wanted to get rid of these monsters, they were not happy with us either.}
{320}{}{Go on.}
{321}{}{Of course. Who would like to be between two lines of fire?}
{322}{}{The siege lasted two weeks. Due to the distance from the main base, we could not count on supplies and got out as best we could - smoked out the enemy with a smoke pipe, flooded bunkers with toxic barrels, used local criminals to create blockages. The super mutants were cut off from the outside world and could not receive provisions.}
{323}{}{Did you starve them to death?}
{324}{}{And do you think this is a glorious battle?}
{325}{}{At the end of the second week, the super mutants had no choice. Some of them surrendered, while others tried to break out of the siege. The last fight was the fiercest and hardest. Our commander showed unprecedented skill in tactics. If we had undertaken the siege of the fort at the very beginning, I would not be telling this story now.}
{326}{}{Wow, you really are stronger than anyone you can find nowadays.}
{327}{}{Yes, you seem to be able to fight.}
{328}{}{Sitting under siege is not particularly impressive.}
{329}{}{Don't worry, son. We'll turn Arizona into a civilized place, too. Just give me time.}
{1329}{}{Don't worry, lady. We'll turn Arizona into a civilized place, too. Just give me time.}
{330}{}{Oh, great. Great. Uh, bye.}
{331}{}{I have no doubt at all after all I've heard. And thanks a lot for the story.}
{332}{}{I wouldn't want something like this to happen in Arizona. Good luck, man with a gun.}
{340}{}{You know what happened to Paladin Bell, right?}
{341}{}{What's it to you? You don't even know him, and we fought shoulder to shoulder. Leave him, it's none of your business.}
{1341}{}{What's it to you? You don't even know him, and we fought shoulder to shoulder. Leave him, it's none of your business.}
{342}{}{I'm trying to cure him. And for that I need details.}
{343}{}{It was during your battles that his tower was torn off, right?}
{344}{}{What are you... Ah, well. Listen, we were on different patrols with him. And the tower was torn off for him already here. Therefore, he could get his injury anywhere.}
{345}{}{He was talking about some kind of ash desert in hell. What do you think it means?}
{346}{}{An ash-colored desert? I don't even know... Although there is one place near Casa Nueva. Cement was mined there, so everything is gray.}
{347}{}{Did you have a task there?}
{348}{}{I didn't tell you that, but at some point in the career, workers began to disappear. One by one. We were sent to deal with this problem.}
{349}{}{Go on.}
{350}{}{We found the gutted remains of people, as if someone had torn them apart. But neither the maniac nor the beast was found. Bell was with us, too. That was the first time we felt that something was wrong with him.}
{351}{}{So, the quarry in Casa Nueva. That's something. Thanks and bye.}