{100}{}{You see a servant.}
{101}{}{You see a thin Mexican. He is wearing a striped shirt and a collar, and he is holding a mop in his hands.}

{110}{}{That's right, senor!}
{111}{}{Glad to try, sir!}
{112}{}{Am I detaining you, senor?}
{113}{}{I'm sorry, senor.}
{114}{}{As you say, senor.}

{1110}{}{That's right, senora!}
{1111}{}{Glad to try, senora!}
{1112}{}{Am I detaining you, senora?}
{1113}{}{I'm sorry, senora.}
{1114}{}{Whatever you say, senora.}

{200}{}{What can I do for you, senor... Oh, you're not from the Brotherhood. Then you better not talk to me, paladins don't like it.}
{1200}{}{What can I do for you, senora... Oh, you're not from the Brotherhood. Then you better not talk to me, paladins don't like it.}
{201}{}{Why?}
{202}{}{They're always imagining a conspiracy. And when they find a reason, they arrange inspections and even a public flogging. Here with this strictly. One was recently drowned for stealing food from the supreme Paladin. I don't want to be in his place.}
{203}{}{Clear. Well, come on.}

{210}{}{(looks around) Listen, we're going to have problems.}
{211}{}{Okay. Be.}
{212}{}{I'd like to ask you about this ship and the Brotherhood.}
{213}{}{You're not from the Brotherhood. I'm already risking answering your questions. And what good does that do me, huh? Conversations only tease the stomach.}
{214}{}{Okay. Be.}
{215}{}{Be careful, we may be overheard.}
{216}{}{Then do not anger the paladins. Bye.}
{217}{}{You clearly don't understand your situation. Tell me!}
{218}{}{Go away or I'll call the paladins!}
{219}{}{Gr-r...}

{220}{}{Who are you? You're not in the Brotherhood, are you?}
{221}{}{No way, senor. See the collar? I'm a prisoner, here's my number.}
{1221}{}{No way, senora. See the collar? I'm a prisoner, here's my number.}
{222}{}{Clearly. Another question.}
{223}{}{Prisoner? But why are you being held against your will?}
{224}{}{I just took a couple of ears from the plantation... Well, a couple of fruits... Not a couple, but a whole bag... But I had to eat something! Now I'm working on the ship until I've served my sentence.}
{225}{}{And are there many people like you serving a sentence here?}
{226}{}{Only a few servants are kept on the ship, the rest work in different places - on plantations, in ruins, in a cement factory, building houses, or simply dragging goods across the desert. I was luckier than them.}
{227}{}{And what are you doing here?}
{228}{}{For example, I scrub this damn deck four times a day! Or I carry different boxes. The Order constantly receives and sends some parcels.}
{229}{}{Who else besides you is serving a sentence here?}
{230}{}{Can you leave here?}
{231}{}{If I run too far from the ship, the collar will explode. This is the invention of scribes. They don't stand on ceremony with the locals here. Besides, they feed me here, and in the wastelands, I will have to look for food again. Tough choice, you know.}
{232}{}{Listen here. Either you give out all the information you know, or you "accidentally" find yourself overboard.}
{233}{}{What do you want? Don't you understand where you are?}
{234}{}{I need information.}

{240}{}{What do you know about the Brotherhood of Steel?}
{241}{}{I know a little, the order doesn't like to talk about themselves. I know that this is just an outpost, and the general staff is located far to the west. And these are the coolest guys in all of Sonora. Even tinkerers can't compare with them.}
{242}{}{Clearly. In general, the Brotherhood is not to be trifled with. Let's change the subject.}
{243}{}{Who's in charge here?}
{244}{}{General Dixon. He is usually in his cabin or the mess.}
{245}{}{Clear. Enough about the Brotherhood.}

{250}{}{You know every corner of the ship, don't you?}
{251}{}{No, there's not everywhere you can go. Especially in the lower holds and warehouses.}
{252}{}{Okay, it doesn't matter.}
{253}{}{And what is in the lower holds?}
{254}{}{Torpedo compartment. They say they store explosives there. And there is also a reactor and rats the size of a dog.}
{255}{}{Wow, it's worth a look.}
{256}{}{Who has the keys to the doors?}
{257}{}{Everyone has limited access, only the supreme paladin has the keys to all the doors.}
{258}{}{Hmm. It seems that the general does not even trust his own in everything.}