{100}{}{You see a scribe's computer.}
{101}{}{You see a computer with access to a shared network.}
{102}{}{You have successfully copied the scribes library.}
{103}{}{You have already copied the library to the holodisk.}

#Dialog
{200}{}{Enter command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Next.}
{204}{}{Go back to the main menu.}

{210}{}{Vault-Tec Vault Search.}
{211}{}{According to the latest data, Vault-Tec Vaults with numbers 25-28 may be located in the vicinity of Phoenix. The General Staff of the Brotherhood of Steel ordered to find all these Vaults, study the situation, and use the resources and equipment available there for self-sufficiency or export to the General Staff.}
{212}{}{}
{213}{}{}
{214}{}{Vault 24.}
{215}{}{Location: Otay Open Space National Nature Reserve, San Diego, California. The condition is unknown. The population is unknown. The Vault is probably located in a zone of high radioactive contamination.}
{216}{}{Vault 25.}
{217}{}{The Vault was found in Phoenix and is in perfect condition. It is currently under the control of the Brotherhood of Steel and is used as a base for the Cathedral of Fire. Some equipment has been dismantled and taken to the outpost in Puerto Penasco.}
{218}{}{Vault 26.}
{219}{}{The remains of the Vault were found to the west of Phoenix. Due to the severe damage sustained during the nuclear bombing, the Vault, along with its equipment, fell into complete disrepair.}
{220}{}{Vault 27.}
{221}{}{There is information about the location of the Vault. At the moment, the search and excavation of the Vault is underway by the forces of the Cathedral of Fire under the leadership of Paladin Ulysses Grant.}
{222}{}{Vault 28.}
{223}{}{The location and condition of the Vault are unknown.}

{230}{}{Development of nanostructured cartridges.}
{231}{}{Due to the shortage of armor-piercing ammunition and the periodic need for it, limited production of 10 mm cartridges made of nanostructured metal was established.}
{232}{}{A tribe of tinsmiths in Two-Sun is engaged in the manufacture of bullets under a standard trade contract.}
{233}{}{}
{234}{}{Food self-sufficiency.}
{235}{}{We managed to fully cover our food requests thanks to the Casa Nueva plantations. At the moment, the harvest is also being exported.}
{236}{}{Development of nuclear weapons.}
{237}{}{In accordance with the request of the General Staff, we are moving to the production of nuclear weapons. At the moment, the project documentation has been completed and the necessary amount of nuclear material is being extracted.}
{238}{}{For reasons of security, logistics, and time savings, the assembly of the final weapon is carried out by representatives of the Phoenix Cathedral of Fire under the strict control of the Brotherhood of Steel.}