{100}{}{You see a command computer.}
{101}{}{You see a computer of the supreme paladin.}

#Dialog
{200}{}{Enter command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Next.}
{204}{}{Go back to the main menu.}

{210}{}{File on Private Corwin.}
{211}{}{Name - Alvin Corwin. The title is novice. The unit is a candidate for paladins. The state of health is normal.}
{212}{}{On behalf of Paladin Dixon, issue a discharge ticket for Novice E. Corwin.}
{213}{}{The order is accepted.}
{214}{}{That's great. I'm going to make Alvin happy.}

{220}{}{Open Dixon's appeal.}
{221}{}{"The modern world needs strength. The kind of strength that will lift him off his knees and put his shoulder to take a step forward. And only the Brotherhood of Steel has everything that is needed for this. But the order remained aloof from the outside world for a long time. When the threat of super mutants loomed over California, it was we who were able to resist it. We can't sit in our bunker anymore. The war is not over yet. Our brothers and sisters in Lost Hills need Sonora's technology and resources. Let's strengthen our steel to resist the enemy together!"}
{222}{}{Mission "Flag of the Nation".}
      #the title is a reference to the film "Prison Rock" 1955
{223}{}{Our goals and objectives require decisive measures to unite and control the wild territory of the former Arizona. This is the only way we can build the infrastructure we need. A government friendly to the Brotherhood of Steel should be established in key cities. Discontent with the new government should be suppressed, and the population should be re-educated.}
{224}{}{The Lame Duck project.}
#name is a political term in the USA
{225}{}{It is necessary to establish a unified authority over the city of Phoenix with full control from the Brotherhood as soon as possible. Within the framework of this new power, to organize a consulting and supervisory body hidden from the public with a member of the Brotherhood of Steel at the head.}
{226}{}{Operation "Wind of War"}
{227}{}{It is necessary to organize and strengthen a colony on the territory of the city of Nogales to control the Mexican border. According to intelligence, the settlement is under the onslaught of the enemy Mexican army.}
{228}{}{Our main goal.}
{229}{}{Our primary goal is to provide the general Staff in Lost Hills with nuclear energy reserves and surviving technologies to fight the remnants of the army of super mutants. Due to the remoteness of the Puerto Penasco outpost, Supreme Paladin Dixon is given special powers and freedoms in decision-making.}

{240}{}{Read Dixon's diary.}
{241}{}{"...The General Staff in California did not send me to Arizona to make this place bloom with love and freedom. Our goal is to collect ancient technologies and other resources that are so necessary for the Brotherhood in these difficult times. Local rednecks absolutely do not understand their value and criminally spend what is left of the pre-war era..."}
{242}{}{"...Whatever these pompous clerks write in their missions, we are not here for peace, but for war. Local residents do not want to voluntarily give up technology and share resources. The capture of Phoenix was a bloody event only because it could not be otherwise. We are *forced* to force the population to peace in order to achieve our goals..."}
{243}{}{"...I know the general Staff in Lost Hills does not approve of such drastic measures. But how else can we be self-sufficient? Our main resource, the sources of nuclear energy, goes a long way from the Flagstaff mines to the Two-Sun workshops, and then is transported across the desert to the outpost and then to Lost Hills. This requires a lot of workers, even forced labor. In these desolate lands, far from home, we have no time to think about morality..."}
{244}{}{"...In Arizona, the local foundations are too strong. Many families live here for generations, and it is very difficult to break through their conservatism. We spent several years establishing ourselves in Phoenix through the cult of Aaron. And there is still resistance there. We have turned the tinsmiths of Two-Sun to our side, but our agreement may lose its force at any moment. Therefore, we have no right to delay. We have to take EVERYTHING, right here and now..."}
{245}{}{Close Dixon's diary.}
{246}{}{Read more.}