{110}{}{Cancellation of the salvo is not possible.}
{111}{}{It made sense to do this before. But not now, when I'm on the Brotherhood's side.}

#Dialog
{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Back.}
{203}{}{Cancel.}
{204}{}{Accept.}
{205}{}{Accept the specified parameters.}
{206}{}{Next.}

{210}{}{Set torpedo parameters.}
{211}{}{Specify the parameters.}
{212}{}{Cancel all entered data.}
{213}{}{Stop data entry and end the session.}
{214}{}{The original parameters have been restored.}

{220}{}{The angle of sight of the TARGET is US.}
{221}{}{Angle of sight WE ARE THE TARGET.}
{222}{}{Current angle: }
{223}{}{ degrees.}
{224}{}{+10 degrees.}
{225}{}{+1 degree.}
{226}{}{-1 degree}
{227}{}{-10 degrees.}
{228}{}{The angle of sight.}

{230}{}{Distance to the target.}
{231}{}{Estimated distance: }
{232}{}{ yards.}
{233}{}{+100 yards.}
{234}{}{+10 yards.}
{235}{}{+1 yard.}
{236}{} {-1 yard.}
{237}{}{-10 yards.}
{238}{}{-100 yards.}

{240}{}{Salvo mode.}
{241}{}{Current mode: }
{242}{}{ Spread angle: }
{243}{}{One torpedo.}
{244}{}{Two torpedoes.}
{245}{}{All torpedoes.}
{246}{}{}
{247}{}{Scatter angle }
{248}{}{0.5 degrees.}
{249}{}{1 degree.}
{250}{}{1.5 degrees.}
{251}{}{2 degrees.}

{260}{}{The speed of the torpedo.}
{261}{}{Current speed: }
{262}{}{ nodes.}
{263}{}{+5 nodes.}
{264}{}{-5 nodes.}

{270}{}{The depth of the explosion.}
{271}{}{Explosion depth: }
{272}{}{ yards.}
{273}{}{+1 yard.}
{274}{}{-1 yard.}

{280}{}{Type of fuse.}
{281}{}{Fuse type: }
{282}{}{undefined.}
{283}{}{Contact.}
{284}{}{Magnetic.}
{285}{}{Timer.}

{290}{}{Set a timer to activate the torpedoes.}
{291}{}{Time to explosion: }
{292}{}{ seconds.}
{293}{}{+10 seconds.}
{294}{}{-10 seconds.}

{300}{}{Launch torpedoes.}
{301}{}{Attention! The gateway opening mechanism is not responding.}
{302}{}{Great, so they're not going anywhere. Activate the torpedoes.}
{303}{}{Oh, no, no, I don't need that. Cancel, cancel!}
{304}{}{The torpedoes are on alert. Starting in... }
{305}{}{ seconds.}
{306}{}{Oops, it's time to escape from a sinking ship...}
{307}{}{Press the buttons at random.}
{308}{}{Oops, it seems that some kind of countdown has begun...}