{110}{}{These are torpedoes with a nuclear charge.}
{111}{}{It must be a damn powerful thing.}
{112}{}{These are torpedoes with a nuclear charge. And they are on alert. }
{113}{}{It's time to get out of here...}
{114}{}{It made sense to do this before. But not now, when I'm on the Brotherhood's side.}

{120}{}{It's a nuclear torpedo. Somewhere nearby there should be a control panel for the torpedo compartment.}
{121}{}{There is nothing to repair here.}
{122}{}{This device is too complicated for you. Perhaps there are other ways to activate the torpedo.}
{123}{}{You have successfully activated the torpedo timer.}
{124}{}{You have successfully deactivated the torpedo timer.}
{125}{}{It is impossible to deactivate the timer.}

{150}{}{Until the explosion left }
{151}{}{ seconds.}