{100}{}{You see the quartermaster.}
{101}{}{You see the tinsmith responsible for the warehouse. His shaven head is covered with a powerful computing helmet.}
{102}{}{T-51b powered infantry armor... How did YOU manage to acquire such technology?}

#First dialogue
{200}{}{(as if not even noticing you) Five thousand one hundred eighty six... no, it doesn't add up ...}
{201}{}{Hey, what do you do here?}
{202}{}{(not looking up) Responsible for trade and goods. If you aren't here for trade, head to our boss. He's in the north-eastern part of the building.}
{203}{}{I see.}

#Repeat dialogue
{210}{}{Yeah?}
{211}{}{Don't mind me.}

{216}{}{Master Khard added you to our list of partners. You can expect special prices here.}
{217}{}{Great.}
{218}{}{Master Khard thinks you deserve a discount higher than our regular partners. Treasure his prudence.}
{219}{}{So your goods are even cheaper now? That's great.}

{220}{}{Why do you need all this equipment?}
{221}{}{It helps me work better. You're a desert primitive, you wouldn't understand.}
{222}{}{Where did you get it?}
{223}{}{Look around - this place is filled with advanced technology that you, savages, have no idea about. We have achieved control over them and now use them as we see fit. This computer is merely one among our many side projects.}
{224}{}{So that's how it is.}

#About the goods
{230}{}{What items do you sell?}
{231}{}{Two Sun has always been known for it's technology. But not all are worthy of it.}
{232}{}{Alright.}
{233}{}{Do you accept Pre-War currency?}

{240}{}{No. Caps only.}
{241}{}{Why?}
{242}{}{Bottlecap currency is supported by the church of the Holy Fire in Phoenix. But I don't like it. Whose idea was it to make those big, bulky things into money? We could make our own, new coins with these machines. And one day, we will.}
{243}{}{Bottlecap currency used to be supported by the church of the Holy Fire in Phoenix. Even though the church is deposed, bottlecaps will remain the most reliable currency in the coming years.}
{244}{}{I see.}
{245}{}{Why so many canned noodles?}
{246}{}{They come from recently breached military warehouses. Excellent army rations. Though the drabness sometimes gets even to us, tinsmiths.}
{247}{}{Noodles make me sick. Have anything else?}
{248}{}{Well... no.}
{249}{}{What a shame.}
{250}{}{Well... there is something. Don't ask me how I got it, but it's the best food you can find. (shows three containers labeled "CR") It won't be cheap, though.}
{251}{}{"Combat ration"? Sounds great. I'll think about.}
{252}{}{You *are* going to give a discount to a member of the Brotherhood of Steel, right?}
{253}{}{You *are* going to give a discount to a servant of the Holy Fire, right?}
{254}{}{Of course. Our friends deserve such respect.}
{255}{}{Great.}
{256}{}{Noodles... Is there really nothing better?}

#If ZAX destroyed the settlement:
{260}{}{By Ampere! What are you doing here?! After the robot invasion, I didn't expect to see anyone in Two Sun. My friends were killed, and the others fled the settlement. I don't think any traveler is going to visit this place anymore.}
{261}{}{Why aren't you leaving?}
{262}{}{I have nowhere to go. The tinsmiths were all I ever knew. And I can't survive without technology. But I have an idea - I'll try to make a floating platform to travel to California on. I'm certain they'll find a use for me there.}
{263}{}{I see. Well, so long.}
{264}{}{How did you survive?}
{265}{}{I know these places yet. And I have equipment for fooling the robots. But it's only a matter of time.}
{266}{}{You still have things to sell, right?}

#Power cell quest
{269}{}{All power cell trade has been halted until the mines of Flagstaff become operational again. Go find power cells somewhere else.}
{270}{}{I need a power cell for a generator.}
{271}{}{The technology is too valuable to be traded away just like that.}
{272}{}{Just name your price.}
{273}{}{And I thought that after everything I did in the Forbidden Zone, I'd be somewhat trusted in here.}
{274}{}{Here is the price. (adds power cell to the other tradable items) If you don't like it, you're welcome to leave.}
{275}{}{Let me think about it.}
{276}{}{In my predicament, these items lose their value. I'm ready to trade them.}
{277}{}{Smart move.}
{278}{}{For the last time - that thing is NOT for sale.}
{279}{}{Okay, okay...}

#Tradable items expansion
{280}{}{I have many connections throughout Arizona. It's very profitable doing business with me.}
{281}{}{Maybe, but mere words aren't enough to convince me.}
{282}{}{A shame that you don't see how much you could benefit.}
{283}{}{That's sufficient. Take a look at these wonderful technologies and name your price.}
{284}{}{Finally.}
{285}{}{Now that Master Khard has lost his job, there's no point for you to not sell me these items.}
{286}{}{After Master Khard's dismantling, I have nothing left to do but trade with everyone I see. Here are all the goods.}
{287}{}{Smart move.}
{288}{}{Master Khard extended the list of goods I can acquire.}
{289}{}{Can I expect to be able to buy the goods for the "worthy"?}
{290}{}{No. But Master Khard could change that.}
{291}{}{I think I should go talk to him.}
{292}{}{I don't think so.}
{293}{}{Fine.}
{294}{}{You need clients now more than ever.}
{295}{}{It's profitable doing business with me.}

#Upgrades
{300}{}{Can you repair my equipment?}
{301}{}{What exactly? Weapons? Armor? Something else entirely? We work with any kind of technology. But it will cost you a fair amount of caps.}
{302}{}{Forget it, then.}
{303}{}{I'm talking about my personal bike.}
{304}{}{Hm... I've never worked with that kind of technology before. Motorcycle components are rare here. We mostly find heavy military trucks and airplanes.}
{305}{}{[Continue]}
{306}{}{But you know what? I could try to boost the motorcycle's speed with the help of airplane components. But with these tires and this kind of engine? I don't know... they probably need to be upgraded to withstand the increased pressure.}
{307}{}{Can you do that?}
{308}{}{I'm telling you - I don't have tires or any other motorcycle components. Try to remember places with old garages. They ought to have something useful.}
{309}{}{I see. I'll be back when I strengthen my iron brahmin.}
{310}{}{It's already done. A guy in Garage City upgraded both the tires and the drive. Now, tell me more about your idea with airplane components.}
{311}{}{They used the most powerful propulsion systems on airplanes, but I can adapt some of these parts to a motorcycle. Overheating's going to be a problem, so you'll also need good thermal outlet pipes and blowing. In addition, a couple of new modules for the on-board computer won't hurt... And, perhaps, higher quality aviation lubricant.}
{312}{}{Sounds great.}
{313}{}{Cursory estimate says the speed will be increased by 40%. Still interested? Then get }
{314}{}{ caps ready, because that is going to be very labor-intensive.}
{315}{}{Here are the caps. Now put that damn booster on!}
{316}{}{I can't afford such luxury yet. Suppose I'll have to drive with the speed of a brahmin for some time more.}
{317}{}{For some reason, I expected a trick like this. From you, wasteland primitives, nothing else can be expected.}
{318}{}{It was an accident...}
{319}{}{Ta-ta! Your bike has been transformed beyond recognition. It will now not drive, but *fly* over the highway!}
{320}{}{Sounds far too difficult, expensive and impractical. I suppose I'll get by without this.}

{330}{}{Master Khard promised me a reward.}
{331}{}{That's right. The rewards are: metallic armor, laser pistol and night-vision goggles. Use these gifts wisely.}
{332}{}{I'll find a worthy utilization for them.}
{333}{}{That's right. Here is the list of possible rewards. Choose the one you want and mark it with an 'X'.}
{334}{}{[Metallic armor]}
{335}{}{[Plasma pistol]}
{336}{}{[Medical pack: 3 stimpaks, 3 antidotes, 1 radaway]}
{337}{}{[Stealth-boy & night-vision goggles]}
{338}{}{[Nuclear power supply unit]}
{339}{}{[350 caps]}
{340}{}{Use this gift wisely.}
{341}{}{I'll find a worthy utilization for it.}

{350}{}{I need my power armor repaired.}
{351}{}{A most excellent example of old technology. I feel the logic circuits failing in my neural network every time I so much as dare look at it. Yes, we do have the capability to repair all that which has been damaged in this armor. But that will cost you a very high amount of caps.}
{352}{}{Here they are. Now, initiate repairs.}
{353}{}{No need. They could repair it for free in the Brotherhood itself.}
{354}{}{I'll think about it. I need to get out of this shell anyway.}

#The Ancient Relic
{400}{}{I have an old atomic clock. What do you have?}
{401}{}{By Ampere! That clock dates back a hundred years, yet still shows time.}
{402}{}{Looks like you really want to get your hands on it.}
{403}{}{The wisdom of our forebears knew no bounds. And now we collect the remains of their technologies, and spend great effort to reproduce that which they could make in mere minutes. This clock is one of those technologies which we cannot recreate.}
{404}{}{I'll give it away for free as a sign of future deals. You won't refuse to provide me service, of course?}
{405}{}{Smart move. You can expect lower prices, desert prim... person.}
{406}{}{Very good.}
{407}{}{I'll sell it to you for 350 caps.}
{408}{}{Smart move. Here are the caps. I take it this won't be our last deal.}
{409}{}{Excellent.}
{410}{}{Technology for technology. I'll give you the clock, if I receive specifications for energy weapons.}
{411}{}{Fair enough. I have the information you need. With it, you can most certainly increase your skill at using energy weapons. Though few of us here like it when commoners can use advanced ancient technology.}
{412}{}{That will come in handy. So long, tinsmith.}
{413}{}{We have this great pneumatic fist here, which we use to knock out any nonsense out of the heads of outsiders. I see no clock among your things, desert primitive.}
{414}{}{How did this happen...}
{415}{}{Give me some time to think. Don't worry, the clock won't break apart.}
{416}{}{The quartermaster lowered the price of his goods by 10%.}