{100}{}{You see the quartermaster.}
{101}{}{You see the tinsmith responsible for the warehouse. His shaved head is covered with a powerful computing helmet.}
{102}{}{Power armor T51b... Curious, how did YOU manage to tame such a complex technology?}

#The first dialog
{200}{}{(as if not noticing you) Five thousand one hundred and eighty-six... no, it doesn't add up...}
{201}{}{Hey, what are you doing?}
{202}{}{ (without looking up from the list) I am responsible for the warehouse and trade. If you're not trading, then go to our boss, he's upstairs.}
{203}{}{I see.}

#Repeat dialog
{210}{}{Yes?}
{211}{}{Nevermind.}

{216}{}{Master Hard has added you to the list of our partners. This means that you can count on special prices in this warehouse.}
{217}{}{Great news.}
{218}{}{Master Hard believes that you deserve a better discount than ordinary partners. Appreciate his prudence.}
{219}{}{So the product has become even cheaper? That's great.}

{220}{}{Why do you need all this equipment?}
{221}{}{Helps with work. It's hard for you savages from the wastelands to understand.}
{222}{}{Where did you get it from?}
{223}{}{Look around - this place is filled with high technology, which you savages have no idea about. We have subdued ancient technologies and use them at our discretion. This computer is just one of our small developments.}
{224}{}{That's how it is.}

#About the product
{230}{}{What do you trade in?}
{231}{}{Two-Sun has always been famous for his technology. But not everyone is worthy of them.}
{232}{}{I see.}
{233}{}{Do you accept pre-war money for payment?}

{240}{}{No, only bottlecaps.}
{241}{}{Why?}
{242}{}{Caps as currency are supported by the Sacred Fire Church in Phoenix. Although I don't like this idea with bulky caps. We could make new coins on our machines. And someday it will happen exactly like this.}
{243}{}{The caps as currency were maintained by the Sacred Fire Church in Phoenix. And although the church has been deposed, caps will remain the most reliable currency for the coming years.}
{244}{}{I see.}
{245}{}{Where did so many canned noodles come from?}
{246}{}{From military depots that were recently found and opened. Excellent army rations. Although monotony sometimes depresses even us tinsmiths.}
{247}{}{Noodles make me gag. Is there anything else?}
{248}{}{Well... no.}
{249}{}{Sorry.}
{250}{}{Well... there's something. Don't ask me where I got it, but it's the best food you can find. (shows three containers marked "IRP") It won't be cheap.}
{251}{}{"Individual diet"? Sounds good, I'll think about your offer.}
{252}{}{You'll give a discount to a member of the Brotherhood of Steel, won't you?}
{253}{}{Will you give a discount to a Follower of Fire?}
{254}{}{Sure. Our friends deserve such respect.}
{255}{}{Wonderful.}
{256}{}{Noodles... Is there really nothing better?}

#If ZAX destroyed the village:
{260}{}{Holy Ampere! What are you doing here?! After the invasion of robots, I did not expect to see someone in Two-Sun. My comrades were killed, and the villagers fled the city. I think no traveler will come here now.}
{261}{}{Why don't you leave?}
{262}{}{I have nowhere to go. Tinsmiths were all I knew. And without technology, I certainly won't be able to survive. But there is one idea - I will try to make a flying platform and go to California on it. There will surely be a use for me there.}
{263}{}{That's it. Well, come on.}
{264}{}{How did you survive?}
{265}{}{I know these places well. And I have the equipment to trick robots. But it's only a matter of time.}
{266}{}{Do you still have things to exchange?}

#Quest for an energy cell
{269}{}{We have temporarily halted the trade of all energy carriers until the Flagstaff mines restore production. Look for power cells somewhere else.}
{270}{}{I need a power cell for the generator.}
{271}{}{This is too valuable technology to give to the firstcomer.}
{272}{}{Just name your price.}
{273}{}{After the events in the Forbidden Zone, I deserve loyalty.}
{274}{}{That's my price. (adds the item to the rest of the goods) If you are not satisfied, you can leave.}
{275}{}{Let me think.}
{276}{}{In my conditions, these items lose their significance. I'm ready to sell them.}
{277}{}{The correct solution.}
{278}{}{I repeat for the last time - this thing is not for sale.}
{279}{}{Come on...}

#Product Disclosure
{280}{}{I have extensive connections throughout Arizona, and it is profitable to do business with me.}
{281}{}{Maybe so. But your words alone are not enough.}
{282}{}{It's a pity that you don't see your benefits.}
{283}{}{Okay, that's enough. Take a look at these beautiful pieces of technology and name your price.}
{284}{}{That would be right away.}
{285}{}{Now that Master Hard is out of business, it makes no sense for you to hold the goods.}
{286}{}{After dismantling the Hard Master, I have no choice but to trade with everyone. Here is my entire product.}
{287}{}{A reasonable solution.}
{288}{}{Master Hard gave me extended access to the goods.}
{289}{}{Can I count on the goods "for the worthy"?}
{290}{}{No. However, Master Hard may decide otherwise.}
{291}{}{So I should talk to him.}
{292}{}{I don't think so.}
{293}{}{Well, that's fine.}
{294}{}{You need customers now more than ever.}
{295}{}{It is profitable to do business with me.}

#Upgrades
{300}{}{Can you fix my gear?}
{301}{}{What exactly? Equipment, weapons, armor? We work with any technology. But it will cost you a substantial amount of caps.}
{302}{}{Forget it.}
{303}{}{I'm talking about my bike.}
{304}{}{Hmm... I've never had to mess with such a technology. Motorcycle parts are rare here, mostly heavy military trucks and airplanes.}
{305}{}{[Next]}
{306}{}{But you know what, I can try to speed up the motorcycle with the help of aviation parts. However, for this you will have to put in powerful tires and strengthen the engine, otherwise they may not cope with the increased load.}
{307}{}{Can you do it?}
{308}{}{I'm telling you, I don't have any tires or other motorcycle parts. Remember the places where there are old garages, there will surely be at least something useful.}
{309}{}{Clear. I will return when I strengthen my iron brahmin.}
{310}{}{Everything is ready. The master in Garage City has updated both the tires and the engine system. Tell me about that idea with the aviation accelerator.}
{311}{}{The planes used the most powerful traction systems, but I can adapt some of these parts to a motorcycle. For the system not to overheat, you will also need a good blowing and thermal discharge pipes. Also, a couple of new modules for the on-board computer will not hurt... And, perhaps, a better aviation lubricant.}
{312}{}{Sounds good.}
{313}{}{According to cursory calculations, this will give an increase in speed by 40%. Still interested? Then prepare }
{314}{}{ bottlecaps, because this service is very time-consuming.}
{315}{}{Here are the bottlecaps. Put that damn accelerator on!}
{316}{}{I can't afford that luxury yet. We will have to drive at the speed of a brahmin for some time.}
{317}{}{For some reason, I was expecting tricks like this. Nothing else can be expected from you savages from the wasteland.}
{318}{}{Yes, I didn't do it on purpose...}
{319}{}{Ta-dam! Your bike has been transformed beyond recognition. Now he will not drive, but fly over the highway!}
{320}{}{Sounds like something too complicated, expensive and impractical. I'll probably do without it.}

{330}{}{Master Hard was talking about a reward for me.}
{331}{}{That's right. Reward: metal armor, laser pistol, night vision goggles. Dispose of these gifts wisely.}
{332}{}{I will find a worthy use for this.}
{333}{}{That's right. Here is a list of available rewards. Choose and mark with a cross.}
{334}{}{[Metal armor]}
{335}{}{[Plasma gun]}
{336}{}{[Medical kit: 3 stimpacks, 3 antidotes, 1 Radaway]}
{337}{}{[Stealth combat and night vision goggles]}
{338}{}{[Nuclear block]}
{339}{}{[350 caps]}
{340}{}{Dispose of these gifts wisely.}
{341}{}{I'll put it to good use.}

{350}{}{I need to fix my power armor.}
{351}{}{A fine example of old technologies. I fix the failure of logical circuits in my neural network, I only have to look at this armor. Yes, we can repair all of her damage. But it will cost you a very large amount of caps.}
{352}{}{Act.}
{353}{}{No need. Perhaps the Brotherhood itself will fix it for free.}
{354}{}{I'll think. Anyway, I need to get out of this shell.}

#Relic
{400}{}{I have an old atomic clock. And what do you have?}
{401}{}{Holy Ampere! This clock is a hundred years old, but it still shows the time.}
{402}{}{It seems to turn you on.}
{403}{}{Our ancestors were infinitely wise. And now we are collecting the remnants of their technology and with great difficulty reproducing what they did in a matter of minutes. This watch is one of those precision technologies that we cannot recreate.}
{404}{}{I will give them away for free as a sign of upcoming deals. You won't refuse my services, will you?}
{405}{}{That's reasonable. You can count on more reasonable prices, Dika... the man from the desert.}
{406}{}{Very good.}
{407}{}{I will sell this watch for 350 caps.}
{408}{}{That's reasonable. Here are the bottlecaps. And I hope that this will not be our last deal.}
{409}{}{Great.}
{410}{}{Technology for technology. I'll give you the watch if I get the energy weapon specification in return.}
{411}{}{Well, that's fair. I have the information I need. With her help, you will surely improve your skills. Although many of us do not like it when commoners have a hand in great ancient technologies.}
{412}{}{I'll need it. See you later, tinker.}
{413}{}{We have a great pneumatic fist with which we knock out any nonsense from the minds of strangers. I don't see a watch among your junk, desert savage.}
{414}{}{How did it happen so...}
{415}{}{Give me time to think. Don't worry, the watch won't go bad during this time.}
{416}{}{The quartermaster lowered the cost of his goods by 10%.}