{100}{}{You see a runaway slave.}
{101}{}{You see one of the runway slaves that have established themselves in these ruins.}

{110}{}{Tinsmiths are gonna pay for everything.}
{111}{}{Tinsmiths separated you from your relatives too? I understand...}
{112}{}{If you hate tinsmiths, you're in the right place.}
{113}{}{Want to join us?}
{114}{}{Join us. We need more suicide saboteurs.}
{115}{}{Got a weapon? What about food or booze?}
{116}{}{What are you looking at?}
{117}{}{I have no idea what the hell "National Bank of Arizona" means.}
{118}{}{Money? We light fires with it. What's wrong with that?}
{119}{}{Fighting for freedom is the only thing we have left to do.}