{100}{}{You see a runaway slave.}
{101}{}{Here is one of the runaway slaves who settled in these ruins.}

{110}{}{The tinsmiths will pay for everything.}
{111}{}{Did the tinsmiths separate you from your family? I understand...}
{112}{}{If you hate tinkers, then you are among your own.}
{113}{}{Do you want to join us?}
{114}{}{Join us. We need more kamikaze saboteurs.}
{115}{}{Do you have a weapon? And food or drink?}
{116}{}{What are you staring at?}
{117}{}{I have no idea what the Arizona National Bank is.}
{118}{}{Money? We light fires with them. And what?}
{119}{}{The struggle for freedom is all that remains for us.}