{100}{}{You see the lookout.}
{101}{}{Here is one of the runaway slaves. He's guarding the entrance.}

{200}{}{Stop! What the hell? How did you manage to get through the traps?}
{201}{}{I had a map.}
{202}{}{Just lucky.}

{203}{}{Are you kidding? Okay... And what the hell do you want here?}
{1203}{}{Are you kidding? Okay... And what the hell do you want here?}
{204}{}{I don't believe in such luck. But even so... What the hell do you want here?}

{205}{}{I want to talk to your boss.}
{206}{}{We don't have a boss. We're all equal here. Are you a slave too? Or are you sniffing around for the tinsmiths? Okay, go to Jeff, he's in charge of tactics. Let's see what he says.}
{207}{}{OK. We'll find something to talk about with him.}
{208}{}{Actually, I've already sniffed out everything I need. Now you will die.}
{1208}{}{Actually, I've already sniffed out everything I need. Now you will die.}
{209}{}{Only one thing is to eliminate your presence in these ruins.}

{210}{}{Come on in, but don't even think about making plans against us.}
{211}{}{OK.}
{212}{}{Bye.}
{213}{}{Spy! Everyone here!}
{214}{}{And that was for nothing.}

{220}{}{Tell me how you got here?}
{221}{}{I was captured in Phoenix and sold to tinsmiths as a slave. Then they were sent to the Forbidden Zone to collect old things. Luckily for me, Jeff was there and helped me out of the trap. Now I'm here, helping in any way I can. I am appreciated for my skill with traps.}
{222}{}{Just grabbed, right? Somehow doubtful.}
{223}{}{Hey, have you ever come across these fanatics worshipping nuclear energy? They don't consider the people in the wastelands to be people. If they need slaves, then no matter who you are and what you do, they will still grab you by the throat with a collar.}
{224}{}{How did you learn to handle mines?}
{225}{}{Uh, Jeff taught me. But I didn't ask who taught him.}
{226}{}{Tell me about Jeff.}
{227}{}{A serious guy, you have to hold on to such people. If it wasn't for him, we would have perished in the Forbidden Zone or starved to death. Sometimes he performs a miracle and finds supplies where no one could find anything.}

#Traps
{230}{}{How do I get out of here without being blown up by mines?}
{231}{}{Go through the back door. I won't tell you anything else.}
{232}{}{Okay.}
{233}{}{We have to trust each other, because we are doing the same thing.}
{234}{}{Okay, I'll show you the minefields. Be careful.}
{235}{}{Thank you.}
{236}{}{You already know too much.}
{237}{}{Well, okay...}