{100}{}{You see Jeff.}
{101}{}{You see the leader of a gang of runaway slaves.}
{102}{}{Soon we will move north and along the way, we will spread the truth about the tinsmiths.}

{200}{}{So, I was informed of your appearance. I confess I'm confused. Who are you and what are you doing here?}

{201}{}{Actually, I'm just looking for valuables in these ruins...}
{202}{}{That's how. Am I supposed to believe this nonsense? You know our location, you successfully bypass the traps, and this is in the middle of a huge territory lying in ruins. I'm asking for the last time - what the hell are you doing here?}
{203}{}{I'm telling the truth.}
{204}{}{Hmm... You look like an experienced scavenger, you had to walk more than one mile... Okay, I'll believe you... this time.}
{1204}{}{Hmm... You look like an experienced scavenger, you had to walk more than one mile... Okay, I'll believe you... this time.}
{205}{}{It's good that we found mutual understanding.}
{206}{}{Then we'll see what you say when we hang you over a burning barrel. Hold the spy, guys!}
{207}{}{Hey, take it easy!}
{208}{}{}
{209}{}{}

{210}{}{I escaped from a labor camp and I need help.}
{1210}{}{I escaped from a labor camp and I need help.}
{211}{}{We were all slaves of tinsmiths once. But we managed to escape. And now our goal is to bring justice to those who put themselves above us. I think we'll work together.}
{212}{}{It's good that we found mutual understanding.}

{220}{}{I'm here on behalf of the tinsmiths. They are investigating the attack on the caravan.}
{221}{}{Yes, that was our job... More precisely, our achievement. It took a whole month to prepare for this operation, and we coped. Now the tinkerers will understand that they are not alone on the Wastelands. And the supplies we get will go to the good cause of our struggle.}
{222}{}{I see.}
{223}{}{You know I can't let you go now. Or is there a reason?}
{224}{}{I'm just a mercenary. I don't care who I work for.}
{225}{}{You'll have to. Because... you're going to die!}
{226}{}{We are fighting not for the sake of bottlecaps, but for the sake of an idea - for the sake of saving the Wastelands from the corrupting "progress". (spits contemptuously)}
{227}{}{[Next]}
{228}{}{But there's no way to fix such corrupt creatures as you. Kill him, guys!}
{1228}{}{But there's no way to fix such corrupt creatures as you. Kill her, guys!}
{229}{}{Hey, take it easy!}
{230}{}{Hmm... You could be our eyes and ears behind enemy lines.}
{1230}{}{Hmm... You could become our eyes and ears behind enemy lines.}
{231}{}{It's good that we found mutual understanding.}

{240}{}{For now, I'll let you stay in our hiding place. But if we suspect something, then don't count on a warm welcome.}
{241}{}{Okay, I understand.}

#Repeat dialog
{250}{}{This is a new member of our resistance. Anything to report?}
{251}{}{Nothing yet.}
{252}{}{I see. There are no more questions.}

{260}{}{I wonder where you all come from?}
{261}{}{Each of us was once a slave to the tinsmiths. We were sent to a Restricted Area for mining, but some managed to escape. It is impossible to get far from here, I had to settle in these ruins and survive on my own.}
{262}{}{What did you mine?}
{263}{}{Objects of ancient technologies. Many of them have not been working for a long time, and some are too dangerous to touch. Therefore, the disturbed spirit of old technologies resisted our appearance and began to destroy all people in the Forbidden Zone, even if they were not here of their own free will.}
{264}{}{How did you manage to escape from the Restricted Area?}
{265}{}{Everyone has their own story, but mostly our predecessors helped us. I am the last person from the former resistance.}
{266}{}{Why don't you leave here?}
{267}{}{We are like this old repository. The tinkerers have destroyed everything dear to us, but we are trying to preserve at least a little of the life we are used to. If not for ourselves, then for our relatives who could still survive in the wastelands.}
{268}{}{Speaking of survival, do you mean attacking travelers?}
{269}{}{Including. Our worst enemies are provided with everything they need because of the wasteland merchants. However, it is not necessary to kill them - it is enough just to scare them away from the feeder so that they stay away from fear.}

#Attempt to smoke out slaves from Tu san
{270}{}{How can I be useful to your resistance?}
{1270}{}{How can I be useful to your resistance?}
{271}{}{We need a spy. Go back to the tinker camp and find information for us about the nearest caravans. It should be on the computers in the big hangar. If you manage, you will get }

{280}{}{The tinsmiths are no longer in business - ZAX drove them out of these parts. It's time for you to get out too.}
{281}{}{So is it true? At first, I didn't believe the denunciations, but now I see how it turned out. This day will be a holiday for the whole wasteland. Now we just have to go home and start living from scratch. Thanks for the help.}
{282}{}{You're welcome.}

{283}{}{Hard is dead, the tinsmiths are in turmoil. Isn't it time for you to go home?}
{284}{}{So is it true? At first, I didn't believe the denunciations, but now I see how it turned out. While it is difficult to say what such a shock will turn out for the tinsmiths, but they will not get stronger soon. I think now we can go home and start life anew. Thanks for the help.}
{285}{}{You're welcome.}

{286}{}{The tinsmiths are preparing to attack. Run if life is precious.}
{287}{}{I'm not going to run because of questionable rumors.}
{288}{}{Then it will remain your problem.}

{289}{}{(Your words worked. The slaves are going to leave Two-Sun.)}
{290}{}{[Leave]}
{291}{}{You won't last in this basement if the tinkerers break through the barricades. And even more so, you will achieve nothing by your death.}
{292}{}{We have to keep fighting! You can't leave tinkerers unpunished.}
{293}{}{If you want to punish them, it's better to do it peacefully, undermining trade ties and reputation. Now you are exhausted and powerless.}
{294}{}{It's up to you.}
{295}{}{Perhaps... our situation is desperate. No food, no medicine, not even the weapons from the last convoy gives us a head start. I'll talk to the others, and let them decide by majority vote.}
{296}{}{The right idea...}
{297}{}{The tinsmiths are preparing for an attack. You have no chance.}