{100}{}{You see Hard.}
{101}{}{You see the leader of the tinsmiths. It seems that there is more iron in him than flesh.}
{102}{}{Go to your virtual world!}

#The first dialog
{200}{}{ (in front of you is something half made up of iron and electronics; his mechanical voice sounds like it comes from another world) A man from the desert. You're not in my database, I can't identify you. Tell me who you are.}
{201}{}{I'm just a man from the wasteland. I'm looking for my relatives from the Villa.}
{202}{}{Villa... The database contains information about a settlement with that name. Several slaves arrived from there. But who are you to barge in here and ask questions?}
{203}{}{Well, if you think about it, no one.}
{204}{}{Directness and assertiveness. We value these qualities. Therefore, I will give you, a primitive creature from the desert, the opportunity to show yourself... as a volunteer.}
{205}{}{I am one of the Followers of the Sacred Fire.}
{206}{}{Some of our ministers came out of this church. But here, where Two Suns shine, the rules are different from the ones you are used to. You can stay in our city but don't distract my people from important work.}
{207}{}{I am the official representative of the Brotherhood of Steel.}
{208}{}{We honor the Brotherhood of Steel. You have given us Energy and taught us how to use many forgotten technologies. How can we help one of the metal brothers?}
{209}{}{Actually, I want to see my relatives. Are they here?}
{210}{}{ (calculating something from his database) Peasants from the Villa... Your visit is late. Your tribesmen are already in the Sacred Mines in search of ancient technologies.}
{211}{}{I will have to ask several questions.}
{212}{}{I am on my way to Puerto Penasco on behalf of the Church of the Sacred Fire.}
{213}{}{You're just obsessed. You must be stopped before you send the entire population of the wasteland to the Mines.}
{214}{}{You don't know who you're talking to, you fool. Submit, you will be assimilated...}
{1214}{}{You don't know who you're talking to, you stupid wasteland creature. Submit, you will be assimilated...}
{215}{}{Well, no!}
{216}{}{What are you talking about? I'm just going to get out of here. And just try to stop me, you freak with nuts.}
{217}{}{I'll ask the questions. And you sit and answer.}

#Repeat dialog
{220}{}{Speak.}
{221}{}{See you.}

#Questions
{230}{}{Speak.}
{231}{}{That is all. I'm leaving.}
{232}{}{Another question.}

{233}{}{What is a former scout of the Brotherhood of Steel doing here?}
{234}{}{The Steel Gods have fallen. Their Olympus was destroyed by a nuclear explosion. But some managed to survive. Despite the loss of their former greatness, they still carry unique skills and knowledge inaccessible to mere mortals. We will kindly provide them with Vault. But on our terms.}
{235}{}{In other words, do you want to extract all the useful information from them and use it at your discretion?}
{236}{}{We are a nation of former military men, our vocation is to revive the greatness of the past world through technology. We will not stop because of the failure of someone else's outpost.}
{237}{}{Clear. Can I ask other questions?}
{238}{}{Well, it seems that one steel god will have a difficult life for a mere mortal.}

{240}{}{How can I save my fellow tribesmen?}
{241}{}{The only way is to go to the Forbidden Zone and find slaves. To get back out, you'll have to disable the internal security systems. This is a severe test even for tinsmiths. The chances of surviving in the Forbidden Zone are small. Talk to the instructor when you're ready to go.}
{242}{}{Why is the Restricted Area so important to you?}
{243}{}{People of the last era brought military equipment there. Over the years, a huge territory has been filled with the most valuable deposits of technology, and the center of this repository is knowledge and drawings. With free access to this repository, we could bring ancient technologies back to life. And with them the greatness of Progress throughout the Wasteland!}
{244}{}{Do you even know what to do with all this later?}
{245}{}{The Brotherhood of Steel will help in the wise use of these finds for the benefit of all mankind. We, as servants of Progress, are obliged to help the Brotherhood.}
{246}{}{What kind of Brotherhood is this?}
{247}{}{Don't you know? Not surprising. Maybe you shouldn't know, but I'll tell you. The Brotherhood of Steel is one of the military units of a bygone era. A small fragment of the past that came to our lands to revive the Old World. A worthy goal for which we tinkerers are ready to sacrifice our Tension. We also strive to have Two Suns shining over the world again.}
{248}{}{Two Suns? I only know about one thing.}
{249}{}{That's right, a pathetic man of flesh and blood. You only know the sun that shines in the sky and gives warmth to the maize shoots. But you don't know the charms of Nuclear Energy, which shines much brighter.}
{250}{}{By the way, where is this Brotherhood of Steel?}
{251}{}{You don't deserve an answer, stranger.}
{1251}{}{You don't deserve an answer, stranger.}
{252}{}{You deserve an answer. Go west past Casa Nueva. And on the shore of the Gulf of California, you will find a Steel Port - this is the citadel of the Brotherhood of Steel.}
{253}{}{Who are you?}
{254}{}{Outsiders call us tinsmiths because our passion is ancient technology. We devoted ourselves to their service, sacrificing even our mortal human bodies. Because technology will save the world and will not let it finally fade away. People will live as long as Two Suns shine, otherwise, they will be degraded to the level of savages. And this time the process will be irreversible.}
{255}{}{Are you somehow connected with the Followers of Fire?}
{256}{}{A church that was created to carry the banner of Progress, but in words more understandable to commoners. We respect and cooperate with these funny people in cassocks because their faith makes people closer to our ideas about the world. But they are one fee below us.}
{257}{}{So this is where they bring uranium from Flagstaff?}
{258}{}{Energy requires fuel. And we need a lot of energy. If it weren't for the greed of primitive creatures from Phoenix and other settlements, we would get all the uranium from Flagstaff.}
{259}{}{What will you do now that the uranium mines are ruined?}
{260}{}{As before, look for remnants of pre-war resources. We rely on the Forbidden Zone, it holds a great many resources and secrets.}
{261}{}{Is it ethical to send people to their deaths?}
{262}{}{Existence in the wastelands is survival. So let these savages survive in the Forbidden Zone and thereby benefit Progress and the whole world. Every life in our time is valuable no more than a cog in a huge machine.}
{263}{}{What if the slaves manage to disable the protection?}
{264}{}{Anyone who brings a valuable artifact from the Forbidden Zone, and even more so turns off the protective system, is waiting for freedom and the ascension of honors. We tinsmiths keep our word.}
{265}{}{Do you know that the Brotherhood of Steel is no more?}
{266}{}{Only some Progress relays are missing. Other followers will take their place. The Steel Port was not the main conduit in the network of this great organization. Their general staff is located in California and is still functioning. Someday Arizona will feel the weight of the metal of the Brotherhood of Steel again.}
{267}{}{Now that the Temple of Fire has been destroyed, are you less trusting of this cult?}
{268}{}{The faith of this church does not matter to us. Another thing is important - with her help, Arizona learned about Progress. It remains for us to properly use this opportunity and continue to broadcast our ideas by taking the vacant place in Phoenix.}

{270}{}{You've lost your humanity. And he became a soulless robot. You need to be unplugged, you fucking freak.}
{271}{}{All I know is that this energy destroyed the Old World. Are you going to do the same?}
{272}{}{We are not going to repeat the mistakes of our ancestors. We have studied their experience and become wiser. Technology should bring back civilization.}
{273}{}{People like you shouldn't even be allowed near a wrench. I will destroy you before you destroy the whole world.}
{274}{}{I need time to think about your words. See you... maybe.}
{275}{}{How interesting. I would like to know more about you and your ideas.}
{276}{}{You know, you're right. Because of a few mistakes in the past, we should not limit ourselves in development.}
{277}{}{It's good that your tiny biological brain can accept this.}
{278}{}{Yes, uh, but I have a few more questions.}

{300}{}{The Forbidden Zone is now under your control, Master Hard.}
{301}{}{ZAX has fallen! His sacred artifacts will return to us, the people for whom they were created. This is a great day for our entire nation. The beginning of a new era.}
{302}{}{Suppose you're right. But what about my people?}
{303}{}{I demand the liberation of my people from slavery.}
{304}{}{You and your people deserve freedom. You can go now. But know that we are only part of a common mechanism. Just like you. Someday the Brotherhood of Steel will come to your homes. What will you do? Be reasonable and surrender to the will of Progress. This is the only way for you to survive in the New World.}
{305}{}{I'll think about your offer. In the meantime, I have to go.}
{306}{}{And what does the Brotherhood of Steel have to do with it?}
{307}{}{We are only servants of these gods. They rule our lands in the name of Progress. They manage our resources and technologies for the development of the entire Wasteland. The story of the enslavement of the Villa was only part of this process. You are lucky to be in the center of a great change.}
{308}{}{Your point of view... deserves attention.}
{309}{}{Rub this nonsense into the rest of the tinkerers, but not me.}

#Kodi
{350}{}{They say you kidnapped Cody from Casa Grande. Is it true?}
{351}{}{The usual ignorance of the inhabitants of the wasteland.}
{352}{}{Then tell me your "official" version.}
{353}{}{What an arrogant demand. But you will receive an answer as an act of goodwill. We did not kidnap Cody but bought him out of the hands of insolvent parents who could not even feed themselves at that time.}
{354}{}{Was it that bad in Casa Grande?}
{355}{}{At the same time, this miserable settlement needed an urgent repair of the water pump. We were the only ones who could fix it. As a payment, the population gave away all their few reserves. Among the merchandise was Cody. A valuable acquisition for our team.}
{356}{}{Why do you need children?}{357}{}{Our society knows the technology, but there are certain problems with childbearing. Taking a three-year-old child and re-educating them according to their principles is one of the ways to maintain our population. The child gets survival and a decent future.}
{358}{}{You don't think his real story will remain a secret, do you?}
{359}{}{Stupid sentimentality. From now on, Cody will be a member of our Team. He is a stranger to the outside world.}
{360}{}{Yes, of course. Looks like we'd better close this conversation right now.}
{361}{}{You're wrong. He has the right to decide his fate. I'll prove it.}

{368}{}{This is a weighty argument. We agree to sign the contract. Tell your leader that we will send an ambassador to negotiate.}
{369}{}{Permission to go, Master.}
{370}{}{I'm here on behalf of the Blue Shields. We have a suggestion.}
{371}{}{What can the road savages offer us?}
{372}{}{Fuel. A lot of fuel. In exchange, they demand recognition of their independence and official trade status.}
{373}{}{Fuel will be a good alternative to uranium during its shortage. However, the Blue Shields have a criminal reputation. We don't want to risk contacting such an unreliable supplier.}
{374}{}{Ben will be angry, but there's nothing to be done. I will give him your refusal.}
{375}{}{Is there anything I can do to change your mind?}
{376}{}{Show that you can be trusted. Then we'll talk.}
{377}{}{I'll think about it.}
{378}{}{My reputation among your people is trustworthy.}
{379}{}{My help with the development of the Forbidden Territory is proof of our reliability.}

#Quests
{390}{}{You probably need someone for special assignments.}
{391}{}{We... interested.}
{392}{}{So what needs to be done?}
{393}{}{One of our caravans was attacked. We have not been able to identify the attackers. Your job is to find out who attacked the caravan. Talk to the gatekeeper, he will indicate the route to the place of the attack.}
{394}{}{So you need to walk a couple of miles? It doesn't sound very difficult.}
{395}{}{I was expecting something more solid, but this will do.}
{1395}{}{I was expecting something more solid, but this will do.}
{396}{}{Before you make a decision, let me know about the results of the investigation. You can go.}
{397}{}{I'm on my way.}

{400}{}{I found out who is behind the attack on the caravan - these are runaway slaves living in the Old City.}
{1400}{}{I found out who is behind the attack on the caravan - these are runaway slaves living in the Old City.}
{401}{}{Good job. You confirm our main version. These slaves have repeatedly made themselves felt, but only now they have begun to exert tangible pressure on Two-Sun.}
{402}{}{What to do now?}
{403}{}{These criminals attack caravans and travelers. Get rid of them Two-Sun. And as proof, return the technology items stolen from us.}
{404}{}{Why can't your people do this?}
{405}{}{Runaway slaves have only learned to hold weapons in the Forbidden Zone, but are already showing tactical skills of insurgent struggle. They are difficult to find among the ruins, and their traps are tricky and dangerous. Besides, we are servants of technology, not war.}
{406}{}{How can I resist a whole crowd of enemies?}
{407}{}{Use your brain where technology fails.}
{408}{}{What will I get for this task?}
{409}{}{We can offer more than just valuables. We offer a New World. You can enter it by becoming a part of Progress. Or stay in the dustbin of history.}
{410}{}{In the ruins, glasses with night vision would help me.}
{411}{}{ (they bring glasses to you) Use this technology rationally.}
{412}{}{This technology is not for outsiders.}
{413}{}{You won't get any more. Use what you have.}
{414}{}{I will solve this problem.}
{415}{}{Not interested. I have more important things to do.}
{416}{}{We need to talk about runaway slaves.}

{420}{}{Runaway slaves no longer threaten you.}
{421}{}{Very good. It looks like you have a vein of steel in you that we appreciate. Now provide a full report.}
{422}{}{It was like this...}
{423}{}{...We are pleased with the results. The award will be given by the quartermaster... Wait. There is one more task for you.}
{424}{}{Tell me.}
{425}{}{By completing the task, you have increased your reputation with the tinsmiths.}
{426}{}{One of our delegates went to Casa Grande but did not return. There are no messages from him on any of our communication channels. We need to find our brother and find out what happened.}
{427}{}{My new shoes won't survive this trip. I hope it's worth it.}
{428}{}{I'm on my way.}
{429}{}{...The result is satisfactory. The award will be given by the quartermaster... Wait. There is one more task for you.}

{430}{}{I managed to find a tinker in Casa Grande. He's dead. Here's the proof - his neurochip.}
{431}{}{What is the cause of death?}
{432}{}{He was killed by a Ranger spy.}
{433}{}{Ranger... We didn't expect so many problems from this organization.}
{434}{}{What does "so many" mean?}
{435}{}{After your mission, we explored the lair of runaway slaves in the Old City. There they found evidence that the slaves were supplied and trained by rangers. So they sought to undermine our reputation and economy. In other settlements, they spread false rumors about us. The Rangers have become a real threat.}
{436}{}{And what to do?}
{437}{}{We will prepare for the fight. After the Brotherhood was eliminated, there was no one else to rely on but themselves. And you can go home. From now on, the Villa is recognized by us as a neutral settlement.}
{438}{}{Damn, but they were waiting for me there. Salute, amigo.}
{439}{}{Go to the Steel Port, and inform the Brotherhood of Steel about our conflict with the Rangers. If they need help, you can count on our recommendation. If there is a future for this world, then you will find it only together with the Brotherhood of Steel. It's time for the Great Flashing.}
{440}{}{The Brotherhood of Steel? Sounds cool. Already on the way.}
{441}{}{Thank you for your trust, Master Hard. I will not shame the great idea of Progress.}
{442}{}{I understand everything, but is there no way to find a tinsmith in a strange city?}
{443}{}{A walkie-talkie will help speed up the search if you tune it to the frequency of the subcutaneous chip that the delegate had.}
