{100}{}{You see Khard.}
{101}{}{You see the leader of the tinsmiths. It looks like there's more steel in him than flesh.}
{102}{}{Go to your virtual world!}

#First dialogue
{200}{}{(you see a half-metal creature covered with electronics; it's mechanical voice sounds like it's coming from another world) Desert human. You aren't in my database, I cannot identify you. State your identity.}
{201}{}{I'm just a person wandering across the Wasteland. I'm looking for my fellow inhabitants of Villa.}
{202}{}{Villa... The database contains information about a settlement with this name. It's the source of several of our slaves. But who are you to come here and ask us questions?}
{203}{}{Well, to be honest, no one.}
{204}{}{Direct and assertive. We value these qualities. For this reason, primitive desert creature, I shall give you the ability to prove your worth... as a volunteer.}
{205}{}{I am among the Followers of the Holy Fire.}
{206}{}{Said church is the source of several of our ministers. But here, where Two Suns burn, the rules are different from the ones you are used to. You can reside in our city, but do not distract my people from their important work.}
{207}{}{I am an official representative of the Brotherhood of Steel.}
{208}{}{We honor the Brotherhood of Steel. You have given us Energy and have taught us how to use many a forgotten technology. How can we help one of our brothers-in-steel?}
{209}{}{Actually, I want to see my relatives. They're here, aren't they?}
{210}{}{(looks something up in his database) Villa peasants... You are too late. Your relatives are already in the Holy Mines, searching for ancient technology.}
{211}{}{I'll need to ask you some questions.}
{212}{}{I'm heading to Puerto Penasco to fulfill an assignment given to me by the Church of the Holy Fire.}
{213}{}{You're utterly insane. You need to be stopped before you send the entire Wasteland's population to the Mines.}
{214}{}{You lack any understanding of who you are talking to, irritant. Resistance is futile. You will be assimilated...}
{1214}{}{You lack any understanding of who you are talking to, foolish desert creature. Resistance is futile. You will be assimilated...}
{215}{}{No way!}
{216}{}{Listen here, machine freak. I'm walking outta here, and NOBODY's gonna be assimilating me.}
{217}{}{I'm going to be asking the questions here. Just sit down and answer.}

#Repeated dialogue
{220}{}{Speak.}
{221}{}{See you later.}

#Questions
{230}{}{Speak.}
{231}{}{That's all. I'm going.}
{232}{}{Another question.}

{233}{}{What's this former Brotherhood of Steel scout doing here?}
{234}{}{The gods of Steel have fallen. Their Olympus - destroyed by an atomic blast. But some survived. Though having lost their former might and power, these minds contain unique skills and knowledge, unavailaible to mere mortals. We will kindly provide them with shelter. Under our conditions.}
{235}{}{So you want to extract all useful information out of them and use it however you see fit?}
{236}{}{We are a nation of former military personnel. Our duty is to restore the greatness of the old world through the power of technology. The destruction of the Brotherhood's base means nothing to us. We shall not stop because of such trivialities.}
{237}{}{Alright. Can I ask you some other questions?}
{238}{}{Welp, looks like one god of Steel has the difficult life of a mortal ahead of him.}

{240}{}{How can I save my relatives?}
{241}{}{There is only one way - to go inside the Forbidden Zone and locate the slaves. To go back, you will need to disable the defense systems. This would prove difficult even for us, the tinsmith collective. The likelihood of your survival in the Forbidden Zone is small. If you must save your relatives, then complete preparations and talk to the instructor.}
{242}{}{Why is the Forbidden Zone so important to you?}
{243}{}{The people of the past transferred various war machines there. Over time, slowly, this giant area became filled with the most valuable of technology - and the center of this vault - with information and blueprints. Access to it would entail the restoration of many ancient technologies. And with them, the spread of the greatness that is Progress across the entire Wasteland!}
{244}{}{Do you even have a plan on what to do with all those technologies afterward?}
{245}{}{The Brotherhood of Steel will assist in the rational use of these findings. For the benefit of all mankind. As servants of Progress, we are required to help the Brotherhood.}
{246}{}{What Brotherhood?}
{247}{}{You do not posess this information? Unsurprising. Perhaps you are not supposed to know, but I will share my information regardless. The Brotherhood of Steel is a military unit from a bygone era. A small fragment of the past that has come into our lands to resurrect the Old World. For such a worthy goal, we, the tinsmith collective, are willing to sacrifice our Voltage. In addition, we strive for the world to be illuminated once again by Two Suns.}
{248}{}{Two Suns? I know of only one.}
{249}{}{Correct, pathetic creature of blood and flesh. You posess information on only the sun in the sky, that gives warmth to maize crops. But you are ignorant of the beauty that is Nuclear Energy, which shines much brighter.}
{250}{}{By the way, where is this Brotherhood of Steel located?}
{251}{}{You do not deserve to receive this information, outsider.}
{1251}{}{You do not deserve to receive this information, outsider.}
{252}{}{You deserve to receive this information. Head west, past Casa Nueva. On the shores of the Gulf of California you will find Steel Port - the designation given to the Brotherhood's citadel.}
{253}{}{Who are you?}
{254}{}{Outsiders have given us the designation 'tinsmith', due to our passion for ancient technology. We have dedicated ourselves to them, sacrificing even our mortal human bodies. They will save this world and not let it fade away into nothingness. While Two Suns shine, humanity will survive. Otherwise, it will degrade to the level of primitives and savages. This time, permanently.}
{255}{}{Are you affiliated with the Followers of the Holy Fire?}
{256}{}{It is a church that carries the banner of Progress, but in a way that is more understandable for the general population. We respect and cooperate with these amusing robed individuals, as their faith brings others closer to our way of thinking. But they are not our equals.}
{257}{}{So this is where all the uranium from Flagstaff ends up.}
{258}{}{Energy requires fuel. Our energy requirements are high. Only the greed of primitive inhabitants of Phoenix and other surrounding settlements stands in the way of us receiving all Flagstaff uranium.}
{259}{}{What will you do now that the uranium mines are no longer operational?}
{260}{}{As before, search for remains of Pre-War resources. Our hopes are placed on the Forbidden Zone. It contains a great many resources and knowledge.}
{261}{}{You think it's justified to send people out to die?}
{262}{}{Wasteland existence is survival. Let the primitives survive in the Forbidden Zone and bring benefit to both Progress and all of humanity. In our time, the value of the individual is simply to be a cog in a colossal machine.}
{263}{}{What if the slaves manage to disable the security grid?}
{264}{}{Freedom and respect awaits anyone who brings a valuable artifact from the Forbidden Zone, to say nothing of those who disable the security grid. We, the tinsmiths, keep our word.}
{265}{}{Are you aware that the Brotherhood of Steel has ceased to exist?}
{266}{}{Destruction has met merely a few relays of Progress. Others will take their place. Steel Port was not the main conductor of this great organization. Their headquarters are located in California, and are fully operational. Arizona will one day feel the Brotherhood's crushing weight once again.}
{267}{}{Now that the Temple of Fire has been destroyed, I take it you're less trusting of the cult?}
{268}{}{The church's faith is irrelevant. What is relevant is that thanks to it, Arizona has learned of Progress. All that is left for us is to use this opportunity and continue transmitting our ideas by taking their place in Phoenix.}

{270}{}{You've become an inhuman, soulless robot. It's time to unplug you, you ugly son of a bitch.}
{271}{}{All I know is that this energy destroyed the Old World. Are you planning on doing the same?}
{272}{}{We have no intention of repeating the mistakes of our forebears. We have learned much from their experience and have become wiser. Only technology can meaningfully restore civilization.}
{273}{}{People like you will find a way to turn even a wrench into a way to implement your twisted plans. I'll destroy you before you all destroy the world.}
{274}{}{I need some time to think about your words. Maybe we'll see each other again sometime... or not.}
{275}{}{How interesting. I would like to know more about you and your ideas.}
{276}{}{I see now that I was wrong. We shouldn't restrict our development because of a few mistakes we made a long time ago.}
{277}{}{It is good that your puny biological brain is capable of accepting this truth.}
{278}{}{Yes, but I, uhh... have a few more questions.}

{300}{}{The Forbidden Zone is now under your control, Master Khard.}
{301}{}{ZAX has fallen! It's holy artifacts will return to those for whom they were created for - human beings. This is a great day for our entire nation. It is the beginning of a new era.}
{302}{}{Let's suppose you're right. But what about my people?}
{303}{}{I demand my people to be freed from slavery.}
{304}{}{You and your people have earned freedom. You may go. But know that we are but a component of a large system. As are you. One day, the Brotherhood of Steel will arrive to your home. What will you do then? The only logical choice is to surrender to Progress. It is the only way for you to survive in the New World.}
{305}{}{I'll think about it. Meanwhile, I should go.}
{306}{}{What does the Brotherhood of Steel have to do with any of this?}
{307}{}{We are but servants of these gods. They rule over us in the name of Progress. They manage our resources and technology to develop the entire Wasteland. Villa's enslavement was only a small part of this process. You were lucky to be in the very center of a great change.}
{308}{}{Your beliefs... deserve some consideration.}
{309}{}{Say that nonsense to other tinsmiths, not me.}

#Cody
{350}{}{They say you stole Cody from Casa Grande. Is that true?}
{351}{}{Typical wastelander ignorance.}
{352}{}{Tell me your "official" version, then.}
{353}{}{Very demanding for someone like you. But you will receive an answer as an act of goodwill. We did not steal Cody, we bought him from struggling parents unable to fulfill even their own nutritional needs.}
{354}{}{Were things really that bad in Casa Grande then?}
{355}{}{At that time, the pathetic settlement was in dire need of repair for their water pump. We were the only ones who could provide this service. As payment, the settlement gave us the entirety of what little supplies they had. Among them was Cody. A valuable acquisition for our collective.}
{356}{}{Why do you need to acquire children?}
{357}{}{Our society knows how to utilize technology well, but there are certain problems with the reproductive process. Acquiring and re-educating small children is one of the ways to support our population. This relationship is highly beneficial to the child - we ensure their survival and provide them with a worthy future.}
{358}{}{You don't think what really happened is going to remain secret, do you?}
{359}{}{Mere sentimentality. From this moment on, Cody is a member of our Collective. For the rest of the world, he is an outsider.}
{360}{}{Yes, of course. Looks like it's better to leave this at that.}
{361}{}{No. He has the right to decide his own destiny. I'll prove it.}

{368}{}{It is undeniable that there is logic in your words. We agree to sign a contract. Tell your leader that we will send an ambassador to negotiate.}
{369}{}{Permission to leave, Master?}
{370}{}{I'm here on behalf of the Blue Shields. We have an offer.}
{371}{}{What can the highway savages offer us?}
{372}{}{Gasoline. A whole lot of gasoline. In return, they ask you to recognize their independence.}
{373}{}{Gasoline will be a good alternative to uranium during times of scarcity. However, the Blue Shields have an established criminal reputation. The risk posed by dealing with such an unreliable supplier is too high for us to take.}
{374}{}{Ben will be mad, but there's nothing I can do. I'll tell him about your refusal.}
{375}{}{Perhaps something will change your mind?}
{376}{}{Show us that you can be trusted. Then we'll talk.}
{377}{}{I'll think about it.}
{378}{}{My reputation among your people deserves your trust.}
{379}{}{My help with the conquest of the Forbidden Zone is evidence enough of our reliablity.}

#Quests
{390}{}{You probably need someone for special assignments.}
{391}{}{We... are interested.}
{392}{}{So, what do I need to do?}
{393}{}{One of our caravans was attacked. The attempt at identifying the attackers failed. We must know their identity - your mission is to discover it. Speak to the gatekeeper. He will show you a route to the site of the attack.}
{394}{}{So I just need to walk a few miles? Doesn't sound too hard.}
{395}{}{I expected something better, but this will do.}
{1395}{}{I expected something better, but this will do.}
{396}{}{Before making a decision, report to me about the results of the investigation. You can go now.}
{397}{}{Already am.}

{400}{}{I found out who was behind the caravan attack - runaway slaves living in the Old City.}
{1400}{}{I found out who was behind the caravan attack - runaway slaves living in the Old City.}
{401}{}{You've performed well. Your findings confirm our main theory. These slaves have already made their presense known several times, but only now are they beginning to meaningfully impact Two Sun.}
{402}{}{What do I do now?}
{403}{}{These criminals are attacking travelers and caravans. Rid Two Sun of them. As proof - bring back the technologies they stole from us.}
{404}{}{Why can't your people do it themselves?}
{405}{}{The runaway slaves have learned to hold weapons only in the Forbidden Zone, but are already showing knowledge of guerilla tactics. They are hard to detect among the ruins, their traps are cunning and dangerous. And besides, we are servants of technology, not war.}
{406}{}{How do I fight against an entire crowd of enemies?}
{407}{}{Where technology fails, use your head.}
{408}{}{What will I receive for completing this assignment?}
{409}{}{We can offer more than simple material rewards. We offer the New World. You can either become part of Progress, or you can get left behind in the dustbin of history.}
{410}{}{I could use some night-vision goggles in those ruins.}
{411}{}{(a tinsmith brings you the goggles) Use this technology rationally.}
{412}{}{This technology is not for outsiders.}
{413}{}{You will not receive anything else. Use your own equipment.}
{414}{}{I'll solve this problem.}
{415}{}{Not interested. I've got more important stuff to do.}
{416}{}{We need to talk about the runaway slaves.}

{420}{}{The runaway slaves pose no more threat to you.}
{421}{}{Very good. You get the mission completed. We value this. Now tell me the full report.}
{422}{}{This is how it went down...}
{423}{}{... We are pleased with the results. The quartermaster will hand out the reward... Wait. There is another assignment for you.}
{424}{}{What is it?}
{425}{}{By completing the assignment, you've increased your reputation among the tinsmiths.}
{426}{}{One of our delegates went to Casa Grande, but has not arrived back. There are no messages from him on any of our communication channels. It is necessary to find our brother and figure out what happened.}
{427}{}{My new boots won't survive this trip. I hope it will be worth it.}
{428}{}{Already on my way.}
{429}{}{Results are... acceptable. The quartermaster will hand out the reward... Wait. There is another assignment for you.}

{430}{}{I managed to find a tinsmith in Casa Grande. Or rather, his corpse. Here's the evidence - his neural chip.}
{431}{}{Cause of death?}
{432}{}{Murdered by a Ranger spy.}
{433}{}{The Desert Rangers... We did not anticipate so many problems from that organization.}
{434}{}{What do you mean, "so many"?}
{435}{}{After your last mission, we extensively studied the base of the runaway slaves in the Old City. We found evidence that the slaves were supplied and trained by the Rangers. They were seeking to undermine our reputation and sabotage our economy. In other settlements, they are spreading false rumours about us. It is clear that the Rangers have become a real threat.}
{436}{}{What will you do?}
{437}{}{Prepare for war. After the destruction of the Brotherhood of Steel, we can only rely on ourselves. You can head home. From this day forward, we will recognize Villa as a neutral settlement.}
{438}{}{Damn, they must be missing me back there. Adios, amigo.}
{439}{}{Head to Steel Port. Report to the Brotherhood about our conflict with the Rangers. If they require assistance, you can count on our recommendation. If this world does have a future, it is only with the Brotherhood of Steel. The time has come for the Great Update.}
{440}{}{The Brotherhood of Steel? Sounds interesting. I'm already on my way.}
{441}{}{I thank you for your trust, Master Khard. I will not dirty the great idea of Progress.}
{442}{}{I understand, but is there no way to find a tinsmith in another settlement?}
{443}{}{A radio would help, if it was set to the frequency of the delegate's neural chip.}