{100}{}{You see Carlos.}
{101}{}{Here is one of the peasants of the Villa. However, he became somehow... other.}
{102}{}{They say real science is coming back to Casa Nueva. Like before the Great War. I have to be there.}
{103}{}{I'll be back home... to make it more civilized.}
{104}{}{I have no choice but to go on a journey. I hope to see a lot of new things.}
{105}{}{How... how can you...}
{106}{}{You... it's your fault...}

#The first dialog
{200}{}{? You... why are you here?}
{201}{}{Obviously to save your ass, Carlos. Let's get out of here...}
{202}{}{Salvation... Salvation from what? From the mouse fuss in the beds with dying crops? From diseases for which the peasants will never find a cure? From enemies against whom we didn't even have primitive rifles? I don't see salvation. I see only the narrow and limited horizons of a handful of diggers.}
{203}{}{Who are you talking about?}
{204}{}{We are savages, amigo, understand this. Savages who saw electric light for the first time only after being in slavery. It was like living in a tin can until someone opened it and showed us the vast world around. And the Villa turned out to be only a small part of it, and not the center, as previously thought.}
{205}{}{Wait a minute...}
{206}{}{Only here I was able to realize myself and my talents. Because my passion for technology was banned in my homeland. I hid it so as not to cause problems for myself and others. Now I am free to follow the call of my mind, and not drag myself after the pack. Go away, amigo. Leave me here.}
{207}{}{I'll leave you for now. But don't think you'll get rid of me so easily.}
{208}{}{I don't think I'm going to dissuade you. Goodbye, amigo.}

{210}{}{Villa time is over, understand this.}
{211}{}{Okay, okay, finish it already.}

{230}{}{Can you explain what's going on here?}
{231}{}{Tinsmiths are trying to open the burial of ancient equipment in the Forbidden Zone. They need local technologies and resources to expand and promote the idea of Progress. But the territory is well protected. Periodically, detachments of slaves and mercenaries are sent there, usually none of them returns.}
{232}{}{Tell me about the tinsmiths.}
{233}{}{This is a semi-religious clan with an old history. They want to revive the ancient technologies they worship in order to put them in the service of people.}
{234}{}{Tell me about the Restricted Area.}
{235}{}{This is a burial ground - the burial of ancient equipment, mainly for military purposes. Therefore, the territory is well fortified and guarded by robots. The tinkerers have found a way to disable the power barrier at the main gate for a short time, but this is not enough. If you're going to go inside, you'll need a special weapon against robots and a package of anti-radiation drugs.}
{236}{}{Who else was here from the Villa besides you?}
{237}{}{Your padre and Gerardo. They have already been sent to the Restricted Area. If you want to save them, you'll have to go after them.}
{238}{}{I'm going to go to the Restricted Area. Carlos, I really need help.}
{239}{}{I... can't help you... The tinsmiths keep a close eye on me and keep a clear record of their warehouses.}
{240}{}{Thanks for the answers. Now it's time for me to get busy.}
{241}{}{Come on, the tinkerers should be interested in my success!}
{242}{}{(looks around) I can give you something. These are pulse grenades. They say you can kill a robot with such a weapon at a time. Use them as a last resort.}
{243}{}{Thank you, Carlos. You helped me a lot.}
{244}{}{Back to other questions.}
{245}{}{It's too dangerous. I'm sorry.}

#Power Cell
{250}{}{I need a power cell for the generator. Can you get it?}
{251}{}{Don't ask me for anything! The tinkerers won't like it if I distribute technology without their permission.}
{252}{}{It is very important. Help me!}
{253}{}{No and no again! I'm not going to risk my place for the benefit of a handful of diggers.}
{254}{}{You're saying hurtful words. See you later.}
{255}{}{Come to think of it, I know how to stay out of suspicion...}
{256}{}{That's a good girl.}
{257}{}{(looks around) If they ask, I have nothing to do with it.}
{258}{}{Come on, amigo.}
{259}{}{We'll see about that...}

#Care
{300}{}{So are you going back to the Villa?}
{301}{}{Don't even ask. Until they kick me out of here, I won't leave myself.}
{302}{}{I won't do it anymore. Have a good stay.}
{303}{}{You're just a fool. And you will remain a fool.}
{304}{}{Too late. The tinkerers have been defeated, the territory is under the control of a hostile machine. Staying here, you'll just die.}
{305}{}{After the death of Master Hard, the locals became even more intolerant of outsiders. Don't you notice that?}
{306}{}{Have you already heard the news about your "thefts"?}
{307}{}{So this is your doing? Ooh... It looks like you have a serious attitude.}
{308}{}{You can't hide anywhere. My padre has ordered you to be returned alive or dead.}
{309}{}{I'm sorry, but this is the only way to bring you to reason.}
{310}{}{This is not your world. My padre says the same.}
{311}{}{This is not your world, amigo. Here you are only a worker, but not a member of society.}
{312}{}{So far it is. But I'm growing above myself. And someday I will be able to join the ranks of tinsmiths on equal terms.}
{313}{}{We'll see about that...}
{314}{}{Right. Tinkerers are distrustful of the rest of the inhabitants of the Wastelands. Their trust can only be achieved by fanaticism about technology. It will be very difficult to join their ranks as equals.}
{315}{}{Then go back to the Villa and bring your knowledge there - that's your way.}
{316}{}{Finally I hear the voice of reason in all this nonsense.}
{317}{}{}
{318}{}{Damn it... I've already made my decision, and you have no idea how hard it was. But it looks like I have no choice left.}
{319}{}{So what have you decided?}

{320}{}{I can't go back to the Villa after everything that happened. I will not be accepted there, and my knowledge and skills will remain useless. You know how stubborn our relatives are.}
{321}{}{But are there places where your talents will be in demand?}
{322}{}{Hmm. Phoenix? No, it's a crappy place where the caps decide too much. That leaves Casa Nueva. Caravaneers told about this small settlement. They say there's a whole scientific laboratory where the best brains of Arizona flock.}
{323}{}{So what prevents you from going there?}
{324}{}{This is a kind of closed settlement. Maybe I just won't be accepted. While I'm here trying to make a new life, can you go to the scientists and talk about my vacancy?}
{325}{}{Of course, amigo. I'll do it out of old friendship.}
{326}{}{Thank you, }
{327}{}{. I'm waiting for news.}
{328}{}{See you later.}
{329}{}{No, I have to go home. Solve your problem yourself.}
{330}{}{Sorry. But if you happen to be around, tell one of the scientists about me, okay?}
{331}{}{I can't promise anything.}
{332}{}{Of course, absolutely.}

{340}{}{We've already discussed this. I can't go home.}
{341}{}{As you wish. Bye.}
{342}{}{Fools don't change. Goodbye.}
{343}{}{I have good news. The followers of the Apocalypse have agreed to accept you with all your knowledge and skills.}
{344}{}{This is encouraging. Don't worry about me, I'll find my way. Thank you for everything.}
{345}{}{The main thing is that you don't work for these damn tinkerers. Come on, get out.}
{346}{}{Maybe someday I'll leave the village for good, like you. Goodbye.}
{347}{}{I'm sorry, but the Followers of the Apocalypse are in the deepest crisis. You won't be able to join them.}
{348}{}{Is it that bad? I've already heard rumors from the caravaneers. Well, it looks like there's no choice anymore. I'll have to go on a trip. I don't know where exactly yet. Maybe east to California. Or to the south, to the New Mexican State. But you definitely won't have to sit still.}
{349}{}{And what, not a bad idea.}
{350}{}{Goodbye, }
{351}{}{. Thanks for everything.}