{100}{}{You see Cody.}
{101}{}{You see a bald child in baggy clothes. His hands remember no rest from labor.}
{102}{}{I'll do everything in my power to make the world a better place.}

#First dialogue
{200}{}{(You see a bald child in baggy clothes. He's trying hard to ignore you.)}
{201}{}{Hey, kid. Where are your parents?}
{202}{}{(cautiously looks around and returns to his duties, muttering the answer under his nose) I... don't have parents.}
{203}{}{How does that work? You were lathed in a machine shop?}
{204}{}{I'm sorry, I didn't mean to offend. But how'd you end up here?}
{205}{}{[Repeat after him]}
{206}{}{My parents died during the war in Casa Grande, and I was left alone on the streets. But the tinsmiths saved me from starving to death. I've been here ever since.}
{207}{}{Hm. That's quite honorable of them.}
{208}{}{Outsiders shouldn't concern themselves with our business.}
{209}{}{Considering the tinsmiths' reputation, this story sounds pretty doubtful. Wouldn't you agree?}
{210}{}{(angrily looks away) How would you know what happened? You're an outsider. You don't know anything. You should go.}
{211}{}{Okay, kid, if you say so.}
{212}{}{If we were out in the Wastes, you wouldn't be talking to me like that. You're lucky we're here.}

{220}{}{What's your name, kid?}
{221}{}{Right now they're calling me Cody, as I was called before. But when I'm initiated into being a tinsmith myself, I'll receive my own identifier and my old name will remain in the past.}
{222}{}{I see.}
{223}{}{How do the tinsmiths treat you?}
{224}{}{Quite well. They feed and clothe me, and only give me work I can handle. Nobody is hurt here. But if you break the rules or try to break something, there will be a painful punishment.}
{225}{}{I see.}
{226}{}{Do you have any friends here?}
{227}{}{Of course. Nobody prohibits people from talking to each other and even playing. Though some games are forbidden, since Khard says they mess with the brain and distract from important business.}
{228}{}{I see.}

#Repeat dialogue
{250}{}{Go away. I can't talk to outsiders.}
{251}{}{Consider me not here.}
{252}{}{By the way, I could go have a look in Casa Grande, if you want, and ask a couple of...}
{253}{}{No! This is my home now, and the tinsmiths treat me very well. You'll just get me in trouble. Leave me alone! (fearfully turns around and walks away)}
{254}{}{Oh, sorry...}
{255}{}{Go ahead, kid. Throw out all that crap you've got swelling up inside you from their way of upbringing.}

{260}{}{I think you should know. The tinsmiths didn't save you. They accepted you as payment for repairing a water pump.}
{261}{}{Nonsense! You're an outsider, where could you know this from?}
{1261}{}{Nonsense! You're an outsider, where could you know this from?}
{262}{}{I found your parents in Casa Grande.}
{1262}{}{I found your parents in Casa Grande.}
{263}{}{They're... alive? But... Why have the others lied to me all this time?}
{264}{}{As I understand it, the tinsmiths were trying to block any memories that could interfere with your assimilation into their Collective.}
{265}{}{You know, adults lie sometimes. For instance, to use someone for our own purposes.}
{266}{}{(defeated) So my parents sold me, and my new family lied to me for years? I don't even know what to think anymore.}
{267}{}{That's for you to decide, Cody.}
{268}{}{I'm thankful to you for opening my eyes. I need to think hard about all this.}
{1268}{}{I'm thankful to you for opening my eyes. I need to think hard about all this.}
{269}{}{Of course. I hope you arrive at the right conclusions. Farewell, little guy.}
{270}{}{What's that, your little world is crumbling before your eyes? Yeah, the tinsmiths turned out to be sly and deceitful bastards, haven't they?}
{271}{}{Don't think I'll start hating this place now. But nobody is going to trick me that easily anymore.}
{272}{}{I like your thinking. Don't let the tinsmiths turn you into a soulless cog in their machine.}
{273}{}{Despite everything, they did give you a much better life than the slums of Casa Grande ever could. Believe me, that dump has nothing human left.}
{274}{}{People usually dislike tinsmiths. If you, a wasteland outsider, praise Two Sun, I can only conclude it really is the best place in the world.}
{275}{}{That's right. Make Two Sun an example for the rest of the wasteland to follow, kid.}
{276}{}{Listen, are you sure my parents died?}
{277}{}{Khard himself told me so. I believe him.}
{278}{}{I think I'll have to have a talk with him...}

