{100}{}{You see Cody.}
{101}{}{In front of you is a bald child in baggy clothes. His hands do not remember rest from work.}
{102}{}{I will do everything to make the world a better place.}

#The first dialog
{200}{}{(In front of you is a bald child in baggy clothes. He studiously ignores you.)}
{201}{}{Hey, where are your parents, baby?}
{202}{}{(looks around warily and returns to his business, muttering the answer under his breath) I have... no parents.}
{203}{}{How is that? Do you really want to say that you were made on a lathe?}
{204}{}{I'm sorry, I don't mean to offend. But how did you end up here?}
{205}{}{[Do the same]}
{206}{}{My parents died during the war in Casa Grande, and I was left alone on the street. But the tinkerers saved me from starvation. I've been here ever since.}
{207}{}{Hmm. This is very noble of them.}
{208}{}{Outsiders should not meddle in our affairs.}
{209}{}{Given the reputation of tinsmiths, this story sounds rather dubious. Don't you find it?}
{210}{}{(looks away viciously) How do you know what happened there? You're an outsider. You don't understand anything. You'd better go.}
{211}{}{Okay, baby, whatever you say.}
{212}{}{If we were in the wastelands, you wouldn't say that to me. You're lucky we're here.}

{220}{}{What's your name, baby?}
{221}{}{So far, my name is Cody, just like before. But when I am initiated into the tinsmiths, I will get my own ID, and the old name will remain in the past.}
{222}{}{I see.}
{223}{}{Are the tinsmiths treating you well?}
{224}{}{Quite. They feed and clothe me, and they give me work only on my strength. No one is offended here. But if you break the rules or try to harm something, the punishment will be quite unpleasant.}
{225}{}{I see.}
{226}{}{Do you have any friends here?}
{227}{}{Sure. No one forbids to communicate with each other and even play. However, some games are banned because Hard says that they interfere with the brain and distract from important things.}
{228}{}{I see.}

#Repeat dialog
{250}{}{Go away. I'm not allowed to talk to strangers.}
{251}{}{Consider me not here.}
{252}{}{By the way, I can stop by the Casa Grande if you want and ask a couple...}
{253}{}{I don't want to! This is my home now, and the tinsmiths treat me very well. You're only going to make trouble for me. Leave me alone! (turns around in fright and walks away)}
{254}{}{Oh, I'm sorry...}
{255}{}{Come on, kid, throw out all the shit that you have accumulated because of your local upbringing.}

{260}{}{I think you should know that. The tinkerers didn't save you, but accepted you as payment for repairing the water station.}
{261}{}{Nonsense! You're a stranger, how can you know that?}
{1261}{}{Nonsense! You're a stranger, how can you know that?}
{262}{}{I found your parents in Casa Grande.}
{1262}{}{I found your parents in Casa Grande.}
{263}{}{They... are they alive? But... Why have the others been lying to me all this time?}
{264}{}{As I understand it, the tinkerers tried to block the memories that could prevent your assimilation into the Collective.}
{265}{}{You know, sometimes adults lie. Well, for example, to use someone for selfish purposes.}
{266}{}{(contrite) So my parents sold me, and my new relatives kept me in a lie for years? I do not know what to think now.}
{267}{}{It's up to you, Cody.}
{268}{}{I'm grateful to you for opening my eyes. Now I need to think about all this carefully.}
{1268}{}{I am grateful to you for opening my eyes. Now I need to think about all this carefully.}
{269}{}{Sure. I hope you come to the right conclusions. Goodbye, man.}
{270}{}{What is it, the world is collapsing before your eyes? Yes, the tinsmiths turned out to be cunning and deceitful creatures, didn't they?}
{271}{}{Don't think I'm going to hate this place now. But now no one will fool me so easily.}
{272}{}{I like your way of thinking. Don't let the tinsmiths make a soulless part of you in a big machine.}
{273}{}{Anyway, they gave you a much better life than the Casa Grande slum. Believe me, there's nothing human left in that hole.}
{274}{}{Tinsmiths are usually disliked. If you, a stranger from the wasteland, praise Two-Sun, then I can only believe that this is really the best place on earth.}
{275}{}{Exactly. Make Two-Sun a model for the whole wasteland, boy.}
{276}{}{Listen, are you sure your parents are dead?}
{277}{}{Hard himself told me about it. I believe him.}
{278}{}{Looks like I'm going to have to talk to him about something...}