{100}{}{You see the guard.}
{101}{}{In front of you is a caravan guard. He is resting after a tiring journey.}

{110}{}{Great.}
{111}{}{Let me rest.}
{112}{}{Do you want to travel with us?}
{113}{}{There is a restless road between Phoenix and Fog.}
{114}{}{Dust storms are sometimes more dangerous than raiders.}
{115}{}{We have a dangerous job.}
{116}{}{Talk to the boss, I'm just guarding the cargo.}
{117}{}{I'd stay away from tinsmiths if I were you.}
{118}{}{Need some advice? Don't go to the local doctor.}
{119}{}{I'd rather go back to Phoenix.}
{120}{}{Tinsmiths don't like strangers and try to avoid unnecessary conversations.}
{121}{}{I'm scared of these tinsmiths - they're like robots.}