{100}{}{You see merchant Clark.}
{101}{}{You see the manager of the caravan. His dark skin speaks of uncountable miles traversed under the scorching sun.}
{102}{}{Good luck.}
{103}{}{Well, we're here. Brotherhood fort's up the road.}

{200}{}{What?}
{201}{}{Maybe we could get to know each other? I'd like to have a few contacts in an unknown place.}
{202}{}{I'm not good for that. I manage caravans. I have a special contract with the tinsmiths - more acquaintances are the last thing I need. But I get you. I used to be a stranger in this place as well, when I first showed up here.}
{203}{}{Looks like you might know something. I'd like to ask you a few questions.}

{210}{}{What?}
{211}{}{Nothing.}
{212}{}{I wouldn't mind chatting some more.}

{220}{}{What is it you do?}
{221}{}{I move cargo through the desert. Tinsmiths don't trust anyone else to do it quite like they trust me.}
{222}{}{Just moving things through the desert? Who in the world would that be useful to?}
{223}{}{I know, it sounds weird, but there really are a few places in the desert where they're waiting in anticipation to receive that stuff. They pay a ton of caps for it, too.}
{224}{}{Are slaves among that cargo?}
{225}{}{Not anymore. Back in the day, they were transferred from Phoenix in droves, to clean the ruins up and build new structures. But now, the demand for this is basically non-existent. Slaves became popular in the north after that, though.}
{226}{}{This Phoenix place - where is it?}
{227}{}{You really don't know? Oh, you missed a lot, then. It's a big city to the north. Go along the 10th highway, you won't miss it.}
{1227}{}{You really don't know? Oh, you missed a lot, then. It's a big city to the north. Go along the 10th highway, you won't miss it.}
{228}{}{Thanks.}

{230}{}{So, who are those tinsmiths really?}
{231}{}{They're something of a cult. They worship technology and progress. Their greatest dream is to acquire robotic bodies and put their consciousness in them. Sounds wild, doesn't it? But they're already integrating wires and stuff into themselves. No one in Sonora is as good with technology as they are.}
{232}{}{What are their immediate plans?}
{233}{}{I dunno, I just move cargo. But they're obviously planning something big.}
{234}{}{Why do you think so?}
{235}{}{They're buying up a ton of uranium ore and slaves. Probably found a big pile of old tech. That means serious investments in Phoenix or some other place, I hear. Yeah, I sense that my caravan will be making a lot of money in the next few years.}
{236}{}{You aren't going to that place where an entire port just blew up, are you?}
{237}{}{Well, there is barely anything left there. But still, there are the Casa Nueva plantations along the way. Though now that I think of it, how long will they be able to survive without Brotherhood of Steel protection? Sooner or later, the settlement will either be abandoned or will submit to the will of the tinsmiths. It's only a matter of time.}
{238}{}{Either way, life isn't going to improve there. Maybe we should change the subject?}

{240}{}{Is it hard moving cargo through the Wastes?}
{241}{}{We're unbeatable at it. We adapt and wait for the seasons most fit for travel.}
{242}{}{What dangers await in the barren lands of Sonora?}
{243}{}{Biggest one is, of course, dehydration and starvation. We get water ahead of time in Casa Grande. That's enough to reach the Bay. There, we desalinate sea water.}
{244}{}{What about animals?}
{245}{}{Nothing can survive in these sands. Well, except radscorpions. Looks like they've chosen Sonora as the place to breed their offspring. The good thing is that we have basically never encountered bandits. People are a rarity in those places.}
{246}{}{Your tales only serve to warm my curiosity. I would like to know more.}
{247}{}{Thanks for the information. I'll go prepare to depart.}

{300}{}{I need to get to Steel Port.}
{301}{}{Steel Port? First time I hear about this place in my life.}
{302}{}{You can trust me.}
{303}{}{Don't worry, I'm part of the Brotherhood.}
{304}{}{Don't worry, I'm a Follower of the Holy Fire.}
{305}{}{What a shame. Perhaps you *have* heard of other places.}
{306}{}{Believe me, no caravan goes there anymore. Something went horribly wrong there. Whole ship exploded like a damn boom bug. Now, in it's place, there's just one big radioactive crater and not a single living person.}
{307}{}{How very... unexpected.}
{308}{}{I don't believe it.}

{310}{}{Alright, I see you can be trusted. But we gotta be careful. The Brotherhood has many enemies, after all.}
{311}{}{So, I can go with your caravan?}
{312}{}{We gather at 6 o'clock in the morning. Don't be late. You can carry no more than 150 pounds worth of cargo. Keep in mind that we'll be making a stop at Casa Nueva. It's the only settlement on the way to the Brotherhood.}
{313}{}{I can head out.}
{314}{}{I'll come at the specified time.}
{315}{}{No one is going to carry your stuff! Get rid of the excess cargo, or we'll leave without you.}
{316}{}{That will be my problem.}
{317}{}{Whatever you say.}
{318}{}{Alright, get ready for a hard journey through the Wasteland.}
{319}{}{[Head out]}
{320}{}{Maybe. Maybe not.}
{321}{}{Fine, I'll take another look at my backpack.}
{322}{}{I'll pay you 1000 caps to go with your caravan.}
{323}{}{You sure you've got that many caps?}
{324}{}{Let me count...}

#Other locations
{400}{}{We'll rest for a bit here. You have some time to look around. Don't oversleep - if you aren't there by the specified time, we'll leave without you.}
{401}{}{What can you tell me about this settlement?}
{402}{}{Casa Nueva is a thriving oasis in the middle of the desert. It's the best place to live among all the ones I know about. But things are quite strict here. Be especially respectful and careful in dealing with the locals here.}
{403}{}{Bye.}
{404}{}{[Wait until the caravan departs]}
{405}{}{You can leave without me. I'm going to stay here for some time.}
{406}{}{As you wish. But keep in mind that travel through the barren wastes of Sonora isn't easy even in a caravan.}
{407}{}{I know. Goodbye.}