{100}{}{You see a peasant.}
{101}{}{You see a fairly regular peasant. They stick out, considering their surroundings.}
{102}{}{Thanks for the help. We won't forget it. We'll spread the word of what you've done.}

{200}{}{Hey, you're not a local, right? I can tell - you don't have that look. Let me give you some free advice - don't associate with these hucksters. They have no regard for outsiders.}
{201}{}{And you are?}
{202}{}{And I'm another victim of their dishonesty, if you'd like to know. The tinsmiths are refusing to sell my settlement power cells for our generators. And why? Because they say we aren't "worthy" of old technologies!}
{203}{}{Tell me more.}
{204}{}{Well that's your problem, not mine. Bye.}

{210}{}{What do you want to know?}
{211}{}{No more. Bye.}
{212}{}{I have to go.}
{213}{}{Tell me more.}

{220}{}{Tell me about your settlement.}
{221}{}{We're just a simple peasant community. Recently, our generator powered down - that was the only source of electricity for our entire valley. We had to go to the tinsmiths for help, but they think us small and undeveloped.}
{222}{}{Is the generator that important to you?}
{223}{}{Our entire community depended on it! The lighting, the water pump, the radio - without those things, our valley will once again turn into a desert, and will become unfit for life.}

{230}{}{Isn't there any other source of those power cells?}
{231}{}{The tinsmiths are the ONLY ones who produce them in our time. And Pre-War cells have become rather hard to find lately. Those technofetishists had plundered everything nearby long ago.}
{232}{}{Have you tried looking for them in Phoenix?}
{233}{}{You kidding? We're settled, crossing that kind of distance would be an enormous challenge. And even then, the Big City's also buying their batteries from the tinsmiths. And their prices are much higher.}

{240}{}{Why don't the tinsmiths want to trade with you?}
{241}{}{They consider us unworthy of their technology. They think we'd just waste their valuable resources. But that's nonsense - we need those cells to survive, what could be more important than that?!}

{250}{}{So what are you going to do now?}
{251}{}{We need those power cells right away... Hey, listen, you're a peasant too, like us, right? I can see it. For all the clothing and armor you can hide behind, your eyes and hands will always give it away. We have to stick together, amigo. Help us, and we'll help you in return.}
{1251}{}{We need those power cells right away... Hey, listen, you're a peasant too, like us, right? I can see it. For all the clothing and armor you can hide behind, your eyes and hands will always give it away. We have to stick together, amigo. Help us, and we'll help you in return.}
{252}{}{Why would I help you?}
{253}{}{I have many friends among the caravaneers. I could ask them to let you travel with them. That, and I'll increase your reputation. Even further, I'll give you some Pre-War money. It doesn't look like people really use it anymore, but maybe some places still do.}
{254}{}{I'll think about it.}
{255}{}{Who can I talk to about these power cells?}
{256}{}{They should be in the storage room, in that big hangar. They have a quartermaster there guarding it. I doubt he'll change his mind.}
{257}{}{We'll see about that.}
{258}{}{So in other words, you're asking me to steal from the tinsmiths?}
{259}{}{Well, they've stolen from many others as well. You'd save a whole settlement and make some friends. Some honest friends, unlike those tinsmiths. So, what do you say, amigo?}

{260}{}{I didn't think anyone was still here!}
{261}{}{What are you doing?}
{262}{}{I need power cells for a generator. They're in the storage room in the hangar, but I can't get in there without getting spotted. You seem like you just went from out of there. The robots don't seem to be touching you. Can you get them?}
{263}{}{I'll see what I can do.}
{264}{}{Deal with your problems yourself. My business there is done.}
{265}{}{I'm already gone.}

{300}{}{Here's a power cell.}
{301}{}{Incredible! How did you get it? Though, nevermind, I don't really want to know. I gotta get outta here while the exit's still availaible. Thanks, amigo. Without you, our community would die.}
{302}{}{Hey! Aren't you forgetting something?}
{303}{}{Oh. Sorry. I lied to you - I don't have any friends among the caravaneers. But I'll still tell everyone I know of what you've done. If you'd like, we could head to Casa Grande together. Safer that way. Decide now, I can't wait around.}
{304}{}{Let's go.}
{305}{}{No thanks. This is where our paths diverge. Goodbye.}
{306}{}{So - you with us? It's tough traveling to Casa Grande alone. You'd be safer traveling with us.}
