{100}{}{You see a guard.}
{101}{}{You see a caravan guard. They're resting after a long and exhausting trip.}

{110}{}{Howdy.}
{111}{}{Let me rest.}
{112}{}{Want to travel with us?}
{113}{}{The Phoenix-Two Sun route isn't very safe.}
{114}{}{Dust storms are often more dangerous than raiders.}
{115}{}{Our profession is a difficult one.}
{116}{}{Talk to the boss, I just guard the goods.}
{117}{}{If I were you, I'd stay away from those tinsmiths.}
{118}{}{Want a tip? Don't visit the local doctor.}
{119}{}{I miss Phoenix.}
{120}{}{The tinsmiths don't like outsiders and try to avoid any more conversation than is strictly necessary.}
{121}{}{I don't like those tinsmiths - they're almost like robots.}