{100}{}{This is Merchant Clark.}
{101}{}{You see the caravan manager. His swarthy skin speaks of uncounted miles of travel traveled under the scorching sun.}
{102}{}{Have a good trip.}
{103}{}{We're here. Up the road is the Brotherhood of Steel Fort.}

{200}{}{What do you want?}
{201}{}{Maybe we can get acquainted? In a strange city, I would like to have a couple of contacts.}
{202}{}{Then you're out of luck with the interlocutor. I am engaged in caravanning. And I have a special contract with tinsmiths, the last thing I need is extra acquaintances. Although I can understand you - I was a stranger in this city myself when I first came here.}
{203}{}{Looks like you have something to ask.}

{210}{}{What do you want?}
{211}{}{Nothing.}
{212}{}{I don't mind chatting some more.}

{220}{}{What are you doing?}
{221}{}{I transport cargo across the desert. The tinkerers trust me with this case like no one else.}
{222}{}{Hauling cargo across the desert? Who needs him there?}
{223}{}{Sounds unconvincing, but there really are a couple of places in the desert where our cargo is very much expected. And they pay great caps for it.}
{224}{}{Are slaves also a marketable commodity there?}
{225}{}{Not anymore. Previously, they were driven there in droves from Phoenix to clear ruins and build settlements. But now there is no such need. But slaves became popular in the northern direction.}
{226}{}{This Phoenix - where is it?}
{227}{}{You really don't know? Oh, so you missed a lot. It's a big city in the north. Go along the 10th Federal highway, you won't miss it.}
{1227}{}{You really don't know? Oh, so you missed a lot. It's a big city in the north. Go along the 10th federal highway, you won't miss it.}
{228}{}{Thank you.}

{230}{}{So who are the tinkerers really?}
{231}{}{Something like a cult, they worship technology and progress. Their most cherished dream is to find robotic bodies and upload their consciousness into them. Sounds fantastic, right? But they are already implanting some kind of hardware in themselves. And with their technical skills, no one in all of Sonora can compare.}
{232}{}{What are their immediate plans?}
{233}{}{I don't know, I'm just moving cargo. But the tinkerers are clearly planning something big.}
{234}{}{Why did you decide that?}
{235}{}{They buy up a lot of uranium ore and slaves. They must have taken up a large accumulation of old equipment. And this is fraught with serious investments in Phoenix or somewhere else. Oh, yes, I can already smell the bait for my caravan for the coming years.}
{236}{}{Aren't you going to the place where the whole port was blown up recently?}
{237}{}{Well, there's almost nothing left now. But there are still Casa Nueva plantations on the way. However, how long will he have the strength to survive without the protection of the Brotherhood of Steel? Sooner or later, the settlement will obey the will of the tinsmiths or become empty.}
{238}{}{It looks like life there will get worse anyway. Let's change the subject?}

{240}{}{Is it hard to carry cargo through the wastelands?}
{241}{}{We are masters in this business. We have to adapt and wait for the most suitable seasons for traveling.}
{242}{}{What dangers await in the barren lands of Sonora?}
{243}{}{Of course, first of all it is dehydration and lack of food. We take the water in advance in Casa Grande. This is enough to walk to the Bay. And there we are already desalinating the sea liquid.}
{244}{}{What about the game?}
{245}{}{No one will survive in such sands except radscorpions. It looks like they have looked after Sonora for breeding their offspring. But we almost did not meet robbers. People are rare in those places.}
{246}{}{Your story only fuels my curiosity. Tell me more.}
{247}{}{Thanks for the information. I'm going to get ready for the trip.}

{300}{}{I need to get to the Steel Port.}
{301}{}{Steel Port? For the first time I hear.}
{302}{}{You can trust me.}
{303}{}{Don't worry, I'm joining the Brotherhood of Steel.}
{304}{}{Don't worry, I'm one of the Followers of Fire.}
{305}{}{Sorry. But maybe you know about other things.}
{306}{}{Believe me, not a single caravan goes there now. Something went wrong with the Brotherhood of Steel, as a result, their ship exploded like a damn demolition beetle. Now instead of a ship there is a radioactive funnel and not a single living soul.}
{307}{}{That's right... surprise.}
{308}{}{I don't think so.}

{310}{}{Okay, I see that you're your man. We need to be careful, because the Brotherhood has many enemies.}
{311}{}{So can I go with your caravan?}
{312}{}{Packing is at 6 am, don't be late. Take no more than 150 pounds of cargo with you. Keep in mind, we'll make a stop at Casa Nueva. This is the only settlement on the way to the Brotherhood.}
{313}{}{I can go.}
{314}{}{I will come at the appointed time.}
{315}{}{No one will drag your stuff! Take away the extra load or we'll leave without you.}
{316}{}{These will be my problems.}
{317}{}{Whatever you say.}
{318}{}{Great, then get ready for a hard journey through the wasteland.}
{319}{}{[Go on a trip]}
{320}{}{Maybe so. Or maybe not.}
{321}{}{Okay, I'll review my backpack again.}
{322}{}{I will pay 1000 caps for the escort.}
{323}{}{Are you sure you have that many caps?}
{324}{}{Let me count it...}

#Other locations
{400}{}{We will spend the night in this settlement. You have a little time to look around. Do not oversleep the departure of the caravan, otherwise we will leave without you.}
{401}{}{What can you tell us about this settlement?}
{402}{}{Casa Nueva is a blooming oasis in the middle of the desert. This is the best place to live among all that I know. But the conditions here are quite tough. Behave especially respectfully and carefully with the local population.}
{403}{}{See you later.}
{404}{}{[Wait for the caravan to depart]}
{405}{}{Leave without me, I'll be late.}
{406}{}{As you wish. But keep in mind that the path through the barren wasteland of Sonora is not easy even in a group with a caravan.}
{407}{}{Okay, bye.}