{100}{}{You see a peasant.}
{101}{}{You see a villager of quite ordinary appearance. It's strange to see him among all this crowd.}
{102}{}{Thanks for the help. We will not forget this and will tell everyone about your feat.}

{200}{}{Hey, you're not from around here, right? You can see them right away. Let me give you a free tip - don't mess with these dealers. They don't put outsiders in anything.}
{201}{}{And you...}
{202}{}{Another victim of their bad faith, if you want to know. The tinkerers refuse to sell power cells for the generator to my settlement. And do you know why? Because they called us unworthy of old technologies!}
{203}{}{Tell us more about this problem.}
{204}{}{It's none of my business. Goodbye.}

{210}{}{What do you want to know?}
{211}{}{Nothing else. Bye.}
{212}{}{I have to go.}
{213}{}{Tell me more.}

{220}{}{Tell me about your settlement.}
{221}{}{Just a small rural community. Recently, our generator ran out - and this is the only source of electricity in the entire valley. I had to turn to the tinsmiths for help, but they consider us small and underdeveloped.}
{222}{}{Is the generator so important to you?}
{223}{}{Our whole community was supported by him! Water pump, lighting, radio communication - without all this, our valley will once again turn into a desert and become uninhabitable.}

{230}{}{Nowhere else to get power cells?}
{231}{}{Tinsmiths *are the only ones* who produce them nowadays. And pre-war cells became difficult to find. After all, the nearest neighborhoods have long been ruined by these techno fanatics.}
{232}{}{Have you tried searching in Phoenix?}
{233}{}{Are you kidding? We are settled people, it will be a great challenge to overcome such a distance. In addition, the Big City also buys batteries from tinsmiths. And the prices there are much more expensive.}

{240}{}{Why don't the tinsmiths want to trade with you?}
{241}{}{They consider us unworthy of their technology. They think that we will waste their valuable resource. But this is complete nonsense - we need cells for survival, what could be more important?!}

{250}{}{What are you going to do now?}
{251}{}{We urgently need power cells... Look, you're a peasant like us, right? I can see that. How not to hide behind all these clothes and armor, and your eyes and hands give away what you are doing. We have to stick together, amigo. Help us, and we will help you.}
{1251}{}{We urgently need power cells... Look, you're a peasant like us, right? I can see that. How not to hide behind all these clothes and armor, and your eyes and hands give away what you are doing. We have to stick together, amigo. Help us, and we will help you.}
{252}{}{Why should I help you?}
{253}{}{I have a lot of friends among the caravaneers, I can arrange with them about the escort, and I will raise your reputation. And yet, this is pre-war money. They don't seem to be used anymore, but maybe you'll find a use for them.}
{254}{}{I'll think about your offer.}
{255}{}{Who can I talk to about these energy cells?}
{256}{}{They are in the warehouse in that big hangar, and the quartermaster is in charge of the warehouse. But I doubt that he will change his attitude.}
{257}{}{We'll see about that.}
{258}{}{In other words, do you propose to rob the tinsmiths?}
{259}{}{Just like they robbed many. But you will save an entire settlement and earn friends among honest people. So what do you think, amigo?}

{260}{}{I didn't think there was anyone else here!}
{261}{}{What are you doing here?}
{262}{}{I need power cells for the generator. They are in the warehouse in the hangar, but I can't go there unnoticed. You seem to have just come from there, and the robots don't seem to touch you. Can you get it?}
{263}{}{I'll see what I can do.}
{264}{}{Deal with your problem yourself. I've already decided on mine.}
{265}{}{Consider me no longer here.}

{300}{}{Here is the power cell for the generator.}
{301}{}{Unbelievable! How did you manage it? However, I don't want to know. It's time for me to get out of here while the exit is free. Thank you, amigo, without you our community would have collapsed.}
{302}{}{Hey, did you forget anything?}
{303}{}{I'm sorry, but I deceived you - I don't have any friends among the caravaneers. But I'll tell everyone I know about your feat anyway. If you want, we'll go to Casa Grande together, it's safer that way. Decide now, I won't wait.}
{304}{}{Then let's go.}
{305}{}{No, our paths diverge here. Happily.}
{306}{}{So, are you with us? The way to Casa Grande is difficult, it will be safer for you to travel with us.}