{100}{}{You see a tinsmith.}
{101}{}{You see one of the ordinary residents of Two Sun.}

#Floating dialogue
{110}{}{The Steel gods are angry at our slow pace of work.}
{111}{}{Why are the Steel gods silent? Have they forgotten about us?}
{112}{}{The Steel gods are content.}

{113}{}{Casa Nueva could lower production.}
{114}{}{Casa Nueva promised to send additional foodstuffs.}
{115}{}{Worrying rumours from Casa Nueva. Unsafe there.}

{116}{}{The highwaymen have robbed yet another Phoenix caravan.}
{117}{}{They say the Blue Shields are finally deposed.}
{118}{}{The Blue Shields have become stronger. They are now a force to be reckoned with.}

{119}{}{These fire-worshippers have always amused me.}
{120}{}{The Followers of the Holy Fire achieved their dream, that's for sure.}
{121}{}{The arrogant fire-worshippers are trying to tell us what to do.}

{122}{}{This Flagstaff uranium is not enough.}
{123}{}{We must conserve energy until the Flagstaff mines become operational again.}
{124}{}{Thanks to the uranium from Flagstaff, we no longer have to conserve energy.}

{125}{}{Being able to access the Forbidden Zone would change our lives.}
{126}{}{We must leave before ZAX unleashes his anger toward us.}
{127}{}{Being able to access the Forbidden Zone will change our lives.}

{128}{}{After the latest operation, Master Khard has become unfeeling.}
{129}{}{Another visit to Doc Jones could be the least.}
{130}{}{Know your place in the Collective.}

{131}{}{Don't forget to pray to the god of technology before eating.}
{132}{}{Thank the gods of Steel that we exist.}
{133}{}{I need to clean my joints.}