{100}{}{You see the tinker.}
{101}{}{You see a resident of Two-Sun. She looks more civilized than other residents.}
{102}{}{You have won the favor of the local population.}

#The first dialog
{200}{}{(you see a bald woman with an optical amplifier under her left eye) Another wasteland savage with primitive ideas of Progress. In that case, our conversation is irrelevant. Leave.}
{201}{}{I'll get over it somehow.}
{202}{}{I think you're missing a lot.}
{203}{}{My ideas about Progress will come as a surprise to you.}
{204}{}{My membership in the Brotherhood of Steel may change your mind.}
{205}{}{After all my efforts, you should expect more trust.}

{206}{}{My data suggests otherwise.}
{207}{}{All right.}
{208}{}{(pause) No objections.}
{209}{}{It's good, uh, that we find a common language.}

#Repeat dialog
{210}{}{What do you want to know?}
{211}{}{Perhaps nothing more. Goodbye.}
{212}{}{Let me ask you another question.}

{213}{}{Why don't you want to talk to me?}
{214}{}{Outsiders with a low coefficient of development do not deserve our trust. An exception may be trade benefits, especially concerning food. Do you have any nutrients?}
{215}{}{I'm rummaging through my bag for something to eat.}
{216}{}{You won't get anything from me.}
{217}{}{My food gift deserves a couple of answers.}

#Questions
{220}{}{Can you tell me why tinsmiths buy slaves?}
{221}{}{We need a workforce to make progress. Without slaves, the process would be much slower and less efficient. Someday we will replace slaves with robots, but it will take a lot of time and energy, which is so lacking now.}
{222}{}{Tell us about the Progress.}
{223}{}{The achievement of technological and civilized perfection, as it was before the Great War. In our time, Progress is necessary for the survival of humanity as a species.}
{224}{}{}
{225}{}{}
{226}{}{Do you know anything about Villa slaves?}
{227}{}{No. This should be discussed with Master Hard, our leader.}
{228}{}{And do you agree with such an inhumane practice?}
{229}{}{The ethical aspect of the issue is not essential. Progress is worth the sacrifice, it will give people more than a handful of primitive people from the wasteland.}

{230}{}{What do you do?}
{231}{}{I serve the workers in the hangar. I prepare nutrients and keep order in the residential complex.}
{232}{}{So do tinsmiths have families?}
{233}{}{Family... Many tinsmiths once had families. But now it doesn't matter.}
{234}{}{Why?}
{235}{}{We accept children from the wastelands and program them to serve our collective. Personality doesn't matter. Family is not needed.}
{236}{}{Some tinsmiths are different from others.}
{237}{}{Our society is divided into levels. Each level has its own set of knowledge and technologies. For example, only the highest members of the team can perform complex and expensive implant operations.}

{240}{}{Why are you so distrustful of outsiders?}
{241}{}{Trust is immaterial. We outperform almost all the inhabitants of the Wasteland in terms of development coefficient. In such a situation, outsiders can be useful mainly as slaves and, in some cases as trading partners.}
{242}{}{But still you have external connections.}
{243}{}{Right... Until recently, we were a closed community and did not let anyone in from outside.}
{244}{}{What has changed?}
{245}{}{Food shortages, mathematical calculations of prospects, and contact with one highly developed community. But I can't discuss this with outsiders.}
{246}{}{A curious position.}