{100}{}{You see the patient.}
{101}{}{Here is a sick tinker. He is suffering from postoperative complications.}
{102}{}{How could primitive medicine cure me? This is illogical!}
{104}{}{Why... I'm not... digitized yet...}
{105}{}{Mine... biomatrix... crashes...}

{110}{}{Take me apart for parts.}
{111}{}{Doctor, will I be deactivated?}
{112}{}{I only regret one thing - that I did not live to digitize my personality.}
{113}{}{It's time to sacrifice yourself to Progress.}
{114}{}{There was a glitch in my biomatrix.}

{115}{}{Thanks for the fix, Doc.}
{116}{}{Being on the verge of deactivation, I rethought a lot.}
{117}{}{I need to review my algorithms.}
{118}{}{Now I no longer believe that Progress is worth my sacrifice.}
{119}{}{Now my biomatrix is fine.}