{100}{}{You see a patient.}
{101}{}{You see an ill tinsmith. He's suffering from post-surgery complications.}
{102}{}{How could that primitive medicine have healed me? It's illogical!}
{104}{}{Why... am I... not digitized...}
{105}{}{My... biomatrix... failing...}

{110}{}{Dissasemble me for spare parts.}
{111}{}{Doctor, will I be deactivated?}
{112}{}{I regret only one thing - that I did not live to have my consciousness digitized.}
{113}{}{The time has come to sacrifice myself in the name of Progress.}
{114}{}{A failure has ocurred in my biomatrix.}

{115}{}{Thank you for the repairs, doc.}
{116}{}{Standing at the edge of deactivation, I've rethought many things.}
{117}{}{I need to take another look at my algorithms.}
{118}{}{I don't think Progress is worth my sacrifice anymore.}
{119}{}{My biomatrix is in working order now.}
