{100}{}{You see a tinker.}
{101}{}{You see one of the ordinary residents of Two-Sun.}

#Floating replicas
{110}{}{The gods have become angry because of our slowness.}
{111}{}{Why did the gods become silent? Have they forgotten about us?}
{112}{}{The gods were pleased.}

{113}{}{Casa Nueva can cut food.}
{114}{}{Casa Nueva promised to send more food.}
{115}{}{Disturbing rumors are coming from Casa Nueva, now it's not safe there.}

{116}{}{The Magistrals robbed another caravan from Phoenix.}
{117}{}{They say that the Blue Shields have finally been deposed.}
{118}{}{The Blue Shields have become stronger. Now they have to be reckoned with.}

{119}{}{I've always found these fire worshippers funny.}
{120}{}{The followers of Fire got what they dreamed of.}
{121}{}{Brazen fire worshippers are trying to tell us what to do.}

{122}{}{This uranium from Flagstaff is not enough.}
{123}{}{We must conserve energy until the Flagstaff mines start working again.}
{124}{}{Now you don't have to save energy thanks to the uranium reserves from Flagstaff.}

{125}{}{Admission to the Restricted Area would change our whole lives.}
{126}{}{We have to leave before ZAX finally unleashes his wrath on us.}
{127}{}{Admission to the Restricted Area will change our whole life.}

{128}{}{After the last operation, Master Hard became insensitive.}
{129}{}{Another visit to Doc Jones may be the last.}
{130}{}{Know your place in the Team.}

{131}{}{Don't forget to pray to the god of technology before eating.}
{132}{}{Pray to the gods of Steel for what we are.}
{133}{}{I need to clean my joints.}