{100}{}{You see a tinsmith.}
{101}{}{You see an inhabitant of Two Sun. She looks more civilized than the other people here.}
{102}{}{You have increased your reputation among the locals.}

#First dialogue
{200}{}{(you see a bald woman with an optical enhancer in the place of her left eye) Yet another Wasteland savage with primitive conceptions of Progress. Such a conversation is pointless. Leave.}
{201}{}{I'll do just fine without it.}
{202}{}{The world is more complex than that.}
{203}{}{My conceptions of Progress may surprise you.}
{204}{}{My membership in the Brotherhood of Steel may change your mind.}
{205}{}{After all I've done for you, I'd expect a little bit more trust.}

{206}{}{My data suggests otherwise.}
{207}{}{Fine.}
{208}{}{(pause) I have no objections.}
{209}{}{It's good that we, uhh, have reached a mutual understanding.}

#Repeated dialogue
{210}{}{What do you want to know?}
{211}{}{At the moment, nothing, I suppose. Goodbye.}
{212}{}{Allow me to ask another question.}

{213}{}{Why don't you want to talk to me?}
{214}{}{Intellectually underdeveloped outsiders are not deserving of our attention. Exceptions include beneficial trade, especially regarding nutrients. Do you posess nutrients?}
{215}{}{I'll look for food in my backpack.}
{216}{}{You won't get anything from me.}
{217}{}{My gift of food deserves a couple of answers.}

#Questions
{220}{}{Can you tell me why the tinsmiths are buying slaves?}
{221}{}{To achieve Progress, we require manpower. Without slaves, the process would be much slower and inefficient. We will replace slaves with machines one day, but that would require high amounts of time and energy that we won't be able to afford sparing for the foreseeable future.}
{222}{}{Tell me about Progress.}
{223}{}{The achievement of technological and civilizational perfection like the one that was achieved before the Great War. In our time, Progress is necessary for humankind to survive as a species.}
{224}{}{}
{225}{}{}
{226}{}{Do you know anything about slaves from Villa?}
{227}{}{No. You should speak about this with Master Khard, our leader.}
{228}{}{And you agree with such inhumane practices?}
{229}{}{The ethical aspect of the practice is inconsequential. Progress is worth sacrifice. Progress justifies the means. It will give humanity far more than a group of desert primitives ever could.}

{230}{}{What is it you do here?}
{231}{}{I supply workers in the hangar. I prepare nutrients and maintain order and cohesion in the residential complex.}
{232}{}{So tinsmiths have families?}
{233}{}{Families... Many tinsmiths once had families. But it is irrelevant now.}
{234}{}{Why?}
{235}{}{We accept children from the Wasteland and program them to serve our Collective. Identity has no meaning. Family is unnecessary.}
{236}{}{Yet tinsmiths are not all alike.}
{237}{}{Our society is divided into levels. Each level has access to it's own array of knowledge and technology. For instance, only the highest members of the Collective can receive complex and resource-demanding implant installation operations.}

{240}{}{Why are you so distrustful of outsiders?}
{241}{}{Trust is irrelevant. We are intellectually superior to almost all inhabitants of the Wasteland. In this situation, most outsiders are useful merely as slaves, and sometimes as trading partners.}
{242}{}{But you still have external connections.}
{243}{}{Correct... However, until a few years ago, we were a closed society and did not allow outsiders to visit.}
{244}{}{What changed?}
{245}{}{Nutrient shortages, mathematical calculations of prospects and the establishment of contact with one highly developed group. But I cannot discuss this with outsiders.}
{246}{}{An interesting opinion.}