{100}{}{You see Abel.}
{101}{}{You see a representative of the Church of the Sacred Fire.}

#The first dialog
{200}{}{Are you here on business? Then you need to see Master Hard. It can be found in the workshop.}
{201}{}{Thank you.}
{202}{}{I would like to meet you specifically.}
{203}{}{Too kind to be true. My name is Abel, I am one of the Followers of Fire if that means anything to you. Now stop wasting my time.}
{204}{}{What are you doing?}
{205}{}{I see you're not going to get rid of that easily. The church needs the services of tinsmiths, just like any modern community. I am assigned to monitor the fulfillment of orders.}
{206}{}{Are the tinkers that good?}
{207}{}{They are the best in their field. You may have already come across their inventions. Pneumatic weapons, computing devices, even prosthetics, and simple implants. Fortunately, tinkerers aren't stupid enough to deal with the first person they meet. They are reluctant to share knowledge and technology. Our church had the honor to find a common language with them.}
{208}{}{It shows. Well, I'll look at it all in action. Goodbye.}
{209}{}{Simply put, someone coveted power in this region. Have a nice day.}

#Repeat dialog
{210}{}{You again?}
{211}{}{Forget it.}
{212}{}{How can I help, brother?}
{1212}{}{How can I help, Sister?}
{213}{}{Thanks, I'll figure it out later somehow.}
{214}{}{Enough information for today.}
{215}{}{I'm the one wasting time talking to you.}
{216}{}{No problem, I'll leave immediately.}

{220}{}{Tell me about your church.}
{221}{}{This is too long a conversation. It's better to visit our temple in Phoenix and find out about everything directly.}
{222}{}{Good.}

{230}{}{Actually, I'm also a Follower of Fire.}
{231}{}{Really? It changes a lot. Welcome to Two-Sun, brother. Together we will glorify the Sacred Fire.}
{1231}{}{Really? It changes a lot. Welcome to Two-Sun, Sister. Together we will glorify the Sacred Fire.}
{232}{}{I see you're more accommodating now. Can you answer a few questions?}
{233}{}{I see.}
{234}{}{Thank you for the answer. Now it's time for me to get busy.}

{240}{}{What does the church in Two-Sun do?}
{241}{}{As I have already said, the church needs technology and knowledge. This is one of our main postulates - the Sacred Fire incinerated the old civilization to build a new one in its place. The tinkerers are the builders of this new civilization. Their production skills and technologies are necessary for survival and development. Unfortunately, many in the wastelands do not understand the idea of Progress, they are afraid to change their ossified way of life.}
{242}{}{What orders are being carried out by tinsmiths now?}
{243}{}{The most important order is energy batteries. Without them, any serious equipment is no more valuable than a pile of garbage. They also make weapons and repair old electronics.}
{244}{}{Where did the tinkerers learn about these technologies?}
{245}{}{Their skills have been passed down from generation to generation. They received some documentation through our church or bought it from caravans.}
{246}{}{Do you not preach in this city?}
{247}{}{The church is striving to expand, but it is enough to have one ambassador in Two-Sun. Tinkerers do not share our faith in everything, but their sympathies are enough for joint achievements.}
{248}{}{Something tells me that there are orders that you would prefer to keep quiet about.}
{249}{}{Now I see why the church accepted you. Yes, there are several special technologies that mere mortals should not know about. This may upset the balance of power or cause waves of protest among the population.}
{250}{}{In history, it is not uncommon for peaceful technologies to be used as weapons. Their harm outweighed their benefit.}
{251}{}{If anyone can ensure progress in this region, it is only us - the servants of the Sacred Fire. We have lived with this idea and are not going to give it up. Believe me, the church is doing everything to turn Sonora into a thriving paradise.}

{260}{}{The tinsmiths enslaved several of my acquaintances. Is there any way to release them?}
{261}{}{But why ? I don't think your acquaintances are that valuable outside of slave bondage. To serve Progress is a great honor and benefit to all mankind. In any case, most of the slaves have already been sent to the Forbidden Zone. You'll have to go there and save your friends yourself.}
{262}{}{While I'm looking for a solution, let's talk about other topics.}
{263}{}{I think there must be a way to free them. Later.}

#gg enemy cult
{300}{}{You again? Get out of this town before I call the guards.}
{301}{}{Wait, why so much hostility?}
{302}{}{Don't speak my tongue, atomic ignorance! The Followers of Fire have a good network of informants, I have already been informed about your exile. Get out!}
{303}{}{Calm down...}

{310}{}{Wait. Who sent you?}
{311}{}{No one. Why are you so nervous?}
{312}{}{I have my reasons. And you shouldn't show up in this city at all. It is very suspicious that the enemy of the Followers of Fire suddenly visited the tinsmiths. It looks like you're playing your game right under our noses.}
{313}{}{So the Church of Fire is no longer in high esteem here?}
{314}{}{The Church was the main engine of progress in Southern Arizona. Now that the main temple has been destroyed, it will take a lot of effort to regain its former greatness and trust. But the tinsmiths have served us for almost ten years. They will not betray their patrons because of a single misunderstanding.}
{315}{}{But then why are you so turned on? Looks like the tinkerers were less submissive, right?}
{316}{}{We thought of them as working machines. Now that they felt free and superior, they could use a charge of electric current to put them in their place. And now stop making fun, you despicable atom. Get out of my sight.}
{317}{}{You know, it's not me who needs to get out of Two-Sun. And you.}
{318}{}{Have a good stay, misanthrope...}
{319}{}{Come on, it's not that bad...}
{320}{}{Leave me, demon of atomic division!}
{321}{}{What are you...}