{100}{}{You see Abel.}
{101}{}{You see a representative of the church of the Holy Fire.}

#First dialogue
{200}{}{You here for business? Then you need to talk to Master Khard. He's in the workshop.}
{201}{}{Thank you.}
{202}{}{I'd like to talk specifically with you.}
{203}{}{I've got a lot of work to do. My name is Abel. I'm of the Followers of the Holy Fire. I hope this is enough information for you, because I really can't be wasting my time.}
{204}{}{What is it you do here?}
{205}{}{Looks like you can't be shaken off that easily. The church needs the tinsmiths' services, as does every contemporary society. My job is to ensure production stays on target.}
{206}{}{The tinsmiths are that good at their jobs?}
{207}{}{They're the best in the field. Perhaps you've already come across their inventions. Pneumatic weaponry, calculation devices, even prostheses and simple implants. Luckily, the tinsmiths are not stupid enough to conduct business with any person they come across. They are hesitant to share knowledge and technology. Our church has had the honor of finding common ground with them.}
{208}{}{I see. Welp, I'll go look at it with my own eyes. Goodbye.}
{209}{}{Simply put, someone has an eye for power over this region. All the best to you.}

#Repeat dialogue
{210}{}{You again?}
{211}{}{Forget it.}
{212}{}{How can I assist you, brother?}
{1212}{}{How can I assist you, sister?}
{213}{}{Thanks, I'll figure the rest of it out myself.}
{214}{}{Enough information for today.}
{215}{}{Looks like I'm the one wasting time talking with you.}
{216}{}{No problem. I'm already leaving.}

{220}{}{Tell me about your church.}
{221}{}{It would take too much time. Visit our temple in Phoenix and learn about it there directly.}
{222}{}{Okay.}

{230}{}{Actually, I'm a Follower of the Holy Fire too.}
{231}{}{Really? This changes things. Welcome to Two Sun, brother. We shall praise the Holy Fire together.}
{1231}{}{Really? This changes things. Welcome to Two Sun, sister. We shall praise the Holy Fire together.}
{232}{}{I see you're more willing to talk now. Mind answering a few questions?}
{233}{}{I see.}
{234}{}{Thank you for your time. Now I need to leave. I've got work to do.}

{240}{}{What does the church really do in Two Sun?}
{241}{}{As I already told you, the church needs technology and knowledge. It is one of our tenets - The Holy Fire burned the civilization of old to ashes, so that a new, better one can be created on it's ruins. The tinsmiths will be it's builders. Their technology and industry are necessary for survival and growth. It's unfortunate that so many in the Wastes don't understand the idea of Progress. They're too afraid to change, to abandon their obsolete traditions.}
{242}{}{What kind of things do the tinsmiths produce?}
{243}{}{In our time, the most precious items in the world are energy cells. Energy cells are vital to the usage of advanced technology. Without them, any complicated machine is nothing more than junk. The tinsmiths also produce weaponry and repair old electronics.}
{244}{}{How did the tinsmiths learn all that?}
{245}{}{They pass down their skills from generation to generation. Some technology requires specific documentation. Most of it was found with the help of our church or bought from caravaneers.}
{246}{}{So you don't preach in this settlement?}
{247}{}{The church seeks to expand, but a simple ambassador is enough for Two Sun. The tinsmiths do not agree with us on everything, but their similar goals have allowed for many cooperative enterprises.}
{248}{}{Something tells me they produce some things you'd rather not tell me about.}
{249}{}{I see now why the church accepted you into it's ranks. Yes, there are certain technologies that mere mortals are better off not knowing about. It could seriously shift the balance of power, or even cause the population to riot.}
{250}{}{The history of humanity has witnessed many cases of peaceful technologies being used as weapons. Their harm outweighted the benefits.}
{251}{}{If there is a power capable of ensuring progress in this region, it can only be us - the servants of the Holy Fire. We have always lived with this thought and shall abandon it under no circumstances. Believe me, the church is doing all it can to turn Sonora into a thriving paradise.}

{260}{}{The tinsmiths have enslaved some of my friends. Is there any way to free them?}
{261}{}{Why would you want to do that? I doubt your acquaintances would give more value to the world if they were to be released. To serve the cause of Progress is a great honor and a great service to all of mankind. In any case, the majority of the slaves have already been sent into the Forbidden Zone. You will have to go there and rescue them yourself.}
{262}{}{While I think of a solution, let's talk about something else.}
{263}{}{There has to be some way to free them. I see I won't find it by talking with you.}

#Player enemy of the cult
{300}{}{You again? Get out of the city before I call the guards.}
{301}{}{Why so hostile?}
{302}{}{Don't you try and fool me, traitor! The church has an extensive network of informants all over the Wasteland. I know all about your expulsion. Get out!}
{303}{}{Calm down, man...}

{310}{}{Wait. Who sent you?}
{311}{}{No one. Why so nervous? Got something to hide?}
{312}{}{I have my reasons. And you shouldn't be in this city at all. Very suspicious that an enemy of the Followers of the Holy Fire would choose to visit the tinsmiths. It looks as if you're playing your own game, right under our very noses.}
{313}{}{I take it the church isn't held up in high esteem here anymore?}
{314}{}{The church was the main engine of progress in Southern Arizona. Now that the main temple has been destroyed, we will need to spend much effort to restore our former glory and the trust we once enjoyed. But the tinsmiths have served us well for almost an entire decade. They won't betray us because of one little accident.}
{315}{}{Then why did you get so worked up? The tinsmiths turned out to be less submissive than you thought?}
{316}{}{We used to think of them as, effectively, machines. Now that they have tasted liberty and superiority, they sure could use an electric shock to put them in their place. Now stop scoffing, pathetic atom. Get out of my sight.}
{317}{}{It's not me who should get out of Two Sun. It's you.}
{318}{}{Sure, misanthrope...}
{319}{}{Come on, it's not that bad...}
{320}{}{Leave me alone, atomic fission devil!}
{321}{}{Okay, okay, just calm down...}