{100}{}{You see the gatekeeper.}
{101}{}{Here is a tinsmith guarding the entrance to the settlement.}
{102}{}{You can pass. But we'll be watching you.}
{103}{}{No entry without permission!}
{104}{}{(hides food and looks around) You can pass, but don't do anything stupid.}

#Cut-the scene at the gate
{110}{}{Something seems to be happening at the main gate.}
{111}{}{Let me in immediately! Hard just has to listen to me!}
{112}{}{Your little tribe thinks too much of itself. Get out.}
{113}{}{How dare you! You've been dependent on our supplies for years and you can't just drive us away!}
{114}{}{Now the Forbidden Zone gives us everything. You are no longer needed. Leave before I use force.}
{115}{}{Damn you!}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{   }

#Primary dialog
{200}{}{Wait. This is a closed area. Name the purpose of the visit.}
{201}{}{Don't, I'm already leaving.}
{202}{}{I see.}

{210}{}{We are not interested in this. Go away.}
{211}{}{Let me in right now, you fucking cyborg!}
{212}{}{Okay, I'll leave peacefully. But maybe I'll be back.}
{213}{}{Go away. Otherwise, the power of Progress will level you to the ground.}
{214}{}{We'll see about that...}
{215}{}{You can go through. While you're inside, hide your weapons and don't run into trouble. Don't talk to slaves. Do not enter the Restricted Area without permission. Go straight to the hangar and talk to Master Hard, our leader. That's it.}
{216}{}{Quite a harsh set of rules. I will try not to create problems.}
{217}{}{There was no need to say. And so everything is clear. Now move out of the way.}
{218}{}{My bike needs maintenance.}

{220}{}{I'm looking for my relatives.}
{221}{}{Maybe they're here. Or maybe not. We are gathering people to work from all over the wasteland, we really need workers. If you want to find relatives, you need to go to the workshop.}
{222}{}{I see.}

{223}{}{I'm here to trade.}
{224}{}{We need some goods. The Hard Master will be interested in profitable trading.}
{225}{}{Great, I'll be glad of a good deal.}

{226}{}{I'm looking for technological enlightenment.}
{227}{}{For a hundred years we have been connected by one power cable. Who are you to seek enlightenment from us? However, times have changed. Perhaps Master Hard will talk to you.}
{228}{}{This is encouraging.}

{229}{}{I need maintenance. Here are two hundred caps to start with.}
{230}{}{We love work. And we love technology. Your problem will become our problem if you are able to pay.}
{231}{}{I think I will find the right amount of caps.}

{232}{}{I am only a peaceful preacher of the Sacred Fire. Let me in for the night, generous tinker!}
{1232}{}{I am only a peaceful preacher of the Sacred Fire. Let us in for the night, generous tinker!}
{233}{}{The Church of the Sacred Fire has been our reliable partner for several years. We welcome you to Two-Sun, minister.}
{1233}{}{Sacred Fire Church has been our reliable partner for several years. We welcome you to Two-Sun, servant.}
{234}{}{I'm glad to hear that.}

{235}{}{I'm from the Brotherhood of Steel.}
{236}{}{We bow before the greatness of the Brotherhood. Your technology is excellent.}
{237}{}{It's true.}

{238}{}{See this robe? I am a Follower of Fire, we have good relations with your people.}
{239}{}{After the fall of your citadel, you risk just your appearance. Go away and don't cause us any problems.}
{240}{}{Damn...}

{241}{}{I'm going from the Cathedral of Fire to the Steel Port. I was told I'd find a place to sleep on the way here.}
{242}{}{We appreciate what the Sacred Fire Church does. You can pass.}
{243}{}{Thank you.}
{244}{}{I'm here to trade. This atomic clock is not the only thing available to me.}

#Repeat dialog
{250}{}{You can pass. But we'll be watching you.}
{251}{}{Of course, uh, no problem.}
{252}{}{Hard assigned to investigate the attack on the caravan.}
{253}{}{It is very strange that Master Hard trusted strangers. But I can only obey.}
{254}{}{Give me some time before I hit the road.}
{255}{}{Who do you think would attack the caravan?}
{256}{}{Previously, no one dared to meddle in our lands, except for highway workers and rare robbers from the north. When Two-Sun opened up to the world, we had a lot of external connections, it could attract even more bandits. Consider it the costs of Progress.}
{257}{}{What do the caravaneers themselves say?}
{258}{}{The attack was sudden - the bandits were waiting for the caravan for several days, hiding in an old building near the highway. They were only interested in the cargo, they allowed the caravaneers to leave.}
{259}{}{Is there something unusual about this?}
{260}{}{Some of the bandits used energy weapons. We believe it was mined in a Restricted Area.}
{261}{}{Show me the place of the attack.}
{262}{}{It's an old cafe on the interstate a few miles from here.}
{263}{}{[Go to the place of the attack]}
{264}{}{And sheathe your weapons, otherwise you'll have problems.}
{265}{}{OK.}

{270}{}{Why did you hang this man on a pole?}
{271}{}{The followers of Fire turned out to be stupid and unworthy of our technologies. The body of this despicable one will serve as an example to the rest.}
{272}{}{I approve. It is high time for these sectarians to disappear from our world.}
{273}{}{Don't you find it too cruel? However, it's up to you.}