{100}{}{You see a gatekeeper.}
{101}{}{You see a tinsmith guarding the entrance to the settlement.}
{102}{}{Access granted. But we'll be watching you.}
{103}{}{Access is forbidden without permission!}
{104}{}{(hides food and looks around) You can go in, but don't do anything stupid.}

#Gate cutscene
{110}{}{Looks like something is happening at the main gates.}
{111}{}{Let me in! Khard has got to listen to me!}
{112}{}{Your pathetic tribe thinks too highly of itself. Leave.}
{113}{}{How dare you! You've been dependant on our shipments for years! You can't just force us to leave like this!}
{114}{}{The Forbidden Zone gives us everything we need now. You are no longer useful. Leave before I employ force.}
{115}{}{Damn you all to hell!}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{   }

#First dialogue
{200}{}{Halt. This is restricted territory. State purpose of visit.}
{201}{}{No need, I am already leaving.}
{202}{}{Alright.}

{210}{}{We are not interested in this. Go.}
{211}{}{Let me in, you damn cyborg!}
{212}{}{Fine, I'll leave. But one day I might come back.}
{213}{}{Leave, before the might of Progress utterly destroys you.}
{214}{}{We'll see about that...}
{215}{}{You can come in. But while you're inside - keep your weapons holstered and do not cause issues. Go directly to the hangar. Do not talk to the slaves, do not enter the Forbidden Zone without permission. Upon arrival, speak with Master Khard, our leader. That is all.}
{216}{}{Strict rules you have here. I'll try not to cause trouble.}
{217}{}{Thanks, Captain Obvious. Now move out of the way.}
{218}{}{My bike requires maintenance.}

{220}{}{I'm looking for my relatives.}
{221}{}{Maybe they're here. Maybe they're not. We collect workers from all across the Wasteland. We need all the manpower we can get. If you wish to find your relatives, you will need to enter the hangar.}
{222}{}{I see.}

{223}{}{I'm here to trade.}
{224}{}{We require certain goods. Master Khard will be interested in mutually-beneficial trade.}
{225}{}{Great. I'll be happy to make a good deal.}

{226}{}{I'm on a quest to achieve technological enlightenment.}
{227}{}{We have been connected by one single power cable for a hundred years. And you, an outsider, seek enlightenment from us? Though... times have changed. Master Khard may will be willing to talk to you.}
{228}{}{This is encouraging.}

{229}{}{I need something maintained. Here's 200 caps for a start.}
{230}{}{We love work. And we love technology. Your problem will become our problem. If you can afford the price.}
{231}{}{I think I'll find the amount of caps you need.}

{232}{}{I'm but a peaceful missionary of the Holy Fire. Let me rest here, noble tinsmith!}
{1232}{}{I'm but a peaceful missionary of the Holy Fire. Let me rest here, noble tinsmith!}
{233}{}{The church of the Holy Fire has been a reliable partner for several years. We welcome you to Two Sun, acolyte.}
{1233}{}{The church of the Holy Fire has been a reliable partner for several years. We welcome you to Two Sun, acolyte.}
{234}{}{Glad to hear it.}

{235}{}{I'm from the Brotherhood of Steel.}
{236}{}{We bow down before the greatness of the Brotherhood. Your technologies are excellent.}
{237}{}{That's certainly true.}

{238}{}{See these robes? I'm a Follower of the Holy Fire. We have good relations with your people.}
{239}{}{After the fall of your citadel, you take a risk merely approaching our territory. Leave and do not cause us issues.}
{240}{}{Shit...}

{241}{}{I've been sent to Steel Port from the Cathedral of the Holy Fire. I was told I'd find a place to rest here.}
{242}{}{We value what the church of the Holy Fire is doing. Access granted.}
{243}{}{Thank you.}
{244}{}{I'm here to trade. This atomic clock is not the only thing I have.}

#Repeated dialogue
{250}{}{Access granted. But we'll be watching you.}
{251}{}{Of course, uhh, no problem.}
{252}{}{Khard has ordered me to investigate the attack on the caravan.}
{253}{}{It is very peculiar that Master Khard trusts an outsider. But I can only obey.}
{254}{}{I need some time before I leave.}
{255}{}{Who do you think could have attacked the caravan?}
{256}{}{In the past, no one dared to enter our territory except for the highwaymen and the rare northern bandits. But when Two Sun opened itself to the world, the connections that became availaible to us could have attracted more bandits. Consider it the cost of Progress.}
{257}{}{What did the caravaneers themselves say?}
{258}{}{The attack was an ambush - the bandits were waiting for the caravan for several days, hiding in an old building near the highway. They were interested only in the cargo. They let the caravaneers go.}
{259}{}{Was there anything out of the ordinary about the attack?}
{260}{}{Some of the bandits utilized energy-based weaponry. We think they acquired it in the Forbidden Zone.}
{261}{}{Show me the site of the attack.}
{262}{}{The old cafe on the federal highway. It is a few miles away from here.}
{263}{}{[Head to the site of the attack]}
{264}{}{And holster your weapons. Or there will be trouble.}
{265}{}{Okay.}

{270}{}{Why did you hang this man?}
{271}{}{It appeared that we had overestimated the intelligence of the Followers of the Holy Fire. They were not deserving of our technology. The body of one of their members will serve as a warning to the rest.}
{272}{}{I approve of this message. These cultists should have been wiped off the face of the Earth a long time ago.}
{273}{}{Don't you think that's a little inhumane? Though, I suppose it's not really any of my business.}