{110}{}{A personal assistant is at your service.}
{111}{}{Unfortunately, I can't help you with anything.}
{112}{}{Please keep the hangar clean... I tried.}
{113}{}{You are not on the list of our employees... unfortunately.}
{114}{}{Please leave the hangar if you do not have an official permit.}
{115}{}{I'm not programmed to follow your orders. I am so sorry. True.}
{116}{}{Please tell us the purpose of the visit.}