{100}{}{You see Romeo-Six.}
{101}{}{You see one of the tinsmiths. He looks very young. Almost a teenager.}
{102}{}{To extract the implant, use surgery.}
{103}{}{With the tinsmith's instructions, you manage to extract the chip from his body.}
{104}{}{Outsider? Here? I suppose I should check my weapon...}

#First dialogue
{200}{}{(you see a wide-eyed teenage tinsmith; he's curiously examining you) Wasteland person, you should know that outsiders are not liked in Two Sun. It would be best for you not to test our patience.}
{201}{}{}
{202}{}{Hey, pal, I just want to talk.}
{203}{}{Go away. We are forbidden to talk with you. (turns around and goes away from you)}
{204}{}{Now that was kind of rude...}
{1204}{}{Pish! Some people have no manners at at all...}
{205}{}{I sense indecision in your words. Do you feel lonely here?}
{206}{}{(stops, bewildered) The Collective considers talking with underdeveloped outsiders unproductive... unless it brings benefit.}
{207}{}{That's what the Collective thinks. What about *you*?}
{208}{}{Hey, watch your mouth!}
{209}{}{Typical primitive reaction. Even if your village has a nuclear reactor and the leaders use energy weapons, you'll still be savages.}
{210}{}{If talking to me is so "unproductive", then why did you start talking with me? Any doubts?}
{211}{}{I'm not staying here for a second more after what I've heard. Goodbye...}

{212}{}{So you're proposing to leave?}
{213}{}{The Collective considers you a destructive element and recommends avoiding contact.}
{214}{}{Earning people's trust here isn't easy. Farewell, tinsmith.}
{215}{}{Who'd you call destructive here? Keep in mind that I won't be so forgiving next time.}
{216}{}{(hesitates) Firstly... Firstly, talk to Master Khard.}
{217}{}{Great, I'll keep that in mind.}
{218}{}{Да... Нет...}
{219}{}{Нет?}

#Dialogue near the toilet
{220}{}{I can't talk right now. We'll meet at 22:00 behind the hotel.}
{221}{}{Alright.}
{222}{}{That's not a good location. We'll meet behind the hotel.}
{223}{}{Alright.}
{224}{}{Nobody will hear us here.}
{225}{}{It looked like you were unsure of yourself back there, when you were talking about your Collective. Does something trouble you?}
{226}{}{Trouble? Yes... maybe. The Collective says that the past is irrelevant, that we must forget it and live by the future, for Progress. But I can't reject my... childhood that easily.}
{227}{}{Childhood? So you aren't from here?}

{228}{}{Two Sun used to be completely closed off for outsiders. But when population lowered, the Collective had to restore it by acquiring children from other settlements. I was accepted and re-educated at an age of 5. I haven't seen my family since then.}
{229}{}{I travel a lot. I could look for your relatives.}

{230}{}{You're really gonna do it? That's great... But my dossier says that my relatives died during a war in Casa Grande. Talk with the locals. I just want to know what happened during the day of our separation.}
{231}{}{Why not ask other tinsmiths directly?}
{232}{}{The Collective doesn't tolerate troublemakers. Refusal to obey the will of the majority is severely punished. It happened before. I have no desire to test the Collective's patience.}
{233}{}{ }
{234}{}{ }
{235}{}{Maybe I could help, but travel to other settlements isn't cheap.}
{236}{}{I could get you some of our technologies, if you're interested. But don't expect much. My storage room access level is quite low.}
{237}{}{Alright, I'll look for your parents.}
{238}{}{(warming up) Great! I mean... (supresses emotions) I will be grateful... We better stop talking and leave now, before anyone gets suspicious. Don't tell anyone that we had this conversation.}
{239}{}{Of course.}
{240}{}{Sorry, kid, but Casa Grande is the opposite of where I'm headed.}
{241}{}{A shame... But if you do end up visiting Casa Grande, remember my request. We better stop talking and leave now, before anyone gets suspicious. Don't tell anyone that we had this conversation.}
{242}{}{Of course.}

{250}{}{(surprised) Me? Well... Could we talk? In private.}
{251}{}{I don't see anything reprehensible in this.}
{252}{}{Well, well, well, *now* you need something?}
{253}{}{(looks around) Could we talk? In private}

{260}{}{Go to the toilet behind the hotel at 22:00.}
{261}{}{Deal.}
{1261}{}{Deal.}
{262}{}{How about no.}

#Dialogue while quest is in progress
{300}{}{Have you received any information?}
{301}{}{I'll be back when I find some.}

#Quest outcome - family dead
{302}{}{I managed to find your relatives, but they turned out to be dead. Don't ask. The tinsmiths are not at fault.}
{303}{}{I should have expected this... Looks like the Collective was right - I can't hold on to the past. And I don't even know if our relations would be good, if we found each other. Now, thanks to you, I can finally rid myself of this splinter in my mind. I won't allow my feelings to overpower my mind anymore.}
{304}{}{Well, that's up to you.}

#Quest outcome - player found the family
{310}{}{Your family is still alive in Casa Grande.}
{311}{}{My previous family is alive? Unbelievable! I want to know everything.}
{312}{}{I don't think you're goin to like what they had to say to me. They told me the tinsmiths just took you during a raid.}
{313}{}{So my brothers-in-metal have been lying to me all this time?! My worst fears have been confirmed... You know, Master Khard won't like it that I'm digging in the past. Especially considering just *what* I've learned...}
{314}{}{My part of the deal is done. It's up to you to figure the rest of it out.}
{315}{}{Wrong. I need to receive proof of what you're saying. Otherwise, the deal is no more.}
{316}{}{Fine. What do you want?}
{317}{}{Totally. Do you want to return to your family?}
{318}{}{I can't stay in Two Sun until I get to the bottom of this story. I need to meet and talk with my family. But Master Khard won't allow me to leave willingly.}
{319}{}{I'll talk with Khard. Maybe he'll allow your family to travel to Two Sun.}
{320}{}{Even I wouldn't be able to convince him. And if I can't, you certainly can't either.}
{321}{}{I'll try. Wait here.}

{322}{}{You have to get out of here.}
{323}{}{Alright, I'll help you get out of here. What do I need to do?}
{324}{}{I could try traveling with a caravan, but first, I need to get rid of the chip. Every tinsmith has a chip installed under the skin of their neck. It transmits location data. Help me remove it! I won't be able to do it on my own.}
{325}{}{Alright, let's do this...}

{326}{}{What am I supposed to do, exactly?}
{1326}{}{What am I supposed to do, exactly?}
{327}{}{Wait a bit.}
{328}{}{But aren't they going to severely punish you.}
{329}{}{I was an outsider here from the beginning... Maybe it's my emotions talking, but it's better to give up my unstable life in Two Sun and go back to my family.}

#Quest outcome - convinced Khard
{330}{}{Khard has allowed your family to visit you. You don't need to go against the Collective anymore.}
{331}{}{How did you do it?! Even his few close friends have trouble arguing with him. You're not even a tinsmith. Amazing... I mean, I'm very grateful. Thanks to you, I finally dealt with this old splinter in my mind. This is very important to me.}
{332}{}{Well, I think this story has finished.}

{335}{}{Your chip is no longer an issue. You can safely leave Two Sun.}
{336}{}{Great. I wouldn't be able to convince Master Khard anyway. But with your help, I'll finally be able to deal with this old splinter in my mind.}
{337}{}{Good luck.}

{340}{}{There's something you should know. The tinsmiths didn't take you. They took you as payment for repairing a water pump.}
{341}{}{My parents... sold me?! This changes everything... You know, Master Khard won't like that I'm digging in the past. Especially considering just *what* I've learned. In any case, thanks to you, I can finally get rid of this old splinter in my mind.}
{342}{}{Exactly. It's time to forget this story.}
{343}{}{That's up to you to decide.}

#Final dialogue
{400}{}{Thanks for your help.}
{401}{}{You're welcome.}

{410}{}{You promised to get me something.}
{411}{}{Yes. What do you need?}
{412}{}{Let me think about it.}
{413}{}{Here, take it. But from this moment on, our deal is considered complete.}
{414}{}{Unfortunate, but a deal is a deal. Good luck.}

{420}{}{I could use more caps.}
{421}{}{I could use atomic batteries.}
{422}{}{The famed tinsmith pneumatic fist.}
{423}{}{One of your pneumatic spears.}
{424}{}{Could you get me night-vision goggles?}
{425}{}{A laser pistol would be the best reward.}
{426}{}{I'm in need of explosives.}

{430}{}{Could you get me a power cell for a generator?}
{431}{}{No way! Power cells are the most valuable thing we produce. Their production and usage are planned a year in advance.}
{432}{}{I see.}