{100}{}{You see Romeo-Six.}
{101}{}{You see one of the tinsmiths. He looks very young, almost a teenager.}
{102}{}{To remove the implant, use the surgery skill.}
{103}{}{Following the tinker's instructions, you manage to extract the chip from his body.}
{104}{}{Alien? Here? Perhaps I should double-check my weapon...}

#The first dialog
{200}{}{(in front of you is a teenage tinker with wide-open eyes; he is studying your person with interest) A man from the wasteland, you should know that in Two-Sun they do not like outsiders. Better not to test our patience.}
{201}{}{}
{202}{}{Hey, man, I just want to talk.}
{203}{}{Go away. We're not allowed to talk to you. (turns around and walks away from you)}
{204}{}{It wasn't very kind...}
{1204}{}{Fi. What boorish treatment of ladies...}
{205}{}{There is indecision in your words. Are you lonely here?}
{206}{}{(stops in bewilderment) The team considers communication with low-developed outsiders unproductive... while it does not bring benefits.}
{207}{}{That's what the Team thinks. And what do you think *you*?}
{208}{}{Hey, who are you calling low-level?}
{209}{}{Typical savage reaction. Even if there is a uranium generator in your village, and the authorities use laser weapons, you still remain savages.}
{210}{}{If our communication is "unproductive", then why are you still talking to me? Is there any doubt?}
{211}{}{I won't set foot here after what I've heard. Goodbye...}

{212}{}{Do you suggest leaving soon?}
{213}{}{The team considers you a destructive element and suggests avoiding contact.}
{214}{}{Yeah, it's not easy to earn trust here. Goodbye, tinker.}
{215}{}{Who is destructive here? Mind you, I won't tolerate it next time.}
{216}{}{(hesitates) At first... Talk to Master Hard first.}
{217}{}{Great, I'll remember that.}
{218}{}{Yes... no...}
{219}{}{No?}

#Dialogue at the toilet
{220}{}{I can't talk right now. Meet me at 22:00 behind the hotel.}
{221}{}{Okay.}
{222}{}{This is not the right place. Meet me behind the hotel.}
{223}{}{Okay.}
{224}{}{They won't hear us here.}
{225}{}{It seems that last time you hesitated when talking about your Team. Is something bothering you?}
{226}{}{Worried? Yes... perhaps. The collective teaches that our past is insignificant, we must forget it and live in the future for the sake of Progress. But I can't just give up mine... childhood.}
{227}{}{Childhood? So you're not from here?}

{228}{}{Previously, Two-Sun was closed to outsiders. But when the population decreased, the Team had to restore the population with children from other settlements. I was accepted and re-educated at the age of five. I haven't seen my family since.}
{229}{}{I travel a lot and I can look for traces of your relatives.}

{230}{}{Are you really going to do this? Fine... But my file says that relatives died during the war in Casa Grande. Talk to the locals. I just want to know what happened on the day of our separation.}
{231}{}{Why not ask other tinkerers directly?}
{232}{}{The team does not stand on ceremony with those who violate the order. Refusal to obey the majority opinion is punishable by severe penalties. Such precedents have already happened. I don't want to test the patience of the Team on myself.}
{233}{}{ }
{234}{}{ }
{235}{}{Perhaps I will help, but the way to another city is not cheap.}
{236}{}{I can get some of our technology if you're interested. But don't count on large stocks, I have a low level of access to the warehouse.}
{237}{}{Okay, I'll look for your parents.}
{238}{}{(brightening up) Great! That is... (makes a dry face) I would be grateful... Now we'd better disperse before we arouse suspicion. And it's not worth talking about the conversation.}
{239}{}{No problem.}
{240}{}{Actually, I'm not on my way, so I'm sorry.}
{241}{}{Sorry... But if you find yourself in Casa Grande, then remember my request. And now we'd better go our separate ways. Consider that this conversation did not happen.}
{242}{}{No problems.}

{250}{}{(surprised) Am I? Well... Can we talk in private?}
{251}{}{I don't see anything wrong with that.}
{252}{}{So, now you need something, huh?}
{253}{}{(looks around) Can we talk in private?}

{260}{}{Come at 22:00 to the toilet behind the hotel.}
{261}{}{Agreed.}
{1261}{}{Oh, a date with a tinker? It's intriguing. I'll be there.}
{262}{}{I don't think I want to be with you... uh, dating.}

#Dialogue when the quest is open
{300}{}{Do you have any information for me?}
{301}{}{I'll come back when I find out something.}

#Quest - the family died
{302}{}{I managed to find your family, but she turned out to be dead. Don't ask, the tinsmiths have nothing to do with it.}
{303}{}{This was to be expected... The team was right - you can't cling to the past. After all, it is not even known if we could find mutual understanding after so many years of separation. Now, thanks to you, I can finally get rid of the old splinter. And from now on I will not let feelings take over my mind.}
{304}{}{Well, it's up to you to decide.}

#Quest - GG found a family
{310}{}{Your family still lives in Casa Grande.}
{311}{}{Is my past family still alive? Unbelievable! Tell me everything you know!}
{312}{}{I don't think you'll like their story. According to them, the tinkerers just took you away during the raid.}
{313}{}{That is, my metal brothers have been deceiving me all this time?! That's what I've always been afraid of... You know, Master Hard won't like me digging into the past. Especially after what I learned...}
{314}{}{My part of the deal is done, then figure it out for yourself.}
{315}{}{Well, no. I have to get proof of your words, otherwise the deal will be canceled.}
{316}{}{Okay. What do you want?}
{317}{}{That's for sure. Do you want to go back to your family?}
{318}{}{I can't stay in Two-Sun anymore until I figure this story out to the end. I need to meet and talk to my family. But Master Hard won't let me go voluntarily.}
{319}{}{I'll talk to Hard, maybe he'll let your family come to Two-Sun.}
{320}{}{Even I won't be able to convince him. And even more so for you.}
{321}{}{I'll try. Wait for news.}

{322}{}{You have to run.}
{323}{}{Okay, I'll help you escape. What should I do?}
{324}{}{I can ask to join the caravan, but first I need to get rid of the chip control. Every tinker has such a chip sewn under the skin on his neck. It transmits data about my location. Help me remove it! I won't do it myself.}
{325}{}{Okay, let's try...}

{326}{}{So what should I do?}
{1326}{}{So what should I do?}
{327}{}{Wait a little longer.}
{328}{}{But then you will be seriously punished by your own.}
{329}{}{I've been a stranger here from the very beginning... Probably, emotions are speaking in me now, but I'd rather sacrifice my precarious position in Two-Sun and return to my family.}

#Quest - Hard managed to convince
{330}{}{Hard has agreed to meet with your family in Two-Sun. You don't have to go against the collective anymore.}
{331}{}{How did you manage it?! It's hard to argue with Master Hard, even for his narrow circle of confidants. But you're not even a tinker. Amazingly... I mean, I'm grateful to you. With your help, I will finally be able to sort out the old thorn. This is very important to me.}
{332}{}{Well, I think we have resolved this issue.}

{335}{}{Your chip is no longer a problem. You can leave Two-Sun.}
{336}{}{Great. I wouldn't have been able to negotiate with Master Hard anyway. But with your help, I will finally be able to sort out the old thorn.}
{337}{}{Well, have a good trip.}

{340}{}{I think you should know that. The tinsmiths didn't take you away but took me as payment for helping repair the water station.}
{341}{}{Me... sold by parents?! It changes a lot... You know, Master Hard won't like it if I keep bringing up the past. Especially after what I found out. Anyway, thanks to you, I can get rid of the old splinter.}
{342}{}{Exactly. It's time to put an end to this story and move on.}
{343}{}{It's up to you.}

#Final dialogue
{400}{}{Thank you for your help.}
{401}{}{Please.}

{410}{}{You promised to get something for me.}
{411}{}{There are no objections. What do you need?}
{412}{}{Give me time to think.}
{413}{}{Here, take this. But from this moment on, our deal is considered completed.}
{414}{}{Sorry, but a deal is a deal. Happily.}

{420}{}{I would like to lift the caps.}
{421}{}{I need nuclear batteries.}
{422}{}{The pneumatic fist that tinsmiths are famous for.}
{423}{}{One of your pneumatic copies.}
{424}{}{Can you get glasses with a night visor?}
{425}{}{A laser gun is the best gift.}
{426}{}{I really need explosives.}

{430}{}{Can you get the power cell for the generator?}
{431}{}{Oh no, these cells are the most valuable thing we make. Their production and disposal are planned for a year ahead.}
{432}{}{I see.}