{100}{}{You see a doctor.}
{101}{}{You see Doc Jones. He looks more like a mechanic than a doctor.}
{102}{}{Operation successful.}

#Floating dialogue (do not delete empty lines)
{110}{}{Fixing people isn't like fixing machinery.}
{111}{}{I never thought about what went into those stim-paks before.}
{112}{}{More traumas as of late.}
{113}{}{I lose a few more patients - I'm definitely getting a technical inspection.}
{114}{}{ }
{115}{}{ }
{116}{}{ }
{117}{}{ }
{118}{}{ }
{119}{}{ }

#First dialogue
{200}{}{Aah, fresh meat. Lie down here. (unceremoniously points to a dirty operating table) So, what are we fixing?}
{201}{}{I'm not a machine to be *fixed*.}
{202}{}{Fine, I get it. You're of the fragile type, right? I suggest amputation - the most effective method in such situations.}
{203}{}{Hey, it's not so bad!}
{204}{}{It isn't? (corrects his strange glasses with glowing lenses, while scanning for something below your chest)}
{205}{}{Uhh, doc... maybe we should talk first?}
{206}{}{Wait a bit, doc, I'll be right back...}
{207}{}{But we're out of tourniquets, so you'll just have to suffer for a while.}

{210}{}{Again?}
{211}{}{Wrong door, doc.}
{212}{}{Enough talk.}
{213}{}{Next topic.}

#Healing
{220}{}{I need healing.}
{221}{}{I'm afraid I'm going to have to disappoint you - I only heal my brethren and those I am ordered to heal by our leader.}
{222}{}{This is not good.}
{223}{}{You have bottle caps? Then show me what needs fixing.}
{224}{}{Nothing.}
{225}{}{Just heal these wounds, doc.}
{226}{}{}
{227}{}{That will cost you }
{228}{}{ caps.}
{229}{}{Okay, doc. Here they are.}
{230}{}{You know, doc, it'd probably be better if I just endured it.}
{231}{}{That can wait. I have more important things to ask you.}
{232}{}{You're perfectly operational.}
{233}{}{Thanks, doc.}
{234}{}{Next time I'll go find another clinic. Bye.}
{235}{}{caps.}

{250}{}{I've heard rumors you tinsmiths have advanced cybernetic implants. Can you install one in me?}
{251}{}{(frowning) Master Khard has agreed to your medical treatment. But spending our priceless implants on a desert savage is far beyond the point of reason.}
{252}{}{Are they that important to you?}
{253}{}{Even among our ranks, few are allowed to have a new implant installed. The procedure requires good reasons and confirmed compatibility. Some wait years for their turn.}
{254}{}{Master Khard deems me worthy. I don't think he'll mind one single operation.}
{255}{}{That may be so. What kind of implant do you want to get? All of these cost }
{256}{}{Not now. I have some business to take care of before I commit to such a major operation.}
{257}{}{Oh. Your body seems to be incompatible with this one.}
{258}{}{Shame. What about another?}
{259}{}{Then let's postpone the operation until then.}
{260}{}{[Strength +1]}
{261}{}{[Perception +1]}
{262}{}{[Endurance +1]}
{263}{}{[Charisma +1]}
{264}{}{[Intelligence +1]}
{265}{}{[Agility +1]}
{266}{}{[Luck +1]}
{267}{}{Excellent.}
{268}{}{ caps. Upfront. Then we can begin. After the operation, you'll need to remain here for around 48 hours to let the system adapt to your body.}
{269}{}{Here are the caps. Let's start, doc.}

#Questions
{300}{}{Why is it so dirty here?}
{301}{}{(looks around in confusion) It is?}
{302}{}{Doc, I'm afraid to ask, but... how many of your patients survive after the operations?}
{303}{}{Just a second, let me turn on the statistics analyzer... There. 58 percent.}
{304}{}{So... a bit more than half.}
{305}{}{This isn't the place you go to get treated for some scratches and cuts. Most patients come here with life-threatening traumas. Second most common reason - electric shock. Following that, irradiation, breathing issues, loss of vision, diarrhoea-}
{306}{}{Uhh, thanks, I get it, doc. You don't need to list them all...}

{310}{}{Tell me about the clinic.}
{311}{}{This is a hospital, not a bar.}
{312}{}{How did you become a doctor?}
{313}{}{My predecessor attempted to self-install a neural implant to improve his medical skills. Something went wrong during the procedure and he died of intracerebral bleeding. My brethren were in need of a new medical specialist. That was when I was sent to learn from the Followers of the Apocalypse. I have been serving here since the moment I got back.}
{314}{}{Where do you get your medical supplies?}
{315}{}{Old, Pre-War medication is received mainly from Phoenix caravans. New ones - from a small laboratory in Casa Nueva. They produce their own medicine there.}
{316}{}{Who are these Followers of the Apocalypse?}
{317}{}{I would call them fanatics, obsessed with the knowledge of the Old World. But all the knowledge in the world is useless without technology.}

{320}{}{Why do the tinsmiths install implants in themselves?}
{321}{}{The human body is fragile and vulnerable. By replacing parts of ourselves with machinery, we seek to make ourselves more secure, to become stronger, smarter and more resilient. The dream of every tinsmith is to become entirely machine and digitize their consciousness. But that, unfortunately, is an unreachable ideal.}

{330}{}{What happened to this patient?}
{331}{}{He was badly wounded. To save his life, I attempted to install a couple of implants and replace the lost limbs with prosthetic equivalents. But the fragile human body is rejecting the technology. He cannot live without these implants, but with them, he dies too. Bitter irony.}
{332}{}{Can he be healed?}
{333}{}{Fixed? No, I'm afraid not. He'll have to be dismantled.}
{334}{}{Can I try to help him?}
{335}{}{If our technologically advanced medicine has failed to save him, your tribal rituals will not be of any help, either. However, in such a hopeless situation, there's no point preventing you from trying.}
{336}{}{Let's see how good my "rituals" are, doc.}
{337}{}{Let's talk about something less morbid.}