{100}{}{You see a doctor.}
{101}{}{This is Doc Jones. He looks more like a mechanic than a doctor.}
{102}{}{The operation was successful.}

#Floating replicas (do not delete empty lines)
{110}{}{Fixing people is harder than fixing machinery.}
{111}{}{I've never thought about the composition of stimpacks.}
{112}{}{Injuries have become more frequent lately.}
{113}{}{I will lose a couple more patients - and I will definitely face a technical inspection.}
{114}{}{ }
{115}{}{ }
{116}{}{ }
{117}{}{ }
{118}{}{ }
{119}{}{ }

#The first dialog
{200}{}{Ah, fresh meat. Fall in there. (unceremoniously points to the dirty operating table) What are we going to fix?}
{201}{}{I'm not a tin can to fix me.}
{202}{}{Okay, got it. So you're made of a particularly brittle alloy? Then I suggest amputation - the most effective way.}
{203}{}{Hey, I'm not that bad!}
{204}{}{Really? (adjusts strange glasses with luminous lenses and looks for something below your chest)}
{205}{}{Eh, doc... can we talk first?}
{206}{}{Wait, Doc, I'll be back soon...}
{207}{}{But the tourniquets are over, so you'll have to suffer.}

{210}{}{What, back to me?}
{211}{}{Wrong door, doc.}
{212}{}{Enough talking.}
{213}{}{Another question.}

#Treatment
{220}{}{I need treatment.}
{221}{}{I have to disappoint you - I treat only my brothers and those whom our leader orders me to.}
{222}{}{This is not good.}
{223}{}{Are there any caps? Then show me what's broken.}
{224}{}{Nothing.}
{225}{}{Just heal my wounds, Doc.}
{226}{}{}
{227}{}{The cost of treatment will be }
{228}{}{ caps.}
{229}{}{Okay, Doc, here are the bottlecaps.}
{230}{}{You know, Doc, it's better if I put up with it.}
{231}{}{It can wait. Now it's more important for me to know something.}
{232}{}{You're fine.}
{233}{}{Thanks, doc.}
{234}{}{Next time I'll find another clinic. Later.}
{235}{}{caps.}

{250}{}{Can you get me one of those implants of yours?}
{251}{}{(frowning) Master Hard has agreed to your medical care. But spending the most valuable implants on a savage from the desert is beyond reasonable.}
{252}{}{Are they that important to you?}
{253}{}{Not every tinker is allowed to install a new implant. This requires a good reason and the capabilities of the body. Some have been waiting for their turn for several years.}
{254}{}{Master Hard thinks I'm worthy. I think he won't mind one operation.}
{255}{}{Maybe so. Choose the type of implant. Its cost is }
{256}{}{Not now. I need to prepare for such an operation.}
{257}{}{Oh no, the installation of this implant is contraindicated for you.}
{258}{}{Sorry. Can we try another one?}
{259}{}{Then we will postpone the operation for a while.}
{260}{}{[Strength +1]}
{261}{}{[Perception +1]}
{262}{}{[Endurance +1]}
{263}{}{[Charisma +1]}
{264}{}{[Intelligence +1]}
{265}{}{[Dexterity +1]}
{266}{}{[Luck +1]}
{267}{}{Great. }
{268}{}{ caps, and we can start. After the operation, it will also take two days to adapt.}
{269}{}{Here are the bottlecaps. Go ahead, Doc.}

#Questions
{300}{}{Why is it so dirty here?}
{301}{}{(looks around in bewilderment) Is it?}
{302}{}{Doc, I'm afraid to ask, but... how many of your patients survived surgery?}
{303}{}{Wait, I'll turn on the statistics analyzer... There is. 58 percent.}
{304}{}{So... a little more than half.}
{305}{}{This is not a place where people get to with light scratches. Most patients come with severe injuries. In second place is an electric shock. And then - radiation, breathing problems, decreased vision, diarrhea...}
{306}{}{Uh, I see, doc. You don't have to continue...}

{310}{}{Tell me about the clinic.}
{311}{}{This is a hospital, not a bar.}
{312}{}{How did you become a doctor?}
{313}{}{My predecessor tried to install a neuroimplant to improve his medical skills. Something went wrong and he died of a brain hemorrhage. My brothers needed a new doctor, and then I was sent to study with the Followers of the Apocalypse. I have been serving here ever since.}
{314}{}{Where did you get the medicines from?}
{315}{}{The old pre-war drugs are mostly brought by caravans from Phoenix. And the new ones are from a small laboratory in Casa Nueva. They have their own production there.}
{316}{}{Who are these Followers of the Apocalypse?}
{317}{}{I would call them fanatics obsessed with the knowledge of the Old World. However, knowledge is useless without technology.}

{320}{}{Why do tinsmiths implant electronics in themselves?}
{321}{}{The human body is fragile and vulnerable. By replacing parts with electronics, we are trying to protect ourselves, become stronger, smarter and more viable. The dream of every tinker is to achieve complete cybernetization and digitization of personality. But this, unfortunately, is an unattainable ideal.}

{330}{}{What happened to this patient?}
{331}{}{He's seriously injured. To save him, I tried to install a couple of implants and prostheses. But the fragile human body rejects technology. He can't survive without implants, but he dies with them. Evil irony.}
{332}{}{Can it be cured?}
{333}{}{Fix it? I'm afraid not. It will have to be "dismantled".}
{334}{}{Can I try it?}
{335}{}{If our high-tech medicine can't cure him, then your savage rituals won't help any more. But I don't mind interfering in such a hopeless situation.}
{336}{}{Let's see what my "rituals" are capable of, Doc.}
{337}{}{Let's talk about something less pessimistic.}