{100}{}{You see the owner of the hotel.}
{101}{}{You see the owner of the hotel. He's lazily scratching his belly as he sits heavily in the ancient pilot seat.}
{102}{}{Close the door now! The robots are everywhere!}

#First dialogue
{200}{}{(reluctantly turns towards you) All rooms are occupied.}
{201}{}{But there are so many keys hanging on the counter...}
{202}{}{They're reserved. Not for sale. If you need a place to sleep, then I suggest asking people in other buildings.}
{203}{}{I doubt they'll let me in.}
{204}{}{That's your problem. Not mine.}
{205}{}{Uhh, okay...}

{210}{}{I told you - all rooms are occupied.}
{211}{}{I think you just want to avoid outsiders.}
{212}{}{I know.}

{213}{}{And I think somebody here is sticking their nose into things that are none of their business.}
{214}{}{Hmm...}

{215}{}{(leans towards you) The tinsmiths are afraid of espionage. They don't want anybody to know of their plans. I have to be careful with outsiders.}
{216}{}{It's good that we've come to an agreement.}
{217}{}{As a Follower of the Holy Fire, I am enraged by the quality of your service!}
{218}{}{I don't think the Brotherhood of Steel will appreciate its members being treated like this.}
{219}{}{Come on! What's with the distrust?}
{220}{}{Think twice about where you are.}
{221}{}{Yes, of course...}

#Repeat dialogue
{250}{}{How can I help you?}
{251}{}{You can't, but thanks for asking. I'll figure things out.}
{252}{}{Goodbye.}

{260}{}{What's going on here?}
{261}{}{The tinsmiths are trying to get access to a big cache of old war machines. No results yet, but it's just a matter of time.}
{262}{}{The tinsmiths recently got access to a big treasure trove of old military technology. We all have a lot of work ahead of us, it seems.}
{263}{}{Know anything about slaves from Villa?}
{264}{}{No, I don't. Ask people in the hangar, that's where they keep the slaves.}
{265}{}{How did you manage to settle in here?}
{266}{}{I arrived here a couple of years ago, when the tinsmiths established a trade route with Phoenix. They needed a hotel to work with the caravaneers, and I made them one. If not for the tinsmiths, I wouldn't have made it to such an age. I'd probably be lying somewhere in the Wastes, my bones scraped clean by the desolate wind.}