{100}{}{This is the owner of the hotel.}
{101}{}{Here is the owner of the hotel. He lazily scratches his belly, sitting heavily in the old pilot's seat.}
{102}{}{Close the door quickly! These robots are everywhere!}

#The first dialog
{200}{}{(reluctantly turns in your direction) All rooms are occupied.}
{201}{}{But half of the keys are hanging on the counter...}
{202}{}{A big race is planned. These numbers are not for sale. If you need to spend the night, I advise you to knock on residential buildings.}
{203}{}{I don't think I'll be welcome there.}
{204}{}{It's none of my business.}
{205}{}{Uh, okay...}

{210}{}{I told you - the rooms are occupied.}
{211}{}{I think you're just avoiding strangers.}
{212}{}{I remember.}

{213}{}{And I think that some people allow themselves too much.}
{214}{}{Grm...}

{215}{}{(leaning towards you) Tinkerers are afraid of espionage and do not want their plans to be public, so I have to be careful with strangers.}
{216}{}{It's good that we found a common language.}
{217}{}{As a Follower of Fire, I am outraged by your service!}
{218}{}{I think the Brotherhood of Steel will not approve of such an attitude towards its subordinates.}
{219}{}{Come on, why so much distrust?}
{220}{}{You're out of town.}
{221}{}{Well, yes, of course...}

#Repeat dialog
{250}{}{What can I do for you?}
{251}{}{Thanks, I'll figure it out somehow.}
{252}{}{Goodbye.}

{260}{}{Tell me what's going on here?}
{261}{}{Tinsmiths are trying to open the burial ground of military equipment. There are no results yet, but it's only a matter of time.}
{262}{}{Tinsmiths have opened the burial ground of military equipment. It looks like we have a lot of work ahead of us.}
{263}{}{Do you know anything about slaves from the Villa?}
{264}{}{No. I don't know. Ask in the hangar, they keep slaves there.}
{265}{}{How did you manage to get along in this place?}
{266}{}{I came here a few years ago when the tinsmiths opened a trade route with Phoenix. They needed a hotel to work with caravanners, and I organized it for them. If it wasn't for the tinsmiths, I wouldn't have lasted to my age. Surely he would be lying somewhere in the wastelands right now, warming his bones in the sun.}