{100}{}{You see a tinsmith.}
{101}{}{You see one of the tinsmiths.}

{200}{}{(After a long journey across a lifeless highway you are brought to the tinsmith settlement. You are put in a row with the other slaves, exhausted from waiting under the baking sun)}
{201}{}{[Continue]}
{202}{}{(One of the tinsmiths scans your body and verifies the data on his tablet) You. From Villa, too? Point them to the Instructor, to be sent after their relatives... Next!}
{203}{}{[Continue]}

{210}{}{I'm busy.}
{211}{}{Whatever you say.}