{100}{}{You see the tinker.}
{101}{}{You see one of the tinsmiths.}

{200}{}{(After a long journey along a deserted highway, you are brought to the settlement of tinsmiths. You are put in a row with the rest of the slaves, exhausted from waiting under the scorching sun)}
{201}{}{[Next]}
{202}{}{(One of the tinsmiths examines you and checks the data on the tablet) You. Also from the Villa? Send him to the Instructor, let him send him after his relatives... So, next...}
{203}{}{[Next]}

{210}{}{I'm busy.}
{211}{}{Whatever you say.}