{100}{}{You see an instructor.}
{101}{}{You see a tinsmith responsible for preparing slaves.}

{200}{}{(adressing the entire group) Now listen to me closely, you rusty cogs! You've been brought here so that your pathetic existence gains at least some meaning!}
{201}{}{[Continue]}
{202}{}{You will have the great honor of participating in the extraction of ancient technology from the Forbidden Zone. That place holds in it equipment from before the War. But there is a problem - a sophisticated security grid doesn't let us past the perimeter. You will need to enter the command center and disable the security from there. Those who do this will receive full freedom.}
{203}{}{[Continue]}
{204}{}{Any questions?}
{205}{}{Yes.}
{206}{}{Not at all.}
{207}{}{Then pick up your shit and go! Anyone who escapes the Forbidden Zone before the end of the mission will be permanently dismantled.}
{208}{}{This is not going to be easy...}
{209}{}{No.}

{210}{}{Who do you think you are? Speak faster!}
{211}{}{Can I get back my equipment if I suceed?}
{212}{}{Yes, in the box in the quartermaster's room. But don't count on it.}
{213}{}{Is my father, Andres, in the Forbidden Zone as well?}
{214}{}{I have no idea who you're talking about. So many pieces of human garbage died in there that I don't see the point of remembering their names.}
{215}{}{What can we expect in the Forbidden Zone?}
{216}{}{Hostile robots, electromagnetic traps and an increased level of radiation. The perimeter is surrounded by a force field, so you're not getting out without a fight.}
{217}{}{Will we be provided with any weapons?}
{218}{}{Use whatever you find in the Zone.}
{219}{}{At least give me brass knucles.}
{220}{}{At least give me a primitive pistol.}
{221}{}{At least give me a stimpak.}
{222}{}{At least give me grenades to use against the robots.}
{223}{}{I'm tired of your whining! You won't receive any weapon at all.}
{224}{}{I'm tired of your whining! Take this and shut your mouth.}
{225}{}{Another question.}

{230}{}{Any results? Report to our leader personally.}
{231}{}{Okay.}
{232}{}{What's this? A volunteer wants to go into the Forbidden Zone?}
{233}{}{Yeah, I'll be participating too.}
{234}{}{No, I'm just passing by.}
{235}{}{Ask your stupid questions, volunteer.}
{236}{}{Talk to our boss, I just handle the slaves.}
{237}{}{Okay.}
{238}{}{The mighty ZAX has fallen! The coming days are going to be filled with much work. That'll be an excellent time to find new slaves.}
{239}{}{I hope you won't need me this time... Uhh, bye.}