{100}{}{You see the instructor.}
{101}{}{You see one of the tinsmiths responsible for training slaves.}

{200}{}{ (addressing the whole group) Listen to me, rusty gears! You were brought to this city so that your insignificant existence would find at least some meaning!}
{201}{}{[Next]}
{202}{}{You have the great honor of participating in the extraction of ancient technologies from the Forbidden Zone. This place has been storing equipment since pre-war times. But there is a problem - a reliable security system does not let us outside the perimeter. You have to get into the control center and disable the protection. To those who do, we grant complete freedom.}
{203}{}{[Next]}
{204}{}{Any questions?}
{205}{}{Yes.}
{206}{}{No way.}
{207}{}{Then pick up your rags and run to the parade ground! Anyone who escapes from the Restricted Area before the end of the mission will be permanently dismantled.}
{208}{}{It looks like it's going to be a tough test...}
{209}{}{No more questions.}

{210}{}{Do you think you can do anything? State it quickly, piece of rags!}
{211}{}{Will I be able to pick up my things if I complete the task?}
{212}{}{Will you pick them up in the quartermaster's drawer? But do not hope that you will succeed.}
{213}{}{Is my father named Andres also in the Restricted Area?}
{214}{}{I have no idea who you're talking about. So much human garbage has already disappeared in the Zone that I don't see the point in remembering at least one of them.}
{215}{}{What should we expect in the Forbidden Zone?}
{216}{}{Hostile robots, electromagnetic traps, and increased radiation background. The perimeter is fenced with a force barrier, so you can't get out without a fight.}
{217}{}{Will they give us at least some weapons?}
{218}{}{Use what you find in the Zone.}
{219}{}{At least give me the brass knuckles.}
{220}{}{At least give me a primitive gun.}
{221}{}{At least give me a stimpack.}
{222}{}{At least give me grenades against robots.}
{223}{}{I'm tired of your whining, pieces of rags! You won't get any weapons.}
{224}{}{I'm tired of your whining, pieces of rags! Take this and shut up.}
{225}{}{Another question.}

{230}{}{Is there a result? Report to our leader personally.}
{231}{}{OK.}
{232}{}{What? A volunteer mercenary in a Restricted Area?}
{233}{}{Yes, I will also participate.}
{234}{}{No, I'm just passing by.}
{235}{}{Ask your stupid questions, volunteer.}
{236}{}{Talk to our boss, I only deal with slaves.}
{237}{}{Okay.}
{238}{}{The great ZAX is defeated! Now we will have hot working days. So, it's time to look for new slaves.}
{239}{}{I hope you can do without me this time... Uh, bye.}