{100}{}{You see your padre.}
{101}{}{You see Andres, your father.}
{102}{}{Your padre has died.}
{103}{}{You receive }
{104}{}{ experience points for freeing your fellow tribesmen.}
{105}{}{That's for my rough childhood, padre.}
{106}{}{Bye. I don't need my father telling me what to do anymore.}

#First dialogue
{200}{}{?!}
{201}{}{Hello, padre.}
{202}{}{How did you find us?}
{203}{}{Well, I had to run around the desert for a while...}
{204}{}{Do you even realize what kind of situation we are in?! You shouldn't be here, you should be at home!}
{205}{}{Villa is being slowly restored. I manage to free some of our people in Flagstaff.}
{206}{}{I see... I see now that I was wrong to think of you as a child. Looks like all these events have given you much life experience. In that case, I'm glad you're here.}
{207}{}{I thought it would be better to save the leader of Villa first, before the others.}
{208}{}{Better?! You think that's better?! Villa can survive without me. An settlement doesn't need a leader if it's abandoned! You should have gone to Flagstaff, to the north, where they are holding our people. Your madre is there as well.}
{209}{}{Alright. Have any ideas on how to get out of here?}
{210}{}{We would have done that already a long time ago, but crossing that barrier is impossible. That's without the fact that the territory is crawling with dangerous robots. The only way out is to reach the center of this place and disable whatever is in there.}
{211}{}{Let's do it, then?}
{212}{}{Don't rush things. This territory is dangerous: not just hostile robots, but also traps. And nobody knows what's inside that bunker. First, scout, find weapons and someone to help you fight.}
{213}{}{No problem, padre. I'll find a way out.}
{214}{}{Not even a thanks. I'm saving you, you know.}
{215}{}{I'll get by without you telling me what to do. Just sit here and wait my instructions.}

#Repeat dialogue
{220}{}{Speak, }
{221}{}{.}
{222}{}{I'll be back soon.}

{230}{}{Let's discuss our plan again.}
{231}{}{Our plan is to sneak past the robots, enter the bunker, and, whatever it is in there, gain control over it. Once we do that, we leave this cursed place and get back to Villa.}
{232}{}{Alright.}

{233}{}{Where can I find weapons?}
{234}{}{Many slaves and mercenaries died here. Search their bodies, one of them may have a weapon. Some old machine not far from here has something that looks like a big gun sticking out of it, but we don't know how to use it.}
{235}{}{Are there other slaves here?}
{236}{}{Some survivor made a camp not far from the bunker. But he has refused to make contact with us. Looks like not all is right with his head.}
{237}{}{How can I sneak past the robots?}
{238}{}{These beasts are more cunning than mole rats. They hide in dark corners or in the sand, you won't see them right away. But you can hear them from ten yards away.}

{240}{}{What is this place?}
{241}{}{As far as I understand, this is a graveyard for long-forgotten technology. The tinsmiths want to restore it. The imbeciles don't understand how dangerous the technology of the Ancients is!}
{242}{}{How do you know that those technologies are dangerous?}
{243}{}{Our forefathers have taught us to fear old technology. They told us that it is unreliable and unsafe, and it is. You have probably already stumbled upon things that can blow up in your hands or harm your health with invisible radiation. I heard stories of entire communities dying from extreme attachment to technology. And in the wrong hands, old things become tools of coersion, or even... extermination.}
{244}{}{Familiar stuff...}
{245}{}{Remember Flagstaff. Remember how easily a small group of stupid bandits enslaved an entire community just thanks to some weapons and electric collars. All that technology has got to be destroyed! All of it! With no exceptions!}
{246}{}{I have to think about this...}

{250}{}{Tell me about the raid on Villa.}
{251}{}{Let's leave these conversations for when we return home. In short, the raiders attacked us at the end of the work day, when our people were returning from the plantations, exhausted. I managed to hold the line in the town hall, but in the end, we were all captured, tied up and brought to Flagstaff. Most of us were sent to work in the local mine. The best of us were sent here.}
{252}{}{Did they bring you to Phoenix?}
{253}{}{Yes, they brought us to a church that was run by some kind of cult. Disgusting people devoid of compassion that have devalued human life. They studied us like rats - took blood for analysis, tortured us and asked us about Villa. Unfortunately, that church is now well-versed on our home.}
{254}{}{I have another question.}
{255}{}{Why were specifically you brought to Two Sun?}
{256}{}{As Villa's leader, I learned much over the course of my life. That's why I was selected as the best one for the job.}

#Joining the player's party, temporarily
{260}{}{Come with me. I need your experience.}
{261}{}{I'll help you get to the bunker. But you'll have to go down there alone.}
{262}{}{Alright, let's go.}
{263}{}{Why?}
{264}{}{You'll have a higher chance of staying undetected that way. Besides, I won't be much of use among all this technology. Your journey through Sonora has given you far more knowledge and experience.}
{1264}{}{You'll have a higher chance of staying undetected that way. Besides, I won't be much of use among all this technology. Your journey through Sonora has given you far more knowledge and experience.}
{265}{}{Hm. We'll see what I can do.}
{266}{}{I'll go alone from this point on.}
{1266}{}{I'll go alone from this point on.}
{267}{}{I'll guard the entrance to the bunker. Good luck.}
{268}{}{[Go]}

#Finishing the liberation quest
{300}{}{Khard has given you freedom. You can go.}
{301}{}{That's good. But *how* will we get out of here?}
{302}{}{Hm. Let me think about it.}
{303}{}{The barrier is disabled. We can escape Two Sun.}
{304}{}{Good work, }
{305}{}{. A shame that this is just a temporary measure. Now the tinsmiths will get access to old technology, and God knows how much they will harm the world with it. At least we have time to prepare.}
{306}{}{[Continue]}
{307}{}{Excellent work, }
{308}{}{. Not only did we receive freedom, but deprived the tinsmiths of these old technologies. God knows how much they would have harmed the wastes if they got control over the technology in that bunker.}
{309}{}{I'll rest for a bit and then head home. See you at Villa.}
{310}{}{Goodbye, padre.}
{311}{}{In the meantime, you could find Carlos and try to reason with him. The tinsmiths have got the fool to join them, filled his head with nonsense. If you can't convince him... He needs to be removed. Do you understand? Maybe I'm asking too much, but believe me, he is posing a potential threat to all of Villa.}
{312}{}{I understand, padre. You can trust me.}
{313}{}{Killing our fellow people? No way. But I'll try to reason with him.}