{100}{}{This is your padre.}
{101}{}{You see Andres, your father.}
{102}{}{Your padre is dead.}
{103}{}{You get }
{104}{}{ experience for the liberation of their fellow tribesmen.}
{105}{}{This is for you for my difficult childhood, Padre.}
{106}{}{Goodbye. I don't need my father's guidance anymore.}

#The first dialog
{200}{}{?!}
{201}{}{Hello, Padre.}
{202}{}{How did you manage to find us?}
{203}{}{Well, I had to run through the desert...}
{204}{}{Don't you understand the situation we're in?! Your place should not be here, but at home!}
{205}{}{The villa is gradually being restored. I managed to rescue those who were in Flagstaff from slavery.}
{206}{}{That's it... Now I see that I thought you were a child in vain. It seems that this whole story has given you a great life experience. In that case, I'm glad you're here.}
{207}{}{It seemed to me that it would be wiser to save the leader of the Villa, and then the others.}
{208}{}{And this is reasonable in your opinion?! Willa can live without me. And who needs a leader in an abandoned settlement?! You should have gone to the town of Flagstaff, where our people are being held. Your madre is there too.}
{209}{}{Okay. I'll deal with it later. Any ideas how to get out of here?}
{210}{}{We would have done it a long time ago if it weren't for the damn barrier. It is impossible to pass through it. The only way out is to get into the bunker of the control center and disable what is there.}
{211}{}{So let's do it?}
{212}{}{Easy to say. This area is teeming with robots and traps. And what is in the bunker, no one knows at all. First, conduct a reconnaissance, find equipment and companions. We also tried to create a weapon against robots. But our technician died while looking for the right parts, and I don't understand it.}
{213}{}{No problem, Padre. I'll find a way out.}
{214}{}{At least say thank you. I'm saving you.}
{215}{}{I'll figure it out without your guidance. Sit and wait for my instructions.}
{216}{}{Pa-adre-e, how long have I been looking for you!}
{1216}{}{Pa-adre-e, how long have I been looking for you!}

#Repeat dialog
{220}{}{Tell me, }
{221}{}{.}
{222}{}{I'll be back soon.}

{230}{}{Let's discuss the plan again.}
{231}{}{Our plan is to get past the robots, get into the bunker and, whatever it is, take control of it. And then get out of this damned place back to the Villa.}
{232}{}{Clear.}

{233}{}{Where can I get weapons?}
{234}{}{Many slaves and mercenaries died here. Look for bodies, maybe some of them still have weapons. I also saw something that looked like a weapon near a large plane. But I do not know how to use it.}
{235}{}{Are there other slaves here?}
{236}{}{There is a survivor's camp not far from the bunker. But he didn't want to cooperate with us. He doesn't seem to be right in the head. And he looks pretty... painful.}
{237}{}{How can robots be bypassed?}
{238}{}{These creatures are smarter than mole rats. They hide in dark corners or in the sand, you won't see them right away. But you can hear them from ten yards away. And it also looks like they're reacting to movement. If you move slowly or stand behind, they may not notice you.}
{239}{}{}

{240}{}{What is this place?}
{241}{}{As far as I understand, this is a graveyard of long-forgotten technologies. The tinkerers want to revive them. I wouldn't want that to happen. These fools do not understand the danger posed by the technology of the Ancients!}
{242}{}{How do you know that these technologies are dangerous?}
{243}{}{Our ancestors taught us to be afraid of old technology. They said she was unreliable and dangerous. All right. Have you already come across things that can explode in your hands or harm your health with invisible radiation? I've heard stories of entire settlements dying out from excessive attachment to technology. And in the wrong hands, old things become a weapon.}
{244}{}{Familiar stories...}
{245}{}{Remember Flagstaff. Remember how easily a group of stupid bandits enslaved an entire settlement only thanks to their weapons and electric collars. All this equipment must be destroyed! All without exception!}
{246}{}{It's worth thinking about...}
{247}{}{And what about your pneumoculac? I could use it.}
{248}{}{Will you leave the old man unprotected? (bitter laugh) Okay, we have one hope left - for you.}
{249}{}{Thanks for the gun, Padre.}

{250}{}{Tell me about the raid on the Villa.}
{251}{}{Let's leave these conversations until we get home. In short, the raiders attacked us at the end of the working day, when our people were returning from the plantations and were tired. I managed to hold the defense in the town hall, but in the end we were all caught, tied up and brought to the town of Flagstaff. Most were left to work in the local mine, and only the best were sent here.}
{252}{}{Have you been to Phoenix?}
{253}{}{Yes, we were brought to a church run by some cult. Disgusting people, devoid of compassion and devalued human life. They studied us in detail, like some kind of rats - they took blood for analysis, tortured us and asked about the Villa. Unfortunately, the church is now well aware of our house.}
{254}{}{There are more questions.}
{255}{}{Why exactly were you sent to Two-Sun?}
{256}{}{As a leader, I have learned a lot. Therefore, of all our residents, I was considered the best candidate for this job.}

#Joining the party
{260}{}{Let's go together. I need your experience.}
{261}{}{I'll help you get to the bunker. But you'll have to go down alone.}
{262}{}{Agreed.}
{263}{}{Why?}
{264}{}{That way you'll have a better chance of going unnoticed. Besides, among all these technologies, I won't be of any use anyway. Your journey through Sonora has given you a lot more knowledge and experience.}
{1264}{}{That way you'll have a better chance of going unnoticed. Besides, among all these technologies, I won't be of any use anyway. Your journey through Sonora has given you a lot more knowledge and experience.}
{265}{}{Hmm. Let's see what I can do.}
{266}{}{Next I'll go alone.}
{1266}{}{Next I'll go alone.}
{267}{}{I'll be guarding the entrance to the bunker. Good luck.}
{268}{}{[Go]}

#Completion of the rescue quest
{300}{}{Hard has given you freedom. You can go.}
{301}{}{It's good. But *how* are we going to get out of here?}
{302}{}{Hmm. Let me think.}
{303}{}{The barrier is disabled, we can escape from Two-Sun.}
{304}{}{Good job, }
{305}{}{. It's a pity, this is only a temporary measure. Now the tinkerers will have access to old technologies, and God only knows how much trouble they will cause. At least we have time to prepare.}
{306}{}{[Next]}
{307}{}{Great job, }
{308}{}{. We not only gained access to freedom, but also deprived the tinkerers of these old technologies. God only knows how much trouble they would have caused the wastelands by subjugating the equipment in the bunker.}
{309}{}{I'll rest for a while and then go home. Meet me at the Villa.}
{310}{}{Bye, Padre.}
{311}{}{Meanwhile, find Carlos and try to reason with him. The tinsmiths won this fool over to their side, filled his head with nonsense. In case of failure... It must be eliminated. Do you understand? Perhaps I'm asking too much, but imagine the danger he poses to the whole Villa now.}
{312}{}{I understand, Padre. Rely on me.}
{313}{}{Kill your kinsman? I'm definitely not going to do that. But it's worth talking to him.}