{100}{}{Here is the administrator.}
{101}{}{You see a middle-aged man. Judging by the way he speaks and moves, he is obsessed with order and neatness.}

#Dialog
{200}{}{Come in, wanderer. I have order and accounting here, so don't confuse anything for me here.}
{1200}{}{Come in, wanderer. I have order and accounting here, so don't confuse anything for me here.}
{201}{}{Goodbye.}
{202}{}{To me again? Great. How can I help you?}
{203}{}{I need to send a package to Phoenix.}
{204}{}{I need to send a package to Flagstaff.}
{205}{}{I need to send a package to Puerto.}

#Sending a parcel
{210}{}{That's why I'm here. The price of the parcel will be }
{211}{}{ bottlecaps. No more, no less. Put the things in that drawer over there by the wall. After payment, we will take them to their destination.}
{212}{}{Here is the fee, the parcel can be sent.}
{213}{}{Not now.}

{214}{}{No, no, that's not enough.}
{215}{}{Can we talk about something then?}
{216}{}{I'll be back when I earn it.}
{217}{}{Now I will make an inventory and enter the data in the log. This is required by the protocol. Here... Thank you for choosing our company. The package will be waiting in Phoenix at the same Sonora Express office.}
{218}{}{Great.}

{220}{}{Can I, as a member of the Brotherhood, count on special prices?}
{221}{}{Definitely, yes. We have special agreements with the Brotherhood.}
{222}{}{Wonderful. Just great.}
{223}{}{Ah, it's you again... But I just have to inform you that the discount on our services has now been canceled. And don't be indignant. This is the decision of the management, I have nothing to do with it.}
{224}{}{Yes, bad luck...}

#The first dialog
{230}{}{What can I do for you?}
{231}{}{Explain what this place is?}
{232}{}{The regional office of the courier company "Sonora Express". We are engaged in various types of delivery.}
{233}{}{And how big is your caravan network?}
{234}{}{It all depends on the specific order. Our central office is located in Phoenix. Paths diverge from it to the nearest settlements.}
{235}{}{I see. I'll keep that in mind for the future.}