{101}{}{You see a surviving scout of the Brotherhood of Steel.}
{102}{}{Someday the Brotherhood of Steel will return to Arizona. It's only a matter of time.}

{200}{}{(passing by, a stranger warily peers into your face) Hmm, I think I've seen you somewhere.}
{201}{}{Perhaps. You're not a local, are you?}
{202}{}{Yes. Just like you. Two strangers in an inhospitable town. It looks like a small world.}
{203}{}{That's right. But I have business here. Do you mind?}
{204}{}{No. Go ahead.}
{205}{}{For now.}
{206}{}{}
{207}{}{}
{208}{}{( nods in greeting)}
{1208}{}{Only after you.}
{209}{}{[Do the same]}
{1209}{}{You're so kind.}

{210}{}{Ah, I remembered. It was you I saw shortly before the explosion at the Steel Port. A curious coincidence, isn't it?}
{211}{}{An explosion? Hey, it's nothing to do with me.}
{212}{}{Is someone accusing you?}
{213}{}{No, sir. Nobody.}
{214}{}{Then why such nervousness? Don't worry, I still don't believe that a man like you could have gone through all the defenses on the ship and detonated the torpedoes. Not even all employees at the base had access there.}
{215}{}{Ugh, good. I already thought you suspected something. Uh, goodbye, sir. Have a good day.}
{216}{}{And if I say that the explosion is my handiwork?}
{217}{}{Now anyone can say that. I would never believe that some savage from the desert would have managed to get into a well-guarded hold and launch torpedoes. Where did you get such skills and knowledge, farmer?}
{1217}{}{Now anyone can say that. I would never believe that some savage from the desert would have managed to get into a well-guarded hold and launch torpedoes. Where did you get such skills and knowledge, redneck?}
{218}{}{Indeed, it sounds fantastic. Like in the old comics. I hope your suspicions are settled.}
{219}{}{Perhaps. But I'll be watching you out of the corner of my eye.}
{220}{}{There's no need for that. Goodbye.}
{221}{}{You should keep quiet after all these events. Your Brotherhood is now part of history. Accept it.}
{222}{}{It's true. However, Puerto Penasco is just an outpost away from the main base. Perhaps we will come back here again.}
{223}{}{But it won't be soon. And by this point, you will not be welcome here. Better think about your own fate, soldier.}
{224}{}{Coming here seemed like the smartest and safest idea. Okay, you won't hear from me again. Goodbye, stranger.}
{1224}{}{Coming here seemed like the smartest and safest idea. Okay, you won't hear from me again. Goodbye, stranger.}
{225}{}{Goodbye, scout of the Brotherhood of Steel.}
{226}{}{Come on, get out of here.}