{101}{}{You see a surviving Brotherhood of Steel scout.}
{102}{}{One day the Brotherhood will return to Arizona. It's only a matter of time.}

{200}{}{(while you walk by, the stranger looks warily at your face) Hm-m, I feel like I saw you before somewhere.}
{201}{}{Maybe you did. You aren't a local, are you?}
{202}{}{Yeah, just like you. Two outsiders in an unwelcoming town. It's a small world after all.}
{203}{}{That's right. But I've got stuff to do. You don't mind, do you?}
{204}{}{No. Go ahead.}
{205}{}{Bye.}
{206}{}{}
{207}{}{}
{208}{}{(nods)}
{1208}{}{Only after you.}
{209}{}{[Do the same]}
{1209}{}{You're so kind.}

{210}{}{Ah, I remember it now. I saw you not long before the explosion at Steel Port. Interesting coincidence, don't you think?}
{211}{}{Explosion? Hey, I had nothing to do with it.}
{212}{}{Was I suggesting so?}
{213}{}{No, sir.}
{214}{}{Why so nervous then? You think I'd really believe that someone like you could bypass all those security systems and blow up the torpedoes? Few people on the base even had access to that room.}
{215}{}{Great, great. I was worried that you suspected me or something. Uhh, goodbye, sir. Have a good day.}
{216}{}{What if I told you I really did all that?}
{217}{}{Anyone can say anything at this point. I'll never believe that some desert primitive could do something like that. Where'd you get the skills and knowledge, tiller?}
{1217}{}{Anyone can say anything at this point. I'll never believe that some desert primitive could do something like that. Where'd you get the skills and knowledge, village woman?}
{218}{}{It's fantasy. Like those old comics. Your curiocity satisfied yet?}
{219}{}{I suppose so. But I'll be watching you.}
{220}{}{No need for that. Bye.}
{221}{}{Your Brotherhood is history now. What happened, happened. There's no point in talking all about it.}
{222}{}{I suppose, in a way. But Puerto Penasco was just an outpost far away from the main base. It's possible that we'll be back here one day.}
{223}{}{That won't happen for quite a while. In the meantime, you won't be welcome here. You better think about your own life, soldier.}
{224}{}{Coming here seemed like the safest and smartest decision. I suppose it really wasn't. Farewell, stranger.}
{1224}{}{Coming here seemed like the safest and smartest decision. I suppose it really wasn't. Farewell, stranger.}
{225}{}{Farewell, Brotherhood scout.}
{226}{}{Yeah, get outta here.}