{100}{}{You see Gerardo.}
{101}{}{Here is one of the enslaved peasants of the Villa.}

#The first dialog
{200}{}{?! And you're here?! I thought the raiders didn't find you...}
{201}{}{No, Gerardo, we haven't found it. That's why I'm here to save you.}
{202}{}{Eh, amigo, you know how to encourage. But believe me, there's no way out of here. The very earth here is saturated with death! We will perish, amigo, and no one will even bury us.}
{203}{}{Where is my padre?}
{204}{}{Now he should be in an old hangar in the middle of the Burial Ground. All the survivors gather there. Go north, you won't miss.}
{205}{}{Good. See you later.}
{206}{}{What about you?}
{207}{}{The padre said to sit here and direct new people to the hangar. Don't worry, I'm relatively safe in these containers.}
{208}{}{I see. See you later, Gerardo.}

{210}{}{Thank heaven you're back!}
{1210}{}{Thank heaven you're back!}
{211}{}{Be.}
{212}{}{The barrier is disabled, and the robots will not touch us. Go back to the Villa.}
{213}{}{And did you manage it all? Truly, here is the real leader of the Villa! Although something has changed in you, amigo... Okay, I'll meet you at home! If, of course, we get there.}
{214}{}{Be.}
{215}{}{What now?}

{220}{}{Come with me, I need support in battle.}
{221}{}{What are you, amigo! You're calling me to my death! With our weapons against robots, we are powerless. It's better to sit back and wait until someone opens the gate.}
{222}{}{I don't recognize you, Gerardo. Remember, you were always a cool pepper in our village?}
{223}{}{Ya... I'm alive only because of your padre. The villa and this world are completely different. I'm not ready for this. Sorry. Even if I return to the Villa, I will not be able to live as before.}
{224}{}{Gerardo, now is not the time for despondency. Get up, your family needs you!}
{225}{}{Okay, amigo... But I won't take a step into that damn bunker! Let's get to the entrance, and then without me.}
{226}{}{Well, at least so.}
{227}{}{No... I'm needed here now. Padre Andres is counting on me.}
{228}{}{I see.}
{229}{}{We should split up. Stay where you are until I get back.}
{230}{}{Whatever you say, amigo...}
{231}{}{That's settled.}