{100}{}{You see Gerardo.}
{101}{}{You see one of Villa's enslaved peasants.}

#First dialogue
{200}{}{You're here too?! I thought the raiders didn't find you...}
{201}{}{They didn't. That's why I'm here, to save you all.}
{202}{}{Eh, amigo, you sure know how to give people hope. But believe me - there is no exit here. The land itself is filled with death! We will die here, amigo, and no one will even bury us.}
{203}{}{Where is my padre?}
{204}{}{He left to scout and hasn't come back. Looks like this land has consumed him as well. If you come to look for him, you'll die too!}
{205}{}{I have to. Wait here until I come back.}

{210}{}{Thank heavens, you're back!}
{1210}{}{Thank heavens, you're back!}
{211}{}{Take care.}
{212}{}{The barrier is disabled, and the robots won't hurt you anymore. Come back to Villa.}
{213}{}{You really did it? Truly, the real leader of Villa stands before me! Though I recognize you, amigo, something changed inside you... Alright, see you at home! Assuming, of course, we make it.}
{214}{}{Take care.}
{215}{}{What now?}

{220}{}{Come with me. I need all the support in battle I can get.}
{221}{}{No, amigo! You're inviting me to step into my grave! With these weapons, we're powerless against those robots. Better to sit tight and wait for someone else to open the gates.}
{222}{}{Looks like slavery broke you.}
{223}{}{You're right... I'm alive right now thanks only to your padre. But... We've seen and lived through things we never would have even imagined before. Even if we return to Villa, our life as it was before all this will never come back.}
{224}{}{Gerardo, now is not the time to be all glomy. Get on your feet, your family needs you!}
{225}{}{Alright, amigo... But I'm not taking a single step into that damn bunker! We'll walk to the exit, you'll go into it without me.}
{226}{}{At least it's something.}
{227}{}{No... I'll stay here... I'm sorry...}
{228}{}{I understand.}
{229}{}{We should split up. Stay here until I come back.}
{230}{}{As you wish, amigo...}
{231}{}{That's agreed upon.}