{100}{}{You see the Survivalist.}
{101}{}{You see a very thin and dirty man. His savage gaze speaks of especially noble intentions.}

#First dialogue
{200}{}{Hey, you! Come any closer - and you're DEAD, get it? Scram before I knock your brains out!}
{201}{}{Let's talk!}
{202}{}{Says the dead man!}

{203}{}{I ain't buying these tricks! Get lost!}
{204}{}{Listen, we can't survive alone. Let's combine our efforts, okay?}
{205}{}{Then I'll have to kill you to get the weapon.}
{206}{}{Fine, look, I'm going away, no problem.}

{207}{}{How do I know it's not a trick?}
{208}{}{Looks like you don't trust people much. But right now, we need each other.}

{209}{}{Dammit, I want to get out of here! Fine, let's combine our efforts. But I'll keep my distance.}
{210}{}{Well, at least it's something.}
{211}{}{Look at me closely. Are two ghouls enemies?}
{212}{}{We need each other. It's obvious.}
{213}{}{You speak nice words, smoothskin, but I'll be fine on my own.}

#Dialogue after befriending
{220}{}{What?}
{221}{}{Nothing.}

{230}{}{Tell me about yourself.}
{231}{}{I'm not telling you anything.}
{232}{}{Uhh, okay.}
{233}{}{At least tell me your name.}
{234}{}{Raul.}
{235}{}{Where are you from?}
{236}{}{Inferno, the city of ghouls to the west. But in my long life, I've been to many places in Mexico and California. Heard anything about Hermosillo? I was born there.}
{237}{}{A city in Mexico? Looks like you had a rich past.}
{238}{}{A hundred years of travel. And here I am now, at risk of dying in the sands. I expected a different death.}
{239}{}{A hundred years? How can you live that long?}
{240}{}{Look closely. I became like that after the atomic blasts. Those aren't burns, they're something else entirely. It extends my life. Dunno what would be better: to have died then and there, or right now.}
{241}{}{You're from the Pre-War era!}
{242}{}{Yes... The Old World was different. People lived among technology, and the cities amazed with their magnificence... But you know what? Nothing really changed. It's fighting for resources all over again, just on a smaller scale and with a different kind of technologies.}
{243}{}{Interesting perspective.}
{244}{}{Why did the tinsmiths send a... ghoul here?}
{245}{}{Because, having lived for so long, I know more than any smoothskin. Add radiation resistance, and you get the perfect candidate for breaching old bases. But the truth is, I have absolutely no idea how to disable the security systems here!}
{246}{}{I see.}

#Part of the player's party
{250}{}{Come with me.}
{251}{}{Just don't get into the thick of it. And keep in mind - I won't come with you into the bunker.}
{252}{}{We'll see about that...}
{253}{}{Wait here, I need to scout.}
{254}{}{Don't even think about trying to trick me.}
{255}{}{Of course...}

{260}{}{Tell me about this place.}
{261}{}{This area was devoted to the conservation of military equipment. The perimeter's surrounded by a force field and mine fields. Hostile robots everywhere. They're controlled by a computer system in an abandoned bunker below the earth.}
{262}{}{What can I expect to encounter in the bunker?}
{263}{}{Most likely robots and some kind of giant computer. I doubt any people are left in there. If you plan on going down there, prepare thoroughly.}