{100}{}{You see a slave.}
{101}{}{You see a forced laborer. He's completely exhausted from continuous work, but still on his feet.}

{102}{}{Looking for your friends? Looks like they have already been sent to the Forbidden Zone.}

{110}{}{Shoot me! I want the suffering to end...}
{111}{}{I'm not allowed to talk to outsiders.}
{112}{}{We're expendable to the tinsmiths.}
{113}{}{I used to be in a gang, but then I was captured and sent here.}
{114}{}{I miss the gang.}
{115}{}{While I was in the gang, I thought about my victims.}
{116}{}{Those tinsmiths are obsessed with old tech.}
{117}{}{Hide your computer, or they'll take it for themselves.}
{118}{}{The Forbidden Zone is certain doom.}
{119}{}{Got anything to eat?}