{100}{}{You see a Survivalist.}
{101}{}{Here is a dirty, emaciated man. His wild look expresses particularly good intentions.}

#The first dialog
{200}{}{Come any closer and you're dead. Get lost before I blow your brains out!}
{201}{}{Let's talk!}
{202}{}{I hear from the corpse!}

{203}{}{I'm not buying these tricks. Get lost!}
{204}{}{Look, we can't survive alone. Let's join forces, okay?}
{205}{}{Then I'll have to kill you to get the weapon.}
{206}{}{Okay, look, I'm leaving, no problem.}
{207}{}{How do I know it's not a trick?}
{208}{}{You don't seem to trust people. But right now we need each other.}

{209}{}{Damn it, I want to get out of here! Let's unite. But I'm not going to get ahead of you.}
{210}{}{Well, that's something.}
{211}{}{Look at me more closely. Are two intelligent mutants enemies of each other?}
{212}{}{We need each other. It's obvious.}
{213}{}{You sing beautifully, smooth-faced. But I'm not bad on my own.}
{1213}{}{You sing beautifully, smooth-faced. But I'm not bad on my own.}

#Dialogue after the introduction
{220}{}{What do I need?}
{221}{}{Nothing.}

{230}{}{Tell me about yourself.}
{231}{}{I won't tell you anything.}
{232}{}{Uh, okay.}
{233}{}{At least tell me your name.}
{234}{}{My name is Raoul.}
{235}{}{Where are you from, Raoul?}
{236}{}{I've traveled a lot. Mostly California and northern Mexico. Have you ever heard of Tijuana? I come from there.}
{237}{}{A city in Mexico? You must have had a rich past.}
{238}{}{A hundred years of travel. And here I am at the risk of disappearing into the sands. I was hoping for another demise.}
{239}{}{A hundred years? How could you live so long?}
{240}{}{I became like this after the nuclear explosions. It's not burns, it's something else. But it seems to prolong my life. I don't even know which is better: to die then or now.}
{241}{}{So you're a man from an ancient era!}
{242}{}{The old World was different. You would have been amazed by the technology of that era. But you know what? Nothing has really changed. People are still fighting over the remnants of resources. Just like in those days.}
{243}{}{An interesting point of view.}
{244}{}{Why the tinsmiths were sent here... a ghoul?}
{245}{}{Because having lived for so many years, I know a lot more than any smooth-skinned person. Add immunity to radiation - and here you have an ideal candidate for opening old bases. But the truth is that I have absolutely no idea how to disable the damn defense system of this damned burial ground!}
{246}{}{I see.}
{247}{}{Enough of these useless questions.}
{248}{}{Do you know about Inferno ghouls?}
{249}{}{You see, I... didn't fit into their collective. I still have enough sense not to go berserk. But these ghouls can't be fixed.}

#Party
{250}{}{Come with me.}
{251}{}{Just don't get into the middle of it. And keep in mind - I will not climb into the bunker.}
{252}{}{Let's see...}
{253}{}{Wait here, I'm scouting.}
{254}{}{Don't try to deceive me.}
{255}{}{Of course...}

{260}{}{Tell me about this place.}
{261}{}{An old burial ground for the preservation of military equipment. The perimeter is surrounded by a force barrier and minefields. There are hostile robots everywhere. They are controlled by a computer system in an abandoned bunker underground.}
{262}{}{What can you expect in a bunker?}
{263}{}{Most likely there are a bunch of damn robots and some big supercomputer. I doubt there are still people there. If you're going to go down, then prepare thoroughly.}