{100}{}{You see a slave.}
{101}{}{Here is one of the local slaves. It looks like he still hasn't figured out where he got to and what's going on at all.}

{110}{}{The tinkerers want us to disable the robots. But how the hell do you do that?!}
{111}{}{Damn tinkers! They grabbed me and threw me into this inferno.}
{112}{}{A lot of people died here. And we probably won't be the last.}
{113}{}{We are still alive thanks to Andres. But it won't be for long.}