{100}{}{You see a slave.}
{101}{}{Here is a forced laborer. He is exhausted from continuous labor, but still keeps on his feet.}

{102}{}{Are you looking for your friends? It seems they have already been sent to the Restricted Area.}

{110}{}{Please kill me! I don't want to endure this torment...}
{111}{}{I'm not allowed to talk to strangers.}
{112}{}{We are just expendable for tinsmiths.}
{113}{}{I used to be in a gang, but I was captured and sent here.}
{114}{}{I miss my gang.}
{115}{}{While I was in the gang, I never thought about my victims.}
{116}{}{These tinsmiths are obsessed with ancient technology.}
{117}{}{Hide your computer, otherwise the tinkerers will take it by force.}
{118}{}{The Forbidden Zone is certain death.}
{119}{}{Is there anything to eat?}