{100}{}{You see the Second-Of-Three.}
{101}{}{You see one of the tinsmiths. He is diligently cleaning his laser pistol.}

{200}{}{(You watch the tinker stubbornly cleaning his laser gun, not paying attention to you.)}
{201}{}{Have you been doing this for a long time?}
{202}{}{(Raises his head to look at you, his gaze expresses complete indifference.) Laser technology is my specialty. I've been doing this all my life.}
{203}{}{So tinsmiths prefer a narrow specialization?}
{204}{}{This is the most effective way to maintain productivity.}
{205}{}{And if one of the specialists does not become?}
{206}{}{There is a duplicate for each of us. If they dismantle me, there will always be a replacement.}
{207}{}{I see.}
{208}{}{Well, I won't bother you.}
{209}{}{It's better not to distract him...}

{210}{}{What do you need, wasteland man?}
{211}{}{What do you need?}
{212}{}{Nothing, yet.}

{220}{}{I also want to learn the art of laser technology.}
{221}{}{We do not share knowledge and skills with the first comer. Earn our trust first.}
{222}{}{Give me time to think.}
{223}{}{What about barter?}
{224}{}{Perhaps. I need electronic parts that are so scarce in our area. Bring 5 units, and then I will make concessions for you.}
{225}{}{Even Master Hard entrusts me with some tasks.}
{226}{}{It's true. This honor falls only to a few.}
{227}{}{Many people in this city trust me.}
{228}{}{Perhaps. But "many" does not mean consensus. However, I can make concessions for a valuable gift - bring a couple of pieces of electronic parts, this will be enough for my loyalty.}
{229}{}{Here are 2 units of electronic parts.}
{230}{}{Here are 5 units of electronic parts.}
{231}{}{We could exchange our skills.}
{232}{}{This... acceptable.}
{233}{}{This... unacceptable. We have nothing to learn from the hillbillies.}

{240}{}{Very good. Now I see that I can do business with you.}
{241}{}{So how about a little introductory course?}
{242}{}{Do you know the basics of quantum mechanics? Then let's not waste time...}
{243}{}{[Next]}
{244}{}{The tinker turned out to be a demanding teacher. But he taught you a lot.}