{100}{}{You see a tinsmith.}
{101}{}{You see a person in dirty working overalls. Their balded head is shrouded in wires and sensors.}

{110}{}{This will need to be dismantled.}
{111}{}{These components can be sold to the Phoenix commoners.}
{112}{}{This bucket of bolts should have ended up in the junkyard a long time ago.}
{113}{}{This junk is good for nothing.}
{114}{}{I feel for this heap of scrap.}
{115}{}{And to think that this pile of rubbish was once a technological masterpiece.}
{116}{}{I can't wait to see the technology from the Forbidden Zone.}
{117}{}{New plasma converter needed.}
{118}{}{One day, planes will begin to fly over our heads once more.}
{119}{}{Hear the blissful sigh of the piston mechanism?}

{120}{}{What do the Steel Gods say?}
{121}{}{The Gods of Steel have promised us new blueprints in exchange for energy cells.}
{122}{}{These components must be transported to Steel Port immediately.}
{123}{}{The Gods of Steel wish to exalt our people.}
{124}{}{}
{125}{}{Even the Steel Gods are powerless before atomic fission.}
{126}{}{We would have never allowed what happened at Steel Port.}
{127}{}{We overestimated the wisdom of the Gods of Steel.}
{128}{}{}
{129}{}{}

{130}{}{When will the new shipment of uranium ore arrive?}
{131}{}{By producing energy cells, we are rebuilding civilization.}
{132}{}{We should restrict the usage of batteries.}
{133}{}{How much uranium ore do we have?}
{134}{}{}
{135}{}{Energy conservation will be necessary until the Flagstaff mine begins operating again.}
{136}{}{Until the Flagstaff mine becomes operational again, we can't make any energy cells.}
{137}{}{The caravaneers say that the Flagstaff mine has completely ceased operation.}
{138}{}{How much uranium ore do we have left?}
{139}{}{Without the Flagstaff mine, we won't be able to make batteries.}

{140}{}{What do they want in the Temple of Fire?}
{141}{}{The fire-worshippers completely fail to grasp the essense of technology.}
{142}{}{The ambassador from the church just makes work harder.}
{143}{}{Tell the ambassador from the church to take his pathetic orders back.}
{144}{}{If the church wants this, they better find the blueprints for it first.}

{145}{}{Regardless of how much we laughed at the fire-worshippers, it turned out we needed them in the end.}
{146}{}{Without the Temple of Fire, acquiring nuclear material will become much harder.}
{147}{}{The value of caps has dropped considerably after the explosion in the Temple.}
{148}{}{Without the church, we need new partners.}
{149}{}{This is what happens when technology gets in the wrong hands.}