{100}{}{You see the tinker.}
{101}{}{In front of you is a man in dirty overalls. His bald head is wrapped in wires and sensors.}

{110}{}{We'll have to take it apart.}
{111}{}{These parts can be sold to commoners in Phoenix.}
{112}{}{It's time for this bucket with nuts to go to the landfill.}
{113}{}{This junk is good for nothing.}
{114}{}{I am full of compassion for this pile of scrap metal.}
{115}{}{But this pile of junk was a masterpiece of technology.}
{116}{}{I can't wait to see the technology from the Forbidden Zone.}
{117}{}{We need a new plasma converter.}
{118}{}{The time will come when planes will appear above us again.}
{119}{}{Do you hear that blissful sigh of the piston mechanism?}

{120}{}{What do the Steel Gods say?}
{121}{}{The gods of Steel promised us new blueprints in exchange for power cells.}
{122}{}{These parts need to be urgently sent to the Steel Port.}
{123}{}{The steel gods want to exalt our people.}
{124}{}{}
{125}{}{Even the gods have become powerless before atomic fission.}
{126}{}{We would never have allowed what happened in the Steel Port.}
{127}{}{The gods of Steel were not as smart as we thought.}
{128}{}{}
{129}{}{}

{130}{}{When will the new batch of uranium ore arrive?}
{131}{}{By making energy cells, we are reviving civilization.}
{132}{}{We should limit the distribution of batteries.}
{133}{}{How much uranium ore do we have?}
{134}{}{}
{135}{}{We'll have to save energy until Flagstaff starts the mine again.}
{136}{}{Until Flagstaff restores the mine, we will not be able to make power cells.}
{137}{}{The caravaneers say the Flagstaff mine is inactive.}
{138}{}{How little uranium ore do we have left?}
{139}{}{Without the Flagstaff mine, we won't be able to make batteries.}

{140}{}{What do they want in the Cathedral of Fire?}
{141}{}{These fire worshippers do not understand the essence of technology at all.}
{142}{}{The more the ambassador of the Cathedral is here, the more difficult it is to work.}
{143}{}{Tell the ambassador of the Cathedral to pick up his worthless orders.}
{144}{}{If the Cathedral wants to do this, let them find the drawings first.}

{145}{}{No matter how much we ridiculed the fire worshippers, we needed them.}
{146}{}{Without the Cathedral of Fire, it will become much harder to obtain nuclear material.}
{147}{}{After the explosion in the Cathedral, the value of the caps plummeted.}
{148}{}{We need new partners. The Cathedral of Fire is no longer in business.}
{149}{}{That's what happens when technology falls into the wrong hands.}