{100}{}{You see Two of Three.}
{101}{}{You see one of the tinsmiths. He is diligently cleaning his laser pistol.}

{200}{}{(You observe the tinsmith diligently cleaning his laser pistol, paying no attention to you.)}
{201}{}{Have you been doing this for a long time?}
{202}{}{(Looks up at you with complete indifference.) Laser technologies are my specialty. I've been doing this for my entire life.}
{203}{}{So the tinsmiths prefer narrow specialization?}
{204}{}{It is the most effective way of maintaining productivity.}
{205}{}{What if one of the specialists dies?}
{206}{}{We each have a duplicate. If I am dismantled, there is always a replacement.}
{207}{}{I see.}
{208}{}{Well, I better not disturb you any longer.}
{209}{}{Better not to disturb him...}

{210}{}{What do you want, wasteland person?}
{211}{}{What do you want?}
{212}{}{Nothing. Goodbye.}

{220}{}{I want to become knowledgeable in the art of laser technologies as well.}
{221}{}{We do not share our skills and knowledge with everyone we see. Earn our trust first.}
{222}{}{Let me think about it.}
{223}{}{How about barter?}
{224}{}{Perhaps. I need electronic components which are scarce in this region. Bring me 5 units, and I will agree to share.}
{225}{}{Even Master Khard gives me some assignments.}
{226}{}{True. Only single digits of individuals receive such an honor.}
{227}{}{Many people trust me here.}
{228}{}{Perhaps. But "many" does not equal consensus. However, I can share this knowledge for a price. Bring me 2 units of electronic components. This will be enough to ensure my loyalty.}
{229}{}{Here are 2 units of electronic components.}
{230}{}{Here are 5 units of electronic components.}
{231}{}{We could exchange our skills.}
{232}{}{Your proposal is... acceptable.}
{233}{}{Your proposal is... unacceptable. There is nothing we can learn from primitives.}

{240}{}{Very good. I see now that I can conduct business with you.}
{241}{}{So, how about a little introductory course?}
{242}{}{Are you familiar with the basics of quantum mechanics? Then let's not waste time...}
{243}{}{[Continue]}
{244}{}{The tinsmith has turned out to be a demanding teacher. But he really did teach you much.}