{100}{}{You see an eyebot.}
{101}{}{You see a messenger robot.}
{102}{}{*Sh-h-h*}
{103}{}{You listen in. The only answer you receive is the hiss of static coming from the loudspeaker.}

{110}{}{I think we understood each other.}

{200}{}{(you are chased down by an eyebot that has a message from ZAX) I thank you for your help. As you can see, I have already terminated the aforementioned illegal settlement. I will release you and your tribesmen on a condition - you will never return to this area.}
{201}{}{Sounds pretty acceptable to me.}
{202}{}{I am counting on your loyalty. Let me assist your next course of action. The evidence in my possession shows that the tinsmiths were accountable to an influential organization known as the Brotherhood of Steel. It is the same organization that is responsible for the spread of slavery throughout the Sonora region. I suggest you find a way to terminate the main Brotherhood base to minimize further risks to Villa.}
{203}{}{You mean the Brotherhood won't stop, even after their defeat at Two Sun? Then where do I find this base?}
{204}{}{Head to the west, to the old port on the shores of the Gulf of California. The safest route passes through the settlement Casa Nueva. I share your interest in liquidating this threat, but I cannot provide any further assistance. My capabilities are far too localized.}
{205}{}{Alright, ZAX, thanks for the help.}
{206}{}{I'm not a robot. I'll figure it out without your help.}