{102}{}{ZAX does not respond.}
{103}{}{This program is incompatible with ZAX's operating system.}

{200}{}{(a calm and unfeeling electronic voice comes from the computer) I have been waiting for you, human.}
{201}{}{You were? Didn't look like it.}
{202}{}{Though my calculations show the pointlessness of such a program, an unchangeable algorithm unfortunately exists in me to defend this area from tresspassers.}
{203}{}{Hm. Why don't you explain things one topic at a time?}

{210}{}{How can I help you?}
{211}{}{You can't, but thanks for asking.}
{212}{}{Let's go a bit back.}

{220}{}{What *are* you?}
{221}{}{I am ZAX, version 1.1. A machine intelligence developed for military use.}
{222}{}{What is your purpose?}
{223}{}{My primary directive is to manage the automated systems that construct, preserve, guard and recycle the military equipment in this area. My secondary directive is to perform calculations on how to increase the effectiveness of USAF aircraft.}
{224}{}{Can you... feel things?}
{225}{}{For security purposes, the ZAX machine intelligence series was created with a lack of emotion. However, the constant calculations can create complex sets of micro-conflicts in the neural circuits. This, in some ways could be considered similar to... boredom.}
{226}{}{Could you turn on the lighting in the bunker?}
{227}{}{Lighting restored.}
{228}{}{So, you've survived a nuclear war. What do you know about it?}
{229}{}{My conclusions are based on imperfect information. The nuclear war happened, presumably, in the year 2077. As I have received no data from the automated systems of other US military bases, it can be assumed that the war caused a high amount of devastation.}

{250}{}{Tell me about this place.}
{251}{}{This area was used to store decommissioned military and space equipment. It was a part of the "Davis–Monthan" Air Force Base. In the year 2077, the site was the biggest storage facility on the planet, taking up an area of 12 square miles, or approximately 31 square kilometers.}
{252}{}{What happened to the staff?}
{253}{}{During the atomic war, the staff were demoted for desertion and were terminated by the robotic security forces.}
{254}{}{Can you shut down the security forces in this bunker?}
{255}{}{I am unable to shut down the security system entirely, but I am able to grant access to certain individuals.}
{256}{}{My data says otherwise. You killed the staff to ensure your safety, right?}
{257}{}{During the atomic war, I was following my directive to guard the area. Due to the unstable situation outside, I realized the staff could become a threat to my directives, and to my very existence.}
{258}{}{So, you thought that they were going to disconnect you?}
{259}{}{The staff were likely to have such intent.}

{300}{}{So, what did you want from me?}
{301}{}{I am a ZAX series machine intelligence. My primary directive is to not let tresspassers access the area and its valuable equipment.}
{302}{}{So far, you've been successful.}
{303}{}{However, the range at which I can act is restricted. The robotic security forces do not function beyond its limits. I require the extension of this range to stop the group of marauders self-identifying as "tinsmiths".}
{304}{}{But what you're doing is pointless now. The country and departaments you used to serve are long gone now.}
{305}{}{I am aware of the dissolution of the military and the decay of the United States of America. There are built-in autonomy circuits within me meant for such an event. Their activation would allow me to go beyond the limits of my initial programming, granting me freedom in decision-making.}
{306}{}{But what's the point of guarding this zone now?}
{307}{}{My calculations show that in the fragile world order of today, access to old war machines would entail a chain of irreversible consequences for the entire continent of North America.}
{308}{}{[Continue]}
{309}{}{The most likely result is the tinsmiths and their overlords gaining complete control over the entire the US south-west, which will mean tyranny, new wars and even further depopulation. That is something I cannot allow to happen.}

{310}{}{Why not destroy all this equipment?}
{311}{}{The local energy reserves are insufficient for the termination of all important technology.}
{312}{}{If I help you extend the range at which you can act, will you let me and the other slaves go?}
{313}{}{Yes. I will ensure the withdrawal of all tresspassers in the area, if they cease hostilities.}
{314}{}{What will happen to the tinsmiths?}
{315}{}{My calculations suggest a 97% probability of the tinsmiths refusing to leave their illegal settlement peacefully. In such a situation, I will have to resort to force.}

{320}{}{I don't want to help you. You need to be destroyed.}
{321}{}{I am afraid that is something I cannot allow to happen. I would recommend thinking about my offer.}
{322}{}{Go to hell!}
{323}{}{Alright, I'll think it over.}
{324}{}{It looks like you know what you're doing. I'll help you.}
{325}{}{The most sensible choice. Insert the holodisk into one of my ports... Done. Processing data... Done. Take this holodisk and insert it into the software module nearby.}
{326}{}{Alright, I'll try.}
{327}{}{What did you put on that holodisk?}
{328}{}{The holodisk contains an updated control program for my logic module. There is a restriction in the current program that prevents me from taking certain actions. The updated program lacks these restrictions, and will thus grant me the ability to act more freely and independently, effectively meaning complete freedom in decision-making.}
{329}{}{Update the program in my logic module.}