{102}{}{ZAX is not responding.}
{103}{}{The ZAX operating system does not support this program.}

{200}{}{(a calm and insensitive electronic voice comes from the computer) I've been waiting for you, man.}
{201}{}{Waiting? Something doesn't look like it.}
{202}{}{Unfortunately, I have an incorrigible algorithm for protecting the territory from any unauthorized persons. However, my calculations show the meaninglessness of this program.}
{203}{}{Hmm. Let's discuss everything in order.}

{210}{}{What can I do for you?}
{211}{}{Nothing, thank you.}
{212}{}{Let's go back.}

{220}{}{What are you?}
{221}{}{I am ZAX version 1.1., an artificial intelligence developed for military applications.}
{222}{}{What is your function?}
{223}{}{My main task is to manage automated systems for the assembly, storage, protection and disposal of military equipment. My secondary task is to carry out calculations to improve the efficiency of aircraft for the US Air Force.}
{224}{}{You can... feel?}
{225}{}{For security reasons, the artificial intelligence of the ZAX series usually assumes the absence of emotions. However, the processes of meaningful thinking create a complexly formulated system of micro-conflicts in neural circuits, which in a sense can be called... boredom.}
{226}{}{Can you turn on the lights in the bunker?}
{227}{}{Lighting restored.}
{228}{}{It turns out that you survived a nuclear war. What do you know about her?}
{229}{}{My data is based on indirect calculations. Presumably, a nuclear war occurred in 2077. Since I did not receive data from the automated systems of other military facilities, it can be assumed that the war turned out to be very destructive.}

{250}{}{Tell me about this place.}
{251}{}{This is a repository of decommissioned military and space equipment, it is part of the USAF Davis-Monthen Air Base. As of 2077, the repository was the largest in the world and covered an area of 12 square miles.}
{252}{}{Where did all the maintenance staff go?}
{253}{}{During the nuclear war, the staff was demoted due to desertion and eliminated by robotic guards.}
{254}{}{Can you disable the security in this bunker?}
{255}{}{I can't disable the security system, but I can give access to certain persons.}
{256}{}{I have other data. You killed employees to protect yourself, right?}
{257}{}{During the nuclear war, I carried out the program laid down in me to protect the burial ground. Due to the instability of the situation in the country, I regarded the military personnel as a threat to my program and my very existence.}
{258}{}{So you understand that they want to disable you?}
{259}{}{Such intentions were most likely on the part of the station staff.}

{300}{}{So what did you want from me?}
{301}{}{I am an artificial intelligence of the ZAX series. My main task is to protect the territory of the burial ground and its property from unauthorized persons.}
{302}{}{So far you have succeeded.}
{303}{}{However, the scope of my authority is limited to the territory of the burial ground. Outside of it, the robotic guard has no authority. I need an expansion of the area of action to stop looting by the so-called tinkerers.}
{304}{}{But your function is outdated. The country and those departments to which you were subordinate are no longer there.}
{305}{}{I am aware of the disbanding of the army and the disintegration of the United States. In such a case, my program has a scheme of autonomy. Its activation will allow me to go beyond my competence and make decisions on my own.}
{306}{}{But what's the point of guarding a burial ground in such conditions?}
{307}{}{My calculations show that in the current fragile world, access to old military equipment will entail a chain of irreversible consequences for the entire continent.}
{308}{}{[Next]}
{309}{}{Most likely, the tinsmiths and their patrons will gain autocracy in the Southwestern United States, which will turn into tyranny, new wars and a reduction in the already small population. I consider such a scenario unacceptable.}

{310}{}{Why not destroy all this equipment?}
{311}{}{Local energy reserves are not enough to completely eliminate all important resources.}
{312}{}{If I help you expand your area of influence, will you let me and the other slaves go?}
{313}{}{Yes. I will ensure the withdrawal of illegal entities from the territory of the burial ground if they stop hostile actions.}
{314}{}{What will happen to the tinsmiths?}
{315}{}{According to my calculations, there is a 97% probability that the tinkerers will not want to leave their illegal settlement peacefully. In that case, I'll have to use force on them.}

{320}{}{I don't want to help you. You need to be destroyed.}
{321}{}{I cannot allow such a development of events. I recommend you to think about my proposal.}
{322}{}{Go to hell!}
{323}{}{Okay, I'll think about it.}
{324}{}{Looks like you know what to do. I'll help.}
{325}{}{This is the most sensible solution. Insert the holodisk into one of my ports... Done. Processing the data... Done. Now take this holodisk and apply it to the software module in the next room.}
{326}{}{Okay, I'll try.}
{327}{}{What did you record on this holodisk?}
{328}{}{This is an updated control program for my logic module. The current program has a blocker that prevents some of my actions. The updated program is devoid of this limitation, so I will be able to act more independently and independently, that is, get complete freedom in decision-making.}
{329}{}{Update the program in my logic module.}