{100}{}{You see the robot eye.}
{101}{}{In front of you is a translator robot.}
{102}{}{*Psh-sh-sh*}
{103}{}{In response, you only get a static hiss from the loudspeaker.}

{110}{}{I think we understand each other.}

{200}{}{(a robo-eye is catching up with you, transmitting a message from ZAX) Thank you for your help. As you can see, I have already liquidated this illegal settlement. But I will release you and your tribesmen on one condition - you will never return to these lands again.}
{201}{}{Sounds acceptable.}
{202}{}{I'm counting on your loyalty. Let me give you a recommendation. According to my information, the tinkerers were accountable to an influential organization called the Brotherhood of Steel. It is this organization that is responsible for the development of slavery in Sonora. You should find a way to eliminate the Brotherhood's main base to reduce further risks to the Villa.}
{203}{}{Are you saying the Brotherhood of Steel won't stop even after the defeat in Two-Sun? Then where can I find this database?}
{204}{}{Head west to the old port on the Gulf of California. The safest way is through the town of Casa Nueva. Like you, I am interested in eliminating this threat, but do not count on further cooperation. My capabilities are too local.}
{205}{}{Okay, ZAX, thanks for the help.}
{206}{}{I'm not your robot, I'll figure it out without your instructions.}