{110}{}{This body should be examined more closely.}
{111}{}{No sense in disturbing the dead now.}
{112}{}{This action not possible to perform in combat.}

{200}{}{This man died of gunshot wound during the raid. It looks like he was one of the attackers, though his appearance doesn't suggest it.}
{201}{}{[Continue]}
{202}{}{In his pocket, you find a sketch of the Old City's streets, with lines showing a safe route. It can be assumed that's where the bandits' camp is located.}
{203}{}{[Head to the Old City]}
{204}{}{[Leave the corpse alone]}
