{110}{}{This body should be examined more closely.}
{111}{}{There's no point in disturbing the dead now.}
{112}{}{This cannot be done during a fight.}

{200}{}{This man died from a gunshot wound during the raid. It looks like he was one of the attackers, although you can't tell from his appearance.}
{201}{}{[Next]}
{202}{}{In his pocket you find a cursory sketch of the layout of the Old City with an indication of a safe route. It can be assumed that a bandit camp is located in this place.}
{203}{}{[Go to the Old Town]}
{204}{}{[Leave the corpse alone]}