{100}{}{You see Khard's computer.}
{101}{}{You see Master Khard's personal computer. It is in excellent condition.}

#Dialogue
{200}{}{Enter command.}
{201}{}{Complete session.}
{202}{}{Back.}

{210}{}{Slave delivery reports.}
{211}{}{(It looks like the tinsmiths love numbers and record-keeping. Detailed data is collected on the slaves here - their origins, occupations, causes of death. Half of the slaves were sent to the Forbidden Zone. Their fate is unknown.)}
{212}{}{Search for slaves from Villa.}
{213}{}{(You find two entries. Carlos works in the hangar, while your padre has been sent into the Forbidden Zone. You'll have to head there yourself to find him.)}
{214}{}{Search for slaves from Phoenix.}
{215}{}{(The main source of slaves for the tinsmiths is the Church of the Holy Fire in Phoenix. You enter the coordinates into your Pip-Boy.)}
{216}{}{Trade reports.}
{217}{}{(The tinsmiths actively trade with several settlements, where they exchange technologies and offer repair services. The main contracts are: the Church of the Holy Fire in Phoenix (slaves, clothing, food), Flagstaff colony (slaves, uranium), Casa Nueva (food), Casa Grande (clean water).)}
{218}{}{Instructions from headquarters.}
{219}{}{(The tinsmith leader is receiving direct instructions from the Brotherhood of Steel, which resides in Puerto Penasco. The Brotherhood doesn't interfere with the internal affairs of the locals, but governs the production of some items and foreign policy. In particular, the Brotherhood requires the tinsmiths to fulfill important requests from the Church of the Holy Fire in Phoenix. The last of such contracts was the construction of components for a nuclear bomb.)}

{220}{}{Dossier on Cody.}
{221}{}{(Cody was among the children the tinsmiths acquired from other settlements and re-educated. Cody's parents gave him away as payment for the repair of the Casa Grande water pump. But for the child's smoother assimilation into the Collective, his official story was somewhat "simplified".)}

{230}{}{Component delivery report from... Garage City?}
{231}{}{(As it turns out, the tinsmiths received from the Followers of the Holy Fire the exact component you gave to the caravaneers in Garage City. It's been directed here to be mass produced.)}
{232}{}{Dossier on Carlos.}
{233}{}{(Surprisingly, despite their isolationism, the tinsmiths have fully accepted Carlos, for his talents and interest in technology.)}
{234}{}{Let's fix the dossier a bit. Here... here... and here. Hopefully that'll bring Carlos down a notch.}
{235}{}{(Your sabotage is complete. The tinsmiths are bound to have suspicions regarding this desert novice)}
{236}{}{Great, this will make Carlos leave Two Sun.}
