{100}{}{This is Hard's computer.}
{101}{}{In front of you is the personal computer of the Hard Master. It is in excellent condition.}

#Dialog
{200}{}{Enter the command.}
{201}{}{End session.}
{202}{}{Back.}

{210}{}{Slave supply reports.}
{211}{}{(Tinsmiths seem to love numbers and accounting. It contains detailed statistics about slaves - their origin, employment, causes of death. Half of the slaves were sent to the Forbidden Zone, their fate is unknown.)}
{212}{}{Information about slaves originally from the Villa.}
{213}{}{(You have discovered information about two slaves. Carlos is working in the hangar, and your padre has been sent to the Restricted Area. I'll have to go there on my own to find it.)}
{214}{}{Information about slaves from Phoenix.}
{215}{}{(The main source of slaves for tinsmiths is the Sacred Fire Church in Phoenix. You enter the coordinates in your Pip-Boy.)}
{216}{}{Reports on trading operations.}
{217}{}{(Tinsmiths actively trade with several settlements, where they exchange technology items and provide repair services. Main contracts: Sacred Fire Church in Phoenix (slaves, clothing, food), Flagstaff Colony (slaves, uranium), Casa Nueva (food), Casa Grande (clean water).)}
{218}{}{Instructions of the General Staff.}
{219}{}{(The leader of the Tinsmiths receives direct instructions from the Brotherhood of Steel from Puerto Penasco. The brotherhood does not interfere in the internal affairs of local residents, but regulates some production and foreign policy. In particular, the Brotherhood obliges to fulfill important requests from the Church of the Sacred Fire in Phoenix. The last such contract was parts for a nuclear bomb.)}

{220}{}{Cody's file.}
{221}{}{(Cody was among the children that the tinkerers acquired in the outer settlements and re-educated under their charter. The parents gave Cody as payment for fixing the water station in Casa Grande. However, for better assimilation of the child within the Collective, his official history has been slightly "simplified".)}

{230}{}{Getting the part from... Garage City?}
{231}{}{(As it turned out, the tinsmiths received from the Followers of Fire the very detail that you gave to the caravaneers in Garage City. She was sent here for mass reproduction.)}
{232}{}{The dossier on Carlos.}
{233}{}{(Oddly enough, for all their closeness, the tinsmiths loved and accepted Carlos for his talents and interests in technology.)}
{234}{}{Well, let's fix the dossier here a little... and then... I hope this will knock Carlos down.}
{235}{}{(You committed a diversion. The tinkerers will surely have suspicions about this newcomer from the wasteland)}
{236}{}{Great, this will make Carlos leave Two-Sun.}