{101}{}{You see a bunch of electronics and other parts. Someone is trying to collect something from this.}
{110}{}{Lots of electronics parts. It seems that they are trying to collect some kind of weapon from this pile.}
{111}{}{This homemade pulse weapon is assembled from various parts found on the territory of the Burial Ground.}
{112}{}{Weapons are collected! Now robots will become more obedient...}