{100}{}{You see a Test Character.}
{101}{}{This is a character for cruel experiments. You can have a good time with him.}
{110}{}{Okay, okay, cool it.}

#Replicas floating
{120}{}{A beautiful day to die.}
{121}{}{Isn't this world beautiful?}
{122}{}{}
{123}{}{}
{124}{}{}
{125}{}{}
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

#Dialog
{200}{}{Glory to the Brotherhood of Steel!}
{201}{}{I hate the Brotherhood. And I hate you too.}
{202}{}{Uh, yes, of course.}
{203}{}{I'm your commander now. I order you to join the squad.}
{204}{}{What are your instructions, sir?}
{205}{}{At ease, soldier.}

{206}{}{Intelligence 2}
{207}{}{Intelligence 4}
{208}{}{Intelligence 5}
{209}{}{Intelligence 6}
{210}{}{Intelligence 8}

{211}{}{Mine is yours not to understand, friend.}
{212}{}{Do you take me for a fool? Here I am for you!}
{213}{}{Stay here while I think about the answer.}
{214}{}{The brotherhood? For the first time, I hear.}
{215}{}{Tell me about the Brotherhood.}