{101}{}{You see a homemade workbench.}
{102}{}{You have made 20 signal cartridges from old festive pyrotechnics.}
{110}{}{This workbench contains components for assembling nuclear batteries.}
{111}{}{All components are used up. There's nothing else to do here.}
{112}{}{You have assembled a micro-core battery for 8 charges.}
{113}{}{You have assembled a micro-core battery for 16 charges.}
{114}{}{You have assembled a micro-core battery for 20 charges.}