{100}{}{You see an emergency terminal.}
{101}{}{You see a computer with the inscription: "Use in an emergency."}
{102}{}{ZAX has seized control of the system, now the initiation of an emergency protocol is impossible.}
{103}{}{The terminal is not functioning.}
{104}{}{The first port is connected. Enter the second access card.}
{105}{}{The second port is connected.}

#Dialog
{200}{}{Enter command.}
{201}{}{End session.}
{202}{}{Back.}

{210}{}{Initiate an emergency protocol.}
{211}{}{Attention! The emergency protocol will trigger a series of pulse explosions with the aim of destroying all electronic equipment within the bunker. This procedure is irreversible and is permissible only in an emergency.}
{212}{}{Who would doubt it?}
{213}{}{OK.}
{214}{}{Are you sure you want to run an emergency protocol?}
{215}{}{No, cancel the explosion.}
{216}{}{Yes, initiate an emergency explosion.}
{217}{}{Please, for security reasons, disconnect this terminal and take away the access cards.}
{218}{}{I'm launching an emergency protocol...}
{219}{}{Come on, do it, you damn piece of hardware!}