{100}{}{You see a kill-switch activation terminal.}
{101}{}{You see a computer terminal. The following words are written on it: "Use to activate ZAX kill-switch".}
{102}{}{ZAX has assumed control of this system. Initiating the kill-switch is no longer possible.}
{103}{}{The terminal isn't functional.}
{104}{}{First keycard inserted. Insert the second access key.}
{105}{}{Second keycard inserted.}

#Dialogue
{200}{}{Enter command.}
{201}{}{Complete session.}
{202}{}{Go back.}

{210}{}{Activate the kill-switch.}
{211}{}{The kill-switch will release a series of electromagnetic pulses that will destroy all electronic equipment in the bunker. Warning! This procedure cannot be cancelled once activated. Perform only in the event of confirmed machine intelligence misalignment.}
{212}{}{Who would have thought?}
{213}{}{Okay.}
{214}{}{Are you sure you want to activate the kill-switch?}
{215}{}{No. Abort activation.}
{216}{}{Yes. Activate.}
{217}{}{In the interests of safety, please disable this terminal and take the access cards with you.}
{218}{}{Activating kill-switch...}
{219}{}{Come on, finish it!}