{100}{}{This is Granny Adonsia.}
{101}{}{Here is a woman you know well - your grandmother. She smokes a pipe and squints with a sharp look.}
{102}{}{Goodbye, Grandma. I hope no one finds out the real cause of your death.}
{103}{}{What kind of demon sent you against us? Banish him! Come to your senses!}

#The first dialog
{210}{}{(takes a drag and then lets out puffs of black smoke while looking at you reproachfully) Here you are. You were lucky to be away from home at a bad time. And maybe it's for the best.}
{211}{}{Granny Adonsia, we don't have time to chat right now. Tell me what's going on.}
{212}{}{Stop grumbling, old woman. Tell me what happened.}
{213}{}{What happened? What's going on?}
{214}{}{Huhm? You start talking like an adult. This is encouraging.}
{215}{}{And you still won't calm down your bad temper. Although it may help you in the future.}
{216}{}{Worried, eh? Not the best quality when you have to make a decision. But when it comes down to it, you'll have to do it.}
{217}{}{So what happened?}

{218}{}{While you were gone, strangers came. Evil people. Ten people, and all with weapons. Our men couldn't handle them.}
{219}{}{Go on.}
{220}{}{Outsiders took all able-bodied. Only the elderly and children were left. Now the Villa is in your hands, you are in charge here. And you'll have to do something about it.}
{221}{}{What can I do alone?}
{222}{}{What do you think? Bring back our men and women. At least their parents. They, too, fell into the clutches of these extranos.}
{223}{}{It won't be easy...}
{224}{}{(nods) Right. And I'll tell you what, although your padre won't like it terribly. Downstairs, in the cellars under the town hall, there is a secret room with family heirlooms. Only a few people know about it. Go down, find and take everything that will be useful to you on the road. And do it right now, time is precious.}
{225}{}{Thanks, Grandma. Now every little thing will help me.}
{226}{}{And that's it? Damn, you're no help. Okay, I'll look in Dad's cellar.}
{227}{}{OK, I'll try to find these old things.}
{228}{}{Be careful. There are rats in the cellars, and it's as dark as a fat-horn's ass. Here, take a lighter, even though I'll miss it. And when you find the secret things, go straight to the square and find Jose there. He will tell me more.}
{229}{}{Before I go down, I have to ask.}
{1229}{}{Before I go down, I have to ask.}
{230}{}{I'll leave immediately.}

{231}{}{Why are you still here?}
{232}{}{Before I leave, I have to ask.}
{1232}{}{Before I leave, I have to ask.}
{233}{}{Really, I have to go.}
{234}{}{You did a good job getting our people back. Well done.}
{1234}{}{You did a good job getting our people back. Well done.}
{235}{}{I have some questions.}
{236}{}{I have to go.}
{237}{}{Well, it's my duty. I will do my best.}
{238}{}{Bring back our men and women. Your parents also fell into the clutches of the extranos.}
{239}{}{I think you're crazy. What can I do against an entire armed squad?}

#Questions
{240}{}{Find Jose in the square, he will tell me more.}
{241}{}{How did the stranger’s assault happen?}
{242}{}{Has someone died?}
{243}{}{What's wrong with my parents?}
{244}{}{This secret room in the cellars raises questions.}
{245}{}{What should I do when I get those ancient things?}
{246}{}{Okay, I'm leaving.}
{247}{}{Another question.}
{248}{}{Your parents are also among the forced laborers. Whether you want it or not, you'll have to save them. Blood for blood and shoulder to shoulder - so our ancestors taught us. If you stay here, you will condemn the community to extinction.}

{250}{}{They all piled up at once at the most unexpected moment. All able-bodied people were tied up and taken away to the east in the morning. Jose knows more, ask him.}
{251}{}{There was a whole massacre at the town hall. Several were killed, others were maimed. If your nerves are weak, it's better not to go there.}
{252}{}{Your padre and madre were also taken away. So hurry up before anything worse happens to them.}
{253}{}{Well of course. Only the old people knew about the Founder's secret room. There are ancient things and knowledge stored there, which everyone in the Villa is not supposed to know about. Padre would have taken you to this room anyway, when he thought it was necessary.}
{254}{}{Obviously stupid. First find Jose and ask about the raid. And then go after the raiders. Then you will have to decide for yourself.}
{1254}{}{Obviously stupid. First find Jose and ask about the raid. And then go after the raiders. Then you will have to decide for yourself.}
{255}{}{But the old people have always taught us that you can't use ancient things. Did even the Founder break this taboo?}
{256}{}{Don't jump to conclusions. Taboos were invented to protect you from the dangers of old things. But not all of them are really dangerous, and some are even useful.}
{257}{}{Perhaps if we knew more about ancient things, we would be ready for the attack of the raiders.}
{258}{}{(inhales thoughtfully and lets out clouds of black smoke) The founder didn't think so. He said that our business is to grow crops. This is the only way we were able to survive in difficult times. And we had a good life without old technologies. Would life be better with them? I don't know. Nobody knows.}
{259}{}{Granny Adonsia, so you knew the Founder?}
{260}{}{Oh, it was so long ago that I don't even remember his face. I remember the mustache, but I don't have a face. But this is a thing of the past, don't worry your head. You have more important questions.}

{261}{}{Grandma, did you know that the Founder was a traitor to his sanctuary?}
{262}{}{That's how. Did the padre show you his notes? Well, Felix's burden was heavy and his conscience came to him in nightmares at night. It's not for you to judge him. He gave life to this place, albeit at the cost of many deaths. So appreciate it.}
{263}{}{Don't fill your head with idle thoughts. That's not what we need to do right now.}

#After the plot ends
{300}{}{You shouldn't have come back to the Villa after everything you've done.}
{1300}{}{You shouldn't have come back to the Villa after everything you've done.}
{301}{}{Oh, come on. It's like you're all so righteous here.}
{302}{}{The wastelands opened my eyes to the world. You are living wrong.}
{303}{}{It's not up to you to decide how we live! The villa survived thanks to the traditions and foundations that we chose. And no Wastelands can dictate to us another way. But you...}
{304}{}{?}
{305}{}{You're just a hypocrite who bottlecaps up his stupidity with the outside world! Go away and don't come back. I curse you, }
{306}{}{!}
{307}{}{Take it easy, Grandma.}
{308}{}{You are the hypocrites here. I won't take another step into this shithole.}
{309}{}{The Founder of the Villa himself warned us to stick together. But it's too late now. This infection cannot be stopped as long as the memory of you is alive.}
{310}{}{By the way, what happened to the Founder?}

{320}{}{I'm proud of you, }
{321}{}{.}
{322}{}{Really?}
{323}{}{It's nice to hear that.}
{324}{}{You have come a long way, but you have remained faithful to your home and your family. Now I can retire knowing that the Villa is in safe hands.}
{1324}{}{You've come a long way, but you've stayed true to your home and your family. Now I can retire knowing that the Villa is in safe hands.}
{325}{}{How could you doubt me?}
{326}{}{Thanks for the kind words, Grandma.}
{327}{}{The old people know a little more than the rest. We knew about the outer cities, and about the technologies of the Old World. And about the fact that only a common misfortune can unite people. And when people are doing well, there is no reason to restrain their selfishness.}
{328}{}{Not without it.}
{329}{}{Again these moralizing ...}
{330}{}{Then conflicts and family breakdown begin. Perhaps the story of the raid was very useful - it reminded us that we should stick together. The founder of the Villa understood this well and prescribed it in his address to the descendants.}
{331}{}{By the way, what happened to him?}

{340}{}{So, }
{341}{}{, you're here. Just like at the beginning of the journey. But something has changed in you, hasn't it?}
{342}{}{Oh, come on. As if you're all so righteous here.}
{343}{}{The wastelands have changed us all. It's okay to change.}
{344}{}{Until now, the Villa has survived thanks to the traditions and foundations that we have chosen. And no Wastelands can dictate to us another way. You should listen more to the opinion of your family.}
{345}{}{I'm not going to argue with you. My decisions have already been made.}
{346}{}{Maybe you're right. So what?}
{347}{}{The Founder of the Villa himself warned us to stick together. But now it's too late - a raid on the Villa could rally the community. Your intervention can create discord.}
{348}{}{By the way, what happened to the Founder? For some reason, I do not know the whole story.}

{350}{}{He died prematurely from hard work in the fields and construction sites. We did not bury it in the ground according to tradition. Instead, they were taken to a cave and surrounded with a brick sarcophagus. This crypt is still well preserved.}
{351}{}{I've never been there. Can you show me this crypt?}
{1351}{}{I've never been there. Can you show me this crypt?}
{352}{}{Curious. I think it's time for me to go. Bye, Grandma.}
{353}{}{Good. Perhaps a visit to his crypt will stir up your callous soul.}
{354}{}{Good. I think you deserve to visit this shrine.}
{355}{}{Good. Perhaps a visit to the crypt will spiritualize you.}
{356}{}{Let's go. I can leave right now.}
{357}{}{It's not up to that now. I'll go there when I get more free time.}

{360}{}{Close the door behind you if you're going to leave.}
{361}{}{I'm already leaving. Bye, Grandma.}
{362}{}{I want to see the Founder's crypt. Can you take me there?}