{100}{}{Here is a raider.}
{101}{}{You see an outsider. By the look of it, he got pretty badly.}
{102}{}{You have received }
{103}{}{ experience for a peaceful solution to the conflict.}
{104}{}{ }
{105}{}{The raider leaves the Villa peacefully.}
{106}{}{My first murder... Strange feelings.}

#Floating replicas
{110}{}{*Heavy breathing*}
{111}{}{*Cough*}
{112}{}{Hr-r-r...}
{113}{}{Damn it...}
{114}{}{Why did I get involved in this?}
{115}{}{And why the hell am I doing this?}
{116}{}{How to get out of here?}
{117}{}{I won't give up so easily.}
{118}{}{When will they come to the rescue?}
{119}{}{And that's it? So will I end my life?}

{120}{}{Think of me whatever you want. I don't care.}
{121}{}{I'm not coming back, you don't have to tremble with fear}
{122}{}{The conversation is over. Don't piss me off.}

#Start of the dialog
{200}{}{(Here is an unknown stranger in tattered dirty clothes; it looks like he is injured and exhausted) Hey, you... *Cough-cough* Say goodbye to life, redneck!}
{201}{}{Hey, take it easy, I don't want to hurt you.}
{202}{}{Hostility? Looks like I'm going to have to defend myself.}
{203}{}{Shut up... (heavy breath) I've been immured in this basement for twenty-four hours. Do you think I'm just going to let it go? *Cough-cough* You'll all pay for it. I'll tear down your Villa!}
{204}{}{You leave me no choice. I'll have to calm you down by force.}
{205}{}{Go to hell!}
{206}{}{Hey, hey, wait...}
{207}{}{Let's start the fun...}
{208}{}{Listen, there's no point in us fighting...}
{209}{}{Look, there's no point in us fighting. Calm down. The worst is over.}
{210}{}{You don't look well. I can cure you.}
{211}{}{You're not going to fight in this state, are you? I can help if you calm down.}
{212}{}{I don't recommend it. Traps are all around.}
{213}{}{There are traps all around. You can't get out without me. And I know the way out.}
{214}{}{Will you attack a defenseless woman? Are you completely crazy?}
{215}{}{ (looks around, coming to his senses) Your truth... Okay, you'll be my guide. But don't try to deceive me. Make an extra move and you're dead.}
{216}{}{Good-good... Can you start by telling me what happened?}

{220}{}{Is this some kind of trick? I'm fucking dying here. Hurry up and take me upstairs.}
{221}{}{Okay, go away. Behind that shelf there is a secret exit to the cellars. You can go up from any of them.}
{222}{}{And you really think I'm going to let you go after all I've heard? You're too dangerous for the Villa.}
{223}{}{A secret exit? Cleverly devised... Hell, I'd like to kill you, but I'm not in the best shape for that. We must conserve our strength. So live for now.}
{224}{}{Uh, okay. Let's do without goodbye hugs.}
{225}{}{Go already. Stop wasting my time.}
{226}{}{Yes, you can take it. (throws you an old key taken by the raiders from your father) There's nothing of value there anyway.}
{227}{}{Hmm...}

# About myself
{250}{}{Who are you anyway?}
{251}{}{None of your damn business.}
{252}{}{Really. It was a pointless question.}
{253}{}{Sorry. I'm only asking because this is the first time I'm talking to an outsider.}
{254}{}{I'm just wondering how you got to this life.}
{255}{}{I'm just a mercenary. Do you understand? No home, no family, no name.}
{256}{}{Oh, I'm sorry. Must be hard to grow up without relatives and home?}
{257}{}{Are you all so wild out there in the wastelands? Here is our Villa - one big family.}
{258}{}{I don't know... I do not know what it means to live in a big pack like you. I probably can't do that. I won't be able to share and trust someone like myself... Damn, you better shut up before I knock your teeth out.}
{259}{}{Why are you so angry?}
{260}{}{Wow, it makes you angry, doesn't it?}
{261}{}{You wouldn't understand. I was found in a dumpster in a big city. The usual story. Where I come from, no one appreciates people. The population is too large, and there is nothing to do. One will disappear and no one will notice.}
{262}{}{If everything is so bad outside the Villa, then you can be understood. At least a little.}
{263}{}{I had to fight for my place. And you just ran away from the problem.}
{264}{}{I don't need your pity. Better take me outside.}
{265}{}{Wait. Answer one more question first.}
{266}{}{You think it's that easy, right? Of course you're here, not there. You'd better shut up and take me outside.}
{267}{}{Wait. Answer one more question.}

{270}{}{Why did you get involved in this business with a raid?}
{271}{}{Because I need to earn money for food. Do you understand? There was no work, and a detachment was being recruited in the camp. I just wanted to earn some light caps on this raid and then get out of here. So what? I'm here. In the fucking basement.}
{272}{}{Was there really no other job? It's so sad.}
{273}{}{Or maybe you just didn't want to work?}
{274}{}{This is not work, this is hard labor. You're being used for some leftovers. I've had enough! I also want to live beautifully.}
{275}{}{What did you do before?}
{276}{}{No one would belittle a valuable employee. So you're not like that.}
{277}{}{Nobody cares about you. Survive as you want. I've worked in a variety of jobs, from a handyman in a bar to a slave raider. I have to earn my food somehow.}
{278}{}{I see you don't like the question. Do you want to talk about it?}
{279}{}{I don't want to.}
{280}{}{Well, your right.}
{281}{}{In my opinion, this is an ordinary excuse for his insolvency.}
{282}{}{Then shove your opinion deep up your ass.}
{283}{}{Hey, that was rude.}
{284}{}{You're putting yourself in the frame of a bad guy to fit the environment, right?}
{285}{}{Damn, there's something in that. Maybe I'm just talking to the wrong people? Or maybe we should sit and think... No, I just need to shut you up. Don't forget who's in charge here.}
{286}{}{Of course, you're the boss here now.}

# About the raid
{290}{}{Tell me what happened here?}
{291}{}{Are you talking about the collapse? (spits) An idiotic story.}
{292}{}{How did you end up in this trap?}
{293}{}{Of course, only a fool would get into such a mess.}
{294}{}{Then you can tell it some other time.}
{295}{}{We made one of your guys show us the basement. They thought there was something valuable stored here. I went down first, but I fell into a trap. There was an explosion from behind, the ceiling collapsed. I lost consciousness. That's all I remember.}
{296}{}{Hmm, apparently it was one of my padre's traps. He arranged it just in case the Villa was seized by outsiders.}
{297}{}{Did you think it was that simple? My padre has provided for the possibility of seizing the Villa.}
{298}{}{It seems we underestimated the cunning of your people. How many more tricks and secrets are hidden in this dungeon, eh?}
{299}{}{Did you try to get out or call for help?}
{300}{}{No one responded. These bitches just left me. I myself could not get out of the basement - the stairs were destroyed, and the exit from the cellar was locked. So... If you're here, then there's a way out somewhere, right?}
{301}{}{Uh, yes, but first I need to figure something out.}
{302}{}{Did you find anything interesting in these cellars?}
{303}{}{Nothing worth risking your own skin for. Although it's strange to see an ancient technology in such a hole. Why do you need it?}
{304}{}{What technology are you talking about?}
{305}{}{technology? You're delusional. The technology of the Ancients is banned in the Villa.}
{306}{}{Don't you know? Long-forgotten technology in the next room. So old and decrepit that they can't even be disassembled for scrap. I wouldn't be surprised if you secretly worship these pieces of iron.}
{307}{}{Nonsense. Why does the padre hide forbidden items from us? He swears himself when something is brought from the wasteland.}
{308}{}{You say it's just garbage? You must have confused something.}
{309}{}{How should I know? You're the one who lives here. But if your leader hides what he forbids, I would stop trusting him.}
{310}{}{Surely he has an explicable reason. But that's not the main thing right now.}
{311}{}{Don't you dare speak ill of my father. Understand?}
{312}{}{I don't know. My specialty is not to understand hardware, but to hit them in the jaw.}
{313}{}{Surely the padre has an explicable reason. But that's not the main thing right now.}
{314}{}{Well yes. By the way - mine too.}
{315}{}{Nothing else can be expected from the barbarian. Okay, enough about that.}

{320}{}{What do you know about the events upstairs? Before I fell here.}
{321}{}{A little bit. I found only the beginning of the raid.}
{322}{}{Why did you attack us at all? Did you want to profit from the harvest?}
{323}{}{Damn barbarians. Are you only capable of robberies, or are you at least of some use?}
{324}{}{Stupid peasant, you... (mocks you, but then clears his throat bitterly) You don't even have the slightest idea about the outside world, do you? Your tribesmen were taken to work in the mine. Although I don't think you know what it is.}
{1324}{}{Stupid peasant woman, you... (mocks you, but then coughs bitterly) You don't even have the slightest idea about the outside world, do you? Your tribesmen were taken to work in the mine. Although I don't think you know what it is.}
{325}{}{[Listen]}
{326}{}{So, you better shut up, otherwise...}
{327}{}{They will be put on collars and forced to work underground. Those who refuse to obey will be severely punished. Face it, these people won't come back to the Villa anymore. And some will not even see the light of the sun.}
{328}{}{I don't understand how you could do such a thing.}
{329}{}{It's a pity I wasn't here during the capture. You would all go for fertilizer.}
{330}{}{Open your eyes, savage. One rifle is enough for three to bring you to your knees. Where do you go against a whole gang of armed mercenaries? (spits) You have lived in your paradise gardens for too long and already have no idea what a cruel world outside of them is.}
{1330}{}{Open your eyes, savage. One rifle is enough for three to bring you to your knees. Where do you go against a whole gang of armed mercenaries? (spits) You have lived in your gardens of Paradise for too long and already have no idea what a cruel world outside of them is.}
{331}{}{It looks like you don't like this place.}
{332}{}{Don't you dare talk about the Villa like that. This place is beautiful.}
{333}{}{You have no idea how I had to survive. I lived on the street, fought for food, robbed passers-by and even killed. Like everyone else in the wastelands... Everyone except you.}
{334}{}{[Next]}
{335}{}{You are the only ones who eat and drink as much as they want. You are clean, plump, and look at people from the Wasteland as if they were garbage. You disgust me. All your blooming Villa is like a lump in my throat for me.}
{336}{}{Yeah, I can't imagine what you've been through. And I don't want to imagine.}
{337}{}{And that's an excuse for you? What a son of a bitch.}