{102}{}{Don't push!}

#Retaliatory remarks - reputation >5
{110}{}{You'll protect us, won't you?}
{111}{}{Kill these raiders! Kill them all!}
{112}{}{I don't want the raiders to come back.}
{113}{}{All strangers are stupid.}
{114}{}{I want to go to Mom!}
#Retaliatory remarks - reputation <-5
{115}{}{You scare me more than those raiders.}
{116}{}{Get away from me! You're like a raider.}
{117}{}{I was told not to talk to you.}
{118}{}{All strangers are stupid. Well, that's what adults say.}
{119}{}{I want to go to mom!}
#Retaliatory remarks - reputation from -5 to 5
{120}{}{And if the aliens come back, will someone protect us?}
{121}{}{It was scary! I'm still shaking...}
{122}{}{I'm afraid the raiders will come again.}
{123}{}{Why are strangers so stupid?}
{124}{}{I want my mom!}
{125}{}{Do you want to play?}