{100}{}{This is Chris.}
{101}{}{Here is one of the residents of the Villa. His gaze betrays a fair amount of puzzlement.}

{110}{}{Chris's backpack was filled with provisions.}
{111}{}{Thank you, that's enough... I hope.}
{112}{}{(}
{113}{}{ of }
{114}{}{) Chris's backpack is full of provisions, but it's not enough for the trip.}
{115}{}{Thank you. At least I won't starve to death.}

{200}{}{? It's you... Not surprisingly, I suspected that you, the new hero of the Villa, would be sent to search. Now they see you as a leader. I probably don't want to lose my special status, right?}
{201}{}{So why did you run away from the community?}
{202}{}{They want to execute me. You know. Why these unnecessary questions?}
{203}{}{I need to know for sure.}
{204}{}{You'd better stay here. Wait for my return.}

{210}{}{If this is my last day, I'd rather spend it with you.}
{211}{}{If this is my last day, then I would rather meet him at the bottom of the well than next to you.}
{212}{}{Don't go anywhere, I'll be back soon.}
{213}{}{I think I missed something in this story. Tell me more.}
{214}{}{Okay. There's no hurry anyway.}
{215}{}{Tell me more.}

{220}{}{Why are they mad at you?}
{221}{}{Like you, I avoided the raiders. But only because he hid from them in the cellars. Now the residents cannot forgive this and consider me a traitor. And traitors in the Villa have always been disliked.}
{222}{}{What kind of execution are they preparing for you?}
{223}{}{I don't know for sure, but someone whispered about stoning. They used to do that. And now, after all this business with the raid, they can come up with something worse.}
{224}{}{What do you know about this place?}
{225}{}{Ancient ruins of some settlement. Our ancestors took bricks from here to build their houses. The rest is destroyed by time. As you can see, there is almost nothing left...}
{226}{}{[Next]}
{227}{}{Funny. The villa exists thanks to these ruins. Now they keep me alive. But no one knows anything about their past and about the people who lived here. Perhaps in other cities with a different way of life, not like in a Villa, I will find my place.}
{228}{}{What are you going to do?}
{229}{}{I don't know. I can't hide for long, and there's nowhere much to run. I've heard about the rangers and the scavengers from the neighboring town. But to go there, you need provisions. (bitter smile) Don't follow her to the Villa.}
{230}{}{If I get you provisions, you can leave these places. But you'll never come back.}
{231}{}{I know! Maybe that's what I've always wanted, but I was afraid to admit it. Among our people, most did not even try to learn anything about the outside world. They have lived their way for decades and are ready to throw stones for any change in it... I want to be free, amigo. Give me a chance!}
{232}{}{Okay, I'll get you some provisions for the trip. Wait here.}
{233}{}{No. My reputation is important to me. And besides, you deserve to be punished. Pack up, we're going back to the community.}
{234}{}{First of all, I need to know the details of this story.}
{1234}{}{First of all, I need to know the details of this story.}
{235}{}{To give Chris supplies, use them on the character.}
{236}{}{Now you have enough provisions to escape to the nearest town.}
{237}{}{I hope so. Let's get some fresh air. I want to take one last look around before I leave.}
{238}{}{Let's go.}
{239}{}{Escort Chris to the square at the Villa.}

#GG takes Chris away from the location:
{240}{}{Can we talk outside?}
{241}{}{Let's go.}
{242}{}{Don't worry about me, I'll find my way.}
{243}{}{Whatever you say.}
{244}{}{Escort Chris to the edge of the ruins, and then return to the Villa.}
{245}{}{Come on, do what you have to do!}
{1245}{}{Come on, do what you have to do!}
{246}{}{Better shut up.}
{247}{}{Look, I'm not in the mood for this decision either.}