{100}{}{You see Chris.}
{101}{}{You see one of the residents of the Villa. His gaze betrays a fair amount of puzzlement.}

{200}{}{(looks away) Oh... I thought those raiders took you, too. It's good that at least someone stayed.}
{201}{}{Bye.}
{202}{}{Tell me about the raid.}
{203}{}{Why didn't the raiders touch you?}
{204}{}{These raiders appeared unexpectedly. Surrounded from all sides and drove our people into a trap. Some hid in their homes, but they were taken out anyway.}
{205}{}{They decided they didn't need me. Probably too thin.}
{206}{}{Something doesn't fit in your words, Chris.}
{207}{}{(looks away) I just... I just hid in the cellar... and sat there until it was over.}
{208}{}{And watched from there how your tribesmen were beaten and tied up? You bastard!}
{209}{}{Chris, you're a coward.}
{210}{}{That's how. Well, it's hard to blame you for that.}
{211}{}{And what was I supposed to do?! Go straight to their hands?! I don't know how to fight... I've never been able to... I could only watch.}
{212}{}{More importantly, what will our people do to you when they return to the Villa? In the meantime, I'll leave you.}
{213}{}{Yes, I know! But what could I do? I don't know how to fight, I didn't have a weapon, It was me against a dozen strangers! It's easy for you to say - you weren't here. And now I have to live with it...}
{214}{}{Do you really think so? Yes, of course, you weren't here either... But this is a small consolation. I left my people anyway. And now I have to live with it.}
{215}{}{Go on.}
{216}{}{The hardest part was for those who hid in the town hall - there was a real massacre.}