{100}{}{You see a peasant.}
{101}{}{In front of you is one of your fellow tribesmen.}
{102}{}{Someday I'll push you too.}
{103}{}{ }

#Floating replicas
{110}{}{Someone has to drive the Jackals out of the desert.}
{111}{}{I would like to see how these Jackals were chased across the desert.}
{112}{}{Have you heard the news about Jackals? You can't trust anyone now. Even the Rangers...}

{113}{}{I don't hope for a good relationship with the scavengers after what they did.}
{114}{}{Now the bastards from Garage City will know how to help our abusers.}
{115}{}{I don't think I'll ever forgive the scavengers.}

{116}{}{We could use some help from the Rangers.}
{117}{}{Damn, even Rangers can't stand up for themselves.}
{118}{}{Rangers are tough guys. But you will have to share with them.}

{119}{}{Our enemies from Flagstaff will get their way someday!}
{120}{}{They say things are really bad in Flagstaff. Let's sing about it, amigos!}
{121}{}{Our freedom will come to an end if Flagstaff develops.}

{122}{}{Caravans bring bad news from the southeast.}
{123}{}{Something is happening in the southeast. I hope it won't affect us.}
{124}{}{It looks like a war has started in the southeast.}

{125}{}{I would rather senor Andres returned from slavery.}
{126}{}{Our new leader lacks the maturity to manage the community.}
{127}{}{Our leader should not be contradicted.}

{128}{}{Someone has to save senora Maria from slavery.}
{129}{}{After the death of senora Maria, it will be difficult.}
{130}{}{Thank heaven, Maria has also returned to the Villa!}

{131}{}{Glory to our savior!}
{132}{}{Senor Andres brought up a real hero.}
{133}{}{The viceroy of Andres shows great promise.}

{134}{}{Hush! That bastard of senor Andres is up to something.}
{135}{}Senor Andres raised a real devil.}
{136}{}{In bad times, we need a strong leader.}

{1131}{}{Glory to our savior!}
{1132}{}{Senor Andres brought up a real heroine.}
{1133}{}{The viceroy of Andres shows great promise.}

{1134}{}{Hush! That bastard of senor Andres is up to something.}
{1135}{}{Senor Andres raised a she-devil.}
{1136}{}{In bad times, we need a strong leader.}

#Retaliatory remarks
{200}{}{You are always welcome here.}
{201}{}{Thank you for saving us, hero.}
{202}{}{You are an example for all of us.}

{210}{}{I have a lot to do, sorry.}
{211}{}{We are rebuilding the village, and what are you doing?}
{212}{}{Why don't you stop bothering us and get busy?}

{220}{}{Don't you dare scare the kids with that thing.}
{221}{}{Don't come near me!}
{222}{}{You'll scare anyone in this thing.}
{223}{}{Scare our enemies with this piece of iron, not us.}
{224}{}{How dare you walk around the Villa in this armor?}
{225}{}{Will this armor scare away our enemies?}
{226}{}{Aren't you hot in this thing?}
{227}{}{Better help us clean up the plantations.}
{228}{}{If this armor is so powerful, then use it to repair houses.}
{229}{}{Watch yourself, you walking barrel! People live here.}