{100}{}{You see a peasant.}
{101}{}{You see a resident of the Villa.}
{102}{}{It looks like someone is waiting for you at the exit!}
{103}{}{Let's make a deal - this conversation didn't happen.}
{104}{}{I'll be damned! You... WHAT ARE you?}
{105}{}{It's good to see you.}

{200}{}{How are the searches going?}
{201}{}{Great. So far.}
{202}{}{Well... to be honest, I'm not in the spirit of the Council's decision either. But this story will serve as an example to others. It will be better for everyone.}
{203}{}{I really hope so.}
{204}{}{Go to hell with your excuses!}

{210}{}{(on the way out of the building, you unexpectedly encounter an old acquaintance; it looks like he was deliberately lying in wait for you) Well, well. We had a lot of one traitor, and now you! What the hell are you doing? Do you want to break the whole way of our life because of one cute and failed coward?}
{211}{}{The community made a mistake. Killing your own is the way to destroy the way of life.}

{212}{}{Maybe so... I don't know! We all changed after that raid. Before him, we lived in peace and no one was going to throw stones at a neighbor. Only in the old days, when the Villa was being rebuilt...}
{213}{}{[Next]}
{214}{}{Here the ancestors took the material for building houses. And they say that life was tight then, a neighbor could steal from a neighbor. We survived that horror and became a big close-knit family. Everything changed after the raid.}
{215}{}{Then you must understand that this is not the way out. Let Chris go.}
{216}{}{I can't! He... he should be an example... so the community decided...}
{217}{}{You are afraid. You are afraid that the Villa will change.}
{218}{}{Yes! Cris... forgive me.}
{219}{}{Ugh, it seems we have solved this problem.}
{220}{}{Then do what you have to do. I won't bother you.}
{1220}{}{Then do what you have to do. I won't bother you.}
{221}{}{I don't care what the community decided. Chris will be free.}
{222}{}{The community will not forgive you for such an act. (spits on your feet and leaves)}
{223}{}{Come on, move back to the herd, you fool...}
{224}{}{Just let Chris go.}

{230}{}{You got it all wrong - I'm taking him to execution.}
{231}{}{Really? And why does he have a backpack full of provisions?}
{232}{}{These are my things. Let him bear it as punishment.}
{233}{}{Hmm... Yes, he should be an example. It's nothing personal, Chris. So the community decided. Let's go to the execution.}
{234}{}{[Return to the square]}

{240}{}{Yes, think what you want. I know what I'm doing.}
{241}{}{Hmm. People talk all sorts of things about you. And as it turned out, not in vain.}
{242}{}{Hmm. People talk all sorts of things about you. But no one expected this!}
{243}{}{Damn it, I wouldn't want to be an outcast in my homeland. Okay, take him to the execution, I won't bother you.}
{244}{}{I don't care what the community thinks. Chris will be free.}