{100}{}{Here is a peasant.}
{101}{}{You see one of the residents of the Villa. He carefully inspects the settlement.}

{110}{}{Hey, has anyone seen Chris?}
{111}{}{If someone has seen Chris, then let them say right now.}
{112}{}{If Chris doesn't come back on his own, it will be worse for him.}
{113}{}{Hey, you! Will you tell me where Chris is hiding?}
{114}{}{This little snake got away with too much.}
{115}{}{I knew Chris would give up.}

{200}{}{Greetings to our savior! How are things going?}
{1200}{}{Greetings to our savior! How are things going?}
{201}{}{Great. Bye.}
{202}{}{Wait! Maybe I'm asking a lot, but we need your help again.}
{203}{}{What kind?}
{204}{}{It's about your old friend Chris. Did you know that this little snake was holed up in the cellars during the raid? While we were fighting with the raiders and suffering humiliation, this traitor was not even going to help us!}
{205}{}{So he's on the run?}
{206}{}{It looks like it. Probably hiding like last time. Find him and bring him back. He must answer to the Community Council. This is important.}
{207}{}{I'm not interested in that. But if I meet him, I will inform him that they are looking for him.}
{208}{}{I'll look for him.}

{210}{}{Have you seen Chris? It would be better for him to come back and answer to the Council.}
{211}{}{Haven't met yet.}
{212}{}{Where do you think he might be hiding?}
{213}{}{He hardly escaped into the wasteland - there is not enough spirit, and there is nowhere to run. We examined the cellars, but we didn't find him there. It remains to think that someone is hiding it, but who is it? Friends, neighbors and his little brother won't confess.}
{214}{}{See you later.}

{220}{}{Chris is dead. His body lies in the Ruins where he was hiding.}
{221}{}{What a shame. It would be more useful to see the execution. But it will be a lesson for everyone else anyway. Thank you for your efforts, the community appreciates it.}
{222}{}{You're welcome.}
{223}{}{With your help, Chris has returned to the Villa and will soon be punished for his betrayal. Thank you, the community appreciates your efforts.}
{224}{}{You're welcome.}
{225}{}{By the way, these forbidden items were found with him. Decide what to do with them, we don't need alien technology. (hands you some old cartridges of different calibers)}
{226}{}{Great, I'm them... I'm disposing of it.}
{227}{}{Obviously, there's no point in waiting for Chris. Right?}
{228}{}{Exactly. He has left the valley and will not return here again.}
{229}{}{So be it. Its very existence can undermine the order in the community. The further away he is from here, the better.}
{230}{}{So my job is done. Have a good stay.}