{100}{}{You see a peasant.}
{101}{}{In front of you is one of your tribesmen who has successfully returned from Flagstaff.}
{102}{}{Hey, after the exploits, did your ego kick in? Don't let go of your hands!}
{103}{}{Don't come any closer, you piece of iron! I can take care of myself!}

{110}{}{What a mess?!}
{111}{}{It will be hard to fix it without parts.}
{112}{}{If only all sorts of heroic personalities would not look at me.}
{113}{}{It seems that someone was digging in my cellar.}
{114}{}{Now I will keep the cellar locked.}
{115}{}{We'll have to change the door.}
{116}{}{The damned raiders, they will answer for everything!}
{117}{}{If I managed the Villa, this wouldn't have happened at all!}
{118}{}{Where was the Council of Elders looking?}
{119}{}{We will never trust strangers again.}

{200}{}{Hi. Thanks for saving my ass. And now, if you'll excuse me, I'm going to save my house.}
{201}{}{Goodbye.}
{202}{}{Sorry, I dug in your cellar and took some supplies.}
{1202}{}{Sorry, I dug in your cellar and took some supplies.}
{203}{}{So it's you. It's not very good-natured of you to dig into other people's things. Don't you find it?}
{204}{}{It was necessary for your salvation.}
{205}{}{Don't rub my ears with silage! No matter what kind of hero you are and no matter what feats you have done, you need to ask permission for other people's things. Do you understand that?}
{1205}{}{Don't rub my ears with silage! No matter what kind of heroine you are and no matter what feats you have done, you need to ask permission for other people's things. Do you understand that?}
{206}{}{Fuck you.}
{207}{}{I see.}
{208}{}{I still have a lot to do. Can you help me with something?}
{209}{}{There are some things preserved in my cellar. Come down and see what you can use out of all this. The descent to the cellar is covered with boxes in the pantry.}
{210}{}{Thank you.}