{100}{}{You see the babysitter.}
{101}{}{You see Anita, one of your many aunts. It looks like she's under a lot of stress.}
{102}{}{Just dig some more, and I'll respond in kind!}
{103}{}{You have added a new task to your Pip-Boy.}
{104}{}{Get out of here, you piece of iron! Don't touch the kids!}

{200}{}{Nice to see you.}
{201}{}{First the raiders, and now you.}
{202}{}{Nothing, goodbye.}
{203}{}{I see. Goodbye.}
{204}{}{}
{205}{}{}
{206}{}{? Oh, how lucky you are. The raiders took half of the village.}
{207}{}{Don't worry, I'll do everything to get them back.}
{208}{}{I know.}
{209}{}{I can see without you, you'd better say something useful.}

{210}{}{Tell me about the raid.}
{211}{}{I don't want to remember this horror! Strangers swooped in a crowd, beat our husbands, broke down doors and windows... I couldn't even run away from fear! And the children still can't come to their senses.}
{212}{}{How are the kids?}
{213}{}{They are still in shock. I have to take care of the children, although I could use some support myself... This is terrible!}
{214}{}{Is there anything I can do to help?}
{215}{}{Yes, probably... Eden was so scared after losing his parents that he ran away and is now hiding somewhere. I can't leave the other kids to look for him. Look for him, okay?}
{216}{}{Where should I start looking?}
{217}{}{Yes, he could be anywhere!}
{218}{}{And yet he has a favorite secret place?}
{219}{}{Well, I remember he set up his "base" in shacks on plantations.}
{220}{}{I'll see what I can do.}
{221}{}{Tell me about Eden again.}
{222}{}{Eden was so scared after losing his parents that he ran away and is now hiding somewhere. I'm afraid he might get into even more trouble.}
{223}{}{Bad news - Eden has passed away.}
{224}{}{(faints) Ah... I guessed it was too late... it's all my fault... if I could have stopped him in time...}
{225}{}{We did what we could.}
{226}{}{As you can see, Eden is back.}
{227}{}{He would have died without your help! Now it's my turn to take care of him. (with tears in his eyes) Thank you so much!}
{228}{}{Come on, we're the same blood.}
{229}{}{I would prefer a piece of juicy meat, but I will have to settle for just one "thank you".}
{1229}{}{I would prefer a piece of juicy meat, but I will have to settle for just one "thank you".}
{230}{}{Ah, that's it. And I already thought that in front of me is the savior of our village. Well, I have something for you. That's what the kids found, it looks like one of the raiders dropped it.}
{1230}{}{Ah, that's it. And I already thought that in front of me is the savior of our village. Well, I have something for you. That's what the kids found, it looks like one of the raiders dropped it.}
{231}{}{Brass knuckles? Yes, I can use it.}
{232}{}{It's good that we have you... Oh, yes, the children found this, it looks like one of the raiders dropped it. Take it, maybe it will help you.}
{233}{}{They still have nightmares. I'm trying to help them while the others are busy rebuilding the village. Although sometimes the support itself would not hurt. We can't let this happen again!}