{101}{}{You see your fellow tribesman. His body is one continuous wound.}
{102}{}{You see your fellow tribesman. After treatment, he is on the mend.}
{103}{}{You will not be able to treat such injuries yourself. We'll have to look for medicines.}
{104}{}{Surgical intervention is required here.}

{105}{}{Thank you, amigo. So much better.}
{106}{}{Thank you, amigo. That's much better.}
{107}{}{Uh, thanks, amigo. It's much better this way. That's just I don't trust this old chemistry.}
{108}{}{Alien medicine is better than our poultices. You can't argue with that!}

{110}{}{The raiders... I think they broke my rib...}

{200}{}{Salute to our savior!}
{201}{}{Bye.}
{202}{}{During the treatment, you were distrustful of pre-war medicine. Why?}
{203}{}{Our ancestors always taught us not to trust the things of the Old World. They said that these things were cursed by spirits and carried danger. But one of them just saved my life. Now I'm thinking, won't I be cursed?}
{204}{}{But you're still alive. Now rest.}
{205}{}{This stranger, of course, knows his business. And I've never been so fresh after an illness! But the ancestors always taught that you can't trust the things and traditions of the Old World. Now everyone will think that I am cursed by spirits!}
{206}{}{But you're still alive. Now rest.}
{207}{}{How do you feel after treatment?}
{208}{}{I thought I was finished. But it's all right now. You're doing real miracles. After all, people with fractures in the Villa rarely survived. And how did we not notice you have this gift before?}
{209}{}{The main thing is that you're alive. Now rest.}

{210}{}{What do you know about the world outside the Villa?}
{211}{}{Not much. All my life I have not been further from our desert. And I don't regret it at all. Talk to Jose, he knows something, because he occasionally does business with strangers.}
{212}{}{I'm going on a trip. How can you help me?}
{213}{}{As you can see, I'm of little use. But I can give you this (takes out a handful of cartridges of different calibers). One of the raiders dropped it during the assault, and I hid it. I hope you'll find this useful.}
{214}{}{Thank you.}
{215}{}{Do you know those who have been outside the Villa?}
{216}{}{What are you! Who in their right mind would leave their home and go to the hot desert?}
{217}{}{Well, yes, I have to practice my skills on someone. Be there.}