{100}{}{You see Eden.}
{101}{}{You see a boy named Eden. He seems wild and scared.}
{102}{}{*Silently nods his head*}
{103}{}{Eden returned to the Villa.}

{200}{}{(Looks at you fearfully, without uttering a word)}
{201}{}{Hey, don't you know it's dangerous to walk alone here?}
{202}{}{(Continues to stare at you in fright)}
{203}{}{Look, It's a tough time for everyone, but together we can get through it. Come on - let's go to the village.}
{204}{}{Don't worry, I'll take care of you.}
{205}{}{Then stand here and get dirty, you pussy. I'm leaving.}
{206}{}{It's too dangerous here. Let's go back to the Villa.}
{207}{}{Hey, look, I have a juicy mutfruit. You must be hungry, right?}
{208}{}{Stay here, I'll be back soon.}
{209}{}{Oops, I think it fell out of my pocket. Stay here, I'll be back soon.}

{210}{}{(Silently shakes his head and backs away from you)}
{211}{}{Ah! (Looks like Eden is ready to follow you now)}
{212}{}{Great, follow me.}