{100}{}{You see Jose.}
{101}{}{It's your uncle. As always, he portrays a cheerful good-natured man, but now it's not working out well.}
{102}{}{Today is not your day, Jose.}
{103}{}{You have added a new task to your Pip-Boy.}
{104}{}{Santo cielo! Why are you scaring me like that? Such armor has no place in a peaceful villa.}
{105}{}{You are possessed by the demons of the desert. Get out of the village. Leave us alone.}
{1105}{}{You're possessed by desert demons. Get out of the village. Leave us alone.}

#The first dialog
{200}{}{Oh, dear amigo, how glad I am that at least the cursed fate has left you with us! Ay-ay-ay, the damned raiders. You're lucky you weren't around.}
{201}{}{Uncle Jose, tell me about the raid.}
{202}{}{Eh, these devils swooped in a crowd when no one was waiting. Someone was immediately tied up, and someone managed to hide at home. Your padre and the men took refuge in the town hall. They were stormed out of there. The shootout was not a joke. The dead are lying like that, there is no one to bury them.}
{203}{}{Tell me more.}
{204}{}{And then everyone was taken to the square. Everyone was evaluated like some kind of bag of corn. Those who were stronger were taken separately, the rest were driven home and locked up.}
{205}{}{What happened then?}

{206}{}{At night, the raiders were not going to sleep - they robbed the Villa and got drunk. And in the morning they took our people and went to the Wastelands, to the east. Since then, it's been quiet and peaceful here. We sit and lick our wounds.}
{207}{}{Who were these raiders?}
{208}{}{You say they went east. Or rather?}
{209}{}{Why did the raiders take our people?}
{210}{}{Well, I think it's time for me to deal with this problem.}
{211}{}{They picked up all sorts of rabble from everywhere. I recognized someone from the Garage, but most people are not local and have never heard of such.}
{212}{}{I only know about Garage City in that direction. The raiders will probably wander there for the night.}
{213}{}{That's what they didn't tell old Jose about their plans. But you know what, it looks like they'll be forced to work. I don't know where or why.}
{214}{}{And my parents?}
{215}{}{Sorry, they took them away. And your father. And Madre, too. Only the elderly were left and children.}
{216}{}{Leave your stupid optimism. I need to know what happened here.}
{217}{}{It's terrible!}

{220}{}{These are the words of the real Valiente Guerrero! What are you going to do now? Will you start chasing the raiders? They are already far away.}
{221}{}{What do you advise me?}
{222}{}{First tell me again about the raid.}
{223}{}{Well, first look into Garage City. It's a nasty place, but the raiders will probably look there. Ask around the locals, they have a chatty tongue when they are well cajoled.}
{224}{}{Cajoling?}
{225}{}{Be careful with those people, they would sell their own mother for profit. Here, take these fruits for the road and maize flour. They'll tell you anything for such things there.}
{226}{}{Thank you, Jose.}
{227}{}{You're welcome. These raiders took out everything they could find. I'm giving you the last one. The main thing is to use it wisely.}
{228}{}{And that's it? What a miser you are.}
{229}{}{Hey, the raiders took out everything they could find. I'm giving you the last one. The main thing is to use it wisely.}
{230}{}{Little, Jose. Need more.}
{231}{}{Just like that, will you take and leave your dear uncle without food? La-adno, here's some more. But I can't give you more. These raiders took out everything they could find.}
{232}{}{These raiders took out everything they could find. I'm giving you the last one. The main thing is to use it wisely.}
{233}{}{So then I'll have to figure it out on my own. Adios, Uncle Jose!}
{234}{}{I see.}

{240}{}{Thank heaven, you came back and brought the others with you!}
{1240}{}{Thank heaven, you came back and brought the others with you!}
{241}{}{Yes, it was not an easy journey. You know, there was a huge world outside the Villa. I've never been told about him.}
{242}{}{And you'd better keep quiet too, amigo. Outsiders have their own truth, and we have our own. And we won't understand each other. That's why we live in isolation from the rest. So that no one tarnishes us, no one imposes their own rules on us. You already know what this raid has done. It's not worth repeating such a story, right?}
{243}{}{I'll think about your words, Jose.}

#Repeat dialog
{250}{}{Good to see you, amigo.}
{251}{}{Amigo, don't go around doing nothing. Get busy with something already, eh?}
{252}{}{I have to go.}

{253}{}{There are a few questions... No, a lot of questions.}
{254}{}{Ask me anything.}
{255}{}{What do you know about the world outside the Villa?}
{256}{}{Have you ever been interested in the cellars of the Villa?}
{257}{}{Do you want to come with me?}
{258}{}{}
{259}{}{Another question.}

{260}{}{Wild desert places. In the north there are cannibal savages, in the east, there is a dump town, there are several other small villages and ranger camps. There is also a rumor about some big city, but I myself have never been further than the Garage.}
{261}{}{Why do you call the neighborhood wild?}
{262}{}{We've been trying to avoid strangers for years. Only if it presses hard, then we go to trade. Strangers cannot be trusted, they usually have neither families nor homes. Is it possible to make friends with such people? So your padre drove all the strangers away.}
{263}{}{It seems that Villa's knowledge of the outside world is very limited. Don't you find it?}
{264}{}{Aren't there enough raiders for you? And the cannibal savages? And the looters? No, it's not for nothing that we shut ourselves off from strangers. After all, there, in the wastelands, people do not live. And they survive.}
{265}{}{Tell me about the savages.}
{266}{}{Jackals, that's what we call them. They are so wild that they don't even know the human language. And they also say that they are all cannibals. Fortunately, they can break off their fangs about us, but the scavengers from the neighboring city often told about them. So stay away from these savages.}
{267}{}{Who are the Rangers?}
{268}{}{Cool and self-confident guys. They say they are protecting us from the villains, but who will understand what they have in mind? Sometimes they come to show themselves, but we can cope without their help... and you know, now such help would be very useful to us.}
{269}{}{If you haven't been, who has?}
{270}{}{Your Uncle Miguel, for example. He once quarreled with your padre and left the Villa. Haven't heard of him for years.}
{271}{}{Why did they quarrel?}
{272}{}{They had an argument about how Villa should deal with outsiders. Some believed that it was necessary to drive them away, and others offered to do business with them. They never found a common language. Although both were talking business.}

{273}{}{Tell me about the neighboring city.}
{274}{}{Garage City? It's a bad town and the people there are bad.}
{275}{}{What kind of people live there?}
{276}{}{Scavengers. That's what they call themselves. They walk through the ruins and look for something valuable. Be careful with them - they're all crooks and they smell bad.}
{277}{}{Where could Miguel have gone?}
{278}{}{I remember he wanted to visit that big city, which is legendary. But I'm afraid he found nothing but death in the sand.}
{279}{}{How do you know about Garage City?}
{280}{}{Hey, I'm the main dealer with outsiders in the Villa. Who better than me to know? Caravans sometimes come from there, we will exchange a few words and disperse peacefully.}
{281}{}{What is the relationship of the Villa with the Garage?}
{282}{}{The padre hasn't told you yet, has he? Bad people live there. But we have to trade with them. We give them food, and they give us tools and repair services. That's where all our "relationships" end.}
{283}{}{It looks like you don't like this city.}
{284}{}{You know old Jose - who treats me with kindness, so I treat him with the same. And these then trade dishonestly, then they want to steal, then they will say rude words. And after all, they have no better opinions about us. They are jealous that we live better than them.}
{285}{}{}
{286}{}{}
{287}{}{(shakes his head ruefully) Eh, amigo, how did this damned wasteland beat you up that you look like that?! Does it hurt? Well, even so. The main thing is not to worry - we are still for you, we are of the same blood.}
{288}{}{Thank you, Jose. I can live with this skin somehow.}
{289}{}{Problems, smooth-skinned? I don't need your pity, so you'd better shut up.}

{290}{}{What are you talking about? We store grain there. Ah, Grandma Adonsia whispered all sorts of stories to you, huh? Hehe, forget it, there's nothing there.}
{291}{}{Then how do you explain this jumpsuit and the arm computer?}
{292}{}{Hmm? Found it under the town hall, then? Well, then talk to your padre. Jose doesn't know anything.}
{1292}{}{Hmm? Found it under the town hall, then? Well, then talk to your padre. Jose doesn't know anything.}
{293}{}{Uncle Jose, you're definitely lying.}
{294}{}{Hey, amigo, enough of this! I'm just a merchant with a bad leg, I'm not privy to secrets. Yes, I know that the padre kept a secret place in the basement. And that family heirlooms were kept there, but it's not my business, you know?}
{295}{}{I would go anywhere with you, but at my age and with my bad leg you won't get far. Don't be angry, you can do it alone. I believe in you. We're the same blood, hey!}
{296}{}{Jose, you're not having fun.}
{297}{}{Eh?}
{298}{}{Well, just so much has happened... Oh well, forget it.}
{299}{}{You're not having fun, Jose. You can't have fun. People died, others were driven into slavery, the Villa was ruined... Stop pretending you're having fun.}
{300}{}{(lip trembling) Amigo... Why are you so...}
{301}{}{And now go cry...}
{302}{}{It's okay, Uncle, just give free rein to your feelings, you don't have to keep them to yourself...}
{303}{}{What are you talking about?}

#Tasks
{310}{}{Is there anything I can do before I leave?}
{311}{}{Do you want to help in the restoration of the Villa? We'll manage somehow, your business is more important.}
{312}{}{Something else?}
{313}{}{There are a couple of strangers on the plantations. It would be nice to drive them out of there.}
{314}{}{More?}
{315}{}{The raiders also broke the weather station. It needs to be fixed. Surely there will be spare parts in the neighboring city.}
{316}{}{Is that all?}
{317}{}{There are no other tasks for you.}
{318}{}{Looters on the plantations are no longer a problem.}
{319}{}{You succeeded! It's scary to imagine how this story would have ended without your intervention. It's good that the Villa has you.}
{320}{}{Bye.}
{321}{}{The weather station is in perfect order.}
{322}{}{Good news! We couldn't have done it without you. Thank you.}
{323}{}{Bye.}

#Gambling
{350}{}{Uncle Jose, I know you like gambling. Shall we play?}
{351}{}{What are you! You need to save our people! That's when they return to the Villa, then I'll be happy to shake the dice at the gaming table.}
{352}{}{Then temporarily forget about the games and talk about something else.}
{353}{}{You're absolutely right, I should hurry up.}
{354}{}{Don't tell me what to do. However, I still didn't want to play.}
{355}{}{Well, if you think about it, then after the return of our people, I could use a detente. But keep in mind - I will not give in.}
{356}{}{Great, get out the board and lay out the dice...}
{357}{}{Playing with you is just wasting time. Let's have a chat.}
{358}{}{You know, now is not the best time. I'll come play later.}
{359}{}{You beat one of the best players of the Villa and thereby increase your level.}
{360}{}{ }
{361}{}{You've lost. Well, this is not the first and not the last case.}