{110}{}{Bad people won't come back? Really?}
{111}{}{. . .}
{112}{}{Your coming in power armor has alarmed the local population.}

{200}{}{(the girl looks numbly at your iron armor, unable to understand whether to admire this sight or scream in horror)}
{201}{}{Greetings, child. From now on, the Big Iron Man will be your protector. And bad people won't dare come here.}
{202}{}{(her eyes widen in admiration, then she runs away to tell about the Big Iron Defender)}
{203}{}{Don't be afraid anymore, child. You're in good hands.}
{204}{}{Yes, run, tell everyone, little gossip girl.}
{205}{}{[Ignore and move on]}

{210}{}{What are you staring at? I will crush anyone who looks at me with an inappropriate look!}
{211}{}{A-a-a! El Diablo! El Diablo!}
{212}{}{Eh, the new generation has become a pussy...}
{213}{}{}
{214}{}{[Ignore and move on]}