{100}{}{This is your madre.}
{101}{}{You see a woman you know well, moreover, your mother.}
{102}{}{Goodbye, Mother. Now I'll take care of myself on my own.}
{103}{}{Your Madre has returned to the Villa.}
{104}{}{Here's another one! Get out of there! Stop scaring people.}
{105}{}{}
{106}{}{ And here is our hero. We love you.}
{1106}{}{And here is our heroine. We love you.}
{107}{}{Please leave and don't come back. No one here wants to hurt you.}
{108}{}{Be careful. We love you.}

#The first dialog
{200}{}{And here is our hero. The whole Villa owes you after our rescue. It was a real feat.}
{1200}{}{And here is our heroine. The whole Villa owes you after our rescue. It was a real feat.}
{201}{}{How did you get to the Villa?}
{202}{}{The path was not close. And very difficult. We were saved by unity and cohesion, in this the inhabitants of the Villa have always differed from the savages.}
{203}{}{Perhaps.}
{204}{}{Oh my God! What have these damned wastelands done to you? Your skin feels like... burned! How are you doing? Can you talk? Ugh, I don't know what to think. It looks like you're going to stay in this skin forever. I am so sorry. But don't worry - we will definitely find a cure for this disease.}
{205}{}{Oh that, I'm already starting to get used to my new body.}

#Second dialog
{210}{}{What can I do for you?}
{211}{}{Oh, nothing special.}
{212}{}{Did something happen? Why aren't you sleeping?}

{220}{}{Can I ask a delicate question?}
{221}{}{Of course, because I can be honest with you?}
{222}{}{Why was the rest of the world hidden from the residents of the Villa? I managed to visit various unusual places, and it was... an unexpected experience.}
{223}{}{Ah! Look at the Villa. When the Founder brought people here, it was a lifeless wasteland. Our ancestors invested their whole lives so that at least something edible could grow here. They succeeded only thanks to their faith in the precepts of the Founder: work for the good of the community, share your gains with everyone and do not let strangers in.}
{224}{}{[Listen]}
{225}{}{Tell me, are there many places outside the Villa where gardens also bloom and peace reigns? In this case, we have nothing to learn from the "rest of the world".}
{226}{}{But the world is changing. Do you think the Villa doesn't need a change?}
{227}{}{What changes can there be? Grow the harvest and share with everyone - that's all the change that can be in our community. Of course, we sometimes need things from the outside, but they can always be exchanged for our fruits. Don't fill your head with unnecessary thoughts. The outside world has lost its way and is going the wrong way. Someday it ends in an abyss.}
{228}{}{I'll think about your words.}
{229}{}{Okay, forget it.}
{230}{}{You know, the community is going to punish Chris for his cowardice.}
{231}{}{I tried to persuade the Council to mitigate the punishment, but the law is above me. Obviously, people need to blow off steam, and they decided to use Chris. Perhaps it would be better this way. In any case, do not contradict the majority opinion.}
{232}{}{It's interesting to listen to you. Can you tell me anything else?}

#Quests
{250}{}{What else can I do for the Villa?}
{251}{}{Your padre still hasn't returned from slavery. I'm afraid someone will have to go on a journey to find him. And there are no volunteers besides you.}
{252}{}{What happened to him after coming to Flagstaff?}
{253}{}{He was interrogated for a long time, and then taken to a big city called Phoenix. I don't know anything else.}
{254}{}{I'll take care of it.}
{255}{}{Ask around other residents. Everyone needs help here - in word or deed.}
{256}{}{Okay.}
{257}{}{The padre died. Don't wait for him.}
{258}{}{(sighs) I can't believe it... He was a strong leader, the whole community was supported by him... Do you know that for sure? Then we should not waste any more time.}
{259}{}{What are you talking about?}
{260}{}{Go to the town hall. We need to gather the elders and decide what to do next. You're our leader now. Make decisions thoughtfully... And I need to lie down. Don't worry about me.}
{261}{}{OK, I'll be there.}
{262}{}{Have you come across Sancho and Hugo? It looks like they stayed in Flagstaff, if they didn't disappear in an attempt to escape.}
{263}{}{Okay.}
{264}{}{Let's chat a little more before we part?}
{265}{}{Let's chat a little more?}

{270}{}{The council wants to blow up the Flagstaff mines. How do you like this idea?}
{271}{}{Please take care of yourself. I don't want to let you go on such a dangerous mission. But this mine needs to be stopped. Otherwise, the hand of the slaveholders will reach our village again. And we don't have the strength to fight it.}
{272}{}{Clear.}
{273}{}{The council decided to destroy the Garage City plant. What do you think about it?}
{274}{}{The scavengers have already shown their corrupt nature. They cannot be trusted, they do not have warm neighborly feelings for us. When they launch the plant, a flood of new labor will flow here. This cannot be allowed if we want to preserve our way of life and peaceful life.}
{275}{}{Clearly.}
{276}{}{How do you feel about the alliance with the Rangers?}
{277}{}{We need allies, and we can't find better rangers. But I am afraid that they will interfere in our internal affairs. This should not be allowed. Let them take food and protect us from robbers. Don't settle for more.}
{278}{}{Your doubts are understandable, Madre.}
{279}{}{How do you feel about the alliance with the Brotherhood of Steel?}
{280}{}{We don't have a choice, do we? Well, the most important thing is that we stay alive. Saving people in such a situation is our main task.}
{281}{}{Good answer, madre.}
{282}{}{Luck will definitely not hurt me.}
{283}{}{You have received a permanent bonus to luck.}

{290}{}{How were you treated in the colony?}
{291}{}{The jailers forced me to work, but at the same time they treated me with leniency, because I am a woman. What can not be said about men. Those they used sometimes with extreme cruelty. However, they did not want to lose their labor force either, so they were mainly engaged in intimidating slaves.}
{292}{}{And ordinary citizens?}
{293}{}{The colonists tried not to talk to me. I think they themselves are not in a particularly free position because of the large taxes. It is not surprising that even the family pendant, inherited from my grandmother, was taken away from me. Although it does not represent any value to the colonists.}
{294}{}{Why would someone need your pendant?}
{295}{}{Well, he said he would get "good caps" from the bartender for it. I doubt that he helped out at least one and a half caps.}
{296}{}{Sorry to hear that. I hope that jailer got what he deserved.}
{297}{}{It's just a family pendant. You can forget about him.}
{298}{}{Here's your pendant.}
{299}{}{Ah, thank you! Really, it wasn't worth the risk. And yet you are doing well to preserve our family history. Put on this pendant. It's yours now. May he bring you good luck on the way.}