{100}{}{You see a marauder.}
{101}{}{You see an outsider who is carefully inspecting the neighborhood in search of valuables.}

{110}{}{We're leaving. Don't even think about following us.}
{111}{}{This time we will leave. But others may come after us.}
{112}{}{That's all we wanted.}
{113}{}{There's nothing else for us to do here.}

{200}{}{Hey! Are you one of the locals? Then you should know where the keys to the hangar are.} 
{1200}{}{Hey! Are you one of the locals? Then you should know where the keys to the hangar are.}
{201}{}{Why do you care about the hangar?}
{202}{}{We know that there is a lot of maize flour there. And this is the only hangar not looted. So quickly find the keys, get us the flour, and then we'll leave here without touching anyone.}
{203}{}{Is maize flour so valuable to you?}
{204}{}{Don't you even know about the famine in the Wastelands? There are barren lands around, only you manage to grow crops. They say you fertilize the earth with human blood. But you know what, I don't care. Just give us all the flour and we'll leave. Understood?}
{205}{}{So you didn't participate in the raid?}
{206}{}{No. We heard about the raid and came to collect what was left after it. Do not waste all these deposits of the most valuable provisions.}
{207}{}{If I give you all the flour from this hangar, will you leave?}
{208}{}{I give you my word. Ten bags will be enough for us, we won't carry more anyway.}
{209}{}{So they're looking for you for lynching? Pitchforks are already being distributed in the square.}
{210}{}{You're bluffing. There were only children and old people left in the village. Who should we be afraid of?}
{211}{}{Old people and children. When they gather in a crowd, it is better not to anger them.}
{212}{}{Damn it! I told you they'd come again. So, let's get out of here...}
{213}{}{Here are 10 bags of maize for you. Is that enough to get you out of the Villa?}
{214}{}{Quite. I don't want a bunch of hillbillies coming after us. So, let's get out of here...}
{215}{}{Give me some time to figure it out. I'll be back.}
{216}{}{Hurry up...}
{217}{}{The looters leave the Villa peacefully.}
{218}{}{Get us some flour, and then we'll leave here without touching anyone.}
{219}{}{I'm not kidding.}
{220}{}{Get out of here!}
{221}{}{Let's see how it ends...}
{222}{}{Okay, you got it.}
{223}{}{The villa is now under the protection of the Rangers. You're taking a big risk.}
{224}{}{Rangers? Here? It's a bad thing. Let's get out of here quickly...}
{225}{}{Yes, yes, you should hurry up.}
{226}{}{Get out. And don't come back.}
