{100}{}{This is Uncle Miguel.}
{101}{}{You see your uncle arriving from Phoenix.}
{102}{}{I've never liked you... uncle.}
{103}{}{Uncle Miguel has returned to the Villa.}
{104}{}{That's right, show the hillbillies high technology. They will be SO happy...}
{105}{}{So this is the legendary power armor? (whistling)}

#The first dialog
{200}{}{Hello, dear nephew. I think I understand now why you value this place so much. It's quiet here. Not like a big stuffy city.}
{1200}{}{Hello, dear niece. I think I understand now why you value this place so much. It's quiet here. Not like a big stuffy city.}
{201}{}{It seems that you despised the Villa with all your appearance. What has changed?}
{202}{}{What are you, I appreciate the Villa! It's a beautiful place and wonderful people. I just wanted to show them that their little world is doomed.}
{203}{}{Then why did you come back?}
{204}{}{Well, the Phoenix is not the same anymore. After you clicked in the wrong place, almost a civil war began there. After that I realized that... I was wrong about something.}
{205}{}{Something? Yes, you were definitely wrong about something, Uncle Miguel. Later.}

{210}{}{Hello, dear nephew.}
{1210}{}{Hello, dear niece.}
{211}{}{Bye, Uncle Miguel.}