{100}{}{This is Chris's brother.}
{101}{}{You see the boy is Chris' brother.}
{102}{}{How do you control this thing? She's a little scary...}

{200}{}{Hi.}
{201}{}{Bye.}
{202}{}{What are you doing?}
{203}{}{They help to restore the house after the raid.}
{204}{}{Did you notice anything unusual?}
{205}{}{Just these strange things that the raiders dropped. (shows spent cartridges and a pair of whole 10 mm cartridges)}
{206}{}{I think I'll take this. There is nothing to touch the things of strangers.}
{207}{}{No, nothing.}

{210}{}{Hi, I'm walking here...}
{211}{}{It's more like you're bringing someone food.}
{212}{}{Aren't you lying? Okay, I'll believe it this time.}
{213}{}{This food is for me.}
{214}{}{[Track where the child will go]}
{215}{}{Don't worry, I believe you.}
{216}{}{Do you know where your brother Chris is?}
{217}{}{Nope. I don't know.}
{218}{}{Okay. I'll keep looking.}