{100}{}{You see old Hidalgo.}
{101}{}{You see one of the elders of the community.}
{102}{}{You are our hero and savior. We love and appreciate you.}
{1102}{}{You are our heroine and savior. We love and appreciate you.}
{103}{}{It will be better for everyone if you leave the Villa. And you will never come back here again.}
{104}{}{Good road to the son of Andres and Maria. Don't forget your roots.}
{1104}{}{Good road to the daughters of Andres and Maria. Don't forget your roots.}
{105}{}{What kind of jokes are these? Get lost, steel demon!}

#The first dialog
{200}{}{(in front of you is an old Hidalgo; as usual, he is half asleep chewing something)}
{201}{}{Ahem. Old man, did you want to see me?}
{202}{}{Ah, }
{203}{}{...Ho-sho... wh... mind... here...}
{204}{}{Listen, if you stop chewing your tobacco, maybe I'll hear something.}
{205}{}{ (spits and wipes himself with a bony palm) I'm talking... The community wants to see you at the meeting. We decided that you should also give your opinion.}
{206}{}{What kind of meeting is this?}
{207}{}{The community must decide what to do next. After all, the problems do not end with saving our people.}
{208}{}{When will the meeting take place?}
{209}{}{In the evening, when everyone finishes their business and gathers in the hall. Old people don't like to rush, so keep in mind that it will take the whole evening.}
{210}{}{I'll come to the beginning. See you later.}
{211}{}{OK, I'll come to the beginning.}
{212}{}{It will be easier for me to wait here. Maybe we'll spread the bones to pass the time?}
{213}{}{I'll wait here. I'm in no hurry anyway.}

{220}{}{, do you remember about the meeting?}
{221}{}{Yes, I'll be on time.}
{222}{}{It's already evening. It's time to start.}
{223}{}{I'll wait here. Maybe we'll spread the bones to pass the time?}
{224}{}{I'll wait here.}
{225}{}{You're late. Everyone has been asleep for a long time.}
{226}{}{Hr-r-r... hruk... khr-khr-khr...}
{227}{}{He's fast asleep. And it's useless to wake him up now...}

{230}{}{The meeting begins.}
{231}{}{The meeting is over.}
{232}{}{Is everyone here? Good. We need to hear everyone.}
{233}{}{ }

#First meeting
{250}{}{As we have all seen, hard times are coming.}
{251}{}{[Next]}
{252}{}{There was a life beyond the valley that we didn't know about. The outsiders have also heard about us and our plantations. Not now, so later all sorts of robbers and traders will come here to snatch from our fruits.}
{253}{}{[Next]}
{254}{}{We must prepare for their appearance. Remember how easily the robbers broke into the village and took everyone prisoner? Even senor Andres could not fend off the attack in the town hall. (the hall is filled with a roar of indignation)}
{255}{}{[Next]}
{256}{}{Hush. We are all tense. But all is not lost yet. We have returned from slavery, our homes have survived, and the plantations will soon yield a new crop. We still have some time.}
{257}{}{[Next]}
{258}{}{(A voice from the audience: "Old man, what can we do? The first bandits will squeeze us out like a ripe mutafruit.") I know, I know... Hush! It's not that bad. }
{259}{}{, come out to us. Come closer, sit here...}
{260}{}{[Go out to the public]}
{261}{}{Here is our savior. }
{1261}{}{Here is our savior. }
{262}{}{ helped all of you to get out of the bondage. He will also help to keep our families from strangers...}
{1262}{}{ helped all of you to get out of the slave fetters. It will also help to keep our families from strangers...}
{263}{}{Hello everyone, guys. How are you?}
{264}{}{Glad to see you all.}
{1264}{}{I'm glad to see you all.}
{265}{}{}
{266}{}{(dissatisfied shouts are heard from the crowd and one of the peasants rises: "Hey, old man, don't shield the kid. We would have gotten out of that mess ourselves. I won't lie if I say that the whole community considers him an unworthy heir. And this story doesn't change anything.") Hush! I know that many of you dislike }
{1266}{}{(dissatisfied shouts are heard from the crowd and one of the peasants rises: "Hey, old man, don't shield the girl. We would have gotten out of that mess ourselves. I won't lie if I say that the whole community considers her an unworthy heir. And this story doesn't change anything.") Hush! I know that many of you dislike }
{267}{}{. But what would you do without his intervention? And even now it's not about that.}
{1267}{}{. But what would you do without her intervention? And even now it's not about that.}
{268}{}{Don't pay any attention to them. They've always been jealous of me.}
{269}{}{It's all right, man. Let's not discuss me, okay?}
{270}{}{(cheers are heard from the audience and one of the peasants rises: "I don't know about the others, but I am grateful to you, }
{271}{}{. Many consider you a worthy heir of their padre.") Do you hear, }
{1271}{}{. Many consider you a worthy heir of their padre.") Do you hear, }
{272}{}{? Appreciate the trust you have earned.}
{273}{}{I understand. You can rely on me.}
{274}{}{Of course. I'll certainly put things in order here.}
{275}{}{(skeptical exclamations are heard from the crowd and one of the peasants rises: "Hey, old man. Of course, we are grateful, but you know, we are not up to heroism right now. }
{276}{}{ did what he had to do. Maybe we won't discuss it now?") You're right. But don't forget who pulled you out of captivity.}
{1276}{}{ did what you had to do. Maybe we won't discuss it now?") You're right. But don't forget who pulled you out of captivity.}
{277}{}{Friends, let's continue.}
{278}{}{Of course, we can't expect any other attitude from you.}

{280}{}{The fact is that slavery and the journey through the desert have undermined the health of senor Andres. He won't be able to get far from the Villa and is barely coping with the rebuilding of the village. }
{281}{}{, you'll have to do some of his work. It's time to take on the responsibility that your padre used to have.}
{282}{}{Of course. I've been preparing for this all my life.}
{1282}{}{Of course. I've been preparing for this all my life.}
{283}{}{Is this a joke? Hey, Daddy, what's going on?}
{284}{}{I also have to tell you the sad news. senor Andres, the padre of your savior, died during his slave wanderings. (universal exclamation) His place of honor according to the rules of the community is occupied by his direct descendant. }
{285}{}{, now you are our leader.}
{286}{}{Of course. I've been preparing for this all my life.}
{1286}{}{Of course. I've been preparing for this all my life.}
{287}{}{Wow. Sounds cool.}

{290}{}{Your madre would be proud of you. It's a pity she's not with us anymore. (everyone takes off their hats in prolonged silence)}
{291}{}{Cheer up, friends. She wouldn't want that.}
{292}{}{If anything, it wasn't my fault. Keep in mind.}
{293}{}{Your madre has already agreed to the transfer of the right of government. Now she is engaged in the restoration of the village, so you, }
{294}{}{, will have to do everything else.}
{295}{}{I can handle it.}
{296}{}{I'm finally being taken seriously.}

{300}{}{ (old Pablo rises from the hall) It's too early for a kid to manage a Villa! Don't make people laugh, Hidalgo! (the peasant rises) Yes, whether it should worry now? You tell me how to deal with slavers! (another peasant shouts after him) Have you heard what's going on with these scavengers from the next town? This is the end of our whole peaceful life!}
{1300}{}{ (old Pablo rises from the hall) It's too early to manage a small Villa yet! Don't make people laugh, Hidalgo! (the peasant rises) Yes, whether it should worry now? You tell me how to deal with slavers! (another peasant shouts after him) Have you heard what's going on with these scavengers from the next town? This is the end of all our peaceful life!}
{301}{}{Friends, calm down!}
{302}{}{What a farce ...}
{303}{}{ (the hall is filled with the hum of discussion, Hidalgo makes a soothing gesture) Hush! Stop making noise! We'll figure it out now, but let's take turns talking. }
{304}{}{, please, it's your turn to keep your word.}
{305}{}{Old Pablo, as usual, doesn't trust anything. I will have to answer his claims.}
{306}{}{About the slavers. This is the most important question.}
{307}{}{Garage City is a dirty city. But what's the problem with scavengers?}

{310}{}{"Hey, Pablo, isn't saving the village enough for you? What else do you want?" - "Shut up, Hidalgo. Let him answer. After all, running a Villa and running from slave owners is not the same thing at all."}
{311}{}{What else will you surprise us old people with?}
{312}{}{Salvation is enough to trust me. It's time for you old people to give way to the young.}
{313}{}{Old Pablo, your grumbling is getting on my nerves. I've said it all.}
{1313}{}{Old Pablo, your grumbling is getting on my nerves. I've said it all.}
{314}{}{That's enough.}
{315}{}{That's what I'm talking about - intemperance! The young don't know what it means to run a community. They don't know the prohibitions and they don't know the history. How can we trust such a person with our kind? (general indignation)}
{316}{}{[Next]}
{317}{}{But everyone will decide in any case. I have expressed my opinion.}
{318}{}{Hmm-m-m... Well, now I see who's in front of me. You value our people and you value our village. You can be trusted. But only if you listen to the old people. (addressing the audience) I approve! (the hall begins to make a joyful noise)}
{319}{}{[Next]}
{320}{}{While you were away, I repaired the weather station that was destroyed by the raiders.}
{1320}{}{While you were away, I repaired the weather station, which was destroyed by the raiders.}
{321}{}{What-what? Ah, the weather station... Was it really necessary to do this while our people were in trouble? Although the station is really important. Especially now, when we have so little food supplies.}
{322}{}{Jose would definitely not have coped with his bad leg.}
{323}{}{Well, I also chased away the looters. They were trying to take the last remnants of the harvest.}
{1323}{}{Well, I also chased away the looters. They were trying to take the last remnants of the harvest.}
{324}{}{And they did it, didn't they? You took the flour out of the hangar and gave it to them. (general indignation)}
{1324}{}{And they did it, didn't they? You took the flour out of the hangar and gave it to them. (general indignation)}
{325}{}{But they left and didn't have time to hurt anyone. And this is the most important thing!}
{326}{}{Yes. And it was the most reasonable decision.}
{327}{}{It's good. We have to save every grain now. Yes, but the looters wouldn't have taken much anyway. And we would have chased them away anyway, but later.}
{328}{}{This is nothing more than your speculation.}
{329}{}{Well, well. While you were gathering your courage, they would have opened the hangar and taken everything that was there. Say "thank you", ungrateful.}
{330}{}{I treated the wounded who were injured during the raid.}
{1330}{}{I treated the wounded who were injured during the raid.}
{331}{}{We know what kind of treatment it was. After all, you know (and everyone knows) that the Founder himself strictly forbade these ancient drugs. They are dangerous, half of them are poison. And if not, then the kind of people you cured may be cursed. It was very thoughtless of you. Although people are really alive. And this is important.}
{332}{}{It was a forced measure. People's lives are more expensive.}
{333}{}{To hell with your moldy taboos!}
{334}{}{People are alive because of you. And they will be able to restore the village. Thank you. But first of all, it was necessary to take care of those who fell into slavery.}
{335}{}{As you can see, I managed to cope with two tasks.}
{336}{}{You won't please, old man.}
{337}{}{The boy Eden almost got into trouble. I barely managed to get him out of the coyote encirclement on the plantation.}
{338}{}{We know this story. That was brave. There's nothing to say. However, I don't think he really needed help. He would have lived on maize leaves for a while, and then he would have returned to the village from hunger. The child is not a fool.}
{339}{}{I don't think so.}
{340}{}{These are just the sneaky conjectures of a nasty old man.}

{350}{}{(another voice from the audience) Wait, old man. We haven't remembered the Chris story yet. He was a traitor and deserved to be flogged. But if not }
{351}{}{, Chris wouldn't be able to escape. Who knows who he'll tell about us in the Wastelands?}
{352}{}{Um, listen...}
{353}{}{Right. It's a bad thing. How can you give yourself such a slack, }
{354}{}{? If someone is guilty, he must be punished. Your softness is not the best trait for a ruler. How will you justify yourself, }
{355}{}{?}
{356}{}{I acted according to my conscience.}
{1356}{}{I acted according to my conscience.}
{357}{}{That's what I'm talking about. Because of your quirks, you're putting our village at risk. (general outcry of indignation)}
{358}{}{Come on...}
{359}{}{I can't believe they were going to stone a fellow countryman.}
{360}{}{Relatives and loved ones should be responsible for each other. Here it is you who deserve a "spanking" for your attitude towards Chris. Shame and shame.}
{361}{}{ (the hall subsides in embarrassment) Well... This is debatable. Perhaps I'd better keep quiet here.}
{362}{}{That's right.}
{363}{}{(another voice from the audience) Wait, old man. In defense, I want to add how }
{364}{}{ returned Chris to us. Chris was a traitor, he deserves a spanking. If it wasn't for }
{1364}{}{ she returned Chris to us. Chris was a traitor, he deserves a spanking. If not for }
{365}{}{, he would have managed to escape. And who knows to whom he would have blabbed about us?}
{366}{}{[Next]}
{367}{}{Right. A good thing. A ruler can't show softness. If someone is guilty, he must be punished.}
{368}{}{[Next]}

{370}{}{(another voice from the audience) Let me! But what about this terrible iron thing that }
{371}{}{ constantly carries and scares children? We don't need that!}
{372}{}{This is power armor. And I need her.}
{373}{}{(old Hidalgo wakes up from a half-doze and gets into the conversation) They are right, }
{374}{}{. The Founder also bequeathed that old technologies should not be used. After all, it was because of them that a Great War happened a hundred years ago. That's why we've always shunned old technology. And you bring all this here and offer to accept it as if nothing had happened.}
{375}{}{Yes, you will not please.}
{376}{}{This technology has saved my life more than once. Perhaps she will save the Villa.}
{377}{}{Hmm-m... Well, if you think about it, maybe it is... But still - do not scare your people. We've been through enough lately.}
{378}{}{Okay...}
{379}{}{What's wrong with the old technology if it protects? Some nonsense.}
{380}{}{The founder knew what he was saying! Do you think you're smarter than your ancestors? (in the hall raises a cry: "U-u-u")}
{381}{}{Yes, you will not please.}
{382}{}{(another voice from the audience) Let me! But what about this terrible iron joke on which }
{383}{}{ driving around in the desert, raising dust and scaring children? We don't need that!}
{384}{}{A motorcycle? Without it, it would be much more difficult to travel long distances.}
{385}{}{(Hidalgo rises and makes a gesture) Who else wants to speak about our hero? No more comments? Then raise your hands, those who agree to appoint }
{1385}{}{(Hidalgo rises and makes a gesture) Who else wants to speak out about our heroine? No more comments? Then raise your hands, those who agree to appoint }
{386}{}{village head.}
{387}{}{Hmm. Interesting.}
{388}{}{Are you kidding me?}
{389}{}{Adopted by an absolute majority. Congratulations, }
{390}{}{. }
{391}{}{Wow, like a stone from the soul ...}
{392}{}{Could it have been otherwise? Well, okay.}
{393}{}{Less than half. Well, }
{394}{}{, you'll have to try a little more to earn trust. But according to the precepts of the Founder, his direct descendant should lead the Villa. Whether you want it or not. Postponing won't change that.}
{395}{}{It's nothing. I'm not in a hurry.}
{396}{}{What stiff-necked misers you are.}
{400}{}{It seems that we have solved all the most important issues. It's time for me to get busy.}
{401}{}{Yes, indeed. We will be waiting for your return. Good luck, }
{402}{}{. And let the winds blow at your back.}
{403}{}{[Leave the meeting]}

{410}{}{(your madre rises) While I was working in the garrison, I happened to eavesdrop on the conversations of mercenaries. They said that the number of slaves would only grow. There's no way they won't come after us again.}
{411}{}{(peasant rises) While I was working in the Flagstaff mines, I happened to eavesdrop on the conversations of mercenaries. They said that the number of slaves would only grow. There is no certainty that they won't come after us again.}
{412}{}{[Next]}
{413}{}{(peasant rises) }
{414}{}{(Sancho rises)}
{415}{}{You're right. We were just running out of the pen. As long as the mines are working, we can't be safe. I propose to destroy them.}
{416}{}{Destroy the mines? How do you propose to do this?}
{417}{}{In the mines we used a thing called "explosives". It explodes so that it collapses tons of stone. This substance should be enough in warehouses to block the passage deep into the mine.}
{418}{}{You're crazy. Go back there for the sake of sabotage? It's too dangerous.}
{419}{}{(Hidalgo stops chewing his tobacco) Do you have any better ideas? Then think about it and tell your decision at the next meeting. But don't delay.}
{420}{}{Okay.}
{421}{}{I like this idea. I'll blow these mines to hell.}
{422}{}{(universal shout of approval) Hooray! Blow up these diggers! Do it!}
{423}{}{Agreed.}
{424}{}{Give me time to think. Perhaps I can find a compromise with the owner of the mine.}
{425}{}{(the audience looks at each other in bewilderment) Can you really do that? Hmm, the wastelands have given you a lot of experience. But for now, the Council is sticking to the proposal with an explosion. I hope you make the right decision.}
{426}{}{Okay.}
{427}{}{ (Ugo rises) }

{430}{}{We have heard rumors from merchants that scavengers in Garage City are trying to restore an ancient factory and start production of various equipment there. Imagine what this means for our modest town!}
{431}{}{[Next]}
{432}{}{Jose, tell them. (Jose rises) Yes, of course... }
{433}{}{We will be a point on the caravan routes. Crowds of seekers of earnings will fall here. Along with them, robbers, weapons, and alcohol will come to the valley. We will not be able to resist such changes, we will simply be swept away.}
{434}{}{Are you suggesting to stop production?}
{435}{}{If it's all about their cars, then you need to destroy the cars themselves. I do not know how to do this. But those who have returned from Flagstaff are talking about something called "explosives". Surely this thing is capable of destroying machines if it destroyed mountains of stones. There is no need to destroy the entire plant.}
{436}{}{I have too good a relationship with the scavengers. I would not like to declare war on them.}
{437}{}{I would not like to declare war on the scavengers. They're our neighbors!}
{438}{}{They are traitors! They served the raiders who enslaved us. How can you build relationships with such bastards? In any case, we cannot allow the development of the plant. If you have another option, do something. But no one will hug these scum.}
{439}{}{Clear.}
{440}{}{For their betrayal, the scavengers deserved a good spanking. I will destroy their damned factory.}
{441}{}{ (universal shout of approval) Hooray! Destroy it! Kick these filthies!}
{442}{}{You can rely on me.}
{443}{}{You want to deprive people of their legitimate development. I will try to find a compromise.}
{444}{}{Negotiate with the scavengers? They are vile hucksters and born deceivers. The council does not approve of such an alliance.}
{445}{}{OK, I will consider different options.}

{450}{}{Hey, old man. I want to inform you that the Flagstaff mines have been destroyed.}
{451}{}{M? Oh... So did you succeed? Good. Well, let's hope for the best.}
{452}{}{It remains to deal with the plant in Garage City...}
{453}{}{I want to inform you that the Flagstaff mines are no longer a problem. Now they use a robot there and reduce the number of slaves.}
{454}{}{A robot, you say? That is, a car from ancient times? Oh, it's not good. Who knows how long she will work and whether Faber will think of something else? But the fact that he no longer needs slaves is good.}
{455}{}{Now I'm going to deal with the factory in Garage City...}
{456}{}{I have news - the machine at the Garage City factory has been destroyed.}
{457}{}{M? Ah... Good news. There's nothing to disturb the old demon. We were fine without the factory.}
{458}{}{It remains to deal with the penal servitude in Flagstaff ...}
{459}{}{We don't need to destroy the machines in Garage City. The leader of the factory offers favorable conditions for the restoration of the Villa.}
{460}{}{Oh... What are you talking about? Are you suggesting an alliance with the scavengers? Many people won't like it. On the other hand, their work would be very useful and would greatly help the whole Villa.}
{461}{}{Now I'm going to deal with the mine in Flagstaff...}
{462}{}{So both problems are solved. It's time to convene a new council.}
{463}{}{ (thinks for a long time, nodding in response) Good... But now you will only talk to the elders.}
{464}{}{Uh, okay...}
{465}{}{}
{466}{}{, we are grateful to you for getting rid of our enemies. Old Hidalgo told us that Garage City and Flagstaff no longer threaten us. But they are our closest and therefore most dangerous enemies.}
{467}{}{It turns out we have plenty of time left now.}
{468}{}{Oh no. I'm afraid that's not the case. You, your padre, and a few other elders have been away from home before. We know what the world around us is like. Without patrons, we are an easy victim for any bandits.}
{469}{}{Then we need to find allies. Or to become strong enough to be reckoned with.}
{470}{}{As you understand, our peasant customs do not allow us to even touch old technologies. We can cultivate, but we can't fight. We need a patron. The only one who can become one is the Rangers. Go to them, and arrange with General Mossman to protect the Villa in exchange for supplies.}
{471}{}{So be it. I will fulfill the will of the Council.}
{472}{}{I don't like the idea of allies.}
{473}{}{This is the will of the Council. We're counting on you.}
{474}{}{You can rely on me.}
{475}{}{Pray that your will does not turn into our willlessness. Happily.}
{476}{}{We are listening to you, }
{477}{}{. Tell me, how are things with our enemies now?}

{480}{}{Have you talked to the Ranger general yet? What is his answer?}
{1480}{}{Have you talked to the Ranger general yet? What is his answer?}
{481}{}{I haven't been able to see him yet. But I'm not giving up hope to do it.}
{482}{}{Recently, an ambassador from the Brotherhood of Steel came to us. His arrogance and arrogance has already bored all the villagers. We would like to hear from you personally, what does all this mean?}
{483}{}{You were looking for a patron ally. Here it is. It's not better to find.}
{484}{}{We know about the Brotherhood of Steel. Your padre found out about him when he was a slave. He also said that if it were not for the Brotherhood, there would be no Flagstaff colony, no Fire cult, and no penal servitude in Two-Sun. Now you bring the beast to our lands and make it work for him?}
{485}{}{So that the beast does not devour us, it remains only to make friends with him. As long as we regularly pay with the harvest, we will not be touched. Moreover, they will help us with equipment and security.}
{486}{}{(painful silence) Now you are the leader of the community. It's up to you to decide where to take her. If that's how you see the Villa's future, so be it. We will not be able to resist your will. We can't do it anymore.}
{487}{}{You are stuck in the past. Villa should have changed long ago. And an alliance with the Brotherhood will be a good impetus to this. The main thing is not to miss the opportunity. And now I need to retire and rethink this whole story. Por desgracia, tengo que irme.}
{488}{}{So, recently an ambassador from the Rangers came to us. Isn't this your job?}
{489}{}{Yes. The Rangers are ready to form an alliance to protect the Villa.}
{490}{}{Give me a minute. Before such an important event, you need to gather your thoughts...}
{491}{}{The Rangers pretend to care about us. Although they are only concerned about providing food. We will not allow them to go beyond the scope of the contract.}
{492}{}{While we are under their protection, we need to strengthen our position and build up our strength to fight back against our enemies on our own.}
{493}{}{(tacit consent) This is a story for you and future generations. You are the leader of the Villa, it's up to you to decide where to lead it. We old people don't have long left. But we are glad that the Villa is in safe hands.}
{494}{}{The main thing is not to allow yourself to be manipulated. And now I need to retire and rethink this whole story. Por desgracia, tengo que irme.}
{495}{}{The Rangers can't ally with us. They are defeated.}
{496}{}{I didn't have a good relationship with the Rangers. It seems they want to kill me at all.}
{497}{}{In that case, we are doomed. We will not be able to defend ourselves from enemies on our own.}
{498}{}{But Flagstaff and Garage City...}
{499}{}{You know perfectly well that they were just the periphery of a big process. Those who control the fate of Sonora are still firmly seated in the south. And they won't miss their chance.}
{500}{}{Who are you talking about?}
{501}{}{Your padre told me that the tinsmiths and fire worshippers were a puppet of the Brotherhood of Steel. Find this Brotherhood and stop it before it's too late. And don't come back to the Villa until then.}
{502}{}{OK. I'm leaving.}
{503}{}{A handful of old people. You're just crazy.}
{504}{}{Are you talking about the Brotherhood of Steel?}
{505}{}{Tinsmiths and fire worshippers were a puppet of the Brotherhood of Steel. Find this Brotherhood and stop it before it's too late. And don't come back to the Villa until then.}
{506}{}{I destroyed the Brotherhood of Steel ship. His voyage was over.}
{1506}{}{I destroyed the Brotherhood of Steel ship. His voyage has come to an end.}
{507}{}{Truly - here is a hero of heroes! Without the Brotherhood of Steel and Rangers, big cities will be mired in discord and will not be able to develop.}
{1507}{}{Truly, you are the patroness of our lands! Without the Brotherhood of Steel and Rangers, big cities will be mired in discord and will not be able to develop.}
{508}{}{For us, this is a chance to get back on our feet and get stronger to fight back against our enemies in the future.}
{509}{}{Now we see that the Villa is in good hands. You are a true leader, you are the future of our people.}
{510}{}{The main thing is not to allow yourself to be manipulated. And now I need to retire and rethink this whole story. Por desgracia, tengo que irme.}
{511}{}{This is very bad. If the Rangers are our enemies now, then we'll have to look for another ally. Who did they fight there, do you know?}
{512}{}{Okay. I'll try to find another ally.}
{513}{}{Perhaps I can sabotage their dam so that they will lag behind us at least temporarily.}