{102}{}{This is for you for my difficult childhood, Padre!}
{103}{}{Goodbye. I don't need my father's guidance anymore.}
{104}{}{Are you all right in the head? Go to the wastelands and bury this... "jar" deeper.}
{105}{}{Your padre has returned to the Villa.}
{106}{}{I'm proud of you, son.}
{1106}{}{I'm proud of you, daughter.}
{107}{}{From now on, I don't have a son. You're a stranger to me.}
{1107}{}{From now on, I don't have a daughter. You're a stranger to me.}
{108}{}{If you want to leave, leave. But don't try to take the others away.}

#The first dialog
{200}{}{Your return has delighted the whole Villa. I'm proud of you.}
{201}{}{This... nice to hear.}
{206}{}{What happened to you?}
{207}{}{You mean my skin? It's nothing.}
{208}{}{I really hope it's not contagious. Believe me, in order to protect the community, I am ready to sacrifice one close person. Enough about that for now.}
{209}{}{Thank you for your honesty... Padre.}

#Repeat dialog
{210}{}{Speak, I'm listening to you.}
{211}{}{It doesn't matter, I'd better go.}
{212}{}{More?}

{220}{}{Padre, why have we always lived in isolation from the rest of the world?}
{221}{}{Excessive contacts with foreigners will not bring good. So the Founder bequeathed. And we learned that well during the raid. Remember the settlements you have visited. People are divided and cannot cohabit in peace and harmony like us.}
{222}{}{[Next]}

{228}{}{I demand an explanation - why the hell is a stranger in a white coat wandering around our plaza and staring at our houses?}
{229}{}{Arthur Carrington is a scientist. It seemed to me that his help would be useful in restoring the Villa after the raid.}
{230}{}{The help of a person who can read and count, but can't hold a shovel in his hand?}
{231}{}{He's a little weak, right, but he knows a lot more about the outside world than you and me. And he also understands old technologies. With their help, we...}
{232}{}{I don't believe my ears! Has traveling through the desert completely overshadowed your mind? We've lived in isolation from the rest of the world for generations, and you bring an outsider here and offer to take up old technologies? Pray that your decision does not turn out to be a mistake. I will keep a close eye on this stranger. And for you, too.}
{233}{}{You won't regret it.}
{234}{}{You know, the community intends to punish Chris for cowardice.}
{235}{}{Villa has always held on to the opinion of the majority. That's the law. It was only thanks to this that we survived in the middle of the desert. Chris's story will be a great example of how important it is to follow everyone.}
{236}{}{}
{237}{}{}
{238}{}{That's why we refused to contact outsiders - so that they would not stain our fragile world with their selfishness. By letting outsiders into the community, we will only get discord. So keep your mouth shut when you talk about such things with the rest of the residents of the Villa.}
{239}{}{I see.}

{240}{}{I need supplies and reliable weapons for my mission.}
{241}{}{(nods his head significantly) I agree. I think it's time to give you some of our relics. There is a safe in my office on the second floor. It stores valuable old things. Take what will be useful to you. The code from the safe is 2093. This is the year when the Founder came to these lands and cultivated the first corn cobs.}
{242}{}{This story is forever in my heart. I will not shame family heirlooms and will fight for our freedom.}
{243}{}{Thank you.}

#Quests
{250}{}{Is there anything else I can help with?}
{251}{}{Our friends are still being held captive by the Flagstaff colonists. The Villa needs me too much right now and I can't leave the settlement to save them. You'll have to do it.}
{252}{}{OK, I'll do it.}
{253}{}{Are you crazy?! It took so much work to free you from Two-Sun, and now Flagstaff...}
{254}{}{We have no choice! This is your responsibility as the future leader of the community. Do what YOU HAVE to do!}
{1254}{}{We have no choice! This is your responsibility as the future leader of the community. Do what YOU HAVE to do!}
{255}{}{Your madre hasn't returned from Flagstaff. I'm afraid she's still in the clutches of the mercenaries. Save her at any cost!}
{256}{}{You can count on me, Padre.}
{257}{}{Madre is dead. Don't wait for her.}
{258}{}{Talk to people. Perhaps I do not know all the furniture in the Villa.}
{259}{}{Okay.}
{260}{}{(takes a deep breath, closing his eyes) Maria... Are you sure you know that? Well, it's better for the rest not to know yet, such news can further burden the lives of our people.}
{261}{}{What are we going to do now?}
{262}{}{We have a lot of work ahead of us. The raiders looted the settlement, rats got into the cellars, the plantations fell into disrepair during our absence, but the main thing is that we must be ready for new clashes with an external threat.}
{263}{}{[Next]}
{264}{}{The whole community should solve this issue. We are gathering a council in the town hall, you come too. Your travel experience will be especially useful when making decisions. Don't be late.}
{265}{}{OK, I'll be there.}
{266}{}{Talk to the people on the ground, maybe I don't know the whole situation in the Villa. And don't forget about the community meeting. Your word will be especially weighty when making decisions.}
{267}{}{OK, I'll come.}

{270}{}{The council wants to blow up the Flagstaff mines. How do you like this idea?}
{271}{}{It's very risky, but it needs to be done. And no one else but you can do it. If we leave the mines as they are, then slavery will only expand and someday it will reach us again. We have too little strength to confront this problem.}
{272}{}{Clearly.}
{273}{}{The council decided to destroy the Garage City plant. What do you think about it?}
{274}{}{Scavengers deserve this fate. They have already betrayed us by providing the raiders with everything they need for a raid. Now they decided to start the old factory. We will lose a lot if this happens. We will lose our privacy, peaceful life and our way of life, which has been developing for decades. To hell with this factory!}
{275}{}{Clear.}
{276}{}{How do you feel about the alliance with the Rangers?}
{277}{}{The Rangers have their own goals, and they don't coincide with ours in everything. But we need allies to strengthen our forces. And there is no one better than rangers. We can only hope that they will not interfere in our internal affairs, limiting themselves only to protection in exchange for food.}
{278}{}{Perhaps you're right, Padre.}
{279}{}{How do you feel about the alliance with the Brotherhood of Steel?}
{280}{}{Looks like we don't have a choice, does it? Well, if we can't defeat the enemy, it remains to make him our friend.}
{281}{}{Good answer, Padre.}

#Background of the Villa
{300}{}{I know about the Founder's Precepts.}
{301}{}{Well, I thought it was too early for you to know about such things. The rest of the residents should not read them either - there is no need to load their heads with questions that are worthy only of leaders. And you, as the future leader of the community, should treat these Covenants with all due attention and respect.}
{302}{}{Do you completely agree with this text?}
{303}{}{Of course. We have followed the Precepts all these generations and must follow them in the future. The founder was a wise man, and his wisdom came from a difficult life experience. Such an experience that none of us have. If he tells us to abandon the old technology, then it makes sense. If he says to cultivate maize, then we will be strong in this. If he considers the interference of the rest of the world in our affairs unacceptable, then the story of the raid only confirms this.}
{304}{}{I see.}
{305}{}{I happened to visit Vault 27. You never talked about him.}
{306}{}{What are you saying?! The very Vault from which our ancestors came out?}
{307}{}{Exactly. As the Founder said, this is a real storehouse of old technologies...}
{308}{}{Shut up! The Founder left the Vault. And you already know why. It is not necessary to stir up the past. Forget everything you could see and hear there.}
{1308}{}{Shut up! The Founder left the Vault. And you already know why. It is not necessary to stir up the past. Forget everything you could see and hear there.}
{309}{}{Why are you so afraid of the past?}

{310}{}{The founder believed that the community should abandon technology and engage only in manual labor. Therefore, he tried not to talk about the Vault and its technologies.}
{311}{}{But it's not just that? He stole some kind of Generator of the Garden of Eden and thereby condemned everyone else to suffering.}
{312}{}{(in the heat) It doesn't matter! He was saving his people! (calming down) Hard times required hard decisions. The founder lived with this burden until the end of his days. But it was he who created the Villa and gave life to this desert. And if someone considers his act a crime, I am personally ready to rip out his tongue.}
{313}{}{But Padre...}
{314}{}{I understand. You won't hear about it again.}

{315}{}{That's enough! Don't discuss it with anyone. The peasants will not be able to understand, and I and the elders categorically do not want to know anything.}
{316}{}{Whatever you say, Padre.}
{317}{}{Well, I'll think about your words.}
{318}{}{Thank you. Don't discuss it with anyone. The peasants will not be able to understand, and I and the elders categorically do not want to know anything.}