{100}{}{You see the ambassador.}
{101}{}{Here is an official ambassador from the Rangers.}
{102}{}{Our union has come to an end, Ambassador.}
{103}{}{You are under reliable protection.}

#The first dialog
{200}{}{Hello, guerrero. So it is to you that we owe such a strong alliance? You're the best of the best. But now you can relax and get back to business as usual. We, the Rangers, will look after the order in the Villa and its surroundings.}
{201}{}{I thought more rangers would be sent here.}
{1201}{}{I thought they'd send more rangers here.}
{202}{}{Don't worry, I'm not alone. The rest are patrolling and exploring the neighborhood. If necessary, I can always call them on the radio.}
{203}{}{Thank you for your service, Ambassador. I have to go.}
{204}{}{OK. But if you're lying, our union will come to an end.}

{210}{}{Greetings.}
{211}{}{It's time for me to go.}