{100}{}{You see the ambassador.}
{101}{}{Here is an official ambassador from the Brotherhood of Steel.}
{102}{}{Our union has come to an end, Ambassador.}
{103}{}{You are under reliable protection.}

#The first dialog
{200}{}{Greetings. I am an ambassador of the Brotherhood of Steel. So it was you who managed to rouse your tribe into an alliance with us? Good job. A lot of benefits will come out of our cooperation.}
{201}{}{Are you alone here?}
{202}{}{Don't worry, my squad has set up camp not far away in the wasteland. We thought our presence was a little... will excite your brother. If necessary, I can always call them on the radio.}
{203}{}{Thank you for your service, Ambassador. I have to go.}
{204}{}{OK. But if you're lying, our union will come to an end.}

{210}{}{Greetings.}
{211}{}{It's time for me to go.}