{100}{}{This is Mr. Assistant.}
{101}{}{You see a robot of the series "Señor Assistant".}

#The first dialog
{200}{}{Ah, finally! It's been a long time since I've seen the faces of living people. Decades of loneliness do not pass without a trace, even for my neural connections... Who are you? Tell me about yourself?}
{201}{}{I }
{202}{}{ from the Villa. And that's who you are... or WHAT are you?}
{203}{}{Lo siento, mi joven descendiente. Technically, I'm a car from the Old Days. But more importantly, I am the personality of Felix Tejada, your direct ancestor. Don't worry, great-great-grandson. Once there were plenty of such robots all over the continent.}
{204}{}{This is something amazing.}
{205}{}{Surely you have a lot of questions. I can answer them, and then you can answer my questions.}
{206}{}{I really have a few questions for you, Mr. Robot.}
{207}{}{I need to look around first. We'll talk later.}

{210}{}{Ah! How nice to see the light of the sun again.}
{211}{}{Glad to see you, great-great-grandson. Let me take a closer look at your face.}
{212}{}{End communication mode.}
{213}{}{Answer a few questions, robot.}
{214}{}{What do you want to know, my dear descendant?}
{215}{}{These were all questions. Hang up.}
{216}{}{Another question.}
{217}{}{Waiting for instructions.}
{218}{}{How sad... And I told the Caretaker that it was no longer possible to live in the Vault.}
{219}{}{I am more and more surprised by the willingness of people to get into the very ass in search of trouble. That's what we're here for, isn't it?}

{220}{}{Why are you being hidden here?}
{221}{}{I myself asked before I died to hide all the old technologies. When I brought my community to the promised land, the objects of the Old World helped us survive. But time passed, and technology began to fail.}
{222}{}{Go on.}
{223}{}{There was nothing to repair them, there was nowhere to find a replacement for them or energy sources. The necessary parts would have to be extracted in dangerous irradiated ruins, and this would have a sad effect on the health of residents. In addition, over time, people have lost their knowledge of the Old World, and ignorance leads to sad mistakes.}
{224}{}{I'm listening.}
{225}{}{I decided to protect future descendants from wrong steps and banned all kinds of electronic technologies. And looking at you, now I understand that this decision saved the life of the community.}
{226}{}{Curious train of thought.}
{227}{}{What kind of place is this?}
{228}{}{The crypt? It looks like there was an illegal fuel waste warehouse here before the War. Or just some kind of bunker. At least here we managed to hide from dust storms until the Villa bloomed in full bloom.}
{229}{}{Clear.}
{230}{}{Tell me how the Villa appeared?}
{231}{}{It's a long and sad story... To be honest, I don't know everything myself. Felix must not have wanted to talk about something. But one thing is clear - it has something to do with Vault 27 near Phoenix.}
{232}{}{Curious.}

{233}{}{What should I call you? You just... just a robot.}
{234}{}{Call me Felix, baby. What, is this too exciting for you? Well, that's your right. In that case, señor Assistant is the nickname your ancestor gave me.}
{235}{}{I'll just call you robot.}
{236}{}{Okay, then you'll be my Assistant.}
{237}{}{Whatever you say, Grandpa Felix.}

{240}{}{Do you want to travel with me?}
{241}{}{Of course, dear great-great-grandson! It's time to stretch these old bones. I hope you won't run too fast?}
{242}{}{Let's go, Grandpa!}
{243}{}{The assistant is ready to follow his master.}
{244}{}{Follow me, robot.}
{245}{}{Stay here and wait for further instructions.}
{246}{}{Grandpa will wait. Don't worry about me, dear.}
{247}{}{Be a good boy and don't pee in your pants, old man.}
{248}{}{Task accepted. I am holding the position until further instructions.}
{249}{}{Wait for me, robot.}
{250}{}{Switch to the protocol mode of the dialog.}
{251}{}{Turn on the personalized dialog mode.}
{252}{}{Speech personalization is disabled.}
{253}{}{That's better.}
{254}{}{Phew, man! Well, you made this old robot move its convolutions. What's next?}
{1254}{}{Phew, baby! Well, you made this old robot move its convolutions. What's next?}
{255}{}{Welcome back, Grandpa.}
{256}{}{Put your weapon away immediately.}