{100}{}{This is Arthur Carrington.}
{101}{}{You see the same archaeologist from Vault 27.}

#The first dialog
{200}{}{It's good to see you again. I have to thank you for the honor. Your Villa opens up new facets for my research work. And I'm already amazed at new discoveries! The way you cope without high technology - it amazes every understanding. Although some technologies should be brought back into use.}
{201}{}{Maybe so.}
{210}{}{Yes, yes?}
{211}{}{Nothing. Bye.}
{212}{}{Enough about that.}

{220}{}{How did you get settled?}
{221}{}{To be honest, your tribesmen are not happy with strangers. Children laugh at my thin physique, and adults shun conversations. You are the only reason that holds back their discontent. But on the other hand, I see interest. Interest in what used to be taboo for your community.}
{222}{}{What technologies do you think should be returned?}
{223}{}{Manual labor is tedious and inefficient. According to my calculations, the aqueduct alone will increase yields by 250% and reduce labor resources by 40%. Unfortunately, the headman does not want to listen to me.}
{224}{}{The villa has so far managed without high technology.}
{225}{}{Yes, but at what cost? Diseases, periodic crop failures, injury hazards and difficult working conditions for the body are only the main troubles that simple pre-war technologies, such as a pump or electric lighting, would help to avoid.}
{226}{}{Do you think the Villa should change?}
{227}{}{This is an unanswered question. It's up to you to live and decide. But someday the flame of civilization will reignite in the south. Will you be able to resist in such a struggle? I doubt. You couldn't even defend yourself against a handful of mercenaries with primitive rifles.}
{230}{}{One of the residents is now lying in a hot delirium. Can you cure him?}
{231}{}{I also had to do a little medicine. I think I can help. But keep in mind that your tribesmen have a negative attitude to pre-war medicine.}
{232}{}{We don't have time to think about such things. Cure him!}
{233}{}{I will try to cure it with my own means.}
{234}{}{Our weather station is damaged. Can you fix it?}
{235}{}{Sure. Meteorology is one of my favorite sciences.}
{236}{}{Then do it.}
{237}{}{However, I'll try it first.}