{110}{}{This clay workshop is an achievement of local technology. There's still some clay left for new dishes.}
{111}{}{The clay workshop is an achievement of local technology. But the last reserves of clay were used up.}
{112}{}{You have made several pieces of tableware. But you weren't allowed anywhere near here before.}
{113}{}{It seems that the Villa traded ceramics with neighboring settlements...}