{110}{}{This well is as old as the Villa itself.}
{111}{}{You lowered a strong rope to the bottom of the well.}
{112}{}{You have already lowered one rope to the bottom of the well. There is no need for the second one.}
{113}{}{Going down to the bottom of the well, you discover a very old hiding place. It looks like someone has hidden forbidden things here.}
{114}{}{That's so unexpected.}
{115}{}{ }
{116}{}{It does not need repair.}