{100}{}{You see Arthur Carrington.}
{101}{}{You see an archaeologist in a torn dirty robe. Despite his shabby appearance, he holds firm.}
{102}{}{Did you want to break into the Vault? So stay here FOREVER!}

{110}{}{And here I would settle down for good.}
{111}{}{The surviving pre-war laboratory? Amazing! And why didn't I know about this place before?}
{112}{}{I wonder if this power plant is still operating?}
{113}{}{Holy saints! These barbarians have settled inside the power plant like bedbugs in an old hotel.}
{114}{}{I can't believe my eyes - the whole valley is littered with the most valuable ancient technologies!}
{115}{}{It looks like the center of a Burial ground. Surely automation has been working since the War.}
{116}{}{These guys don't just read books. Who are they?}

#Before the escape (in the reactor room)
{200}{}{I was expecting rescuers from Phoenix, but who ARE YOU?}
{201}{}{I am a peasant from a Villa. My ancestors are somehow connected with this Vault. And I'm here to find out the details.}
{1201}{}{I'm a peasant from a villa. My ancestors are somehow connected with this Vault. And I'm here to find out the details.}
{202}{}{It's impressive that you managed to get this far. You know, I've heard about this Villa thing. But if you want to know the details, then help me finish my business in this Vault.}
{203}{}{What's your business here?}
{204}{}{So it was you I was talking to on the intercom? Well, your work is impressive. I wish we had crossed paths before.}
{205}{}{Go so far to turn around? Well, no.}
{206}{}{That's exactly what I thought when I led the expedition on its last outing. As you can see, it was a mistake.}
{207}{}{Tell me what happened.}
{208}{}{I don't think this is the right time to talk. I'll tell you everything, but first, you need to finish what you started.}
{209}{}{What are you talking about?}
{210}{}{Now is not the time to talk. Pack your things, we're leaving.}
{211}{}{I totally agree. But first, you need to finish what you started.}
{212}{}{I have to get into the overseer's post. This room is located one level above. Follow there. We shouldn't waste any time. Yes, my name is Arthur Carrington. Glad to meet you.}
{213}{}{Is it really so necessary...}
{214}{}{Okay. But don't be silly.}
#Before the escape (as overseer)
{220}{}{Damn it! Is this a complete failure?}
{221}{}{What happened? You look depressed...}
{222}{}{Hey, are you talking to yourself? I want to know too.}
{223}{}{Protocol zero.}
{224}{}{Protocol... what?}
{225}{}{What the hell is the protocol?}
{226}{}{I suspected it would all end there. Many years of imprisonment brought the overseer out of his mental balance, and he launched a chain of procedures to destroy the Vault. The so-called "protocol zero".}
{227}{}{But some of the equipment works.}
{228}{}{Looks like his plans weren't much more successful than yours.}
{229}{}{Yes, that's right. Obviously, the residents resisted the actions of the overseer and were able to stop some of the procedures. They saved their lives but doomed themselves to years of suffering by becoming... ghosts.}
{230}{}{I think they suffered long before that.}
{231}{}{If we stay here, we'll be one of them.}
{232}{}{Yes... Of course... look, I need to get to the surface. There doesn't seem to be anything of value left here. I see no point in putting myself in further danger. Together we have more chances to break through. Will you help me?}
{233}{}{Let's go. First I'll bring you to the surface.}
{234}{}{Very good. Take command, boss. I am not strong in military affairs, but I will keep an eye on the rear.}
{235}{}{Forward.}

# During the escape
{250}{}{It's not worth staying here.}
{251}{}{Let's move on.}

{260}{}{What can you say about this room?}
{261}{}{This is the reactor level. Once the reactor overheated and caused a spontaneous explosion, destroying part of the level. Fortunately, the rock protects us from its powerful radiation.}
{262}{}{This is the service level. There was a Vault management center and various support services. I would like to see all this splendor of technological progress in its original form.}
{263}{}{Educational center. The library is in electronic form. Amazing ingenuity of our ancestors.}
{264}{}{This is an entertainment hall. But it seems that because of overpopulation, they didn't have parties here, but lived.}
{265}{}{This is the post of the overseer, one might say, a local manager. From here it was possible to control all the Vault systems. Now nothing is working here - it looks like the overseer destroyed the equipment with an emergency pulse explosion.}
{266}{}{This is one of the residential levels. Apart from the bedrooms, there is nothing significant here.}
{267}{}{Another question.}

{270}{}{You saved me. Without you, I could have stayed there forever and become one of those ghosts. You know, after that, I began to look at human life a little differently.}
{1270}{}{You saved me. I could stay there forever and become one of those ghosts. You know, after that, I began to look at human life a little differently.}
{271}{}{Anyway, now you're free and you can help the still alive.}
{272}{}{Just "a little"? It seems that life doesn't teach you anything, Mr. Scientist.}
{273}{}{As you understand, right now I can't repay you in any way. But when I get to Phoenix, I will definitely tell my friends about you in the Cathedral of Fire. You should look there too. But it will be difficult for me to get to Phoenix alone. Maybe we should go together?}
{274}{}{Of course, let's go to Phoenix. Why not?}
{275}{}{Thank you. You're saving me again. If anything, I can carry some things. And I don't mind seeing some interesting places along the way.}
{276}{}{Great. Come on, Arthur.}
{277}{}{Don't try to escape without me.}
{278}{}{I will be happy to accept you into the team. But what about the answers to the questions?}
{279}{}{I heard that there were some problems in the Cathedral. We should hurry up.}
{1279}{}{I heard that there were some problems in the Cathedral. We should hurry up.}
{280}{}{Actually, I'm not on my way. I don't think I'll be in Phoenix anytime soon.}
{281}{}{It's not a big deal. Take me to the nearest settlement, and there I can find my way. If anything, I can carry some things. And I also don't mind seeing interesting places along the way.}
{282}{}{Consider yourself on the team. Come on, Arthur.}
{283}{}{Then you will carry all my things. And don't whine after that. Go ahead!}
{284}{}{Welcome to the team. Can we talk normally now?}

# After escaping
{300}{}{How are you, boss?}
{301}{}{So, let's look at these equations... Oh, did I miss something?}
{302}{}{There are always not enough answers.}
{303}{}{What, do you need wise advice again?}
{304}{}{Are we in Phoenix yet?}
{305}{}{Hey boss, it seems your route isn't accurate enough.}
{306}{}{What do you want?}
{307}{}{My plans have long been thwarted.}
{308}{}{I don't mind talking. But can we dilute them a little with Latin?}
{309}{}{Let's move on, Arthur.}

{310}{}{I don't feel well. It seems to be the effects of poisoning.}
{311}{}{Let... Okay, bend over... And now so... Is that better now?}
{312}{}{Yes... Thanks, Doc.}

#Questions
{320}{}{I have a lot of questions for you.}
{321}{}{Oh, of course. And I have a lot of answers.}
{322}{}{Sure. I will answer any of your questions.}
{323}{}{These answers are enough.}
{333}{}{Another question.}
{334}{}{And where is the city of Phoenix?}
{335}{}{You really don't know? This is strange... Hold out Pip-Boy, I'll show this city on the map.}
{336}{}{Thank you.}

{350}{}{Tell me about yourself.}
{351}{}{Haven't I introduced myself yet? Arthur Carrington, head of the expedition. To some extent, I am a free scientist, if you like.}
{352}{}{Where did you get your education from?}
{353}{}{My parents taught me the basics of writing and computer skills. This is a rarity in our area, so many people in Phoenix used my services. When the cult of fire worshippers took over the city, I had new opportunities for doing science, which I could only dream of before.}
{354}{}{Who were your parents?}
{355}{}{I think they were the descendants of those who came out of the Vault. Although they did not directly talk about it.}
{356}{}{Why did you go on an expedition?}
{357}{}{The fire worshippers were looking for people to scout. Their interests were too much... mercantile. They needed only practically significant things-old equipment, energy sources, and weapons, after all. As a scientist, I looked at things more broadly. The Vault could tell a lot about the Old World and help in the development of the New One. Ancient relics should not be thrown around so recklessly.}

{360}{}{Tell me what happened to the expedition.}
{361}{}{Not the most pleasant topic for conversation. After descending to the Vault, we split into two groups. The first one was supposed to monitor the backup generator, and the second one was supposed to go down to the reactor room with me. After the split, everything didn't go according to plan.}
{362}{}{What happened to your group?}
{363}{}{We went down to the reactor room and began to examine the premises. But there was a trap in one of them. The explosion killed my subordinates and knocked me unconscious. When I woke up, the elevator was lifted up, the electricity was turned off, and the first group did not get in touch.}
{364}{}{What happened to the first group?}
{365}{}{Most likely, the group was attacked by ghosts. You probably know more than me. In any case, the generator could not run out on its own. Obviously, one of the ghosts pulled out the power cells from there and thereby left me trapped.}
{366}{}{I examined the bodies of your group. One of them had a gunshot wound to the head. What do you say?}
{1366}{}{I examined the bodies of your group. One of them had a gunshot wound to the head. What do you say?}
{367}{}{And why did you have to stick your nose in dirty laundry? Yes, it wasn't just me who survived. The second member of the expedition was injured, but taking care of him would have required all my resources. I couldn't afford it.}
{368}{}{It looks more like you were just holding the rear for safety, and you wasted your people.}
{369}{}{Caution allowed me to live up to my age. And it was only here, in the Vault, that I paid the price for letting my ambitions get the better of me. But I had to act decisively because the expedition was under threat - at any moment the cult could stop funding or send me a replacement. I couldn't derail my life's work!}

{370}{}{What do you know about ghosts?}
{371}{}{They are victims of mutations that arose due to a set of conditions after the "zero protocol": poisonous gases and viruses in the air, the use of gas masks, radiation, taking certain medications, and much more. They were in suspended animation for decades until we disturbed them. During this time, their brains have degraded. Only animal instincts remained.}
{372}{}{Have you noticed that I've mutated into something similar too?}
{1372}{}{Have you noticed that I've mutated into something similar too?}
{373}{}{I almost mistook you for a ghost when I met you. Congratulations, you have a long life ahead of you.}

{380}{}{You promised to tell me about the connection between the Vault and the Villa.}
{381}{}{I'm sorry, I lied so you'd have a reason to save my life. I don't know anything about the Villa, or how things from the Vault ended up there. Most likely, a long time ago someone came out of the Vault, and then his things came to you. This is a common thing.}
{382}{}{[Next]}
{383}{}{You'll have to go downstairs and look for something that will give hints of an answer. Here, take an access card, it will allow you to open locked doors.}
{384}{}{You shouldn't have lied to me. This is the first and last warning.}
{385}{}{Thank you at least for that. We need to see what's there.}
{386}{}{Go back to this damned place? Oh, this is going to be an ordeal.}

{390}{}{What are you going to do now?}
{391}{}{I'll make a big report and try to get some more resources from the cult to complete the expedition. I need a reliable guard to clear the ghost Vault and a new set of slaves.}
{392}{}{Clear. Do as you want.}
{393}{}{A lot of people died because of you and your ambitions. Do you want to continue?}
{394}{}{As cruel as it may sound, the lives of mercenaries and slaves were less valuable than the legacy of ancient times. Just think what prospects will open up if we return Phoenix to its forgotten technologies!}
{395}{}{Did technology help the local ghosts?}
{396}{}{No, they didn't help. So what? This is nothing more than the stupidity of one particular person in the overseer's Vault.}
{397}{}{Okay. Whatever you say.}
{398}{}{Technology has not saved the residents of the Vault. On the contrary, they were condemned to eternal suffering.}
{399}{}{What do you mean by that?}
{400}{}{Technology will not save a rotten society. But they will generate wars around ancient artifacts.}
{401}{}{Hmm... I didn't think about it. The Phoenix Society is undergoing a reformation thanks to the cult of Fire. The introduction of ancient technologies gave a lot of benefits, but at the same time divided the population... Perhaps I should read more books on sociology.}
{402}{}{Just thinking out loud. Forget it.}
{403}{}{This is the end of our conversation. So far.}
{404}{}{It's good that we have reached an understanding. And now to answer other questions.}

#PARTY
{450}{}{I need you. Come with me.}
{451}{}{No, boss. Too many people. This prevents me from concentrating on thinking about my grand plan.}
{452}{}{But this is not good.}
{453}{}{It's time for us to break up. Then you will go alone.}
{454}{}{Are you going to leave me like this after all our adventures? Okay. I'm going to stay here and read a pocketbook until you change your mind.}
{455}{}{Be.}
{456}{}{You can take off your armor.}
{457}{}{Thank you, Chief. It's too stuffy in there.}
{458}{}{That's all.}
{459}{}{Hide your weapon.}
{460}{}{Hmm. Whatever you say, boss.}
{461}{}{That's it.}
{462}{}{Maybe I'll come back for you later.}
{463}{}{We have reached Phoenix. That was what needed to be proved. You know, if there were people like you on the expedition, I wouldn't have failed.}
{464}{}{What are you going to do?}
{465}{}{I have a lot to do. First, you need to meet with the customer and report on the results. It will take a couple of days. Until then, please don't bother me.}
{466}{}{Okay. We'll meet here in two days.}
{467}{}{Greetings to my savior.}
{468}{}{Bye, Arthur.}

{470}{}{And here is my savior. Glad to see you.}
{1470}{}{And here is my savior. It's good to see you.}
{471}{}{How was your report received? You're not beaming with happiness.}
{472}{}{Now no one needs the results of my many months of work. The Temple of Fire is destroyed. I don't know what happened there, but the fire worshippers are now in exile, and no one needs a scientist like me anymore.}
{473}{}{Are you sure?}
{474}{}{There is one clue. In the Cathedral, I came across scant reports about the city of scientists somewhere in the south, but there is too little information about it. I want to go there to find happiness at last. If you're going that way, let me know.}
{475}{}{It must be a difficult path. I'll think about it.}
{476}{}{Yes, by the way, I managed to snatch some Radawaye and stimpacks in the laboratory. Take it as a token of gratitude for the rescue.}
{477}{}{See you later.}
{480}{}{Is this the place you were talking about?}
{481}{}{It looks like it! The city of science and progress. A real miracle in the middle of the desert. Even the air smells different here. Just what I need for my research.}
{482}{}{So it's time to break up?}
{483}{}{Yes, check our backpacks, do I have any of your things left? I'm going to the Followers of the Apocalypse for instruction.}
{484}{}{[Next]}
{485}{}{I was glad to meet you. I never thought that a man from the wastelands would teach me the most important thing - to appreciate people's lives. I used to put everything in the glory of science. It's time to do something really useful.}
{486}{}{Goodbye, Arthur.}
{487}{}{The customer was extremely dissatisfied with the results of my many months of work. I was reprimanded for waste and inefficiency and even offered to be burned at the stake. But how could I know that there would be these "ghosts" in the Vault? And that the Vault itself is so messed up? The expenses of the expedition were not justified. That's what they say. Damn lid-lovers! It looks like my scientific career will come to an end here.}