{100}{}{This is the library terminal.}
{101}{}{This terminal could give access to an electronic library. But it's not working right now.}

{110}{}{This terminal could give access to an electronic library. But it's not working right now.}
{111}{}{You can access the electronic library through this terminal.}
{112}{}{You managed to restore the library terminal.}
{113}{}{The library terminal is turned off. To start it, the power supply should be restored.}