{102}{}{*Hissing*}
{103}{}{Talking on the intercom during a fight is extremely difficult.}

#The first dialog
{200}{}{ (a weak but encouraging voice comes from the intercom) Reception! Can you hear me? Who's in touch?}
{201}{}{I'm just passing by.}
{202}{}{Eh? Are you a talking box to me? I'm just passing by here.}
{203}{}{Damn it. I was expecting help from Phoenix... But maybe it's better this way. Tell me, wanderer, why are you here? Are you looking for something?}
{1203}{}{Damn it. I was expecting help from Phoenix... But maybe it's better this way. Tell me, wanderer, why are you here? Are you looking for something?}
{204}{}{It seemed to me that here I would find the prehistory of my people. There were things from Vault 27 in the Villa. This must be the place.}
{205}{}{Villa... Yes, I know what you're talking about. And I know how to help you.}
{206}{}{Great! Tell me where to go?}
{207}{}{Take your time. Help me first. I'm stuck on the lower level and I won't get out of here myself. All you need is to find a backup generator on the residential level and start it.}
{208}{}{Answers first. I have a lot of questions.}
{209}{}{Okay, I'll try.}

#Second dialog
{210}{}{It's good that you're still here. But hurry up before I suffocate.}
{211}{}{I have a lot of questions.}
{212}{}{End of communication.}
{213}{}{There is another question.}

{214}{}{Great. If necessary, use the intercom to contact me.}
{215}{}{Before the connection.}
{216}{}{The intercom is not responding.}
{217}{}{[Leave]}

#Answers
{220}{}{Ask.}
{221}{}{Who are you?}
{222}{}{Arthur Carrington, head of the expedition. We investigated this Vault for useful resources. Surely you have already come across our things near the tunnel.}
{223}{}{How long can you hold out in the trap?}
{224}{}{It's hard to say. I have food and water supplies. The problem with the air was solved, but it won't be for long.}
{225}{}{Why does the intercom work if there is no power in the Vault?}
{226}{}{The ancient engineers were smart. They connected the intercoms to the components of a conventional walkie-talkie and provided long-lived batteries. Just in case like now.}
{227}{}{What do I need to know before going down to the Vault?}
{228}{}{It's dark here, there's no energy. The air is poisoned, but gas masks will solve this problem. And take the weapon... just in case.}
{229}{}{Why are there weapons here?}
{230}{}{I'm just offering to be safe. This is an old Vault. I don't know all his secrets myself.}
{231}{}{You didn't tell me anything about those horrible people in gas masks!}
{232}{}{Ghosts? Shadows of the past. We woke them up when we went downstairs. It's hard to believe they're still alive... if they can be considered alive at all.}
{233}{}{So you knew!}
{234}{}{I'm sorry, I should have warned you, but then I could have lost my only hope of salvation. Don't you understand?}

#Rescue
{240}{}{So what do I need to do?}
{241}{}{Find a backup generator on the residential level and start it up. If you need a spare battery, it can be in stock at a lower level.}
{242}{}{I see you've managed to start the generator. Now find a ventilation system somewhere on the same level and try to start it. This should purify the air from harmful gases.}
{243}{}{Is the air cleared? Great! Go down to the lower level and find the second elevator in the control center. I'll be waiting there. If something happens along the way, contact me on the intercom.}
{244}{}{We have a problem. On the way to the elevator, a crowd of some distraught people gathered!}
{245}{}{We have a problem. A crowd of ghosts gathered on the way to the elevator.}
{246}{}{These are ghosts. You have to be careful with them. We shouldn't take any chances now, it's better not to get into a fight.}
{247}{}{Maybe distract them?}
{248}{}{I thought about it too... Inspect the adjacent rooms and try to run something from the old equipment there, which will create a lot of noise. And try not to get caught by the ghosts.}
{249}{}{Okay.}