{100}{}{Here is Alekhno.}
{101}{}{You see a half-naked man with a crazy look. He brandishes his machete threateningly.}

{110}{}{And die, you creatures!}
{111}{}{Viper house!}
{112}{}{I was kidnapped! I was kidnapped!}
{113}{}{Alex! The Times! Moscow!}
{114}{}{You will report directly to me.}
{115}{}{This will be my answer to the bastards.}
{116}{}{I went here, collected food, didn't touch anyone.}
{117}{}{They're watching me!}
{118}{}{What Mexican scum took the cart?}
{119}{}{Riot and death! Riot and death!}
{120}{}{I'll feed you with a grenade launcher.}
{121}{}{Tu! Murda!}
{122}{}{Monkeys are walking around here, there's a monkey over there.}
{123}{}{Here are the motherfuckers!}
{124}{}{U-u-u!}
{125}{}{I love animals.}