{100}{}{You see Alejo.}
{101}{}{You see a half-naked man with a crazy look. He threateningly waves his machete around.}

{110}{}{Die, bastards!}
{111}{}{Snake!}
{112}{}{I was kidnapped! I was kidnapped!}
{113}{}{Alex! Times! Moscow!}
{114}{}{You will report directly to me.}
{115}{}{This is my answer to these bastards.}
{116}{}{I was walking around, gathering food, not bothering anybody.}
{117}{}{They're watching me!}
{118}{}{What mexican scum took the cart?}
{119}{}{Death! Rebellion! Death! Rebellion!}
{120}{}{Hungry for more bullets?}
{121}{}{Twu! Merda!}
{122}{}{The monkeys keep walking in a circle. Look at that one- it looks funny.}
{123}{}{Bastards!}
{124}{}{Ou-u-u!}
{125}{}{I love animals.}
