{100}{}{There's a patrolman in front of you.}
{101}{}{You see a warrior of the Brotherhood of Steel.}

{110}{}{What are you doing in this desert?}
{111}{}{The nearest city is in the northeast.}
{112}{}{These lands are under the protection of the Brotherhood.}
{113}{}{We won't touch you as long as you accept our terms.}

{120}{}{Welcome back, brother.}
{121}{}{How's the road, brother?}
{122}{}{What's new on the wastelands, brother?}
{123}{}{Sorry, but we can't escort you to the base.}

{1120}{}{Welcome back, sister.}
{1121}{}{How's the road, Sister?}
{1122}{}{What's new on the wastelands, Sister?}
{1123}{}{Sorry, but we can't escort you to the base.}