{100}{}{You see a patrolman.}
{101}{}{You see a Brotherhood of Steel warrior.}

{110}{}{What are you doing in this desert?}
{111}{}{Closest settlement is to the north-east.}
{112}{}{These lands are under Brotherhood protection.}
{113}{}{We won't bother you, so long as you accept our terms.}

{120}{}{Welcome back, brother.}
{121}{}{How are the travels, brother?}
{122}{}{What's new out there in the wasteland, brother?}
{123}{}{Sorry, but we can't escort you back to base.}

{1120}{}{Welcome back, sister.}
{1121}{}{How are the travels, sister?}
{1122}{}{What's new out there in the wasteland, sister?}
{1123}{}{Sorry, but we can't escort you back to base.}
