#Regular random lines
#Important: leave the empty lines!
{110}{}{Moo-o}
{111}{}{M-moo-o}
{112}{}{*Snort*}
{113}{}{Moo-o-o}
{114}{}{   }
{115}{}{   }
{116}{}{   }
{117}{}{   }
{118}{}{   }
{119}{}{   }

#Lines if player character has low Intelligence
{120}{}{*Snort*}
{121}{}{*Heh-heh*}
{122}{}{Hey, dude.}
{123}{}{Two heads are better.}
{124}{}{Can you hear us?}
{125}{}{He's reading our thoughts.}
{126}{}{He's... eavesdropping on us?}
{127}{}{We know your thoughts.}
{128}{}{I think he's high.}
{129}{}{I'm not talking with that one.}
{130}{}{If he can hear us, that's bad news.}
{131}{}{Let him go.}
{132}{}{But he could tell the others.}
{133}{}{No one will believe him, anyway.}
{134}{}{Right. We'll just ignore him.}
{135}{}{Another drifter.}
{136}{}{Isn't he... dangerous?}
{137}{}{Hey, quiet.}
{138}{}{He can't hear us.}
{139}{}{Stop. This is dangerous.}
{140}{}{Right. Everyone, stop thinking.}
{141}{}{I pity that human.}
{142}{}{Humans are so fragile.}
{143}{}{Humans are so savage.}
{144}{}{I still can't understand why they need conflict.}
{145}{}{No contacting that one.}
{146}{}{One of them could listen in on us.}
{147}{}{He probably thinks it's all in his imagination.}
{148}{}{Silly human.}
{149}{}{I'm thinking about the eternal things.}
{150}{}{Heh! That creature has a woefully low intellect.}
{151}{}{It looks as if they were lobotomized.}

{1120}{}{*Snort*}
{1121}{}{*Heh-heh*}
{1122}{}{Hey, you.}
{1123}{}{Two heads are better.}
{1124}{}{Can you hear us?}
{1125}{}{She's reading our thoughts.}
{1126}{}{She's... eavesdropping on us?}
{1127}{}{We know your thoughts.}
{1128}{}{I think she's high.}
{1129}{}{I'm not talking with that one.}
{1130}{}{If she can hear us, that's bad news.}
{1131}{}{Let her go.}
{1132}{}{But she could tell the others.}
{1133}{}{No one will believe her, anyway.}
{1134}{}{Right. We'll just ignore her.}
{1135}{}{Another drifter.}
{1136}{}{Isn't she... dangerous?}
{1137}{}{Hey, quiet.}
{1138}{}{She can't hear us.}
{1139}{}{Stop. This is dangerous.}
{1140}{}{Right. Everyone, stop thinking.}
{1141}{}{I pity that human.}
{1142}{}{Humans are so fragile.}
{1143}{}{Humans are so savage.}
{1144}{}{I still can't understand why they need conflict.}
{1145}{}{No contacting that one.}
{1146}{}{One of them could listen in on us.}
{1147}{}{She probably thinks it's all in her imagination.}
{1148}{}{Silly human.}
{1149}{}{I'm thinking about the eternal things.}
{1150}{}{Heh! That creature has a woefully low intellect.}
{1151}{}{It looks as if they were lobotomized.}

