#The usual random cues
#Important: leave the lines with spaces!
{110}{}{Mu-u}
{111}{}{M-m-u}
{112}{}{*Snort*}
{113}{}{Mu-u-u}
{114}{}{   }
{115}{}{   }
{116}{}{   }
{117}{}{   }
{118}{}{   }
{119}{}{   }

#Replicas with low Intelligence GG
{120}{}{*Snort*}
{121}{}{*Hee-hee*}
{122}{}{Hey, dude.}
{123}{}{Two heads are better.}
{124}{}{Can you hear us?}
{125}{}{He reads our thoughts.}
{126}{}{Is he eavesdropping on us?}
{127}{}{We know your thoughts.}
{128}{}{I think he's high.}
{129}{}{I won't talk to him.}
{130}{}{If he hears us, it's bad.}
{131}{}{Let him go.}
{132}{}{He can tell others.}
{133}{}{No one will believe him.}
{134}{}{That's right, ignore him.}
{135}{}{Another tramp.}
{136}{}{Is he not dangerous?}
{137}{}{Hey, you, shut up.}
{138}{}{He can't hear us.}
{139}{}{It's dangerous, stop it.}
{140}{}{So, stop thinking.}
{141}{}{I feel sorry for this man.}
{142}{}{People are so fragile.}
{143}{}{People are so wild.}
{144}{}{I don't understand why people need enmity.}
{145}{}{No contact with this creature.}
{146}{}{We may be overheard.}
{147}{}{He thinks he's imagining it.}
{148}{}{Stupid man.}
{149}{}{I'm thinking about the eternal.}
{150}{}{Ha! This creature has a depressingly low intelligence.}
{151}{}{It seems that this unfortunate creature was lobotomized.}

{1120}{}{*Snort*}
{1121}{}{*Hee-hee*}
{1122}{}{Hey, dude.}
{1123}{}{Two heads are better.}
{1124}{}{Can you hear us?}
{1125}{}{She reads our thoughts.}
{1126}{}{Is she eavesdropping on us?}
{1127}{}{We know your thoughts.}
{1128}{}{I think she's high.}
{1129}{}{I won't talk to her.}
{1130}{}{If she hears us, it's bad.}
{1131}{}{Let it go on.}
{1132}{}{She can tell others.}
{1133}{}{No one will believe her.}
{1134}{}{That's right, ignore her.}
{1135}{}{Another tramp.}
{1136}{}{Is she not dangerous?}
{1137}{}{Hey, you, shut up.}
{1138}{}{She can't hear us.}
{1139}{}{It's dangerous, stop it.}
{1140}{}{So, stop thinking.}
{1141}{}{I feel sorry for this little man.}
{1142}{}{People are so fragile.}
{1143}{}{People are so wild.}
{1144}{}{I don't understand why people need enmity.}
{1145}{}{No contact with this creature.}
{1146}{}{We may be overheard.}
{1147}{}{She thinks she's imagining it.}
{1148}{}{Stupid human child.}
{1149}{}{I'm thinking about the eternal.}
{1150}{}{Ha! This creature has a depressingly low intelligence.}
{1151}{}{It looks like this unfortunate creature has been lobotomized.}