{100}{}{You see a cannibal.}
{101}{}{You see a strange man. They smile while examining you. It's not a good smile.}

{110}{}{You're going to make for a fine meal for my whole family.}
{111}{}{Your buttocks will make for a great stake.}
{112}{}{You're going to be my lunch.}
{113}{}{Share your meat with a poor, starving man!}
{114}{}{I could live off your tender meat for several months.}
{115}{}{I'll leave your buttocks for the last. First, I'll eat the eyes and the brain.}
{116}{}{Do you have any idea how many people your meat could feed?}
{117}{}{Sorry, but I'm going to eat you. It's nothing personal.}
{118}{}{It's nothing personal. I'm just really, really hungry.}
{119}{}{Don't be afraid, I don't bite... not until I roast you on the fire.}
