{100}{}{You see a cannibal.}
{101}{}{You see a strange man. He smiles unkindly, looking at you.}

{110}{}{Your body can feed my whole family.}
{111}{}{Your buttocks will make a great steak.}
{112}{}{You will be my lunch.}
{113}{}{Share your meat with the hungry!}
{114}{}{I can live on your juicy meat for several months.}
{115}{}{I'll eat your guts last. And the eyes and brain will go first.}
{116}{}{Do you have any idea how many people could feed on your meat?}
{117}{}{Excuse me, but I'm going to have a snack with you. Nothing personal.}
{118}{}{Nothing personal. I just really want to eat.}
{119}{}{Don't be afraid, I don't bite... until I roast you properly on the fire.}