{100}{}{Here is a merchant.}
{101}{}{You see the head of the caravan.}
{102}{}{Put away your weapon if you really have peaceful intentions.}

{200}{}{Hello, traveler. Lately it has become increasingly difficult to get from one place to another and not be ambushed at the same time.}
{1200}{}{Hello, traveler. Lately it has become increasingly difficult to get from one place to another and not be ambushed at the same time.}
{201}{}{Hmm. There are rumors about a man of your appearance. Unkind rumors.}
{202}{}{Thank God you're with us! I'm glad our paths crossed. What can I do for such a respected person?}
{203}{}{I'm just passing by.}
{204}{}{I need to restock. Do you have any goods left?}
{205}{}{This is my favorite craft. Look, choose.}
{206}{}{So, so...}
{207}{}{Have a good trip.}
{208}{}{Thank you.}

{210}{}{Now what can I do for you?}
{211}{}{Bye.}