{100}{}{You see a guard.}
{101}{}{You see a caravan guard.}

{110}{}{I hope we won't encounter anyone else afterward.}
{111}{}{It'll be great to get the caps right after reaching our destination.}
{112}{}{I hope the bar will be open when we arrive.}
{113}{}{It'll be great to eat some real food again.}
{114}{}{This journey was exhausting.}
{115}{}{The brahmin move far too slowly when they're carrying stuff.}
