{100}{}{There is a guard in front of you.}
{101}{}{You see one of the caravan guards.}

{110}{}{I hope we won't meet anyone else on the way.}
{111}{}{It will be great to get the bottlecaps right after completing the path.}
{112}{}{I hope the bar will still be open when we get there.}
{113}{}{It would be nice to finally eat real food.}
{114}{}{This journey has been tedious.}
{115}{}{Brahmins are too slow under load.}