{100}{}{You see a trader.}
{101}{}{You see a caravan leader.}
{102}{}{Put away the weapon, if you really do have peaceful intentions.}

{200}{}{Greetings, wanderer. Lately, it's becoming harder and harder to get from one place to another without being ambushed at some point.}
{1200}{}{Greetings, wanderer. Lately, it's becoming harder and harder to get from one place to another without being ambushed at some point.}
{201}{}{Hm. There are rumours about a person with your appearance. They aren't good rumours.}
{202}{}{Thank god you're here! It's great that our paths crossed. How can I help such a respected person as you?}
{203}{}{I'm just passing by.}
{204}{}{I need to resupply. Do you have any goods left?}
{205}{}{I have many supplies with me. Go take a look.}
{206}{}{Let's see...}
{207}{}{Good luck.}
{208}{}{Thanks.}

{210}{}{What can I do for you now?}
{211}{}{Bye.}
