{100}{}{Here is a farmer.}
{101}{}{You see a man with overworked hands. He is carrying a bag of things.}
{102}{}{First, let's put away the weapons. OK?}

{200}{}{Hello, traveler. I see you're ready to talk, not wave your hands like some. How can I help you?}
{1200}{}{Hello, traveler. I see you're ready to talk, not wave your hands like some. How can I help you?}
{201}{}{Probably nothing. Bye.}
{202}{}{Where are you going?}
{203}{}{I'm going to the nearest settlement to trade. Goods from my farm are snapped up on the fly.}
{204}{}{And what are you selling?}
{205}{}{I have a surplus crop. I want to exchange it for something useful that I can't get on my own.}
{206}{}{Can we trade right here?}
{207}{}{Why not? It will be easier for me.}
{208}{}{Perhaps another time.}
{209}{}{Let's see what you have.}

{210}{}{Well, great. We have to go.}
{211}{}{Bye.}
{212}{}{Hmm, I've seen you somewhere... Hey! It's you the Rangers are looking for, isn't it? I don't know what your problems are with them, and I don't want to know. Just go your own way.}
{213}{}{Bye.}
{214}{}{Just tell me one more time...}
{215}{}{Hmm, I've seen you somewhere... Hey! It's you the Rangers are looking for, isn't it? Don't worry, I won't turn you in. They're looking for me too, heh-heh.}
{216}{}{That's good. And where are you going?}