{100}{}{You see a farmer.}
{101}{}{You see a man with work-weary hands. He's carrying a bag on his back.}
{102}{}{Let's put away our weapons first, okay?}

{200}{}{Hello, wanderer. I see that you're willing to talk, rather than wave hands around, like others. How can I help you?}
{1200}{}{Hello, wanderer. I see that you're willing to talk, rather than wave hands around, like others. How can I help you?}
{201}{}{I don't think you can. Bye.}
{202}{}{Where are you heading?}
{203}{}{I'm going to the nearest settlement, to trade. The goods from my farm are bought up on the fly.}
{204}{}{What kind of goods are you selling?}
{205}{}{I have some food. I want to exchange it for valuable things I can't get on my own.}
{206}{}{Maybe we could exchange right here?}
{207}{}{Why not? It'd be easier for me.}
{208}{}{Another time, maybe.}
{209}{}{Let's see what you have.}

{210}{}{Great. It's time for me to go.}
{211}{}{Bye.}
{212}{}{Hm, I saw you somewhere... Hey! Aren't you the one the Rangers are looking for? I don't know what problems you have with them, and I don't want to know, okay? Just go.}
{213}{}{Bye.}
{214}{}{You say that to me one more time, you're going to regret it...}
{215}{}{Hm, I saw you somewhere... Hey! Aren't you the one the Rangers are looking for? Don't worry, I'm not going to give you up or anything. They're looking for me, too. Heh-heh.}
{216}{}{Great. Where are you heading?}
