{100}{}{Here is a hermit.}
{101}{}{You see an overgrown man in dirty rags. I wonder how many years he hasn't washed?}
{102}{}{Threaten? Wah!}

{200}{}{Hmm-m... It's been a long time since I've talked to anyone. The language is heavy.}
{201}{}{I don't want to talk to anyone either. I suggest we disperse.}

{210}{}{It was good to talk. Now go away. I'm tired.}
{211}{}{Talking makes my head hurt. Go away.}
{212}{}{I'm already talking today. That's enough.}
{213}{}{Bye.}

{220}{}{Why are you a hermit?}
{221}{}{Want to leave. One. Peace.}
{222}{}{But still - are there any settlements nearby?}
{223}{}{Hermosillo is there. (he points with his hand) Don't walk. Dangerous.}
{224}{}{Toussaint is there. (he points with his hand) Don't walk. Dangerous.}
{225}{}{Maybe you have something to exchange?}
{226}{}{Okay, here's what I have.}
{227}{}{Perhaps it's time for us to disperse.}
{228}{}{Santa Ana is there. (he points with his hand) A good place.}