{100}{}{You see a hermit.}
{101}{}{You see a hairy man in dirty rags. You wonder when was the last time he washed.}
{102}{}{Threat? Bah!}

{200}{}{Hmm-m... Me no talk with anyone for long time. Tongue heavy.}
{201}{}{I don't want to talk to anyone, either. I suggest we go our separate ways.}

{210}{}{It was good talking. Now go. Me tired.}
{211}{}{Talk makes head hurt. Go.}
{212}{}{Me already talk today. Enough.}
{213}{}{Bye.}

{220}{}{Why do you live like this?}
{221}{}{Want to go. Alone. Calm.}
{222}{}{Still - are there any settlements nearby?}
{223}{}{Hermosillo - there. (shows location) No go. Danger.}
{224}{}{Two Sun - there. (shows location) No go. Danger.}
{225}{}{Perhaps we could exchange things?}
{226}{}{Okay, here is what me have.}
{227}{}{I think we should go our separate ways.}
{228}{}{Santa Ana - there. (shows location) Good place.}
