{100}{}{You see a civilian.}
{101}{}{You see a dirty, emaciated person.}

{110}{}{°Por favor, no nos ataquen!}
{111}{}{°No queremos problemas!}
{112}{}{Estamos buscando un nuevo hogar.}
{113}{}{øYa hemos llegado?}
{114}{}{Quiero dormir.}
{115}{}{Tü eres aventurero, øNo?}
{116}{}{Ya estamos hartos de estos tiranos y guerrilleros.}
{117}{}{Hay bandidos por todas partes.}
{118}{}{°Dêjanos en paz!}
{119}{}{No tenemos nada de valor.}

{210}{}{You're not going to attack us, right?}
{211}{}{We just want to lead peaceful lives.}
{212}{}{We're looking for a new home, where we can begin a new life.}
{213}{}{Are we there yet?}
{214}{}{I want to sleep.}
{215}{}{You're adventurers, right?}
{216}{}{Enough of these tyrants and warlords.}
{217}{}{The damn bandits are everwhere.}
{218}{}{Leave us alone!}
{219}{}{We have nothing to steal.}
