{100}{}{You see a civilian.}
{101}{}{You see a dirty, emaciated man.}

{110}{}{Por favor, no nos ataquen!}
{111}{}{No queremos problemas!}
{112}{}{Estamos buscando un nuevo hogar.}
{113}{}{Ya hemos llegado?}
{114}{}{Quiero dormir.}
{115}{}{Tu eres aventurero, No?}
{116}{}{Ya estamos hartos de estos tiranos y guerrilleros.}
{117}{}{Hay bandidos por todas partes.}
{118}{}{Dêjanos en paz!}
{119}{}{No tenemos nada de valor.}

{210}{}{You won't attack us, will you?}
{211}{}{We just want a peaceful life.}
{212}{}{We are looking for a new home to start life anew.}
{213}{}{Are we there yet?}
{214}{}{I want to sleep.}
{215}{}{You're adventurers, aren't you?}
{216}{}{We've had enough of these tyrants and warriors.}
{217}{}{Damn bandits everywhere.}
{218}{}{Leave us alone!}
{219}{}{We have nothing to steal}