{100}{}{Here is a traveler.}
{101}{}{You see an overgrown man in a dirty, worn jacket with a sawn-off belt. He looks warily in your direction.}

{200}{}{Don't get too close. My dog is too jealous. Where are you from?}
{201}{}{I'm from a village in Northern Arizona. I was kicked out by bad people. And you?}
{202}{}{I'm from Southern California. Just traveling.}
{203}{}{Do you mind if I ask a couple of questions?}
{204}{}{I see. This is where we will disperse, each in his own direction.}

{210}{}{Do you want to know something? Okay. Speak.}
{211}{}{I think I should go.}
{212}{}{Be careful in these lands. I have often met feral ghouls and huge rats here. Good luck.}
{213}{}{Bye.}

{220}{}{Where are you going?}
{221}{}{Nowhere in particular. I just want to see the world. Surely there is a place somewhere that has not yet been spoiled by War or human greed. Well, if there is no such thing, you will have to go back and build a new house.}
{222}{}{What's the news from California?}
{223}{}{There has been unrest there in recent years. The army of super mutants is defeated, the ghouls of the Necropolis migrate to the south, and a new round of trade wars has begun in the Hub. More and more people are leaving in search of new places to live because the Los Angeles neighborhood is crowded.}
{224}{}{Why do you need a dog?}
{225}{}{I got stuck on the road. At first I thought to roast her on the fire. But then it turned out that the dog is a lot of use on the way.}
{226}{}{How about an exchange?}
{227}{}{OK. Let me see what you have.}
{228}{}{Do you know the nearest settlements?}
{229}{}{I was told that in the east there is a continuous barren wasteland. I'm even surprised that I met you. However, I've also heard that Ranger lands stretch to the northeast. The fame of them is known even in California.}
{230}{}{Anything else?}
{231}{}{I was also warned about the ruins of Inferno. They say this is a very dangerous place where only death awaits an ordinary person. Think three times if you decide to go there.}