{100}{}{You see a scavenger.}
{101}{}{You see a man in dirty clothes. He is carrying a very heavy backpack full of junk on his back.}
{102}{}{Hey, why the threats? I didn't do anything to you, no?}

{200}{}{Fine, but keep your hands where I can see them. The bandits don't let me rest. What do you want?}
{201}{}{Why are you asking?}
{202}{}{I'm just passing by.}
{203}{}{Well, I've been looking for valuable things in these ruins for a long time. If you need something, I'll try to find it. For now, this is what I have.}
{204}{}{Understood. Maybe I'll get back to you later.}
{205}{}{Hmm, I saw you somewhere... Hey! You're the one they're looking for in Phoenix, aren't you? Don't worry, I won't give you up. They're looking for me there too.}
{206}{}{Great. What are you doing in such a terrible place?}

{210}{}{Do you need something? I can try to find it, I have a lot of different things with me.}
{211}{}{I have to go.}