{100}{}{You see a scavenger.}
{101}{}{You see a man in dirty clothes. He bends under the weight of a backpack full of various garbage.}
{102}{}{Hey, why these threats? I'm not poking you with a stick, am I?}

{200}{}{Okay, but keep your hands in plain sight. The bandits haven't been giving me any peace lately. What do you need?}
{201}{}{Why are you asking?}
{202}{}{I'm just passing by.}
{203}{}{Well, I've been looking for useful things on these ruins for a long time. If you need something, I'll try to find it. In the meantime, here's what I have.}
{204}{}{I see. Maybe I'll come back to you.}
{205}{}{Hmm, I've seen you somewhere... Hey! They're looking for you in Phoenix, aren't they? Don't worry, I won't turn you in. Someone is looking for me there too.}
{206}{}{That's good. What are you doing in such a terrible place?}

{210}{}{Do you need something? I can search, I have a lot of different things.}
{211}{}{I have to go.}