{100}{}{You see a traveler.}
{101}{}{You see an hairy man in a dirty, shabby jacket with a cut-off on the belt. He's warily looking at you.}

{200}{}{Don't come too close. My dog's too jealous. Where are you from?}
{201}{}{From a village in Northern Arizona. Bad people kicked me out. What about you?}
{202}{}{I'm from Southern California. Just traveling.}
{203}{}{You aren't against me asking a few questions, are you?}
{204}{}{I see. Let's wrap this up right here and continue traveling to our different destinations.}

{210}{}{You want to learn something? Okay. Ask away.}
{211}{}{I think I should go.}
{212}{}{Be careful in these lands. I've met feral ghouls and giant rats. Good luck.}
{213}{}{Bye.}

{220}{}{Where are you heading?}
{221}{}{Nowhere in particular. I want to see the world. There has to be a place somewhere that the Great War and human greed hasn't corrupted. Well, and if there isn't, I'll have to get back and build myself a home.}
{222}{}{What's happening in California?}
{223}{}{The latest years haven't been quiet. The supermutant army is defeated, the Necropolis ghouls are migrating to the south, and a new series of trade wars has begun in the Hub. More and more people are leaving in search of new places to live. Los Angeles and the surrounding areas are overpopulated.}
{224}{}{Why do you keep this dog with you?}
{225}{}{It came to me all by itself, and wouldn't leave. At first, I was thinking of killing it and roasting it on a fire, but then it turned out that dogs are useful for traveling.}
{226}{}{Maybe we could exchange things?}
{227}{}{Sure. Let me see what you have.}
{228}{}{Do you know where the nearest settlements are?}
{229}{}{I was told that the east is just endless barren wastes. I was quite surprised to meet you. Though, I've heard that Ranger territories are to the north-east. They're known even in California.}
{230}{}{Anything else?}
{231}{}{I was also warned about the ruins of Inferno. They say that it's a very dangerous place, and that only death awaits a regular person there. Think thrice before going there.}
