{100}{}{There's a patrolman in front of you.}
{101}{}{You see a private in standard army armor.}

{110}{}{El intruso!}
{111}{}{Veo al intruso!}
{112}{}{Eres gringo, No?}
{113}{}{Bienvenido a Mexico!}
{114}{}{Quê se te perdiÉ aqui?}
{115}{}{Vienes del norte?}
{116}{}{Esto es Nuevo Mexico.}
{117}{}{Esta es nuestra tierra!}
{118}{}{Guarda tus armas!}
{119}{}{No nos caen bien los gringos.}
{120}{}{Quiên eres?}

{210}{}{Violator!}
{211}{}{I see the intruder!}
{212}{}{Are you an American?}
{213}{}{Welcome to Mexico.}
{214}{}{What are you looking for?}
{215}{}{Did you come from the north?}
{216}{}{This is the New Mexico.}
{217}{}{This is our land!}
{218}{}{Put away your weapon.}
{219}{}{We don't need outsiders here.}
{220}{}{Who else are you?}