{100}{}{You see a patrolman.}
{101}{}{You see a private in typical military armor.}

{110}{}{°El intruso!}
{111}{}{°Veo al intruso!}
{112}{}{Eres gringo, øNo?}
{113}{}{°Bienvenido a Mêxico!}
{114}{}{øQuê se te perdiÉ aquö?}
{115}{}{øVienes del norte?}
{116}{}{Esto es Nuevo Mêxico.}
{117}{}{°Esta es nuestra tierra!}
{118}{}{°Guarda tus armas!}
{119}{}{No nos caen bien los gringos.}
{120}{}{øQuiên eres?}

{210}{}{Intruder!}
{211}{}{I see an intruder!}
{212}{}{You an american?}
{213}{}{This is Mexican territory.}
{214}{}{What are you looking for?}
{215}{}{Did you come from the north?}
{216}{}{This is New Mexico.}
{217}{}{This is our land!}
{218}{}{Put away your weapon.}
{219}{}{We don't need outsiders here.}
{220}{}{Who the heck are you?}
