{110}{}{Shall I tell you a joke, Mr. McClellan?}
{111}{}{Good morning, Mrs. McClellan.}
{112}{}{A schmuck like you killed Mrs. McClellan!}
{113}{}{Get away from the McClellan family residence!}
{114}{}{Run, Mrs. McClellan! Head to the basement, and take the children with you!}
{115}{}{I will not allow my masters to be insulted!}
{116}{}{No thing and no creature will prevent my master from walking his dog in the morning.}
{117}{}{Thief detected! Master, do not leave the room, and lock the door!}
{118}{}{You should not have kidnapped my master's dog!}
{119}{}{God, what a blinding flash... Mr. McClellan? What happened to you? Mr. McClellan!}
{120}{}{I cannot bring harm to members of the McClellan family. You are not a member of the McClellan family.}
{121}{}{I was made to follow only the orders of the McClellan family.}
{122}{}{I must ensure my own safety, as I am the property of the McClellan family.}
{123}{}{There will be a drizzle today.}
{124}{}{This plebian blood will serve as a highly effective lubricant!}
{125}{}{Initiating "Deep cleaning" protocol.}
{126}{}{Shall I place that primate's scull near your trophies, Mr. McClellan?}
{127}{}{Shall I serve the offender with garlic or mustard sauce, Mrs. McClellan?}
{128}{}{You will have to face the penalty.}
