{110}{}{Shall I tell you a joke, Mr. McClellan?}
{111}{}{Good morning, Mrs. McClellan.}
{112}{}{A nobody like you killed Mrs. McClellan!}
{113}{}{Away from the McClellan family home!}
{114}{}{Save yourself, Mr. McClellan! Go to the basement and get the kids!}
{115}{}{I will not let my masters offend!}
{116}{}{No one can interrupt my master's dog's morning walk.}
{117}{}{I see a thief! Master, don't leave the room and lock the door!}
{118}{}{You shouldn't have kidnapped my master's dog!}
{119}{}{God, that blinding flash... Mr. McClellan? What's the matter with you? Mr. McClellan!}
{120}{}{I cannot harm members of the McClellan family. But you're not from this family.}
{121}{}{I was created to obey only the orders of the McClellan family.}
{122}{}{I have to take care of my safety because I am the property of the McClellan family.}
{123}{}{It will be a gentle rain today.}
{124}{}{Your blood will be a great lubricant, plebeian!}
{125}{}{Activating the "Deep Cleaning" protocol}
{126}{}{Should I place this primate's skull next to your trophies, Mr. McClellan?}
{127}{}{Shall I serve the intruder with garlic or mustard sauce, Mrs. McClellan?}
{128}{}{You'll have to pay a fine.}