{100}{}{You see a ghoul.}

{110}{}{How old are you?}
{111}{}{We've traveled a long way. From Necropolis to the Hub, then from the Hub to San Diego... and now, we're here.}
{112}{}{There's just supermutants and ghouls in San Diego.}
{113}{}{There's a lot of radiation to the north-west.}
{114}{}{Thinking of going to California yourself? You wouldn't survive the mountains. Or the radiation, or the mutants. No way. Don't even try. It's impossible.}
{115}{}{Itching to move, too?}
{116}{}{Those damn ghoul-hating people kicked us from our homes.}
{117}{}{I miss the charred ruins of Necropolis. I lived there for a long time.}
{118}{}{You use caps here, too? Huh. Interesting coincidence.}
{119}{}{That Master guy, he made flying worms and human-dog hybrids. Nobody knows why.}
{120}{}{The Master was overthrown, and his army was defeated.}
{121}{}{I heard a few things about a Vault Dweller. Lucky guy, for sure.}
{122}{}{That Vault Dweller, I hear he only really cared for himself.}
{123}{}{If the Cathedral wasn't destroyed by some smoothskin, we would have never escaped here.}
{124}{}{Have you heard about the Vault Dweller?}
{125}{}{We don't really have a destination in mind.}
{126}{}{There wasn't enough place in San Diego for us.}
{127}{}{Dayglow's to the north-west, but there's no way you're getting there. Trust me.}
{128}{}{Have you seen those ugly, big worms?}
{129}{}{}

{130}{}{Sorry, normie, you can't come with us.}
{131}{}{Seeing a normie in a place like this? Never would have thought it possible.}
{132}{}{Hey, normie, we don't like ghoul-haters around here. Just for the record.}
{133}{}{You normies are always angry at something. Why don't you just relax and enjoy yourselves?}
{134}{}{We don't need normies. We have a certain vibe here, you know.}

{150}{}{Sorry, my rotting friend, but you can't come with us.}
{151}{}{Didn't expect to see another uglie like me in such a place.}
{152}{}{These normies - they all hate us. Wouldn't you agree?}
{153}{}{Normies kick you out of places, too? We all know exactly how it feels.}
{154}{}{We'd take you with us, but we don't really know where to go.}
