{100}{}{You see a ghoul.}

{110}{}{How old are you?}
{111}{}{We went a long way from the Necropolis to the Hub, and then from the Hub to San Diego... And here we are.}
{112}{}{There are only super mutants and ghouls in San Diego right now.}
{113}{}{There is a continuous band of radiation in the northwest.}
{114}{}{You can't go to California this way because of the mountains, mutants, and radiation.}
{115}{}{What, too, is not sitting still?}
{116}{}{The damn racists just kicked us out of our homes.}
{117}{}{I miss the burnt ruins of my native Necropolis.}
{118}{}{Do you also use caps? A strange coincidence.}
{119}{}{The creator for some reason bred flying worms and crossed people with dogs.}
{120}{}{The Creator is overthrown, and his army is defeated.}
{121}{}{I don't know who this Guy was, but he was damn lucky.}
{122}{}{The Vault-seeker cared only about himself.}
{123}{}{If one smooth-skinned man hadn't destroyed the Cathedral, we wouldn't have escaped here.}
{124}{}{Do you know about the Vault-seeker?}
{125}{}{We wander wherever we look.}
{126}{}{There wasn't enough room for us in San Diego.}
{127}{}{The Dayglow is in the northwest, but you can't get there.}
{128}{}{Have you come across these ugly giant worms?}
{129}{}{}

{130}{}{I'm sorry, normie, but you can't come with us.}
{131}{}{I never I would see normies here.}
{132}{}{Hey, normie, we don't like racists here. But it is, by the way.}
{133}{}{You normies are always unhappy. Relax and enjoy life.}
{134}{}{We don't need normies in the team. We have a special atmosphere here, you know.}

{150}{}{Sorry, my rotting friend, but you can't come with us.}
{151}{}{I never thought to see a freak like me here.}
{152}{}{These normies are all racists. Don't you find it?}
{153}{}{Are you being chased away by the normies too? This is so familiar to us.}
{154}{}{We'd take you with us, but we don't know where to go.}