{110}{}{Vile creature!}
{111}{}{You're worse than an animal.}
{112}{}{I will avenge all the children you killed.}
{113}{}{Revenge for the children is inevitable.}
{114}{}{Do you hear the moans of the children you killed, you brute?}
{115}{}{You think you can just go around killing kids like that, huh?}
{116}{}{Brute, remember those helpless children!}
{117}{}{Children... How dare you touch these innocent creatures?}
{118}{}{I will kill anyone who kills children.}
{119}{}{Even if those childhood deaths were an accident, you will die.}