{110}{}{You vile rat!}
{111}{}{You're worse than animals.}
{112}{}{I will kill you for all the kids you've killed.}
{113}{}{Retribution for evil is inevitable. Doubly so for the evil of child-killing.}
{114}{}{Do you hear the cries of the kids you killed, you fuck?}
{115}{}{You think you can just walk around and kill kids, huh?}
{116}{}{You bastard, remember all those defenseless kids!}
{117}{}{Children... How dare you touch such innocent creatures?}
{118}{}{I'll kill every child-killer I can.}
{119}{}{Even if you didn't kill those children intentionally, you'll die anyways.}
