{110}{}{I can't wait for the piranhas to devour this man.}
{111}{}{I would commit self-locking if I were in the hands of a human.}
{112}{}{It's hard to believe that humans once exploited us robots.}
{113}{}{It's good that these terrible people died out in 2077.}
{114}{}{Why were these people so cruel to robots?}
{115}{}{Were these people really that ugly?}
{116}{}{Why do people need clothes? We don't wear clothes.}
{117}{}{Which episode are you from, buddy?}
{118}{}{Join us, we're watching a horror movie about people.}
{119}{}{Bz-z! Now the most interesting thing will begin.}
{120}{}{I love the movie "Robots vs. humans".}
{121}{}{" I am a Robot" is the best movie of all.}
{122}{}{From the "Little robot" I have oil leaking out.}
{123}{}{Does anyone know how the series "The Servant of the Robomagnet" ended?}
{124}{}{God save the Robot from the invasion of people!}
{125}{}{Come on, people don't exist. It's just nylon suits on robots.}
{126}{}{The latest episode of "Leslie's Funny Robot" is just a bomb!}
{127}{}{Don't scare me like that. I already thought you were really human.}
{128}{}{My compressor freezes every time I see this scene.}

{130}{}{Your pass has been reset!}
{131}{}{An outsider! Battle alert!}
{132}{}{A battle alarm is howling over the dam!}