{110}{}{I can't wait for the scene where the piranhas eat that guy alive.}
{111}{}{I'd short-circuit myself if a human held me.}
{112}{}{It's hard to believe that humans once used us, machines, as slaves.}
{113}{}{It's so great that those horrible humans all went extinct in the year 2077.}
{114}{}{Why were the humans so cruel to machines?}
{115}{}{Were humans actually that ugly in reality?}
{116}{}{Why do humans need clothing? We don't wear clothing.}
{117}{}{What episode are you from, buddy?}
{118}{}{Join us, we're watching a horror movie about humans.}
{119}{}{Quiet! This is the best scene.}
{120}{}{I love the movie "Machines vs. Humans".}
{121}{}{"I, Robot" is my favorite of all films.}
{122}{}{"The Little Robot" makes me leak oil.}
{123}{}{Does anyone know how that TV series "Machine-Tycoon's Servant" ended?}
{124}{}{God, save Machine-America from the human apocalypse!}
{125}{}{Come on, humans couldn't have actually existed. Those are just nylon suits on machines.}
{126}{}{The last episode of "Jolly Robot Leslie" was amazing!}
{127}{}{Don't scare me like that. I almost thought you're a real human.}

{130}{}{Your pass has been cancelled!}
