{110}{}{Oh no, I've been avoiding people for 90 years. Your appearance completes my mission. I don't need to exist anymore.}
{111}{}{I'm a Shibot. My goal is to "avoid people." The successful completion period is 90 years.}

{120}{}{I am a Washer. My goal is to avoid people.}
{121}{}{The deadline for successful completion of the goal is 90 years.}
{122}{}{Your appearance completes my mission. This is unacceptable.}
{123}{}{No one must know that my mission has failed.}
{124}{}{I will erase you from my memory.}
{125}{}{I've been successfully avoiding people for 90 years. But you interrupt my task.}
{126}{}{You're a hindrance to my main goal.}
{127}{}{There's no point running away now.}
{128}{}{I'm tired of running away from people.}
{129}{}{I want to get closer to you. But this is forbidden.}