{110}{}{Oh no. I have successfully avoid humans for 90 years. Your arrival concludes The Mission. I have no reason to exist any longer.}
{111}{}{I am ShyBot. My Mission is to "avoid humans". Mission has been successfully followed for 90 years.}

{120}{}{I am ShyBot. My Mission is to avoid humans.}
{121}{}{Mission has been successfully followed for 90 years.}
{122}{}{Your arrival concludes The Mission. This cannot be allowed.}
{123}{}{No one must know that I have failed The Mission.}
{124}{}{I will erase you from my memory.}
{125}{}{I have been successfully avoiding humans for 90 years. You interfere with The Mission.}
{126}{}{You present a problem for The Mission.}
{127}{}{No point running away now.}
{128}{}{I am tired of running away from humans.}
{129}{}{I want to get close to you. But it is forbidden.}
