{100}{}{Here is a hunter.}
{101}{}{You see a man with a thick beard. He seems pretty exhausted after hunting.}
{102}{}{So, let's put the guns away together, OK?}

{200}{}{Hello, stranger. I rarely see travelers in these lands. At first I thought I was seeing game at all.}
{1200}{}{Hello, stranger. I rarely see travelers in these lands. At first I thought I saw game at all.}
{201}{}{So you're a hunter?}
{202}{}{That's right. There is not much game here, but I have enough to feed myself and trade in a big city.}
{203}{}{And what kind of city?}
{204}{}{Flagstaff? It's a big colony around an old mine. It was founded a few years ago, and during this time the ruins have changed beyond recognition. Go on the high road, you won't miss.}
{205}{}{Thank you. What about the game?}
{206}{}{Can I buy some meat for the road from you?}
{207}{}{Just dried some fresh meat. I can exchange for something useful.}
{208}{}{Maybe another time.}
{209}{}{It was time for me to restock.}
{210}{}{Okay, I have to get on the road before the meat goes bad.}
{211}{}{Be there.}
{212}{}{Hey, isn't that you the guys from the garrison were looking for? Looks like they're really mad at you. You be careful with them there. I don't care, but if they see me with you, then there will be problems with the sale of game.}
{213}{}{Wait. I want to exchange your jerky.}