{100}{}{You see a hunter.}
{101}{}{You see a man with a thick beard. He seems to be exhausted from hunting..}
{102}{}{Let's put our weapons away together, okay?}

{200}{}{Howdy, stranger. I don't see people much around here. At first, I thought you were an animal.}
{1200}{}{Howdy, stranger. I don't see people much around here. At first, I thought you were an animal.}
{201}{}{You're a hunter?}
{202}{}{That's right. There's not too many animals around here, but it's enough for me to feed myself and trade for things I need in the big city.}
{203}{}{What is that city?}
{204}{}{Flagstaff, I think it is called? Big colony around an old mine. It was founded a few years ago, and in that time, the ruins have been changed beyond recognition. Go along the main road, you won't miss it.}
{205}{}{Thanks. What about meat?}
{206}{}{Could I get some meat for my travels?}
{207}{}{I've just finished drying some fresh meat. I can exchange it for something valuable.}
{208}{}{Maybe next time.}
{209}{}{I've just been wanting to resupply.}
{210}{}{I need to go, before the meat goes bad.}
{211}{}{Goodbye.}
{212}{}{Hey, aren't you the person the guys from the garrison have been looking for? It looks like they're really mad at you, be careful with them. I don't really care, but if they see you talking to me, I could have problems selling meat.}
{213}{}{Wait. I want to get some of your dried meat.}
