{110}{}{This container is boarded up. It can be opened only with brute force.}
{111}{}{You do not have enough Strength to use this device.}
{112}{}{You have successfully opened the container.}

{120}{}{You opened the side of the container a little. Press harder.}
{121}{}{A little more and you'll be there!}
{122}{}{Just a little more! The container is almost opened.}
{123}{}{Almost there... Come on, do it!}
{124}{}{That wasn't enough, you need to push a little more.}
{125}{}{Almost done! You need to push a little more.}
