{110}{}{This box is boarded up. It can only be opened by brute force.}
{111}{}{You don't have enough strength to use the tool.}
{112}{}{You managed to open the lid of the box.}

{120}{}{You have only slightly opened the wall of the box. Push harder.}
{121}{}{A little more and you're at the goal!}
{122}{}{Come on! This box is almost broken.}
{123}{}{Almost... Come on, rookie, do it!}
{124}{}{It wasn't enough, we need to push a little more.}
{125}{}{Almost got it! We need to push a little more.}