{100}{}{This can't be done during combat.}
{101}{}{This item is used with hands.}
{102}{}{The cave's walls are jamming the radio signal.}
{103}{}{Something is jamming the radio signal. ZAX, most likely.}

{210}{}{A light static crackling noise comes out from the speaker.}
{211}{}{Listen to general frequencies.}
{212}{}{Listen to the frequencies of Faber's mercenaries.}
{213}{}{Listen to the Ranger frequencies.}
{214}{}{Listen to the Fire-Worshipper frequencies.}
{215}{}{Listen to the Phoenix rebel frequencies.}
{216}{}{Listen to the tinsmith frequencies.}
{217}{}{Listen to Brotherhood of Steel frequencies.}
{218}{}{Listen to the Vault 27 emergency frequency.}
{219}{}{Turn radio off.}

#General frequencies
{230}{}{You only hear white noise.}
{231}{}{Stop listening.}
{232}{}{Looks like I'm too far away from any signals on this frequencies.}
{233}{}{Listen for signals on all frequencies.}
{234}{}{...help! The Jackals caught us in an ambush, immediate help requested!}
{235}{}{I hear you. Where are you?}
{236}{}{Dammit, finally! Listen, the Jackals caught us in an ambush. We can't get out by ourselves. If you help us, we'd find some way to compensate. Here are the coordinates. To the north of Garage City... Be careful and bring as many people as you can... Oh god, they're already here... (signal is gone)}
{237}{}{Hang on, stranger. Whoever you are.}
{238}{}{Hang on, Ranger. Help is already on it's way.}
{239}{}{Reading you loud and clear. Commander Helford sent me to help. What is your location?}

#Rangers
{240}{}{(You hear several boring conversations between patrolmen. Nothing of interest.)}
{241}{}{"...last place they were seen was Garage City." - "They could have died along the way. There were children among the refugees, after all." - "Why'd they even leave Vegas?" - "No idea. I heard rumours of entire wars between clans. And apparently, cannibalism is becoming more and more common there, too. We don't even have our own local problems solved." - "That's exactly right. Maybe it's good that they became lost in the desert. Not as many mouths to feed at the base." - "Be careful. Civilians could hear you." - "I know, I know..."}
{242}{}{"...beats starving, but damn do I miss the times when we could have good meals. When are they going to bring normal meat to the base again?" - "They say San Brahmin has even more problems now. Until the situation is resolved, we'll just have to continue eating that stuff." - "Dammit. My stomach can't take any more of that crap..."}
{243}{}{*static* "...and pushed them into the ruins. Siege lasted 3 days, they ended up surrendering because of the hunger." - "Wow. 3 Days under the sun, that's definitely something." - "Yeah. But they turned out to be completely worthless. They had nothing of value on them..." - *static* - "Cut the chatter! You will share stories strictly in the canteen." - *static* - "As you wish. I'm not used to saying no to ladies." - *static* - "Continue being a smartass and I'll make them cut your rations for the week."}
{244}{}{*static* "...they're heading out. What do we do? Over." - "Let them go. We don't need trouble from a few wanderers."}
{245}{}{"...feed them to the mantises!" - "Calm down, sargeant. I'll tell the boys to intercept the caravan and return the stolen items. Be more careful with unchecked traders next time."}
{246}{}{"...few rations. Dunno if we should help them. We're running out of rations, too." - "Keep them. Closest outpost's too far, don't risk it..."}
{247}{}"{...one left, he ran away into the desert." - "Let him go. I'll tell the closest patrolmen to intercept him." - "I appreciate it, but I'll deal with him myself." - "Ranger! Do *not* run after him in the open desert!" - "To hell with that. I'll do it anyway." - "(pause) Whatever. But if you do that again, I will report it to the commander."}
{248}{}{*static* - "Bravo" team, do you copy?" - *static* - "Bravo" team, do you copy?!.. Shit..."}
{249}{}{*static*}

{250}{}{...can't believe it! Who the hell could have done that?!" - "Rangers have a lot of enemies. But the dam was destroyed from within... it had to have been one of them. They say someone was allowed entry into the dam right before it was destroyed. Guards were interrogated. They won't be seeing their badge, that's for sure."}
{251}{}{...on the base, you'll definitely want to take a look at that one. He's young, but a great mechanic." - "I don't like dealing with teenagers. The important thing is that he watches over the dam. Soon, old man Rufus will be gone. What will we do without him?"}
{252}{}{...noticed that too. What happened?" - "Operators hired some peasant to fix the antenna. Now the radio works better and has a longer range. - "Peasant? What a twist. If I met them, I'd tip them my hat."}
{253}{}{...captured that fugitive. Bitch was hiding in the basement, near the farmers on the 95th highway." - "Right under our noses? All while we were looking for them everywhere and failing to find him?" - "Great spy. We could use people like him. I hear it wasn't our men that caught him, it was some wanderer." - "So, outsiders *can* be useful, after all." - "You don't say..."}

{260}{}{This is ranger }
{261}{}{. I'm in the desert, not too far away from the base. I need supplies, immediately. Over.}
{262}{}{*static* Roger, ranger. Do you have the location of Quartz? It's to the south. Find the ruins by the bar, there is a secret basement there. We put various supplies there. Hope this helps. Over.}
{263}{}{Thank you, fellow ranger. Out.}
{264}{}{Search for the source of whatever is relaying ranger radio communications.}
{265}{}{You fail to find the phenomenon. It seems that the source is too far away.}
{266}{}{The source is too far away. You should head back to the Ranger base and head strictly east.}
{267}{}{It looks like you've found the source of the echo! Only thing left is to head there.}
{268}{}{Go to the source right now.}
{269}{}{}
{270}{}{Asking all rangers: has anybody seen a very big radscorpion? What were the coordinates? Over.}
{271}{}{Roger, ranger. The last time it was detected was at these coordinates. You're really going out hunting, huh? Be careful. You don't want to get anywhere close to that beast without at least a grenade launcher. Over.}
{272}{}{[Head to the received coordinates]}
{273}{}{Roger, fellow ranger. Out.}
{1273}{}{Roger, fellow ranger. Out.}
{274}{}{Roger that. Out.}

#The Old Motel
{290}{}{Cycle through all frequencies.}
{291}{}{You identify a barely discernible signal. It's a request for help.}
{292}{}{[Listen]}
{293}{}{[Ignore]}
{294}{}{...Anybody! Help! I'm in some kind of old motel. South-west of Phoenix. They've blocked all the exits. I can't get out. Someone, please help...}
{295}{}{[Continue]}
{296}{}{Everyone else got caught in the traps and died. I'm the only one who has survived... Someone's coming... What do you want? Get away! Oh, god! Don't touch me! No! NO! A-a-a! (signal is gone)}
{297}{}{An old motel to the south-west. Great. Off I go for yet another harsh journey through the wastes...}

#Vault 27
{300}{}{The emergency frequency is transmitting a distress signal.}
{301}{}{Obviously, I'm too far away from the Vault. I have to return to Phoenix and try various directions.}
{302}{}{This is pointless. I already know where the Vault is.}
{303}{}{The signal is more intense in that direction. I'll try triangulation...}
{304}{}{The signal is intensifying.}
{305}{}{Got it! Looks like I found the source.}
{1305}{}{Got it! Looks like I found the source.}

#Flagstaff - Faber mercenaries
{310}{}{(You hear various conversations between patrolmen. Nothing of any particular interest to you.)}
{320}{}{All hands, we are under attack! I repeat, we are under attack! There's a whole crowd of primitives! Requesting immediate backup! All... A-a-a!}
{321}{}{Roger that. Sending a unit from the garrison. Hang on...}
{322}{}{(Yes, empty the garrison of life, idiot, that's exactly what I need)}
{323}{}{Track the missing tinsmith's signal.}
{324}{}{Signal tracking failed.}
{325}{}{Maybe I'm just to far away from him. I need to get back to the center of Casa Grande.}
{326}{}{You detect the barely discernible signal.}
{327}{}{Great. He's somewhere in the settlement. It looks like the signal is coming from the east.}
{328}{}{You hear the signal from the implant very well.}
{329}{}{So, he's somewhere nearby. He or his corpse.}

#Inferno
{350}{}{Brotherhood of Steel unit, respond. Do you copy?}
{351}{}{(you hear only white noise in response}
{352}{}{I repeat. Brotherhood of Steel unit, this is the rescue team. Respond.}
{353}{}{Doesn't look like anyone is hearing me. Turn off the radio.}
{354}{}{This is paladin Barkley... reading you loud and clear, comrade. We're in a difficult situation. I'm wounded, and my communications with the other members of my unit aren't working. Requesting immediate help. Over.}
{355}{}{Roger that. What is your location, paladin Barkley? Over.}
{1355}{}{Roger that. What is your location, paladin Barkley? Over.}
{356}{}{Location is... underneath the manhole near the destroyed supermarket. Be careful. There are many mutants on the surface. Over.}
{357}{}{Roger that. Stay where you are. Out.}
{358}{}{Hey, does anyone hear me?}
{359}{}{(Nobody replies)}
{360}{}{I repeat. Does anyone hear me? Is anyone alive in this place?}
{361}{}{Fine. This was a bad idea.}
{362}{}{This is Barkley... Yes, at least one living person is here. Listen to me carefully, comrade. I'm wounded. I need immediate help.}
{363}{}{Where are you, Barkley?}
{364}{}{In the sewers, near the destroyed supermarket. Head right to me, don't lose any time. And be careful. The mutants are everywhere.}
{365}{}{Hang on, Barkley. Help is on it's way.}
{366}{}{Wait, mutants? This doesn't bode well.}

{370}{}{[Look for the signal]}
{371}{}{(You carefully cycle through the frequencies and point the radio toward all directions you can think of, until, finally, sound comes out of the speaker.)}
{372}{}{[Listen]}
{373}{}{[Ignore]}
{374}{}{(you hear old music through the heavy white noise)}
{375}{}{[Listen to the music until the end]}
{376}{}{… Hey, wasteland wanderer! Tired of constant travel? Exhausted from walking through the desert? Then head right to the Hub!}
{377}{}{[Continue]}
{378}{}{You'll find everything needed for relaxation here: bars, hotels, a giant marketplace... and, of course, the unforgettable "Maltese Falcon" cafe! Come to our cafe to relax and forget about deathclaws and highwaymen.}
{379}{}{Want that fresh feeling? We have nuka-cola reserves! And for fans of the energetic and exciting, we'll always pour a cup of the legendary Hub rum.}
{380}{}{"But what about slot machines?", you might ask. Do we have them? Yes, we have them, baby. One of the few remaining ones in modern California. Don't miss this opportunity!}
{381}{}{And, of course, our ladies will always take *extra special care* of our dear clients, who are so lonely during their travels. Head to the «Maltese Falcon»! Head to the Hub - it is waiting for you! (old music begins again)}
{382}{}{Man, that's so far away. And I need to go in the exact opposite direction...}
{383}{}{You receive experience points for listening to a signal from California.}
