#Containers
{100}{}{Hey, put that back right now!}
{101}{}{You touch that one more time - you'll regret it.}
{102}{}{Don't you dare touch my stuff!}
{103}{}{I don't know what it is you're looking for, but it's not there. Got it?}
{104}{}{You touch that one more time - you'll be knee-deep in trouble.}
{105}{}{Don't touch that.}
{106}{}{Don't tell me you're just "looking for your keys".}
{107}{}{Get away from there!}
{108}{}{You know, it ain't nice to take other people's stuff}

{109}{robots}{*Show pass*}

#Doors
{110}{}{You can't go in there.}
{111}{}{Hey, you! What are you doing in there?}
{112}{}{Don't tell me you're just "looking for your keys".}
{113}{}{Get away from that door right now!}
{114}{}{You try that again - you're going to be in a lot of trouble.}
{115}{}{Don't do that.}
{116}{}{Don't even think about going in there. It isn't locked for nothing.}
{117}{}{Get away from there, now!}
{118}{}{Stop touching that, or you're going to get in a world of trouble.}

{119}{robots}{*Show pass*}

#Lines for attacking player
{120}{people}{I warned you!}
{121}{robots}{Intruder detected!}

{122}{}{The owner does not like you touching their personal belongings.}
{123}{}{The owner of the building is not letting you in there.}
{124}{}{The robot is guarding this warehouse.}
{125}{}{The robot is guarding this place.}

{126}{}{ does not allow you to touch these items.}
{127}{}{ does not allow you to touch these items.}
{128}{}{ is not letting you in there.}
{129}{}{ is not letting you in there.}

{130}{}{No toques la puerta.}
