#For containers
{100}{}{Hey, put that back quickly!}
{101}{}{Touch it again and you'll pay.}
{102}{}{Hands off my stuff!}
{103}{}{I don't know what you're looking for, but it's not here. Got it?}
{104}{}{Just touch it again and you'll have problems.}
{105}{}{Don't touch it.}
{106}{}{Just don't tell me you're "just looking for your keys."}
{107}{}{Get out of there!}
{108}{}{You know, it's not good to take someone else's}

{109}{robots}{*Present a pass*}

#For doors
{110}{}{You can't go there.}
{111}{}{Hey, you! What are you doing there?}
{112}{}{Just don't tell me that "you're just looking for your keys"}
{113}{}{Get out of there, quickly!}
{114}{}{Just try it and you'll have problems.}
{115}{}{Don't do it.}
{116}{}{Don't even think about it. It's closed for a reason.}
{117}{}{Get out of there!}
{118}{}{Leave it alone, or I'll take exceptional measures on your ass.}

{119}{robots}{*Present a pass*}

#Replicas when attacking GG
{120}{people}{You were warned!}
{121}{robots}{An intruder has been detected!}

{122}{}{The owner doesn't like you touching his things.}
{123}{}{The owner doesn't intend to let you in there.}
{124}{}{The robot guards this warehouse.}
{125}{}{The robot is guarding this place.}

{126}{}{ does not allow you to touch these things.}
{127}{}{ does not allow you to touch these things.}
{128}{}{ does not intend to let you in there.}
{129}{}{ does not intend to let you in there.}

{130}{}{No toques la puerta.}