{101}{}{This device is very good for making alcoholic beverages.}
{102}{}{This device is very good for making alcoholic beverages. But it must receive raw material, first.}
{103}{}{Making alcohol in combat will be too hard.}

{110}{}{The device must receive raw material to make tequila.}
{111}{}{This turned out to be harder than you expected. You'll have to examine the recipe first.}
{112}{}{Raw material loaded. To make tequila, use scientific methods.}
{113}{}{The device is already fully loaded. It can't receive any more raw material.}
{114}{}{This raw material should be poured directly into the hopper.}
{115}{}{The wasteland tequila is ready and is waiting to be poured into bottles.}
{116}{}{You receive }
{117}{}{ bottles of wasteland tequila.}
{118}{}{You missed something.}

{120}{}{The device is fully operational and does not need repairs.}
{121}{}{Having a lock on all these bottles would be the pinnacle of engineering. How did you even come up with such a brilliant idea?}
{122}{}{The device has been destroyed. This will be a big loss for whoever is spreading alcoholism.}
{123}{}{Oops...}
