{101}{}{This device is perfect for making alcoholic beverages.}
{102}{}{This device is perfect for making alcoholic beverages. But first it needs to be refueled.}
{103}{}{It will be too difficult to prepare alcohol in battle.}

{110}{}{To make tequila, it is necessary to fill the device with raw materials.}
{111}{}{It turned out to be not as easy as you expected. You'll have to study the recipe first.}
{112}{}{You refueled the machine. To make tequila, use scientific methods.}
{113}{}{The unit is already fully fueled. No more raw materials will fit in it.}
{114}{}{This raw material should be poured directly into the container of the device.}
{115}{}{Wasteland tequila is ready and waiting to be bottled.}
{116}{}{You have received }
{117}{}{ bottles of wasteland tequila.}
{118}{}{Something is missing}

{120}{}{The device is in perfect order and does not need repair.}
{121}{}{Locking all these bottles would be the height of engineering. And why only you guessed it before?}
{122}{}{The device is destroyed. It will be a big loss for the local hotbed of drunkenness.}
{123}{}{Oops...}