{110}{}{The machine gives out goods only for money. Unless, of course, you're going to hack it.}
{111}{}{This merchant has already been hacked.}
{112}{}{}
{113}{}{ The lock is too complicated.}
{114}{}{The lockpicks are installed. Now it will be easier for you to crack this lock.}
{115}{}{The lock already has the required number of lock picks.}
{116}{}{An electronic decoder is not suitable for breaking mechanical locks.}
{117}{}{You have opened the container with the goods. It's time to see what's left inside.}
{118}{}{Now that the machine is open, it doesn't make sense.}
{119}{}{You got a nuclear battery.}
{120}{}{The vending machine ran out of goods.}
{121}{}{}
{122}{}{You cannot bypass the protective mechanism of the merchant.}