{108}{}{ Integrity: }
{109}{}{%.}
{110}{}{ blocks the way. You could destroy it with explosives or a sledgehammer.}
{111}{}{You do not have enough Strength. Try to use something stronger.}
{112}{}{With brute force, you remove the obstacle. The way is no longer blocked.}
{113}{}{The blast blows the obstacle into smithereens.}
{114}{}{Looks like more heavy equipment is needed here.}
{115}{}{The hit cracks the obstacle into many smaller, but still large chunks.}
{116}{}{Obstacle integrity change is }
{117}{}{%.}
{118}{}{-}
{119}{}{%}
{120}{}{Only brute force will help here.}
{121}{}{You doubt that this can be burned down with a lighter.}
{122}{}{Search for a more powerful instrument.}
{123}{}{Construction is clearly not your thing.}