{108}{}{ Current status }
{109}{}{%.}
{110}{}{ blocks the passage. With a sledgehammer or a package of explosives, you could destroy this obstacle.}
{111}{}{You lack strength. Try using something more powerful.}
{112}{}{Using brute force, you eliminate the obstacle and free the passage.}
{113}{}{The explosion splits the obstacle into small fragments.}
{114}{}{It seems that heavier weapons are needed here.}
{115}{}{The impact splits the obstacle into many fragments.}
{116}{}{The obstacle is destroyed by }
{117}{}{%.}
{118}{}{-}
{119}{}{%}
{120}{}{Only brute force will help here.}
{121}{}{It can hardly be ignited with a lighter.}
{122}{}{Look for a more powerful tool.}
{123}{}{Construction is clearly not your profile.}