{110}{}{Valuable Pre-War knowledge is stored here. Studying it wouldn't hurt.}
{111}{}{Looks like you can't understand such complicated information.}
{112}{}{This is beyond your understanding.}
{113}{}{You spend an entire day studying this Pre-War knowledge. Things have now become much more clear.}
{114}{}{You quickly glance through the records and don't find anything new.}
{115}{}{Library terminal access granted.}

{121}{}{The preacher won't like you studying the holy writings without permission.}
{122}{}{The library terminal needs a keycard.}
{123}{}{Reading electronic books while breathing in asphyxiating gas is too dangerous.}
{124}{}{The Followers won't like you going through their data without permission.}
{125}{}{The Brotherhood's scribes did not give you permission to study this database.}
{126}{}{The local cultists won't like you going through their books without permission.}
