{110}{}{"here we keep valuable pre-war knowledge. It will not be superfluous to study them.}
{111}{}{It looks like you won't be able to master such complex information.}
{112}{}{This is beyond your understanding$.}
{113}{}{Ö you spent the whole day studying this storehouse of pre-war knowledge. Ònow a lot has become clearer.}
{114}{}{you skimmed through the records and found nothing new.}
{115}{}{the access to the library terminal is open.}

{121}{}{The preacher will not like it if you study the Holy scriptures without permission.}
{122}{}{The library terminal requires an access card.}
{123}{}{"make e-books in the conditions ofÿx suffocating gas is deadly Zanÿtie.}
{124}{}{sledovatelÿm not likeÿ if you become coatsÿ in their data without permissionÿ.}
{125}{}{isari Ratsch did not give you permissionÿ forÿ Vibrÿ the database.}
{126}{}{Estim cultists not likeÿ if you become coatsÿ in their books without permissionÿ.}