{110}{}{The vending machine gives out a drink only for money. Unless, of course, you're going to hack it.}
{111}{}{This machine has already been hacked.}
{112}{}{}
{113}{}{ The lock is too complicated.}
{114}{}{The lockpicks are installed. Now it will be easier for you to crack this lock.}
{115}{}{The lock already has the required number of lock picks.}
{116}{}{An electronic decoder is not suitable for breaking mechanical locks.}
{117}{}{You opened a container with drinks. It's time to see what's left inside.}
{118}{}{Now that the machine is open, it doesn't make sense.}
{119}{}{You have received a bottle of warm, exhausted core Cola.}
{120}{}{The vending machine ran out of stocks of cola kernels.}
{121}{}{}
{122}{}{You can't bypass the protective mechanism of the machine.}