#General
{110}{}{Before locking the lock, you should close the door.}
{111}{}{You lock the lock.}
{112}{}{You open the lock.}
{113}{}{It will be too difficult to do this in battle.}
{114}{}{The lock is closed.}
{115}{}{There was no trace left on the door.}
{116}{}{The explosion didn't even leave a scratch on the door.}
{117}{}{Before locking the lock, you should close the door.}

#Attempt to open
{120}{}{You find that }
{121}{}{ equipped with a dangerous trap.}
{122}{}{You find that }
{123}{}{ turned out to be with a trap!}
{124}{}{ turned out to be equipped with a trap!}

#Skills
{130}{}{This skill is useless here.}
{131}{}{ locked.}
{132}{}{ has a lock with difficulty level }
{133}{}{.}
{134}{}{ And it will not be superfluous to check for traps.}
{135}{}{The hacking attempt failed. Try again.}
{136}{}{}
{137}{}{The hacking attempt failed.}
{138}{}{With such a low skill, you won't learn anything useful.}
{139}{}{This lock is too complicated.}

#Broken lock
{140}{}{Alas, this lock is physically broken. And it's forever.}
{141}{}{This lock is already broken.}
{142}{}{It makes no sense to break open the lock.}
{143}{}{This lock cannot be broken by brute force.}
{144}{}{It takes *very* great strength to break this lock.}
{145}{}{Using brute force, you break the lock. No one will ever be able to close it again.}
{148}{}{ it turned out to be equipped with a trap!}
{149}{}{Weapons should be used in combat mode. }
# Use combat mode to break this lock.

#Traps
{150}{}{You fail to detect the trap.}
{151}{}{}
{152}{}{}
{153}{}{You have found a trap, but you cannot defuse it.}
{154}{}{It was a mistake! Perhaps in another case you will not allow it.}
{155}{}{You have successfully defused a primitive trap.}
{156}{}{You have successfully defused the trap from an old 12 gauge cartridge.}
{157}{}{You have successfully defused a frag grenade trap.}
{158}{}{You have successfully defused the electronic trap.}
{159}{}{You have successfully disabled the alarm.}

#Items
{160}{}{It hardly helps with a broken lock.}
{161}{}{The lockpicks are installed. Now it will be easier for you to crack this lock.}
{162}{}{The lock already has the required number of lock picks.}
{163}{}{An electronic decoder is not suitable for breaking mechanical locks.}
{164}{}{This lock needs another key.}
{165}{}{This key doesn't fit. It is unlikely that you will find the key to this lock at all.}
{166}{}{The explosion blows the door to pieces.}
{167}{}{A master key will not help in breaking electronic locks.}
{168}{}{One decoder is already installed.}
{169}{}{The decoder is installed. Now it will be easier for you to crack this lock.}
{170}{}{A shovel won't help here.}
{171}{}{This key doesn't fit.}