#Details
{101}{}{You see a slot machine.}
{102}{}{You see a strange slot machine.}
{103}{}{You see a slot machine.}
{104}{}{You see a shining slot machine.}
{105}{}{You see a glowing slot machine.}

#Interaction, skill and item use
{110}{}{Trying to break this open won't accomplish anything.}
{111}{}{This fancy-looking machine gives tokens and makes sounds designed to exploit the human brain's reward systems. Villa didn't have anything like it.}
{112}{}{The slot machine clearly doesn't need repair.}
{113}{}{Doing this during combat will be hard.}
{114}{}{Playing with the slot machine requires special tokens.}
{115}{}{This particular machine is out of tokens. You'll have to wait for it to get refilled.}
{116}{}{You have no idea what to do with this.}
{117}{}{Insert the token to play.}
{118}{}{Your bet: }
{119}{}{.}
{120}{}{Unfortunately, this slot machine can no longer accept bets as it itself lacks tokens.}
{121}{}{Maximum bet reached (20 tokens).}
{122}{}{These tokens don't fit this slot machine.}
{123}{}{}
{124}{}{}

#Player character comments when losing and not having tokens
{125}{}{This is bullshit!}
{126}{}{That was my last one...}
{127}{}{Getting it back won't be easy.}
{128}{}{Dammit! It ate my last tokens!}
{129}{}{Dammit! I'm out!}

#Slot machine
{130}{}{*Clank*}
{131}{}{*Ding*}
{132}{}{*Bs-s-s*}
{133}{}{*Tr-r-r*}
{134}{}{*Play with me*}
{135}{}{*Hey, hi*}
{136}{}{*You'll like me*}
{137}{}{*Ring*}
{138}{}{*Ding dong*}
{139}{}{*Blam*}
{140}{}{}
{141}{}{}
{142}{}{}
{143}{}{}
{144}{}{}
{145}{}{}
{146}{}{}
{147}{}{}
{148}{}{}
{149}{}{}

#Game results
{150}{}{You have lost.}
{151}{}{You have lost. No use being angry.}
{152}{}{Your bet burned.}
{153}{}{It's like the machine is mocking you. You have lost.}
{154}{}{You have lost. Today is clearly not your day.}

{155}{}{You have won }
{156}{}{ tokens.}
{157}{}{ tokens.}
{158}{}{ tokens. Good job!}
{159}{}{JACKPOT!}

#Slot labels
{160}{}{URANIUM}
{161}{}{PLUTONIUM}
{162}{}{RADIUM}
{163}{}{POLONIUM}
{164}{}{RADON}
{165}{}{BERILLIUM}
{166}{}{MERCURY}
{167}{}{TELLURIUM}
{168}{}{THORIUM}
{169}{}{LEAD}

{170}{}{ - }
{171}{}{ATOM}
{172}{}{BOMB}
{173}{}{CLOUD}
{174}{}{COWBOY}
{175}{}{SEVEN}
{176}{}{CANNON}
{177}{}{HORN}
{178}{}{}
{179}{}{}
