#Detailed description
{101}{}{This is a regular slot machine.}
{102}{}{You see a strange car.}
{103}{}{You see a slot machine.}
{104}{}{You see a sparkling slot machine.}
{105}{}{You see a shining slot machine.}

#Interaction, use of skills and items
{110}{}{Hacking this machine won't do anything.}
{111}{}{This cool machine makes sounds and gives out chips. This has never happened in the Villa.}
{112}{}{This particular machine does not need repair.}
{113}{}{It will be extremely inconvenient to do this during the battle.}
{114}{}{This slot machine requires a special playing chip to play.}
{115}{}{This slot machine has run out of chips. We will have to return to it after replenishment.}
{116}{}{You have no idea what to do with it.}
{117}{}{To play, insert a playing chip.}
{118}{}{Your bid: }
{119}{}{.}
{120}{}{Unfortunately, the slot machine cannot accept more bets due to a lack of its own chips.}
{121}{}{The maximum bet has been reached (20 chips).}
{122}{}{These chips are not suitable for this slot machine.}
{123}{}{}
{124}{}{}

#Phrases over GG when losing and no chips in your pocket
{125}{}{Hey, it's a robbery!}
{126}{}{That was the last trick...}
{127}{}{It won't be easy to win back.}
{128}{}{Damn it! This machine ate my last chips!}
{129}{}{Damn it! I'm broke!}

#Replicas over the machine
{130}{}{*Ding*}
{131}{}{*Ding*}
{132}{}{*Bz-z-z*}
{133}{}{*Tr-r-r*}
{134}{}{*Play with me*}
{135}{}{*Hey, hello*}
{136}{}{*You'll like me*}
{137}{}{*Jingle*}
{138}{}{*Ding dong*}
{139}{}{*Blam-s*}
{140}{}{}
{141}{}{}
{142}{}{}
{143}{}{}
{144}{}{}
{145}{}{}
{146}{}{}
{147}{}{}
{148}{}{}
{149}{}{}

#Replicas when playing
{150}{}{You lost.}
{151}{}{You've lost. Accept it.}
{152}{}{Your bid has burned out.}
{153}{}{The machine seems to mock you. You lost.}
{154}{}{You've lost. Today is not your day.}

{155}{}{You have won }
{156}{}{ chips.}
{157}{}{ chips.}
{158}{}{ chips. Great game!}
{159}{}{JACKPOT!}

#Drum names
{160}{}{URANUS}
{161}{}{PLUTONIUM}
{162}{}{RADIUM}
{163}{}{POLONIUS}
{164}{}{RADON}
{165}{}{BERYLLIUM}
{166}{}{MERCURY}
{167}{}{TELLURIUM}
{168}{}{THORIUM}
{169}{}{LEAD}

{170}{}{ - }
{171}{}{ATOM}
{172}{}{BOMB}
{173}{}{CLOUD}
{174}{}{COWBOY}
{175}{}{SEVEN}
{176}{}{CANNON}
{177}{}{MOUTHPIECE}
{178}{}{}
{179}{}{}