{110}{}{This skill is not applicable here.}
{111}{}{It is unlikely that you will be able to dig a hole in combat conditions.}
{112}{}{You can't even lift a shovel with such force.}
{114}{}{You'll have to work hard to look inside.}
{115}{}{Someone carelessly buried a dog here. And this someone was clearly in a hurry.}
{116}{}{This hole is not so easy to bury.}
{117}{}{While digging the grave, it suddenly began to crumble and carried you down into the underground voids.}
{118}{}{What the hell...}
{119}{}{Ay-ay-ay...}
{120}{}{The pit is quite deep.}