{110}{}{This skill is not valuable here.}
{111}{}{It's unlikely that you will be able to dig a hole in combat conditions.}
{112}{}{With that level of strength, even lifting the shovel will take herculean effort.}
{114}{}{You'll have to spend some effort to look inside.}
{115}{}{Someone was in a big hurry to bury a dog here.}
{116}{}{This hole will not be dug easily.}
{117}{}{As you dig, the grave suddenly starts to crumble, sending you down into the bowels of the earth.}
{118}{}{What the hell...}
{119}{}{Ouch...}
{120}{}{The hole is quite deep.}
