{110}{}{"To use the trap, you need the appropriate skills.}
{111}{}{N-n-m! These iguanas were not quick enough, and soon they will be in someone's stomach.}
{112}{}{- with such skills, this trap will be more useless than garbage.}
{113}{}{the feeding is over, this trap is now useless.}
{114}{}{two traps in one place? It's a useless$waste of time.}
{115}{}{You have successfully set the trap.}
{116}{}{Õoroshaÿ idaÿ, but you have no idea how to do it.}