{110}{}{To use the trap, you need to have certain skills.}
{111}{}{Exquisite! These iguanas weren't bright enough, and now they're going to end up in someone's stomach.}
{112}{}{With these skills, a pile of trash will serve as a better trap.}
{113}{}{Out of lure, the trap is now useless.}
{114}{}{Setting up two traps in the same place is a waste of time.}
{115}{}{You successfully install a trap.}
{116}{}{Good plan, but you have no idea how to do it.}