{110}{}{You haven't learned anything new, yet. Perhaps you could try a more methodical approach.}
{111}{}{?}
{112}{}{Systemic analysis is clearly not your forte.}
{113}{}{This is impossible to repair.}
{114}{}{To examine the object, you should utilize scientific methods.}
{115}{}{What is THAT doing here?}

# 20 lines per location.
# 2 lines per object:
#   - 1st: log message
#   - 2nd: a comment from the player character (if it is not necessary, put space into the line, otherwise the player character will say Error)

#Villa
{200}{}{An old birthing chair. You were born on it.}
{201}{}{Good thing I don't remember it.}
{202}{}{This old technology is no longer functional due to extensive rust.}
{203}{}{It doesn't work. And won't ever work.}
{204}{}{The computer is so ancient, that some of it's parts have entirely turned to rust. It hasn't been used for several decades. If you had to guess - fourty, fifty years. Not surprising for Villa.}
{205}{}{Padre didn't tell me about this...}
{206}{}{You arrive to the conclusion that the symbol represents a winged creature flying out of fire. But you're not sure.}
{207}{}{The symbol was definitely left behind by the raiders.}
{208}{}{One of the achievements of local engineering. You weren't allowed anywhere close ever since you were a child - there was no more space for other people to work.}
{209}{}{There's too little of them here. They probably sold a portion of the ceramics to nearby settlements.}

#Jackals
{210}{}{}
{211}{}{}
{212}{}{}
{213}{}{}
{214}{}{This looks like a nuclear ramjet engine. The technology is too advanced to have been made in the present day.}
{215}{}{Making this thing move would require a LOT of effort.}
{216}{}{This equipment controlled how much of a complicated mixture of gases would go into the sarcophagi. Recently, an internal timer automatically disabled the gas flow.}
{217}{}{Wow. They must have slept for decades.}
{218}{}{This construction, made from wood and skulls, clearly represents something from the Pre-War era. The number 15 is written on a piece of skin.}
{219}{}{An echo from times of old, that has lost it's meaning.}

#Flagstaff
{220}{}{Looks like surgeries are done here occasionally. The basement muffles the screams of the sick.}
{221}{}{So unhygienic, too...}
{222}{}{The information written here doesn't line up with reality. Looks like this mine is from Pre-War times.}
{223}{}{This thing's older than the colony.}
{224}{}{This ancient poster encourages women to work hard during a time of war.}
{225}{}{On Villa, everyone works without any posters.}
{226}{}{The sign says: "Northern Arizona Museum". Below the sign, there are several other words: "Museum, shop and library".}
{227}{}{What could "museum" mean?}
{228}{}{While watching the ancient exhibit with great interest, you suddenly find a grenade next to it. Someone must have forgotten it.}
{229}{}{Where did this come from?}

#San Brahmin
{230}{}{The exhibit inspires both awe and terror.}
{231}{}{Sure nice that there are no more monsters like that... I hope.}
{232}{}{The names of several movies are written here. You haven't seen them. You haven't seen any movie at all.}
{233}{}{   }
{234}{}{}
{235}{}{}
{236}{}{}
{237}{}{}
{238}{}{}
{239}{}{}

#Phoenix
{240}{}{Hidden surveillance cameras allow Aaron to see almost everything that happens inside the cathedral.}
{241}{}{Looks like the Overlord of Phoenix is a control freak.}
{242}{}{Studying the data, you have arrived at several conclusions. You will now receive a 15% bonus to your chances at winning roulette.}
{243}{}{Heh, wear and tear can be quite useful, it turns out.}
{244}{}{You have studied the recipe for making wasteland tequila.}
{245}{}{I see now, why no one else makes it except for the casino.}
{246}{}{You have already studied the recipe for making wasteland tequila.}
{247}{}{Enough of these numbers.}
{248}{}{While the statue survived, the labels, if there were any, haven't. You can only guess why it has been placed here.}
{249}{}{Quite... fitting. For these ruins.}

#Two Sun and Vault 27
{250}{}{The tinsmiths made this computer from various components. It's a wonder, but it works, and works quite well.}
{251}{}{The tinsmiths have made impressive achievements.}
{252}{}{Blackened gold bars. They say that gold was once incredibly valuable, but nowadays, it's not worth even a single cap.}
{253}{}{Gold stopped being valuable a long time ago.}
{254}{}{Among the financial records, you find data on slaves. Most of them are being transported to Two Sun.}
{255}{}{I suppose I should go visit Two Sun and take a look at the slaves.}
{256}{}{On the back side of the painting, you find a code.}
{257}{}{Hm, what do these numbers mean?}
{258}{}{These mercenaries died from a powerful explosion. One of them, however, died from a 10mm bullet to the head.}
{259}{}{I shouldn't look at this kind of stuff for long.}

#Rangers and Quartz
{260}{}{This ancient road sign shows the distance to the dam. Above, the following words have been painted: "Ranger territory".}
{261}{}{Parker Dam is up ahead. The Ranger citadel.}
{262}{}{You have carefully studied the Ranger maps. Traveling around this region will now become much easier.}
{263}{}{Wow. The cartographer has sure been keeping busy.}
{264}{}{The cartographer won't let you examine his maps.}
{265}{}{   }
{266}{}{Rangers prefer to rely on people, rather than machines. Even when such advanced technology is fight under their noses.}
{267}{}{This computer hasn't been used in a long time.}
{268}{}{"Warning! Protected zone. All persons in this area are subject to Federal law for protection of the object".}
{269}{}{A surviving Pre-War sign.}
{270}{}{The locals were trying to build themselves a "reactor". Failure turned to disaster, and the entire area became irradiated.}
{271}{}{So that's what happened here...}
{272}{}{The sign reads: "Welcome to Quartzsite. Founded in the year 1879. 879 feet above sea level".}
{273}{}{Many people must have passed through this place once.}
{274}{}{"Welcome to Parker Dam. Founded in 1934-1938, reconstructed in 2055".}
{275}{}{A *very* old building.}
{276}{}{An old road sign. A Ranger symbol has been painted on it.}
{277}{}{The Ranger symbol means that they are protecting a settlement.}
{278}{}{}
{279}{}{}

#Other locations
{280}{}{"Monument to the Victims of Annexation and Border Troubles of 2051".}
{281}{}{So, the US of A *did* annex Mexico, after all.}
{282}{}{Security system disabled.}
{283}{}{How do you like that, tin can?}
{284}{}{"Attention, wanderer! In this settlement, the following is strictly forbidden: alcohol, drugs, open carrying of weapons. Crop theft will be punished with the death penalty. A night-time curfew is in place".}
{285}{}{This place sure has strict rules.}
{286}{}{The guest log ends during the year 2077.}
{287}{}{Nothing of particular interest.}
{288}{}{This painting is more than a century old. It's a wonder it's still here.}
{289}{}{Could people have actually painted this?}

#Puerto
{290}{}{Brotherhood of Steel radio frequencies copied.}
{291}{}{Great. I'll be able to eavesdrop on Brotherhood patrolmen.}
{292}{}{The ladder leads down. How unexpected.}
{293}{}{?}
{294}{}{You have carefully studied the Brotherhood of Steel maps. Traveling around this region will now become much easier.}
{295}{}{Brotherhood scouts sure earn their rations.}
{296}{}{You try to find Villa, but the true size of the continent overwhelms you.}
{297}{}{Is the world really so... big?}
{298}{}{This welcome sign is bilingual - it has text in both spanish and english.}
{299}{}{These ruins must have once been a nice place...}

{300}{}{This equipment allows the locals to contact Puerto.}
{301}{}{Standard transmitter.}
{302}{}{This equipment used to allow the locals to contact Puerto.}
{303}{}{Standard transmitter.}
