{110}{}{You haven't learned anything new yet. It may be worth investigating more methodically.}
{111}{}{?}
{112}{}{System analysis is not your strong suit.}
{113}{}{It cannot be repaired.}
{114}{}{To study the object, you should use scientific methods.}
{115}{}{What is IT doing here?}

# 20 lines are allocated for one location.
# 2 adjacent rows are created for each object:
# - the first one under the message in the log
# - the second one under the replica over the GG (if you don't need it, put spaces in it, otherwise the GG will say Error)

#Villa
{200}{}{It's an old midwife's chair. You were born in it.}
{201}{}{Not the most pleasant memories}
{202}{}{This ancient technology does not function, as it has rusted through from dampness.}
{203}{}{Does not work. And it won't work.}
{204}{}{This computer is so ancient that its parts are completely rusty. It hasn't been used for at least forty years. This is not surprising for the Villa.}
{205}{}{The padre didn't tell me...}
{206}{}{You come to the conclusion that the symbol depicts a winged creature flying out of the fire. But this is not accurate.}
{207}{}{This symbol was left by the raiders}
{208}{}{One of the achievements of local engineering. You have not been allowed to go to him since childhood, since all the vacant places were occupied.}
{209}{}{It seems that some of our ceramics were sold to neighboring settlements}

# Jackals
{210}{}{}
{211}{}{}
{212}{}{}
{213}{}{}
{214}{}{It's probably a nuclear ramjet engine. This technology is too complicated for the modern world.}
{215}{}{It will take a lot of work to make it move on its own}
{216}{}{This equipment controlled the flow of a complex gas mixture into the sarcophagi. Recently, it was automatically disabled by an internal timer.}
{217}{}{Wow, they must have been sleeping for decades}
{218}{}{This structure of boards and skulls probably depicts something from the pre-war era. The figure 15 is drawn on a piece of skin.}
{219}{}{An echo of ancient times that has lost its meaning}

#Flagstaff
{220}{}{It seems that surgical operations are sometimes performed here, and the basement hides the screams of patients.}
{221}{}{And no hygiene...}
{222}{}{The information on the stand does not correspond to reality. It looks like this mine is from pre-war times.}
{223}{}{This stand is older than the colony}
{224}{}{This ancient poster agitates women to work hard during the war.}
{225}{}{And they work at the Villa without any agitation}
{226}{}{The inscription reads: "Museum of Northern Arizona." Below the caption: "Museum, shop and library".}
{227}{}{I do not know what a "museum" is.}
{228}{}{Looking with interest at an ancient exhibit, you suddenly discover someone has forgotten a grenade at its foot.}
{229}{}{And this is here from where?}

#San Brahmin
{230}{}{This exhibit is admired and feared at the same time.}
{231}{}{It's good that there are no such monsters in the world anymore... probably.}
{232}{}{Movie titles are written here. You've never seen them. You haven't seen any movies at all.}
{233}{}{ }

#Phoenix
{240}{}{Hidden surveillance cameras allow Aaron to monitor the premises of the cathedral.}
{241}{}{It seems the Lord of the Phoenix is obsessed with security and control}
{242}{}{After studying the statistics of winnings, you have come to some conclusions. Now the roulette game will be 15% more successful.}
{243}{}{Heh, sometimes the wear of parts can be turned to your advantage}
{244}{}{You have studied the recipe for making wasteland tequila.}
{245}{}{Now it's clear why no one does this except the casino}
{246}{}{You've already studied the recipe for making wasteland tequila.}
{247}{}{I've had enough of these numbers}
{248}{}{This statue has no signatures. We can only guess why it was put here.}
{249}{}{It looks quite... appropriate. For these ruins.}

#Two-Sun, Vault 27
{250}{}{This computer was created by tinsmiths from various components. Surprisingly, it works great.}
{251}{}{It looks like the tinsmiths have made good progress}
{252}{}{Blackened gold bars. They say they used to have a high price, but now no one will pay even one lid for them.}
{253}{}{This gold has long been devalued}
{254}{}{Among the payment orders you find data about slaves. They are mostly transported to Two-Sun.}
{255}{}{Perhaps it's worth visiting Two-Sun and taking a look at the slaves}
{256}{}{You found some code on the back of the picture.}
{257}{}{Hmm, what do these numbers mean?}
{258}{}{These mercenaries were killed by a strong explosion. But one of them died from being shot in the head with a 10 mm bullet.}
{259}{}{It's not worth looking at for a long time}

#Rangers, Quartzsite
{260}{}{This ancient sign indicates the distance to the dam. On top of the paint is an inscription: "Ranger Territory."}
{261}{}{Higher up the highway is Parker Dam — the citadel of the Rangers}
{262}{}{You have carefully studied the Ranger maps. Now traveling around the neighborhood will become much easier.}
{263}{}{Wow, the cartographer didn't waste time in vain}
{264}{}{The cartographer won't let you go through his papers.}
{265}{}{ }
{266}{}{Rangers rely more on themselves than on technology. Even with such technologies right under your nose.}
{267}{}{This computer has not been used for a long time}
{268}{}{"Attention! Protected area. All persons in this area are subject to the Federal Law on the Protection of this Object."}
{269}{}{It seems that this sign has been preserved since pre-war times}
{270}{}{A homemade "reactor" that local residents tried unsuccessfully to assemble. The failure turned into an accident and irradiation of the territory.}
{271}{}{So that's what happened here}
{272}{}{Information for visitors: "Quartzsite, founded in 1879, altitude above sea level 879".}
{273}{}{Probably, a lot of people used to pass through the city}
{274}{}{"Parker Dam, founded in 1934-1938, reconstructed in 2055".}
{275}{}{This is a *very* old structure}
{276}{}{An old road sign. The Rangers' mark is applied on top.}
{277}{}{This label means that the village is protected by rangers}
{278}{}{}
{279}{}{}

#Other locations
{280}{}{"Monument to the victims of the annexation and border riots of 2051".}
{281}{}{So the US has annexed Mexico after all}
{282}{}{The security system is disabled.}
{283}{}{How's that for you, rusty tin can?}
{284}{}{"Attention, traveler! Alcohol, drugs, and the open carrying of weapons are prohibited here. For stealing crops — the death penalty. There is a curfew at night."}
{285}{}{Strict rules here}
{286}{}{The guest log ends in 2077.}
{287}{}{Nothing interesting}
{288}{}{This painting is more than a hundred years old. It is amazing that it has been preserved at all.}
{289}{}{Is it really hand-drawn?}

#Puerto
{290}{}{The radio frequencies of the Brotherhood Have been copied.}
{291}{}{Great, so I can eavesdrop on Brotherhood patrolmen}
{292}{}{This ladder leads down. What a surprise.}
{293}{}{?}
{294}{}{You have carefully studied the maps of the Brotherhood of Steel. Now traveling around the neighborhood will become much easier.}
{295}{}{The Brotherhood's scouts get their IRP for a reason}
{296}{}{You are unsuccessfully trying to find a Villa. But you are struck by the scale of the continent.}
{297}{}{Is the world really that huge?}
{298}{}{This welcome index is written in two languages — Spanish and English.}
{299}{}{Probably, once these ruins were a nice place...}

{300}{}{This equipment is used to connect local residents with Puerto Penasco.}
{301}{}{Standard radio transmitter.}
{302}{}{Once this equipment was used to connect local residents with Puerto Penasco.}
{303}{}{Standard radio transmitter.}

#The Dayglow
{310}{}{Religious meetings were held in this hall.}
{311}{}{"... And we will call ourselves Followers of the Apocalypse. In order to cleanse the world from the sin of our ancestors."}
{312}{}{Scientific conferences were held in this hall.}
{313}{}{"... And we must use our knowledge for the sake of restoring civilization after a nuclear war."}
{314}{}{Highway #8 leads north to the Old Town. Highway #805 leads east to the dam.}
{315}{}{Judging by these signs, there will be a fork in the road ahead.}
{316}{}{Among the junk you find a piece of paper with six digits and decide to memorize them.}
{317}{}{It looks like some kind of code.}
{318}{}{This is the first time you see a TV in action. This sight turned out to be quite enough... disappointing.}
{319}{}{And this noise was watched by people in the past for some reason?}