{102}{}{It doesn't make sense.}
{103}{}{This can be set on fire to illuminate the area.}

{110}{}{You lit the lamp. Its dim light barely penetrates the darkness of the cellars.}
{111}{}{This lamp contains a little oil. It remains only to set it on fire to light up the cellar.}
{112}{}{This lamp dimly illuminates the cellar.}
{113}{}{This lamp has run out of oil.}
{114}{}{Fire and smoke scare the local coyotes.}