{102}{}{This is pointless.}
{103}{}{This can be lit up to illuminate the immediate surroundings.}

{110}{}{You light the lamp. It's glimmering light barely repels the darkness of the cellars.}
{111}{}{This lamp still has some oil in it. The only thing left is to light it up, to illuminate the basement.}
{112}{}{This lamp's glimmering light is illuminating the basement.}
{113}{}{This lamp is all out of oil.}
{114}{}{The fire and smoke scare the local coyotes.}
