{110}{}{Only Pre-War cash will make the machine release it's contents. Unless you plan to break it open, of course.}
{111}{}{This machine is already broken open.}
{112}{}{}
{113}{}{The lock is too advanced for you.}
{114}{}{Lockpicks inserted. Picking this lock will be easier now.}
{115}{}{The lock already has enough lockpicks in it.}
{116}{}{An electronic decoder is useless when dealing with mechanical locks.}
{117}{}{You have opened up the storage compartment. Time to see what's inside.}
{118}{}{This is pointless now that the machine is broken open.}
{119}{}{You receive mentats.}
{120}{}{The machine is out of mentats.}
{121}{}{}
{122}{}{You fail to bypass the security mechanisms of the machine.}
