{101}{}{This is a newspaper machine. Everything about it is a reminder of the bygone era it was created in.}
{102}{}{The newspaper machine is already broken open.}
{103}{}{The cover is quite tightly closed. Your attempts at opening it don't do a thing.}
{104}{}{You try to open the lock, but it seems that due to filth and rust, it's stuck in place.}
{105}{}{You remove the cover. Now, everything inside of the newspaper machine is yours.}
{106}{}{Today is my lucky day, it seems.}
