{101}{}{It's a newspaper vending machine. With all his appearance, he reminds of a bygone era.}
{102}{}{The newspaper machine has already been opened.}
{103}{}{The lid of the newspaper machine is tightly closed and does not give in.}
{104}{}{The lock does not give in, it is stuck due to dirt and rust.}
{105}{}{You have opened the lid of the newspaper machine. Now everything that lies here belongs to you.}
{106}{}{I'm pretty damn lucky today}