{110}{}{The emitter is damaged and does not work. It cannot be repaired locally.}
{111}{}{This skill won't help here.}
{112}{}{The emitter has been reconfigured to a different frequency.}
{113}{}{You can't figure out the emitter system.}
{114}{}{The force field is on.}
{115}{}{The force field is disabled.}
{116}{}{It will be too difficult to do this during the battle.}
{117}{}{The decoder is connected. Now it will be easier for you to hack this system.}
{118}{}{There is nowhere to connect the second decoder.}
{119}{}{You are unable to reconfigure the power emitter.}