{110}{}{The emitter is damaged beyond repair.}
{111}{}{This skill won't help here.}
{112}{}{Emitter frequency changed.}
{113}{}{You fail to figure out how to change the emitter's systems.}
{114}{}{Force field formed.}
{115}{}{Force field disabled.}
{116}{}{This will be far too complicated to do in combat.}
{117}{}{Decoder installed. Hacking this system will be easier now.}
{118}{}{There's no port for a second decoder.}
{119}{}{You fail to reconfigure the force field emitter.}
