{110}{}{ blocks the passage. With a large force or a package of explosives, you could remove this obstacle.}
{111}{}{You don't have the strength to dismantle this mountain of stones.}
{112}{}{Using brute force, you eliminate the obstacle and free the passage.}
{113}{}{The explosion blows rocks in all directions.}
{114}{}{It seems that heavier weapons are needed here.}
{115}{}{It is impossible to dig during the battle.}
{116}{}{Special equipment is needed here}