{110}{}{ blocks the way. High physical strength or an explosive could get rid of this obstacle.}
{111}{}{You are not strong enough to deal with this pile of rock.}
{112}{}{Your brute force allows you to get rid of the obstacle and clear the way.}
{113}{}{The explosion spreads small pieces of rock in all directions.}
{114}{}{Looks like you're going to need heavier equipment.}
{115}{}{Digging in combat is impossible.}
{116}{}{Specialised tools are needed here.}
