{110}{}{It looks like this }
{111}{}{ short-circuited. But it can still be repaired.}
{112}{}{This one }
{113}{}{ works. And it will work for some more time.}
{114}{}{Have you fixed this one yet }
{115}{}{.}
{116}{}{You have successfully fixed this }
{117}{}{. Now it will give stable light for some more time.}
{118}{}{The repair failed. Maybe you should improve your repair skill.}
{119}{}{You've done something wrong. Try again.}
{120}{}{ due to your incompetence, it finally fails.}