{110}{}{Looks like this }
{111}{}{ was short-circuited. But it can still be repaired.}
{112}{}{This }
{113}{}{ will now work for some time.}
{114}{}{You have already repaired this }
{115}{}{.}
{116}{}{You have successfully repaired this }
{117}{}{. It will now produce stable light for some time.}
{118}{}{Repair attempt failed. Perhaps you should improve your knowledge in the field of repair.}
{119}{}{You did something wrong. Try again.}
{120}{}{, due to your incompetence, shuts down forever.}
