{110}{}{Components from various ammunition are collected here. With developed skills, you can make something useful out of them.}
{111}{}{There is only useless garbage left here.}
{112}{}{With such a skill, you will only spoil the working material.}
{113}{}{Ammunition is made and is in your backpack.}
{114}{}{You have manufactured: }
{115}{}{.}
{116}{}{You've made some fuel.}

{200}{}{Components from various ammunition are collected here. We will have to choose, because the reserves of lead and gunpowder are limited.}
{201}{}{Not now.}
{202}{}{Other.}
{203}{}{Back.}
{204}{}{.}
{205}{}{There are enough components for }
{206}{}{ pcs. (with your current repair skills).}
{207}{}{That's what you need. And now let's get to work!}
{208}{}{Postpone.}