{110}{}{Parts from various types of ammunition are collected here. With high enough skills, they could be turned into something useful.}
{111}{}{Only useless junk is left here.}
{112}{}{With this kind of skill, you're just going to make things worse.}
{113}{}{You make the ammo and put it in your inventory.}
{114}{}{You made: }
{115}{}{.}
{116}{}{You made some fuel.}

{200}{}{Parts from various types of ammunition are collected here. You will have to choose, since the lead and gunpowder supplies are limited.}
{201}{}{Not now.}
{202}{}{Next.}
{203}{}{Previous.}
{204}{}{.}
{205}{}{Components are enough to make }
{206}{}{ units. (with your current repair skill).}
{207}{}{That's more like it.}
{208}{}{Delay.}
