{110}{}{This mini-laboratory is filled with various components. We need knowledge to make something useful out of them.}
{111}{}{This mini-lab is empty. Now it's useless.}
{112}{}{You should have spent more time on chemistry textbooks.}
{113}{}{After much preparation, you have made one stimpack.}
{114}{}{After much preparation, you have made two stimpacks.}
{115}{}{After much preparation, you have made three stimpacks.}
{116}{}{You've made some fuel.}