{110}{}{This mini-laboratory is full of various chemicals. It will take knowledge to turn them into something useful.}
{111}{}{The contents of the mini-laboratory have been used up, making it useless.}
{112}{}{You should have studied chemistry more.}
{113}{}{After a while, you make a stimpak.}
{114}{}{After a while, you make two stimpaks.}
{115}{}{After a while, you make three stimpaks.}
{116}{}{You make some fuel.}
