{100}{}{One-two, check #1.}
{101}{}{One-two, check #2.}
{102}{}{One-two, check #3.}

{110}{}{This granary was completely looted.}
{111}{}{The Town Hall has been vandalized and looted. There are signs of a struggle everywhere.}
{112}{}{This is the only surviving building — a silent witness of ancient times. And it looks like someone has been here recently.}
{113}{}{The checkpoint building was completely looted by slaves.}
{114}{}{Judging by the numerous tracks, the bandits spent several days here waiting for the caravan.}
{115}{}{This shack seems to have been abandoned for a long time, but you notice a few drops of blood on the floor.}
{116}{}{This shack seems to have been abandoned for a long time.}
{117}{}{A long-abandoned and looted drinking establishment. Someone has arranged an overnight stay here.}
{118}{}{An old dilapidated house. It is impossible to live here.}
{119}{}{The building is filled with numerous traces. Apparently, the residents spent a lot of time here.}
{120}{}{The hut of the community leader. The owner kept order even in the midst of all this devastation.}
{121}{}{By entering the club, you attract a lot of attention to yourself. Visitors evaluate you incredulously and soon return to their business.}
{122}{}{This stuffy barrack is saturated with the smells of rust and rubber.}
{123}{}{Peace and quiet reigns in this library.}
{124}{}{The personal office of the Lord of the Phoenix stands out for sophistication and luxury.}
{125}{}{This dark stuffy room is a mess.}
{126}{}{This is your suite. Finally, you can relax after all these tedious journeys.}
{127}{}{This is a suite. It looks impressive against the background of the surrounding hopelessness.}
{128}{}{The road ahead rests against the rubble of destroyed buildings.}
{129}{}{Ugh, this family definitely had something to hide.}
{130}{}{This is a former pumping station. The locals dragged away everything from here that could be used in everyday life.}
{131}{}{This place stands out with a terrible stench.}
{132}{}{The caravaneers have set up a barrack in this old building. It's stuffy, noisy and stinks of sweat.}
{133}{}{This bar has been abandoned and plundered for a long time. It looks like a shootout took place here a long time ago.}
{134}{}{This building has been abandoned for a long time. It looks like there was once a swimming pool here, but now there is not even a drop of water left.}
{135}{}{This large house stands out for its rich decoration and relative cleanliness.}
{136}{}{The road ahead ends in impassable ruins. We'll have to look for a workaround.}
{137}{}{A tall building with lighted windows can be seen ahead. A whole crowd of wild ghouls roams in front of him.}
{138}{}{The sign at the entrance reads: "Open carrying of weapons is prohibited in the casino."}
{139}{}{This supermarket was destroyed by a shock wave. Many of its visitors died on the spot.}
{140}{}{This store was badly damaged by the blast wave. Its walls are about to collapse.}
{141}{}{Further to the south-east, especially destroyed neighborhoods stretch. It looks like there was an epicenter of a nuclear explosion. Nothing survived.}
{142}{}{This administrative building was recently abandoned. The workers even threw their things in a hurry.}
{143}{}{This place reeks of sterile cleanliness. You're not used to this smell. Or rather, to his absence.}
{144}{}{The building of the former hotel has long been abandoned. It looks like someone took everything of value out of here, including furniture.}
{145}{}{The restaurant is gloomy and dirty. It is worth looking carefully at your feet so as not to stumble.}
{146}{}{The basement stinks terribly of urine and old rags.}
{147}{}{It looks like this ancient sewer was dug by someone.}
{148}{}{These containers are completely leaky. Oil spills into the sea, and vapors risk breaking out from any spark.}
{149}{}{There are traces of bare human feet around the lighthouse.}
{150}{}{Further north the road is lost in the sand.}
{151}{}{This is the road you came from Sonora. To go back, wait for the shipment at the collection point.}
{152}{}{The road is blocked by collapses of buildings.}