#Welcome messages in the log at the first visit to the map
# The number is defined as 100+card number by MAPS.TXT
# If the message is not needed, then leave the line empty (without characters and spaces).
# Do not delete empty lines between 100-150! Otherwise, error will appear in the game log.
{100}{}{}
{101}{}{}
{102}{}{}
{103}{}{}
{104}{}{}
{105}{}{}
{106}{}{}
{107}{}{}
{108}{}{}
{109}{}{}
{110}{}{}
{111}{}{}
{112}{}{}
{113}{}{}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}
{120}{}{}
{121}{}{After a long journey, you return to your native village, instead of a warm welcome, you are greeted with sullen silence.}
{122}{}{}
{123}{}{You descend to the cellars. The air is thick with the scent of dampness and the odor of rat droppings}
{124}{}{}
{125}{}{You have come to the Flagstaff Colony. It's unexpectedly crowded here.}
{126}{}{You see a garrison and a colony correctional facility. Behind bars, you find your fellow tribesmen.}
{127}{}{}
{128}{}{Ruins of the old city. The depressing appearance of these ruins does not inspire confidence.}
{129}{}{You are standing at the gates of Garage City. The smell of rust and rubber reeks from this settlement a mile away.}
{130}{}{}
{131}{}{}
{132}{}{The way to the nomads' camp is suddenly blocked by a military detachment.}
{133}{}{You have entered a tribal camp lost among the dunes.}
{134}{}{You have come to the pens. The persistent smell of cattle can be felt already a mile away.}
{135}{}{You have come to the settlement of tinsmiths. Unusual buildings built of aviation equipment can be seen behind the gates.}
{136}{}{}
{137}{}{}
{138}{}{It seems that this bunker has been abandoned for a hundred years.}
{139}{}{Ahead you notice old ruins. Judging by the humid air, there should be a sea behind them.}
{140}{}{You found yourself at a small pier.}
{141}{}{For the first time in your life you were on the deck of a destroyer.}
{142}{}{}
{143}{}{The road led you to the dam. On its top, the ranger bastion is unapproachably located.}
{144}{}{}
{145}{}{}
{146}{}{You have reached a huge city located among ancient ruins. Its gloomy streets greet you with heavy smog.}
{147}{}{}
{148}{}{These slums seem unsafe. You should always be on your guard here.}
{149}{}{An ornate building towers over the city. A crowd of people wander aimlessly in front of it.}
{150}{}{}
{151}{}{}
{152}{}{}
{153}{}{}
{154}{}{}
{155}{}{This place is surrounded by impassable ruins. No wonder it's hard to find.}
{156}{}{The premises of the Vault seem to be emptied. As if everything useful was taken out of here, and for a very long time.}
{157}{}{You have come to the small town of Casa Grande, located in the middle of the caravan route.}
{158}{}{}
{159}{}{}
{160}{}{This place remembers all the horrors of the Great War.}
{161}{}{Before you are the charred ruins of a once large city. Now its streets are flooded with dangerous creatures.}
{162}{}{}
{163}{}{}
{164}{}{You have discovered a small town surrounded by green plantations. There is a lot of life in this oasis.}
{165}{}{In the middle of the desert there is a huge plantation. So familiar to you and at the same time so alien landscape...}
{166}{}{}
{167}{}{A deserted highway leads you to a bandit's lair. It looks like no one is waiting for you here.}
{168}{}{This place looks abandoned, but something about it worries you.}
{169}{}{What a sad sight. This place will be uninhabitable for the next hundred years.}
{170}{}{You went down into the uranium mines.}
{171}{}{A lonely motel appears on the side of the road like a ghost.}
{172}{}{An old high lighthouse on the shore beckons to a casual traveler.}
{173}{}{}
{174}{}{}
{175}{}{}
{176}{}{The echo of your footsteps breaks the silence of the cathedral.}
{177}{}{You see a graveyard of long-forgotten technologies.}
{178}{}{}
{179}{}{You have come to the ancient ruins. No one has lived here for a very long time.}
{180}{}{The shores of Colorado are overgrown with prickly vegetation, in which various game can hide.}
{181}{}{}
{182}{}{Time has not spared this place — dilapidated buildings collapsed, and sandstorms covered the ruins with a layer of sand.}
{183}{}{}
{184}{}{}
{185}{}{}
{186}{}{}
{187}{}{}
{188}{}{You are almost desperate in search of human settlements when suddenly a small ranch appears ahead.}
{189}{}{The desert smoothly turns into dilapidated one-story blocks. It looks like a military garrison has settled here.}
{190}{}{After passing the old quarters, you climb to the fort on the hill of Cerro de la Campana.}
{191}{}{Externally, this old school looks dilapidated and abandoned. Being inside, you should be careful.}
{192}{}{}
{193}{}{}
{194}{}{It looks like the Rangers periodically monitor this water pump. At least it works.}
{195}{}{A surviving building with lighted windows can be seen ahead. A whole crowd of rippers roams in front of him.}
{196}{}{}
{197}{}{}
{198}{}{}
{199}{}{}
{200}{}{}
{201}{}{This place seems completely silent. But at the same time, there is an incredible tension in it.}
{202}{}{}
{203}{}{}
{204}{}{}
{205}{}{}
{206}{}{}
{207}{}{}
{208}{}{}
{209}{}{}
{210}{}{The warehouse building was badly damaged by the shock wave. The main part of the goods must have fallen into disrepair.}
{211}{}{}
{212}{}{It seems that work at this quarry has been urgently suspended.}
{213}{}{}
{214}{}{}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}
{220}{}{It seems that you accidentally stumbled upon a festival.}
{221}{}{You come across an ancient monument that seems to have stood the test of time for many decades if not even more.}
{222}{}{In front of you is an ancient cemetery. So ancient that it is completely overgrown with desert plants.}
{223}{}{}
{224}{}{}
{225}{}{}
{226}{}{}
{227}{}{}
{228}{}{}
{229}{}{}
{230}{}{}
{231}{}{}
{232}{}{}
{233}{}{}
{234}{}{}
{235}{}{}
{236}{}{}
{237}{}{}
{238}{}{}
{239}{}{}
{240}{}{You went down into the cave. If you didn't know the exact coordinates, you would hardly have found it in the middle of Auteuil Park.}
{241}{}{}
{242}{}{}
{243}{}{}
{244}{}{You have entered a radioactive area.}
{245}{}{}
{246}{}{}
{247}{}{}
{248}{}{You have entered a radioactive area.}
{249}{}{}
{250}{}{Before you are barren wastelands.}

{500}{}{You get }
{501}{}{ experience for surviving in the cellars of the Villa.}
{502}{}{Prisoners escaped from the correctional institution!}
{503}{}{You get }
{504}{}{ experience for destroying the Cathedral of the Sacred Fire.}
{505}{}{Until the explosion left }
{506}{}{ seconds.}
{507}{}{You get }
{508}{}{ experience for destroying the Ranger Citadel.}
{509}{}{ experience for destroying the Brotherhood of Steel Fort.}
{510}{}{You illegally entered the headquarters of the Brotherhood of Steel bypassing the sentries at the ramp.}
{511}{}{Now the main thing is not to get burned.}
{512}{}{You get }
{513}{}{ experience for crossing the border.}
{514}{}{ experience for a successful landing on Coronado Island.}
{515}{}{ experience for the final destruction of Coronado Island.}
{516}{}{ experience for the liberation of Coronado Island from military control.}
