{110}{}{Trap!}
{111}{}{You have found a trap.}
{112}{}{ falls into a trap.}
{113}{}{Your abilities have saved you from a dangerous trap.}
{114}{}{}
{115}{}{This trap seems too dangerous.}
{116}{}{The trap has been successfully defused.}
{117}{}{You are afraid that you will not be able to set the trap here correctly.}
{118}{}{The trap is set.}
{119}{}{This trap is currently safe.}
{120}{}{This trap is too dangerous. We'll have to neutralize it first.}
{121}{}{You've shorted out the emitter.}
{122}{}{You couldn't short-circuit the emitter.}
{123}{}{You can set a good trap here.}
{124}{}{You can build a good trap out of this.}
