{100}{}{You have been hit by a rockfall. And you got off easy.}
{101}{}{The mountains are trying to stop you. But you successfully dodge falling rocks.}
{110}{}{You have crossed the irradiated lands and received an increased dose of radiation.}
{120}{}{You are caught in a dust storm!}
{130}{}{You are trying in vain to find water.}
{131}{}{After an exhausting search, you still find some water.}
{132}{}{You managed to avoid dehydration thanks to your own water reserves.}
{133}{}{You managed to avoid dehydration thanks to the supplies from the gift flask.}
{134}{}{There seems to have been an accident here recently. That's what speeding means!}
